### ISSUE TITLE
elixirc_paths: doesn't work with relative path

### ISSUE THREAD

**Issue by mojidabckuu** [elixir-lang/elixir#10016]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 22 [erts-10.6.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.10.3 (compiled with Erlang/OTP 22)

* Operating system: 
Mac OS Catalina

### Current behavior

Probably related to [this issue](https://github.com/elixir-lang/elixir/issues/9896) but running on Mac OS. I have the next line in my `mix.exs` file.
```
  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test),
    do: ["lib", "test/support", "../../payment_method_storage/test/support/factory.ex"]
```
The specified file exists. After migration from 1.7.2 to 1.94/1.10.3 I got in my console
```
** (Mix) Could not find source for "/Users/vladgorbenko/Documents/elixir/scene/payment_method_storage/test/support/factory.ex". Make sure the :elixirc_paths configuration is a list of relative paths to the current project or absolute paths to external directories
```
**Note** If I put absolute path then it works as expected.

### Expected behavior

Expected relative path to compile the file

**Comment by josevalim** [comment]
Correct, the error message says it all: "a list of relative paths to the current project or absolute paths to external directories". The previous behaviour of automatically guessing external directories led to inconsistent compilation, which is why we had to enforce it.

**Comment by mojidabckuu** [comment]
The absolute path is different on each machine, so it won't work. What are the alternatives? Is there any setting to include specific files particularly for test env?

**Comment by josevalim** [comment]
@mojidabckuu you need to use `:path` dependencies then.

**Comment by mojidabckuu** [comment]
`:path` means "include everything under lib directory from the dependency". The case is to import a single file for test env only which contains predefined factory. Using `:path` forces me to put `factory.ex` in lib which will go to production codebase.

**Comment by mojidabckuu** [comment]
If machine asks for an absolute path, then just give it.
`__ENV__.file` returns the absolute path to the current file, then I just played with my included factory path , at the end I got something like this
```elixir
project_path = (__ENV__.file |> String.split("/") |> Enum.drop(-3) |> Enum.join("/"))
my_important_include =  project_path <> "/wow/cool/awesome.ex"
```
