### ISSUE TITLE
Add cross-module support for h/1 in IEx.

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#10021]
Let's say that I'm looking for information on a function, but I don't know which module it's in. Worse yet, I may not even know its arity. Shouldn't h/1 be able to search all of the loaded modules and offer me a selection of possibilities?

**Comment by josevalim** [comment]
@RichMorin as we mention in the issues template, please use the ElixirForum or the mailing list for feature requests. Features like this often come with complexities and limitations, which need to be throughly discussed before they are implemented.
