### ISSUE TITLE
Incorrect documentation for Calendar.TimeZoneDatabase.time_zone_periods_from_wall_datetime/2

### ISSUE THREAD

**Issue by ellispritchard** [elixir-lang/elixir#10036]
*Since 1.8.0*

The documentation for `Calendar.TimeZoneDatabase.time_zone_periods_from_wall_datetime/2` states:
```
If there is only a single possible period for the provided `datetime`, the a tuple with `:single`
  and the `time_zone_period` is returned.
```

This disagrees with the type spec and the implementation in `Calendar.UTCOnlyTimeZoneDatabase`, which returns `{:ok, time_zone_period}` for a single matching period.

https://github.com/elixir-lang/elixir/blob/c88ecdec1655b04f88e3caef22f050bb85740e4c/lib/elixir/lib/calendar/time_zone_database.ex#L62

**Comment by josevalim** [comment]
Yes, it should be call `:ok`. Can you please send a PR? :)

**Comment by ellispritchard** [comment]
Apologies, this was fixed 3 months ago, somehow looking at an earlier ref 🤦
