### ISSUE TITLE
(Mix) httpc request failed with: {:could_no_establish_ssh_tunnel, {'HTTP/1.1', 407, 'authenticationrequired'}}

### ISSUE THREAD

**Issue by jxlczjp77** [elixir-lang/elixir#10039]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Linux ubuntu 4.15.0-100-generic

Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Interactive Elixir (1.10.3) - press Ctrl+C to exit (type h() ENTER for help)
```

### Current behavior

```shell
➜  work mix local.hex
** (Mix) httpc request failed with: {:could_no_establish_ssh_tunnel, {'HTTP/1.1', 407, 'authenticationrequired'}}

Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.
```

### Expected behavior

➜  work echo $http_proxy
http://zzz:%21abcdef2%40@proxyhk.abc.com:8080
➜  work echo $https_proxy
http://zzz:%21abcdef%40@proxyhk.abc.com:8080

**Comment by josevalim** [comment]
It seems that unfortunately we are not being able to handle the ssl tunnel from your proxy. You can run this command to install it manually:

    mix archive.install github hexpm/hex tag v0.20.5

**Comment by josevalim** [comment]
We should probably change the error message to mention the install command above. Although we ideally want to have a "latest" branch on hex and do:

    mix archive.install github hexpm/hex branch latest

/cc @ericmj @wojtekmach

**Comment by josevalim** [comment]
Hi @jxlczjp77, let’s keep this open so we improve the error message. Thanks!
