### ISSUE TITLE
Allow the path to the release vm.args.eex to be configured

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-lang/elixir#10032]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.3-otp-22
* Operating system:  macOS

### Current behavior

Mix releases automatically discovers and uses the vm.args.eex located at `rel/vm.args.eex` if one exists.

### Desired behavior

Allow the path to this file to be explicitly set in the release config.

The reason I am desiring this ability is because I have a project that builds for multiple Mix targets and I need to change the contents of the vm.args file based on the Mix target that I am compiling for. The current workaround I am implementing is to copy the vm.args file I need into the release for the target and add update the target's environment `RELEASE_VM_ARGS=/path/to/custom.vm.args`

I could see this being useful for more than just this file. It might be easiest to allow the location of `rel` to be changed such that we could implement `rel/host` and `rel/target` if we need.

**Comment by josevalim** [comment]
We could have a `rel_path` release config and we get everything from it. And you can set it to `rel/host` and `rel/target` specifically. WDYT? A PR is welcome.

**Comment by mobileoverlord** [comment]
Sounds good, its pretty straight fwd. I'll put something together. Thanks :)

**Comment by josevalim** [comment]
I got to do it after all. In master.
