### ISSUE TITLE
Module dependency not detected a compile time

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#10037]
I'm not certain if this is a bug or working as expected. If the latter then my apologies for the report.

### Environment 

* Elixir 1.10.3 and master, erlang 22.3.3
* Operating system: macOS Catalina

### Current behavior

A module referenced in a Plug configuration is not compiled at compile time in `:test`.  In this [test repo](https://github.com/syfgkjasdkn/cldr-demo), the following error occurs

### Code example
```elixir
defmodule DemoWeb.Router do
  use DemoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :localized do
    plug Cldr.Plug.SetLocale,
      apps: [:cldr, :gettext],
      cldr: Demo.Cldr,  # <-- Error occurs because this module is not compiled when the plug definition is compiled in prod and test
      from: [:query, :accept_language]
  end
  ...
```
### Reproduce the error

```bash
% MIX_ENV=test mix compile
...
==> ex_cldr_units
Compiling 8 files (.ex)
Generated ex_cldr_units app
==> demo
Compiling 16 files (.ex)

== Compilation error in file lib/demo_web/router.ex ==
** (Cldr.UnknownBackendError) The backend Demo.Cldr is not known or not a backend module.
    (ex_cldr 2.14.0) lib/cldr/plug/plug_set_locale.ex:426: Cldr.Plug.SetLocale.validate_cldr/2
    (ex_cldr 2.14.0) lib/cldr/plug/plug_set_locale.ex:119: Cldr.Plug.SetLocale.init/1
...
```
The error does not occur in `:dev` mode, presumably because `Plug.init/1` is called at runtime where as in `:prod` and `:test` its called at compile time.

### Workaround
`require`ing the module forces compilation order.
```elixir
defmodule DemoWeb.Router do
  use DemoWeb, :router
  require Demo.Cldr  # <---- requiring the module forces compilation order
  ...
end
```

```bash
% MIX_ENV=test mix compile
Compiling 16 files (.ex)

16:56:00.929 [info]  Downloaded locale "de"
Generating Demo.Cldr for 4 locales named ["de", "en", "en-001", "root"] with a default locale named "de"
Generated demo app
```
### Expected behavior

The compiler detects the module dependency and compiles it.

**Comment by wojtekmach** [comment]
I wonder if it's because `config :phoenix, :plug_init_mode, :runtime` (https://github.com/syfgkjasdkn/cldr-demo/blob/master/config/dev.exs#L59)

**Comment by kipcole9** [comment]
I just updated the notes to reflect it works fine in `:dev`, its in `:test` that this occurs (and probably in `:prod`) due to the different runtime versus compile time execution of `Plug.init/1` as you note.

**Comment by josevalim** [comment]
Kip, how are you checking if the module exists? It seems you are checking
it in a way that does not guarantee it was compiled, especially within Plug
that works at compile time. It feels your CLDR plug should call
Code.ensure_compiled on the module during its init.

Alternatively, you can change your loaded check to actually invoke a
function on the module: backend.__cldr__, and that will guarantee it is
loaded at runtime or guarantee it is compiled at runtime.

**Comment by kipcole9** [comment]
José, you are right, I'm only calling `Code.ensure_loaded/1`.   No problem at all to change to `Code.ensure_compiled/1` if you think thats appropriate (I try to avoid it given that suggestion in the docks). But given the compile-time behaviour it makes sense.

FWIW here's the current code:
```elixir
    defp validate_app_and_scope!(app, module) when not is_nil(app) and is_atom(module) do
      cond do
        app in @app_options && Code.ensure_loaded?(module) ->
          :ok

        app in @app_options ->
          raise ArgumentError, "Backend module #{inspect(module)} is unavailable"

        true ->
          raise ArgumentError, "App #{inspect(app)} is unknown"
      end
    end
```

**Comment by josevalim** [comment]
You do want to avoid it but given you are trying to verify it at compile-time, then at least on this case you shouldn't. Closing this for now but feel free to follow up if you have questions.
