### ISSUE TITLE
Registry's handle_call(:sync, _, state)

### ISSUE THREAD

**Issue by balena** [elixir-lang/elixir#10047]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.3 (compiled with Erlang/OTP 21)
* Operating system: Mac OS Mojave

### Current behavior

Everything is working, nice and smooth.

### Expected behavior

However I believe there is a dangling `handle_call(:sync, _, state)` function call in the `Registry.Partition` implementation. I believe it is not called, or at least I couldn't find anything calling it from the code.

This is not urgent, and it won't harm leaving it there.

**Comment by ericmj** [comment]
It seems to be used for testing: https://github.com/elixir-lang/elixir/blob/480c3a30be61b260b3b95f42ba12e24434103159/lib/elixir/test/elixir/registry_test.exs#L823.
