### ISSUE TITLE
Compiling a library that defines a protocol that has implementation in other dependencies issues a warning

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#10042]
### Environment

* Elixir & Erlang/OTP: Elixir 1.11.0-dev, erlang 23
* Operating system: macOS Catalina
 
### Current behavior

Compiling a library that defines a protocol that has implementation in other dependencies issues a warning.  For example, using [ex_cldr_units](https://hex.pm/packages/ex_cldr_units) the following occurs. Note that the warning is issued during compilation of `ex_cldr` which is a transitive dependency of `ex_cldr_numbers` which is defined in the `mix.exs` of `ex_cldr_units`.

In the below:
1. `ex_cldr_numbers` is a direct dependency of `ex_cldr_units`
2. `ex_cldr` is a transitive dependency of `ex_cldr_numbers`
3. `ex_cldr_lists` is a direct dependency of `ex_cldr_units`
4. The protocol `Cldr.Chars` is defined in `ex_cldr`
5. Implementations of `Cldr.Chars` are in the respective packaged `ex_cldr_units`, ex_cldr_numbers` and `ex_cldr_lists`
6. All of these are library apps, not OTP apps in the classical sense (they have no `use Application`)

```bash
==> ex_cldr
Compiling 2 files (.erl)
Compiling 30 files (.ex)
warning: Cldr.Chars.List.__impl__/1 defined in application :ex_cldr_lists is used by the current application but the current application does not directly depend on :ex_cldr_lists. To fix this, you must do one of:

  1. If :ex_cldr_lists is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :ex_cldr_lists is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :ex_cldr_lists, you may optionally skip this warning by adding [xref: [exclude: Cldr.Chars.List] to your "def project" in mix.exs

  lib/cldr/protocol/cldr_chars.ex:3: Cldr.Chars.impl_for/1

warning: Cldr.Chars.Float.__impl__/1 defined in application :ex_cldr_numbers is used by the current application but the current application does not directly depend on :ex_cldr_numbers. To fix this, you must do one of:

  1. If :ex_cldr_numbers is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :ex_cldr_numbers is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :ex_cldr_numbers, you may optionally skip this warning by adding [xref: [exclude: Cldr.Chars.Float] to your "def project" in mix.exs

  lib/cldr/protocol/cldr_chars.ex:3: Cldr.Chars.impl_for/1

warning: Cldr.Chars.Integer.__impl__/1 defined in application :ex_cldr_numbers is used by the current application but the current application does not directly depend on :ex_cldr_numbers. To fix this, you must do one of:

  1. If :ex_cldr_numbers is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :ex_cldr_numbers is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :ex_cldr_numbers, you may optionally skip this warning by adding [xref: [exclude: Cldr.Chars.Integer] to your "def project" in mix.exs

  lib/cldr/protocol/cldr_chars.ex:3: Cldr.Chars.impl_for/1

Generated ex_cldr app
```
Mix.exs is:
```elixir
  defp deps do
    [
      {:ex_cldr_numbers, "~> 2.13"},
      {:ex_cldr_lists, "~> 2.5"},
      {:ratio, "~> 2.4"},
      {:decimal, "~> 1.6 or ~> 2.0", optional: true},
      {:dialyxir, "~> 1.0", only: [:dev], runtime: false},
      {:ex_doc, "~> 0.18", only: [:dev, :release]},
      {:jason, "~> 1.0", optional: true},
      {:sweet_xml, "~> 0.6", only: [:dev, :test], optional: true}
    ]
  end
```

### Expected behavior

These warning don't appear since they are not relevant (as best I can tell)

**Comment by josevalim** [comment]
Hi @kipcole9, which master commit are you using? I have cloned `ex_cldr_units` and run `mix deps.get` and I could not reproduce this. I have also tried using `ex_cldr_units` as a dep and everything worked. Can you also try removing `_build` and making sure the warnings still appear? Thanks.

**Comment by kipcole9** [comment]
Thats very embarrassing José, of course I should delete the `_build` dir before building on master and I did not.

There is no error now. Sorry for wasting your time.

**Comment by josevalim** [comment]
No problem at all. :)
