### ISSUE TITLE
Protocol for writing key/value data

### ISSUE THREAD

**Issue by jjl** [elixir-lang/elixir#10044]
I find myself trying to abstract harder than the standard library would like me to again.

In particular, for reading, we have both the Enumerable trait and the `Access` behaviour. Even if we pretend for a moment that Collectable is anywhere near as useful as Enumerable (which has a huge advantage both in terms of methods and of wrapping functions), there isn't even a simple inverse to `Access`. This leaves us in a curious circumstance where we can abstract away reading keyed data, but not able to write it.

I think there's quite a lot we could do here, but a minimum proposal would be a `Keyed` protocol or behaviour with a single 3-arity `put` method. We could demand that implementors of `Keyed` implement `Access` too and maybe add `update`.

Thoughts?

**Comment by jjl** [comment]
Oh, and it would be nice if Collectables had the ability to produce an empty version of themselves.

**Comment by josevalim** [comment]
Please use the mailing list for proposals, as more people will be able to engage the discussion there.

Also, note that you can store things with the Access protocol. Although there is no “put” API, you can do it with get_and_update. Creating a high level API on top of it is trivial and is done in places such as put_in.
