### ISSUE TITLE
Define a user-type named union crash on generate docs and get function docs on IEX

### ISSUE THREAD

**Issue by Cleidiano** [elixir-lang/elixir#10054]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.3-otp-22
* Operating system: Linux Mint 19.3

### Current behavior
To reproduce:
- Create a simple project, 
- Include `:ex_doc` dependency, 
- Define a module as bellow and than 
- run mix docs
```elixir
defmodule Example do
  @moduledoc """
  Documentation for Example.
  """

  @doc """
  Hello world.

  """
  @type union :: any()

  @spec hello :: union()
  def hello do
    :world
  end
end
```

```bash
** (Enum.EmptyError) empty error
    (elixir 1.10.3) lib/enum.ex:2057: Enum.reduce/2
    (elixir 1.10.3) lib/code/typespec.ex:21: Code.Typespec.spec_to_quoted/2
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc 0.22.1) lib/ex_doc/retriever.ex:285: ExDoc.Retriever.get_function/4
    (ex_doc 0.22.1) lib/ex_doc/retriever.ex:238: anonymous fn/6 in ExDoc.Retriever.get_docs/3
    (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc 0.22.1) lib/ex_doc/retriever.ex:237: ExDoc.Retriever.get_docs/3
    (ex_doc 0.22.1) lib/ex_doc/retriever.ex:136: ExDoc.Retriever.do_generate_node/3

```
### Expected behavior
The documentation should be generated;

**Comment by Cleidiano** [comment]
I have look at the typespec module code base and it's caused by
https://github.com/elixir-lang/elixir/blob/50995e66404fee889846db7343705f881b2a3f25/lib/elixir/lib/code/typespec.ex#L300
adding a guard to ensure that isn't a empty args should be enough.
If this behaviour isn't desired, let me know that I could submit a PR.

**Comment by michalmuskala** [comment]
I think the issue is that `union()` should be compiled into a `:user_type` AST node instead of the `:type` node it compiles to right now

**Comment by Cleidiano** [comment]
It's compiled into `:user_type` right now, the flip at occurs at https://github.com/elixir-lang/elixir/blob/50995e66404fee889846db7343705f881b2a3f25/lib/elixir/lib/code/typespec.ex#L219

**Comment by wojtekmach** [comment]
Does the crash occur just in ExDoc, or when doing `iex> h ` too? If just in ExDoc, could you transfer the issue to that repo?

**Comment by Cleidiano** [comment]
It occours ant `iex>` h too.

**Comment by Cleidiano** [comment]
A possible solution is to annotate the name of `user_type` at line `220` and handle it at https://github.com/elixir-lang/elixir/blob/50995e66404fee889846db7343705f881b2a3f25/lib/elixir/lib/code/typespec.ex#L326
