### ISSUE TITLE
unquote called outside of quote

### ISSUE THREAD

**Issue by heavyk** [elixir-lang/elixir#10057]
### Environment

  * Elixir & Erlang versions (elixir --version): Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.3 (compiled with Erlang/OTP 22)

  * VSCode ElixirLS version: 0.4.0
  * Operating System Version: darwin 19.4.0
  
### Current behavior

```ex
defmodule MacroTesting.TryUsing do
  defmacro __using__(_) do
    quote [
      location: :keep,
      bind_quoted: [] # if I comment this out, it works
    ] do
      import unquote(__MODULE__)

    end
  end
end

defmodule MacroTesting do
  use MacroTesting.TryUsing
  def hello do
    :world
  end
end
```

yields:
```
== Compilation error in file lib/macro_testing.ex ==
** (CompileError) lib/macro_testing.ex:7: unquote called outside quote
    expanding macro: MacroTesting.TryUsing.__using__/1
    lib/macro_testing.ex:14: MacroTesting (module)
    (elixir 1.10.3) expanding macro: Kernel.use/1
    lib/macro_testing.ex:14: MacroTesting (module)
```

commenting the empty bind_quoted line out and it will work

---

I did a search for the bug, but I couldn't find any other cases where this was happening to anyone else, here or on the internet. I'm also not sure if it's a bug and I'm just doing it wrong, because it seems such a common use case

**Comment by maennchen** [comment]
@heavyk 

https://hexdocs.pm/elixir/Kernel.SpecialForms.html#quote/2-options

> `:bind_quoted` - passes a binding to the macro. Whenever a binding is given, `unquote/1` is automatically disabled.

**Comment by heavyk** [comment]
oh, so I should pass __MODULE__ into the bind quoted? dang... I didn't realise that. perhaps then I could make a PR to improve the error message...

I just tried it and
```ex
defmodule MacroTesting.TryUsing do
  defmacro __using__(_) do
    quote [
      location: :keep,
      bind_quoted: [mod: __MODULE__] # if I comment this out, it works
    ] do
      import mod
    end
  end
end
```

now yields,
```
== Compilation error in file lib/macro_testing.ex ==
** (CompileError) lib/macro_testing.ex:7: invalid argument for import, expected a compile time atom or alias, got: mod
    expanding macro: MacroTesting.TryUsing.__using__/1
    lib/macro_testing.ex:13: MacroTesting (module)
    (elixir 1.10.3) expanding macro: Kernel.use/1
    lib/macro_testing.ex:13: MacroTesting (module)
```

**Comment by josevalim** [comment]
In this case it is best to skip bind_quoted and use unquote for everything. Or split into two quotes, one with bind_quoted and one without. But the behavior is expected and documented. :)
