### ISSUE TITLE
`h ()` gives a warning AND valid documentation

### ISSUE THREAD

**Issue by tverlaan** [elixir-lang/elixir#10066]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.3
* Operating system: MacOS

When entering `h ()` in IEx I get both a warning and a nice explanation about the __block__ macro. It is not so much a problem but perhaps we could make the experience a bit nicer by not showing the warning and only displaying the documentation of `__block__`.

```
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.10.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> h ()
warning: invalid expression (). If you want to invoke or define a function, make sure there are no spaces between the function name and its arguments. If you wanted to pass an empty block, pass a value instead, such as a nil or an atom
  iex:1


                            defmacro __block__(args)

Internal special form for block expressions.

This is the special form used whenever we have a block of expressions in
Elixir. This special form is private and should not be invoked directly:

    iex> quote do
    ...>   1
    ...>   2
    ...>   3
    ...> end
    {:__block__, [], [1, 2, 3]}

iex(2)>
```

Entering empty parentheses in IEx directly also produces the warning and has as result `nil`. I'm not sure if the warning helps in this situation. I was using `()` to copy some multiline code from my editor into the iex console.
To be complete:
```
iex(2)> ()
warning: invalid expression (). If you want to invoke or define a function, make sure there are no spaces between the function name and its arguments. If you wanted to pass an empty block, pass a value instead, such as a nil or an atom
  iex:2

nil
iex(3)>
```

**Comment by josevalim** [comment]
I understand the confusion. Our preference would be to raise if `()` is used but that would be a backwards incompatible change. So it has to continue emitting `nil` instead of just failing. This will be fixed when we launch Elixir 2.0 (not plans for it though) and convert the deprecation to an error. :)
