### ISSUE TITLE
Add new! to Date/Time/NaiveDateTime/DateTime

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#10063]
Currently Date/Time/NaiveDateTime have non-bang versions, so we will add the `!` ones. For DateTime, we will add new/3, which expects a `date, time, time_zone`, similar to `DateTime.from_naive` but with only date and time, as well as the bang variant.

**Comment by fertapric** [comment]
I think `new/*` should also accept a `time_zone_database \\ Calendar.get_time_zone_database()` as a fourth argument to fill the offset info.

**Comment by josevalim** [comment]
Closing in favor of PR.
