### ISSUE TITLE
extname function on Path module instead of File

### ISSUE THREAD

**Issue by 0x2C6** [elixir-lang/elixir#10076]
Why function extname placed on the Path module instead of the File module?  Because I think File.extname is more self-descriptive instead of Path.extname where we send file name as a string.
Is there any discussion or plan about it? Probably it's not "have to do" but "would be good" to make. As I developer who needs it probably would first look to the File module.

P.S:
It is not a feature and I thought no need to write it to the mailing list. Can be closed if it's not in the future plans

**Comment by josevalim** [comment]
File functions generally go through the file system. We have no plans to change this, unless there is a compelling reason. :)
