### ISSUE TITLE
`--warnings-as-errors` exits with a zero exit code (it should exit with a non-zero exit code)

### ISSUE THREAD

**Issue by alizain** [elixir-lang/elixir#10073]
### Environment

* **Elixir & Erlang/OTP versions:**

    `elixir --version`
    ```
    Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
    Elixir 1.10.3 (compiled with Erlang/OTP 22)
    ```

    `.tool-versions`
    ```
    elixir 1.10.3-otp-22
    erlang 22.2.8
    ```

* **Operating system:**

    ```
    macOS 10.15.5
    ```

### Current behavior

When compiling with `mix compile --force --warnings-as-errors`, any warning should cause a non-zero exit code. Instead, the compiler is currently exiting with a `0` exit code.

The warning in my application is:

```
warning: Repo.preload/2 is undefined (module Repo is not available or is yet to be defined)
```

I can reproduce this bug in `1.10.0` and `1.10.2` Elixir versions as well.

Here's the simplest example that triggers this behaviour:

```elixir
defmodule ModuleNotAvailable do
  def hello do
    Something.not_here()
  end
end

```

### Expected behavior

The compiler should exit with a non-zero exit code. I can confirm that `1.9.4` is working correctly.

**Comment by alizain** [comment]
To add more context:

```
defmodule WarningsAsErrors do
  def hello do
    unused = 1

    3
  end
end
```

```
warning: variable "unused" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/warnings_as_errors.ex:16: WarningsAsErrors.hello/0
```

Unused variables correctly returns a non-zero exit code

**Comment by alizain** [comment]
```
defmodule WarningsAsErrors do
  def hello(_something) do
    1
  end

  def hello(another) do
    another
  end
end
```

```
warning: this clause cannot match because a previous clause at line 2 always matches
  lib/warnings_as_errors.ex:6
```

This warning works correctly too

**Comment by josevalim** [comment]
Thank you, this has been fixed on ead8cf610141f537dcc52be858770d8000753058.

**Comment by alizain** [comment]
Ah, gotcha. I had found this commit (and the linked issue) before opening this issue, but I had assumed that since this commit occurred on Feb 29 and `1.10.3` was released on April 25, this would already be in there. After checking, it looks like this commit has not been released yet.

Do you have an approximate ETA of when it will be released?

This bug is breaking our CI infra - we rely on warnings to help catch classes of bugs.

**Comment by josevalim** [comment]
Unfortunately it requires some other changes done in master, so it will be released with Elixir v1.11 that comes in Sep/Oct this year.

**Comment by adrianomitre** [comment]
I stumbled upon the same bug.

Here is some more evidence I collected before finding this issue:
- https://github.com/adrianomitre/warning_as_errors_bug_in_elixir_1_10_x/runs/924168226 <- fails, as it should, in all versions below 1.10

**Comment by eksperimental** [comment]
> I stumbled upon the same bug.
> 
> Here is some more evidence I collected before finding this issue:
> 
>     * https://github.com/adrianomitre/warning_as_errors_bug_in_elixir_1_10_x/runs/924168226 <- fails, as it should, in all versions below 1.10

the commit ead8cf610141f537dcc52be858770d8000753058 is only in master, no other branch. So you will see the error in 1.10 and older versions

**Comment by adrianomitre** [comment]
For the specific deprecated warnings of the referred project, the bug is
absent in versions older than 1.10 (at least from 1.5, the oldest I tested).

Em qua, 29 de jul de 2020 22:45, Eksperimental <notifications@github.com>
escreveu:

**Comment by adrianomitre** [comment]
@alizain I do not know if you already worked around this issue, but let me share two workarounds I came up with:
- If your project also compiles in Elixir 1.9, you can do like I did in https://github.com/michalmuskala/jason/pull/112
- If not, you can scan the stderr, like I did in https://github.com/adrianomitre/warning_as_errors_bug_in_elixir_1_10_x/pull/1
