### ISSUE TITLE
Tab completion with casing error fails with beam_load.c error

### ISSUE THREAD

**Issue by jeroenvisser101** [elixir-lang/elixir#10071]
### Environment

Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 23)

macOS 10.15.4

This issue also happens on OTP 22.

### Current behavior
Triggering autocomplete after not typing the module name correctly results in a error:

```
iex(1)> DAtetime.<tab>
[error] pid=<0.50.0>  >> Loading of ~/.asdf/installs/elixir/1.10.3-otp-23/bin/../lib/elixir/ebin/Elixir.DAtetime.beam failed: :badfile

[error] pid=<0.50.0>  >> beam/beam_load.c(1440): Error loading module 'Elixir.DAtetime':
  BEAM file exists but it defines a module named Elixir.DateTime
```

### Expected behavior

No error, just no completion.

**Comment by josevalim** [comment]
Unfortunately simply asking the VM does this module exists emits this warning. There is nothing we can do to address this, especially given that some filesystems are case insensitive. Sorry.

**Comment by jeroenvisser101** [comment]
Ah, no worries, just couldn't find a report and wanted to see if it was fixable, and I never had this happen before

All good, thanks for checking!
