### ISSUE TITLE
Internal consistency check failed

### ISSUE THREAD

**Issue by DanielDent** [elixir-lang/elixir#10084]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
   * Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
   * Elixir 1.10.3 (compiled with Erlang/OTP 21)
* Operating system: Debian Testing (updated within last 24 hours)

### Current behavior

```
== Compilation error in file lib/file_name_here/file_name_here.ex ==
** (CompileError) Elixir.FileNameHere: function parse/2+1601:
  Internal consistency check failed - please report this bug.
  Instruction: {test,is_eq_exact,{f,772},[{x,1},{atom,true}]}
  Error:       {uninitialized_reg,{x,1}}:

    (stdlib 3.13) lists.erl:1338: :lists.foreach/2
    (elixir 1.10.3) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
    (elixir 1.10.3) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

I'm unclear if this is a packaging issue or a genuine bug. I'm using what currently gets installed from the erlang-solutions Debian packages (note the version mismatch OTP21 vs OTP23).

Normally this code base is used with the following versions (from Docker tag `elixir:1.10-slim`):
   * Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
   * Elixir 1.10.3 (compiled with Erlang/OTP 22)

On those versions, it compiles fine.

**Comment by wojtekmach** [comment]
Could you show the file that crashes the compiler and/or narrow it down to minimal amount of code?

**Comment by DanielDent** [comment]
I've managed to narrow it down to a small amount of code. It's significantly changed from what I started with, but it still produces the same crash.

https://github.com/DanielDent/elixir_issue_10084/blob/master/lib/issue_demo.ex

Here's what happens for me with a fresh checkout of that repo:

```
$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  typed_struct 0.2.0
* Getting typed_struct (Hex package)

$ mix
==> typed_struct
Compiling 2 files (.ex)
Generated typed_struct app
==> elixir_issue_10084
Compiling 2 files (.ex)

== Compilation error in file lib/issue_demo.ex ==
** (CompileError) Elixir.IssueDemo: function i_am_a_function/1+27:
  Internal consistency check failed - please report this bug.
  Instruction: {test,is_eq_exact,{f,27},[{x,3},{atom,true}]}
  Error:       {uninitialized_reg,{x,3}}:

    (stdlib 3.13) lists.erl:1338: :lists.foreach/2
    (elixir 1.10.3) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
```

**Comment by DanielDent** [comment]
I've added a Dockerfile which reproduces the issue. `docker build .` on that repo gets the same error.

**Comment by josevalim** [comment]
Reproduced and reported upstream with a minimal case: https://bugs.erlang.org/browse/ERL-1276

Thanks!
