### ISSUE TITLE
Mix dependency compilation order does not consider optional dependencies

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#10099]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.1 (compiled with Erlang/OTP 20)

* Operating system: Manjaro x64 Linux

### Reproducible situation

The situation arises when creating an application with two dependencies, where one of the dependencies lists the other dependency as `optional: true`.

A practical example: Say we are writing an application that depends on `norm` and wants to use the extra functionality provided by `stream_data`. (c.f. https://github.com/keathley/norm/issues/46 )

So in our application's `mix.exs`, we have 
```
      {:stream_data, "~> 0.5"},
      {:norm, "~> 0.10"},
```

In Norm's [`mix.exs`](https://github.com/keathley/norm/blob/master/mix.exs#L34) we have:

```
  {:stream_data, "~> 0.5", optional: true, only: [:dev, :test]},
```

In our application, we have some code that uses [the functionality that Norm adds at compile-time if `stream_data` is available](https://github.com/keathley/norm/blob/master/lib/norm/generatable.ex#L8), like calling `Norm.Generatable.gen(:foo)`.

### Current behavior

`norm` is compiled before `stream_data`. I think Mix sees them as dependencies that are not inter-dependent and thus compiles them in an arbitrary order (which currently defaults to alphabetical).

### Expected behavior

Mix seems to disregard the optional dependency `norm` has on `stream_data`. I would expect Mix to realize that this optional dependency means that `stream_data` should be compiled before `norm` to make sure that optional features are compiled correctly.

**Comment by josevalim** [comment]
Can you please provide an application that reproduces the error?

**Comment by josevalim** [comment]
Also, can you please try it on latest Elixir? Or at least latest v1.9.x?

**Comment by Qqwy** [comment]
Here you go: (This is on Erlang/OTP 23, Elixir v 1.10.3) https://github.com/Qqwy/elixir-mix-compilation-order-example

Run:
```
$ mix deps.get
$ iex -S mix
iex> MixCompilationOrderExample.hello
```

**Comment by josevalim** [comment]
Here is the issue: https://github.com/keathley/norm/blob/master/mix.exs#L34

stream_data is actually not an optional dependency in prod, which is the default environment of all deps. Removing the `:only` flag should fix it. :)

**Comment by josevalim** [comment]
And thanks for the app!

**Comment by Qqwy** [comment]
Thank you for the quick response! :smile:
