### ISSUE TITLE
mix app.start should warn if the application has a supervision tree and root is not a supervisor

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#10096]
This will help catch bugs as in https://github.com/phoenixframework/phoenix_live_dashboard/issues/156. Here is how we can perform those checks:

https://github.com/phoenixframework/phoenix_live_dashboard/blob/f44578da1ae39026eb03ca74d0b7e7f5c3cb1668/lib/phoenix/live_dashboard/system_info.ex#L254-L260

**Comment by kelvinst** [comment]
I can tackle this if no one has already planned to 🙂

**Comment by josevalim** [comment]
All yours!

**Comment by kelvinst** [comment]
Just wanted to point I have started it, but the check you mentioned would not work if the root process is not a gen_server, as the `call` made on [`:supervisor.which_children`](https://github.com/phoenixframework/phoenix_live_dashboard/blob/f44578da1ae39026eb03ca74d0b7e7f5c3cb1668/lib/phoenix/live_dashboard/system_info.ex#L285) do not have a timeout...

We could do a `GenServer.call(root_process, :which_children, 500)` (or maybe a `:count_children`, as it probably would be a lot faster), but I don't think that is the most reliable way to define if a process is a supervisor or not.

Do you guys know if there is any other way to check that?

**Comment by maennchen** [comment]
@kelvinst I think that the proposed check would be very bad since a lot of GenServers don't define a fallback `handle_call` which would therefore crash the process.

I have no idea for a better check however.

**Comment by maennchen** [comment]
One characteristic I found is in the process dictionary under `$initial_call`:

```elixir
iex> Process.info(GenServer.whereis(Acme.Supervisor))
[
  registered_name: Acme.Supervisor,
  current_function: {:gen_server, :loop, 7},
  initial_call: {:proc_lib, :init_p, 5},
  status: :waiting,
  message_queue_len: 0,
  links: [#PID<0.767.0>, #PID<0.769.0>],
  dictionary: [
    "$initial_call": {:supervisor, Supervisor.Default, 1},
    "$ancestors": [#PID<0.767.0>]
  ],
  trap_exit: true,
  error_handler: :error_handler,
  priority: :normal,
  group_leader: #PID<0.766.0>,
  total_heap_size: 1974,
  heap_size: 987,
  stack_size: 11,
  reductions: 1506,
  garbage_collection: [
    max_heap_size: %{error_logger: true, kill: true, size: 0},
    min_bin_vheap_size: 46422,
    min_heap_size: 233,
    fullsweep_after: 65535,
    minor_gcs: 1
  ],
  suspending: []
]
```

**Comment by josevalim** [comment]
> @kelvinst I think that the proposed check would be very bad since a lot of GenServers don't define a fallback handle_call which would therefore crash the process.

However, this would only happen if the root process is not a supervisor, which would be a bug. So we would crash, but the user code is also wrong. The question is: is this an acceptable trade-off?

**Comment by kelvinst** [comment]
> One characteristic I found is in the process dictionary under $initial_call:

Yeah, I was thinking about the `$initial_call` too @maennchen, but I guess all the elements of the tuple can be customised by the user (except for the argument count). Maybe we can do check if the supervisor module implements a given behaviour though, IDK.

> However, this would only happen if the root process is not a supervisor

I think I was not clear about the problem sorry, `:supervisor.which_children(root_proc)` only fail when the process is a GenServer, when it is not a GenServer at all it hangs undefinitely, as the call made on it do not have a timeout.

**Comment by kelvinst** [comment]
You can easily check that with: `fn -> Process.sleep(10000) end |> spawn() |> :supervisor.which_children()`

**Comment by josevalim** [comment]
I see. I guess it is best to leave it be then, as even with the timeout it would lead to a wait. Thanks for investigating!
