### ISSUE TITLE
I can not able to create new project using mix new command

### ISSUE THREAD

**Issue by shrutimandaliya** [elixir-lang/elixir#10107]
I got error like below

mix new project1
** (Mix) Application name must start with a letter and have only lowercase letters, numbers and underscore, got: "Project1". The application name is inferred from the path, if you'd like to explicitly name the application then use the "--app APP" option.

**Comment by josevalim** [comment]
Correct! As the error messages says, the project name must only have lowercase letters, so use “project1” instead of “Project1” :) have fun!
