### ISSUE TITLE
GenServer.whereis/1 is returning pid for pid of process not associated with any server

### ISSUE THREAD

**Issue by DominikWolek** [elixir-lang/elixir#10106]
### Environment

```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```

### Current behavior

```elixir
iex> pid = spawn fn -> 0 end
#PID<0.108.0>
iex> GenServer.whereis(pid)
#PID<0.108.0>
```

### Expected behavior

```elixir
iex> pid = spawn fn -> 0 end
#PID<0.108.0>
iex> GenServer.whereis(pid)
nil
```

Or, perhaps, change the spec of `GenServer.whereis/1` from
```elixir
whereis(server()) :: pid() | {atom(), node()} | nil
```
to 
```elixir
whereis(name() | {atom(), node()}) :: pid() | {atom(), node()} | nil
```

**Comment by whatyouhide** [comment]
Thanks for the report @DominikWolek! Why would the expected behavior be to return `nil`? `pid` is associated with the given `pid`, after all?

**Comment by DominikWolek** [comment]
@whatyouhide 
From documentation:
> Returns the `pid` or `{name, node}` of a GenServer process, or `nil` if no process is associated with the given server.

Returned `pid` is not `pid` of a GenServer process (despite being associated with itself). 

If I pass `name` not associated with any server, `whereis/1` will return `nil`. I would like to expect the same for `pid`.

**Comment by josevalim** [comment]
We could do a `Process.alive?` check but I am not sure if it would solve any problem. The other option is to clarify the docs (which are ambiguous today). @DominikWolek can you please tell us a bit more about your scenario?

**Comment by DominikWolek** [comment]
@josevalim there is no real-life scenario - I just found ambiguity (or mismatch) in documentation during my testing course's project.

I don't really see a scenario for using `whereis/1` on `pid` (even `pid` of server's process), either.

**Comment by josevalim** [comment]
@DominikWolek it is useful when you want to accept any of the formats and convert them to something you can pass to `send/2`. Otherwise you need to pattern match and handle `pid`s explicitly before.

**Comment by DominikWolek** [comment]
@josevalim ok. In that case, this is minor ambiguity in `GenServer` documentation.
