### ISSUE TITLE
Private types references from public ones

### ISSUE THREAD

**Issue by smaximov** [elixir-lang/elixir#10103]
Hello, sorry in advance if it's not a kind of question to ask here. 

I just noticed that some public Elixir types reference private types (e.g., [`Exception.kind/0`](https://hexdocs.pm/elixir/Exception.html#t:kind/0) references private `non_error_kind/0`). Is this intended? It seems like it would make sense to make these private types opaque if they are indeed private, or make them public otherwise.

**Comment by josevalim** [comment]
Fixed, thanks!
