### ISSUE TITLE
How to disable warnings about unused variables?

### ISSUE THREAD

**Issue by GildedHonour** [elixir-lang/elixir#10115]
This doesn't work 
```
defmodule M1 do
  @compile :nowarn_unused_vars
  # ........
end
```

I want to disable them on the level **of the compiler**, per file, project or globally.

**Comment by GildedHonour** [comment]
```
% iex --version
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

IEx 1.10.2 (compiled with Erlang/OTP 22)
```

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

PS: It is not possible on purpose. You have to prefix the variables names to underscore (or assigns them to underscore).

**Comment by GildedHonour** [comment]
> PS: It is not possible on purpose. You have to prefix the variables names to underscore (or assigns them to underscore).

I'm cross with you.

**Comment by maoyanyonghu** [comment]
see this file lib/elixir/src/elixir_env.erl
at line 141 - 148
`            case not_underscored(Name) of
              true ->
                Warn = {unused_var, Name},
                elixir_errors:form_warn([{line, ClauseValue}], ?key(E, file), ?MODULE, Warn);

              false ->
                ok
            end,
`

you can change this code and recompile.

**Comment by lukaszsamson** [comment]
> PS: It is not possible on purpose. You have to prefix the variables names to underscore (or assigns them to underscore).

I see your point but we are having an issue with some macro generated code (https://github.com/appsignal/appsignal-elixir transaction decorators). The underlying issue is in the decorator lib https://github.com/arjan/decorator/issues/31 but the not needed warnings emerge in client code.

**Comment by michalmuskala** [comment]
The "trick" to silence those warnings for maco-generated variables is to add a dummy usage, e.g.:

```elixir
quote do
  var!(state) = build_state_for_user_they_might_not_use()
  _ = var!(state)
  unquote(user_code)
end
```

This pattern is used pretty frequently in stdlib macros

**Comment by lukaszsamson** [comment]
@michalmuskala in our case the variable IS used and the warning is still generated

```
@impl true
@decorate channel_action()
def handle_in(
      "some_message",
      %{"id" => id},
      %{assigns: %{current_user: current_user}} = socket
    ) do
  do_sth(id, current_user)

  {:reply, :ok, socket}
end
```

```
variable "current_user" is unused (if the variable is not meant to be used, prefix it with an underscore)
```

**Comment by ericmj** [comment]
@lukaszsamson That would be a bug. Please open an issue and include a project or file that reproduces the issue.

**Comment by lukaszsamson** [comment]
@ericmj yes, and as I already wrote it is a bug in a dependency https://github.com/arjan/decorator/issues/31.
While I know I'm dealing with a bug that is unlikely to be fixed I would like to silence the annoying warning.

**Comment by ericmj** [comment]
If the warning was incorrect or no reasonable fix existed for then we could consider adding a way to disable it. But in this case there is a fix which is not being done so the warning is correct and should remain until fixed.
