### ISSUE TITLE
Appending a number to an empty list returns a string

### ISSUE THREAD

**Issue by NathanGrimaud** [elixir-lang/elixir#10123]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 22)

* Operating system: 
Linux (Manjaro)

### Current behavior

When I'm trying to append a number to an empty list, it sometimes returns a letter

`iex(1)> [0 | []]
[0] 
iex(2)> [1 | [0]]
[1, 0]
iex(3)> [71 | []]
'G'
iex(4)> [71 | [0]]
[71, 0]

iex(1)> [] ++ [0]
[0]
iex(2)> [] ++ [71]
'G'
`
Many numbers creates this issue, from 7 to 13, 31 to 126
You can see each case with this line: 
`1..1000 |> Enum.each(fn number -> IO.inspect([number | []]) end)`

Every thing work as intended when the enum we are appending a number to is not empty.

### Expected behavior
I might be doing something wrong but I guess it should always return a list.

Thanks for your help !

**Comment by adkron** [comment]
This is actually a side affect of using a integer is the ASCII range. You are causing the console to print a charlist. That is how Erlang implements strings. It is still a list of codepoints. You can recognize a charlist from a String because of the ticks. Single tick is charlist and double tick is String.

**Comment by fertapric** [comment]
As @adkron explained, that's an expected behaviour.

Check the [documentation for "Binaries, strings, and charlists"](https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html) for more information 🙂

**Comment by NathanGrimaud** [comment]
Alright thanks @adkron ! This is quite confusing, but I wont make this mistake twice ^^
