### ISSUE TITLE
Provide more granularity for the strip_beams release configuration

### ISSUE THREAD

**Issue by noozo** [elixir-lang/elixir#10122]
Currently `mix release` provides the boolean flag `strip_beams` to control whether or not beam files are stripped of metadata like documentation, for example.

It would be good to be able to specify exactly *what* to strip and what to keep.

One example of this necessity can be seen here: https://github.com/open-api-spex/open_api_spex/issues/242
tldr> OpenApiSpex relies on code documentation for generating OpenAPI documentation at runtime, which means it would be nice to tell mix release not to strip the beam files out of the docs only, hence keeping the final compiled files a bit smaller.

For instance, in my own project, using strip_beams flag right now increases my final docker container size from 71MB to 96MB. I'm guessing if we could keep docs alone this size would be much smaller.

**Comment by josevalim** [comment]
Thank you! We will definitely ship this on v1.11. A PR is welcome!

**Comment by noozo** [comment]
@josevalim, working on a PR for this. My approach is to allow another option to be passed (possibly named strip_beams_exceptions), a list that can contain chunks not to be stripped when the strip_beams option is true. You would pass, for instance [:docs, :debug_info] and everything would be stripped as usual, except those 2 chunks (besides the already @significant_chunks).

Does that sound reasonable, or would another way be preferable?

Another couple of questions, while i'm at it:
- Should the same ability be added to Mix.Tasks.Escript.Build?
- When opening a PR is it better to wait until everything is working, or can WIP open PR's exist?

Thanks!

**Comment by josevalim** [comment]
I believe we can do: strip_beams: [keep: “Docs”]. We should support it on Build too. Open the PR whenever you would like to get feedback. :)

**Comment by noozo** [comment]
Yeah, that sounds better. Cool, will do!
