### ISSUE TITLE
Precompiled.zip for big endian systems.

### ISSUE THREAD

**Issue by adpopescu** [elixir-lang/elixir#10124]
Currently when the Precompiled.zip is used for installation on big endian systems this warning appears:

warning: Elixir is running in a system with a different endianness than the one its source code was compiled in. Please make sure Elixir and all source files were compiled in a machine with the same endianness as the current one: big

Could a Precompiled.zip package for big endian be provided?

Thank you.

**Comment by josevalim** [comment]
Hi @adpopescu, we have no plans to do so. My recommendation is for users to compile Elixir on those systems or use one package managers from https://elixir-lang.org/install.html.

The Precompiled.zip exists mostly for Windows support, where the package distribution in there is ironed out as in Unix systems, although it obviously works on most other systems too (except for endianness).
