### ISSUE TITLE
ApplicationTracer doesn't warn on Mix/ExUnit

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#10137]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): master
* Operating system: macOS 10.15.4

### Current behavior

Let's say I have this module:

```
defmodule Dummy do
  def hello do
    Mix.compilers()
  end
end
```

While it works fine in dev etc, it won't work in releases (since I didn't add it to `:extra_applications`)

```
% mix release
% _build/dev/rel/dummy/bin/dummy eval "Dummy.hello"
** (UndefinedFunctionError) function Mix.compilers/0 is undefined (module Mix is not available)
    Mix.compilers()
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.0-dev) lib/code.ex:341: Code.eval_string_with_error_handling/3
```

### Expected behavior

ApplicationTracer warns on this.

**Comment by josevalim** [comment]
We don't warn because many projects, such as Ecto, Phoenix, and Gettext, depend on Mix functions but they obviously don't want to list `:mix` as an extra application. This means we don't warn for any of Elixir built-in apps except eex and logger.

**Comment by wojtekmach** [comment]
That makes sense, thanks!

**Comment by josevalim** [comment]
Curiously, we may be able to fix those if we list ExUnit and Mix as optional dependencies. Given Erlang/OTP may introduce optional dependencies, we can probably introduce `extra_applications: [:foo, :bar, mix: :optional]`. For now, those optional dependencies will be simply discarded.

**Comment by josevalim** [comment]
Although we wouldn't be able to enforce this for now, since using the `mix: :optional` syntax would restrict Phoenix to Elixir v1.11. Although we can probably add the feature now paving the road for the future.
