### ISSUE TITLE
"undefined field * in expression" - false positive?

### ISSUE THREAD

**Issue by fuelen** [elixir-lang/elixir#10148]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.0-dev (b792ae5) (compiled with Erlang/OTP 22), erlang 22.3.4
* Operating system: Linux

### Current behavior
```elixir
  def test(record) when not is_struct(record, URI) do
    record.name
  end
```
produces
```
warning: undefined field "name" in expression:

    # lib/elixir_playground.ex:25
    record.name

where "record" was given the type %{} in:

    # lib/elixir_playground.ex:24
    :erlang.map_get(:__struct__, record)

where "record" was given the type %{} in:

    # lib/elixir_playground.ex:24
    is_map_key(record, :__struct__)

where "record" was given the type unbound() in:

    # lib/elixir_playground.ex:24
    is_atom(URI) or :fail

Conflict found at
  lib/elixir_playground.ex:25: ElixirPlayground.test/1

```

### Expected behavior

I think the function above is correct and warning should not be shown.

**Comment by josevalim** [comment]
Thanks for the report. There are probably three scenarios in `not` we need to consider:

1. `not is_type` - if there is any is_type check at any level, discard everything and mark the vars as dynamic

2. `not is_map_key(var, :foo)` - we can still say `var` is `map`

3. `not var` - we can still var is `false`

The other thing is that we should probably remove "unbound" / "dynamic" entries from the trace.

**Comment by fuelen** [comment]
@ericmj @josevalim 
Just tried `Elixir 1.11.0-dev (6228ade) (compiled with Erlang/OTP 22)`  and found one more similar issue:
```elixir
  def test(project) when project.type == :secret do
    project.name
  end
```
produces
```
warning: undefined field "name" in expression:

    # lib/elixir_playground.ex:32
    project.name

where "project" was given the type %{} in:

    # lib/elixir_playground.ex:31
    :erlang.map_get(:type, project)

Conflict found at
  lib/elixir_playground.ex:32: ElixirPlayground.test/1


```
