### ISSUE TITLE
Incorrect spec for Port.open({:spawn_executable...

### ISSUE THREAD

**Issue by Will-W** [elixir-lang/elixir#10143]
The spec for `Port,open()` has this type for the name argument (latest master as of now):
```
  @type name ::
          {:spawn, charlist | binary}
          | {:spawn_driver, charlist | binary}
          | {:spawn_executable, charlist | atom}
          | {:fd, non_neg_integer, non_neg_integer}
```

`:spawn_executable` is missing a `binary` option, which means that copy and pasted examples such as this from the documentation produce dialyzer errors:

```
      Port.open(
        {:spawn_executable, "/path/to/program"},
        args: ["a", "b", "c"]
      )
```

I can see no reason why `spawn_executable` shouldn't take binary (and it works), but if there is some issue I'm not aware of then the docs need to match.

### Environment
My environment is as follows, but as I said above, source code shows this problem in current master.

Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.10.2 (compiled with Erlang/OTP 22)
Linux (Fedora 30)

**Comment by ericmj** [comment]
It seems to accept binaries, since they are included in `file:name_all()`: http://erlang.org/doc/man/erlang.html#open_port-2.
