### ISSUE TITLE
Registry.body() spec not aligned with docs example

### ISSUE THREAD

**Issue by miquecg** [elixir-lang/elixir#10184]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.4 / OTP 22
* Operating system: N/A

### Current behavior

[`Registry.body()`](https://hexdocs.pm/elixir/1.10.4/Registry.html#t:body/0) spec is as follows: `[atom() | tuple()]`. It doesn't allow maps, for instance, even when they are completely valid.

```elixir
tuple = {:key, self(), "foo"}
match_spec = [
  {
    {:"$1", :_, :"$3"},
    [],
    [%{id: :"$1", value: :"$3"}]
  }
]
:ets.test_ms(tuple, match_spec)

iex> {:ok, %{id: :key, value: "foo"}}
```

[`Registry.select/2`](https://hexdocs.pm/elixir/1.10.4/Registry.html#select/2) also documents that a map is a possible pattern:

> To get a result format like `%{key: key, pid: pid, value: value}`, assuming
> you bound those variables in order in the match part, you would provide a
> body like `[%{key: :"$1", pid: :"$2", value: :"$3"}]`.

If I understand [match specification in Erlang](https://erlang.org/doc/apps/erts/match_spec.html) correctly, which is a bit complex, it allows `tuples`, `lists` and `maps`; empty or with values inside (more of them or any other term).

```erlang
MatchBody ::= [ ConditionExpression, ... ]
ConditionExpression ::= ExprMatchVariable | { GuardFunction } | { GuardFunction, ConditionExpression, ... } | TermConstruct
ExprMatchVariable ::= MatchVariable (bound in the MatchHead) | '$_' | '$$'
TermConstruct = {{}} | {{ ConditionExpression, ... }} | [] | [ConditionExpression, ...] | #{} | #{term() => ConditionExpression, ...} | NonCompositeTerm | Constant
NonCompositeTerm ::= term() (not list or tuple or map)
Constant ::= {const, term()}
```

### Expected behavior

The `body()` spec should be general enough to no cause warnings when using Dialyzer, at least having also maps, although potentially any value is allowed by the underlying `:ets` module. Not sure about drawbacks, etc.

**Comment by josevalim** [comment]
Erlang just [uses `[term()]`](https://erlang.org/doc/man/ets.html#type-match_spec), so that's probably what we should change to. Can you please send a PR?

**Comment by miquecg** [comment]
Sure, no problem!

**Comment by miquecg** [comment]
This [change](#10017) was merged to master in May but didn't make it to 1.10 yet. Are changes cherry picked from development branch?

If you still want I can open a new PR against 1.10.

**Comment by josevalim** [comment]
Thanks, i have backported it but there are no plans for a new v1.10 at the moment, so you will most likely see it on v1.11, which should have a RC next month.

**Comment by miquecg** [comment]
Ok, that's fine :+1:
