### ISSUE TITLE
__MODULE__ with extra underscores still parses and compiles

### ISSUE THREAD

**Issue by axelson** [elixir-lang/elixir#10197]
# Environment

* Elixir & Erlang/OTP versions (elixir --version): 
* Operating system: 

### Current behavior

```Elixir
iex(1)> defmodule Example do
...(1)>   defstruct []
...(1)>
...(1)>   def func(%____MODULE__{}), do: true
...(1)> end
{:module, Example,
 <<70, 79, 82, 49, 0, 0, 7, 76, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 194,
   0, 0, 0, 20, 14, 69, 108, 105, 120, 105, 114, 46, 69, 120, 97, 109, 112, 108,
   101, 8, 95, 95, 105, 110, 102, 111, 95, ...>>, {:func, 1}}
iex(2)> Example.func(%Example{})
true
```

### Expected behavior

A compilation error.

### Thoughts

Is this expected? I would generally expect the compiler to be more strict. Additional `_` after `MODULE` are also ignored.

**Comment by josevalim** [comment]
`___this_is_a_valid_variable_name____` so is this `___MODULE_____`. :) So in your case you are getting just assigning the struct name to a variable that is not used. I know this can be confusing but I don't think there is an immediately obvious solution besides perhaps forbidding variables starting with  underscore as the struct name, which can also be confusing.

**Comment by josevalim** [comment]
Sent #10198 for discussion.

**Comment by axelson** [comment]
Ah, I see. That indeed makes sense. I agree that a compiler warning makes sense :+1:
