### ISSUE TITLE
Diffing algorithm in ExUnit does not handle == vs === comparisons correctly

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#10210]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```
* Operating system: macOS

### Current behavior

Given the following tests:

```elixir
defmodule FooTest do
  use ExUnit.Case
  doctest Foo

  test "==" do
    assert %{a: 1} == %{a: 1.0}
    assert %{a: 1, b: 2} == %{a: 1.0, b: :different}
  end

  test "===" do
    assert %{a: 1, b: 2} === %{a: 1.0, b: :different}
  end
end

```

when executed the following error is presented:

![Screenshot 2020-07-20 at 18 14 20](https://user-images.githubusercontent.com/477062/87966221-deda6480-cab4-11ea-95f4-2884d926dd6f.png)

The output for the `===` comparison is correct - both the `a` key and the `b` key are different and causing the failure. But the output for the `==` comparison is incorrect - the values under the `a` key compare equal (which is demonstrated by the first assertion passing).

### Expected behavior

The diff should only include values that don't compare equal under the chosen comparison operator. In the particular example the values of the `a` key in the `==` test should not be highlighted.

**Comment by josevalim** [comment]
http://www.nooooooooooooooo.com/

**Comment by michalmuskala** [comment]
I'm sorry I looked at this too closely 😅
I was attempting to port this to Erlang

**Comment by josevalim** [comment]
Haha, thanks for the report! @michalmuskala how would you port it to Erlang? Would you use a macro? ct or eunit or other? :)

**Comment by michalmuskala** [comment]
I'm thinking about CT since that's what I use right now, but main parts of it should be quite generic. The WIP can be found here: https://github.com/michalmuskala/better_assert. It's a mixture of macros and parse transforms. So far I focused on gathering information from surrounding code, actual diffing comes next.

Beyond just the diffing, I want to also port other assertion types like `assert_receive` and `assert_match` that "leak" variables. Today Erlang's `?assertMatch` does not "leak" variables, so it is of fairly limited utility (and the improvement in error message over a raw match error is not that huge either).
