### ISSUE TITLE
Node.connect doesn't work with simple sname

### ISSUE THREAD

**Issue by malaire** [elixir-lang/elixir#10229]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.4 ; Erlang/OTP 23
* Operating system: Debian 10

### Current behavior

    # first terminal
    $ iex --sname one
    iex(one@localhost)1>

    # second terminal
    $ iex --sname two
    iex(two@localhost)1> Node.connect :one
    17:32:29.619 [error] 
    ** Cannot get connection id for node :one
    
    false

    # third terminal
    $ epmd -names
    epmd: up and running on port 4369 with data:
    name two at port 35695
    name one at port 41151

### Expected behavior

I expected second node to be able to connect to first node.

### Notes

Using `sname`:s `one@localhost` and `two@localhost` does work.

Maybe related to #3955 although that is about OSX. Unfortunately that issue doesn't have any solution applicable to Debian.

`/etc/hosts`:

    127.0.0.1  localhost box local.amolelingue.com dev.amolelingue.com
    
    ::1     localhost ip6-localhost ip6-loopback
    ff02::1 ip6-allnodes
    ff02::2 ip6-allrouters

**Comment by josevalim** [comment]
You need to do `Node.connect(:one@localhost)` and not the atom itself. :)

**Comment by josevalim** [comment]
Btw, your machine seems to be named localhost, which is why you are pointing to localhost, but it is not actually using the full name resolution, just the machine name.
