### ISSUE TITLE
Improve error message for Application.compile_env! and Application.get_env!

### ISSUE THREAD

**Issue by Voronoff** [elixir-lang/elixir#10225]
### Environment

Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 22)
Ubuntu 18.04.4 LTS

### Current behavior

Missing the configuration that you try to access using an `Application.compile_env!` or `Application.get_env!` gives a very misleading error message, saying that the application was not loaded/started and suggesting to fix that in `:extra_applications`.

This config:
```
config :curious_messenger, :pow,
  user: CuriousMessenger.Auth.User,
  repo: CuriousMessenger.Repo,
  web_module: CuriousMessengerWeb
```

with this request:
` @cache_backend Application.compile_env!(:curious_messenger, [:pow, :cache_store_backend])`

raises this error:
```
== Compilation error in file lib/curious_messenger_web/credentials.ex ==
** (ArgumentError) could not fetch application environment [:pow, :cache_store_backend] for application :curious_messenger because the application was not loaded/started. If your application depends on :curious_messenger at runtime, make sure to load/start it or list it under :extra_applications in your mix.exs file
    (elixir 1.10.3) lib/application.ex:653: Application.fetch_env!/2
    lib/curious_messenger_web/credentials.ex:18: (module)
    (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6
```

while this request:
`@cache_backend Application.compile_env!(:curious_messenger, :pow)`

works as expected:
```
[
  user: CuriousMessenger.Auth.User,
  repo: CuriousMessenger.Repo,
  web_module: CuriousMessengerWeb
]
```

### Expected behavior

The error should determine if the application was loaded and the configuration was missing, and if so say something along the lines of
```
** (ArgumentError) could not fetch application environment [:pow, :cache_store_backend] for application :curious_messenger because the configuration was missing for [:pow, :cache_store_backend]. Check your config.exs file to make sure it is defined there. 
```

**Comment by josevalim** [comment]
@Voronoff thanks for the report.

This is true for `compile_env` but not quite for `get_env`. That's because if you configure an application that doesn't exist or has not been loaded, Mix is going to complain. The issue is that the error from `compile_env` happens too early, before Mix gets to tell you are configuring something that does not exist/has not been loaded, so in there we should indeed point to `config.exs`. I will fix it accordingly, thanks!
