### ISSUE TITLE
mix cmd not respecting multiple --app options in umbrella application in v1.10.4

### ISSUE THREAD

**Issue by vkk-steigend** [elixir-lang/elixir#10230]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.4 & 22.3.4.3
* Operating system: Debian 10 - Buster (Using docker image elixir:1.10.4)

### Current behavior
Suppose an umbrella project existis with 3 projects app1, app2, app3.
Run the following from the root of the umbrella project:
`mix cmd --app app1 --app2 "ls"`
It lists only the files and folders which are present only in the app which is specified with the first -app option. In this case it lists files and folders from app1 only.

### Expected behavior
The task should execute the specified command in all projects specified using multiple --app option.
`mix cmd "ls"` is working as expected.

This was working as expected in v1.10.2

**Comment by wojtekmach** [comment]
Already fixed on master (https://github.com/elixir-lang/elixir/pull/10226) :)
