### ISSUE TITLE
Tests in `mix test --trace` are hard to trace

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10232]
The results by --trace were not clear as I couldn't immediately identify the test that was emitting a warning.

```
ExDoc.Formatter.HTMLTest
  ...
  * test generates extras without any other content (10.9ms)
  ...
```

The following points are noted:

**1.  the test file is omitted. Only the module is shown.**
I think we could show the source of the file next to the module.

```
ExDoc.Formatter.HTMLTest (test/ex_doc/formatter/html_test.exs)
```

It is hard to find the test when used inside a describe.
That's because.

**2. there is no line number**

**3. the test name is the joining of the title in describe and the title of the test, plus it is prefixed with the word test.**

I searched for "test generates extras without any other content", "generates extras without any other content",
"generates extras without any" and nothing turned up.

We could show some structured results, including line numbers 

## Tentative format

```
ExDoc.Formatter.HTMLTest  (test/ex_doc/formatter/html_test.exs)
  * generates extras [:298]
      - without api-reference [:416] (64.9ms)
```

another simpler solution would be to keep it flat as it is, and add the line number and source file.

```
ExDoc.Formatter.HTMLTest  (test/ex_doc/formatter/html_test.exs)
  * test generates extras without api-reference [:416] (64.9ms)
```

**Comment by Eiji7** [comment]
@eksperimental I like "simpler solution", but there is still something missing …

I propose something like:
```elixir
ExDoc.Formatter.HTMLTest  (test/ex_doc/formatter/html_test.exs)
  * test: generates extras [line 298] without api-reference [line 416] (64.9ms)
```

or shorter version:
```elixir
ExDoc.Formatter.HTMLTest  (test/ex_doc/formatter/html_test.exs)
  * test: generates_extras:298 without_api_reference:416 (64.9ms)
```

In both cases `test` looks more like `prefix` with `:` character after it and there is line number as separator between `describe` name and `test` name. Also for me at first sight `[:416]` is not clear and may confuse beginners whereas `without_api_reference:416` looks more like `file_name:line` which I believe is well known format.

**Comment by josevalim** [comment]
We no longer have the describe information but we can add line+file.

**Comment by eksperimental** [comment]
> ```elixir
> ExDoc.Formatter.HTMLTest  (test/ex_doc/formatter/html_test.exs)
>   * test: generates extras [line 298] without api-reference [line 416] (64.9ms)
> ```

Loved this one.
*  +1 for doing "test: " a prefix
* +1 for adding the line: notation.

**Comment by eksperimental** [comment]
> We no longer have the describe information but we can add line+file.

File is stored in every test, but not in the first level of`t:ExUnit.TestModule/0`. Should we look for the line of the first test? or obtain the address of the file based on the module?

**Comment by NickNeck** [comment]
The test formatter gets something like this:
```elixir
{:test_started,
 %ExUnit.Test{
   case: Tox.DateTimeTest,
   logs: "",
   module: Tox.DateTimeTest,
   name: :"test shift/3 adds a month at new year",
   state: nil,
   tags: %{
     async: false,
     describe: "shift/3",
     describe_line: 9,
     file: "/Users/kruse/Projects/tox/test/tox/datetime_test.exs",
     line: 47,
     module: Tox.DateTimeTest,
     registered: %{},
     test: :"test shift/3 adds a month at new year",
     test_type: :test
   },
   time: 0
 }}
```
It seems all the needed information is there. Or did I miss something?

**Comment by eksperimental** [comment]
> The test formatter gets something like this:
> 
> ```elixir
> {:test_started,
>  %ExUnit.Test{
>    case: Tox.DateTimeTest,
>    logs: "",
>    module: Tox.DateTimeTest,
>    name: :"test shift/3 adds a month at new year",
>    state: nil,
>    tags: %{
>      async: false,
>      describe: "shift/3",
>      describe_line: 9,
>      file: "/Users/kruse/Projects/tox/test/tox/datetime_test.exs",
>      line: 47,
>      module: Tox.DateTimeTest,
>      registered: %{},
>      test: :"test shift/3 adds a month at new year",
>      test_type: :test
>    },
>    time: 0
>  }}
> ```
> 
> It seems all the needed information is there. Or did I miss something?

This is the code that prints the test module, and no file path is stored in there.

```elixir
  def handle_cast({:module_started, %ExUnit.TestModule{name: name}} = struct, config) do
    if config.trace() do
      IO.puts("\n#{inspect(name)}")
    end

    {:noreply, config}
  end

```

**Comment by eksperimental** [comment]
@josevalim thank you for the commit. I had a PR almost ready, which pretty much did the same.
I will submit a PR including some things that were not covered by your commit.

One question. I am thinking we should also store the line where the TestModule is defined, as there may be more than one module per file, while uncommon, it is possible.

**Comment by eksperimental** [comment]
> One question. I am thinking we should also store the line where the TestModule is defined, as there may be more than one module per file, while uncommon, it is possible.

regardless of whether we use in --trace, I think it is worth to have it in the TestModule struct

**Comment by josevalim** [comment]
@eksperimental the line will most likely be unnecessary information most times - so I wouldn't include it. I don't think we should automatically dump all info we had. For this reason, I wouldn't add it to the struct either, unless someone has a need.
