### ISSUE TITLE
[suggestion] Improve documentation about typespec and sigils

### ISSUE THREAD

**Issue by belchior** [elixir-lang/elixir#10259]
Will be helpful if the [Typespec doc](https://hexdocs.pm/elixir/typespecs.html#content) do some mention about how to typespec sigils, mainly because of the regex sigils.

**Comment by eksperimental** [comment]
Sigils are helpers that return different terms, For instance the `t:Regex.t/0` type  is a Regex struct (`%Regex{}`), while the ~S sigil will return a binary. It is up to the use how you generate the terms that you pass to the functions you want to typespec.
