### ISSUE TITLE
Kernel.var/2 fails on "standard tuple form {name, meta, context}"

### ISSUE THREAD

**Issue by beadsland** [elixir-lang/elixir#10251]
### Environment

Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:4:2] [ds:4:2:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 22)

Ubuntu 18.04.4 LTS

[https://hexdocs.pm/elixir/Kernel.html#var!/2](https://hexdocs.pm/elixir/Kernel.html#var!/2)

>When used inside quoting, marks that the given variable should not be hygienized.
>
>The argument can be either a variable unquoted or in standard tuple form {name, meta, context}.
>
>Check Kernel.SpecialForms.quote/2 for more information.

### Current behavior

**Note:** `var!/2` is intended for use within quoting, as its usage is to unhygenically reference variables from within a macro. However, iex reproduces the exact same errors as seen on compiling a macro, so I'm using the iex output here for clarity.

```
iex(1)> state = "hello, world"
"hello, world"
iex(2)> var!(state)
"hello, world"
iex(3)> var!({:state, [], nil})
** (ArgumentError) expected a variable to be given to var!, got: {:state, [], nil}
    (elixir 1.10.4) lib/kernel.ex:3809: Kernel."MACRO-var!"/3
    (elixir 1.10.4) expanding macro: Kernel.var!/1
    iex:3: (file)
iex(3)> var!({:state, [], nil}, nil)
** (ArgumentError) expected a variable to be given to var!, got: {:state, [], nil}
    (elixir 1.10.4) expanding macro: Kernel.var!/2
    iex:3: (file)
iex(4)> Macro.var(:state, nil)
{:state, [], nil}
iex(4)> var!(Macro.var(:state, nil)) 
** (ArgumentError) expected a variable to be given to var!, got: Macro.var(:state, nil)
    (elixir 1.10.4) lib/kernel.ex:3809: Kernel."MACRO-var!"/3
    (elixir 1.10.4) expanding macro: Kernel.var!/1
    iex:4: (file)
iex(4)> var!(1 + 1) 
** (ArgumentError) expected a variable to be given to var!, got: 1 + 1
    (elixir 1.10.4) lib/kernel.ex:3809: Kernel."MACRO-var!"/3
    (elixir 1.10.4) expanding macro: Kernel.var!/1
    iex:4: (file)
```

The last two errors are particularly striking. One would expect the result of `Macro.var/2` or `1 + 1` to be passed to `var!/2`, not the raw infix expression from within the parentheses. That is, the final error ought to read "got: 2", not "got: 1 + 1". (At least, given implementation shown in Kernel.ex)

This suggests some magic compiler intervention, which is to be expected given that `var!/2` is intended for unhygenic variable references within macros.

However, it also suggests that the first error is also resulting from raw infix expressions being intercepted by the compiler, rather than these expressions being resolved. _i.e._, the compiler is raising an ArgumentError on the raw uncompiled infix "{:state, [], nil}" rather than the (legal, per docs) compiled tuple `{:state, [], nil}`.

### Expected behavior

My instinct would be that `var!/2` shouldn't even be legal unquoted (how does one unhygenically reference a variable if you're not quoted?). My instincts notwithstanding, there's nothing evident in Kernel.ex that would complain about passing a standard tuple form to `var!/2` in iex. That is:

`var!({name, meta, atom}, context) when is_atom(name) and is_atom(atom)`

is a valid signature.

Further inspection, however, reveals that there's no implementation in Kernel.ex other than defensive. This makes sense, of course, given that one expects compiler magic under normal circumstances in order to go unhygenic. In which case, one would anticipate iex(3) through iex(5) to return `{state, [], nil}` (per Kernel.ex), not the value of `state`.

But, again, compiler magic is implicated, and `var!/2` is strangely legal in iex, so assuming this, we should expect the output shown below.

```
iex(1)> state = "hello, world"
"hello, world"
iex(2)> var!(state)
"hello, world"
iex(3)> var!({state, [], nil})
"hello, world"
iex(4)> var!({state, [], nil}, nil)
"hello, world"
iex(5)> var!(Macro.var(:state))
"hello, world"
iex(6)> var!(1 + 1)
** (ArgumentError) expected a variable to be given to var!, got: 2
    (elixir 1.10.4) lib/kernel.ex:3809: Kernel."MACRO-var!"/3
    (elixir 1.10.4) expanding macro: Kernel.var!/1
    iex:6: (file)
```
Again, `var!/2` really ought'nt be legal at all in iex, but insofar as it is, it shouldn't be throwing errors for uncompiled infix.

**Comment by josevalim** [comment]
`Kernel.var` expects a variable. Since it is a macro, it matches on the AST of a variable, which is a three element tuple:

```
iex(1)> quote do: var
{:var, [], Elixir}
```

The AST of a 3-element tuple would actually be different:

iex(2)> quote do: {:var, [], Elixir}
{:{}, [], [:var, [], {:__aliases__, [], [Elixir]}]}
```

The documentation is confusing because it is referring to the variable AST but it doesn't really expect the AST to be given literally. I will fix the docs, thanks for the report!

**Comment by beadsland** [comment]
By `Kernel.var`, I assume you mean `Kernel.var!` (per my original heading for this submission), as it is `Kernel.var!` (with the bang) that I'm trying to get working, not `Kernel.var` (_sans_ bang). (Are you perhaps thinking of `Macro.var`?)

The explanation is certainly helpful, however:

```
iex(1)> quote do: var
{:var, [], Elixir}
iex(2)> quote do: {:var, [], Elixir}
{:{}, [], [:var, [], {:__aliases__, [], [Elixir]}]}
iex(3)> var!({:{}, [], [:var, [], {:__aliases__, [], [Elixir]}]})
** (ArgumentError) expected a variable to be given to var!, got: {:{}, [], [:var, [], {:__aliases__, [], [Elixir]}]}
    (elixir 1.10.4) lib/kernel.ex:3809: Kernel."MACRO-var!"/3
    (elixir 1.10.4) expanding macro: Kernel.var!/1
    iex:3: (file)
```

Still unable to get `var!/2` to accept the ast of the 3-element tuple. 

It certainly helps to have the correct form, ast of standard tuple rather than raw standard tuple, but if var!/2 still refuses to parse the infix into a tuple, we're not getting anywhere.

Also, if we're correcting documentation, we'll need to correct the source file for Kernel.ex also. Again, the signature shown in that file is:

`var!({name, meta, atom}, context) when is_atom(name) and is_atom(atom)`

That is, the source file isn't asking for the ast of {name, meta, atom}. It's asking for {name, meta, atom}. The only other clause of of `var!/2` in the source file merely throws an error for failing to match the 3-tuple specified in the signature above.

To be clear, the use case to unhygienically reference a variable the name of which is not known at compile time. The macro I'm working on would either take the last variable named in __ENV__.vars or else a variable named as a parameter to the macro, both of which would be in the form of atoms, and pass this information to `!var/2` to unhygienically modify the variable so named. _e.g._, if working with current docs, this ought to work:

```
defmacro dirty_last(var_as_atom) when is_atom(var_as_atom) do
    quote bind_quoted: [var_as_atom: var_as_atom] do
        if is_map(!var({var_as_atom, [], __ENV__.context})) do
            !var({var_as_atom, [], __ENV__.context}) = Map.put !var({var_as_atom, [], __ENV__.context}), :dirty, "hello world"
        end
    end
end

```

Per your explanation above, it ought to read:

```
defmacro dirty_last(var_as_atom) when is_atom(var_as_atom) do
    quote bind_quoted: [var_as_atom: var_as_atom] do
        if is_map(!var({:{}, [], [var_as_atom, [], {:__aliases__, [], [__ENV__.context]}]})) do
            !var({:{}, [], [var_as_atom, [], {:__aliases__, [], [__ENV__.context]}]}) = Map.put !var({:{}, [], [var_as_atom, [], {:__aliases__, [], [__ENV__.context]}]}), :dirty, "hello world"
        end
    end
end

```

However, as per OP, this is still the case:

```
iex(4)> var!(1 + 1) 
** (ArgumentError) expected a variable to be given to var!, got: 1 + 1
    (elixir 1.10.4) lib/kernel.ex:3809: Kernel."MACRO-var!"/3, 
    (elixir 1.10.4) expanding macro: Kernel.var!/1
    iex:4: (file)
```

That is, the tuple never gets to `var!/2`. Whether `{:var, [], Elixir}` or `{:{}, [], [:var, [], {:__aliases__, [], [Elixir]}]}` or `1 + 1`, the only thing that ever gets to `var!/2` is the uncompiled infix between the parentheses. Effectively, `var!/2` is treating the infix as a string. That is calling `var!(a)` passes `var!/2` the string "a" and `var!({:{}, [], [:var, [], {:__aliases__, [], [Elixir]}]})` passes `var!/2` the string "{:{}, [], [:var, [], {:__aliases__, [], [Elixir]}]}" not the ast `{:{}, [], [:var, [], {:__aliases__, [], [Elixir]}]}`.

So long as this is the case, it doesn't matter how the documentation is corrected, `var!/2` will continue to throw errors when passed a tuple, whether a standard tuple or an ast of a standard tuple, because `var!/2` is never given the tuple, only a string representing the tuple.

**Comment by beadsland** [comment]
*Suggestion*

Obviously, there's some compiler magic happening that's intercepting `var!/2` and keeping the infix from being compiled. Otherwise, this couldn't possibly work:

```
iex(1)> hello = "world"
"world"
iex(2)> var!(hello)
"world"

```

Because if the compiler were passing `var!/2` the compiled value of `hello`, it wouldn't get the unquoted variable name `hello` but the value "world", and then `var!/2` would barf on "hello" not being a variable. That is `var!/2`, unlike any other function, requires that it be passed the literal infix between its parentheses, not the compiled value represented by that infix, in order to be able to divine variable names. No other function is capable of divining the name of a variable in the infix of its paramater list. 

That there is compiler magic happening is confirmed by the fact that the clauses for `Kernel.var!/2` are entirely defensive. There's nothing here doing anything magical to achieve unhygienic variable work. Therefore, this must be happening somewhere else, that is, in the compiler, not the source of `Kernel.var!/2`. Indeed, as written the source for `Kernel.var!/2` doesn't know about anything but standard tuples. There's no clause that matches an uncompiled infix variable name.

That all being the case, the problem seems to be that the compiler is unreflexively passing anything and everything in the infix of `var!/2`, rather than looking at what is passed. To match the docs, what ought to be happening is that if the compiler sees a parenthesized infix that looks like a variable name, it should treat it as such, but if it sees anything else, it should attempt to compile it, and then pass that to `var!/2`.

This would allow `var!/2` to continue to magically accept the names of variables but also to accept a tuple representing the name of a variable, as per the docs. Whether this tuple is in standard form or ast of standard form is neither here nor there, so long as you can actually pass a valid tuple to `var!/2` and not be told it wasn't a variable.

**Comment by josevalim** [comment]
Yes, I meant Kernel.var!. Note the code is correct as is, you are not supposed to pass the tuple literally, you will always pass a variable and we will match on the AST received since var! is a macro. The docs have been changed to remove the confusion.
