### ISSUE TITLE
Support comments trailing block start/end in EEx tags

### ISSUE THREAD

**Issue by christhekeele** [elixir-lang/elixir#10256]
In response to [`elixir-lang-core` forum guidance](https://groups.google.com/forum/#!topic/elixir-lang-core/L6TIqlqdQmw) to open an issue here:

> In complex EEx templates I find it helpful to document the [start and] end of control-flow or loop statements.
> Unfortunately, this results in compiler syntax error

<details>
  <summary><strong><em>Environment</em></strong></summary>

* Elixir & Erlang/OTP versions (elixir --version): 

  ```
  Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
  Elixir 1.10.3 (compiled with Erlang/OTP 22)
  ```

* Operating system: 

  macOS Catalina 10.15.5

</details>

<details open>
  <summary><strong><em>Current behavior</em></strong></summary>

`EEx` can successfully compile these snippets:

- ```elixir
  EEx.compile_string(~S[
    <%= IO.puts("general expression") # expression comment %>
  ])
  #=> ✅
  ```

- ```elixir
  EEx.compile_string(~S[
    <% if true, do: "content" # one-liner block comment %>
  ])
  #=> ✅
  ```

However, it fails to compile these:

- ```elixir
  EEx.compile_string(~S[
    <% if true do # start block comment %>
      ...long content
    <% end %>
  ])
  #=> ❌ 
  # ** (TokenMissingError) nofile:2: missing terminator: end (for "do" starting at line 2)
  #     lib/eex/compiler.ex:45: EEx.Compiler.generate_buffer/4
  #     (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6
  #     (iex 1.10.3) lib/iex/evaluator.ex:258: IEx.Evaluator.handle_eval/5
  #     (iex 1.10.3) lib/iex/evaluator.ex:239: IEx.Evaluator.do_eval/3
  #     (iex 1.10.3) lib/iex/evaluator.ex:217: IEx.Evaluator.eval/3
  ```

- ```elixir
  EEx.compile_string(~S[
    <% if true do %>
      ...long content
    <% end # end block comment %>
  ])
  #=> ❌ 
  # ** (SyntaxError) nofile:4: unexpected token: end
  #     lib/eex/compiler.ex:45: EEx.Compiler.generate_buffer/4
  #     lib/eex/compiler.ex:54: EEx.Compiler.generate_buffer/4
  #     (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6
  #     (iex 1.10.3) lib/iex/evaluator.ex:258: IEx.Evaluator.handle_eval/5
  #     (iex 1.10.3) lib/iex/evaluator.ex:239: IEx.Evaluator.do_eval/3
  ```

</details>

### Expected behavior

It seems reasonable for `EEx` to support all of these types of trailing comments and compile them happily.

**Comment by richardkmichael** [comment]
@josevalim I was just going to try to look at it myself!  That was fast, thank you very much! :) <3

**Comment by christhekeele** [comment]
Amazingly fast, thanks José! 💞❤️🧡💛💚💙💜💖💜💙💚🧡💛❤️💘
