### ISSUE TITLE
with keyword compilation error when with is followed by a new line

### ISSUE THREAD

**Issue by bulenterdemir** [elixir-lang/elixir#10253]
Hi, when the keyword `with ` is followed by a new line, the compiler wouldn't compile. In the code below, get_user_by_username_and_password1 would compile normally, however, get_user_by_username_and_password2 would give an error:

def get_user_by_username_and_password1(username, password) do
    with user when not is_nil(user) <- @repo.get_by(User, %{username: username}),
      true <- Password.verify_with_hash(password, user.hashed_password) do
      user
    else
      _ -> Password.dummy_verify
    end
  end

 def get_user_by_username_and_password2(username, password) do 
    with
      user when not is_nil(user) <- @repo.get_by(User, %{username: username}),
      true <- Password.verify_with_hash(password, user.hashed_password) do
        user 
    else
      _ -> Password.dummy_verify
    end
  end 

The compiler error message is:

==> auction
Compiling 1 file (.ex)

== Compilation error in file lib/auction.ex ==
** (SyntaxError) lib/auction.ex:67: syntax error before: do
    (elixir 1.10.4) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7

**Comment by josevalim** [comment]
Correct. `with` by itself would be as if you were trying to access the variable “with”. So you either need parens or you need to add `\` at the end of the line to mark the expression has not finished.

It helps to understand that in Elixir there are very few actual keywords, “with” is not one of them, so it follows the same rules as any other identifier in the language.

**Comment by bulenterdemir** [comment]
I understand. Thank you for your quick response.
