### ISSUE TITLE
Compilation error: Inconsistent behaviour in map typespec keys

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10260]
```elixir
  @type ok :: %{
          :foo =>  list(),
          :bar => list(),
        }


  @type ok2 :: %{
          foo: list(),
          bar: list(),
        }

  @type ok3 :: %{
          :bar => list(),
          foo:  list(),
        }

  @type error3 :: %{
          foo:  list(),
          :bar => list(),
        }
```
The last type won't compile.  Look how swapping the order from ok3 breaks it,

```
== Compilation error in file lib/foo.ex ==
** (SyntaxError) lib/foo.ex:58: syntax error before: bar
    (elixir 1.11.0-dev) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
make: *** [Makefile:117: lib/iex/ebin/Elixir.IEx.beam] Error 1

```

**Comment by Eiji7** [comment]
@eksperimental I think it's not strictly a `Typespec` thing, but how syntactic sugar of maps work …

```elixir
iex(1)> %{foo: :foo, :bar => :bar}
** (SyntaxError) iex:1: syntax error before: bar

iex(1)> %{:bar => :bar, foo: :foo}
%{bar: :bar, foo: :foo}
```

Which shows that `=>` form should be used before keyword-like syntax. Otherwise it would fail.

**Comment by josevalim** [comment]
As all other parts in the language, they key: value syntax can only be used as the “last” argument.

**Comment by eksperimental** [comment]
> @eksperimental I think it's not strictly a `Typespec` thing, but how syntactic sugar for keyword-like syntax in maps works …
> 
> ```elixir
> iex(1)> %{foo: :foo, :bar => :bar}
> ** (SyntaxError) iex:1: syntax error before: bar
> 
> iex(1)> %{:bar => :bar, foo: :foo}
> %{bar: :bar, foo: :foo}
> ```
> 
> Which shows that `=>` form should be used before keyword-like syntax. Otherwise it would fail.

True. I totally overlooked at it. Thank you guys
