### ISSUE TITLE
If on-liner doesn't work when no space is given in between `if` and `(`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10282]
All of these combinations work.
```elixir
a = 1

if (a == 1), do: :one
if(a == 1) do :one end

if (a == 1) do :one; else :else end
if (a == 1), do: :one, else: :else
if a == 1, do: :one, else: :else
if(a == 1) do :one; else :else end
if(a == 1, do: :one, else: :else)
```

but this one does not
```elixir
a = 1
if(a == 1), do: :one
if(a == 1), do: :one, else: :else
```

You will get 
`** (SyntaxError) iex:3:11: syntax error before: ','`

**Comment by josevalim** [comment]
Correct. If you do `if(` then the parens are the parens of the call. Closing the parens, close the call. For `if (a == 1)`, the parens *wrap the first argument*.

**Comment by eksperimental** [comment]
> Correct. If you do `if(` then the parens are the parens of the call. Closing the parens, close the call. For `if (a == 1)`, the parens _wrap the first argument_.

Thank you for the clarification
