### ISSUE TITLE
Mix cannot compile rebar3 dep with overwritten pkg_name

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#10284]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 22 [erts-10.7.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.4 (compiled with Erlang/OTP 22)
* Operating system: macOS

### Current behavior

Mix cannot compile rebar3 dep with overwritten pkg_name

```
Unchecked dependencies for environment test:
* erlzmq_dnif (Hex package)
  could not find an app file at "_build/test/lib/erlzmq_dnif/ebin/erlzmq_dnif.app". Another app file was found in the same directory "_build/test/lib/erlzmq_dnif/ebin/erlzmq.app", try changing the dependency name to :erlzmq
** (Mix) Can't continue due to errors on dependencies
```

mix.exs deps
```
{:erlzmq_dnif, "4.0.0"},
```

erlzmq.app.src
```
{application,erlzmq,
             [{pkg_name,erlzmq_dnif},
...]}.
```

### Expected behavior

Should compile fine

**Comment by josevalim** [comment]
You should specify it as `{:erlzmq, "4.0.0", hex: :erlzmq_dnif}`. :)

**Comment by lukaszsamson** [comment]
Thanks @josevalim. It wasn't easy to find docs on that option as it differs from the rebar one.

**Comment by josevalim** [comment]
PR for docs are always welcome! :)
