### ISSUE TITLE
DateTime.add for LMT timezone doesn't use given offset

### ISSUE THREAD

**Issue by tjheeta** [elixir-lang/elixir#10281]
## Environment

Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
Elixir 1.10.4 (compiled with Erlang/OTP 23)
Ubuntu 18.04.4

### Current behavior

LMT (Local Mean Time) is a variable timezone that depends on longitude. 
```
iex> dt = DateTime.from_naive!(~N[1756-06-27 20:00:00], "Europe/Vienna")
#DateTime<1756-06-27 20:00:00+01:05 LMT Europe/Vienna>
```
However, since Mozart was actually born in Salzburg which has a longitude of 13.0443. In this case, we would adjust the timezone to be 52 minutes (4 minutes per degree longitude). 
```
iex> dt1 = %{dt | utc_offset: 13*4*60}
#DateTime<1756-06-27 20:00:00+00:52 LMT Europe/Vienna>
```
Adding and subtracting a second changes the offset to the original timezone from IANA. 
```
iex> DateTime.add(dt1, -1) |> DateTime.add(1)
#DateTime<1756-06-27 20:13:21+01:05 LMT Europe/Vienna>
```
Technically, this is the correct time, but shifted slightly. This can cause rather odd behaviour around midnight. Below is the actual time/bug I ran into and spent time debugging.

```
iex> dt = DateTime.from_naive!(~N[0100-01-01 00:00:00], "Europe/London")
#DateTime<0100-01-01 00:00:00-00:01 LMT Europe/London>
iex> dt1 = %{ dt | utc_offset: -35 }
#DateTime<0100-01-01 00:00:00-00:00 LMT Europe/London>
iex> DateTime.add(dt1, -86400) |> DateTime.to_date
~D[0099-12-30]
```

### Expected behavior

It would be nice if there was an offset that has been set in LMT to remain the same. 

This currently returns false, but would expect it to be true.
```
iex> dt = DateTime.from_naive!(~N[1756-06-27 20:00:00], "Europe/Vienna")
#DateTime<1756-06-27 20:00:00+01:05 LMT Europe/Vienna>
iex> dt1 = %{dt | utc_offset: 13*4*60}
#DateTime<1756-06-27 20:00:00+00:52 LMT Europe/Vienna>
iex> DateTime.add(dt1, -1) |> DateTime.add(1) == dt1 
true # This currently returns false
```

This currently returns ~D[0099-12-30], but would expect it to be ~D[0100-01-01]
```
iex> dt = DateTime.from_naive!(~N[0100-01-01 00:00:00], "Europe/London")
#DateTime<0100-01-01 00:00:00-00:01 LMT Europe/London>
iex> dt1 = %{ dt | utc_offset: -35 }
#DateTime<0100-01-01 00:00:00-00:00 LMT Europe/London>
iex> DateTime.add(dt1, -86400) |> DateTime.to_date
~D[0099-12-31] # This currently returns ~D[0099-12-30]
```

### Potential datetime.ex changes

I'm not sure if this is the correct place to add the change, but on first glance line 1069 of datetime.ex is:
      |> shift_zone_for_iso_days_utc(calendar, precision, datetime.time_zone, time_zone_database)

As far as I can see, this function needs to take the current utc_offset and if the zone_abbr == "LMT", use it instead of looking up from the tz database in line 452 if the new time is still LMT.

This will preserve any manually added LMT offset while allowing any other timezone changes to occur on date changes. I haven't looked through the rest of the calling functions yet, such as DateTime.shift_zone, which this change may affect.

**Comment by josevalim** [comment]
You should not change the utc_offset directly. If you change it, then whenever we need to round trip to the timezone database, your changes will be lost.

Which timezone database are you using? If you want to preserve LMT, then you need a LMT aware database and you need to reflect this information on the timezone name. For example: "Europe/London/13.0443".

**Comment by tjheeta** [comment]
Ah, that does seem like a nicer way to do it. It doesn't appear that either of the tz databases I know of support it. What am I missing?

```
iex> Calendar.get_time_zone_database
Tz.TimeZoneDatabase
iex> DateTime.from_naive!(~N[0100-01-01 00:00:00], "Europe/London")
#DateTime<0100-01-01 00:00:00-00:01 LMT Europe/London>
iex> DateTime.from_naive!(~N[0100-01-01 00:00:00], "Europe/London/13.04")
DateTime.from_naive!(~N[0100-01-01 00:00:00], "Europe/London/13.04")
** (ArgumentError) cannot convert ~N[0100-01-01 00:00:00] to datetime, reason: :time_zone_not_found
    (elixir 1.10.4) lib/calendar/datetime.ex:400: DateTime.from_naive!/3
```


```
iex> Calendar.get_time_zone_database
Tzdata.TimeZoneDatabase
iex> DateTime.from_naive!(~N[0100-01-01 00:00:00], "Europe/London")
#DateTime<0100-01-01 00:00:00-00:01 LMT Europe/London>
iex> DateTime.from_naive!(~N[0100-01-01 00:00:00], "Europe/London/13.04")
** (ArgumentError) cannot convert ~N[0100-01-01 00:00:00] to datetime, reason: :time_zone_not_found
    (elixir 1.10.4) lib/calendar/datetime.ex:400: DateTime.from_naive!/3


```

**Comment by josevalim** [comment]
It will probably be out of the scope for those libraries to implement LMT. You would have to create your own calendar database library (which could be a wrapper on those libraries with the additional handling).
