### ISSUE TITLE
Impossible to pass `&//2` as a parameter

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/elixir#10311]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.10.1 (compiled with Erlang/OTP 22)`
* Operating system: Ubuntu 18.04

### Current behavior

Parsing errors when `&//2` is followed by a comma:

```elixir
iex> apply(&//2, [1, 2]) 
** (CompileError) iex:3: undefined function apply/1
iex> {&//2, :op}
** (SyntaxError) iex:6: unexpected comma. Parentheses are required to solve ambiguity inside containers.

This error may happen when you forget a comma in a list or other container:

    [a, b c, d]

Or when you have ambiguous calls:

    [one, two three, four, five]

In the example above, we don't know if the parameters "four" and "five" belongs to the list or the function "two". You can solve this by explicitly adding parentheses:

    [one, two(three, four), five]

Elixir cannot compile otherwise. Syntax error before: ','
```

The following work though: 
```elixir
# with other operators
iex> apply(&*/2, [1, 2]) 
2
# when not followed by a comma
iex> {:op, &//2}  
{:op, &:erlang.//2}
iex> inspect(&//2)               
"&:erlang.//2"
# with brackets
iex> apply((&//2), [1, 2])
0.5
```

Interestingly, the formatter removes the brackets when I tried them as a workaround. I eventually managed to hack around by defining a constant: `@div &//2`.

### Expected behaviour

Ideally:
```elixir
iex> apply(&//2, [1, 2]) 
0.5
```

But if not working due to a legit reason / known limitation, it might good to at least make sure the formatter doesn't remove the needed bracket.

I think I've got a working PR, will try to open it.

**Comment by eksperimental** [comment]
It is not impossible. You just need to use parentheses

```elixir
iex(1)> apply(&(//2), [1, 2]) 
0.5

iex(2)> {&(//2), :op}
{&:erlang.//2, :op}
```

**Comment by sabiwara** [comment]
> It is not impossible. You just need to use parentheses
> 
> ```elixir
> iex(1)> apply(&(//2), [1, 2]) 
> 0.5
> 
> iex(2)> {&(//2), :op}
> {&:erlang.//2, :op}
> ```

Indeed, as I mentioned it, but they get removed by the formatter :slightly_smiling_face:

**Comment by eksperimental** [comment]
Oh, I see. Definitely something to be fixed

**Comment by josevalim** [comment]
There is definitely a bug here if you compare the ASTs:

```
iex(4)> quote do: apply(&//2, [1, 2])
{:apply, [],
 [
   {:&, [],
    [{:/, [context: Elixir, import: Kernel], [{:/, [], Elixir}, 2]}, [1, 2]]}
 ]}
iex(5)> quote do: apply(&+/2, [1, 2])
{:apply, [context: Elixir, import: Kernel],
 [
   {:&, [import: Kernel, context: Elixir],
    [{:/, [context: Elixir, import: Kernel], [{:+, [], Elixir}, 2]}]},
   [1, 2]
 ]}
```

I will take a look at the PR!
