### ISSUE TITLE
python reference in docs outdated/unnecessary? 

### ISSUE THREAD

**Issue by mario-mazo** [elixir-lang/elixir#10314]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.4 (compiled with Erlang/OTP 23)
* Operating system: MacOS

### Current behavior
Hello while reading the docs I saw this line

> ExUnit.DocTest implements functionality similar to [Python's doctest](https://docs.python.org/2/library/doctest.html).

https://github.com/elixir-lang/elixir/blob/749459a32fc576864a6b98dcc1f0f45329a54b9f/lib/ex_unit/lib/ex_unit/doc_test.ex#L3

So the first thing is... I know is unlikely but what if I dont know what Python doctests are? wouldn't be better to explain it here in "local" terminology instead of forwarding people there? This can be particularly strange/discouraging for people learning elixir as a first language  

Also it points to a deprecated version of the python docs

### Expected behavior

explain what a doc test is here or update the link to current python documentation

**Comment by wojtekmach** [comment]
I believe the next very next paragraph tries to explain what doctests are but it of course could be improved further. I always thought mentioning Python's doctests was giving credit where credit was due but maybe moving things around would make things clearer.

**Comment by mario-mazo** [comment]
Yes the explanation is there. But having the first line as a python reference shows up like this (at least in my resolution) when you hover over the `ExUnit.DocTest`

![Screenshot 2020-09-09 at 22 23 37](https://user-images.githubusercontent.com/30439204/92656191-e5d26600-f2f2-11ea-9762-223fc66134c1.png)

**Comment by josevalim** [comment]
We do inherit a lot from other languages and we are very open about it in many channels but I agree the documentation is not the best place to do it. :) thanks @mario-mazo
