### ISSUE TITLE
Keyword.replace/3 does not return the exact same result as Keyword.replace!/3

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10345]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): v1.11.0-rc / OTP 23

### Current behavior
```elixir
iex(1)> Keyword.replace([a: 1, b: 2, a: 4, a: 5, b: 6], :b, 1)
[b: 1, a: 1, a: 4, a: 5]

iex(2)> Keyword.replace!([a: 1, b: 2, a: 4, a: 5, b: 6], :b, 1)
[a: 1, b: 1, a: 4, a: 5]

```
### Expected behavior

While both results are considered equal by `Keyword.equal?/2`, I think to avoid unexpected results, they should be returned in the same order.

I personally prefer the ordered returned by `replace!/3`, but I have the feeling that the `replace/3` implementation is more performant, I haven't test it though

**Comment by josevalim** [comment]
Note ordering is not guaranateed but it doesn't hurt to make these funs consistent. Thanks!

**Comment by eksperimental** [comment]
:+1:
