### ISSUE TITLE
Document reserved @struct attribute

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10352]
defining `@struct` before defstruct makes defstruct to raise.

```elixir
defmodule Foo do
  @struct config: false
  @enforce_keys Keyword.keys(@struct)
  defstruct @struct
end
```

```
== Compilation error in file lib/foo.ex ==
** (ArgumentError) defstruct has already been called for Foo, defstruct can only be called once per module
```

This reserved struct is not documented. I think it could be added before the "Typespec attributes" section in the `Module` module.
Additionally it could also be documented `@enforce_keys`

I can contribute a PR once agreed on

**Comment by josevalim** [comment]
It sounds like it is an implementation detail we should not be exposing so I would rather rename it to @__struct__. I believe we access it on elixir_erl.erl though, so we need to change it there too.

**Comment by eksperimental** [comment]
> It sounds like it is an implementation detail we should not be exposing so I would rather rename it to @**struct**. I believe we access it on elixir_erl.erl though, so we need to change it there too.

Sorry, it is already named `@struct`

**Comment by eksperimental** [comment]
I think you meant `@__struct__` but github formatted your code

**Comment by eksperimental** [comment]
I have submitted a PR.
The other thing left is that if we want to document `@enforce_keys` in the `Module` module
