### ISSUE TITLE
HKCU\\Console seems to be invalid. HKCU\Console works

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [elixir-lang/elixir#10357]
`HKCU\\Console` seems to be invalid.
`HKCU\Console` works fine.

```
C:\Gateway
λ reg add HKCU\\Console /v VirtualTerminalLevel /t REG_DWORD /d 1
ERROR: Invalid key name.
Type "REG ADD /?" for usage.

C:\Gateway
λ reg add HKCU\Console /v VirtualTerminalLevel /t REG_DWORD /d 1
The operation completed successfully.
```
https://github.com/elixir-lang/elixir/blob/de2010649db4552a0d9cde59ff4e94e2f339bb35/lib/elixir/lib/io/ansi.ex#L30

Please confirm.

Windows 10, ConEmu

**Comment by josevalim** [comment]
It is escaped in the source code to work with Elixir strings. But in the docs it appears correctly: https://hexdocs.pm/iex/master/IEx.html#module-coloring :) Thanks!
