### ISSUE TITLE
Why I can't install elixir with erlang 23+ on FreeBSD

### ISSUE THREAD

**Issue by alaadahmed** [elixir-lang/elixir#10368]
Trying install elixir on __FreeBSD 12.1__, but I couldn't manage to install it with __Erlang 23+__.
I used `pkg` and also tried to `make install` from `/usr/ports/lang/elixir` but the same, it always install with __Erlang 21__.

<img width="1166" alt="Screen Shot 2020-09-24 at 21 23 18" src="https://user-images.githubusercontent.com/14099508/94190609-9f613780-feac-11ea-8608-152f18fdf444.png">

Because I develop with __Elixir 1.10.4__ with __Erlang 23.1__ on my local machine, and I doubt maybe I will face some issues when I recompile it on my __FreeBSD__ server.

**Comment by josevalim** [comment]
Hi @alaadahmed ! I recommend reaching out to Elixir Forum (or similar) for support because this seems to be a FreeBSD issue in particular. Maybe you can explicitly ask it to install Erlang before? We don’t maintain the Erlang packages for FreeBSD so it is not an area we have expertise with. Thanks!

**Comment by Eiji7** [comment]
@alaadahmed I have used `FreeBSD` before, so here goes some useful links:
1. [erlang makefile in lang port](https://svnweb.freebsd.org/ports/head/lang/erlang/Makefile?view=markup)
2. [elixir makefile in lang port](https://svnweb.freebsd.org/ports/head/lang/elixir/Makefile?view=markup)

(those 2 should give you answer about current FreeBSD support)

3. [similar thread on elixirforum.com](https://elixirforum.com/t/freebsd-and-elixir-1-5-and-otp-20-will-i-have-to-install-and-compile-them-from-the-source-code/7795?u=eiji)
4. [asdf version manager I recommend](https://asdf-vm.com) and [FreeBSD issue](https://github.com/asdf-vm/asdf-erlang/pull/37) confirms that `asdf` works on `FreeBSD`
5. [erlang installation guide](https://erlang.org/doc/installation_guide/INSTALL.html#required-utilities) for a list of dependencies before you start to use version manager

As said if you have some problems during installation feel free to create a post on Elixir Forum.

**Comment by alaadahmed** [comment]
Thanks you @Eiji7 
I already checked these two specific files, problem is the one of Erlang
You can't install Erlang lang 23+, but you can install Erlang-Runtime23
and Elixir needs Erlang itself. 
I mean on FreeBSD ports, the highest version of erlang __lang__ is 21+, but __runtime__ is 23+

Here is the MakeFile for erlang lang port 😔
<img width="296" alt="Screen Shot 2020-09-25 at 00 15 14" src="https://user-images.githubusercontent.com/14099508/94205937-94b29c80-fec4-11ea-9271-c32db2966175.png">


Here is the MakeFile for Elixir, no problem with it, it specifies erlang dep is >= 21+, problem is to find it in FreeBSD ports 😅
<img width="898" alt="Screen Shot 2020-09-25 at 00 15 47" src="https://user-images.githubusercontent.com/14099508/94205948-9bd9aa80-fec4-11ea-8270-bbec30831549.png">
