### ISSUE TITLE
Compiler crash on list operators in guards

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#10361]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.4 (compiled with Erlang/OTP 23)
```
* Operating system: macOS

### Current behavior

Given the following module:
```elixir
# foo.ex
defmodule Foo do
  def check(value) do
    case value do
      list when list ++ [1] -> list
    end
  end
end
```

running `elixir foo.ex` crashes with
```
** (ArgumentError) argument error
    (stdlib 3.13) :unicode.characters_to_binary(Foo)
    (elixir 1.10.4) src/elixir_utils.erl:125: :elixir_utils.characters_to_binary/1
    (elixir 1.10.4) src/elixir_erl_compiler.erl:76: anonymous fn/1 in :elixir_erl_compiler.format_errors/1
    (stdlib 3.13) lists.erl:1338: :lists.foreach/2
    (elixir 1.10.4) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
```
### Expected behavior

This program should be rejected with a nice error, Erlang does not support `++` and `--` in guards (nor does it allow `!`).

**Comment by eksperimental** [comment]
@michalmuskala I have found the bug, it is describe in this comment https://github.com/elixir-lang/elixir/pull/10363#issuecomment-697111564

**Comment by michalmuskala** [comment]
Closed by https://github.com/elixir-lang/elixir/pull/10363
