### ISSUE TITLE
Infinity NProgress, when Re-login on Brave browser.

### ISSUE THREAD

**Issue by Bogdan1001** [elixir-lang/elixir#10375]
I faced a problem. On two browsers, everything works ok (Firefox and Chrome), but on Brave browser, I noticed the following behavior I use gen_auth for authentication, the essence of the problem:
1. I register a new user
2. I log out
3. Log in back
4. NProgress cannot load, as if something is loading. There are no warning errors in the console; everything is clean. The app as a whole function correctly; the only visual thing with infinity loading NPrograss and only on the Brave browser.

P.S. I am not sure is it Live View issue.

**Comment by josevalim** [comment]
You probably wanted to fill it in the LiveView repo :) note we already have an issue there about nprogress, so it is probably related! :)
