### ISSUE TITLE
Incompatible types binary() !~ map() in nested map pattern match

### ISSUE THREAD

**Issue by dmorneau** [elixir-lang/elixir#10371]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.0-dev (75726d5) (compiled with Erlang/OTP 23)
* Operating system: macOS

### Current behavior

Compiling this module causes a type warning:

```
defmodule Test do
  def handle(%{"type" => "order"} = event) do
    %{"amount" => amount} = event
    %{"user" => user} = event
    %{"id" => user_id} = user
    {:order, user_id, amount}
  end
end
```

```
warning: incompatible types:

    binary() !~ map()

in expression:

    # sample.ex:5
    %{"id" => user_id} = user

where "user" was given the same type as "amount" in:

    # sample.ex:4
    %{"user" => user} = event

where "user" was given the type map() in:

    # sample.ex:5
    %{"id" => user_id} = user

where "amount" was given the type binary() in:

    # sample.ex:3
    %{"amount" => amount} = event

where "amount" was given the type binary() in:

    # sample.ex:3
    %{"amount" => amount} = event

where "amount" was given the type binary() in:

    # sample.ex:3
    %{"amount" => amount} = event

Conflict found at
  sample.ex:5: Test.handle/1
```

If I do the pattern match in one line `%{"user" => %{"id" => user_id}} = event`, the warning becomes very complicated.

### Expected behavior

I don't think there should be a type warning, the code behaves fine:

```
iex(22)> Test.handle(%{"type" => "order", "amount" => 100, "user" => %{"id" => 1}})
{:order, 1, 100}
```

I also found it curious that the `"amount" was given the type binary()` part of the warning was repeated 3 times with the exact same message.

**Comment by eksperimental** [comment]
I agree. If instead of strings as keys we use atoms, no warning is emitted.

Also, the `!~` operator does not exist in Elixir. If this is a special operator used for types it should at least be documented.

**Comment by eksperimental** [comment]
It also happens in v1.11.0-rc0

**Comment by wingyplus** [comment]
If I do like an example below in Elixir 1.11.0-rc.0, the warning will disappear:

```elixir
defmodule Test do
  def handle(%{"type" => "order"} = event) do
    %{"amount" => amount, "user" => user} = event
    %{"id" => user_id} = user
    {:order, user_id, amount}
  end
end
```
