### ISSUE TITLE
`Config.config/3` overwrites previous keyword lists when called from `config/runtime.exs`

### ISSUE THREAD

**Issue by nathanl** [elixir-lang/elixir#10379]
#### Elixir & Erlang/OTP versions (elixir --version):

Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.0-rc.0 (48cee5a) (compiled with Erlang/OTP 21)

#### Operating system

MacOS Catalina (10.15.6)

### Current behavior

When called from `config/runtime.exs`, `Config.config/3` overwrites previous keyword lists rather than deep merging with those set in `config/config.exs` and other compile-time config files.

Possibly this works differently in `config/runtime.exs` because the process dictionary calls happen in a different process?

### Expected behavior

`Config.config/3` should deep merge keyword lists with those set in other config files, as calls from other config files do.

### Demo

Please see this minimal demo repo: https://github.com/nathanl/config_demo

**Comment by ericmj** [comment]
Please try the `master` branch. A similar issue was opened and fixed recently: https://github.com/elixir-lang/elixir/issues/10365.

**Comment by nathanl** [comment]
Yep, that fixed it. Sorry I didn't see that issue.
