### ISSUE TITLE
Make IEx parser customizable

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#10390]
This is a proposal to address #10372.

The parser is a MFArgs which receives the current input, the parsing options, and the buffer. It returns either `{:ok, expr, buffer}` or `{:incomplete, buffer}`. Buffer always starts as an empty string. Here is the default implementation:

```elixir
@break_trigger "#iex:break\n"

def parse(@break_trigger, _opts, "") do
  {:incomplete, ""}
end

def parse(@break_trigger, opts, _buffer) do
  :elixir_errors.parse_error([line: opts[:line]], opts[:file], "incomplete expression", "")
end

def parse(input, opts, buffer) do
  input = buffer <> input
  
  case Code.string_to_quoted(input, opts) do
    {:ok, forms} ->
      {:ok, forms, ""}

    {:error, {_, _, ""}} ->
      {:incomplete, input}

    {:error, {location, error, token}} ->
      :elixir_errors.parse_error(location, opts[:file], error, token)
  end
end
```

This code was extracted [from the evaluator](https://github.com/elixir-lang/elixir/blob/master/lib/iex/lib/iex/evaluator.ex#L204), which should be changed to call a configurable MFArgs. The options are `[file: "iex", line: iex_state.counter]`. If the parser raises, the buffer is reset to an empty string. 

The parser shall be configurable via `IEx.configure`. A PR is welcome!

**Comment by wojtekmach** [comment]
I believe this can be closed thanks to #10394.
