### ISSUE TITLE
URI.parse/1 will treat host as a path when scheme is missing

### ISSUE THREAD

**Issue by freshtonic** [elixir-lang/elixir#10395]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

elixir 1.10.3-otp-22
erlang 22.3.2

* Operating system: 

MacOS

### Current behavior

Incorrect:

```
iex(4)> URI.parse("example.com")                           
%URI{
  authority: nil,
  fragment: nil,
  host: nil,
  path: "example.com",  # <-- host is misidentified as the path here.
  port: nil,
  query: nil,
  scheme: nil,
  userinfo: nil
}
```

Correct:
```
iex(5)> URI.parse("http://example.com")
%URI{
  authority: "example.com",
  fragment: nil,
  host: "example.com",
  path: nil,
  port: 80,
  query: nil,
  scheme: "http",
  userinfo: nil
}
```

### Expected behavior

I would expect `URI.parse/1` to correctly assign the host in the returned struct when the scheme is not present.

**Comment by freshtonic** [comment]
Closing because scheme is mandatory

**Comment by josevalim** [comment]
Yes, this is according to the linked RFC. IIRC, browsers will behave the same in links, for example. You can write it as `//example.com` if you want just the host.
