### ISSUE TITLE
Mix.target not respected when starting application

### ISSUE THREAD

**Issue by ConnorRigby** [elixir-lang/elixir#10405]
For Nerves we use `Mix.target()` and `targets: ` in dependencies to control which apps get started on a device
compared to which apps get started on the host machine. When supplying a `target` dependency, elixir tries to start it even
tho it isn't compiled.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.11.0 (compiled with Erlang/OTP 23)
```

* Operating system: 
```sh
$ uname -a                                                                                                                                                                                      
Linux connor-mini-pc 5.8.12-arch1-1 #1 SMP PREEMPT Sat, 26 Sep 2020 21:42:58 +0000 x86_64 GNU/Linux
```

### Current behavior

Adding a mix dep that should only be available for a particular target prevents
starting the app. 

```elixir
  defp deps do
    [
       {:some_app_only_for_target, "~> 0.1", targets: [:some_target1, :some_target2]}
    ]
  end
```

```
$ iex -S mix
** (Mix) Could not start application some_app_only_for_target: could not find application file: some_app_only_for_target.app
```

### Expected behavior

App should start without that target dependency needing to be started.

**Comment by ConnorRigby** [comment]
I'm trying to make a small project to reproduce right now. having a bit of trouble tho. there's something subtle in our new project generator causing this as far as i can tell..

**Comment by mobileoverlord** [comment]
[target_example.zip](https://github.com/elixir-lang/elixir/files/5335403/target_example.zip)

This is a plain mix project that exercises the issue. If you cd in to target_run and call `iex -S mix` you should receive
```
Erlang/OTP 23 [erts-11.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Compiling 1 file (.ex)
Generated target_run app
** (Mix) Could not start application target_dep: could not find application file: target_dep.app
```

**Comment by ConnorRigby** [comment]
> I'm trying to make a small project to reproduce right now. having a bit of trouble tho. there's something subtle in our new project generator causing this as far as i can tell..

Whoops, i wasn't using elixir 1.11 to reproduce :flushed: thanks Justin
