### ISSUE TITLE
fully qualifying a macro in the current module produces a warning about needing to require it

### ISSUE THREAD

**Issue by jjl** [elixir-lang/elixir#10401]
```
warning: you must require CommonsPub.Circles.Circle.Migration before invoking the macro CommonsPub.Circles.Circle.Migration.create_circle_table/1
  lib/circle.ex:53: CommonsPub.Circles.Circle.Migration.migrate_circle/1
```

**Comment by josevalim** [comment]
Thanks for the report. I am unsure if we should allow this to work or rather raise. In Elixir, `Mod.foo()` is different than just `foo()` and you shouldn't be able to call a remote macro while your are still being defined.

**Comment by jjl** [comment]
I agree in principle, but in practice it would mean duplicating a lot of code in the case where you have a macro that expands to a macro invocation in the current module and then want to also expose a function using it again in the same module (the situation i am in).
