### ISSUE TITLE
GenServer: Using super() on `child_spec/1` should not show a deprecation warning

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/elixir#10415]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.3 / otp: 22
* Operating system: macOS

### Current behavior

When you try to override the default `child_spec/1` function in a `GenServer`, so, we can set the `id` dynamically:

```elixir
iex(1)> defmodule Sample do
...(1)>   use GenServer
...(1)>
...(1)>   def child_spec(opts) do
...(1)>     id = Keyword.get(opts, :portal, :something)
...(1)>     opts |> super() |> Supervisor.child_spec(id: :"#{id}_bla")
...(1)>   end
...(1)> end
```

You get the following warning:

```elixir
warning: calling super for GenServer callback child_spec/1 is deprecated
  iex:6: Sample.child_spec/1
```

But, if you try to the same with a `Supervisor`, you don't get any warning:

```elixir
iex(2)> defmodule Demo do
...(2)>   use Supervisor
...(2)>
...(2)>   def child_spec(opts) do
...(2)>     id = Keyword.get(opts, :portal, :something)
...(2)>     opts |> super() |> Supervisor.child_spec(id: :"#{id}_bla")
...(2)>   end
...(2)> end
```

I _believe_ that the issue was introduced after this [change](https://github.com/elixir-lang/elixir/commit/c024b0eeb2dc69a759fe5ceeb1c8216d58ae9386#diff-ed0344c13ed25389035f337d94902894R301-R316).  Based on José's comment, he wanted to deprecate the usage of `super` on the GenServer _callbacks_, but `child_spec/1` is not a callback, is just a default implementation that is `overridable`. So, I think we should exclude `child_spec/1` from that warning, wdyt?

### Expected behavior

Be able to override `child_spec/1` in a `GenServer` without getting any _deprecation warning_, same as we can do with a `Supervisor`.

**Comment by josevalim** [comment]
You are correct. :heart: We should fix it but I also want to point out that the solution is likely cleaner if you are not using `super`, so I wouldn't use it anyway. :)

**Comment by milmazz** [comment]
Thanks, @josevalim. I followed your advice, and also that way, I avoid the deprecation warning. I agree with you; the intention is more explicit without the `super()`. But, I guess that a PR is still welcome, right?

**Comment by josevalim** [comment]
> But, I guess that a PR is still welcome, right?

Yes!
