### ISSUE TITLE
Unclear docs about config/runtime.exs

### ISSUE THREAD

**Issue by fxn** [elixir-lang/elixir#10413]
The current docs for `config/runtime.exs` are

> For runtime configuration, you can use the config/runtime.exs file. It is executed after your Mix project is compiled and also before a release (assembled with mix release) starts.

I do not understand this sentence:

> It is executed after your Mix project is compiled

when a project is compiled, as in `mix compile` or when building a Docker image, anything executed is executed in the void, you see what I mean :).

Does that mean "before the application starts"?

**Comment by fxn** [comment]
Hmmm, since `config/runtime.exs` is meant to replace `config/releases.exs` in modern projects, I believe the value of `config_env()` for releases should be documented too...

Maybe I could dig into all this a bit and propose a doc patch.

**Comment by josevalim** [comment]
Maybe it is best to say: "it is executed after all modules are compiled and before applications start in both Mix and releases"?

> , I believe the value of config_env() for releases should be documented too...

`config_env()` will be the environment variable the release was assembled in.

Let me know if you want to make these changes or you will submit a PR cause I am not sure right now which page you are looking at. :D

**Comment by fxn** [comment]
> it is executed after all modules are compiled and before applications start in both Mix and releases

I believe I understand what you try to transmit, but if the docs say "it is executed after all modules are compiled and ...", in particular it is executed "after all modules are compiled". But if you run `mix compile` all modules are compiled and the file is not executed!

Basically, we want to say "this is not executed at compile time, but at runtime", right?

> Let me know if you want to make these changes or you will submit a PR cause I am not sure right now which page you are looking at. :D

LOL, I was referring to https://hexdocs.pm/elixir/master/Config.html.

**Comment by josevalim** [comment]
If we said "It is executed right before applications start in both Mix and releases" it would also be correct, so we can go with that instead? :)

**Comment by fxn** [comment]
> If we said "It is executed right before applications start in both Mix and releases" it would also be correct, so we can go with that instead? :)

Awesome! Firing the editor like a rocket!

**Comment by josevalim** [comment]
Closing in favor of PR!
