### ISSUE TITLE
Protocol.UndefinedError stack trace can be a bit cryptic

### ISSUE THREAD

**Issue by pera** [elixir-lang/elixir#10425]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```
* Operating system: 
```
Arch Linux
```

### Current behavior

Calling a function like `def test(), do: Enum.map(nil, fn x -> x end)` produces the following error message:
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Function, List, Map, IO.Stream, HashDict, GenEvent.Stream, Date.Range, Range, HashSet, Stream, MapSet, File.Stream
    (elixir 1.10.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.10.3) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.10.3) lib/enum.ex:3383: Enum.map/2
```

### Expected behavior

I am actually not sure if this is an unexpected behavior at all, but I would personally expect to see a stacktrace that includes at least the function that caused the error. In some cases part of the stacktrace is actually included in the error message, but it's not complete (i.e. the actual function that produces the error is not included) and can be a bit difficult to interpret/debug.

**Comment by josevalim** [comment]
Nothing we can do here because of tail call optimization. The last call will always be removed and it is part of the language runtime. In any case, thanks for the report!

**Comment by michalmuskala** [comment]
This is not specific to `Protocol.UndefinedError`, but a more general issue that results from the tail call omission that Erlang VM performs.

It's an optimisation that allows tail-recursive calls not to grow stacks, but it results in all tail calls from being omitted from stacktraces (since they don't have a stack entry). This is especially important for infinite loops in `GenServers` or loops in general.

I'm not sure there is much that can be done in here from Elixir dise.

**Comment by pera** [comment]
@michalmuskala thanks that makes perfect sense. It would be helpful if somehow the Erlang's stack trace included some form of notice/mark when TCO is performed within a function, so if you had something like:
```elixir
  def f do
    [1,2,3]
    |> Enum.map(fn x -> g(x) end)
    |> IO.inspect() # to avoid TCO here
  end

  def g(xs) do
    h(xs)
  end

  # ...far away in your code
  def h(_xs) do
    Enum.map(nil, fn x -> x end)
  end
```

The call-stack back trace in the error message would add a `*` (for instance):
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): Function, List, Map, IO.Stream, HashDict, GenEvent.Stream, Date.Range, Range, HashSet, Stream, MapSet, File.Stream
    (elixir 1.10.3) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.10.3) lib/enum.ex:141: Enumerable.reduce/3
    (elixir 1.10.3) lib/enum.ex:3383: Enum.map/2
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
   *(elixir_test 0.1.0) lib/elixir_test.ex:19: ElixirTest.f/0
```
(I got very confused when I read a stacktrace like this one this morning since it was extremely unlikely that the value passed to the map in f() wasn't a list but a nil, and of course I wasted some time trying to figure out how that value wasn't a list :laughing: )
