### ISSUE TITLE
Compiler should not warn about deprecations in @deprecated function

### ISSUE THREAD

**Issue by redrabbit** [elixir-lang/elixir#10443]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.0 (compiled with Erlang/OTP 23)
```

* Operating system:

```
macOS Catalina
MacBook Pro (Retina, 15-inch, Late 2013)
```

### Current behavior

When a function has the `@deprecated` attribute, the compiler should not warn about deprecations within that function.

For example, [`Plug.Conn.WrapperError.reraise/3`](https://github.com/elixir-plug/plug/blob/d685f4548beaec9558b650d84690fc9e6c544d5c/lib/plug/conn/wrapper_error.ex#L21) is marked as deprecated. Internally, the function calls [`System.stacktrace/0`](https://hexdocs.pm/elixir/System.html#stacktrace/0) which is deprecated as well (and the reason why `reraise/3` has been deprecated in the first place).

```
==> plug
Compiling 1 file (.erl)
Compiling 40 files (.ex)
warning: System.stacktrace/0 is deprecated, use __STACKTRACE__ instead
  lib/plug/conn/wrapper_error.ex:23

Generated plug app
```

### Expected behavior

The compiler should not warn about deprecated code inside functions tagged with `@deprecated`.

If a function is deprecated and still available, it's there for compatibility reasons (version semantic, deprecation policy, etc.).

**Comment by josevalim** [comment]
I don’t think that’s generally true. Maybe a function was deprecated before Elixir deprecated function. Maybe a function is invoking two other functions from different libraries that were deprecated at distinct times, etc.

Even if we did this, it is not a trivial check to add. What if the deprecated call came from a private function referenced exclusively from the publicly deprecated one?

For all of the reasons, I don’t think this is a bug, nor a behavior we should add. Thanks!
