### ISSUE TITLE
relax formatting for a single line break at the end of modules

### ISSUE THREAD

**Issue by chapmanjacobd** [elixir-lang/elixir#10456]
The formatter is basically perfect but there is one very tiny thing which could be more clear.

### Current behavior

```ex
defmodule HelloWeb.PageController do
  use HelloWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end
```

### Expected behavior

Additional vertical space makes the last `end` less ambiguous. It is part of the module and not part of def:index.

I am not suggesting changing the default but relaxing the current config of 0 lines to 0 or 1 lines.

```ex
defmodule HelloWeb.PageController do
  use HelloWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end

end
```

**Comment by josevalim** [comment]
Hi @chapmanjacobd! We know devs have some preferences to certain aspects of the formatter but we have no plans to make further changes to it. While you probably prefer a newLine there, I am sure other developers prefer the current style, and such a change would only generate churn. Therefore we will keep things as is, thanks!
