### ISSUE TITLE
Application boundaries warnings not showing up

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#10452]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
$ elixir --version
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.11.1 (compiled with Erlang/OTP 23)
```
* Operating system: Ubuntu 18.04.5 LTS

### Current behavior
Application boundaries warnings added in https://github.com/elixir-lang/elixir/commit/9d56a019ee0fe9475a61583f26f815e4bdf5717b are not reliably showing up in a umbrella project. Reproduction repository: https://github.com/michallepicki/missing-boundary-warning-example

```
$ mix compile --warnings-as-errors
==> child_app_c
Compiling 1 file (.ex)
Generated child_app_c app
==> child_app_b
Compiling 1 file (.ex)
Generated child_app_b app
==> child_app_a
Compiling 1 file (.ex)
Generated child_app_a app
$ echo $?
0
```

### Expected behavior
Elixir compilation warns about [this call](https://github.com/michallepicki/missing-boundary-warning-example/blob/ff36d797c4d82b0440fcf81d022320013e1fed63/apps/child_app_a/lib/child_app_a.ex#L16) from `child_app_a` to `child_app_c`

I can see there's a recent commit related to application tracers on master so I will try to see if it fixes the issue or not.

**Comment by michallepicki** [comment]
Tried with Elixir `272303e`, same result:
```
$ elixir --version
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [hipe]

Elixir 1.12.0-dev (272303e) (compiled with Erlang/OTP 23)
$ mix do clean, compile --warnings-as-errors
==> child_app_c
Compiling 1 file (.ex)
Generated child_app_c app
==> child_app_b
Compiling 1 file (.ex)
Generated child_app_b app
==> child_app_a
Compiling 1 file (.ex)
Generated child_app_a app
$ echo $?
0
```

**Comment by michallepicki** [comment]
Maybe that's expected because it is an indirect dependency? But the warning that was added and the [1.11 announcement](https://elixir-lang.org/blog/2020/10/06/elixir-v1-11-0-released/#compiler-checks-application-boundaries) say
> but the current application does not directly depend
and
> it requires child applications to explicitly list their dependencies

so I thought using indirect dependencies without listing them explicitly is disallowed as well

**Comment by wojtekmach** [comment]
> Maybe that's expected because it is an indirect dependency?

Yeah, that's how it works. But I also agree that seeing it needs to **directly** depend is misleading.

Btw, an even easier way to reproduce it is creating a new project and putting a call to `:crypto.version()`, we'll get the warning, but we can silence it by setting `extra_applications: [:ssl]` (ssl depends on crypto)

**Comment by josevalim** [comment]
It is poor wording on the announcement. I will fix both the changelog and the announcement, thank you.
