### ISSUE TITLE
Tried to ask this question but question was closed at stackoverflow. Can anyone quickly answer it please?

### ISSUE THREAD

**Issue by hiqsociety** [elixir-lang/elixir#10465]
Trying to use phoenix as a web application firewall to block DDOS like attacks. is it advisable to write a WAF using phoenix? else, what should be fronting phoenix as a firewall? i cant use iptables because i would like to block bad / missed IPs from cloudflare. it's already fronted by cloudflare but cloudflare doesnt block everything.

i'm totally newbie to erlang / phoenix / elixir etc. since it's running concurrently, how do i ensure that the ip gotten is blocked specifically? meaning, can i specifically route ip to process? or i cant? or i shouldnt?

**Comment by josevalim** [comment]
Can you please try the Elixir Forum? As the issue template says, we don't really answer questions here, as we want to focus on actionable issues. Thank you.
