### ISSUE TITLE
warning: variable "me" is unused (if the variable is not meant to be used, prefix it with an underscore)

### ISSUE THREAD

**Issue by RaymondLoranger** [elixir-lang/elixir#10478]
Erlang/OTP 21 [erts-10.3] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.11.1 (compiled with Erlang/OTP 21)

```elixir
test "returns %Game{} given valid args" do
  me = self()
  assert %Game{
               name: "Aveline",
               player1: %Player{name: "Jordan", gender: :m, pid: me}
             } = Game.new("Aveline", "Jordan", :m, me)
  end
```

See https://hex.pm/packages/islands_game

**Comment by maennchen** [comment]
@RaymondLoranger I believe this should be:

```elixir
assert %Game{
               name: "Aveline",
               player1: %Player{name: "Jordan", gender: :m, pid: ^me}
             } = Game.new("Aveline", "Jordan", :m, me)
```

(See the `^` before the variable)

**Comment by maennchen** [comment]
https://elixir-lang.org/getting-started/pattern-matching.html#the-pin-operator

**Comment by josevalim** [comment]
Thanks @maennchen for the help! :heart:

**Comment by josevalim** [comment]
Actually, I think we can improve the warning here. If there is an existing me variable, we could say they can use the pin operator to match on it. :D

**Comment by maennchen** [comment]
@josevalim Sure, thanks for you doing it all the time :)

I agree, that would be super helpful (especially since it's not the first time that I've seen that question).

**Comment by RaymondLoranger** [comment]
Many thanks!

**Comment by josevalim** [comment]
Hi @RaymondLoranger , if you don't mind i want to keep this open because I want to improve the warning. :)

**Comment by maennchen** [comment]
@josevalim I'd love to dig a little deeper into elixir itself. Could I provide a PR and you give me a pointer where to look?

**Comment by josevalim** [comment]
@maennchen it will be my pleasure! I will give you a very loose pointer: the fix is going to be on the Erlang part of the codebase (lib/elixir/src). I am going to add some details below, but I will leave them hidden, in case you don't  want too many spoilers.

Also, if you haven't yet, check out the README on how to compile the project and run tests. :)

<details>To be added.</details>

**Comment by josevalim** [comment]
Details added (and updated). ^

**Comment by josevalim** [comment]
<details>More details incoming.</details>

**Comment by maennchen** [comment]
@josevalim You are right and it can't be done only in `elixir_env` I think.

<details>
  <summary>Test</summary>

```elixir
  test "unused variable that could be pinned" do
    output =
      capture_err(fn ->
        # Note we use compile_string because eval_string does not emit unused vars warning
        Code.compile_string("""
        defmodule Sample do
          def test(arg) do
            compare_local = "hello"
            match?(compare_local, "hello")

            compare_nested = "hello"
            case "hello" do
              compare_nested -> true
              _other -> false
            end
          end
        end
        """)
      end)

    assert output =~
             "variable \"compare_local\" is unused (there is a variable with the same name in the context, did you mean to use the pin-operator?)"

    assert output =~
             "variable \"compare_nested\" is unused (there is a variable with the same name in the context, did you mean to use the pin-operator?)"
  after
    purge(Sample)
  end
```

</details>

<details>
  <summary>Output when Dumping `Unused` Variable</summary>

```
#{{arg,0}=>2,{compare_local,1}=>3}
#{{arg,0}=>2,{compare_local,1}=>3}
#{{arg,0}=>2,{compare_local,1}=>3,{compare_nested,3}=>6}
#{{arg,0}=>2,{compare_local,1}=>3,{compare_nested,3}=>6}
#{{arg,0}=>2,{compare_local,1}=>3,{compare_nested,3}=>6}
```

</details>

**Comment by josevalim** [comment]
Yeah, I think the approach in my second details may be the way to go!

**Comment by maennchen** [comment]
@josevalim Worked, thanks for your help :heart:

**Comment by josevalim** [comment]
Closing in favor of PR!
