### ISSUE TITLE
Formatter does not preserve Windows line endings

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#10504]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 23 [erts-11.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Operating system: all (relevant only on Windows)

### Current behavior

```
iex(2)> Code.format_string!("defmodule A   do\r\n:ok\r\nend")
["defmodule", " ", "A", " do", "\n  ", ":ok", "\n", "end"]
```
the same goes for `mix format`

Sorry if this has been raised before. I couldn't find any issues related to this nor any info in `mix format` nor `Code.format_string!` docs.

### Expected behavior

I don't know if CRLF should be preserved. If yes then it's a bug. If not then it should be a documented behaviour.

**Comment by ericmj** [comment]
I think CRLF is still the standard for Windows (please let me know if I am wrong) so the formatter should indeed preserve the line endings.

**Comment by josevalim** [comment]
Agreed. I think the simplest way is to do a pass on the data after formatting that converts "\n" to "\r\n" if you are on Windows. The main question I have is: should we effectively preserve the input or if we should always use "\r\n" on Windows. I am more inclined towards the latter. In any case, the behaviour should be disableable via an option.

**Comment by chulkilee** [comment]
I'm more inclined to stick with `\n`. Please note that a line may end with `\n` in a string, which should not use `\r\n` - so Windows editors has to deal with `\n` in such cases anyway. 

```elixir
"a
b" |> IO.inspect()
```
```sh
$ cat t.exs | unix2dos > t.dos.exs && elixir t.dos.exs && elixir t.exs
"a\r\nb"
"a\nb"
```

I'm more inclined to enforce `\n` like go fmt (see https://github.com/golang/go/issues/16355). "Recent" windows tools should handle unix format nicely anyway.

**Comment by ericmj** [comment]
> The main question I have is: should we effectively preserve the input or if we should always use "\r\n" on Windows. I am more inclined towards the latter.

We should preserve what is in the source file. If we always switch to "\r\n" and to "\n" on unix you can't really have developers using both systems on the same project.

We would also need `--check-formatted` to ignore what line ending is used.

**Comment by lukaszsamson** [comment]
> We should preserve what is in the source file. If we always switch to "\r\n" and to "\n" on unix you can't really have developers using both systems on the same project.

That leads to mixed line endings in my experience.
How about reading git settings? It's a good practise on Windows to set
```
git config --global core.autocrlf true
```

**Comment by josevalim** [comment]
What was your initial use case that made you report the issue, @lukaszsamson?

Given Go enforces \n, I am more inclined to keep things as is. And yes, most Windows tools nowadays handles it transparently.

**Comment by ericmj** [comment]
There are other tools to prevent mixed line endings. If you have this set `git config --global core.autocrlf true` there is no need for the formatter to also mess with the line endings, so reading this config seems unnecessary. I am also guessing that if you are setting `core.autocrlf` then you actually want the CRLF so the formatter converting to LF would be wrong.

**Comment by lukaszsamson** [comment]
> What was your initial use case that made you report the issue, @lukaszsamson?

I was validating if elixir-ls behaves correctly with regards to line endings.

> Given Go enforces \n, I am more inclined to keep things as is. And yes, most Windows tools nowadays handles it transparently.

As i wrote in the issue report, I'm OK with keeping it as it is. I just found it strange it's not documented.

**Comment by josevalim** [comment]
Ok, I think the simplest and least obstrusive change for now is to keep and document the behaviour, so that's what we will do. We can add an option to enforce one or the other in the future.

**Comment by chulkilee** [comment]
@lukaszsamson  Please note that git's `core.autocrlf` option *may* change the value of a string in elixir code (as I shown there), since git does not know the context (as [I shown in the above](https://github.com/elixir-lang/elixir/issues/10504#issuecomment-731729619))

https://github.community/t/git-config-core-autocrlf-should-default-to-false/16140

**Comment by lukaszsamson** [comment]
> Please note that git's core.autocrlf option may change the value of a string in elixir code (as I shown there), since git does not know the context (as I shown in the above)

I have to say this is a surprising behaviour. It's not particularly documented either. Moreover, it is not consistent with heredoc. In heredocs `\r\n` gets changed to `\n`

**Comment by josevalim** [comment]
@lukaszsamson it is nothing related to Elixir. Git will change all newlines to CRLF if configured to, including the ones inside strings. There is nothing Git or Elixir can do.

**Comment by chulkilee** [comment]
@josevalim  I found heredoc (`"""`) *always* change `\r\n` into `\n` while multi-line string with single quote (`"`) is preserving the line ending.

I guess it's related to https://github.com/elixir-lang/elixir/blob/v1.11.2/lib/elixir/src/elixir_tokenizer.erl#L995

```elixir
"a
b" |> IO.inspect(label: "single")

"""
a
b
""" |> IO.inspect(label: "triple")
```

```sh
cat t.exs | unix2dos > t.dos.exs && elixir t.dos.exs && elixir t.exs
single: "a\r\nb"
triple: "a\nb\n"
single: "a\nb"
triple: "a\nb\n"
```

You can see - triple (heredoc) is always using `\n` while single quote is preserving it as-is (which is correct, since it's binary actually!)

**Comment by josevalim** [comment]
Oh, I see. This is definitely an Elixir bug then, thanks! No need for a new issue, I plan to tackle all of this today or latest this week.
