### ISSUE TITLE
Custom assert message ignored when using '=' operator

### ISSUE THREAD

**Issue by azizk** [elixir-lang/elixir#10503]
### Environment

* Elixir & Erlang/OTP versions: Elixir 1.11.0 (compiled with Erlang/OTP 23)
* Operating system: Linux

### Current behavior
The assertion fails but doesn't display the provided message.
```elixir
assert 1 = 2, "1 is not 2"

# ** (MatchError) no match of right hand side value: 2
```
It's displayed if you use "==" for example.
```elixir
assert 1 == 2, "1 != 2"

# ** (ExUnit.AssertionError) 
#
# 1 != 2
```
Comparison with assert without message.
```elixir
assert 1 = 2

# ** (ExUnit.AssertionError)

# match (=) failed
# code:  assert 1 = 2
# left:  1
# right: 2
```
### Expected behavior
```elixir
assert 1 = 2, "1 is not 2"

# ** (ExUnit.AssertionError)

# 1 is not 2
# code:  assert 1 = 2
# left:  1
# right: 2
```

**Comment by vnbrs** [comment]
Shoudn't match assertions raise `ExUnit.AssertionError` instead of a regular `MatchError`?

**Comment by v0idpwn** [comment]
The same happens with refute/2.
It works this way because they're just functions, not macros as assert. I ain't sure if this is a bug, but if it is, it should be easy to fix making those functions macros.

**Comment by josevalim** [comment]
After checking the APIs, this behaviour is correct. `assert/1` is macro based and `assert/2` simply executes the first argument, without doing any macro manipulation. You can do `assert match?(...), "message"` in your case. I will add an example to the docs.

**Comment by azizk** [comment]
Okay, but why not do the same macro manipulation in `assert/2`? I was hoping to get the comparison between the left and right-hand side and the highlighting of keys if it's a map, but with `match?(...)` you won't see that...

**Comment by josevalim** [comment]
@azizk you will see that if `match?(...)`, you won't see that with `assert/2`. Once you pass your own message, then it means you are replacing the message ExUnit generates (which is the one with the diff).

**Comment by azizk** [comment]
@jose Yeah, I meant `match?` with `assert/2`. Now I see that you intend the message to be a complete replacement. In that sense it's working correctly. But maybe you'd like to reconsider because it would seem more consistent with `assert/1`, if `assert/2` also printed a detailed `AssertionError` where the custom message is used. Moreover there's no easy way to print the left and right-hand side expressions in your custom message and if there was it would be tedious and impractical to do so.

I just noticed some code in the module that looks like this case was planned, or maybe it was left in unintentionally:
```elixir
            _ ->
              left = unquote(Macro.escape(left))
              message =
                (message || "match (=) failed") <>
                  ExUnit.Assertions.__pins__(unquote(pins))
```

**Comment by azizk** [comment]
@josevalim Never mind the code I posted above. That was just an attempt I made some time ago. :)
