### ISSUE TITLE
Genreated function arguments should be 1-based, and not 0-based as they currently are

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10518]
In the documentation when we refer to the arguments we refer to their ordinal value (first, second, third), but when the arguments are not named, they are 0-based as in this example.

```
warning: undefined field "bar" in expression:

    # (for doctest at) lib/foo.ex:11
    arg1.bar

expected one of the following fields: 

where "arg1" was given the type map() in:

    # (for doctest at) lib/foo.ex:11
    {arg0, arg1} = {%Foo{bar: "baz"}, %{}}

Conflict found at
  (for doctest at) lib/foo.ex:11: FooTest."doctest Foo.is_valid?/2 (1)"/1
```

Here arg1 is not the first argument but the second one, which is really confusing.

~The same apply in ExDoc when arguments are not named, and a default name is given.~
This is not happening anymore either the current version of ExDoc or either Elixir itself. But there is another issue with unnamed arguments and I will create an issue later.

**Comment by josevalim** [comment]
@eksperimental I am not sure what you are talking about. Can you please provide the code that emits the warning? Or perhaps fill in the issues template accordingly? I am thinking the args vars are being generated and are not related to argument functions nor anything.

**Comment by eksperimental** [comment]
lib/foo.ex
```elixir
defmodule Foo do
  defstruct [:bar]

  @moduledoc """
  Documentation for `Foo`.
  """

  @doc """
  Returns if the argument is a valid Foo struct or not.

      iex> Foo.is_valid?(%Foo{bar: "baz"}, %{})
      false

      # iex> Foo.is_valid?(%Foo{})
      # false

      # iex> Foo.is_valid?(%Foo{bar: "baz"})
      # true

  """
  @spec is_valid?(any(), any()) :: boolean()
  defguard is_valid?(term1, term2 \\ nil)
           when is_struct(term1, __MODULE__) and is_map_key(term1, :bar) and not is_nil(term1.bar) and
                  is_struct(term2, __MODULE__) and is_map_key(term2, :bar) and
                  not is_nil(term2.bar)
end
```

foo_test.exs

```elixir
defmodule FooTest do
  use ExUnit.Case
  doctest Foo
end

```

**Comment by eksperimental** [comment]
> @eksperimental I am not sure what you are talking about. Can you please provide the code that emits the warning? Or perhaps fill in the issues template accordingly? I am thinking the args vars are being generated and are not related to argument functions nor anything.

The issue is with the positional number given to the generated arguments.

**Comment by ericmj** [comment]
The names are not positional, they only have a number to ensure they are unique.

**Comment by eksperimental** [comment]
> The names are not positional, they only have a number to ensure they are unique.

yes. my suggestion is that they should be 1-based, not 0-based. That's all

**Comment by eksperimental** [comment]
> The names are not positional, they only have a number to ensure they are unique.

oh. I see, Still they could be 1-based and not 0-based.

**Comment by josevalim** [comment]
I see it now. The code snippet was really important to understand what this was about. It should be an easy fix.

**Comment by eksperimental** [comment]
> I see it now. The code snippet was really important to understand what this was about. It should be an easy fix.

Awesome. Thank you. I tried looking in the compiler files for a bit, and got lost.

**Comment by eksperimental** [comment]
> The code snippet was really important to understand what this was about.

Sure. Sorry about that
