### ISSUE TITLE
Variables named "_" are named like that in the docs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10519]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.2 (compiled with Erlang/OTP 23)

```elixir
defmodule Foo do
  def unnamed_args(_, _), do: true
end
```

```elixir
iex(1)> h Foo.unnamed_args

                             def unnamed_args(_, _)                             

```

They should be named arg1 and arg2
```elixir
def unnamed_args(arg1, arg2)
```

This happens in IEx and ExDoc

**Comment by josevalim** [comment]
According to the tests, this was by design, as to signal the argument is not used. Give it a better name for the code, and you will be rewarded seeing it in the docs to. :)

**Comment by eksperimental** [comment]
> According to the tests, this was by design, as to signal the argument is not used. Give it a better name for the code, and you will be rewarded seeing it in the docs to. :)

I think if we want to signal it we should emit a warning. 
Using `def unnamed_args(_a, _b), do: true` will not signal anything, and still the arguments are not being used.
