### ISSUE TITLE
Mix fails to work with Rebar 3.14.2

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#10517]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
    ```
    Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

    Elixir 1.11.2 (compiled with Erlang/OTP 22)
    ```

* Operating system: macOS, but @NobbZ reported that it also happens on Linux

### Current behavior

When trying to compile Elixir LS with Rebar 3.14.2 (set via environment variable `MIX_REBAR3`) it fails to compile with message:

```
===> Compiling providers
===> Compiling src/providers.erl failed
src/providers.erl:31: can't find include file "providers.hrl"
src/providers.erl:285: undefined macro 'PRV_ERROR/1'
src/providers.erl:274: function process_dep/2 undefined
src/providers.erl:276: function process_dep/2 undefined
** (Mix) Could not compile dependency :providers, "/nix/store/vwpgznpbg6d2ksl6pqi89n5q1cac1d9a-rebar3-3.14.2/bin/rebar3 bare compile --paths /private/tmp/nix-build-elixir-ls-3acc1fdb2ef2c1167935f7b6e74300e039200ec5.drv-1/source/_build/shared/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile providers", update it with "mix deps.update providers" or clean it with "mix deps.clean providers"
```

### Expected behavior

It should compile without error.

**Comment by hauleth** [comment]
While I know, that Elixir do not guarantee the compatibility with later versions of the Rebar than the built-in one (which is 3.13.2 IIRC), but I think that it will need to be tackled earlier or later and I would prefer earlier, as it makes Nix integration much easier.

**Comment by josevalim** [comment]
I think the issue is with this env var:

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/deps.compile.ex#L204

Can you try commenting out that line, run `make compile`, and see if it addresses the problem? It may be that rebar3 is reading the include file from the output directory instead of the input one?

**Comment by hauleth** [comment]
@josevalim commenting that line out helped with building the Elixir LS.

**Comment by josevalim** [comment]
This works:

```
$ git clone git@github.com:tsloughter/providers.git
$ rebar3 bare compile --paths .
```

This doesn't:

```
$ git clone git@github.com:tsloughter/providers.git
$ REBAR_BARE_COMPILER_OUTPUT_DIR=oops rebar3 bare compile --paths .
===> Compiling src/providers.erl failed
src/providers.erl:31: can't find include file "providers.hrl"
src/providers.erl:285: undefined macro 'PRV_ERROR/1'

src/providers.erl:274: function process_dep/2 undefined
src/providers.erl:276: function process_dep/2 undefined
```

My understanding is that, by changing `REBAR_BARE_COMPILER_OUTPUT_DIR`, it can no longer read the include directory. As the `include` directory needs to be copied to the output directory anyway, I can easily fix this. I just want to make sure this behaviour is expected. /cc @tsloughter

**Comment by tsloughter** [comment]
Yup, the code path used is based on the output directory.

But the same should be done for `priv` as well I think.
