### ISSUE TITLE
iex: Can we make r/0 an alias to `recompile`?

### ISSUE THREAD

**Issue by mrjoelkemp** [elixir-lang/elixir#10514]
I was curious if you're open to having r/0 in iex do the same functionality as `recompile`. It's a minor thing, but from a dev experience perspective, it would be incredible to not have to type out `recompile` to update a running app in iex. Ideally, I could just type `r` alone and have the changed files recompiled. 

I'm open to working on a PR if it's an acceptable request.

**Comment by josevalim** [comment]
The issue is that r/1 already means something and it is not the same, so I would prefer to not mix those. If you prefer, you can start a discussion on the mailing list to collect more feedback.
