### ISSUE TITLE
Compiler does not detect duplicated clauses with guards

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10525]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): master

### Current behavior

The compiler does not detect duplicated clauses when guards are used and fails to warn that a previous clause will always match.

```elixir
defmodule Bar do
  def term(term), do: term
  def term(term), do: {:unreacheable, term}

  def atom_guard(term) when is_atom(term), do: term
  def atom_guard(term) when is_atom(term), do: {:unreacheable, term}

  def map_pattern_match(%{} = term), do: term
  def map_pattern_match(%{} = term), do: {:unreacheable, term}

  def map_guard(term) when is_map(term), do: term
  def map_guard(term) when is_map(term), do: {:unreacheable, term}
end
```

```console
$ mix compile
Compiling 1 file (.ex)
warning: this clause for term/1 cannot match because a previous clause at line 2 always matches
  lib/bar.ex:3

warning: this clause cannot match because a previous clause at line 8 always matches
  lib/bar.ex:9

```
### Expected behavior
The compiler should emit a warning about `atom_guard/1` and `map_guard/1` in the same fashion as it warns with the other functions.

**Comment by josevalim** [comment]
Yes, those messages come from the Erlang compiler and they are a nice-to-have, they don't change how the code works, and they are not guaranteed to be emitted.

**Comment by eksperimental** [comment]
> Yes, those messages come from the Erlang compiler and they are a nice-to-have, they don't change how the code works, and they are not guaranteed to be emitted.

Should I report this to OTP?

**Comment by josevalim** [comment]
No, because it is not the point of the compiler to find all of these cases. You would need a type system and Elixir nor Erlang have one. The warnings you see are found just by luck when optimizing code, the goal of the compiler is not to look for them.
