### ISSUE TITLE
Mix can't run tasks on Aarch64

### ISSUE THREAD

**Issue by tjm1518** [elixir-lang/elixir#10527]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 20, erts 9.2. Latest version of Elixir from apt (unsure of exact version, see #10526)
* Operating system: Ubuntu 18.04 LTS
* Architecture: Aarch64 (ARM v8)
* Nvidia Jetson Nano (Similar to Raspberry Pi)

### Current behavior

Running `mix new <name>` returns an error such as `** (Mix) Application name must start with a letter and have only lowercase letters, numbers and underscore, got: "<name>". The application name is inferred from the path, if you'd like to explicitly name the application then use the "--app APP" option.` regardless of whether the name is actually valid or not.

Attempting to run a mix task on a known working project gives `** (Mix) Invalid Elixir version requirement ~> 1.11 in mix.exs file` which I suspect may also be linked to #10526. Changing the version to other previous versions does not fix this.

### Expected behavior

Running `mix new <name>` where name is valid should create a new mix project with the provided name.

Running a known working mix task with Elixir 1.11 or any previous version should execute that task in the provided version of Elixir.

**Comment by josevalim** [comment]
Same reason as #10526 (running an early Elixir version in an old Erlang version).
