### ISSUE TITLE
Argument name in function signature is lost when multiple clause undescore-prefixed variables is used

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10524]
```elixir
defmodule Foo do
  def fun1_a(_first, last) when is_atom(last), do: true
  # signature: fun1_a(first, last)

  def fun1_b(_, last) when is_atom(last), do: true
  def fun1_b(_first, last) when is_binary(last), do: false
  # signature: fun1_b(arg1, last)
  # expected signature: fun1_b(first, last)

  def fun1_c(_first, last) when is_atom(last), do: false
  def fun1_c(_, last) when is_binary(last), do: true
  # signature: fun1_c(arg1, last)
  # expected signature: fun1_c(first, last)

  def fun1_d(_first, last) when is_atom(last), do: false
  def fun1_d(_one, last) when is_binary(last), do: true
  # signature: fun1_c(arg1, last)
  # expected signature: fun1_c(first, last)
end
```

in IEx, run
```elixir
h(Foo.fun1_a())
h(Foo.fun1_b())
h(Foo.fun1_c())
h(Foo.fun1_d())
```

I would expect the if the first clause defined a name, stick to it. that would avoid to create a body-less clause.
also if in the the first clause the argument is defined as `_`, but in a following clause is is defined with `_a_name`, then `a_name` used in the signature.

**Comment by josevalim** [comment]
We have gone back and forth on this with time. The issue is that people would write this:

    def fun1_b(_string, last) when is_atom(last), do: true
    def fun1_b(_, last) when is_binary(last), do: false

And we would preserve it as a `string` but the truth is that it could be anything! After all, calling it with `fun1_b(123, "foo")` will work just fine. That's why we are conservative and, in face of conflicting names, we always fallback to arg1. If you want to make sure a name is going to stick, then use a function head.

**Comment by eksperimental** [comment]
> We have gone back and forth on this with time. The issue is that people would write this:
> 
> ```
> def fun1_b(_string, last) when is_atom(last), do: true
> def fun1_b(_, last) when is_binary(last), do: false
> ```
> 
> And we would preserve it as a `string` but the truth is that it could be anything! After all, calling it with `fun1_b(123, "foo")` will work just fine. That's why we are conservative and, in face of conflicting names, we always fallback to arg1. If you want to make sure a name is going to stick, then use a function head.

I have been playing around this issue a lot and it saw what you explained here with unnamed arguments, but I think this one is not the case. If someone named `_string`, yes, it could be anything, but it was named `_string` for a reason.
take this example, only one clause:
> def fun1_b(_string, last) when is_atom(last), do: true

the signature will be `string` and the variable could still be anything.
IMO if an argument is named with an underscore --as of now-- it should only be replaced with a named variable without underscore (actually this is debatable) but it should never be lost.
