### ISSUE TITLE
Elixir -v (and --version) crash on Aarch64

### ISSUE THREAD

**Issue by tjm1518** [elixir-lang/elixir#10526]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 20, erts 9.2. Latest version of Elixir from apt.
* Operating system: Ubuntu 18.04 LTS
* Architecture: Aarch64 (ARM v8)
* Nvidia Jetson Nano (Similar to Raspberry Pi)

### Current behavior

Running `elixir -v` or `elixir --version` results in a crash dump. Dump file is attached & console output below.

```bash
tm@tm-jetson:~/gpio$ elixir -v
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

{"init terminating in do_boot",{{badmatch,error},[{'Elixir.System',build,0,[{file,"lib/system.ex"},{line,172}]},{'Elixir.System',build_info,0,[{file,"lib/system.ex"},{line,164}]},{'Elixir.Kernel.CLI',parse_shared,2,[{file,"lib/kernel/cli.ex"},{line,153}]},{'Elixir.Kernel.CLI','shared_option?',3,[{file,"lib/kernel/cli.ex"},{line,113}]},{'Elixir.Kernel.CLI',main,1,[{file,"lib/kernel/cli.ex"},{line,14}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{badmatch,error},[{Elixir.System,build,0,[{_},{_}]},{Elixir.System,build_info,0,[{_},{_}]},{Elixir.Kernel.CLI,parse_shared,2,[{_},{_}]},{Elixir.Kernel.CLI,shared_option?,

Crash dump is being written to: erl_crash.dump...done
```

[erl_crash.dump.log](https://github.com/elixir-lang/elixir/files/5631443/erl_crash.dump.log)

### Expected behavior

The currently installed version of Elixir should be printed.

**Comment by josevalim** [comment]
@tjm1518 which version does apt say you are supposed to have?

**Comment by tjm1518** [comment]
@josevalim The installed version is 1.3.3-2 apparently (I guess there aren't newer versions for ARM as I have 1.11.2-1 on my pc?)

**Comment by josevalim** [comment]
Elixir v1.3.3 definitely won't run on Erlang/OTP 20, please check this table: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

The issues you are running into is because Erlang/OTP 20 updated the regex engine, so you have an Elixir version with regexes compiled for earlier versions, and now all regexes fail. So we can't parse the version, we can't validate the mix task command, etc. You can use something like asdf to compile Elixir for you.

**Comment by josevalim** [comment]
Also worth saying that we later fixed Elixir to be more resilient to Erlang upgrading the regex engine but, iirc, OTP 20 was the first time it happened.

**Comment by tjm1518** [comment]
Ok thank you, I'll try compiling from scratch.

Would it be possible to change the version of Elixir available via apt for ARM architectures given it's not compatible with the version of Erlang it installs as a dependency? I'm not really an expert on package managers so I'm not sure how this is done/how easy it is to fix.

**Comment by josevalim** [comment]
I am not sure how to do it either, we don't maintain the apt packages. Elixir versions should be mostly independent of architecture though (as long as they have the same endianness).
