### ISSUE TITLE
EEx compiler should provide a warning if a block is used without <%=

### ISSUE THREAD

**Issue by halostatue** [elixir-lang/elixir#10536]
As I described on [elixir-lang-core](https://groups.google.com/g/elixir-lang-core/c/FKA9PancUm0), I had a bug that happened because my eyes slipped over the following bug:

```eex
<% if @password do %>
  Temporary password: <%= @password %>
<% else %>
  You will need to log in with your password.
<% end %>
```

The error is easily corrected:

```eex
<%= if @password do %>
  Temporary password: <%= @password %>
<% else %>
  You will need to log in with your password.
<% end %>
```

It seems to me that the EEx compiler _should_ be able to provide a compile warning if a block is used when `<% … %>` is used instead of `<%= … %>`.

This would introduce one possible incompatibility with the current compiler:

```eex
<% somevar = for item <- list do %>
  <% if(item % 2 == 0, do: item * 2, else: item * 3) %>
<% end %>
```

This can be resolved by combining these into a single tag:

```eex
<% somevar = form item <- list do
  if(item % 2 == 0, do: item * 2, else: item * 3)
end %>
```

As requested, I’ve opened an issue.

**Comment by v0idpwn** [comment]
I also experienced some bugs with this behaviour and it became an attention point for me, while I believe it shouldn't. 
It is also not really clear in the docs whether you should use `<%` or <%=` and this gets even more tricky for newcomers.
