### ISSUE TITLE
** (UndefinedFunctionError) 

### ISSUE THREAD

**Issue by exit9** [elixir-lang/elixir#10535]
### Environment
Erlang package: esl-erlang 1:23.1-1
$ elixir -v
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.11.2 (compiled with Erlang/OTP 23)

Ubuntu 20.04 
VSCode + ElixirLS

### Current behavior

I start refactoring, deleted some modules and get: 
```
Please report this bug: https://github.com/elixir-lang/elixir/issues

** (UndefinedFunctionError) function App.Some.SomeEcto.__struct__/0 is undefined (module App.Some.SomeEcto is not available)
        App.Some.SomeEcto.__struct__()
        (elixir 1.11.2) lib/module/types/of.ex:101: Module.Types.Of.struct/3
        (elixir 1.11.2) lib/module/types/pattern.ex:177: Module.Types.Pattern.of_pattern/3
        (elixir 1.11.2) lib/module/types/pattern.ex:161: Module.Types.Pattern.of_pattern/3
        (elixir 1.11.2) lib/module/types/helpers.ex:93: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.11.2) lib/module/types/pattern.ex:12: Module.Types.Pattern.of_head/4
        (elixir 1.11.2) lib/module/types.ex:62: Module.Types.warnings_from_clause/6
        (elixir 1.11.2) lib/module/types.ex:22: anonymous fn/8 in Module.Types.warnings/5
        (elixir 1.11.2) lib/enum.ex:3421: Enum.flat_map_list/2
        (elixir 1.11.2) lib/enum.ex:3422: Enum.flat_map_list/2
        (elixir 1.11.2) lib/module/parallel_checker.ex:104: Module.ParallelChecker.check_module/2
        (elixir 1.11.2) lib/module/parallel_checker.ex:300: anonymous fn/5 in Module.ParallelChecker.spawn_checkers/1
```

The warning is only displayed in the mix.exs file. Some warnings displayed in the terminal correctly.

### Expected behavior

I can remove some unnecessary module, go to all definitions specified by the compiler or dialyzer, and change the functions.

### Workaround

Fix other ecto scemas.

**Comment by josevalim** [comment]
Interesting. This is indeed a bug. The struct was removed but the compiler did not fail. Can you consistently reproduce this? If so, can you try to isolate it?

**Comment by exit9** [comment]
```
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (Module.Types.Error) found error while checking types for App.Some.SomeStructView.get_stream_config/2

def(get_stream_config(%App.SomeStruct{} = struct, server_data)) do
  case(App.Module.find_data(server_data.server_config, struct)) do
    {:ok, v} ->
      v
    _ ->
      nil
  end
end
```
I think this can help

**Comment by lukaszsamson** [comment]
@exit9  Do you get this error in terminal or only in VSCode as elixirLS diagnostic?

**Comment by exit9** [comment]
Both with same error but with different traces. I that error happens because of deleting shema module and connector module when they are used in many places, so maybe some race conditions. Also was another error with erlang.get_ets{parent)

**Comment by exit9** [comment]
Elixir can't check types in parallel compiler when scemas have links on deleted other with connector schema (join_trough) or just can't get result on such shemas.

**Comment by josevalim** [comment]
@exit9 Ecto doesn't check those indeed to avoid cyclic dependencies but that is not meant to be the root cause here, exactly because Ecto doesn't check structs.

Do you, by any chance, have a small repo that reproduces it? Something that I can run `mix compile` or another command, that will show the same error?

**Comment by exit9** [comment]
ok. I try to do it later.

**Comment by josevalim** [comment]
Ping. :)

**Comment by josevalim** [comment]
Got a reproduction case in #10584, thank you.

**Comment by exit9** [comment]
Great. Sorry about reproduction project, I got sick for two weeks. Now I'm fine and happy about resolving problem)

**Comment by josevalim** [comment]
No problem, glad to hear you are well!
