### ISSUE TITLE
Curious parsing(/macro expansion?) error when passing a quoted snippet to a module attribute

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#10544]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.3 / OTP 23
* Operating system: Linux Manjaro 

### Situation

Consider the following module:

```elixir
defmodule Foo do
  @common_snippet quote do
    [1,2,3,4]
  end

  # ... hypothetically some other code here
end
```

### Current behavior

```
$ iex -S mix
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Compiling 1 file (.ex)

== Compilation error in file lib/small_test.ex ==
** (ArgumentError) expected 0 or 1 argument for @common_snippet, got: 2
    (elixir 1.10.3) lib/kernel.ex:3044: Kernel.do_at/5
    (elixir 1.10.3) expanding macro: Kernel.@/1
    lib/small_test.ex:38: Foo (module)
```

### Expected behavior

I would expect the module should compile.

However, it seems that there is some parsing precedence and/or macro-expansion issue happening here.

Maybe there is a clear underlying reason why the particular structure of `@name quote do ... end` cannot be supported.
If that is the case, then we could at least improve the current error message.

**Comment by michalmuskala** [comment]
I think the problem is that `do ... end` block is parsed as part of the `@` operator, and not for the `quote` construct, since blocks always bind to the outermost construct on the line.

```elixir
@common_snippet (quote do
    [1,2,3,4]
end)
```
and
```elixir
@common_snippet quote(do: [1,2,3,4])
```
should work correctly

**Comment by Qqwy** [comment]
> [...] since blocks always bind to the outermost construct on the line.

I see! This information is new to me. It might be nice to add it to Elixir's documentation somewhere, although I do not know what page/module would make the most sense :thinking: .

And besides that: can(/should?) we add a better error message for this particular case?

_I'll happily contribute a PR for one or both of these, of course :wink: ._

**Comment by ericmj** [comment]
A PR that adds the do/end binding rules to the syntax reference would be very appreciated.

I haven't seen `UNARY_OP ... do ... end` used in the wild so I think we should be able to deprecate it and add a warning for it.

**Comment by josevalim** [comment]
I would rather not deprecate it.

```elixir
-if something do
  x
else
  y
end
``` 

is totally fine. My suggestion is to check if a do/end block was given to `@` and raise a more specific hint.

**Comment by ericmj** [comment]
@josevalim In your example the `do` binds to `if` so we can still warn when `do` would bind to the unary operator.

This also highlights a subtlety with the binding rules. `do` binds to the first construct on the same line except when a function precedes it and the other first construct is an operator?

**Comment by josevalim** [comment]
The do is not binding to @ in the original post either. The do is binding to the attribute name which trips the @ macro off. The behavior is the same as any other unwary operatorz

**Comment by michalmuskala** [comment]
Ah, yeah, assuming it binds to `@` was my bad

**Comment by Qqwy** [comment]
Thank you very much, team! :heart:
