### ISSUE TITLE
Code.eval_quoted/3 does not use provided aliases

### ISSUE THREAD

**Issue by Zurga** [elixir-lang/elixir#10553]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.11.0
* Operating system: Manjaro

### Current behavior
When `:aliases` are given to `Code.eval_quoted/3` the aliases are not used in the quoted ast. See the following example:
```
code = quote do NewString.to_atom("hello") end
Code.eval_quoted(code, [], aliases: [{NewString, String}])
```
gives me:
```
** (UndefinedFunctionError) function NewString.to_atom/1 is undefined (module NewString is not available)
    NewString.to_atom("hello")
    (stdlib 3.13.2) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.11.0) lib/code.ex:706: Code.eval_quoted/3
```
### Expected behavior
I would expect this to work the same way as `Code.eval_string/3`. Which has no issue when running this example:
`Code.eval_string("NewString.to_atom(\"hello\")", [], aliases: [{NewString, String}])`

### Current workaround
For now, I can work around this issue by running `Macro.to_string/1` on the quoted code but I don't know how this affects the performance of my code.

Thanks in advance!

**Comment by josevalim** [comment]
The answer is in the quoted expression:

```
iex(1)> code = quote do NewString.to_atom("hello") end
{{:., [], [{:__aliases__, [alias: false], [:NewString]}, :to_atom]}, [], ["hello"]}
```

Elixir adds an `alias` false because, when passing quoted expressions around, we want to preserve the context of the writer! If you want something to have the context of where it is resolved, you need to explicitly mark it as so:

```
iex(4)> code = quote do alias!(NewString).to_atom("hello") end    
{{:., [],
  [
    {:alias!, [context: Elixir, import: Kernel],
     [{:__aliases__, [alias: false], [:NewString]}]},
    :to_atom
  ]}, [], ["hello"]}
iex(5)> Code.eval_quoted(code, [], aliases: [{NewString, String}])
{:hello, []}
```

There is a section on the `quote` docs about hygiene that explains this in detail (and why it matters).

Thanks for the report!
