### ISSUE TITLE
Top-level reference to other module causes compile-time dependency

### ISSUE THREAD

**Issue by randycoulman** [elixir-lang/elixir#10565]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 21)
```

* Operating system: Mac OS/X Mojave

### Current behavior

I'm not sure if this is a bug or if there's a good reason for this behavior.  I discovered it while trying to get to the bottom of https://github.com/bamorim/typed_ecto_schema/issues/6.

If a module contains a top-level (i.e., outside of any function definition or macro body) reference to another module, Elixir adds a compile-time dependency on that module.

I have two files, `a.ex` and `b.ex`:

```elixir
# a.ex
defmodule A do
end

#b.ex
defmodule B do
  IO.inspect(A)
end
```

If I run `mix xref graph --label compile`, I get the following output:

```
lib/b.ex
└── lib/a.ex (compile)
```

If I change `b.ex` to be:

```elixir
defmodule B do
  IO.inspect(NotAModule)
end
```

The dependency goes away as it should.

Is there a reason that `A` can't be considered "just an atom" in this context like `NotAModule` seems to be?

### Expected behavior

I expect code like this to not generate a compile-time dependency on another file, but there might be a good reason for it that I'm not aware of.

Thanks!

**Comment by josevalim** [comment]
The issue is that you may be passing `A` to a module that calls `A` and, therefore, if we don't track it, we will have bugs because we won't recompile B. So any reference to anything that looks like module needs to be treated as a compile-time dependency.
