### ISSUE TITLE
Its bug or a feature?

### ISSUE THREAD

**Issue by ijunaid8989** [elixir-lang/elixir#10575]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.11.1 & 23.0
* Operating system: Ubuntu 18.04

### Current behavior

![image](https://user-images.githubusercontent.com/13561999/102044417-996a5b00-3df8-11eb-919c-3aecbb5627cb.png)

### Expected behavior

Shouldn't it bother by the spaces? and throw an error?

**Comment by josevalim** [comment]
Feature. Most languages, including Elixir, allows spaces between operators (which dot is one of).
