### ISSUE TITLE
Compiler doesn't catch undefined function calls in `with` clauses

### ISSUE THREAD

**Issue by kyleVsteger** [elixir-lang/elixir#10578]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]`
* Operating system: `MacOS 10.15.7 (19H2)`

### Current behavior
- Repo to reproduce: https://github.com/kyleVsteger/ex_with_bug
- Define an empty module `Foo` 
- Define another module `Bar` and a function `test` 
- Make a call to `Foo.func()` within a `with` clause
- Run `mix compile` —  No warning is produced
- Add a call to `Foo.func()` outside of the `with` clause
- Run `mix compile` —  a warning is produced 

### Expected behavior
- The compiler should complain that we're trying to call `Foo.func` in the `with` clause

**Comment by josevalim** [comment]
Thank you. This has been recently fixed on master and v1.11 branches, we will have a new release soon!
