### ISSUE TITLE
Logger level from `config.exs` is not respected in some cases

### ISSUE THREAD

**Issue by epsylonix** [elixir-lang/elixir#10589]
### Environment

Elixir 1.11.2
Erlang/OTP 23.2

### Current behavior
```
mix new logtest
```

```
# config/config.exs

import Config

config :logger,
  backends: [:console],
  level: :info

config :logger, :console,
  level: :info,
  metadata: :all
```

```
# lib/mix/tasks

defmodule Mix.Tasks.Logtest do
  use Mix.Task
  require Logger

  def run(_) do
    IO.inspect(Application.get_all_env(:logger))

    Logger.debug("!!!")

    IO.inspect(:logger.get_config())
  end
end
```

```
mix logtest

[
  utc_log: false,
  translators: [{Logger.Translator, :translate}],
  backends: [:console],
  discard_threshold_for_error_logger: 500,
  handle_sasl_reports: false,
  truncate: 8096,
  discard_threshold: 500,
  compile_time_application: nil,
  sync_threshold: 20,
  discard_threshold_periodic_check: 30000,
  console: [level: :info],
  handle_otp_reports: true,
  start_options: [],
  level: :info,
  translator_inspect_opts: [],
  compile_time_purge_matching: []
]

21:01:40.550 [debug] !!!
%{
  handlers: [
    %{
      config: %{
        sasl: false,
        thresholds: {20, 500},
        translators: [{Logger.Translator, :translate}],
        truncate: 8096,
        utc_log: false
      },
      filter_default: :log,
      filters: [],
      formatter: {:logger_formatter, %{}},
      id: Logger,
      level: :all,
      module: Logger.Handler
    }
  ],
  module_levels: [],
  primary: %{
    filter_default: :log,
    filters: [process_disabled: {&Logger.Filter.process_disabled/2, []}],
    level: :debug
  },
  proxy: %{
    burst_limit_enable: false,
    burst_limit_max_count: 500,
    burst_limit_window_time: 1000,
    drop_mode_qlen: 1000,
    flush_qlen: 5000,
    overload_kill_enable: false,
    overload_kill_mem_size: 3000000,
    overload_kill_qlen: 20000,
    overload_kill_restart_after: 5000,
    sync_mode_qlen: 500
  }
}
```
### Expected behavior

Since the Logger level is set to `:info`, debug messages like `21:01:40.550 [debug] !!!` should not be sent to the output.

Another possible issue is that the `Logger` handler level is set to `level: :all`. If I understand correctly, when I use Mix with an Erlang app and log using macros (like `?LOG_INFO(...)`), all messages will be sent to the handler even if the log level permits filtering them in the caller process. Shouldn't the Logger handler level be set to `:info`?

**Comment by epsylonix** [comment]
@hauleth, I've created this issue as you suggested

**Comment by josevalim** [comment]
This is working as expected. When Mix runs, Logger is already configured and running. Therefore, any configuration that you do in Logger is only going to have an affect once you reset the logger app, which is done by Mix only when you start your application.

For example, some applications may not use a logger at all, which means we won't even start it. So as soon as you start the app, you should see your configuration propagate. Thanks!

**Comment by fertapric** [comment]
Here are some links that are related to this issue:
https://github.com/elixir-lang/elixir/commit/78551c11c9c97bb608e4097d2e0c36458b11f535
https://github.com/elixir-lang/elixir/issues/9675

The example demonstrates that `mix deps.get` fails because the Logger, that was restarted before executing the Mix tasks, is trying to use a module that is defined in one of the dependencies that would be fetched by executing that exact `mix deps.get`.

**Comment by epsylonix** [comment]
thanks for a fast reply! Could you please clarify a couple more things:

1. When run using `iex -S mix` the logger level works as expected but the `Logger` handler level is still `:debug`, could you please address this specifically

> when I use Mix with an Erlang app and log using macros (like ?LOG_INFO(...)), all messages will be sent to the handler even if the log level permits filtering them in the caller process

```
iex -S mix
Erlang/OTP 21 [erts-10.3.5.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> require Logger
Logger
iex(2)> Logger.debug("!!!")
:ok
iex(3)> :logger.get_config()
%{
  handlers: [
    %{
      filter_default: :log,
      filters: [],
      formatter: {:logger_formatter, %{}},
      id: Logger,
      level: :debug,
      module: Logger.ErlangHandler,
      sasl_reports?: false
    }
  ],
  module_levels: [],
  primary: %{filter_default: :log, filters: [], level: :debug},
  proxy: %{
    burst_limit_enable: false,
    burst_limit_max_count: 500,
    burst_limit_window_time: 1000,
    drop_mode_qlen: 1000,
    flush_qlen: 5000,
    overload_kill_enable: false,
    overload_kill_mem_size: 3000000,
    overload_kill_qlen: 20000,
    overload_kill_restart_after: 5000,
    sync_mode_qlen: 500
  }
}
```

2. Do I understand correctly that Logger configuration from mix config will not work in Mix tasks and this is an expected behavior? We have a custom mix task that runs eunit tests without starting the app, is it not possible to configure logger through mix config for such task (should Logger be configured manually in the task itself)?

**Comment by josevalim** [comment]
For the eunit task, you would need to stop and start the logger application
manually for it to kick-in.
-- 


*José Valimhttps://dashbit.co/ <https://dashbit.co/>*

**Comment by hauleth** [comment]
@josevalim I have encountered something similar when doing `MIX_ENV=test mix ecto.migrate` and I am trying to find the source of the bug, as earlier it was printing nothing (as there is `config :logger, level: :warn`) and now it prints all messages from the migration. IIRC it shouldn't happen and the old behaviour (where the message weren't logged) should be kept as is.

**Comment by josevalim** [comment]
Then it is an Ecto behaviour because it is up to Ecto to choose to restart Logger or not. I think we started restarting the Logger and then we reverted to no longer do it as we ran into issues.

**Comment by jeremyjh** [comment]
@josevalim Is this a documented and intended change? We did not see this behaviour (mentioned by @hauleth) in 1.9 branch. 1.10 had this in its CHANGELOG: "[Mix.Task] Ensure project's Logger config is used when running Mix tasks".

This has caused problems for us due to e.g. CI logs overflowing and no longer being displayed in the browser.

**Comment by josevalim** [comment]
The CHANGELOG entry would be incorrect then. We changed this during dev/RC but then reverted it on the same cycle. So the behavior never changed in a final release but likely creeped into the CHANGELOG.
