### ISSUE TITLE
Strange Enum.take behavior

### ISSUE THREAD

**Issue by cgimenes** [elixir-lang/elixir#10592]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.11.0 (compiled with Erlang/OTP 23)

* Operating system: 

OS: Manjaro Linux x86_64
Kernel: 5.8.18-1-MANJARO

### Current behavior

```elixir
iex(1)> Stream.iterate(31, &(&1 + 1)) |> Enum.take(5)
[31, 32, 33, 34, 35]
iex(2)> Stream.iterate(32, &(&1 + 1)) |> Enum.take(5) 
' !"#$'
iex(3)> Stream.iterate(31, &(&1 + 1)) |> Enum.at(0)  
31
iex(4)> Stream.iterate(32, &(&1 + 1)) |> Enum.at(0)
32
```

### Expected behavior

```elixir
iex(1)> Stream.iterate(31, &(&1 + 1)) |> Enum.take(5)
[31, 32, 33, 34, 35]
iex(2)> Stream.iterate(32, &(&1 + 1)) |> Enum.take(5) 
[32, 33, 34, 35, 36]
```

**Comment by chulkilee** [comment]
That's just a different representation of a list - as a charlist.

```elixir
' !"#$' == [32, 33, 34, 35, 36]
true
```

See https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#charlists for details :)

**Comment by cgimenes** [comment]
Thanks!
