### ISSUE TITLE
Bug or a feature?

### ISSUE THREAD

**Issue by ijunaid8989** [elixir-lang/elixir#10598]
* Elixir & Erlang/OTP versions (elixir --version): 1.11.1, 23.0
* Operating system: 

### Current behavior

I have this module

```
defmodule Recording.Worker do
  use GenServer
  require Logger
```
and I am staring it as 

```
defmodule Recording.Supervisor do
  use DynamicSupervisor

  def start_link(opts) do
    DynamicSupervisor.start_link(__MODULE__, opts, name: __MODULE__)
  end

  def start_child(opts),
    do: DynamicSupervisor.start_child(__MODULE__, {Recordingg.Worker, opts})

  @impl DynamicSupervisor
  def init(opts),
    do: DynamicSupervisor.init(strategy: :one_for_one, extra_arguments: [opts])
end
```

I mistakenly added the other G in Recording(g) and It didn't throw any error 

### Expected behavior

It should give some error that the module is not available? 

But It's working all fine also I can see Recording.Worker running successfully.

**Comment by josevalim** [comment]
Modules in Elixir are late bound (for example, they can be loaded at any time), so this is expected. We would warn only if a literal call was happening on the snippet you shared.

**Comment by ijunaid8989** [comment]
I didn't see any warning but why didn't it give any error? like not even this, that module is not available?

**Comment by Eiji7** [comment]
@ijunaid8989 Simply you can:
1. Have your code like now
2. Dynamically load module (e.g. eval quoted expression or string or dynamically load file)
3. Call `Recording.Supervisor.start_child/1`

In such example scenario you would have no error or warning as it's dynamically generated code use case.

However such code:
```elixir
defmodule Example do
  def sample, do: :ok
end
Exampleeee.sample()
```
forces lookup for `Exampleeee` as its call happens at compilation time:
```elixir
== Compilation error in file lib/example.ex ==
** (UndefinedFunctionError) function Exampleeee.sample/0 is undefined (module Exampleeee is not available)
    Exampleeee.sample()
    (elixir 1.11.2) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

When call happens at runtime we have a warning instead, for example:
```elixir
defmodule Example do
  def sample, do: :ok

  def test, do: Exampleeee.sample()
end
```
gives:
```elixir
warning: Exampleeee.sample/0 is undefined (module Exampleeee is not available or is yet to be defined)
  lib/example.ex:3: Example.test/0
```

Why module without call does not gives any error or warning? Consider another example:
```elixir
defmodule Example do
  def sample, do: :ok

  def test do
    module = Exampleeee
    module.sample()
  end
end
```
How compiler would know which module was called? In theory somebody may even fetch module name from external resource (like by using some weird API). There is no way to guess if `A` atom in code (it does not even need to be a module) is actually module and is loaded at runtime.

```elixir
IO.inspect ImNotAModule
# ImNotAModule
IO.inspect :ImNotAModule
# :ImNotAModule

# What's difference? It's just a syntax sugar!
IO.inspect Atom.to_string(ImNotAModule)
# "Elixir.ImNotAModule"
IO.inspect Atom.to_string(:ImNotAModule)
# "ImNotAModule"
```

`atom` is just `atom` and without explicit call we don't know what do you want to do with it or how and when you load it at runtime. When call is at runtime we are giving only warning as you can load such module before it's called.

There are many better and worse use cases/solutions which uses this and therefore we can't just give an error. We are giving warning for a call at runtime as "by default" we expect that `x` module should be available, but we don't require that.

**Comment by ijunaid8989** [comment]
@Eiji7 Thank you for this explanation.
