### ISSUE TITLE
Compiler throw error when get map key in form of m.B

### ISSUE THREAD

**Issue by wingyplus** [elixir-lang/elixir#10594]
**NOTE:** feel free to close it if it's design by intent. :)

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.11.1
* Operating system: macOS Catalina

### Current behavior

I create a map that key begin with capital letter like this:

```
my_map = %{
  Body: "value"
}
```

If I try to get key `Body` with `my_map.Body`, compiler will raise an error:

```
** (CompileError) iex:6: invalid alias: "hello.Body". If you wanted to define an alias, an alias must expand to an atom at compile time but it did not, you may use Module.concat/2 to build it at runtime. If instead you wanted to invoke a function or access a field, wrap the function or field name in double quotes
```

### Expected behavior

I expected to receive a value from key `Body`.

**Comment by josevalim** [comment]
It is intentional, please do as the error message suggests: `map."Body"`. Thanks :)

**Comment by wingyplus** [comment]
@josevalim I'm just interesting in this case. Why compiler need to be wrap by `""`?

**Comment by josevalim** [comment]
Because it is ambiguous if `a.B` is meant to be the same as `Alias.B` or `map."B"`.

**Comment by wingyplus** [comment]
I got it. Thanks
