### ISSUE TITLE
Mix.Utils.extract_stale/2 marks all source files as stale if the manifest doesn't exist

### ISSUE THREAD

**Issue by baseballlover723** [elixir-lang/elixir#10590]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
Elixir 1.12.0-dev (86e2384) (compiled with Erlang/OTP 23)
```
(Though it also happens on elixir 1.11.x)

* Operating system: MacOs Catalina (10.15.7)

### Current behavior

In an umbrella project, if there is an app with no source code, then 
```
    manifests = Mix.Tasks.Compile.Elixir.manifests()
    configs = Mix.Project.config_files()
    stale = Mix.Utils.extract_stale(configs, manifests)
```
marks all of config files as stale. (this snippet is taken from phoenix: https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/code_reloader/server.ex#L210-L230)

This prevents phoenix's code reloading from working, since the manifest file (`test_empty_app_umbrella/_build/dev/lib/common_config/.mix/compile.elixir`) doesn't exist, which causes its last updated to be the unix epoch, and so thus any source files are marked as being stale. See https://github.com/baseballlover723/test_empty_app for a reproducible test project.

### Expected behavior

Source files (from the umbrella) are not marked as stale if a child app has no source files.

### Notes
I would consider this to be a bug in mix and not in phoenix, since `Mix.Tasks.Compile.Elixir.manifests()` returns a manifest file that may or may not exist. In my opinion, either `Mix.Tasks.Compile.Elixir.manifests()` should check and make sure that the manifest file exists, or manifest files should just always be generated, even if there isn't any source code.

**Comment by josevalim** [comment]
Closing in favor of PR. Thanks.
