### ISSUE TITLE
`@impl` is skipping the warnings when defdelegate is used

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10593]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir master, Erlang/OTP 23
* Operating system: Linux

### Current behavior
```elixir
defprotocol ImplDefdelegate do
  @moduledoc """
  Documentation for `ImplDefdelegate`.
  """
  def foo(term)

  def bar(term)
end

defimpl ImplDefdelegate, for: List do
  @impl true
  def foo(_) do
    :list
  end

  defdelegate bar(list), to: __MODULE__, as: :baz

  def baz(_) do
    :list
  end
end
```

```
$ mix test
Compiling 2 files (.ex)
Generated impl_defdelegate app


Finished in 0.02 seconds
0 failures

```
no warnings,

### Expected behavior

A warning ("module attribute @impl was not set for function bar/1 callback") should be given

**Comment by josevalim** [comment]
We skip warnings for generated code. We may need to add some special annotations here to make it clear the code is not quite generated.

**Comment by eksperimental** [comment]
I can give it a try

**Comment by josevalim** [comment]
Hi @eksperimental, are you still planning to investigate this one? Otherwise I will add labels so someone else can pick it up. :)

**Comment by eksperimental** [comment]
> Hi @eksperimental, are you still planning to investigate this one? Otherwise I will add labels so someone else can pick it up. :)

I totally forgot about this one. I will try to find some time for this, otherwise I will report back at the end of the weekend.

**Comment by eksperimental** [comment]
I have found the bug.
How do we add the annotation?

**Comment by josevalim** [comment]
@eksperimental I am not sure what you are asking. :)

**Comment by eksperimental** [comment]
> @eksperimental I am not sure what you are asking. :)

How can we annotate defdelegate quoted code?
I tried to modify the meta information and but i did not work.
If this does not make sense I will upload a PR so we can talk over real code
