### ISSUE TITLE
Inspect not work for 1.11.2, worked fine for 1.9.4

### ISSUE THREAD

**Issue by cisiqo** [elixir-lang/elixir#10614]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  1.11.2
* Operating system: macOS 10.15.7

### Current behavior

```
defmodule Test do

  require Record
  Record.defrecordp(:xmlel, name: "", attrs: [], children: [])

  def ns_pubsub,
    do: "http://jabber.org/protocol/pubsub"

  def run do
    jid = "example@abc.com"

    IO.inspect xmlel(
        name: "pubsub",
        attrs: [{"xmlns", ns_pubsub()}],
        children: [
          xmlel(name: "subscribe", attrs: [{"node", "12121"}, {"jid", jid}])
        ]
      )
  end
end

Test.run()
```

#### It's output: 
`{:xmlel, "pubsub", [{"node", "12121"}, {"jid", "example@abc.com"}],
 [{:xmlel, "subscribe", [{"node", "12121"}, {"jid", "example@abc.com"}], []}]}`

### Expected behavior

The correct output maybe like this:
`{:xmlel, "pubsub", [{"xmlns", "http://jabber.org/protocol/pubsub"}],
 [{:xmlel, "subscribe", [{"node", "12121"}, {"jid", "example@abc.com"}], []}]}`

It was work for Elixir 1.9.4

**Comment by josevalim** [comment]
This has been fixed on Elixir master and v1.11. We will have a new release for v1.11 next week, thanks!
