### ISSUE TITLE
"Incompatible types in guard" warning

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10611]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.0-dev (compiled with Erlang/OTP 23)
* Operating system: Linux

### Current behavior

```elixir
  defguard size(struct)
           when is_map_key(struct, :map) and map_size(:erlang.map_get(:map, struct))

  #...

  def pop(%Foo{map: map} = struct, position) when size(struct) > 0 and position in [:end, nil] do
  	#...
  end
```

```
warning: incompatible types:

    integer() !~ true | false

in expression:

    # test/protocols/foo.ex:32
    is_map_key(struct, :map) and map_size(:erlang.map_get(:map, struct))

Conflict found at
  test/protocols/foo.ex:32: Foo.pop/2
```

The problem happens when we connect a statement that returns a boolean with one that returns something that is not, which are valid for the "and" operator since only the left side needs to evaluate to a boolean

### Expected behavior

No warnings at all

/cc @ericmj

**Comment by Eiji7** [comment]
@eksperimental If I remember correctly guards cannot return other type than boolean.

Example working code:
```elixir
defmodule Foo do
  defstruct [:map]
end

defmodule Example do
  defguard size(struct)
           when is_map_key(struct, :map) and map_size(:erlang.map_get(:map, struct)) > 0

  def pop(%Foo{map: map} = struct, position) when size(struct) and position in [:end, nil] do
    map
  end
end
```

btw. You did not check if `struct` in guard is map or struct. Also same goes to `struct.map`:

```elixir
defmodule Foo do
  defstruct [:map]
end

defmodule Example do
  # struct Foo always have :map key, so we do not need to call is_map_key/2 here
  defguard is_valid_foo(foo) when is_struct(foo, Foo) and is_map(foo.map) and map_size(foo.map) > 0
  # example for map
  #  defguard is_valid_foo(foo) when is_map(foo) and is_map_key(foo, :map) and  is_map(foo.map) and map_size(foo.map) > 0

  def sample(foo) when is_valid_foo(foo), do: {:ok, foo}
  def sample(_foo), do: {:error, :invalid_foo}
end

iex> Example.sample(5)                 
{:error, :invalid_foo}
iex> Example.sample(%{})
{:error, :invalid_foo}
iex> Example.sample(%Foo{})
{:error, :invalid_foo}
iex> Example.sample(%{map: %{}})
{:error, :invalid_foo}
iex> Example.sample(%Foo{map: %{}})
{:error, :invalid_foo}
iex> Example.sample(%{map: %{a: 5}})
{:error, :invalid_foo}
iex> Example.sample(%Foo{map: %{a: 5}})
{:ok, %Foo{map: %{a: 5}}}
```

**Comment by josevalim** [comment]
It seems to be a bug because we are checking for the guard at invocation time, i.e. when we know that it is going to be compared with `> 0`. Here is a how I reproduced it:

```elixir
defmodule Foo do
  defstruct map: %{}

  defguard size(struct)
           when is_map_key(struct, :map) and map_size(:erlang.map_get(:map, struct))

  def pop(%Foo{map: map} = struct, position) when size(struct) > 0 and position in [:end, nil] do
    #...
  end
end
```

**Comment by eksperimental** [comment]
> @eksperimental If I remember correctly guards cannot return other type than boolean.

They actually do. I read the docs because I had my doubts. I think this should be documented.

`defguard size(map) when map_size(map)` is totally valid.


> btw. You did not check if `struct` in guard is map or struct. Also same goes to `struct.map`:

Thank you for spotting it. Actually I did in my code, I did not in the example, just to simplify it.

> All of my examples do not show any error/warning.

Sorry, but the guard must return an integer. it is the whole point of implementing it, since I am using it `def foo(struct) when size(struct) > 0`

**Comment by eksperimental** [comment]
@Eiji7 just to make it clear. Guard expressions must return a boolean.

from the docs:
> Failing guards
> 
> A function clause will be executed if and only if its guard expression evaluates to true. If any other value is returned, the function clause will be skipped. In particular, guards have no concept of "truthy" or "falsey".

But guards can return anything, once evaluated they become an expression that must return true/false.
I think this should be clarified both in the defguard doc and the "Patterns and Guards" page.
