### ISSUE TITLE
Code.format_string!/2 doesn't insert parentheses for 1-arity call to a local function in a pipeline

### ISSUE THREAD

**Issue by jonleighton** [elixir-lang/elixir#10629]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
➜ elixir --version
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.12.0-dev (6a4b2ec) (compiled with Erlang/OTP 21)
```

* Operating system: Arch Linux

### Current behavior

test.exs:

``` elixir
defmodule Other do
  def omg, do: nil
  def omg(_a), do: nil
end

defmodule Test do
  def foo(a) do
    a |> Other.omg
    a |> omg

    Other.omg a
    omg a

    Other.omg
    omg
  end

  def omg, do: nil
  def omg(_a), do: nil
end
```

Run `mix format test.exs`.

The file now contains:

``` elixir
defmodule Other do
  def omg, do: nil
  def omg(_a), do: nil
end

defmodule Test do
  def foo(a) do
    a |> Other.omg()
    a |> omg

    Other.omg(a)
    omg(a)

    Other.omg()
    omg
  end

  def omg, do: nil
  def omg(_a), do: nil
end
```

### Expected behavior

I find it quite surprising that parens are not added to the `a |> omg` line.

The `omg` line emits a warning:

```
warning: variable "omg" does not exist and is being expanded to "omg()", please use parentheses to remove the ambiguity or change the variable name
```

In that case it's ambiguous, and a warning provides a nudge, so I don't expect the formatter to add parens.

But the `a |> omg` line is not ambiguous, and doesn't seem to fit into the no-parens-needed exceptions as specified in the docs for `Code.format_string!/2`:

>  Elixir has two syntaxes for function calls. With parens and no parens. By default, Elixir will add parens to all calls except for:
>
>   1. calls that have do/end blocks
>    2. local calls without parens where the name and arity of the local call is also listed under :locals_without_parens (except for calls with arity 0, where the compiler always require parens)

Is this behaviour intentional?

**Comment by wojtekmach** [comment]
I believe the reason the formatter does not do that is it would change semantics. Here's a weird pipe implementation that assigns to a variable:

```elixir
defmodule WeirdPipe do
  defmacro left |> right do
    quote do
      unquote(right) = unquote(left)
    end
  end
end

defmodule Main do
  import Kernel, except: [|>: 2]
  import WeirdPipe

  def main() do
    "foo"
    |> a

    IO.inspect(a)
  end
end

Main.main()
```

If the formatter would change `|> a` to `|> a()`, this program would break.

**Comment by jonleighton** [comment]
Interesting, that's a very funky edge case but it makes sense! Perhaps this bug should actually be a documentation fix then? (Assuming there's no way for the formatter to check that we're using the standard `Kernel.|>/2`?)

**Comment by josevalim** [comment]
Hi Jon!

It is documented the formatter does not change the AST - which is why we don't change the code here. `quote(do: a) != quote(do: a())`. I understand this is a roundabout way of explaining what you asked but I think it is good enough.

Generally speaking, unless the formatter breaks your code, it is working as intended. :)

> (Assuming there's no way for the formatter to check that we're using the standard Kernel.|>/2?)

Figuring that out requires code execution and the formatter doesn't execute code.

**Comment by jonleighton** [comment]
Hi José! Thanks for the explanation 😀
