### ISSUE TITLE
runtime: false triggers "the application is not available" when config exists for dependency

### ISSUE THREAD

**Issue by TheFirstAvenger** [elixir-lang/elixir#10624]
I have `:git_hooks` ([source here](https://github.com/qgadrian/elixir_git_hooks)) as a dependency in a project as `only: :dev, runtime: false`. It requires config to be specified in `dev.exs`. When I run the project in dev, I get the recently added warning:

```
You have configured application :git_hooks in your configuration file,
but the application is not available.

This usually means one of:

  1. You have not added the application as a dependency in a mix.exs file.

  2. You are configuring an application that does not really exist.

Please ensure :git_hooks exists or remove the configuration.
```

I am not sure if the issue is `:git_hooks` doing something it shouldn't be with it's config method, or if this is something that Elixir should be adjusted to recognize (i.e. search the full list of deps, not just the list of running applications).

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.11.2/22.3.1
* Operating system: macOS 10.15.7

### Current behavior

Warning noted above is displayed

### Expected behavior

No warning

**Comment by josevalim** [comment]
Related to #10546.

**Comment by josevalim** [comment]
The issue is the `only: :dev` option. Given it is only a dev dependency, i recommend wrapping it in a `if config_env() == :dev do` block. :)

**Comment by TheFirstAvenger** [comment]
@josevalim Apologies, but I am not clear exactly which section you mean to wrap in the `config_env()` check. This error appears when running in `:dev` env, so unless I am misunderstanding, the resulting code with the check would compile the same as it does now, and would still fail with the same warning.

**Comment by josevalim** [comment]
I cannot reproduce any warning (in master) if i put the config on config/dev.exs. Can you please share a sample project to make sure we are both looking at the same issue? :)

**Comment by TheFirstAvenger** [comment]
https://github.com/TheFirstAvenger/dep_warning_example

@josevalim Pull the above repo, `mix deps.get` and `iex -S mix` and you should see the warning. Verified still seeing it on the current master.

**Comment by jeremyowensboggs** [comment]
Here is another, similar example in an umbrella project: https://github.com/jeremyowensboggs/dep_warning_example.
You can see the warnings with a `mix test` or a ` MIX_ENV=test mix run -e "1"` from the root project.
