### ISSUE TITLE
Support absolute path passed as an environment variable in releases

### ISSUE THREAD

**Issue by D4no0** [elixir-lang/elixir#10638]
First of all I am happy to announce that I was able to run a phoenix liveview project on an android device !

The current limitation is that I had to manually modify `release_name/bin/release_name` and `release_name/releases/version/elixir` files to include the absolute path of the application:
`RELEASE_ROOT=/data/data/com.isotope11.erlanglauncher/files/test_phoenix_android`

This is required because starting Android 10, it is not possible anymore to have execute permission for files stored within the app's home directory (data), you can read more about this [here](https://github.com/JeromeDeBretagne/erlanglauncher/issues/2). 

The solution to this problem was to move the project to dynamic libraries, and symlink them at runtime, the problem with this approach is that commands like `cwd` will always point to the wrong path.

A [solution](https://github.com/erlang/otp/pull/2863) proposed and merged in otp repository is to add an environment variable that contains the absolute path to the project, such a solution should work in elixir too, and can be added to releases configuration as a new feature.

**Comment by josevalim** [comment]
Awesome news! ROOTDIR support pushed.

**Comment by wojtekmach** [comment]
@josevalim just double-checking, should Elixir be setting `ROOTDIR` or `ERL_ROOTDIR`? Here's the follow-up commit to https://github.com/erlang/otp/pull/2863: https://github.com/erlang/otp/commit/5475a9e25849adc7ab992e22dbcc93cd1667e528

**Comment by D4no0** [comment]
It seems there was a misunderstanding, the problem is not with ERTS (we use the erts from OTP that is compiled with android toolchain), the problem appears when we use the launch script `/bin/release_name.sh`, the file contains the lines:
```
SELF=$(readlink "$0" || true)
if [ -z "$SELF" ]; then SELF="$0"; fi
RELEASE_ROOT="$(cd "$(dirname "$SELF")/.." && pwd -P)"
```
It is possible to know the absolute path **only at runtime** , also all commands like relative directory will not work since all files are symlinked from **runtime generated paths**, it is the only current way to get this running on Android 10. Currently to make it work for a single application I had to replace `RELEASE_ROOT` with:
```
RELEASE_ROOT=/data/data/com.isotope11.erlanglauncher/files/test_phoenix_android
```
What I would like in this case is to add possibility to pass `RELEASE_ROOT` as environment variable.

This is also applicable to file `releases/0.1.0/elixir`, on lines:
```
SELF=$(readlink_f "$0")
SCRIPT_PATH=$(dirname "$SELF")
```

**Comment by josevalim** [comment]
I wonder that, instead of making those customizable, we could properly detect the absolute path in the first place?

**Comment by D4no0** [comment]
Sadly this is not possible with current symlinking, to understand why I will briefly explain how currently we transfer binaries on android:
All files from release folder are converted to temporary .so files (so that the files will be transfered to apk as shared objects). Such files will have **runtime paths** that change with every run of the application. Such technique is required since starting android 10, executable binaries can be run only from libraries folder which is read-only, as to tight up the security. Since the release folder contains multiple files, it is not possible to pack the folder into a single .so file without any extraction operations, so there will be 1 temporary path for **every** file from release. Later to be able to address the files correctly, symlinks are created and the folder/file structure/name is restored. Trying to use relative paths functions will result in resolving the name with the temporary path that will never work, since every file has a different temporary path.

This solution is a hack of course, however is the only solution I know and applications like termux are using it.

To solve this problem indefinitely, in theory the erts executables should be built to a single executable, in practice this is very hard to do as very little documentation is provided how to do it.

**Comment by josevalim** [comment]
Understood. We welcome then PRs that make those configurable as described above. If you have any questions, don't hesitate to ask. Thank you!
