### ISSUE TITLE
Formatter: Add option to remove parentheses

### ISSUE THREAD

**Issue by zimt28** [elixir-lang/elixir#10643]
Currently, functions listed under `:locals_without_parens` don't get extra parentheses unless they already have them. It would be nice to have a formatter option which removes parentheses, if a function is listed under `:locals_without_parens`.

I know the formatter shouldn't get (m)any options, but this just extends the one existing option and removes the only possible inconsistency in formatted codebases.

**Comment by josevalim** [comment]
Please see an explanation of why that is hard to achieve here: #8165. TL;DR: the formatter doesn't have complete understanding of the AST - for example, it doesn't know def is a function definition or that piping to `foo()` is actually calling `foo/1`, etc, which would make providing both directions complicated.
