### ISSUE TITLE
Invisible message line

### ISSUE THREAD

**Issue by RaymondLoranger** [elixir-lang/elixir#10640]
In the following session excerpt, the line starting with **Failed to use...** is invisible!!
I suspect it is because the foreground color is the same as the background color:

C:\Users\Ray\Documents\ex_dev\projects\islands_engine (master -> origin)
λ mix deps.get
Resolving Hex dependencies...

**Failed to use "poison" (versions 4.0.0 and 4.0.1) because**
  islands_coord (version 0.1.15) requires ~> 4.0
  islands_tally (version 0.1.10) requires ~> 3.0

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}

**Comment by josevalim** [comment]
Can you please post a screenshot? Thank you!

**Comment by RaymondLoranger** [comment]
![image](https://user-images.githubusercontent.com/4298228/104126676-e4aa5780-532b-11eb-80d0-109f7828fcf4.png)

**Comment by wojtekmach** [comment]
Could you `IO.puts IO.ANSI.format([:underline, "foo"])` on your machine, is it displayed properly?

**Comment by RaymondLoranger** [comment]
![image](https://user-images.githubusercontent.com/4298228/104127059-01478f00-532e-11eb-8383-00f6d672390b.png)

**Comment by josevalim** [comment]
Hi @RaymondLoranger, this message is printed by Hex, so I will transfer it to their repo. Can you please let us know your `mix hex.info`?

Although I have to say I looked at their repo and I didn't see anywhere where they would set the message to black. I also cannot reproduce it locally. Do you have another terminal emulator for Windows which you could give a try? Thanks!

**Comment by josevalim** [comment]
Actually, I cannot transfer as Hex is in another organization. Can you please open up a report there with hex.info and the info I just requested above? Thank you!
