### ISSUE TITLE
Unexpected whitespace trimming in EEx templates

### ISSUE THREAD

**Issue by lucazulian** [elixir-lang/elixir#10653]
### Environment

* Elixir 1.11.3 (compiled with Erlang/OTP 23) 
* Ubuntu 20.04.1 LTS

### Current behavior

Evaluating with EEx:
```
      <%= 123 %>
      <%=if false do %>
      <% end %>
      <%=if false do %>
      <% end %>











      
      <%= 789 %>
```

result:
```
      123


      789
```
 This result is obtained with `trim: true`.

### Expected behavior

```
      123











      
      789
```
I was expecting the previous result as stated in the documentation
`:trim - if true, trims whitespace left and right of quotation tags up until newlines. At least one newline is retained. Defaults to false.`

I'm sorry for the example, it's the only way I found for make clear my point.

**Comment by josevalim** [comment]
Hi @lucazulian! I think the confusion arises from what "whitespace" in the documentation means. In this case, "whitespace" also includes newlines. That's why it says at least one newline is retained, because it will trim all others.

**Comment by lucazulian** [comment]
Hi @josevalim thak you! Just a question: how can I achieve the expected behaviour? I've tried with `trim: false` but there is still something wrong in this case

**Comment by josevalim** [comment]
You need to disable trim but you may need to keep the if/end in a single line to avoid extra spaces. You can take a look at how Phoenix generators do it as an example.

**Comment by silvadanilo** [comment]
@josevalim so you intend "at most" one new line instead of "at least" ?

**Comment by josevalim** [comment]
It is rather exactly one new line, as we don't trim whitespace unless there is a newline and we remove all others, except one.
