### ISSUE TITLE
OTP releases with TLS enabled for distribution falis to communicate with running release

### ISSUE THREAD

**Issue by ConnorRigby** [elixir-lang/elixir#10656]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.11.3 (compiled with Erlang/OTP 23)
```

* Operating system:  
```
Linux connor-mini-pc 5.9.12-arch1-1 #1 SMP PREEMPT Wed, 02 Dec 2020 16:14:56 +0000 x86_64 GNU/Linux
```

### Current behavior

When creating a fresh release, and enabling TLS for Erlang distribution, the helper script in the release doesn't allow for communication.

from the started release:

```bash
env RELEASE_NODE=ssl_test1 _build/dev/rel/example/bin/example start_iex
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(ssl_test1@connor-mini-pc)1>                
12:24:58.578 [info]  TLS :server: In state :hello at tls_record.erl:539 generated SERVER ALERT: Fatal - Unexpected Message
 - {:unsupported_record_type, 0}
```

and from a different terminal trying to call `remote`:

```bash
env RELEASE_NODE=ssl_test1 _build/dev/rel/example/bin/example remote
Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Could not contact remote node ssl_test1@connor-mini-pc, reason: :nodedown. Aborting...
```

One work around is to edit the [outputed helper script](https://github.com/elixir-lang/elixir/blob/36417f5e62e2e3628c1bb84ed7a5da70d855f90e/lib/mix/lib/mix/tasks/release.init.ex#L204), changing the `remote` section to look something like:

```bash
  remote)
    exec "$REL_VSN_DIR/iex" \
         --werl --hidden --cookie "$RELEASE_COOKIE" \
         $(release_distribution "rem-$(rand)-$RELEASE_NODE") \
         --boot "$REL_VSN_DIR/$RELEASE_BOOT_SCRIPT_CLEAN" \
         --boot-var RELEASE_LIB "$RELEASE_ROOT/lib" \
         --vm-args "$RELEASE_VM_ARGS" \ # <--------------------------------------- add this line right here
         --remsh "$RELEASE_NODE"
    ;;
```

However i do not believe this is the correct solution.

I'm actually fine with this being a "closedwontfix" kind of situation, but i do think it's worth a short discussion if that's the case. 
I've made an example repository [here](https://github.com/ConnorRigby/elixir-distribution-ssl-example)

**Comment by tsloughter** [comment]
In rebar3/relx we parse out the needed distribution arguments from `vm.args` to use in stuff like `erl_call` and remote shells: https://github.com/erlware/relx/blob/master/priv/templates/extended_bin#L646-L658

**Comment by josevalim** [comment]
@tsloughter awesome, thank you! That sounds like too much work though and I don't want to implement that for Windows, haha. :D I am thinking a separate remote.vm.args would work great but maybe I should wait until we support the new connection modes in Erlang/OTP 23.1, just in case we introduce conflicts by the time we support it?

**Comment by tsloughter** [comment]
Probably don't have to worry about conflicts with 23.1.

I considered a `remote.vm.args` at one point, I think the only reason we didn't do it was it would require duplication and keeping them in sync. Probably less of an issue when using `.eex` templates for them.

**Comment by josevalim** [comment]
Thanks! Let's go the remote.vm.args route then!

**Comment by josevalim** [comment]
Added remote.vm.args in 4852fc51c4bbd07edf9013490fcc405ee097aa69.
