### ISSUE TITLE
eex adds unwanted newline

### ISSUE THREAD

**Issue by k-cross** [elixir-lang/elixir#10651]
### Environment

upgrading from `1.10.3`/`otp 22.3.4` to `1.11.2`/`otp 23.2.1`
MacOS Darwin 19.6.0

### Current behavior

Evaluating with `EEx`:
```
Package: <%= sanitized_name %>
Version: <%= version %>
Vendor: <%= vendor %>
Architecture: <%= arch %>
Maintainer: <%= maintainers %>
Installed-Size: <%= installed_size %>
<%= if external_dependencies != nil do %>
Depends: <%= external_dependencies %>
<% end %>
Priority: optional
Section: utils
Homepage: <%= homepage %>
Description: <%= description %>
```

result:

```
Package: foo
Version: foo
Vendor: foo
Architecture: foo
Maintainer: foo
Installed-Size: 123412

Depends: stuff

Priority: optional
Section: utils
Homepage: foo
Description: foo
```

Evaluating to `false` also adds a single newline which breaks from old behavior.

### Expected behavior

Evaluates w/o newline

```
Package: foo
Version: foo
Vendor: foo
Architecture: foo
Maintainer: foo
Installed-Size: 123412
Depends: stuff
Priority: optional
Section: utils
Homepage: foo
Description: foo
```

I checked and didn't see any mention of this behavior or duplicate in changelog or issue respectively. Thanks for everything!

**Comment by josevalim** [comment]
It is actually the opposite, EEx does not remove newlines, so the new lines are there because of the `if`.  You can rewrite it to:

```
Installed-Size: <%= installed_size %><%= if external_dependencies != nil do %>
Depends: <%= external_dependencies %>
<% end %>Priority: optional
```

or similar.

**Comment by k-cross** [comment]
Yes you're right, it's not removing the `newline` but the previous version did so the behavior has changed. Is that something worth addressing or adding an option for? If not, it's fine to close.

**Comment by josevalim** [comment]
The previous version was extremely hard to explain how it worked and understand, which led to bug reports and the fix for a more consistent behavior. Thanks!
