### ISSUE TITLE
`mix test –cover` crashes with a `FunctionClauseError`

### ISSUE THREAD

**Issue by ckruse** [elixir-lang/elixir#10666]
### Environment

~~~
Erlang/OTP 23 [erts-11.1.5] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
~~~

macOS 11.1 (20C69) 

### Current behavior

On a project I am maintaining I get the following error when running `mix test --cover`:

~~~
Cover compiling modules ...
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in :cover."-patch_code1/2-lc$^0/1-1-"/1
        cover.erl:2181: :cover."-patch_code1/2-lc$^0/1-1-"(2)
        cover.erl:2181: :cover.patch_code1/2
        cover.erl:2183: :cover."-patch_code1/2-lc$^1/1-0-"/2
        cover.erl:2183: :cover."-patch_code1/2-lc$^1/1-0-"/2
        cover.erl:2191: :cover.patch_code_tuple/5
        cover.erl:2183: :cover."-patch_code1/2-lc$^1/1-0-"/2
        cover.erl:2183: :cover."-patch_code1/2-lc$^1/1-0-"/2
        cover.erl:1649: :cover.transform/4
    cover.erl:602: :cover.call/1
    (mix 1.11.3) lib/mix/tasks/test.coverage.ex:142: anonymous fn/2 in Mix.Tasks.Test.Coverage.cover_compile/1
    (elixir 1.11.3) lib/enum.ex:2193: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.11.3) lib/mix/tasks/test.coverage.ex:141: Mix.Tasks.Test.Coverage.cover_compile/1
    (mix 1.11.3) lib/mix/tasks/test.coverage.ex:122: Mix.Tasks.Test.Coverage.start/2
    (mix 1.11.3) lib/mix/tasks/test.ex:336: Mix.Tasks.Test.do_run/3
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/task.ex:439: Mix.Task.run_alias/5

08:53:12.591 [error] Process #PID<0.3787.0> raised an exception
** (FunctionClauseError) no function clause matching in :cover."-patch_code1/2-lc$^0/1-1-"/1
    cover.erl:2181: :cover."-patch_code1/2-lc$^0/1-1-"(2)
    cover.erl:2181: :cover.patch_code1/2
    cover.erl:2183: :cover."-patch_code1/2-lc$^1/1-0-"/2
    cover.erl:2183: :cover."-patch_code1/2-lc$^1/1-0-"/2
    cover.erl:2191: :cover.patch_code_tuple/5
    cover.erl:2183: :cover."-patch_code1/2-lc$^1/1-0-"/2
    cover.erl:2183: :cover."-patch_code1/2-lc$^1/1-0-"/2
    cover.erl:1649: :cover.transform/4
~~~

### Expected behavior

The mix task should finish without an error and generate a coverage report.

**Comment by josevalim** [comment]
Hi @ckruse, thanks for the report. Unfortunately I will also need a way to reproduce this error. It is most likely caused by some code in `lib`. Something you can try is to slowly remove code in `lib` until you have one or two files that reproduce the issue. And then to the same for the file until you have a minimal snippet. If tests start running, it is because you have removed the file with the bug. Thank you!

**Comment by ckruse** [comment]
Hi @josevalim,

I already guessed that the provided information is not enough, sorry for that. I just didn't know what you need to identify the problem. I will do what you suggested as soon as the video call I'm currently struck in is finished ;-)

Regards,
 CK

**Comment by ckruse** [comment]
Hi @josevalim,

got it! It is a function with the name `clauses`. You can reproduce it by creating a new project via `mix new foobar` and create a function with the name `clauses` in the module. `mix test --cover` will fail with the error described above.

I created an example project at <https://github.com/ckruse/foobar>

**Comment by josevalim** [comment]
Thanks for the isolation, it helped a ton. PR to OTP sent here: https://github.com/erlang/otp/pull/2997

Please rename the function for now. :)

**Comment by ckruse** [comment]
Thank you for your work!
