### ISSUE TITLE
File.stream!/1 normalizes linebreaks

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#10668]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 23 [erts-11.1.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.2 (compiled with Erlang/OTP 23)
* Operating system: Mac OS X

### Current behavior

`File.stream!` normalizes linebreaks, which broke the assumption I had:
`Enum.into(File.stream!(file), <<>>) == File.read!(file)`

```elixir
iex(3)> File.write!("dummy", "test\n2\3")
:ok
iex(4)> File.stream!("dummy") |> Enum.to_list()
["test\n", "23"]
iex(5)> File.write!("dummy", "test\r\n2\3")
:ok
iex(6)> File.stream!("dummy") |> Enum.to_list()
["test\n", "23"]
iex(7)> File.stream!("dummy", [], 2048) |> Enum.to_list()
["test\r\n23"]
iex(8)> File.read!("dummy")
"test\r\n23"
```

### Expected behavior

Either have the normalization of linebreaks documented or have it not happen.

**Comment by josevalim** [comment]
This comes from the lower-level Erlang libraries, so it is not something we can easily change. Therefore a PR that updates the docs would be welcome. If we ever change this behaviour in the future, it would have to be via an option anyway.

**Comment by ericmj** [comment]
It is documented on the underlying erlang function http://erlang.org/doc/man/file.html#read_line-1 so we can do the same for `File.stream`.
