### ISSUE TITLE
mix deps.get unable to fetch docs, fills ram until the OS has to terminate it

### ISSUE THREAD

**Issue by Awlexus** [elixir-lang/elixir#10679]
### Environment
**Elixir & Erlang/OTP versions (elixir --version):** 
```
Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.0 (compiled with Erlang/OTP 23)
```
**Operating system:** Arch Linux x86_64 (Linux 5.10.10-arch1-1)

When I try to fetch the dependencies for a project the command produces the following output and then starts to fill up my whole ram (16GB) until the system shuts down the process.
```
$ mix deps.get
Resolving Hex dependencies...
```
This only happens with these exact dependencies:
```elixir
[
  {:phoenix, "~> 1.5.7"},
  {:phoenix_ecto, "~> 4.1"},
  {:ecto_sql, "~> 3.4"},
  {:postgrex, ">= 0.0.0"},
  {:phoenix_live_dashboard, "~> 0.4"},
  {:telemetry_metrics, "~> 0.4"},
  {:telemetry_poller, "~> 0.4"},
  {:gettext, "~> 0.11"},
  {:jason, "~> 1.0"},
  {:plug_cowboy, "~> 2.0"},
  {:ash, "~> 1.32"},
  {:ash_json_api, "~> 0.27.1"},
  {:ash_graphql, "~> 0.12.0"},
  {:absinthe, "~> 1.5"},
  {:absinthe_phoenix, "~> 2.0"}
]
```

## Steps to reproduce
* run "mix new test"
* set the dependencies in `mix.exs` to the list above
* run "mix deps.get"

P.S. I know that I could use `:override` to avoid this, but I think this should not happen.

**Comment by ericmj** [comment]
Do you have a `mix.lock` file? If so please include it.

**Comment by ericmj** [comment]
This is an issue with Hex so please reopen the issue on https://github.com/hexpm/hex.

**Comment by Awlexus** [comment]
@ericmj I[ moved the issue](https://github.com/hexpm/hex/issues/858) and to answer your question: No, I don't have a lock-file before or after the steps. (Mentioned this in the new issue)
