### ISSUE TITLE
Internal consistency check failed

### ISSUE THREAD

**Issue by srogers** [elixir-lang/elixir#10672]
### Environment

* Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1]
* Interactive Elixir (1.11.2)
* Operating system: MacOS 11.1 (20C69)

### Current behavior

given the file crash.ex :
```
defmodule Crash do
  def curious(value, opts \\ []) do
    width  = Keyword.get(opts, :width, 500.0)
    height = width  / 25.0 
    _middle = if value, do:  width / 2.0, else: 0
    _more = height + 1
  end
end
```
then

`iex(1)> c("crash.ex")` 

yields:

== Compilation error in file crash.ex ==
** (CompileError) Elixir.Crash: function curious/2+33:
  Internal consistency check failed - please report this bug.
  Instruction: {bif,fadd,{f,0},[{fr,0},{fr,1}],{fr,0}}
  Error:       {bad_floating_point_state,undefined}:

    (stdlib 3.13.2) lists.erl:1342: :lists.foreach/2
    (elixir 1.11.2) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
** (CompileError)  compile error
    (iex 1.11.2) lib/iex/helpers.ex:200: IEx.Helpers.c/2

This is a pared down example from a real module/function. Most any change in the structure will eliminate the crash.

**Comment by josevalim** [comment]
Thank you! Reported upstream as: https://bugs.erlang.org/browse/ERL-1471
