### ISSUE TITLE
Inconsistently shown binaries in test error output

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#10684]
### Environment

```
% elixir --version
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
```

### Current behavior

Give the following test case

```
defmodule MyTest do
	use ExUnit.Case, async: true
	test "test" do
		s1 = <<173, 14, 18, 92, 238, 131, 198, 219, 200, 150, 75, 161, 167, 101, 122, 54, 80, 70, 164, 120>>
		s2 = <<94, 143, 182, 177, 97, 141, 183, 114, 165, 85, 106, 231, 190, 231, 197, 215, 15, 133, 50, 242>>
		IO.inspect(s1, label: "s1")
		IO.inspect(s2, label: "s2")
		assert s1 == s2
	end
end
```
its output is:
```
% mix test
s1: <<173, 14, 18, 92, 238, 131, 198, 219, 200, 150, 75, 161, 167, 101, 122, 54, 80,
  70, 164, 120>>
s2: <<94, 143, 182, 177, 97, 141, 183, 114, 165, 85, 106, 231, 190, 231, 197, 215,
  15, 133, 50, 242>>


  1) test test (MyTest)
     test/my_test.exs:3
     Assertion with == failed
     code:  assert s1 == s2
     left:  "\xAD\x0E\x12\\\xEE\x83\xC6\xDBȖK\xA1\xA7ez6PF\xA4x"
     right: "^\x8F\xB6\xB1a\x8D\xB7r\xA5Uj\xE7\xBE\xE7\xC5\xD7\x0F\x852\xF2"
     stacktrace:
       test/my_test.exs:8: (test)

..

Finished in 0.07 seconds
1 doctest, 2 tests, 1 failure

Randomized with seed 938474
```

That is, the terms `s1` and `s2` are shown inconsistently in the output, in the case of `s1` as both `<<173, 14, 18, 92, 238, ...>>`  and `"\xAD\x0E\x12\\\xEE ..."`.

### Expected behavior

The terms should be shown consistently, preferably in this case in binary form `<<...>>` which seems the most easy to read and helpful for debugging the cause of a test error.

**Comment by josevalim** [comment]
They are both valid representations. We compared them as binaries of not valid before but then people noticed that one bad character would mess the comparison and make the diff less useful. So there is no approach that will work on all cases but since strings are more common, that’s what we chose. Thanks.
