### ISSUE TITLE
File.cd!/2 not parallel friendly

### ISSUE THREAD

**Issue by hrubi** [elixir-lang/elixir#10695]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.4 / 22.3.2
* Operating system: Gentoo

### Current behavior

Function `File.cd!/2` looks to me like a [bracket pattern](https://wiki.haskell.org/Bracket_pattern) which I would expect to safely execute the specified function in target directory. However, it is not. It calls `:file.set_cwd/1` and temporarily changes the global state of the Erlang file server (its CWD) for the timespan when the function is executed.

`File.cd!/2` is not parallel friendly. If some code uses relative paths and relies on the CWD of the file server to be the one the VM was started in, it can result in an error. See bug in Phoenix https://github.com/phoenixframework/phoenix/issues/4204.

Also when two `File.cd!/2` functions are called in parallel, there's a chance that the CWD won't be restored to the original one prior to those calls. See https://gist.github.com/hrubi/f1880665787d861fb84a20f491c0ee34.

### Expected behavior

Either the `File.cd!/2` is made parallel safe, or there's a warning in the documentation that it is not parallel safe.

**Comment by wojtekmach** [comment]
Please send a PR to improve `File.cd!/2` docs, we already mention concurrency concerns on `File.cd/1`.
