### ISSUE TITLE
Odd code formatting result with `force_do_end_blocks: true` 

### ISSUE THREAD

**Issue by halostatue** [elixir-lang/elixir#10691]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
  * Erlang/OTP 22 [erts-10.7.2.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
  * Elixir 1.10.4 (compiled with Erlang/OTP 22)
* Operating system:  MacOS

### Current behavior

We configured `.formatter.exs` to include `force_do_end_blocks: true`. This worked reasonably well, but causes problems with some DSL-ish macro definitions. Specifically:

```elixir
defmacro authorized(condition, clauses) do
  build_authorized(condition, clauses)
end

defp build_authorized(condition, do: do_clause, else: else_clause) do
  quote do
    if unquote(condition) do
      unquote(do_clause)
    else
      unquote(else_clause)
    end
  end
end

defp build_authorized(condition, do: do_clause) do
  else_clause = quote do
    {:error, "unauthorized"}
  end
  build_authorized(condition, do: do_clause, else: else_clause)
end
```

This gets formatted as:

```elixir
defmacro authorized(condition, clauses) do
  build_authorized(condition, clauses)
end

defp (build_authorized(condition) do
        do_clause
      else
        else_clause
      end) do
  quote do
    if unquote(condition) do
      unquote(do_clause)
    else
      unquote(else_clause)
    end
  end
end

defp (build_authorized(condition) do
        do_clause
      end) do
  else_clause =
    quote do
      {:error, "unauthorized"}
    end

  build_authorized(condition) do
    do_clause
  else
    else_clause
  end
end
```

### Expected behavior

We expect this to be formatted as:

```elixir
defmacro authorized(condition, clauses) do
  build_authorized(condition, clauses)
end

defp build_authorized(condition, do: do_clause, else: else_clause) do
  quote do
    if unquote(condition) do
      unquote(do_clause)
    else
      unquote(else_clause)
    end
  end
end

defp build_authorized(condition, do: do_clause) do
  else_clause =
    quote do
      {:error, "unauthorized"}
    end

  build_authorized(condition) do
    do_clause
  else
    else_clause
  end
end
```

I’d rather the forwarded call to `build_authorized` with the default else clause not be reformatted, but it makes sense.

Unwrapping the do/else/end blocks in the function definition, on the other hand seems wrong. The code compiles just fine, but it’s not really readable.

https://elixirforum.com/t/automatic-elixir-code-transforms-advanced-mix-format/37319/4

**Comment by josevalim** [comment]
The formatter is really not aware of the context, so if you force it, it will force everywhere. Your only option is to rewrite to pattern match so it happen inside the function and not the head.
