### ISSUE TITLE
Mix release RPC Logger cannot be configured

### ISSUE THREAD

**Issue by SophisticaSean** [elixir-lang/elixir#10710]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Operating system: MacOS/Ubuntu

### Current behavior

We build the release and start the app in production with `_build/dev/rel/genesis/bin/app start`. 
We use LoggerJSON to log structured logs for use in Datadog.
When connecting to the running app via `rpc` to issue it commands like periodic cron jobs, the logs from the `rpc` do not show up in stdout from the app. They show up in the process that made the `rpc` but without any structure/configuration. 

This forces me to wrap any `rpc` I want to do in a GenServer so the logs as a result of that call can be configured through our LoggerJSON and properly propagated to Datadog.

### Expected behavior

An RPC call should have a way to configure the standard logger to ensure the logs that result from that RPC are structured in the format your organization has configured.

**Comment by SophisticaSean** [comment]
I am open to any work arounds or help. I've been experimenting with this for about a week and have no answers.

**Comment by SophisticaSean** [comment]
This is not unique to LoggerJSON. Even simple tweaks to `:console` logger are not applied to an `rpc`.

**Comment by josevalim** [comment]
Hi Sean! I cannot reproduce it. Here is what I did:

1. mix new foo
2. changed lib/foo.exs to this:

```
defmodule Foo do
  require Logger
  def hello do
    Logger.error "OOPS"
  end
end
```

3. Add `config/runtime.exs` with:

```
import Config

config :logger, :console,
  format: "NODE [$level] $message $metadata\n"
```

4. `mix release`
5.  `_build/dev/rel/foo/bin/foo start`
6. `_build/dev/rel/foo/bin/foo rpc Foo.hello`

And I could see the information was logged in the `start` node in the given configuration. What am I missing? :)

**Comment by SophisticaSean** [comment]
Thanks Jose! 

Yes, my issue lies specifically with the output when you run step #6. The logs from the RPC are not formatted properly. I replicated your very thorough setup and the result from step #6 is not formatted and shows up as this:

`14:00:53.385 [info]  OOPS`

**Comment by SophisticaSean** [comment]
Let me test this out! It seems like it may be the solution. 

Is there an intuitive way that I would be able to know that `runtime.exs` would be the solution to this issue? I've really tried to research this as thoroughly as possible but it honestly never occurred to me that I would need runtime.exs for this. All of our release configuration is currently in `releases.exs`. 

It seems counter-intuitive to me that all logs take the proper formatting _until_ you use `rpc`.

**Comment by SophisticaSean** [comment]
Ok so `runtime.exs` has made it even more confusing. It seems that the runtime configuration doesn't respect backends other than `:console` for Logger. 

So I have my test module: 
```elixir
defmodule MyApp.Scheduler do
  require Logger
  def test_task() do
    Logger.info("Hello from test task")
  end

end
```

and my `runtime.exs`: 
```elixir
import Config

config :logger,
  level: :info,
  metadata: :all,
  backends: [:console, LoggerJSON]

config :logger, :console, format: "NODE [$level] $message $metadata\n"
```

This is the result from the `rpc` terminal (nothing is printed): 
```
_build/dev/rel/myapp/bin/myapp rpc "MyApp.Scheduler.test_task()"
```

This is the result from the `_build/dev/rel/myapp/bin/myapp start` terminal:
```
14:36:16.829 [info] Hello from test task
```

There should be two log lines. One from `:console` and one from `LoggerJSON`.

**Comment by SophisticaSean** [comment]
It should be noted that I get two log lines when the application starts up, which is expected behavior: 

```
{"time":"2021-02-13T14:32:42.369Z","severity":"info","message":"Starting task root supervisor","metadata":{}}
14:32:42.369 [info] Starting task root supervisor
```

**Comment by SophisticaSean** [comment]
I know why it's different. LoggerJSON is currently set to no-op when it is not the logger groupleader: https://github.com/Nebo15/logger_json/blob/master/lib/logger_json.ex#L115

When this RPC is made, it is not the group leader so it no-ops instead of logging the line. 

I have a path forward. My standing question would be: how would one reason about or what should they read in order to know that you'd have to use `runtime.exs` here to support RPC logging on the main node when a configuration in `releases.exs` seemingly works but doesn't support RPC logging?

**Comment by SophisticaSean** [comment]
For posterity: `releases.exs` won't work for Logger configuration at all when you `_build/dev/rel/myapp/bin/myapp start` your mix release. You have to use `runtime.exs` for that. I had some complicated logic that was configuring/starting/stopping backends and Logger at runtime when an `rpc` was made and it was confusing me on this issue.

**Comment by SophisticaSean** [comment]
Closing issue since everything has been resolved. Put your logger configurations in `runtime.exs`!
