### ISSUE TITLE
Issues with question and exclamation marks in atoms

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10722]
I have found some issues with messages that were not fully complying with the syntax.

1. This message should mention that atoms may end with ! or ?

```elixir
iex(21)> :"a!"
warning: found quoted atom "a!" but the quotes are not required. Atoms made exclusively of ASCII letters, numbers, and underscore do not require quotes
:a!

iex(22)> :"a?"
warning: found quoted atom "a?" but the quotes are not required. Atoms made exclusively of ASCII letters, numbers, and 
underscore do not require quotes
:a?
```

2. This one does not emit a warning in either case, but the atom is built. It should emit a warning when not using quotes.
```elixir
iex(25)> :"!"
:!
iex(26)> :!  
:!
```

3. This one fails to build the atom when quotes are not used.
```elixir
iex(29)> :"?"
:"?"
iex(30)> :?  
** (SyntaxError) iex:30:1: unexpected token: ":" (column 1, code point U+003A)
```

I can provide a fix for no. 1 and 2 once agreed on

**Comment by eksperimental** [comment]
I noticed that they were operators that and came to fix no2, and 3, to see your comment :rofl: 

Still, the warning message in no 1 needs to be fixed, since it is contradictory.
Maybe add ", or that end in ! or ? do not need to be quoted."

**Comment by josevalim** [comment]
I see, good call!

**Comment by eksperimental** [comment]
I noticed that the whole message had to be revamped to be strict to what the syntax expresses.

how about this warning?

> warning: found quoted atom "a!" but the quotes are not required. Atoms starting with a Unicode letter or an underscore, which may be followed by a sequence of Unicode letters, numbers, underscores, and @, and ending in ! or ? do not require quotes.

**Comment by josevalim** [comment]
This warning is to avoid people writing ["foo": bar] and thinking "foo" will be a string. It is actually ok if you want to write :"josé" to make it clearer that it is in Unicode - we just want to catch the basic ASCII cases.

**Comment by eksperimental** [comment]
then this?

> Atoms made exclusively of ASCII letters, numbers, and underscores, wich may end with a ! or a ?, do not require quotes

**Comment by josevalim** [comment]
I would rather no longer warn if it ends with `?` and `!`. WDYT?

**Comment by josevalim** [comment]
Although that may make it too much of a special case, it is probably best to just follow the identifier rule.

**Comment by eksperimental** [comment]
> Although that may make it too much of a special case, it is probably best to just follow the identifier rule.

so we warn?

**Comment by josevalim** [comment]
Yeah, I am not sure. We need to either:

1. Update the warning message to mention ? and !
2. No longer emit it for atoms ending with ? and !

**Comment by josevalim** [comment]
Ok, I think we should update the warning because someone may do this: `import Enum, only: ["empty?": 1]`. Could you please submit a PR? :)

**Comment by josevalim** [comment]
CLosing in favor of the PR.
