### ISSUE TITLE
Error in DateTime.new/4 docs when returning :ambiguous dates

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10731]
From the docs:

```elixir
  When the datetime is ambiguous - for instance during changing from summer
  to winter time - the two possible valid datetimes are returned. First the one
  that happens first, then the one that happens after.

      iex> {:ambiguous, first_dt, second_dt} = DateTime.new(~D[2018-10-28], ~T[02:30:00], "Europe/Copenhagen", FakeTimeZoneDatabase)
      iex> first_dt
      #DateTime<2018-10-28 02:30:00+02:00 CEST Europe/Copenhagen>
      iex> second_dt
      #DateTime<2018-10-28 02:30:00+01:00 CET Europe/Copenhagen>
```

It looks like the results are returned in the reverse order.

**Comment by josevalim** [comment]
It is not. I believe the first one is 12:30 UTC, the second is 01:30 UTC. :)

**Comment by eksperimental** [comment]
> It is not. I believe the first one is 00:30 UTC, the second is 01:30 UTC. :)

https://en.wikipedia.org/wiki/Central_European_Time
Central European Time (CET), used in most parts of Europe and a few North African countries, is a standard time which is 1 hour ahead of Coordinated Universal Time (UTC). The time offset from UTC can be written as UTC+01:00. 

https://en.wikipedia.org/wiki/Central_European_Summer_Time
Central European Summer Time (CEST), sometimes referred to as Central European Daylight Time (CEDT), is the standard clock time observed during the period of summer daylight-saving in those European countries which observe Central European Time (CET; UTC+01:00) during the other part of the year. It corresponds to UTC+02:00

Sorry, I am missing something fundamental. I am not aquanted with this Elixir module and time zones

**Comment by eksperimental** [comment]
You are right. +2 happens first than +1
