### ISSUE TITLE
SyntaxError when defining module attribute with numeric-starting key

### ISSUE THREAD

**Issue by vnbrs** [elixir-lang/elixir#10755]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Operating system: macOS 11.2.2

### Current behavior

When declaring module attributes starting with numbers, a syntax error pops up.

```
defmodule Test do
  @5_days_in_seconds 5 * 24 * 60 * 60
end
** (SyntaxError) syntax error before: '_days_in_seconds'
```

### Expected behavior

1. Is there any reasons not to accept numbers to start module attribute keys?
2. If there is, should this syntax error message be more detailed?

**Comment by wojtekmach** [comment]
My guess is module variables follow the same naming rules as regular variables:

```
iex(1)> 5_days_in_seconds = 5 * 24 * 60 * 60
** (SyntaxError) iex:1:2: syntax error before: '_days_in_seconds'
```

**Comment by josevalim** [comment]
Correct @wojtekmach! In fact, `@` is a unary operator like plus, not a special token, so you could actually write this `@ foo` and it would work:

```elixir
iex(1)> quote do: @foo
{:@, [context: Elixir, import: Kernel], [{:foo, [context: Elixir], Elixir}]}
iex(2)> quote do: @ foo
{:@, [context: Elixir, import: Kernel], [{:foo, [context: Elixir], Elixir}]}
```

For now, I think we can detect the case of identifiers starting with numbers in the tokenizer and raise accordingly.

**Comment by Eiji7** [comment]
> Is there any reasons not to accept numbers to start module attribute keys?

@vnbrs As mentioned above module attribute have exactly same syntax as variables:

> ![variable naming](https://rawgit.com/itsgreggreg/elixir_quick_reference/50ffe1e533896247fbb6429b72f83cdbb1186a8a/images/variable-naming.png)<br>
> 
> Source: https://github.com/itsgreggreg/elixir_quick_reference#variables

I can only guess why it's like that, but I would say that's for support syntax like: `0b1` (in this case it's an integer in a binary representation).

btw. Those examples are also worth to investigate:
```elixir
iex(1)> 0b2
** (SyntaxError) iex:1:2: syntax error before: b2

iex(1)> 0xG
** (SyntaxError) iex:1:2: syntax error before: xG
```

**Comment by kipcole9** [comment]
Elixir is Unicode-centric and part of the decision @josevalim made is to follow the identifier syntax which is described in [Unicode technical report 31](https://unicode.org/reports/tr31/) (with some incredibly minor differences). The core team also makes backward compatibility a commitment so your proposal is unlikely to get traction. If you feel passionately that the change has merit, then the recommended approach is to gather consensus in [Elixir Forum](https://elixirforum.com) or contribute a proposal to the [Elixir Core mailing list](https://groups.google.com/g/elixir-lang-core).
