### ISSUE TITLE
Config Module and Distillery

### ISSUE THREAD

**Issue by Sgoettschkes** [elixir-lang/elixir#10758]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.11.3 & 23
* Operating system: macOS 10.15.7

### Current behavior

I used the migration guide for the new Config module at https://hexdocs.pm/elixir/Config.html#module-migrating-from-use-mix-config. Running `mix distillery.release` now causes the following error message:

`Release failed: no :env key was given to this configuration file`

This error is caused by having `import_config "#{config_env()}.exs"` in my config.exs file.

### Expected behavior

If this is a bug, running `mix distillery.release` should not cause an error in the config module. If additional steps are needed to migrate from Mix.Config to Config in case of distillery, I'd appreciate some guidance (I couldn't figure it out) and would in return create a PR improving the migration documentation.

**Comment by josevalim** [comment]
Can you please include the whole stacktrace from the distillery error message?

**Comment by josevalim** [comment]
Actually, I got a fix. :) Meanwhile, the simplest fix is for you to continue using Mix.env() and Mix.target() instead of `config_env()` and `config_target()`.

**Comment by Sgoettschkes** [comment]
That was fast. Using `Mix.env()` is working, thanks! I assume it should be changed back to `config_env()` after the fix is released? In that case no change to the documentation would be needed.

**Comment by josevalim** [comment]
Fixed in master and v1.11.
