### ISSUE TITLE
Make install fails

### ISSUE THREAD

**Issue by tomciopp** [elixir-lang/elixir#10752]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.11.3
* Operating system: Mac OSX 10.15.7 (Intel)

### Current behavior
Trying to build elixir with Docker and am getting an error on the following line

$: git clone https://github.com/elixir-lang/elixir --depth 1 --branch v1.11.3 && cd elixir && make && make install
-> returned a non-zero code: 2

```bash
make: erlc: No such file or directory 
make: *** [Makefile:81: lib/elixir/src/elixir_parser.erl] Error 127
```

### Expected behavior

make && make install should correctly build elixir

**Comment by ericmj** [comment]
Given the error `erlc: No such file or directory` it looks like you are using a Docker image without Erlang installed.

For further questions or help please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow, where a wider community will be able to help you. Thank you!

**Comment by tomciopp** [comment]
@ericmj That's not the case.

**Comment by josevalim** [comment]
There is nothing we can do if the system cannot find erlc. Please try to investigate why erlc is not available, as it is not an issue specific to Elixir. :)
