### ISSUE TITLE
Release cannot start after migration to 1.11.x (File.Error on runtime.exs)

### ISSUE THREAD

**Issue by xadhoom** [elixir-lang/elixir#10768]
### Environment

* 1.11.3
* Operating system: Linux

### Current behavior

According to docs, Elxir 1.11.x introduced a new runtime.exs for releases config, but releases.exs is still supported. Instead if you start a release using the not yet deprecated releases.exs the release fails to start because runtime.exs cannot be found.

Looking into the code [here](https://github.com/elixir-lang/elixir/blob/v1.11/lib/mix/lib/mix/tasks/release.ex#L1215) seems that releases.exs is still supported while *assembling* the release, but gets renamed to runtime.exs and the final release expects to find it in place. This breaks existing systems which cannot continue to start with an existing config file (maybe deployed manually, via script or automated system), but those system must be updated to handle the new file name. 

I don't know if this is the intended behaviour or not (maybe it should support the old file also on release start?), for sure the docs should clarify this aspect.

### Expected behavior

Releases configured via releases.exs should start or at least the docs should mention that the existing file must be renamed to runtime.exs

**Comment by wojtekmach** [comment]
Could you paste the error you're getting or ideally share a sample app that showcases the problem?

I couldn't reproduce it locally, here's what I tried on v1.11.3:

```
~/tmp% mix new foo
~/tmp% cd foo
~/tmp/foo% mkdir -p config; echo "IO.inspect __ENV__.file" > config/releases.exs
~/tmp/foo% mix release
Compiling 1 file (.ex)
Generated foo app
* assembling foo-0.1.0 on MIX_ENV=dev
* using config/releases.exs to configure the release at runtime

Release created at _build/dev/rel/foo!

    # To start your system
    _build/dev/rel/foo/bin/foo start

Once the release is running:

    # To connect to it remotely
    _build/dev/rel/foo/bin/foo remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/dev/rel/foo/bin/foo stop

To list all commands:

    _build/dev/rel/foo/bin/foo

~/tmp/foo% _build/dev/rel/foo/bin/foo start
"/Users/wojtek/tmp/foo/_build/dev/rel/foo/releases/0.1.0/runtime.exs"
```

**Comment by xadhoom** [comment]
The problem is that your releases.exs got renamed to runtime.exs and it works (release assembly time)

The issue is that if an existing file releases.exs in *already* in the release path is not used at all. Basically try renaming `/Users/wojtek/tmp/foo/_build/dev/rel/foo/releases/0.1.0/runtime.exs` in 
 `/Users/wojtek/tmp/foo/_build/dev/rel/foo/releases/0.1.0/releases.exs` and the error will pop up.

My point that the doc does not mention this change, so if you have any automated deployment which manages a releases.exs you have to update it to avoid breaking the release start. Or releases.exs should be loaded from release dir if runtime.exs is not present.

**Comment by wojtekmach** [comment]
Gotcha, thanks for the explanation.

**Comment by josevalim** [comment]
> My point that the doc does not mention this change,

The reason it was not mentioned is because you should not fiddle with the release structure. :) It may change at any time and we don't guarantee modifying the assembled files will continue to work in the future.

Releases support a mechanism to load external configuration file, you could do this for example:

    releases: [
      demo: [
        config_providers: [{:system, "RELEASE_ROOT", "/custom.exs"}]
      ]
    ]

And now you can include a "custom.exs" at the root without changing the inner directories. In your case though, because you need to continue using the existing directory, you need to add the release version. This should work:

    releases: [
      demo: [
        steps: [&prepend_config_provider/1, :assemble]
      ]
    ]

    defp append_config_provider(release) do
      update_in release.config_providers, &[{:system, "RELEASE_ROOT", "/releases/#{release.version}/runtime.exs"} | &1]
    end

**Comment by xadhoom** [comment]
> The reason it was not mentioned is because you should not fiddle with the release structure.

Fiddling :) ? I was just expecting that my releases.exs works as before. The "renaming" was just an example, the real thing is that deployment scripts (or whatever) puts configs into releases.exs ( is meant for that I think ) and this does not work anymore, they must write configs into runtime.exs. Which is fine, simply not expected.

> Releases support a mechanism to load external configuration file

Ok fine, will follow that route so, even if now I think I completely misunderstood the usage of runtime/releases.exs . If I cannot configure them but use an external "include" to avoid naming changes of the file meant to have runtime configs what's the point in having them at all :) ?

To still *fully* support the old releases.exs the changes are trivial, by using `releases.exs` [here](https://github.com/elixir-lang/elixir/blob/v1.11/lib/mix/lib/mix/tasks/release.ex#L1219) and [there](https://github.com/elixir-lang/elixir/blob/v1.11/lib/mix/lib/mix/tasks/release.ex#L1220) if the `deprecated_path` is set everything is fine again.

But ok, back to understand what's the intended usage of runtime/releases.exs so. Maybe just configs set different from default when building the release itself?
