### ISSUE TITLE
Incorrect comparison between large integers and floating point numbers 

### ISSUE THREAD

**Issue by software-opal** [elixir-lang/elixir#10777]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
  ```
  Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

  Elixir 1.11.3 (compiled with Erlang/OTP 23)
  ```
* Operating system: Debian Buster -- The `elixir:1.11.3` docker container.

### Current behavior

```elixir
iex(1)> 51922944407877030 == 5.192294440787703e16
false
iex(2)> 51922944407877030 / 1 == 5.192294440787703e16
true
iex(3)> 5192294440787703 == 5.192294440787703e15 
true
```

### Expected behavior

The comparisons above should all return `true`:

```elixir
iex(1)> 51922944407877030 == 5.192294440787703e16
true
```

We've run into this issue because we receive numbers of the form `5.1...e16`, which are then persisted and parsed back in the form `51...`. This format change causes the types to be different(the first is a float, and the second an integer). We then rely on that comparison to perform other actions which created some weird effects in our code.

**Comment by wojtekmach** [comment]
Unsurprisingly we have the same issue in erl so if anything this is a BEAM issue:

```
$ erl
Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Eshell V11.1.8  (abort with ^G)
1> 51922944407877030 == 5.192294440787703e16.
false
```

**Comment by josevalim** [comment]
Float numbers will have imprecision at this size. You cannot assume that `5.192294440787703e16` is `51922944407877030`. Case in point:

```iex
iex> 51922944407877032 == 5.192294440787703e16
true
```

Notice I changed the last digit of the itneger from 0 to 2. This is not specific to Elixir either. Let's look at Python:

```python
>>> 51922944407877032 == 5.192294440787703e16
True
```

Or ruby:

```irb
irb(main):003:0> 51922944407877032 == 5.192294440787703e16
=> true
```

If you want to store such large numbers with such high precision then you should not be using floats. It is not a language fault, it is how floats behave. :)
