### ISSUE TITLE
Possible regression in protocol consolidation

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#10787]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 23 [erts-11.1.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.12.0-dev (c5373b9) (compiled with Erlang/OTP 23)

* Operating system: macos 10.15.7

### Current behavior

elixir-LS tests on elixir master started failing recently with
```
00:01:48.989 [error] Task #PID<0.2814.0> started from #PID<0.2775.0> terminating
** (CaseClauseError) no case clause matching: {:error, :not_a_protocol}
    (mix 1.12.0-dev) lib/mix/tasks/compile.protocols.ex:141: Mix.Tasks.Compile.Protocols.consolidate/4
    (elixir 1.12.0-dev) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.0-dev) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<9.50388162/0 in Mix.Tasks.Compile.Protocols.consolidate/6>
    Args: []
```
The crash happens when there are some stale beams. I wasn't yet able to reproduce it any other way so I'm not sure if this is an error in elixir/mix or elixir-LS tests are doing something they should not do.

**Comment by josevalim** [comment]
How are you running the tests? Can I just “git clone” and “mix test” it?

**Comment by lukaszsamson** [comment]
> How are you running the tests? Can I just “git clone” and “mix test” it?

Yes. The first time it happened was after switch from 1.11 to master so tere might be some stale beams left in apps/elixir_ls_utils/.temp. Then I cleaned this dir and ran mix test twice. The first succeeded but the second failed again. To investigate more I built elixir with some logs in protocol consolidation but I was not able to reproduce it since. Feel free to close.

**Comment by josevalim** [comment]
I can't think of any changes around this, except for a fix for `mix test --cover`. Were you using coverage by any chance? 🤔

**Comment by josevalim** [comment]
I couldn't reproduce, not even with `--cover`. If you have a mechanism to reproduce this, please let us know!

**Comment by lukaszsamson** [comment]
> Were you using coverage by any chance? 

No

> I can't think of any changes around this

I was thinking that https://github.com/elixir-lang/elixir/commit/58e36cdd0e45dbbb5aa5ebaf28b54f26f8e03de7#diff-b2e01f8516dc18e05207da103c1bedb110da9c4a56e22434cae68a2a41247d5e in combination with version switch might have led to some stale beams.

I'll reopen if it shows up again.
