### ISSUE TITLE
Regex \R treats Swedish letter "Å" unintuitively

### ISSUE THREAD

**Issue by henrik** [elixir-lang/elixir#10799]
We had an issue where a LiveView page suddenly started reloading itself infinitely. Turned out it was a sneaky issue where a string ended up as invalid UTF-8.

I realise this likely isn't technically a bug, but it seems unintuitive to me so I thought it might be worth raising to see if the developer experience could be reasonably improved somehow.

The issue is this:

``` elixir
iex(6)> String.split("Åland\nLine 2", ~r/\R/) |> hd
<<195>>
```
\R is documented in http://erlang.org/doc/man/re.html#newline_sequences as representing "any Unicode newline sequence".

The issue here is that "Å" is the bytes 195 and 133, and 133 is also "NEL (next line, U+0085)".

The docs mention that the "bsr_anycrlf" setting affects whether \R matches CR, LF, or CRLF only, or all of these obscure newline sequences. So I'm wondering if it could possible make sense in some future version of Elixir to set it that way by default. Backwards incompatible, but arguably better DX.

Though perhaps this is too much of an edge case to outweigh the backwards incompatibility?

Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.3 (compiled with Erlang/OTP 21)

**Comment by kipcole9** [comment]
This happened because unfortunately neither erlang or Elixir default to unicode mode in regex matching.  So if you add the `u` flag to your regex I believe you'll see the expected result:
```elixir
iex> String.split("Åland\nLine 2", ~r/\R/u) |> hd
"Åland"
```

**Comment by josevalim** [comment]
Closing per @kipcole9's comment above. :)

**Comment by henrik** [comment]
Thank you, @kipcole9 and @josevalim! I assume there are good reasons (perf and backwards compatibility?) not to change this default :)
