### ISSUE TITLE
Built-in `mfa()` type appears incorrect

### ISSUE THREAD

**Issue by nathanl** [elixir-lang/elixir#10805]
Maybe I'm missing something, but the built-in `mfa()` type on [Typespecs](https://github.com/elixir-lang/elixir/blob/601589e4be9c1b91aff47c74572ba6f22d2d6263/lib/elixir/pages/typespecs.md) seems to be incorrect.

Instead of `{module(), atom(), arity()}`, it should be `{module(), atom(), list()}`, right?

### Environment

* Elixir & Erlang/OTP versions (elixir --version):

Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.11.1 (compiled with Erlang/OTP 23)

* Operating system: MacOS 10.15.7

### Current behavior

[See runnable demo](https://github.com/nathanl/mfa_demo)

This code fails dialyzer:

```
defmodule MfaDemo do
  @moduledoc """
  Documentation for `MfaDemo`.
  """
  
  @doc """
  Applies an mfa and converts the return value to a boolean
  """
  @spec apply?(mfa :: mfa()) :: boolean()
  def apply?({m, f, a}) do
    !!apply(m, f, a)
  end
end
```

This code passes:

```
defmodule MfaDemo do
  @moduledoc """
  Documentation for `MfaDemo`.
  """
  @type actual_mfa :: {module(), atom(), list()}

  @doc """
  Applies an mfa and converts the return value to a boolean

  If the spec uses `mfa()` instead of `actual_mfa()`,
  `mix dialyzer` will fail.
  """
  @spec apply?(mfa :: actual_mfa()) :: boolean()
  def apply?({m, f, a}) do
    !!apply(m, f, a)
  end
end
```

### Expected behavior

I expect `mfa()` to be a tuple containing the arguments for `Kernel.apply/3`.

**Comment by ericmj** [comment]
`mfa()` is `{module(), atom(), arity()}`. The last argument is the number of arguments – not the actual list of arguments.

You can find the built-in types documented here: https://hexdocs.pm/elixir/typespecs.html#built-in-types.
