### ISSUE TITLE
Macro.camelize/1 should keep underscores between digits

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10839]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir master 

### Current behavior
Today I created an app called, "app1_12", the app module was name "App112" which renders it hard to read.

```elixir
iex> Macro.camelize("app1_12")                        
"App112"
```

### Expected behavior

Macro.camelize/1 should keep underscores between digits

```elixir
iex> Macro.camelize("app1_12")                        
"App1_12"
```

I can contribute a PR if this behaviour is the desired one.

**Comment by josevalim** [comment]
Given we preserve underscore between uppercase letters, we can do the same for digits too. PR is welcome.

**Comment by kelvinst** [comment]
I would gladly do this if no one else is interested 😄

**Comment by eksperimental** [comment]
> I would gladly do this if no one else is interested smile

@kelvinst please go ahead

**Comment by eksperimental** [comment]
> Given we preserve underscore between uppercase letters, we can do the same for digits too. PR is welcome.

Good call.

**Comment by kelvinst** [comment]
Just for clarification: `Macro.camelize("app_10")` should still return `App10` then?

**Comment by eksperimental** [comment]
> Just for clarification: `Macro.camelize("app_10")` should still return `App10` then?

Yes.

**Comment by kelvinst** [comment]
Worth noticing though, we never remove the underscores before upcased letters, it's not just when we have it between two of them:

```
iex(1)> Macro.camelize("foo_1")
"Foo1"
iex(2)> Macro.camelize("foo_A")
"Foo_A"
```
