### ISSUE TITLE
Function calls wrapped in literals are uncoverable

### ISSUE THREAD

**Issue by pmonson711** [elixir-lang/elixir#10847]
From the forum topic https://elixirforum.com/t/surprising-lines-missing-from-coverage-results/38571/2?u=pmonson711

### Environment

* Elixir & Erlang/OTP versions (elixir --version): (tested but I believe it's still in the lastest)
    Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

    Elixir 1.10.3 (compiled with Erlang/OTP 23) 

* Operating system:
    debian linux  

### Current behavior

1. create a new mix project `mix new coverage_why`
2. paste the following in lib/coverage_why.ex 

```elixir
defmodule CoverageWhy do
  def hello do
    :world
  end

  def i_has_coverage do
    hello()
  end

  def i_has_no_coverage do
    {:ok, hello()}
  end

  def i_has_no_coverage_as_well do
    [hello()]
  end

  def i_has_no_coverage_as_either do
    [hello()]

    :ok
  end
end
```
3. run `mix test --cover`

The calls to `hello()` wrapped in literals are not marked as uncovered.

### Expected behavior

I would expect the statements

- `{:ok, hello()}`
- `[hello()]`

to be marked uncovered.

**Comment by josevalim** [comment]
This has been fixed in master earlier today (after the forum comment).  Thanks for opening up the issue in anyway!
