### ISSUE TITLE
~7 Second (31%) difference between Mix test and mix test --partitions

### ISSUE THREAD

**Issue by SophisticaSean** [elixir-lang/elixir#10853]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.3 (compiled with Erlang/OTP 23) 
* Operating system: Ubuntu 18.04.5

### Current behavior

In a sufficiently large test suite, it is up to 31% faster for me to run the test suite using test partitions than it is by just running `mix test`. I've tried setting `--max-cases` to a larger number and the throughput doesn't seem to change. I've also tried to increase the ecto pool_size and that just serves to make the tests slower.

just `mix test`
```bash
time mix test --max-cases 256

................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 18.8 seconds
14 doctests, 754 tests, 0 failures

Randomized with seed 891883
mix test --max-cases 256  208.58s user 25.21s system 947% cpu 24.671 total
```

```bash
function run_tests {
  unset pids
  start=$(date +%s.%N);
  for i in {1..$1}; do
    MIX_TEST_PARTITION=${i} mix test --partitions $1 &                
    pids[${i}]=$!
  done

  for pid in ${pids[*]}; do
    wait $pid
  done
  dur=$(echo "$(date +%s.%N) - $start" | bc);
  printf "Execution time: %.6f seconds\n" $dur
};

run_tests 6;
[10] 18922
[11] 18923
[12] 18924
[13] 18925
[14] 18926
[15] 18928
............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

.Finished in 6.1 seconds
122 tests, 0 failures

Randomized with seed 311983
...[14]    18926 done       MIX_TEST_PARTITION=${i} mix test --partitions $1
.....................

Finished in 6.4 seconds
114 tests, 0 failures

Randomized with seed 400542
..[13]    18925 done       MIX_TEST_PARTITION=${i} mix test --partitions $1
..............................................................................................................................

Finished in 10.4 seconds
142 tests, 0 failures

Randomized with seed 233432
.[10]    18922 done       MIX_TEST_PARTITION=${i} mix test --partitions $1


Finished in 10.1 seconds
9 doctests, 145 tests, 0 failures

Randomized with seed 543530
[12]    18924 done       MIX_TEST_PARTITION=${i} mix test --partitions $1
.........

Finished in 11.3 seconds
3 doctests, 76 tests, 0 failures

Randomized with seed 532807
[15]    18928 done       MIX_TEST_PARTITION=${i} mix test --partitions $1
.

Finished in 11.6 seconds
2 doctests, 155 tests, 0 failures

Randomized with seed 427508
[11]    18923 done       MIX_TEST_PARTITION=${i} mix test --partitions $1
Execution time: 17.914845 seconds
```
This machine has 32 threads available.
We can see `mix test` took 24.671 seconds from startup to completion. `mix test --partitions 6` took 17.914 seconds leaving us with a difference of ~6.6 seconds.

### Expected behavior

Whatever magic is happening on test partition should be ported to vanilla `mix test` so we can save those precious 7 seconds.

**Comment by josevalim** [comment]
It is impossible for us to know the root cause without access to the suite. For example, maybe your tests are not marked as async? For this purpose, you can try Elixir master and let us know how much time it reports on sync vs async tests.

So if you can reproduce it somewhere publicly available, such as Hex.pm suite, then I will gladly take a look too. Otherwise my hands are tied. :)

**Comment by josevalim** [comment]
It can also be the bottleneck happens only ok a high number of cores. So if you have a 16 core, 8 core and 4 core machines, it would be good to know the difference!

**Comment by SophisticaSean** [comment]
> 
> 
> It can also be the bottleneck happens only ok a high number of cores. So if you have a 16 core, 8 core and 4 core machines, it would be good to know the difference!

I'll test this too!

**Comment by SophisticaSean** [comment]
I was able to replicate this on this branch: https://github.com/SophisticaSean/elixir-async-testing/tree/testing-performance-issues

I know the tests are contrived but I didn't want to have to write a bunch of application logic to replicate my issue. It has something to do with tests that take a lot of Ecto time. (and I imagine any other time as well). The behavior I see is that on the `mix test` run it'll sometimes hang on the longer running Ecto heavy tests. No other tests report as complete when it hangs on these Ecto heavy tests. I believe this is why running parallel `mix test --partitions` runs is faster, they all separately hang on those heavy Ecto tests but since they're running in parallel they don't collectively slow each other down.

My expectation would be that `mix test` would handle this case for me and have several other cpu threads working on other test files in tandem with the main `mix test` thread. So at any given time we should always have tests running and completing. 

Run tests script again (use `gdate` instead of `date` if you're on MacOs or Unix): 
```bash
function run_tests {
  unset pids
  start=$(date +%s.%N);
  for i in {1..$1}; do
    MIX_TEST_PARTITION=${i} mix test --partitions $1 &                
    pids[${i}]=$!
  done

  for pid in ${pids[*]}; do
    wait $pid
  done
  dur=$(echo "$(date +%s.%N) - $start" | bc);
  printf "Execution time: %.6f seconds\n" $dur
};
```

### Results
  - 32 Core Server ~2.6 ghz clock speed:
      - vanilla `mix test` average over 20 runs: 21.868 seconds
      - `run_tests 4` average over 20 runs: 17.3519 seconds
      - 31% speed difference.
  - Macbook Pro 2017 15in intel i7, 4 cores, 8 threads, 2.9 ghz clock speed:
      - vanilla `mix test` average over 20 runs:  31.4103 seconds
      - `run_tests 4` average over 20 runs: TBD macbook got low on battery and started throttling

**Comment by josevalim** [comment]
Thanks! This is most likely an Ecto issue then, can you please open it there? Unfortunately I cannot transfer it across orgs.

**Comment by josevalim** [comment]
Btw, my bash is complaining on this:

    -bash: {1..4}: syntax error: operand expected (error token is "{1..4}")

Do you know another version that doesn't rely on ranges? Otherwise I will google it later. Thanks!

**Comment by SophisticaSean** [comment]
> Thanks! This is most likely an Ecto issue then, can you please open it there? Unfortunately I cannot transfer it across orgs.

I'm working on an Ecto-free replication, if ecto is the issue I'll transfer it.

**Comment by josevalim** [comment]
> I pushed another simulated workload option that uses :timer.sleep instead of a bunch of Ecto queries and I have similar results:

Well, in this case it is easy. :) The profile of your tests is that they are mostly IO-bound. So run_tests of 6 is going to give you `2 * 6 * number_of_cores` max cases. So if you run `mix test --max-cases THAT_VALUE`, you should see similar performance as `run_tests 6`. In my case, I was able to go from 54s to 14s, which is faster than `run_tests`. Can you also try?

**Comment by v0idpwn** [comment]
TIL `--max-cases`. 

Found a weird behaviour: 
in the `test` task docs it claims that the default `max-cases` is twice the number of cores. Seems like this default wasn't working here: got a massive speed up in a project by setting `max-cases` to 6 or 12 in my 6 core 12 threads machine. What could be happening?

**Comment by josevalim** [comment]
@v0idpwn what does `System.schedulers_online` return to you?

**Comment by v0idpwn** [comment]
12

**Comment by josevalim** [comment]
Grep for max_cases in the project, as the default can be changed on ExUnit.configure/run.

**Comment by v0idpwn** [comment]
You're correct. Thanks and sorry for polluting here. ❤️

**Comment by SophisticaSean** [comment]
@josevalim awesome, I replicated your findings on the :timer.sleep implementation so it doesn't seem like an Ecto issue. I'll move this over there.
