### ISSUE TITLE
Backward imcompatible syntax introduced with new range operator

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10857]
I get hit by this a few times already so I am reporting it.
The AST atom representation of the new range operator `:"..//"` is formatted like that.
Now in Elixir v1.12+ the quotes are omitted, 

```elixir
Interactive Elixir (1.13.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :"..//"
:..//
iex(2)> :..//  
:..//
```

The problem is that prior to v1.12, omitting the quotes will generate a syntax error.

```elixir
Interactive Elixir (1.11.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :"..//"
:"..//"

iex(1)> :..//      
** (SyntaxError) iex:1:4: syntax error before: '/'
```

So code formatted with `mix format` in v1.12+ may not be backward compatible with earlier versions.
This is because all operators in Elixir are valid atoms and do not need to be quoted.
I think we should make the exception here, and implement the rule in v1.17 once 1.11 is no longer maintained.

PS: I can provide a PR for this

**Comment by josevalim** [comment]
@eksperimental good catch. Let's fix this in the formatter and add a TODO saying we can remove the automatic quotes v1.16. :) PRs welcome!

**Comment by eksperimental** [comment]
> > This is because all operators in Elixir are valid atoms and do not need to be quoted.
> 
> I found one exception to this rule! (well not exception to the rule per se, but different inspect behaviour)
> 
> ```
> iex(1)> :::
> :"::"
> ```
> 
> and I wonder if similar backwards compatibility concerns were the reason.

`:"//"` is the other one.
Here' s the reason behind (taken from the `Code.Identifier` module)

>     * `:not_atomable` - callable operators that must be wrapped in quotes when
>       defined as an atom. For example, `::` must be written as `:"::"` to avoid
>       the ambiguity between the atom and the keyword identifier

**Comment by josevalim** [comment]
`:"//"` is not an actual operator though. It exists in the internal inspection tools but it never surfaces as an operator to developers.
