### ISSUE TITLE
.beam files different between builds

### ISSUE THREAD

**Issue by schneebyte** [elixir-lang/elixir#10887]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
  Erlang/OTP 23 [erts-11.1.8] 
  Elixir (1.11.4)
* Operating system: Linux / NixOS

### Current behavior
Running
`ERL_COMPILER_OPTIONS=deterministic mix deps.compile`
or
`mix deps.compile`
multiple times on a Phoenix Project with :phoenix_live_dashboard "0.4.0"
produces a difference in the `Elixir.Phoenix.LiveDashboard.Helpers.beam` file.

I ran `mix deps.compile` about 10 times and got 2 different versions of the .beam file.

**Comment by josevalim** [comment]
We don't respect the Erlang compiler flag (it is about the Erlang compiler not Elixir's). Instead we track changes using `mix`.
