### ISSUE TITLE
Expose `Logger.Utils.scan_inspect/4`

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#10882]
Currently there is no `:io_lib.format`-like functionality in Elixir. The only possible approach is to use `:io_lib.scan/2` and then manually traverse the list in similar vain to `Logger.Utils`. However as we are slowly implementing more and more of #9465 we probably will want to encourage people to use Erlang's logger handlers in future, as these provide more possibilities. 

However to be able to work with Erlang's formatters we need to support messages in format of `{:io,format(), [term()}`. This mean, that having such functionality right there, without implementing it manually would be really handy for formatter authors.

This would also help some people that wanted to have more control over string formatting when working with numbers or floats (and potentially other data).

My proposal would be to add `IO.format/{2,3}` that would output `iodata()` with formatted string. 3rd argument would be similar to 2nd argument in `Kernel.format/2`.

**Comment by josevalim** [comment]
Let’s wait to cross this bridge when necessary on #9465 requires it. We can tackle it there.
