### ISSUE TITLE
Do path autocompletion in IEx

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#10888]
@fhunleth, can you kindly remind me what are the conditions to trigger this? Whenever we are at the beginning of a string? Or does the string have to start with `/` or `.`?

**Comment by fhunleth** [comment]
For https://github.com/elixir-toolshed/toolshed/blob/main/lib/toolshed/autocomplete.ex, I chose to only trigger when the string starts with `/` or `.`. I've run into a couple cases over the past few months where I've wanted a mid-string completion, but I don't remember specifics - it was probably when using `:os.cmd`. I don't think that my fingers have expected tab to work for file completion immediately after the `"`.

**Comment by kelvinst** [comment]
@fhunleth are you doing this already? If not, let me know and I can give it a try.

**Comment by fhunleth** [comment]
@kelvinst Thank you, thank you, thank you for asking. Every time I've gotten started, something has interrupted my progress, so please give it a try. If the toolshed code helps at all, feel free to copy as much or as little as you want.
