### ISSUE TITLE
URI.parse/1 strips [] from IPv6 address literals in host field

### ISSUE THREAD

**Issue by dch** [elixir-lang/elixir#10896]
### Environment

* `elixir --version: 1.11.4 Erlang/OTP 23 [erts-11.1.8] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1]  (compiled with Erlang/OTP 21)`

An IPv6 literal is the equivalent of `127.0.0.1`, e.g. `[fe80::]`. Per [RFC2732](https://tools.ietf.org/html/rfc2732) hostnames in URIs should be represented with the `[]` included.

Thanks @polymetis for the paired code spelunking to track this down.

### Current behavior

```
iex(1)> URI.parse("http://user:password@[fe80::]:1337/?foo=bar")
%URI{
  authority: "user:password@[fe80::]:1337",  <----- wrapped correctly
  fragment: nil,
  host: "fe80::", <----------- wrapping is missing
  path: "/",
  port: 1337,
  query: "foo=bar",
  scheme: "http",
  userinfo: "user:password"
}

## Erlang also does this

iex(2)> :uri_string.parse('http://user:password@[fe80::]:1337/?foo=bar')
%{
  host: 'fe80::', <------------ wrapping is missing
  path: '/',
  port: 1337,
  query: 'foo=bar',
  scheme: 'http',
  userinfo: 'user:password'
}
iex(3)> 
```

### Expected behavior

```
iex(4)>  URI.parse("http://[fe80::]/").host   
"[fe80::]"
```

### References

- [wikipedia](https://en.wikipedia.org/wiki/IPv6)  for a relatively digestable explanation

> Because IPv6 addresses contain colons, and HTTP uses colons as the port-address separator,
> RFC2732[39] specifies to use [square brackets] when using IPv6 addresses in URLs. e.g. > http://[2001:db8:4006:812::200e] (or, with a port, http://[2001:db8:4006:812::200e]:8080/path/page.html)

- normative ABNF  from [RFC3986 appendix A](https://tools.ietf.org/html/rfc3986#appendix-A) which updated and obsoleted RFC2732

- proposed deprecation of `URI.parse/1` in favour of Erlang's version https://github.com/elixir-lang/elixir/issues/10865

```
      IP-literal = "[" ( IPv6address / IPvFuture  ) "]"
```

- https://github.com/erlang/otp/issues/4731

### Background

When dealing with IPv6 only hostnames (servers that *only* have ip6 `AAAA` records in DNS), such as https://ipv6.google.com/ the impact is that downstream libraries try to treat the `IPv6 literal address` as a hostname, which obviously simply doesn't work. This fails in several places, for example, HTTP adapters used in Tesla, when the `userinfo` part of the URI struct is passed in as a header, and the ipv6 address is then used to reconstruct the URI from hostname, or any other `gen_tcp` like functionality.

### Options

- fix upstream `uri_string:parse/1` in Erlang because of proposed Elixir deprecation
- don't fix, but add an additional function to URI module, that can strip `userinfo` from `authority`
- do nothing to avoid Breaking The Internet

I'm happy to PR either case.

**Comment by josevalim** [comment]
Great breakdown. My suggestion is to:

1. Add a note to `URI.parse` that it removes the `[` and `]` from IPv6 addresses - we won't change this behaviour
2. Add a note to #10865 so we fix this behaviour when we replace URI.parse

Then depending on what Erlang answers we will have to choose if we will depend on their version or if we will have to roll our own on #10865.
