### ISSUE TITLE
Warn if @optional_callbacks is set inside protocol

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#10901]

**Comment by eksperimental** [comment]
I would like to take on this one.

Should we also warn if `@callback` and `@macrocallback` are used?

**Comment by josevalim** [comment]
Please go ahead! Note the idea is to warn on the @before_compile callback. We can warn for `@callback` and `@macro_callback` as well as long as it is relatively straight-forward. :) I think it will be hard because we will have some callbacks registered already from the definitions itself.
