### ISSUE TITLE
Modules with looping names are not properly aliased

### ISSUE THREAD

**Issue by filipeherculano** [elixir-lang/elixir#10928]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.4 (compiled with Erlang/OTP 22)
```

* Operating system: 20.04.1-Ubuntu

### Current behavior

```elixir
defmodule Test do
  alias A.B.A # aliased to A = A.B.A
  alias A.B.B # aliased to B = A.B.A.B.B
end
```

### Expected behavior

```elixir
defmodule Test do
  alias A.B.A # aliased to A = A.B.A
  alias A.B.B # aliased to B = A.B.B
end
```

Found this issue when trying to alias a module that starts and ends with the same module name. Unfortunately the expected behaviour is as described above. This looks to be not a huge problem, but sure it is a corner case. I did find (when trying to find any other related closed issues [here](https://github.com/elixir-lang/elixir/issues/316#issuecomment-6029672)) @josevalim saying the first module name is expanded and that's probably what is happening.

`alias A.B.B -> (A).B.B -> (A.B.A).B.B -> A.B.A.B.B`

A workaround for this issue (since we usually sort aliases given `mix format` rules) is to use `alias A.B.{A, B}`. However I do find it weird for one kind of usage giving this wrong result, so I think this is relevant.

*** If not too much to ask I would like to fix this issue myself (if any help guiding where I should look at will be helpful). I tried to fix it myself but I'm not too familiar with the codebase yet and decided to check if this is a known issue or just some undesired use of `alias` macro. However I failed to see anywhere in the docs this being warned

**Comment by Eiji7** [comment]
@filipeherculano As far as I know this is expected. In order to not have aliased `A` you should add `Elixir` prefix, for example:

```elixir
defmodule Example do
  alias A.B.A
  alias Elixir.A.B.B
end

{:module, Example,
 <<70, 79, 82, 49, 0, 0, 3, 196, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 133,
   0, 0, 0, 13, 14, 69, 108, 105, 120, 105, 114, 46, 69, 120, 97, 109, 112, 108,
   101, 8, 95, 95, 105, 110, 102, 111, 95, ...>>, A.B.B}
```

**Comment by josevalim** [comment]
Yes, this is expected. You have aliased A, so what A means will different in subsequent calls. Either do what @Eiji7 said or alias both at once:

  alias A.B.{A, B}
