### ISSUE TITLE
Float.parse - unexpected error from :erlang.binary_to_float

### ISSUE THREAD

**Issue by mindok** [elixir-lang/elixir#10939]
### Environment

Erlang/OTP 22 [erts-10.7] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Elixir 1.11.2 (compiled with Erlang/OTP 21)

### Current behavior

`Float.parse("1f2000")` returns `{1.0, "f2000"}` (expected)
`Float.parse("1e200")`  returns `{1.0e200, ""}` (expected)

`Float.parse("596e5441-78d2-4032-a08c-631ad4de8c04")` errors with stack trace

```
** (ArgumentError) argument error
    :erlang.binary_to_float("596.0e5441")
    (elixir 1.11.2) lib/float.ex:111: Float.parse_unsigned/4
```

### Expected behavior

`Float.parse("596e5441-78d2-4032-a08c-631ad4de8c04")` returns either `{596.0, "e5411..."}` or `{:error}` rather than raising

It is an edge case where it appears that the result could be a number outside the range for a float whereas it isn't really a parsable float in the first place.

**Comment by ericmj** [comment]
This is a documented behavior. Quoted from the `Float.parse/1` docs:

> If the size of float exceeds the maximum size of 1.7976931348623157e+308, the ArgumentError exception is raised.

**Comment by josevalim** [comment]
Closing per the above.
