### ISSUE TITLE
Improve user experience when calling def/2 inside protocol

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10937]
Users may be tempted to write the do block inside the protocol definition.

```elixir
defprotocol AProtocol do
  @spec foo(atom) :: :atom
  def foo(atom) when is_atom(atom), do: :atom 
end
** (CompileError) iex:3: undefined function def/2 (there is no such import)`
```

These should fail in a nicer way and/or be documented.

I think we could Improve the user experience by:
1. Adding a `def/2` function that raises, hinting the user to define a function head with `def/1`.
3. Improving the docs, mentioning that these callbacks must be defined in the same fashion we define function heads, using `def/1`

**Comment by josevalim** [comment]
We already explains how to define protocols on `defprotocol` but improvements are welcome. I would probably skip 1 for now. Thanks.
