### ISSUE TITLE
File.ls crashes with UnicodeConversionError

### ISSUE THREAD

**Issue by rengel-de** [elixir-lang/elixir#10959]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
* Erlang/OTP 22 [erts-10.7] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.11.2 (compiled with Erlang/OTP 21)

* Operating system: 
* Windows 10

### Error description

If a directory contains files with some filenames that have some weird Unicode characters in them, the `File.ls` and `File.ls!` commands crash, when I try to read the contents of the directory.

Here an example for such a filename in my `D:/Temp/Downloads` directory:

`GitHub - lpil_mix-test_watch_ 🎠 Because TDD is awesome.pdf`

And here the crash report:

```
iex(1)> my_path = "D:/Temp/Downloads"
"D:/Temp/Downloads"
iex(2)> File.exists?(my_path)
true    
iex(3)> File.ls(my_path)
** (UnicodeConversionError) invalid code point 55356
    (elixir 1.11.2) lib/list.ex:944: List.to_string/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.2) lib/file.ex:1567: File.ls/1
iex(3)>
```

Expected behavior:

Elixir should be able to handle any file name character that can be handled by the file system of the operating system.

**Comment by josevalim** [comment]
I assume there is something else at play. In your error message, it says codepoint 55356, which is invalid because [it is a high surrogate](http://www.unicode-symbol.com/u/D83C.html). However, the string pasted in your error message has the codepoint 127904, which is 🎠. Can you please use `:file.ls` in that directory and let us know what it returns? Something, somewhere, is returning actually invalid codepoint.

**Comment by rengel-de** [comment]
Sorry, don't know how to make `:file.ls`. I created a small file `ls_error.exs`:

```
defmodule LsError do
  def get_files(path) do
    # :file.list_dir(path)
    # :file.ls(path)
    File.ls(path)
  end
end

my_path = "D:/Temp/Downloads"
LsError.get_files(my_path)
```
Only the command File.ls works. Here is the output.

```
D:\projects\elixir\file_system>elixir ls_error.exs
** (UndefinedFunctionError) function :file.ls/1 is undefined or private
    (kernel 6.5.2) :file.ls("D:/Temp/Downloads")
    (elixir 1.11.2) lib/code.ex:931: Code.require_file/2

D:\projects\elixir\file_system>elixir ls_error.exs
** (UndefinedFunctionError) function :file.ls/1 is undefined or private
    (kernel 6.5.2) :file.ls("D:/Temp/Downloads")
    ls_error.exs:5: LsError.get_files/1
    (elixir 1.11.2) lib/code.ex:931: Code.require_file/2

D:\projects\elixir\file_system>elixir ls_error.exs
** (UnicodeConversionError) invalid code point 55356
    (elixir 1.11.2) lib/list.ex:944: List.to_string/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.2) lib/file.ex:1567: File.ls/1
    (elixir 1.11.2) lib/code.ex:931: Code.require_file/2
```

However, I can recreate the error any time. I have attached the file in question:
First, as raw pdf_

[GitHub - lpil_mix-test_watch_ 🎠 Because TDD is awesome.pdf](https://github.com/elixir-lang/elixir/files/6391051/GitHub.-.lpil_mix-test_watch_.Because.TDD.is.awesome.pdf)

Second, just in case, as a zip file:

[ls_error.zip](https://github.com/elixir-lang/elixir/files/6391119/ls_error.zip)


The file and its filename were created by a screenshot tool (Fireshot Pro, more info at the bottom of the pdf file). The pdf file just contains a full-page screenshot of [mix-test.watch](https://github.com/lpil/mix-test.watch).

Apparently, the Windows file system can handle such strange emoticons in filenames.

**Comment by josevalim** [comment]
Can you please try this?

    elixir --erl "+fnu" ls_error.exs

And yeah, I meant `:file.list_dir`. Can you please try `:file.list_dir` and `:file.list_dir_all`? Thanks!

**Comment by rengel-de** [comment]
Here my modified file:

```
defmodule LsError do
  def get_files(dir) do
    :file.list_dir(dir)
    |> IO.inspect(label: ":file.list_dir")
    :file.list_dir_all(dir)
    |> IO.inspect(label: ":file.list_dir_all")
    File.ls(dir)
    |> IO.inspect(label: "File.ls")
  end
end

my_dir = "D:/Temp/Downloads"
LsError.get_files(my_dir)
```

And the output:

```
D:\projects\elixir\file_system>elixir --erl "+fnu" ls_error.exs
:file.list_dir: {:ok,
 [
   [71, 105, 116, 72, 117, 98, 32, 45, 32, 108, 112, 105, 108, 95, 109, 105,
    120, 45, 116, 101, 115, 116, 95, 119, 97, 116, 99, 104, 95, 32, 55356,
    57248, 32, 66, 101, 99, 97, 117, 115, 101, 32, 84, 68, 68, 32, 105, 115,
    ...]
 ]}
:file.list_dir_all: {:ok,
 [
   [71, 105, 116, 72, 117, 98, 32, 45, 32, 108, 112, 105, 108, 95, 109, 105,
    120, 45, 116, 101, 115, 116, 95, 119, 97, 116, 99, 104, 95, 32, 55356,
    57248, 32, 66, 101, 99, 97, 117, 115, 101, 32, 84, 68, 68, 32, 105, 115,
    ...]
 ]}
** (UnicodeConversionError) invalid code point 55356
    (elixir 1.11.2) lib/list.ex:944: List.to_string/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.2) lib/file.ex:1567: File.ls/1
    ls_error.exs:7: LsError.get_files/1

D:\projects\elixir\file_system>elixir ls_error.exs
:file.list_dir: {:ok,
 [
   [71, 105, 116, 72, 117, 98, 32, 45, 32, 108, 112, 105, 108, 95, 109, 105,
    120, 45, 116, 101, 115, 116, 95, 119, 97, 116, 99, 104, 95, 32, 55356,
    57248, 32, 66, 101, 99, 97, 117, 115, 101, 32, 84, 68, 68, 32, 105, 115,
    ...]
 ]}
:file.list_dir_all: {:ok,
 [
   [71, 105, 116, 72, 117, 98, 32, 45, 32, 108, 112, 105, 108, 95, 109, 105,
    120, 45, 116, 101, 115, 116, 95, 119, 97, 116, 99, 104, 95, 32, 55356,
    57248, 32, 66, 101, 99, 97, 117, 115, 101, 32, 84, 68, 68, 32, 105, 115,
    ...]
 ]}
** (UnicodeConversionError) invalid code point 55356
    (elixir 1.11.2) lib/list.ex:944: List.to_string/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.11.2) lib/file.ex:1567: File.ls/1
    ls_error.exs:7: LsError.get_files/1

```

Could you recreate the problem on your machine?

**Comment by rengel-de** [comment]
An addendum: If I add another file (here: `ls_error.zip`) to the directory, the Erlang commands display this file's name as readable strings (as exepected):

```
D:\projects\elixir\file_system>elixir --erl "+fnu" ls_error.exs
:file.list_dir: {:ok,
 [
   [71, 105, 116, 72, 117, 98, 32, 45, 32, 108, 112, 105, 108, 95, 109, 105,
    120, 45, 116, 101, 115, 116, 95, 119, 97, 116, 99, 104, 95, 32, 55356,  
    57248, 32, 66, 101, 99, 97, 117, 115, 101, 32, 84, 68, 68, 32, 105, 115,
    ...],
   'ls_error.zip'
 ]}
:file.list_dir_all: {:ok,
 [
   [71, 105, 116, 72, 117, 98, 32, 45, 32, 108, 112, 105, 108, 95, 109, 105,
    120, 45, 116, 101, 115, 116, 95, 119, 97, 116, 99, 104, 95, 32, 55356,  
    57248, 32, 66, 101, 99, 97, 117, 115, 101, 32, 84, 68, 68, 32, 105, 115,
    ...],
   'ls_error.zip'
 ]}
** (UnicodeConversionError) invalid code point 55356
    (elixir 1.11.2) lib/list.ex:944: List.to_string/1
    (elixir 1.11.2) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2        
    (elixir 1.11.2) lib/file.ex:1567: File.ls/1
    ls_error.exs:7: LsError.get_files/1
```
Could it be that Erlang/Elixir don't know how handle emoticons just in filenames?

**Comment by josevalim** [comment]
Reported upstream, thanks! https://github.com/erlang/otp/issues/4779

**Comment by nixxquality** [comment]
Should the issue not be kept open until upstream can fix? I just ran into the same issue, emoji filename caused a crash in an Elixir application.
