### ISSUE TITLE
Doc: Language specification

### ISSUE THREAD

**Issue by inet56** [elixir-lang/elixir#10950]

**Comment by inet56** [comment]
@josevalim can you please tell why closed without a answer?

**Comment by josevalim** [comment]
When we open up an issue, there is a template. Please fill accordingly. It is unclear what you are asking if all you provide is a title.

**Comment by inet56** [comment]
I wanted to know is there a specification for elixir.

**Comment by josevalim** [comment]
There is a syntax reference and a bunch of related pages in our docs: https://hexdocs.pm/elixir/syntax-reference.html
