### ISSUE TITLE
Mix.install/2 with force: true is not working

### ISSUE THREAD

**Issue by rdlu** [elixir-lang/elixir#10969]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 23 [erts-11.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.12.0-rc.1 (ce321f8) (compiled with Erlang/OTP 23)
```
 
* Operating system: 
`ArchLinux updated today` 
using `asdf global elixir 1.12.0-rc.1-otp-23` and latest livebook with the README instructions.

### Current behavior

I tested this in a Livebook environment, trying to fix the deps I installed wrongly in the first run:

```
# install_opts = [force: true, verbose: true]
IO.puts(DateTime.utc_now())

# First run
Mix.install(
  [
    {:poison, "~> 3.1"},
    {:meeseeks, "~> 0.15.1"}
  ],
  force: true
)

# Second run
Mix.install(
  [
    {:httpoison, "~> 1.8"},
    {:meeseeks, "~> 0.15.1"}
  ],
  force: true
)
```

But I'm getting this on the second Mix.install:
`Mix.install/2 can only be called with the same dependencies in the given VM` 

### Expected behavior

Force option to properly delete the cached folder and install the second run of deps.

### Making it work by hand

I can get my livebook in a working state by using `rm -rf  ~/.cache/mix/installs/elixir-1.12.0-rc.1-erts-11.2.1`, but it seems that the force option is not deleting the right folder. 

By just deleting what is inside `.cache/mix/installs/elixir-1.12.0-rc.1-erts-11.2.1` I have the same dependencies message, but deleting the parent `elixir-VERSION-....` folder Mix.install install correctly. 

Thanks for this awesome tool! Looking forward to replace jupyter, just need to figure out this deps stuff.

**Comment by wojtekmach** [comment]
It’s not just a matter of busting the cache, the modules have been loaded into the VM and we’d need to properly unload them which is a bit tricky hence we left that for the future. This isn’t ideal but you need to restart your VM. In the meantime, maybe we should have an option in Livebook to restart the VM so you don’t need to go back to the terminal and grab the new url with the new token.

**Comment by josevalim** [comment]
You can restart the VM in Livebook by clicking on the runtime icon in the sidebar and then clicking reconnect. It is a limitation of Mix.install/2 at the moment that it can only be called once, which we may fix in the future, but force is working as expected. Thanks for the report!
