### ISSUE TITLE
IEx crashing on tab completion

### ISSUE THREAD

**Issue by ThePuzzlemaker** [elixir-lang/elixir#10970]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 24 [RELEASE CANDIDATE 3] [erts-12.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.0-rc.1 (ce321f8) (compiled with Erlang/OTP 24)
```
* Operating system: Arch Linux (installed with asdf)

### Current behavior

Contents of `foo.ex`:
```ex
defmodule Foo do
  def foo(a), do: a
end
```

- Run `iex foo.ex`
- Type `Foo.foo(` and then press tab
- An error occurs:
```
iex(1)> Foo.foo(*** ERROR: Shell process terminated! (^G to start new job) ***

11:30:47.973 [error] Process #PID<0.66.0> raised an exception
** (FunctionClauseError) no function clause matching in IEx.Autocomplete.expand_signatures/2
    (iex 1.12.0-rc.1) lib/iex/autocomplete.ex:135: IEx.Autocomplete.expand_signatures(:error, #PID<0.78.0>)
    (kernel 8.0) group.erl:596: :group.get_line1/5
    (kernel 8.0) group.erl:471: :group.get_chars_loop/9
    (kernel 8.0) group.erl:181: :group.io_request/6
    (kernel 8.0) group.erl:117: :group.server_loop/3
```

This appears to happen for any user-defined functions or functions from external libraries (including ones written in Erlang), except for ones with arity 0.

### Expected behavior

IEx should not crash and a completion list should be shown.

**Comment by v0idpwn** [comment]
Can confirm it also happens on master
