### ISSUE TITLE
Beam files aren't built with rebar3 3.14.4 + Elixir 1.12.0-rc.1 + build_embedded: true

### ISSUE THREAD

**Issue by fhunleth** [elixir-lang/elixir#10978]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```sh 
$ elixir --version
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.12.0-rc.1 (ce321f8) (compiled with Erlang/OTP 23)
```

And

```sh
$ /Users/fhunleth/.asdf/installs/elixir/1.12.0-rc.1-otp-23/.mix/rebar3 --version
rebar 3.14.4 on Erlang/OTP 23 Erts 11.2
```

Since old rebar3 versions could affect this and that was originally an issue in my setup, I deleted all `rebar3` binaries every where else and reproduced on two machines.

* Operating system: 

OSX and Ubuntu

### Current behavior

Here's a demo: https://github.com/fhunleth/elixir_rebar3_test

When I build that test project, no `.beam` files get built in `cowlib`. This causes problems later on.

So far I've been able to narrow this down to whether `build_embedded` is enabled or not.

**Comment by fhunleth** [comment]
Updates:

1. `rebar3` builds `cowlib` successfully. The problem doesn't have to do with `rebar3` or how `rebar3` is invoked.
2. The problem is that the `_build/dev/lib/cowlib/ebin` is erased and then the contents of `deps/cowlib/ebin` are copied over. This is what makes it look like `cowlib` hadn't been built, but it was built.

If you change `symlink_ebin` to `false` at https://github.com/elixir-lang/elixir/blob/v1.12/lib/mix/lib/mix/tasks/deps.compile.ex#L329, it "fixes" the problem. I don't think it's the right fix, but that's where I've gotten so far.

**Comment by josevalim** [comment]
No longer symlinking ebins is the right thing but it won’t work for old rebar versions, so it is hard to get a fix for now that works for everybody. I will revert the breaking change on v1.12 but keep it in master and add the symlink ebin fix. Thanks for digging deeper!

**Comment by fhunleth** [comment]
Thanks! This is the only issue I've found on Nerves with Elixir 1.12. Everything else appears to work great.

**Comment by fhunleth** [comment]
FYI - I confirmed that a328bb8 fixes the issue with the Nerves project where I first encountered it. Thanks! 🎉
