### ISSUE TITLE
Issue with is_struct/2 and dialyzer

### ISSUE THREAD

**Issue by rodrigues** [elixir-lang/elixir#10972]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.11.4, OTP 23.3
* Operating system:  macOS

### Current behavior

The following code triggers a dialyzer error:

```elixir
  def test(value) do
    if is_struct(value, DateTime) do
      :foo
    else
      :bar
    end
  end
```

```shell
lib/is_struct_dz.ex:3:pattern_match_cov
The pattern
:variable_

can never match, because previous clauses completely cover the type
DateTime.

________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
```

Created this repo to help reproducing the issue: https://github.com/rodrigues/is_struct_dialyzer

### Expected behavior

This shouldn't trigger a dialyzer error. It seems to be something in Elixir side though, not sure 🤔

Thanks!

**Comment by v0idpwn** [comment]
Some more test samples, hope it helps:

`Elixir 1.11.4 (compiled with Erlang/OTP 24), Erlang/OTP 24 [RELEASE CANDIDATE 2]`: happens
`Elixir 1.12.0-rc1 (compiled with Erlang/OTP 24), Erlang/OTP 24 [RELEASE CANDIDATE 2]`: no error
`Elixir 1.13.0-dev (3c7e3bd) (compiled with Erlang/OTP 24), Erlang/OTP 24 [RELEASE CANDIDATE 2]`: no error
