### ISSUE TITLE
Failure in linked process during ExUnit on_exit doesn't change process exit code

### ISSUE THREAD

**Issue by chaodhib** [elixir-lang/elixir#10974]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.4 OTP 22
* Operating system: Ubuntu 

### Current behavior

The issue is very similar to https://github.com/elixir-lang/elixir/issues/5967 except here, it is about the [on_exit/2](https://hexdocs.pm/ex_unit/ExUnit.Callbacks.html#on_exit/2) callback: if an error occurs during the callback, that error does not influence the exit code. Also, the test is marked as succesful (despite the message "all tests have been invalidated")

```Elixir
defmodule SampleTest do
  use ExUnit.Case
  doctest Sample

  setup_all do
    on_exit(fn -> raise "boom" end)

    :ok
  end

  test "greets the world" do
    assert Sample.hello() == :world
  end
end
```

```
  1) SampleTest: failure on setup_all callback, all tests have been invalidated
     ** (RuntimeError) boom
     stacktrace:
       test/sample_test.exs:6: anonymous fn/0 in SampleTest.__ex_unit_setup_all_0/1
       (ex_unit 1.10.4) lib/ex_unit/on_exit_handler.ex:142: ExUnit.OnExitHandler.exec_callback/1
       (ex_unit 1.10.4) lib/ex_unit/on_exit_handler.ex:128: ExUnit.OnExitHandler.on_exit_runner_loop/0



Finished in 0.03 seconds
1 test, 0 failures
```

### Expected behavior

A non-zero exit code and the tests affected by the setup_all where the on_exit callback was initialized should be marked as failed.

**Comment by QuinnWilton** [comment]
I think I've got a fix for this. I'll PR it soon.
