### ISSUE TITLE
Unhelpful error for typespecs with inconsistent key syntax

### ISSUE THREAD

**Issue by nathanl** [elixir-lang/elixir#10973]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.1 (compiled with Erlang/OTP 23)
* Operating system: MacOS 10.15.7

### Current behavior

Starting from a valid typespec for `Spec.t()`:

```elixir
defmodule Spec do
  @type t :: %{
    size: non_neg_integer(),
    name: String.t()
  }
end
```

If we add an optional key, we get a confusing error:

```elixir
defmodule Spec do
  @type t :: %{
    size: non_neg_integer(),
    name: String.t(),
    optional(:color) => String.t() # (SyntaxError) lib/foo.ex:5:5: syntax error before: optional
  }
end
```

### Expected behavior

The error should explain that the fix is to convert all the keys to use the `=>` syntax:

```elixir
defmodule Spec do
  @type t :: %{
    :size => non_neg_integer(),
    :name => String.t(),
    optional(:color) => String.t()
  }
end
```

**Comment by KronicDeth** [comment]
That's not a typespec-specific issue.  It's how the grammar works for maps/structs.  You either need to use association operators (`=>`) or keywords (`<atom>:`) only, so potentially other error messages about maps/structs in general could be improved.

**Comment by FreedomBen** [comment]
I'm getting the error even when using the other syntax.  In other words, this doesn't work (it gives me the error):

```elixir
  @type t :: %__MODULE__{
          :id => String.t(),
          :zone_id => String.t(),       
          optional(:locked) => boolean()
        }
```

If I remove the `optional()` it compiles just fine:

```elixir
  @type t :: %__MODULE__{
          :id => String.t(),
          :zone_id => String.t(),
          :locked => boolean()
        }
```

Is this something that _should_ work?
