### ISSUE TITLE
CompileError: type variable tx is unused

### ISSUE THREAD

**Issue by azizk** [elixir-lang/elixir#10985]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.3 (compiled with Erlang/OTP 23)
* Operating system: Linux

### Current behavior

```elixir
defmodule X do
  # 1
  @spec create1(map) :: {:ok, map}
  def create1(params), do: {:ok, params}

  @spec create1!(tx) :: map when tx: var
  def create1!(params), do: create1(params) |> ok_or_raise()

  # 2
  @spec create2(map, map) :: {:ok, {map, map}}
  def create2(params1, params2), do: {:ok, [params1, params2]}

  @spec create2!(ty, ty) :: {map, map} when ty: var
  def create2!(params1, params2), do: create2(params1, params2) |> ok_or_raise()

  @spec ok_or_raise({:ok, data} | any) :: data | no_return when data: var
  def ok_or_raise(_)
  def ok_or_raise({:ok, x}), do: x
  def ok_or_raise(_), do: raise "error"
end
```

Getting: `** (CompileError) iex:6: type variable tx is unused`

### Expected behavior

I think it should compile, but I'm not entirely sure. I don't understand why the second function with 2 parameters compiles. Maybe Elixir considers the second `ty` as "usage"?

**Comment by josevalim** [comment]
We will improve the warning. The thing is that a type variable only makes sense if you use it more than once. Otherwise it is equivalent to term.

**Comment by azizk** [comment]
Thanks!
While I have your ear, can I ask you if this a known bug: when you define a remote type in a spec, such as `@spec fun(Post.t()) :: id`, the Elixir compiler and ElixirLS don't tell you that the module `Post` is not available (or misspelled). However, if you run dialyzer it tells you there's an unknown type but unfortunately without mentioning the file and line number. So when you're in the process of cleaning up spec warnings you'll have a hard time sometimes...

**Comment by josevalim** [comment]
We only do very basic validation of type specs. For the rest you really need dialyzer.

**Comment by azizk** [comment]
Hm, but isn't this arguably the most basic validation to do? That is to check if the symbol being referenced actually exists?

**Comment by azizk** [comment]
@josevalim I think it would help if you could clarify the meaning of `var`a bit more in the docs. The "Typespecs" page mentions `var` has "no restrictions". Isn't that the same as `term` or `any`?

**Comment by josevalim** [comment]
Yes but if two arguments have the same var, then they have the same type.
