### ISSUE TITLE
Mix wrongly passing flag to dependency tasks

### ISSUE THREAD

**Issue by szymon-jez** [elixir-lang/elixir#10982]
### Precheck

Checked and this looks like a bug.

#### Elixir & Erlang/OTP versions (elixir --version): 

```
Erlang/OTP 23 [erts-11.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.10.4 (compiled with Erlang/OTP 23)
```

and

```
Erlang/OTP 23 [erts-11.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.4 (compiled with Erlang/OTP 23)
```

#### Operating system

Linux

### Current behavior

Passing the `--force` flag to `mix ecto.load` causes it to run the `compile` task. It wrongly passes that flag to the dependency task.

#### Reproduction

1. `git clone https://github.com/socialpaymentsbv/mix-flag-bug-example && cd mix-flag-bug-example`
2. `mix do deps.get, compile`
3. `mix ecto.load --force`
4. observe recompilation

##### Control run

Control run to make sure that the `--force` flag is indeed causing this and not something else.

1. `mix ecto.load`
2. Observe no recompilation

### Expected behavior

Running `mix ecto.load --force` should not force recompilation. It should only *"not ask for confirmation when loading data"* as `mix help ecto.load` says.

In other (more generic) words: Mix – as it is with Erlang/OTP 22 – should not pass the flags supplied (e.g. `--force`) to the runned task (e.g. `ecto.load`) to dependant tasks (e.g. `compile`).

#### Workaround

In `ecto.load` the workaround that can be applied is passing the flag `--no-compile`.

**Comment by josevalim** [comment]
Thanks for the report! This is an issue in ecto.load. It has full control over what to call downstream and with which args. Can you please move this issue to ecto_sql? Or please submit a PR: I think the easiest route is likely to rename it to `--yes`. Thank you.

**Comment by josevalim** [comment]
actually, it is better to delete --force from args, I will fix it there, no need for a report, thanks!

**Comment by szymon-jez** [comment]
Thanks José for looking in to it, but I don't know if I understand right: you want to remove the `--force` flag completely from `ecto.load`, yes?

And I'm curious how the upgrade from Erlang 22 to 23 caused this change in behavior?
