### ISSUE TITLE
Allow test files to be compiled

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#10983]
This will be an experimental feature for us to experiment on the timing for running tests. The idea is that we will add tests to the compilation directory and traverse them afterwards looking for any test unit case. Features such as --stale won't be available but most other features should work. We should explicitly support running a given file by doing a pass on the filtered beams source location.

**Comment by josevalim** [comment]
I have made some changes so it is possible to try this if someone is inclined to. Notice you will need Elixir v1.14 (unreleased currently, so you need main):

1. Rename all test files from `_test.exs` to `_test.ex`
2. Add an empty `test/noop_test.exs` to force tests to run
3. Add "test" to :elixirc_paths in `def project` and set `warn_test_pattern: "_nothing.exs"`
4. Remove doctests as they are not supported in compiled test modules
5. Add the following to the end of your `test/test_helper.exs`

```elixir
    for module <- Application.spec(Mix.Project.config()[:app], :modules) do
      ex_unit = Keyword.get(:erlang.get_module_info(module, :attributes), :ex_unit_async, [])

      cond do
        true in ex_unit -> ExUnit.Server.add_async_module(module)
        false in ex_unit -> ExUnit.Server.add_sync_module(module)
        true -> :ok
      end
    end
```

There are some sub-optimal things in this approach:

1. test code is compiled with regular code, and it should be a separate pass
2. doctests do not work (but it will be addressed when we solve 1)

However, it is enough to evaluate for improvements. In particular, I am looking for the time to run `time mix test` before and after this patch. In Livebook, I did not see a large difference in this approach (only 0.5s faster) but people with larger codebases may see different results. Feel free to post them here.

**Comment by Adzz** [comment]
FYI I had to change it to this:

```elixir
ex_unit = Keyword.get(module.module_info(:attributes), :ex_unit_async, [])
```

`:erlang.get_module_info` requires the module to be loaded and they weren't for me.

**Comment by josevalim** [comment]
Thanks, I have updated it!

**Comment by gmile** [comment]
@Adzz out of curiosity, have you been able to notice a positive change in the test running time? 🤔

**Comment by josevalim** [comment]
I got some reports and nobody was able to report actually meaningful gains, which is somewhat expected. So I will be dropping this idea for now. :)

**Comment by ding-an-sich** [comment]
One use-case for this not related to performance is to make flaky test suites slightly less painful to work with. We currently run in our CI something akin to `mix test  | mix test --failed` to automatically retry failed tests. 

The problem with that approach is that mix test --failed is happy to exit with code 0 if the previous run was aborted because of compilation errors, it simply sees no failed tests to rerun. If we could separate and independently compile test files we could catch common compilation errors like typos in variable names without running the test suite first.

**Comment by josevalim** [comment]
I don't see how that is possible. A syntax error in the test file will trigger the same syntax error once you run `mix test --failed`, exactly because there is no caching?

**Comment by ding-an-sich** [comment]
What I see on Elixir 1.13.4 (compiled with Erlang/OTP 24):

```elixir
defmodule TestFailedTest do
  use ExUnit.Case
  doctest TestFailed

  test "greets the world" do
    greet = TestFailed.hello()
    assert greeet == :world
  end
end
```

```bash
mix test --warnings-as-errors | mix test --failed --warnings-as-errors

> There are no tests to run
warning: variable "greeet" does not exist and is being expanded to "greeet()", please use parentheses to remove the ambiguity or change the variable name
  test/test_failed_test.exs:7: TestFailedTest."test greets the world"/1
warning: variable "greet" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/test_failed_test.exs:6: TestFailedTest."test greets the world"/1

echo $?
> 0
```

**Comment by josevalim** [comment]
Oh sure, if it is warning as errors then it is a known scenario. More info here: https://github.com/elixir-lang/elixir/issues/11484

**Comment by josevalim** [comment]
Thanks for clarifying!

**Comment by josevalim** [comment]
Also note that in recent releases we added different status code for failed tests and warnings as errors, so you can check what lead to a failure.

**Comment by ding-an-sich** [comment]
Hmmm, I'm seeing the same behavior without the --warnings-as-errors flag.

Will take a look at the different exit statuses and try to cook up a solution for our CI, thanks for pointing that out!

**Comment by michallepicki** [comment]
@ding-an-sich I've had a different workaround somewhere but tried this now and also seems to work (you'd need to adjust the path slightly):
```
mix test || (elixir -e "Application.ensure_all_started(:ex_unit);{_, failures} = ExUnit.Filters.failure_info(\"_build/test/lib/test_failed/.mix/.mix_test_failures\"); false = (Enum.count(failures) == 0)" && mix test --failed)
```
