### ISSUE TITLE
Invalid signature in docs for Kernel.SpecialForms.fn

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#10998]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12 and older

### Current behavior
`fn` is arity 1 macro but its spec in docs does not reflect it.
```
Code.fetch_docs(Kernel.SpecialForms)
[
...
{{:macro, :fn, 1}, 1568, ["fn"],
    %{
      "en" => ...
    }, %{}},
...
]
```

### Expected behavior
It would be best if it could return `"fn(clauses)"` similar to other macros from this module

I'd be happy to create a PR if given some pointers where to look

**Comment by josevalim** [comment]
I think the issue is that somewhere we skip the first argument of the macros when storing the signature. But we probably don’t want to do so if the macro is coming from special forms. The issue will most likely be around the Erlang part of the code base. :)
