### ISSUE TITLE
Hang on `DynamicSupervisor.which_children`

### ISSUE THREAD

**Issue by Chlorophytus** [elixir-lang/elixir#10997]
I'm not sure what is happening but I've deduced it to an OTP or Elixir bug. I'm not sure if it's upstream too. If needed, I can write a test case.

### Environment

* Elixir 1.12.0, Erlang/OTP 24.0.1
* Xubuntu 21.04

### Current behavior

Inside the `DynamicSupervisor`...
```elixir
  @spec ping_servers(integer) :: list
  def ping_servers(foo) do
    Logger.debug("PING SERVERS", bar: foo)
    children = DynamicSupervisor.which_children(__MODULE__)
    Logger.debug("PING SERVERS children ok", bar: foo)
    ping_server(foo, children, [])
  end
```
"PING SERVERS children ok" is never reached, and the IEx prompt hangs.

### Expected behavior

"PING SERVERS children ok" should be reached and `ping_server` should be called.

**Comment by v0idpwn** [comment]
Is your `ping_servers` function being called from the own dynamic supervisor process? (Such as in the init/1 callback)

**Comment by Chlorophytus** [comment]
> Is your `ping_servers` function being called from the own dynamic supervisor process? (Such as in the init/1 callback)
> I didn't manage to reproduce it here

It isn't being called from the own dynamic supervisor process.

**Comment by josevalim** [comment]
Hi @Chlorophytus ! The code as is should work, so we definitely need a mechanism to reproduce it. As @v0idpwn said, the most likely reason is that you are calling it on start_link/init/terminate that is being invoked by a supervisor.

**Comment by Chlorophytus** [comment]
> Hi @Chlorophytus ! The code as is should work, so we definitely need a mechanism to reproduce it. As @v0idpwn said, the most likely reason is that you are calling it on start_link/init/terminate that is being invoked by a supervisor.

This quirk should probably be better documented, I'll work around this by not calling `which_children` but having something else keep track of child PIDs.
Closing, feel free to reopen if I made a mistake in this regard.

:)
