### ISSUE TITLE
Missing specs in EEP 48 docs for callbacks

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#10999]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12 and earlier

### Current behavior

Currently elixir does not fill spces for callback entries, e.g.
```
Code.fetch_docs(Application)
[
...
{{:callback, :stop, 1}, 324, [],
    %{
      "en" => ...
    }, %{}}
...
```
It is filled for OTP callbacks though (since OTP 23 obviously)
```
Code.fetch_docs(:application)
[
...
{{:callback, :stop, 1}, [file: 'application.erl', location: 0],
    ["Module:stop(State)"], %{"en" => [{...}, ...]},
    %{
      edit_url: "https://github.com/erlang/otp/edit/maint/lib/kernel/doc/src/application.xml#L610"
    }}
...
```

### Expected behavior

It would be good if elixir also returned specs for callbacks. Now the only way to get them is through internal `Code.Typespec` (and IIRC there are no plans of exposing it publicly)

**Comment by josevalim** [comment]
This is intentional. We don’t want to duplicate the information that is already in the abstract code. Erlang adds it because their information is extracted from the XML file.
