### ISSUE TITLE
No warnings for this code

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#10994]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir master / OTP 24

### Current behavior

```elixir
  def foo(integer) when is_integer(integer), do: 1
  def foo(integer) when is_integer(integer), do: 2
  def foo(_), do: 3
```
Compiles without warnings

### Expected behavior

Shouldn't we emit a warning like:
warning: this clause for foo/1 cannot match because a previous clause at line 19 always matches

**Comment by josevalim** [comment]
Correct. Such warnings come from the Erlang compiler and are best-effort. It is not the job of the compiler to detect all of the possible scenarios where the is clause redundancy. In fact, it may even detect such cases, but it happens too deep in the compiler stack that makes it hard to trace back to the original source code.
