### ISSUE TITLE
Misleading warning when aliasing erlang module without as

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#11000]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12 and earlier

### Current behavior

```
defmodule My do
  alias :lists
end
```
results in
```
warning: unused alias :"Elixir.lists"
```

### Expected behavior

A more suiting warning or an error.

**Comment by kelvinst** [comment]
Is this open for PRs? Will we actually improve it? I think a warning like `use \`:as\` option when aliasing other BEAM languages modules`, WDYT?

**Comment by josevalim** [comment]
That’s what I have in mind too. I think we can error instead of warning as well.
