### ISSUE TITLE
Add support for --repeat to mix test

### ISSUE THREAD

**Issue by azizk** [elixir-lang/elixir#11016]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.0 (compiled with Erlang/OTP 24)
* Operating system: Linux

### Current behavior

Mix doesn't support a `--repeat` option, which makes repeating the previously executed tests difficult or inconvenient.

### Expected behavior

I'm missing such an option because:
* in an editor it's pretty simple to bind a shortcut to `mix test --repeat` which aids in TDD
* in the CLI it's practical to have mix repeat the tests if all succeeded after a `mix test --failed`
* likewise after a `mix test --stale` or any other similar command

**Comment by azizk** [comment]
Would love to see this implemented. :heart: Maybe I could do it but I don't think I'd be fast. I have no clue about the `mix` code base.

**Comment by wojtekmach** [comment]
Please send feature proposals to the elixir-lang-core mailing list :)

**Comment by azizk** [comment]
Sorry, my bad. :)

**Comment by josevalim** [comment]
Closing pending the mailing list discussion. I also think this may be implemented as `mix test --failed && mix test`? So it is important to discuss that too.
