### ISSUE TITLE
OptionParser.parse/2 silently accepts invalid modifiers

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#11017]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): master

### Current behavior

If we use an invalid modifier, e.g.: `:atom` or `:number` which one might expect are supported but actually aren't, it is simply ignored and the option is considered valid:

```elixir
iex> OptionParser.parse(~w(--proglang foo), strict: [proglang: :atom])
{[proglang: "foo"], [], []}
```

only if we use the proper modifier and the option doesn't conform to that, the option is considered invalid:

```elixir
iex> OptionParser.parse(~w(--proglang foo), strict: [proglang: :integer])
{[], [], [{"--proglang", "foo"}]}
```

### Expected behavior

I think we should either raise an ArgumentError or if that would be considered a breaking change, at least print a warning.

**Comment by josevalim** [comment]
A PR that raises an argument error is welcome!
