### ISSUE TITLE
Errors caused by List.foldl and Enum.reduce are inconsistent

### ISSUE THREAD

**Issue by pablohildo** [elixir-lang/elixir#11026]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.1 (Erlang/OTP 24)
* Operating system: Ubuntu 20.04.2 LTS

### Current behavior

The issue doesn't imply any kind of real threat or high priority bug, but it seems to me that since both functions implement the exact same behavior (both calling `:lists.foldl/3`), they should have similar returns.

```elixir
iex(1)> Enum.reduce([1, 2], 0, 1)
** (BadFunctionError) expected a function, got: 1
    (elixir 1.12.1) lib/enum.ex:2356: Enum."-reduce/3-lists^foldl/2-0-"/3
iex(1)> List.foldl([1, 2], 0, 1)
** (FunctionClauseError) no function clause matching in List.foldl/3

    The following arguments were given to List.foldl/3:

        # 1
        [1, 2]

        # 2
        0

        # 3
        1

    Attempted function clauses (showing 1 out of 1):

        def foldl(list, acc, fun) when is_list(list) and is_function(fun)

    (elixir 1.12.1) lib/list.ex:245: List.foldl/3
```

### Expected behavior

I feel like the error should be similar since the cause of the problem is the same in both cases. Although that does not cause any kind of high priority problem, I noticed that the solution seems to be pretty simple and non-breaking, as it appears to be related to the following:

https://github.com/elixir-lang/elixir/blob/v1.12.1/lib/elixir/lib/list.ex#L244-L247
https://github.com/elixir-lang/elixir/blob/v1.12.1/lib/elixir/lib/enum.ex#L2354-L2357

It's noticeable that both of them implement the same behavior, but `List.foldl/3` includes a guard that guarantees `fun` is actualy a function, while `Enum.reduce/3` doesn't.

I can work on this issue if it should be resolved.

**Comment by sushant12** [comment]
The `List.foldl/3`is using `is_function/1` guard clause. That's why the different err.

**Comment by josevalim** [comment]
Correct. Elixir APIs do not guarantee the format of such exceptions. For example, refactoring case to a function clause or to a with may change the error message from CaseClauseError to FunctionClauseError to WithClauseError. Other things, such as compiler inlining, may change some of those too, so this behaviour is expected. Thanks!
