### ISSUE TITLE
Warn if ?\lettter is used but there is no such escape sequence

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11028]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): v1.12 / OTP 24
* Operating system: Mac

### Current behavior

```
?\w == 119
```

### Expected behavior

The code above should print a warning: "unknown escape sequence ?\w, use ?w instead"

**Comment by QuinnWilton** [comment]
I've got this!

**Comment by josevalim** [comment]
Closing in favor of the PR!
