### ISSUE TITLE
undefined function when capturing function inside module

### ISSUE THREAD

**Issue by vinibrsl** [elixir-lang/elixir#11020]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.11.0 (compiled with Erlang/OTP 21)
* Operating system: macOS 11.4

### Current behavior

When capturing a module function, `undefined function` is raised.

```
defmodule TestModule do
  @test [
    foo: &String.upcase/1,
    bar: &bar/0
  ]

  def bar(), do: "bar"
end

** (CompileError) iex:21: undefined function bar/0
    (stdlib 3.14) lists.erl:1358: :lists.mapfoldl/3
    (stdlib 3.14) lists.erl:1359: :lists.mapfoldl/3
    (elixir 1.11.0) expanding macro: Kernel.@/1
```

I can only solve this by capturing the function with the module name, e.g. `&TestModule.bar/0`.

### Expected behavior

I was expecting the function to be capture without the module name, as it's being captured inside the same module the function is defined.

**Comment by wojtekmach** [comment]
You cannot call or capture a function from the module that is being defined.

**Comment by josevalim** [comment]
This is expected behavior. In a module body, functions have not been defined yet, so you can’t capture nor invoke them. You can use `__MODULE__` so it is an external reference but local references are not possible.
