### ISSUE TITLE
Erlang 24 changed Path.extname behaviour, returns empty string when only file extension is given

### ISSUE THREAD

**Issue by ZombieHarvester** [elixir-lang/elixir#11023]
### Environment

* Elixir 1.12.1 (compiled with Erlang/OTP 24)
* macOS Big Sur 11.3.1

### Current behavior

`Path.extname(".jpg") == ""`

### Expected behavior

`Path.extname(".jpg") == ".jpg"`

Behaviour from Elixir 1.12.1 (compiled with **Erlang/OTP 23**)

Upgrading to Erlang 24 changed the behaviour for `Path.extname` when only file extension is given without file name. With Erlang 23 it returns the extension, with Erlang 24 it returns empty string

**Comment by josevalim** [comment]
Yes, this was considered a bug fix on Erlang/OTP side, so we are considering the same here. In particular, the property that `filename == Path.basename(filename) <> Path.extname(filename)` was not held in previous OTP versions:

```iex
iex(1)> Path.basename(".gitignore")
".gitignore"
iex(2)> Path.extname(".gitignore")
".gitignore"
iex(3)>
```

But now works as expected:

```iex
iex(1)> Path.basename(".gitignore")
".gitignore"
iex(2)> Path.extname(".gitignore")
""
iex(3)>
```

Perhaps we should add a note to the docs?

**Comment by ForgottenGensym** [comment]
I started a PR to add a note to the documentation, as well as adding a couple of doctests to confirm the intended behavior. However, I realized that the Erlang/OTP bug fix for this doesn't apply to paths, only files that aren't inside any directories (relatively). 

More concretely,
### Current behavior
```elixir
Path.extname(".gitignore") == ""
Path.extname("~/foo/bar/.gitignore") == ".gitignore"
```

### Expected Behavior
```elixir
Path.extname(".gitignore") == ""
Path.extname("~/foo/bar/.gitignore") == ""
```

**Comment by ForgottenGensym** [comment]
Sorry about that, that was just an issue with CI. Never mind!
