### ISSUE TITLE
Check mix.exs elixir version requirement earlier

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#11032]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.1
* Operating system: 

### Description

Currently the elixir version requirement is checked when the application is started or compiled, but we should check before compiling dependencies.

Otherwise you will compile deps, get the error message, change elixir version, which will trigger recompilation of all deps again.

**Comment by josevalim** [comment]
I am on it.
