### ISSUE TITLE
Don't prevent n-ary replacement functions for String.replace/4 when pattern is a Regex

### ISSUE THREAD

**Issue by benhaney** [elixir-lang/elixir#11031]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.0 (compiled with Erlang/OTP 23)
* Operating system: macOS

### Current behavior

When using `String.replace/4` with a regex `pattern` argument, `replacement` functions are restricted to being unary.

ie, the following works with `Regex.replace/4`, which accepts an n-ary replacement function for accessing match groups:
```elixir
iex> Regex.replace(~r/_(\w)/, "foo_bar", fn _, c -> String.upcase(c) end)
"fooBar"
```

But the equivalent version using `String.replace/4` does not
(exception snipped to relevant bits)
```elixir
iex> String.replace("foo_bar", ~r/_(\w)/, fn _, c -> String.upcase(c) end)
** (FunctionClauseError) no function clause matching in String.replace/4

    Attempted function clauses:
        def replace(subject, pattern, replacement, options) when [...] is_binary(replacement) or is_function(replacement, 1)
```

### Expected behavior

Since `String.replace/4` essentially [delegates to `Regex.replace/4`](https://github.com/elixir-lang/elixir/blob/v1.12.1/lib/elixir/lib/string.ex#L1474-L1476) with a different argument order when the given `pattern` is a Regex, I would expect the `replacement` function to have the same capabilities and behavior in that case. But because of a guard on `String.replace/4`, n-ary replacement functions are blocked even though the internal call to `Regex.replace/4` would support them.

Wouldn't it make sense to change the guard on `String.replace/4` to allow n-ary functions when the `pattern` is a regex (and of course, continuing to forbid it when `pattern` is not a regex), so that this works?:

```elixir
iex> String.replace("foo_bar", ~r/_(\w)/, fn _, c -> String.upcase(c) end)
"fooBar"
```

Playing devil's advocate, I'll bring up the potential response of "just use `Regex.replace/4` for this," but then why does `String.replace(_, %Regex{}, _, _)` exist at all? It's just a convenient interface to `Regex.replace/4` where the string argument can be easily piped in, but it seems to (unintentionally?) block a bit of the normal functionality of `Regex.replace/4`

**Comment by josevalim** [comment]
Thanks for the well written issue!

I believe you spotted the root cause: I want to avoid large differences in the String API when it comes to the regex/string/compiledmatch argument. So the main reason is to keep the different arguments consistent. If you want to fully leverage the power of regexes, then you need to fallback to the Regex module, as you noted.

Note that the anonymous function was partly introduced exactly to normalize some of the differences regexes and strings (which was the insert_replaced option).
