### ISSUE TITLE
Potentially wrongfully reported compile times for %MyStruct{} in type specs

### ISSUE THREAD

**Issue by PragTob** [elixir-lang/elixir#11036]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Initial discovery and testing:

```
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.4 (compiled with Erlang/OTP 23)
````

Checking if it's still an  issue on the struct example with a newer version:

```
Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.0 (compiled with Erlang/OTP 24)
```

* Operating system: OSX 11.3.1

### Current behavior

On a bigger Phoenix application we always got tons of compile time warnings (longer than 10 seconds). Following the first steps of https://dashbit.co/blog/how-to-debug-elixir-erlang-compiler-performance we profiled the compile time and came out with lots of really large compile times (~19 20 seconds+, on a 13 inch MBP that is)

(all code snippets with application details removed)

```
# this was on elixir 1.11.4 with otp 23
[profile] lib/file.ex compiled in 22636ms
```

Notice also how it shows no waiting time. But the files themselves looked very innocent, one example that looks like many:

```elixir
defmodule SomeModule do
  @moduledoc false
  alias Other.Module

  @spec call(map(), %SomeStruct{}) :: {:ok, map()} | {:error, :reason}
  def call(params, country) do
    # 7 loc, calling one other not core elixir module
  end
end
```

Now, that was already very strange because there are no macros or anything special in there and from the linked blog post I understand the time (20 seconds!) was time spent compiling this module, plus it had no waiting time.

This even happened on struct definitions:

```
# elixir 1.12 with otp 24
[profile] lib/struct.ex compiled in 8665ms
```

```elixir
defmodule AStruct do
  @moduledoc false

  @derive Jason.Encoder

  @enforce_keys [
    :a,
    :b,
    :c,
    :d
  ]
  defstruct [
     :a,
    :b,
    :c,
    :d
  ]

  @type t :: %__MODULE__{
          a: String.t(),
          b: String.t(),
          c: String.t(),
          d: %AnotherStruct{}
        }
end
```

Now why am I thinking the time reported is wrong?

1. doing the "touch and compile again" from the blog post the compile time goes down to 100-500ms
2. The fix we applied to the code base is to reference a type instead of the struct directly, which reduces compile time dependencies (which I'd count as "waiting"), so for our `AStruct` example we'd do:

```elixir 
defmodule AStruct do
   # ...
  @type t :: %__MODULE__{
         # ...
          d: AnotherStruct.t()
        }
end

defmodule AnotherStruct do
   @type t :: %__MODULE__{}
end
```

which is semantically equivalent for the type checker. And that _really_ reduced reported compile times:

```
[profile] lib/struct.ex compiled in 386ms
```

This is repeatable. I removed occurrences of this in ~50 files  with a reported compile time of 5s+ from the code base and it always "fixed" it (going from even 30 seconds of "compile time" to 100ms with _this one weird trick_). However, the total compile time stayed the ~same. This, plus the major difference being it is a compile time dependency vs. not leads me to believe it is not correctly reported as waiting time but full compile time (both in the profiler and the "took longer than 10s to compile" warnings). Maybe I'm wrong though.

I haven't created an example to reproduce, as we'd need a lot of files but if needed I could try to reproduce in a branch of a bigger OSS project or something. Let me know, I hope it's already enough information :) 

### Expected behavior

I would expect the time to be reported as waiting time in the `--profile time` option as well as for it not to show up in the `Compiling lib/file.ex (it's taking more than 10s)` warnings (unless files waiting are supposed to show up there, but I don't think so).

**Thank you a lot for your amazing work as always, go have a bunny** 💚 

![IMG_20200719_072817](https://user-images.githubusercontent.com/606517/120821182-876ea700-c555-11eb-9a0f-28f03aa3b4c8.jpg)

**Comment by josevalim** [comment]
Thanks for the report. I was able to reproduce it with this:

```elixir
defmodule Foo do
  @spec hello() :: %Bar{}
  def hello do
    Bar.new
  end
end
```

```elixir
defmodule Bar do
  Process.sleep(3000)
  defstruct [:omg]
  def new, do: %Bar{}
end
```

I am investigating!

**Comment by josevalim** [comment]
Good news. I found out the root cause but the fix is a bit involved, so I am not very confident of including it on v1.12.

**Comment by PragTob** [comment]
Now I feel kinda stupid I didn't think of using sleep to reproduce the issue 😅

Thank you a lot for your outstanding work @josevalim, as always! 

![WhatsApp Image 2021-05-26 at 11 44 52](https://user-images.githubusercontent.com/606517/120936453-22a77e00-c708-11eb-803f-f5e83ac06104.jpeg)
