### ISSUE TITLE
no `@doc since: "1.12.0"`

### ISSUE THREAD

**Issue by TORIFUKUKaiou** [elixir-lang/elixir#11040]
### Current behavior

I find some functions of no `@doc since: "1.12.0"`.
similar: https://github.com/elixir-lang/elixir/pull/11039

Do these need to have `@doc since: "1.12.0"`?
If these need it, I am going to send a pull request.

- https://github.com/elixir-lang/elixir/blob/877ebd2e129fe2a469a363a8575edbb7400f3dda/lib/elixir/lib/io.ex#L560
- https://github.com/elixir-lang/elixir/blob/877ebd2e129fe2a469a363a8575edbb7400f3dda/lib/elixir/lib/io.ex#L519

### These have comments of "has been introduced in Elixir v1.12.0".
- I think that these may be unnecessary on them with `@doc since: "1.12.0"`.
- Do these need to have `@doc since: "1.12.0"`?
  - https://github.com/elixir-lang/elixir/blob/877ebd2e129fe2a469a363a8575edbb7400f3dda/lib/elixir/lib/list.ex#L286
  - https://github.com/elixir-lang/elixir/blob/877ebd2e129fe2a469a363a8575edbb7400f3dda/lib/elixir/lib/list.ex#L313

### On the other hand, these do not have comments of "has been introduced in Elixir v1.12.0".
- I think the comment may be necessary at least as List.first/2 or List.last/2.
  - https://github.com/elixir-lang/elixir/blob/877ebd2e129fe2a469a363a8575edbb7400f3dda/lib/elixir/lib/io.ex#L579
  - https://github.com/elixir-lang/elixir/blob/877ebd2e129fe2a469a363a8575edbb7400f3dda/lib/elixir/lib/io.ex#L546

By the way, I did the following blog post to check it out.
Only Japanese...
https://qiita.com/torifukukaiou/items/7230861686ad5adf31f5

**Comment by josevalim** [comment]
Yes, a pull request is welcome:

1. Add @doc since: ... to binstream/1 and stream/1
2. Add a comment to binstream/2 and stream/2

**Comment by wojtekmach** [comment]
Thanks @TORIFUKUKaiou for sending patches! I have a tool that is supposed to catch these omissions, https://github.com/wojtekmach/app_manifest, so feel free to use it to find more spots, if any. :)

**Comment by TORIFUKUKaiou** [comment]
@wojtekmach
Thank you very much for introducing your tool app_manifest.
I first know `Application.load`, `Code.fetch_docs` and Application.spec by reading app_manifest's code.
Thanks!

I use app_manifest. I can show a diff.
I will find spots by using  app_manifest in the near future.

I suppose that this issue is going to be resolved only IO.binstream, IO.stream.
