### ISSUE TITLE
Expression crashes when evaluated in the REPL

### ISSUE THREAD

**Issue by hansihe** [elixir-lang/elixir#11054]
### Environment
```
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Elixir 1.13.0-dev (5368761) (compiled with Erlang/OTP 22)
```

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

### Current behavior
When evaluated in the Elixir REPL, this expression will crash:
```
for n <- (a = 1; [1]), do: a
```

```
** (ErlangError) Erlang error: {:unbound, :_a@1}
    (stdlib 3.15.1) erl_eval.erl:214: :erl_eval.expr/5
    (stdlib 3.15.1) erl_eval.erl:229: :erl_eval.expr/5
    (elixir 1.13.0-dev) lib/enum.ex:2353: Enum."-reduce/3-lists^foldl/2-0-"/3
```

Interestingly, the expression compiles and runs as expected when compiled within a module instead of evaluated in the REPL.

### Expected behavior
The expression should evaluate in the same way as when compiled within a module, and should return `[1]`.

**Comment by hansihe** [comment]
As a small aside of this, is there a recommended easy way to view the erlang abstract format for an expression? That would be really useful for debugging in this case.

**Comment by josevalim** [comment]
https://github.com/michalmuskala/decompile

**Comment by hansihe** [comment]
Found `:elixir.quoted_to_erl/2` too which seemed to to do the job real quick in this case.

```
{:call, 0, {:remote, 0, {:atom, 0, :lists}, {:atom, 0, :reverse}},
  [
    {:call, 0, {:remote, 0, {:atom, 0, Enum}, {:atom, 0, :reduce}},
     [
       {:block, 0,
        [
          {:match, 0, {:var, 0, :_@1}, {:integer, 0, 1}},
          {:cons, 0, {:integer, 0, 1}, {nil, 0}}
        ]},
       {nil, 0},
       {:fun, 0,
        {:clauses,
         [
           {:clause, 0, [{:var, 0, :_@2}, {:var, 0, :_@3}], [],
            [{:cons, 0, {:var, 0, :_@1}, {:var, 0, :_@3}}]}
         ]}}
     ]}
  ]}
```

It looks like this should either succeed or fail both in `erl_eval` and the compiler. Could this be a bug in `erl_eval`?

**Comment by hansihe** [comment]
Yep, seems like it.

This compiles:
```
-module(abc).
foo() ->
lists:reverse('Elixir.Enum':reduce(begin
                                       _@1 = 1,
                                       [1]
                                   end,
                                   [],
                                   fun(_@2, _@3) ->
                                          [_@1 | _@3]
                                   end)).
```

While this fails in the erlang repl, same message as in my bug report.
```
lists:reverse('Elixir.Enum':reduce(begin
                                       _@1 = 1,
                                       [1]
                                   end,
                                   [],
                                   fun(_@2, _@3) ->
                                          [_@1 | _@3]
                                   end)).
```

**Comment by hansihe** [comment]
```
lists:reverse('Elixir.Enum':reduce(begin
                                       _@1 = 1,
                                       [1]
                                   end,
                                   [],
                                   fun(_@2, _@3) ->
                                          [_@1 | _@3]
                                   end))
```

Seems to fail both when compiled in a file and when run in the erlang repl.

Last post that I deleted was wrong, I forgot how colorless the erlc output was.

**Comment by josevalim** [comment]
This is a bug in the Elixir pass. Variables in arguments are not accessible in the same expression.

For example, you can't do this:

    foo(a = 1, a)

But the above compiles because we are missing a check and the Erlang compiler does not check it again... but the behaviour is likely undefined.

**Comment by hansihe** [comment]
Ah, that makes sense then.

I was operating under the assumption that the scoping of for expressions worked as follows, mainly just by looking at observed behavior.

```
# Scope 0
c = 0
for a <- (d = 1; [1, 2, 3]), b <- (e = 2; [1, 2, 3]) do
  f = 3
end
```

```
scope 0 do
  # c defined here
  # d defined here
  scope 1 do
    # a defined here
    # e defined here
    scope 2 do
      # b defined here
    end
  end
end
```

I take it you mean that each expression in each item in the `for` should have its own scope?

**Comment by josevalim** [comment]
It is hard to express the scope rules in the example above because the scoping rules are parallel. For example, foo(arg1, arg2) both build on the scope before foo and then merge it after foo. So in your example, it is easier to say that none of `d` and `e` are available inside scope 2 because they are defined in parallel with scope 2.

Although I think for for-comprehensions, we should probably go with what you propose, especially because the scoping roles for `with` do allow this kind of behaviour.

**Comment by hansihe** [comment]
Then `d` would be available in the outer scope, after the for expression too right? That would match the behavior of arguments of most other expressions.

`for` does seem to be a bit of a weird case though, in that it would have to have a rule that only the first item is ever within the enclosing scope.
