### ISSUE TITLE
Application.compile_env!/2 adds unnecessary compilation dependencies when given module names

### ISSUE THREAD

**Issue by devonestes** [elixir-lang/elixir#11052]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.12.0 (compiled with Erlang/OTP 23)

* Operating system: 
Linux Mint 19

### Current behavior

I recently found that when using modules as keys in configuration, accessing that configuration in your application using `Application.compile_env!/2` creates a compilation dependency on the file in which the module is defined. However, if I manually expand the "Elixir" version of that module name to the "Erlang" version, no compilation dependency is created and the configuration works just fine as intended. Below is an example:

```elixir
# mix.exs
defmodule CompileEnvExample.MixProject do
  use Mix.Project

  def project do
    [
      app: :compile_env_example,
      version: "0.1.0",
      elixir: "~> 1.12",
      start_permanent: Mix.env() == :prod,
      deps: []
    ]
  end

  def application, do: []
end
```
```elixir
# config/config.exs
import Config

config :compile_env_example, CompileEnvExample.Dep, :config_value

config :compile_env_example, CompileEnvExample.RawDep, :config_value
```
```elixir
# lib/compile_env_example.ex
defmodule CompileEnvExample do
  @val Application.compile_env!(:compile_env_example, [CompileEnvExample.Dep])
  @raw_val Application.compile_env!(:compile_env_example, [:"Elixir.CompileEnvExample.RawDep"])

  def val do
    IO.inspect(@val)
    IO.inspect(@raw_val)
  end
end
```
```elixir
# lib/dep.ex
defmodule CompileEnvExample.Dep do
end
```
```elixir
# lib/raw_dep.ex
defmodule CompileEnvExample.RawDep do
end
```

Given that Mix project, I can then see the compilation dependency with `xref`:

```
$ mix xref graph --source lib/compile_env_example.ex
lib/compile_env_example.ex
└── lib/dep.ex (compile)
```

### Expected behavior

I wouldn't expect a reference to a module like this to create a compilation dependency on that file since the module name is just an atom in this case (as seen by the manual "translation" to the "Erlang" version of the atom in the example above). Because the module is in this case only being used as an atom for configuration, I would expect no dependency at all.

**Comment by josevalim** [comment]
As a general rule, all atoms at the root will add compile-time dependencies because the compiler doesn't know how those atoms are being used. For example, maybe `Application.compile_env` is calling a function in said atoms.

However, in this case, `Application.compile_env` could expand them, since we know we won't use it.
