### ISSUE TITLE
Edge Cases in which mix format goes over the max line length

### ISSUE THREAD

**Issue by PragTob** [elixir-lang/elixir#11059]
👋  Hello lovely and thank you for the joy that is elixir and the formatter, I'm relying on them a lot 💚 

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
➜  formatter_bug git:(master) elixir -v
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.1 (compiled with Erlang/OTP 24)
```

(also experienced in 1.11.4 & OTP 23)

* Operating system: MacOS 11.3.1

### Current behavior

Using the standard .formatter.exs:

```elixir
# Used by "mix format"
[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
]
```

(so it's max_line 98 which is the default iirc)

(fresh project created)

the following file doesn't break lines on `mix format` that are over the max line length - places are indicated:

```elixir
defmodule FormatterBug do
  def hello do
    # this line is exacly 98 and formatted right and breaks once you add one character:         98
    {:world, :something, :something, :something, :something, :something, :something, :somethi, :a}
    # seems to "break" only when value is next line after `=`, seems like the closing parentheses
    # or something isn't counted
    val =
      hd([:world, :something, :something, :something, :something, :something, :h, :somethi, :abcd])

    # this seems to not count ` do`
    with {:ok, _} <- dummy_fun({:world, :something, :something, :someth, :somethi, :abcdefghjkim}) do
      "abc"
    end

    # this doesn't seem to count the closing parentheses (my initial example is from a deep ecto preload)
    %{
      a:
        {:value,
         {:world, :something, :something, :something, :something, :something, :sing, :somethi, :a}}
    }

    {:world, :something, :something, :something, :something, :something, :something, :somethi, :a}

    val
  end

  defp dummy_fun(a) do
    nil
  end
end
```

### Expected behavior

I would expect the formatter to break the lines in whatever way it prefers at the column at 98. I mean it's not critical, just noticed it with the credo max line length linter hitting code although the formatter is working.

-------------

Thank you very much for everything as always!

![IMG_20200607_075553](https://user-images.githubusercontent.com/606517/121673817-98696c00-cab1-11eb-9720-591c898696cb.jpg)

**Comment by josevalim** [comment]
There are many situations where we can't respect the line break because there is no opportunity to do a line break after we go over the line. FWIW, there is a fix, which is to add backtracking, but it makes formatting slow enough that it starts becoming impractical for things like format on save.

Usually we are one or two characters (keywords, parens, etc) but in cases like strings, you may be the whole string off. :) This is documented behaviour: https://hexdocs.pm/elixir/Code.html#format_string!/2-line-length

Thanks! 🐰

**Comment by PragTob** [comment]
Oh damn, my google didn't come up with that. Thanks @josevalim . It was kinda confusing because as you add another character it breaks. Worst case I found is 3 characters off, but agreed - I'd rather have it be 3 chars off but be faster.

Thanks for all the work and sorry for the noise! 💚
