### ISSUE TITLE
URI.decode_www_form should allow decoding of %%

### ISSUE THREAD

**Issue by dylan-chong** [elixir-lang/elixir#11068]
Although technically spec compliant, `URI.decode_www_form` fails to convert a `%%` to a `%`.
We do receive URLs which contain `%%` instead of `%25` from sources which we do not control.

Upon receiving a `%%` eg `curl 'http://localhost:4000/bla?value=%%'` we get an error:

```
** (Plug.Conn.InvalidQueryError) invalid urlencoded params, got %%
```

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.1 
* Phoenix: 1.5.9
* Operating system: Mac os 11.3

### Current behavior

```
iex(13)> URI.decode_www_form "http://localhost:4000/bla?value=%%"
** (ArgumentError) malformed URI "http://localhost:4000/bla?value=%%"
    (elixir 1.12.1) lib/uri.ex:440: URI.decode_www_form/1
iex(14)> URI.decode_www_form "http://localhost:4000/bla?value=%25"
"http://localhost:4000/pixel?value=%"
```

### Expected behavior

It would be nice to have the following behaviour

```
iex(13)> URI.decode_www_form "http://localhost:4000/bla?value=%%"
"http://localhost:4000/pixel?value=%"
iex(14)> URI.decode_www_form "http://localhost:4000/bla?value=%25"
"http://localhost:4000/pixel?value=%"
```

**Comment by josevalim** [comment]
Yes, according to the spec you are correct: https://url.spec.whatwg.org/#percent-decode

we should append % if it is not followed by digits.

**Comment by dylan-chong** [comment]
Ah hadn’t thought of that, thanks that’s a great idea
