### ISSUE TITLE
Error Message Lies

### ISSUE THREAD

**Issue by JEG2** [elixir-lang/elixir#11069]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):   

```
Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.12.1 (compiled with Erlang/OTP 22)
```

* Operating system:   macOS Big Sur 11.2.3

### Current behavior

```elixir
iex(1)> String.to_existing_atom("valid_utf8")
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: invalid UTF8 encoding

    :erlang.binary_to_existing_atom("valid_utf8", :utf8)
```

The error is a lie.  It's valid UTF-8, it just doesn't exist as an atom.

### Expected behavior

It would be great if it could tell us the atom doesn't exist.  If that's not possible though, we should at least stop giving an incorrect reason.

**Comment by thiamsantos** [comment]
I think it is the same error reported at https://github.com/elixir-lang/elixir/issues/11014. It seems to be already fixed in OTP https://github.com/erlang/otp/commit/c1942e39d44d50bb4bdf8e22456f31ee23931fdb.

**Comment by josevalim** [comment]
Precisely, thanks @thiamsantos and @JEG2!
