### ISSUE TITLE
`Record.extract_all` doesn't document `macro` option

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#11074]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.0
* Operating system: 

### Current behavior

Record.extract_all doesn't document `macro` option, not sure about the `includes` one, which I didn't try.

### Expected behavior

Have the docs be there or be pointer to `Record.extract`'s docs

**Comment by josevalim** [comment]
Please do send a PR that makes it point to `Record.extract` options. Thanks!
