### ISSUE TITLE
mix format should keeping user's formatting more.

### ISSUE THREAD

**Issue by lizhaochao** [elixir-lang/elixir#11087]
leave blank line which between functions cause functions are hard to read. such as:
```elixir
def make_something(%{} = data) do
  Enum.map(data, fn term -> {term} end)
end

def make_something(_other_data), do: nil

def make_other(%{} = data) do
  Enum.map(data, fn term -> {term} end)
end

def make_other(_other_data), do: nil
```  

expected:
```elixir
def make_something(%{} = data) do
  Enum.map(data, fn term -> {term} end)
end
def make_something(_other_data), do: nil

def make_other(%{} = data) do
  Enum.map(data, fn term -> {term} end)
end
def make_other(_other_data), do: nil
```

the same functions should be no blank line via options config or just keep user's formatting.

fold function block in pycharm ide like this:
```elixir
def make_something(%{} = data) do: ...
def make_something(_other_data), do: nil

def make_other(%{} = data) do: ...
def make_other(_other_data), do: nil
```
it will be readable more.

**Comment by josevalim** [comment]
Hi @lizhaochao,

We understand everyone has preferences on the formatter but we don't plan to make many more changes to how it behaves today. The good news is that, on Elixir v1.13, we will make all of the APIs that the formatter uses public, so people who want to roll their own can always do so.

Thank you,

**Comment by lizhaochao** [comment]
> Hi @lizhaochao,
> 
> We understand everyone has preferences on the formatter but we don't plan to make many more changes to how it behaves today. The good news is that, on Elixir v1.13, we will make all of the APIs that the formatter uses public, so people who want to roll their own can always do so.
> 
> Thank you,

I'd like to join it, there is a issue/task for formatter API public ?

**Comment by lizhaochao** [comment]
> Hi @lizhaochao,
> 
> We understand everyone has preferences on the formatter but we don't plan to make many more changes to how it behaves today. The good news is that, on Elixir v1.13, we will make all of the APIs that the formatter uses public, so people who want to roll their own can always do so.
> 
> Thank you,

hi @josevalim 

I'd like to join it, there is a issue/task for formatter API public ?

**Comment by josevalim** [comment]
This was the original discussion: https://groups.google.com/g/elixir-lang-core/c/-8CPorfVTxg

Note the issues and pull requests have already been merged though, so everything you need should be in master.
