### ISSUE TITLE
`IO.read(dev, :line)` defaults to `latin1` when fed a binary device

### ISSUE THREAD

**Issue by hansihe** [elixir-lang/elixir#11089]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
  ```
  Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
  Elixir 1.13.0-dev (82a9aa3) (compiled with Erlang/OTP 22)
  ```
* Operating system: `Ubuntu 20.04.2 LTS`

### Current behavior

Say I have a file `test.txt` with the following data encoded in UTF-8:
```elixir
abcæøå
```

When opened with the `utf8` encoding, we see what we expect:
```elixir
iex(1)> File.open!("test.txt", encoding: :utf8) |> IO.read(:line)
"abcæøå\n"
```

However, when no encoding is specified (binary), `IO.read` defaults to `latin1`. This means that the data will be decoded as latin1 and reencoded as a UTF8 binary:
```elixir
iex(4)> File.open!("test.txt") |> IO.read(:line)
"abcÃ¦Ã¸Ã¥\n"
```

This all seems to stem from [`:io.get_line`](https://erlang.org/doc/man/io.html#get_line-1) being used by `IO.read(dev, :line)`. The docs for it says:
> The function returns:
>
> Data
>     The characters in the line terminated by a line feed (or end of file). If the I/O device supports Unicode, the data can represent codepoints > 255 (the latin1 range). If the I/O server is set to deliver binaries, they are encoded in UTF-8 (regardless of if the I/O device supports Unicode).

This same behavior seems to be expressed by all variants of `IO.read`.

### Expected behavior

Although it might be argued this behavior is not inherently a bug, it was very unexpected to me. I would expect either:
1. An exception when the device passed to `IO.read(dev, :line)` has binary encoding, since reading a line of binary data is a nonsensical operation.
2. It should default to `utf8` instead of `latin1`, since this is the behavior of the rest of the Elixir standard library.
3. Failing the two options above, defaulting to `latin1` should be documented.

Any thoughts?

**Comment by josevalim** [comment]
Unfortunately there isn't much you can do here. IO.read already defaults to utf8,
but it needs to match the device encoding. Otherwise, it will convert it. This is
documented in the `File.open/1` function:

> In order to write and read files, one must use the functions in the IO module.
> By default, a file is opened in :binary mode, which requires the functions
> IO.binread/2 and IO.binwrite/2 to interact with the file. A developer may pass
> :utf8 as an option when opening the file and then all other functions from IO
> are available, since they work directly with Unicode data.

In other words, we took option 3. :) If you feel like we could document in other
places, PRs are welcome!

There is no operation in Erlang which is "ready in whatever encoding the file
is", so you always need to match the IO function with the file mode.
