### ISSUE TITLE
`not in` misbehaves with [true] list when in guards

### ISSUE THREAD

**Issue by ityonemo** [elixir-lang/elixir#11088]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

Erlang/OTP 24 [erts-12.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.0 (compiled with Erlang/OTP 24)

Also tested down to Elixir 1.11-23

* Operating system: 

Linux elion 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 x86_64 x86_64 GNU/Linux

### Current behavior

`not in` guard qualifier does not work with the list [true].  Also does not work if it's explicit (`not(var in [true])`)  No issues with `false`, or if true is part of a longer list.  It's also totally fine in the not-guard context.

```
defmodule M do
  def f(x) when x not in [true], do: :ok
  def f(x), do: :error
end

iex> M.f(true)
:error
iex> M.f(:foo)
:error
```

### Expected behavior
```
iex> M.f(true)
:error
iex> M.f(:foo)
:ok
```

**Comment by josevalim** [comment]
Reported upstream, thank you: https://github.com/erlang/otp/issues/5007
