### ISSUE TITLE
Time.convert cannot return {:error, _} but docs and spec says it can

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#11092]
The Time.convert/2 function [documentation](https://github.com/elixir-lang/elixir/blob/3d437bd03424be8e8c52ed6d29409b1db3911bf0/lib/elixir/lib/calendar/time.ex#L561) says it can return an error, but currently there is no way this can happen, it will always return `{:ok, _}` (or maybe it may crash in one of the calendar modules). In addition to that, there is a Time.convert! function that [says it will raise ArgumentError](https://github.com/elixir-lang/elixir/blob/3d437bd03424be8e8c52ed6d29409b1db3911bf0/lib/elixir/lib/calendar/time.ex#L617), but I think there's no way this would happen.

Having the interface as is probably makes sense for similarity with other APIs, but I think docs and spec are confusing. Or maybe this is a mistake?

**Comment by josevalim** [comment]
This is intentional. There is nothing at the moment that would cause it to return `{:error, _}` but it may change in the future and we want users to plan accordingly. :) Thanks!
