### ISSUE TITLE
IEx should respond to control-l (as in L)

### ISSUE THREAD

**Issue by LandonSchropp** [elixir-lang/elixir#11109]
### Environment

* Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit] [dtrace]
* Elixir 1.12.2 (compiled with Erlang/OTP 24)
* macOS 11.4

### Current behavior

Many coding REPLs respond to the control-l command. This company typically clears the screen, while allowing you to scroll up for the shell history. For example, you can use control-l in irb, node, python, bash, zsh, and other shells, but not in IEx.

### Expected behavior

I would expect IEx to implement the control-l shortcut, just like it implements other standard shell shortcuts such as control-w, control-u, control-a and control-e.

**Comment by wojtekmach** [comment]
IEx uses the Erlang shell under the hood so any features like that need to happen there. FWIW on macOS cmd+k does exactly this.

**Comment by josevalim** [comment]
As @wojtekmach explained, this feature would have to be submitted to Erlang first, but given there is already similar functionality under cmd+k (which also works in bash), I am not sure if they would add another shortcut, but it is a question for them to answer. :) Thanks!

**Comment by LandonSchropp** [comment]
Thanks! I'll submit it to them.

**Comment by LandonSchropp** [comment]
@wojtekmach The command-k shortcut isn't quite the same thing. AFAIK, control-l is part of the shell, while command-k is part of the terminal. If you're using something like tmux, command-k doesn't work.
