### ISSUE TITLE
`?` include in url returned by URI.to_string when `:query` is empty

### ISSUE THREAD

**Issue by thiamsantos** [elixir-lang/elixir#11100]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.1 (compiled with Erlang/OTP 24)
```
* Operating system: Linux mint

### Current behavior

When the `:query` field in a `URI` struct is an empty string, a `?` is include in the final url even though we don't actually have a query string.

```elixir
assert URI.parse("https://elixir-lang.org") |> Map.put(:query, "") |> URI.to_string() == "https://elixir-lang.org?"
```

We come up with this behaviour while using `URI.encode_query` to build the query params of the url.

```elixir
base_url
|> URI.parse()
|> Map.put(:path, path)
|> Map.put(:query, URI.encode_query(query_params))
|> URI.to_string()
```

### Expected behavior

I would expect for the `?` to be only included when the query has a real value.

```elixir
assert URI.parse("https://elixir-lang.org") |> Map.put(:query, "") |> URI.to_string() == "https://elixir-lang.org"
```

**Comment by josevalim** [comment]
The current behaviour is correct. After all, we need to distingish between "https://elixir-lang.org/?" and "https://elixir-lang.org/". So nil is not the same as an empty string.

**Comment by thiamsantos** [comment]
Thanks for the quick response :)
