### ISSUE TITLE
Logger drops gen_statem crash reports

### ISSUE THREAD

**Issue by dmorneau** [elixir-lang/elixir#11115]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.2 on OTP-24.0.3
* Operating system: macOS

### Current behavior

It seems at some point the Elixir logger stopped translating gen_statem crash reports. Someone mentioned the same problem here: https://elixirforum.com/t/why-does-logger-translator-ignore-gen-statem-reports/37418

Due to this gen_statem crashes don't show up in application logs.

### Expected behavior

I think it would make sense to support these reports, since they're standard OTP components, and they seemed to be supported at some point in the past (https://github.com/elixir-lang/elixir/pull/4834). This also affects Sentry integration, since it's implemented as a Logger backend ([logger_backend.ex](https://github.com/getsentry/sentry-elixir/blob/master/lib/sentry/logger_backend.ex)).

**Comment by josevalim** [comment]
My suggestion is to ask Sentry to log all error messages - as those reports are originated as error messages and there are other error messages, outside of `gen_statem` reports, that you likely want to see in a tool such as Sentry.
