### ISSUE TITLE
Shell scripts unintentionally continue despite `set -e`

### ISSUE THREAD

**Issue by nh2** [elixir-lang/elixir#11114]
The code in

https://github.com/elixir-lang/elixir/blob/799b4ceb8b674da91ff5b51699450aa295fb720b/lib/mix/lib/mix/tasks/release.init.ex#L85-L100

and onward does not have the effect that is likely intended.

`set -e` is used to make the script exit early on failure.

But e.g. lines like

```sh
export RELEASE_COOKIE="${RELEASE_COOKIE:-"$(cat "$RELEASE_ROOT/releases/COOKIE")"}"
```

will on error (e.g. if the `COOKIE` file does not exist) print a message to stderr and then **happily continue with `RELEASE_COOKIE` being set to the empty string**.

Shell is full of surprises. This code would be OK [if it didn't use `export`](https://unix.stackexchange.com/questions/426943/bash-export-ignores-set-ex). This is one of [lots of exceptions](http://mywiki.wooledge.org/BashFAQ/105) that nobody can remember.

[`shellcheck`](https://www.shellcheck.net/) would also have immediately pointed out this error (but not many others).

---

PS: I have not met one person on the planet who really understands POSIX shell. It should be avoided.

**Comment by nh2** [comment]
@josevalim Thanks for the extra `COOKIE` file check improvement, but that doesn't really address this issue:

The _entire_ script is wrong and does not handle subshell exit codes correctly; not just that one line I gave as an example

Even with your improvement, it will continue to run despite fatal errors.

And `shellcheck` still points that fact out.

It is all the `export`s that need to be fixed, as indicated by the [StackOverflow link](https://unix.stackexchange.com/questions/426943/bash-export-ignores-set-ex) I psoted in the issue description.

**Comment by josevalim** [comment]
Hi @nh2, I understood the case. :) I have revised the exports individually and I could not find another one that could fail silently. Unless you propose for us to fully migrate to the style in SO to avoid said pitfalls _in the future_?

**Comment by nh2** [comment]
@josevalim Yes, I propose to migrate from

```sh
export X=$(...)
```

to the approach recommended in that SO and by `shellcheck`:

```sh
X=$(...)
export X
```

so that silent failure cannot creep in in general.

For example, if somebody renamed the file in

```
export RELEASE_VSN="${RELEASE_VSN:-"$(cut -d' ' -f2 "$RELEASE_ROOT/releases/start_erl.data")"}" 
```

I believe that would also turn into a "silent" `No such file or directory` instead of bailing out loudly).

**Comment by nh2** [comment]
@josevalim Thanks!
