### ISSUE TITLE
Breaking changes in Range on 1.12

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#11110]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.x

### Current behavior

In elixirLS we distirubute precompiled modules. We compile on elixir versions older than 1.12. We have a piece of code that does
```
String.split("some", 0..-2)
```
Executing that code on elixir 1.12 it crashes with

```
** (FunctionClauseError) no function clause matching in String.slice/2
        (elixir 1.12.2) lib/string.ex:2086: String.slice("String.", %Inspect.Error{message: "got FunctionClauseError with message \"no function clause matching in Inspect.Range.inspect/2\" while inspecting %{__struct__: Range, first: 0, last: -2}"})
```
Reported in https://github.com/elixir-lsp/elixir-ls/issues/571

There are two problems. First is `String.slice` and second is `Inspect` implementation for `Range`. Both no longer accept accepts Ranges with no `step`. I'm afraid there are more such cases.

### Expected behavior

Actually I don't know what is expected here.

I know that implicitly decreasing ranges are soft deprecated but there is no trivial way make this code backwards compatible.

From reading https://hexdocs.pm/elixir/1.12/compatibility-and-deprecations.html it's not clear wether a module compiled with version x will work against a standard library from version x+1. There is no mention of ABI compatibility. Should a struct received over the network from an erlang cluster node running some older elixir version cause a crash in standard library? I'm not sure about `String.slice` and others but at least I would expect `Inspect` to be able to handle any map.

**Comment by ericmj** [comment]
> From reading https://hexdocs.pm/elixir/1.12/compatibility-and-deprecations.html it's not clear wether a module compiled with version x will work against a standard library from version x+1. There is no mention of ABI compatibility. Should a struct received over the network from an erlang cluster node running some older elixir version cause a crash in standard library? I'm not sure about String.slice and others but at least I would expect Inspect to be able to handle any map.

The rule (unsure if it is documented anywhere) is that only modules precompiled against the same Elixir minor version that you are running are guaranteed to work. If you distribute precompiled code you need to precompile against all Elixir minor versions that you support.

**Comment by josevalim** [comment]
Eric is correct when it comes to code compilation and macros. But here we
are talking about data and I think we should support data created in
previous versions.

**Comment by josevalim** [comment]
I am pushing a fix soon but, given you likely want to support v1.12.0-2, you may need to rewrite this using another operation. If you are removing two known characters, consider using `replace_trailing` instead.

**Comment by lukaszsamson** [comment]
> I am pushing a fix soon but, given you likely want to support v1.12.0-2, you may need to rewrite this using another operation. If you are removing two known characters, consider using replace_trailing instead.

@josevalim Thanks. In that particular case replace trailing will do but unfortunately there are many other usages.

> Eric is correct when it comes to code compilation and macros. But here we
are talking about data and I think we should support data created in
previous versions.

Whatever the final decision  will be, this needs to be documented https://hexdocs.pm/elixir/1.12/compatibility-and-deprecations.html
