### ISSUE TITLE
Unclear error message when using a variable in a bitstring: `<<a>>`

### ISSUE THREAD

**Issue by azizk** [elixir-lang/elixir#11123]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.1 (compiled with Erlang/OTP 24)
* Operating system: Linux

### Current behavior

```elixir
iex(1)> a = "a"
iex(2)> <<a>>
** (ArgumentError) argument error while evaluating iex at line 2
```
The following expressions work however:
```elixir
iex(1)> <<"a">>
"a"
iex(2)> a = "a"
iex(3)> << a <> "" >>
"a"
iex(4)> << a::binary >>
"a"
```

### Expected behavior

I'd expect a more specific error message. I'm not sure, but maybe there shouldn't even be an error. When such an expression is inside more complex code you don't have a clue where the issue is stemming from.

**Comment by josevalim** [comment]
It is an error because the default is for them to be treated as integers. Unfortunately there isn’t much we can do here though, since the error comes from the runtime. I have opened up an issue on OTP a couple weeks ago and we may have better error messages once it is tackled. Thanks!

**Comment by josevalim** [comment]
Also note compiled code may have slightly better error messages, compared to evaluated ones.

**Comment by azizk** [comment]
You're right, I only checked it in the shell. But I just tried it in some compiled project and it gives the same error including the stacktrace, e.g.:

```
== Compilation error in file xyz.ex ==
** (ArgumentError) argument error
    (elixir ...) lib/path/file.ex:123: XYZ.func/1
    ...
```

Okay, so it's an Erlang issue. Thanks for the efforts to get better error messages! :)
