### ISSUE TITLE
Recognize `[]:`, `:[]`, `^^:` and `:^^` as atoms

### ISSUE THREAD

**Issue by azizk** [elixir-lang/elixir#11136]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.12.1
* Operating system: Linux

### Current behavior

Compiler gives a syntax error for `[]:`, `:[]`, `^^:` and `:^^`.

### Expected behavior

Since I saw a commit where you made `.:` work, I'd like to ask you if you could support the mentioned atoms as well. If not, that's fine. I just want to know for the Sublime Text Elixir package I maintain.

**Comment by azizk** [comment]
Oh, I think `^^` isn't even an operator. So never mind about that one.

**Comment by josevalim** [comment]
We don't implement `:[]` because it doesn't appear as node in the AST. `:.` does and therefore `.:` should work too.
