### ISSUE TITLE
Introduce Code.Fragment.cursor_to_quoted

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11147]
The idea of `cursor_to_quoted` is to receive a code fragment and convert it to a quoted expression with a remote call as flag.

For example:

```elixir
iex> Code.Fragment.cursor_to_quoted("1 + ", Flag, [function: :cursor])
{:+, [], [1, {{:., [], [Elixir.Flag, :cursor]}, [], []}]}
```

Now, if you have a `Flag.cursor/0` macro, you will be able to expand said code and collect the environment information. Or alternatively traverse the AST and see the position of the cursor.

/cc @axelson @lukaszsamson @msaraiva

**Comment by lukaszsamson** [comment]
Isn't it achievable today with simply inserting `Flag.cursor()` and then calling `Code.string_to_quoted`?

**Comment by josevalim** [comment]
The cursor one will, by definition, receive incomplete code. Think this example:

```elixir
defmodule Foo do
  def bar do
    1 +
```

Also, the cursor has to handle cases like the one below. For example, adding Flag.cursor() works here:


```elixir
defmodule Foo do
  def bar do
    foo(
```

But not here:

```elixir
defmodule Foo do
  def bar do
    foo(first_argum
```

In the latter, we will replace `first_argum` by `Flag.cursor()`.

**Comment by msaraiva** [comment]
@josevalim so `cursor_to_quoted` will try it's best to have `Flag.cursor` in a valid position and automatically close the missing pieces? Like the result of the last example would be the quoted form of:

```elixir
defmodule Foo do
  def bar do
    foo(Flag.cursor())
  end
end
```

**Comment by josevalim** [comment]
@msaraiva correct, that's the idea. My understanding is that this functionality is used by Elixirsense. Correct?

**Comment by msaraiva** [comment]
Yeah, we do some hacking trying to make the code parsable so we can traverse it. This feature could replace that for sure. It would be much cleaner and, assuming it will be able to provide a valid AST most of the time, it will be much more reliable.

**Comment by lukaszsamson** [comment]
@josevalim do you plan to make it work (as a best effort obviously) in cases when code has partially closed statements?
I mean e.g.
```
defmodule Foo do
  def bar do
    foo(
  end
end
```
or

```
defmodule Foo do
  def bar do
    %{
      abc: foo(
    } |> some()
  end
end
```
or
```
defmodule Foo do
  def bar, do: [foo(]
end
```

**Comment by josevalim** [comment]
Yes, it works by definition only on partially closed statements because you should only give the data to it until the cursor position.

**Comment by lukaszsamson** [comment]
> My understanding is that this functionality is used by Elixirsense. Correct?

We use a few approaches in elixir_sense:
1. `Code.string_to_quoted` and try to fix source basing on parser error messages until it parses (or give up)
2. Using elixir tokenizer to get a few interesting tokens (IIRC to get `Module.function` subject)
3. Regex (e.g. to find not necessarily closed `alias A.{B, C`)
4. Copied code from `Code.cursor_context` (in completions to make it work with elixir < 1.12)

**Comment by josevalim** [comment]
Right, in this case, it would replace your code for 1.

I don't know yet how to elegantly solve 2. Using the tokenizer will always fail for other macros that define modules and functions. The only correct solution I came up with is to get the AST from step 1 and then expand it recursively.

For 3, this is something we should support in cursor_context (so we tell you that the context there is an alias). In fact, I am sure cursor_context is missing many relevant contexts. For example, I am not sure if you want a `struct` context after `%` (tricky because it can be var or alias or even a macro call). Or if we want a sigil context and so on. So feedback on missing completions are always welcome.

**Comment by lukaszsamson** [comment]
> it would replace your code for 1

Looking forward to it. One thing that is particularly difficult with approach 1 is determining module vs function context from AST only when source has been "fixed" in cases like.
```
defmodule Foo do
  def bar, do: 
end
```

> For 3, this is something we should support in cursor_context

That would be awesome. BTW I'd love to see typespec context.

> For example, I am not sure if you want a struct context after % (tricky because it can be var or alias or even a macro call)

Regarding structs we use another hacky approach I forgot - text walking with `String.next_grapheme` on reversed string.
