### ISSUE TITLE
`elixir --version` from command line is slow

### ISSUE THREAD

**Issue by atavistock** [elixir-lang/elixir#11146]
Because I use different languages for different clients, I've been showing my current environment in the command prompt.   Elixir is one of the few languages which takes longer than 100ms to respond with a version number, in fact it typically takes nearly 500ms to respond.  I recognize that this is likely due to having to start the VM, then ask it the version, but this is slow compared to other VM based languages and probably should be "fixed" if it can be.

### Environment

Doesn't seem OS or version dependent, but in case it is:

* Elixir 1.12.2
* Erlang/OTP 24 [erts-12.0.3] 
* Mac OS/X 11.5

### Current behavior

```
> command time elixir --version
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
        0.46 real         0.44 user         0.11 sys

```

### Expected behavior

I would expect to get the version number in less than 100ms.

Some examples from other languages

```
> command time erl -version
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 12.0.3
        0.04 real         0.01 user         0.01 sys
```

```
> command time ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
        0.02 real         0.00 user         0.00 sys
```

```
> command time node --version
v12.16.3
        0.01 real         0.00 user         0.00 sys
```

```
> command time java --version
java 10.0.2 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
        0.14 real         0.10 user         0.04 sys
```

**Comment by josevalim** [comment]
I can think of two options:

1. Try to improve things a bit but at best by 100ms
2. Introduce a `elixir --short-version` which emits the hardcoded version directly on the boot/bash script

Thoughts?

**Comment by atavistock** [comment]
A `--short-version` probably wouldn't help all that much because existing tools that might look for elixirs version would still call `--version`.  Also I think keeping the same banner would be ideal.  I'm okay with living with the problem (I have until now) but leaving it as a "nice to fix at some point".  

One thought, it seem the version of OTP that elixir is compiled against is important, if its possible to drop an `${ELIXIR_ROOT}/OTP_VERSION` file when its compiled then it just becomes a pretty simple concatenation 

`
ELIXIR_VERSION=$(cat ../VERSION)
OTP_VERSION=$(cat ../OTP_VERSION)
echo "Elixir ${ELIXIR_VERSION} (compiled with Erlang/OTP ${OTP_VERSION})"
`

.. but I'm not sure if thats viable

**Comment by josevalim** [comment]
"version of OTP that elixir is compiled against is important" not really, so we don't need to worry about that.

The `--short-version` would provide a path forward, at least, so tools could be updated in the long term? Otherwise it is likely the issue will exist for a really long time. I would say all other tools seem to be aborting very early in the process, and it is hard for us to do that with the current information we print.

**Comment by atavistock** [comment]
Well then `--short-version` is a good path forward.

**Comment by josevalim** [comment]
Closing in favor of PR.
