### ISSUE TITLE
Allow complete mapping of Elixir source

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11145]
There is a wealthy of information we want to be able to track per compiled module:

  * imports and aliases (supported by tracers)
  * local and remote invocations (supported by tracers)
  * variables
  * struct definition
  * module attributes
  * local functions 

Compilation tracers make it possible to only track the first two items. Our goal with this task is to make it possible to track the remaining ones via tracers. In particular, we will:

  * [x] Introduce a `{:on_module, env, bytecode}` callback to compilation tracers with every module definition. In this callback, you can call `Module.get_attribute(env.module, :struct)` to get a possible struct definition. You can also call `Module.definitions_in/1` and `Module.get_definition/2` to get the expanded source code and extract all variables

  * [x] Introduce a `nillify_clauses` option to `Module.get_definition/2` so we can get metadata for a given clause without all of its code

  * [x] Introduce a `Module.attributes_in(module)` to get the name of all module attributes and add a official recommendation that all private (non-user facing) module attributes should start with underscore

  * [x] Add `@__records__` reflection

  * [x] Add `Module.overridables_in` reflection

/cc @lukaszsamson @axelson @msaraiva

**Comment by v0idpwn** [comment]
Possible bikeshedding: I think `list_attributes` is a better name than `attributes_in` because it is more coherent with the existing `get_attribute`, `has_attribute`, `put_attribute`, etc.

**Comment by josevalim** [comment]
We already have `definitions_in`, so `attributes_in` is meant to mirror that.

**Comment by lukaszsamson** [comment]
I would also like to see types, specs, callbacks, behaviours, overridable functions. Currently it's only possible to get (most of) those via runtime introspection or AST.

**Comment by josevalim** [comment]
@lukaszsamson Good point. How do you get the overridable ones and how do you use it for? I will add a new tracer callback but since it will be called at the end of the module, all of the functions that were overridable will have been "written down". What information do you want? All functions that were overridable at some point? Or all of the functions that were not overridden?

**Comment by lukaszsamson** [comment]
elixir_sense uses a hacky way of expanding `use X` macro and matching on `Module.make_overridable` calls in AST
https://github.com/elixir-lsp/elixir_sense/blob/7fb31589e9dfdb91c6498e1169a13a0fe056d15b/lib/elixir_sense/core/ast.ex#L258

We use it to provide a list of suggestions of functions/macros that can be overridden in a client module. I can also think of marking somehow overridden functions (e.g. when showing hover docs or in completion lists) though we don't do that ATM.
We also provide navigation to `super` inside overridden functions (the current approach does not work for macros due to self referencing macro expansion)

**Comment by lukaszsamson** [comment]
I would also like to see better support for records. Currently it's only possible to match on `Kernel.defrecord` in AST or query `__info__(:macros)` but that does not give much info. AFAIK there is no way to get a list of record types defined in a module.

**Comment by josevalim** [comment]
Records is easy because they are just macros, so all we need is to add a `@__records__` attribute for book-keeping.

**Comment by josevalim** [comment]
@lukaszsamson there is one particular bit I will need your help with which is to open up issues in libraries that are defining private module attributes and tell them they should be prefixed with `_` (if they don't do so yet). We don't need to do this upfront, but rather as you use Elixirsense and find out the module attribute list is too long. I will be pushing a warning to our docs soon.

**Comment by josevalim** [comment]
All in.
