### ISSUE TITLE
Macro.Env.t() is too strict and causes dialyzer warnings that propagate

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#11155]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): elixir master at `106a99f13432b8187293360f2bcad482f95e8ac3`
```
$ elixir --version
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:6:6] [ds:6:6:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

### Current behavior

Fixture:
```
defmodule Dialyzer.MacroEnvStruct do
  def fun() do
    Macro.Env.location(__ENV__)
  end
end
```

Test in `dialyzer_test.exs`:
```
  test "no warning on Macro.Env struct usage", context do
    copy_beam!(context, Dialyzer.MacroEnvStruct)
    assert_dialyze_no_warnings!(context)
  end
```

Result:
```
  1) test no warning on Macro.Env struct usage (Kernel.DialyzerTest)
     test/elixir/kernel/dialyzer_test.exs:155
     macro_env_usage.ex:2: Function 'fun'/0 has no local return
     
     
     code: assert_dialyze_no_warnings!(context)
     stacktrace:
       test/elixir/kernel/dialyzer_test.exs:157: (test)
```

### Expected behavior

No dialyzer warning, or at least one that does not propagate up the call stack potentially through the whole program

### Notes

This happens because the `vars` field was removed from type (so the type only covers maps that don't have that field) but the struct definition still contains that field so it's being included when creating that struct.

I understand deprecating this field is documentation/information that the Elixir team wants to provide, and the Elixir team may have its own opinions as to how the types in the language should work, similarily to [the MapSet.t() being opaque](https://github.com/elixir-lang/elixir/pull/9995#issuecomment-620891390) - but my opinion is that if the Elixir team wants to communicate through the `@type` and `@spec` attributes something that does not align with what meaning those attributes already have in the Erlang ecosystem through the Dialyzer tooling, maybe there need to be new ways to express this information to have it present (or absent, like with this struct field) in Elixir documentation but erased (or recovered) when compiled to beams.

**Comment by josevalim** [comment]
@michallepicki this was my bad. The field was private but we held removing it because others could be using it and I decided to do so for 1.13 but apparently I did not yank it from all places. I will fix it.

**Comment by michallepicki** [comment]
I thought it was left in the struct on purpose. If it's good to remove from there, then it should fix it!

**Comment by michallepicki** [comment]
I tested the fix and dialyzer still shows a warning, I think because of vars presence [here](https://github.com/elixir-lang/elixir/blob/5728a4b7c14c04730ff929469c8ddf00a82c31be/lib/elixir/src/elixir_env.erl#L26). After removing that one, there is one test failing:
```
Randomized with seed 61070
==> iex (ex_unit)

  1) test breakpoints prints table with breaks (IEx.HelpersTest)
     test/iex/helpers_test.exs:105
     ** (KeyError) key :vars not found
     code: assert capture_io(fn -> URI.decode_query("foo=bar", %{}) end) != ""
     stacktrace:
       (iex 1.13.0-dev) lib/iex/pry.ex:85: IEx.Pry.pry/2
       (elixir 1.13.0-dev) URI.decode_query/2
       (ex_unit 1.13.0-dev) lib/ex_unit/capture_io.ex:272: ExUnit.CaptureIO.do_capture_gl/2
       (ex_unit 1.13.0-dev) lib/ex_unit/capture_io.ex:230: ExUnit.CaptureIO.do_with_io/3
       (ex_unit 1.13.0-dev) lib/ex_unit/capture_io.ex:106: ExUnit.CaptureIO.capture_io/1
       test/iex/helpers_test.exs:116: (test)
``` 

[lib/iex/pry.ex:85](https://github.com/elixir-lang/elixir/blob/master/lib/iex/lib/iex/pry.ex#L85)

Possibly that should be setting `current_vars`
