### ISSUE TITLE
Should calling accessed map values as functions be a compiler warning?

### ISSUE THREAD

**Issue by LandonSchropp** [elixir-lang/elixir#11160]
### Environment

* Erlang/OTP 24 [erts-12.0.3]
* Elixir 1.12.2
* macOS 11.4

### Current behavior

This compiles and runs without warnings:

```
map = %{ hello: "hello" }
map.hello
map.hello()
```

### Expected behavior

I'm a bit surprised that the `map.hello()` isn't a compiler error or warning. Should it be?

**Comment by josevalim** [comment]
Please see #9510. We are tackling this in steps and deprecations are coming in. :)

**Comment by LandonSchropp** [comment]
Awesome, thanks!
