### ISSUE TITLE
Track compile-time config usage via compile_env

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11181]
When we added `compile_env`, its main goal was to detect outdated configuration in dependencies and in the current project. However, we can bring it further.

Today, every time you change a config file, it needs to recompile the whole project. However, once we start pushing towards `Application.compile_env`, we will actually know which files use a configuration (if at all) and only recompile the files when specific app-key-values change.

However, there are still a handful of big issues. Because Elixir compilation is just executing code, it may be hard to distinguish some scenarios. Let's see some examples.

## Reading at compile-time indirectly within the same app

In the future, doing this will emit a warning and be invalid:

```elixir
defmodule Bar do
  @foo_bar Application.get_env(:foo, :bar, :default)
```

Instead, you should do:

```elixir
defmodule Bar do
  @foo_bar Application.compile_env(:foo, :bar, :default)
```

This is good, because it helps us towards detecting these compile-time configuration. However, the following will work:

```elixir
defmodule Config do
  def config, do: Application.get_env(:foo, :bar, :default)
end
```

```elixir
defmodule Bar do
  @foo_bar Config.config()
```

Now we still have the compile time configuration, but because it was moved to a function, we lost it. This means that, if we no longer fully recompile the project whenever the config changes, the following code will be outdated/wrong.

One possible solution to this problem is to not populate the application environment for `:foo` until after it is compiled and we read all `compile_env` from elsewhere. If we do so, then trying to read any key for `:foo` at compilation runtime will fail, unless it goes through `compile_env`. This behaviour would be obviously be a breaking change, but we can make it opt-in (and the benefit is faster recompilation times).

## Reading at compile-time indirectly across apps

However, things get trickier once we consider how those values may apply across apps. For example, imagine our app `:foo` has a dependency on Phoenix. Phoenix will have its own **runtime** configuration but, in order to compile our application `:foo`, Phoenix may read its **runtime** configuration which will affect how it compiles `:foo` (which makes it a compile time configuration from `:foo`'s perspective). An example where this occurs today is in Phoenix template engines, which changes how our application views are compiled.

We could say that Phoenix maybe should parameterize those values instead of using the app environment, but the fact is that any project could do this and, because from Phoenix perspective it is doing all of this work at runtime, it is not doing anything wrong! This means that our options are either:

1. Ignore this scenario and accept the code may get out of date

2. Recompile the whole project whenever the configuration of any dependency changes and, if this is the case, is there even a point in adding this feature?

I'd say `1` is not an acceptable option so is there a point of tracking only the config changes of the current app? In practice, which configs do you change the most? The one of external apps or of your own app?

/cc @sasa1977 @wojtekmach @marcandre

**Comment by ericmj** [comment]
> One possible solution to this problem is to not populate the application environment for :foo until after it is compiled and we read all compile_env from elsewhere. If we do so, then trying to read any key for :foo at compilation runtime will fail, unless it goes through compile_env. This behaviour would be obviously be a breaking change, but we can make it opt-in (and the benefit is faster recompilation times).

This sounds reasonable.

> We could say that Phoenix maybe should parameterize those values instead of using the app environment, but the fact is that any project could do this and, because from Phoenix perspective it is doing all of this work at runtime, it is not doing anything wrong! This means that our options are either:

I would say option 1 and the template engine config should move into the application env of `:foo` or possibly add a `template()` function in `MyAppWeb`.

**Comment by marcandre** [comment]
> trying to read any key for `:foo` at compilation runtime will fail, unless it goes through `compile_env`

👍

> from Phoenix perspective it is doing all of this work at runtime, it is not doing anything wrong

I might be completely off base, but in this case, Phoenix is compiling things and it doesn't seem unreasonable to me to put on it the burden of maintaining those dependencies. Could Phoenix maintain a module (say in `lib/.app_interdependencies/phoenix.ex`, maybe via some public API) and create a compile-time dependency to that module for the files it compiles? If the config changes, Phoenix could force the rebuilding by modifying that file, and only the relevant files would be recompiled.

**Comment by josevalim** [comment]
Even if we could say that Phoenix is responsible for this, the problem is a bit more generalized. Let me give a silly example which I think shows the point.

Imagine someone creates a word splitter library:

```elixir
defmodule WordSplitter do
  def split(string) do
    String.split(string, Application.get_env(:word_splitter, :separator, " "))
  end
end
```

By all measurements this is a horrible package but bear with me. Now imagine someone is writing a library that meta programs some stuff based on words:

```elixir
defmodule MyLib do
  words = HTTPClient.get("/dictionary") |> WordSplitter.split()
  for word <- words do
    def known_word?(unquote(word)), do: true
  end
  def known_word?(_), do: false
end
```

The issue with the code above is that WordSplitter is a library, from its point of view it is only used at runtime, but someone is using it at compile time which makes its configuration compile time specific.

There is another option in all of this which is to introduce an explicit compile_env configuration in `import Config`:

    compile_env :my_app, Endpoint, ... 

But I don't like that because the work of figuring out what is compile and what is not becomes a user responsibility.

**Comment by marcandre** [comment]
I'm not sure if dependencies across apps are handled differently, but from my naive perspective, `WordSplitter` is introducing a runtime dependency on "config:word_splitter/separator" (not an actual file, but plays that role), and `MyLib` has a compile time dependency on `WordSplitter`, so any change to that config, while not requiring a recompilation of `WordSplitter`, would trigger recompilation of transient dependencies like `MyLib`.
Calling `Application.compile_env` is the same, except the dependency is compile-time.

**Comment by sasa1977** [comment]
If I get this right, the goal is to more reliably find compile-time usages of `get_env`, which are still introduced by invoking a function at compile-time/ The ultimate goal is to reduce the amount of recompiled modules when a config file changes, right?

If that's the case, could this be addressed through the compilation tracer mechanism? The idea is to somehow mark every function that invokes `Application.get_env` & co as a runtime-only function, and then emitting a warning when such function is invoked at compile time. A runtime property of a function would be transitive (a function invoking a runtime function is also a runtime function). 

I don't expect this would be an easy change (especially considering that this has to work across deps), but to me the more important question is could this lead to some unacceptable false positives/negatives? For example, this can be easily circumvented with `apply`, but I'm not too much worried about that, because `apply` is in a sense a backdoor around many guarantees (and perhaps it's worth thinking about warning on the usage of `apply` at compile time?). Can you think of other similar scenarios, especially the ones which would cause some module not to be recompiled when it should be?

**Comment by josevalim** [comment]
Right. We could make the compiler smarter to work across dependencies and track application `get_env` too but it doesn't matter how smart we get, there will always be false positives. For example, what if we write the example above to:

```elixir
defmodule WordSplitter do
  def split(string, key \\ :separator) do
    String.split(string, Application.get_env(:word_splitter, key, " "))
  end
end
```

Now we don't know the key, and anyone could parameterized on the both app name and key like that. Then we could say, what if we mark any module that reads the `Application` as stale? But you can still do this:

```elixir
defmodule WordSplitter do
  def split(string, app_reader \\ Application) do
    String.split(string, app_reader.get_env(:word_splitter, :separator, " "))
  end
end
```

However, I think the following should work: if an application changes its configuration, then we only recompile the files that depends on modules of said application as well as  any module of applications that depend on said application. This will be fine as long as an application only read its own application environment, which is a semantic that I will be much happier to enforce, and it should still considerably reduce the blast radius.

**Comment by sasa1977** [comment]
Yeah, given the amount of freedom we have at compile time, I'm not sure if per-key (or even per-app) tracking can be achieved. However, I think that a question "Should this module be recompiled if anything in config changes?" could be answered with "reasonable" confidence, and almost no false negatives (though with some false positives, but that should be fine), and that it would in most cases significantly reduce the amount of recompiled modules.

> However, I think the following should work: if an application changes its configuration, then we only recompile the files that depends on modules of said application as well as any module of applications that depend on said application. This will be fine as long as an application only read its own application environment, which is a semantic that I will be much happier to enforce, and it should still considerably reduce the blast radius.

Not really sure I follow this. The config is always provided by the root app, no? If so, what does "changes it config" and "reads its own app env" mean?

**Comment by josevalim** [comment]
Imagine the configuration for the `:phoenix` app changed. This most likely will change how the `:phoenix` application compiles my code. But I know all of my code that calls the `:phoenix` application, because I know all modules in the `:phoenix` application, and I know which one of my modules are calling them. So basically, if the config for the `:phoenix` application changes, then I consider all of its modules (and all of the modules of dependencies that depend on `:phoenix`) to be changed.

**Comment by josevalim** [comment]
I have pushed the approach I explained above to this branch: https://github.com/elixir-lang/elixir/pull/11201

So it addresses all cases related to dependencies, which means we can simplify the scope of this discussion. I will open up a pruned discussion and share more updates soon.

**Comment by josevalim** [comment]
Closing this. New issues coming soon.
