### ISSUE TITLE
Regular expression String.replace corruption

### ISSUE THREAD

**Issue by jakesgordon** [elixir-lang/elixir#11205]
### Environment

This issue is reproducible with the `elixir:1.11.2` docker image
```
Erlang/OTP 23 [erts-11.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.11.2 (compiled with Erlang/OTP 23)
```

### Current behavior

When run with enough iterations a `String.replace` using a particular regex with matching can give unpredictable results. The following code **should** provide the exact same result every time:
```
iex(1)> "EmployeeEmailAddress" |> String.trim |> String.replace(~r/([a-z])([A-Z])/, "\\1_\\2")
"Employee_Email_Address"
```

**However**, when run in a loop with enough iterations (> 100,000) we start to see more than 1 unique result:
```
iex(2)> Enum.map(1..1_000_000, fn _ -> "EmployeeEmailAddress" |> String.trim |> String.replace(~r/([a-z])([A-Z])/, "\\1_\\2") end) |> Enum.uniq
["Employee_Email_Address", "EmployeeEmailAddress"]
```

This can be reproduced using the vanilla `elixir:1.11.2` docker container:
```
$ docker run -it elixir:1.11.2 elixir -e 'Enum.map(1..1_000_000, fn _ -> "EmployeeEmailAddress" |> String.trim |> String.replace(~r/([a-z])([A-Z])/, "\\1_\\2") end) |> Enum.uniq |> IO.inspect'
["Employee_Email_Address", "EmployeeEmailAddress", "Employee_EmailAddress"]
```
_(NOTE: there should be a single uniq result above, but there are 3 different ones!)_

### Expected behavior

I would expect to see only a single unique result no matter how many iterations
```
$ docker run -it elixir:1.11.2 elixir -e 'Enum.map(1..1_000_000, fn _ -> "EmployeeEmailAddress" |> String.trim |> String.replace(~r/([a-z])([A-Z])/, "\\1_\\2") end) |> Enum.uniq |> IO.inspect'
["Employee_Email_Address"]
```

### Notes

 * If we remove the `String.trim` from the example code then it works perfectly, so there is some interaction between the `String.trim` (which does a binary copy) and the `String.replace`
 * The regexp is very specific with 2 matches designed to turn a `CamelCase` formatted value to an `under_score` formatted value. We do not know if it's only a problem with this specific regex, or if it's a more widespread problem with any matching regex
 * Preliminary testing shows that this issue cannot be reproduced with the latest `elixir:1.12.2` docker image and so may be fixed in the latest releases... however we did see one occurrence of the problem with a local 1.12.2 install that did not have the jit enabled, so we're not 100% sure that it's resolved in 1.12.2/24

### Background

For background, this comes from research into an intermittent test failure we were having with our application using the `Inflex.underscore` library function in order to turn `CamelCase` formatted strings into `under_score` formatted strings. On rare occasions the underscores were missing or in innapropriate positions within the final binary. We extracted the `Inflex` code and simplified until we got it down to this simple use case.

We did chase some red herring clues that appeared to exacerbate the problem - we thought it might be an interaction with other concurrent ExUnit tests for a while, and we were also doing this conversion in the context of a `CSV.decode` ParallelStream loop, but ultimately we found that - with enough iterations - we were able to reproduce the problem in a clean elixir console with the code provided above.

**Comment by jakesgordon** [comment]
One comment I forgot to add... It's possible this may turn out to be an issue with the underlying erlang `:re` library, we could reproduce the same problem using `:re.run()` instead of `String.replace`

**Comment by josevalim** [comment]
Thanks @jakesgordon for the detailed report. This would most likely be an OTP issue but we would need to isolate it further. I will give it a try on 23 and let you know how it goes. If you do give it a try and succeed, let me know. :) for a starter, can you share the :re.run version?

**Comment by jakesgordon** [comment]
Here's a variation using `:re.run` instead of `String.replace`...

The output of a single (correct) execution looks like this...
```
$ docker run -it elixir:1.11.2 elixir -e '"EmployeeEmailAddress" |> String.trim |> :re.run("([a-z])([A-Z])") |> IO.inspect'
{:match, [{7, 2}, {7, 1}, {8, 1}]}
```

... but if we run it in a loop we see more than one unique result..
```
$ docker run -it elixir:1.11.2 elixir -e 'Enum.map(1..5_000_000, fn _ -> "EmployeeEmailAddress" |> String.trim |> :re.run("([a-z])([A-Z])") end) |> Enum.uniq |> IO.inspect'
[{:match, [{7, 2}, {7, 1}, {8, 1}]}, :nomatch]
```

frequently the additional result is a `:nomatch` but sometimes (more rare) it's just a slightly different match, e.g, here's one where I got 3 distinct results:
```
$ docker run -it elixir:1.11.2 elixir -e 'Enum.map(1..1_000_000, fn _ -> "EmployeeEmailAddress" |> String.trim |> :re.run("([a-z])([A-Z])") end) |> Enum.uniq |> IO.inspect'
[
  {:match, [{7, 2}, {7, 1}, {8, 1}]},
  :nomatch,
  {:match, [{16, 2}, {16, 1}, {17, 1}]}
]
```

**Comment by jakesgordon** [comment]
... and note again, if I remove the `String.trim` it all appears to work correctly every time
```
$ docker run -it elixir:1.11.2 elixir -e 'Enum.map(1..1_000_000, fn _ -> "EmployeeEmailAddress" |> :re.run("([a-z])([A-Z])") end) |> Enum.uniq |> IO.inspect'
[match: [{7, 2}, {7, 1}, {8, 1}]]
$ docker run -it elixir:1.11.2 elixir -e 'Enum.map(1..1_000_000, fn _ -> "EmployeeEmailAddress" |> :re.run("([a-z])([A-Z])") end) |> Enum.uniq |> IO.inspect'
[match: [{7, 2}, {7, 1}, {8, 1}]]
```

**Comment by jakesgordon** [comment]
[CORRECTION]. For the `re:run` variation to be equivalent to the `String.replace` version I probably need to explicitly include the `[:global]` option, but the result appears to be the same, given enough iterations I start to get multiple different results:
```
$ docker run -it elixir:1.11.2 elixir -e 'Enum.map(1..1_000_000, fn _ -> "EmployeeEmailAddress" |> String.trim |> :re.run("([a-z])([A-Z])", [:global]) end) |> Enum.uniq |> IO.inspect'
[
  {:match, [[{7, 2}, {7, 1}, {8, 1}], [{12, 2}, {12, 1}, {13, 1}]]},
  {:match, [[{7, 2}, {7, 1}, {8, 1}]]},
  :nomatch
]
```

Sometimes it gets both expected matches, sometimes it gets only one, sometimes it gets none (and on very very very rare occasions it gets a match in a completely incorrect location)

**Comment by josevalim** [comment]
Isolated and reported upstream here: https://github.com/erlang/otp/issues/5150

Thank you!

**Comment by jakesgordon** [comment]
Thank you!
