### ISSUE TITLE
Issues with mix deps.update

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#11208]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
elixir 1.12.2 and master
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
* Operating system: macOS

### Current behavior

On two separate projects we started getting errors with mix deps.update commands. Here is a small reproduction

1. clone https://github.com/lukaszsamson/elixir_deps_resolution_bug_repro
2. mix deps.get
3. mix deps.update --all
```
* Updating browser (https://github.com/lukaszsamson/elixir-browser.git - origin/dev)
Resolving Hex dependencies...
```
hangs with high cpu usage

I don't know if this is an issue with hex or mix not being able to resolve version constraints.
If I relax dependency on plug_cowboy to ~> 2.0 then mix deps.update --all will attempt to downgrade it to 2.3 for some reason.

### Expected behavior

Dependency resolution should finish or return an error if the server is not responding in timely manner

**Comment by josevalim** [comment]
This is a Hex issue which is already being tracked. A commit has recently been pushed to Hex to show an error message in those cases leading people what to do, see https://github.com/hexpm/hex/pull/900.
