### ISSUE TITLE
Syntax error with ->

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#11209]
### Environment

```
$ uname -a
Linux 5.13.11 #1-NixOS SMP Sun Aug 15 12:01:57 UTC 2021 x86_64 GNU/Linux

$ elixir --version
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

### Current behavior

See https://elixirforum.com/t/does-this-worth-an-issue/41897/4 for examples

The main problem here is that
```elixir
f(1 -> 2)
```
results in a syntax error

But something like
```elixir
(1 -> 2) |> f()
# or
f((1 -> 2))
```

Is a valid expression

### Expected behavior

```elixir
f(1 -> 2)
```

Does not result in syntax error

**Comment by josevalim** [comment]
This is intentional. In this case, the parentheses are delimiters of the ->. In the same way that `fn`/`end` and `do`/`end` are. Or in the same way `[` and `]` are delimiters around a list. So you do need to write `f((1 -> 2))`.  Note this is mostly used in typespecs.
