### ISSUE TITLE
mix format: Unnecessary change in unix shebang

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#11215]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.13.0-dev (a802acf) (compiled with Erlang/OTP 24)`

### Current behavior

```
$ echo '#!/usr/bin/env elixir' | mix format -
#! /usr/bin/env elixir
```

Please note the extra whitespace:

```
#! /usr/bin/env elixir
  ^
```

FWIW, this doesn't break anything. If this file is made executable, it is executed as usual.

### Expected behavior

```
$ echo '#!/usr/bin/env elixir' | mix format -
#!/usr/bin/env elixir
```

**Comment by josevalim** [comment]
This seems to have been intentional (there is a test) but I noticed that the Unix convention is no space, so we should definitely allow it. I will make it so we don't touch the comment after a `#!`.
