### ISSUE TITLE
delegate_to option in @doc seems to be ignored when working with @behaviour

### ISSUE THREAD

**Issue by Eiji7** [elixir-lang/elixir#11219]
### Environment

```elixir
$ elixir --version
Erlang/OTP 23 [erts-11.2.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.12.2 (compiled with Erlang/OTP 23)
```

```bash
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### Current behavior

Below code gives only `@behaviour` part of documentation and skips `@doc delegate_to`.

```elixir
defmodule Example do
  @callback sample() :: any

  def sample() do
    # any content
  end
end

defmodule Test do
  @behaviour Example

  defdelegate sample(), to: Example
end
```

However if you comment `@behaviour …` line you should see `delegate_to` missing documentation …

### Expected behavior

Both `@behaviour` and `delegate_to` should be shown in documentation.

Originally reported on [Elixir Forum](https://elixirforum.com/t/behaviour-callback-and-spec/20463/12?u=eiji)

**Comment by shahryarjb** [comment]
## More tests after generating:

### without `@behaviour`
![Screen Shot 1400-06-08 at 22 02 09](https://user-images.githubusercontent.com/8413604/131380436-3943de4a-b47a-4413-89ae-1700b2ad1b33.png)


### without `@behaviour` on iex
```elixir
                               def create(attrs)

delegate_to: MishkaDatabase.CRUD.crud_add/1
```

### with `@behaviour` on `iex`:

```elixir
iex(2)> h MishkaDatabase.Public.Setting.create
@callback create(record_input()) ::
            {:error, :add, error_tag(), repo_error()}
            | {:ok, :add, error_tag(), repo_data()}
```


with `@impl true` on `iex`:
```
iex(10)> h MishkaDatabase.Public.Setting.create
No documentation for MishkaDatabase.Public.Setting.create was found
```

thanks
