### ISSUE TITLE
Mix Test not executing tests of file.

### ISSUE THREAD

**Issue by tech0tron** [elixir-lang/elixir#11225]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.12.2. w/ Erlang/OTP 24
* Operating system: Windows 10 Home, Version 2004, OS build 19041.1110

### Current behavior

I am doing the Mix/OTP tutorial on Elixir's website. I created my project with mix and am trying to run a test on my module. The module's directory is in ~/Desktop/kv, which is also where the Powershell terminal is. The test code is in kv/test/kv_bucket_test.exs and looks like this:
```
defmodule KV.BucketTest do
  use ExUnit.Case, async: true

  test "store values by key" do
    {:ok, bucket} = KV.Bucket.start_link([])
    assert KV.Bucket.get(bucket, "milk") == nil

    KV.Bucket.put(bucket, "milk", 3)
    assert KV.Bucket.get(bucket, "milk") == 3
  end
end
```

KV.Bucket is defined in lib/bucket.ex and looks like this:
```
defmodule KV.Bucket do
  use Agent

  @doc """
  Starts a new bucket.
  """
  def start_link(_opts) do
    Agent.start_link(fn -> %{} end)
  end

  @doc """
  Gets a value from the `bucket` by `key`.
  """
  def get(bucket, key) do
    Agent.get(bucket, &Map.get(&1, key))
  end

  @doc """
  Puts the `value` for the given `key` in the `bucket`.
  """
  def put(bucket, key, value) do
    Agent.update(bucket, &Map.put(&1, key, value))
  end

end
```

Running mix test within ~/Desktop/kv on Powershell yields this:
```
Finished in 0.02 seconds (0.02s async, 0.00s sync)
1 test, 0 failures

Randomized with seed 179471
```

It does not do the tests in kv_bucket_test.exs.

**Comment by tech0tron** [comment]
![image](https://user-images.githubusercontent.com/76018881/132117224-4faca5d4-3db0-4ad9-afda-8b5e721b869a.png)

Here is the file directory in visual form.

**Comment by josevalim** [comment]
There is only one test file and the test suite says:

```
Finished in 0.02 seconds (0.02s async, 0.00s sync)
1 test, 0 failures

Randomized with seed 179471
```

So it did run 1 test. Isn't that what you are expecting? :)

**Comment by tech0tron** [comment]
I thought it would show me something like 'test "store values by key" -- succeeded', similar to how rust's testing suite does it; my apologies.

Big fan of your work!
