### ISSUE TITLE
Dead cycle when use alias by a wrong way

### ISSUE THREAD

**Issue by feng19** [elixir-lang/elixir#11229]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir (1.12.3) & Erlang/OTP (24.0)
* Operating system: MacOS

### Current behavior

```elixir
Code.eval_string("Post", [], [aliases: [{Post, Post}]])
```

Dead cycle on here:

```elixir
:elixir_aliases.lookup(Post, [{Post, Post}], nil)
```

### Expected behavior

Ignore wrong aliases and emit a warning.

**Comment by josevalim** [comment]
@feng19 thanks for the report!

You should strongly consider passing an env instead:

    alias Post, as: FooBar
    Code.eval_string("Post", [], __ENV__)

The aliases and direct manipulation options are already soft deprecated in master and they will be fully deprecated in future versions. :)
