### ISSUE TITLE
Some elixir tests fails with otp-24 in branch v1.11

### ISSUE THREAD

**Issue by xadhoom** [elixir-lang/elixir#11221]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): branch v1.11, v1.11.4 and otp 24.0.5
* Operating system: linux

### Current behavior

running `make test` in elixir sources leads to 7 failures in `Kernel.WarningTest` (mostly capture_log matches)

### Expected behavior

All tests should pass, since v1.11.4 is reported compatible with otp-24

Stumbled into this while packaging elixir in rpm, the rpm build phase runs `make tests` and this leads to build failure. Maybe they can be ignored ?

**Comment by josevalim** [comment]
I have backported a commit that addresses those but yeah, they are safe. Just some warning formatting.

**Comment by xadhoom** [comment]
Great!

A couple of other tests still fails in `Logger.TranslatorTest`, specifically `test/logger/translator_test.exs:869` and `test/logger/translator_test.exs:761`.

Seems that the translated supervisor reports are missing the expected `Restart`, `Shutdown` and `Type` fields.
