### ISSUE TITLE
Problem with structured logger truncation

### ISSUE THREAD

**Issue by rodrigues** [elixir-lang/elixir#11223]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): master with otp 24
* Operating system: macOS

### Current behavior

We're logging using a map as the log message. One of the values is a reasonably big string, but we don't want to truncate it, we need to log the full payload. Today the logger truncates it though to first `4096` characters 🤔

```elixir
Logger.info(%{msg: long_string})
# gets truncated: xxxxxxxxxx" <> ...]
```

I was looking into how to tweak that, and it seems to me that`truncate: :infinity` configuration only works if the message is a binary.

I'm not sure if there's currently a way to tweak that, couldn't find anything related to it.

I have an example in `.livemd` here:
https://gist.github.com/rodrigues/f09d9f3816cfec32f65a7f15715184e7

### Expected behavior

Be able to tweak the printable limit / depth of structured logs.

Thanks!

**Comment by josevalim** [comment]
There is a `translator_inspect_opts` that configures how Erlang reports get translated into strings but unfortunately it is not used for reports. I will push a fix soon.
