### ISSUE TITLE
Partial line test coverage and literal returns don't behave intuitively or consistent with most languages.

### ISSUE THREAD

**Issue by SophisticaSean** [elixir-lang/elixir#11237]
### Precheck

* For bugs, do a quick search and make sure the bug has not yet been reported - DONE

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.12.2 (compiled with Erlang/OTP 24)
```
* Operating system: macOS

### Current behavior

Ternary in Elixir can hide errors because Elixir doesn't allow partial line/branching test coverage so given this example:

```elixir
def ternary_process(user) do
    _new_card = user["name"] || []
end

------- "TEST" ------
test "ternary" do
    thing = %{"name" => "tim"}
    assert "tim" == BankAccount.ternary_process(thing)
end
```

You'll see the above is considered 100% covered: 

<img width="353" alt="Screen Shot 2021-08-15 at 6 18 30 PM" src="https://user-images.githubusercontent.com/2059265/132926783-c81c8fbc-3d9e-4070-a29b-71dbc73395de.png">

Compare this to the `case` version:

```elixir
def ternary_process(user) do
    case user["name"] do
      value when is_binary(value) -> value
      nil -> []
    end
  end

-------- TEST -------
test "ternary" do
    thing = %{"name" => "tim"}
    assert "tim" == BankAccount.ternary_process(thing)
end
```

<img width="362" alt="Screen Shot 2021-08-15 at 6 53 18 PM" src="https://user-images.githubusercontent.com/2059265/132926772-5814535a-2ba4-451b-9ce0-4f52ffc5c5e2.png">

You can see `nil -> []` is not recorded as covered. But the whole function is still considered 100 percent covered!

With this code, we can see that now we have an uncovered case in our code:
```elixir
def ternary_process(user) do
    case user["name"] do
      value when is_binary(value) -> value
      nil -> Enum.to_list([])
    end
  end
-------- TEST -------
test "ternary" do
    thing = %{"name" => "tim"}
    assert "tim" == BankAccount.ternary_process(thing)
end
```
<img width="395" alt="Screen Shot 2021-09-10 at 5 52 58 PM" src="https://user-images.githubusercontent.com/2059265/132928580-3c9e8d8d-1dae-4735-b1a5-68ac31f4f269.png">

By adding one more test, now, we can see that we've successfully covered this code now:
```elixir
def ternary_process(user) do
    case user["name"] do
      value when is_binary(value) -> value
      nil -> Enum.to_list([])
    end
  end
-------- TEST -------
  test "ternary" do
    thing = %{"bad_key" => "tim"}
    assert [] == BankAccount.ternary_process(thing)
  end

  test "ternary test name key" do
    thing = %{"name" => "tim"}
    assert "tim" == BankAccount.ternary_process(thing)
  end
```
<img width="395" alt="Screen Shot 2021-09-10 at 5 38 12 PM" src="https://user-images.githubusercontent.com/2059265/132927982-dfe45d33-220f-441b-bc3a-3666860489b9.png">

### Expected behavior
With Javascript, Go, Java, Python, or Ruby I can expect partial coverage and static returns to be reported as covered or not.

It feels pretty bad to have to outlaw ternary since it has caused production bugs when the code was reported as 100 percent covered. It also feels bad to have to wrap literals in functions to ensure we're recording coverage on that branch.

**Comment by SophisticaSean** [comment]
It's hard for me to think Elixir is "production ready" when this very important metric has been overlooked. I only discovered this by accident since partials and literal coverage is basically table stakes for most other modern languages now like Javascript, Go, Java, Python, or Ruby.

**Comment by SophisticaSean** [comment]
I am aware that this likely involves work in Erlang but I wanted to have high level issue tracking it here in Elixir.

**Comment by josevalim** [comment]
Unfortunately there is nothing we can do here. The default coverage mechanism is line execution based, so it expects the line to be executed to mark is as covered. The cover docs detail it in the first paragraph:

> The module cover provides a set of functions for coverage analysis of Erlang programs, counting how many times each executable line of code is executed when a program is run. 

A pattern is not a executable line of code nor is an Elixir AST literal. We have made some improvements to help with this but they are not guaranteed.

There are other types of coverages, which are based on clauses. Those coverage would actually check which patterns and guards you matched and so on. If it is such a deal breaker for you to consider Elixir not "Production ready" and be table stakes, then I recommend you investing on this part of the ecosystem you find relevant.

**Comment by SophisticaSean** [comment]
I would appreciate guidance rather than just closing the issue. This comes off as dismissive. I'm reporting the issue for posterity and guidance, not for a quick 1 off answer.

I'm happy to help here but, as I understand it, its a fundamental Elixir/Erlang issue since we it seems one of the two (likely Erlang) is what's responsible for the antiquated line-only coverage reporting. I'm having a hard time understanding how the community could even write an alternative `coverage` library if the language can't fundamentally support this feature. 

Could you help me understand where the fundamental limitation is? I've reviewed the stack from Elixir to Erlang and it seems like a fundamental Erlang limitation, which is why I reached out here for your help.

**Comment by SophisticaSean** [comment]
It'd be more becoming of you as a language curator to guide me on how to resolve this issue rather than write me off and close the ticket considering you've implemented ideas/discussions we've had (like test partitioning) in the past.

**Comment by ericmj** [comment]
Please stop being so antagonistic. No on here is obligated to help you and any help you receive is a courtesy. Language such as “not production ready” and “unbecoming” is not productive, instead try to approach issues with a more positive mindset and I think you will see you get a more positive response.

I would have liked to help with this issue as I have seen the same problems but I don’t really feel like investing in it and reaching out when the original issue and subsequent comments have such a negative feeling.

**Comment by gaiabeatrice** [comment]
I don't feel the feeling of the message was antagonistic, while I see "No on here is obligated to help you and any help you receive is a courtesy." as antagonistic.

I think this was meant to be as the beginning of a discussion, but the issue was suddenly closed.

The other languages were probably brought up as an example to highlight the importance of "non misleading" test coverage and confidence in a project.

Elixir is my favorite language, I am a huge advocate for it, but I do think the issue highlighted here can be improved to bring even more confidence in the code we write everyday.

Here nobody requested anything but guidance and the start of a discussion to bring this feature to life, in my opinion.

**Comment by josevalim** [comment]
As @ericmj said, while I am often very glad to help and provide guidance, it is hard to find motivation to do it when it is put under the premise of it being my obligation or it being a major language flaw that dismisses all of its other production qualities.

My actual obligation is to triage this issue and it has been done. Therefore I will go ahead and lock this issue.

**Comment by josevalim** [comment]
Hi @gaiabeatrice! 👋 Apologies, we were writing at the same time.

> I think this was meant to be as the beginning of a discussion, but the issue was suddenly closed.

Note we use the issues tracker for actionable issues only. If a lot of people in the community opened up issues for guidance, it would be hard for us to focus on the actual bugs and we would definitely be outnumbered, as we are only a few! Therefore I recommend the forum or somewhere to move this discussion forward.

In any case, I appreciate you jumping in. Mentioning other languages is definitely not an issue and they are always useful as reference. Although I do take issue with anyone expecting more of us besides of the huge work we already put into the language. :)
