### ISSUE TITLE
Partial line test coverage and literal returns don't behave intuitively or consistent with most languages.

### ISSUE THREAD

**Issue by SophisticaSean** [elixir-lang/elixir#11244]
https://github.com/elixir-lang/elixir/issues/11237#issue-993678075

Let's try this again. Since this issue was locked for some reason.

How can we solve this problem?

**Comment by SophisticaSean** [comment]
Let's make this issue less about us and more about how we can ameliorate this issue.

**Comment by SophisticaSean** [comment]
I see https://github.com/elixir-lang/elixir/issues/11237#issuecomment-918808367 now. I find it odd @josevalim didn't give me that feedback directly.

I think next time you'd do better by helping me understand the appropriate forum for this issue. It's sad it took a response from someone else to get some constructive feedback.

**Comment by SophisticaSean** [comment]
For posterity, the ElixirForum issue is here: https://elixirforum.com/t/partial-line-test-coverage-in-elixir/42335

**Comment by josevalim** [comment]
Please don't put the onus all on us. While I understand now that mentioning the forum would have been a desired outcome - it was not originally clear - please also understand the tone you take on this and previous discussions are not helpful.

For example, I believe my original comment had constructive feedback into the issue and about the possibility of alternative approaches, continuing to dismiss it is unlikely to make future conversations productive.
