### ISSUE TITLE
Wrong warning in IEx when module private function is converted to public

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11251]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  IEx 1.13.0-dev (fb86a77) (compiled with Erlang/OTP 24)
* Operating system: Linux

### Current behavior

create a project and save these two files.

```elixir
# lib/foo.ex (version 1)
defmodule Foo do
  alias Bar, as: B

  def public(), do: B.public()
end
```

```elixir
# lib/bar.ex (version 1)
defmodule Bar do
  def public(), do: private()
  defp private(), do: :private
end
```

Launch IEx,
$ iex -S mix
```elixir
iex(1)> Foo.public()
:private
```

Now update the files with these versions, where Bar.private/0 is changed from private to public.

```elixir
# lib/foo.ex (version 2)
defmodule Foo do
  alias Bar, as: B

  def public(), do: B.public()
  def private(), do: B.private()
end
```

```elixir
# lib/bar.ex (version 2)
defmodule Bar do
  def public(), do: private()
  def private(), do: :public
end
```

And run:
```elixir
iex(2)> r Bar; r Foo
warning: Bar.private/0 is undefined or private
  lib/foo.ex:4: Foo.private/0
iex(3)> Foo.private()
:public
iex(4)> Foo.public()
:public
iex(5)> Bar.private()
:public

```

Note: This bugs happens if the modules are in different .ex files.

### Expected behavior

No warnings.

**Comment by josevalim** [comment]
The reason for this is because `r` only reloads the file in memory, but it does not reload its metadata in disk. It may be we can't do much about this besides documenting it as a pitfall of `r`, compared to `recompile`, unfortunately. I will investigate.

**Comment by eksperimental** [comment]
@josevalim I have tested the changes and I can confirm that the issue still persists.

**Comment by eksperimental** [comment]
> @josevalim I have tested the changes and I can confirm that the issue still persists.

Oh... I see the docs, `r [Bar, Foo]` does work.
Thank you.
