### ISSUE TITLE
Receiving a message with an invalid timeout value causes a segmentation fault (on IEx)

### ISSUE THREAD

**Issue by khattori** [elixir-lang/elixir#11266]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 24 [erts-12.0.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [jit]
Elixir 1.12.3 (compiled with Erlang/OTP 22)
* Operating system: 
CentOS Stream release 8

### Current behavior

```
iex(1)> send(self(), :hello)
:hello
iex(2)> receive do
...(2)>   :none -> :never
...(2)> after
...(2)>   nil -> :never
...(2)> end
Segmentation fault (core dumped)
```

### Expected behavior
Expect an exception to be thrown as follows:
```
iex(1)> receive do
...(1)>   :none -> :never
...(1)> after
...(1)>   nil -> :never
...(1)> end
** (ErlangError) Erlang error: :timeout_value
    :prim_eval.receive/2
```

**Comment by josevalim** [comment]
@khattori, thanks for the report. Can you please try this in the Erlang shell? I am suspecting this is an Erlang bug:

```erlang
$ erl
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.0  (abort with ^G)
1> self() ! hello.
hello
2> receive
2> none -> never
2> after
2> nil -> never
2> end.
```

**Comment by josevalim** [comment]
I was able to install the same Erlang as yours and I could reproduce it in Elixir but not in Erlang. I will investigate it more. :)

**Comment by khattori** [comment]
I've also confirmed that Erlang doesn't cause the problem.
Thank you for your investigation.

**Comment by josevalim** [comment]
I was able to isolate it and report it upstream: https://github.com/erlang/otp/issues/5235 Thank you for the original report!
