### ISSUE TITLE
Add --noconfirm flag to mix

### ISSUE THREAD

**Issue by xeruf** [elixir-lang/elixir#11265]
### Environment

```
❯ elixir --version
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```
* Operating system: Arch Linux

### Current behavior

When running `mix deps.get` I get the following prompt:
```
Could not find Hex, which is needed to build dependency :phoenix
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn]
```
I get this for multiple packages, and would like to skip the confirmation without specifying each package manually.

### Expected behavior

A flag such as `--noconfirm` which automatically accepts such prompts for scripting.
Or accept `--force` for `deps.get`, too.

**Comment by josevalim** [comment]
At the moment we don’t plan to support anything besides the suggested mix local.hex —force, which you can run explicitly on scripts. Thank you. :)
