### ISSUE TITLE
IEx.Info protocol documentation?

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#11262]
When calling `i/1` in IEx, general information about the term passed to it is shown.
This is implemented as the `IEx.Info` protocol.

I am interested in implementing this protocol for my own types, to improve the description "This is a struct. Structs are maps with a __struct__ key." as well as potentially add some other definitions to the list of definitions.

However, IEx.Info is not currently documented at all.

- Should we add documentation to it?
- Or is this protocol intended to be 'private' to Elixir/IEx? If so, should we add some indication that this is the case somewhere?

**Comment by josevalim** [comment]
@Qqwy we should definitely document it. It is public but apparently the docs were "forgotten". Can you please send a PR? :)
