### ISSUE TITLE
Runtime config not present in migrations

### ISSUE THREAD

**Issue by D4no0** [elixir-lang/elixir#11272]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): elixir 1.12 otp 24.0.5
* Operating system: ubuntu 20.04

### Current behavior

Getting configuration using `Application.get_all_env()` returns only compile-time configuration.
Example:
```
defmodule TestPhoenix.ConfigRepo.Migrations.CreateAccounts do
  use Ecto.Migration

  defp get_env(), do: Application.get_all_env(:test_phoenix)

  def change do
    IO.inspect get_env()
  end
end
```

### Expected behavior

It should return the updated configuration with runtime values.

Is there a way to get the runtime configuration correctly? I suppose this should work without problems in a released system when using release tasks, so this problem persists only when using `mix ecto.migrate`.

**Comment by josevalim** [comment]
What is your Ecto version? It is up to Ecto to load config/runtime.exs and this has been added in recent releases. So I will close this, as it is not an Elixir issue, but if you are on latest and the issue exists, please open up an issue in Ecto. Thanks!

**Comment by D4no0** [comment]
Oh my bad, forgot ecto is a separate library :)

**Comment by D4no0** [comment]
I can confirm that everything works as expected in ecto 3.7.1, thanks for the help.
