### ISSUE TITLE
Store the whole statement in IEx history

### ISSUE THREAD

**Issue by dannote** [elixir-lang/elixir#11296]
### Current behavior

When you paste some multiline code in `iex`:

```
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Interactive Elixir (1.12.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> IO.puts "Hi there"
Hi there
:ok
iex(2)> if true do
...(2)>   IO.puts "Elixir is awesome"
...(2)> end
Elixir is awesome
:ok
iex(3)>  
```

And then press <kbd>↑</kbd>, it shows just the last line:

```
iex(3)> end
```

### Expected behavior

It would be useful to store the whole last valid statement, as it's done in `bash`:

```
iex(3)> if true do
...(3)>   IO.puts "Elixir is awesome"
...(3)> end
```

Maybe combined into one line:

```
iex(3)> if true do; IO.puts "Elixir is awesome"; end
```

**Comment by josevalim** [comment]
Hi @dannote!

Unfortunately this is not something we can address unless the functionality is first introduced in Erlang. IEx simply uses the Erlang shell and the readline behaviour (as well as all Emacs-like bindings) are provided by Erlang.

Therefore, if you want to see this functionality, then you (or someone interested) would have to implement it upstream first.

Given it is nothing something we cannot act on, I will go ahead and close this issue. But feel free to ask for clarifications! Thanks!
