### ISSUE TITLE
`defoverridable` allows changing `defp` to `def`. Is this intended or not?

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#11292]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): v1.12.0 / OTP 24
* Operating system: Linux Manjaro x86-64

### Given

```elixir
defmodule Foo do        
  defp bar(), do: 42
  # In practice, the lines below would be added by some AST returned by a macro:
  defoverridable bar: 0
  def bar(), do: super() + 1
end
```
(This issue is based on https://github.com/Qqwy/elixir-type_check/issues/64 )

### Current behavior

This code happily compiles, resulting in the module `Foo` where `bar` is a public function.

### Expected behavior

I would have expected `defoverridable` to not have worked on a private function.
Or if it did, to not allow changing it from a private function to a public function.

Is the current behaviour intended? (If so, can we improve the documentation?) 
Or is this a bug?

**Comment by josevalim** [comment]
Yes, you can tweak the visibility but you can't change it from function to macro and vice-versa. A pull request to improve the docs is welcome.
