### ISSUE TITLE
Weird behaviour on Macro.to_string on master

### ISSUE THREAD

**Issue by v0idpwn** [elixir-lang/elixir#11297]
Hello!
I was running 1.13-dev and found some malformated things coming from Ecto. I traced them back to `Macro.to_string`. I think it is probably a bug, but I'm not really sure.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit]

Elixir 1.13.0-dev (2dcc7b6) (compiled with Erlang/OTP 24)
```
* Operating system: Linux

### Current behavior
Elixir 1.12.3:
```elixir
iex(1)> Macro.to_string(<<1, 2, 3>>)
"<<1, 2, 3>>"
```
Elixir master:
```elixir
iex(1)> Macro.to_string(<<1, 2, 3>>)
"\"\\x01\\x02\\x03\""
```
### Expected behavior
Same output as 1.12.3

**Comment by josevalim** [comment]
The change is correct. Macro.to_string expects a AST, if you give it a string, then it is because it is a string in the AST too. From Macro.to_string point of view, `<<1, 2, 3>>` must be `{:<<>>, _, [1, 2, 3]}`. For example:

    iex> Macro.to_string(quote do: <<1, 2, 3>>)
    "<<1, 2, 3>>"

**Comment by v0idpwn** [comment]
Understood! Will try to fix this assumption by Ecto then. Thanks a lot!
