### ISSUE TITLE
Elixir builds on GitHub Actions

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#11318]
Currently, on every Elixir GitHub release, there's a `Precompiled.zip` build. That build is against an oldest supported OTP version for that release.

I'd like to propose to build Elixir against all major OTP versions that a given release supports to make sure we can use all the OTP features.

For example, for Elixir v1.13, we'd have:

```
elixir-1.13.0-otp-22.zip
elixir-1.13.0-otp-23.zip
elixir-1.13.0-otp-24.zip
```

We should always build against OTP MAJOR.0, given, say, code compiled on OTP 24.1 may not work optimally on OTP 24.0.

We'd attach these builds to every Elixir release going forward. We could even do it for Elixir master, even compile it against OTP master, but it is a bit tricky because we need a tag and a release to attach these to so let's leave that out of the scope for now. (One idea is we'd have a `master-nightly` tag that we update nightly.)

The release assets would be added after the release is published. Here's how we can do that on GitHub Actions: https://github.com/elixir-nx/xla/blob/9307f1a4eaeeb72a3474b6fa4461e44d40b15dbc/.github/workflows/release.yml#L37:L39. We'd need to make sure we update the release notes with the SHAs of the uploaded artifacts.

Worth mentioning that Hex Bob is already providing [Elixir builds](https://github.com/hexpm/bob#elixir-builds). Bob will keep making Elixir builds but that functionality is becoming deprecated.

**Comment by princemaple** [comment]
There is an official github action for uploading assets, if you want to separate building and uploading.

https://github.com/elixir-lsp/elixir-ls/blob/master/.github/workflows/release-asset.yml#L78-L87

**Comment by michallepicki** [comment]
> There is an official github action for uploading assets
The [actions/upload-release-asset](https://github.com/actions/upload-release-asset) action repository is archived and the action is not maintained anymore.

> The release assets would be added after the release is published
Alternatively, instead of having the workflow be triggered by a new release like Nx does, a pushed tag could be the release workflow trigger. Then the workflow itself could create a *draft* release and upload the built artifacts there. When it is done someone from the team with write access can see the draft on the `/releases` page, fill in release notes and hit Publish. The advantage of such approach is that when it is published, it already has the artifacts. [Gleam](https://github.com/gleam-lang/gleam/blob/16ea8364407f8e4d748c1ba07f12db9bfb3dad2a/.github/workflows/release.yaml#L21) has such workflow set up.

**Comment by wojtekmach** [comment]
> The actions/upload-release-asset action repository is archived and the action is not maintained anymore.

It's fine, we can do `$ gh release upload ...`.

> Alternatively, instead of having the workflow be triggered by a new release like Nx does, a pushed tag could be the release workflow trigger. 

Yup, I think that works too!

**Comment by josevalim** [comment]
I like the tag approach too. A PR exploring this will definitely be welcome if someone wants to tackle it!

**Comment by michallepicki** [comment]
After #11522 got merged, what is left to do for this issue?

**Comment by wingyplus** [comment]
Hi, I'm back ✋ 

I'm working on a nightly release on my fork repo (main branch) https://github.com/wingyplus/elixir. The working progress may be slow due to my childbirth a month ago, which's quite less sleep. But I'll try my best. 🙇

**Comment by wojtekmach** [comment]
Regarding nightly builds, instead of creating a -dev release (which is a moving target), I just found out there's a https://nightly.link service we could consider using instead.

Thanks to @garazdawi (https://github.com/erlang/otp/pull/5597/files#diff-6dd41ca62423bfc1cddf3a9965348f170fef4124046aeac444c7c12dceb8688bR5)

**Comment by wingyplus** [comment]
> Regarding nightly builds, instead of creating a -dev release (which is a moving target), I just found out there's a https://nightly.link service we could consider using instead.
> 
> Thanks to @garazdawi (https://github.com/erlang/otp/pull/5597/files#diff-6dd41ca62423bfc1cddf3a9965348f170fef4124046aeac444c7c12dceb8688bR5)

That's great. If we can do it, we may create a scheduled workflow that builds artifacts every night?

**Comment by wingyplus** [comment]
@josevalim sorry to comment on closed issue. Just want to ask that do we still need the nightly build?

**Comment by josevalim** [comment]
Yes, that would be awesome if you are still interested in tackling it :)
