### ISSUE TITLE
IO.inspect should sort map keys

### ISSUE THREAD

**Issue by drathier** [elixir-lang/elixir#11328]
### Current behavior

`IO.inspect`ing a large map currently lists the keys in a non-sorted order, presumably one reflecting the internal structure of the Map data type.

### Expected behavior

`IO.inspect` should print Map keys in sorted order, so you can more easily find a specific key when debugging.

**Comment by josevalim** [comment]
Hi @drathier , I disagree we should do this change. :) Maps do not guarantee ordering and, as you might know, large maps are unordered. If we sort them, it may give users the wrong impression and, they may be surprised that when they enumerate the map themselves they will get a different order.

**Comment by drathier** [comment]
What about an option argument to inspect then? There's plenty of those already: https://hexdocs.pm/elixir/1.12/Inspect.Opts.html

**Comment by hurricanebilly** [comment]
please an option to print sorted really would help with debugging

**Comment by sabiwara** [comment]
`custom_options: [sort_maps: true]` has been added since 1.14.4 ([doc](https://hexdocs.pm/elixir/1.17.0/Inspect.Opts.html)) and do provide this functionality.
