### ISSUE TITLE
Compiler performance regression on 1.13 (master)

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#11335]
### Environment

* Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
* Elixir 1.13.0-dev (29e40b1) (compiled with Erlang/OTP 22) and
* Elixir 1.12.2 (compiled with Erlang/OTP 24)
* macOS Big Sur 11.5.2

### Current behavior

Compiling [ex_cldr](https://github.com/elixir-cldr/cldr) on Elixir master compiles **28% more slowly** than Elixir 1.12.2 for the `:dev` environment and over **4x slower** for the `:test` environment.  

The difference in the two environments is only the configuration of [ex_cldr backend modules](https://hexdocs.pm/ex_cldr/readme.html#backend-module-configuration). These backend modules are [generated at compile time](https://hexdocs.pm/ex_cldr/readme.html#backend-module-configuration) based upon [CLDR](cldr.unicode.org) data.

Given the compile time is related to the code generation of a variable number of backend modules, and the potentially large number of function heads for certain functions, my working assumption this is the area where something may have changed.

### Expected behavior

Compile times for Elixir 1.12 and master to be similar.

### How to reproduce

1. `git clone https://github.com/elixir-cldr/cldr`
2. `mix deps.get`
2. `mix compile` compiles deps and `ex_cldr`
3. `time mix compile --force` to compile `ex_cldr` and report compilation time (:dev environment)
4. `time MIX_ENV=test mix compile --force` to do the same for :test environment

#### Elixir 1.12.2-otp-24

```bash
kip@Kips-iMac-Pro cldr % asdf current elixir
elixir          1.12.2-otp-24   /Users/kip/.tool-versions

kip@Kips-iMac-Pro cldr % time mix compile --force
Compiling 1 file (.yrl)
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 72 files (.ex)
warning: Using the global configuration is deprecated.  Global configuration only supports the [:json_library, :default_locale, :default_backend, :cacertfile, :data_dir, :force_locale_download] keys. The keys [MyApp.Gettext] should be configured in a backend module or via the :otp_app configuration of a backend module.  See the readme for further information.

Generating MyApp.Cldr for 12 locales named ["ar", "de", "doi", "en", "en-AU", ...] with a default locale named "en"
Generated ex_cldr app
mix compile --force  46.84s user 4.81s system 354% cpu 14.576 total
```

#### Elixir master (Oct 23rd)
```bash
kip@Kips-iMac-Pro cldr % asdf current elixir     
elixir          master          /Users/kip/Development/cldr/.tool-versions

kip@Kips-iMac-Pro cldr % time mix compile --force
Compiling 1 file (.yrl)
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 72 files (.ex)
warning: Using the global configuration is deprecated.  Global configuration only supports the [:json_library, :default_locale, :default_backend, :cacertfile, :data_dir, :force_locale_download] keys. The keys [MyApp.Gettext] should be configured in a backend module or via the :otp_app configuration of a backend module.  See the readme for further information.

Generating MyApp.Cldr for 12 locales named ["ar", "de", "doi", "en", "en-AU", ...] with a default locale named "en"
Compiling lib/backend.ex (it's taking more than 10s)
Generated ex_cldr app
mix compile --force  57.81s user 6.52s system 342% cpu 18.786 total
```
### MIX_ENV=test

The only material difference is the configuration of several backends, one of which
configures all locales (571 of them) which does stress the code gen phase of
compilation but this configuration would only be considered relevant to
testing the lib.

In non-dev environments, the modules in `./mix` are also not compiled (they are not part
of the published package). This is why in :dev mode there are 72 files compiled and only 55 in :test.

#### Elixir 1.12.2-otp-24

```bash
kip@Kips-iMac-Pro cldr % asdf current elixir                  
elixir          1.12.2-otp-24   /Users/kip/.tool-versions

kip@Kips-iMac-Pro cldr % time MIX_ENV=test mix compile --force
Compiling 1 file (.yrl)
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 55 files (.ex)
Generating WithGettextBackend.Cldr for 6 locales named ["en", "en-001", "en-GB", "es", "it", ...] with a default locale named "en-001"
Generating MyApp.Cldr for 13 locales named ["ar", "de", "doi", "en", "en-001", ...] with a default locale named "en-001"
Generating TestBackend.Cldr for 571 locales named ["af", "af-NA", "agq", "ak", "am", ...] with a default locale named "en-001"
Please be patient, generating functions for many locales can take some time
Compiling test/support/cldr_backend.ex (it's taking more than 10s)
Generating DefaultBackend.Cldr for 2 locales named ["en-001", "und"] with a default locale named "en-001"
Generating AnotherBackend.Cldr for 3 locales named ["en", "en-001", "und"] with a default locale named "en-001"
Generating WithNoGettextBackend.Cldr for 2 locales named ["en-001", "und"] with a default locale named "en-001"
Generating WithOtpAppBackend.Cldr for 4 locales named ["en", "en-001", "fr", "und"] with a default locale named "en-001"
Generated ex_cldr app
MIX_ENV=test mix compile --force  136.03s user 12.18s system 169% cpu 1:27.34 total
```

#### Elixir master (Oct 23rd)

```bash
kip@Kips-iMac-Pro cldr % asdf current elixir                  
elixir          master          /Users/kip/Development/cldr/.tool-versions
kip@Kips-iMac-Pro cldr % time MIX_ENV=test mix compile --force

Compiling 1 file (.yrl)
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 55 files (.ex)
Generating WithGettextBackend.Cldr for 6 locales named ["en", "en-001", "en-GB", "es", "it", ...] with a default locale named "en-001"
Generating MyApp.Cldr for 13 locales named ["ar", "de", "doi", "en", "en-001", ...] with a default locale named "en-001"
Generating TestBackend.Cldr for 571 locales named ["af", "af-NA", "agq", "ak", "am", ...] with a default locale named "en-001"
Please be patient, generating functions for many locales can take some time
Compiling lib/backend.ex (it's taking more than 10s)
Compiling test/support/cldr_backend.ex (it's taking more than 10s)
Generating DefaultBackend.Cldr for 2 locales named ["en-001", "und"] with a default locale named "en-001"
Generating AnotherBackend.Cldr for 3 locales named ["en", "en-001", "und"] with a default locale named "en-001"
Generating WithNoGettextBackend.Cldr for 2 locales named ["en-001", "und"] with a default locale named "en-001"
Generating WithOtpAppBackend.Cldr for 4 locales named ["en", "en-001", "fr", "und"] with a default locale named "en-001"
Generated ex_cldr app
MIX_ENV=test mix compile --force  510.02s user 48.19s system 135% cpu 6:51.92 total
```

**Comment by kipcole9** [comment]
José, I re-ran compilation on Elixir master (cloned and compiled on OTP 24) and performance has improved for sure, down from 7 minutes to 6 minutes. But ... thats still significantly different to Elixir 1.12 at 1 minute 30 seconds.

I know this is a very atypical case, but the comparative difference is surprising. I'm happy to dig into this further but I don't actually know how to profile the compilation process.  If you have any suggestions please let me know and I'll explore further.

**Comment by josevalim** [comment]
So the slow down comes from this module:

```elixir
defmodule TestBackend.Cldr do
    use Cldr,
      default_locale: "en-001",
      locales: :all,
      gettext: TestGettext.Gettext,
      precompile_transliterations: [{:latn, :arab}, {:arab, :thai}, {:arab, :latn}],
      providers: []
  end
```

I suspect that compiling it directly (via the ex_cldr) dependency is enough to reproduce the error however I am running into some unexpected behaviour. If I do:

    time elixir -pa "_build/test/lib/*/ebin" test/support/cldr_backend.ex

It takes the same on Elixir v1.12 and Elixir v1.13. However, if I do `mix compile`, then it is indeed (much) faster on v1.12! So there is something happening only during compilation that makes it much faster and somehow that changed between v1.12 and v1.13. I will continue investigating.

**Comment by josevalim** [comment]
Ok, so here is the root cause: https://github.com/elixir-cldr/cldr/blob/master/lib/cldr/locale/cache.ex#L34

We have renamed this process dictionary key to something else, so the cache is disabled. We didn't have a way to check for this in earlier Elixir versions, but now we have `Code.can_await_module_compilation?/0` since v1.11. If you find yourself in a situation where you need to rely on internal compiler behaviour, please open up an issue so we can expose a stable API. :)
