### ISSUE TITLE
mix test: File.cd in test can cause paralllel compiler compile error due to working directory changed

### ISSUE THREAD

**Issue by wingyplus** [elixir-lang/elixir#11368]
### Environment

```shell
$ elixir --version
Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

* Operating system: macOS

### Current behavior

Found in my phoenix application. If I have tests that change directory like change to fixture directory and enable asynchronous test:

```elixir
defmodule ATest do
  use App.DataCase, async: true

  test "match the file" do
    in_fixtures("dira", fn -> 
      # do some test logic
    end)
  end 

  defp in_fixtures(dir, fun) do
    File.cd!("test/fixtures/#{dir}", fun)
  end
end
```

And have other test files that run asynchronously too, test will fail with due compilation error like:

```
==> app
..........................................................................................................
== Compilation error in file test/app/redacted_test.exs ==
** (MatchError) no match of right hand side value: {:error, :enoent}
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:428: Kernel.ParallelCompiler.require_file/2
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:321: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

Code compilation should not error. Test flaky is acceptable. :)

**Comment by wingyplus** [comment]
Just try to fix by expanding path before running `Kernel.ParallelCompiler.require`:

```diff
$ git diff
diff --git a/lib/mix/lib/mix/compilers/test.ex b/lib/mix/lib/mix/compilers/test.ex
index 0cfc121c8..0478a7c11 100644
--- a/lib/mix/lib/mix/compilers/test.ex
+++ b/lib/mix/lib/mix/compilers/test.ex
@@ -37,6 +37,8 @@ def require_and_run(matched_test_files, test_paths, opts) do
     else
       task = ExUnit.async_run()

+      test_files = Enum.map(test_files, & Path.expand(&1))
+
       try do
         case Kernel.ParallelCompiler.require(test_files, parallel_require_callbacks) do
           {:ok, _, _} -> :ok
```

Tests can now running without compilation error.

**Comment by josevalim** [comment]
If you call cd, then your tests cannot run concurrently because cd is global. We could change the compiler but other operations may fail, such as any relative path used by your test files or any other concurrently running mix operation. Please disable async for this case.

**Comment by wingyplus** [comment]
I agree that it should not run concurrently since it's file operation. But at least, tests that relate to cd operation should fail and let other tests run, not break because of compilation failure.

**Comment by wingyplus** [comment]
But if try expand test file path before running parallel compiler would safe enough for this case?
