### ISSUE TITLE
Breaking change in Mix.Shell.yes?

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#11372]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.13.0-rc.0 (48b838a) (compiled with Erlang/OTP 24)
* Operating system: macOS

### Current behavior

The change (introduced in https://github.com/elixir-lang/elixir/pull/10892/files) is mentioned in release notes as a bug fix but is a breaking change forcing code changes and breaking backwards compatibility.

```
warning: got "@impl Mix.Shell" for function yes?/1 but this behaviour does not specify such callback. The known callbacks are:

  * Mix.Shell.cmd/1 (function)
  * Mix.Shell.cmd/2 (function)
  * Mix.Shell.error/1 (function)
  * Mix.Shell.info/1 (function)
  * Mix.Shell.print_app/0 (function)
  * Mix.Shell.prompt/1 (function)
  * Mix.Shell.yes?/2 (function)

  lib/language_server/mix_shell.ex:41: ElixirLS.LanguageServer.MixShell (module)

warning: function yes?/2 required by behaviour Mix.Shell is not implemented (in module ElixirLS.LanguageServer.MixShell)
  lib/language_server/mix_shell.ex:1: ElixirLS.LanguageServer.MixShell (module)
```

### Expected behavior

Old arity version deprecated but still present in behaviour as an optional callback. Standard library code able to call new arity and fall back to old arity.

**Comment by josevalim** [comment]
It is listed as a bug fix as an accident, I will fix that. In any case, it is worth noting that adding new callbacks are not a breaking change. Of course, we still need to keep `yes?/1` as part of the behaviour too, after all `Mix.shell().yes?/1` must still work, but if any new code calls `yes?/2`, then it won't work and that is expected. Fix incoming soon.

**Comment by lukaszsamson** [comment]
Thanks
