### ISSUE TITLE
No warning when matching __Module__ in function head

### ISSUE THREAD

**Issue by evnu** [elixir-lang/elixir#11380]
Usually, when using incorrect compiler variables such as `__FUBAR__` in a function head, a warning is written. This does not happen when writing `__Module__` instead of `__MODULE__` (or any prefix of `Module` with at least `Mo`).

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
~ elixir --version
Erlang/OTP 24 [erts-12.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

* Operating system:  Linux

### Current behavior

```elixir
defmodule MyModule do
  defstruct []

  defp matcher(n = %__Module__{}) do
    n.__struct__
  end

  def runner do
    matcher(%__MODULE__{})
  end
end

MyModule.runner() |> IO.inspect()
```

`__Module__` is made available as a variable in `matcher/1`. Note that using a struct is not required, the following has the same behaviour:

```elixir
  defp matcher(m = __Mo__) do
    m
  end
```

### Expected behavior

```
warning: unknown compiler variable "__Module__" (expected one of __MODULE__, __ENV__, __DIR__, __CALLER__, __STACKTRACE__)
  repro.exs:4: MyModule.matcher/1
```

**Comment by josevalim** [comment]
Hi @evnu!

It is worth clarifying that the code that you wrote is valid from the point of view of the compiler. The warning is there to help developers catch common gotchas at the cost of refusing valid code (after all, someone *could* name their variable `___MODULE___` and, albeit confusing, it should be fine).

Therefore, the cost of warning in more situations is rejecting even further valid code. Our heuristic today expect all letters to be uppercase, and I plan to leave it as such for now, but if this continues to be a common mistake, we will make the warning more general.

Thanks!
