### ISSUE TITLE
Elixir installer - Download failed

### ISSUE THREAD

**Issue by Squadz** [elixir-lang/elixir#11388]
Hi all,
FYI, it seems there is an issue with the installer "elixir-websetup.exe".
The connection failed when downloading Erlang - OTP 24.1 (64-bit), however if  I uncheck it, I can successfully download Elixir.
![1](https://user-images.githubusercontent.com/6948946/141494403-45e1052e-ca8a-4737-86c1-24712b42a8bd.png)

Same thing happened with chocolatey:
The remote file either doesn't exist : https://erlang.org/download/otp_win64_24.0.exe
![2](https://user-images.githubusercontent.com/6948946/141494525-8f4fab77-ef1f-4625-b584-c3583aa755a3.png)

As a workaround, I downloaded the latest OTP from : https://github.com/erlang/otp/releases/download/OTP-24.1.5/otp_win64_24.1.5.exe

**Comment by josevalim** [comment]
Parts of erlang.org is offline at the moment. I believe it is something temporary and it should be available back up by tomorrow. I will keep this open up meanwhile, thanks for reporting!

**Comment by Squadz** [comment]
Closing this issue, the link for "otp_win64_24.0.exe" is working again.
