### ISSUE TITLE
Code formatted with `Code.quoted_to_algebra` does not preserve user choice on module attribute kw list

### ISSUE THREAD

**Issue by doorgan** [elixir-lang/elixir#11393]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
  Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

  Elixir 1.14.0-dev (39121ad) (compiled with Erlang/OTP 22)
* Operating system: Linux

### Current behavior

Parsing a string with a module attribute and a keyword list ignores the user preference on brackets:
```elixir
iex> opts = [literal_encoder: &{:ok, {:__block__, &2, [&1]}}, token_metadata: true]
iex> {:ok, quoted} = Code.string_to_quoted("""
...> @foo [
...>   a: 1,
...>   b: 2
...> ]
...> """, opts)
iex> quoted |> Code.quoted_to_algebra() |> Inspect.Algebra.format(80) |> IO.puts()
@foo a: 1,
     b: 2
:ok
```
([Reproduction gist](https://gist.github.com/doorgan/d2ca852802781e1a97ae8399674d3a19))

### Expected behavior

It should preserve the user choice on square brackets like it does with the rest of the code:
```elixir
iex> opts = [literal_encoder: &{:ok, {:__block__, &2, [&1]}}, token_metadata: true]
iex> {:ok, quoted} = Code.string_to_quoted("""
...> @foo [
...>   a: 1,
...>   b: 2
...> ]
...> """, opts)
iex> quoted |> Code.quoted_to_algebra() |> Inspect.Algebra.format(80) |> IO.puts()
@foo [
  a: 1,
  b: 2
]
:ok
```

---

I was going to prepare a PR for this one, but I'm not sure if the issue here is with the normalizer or the formatter. As far as I can tell, the only difference is that the kw list with brackets has `:closing` metadata. Whether or not this metadata is present, the formatter seems to only look at the `format: :keyword` metadata from the elements.

**Comment by josevalim** [comment]
Yes, we should address it. It sounds like a formatter issue, because if the normalizer is enough to keep it as keyword in other places, it should be enough here too.
