### ISSUE TITLE
Concurrency issues with dependencies (in 1.13.0-rc.0?)

### ISSUE THREAD

**Issue by marcandre** [elixir-lang/elixir#11392]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.13.0-rc.0

### Current behavior

I just installed 1.13.0-rc.0 and updated `fun_with_flags` on a branch (previous version was not elixir 1.13 compatible).

I thought I was going crazy because I got a very strange error. It was not easy, but I was able to reproduce it when switching branches.

Let's say there are two branches "new" and "old" with the `mix.exs/lock` files pointing to the new and old `fun_with_flags` respectively.

1) start from branch "new". `mix compile` works fine
2) switch to branch "old" (do nothing else)
3) switch back to branch "new"
4) `mix compile` fails as it somehow attempts to compile the old `fun_with_flags`!?
5) check the commit log, everything is as it should be, waste some more time...
6) `mix compile` now works!?!?

I finally understood that the issue was that my VS Studio Code was resolving the dependencies in the background.
After step 2, VS code starts `mix deps.get` or equivalent, which finishes I imagine at some point after step 3. I presume VS Code queues up a new `mix deps.get` on the second branch switch, and when that finishes we get the successful compilation of step 6. So maybe the failing `mix compile` made the version check before the the old `fun_with_flags` gets written to disk but the files were read for compilation afterwards?

```
$ mix compile
==> db_connection
Compiling 14 files (.ex)
Generated db_connection app
==> postgrex
Compiling 62 files (.ex)
Generated postgrex app
==> ecto_sql
Compiling 26 files (.ex)
Generated ecto_sql app
==> fun_with_flags
Compiling 21 files (.ex)
Generated fun_with_flags app
==> one_time_pass_ecto
Compiling 2 files (.ex)
Generated one_time_pass_ecto app
==> fun_with_flags_ui
Compiling 5 files (.ex)
Generated fun_with_flags_ui app
==> geo_postgis
Compiling 4 files (.ex)
Generated geo_postgis app
==> bobby
Generated bobby app
$ git switch old
Switched to branch 'old'
$ git switch new
Switched to branch 'new'
$ mix compile
==> db_connection
Compiling 14 files (.ex)
Generated db_connection app
==> postgrex
Compiling 61 files (.ex)
Generated postgrex app
==> ecto_sql
Compiling 26 files (.ex)
Generated ecto_sql app
==> fun_with_flags
Compiling 20 files (.ex)

== Compilation error in file lib/fun_with_flags/protocols/actor.ex ==
** (CompileError) lib/fun_with_flags/protocols/actor.ex:117: undefined function defdelegate/2 (there is no such import)

could not compile dependency :fun_with_flags, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile fun_with_flags", update it with "mix deps.update fun_with_flags" or clean it with "mix deps.clean fun_with_flags"
[15:20][~/super-pas(delete_me)]$ mix compile
[...]
Generated bobby app
```

Sadly, I am not familiar enough with the compilation process to suggest anything, I am unsure if this issue existed before 1.13 or not, and but it seems like some sort of global lock when updating the dependencies and/or compiling could improve this issue.  Alternatively, dependencies might be fetched and organized by version, which could circumvent this issue and avoid us having to constantly `mix deps.get` when switching between branches with different dependencies.
Maybe there is no good solution for this, in which case feel free to close this.

**Comment by michallepicki** [comment]
> I finally understood that the issue was that my VS Studio Code was resolving the dependencies in the background.

I think it should be off by default, it's the first thing I disable in ElixirLS

**Comment by josevalim** [comment]
Hi @marcandre! The issue you describe makes sense, as there are no locks around the dependency management. So if the compiler is running while something else is calling `mix deps.get`, then we will have race conditions.

The versioning could be a solution but it is tricky outside of Hex. For example, versioning with git is a bit harder, because we only know the reference after we start the initial checkout and renaming the directory will lead to more work on the filesystem. We could alternatively move the git repositories elsewhere and do shallow copies, but this means Mix is now caching git repos elsewhere in the filesystem.

So, for now, I think @michallepicki is correct and VS Studio Code should likely not have this functionality enabled by default, as they are working with an assumption that is not true.

**Comment by marcandre** [comment]
Thanks to both of you. I opened https://github.com/elixir-lsp/elixir-ls/issues/626 and will close this.
