### ISSUE TITLE
Generated: true does not silence incompatible types warning

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#11407]
### Overview

Option `generated: true` should silence all the warnings inside given AST. As the documentation says
> :generated - Whether the code should be considered as generated by the compiler or not. This means the compiler and tools like Dialyzer may not emit certain warnings.

But it doesn't silence incompatible types warnings. These warnings can't be avoided when generating code which uses external variables

### Environment

```
Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.12.3 (compiled with Erlang/OTP 24)
linux
```

### Current behavior

```elixir
defmodule Testerino do

  defmacrop do_the_case(variable) do
    quote generated: true do
      variable = unquote(variable)
      case nil do
        _ when is_integer(variable) ->
          :integer
        _ when is_atom(variable) ->
          :atom
      end
    end
    |> Macro.prewalk(fn item ->
      Macro.update_meta(item, &Keyword.put(&1, :generated, true))
    end)
  end

  def g() do
    variable = 1
    do_the_case(variable)
  end
  
end
```

Raises an incompatible types warning

```elixir
warning: incompatible types:

    integer() !~ atom()

in expression:

    # types.exs:20
    is_atom(variable)

where "variable" was given the same type as "variable" in:

    # types.exs:20
    variable = variable

where "variable" was given the type atom() in:

    # types.exs:20
    is_atom(variable)

where "variable" was given the type integer() in:

    # types.exs:19
    variable = 1

Conflict found at
  types.exs:20: Testerino.g/0
```

### Expected behavior

This code does not raise an incompatible types warning because `generated` is set to `true` in the ast

### PS
> I get that this code can be rewritten. The more meaningful example can be found [here](https://github.com/hissssst/pathex/blob/master/test/pathex_test.exs#L124)

**Comment by hissssst** [comment]
@josevalim , Any comments on this?

**Comment by josevalim** [comment]
@hissssst what do you mean?

**Comment by hissssst** [comment]
@josevalim, Ahhh, sorry!
I didn't see the commit hash attached, I thought that this issue was silently closed. Again, I am sorry!

Thank you for this quick fix!
