### ISSUE TITLE
IEx: Code completion is missing for callback implementions in Exceptions

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11409]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.13.0-rc.1 (2765e0f) (compiled with Erlang/OTP 24 
* Operating system: Linux

### Current behavior

```elixir
Interactive Elixir (1.13.0-rc.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Code.LoadError.

# I had to manually type "exception("                                              
iex(1)> Code.LoadError.exception([file: "xxx", message: "xxx"])
%Code.LoadError{file: "xxx", message: "could not load xxx"}

```

**Comment by RudolfMan** [comment]
Isn't it "by design"? Callback implementations are not meant to be called directly by user code. So implicitly they are marked with `@doc false`.

**Comment by eksperimental** [comment]
Hi. Behaviours are a way to enforce that certain functions/macros (callback) are implemented given a module adheres to it.
In the particular case of the behaviours `Exceptions` boilerplate and overridable callback implementations are created by useing `defexception` and these callbacks implementations docs are not set to `false`.

**Comment by josevalim** [comment]
`@impl true` Sets `@doc false` By default, so this is expected.

**Comment by eksperimental** [comment]
> `@impl true` Sets `@doc false` By default, so this is expected.

So using `@impl ModuleName` bypasses this and does not set `@doc false`.. Good to know

**Comment by RudolfMan** [comment]
> So using `@impl ModuleName` bypasses this and does not set `@doc false`.

Not really. To make autocomplete work we could set `@doc` explicitly.

**Comment by wojtekmach** [comment]
> So using @impl ModuleName bypasses this

`@impl true` sets `@doc false` but `@impl ModuleName` does not? Seems like a bug, `@impl Mod` and `@impl true` should behave the same in this regard?

**Comment by josevalim** [comment]
Both of them set @doc false. When I said "@impl true Sets @doc false By default, so this is expected.", I didn't say that only `@impl true` sets it to false. :)

**Comment by eksperimental** [comment]
I ran the examples in the Elixir website, and it did show the suggestions.

```elixir
Interactive Elixir (1.13.0-rc.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule Parser do
...(1)>   @doc """
...(1)>   Parses a string.
...(1)>   """
...(1)>   @callback parse(String.t) :: {:ok, term} | {:error, String.t}
...(1)> 
...(1)>   @doc """
...(1)>   Lists all supported file extensions.
...(1)>   """
...(1)>   @callback extensions() :: [String.t]
...(1)> end
iex(2)> defmodule JSONParser do
...(2)>   @behaviour Parser
...(2)> 
...(2)>   @impl Parser
...(2)>   def parse(str), do: {:ok, "some json " <> str} # ... parse JSON
...(2)> 
...(2)>   @impl Parser
...(2)>   def extensions, do: ["json"]
...(2)> end
iex(3)> JSONParser.
extensions/0    parse/1
```

Now I ran it with `@impl true` and it works the same way.

**Comment by josevalim** [comment]
Remember that modules defined in memory do not have docs, so we don’t know what is public/private, therefore we show everything.
