### ISSUE TITLE
Unicode regression in 1.13.0-rc.1

### ISSUE THREAD

**Issue by k-cross** [elixir-lang/elixir#11400]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): elixir 1.13.0-rc.1-otp24
* Operating system: MacOS 12.0.1

### Current behavior

Compilation fails of open source dependency `faker`

```
== Compilation error in file lib/faker/string.ex ==
** (SyntaxError) lib/faker/string.ex:144:15: invalid bidirectional formatting character in string: \u202A. If you want to use such character, use it in its escaped \u202A form instead
    (elixir 1.13.0-rc.1) lib/kernel/parallel_compiler.ex:346: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
could not compile dependency :faker, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile faker", update it with "mix deps.update faker" or clean it with "mix deps.clean faker"
```

### Expected behavior

Dependency compiles.

I looked at the line and position that is breaking in `faker`, and it looks valid to me but I do not understand unicode. It compiles in rc.0 also.

**Comment by ericmj** [comment]
There is a fix in progress for this in faker: https://github.com/elixirs/faker/pull/434.
