### ISSUE TITLE
Improve Error when macro exists but has not been required.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11408]
```elixir
iex> Foo.map_get(%{a: 1, x: :x}, :x)                                                          
** (UndefinedFunctionError) function Foo.map_get/2 is undefined or private. However there is a macro with the same name and arity. Be sure to require Foo if you intend to invoke this macro
    Foo.map_get(%{a: 1, x: :x}, :x)
```

IMHO we should not raise with `UndefinedFunctionError` because:

1. the macro is defined, it just has not been required.

2.  by saying  "function Foo.map_get/2 is undefined or private" and later "However there is a macro with the same name and arity." is contradictory:
-  since macros are function and this one does exist
- also there cannot be a private function or public function with the same name and arity under the same module, so it is confusing, if not misleading, to mention that.

I think we could error.:

`** (UnrequiredMacroError) module Foo needs to be required in order to ivoke macro Foo.map_get/2`

I can contribute a PR if the proposal is considered.

**Comment by josevalim** [comment]
Emitting the warning that you want is not possible:

1. If the module was not required/compiled, we should not load/compile it, and therefore we don't know if something is a macro or not

2. Then at runtime it will try to call it as a function, raise undefined_function, which we then annotate with macro information. Changing the exception name would be confusing

**Comment by eksperimental** [comment]
I see. so, couldn't we only update the error message?

Something like:
> ** (UndefinedFunctionError) in order to invoke macro Foo.map_get/2 module Foo needs to be required
