### ISSUE TITLE
Inspect protocol implementation for Exception does not work in Elixir core

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11404]
Plesase use this branch.

https://github.com/eksperimental/elixir/commits/inspect_exception

this commit add the implementation of Inspect,
https://github.com/eksperimental/elixir/commit/2f70c3395a5b4b99e41fa37750c757f05a1aa74e

```elixir
iex> IO.inspect(%Inspect.Error{})
%Inspect.Error{message: nil}
%Inspect.Error{message: nil}

iex> Inspect.__protocol__(:impls)
{:consolidated,
 [Any, Atom, BitString, Date, Date.Range, DateTime, Failing, Float, Function,
  HashDict, HashSet, Integer, List, Macro.Env, Map, MapSet, NaiveDateTime, PID,
  Port, Range, Reference, Regex, Stream, Time, Tuple, Version,
  Version.Requirement]}
```

It only happens in Elixir Core

**Comment by josevalim** [comment]
@eksperimental the inspect protocol should not be consolidated for Elixir, only in projects:

```
Interactive Elixir (1.13.0-rc.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Inspect.__protocol__ :impls
:not_consolidated
```

So my hunch is that you have a Elixir.Inspect.beam around that is overriding the Inspect actually in Elixir. :)

**Comment by eksperimental** [comment]
I messed up here.
What i mean is that it did not happen in an Mix project but loading the Elixir main version that was linked.
I was running `make clean comiple" but what I actually had to do was "mix clean" in the Mix project. 

Thank you
