### ISSUE TITLE
Mirroring (HEX_CDN and HEX_MIRROR) not working in rebar3 specific case

### ISSUE THREAD

**Issue by matreyes** [elixir-lang/elixir#11414]
### Precheck

Checked!

### Environment

elixir:1.10 (official docker version)

### Current behavior

Using hex mirrors:
export HEX_MIRROR=*private url*
export HEX_CDN=*private url*

and Having `repo.hex.pm` blocked by firewall (you could test it pointing to localhost in /etc/hosts)

and Having Snappyer as a dependency for my project (https://hex.pm/packages/snappyer).

When I Fetch the dependencies (mix deps.get), It downloads them through the mirror without problem.
But when I try to compile the dependency, it tries to connect to `repo.hex.pm` to get the `pc` sub-dependency (https://hex.pm/packages/pc), and it fails as it is blocked.

```
# DEBUG=1 mix deps.compile snappyer
===> Hex get_package request failed: {error,
                                      {failed_connect,
                                       [{to_address,{"repo.hex.pm",443}},
                                        {inet,[inet],nxdomain}]}}
....
``` 

Running `rebar3 compile` directly from the snappyer project having exported the HEX_CDN env variable, works OK.
Running `rebar3 compile` directly from the snappyer project removing the HEX_CDN env variable, fails as expected.

### Expected behavior

Compiling from mix (from the elixir project) should use the HEX_MIRROR (and/or HEX_CDN) env variable to fetch the `pc` package, but it does not. 

Thanks!!!!!!!

**Comment by ericmj** [comment]
We should pass down `HEX_CDN` to rebar3 when we compile deps here: https://github.com/elixir-lang/elixir/blob/main/lib/mix/lib/mix/tasks/deps.compile.ex#L220.

**Comment by josevalim** [comment]
@ericmj i don't think that's the case, unfortunately. All env vars are automatically passed downstream. You can try it out with ` Mix.shell().cmd("env")`.

**Comment by matreyes** [comment]
Hi @josevalim and @ericmj 

I have more info about the error.
Mix tries to use rebar3 from `/root/.mix/rebar3`, and in that case, it doesn't take environment variables, even if I pass them directly in the command (and I don't have any idea why this happens)
If I set `MIX_REBAR3=rebar3` (so it uses `/usr/local/bin/rebar3`) it takes env variables and compiles successfully.

I don't know if you want to investigate more or create a kind of fallback for this issue, if not, feel free to close the thread.

And as always, thanks both of you for your amazing work ❤️.

**Comment by josevalim** [comment]
@matreyes could it be that you have an outdated rebar in `/root/.mix/rebar3`? Can you try `/root/.mix/rebar3 --version`? And what is `rebar3 --version`? Does it work after `mix local.rebar`?

**Comment by matreyes** [comment]
/root/.mix/rebar3 --version
3.13.3

rebar3 --version
3.17.0

mix local.rebar doesn't updates /root/.mix version (the other is already up to date)

**Comment by josevalim** [comment]
Ok, it seems to be rebar3 related then: https://github.com/erlang/rebar3/pull/2204

If you pick a more recent Elixir version, it should install a more recent rebar3 too.

Thanks for the report!
