### ISSUE TITLE
`Macro.to_string` fails on some tuples in 1.13rc1 but works in 1.12.3

### ISSUE THREAD

**Issue by breunigs** [elixir-lang/elixir#11423]
### Environment

I am comparing:
```
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.12.3 (compiled with Erlang/OTP 22)
```
and
```
Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.13.0-rc.1 (0974e90) (compiled with Erlang/OTP 22)
```
OS is `Linux 5.14.0-4-amd64 #1 SMP Debian 5.14.16-1 (2021-11-03) x86_64 GNU/Linux` in both cases.

### Minimal example to reproduce

Technically the issue already occurs with: `Macro.to_string({"a", "b", "c"})`. However, I am not sure if that is even sensible, so here's a slightly larger, but still reduced version:

```elixir
{:def, [context: Elixir, import: Kernel],
 [{:sources, [context: Elixir], []}, [do: [{"a", "b", "c"}]]]}
|> Macro.to_string()
```

The quoted code generated by both versions is identical. It can be reproduced using:
```elixir
sources = [{"a", "b", "c"}]
quote do
  def sources() do
    unquote(sources)
  end
end
```

### Results

1.12.3 returns the expected `"def(sources()) do\n  [{\"a\", \"b\", "\c\"}]\nend"`
1.13rc1 bails:
```
** (FunctionClauseError) no function clause matching in Keyword.fetch/2    
    
    The following arguments were given to Keyword.fetch/2: 
    
        # 1
        "b"
    
        # 2
        :line
    
    Attempted function clauses (showing 1 out of 1):
    
        def fetch(keywords, key) when is_list(keywords) and is_atom(key)
    
    (elixir 1.13.0-rc.1) lib/keyword.ex:535: Keyword.fetch/2
    (elixir 1.13.0-rc.1) lib/code/formatter.ex:1936: Code.Formatter.traverse_line/2
    (elixir 1.13.0-rc.1) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir 1.13.0-rc.1) lib/code/formatter.ex:1878: Code.Formatter.each_quoted_to_algebra_with_comments/6
    (elixir 1.13.0-rc.1) lib/code/formatter.ex:1866: Code.Formatter.quoted_to_algebra_with_comments/6
    (elixir 1.13.0-rc.1) lib/code/formatter.ex:552: Code.Formatter.block_args_to_algebra/4
    (elixir 1.13.0-rc.1) lib/code/formatter.ex:156: Code.Formatter.to_algebra/2
    (elixir 1.13.0-rc.1) lib/macro.ex:948: Macro.to_string/1
```

### Extra info

* The output is similar for rc0, so I guess this is not a result of the seemingly related https://github.com/elixir-lang/elixir/commit/d7b1591e8311f663828dcf0ace3b438cd2a914bd .
* The actual version I had in use with 1.12 uses this for generation:
  https://github.com/breunigs/veloroute/blob/v2/lib/video/rendered.ex#L175-L209
  and yields output like this:
  https://github.com/breunigs/veloroute/blob/v2/data/auto_generated/video/00ac485abc0115aac3f60077b3cfcda6.ex#L25
* The tuples need to have exactly 3 elements. 
* The types don't matter, i.e. this works equally well (or not) with atoms or integers

**Comment by josevalim** [comment]
Keep in mind that the previous version worked by accident. `Macro.to_string` expects an AST as input and `{1, 2, 3}` is not a valid AST. You are missing a `Macro.escape` call somewhere. :)

**Comment by breunigs** [comment]
> You are missing a `Macro.escape` call somewhere.

Indeed I was, thank you for the hint. A less low level error message would be appreciated, but I'm not sure it's worth the effort to implement. In any case, it's not something to fix for an RC.
