### ISSUE TITLE
Kernel.put_elem reports ArithmeticError if second argument is not an integer

### ISSUE THREAD

**Issue by rlipscombe** [elixir-lang/elixir#11435]
```
iex(1)> Kernel.put_elem({1, 2}, :moo, 1)
** (ArithmeticError) bad argument in arithmetic expression: :moo + 1
    :erlang.+(:moo, 1)
```

I understand _why_: it just calls `:erlang.setelement`, adding one to the index ('cos Erlang's one-based). But it's confusing (particularly because I was messing around with `Kernel.+` and pipelines at the time).

Would it be better if it failed with `ArgumentError` instead?

Similarly, `Kernel.elem`:

```
iex(1)> Kernel.elem({1, 2}, :moo)
** (ArithmeticError) bad argument in arithmetic expression: :moo + 1
    :erlang.+(:moo, 1)
```
(Elixir 1.12.3 on Erlang/OTP-24.0.6)

**Comment by rlipscombe** [comment]
I should note that I attempted to implement this:

```
  def put_elem(tuple, index, value) when is_tuple(tuple) and is_integer(index) and index >= 0 do
    :erlang.setelement(index + 1, tuple, value)
  end
```

(I had to move the `and` macro up in the file...)

...but my changes aren't taking. Is there something "special" about Kernel that means it doesn't bother evaluating guards?

**Comment by v0idpwn** [comment]
These functions are inlined by the compiler so they don't add overhead over calling the erlang bifs

**Comment by rlipscombe** [comment]
> These functions are inlined by the compiler so they don't add overhead over calling the erlang bifs

Ah, OK. Where is this done? Is it just certain `Kernel` functions, or all of them?

**Comment by rlipscombe** [comment]
Never mind. Found it: `elixir_rewrite.erl`, line 258, `inner_rewrite`.

**Comment by josevalim** [comment]
Yeah, exactly. Adding the checks at compile-time would unfortunately make it much slower.
