### ISSUE TITLE
Backport "Silence httpc warnings" to supported Elixir versions

### ISSUE THREAD

**Issue by mezz** [elixir-lang/elixir#11430]
Hello!
The issue described here: [Mix local.hex warning - ‘Authenticity is not established by certificate path validation’](https://elixirforum.com/t/mix-local-hex-warning-authenticity-is-not-established-by-certificate-path-validation/39665)
Was fixed in Elixir 1.12 here: https://github.com/elixir-lang/elixir/commit/3339168330c4a8b8970085f2ae631e2a487cee01

I am running Github Actions to validate my small library against Elixir 1.7 through 1.12, and all the older ones are printing these warnings that appear security-related but are actually benign.
Could this fix be backported to all supported Elixir versions? 
This is not an urgent issue, but I thought I should ask.

Thank you!

**Comment by josevalim** [comment]
Note earlier Elixir versions are not guaranteed to work on OTP 24, which is when this warning was introduced: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

Plus it is unlikely we will release new versions from previous versions, so overall I don't see a need to backport it. :) Thanks for pinging though!

**Comment by mezz** [comment]
I have confirmed that this is only affecting Elixir 1.11.4 with OTP 24, so I will just remove that from my matrix of versions to test.
Thank you for the information!
