### ISSUE TITLE
URI.new: possible regression, or bad error, when query contains unquoted square bracket

### ISSUE THREAD

**Issue by schnittchen** [elixir-lang/elixir#11450]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

```
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.0-rc.1 (compiled with Erlang/OTP 24)
```

From the `elixir:1.13-slim` Docker container

(And I think this tag should not carry the rc1!)

* Operating system: Ubuntu/Pop! OS, Docker (see above)

### Current behavior

```
"http://www.example.com?x[y]=" |> URI.new   
{:error, ":"}

"http://www.example.com?x[y]=" |> URI.parse
%URI{
  authority: "www.example.com",
  fragment: nil,
  host: "www.example.com",
  path: nil,
  port: 80,
  query: "x[y]=",
  scheme: "http",
  userinfo: nil
}
```

### Expected behavior

Unsure. Maybe tolerating the square brackets is fine. If not, the ":" error is very misleading.

**Comment by schnittchen** [comment]
N.B. Phoenix generates such URLs:

```
MyApp.Router.Helpers.session_url(MyApp.Endpoint, :create, foo: %{bar: "baz"})
"http://localhost:4000/session?foo[bar]=baz"
```

**Comment by josevalim** [comment]
According to the specification, `[` and `]` are indeed not allowed. I think our option is to undeprecate URI.parse/1 and add a clearer distinction between them.

**Comment by josevalim** [comment]
About the unspecified location, can you please open up an issue in the OTP repo?

```erl
~/OSS/elixir[main]$ erl
Erlang/OTP 24 [erts-12.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.1  (abort with ^G)
1> uri_string:parse("http://localhost:4000/session?foo[bar]=baz").
{error,invalid_uri,":"}
```
