### ISSUE TITLE
Macro.to_string/1 drops square brackets in module attributes

### ISSUE THREAD

**Issue by arjan** [elixir-lang/elixir#11459]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  **1.13.0 / OTP 24**
* Operating system:  **Arch linux**

### Current behavior

Macro.to_string/1 drops the square brackets on a module attribute declaration.

```
iex(3)> Code.string_to_quoted!("@param [1]")  |> Macro.to_string()
"@param 1"
```
Note that it can be worked around with using `Macro.to_string/2`:

```
iex(7)> Code.string_to_quoted!("@param [1]")  |> Macro.to_string(fn _ast, s -> s end)
"@param([1])"
```
Although this gives a warning (#11373)

### Expected behavior

It would be expected that the result of `Macro.to_string` returns an equivalent AST when parsed again; with 1.13 this is not the case.

On Elixir 1.12 it works correctly:

```
iex(5)> Code.string_to_quoted!("@param [1]")  |> Macro.to_string()                                   
"@param([1])"
```

**Comment by josevalim** [comment]
Hi @doorgan, if you can take a look, it would be very appreciated. Otherwise I will investigate it in the next days. :)

**Comment by doorgan** [comment]
Sure, I'll take a look by the end of my day :)

**Comment by arjan** [comment]
Thanks all for this fast fix!
