### ISSUE TITLE
IEx outputs malformed docs for :queue.in/2

### ISSUE THREAD

**Issue by QuinnWilton** [elixir-lang/elixir#11463]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.14.0-dev (2c8a9dd) (compiled with Erlang/OTP 23)
* Operating system: macOS Big Sur 11.6

### Current behavior

When running `h :queue.in` within IEx, the docs are printed incorrectly:

![image](https://user-images.githubusercontent.com/285821/145328162-e7654e6a-bf5f-40e6-af68-4a294a8076d2.png)

### Expected behavior

I haven't investigated, but my suspicion is that the function name is causing the typespec to be rendered using the infix notation used for `Kernel.in/2`.

As contrast, consider the correctly rendered output for `:queue.out/1`:

![image](https://user-images.githubusercontent.com/285821/145328406-c777ad4b-8bbe-44b3-af5b-ef49b528f1be.png)

**Comment by josevalim** [comment]
@QuinnWilton thanks for the report!

This is definitely a bit surprising but I don't think it is wrong. If you were to write this spec in Elixir, that's precisely how you would write it. We could change this to show a regular `in(..., ...)` notation, but then if you copy and paste it, it is invalid code.

Plus fixing this may break other cases where `in` is defined in Elixir, unless we start checking the language, which I don't think is worth it.

For those reasons, I am more inclined to go with a "won't fix"/"unresolved".

Thoughts?

**Comment by QuinnWilton** [comment]
Ah, that makes sense! I was initially confused by the way it was being displayed, but your explanation makes sense, and I do think it's important to ensure that only valid code is being output.

Marking this as "won't fix" sounds reasonable to me.
