### ISSUE TITLE
Unicode issues with Elixir 1.13.0

### ISSUE THREAD

**Issue by marcelotto** [elixir-lang/elixir#11461]
After upgrading the [RDF.ex](https://github.com/rdf-elixir/rdf-ex) project to Elixir 1.13 some of the [official W3C test files](https://www.w3.org/2013/TurtleTests/) of the Turtle spec can no longer be parsed with the leex/yecc parsers due to Unicode issues. 

The issues must be related to the newest Elixir version, since I've tested it with the latest OTP version 24.1.7 but also with the exact OTP version I've used before (24.0.1) with Elixir 12.3 where everything worked fine.

There seem to be two error scenarios with different results. Here's the output of trying to read one of W3C test files from each of these two categories with Elixir 1.12.3:

```
iex(1)> RDF.Turtle.read_file("test/data/TURTLE-TESTS/prefix_with_non_leading_extras.ttl")
{:ok,
 #RDF.Graph<name: nil
  @prefix a·̀ͯ‿.⁀: <http://a.example/> .

  a·̀ͯ‿.⁀:s
      a·̀ͯ‿.⁀:p a·̀ͯ‿.⁀:o .
>}

iex(2)> RDF.Turtle.read_file("test/data/TURTLE-TESTS/LITERAL1_with_UTF8_boundaries.ttl")
{:ok,
 #RDF.Graph<name: nil
  @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
  @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
  @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

  <http://a.example/s>
      <http://a.example/p> "߿ࠀ࿿က쿿퀀퟿�𐀀𿿽񀀀󿿽􀀀􏿽" .
>}
```

Here's the result of running the same code with Elixir 1.13.0:

```
iex(1)> RDF.Turtle.read_file("test/data/TURTLE-TESTS/prefix_with_non_leading_extras.ttl")
{:error, "line 2: undefined prefix \"a·̀ͯ‿.⁀\""}

iex(2)> RDF.Turtle.read_file("test/data/TURTLE-TESTS/LITERAL1_with_UTF8_boundaries.ttl")
** (ArgumentError) argument error
    (stdlib 3.16.1) io.erl:99: :io.put_chars(:standard_io, [<<27, 91, 51, 51, 109, 27, 91, 51, 57, 109, 123, 27, 91, 48, 109, 27, 91, 51, 51, 109, 27, 91, 51, 54, 109, 58, 111, 107, 27, 91, 48, 109, 27, 91, 51, 51, 109, 27, 91, 51, 57, 109, 44, 27, 91, 48, 109, 27, 91, ...>>, 10])
```

Unfortunately I'm not yet able to reproduce an issue with these inputs outside of the leex/yecc parsers.

Noticeably, for the test files producing the argument errors the ExUnit formatter does not seem to be able to format the error.

```
** (UnicodeConversionError) invalid encoding starting at <<244, 143, 191, 34, 32, 46, 10, 62>>
    (elixir 1.13.0) lib/list.ex:997: List.to_string/1
    (ex_unit 1.13.0) lib/ex_unit/formatter.ex:344: anonymous fn/3 in ExUnit.Formatter.format_args/2
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_unit 1.13.0) lib/ex_unit/formatter.ex:340: ExUnit.Formatter.format_args/2
    (ex_unit 1.13.0) lib/ex_unit/formatter.ex:188: ExUnit.Formatter.format_exception/6
    (ex_unit 1.13.0) lib/ex_unit/formatter.ex:161: anonymous fn/7 in ExUnit.Formatter.format_test_failure/5
    (elixir 1.13.0) lib/enum.ex:1690: anonymous fn/2 in Enum.map_join/3
    (elixir 1.13.0) lib/enum.ex:4125: Enum.map_intersperse_list/3
    (elixir 1.13.0) lib/enum.ex:1690: Enum.map_join/3
    (ex_unit 1.13.0) lib/ex_unit/formatter.ex:160: ExUnit.Formatter.format_test_failure/5
    (ex_unit 1.13.0) lib/ex_unit/cli_formatter.ex:108: ExUnit.CLIFormatter.handle_cast/2
    (stdlib 3.16.1) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.16.1) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Here are all of the test files causing errors:

- [https://www.w3.org/2013/TurtleTests/LITERAL1_with_UTF8_boundaries.ttl](https://www.w3.org/2013/TurtleTests/LITERAL1_with_UTF8_boundaries.ttl)
- [https://www.w3.org/2013/TurtleTests/LITERAL2_with_UTF8_boundaries.ttl](https://www.w3.org/2013/TurtleTests/LITERAL2_with_UTF8_boundaries.ttl)
- [https://www.w3.org/2013/TurtleTests/LITERAL_LONG1_with_UTF8_boundaries.ttl](https://www.w3.org/2013/TurtleTests/LITERAL_LONG1_with_UTF8_boundaries.ttl)
- [https://www.w3.org/2013/TurtleTests/LITERAL_LONG2_with_UTF8_boundaries.ttl](https://www.w3.org/2013/TurtleTests/LITERAL_LONG2_with_UTF8_boundaries.ttl)
- [https://www.w3.org/2013/TurtleTests/prefix_with_PN_CHARS_BASE_character_boundaries.ttl](https://www.w3.org/2013/TurtleTests/prefix_with_PN_CHARS_BASE_character_boundaries.ttl)
- [https://www.w3.org/2013/TurtleTests/prefix_with_non_leading_extras.ttl](https://www.w3.org/2013/TurtleTests/prefix_with_non_leading_extras.ttl)

The first four with_UTF8_boundaries test files are causing the argument error (and `UnicodeConversionError`s in the tests), while the later two are causing the error tuples.

During research for what these test cases actually aim to test, I only found this explanation for the with_UTF8_boundaries ones in the [README of the W3C test suite](https://www.w3.org/2013/TurtleTests/README):

> The Turtle language uses UTF-8 encoding. The following tests include non-ascii characters:
> -  localName_with_assigned_nfc_bmp_PN_CHARS_BASE_character_boundaries
> -  localName_with_assigned_nfc_PN_CHARS_BASE_character_boundaries *
> -  localName_with_nfc_PN_CHARS_BASE_character_boundaries *
> -  labeled_blank_node_with_PN_CHARS_BASE_character_boundaries *
> -  LITERAL1_with_UTF8_boundaries *
> -  LITERAL_LONG1_with_UTF8_boundaries *
> -  LITERAL2_with_UTF8_boundaries *
> -  LITERAL_LONG2_with_UTF8_boundaries *
>
> Those marked with a * include characters with codepoints greater than U+FFFD and are thus expressed as a pair of surrogate characters when represented in UCS2.
> 

While searching for changes in Elixir 1.13 that could be causing this, I found this PR that could be a possible cause: #11310 (although I admittedly don't really grasp it, at least it seems related)

**Comment by josevalim** [comment]
It is a bug on String.slice/2. I am just not sure which one.

**Comment by marcelotto** [comment]
Thank you for the incredibly fast fix and your great work in general.
