### ISSUE TITLE
iex Bracket Matches Inside Strings

### ISSUE THREAD

**Issue by boone** [elixir-lang/elixir#11472]
Minor issue I noticed while typing characters for [Advent of Code Day 10](https://adventofcode.com/2021/day/10). 😄 Apologies if this is some artifact of the command line that cannot be improved.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.13
* Operating system: macOS 11.6.1

### Current behavior

Inside `iex`, if you open with some kind of bracket character, e.g. `[({` and then inside, include a string or charlist that contains the closing character, `iex` highlights the starting character as if the section has been properly closed.

Start by typing: `foo("bar`, now type `)` and it will highlight the leading `(`. If you continue to type with `")`, this correct closing parenthesis will not trigger the highlight with the opening parenthesis.

### Expected behavior

The opening character should not be highlighted until a closing character is typed, outside the context of a string or charlist. Livebook seems to do this correctly already.

**Comment by josevalim** [comment]
This is an Erlang shell behaviour and unfortunately we can't tweak it without changes upstream. At the same time, this can be handy inside strings (such as when writing markdown) or most times we use those characteres. So I am not sure I would disable it even if we could. The case of the Advent of Code, where have mostly bad pairs, is rather the exception than the rule! :D

But there is no problem in checking, thanks for the report!

**Comment by boone** [comment]
Thanks for the clarification! (and also for the AoC Twitch streams)
