### ISSUE TITLE
Match in with clause broke since upgrading to 1.13

### ISSUE THREAD

**Issue by Nickforall** [elixir-lang/elixir#11489]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.13.0, OTP 22
* Operating system: MacOS 12.0

### Current behavior

Our project stopped compiling on 1.13, I don't know if the code below is valid elixir code that somehow just compiled, but I wanted to file this issue anyways in case it is valid code and it's a regression :)

```
iex(1)> with %{} <- x = Map.new() do
...(1)> IO.inspect(x)
...(1)> end
** (CompileError) iex:2: undefined function x/0 (there is no such import)
```

### Expected behavior

On 1.12 it does this

```
iex(2)> with %{} <- x = Map.new() do
...(2)> IO.inspect(x)
...(2)> end
%{}
%{}
```

**Comment by josevalim** [comment]
It was a bug that has been addressed in v1.13. Matches on `with` are never expected to leak variables and this was an unfortunate exception. So unfortunately the code has to be fixed. Thanks for reporting and double checking! :heart:
