### ISSUE TITLE
`i` helper in IEX is showing the wrong information about non-enumerable anonymous functions

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11497]
```elixir
iex(8)> i fn(x, y, z, y) -> nil end

Implemented protocols
  Enumerable, IEx.Info, Inspect
```

this is only valid for arity-2 anoynmous functions

**Comment by josevalim** [comment]
Yes. The protocol is implemented for all functions, we don’t know from outside which one works.

but that’s for all protocols. A list of atoms can’t be converted to string but any list shows up as String.Chars.
