### ISSUE TITLE
Publish source code checksum for releases

### ISSUE THREAD

**Issue by deepankar-j** [elixir-lang/elixir#11495]
Currently, releases contain checksums for the precompiled assets, but not the source code zip/tar.gz files. 

https://github.com/elixir-lang/elixir/releases

Would it be possible to publish the checksum for those files?  It would help ensure integrity of the source we're compiling and running.

**Comment by ericmj** [comment]
It is GitHub that creates those files. We could download the files and get the checksum for them after the release has been created and then update the release.  But if it's not the creator of the files that adds the checksum then it somewhat defeats the purpose of the checksum in the first place.

**Comment by deepankar-j** [comment]
Ah, good to know.  I guess I'll dig through GitHub's documentation to figure out how to obtain the checksum.

It seems like a waste for any consumer of those assets to have to go through figuring out the checksum or forego doing a checksum altogether.

**Comment by josevalim** [comment]
Yes, exactly. This a feature request for GitHub. :) I think it could be a good idea for them to include the checksums. Please follow up with them, thanks!

**Comment by deepankar-j** [comment]
That's fair, @josevalim.  I did a bit of digging for GitHub issues and it seems there isn't much traction from GitHub for supporting checksums for source code downloads.

On a side note, it looks like OTP releases include their own source code tar.gz files + associated MD5/SHA256 hashes.

For the benefit of others, my current solution is to clone the repo instead to get the source:

```
git clone --depth 1 https://github.com/elixir-lang/elixir.git -b v1.13.1
```
