### ISSUE TITLE
IEx: Guess argument names in function signatures based on specs when no argument name provided

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11504]
I am posting here, but this applies to ExDoc as well:

The following code will generate
```elixir
def foo(1), do: "one"
```

in IEx:

```elixir
iex(1)> h Typespecs.foo

                                 def foo(arg1)                                  
``` 

I realized that we can do better when a spec is provided,

```elixir
@spec foo(integer()) :: String.t()
def foo(1), do: "one"
```

we could show:

                                 def foo(integer)

If multiple specs are provided, we take the first spec (same as we do with multiple function clauses)

**Comment by josevalim** [comment]
I understand how it can be a benefit but I don’t want to couple the code with specs, especially given specs are annotations. Furthermore, the best argument names are unlikely to be the type.

On a positive note, most places that show docs also show specs, so you do get that information too.

**Comment by eksperimental** [comment]
> especially given specs are annotations. Furthermore, the best argument names are unlikely to be the type.

True, and if a am not mistaken we did that ages ago in ExDoc and we decided to ditch it, now that you mention this.
