### ISSUE TITLE
File.rm_rf\1 may fail on Windows directories with internal symlinks

### ISSUE THREAD

**Issue by eteeselink** [elixir-lang/elixir#11501]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
    * Erlang/OTP 24 [erts-12.0] [source] [smp:8:8] [ds:8:8:10] [async-threads:1]
    * Elixir 1.13.1 (compiled with Erlang/OTP 22)
* Operating system: Windows 10 Build 19042

### Current behavior

When I run `File.rm_rf` on a path that internally contains symlinks, I get a `not owner` error, eg:

```
 ** (File.Error) could not remove files and directories recursively from "c:/code/_oss/phoenix/tmp/iKuBx8Si+O/mix_phoenix_digest": not owner
```

And only about half the directory contents is actually erased.

### Expected behavior

For the entire directory to disappear

### Steps to reproduce

I was trying to hack on Phoenix. I did `git clone`, `mix deps.get` and `mix test` from Phoenix master. I got a few failing tests, some about phx.auth that I decided to skip, but 2 failing Mix.Tasks.Phx.DigestTest tests looked fixable so I had a look.

To repro:
- Get a Windows box / VM
- Clone the Phoenix repo, `mix deps.get`
- `mix test .\test\mix\tasks\phx.digest_test.exs`
- the above error should show

I'm not going to be surprised if the same error does not show up everywhere, because directory listing order might influence it (see below) and I'm not sure that's deterministic. It fails consistently on my box though.

### A guess

Here's my suspicion as to what's going on:
- This test creates a little phoenixy file tree inside `<repo>\tmp\<uniqid>\` which includes an internal symlink:
    - mix_phoenix_digest\
        - priv
        - _build\test\lib\phoenix\priv -> \mix_phoenix_digest\priv (SYMLINK)
- Elixir's `File.rm_rf\1` recursively goes through all the files, but deletes `\mix_phoenix_digest\priv` before it gets to  `\mix_phoenix_digest\_build` and its children. This makes the ` _build\test\lib\phoenix\priv` symlink a broken symlink
- For reasons beyond me (but likely related to Windows's shitty symlink support), Windows won't let Elixir delete this broken symlink. No idea why "not owner" is the error given, I confirmed that the same user is the owner if every file, directory and symlink in there.

### Workaround

- The actual `rm_rf` in this case is called from Phoenix's `MixHelper.in_tmp\2` function.
- If I replace the line with `File.rm_rf!(path)` by a call to Erlang's new-ish `del_dir_r`, ie `:file.del_dir_r(IO.chardata_to_string(path))`, then the test magically passes and the given tmp directory is nicely cleaned up.

I don't know what `:file.del_dir_r` does differently and haven't looked deeper. I had hoped to fix a Phoenix test but I think going deep into Elixir's OS code is a bit too far down the rabbit hole for tonight :)

**Comment by josevalim** [comment]
Thanks for the report!

I took a look at `del_dir_r` implementation and it does not have any special code to handle symlinks. I pushed a similar implementation to Elixir and I did get errors about symlinks, including the famous `not_owner`: https://github.com/elixir-lang/elixir/runs/4571190787?check_suite_focus=true

**Comment by josevalim** [comment]
@eteeselink I think I might have figured out by merging both Elixir and Erlang solutions. Can you please give latest main a try and let me know if it works? If you want me to precompile it for you, let me know!

**Comment by eteeselink** [comment]
I will!

Last I checked (a few years ago) compiling Elixir from main was super easy, so I think I can make do without the precompile. As before, this might take a few days but I'll be sure to double check + try to break it etc.

**Comment by eteeselink** [comment]
Damn! I'm sad to report that the change do not seem to fix the test.

Here's a console log, first with v1.13.1 and then with latest main:

```
C:\code\_oss\phoenix>mix test test\mix\tasks\phx.digest_test.exs
Compiling 1 file (.ex)


  1) test digests and compress files (Mix.Tasks.Phx.DigestTest)
     c:/code/_oss/phoenix/test/mix/tasks/phx.digest_test.exs:13
     ** (File.Error) could not remove files and directories recursively from "c:/code/_oss/phoenix/tmp/Kjz3cleFah/mix_phoenix_digest": not owner
     stacktrace:
       (elixir 1.13.1) lib/file.ex:1292: File.rm_rf!/1
       installer/test/mix_helper.exs:25: MixHelper.in_tmp/2
       test/mix/tasks/phx.digest_test.exs:14: (test)



  2) test digests and compress files without the input path (Mix.Tasks.Phx.DigestTest)
     c:/code/_oss/phoenix/test/mix/tasks/phx.digest_test.exs:22
     ** (File.Error) could not remove files and directories recursively from "c:/code/_oss/phoenix/tmp/NosnttpKhI/mix_phoenix_digest_no_input": not owner
     stacktrace:
       (elixir 1.13.1) lib/file.ex:1292: File.rm_rf!/1
       installer/test/mix_helper.exs:25: MixHelper.in_tmp/2
       test/mix/tasks/phx.digest_test.exs:23: (test)

..

Finished in 0.2 seconds (0.00s async, 0.2s sync)
4 tests, 2 failures

Randomized with seed 497474

C:\code\_oss\phoenix>set PATH=c:\code\_oss\elixir\bin;%PATH%

C:\code\_oss\phoenix>elixir --version
Erlang/OTP 24 [erts-12.0] [source] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.14.0-dev (0ec6cf8) (compiled with Erlang/OTP 24)

C:\code\_oss\phoenix>mix test test\mix\tasks\phx.digest_test.exs
==> jason
  [SKIP compiling libs]
Generated phoenix app
.

  1) test digests and compress files without the input path (Mix.Tasks.Phx.DigestTest)
     c:/code/_oss/phoenix/test/mix/tasks/phx.digest_test.exs:22
     ** (File.Error) could not remove files and directories recursively from "c:/code/_oss/phoenix/tmp/VjW0psPDSJ/mix_phoenix_digest_no_input": file already exists
     stacktrace:
       (elixir 1.14.0-dev) lib/file.ex:1289: File.rm_rf!/1
       installer/test/mix_helper.exs:25: MixHelper.in_tmp/2
       test/mix/tasks/phx.digest_test.exs:23: (test)



  2) test digests and compress files (Mix.Tasks.Phx.DigestTest)
     test/mix/tasks/phx.digest_test.exs:13
     ** (File.Error) could not remove files and directories recursively from "c:/code/_oss/phoenix/tmp/FxWZi+Vz+V/mix_phoenix_digest": file already exists
     code: in_tmp @output_path, fn ->
     stacktrace:
       (elixir 1.14.0-dev) lib/file.ex:1289: File.rm_rf!/1
       installer/test/mix_helper.exs:25: MixHelper.in_tmp/2
       test/mix/tasks/phx.digest_test.exs:14: (test)

.

Finished in 0.1 seconds (0.00s async, 0.1s sync)
4 tests, 2 failures

Randomized with seed 723499

C:\code\_oss\phoenix>
```

just to sanity check, I confirmed that your code changes were in the file.ex that I just compiled Elixir from (ie that I cloned the right branch etc). Not able to dive deeper right now, unfortunately. Will be happy to run more tests. Also wow @ how quickly Elixir compiles and tests!
