### ISSUE TITLE
function_exported? is not working as expected

### ISSUE THREAD

**Issue by juancgalvis** [elixir-lang/elixir#11524]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```shell
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]

IEx 1.13.1 (compiled with Erlang/OTP 24)
```
* Operating system:  `Linux and Mac OS Catalina 10.15.7`

### Current behavior

When a library that I have been using in my project tries to check if a module exists it does not return the correct value.
[source](https://github.com/rrrene/credo/blob/master/lib/credo/execution/task/initialize_plugins.ex)

```elixir
    module_loaded? = function_exported?(mod, :__info__, 1)

    if module_loaded? do
      exec
      |> Execution.set_initializing_plugin(mod)
      |> mod.init()
      |> Execution.ensure_execution_struct("#{mod}.init/1")
      |> Execution.set_initializing_plugin(nil)
    else
      Execution.halt(
        exec,
        "Plugin module `#{Credo.Code.Module.name(mod)}` is not available and could not be initialized."
      )
    end
  end
```

The programs prints this error: 
```
** (credo) Plugin module `CredoSonarqube` is not available and could not be initialized.
```

I have modified the source and added some debugging code, in this case I call the "non exported" function and it works, but the `function_exported?/3` returns me that the function is not exported.

```elixir
    module_loaded? = function_exported?(mod, :__info__, 1)
    IO.puts "Loaded #{module_loaded?}"
    IO.inspect mod.__info__(:attributes)
```

The programs prints this error: 
```
Loaded false
[vsn: [133661204301518338321556655237502500826]]
```

### Expected behavior

I expect that the function `function_exported?/3` returns me the real value

**Comment by josevalim** [comment]
As the documentation says, `function_exported?/3` will not load the module:

> Note that this function does not load the module in case it is not loaded. Check Code.ensure_loaded/1 for more information.
>
> https://hexdocs.pm/elixir/Kernel.html#function_exported?/3

Invoke `Code.ensure_loaded?/1` before as necessary!
