### ISSUE TITLE
Log.debug and friends need to update the docs

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11546]
Currently the function signatures are like:

`debug(message_or_fun, metadata \\ [])`

If these functions were not a macro, we could spec them using this type:
`@type message_or_fun :: binary() | 0_arity_fun :: (-> type)  | map() | keyword() | list() |  iolist()`

I think these need to be documented, as it is inaccurate just to say "message_or_fun"

**Comment by josevalim** [comment]
I would say they are OK. It depends on what you mean by `message`. If you consider message to be both unstructured (iodata) and structured (map, keyword), it is fine.

The other thing is that is we can't capture all types as the argument name, nor it is the job of the argument name. Perhaps we could name it `message_or_data_or_fun` but I am not sure if that is really helpful. Again, it depends on what you understand as `message`. :)

**Comment by eksperimental** [comment]
Well, this issue is not about creating a spec, but documenting what is spected.
As of now the only "documentation" is the warning message you get when you pass the wrong data type.

```
iex(8)> Logger.info(:yay)          
warning: passing :yay to Logger is deprecated, expected a map, a keyword list, a binary, or an iolist
  (logger 1.13.1) lib/logger.ex:819: Logger.__do_log__/4
  (stdlib 3.16.1) erl_eval.erl:685: :erl_eval.do_apply/6
  (elixir 1.13.1) src/elixir.erl:289: :elixir.recur_eval/3
  (elixir 1.13.1) src/elixir.erl:274: :elixir.eval_forms/3
  (iex 1.13.1) lib/iex/evaluator.ex:310: IEx.Evaluator.handle_eval/3
  (iex 1.13.1) lib/iex/evaluator.ex:285: IEx.Evaluator.do_eval/3

:ok

08:31:14.544 [info]  yay
```
