### ISSUE TITLE
Nudge towards a common solution for a "do" expression SyntaxError

### ISSUE THREAD

**Issue by pdgonzalez872** [elixir-lang/elixir#11551]
### Environment

Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Interactive Elixir (1.13.0-dev) - press Ctrl+C to exit (type h() ENTER for help)

### Current behavior

Hi!

I'm reaching out about something that may add some value. I personally use
`with` a lot and sometimes I forget a trailing comma when moving functions
around in the `with` statement. I know that the error above means that I very likely 
forgot a trailing comma in a `with`, but the error doesn't nudge me to it despite
being completely correct in telling me why the error happened.

This is the current behavior:

```
~ :> iex
iex(1)> with true <- 1 == 1, do
** (SyntaxError) iex:1:22: unexpected reserved word: do. In case you wanted to write a "do" expression, you must either use do-blocks or separate the keyword argument with comma. For example, you should either write:

    if some_condition? do
      :this
    else
      :that
    end

or the equivalent construct:

    if(some_condition?, do: :this, else: :that)

where "some_condition?" is the first argument and the second argument is a keyword list

iex(1)>
```

### Expected behavior

A note/hint saying this SyntaxError could be a trailing comma before the `do`
in a `do` expression. That'd be great and think it would be a helpful nudge to
users (mostly newcomers) that may not haven't gotten used to/know what the
error could mean.

```
iex(1)> if true, do
** (SyntaxError) iex:1:10: unexpected reserved word: do. In case you wanted to write a "do" expression, you must either use do-blocks or separate the keyword argument with comma. For example, you should either write:

    if some_condition? do
      :this
    else
      :that
    end

or the equivalent construct:

    if(some_condition?, do: :this, else: :that)

where "some_condition?" is the first argument and the second argument is a keyword list.

** Note:

You may see this error if you forget a trailing comma before the "do" in a "do" expression.
This is common when using a `with` statement or a `for` comprehension spanning multiple lines.
If this is the case, please verify it is contructed correctly.

iex(1)>
```

As usual, feel free to discard the changes here if you want to, no hard
feelings! Thanks for your work! ❤️

**Comment by whatyouhide** [comment]
Closing in favor of the PR #11552, we can keep the discussion going in there 👍 Thanks @pdgonzalez872! 💟
