### ISSUE TITLE
Keyword.validate has unintended or undocumented behaviour and lacks test

### ISSUE THREAD

**Issue by schnittchen** [elixir-lang/elixir#11563]
### Environment

Elixir 1.13.1

### Current behavior

`Keyword.validate([a: 1, a: 2], [:a])` returns an error (`{:error, [:a]}`). There is no test around this behaviour (in fact there is no "happy path" test for `Keyword.validate` in `keyword_test.exs`).

### Expected behavior

I was surprised by the failed validation, depending on use case this might be considered right or wrong. The documentation is silent about this. If this is considered the right behaviour, it should be made clear in the documentation, and there should be a test for it.

Note that people might depend on this behaviour, potentially locking the language in w.r.t. this function. As an example, since a (per `validate/2`) valid keyword list can only contain the given keys and each key can appear only once, this

```
Keyword.validate!(opts, [:a, :b])
2 = Enum.count(opts)
```

would ensure that `opts` has exactly the two keys (NB this is a semantics that I had originally expected from `validate/2` and that I miss)

**Comment by josevalim** [comment]
Unless said otherwise, `Keyword` is meant to work the same as `Map`, especially for functions that exist in both. So I would say the current behaviour is correct. I will push tests.

**Comment by schnittchen** [comment]
Thank you :heart:
