### ISSUE TITLE
Pipe operator and multiple parameters

### ISSUE THREAD

**Issue by edgurgel** [elixir-lang/elixir#1156]
Acording to Kernel doc:

``` elixir
[1,[2],3] |> List.flatten |> Enum.map(&1 * 2)
```

and

``` elixir
Enum.map(List.flatten([1,[2],3]), &1 * 2)
```

Are the same. Implicitly the output of List.flatten is given to the first argument.

Would be too crazy or unreadable if we could pass the argument position? Something like:

``` elixir
[1,[2],3] |> List.flatten |>2 My.func(&1 * 2)
```

And the expression would translate to:

``` elixir
My.func(&1 * 2, List.flatten([1,[2],3]))
```

Too confusing?

**Comment by rebelwarrior** [comment]
I second @alco,  I was confused by `string |> Regex.match?` not working as expected. Either `_` or `&1` are good options. I like the later just cause it is in the space of argument goes here, where `_` seem to be for something along 'placeholder'.

**Comment by ericmj** [comment]
Please don't resurrect old issues. Use the mailing list for feature proposals.

**Comment by amadeu01** [comment]
@josevalim  Wouldn't be useful to have some macro for converting functions with arity greater than 1 to a combined monad?

From swift prelude 
https://github.com/pointfreeco/swift-overture

```swift
let stringWithEncoding = flip(curry(String.init(data:encoding:)))
// (String.Encoding) -> (Data) -> String?

let utf8String = stringWithEncoding(.utf8)
// (Data) -> String?
```

Or from haskell [curry](http://hackage.haskell.org/package/base-4.12.0.0/docs/Prelude.html#v:curry)

Using curry, wouldn't in certain way resolve this?
