### ISSUE TITLE
Should we auto-link to anonymous functions?

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11573]
I am editting some docs, and I see the convenient need to automatically link anonymous functions for examples (from the Enum.sort/2 docs)

Original

    `sort/2` allows a developer to pass `:asc` or `:desc` as the sorter, which is a convenience for `<=/2` and `>=/2` respectively.

My correction changes this as the convenince is for `&<=/2` and  `&>=/2`

    `sort/2` allows a developer to pass `:asc` or `:desc` as the sorter, which is a convenience for `&<=/2` and `&>=/2` respectively.

but then don't get automatically linked, so I have to write them like:

    `sort/2` allows a developer to pass `:asc` or `:desc` as the sorter, which is a convenience for [`&<=/2`](`<=/2`) and [`&>=/2`](`>=/2`) respectively.

The other question is whether we should auto-link in cases like: `&Atom.to_string(&1)`

**Comment by wojtekmach** [comment]
Should this be an ExDoc issue instead?

If we accept this, do we autolink `` `Atom.to_string(:foo)` `` too? The latter is pretty popular in Erlang codebases, e.g.: ``Equivalent to `(...)` ``.

I think all three things (`` `&<=/2` ``, `` `&Atom.to_string(&1)` ``, and `` `Atom.to_string(:foo)` ``) would be kinda nice but it increases complexity so I probably wouldn't, especially that we have the escape hatch of custom links.

**Comment by josevalim** [comment]
We should not. It will add another way of doing things, so we can start seeing both `is_atom/1` and `&is_atom/1` in docs. Plus we already support ``[...](`>=/2`)` for custom linking.

**Comment by eksperimental** [comment]
> Should this be an ExDoc issue instead?
> 
> If we accept this, do we autolink `` `Atom.to_string(:foo)` `` too? The latter is pretty popular in Erlang codebases, e.g.: `` Equivalent to `(...)` ``.
> 
> I think all three things (`` `&<=/2` ``, `` `&Atom.to_string(&1)` ``, and `` `Atom.to_string(:foo)` ``) would be kinda nice but it increases complexity so I probably wouldn't, especially that we have the escape hatch of custom links.

I'm so sorry, I thought i was posting it in ExDoc.

**Comment by eksperimental** [comment]
> Should this be an ExDoc issue instead?
> 
> If we accept this, do we autolink `` `Atom.to_string(:foo)` `` too? The latter is pretty popular in Erlang codebases, e.g.: `` Equivalent to `(...)` ``.
> 
> I think all three things (`` `&<=/2` ``, `` `&Atom.to_string(&1)` ``, and `` `Atom.to_string(:foo)` ``) would be kinda nice but it increases complexity so I probably wouldn't, especially that we have the escape hatch of custom links.

Personally I would only support auto-linking `&<=/2`,
I do not agree with @josevalim 's point: if people start abusing `&<=/2` to link to `<=/2` it is up to them, as they are two totally different things.
