### ISSUE TITLE
Warn if any of True, False, and Nil aliases are used

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11586]
It can be a common mistake that may go otherwise unnoticed. However, `Boolean.True` should still be fine. In a nutshell, we should warn when `True` resolves to `:"Elixir.True"` and similar.

**Comment by fmterrorf** [comment]
Hi Jose! Do you accept PRs for this issue?

**Comment by wojtekmach** [comment]
I am not José but I know for a fact that contributions to open issues, especially tagged v1.14, are definitely welcome.
