### ISSUE TITLE
Why was the reference to Erlang's compile options removed from the documentation?

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#11589]
In commit https://github.com/elixir-lang/elixir/commit/69df6543fb922287fae7fd8a5e4aee805b9d19d4, as part of the release of Elixir v1.11.0-rc.0, the link to the Erlang [`:compile` module](https://www.erlang.org/doc/man/compile.html) / compile options was removed from the module-documentation of the `Module` module.

Without context it seems weird to remove this reference. Why was it removed?

**Comment by josevalim** [comment]
Because before we were used to share the lint pass with Erlang, which is where many of the options come from, and now we don't. So there is very little shared options now. I would prefer to explicitly document them. :)

**Comment by Qqwy** [comment]
I see! Thanks for clearing that up. :green_heart: 

Should we then document more features? 
For instance, `@compile :inline`, `@compile {:inline_size, integer}` and `@compile :inline_list_funcs` might warrant documenting.

If you give me the green light, I'll send a PR.

**Comment by josevalim** [comment]
We can document the first two but I wouldn't document the third as it does not apply to Enum/List, only `:lists`. :)
