### ISSUE TITLE
Should Code.format_string!/2 emit warnings?

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11595]
`Code.format_string!/2` may emit warnings for stuff like `fn -> end`. The formatted code will automatically fix it to `fn -> nil end`, so the warnings are irrelevant. Should we just disable those warnings altogether? Or should we have an option for them?

**Comment by whatyouhide** [comment]
@josevalim I don't think warnings belong in `Code.format_string!/2` so I'm definitely in favor of taking them away. I would only consider leaving them available through an opt-in option in case we didn't have a way to get a piece of code and get warnings on its syntactic part. Do we have a way to do that that doesn't also compile the code?
