### ISSUE TITLE
mix release --werl usage not configurable

### ISSUE THREAD

**Issue by joeapearson** [elixir-lang/elixir#11596]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.13.0
* Operating system: Windows containers

### Current behavior

I've created a release using `mix release` and have then packaged it into a windows container.

When I execute `bin/app remote` from within the container, nothing happens and I am returned to a command prompt.

### Expected behavior

Able to perform release commands as documented from within a container, e.g. `bin/app.bat remote` etc.

### Investigations so far

I have determined this is because of the assumed `--werl` flag, which won't work in container environments since it attempts to create a new window.  For example:

https://github.com/elixir-lang/elixir/blob/main/lib/mix/lib/mix/tasks/release.init.ex#L188 (there are a couple of other references in the init file).

### Workaround

What I have done is to use the [module overlays](https://hexdocs.pm/mix/Mix.Tasks.Release.html#module-overlays) feature to create my own `app.bat` file which removes references to `--werl`.  I am now able to perform `bin/app remote` and I now get as far as an IEx shell .  Hooray.

### Where it comes unstuck

However... it appears that all is not well.  When I run `bin/app.bat remote` for example, I am presented with this output:

```
.\app.bat remote
warning: the --remsh option will be ignored because IEx is running on limited shell
Interactive Elixir (1.13.0) - press Ctrl+C to exit (type h() ENTER for help)
…
```

From my understanding of [module remote shells](https://hexdocs.pm/iex/1.13/IEx.html#module-remote-shells) it seems that the `--remsh` flag is rather crucial, so my assumption is that it's not quite working as expected.

Can anyone offer any advice as to:

* Is the printed warning a big problem or just noise?
* If the latter, can I fix or suppress it somehow?
* What would be the best method for making the use of `--werl` configurable in a future MR for other users?

**Comment by josevalim** [comment]
It is a big problem. I am afraid you are not actually connected to the remote node (try executing any code from your app and see if it works).

**Comment by joeapearson** [comment]
> I am afraid you are not actually connected to the remote node

As I suspected.  Any advice on where to look next?

**Comment by josevalim** [comment]
Unfortunately I don't think there is an alternative. :( I think at the moment it is not possible to establish a remote shell within a Windows container. Perhaps if you use WSL. The good news is that Windows is finally moving to virtual terminals (instead of their own console APIs), which should bring Unix parity in the long term, so in the future the Erlang remote shell will work directly without `--werl`. But that's an Erlang change, unfortunately there is not much we can do here. :(

**Comment by joeapearson** [comment]
Thanks for the time and thoughts @josevalim !
