### ISSUE TITLE
Typo in Supervisor docs

### ISSUE THREAD

**Issue by MeerKatDev** [elixir-lang/elixir#11600]
On the Supervisor docs it shows
```
def child_spec(arg) do
  %{
    id: Stack,
    start: {Stack, :start_link, [arg]}
  }
end
```
and in the errors:
```
If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end
```

Aren't those brackets around `opts` and `arg` (which might be better written as `args` I guess) optional?

**Comment by MeerKatDev** [comment]
It doesn't depend, really. I have this supervisor:
```
...
def start(_type, _args) do
  port = String.to_integer(System.get_env("PORT", "4040"))
  
  children = [
	  {ExampleModule, [port]}
  ]
...
```

and if I define `child_spec` like this
```
  def child_spec(args) do
    %{
      id: __MODULE__,
      start: {__MODULE__, :start_link, [args]}
    }
  end
```
it gives this error
```
** (FunctionClauseError) no function clause matching in :inet_tcp.getserv/1
  (kernel 8.2) inet_tcp.erl:55: :inet_tcp.getserv([4040])
```
instead, it works if I remove the parenteses in the child_spec. 

If you notice, in the docs you write this:
```
children = [
  {Stack, [:hello]}
]
```
and then this
```
def child_spec(arg) do
  %{
    id: Stack,
    start: {Stack, :start_link, [arg]}
  }
end
```
which won't work.

When calling a function with the tuple mod/fun/args, we never send one argument, but instead a list of arguments, even if there is a single argument. Why change it for this case only? Now I'm referring to the way `child_spec` is documented.

**Comment by josevalim** [comment]
That's because you are passing a list in the childspec:

    {ExampleModule, [port]}

If you pass it as a single argument, then it will arrive as a single argument in `start_link`:

    {ExampleModule, port}

**Comment by MeerKatDev** [comment]
@josevalim I'm doing as it's written in the docs

**Comment by josevalim** [comment]
The issue is not in the Elixir docs, the issue is in the first code snippet using the port. Where is said code snippet coming from?

**Comment by MeerKatDev** [comment]
The last two code snippets I gave are [copied from the Supervisor docs](https://hexdocs.pm/elixir/1.13/Supervisor.html#module-child_spec-1), which I use to give the example above. I don't understand why it's so difficult to see this.

**Comment by josevalim** [comment]
The docs are correct. The convention is to pass a single argument to child_spec which makes it to start_link. You can pass a list of arguments, but that's not the convention (although you are welcome to change it).

You can either change the first code snippet to adhere to the convention or not follow the convention, so the docs no longer apply.

I am not sure if there are other ways I can explain this, so I will bow out of this discussion. Feel free to start a discussion on ElixirForum if you want a different perspective.

**Comment by MeerKatDev** [comment]
There are two separate code snippets involved in the docs I'm pointing to:

```
children = [
  {Stack, [:hello]}
]
```
and then this
```
def child_spec(arg) do
  %{
    id: Stack,
    start: {Stack, :start_link, [arg]}
  }
end
```
It's clear as day that if what you say it's true, one or the other is correct, not both. In the first you are passing a list, in the second you assume a single argument.

**Comment by josevalim** [comment]
In the first I am passing a list because the initial argument is a list. Your initial argument is a port, an integer, and therefore it should not be wrapped in a list.

**Comment by josevalim** [comment]
To be as clear as I can possibly be. In the stack case, the stack is represented as a list, so there is still one single argument, and said argument is a list itself. When I pass a stack of `[]`, `[:foo, :bar]`, or `[:foo, :bar, :baz]`, they will all arrive as similar lists in the process.

In your case, you want a port, an integer, then therefore you should pass a port, an integer, and not a list. This is precisely what I said in my second reply to this thread.
