### ISSUE TITLE
List destruction

### ISSUE THREAD

**Issue by erdalturan** [elixir-lang/elixir#11605]
### Precheck

On the iex shell an additional definition named irrelevant from the match list calls the last value
I defined below "v" not a defination in the list.
### Environment

* Elixir & Erlang/OTP versions(OTP 24, erts-12.2.1, elixir 1.13.0: 
* Operating system: Linux Ubuntu

### Current behavior
`Interactive Elixir (1.13.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> clear

iex(2)> b=[1,2,3]
[1, 2, 3]
iex(3)> [a,b,c]=b
[1, 2, 3]
iex(4)> a
1
iex(5)> b
2
iex(6)> c
3
iex(7)> v
3
iex(8)> v
3
iex(9)> d
** (CompileError) iex:9: undefined function d/0 (there is no such import)
`
Include code samples, errors and stacktraces if appropriate.
If reporting a bug, please include the reproducing steps.

### Expected behavior

A short description on how you expect the code to behave.

**Comment by josevalim** [comment]
Correct. It is a convenience for reading the value of the last cell. It is defined here: https://hexdocs.pm/iex/IEx.Helpers.html#v/1
