### ISSUE TITLE
Documentation incoherence

### ISSUE THREAD

**Issue by RaymondLoranger** [elixir-lang/elixir#11609]
The documentation for [start_link/3](https://hexdocs.pm/elixir/DynamicSupervisor.html#start_link/3) is incoherent.
The 1st parameter is _mod_ while the documentation speaks of a given _module_.

IMO, the function head should say _module_ instead of _mod_ and the doc should say `init_arg` instead of `arg`.

**Comment by josevalim** [comment]
Thanks for the report, fixed! You are welcome to send a PR next time if you prefer too!
