### ISSUE TITLE
StringIO fails to start under supervisor

### ISSUE THREAD

**Issue by aaronrenner** [elixir-lang/elixir#11619]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  Elixir 1.13.2, OTP 24
* Operating system: PopOS 21.10

### Current behavior

The documentation for `StringIO` mentions a `child_spec/1` function which makes me think I should be able to start the `StringIO` under a supervisor (or with `start_supervised/1`. Unfortunately when I try to have the supervisor start it, the following exception is raised.

```
     ** (RuntimeError) failed to start child with the spec StringIO.
     Reason: an exception was raised:
         ** (UndefinedFunctionError) function StringIO.start_link/1 is undefined or private
             (elixir 1.13.2) StringIO.start_link([])
             (stdlib 3.17) supervisor.erl:414: :supervisor.do_start_child_i/3
             (stdlib 3.17) supervisor.erl:400: :supervisor.do_start_child/2
             (stdlib 3.17) supervisor.erl:706: :supervisor.handle_start_child/2
             (stdlib 3.17) supervisor.erl:455: :supervisor.handle_call/3
             (stdlib 3.17) gen_server.erl:721: :gen_server.try_handle_call/4
             (stdlib 3.17) gen_server.erl:750: :gen_server.handle_msg/6
             (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Expected behavior

I'd expect to either be able to start a `StringIO` via a supervisor (where `child_spec` calls `open/3`) or the `child_spec` function shouldn't exist in the documentation.

**Comment by whatyouhide** [comment]
@aaronrenner how are you starting the `StringIO` under the supervisor?

**Comment by josevalim** [comment]
The `child_spec` function was added by `use GenServer` but I really don't think it is supported in StringIO case. We should remove the automatically generated function.
