### ISSUE TITLE
mix project name `pa` not working as expected. Error: ** (Mix) Could not start application pa: {:bad_environment_value,

### ISSUE THREAD

**Issue by seungjin** [elixir-lang/elixir#11613]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  Elixir 1.13.2 (compiled with Erlang/OTP 22)
* Operating system: Linux(Fedora) 5.15.16-100.fc34.x86_64

### Current behavior

mix new with its name `pa` . Then `mix test` or `iex -S mix` complains `** (Mix) Could not start application pa: {:bad_environment_value,`

```
$ mix new pa
..
..
$ cd pa
$ mix test
Compiling 1 file (.ex)
Generated pa app

12:55:50.650 [error] application_controller: syntax error before: '/': /var/home/seungjin/.elixir/1.13/bin/../lib/eex/ebin

=ERROR REPORT==== 8-Feb-2022::12:55:50.790188 ===
application_controller: syntax error before: '/': /var/home/seungjin/.elixir/1.13/bin/../lib/eex/ebin

** (Mix) Could not start application pa: {:bad_environment_value, '/var/home/seungjin/.elixir/1.13/bin/../lib/eex/ebin'}
```

### Expected behavior

`mix test` and `iex -S mix` should work.

**Comment by seungjin** [comment]
Tried with `ka`, `po`, `pa` but all work. Only issue with `pa`.

**Comment by josevalim** [comment]
There is a command line option called -pa and they may be conflicting. I will investigate, thank you!

**Comment by Nicd** [comment]
Is it a concern that application names are passed to a command line somewhere where they can be mixed with command line flags?

**Comment by josevalim** [comment]
Yes, it is. I am planning to report this to the OTP team. :)
