### ISSUE TITLE
Add `--rpc-call` flag and use it in release rpc command

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#11630]
Today we can do:

```
$ elixir --sname bar --rpc-eval foo 'IO.puts ["a", "b", "c"]'
```

While this works well, imagine we have a CLI utility that uses the above under the hood. We'd be passing CLI args to the eval string which is very unsafe as someone could execute arbitrary code.

We'd like to propose adding `--rpc-call mod fun` which would eval `mod.fun(argv)` over rpc where argv are unconsumed command line arguments. Under the hood we'd make sure they are properly sanitized (e.g. by inspecting the AST.) Here's how an equivalent to the above invocation would look like:

```
$ elixir --sname bar --rpc-call IO puts a b c
```

This flag would be used in the release script created by `$ mix release` too. Here's how it would work:

```
$ bin/myapp rpc arg1                  # uses --rpc-eval like today
$ bin/myapp rpc arg1 arg2 [arg3, ...] # uses --rpc-call
```

cc @josevalim

**Comment by wojtekmach** [comment]
> ```
> $ bin/myapp rpc arg1                  # uses --rpc-eval like today
> $ bin/myapp rpc arg1 arg2 [arg3, ...] # uses --rpc-call
> ```

this is a totally separate discussion but I wonder if for consistency we should also have:

```
$ bin/myapp eval arg1                  # uses --eval like today
$ bin/myapp eval arg1 arg2 [arg3, ...] # uses a new --call mod fun ...
```

I think this could be especially useful in the new `bin/migrate` stub generated by `mix phx.gen.release`, we could more easily pass args to it. :)

**Comment by josevalim** [comment]
@wojtekmach we should support the three args in `bin/release eval` too. However, eval is not problem because we can implement it today!

```elixir
$ elixir -e "[mod, fun | args] = System.argv(); apply(Module.concat([mod]), String.to_atom(fun), args)" -- IO puts "hello world"
hello world
```

The thing about rpc is that we really need to support it properly in order to pass the argv.

**Comment by josevalim** [comment]
Unfortunately we are not adding this feature because it is unreasonably hard to expose it under the .bat files on Windows. :(

**Comment by simonmcconnell** [comment]
I'm pretty sure Windows has ruined any attempt at passing args on the command line because the shells handle escapes etc differently. The method I'm exploring is having a single command the takes you into the program so you can enter args one at a time, as prompted.
