### ISSUE TITLE
Mix.Tasks.LocalTest failing on Erlang/OTP 25

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#11638]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
$ bin/elixir --version
Erlang/OTP 25 [RELEASE CANDIDATE 1] [erts-13.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.0-dev (22e3b12) (compiled with Erlang/OTP 25)
```
* Operating system: Ubuntu 21.10

### Current behavior

The next issue found in trying to get Elixir tests passing on Erlang/OTP 25 is

```
$ TEST_FILES="local_test.exs" make test_mix
==> mix (ex_unit)
Excluding tags: [windows: true]

...

  1) test MIX_PATH (Mix.Tasks.LocalTest)
     test/mix/tasks/local_test.exs:6
     ** (Mix.NoTaskError) The task "local.sample" could not be found. Did you mean "local"?
     Note no mix.exs was found in the current directory
     code: Mix.Task.run("local.sample")
     stacktrace:
       (mix 1.14.0-dev) lib/mix/task.ex:315: Mix.Task.get!/1
       (mix 1.14.0-dev) lib/mix/task.ex:400: Mix.Task.run_task/4
       test/mix/tasks/local_test.exs:20: (test)
```

I think this may be related to this point from [Erlang/OTP 25.0-rc1 announcement](https://www.erlang.org/news/153):
> To enable more optimizations, BEAM files compiled with OTP 21 and earlier cannot be loaded in OTP 25.

The [Elixir.Mix.Tasks.Local.Sample.beam file](https://github.com/elixir-lang/elixir/blob/2ddd291c533cdc2b1b1f02153d94c0b248cb9836/lib/mix/test/fixtures/archive/ebin/Elixir.Mix.Tasks.Local.Sample.beam) hasn't been changed at least since 2013.

I can send an updated file but I'm not sure it would be accepted?

I can confirm the test passes after executing these commands:
```
cd lib/mix/test/fixtures/archive
rm ebin/Elixir.Mix.Tasks.Local.Sample.beam
asdf install erlang 23.3.4.11 && asdf local erlang 23.3.4.11
asdf install elixir 1.11.4 && asdf local elixir 1.11.4
elixirc lib/local.sample.ex -o ebin/
rm .tool-versions
```

**Comment by josevalim** [comment]
Great catch @michallepicki! Can you please send a PR so we gitignore that file and instead we compile it in the test_helper.exs in case said file no longer exists? I think you also need to make sure remove that directory on `make clear`.

**Comment by michallepicki** [comment]
> Can you please send a PR so we gitignore that file and instead we compile it in the test_helper.exs in case said file no longer exists?

I'll try! :)
