### ISSUE TITLE
mix local.hex exits (exit 0) Snapcraft build-override multiline scriplet midway without any error

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [elixir-lang/elixir#11646]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 24 Elixir (1.13.0)
* Operating system: Ubuntu 20.04

### Current behavior

Hello everyone, I am facing a really strange issue. When I run the following command:
`snapcraft build my-part --use-lxd --debug --shell-after`

The build-override scriplet only runs till line 3 and opens a shell without any error. But when I run the scriplet as a separate shell script manually inside the lxd container it runs perfectly.
```
override-build: |
      cd -
      make
      mix local.hex --if-missing --force
      mix local.rebar --if-missing --force
      mix deps.get
      cd assets
      npm install
      npm ci
      npm run deploy
      cd -
      mix phx.digest
      mix distillery.release
```
## OUTPUT
```
...
..
+ mix local.hex --if-missing --force
* creating ./.mix/archives/hex-1.0.1
snapcraft-my-part # 
```
I have checked the exit code of `mix local.hex --if-missing --force` and it is 0.

### Expected behavior

The whole scriptlet should run completely.

This only happens with all mix commands under `override-build`. I want to know if mix somehow kills the parent process.

**Comment by roychowdhuryrohit-dev** [comment]
Found a workaround where we run every `mix` commands in a new background OS processes and waiting for them. This way the parent processes remain unaffected.

```sh
mix local.hex --if-missing --force &
wait $!
```

**Comment by josevalim** [comment]
Hi @roychowdhuryrohit-dev. Can you break this down into a reproducible issue that does not include snapcraft? We need to first rule out it being a snapcraft issue. Thank you!

**Comment by roychowdhuryrohit-dev** [comment]
Reason that it's not a Snapcraft issue: Any other commands work correctly.
Reason that it maybe a Snapcraft issue: When running mix commands inside a shell script separately it works perfectly.

**Comment by roychowdhuryrohit-dev** [comment]
> Exactly. It is unclear, that's why I propose to focus on finding a way to reproduce the issue outside snapcraft. Doing so will also help us work on a fix later on. :)

I have added the steps to reproduce this issue outside Snapcraft.

**Comment by roychowdhuryrohit-dev** [comment]
As a workaround we run every `mix` commands in a new background OS processes and waiting for them. This way the parent processes remain unaffected.

```sh
mix local.hex --if-missing --force &
wait $!
```

**Comment by josevalim** [comment]
I will close this for now, please let us know if you have steps to reproduce this issue. Thank you!
