### ISSUE TITLE
~/.mix/rebar3 version and corp.proxies/CA problems

### ISSUE THREAD

**Issue by winks** [elixir-lang/elixir#11647]
Short version: 

I am behind a proxy that intercepts SSL via a custom CA, this was fixed in rebar 3.17, but the bundled/auto-downloaded? version via mix doesn't have this yet.

Long version:

I was trying to build [this example project](https://github.com/open-api-spex/open_api_spex/tree/master/examples/phoenix_app) and noticed that I got some "Unknown CA" error from `~/.mix/rebar3` (did not copy the exact output fast enough, sorry). I thought I had solved this as described in [this rebar3 issue](https://github.com/erlang/rebar3/issues/2679) - but then I noticed that [this piece of rebar code](https://github.com/erlang/rebar3/blob/main/src/rebar_utils.erl#L1045) was only added on 2021-05-27, which is also mentioned in the [rebar 3.17.0 patch notes](https://github.com/erlang/rebar3/releases/tag/3.17.0)

Here's a gist: https://gist.github.com/winks/3d5a970a5105597536ad7384f7792db4 (ignore the download error per se, on another machine 3.15.x was installed and showed the CA error from rebar, this is just for 'what operations happened in what order')

### Environment

```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.13.2 (compiled with Erlang/OTP 24)
# (installed via kerl and kiex)
Description:	Ubuntu 20.04.3 LTS
```

**I tried this on a second machine with 24.2.1 and 1.13.3 - no change**

On #elixir on irc I was pointed to https://repo.hex.pm/installs/rebar3-1.x.csv - so maybe bumping this would fix it.

### Current behavior

`mix deps.compile esqlite` fails with the rebar "Unknown CA" error

### Expected behavior

The custom CA is accepted via `~/.config/rebar3/rebar.config` - which works with rebar 3.18 and *should* work with 3.17, but I only tested 3.18 and looked at the 3.17 patch notes.

My apologies if I am misjudging the issue, as I can only assume that my `~/.mix/rebar3` is indeed bootstrapped from mix itself, any pointers are appreciated if this would be in one of the dependencies down the line in the example project above (not mine).

**Comment by josevalim** [comment]
Thank you for the report! We are already updating the rebar3 coming in the upcoming Elixir v1.14 version, we are testing it locally before committing it to the .csv file. Meanwhile, you can install rebar3 yourself and make `MIX_REBAR3` point to it. :) Then Mix will use it for all projects.

**Comment by newmanjeff** [comment]
As of 11/16, the rebar3 from hex.pm is still 3.15.x for elixir 1.14.  Is there a reason rebar3 failed in test for elixir 1.14 and should be avoided?
