### ISSUE TITLE
Compilation hangs when trying to compile a particular map-related code

### ISSUE THREAD

**Issue by mat-hek** [elixir-lang/elixir#11658]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
  ```
  Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

  Elixir 1.13.3 (compiled with Erlang/OTP 24)
  ```
  **This seems not to happen on 1.12**
* Operating system: Mac OS 11.6

### Current behavior

Trying to compile the following code makes the compilation hang and use 70-100% of a CPU core

```elixir
defmodule A do

  def fun(x, y) do
    key_var = y
    %{^key_var => _value} = x
    key_var2 = y
    %{^key_var2 => _value2} = x
    y.z
  end
end
```

Replacing `y.z` with
```elixir
key_var3 = y
%{^key_var3 => _value3} = x
```
gives the same effect

### Expected behavior

I believe this should compile normally ;)

**Comment by bblaszkow06** [comment]
I may add it works fine on
```
$ elixir -v
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.12.3 (compiled with Erlang/OTP 24)
```

and hangs on
```
$ elixir -v       
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.13.0 (compiled with Erlang/OTP 24)
```

**Comment by michallepicki** [comment]
Caveat: I don't know what I'm doing :D

This seems to be introduced by https://github.com/elixir-lang/elixir/pull/10820 . Possibly before it, the situation was handled by flipping unify target and source arguments `if stack.context == :pattern do` in the top unify. I don't know yet how this code works exactly but flipping the order of clauses that handle vars from
```
  def unify(type, {:var, var}, stack, context) do
    unify_var(var, type, stack, context, _var_source = false)
  end

  def unify({:var, var}, type, stack, context) do
    unify_var(var, type, stack, context, _var_source = true)
  end
```
to

```
  def unify({:var, var}, type, stack, context) do
    unify_var(var, type, stack, context, _var_source = true)
  end

  def unify(type, {:var, var}, stack, context) do
    unify_var(var, type, stack, context, _var_source = false)
  end
```
makes the unification stop. This makes recursive vars point to each other in a slightly different way and some tests fail because of that (changes to get them passing seem to make sense though) and warnings may get printed a bit differently but at a glance what should pass still passes and what should fail still fails.

**Comment by nhpip** [comment]
Seeing something similar.....was actively debugging as I was posting
```
$ elixir -v
Erlang/OTP 25 [erts-13.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.13.4 (compiled with Erlang/OTP 25)
```
https://elixirforum.com/t/weird-behavior-in-a-test-case/49484/5

**Comment by josevalim** [comment]
Can you please post a snippet that reproduces the error, similar to the one posted by @mat-hek at the top?

**Comment by mikebveil** [comment]
@nhpip's colleague here. I've been able to reduce it to this snippet:
```
  def hangs_compiler() do
    users = foo()
    _foo = users.alice.user_id
    _bar = users.alice.user_id
    users = %{users | alice: %{users.alice | foo: 1}}
    _unused = users.alice.user_id
  end

  defp foo(), do: nil # I assume the body of this function doesn't matter
```
A slightly different snippet…
```
  def crash_compiler() do
    users = foo()
    _foo = users.alice.user_id
    _bar = users.alice.user_id
    users = %{users | alice: %{users.alice | foo: 1}}
    _unused = %{user_id: users.alice.user_id}
  end

  defp foo(), do: nil
```
…gives a compiler warning:
```
warning: incompatible types:

    map() !~ var2

in expression:

    # test/api/test.exs:7
    _unused = %{user_id: users.alice.user_id}

where "_unused" was given the type map() in:

    # test/api/test.exs:7
    _unused = %{user_id: users.alice.user_id}

Conflict found at
  test.exs:7: Test.hang_compiler/0
```
I haven't been able to reduce the size of this code and still get a hang or warning. Even the duplicate assignments to `_foo` and `_bar` are necessary.

**Comment by nhpip** [comment]
Even fails with "real data"

```
  def hangs_compiler() do
    users = foo()
    _foo = users.alice.user_id
    _bar = users.alice.user_id
    users = %{users | alice: %{users.alice | foo: 1}}
    unused = users.alice.user_id
  end

  defp foo(), do: %{alice: %{user_id: 9}}

```

**Comment by michallepicki** [comment]
Spent a little bit of time looking into this, reversing my previous patches doesn't seem to change anything. What I find suspicious is that [here](https://github.com/elixir-lang/elixir/blob/b7bc1c39b8d1039bd74c6343039f94f0d7558618/lib/elixir/lib/module/types/expr.ex#L150) for the outer map update (from `users = %{users | alice: %{users.alice | foo: 1}`), `arg_pairs` has duplicate required key for `:user_id` (pointing to type variables for `_foo` and `_bar`). I suspect the required keys of the same key value should be unified at some point, not sure at which point though.
