### ISSUE TITLE
Non ASCII characters in map keys

### ISSUE THREAD

**Issue by cw789** [elixir-lang/elixir#11660]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 24)
```
* Operating system: Windows

### Current behavior

```
iex(1)> %{"Ä" => "B"}
%{<<0>> => "B"}
```
~~It seems not to bee IEx related.~~
It does not occur on v1.13.2 under Linux.
So it's either Windows / IEx related or introduced with v1.13.3.

### Expected behavior

```
iex(1)> %{"Ä" => "B"}
%{"Ä" => "B"}
```

**Comment by josevalim** [comment]
I believe this is Windows related. The terminal on Windows is not Unicode based. You need to either change the codepage, configure the terminal to be in Unicode, or use `iex --werl`. To quote the docs here:

> If you are running on Windows and you see incorrect values printed, you may need change the encoding of your current session by running chcp 65001 before calling iex (or before calling iex.bat if using PowerShell).

**Comment by josevalim** [comment]
If the problem persists, you can also try `erl` and see if the issue exists there (most likely yes).

**Comment by cw789** [comment]
Thanks José. I'll dig deeper some time.
You can close the issue any time (Windows should not be a priority).

I just remembered I'm using the beta UTF-8 support on Windows.
So it's probably anywhere related to that.

**Comment by josevalim** [comment]
Windows is definitely a priority but I am 99% sure this is not an Elixir problem, likely Windows or Erlang, so I will go ahead and close. Feel free to post updates here and I will be glad to reopen if it turns out to be an Elixir issue!
