### ISSUE TITLE
(Confusing?) Documentation regarding child_spec ids for DynamicSupervisor

### ISSUE THREAD

**Issue by travisgriggs** [elixir-lang/elixir#11662]
The documentation for DynamicSupervisor.start_child/2 says

> child_spec should be a valid child specification as detailed in the "Child specification" section of the documentation for [Supervisor](https://hexdocs.pm/elixir/Supervisor.html). The child process will be started as defined in the child specification.

That documentation in turn says that a valid child_spec:

> :id - any term used to identify the child specification internally by the supervisor; defaults to the given module. In the case of conflicting :id values, the supervisor will refuse to initialize and require explicit IDs. This key is required.

However, after some naive code that broke this rule, digging through the source, and then running some experiments, I think I've convinced myself that this constraint is actually not true for children of DynamicSupervisors. It appears you have to include the field in your spec, but otherwise the value is completely discarded/ignored.

I *think* the documentation should express this, maybe something like:

> child_spec should be a valid child specification as detailed in the "Child specification" section of the documentation for [Supervisor](https://hexdocs.pm/elixir/Supervisor.html). The child process will be started as defined in the child specification. Note that while the id: field is still required in the spec, the value is ignored and therefore does not need to be unique.

One might also amend the generic documentation as:

> :id - any term used to identify the child specification internally by the supervisor; defaults to the given module. This key is required. For Supervisors, in the case of conflicting :id values, the supervisor will refuse to initialize and require explicit IDs. This is not the case for DynamicSupervisors though.

If I'm not totally off-base here (I'm green, so I may be), then this would be about the level I'm good for to submit a pull-request with the doc changes, per any of your guidance.

**Comment by josevalim** [comment]
Both proposed changes are great and we would love a pull request to add them!
