### ISSUE TITLE
Mix having trouble with do notation and multiple tasks

### ISSUE THREAD

**Issue by bmitc** [elixir-lang/elixir#11682]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
    ```
    Erlang/OTP 24 [erts-12.1.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

    Elixir 1.13.3 (compiled with Erlang/OTP 22)
    ```
* Operating system: Windows 11, OS Build 22000.527

### Current behavior

The [Livebook local install instructions](https://livebook.dev/#install) don't work on Windows due to an error with Mix. The instructions are:

![image](https://user-images.githubusercontent.com/65685447/156699778-3f953c34-ae41-41c4-b606-8b668d5e3ba0.png)

Running this on Windows with PowerShell yields:
```powershell
PS > mix.bat do local.rebar --force, local.hex --force
** (Mix) Invalid arguments given to mix local.rebar. To find out the proper call syntax run "mix help local.rebar"
```

### Expected behavior

It seems like this was expected to work as is on any OS. I was able to break it up into two commands, but `mix.bat do` doesn't seem to like the comma and two separate tasks. I originally was going to file this in the Livebook repo, as maybe the instructions could be updated, but it seems like it's maybe a Mix issue?

### Some Notes

I tried this:
```powershell
PS > mix.bat do local.hex --force, local.rebar --force
* creating c:/Users/<user>/.mix/archives/hex-1.0.1
```
which doesn't error out but it doesn't seem to do anything for the `local.rebar --force` tasks. At least nothing is printed to the console like what happens if just `mix.bat local.rebar --force` is ran.

If I run something like `mix.bat do credo, dialyzer`, then only Credo seems to run.

I haven't tried this on my macOS machine yet.

**Comment by wojtekmach** [comment]
It seems `mix do` doesn't properly handle `, ` on Windows shells:

```
# cmd.exe
> mix do cmd echo foo, cmd echo bar
foo cmd echo bar
```

```
# powershell
> mix do cmd echo foo, cmd echo bar
foo cmd echo bar
```

```
# bash
> mix do cmd echo foo, cmd echo bar
foo
bar
```

Here's one idea:

```
# cmd.exe
> elixir -e "IO.inspect(System.argv())" -- foo, bar
["foo", "bar"]
```

```
# bash
# cmd.exe
> elixir -e "IO.inspect(System.argv())" -- foo, bar
["foo,", "bar"]
```

notice we have `"foo"` on cmd but `"foo,"` on bash. It seems Windows shells drop `, `, it never reaches Elixir land. That would explain why `mix do cmd echo foo, cmd echo bar` is seems to be same as running `mix do cmd echo foo cmd echo bar`.

**Comment by bmitc** [comment]
Thanks for investigating this.

[It turns out that a `,` is a special operator in PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_operators?view=powershell-7.2#comma-operator-), so it seems the use of the `,` in Mix may be improper in PowerShell unless handled.

I have been using `mix.bat`, but I tried `mix.ps1` as well, which didn't work either. Taking a look at the `mix.ps1` PowerShell script, it seems to be aware of commas being treated as array delimiters, but I haven't walked through the details of it yet.

Neither `mix.bat 'do credo, dialyzer'` nor `mix.bat do 'credo, dialyzer'` work either. Same if replacing `mix.bat` with `mix.ps1`, which seems to just call `mix.bat`.

```powershell
PS > mix.ps1 do 'credo, dialyzer'
** (Mix) The task "credo, dialyzer" could not be found
PS > mix.ps1 'do credo, dialyzer'
** (Mix) The task "do credo, dialyzer" could not be found
```

That seems to be a Mix problem (or at least `mix.bat` or `mix.ps1`)?

As a side note, I'm wondering if it's possible for the Elixir distributions to digitally sign `mix.ps1`? [See here.](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.2#powershell-execution-policies)

```powershell
PS > mix.ps1
mix.ps1 : File C:\Program Files (x86)\Elixir\bin\mix.ps1 cannot be loaded. The file C:\Program Files (x86)\Elixir\bin\mix.ps1 is not
digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execution policy,
see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ mix.ps1
+ ~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

I think it would be preferable to use the `AllSigned` execution policy, whereas right now something more permissive like `RemoteSigned` needs to be used.

**Comment by josevalim** [comment]
And `,` is a reserved character on cmd as well, so whatever the approach, it is not going to work on Windows.

We need to revisit the approach altogether, unfortunately. My suggestion at the moment is to support something like `mix do task1 arg1 + task2 arg1 + task3`. If someone wants to submit a PR, it will be welcome. For now I will update Livebook's website. Thank you for the report.
