### ISSUE TITLE
throw an IO error when writing to a filesystem with no space left

### ISSUE THREAD

**Issue by c4710n** [elixir-lang/elixir#11707]
### Precheck

Recently, I read an article - [Bugs in Hello World](https://blog.sunfishcode.online/bugs-in-hello-world/). And, I found Elixir doesn't act as expected in this article.

`hello.exs`:
```elixir
IO.puts("Hello World!")
```

```elixir
$ elixir hello.exs > /dev/full 
$ echo $?
0
```

Quotes from the article:
> Linux has a fun device file called `/dev/full`, which is like its more famous cousin `/dev/null`, but when you write to `/dev/full`, instead of throwing away the data, it fails. It acts like a file on a filesystem that has just run out of space:
> ```
> $ echo "Hello World!" > /dev/full
> bash: echo: write error: No space left on device
> $ echo $?
> 1
> ```
> This is a great little tool for testing that programs handle I/O errors correctly. It's inconvenient to create actual filesystems with no space left, or disks that actually fail, but it's really easy to ask a program to write its output to `/dev/full` and see what happens.

### Environment

* Elixir Version: 1.12.3 (compiled with Erlang/OTP 24)
* Operating system: Linux (NixOS)

### Current behavior

Elixir won't throw an IO error when writing to a filesystem with no space left.

### Expected behavior

Elixir throws an IO error when writing to a filesystem with no space left.

**Comment by josevalim** [comment]
Can you please try with this program?

    IO.inspect(:stderr, IO.puts("Hello world!"), [])

I think it would be very Elixir-unlike for a failure on a single operation to cause the software to exit or change the exit code. The correct would be perhaps to return an error tuple. So please try the above and if it still returns `:ok`, then I recommend filing an issue upstream in Erlang. After all, `IO.puts` is simply a call to `io:put_chars`. :)

**Comment by c4710n** [comment]
I tried the program with following steps.

`hello.exs`:

```elixir
IO.inspect(:stderr, IO.puts("Hello world!"), [])
```

Then run:
```sh
$ elixir hello.exs > /dev/full
:ok

$ echo $?
0
```

**Comment by josevalim** [comment]
This is definitely an Erlang issue then. Can you please report it upstream on github.com/erlang/otp? I think it suffices to say that writing to a full device works. Thank you!

**Comment by c4710n** [comment]
Reported. Thanks for your guidance.

**Comment by josevalim** [comment]
Thank you! Closing in favor of https://github.com/erlang/otp/issues/5797. :)
