### ISSUE TITLE
mix compile after recompile within iex

### ISSUE THREAD

**Issue by cw789** [elixir-lang/elixir#11704]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.3 (compiled with Erlang/OTP 24)
```
* Operating system: Windows 11

### Current behavior

I'm not sure if this is a bug or really unexpected - but closing an issue is anyway fast.

With the following `mix.exs` + the following steps.

- `iex -S mix`
- Bump `@version` in `mix.exs`
- `recompile` within `iex`
- Exit `iex`
- Run `mix compile`
- Enter `iex` again
- `Application.spec(:my_app, :vsn)`
- Version got not bumped

**mix.exs**
```
defmodule MyApp.MixProject do
  use Mix.Project

  @version "0.1.0"

  def project do
    [
      app: :my_app,
      version: version(),
      elixir: "~> 1.13",
      start_permanent: Mix.env() == :prod,
      deps: []
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp version(), do: @version
end

```

### Expected behavior

I would expect to not need `mix recompile --force` in this situation.

**Comment by cw789** [comment]
Would I be on the right track if in [`IEx.Helpers.recompile/1`](https://github.com/elixir-lang/elixir/blob/main/lib/iex/lib/iex/helpers.ex#L94) → [`IEx.Helpers.reenable_tasks/1`](https://github.com/elixir-lang/elixir/blob/main/lib/iex/lib/iex/helpers.ex#L124) I there then not to do a ` Mix.Task.reenable("compile.app")`.

I'm just guessing into the dark.

**Comment by josevalim** [comment]
We can do that, yes, but also keep in mind that the docs do mention that applications are not restarted. It is strictly about modules.

**Comment by cw789** [comment]
Ok right. Then this is not the solution.

I currently do not see the solution so that `mix compile` after `recompile` within `IEx` will update Application if you enter `IEx` again.

**Comment by josevalim** [comment]
Sorry, I mean we can try, we will have to update the docs though.

**Comment by cw789** [comment]
Ok, I will have a look into it the next weeks.

**Comment by josevalim** [comment]
Closing this as the docs mention applications are not recompiled/restarted. However, if someone wants to improve the workflow, PRs are welcome (there are limits to what it can achieve though).
