### ISSUE TITLE
Check compile-time dependencies on macros

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11714]
* [ ] All modules and calls in macros should be a compile-time dep
* [ ] `defguard` and `defguardp` should not add compile-time deps
* [ ] If `var in @attr` is used and `@attr` expands to a list of aliases, we should emit a warning instruction users to use `defguard` and remove the compile-time deps

**Comment by fmterrorf** [comment]
Hello @josevalim. I'd like to help out on this issue, but I'm not sure where to start. Just wondering if you can give some advice on where to look. Thanks

**Comment by josevalim** [comment]
Sorry @fmterrorf, your comment fell through the cracks (I had - still have - an arm injury which did not allow me to stay on top of issues as usual). I will tackle this issue now but if you pick something else I may be in a better position to help.
