### ISSUE TITLE
mix deps.update for erlang library

### ISSUE THREAD

**Issue by meox** [elixir-lang/elixir#11719]
### Precheck

Seems that `mix deps.update my_erlang_lib` pinned to a particular branch doesn't update the commit reference to the mix.lock file

### Environment

* Elixir & Erlang/OTP versions (elixir --version):  
```sh
Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit]
Elixir 1.13.0 (compiled with Erlang/OTP 24)
```

* Operating system:  Debian 11

**Comment by meox** [comment]
I have an external Erlang library in a local gitlab repository:
```elixir
  defp deps do
    [
      {:myerlang_lib, git: "git@mylocal.com:core/erl/pfcp.git", ref: "my-branch"}
      # other libs
    ]
  end
```

if I do: `mix deps.get` this works and in the mix.lock I have the right commit reference.
But if I later update the lib and run: `mix deps.update  myerlang_lib` the lock file is not updated.
I have to change it manually.

**Comment by josevalim** [comment]
References are always assumed to be static. Please use branch: "my-branch" instead.
