### ISSUE TITLE
Creating bitstring from a literal charlist

### ISSUE THREAD

**Issue by andrhua** [elixir-lang/elixir#11717]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.13.2, OTP 24
* Operating system: Arch Linux 5.16.15

### Current behavior

According to docs for [`<<>>/1`](https://hexdocs.pm/elixir/1.13.2/Kernel.SpecialForms.html#%3C%3C%3E%3E/1):

> Elixir also accepts by default the segment to be a literal string or a literal charlist, which are by default expanded to integers

And indeed you can build a bitstring from a string segment:
```
iex(1)> <<0, "foo">>
<<0, 102, 111, 111>>
```
but not from a charlist:
```
iex(2)> <<0, 'foo'>>
** (CompileError) iex:2: invalid literal 'foo' in <<>>
    (elixir 1.13.2) src/elixir_bitstring.erl:44: :elixir_bitstring.expand/8
    (elixir 1.13.2) src/elixir_bitstring.erl:26: :elixir_bitstring.expand/5
```

### Expected behavior

Being able to construct bitstring from charlist segments

**Comment by josevalim** [comment]
Can you please send a pull request that updates the docs? I don't think this was actually supported, so it is rather a mistake in the docs. Thank you!
