### ISSUE TITLE
Inconsistent documentation of Inspect.Opts in IEx

### ISSUE THREAD

**Issue by krns** [elixir-lang/elixir#11721]
### Current behavior

The [Inspect.Opts module](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/inspect/algebra.ex#L44) says:

```
    * `:pretty` - if set to `true` enables pretty printing. Defaults to `false`.
```

The [IEx module](https://github.com/elixir-lang/elixir/blob/main/lib/iex/lib/iex.ex#L430-L431) says:

```
A keyword list containing inspect options used by the shell
  when printing results of expression evaluation. Default to
  pretty formatting with a limit of 50 entries.
```

https://github.com/elixir-lang/elixir/blob/89e57882e120e77d755477b96ecfa15032dd582d/lib/iex/lib/iex.ex#L420-L421

### Expected behavior

The [IEx module](https://github.com/elixir-lang/elixir/blob/main/lib/iex/lib/iex.ex#L430-L431) documentation should be:

```
A keyword list containing inspect options used by the shell
  when printing results of expression evaluation. Defaults to
  a limit of 50 entries.
```

I can provide a PR if you like?

**Comment by josevalim** [comment]
The current version is correct. Inspect.Opts is the default behaviour, but IEx overrides it by default: https://github.com/elixir-lang/elixir/blob/89e57882e120e77d755477b96ecfa15032dd582d/lib/iex/mix.exs#L18 :)

**Comment by krns** [comment]
Oh, I missed that. I will create a PR anyway to fix the `default to` typo :-)
