### ISSUE TITLE
Version.parse/1 removes dots from Version.build field

### ISSUE THREAD

**Issue by peake100** [elixir-lang/elixir#11735]
### Environment

* Elixir & Erlang/OTP versions: Elixir 1.13.0 (compiled with Erlang/OTP 24)
* Operating system: OSX 11.6 (Big Sur)

### Current behavior

When parsing `"1.0.0-alpha.3+20130417140000.amd64"` using `Version.parse/1`, I expect the resulting `Version.build` to contain `"20130417140000.amd64"`, but instead it contains `"20130417140000amd64"` (dot separator removed). This example value is pulled from the module's [documentation](https://hexdocs.pm/elixir/1.12/Version.html#module-versions).

Here is a quick test to reproduce the behavior

```elixir
test "parse Version with multi-part build tag" do
  assert {:ok, %Version{} = semver} = Version.parse("1.0.0-alpha.3+20130417140000.amd64")
  assert semver.build == "20130417140000.amd64"
end
```

Result:

```text
 Assertion with == failed
 code:  assert semver.build == "20130417140000.amd64"
 left:  "20130417140000amd64"
 right: "20130417140000.amd64"
```

This also affects round-tripping the value:

```elixir
test "round-trip Version with multi-part build tag" do
  assert {:ok, %Version{} = semver} = Version.parse("1.0.0-alpha.3+20130417140000.amd64")
  assert to_string(semver) == "1.0.0-alpha.3+20130417140000.amd64"
end
```

Result:

```text
 Assertion with == failed
 code:  assert to_string(semver) == "1.0.0-alpha.3+20130417140000.amd64"
 left:  "1.0.0-alpha.3+20130417140000amd64"
 right: "1.0.0-alpha.3+20130417140000.amd64"
```

### Expected behavior

The above test should pass. With the API as it is now, I would expect dots to be preserved. But if we zoom out a bit, I would expect the `Version.build` field to use the same value representation as the `Version.pre` field (a list of parsed sections). For instance, in the above example, the `pre` field is parsed as `["alpha", 3]`, as this test shows:

```elixir
test "parse Version with multi-part pre tag" do
  assert {:ok, %Version{} = semver} = Version.parse("1.0.0-alpha.3+20130417140000.amd64")
  assert semver.pre == ["alpha", 3]
end
```

In an idealized world, I would expect the `Version.build` field to follow the same convention, so something like this would pass:

```elixir
test "parse Version with multi-part build tag" do
  assert {:ok, %Version{} = semver} = Version.parse("1.0.0-alpha.3+20130417140000.amd64")
  assert semver.build == ["20130417140000", "amd64"]
end
```

But that would, of course, be a breaking change, and may have some pitfalls I am unaware of that lead to the original design decision to parse the build tag to a single string.

### Possible Solution

I believe the error can be fixed quite simply in [this codeblock](https://github.com/elixir-lang/elixir/blob/a64d42f5d3cb6c32752af9d3312897e8cd5bb7ec/lib/elixir/lib/version.ex#L358-L369):

```elixir
@spec parse(String.t()) :: {:ok, t} | :error
def parse(string) when is_binary(string) do
  case Version.Parser.parse_version(string) do
    {:ok, {major, minor, patch, pre, build_parts}} ->
      build = if build_parts == [], do: nil, else: Enum.join(build_parts, "") # <--- Problem child
      version = %Version{major: major, minor: minor, patch: patch, pre: pre, build: build}
      {:ok, version}

    :error ->
      :error
  end
end
```

By changing the annotated line to:

```elixir
build = if build_parts == [], do: nil, else: Enum.join(build_parts, ".")
```

... if the current type for the `Version.build` field is desirable.

I would be happy to submit a PR for this with a couple tests, but have not contributed to Elixir before. So if that would be helpful where should I look for contribution guidelines / processes?

Thank you for your time!

**Comment by wojtekmach** [comment]
Nice catch! A PR sounds great. Check out these guidelines: https://github.com/elixir-lang/elixir#contributing.

**Comment by peake100** [comment]
> Nice catch! A PR sounds great. Check out these guidelines: https://github.com/elixir-lang/elixir#contributing.

Thanks! I'll put something together tomorrow.

**Comment by peake100** [comment]
Had time today. PR is up for your consideration: #11736
