### ISSUE TITLE
Mix does not install latest available version of package

### ISSUE THREAD

**Issue by marceldegraaf** [elixir-lang/elixir#11745]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.12.3 (compiled with Erlang/OTP 24)` (installed via `asdf`)
* Operating system: Debian Linux 11.2

### Current behavior

In a freshly created Mix application (`mix new my_app`) I edit `mix.exs` and add `ex_cldr` as a dependency: 

```elixir
  defp deps do
    [
      {:ex_cldr, "~> 2.0"}
    ]
  end
```

I then run `mix deps.get` to install the dependencies. This installs `ex_cldr` version 1.27.1:

```
$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
New:
  cldr_utils 2.17.1
  decimal 2.0.0
  ex_cldr 2.27.1
* Getting ex_cldr (Hex package)
* Getting cldr_utils (Hex package)
* Getting decimal (Hex package)
```

This is surprising, as the latest version of `ex_cldr` at the time of writing is `2.28.0` (release April 5, 2022). This is confirmed by `mix hex.search` on the affected system:

```
$ mix hex.search ex_cldr
Package                      Description                                            Version  URL
ex_cldr                      Common Locale Data Repository (CLDR) functions for...  2.28.0   https://hex.pm/packages/ex_cldr
```

Editing `mix.exs` a second time, this time setting the latest version of `ex_cldr` specifically:

```elixir
  defp deps do
    [
      {:ex_cldr, "2.28.0"}
    ]
  end
```

Now, when running `mix deps.update ex_cldr` I expect the latest version (`2.28.0`) of `ex_cldr` to be installed. Instead, Mix returns this error:

```
$ mix deps.update ex_cldr
** (Mix) No matching version for ex_cldr 2.28.0 (from: mix.exs) in registry

The latest version is: 2.27.1
```

I have tried deleting Hex's cache (`rm ~/.hex/cache.ets`) but that did not help. I have no idea why this happens, or how to debug it further.

Please do let me know if this isn't the right place to create this issue – happy to move it somewhere more appropriate.

**Comment by kipcole9** [comment]
I just created a new project on Elixir 1.13.2 and added only:
```elixir
defp deps do
    [
      {:ex_cldr, "~> 2.0"}
    ]
  end
```
and dependency resolution retrieved what is expected:
```elixir
kip@Kips-MacBook-Pro ctest % mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
New:
  cldr_utils 2.17.1
  decimal 2.0.0
  ex_cldr 2.28.0
* Getting ex_cldr (Hex package)
* Getting cldr_utils (Hex package)
* Getting decimal (Hex package)
```
I wonder if this is a mix or hex version issue? (I'm the author of `ex_cldr`)

**Comment by ericmj** [comment]
Do you have the same issue if you use a clean install? You can use docker to check it:

```
docker run -it hexpm/elixir:1.12.3-erlang-24.3.3-debian-bullseye-20210902 bash
```

**Comment by marceldegraaf** [comment]
@kipcole9 and @ericmj – thanks for your quick replies. Some interesting points here.

The issue described above (in a fresh Elixir app) occurs with `Hex.version = 0.21.3`. However, a quick `mix local.hex` upgraded Hex to `1.0.1` but the issue persists. I'm still not able to install `ex_cldr = 2.28.0`.

Per Eric's instructions I've tried installing `ex_cldr = 2.28.0` in a Docker container, in a fresh Elixir app. And that fails as well, with the same error message: version `2.27.1` is the latest version to be found.

This seems to point to a (caching?) issue somewhere in the network layer. Eric – that Fastly debug page seems to include some dynamic checks but the issue occurs on a headless Hetzner server. Is there something similar I can do from that machine?

**Comment by josevalim** [comment]
I could reproduce the issue and @ericmj has fixed it for me! :heart: It was a cdn cache issue indeed.

@marceldegraaf can you please try again?

**Comment by marceldegraaf** [comment]
```
$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  cldr_utils 2.17.1
  decimal 2.0.0
  jason 1.3.0
Upgraded:
  ex_cldr 2.27.1 => 2.28.0
* Updating ex_cldr (Hex package)
```

It works! Thanks so much to all involved.
