### ISSUE TITLE
`ExUnit.after_suite` callbacks are not called when no tests were ran

### ISSUE THREAD

**Issue by jared-mackey** [elixir-lang/elixir#11746]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit]
Elixir 1.13.3 (compiled with Erlang/OTP 24)
```
* Operating system: 
```
Linux 5.17.1-arch1-1 x86_64
```

### Current behavior

`ExUnit.after_suite` callbacks are not called when no tests were ran. This can happen when in an umbrella application you run a suite of tests using test partitioning. It could shake out that an app has no tests in this partition. This is problematic for things that do setup in `test_helpers` that needs to be reverted before the next application's suite of tests runs.

### Expected behavior

`ExUnit.after_suite` callbacks would be ran if they're setup, even when no tests were ran.

**Comment by josevalim** [comment]
Sounds good! A PR is welcome!
