### ISSUE TITLE
Automatically perform NFC + additions for identifiers

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11753]
We should perform NFC normalization by default and provide a mechanism for additional normalizations (NFKC or others). At first, the only normalization we will perform is latin micro to greek mu found in NFKC. For the normalization, we will change the scriptset of the target letter (in this case, greek mu) to be the union of the scriptset of origin and target characters. Given latin mu is top, the result in this case is top too. This can be implemented programatically.

This rule will help us in the future if we want to handle things like converting Latin epsilon to Greek epsilon, but still distinguishing them from the Ukrainian epsilon-like character.

We should also improve the error messages for non-NFKC characters. If we have an invalid token, we can apply NFKC and try to parse it again. If it succeeds, the error message can tell the user how to properly write the identifier. This should be fully done on `elixir_tokenizer.erl` for now.

Overall, we will have three distinct tasks:

  * [ ] Apply NFC automatically instead of raising
  * [ ] Support additional normalizations as explained above
  * [ ] Improve error messages for identifiers not written in NFKC

See discussion in #11751. /cc @mrluc

**Comment by josevalim** [comment]
Hi @mrluc! Just a quick ping to see if you want to tackle this one. No worries if you can't, then I will put it on my plate as we prepare to v1.14.

**Comment by mrluc** [comment]
@josevalim - sorry for the delay in responding; I managed to circle back and I'm picking it up today.

**Comment by mrluc** [comment]
this ended up slipping into a 2nd week's "shop time" (Friday), sorry about that y'all -- the linked PR addresses the items mentioned in this issue description 👍
