### ISSUE TITLE
Can't run formatter two times in a row in umbrella project (when using formatter plugin)

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#11759]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 22)
```
* Operating system: `Linux 5.16.15-76051615-generic`

### Current behavior

I have an umbrella project that uses Phoenix LiveView, and ever since adding the [HTMLFormatter](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html), every time I run `mix format` I need to recompile the deps to be able to run the formatter again. Formatter succeeds the first time, but the second time it fails with:
```
** (UndefinedFunctionError) function Phoenix.LiveView.HTMLFormatter.format/2 is undefined (module Phoenix.LiveView.HTMLFormatter is not available)
    Phoenix.LiveView.HTMLFormatter.format("Hello!\n", [file: "/home/michal/hello/apps/hello_web/lib/hello_web.ex", line: 5, sigil: :H, modifiers: [], opening_delimiter: "\"\"\"", import_deps: [:phoenix], plugins: [Phoenix.LiveView.HTMLFormatter], inputs: ["*.{heex,ex,exs}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{heex,ex,exs}"]])
    (elixir 1.13.4) lib/code/formatter.ex:1333: Code.Formatter.maybe_sigil_to_algebra/4
    (elixir 1.13.4) lib/code/formatter.ex:458: Code.Formatter.quoted_to_algebra/3
    (elixir 1.13.4) lib/code/formatter.ex:549: anonymous fn/3 in Code.Formatter.block_args_to_algebra/4
    (elixir 1.13.4) lib/code/formatter.ex:1898: Code.Formatter.each_quoted_to_algebra_with_comments/6
    (elixir 1.13.4) lib/code/formatter.ex:1876: Code.Formatter.quoted_to_algebra_with_comments/6
    (elixir 1.13.4) lib/code/formatter.ex:554: Code.Formatter.block_args_to_algebra/4
    (elixir 1.13.4) lib/code/formatter.ex:1796: Code.Formatter.clauses_to_algebra/4
```

To be able to run `mix format` again, I need to recompile the dependency that provides the formatter plugin with `mix deps.compile`

I have reduced the issue to an [example project](https://github.com/michallepicki/formatter-two-times-bug). It is a new project created with `mix new hello --umbrella` and a `mix new hello` project inside of it, with `{:phoenix_live_view, "~> 0.16"}` dependency added, [HTMLFormatter](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html) configured, and a LiveView module file:
```elixir
defmodule HelloWeb do
  use Phoenix.LiveView

  def render(assigns) do
    ~H"""
    Hello!
    """
  end

  def mount(_params, %{}, socket) do
    {:ok, socket}
  end
end
```

### Expected behavior

Running the formatter for the second time in a row should not error

### Notes
I was not sure if this issue belongs here or phoenix_live_view, where the formatter plugin comes from

**Comment by josevalim** [comment]
Please check https://github.com/phoenixframework/phoenix_live_view/issues/1969 :)
