### ISSUE TITLE
mix run freezes computer

### ISSUE THREAD

**Issue by Abdul-Muiz-Iqbal** [elixir-lang/elixir#11766]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]

Elixir 1.13.2 (compiled with Erlang/OTP 24)
* Operating system: 
Fedora Linux 35 Xfce Version 4.16

### Current behavior
Running the command mix run starts compiling the project, however after 10 seconds it says that compilation is taking more than 10 seconds. After this the computer freezes for a few minutes before crashing and logging me out. Upon checking memory usage, I found that the command would completely max out my memory, thus the freezing.

### Expected behavior
The code should compile without issue.

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces the error? It is most likely something related to your application code that is taking too long to compile, so you need to isolate that so we can reproduce it. Thanks!

**Comment by josevalim** [comment]
If you have more information, please let us know!
