### ISSUE TITLE
Flag `ordered: false` in Task.async_stream and Task.Supervisor.async_stream_no_link causes crazy memory usage.

### ISSUE THREAD

**Issue by dingpl716** [elixir-lang/elixir#11760]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.7.2.1]
Elixir (1.10.3)
```   
* Operating system: `macOS Big Sur 11.1`

### Current behavior

I monitored following code with Prometheus metrics `erlang_vm_memory_bytes_total`. From the screenshot below you can see that when flag `ordered:false` was added, the VM memory grows very quickly, but when the flag is removed (by default it is `true`), the memory usage is stable.

Code to Repro:
```
    1..10_000_000
    |> Task.async_stream(&process_line/1, ordered: false)
    |> Stream.run()

  defp process_line(_) do
      :ok
  end
```
<img width="1776" alt="Screen Shot 2022-04-16 at 6 38 24 PM" src="https://user-images.githubusercontent.com/3527426/163696687-6a752b9f-24dd-47bc-baaf-961318b94f1d.png">

### Expected behavior

Intuitively speaking, since `ordered: false` does less things than `ordered: true`, I think it should consume less memory than what it does now.

**Comment by josevalim** [comment]
Yes, there was a bug where we held processes for longer than we should. Please try latest Elixir and let us know if the issue persists.

**Comment by josevalim** [comment]
I just want to say I cannot reproduce it on latest Elixir indeed. :) Please confirm and let me know, thanks for the report!

**Comment by dingpl716** [comment]
Yea, the issues does not exist on latest elixir. Closing the issue now.
