### ISSUE TITLE
Output for `compile_env` checks not showing sometimes

### ISSUE THREAD

**Issue by escobera** [elixir-lang/elixir#11771]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Elixir 1.13.3 (compiled with Erlang/OTP 24)

* Operating system: 

Tested on Manjaro Linux and Arch on WSL2 

### Current behavior
This is an intermitent error, so it is a little cumbersome to reproduce.

When I start an application with a compile-time configuration that's been overwritten at runtime sometimes the error doesn't show properly:

Sometimes it simply doesn't show the elixir formatted error, only the erlang part, like this:
```
❯ _build/dev/rel/dev_app/bin/dev_app start
{"init terminating in do_boot",{<<"aborting boot">>,[{'Elixir.Config.Provider',boot,2,[]}]}}
init terminating in do_boot ({,[{Elixir.Config.Provider,boot,2,[]}]})
```

Steps to reproduce

1 - Create a new app with `mix new dev_app --sup`
2 - `cd dev_app`
3 - Change `lib/dev_app.ex` to: 
```elixir
defmodule DevApp do
  # this creates the compile time check
  @test_attr Application.compile_env(:dev_app, :test_attr, false)
  def hello do
    :world
  end
end
```
4 - Add a `config/runtime.ex` with the following contents:
```elixir
import Config
#this changes the config value at runtime to trigger the error
config :dev_app, test_attr: "test"
```
4 - run `mix compile`
5 - try starting the app with `_build/dev/rel/dev_app/bin/dev_app start` multiple times until the error occurs.

### Expected behavior

The expected message is as following:
```
❯ _build/dev/rel/dev_app/bin/dev_app start
ERROR! the application :dev_app has a different value set for key :test_attr during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was not set
  * Runtime value was set to: "test"

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile dev_app --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag


{"init terminating in do_boot",{<<"aborting boot">>,[{'Elixir.Config.Provider',boot,2,[]}]}}
init terminating in do_boot ({,[{Elixir.Config.Provider,boot,2,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by josevalim** [comment]
Thanks! I have “fixed” this earlier today by using stdio instead of stderr. It may still happen in some cases, but it should be considerably less frequent in my tests. :)

**Comment by escobera** [comment]
lol, I can't keep up with your speed 😆
