### ISSUE TITLE
`mix`: Example for `escript.build` is misleading

### ISSUE THREAD

**Issue by NobbZ** [elixir-lang/elixir#11770]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Documentation of `mix` 1.13.x, probably others
* Operating system: all

### Current behavior

https://hexdocs.pm/mix/Mix.Tasks.Escript.Build.html#module-example

The linked example has a single code block showing 2 modules. The way it is displayed made some people think, it would work to have the mix project and the escript main module within the same `mix.exs`.

### Expected behavior

It should be made more clear that the modules need to be in separate files, of which the escripts implementation needs to be `lib/*.ex` rather than an `*.exs`.

**Comment by josevalim** [comment]
Can you please provide a PR? :)
