### ISSUE TITLE
inet_gethost.exe path error

### ISSUE THREAD

**Issue by kotsius** [elixir-lang/elixir#11785]
### Environment

• Erlang/OTP 24⦗.3.3⦘ [erts-12.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]
• Elixir 1.13.4 (compiled with Erlang/OTP 22)
• Windows 10 Pro v20H2

### Current behavior

"elixir myFile.exs", "mix ecto.create", "mix ecto.migrate" output:

C:\Program Unknown option "Files\+Programming\Erlang\erts-12.3.1\bin\inet_gethost.exe"
Usage: C:\Program [-d [-d ...]] [-g ‹greedy threshold›] [‹number of workers›]

### Expected behavior

No error message. Calling inet_gethost.exe should be able to handle the space in 'Program Files'.
I guess that the solution would involve placing the inet_gethost execution path inside quotes.

**Comment by josevalim** [comment]
Hi @kotsius. Can you please try typing out "erl" or "werl"? My suspicion is that this is rather an Erlang issue. Thank you.

**Comment by kotsius** [comment]
Thanks @josevalim.

Passing --werl to "mix ecto.create" and "mix ecto.migrate" does not seem to be an option. Whereas "elixir myFile.exs" does not call inet_gethost.exe consistently, so test results are not conclusive.

It may well be an Erlang issue. I just thought I should raise a flag, in case this was something that could be easily resolved. Please feel free to close the issue if nothing else can be done at this end.

**Comment by josevalim** [comment]
Sorry, I mean to type `erl` and `werl` directly as to start Erlang instead of Elixir. :)

**Comment by kotsius** [comment]
My rudimentary testing suggests that "werl myFile.exs" does not output the error ("erl myFile.exs" fails to complete for unknown reason). Therefore, either inet_gethost.exe is called correctly, or it is not called at all.

I presume that werl is not meant to be used with mix (I could not find any examples online).

**Comment by josevalim** [comment]
@kotsius does the error happen when you call just `iex` or `erl`? Passing no arguments whatsoever?

**Comment by kotsius** [comment]
No, I can call both iex and erl without arguments. There is no error.

**Comment by josevalim** [comment]
Oh, so can you share the contents of `myFile.exs`? :) Or a minimal necessary to reproduce the error?

**Comment by kotsius** [comment]
I could share the contents privately, but as I said, "elixir myFile.exs" does not call inet_gethost.exe consistently. I rebooted my PC for every test, as subsequent calls do not produce the error. On the other hand, "mix ecto.create" and "mix ecto.migrate" seem to be more consistent.

**Comment by josevalim** [comment]
I see. This is definitely an Erlang issue then and we need to find a way to isolate it. Does this reproduce it?

    elixir -e ":ssl.start(); Application.start(:inets); IO.inspect :httpc.request('https://google.com')"

**Comment by kotsius** [comment]
No, the error is not in the output.

**Comment by josevalim** [comment]
What about `elixir -e "IO.inspect :inet.gethostbyname 'google.com'"`? And what does `elixir -e "IO.inspect :inet.get_rc"` print?

**Comment by kotsius** [comment]
No error. [lookup: [:native]]

**Comment by josevalim** [comment]
What is your database connection hostname? Can you try looking it up on :inet instead and see if it reproduces it?

**Comment by kotsius** [comment]
elixir -e "IO.inspect :inet.gethostbyname 'localhost'"
elixir -e "IO.inspect :inet.gethostbyname 'myComputerName'"
both output {:ok, {:hostent, 'myComputerName', [], :inet, ⦗...⦘}. No errors, therefore. Also note that 'myFile.exs' is my custom static asset digest processor for Phoenix. It does not connect to the database.

**Comment by josevalim** [comment]
Thank you! What about `elixir --sname foo -e "IO.inspect :inet.gethostbyname 'localhost'"`?

If you have any ideas on how to reproduce the issue consistently, please let us know. Otherwise there isn't much we can do. :'(

**Comment by kotsius** [comment]
No error either. When it comes to consistency, "mix ecto.create" outputs the error every time. Despite this, we probably have to put up with this minor bug, until someone else comes along with more hints about it.

**Comment by josevalim** [comment]
Which database are you using? Maybe you can try running `mix run --no-start --eval "Ecto.Adapters.Postgres.storage_up(database: "foo", hostname: "bar")`, passing your credentials and see if that triggers it?

**Comment by kotsius** [comment]
mix run --no-start -e "Ecto.Adapters.Postgres
  .storage_up(database: 'myDatabase', hostname: 'localhost', username: 'myUser', password: 'myPwd')"

returns (twice):
  ** (Postgrex.Error) FATAL 28P01 (invalid_password) password authentication failed for user "myUser"
      (db_connection 2.4.2) lib/db_connection/connection.ex: 100: DBConnection.Connection.connect/2
      (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
      (stdlib 3.17.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

I have double-checked the password and tried with 2 different users. Could this be relevant?

**Comment by josevalim** [comment]
I don't think it should be relevant but if that does not reproduce the inet_gethost error, I don't know what can. :D

**Comment by kotsius** [comment]
Many thanks for your commendable efforts.

**Comment by josevalim** [comment]
Closing this for now as we cannot reliably reproduce it. If anyone can break it down, please do drop a comment. Thank you!

**Comment by inikulshin** [comment]
@josevalim 

I think this bug was fixed in 25.0 by https://github.com/erlang/otp/commit/a32f6d210a58ba1e56f54f07c91106efed2c0777 and later commits in `lib/kernel/src/inet_gethost_native.erl` as `open_port` call was changed from `spawn` to `spawn_executable`

https://www.erlang.org/doc/man/erlang.html#open_port-2

> {spawn, Command}
> ... If spaces in executable filenames are desired, use {spawn_executable, Command} instead.

I don't know if it should be merged also into 24.* or not.

---

However, I also think there is a bug in `erts/emulator/sys/win32/sys.c` in `spawn` mode:

If `static int application_type` is ran with `inet_gethost`, the output path (`wfullpath`) may contain spaces, but `requote` output will be `FALSE`, as it set by **input** and not by **output**,

After that the following code will produce `newcmdline` with **unquoted** `execPath`:

        if (requote) {
            wcscat(newcmdline, L"\"");
        }
        wcscat(newcmdline, execPath);
        if (requote) {
            wcscat(newcmdline, L"\"");
        }

And finally, `CreateProcessW` with both non-NULL `execPath` and `newcmdline` will cause to process to run, but the 'newcmdline' will be split to `argv`: `argv[0] = "C:\Program"` and `argv[1] = "Files+Programming\Erlang\erts-12.3.1\bin\inet_gethost.exe"`

**Comment by inikulshin** [comment]
It's introduced in https://github.com/erlang/otp/commit/f0a273c5a5ebfc97cfe1e88341c803b85d2295e4

@raimoniskanen FYI

**Comment by josevalim** [comment]
Awesome find @inikulshin! Can you please report this in the Erlang/OTP repo?

**Comment by inikulshin** [comment]
@josevalim haha, I was sure I'm already commenting Erlang/OTP repo.

Sure.
