### ISSUE TITLE
String.to_existing_atom throwing an exception with an already existing atom

### ISSUE THREAD

**Issue by thiagomajesk** [elixir-lang/elixir#11786]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```
* Operating system: Ubuntu-20.04 WSL2 instance under Windows 11

### Current behavior

While on an iex session using `iex -S mix`, I get an error converting a string to an atom that definitely exists:

```
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom
 
    :erlang.binary_to_existing_atom("d4", :utf8)
```

Interestingly enough, when loading the module that contains the atom isolated with `iex file.ex`, it works as expected. The conversion also works if I create a separate project with only the module that declares the atom. 

I was using another Elixir version when I noticed this error initially, but it seems that after mixing and matching with other OTP versions I managed to make the error happen more consistently. I even managed to make it go away once, by assigning a list of atoms to an unused variable before doing the conversion (really weird behavior). 

![visual-repro](https://user-images.githubusercontent.com/13930952/166114187-06403f75-d665-4ef0-b8ea-11e2a55ff9f4.gif)

I can't find a proper way of reproducing this error outside of the project's context as it seems to be something very specific. Since I can't make the project public and this is really outside of my area of knowledge, I'm willing to pair with someone to show what's actually happening or share the private repository so we can make some tests together.

### Expected behavior

`String.to_existing_atom` should actually be returning the existing atom instead of throwing.

**Comment by josevalim** [comment]
Atoms are loaded when the module that defines them is loaded. In your example, the module has not been loaded, so the only atoms that you can load are the ones loaded defined in other modules. If you invoke any function in the module with the die, then all atoms should be available, and it will work. I will improve the docs.

**Comment by thiagomajesk** [comment]
Hey @josevalim, what do you mean by that the module is not loaded? But also, see that "df" is converted while "d4" is not and both are used and defined is the same places.

**Comment by josevalim** [comment]
`df` was likely defined by another module.

**Comment by thiagomajesk** [comment]
> df was likely defined by another module (that has already been loaded).

Oh ok, thanks... I think that kinda confirms my suspicion then, but I have to ask to be sure: Is the atom table shared? I mean, I can confirm that my code is not defining the atom `df` anywhere, so it's likely being defined in a third-party library then (which is an interesting surprise, given that `df` is not quite a common acronym and that really tripped me up 😅).

I found a way to list all defining atoms in the VM with: `for i <- 0..:erlang.system_info(:atom_count)-1, do: :erlang.binary_to_term(<<131,75,i::24>>)` and I see that it's there, but I don't know if it's possible to track where it's being defined (this would be really helpful).

Nonetheless, thanks again for the explanations, I wonder if other people got confused by this in the past (it surely will help have this in the docs now)🙈.
