### ISSUE TITLE
test.coverage does not ignore modules properly in umbrella applications

### ISSUE THREAD

**Issue by jared-mackey** [elixir-lang/elixir#11783]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.13.4
* Operating system: Arch/Linux

### Current behavior

Running `mix test --cover --export-coverage cov && mix test.coverage`  from the root of an umbrella application does not ignore coverage for modules defined in each sub applications `ignore_modules` option. Moving them to only the root `mix.exs`'s `ignore_modules` option works for when running from the root but then they don't inherit properly when doing `mix cmd ...` or simply changing to that app directory and running from the app. Additionally, `mix test --cover` by itself seems to be working correctly, it is just when using partitioning or exporting coverage that it is not working.

### Expected behavior

`ignore_modules` should apply regardless of where the invocation is coming from.

**Comment by jared-mackey** [comment]
Oh, I had missed this piece of documentation.

```
  When running `test.coverage` from the umbrella root, it
  will use the `:test_coverage` configuration from the umbrella root.
 ```

Which I guess makes sense but feels a bit weird. Especially since you'd have to duplicate those configurations down to each umbrella application if you wanted to get the same results between running from the root and running from the sub app.

Is there a way to have a sub app call functions from the root mix project file or vice versa? Maybe a bit beyond the scope of this issue but that is one of my common run ins when doing this kind of configuration is duplication between sub apps mix project file and/or root mix project file.

**Comment by josevalim** [comment]
Generally speaking umbrellas do not load configuration from the children, so the duplication is necessary. You can have a shared.exs file that you load with Code.require_all from all mix.exs files with shared configuration though.
