### ISSUE TITLE
Remove `Kernel.to_char_list/1`

### ISSUE THREAD

**Issue by moogle19** [elixir-lang/elixir#11789]
`Kernel.to_char_list/1` was (soft-)deprecated 5 years ago and emits a warning since 2 years.
I think it could be remove with Elixir 1.14 or is there a reason, why it shouldn't be removed?

**Comment by michallepicki** [comment]
If I understand the [Compatibility and Deprecations documentation](https://hexdocs.pm/elixir/1.13.4/compatibility-and-deprecations.html#policy) correctly, it will be removed when/if Elixir 2.0 is released

**Comment by ericmj** [comment]
Deprecated functionality will be removed on the next major version release 2.0.0.
