### ISSUE TITLE
`@deprecated` with multiple default values prints multiple warnings

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#11797]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.14.0-dev (abda4a1) (compiled with Erlang/OTP 25)`
* Operating system: macOS

### Current behavior

```
iex(1)> defmodule Finch do
...(1)>   @doc false
...(1)>   @deprecated "Finch.request/6 is deprecated, use Finch.build/5 + Finch.request/3 instead"
...(1)>   def request(name, method, url, headers, body \\ nil, opts \\ []) do
...(1)>     {name, method, url, headers, body, opts}
...(1)>   end
...(1)> end
{:module, Finch,
 <<70, 79, 82, 49, 0, 0, 8, 136, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 164,
   0, 0, 0, 16, 12, 69, 108, 105, 120, 105, 114, 46, 70, 105, 110, 99, 104, 8,
   95, 95, 105, 110, 102, 111, 95, 95, 10, ...>>, {:request, 6}}
iex(2)> Finch.request(MyApp.Finch, :get, "https://elixir-lang.org", [])
warning: Finch.request/4 is deprecated. Finch.request/6 is deprecated, use Finch.build/5 + Finch.request/3 instead
  iex:2

warning: Finch.request/4 is deprecated. Finch.request/6 is deprecated, use Finch.build/5 + Finch.request/3 instead
  iex:2

{MyApp.Finch, :get, "https://elixir-lang.org", [], nil, []}
```

### Expected behavior

Just one warning.

**Comment by eksperimental** [comment]
May I pick this one up?

**Comment by josevalim** [comment]
Yes please!

**Comment by eksperimental** [comment]
I'm already working on it.

Upon investigation, I can mention that:
1. It is unrelated to default values.
2. It only happens in IEx.
3. The culprit is `lib/elixir/src/elixir_dispatch.erl`
3. It has been introduced in the current development version

I will later on do a `git bisect` to see to find the commit that introduced the bug, and see how it can be tackled.

**Comment by eksperimental** [comment]
Ran the bisect.
The commit that introduced this bug is: 395b0534f0e5312ab3ebbb9a9f9bc8da224ffdd8

Here's the reduced case that emits the double warning:
```elixir
      defmodule Foo do
        @deprecated "Use :bar instead."
        def bar(), do: :bar
        end
      end

      Foo.bar()
```

**Comment by josevalim** [comment]
Awesome investigation. I pushed another fix to the evaluator, which seems to also have fixed this. Thanks @eksperimental!

**Comment by eksperimental** [comment]
@josevalim Awesome. I'm glad this could be solved. BTW I don't see the changes in the commit history yet. Looking forward to read the solution.

**Comment by josevalim** [comment]
It should be this one: https://github.com/elixir-lang/elixir/commit/f3259958bf42177b4759a59cf9fe28a08599a370
