### ISSUE TITLE
Formatter will complain about empty .exs files

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11800]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): v1.13.4 / OTP 24
* Operating system: Linux

### Current behavior

I have `config/dev.exs` file which is empty. The formatter  complains about it not being formatted.
When I run `mix format` it will add a new line.

### Expected behavior

To not to complain, and accept that some files can be just empty.

**Comment by josevalim** [comment]
Agreed. PRs welcome!
