### ISSUE TITLE
Enum.sort_by/3 works faster with `:asc` than with `&<=/2`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11808]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): main / OTP 24
* Operating system: Linux

### Current behavior

The benchmark:
https://github.com/eksperimental/benchmark/blob/enum_sort_by/benchmarks/enum_sort_by_default_sorter.exs

The benchmark results:
https://gist.github.com/eksperimental/f16e6df01e193cf075157a932bcd573c

The current default could go from 1.52x to 2.21x slower,
same for memory, so my suggestion is to switch to `:asc`, plus the default sorter for `List.keysort/3` is currently `:asc` so it aligns with ti.

**Comment by josevalim** [comment]
Yes, PR please!

**Comment by eksperimental** [comment]
Alright

**Comment by josevalim** [comment]
Ping because I think you forgot :)

**Comment by eksperimental** [comment]
I haven't  :D 
I was busy with the other PRs. This one require tweaking the docs which are based the default argument. I will have it ready for soon.

**Comment by josevalim** [comment]
And here i was thinking it was a 1LOC change. Sorry for the ping then!
