### ISSUE TITLE
Recompilation not always considered for path deps

### ISSUE THREAD

**Issue by jjcarstens** [elixir-lang/elixir#11818]
Environment

Elixir & Erlang/OTP versions (elixir --version): Elixir 1.13.4 (compiled with Erlang/OTP 24)
Operating system: MacOS 12.3

### Current behavior

TL;DR If your lib `:a` has a path dependency `:b` and you update one of `:b`'s dependencies from `:a`, then `:b` is not aways considered for recompilation due to the dependency update and can produce broken code. 

Background: Using path dependencies in a ["poncho"](https://embedded-elixir.com/post/2017-05-19-poncho-projects/) style setup is a coming practice for Nerves firmware due to issues between Nerves tooling and umbrella project tooling. Its essentially a mono repo and your firmware lib references a bunch of path dependencies when building the firmware bundle

Example project at https://github.com/jjcarstens/path_recompile

<details>
<summary>Example & Explanation </summary>

To explain, we're going to pick on `ecto` a bit (cause this is how I discovered it 🤣)

I have a project structure like so (`:a` depends on `:b` which is in the same root. `:b` is the database):

```sh
> a √ % mix deps.tree
a
└── b (../b)
    ├── ecto 3.7.2 (Hex package)
    │   ├── decimal ~> 1.6 or ~> 2.0 (Hex package)
    │   └── telemetry ~> 0.4 or ~> 1.0 (Hex package)
    ├── ecto_sqlite3 ~> 0.7 (Hex package)
    │   ├── decimal ~> 1.6 or ~> 2.0 (Hex package)
    │   ├── ecto ~> 3.7 (Hex package)
    │   ├── ecto_sql ~> 3.7 (Hex package)
    │   │   ├── db_connection ~> 2.2 (Hex package)
    │   │   │   ├── connection ~> 1.0 (Hex package)
    │   │   │   └── telemetry ~> 0.4 or ~> 1.0 (Hex package)
    │   │   ├── ecto ~> 3.7.0 (Hex package)
    │   │   └── telemetry ~> 0.4.0 or ~> 1.0 (Hex package)
    │   └── exqlite ~> 0.9 (Hex package)
    └── exqlite ~> 0.11 (Hex package)
        ├── db_connection ~> 2.1 (Hex package)
        └── elixir_make ~> 0.6 (Hex package)
```

Its currently using `ecto 3.7.2` and everything is golden and running as expected:

```elixir
> a ?1 % iex -S mix
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

==> b
Generated b app
Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> B.transaction(fn -> :ok end)

17:46:22.904 [debug] QUERY OK db=1.0ms idle=1374.6ms
begin []
 
17:46:22.906 [debug] QUERY OK db=0.1ms
commit []
{:ok, :ok}
```

I then update to `ecto 3.8.3` from my `:a` lib (remembering that `ecto` is a transient dep from `:b` technically), and the same function is totally broken:

```elixir
> a ?1 % mix deps.update --all
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  connection 1.1.0
  db_connection 2.4.2
  decimal 2.0.0
  ecto_sqlite3 0.7.4
  elixir_make 0.6.3
  exqlite 0.11.0
  telemetry 1.1.0
Upgraded:
  ecto 3.7.2 => 3.8.3
  ecto_sql 3.7.2 => 3.8.1
* Updating ecto (Hex package)
* Updating ecto_sql (Hex package)

> a √ % iex -S mix
Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

==> ecto
Compiling 56 files (.ex)
Generated ecto app
==> ecto_sql
Compiling 26 files (.ex)
Generated ecto_sql app
==> ecto_sqlite3
Compiling 4 files (.ex)
warning: function query_many/4 required by behaviour Ecto.Adapters.SQL.Connection is not implemented (in module Ecto.Adapters.SQLite3.Connection)
  lib/ecto/adapters/sqlite3/connection.ex:1: Ecto.Adapters.SQLite3.Connection (module)

Generated ecto_sqlite3 app
==> b
Generated b app
==> a
Generated a app
Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> B.transaction fn-> :ok end
** (FunctionClauseError) no function clause matching in Ecto.Repo.Transaction.transaction/4    
    
    The following arguments were given to Ecto.Repo.Transaction.transaction/4:
    
        # 1
        B
    
        # 2 
        B
    
        # 3
        #Function<45.65746770/0 in :erl_eval.expr/5>
    
        # 4
        []
    
    Attempted function clauses (showing 3 out of 3):
    
        def transaction(_repo, _name, fun, {adapter_meta, opts}) when is_function(fun, 0)
        def transaction(repo, _name, fun, {adapter_meta, opts}) when is_function(fun, 1)
        def transaction(repo, _name, %Ecto.Multi{} = multi, {adapter_meta, opts})
    
    (ecto 3.8.3) lib/ecto/repo/transaction.ex:5: Ecto.Repo.Transaction.transaction/4
```

Why aren't I putting this in the `ecto` repo then?? Well, it took a bit of digging but it turns out that my `:b` lib is not being recompiled. In the output above, you can see that it is simply "generated":

```sh
...
==> b
Generated b app
==> a
Generated a app
...
```

And thats problematic because the change from ecto 3.7 to 3.8 included some pretty major changes in the `__using__` macro of `Ecto.Repo` behavior. However, its all in the generated functions of the macro so there was no need to update that as potentially breaking since its internal to the lib...except in my case where my path dependency that does `use Ecto.Repo` did not recompile with the update, leading to the function failure above 🎉 

I confirmed this 2 ways:
* Used https://github.com/michalmuskala/decompile lib to decompile the beam code and see the definitions before and after the update
* `rm -rf _build`, recompiled, and everything was 👌
</details>
 
### Expected behavior

I'd expect the dep update in `:a` to trigger a recompilation of path dependency of `:b` - If this is handled in umbrella projects, I guess that might mean Nerves needs to check into that again?

**Comment by wojtekmach** [comment]
I believe the same problem exists for Hex dependencies. That is, in libraries instead of doing things like these at compile-time:

```elixir
if Code.ensure_loaded?(Jason) do
  def decode(x), do: Jason.decode!(x)
else
  raise "missing :jason dependency"
end
```

we'd have to do them at runtime:

```elixir
def decode(x) do
  if Code.ensure_loaded?(Jason) do
    # ...
  else
    # ...
  end
end
```

If we can track optional deps and once they are added at the top-level, recompile the affected deps, I think we could go with doing things at compile-time which I think would be a win.

**Comment by josevalim** [comment]
We do track optional dependencies for Hex dependencies, so that works. I believe the issue here is that path dependencies are always recompiled, so the go through a different code path, which has this bug.
