### ISSUE TITLE
Support filename in `mix format -` when reading from stdin for plugin detection

### ISSUE THREAD

**Issue by ascandella** [elixir-lang/elixir#11817]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
`Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
Elixir 1.13.0 (compiled with Erlang/OTP 24)`
* Operating system:
`Linux 5.13.0`

### Current behavior

Running `mix format -` to read from stdin works correctly when piped `.ex` or `.exs` files. However, when using plugin-based formatting (for example, the `:phoenix_live_view` / `Phoenix.LiveView.HTMLFormatter`), there's no way to specify the extension so `mix format` crashes when reading the file.

Example:

```sh
$ cat .formatter.exs                 
[
  import_deps: [:ecto, :phoenix, :phoenix_live_view],
  plugins: [Phoenix.LiveView.HTMLFormatter],
  inputs: ["*.{ex,exs,heex}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs,heex}"],
  subdirectories: ["priv/*/migrations"]
]

$ cat test.html.heex               
<div>
hello</div>

$ cat test.html.heex | mix format -
mix format failed for stdin
** (SyntaxError) stdin:1:1: syntax error before: '<'
    |
  1 | <div>
    | ^
    (elixir 1.13.0) lib/code.ex:737: Code.format_string!/2
    (mix 1.13.0) lib/mix/tasks/format.ex:544: Mix.Tasks.Format.elixir_format/2
    (mix 1.13.0) lib/mix/tasks/format.ex:560: Mix.Tasks.Format.format_file/2
    (elixir 1.13.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.13.0) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

$ mix format test.html.heex
$ cat test.html.heex               
<div>
  hello
</div>
```

This seems to boil down to this code: https://github.com/elixir-lang/elixir/blob/a1527dce9dfdafa240f2a79c13a2763842b6d371/lib/mix/lib/mix/tasks/format.ex#L456-L461

### Expected behavior

I'd like the ability to pass a flag in addition to `-` for reading from stdin so that `mix format` can pick the correct parser/formatter for `.heex` code.

This is especially useful with editor plugins (formatting without save). On other tools, this is frequently called `--stdin-filepath` or `--stdin-filename`

### Open to working on this

If this is deemed worthy of supporting, I'm happy to put a PR together adding said functionality

**Comment by josevalim** [comment]
`--stdin-filename` sounds great to me. A PR is welcome!
