### ISSUE TITLE
How do I disable semantic recompilation?

### ISSUE THREAD

**Issue by michaelklishin** [elixir-lang/elixir#11812]
Apologies for using an issue to ask a question but you folks don't have GitHub Discussions enabled
and I am too lazy to sign up for Elixir Forum.

Team RabbitMQ has adopted Bazel in recent months and it builds our entire tree of Erlang and Elixir subprojects. As of [Elixir 1.13](https://github.com/elixir-lang/elixir/blob/v1.13/CHANGELOG.md), we have started seeing obscure
failures about CLI tool modules not being compiled.

It turns out, 1.13 ships with a [smarter recompilation feature](https://github.com/elixir-lang/elixir/blob/v1.13/CHANGELOG.md#semantic-recompilation) in Mix, which makes a lot of sense.
However, for us not using Mix as the primary tool, this is now a headache since it's not
Mix that decides the state of the overall build.

Is there a way to force Mix to compile the project "the good ole way" that Bazel users can
try? Without running clean first, of course, that would our last resort.

Thank you.

**Comment by josevalim** [comment]
Hi @michaelklishin!

Semantic recompilation is not a single feature, but a group of smaller changes which collectively we decided to give it such name. So while we cannot disable it altogether, if you can pinpoint to a particular behavior that is being problematic, then we can likely help. Attempts to isolate and reproduce it can help too!

Also, to avoid confusion, you say you’re not using mix, but semantic recompilation applies only to mix compile. So I assume you are using subsets of Mix?

**Comment by michaelklishin** [comment]
Thank you for the quick response, @josevalim.

We drive Mix from Bazel rules. We also compile some Erlang dependencies (RabbitMQ CLI tools depend on core modules) via Bazel. So we have
a classic build tool competition scenario which Mix in 1.12.x does not run into but 1.13.x does.

It will take a while for us to pin point, so far we have evidence that
this problem is specific to 1.13.x.

I think I have my answer for now so happy to close this issue. If
we find out something more specific we'd follow up. Thanks again.
