### ISSUE TITLE
Unexpected behaviour for `mix test` when line is before the first test declaration

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11825]
### Environment

Elixir & Erlang/OTP versions (elixir --version): 1.13.4 / OTP 24
Operating system: Linux

### Current behavior

Take this repo https://github.com/eksperimental/missing_test/
and run

`mix test test/failing_test_test.exs:3`

![image](https://user-images.githubusercontent.com/9133420/168365929-8648adc6-72aa-4f96-8d06-5fb874c82643.png)

It looks all good. I'm happy.  It all looks green!
Nope. No test was executed. All four tests fail in reality.

### Expected behavior

If no test is executed I expect a message in red or yellow to catch my attention.
Nobody runs `mix test` to run no tests.

Related issue: https://github.com/elixir-lang/elixir/issues/11824

**Comment by josevalim** [comment]
Perfect. Agreed!
