### ISSUE TITLE
Unexpected behaviuor for `mix test LINE_NO`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11824]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.13.4 / OTP 24
* Operating system: Linux

### Current behavior

Take this repo https://github.com/eksperimental/missing_test/
and run

` mix test test/missing_test_test.exs:12`

the test on line 13 shuld fail. I get:

```
.

Finished in 0.01 seconds (0.00s async, 0.01s sync)
4 tests, 0 failures, 3 excluded
```

Even line 12 contains a tag that belongs to the test on line bellow, ExUnit runs the test above that line.

It is kind of weird IMO that it will run the test above and not the test bellow.
There's a mention to this in the docs, but it refers to the `describe` block

### Expected behavior

I would expect if I mention the line of the tags to run the test that that tag belongs to.

**Comment by josevalim** [comment]
I believe this is documented. It is always the test starting at or before the line. This can be useful because you can do file:10000 and always run the latest as you add.

**Comment by josevalim** [comment]
> If a given line starts a describe block, that line filter runs all tests in it. Otherwise, it runs the closest test on or before the given line number.

Also note this is not possible to address otherwise. We don’t know the position attributes are defined. :) only the test macro.

thanks for the report!

**Comment by eksperimental** [comment]
I only found this reference in the  `mix help test`

> If a given line starts a describe block, that line filter runs all tests in it.
> Otherwise, it runs the closest test on or before the given line number.

But if refers to `describe` blocks only.

**Comment by josevalim** [comment]
The second line is not about describe  :)

**Comment by eksperimental** [comment]
I will try to improve the docs a bit to make it even clearer. Thank you
