### ISSUE TITLE
Supervisor child spec is missing :module value explanation

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11830]
As of now, we only mention 
> There is a sixth key, :modules, which is optional and is rarely changed. It is set automatically based on the :start value.

From Erlang docs:
https://www.erlang.org/doc/man/supervisor.html#child_spec

> `modules` is used by the release handler during code replacement to determine which processes are using a certain module. As a rule of thumb, if the child process is a supervisor, gen_server or, gen_statem, this is to be a list with one element [Module], where Module is the callback module. If the child process is an event manager (gen_event) with a dynamic set of callback modules, value dynamic must be used. For more information about release handling, see Release Handling in OTP Design Principles.

**Comment by eksperimental** [comment]
@josevalim I am working on the Supervisor module docs, 
one thing I found is that `Supervisor.start_link/2` accepts both in the specs and function guards, an empty list as `children`. Does it make sense?
If so, I would like to mention this in the docs, if not I would like to correct  the specs and maybe add a guard

**Comment by eksperimental** [comment]
the same goes for `Supervisor.init/2`

**Comment by josevalim** [comment]
Yes. You can start a supervisor with no children, because you want to add children later or because you want an application callback to run something but you don't have any children.

**Comment by josevalim** [comment]
Also, i don't see why we need to call out empty lists. Most functions in Enum and many other modules accept empty lists too... it is a natural property of lists. I think we should call only the opposite (when an empty list is not accepted).

**Comment by eksperimental** [comment]
Ok. Thank you for the clarification. 
I will not mention empty lists explicetly, but there is a case where i need to mention the fact that children could be empty. You will see it in the PR.
