### ISSUE TITLE
ExUnit describe name limit error

### ISSUE THREAD

**Issue by zorbash** [elixir-lang/elixir#11844]
### Environment

Elixir & Erlang/OTP versions (elixir --version):  Erlang/OTP 23 Elixir 1.13.3 (compiled with Erlang/OTP 22)
Operating system: MacOS

### Current behavior

Tests with very verbose names emit an error.

```elixir
ExUnit.start(auto_run: false)

defmodule AQuiteVerboseTest do
  use ExUnit.Case

  describe """
  perform_action/1
  when the parameters are valid
  and the user is logged in
  and the user is a VIP
  and the user has not made a purchase in the last 3 weeks
  and the user likes science fiction books
  """ do
    setup [
      :build_valid_parameters,
      :log_in,
      :make_user_vip,
      :like_science_fiction
    ]
    
    test "email sends a discount code to the user to buy a book by Arthur C. Clarke"

    defp build_valid_parameters(_), do: :ok
    defp log_in(_), do: :ok
    defp make_user_vip(_), do: :ok
    defp like_science_fiction(_), do: :ok
  end
end

ExUnit.run()
```

Running the above crashes with:

```
** (SystemLimitError) a system limit has been reached
    :erlang.binary_to_atom("test perform_action/1\nwhen the parameters are valid\nand the user is logged in\nand the user is a VIP\nand the user has not made a purchase in the last 3 weeks\nand the user likes science fiction books\n email sends a discount code to the user to buy a book by Arthur C. Clarke", :utf8)
    (ex_unit 1.13.3) lib/ex_unit/case.ex:556: ExUnit.Case.register_test/6
    #cell:21: anonymous fn/0 in :elixir_compiler_5.__MODULE__/1
    (ex_unit 1.13.3) lib/ex_unit/case.ex:489: ExUnit.Case.__describe__/4
    #cell:6: (module)
```

Include code samples, errors and stacktraces if appropriate.
If reporting a bug, please include the reproducing steps.

### Expected behavior

It should either not crash or provide a helpful (possibly compile-time) error message for the developer to fix the issue.

### Details

This seems to be happening due to the fact that ExUnit defines each of the `describes` as a function on the test module (in this case `AQuiteVerboseTest`. In order to do so in [ex_unit/case.ex:556](https://github.com/elixir-lang/elixir/blob/v1.13.4/lib/ex_unit/lib/ex_unit/case.ex#L556), `register_test/6` attempts to convert the name into an atom. There is though a system limit of 255 characters in an atom leading to the `SystemLimitError`. Some developers might not be familiar with the "255 characters in an atom" limit making it difficult to diagnose this error.

This issue also affects testing libraries which call `register_test/6` like for example [wallaby](https://github.com/elixir-wallaby/wallaby), where such verbose tests may be more common to describe a user interaction.

I see the opportunity to provide a more helpful error message by checking whether `:"#{test_type} #{describe} #{name}"` is > 255 characters and displaying a specific error message. 

Alternatively, to support longer names, a possible approach I can think of is to generate unique but shorter function names and keep a mapping between the generated function name and the test name in `%ExUnit.Test{}`.

Happy to submit a PR to change this.

Again thank you for ExUnit and all your work keeping Elixir awesome.

**Comment by whatyouhide** [comment]
Hey @zorbash, good catch and thanks for the report. I think a mapping between randomly-generated function names and tests is generally a good idea, but it will be more involved to implement. Starting with an error message when converting the string test/describe name to an atom is probably a good idea in any case, if you want to give that a shot 🙃

**Comment by zorbash** [comment]
Thank you @whatyouhide I'll start working on a PR for a friendlier error message.

**Comment by josevalim** [comment]
Agreed on improving the error message!

> Alternatively, to support longer names, a possible approach I can think of is to generate unique but shorter function names and keep a mapping between the generated function name and the test name in %ExUnit.Test{}.

I don't think we would need a mapping. We always know the function we run in relation to the test, but I don't think ExUnit formatters were designed to consider multiline describes. So if that's something we would want to encourage in the future, that's where most of the work would have to go. So sticking with improving the error message sounds like the right call!
