### ISSUE TITLE
Dynamic supervisors are not calling init/2 callback on start

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11870]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  Elixir 1.14.0-dev (9a4d10e) (compiled with Erlang/OTP 25)
* Operating system: Linux

### Current behavior

As of now the init/2 callback has no efffects when starting the Dynamic Supervisor,
There´ s either a bug or a documentation error.

Documentation for ` c:DynamicSupervisor.init/1` says:

> Callback invoked to start the supervisor and during hot code upgrades.

I have created this demo, 
https://github.com/eksperimental/dyn_sup_init
You can run ` iex -S mix`  and you will get

```
[notice] Application dyn_sup_init exited: DynSupInit.Application.start(:normal, []) returned an error: shutdown: failed to start child: DynSupInit.Sup1
    ** (EXIT) :bye_supervisor
** (Mix) Could not start application dyn_sup_init: DynSupInit.Application.start(:normal, []) returned an error: shutdown: failed to start child: DynSupInit.Sup1
    ** (EXIT) :bye_supervisor
```

You can see the supervisor exists, but it should exist with `:bye_dynamic_supervisor` 

### Expected behavior

To ` init/2`  callback be invoked, or the docs to say something different.

**Comment by josevalim** [comment]
You must use start_link/3: https://hexdocs.pm/elixir/DynamicSupervisor.html#start_link/3 :)

**Comment by eksperimental** [comment]
It is confusing, 1st because ` init/1`  is a required callback, and if you only read de description of ` start_link/1`  it is not clear that it will not be executed.
I see it happens the same in Supervisor, does it happen somewhere else where on version of start_link will call init/1, and  and the other wont?

**Comment by josevalim** [comment]
Only on those two! :) I think we mention it on the module docs but we should likely mention on the individual functions too.

**Comment by eksperimental** [comment]
I´ m calling it a day. I will submit a PR tomorrow if you haven't by then.
