### ISSUE TITLE
Code.Fragment.surround_context doesn't understand __MODULE__ special form

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#11875]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.13, dev

### Current behavior

this one is OK
```
Code.Fragment.surround_context("__MODULE__", {1, 4})
%{begin: {1, 1}, context: {:local_or_var, '__MODULE__'}, end: {1, 11}}
```
not optimal - it’s not a var
```
Code.Fragment.surround_context("__MODULE__.call()", {1, 13})
%{begin: {1, 1}, context: {:dot, {:var, '__MODULE__'}, 'call'}, end: {1, 16}}
```
does not understand submodules
```
Code.Fragment.surround_context("__MODULE__.Submodule", {1, 13})
:none
```
and submodule remote calls
```
Code.Fragment.surround_context("__MODULE__.Submodule.call()", {1, 23})
:none
```
not optimal - does not detect struct
```
Code.Fragment.surround_context("%__MODULE__{}", {1, 5})               
%{begin: {1, 2}, context: {:local_or_var, '__MODULE__'}, end: {1, 12}}
```
submodule struct not working
```
Code.Fragment.surround_context("%__MODULE__.Submodule{}", {1, 14})
:none
```

### Expected behavior

I would expect it to understand special forms like `__MODULE__`, `__ENV__`, etc. It would be great if `Code.Fragment.cursor_context` also did.

**Comment by josevalim** [comment]
For completeness, they are vars at the AST level, so I would say that all result types that are not `:none` are correct. We need to fix the `:none` cases though and update the docs. :)
