### ISSUE TITLE
Unclear stacktrace in Error.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11880]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.14.0-dev (1e5932b) (compiled with Erlang/OTP 25)
* Operating system: Linux

### Current behavior

I was getting an error in my test suite, it was hard to track down.

```
  1) test foo test (MyAppTest)
     test/checker_test.exs:437
     ** (EXIT from #PID<0.312.0>) an exception was raised:
         ** (CaseClauseError) no case clause matching: :none
             (kernel 8.4) erl_erts_errors.erl:754: :erl_erts_errors.format_erlang_error/3
             (kernel 8.4) erl_erts_errors.erl:34: :erl_erts_errors.format_error/2
             (elixir 1.14.0-dev) lib/exception.ex:1693: ErlangError.error_info/3
             (elixir 1.14.0-dev) lib/exception.ex:1575: ErlangError.normalize/2
             (ex_unit 1.14.0-dev) lib/ex_unit/runner.ex:592: ExUnit.Runner.failed/3
             (ex_unit 1.14.0-dev) lib/ex_unit/runner.ex:516: ExUnit.Runner.exec_test/1
             (stdlib 4.0) timer.erl:235: :timer.tc/1
             (ex_unit 1.14.0-dev) lib/ex_unit/runner.ex:463: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4

```

No failing line number in the test, neither the stacktrace.
The error happens when calling Process.send/3 when the destination is an atom with an unregistered name. 
`Process.send(:foo, :bar, [])`

### Expected behavior

A better stacktrace.

**Comment by eksperimental** [comment]
I see this is an inlined function and there's not much we can do.

For the record, this cryptic error was introduced in OTP 24

This is how the error looked like before.

This was the error with OTP 23
```
iex(1)> Process.send(:foo, :bar, [])
** (ArgumentError) argument error
    :erlang.send(:foo, :bar, [])
```

**Comment by josevalim** [comment]
https://github.com/erlang/otp/pull/6028

We should also fix this in Elixir.
