### ISSUE TITLE
Some odd typespecs that use `maybe_improper_list` include `[]` as possible 'improper' terminator

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#11886]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): v1.13.4 (
* Operating system: Linux Manjaro

### Current behavior

The following typespecs in the standard library are written somewhat oddly:
- The builtin `iolist()` type, which is defined as `maybe_improper_list(byte() | binary() | iolist(), binary() | [])` (c.f. [here, but scroll down](https://hexdocs.pm/elixir/1.10.0/typespecs.html#types-and-their-syntax)
- [IO.chardata](https://hexdocs.pm/elixir/1.10.0/IO.html#t:chardata/0)
- [IO.ANSI.ansilist](https://hexdocs.pm/elixir/1.10.0/IO.ANSI.html#t:ansilist/0)

In all three cases, the type is a 
```
maybe_improper_list(_, one_or_more_other_types | [])
```

Why is the empty list listed as possible 'improper' terminator?

### Expected behavior

I would expect these typespecs to have the format of just e.g.

```
maybe_improper_list(_, one_or_more_other_types)
```

because `maybe_improper_list` itself already allows normal 'proper' lists.

**Comment by josevalim** [comment]
I believe it is called `maybe_improper_list` because it can be an empty list altogether, and the empty list is not improper. In any case, we mirror Erlang's own definition of iolist:

    iolist :: maybe_improper_list(byte() | binary() | iolist(), binary() | [])

Which makes me think we are correct. If our interpretation is wrong and someone changes the ERlang definition upstream, we will be glad to mirror it here! :)

**Comment by Qqwy** [comment]
For clarity/posterity: @josevalim I asked this over on the Erlang side. It turns out the definition is correct, but it is the naming which is odd. `maybe_improper_list` should be understood as `list_terminated_by(element_type(), terminator_type())`. 

The result is an improper list when the possibilities of `terminator_type()` does _not_ include `[]` , a proper list when `[]` is the _only_ possibility and 'maybe' an improper list when `[]` is one of the possibilities.

**Comment by josevalim** [comment]
In this case, perhaps the best names and base types would be:

    [] #=> empty list
    nonempty_list(type, terminator)

Which means we can have:

    list(type, terminator) # same as [] | nonempty_list(type, terminator)
    list(type)             # same as list(type, [])
    nonempty_list(type)    # same as nonempty_list(type, [])

Because I don't see why we need to have improper or proper in the name if the argument is the one specifying it. :)
