### ISSUE TITLE
Recently introduced option "nillify_clauses" in Module.get_definition/3 module is misspelt

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#11918]
### Elixir and Erlang/OTP versions

It should by "nilify", not "nillify".

Deprecation will be needed.

I can provide a PR.

### Operating system

Any

### Current behavior

`:nillify_clauses`

### Expected behavior

`:nilify_clauses`

**Comment by josevalim** [comment]
Good catch! I think we should add a new function though, to avoid changing the return type based on an option. Maybe `get_definition_meta` That returns {kind, meta}? Or `get_definition_info`.

**Comment by eksperimental** [comment]
...and deprecate `get_definition/3` ?

**Comment by josevalim** [comment]
Only the option.

**Comment by eksperimental** [comment]
I see now. So we would depreate `get_definition/3` and go back to having only `get_definition/2` as in v1.12 ?

**Comment by josevalim** [comment]
That can be a good way to tackle it, yes!

**Comment by eksperimental** [comment]
Ok, I will submit a PR whenever I get the chance.

By the way, when is the first RC of v1.14 planned (roughly) to be out?

**Comment by josevalim** [comment]
Hopefully in two weeks, I need to go through the issues tracker and trim it down. :)

**Comment by josevalim** [comment]
Ok, I have an idea that does not require adding a new function and it doesn't change the signature. We could simply return an empty list. I am not sure what to call it though. `:emptify_clauses`?  `:empty_clauses`? `:skip_clauses`?

**Comment by eksperimental** [comment]
`:skip_clauses`, `:ignore_clauses`, `:omit_clauses` are good.
I would personally go with `:skip_clauses`

**Comment by josevalim** [comment]
Closing in favor of PR!

**Comment by wojtekmach** [comment]
:empty_clauses and :skip_clauses sound good to me. Maybe slightly more in favour of skip_clauses.
