### ISSUE TITLE
Edge cases of String.starts_with?, String.ends_with? and String.contains?

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#1191]
``` elixir
iex(1)> String.starts_with? "", ""
false
iex(2)> String.ends_with? "", ""
true
iex(3)> String.contains? "", ""
false

iex(4)> String.starts_with? "a", ""
** (ArgumentError) argument error
iex(4)> String.ends_with? "a", ""
true
iex(5)> String.contains? "a", ""
** (ArgumentError) argument error
```
1. Obviously, all three must be consistent between each other.
2. Is it OK to move away from the semantics of `:binary` match and make our own decisions about what the calls above should return?

I see them working like this:

``` elixir
String.starts_with? "", ""  # true
String.ends_with? "", ""    # true
String.contains? "", ""     # true

String.starts_with? "a", "" # true
String.ends_with? "a", ""   # true
String.contains? "a", ""    # true

String.starts_with? "", "a" # false
String.ends_with? "", "a"   # false
String.contains? "", "a"    # false
```

Consequently, the following should also hold:

``` elixir
String.starts_with? "", ["", "a"]  # true
String.ends_with? "b", ["", "a"]   # true
String.contains? "b", ["", "a"]    # true
```

**Comment by MSch** [comment]
Old issue but I just ran into something related...

```elixir
String.contains?("whatever", []) # false
String.contains?("whatever", "") # true
```

IMO `[]` should behave the same way as `""` does, so it's consistent.

Not sure if that could even be changed for 1.1 though?

**Comment by alco** [comment]
Looks like intended behaviour to me. Matching an empty string is different from trying to match an empty list of things. The latter is more similar to `Enum.any?` (does the string contain any of these substrings?):

```elixir
Enum.any?([], & &1 in ["a", "b", "c"])  # false
```

If the list of substrings is empty, it doesn't make sense to say that the target string contains something from it, does it?

**Comment by MSch** [comment]
Right. :)

**Comment by ThomasArts** [comment]
Is there a possibility that the issue is re-introduced?
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.3.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> String.contains? "n", "" 
** (ArgumentError) argument error
    (stdlib) :binary.match("n", "")
    (elixir) lib/string.ex:1699: String.contains?/2
iex(1)>

**Comment by josevalim** [comment]
@ThomasArts we have decided to use the same solution as Erlang which is to fail if the string is empty since the previous behaviour was highly desired by some and highly undersired by others. :)

**Comment by ThomasArts** [comment]
Well... I guess there are algebraic laws that I cannto think of that they are interested in, but I like the following kind of properties to hold

 1) property Start string (StringEqc)
     test/string_eqc.exs:9
     forall({s1, s2} <- {utf8, utf8}) do
       String.starts_with?(s1 <> s2, s1)
     end
     Failed for {"", ""}

But... I can put a non_empty(utf8) instead... just not as clean.

**Comment by josevalim** [comment]
That's a very good point @ThomasArts. I will bring this behaviour back now that we have a good mechanism to explain why it behaves like this. Thank you!

**Comment by ThomasArts** [comment]
And for the other issue mentioned in this discussion, it is natural to not call contains? with an empty list of strings. The property that one is interested in is:

  property "String contains any of the given contents" do
    forall {s1, strings, s3} <- {utf8, non_empty(list(utf8)), utf8} do
      forall s2 <- elements(strings) do
        String.contains?(s1 <> s2 <> s3, strings)
      end
    end
  end

  property "Contains string" do
    forall {s1, s2, s3} <- {utf8, utf8, utf8} do
      String.contains?(s1 <> s2 <> s3, s2)
    end
  end

**Comment by lpil** [comment]
Hi @ThomasArts , if you place ``` on a line before and after your code you will get a monospace font. Syntax highlighting can be achieved by adding the language name after the first 3 ticks.

    ```elixir
    add(1, 2)
    ```

**Comment by ThomasArts** [comment]
Thanks a lot. I tried to get it right, but gave up. Good to know the way it works now.

Regards
Thomas
