### ISSUE TITLE
Printing information about binary optimizations causes the compiler to crash with an error

### ISSUE THREAD

**Issue by rychale** [elixir-lang/elixir#11914]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Operating system

Linux (NixOS)

### Current behavior

When running the code attached like: ERL_COMPILER_OPTIONS=bin_opt_info mix run --no-start bench/decoder_bench.exs

the compiler is crashing with error:

```
Generated elixir_internal_error app
** (CompileError) bench/decoder_bench.exs: internal error in pass beam_ssa_bsm:
exception error: no match of right hand side value []
  in function  beam_ssa_bsm:make_warning/3 (beam_ssa_bsm.erl, line 1014)
  in call from beam_ssa_bsm:add_unopt_binary_info/5 (beam_ssa_bsm.erl, line 1011)
  in call from lists:foldl/3 (lists.erl, line 1350)
  in call from lists:foldl_1/3 (lists.erl, line 1355)
  in call from beam_ssa:fold_instrs_1/4 (beam_ssa.erl, line 833)
  in call from lists:foldl_1/3 (lists.erl, line 1355)
  in call from beam_ssa_bsm:module/2 (beam_ssa_bsm.erl, line 98)
  in call from compile:'-select_passes/2-anonymous-0-'/3 (compile.erl, line 678)
    (stdlib 4.0) lists.erl:1442: :lists.foreach_1/2
```

[decoder_bench.txt](https://github.com/elixir-lang/elixir/files/8876021/decoder_bench.txt)

### Expected behavior

Expecting the compiler to output information about binary optimizations.

**Comment by Qqwy** [comment]
I tried reproducing this issue. Some notes:
- The crash itself is caused in one of Erlang's compilation passes that happens after Elixir itself has finished all of its work
- The particular compiler pass `beam_ssh_bsm` does [bit syntax matching](https://github.com/erlang/otp/blob/eccc556e79f315d1f87c10fb46f2c4af50a63f20/lib/compiler/src/beam_ssa_bsm.erl#L21) optimization.
- The error does _not_ show up using Elixir `1.12.0-otp-24` (running on OTP 25) 
  - But on that version the output looks as follows:
```
Compiling 1 file (.ex)
Generated decoder_problem app
warning: BINARY CREATED: binary is returned from the function
  bench/decoder_bench.exs:20
```
which is also missing the expected information.

- It is highly curious that enabling the `IO.puts` statement fixes the compiler error, and that not passing the `ERL_COMPILER_OPTIONS=bin_opt_info` also fixes the compiler error.


This bug really seems to be an interplay between how the Elixir compiler generates (on OTP 25) Core Erlang, and how the Erlang compiler handles it afterwards.

**Comment by rychale** [comment]
I can reproduce the same issue with

Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.13.1 (compiled with Erlang/OTP 24)


```
[~/git/elixir_internal_error]$ ERL_COMPILER_OPTIONS=bin_opt_info mix run --no-start bench/decoder_bench.txt 
** (CompileError) bench/decoder_bench.txt: internal error in pass beam_ssa_bsm:
exception error: no match of right hand side value []
  in function  beam_ssa_bsm:make_warning/3 (beam_ssa_bsm.erl, line 1015)
  in call from beam_ssa_bsm:add_unopt_binary_info/5 (beam_ssa_bsm.erl, line 1012)
  in call from lists:foldl/3 (lists.erl, line 1267)
  in call from beam_ssa:fold_instrs_1/4 (beam_ssa.erl, line 817)
  in call from lists:foldl/3 (lists.erl, line 1267)
  in call from beam_ssa_bsm:module/2 (beam_ssa_bsm.erl, line 98)
  in call from compile:'-select_passes/2-anonymous-0-'/3 (compile.erl, line 691)
  in call from compile:fold_comp/4 (compile.erl, line 418)
    (stdlib 3.17) lists.erl:1342: :lists.foreach/2
```

**Comment by josevalim** [comment]
This is enough to reproduce the issue too:

```
Module.create(
  Parser,
  quote generated: true do
    def fields(buffer, offset) do
      <<_::binary-size(offset)>> <> fragment = buffer
      # Enabling the next line eliminates the internal compiler error
      # IO.puts(fragment)
    end
  end,
  [file: "foo"]
)
```

**Comment by josevalim** [comment]
Reported upstream here: https://github.com/erlang/otp/issues/6097
