### ISSUE TITLE
Undefined-function warning when $handle_undefined_function is defined

### ISSUE THREAD

**Issue by marcelotto** [elixir-lang/elixir#11922]
### Elixir and Erlang/OTP versions

Elixir 1.13.3 (compiled with Erlang/OTP 24)

### Operating system

macOS Monterey

### Current behavior

Undefined-function warnings like this

```
warning: Mod.fun/2 is undefined or private
```

are also raised for function calls on modules which have a `$handle_undefined_function` implementation handling the call properly.

### Expected behavior

Undefined-function warnings are not raised for modules with a `$handle_undefined_function` implementation.

I’m aware that the use of `$handle_undefined_function` is quite controversial, and I don't want to trigger a new debate here on the usefulness of it. Regardless of the arguments about when this feature should really be used, even if it might be just a few cases where its use is justified, it should be properly usable in these cases, which it isn’t when such warnings are produced.

I’m not describing the scenario I’m using `$handle_undefined_function` in, since I think it doesn’t really matter for the general issue (and, as I’ve said, I don’t want to trigger arguments about when to use the feature), but if it helps in any way, I can provide more details, since it is in the context of an open source project.

**Comment by marcelotto** [comment]
> It is not really a feature we want to encourage, so you can skip the warning by passing `@compile {:no_warn_undefined, Mod}`. You can also set this globally, if so desired, in your mix.exs by setting `xref: [exclude: Mod]`. Thanks!

That's how I handled the situation up to now. Unfortunately, that's not working anymore in a new scenario, where the modules itself are dynamically created.

I would happily try to give it a shot myself on removing the warning in this situation. So, I'd like to explain the situation to maybe change your mind on accepting a PR for this. 

In the [RDF.ex](https://github.com/rdf-elixir/rdf-ex) project, an implementation of RDF in Elixir, [vocabulary namespaces](https://rdf-elixir.dev/rdf-ex/vocabularies.html#defining-vocabulary-namespaces) are an important feature, which allows users to deal with URIs that are omnipresent in RDF, by defining modules which represent the URI namespace for the terms of an RDF vocabulary as a module. Usually, the terms are explicitly defined and the respective functions returning the URI are generated properly. However, there’s also the possibility to define so called non-strict vocabulary namespaces, where the terms are not pre-defined. This feature is implemented using `$handle_undefined_function` by simply concatenating the requested term with the base URI namespace. Although, I explicitly advise users against their use (as they lose compile-time checks), they are useful in certain situations, most prominently in tests. Here I was fine having to ignore the raised undefined-function warnings explicitly.

However, in the latest version of RDF.ex a [graph DSL](https://rdf-elixir.dev/rdf-ex/description-and-graph-dsl.html#graph-builder) was introduced which allows to encode RDF graphs directly in Elixir. For this DSL, it would be very nice to offer users the possibility to declare namespaces in the same way as they are used to from the usual RDF serialization languages and generate such non-strict vocabulary namespace modules ad-hoc. The [implementation of this](https://github.com/rdf-elixir/rdf-ex/commit/eac696114fca6fbb144b3172a87957bb51756816) went very smoothly, but unfortunately produces these annoying warnings, which can’t be ignored anymore, making this feature unusable for projects which care for warnings, so essentially every project.

**Comment by josevalim** [comment]
Theoretically speaking, any `$handle_undefined_function` can be handled by a call function to a function where the polymorphism is the first argument. Instead of `SomeMod.foo(1, 2, 3)` and `SomeMod.bar(1, 2, 3)`, you can do `SomeMod.call(:foo, [1, 2, 3])` and `SomeMod.call(:bar, [1, 2, 3])`. If the arity is the same or known before hand, then you can skip the list too: `SomeMod.call(:foo, 1, 2, 3)` and `SomeMod.call(:bar, 1, 2, 3)`. If it has to be short, then you can rename `call` to `n` for namespaces.

**Comment by marcelotto** [comment]
The vocabulary namespaces try to resemble something like the QName representation of URIs from XML, which is quite common in the RDF world. So, a QName like `ns:term` would be written with RDF.ex in Elixir as `NS.term`. Not only would `NS.call(:term)` strongly deviate from this, it would no longer be consistent with the strict vocabulary namespaces with proper functions for the terms (for which I wouldn't want to sacrifice this form just for consistency with the non-strict form).

I really appreciate your effort to help me find an alternative solution without `$handle_undefined_function` and would be very happy if one existed, but I can't see one which maintains the nice QName-like form. 

One idea I’ll try in the next couple of days is to wrap all the currently generated code in a function in an additional module, where I can generate the `@compile {:no_warn_undefined, Mod}` for the generated ad-hoc namespace modules. I'll report back if it worked out.

However, a few more words on the requested exception for the warning. Regarding the fear that this change would encourage wider use of this "dirty" feature, leading to something like the `method_missing` situation in Ruby: it's already hard enough to use this feature in Elixir, and you really did a fantastic job of cultivating a more clean and explicit style in the community, so that I really can't imagine this to happen in Elixir. In the six years I’m working with Elixir now, I never had the wish to this feature, except in this single instance. And I guess that accurately exemplifies its status: a feature almost never needed, except for the very rare occasions where it is, and then it’s good to have this very specific tool available in the toolbox. 

But I also understand any reluctance on spending efforts for better support of this feature, especially if it introduces too much additional complexity.

**Comment by marcelotto** [comment]
Just for any else in a similar situation stumbling across this issue: I was able to get rid of the warnings by wrapping the generated function calls in an additional function in an additional module, in which I could generate the respective `@compile {:no_warn_undefined, mod}` declarations. See https://github.com/rdf-elixir/rdf-ex/commit/65bb0831b8e37aae2a588d0427e269de051b4a2e
