### ISSUE TITLE
ExUnit.Parameterized causes “warning: variable does not exist” (but runs fine?)

### ISSUE THREAD

**Issue by nathanalderson** [elixir-lang/elixir#11936]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```

### Operating system

Linux (arch)

### Current behavior

I am trying to use `ExUnit.Parameterized`. If I try to run the exact example module in [the documentation](https://hexdocs.pm/ex_parameterized/ExUnit.Parameterized.html), then I get a warning on this line:

```
  # support Callback as `context`
  test_with_params "add params with context", context,
    fn (a, b, expected) ->
      assert a + b == expected
    end do
      [
        {context[:value], 2, 3}  # *** warning here
      ]
  end
```

The warning is `warning: variable "context" does not exist and is being expanded to "context()", please use parentheses to remove the ambiguity or change the variable name`

Interestingly, if I disable warnings as errors the test runs and passes just fine.

### Expected behavior

No warning is issued.

**Comment by josevalim** [comment]
Please file this in the parameterized project issues tracker, as it is most likely something related to their code generation. If not, an issue that isolates and removes ExUnit.Parameterized would be welcome!
