### ISSUE TITLE
`@behaviour` and `@impl` should add runtime dependency

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#11955]
### Elixir and Erlang/OTP versions

main

### Operating system

macOS

### Current behavior

Currently `@behaviour` adds a compile-time dependency. It doesn't change code being compiled it just emits a warning. And so it can be a runtime dependency and handled in a group pass.

### Expected behavior

`@behaviour` should add a runtime dependency.

**Comment by wojtekmach** [comment]
@marcandre you may like this one. :) Thank you for [this] and other Hex.pm PRs around re-compilation!

[this]: https://github.com/hexpm/hexpm/pull/1144

**Comment by josevalim** [comment]
This is a tricky one but I will be glad to sit and discuss @marcandre if you are interested!

**Comment by marcandre** [comment]
It makes sense that checking of behaviour match can be done outside of both the implementation and the spec files, I should have thought of that.

I can definitely have a look at it, even though it seems pretty intimidating 😅

**Comment by josevalim** [comment]
I shot you an email in case you want to jump into a call!

**Comment by marcandre** [comment]
Ah, passing a behaviour to `defoverridable/1` / `Module.make_overridable` will now have to introduce a compile-time dependency.
