### ISSUE TITLE
Add string_to_quoted in Code.Fragment

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#11967]
The idea is that the code will be incomplete and we will try to fix it.

@lukaszsamson, is the cursor position relevant when trying to fix it? Or do we rely exclusively on indentation?

**Comment by josevalim** [comment]
@lukaszsamson can you please provide some test cases for what you expect here? Like:

```
def foo do
  {foo,
end
```

Should be equivalent to:

```
def foo do
  {foo}
end
```


In particular, what happens in the case of mismatched do/end (additional ones or missing ones). Also, can you please let us know what this information is used for?

Thank you!

**Comment by josevalim** [comment]
@lukaszsamson @scohen @scottming  can you please provide many examples of what you expect here? Like:

```
def foo do
  {foo,
end
```

Should be equivalent to:

```
def foo do
  {foo}
end
```

In particular, what happens in the case of mismatched do/end (additional ones or missing ones). Thanks!

**Comment by scohen** [comment]
I see how this gets tricky; Tuples have a different AST representation than something like a map. In this case, I feel what you have there should be equivalent to what I'd desire (but with a cursor in there) Same with the do/end. I really only care about the things before the cursor, and I would likely be feeding 
```elixir
def foo do 
  {foo, 
```
to the function. I would say that the cursor position is very relevant to me. 
This would make me happy:
```elixir
{:def, [line: 1], [{:my, [line: 1], nil}, [do: {:foo, {:__cursor__, [line: 2, column: 8], []}]]}
```

**Comment by josevalim** [comment]
Code.Fragment.container_cursor_to_quoted can achieve this today then.

**Comment by scohen** [comment]
I don't think it can, because we're not always in a container.

**Comment by josevalim** [comment]
So let’s go back to the previous discussion. This is about something else, which examples for are still appreciated. :)

**Comment by scohen** [comment]
Ok. will do.

**Comment by josevalim** [comment]
Some tests can be found in https://github.com/elixir-lsp/elixir_sense/blob/master/test/elixir_sense/core/parser_test.exs and https://github.com/elixir-lsp/elixir_sense/blob/master/test/elixir_sense/suggestions_test.exs

**Comment by zachallaun** [comment]
This would be extremely useful. José (or anyone else), do you have any guidance on how you'd like this to be approached/implemented? I'm assuming that, for safety, we don't want to modify the existing parser, but instead introduce a completely new one. Would you start with a literal copy of the current parser and then modify it to correct/skip when issues are encountered, or do you envision a ground-up rewrite?

**Comment by josevalim** [comment]
Hi @zachallaun! You can look at `Code.Fragment.container_cursor_to_quoted`. We have historically been modifying the current tokenizer, since it was already aware of terminators, and I would probably continue exploring the same front. :) Although fixing operators may be harder.

**Comment by zachallaun** [comment]
Thanks for the tip!

Looking through the code a bit, here's my current mental model. If you could correct any obvious mistakes, I'd greatly appreciate it!

---

The approach taken with `container_cursor_to_quoted` is to correct things during tokenization. This happens for `container_cursor_to_quoted` using a `cursor_completion` flag. The parser itself is unchanged. When `cursor_completion` is set, the string is tokenized, then the cursor is inserted, followed by any trailing terminator tokens. The insertion of terminators is what makes the result a valid list of tokens that can be passed as normal to the parser.

`Code.Fragment.string_to_quoted` will set a different flag that will cause the tokenizer to repair the stream of tokens with an error is encountered. At least one challenge will be determining the best way to repair. Sometimes it will be to insert terminators, as in this example:

```elixir
%{foo: 1, bar: 2
# =>
%{foo: 1, bar: 2}
```

Other times it may be to insert a "filler" token before the terminator:

```elixir
%{foo: 1, bar:
# =>
%{foo: 1, bar: __FILLER__}
```

Or else to ellide a token entirely:

```elixir
%{foo: 1, b
# =>
%{foo: 1}
```

**Comment by josevalim** [comment]
Yeah, although I am wondering if it is worth holding on this one altogether and work first on  #12645. And, depending if that one does not address all cases, we work on this one.

**Comment by josevalim** [comment]
Closing this in favor of [spitfire](https://github.com/elixir-tools/spitfire).
