### ISSUE TITLE
Mix test task not running appropriately in umbrella

### ISSUE THREAD

**Issue by Mrjaco12** [elixir-lang/elixir#11997]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1]

Elixir 1.13.3 (compiled with Erlang/OTP 24)

### Operating system

macOS 12.4

### Current behavior

Using `Mix.Tasks.Test.run/1` within a mix alias in an umbrella application is not running any tests. Here is an [example repo](https://github.com/Mrjaco12/mix_test_bug_umbrella). I believe that the issue is related to [this line](https://github.com/elixir-lang/elixir/blob/0cec016972da3faeddb1c07d0a8f194ae9d66b2b/lib/mix/lib/mix/tasks/test.ex#L428) returning false. I'm not sure why this might be the case. I think an easy fix would be to replace the existing check with a check of `Mix.Project.umbrella?` but I'm not sure if that would have any implications on other use cases of the task.

### Expected behavior

The mix task should be able to self-identify as being inside an umbrella app and run all the appropriate tests.

**Comment by josevalim** [comment]
Yes, you must not use `Mix.Tasks.Test.run/1`. You should always use `Mix.Task.run("test")` for running tasks.

**Comment by josevalim** [comment]
You can dynamically define the alias. For example, change the Docker setup to be a no-op if in CI.
