### ISSUE TITLE
Cannot parse `%Version{}` when pre-release part contains only digits and starts with `0`

### ISSUE THREAD

**Issue by thalesmg** [elixir-lang/elixir#12000]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.2.1] [emqx-34f64a18a3] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```

### Operating system

Ubuntu 20.04, Archlinux

### Current behavior

We are using a prefix of our project's git hash as a pre-release version.  It works almost always.  Except that now that such prefix starts only with digits, `Version.parse/1` fails.

```elixir
iex(2)> Version.parse("5.0.4-01614284") # the original version
:error
iex(3)> Version.parse("5.0.4-01614284a") # note the appended "a"
{:ok, #Version<5.0.4-01614284a>}
iex(4)> Version.parse("5.0.4-a01614284") # note the prepended "a"
{:ok, #Version<5.0.4-a01614284>}
```

I noticed that there's even a [test case](https://github.com/elixir-lang/elixir/blob/9be08c8ac8fe2c5d35dabcd9bf5a3a394ff0efe5/lib/elixir/test/elixir/version_test.exs#L97) asserting this.  But that doesn't seem to match the description of what's allowed for pre-release identifiers:

> Pre-releases are supported by optionally appending a hyphen and a series of period-separated identifiers immediately following the patch version. Identifiers consist of only ASCII alphanumeric characters and hyphens ([0-9A-Za-z-]):

The issue is probably [this check](https://github.com/elixir-lang/elixir/blob/7e4fbe657dbf9c3e19e3d2bd6c17cc6d724b4710/lib/elixir/lib/version.ex#L596), as prepending any non-zero digit will also fix the issue:

```elixir
iex(2)> Version.parse("5.0.4-101614284") # prepended "1" to the original version.
{:ok, #Version<5.0.4-101614284>}
```

### Expected behavior

`"5.0.4-01614284"` should be a valid version.

**Comment by josevalim** [comment]
This works:

```
iex(1)> Version.parse("5.0.4-1614284") #
{:ok, %Version{major: 5, minor: 0, patch: 4, pre: [1614284]}}
```

the issue is the leading zero, per the spec:

>  Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. 

For non compliant projects, you can pass the version as a regex. :)

**Comment by thalesmg** [comment]
Thanks for the answer.

The issue is: what if we want to interpret the pre-release as a string?  That's why it works most of the time, except on this rare occasion when the string happened to consist of only digits AND start with a `0`.  :see_no_evil: 

> For non compliant projects, you can pass the version as a regex. :)

In our case, we want to set it as the version in the `project/0` function in our Mix project.

```elixir
defmodule SomeMixProject do
  def project() do
    [
      version: "5.0.4-01614284"
...
```

How can I pass that as a regex?  I don't understand.

**Comment by josevalim** [comment]
You are simply not able to do that. Version for Elixir projects need to follow the semver scheme.
