### ISSUE TITLE
A better description for Enum module

### ISSUE THREAD

**Issue by Enuzo** [elixir-lang/elixir#12001]
In the doc:
https://github.com/elixir-lang/elixir/blob/fb729784e5504f499b0179c4f154e73ea2a6f216/lib/elixir/lib/enum.ex#L206
Enum module is described as:
"Provides a set of _algorithms_ to work with enumerables."
I'll suggest that a clearer description would be :
"Provides a set of _functions_ to work with enumerables."

**Comment by josevalim** [comment]
PR please!

**Comment by Enuzo** [comment]
> PR please!

Done.
