### ISSUE TITLE
Inconsistent module resolution ignoring case

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/elixir#12006]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)

### Operating system

macOS 12.4

### Current behavior

Several functionalities are resolving modules in a case-insensitive manner:

- The following doesn't raise any compile warning, but ends up in a runtime failure:

```elixir
Io.puts("hello") 
```

- The following returns the docs for `IO`:

```elixir
Code.fetch_docs(Io)
```

This seems to be due to a problem with the `:code` module:

```
:code.get_object_code(Io) != :error
```

Originally reported on [StackOverflow](https://stackoverflow.com/questions/73095636/where-vscode-compiler-cant-find-the-mistaken-spelling-genserver).

### Expected behavior

Module resolution should always be case-sensitive:

- raise a compile warning for all non-existing modules
- `Code` and `Module` functions should behave consistently when a module doesn't exist

I started working on a fix, will try to send a PR soon.

**Comment by josevalim** [comment]
The module resolution actually depends on the filesystem, because .beam files are looked up in the filesystem. Changing this tone consistent will be expensive in case insensitive file systems. However, I fully agree that we should not return the docs in the example you mentioned. We should verify the returned module name matches.

**Comment by sabiwara** [comment]
OK. I was thinking about using the approach used [here](https://github.com/elixir-lang/elixir/commit/352dd7f78c5aeb982863929c2290349e6b820857) in other places using `:code.get_object_code/1` to check the module atom matches:

```elixir
iex> :code.get_object_code(Io) |> elem(1) |> :beam_lib.info() |> Keyword.fetch(:module)
{:ok, IO}
```

**Comment by josevalim** [comment]
Yup, perfect!
