### ISSUE TITLE
Elixir 1.14 reports itself as "1.14.0-dev"

### ISSUE THREAD

**Issue by sax** [elixir-lang/elixir#12021]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.0-dev (05b17af) (compiled with Erlang/OTP 25)

### Operating system

MacOS Monterrey

### Current behavior

I've just installed Elixir 1.14-otp-25 using `asdf`. When running `elixir --version` from a terminal or `System.version()` from an iex session, Elixir reports itself as `1.14.0-dev`.

### Expected behavior

Now that the version has been officially released, I would expect the version to report itself as `1.14.0`.

**Comment by princemaple** [comment]
Don't think it's officially released yet..

**Comment by sax** [comment]
Oh! I thought it was released this morning. I'll leave this open for now, but am happy for it to be closed if 1.14 hasn't actually been released.

**Comment by wingyplus** [comment]
The maintainer will change the version when 1.14 is land. So i dont think this is a bug. :)

**Comment by josevalim** [comment]
It has not been released, just branched.
