### ISSUE TITLE
Unicode reports invalid encoding in Windows terminals (powershell, cmd windows) 

### ISSUE THREAD

**Issue by dougedmunds** [elixir-lang/elixir#12066]
### Elixir and Erlang/OTP versions

PS C:\Users\DAE> elixir --version
Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 22)

### Operating system

Window 10 home

### Current behavior

iex(1)> a = "josé"
** (UnicodeConversionError) invalid encoding starting at <<130, 34, 10>>
    (elixir 1.13.4) lib/string.ex:2407: String.to_charlist/1

### Expected behavior

iex(1)> a = "josé"
"josé"

**Comment by josevalim** [comment]
The windows terminal unfortunately is not on UTF8 by default, so you need to change codepage by calling `chcp 65001`: https://hexdocs.pm/iex/IEx.html#module-encoding-and-coloring

**Comment by dougedmunds** [comment]
I think you should reopen this and modify the bat file.

It would be better to add  chcp65001 to the iex.bat file (immediately after :run), rather than expecting the user to remember to do this manually *every time* they open a cmd window or powershell.   

One significant reason is that the default code page 437 actually *converts" non-English letters to English,  and Elixir does not catch the conversion, meaing that some stored data will not match the actual entry.  

Here is an example, from Polish, using the word for "cabbage roll":  Gołąbki. 
If the code page is unchanged from cp437, this is the result produced by Elixir:

Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> a = Gołąbki
Golabki
iex(2)> a
Golabki

**Comment by dougedmunds** [comment]
Two related pages on StackOverFlow: 

Win 10   how to change the default code page
https://stackoverflow.com/questions/7432545/change-codepage-in-cmd-permanently#:~:text=Start%20%2D%3E%20Run%20%2D%3E%20regedit,the%20value%20to%20'chcp%20437'

Win 11 has changed the default to 65001 (and new problems it may have created) 
[WIndows 11 Default API and UTF Encoding](https://stackoverflow.com/questions/70201846/windows-11-default-api-and-utf-encoding)

**Comment by josevalim** [comment]
Thank you @dougedmunds!

We did do so in the past but we unfortunately ran into issues. :( Luckily, this is addressed in Erlang/OTP 26 because it sets the page directly from the VM, so should not be r

**Comment by josevalim** [comment]
Accidentally reopened. This is tackled upstream per above :)
