### ISSUE TITLE
Fail to load modules in mix project when iex -S mix with --no-pry option

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/elixir#12072]
### Elixir and Erlang/OTP versions

% elixir --version
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0-rc.0 (6449239) (compiled with Erlang/OTP 25)

### Operating system

macOS Monterey 12.5

### Current behavior

In some `mix` project, run the following command:

```
iex --no-pry -S mix
```

Then, iex starts but it seems to fail load modules in the project.

### Expected behavior

The modules in the `mix` project should be loaded and able to run by inputting the name of each module to the prompt.

**Comment by wojtekmach** [comment]
Nice catch. It seems `--no-pry` flag prevents parsing any other command-line options.

This works as expected:

```
% iex --bad
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

--bad : Unknown option
```

but this does not:

```
% iex --no-pry --bad
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Interactive Elixir (1.15.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```
