### ISSUE TITLE
Ranges do not equal when it seems they should in a guard

### ISSUE THREAD

**Issue by ollien** [elixir-lang/elixir#12076]
### Elixir and Erlang/OTP versions
```
Erlang/OTP 24 [erts-12.3.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```

### Operating system

Fedora 36

### Current behavior

I wanted to write a function that would, given a range and a value, n, check if the range spans exactly n..n. My first attempt looked something like this, but does not have the expected behavior (note the first return value is false)

```elixir
defmodule Range do
  def equal?(n, range) when range == n..n, do: true
  def equal?(n, range), do: false
end

IO.puts(Range.equal?(1, 1..1)) # false
IO.puts(Range.equal?(1, 1..5)) # false
```

While this function can be written by using pattern matching on the range argument (replacing the first `equal?` declaration with `  def equal?(n, n..n), do: true`), I was surprised this didn't work.

Some on StackOverflow have [speculated](https://stackoverflow.com/a/73349444/1103734) this is due to the `step` evaluating to `nil` in a guard. Indeed, it does work if `when range == n..n` is replaced with `when range == n..n//1`

### Expected behavior

 I would have expected `when range == n..n` to correctly guard the call for when the range was exactly `n..n`, especially given this works

```
iex(1)> range = 1..1
1..1
iex(2)> n = 1
1
iex(3)> range == 1..1
true
iex(4)> match?({n, n..n}, {1, 1..1})
true
```

**Comment by wojtekmach** [comment]
> Some on StackOverflow have [speculated](https://stackoverflow.com/a/73349444/1103734) this is due to the step evaluating to nil in a guard

yup:

```elixir
Mix.install([
  {:decompilerl, github: "aerosol/decompilerl"}
])

defmodule Range do
  def equal?(n, range) when range == n..n, do: true
  def equal?(n, range), do: false
end
|> Decompilerl.decompile(skip_info: true)
```

```erlang
-module('Elixir.Range').

-compile([no_auto_import]).

-export(['equal?'/2]).

'equal?'(_n@1, _range@1)
    when _range@1 ==
             #{'__struct__' => 'Elixir.Range', first => _n@1,
               last => _n@1, step => nil} ->
    true;
'equal?'(_n@1, _range@1) -> false.
```

**Comment by josevalim** [comment]
It is fixed, tks for the report! However, be careful with the concept of equality with ranges. For example, those ranges are not structurally equal but they do emit the same elements: 1..1/1, 1..1/-1, 1..1/2, etc.
