### ISSUE TITLE
Unexpected error from File.rm_rf!

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12088]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0-rc.1 (ed076eb) (compiled with Erlang/OTP 24)

### Operating system

macOS

### Current behavior

when running `mix deps.update --all`
```
Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  cowlib 2.11.0
Upgraded:
  cowboy 2.7.0 => 2.9.0
  protobuf 0.7.1 => 0.10.0 (minor)
  ranch 1.7.1 => 1.8.0
* Updating protobuf (Hex package)
* Updating cowboy (Hex package)
** (File.Error) could not remove files and directories recursively from "/Users/my_user/my_proj/deps/cowboy": file already exists
    (elixir 1.14.0-rc.1) lib/file.ex:1339: File.rm_rf!/1
    (hex 1.0.1) lib/hex/scm.ex:154: Hex.SCM.update/1
    (mix 1.14.0-rc.1) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
    (mix 1.14.0-rc.1) lib/mix/dep/converger.ex:213: Mix.Dep.Converger.all/9
    (mix 1.14.0-rc.1) lib/mix/dep/converger.ex:146: Mix.Dep.Converger.all/7
    (mix 1.14.0-rc.1) lib/mix/dep/converger.ex:131: Mix.Dep.Converger.all/4
    (mix 1.14.0-rc.1) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
    (mix 1.14.0-rc.1) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
```

```
ls -la deps/cowboy 
total 0
drwxr-xr-x  3 my_user  staff   96 18 Aug 11:00 .
drwxr-xr-x  8 my_user  staff  256 18 Aug 11:00 ..
drwxr-xr-x  5 my_user  staff  160 18 Aug 11:00 ebin
ls -la deps/cowboy/ebin 
total 32
drwxr-xr-x  5 my_user  staff   160 18 Aug 11:00 .
drwxr-xr-x  3 my_user  staff    96 18 Aug 11:00 ..
-rw-r--r--  1 my_user  staff  1584 18 Aug 11:00 cowboy_middleware.beam
-rw-r--r--  1 my_user  staff  6760 18 Aug 11:00 cowboy_stream.beam
-rw-r--r--  1 my_user  staff  1680 18 Aug 11:00 cowboy_sub_protocol.beam
```

The problem is not reproducible. It may be some kind of race conditions in hex/elixir/os

### Expected behavior

It should not crash with that error

**Comment by josevalim** [comment]
Looking at the code, the issue seems to be that someone was writing to the directory at the same time we were deleting it. Would the timestamps above align with said explanation?

I can't think of it being a Hex issue... so maybe something running in the background? Maybe ElixirLS or something else was running during `mix deps.update`?

**Comment by lukaszsamson** [comment]
I'm running ElixirLS with disabled auto updating (too problematic) but it could have been running a compile in the background.

**Comment by josevalim** [comment]
Ok! I will close this for now. The ideal fix would be for us to start locking certain tasks, but that needs a file system lock and there isn't such API in OTP today. We will chat later. :)
