### ISSUE TITLE
Type information leaking between branches in cond block

### ISSUE THREAD

**Issue by ashton314** [elixir-lang/elixir#12082]
### Elixir and Erlang/OTP versions

Erlang/OTP 23 [erts-11.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]
Elixir 1.11.4 (compiled with Erlang/OTP 23)

### Operating system

macOS 12.5

### Current behavior

Consider this code:

```elixir
defmodule Foo do
  def bar(thing) do
    cond do
      match?({:square, _width}, thing) ->
        {:square, width} = thing
        width + 1

      match?({:circle, _radius}, thing) ->
        {:circle, radius} = thing
        radius * 2
    end
  end
end
```

When this file gets compiled (I encountered this as part of a big project, but you could dump that snippet into `foo.exs` and then run `c "foo.exs"` in an IEx shell) it emits the following warning:

```
iex(1)> c "foo.exs"
warning: incompatible types:

    :square !~ :circle

in expression:

    # foo.exs:9
    {:circle, radius} = thing

where "thing" was given the type {:square, var1} in:

    # foo.exs:5
    {:square, width} = thing

where "thing" was given the type {:circle, var2} in:

    # foo.exs:9
    {:circle, radius} = thing

Conflict found at
  foo.exs:9: Foo.bar/1

[Foo]
```

### Expected behavior

Type inference is acting like the code fell through one branch. It should instead consider the branches of `cond` independently.

**Comment by ashton314** [comment]
Note that the code still runs without errors; the type checker is warning about an error that will never occur.

**Comment by wojtekmach** [comment]
I could reproduce this on Elixir v1.13 but couldn't on v1.14 so I think we can close this. :)

**Comment by josevalim** [comment]
Yes, this has been fixed in v1.14. :) Thanks for the report!

**Comment by ashton314** [comment]
Yay! Now hurry up and release that goodness so our CI pipeline can be happy. ;-)

Thanks for all y’all do with this language! 💙

**Comment by wojtekmach** [comment]
RCs are out, trying them out on your CI pipelines and reporting any problems you might encounter will be very appreciated. ;)
