### ISSUE TITLE
Elixir compiler ingores an expression has been assigned to a variable prefixed with underscore and emits warning

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#12098]
### Elixir and Erlang/OTP versions

Erlang/OTP 23 [erts-11.2.2.15] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.14.0-rc.1 (185eeec) (compiled with Erlang/OTP 23)

### Operating system

Linux

### Current behavior

This is a weird warning that I managed to isolate:

```
$ mix
Compiling 1 file (.ex)
warning: the result of the expression is ignored (suppress the warning by assigning the expression to the _ variable)
  lib/if_warning.ex:5

Generated if_warning app
```

```elixir
defmodule IfWarning do
  def foo(arg, errors) do
    _all_errors =
      if is_list(errors) do
        errors ++ ["1"]
      else
        errors
      end

    # TODO: Email all_errors
    # email(all_errors)

    {arg, errors}
  end
end
```

The warning is not generated if you use `_` instead of `_all_errors`,
The warning is generated when `++/2` is used. If i evaluate and return other expressions instead such as  `["1" | errors]`, `Enum.uniq(errors)` or `:foo`, no warning are emitted.

### Expected behavior

No warning should be emitted.

**Comment by josevalim** [comment]
I beleive the warning is coming from Erlang and I cannot reproduce it on OTP 25.

**Comment by eksperimental** [comment]
True. Neither OTP 24 nor 25 emits the warning.

Should this be reported upstream?

**Comment by josevalim** [comment]
I don't think so. The bug has been addressed, and I don't believe they would backport anything to 23, unless it is a security issue.
