### ISSUE TITLE
ExUnit.CaptureLog.capture_log/2

### ISSUE THREAD

**Issue by TraceyOnim** [elixir-lang/elixir#12092]
### Elixir and Erlang/OTP versions

erlang 24.1.7
elixir 1.13.4-otp-24

### Operating system

linux(ubuntu)

### Current behavior

capture_log/2 returns an empty string if `Logger.info/1` is used

```elixir
capture_log(fn ->
        Logger.info("======")
end)
```

### Expected behavior

To return the log message despite which logger is used. 
However , if this is how its supposed to perform, the [docs](https://hexdocs.pm/ex_unit/1.13/ExUnit.CaptureLog.html#capture_log/2) should be updated  to point out the case.

**Comment by josevalim** [comment]
The docs indeed have recently been updated to explain why this happens. Please check the docs from main: https://hexdocs.pm/ex_unit/master/ExUnit.CaptureLog.html#capture_log/2 :)

**Comment by TraceyOnim** [comment]
Thank you @josevalim , I have seen the part that explains
