### ISSUE TITLE
Unexpected ArgumentError raised when interpolating an integer into a string: possible bug with Elixir guards and Erlang 25?

### ISSUE THREAD

**Issue by connorlay** [elixir-lang/elixir#12095]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.0-rc.1 (7e7a1fa) (compiled with Erlang/OTP 25)

### Operating system

Pop!_OS 22.04 LTS 11th Gen Intel® Core™ i7-11800H @ 2.30GHz × 16 

### Current behavior

See https://github.com/connorlay/guard_bug

👋🏻 This is my first bug report for Elixir, please let me know if I should provide any additional information 🙂 

When attempting to upgrade a project on Elixir 1.13.4 and Erlang 24 to Elixir 1.14.0-rc1 Erlang 25, I ran into this perplexing bug related to guard statements and string interpolation. 

Below is a test demonstrating this behavior:

**Test Case:**
```elixir
defmodule ErlangGuardTest do
  use ExUnit.Case

  # this function is the possible bug
  def f(a, b) when is_integer(b) or is_binary(b) do
    "#{a}_#{b}"
  end

  # this function works just fine
  def g(a, b) when is_integer(b) do
    "#{a}_#{b}"
  end
  
  test "this raises a runtime error" do
    f(A, 2749963626218098647) # possible bug?
  end
  
  test "without the second guard does not raise" do
    g(A, 2749963626218098647)
  end
  
  test "smaller integer does not raise a runtime error" do
    f(A, 274996362621809864) # note the omitted trailing 7
    g(A, 274996362621809864)
  end
end
```

This is the output I see when running the test with Elixir 1.14.0-rc1 and Erlang 25:

```
  1) test this raises a runtime error (ErlangGuardTest)
     test/erlang_test.exs:14
     ** (ArgumentError) construction of binary failed: segment 3 of type 'binary': expected a binary but got: 2749963626218098647
     code: f(A, 2749963626218098647) # possible bug?
     stacktrace:
       test/erlang_test.exs:6: ErlangGuardTest.f/2
       test/erlang_test.exs:15: (test)
```

### Expected behavior

When using Elixir 1.13.4 OR 1.14.0-rc1 and Erlang 24 the same tests pass.

**Comment by josevalim** [comment]
Thank you, reported on https://github.com/erlang/otp/issues/6239.
