### ISSUE TITLE
Writing to named pipe/fifo in a Task fails in 1.14-rc.1

### ISSUE THREAD

**Issue by kerryb** [elixir-lang/elixir#12093]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.0-rc.1 (185eeec) (compiled with Erlang/OTP 25)

### Operating system

macOS 12.5.1 (21G83)

### Current behavior

I have some code that uses named pipes to pass parameters to external scripts (to avoid exposing sensitive data in `ps` output etc). When I upgraded from 1.13.4 to 1.14-rc-1 this stopped working, with the process locking up and never completing. Apologies if this is just me doing something terrible that should never have worked in the first place!

I’ve tried to reduce it to as simple a case as I could. Here’s that code:

```elixir
File.rm_rf("fifo")
System.cmd("mkfifo", ["fifo"])

task_1 =
  Task.async(fn ->
    IO.puts("writing")
    File.write!("fifo", "test\n")
    IO.puts("writing finished")
  end)

task_2 =
  Task.async(fn ->
    IO.puts("reading")
    "head -1 fifo" |> System.shell() |> IO.inspect(label: "read")
    IO.puts("reading finished")
  end)

IO.puts("waiting for reader")
Task.await(task_2)
IO.puts("waiting for writer")
Task.await(task_1)
File.rm_rf("fifo")
IO.puts("done")
```

Here’s the output in 1.14-rc.1:

```
tmp$ elixir --version
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.0-rc.1 (185eeec) (compiled with Erlang/OTP 25)tmp$ elixir fifo.exs
waiting for reader
writing
reading
^C
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C
```

### Expected behavior

This is the exact same code running in 1.13.4:

```
tmp$ elixir --version
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.13.4 (compiled with Erlang/OTP 25)
tmp$ elixir fifo.exs
waiting for reader
writing
reading
writing finished
read: {"test\n", 0}
reading finished
waiting for writer
done
```

**Comment by josevalim** [comment]
Your code has an inherent race condition: there is no guarantee task1 will write before or after task2. For example, adding `Process.sleep(1)` (1ms) to any of them change the outcome. This means that any change in Elixir, your machine, etc, may change how those processes are scheduled and change the result. For example, maybe tasks got a tiny bit faster, maybe the got a tiny bit slower, etc. You have to address this in your code. :)

**Comment by kerryb** [comment]
Thanks – I could have sworn I’d tried putting a sleep at the beginning of the writer task to test that, but apparently not.
