### ISSUE TITLE
Confusing warning generated by misused for comprehension with uniq

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12107]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0-rc.1 (b0153d5) (compiled with Erlang/OTP 24)

### Operating system

any

### Current behavior

When compiled, this code
```
defmodule Repro do
  def go(changes) do
    for change <- changes, uniq: true, do: (
      Some.fun(change)
    )
    :ok
  end
end
```
emits
```
warning: the result of calling element/2 is ignored (suppress the warning by assigning the expression to the _ variable)
```

### Expected behavior

This code is obviously wrong as the uniqueness is checked on the result of `Some.fun(change)` and not on `change` but the warning is confusing. There is no `element/2` call in the code.

**Comment by sabiwara** [comment]
The code is transpiled into:

```elixir
:erlang.element(
  1,
  Enum.reduce(changes(), {[], %{}}, fn change, var2 ->
    {var4, var5} = var2

    var3 =
      (
        Some.fun(change)
        nil
      )

    case var5 do
      %{^var3 => true} -> {var4, var5}
      %{} -> {var3, Map.put(var5, var3, true)}
    end
  end)
)

:ok
```

The `element` call isn't needed here, just like the final call to `:lists.reverse` is removed when the comprehension isn't used. I will try to send a PR.

But as pointed out this use of `uniq` is quite wrong:
- we are building a map for nothing
- keys aren't even the result of the function, just `nil`
- `Some.fun` is still called on every element

So maybe there is another warning to emit here as well?
