### ISSUE TITLE
formatter removes brackets in `if` condition if `if` and condition are on separate lines

### ISSUE THREAD

**Issue by simonmcconnell** [elixir-lang/elixir#12104]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Operating system

Windows 11

### Current behavior

The formatter removes the brackets around the `queue` arg.

```elixir
    timer = if

    :queue.is_empty(queue) do
      nil
    else
      Process.send_after(self(), :check, Ctapi.get_delay())
    end
```

`mix format`

```elixir
    timer = if

    :queue.is_empty queue do
      nil
    else
      Process.send_after(self(), :check, Ctapi.get_delay())
    end
```

### Expected behavior

`if` and condition are put back on the same line.  This is what happens when the `if` and its condition are on the same line.

```elixir
    timer =
      if :queue.is_empty(queue) do
        nil
      else
        Process.send_after(self(), :check, Ctapi.get_delay())
      end
```

**Comment by simonmcconnell** [comment]
`.formatter.exs`
```elixir
[
  import_deps: [:ecto, :typed_struct, :stream_data],
  inputs: ["*.{ex,exs}", "{config,lib,test}/**/*.{ex,exs}"],
  plugins: [FreedomFormatter],
  subdirectories: ["priv/*/migrations"],
  trailing_comma: true,
]
```

I've tried it with and without the plugin.

**Comment by josevalim** [comment]
`if` is  not a keyword in Elixir. So `timer = if`  is literally assigning the value of the variable `if` to the variable `timer`. Adding parenthesis per line, you would have this:

```elixir
    (timer = if)

    (:queue.is_empty(queue) do
      nil
    else
      Process.send_after(self(), :check, Ctapi.get_delay())
    end)
```

So this behaviour is expected. :)
