### ISSUE TITLE
elixir 1.14: Internal consistency check failed

### ISSUE THREAD

**Issue by jgallinari** [elixir-lang/elixir#12110]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

macOS 12.5.1 (Intel)

### Current behavior

```
❯ mix test
Excluding tags: [:integration, :sym]


== Compilation error in file test/oss_web/integration/order_test.exs ==
** (CompileError) elixir_compiler_33:1: function '-__MODULE__/1-fun-0-'/2+6:
  Internal consistency check failed - please report this bug.
  Instruction: {get_map_elements,
                   {f,44},
                   {x,0},
                   {list,
                       [{atom,url},
                        {x,3},
                        {atom,func},
                        {x,3},
                        {atom,desc},
                        {x,2}]}}
  Error:       conflicting_destinations:

    (stdlib 4.0.1) lists.erl:1442: :lists.foreach_1/2
```

### Expected behavior

mix test compiles the code without error, which is OK on elixir 1.13.4

**Comment by josevalim** [comment]
This is a bug in the Erlang compiler, in order to address it we will need a way to reproduce it. Can you please provide one?

**Comment by jgallinari** [comment]
Hi @josevalim, I created a minimal sample to reproduce the issue here: https://github.com/jgallinari/ex_issue_12110
🙂

**Comment by josevalim** [comment]
Thank you, that was very helpful. Bug reported upstream here: https://github.com/erlang/otp/issues/6277
