### ISSUE TITLE
Removal of `Precompiled.zip` has broken Scoop

### ISSUE THREAD

**Issue by simonmcconnell** [elixir-lang/elixir#12134]
### Elixir and Erlang/OTP versions

1.14

### Operating system

Windows

### Current behavior

The change to the release format has broken Scoop, which some of us use to install apps on Windows.  The manifest was using `Precompiled.zip`, which has been removed.  Is it at all possible to put it back, so that we can have the option of installing old and new versions of Elixir?  If Scoop's Elixir manifest is updated to the new release format, we lose the ability to install pre-1.14 versions through scoop (at least ones that we don't explicitly add to the `Versions` bucket).  We're going to have to add Elixir to the `Versions` bucket to allow installation of the different OTP builds regardless, so it is not the end of the world if we can't.

https://github.com/ScoopInstaller/Main/issues/3886

### Expected behavior

`scoop install elixir` doesn't crash

**Comment by josevalim** [comment]
The goal with this release was to automate our setup and provide precompiled Elixir per OTP version. I could manually upload a Precompiled.zip for now but that would be only a temporary solution. Long term you would need to migrate to the new format. Would that help?

**Comment by wojtekmach** [comment]
Another solution would be to point to 

`https://repo.hex.pm/builds/elixir/{REF}.zip`

see https://github.com/hexpm/bob#elixir-builds for more information. Under these urls we have past and will have future Elixir builds.

**Comment by rashil2000** [comment]
> Another solution would be to point to
> 
> `https://repo.hex.pm/builds/elixir/{REF}.zip`
> 
> see https://github.com/hexpm/bob#elixir-builds for more information. Under these urls we have past and will have future Elixir builds.

This seems to be a good backward friendly (for Scoop) option
