### ISSUE TITLE
[1.14.0/OTP 25.0.4] Zombie process script exits immediately

### ISSUE THREAD

**Issue by randycoulman** [elixir-lang/elixir#12135]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

macOS Monterey v12.4

### Current behavior

When using the [zombie process handling script](https://hexdocs.pm/elixir/1.13/Port.html#module-zombie-operating-system-processes) to launch a Phoenix app, the script now terminates the process immediately.

I [created a simple repository](https://github.com/randycoulman/elixir_zombie_bug) to demonstrate the issue.

To reproduce:
- Clone the repository
- Run `mix s`
- Notice that the application exits immediately with exit code 137

To verify what was happening, I added a `sleep 5` to the script (see commented out line). With that line in place, the application starts up and is running, but then is killed once the 5 second sleep time expires.

It appears that the script is unable to read from `stdin` and so believes that the `exec`ed process has exited, so initiates its cleanup process.

I also tested the following combinations:
- Elixir 1.13.4/OTP 25.0.4: works as expected
- Elixir 1.14.0/OTP 24.3.4: fails as described above

Thus, it appears that the issue was introduced with Elixir 1.14.0 as is not specific to a particular OTP version.

### Expected behavior

When starting the application with `mix s`, it should stay running. When exiting the application (with `Ctrl-C Ctrl-C`), the `beam` process should no longer be running.

**Comment by josevalim** [comment]
Caused by #11767. I have a fix, but I am verifying a couple things.

**Comment by randycoulman** [comment]
Awesome! Thanks, @josevalim!
