### ISSUE TITLE
Unicode 15 changes to identifier and security specifications

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#12142]
Unicode 15 updated two specifications that may have relevance to Elixir's identifier patterns for a future release:

* [UAX #31](https://www.unicode.org/reports/tr31/tr31-37.html), Unicode Identifier and Pattern Syntax, provides more guidance on profiles for default identifiers, clarifies the use of default ignorable code points in identifiers, and discusses the relationship between Pattern_White_Space and bidirectional ordering issues in programming languages.

* [UTS #39](https://www.unicode.org/reports/tr39/tr39-26.html), Unicode Security Mechanisms, changes the zero width joiner (ZWJ) and zero width non-joiner (ZWNJ) characters from Identifier_Status=Allowed to Identifier_Status=Restricted; they are therefore no longer allowed by the General Security Profile by default.

### Expected behavior

Review current identifier security against updated Unicode guidance.

**Comment by josevalim** [comment]
Thank you @kipcole9. I have reviewed the changes in the standard and we don't allow bidi nor joiners in identifiers, so we are "immune". However, we made changes in Elixir v1.14 regarding UAX 31. Those are properly reflected now. :)

Btw, @eksperimental, do we need anything to trigger the Unicode builds?

Thank you both! :heart:

**Comment by eksperimental** [comment]
Thank you for pinging me @josevalim . I noticed the app stopped a while ago due to some issue and I knew in September there was a new version of Unicode, but I didn't get the chance to restart it. I will do this later on today, so hopefully PRs wil be automatically submitted to both Elixir and OTP.
