### ISSUE TITLE
Superslow compilation in 1.14

### ISSUE THREAD

**Issue by hfjallemark** [elixir-lang/elixir#12149]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

macOS Monterey 12.6

### Current behavior

Compile times after going from Elixir `1.13.4` to `1.14.0` went up by an order of magnitude. It takes over 1 minute to just compile one file.

Running `mix compile --force --profile time` I'm seeing that the **group pass check** takes much longer than the **compilation cycle**:

```
[profile] Finished compilation cycle of 361 modules in 6864ms
[profile] Finished group pass check of 361 modules in 41570ms
```

Any ideas why and how we can debug this more to identify the culprit? We tried using 1.14.0 on another project and the compilation times were fine there.

### Expected behavior

It should compile fast like it did in version `1.13.4`.

**Comment by wojtekmach** [comment]
Could you share a sample project where you see the slowness?

**Comment by josevalim** [comment]
@hfjallemark there is something specific to this single file making compilation slow. My suggestion is to remove the bits of that file, slowly, leaving only the parts that make compilation slow. And then anonymize it and post its contents in here. From there, it should be hopefully easy to fix it!

**Comment by hfjallemark** [comment]
Thanks for the quick responses!

After some more investigation it seems [`temple`](https://github.com/mhanberg/temple) was the culprit. We're running an old version (`0.5`). This may be the weirdest bug I've ever encountered. Can't really explain it in any other way than showing the diff:

Before:

```elixir
# Superslow:
# [profile] Finished compilation cycle of 361 modules in 7281ms
# [profile] Finished group pass check of 361 modules in 33472ms

for tweet <- @twitter.tweets do
  social_post class: "twitter-tweet",
               content: tweet.message,
               id: tweet.id,
               logo_id: tweet.owner.organization.logo,
               logo_name: tweet.owner.organization.display_name,
               published_at: tweet.published_at
end
```

After:
```elixir
# Fast again:
# [profile] Finished compilation cycle of 361 modules in 6805ms
# [profile] Finished group pass check of 361 modules in 810ms

for tweet <- @twitter.tweets do
  logo_id = tweet.owner.organization.logo
  logo_name = tweet.owner.organization.display_name

  social_post class: "twitter-tweet",
              content: tweet.message,
              id: tweet.id,
              logo_id: logo_id,
              logo_name: logo_name,
              published_at: tweet.published_at
end
```

It seems the number of dots affected the compilation times:
```elixir
tweet.owner.organization.logo # Slowest
tweet.owner.organization # Slow
tweet.owner # Faster
tweet # Fastest
```

++ @mhanberg

**Comment by josevalim** [comment]
This is definitely a regression in Elixir. But I assume temple was also outputting the same expression multiple times, which made it worse.
