### ISSUE TITLE
Very high memory consumption on big test suite due to context merged into ExUnit.Test structs

### ISSUE THREAD

**Issue by vorce** [elixir-lang/elixir#12141]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Operating system

Both macOS 12.5.1 and Debian (seen on both local execution as well as our CI)

### Current behavior

Hello folks!

This week we’ve noticed an increase in our quite large test suite getting killed on CI servers (16GB RAM, 8vCPUs). The test suite consists of 18221 test cases, most of them async.

After some investigation we found that the `ExUnit.TestModule` structs can become very large (~137MB for a single phoenix controller test with ~110 test cases). Digging further we see that the test context is included in each `ExUnit.Test` struct is sent to the formatters.

Unfortunately for us we added our OpenApiSpex spec to the context in the Web.ConnCase module 🤦

We did this out of convenience, since the spec is needed to make assertions on if a response matches a spec (which we use a lot). The result is that the (very big!) spec is in every `ExUnit.Test` struct for our controller tests! We've fixed this, but still have some questions:

- Why is the context in the Test struct’s `tags` ([merge starting](https://github.com/elixir-lang/elixir/blob/7850bdd7e882815eefd1ba4b16871b32521b8bf8/lib/ex_unit/lib/ex_unit/runner.ex#L356))? It can grow quite big even with more sensible data in there (like ecto schemas). It gets worse the more ExUnit formatters you’re using.
    - We’ve also seen a message queue of the formatter reaching 54, further increasing memory usage
- Is this behavior documented anywhere? Should it be (to prevent similar foot shooting)?

When we adjusted our test suite to remove the specs from the test context **our memory usage dropped from ~9GB-16GB+ to a measly ~1.3GB**. So, the gains from this are very significant.

As an aside, before that running without a formatter also already helped reduce memory usage.

If you need more details we’re happy to share! Thanks a lot.

### Expected behavior

We’re unsure about the behavior of contexts being merged and kept as part of the `ExUnit.Test` struct - it seems to us that there could be room for improvement here (removed or reduced).

Alternatively, guidance/docs to restrict context usage would be great.

**Comment by PragTob** [comment]
And a thank you for all your excellent work! 💚 

![IMG_20220728_203124](https://user-images.githubusercontent.com/606517/190657817-fec6cb3d-01f6-4e0e-aa34-8be19e6972ea.jpg)

**Comment by josevalim** [comment]
Awesome job @vorce! A fix will be available in the next Elixir version!

**Comment by vorce** [comment]
Wow that was fast. Thanks José! It was a big team effort at Remote 😃

**Comment by PragTob** [comment]
Thanks for the quick fix @josevalim !

![IMG_20200510_081811_Bokeh](https://user-images.githubusercontent.com/606517/190969521-b046b633-7faa-4dfb-961f-9c3db90241cf.jpg)
