### ISSUE TITLE
Compiler gets stuck sometimes, have to delete compiled build to be able to compile again

### ISSUE THREAD

**Issue by gordoneliel** [elixir-lang/elixir#12140]
### Elixir and Erlang/OTP versions

Elixir: 1.14.0
Erlang: 25.0.4

### Operating system

macos

### Current behavior

When compiling a project with errors, the compiler gets stuck with this error:

`
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (MatchError) no match of right hand side value: {:error, :missing}
        (elixir 1.14.0) lib/module/parallel_checker.ex:363: Module.ParallelChecker.fetch_module_map!/2
        (elixir 1.14.0) lib/module/parallel_checker.ex:65: anonymous fn/5 in Module.ParallelChecker.spawn/3
`

### Expected behavior

This only started happening after upgrading to:
Elixir: 1.140.0
Erlang: 25.0.4

**Comment by josevalim** [comment]
Thanks for the report!. I will investigate but unfortunately without a way to reproduce the issue, it may not be trivial to fix. If you can isolate it, it would be very helpful! :)

**Comment by gordoneliel** [comment]
I'll try to. Not sure what will be helpful here. Is there something I could do to help trace and dump logs/etc to make it easier to identify?

**Comment by josevalim** [comment]
@gordoneliel I just pushed a commit on v1.14 branch to raise with more information. Can you run with it for a while and report back the additional metadata? :)

**Comment by gordoneliel** [comment]
@josevalim Getting this:

```
Compiling 1 file (.ex)
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (RuntimeError) could not load Elixir metadata for module Rosters.InvitationJob, written in backend :elixir_erl, due to reason: :missing

Please report this bug: https://github.com/elixir-lang/elixir/issues

        (elixir 1.15.0-dev) lib/module/parallel_checker.ex:388: Module.ParallelChecker.fetch_module_map!/2
        (elixir 1.15.0-dev) lib/module/parallel_checker.ex:66: anonymous fn/5 in Module.ParallelChecker.spawn/3
```

Said module is available without errors.

To add some context, this is an umbrella project, im in a specific umbrella app and trying to run tests

**Comment by josevalim** [comment]
@gordoneliel thank you!

Maybe the module is compiled without debug info? Can you please try this in IEx:

```
iex> :beam_lib.chunks(:code.which(Rosters.InvitationJob), [~c"Dbgi"])
```

What does it return?

**Comment by josevalim** [comment]
I pushed another commit to the v1.14 branch, can you please give it a try?

**Comment by gordoneliel** [comment]
@josevalim Just did, not seeing the issue anymore! Seems to be fixed but Ill reopen if it happens again. Thanks for looking into this so quickly

**Comment by whoiswentz** [comment]
I'm getting this error, I need update my elixir version to fix?

**Comment by josevalim** [comment]
I will release a new patch version this week.

**Comment by gordoneliel** [comment]
I have this config in my umbrella projects:

`elixirc_options: [debug_info: Mix.env() == :dev],`

which seemed to cause the issue.
@whoiswentz
