### ISSUE TITLE
Unable to use a compile-time proper list with `in/2` operator inside a guard expression in case

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#12151]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0] [source] [64-bit]
Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

### Current behavior

Here's s reduced case:

```elixir
list = [1, 2, 3]
numbers = [2, 4, 6]

case list do
  n when n in numbers -> true
  _ -> false
end
```

It would not compile 

```
** (ArgumentError) invalid right argument for operator "in", it expects a compile-time proper list or compile-time range on the right side when used in guard expressions, got: numbers
    (elixir 1.14.0) lib/kernel.ex:4344: Kernel.raise_on_invalid_args_in_2/1
    (elixir 1.14.0) expanding macro: Kernel.in/2
    foo.exs:21: (file)
    (elixir 1.14.0) expanding macro: Kernel.|>/2
    foo.exs:24: (file)
```

### Expected behavior

To not raise.

I can look into it a provide a PR with a fix, but just wanted to report the issue first.

**Comment by josevalim** [comment]
It is not at compile-time really. Variables and their contents are only available at runtime. A macro is not capable of accessing its value. :)
