### ISSUE TITLE
Macro.expand(__ENV__, __ENV__) returns non-ast structure

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12157]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 24)
```
Or any other version since b08593b9d1b82e65035abc9bf074ea47dc5817b1.

### Current behavior

`Macro.expand(__ENV__, __ENV__)` returns `%Macro.Env{}`, but this structure does not comply with `Macro.t()`, therefore spec for `expand` is broken

### Expected behavior

`Macro.expand(__ENV__, __ENV__)` does not return env as it is, but rather as an escaped ast.
Or `Macro.t()` spec is fixed
Or `Macro.expand` spec is fixed

**Comment by hissssst** [comment]
Oh, I've found out that just `%Macro.Env{}` is not filling the `Macro.t()` type

**Comment by josevalim** [comment]
Yes, structs are not valid AST. :)

**Comment by hissssst** [comment]
Let me reopen an issue with more details, I've lost my context and submitted the wrong thing, haha
