### ISSUE TITLE
Returning ascii character instead of integer

### ISSUE THREAD

**Issue by OnigiriJack** [elixir-lang/elixir#12179]
### Elixir and Erlang/OTP versions

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Mac0S 12.6

### Current behavior

```elixir
Enum.map([{43, 1}], fn {id, _} -> id end)
```

Returns 

`'+'`

### Expected behavior

I expect `43` as an integer to be returned

**Comment by sabiwara** [comment]
https://elixirforum.com/t/elixir-gotchas-and-common-issues-wiki/40261#heading--my-list-of-integers-is-printing-as-a-string

**Comment by josevalim** [comment]
Closing per the above, thanks!
