### ISSUE TITLE
Using a w sigil next to a module name in module body turns this module name into a compile dependency

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#12174]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.0-dev (bcc11bf) (compiled with Erlang/OTP 25)
```

### Operating system

MacOS 12.6 (Apple silicon)

### Current behavior

As a short background: I've been removing compile-time dependencies between modules in my work project, to reduce unnecessary recompilations (as a more immediate fix - the more general problem is that in this project no matter what tiny change I make, hundreds of modules get marked as "stale" because of a mess of runtime dependencies between modules).

One of the patterns I was applying was changing Plugs to use `apply` when using function options, and changing their interfaces from:

```elixir
plug SomePlug, fun_option: &OtherModule.some_fun/1
```

to:

```elixir
plug SomePlug, fun_option: {OtherModule, :some_fun}
```

This worked well until one of modules had also a different option with value passed as a sigil, like this:
```elixir
plug SomePlug, another_option: ~w(one two), fun_option: &OtherModule.some_fun/1
```

Even though I changed the function to be passed as a `{module, function}` tuple, the module where I used this plug still had compile dependency on `OtherModule`. The dependency goes away after I expand the sigil "manually" to `["one", "two"]`.

I have reduced this further to this set of two modules:

```elixir
# lib/a.ex
defmodule A do
end

# lib/b.ex
defmodule B do
  @attr [~w(text), A]
  def b, do: @attr
end
```

Given a project with those two modules (each in separate file), when I change file `lib/a.ex` (e.g. add an empty line to this file), the file `lib/b.ex` unnecessarily recompiles. If I change `lib/b.ex` to say `@attr [["text"], A]` instead, and then (after a full compile) append `lib/a.ex` with an empty line, `lib/b.ex` does not recompile.

Edit: Edited because I realized only two modules are needed to reproduce.

### Expected behavior

Sigil usage in module body should not turn atoms outside of this sigil into compile dependencies.

**Comment by josevalim** [comment]
This is tricky. We can assume knowledge if we can verify the imported version comes from Kernel.

**Comment by michallepicki** [comment]
So a custom sigil could use an atom listed _outside of it_ at compile time?

**Comment by josevalim** [comment]
A sigil is a macro, so it can do anything.

**Comment by zachdaniel** [comment]
I'm a bit confused on the idea here. Macros can do anything, but the module name isn't *inside* the invocation of the macro. Its outside of it. The implication here is that any macro could theoretically cause any module name it appears in a list with to be a compile time dependency?

**Comment by michallepicki** [comment]
Thank you @zachdaniel , I am also still unsure how a sigil macro could use this.

`plug` is also a macro, but when I pass a module name atom directly to it in its argument, there is no compile time dependency. Couldn't `plug` also use it for anything?

**Comment by michallepicki** [comment]
@josevalim Thank you, I confirmed the compile dependency is no longer there when using sigils in module attributes. But I am still seeing a compile dependency for my original use-case of a sigil inside of a plug invocation:
```
plug SomePlug, another_option: ~w(one two), fun_option: {OtherModule, :some_fun}
```

I understand removing this compile dependency would be too involved and is not planned for now?

**Comment by josevalim** [comment]
Plug would have to use Macro.expand_literals, but that would impose an Elixir v1.14.1 dependency. In other words, it will happen, but not immediately.
