### ISSUE TITLE
`:dbg_callback` runtime vs. compile time setting

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#12182]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Mac OS X

### Current behavior

I tried out `dbg` today. I ran it on `iex -S mix phx.server`, however I just wanted the debug printing and not pry, so I stopped the server and used `mix phx.server`. I then removed the `dbg` calls again. Later I stopped the server and went back to `iex -S mix phx.server` again to run some traces, which got me the following error:

```
Generated content_pool app
ERROR! the application :elixir has a different value set for key :dbg_callback during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was set to: {Macro, :dbg, []}
  * Runtime value was set to: {IEx.Pry, :dbg, []}

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile elixir --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag


** (ErlangError) Erlang error: "aborting boot"
    (elixir 1.14.0) Config.Provider.boot/2
```

### Expected behavior

I don't think any of my behaviour is unexpected, so I think there should be no error happening here.

**Comment by josevalim** [comment]
Hi @LostKobrakai!

Unfortunately I cannot reproduce the error. I tried it on Livebook like this:

1. Added `dbg()` to Livebook.live_markdown_to_elixir/1
2. Ran `iex -S mix phx.server`
3. Killed the server and ran `mix phx.server`
4. Removed `dbg()
5. Reloaded the page
6. Added `dbg()`
7.  Killed the server and ran `iex -S mix phx.server`

Maybe you can provide which steps lead to this error in Livebook?

**Comment by LostKobrakai** [comment]
In a freshly downloaded livebook folder (assets already setup):

1. Run `iex -S mix phx.server`
2. Add `dbg()` to `handle_event("new", …)` in `/lib/livebook_web/live/home_live.ex`: 
`{:noreply, create_session(socket) |> dbg()}`
3. Open homepage and create new livebook (cancel pry in console)
4. 2x `Ctrl+C` to stop the server
5. Run `mix phx.server`
6. Remove ` |> dbg()`
7. 2x `Ctrl+C` to stop the server
8. Run `iex -S mix phx.server`

This results in the error on my end.

**Comment by Rio517** [comment]
For others who also may run into this in phoenix apps, this is configured on your endpoint. Add to your confix.exs endpoint:

```
config :petal_pro, MyappWeb.Endpoint,
  .
  .
  reloadable_compilers: [:elixir, :app]
```

**Comment by mfeckie** [comment]
Thanks for documenting this, hit this today and was quite confused

**Comment by marpo60** [comment]
👋 

I was trying to setup a custom dbg_callback in a Livebook, without phoenix. 

I ended up doing this `Application.put_env(:elixir, :dbg_callback, {__MODULE__, :dbg, []})`
I saw that this was done in a [test](https://github.com/elixir-lang/elixir/commit/ffa6bd844e35a5feb94c98ae3930f86957437267#diff-c4f57fb0c1794e38f71b235379801e2a0611479225bfada72f9a8c5444239813R302)

Does it make sense to add that in this section: https://hexdocs.pm/elixir/main/Kernel.html#dbg/2-configuring-the-debug-function?
