### ISSUE TITLE
Potential breaking change in 1.14.1 with defimpl using __MODULE__

### ISSUE THREAD

**Issue by wkirschbaum** [elixir-lang/elixir#12186]
### Elixir and Erlang/OTP versions

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

Linux

### Current behavior

The following code fails to compile in 1.14.1, but compiles in 1.14.0

```
defmodule Foo do
  defstruct [:bar, :baz]

  defimpl Jason.Encoder, for: __MODULE__ do
    def encode(foo, opts) do
      %{
        bar: foo.bar,
        baz: foo.baz
      }
      |> Jason.Encode.map(opts)
    end
  end
end
```

Full example here: https://github.com/wkirschbaum/bug_check/actions/runs/3226477792 ( with test failures )

### Expected behavior

I would have expected this to not be a breaking change.

**Comment by josevalim** [comment]
Definitely a bug, thanks for the report. Note though, in this case, you can also remove `for: __MODULE__` and it will remain backwards compatible.

**Comment by wkirschbaum** [comment]
Thanks, did not know it can be removed. We just specified the module names explicitly which also works.

**Comment by josevalim** [comment]
Fixed in 35377072edf622d4ea26671e999e9e7a60627f32.

**Comment by hukl** [comment]
Just ran into the same issue. We use this to implement json formatters for different schemas. Intuitively I tried to remove the for: `__MODULE__` - that made the app compile again but broke our tests. I guess somehow namespace lookup now get confused or messed up. I really hope 1.14.2 will just magically work again. If not I can post code examples.

**Comment by hukl** [comment]
Indeed - huh! I didn't update my homebrew repo it seems. I can hereby confirm, that 1.14.2 fixes the issue :)
