### ISSUE TITLE
`Code.Typespec.fetch_specs` sometimes fails in Elixir 1.14+

### ISSUE THREAD

**Issue by marcandre** [elixir-lang/elixir#12189]
### Elixir and Erlang/OTP versions

```
$ elixir --version
Erlang/OTP 25 [erts-13.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 23)
```

### Operating system

Mac OS

### Current behavior

One of the following test fails in Elixir 1.14+ only, and only if `async: true` is present.

```elixir
defmodule EmptyMixTest do
  use ExUnit.Case, async: true

  test "example" do
    {:module, _module, binary, _} = defmodule Test, do: nil

    assert Code.Typespec.fetch_specs(binary) == {:ok, []}
  end

  test "another example" do
    {:module, _module, binary, _} = defmodule Test2, do: nil

    assert Code.Typespec.fetch_specs(binary) == {:ok, []}
  end
end
```

### Expected behavior

This seems like a regression and should work, right?

**Comment by josevalim** [comment]
We added `:test_elixirc_options` in v1.14, which defaults to `[docs: false, debug_info: false]` because those are actually not needed for most tests and therefore we can improve compilation. The second option disables the introspection for retrieving types which you can set to true in your mix.exs. I believe you can also set `@compile :debug_info` directly in the module, if you prefer.

**Comment by marcandre** [comment]
Ah! Thank you 😁 

I had actually checked if an explicit `elixirc_options: [debug_info: true]` had an effect, didn't realize there was a separate setting for test. Did you consider having `test_elixirc_options` be merged with `elixirc_options`?

Also, why do the tests pass when removing `async: true`?

**Comment by josevalim** [comment]
> Did you consider having test_elixirc_options be merged with elixirc_options?

Given they have different defaults, I think merging them would be more confusing. 

> Also, why do the tests pass when removing async: true? 

Oh, there is a race condition. I will address it soon.
