### ISSUE TITLE
Breaking change in expansion of pipe operator?

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/elixir#12196]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

macOS 12.6

### Current behavior

Since 1.14, `Macro.expand_once/2` or `expand/2` only expand the first level of the pipeline:

```elixir
Interactive Elixir (1.14.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Macro.expand_once((quote do: 1 |> foo() |> bar()), __ENV__)
{:bar, [],
 [{:|>, [context: Elixir, imports: [{2, Kernel}]], [1, {:foo, [], []}]}]}
````

In previous versions, it used to expand the whole pipeline:

```elixir
Interactive Elixir (1.13.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Macro.expand_once((quote do: 1 |> foo() |> bar()), __ENV__)
{:bar, [], [{:foo, [], [1]}]}
```

### Expected behavior

I'm not sure if this change is intended, but I thought it might be considered breaking and I couldn't find it documented in the changelog.
On the other hand, an implementation relying on the previous behavior was probably not a great idea, so it is probably not an issue in practice, I just wanted to confirm.

**Comment by josevalim** [comment]
The pipe macro itself was used to expand the whole pipeline recursively, but we changed that because it made dbg unable to see the pipeline.

I don’t think this is a breaking change however, because as you said, I don’t think the AST of a macro is part of its public contract. :)
