### ISSUE TITLE
Node.start does not work just after restarting macOS

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/elixir#12219]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

macOS Monterey 12.6.1

### Current behavior

Run the following command and function just after restarting macOS:

```
iex
```

```elixir
Node.start(:host, :shortnames)
```

Then I got the following error:

```elixir
07:25:06.212 [notice] Protocol 'inet_tcp': register/listen error: econnrefused

{:error,
 {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}},
  {:child, :undefined, :net_sup_dynamic,
   {:erl_distribution, :start_link,
    [
      %{
        clean_halt: false,
        name: :host,
        name_domain: :shortnames,
        net_tickintensity: 4,
        net_ticktime: 60,
        supervisor: :net_sup_dynamic
      }
    ]}, :permanent, false, 1000, :supervisor, [:erl_distribution]}}}
```

Once running the following:

```
iex --sname host -S mix
iex
```

Then I can run the following command successfully:

```elixir
Node.start(:host, :shortnames)
```

### Expected behavior

Run the following command and function successfully even just after restarting macOS:

```
iex
```

```elixir
Node.start(:host, :shortnames)
```

**Comment by wojtekmach** [comment]
All Node.start does it is calling the underlying :net_kernel.start. Could you report this to the OTP team instead?

**Comment by zacky1972** [comment]
OK!

**Comment by josevalim** [comment]
This is expected. For the Erlang distribution to work, you need `epmd` running. When you do `iex --sname` (or `erl -sname`), `epmd` is automatically started for you. However, if you kill `epmd`, you can reproduce the same failure without restarting the machine:

```
$ killall epmd
$ iex
Erlang/OTP 25 [RELEASE CANDIDATE 2] [erts-13.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Node.start(:host, :shortnames)

09:09:32.101 [notice] Protocol 'inet_tcp': register/listen error: econnrefused
```

Perhaps the error message could be clearer, either by changing the exit code to `noepmd` or by also logging a clearer reason, but the behaviour is expected. :)
