### ISSUE TITLE
Importing a module into itself should generate a clearer error

### ISSUE THREAD

**Issue by mmower** [elixir-lang/elixir#12225]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

macOS 10.14.6

### Current behavior

If you accidentally import a module into itself (for example, by completing the wrong thing in VSCode as I just did) you get a somewhat cryptic error:

```
defmodule Rez.Error do
  import Rez.Error
end
```

```
== Compilation error in file lib/error.ex ==
** (UndefinedFunctionError) function Rez.Error.module_info/1 is undefined (function not available)
    Rez.Error.module_info(:exports)
    (elixir 1.14.1) src/elixir_import.erl:98: :elixir_import.calculate/6
    (elixir 1.14.1) src/elixir_import.erl:28: :elixir_import.import/4
```

Essentially `module_info` is undefined. This leads you down a path that isn't likely to help you figure out the real problem, especially with a long and more challenging to read module name.

### Expected behavior

I'd expect the error to be along the lines of:

`error.ex:2 — you cannot import module Rez.Error into itself.`

**Comment by josevalim** [comment]
In main we get:

```
iex(1)> defmodule Foo do
...(1)> import Foo
...(1)> end
** (CompileError) iex:2: you are trying to use/import/require the module Foo which is currently being defined.
```

:)

**Comment by mmower** [comment]
I should have mentioned I am using `mix compile`. And I don't get the same error as observed.

**Comment by josevalim** [comment]
You are right, it doesn't happen on `mix compile`!

**Comment by mmower** [comment]
I can't edit my previous comment. I didn't realise that your comment "In main we get" was meant to be read as "I have fixed this, and now on the main branch, you get." Thanks, José.
