### ISSUE TITLE
String.downcase not working as expected

### ISSUE THREAD

**Issue by howtex** [elixir-lang/elixir#12237]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

### Operating system

Both Ubuntu (WSL) and windows

### Current behavior

ascii number 304 not working properly

iex(9)> <<cp::utf8>>=String.downcase(List.to_string([300]))
"ĭ"
iex(10)> <<cp::utf8>>=String.downcase(List.to_string([301]))
"ĭ"
iex(11)> <<cp::utf8>>=String.downcase(List.to_string([302]))
"į"
iex(12)> <<cp::utf8>>=String.downcase(List.to_string([303]))
"į"
iex(13)> <<cp::utf8>>=String.downcase(List.to_string([304]))
** (MatchError) no match of right hand side value: "i̇"

iex(13)> <<cp::utf8>>=String.downcase(List.to_string([305]))
"ı"
iex(14)> <<cp::utf8>>=String.downcase(List.to_string([306]))
"ĳ"
iex(15)> <<cp::utf8>>=String.downcase(List.to_string([307]))
"ĳ"
iex(16)> <<cp::utf8>>=String.downcase(List.to_string([308]))

String.downcase seems to be the culprit

iex(20)> <<cp::utf8>>=List.to_string([304])
"İ"
iex(21)> <<cp::utf8>>=String.downcase(List.to_string([304]))
** (MatchError) no match of right hand side value: "i̇"

### Expected behavior

iex(21)> <<cp::utf8>>=String.downcase(List.to_string([304]))
"İ"

**Comment by ericmj** [comment]
When converting the character `İ` to lower case it is being split into two code points. `::utf8` matches a single code point so the match fails.

This will match:
```elixir
iex(1)> <<first::utf8, second::utf8>> = String.downcase(List.to_string([304]))
"i̇"
```
