### ISSUE TITLE
mix test with absolute path on umbrella project root doesn't work as expected

### ISSUE THREAD

**Issue by joaopsramos** [elixir-lang/elixir#12233]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:32:12] [ds:32:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

Arch

### Current behavior

With a new umbrella project like this
.
├── apps
│   ├── bar
│   └── foo
├── _build
│   └── test
└── config
`pwd`: /tmp/umbrella

Running `mix test /tmp/umbrella/apps/bar/test/bar_test.exs` gives the following output:
```
==> foo
..
Finished in 0.01 seconds (0.00s async, 0.01s sync)
1 doctest, 1 test, 0 failures

Randomized with seed 436342
==> bar

Finished in 0.00 seconds (0.00s async, 0.00s sync)
0 failures

Randomized with seed 436342
```

Running the `foo_test.exs` gives the exact same result.

It looks like the tests are run for the same app which is the first to be compiled in an umbrella project.

### Expected behavior

It should run the right test when using an absolute path

**Comment by joaopsramos** [comment]
Correction: it actually runs the right test, only the output is wrong, making the `bar_test.exs` fail: (Note the file path on the error)
```
==> foo

  1) test greets the world (BarTest)
     apps/foo/tmp/umbrella/apps/bar/test/bar_test.exs:5
     Refute with == failed, both sides are exactly equal
     code: refute Bar.hello() == :world
     left: :world
     stacktrace:
       /tmp/umbrella/apps/bar/test/bar_test.exs:6: (test)

.
Finished in 0.01 seconds (0.00s async, 0.01s sync)
1 doctest, 1 test, 1 failure

Randomized with seed 869624
==> bar

Finished in 0.00 seconds (0.00s async, 0.00s sync)
0 failures

Randomized with seed 869624

```

**Comment by gilacost** [comment]
is the test folder at the same level as the apps in the umbrella @joaopsramos?

**Comment by joaopsramos** [comment]
> is the test folder at the same level as the apps in the umbrella @joaopsramos?

No, it's inside the `test/` directory of each app, `apps/foo/test/foo_test.exs`

**Comment by gilacost** [comment]
Apologies @joaopsramos, but I've been not able to reproducing this, at least in macos, maybe is something related to arch 🤷‍♂️? Please could you check [this](http://g.recordit.co/TgkVnfqgvh.gif) and tell me if I am doing something wrong 🙏 .

**Comment by joaopsramos** [comment]
Hi @gilacost, sorry for the late reply, the gif doesn't show you running the tests, so I can't tell if it is wrong or not, but in your case, the next step after the end of the gif would be to run `mix test /home/$USER/Repos/umbrella/apps/foo/test/foo_test.exs` (with absolute path) and check the output

**Comment by gilacost** [comment]
Hey @joaopsramos no worries for the timing at all 🤗! Please forgive me for the gif 🙏 , sometimes my brain just goes ahead time and believes I am done 😂 .  Please check [this one](http://g.recordit.co/nOfiBWFyek.gif) out! I am running `Elixir 1.15.0-dev (2cdb766) (compiled with Erlang/OTP 24)` thought, I will try to test it against `Elixir 1.14.1 (compiled with Erlang/OTP 25)` along the day and see if we have the same result  😛

**Comment by joaopsramos** [comment]
You have the same problem as me, note that you ran `foo_test` but the output shows as if from the `bar` app
![image](https://user-images.githubusercontent.com/53311154/204022551-34e12299-0378-4143-9aad-515e7bc4d369.png)

**Comment by gilacost** [comment]
I see what you mean 😄. I manage to reproduce but I think I've gone as far as I can go, at least for now. If anyone fancies iterating quickly, update the `test "umbrella with file path"` in `lib/mix/test/mix/tasks/test_test.exs`:
```elixir
    test "umbrella with file path" do
      in_fixture("umbrella_test", fn ->
        # Run false positive test first so at least the code is compiled
        # and we can perform more aggressive assertions later
        # output = mix(["test", "apps/unknown_app/test"])

        # assert output =~ """
        #        ==> bar
        #        Paths given to "mix test" did not match any directory/file: apps/unknown_app/test
        #        """

        # assert output =~ """
        #        ==> foo
        #        Paths given to "mix test" did not match any directory/file: apps/unknown_app/test
        #        """

        # output = mix(["test", "apps/bar/test/bar_tests.exs"])

        # assert output =~ """
        #        ==> bar
        #        ....
        #        """

        # refute output =~ "==> foo"
        # refute output =~ "Paths given to \"mix test\" did not match any directory/file"

        # output = mix(["test", "./apps/bar/test/bar_tests.exs"])

        # assert output =~ """
        #        ==> bar
        #        ....
        #        """

        # refute output =~ "==> foo"
        # refute output =~ "Paths given to \"mix test\" did not match any directory/file"

        # output = mix(["test", "apps/bar/test/bar_tests.exs:10"])

        # assert output =~ """
        #        ==> bar
        #        Excluding tags: [:test]
        #        Including tags: [line: \"10\"]

        #        .
        #        """

        # refute output =~ "==> foo"
        # refute output =~ "Paths given to \"mix test\" did not match any directory/file"

        foo_test_absolute_path = "#{fixture_path()}/umbrella_test/apps/foo/test/foo_tests.exs"
        # foo_test_absolute_path = "apps/foo/test/foo_tests.exs"
        expected_output = "==> foo"
        output = mix(["test", foo_test_absolute_path])
        assert expected_output == output |> String.split("\n") |> List.first()
      end)
    end
```

and then test with:

```bash
make compile && LINE=448 bin/elixir lib/mix/test/mix/tasks/test_test.exs
```

Cheers!
