### ISSUE TITLE
ParallelChecker ignores generated meta

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12264]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.3.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 24)
```

### Operating system

linux

### Current behavior

```sh
$ cat lib/bug.ex
```
```elixir
defmodule Bug do

  defmacro the_bug() do
    quote do
      defmodule unquote(X) do
        def f() do
          x = %{}
          %{x | one: 1, two: 2, three: 3}
        end
      end
    end
    |> Macro.prewalk(fn ast ->
      ast
      |> Macro.update_meta(&Keyword.put(&1, :generated, true))
      |> Macro.update_meta(&Keyword.put(&1, :line, 1234))
    end)
    |> Code.compile_quoted("file.ex")

    :well
  end

end
```

```sh
$ cat lib/caller.ex
```

```elixir
defmodule Caller do
  import Bug

  the_bug()
end
```

```sh
$ mix
Compiling 2 files (.ex)
warning: incompatible types:

    %{} !~ %{one: dynamic(), two: dynamic(), three: dynamic(), optional(dynamic()) => dynamic()}

in expression:

    # file.ex:1234
    %{x | one: 1, two: 2, three: 3}

where "x" was given the type %{} in:

    # file.ex:1234
    x = %{}

where "x" was given the type %{one: dynamic(), two: dynamic(), three: dynamic(), optional(dynamic()) => dynamic()} in:

    # file.ex:1234
    %{x | one: 1, two: 2, three: 3}

Conflict found at
  file.ex:1234: X.f/0

Generated bug app
```

### Expected behavior

No warning produced

**Comment by josevalim** [comment]
As of now, this is on purpose. This warning doesn’t check for the generated flag (mostly warnings that are style/convention related do).

**Comment by josevalim** [comment]
Btw, is there any particular reason why you are generating this code? Looking at the recent issues, it seems to be something related to random/fuzzy code generation? We could skip the warning but we should have good reasons to make it skippable when it will obviously fail at runtime!

**Comment by hissssst** [comment]
@josevalim, I am using it to test my compiler, so it actually makes sense.

```elixir
# This macro generates Abstract Term Format
abstract do
  x = %{}
  %{x | one: 1, two: 2, three: 3}
end
# This function translates in to the language
|> to_tria!()
# This macro performs matching assertion on AST
|> assert_tri do
  x = %{}
  %{x | one: 1, two: 2, three: 3}
end
```

**Comment by hissssst** [comment]
> We could skip the warning but we should have good reasons to make it skippable when it will obviously fail at runtime!

Well, `generated: true` silences warnings for `1 + "a"`, etc.

**Comment by josevalim** [comment]
Yes, that warning comes from Erlang but our goal is to move it to Elixir. For now, we plan to not silent them, but our minds may change in the future! You should be able to capture the warning if necessary.
