### ISSUE TITLE
Map update syntax in guards

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12261]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.3.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 24)
```

### Operating system

linux

### Current behavior

```elixir
iex(1)> case [1, 2, 3] do
...(1)>   x when %{%{x: 1} | x: 2} == %{x: 2} -> x
...(1)> end
** (CompileError) iex:3: cannot use map/struct update syntax in guard, got: %{%{x: 1} | x: 2}
```

### Expected behavior

Map update syntax in guards stays valid
See https://elixirforum.com/t/bug-in-elixir-map-update-in-guards/51688 for complete discussion

**Comment by josevalim** [comment]
Hi @hissssst, for now we don't plan to add support for this but it was good to know that it is a possibility given by Erlang. :)
