### ISSUE TITLE
Calendar.strftime/2 strange behaviour when year is negative integer

### ISSUE THREAD

**Issue by wingyplus** [elixir-lang/elixir#12266]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

macOS 12.5 (Monterey)

### Current behavior

In the [Calendar.strftime](https://github.com/elixir-lang/elixir/blob/947717755f3c9c59d326599db1bcbc556767402c/lib/elixir/lib/calendar.ex#L472) said that year will format as `-0001` when `year` in `Date` is negative value. But it's not in version 1.14.1:

```elixir
iex(3)> Date.new!(-1, 11, 30) |> Calendar.strftime("%Y%m%d")
"00-11130"
iex(4)> Date.new!(-11, 11, 30) |> Calendar.strftime("%Y%m%d")
"0-111130"
iex(5)> Date.new!(-111, 11, 30) |> Calendar.strftime("%Y%m%d")
"-1111130"
iex(6)> Date.new!(-1111, 11, 30) |> Calendar.strftime("%Y%m%d")
```

### Expected behavior

I expected that `-` sign should appear first and year with zero padding. For example:

```
-0001
-0011
-0111
-1111
```

**Comment by josevalim** [comment]
Definitely a bug. Would you like to send a PR? Otherwise I can tackle it later today. :)

**Comment by wingyplus** [comment]
PR opened. 🙇
