### ISSUE TITLE
Do not raise compile error from Kernel.Typespec

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#12277]
Instead we should raise `Kernel.TypespecError` that works exactly the same as `CompileError`. The raising code is already defined and encapsulated here:

https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/kernel/typespec.ex#L942-L944

**Comment by zacck** [comment]
Hi @josevalim  I'd like to work on this please

**Comment by josevalim** [comment]
Please go ahead!

**Comment by zacck** [comment]
Hi @josevalim  so we tried finding `Kernel.TypespecError` but could not find it or raise it, could we perhaps need to define the error or maybe use `Code.Typespec` cc @amos-kibet

**Comment by josevalim** [comment]
You would have to define it, yes!

**Comment by zacck** [comment]
Aha awesome on it! thank you

**Comment by zacck** [comment]
Hey @josevalim  so we think we solved it as you recommended, however we have a question since the new error works exactly the same as the older one. How come we had to implement and raise Kernel.typespecError? cc @lindakadz @amos-kibet @gettyorawo @okothokongo

**Comment by josevalim** [comment]
We changed CompileError in Elixir main to only contain a summary of the error, so this change is mostly to align with that change and have a specific error to typespecs.

**Comment by zacck** [comment]
@josevalim  thank you and changes pushed!
