### ISSUE TITLE
Macro.expand(quote(do: __ENV__), __ENV__) now with lexical_tracker

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12299]
### Elixir and Erlang/OTP versions

1.14.2

### Operating system

linux

### Current behavior

```elixir
Macro.expand(quote(do: __ENV__), %{__ENV__ | lexical_tracker: self()})
```

Returns AST with pid inside which is not an AST defined in `Macro.t`

### Expected behavior

```elixir
Macro.expand(quote(do: __ENV__), %{__ENV__ | lexical_tracker: self()})
```

Returns correct AST

**Comment by josevalim** [comment]
@hissssst do you want to PR this one using the other one as a template or should I go ahead? :)

**Comment by hissssst** [comment]
Yeah, will do
