### ISSUE TITLE
Macro.expand(quote(do: __ENV__)) returns non-AST

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12297]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.3.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 24)
```

### Operating system

linux

### Current behavior

```elixir
Macro.expand(quote(do: __ENV__), __ENV__)
```

Returns non-AST structure with `%{}` inside `versioned_vars` key

### Expected behavior

```elixir
Macro.expand(quote(do: __ENV__), __ENV__)
```

Returns valid AST
Or `Macro.expand` spec is fixed

**Comment by josevalim** [comment]
Fixed in https://github.com/elixir-lang/elixir/commit/d3f8a103a75931f12dbe40d4a7f6ea96426c36ac
