### ISSUE TITLE
`Time.add` behaviour changed in 1.14

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#12303]
### Elixir and Erlang/OTP versions

1.14.0

### Operating system

Mac OS

### Current behavior

1.13
```
iex(1)> Time.add(Time.new!(0, 0, 0), 1, :millisecond)
~T[00:00:00.001000]
```

1.14
```
iex(1)> Time.add(Time.new!(0, 0, 0), 1, :millisecond)
~T[00:00:00]
```

### Expected behavior

Not sure which one of those is meant to be the correct behaviour, but it feels like a breaking change. If this is indeed an intended change than it should at least be called out in the changelog for 1.14.

https://github.com/elixir-lang/elixir/commit/141996e61f3458c97415606c2b5749dfec8bdbc3#diff-5db8747f7a20154d5bb7e86aa4648c617f5d38ea02a703b3be28d2fc8bde3175L485

**Comment by josevalim** [comment]
The behaviour of Time.add was at least inconsistent with NaiveDateTime/DateTime but I think the correct behaviour is to keep the maximum precision of both time and the given unit.
