### ISSUE TITLE
`mix do` does not detect changes in `priv` directory when `release` task is used in `prod` env

### ISSUE THREAD

**Issue by DaniruKun** [elixir-lang/elixir#12307]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.14.2 (compiled with Erlang/OTP 25)
```

### Operating system

darwin, linux

### Current behavior

When running a sequence of tasks using `mix do` using `MIX_ENV=prod` and bundling a release with `release` as the final step, the changes to the `priv` dir are ignored.
For example, if we run `MIX_ENV=prod mix mytask + release`, and `mytask` e.g. generates some static files and puts them in `priv/static`, then the built release will be missing these files.
When running with `build_embedded: false`, this doesn't happen.
The current workaround is to call `mix mytask` and `mix release` separately.

### Expected behavior

Properly detect changes to `:code.priv_dir` in `mix do`, and have it be consistent between different MIX_ENVs

**Comment by josevalim** [comment]
Do you happen to have `build_embedded: true` in your mix.exs?

**Comment by DaniruKun** [comment]
@josevalim ah yep, it is enabled for `prod` env.
