### ISSUE TITLE
Compilation error message point to wrong line

### ISSUE THREAD

**Issue by csokun** [elixir-lang/elixir#12306]
### Elixir and Erlang/OTP versions

1.14.1

### Operating system

Ubuntu

### Current behavior

There is a syntax error in line 3, but the compiler report issue somewhere else.
![image](https://user-images.githubusercontent.com/29750/208563067-ff0d742b-6907-4a88-a4fb-6587ed0ffde4.png)

### Expected behavior

Expected compiler to point to line 3 missing `"`

**Comment by josevalim** [comment]
The error is correct. You started a string in that line and it spawned several lines, leading to the error. There is no way Elixir can know that part is invalid, because you could have a string with several lines as test name. :)
