### ISSUE TITLE
"Internal consistency check failed" when using range deconstruction in anonymous function

### ISSUE THREAD

**Issue by Karl255** [elixir-lang/elixir#12304]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

WSL Ubuntu 20.04.5 LTS on Windows 10 21H1 (build 19043.2251)

### Current behavior

Running the Elixir script

```elixir
Enum.map([1..5, 10..15], fn s..e = r ->
  r
end)
|> IO.inspect()
```

causes the error:

```
** (CompileError) elixir_compiler_0:1: function '-__FILE__/1-fun-0-'/1+6:
  Internal consistency check failed - please report this bug.
  Instruction: {get_map_elements,
                   {f,9},
                   {x,0},
                   {list,
                       [{atom,last},
                        {x,2},
                        {atom,first},
                        {x,2},
                        {atom,'__struct__'},
                        {x,1}]}}
  Error:       conflicting_destinations:

    (stdlib 4.0.1) lists.erl:1442: :lists.foreach_1/2
```

### Expected behavior

The code should work without crashing, just like it does when using an equivalent function within a module.

**Comment by sabiwara** [comment]
It seems to be an OTP issue from the [beam_validator](https://github.com/erlang/otp/blob/master/lib/compiler/src/beam_validator.erl#L81) module, there is already an issue reported here: https://github.com/erlang/otp/issues/6552 which seems similar (but might actually need to be reported as a separate issue?).

Here is a minimal example to reproduce it in iex:
```elixir
iex> Code.compile_string("fn _.._ = r -> r end")
** (CompileError) elixir_compiler_5:1: function '-__FILE__/1-fun-0-'/1+6:
  Internal consistency check failed - please report this bug.
```

**Comment by josevalim** [comment]
Thank you! Reported upstream here: https://github.com/erlang/otp/issues/6586
