### ISSUE TITLE
Code.compile_quoted floating bug

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#12300]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 24 [erts-12.3.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 24)
```

### Operating system

linux

### Current behavior

Sometimes `Code.compile_quoted` creates module with `abstract_code` chunk, sometime it does not

### Reproduction steps

1. Create an empty project
2. Create this file in test
```elixir
defmodule BugTest do
  use ExUnit.Case, async: true

  describe "well" do
    test "greets the world" do
      alias Enum, as: Enumm

      [{_, binary}] =
        quote do
          defmodule X do
            def f(x), do: x
          end
        end
        |> Code.compile_quoted()

      IO.inspect(:beam_lib.chunks(binary, [:abstract_code]))
    end
  end
end
```

3. Run it several times and see that sometimes it generates `abstract_code`, and sometimes it does not

https://user-images.githubusercontent.com/37012324/207561069-790c5d9b-cda3-4d69-ae7a-687dc2e2ce9b.mp4

### Expected behavior

Abstract Code chunk is always generated unless otherwise stated in `erlc_options`

**Comment by hissssst** [comment]
Looks like some ParallelCompiler data-race

**Comment by josevalim** [comment]
@hissssst it is because the test is async. This means the test is running while other test cases are loading and debug info is disabled while compiling tests (because they are unecessary).

**Comment by josevalim** [comment]
You can either make test cases sync or set `[test_elixirc_options: [debug_info: true, docs: true]]` so the behaviour is always consistent.

**Comment by josevalim** [comment]
Yes, the option is a new option introduced to speed up compilation of test files.

**Comment by hissssst** [comment]
Ahh, I've missed it in changelog

`[mix test] Support :test_elixirc_options and default to not generating docs nor debug info chunk for tests`

But I still can't see any reason why, if the default is to __not generate debug_info__, it generates it sometimes

**Comment by josevalim** [comment]
The configuration only applies while tests are loading. Once they are done loading, it reverts to `elixirc_options`, which has them set to true. Hence the race condition. The solutions mentioned above should address it.

PS: Fat finger reopened it by accident. :)

**Comment by hissssst** [comment]
Alright, got it, thanks for the explanation
