### ISSUE TITLE
:erpc.send_request/2 can't execute code on iex node

### ISSUE THREAD

**Issue by martosaur** [elixir-lang/elixir#12319]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

MacOS

### Current behavior

Steps (I'm using `:erpc.call` for simplicity):
1. Start iex session `iex --sname foo`
2. Start remote shell to the node: `iex --sname bar --remsh foo`
3. Define a module in your session:

    ```elixir
    defmodule Prober do
      def call_fn(node) do
        :erpc.call(node, fn -> IO.inspect("FOO") end)
      end
    
      def call_mfa(node) do
        :erpc.call(node, IO, :inspect, ["BAR"])
      end
    end
    ```

4. Try to call both functions for the `bar` node:
    ```elixir
    iex(foo@AliaksandrsMBP2)2> [node] = Node.list()
    [:bar@AliaksandrsMBP2]
    iex(foo@AliaksandrsMBP2)3> Prober.call_mfa(node)
    "BAR"
    "BAR"
    iex(foo@AliaksandrsMBP2)4> Prober.call_fn(node) 
    ** (ErlangError) Erlang error: {:exception, :undef, [{#Function<0.52990468/0 in Prober.call_fn/1>, [], []}, {:erlang, :apply, 2, []}]}
        (kernel 8.2) erpc.erl:505: :erpc.call/5
    ```

### Expected behavior

Both MFA and fn versions of :erpc.call should work.

**Comment by josevalim** [comment]
This is expected. A node can only execute the code of a function if said function exists in the remote node. `IO.inspect` ships as part of Elixir and therefore it will be available on other nodes. Anonymous functions in IEx are always evaluated (they belong to `erl_eval`) and therefore they work too. But a function from any other module, anonymous or not, needs to be defined in the target node. You either need to load said module on all nodes or avoid executing this code on nodes without said module.
