### ISSUE TITLE
Logger doesn't preserve `:domain` set at process metadata.

### ISSUE THREAD

**Issue by RudolfMan** [elixir-lang/elixir#12316]
### Elixir and Erlang/OTP versions

Elixir 1.14.2 (compiled with Erlang/OTP 25) _(and older, I guess)_

### Operating system

I tried on MacOS 12.6.2 (but I think it's the same everywhere else)

### Current behavior

```elixir
# stop all events with domain `[:elixir, :my_app, :foo | _]`
:logger.add_primary_filter(
  :filter_foo,
  {&:logger_filters.domain/2, {:stop, :sub, [:elixir, :my_app, :foo]}}
)

require Logger

Logger.metadata(domain: [:my_app, :foo])

Logger.info("hello") # still logs the message despite filter added
```

Or we could print domain as part of the metadata and see that it's replaced with `elixir`
```elixir
require Logger

Logger.configure_backend(:console, format: "$metadata$message\n", metadata: [:domain])

Logger.metadata(domain: [:my_app, :foo])

Logger.info("hello") # domain=elixir hello
```

### Expected behavior

It should behave same as when domain is passed optionally with metadata to `Logger.log/3` macro and friends.

For example this works as expected
```elixir
require Logger

Logger.configure_backend(:console, format: "$metadata$message\n", metadata: [:domain])

Logger.info("hello", domain: [:my_app, :foo]) # domain=elixir.my_app.foo hello
```
And it doesn't log when filter is set.
```elixir
:logger.add_primary_filter(
  :filter_foo,
  {&:logger_filters.domain/2, {:stop, :sub, [:elixir, :my_app, :foo]}}
)

require Logger

Logger.info("hello", domain: [:my_app, :foo]) # no log, just returns :ok
```

**Comment by RudolfMan** [comment]
I put together a possible solution here https://github.com/elixir-lang/elixir/commit/dc643b040feacc46fea02981976cbd14be17f776 
but I'm not sure if it's the right thing to do, as it would make every log event to read metadata one more time (I haven't benchmark it)

**Comment by josevalim** [comment]
Perhaps in your case the best option is to use `:logger` directly?

**Comment by RudolfMan** [comment]
> Perhaps in your case the best option is to use `:logger` directly?

Thanks for the quick response! The problem was when `Logger` is used in library.

Surely, I can set a custom key in metadata and filter out logs based on it or use other ways to suppress logs, I just thought this could be helpful to use erlang's built in `:logger_filters.domain/2`. Seems like it's not an option for elixir yet.

Thanks, for adding the clarification in the docs for `Logger.metadata/1`!
