### ISSUE TITLE
Weird App Dependency Errors in Umbrella

### ISSUE THREAD

**Issue by aselder** [elixir-lang/elixir#12318]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

OS X 13.2

### Current behavior

Getting warnings while compiling, such as:

```
warning: Core.AudienceSegments.get_audience_segment!/1 defined in application :core is used by the current application but the current application does not depend on :core. To fix this, you must do one of:

  1. If :core is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :core is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :core, you may optionally skip this warning by adding [xref: [exclude: [Core.AudienceSegments]]] to your "def project" in mix.exs
 ```

Both `core` and `shopkeeper_web` are apps in the same umbrella.  Here are the relevant parts of the mix.exs from `shopkeeper_web`:

```
# Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [
      mod: {ShopkeeperWeb.Application, []},
      extra_applications: [:logger, :runtime_tools]
    ]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [
      {:absinthe_phoenix, "~> 2.0"},
      {:core, in_umbrella: true},
      {:cors_plug, "~> 3.0"},
      {:dataloader, "~> 1.0"},
      {:esbuild, "~> 0.3", runtime: Mix.env() == :dev},
      {:fake_saml_idp, github: "pepsico-ecommerce/fake_saml_idp", only: [:dev, :test]},
      {:floki, ">= 0.30.0", only: :test},
      {:fun_with_flags, "~> 1.10.0"},
      {:fun_with_flags_ui, "~> 0.8"},
      {:gettext, "~> 0.18"},
      {:hackney, "~> 1.8"},
      {:jason, "~> 1.2"},
      {:oban_web, "~> 2.9", repo: "oban"},
      {:phoenix, "~> 1.6.14"},
      {:phoenix_ecto, "~> 4.4"},
      {:phoenix_html, "~> 3.0"},
      {:phoenix_live_dashboard, "~> 0.6"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.18.3"},
      {:phoenix_profiler, "~> 0.2.0"},
      {:plug_cowboy, "~> 2.5"},
      {:remote_ip, "~> 1.0"},
      {:samly, "~> 1.2"},
      {:sentry, "~> 8.0.0"},
      {:sobelow, "~> 0.8", only: [:dev, :test], runtime: false},
      {:tailwind, "~> 0.1", runtime: Mix.env() == :dev},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0"},
      {:timex, "~> 3.0"}
    ]
  end
```

This behavior seems to happen when a new module is added to `core` and then referenced from apps in the umbrella depending on `core`.

### Expected behavior

Compiles without warnings

**Comment by josevalim** [comment]
Thank you @aselder! Would it be possible for you to isolate and reproduce the issue in a smaller app or have a way for me to reproduce it locally? Feel free to also reach out to me privately.

**Comment by aselder** [comment]
@josevalim I'll see what I can do about isolating this into a simple test case, but that might be challenging since (except for one branch building in GitHub) we're having issues reproducing it locally consistently.

**Comment by jared-mackey** [comment]
Thanks for making this issue. I’d like to confirm that I’ve also been seeing this. I have been having a hard time reproducing it as well and have been hesitant to open an issue because of that. 

I usually run into it when pulling in git changes that have added a new app or dependency between apps and then running `mix compile`. However, it does not seem to be every time a change like that is made. To resolve it, I have to use `mix do clean, compile`.

**Comment by jared-mackey** [comment]
Not to hijack this issue, but another issue that I feel might be very related is that sometimes the compiler will allow a warning to sneak through even though we have warnings as errors turned on. When this happens, subsequent compilations do not even print the warning unless it has to recompile the module that produced it originally again. It feels related because it appears to be a similar compilation caching issue with umbrella apps. I have only seen this issue in an umbrella app. 

I’d be happy to open a separate issue for this but I fear it’ll be in the same boat of being very hard to reproduce consistently. So I wanted to at least mention it here so when someone is looking into this dependency problem they’d maybe also look at this warning issue as well.

**Comment by lukaszsamson** [comment]
I see this dependency warning quite often in elixir-LS when on umbrella apps. So far I wasn't able to isolate and reproduce it and it's transient. On the next compilation, especially if I re-trigger dependency umbrella child compilation it's gone.

**Comment by maennchen** [comment]
I have also seen this error before via Elixir LS in multiple projects. I tried to create a reproduction repo some time ago but failed to reproduce the issue.

**Comment by westmark** [comment]
I also have this problem and it went away after a recompile. However, I still have these issues showing up in VS Code, even though `mix compile` does not output any errors or warnings 😵‍💫

**Comment by jared-mackey** [comment]
@josevalim ❤️ thanks for the fix! Hoping that resolves the issue!

Do you believe that will also fix the issue with the cached warnings I mentioned above or should I make a separate issue for that?

Thanks so much 😄

**Comment by josevalim** [comment]
It is your call. If you can isolate it, please open up a bug report, otherwise let’s see if it has been addressed. :)

**Comment by Gigitsu** [comment]
I'm having the same problem but with ElixirLS and it seems to be a compile-time warning.

@josevalim I've created [this repository](https://github.com/Gigitsu/elixir_ls_umbrella_issue) to isolate and reproduce the issue, in the readme file I've put every info which I think could be useful. Hope it helps.

**Comment by josevalim** [comment]
Thank you @Gigitsu! :heart: Since it is specific to ElixirLS, I will ping @lukaszsamson so he takes a look at it first.

**Comment by Gigitsu** [comment]
Thank you @josevalim, in the meanwhile I'll do more investigations

**Comment by Gigitsu** [comment]
I tried to make it happen outside ElixirLS but without success. As far as I can see, ElixirLS execute this 

```sh
MIX_ENV=test MIX_TARGET=host mix compile --return-errors --ignore-module-conflict --all-warnings --no-protocol-consolidation
```

but when I execute that, I get no warnings.

I'm quite sure I'm using the same Elixir/Erlan installation used by ElixirLS so I don't know why I cannot reproduce the warning.

**Comment by lukaszsamson** [comment]
The main difference is that when you run mix from terminal you get a clean state everytime. What if you tried that from a single iex session?

**Comment by lukaszsamson** [comment]
@josevalim I'm able to reproduce it in iex on elixir 1.14.5

```
git clone git@github.com:Gigitsu/elixir_ls_umbrella_issue.git
cd elixir_ls_umbrella_issue
mix deps.get
iex
```
run this in iex
```
Mix.Local.append_archives()
Mix.start()
mixfile = Path.absname("mix.exs")
Kernel.ParallelCompiler.compile([mixfile])
Mix.Task.run("loadconfig")
Mix.Task.run("compile")
Mix.Task.clear()
```
with iex session still running rename module `Common.Lib` to `Common.Lib1` in `apps/common/lib/common/lib.ex` and import in `apps/non_phx_app/lib/non_phx_app/application.ex`
compile once again
```
Mix.Task.run("compile")

==> common
Compiling 1 file (.ex)
Generated common app
==> non_phx_app
Compiling 1 file (.ex)
warning: Common.Lib1.boo/0 defined in application :common is used by the current application but the current application does not depend on :common. To fix this, you must do one of:

  1. If :common is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :common is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :common, you may optionally skip this warning by adding [xref: [exclude: [Common.Lib1]]] to your "def project" in mix.exs

  lib/non_phx_app/application.ex:8: NonPhxApp.Application

warning: Common.Lib1.foo/0 defined in application :common is used by the current application but the current application does not depend on :common. To fix this, you must do one of:

  1. If :common is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs

  2. If :common is a dependency, make sure it is listed under "def deps" in your mix.exs

  3. In case you don't want to add a requirement to :common, you may optionally skip this warning by adding [xref: [exclude: [Common.Lib1]]] to your "def project" in mix.exs

  lib/non_phx_app/application.ex:6: NonPhxApp.Application
```

**Comment by lukaszsamson** [comment]
I'm not able to reproduce it on 1.15@52cf991302bfdc987a070ed4e1c2ba194ed47162 in neither iex nor ElixirLS so the changes to app tracer in 1.15 may have fixed it.
