### ISSUE TITLE
System.cmd hangs if command expects input on stdin; breaks iex

### ISSUE THREAD

**Issue by rlipscombe** [elixir-lang/elixir#12321]
### Elixir and Erlang/OTP versions

1.13.4 and 1.14.2

### Operating system

Ubuntu 22.04 (WSL)

### Current behavior

```
 % iex
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> System.cmd("cat", [])

User switch command
 --> s
 --> c
Eshell V13.1.2  (abort with ^G)
1> :erlang.processes()
1>
```

That `:erlang.processss()` does nothing; just returns to the prompt. Tab completion's completely broken.

### Expected behavior

The first command should probably fail when `cat` attempts to read from stdin. At the least, the shell shouldn't be hosed.

**Comment by rlipscombe** [comment]
Originally reported at https://stackoverflow.com/questions/75035674/how-can-i-get-system-cmd-to-end-normally

**Comment by josevalim** [comment]
The new shell you start is an Erlang shell (the prompt is the hint):

```
Interactive Elixir (1.15.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> System.cmd("cat", [])

User switch command
 --> s
 --> c
Eshell V13.0  (abort with ^G)
1> erlang:processes().
[<0.0.0>,<0.1.0>,<0.2.0>,<0.3.0>,<0.4.0>,<0.5.0>,<0.6.0>,
 <0.7.0>,<0.10.0>,<0.42.0>,<0.44.0>,<0.46.0>,<0.47.0>,
 <0.49.0>,<0.50.0>,<0.51.0>,<0.52.0>,<0.53.0>,<0.54.0>,
 <0.55.0>,<0.56.0>,<0.57.0>,<0.58.0>,<0.59.0>,<0.60.0>,
 <0.61.0>,<0.62.0>,<0.63.0>,<0.64.0>|...]
```

Related to SO, it is necessary to understand what both ack and rg expect on an empty pattern. It may be that, like cat, they are waiting for an input, and therefore it is expected `System.cmd` will block until said input is given (which is not possible). You either need to invoke them directly or use the low-level Port module.

**Comment by rlipscombe** [comment]
> The new shell you start is an Erlang shell (the prompt is the hint)

Doh! I've been doing Erlang all day, so that didn't jump out as different.

I'm assuming that if there had been a way to make new jobs be Elixir jobs, it would already have happened...? Or is that an open issue?

> it is expected System.cmd will block until said input is given (which is not possible)

Is it worth adding an option to `System.cmd` that closes stdin, for when you're running commands that hang like this?

**Comment by josevalim** [comment]
> I'm assuming that if there had been a way to make new jobs be Elixir jobs, it would already have happened...? Or is that an open issue?

You can make it happen by typing `s 'Elixir.IEx'`. I am considering making it shorter as `s iex`.

> Is it worth adding an option to System.cmd that closes stdin, for when you're running commands that hang like this?

AFAIK ports do not allow to close stdin. But maybe there could be an option to close it immediately after start.
