### ISSUE TITLE
mix command failes when path contains brackets like (x86)

### ISSUE THREAD

**Issue by kiru** [elixir-lang/elixir#12330]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads: 1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OT 25)

### Operating system

Tested on Windows 7 and Windows 10

### Current behavior

A releas created with "mix release" on a newly created project on Windows should run from a folder which contains space and brackets. 

### To reproduce: 

````
C:\demo>mkdir "with (x86)"

C:\demo>cd "with (x86)"

C:\demo\with (x86)>mix new demo
* creating README.md
* creating .formatter.exs
* creating .gitignore
* creating mix.exs
* creating lib
* creating lib/demo.ex
* creating test
* creating test/test_helper.exs
* creating test/demo_test.exs

Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:

    cd demo
    mix test

Run "mix help" for more commands.

C:\demo\with (x86)>cd demo
C:\demo\with (x86)\demo>mix release.init
* creating rel/vm.args.eex
* creating rel/remote.vm.args.eex
* creating rel/env.sh.eex
* creating rel/env.bat.eex

C:\demo\with (x86)\demo>mix release
Compiling 1 file (.ex)
Generated demo app
* assembling demo-0.1.0 on MIX_ENV=dev
* skipping runtime configuration (config/runtime.exs not found
* creating _build/dev/rel/demo/releases/0.1.0/vm.args
* creating _build/dev/rel/demo/releases/0.1.0/remote.vm.args
* creating _build/dev/rel/demo/releases/0.1.0/env.sh
* creating _build/dev/rel/demo/releases/0.1.0/env.bat

Release created at _build/dev/rel/demo

    # To start your system
    _build/dev/rel/demo/bin/demo start

Once the release is running:

    # To connect to it remotely
    _build/dev/rel/demo/bin/demo remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/dev/rel/demo/bin/demo stop

To list all commands:

    _build/dev/rel/demo/bin/demo


C:\demo\with (x86)\demo>
C:\demo\with (x86)\demo>cd _build/dev/rel/demo/bin

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>demo version
demo 0.1.0

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>demo start
"\demo\_build\dev\rel\demo\releases\0.1.0\sys""" kann syntaktisch an dieser Stelle nicht verarbeitet werden.

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>
````

The error is in German and says something like "could not process at this location". I don't have access to a Windows Machine English (if you have one, please post the error as text in the comments, just for the sake of searchability). 

This issue could be related to https://github.com/elixir-lang/elixir/issues/9242. 

### Why?
We are migrating a project from [distillery](https://github.com/bitwalker/distillery) to `mix release`. We already had many issues regarding spaces in path and patched the relevant distillery scripts by hand.

We deploy to Windows machine, where the application is copied to "C:\Program Files (x86)\folder\", so that is where we encountered this issue. 

I will analyze the issue further and post more details.

**Comment by kiru** [comment]
I removed "@echo off" and rerun the script to see where the error originates: 

````
C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>demo start

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>setlocal enabledelayedexpansion

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>pushd .

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>cd "C:\demo\with (x86)\demo\_build\dev\rel\demo\bin\\.."

C:\demo\with (x86)\demo\_build\dev\rel\demo>set RELEASE_ROOT=C:\demo\with (x86)\demo\_build\dev\rel\demo

C:\demo\with (x86)\demo\_build\dev\rel\demo>popd

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>if not defined RELEASE_NAME (set RELEASE_NAME=demo )

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>if not defined RELEASE_VSN (for /F "tokens=1,2" %K in ('type "!RELEASE_ROOT!\releases\start_erl.data"') do (set ERTS_VSN=%K )  && (set RELEASE_VSN=%L ) )

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>if not defined RELEASE_PROG (set RELEASE_PROG=demo.bat )

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>set RELEASE_COMMAND=start

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>set REL_VSN_DIR=!RELEASE_ROOT!\releases\!RELEASE_VSN!

C:\demo\with (x86)\demo\_build\dev\rel\demo\bin>call "!REL_VSN_DIR!\env.bat"
"\demo\_build\dev\rel\demo\releases\0.1.0\sys""" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
````

**Comment by josevalim** [comment]
Thank you @kiru! Feel free to submit a pull request if you run into a fix. :)

**Comment by josevalim** [comment]
@kiru note i could not reproduce the failure here: https://github.com/elixir-lang/elixir/pull/12331

**Comment by josevalim** [comment]
Note that test only tests eval command though. Can you double check if eval works or fails for you?

**Comment by kiru** [comment]
> @kiru note i could not reproduce the failure here: https://github.com/elixir-lang/elixir/pull/12331

That is strange. Looking at the test, I am not sure what the difference it makes if you call the script via cmd.exe vs calling it via ?`Symstem.cmd()`

> Note that test only tests eval command though. Can you double check if eval works or fails for you?

Yes, the error also occurs for eval. The exact error message in English is: `"\demo\_build\dev\rel\demo\releases\0.1.0\sys""" was unexpected at this time.`

We found the root cause. It's in [elxir.bat](https://github.com/elixir-lang/elixir/blob/main/bin/elixir.bat#L136):
> if ""==!par:-r=!          (set "parsElixir=!parsElixir! -r %1" && shift && goto startloop)

If you call the elixr.bat from a folder with parenthesis, like this: 
> elixir.bat --erl-config "C:\(run)\demo\_build\dev\rel\demo\releases\0.1.0\sys"

Then, at some point elixir.bat:136 will run with `%1` being the parameter given to `--erl-config`:

 >  if ""==!par:-r=!          (set "parsElixir=!parsElixir! -r "C:\(run)\demo\_build\dev\rel\demo\releases\0.1.0\sys"" && shift && goto startloop)

Now, windows will interpret the `"` and parenthesis ([0]) and sees: 
>  if ""==!par:-r=!          (
>     set "parsElixir=!parsElixir! -r "
 >    C:\(run
> )
> \demo\_build\dev\rel\demo\releases\0.1.0\sys"" && shift && 

Hence, we end up with the error message `"\demo\_build\dev\rel\demo\releases\0.1.0\sys"""` being unexpected, as it thinks it's an command to run. 

The simple fix was to add a tilde to `%~1`, what that changes is that we don't have the double-quotes anymore: 
>  if ""==!par:-r=!          (set "parsElixir=!parsElixir! -r C:\(run)\demo\_build\dev\rel\demo\releases\0.1.0\sys" && shift && goto startloop)

I will create a PR for this.

[0] https://www.reddit.com/r/Batch/comments/gpfere/comment/frlqhv9/?utm_source=share&utm_medium=web2x&context=3
