### ISSUE TITLE
Git sparse checkout doesn't pull dependencies in umbrella

### ISSUE THREAD

**Issue by Efesto** [elixir-lang/elixir#12348]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.2 (compiled with Erlang/OTP 23)

### Operating system

macOS

### Current behavior

When trying to pull a dependency configured with `:git` and `:sparse` options pointing to an app belonging to an umbrella application that requires a dependency within the umbrella, `mix deps.get` will not pull the additional dependency.

This yields to a `dependency is not available` error  trying to comple the app.

see https://github.com/elixir-lang/elixir/commit/a7cfa15caac2148b5159c1b855eb48e5b09b9fda for a reproducing test.

### Expected behavior

The dependency in umbrella is pulled together with the referred app

**Comment by Efesto** [comment]
## Hotfix

Add the additional dependency explicitly, using `:sparse` option as well and `override: true`

**Comment by josevalim** [comment]
Yes, we don't expect this to work either, as path dependencies will always be considered path dependencies. You can either use sparse and override but it is prefferrable for you to break them into regular dependencies if you want to use them externally.

**Comment by Efesto** [comment]
Understood, I've updated my hotfix comment with two possible solutions
