### ISSUE TITLE
Improve output control in mix xref

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#12343]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

The `--format dot` option for the [`mix xref`](https://github.com/elixir-lang/elixir/blob/main/lib/mix/lib/mix/tasks/xref.ex) command is hard-coded to write into `xref_graph.dot` in the current directory.  This seems inflexible and inefficient; worse, it could cause name collisions.

### Expected behavior

The command should allow output to be sent to stdout and/or a specified path.

**Comment by josevalim** [comment]
We can support `--output`. If `-` is given, it will write to stdout.

**Comment by RichMorin** [comment]
That would be great; thanks!

**Comment by RichMorin** [comment]
Thanks, all.
