### ISSUE TITLE
Wrong character escaping in bin/elixir

### ISSUE THREAD

**Issue by wejn** [elixir-lang/elixir#12345]
### Elixir and Erlang/OTP versions

I'd guess any version since https://github.com/elixir-lang/elixir/blob/127ae4b069bff1469d2b620d9f54683db665ab6e/bin/elixir#L239 and possibly older.

### Operating system

Linux (alpine edge)

### Current behavior

When trying to bump Alpine's `community/elixir` package to 1.14.3, I discovered a presubmit issue where our build infra throws an error:

```
sed: bad regex '[^a-zA-Z0-9_\-/]': Invalid character range
```

Tracking this down: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/43260#note_283537 I think the sed regex in `bin/elixir` (https://github.com/elixir-lang/elixir/blob/127ae4b069bff1469d2b620d9f54683db665ab6e/bin/elixir#L239) that was tweaked in #8736 is wrong:

``` sh
# alpine 3.12
alpine:~# sed 2>&1 | head -n 1
BusyBox v1.31.1 () multi-call binary.
alpine:~# echo "abc/-\\~%" | sed 's/[^a-zA-Z0-9_\-\/]/\\&/g'
abc/\-\\~\%

# alpine edge
alpine:~# sed 2>&1 | head -n 1
BusyBox v1.36.0 (2023-01-12 15:07:31 UTC) multi-call binary.
alpine:~# echo "abc/-\\~%" | sed 's/[^a-zA-Z0-9_\-\/]/\\&/g'
sed: bad regex '[^a-zA-Z0-9_\-/]': Invalid character range

# gnu sed on debian
$ sed --version | head -n 1
sed (GNU sed) 4.7
$ echo "abc/-\\~%" | sed 's/[^a-zA-Z0-9_\-\/]/\\&/g'
abc/\-\\~\%

# with my quickfix:
$ echo "abc/-\\~%" | sed 's@[^a-zA-Z0-9_/-]@\\&@g'
abc/-\\\~\%

# and FTR, original:
$ echo "abc/-\\~%"
abc/-\~%
```

and only recent upgrade of busybox, which became stricter about regex parsing, is failing on the regex. GNU sed seems to be silently ignoring the issue.

The reason why the regex is wrong is outlined in detail on [the failed alpine merge](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/43260#note_283537) but essentially, there's unintentional invalid character range `\-/` supplied to the `sed`.

I think it should be `sed 's@[^a-zA-Z0-9_/-]@\\&@g'` instead. That way (the `-` at the end) you don't create a range, and by using `@` as separator you avoid the perilous escaping of `/`.

### Expected behavior

As described above, I think the https://github.com/elixir-lang/elixir/blob/127ae4b069bff1469d2b620d9f54683db665ab6e/bin/elixir#L239 should read:

```
 ESCAPED="$ESCAPED $(echo "$PART" | sed 's@[^a-zA-Z0-9_/-]@\\&@g')"
```

because IMO the intent is to escape all characters but alphanumeric and `_`, `/`, `-`.

**Comment by josevalim** [comment]
@wejn would you like to submit a pull request? :)

**Comment by wejn** [comment]
> @wejn would you like to submit a pull request? :)

Sure thing. Need a few more hours before I have time to do that, tho.
