### ISSUE TITLE
Square Bracket Access After Function Call In Pipeline Causes Piped Argument to Not Be Recognized

### ISSUE THREAD

**Issue by jpramassini** [elixir-lang/elixir#12351]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 25)

### Operating system

Mac OS Monterey 12.5

### Current behavior

I am trying to access a map field's value from an item in a list within a pipeline of functions. This data structure is the result of a previous function (simplified to just a data structure for this example), and is piped into `Enum.at`, after which I am attempting to access a field of the retrieved value from the list.

For example:

```elixir
hello = [%{user: "username"}]
hello |> Enum.at(0)[:user]
```
When running this code, I get a

```
** (UndefinedFunctionError) function Enum.at/1 is undefined or private. Did you mean:

      * at/2
      * at/3

    (elixir 1.14.1) Enum.at(0)
```
error.

When replacing the square bracket access with
```elixir
hello |> Enum.at(0) |> Access.get(:user)
```
I successfully get back `"username"` as expected.

### Expected behavior

I would expect that I could use square bracket accessing after function calls within a pipeline, as the access would be evaluated on the result of the function call, however it appears that the bracket access is evaluated before the function and its arguments are. This also could be a lack of understanding on the scoping of the pipe on my part, as the `Enum.at` expression is now doing that and accessing, so I may be misinterpreting which of the operations the pipe is actually getting applied to. My expectation would be that the pipe applies to the `Enum.at` in this case, as it would evaluate first before the access can run. Thanks!

**Comment by jpramassini** [comment]
Breaking all code written today definitely sounds like a less than ideal outcome! The improved error message would definitely be helpful in this case, and could probably provide a quick workaround given the alternatives are so easy to switch to here with good info about what's breaking (either not using the pipe at all or using `Access.get` instead of the square brackets.). Thanks for the quick response!

**Comment by jpramassini** [comment]
@josevalim, is there any chance this would be a good first issue to work on? The scope seems relatively small and I've been looking for an opportunity to contribute. If not, no worries, but if so I'd love to help out. I would probably benefit from direction to the generation for `Access`, since I'm unfamiliar with the codebase, but I've found the Macro.pipe code.

**Comment by josevalim** [comment]
@jpramassini check elixir_parser.yrl, that's where we generate the ast for Access.get. :)
