### ISSUE TITLE
Code.compile_string does not respect parser_options

### ISSUE THREAD

**Issue by scohen** [elixir-lang/elixir#12364]
### Elixir and Erlang/OTP versions

1.13.4, 1.14.0, 14.1,  1.14.2, 1.14.3

### Operating system

macos

### Current behavior

From the documentation, it seems that setting compiler options affects the compiler globally. It also states that `Code.compiler_options` takes the `parser_options` key and all of the options defined in `Code.string_to_quoted`. 

```elixir
code_with_error = """
defmodule MyModule do 
  def error do 
    %{
  end
end
"""
parser_opts = [line: 5, column: 5]
Code.put_compiler_option(:parser_options, parser_opts)
iex(11)> Code.string_to_quoted(code_with_error, parser_opts)
{:error,
 {[line: 8, column: 3],
  {"unexpected reserved word: ",
   ". The \"{\" at line 7 is missing terminator \"}\""}, "end"}}


iex(12)> Code.compile_string(code_with_error)
{:error,
 {[line: 4, column: 3],
  {"unexpected reserved word: ",
   ". The \"{\" at line 3 is missing terminator \"}\""}, "end"}}
```

### Expected behavior

The error line should be 8 in the call to `compile_string` and the column should be 8 in both examples.
The same thing happens when invoking the `mix compile` task via `Mix.Tasks.run("compile")`

I'm not sure if this is a documentation problem or a problem in the code, but I'm working on the elixir language server, and it would be very nice to be able to have zero-based columns and lines so we don't have to keep adding and subtracting 1 everywhere. 

Thanks for looking into this!

**Comment by josevalim** [comment]
Just as a heads up, it is a documentation/clarify issue. Changing parser options on calls to string_to_quoted may break libraries running alongside the code server. The compiler options affect the code compiled globally, but not the global options. I will clarify it later.

**Comment by scohen** [comment]
@josevalim thanks for the quick response, I'm not following; The problem is that the compiler options don't affect the code compiled globally. 

There's also a secondary problem where the column option passed into `string_to_quoted` doesn't seem to have an effect, but I'm most interested in changing things globally so I can get diagnostics that match the lsp conventions.

**Comment by doorgan** [comment]
Something worth noting is that apparently `line` and `column` options are not "parser options", but rather options specific to `string_to_quoted` to initialize the tokenizer. So it's not a compiler option, and it's not a parser option either.

**Comment by scohen** [comment]
@josevalim the documentation is still incorrect or misleading, setting these options does not affect `Code.compile_string`'s line or columns.

**Comment by josevalim** [comment]
Oh,  I understand now. Yes, those options do not apply in this case. What is the use case for setting the line and column globally?

**Comment by scohen** [comment]
So, I'm working on an elixir language server, and unlike `elixir_ls`, this one runs a separate BEAM process that surrounds a project.  The language server then injects a small amount of control code into the created VM. The reasoning here is that we don't want the language server's code to pollute a project's code and we don't want a project's code to pollute the language server (there's a TON of code in `elixir_ls` that tries to un-do this pollution, and it's really not necessary, and it doesn't work very well).

Among other things, this separate VM will do builds, and it would be great if I could adjust the lines and columns to be zero-based, as this is what the LSP spec requires. It looked like this was possible by setting these options, but this has been extremely fraught.

It would _also_ be super cool if I could get warnings out of the compiled code somehow without having to capture io, but this doesn't look possible to me.
