### ISSUE TITLE
Path uses slash (/) instead of backslash (\) on windows

### ISSUE THREAD

**Issue by kitofr** [elixir-lang/elixir#1236]
Windows usually works best with paths that uses backslash, and regularly fail with forward slashes. Therefore I propose that:

Path.join("foo", "bar") should return "foo\bar" on windows, not "foo/bar".

I'm however to new to the language to propose a solution, or even better a pull request. Is there a way to know that elixir is currently executing on windows?

**Comment by mspanc** [comment]
#1231 was closed long time ago and this bug is still present. IMO it should be reopened. 

```
iex(1)> Mix.Project.app_path()
"c:/Users/me/aktivitis/radiokit/myapp/_build/dev/lib/myapp"
```

It causes a lot of trouble if you pass this path to any external command.

**Comment by ericmj** [comment]
@mspanc It is not a bug. A separate function is needed that transforms the path from forwardslashes to backslashes

**Comment by mspanc** [comment]
@ericmj why? Elixir is probably the only known language where Path.join and similar functions ignore the fact that windows use backslashes. What is the rationale behind this?

**Comment by ericmj** [comment]
José Valim explains it in this comment https://github.com/elixir-lang/elixir/issues/1236#issuecomment-19370645.

**Comment by josevalim** [comment]
@mspanc you are not supposed to care about forward or backward slashes inside the VM, unless you are passing the path to something outside of the VM in which you can then explicitly convert to backward slashes.
