### ISSUE TITLE
Mix.Compilers.ApplicationTracer.warnings/1 very slow when :ets table includes many objects

### ISSUE THREAD

**Issue by naserca** [elixir-lang/elixir#12367]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.14.3 (compiled with Erlang/OTP 25)
```

### Operating system

MacOS 11.3.1

### Current behavior

We have a very large Phoenix.Router: ~1900 lines

After some debugging, I added some profiling around only the `Mix.Compilers.ApplicationTracer.warnings/1` call [here](https://github.com/elixir-lang/elixir/blob/v1.14/lib/mix/lib/mix/compilers/elixir.ex#L464) like:
```elixir
start = System.monotonic_time()
warnings = Mix.Compilers.ApplicationTracer.warnings(modules)
finish = System.monotonic_time()
time = System.convert_time_unit(finish - start, :native, :millisecond)
IO.puts(
  :stderr,
  "[profile] Mix.Compilers.ApplicationTracer.warnings for #{length(modules)} modules in #{time}ms"
)
```

The output of `time mix compile --profile time` now looks like:
```
Compiling 1 file (.ex)
[profile]   9456ms compiling +      0ms waiting for lib/foo_web/router.ex
[profile] Mix.Compilers.ApplicationTracer.warnings for 2 modules in 24227ms
[profile] Finished compilation cycle of 2 modules in 33697ms
[profile] Finished group pass check of 32 modules in 960ms
mix compile --profile time  33.60s user 13.01s system 118% cpu 39.311 total
```

This is due to having to call `:code.which/1` (~25ms per module) on ~1000 modules [here](https://github.com/elixir-lang/elixir/blob/v1.14/lib/mix/lib/mix/compilers/application_tracer.ex#L117).

I can't quite figure out the context of [the comment](https://github.com/elixir-lang/elixir/blob/v1.14/lib/mix/lib/mix/compilers/application_tracer.ex#L115) `# If the module belongs to this application (from another compiler), we skip it.` enough to understand the best way to improve this.

Let me know if anything seems obvious!

### Expected behavior

`Mix.Compilers.ApplicationTracer.warnings/1` should run faster. (I think!)

**Comment by josevalim** [comment]
@naserca could you share this router somehow? Even if privately with me? :)

**Comment by josevalim** [comment]
Or, perhaps even easier, can you please try this PR out, @naserca? https://github.com/elixir-lang/elixir/pull/12368

**Comment by naserca** [comment]
Definitely an improvement! From ~24s to ~7s.

```
Compiling 1 file (.ex)
[profile]   9278ms compiling +      0ms waiting for lib/foo_web/router.ex
[profile] Mix.Compilers.ApplicationTracer.warnings for 2 modules in 7364ms
[profile] Finished compilation cycle of 2 modules in 16657ms
[profile] Finished group pass check of 32 modules in 966ms
mix compile --profile time  21.82s user 5.38s system 122% cpu 22.179 total
```

We just genuinely have a ton of distinct controller modules in the file.

**Comment by josevalim** [comment]
@naserca I pushed another commit to the branch, can you please try latest?

**Comment by naserca** [comment]
No change from the initial commit.

**Comment by josevalim** [comment]
@naserca hrm, the second commit is meant to make a huge difference because we are now deleting the apps that belong to the current application. That should remove most of the calls. Can you please try only the second commit or investigate if we are indeed removing entries from the table?

**Comment by naserca** [comment]
Will check on Monday! Thanks for looking into this!

**Comment by josevalim** [comment]
Btw, the reason why `:code.which/1` is expensive is due to filesystem lookups. I am actually working on a patch for Erlang to address this. Here is my branch: https://github.com/josevalim/otp/tree/jv-all-boot-patches

To install with asdf:

    export OTP_GITHUB_URL="https://github.com/josevalim/otp"
    asdf install erlang ref:195084956a05c437d2ac4962a2fd047f69da7ee1

Besides speeding this up, it should also speed up boot time. Do the command below with your regular Erlang at least 4 times and let us know the last 3:

    $ time mix run -e 1

Then try the fork and let us know if it is any faster.

**Comment by josevalim** [comment]
@naserca I picked another approach altogether and removed the application tracer in main. Please give it a try. The new branch should give faster boot times and faster compilation times for dependencies in large projects.

**Comment by tessi** [comment]
Hey, I'm running the same huge elixir app @naserca does. To save Alex some time, I tried to get the timings, but run into an error.

What I did:

```
asdf install erlang ref:9a4ac730d87a9b4bbea720e71aa2a570bb739681
asdf shell erlang ref:9a4ac730d87a9b4bbea720e71aa2a570bb739681

# probably not needed, but I wanted to make sure nothing is cached
asdf uninstall elixir 1.14.3-otp-25
asdf install elixir 1.14.3-otp-25
```

now the timing fails during compilation:

```
❯ time mix run -e 1
Compiling 5269 files (.ex)

== Compilation error in file lib/<snip>.ex ==
** (CompileError) Elixir.<snip>:1: function <snip>/2+14:
  Internal consistency check failed - please report this bug.
  Instruction: {bs_match,{f,0},
                         {y,3},
                         {commands,[{integer,3,{literal,[]},16,1,{x,0}}]}}
  Error:       throws_exception:

    (stdlib 4.2) lists.erl:1568: :lists.foreach_1/2
```

is this me being stupid or the changed OTP branch?

**Comment by tessi** [comment]
Thanks for looking into it 💜 I reduced and anonymized the module as much as possible so that it still triggers the compiler exception. It now fails with a _slightly_ different error when running with `elixir lib/<snip>.ex`.

```
defmodule ReproduceCompilationBug do
  def run(_) do
    for element <- [] do
      Enum.each([], &inner(&1, element))
    end
  end

  defp inner(_a, b) do
    c =
      case b do
        "1000" -> :test
        "1001" -> :test2
      end

      ReproduceCompilationBug.run(c)

    case b do
      "b" -> :b
    end
  end
end
```

```
❯ elixir reproduce_compilation_bug.ex
** (CompileError) Elixir.ReproduceCompilationBug:1: function inner/2+13:
  Internal consistency check failed - please report this bug.
  Instruction: {bs_match,{f,0},
                         {y,1},
                         {commands,[{integer,0,{literal,[]},16,1,{x,0}}]}}
  Error:       throws_exception:

    (stdlib 4.2) lists.erl:1568: :lists.foreach_1/2
```

**Comment by josevalim** [comment]
Awesome job. Reported upstream here: https://github.com/erlang/otp/issues/6755

**Comment by tessi** [comment]
oh, wow. you could remove the `run()` function, didn't check that 🤦 thanks for further reducing the example :)

**Comment by josevalim** [comment]
@tessi I have updated my comment with the fix from the Erlang/OTP team. :) So you can try it again if you are interested!

**Comment by tessi** [comment]
Hey @josevalim

this time, it compiled :) here are the timings (each with 3 not-listed warm-up runs before)

### with OTP 25.2

* mix run -e 1  4.07s user 3.70s system 157% cpu 4.919 total
* mix run -e 1  4.10s user 3.75s system 160% cpu 4.888 total
* mix run -e 1  4.14s user 3.79s system 156% cpu 5.073 total

### with `ref:f3e0f6b1bb207321eb65cf7c08f18c1c7f2854ec`

* mix run -e 1  3.88s user 3.34s system 136% cpu 5.306 total
* mix run -e 1  3.90s user 3.36s system 136% cpu 5.301 total
* mix run -e 1  3.98s user 3.63s system 138% cpu 5.476 total

**Comment by josevalim** [comment]
Ah, that's shame. I was hoping for bigger gains but it seems it is roughly around 5%. Thanks for giving it a run!

**Comment by naserca** [comment]
@josevalim You know this already ;) but this commit https://github.com/elixir-lang/elixir/commit/845c20a33524f1946a2660e5c7d4c8904cc79d30 has completed squashed all the dead-weight time from a recompilation of the big router. All that's left is the profiled ~9s of the router file and the boot time. Thank you as always!!

💚 💙 💜 💛 ❤️

Do you want this work in the `v1.14` branch? Happy to open an MR to port it.

**Comment by josevalim** [comment]
The work unfortunately is not "safe" to be backported. v1.15 should be out in May/June. :)

**Comment by naserca** [comment]
Makes sense! Thanks again!
