### ISSUE TITLE
Mix test.coverage fails with an exception raised

### ISSUE THREAD

**Issue by tjchambers** [elixir-lang/elixir#12377]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 23)

### Operating system

Ubuntu 22.04

### Current behavior

```
$ mix test.coverage
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        (tools 3.5.3) cover.erl:1782: :cover.do_compile_beam2/6
        (tools 3.5.3) cover.erl:1672: :cover.do_compile_beam/3
        (stdlib 4.1) lists.erl:1320: :lists.map_1/2
        (stdlib 4.1) lists.erl:1320: :lists.map_1/2
        (stdlib 4.1) lists.erl:1315: :lists.map/2
        (tools 3.5.3) cover.erl:3150: anonymous fn/2 in :cover.pmap_spawn/4
    (tools 3.5.3) cover.erl:777: :cover.call/1
    (mix 1.14.3) lib/mix/tasks/test.coverage.ex:216: anonymous fn/2 in Mix.Tasks.Test.Coverage.cover_compile/1
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.14.3) lib/mix/tasks/test.coverage.ex:215: Mix.Tasks.Test.Coverage.cover_compile/1
    (mix 1.14.3) lib/mix/tasks/test.coverage.ex:148: Mix.Tasks.Test.Coverage.run/1
    (mix 1.14.3) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

### Expected behavior

I expected it to run the test suite (which is 100% green) and list the coverage details. I have tried this with and without ex_coveralls - same behavior. I am not sure whether this is an elixir issue or an erlang issue. 

I would be happy to debug this if I had any ideas provided as to how and where to dive in.

**Comment by josevalim** [comment]
Hi @tjchambers! I think for now you will have to debug this a bit further to determine the root cause. Do this:

1. Go to your Erlang installation and find the cover.erl file. It is likely at `lib/tools/src/cover.erl`.
2. Add a `erlang:display({pre, Module}),` call right before the line you get the MatchError, and a similar ` `erlang:display({post, Module}),` after
3. Inside `lib/tools`, run `erlc -o ebin src/cover.erl`
4. Run the command again and it will find the failed module

Now that you know which module fails, we need to try to understand why it fails. You can try making the module empty. Does it at least run the test suite now? With a bit of add and remove you should find which part of the module is problematic.

From there, I can help with either reporting or fixing it upstream.

Good luck!

**Comment by tjchambers** [comment]
thanks for the rapid response @josevalim!

I did as you requested, but unfortunately not getting anything definitive. I get different results everytime I run my command for example: 

```
{pre,'Elixir.SctWeb.TcaParticipantHTML'}
{pre,'Elixir.Sct.Telemetry'}
{pre,'Elixir.SctWeb.ObservationController'}
{post,'Elixir.SctWeb.LifeHistoryController'}
{post,'Elixir.Sct.JOE.OeResult'}
{post,'Elixir.Sct.Tasks.ResultsInvitationCheckupTask'}
{post,'Elixir.SctWeb.CollectPointsController.SctWeb.CollectPointsForm'}
{post,'Elixir.SctWeb.ThemeMatrixController'}
{post,'Elixir.Sct.Tasks.DeleteTempThemesTask'}
{post,'Elixir.SctWeb.OeConclusionHTML'}
{post,'Elixir.Sct.Cldr.Number.Cardinal'}
{post,'Elixir.SctWeb.ActivityController'}
{post,'Elixir.SctWeb.ObjectiveActualController'}
{post,'Elixir.SctWeb.ObservationController'}
{post,'Elixir.Sct.Repo'}
{post,'Elixir.SctWeb.CondensedSeedsInvitationHTML'}
{post,'Elixir.SctWeb.TcaParticipantHTML'}
{post,'Elixir.SctWeb.ThemeHTML'}
{post,'Elixir.Sct.Align'}
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        (tools 3.5.3) src/cover.erl:1785: :cover.do_compile_beam2/6
        (tools 3.5.3) src/cover.erl:1672: :cover.do_compile_beam/3
        (stdlib 4.1) lists.erl:1320: :lists.map_1/2
        (stdlib 4.1) lists.erl:1320: :lists.map_1/2
        (stdlib 4.1) lists.erl:1315: :lists.map/2
```

and another run:

```
{pre,'Elixir.Sct.Internal.TopicTracker'}
{post,'Elixir.SctWeb.PointHTML'}
{post,'Elixir.Sct.Cldr.DateTime'}
{post,'Elixir.Sct.Tasks.SeedInvitationCheckupTask'}
{pre,'Elixir.Sct.Telemetry'}
{post,'Elixir.Sct.Internal.TopicTracker'}
{post,'Elixir.Sct.Cldr.Number.PluralRule.Range'}
{post,'Elixir.SctWeb.SwimlaneController'}
{post,'Elixir.Sct.Cldr'}
{post,'Elixir.Sct.Repo'}
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        (tools 3.5.3) src/cover.erl:1785: :cover.do_compile_beam2/6
        (tools 3.5.3) src/cover.erl:1672: :cover.do_compile_beam/3
        (stdlib 4.1) lists.erl:1320: :lists.map_1/2
        (stdlib 4.1) lists.erl:1320: :lists.map_1/2
        (stdlib 4.1) lists.erl:1315: :lists.map/2
```

SO it does not appear deterministic. I infer there is some parallel activity in progress. 

I tried instrumenting so of the compilation modules, but similar results. I also took all of my test suite out (which was passing green on over 1000 tests). 

Any further suggestions to isolate the root cause?

**Comment by josevalim** [comment]
I think the issue was on my suggestion on how to instrument it. Instead of pre and post,  can you pattern match on the result of compile:forms and log only in case of `error`?

**Comment by tjchambers** [comment]
Quite a journey for a noob. I had to learn some erlang. But I did get to the bottom of the issue:

```elixir
defmodule Sct.Telemetry do
  @moduledoc false

  use Supervisor
  import Telemetry.Metrics

  @spec start_link(any) :: :ignore | {:error, any} | {:ok, pid}
  def start_link(arg) do
    Supervisor.start_link(__MODULE__, arg, name: __MODULE__)
  end

  # @spec init(...) :: {:ok, tuple} <--- the offending line
  def init(_arg) do
    children = [
      {:telemetry_poller, measurements: periodic_measurements(), period: 10_000}
    ]

    Supervisor.init(children, strategy: :one_for_one)
  end

  @spec metrics :: [Telemetry.Metrics.Summary.t(), ...]
  def metrics do
    [
      # Phoenix Metrics
      summary("phoenix.endpoint.stop.duration",
        unit: {:native, :millisecond}
      ),
      summary("phoenix.router_dispatch.stop.duration",
        tags: [:route],
        unit: {:native, :millisecond}
      ),

      # Database Time Metrics
      summary("sct.repo.query.total_time", unit: {:native, :millisecond}),
      summary("sct.repo.query.decode_time", unit: {:native, :millisecond}),
      summary("sct.repo.query.query_time", unit: {:native, :millisecond}),
      summary("sct.repo.query.queue_time", unit: {:native, :millisecond}),
      summary("sct.repo.query.idle_time", unit: {:native, :millisecond}),

      # VM Metrics
      summary("vm.memory.total", unit: {:byte, :kilobyte}),
      summary("vm.total_run_queue_lengths.total"),
      summary("vm.total_run_queue_lengths.cpu"),
      summary("vm.total_run_queue_lengths.io")
    ]
  end

  defp periodic_measurements do
    []
  end
end
``` 

It was the `@spec` on the `init` function that was causing the failure. I copied this module from somewhere over a year ago - do not recall from where. I note that in a fresh Phoenix 1.7 rc 0 install I made that line reads `@impl true` and is not an `@spec` at all. 
 
Once I commented out that line and ran `mix test --cover` (that and `mix test.coverage` both failed before) I got the test coverage analysis. Other than __ don't add that @spec I am not sure whether this warrants future action. Although it would have been nice to at least know the Module name that was at fault instead of having to instrument.  

FWIW here was my (sloppy) code change to dump out the Module before the failure:

```erlang
    %% original
    %% {ok, Module, Binary} = compile:forms(Forms, Options),

    Result =  compile:forms(Forms, Options),

    case Result of
        error ->
            erlang:display({error, Module});
        _Else ->
            true
    end,

    {ok, Module, Binary} = Result,
    ```

**Comment by josevalim** [comment]
You did great! You did find an Elixir bug, you cannot use `...` there. But Elixir was failing to report it, which sent invalid code to Erlang, which then crashed. I will push a fix soon. Thanks and awesome job!

**Comment by tjchambers** [comment]
@josevalim thanks for taking the ball from here! I could not have done it without your help. Got me some erlang under my belt too. So wins all around. Appreciate the rapid responses.
