### ISSUE TITLE
Confusing error message from ExUnit when setup returns incorrect type

### ISSUE THREAD

**Issue by benregn** [elixir-lang/elixir#12381]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.1 (compiled with Erlang/OTP 23)

### Operating system

macOS 12.6 (21G115)

### Current behavior

In my test `setup` I had a function call as the last thing which returns {:ok, _} and, of course, got an error:

```
** (RuntimeError) expected ExUnit callback in MyAppWeb.UsersLive.IndexTest to return :ok | keyword | map, got {:ok, true} instead
     stacktrace:
       (ex_unit 1.14.1) lib/ex_unit/callbacks.ex:688: ExUnit.Callbacks.raise_merge_failed!/2
```

### Expected behavior

It took me bit to realize my mistake because I didn't immediately connect the error to be about something in the `setup`. Maybe the error message could be improved?

**Comment by wojtekmach** [comment]
What'd be the ideal error message in your opinion?

**Comment by benregn** [comment]
Maybe if it directly mentions that it's the incorrect return from the `setup`. Cherry on top would include the return line in the stracktrace 😄

**Comment by whatyouhide** [comment]
@benregn the error message says that the "ExUnit callback" (= `setup`) was expected to return this and that, but it returned this other thing. I agree the location would be nice, I can work on a PR for that, but other than that do you think we could improve the actual error message itself? Can you show an example if you do?

**Comment by josevalim** [comment]
I think we could say "ExUnit setup callback" or "ExUnit setup_all callback". Showing the line is tricky because tail call elimination but we can wrap the code slightly around.

**Comment by benregn** [comment]
For me personally, just including `setup` or `setup_all` in the error message would improve it the most because that is a more explicit than having to make the mental jump from `ExUnit callback` -> `setup`/`setup_all`.
