### ISSUE TITLE
Encode Base 64 error

### ISSUE THREAD

**Issue by loscarepapa** [elixir-lang/elixir#12401]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macos big sur 11.7

### Current behavior

Trying to replicate javascript's btoa function to encode accents returns a different base 64

in btoa the word Mexico returns
> var sourceStr = "México";
> var encodedStr = btoa(sourceStr);
> encodedStr

'teh4aWNv'

elixir:
iex(1)> Base.encode64("México")
"TcOpeGljbw=="

### Expected behavior

in btoa the word Mexico returns
> var sourceStr = "México";
> var encodedStr = btoa(sourceStr);
> encodedStr

'teh4aWNv'

elixir:
iex(1)> Base.encode64("México")
"teh4aWNv"

**Comment by josevalim** [comment]
According to the docs:

> The btoa() function takes a JavaScript string as a parameter. In JavaScript strings are represented using the UTF-16 character encoding: in this encoding, strings are represented as a sequence of 16-bit (2 byte) units. Every ASCII character fits into the first byte of one of these units, but many other characters don't. 

Elixir strings are represented using UTF-8. Since they underlying representation differs, their encoding will differ too. The JS docs has hints on how to handle this: https://developer.mozilla.org/en-US/docs/Web/API/btoa
