### ISSUE TITLE
The pin doesn't pin

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#12407]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

Given the following module:
```elixir
defmodule Test do
  def test() do
    zero = 0
    one = 1

    result = ^one = zero
    IO.inspect({zero, one})
    result
  end
end
```

Running `Test.test()` outputs:
```elixir
iex(1)> Test.test()
{0, 0}
0
```

### Expected behavior

The code should fail with a match error.

This is caused by an issue in Erlang: https://github.com/erlang/otp/issues/6873. The issue exists at least in OTP 24 and 25. The current OTP master does not present it.
However, given how serious in terms of language semantics the issue is, I decided to report it here as well - Elixir might want to employ some sort of mitigation through compiling to a different code pattern.

**Comment by josevalim** [comment]
Thank you!

**Comment by sopotc** [comment]
> The issue exists at least in OTP 24 and 25

Also in 23 as confirmed by OTP.

**Comment by josevalim** [comment]
Closing as it has been backported to OTP 23, 24, 25. Thanks @michalmuskala !
