### ISSUE TITLE
Tests for maps fail with OTP26

### ISSUE THREAD

**Issue by moogle19** [elixir-lang/elixir#12403]
### Elixir and Erlang/OTP versions

Elixir: main
OTP: 26.0-rc1

### Operating system

macOS

### Current behavior

Many tests for maps fail, since the sort ordering changed for OTP26 (https://www.erlang.org/news/160#maps).
This mostly concerns `Enum` and `Inspect` functions, since the test require a specific ordering in their `asserts`.

### Expected behavior

The tests shouldn't assume a specific sorting order for maps.

**Comment by josevalim** [comment]
Yes, please see #11985.
