### ISSUE TITLE
"Naming Conventions" suggestions

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#12419]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

The [Naming Conventions](https://hexdocs.pm/elixir/naming-conventions.html) page leaves out quite a bit of critical information.

### Expected behavior

The page should be expanded to include both conventions (may) and rules (must).  A number of picky details could also be usefully added, e.g.:

- What characters may be used at the start of a name?
- What characters may be used within a name?
- How many digits may be used in the function arity?
- What is the role of periods in module names?
- What rules apply to module attributes?
- What possible conflicts are there with Erlang naming?

**Comment by josevalim** [comment]
Many of your questions are answered in the syntax reference, but it is not linked, I will do so. The goal of the naming convention is to be more lightweight than precise.

**Comment by RichMorin** [comment]
Thanks!
