### ISSUE TITLE
Change in system variables aborts incremental compilation

### ISSUE THREAD

**Issue by bruno-delfino1995** [elixir-lang/elixir#12411]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:32:24] [ds:32:24:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux

### Current behavior

Given the following module and config:

```elixir
# lib/play.ex

defmodule PlayEx do
  @name Application.compile_env(:play_ex, __MODULE__, []) |> Keyword.get(:name, nil)

  def hello() do
    IO.puts("Hello, #{@name}")
  end
end

# config/config.exs

import Config

config :play_ex, PlayEx, name: System.get_env("NAME", "Unknown")
```

When compiling with a variable different from the first successful compilation, I get an error, but everything works fine if I clean the previous results.

```bash
$ NAME=A mix compile
Compiling 1 file (.ex)
Generated play_ex app

$ NAME=B mix compile
ERROR! the application :play_ex has a different value set for key PlayEx during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:

  * Compile time value was set to: [name: "A"]
  * Runtime value was set to: [name: "B"]

To fix this error, you might:

  * Make the runtime value match the compile time one

  * Recompile your project. If the misconfigured application is a dependency, you may need to run "mix deps.compile play_ex --force"

  * Alternatively, you can disable this check. If you are using releases, you can set :validate_compile_env to false in your release configuration. If you are using Mix to start your system, you can pass the --no-validate-compile-env flag


** (ErlangError) Erlang error: "aborting boot"
    (elixir 1.14.0) Config.Provider.boot/2

$ mix clean

$ NAME=B mix compile
Compiling 1 file (.ex)
Generated play_ex app
```

### Expected behavior

I thought the change would trigger a new compilation because you should get an application that behaves differently, given the new configuration. I was on the assumption that `mix` tracked configuration values, but it seems that only file changes trigger new compilations.

**Comment by josevalim** [comment]
You are right. We track it is invalid but, in this particular case, we could detect it has changed and recompile. I will explore if doing such check is not expensive and do so.

**Comment by josevalim** [comment]
So I have investigated this and unfortunately the check is not that quick. And, if it is slow, it will make every mix operation (such as `mix test`) slower. So for now I will prefer to not add this check, given the costs can be high and I think the usage is not that common.

Btw, is there a reason why you don't treat it as a runtime configuration instead?

**Comment by bruno-delfino1995** [comment]
That's a bummer :frowning_face: but I prefer this "issue" to slower commands. There's no particular reason blocking me from using a runtime configuration instead. I was porting a monolithic application to runtime configs but couldn't port everything simultaneously because of its size. So I found this "issue" while looking for alternative methods to configure our external environment while keeping caches.

Is there a reference to this behavior on Mix's docs? If I haven't missed anything there, I guess I could drop a PR with a note for that o/
