### ISSUE TITLE
`defguard` not considered covered except if "invoked" from tests

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [elixir-lang/elixir#12420]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macOS 12.5.1

### Current behavior

`defguard` is not considered "covered" in tests (not all the time, at least)

### Expected behavior

# To replicate

```bash
mkdir /tmp/defguard_cover && pushd /tmp/defguard_cover

mix new . --app defguard_cover

cat <<EOT > lib/defguard_cover.ex
defmodule DefguardCover do
  defguard is_int(i) when is_integer(i)
  def is_int?(i) when is_int(i), do: true
  def is_int?(_), do: false
end
EOT

cat <<EOT > test/defguard_cover_test.exs
defmodule DefguardCoverTest do
  use ExUnit.Case
  require DefguardCover

  test "greets the world" do
    assert DefguardCover.is_int?(1)
    refute DefguardCover.is_int?(:a)
  end
end
EOT

mix test --cover # coverage is 66.67%
```

# Expected results

That `defguard` is considered "covered" for the above tests.

Interestingly enough, if called from the test module itself, the `defguard` is considered covered.

**Comment by josevalim** [comment]
Short answer: defguard is a macro, so it is expanded at compile time and therefore not covered except if invoked/expanded on tests.
