### ISSUE TITLE
String.replace/3 on non-breakable space (0x00A0) with \w match returns unprintable output

### ISSUE THREAD

**Issue by travelmassive** [elixir-lang/elixir#12422]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.3.2.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 23)

### Operating system

Ubuntu 20.04.1 LTS

### Current behavior

Background:  

I received some user input in my Phoenix LiveView app that caused a broken page (constant reload).

The input contained an invisible U+00a0 (no break space) from iPhone keyboard input. When preparing the input for rendering, I use a regex (to format links, etc) that uses a \w character class. Using the \w character class with a string that contains U+00a0 results in non-printable output.

Examples:

```
String.printable?(<< 0x00A0 :: utf8 >>)  # true
String.printable?(String.replace(<< 0x00A0 :: utf8 >>, ~r/\w/, "")) # false
```

This behaviour also happens with 0x202f (narrow no-break space)

```
String.printable?(<< 0x202f :: utf8 >>) # true
String.printable?(String.replace(<< 0x202f :: utf8 >>, ~r/\w/, "")) # false
```

Note: These are simple examples above to demonstrate the issue. The same result also happens for \W (non-word) regex.

In the meantime, I've stripped 0x00A0 from any input before managing it with regex. 

This was a bit of a tricky issue to hunt down, so I'm submitting an issue in case other people are experiencing the same.

This might be related to #4300

Thanks for any advice! ~ Ian

### Expected behavior

Invoking String.replace with a \w or \W regex on non-breakable space (0x00A0) should return printable output.

**Comment by whatyouhide** [comment]
```elixir
iex> 0x00A0
160
iex> inspect(<<0x00A0 :: utf8>>, base: :hex)
"<<0xC2, 0xA0>>"
iex> String.replace(<<0x00A0 :: utf8>>, ~r/\w/, "")
<<160>>
```

Seems like replacing `\w` is stripping the `0xC2` UTF-8 part.

**Comment by josevalim** [comment]
Regexes are not Unicode by default, so if you pass a Unicode encoded string, it won't behave as expected:

```
iex(2)> String.replace(<<0x00A0 :: utf8>>, ~r/\w/u, "") == <<0x00A0 :: utf8>>
true
```

**Comment by travelmassive** [comment]
Thanks for taking a look at this — a quick followup question.

What is the best way to safely handle regexes with Unicode?  This seems like a common pattern for doing stuff with user-submitted text such as linkifying, markdown, etc. And most of the time the regex works with text containing emojis, japanese characters, etc, so these particular characters are a "gotcha" for unsuspecting developers (like me!).

**Comment by josevalim** [comment]
Sorry, my answer was probably not clear, but you can pass the /u to the regex to make it Unicode aware.

**Comment by maennchen** [comment]
I too have seen people beeing unaware of the issue of using unicode regexes for unicode strings.

Is there some way we could warn users if unicode strings are provided to a regex and the flag is not set?

**Comment by josevalim** [comment]
The problem is that it is impossible to know with 100% accuracy if a string is Unicode or random blobs. Even invalid Unicode strings could be passed through a regex to capture valid bits, and such checks would likely be expensive (at least they have a linear cost!)

**Comment by maennchen** [comment]
@josevalim Yeah, that would be quite inefficient.

The only way I can think of otherwise is to make the choice explicit. We could create a modifier for the current standard behaviour and warn if neither the unicode modifier nor the new modifier is supplied.

Not sure though if that would be too much noise though to migrate current codebases…
