### ISSUE TITLE
Parallel Compiler crashes in umbrella app when a test runs `File.cd!`/`Mix.Task.run`

### ISSUE THREAD

**Issue by halfdan** [elixir-lang/elixir#12437]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

MacOS Ventura 13.0

### Current behavior

In an umbrella app there can be a race condition where ExUnit has started running tests while the ParallelCompiler is still in the process of asynchronously requiring test files. If one of the tests getting executed happens to call `File.cd` (which changes the `cwd` of the entire BEAM) the parallel compiler will be unable to construct the correct absolute path to the test file in an umbrella app.

This can be demonstrated by creating a dummy umbrella app, with one app in it. Since ExUnit happens to run test files in an alphabetical order we can create a test file `a_dummy_test.exs` that changes the `cwd` using `File.cd` (or in the case of my example repo it happens to try and run a mix task (`Mix.Task.run`). To ensure the parallel compiler remains busy we create a bunch of dummy tests. 

It could be argued that `File.cd` should not be called in any test but it seems the recommended way of testing mix tasks is by calling `Mix.Task.run` which will inadvertently call `File.cd!` in https://github.com/elixir-lang/elixir/blob/v1.14.3/lib/mix/lib/mix/project.ex#L403-L407 when it tries to execute a mix task in the app directory. 

The issue is that the parallel compiler will call [`Path.expand`](https://github.com/elixir-lang/elixir/blob/v1.14.3/lib/elixir/lib/kernel/parallel_compiler.ex#L330) as it spawn workers. This happens as it requires the files and not beforehand. The bug could be fixed by `Path.expand`ing the files in https://github.com/elixir-lang/elixir/blob/v1.14.3/lib/elixir/lib/kernel/parallel_compiler.ex#L140-L142 or even upstream. 

Here's a dummy project that can replicate the issue: https://github.com/halfdan/elixir-crashing-compiler

```
➜  mix test
==> core
.................
== Compilation error in file test/hello_1015_test.exs ==
** (MatchError) no match of right hand side value: {:error, :enoent}
    (elixir 1.14.3) lib/kernel/parallel_compiler.ex:449: Kernel.ParallelCompiler.require_file/2
    (elixir 1.14.3) lib/kernel/parallel_compiler.ex:342: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7

13:36:52.205 [error] GenServer Mix.ProjectStack terminating
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Mix.ProjectStack.recur/1
    (mix 1.14.3) lib/mix/project_stack.ex:223: anonymous fn([]) in Mix.ProjectStack.recur/1
    (mix 1.14.3) lib/mix/project_stack.ex:310: Mix.ProjectStack.handle_call/3
    (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
    (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
    (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.95.0>): {:update_stack, #Function<22.127266841/1 in Mix.ProjectStack.recur/1>}
State: {[], []}
Client #PID<0.95.0> is alive

    (stdlib 4.1.1) gen.erl:237: :gen.do_call/4
    (elixir 1.14.3) lib/gen_server.ex:1035: GenServer.call/3
    (mix 1.14.3) lib/mix/project_stack.ex:223: Mix.ProjectStack.recur/1
    (mix 1.14.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.14.3) src/elixir_compiler.erl:66: :elixir_compiler.dispatch/4
    (elixir 1.14.3) src/elixir_compiler.erl:51: :elixir_compiler.compile/3
    (elixir 1.14.3) src/elixir_compiler.erl:39: :elixir_compiler.eval_or_compile/3
    (elixir 1.14.3) src/elixir_lexical.erl:15: :elixir_lexical.run/3
    (elixir 1.14.3) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
    (elixir 1.14.3) lib/module/parallel_checker.ex:110: Module.ParallelChecker.verify/1
    (elixir 1.14.3) lib/code.ex:1260: Code.require_file/2
    (elixir 1.14.3) lib/kernel/cli.ex:574: Kernel.CLI.wrapper/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.3) lib/kernel/cli.ex:83: Kernel.CLI.process_commands/1
    (elixir 1.14.3) lib/kernel/cli.ex:37: anonymous fn/2 in Kernel.CLI.main/1
    (elixir 1.14.3) lib/kernel/cli.ex:131: anonymous fn/3 in Kernel.CLI.exec_fun/2
** (exit) exited in: GenServer.call(Mix.ProjectStack, {:update_stack, #Function<22.127266841/1 in Mix.ProjectStack.recur/1>}, :infinity)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Mix.ProjectStack.recur/1
            (mix 1.14.3) lib/mix/project_stack.ex:223: anonymous fn([]) in Mix.ProjectStack.recur/1
            (mix 1.14.3) lib/mix/project_stack.ex:310: Mix.ProjectStack.handle_call/3
            (stdlib 4.1.1) gen_server.erl:1149: :gen_server.try_handle_call/4
            (stdlib 4.1.1) gen_server.erl:1178: :gen_server.handle_msg/6
            (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (elixir 1.14.3) lib/gen_server.ex:1038: GenServer.call/3
    (mix 1.14.3) lib/mix/project_stack.ex:223: Mix.ProjectStack.recur/1
    (mix 1.14.3) lib/mix/cli.ex:84: Mix.CLI.run_task/2
    (elixir 1.14.3) lib/code.ex:1260: Code.require_file/2
```

### Expected behavior

The parallel compiler should be able to handle a change of `cwd`.

**Comment by josevalim** [comment]
Thank you for the well done report @halfdan!

`cwd` is a global property so any test that calls `cwd` cannot run asynchronously. We could change the compiler but I am certain other parts of the tooling can exhibit faulty behaviour too. Not only the tooling but your tests themselves, for example, if you do any Code.require_file from your test files or try to load any fixture using relative directories.

So my suggestion is to mark any test that changes cwd as sync. Thanks!

**Comment by halfdan** [comment]
@josevalim That mostly makes sense. I think it's still a bit odd the parallel compiler will crash like this and it would be trivial to make it safe for this particular case. It's an implementation detail currently that ExUnit will wait for all modules to be loaded before starting the sync test suite. 

That said - I do agree with the general assessment that the test should simply be sync ;)
