### ISSUE TITLE
`mix test --profile-require` expects undocumented `time` argument

### ISSUE THREAD

**Issue by halfdan** [elixir-lang/elixir#12439]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

MacOS Ventura

### Current behavior

`mix test --profile-require` has an [undocumented](https://github.com/elixir-lang/elixir/blob/49aec4cbfa7861a486fae24ce048bde3ba2bf74c/lib/mix/lib/mix/tasks/test.ex#L164-L165) string argument. 

The only valid value for it seems to be `time`  (https://github.com/elixir-lang/elixir/blob/49aec4cbfa7861a486fae24ce048bde3ba2bf74c/lib/mix/lib/mix/compilers/test.ex#L61).

I propose to change `--profile-require` to be a boolean flag given that it only supports `time` at present. Alternatively it should default to `time` as per documentation.

### Expected behavior

I would expect `--profile-require` to default to evaluating require time.

**Comment by josevalim** [comment]
It is `time` for consistency with the `--profile time`  option that exists for the compiler. Since we may support other modes in the future, can you please send a PR documenting the "time" option? i.e. no change of behaviour, only docs. Thanks!
