### ISSUE TITLE
Add multi-letter uppercase sigils

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#12447]
See [the discussion in the mailing list](https://groups.google.com/g/elixir-lang-core/c/cocMcghahs4/m/DdYRNfuYAwAJ).

**Comment by whatyouhide** [comment]
Closed in #12448.

**Comment by thiagomajesk** [comment]
Hi @whatyouhide! First of all, excellent work! I was reading the mailing list yesterday and saw an alternate syntax for interpolating multi-letter uppercase sigils which is similar to what Phoenix `~H` uses. However, I can't find it on the new docs.

Did the initial proposal change? It seems the docs describe that values are not interpolated with multi-letter uppercase sigils: https://github.com/elixir-lang/elixir/commit/c0726e88133b0dd16613456a458be5944f3c7cda.

**Comment by whatyouhide** [comment]
The idea with the custom interpolation was that the sigil itself can implement it if they want to. @josevalim just suggested a possible interpolation syntax, but sigils could choose whatever. Does that make sense?

**Comment by thiagomajesk** [comment]
Oh, I see! I didn't get that from the proposal, sorry. I thought that the new sigils would still allow some sort of interpolation. 

So, does it mean that now, if I want to create a custom sigil with any sort of interpolation I'll have to go through the AST and find the values myself between said 'tokens' myself, is that right?

**Comment by whatyouhide** [comment]
@thiagomajesk yes, exactly.
