### ISSUE TITLE
end_of_day/1 should be comparable with inspect

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#12449]
One way to look at it is we should be able to write the assertion under question using just sigils:

```elixir
assert NaiveDateTime.end_of_day(~N[2000-01-01 23:00:07]) == ~N[2000-01-01 23:59:59]
```

and the fact we can't is a reason to revisit this?

_Originally posted by @wojtekmach in https://github.com/elixir-lang/elixir/pull/12443#discussion_r1126143506_

**Comment by josevalim** [comment]
We should probably truncate it based on the precision: `{(10 ** precision) - 1, precision}`

**Comment by thiamsantos** [comment]
That makes sense. I will open a PR.
