### ISSUE TITLE
Incorrect treatment of local variables in quoting

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/elixir#12446]
### Elixir and Erlang/OTP versions

1.14.2

### Operating system

Mac

### Current behavior

Running the following:

```elixir
defmodule TestWrapper do
  def render() do
    quote do
      defmodule Foobar do
        def bar(baz) do
          bar + 1
        end
      end
    end
  end
end

IO.inspect(TestWrapper.render())
```

outputs:

```elixir
{:defmodule, [context: TestWrapper, imports: [{2, Kernel}]],
 [
   {:__aliases__, [alias: false], [:Foobar]},
   [
     do: {:def, [context: TestWrapper, imports: [{1, Kernel}, {2, Kernel}]],
      [
        {:bar, [context: TestWrapper], [{:baz, [], TestWrapper}]},
        [
          do: {:+, [context: TestWrapper, imports: [{1, Kernel}, {2, Kernel}]],
           [{:bar, [], TestWrapper}, 1]}
        ]
      ]}
   ]
 ]}
```

### Expected behavior

I would expect the tuple for the argument of `Foobar.bar/1` to be `{:baz, nil}` as it is a local variable and not meant for expansion. The test output shows it is being quoted as `{:baz, [], TestWrapper}`.

**Comment by josevalim** [comment]
This is expected. Please see the section on variable hygiene in `quote` docs. If this is leading to another problem, then please give more context. :)

**Comment by bcardarella** [comment]
Gotcha, it may make sense to provide some context here.

In Beacon, the LiveView CMS we're building, we've been loading all LV pages from the db and composing a single massive module of LV templates to compile at the application boot time. This has lead to a bad time on Fly has we're now hitting OOM errors when deploying. I've been rewriting this to move away from compiling a String representation of the module to run with `Code. compile_string` over to producing a large module as an AST so I can instead use `Code.compile_quoted`

Our longer-term plan is to split into many modules but we need to launch and I need to free up overhead so if a single module AST approach gets us there for now we'll circle back and work on the many-module approach later.

However, when it comes to using LV's `~H` sigil this LOC is messing with the AST approach: https://github.com/phoenixframework/phoenix_live_view/blob/main/lib/phoenix_component.ex#L744 as `Macro.Env.has_var?/2` expands to: `Map.has_key?/2` and the sigil is looking for `{:assigns, nil}` in the AST.

Reading through the hygiene section its not clear to me how to get `quote/2` to produce the proper AST for the `~H` sigial's check.

**Comment by bcardarella** [comment]
A failing example of what is happening:

```elixir
defmodule TestWrapper do
  def render() do
    quote do
      defmodule Foobar do
        import Phoenix.Component
        def bar(assigns) do
           ~H"""
           """
        end
      end
    end
  end
end

TestWrapper.render()
```

> ** (RuntimeError) ~H requires a variable named "assigns" to exist and be set to a map

**Comment by josevalim** [comment]
I see. per the docs, use `var!(assigns)`. :)

**Comment by bcardarella** [comment]
oh yes that does work, I guess within the `quote` it doesn't matter where `var!` is used. Thanks!
