### ISSUE TITLE
Stream.zip/1 with empty list induces memory spike

### ISSUE THREAD

**Issue by alecostard** [elixir-lang/elixir#12459]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

x86_64 GNU/Linux

### Current behavior

When executed, the line below consumes all memory:

```
 [] |> Stream.zip() |> Enum.to_list()
```

A less nasty way to check is to run the following while monitoring ram/cpu:

```
spawn(fn ->
  :timer.kill_after(3000)
  [] |> Stream.zip() |> Enum.to_list()
  IO.puts("done")
end)
```

### Expected behavior

When "materialized", `Stream.zip([])` should not cause a memory spike and just be the empty list.

```
[] == [] |> Stream.zip() |> Enum.to_list() 
```

**Comment by alecostard** [comment]
Tested on master and the problem is there too. Looking at the `stream.ex`, I believe this happens due to an infinite recursion with `zip_list/4`, since `zip_list([], {:cont, _something}, fun, zip_fun)` calls `zip_list_heads_tails([], [], [])`, which returns `{[], []}`, making `zip_list/4` recurse with `zip_list([], {:cont, _something2}, acc), fun, zip_fun)`. 

A new clause

```
defp zip_list([], {:cont, acc}, _fun, _zip_fun), do: {:done, acc}
```

seems to solve this problems, but I may be missing something.


Since this comes from `zip_list/4`, it also affects `Stream.zip_with/2`

**Comment by whatyouhide** [comment]
@alecostard yep, a PR is welcome!
