### ISSUE TITLE
alias overrriding even with Elixir. prefix

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#12456]
I wanted to see how this alias overwriting work in case of external submodules and I've found something odd
```
defmodule Parent do
        alias OtherParent.Child
        def a1, do: IO.puts "Parent " <> inspect(__ENV__.aliases)
        defmodule Elixir.Child do
          def a2, do: IO.puts "Elixir.Child " <> inspect(__ENV__.aliases)
        end
        def a3, do: IO.puts "Parent " <> inspect(__ENV__.aliases)
end
```
```
iex(3)> Parent.a1
Parent [{Child, OtherParent.Child}]
:ok
iex(4)> Child.a2
Elixir.Child []
:ok
iex(5)> Parent.a3
Parent []
:ok
```
So it removes the alias. This does not happen for nested external submodule e.g. `Elixir.Child.One`

_Originally posted by @lukaszsamson in https://github.com/elixir-lang/elixir/issues/12451#issuecomment-1461393633_

**Comment by sabiwara** [comment]
I think what's happening is:
- `defmodule Elixir.Child` starts expanding an `alias`: https://github.com/elixir-lang/elixir/blob/8a0961c9dcecd8135a8108c20866de515c0951a2/lib/elixir/lib/kernel.ex#L4925 (`{:alias, [defined: Child, context: Parent, line: 4],
 [Child, [as: nil, warn: false]]}`)
- we call [this clause](https://github.com/elixir-lang/elixir/blob/8a0961c9dcecd8135a8108c20866de515c0951a2/lib/elixir/src/elixir_aliases.erl#L13-L14) which cleans the alias
- this is basically what makes this [alias removal test pass](https://github.com/elixir-lang/elixir/blob/8a0961c9dcecd8135a8108c20866de515c0951a2/lib/elixir/test/elixir/kernel/alias_test.exs#L67-L68)

I'm not sure what the right fix is, we need to be able to distinguish between the legit alias removal and the case where it is triggered by a defmodule.

**Comment by lukaszsamson** [comment]
> I would argue that we should not do an alias if the module starts with Elixir., because the point of Elixir. is to bypass aliases altogether. :)

It sounds reasonable.

@josevalim when we are at it let's take a look on another non trivial example. Does this behave correctly? It seems `__MODULE__.Child` expands to `Elixir.Parent.Child` and not `Parent.Child` and does not set an alias `{Parent, Parent.Parent}`.

```
defmodule Parent do
    alias OtherParent.Child
    def a1, do: IO.puts "Parent " <> inspect(__ENV__.aliases)
    defmodule __MODULE__.Child do
      def a2, do: IO.puts "__MODULE__.Child " <> inspect(__ENV__.aliases)
    end
    def a3, do: IO.puts "Parent " <> inspect(__ENV__.aliases)
end
```

```
iex(2)> Parent.a1
Parent [{Child, OtherParent.Child}]
:ok
iex(3)> Parent.Child.a2
__MODULE__.Child [{Child, OtherParent.Child}]
:ok
iex(4)> Parent.a3
Parent [{Child, OtherParent.Child}]
:ok

```

**Comment by josevalim** [comment]
@lukaszsamson it is correct to me, because `__MODULE__.Child` is also fully qualified (IMO).
