### ISSUE TITLE
Mix run losing the first command line argument

### ISSUE THREAD

**Issue by eamonno** [elixir-lang/elixir#12460]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Tested on Windows 11 and Arch Linux

### Current behavior

If you have a mix project that uses `System.argv()` somewhere and launch it with either of the following:

```
mix run a b c
mix run -- a b c
```

When you look at System.argv() you will just get `["b", "c"]` in both cases. It seems the first argument is being silently pruned as some sort of script name but with no error or warning printed. 

### Expected behavior

In the first case `mix run a b c` this may be intended though you would expect some sort of warning about there not being any script named "a" to run. In the second with the specific `--` parameter this almost certainly is a bug.

If you run the either of the following:

```
mix run -e "IO.inspect(System.argv())" a b c
mix run -e "IO.inspect(System.argv())" -- a b c
```

Then System.argv will correctly include all three parameters. It should probably work the same without the `-e` argument.

**Comment by eamonno** [comment]
There seems to be a few other bugs in mix with command line arguments too.

```
mix test
```

Will have "test" in `System.argv()`. Similarly

```
mix test --color
```

Will have both "test" and "--color" in `System.argv()`.

Finally running:

```
mix test -- a b c
```

Will have `System.argv()` as `["test", "a", "b", "c"]`.

All of those strike me as incorrect.

**Comment by ericmj** [comment]
`mix run` is the only task that changes `System.argv/0`. No other tasks changes it so `System.argv/0` will return the arguments Elixir was invoked with.
