### ISSUE TITLE
Mix format not working with plugin

### ISSUE THREAD

**Issue by ivan-srsen** [elixir-lang/elixir#12466]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.13.4 (compiled with Erlang/OTP 25)

### Operating system

MacOS

### Current behavior

I've made my own formatter, which I import as a dependency to my project.
This is the content of a .formatter.exs file.

[
  plugins: [MyFormatter],
  inputs: ["mix.exs", "{lib,test}/**/*.{ex,exs}"]
]

and there are the deps

defp deps do
    [
      Deps.deps1(),
      Deps.my_formatter()
  ]
end

I'm trying to run mix format --check-formatted when running my test pipeline, so I first do mix deps.get and then mix deps.compile my_formatter. After that I run mix format --check-formatted. I got an output:

** (Code.LoadError) could not load /Users/name/org/project/deps/hackney/.formatter.exs
    (elixir 1.13.4) lib/code.ex:1733: Code.find_file/2
    (elixir 1.13.4) lib/code.ex:1122: Code.eval_file/2
    (mix 1.13.4) lib/mix/tasks/format.ex:417: Mix.Tasks.Format.eval_file_with_keyword_list/1
    (mix 1.13.4) lib/mix/tasks/format.ex:242: Mix.Tasks.Format.eval_dot_formatter/1
    (mix 1.13.4) lib/mix/tasks/format.ex:218: Mix.Tasks.Format.formatter_for_file/2
    lib/sourceror.ex:921: Sourceror.locals_without_parens/0
    lib/sourceror.ex:211: Sourceror.to_string/2
    lib/my_formatter.ex:46: my_formatter.format/2

### Expected behavior

I'm not sure why other deps are loaded.

**Comment by josevalim** [comment]
Can you please provide an application that reproduces the error? It seems that may be other factors leading to this failure. Thank you.

**Comment by ivan-srsen** [comment]
If I remove MyFormatter from plugins, everything is fine. Seems like it runs through every deps folder and checks if there is .formatter.exs if there is a plugin defined.

**Comment by josevalim** [comment]
I have an application that uses plugins and, afaik, I cannot see said behaviour. Therefore, if you can provide something that reproduces the error it would help a lot!
