### ISSUE TITLE
Compilation error when a guard fails in stead of pursing execution avoiding leak

### ISSUE THREAD

**Issue by kenaryn** [elixir-lang/elixir#12474]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

Void Linux with kernel 6.18.1_3

### Current behavior

When trying to reproduce the snippet code in the official documentation at https://elixir-lang.org/getting-started/case-cond-and-if.html:

```elixir
case 1 do
  x when hd x -> "Will not match"
  x -> "Got #{1}"
```
works as intended in the interactive REPL (*i.e. iex) but returns a compilation error when running `elixir <file.exs>` from a terminal:
```elixir
warning: the call to hd/1 will fail with ArgumentError
  case3.exs:2

13:42:22.358 [error] beam/beam_load.c(356): Error loading function elixir_compiler_0:'__FILE__'/1: op get_hd: Sd:
  bad tag 1 for destination

13:42:22.358 [error] Loading of  failed: :badfile

** (UndefinedFunctionError) function :elixir_compiler_0.__FILE__/1 is undefined (module :elixir_compiler_0 is not available)
    :elixir_compiler_0.__FILE__({})
    (elixir 1.14.3) lib/code.ex:1260: Code.require_file/2
```

N.B. the same snippet code outright crashes the compiler when running `elixirc` command:
```
== Compilation error in file case3.exs ==
** (UndefinedFunctionError) function :elixir_compiler_0.__FILE__/1 is undefined (module :elixir_compiler_0 is not available)
    :elixir_compiler_0.__FILE__({})
    (elixir 1.14.3) lib/kernel/parallel_compiler.ex:340: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/7
```

### Expected behavior

The terminal shall output the following:
`Got 1`

**Comment by Nicd** [comment]
Observed on macOS 13 with Elixir 1.14.2 and Erlang 25.

**Comment by Arkforest** [comment]
I also got the same error on AV Linux 21.3 with Elixir 1.14.3 and Erlang/OTP 25.

**Comment by josevalim** [comment]
Reported upstream: https://github.com/erlang/otp/issues/7024. Thank you!
