### ISSUE TITLE
Compilation Tracer emits :remote_function for imported function calls

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12478]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

Given this 3 modules
```
defmodule Referenced do
  def referenced_fun do
    :ok
  end

  defmacro referenced_macro(clause, do: expression) do
    quote do
      if(!unquote(clause), do: unquote(expression))
    end
  end

  def uses_fun(_a) do
    referenced_fun()
  end

  def uses_macro(a) do
    referenced_macro a do
      :ok
    end
  end
end
```

```
defmodule Remote do
  require Referenced

  def uses_fun do
    Referenced.referenced_fun()
  end

  def uses_macro(a) do
    Referenced.referenced_macro a do
      :ok
    end
  end
end
```

```
defmodule Imported do
  import Referenced

  def uses_fun do
    referenced_fun()
  end

  def uses_macro(a) do
    referenced_macro a do
      :ok
    end
  end
end
```
and a tracer with
```
def trace({kind, meta, module, name, arity}, %Macro.Env{} = env)
      when kind in [:imported_function, :imported_macro, :remote_function, :remote_macro] do
    if module == Referenced do    
      IO.inspect({kind, name, env.module})
    end
    :ok
  end

  def trace({kind, meta, name, arity}, %Macro.Env{} = env)
      when kind in [:local_function, :local_macro] do
        if env.module == Referenced do    
          IO.inspect({kind, name, env.module})
        end
    :ok
  end
```
I get the following events
```
{:local_function, :referenced_fun, Referenced}
{:local_macro, :referenced_macro, Referenced}
{:imported_function, :referenced_fun, Imported}
{:remote_function, :referenced_fun, Imported}
{:imported_macro, :referenced_macro, Imported}
{:remote_function, :referenced_fun, Remote}
{:remote_macro, :referenced_macro, Remote}
```

### Expected behavior

Basing on the docs for both `:remote_function` and `:imported_function` I wouldn't expect to see
```
{:remote_function, :referenced_fun, Imported}
```

Found during debugging of https://github.com/elixir-lsp/elixir-ls/issues/842. In case of HEEX the `:remote_function` and `:imported_function` event have different meta but I'm going to report a separate issue when I gather more info.

**Comment by josevalim** [comment]
Good find. I can see arguments for both duplication it (if you are interested in only remote calls you can ignore imports) and against (unnecessary events). I will investigate if this behavior has changed since tracers were introduced and, if not, document it accordingly.

**Comment by josevalim** [comment]
Yes, I can confirm this is intentional and constructs like Macro.expand will only call the import trace but not the other, because it expands, but it does not dispatch:

```elixir
defmodule Imported do
  import Referenced
  Macro.expand({:referenced_fun, [], []}, %{__ENV__ | tracers: [Tracer]}) |> IO.inspect
end
```

**Comment by lukaszsamson** [comment]
OK, I'm fine with leaving it as it is and documenting. On to my next question. Is it expected to see meta without line and column info? Or with wrong line/column?
In a freshly generated phoenix app with live view I run
```
def trace({kind, meta, module, name, arity}, %Macro.Env{} = env)
      when kind in [:imported_function, :imported_macro, :remote_function, :remote_macro] do
    if module == ComponentRefWeb.CoreComponents do    
      IO.inspect({kind, name, env.module, meta, env.file <> if(meta[:line], do: ":#{meta[:line]}", else: "")})
    end
    register_call(meta, module, name, arity, env)
  end

  def trace({kind, meta, name, arity}, %Macro.Env{} = env)
      when kind in [:local_function, :local_macro] do
    if env.module == ComponentRefWeb.CoreComponents do    
      IO.inspect({kind, name, env.module, meta, env.file <> if(meta[:line], do: ":#{meta[:line]}", else: "")})
    end
    register_call(meta, env.module, name, arity, env)
  end
```
and there's a lot of bogus events
- no meta on import (it is there on remote call of the same function)
```
{:imported_function, :flash_group, ComponentRefWeb.Layouts, [],
 "/Users/my/component_ref/lib/component_ref_web/components/layouts/app.html.heex"}
 ```
 - wrong column (this line is `    <.flash_group flash={@flash} />` so column 11 is in the middle of `flash_group` call)
 ```
 {:remote_function, :flash_group, ComponentRefWeb.Layouts,
 [line: 40, column: 11],
"/Users/my/component_ref/lib/component_ref_web/components/layouts/app.html.heex:40"}
```
 - wrong line in meta (it's the line of `~H"""`, not the actual function usage)
 ```
 {:local_function, :icon, ComponentRefWeb.CoreComponents,
 [counter: {ComponentRefWeb.CoreComponents, 150}, line: 47],
"/Users/my/component_ref/lib/component_ref_web/components/core_components.ex:47"}
```
- no meta (shouldn't meta point to `use` expression)
```
{:remote_function, :__phoenix_component_verify__,
 ComponentRefWeb.CoreComponents, [],
 "/Users/my/component_ref/lib/component_ref_web/components/core_components.ex"}
 ```
 - no column
 ```
 {:local_function, :hide_modal, ComponentRefWeb.CoreComponents, [line: 75],
"/Users/my/component_ref/lib/component_ref_web/components/core_components.ex:75"}
 ```
 I'm not sure if those are HEEX errors

**Comment by josevalim** [comment]
@lukaszsamson yeah, I have an idea why all of those are happening, none of them are Elixir specific. I think the biggest issues are code generated by the `~H` sigil may point to its call site, especially where it does `Macro.expand`.

I am going to push a commit to LiveView tomorrow with some examples on to handle this and I hope it serves as template to handle further cases. But the thing to keep in mind is that this will _always_ happen with macros, there is no escaping.

**Comment by josevalim** [comment]
Here you go: https://github.com/phoenixframework/phoenix_live_view/commit/b06b9b463545a1ad56e20f3a72f704a15c12e651

Please give it a try. Feel free to send PRs with more tests if something is missing :) Thank you!
