### ISSUE TITLE
Add map function to change key (and maybe value) data type

### ISSUE THREAD

**Issue by kevinam99** [elixir-lang/elixir#12487]
Maps, in Elixir, have the flexibility of having strings or atoms as keys. As such, it could get cumbersome when/if maps are present in a codebase where the keys are of different types and so, it runs into issues.

It would be nice if there were a Map function that would take in a map and convert the keys to the desired type. It can help provide a standard flow within a program without having to account for differing types of keys.

I'm proposing a function that would take in a map and a keyword list `opts` which specifies the required type of keys to be converted to and also whether to extend the type conversion to the values. The default can be `atoms` and `false` respectively.

I have a basic flow in mind and I could work on this if this seems like a good idea.

eg:
```elixir
map =  %{
  "id" => 1,
  "price" => 500.00,
  "status" => "pending",
  "nested_map" => %{
    "key1" => %{"key" => "value", "count" => 10},
    "id" => "alphanumer1c_id",
  },
  "inserted_at" => DateTime.utc_now()
}

# proposed function
Map.convert_keys(map, keys: :atoms, convert_values: true)

# output
# %{
#   id: 1,
#   inserted_at: ~U[2023-03-23 03:58:03.444817Z],
#   nested_map: %{id: :alphanumer1c_id, key1: %{count: 10, key: :value}},
#   price: 500.0,
#   status: :pending
# }
```

Sure, we can use
```elixir
map |> Jason.encode!() |> Jason.decode!(keys: :atoms)
```
but this will add a new dep.

**Comment by josevalim** [comment]
Hi @kevinam99, please send feature proposals to the mailing list, but it is unlikely this will make to core at the moment, as conversion to atoms needs to be done carefully.
