### ISSUE TITLE
Incompatible Type warning for compatible types (is_number, is_integer, is_float)

### ISSUE THREAD

**Issue by novaugust** [elixir-lang/elixir#12505]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Elixir 1.14.2 (compiled with Erlang/OTP 25)

### Operating system

macos

### Current behavior

Compiling this snippet raises a type warning:

```ex
defmodule Foo do
  def bar(token, number) when is_number(number) do
    case token do
      token when is_float(number) -> token
      token when is_integer(number) -> token
    end
  end
end
```

<details><summary> warning: incompatible types integer() !~ float()</summary>
warning: incompatible types:

    integer() !~ float()

in expression:

    # test.exs:4
    is_float(number)

where "number" was given the type integer() | float() in:

    # test.exs:2
    is_number(number)

where "number" was given the type float() in:

    # test.exs:4
    is_float(number)

Conflict found at
  test.exs:4: Foo.bar/1
</details>

### Expected behavior

notably this code correctly doesn't warn, which is the expected behaviour for the block above as well
```ex
defmodule Foo do
  def bar(number) when is_number(number) do
    case number do
      number when is_float(number) -> :float
      number when is_integer(number) -> :integer
    end
  end
end
```

**Comment by josevalim** [comment]
Moved to #10485.
