### ISSUE TITLE
validate_compile_env causes applications to be loaded in release 'eval'

### ISSUE THREAD

**Issue by mwhitworth** [elixir-lang/elixir#12516]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 23)

### Operating system

MacOS

### Current behavior

We have a use case where we would like to control all the loading and booting of all applications in the project.

Running code in this context can be achieved with `mix eval` - running `Application.loaded_applications() |> IO.inspect()` in a `mix` context produces the expected list (`kernel`, `stdlib`, ...)

Placing compile-time environment for any application into `config/config.exs` and compiling using `mix release` causes these applications to be loaded when `validate_compile_env` is `true` (the default), verified using `Applications.loaded_applications() |> IO.inspect()`

This behaviour means that the application is already loaded in this context, which is inconsistent with `mix eval`

### Expected behavior

Either:
- this behaviour around `validate_compile_env` is more clearly documented, given it is hard to add diagnostics during Erlang/Elixir boot
- `Config.Provider` is not booted during the "start clean" boot
(or perhaps both)

**Comment by josevalim** [comment]
I would say it is fine to load the applications but they should not be started. We need to address the documentation at the relevant places.
