### ISSUE TITLE
elixir command returns incorrect exit status

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12513]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.14.4 (compiled with Erlang/OTP 25)

### Operating system

macOS, windows

### Current behavior

When `System.stop` is called from an `.exs` script or ad hoc eval it always return 0 exit code

on macOS
```
elixir -e "System.stop(1)"
echo $?
0
```

on windows
```
elixir -e "System.stop(1)"
echo %ERRORLEVEL%
0
```
It works correctly for `System.halt`

macOS
```
elixir -e "System.halt(1)"
echo $?
1
```
windows
```
elixir -e "System.halt(1)"
echo %ERRORLEVEL%
1
```

erlang also works correctly
```
erl -eval "init:stop(1)."
echo $?
1
```
iex is not affected by this bug
```
iex
Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Interactive Elixir (1.14.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> System.stop(1)
:ok
iex(2)> %                                                                                                                                                                                                       echo $?        
1
```

### Expected behavior

Correct exit code should be returned

**Comment by josevalim** [comment]
System.stop is asynchronous, so you have an inherent race. This is clearly documented on main (maybe earlier) but it has been a source of pitfalls nonetheless.

So I have tried changing this behaviour to be sync and it turns out that doing so breaks System.stop from within a RPC, as you want to shut down the RPC before the system stops. Therefore we have to keep the current behaviour.

**Comment by lukaszsamson** [comment]
> System.stop is asynchronous, so you have an inherent race. This is clearly documented on main (maybe earlier)

1.14.4 does not mention async behavior. Not everyone reads main docs

> it has been a source of pitfalls nonetheless.

Yes, e.g.
https://elixirforum.com/t/system-stop-1-does-not-return-code-to-shell/17542

> Therefore we have to keep the current behaviour

OK but I'd suggest expanding the docs and explicitly stating that in case the program terminates before `:erlang.halt` is called by `:init.stop` a different exit code may be returned

**Comment by ericmj** [comment]
You can find the `main` docs here https://hexdocs.pm/elixir/main/System.html#stop/1.

Can you open a PR with your suggested changes to the docs?
