### ISSUE TITLE
running elixir code is failing on windows 

### ISSUE THREAD

**Issue by burnstreet** [elixir-lang/elixir#12521]
I ran the elixir web installer on windows 10 X64, installing Erlang OTP25 with it, and tried to run a sample

C:\Daten\Code\elixir\servy>elixir --version 
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 25)

I then ran 
> mix new servy

changin servy.ex to

`defmodule Servy do
  def hello(name) do
    "Hello #{name}"
  end
end

Io.puts Servy.hello("Elixir")`

running ` elixir .\lib\servy.ex > servy.log`
I get
** (UndefinedFunctionError) function Io.puts/1 is undefined (module Io is not available)
    Io.puts("Hello Elixir")
    (elixir 1.14.4) lib/code.ex:1260: Code.require_file/2
[servy.log](https://github.com/elixir-lang/elixir/files/11204159/servy.log)

the file Elixir.Io.beam exists in the location the log is searching for it

**Comment by wojtekmach** [comment]
change `Io.puts` to `IO.puts` and you'll be ready to go!
