### ISSUE TITLE
build_embedded option seems to be deprecated

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12542]
### Elixir and Erlang/OTP versions

main@5d807c7a7fd7c589a0e02625391c1b0dbe1c64d5

### Operating system

*

### Current behavior

Since https://github.com/elixir-lang/elixir/commit/c65231e09612fcab7369052b5a10ae6679476b99 `build_embedded` mixfile option does not have any effect and is no longer documented. There are still mentions in the code and tests (e.g. test `gets and compiles dependencies with build_embedded` or remark
```
# This is used to test that the built-in ebin is ignored
# when build_embedded is true.
```
in test_helper.exs

### Expected behavior

If it's deprecated it should be mentioned in the changelog. The relevant references should be removed from code and tests.

**Comment by josevalim** [comment]
It is not really deprecated rather it is no longer need to solve the problems it originally did. I don't want to deprecate it because we may use it in the future but we should probably add a note to the docs anyway.
