### ISSUE TITLE
ExUnit module tags not passed to setup_all

### ISSUE THREAD

**Issue by dvic** [elixir-lang/elixir#12544]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.1.4] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

When I use `@moduletag` the `setup_all` callback does not receive it.

```elixir
defmodule FooBar do
  use ExUnit.Case
  @moduletag :something

  setup_all tags do
    dbg(tags) # tags #=> %{case: FooBar, module: FooBar}
    :ok
  end
end
```

### Expected behavior

The `setup_all` callback should receive the module tag. Is this intended behaviour or a bug? In case of the former I can add some docs about it to https://hexdocs.pm/ex_unit/1.14.4/ExUnit.Case.html#module-tags 

```elixir
defmodule FooBar do
  use ExUnit.Case
  @moduletag :something

  setup_all tags do
    dbg(tags) # tags #=> %{..., something: true}
    :ok
  end
end
```

**Comment by josevalim** [comment]
I believe a PR to pass those tags will be welcome. :) We likely merge them in, we are probably just doing it too late.

**Comment by whatyouhide** [comment]
Mh, this is an interesting issue. I don't think it's either intended behavior or bug, I think it's just something we didn't notice before. I think we should pass them in yes, so a PR would be great! 💟
