### ISSUE TITLE
Support DateTime/NaiveDateTime.utc_now(time_unit_or_precision)

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#12557]
### Elixir and Erlang/OTP versions

All.

### Operating system

All.

### Current behavior

Current API: `DateTime/NaiveDateTime.utc_now(calendar)`

### Expected behavior

New API: `DateTime/NaiveDateTime.utc_now(calendar_or_timeunit \\ Calendar.ISO)` and `DateTime/NaiveDateTime.utc_now(time_unit, calendar)`. The goal of supporting precision is to avoid doing `NaiveDateTime.utc_now() |> NaiveDateTime.truncate(:second)`.

**Comment by viniciusmuller** [comment]
Hey @josevalim, I would like to implement this, can I self-assign it?

**Comment by josevalim** [comment]
Unfortunately we can’t officially assign a non-committer but consider it yours. :)
