### ISSUE TITLE
Implementing a protocol hits system path length limit

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12552]
### Elixir and Erlang/OTP versions

any

### Operating system

any with short path

### Current behavior

When building a project with long alias module the compiler generates protocol implementation modules that are too long for the current filesystem limit.
This is an example from elixirLS - module `ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent` is able to build by itself, but `JasonVendored.Encoder` implementation hits the limit
```
[error] [label: {:erl_prim_loader, :file_error}, report: 'File operation error: enametoolong. Target: /home/jason/.asdf/installs/erlang/24.3.4.9/lib/asn1-5.0.18.1/ebin/Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent1.beam. Function: get_file. Process: code_server.']

** (File.Error) could not write to file "/home/jason/elixir-ls/_build/shared/lib/language_server/ebin/Elixir.JasonVendored.Encoder.ElixirLS.LanguageServer.Experimental.Protocol.Types.TextDocument.ContentChangeEvent.TextDocumentContentChangeEvent.beam": file name too long
    (elixir 1.12.3) lib/file.ex:1054: File.write!/3
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:209: anonymous fn/3 in Kernel.ParallelCompiler.write_module_binaries/3
    (elixir 1.12.3) lib/enum.ex:1206: anonymous fn/3 in Enum.flat_map/2
    (stdlib 3.17.2.2) maps.erl:410: :maps.fold_1/3
    (elixir 1.12.3) lib/enum.ex:2397: Enum.flat_map/2
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:182: Kernel.ParallelCompiler.spawn_workers/3
    (mix 1.12.3) lib/mix/compilers/elixir.ex:89: Mix.Compilers.Elixir.compile/6
    (mix 1.12.3) lib/mix/task.ex:394: anonymous fn/3 in Mix.Task.run_task/3
```
Originally reported in https://github.com/elixir-lsp/elixir-ls/issues/832

### Expected behavior

Not sure. Maybe the compiler should generate shorter file names but I have no idea how would it play with beam code loader. Other options are:
- emitting a warning earlier when module name length is big or alias nesting too deep
- nicer compilation error
- leaving it be and adding some warning in the docs

**Comment by josevalim** [comment]
We can try to do a better error message but that's it. You would have to work on shorter module names.

**Comment by josevalim** [comment]
So I have further looked into this and I don't think it is something we can address, unfortunately. We don't know what is the filesystem message and it comes deep from within Erlang. I have read that the path name can be quite long in most OSes (4k) and a single segment name is typically 255, which are both quite distant here. So it seems to be a specific OS with quite short path name. My suggestion is to try to make the module names shorter anyway.

I will keep an eye if this continues to happen in the future and think of ways it can improve, but it seems to be quite uncommon given the above. :)
