### ISSUE TITLE
Consider mix aliases in umbrella projects

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/elixir#12572]
When in an umbrella project, a mix task can be run from the root. If the task exists in an app within the umbrella, it is run, otherwise, it is skipped for that app with a message. However, aliases are not treated in the same way, aliases will simply show an error that the mix task was not found.

We could look into the aliases of the apps and if one exists, allow the mix task to be run.

Related to: https://github.com/phoenixframework/phoenix/issues/5461

**Comment by josevalim** [comment]
Sounds good to me! PR welcome!

**Comment by ericmj** [comment]
For module mix tasks there will be a compilation warning if there are conflicting names. Will we add a warning or error when there are conflicting alias names in the umbrella child apps?
