### ISSUE TITLE
Both 1.14.5 and 1.15.0-rc0 with OTP-26 compilation hang on Windows

### ISSUE THREAD

**Issue by edwardzhou** [elixir-lang/elixir#12589]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.5 (compiled with Erlang/OTP 25)

Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.0-rc.0 (3cdb388) (compiled with Erlang/OTP 26)

### Operating system

Windows 10 64bit

### Current behavior

C:\work\dms_nerves\dms_ui>iex -S mix
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

==> uniq
Compiling 4 files (.ex)
Generated uniq app
==> logger_file_backend
Compiling 1 file (.ex)
Generated logger_file_backend app
==> file_system
Compiling 7 files (.ex)
Generated file_system app
==> combine
Compiling 6 files (.ex)
Generated combine app
==> mime
Compiling 1 file (.ex)
Generated mime app

^^^^^^ hang on here.

### Expected behavior

should able to compile all libraries and enter iex

**Comment by josevalim** [comment]
Can you provide a mix.exs that reproduces the issue? It can be just your listing of `def deps`. Thanks!

**Comment by wojtekmach** [comment]
If you can reproduce this with an `Mix.install(...)`, even better.

**Comment by edwardzhou** [comment]
> Can you provide a mix.exs that reproduces the issue? It can be just your listing of `def deps`. Thanks!

dms_ui deps:
```elixir
  defp deps do
    [
      {:phoenix, "~> 1.7.2"},
      {:phoenix_html, "~> 3.3"},
      {:phoenix_live_reload, "~> 1.2", only: :dev},
      {:phoenix_live_view, "~> 0.18.16"},
      {:floki, ">= 0.30.0", only: :test},
      {:phoenix_live_dashboard, "~> 0.7.2"},
      {:esbuild, "~> 0.7", runtime: Mix.env() == :dev},
      {:tailwind, "~> 0.2.0", runtime: Mix.env() == :dev},
      {:telemetry_metrics, "~> 0.6"},
      {:telemetry_poller, "~> 1.0"},
      {:gettext, "~> 0.20"},
      {:jason, "~> 1.2"},
      {:plug_cowboy, "~> 2.5"},
      {:dms_engine, path: "../dms_engine", env: Mix.env()}
    ]
  end
```

dms_engine's deps
```elixir
  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:circuits_gpio, "~> 1.0"},
      # {:circuits_i2c, "~> 1.1"}, #, targets: @all_targets},
      # {:circuits_uart, "~> 1.5.1"}, #, targets: @all_targets},
      # {:circuits_spi, "~> 1.3"}, # targets: @all_targets},
      {:jason, "~> 1.2"},
      {:uniq, "~> 0.1"},
      {:nanoid, "~> 2.0.5"},
      {:net_address, "~> 0.3"},
      {:mac_address, "~> 0.0.0"},
      {:logger_file_backend, "~> 0.0.13"},
      {:timex, "~> 3.7"}
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
    ]
  end
```

**Comment by edwardzhou** [comment]
> If you can reproduce this with an `Mix.install(...)`, even better.

it is weird that Mix.install works in iex.

```elixir

C:\work\dms_nerves\dms_ui>iex
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.install [{:mime, "~> 2.0.3"}]
Resolving Hex dependencies...
Resolution completed in 0.019s
New:
  mime 2.0.3
* Getting mime (Hex package)
==> mime
Compiling 1 file (.ex)
Generated mime app
:ok
iex(2)>
```

but hangs everytime `mix compile` or `iex -S mix`. even after deleted _build by 'rm -rf _build'.

**Comment by edwardzhou** [comment]
I reproduced the same easily with clean Windows 11.

step1. download and install OTP26
https://github.com/erlang/otp/releases/download/OTP-26.0/otp_win64_26.0.exe

step2. download and extract elixir-1.15.0-rc0 from
https://github.com/elixir-lang/elixir/releases/download/v1.15.0-rc.0/elixir-otp-26.zip

step3. enter command-line

```cmd
set set PATH="c:\Program Files\Erlang OTP\bin";c:\work\elixir-otp-26\bin;%PATH%
C:\temp>elixir -v
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.0-rc.0 (3cdb388) (compiled with Erlang/OTP 26)

# install phoenix creator 1.7.2
mix archive.install hex phx_new

mix phx.new demo

cd demo
mix deps.get
mix compile

~~~~~~ hang ~~~~~~

```

**Comment by josevalim** [comment]
This is an issue with Erlang/OTP 26 manifested through Rebar3: https://github.com/erlang/otp/issues/7261

A temporary fix for Rebar3 has been sent here: https://github.com/erlang/rebar3/pull/2794

It is not an Elixir issue, but I will keep this open for guidance. Thanks for the reports!

**Comment by josevalim** [comment]
There is a new Rebar3 out and `mix local.rebar` should install it by default from now on!
