### ISSUE TITLE
Code diagnostic file is expanded

### ISSUE THREAD

**Issue by jonatanklosko** [elixir-lang/elixir#12585]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.0-rc.0 (3cdb388) (compiled with Erlang/OTP 26)

### Operating system

macOS 13.3.1 22E261 arm64

### Current behavior

```elixir
iex(1)> Code.with_diagnostics(fn ->
...(1)>   try do
...(1)>     Code.eval_string("x", [])
...(1)>   rescue
...(1)>     e -> e
...(1)>   end
...(1)> end)
{%CompileError{
   file: "nofile",
   line: 0,
   description: "cannot compile file (errors have been logged)"
 },
 [
   %{
     message: "undefined variable \"x\"",
     position: 1,
     file: "/Users/jonatanklosko/nofile",
     stacktrace: [],
     severity: :error
   }
 ]}
```

### Expected behavior

The diagnostic file should be `"nofile"`.

**Comment by josevalim** [comment]
Closing in favor of the PR.
