### ISSUE TITLE
Function clause binary match error on OTP 26

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#12587]
### Elixir and Erlang/OTP versions

Elixir 1.14.4 and OTP 25.3.2 - working correctly
Elixir 1.14.4 and OTP 26.0 - appears to have a regression in binary pattern matches in function heads

I suspect this is an OTP 26 issue. I am opening the issue here for verification and to receive guidance before opening an issue on OTP.

### Operating system

MacOS 12.3

### To reproduce

A full test case is in the repo https://github.com/kipcole9/match_test To run it:
```bash
# Assumes asdf is installed with erlang and elixir plugins
# Will install Elixir 1.14.4-OTP-25 and 1.14.4-OTP-26
# Will install Erlang 25.3.2 and 26.0
git clone https://github.com/kipcole9/match_test
cd match_test
./run.sh
```

### Issue description
The test case generates function clauses as follows:
```elixir
  for unit <- @units do
    def match_test_1(<<unquote(unit), rest::binary>> = full_unit) do
      # Do something
    end
  end
```
Where `@units` is a list of strings in descending order of string length. Therefore each function clause will perform a "longest match" of a given string argument. Then the test takes each of the strings, in the same order, and calls the match function. Each function invocation should match exactly to the function clause with the same string in the match part of the function head.

In OTP 25 and earlier this executes correctly.
In OTP 26 there are several incorrect matches where a longer and correct match does not happen, but a shorter match does where the shorter match is a prefix of the longer match. For example the test result:
```elixir
FAILURE Found only partial match for dessert_spoon_imperial. Found "dessert_spoon". Rest = "_imperial"
```
means that when invoked as `match_test_1("dessert_spoon_imperial")` it matches incorrectly on `dessert_spoon`.

### Additional symptoms

* The match failures happen only on binary pattern matches of the form `<<"string_constant", rest::binary>>` when `rest == ""`.
* The match failures appear to happen based upon the list length and therefore number of clauses generated. I cannot find a definitive rule for this.

### Expected behavior

Behaviour on OTP 25 and OTP 26 should be the same.

**Comment by josevalim** [comment]
Reported here: https://github.com/erlang/otp/issues/7259 :)
