### ISSUE TITLE
internal error in pass beam_ssa_opt: exception error: undefined function beam_bounds:'+'/2

### ISSUE THREAD

**Issue by dch** [elixir-lang/elixir#12592]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns] [dtrace] [sharing-preserving]

Elixir 1.15.0-rc.0 (compiled with Erlang/OTP 24)
```

- I'm mindful this might be an OTP26 issue, as there are a number of optimisation bugs
reported & fixed upstream in OTP, but let's start off here as this doesn't occur in OTP26 + Elixir 1.14.5.

- also tested with OTP26 + Elixir main @ 5480491dc54259c90a4b63caaa871491d00d3b14 and same result.

### Operating system

FreeBSD 14.0-CURRENT amd64

### Current behavior

- install 1.15-rc.0 + OTP26
- git clone https://github.com/elixir-plug/mime
- `cd mime && mix do deps.get --all, deps.compile, compile`

```
mix do deps.get --all, deps.compile, compile
Resolving Hex dependencies...
Resolution completed in 0.053s
Unchanged:
  earmark_parser 1.4.26
  ex_doc 0.28.4
  makeup 1.1.0
  makeup_elixir 0.16.0
  makeup_erlang 0.1.1
  nimble_parsec 1.2.3
* Getting ex_doc (Hex package)
* Getting earmark_parser (Hex package)
* Getting makeup_elixir (Hex package)
* Getting makeup_erlang (Hex package)
* Getting makeup (Hex package)
* Getting nimble_parsec (Hex package)
Compiling 1 file (.ex)
Sub pass ssa_opt_ranges
Function: downcase/2

== Compilation error in file lib/mime.ex ==
** (CompileError) lib/mime.ex: internal error in pass beam_ssa_opt:
exception error: undefined function beam_bounds:'+'/2
  in function  beam_call_types:arith_type/2 (beam_call_types.erl, line 895)
  in call from beam_ssa_type:ranges_propagate_types/2 (beam_ssa_type.erl, line 861)
  in call from beam_ssa_type:ranges_is/3 (beam_ssa_type.erl, line 837)
  in call from beam_ssa_type:ranges/3 (beam_ssa_type.erl, line 824)
  in call from beam_ssa_opt:ssa_opt_ranges/1 (beam_ssa_opt.erl, line 448)
  in call from compile:run_sub_passes_1/3 (compile.erl, line 419)
  in call from beam_ssa_opt:phase/4 (beam_ssa_opt.erl, line 114)
    (stdlib 5.0) lists.erl:1686: :lists.foreach_1/2
```

### Expected behavior

compile ok, all the beautiful tests are green, and the world is good :rainbow: :green_heart: :globe_with_meridians:

**Comment by josevalim** [comment]
Thanks @dch! Could this be a FreeBSD issue? Because I cannot reproduce this. :(

**Comment by josevalim** [comment]
Oh, I see you are using an Elixir compiled for Erlang/OTP 24. We now provide builds per OTP version, which should avoid similar issues and provide better performance. Can you try using that instead? How did you install Elixir?

**Comment by dch** [comment]
I will re-try this against maint later this week, https://github.com/erlang/otp/issues?q=ssa has seen some very recent fixes.

Is there a way to get the .S files (or .erl files) that Elixir is producing, that are failing the optimisation pass? this would be easier for the OTP team to look at.

**Comment by josevalim** [comment]
Ideally you always want to run Elixir compiled against latest Erlang/OTP.

> Is there a way to get the .S files (or .erl files) that Elixir is producing, that are failing the optimisation pass? this would be easier for the OTP team to look at.

Why I try to do is to remove code from the Elixir file until I have a minimal file that reproduces the issue. Then you can use something like https://github.com/michalmuskala/decompile to convert that to Erlang. I can help with this step too!

**Comment by wojtekmach** [comment]
> Then you can use something like https://github.com/michalmuskala/decompile to convert that to Erlang

shameless plug: https://github.com/wojtekmach/mix_install_examples/blob/main/decompilerl.exs

**Comment by josevalim** [comment]
Closing this for now as it is not an Elixir issue, I will be very glad to continue the convo though :)

**Comment by dch** [comment]
<3 these decompiler helpers! & thanks for the tips.

- The error is replicated with the official pre-built asset https://github.com/elixir-lang/elixir/releases/download/v1.15.0-rc.0/elixir-otp-26.zip as well
- the equivalent AFAICT erlang code compiles without issue
-

**Comment by dch** [comment]
yes it still does.

On a fresh asdf OTP26 + elirix 1.15.0-rc.0 on MacOS, it builds & runs fine,
so I can take that Elixir.Wat.beam and decompiling it:

```erl
%% blah blah
lower(<<_h@1/integer, _t@1/binary>>)
    when erlang:is_integer(_h@1) andalso
             _h@1 >= 65 andalso _h@1 =< 90 ->
    <<(_h@1 + 32):8/binary, _t@1/binary>>.
```

Which runs just fine on FreeBSD here. dropping that into wat.erl.

**Comment by dch** [comment]
I notice that on FreeBSD, OTP is built with `sharing-preserving` as well.

**Comment by dch** [comment]
And indeed, disabling `sharing-preserving` in the build fixes this. I still can't replicate this bug in native erlang but I will raise this with OTP team.

**Comment by dch** [comment]
this was caused by ERL_LIBS being set, which pulled in older OTP24 beam files, thus breaking everything. Switching off `sharing-preserving` caused these to be removed, when the package was installed. erlang compiler doesnt need these and thus succeeds.
