### ISSUE TITLE
Incorrect results of IO.getn in Elixir 1.14.4 (compiled with Erlang/OTP 26)

### ISSUE THREAD

**Issue by masahiro-999** [elixir-lang/elixir#12594]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 26)

it is installed with asdf.

### Operating system

Ubuntu 22.04.2 LTS on WSL2

### Current behavior

I am using Elixir 1.14.4, which is compiled with Erlang/OTP 26. When I run the following code:

main.ex
```
defmodule Main do
  def main() do
    IO.getn(:stdio, "", 1) |> IO.inspect()
    IO.getn(:stdio, "", 1) |> IO.inspect()
  end

end
```
I get the following output:
```
$ elixirc main.ex
$ echo "x"| elixir -e 'Main.main()'
"x"
{:error, :collect_chars}
```

### Expected behavior

result with Elixir 1.14.4 (compiled with Erlang/OTP 25)
```
$ echo "x"| elixir -e 'Main.main()'
"x"
"\n"
$
```

**Comment by josevalim** [comment]
Reported here: https://github.com/erlang/otp/issues/7286 Thank you!
