### ISSUE TITLE
nowarn_function on macro causes mix test --cover to fail

### ISSUE THREAD

**Issue by lud-wj** [elixir-lang/elixir#12597]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 25)

### Operating system

Ubuntu

### Current behavior

This codes makes the `--cover` flag to fail when running `mix test`

```elixir
defmodule Demo do
  @compile_env Mix.env()

  @dialyzer {:nowarn_function, debug: 1}

  defmacro debug(body) do
    if @compile_env == :prod do
      quote do
        unquote(body)
      end
    else
      code = Macro.to_string(body)

      quote do
        value = unquote(body)

        IO.puts("""
        Code
        #{unquote(code)}

        Result
        #{inspect(value)}
        """)

        value
      end
    end
  end

  def hello do
    debug(String.to_atom("world"))
  end
end
```

```
mix test --cover                        
Compiling 1 file (.ex)
Cover compiling modules ...
** (exit) an exception was raised:
    ** (MatchError) no match of right hand side value: :error
        src/cover.erl:1782: :cover.do_compile_beam2/6
        src/cover.erl:1672: :cover.do_compile_beam/3
        (stdlib 4.0) lists.erl:1315: :lists.map/2
        src/cover.erl:3150: anonymous fn/2 in :cover.pmap_spawn/4
    src/cover.erl:777: :cover.call/1
    (mix 1.14.4) lib/mix/tasks/test.coverage.ex:217: anonymous fn/2 in Mix.Tasks.Test.Coverage.cover_compile/1
    (elixir 1.14.4) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.14.4) lib/mix/tasks/test.coverage.ex:216: Mix.Tasks.Test.Coverage.cover_compile/1
    (mix 1.14.4) lib/mix/tasks/test.coverage.ex:197: Mix.Tasks.Test.Coverage.start/2
    (mix 1.14.4) lib/mix/tasks/test.ex:511: Mix.Tasks.Test.do_run/3
    (mix 1.14.4) lib/mix/task.ex:421: anonymous fn/3 in Mix.Task.run_task/4
    (mix 1.14.4) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

### Expected behavior

`@dialyzer {:nowarn_function, debug: 1}` removes the warning `The test :test == :prod can never evaluate to 'true'`.

I know `Mix.env()` can be used directly in the macro and that would remove the dialyzer warning. But there is still a compilation error with cover here.

I am not sure that it is a bug because there is no `debug/1` function. But `:nowarn_function` does not accept `"MACRO-debug": 2`.

Maybe the fact that `debug: 1` successfully removes the warning is just a quirk of ElixirLS…

**Comment by josevalim** [comment]
You can't actually tell Dialyzer to silence a macro. You can move the logic to a private function and tell it to silence it instead. I will improve the error message. :)

**Comment by lud-wj** [comment]
Cool thanks!
