### ISSUE TITLE
Hex docs for Elixir is offline

### ISSUE THREAD

**Issue by guisehn** [elixir-lang/elixir#12617]
I'm not sure if this is the correct place to report, but the Hex docs for all versions of Elixir ([except the latest one, v1.15.0-rc.1](https://hexdocs.pm/elixir/Kernel.html)) are offline:

Example: https://hexdocs.pm/elixir/1.12/Supervisor.html

<img width="723" alt="Screen Shot 2023-05-29 at 8 43 28 PM" src="https://github.com/elixir-lang/elixir/assets/830208/50b9a1d0-95f7-4421-88e7-c39d1412c836">

**Comment by ericmj** [comment]
We are not supposed to publish docs for other branches than `main`. You need to type out the full version name such as https://hexdocs.pm/elixir/1.12.0/Supervisor.html

**Comment by guisehn** [comment]
@ericmj The URL https://hexdocs.pm/elixir/1.12/Supervisor.html is the first result for `elixir supervisor` on Google, and lots of other search queries like `enum elixir`, `kernel elixir` are leading to breaking pages.

Should we consider keeping those URLs functional? Also, the version dropdown seems to be broken as it doesn't allow navigating to past and future versions except for the current one.

<img width="219" alt="Screen Shot 2023-05-30 at 00 04 27" src="https://github.com/elixir-lang/elixir/assets/830208/e135e8b0-6a9f-45fe-95d1-12744f33c0d7">

**Comment by ericmj** [comment]
The drop-down is a known issue that we have possible fix for, it should be fixed after the next Elixir version.

The MAJOR.MINOR docs we're never intended to be supported. They are not in the sitemaps so I am not sure why they were indexed, but they should be dropped from indexes soon as they return 404.

We switched they we upload elixir docs to hexdocs to be based on GitHub actions and that broke the old unsupported versions and there isn't really a way we can revert back.

**Comment by guisehn** [comment]
The issue started happening again with 1.12.

- https://hexdocs.pm/elixir/1.12/Process.html is offline
- https://hexdocs.pm/elixir/1.12/Kernel.html is not loading any assets

Both pages are the first result on Google for `process elixir` and `kernel elixir`
