### ISSUE TITLE
mix local.rebar --force gives an error related to checksum

### ISSUE THREAD

**Issue by pedrofurtado** [elixir-lang/elixir#12624]
### Elixir and Erlang/OTP versions

elixir -v
Erlang/OTP 21 [erts-10.3.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.7.4 (compiled with Erlang/OTP 20)

### Operating system

Debian 9

### Current behavior

HEX_MIRROR=https://cdn.jsdelivr.net/hex mix local.rebar --force
* creating root/.mix/rebar
** (Mix) Could not install Rebar because Mix could not verify authenticity of metadata file at "https://cdn.jsdelivr.net/hex/installs/rebar3-1.x.csv". This may happen because a proxy or some entity is interfering with the download or because you don't have a public key to verify the download.

You may try again later or check if a new public key has been released in our public keys page: https://repo.hex.pm/installs/public_keys.html

### Expected behavior

The command worked well. I see that has a difference between theses two files, when I download it via browser:

https://repo.hex.pm/installs/rebar3-1.x.csv
Content:
3.13.3,e9d2f4b857004524883ae5812dec43210374324f1203d40d8fe43d99c9e913e509f3a72c2097d5dc052ccafd5a5578b931695d4cc02b35e93890db69457297d2,1.0.0
3.15.2,b5ed03cb3d293beb655421498466f2abc082bb41fb1962456654da38f6877d3990994583e90f108997360977a07b771cc5679df9f0a7aab531056395646d4540,1.11.4
3.15.2,718c9a7014f9c2040fe98d9881c2d2011e56d56904aa66758f37f3d639a810a86a5f164bc63412e304099731a20700a33290debe605eefd1f2f1dd831074b581,1.13.0
3.22.0,7a4905d0dc3328999d314620e3f1ea9aff554e61efe19e53756117aa0225702a88a236effb92bd94916c1e14953b4273bb2595523725c4e08260dd3150beb4dc,1.14.5
3.22.0,7e000ef1ba7f827e6dbae120aa3a19cf25d277d00fc280a142ff19e9b11f378423122cba475a2b6735ffbf80d011e9b5dbccb720afb0dc07c5ad5cd5d20cdb8b,1.15.0-rc.0

https://cdn.jsdelivr.net/hex/installs/rebar3-1.x.csv
Content:
3.13.3,30cbfeacddf5219f9a9b228abf3ce2d5f3207907927f15b0311e925f6976c82a8ce7b7ff7ecb62c2283664a82d03da4634d7644767f93493b79616a737cdff30,1.0.0
3.15.2,f5647fe03d3f204469ed613de3e194dd87a47edf16d882f964af49b480cfe3e7b060c76c5b5aae090477e488ecb42e0c4364bb5871479f688da331164bd39b78,1.11.4
3.15.2,c0ab87f1345d5e6ce480fe06ec10801c3f3f7fd3642ec1dbbecd43498a9aac9c29f9eb23a01564ce00df6c5a272b5ac9635e884b470f6f3944c94ae85e202b1e,1.13.0
3.22.0,a975373366edc08e2213bf3c9df71e0ac06409505c91efd10f2e42397ecc8a7ee38cbd442fee03c6db06cb3c875cf60015b36aae07d839de1692b01e9f76138d,1.14.5
3.22.0,3343941099bf8b83980cb2ec2280fa63dee8e7200b0da47c4325f0a48a739ab6f5402b0e5e3dbf7ff2112e14c9644ad68eb604179f895dba6346b02b15fa2185,1.15.0-rc.0

Appears that are a mismatch between content in the two files, that in theory should be the same (I think).

Possible related issues: https://github.com/elixir-lang/elixir/issues/12615
Possible related links: https://elixirforum.com/t/error-installing-rebar3/56160/8 | https://stackoverflow.com/a/76358319

**Comment by wojtekmach** [comment]
We had about 2h outage window on May 29th where the .csv was not properly signed and perhaps jsdeliver cached a version of the file during that time.

**Comment by pedrofurtado** [comment]
@josevalim Is there some manual action that we need to do? Or JsDelivr will refresh cache at their time? 👍

**Comment by josevalim** [comment]
We don't know. We are not responsible for it. You have to ask them.
