### ISSUE TITLE
Inconsistent behaviour for bitstring segments with string values and utf type modifiers

### ISSUE THREAD

**Issue by bartblast** [elixir-lang/elixir#12634]
### Elixir and Erlang/OTP versions

elixir: 1.14.5-otp-26
erlang/otp: 26.0

### Operating system

macOS Ventura 13.4

### Current behavior

It is possible to use string literals in bitstring segments with utf8, utf16, and utf32 type modifiers, but it fails for runtime string values:

```
iex> <<"abc"::utf8>>
"abc"
```

```
iex> <<"abc"::utf16>>
<<0, 97, 0, 98, 0, 99>>
```

```
iex> <<"abc"::utf32>>
<<0, 0, 0, 97, 0, 0, 0, 98, 0, 0, 0, 99>>
```

```
iex> x = "abc"
iex> <<x::utf8>>
** (ArgumentError) construction of binary failed: segment 1 of type 'utf8': expected a non-negative integer encodable as utf8 but got: "abc"
    (stdlib 5.0) eval_bits.erl:145: :eval_bits.eval_exp_field/6
    iex:5: (file)
```

```
iex> x = "abc"
iex> <<x::utf16>>
** (ArgumentError) construction of binary failed: segment 1 of type 'utf16': expected a non-negative integer encodable as utf16 but got: "abc"
    (stdlib 5.0) eval_bits.erl:147: :eval_bits.eval_exp_field/6
    iex:5: (file)
```

```
iex> x = "abc"
iex> <<x::utf32>>
** (ArgumentError) construction of binary failed: segment 1 of type 'utf32': expected a non-negative integer encodable as utf32 but got: "abc"
    (stdlib 5.0) eval_bits.erl:153: :eval_bits.eval_exp_field/6
    iex:6: (file)
```

### Expected behavior

Bitstrings can be constructed from string value segments in runtime.

**Comment by josevalim** [comment]
This is expected. utf-8 only really support codepoints. `<<"abc"::utf8>>` is convenience for `<<?a::utf8, ?b::utf8, ?c::utf8>>`. In other words, you cannot interpolate a whole binary with a given encoding. You can use `<<x::binary>>` instead.

**Comment by bartblast** [comment]
@josevalim Thank you for the clarification and the docs update! I was not aware of how this works internally.

I think it’s worth looking into that in the future though, because of the developer experience - they don’t know how it works internally. They may expect different behavior since theoretically given the encoding we should be able to fetch the code points from the binary and apply segment modifiers. I understand that the implementation may be problematic though and it’s a very very low priority.

By the way some background info - I’m working on bitstring transpilation as part of Hologram here:
It may be of interest to you. At the moment the implementation is quite naive, I don’t care about performance at this stage - for example, I use UInt8 for the bit array ;) It is possible that at this stage, I got some things wrong, due to a misunderstanding of internal implementation.
* https://github.com/bartblast/hologram/blob/master/assets/js/bitstring.mjs
* https://github.com/bartblast/hologram/blob/master/test/javascript/bitstring_test.mjs
* https://github.com/bartblast/hologram/blob/master/test/elixir/hologram/ex_js_consistency/bitstring_test.exs
