### ISSUE TITLE
Warnings on warning_tests possibly not asserting enough

### ISSUE THREAD

**Issue by viniciusmuller** [elixir-lang/elixir#12648]
### Elixir and Erlang/OTP versions

Elixir 1.16.0-dev (486eb46) (compiled with Erlang/OTP 25)

### Operating system

Any

### Current behavior

While refactoring the warning tests, I've noticed there were a few warnings that appeared to be testing nothing yet still passing:

Take a look at the following cases:

- [Unreachable spec warning](https://github.com/elixir-lang/elixir/blob/486eb46795fabffd2d231575cd8a9829542f5225/lib/elixir/test/elixir/kernel/warning_test.exs#LL1676C6-L1676C6)

  If we update the assertion to be like this:
  ```ex
  assert_warn_eval(
     [ "nofile:2:  ", "unreachable" ],
     """
     defmodule Sample do
       defp my_fun(x), do: x
       @spec my_fun(integer) :: integer
     end
     """)
   ```

     We see that this fails and the code actually warns with a "unused function" rather than "unreachable spec" message.

- [Assertion with `=~ ""`](https://github.com/elixir-lang/elixir/blob/486eb46795fabffd2d231575cd8a9829542f5225/lib/elixir/test/elixir/kernel/warning_test.exs#L1514)
  Here I think the intent is to test that the line is empty, but when using `=~`, it will pass on any captured eval. If running the test using `== ""`, it currently warns with "function head for def add/2 must come at the top of its direct implementation" and fails.

### Expected behavior

The tests should assert the expected behavior more precisely

**Comment by josevalim** [comment]
Can you please send a PR removing both assertions?

1. Specs are pruned now if they are unreachable as we warn for the function
2. you Can override the docs of attached to the headless clause


Great finds!
