### ISSUE TITLE
Code.(compile/eval)_quoted drop file information in some cases

### ISSUE THREAD

**Issue by viniciusmuller** [elixir-lang/elixir#12659]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:32:16] [ds:32:16:10] [async-threads:1] [jit:ns]

Elixir 1.16.0-dev (9041fca) (compiled with Erlang/OTP 25)

### Operating system

NixOS

### Current behavior

Given the following snippet:

```ex
# test.exs

src = """
defmodule Sample do
  @file "foo-bar.ex"
  @foo 1

  def bar do
    @foo
    :ok
  end
end
"""

ast = Code.string_to_quoted!(src)
Code.compile_quoted(ast)

src_nofile = """
defmodule Sample2 do
  @file "foo-bar.ex"

  defp a, do: 1
end
"""

ast = Code.string_to_quoted!(src_nofile)
Code.eval_quoted(ast)
```

Executing it with `elixir test.exs` gives the following output:
```
warning: module attribute @foo in code block has no effect as it is never returned (remove the attribute or assign it to _ to avoid warnings)
  foo-bar.ex:6: Sample.bar/0

warning: function a/0 is unused
  nofile:4: Sample2 (module)
```

Even though `Sample2` has a `@file` attribute, it seems to be dropped in evaluation, while in the `Sample` example not.

I've checked and this also happens in Elixir v1.14.2

### Expected behavior

Both cases should output the correct file

**Comment by josevalim** [comment]
@viniciusmuller do you want to go ahead and attempt to fix this one too?

**Comment by viniciusmuller** [comment]
@josevalim I can give it a shot! Do you any pointers on what might be happening here?
