### ISSUE TITLE
Process exit during ExUnit setup_all callback causes tests to be skipped and suite to pass

### ISSUE THREAD

**Issue by sneako** [elixir-lang/elixir#12650]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Elixir 1.14.4 (compiled with Erlang/OTP 25)
```

.tool-versions
```
elixir 1.14.4-otp-25
erlang 25.3
```

### Operating system

Fedora 38

### Current behavior

If the test process or a linked process exits during the `setup_all` callback, the test suite will skip all tests in the file and report that the suite has passed.

```shell
❯ mix test


  0) SetupAllFailureTest: failure on setup_all callback, all tests have been invalidated
     ** (EXIT from #PID<0.160.0>) :error


Finished in 0.01 seconds (0.00s async, 0.01s sync)
0 failures

Randomized with seed 925073
```

This only occurs with `setup_all`, using `setup` instead results in the expected behaviour.

Here is a minimal repo with a test that reproduces the issue: https://github.com/sneako/setup_all_failure/blob/main/test/setup_all_failure_test.exs

### Expected behavior

Failures should be reported for all tests that failed to run and the suite should fail.

**Comment by sneako** [comment]
Could the fix be as simple as trapping exits here? https://github.com/elixir-lang/elixir/blob/97873b87c9aedc2a697d5b79090eb243ed730422/lib/ex_unit/lib/ex_unit/runner.ex#LL307C24-L307C24

**Comment by josevalim** [comment]
We monitor it from the parent, so we know it failed, but it seems we are not marking anything as failed when that happens. The code would be here: https://github.com/elixir-lang/elixir/blob/97873b87c9aedc2a697d5b79090eb243ed730422/lib/ex_unit/lib/ex_unit/runner.ex#L296-L297

We should probably do the same we do here: https://github.com/elixir-lang/elixir/blob/97873b87c9aedc2a697d5b79090eb243ed730422/lib/ex_unit/lib/ex_unit/runner.ex#L291 - i.e. mark all tests as invalid.
