### ISSUE TITLE
Iex failed when trying to use autocomplete

### ISSUE THREAD

**Issue by glyh** [elixir-lang/elixir#12661]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Linux arch 6.3.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 10 Jun 2023 00:35:35 +0000 x86_64 GNU/Linux

### Current behavior

1. open iex
2. press tab
3. it shows up this:
```
22:50:26.571 [error] Process #PID<0.71.0> raised an exception
** (UndefinedFunctionError) function :group.interfaces/1 is undefined or private
    (kernel 9.0.1) :group.interfaces(#PID<0.70.0>)
    (iex 1.14.0) lib/iex/broker.ex:19: IEx.Broker.shell/0
    (iex 1.14.0) lib/iex/autocomplete.ex:40: IEx.Autocomplete.expand/1
    (kernel 9.0.1) group.erl:658: :group.get_line1/5
    (kernel 9.0.1) group.erl:498: :group.get_chars_loop/10
    (kernel 9.0.1) group.erl:190: :group.io_request/6
    (kernel 9.0.1) group.erl:116: :group.server_loop/3

```

### Expected behavior

no error

**Comment by glyh** [comment]
I'm using arch linux's elixir package BTW

**Comment by josevalim** [comment]
Elixir v1.14.0 is not compatible with Erlang/OTP 26. You must use Erlang/OTP 25 or bump to Elixir v1.14.5 (or later). More info here: https://hexdocs.pm/elixir/compatibility-and-deprecations.html
