### ISSUE TITLE
`Code.Fragment.container_cursor_to_quoted/1` can't return aliases when cursor at alias line.

### ISSUE THREAD

**Issue by scottming** [elixir-lang/elixir#12673]
Is this a bug?

```elixir
iex(2)> s = "defmodule Mymodule do\n  alias Foo.Bar\n"                                     
"defmodule Mymodule do\n  alias Foo.Bar\n"
iex(3)> s |> Future.Code.Fragment.container_cursor_to_quoted
{:ok,
 {:defmodule, [line: 1],
  [
    {:__aliases__, [line: 1], [:Mymodule]},
    [
      do: {:__block__, [],
       [
         {:alias, [line: 2], [{:__aliases__, [line: 2], [:Foo, :Bar]}]},
         {:__cursor__, [line: 3], []}
       ]}
    ]
  ]}}
iex(4)> s = "defmodule MyModule do\n  alias Project.Structs.User"
"defmodule MyModule do\n  alias Project.Structs.User"
iex(5)> s |> Future.Code.Fragment.container_cursor_to_quoted     
{:ok,
 {:defmodule, [line: 1],
  [
    {:__aliases__, [line: 1], [:MyModule]},
    [do: {:alias, [line: 2], [{:__cursor__, [line: 2], []}]}]
  ]}}
iex(6)> 
```

I'm trying to copy some code to the Lexical repo: https://github.com/lexical-lsp/lexical/pull/217

But I can't extract the aliases with this line: `"defmodule MyModule do\n  alias Project.Structs.User"`

**Comment by josevalim** [comment]
Can you tell me the macro task you are trying to do? The container cursor to quoted returns the parent, in this case the parent is the do block. `cursor_context` will tell you that you are in an alias. So you always look at cursor_context first, and then you use container to disambiguate or to get more context. Does that make sense?

**Comment by scottming** [comment]
Thanks for the quick reply, I'm trying to build an `alias_mapping`.

for example:

```elixir
      source = ~q[
        defmodule MyModule do
          alias Project.Structs.Profile
          alias Project.Structs.User<CUSOR>
      ]
```

The result should be:

```
at_position(source) #=> %{
  MyModule => MyModule,
  Profile => Project.Structs.Profile,
  User => Project.Structs.User,
  :__MODULE__ => MyModule
}
```

Do you have any suggestions to archive this goal?

**Comment by scottming** [comment]
o, I see; thanks for the quick reply. I'm trying to build an `alias mapping`, with your suggestion, I think I can use `cursor_context` + `container_cursor_to_quoted` to do that.

**Comment by josevalim** [comment]
Building the mapping is not something the Elixir tools will help, unfortunately. We want to tackle that in #12645.

if you want the AST until the current cursor, then you can always append a new line and call container_cursor_to_quoted. But using Elixir sense and private APIs may still be the best way to achieve that :(

**Comment by scottming** [comment]
Yes, I have noticed this.

I cannot handle this `defmodule MyModule do\n  alias Project.Structs.User, as: MyUser` with `cursor_context` + `container_cursor_to_quoted.` Let me try adding a new line first.):

**Comment by scottming** [comment]
@josevalim 
Hi, José, we already built our alias_mapping, and we think we found a bug.

```elixir
iex(1)> Code.Fragment.container_cursor_to_quoted("%Struct{field: 1, fie\n")
{:error,
 {[line: 1, column: 17],
  "unexpected expression after keyword list. Keyword lists must always come last in lists and maps. Therefore, this is not allowed:\n\n    [some: :value, :another]\n    %{some: :value, another => value}\n\nInstead, reorder it to be the last entry:\n\n    [:another, some: :value]\n    %{another => value, some: :value}\n\nSyntax error after: ",
  "','"}}
  ```
  
`%Struct{field: 1, fie\n` this line should not fail the AST parsing, right?

**Comment by sabiwara** [comment]
> %Struct{field: 1, fie\n this line should not fail the AST parsing, right?

I think`\n` is the issue here: keyword keys must be immediately followed by `:` without any whitespace. The following are syntax errors:

```elixir
%{field : 1}
```

```elixir
%{field
: 1}
```

**Comment by sabiwara** [comment]
[Added](https://github.com/elixir-lang/elixir/pull/12773) to the syntax reference.

**Comment by scottming** [comment]
@sabiwara 

Thanks, but if this case cannot be handled by `container_cursor_to_quoted`, then we have to do something special for when the cursor is in **struct arguments**, like not adding a new line.

cc @scohen

**Comment by josevalim** [comment]
IIRC, the new line is a temporary solution until #12645 is in place. My suggestion is for you to add a newline and then, if it fails to parse, try again without the newline.
