### ISSUE TITLE
Elixir 1.15.0 Windows installer on top of OTP 26.0.1 failing (looking in `C:\Program Files\erl-23.2`)

### ISSUE THREAD

**Issue by chgeuer** [elixir-lang/elixir#12678]
### Elixir and Erlang/OTP versions

I have OTP 26.0.1 ([erts-14.0.1]) x64 installed, in "C:\Program Files\Erlang OTP", on Windows 11 x64 (22H2 OS Build 22621.1848).

### Operating system

Windows 11 Pro x64 (22H2 OS Build 22621.1848)

### Current behavior

- Installed `otp_win64_26.0.1.exe` (into `C:\Program Files\Erlang OTP`)
- I renamed the installer locally to have 1.15.0 in the filename.
- Run "Elixir 1.15.0 on Erlang 26" installer (`.exe`)

Error message: 

> "Found existing Erlang/OTP installation at C:\Program Files\erl-23.2 but checking it exited with error: "

![image](https://github.com/elixir-lang/elixir/assets/795162/498bad81-bacb-495f-ab87-f335eedd209e)

Using Procmon64.exe, I see the following CreateFile events

```text
C:\Program Files\erl-23.2\bin\erl.exe
C:\Program Files\erl-23.2\bin\erl.exe.exe
C:\Program Files\erl-23.2\bin\erl.exe -noinput
C:\Program Files\erl-23.2\bin\erl.exe -noinput.exe
C:\Program Files\erl-23.2\bin\erl.exe -noinput -eval
C:\Program Files\erl-23.2\bin\erl.exe -noinput -eval.exe
C:\Program Files\erl-23.2\bin\erl.exe -noinput -eval "io:put_chars(erlang:system_info(otp_release)),halt()."
C:\Program Files\erl-23.2\bin\erl.exe -noinput -eval "io:put_chars(erlang:system_info(otp_release)),halt().".exe
```

![image](https://github.com/elixir-lang/elixir/assets/795162/033851cb-4aa7-4454-b80d-962dc3afbf78)

Running `"C:\Program Files\Erlang OTP\bin\erl.exe" -noinput -eval "io:put_chars(erlang:system_info(otp_release)),halt()."` prints `26`.

### Expected behavior

Installation :-)

**Comment by wojtekmach** [comment]
Thank you for the report.

Do you have an installation at `C:\Program Files\erl-23.2` and if so, did you try uninstalling it first?

**Comment by wojtekmach** [comment]
I noticed we don't quote the path to erl.exe, so here's a patch that does that:

```
~/src/elixir[v1.15]% git diff
```

```diff
diff --git a/lib/elixir/scripts/windows_installer/installer.nsi b/lib/elixir/scripts/windows_installer/installer.nsi
index 2f36142be..7f128703c 100644
--- a/lib/elixir/scripts/windows_installer/installer.nsi
+++ b/lib/elixir/scripts/windows_installer/installer.nsi
@@ -40,28 +40,28 @@ Function CheckOTPPageShow
     Pop $DownloadOTPLink
     ${NSD_OnClick} $DownloadOTPLink OpenOTPDownloads
   ${Else}
-    nsExec::ExecToStack `$OTPPath\bin\erl.exe -noinput -eval "\
+    nsExec::ExecToStack '"$OTPPath\bin\erl.exe" -noinput -eval "\
     io:put_chars(erlang:system_info(otp_release)),\
-    halt()."`
+    halt()."'
     Pop $0
     Pop $1

     ${If} $0 == 0
       StrCpy $InstalledOTPRelease $1
       ${If} $InstalledOTPRelease == ${OTP_RELEASE}
-        ${NSD_CreateLabel} 0 0 100% 20u "Found existing Erlang/OTP $InstalledOTPRelease installation at $OTPPath. Please proceed."
+        ${NSD_CreateLabel} 0 0 100% 20u "Found existing Erlang/OTP $InstalledOTPRelease installation at $\"$OTPPath$\". Please proceed."
       ${ElseIf} $2 < ${OTP_RELEASE}
-        ${NSD_CreateLabel} 0 0 100% 30u "Found existing Erlang/OTP $InstalledOTPRelease installation at $OTPPath but this Elixir installer was precompiled for Erlang/OTP ${OTP_RELEASE}. \
+        ${NSD_CreateLabel} 0 0 100% 30u "Found existing Erlang/OTP $InstalledOTPRelease installation at $\"$OTPPath$\" but this Elixir installer was precompiled for Erlang/OTP ${OTP_RELEASE}. \
         We recommend checking if there is an Elixir version precompiled for Erlang/OTP $InstalledOTPRelease. Otherwise, proceed."
       ${Else}
         SetErrorlevel 5
-        MessageBox MB_ICONSTOP "Found existing Erlang/OTP $InstalledOTPRelease installation at $OTPPath but this Elixir version was precompiled for Erlang/OTP ${OTP_RELEASE}. \
+        MessageBox MB_ICONSTOP "Found existing Erlang/OTP $InstalledOTPRelease installation at $\"$OTPPath$\" but this Elixir version was precompiled for Erlang/OTP ${OTP_RELEASE}. \
         Please upgrade your Erlang/OTP version or choose an Elixir installer matching your Erlang/OTP version"
         Quit
       ${EndIf}
     ${Else}
       SetErrorlevel 5
-      MessageBox MB_ICONSTOP "Found existing Erlang/OTP installation at $OTPPath but checking it exited with $0: $1"
+      MessageBox MB_ICONSTOP "Found existing Erlang/OTP installation at $\"$OTPPath$\" but checking it exited with $0: $1"
       Quit
     ${EndIf}
   ${EndIf}
```

and I have also created the installer for Elixir v1.15 on OTP 26:

[elixir-otp-26.exe.zip](https://github.com/elixir-lang/elixir/files/11793278/elixir-otp-26.exe.zip)

**Comment by chgeuer** [comment]
Thanks @wojtekmach, 

the snippet helped me to understand where the `erl-23.2` stuff came from. My filesystem was clean, but the registry had a left-over:

```regedt
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\11.1.4]
@="C:\\Program Files\\erl-23.2"
"Start Menu Folder"="Erlang OTP 23 (x64)"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\14.0.1]
@="C:\\Program Files\\Erlang OTP"
"Start Menu Folder"="Erlang OTP 26 (x64)"
```

When I execute the exe in your attached file, Windows Defender quarantines the item, as it detects `Trojan:Win32/Bearfoos.A!ml`.

![image](https://github.com/elixir-lang/elixir/assets/795162/a4d708e8-36e2-4113-8507-949ea14c2c45)

**Comment by markenzie** [comment]
I think this needs to be reopened and looked at closer. Just caused me some headaches as well. Uninstalled all versions of Erlang and Elixir. Deleted any folders or remenants I could find inside Program Files. Still running into the original error reported.

> ### Registry leftover
> the snippet helped me to understand where the `erl-23.2` stuff came from. My filesystem was clean, but the registry had a left-over:
> 
> ```
> [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\11.1.4]
> @="C:\\Program Files\\erl-23.2"
> "Start Menu Folder"="Erlang OTP 23 (x64)"
> 
> [HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Ericsson\Erlang\14.0.1]
> @="C:\\Program Files\\Erlang OTP"
> "Start Menu Folder"="Erlang OTP 26 (x64)"
> ```

> Error message:
> 
> > "Found existing Erlang/OTP installation at C:\Program Files\erl-23.2 but checking it exited with error: "
> 

The installer is obviously finding old registry keys that should have been removed by previous uninstallers. 

It's trying to run a file that doesn't even exist. A better fallback would be to ignore that registry key completely if the executable path does not exist. Its evident in the no error message - no program to run, no error.

**Comment by josevalim** [comment]
This is a good idea. Would you like to try a PR too? /cc @wojtekmach

**Comment by markenzie** [comment]
Thank you. I've never worked with NSI but I did do some digging.

Problematic lines:

https://github.com/elixir-lang/elixir/blob/v1.15.4/lib/elixir/scripts/windows_installer/installer.nsi#L32-L35

On 32 we pick the 0th entry in the subkey which I beleive is sorted by insertion-order but might be alphabetically but I'm not sure.

Then on 43 that's used as the direct path to erl.exe for OTP information.

**Comment by Iftakharpy** [comment]
When I try to execute the elixir installer I get this error it says it found OTP installation but there is no OPT installed. If I proceed with the installation and then install OTP 27, I can't run the `iex` command I get the following error. Can someone help me fix this.
```
PS C:\Users\iftak> iex
Cannot find file at 'c:\program files\erlang otp\erts-14.0.2\bin\erl.exe' (c:\program files\erlang otp\erts-14.0.2\bin\erl.exe). This usually indicates a missing or moved file.
```
![image](https://github.com/user-attachments/assets/15a4fb7e-f015-4874-8cb1-97a544498d62)
