### ISSUE TITLE
iex crashes when using autocomplete

### ISSUE THREAD

**Issue by jeroenbourgois** [elixir-lang/elixir#12672]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Elixir 1.14.0 (compiled with Erlang/OTP 25)

### Operating system

Arch Linux, Kernel: x86_64 Linux 6.3.1-arch1-1

### Current behavior

- I startup `iex` either withing a Mix project folder or in an empty `/tmp` folder;
- I enter the beginning of a command and hit the `tab` key;
- I am presented with the following error (here I types `Enum.` and hit `tab`):

```
iex|1|▶ Enum.*** ERROR: Shell process terminated! (^G to start new job) ***

11:18:30.581 [error] Process #PID<0.71.0> raised an exception
** (UndefinedFunctionError) function :group.interfaces/1 is undefined or private
    (kernel 9.0.1) :group.interfaces(#PID<0.70.0>)
    (iex 1.14.0) lib/iex/broker.ex:19: IEx.Broker.shell/0
    (iex 1.14.0) lib/iex/autocomplete.ex:40: IEx.Autocomplete.expand/1
    (kernel 9.0.1) group.erl:658: :group.get_line1/5
    (kernel 9.0.1) group.erl:498: :group.get_chars_loop/10
    (kernel 9.0.1) group.erl:190: :group.io_request/6
    (kernel 9.0.1) group.erl:116: :group.server_loop/3
````

### Expected behavior

I expected to be presented with a list of methods within `Enum`.

I haven't (or can't remember) updated Elixir nor Erlang in a while, though I am not sure about that. It's not something critical, but really really annoying :)

Is there something I can do to diagnose the actual error?

Note:
I also tried removing my local `.iex.exs` file, same result.

Update:
I just noticed that previous commands are not saved anymore, probably related. With previous commands I mean: normally I can exit an iex shell and enter it again, hit the up arrow and be presented with my last command.

Where is that info stored? Maybe I just need to clean that folder/file?

**Comment by sabiwara** [comment]
Erlang 26 is only supported [from 1.14.5](https://hexdocs.pm/elixir/1.14.5/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp).

**Comment by jeroenbourgois** [comment]
:facepalm: stupid me. I'll have to wait a bit then, the latest elixir package for arch is on 1.14.0-1 and I don't really fancy building it from source. Thanks a lot!
