### ISSUE TITLE
Could not start application no such file or directory on Elixir 1.15.0

### ISSUE THREAD

**Issue by SteffenDE** [elixir-lang/elixir#12682]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit

also happens on 1.15.0 and Erlang/OTP 25.

### Operating system

macOS

### Current behavior

The first invocation of mix compile works, any subsequent mix commands lead to the error

```
** (Mix) Could not start application :included_app_one: {~c"no such file or directory", ~c"geolix.app"}
```

The issue occurs in an umbrella application, where app one includes a dependency as `included_application` and `runtime: false` and the second app depends on the first app. To reproduce, see: https://github.com/SteffenDE/elixir-include-umbrella-issue
Creating a release using `rm -rf _build && mix release app` creates a functional release that works as expected. Adding `prune_code_paths: false` does NOT fix the problem.

### Expected behavior

Subsequent mix compile calls should work.

**Comment by SteffenDE** [comment]
Can confirm that this solves the issue, thank you very much! 😃

**Comment by whatyouhide** [comment]
Yep, I’m experiencing the same with an umbrella app that depends on [fun_with_flags](https://github.com/tompave/fun_with_flags) and shoves it inside `:included_applications`.

**Comment by josevalim** [comment]
@whatyouhide this is fixed. Please run either on the main (or v1.15 branches) for a while to see if you catch any regressions. :)
