### ISSUE TITLE
Duplicate seeds for random number generator

### ISSUE THREAD

**Issue by randycoulman** [elixir-lang/elixir#12685]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)
```

I haven't yet tested with Elixir 1.15, but the code in question hasn't changed, so I expect that the same results apply.

### Operating system

MacOS 13.4

### Current behavior

ExUnit currently [seeds the OTP random number generator (RNG)](https://github.com/elixir-lang/elixir/blob/698fcdb82c4b346803f53cd34d822404b14172c7/lib/ex_unit/lib/ex_unit/runner.ex#L487-L489) for a test process with a [now-deprecated algorithm](https://github.com/elixir-lang/elixir/blob/698fcdb82c4b346803f53cd34d822404b14172c7/lib/ex_unit/lib/ex_unit/runner.ex#L6) and a seed that is based on the test seed, a hash of the module name, and a hash of the test name. I believe that this is to make test runs using the same test seed more repeatable than they otherwise would be, which is a good thing.

In our code, we generate random slugs for various purposes, and we found that multiple tests were generating the same slug resulting in collisions and spurious test failures. We ultimately discovered that RNG seed was the same even when given different inputs. In one case, two tests in the same module were generating the same RNG seed even though the hashes of their test names were different.

Here's an example of the problem. Note that, it doesn't seem to matter what the test module name is; I've tried different module names with these two test names, and I get duplicate seeds.

```
iex(1)> :erlang.phash2(:"test deletes objects")
66851555
iex(2)> :erlang.phash2(:"test creates objects")
45880035
iex(3)> seed = fn name -> :rand.seed(:exs1024, {:erlang.phash2(MyApp.SeedTest), :erlang.phash2(name), 23848}) end
#Function<42.3316493/1 in :erl_eval.expr/6>
iex(4)> seed.(:"test deletes objects")
{%{
   jump: #Function<12.34006561/1 in :rand.exs1024_jump>,
   max: 18446744073709551615,
   next: #Function<11.34006561/1 in :rand.exs1024_next>,
   type: :exs1024
 },
 {[13504970322214688558, 1370191292280206732, 10302324884822962213,
   17534044084276742230, 3711192206464673659, 13885585154416371597,
   8069133421021339685, 426054385629631675, 6155781543359386638,
   14076542722417284742, 710317579518961401, 14059512158466608421,
   18197249724286071515, 9701728185547967735, 15925051505617382990,
   14201379061095463323], []}}
iex(5)> seed.(:"test creates objects")
{%{
   jump: #Function<12.34006561/1 in :rand.exs1024_jump>,
   max: 18446744073709551615,
   next: #Function<11.34006561/1 in :rand.exs1024_next>,
   type: :exs1024
 },
 {[13504970322214688558, 1370191292280206732, 10302324884822962213,
   17534044084276742230, 3711192206464673659, 13885585154416371597,
   8069133421021339685, 426054385629631675, 6155781543359386638,
   14076542722417284742, 710317579518961401, 14059512158466608421,
   18197249724286071515, 9701728185547967735, 15925051505617382990,
   14201379061095463323], []}}
```

### Expected behavior

I think that the seeding of the RNG should be more random than it currently is.

I think that the fundamental idea of seeding the RNG based on the test seed is a good idea and should be preserved. I believe that we're running into a weakness of the seed generation for the RNG that ExUnit is using.

I think the best solution would be to use a newer RNG algorithm as part of the seeding process in ExUnit.

My recommendation would be to change [`@rand_algorithm`](https://github.com/elixir-lang/elixir/blob/698fcdb82c4b346803f53cd34d822404b14172c7/lib/ex_unit/lib/ex_unit/runner.ex#L6) to `:default` so that ExUnit is always using the default RNG algorithm for a given OTP version.

The `:default` value [has been available since OTP 24](https://www.erlang.org/doc/man/rand.html#seed-2), which is [the minimum version supported by Elixir 1.15.x](https://hexdocs.pm/elixir/1.15.0/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp).

If it is more important to use the same algorithm for all supported OTP versions, even if the default changes, then we could hard-code the current default of `:exsss` instead, which has [been available since OTP 22](https://www.erlang.org/doc/man/rand.html#description). This would mean that a similar issue could arise in the future as the RNG algorithms change in later OTP versions.

If I use the same example as above with the `:default` algorithm, I get different seeds as expected.

```
iex(4)> seed = fn name -> :rand.seed(:default, {:erlang.phash2(MyApp.
SeedTest), :erlang.phash2(name), 23848}) end
#Function<42.3316493/1 in :erl_eval.expr/6>
iex(5)> seed.(:"test deletes objects")                               
{%{                                         
   bits: 58,
   jump: #Function<3.34006561/1 in :rand.exsplus_jump>,
   next: #Function<0.34006561/1 in :rand.exsss_next>,
   type: :exsss,
   uniform: #Function<1.34006561/1 in :rand.exsss_uniform>,
   uniform_n: #Function<2.34006561/2 in :rand.exsss_uniform>
 }, [218831190204491433 | 204513716520166439]}
iex(6)> seed.(:"test creates objects")                               
{%{                                         
   bits: 58,
   jump: #Function<3.34006561/1 in :rand.exsplus_jump>,
   next: #Function<0.34006561/1 in :rand.exsss_next>,
   type: :exsss,
   uniform: #Function<1.34006561/1 in :rand.exsss_uniform>,
   uniform_n: #Function<2.34006561/2 in :rand.exsss_uniform>
 }, [115633106507893109 | 19965906867837765]}
```

If this seems like a viable solution, I'm happy to put together a PR for it (but feel free to go ahead on your own).

**Comment by josevalim** [comment]
Great analysis!

The problem with changing the seed algorithm is that it is a backwards incompatible change. Some tests may not start to fail. So perhaps we should:

1. Change it to a more recent one (exsss)
2. But also add an option to change it (so folks can preserve backwards compatibility or update to another)

Are you interested in sending a PR?

**Comment by randycoulman** [comment]
I'm happy to work on a PR, but probably won't have time until next week at the earliest. If someone else is interested, go for it. Otherwise, I'll work on it when I have time.

**Comment by josevalim** [comment]
Next week sounds great. This would be part of Elixir v1.16 only, so we have six months. :)

**Comment by kevinferretti** [comment]
@randycoulman thanks for putting in the work to document this issue. If you haven't started one, I'll attempt a PR as a learning exercise since I'm new to Elixir.

**Comment by randycoulman** [comment]
@kevinferretti I haven't had a chance to start on it yet, so go for it!

**Comment by josevalim** [comment]
Closing in favor of #12733.
