### ISSUE TITLE
Mix compiler task not consistently working after 1.15 upgrade

### ISSUE THREAD

**Issue by beerlington** [elixir-lang/elixir#12686]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

### Operating system

MacOS 12.6.6

### Current behavior

My app has a custom mix compiler task that cannot consistently be found after upgrading to Elixir 1.15.

The first the the app compiles, everything loads fine. If I shutdown the server and then try to start it again, I get an error like:

```
** (Mix) The task "compile.test" could not be found. Did you mean "compile"?
```

I've recreated the issue with a barebones app https://github.com/beerlington/elixir-1.15-compiler-demo

If I run a command like `mix test` twice, the first time it succeeds and the second time I get an error about the mix compiler task not being found.

### Expected behavior

The compiler task should always be found when running the tests or starting the application.

**Comment by aptinio** [comment]
This also happens on a project I'm working on which depends on [Rambo](https://github.com/jayjun/rambo). Rambo has a Mix task that [uses `Mix.Task.Compiler`](https://github.com/jayjun/rambo/blob/master/lib/mix/tasks/compile.rambo.ex).

**Comment by zvlasic** [comment]
Having the same problem with our own custom task
