### ISSUE TITLE
Elixir broken on MacOS Sonoma

### ISSUE THREAD

**Issue by ohenecoker** [elixir-lang/elixir#12684]
### Elixir and Erlang/OTP versions

elixir 1.15.0-otp-26

### Operating system

MacOS Sonoma version 14.0 Beta

### Current behavior

I can't get elixir to run on my mac. The issue started after I updated my OS to Sonoma. I always get a bus error anytime I run any elixir command (see below). I don't know enough about the internals of elixir to diagnose this problem.

`[1]    88716 bus error  elixir -v`

### Expected behavior

No "bus" error

**Comment by josevalim** [comment]
What happens if you just run `erl`? My suspicion is that this is an Erlang issue but most likely it is a platform issue. You need to make sure you are running an Erlang compiled for Apple Silicon (and Rosetta is not involved).

**Comment by wojtekmach** [comment]
Does running `$ erl` work?

If not, that'd be an OTP issue. You can find more information by opening up Console.app and "Crash Reports".

**Comment by ohenecoker** [comment]
> What happens if you just run `erl`? My suspicion is that this is an Erlang issue but most likely it is a platform issue. You need to make sure you are running an Erlang compiled for Apple Silicon (and Rosetta is not involved).

@josevalim I get the same thing
<img width="294" alt="Screenshot 2023-06-20 at 8 52 26 AM" src="https://github.com/elixir-lang/elixir/assets/478208/0e16ff07-5e49-4d43-aeef-bf6aaa3007e9">

**Comment by josevalim** [comment]
Yes, so that's an Erlang issue but I really think that the `erl` you are using does not match your system. How did you install it? There is also a thread on the forum about it, but the forum is offline: https://elixirforum.com/t/bus-error-after-upgrading-to-sonoma-beta/56354 - you can check it once it is back up

Closing for now! :)

**Comment by ohenecoker** [comment]
@josevalim I installed it via homebrew. Thanks! I'll check out the forum.

**Comment by optikfluffel** [comment]
@ohenecoker I just tried with Erlang and Elixir being installed via `asdf` and everything seems to work on my little Beta VM over here.

**Comment by ohenecoker** [comment]
@optikfluffel that's interesting I wonder if uninstalling/removing erlang and elixir and reinstalling via asdf will solve it.

**Comment by ohenecoker** [comment]
@optikfluffel installing via asdf worked!! Thanks a lot!
