### ISSUE TITLE
Function calls without parentheses fail to compile in elixir 1.15

### ISSUE THREAD

**Issue by rliebling** [elixir-lang/elixir#12688]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [
jit]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

```

### Operating system

osx

### Current behavior

Not sure whether this was expected.  If so, probably worth mentioning in the `incompatibilities` section of the changelog/release notes.  (Seems like i saw some discussion of it somewhere but cannot find it now.)

Consider this example `foo.exs`:

```
defmodule Foo do
  def bar do
    1
  end
  def baz do
    bar
  end
end

IO.inspect Foo.baz
```

In elixir 1.14 this gives a warning:

```
% /opt/homebrew/bin/elixir /tmp/foo.exs
warning: variable "bar" does not exist and is being expanded to "bar()", please use parentheses to remove the ambiguity or change the variable name
  /tmp/foo.exs:6: Foo.baz/0

1
```

But, in 1.15 it gives an error:

```
 % elixir /tmp/foo.exs                  
error: undefined variable "bar"
  /tmp/foo.exs:6: Foo.baz/0

** (CompileError) /tmp/foo.exs: cannot compile module Foo (errors have been logged)
```

I suspect this will come up in people's code, but is not listed in the release notes/changelog for elxiir 1.15.  I came across this because the version of `recon_ex` on hex has this mix.exs: https://github.com/tatsuya6502/recon_ex/blob/97a66cb6c2a8e64c7c50827672c5e53b7f6f6467/mix.exs which produces this error about `deps` (no parenthesis to disambiguate it as a function invocation).

### Expected behavior

I think this is expected - in which case I just think it should be called out in the release notes.  But, it may not be intentional - i don't know.

**Comment by wojtekmach** [comment]
It is mentioned here https://github.com/elixir-lang/elixir/blob/v1.15/CHANGELOG.md#elixir

> [Kernel] Raise instead of warning on undefined variables. Previously, an undefined variable would attempt to invoke a function of the same name, which led to confusing error messages, especially to newcomers. To enable the previous behaviour, invoke Code.compiler_options(on_undefined_variable: :warn) at the top of your mix.exs

**Comment by rliebling** [comment]
Ah, thanks for pointing me to it.  I'm fine if you want to close this.  I suggest perhaps adding mention to the "Hard Deprecations" section, though.  I would not expect to see a change like this under 'Enhancements' - the enhancement seems to be that there's a way to maintain the old behavior.

but, like i said, I accept the judgment of the team and just wanted to make sure it was intended behavior.

**Comment by whatyouhide** [comment]
Maybe we could suggest `Code.compiler_options(on_undefined_variable: :warn)` itself in the new error message.

**Comment by josevalim** [comment]
I added a note to the release notes but I forgot to apply them to the CHANGELOG. The release notes say:

> ### Potential incompatibilities
>
> As part of this effort, the behaviour where undefined variables were
> transformed into nullary function calls, often leading to confusing error
> reports, has been disabled during project compilation. You can invoke
> `Code.compiler_options(on_undefined_variable: :warn)`
> at the top of your `mix.exs` to bring the old behaviour back.

**Comment by josevalim** [comment]
@whatyouhide we don't want to add mention that in the error message because you would only want this behaviour when using a dependency that is showing a warning for at least 6 years. For everyone else, the added context is confusing or unecessary, which is why we changed the behaviour in the first place.

**Comment by josevalim** [comment]
Changelog updated.
