### ISSUE TITLE
Error: 1) test code path prunning (Mix.Tasks.CompileTest) Elixir 1.15.0 Erlang/OTP 26 [erts-14.0.1] 

### ISSUE THREAD

**Issue by verbus** [elixir-lang/elixir#12689]
### Elixir and Erlang/OTP versions

verbus@ubuntu-s-8vcpu-16gb-nyc1-01:~/elixir-1.15.0$ pwd
/home/verbus/elixir-1.15.0
verbus@ubuntu-s-8vcpu-16gb-nyc1-01:~/elixir-1.15.0$ cat VERSION 
1.15.0

### Operating system

uname -a Linux ubuntu-s-8vcpu-16gb-nyc1-01 5.4.0-152-generic #169-Ubuntu SMP Tue Jun 6 22:23:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Current behavior

After running:

$ make test
==> elixir (eunit)
  All 132 tests passed.

==> elixir (ex_unit)
Excluding tags: [windows: true]
.
.
.
.

1) test code path prunning (Mix.Tasks.CompileTest)
     test/mix/tasks/compile_test.exs:332
     match (=) failed
     code:  assert {:docs_v1, _, _, _, _, _, _} = Code.fetch_docs(:zlib)
     left:  {:docs_v1, _, _, _, _, _, _}
     right: {:error, :chunk_not_found}
     stacktrace:
       test/mix/tasks/compile_test.exs:340: anonymous fn/0 in Mix.Tasks.CompileTest."test code path prunning"/1
       (elixir 1.15.0) lib/file.ex:1624: File.cd!/2
       test/test_helper.exs:146: MixTest.Case.in_fixture/3
       test/mix/tasks/compile_test.exs:335: (test)
...........................................................................................................................................................................................................................
Finished in 232.7 seconds (5.1s on load, 0.05s async, 227.6s sync)
6 doctests, 796 tests, 1 failure

Randomized with seed 369567
make: *** [Makefile:116: test_mix] Error 2

### Expected behavior

Expected test to pass.

**Comment by josevalim** [comment]
It happens if using Erlang/OTP compiled without docs. But it has been fixed on main/v1.15 branches already.
