### ISSUE TITLE
Subsequent run of "mix compile" fails

### ISSUE THREAD

**Issue by gmile** [elixir-lang/elixir#12691]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.0 (compiled with Erlang/OTP 24)

### Operating system

macOS 13.3 (22E252)

### Current behavior

Running `mix compile` second time in a row fails:

```
$ mix compile
Compiling 1 file (.yrl)
src/sample_parser.yrl:2:34: Warning: terminal symbol '$.' not used
Compiling 1 file (.erl)
Compiling 1 file (.ex)
Generated yecc_issue app
$ mix compile
** (UndefinedFunctionError) function :yecc.format_error/1 is undefined (module :yecc is not available)
    :yecc.format_error({:unused_terminal, :"$."})
    (mix 1.15.0) lib/mix/compilers/erlang.ex:301: anonymous fn/3 in Mix.Compilers.Erlang.show_warnings/1
    (elixir 1.15.0) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix 1.15.0) lib/mix/compilers/erlang.ex:298: Mix.Compilers.Erlang.show_warnings/1
    (mix 1.15.0) lib/mix/compilers/erlang.ex:108: Mix.Compilers.Erlang.compile/5
    (mix 1.15.0) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.0) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.15.0) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
```

I've prepared repository with a minimal reproduction example here: https://github.com/gmile/yecc_issue.

### Expected behavior

Running `mix compile` second time in a row doesn't fail.

**Comment by josevalim** [comment]
You need to depend on `parser_tools`, otherwise it won't be available. I will investigate why it works the first time though.

**Comment by josevalim** [comment]
Ignore the above. This is a bug indeed.

**Comment by elishagreenwald** [comment]
Hi was this fixed in a later version of Elixir? I'm using 1.15 and getting this bug.

**Comment by josevalim** [comment]
What version of Elixir 1.15?

**Comment by elishagreenwald** [comment]
> What version of Elixir 1.15?

Erlang/OTP 26 [erts-14.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

**Comment by josevalim** [comment]
Yes, that's the same version as OP who reported the bug, so please update!

**Comment by elishagreenwald** [comment]
Got it, thanks!
