### ISSUE TITLE
Slower compilation times on Erlang/OTP 26

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#12696]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

(I'm using asdf, elixir 1.15.0-otp-26, erlang 26.0.1)

### Operating system

macOS Big Sur 11.7.1

### Current behavior

After upgrading my application to Erlang/OTP 26 (26.0.1) I noticed `mix test` times in my project were consistently adding ~1 second extra compared to Erlang/OTP 25 (25.1.2). Erlang OTP 26 is supposed to be faster, so that made me raise my eyebrow 🤨 

After some investigation I managed to extract some code from the project to a minimum sample app that reproduces the issue: [https://github.com/fertapric/hello](https://github.com/fertapric/hello)

Using that example app, I get this compilation times for different Erlang/OTP version:

**Erlang/OTP 26**
```
$ asdf current
elixir          1.15.0-otp-26   ASDF_ELIXIR_VERSION environment variable
erlang          26.0.1          ASDF_ERLANG_VERSION environment variable
$ time mix test --profile-require time
[profile]    981ms compiling +      0ms waiting while compiling test/hello_test.exs
[profile] Finished compilation cycle of 1 modules in 982ms
[profile] Finished group pass check of 1 modules in 9ms
There are no tests to run

real	0m2.658s
user	0m2.081s
sys	0m1.547s
```

**Erlang/OTP 25**
```
$ asdf current
elixir          1.15.0-otp-25   ASDF_ELIXIR_VERSION environment variable
erlang          25.1.2          ASDF_ERLANG_VERSION environment variable
$ time mix test --profile-require time
[profile]    337ms compiling +      0ms waiting while compiling test/hello_test.exs
[profile] Finished compilation cycle of 1 modules in 338ms
[profile] Finished group pass check of 1 modules in 7ms
There are no tests to run

real	0m1.613s
user	0m1.052s
sys	0m0.433s
```

Debugging a bit I discovered that by removing the [`import` in `ExUnit.CaseTemplate`'s `using`](https://github.com/fertapric/hello/blob/main/test/support/test_case.ex#L6) compilation times were reduce drastically:

**Erlang/OTP 26**
```
$ asdf current
elixir          1.15.0-otp-26   ASDF_ELIXIR_VERSION environment variable
erlang          26.0.1          ASDF_ERLANG_VERSION environment variable
$ time mix test --profile-require time
[profile]    167ms compiling +      0ms waiting while compiling test/hello_test.exs
[profile] Finished compilation cycle of 1 modules in 168ms
[profile] Finished group pass check of 1 modules in 7ms
There are no tests to run

real	0m1.821s
user	0m1.274s
sys	0m1.447s
```

**Erlang/OTP 25**
```
$ asdf current
elixir          1.15.0-otp-25   ASDF_ELIXIR_VERSION environment variable
erlang          25.1.2          ASDF_ERLANG_VERSION environment variable
$ time mix test --profile-require time
[profile]    144ms compiling +      0ms waiting while compiling test/hello_test.exs
[profile] Finished compilation cycle of 1 modules in 144ms
[profile] Finished group pass check of 1 modules in 6ms
There are no tests to run

real	0m1.287s
user	0m0.849s
sys	0m0.404s
```

So it seems that it might be something that was happening before, but it was exacerbated by Erlang/OTP 26 🤔 

### Expected behavior

Similar (or better) compilation times for Erlang/OTP 26

**Comment by josevalim** [comment]
Reported here: https://github.com/erlang/otp/issues/7432
