### ISSUE TITLE
elixir compiler fails to compile erlang lib

### ISSUE THREAD

**Issue by fcevado** [elixir-lang/elixir#12693]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.15.0 (compiled with Erlang/OTP 26)
```
and also
```
Erlang/OTP 25 [erts-13.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.15.0 (compiled with Erlang/OTP 25)
```

### Operating system

linux 6.3.7-gentoo x86_64

### Current behavior

when compiling package [eredis](https://hex.pm/packages/eredis) that is an erlang package, with elixir 1.15 with either erlang 25 and erlang 26 the following errors happening:
```
==> eredis
Compiling 7 files (.erl)
src/eredis_parser.erl:25:14: can't find include lib "eunit/include/eunit.hrl"
%   25| -include_lib("eunit/include/eunit.hrl").
%     |              ^
```

### Expected behavior

compiling with elixir 1.14.5 either  with erlang 26 and 25 doesn't break the package compilation.
i've also tested using docker image from hexpm using `debian-bullseye-20230522` and same behaviour repeates, either for breaking the compilation on 1.15 and compilation working with 1.14.5

**Comment by josevalim** [comment]
This is behaving as expected. `eredis` depends on `eunit` but it is not listing `eunit` as dependency. The fix is similar to #12681. Either add `eunit` as a dependency or ask it to be compiled with Rebar. You can ask them to remove their `mix.exs` file too and it should all work.
