### ISSUE TITLE
ExUnit.CaptureLog fails in tests on high concurrency

### ISSUE THREAD

**Issue by hubertlepicki** [elixir-lang/elixir#12692]
### Elixir and Erlang/OTP versions

erlang 26.0.1
elixir 1.15-otp-26 and also main

### Operating system

Fedora Linux 37

### Current behavior

When running tests in high concurrency (--max-cases >= 4) I am getting undeterministic failures when my tests use capture_log function.

The error I see on the console is:

```
Logger - error: {Logger - error: removed_failing_handler,'Elixir.ExUnit.CaptureServer'}
{removed_failing_handler,'Elixir.ExUnit.CaptureServer'}

````

I have created an isolated repository with some dummy tests that log a lot of messages to replicate, and I am able to reproduce the bug every time by simply

1. Checking out the repository
2. Running `mix test` (I have AMD64 CPU with 12 cores)

The repository is here:
https://github.com/hubertlepicki/kaboom

The output I see:

```
» mix test
...Logger - error: Logger - error: {removed_failing_handler,'Elixir.ExUnit.CaptureServer'}
{removed_failing_handler,'Elixir.ExUnit.CaptureServer'}
...

  1) test log some warnings (Kaboom3Test)
     test/kaboom3_test.exs:16
     Assertion with =~ failed
     code:  assert capture_log(fn -> Enum.each(0..1000, fn i -> Logger.warning("log msg #{i}") end) end) =~ "log msg"
     left:  ""
     right: "log msg"
     stacktrace:
       test/kaboom3_test.exs:17: (test)



  2) test log some debugs (KaboomTest)
     test/kaboom_test.exs:8
     Assertion with =~ failed
     code:  assert capture_log(fn -> Enum.each(0..1000, fn i -> Logger.debug("log msg #{i}") end) end) =~ "log msg"
     left:  ""
     right: "log msg"
     stacktrace:
       test/kaboom_test.exs:9: (test)



  3) test log some warnings (Kaboom2Test)
     test/kaboom2_test.exs:16
     Assertion with =~ failed
     code:  assert capture_log(fn -> Enum.each(0..1000, fn i -> Logger.warning("log msg #{i}") end) end) =~ "log msg"
     left:  ""
     right: "log msg"
     stacktrace:
       test/kaboom2_test.exs:17: (test)



  4) test log some debugs (Kaboom4Test)
     test/kaboom4_test.exs:8
     Assertion with =~ failed
     code:  assert capture_log(fn -> Enum.each(0..1000, fn i -> Logger.debug("log msg #{i}") end) end) =~ "log msg"
     left:  ""
     right: "log msg"
     stacktrace:
       test/kaboom4_test.exs:9: (test)

......
Finished in 0.3 seconds (0.3s async, 0.00s sync)
16 tests, 4 failures

Randomized with seed 263562
```

or similar, sometimes more, sometimes less test pass before the logger is removed.

The logger handler is removed here:
https://github.com/erlang/otp/blob/6a95736c21a126497c7efdca44207b7e9fc9d92d/lib/kernel/src/logger_backend.erl#L56

But I am unsure how to enable/see the internal logging in Erlang, if someone could point me towards right direction I could report what the actual exception is.

### Expected behavior

The tests should pass

**Comment by PragTob** [comment]
We're experiencing the same thing in our CI (trying to upgrade). Thanks @hubertlepicki for creating a minimal reproduction repo! 💚

**Comment by hubertlepicki** [comment]
@PragTob you can probably make it work, albeit slower, on the CI by passing `--max-cases=1` to `mix test`  command.

**Comment by hubertlepicki** [comment]
I can confirm this fixex the concurrency issue on both: the test repo I created above and my actual CI pipeline. 

Thanks @josevalim
