### ISSUE TITLE
test_mix make task intermittently fails (due to BEAM segfault) on Alpine Linux

### ISSUE THREAD

**Issue by wejn** [elixir-lang/elixir#12713]
#### Alpine 3.18.2

Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

---

#### Alpine edge

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

---

#### Alpine edge

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit]

Elixir 1.14.5 (compiled with Erlang/OTP 26)

### Operating system

Linux (alpine 3.18.2), Linux (alpine edge)

### Current behavior

While working on [elixir 1.15.0 release for Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/48331#note_319908) I encountered an intermittent test error in `test_mix` make target.

I traced it down to [a segfault in beam](https://github.com/erlang/otp/issues/7436), somehow triggered by `System.restart()` in specific setups (I think).

It would be super nice to have a smaller set of steps to reproduce, because the two cases I managed to get to:

-  run `yes "" | mix test --listen-on-stdin` in a fresh phoenix project (`mix phx.new ...`) and have it restart a few times
- the one below using the attached [`crash-beam-using-mix.exs`](https://github.com/elixir-lang/elixir/files/11860450/crash-beam-using-mix.txt) (cut down from `lib/mix/test/mix/tasks/test_test.exs`)

aren't very satisfying.

To reproduce with `elixir-1.15.0` tarball:

```sh
# on an Alpine Linux instance, mine is 4cpu, 8Gi RAM

# Get erlang
apk install erlang

# Get elixir + two patches
tar axf elixir-1.15.0.tar.gz 
cd elixir-1.15.0
curl -s https://github.com/elixir-lang/elixir/commit/73b65eca5af294a8afbed5bc73c178da18f0055c.diff | patch -p1
curl -s https://github.com/elixir-lang/elixir/commit/9b254e6830d0f44e26179582a16fef6f642df754.diff | patch -p1

# Build it
make -j

# Get the attachment + rename
wget https://github.com/elixir-lang/elixir/files/11860450/crash-beam-using-mix.txt
mv crash-beam-using-mix.txt crash-beam-using-mix.exs

# Clear kernel ring buffer (discarding current) -- so the segfault is easy to see
dmesg -c>/dev/null

# Crash the beam
./bin/elixir -pr crash-beam-using-mix.exs; dmesg -c
```

Output of the last command (last two lines are the segfault from `dmesg`):

```
Excluding tags: [windows: true]



  1) test --listen-on-stdin does not exit on compilation failure (Mix.Tasks.TestTest)
     /root/elixir-1.15.0/fail.exs:11
     ** (ExUnit.TimeoutError) test timed out after 5000ms. You can change the timeout:
     
       1. per test by setting "@tag timeout: x" (accepts :infinity)
       2. per test module by setting "@moduletag timeout: x" (accepts :infinity)
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. by running "mix test --timeout x" which sets timeout
       5. or by running "mix test --trace" which sets timeout to infinity
          (useful when using IEx.pry/0)
     
     where "x" is the timeout given as integer in milliseconds (defaults to 60_000).
     
     stacktrace:
       fail.exs:65: Mix.Tasks.TestTest.receive_until_match/3
       fail.exs:46: anonymous fn/0 in Mix.Tasks.TestTest."test --listen-on-stdin does not exit on compilation failure"/1
       (elixir 1.15.0) lib/file.ex:1624: File.cd!/2
       lib/mix/test/test_helper.exs:146: MixTest.Case.in_fixture/3
       fail.exs:12: (test)
       (ex_unit 1.15.0) lib/ex_unit/runner.ex:463: ExUnit.Runner.exec_test/2
       (stdlib 5.0.1) timer.erl:270: :timer.tc/2
       (ex_unit 1.15.0) lib/ex_unit/runner.ex:385: anonymous fn/5 in ExUnit.Runner.spawn_test_monitor/4


Finished in 5.2 seconds (0.2s on load, 0.00s async, 5.0s sync)
1 test, 1 failure

Randomized with seed 695396
[  278.317307] erts_sched_4[3171]: segfault at 7103 ip 000055a585eb9360 sp 00007efd80fdd570 error 4 in beam.smp[55a585c49000+337000] likely on CPU 1 (core 1, socket 0)
[  278.317320] Code: 00 00 00 48 c7 45 d8 00 00 00 00 48 8b 51 10 48 89 41 18 48 89 55 c0 48 85 d2 0f 84 87 07 00 00 66 2e 0f 1f 84 00 00 00 00 00 <48> 39 4a 18 0f 84 96 03 00 00 48 89 42 20 4c 8b 41 10 49 39 f0 0f
```

The output shows two notable things:

- There is a segfault in the beam.smp (last two lines, from the `dmesg -c`)
- Test failing after 5s (because beam segfaulted and is no longer responding on the port)

### Expected behavior

BEAM doesn't segfault, but that's probably not on Elixir team. ;)

So more relevant -- smaller amount of steps to reproduce (for the OTP team) is found, and reported on the [OTP Issue 7436](https://github.com/erlang/otp/issues/7436).

But obviously, if anyone manages to find out any additional faulty assumptions of mine, I'd be grateful. In the end, I just don't want the tests to intermittently fail on alpine. ;)

**Comment by josevalim** [comment]
Thank you for the excellent report on both sides and for breaking it down. You are right, this is not an Elixir bug per-se, so I will go ahead and close this, but I am also watching on the other side and I will reopen if anything changes. :heart:
