### ISSUE TITLE
make underscoring integers optional on formatter

### ISSUE THREAD

**Issue by sdancer** [elixir-lang/elixir#12712]
fourth year in a row making this request

motivation: our source contains a lot of ids, that are hard to lookup//xref with grep(and similar) either in the source, or in other places if they get underscored

**Comment by josevalim** [comment]
Please don't open up duplicate requests. Asking something for the fourth time is not an argument for us to change anything. And also please don't use the issues tracker for requests, as asked in the wizard.

If this is important to you, note that we will keep underscores as long as there is any, so you can write IDs as `0_32132789732891738921`.

**Comment by michallepicki** [comment]
Maybe https://github.com/marcandre/freedom_formatter would be open to add this feature

**Comment by sdancer** [comment]
not a duplicate issue through, previous times were asked over other channels such as irc, mail list, etc
