### ISSUE TITLE
IEx 1.15 fails to load module

### ISSUE THREAD

**Issue by meppu** [elixir-lang/elixir#12723]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:32:8] [ds:32:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.0 (compiled with Erlang/OTP 25)

*from https://www.reddit.com/r/elixir/comments/14kibkn/iex_does_not_load_module/, same issue with Erlang/OTP 26*

### Operating system

GNU/Linux (NixOS Unstable)

### Current behavior

IEx fails to load given module from CLI, learned about issue from [this reddit post](https://www.reddit.com/r/elixir/comments/14kibkn/iex_does_not_load_module/). First i though OP was doing something wrong and it was working on Elixir 1.14.5 with Erlang/OTP 25

Then i tried same thing with 1.15 and then i realized OP was right.

Here the video: https://www.youtube.com/watch?v=os-Nh1MGYhc
*i tried to press tab in video to get auto-complete but i didn't receive anything*

### Expected behavior

Expected behaviour (1.14.5): https://www.youtube.com/watch?v=5exkSXPnCjI

**Comment by josevalim** [comment]
@meppu can you please try main/v1.15 branches? I cannot reproduce the issue, so I believe it has been fixed. :)

**Comment by josevalim** [comment]
If the issue persists, please add a `IO.puts ...` to the file, so we confirm if the file is being executed or not. :)

**Comment by meppu** [comment]
Seems like with branch `v1.15` it is working :) Thanks!

![image](https://github.com/elixir-lang/elixir/assets/112294217/ff2f3ea4-126a-42f5-bbae-84cf607dd5bb)

**Comment by josevalim** [comment]
Thank you for reporting and confirming, very appreciated <3
