### ISSUE TITLE
String.valid? function is breaking with a non-string value

### ISSUE THREAD

**Issue by ViseLuca** [elixir-lang/elixir#12727]
### Elixir and Erlang/OTP versions

In Elixir 1.14.5 when passing a non-string value do the `String.valid?` function would be safe with this code:

```
...
 @spec valid?(t) :: boolean
  def valid?(string)

  def valid?(<<string::binary>>), do: valid_utf8?(string)
  def valid?(_), do: false
...
```

Now in Elixir 1.15 is returning with a breaking error for the code:

```
...
@spec valid?(t) :: boolean
  def valid?(string, algorithm \\ :default)

  def valid?(<<string::binary>>, :default), do: valid_utf8?(string)
  def valid?(<<string::binary>>, :fast_ascii), do: valid_utf8_fast_ascii?(string)
...
```
that expect always a binary. Why this change? 

If I pass to it a float, for example, before the response was `false` now is `** (FunctionClauseError) no function clause matching in String.valid?/2`. 

IMHO was correct `false` response because was not a string, why this change?

Maybe we can add again a pattern match for other types?

```
@spec valid?(t) :: boolean
  def valid?(string, algorithm \\ :default)

  def valid?(<<string::binary>>, :default), do: valid_utf8?(string)
  def valid?(<<string::binary>>, :fast_ascii), do: valid_utf8_fast_ascii?(string)
  def valid?(_, _), do: false
```

Thank you

### Operating system

OSX 13.4.1

### Current behavior

iex(1)> String.valid?(1, :default)
```
** (FunctionClauseError) no function clause matching in String.valid?/2    
    
    The following arguments were given to String.valid?/2:
    
        # 1
        1
    
        # 2
        :default
    
    Attempted function clauses (showing 2 out of 2):
    
        def valid?(<<string::binary>>, :default)
        def valid?(<<string::binary>>, :fast_ascii)
    
    (elixir 1.15.0) lib/string.ex:1827: String.valid?/2
    iex:1: (file)

```

### Expected behavior

iex(1)> String.valid?(1, :default)
false

**Comment by josevalim** [comment]
The previous behaviour was an accident but [the spec](https://hexdocs.pm/elixir/1.14.3/String.html#valid?/1) denoted only strings were expected. Please explicitly check for is_binary(...) before calling String.valid?. Thank you.

**Comment by whatyouhide** [comment]
The response was incorrect in previous versions according to the spec, because the spec has said that this function takes a `String.t()` since Elixir 1.0. So, if you pass something that is not a string, it is not documented to work.

**Comment by ViseLuca** [comment]
Thank you both!
