### ISSUE TITLE
`capture_log/2` options no longer affect captured log output when ExUnit configured to `capture_log: true`

### ISSUE THREAD

**Issue by msz** [elixir-lang/elixir#12720]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.15.0 (compiled with Erlang/OTP 25)

### Operating system

macOS 13.3.1 (a) 

### Current behavior

When ExUnit is configured to `capture_log: false`, options in `ExUnit.CaptureLog.capture_log/2` calls correctly affect captured log output.

When ExUnit is configured to `capture_log: true`, options in `ExUnit.CaptureLog.capture_log/2` calls don't affect captured log output and defaults are used.

This seems to have changed since Elixir 1.14.5. See https://github.com/msz/capture_log_config_reproduction for a reproduction of the issue.

### Expected behavior

When ExUnit is configured to `capture_log: false`, options in `ExUnit.CaptureLog.capture_log/2` calls correctly affect captured log output.

When ExUnit is configured to `capture_log: true`, options in `ExUnit.CaptureLog.capture_log/2` calls correctly affect captured log output.

**Comment by sabiwara** [comment]
I think it was introduced with [this change](https://github.com/elixir-lang/elixir/commit/8405180ebc8ff3c845f174135e38870c9689f813#diff-8c44117b9ff11f42ee4c114e8b82fab49470961aab1b1c20684e5ff901a98a08R76-R78), and what happens is that `log_capture_on` gets called twice:
- first with `opts: []`, `refs` becomes of size 1, setup handler with formatter
- second with passed `opts`, `refs` size 2, skipping the handler setup

I'm not familiar enough with `:logger` to figure out what should be done in this case. Should we remove the existing handler and replace it?

Here is a test reproducing the issue: https://github.com/elixir-lang/elixir/pull/12721
