### ISSUE TITLE
Potential bug with mix aliases in Elixir 1.15.1

### ISSUE THREAD

**Issue by Miradorn** [elixir-lang/elixir#12738]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.15.1 (compiled with Erlang/OTP 26)

### Operating system

MacOs 13.4.1

### Current behavior

example minimal repro: https://github.com/Miradorn/hex-audit-minimal-repro

run `mix lint`, it will complain that `hex.audit` is not available.
if you change the order in the alias to first run `hex.audit` everything works.

Also quite possible I'm doing smth wrong here :D

Thanks for any help and all your work ❤️ 

### Expected behavior

both tasks should be run

**Comment by wojtekmach** [comment]
Perhaps apps that are not explicitly specified get unloaded after the first Mix task run?

FWIW this issue can be solved by adding `:hex` to `:extra_applications`, e.g.

```elixir
def application do
  [
    extra_applications: [:logger] ++ extra_applications(Mix.env())
  ]
end

defp extra_applications(env) when env in [:dev, :test], do: [:hex]
defp extra_applications(_), do: []
```

**Comment by josevalim** [comment]
Correct! Once your application compiled, the load path is pruned, then you won’t find previous deps/apps unless you list them as Wojtek mentioned. :) if this is confusing we may need to come up with alternative strategies.

**Comment by Miradorn** [comment]
thanks for the solution/workaround!
To me at least it felt surprising, especially since it works when being the first command. Maybe a pointer in the docs (and an update of the scaffolded mix.exs file on new projects?) might help!

❤️
