### ISSUE TITLE
Maybe code path pruning issue

### ISSUE THREAD

**Issue by 0urobor0s** [elixir-lang/elixir#12745]
### Elixir and Erlang/OTP versions

Elixir 1.15.2 (compiled with Erlang/OTP 26)

### Operating system

macOS and Debian 12

### Current behavior

In a project, we have some code that uses the [apply/3](https://hexdocs.pm/elixir/1.12.3/Kernel.html#apply/3) function to invoke two functions created by the `Phoenix.Component` [embed_templates/1](https://hexdocs.pm/phoenix_live_view/Phoenix.Component.html#embed_templates/1), one for the html and the other for the text version.

When upgrading from Elixir v1.14 to Elixir v1.15 the `mix test` command started failing, but only after the first time it's called.
Outside of the test environment, the code works both in development and in production.

We've created an [example project](https://github.com/0urobor0s/t_cache) which shows this issue.
To reproduce, clone the repository and run `for i in {1..2}; do mix test; done` which should work in the first run and fail in the second with the error (it can also be the text version):
```
  1) test cache_component/1 (TCacheTest)
     test/t_cache_test.exs:9
     ** (ArgumentError) errors were found at the given arguments:

       * 1st argument: not an already existing atom

     code: assert {%Phoenix.LiveView.Rendered{static: [""]}, ""} = TCache.cache_component("mail")
     stacktrace:
       :erlang.binary_to_existing_atom("mail_html", :utf8)
       (t_cache 0.1.0) lib/t_cache.ex:15: TCache.cache_component/1
       test/t_cache_test.exs:10: (test)
```

When running with `iex -S mix test` the results are:
```
iex (1) > String.to_existing_atom("mail_html")
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

    :erlang.binary_to_existing_atom("mail_html", :utf8)
    iex:1: (file)

iex (1) > String.to_existing_atom("mail_text")
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not an already existing atom

    :erlang.binary_to_existing_atom("mail_text", :utf8)
    iex:1: (file)

iex (1) > TCacheWeb.Email.__info__(:functions)
[__mix_recompile__?: 0, mail_html: 1, mail_text: 1]
# ^ which makes the String.to_existing_atom runs work
```

Either removing the whole `_build/test` or the cache files (although this creates warnings) makes the test work again for the first run. Also running the `mix test` command with the `--cover` option (`mix test --cover`) seems to work and not trigger the issue.

As stated in the Elixir v1.15 [changelog](https://github.com/elixir-lang/elixir/blob/v1.15/CHANGELOG.md), adding `prune_code_paths: false` to the `mix.exs` file seems to fix the issue.

In the [example project](https://github.com/0urobor0s/t_cache), the likely "interesting" files are:
- [lib/t_cache.ex](https://github.com/0urobor0s/t_cache/blob/main/lib/t_cache.ex)
- [test/t_cache_test.exs](https://github.com/0urobor0s/t_cache/blob/main/test/t_cache_test.exs)
- [lib/t_cache_web/components/email.ex](https://github.com/0urobor0s/t_cache/blob/main/lib/t_cache_web/components/email.ex)

PS: This doesn't seem to be an issue when having a [simple example](https://github.com/0urobor0s/t_cache/blob/main/lib/t_cache.ex#L10), as it could only be seen in the Phoenix.Component created functions. The decision to create an issue here was due to the Elixir version change causing this new behaviour, however let us know if this issue should have been created in the Phoenix repository instead.

### Expected behavior

Expect `mix test` to finish without failures in all test runs:
```
.......
Finished in 0.1 seconds (0.07s async, 0.1s sync)
7 tests, 0 failures
```

**Comment by josevalim** [comment]
This is expected and it can happen in any Elixir version. An atom is only available after the module that defines it is loaded. Therefore you should only instantiate atoms within the module they are defined. Otherwise you are going to have race conditions based if a module has been loaded or not. :)

the docs also discuss this: https://hexdocs.pm/elixir/main/String.html#to_existing_atom/1

**Comment by 0urobor0s** [comment]
Thank you for the quick reply. I was under the impression that the modules functions (atoms) were loaded when running `mix test`. It seems the assumption was mistaken.

```
$ iex -S mix test
iex (1) > :code.module_status(TCacheWeb.Email)
:not_loaded
```

Glad that the version upgrade uncovered this issue.
