### ISSUE TITLE
Move official guides into the Elixir repository

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#12747]
When this happens, the "Writing Documentation" should be part of the guides and not part of the "References".

**Comment by josevalim** [comment]
Once we are done, we should also remove all references to "elixir-lang.org/getting-started" from this project and also set up redirects from elixir-lang.org to hexdocs.pm/elixir/main.

**Comment by josevalim** [comment]
We are missing the Mix and OTP guides which @whatyouhide will transfer (if for any reason you can no longer do it, let me know). :)

**Comment by whatyouhide** [comment]
I'm on in this weekend, no worries 👍

**Comment by josevalim** [comment]
@whatyouhide I believe the remaining step is to have the website point to hexdocs.pm. But I guess we should do it once v1.16 is out.

**Comment by whatyouhide** [comment]
@josevalim yeah, we can set the 302 redirect on elixir-lang.org once the guides will be at hexdocs.pm/elixir, which now points to 1.15.2 🙃

**Comment by whatyouhide** [comment]
I would personally close this issue and add an issue to elixir-lang.org's repo.

**Comment by josevalim** [comment]
PR here: https://github.com/elixir-lang/elixir-lang.github.com/pull/1738
