### ISSUE TITLE
iex hangs on startup (Windows) and possible fix

### ISSUE THREAD

**Issue by ptome** [elixir-lang/elixir#12740]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.1 (compiled with Erlang/OTP 26)
```

### Operating system

Windows 10 21H2 (build 19044.3086)

### Current behavior

When starting iex in a command shell, it hangs on startup.  I can still CTRL+C and abort:

```
C:\Code\elixir\test>iex

BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
Terminate batch job (Y/N)? Y
```
Executing a dry run, it shows elixir.bat is using runMode with start_cli value:

```
C:\Code\elixir\test>set ELIXIR_CLI_DRY_RUN=1

C:\Code\elixir\test>iex
"erl.exe"    -noshell -elixir_root "C:\Tools\elixir\bin\..\lib" -pa "C:\Tools\elixir\bin\..\lib\elixir\ebin" -s elixir start_cli  -user elixir -extra  --no-halt +iex
```

### Expected behavior

I believe the correct runMode should be start_iex.  If I change the comparison on elixir.bat, line 167, from:

`if !runMode! == "iex" (`

to

`if %runMode% == "iex" (`

the dry run shows:

```
C:\Code\elixir\test>iex
"erl.exe"    -noshell -elixir_root "C:\Tools\elixir\bin\..\lib" -pa "C:\Tools\elixir\bin\..\lib\elixir\ebin" -s elixir start_iex  -user elixir -extra  --no-halt +iex
```

And the final test, it now works:
```
C:\Code\elixir\test>set ELIXIR_CLI_DRY_RUN=

C:\Code\elixir\test>iex
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

If my understanding is correct, this was introduced with commit https://github.com/elixir-lang/elixir/pull/12697/commits/74d085ca28565332c23445fcb0e06097b7dcce8b

Unfortunately I don't know enough about Windows batch files and enabledelayedexpansion to know why it needs this change.

**Comment by josevalim** [comment]
This is very weird. Can you please try the version in 0929a431d432f842e2e0e84d5a32b3821c9d3129? I don't understand why delayed expansion cannot be used here but maybe it is best to not use it at all.

**Comment by ptome** [comment]
> This is very weird. Can you please try the version in [0929a43](https://github.com/elixir-lang/elixir/commit/0929a431d432f842e2e0e84d5a32b3821c9d3129)? I don't understand why delayed expansion cannot be used here but maybe it is best to not use it at all.

It works with the new version (variable definition).  Thank you José!
