### ISSUE TITLE
Mix release remote command not working in > 1.15.0

### ISSUE THREAD

**Issue by rodrigues** [elixir-lang/elixir#12757]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.1 (compiled with Erlang/OTP 25)

(problem also reproduced in 1.15.2, worked in 1.15.0)

### Operating system

macOS Ventura, Alpine 3.18.2

### Current behavior

Release remote shell gets stuck:

```fish
mix new testapp --sup
cd testapp
mix release
_build/dev/rel/testapp/bin/testapp start
```

in another shell:

```fish
_build/dev/rel/testapp/bin/testapp remote

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

```

(the shell prompt isn't shown)

### Expected behavior

As with Elixir `<= 1.5.0`, show the prompt:

```fish
❯ _build/dev/rel/testapp/bin/testapp remote
Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Interactive Elixir (1.15.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(testapp@XYZ)1> 
```

Thanks!

**Comment by rodrigues** [comment]
Oh, now I see this one https://github.com/elixir-lang/elixir/issues/12746, is it fixed?

**Comment by josevalim** [comment]
Yes. It should also work on latest Elixir + Erlang/OTP 26.
