### ISSUE TITLE
Every httpc request fails

### ISSUE THREAD

**Issue by mpopovic-ax** [elixir-lang/elixir#12770]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.15.2 (compiled with Erlang/OTP 26)

### Operating system

Ubuntu 22.04.2 LTS

### Current behavior

I'm using [asdf](https://asdf-vm.com/) to install latest Elixir with Erlang. However, after that process I'm encountering an issue where I can't install any dependency because `httpc` can't establish connection to any server for some reason:
```bash
$ mix local.hex --force
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {~c"builds.hex.pm", 443}}, {:inet6, [:inet6], :nxdomain}]}

Could not install Hex because Mix could not download metadata at https://builds.hex.pm/installs/hex-1.x.csv.
```
Currently, I don't have IPv6 support with my Internet provider, however after testing it manually on IPv4 address, seems like that doesn't work either:
```elixir
iex(1)> :inets.start
:ok
iex(2)> :ssl.start
:ok
iex(3)> :httpc.request 'https://elixir-lang.org'
{:error,
 {:failed_connect,
  [{:to_address, {~c"elixir-lang.org", 443}}, {:inet, [:inet], :nxdomain}]}}
```
I've previously spent my time on Google and tried various suggestions, even compiling Erlang/OTP with some `kerl` flags - because I've found the problem could also be OpenSSL version incompatibility, but nothing has helped so far. I've run out of options.

Strangely, everything works fine (Hex and everything else installs normally) on my Windows 11 machine with WSL 2 with the same setup (also using Ubuntu there).

**Comment by paulo-ferraz-oliveira** [comment]
Same.

I have a bit more info on the shell, though

```
18:24:39.737 [warning] Description: 'Server authenticity is not verified since certificate path validation is not enabled'
     Reason: 'The option {verify, verify_peer} and one of the options \'cacertfile\' or \'cacerts\' are required to enable this.'

{:error,
 {:failed_connect,
  [{:to_address, {'elixir-lang.org', 443}}, {:inet, [:inet], :nxdomain}]}}
```

---

If you try

```elixir
:httpc.request(:get, {'https://elixir-lang.org', []}, [ssl: :httpc.ssl_verify_host_options(true)], [])
```

does it work?

**Comment by mpopovic-ax** [comment]
I'm getting the same error with that command.

**Comment by josevalim** [comment]
What does `:public_key.cacerts_get()` return for both of you? Perhaps it cannot find certificates on Ubuntu for some reason?

**Comment by mpopovic-ax** [comment]
Actually it returns me a bunch of certificates (it's huge output so I won't paste it here)

**Comment by paulo-ferraz-oliveira** [comment]
I'm on Mac, if that's relevant. `:public_key.cacerts_get()` is the same for me: returns a bunch of certificates.

**Comment by josevalim** [comment]
Could you have any sort of global configuration that is forcing httpc to behave different? Maybe any flags on ERL_AFLAGS or ERL_ZFLAGS env var?

**Comment by mpopovic-ax** [comment]
No, I don’t have such flags set.

**Comment by wojtekmach** [comment]
:nxdomain looks like a network maybe? Does other http clients work for you? How about:

```elixir
Mix.install([:mint, :castore])
Mint.HTTP.connect(:https, "erlang.org", 443)
```

**Comment by wojtekmach** [comment]
I believe :nxdomain can happen when you talk to ipv6-only host on ipv4 and vice versa, so I’d focus on those. Certs stuff, while also important of course, might be red herring. OS certs issues can probably be overcome with :castore package shown above.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... to me, using the OP's instructions, this is now working, i.e. (some stuff cut out for readability)

```elixir
iex(1)> :inets.start
:ok
iex(2)> :ssl.start
:ok
iex(3)> :httpc.request 'https://elixir-lang.org'

16:20:05.650 [warning] Description: ~c"Server authenticity is not verified since certificate path validation is not enabled"
     Reason: ~c"The option {verify, verify_peer} and one of the options 'cacertfile' or 'cacerts' are required to enable this."

{:ok,
 {{~c"HTTP/1.1", 200, ~c"OK"},
  [
    "<a buncha headers>"
  ],
  ~c"<!DOCTYPE html>
<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\">
<head>
  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />
    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />
      <meta name=\"description\" content=\"Welcome to Elixir, a dynamic, functional language designed for building scalable and maintainable applications\">
        <title>The Elixir ...
```

**Comment by mpopovic-ax** [comment]
@wojtekmach well I can't install any dependency, because Mix itself is not working due to `httpc` failing.

**Comment by wojtekmach** [comment]
doh, sorry about that. Does `:ssl.connect('builds.hex.pm', 443, [])` work? And other hosts?

**Comment by mpopovic-ax** [comment]
```elixir
iex(3)> :ssl.connect('builds.hex.pm', 443, [])
{:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}
iex(4)> :ssl.connect('google.com', 443, [])   
{:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}
```

**Comment by wojtekmach** [comment]
And

```elixir
:ssl.connect('google.com', 443, [cacerts: :public_key.cacerts_get()])
```

?

**Comment by mpopovic-ax** [comment]
```elixir
iex(5)> :ssl.connect('google.com', 443, [cacerts: :public_key.cacerts_get()])
{:error, :nxdomain}
```

**Comment by rubin55** [comment]
This looks vaguely like issues I've been having in combination with OpenSSL 3.x, which dropped various "legacy" ciphers and which changed the default behavior regarding `UnsafeLegacyRenegotiation` and `UnsafeLegacyServerConnect`.

@mpopovic-ax : which version of OpenSSL is erlang linked against c.q. what does your system have? Same question to @paulo-ferraz-oliveira

I might be completely off the mark.

**Comment by paulo-ferraz-oliveira** [comment]
I'm on macOS. My OpenSSL is linked (local Erlang compile via `kerl`) to openssl@1.1, from `brew`.

**Comment by josevalim** [comment]
Closing this for now, as it seems to be a system issue, external to Elixir itself. Thank you!
