### ISSUE TITLE
Change in the behaviour of Kernel.function_exported? when updating from 1.14 to 1.15?

### ISSUE THREAD

**Issue by tarzan** [elixir-lang/elixir#12779]
### Elixir and Erlang/OTP versions

Elixir 1.15.2
Erlang 26.0.1

### Operating system

MacOS 13.4.1

### Current behavior

I have some module MyApp.MyModule and on first run of the app the following works as expected:
```ex
❯ iex -S mix                      
Compiling 1 file (.ex)

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Interactive Elixir (1.15.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Kernel.function_exported?(MyApp.MyModule, :__info__, 1)
true
iex(2)> MyApp.MyModule.__info__(:module)
MyApp.MyModule
iex(3)> MyApp.MyModule.__info__(:functions)
[]
```
while starting it a second time:
```ex
❯ iex -S mix
Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Interactive Elixir (1.15.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Kernel.function_exported?(MyApp.MyModule, :__info__, 1)
false
iex(2)> MyApp.MyModule.__info__(:module)
MyApp.MyModule
iex(3)> MyApp.MyModule.__info__(:functions)
[]
```

### Expected behavior

I would expect them both to return `true` on `function_exported?/1`.

**Comment by josevalim** [comment]
The behaviour did not change, you were most likely relying on a side effect. The function documentation says:

> Note that this function does not load the module in case it is not loaded.
> Check `Code.ensure_loaded/1` for more information.

So it is not guaranteed the module has been loaded before and, if you are not checking if it is loaded, you were relying on someone else loading it as a side-effect. Your previous code v1.14 could still fail in other ways. So add the ensure_loaded? and you should be good.
