### ISSUE TITLE
Suggestion: clarify upgrade path for `Regex.regex?/1`

### ISSUE THREAD

**Issue by thbar** [elixir-lang/elixir#12785]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.15.2 (compiled with Erlang/OTP 24)

### Operating system

Mac OS

### Current behavior

In Elixir 1.15, `Regex.regex?/1` is deprecated. An upgrade path is suggested here:

https://hexdocs.pm/elixir/1.14.5/Regex.html#regex?/1

> Use Kernel.is_struct/2 or pattern match on %Regex{} instead.

I find that the hint provided is not explicit enough for people faced with this the first time.

Ultimately what seems to work is indeed logical:

```elixir
iex(1)> Kernel.is_struct(~r/something/, Regex) 
true
iex(2)> Kernel.is_struct("something", Regex)   
false
```

This works because `Regex` is itself a `Struct` (https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/regex.ex#L156).

### Expected behavior

I would have found the following (or something similar) to be more helpful:

> Use Kernel.is_struct(xyz, Regex) or pattern match on %Regex{} instead.

I would be happy to help clarify this with a PR of some sort (but unsure if it should target Elixir 1.14, or the upgrade matrix etc).

**Comment by josevalim** [comment]
Please PR and it can target main. :)
