### ISSUE TITLE
`Code.Typespec.fetch_types` always returns `:error` for module in `mix test`

### ISSUE THREAD

**Issue by shahryarjb** [elixir-lang/elixir#12787]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.1 (compiled with Erlang/OTP 26)
```

### Operating system

MacOS

### Current behavior

Hello, `Code.Typespec.fetch_types` function works very well for `Protocol`, but it does not work with module binary in Elixir 1.15.1 and otp 26, it seems works in pervious Elixir and otp version.

# Example:

```elixir
  {:module, _name, bytecode, _exports} =
    defmodule OpaqueTestStruct do
       @type t :: any
    end

  Code.Typespec.fetch_types(bytecode)
  # It returns :error
  
  # OR
```

But if you test it with `protocol`, it works and returns the type.

```elixir
  {_, _, sample_binary, _} =
    defprotocol Sample do
      @type t :: any
      @doc "Ok"
      @deprecated "Reason"
      @spec ok(t) :: boolean
      def ok(term)
    end

 Code.Typespec.fetch_types(sample_binary)
```

> ### It should be noted, all the thing works in `ex` and `iex`, but it does not work in `mix test` and test files

---

### Expected behavior

I know it is false doc module and there’s no backwards compatibility guarantee, but I saw you are using it inside elixir code and there is no another way to check module types, Am I right?

https://github.com/elixir-lang/elixir/blob/main/lib/elixir/test/elixir/typespec_test.exs#L10-L28

So, I think this erlang function is used in elixir code can be match with the pattern

```elixir
:beam_lib.chunks(bytecode, [:debug_info])
```
So it does not passed and returns `:error`, I found it here
https://github.com/elixir-lang/elixir/blob/7858bac32b80d887fd4e672288a2fa43b40daeb3/lib/elixir/lib/code/typespec.ex#L156-L174

I have no knowledge from erlang to fix it and send pull request, sorry! ☹️

For reproducing this problem you can test this library one of the useful library in elixir for struct and it is simple project
https://github.com/ejpcmac/typed_struct

----
## I could not be able to find another function to check is there the type we put it inside module or not? I really need a function to pass it to test my project

Thank you in advance
> I would really like to be able to solve this problem, if it really is a problem, I would do something to help improve it, but my Erlang literacy is very low.

**Comment by shahryarjb** [comment]
Dear @josevalim, it works in `iex` and in a `ex` file no problem in runtime, but when I use it inside a test file, for example
in this path `test/guarded_struct_test.exs` and run `mix test` you can see it returns `:error`.

> make sure debug_info i not disabled in your project.
I did not change anything, create elixir project with `mix new a_name` and test

I created a very simple elixir project in this url
https://github.com/shahryarjb/fetch_types

I just have this file: `test/fetch_types_test.exs` without any another code. and run `mix test`

https://github.com/shahryarjb/fetch_types/blob/master/test/fetch_types_test.exs#L4-L13

I record a short video to test. please see it

https://github.com/elixir-lang/elixir/assets/8413604/ae60818a-d6ba-46eb-8feb-65d251b72114


I hope you will always be healthy

**Comment by josevalim** [comment]
Add this to your mix.exs under def project:

    test_elixirc_options: [debug_info: true]

debug_info and docs are disabled by default in tests for performance. :)

**Comment by shahryarjb** [comment]
Thank you.
Dear @josevalim 
If you agree, I should add this note to the `Code.Typespec.fetch_types` documentation. and send a pull request?
