### ISSUE TITLE
Mix Release `remote` command fails/hangs on 1.15.2 OTP 25

### ISSUE THREAD

**Issue by Billzabob** [elixir-lang/elixir#12791]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.2 (compiled with Erlang/OTP 25)

### Operating system

macOS Ventura 13.4.1

### Current behavior

Running the mix release `remote` command hangs right after printing out OTP version.

### Steps to reproduce
```bash
# Elixir 1.15.2 OTP 25
mix phx.new my_app
cd my_app
mix deps.get
MIX_ENV=prod mix release
export DATABASE_URL=ecto://postgres:postgres@localhost/my_db
export SECRET_KEY_BASE=T+B3JlTD8HxvlLiUM8zjfsAwJh/ZFAVbP+6omJksTJck7WH4m2F/0Av8sde+tiMw
export PHX_SERVER=true
_build/prod/rel/my_app/bin/my_app start_iex

# Then in another terminal
_build/prod/rel/my_app/bin/my_app remote
```

Notably, it works just fine with Elixir 1.15.2 and OTP 26

### Expected behavior

Connect to the remote server with an iex shell without hanging.

**Comment by josevalim** [comment]
This has been fixed in the v1.15 branch and will be addressed on Elixir v1.15.3. Thanks!
