### ISSUE TITLE
Inconsistent arithmetics with recursion when running on docker/vm with multiple cpu

### ISSUE THREAD

**Issue by RobPando** [elixir-lang/elixir#12795]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.0 (compiled with Erlang/OTP 26)

On DOCKER:
ELIXIR_VERSION=1.15.3
OTP_VERSION=26.0.2

### Operating system

debian:bullseye-20230612-slim

### Current behavior

So this is my last stop to figure this issue out which seems to be a compiler issue on the different vm. 
When I run a simple phoenix app with the following module
```elixir
defmodule TestCurvy.Util do
  # Recursive inv function
  def inv_op(lm, hm, low, high) when low > 1 do
    r = div(high, low)
    inv_op(hm - lm * r, lm, high - low * r, low)
  end

  def inv_op(lm, _hm, _low, _high), do: lm
end
```
and I run something like this `TestCurvy.Util.inv_op(1, 0, 85715544340734810568335997580837940913292120770256072394575581398011106779447, 115792089237316195423570985008687907853269984665640564039457584007908834671663)`
Locally I get the CORRECT output which is: `23540938214369567692016788189744227367858201159418889382729252922507896748155`

However running this on a docker container (I found this out from running in fly.io but can reproduce locally) something happens to the arithmetics along the way get out of wack and I get this output `-12386495990679745160386149006720629616816317566663855265396018338693106960261`

I tried tracking it and I dont know why but along the way `hm - lm * r` trips up within the recursion to where `hm` is not calculated it just rolls with `lm*r` weirdest thing.  I have this test app https://github.com/RobPando/test-fly-curvy-issue
If this is run locally it will give the correct output but if you build it via docker with the following steps:
1. `docker build . --tag roberto:latest`
2. `docker run -e DATABASE_URL=file:///foo.sqlite -e SECRET_KEY_BASE=whatevs -p 8000:8000 roberto:latest`
3.  `docker ps` => to get CONTAINER ID
4. docker exec -it CONTAINER_ID /app/bin/test_fly_curvy_app remote

Then run the function I mention you will get the wrong output.

I thought it was a phoenix issue since copying and pasting the module above directly to iex inside the docker container does spit out. the correct output, however it was pointed out to me that these compile differently so now I am back to it being a compiler issue. Also I tried it on fly with 1 CPU and it gives the correct output, anything above 1 gives the wrong one. 

### Expected behavior

Consistency across environment.

**Comment by josevalim** [comment]
Thanks for the report. This is definitely a bug somewhere even lower down the stack. Can you please try Erlang/OTP 26.0.2? Also, if it only happens in Docker, it may be an emulation bug too.

Given you can reproduce it with a single module, can you try doing a simple image with Elixir that does `elixir path/to/script.exs` that defines the module and invokes it? Can that reproduce it?

Further breaking it down will help report it upstream. (Also, is Debian the system OS or your own OS?).

**Comment by RobPando** [comment]
@josevalim thanks for the quick response! really appreciate it. So I tried Erlang/OTP 26.0.2 and the issue persisted. I tried the `.exs` file idea stuffed it in the docker build to be called it and that gives the right output. As an additional check I also called the module on the `.ex` file on the start application function just for sanity check and that give the wrong output upon start of the app.

`debian:bullseye-20230612-slim` is the docker runner image (using the default docker file generated by fly.io for phoenix apps). I think it is worth reiterating that when placed on a 1cpu vm the output is the correct one, the wrong output starts on a vm with a cpu greater than 1. my local machine is MacOS 13.4.1 (22F82).

**Comment by josevalim** [comment]
Thank you, it was indeed an Elixir bug. I appreciate the isolation, it helped a lot :)

**Comment by RobPando** [comment]
Of course @josevalim ! is there anywhere I can track the fix? also I am not sure if this matters but in my debugging I pulled out the beam file from the docker file and compared it to what it compiles locally and there is a difference to where compiler info is undefined in the beam file from the docker image (where the issue is). Thank you once again!

**Comment by josevalim** [comment]
This has been fixed in Elixir as well (and in the next Elixir version).
