### ISSUE TITLE
Error on running 'make test'

### ISSUE THREAD

**Issue by gbmoretti** [elixir-lang/elixir#128]
Sorry if here isn't the right place for questions. But i'm getting the following error when trying to run "make test"

```
Uncaught error in rebar_core: {'EXIT',
                               {undef,
                                [{crypto,start,[],[]},
                                 {rebar,run_aux,1,[]},
                                 {rebar,main,1,[]},
                                 {escript,run,2,
                                  [{file,"escript.erl"},{line,727}]},
                                 {escript,start,1,
                                  [{file,"escript.erl"},{line,277}]},
                                 {init,start_it,1,[]},
                                 {init,start_em,1,[]}]}}
make: ** [deps] Erro 1
```

Erlang version:

```
Erlang R15B (erts-5.9) [source] [smp:4:4] [async-threads:0] [kernel-poll:false]
```

I'm using in Ubuntu 11.10

**Comment by zaidshaikh112** [comment]
how did it was resolved the issue my friend

**Comment by OvermindDL1** [comment]
> how did it was resolved the issue

Usually better to ask questions like this at https://elixirforum.com/ as this is primarily for issue tracking.  :-)

However, they solved it either by recompiling erlang with all modules (or at least with the crypto module added), or they reinstalled from their packaging system.
