### ISSUE TITLE
Alternative for blake2b on systems that do not support that hash function?

### ISSUE THREAD

**Issue by VlkrS** [elixir-lang/elixir#12809]
blake2b is not supported on all platforms that can run Erlang, i.e. those building with LibreSSL rather than OpenSSL.

Would it be possible to fall back to a different hash or even a checksum for that purpose? As far as I understand this is only needed to detect changes for recompilation and actually requires none of the security properties of a cryptographic hash?

https://github.com/elixir-lang/elixir/blob/7c1cc52c869fdc97cd43eb8f2a6acbb0b1742861/lib/mix/lib/mix/compilers/elixir.ex#L454

**Comment by josevalim** [comment]
What error do you get in those cases?

**Comment by VlkrS** [comment]
```
** (ErlangError) Erlang error: {:notsup, {~c"hash.c", 112}, ~c"Digest type not supported in this cryptolib"}
```

in Mix.Tasks.DepsTest - patching those lines to use :sha26 works.
