### ISSUE TITLE
module :crypto is not available in a NIF project, on OTP 26 and elixir v1.15

### ISSUE THREAD

**Issue by Ljzn** [elixir-lang/elixir#12817]
### Elixir and Erlang/OTP versions

Erlang/OTP OTP-26.0.2 - built on ubuntu-22.04
Using Elixir v1.15.2 (built for Erlang/OTP 26)

### Operating system

ubuntu-22.04

### Current behavior

I'm use github action CI to run test for a NIF project. When use OTP26 there is a error "module :crypto is not available"

https://github.com/Ljzn/libsecp256k1/actions/runs/5640863813/job/15278076461

Using former version like OTP24 and Elixir v1.14.2, everything works fine.

https://github.com/Ljzn/libsecp256k1/actions/runs/5640915310/job/15278206566

### Expected behavior

module :crypto is available on OTP26

**Comment by josevalim** [comment]
You must list crypto as an extra application: https://github.com/Ljzn/libsecp256k1/pull/1
