### ISSUE TITLE
Docs: "Inlined by the compiler" is potentially misleading

### ISSUE THREAD

**Issue by zachallaun** [elixir-lang/elixir#12810]
### Elixir and Erlang/OTP versions

main 

### Operating system

N/A

### Current behavior

Some public functions include the note "Inlined by the compiler." Multiple examples in the `Map` module specifically:

- https://hexdocs.pm/elixir/main/Map.html#delete/2
- https://hexdocs.pm/elixir/main/Map.html#fetch/2
- etc...

### Expected behavior

According to the [compile options docs](https://hexdocs.pm/elixir/main/Module.html#module-compile-options), inlining is module-local. So while documentation that certain functions are inlined isn't factually incorrect, it's somewhat misleading: the inlining only applies to internal usage within that module. 

This isn't a "big deal," but it seems like it's documenting an implementation detail, may confuse some users, and clutters the documentation somewhat. 

Edit: unless this is an inlining that's cross-module and not related to the compile option?

**Comment by sabiwara** [comment]
> I believe this is a different inlining than that available in the compile options.

Correct. It is explained [here](https://hexdocs.pm/elixir/Kernel.html#module-inlining).

**Comment by zachallaun** [comment]
Thank for and apologies for the pings!
