### ISSUE TITLE
Code examples in mix help escript.build have wrong indentation

### ISSUE THREAD

**Issue by gmile** [elixir-lang/elixir#12840]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.1 (compiled with Erlang/OTP 24)

### Operating system

macOS 13.3 (22E252)

### Current behavior

In terminal, code examples at the bottom of `mix help escript.build` output appear to have wrong indentation. 

```
## Example

  • mix.exs:
    defmodule MyApp.MixProject do

        use Mix.Project

        def project do
          [
            app: :my_app,
            version: "0.0.1",
            escript: escript()
          ]
        end

        def escript do
          [main_module: MyApp.CLI]
        end

    end


  • lib/cli.ex:
    defmodule MyApp.CLI do

        def main(_args) do
          IO.puts("Hello from MyApp!")
        end

    end
```

<details>
  <summary>Screenshot</summary>
 
  <img width="424" alt="image" src="https://github.com/elixir-lang/elixir/assets/207112/c143ebb8-f4be-424f-99c1-72d234754fb7">
</details>

### Expected behavior

Output in terminal looks something like this:

```
## Example

  • mix.exs:

      defmodule MyApp.MixProject do
        use Mix.Project

        def project do
          [
            app: :my_app,
            version: "0.0.1",
            escript: escript()
          ]
        end

        def escript do
          [main_module: MyApp.CLI]
        end
      end


  • lib/cli.ex:

      defmodule MyApp.CLI do
        def main(_args) do
          IO.puts("Hello from MyApp!")
        end
      end
```

<details>
  <summary>Screenshot (prepared using vim)</summary>
 
  <img width="420" alt="image" src="https://github.com/elixir-lang/elixir/assets/207112/cde4e5c4-44e5-472f-9b7d-27604db65b7d">
</details>

I did try to make it look nicer by wrapping the [code blocks](https://github.com/elixir-lang/elixir/blob/v1.15.1/lib/mix/lib/mix/tasks/escript.build.ex#L104-L130) into ticks and playing with indentation, but all my attempts failed miserably.

**Comment by wojtekmach** [comment]
I think the markdown is slightly wrong indeed. (Elixir uses a hand rolled markdown output formatter.) IMHO we should either:

option 1:

```markdown
  ## Example

    * `mix.exs`:

          defmodule MyApp.MixProject do
            use Mix.Project

            def project do
              [
                app: :my_app,
                version: "0.0.1",
                escript: escript()
              ]
            end

            def escript do
              [main_module: MyApp.CLI]
            end
          end

    * `lib/cli.ex`:

          defmodule MyApp.CLI do
            def main(_args) do
              IO.puts("Hello from MyApp!")
            end
          end
```

<img width="369" alt="image" src="https://github.com/elixir-lang/elixir/assets/76071/947d6656-b406-42c9-9d3b-d1662007df1f">

option 2:

```markdown
  ## Example

  `mix.exs`:

      defmodule MyApp.MixProject do
        use Mix.Project

        def project do
          [
            app: :my_app,
            version: "0.0.1",
            escript: escript()
          ]
        end

        def escript do
          [main_module: MyApp.CLI]
        end
      end

  `lib/cli.ex`:

      defmodule MyApp.CLI do
        def main(_args) do
          IO.puts("Hello from MyApp!")
        end
      end
```

<img width="323" alt="image" src="https://github.com/elixir-lang/elixir/assets/76071/a15cf999-921a-490a-9596-dfe3cca1cc76">

I think option 2 is nicer.

**Comment by gmile** [comment]
FWIW 2nd option looks like :+1:
