### ISSUE TITLE
Code.Fragment.cursor_context and var calls

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12845]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

Those examples work
```
Code.Fragment.cursor_context("asd.a")
{:dot, {:var, ~c"asd"}, ~c"a"}
Code.Fragment.cursor_context("@asd.a(")
{:dot_call, {:module_attribute, ~c"asd"}, ~c"a"}
Code.Fragment.cursor_context("asd.a(") 
{:dot_call, {:var, ~c"asd"}, ~c"a"}
```
But those return `:none`
```
Code.Fragment.cursor_context("asd.(")                
:none
Code.Fragment.cursor_context("@asd.(")  
:none
```

### Expected behavior

```
Code.Fragment.cursor_context("asd.(")                
{:dot_call, {:var, ~c"asd"}, []}
Code.Fragment.cursor_context("@asd.(")  
{:dot_call, {:module_attribute, ~c"asd"}, []}
```

**Comment by sabiwara** [comment]
I think we would need a new tag, this shouldn't be a `:dot_call` if my understanding is correct.
Maybe {`:anonymous_call`, ~c"asd"}?
