### ISSUE TITLE
Warnings for unused imports/aliases when using __ENV__

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/elixir#12848]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 26)
```

Also applies to `main`

### Operating system

MacOS

### Current behavior

When following the recipe suggested in the [docs](https://hexdocs.pm/elixir/main/Macro.Env.html) to generate a new `Macro.Env`:

```elixir
defmodule MyEnv do
  def make_env do
    import Kernel, only: [+: 2]
    alias String.Chars
    __ENV__
  end
end
```

the compiler will emit unused warnings:

```elixir
warning: unused alias Chars
warning: unused import Kernel
```

### Expected behavior

I'm not sure what the best approach is:
- disable these warnings when importing within a function that has `__ENV__` (probably the best?)
- disable these warnings even when importing at the top when `__ENV__` is used in the module (probably too extreme, risk of false positives)
- edit the doc recipe with a way of avoiding the issue? (I don't have a good suggestion)

I'm assigning this to myself, but opened the issue for discussion.

**Comment by josevalim** [comment]
You need to pass the `warn: false` to import and alias. I am not sure if there is something else we could do. We can update the recipe :)

**Comment by sabiwara** [comment]
Oh I forgot about `warn: false` for `import` and didn't know it existed for `alias`
Awesome, will do that!
