### ISSUE TITLE
Update to Unicode 15.1 after release in September

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#12855]
### Elixir and Erlang/OTP versions

All

### Operating system

All

### Current behavior

Elixir is currently built with Unicode 15. In September 2023, [Unicode 15.1](https://unicode.org/versions/Unicode15.1.0) will be released. 

### Expected behavior

Update to [Unicode 15.1](https://unicode.org/versions/Unicode15.1.0/) prior to the release of Elixir 1.16.

**Comment by josevalim** [comment]
Hi @eksperimental, can you please confirm that we should still automatically receive PRs once there is a new release or is it better if we ping you? Thank you! :heart:

**Comment by eksperimental** [comment]
Hey José
I haven't checked that node for almost a year, I will see if I can have a look at it before September.

The app is checking for a new Unicode version every six hours, so if a new version is out and the PR hasn´t been created, something happened, so please ping me and  I will check on it.

Cheers

**Comment by kipcole9** [comment]
Apologies, I didn't realise there is an automated process in place now so. @eksperimental, sorry for the noise. Unicode 15.1 is out in September so I'm sure your script will pick it up then.

**Comment by eksperimental** [comment]
No Worries @kipcole9 ,
Feel free to reopen this PR in September if needed
