### ISSUE TITLE
`iex` and `iex -S mix` seem to have different behaviour when loading OTP modules

### ISSUE THREAD

**Issue by ankhers** [elixir-lang/elixir#12854]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 25)

### Operating system

Linux (NixOS) and MacOS

### Current behavior

```bash
$ mix new foo
$ cd foo
```

If you now run `iex` and `:observer.start()`, observer should start. If instead you run `iex -S mix` and run `:observer.start()`, observer fails to start with the following.

```
** (UndefinedFunctionError) function :observer.start/0 is undefined (module :observer is not available)
    :observer.start()
    iex:1: (file)
```

### Expected behavior

I would have expected observer to start, just like in the `iex` scenario.

**Comment by wojtekmach** [comment]
Yeah in 1.15+ in Mix projects, we need to add OTP apps to :extra_applications. In this case you might need to add both :observer and :wx. Alternatively you can call `Mix.ensure_application!(app)`.

**Comment by josevalim** [comment]
Yes, any Erlang/OTP app that is not in your code path needs to be added afterwards. Currently you need to list wx, observer, and runtime_tools but I have a PR to Erlang/OTP to require only observer.

**Comment by ankhers** [comment]
Is this something that iex would be able to add to the code path? I would not want to add observer and wx to my final release for deployment (not saying no one would). But these kinds of tools are really useful for local development and for being able to attach to a running cluster to see what is happening.

**Comment by janpieper** [comment]
@josevalim I think you mean this PR https://github.com/erlang/otp/pull/7441, right?

**Comment by josevalim** [comment]
Correct!

**Comment by josevalim** [comment]
This is streamlined in Erlang/OTP 27.
