### ISSUE TITLE
Stream API returns corrupted data in the REPL

### ISSUE THREAD

**Issue by benjamin-thomas** [elixir-lang/elixir#12864]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 26)
```
Installed via asdf

### Operating system

Ubuntu 2204

### Current behavior

Hello, 

I was playing with the Stream API and got surprised by the output. I think the screenshot speaks for itself.

![image](https://github.com/elixir-lang/elixir/assets/1557738/e5dcec75-fd87-4ff2-9522-a83dee808197)

### Expected behavior

The function chain should not return what appears to be binary data.

**Comment by sabiwara** [comment]
This is expected behavior, see explanation in a similar [issue](https://github.com/elixir-lang/elixir/issues/8993#issuecomment-487517855), or more details in the [getting started guide](https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#charlists).

You can also [configure iex](https://hexdocs.pm/iex/IEx.html#module-configuring-the-shell) to display these as list of integers:

```elixir
# .iex.exs
IEx.configure(inspect: [charlists: :as_lists])
```

**Comment by benjamin-thomas** [comment]
I see thanks, it makes sens now. I would argue it's not a good default, considering the principle of least surprise.

**Comment by sabiwara** [comment]
It sure is a quirk that comes up often, but given it is covered in all learning resources like the getting started guide mentioned above, the surprise should only happen before people learned the basics.

On the other hand, it would make it quite hard to work with libraries using charlists. Imagine debugging production logging values like
 ```elixir
%{url: [47, 102, 111, 111, 47, 98, 97, 114, 47, 49, 50, 51]}
# vs
%{url: ~c"/foo/bar/123"}
```

If we do it only for IEx by default, then we'll get question about why IEx returns something different, so this will only shift the problem.

**Comment by benjamin-thomas** [comment]
Mmm I don't know about that. I've come back here to Elixir after a few months off of it and already spent a fair amount of time learning the basics. I must have forgotten this quirk, sorry for the bother.

Point noted on the logging bit but I would say that it would be reasonable to expect a user to configure one's shell at that point.

I'm just arguing that this is not a good default.

```
iex(1)> [6,7,8]
[6, 7, 8]
iex(2)> [7,8,9]
~c"\a\b\t"
```

But I also understand this must have been discussed to death but I'm throwing my 2c anyway :)
