### ISSUE TITLE
Multiple aliases can follow consecutively

### ISSUE THREAD

**Issue by levex** [elixir-lang/elixir#12866]
### Elixir and Erlang/OTP versions

``` 
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]

 Elixir 1.15.4 (compiled with Erlang/OTP 26)
```

### Operating system

macOS 13.3.1 (22E261)

### Current behavior

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit] [dtrace]

Interactive Elixir (1.15.4) - press Ctrl+C to exit (type h() ENTER for help)
iex [08:09 :: 1] > alias alias Kernel 
Kernel
iex [08:09 :: 2] > alias alias alias Kernel
Kernel
iex [08:09 :: 3] > 
```

### Expected behavior

Maybe this should error out, instead of just letting me add as many aliases as I want?

**Comment by josevalim** [comment]
There is nothing wrong here and I don't think we should special case. `alias` shouldn't care how its argument is formed, only that it expands to an atom, and `alias Kernel` does expand to an atom, so it is all good!

**Comment by levex** [comment]
That makes sense! Thank you @josevalim  :)
