### ISSUE TITLE
The Elixir installer incorrectly appends paths to a Windows environment variable

### ISSUE THREAD

**Issue by krysros** [elixir-lang/elixir#12878]
![Path](https://github.com/elixir-lang/elixir-windows-setup/assets/5299999/cc223b11-05fe-441b-b0f9-8cff9e46cae1)

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 25)

**Comment by juliangiebel** [comment]
This elixir installer just overrode my path env variable:
![grafik](https://github.com/elixir-lang/elixir/assets/8915246/abbbc5e7-f065-462b-8b40-ee258813ebfd)

After running it with both add to path options enabled my path looked like this:
```
C:\Program Files\Elixir\bin
C:\Program Files\Erlang OTP\bin
```

Luckily I was able to restore my path from an already running program using process explorer. [Related StackExchange thread](https://superuser.com/questions/523688/how-to-restore-the-path-environment-variable-i-deleted)

Maybe what happened to me is related to this issue?

**Comment by wojtekmach** [comment]
Thank you for the report and the advice. I'll try to fix it asap.

**Comment by lboulard** [comment]
> This elixir installer just overrode my path env variable: ![grafik](https://user-images.githubusercontent.com/8915246/263964456-abbbc5e7-f065-462b-8b40-ee258813ebfd.png)
> 
> After running it with both add to path options enabled my path looked like this:
> 
> ```
> C:\Program Files\Elixir\bin
> C:\Program Files\Erlang OTP\bin
> ```
> 
> Luckily I was able to restore my path from an already running program using process explorer. [Related StackExchange thread](https://superuser.com/questions/523688/how-to-restore-the-path-environment-variable-i-deleted)
> 
> Maybe what happened to me is related to this issue?

I can confirm the issue since version 1.15.2 at least. Always unchecked PATH modifications else PATH for user account is lost and only Elixir and Erlang entry exists.

**Comment by wojtekmach** [comment]
Could you share how long your PATH value is?

If you got your Elixir installation working, does the following snippet works on your machine?

```elixir
iex> with {:ok, reg} <- :win32reg.open([:read]),
          :ok <- :win32reg.change_key(reg, ~c"\\current_user\\environment"),
          do: :win32reg.value(reg, ~c"path")
```

**Comment by lboulard** [comment]
Yes, this code works.
On this computer, length of PATH environment variable for USER is 1127 chars.

**Comment by wojtekmach** [comment]
Great, thank you for checking.

**Comment by wojtekmach** [comment]
@lboulard as I alluded to in my previous messages I think what is happening is NSIS which use to create the installer has a 1024 character limit on the string datatype and it seems we are hitting that when trying to prepend otp/bin and elixir/bin to user's PATH.

I'm planning to ship an escript that uses the `:win32reg` api mentioned above to manipulate the paths in a safer way. I am aware there's a `setx` utility available but it seems to have a 1024 character limit too. If you can think of other possible solutions it would be greatly appreciated.

**Comment by lboulard** [comment]
@wojtekmach I confirm the SETX limit:

```dobatch
SETX Path "..."

WARNING: The data being saved is truncated to 1024 characters.

SUCCESS: Specified value was saved.
```

Note also that PATH registry is a `REG_EXPAND_SZ` type and using SETX in CMD.EXE may expand variable without user consent.
So SETX is not a option. Only direct registry manipulation seems the answer if changing NSIS is not an option.

Also, you have possible usage of [Large String Special Build of NSIS](https://nsis.sourceforge.io/Special_Builds).

**Comment by wojtekmach** [comment]
yeah I saw the page about special builds but I felt like building nsis from scratch is a lot of effort only to inevitably someone hitting the 8192 down the road. hence while it's not ideal either I think manipulating the path using win32reg api that ships with OTP seems like the least bad option.

Swapping NSIS for a different tool is definitely an option but someone would have to contribute it with the feature parity we have at the moment.

**Comment by wojtekmach** [comment]
OK, besides using escript I think we can make the following changes to UI and in general work a little bit more explicitly and reliably:

<img width="545" alt="image" src="https://github.com/elixir-lang/elixir/assets/76071/60b72cc1-f7c3-4989-bf18-d65c3a753104">


If the user checks any of the checkboxes, we'd add an %ElixirInstallerPaths% with the ; separated paths and then add %ElixirInstallerPaths to %Path%:

<img width="620" alt="image" src="https://github.com/elixir-lang/elixir/assets/76071/d6927455-4a2a-42b4-941c-428679e537dd">

Windows expands %ElixirInstallerPaths% into the paths like below:

<img width="834" alt="image" src="https://github.com/elixir-lang/elixir/assets/76071/1e2ccd35-b423-4bba-b87b-d2aea6084be9">

Similarly, the uninstaller would be much simpler and more reliable too:

<img width="545" alt="image" src="https://github.com/elixir-lang/elixir/assets/76071/3e7a10b4-f43d-4128-812b-a9747b9b7439">

WDYT?

**Comment by lboulard** [comment]
Hello,

I am not sure this is that better.

 - At the end, by removing `%ElixirInstallerPaths%`, you have to cleanup PATH to remove this entry in PATH.
   Else, user will see a double semi-colon `;;` in PATH.
 - You have also the same problem as inserting environment variable in PATH only once.
   Same problem as before without a separate environment variable for Elixir and Erlang executable paths.
 - If user had already inserted Erlang executable paths, user will have duplicate entry for Erlang.

Better seeing PATH as list and manipulate as list. My own limited experience in dealing with user PATH modification:

For insertion at installation, for each path `NewPath` to insert:

 - Convert PATH to list splitting PATH string on `;`
 - Filter list removing `NewPath`
 - Insert `NewPath` at list head
 - Convert back list to PATH by joining with `;`

Putting `NewPath` at PATH start guaranty that executable path is first during PATH executables lookup.
This avoid mysterious bug reports where installed program if not found, nor working as intended, because an executable installation is shadowed. To not optimise case of multiple paths insertion, this is not worth the risk of bugs.

For removal at deinstallation, obviously the sequence is:

 - Convert PATH to list splitting PATH string on `;`
 - Filter list removing `NewPath`
 - Convert back list to PATH by joining with `;`

**Comment by wojtekmach** [comment]
The idea was the uninstaller would remove  %ElixirInstallerPaths% and adjust %Path% accordingly. And yes we’d always prepend.

**Comment by lboulard** [comment]
Then, how do you handle if `C:\Program Files\Erlang OTP\bin` is already present in PATH and `C:\Program Files\Erlang OTP\bin` is not?

**Comment by wojtekmach** [comment]
If it’s already present don’t check the checkbox :)


But yeah we can keep the previous UI for sure. Doing the path as list in Erlang is trivial and I feel much more confident doing so.

**Comment by wojtekmach** [comment]
@lboulard I have opened #12900. If you'd like to test it, do:

```
cd /path/to/elixir
cd lib/elixir/scripts/windows_installer
curl -L -o Precompiled.zip https://github.com/elixir-lang/elixir/releases/download/v1.15.5/elixir-otp-26.zip
ELIXIR_ZIP=Precompiled.zip ./build.sh
```

you need to have NSIS installed.

Anyway, I ended up handling duplicates in the Erlang code after all.

**Comment by wojtekmach** [comment]
Here's the zip of the installer: [elixir-otp-26.exe.zip](https://github.com/elixir-lang/elixir/files/12476514/elixir-otp-26.exe.zip)

**Comment by lboulard** [comment]
@wojtekmach PATH is correctly updated in registry.
But you need the Windows Message Broadcast to inform `Explorer.exe` and `other` to refresh system + user environment.

(For an unknown reason, I already have both paths in SYSTEM environment)

**Comment by lboulard** [comment]
@wojtekmach "For me, it is enough to restart my terminal program."

For Windows, requires restarting the computer. Not the terminal.
Terminal is always getting environment from Explorer not from Registry.

**Comment by wojtekmach** [comment]
> For Windows, requires restarting the computer. Not the terminal.

I am testing this on Windows and it works here. :) I'm using their Terminal app.

> PowerShell

yeah that's a no, running powershell things requires additional permissions.

**Comment by lboulard** [comment]
@wojtekmach "I am testing this on Windows and it works here. :) I'm using their Terminal app."

Same here. And it did not work 😋
Ah... Windows...

**Comment by wojtekmach** [comment]
What are you using as your terminal? "Command Prompt" app (I guess cmd.exe) ?

Restarting "Terminal" app allows me to see updated env. Restarting "Command Prompt" does not.

**Comment by lboulard** [comment]
User only installation of "Windows Terminal".
I known that Windows 10 and Windows 11 are not the same regarding terminal.
On windows 10, it behave more like cmd.exe

**Comment by lboulard** [comment]
@wojtekmach Thank you for patch and pull request

**Comment by simonmcconnell** [comment]
@wojtekmach was there a limitation with Inno setup that triggered the change to NSIS? If not, I'm happy to look at changing to Inno. It's what I use for my installer.

**Comment by wojtekmach** [comment]
No particular reason we chose NSIS. That's what we used for Livebook Desktop and so I was familiar with it. One minor benefit I guess is the official Erlang installer uses it too though we are not sharing any code.

**Comment by wojtekmach** [comment]
Sunk cost fallacy aside just to be clear I personally wouldn't mind switching to another solution if it has better DX.

**Comment by simonmcconnell** [comment]
I chose Inno based on the weird NSIS syntax and because it doesn't brand the installer. I felt having "Nullsoft Installer ..." written on my product's installer looked less professional, but that's not necessarily a concern for Elixir.

I can look into an Inno setup for Elixir.

**Comment by wojtekmach** [comment]
for posterity: Go windows installer seems to be building a .msi with [wix](https://wixtoolset.org): https://github.com/golang/build/blob/762ea3306f82c4b9d09876cc7d7bd4370bb2b264/internal/task/releaselet/releaselet.go#L326. wix is even pre-installed on [windows](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md) runners on Github Actions. (But so is NSIS and Inno :D)

**Comment by krysros** [comment]
Side note: The Python installer allows you to disable path length limit at the end of the installation.

![Disable path length limit](https://github.com/elixir-lang/elixir/assets/5299999/cc0646c9-813f-48ef-8bec-da7a5eab2a88)
