### ISSUE TITLE
`when map.field or x` is not commutative

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#12874]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.16.0-dev (88ad5d2) (compiled with Erlang/OTP 26)

### Operating system

macOS

### Current behavior

Not sure if this is expected nor whether it's a bug in Elixir or OTP. Apologies if this is documented anywhere!

Here's a minimal script:

```elixir
defmodule Main do
  def f1(x) when x.field == 1 or x == 1, do: {:ok, x}
  def f1(_), do: :error

  def f2(x) when x == 1 or x.field == 1, do: {:ok, x}
  def f2(_), do: :error

  def main do
    :error = f1(1)
    {:ok, 1} = f2(1)
  end
end

Main.main()
```

For a more realistic code snippet:

```elixir
  def decompress_body({request, response})
      when request.options.raw == true or
             response.body == "" or
             not is_binary(response.body) do
    {request, response}
  end

  def decompress_body({request, response}) do
    compression_algorithms = get_content_encoding_header(response.headers)
    {request, update_in(response.body, &decompress_body(&1, compression_algorithms))}
  end
```

Changing the order of guard elements fixes the bug.

### Expected behavior

The order does not matter.

**Comment by wojtekmach** [comment]
guards cannot raise.

**Comment by josevalim** [comment]
That's the semantics of guards. If a guard raises, it is considered that the guards fail: https://hexdocs.pm/elixir/main/patterns-and-guards.html#errors-in-guards

So if you mix the error semantics with the short-circuiting, it all makes sense. I believe the type system would be able to tell though that the right side of `or` is unreachable. So stay tuned.

**Comment by wojtekmach** [comment]
Perfect, thank you both.

**Comment by wojtekmach** [comment]
And yeah this was totally documented, sorry about that.
