### ISSUE TITLE
Incorrect column reported for non-atom aliases

### ISSUE THREAD

**Issue by zachallaun** [elixir-lang/elixir#12870]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.16.0-dev (6a72d29) (compiled with Erlang/OTP 26)
```

(Also replicated on 1.14 and 1.15)

### Operating system

Ubuntu 22.04

### Current behavior

```elixir
# correct
iex(1)> Code.string_to_quoted!("Foo.Bar", columns: true)
{:__aliases__, [line: 1, column: 1], 
 [:Foo, :Bar]}

# incorrect
iex(2)> Code.string_to_quoted!("__MODULE__.Bar", columns: true)
{:__aliases__, [line: 1, column: 11], # <- should be 1, not 11
 [{:__MODULE__, [line: 1, column: 1], nil}, :Bar]}

# incorrect
iex(3)> Code.string_to_quoted!("@foo.Bar", columns: true)
{:__aliases__, [line: 1, column: 5], # <- should be 1, not 5
 [{:@, [line: 1, column: 1], [{:foo, [line: 1, column: 2], nil}]}, :Bar]}
```

### Expected behavior

In all three examples above, I expect the `:column` metadata of the `:__aliases__` node to be `1`.

**Comment by josevalim** [comment]
Honestly, I can see an argument for both. I can see `__aliases__` pointing to the first static alias, as that would encode more interesting information on the AST. Otherwise we end-up duplicating info.

**Comment by zachallaun** [comment]
My concern is that it is unexpected and requires you to analyze the AST in a non-obvious way. Consider that you're trying to get the start column for a node. You need to do something like:

```elixir
def start_column({:__aliases__, _, [{_, meta, _} | _]), do: meta[:column]
def start_column({:__aliases__, meta, _), do: meta[:column]
...
```

While there are other instances where the `:column` of a node isn't at the beginning (`:.`, for example), I'm not sure whether there are nodes where the column *varies* based upon the presence of certain children.

**Comment by josevalim** [comment]
Yeah, that's the other side. But right now I am inclined to keep the special case, in favor of having more information. :)

**Comment by zachallaun** [comment]
It's not really more information, though, is it? If you wanted to know where the first static alias is, you could calculate the offset from the first arg. In the majority of cases, I'd think, you expect this to be the start of the `:__aliases__` node. ([In Sourceror](https://github.com/doorgan/sourceror/issues/99), for instance, this is the cause of a bug in a utility to get the line/column range of a node.)

**Comment by josevalim** [comment]
The first argument can be anything, including a complex macro.

**Comment by zachallaun** [comment]
Fair enough! I'll propose a fix in Sourceror.

Is there anywhere for things like this to be documented? It's pretty in the weeds and I'm not sure there's anywhere that really describes AST metadata quite at this level. (The [syntax reference](https://hexdocs.pm/elixir/main/syntax-reference.html#aliases-1), for instance, doesn't get into metadata.)

**Comment by josevalim** [comment]
I am not sure to be honest. It would most likely end-up "polluting" the syntax reference because people reading that doc may not necessarily care. :( Perhaps for now it is best to wait a bit until we have more "needs"?

**Comment by zachallaun** [comment]
Sounds good to me! Perhaps, eventually, something like @doorgan's [deep dive into the Elixir AST](https://dorgan.netlify.app/posts/2021/04/the_elixir_ast/) could be contributed to the new metaprogramming section of the v1.16 docs.
