### ISSUE TITLE
`Code.Fragment.surround_context/2` returns no information for locals or vars at the start of an alias

### ISSUE THREAD

**Issue by zachallaun** [elixir-lang/elixir#12889]
### Elixir and Erlang/OTP versions

Tested on `main`:

```
$ bin/elixir --version
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.16.0-dev (96a41c8) (compiled with Erlang/OTP 26)
```

### Operating system

Ubuntu 22.04

### Current behavior

`Code.Fragment.surround_context/2` unexpectedly returns `:none` for locals or vars at the beginning of an alias.

```elixir
iex(1)> Code.Fragment.surround_context("TopLevel", {1, 1})
%{context: {:alias, ~c"TopLevel"}, begin: {1, 1}, end: {1, 9}}

iex(2)> Code.Fragment.surround_context("TopLevel.Nested", {1, 1})
%{context: {:alias, ~c"TopLevel.Nested"}, begin: {1, 1}, end: {1, 16}}

iex(3)> Code.Fragment.surround_context("TopLevel.", {1, 1})
%{context: {:alias, ~c"TopLevel"}, begin: {1, 1}, end: {1, 9}}

iex(4)> Code.Fragment.surround_context("__MODULE__", {1, 1})
%{context: {:local_or_var, ~c"__MODULE__"}, begin: {1, 1}, end: {1, 11}}

iex(5)> Code.Fragment.surround_context("__MODULE__.foo", {1, 1})
%{context: {:local_or_var, ~c"__MODULE__"}, begin: {1, 1}, end: {1, 11}}

# unexpected!
iex(6)> Code.Fragment.surround_context("__MODULE__.Nested", {1, 1})
:none

# note column 11
iex(7)> Code.Fragment.surround_context("__MODULE__.Nested", {1, 11})
%{
  context: {:alias, {:local_or_var, ~c"__MODULE__"}, ~c"Nested"},
  begin: {1, 1},
  end: {1, 18}
}

iex(8)> Code.Fragment.surround_context("__MODULE__.", {1, 1})
%{context: {:local_or_var, ~c"__MODULE__"}, begin: {1, 1}, end: {1, 11}}

iex(9)> Code.Fragment.surround_context("foo.bar", {1, 1})
%{context: {:local_or_var, ~c"foo"}, begin: {1, 1}, end: {1, 4}}

# unexpected!
iex(10)> Code.Fragment.surround_context("foo.Bar", {1, 1})
:none
```

### Expected behavior

For the two unexpected results above, I would expect:

```elixir
iex(6)> Code.Fragment.surround_context("__MODULE__.Nested", {1, 1})
%{context: {:local_or_var, ~c"__MODULE__"}, begin: {1, 1}, end: {1, 11}}

iex(10)> Code.Fragment.surround_context("foo.Bar", {1, 1})
%{context: {:local_or_var, ~c"foo"}, begin: {1, 1}, end: {1, 4}}
```

**Comment by zachallaun** [comment]
Looking at [the tests related to this](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/test/elixir/code_fragment_test.exs#L766-L876), it doesn't look like any are asserting that a `__MODULE__.Foo` context is `:none` when the focused column is somewhere within the `__MODULE__`, so I'm assuming this is a bug!

**Comment by josevalim** [comment]
Looks like a bug to me! Feel free to send a PR if you want, otherwise let me know and I will tackle it :)

**Comment by zachallaun** [comment]
I'm not very familiar with `Code.Fragment` and I'm not entirely sure where to start, but I'd be happy to poke around and see if I can figure it out! If you can point to the likely location for changes, that would probably be a great help! Alternatively, if you think this would be a quick thing for you to just fix, that is completely fine with me. 🙂

**Comment by zachallaun** [comment]
Nevermind -- I think I found it :)

**Comment by zachallaun** [comment]
I have [a commit that addresses this](https://github.com/elixir-lang/elixir/commit/08610ad8d3858f0001639d5b457d3124d8c83369), but not in the way I originally thought when posting the issue. Specifically, here's what I _thought_ should happen:

```elixir
iex(1)> Code.Fragment.surround_context("foo.Bar", {1, 1})
%{context: {:local_or_var, ~c"foo"}, begin: {1, 1}, end: {1, 4}}

iex(2)> Code.Fragment.surround_context("foo.bar.Baz", {1, 1})
%{context: {:local_or_var, ~c"foo"}, begin: {1, 1}, end: {1, 4}}
```

Here's what _actually_ happens when handling this case in looked like the "obvious way" in the code:

```elixir
iex(1)> Code.Fragment.surround_context("foo.Bar", {1, 1})
%{
  context: {:alias, {:local_or_var, ~c"foo"}, ~c"Bar"},
  begin: {1, 1},
  end: {1, 8}
}

iex(2)> Code.Fragment.surround_context("foo.bar.Baz", {1, 1})
%{context: {:local_or_var, ~c"foo"}, begin: {1, 1}, end: {1, 4}}
```

Is there something I'm missing, or is this the correct behavior?

**Comment by josevalim** [comment]
Yes, this is correct. `foo.bar.Baz` is equivalent to `(foo.bar).Baz` and therefore you are selecting the left side of `foo.bar`.
