### ISSUE TITLE
`rescue e in [FunctionClauseError, CaseClauseError]` reports truncated message

### ISSUE THREAD

**Issue by lud-wj** [elixir-lang/elixir#12887]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

### Operating system

Xubuntu latest

### Current behavior

```
      e in FunctionClauseError ->
        Exception.message(e) |> IO.puts()
```

Displays "no function clause matching in MyMod.my_fun/1        

```
      e in [FunctionClauseError, CaseClauseError] ->
        Exception.message(e) |> IO.puts()
        Exception.format_banner(:error, e, __STACKTRACE__) |> IO.puts()
```

Displays only "no function clause matches" and the banner is only "** (FunctionClauseError) no function clause matches"

### Expected behavior

I would expect the full exception message/banner to be generated, or the "in list" syntax to be invalid.

Edit: The "in list" form seems to compile down to `'Elixir.Exception':normalize(error, _@2, [])`, that is passing an empty list instead of the stacktrace. Also the binding for the stacktrace (`error:_@2:___STACKTRACE__@1`) is in a single place so it should be available.

**Comment by sabiwara** [comment]
I think this works as expected, these are respectively the message and the banner?

If you want the full message with stacktrace you should use [`Exception.format/3`](https://hexdocs.pm/elixir/Exception.html#format/3):

```elixir
try do
  :lists.sum(0)
rescue err in FunctionClauseError ->
  Exception.format(:error, err, stacktrace) |> IO.puts()
end
```

Prints:

```
** (FunctionClauseError) no function clause matching in :lists.sum/2
    (stdlib 4.0.1) lists.erl:319: :lists.sum(0, 0)
    iex:3: (file)
```

If you want to see the extra argument information, you can use [`blame/3`](https://hexdocs.pm/elixir/Exception.html#blame/3) first (potentially expensive)

```elixir
try do
  :lists.sum(0)
rescue err in FunctionClauseError ->
  {payload, stacktrace} = Exception.blame(:error, err, __STACKTRACE__)
  Exception.format(:error, payload, stacktrace) |> IO.puts()
end
```

prints

```
** (FunctionClauseError) no function clause matching in :lists.sum/2

The following arguments were given to :lists.sum/2:

    # 1
    0

    # 2
    0
```

**Comment by sabiwara** [comment]
I understood the cause, but won't have time to submit a fix.

The problem is here:
https://github.com/elixir-lang/elixir/blob/main/lib/elixir/src/elixir_erl_try.erl#L58

`:lists.splitwith` is like `Enum.split_while`, not `Enum.split_with`. It stops once it reached `CaseClauseError` for which `is_normalized_with_stacktrace` returns `false`.

```erlang
ErlangAliases: ['Elixir.CaseClauseError','Elixir.FunctionClauseError']
splitwith: {[],['Elixir.CaseClauseError','Elixir.FunctionClauseError']}
```

**Comment by lud-wj** [comment]
@sabiwara Thanks for the fix!
