### ISSUE TITLE
Fail to execute :rand.uniform of BigNum in a test case.

### ISSUE THREAD

**Issue by zacky1972** [elixir-lang/elixir#12886]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

### Operating system

macOS Ventura 13.5

### Current behavior

Describe the following test case:

```elixir
defmodule TmpTest do
  use ExUnit.Case

  test "test" do
    assert :rand.uniform(Bitwise.bsl(1, 2041)) <= Bitwise.bsl(1, 2041)
  end
end
```

Then, do `mix test`.

Finally, the following error occurs:

```
 1) test test (TmpTest)
     test/ex_int/tmp_test.exs:4
     ** (ArithmeticError) bad argument in arithmetic expression
     code: assert :rand.uniform(Bitwise.bsl(1, 2041)) <= Bitwise.bsl(1, 2041)
     stacktrace:
       (stdlib 5.0.2) rand.erl:364: :rand.uniform_s/2
       (stdlib 5.0.2) rand.erl:319: :rand.uniform/1
       test/ex_int/tmp_test.exs:5: (test)
```

### Expected behavior

The test case should be successful.

**Comment by zacky1972** [comment]
This has a strange feature:

If you execute the following script, then it succeed:

```elixir
:rand.uniform(Bitwise.bsl(1, 2041))
```

**Comment by josevalim** [comment]
This is fixed on Elixir main, because ExUnit in main uses a more recent rand algorithm. :)
