### ISSUE TITLE
Compiler hangs on specific interaction between `Inspect.impl_for/1` and `Kernel.ParallelCompiler.async/1`

### ISSUE THREAD

**Issue by zachdaniel** [elixir-lang/elixir#12897]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.5 (compiled with Erlang/OTP 24)

EDIT: tried with elixir 1.14 and 1.13, and also with Elixir compiled with the same version of OTP that is being used (26)

### Operating system

Mac (apple silicon)

### Current behavior

Reproduced in the following project: https://github.com/zachdaniel/parallel_compiler_bug

In [spark](https://github.com/ash-project/spark) we define many modules to back the DSLs that we define, and to aid in compile times in that process, we use `Kernel.ParallelCompiler.async/1`. @jimsynz and spent quite some time debugging what appeared to be some kind of compiler deadlock (infinite hang in the compile step) and we ultimately discovered that it was when trying to inspect a struct. Boiling it down further, we were able to arrive at a minimal reproduction of just calling `Inspect.impl_for/1` to reproduce the issue. If we don't use `async/1` and instead just do the work inline, the inspecting works properly. If we had set a timeout instead of `:infinity` we would have also likely taken less time to discover the issue.

### Expected behavior

`Inspect.impl_for/1` works properly inside of `Kernel.ParallelCompiler.async/1` instead of halting indefinitely.

**Comment by lukaszsamson** [comment]
Possibly related to that: I hit a similar deadlock issue in ElixirLS debugger when a breakpoint set inside `Inspect` implementation was hit.

**Comment by josevalim** [comment]
@zachdaniel thank you for the very detailed report, I have found the root cause, but I need to study the best fix.

@lukaszsamson from my initial glance, you are reporting a separate issue, but from a glance, it sounds expected. If the ElixirLS debugger uses `Inspect` for printing results, debugging `Inspect` will set a deadlock or an infinite loop.

**Comment by lukaszsamson** [comment]
> it sounds expected. If the ElixirLS debugger uses `Inspect` for printing results, debugging Inspect will set a deadlock or an infinite loop

That was my guess as well. The strange thing is it deadlocks only for `Inspect` and not for `Enumerable`, `Collectable` and `Chars`. All of those are used. But enough with the sidetracking - I forbid setting breakpoints in `Inspect` implementations.

**Comment by josevalim** [comment]
@zachdaniel after further exploration of the code, I can't see a way to address it without adding a new abstraction (pmap). So you will have to wait until Elixir v1.16 before adding this feature (or make sure that your code does not attempt to run/load user modules).

**Comment by zachdaniel** [comment]
I can accept that limitation for now, especially if we expect a fix sometime in the future. Generally, end user code should not be loaded in this context, I exposed access to an "async compile" helper to allow extensions that define modules to leverage it, and I will add to its docs that it needs to avoid calling user modules when used.

**Comment by zachdaniel** [comment]
By "I can accept that limitation" I mean that we shouldn't need to remove the feature, we can just update docs 😂

**Comment by josevalim** [comment]
Kernel.ParallelCompiler.pmap/2 has been introduced as a more robust abstraction for perform parallel work in the compiler.
