### ISSUE TITLE
`dbg` recompilation issue

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12892]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15@def65ab1208939acf92bcc3649a932facdc87f52 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

When working on dbg backend for ElixirLS debugger I noticed an issue with macro recompilation. Whenever I change the dbg backend implementation I need to nuke the client mix project _build directory.
Repro:
This is a simplified script that simulates running a debug session executing
```
mix run -e "DbgRecompile.hello()"
```
1. `git clone git@github.com:lukaszsamson/elixir_dbg_recompilation_repro.git`
2. `cd elixir_dbg_recompilation_repro`
3. `elixir run.exs`
works fine
```
Compiling 1 file (.ex)
Generated dbg_recompile app
running with dbg
[lib/dbg_recompile.ex:17: DbgRecompile.hello/0]
:world #=> :world
```
4. `git checkout changed`
changed
```
  def dbg(code, options, %Macro.Env{} = caller) do
    quote do
      GenServer.call(unquote(__MODULE__), {:dbg, __ENV__}, :infinity)
      unquote(Macro.dbg(code, options, caller))
    end
  end
```
to
```
  def dbg(code, options, %Macro.Env{} = caller) do
    quote do
      GenServer.call(unquote(__MODULE__), {:dbg, __ENV__, true}, :infinity)
      unquote(Macro.dbg(code, options, caller))
    end
  end
```
and
```
def handle_call({:dbg, %Macro.Env{}}, _from, state) do
```
to
```
def handle_call({:dbg, %Macro.Env{}, _}, _from, state) do
```
6. `elixir run.exs`
```
running with dbg

08:31:39.393 [error] GenServer MyDbg terminating
** (FunctionClauseError) no function clause matching in MyDbg.handle_call/3
    run.exs:21: MyDbg.handle_call({:dbg, #Macro.Env<aliases: [], context: nil, context_modules: [DbgRecompile], file: "/Users/lukaszsamson/bug_repro/elixir_dbg_recompilation_repro/lib/dbg_recompile.ex", function: {:hello, 0}, functions: [{Kernel, [!=: 2, !==: 2, *: 2, **: 2, +: 1, +: 2, ++: 2, -: 1, -: 2, --: 2, /: 2, <: 2, <=: 2, ==: 2, ===: 2, =~: 2, >: 2, >=: 2, abs: 1, apply: 2, apply: 3, binary_part: 3, binary_slice: 2, binary_slice: 3, bit_size: 1, byte_size: 1, ceil: 1, div: 2, elem: 2, exit: 1, floor: 1, function_exported?: 3, get_and_update_in: 3, get_in: 2, hd: 1, inspect: 1, inspect: 2, is_atom: 1, is_binary: 1, ...]}], lexical_tracker: nil, line: 17, macro_aliases: [], macros: [{Kernel, [!: 1, &&: 2, ..: 0, ..: 2, ..//: 3, <>: 2, @: 1, alias!: 1, and: 2, binding: 0, binding: 1, dbg: 0, dbg: 1, dbg: 2, def: 1, def: 2, defdelegate: 2, defexception: 1, defguard: 1, defguardp: 1, defimpl: 2, defimpl: 3, defmacro: 1, defmacro: 2, defmacrop: 1, defmacrop: 2, defmodule: 2, defoverridable: 1, defp: 1, defp: 2, defprotocol: 2, defstruct: 1, destructure: 2, get_and_update_in: 2, if: 2, ...]}], module: DbgRecompile, requires: [Application, Kernel, Kernel.Typespec], ...>}, {#PID<0.93.0>, #Reference<0.700957947.3508535297.221786>}, %{})
    (stdlib 4.3.1.2) gen_server.erl:1149: :gen_server.try_handle_call/4
    (stdlib 4.3.1.2) gen_server.erl:1178: :gen_server.handle_msg/6
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.93.0>): {:dbg, #Macro.Env<aliases: [], context: nil, context_modules: [DbgRecompile], file: "/Users/lukaszsamson/bug_repro/elixir_dbg_recompilation_repro/lib/dbg_recompile.ex", function: {:hello, 0}, functions: [{Kernel, [!=: 2, !==: 2, *: 2, **: 2, +: 1, +: 2, ++: 2, -: 1, -: 2, --: 2, /: 2, <: 2, <=: 2, ==: 2, ===: 2, =~: 2, >: 2, >=: 2, abs: 1, apply: 2, apply: 3, binary_part: 3, binary_slice: 2, binary_slice: 3, bit_size: 1, byte_size: 1, ceil: 1, div: 2, elem: 2, exit: 1, floor: 1, function_exported?: 3, get_and_update_in: 3, get_in: 2, hd: 1, inspect: 1, inspect: 2, is_atom: 1, is_binary: 1, ...]}], lexical_tracker: nil, line: 17, macro_aliases: [], macros: [{Kernel, [!: 1, &&: 2, ..: 0, ..: 2, ..//: 3, <>: 2, @: 1, alias!: 1, and: 2, binding: 0, binding: 1, dbg: 0, dbg: 1, dbg: 2, def: 1, def: 2, defdelegate: 2, defexception: 1, defguard: 1, defguardp: 1, defimpl: 2, defimpl: 3, defmacro: 1, defmacro: 2, defmacrop: 1, defmacrop: 2, defmodule: 2, defoverridable: 1, defp: 1, defp: 2, defprotocol: 2, defstruct: 1, destructure: 2, get_and_update_in: 2, if: 2, ...]}], module: DbgRecompile, requires: [Application, Kernel, Kernel.Typespec], ...>}
State: %{}
Client #PID<0.93.0> is alive

    (stdlib 4.3.1.2) gen.erl:237: :gen.do_call/4
    (elixir 1.15.4) lib/gen_server.ex:1071: GenServer.call/3
    (dbg_recompile 0.1.0) lib/dbg_recompile.ex:17: DbgRecompile.hello/0
    (elixir 1.15.4) src/elixir.erl:376: anonymous fn/4 in :elixir.eval_external_handler/1
    (stdlib 4.3.1.2) erl_eval.erl:748: :erl_eval.do_apply/7
    (elixir 1.15.4) src/elixir.erl:361: :elixir.eval_forms/4
    (elixir 1.15.4) lib/module/parallel_checker.ex:112: Module.ParallelChecker.verify/1
    (elixir 1.15.4) lib/code.ex:543: Code.validated_eval_string/3
```

### Expected behavior

The compiler should detect that `dbg` has changed and recompile modules using it

**Comment by josevalim** [comment]
> The compiler should detect that dbg has changed and recompile modules using it

We already check this but it seems something is missing. I will investigate! Thanks for the repro!

**Comment by josevalim** [comment]
I am not sure there is something we can do to fix this. The `compile_env` is exactly the same but you changed the implementation of the macro expansion. I don't believe this happen in an actual project because:

1. If dbg comes from a dependency, updating the dbg module requires updating the dependency which would make it recompile

2. If dbg comes from the same project, updating the dbg module would trigger callers to recompile

But here, because the module management (and its changes) are happening completely outside of Elixir, we can't really know you changed the implementation. We could do things like store the module MD5, but given this can only happen in a case where you are manipulating the environment behind the scenes, you should be able to address this by changing the MFA (you can use a different callback name) or even by storing a fake argument such as:

    Application.put_env(:elixir, :dbg_callback, {MyDbg, :dbg, [:v1]})

**Comment by josevalim** [comment]
I pushed a commit that guarantees we recompile if the dbg module changes, but the module has to be tracked by Mix, which may not be the case here. If that's indeed true, you need to make sure you change the env var so Mix can see the change. :)

**Comment by lukaszsamson** [comment]
> I am not sure there is something we can do to fix this. The compile_env is exactly the same but you changed the implementation of the macro expansion

I feared that this issue may be limited to some specific scenarios but I made the repro so we are sure that it is not a manifestation of a wider problem with recompilation.

> If dbg comes from the same project, updating the dbg module would trigger callers to recompile (not quite, I am pushing a fix to guarantee this)

Since the fix requires using `Macro.compile_apply` there may still be some client code not related to `dbg` that is susceptible to that issue. The need for occasional nuking of _build unfortunately won't go away

**Comment by josevalim** [comment]
> I feared that this issue may be limited to some specific scenarios but I made the repro so we are sure that it is not a manifestation of a wider problem with recompilation.

The repo is still messing up with the environment outside of Mix, so it doesn't really change the assessment here.

> Since the fix requires using Macro.compile_apply there may still be some client code not related to dbg that is susceptible to that issue. The need for occasional nuking of _build unfortunately won't go away

If you read an env var at compile-time and you do a dynamic dispatch, that would always be hidden from Mix. There is really nothing we can do here. The goal of introducing `compile_apply` is exactly to provide an API to make that clear for the compiler.

**Comment by bcardarella** [comment]
Is `Macro.compile_apply/4` intended to expand macros under a given caller? According to the docs:

> This is used when you want to programmatically invoke a macro at compile-time.

and this seems like expanding macros with a caller override is the intended use-case. However, I cannot find any unit tests and only that single LOC within `dbg` uses it. Furthermore, I can only find a single reference of it being used at all in all of GitHub: https://github.com/search?q=%22Macro.compile_apply%22&type=code (these are all hits from forks of Elixir)

I attempted to use it to have a macro call a macro outside of the `quote` block with the caller that called the first macro. I have a good reason to do so, but the compilation fails because the module isn't required. Even adding the require to the `caller` doesn't change anything in this Livebook example:


# Macro.compile_apply/4

## Section

```elixir
defmodule Foo do
  defmacro __using__(_) do
    Module.register_attribute(__CALLER__.module, :foo, persist: true)
    Module.put_attribute(__CALLER__.module, :foo, :bar)

    quote do
      def test do
        :test
      end
    end
  end
end
```



```
{:module, Foo, <<70, 79, 82, 49, 0, 0, 9, ...>>, {:__using__, 1}}
```

```elixir
defmodule Bar do
  defmacro use_foo do
    {:ok, env} = Macro.Env.define_require(__CALLER__, [line: 0], Foo)
    Macro.Env.required?(env, Foo) |> IO.inspect(label: "Required?")
    Macro.compile_apply(Foo, :__using__, [[]], env)
  end
end
```



```
{:module, Bar, <<70, 79, 82, 49, 0, 0, 8, ...>>, {:use_foo, 0}}
```

```elixir
defmodule Baz do
  require Bar
  Bar.use_foo()
end

Baz.__info__(:attributes) |> Keyword.get(:foo) |> IO.inspect()
Baz.test()
```



```
Required?: true
```



```
** (UndefinedFunctionError) function Foo.__using__/1 is undefined or private. However, there is a macro with the same name and arity. Be sure to require Foo if you intend to invoke this macro
    Foo.__using__([])
    expanding macro: Bar.use_foo/0
    #cell:t4ra2pplcx3bmcpz:1: (file)
```

**Comment by josevalim** [comment]
Macro.expand will expand macros. compile_apply is for functions, I will improve the docs.

**Comment by josevalim** [comment]
Yes, the macro mention in the docs was plain wrong, I fixed it locally and will push it. Thanks for the feedback!
