### ISSUE TITLE
Sign Windows installer binaries

### ISSUE THREAD

**Issue by rhblind** [elixir-lang/elixir#12891]
### Elixir and Erlang/OTP versions

This issue probably affects all installer binaries as well, but I haven't tested.

### Operating system

Windows 11

### Current behavior

Windows Defender blocks the installer because the installer is unsigned.
Many companies enforces this behaviour. Sometimes users have Administrator access to their own computers and can override Windows Defender, but not always.

If binaries are signed, it can be easier for companies to allow users install Elixir using the Windows binary installer.

![Unknown publisher](https://github.com/elixir-lang/elixir/assets/1574295/72a60292-b88f-4be2-8e10-45ae1a595c6b)

### Expected behavior

The Windows installer binaries are signed and not blocked by Windows Defender.
Optionally, the publisher certificate can be allowlisted in Windows Defender corporate rules so that the installer can run.

**Comment by josevalim** [comment]
We looked into this and unfortunately the only way to bypass these screens is by having a certificate tied to a company (or a person), and I believe both options would misrepresent how Elixir is developed and maintained today. One option would be to ask the Erlang Ecosystem Foundation if they could acquire the certificate and that's additional work. Another option is to use self-signed certificates but it is unlikely they would be accepted for the case above.

And even if the above is somehow acceptable, we would need to move the build out of CI into something private, making it harder for others to improve and contribute.

For all of these reasons, we don't plan to tackle this for now. We recommend using chocolatey or installing from precompiled source as alternatives.

**Comment by rhblind** [comment]
I understand, thanks for looking into this.
