### ISSUE TITLE
mix deps.get throwing timeout error

### ISSUE THREAD

**Issue by Dipendra-creator** [elixir-lang/elixir#12903]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

### Operating system

Windows

## I have got many solutions lix `mix.local.hex --force` will work or `mix deps.clean --all` nothing worked for still showing these errors

E:\Learning\Elixir\code\demo>`mix local.hex --force`
* creating c:/Users/dipus/.mix/archives/hex-2.0.6

E:\Learning\Elixir\code\demo>`mix deps.get`
Failed to fetch record for phoenix_live_reload from registry (using cache instead)
:timeout
Failed to fetch record for phoenix_ecto from registry (using cache instead)
:timeout
Failed to fetch record for phoenix_html from registry (using cache instead)
:timeout
Failed to fetch record for phoenix from registry (using cache instead)
:timeout
Failed to fetch record for floki from registry (using cache instead)
:timeout
** (Mix) No package with name phoenix (from: mix.exs) in registry

### Expected behavior

It should get all the dependencies required

**Comment by josevalim** [comment]
Are you behind a proxy or anything that may affect your connection?

**Comment by josevalim** [comment]
Hi @Dipendra-creator , please let us know if you have more information on the above and we will gladly reopen. Thank you!
