### ISSUE TITLE
IEx should intercept stdio until it started successfully

### ISSUE THREAD

**Issue by scottming** [elixir-lang/elixir#12917]
### Elixir and Erlang/OTP versions

elixir          1.15.4-otp-26 
erlang          26.0.2        

### Operating system

macOS 13.4.1

### Current behavior

I'm unsure if this is a bug of OTP 26 or IEx. I noticed that before OTP 26, IEx would intercept stdio until it started successfully. This allowed us to execute two commands sequentially(Very friendly to some editor testing tools), one for starting IEx and another for the execution of a command on IEx.

Is there any way to make the **waiting** behavior of the IEx shell consistent with OTP 25?

The below video shows `IExUnit.run("test/dummy_test.exs", line: 5, ...` runs before the IEx shell starts.

https://github.com/elixir-lang/elixir/assets/12830256/4faea657-181a-484f-8d12-a83258dc6ddc

### Expected behavior

https://github.com/elixir-lang/elixir/assets/12830256/817e8b0e-cb84-4163-bc3c-3eea969669e5

**Comment by josevalim** [comment]
@scottming can you either provide a script that reproduces the issue or try this with `erl` (without Elixir), so we know if it is an Elixir or Erlang issue?

**Comment by scottming** [comment]
Ok, this is the script.

```expect
#!/usr/bin/expect

spawn iex -S mix
send "IO.puts(\"Hello, world!\")\r"
interact
```

when running under `26.0.2`:

```elixir
~/Code/dummy ❯ ./script.exp                                                                             26.0.2  1.15.4-otp-25
spawn iex -S mix
IO.puts("Hello, world!")
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C% 
```

when running under 25.3.2

```elixir
~/Code/dummy ❯ ./script.exp                                                                      12s  25.3.2.4  1.15.4-otp-25
spawn iex -S mix
IO.puts("Hello, world!")
Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Compiling 1 file (.ex)
Generated dummy app
Interactive Elixir (1.15.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> IO.puts("Hello, world!")
Hello, world!
:ok
iex(2)>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C%
```

### Just use `erl`

```erlang
# another script
#!/usr/bin/expect

spawn erl
send "\"Hello World\".\n"
interact
```

 It'll work on both 25 and 26.
 
 ```erl
 ~/Code/dummy ❯ ./erl_script.exp                                                                         26.0.2  1.15.4-otp-25
spawn erl
"Hello World".
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Eshell V14.0.2 (press Ctrl+G to abort, type help(). for help)
1> "Hello World".
"Hello World"
2>
```

**Comment by josevalim** [comment]
Reported it upstream, thank you: https://github.com/erlang/otp/issues/7650

**Comment by josevalim** [comment]
I believe this behaviour won't be possible from now on. @scottming is there a reason why you can't use `--eval "..."` to pass the information that you need?

**Comment by scottming** [comment]
@josevalim Okay, I got it. Thank you.

I can achieve the same goal using "--eval".


<img width="1051" alt="CleanShot 2023-09-13 at 21 22 39@2x" src="https://github.com/elixir-lang/elixir/assets/12830256/a2a17811-a3c9-4b92-b586-dcaca50d1601">
