### ISSUE TITLE
Formatter removes necessary parentheses

### ISSUE THREAD

**Issue by LVala** [elixir-lang/elixir#12920]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.5 (compiled with Erlang/OTP 26)
```

### Operating system

MacOS Ventura 13.2

### Current behavior

Let's assume I have `my_file.exs` where I create a bitstring:

```elixir
len = 5

<<0::(len-1)*5>>
```
This works just fine, but when `mix format my_file.exs` is executed, the contents of the file change to:

```elixir
len = 5

<<0::len-1*5>>
```

which does not compile as it seems that the "unit" part (`5` in the first case, `1*5` above) has to be an integer literal. Of course, I could use `<<0::size(len-1)-unit(5)>>` but the above does not seem like a desired behaviour.

### Expected behavior

The bitstring `size*unit` shortcut syntax is formatted properly.

**Comment by sabiwara** [comment]
Thank you for reporting ❤️
Will take a look later
