### ISSUE TITLE
[ExUnit] No default rand_algorithm specified in examples.

### ISSUE THREAD

**Issue by dkuku** [elixir-lang/elixir#12939]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.15.5 (compiled with Erlang/OTP 24)

### Operating system

linux

### Current behavior

To reproduce:
```bash
cd lib/ex_unit
mix run examples/difference.exs
```
This returns only errors, lots of them but the repeated part is pasted below.
it's because the default rand_algorithm is not specified anywhere in the opts and `:rand.seed` receives `nil` as algorithm type which is invalid. When I edit the code and set a default value of `:exsss` then it works.
```elixir
14:46:19.179 [error] Error in process #PID<0.138.0> with exit value:
{:function_clause,
 [
   {:rand, :mk_alg, [nil], [file: ~c"rand.erl", line: 706]},
   {:rand, :seed_s, 2, [file: ~c"rand.erl", line: 297]},
   {:rand, :seed, 2, [file: ~c"rand.erl", line: 291]},
   {ExUnit.Runner, :"-spawn_test_monitor/4-fun-1-", 6,
    [file: ~c"lib/ex_unit/runner.ex", line: 390]}
 ]}
```
```elixir
     ** (EXIT from #PID<0.138.0>) an exception was raised:
     
          ** (FunctionClauseError) no function clause matching in :rand.mk_alg/1

          The following arguments were given to :rand.mk_alg/1:

              # 1
              nil

          stacktrace:
            (stdlib 5.0.2) rand.erl:706: :rand.mk_alg/1
            (stdlib 5.0.2) rand.erl:297: :rand.seed_s/2
            (stdlib 5.0.2) rand.erl:291: :rand.seed/2
            (ex_unit 1.15.5) lib/ex_unit/runner.ex:390: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4
```

### Expected behavior

There should be a fallback to a default random seed algorithm

**Comment by josevalim** [comment]
I cannot reproduce this. Please make sure that you ran `make compile` and you run it with `elixir examples/difference.exs`. We can't use `mix` inside Elixir projects themselves because `mix` may not have been defined.

**Comment by josevalim** [comment]
Btw, the default value is defined in the mix.exs file, in the application configuration. :)
