### ISSUE TITLE
Regression in Mix.Tasks.Format.formatter_for_file introduced in 1.15.5

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12930]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.5 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

Elixir 1.15.5 introduced a regression in formatter plugin loading making it no longer able to format `~H` sigils.

Repro:
1. mix phx.new formatter_regerssion
2. cd formatter_regerssion 
3. mix deps.get
4. break sigil formatting in lib/formatter_regerssion_web/components/core_components.ex
5. execute this script in iex

```
Mix.start()
Code.compile_file("mix.exs")
Mix.Task.run("loadconfig")
{f, o} = Mix.Tasks.Format.formatter_for_file("lib/formatter_regerssion_web/components/core_components.ex")
text = File.read!("lib/formatter_regerssion_web/components/core_components.ex") 
text == f.(text)
```
on 1.15.5 it returns `true`
on 1.15.4 it compiles before and then returns `false`

Even if  explicit `Mix.Task.run("compile")` is added on 1.15.5 it still produces a formatter not being able to format sigils.

Invoking `Code.format_string!` is also broken
```
IO.iodata_to_binary([Code.format_string!(text, o), ?\n]) == text
true
```

Most likely the regression was introduced in fixes for https://github.com/elixir-lang/elixir/issues/12880 (https://github.com/elixir-lang/elixir/commit/9f977be589879cc564a6dd06cc1902e4480d021e or https://github.com/elixir-lang/elixir/commit/dc8cfcd4c9538eae5a9324e81db3bafb7b58b01e)
Originally reported in https://github.com/elixir-lsp/elixir-ls/issues/975

### Expected behavior

Formatter should work when invoked via code. If plugin loading now requires some additional code this should be documented. Breaking changes should not be introduced in patch releases.

**Comment by josevalim** [comment]
I will investigate. Please do test the fix once it is out, since the previous commit was aiming to address another bug in Elixir LSP and the breaking change is non intentional.

**Comment by lukaszsamson** [comment]
> I will investigate. Please do test the fix once it is out, since the previous commit was aiming to address another bug in Elixir LSP and the breaking change is non intentional.

The previous fix was not related to Elixir LS at all

**Comment by josevalim** [comment]
@lukaszsamson oh, I thought that was the case, apologies. Anyway, please give it a try a now and let me know.

**Comment by lukaszsamson** [comment]
Thanks @josevalim, It's working fine again on 6654f1b9225a08357cf9e88d19aad8de69d8d1f7

**Comment by josevalim** [comment]
Excellent, i will ship a new version either this week or the beginning of next one.
