### ISSUE TITLE
Support multiple releases in `mix release`

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#12943]
We want to support:

```shell
mix release REL1 REL2 <...>
```

As long as the project is already compiled, we can even support doing this in parallel, either by default or behind a `--parallel` flag.

**Comment by josevalim** [comment]
We can do parallel by default. If we ask any question to the user, we also need to make sure we ask before we start the parallel generation. We need to check for uses of `Mix.shell()`.

**Comment by ghalestrilo** [comment]
Are PRs welcome on this?

**Comment by josevalim** [comment]
@whatyouhide, you mentioned you had plans to implement this. Please let us know the status or provide more information on implementation constraints so someone else can tackle it. :)

**Comment by whatyouhide** [comment]
Ooooph, please do tackle this 😄 I’m completely swamped. @ghalestrilo let us know if you do plan on giving this a try! :heart_decoration:

**Comment by josevalim** [comment]
After sleeping on this, I am actually thinking it does not need to be part of Elixir. First of all, while we should ensure our code can run in parallel, there is no guarantee third party steps, for example, run in parallel. Furthermore, you can implement this yourself by doing something like:

```elixir
aliases: ["par.release": &par_release/1] 
```

and then:

```elixir
def parse_release(_args) do
  Mix.Task.run("compile")
  task1 = Task.async(fn -> Mix.Task.rerun("release", ["foo"]) end)
  task2 = Task.async(fn -> Mix.Task.rerun("release", ["bar"]) end)
  Task.await(task1)
  Task.await(task2)
end
```

So I think we can go ahead and close this. :)

**Comment by lukaszsamson** [comment]
@josevalim I have a related question. I have an umbrella that has a few apps and a few common core apps and deps. I build a release for each of the apps and copy the output directory into one common docker image. The outcome is that common apps and deps beams are multiplicated in each of the apps and the resulting docker image is unnecessarily big. I solved that with a hacky bash script

```
#!/bin/bash
set -e
cd _build/prod/rel
mkdir my_umbrella

# copy all releases
cp -r app1/* my_umbrella
cp -r app1/* my_umbrella
cp -r app2/* my_umbrella

# start_erl.data is read on start and contains entry point app name so we drop it
rev my_umbrella/releases/start_erl.data | cut -d'-' -f2- | rev > my_umbrella/releases/start_erl.data.tmp
# drop final newline added by above
truncate -s -1 my_umbrella/releases/start_erl.data.tmp

rm my_umbrella/releases/start_erl.data
mv my_umbrella/releases/start_erl.data.tmp my_umbrella/releases/start_erl.data

# remove so we don't need to dockerignore
rm -r app1 \
    app2 \
    app3 
```

With that script I build my apps
```
mix release app1
mix release app2
mix release app3
./collect_releases.sh
```

and copy the output to docker image
```
COPY --chown=swuser:swuser _build/$MIX_ENV/rel/my_umbrella/ /opt/my_umbrella/
```

Then in docker entrypoint I exec the release I need by dispatching on command line argument
```
exec /opt/my_umbrella/bin/"$1" start
```

Would it make sense to support this usecase in mix?

**Comment by josevalim** [comment]
It may make sense to support that by supporting several bootscripts. Releases have the concept of bootscripts and we can provide several. Here is what you can do:

1. Add an optional called `:bootscripts` as a keyword list where the key name is the bootscript name and the value is a keyword list of applications (the same as allowed in `:applications` today)

2. Change `Mix.Release` to generate additional configuration for each additional bootscript

Now you can trigger another boot process with `RELEASE_BOOT_SCRIPT=bootscript bin/my_app`, where `RELEASE_BOOT_SCRIPT` is already supported today. A pull request to add this would be very welcome!

**Comment by lukaszsamson** [comment]
In my case it's not a boot time script but rather a build/release assemble time script

**Comment by josevalim** [comment]
Can you please expand on what you mean? Boot script is something specific to the VM that allows you to use the same release but starting different applications. I understand your script runs on assemble time, but I think the only way it makes sense to add this to Elixir is via custom boot scripts. If you need to diverge more than what boot scripts provide, then it is not possible.

**Comment by lukaszsamson** [comment]
My script besides making it possible to run multiple releases from the same docker image also deduplicates beam files coming from common dependencies. If that is not something commonly needed I'm totally fine with that not being supported out of the box
