### ISSUE TITLE
`mix deps.get` seems to not update to latest commit in a branch after the first fetch

### ISSUE THREAD

**Issue by pdgonzalez872** [elixir-lang/elixir#12948]
### Elixir and Erlang/OTP versions

```
deps_example [main] $ elixir --version
Erlang/OTP 25 [erts-13.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.14.1 (compiled with Erlang/OTP 25)
```

### Operating system

mac

### Current behavior

Hi!

I think there is some unexpected behavior when using `mix deps.get` with a git source and a target `branch` for a library.

If we use `branch` and run `mix deps.get` we fetch the commits and correctly use the last commit in the branch.

However, in subsequent `mix deps.get`s we don't seem to get the latest commit of the branch though, we get a success message "All deps up to date" instead.

Wouldn't the expected behavior be to run `mix deps.get` and have the branch always point to the latest possible commit in the branch?

I was able to repro the issue with the following repos:
- https://github.com/pdgonzalez872/deps_example <- this is the app that uses the library
- https://github.com/pdgonzalez872/deps_example_target <- this is the "library", using this branch: https://github.com/pdgonzalez872/deps_example_target/pull/1

Here is the library's repo's branch status:
```
deps_example_target [a_remote_branch] $ git log --oneline
2f62538 (HEAD -> a_remote_branch, origin/a_remote_branch) Add third commit to branch
8cbf194 Add second commit to branch
bf8f999 Add first commit to branch
c775b61 (origin/main, main) first commit
```

Here, I add the lib to the project and do a `mix deps.get` to pull the library branch when it was in it's second commit. I commit the changes to `main`. Then, I observe the behavior I'm trying to capture in this issue:
```
deps_example [main] $ git show | ag "+" -Q
+++ b/mix.exs
@@ -22,7 +22,7 @@ defmodule DepsExample.MixProject do
+      {:deps_example_target, git: "git@github.com:pdgonzalez872/deps_example_target.git", branch: "a_remote_branch"}
+++ b/mix.lock
@@ -0,0 +1,3 @@
+%{
+  "deps_example_target": {:git, "git@github.com:pdgonzalez872/deps_example_target.git", "8cbf194b4715bcfeaf386592fd1ade50c5519ddf", [branch: "a_remote_branch"]},
+}
deps_example [main] $ git status
On branch main
nothing to commit, working tree clean
deps_example [main] $ mix deps.get
All dependencies are up to date
deps_example [main] $ cat mix.lock
%{
  "deps_example_target": {:git, "git@github.com:pdgonzalez872/deps_example_target.git", "8cbf194b4715bcfeaf386592fd1ade50c5519ddf", [branch: "a
_remote_branch"]},
}
deps_example [main] $
```

Note how the "library" is at 2f62538, but mix.lock has it as 8cbf194b4715bcfeaf386592fd1ade50c5519ddf (the second commit).

Am I seeing this correctly?

Thanks for your work! ❤️ 

### Expected behavior

When we run subsequent `mix deps.get`s targeting a library's `branch`, I'd expect the latest commit available to be reflected in `mix.lock`, not just the latest commit when we fetched the deps for the first time.

**Comment by wojtekmach** [comment]
If there is no mix.lock, deps.get gets the latest version and writes the lock. If there is a mix.lock, deps.get gets the version from the lock. If you want to update, run mix deps.update. Does this make sense? Or am I misunderstanding the problem?

**Comment by josevalim** [comment]
Correct. Mix deps.get should always use the lock if one is available, otherwise everyone running the command to get up to date will now suddenly migrate to more recent versions.

**Comment by pdgonzalez872** [comment]
hi @wojtekmach ! ❤️ 

> Does this make sense? Or am I misunderstanding the problem?

It does. I think the fact that `mix deps.get` updates an existing `mix.lock` when a `tag/version` is changed is what tripped me up. My workflow for libs has always been to use the local path in the app code when developing, merging the lib code, getting a tag and then bumping the version in the app code. I was using `mix deps.get` for updating the app code's `mix.lock`. Somehow I went the remote branch this time, saw this behavior and thought to reach out.

Thanks for helping me see this the right way!

**Comment by wojtekmach** [comment]
Right if in your mix.exs you change to a different tag/branch then I believe it is as if the dep was never in mix.lock. We resolve it from scratch so to speak.

I believe this can be closed!

**Comment by pdgonzalez872** [comment]
makes sense! Thanks @wojtekmach @josevalim !
