### ISSUE TITLE
Wrong suffix _umbrella generated by mix phx.new

### ISSUE THREAD

**Issue by mksmtn** [elixir-lang/elixir#12971]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

### Operating system

Ubuntu 22.04.2 LTS

### Current behavior

I'm in `/workspaces/foo-live` folder. I'm doing `mix phx.new . --module Foo --app foo --umbrella`. The mix task is trying to create a project inside `/workspaces/foo-live_umbrella`. More precisely, I get an warning `The directory /workspaces/foo-live_umbrella already exists. Are you sure you want to continue?`, because the project was already generated inside this directory.

I've also tried specifying the full path `mix phx.new /workspaces/foo-live --module Foo --app foo --umbrella`. The behaviour is the same.

### Expected behavior

The mix task should not add the `_umbrella` suffix to the path. It should generate project files inside `/workspaces/foo-live`.

**Comment by josevalim** [comment]
This should be a bug reported to github.com/phoenixframework/phoenix :) Although I am pretty sure they are intentional about this. The root is foo-live_umbrella, the apps inside are called foo-live. In any case, the root name does not matter, you can rename it if you want.
