### ISSUE TITLE
Inspect never returns when inspect or dbg used in implementation

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#12974]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.6 (compiled with Erlang/OTP 26)

### Operating system

macOS

### Current behavior

Repro:
Execute this in iex
```
defmodule MyModule do
  defstruct [:a]
end

defimpl Inspect, for: MyModule do
  def inspect(term, opts) do
    dbg()
    Inspect.Algebra.string("MyModule")
  end
end

Inspect.inspect(%MyModule{}, [])
```

### Expected behavior

I guess making `inspect` or `dbg` in `Inspect` implementation a compile time error is impossible. A runtime error is more sane. Otherwise this should be documented

**Comment by josevalim** [comment]
Yes, this is pretty much expected. If you try to inspect or dbg anything inside an Inspect implementation, then you will enter an infinite loop. It is not something we can avoid at compile-time. It is a runtime issue and checking for accidental recursion will make the regular execution more expensive, for cases that only happen when developing new implementations.

If you find yourself deadlocked, you can always wrap inspection in a process, and abort after a timeout.
