### ISSUE TITLE
Unable to install elixir for more than a week now!

### ISSUE THREAD

**Issue by 1cbyc** [elixir-lang/elixir#12987]
### Elixir and Erlang/OTP versions

Unable to install elixir for more than a week now!

I am unable to install elixir on my HP ProLiant ML30 Gen10 for a week now. 

This url is not functioning: https://github.com/erlang/otp/releases/download/OTP-26.1.1/otp_win64_26.1.1.exe 

### Operating system

Windows

### Current behavior

I am unable to install elixir on my HP ProLiant ML30 Gen10 for a week now. 

This url is not functioning: https://github.com/erlang/otp/releases/download/OTP-26.1.1/otp_win64_26.1.1.exe 

### Expected behavior

It is supposed to download!

**Comment by 1cbyc** [comment]
> Could you please include some details? The URL not function is too vague. Do you get a 404? Does the file download but then the installer doesn't work? Could you list step by step what you did, what you expected to have happened, and what actually happened?

I used the installer, I kept getting errors whilst trying to run it.

**Comment by josevalim** [comment]
@1cbyc can you expand what error you got? Can you explain step by step? Can you show screenshot of errors or the steps that succeeded? Without more details, we can't really help, sorry.

**Comment by josevalim** [comment]
Closing this. If more information is provided, we will be glad to reopen and debug.
