### ISSUE TITLE
Missing byte when writing a streamed image to a file

### ISSUE THREAD

**Issue by koenusz** [elixir-lang/elixir#12986]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

### Operating system

6.2.0-33-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Sep  7 10:33:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Current behavior

I tried to test some functionality of capturing a stream into a file. For this purpose I streamed a file from the local File system to test my code. 

I noticed that the file almost completely got stored on disk, strangely there was just 1 byte missing from the file. However, this  did make the image a non valid jpg. 

In the end I reproduced the bug by cutting the code down to these two lines.
```elixir
    File.stream!(@image_path)
    |> Enum.into(File.stream!(@stream_path))
```
This gives the same result:
```elixir
    File.stream!(@image_path)
    |> Stream.into(File.stream!(@stream_path2))
    |> Stream.run()
```

I made a repo that reproduces the bug.
[repo](https://github.com/koenusz/stream_bug_test)

The missing byte is located at 2BE0 0B and its value is supposed to be 0D

Manually inserting it back to the image makes the jpg valid again.

### Expected behavior

I expect a jpg image to be stored on disk complete with that one missing byte.

**Comment by josevalim** [comment]
Stream streams by line, not including the line break (0D) itself. It is not safe for binary files. You must pass the third argument with the number of bytes to read.

**Comment by koenusz** [comment]
Solved the issue, Thank you!
