### ISSUE TITLE
multivar sigil inside a quote isn't respecting unquote

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/elixir#12999]
### Elixir and Erlang/OTP versions

Erlang/26
Elixir 1.15.5

### Operating system

MacOS 14.0

### Current behavior

```elixir
body = "a-b-c"

quote do
  def foobar(1, 2) do
    ~FOO"""
      #{unquote(body)}
    """
  end
end
|> Macro.to_string()
|> IO.puts()

quote do
  def foobar(1, 2) do
    ~s"""
      #{unquote(body)}
    """
  end
end
|> Macro.to_string()
|> IO.puts()
```

Results with this output:

```
def foobar(1, 2) do
  ~FOO"""
    #{unquote(body)}
  """
end
def foobar(1, 2) do
  ~s"""
    #{"a-b-c"}
  """
end
```

### Expected behavior

`~s` is respecting `unquote` and the interpolation is getting the string `"a-b-c"` which is `body`'s value, but `~FOO` which has an identical multiline string is *not* respecting `unquote` so its interpolation is now getting `unquote(body)`. I would exxpect both sigils to both `unquote` properly

**Comment by kipcole9** [comment]
Uppercase sigils aren't defined to support string interpolation (whether one character or many) which I think explains the result you are seeing.

**Comment by bcardarella** [comment]
@kipcole9 why would that matter for the `unquote` though? Shouldn't the syntax within the `quote` not matter prior to the replacement of `unquote`s?

**Comment by wojtekmach** [comment]
If I remember correctly the parser handles interpolations, changes AST from a “plain” string to a string with static abd dynamic pieces. Since it’s in the parser, if we used non-interpolated sigils like ~S, macros see a string `"unquote"` and there is nothing to expand.

**Comment by bcardarella** [comment]
@wojtekmach is there any way to instruct the compiler that a custom sigil should be interolated?

**Comment by kipcole9** [comment]
> If I remember correctly the parser handles interpolations

Yes, and I should have said so in my earlier response. Hence by the time of macro expansion, the sigil is already processed.

**Comment by sabiwara** [comment]
I think this is the intended behavior as described in the [docs](https://hexdocs.pm/elixir/main/sigils.html#interpolation-and-escaping-in-string-sigils): there is no interpolation, the fact it is `unquote` here does not change it.

> If I remember correctly the parser handles interpolations

Indeed it seems to be on the tokenizer level:
<img width="545" alt="Screenshot 2023-10-09 at 16 03 30" src="https://github.com/elixir-lang/elixir/assets/11598866/b90c7af4-3386-4224-9b26-4085d9ef2b15">

> is there any way to instruct the parser that a custom sigil should be interolated?

I think the simpler way is to use a lowercase sigil? (unfortunately these are not multi-letter).

**Comment by josevalim** [comment]
If you use EEx to parse code expressions for you, then you can use unquote as well. The unquote here is a red herring. Unquote will work fine if you use anything to parse the code snippets out (such as EEx).
