### ISSUE TITLE
Deprecated and undefined function warnings point to different places

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#12995]
### Elixir and Erlang/OTP versions

Main

### Operating system

Any

### Current behavior

This code:

```elixir
defmodule Foo do
  def bar do
    require Logger
    Logger.warn "OMG"
    Logger.unknown "OMG"
  end
end
```

emits:

```
$ elixir foo.exs
    warning: Logger.warn/1 is deprecated. Use Logger.warning/2 instead
    │
  4 │ Logger.warn "OMG"
    │        ~
    │
    └─ foo.exs:4:8: Foo.bar/0

    warning: Logger.unknown/1 is undefined or private
    │
  5 │ Logger.unknown "OMG"
    │       ~
    │
    └─ foo.exs:5:7: Foo.bar/0
```

Notice one points to the dot, the other to the function name. Preferences?

### Expected behavior

To be decided.

**Comment by whatyouhide** [comment]
@josevalim my 2c is that the function name is better, since that's the subject of the deprecation. Doesn't really matter though 🙃
