### ISSUE TITLE
Dependencies not yet available in command with `mix do deps.compile, [COMMAND]`

### ISSUE THREAD

**Issue by kevinschweikert** [elixir-lang/elixir#13000]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.6 (compiled with Erlang/OTP 26)

### Operating system

Docker 1.15.6-erlang-26.1-debian-bullseye-20230612-slim and macOS Ventura 13.5.2 (22G91)

### Current behavior

In our Dockerfile we have the line `mix do deps.compile, tailwind.install --if-missing, esbuild.install --if-missing`. After an update to Elxir 1.15 we get the following output:

```shell
16:05:02.552 [debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.3.2/tailwindcss-macos-arm64
** (ArgumentError) unknown application: :castore
    (elixir 1.15.6) lib/application.ex:1010: Application.app_dir/1
    (elixir 1.15.6) lib/application.ex:1037: Application.app_dir/2
    (tailwind 0.2.1) lib/tailwind.ex:280: Tailwind.fetch_body!/1
    (tailwind 0.2.1) lib/tailwind.ex:224: Tailwind.install/1
    (mix 1.15.6) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (elixir 1.15.6) lib/enum.ex:984: Enum."-each/2-lists^foreach/1-0-"/2
    (mix 1.15.6) lib/mix/task.ex:447: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.15.6) lib/mix/cli.ex:92: Mix.CLI.run_task/2
```

The issue can be recreated with the following steps:

```shell
mix phx.new do_compile_bug
cd do_compile_bug
mix deps.get
mix do deps.compile, tailwind.install --if-missing, esbuild.install --if-missing
```

When we separate the steps into:

```shell
mix compile
mix do tailwind.install --if-missing, esbuild.install --if-missing
```

it works.

### Expected behavior

The command `mix do deps.compile, tailwind.install --if-missing, esbuild.install --if-missing` should work as with Elixir 1.14

**Comment by josevalim** [comment]
This is a mix tailwind issue, so I pushed a commit there. I will also improve the docs on the Elixir side, thank you.
