### ISSUE TITLE
EEx - Adding a comment in after a case causes an error

### ISSUE THREAD

**Issue by Adzz** [elixir-lang/elixir#13002]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.3 (compiled with Erlang/OTP 25)

### Operating system

mac Ventura 13.5 (22G74)

### Current behavior

I'm opening an issue here because I think it's an EEx issue, but please let me know if I should open it somewhere else instead. If I have a template like this:

```elixir
~H"""
<%= case true do %>
  <% true -> %>
     It was true
<% end %>
"""
```

it renders as expected. If I do this:

```elixir
~H"""
<%= case true do %>
  <!-- This is a comment -->
  <% true -> %>
     It was true
<% end %>
"""
```

I get the following error:

```sh
== Compilation error in file lib/the_file.ex ==
** (SyntaxError) lib/the_file:241: unexpected operator ->. If you want to define multiple clauses, the first expression must use ->. Syntax error before: '->'
    (eex 1.14.3) lib/eex/compiler.ex:392: EEx.Compiler.generate_buffer/4
    (eex 1.14.3) lib/eex/compiler.ex:347: EEx.Compiler.generate_buffer/4
    (phoenix_live_view 0.18.18) expanding macro: Phoenix.Component.sigil_H/2
...
```

### Expected behavior

I would expect adding a comment should not affect it, but maybe that assumption is wrong! If so, I wonder if a better error is possible.

**Comment by josevalim** [comment]
There is nothing EEx can do here. EEx doesn't know about HTML, it doesn't know that text is a comment, and it doesn't know it is meaningless.

However, even if it knew HTML, `<!--` is actual text that goes on the template, not a comment. And, like in Elixir, you can't have anything between `do` and the first clause.
