### ISSUE TITLE
Mixed compile-time and runtime variables result in incremental build errors

### ISSUE THREAD

**Issue by deepankar-j** [elixir-lang/elixir#13014]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:11:10] [ds:11:10:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 25)
```

### Operating system

Ubuntu 20.04

### Current behavior

**Background**
This issue somewhat relates to [Issue 12411](https://github.com/elixir-lang/elixir/issues/12411), but the steps to reproduce are slightly different.  I'm raising this separate ticket for capturing the separate usage scenario, which may result in a different corrective action.

**The Issue**
When some config values for a given scope/module are compile-time, while others are runtime, incremental builds result in errors like:

```
ERROR! the application :my_app has a different value set for key Repo during runtime compared to compile time. Since this application environment entry was marked as compile time, this difference can lead to different behaviour than expected:
...
```

Here's an example snippet for one such use case.

```
# In config.exs
config :my_app, Repo,
  log_level: :warn,
  db_name: :foo,
  adapter: Ecto.Adapters.Postgres,
  metadata: [read_only: true]
  
  
 # In runtime.exs
 config :my_app, Repo,
   username: `System.get_env("DB_USERNAME") ,
   password: `System.get_env("DB_PASSWORD") 
   
 # In a module
@db_config Application.compile_env(:my_app, Repo)
 ```

Then, during incremental builds, we'd see errors like the one mentioned above.

**Workaround**
Thanks to the [tip from Wojtek Mach in this forum post answer](https://elixirforum.com/t/validating-compile-runtime-configuration-error-the-application-backend-has-a-different-value-set-for-key-basic-auth-during-runtime/32373/2), we found a workaround -- replace all uses of `compile_env` with `get_env`.

### Expected behavior

Ideally, `compile_env` should be able to handle keyword list level scoping for tracking whether the value has changed.  Currently, it only tracks at the scope/module level.   If that isn't easily feasible, this limitation for configs should be clearly documented.

**Comment by josevalim** [comment]
The error message is correct. `Application.compile_env` can deal with scoping, you need to give it a nested path:

    Application.compile_env(:my_app, [Repo, :username])

I will take a look at the docs and improve if something is missing.

**Comment by deepankar-j** [comment]
Thank you, @josevalim! 💚

That makes sense.  My bad for not realizing that compile_env supported path for the keys and that could result in better granularity for the variable tracking.
