### ISSUE TITLE
iex shell doesn't load .ex or .exs files

### ISSUE THREAD

**Issue by adrianbrink** [elixir-lang/elixir#13028]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.15.0 (compiled with Erlang/OTP 24)

### Operating system

Darwin two 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:43:05 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6020 arm64

### Current behavior

```elixir
defmodule Math do
  def sum(a, b) do
    a + b
  end

  def zero?(0) do
    true
  end
end
```
The above snippet is in a file called `math.exs` (or `math.ex`; it doesn't work either way).

Start iex with `iex math.exs` (outside of any project or mix environment or even git). I would expect that the Math module is available in my shell, since that's the way it's described in the getting started docs. I can manually load it with `c "math.exs" and then it's available. I receive no error when running `iex math.exs`.

Here is the full output (also with trying with `math.ex`):

```bash
➜  ex_scripts iex math.ex
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Interactive Elixir (1.15.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Math.sum(1,2)
** (UndefinedFunctionError) function Math.sum/2 is undefined (module Math is not available)
    Math.sum(1, 2)
iex(1)> c "math.ex"
[Math]
iex(2)> Math.sum(1,2)
3
iex(3)>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C%
➜  ex_scripts mv math.ex math.exs
➜  ex_scripts iex math.exs
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Interactive Elixir (1.15.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Math.sum(1,2)
** (UndefinedFunctionError) function Math.sum/2 is undefined (module Math is not available)
    Math.sum(1, 2)
iex(1)> c "math.exs"
[Math]
iex(2)> Math.sum(1,2)
3
iex(3)>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C%
```

### Expected behavior

I would expect that the Math module is available in the iex shell.

**Comment by adrianbrink** [comment]
A second step is to try and start iex with a broken file `iex math_broken.exs`.

```elixir
defmodule Math do
  def sum(a, b) do
    do_sum(a, b)
  end

  def zero?(0) do
    true
  end
end
```
This is in `math_broken.exs` (all the steps also work with `math_broken.ex`).

```bash
➜  ex_scripts iex math_broken.exs
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Interactive Elixir (1.15.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Math.sum(1,2)
** (UndefinedFunctionError) function Math.sum/2 is undefined (module Math is not available)
    Math.sum(1, 2)
iex(1)> c "math_broken.exs"
error: undefined function do_sum/2 (expected Math to define such a function or for it to be imported, but none are available)
  math_broken.exs:3: Math.sum/2


== Compilation error in file math_broken.exs ==
** (CompileError) math_broken.exs: cannot compile module Math (errors have been logged)

** (CompileError) compile error
    (iex 1.15.0) lib/iex/helpers.ex:182: IEx.Helpers.c/2
iex(1)> Math.sum(1, 2)
** (UndefinedFunctionError) function Math.sum/2 is undefined (module Math is not available)
    Math.sum(1, 2)
iex(1)>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C%
```

I would expect that an error gets thrown when starting iex and not only when trying to load the broken file with `c "math_broken.exs`. 

However the output above indicates otherwise.

**Comment by adrianbrink** [comment]
I can reconfirm the bug described in #12723.

Is there a fix/patch I could try?

**Comment by josevalim** [comment]
Please update to Elixir v1.15.7. The version (1.15.0) you are using indeed has this bug. :)
