### ISSUE TITLE
Enum.map returns nonsense

### ISSUE THREAD

**Issue by harpetersen** [elixir-lang/elixir#13025]
### Elixir and Erlang/OTP versions

**For one attempt:**
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)

**As well as**

Elixir 1.15.1

(no elixir --version output, as this was uninstalled to install 1.12.2)

**As well as**

Whatever version https://www.tutorialspoint.com/execute_elixir_online.php uses.

### Operating system

Linux: pop_OS! 22.04 & Online

### Current behavior

Per this stack [overflow question](https://stackoverflow.com/questions/77333957/elixir-enum-map-giving-odd-responses-for-higher-values): 

these iex commands in linux give the following odd responses

```
    iex(1)> Enum.map([2, 3, 4], fn x -> x * 10 end)
    [20, 30, 40]
    iex(2)> Enum.map([4, 6, 8], fn x -> x * 10 end)
    '(<P'
```
    

Double-checking with an online code pad [here](https://www.tutorialspoint.com/execute_elixir_online.php), I attempted similar to see if it changed results. 

Where this code:

```
a = Enum.map([2, 3, 4], fn x -> x * 10 end)
b = Enum.map([4, 6, 8], fn x -> x * 10 end)
IO.puts "Program Start"
IO.inspect a
IO.inspect b
IO.puts "Program End"
```
    
Gave this response
```

Program Start
[20, 30, 40]
'(<P'
Program End
```

### Expected behavior

    iex(1)> Enum.map([2, 3, 4], fn x -> x * 10 end)
    [20, 30, 40]
    iex(2)> Enum.map([4, 6, 8], fn x -> x * 10 end)
    [40, 60, 80]

**Comment by harpetersen** [comment]
As the tutorialspoint version was a .php, that means it's likely running on apache or nginx, which would imply their server is also linux. 

I was unable to test on windows or mac, but if it works in either of those, it could be a linux-specific issue; but it's not version or environment-specific between linux versions.

**Comment by wojtekmach** [comment]
This is not a bug. Please see https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#charlists
