### ISSUE TITLE
Column info in Module.get_definition/2

### ISSUE THREAD

**Issue by mhanberg** [elixir-lang/elixir#13029]
Originally opened on the Elixir Forum (https://elixirforum.com/t/how-to-find-function-clause-column-information/59177), cross posting here at the request of Jose.

---

Currently I am able to acquire the line for a function clause definition using the `:on_module` tracer event, similar to the following code

```elixir
  def trace({:on_module, bytecode, _}, env) do
    defs = Module.definitions_in(env.module)

    defs =
      for {name, arity} = _def <- defs do
        {name, Module.get_definition(env.module, {name, arity})}
      end
  
    :ok
  end
```

When I eventually loop through each function and its clauses, I get a structure that looks like this:

```elixir
{[line: 943], ["defmodule"], [],
 {{:., [line: 943, column: 80], [GenLSP.Enumerations.SymbolKind, :module]},
  [closing: [line: 943, column: 88], line: 943, column: 81], []}}
```

which corresponds to the following code snippet:

```elixir
  defp elixir_kind_to_lsp_kind("defmodule"), do: GenLSP.Enumerations.SymbolKind.module()
```

As you can see here, the metadata includes the line `[line: 943]`, but not the column. I currently use `columns: true` for the compiler options, but the column doesn't seem to show up here.

Would you know if I'm doing something wrong here?

**Comment by josevalim** [comment]
Can you please provide a small app or script that reproduces this btw? :)

**Comment by mhanberg** [comment]
Yes, I'll get you that today!

**Comment by mhanberg** [comment]
@josevalim luckily I already had a demo app that was 90% of the way there: https://github.com/mhanberg/tracer_demo

Thanks!

**Comment by mhanberg** [comment]
Thanks José!
