### ISSUE TITLE
Wrong unused import warning

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#1303]
The example below emits a unused import warning even if `from` is imported and used from `Ecto.Query`. That's because the code is evaluated in another module, losing it's original context.

One solution is so start the dispatch tracker per file too or tag the macro contents with the original module.

``` elixir
Code.require_file "../test_helper.exs", __DIR__

defmodule Ecto.QueryTest do
  use ExUnit.Case

  import Ecto.Query

  defmacrop delay_compile(block) do
    quote do
      defmodule Sample do
        unquote(block)
      end
    end
  end

  test "from check" do
    assert_raise ArgumentError, "from expressions must be in `var in Record` format", fn ->
      delay_compile do: from(x + 1)
    end
  end
end
```

**Comment by sraka1** [comment]
@josevalim is there at least a way to suppress the warning in such a case? I have the exact same use-case (usage of Ecto.Query imports in a macro, which is then executed in another module) and am seeing the unused import warning (Elixir v1.14.5).

**Comment by josevalim** [comment]
You can pass warn: false.
