### ISSUE TITLE
Clarify how to use the /rel/overlays script files in Umbrella

### ISSUE THREAD

**Issue by francois08** [elixir-lang/elixir#13038]
### Elixir and Erlang/OTP versions

Elixir 1.14.4 (compiled with Erlang/OTP 25)

### Operating system

Windows

### Current behavior

When running the release for a specific Umbrella app, the files under `/rel/overlays/bin` are not copied (and so I am missing the `migration` script).

```elixir
MIX_ENV=prod mix release foo_app_release
```

However when running `mix release` without specifying an app name, the files are copied into the release as documented.

In an Umbrella app, we list the releases in the `mix.exs` file and from the root we may execute `mix release <release_name>`. However the files under `rel/overlays/bin` are not copied.

This could be an example structure:
```
- foo_app
    - rel
      - overlays/bin
         - migrate
         - server
- bar_app
    - rel
      - overlays/bin
         - migrate
         - server
```

Actually while I'm writing this I realize one release may contain multiple `applications`, and so there should be a way to specify for a release where the overlay files are so that they can be copied...?

**Comment by francois08** [comment]
It seems that by moving the /rel directory in the root folder, th files will get copied, but in that case how to we specify the app that is currently being deployed?

E.g.
```bash
#!/bin/sh
cd -P -- "$(dirname -- "$0")"
exec ./foo_app eval FooApp.Release.migrate
```
How do we make `exec ./foo_app eval FooApp.Release.migrate` dynamic so it works for ou `bar_app` too?

**Comment by josevalim** [comment]
Yes, the release always runs from the directory you call the command. You can use the `:applications` key to configure what applications are loaded/running/etc but my general suggestion would be to release specific applications. :)

**Comment by francois08** [comment]
We have the `:releases` key in `mix.exs` which allows me to execute:
> mix release <release_name>

The problem with that is that I would have to update the content of the rel scripts every time (as the paths in the rel scripts are hard coded which doesn't suit me in a multi-app context).

Your suggestion is to not rely on the command with the release as parameter name, but instead execute `mix release` inside the specific app? Then I just ditch `: releases`?

Sorry for not understanding straight away 😅

How about we pass the `<release_name>` argument passed to `mix release` as some parameter in the `rel` script somehow and adapt the scripts to use that parameter so we can just use that command in an Umbrella app with multiple independently deployable apps?

**Comment by josevalim** [comment]
You can still use `:releases` inside each individual app. My point was just that, if you want to have multiple releases scripts, with different templates/overlays based on the child application, then that's a sign you want to move the release process to particular applications. I tend to prefer the most specific approach, but it is just a suggestion, I don't have access to your code, you will definitely know better. :)

> let the developer explicitly specify a path for the rel scripts in :releases config, optionally:

Already possible via `rel_templates_path`.
