### ISSUE TITLE
IEx should allow returning to a prompt from a blocking task in a user friendly manner

### ISSUE THREAD

**Issue by deliciouslytyped** [elixir-lang/elixir#13032]
I feel like I'm missing something here, I couldn't find any other issues for this.

There does not seem to be an easy way to interrupt a blocking task (like https://stackoverflow.com/questions/48867809/why-my-receive-method-is-stopping-my-iex) in iex, similar to how you can ^C in a linux shell.

^C in iex brings up the interrupt menu, but there is no easy way to kill the current task and return to a prompt. The kill submenu appears to allow cycling through running tasks, but there is no easy way to tell which task corresponds to the blocking task.

**Comment by deliciouslytyped** [comment]
This is a separate issue, but it would be nice to make solutions common issues with handling iex more prominent for new users, or just fix things so they aren't a problem at all.

- The other major issue I ran into as a new user is handling mistyped expressions, where the only way to exit the multiline prompt is with #iex;break at the very beginning of a line. This is int he documentation, but I had to resort to googling and it's a bit obscure.
- The ^G menu is a bit obscure.

**Comment by josevalim** [comment]
In this case, Elixir uses the Erlang shell, so you should suggest those improvements upstream. erlangforums.com is potentially a good place to get started.

One possible explanation for this is that the Ctrl+C menu shows up even when not running the shell, so it may not be straightforward to cause it to not interrupt. In any case, all options are listed under IEx docs.
