### ISSUE TITLE
Issue with 1.15.6 and Code loading

### ISSUE THREAD

**Issue by epinault** [elixir-lang/elixir#13116]
### Elixir and Erlang/OTP versions

OTP26
Elixir 1.15.x

### Operating system

OSX, Debian

### Current behavior

hello,

 I am finding an issue that maybe is something not yet implemented but in OTP 26 the follow code breaks

Mix.Task.get("phx.new") now returns nil

I had a mix task that tries to detect if phoenix is installed by detecting the mix task above. All worked till OTP 26. but in OTP 26 it cannot find the code being loaded somehow. Any idea ? We are seeing that a lot with atom (to_existiing_atom failing in our code base and having to force loading the module before so the atom are available)

To make the repo easy, I create a simple repro repo . Steps to follow

1. Clone the repo https://github.com/epinault/elixir-1-15-repro
2. I use asdf but you can see the default version is 1.15 and OTP25
3. run `mix local.hex`
4. run `mix archive.install hex phx_new`
5. now compile the project and run `mix my_test`
6. you will see 
```
[lib/mix/tasks/test.ex:8: Mix.Tasks.MyTest.run/1]
Mix.Task.get("phx.new") #=> nil
```

The same process was repeated with the following version and I will show the output for each

OTP 25.3.2.3 and Elixir 1.14.5
```
[lib/mix/tasks/test.ex:8: Mix.Tasks.MyTest.run/1]
Mix.Task.get("phx.new") #=> Mix.Tasks.Phx.New
```

OTP 26.1.1 and Elixir 1.14.5
```
[lib/mix/tasks/test.ex:8: Mix.Tasks.MyTest.run/1]
Mix.Task.get("phx.new") #=> Mix.Tasks.Phx.New
```

OTP 25.3.2.3 and Elixir 1.15.6
```
[lib/mix/tasks/test.ex:8: Mix.Tasks.MyTest.run/1]
Mix.Task.get("phx.new") #=> nil
```

OTP 26.1.1 and Elixir 1.15.6
```
[lib/mix/tasks/test.ex:8: Mix.Tasks.MyTest.run/1]
Mix.Task.get("phx.new") #=> nil
``` 

### Expected behavior

the Mix.Task.get("phx.new") would return the actual Module for that mix task and so it can be called
as such in all cases

[lib/mix/tasks/test.ex:8: Mix.Tasks.MyTest.run/1]
Mix.Task.get("phx.new") #=> Mix.Tasks.Phx.New

**Comment by josevalim** [comment]
Thank you for the report. Elixir v1.15 has a feature called "code path pruning", where it only keeps what you explicitly list as a dependency in your mix.exs. This is done for performance and to help avoid surprises in production where you call something that you did not include as a dependency. You can set `prune_code_paths: false` in your `mix.exs` and it will revert to Elixir's v1.14 behaviour.

**Comment by epinault** [comment]
ok that fixed it for this case! since I can never have that dependency and expect it to be installed  as an archive. Maybe I need to find a better way to detect it but that was the cheap way since it shows as a task your project list once installed

**Comment by josevalim** [comment]
How do people use your project? Is it also as an archive? Then you can probably check when you start if `phx_new` is also available and abort otherwise.

**Comment by epinault** [comment]
right now it s not an archive and we had it as an escript but ran into some issue. so we just clone the repo and use as a command mix within the repo (not great). Really we would want it to be a binary/release that people can run . The project is to basically do code generation on top of phoenix to build more opinions or more complete setup of a service we build (dockerfile, dialyzer configured etc etc)

**Comment by josevalim** [comment]
If it is an escript, then you could list both mix and phx_new as a dependency and then invoke it as Mix.Task.run.

**Comment by josevalim** [comment]
Closing this one for now!
