### ISSUE TITLE
variable in if statement available also in else

### ISSUE THREAD

**Issue by dvic** [elixir-lang/elixir#13110]
### Elixir and Erlang/OTP versions

1.15.7

### Operating system

Mac OS X

### Current behavior

```elixir
if foo = false do
  IO.puts("yes")
else
  IO.puts("no: #{foo}")
end
```

Currently compiles fine and prints `no: false`. Is this working as intended? I could not find anything about this in the docs.

### Expected behavior

Above should emit a warning that 'foo' is not found?

**Comment by josevalim** [comment]
Yes, this is intentional. Think it compiles the same as:

```
foo = false 

case !!foo do
  true -> ...
  false -> ...
end
```

If you would like to submit a PR to improve the docs, it will be welcome.

**Comment by josevalim** [comment]
Closing this for now, PRs still welcome :)

**Comment by dvic** [comment]
> Closing this for now, PRs still welcome :) 

On its way :)

Quick question though: any idea why these docs fail to compile:

![image](https://github.com/elixir-lang/elixir/assets/1214337/adb25d63-32e9-4f0b-871f-056b09b86bcf)

the error is:

```
❯ make docs
make[1]: Nothing to be done for `unicode'.
==> elixir (compile)
      error: undefined variable "foo"
      │
 3823 │   >       IO.puts("no: #{foo}")
      │                          ^^^
      │
      └─ lib/kernel.ex:3823:26: Kernel (module)


== Compilation error in file lib/kernel.ex ==
** (CompileError) lib/kernel.ex: cannot compile module Kernel (errors have been logged)
    (elixir 1.17.0-dev) expanding macro: Kernel.to_string/1
    lib/kernel.ex:3823: Kernel (module)
    (elixir 1.17.0-dev) expanding macro: :elixir_bootstrap.@/1
    lib/kernel.ex:3776: Kernel (module)
make: *** [lib/elixir/ebin/Elixir.Kernel.beam] Error 1
```

I was able to successfully compile the docs without the newly introduced part.

By the way, this is what the if macro ends up with:

```elixir
 defp build_if(condition, do: do_clause, else: else_clause) do
    optimize_boolean(
      quote do
        case unquote(condition) do
          x when :"Elixir.Kernel".in(x, [false, nil]) -> unquote(else_clause)
          _ -> unquote(do_clause)
        end
      end
    )
  end
```

So that explains why the binding is available in the else clause :)

**Comment by josevalim** [comment]
You are interpolating inside the `@doc """`. Either escape the interpolation or change it to `@doc ~S"""`.
