### ISSUE TITLE
Logs in on_exit are not captured

### ISSUE THREAD

**Issue by colinsmetz** [elixir-lang/elixir#13111]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 24)

### Operating system

Ubuntu 22.04.3 LTS

### Current behavior

Hello!

Since Elixir 1.15.0, it seems that calls to Logger that are happening inside an `on_exit` in a test are not captured when using the `capture_log: true` option.

Minimal reproducible example:

```elixir
# test_helper.exs
ExUnit.start(capture_log: true)

# bug_capture_log_test.exs
defmodule BugCaptureLogTest do
  use ExUnit.Case
  require Logger

  test "should not display any log" do
    on_exit(fn -> Logger.warning("Hey!") end)
  end
end
```

With Elixir 1.14.5:

```
$ mix test
.
Finished in 0.01 seconds (0.00s async, 0.01s sync)
1 test, 0 failures
```

With Elixir 1.15.0 (and 1.15.7):

```
$ mix test

17:31:48.486 [warning] Hey!
.
Finished in 0.01 seconds (0.00s async, 0.01s sync)
1 test, 0 failures
```

### Expected behavior

I expect all the logs to be captured and not displayed on stdout when using `capture_log: true`, even when using `on_exit`.

**Comment by josevalim** [comment]
You will have to wrap in `capture_log` inside `on_exit`. That's because `on_exit` runs on a completely separate process than the test one by design, as that's how we can guarantee it works,. and `capture_log` is tied to the process that calls it.

**Comment by colinsmetz** [comment]
Thanks for the reply.

I am well aware that `on_exit` runs on a separate process than the test one, however I still find this new behaviour frustrating and counter-intuitive. I would understand that in the following case, the log would be displayed, as I'm aware that the `on_exit` runs later on, outside of the `capture_log`:

```elixir
  test "should not display any log" do
    ExUnit.CaptureLog.capture_log(fn ->
      on_exit(fn ->
        Logger.warning("Oh no.")
      end)
    end)
  end
```

However, in my case, the `capture_log` is configured when calling `ExUnit.start`, which runs all the test suite. So I expect the parameter to apply to *the entire test suite* and not make an exception for the `on_exit`.

Now this is just my feeling. I understand that this might not be the place for debating new behaviours that might have been planned, so I won't insist further here, and we will try to find other solutions to get rid of all the undesired logs.

**Comment by josevalim** [comment]
@colinsmetz in this case, wouldn't be better to disable logging altogether? `capture_log` would still work per test.

**Comment by colinsmetz** [comment]
You're right, it seems that would work> Thanks for the help! :bow:
