### ISSUE TITLE
Connecting to a running release without `$HOME` set fails

### ISSUE THREAD

**Issue by Munksgaard** [elixir-lang/elixir#13127]
### Elixir and Erlang/OTP versions

```
$ elixir --version
Erlang/OTP 25 [erts-13.2.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.6 (compiled with Erlang/OTP 25)
```

### Operating system

Linux/NixOS

### Current behavior

I am running an Elixir release as a systemd service. The service-definition looks something like this (simplified/redacted):

```
[Unit]
Description=My App

[Service]
Type=notify
ExecStart=/nix/store/[hash]/bin/my_app start
DynamicUser=true
WorkingDirectory = "/run/my_app";
StateDirectory = "my_app";
RuntimeDirectory = "my_app";
```

This works great, until I try to connect to the running service using `my_app remote`. I get the following error:

```
$ my_app remote
Erlang/OTP 25 [erts-13.2.2.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.6) - press Ctrl+C to exit (type h() ENTER for help)
*** ERROR: Shell process terminated! (^G to start new job) ***

09:55:36.659 [error] Process #PID<10530.2743.0> on node :"app@my-app" raised an exception
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a pid

    :erlang.monitor(:process, {:error, {%RuntimeError{message: "could not find the user home, please set the HOME environment variable"}, [{System, :user_home!, 0, [file: ~c"lib/system.ex", line: 375, error_info: %{module: Exception}]}, {Path, :resolve_home, 1, [file: ~c"lib/path.ex"
, line: 716]}, {Path, :expand, 1, [file: ~c"lib/path.ex", line: 166]}, {Enum, :"-map/2-lists^map/1-1-", 2, [file: ~c"lib/enum.ex", line: 1693]}, {Enum, :"-map/2-lists^map/1-1-", 2, [file: ~c"lib/enum.ex", line: 1693]}, {IEx.Evaluator, :load_dot_iex, 2, [file: ~c"lib/iex/evaluator.ex"
, line: 256]}, {IEx.Evaluator, :init, 5, [file: ~c"lib/iex/evaluator.ex", line: 28]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 240]}]}})
    lib/iex/server.ex:89: IEx.Server.run_without_registration/3

BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
^C
```

After a bit of diagnostics, it seems like the problem is that iex expects $HOME to be set for the user running the release. However, that is not the case here, because we are using a dynamic (ephemeral) service.

Specifically, it looks like [`load_dot_iex`](https://github.com/elixir-lang/elixir/blob/82a03f6b045f18fbfe9738fefca0cfe43838731a/lib/iex/lib/iex/evaluator.ex#L257) results in a call to `System.home!/0` [here](https://github.com/elixir-lang/elixir/blob/82a03f6b045f18fbfe9738fefca0cfe43838731a/lib/elixir/lib/path.ex#L832), which raises the runtime error seen above.

Note that `$HOME` _is set_ for the user that is attempting to connect, but not for the user running the release.

### Expected behavior

It should be possible to attach to a release that is running as a user without `$HOME` set.

**Comment by Munksgaard** [comment]
Thanks!

**Comment by Munksgaard** [comment]
@josevalim Seems like the fix didn't make it into 1.16, was that on purpose?

**Comment by josevalim** [comment]
@Munksgaard accident. I will backport it.

**Comment by Munksgaard** [comment]
Thank you :heart:
