### ISSUE TITLE
No compiler warning on unused root-level aliases

### ISSUE THREAD

**Issue by novaugust** [elixir-lang/elixir#13146]
### Elixir and Erlang/OTP versions

elixir 1.14.2

### Operating system

macos

### Current behavior

no unused warning for root-level aliases:
```
iex(1)> defmodule Bar do
...(1)>   alias Foo
...(1)> end
{:module, Bar, ......}
```
whereas there is a warning if `as:` is used
```
iex(2)> defmodule Bar do
...(2)>   alias Foo, as: Fop
...(2)> end
warning: unused alias Fop

{:module, Bar, ......}
```

certainly it's valid to say "why would anyone alias a root-level module name in the first place", but as long as the language allows it it might as well warn on the issue =)

### Expected behavior

I'd expect to see an "unused alias" compiler warning

Ideally, I'd even like a "this code does nothing" compiler warning to help developers keep their codebases neat and tidy, but [i've got ways to take care of that otherwise ^.^](https://github.com/adobe/elixir-styler/issues/87)

**Comment by novaugust** [comment]
i'd be happy to take a stab at the "don't do that" warning assuming https://github.com/elixir-lang/elixir/commit/50579b41db16100eb2ded21530830a32a09c32ec makes a good template

**Comment by wojtekmach** [comment]
You mentioned you’re on Elixir 1.14.2, double check if the bug happens on Elixir main or latest version, 1.16.0-rc, perhaps it was fixed since.

**Comment by milmazz** [comment]
> perhaps it was fixed since.

No

```elixir
main   ./bin/iex
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Interactive Elixir (1.17.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule Bar do
...(1)> alias Foo
...(1)> end
{:module, Bar,
 <<70, 79, 82, 49, 0, 0, 4, 92, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 161,
   0, 0, 0, 16, 10, 69, 108, 105, 120, 105, 114, 46, 66, 97, 114, 8, 95, 95,
   105, 110, 102, 111, 95, 95, 10, 97, 116, ...>>, Foo}
iex(2)> defmodule Bar do
...(2)> alias Foo, as: Fop
...(2)> end
warning: redefining module Bar (current version defined in memory)
└─ iex:2: Bar (module)

warning: unused alias Fop
└─ iex:3

{:module, Bar,
 <<70, 79, 82, 49, 0, 0, 4, 92, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 161,
   0, 0, 0, 16, 10, 69, 108, 105, 120, 105, 114, 46, 66, 97, 114, 8, 95, 95,
   105, 110, 102, 111, 95, 95, 10, 97, 116, ...>>, Foo}
```

```console
git rev-parse --short HEAD
ba2e56954
```

**Comment by josevalim** [comment]
This happens in this case because no alias is defined:

```elixir
Interactive Elixir (1.17.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> alias Foo, as: Foo
Foo
iex(2)> __ENV__.aliases
[]
```

We could warn in this case in general but it was also added to support meta-programming, so you can also alias root modules without having to special case them. Otherwise, it works:

```elixir
iex(3)> defmodule Foo do
...(3)> alias Bar.Baz
...(3)> end
warning: unused alias Baz
└─ iex:4
```

Given this is a minor exception, I will close this one for now. :)
