### ISSUE TITLE
1.16 compile error messages are more difficult to parse and contain ANSI control codes

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#13142]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.16.0-rc.0 (aa0dcb9) (compiled with Erlang/OTP 26)

### Operating system

any

### Current behavior

This is not something that is new to 1.16 but each version makes it more difficult to extract structured information from Mix.Task.Compiler.Diagnostic

This simple repro app, when compiled, returns inadequate information - the file is not the one that is broken. The correct one needs to be extracted from the message.

In previous versions the file could be extracted with a regex relatively easily but now it's difficult to do reliably. In this example it's not clear where the file part and message part is:
```
** (SyntaxError) invalid syntax found on lib/template.eex:2:5:
```

Moreover, there are ANSO codes in a message that is not intended for terminal
```
   │ \e[31m    ^\e[0m\n    │\n    └─ 
```

Repro:
1. git clone https://github.com/lukaszsamson/build_errors_on_external_resource
2. cd build_errors_on_external_resource
3. in iex run
```
Mix.start()
Code.compile_file("mix.exs")
Mix.Task.run("compile", ["--return-errors"])
```
```
Compiling 1 file (.ex)

== Compilation error in file lib/has_error.ex ==
** (SyntaxError) invalid syntax found on lib/template.eex:2:5:
    error: syntax error before: ','
    │
  2 │  , 
    │     ^
    │
    └─ lib/template.eex:2:5
    lib/eex/compiler.ex:332: EEx.Compiler.generate_buffer/4
    lib/has_error.ex:2: (module)
{:error,
 [
   %Mix.Task.Compiler.Diagnostic{
     file: "/Users/lukaszsamson/bug_repro/build_errors_on_external_resource/lib/has_error.ex",
     severity: :error,
     message: "** (SyntaxError) invalid syntax found on lib/template.eex:2:5:\n    \e[31merror:\e[0m syntax error before: ','\n    │\n  2 │  , \n    │ \e[31m    ^\e[0m\n    │\n    └─ lib/template.eex:2:5\n    lib/eex/compiler.ex:332: EEx.Compiler.generate_buffer/4\n    lib/has_error.ex:2: (module)\n",
     position: {2, 5},
     compiler_name: "Elixir",
     span: nil,
     details: nil,
     stacktrace: [
       {EEx.Compiler, :generate_buffer, 4,
        [file: ~c"lib/eex/compiler.ex", line: 332]},
       {:elixir_compiler_0, :__MODULE__, 1,
        [file: ~c"lib/has_error.ex", line: 2]},
       {:elixir_compiler, :dispatch, 4,
        [file: ~c"src/elixir_compiler.erl", line: 67]},
       {:elixir_compiler, :compile, 3,
        [file: ~c"src/elixir_compiler.erl", line: 52]},
       {:elixir_module, :eval_form, 7,
        [file: ~c"src/elixir_module.erl", line: 424]},
       {:elixir_module, :compile, 7,
        [file: ~c"src/elixir_module.erl", line: 128]},
       {:elixir_compiler, :maybe_fast_compile, 3,
        [file: ~c"src/elixir_compiler.erl", line: 38]}
     ]
   }
 ]}
```

### Expected behavior

Structured info returned as map in `details` with error returned as struct/tuple. error stacktrace returned as list. Stringified message without ANSI codes.

**Comment by josevalim** [comment]
Thank you, we will review this before we ship it. The file needs to be correct and we will see if we can move the snippet to its own field.

**Comment by lukaszsamson** [comment]
> The file needs to be correct

It was not correct in previous releases but the error message was more predictable so it was relatively easy to extract

**Comment by lukaszsamson** [comment]
```
** (TokenMissingError) token missing on lib/abc.ex:4:1:
   error: missing terminator: end (for "fn" starting at line 1)
   └─ lib/abc.ex:4:1
```
TokenMissingError also has some context info - the position is `{4, 1}` but important info relates to line 1. It would be great if this could be fetched without regexes

**Comment by scottming** [comment]
I'm aware that Elixir 1.16 has made significant improvements in the presentation of diagnostics. However, I'd like to ask if it's possible for us to use a different field to represent the original message or the formatted message.

The reason behind this is that I believe editor clients and command-line interfaces have different focuses when it comes to displaying messages. Command-line interfaces may benefit from a more visually appealing presentation to enhance clarity during runtime.

On the other hand, editors prioritize accuracy in positioning, and messages are expected to be concise without any extra information.

For example, regarding diagnostics for undefined variables, the editor might only be concerned with the message on the first line.

![CleanShot 2023-11-27 at 17 26 04@2x](https://github.com/elixir-lang/elixir/assets/12830256/21d32b37-5bb0-45b7-9b1f-071ed93a68d5)

![CleanShot 2023-11-27 at 17 22 29@2x](https://github.com/elixir-lang/elixir/assets/12830256/cc7746a7-641d-469b-9d5b-18dff7cb5e4a)

Of course, if we can easily extract important information from the formatted message, that would be great too.

**Comment by josevalim** [comment]
@lukaszsamson we are now adding the exception under the `details` field of the diagnostic. I do have one favor, however. You will probably need to access some of the exception fields, such as line, column, etc. Please submit a PR updating the docs to mark all fields that you access as public. :)

@scottming I have verified that the diagnostic for undefined variables does no include the snippet, so what you requested should already be good to go. If not, please let me know.

**Comment by lukaszsamson** [comment]
> Please submit a PR updating the docs to mark all fields that you access as public

Doesn't the usual rule _not underscored_ => _public_ apply here?

**Comment by josevalim** [comment]
I don't think this has ever been the case for struct. It is also not the case for module names as well, for obvious reasons. It only applies to functions really.

**Comment by lukaszsamson** [comment]
What about ANSI control codes in the diagnostic messages? In case of ElixirLS I explicitly disable ANSI with 
```
Application.put_env(:elixir, :ansi_enabled, false)
```

**Comment by lukaszsamson** [comment]
@josevalim this is still not working as expected. Retested on 28f8eba9a2ffdc91d192ea949b21b1250220351d. Notice that file is still invalid (though in detail it is correct). The message is not optimal for programmatic usage (I discard it completely and use what `Exception.format_banner` returns)
```
{:error,
 [
   %Mix.Task.Compiler.Diagnostic{
     file: "/Users/lukaszsamson/bug_repro/build_errors_on_external_resource/lib/so mo/has_error.ex",
     severity: :error,
     message: "** (SyntaxError) invalid syntax found on lib/template.eex:2:5:\n    \e[31merror:\e[0m syntax error before: ','\n    │\n  2 │  , \n    │ \e[31m    ^\e[0m\n    │\n    └─ lib/template.eex:2:5\n    lib/eex/compiler.ex:332: EEx.Compiler.generate_buffer/4\n    lib/so mo/has_error.ex:2: (module)\n",
     position: {2, 5},
     compiler_name: "Elixir",
     span: nil,
     details: {:error,
      %SyntaxError{
        file: "lib/template.eex",
        line: 2,
        column: 5,
        snippet: " , ",
        description: "syntax error before: ','"
      }},
     stacktrace: [
       {EEx.Compiler, :generate_buffer, 4,
        [file: ~c"lib/eex/compiler.ex", line: 332]},
       {:elixir_compiler_0, :__MODULE__, 1,
        [file: ~c"lib/so mo/has_error.ex", line: 2]},
       {:elixir_compiler, :dispatch, 4,
        [file: ~c"src/elixir_compiler.erl", line: 67]},
       {:elixir_compiler, :compile, 4,
        [file: ~c"src/elixir_compiler.erl", line: 52]},
       {:elixir_module, :eval_form, 7,
        [file: ~c"src/elixir_module.erl", line: 426]},
       {:elixir_module, :compile, 7,
        [file: ~c"src/elixir_module.erl", line: 128]},
       {:elixir_compiler, :maybe_fast_compile, 3,
        [file: ~c"src/elixir_compiler.erl", line: 38]}
     ]
   }
 ]}
```

**Comment by josevalim** [comment]
It looks like an EEx bug. I will take a look at it tomorrow!

**Comment by josevalim** [comment]
@lukaszsamson this is really tricky. :( We need the :file in the diagnostic to match the file being compiled, because we use it to know to track diagnostics to their source files. We probably need a new field.

**Comment by lukaszsamson** [comment]
> We need the :file in the diagnostic to match the file being compiled

OK. I can workaround that and get the correct file and position/span from details. But if we go that way then please make sure that the position on diagnostic refers to the compiled file and not to template. Note that in this case position/span on diagnostic refers to the template file, e.g. if I add some newlines to template I get this
```
%Mix.Task.Compiler.Diagnostic{
     file: "/Users/lukaszsamson/bug_repro/build_errors_on_external_resource/lib/so mo/has_error.ex",
     severity: :error,
     message: "** (SyntaxError) invalid syntax found on lib/template.eex:11:5:\n    error: syntax error before: ','\n    │\n 11 │  , \n    │     ^\n    │\n    └─ lib/template.eex:11:5\n    lib/eex/compiler.ex:332: EEx.Compiler.generate_buffer/4\n    lib/so mo/has_error.ex:4: (module)\n",
     position: {11, 5},
     compiler_name: "Elixir",
     span: nil,
     details: {:error,
      %SyntaxError{
        file: "lib/template.eex",
        line: 11,
        column: 5,
        snippet: " , ",
        description: "syntax error before: ','"
      }},
     stacktrace: [
       {EEx.Compiler, :generate_buffer, 4,
        [file: ~c"lib/eex/compiler.ex", line: 332]},
       {:elixir_compiler_0, :__MODULE__, 1,
        [file: ~c"lib/so mo/has_error.ex", line: 2]},
       {:elixir_compiler, :dispatch, 4,
        [file: ~c"src/elixir_compiler.erl", line: 67]},
       {:elixir_compiler, :compile, 4,
        [file: ~c"src/elixir_compiler.erl", line: 52]},
       {:elixir_module, :eval_form, 7,
        [file: ~c"src/elixir_module.erl", line: 426]},
       {:elixir_module, :compile, 7,
        [file: ~c"src/elixir_module.erl", line: 128]},
       {:elixir_compiler, :maybe_fast_compile, 3,
        [file: ~c"src/elixir_compiler.erl", line: 38]}
     ]
   }
```

BTW I checked and phoenix heex templates share the same behaviour

**Comment by josevalim** [comment]
I think it makes sense to keep the `file`, `line`, and `span` all related to each other. Given the source is only used internally by the compiler (as far as I know), I will add a new field called `source` for the compiler usage.
