### ISSUE TITLE
installer.nsi does not write program details to registry

### ISSUE THREAD

**Issue by Trenly** [elixir-lang/elixir#13154]
### Elixir and Erlang/OTP versions

N/A

### Operating system

Windows 10/11

### Current behavior

No way to determine the package is installed on windows. The application does not appear in appwiz.cpl

### Expected behavior

The nullsoft installer should write the appropriate `DisplayName`, `DisplayVersion`, and `Publisher` keys to the Uninstall section of the registry. 

Example from other programs -

```
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APNAME}" "DisplayName" "${APNAME} ${APVER}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APNAME}" "DisplayVersion" "${APVER}"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APNAME}" "UninstallString" '"$INSTDIR\uninstall.exe"'
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APNAME}" "NoModify" 1
  WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APNAME}" "NoRepair" 1
```

**Comment by wojtekmach** [comment]
Thank you for the report and extra information. I'll look into it soon.
