### ISSUE TITLE
Unexpected warning on function used in `@compile` attribute

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#13167]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.16.0-rc.0 (6475917) (compiled with Erlang/OTP 26)

### Operating system

macOS

### Current behavior

There is a test in elixir source that asserts no unused function warning is generated when it's used in `@compile` attribute. While the test passes, this is not working as expected in an actual project.
Repro:
An empty project with this in `lib/sample.ex`
```
defmodule Sample do
  @compile {:inline, foo: 1}

  defp foo(_), do: :ok
end
```

`mix compile` result
```
    warning: function foo/1 is unused
    │
 4  │   defp foo(_), do: :ok
    │        ~
    │
    └─ lib/a.ex:4:8: Sample (module)
```

### Expected behavior

No warning or documentation update if private functions cannot be inlined

**Comment by josevalim** [comment]
Private functions can be inlined. The warning is also correct that the function is not used. If nobody calls it, it is not inlined anywhere. I am not sure which behaviour you are expecting here. :)

**Comment by josevalim** [comment]
> There is a test in elixir source that asserts no unused function warning is generated when it's used in @compile attribute. While the test passes, this is not working as expected in an actual project.

Which test are you referring to?

**Comment by lukaszsamson** [comment]
I meant this one https://github.com/elixir-lang/elixir/blob/fcacbfa40143b9877e0f79311e41e6505f81800e/lib/elixir/test/elixir/kernel/warning_test.exs#L1242C8-L1242C8 but I must have misread it. I thought it checks if no warning is generated at all. Sorry for the noise

**Comment by josevalim** [comment]
No problem! Thank you for sanity checking all warnings!
