### ISSUE TITLE
Attribute warnings are not emitted if tracer reads attributes in `on_module` event

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#13168]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.16.0-rc.0 (6475917) (compiled with Erlang/OTP 26)

### Operating system

macOS

### Current behavior

Repro:
1. create an empty mix project and put this code in `lib/sample.ex`
```
defmodule Sample do
  @doc "Something"
end
```
in iex setup a tracer and run compilation
```
defmodule Tracer do
  def trace({:on_module, _, _}, %Macro.Env{} = env) do
    for name <- Module.attributes_in(env.module) do
      IO.puts(inspect({name, Module.get_attribute(env.module, name)}))
    end
    :ok
  end

  def trace(_trace, _env) do
    :ok
  end
end

Code.compiler_options(%{Code.compiler_options() | tracers: [Tracer]})
Mix.start()
Code.compile_file("mix.exs")
Mix.Task.run("compile", ["--return-errors"])
```

Result:
```
{:ok, []}
```

### Expected behavior

Tracer presence should not modify the outcome of compilation. Diagnostic should be returned as it is without it.
```
%Mix.Task.Compiler.Diagnostic{
     file: "lib/sample.ex",
     severity: :warning,
     message: "module attribute @doc was set but no definition follows it",
     position: 2,
     compiler_name: "Elixir",
     span: nil,
     details: nil,
     stacktrace: [{Sample, :__MODULE__, 0, [file: "lib/sample.ex", line: 2]}]
   }
```

**Comment by josevalim** [comment]
Yes, if you read the attribute, it will no longer marked as unused. We can add an API to make this possible, such as Module.peek_attribute, but given this feature is not used by ElixirLS right now, we will skip it.
