### ISSUE TITLE
Elixir silently removes exclamation marks and reports no such file (Windows 10)

### ISSUE THREAD

**Issue by robss2020** [elixir-lang/elixir#13165]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Operating system

Windows 10

### Current behavior

Exclamation marks are silently removed from filenames, although they are allowed characters in Windows, and an error is reported.

To reproduce: save IO.puts("Hello, world!") as "hello world!.exs" and execute it with:
elixir "hello world!.exs"
It will fail with "no file named hello world.exs" (silently removing the exclamation mark). Also works without quotation marks as a single word (helloworld!.exs).

C:\test>elixir "hello world!.exs"
No file named hello world.exs

![image](https://github.com/elixir-lang/elixir/assets/70531052/fc18d6ee-d003-4506-b228-d8275e5898c0)

![image](https://github.com/elixir-lang/elixir/assets/70531052/24db2433-5c1a-4ecf-8fec-ee3d670cbe70)

### Expected behavior

If it is legal in the operating system it should be accepted as an input file, or at least the error message should say "! is not allowed in filename" if it can't be run for some reason.

**Comment by josevalim** [comment]
Thank you. I could easily reproduce the issue but it does not seem trivial to fix. I think we should rewrite our script to PowerShell, it should be both more maintainable and we could also test them on Unix as of PowerShell 7.

You may be able to run it as `elixir "helloworld^!.exs"` meanwhile.

**Comment by josevalim** [comment]
There is a failing test here: #13166
