### ISSUE TITLE
elixir and elixirx breaks cmd.com up arrow on Windows

### ISSUE THREAD

**Issue by robss2020** [elixir-lang/elixir#13163]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Operating system

Windows 10

### Current behavior

after I run elixir or elixirc from cmd.com in Windows the up arrow no longer goes to the last command but pastes ^[[A instead.  Something about elixir or elixirc breaks cmd.

Instead the normal behavior should continue, up arrow should go to the last command.

### Expected behavior

Up arrow should continue to show last command.

**Comment by simonmcconnell** [comment]
That's on OTP issue that is due to be fixed in 26.2.

**Comment by robss2020** [comment]
Great, glad to hear it!

**Comment by josevalim** [comment]
Closing it as it has been addressed upstream!
