### ISSUE TITLE
Need ability to add custom CA cert to `mix deps.get` and similar when running behind corporate firewall (Elixir 1.15+)

### ISSUE THREAD

**Issue by japhib** [elixir-lang/elixir#13169]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.15.6 (compiled with Erlang/OTP 25)

### Operating system

macOS Ventura 13.6.1

### Current behavior

When running `mix deps.get`, I get the following error:

```
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {~c"builds.hex.pm", 443}}, {:inet, [:inet], {:tls_alert, {:unknown_ca, ~c"TLS client: In state wait_cert_cr at ssl_handshake.erl:2111 generated CLIENT ALERT: Fatal - Unknown CA\n"}}}]}

Could not install Hex because Mix could not download metadata at https://builds.hex.pm/installs/hex-1.x.csv.
```

If I add the following line to the beginning of `Mix.Tasks.Deps.Get`, it works fine without an error:
```elixir
:public_key.cacerts_load("path/to/firewall_cert.crt")
```

Note that this only happens with Elixir 1.15 and newer. This happens for everyone at my company because we work behind a sort of corporate firewall. The path `"path/to/firewall_cert.crt"` above would be the path to the firewall software's provided CA cert.

It would be awesome if we could have an extra environment variable or configuration somewhere where we could specify a path to an "extra" CA cert. Mix would then just need to run `:public_key.cacerts_load()` with the provided path, before attempting to reach out to Hex.

Another fix would be to provide a command line argument (maybe one exists already?) to intentionally [use the `verify_none` option](https://github.com/elixir-lang/elixir/blob/v1.15.6/lib/mix/lib/mix/utils.ex#L683) that is used on error.

### Expected behavior

I would expect `mix deps.get` to be able to be configured to work, even if it requires a bit of extra configuration when running behind a corporate firewall.

**Comment by wojtekmach** [comment]
Does putting `:public_key.cacerts_load("path/to/firewall_cert.crt")` at the beginning of _your_ `mix.exs` work? I think it should!

**Comment by japhib** [comment]
Yes, that does work! Thank you for the suggestion.

Worth noting that `curl https://builds.hex.pm/installs/hex-1.x.csv` works fine from behind our firewall. It seems like some combination of our firewall software not injecting its CA cert in all the right places, and erlang's `:public_key.cacerts_get()` not looking in the places where the CA cert is getting put. If Erlang looked for certs in the same places as `curl`, that seems like it would fix the problem. Which seems like an issue with Erlang more than Elixir, but I'm not really sure which path Erlang should be looking that it doesn't.

**Comment by wojtekmach** [comment]
`iex> open :public_key.cacerts_get` should open source code as long as your OTP has source files. AFAIR there is a separate module that loads certs and for macOS there it opens port to `security` CLI to grab certs. I assume your custom cert is installed in the system trust store. Perhaps OTP is grabbing certs differently than curl, for example it reads from login store instead of system store or vice versa? It’s a long shot but I thought I’d mention this anyway. You can try asking on elixir and/or erlang forum.

**Comment by josevalim** [comment]
You can set `HEX_CACERTS_PATH` to point to additional certs as well. :)

**Comment by James-E-A** [comment]
> You can set `HEX_CACERTS_PATH` to point to additional certs as well. :)

Other commands, such as [`mix local.rebar`](https://hexdocs.pm/mix/main/Mix.Tasks.Local.Rebar.html), completely ignore that flag, and they even ignore the last-resort `HEX_UNSAFE_HTTPS=1`. Should that be a separate issue, or would it be considered part of this one?

-----

> \*\* (Mix) httpc request failed with: `{:failed_connect, [{:to_address, {~c"builds.hex.pm", 443}}, {:inet, [:inet], {:tls_alert, {:unknown_ca, ~c"TLS client: In state wait_cert_cr at ssl_handshake.erl:2183 generated CLIENT ALERT: Fatal - Unknown CA\n"}}}]}`
>
> Could not install Rebar because Mix could not download metadata at https://builds.hex.pm/installs/rebar.csv.
