### ISSUE TITLE
Should built in `mix` tasks should use `strict`, not `switches` for `OptionParser` parsing

### ISSUE THREAD

**Issue by halostatue** [elixir-lang/elixir#13175]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Operating system

macOS

### Current behavior

This is *mostly* a problem-in-chair, but one that I think that Elixir's mix tasks could help with. If this wouldn't apply to all provided mix tasks, perhaps it could apply to a few key ones.

In one of my GHA workflows, I had:

```yaml
- run: |
    mix deps.clean --unused -unlock || true
    git diff --exit-code
```

This helps us find dependencies in our `mix.lock` that we should have cleaned up but hadn't. We suppress the return code of `mix deps.clean` because we want to show the diff (although we could *probably* change it to `mix deps.clean … || git diff --exit code`; I need to test).

It never worked, and it probably isn't a surprise as to why, but it was quite annoying — about three months after I added this — to realize that I had forgotten a dash (`-unlock` vs `--unlock`) and `mix deps.clean` didn't warn me of the incorrect flag, even though (as far as I know), it is not legal to start a dependency name with `-`.

### Expected behavior

I should get a warning about unknown flags. There are two problems here (one appears that it might be an OptionParser bug):

1. The erroneous `-unlock` is not warned against.
2. The erroneous `-unlock` is swallowed entirely by `OptionParser.parse/2` with `switches` and is broken apart with `strict`.

For the latter:

```elixir
switches = [unlock: :boolean, all: :boolean, only: :string, unused: :boolean, build: :boolean]
args = ["--unused", "-unlock"]

OptionParser.parse(args, strict: switches)
# => {[unused: true], [], [{"-u", nil}, {"-n", nil}, {"-l", nil}, {"-o", nil}, {"-c", nil}, {"-k", nil}]}

OptionParser.parse(args, switches: switches)
# => {[unused: true], [], []}

OptionParser.parse(args, switches: switches, allow_nonexistent_atoms: true)
# => {[unused: true], [], []}
```

Using `strict` would work with reporting about the unknown flags, but what is strange is that I would expect that `allow_nonexistent_atoms` would put `[u: nil, n: nil, l: nil, o: nil, c: nil, k: nil]` in the `switches` flags position, or that either would pass `-unlock` through to the `args` position so that an error could be reported about the invalid dependency being cleaned (or, if `--unused` does not allow specifying additional dependencies, warning about that).

**Comment by josevalim** [comment]
Yes, we converted many tasks to use the strict version in the past, but apparently not all. However, note we cannot convert all of them, because many tasks are also used transparently as a building block for other ones. So for example, we can't convert "compile". I am pushing a fix for this one.

**Comment by halostatue** [comment]
I do find it weird that in non-strict mode and non-allow mode, the `-unlock` string isn’t just passed through to the `args` result. Should we open something for that directly?
