### ISSUE TITLE
IO.warn diagnostic with not filled metadata

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#13179]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.16.0-rc.1 (81a12b7) (compiled with Erlang/OTP 26)

### Operating system

macOS

### Current behavior

Repro:
1. Create an empty mix project
2. Add `IO.warn("foo")` in `mix.exs`
3. in iex
```
Mix.start()
Code.with_diagnostics(fn -> Code.compile_file("mix.exs") end)
```

```
   %{
     message: "foo",
     position: 0,
     file: nil,
     stacktrace: [
       {:elixir_compiler_0, :__FILE__, 1, [file: ~c"mix.exs", line: 57]},
       {:elixir_compiler, :dispatch, 4,
        [file: ~c"src/elixir_compiler.erl", line: 67]},
       {:elixir_compiler, :compile, 4,
        [file: ~c"src/elixir_compiler.erl", line: 52]},
       {:elixir_compiler, :maybe_fast_compile, 3,
        [file: ~c"src/elixir_compiler.erl", line: 39]},
       {:elixir_lexical, :run, 3, [file: ~c"src/elixir_lexical.erl", line: 15]},
       {:elixir_compiler, :quoted, 3,
        [file: ~c"src/elixir_compiler.erl", line: 17]}
     ],
     span: nil,
     severity: :warning
   }
```

```
Mix.start()
Kernel.ParallelCompiler.compile(["mix.exs"], return_diagnostics: true)
```

```
compile_warnings: [
     %{
       message: "foo",
       position: 0,
       file: nil,
       stacktrace: [
         {:elixir_compiler_1, :__MODULE__, 1, [file: ~c"mix.exs", line: 57]},
         {:elixir_compiler, :dispatch, 4,
          [file: ~c"src/elixir_compiler.erl", line: 67]},
         {:elixir_compiler, :compile, 4,
          [file: ~c"src/elixir_compiler.erl", line: 52]},
         {:elixir_module, :eval_form, 7,
          [file: ~c"src/elixir_module.erl", line: 426]},
         {:elixir_module, :compile, 7,
          [file: ~c"src/elixir_module.erl", line: 128]},
         {:elixir_compiler_0, :__FILE__, 1, [file: ~c"mix.exs", line: 1]}
       ],
       span: nil,
       severity: :warning
     }
     ]
```

Similarly, if I put `IO.warn` in `lib/sample.ex` and do
```
Mix.start()
Code.compile_file("mix.exs")
Mix.Task.run("compile", ["--return-errors", "--force"])
```
the warning will be printed with file and position
```
warning: foo
  lib/sample.ex:2: (file)
  (elixir 1.16.0-rc.1) src/elixir_compiler.erl:67: :elixir_compiler.dispatch/4
  (elixir 1.16.0-rc.1) src/elixir_compiler.erl:52: :elixir_compiler.compile/4
  (elixir 1.16.0-rc.1) src/elixir_compiler.erl:39: :elixir_compiler.maybe_fast_compile/3
  (elixir 1.16.0-rc.1) src/elixir_lexical.erl:15: :elixir_lexical.run/3
  (elixir 1.16.0-rc.1) src/elixir_compiler.erl:17: :elixir_compiler.quoted/3
```

but returned diagnostic is not filled
```
%Mix.Task.Compiler.Diagnostic{
     file: nil,
     severity: :warning,
     message: "foo",
     position: 0,
     compiler_name: "Elixir",
     span: nil,
     details: nil,
     stacktrace: [
       {:elixir_compiler_0, :__FILE__, 1, [file: ~c"lib/sample.ex", line: 2]},
       {:elixir_compiler, :dispatch, 4,
        [file: ~c"src/elixir_compiler.erl", line: 67]},
       {:elixir_compiler, :compile, 4,
        [file: ~c"src/elixir_compiler.erl", line: 52]},
       {:elixir_compiler, :maybe_fast_compile, 3,
        [file: ~c"src/elixir_compiler.erl", line: 39]},
       {:elixir_lexical, :run, 3, [file: ~c"src/elixir_lexical.erl", line: 15]},
       {:elixir_compiler, :quoted, 3,
        [file: ~c"src/elixir_compiler.erl", line: 17]}
     ]
   }
```

### Expected behavior

position and file properties populated

**Comment by josevalim** [comment]
Yes, this is intentional, and you can look into the stacktrace in said cases. The issue is that, when a stacktrace is given, we can't guarantee it is precise, and showing the snippet could be misleading.

**Comment by sabiwara** [comment]
> Yes, this is intentional, and you can look into the stacktrace in said cases. The issue is that, when a stacktrace is given, we can't guarantee it is precise, and showing the snippet could be misleading.

Maybe we should document the [`Code.diagnostic`](https://hexdocs.pm/elixir/1.15.7/Code.html#t:diagnostic/1) type accordingly, or provide a function to fetch the file & position from a diagnostic?

**Comment by josevalim** [comment]
I think we should document IO.warn instead.

**Comment by josevalim** [comment]
But i think the point is that we don't want to conflate the file and position with the one in the stacktrace. maybe it is fine for IDEs, but not generally.

**Comment by lukaszsamson** [comment]
@josevalim I fail to see how https://github.com/elixir-lang/elixir/commit/2c1ca00d6b0d91b762af25b3391d3046fd104eb0 improves the situation. When emitting diagnostics I need to map the diagnostic to document URI (see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#publishDiagnosticsParams). There is no such thing as diagnostic with null URI. Even if I emit something fake as `file:///nofile` or `unknown:abcd` the editor will try to open that file and navigate to diagnostic range. If I substitute `mix.exs` then the diagnostic is invalid, misplaced and confusing.

**Comment by josevalim** [comment]
Please read my previous comment. This is not an issue, I have only improved the docs. Elixir's definition of a diagnostic does not have to match the language server one. It is up to you to convert our diagnostic to something that makes sense to LSP. What Elixir is saying is that: if there is a file+position, then the diagnostic is precise. If there is only a stacktrace, then you can decide if you want to infer the file+position from the stacktrace or not. It is up to you. Elixir chooses to not emit a snippet in such cases. You may choose to traverse the stacktrace (perhaps trying to match against one of the project modules/files) or not show the diagnostic in editor (because, once again, it is not precise).

**Comment by josevalim** [comment]
I have pushed more docs, this time to Code.diagnostic and Mix.Tasks.Compiler.Diagnostic.

**Comment by lukaszsamson** [comment]
Thanks for explaining that

> You may choose to traverse the stacktrace (perhaps trying to match against one of the project modules/files)

Thats what I need to do. Is there an API for that?

**Comment by josevalim** [comment]
No, but I think it is specific to your use case. But the stacktrace is a publically documented data structure, so you can traverse it as you prefer.
