### ISSUE TITLE
Pattern matches in function calls escape scope

### ISSUE THREAD

**Issue by Munksgaard** [elixir-lang/elixir#13170]
### Elixir and Erlang/OTP versions

```
$ elixir --version
Erlang/OTP 25 [erts-13.2.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.6 (compiled with Erlang/OTP 25)
```

### Operating system

Linux/NixOS

### Current behavior

Pattern matches that bind variables inside a function call or `if` statements escape the scope of the function call or `if`-expression. For instance, in the following piece of code, `x` is bound after the call to `if`:

```elixir
$ iex
Erlang/OTP 25 [erts-13.2.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.6) - press Ctrl+C to exit (type h() ENTER for help)
iex [22:27 :: 1] > if x = :foo, do: :bar
:bar
iex [22:27 :: 2] > x
:foo
```

It can also be seen in this example, (courtesy of @vhf on #elixir on libera.chat (I hope it's the same person)):

```elixir
$ iex
Erlang/OTP 25 [erts-13.2.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.6) - press Ctrl+C to exit (type h() ENTER for help)
iex [22:33 :: 1] > fun = fn _a -> nil end
#Function<42.3316493/1 in :erl_eval.expr/6>
iex [22:33 :: 2] > x = 1
1
iex [22:33 :: 3] > fun.(x = 2)
nil
iex [22:33 :: 4] > x
2
```

I am not sure what the intended behavior is here, but this was surprising to me, and it doesn't seem to be documented in [the relevant section of the documentation](https://hexdocs.pm/elixir/patterns-and-guards.html#guards).

### Expected behavior

I would not expect pattern matches inside function calls or `if` statements to escape the scope of said function call or `if` statement.

**Comment by viniciusmuller** [comment]
Hey @Munksgaard, I believe this is the intended behavior, nothing is escaping from a scope because in both examples you shared the assignment is at the top-level scope:

- A function call does not create a new scope
- The condition expression for the if is also evaluated in the same scope as it's defined, but its `do` block runs in a new scope

If you can try the following instead:

```ex
iex(2)> x = :foo
:foo
iex(3)> if :foo, do: x = :bar
:bar
iex(4)> x
:foo
```

I'm not sure where it would be the best update the documentation, but I believe this notion of 'what creates a scope and what not' is the key for clearing this out

**Comment by sabiwara** [comment]
I believe the first case is intentional for the same reason as https://github.com/elixir-lang/elixir/issues/13110#issuecomment-1812655104.

The second one is consistent with Erlang so I think it's probably fine too:

```erlang
Eshell V14.1 (press Ctrl+G to abort, type help(). for help)
1> hd(X = [1]).
1
2> X.
[1]
```

**Comment by josevalim** [comment]
Function calls do not introduce a new scope. As far as I know, this is consistent with most programming languages. New scopes are typically introduced by block constructs.

**Comment by Munksgaard** [comment]
Thank you all for your comments. 

I see now that this behavior is not as unwarranted as I thought. I guess I was surprised because the [Rust-equivalent of my first example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=580f26566a5b1949b96648ebe8716e7f) does _not_ bind outside the `if`:

```rust
fn main() {
    let foo = Some(42);

    if let Some(bar) = foo {
        println!("{}", bar);
    };
    
    println!("{}", bar);  // <- Compile-time error, since bar is not in scope
}
```

Similarly, the Standard ML equivalent of the second example looks like this, and also does not bind outside the function application:

```sml
let val f = fn _ => 42 
in f(let val x = 1 in 2 end)
end;

(* `x` is not in scope here *)
```

However, in both cases you could argue that the `let` introduces a new scope. I guess it's time for me to update my mental model of pattern match binding in Elixir/Erlang :slightly_smiling_face:

**Comment by josevalim** [comment]
I guess in Rust the brackets are used to introduce new blocks/scopes, so it makes sense it won't leak out of them. In Elixir we could use parentheses, but parens are used for grouping, and they do not introduce new blocks/scopes.

**Comment by Munksgaard** [comment]
> I guess in Rust the brackets are used to introduce new blocks/scopes, so it makes sense it won't leak out of them. In Elixir we could use parentheses, but parens are used for grouping, and they do not introduce new blocks/scopes.

Yes, brackets introduce a new scope in Rust, but notice that there are no brackets around the `if let` in the first example. Actually, a better example might be [the following](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e7ac3cc185d9f000fba960d1e13a081c):

```rust
fn main() {
    if let bar = 42i64 {
        println!("{}", bar);
    };
    
    println!("{}", bar);  // <- Compile-time error, since bar is not in scope
}
```

**Comment by josevalim** [comment]
Right, but `if let` in Rust introduces branching. You can do this:

```
   if let Some(i) = number {
        println!("Matched {:?}!", i);
    }
```

Which means `i` is only assigned in some cases. You can't introduce branching on the argument of `if` in Elixir. It is always executed, so those are apple to orange comparisons.

**Comment by Munksgaard** [comment]
Yes, I see that now. Thanks for taking the time to explain :-)

**Comment by lukaszsamson** [comment]
This behavior definitively deserves some documentation

**Comment by josevalim** [comment]
Yes, we should document better which constructs introduce a new scope, but I am not a big fan of introducing negative assertions in the docs, such as "function calls do not introduce a new scope".
