### ISSUE TITLE
Off by one error when translating erlang `badarg` to elixir `ArgumentError`

### ISSUE THREAD

**Issue by NobbZ** [elixir-lang/elixir#13189]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.15.7) - press Ctrl+C to exit (type h() ENTER for help)

### Operating system

Linux

### Current behavior

The translated argument "count" is off by one:

```
iex(1)> :erlang.phash("", 0)
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: out of range

    :erlang.phash("", 0)
    iex:1: (file)
```

The out of bounds argument is actually the second one.

### Expected behavior

The "bad argument" is reported correctly.

**Comment by NobbZ** [comment]
OTP tells you the index, while elixir gives a first, second, third, etc.

I currently do not have any other function at hands where I knew how to provoke a bad arg.

A reason to fix it in OTP would be only if we found an inconsistency in how they count.

As long as OTP always does a 0-based index, elixir has to adjust for that. Either by also reporting the zerobased index or by "plus 1" it.

**Comment by josevalim** [comment]
Fixed here: https://github.com/erlang/otp/pull/7960

**Comment by NobbZ** [comment]
So it was just an unfortunate error with the `phash*` functions? Thanks!
