### ISSUE TITLE
Decide if TokenMissingError and MismatchedDelimiterError should have end_line/column or begin_line/column

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#13187]
And whatever we choose should be passed down to the diagnostics and we need to document these fields.

The big question is: should the line/column point by default to where the delimiter starts or where it is missing/mismatched?

Perhaps this doesn't matter for IDEs. IDEs will receive both line+column PLUS the span, so they can always highlight the whole bit. If this is the case, then I would have line/column be the starting position and include end_line/end_column, so it is closer to the diagnostic.

/cc @lukaszsamson

**Comment by lukaszsamson** [comment]
LSP diagnostics are based on ranges and so far I assumed the following. I omit the mapping from UTF8 1-based to UTF16 0-based columns for simplicity
1. if position is 0 I map it to range {1, 1} - {1, 1}
2. If position is pos_integer line I find the first nonwhitespace char and {line, first_char}-{line, first_char}
3. If position is tuple {line, column} I return {line, column}-{line, column}
4. If position is range I return exactly that range

Besides the main diagnostic range, message and severity there are 3 things we can use to make them more helpful.
1. A collection of tags https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag. VSCode marks unused and deprecated warnings specially. So far I use regex for extracting that.
Notice gray font on unused and strikethrough on deprecated
<img width="223" alt="Screenshot 2023-12-14 at 12 21 30" src="https://github.com/elixir-lang/elixir/assets/1078186/01ace889-c060-455b-947e-8f3f20b4cc0f">
2. A collection of related info https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticRelatedInformation. This makes it possible to make the diagnostic in line 5, and point to line 1 starting the unclosed token and line 8 when document ends. You can click on the related info and it will navigate to relevant position in the editor. Here I extract it from `end_line`, `closing_delimiter` or via regex from hint in `description`
<img width="748" alt="Screenshot 2023-12-14 at 12 17 23" src="https://github.com/elixir-lang/elixir/assets/1078186/97d202c3-da99-4818-9208-bfaa9348b326">
3. Error code and URL link to description - no such thing in elixir right now

**Comment by josevalim** [comment]
Thanks. You will have the exception now, so hopefully you can extract all of that more reliably.

**Comment by viniciusmuller** [comment]
> BTW here the new diagnostics look rather ugly as the UI does not use fixed width font

@lukaszsamson apart from the font, the problem mainly seems to be the fact that this vscode thing is trimming all the trailing whitespace in the error lines, making it unaligned

I don't use vscode but I can try it later as well, but it would be cool if you tried how it looks like with a language such as rust, as it also have these trailing whitespaces in order to make padding for the line numbers (although ours are a bit more indented to the right)

**Comment by lukaszsamson** [comment]
@viniciusmuller that's a known issue with vscode. The same diagnostics are rendered properly in other places https://github.com/microsoft/vscode/issues/198981

**Comment by viniciusmuller** [comment]
Well, at least it looks very nice on the error hover pop-up
