### ISSUE TITLE
URI.Error parsing URI with # in the fragment

### ISSUE THREAD

**Issue by 1player** [elixir-lang/elixir#13191]
### Elixir and Erlang/OTP versions

Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Operating system

Linux

### Current behavior

```
iex(5)> URI.new!("https://app.gitter.im/#/room/#rbspy_rbspy:gitter.im")
** (URI.Error) cannot parse due to reason invalid_uri: ":"
    (elixir 1.15.7) lib/uri.ex:637: URI.new!/1
    iex:5: (file)
```

### Expected behavior

URI to be parsed correctly. Removing the second `#` character in the fragment (i.e. `https://app.gitter.im/#/room/rbspy_rbspy:gitter.im`) works, so perhaps URI.new! does not accept a second hash character. In any case, this is a valid URL, so it should be parsed.

**Comment by josevalim** [comment]
It is not a valid URL according to the RFC3986, which is implemented by the URI module:

```
fragment    = *( pchar / "/" / "?" )
pchar       = unreserved / pct-encoded / sub-delims / ":" / "@"
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
            / "*" / "+" / "," / ";" / "="
unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
```

**Comment by 1player** [comment]
@josevalim Fine. But shouldn't `URI.encode/1` deal with that, and percent-encode the second # character? The docs for that function say "Percent-escapes all characters that require escaping in string.", yet it is unable to handle with this URL which is actually seen and used in the wild.

**Comment by 1player** [comment]
Also, the RFC you reference also states, in contradiction to the BNF syntax you pasted: "A fragment identifier component is indicated by the presence of a number sign ("#") character and terminated by the end of the URI." which is exactly the interpretation any modern browser follows.

So `https://app.gitter.im/#/room/#rbspy_rbspy:gitter.im` in theory isn't valid, in practice it is and browsers are able to handle that just fine (just try to open it for yourself)

**Comment by josevalim** [comment]
Encode is typically used for escaping segments of a URL, exactly because different parts of a URL require different escaping rules.

> url |> URI.encode() |> URI.new!()

This variant only holds if you have a valid URL in the first place. Once again, escaping in a URL is context sensitive, so in order to escape/encode something properly, you need to give it a valid URL (which you don't have here).

If you give it an invalid URL, then there is ambiguity.  For example, take your URL:

    https://app.gitter.im/#/room/#rbspy_rbspy:gitter.im

You are expecting it to be:

    https://app.gitter.im/#/room/%23rbspy_rbspy:gitter.im

But it could as well be:

    https://app.gitter.im/%23/room/#rbspy_rbspy:gitter.im

It is impossible for us to know without a valid URL. You are asking for something to guess what is the meaning here and a strict parser can't do it for you.

**Comment by josevalim** [comment]
> Also, the RFC you reference also states, in contradiction to the BNF syntax you pasted

The BNF was lifted directly from the RFC too, so feel free to reach out asking for a clarification. 

You can also use URI.parse, which is a looser version of parsing and it will match the Python one, but it doesn't change the fact it does not follow the RFC grammar.

**Comment by 1player** [comment]
> > url |> URI.encode() |> URI.new!()
> 
> This variant only holds if you have a valid URL in the first place. Once again, escaping in a URL is context sensitive, so in order to escape/encode something properly, you need to give it a valid URL (which you don't have here).
> 

I get your point about ambiguity, but the point of URI.encode is to take a *binary*, not a valid URL, and encode it to a valid URL. 

And in any case, the interpretation is simple and clearly explained by the RFC: the first # character delimits the start of the fragment. So, if URI.new! should not accept that, I disagree that URI.encode should just spit out an invalid URL that could be encoded.

Which means that `https://app.gitter.im/#/room/%23rbspy_rbspy:gitter.im` is the only valid result for `URI.encode("https://app.gitter.im/#/room/#rbspy_rbspy:gitter.im")`

**Comment by josevalim** [comment]
> And in any case, the interpretation is simple and clearly explained by the RFC

We will have to disagree here. Between a textual representation and a BNF grammar, both provided by the RFC, the BNF grammar is the most precise one, and I would rather adhere to that.

However, if you think your interpretation is correct, you can split on "#", and then join the first pair with "#" and the rest with "%23". Or use URI.parse which is loose.
