### ISSUE TITLE
OptionParser does not work as expected for strict booleans

### ISSUE THREAD

**Issue by spinettaro** [elixir-lang/elixir#13197]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.6 (compiled with Erlang/OTP 26)

### Operating system

Windows

### Current behavior

```
iex(2)> OptionParser.parse(["--source", "false"], strict: [source: :boolean])
{[source: true], ["false"], []}
```

### Expected behavior

```
iex(2)> OptionParser.parse(["--source", "false"], strict: [source: :boolean])
{[source: false], [], []}
```

I expect it to work like string
```
iex(1)>OptionParser.parse(["--source", "lib"], strict: [source: :string])
{[source: "lib"], [], []}
```

**Comment by wojtekmach** [comment]
boolean are in the form `--foo` and `--no-foo`, not `--foo=x`:

```elixir
iex(1)> OptionParser.parse(["--no-source"], strict: [source: :boolean])
{[source: false], [], []}
```

**Comment by spinettaro** [comment]
ok thanks @wojtekmach, there was an ongoing discussion on `openapi.spec` repo https://github.com/open-api-spex/open_api_spex/pull/579 . Just as reference

**Comment by spinettaro** [comment]
however I'm going to create a PR to make it more explicit in OptionParser documentation. Thanks again for the quick reply @wojtekmach
