### ISSUE TITLE
Unexpected formatter behaviour

### ISSUE THREAD

**Issue by MrYawe** [elixir-lang/elixir#13198]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Operating system

macOS 14.1.1 (23B81)

### Current behavior

With the following code in a module:
```elixir
def(say_hello) do
    "Hello!"
end
```

Run:
```
mix format
```

No changes.

### Expected behavior

I'm not sure it's a bug but I'm surprised that the following code is not formatted to:

```elixir
def say_hello do
    "Hello!"
end
```

**Comment by josevalim** [comment]
Elixir formatter does not remove parenthesis once the developer adds them, respecting the developers choice.
