### ISSUE TITLE
`macro-anti-patterns.md` should be `meta-anti-patterns.md`?

### ISSUE THREAD

**Issue by kianmeng** [elixir-lang/elixir#13202]
### Elixir and Erlang/OTP versions

Elixir 1.16 and Erlang/OTP 26.2.1

### Operating system

Ubuntu 23.10 Mantic

### Current behavior

The 
The release blog post https://elixir-lang.org/blog/2023/12/22/elixir-v1-16-0-released/ pointed to a missing link, https://hexdocs.pm/elixir/meta-anti-patterns.html

### Expected behavior

`lib/elixir/pages/anti-patterns/macro-anti-patterns.md` should be `lib/elixir/pages/anti-patterns/meta-anti-patterns.md` to fix 404 link of the above blog post and also to match the page title to filename naming convention?

No PR as it will discard existing Git history.

**Comment by josevalim** [comment]
Fixed in the article!
