### ISSUE TITLE
Broken 'enumerables and streams' link after migrating 'getting started' to hexdocs

### ISSUE THREAD

**Issue by angelikatyborska** [elixir-lang/elixir#13209]
### Elixir and Erlang/OTP versions

Elixir 1.16.0

### Operating system

does not apply

### Current behavior

Thank you for adding all those redirects from the old Getting Started pages to HexDocs 🙏.  I just finished migrating a whole bunch of links in my repo, and noticed that one of the redirects is incorrect.

The URL
`https://elixir-lang.org/getting-started/enumerables-and-streams.html`
redirects to
`https://hexdocs.pm/elixir/1.16/enumerables-and-streams.html`

### Expected behavior

It should redirect to:
`https://hexdocs.pm/elixir/1.16/enumerable-and-streams.html`

**Comment by josevalim** [comment]
Fixed in elixir-lang.github.com main, thank you!

**Comment by josevalim** [comment]
(it should be live in one or two minutes)
