### ISSUE TITLE
`ctrl-h` in iex deletes entire word as of Elixir 1.16

### ISSUE THREAD

**Issue by sodapopcan** [elixir-lang/elixir#13214]
### Elixir and Erlang/OTP versions

>Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.16.0 (compiled with Erlang/OTP 24)

### Operating system

macos 13.5 (22G74)

### Current behavior

I'm not sure if I should be reporting this here or on Erlang so apologies if this is the wrong palce.

As of Elixir 1.16, pressing `ctrl-h` now works as "delete back one word" mimicking the behaviour of `ctrl-w`.

### Expected behavior

`ctrl-h` should just be sending `backspace`.

**Comment by josevalim** [comment]
Please report this to Erlang. :) Make sure you are on latest though (26.2)! Thank you!

**Comment by sodapopcan** [comment]
Ugh, this is embarrassing.  Ya, I just didn't realize I hadn't also upgraded Erlang on this project.  Apologies and thanks.
