### ISSUE TITLE
Output of `Kernel.ParallelCompiler.compile/2` unexpectedly different between Elixir 1.15.7 and 1.16.0 when used from an escript

### ISSUE THREAD

**Issue by angelikatyborska** [elixir-lang/elixir#13217]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

macOS 14.1 (but I also reproduced the bug in a debian-bookworm Docker container)

### Current behavior

I read the [release notes](https://github.com/elixir-lang/elixir/releases/tag/v1.16.0) twice and didn't find anything that would explain this change in behavior, hence I'm opening an issue.

When run from an escript, `Kernel.ParallelCompiler.compile/2` in Elixir 1.15.7 reports both compile warnings and runtime warnings, but in Elixir 1.16.0 it only reports compile warnings. This difference only happens in an escript and I don't know why. When run in iex, in both Elixir versions both types of warnings are reported.

I created a reproduction repository for this, see its README for more details: https://github.com/angelikatyborska/elixir_1_16_parallel_compiler_compile

### Expected behavior

I would expect the output of `Kernel.ParallelCompiler.compile/2` to be identical when run from an escript and from iex. Ideally that would mean that it always reports both runtime and compile warnings.

If the change of behavior between Elixir 1.15.7 and 1.16.0 is intentional, then I would expect to find a mention of it in the release notes.

**Comment by josevalim** [comment]
Thank you for the report, @angelikatyborska!

I have a suspicion this is related to all Elixir source files are stored inside the `.escript`. For some reason they cannot be found and the warnings are not emitted.

**Comment by josevalim** [comment]
Found it. We are stripping the beams, and that includes metadata the compiler uses for checking deprecations. Adding this to the script configuration should do it:

    escript: [main_module: Elixir116, strip_beams: [keep: ["ExCk"]]]

I will add a note to the CHANGELOG. :)

**Comment by josevalim** [comment]
If you want to keep all other information, such as debug info and docs, then you can set `strip_beams: false`. I assume binary size is not a concern for you, so that should be a good call too.

**Comment by josevalim** [comment]
CHANGELOG entry added, sorry for the hiccup :)

**Comment by angelikatyborska** [comment]
Thank you for the fast and helpful answer 🙌  this is exactly what I needed.
