### ISSUE TITLE
Mix help printing escaped unicode bullet points

### ISSUE THREAD

**Issue by harrisi** [elixir-lang/elixir#13220]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.16.0 (compiled with Erlang/OTP 26)
```

### Operating system

macOS 14.2.1

### Current behavior

When using `mix help`, if the help text includes bullet points and colors are enabled, the bullet points are rendered as escaped unicode. Colors seem to work fine, as you can see in the screenshot.

<details>
  <summary>Screenshot</summary>
  <img width="682" alt="Screenshot of terminal with colors and escaped unicode" src="https://github.com/elixir-lang/elixir/assets/14868079/60f42dfa-8b94-4f15-8fad-8205742259ca">
</details>

Disabling colors with the following config (~/.mix/config.exs) disables colors and renders the ASCII `*` as expected.

```elixir
import Config

config :mix,
  colors: [enabled: false]
```

```
> mix help deps
...
It supports the following options:

  \x{2022} --all - lists all dependencies, regardless of specified environment
...
```

### Expected behavior

```
> mix help deps
...
It supports the following options:

  • --all - lists all dependencies, regardless of specified environment
...
```

**Comment by josevalim** [comment]
It worked here so I assume your font does not support said Unicode characters. Can you please try other fonts? I am using Monaco.

**Comment by harrisi** [comment]
Same behavior with Monaco (I was using Menlo). I can print the character just fine in `iex`, as well:

```ex
❯ iex
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Interactive Elixir (1.16.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> "\u2022"
"•"
iex(2)> 
```

**Comment by josevalim** [comment]
Interesting. Which terminal are you using then?

**Comment by harrisi** [comment]
I tried this in macOS's default terminal as well as (entirely up-to-date) iTerm2. I'm using zsh. Some other possibly relevant things:

$LANG=C # I also tried LANG=en_US.UTF-8, no difference
$TERM=xterm-256color

Terminal encoding is set to UTF-8 in settings, as well just to make sure.

I'm confused on why the output would be using the `\x{nn..}` syntax as well, but probably not relevant.

**Comment by josevalim** [comment]
Good call on the env vars. I could not reproduce by changing them here but what does `locale` return to you?

**Comment by harrisi** [comment]
```sh
❯ locale
LANG="C"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

I tried messing with them in various ways, no change.

**Comment by josevalim** [comment]
You can try adding this to your bash profile:

```
if [[ -z "$LC_ALL" ]]; then
  export LC_ALL='en_US.UTF-8'
fi
```

You can also check what is under "Preferences > Profile > Advanced > International".

**Comment by harrisi** [comment]
Huh. I swore I tried that, but looking back in `history`, I didn't. I thought `LANG=en_US.UTF-8 mix help deps` would do it, but I misread the man page it seems.

The actual variable that fixes it is `LC_CTYPE`. Setting that to `en_US.UTF-8` works. Also, your solution to setting `LC_ALL` works.

I'd be curious to see if you can recreate it with something like this: `LC_ALL= LC_CTYPE=C mix help deps`. Not sure if your other locale settings will affect that.

Either way, thanks. I'm not sure if this is an issue or not, so feel free to close it if it's just PEBKAC. :)

**Comment by josevalim** [comment]
Jackpot, `LC_ALL= LC_CTYPE=C mix help deps` reproduces it for me too. :)

I don't think this is an Elixir issue per se. I am glad we have it documented though in case anyone else runs into it. Thanks!
