### ISSUE TITLE
Individual testcases are always passed on Windows

### ISSUE THREAD

**Issue by ndtoan96** [elixir-lang/elixir#13225]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)
```

### Operating system

Windows

### Current behavior

`mix test folder\file.exs:<line>` always returns exit code 0, even if the test should fail.

`mix test folder/file.exs:<line>` behaves correctly. (notice the separator `\` vs `/`)

![image](https://github.com/elixir-lang/elixir/assets/33489972/00b7aa35-700b-4291-b44b-8ce74e1fa078)

### Expected behavior

On Windows, `\` separator should not cause problem.

**Comment by jimharter** [comment]
I am running into the same issue.  I don't think the issue is that they always pass.  Instead, it is that all tests are excluded.  Also, I verified that it works properly on 1.15.7.
