### ISSUE TITLE
List.delete seems to not work on charlists ~c""

### ISSUE THREAD

**Issue by z7ealth** [elixir-lang/elixir#13221]
### Elixir and Erlang/OTP versions

➜ elixir -v
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:32:12] [ds:32:12:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Operating system

OpenSuse Tumbleweed (Linux)

![imagen](https://github.com/elixir-lang/elixir/assets/37885943/6817d2bd-24e9-4a7b-babc-df53349940be)

### Current behavior

![imagen](https://github.com/elixir-lang/elixir/assets/37885943/9f3bc882-8003-4191-ad14-d75802553db1)

### Expected behavior

list = ~c"Hello"

List.delete(list, ~c"H")
"ello"

**Comment by kipcole9** [comment]
In your example, the equivalent would be:
```elixir
iex> List.delete(~c"Hello", [?H])
```
And since there is no entry `[?H]` in the list, the list is returned unmodified.

If you are trying to delete a single character from the chartist then:
```elixir
iex> List.delete(~c"Hello", ?H)
```
would be appropriate.

**Comment by z7ealth** [comment]
Oh i see, sorry im still learning...

Happy new year!

**Comment by kipcole9** [comment]
@z7ealth all good. I'd recommend participating in the [Elixir Forum](https://elixirforum.com) - it's a great community and a good place to ask and learn.
