### ISSUE TITLE
Version-specific canonical links resulting in old documentation showing up in Google

### ISSUE THREAD

**Issue by bradhanks** [elixir-lang/elixir#13223]
### Elixir and Erlang/OTP versions

rlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

MacOS

### Current behavior

When I'm searching for Elixir documentation, I consistently get old versions showing up. 

<img width="723" alt="image" src="https://github.com/elixir-lang/elixir/assets/3719024/235d137e-b218-43a2-9fb4-cb607cf34c22">
<img width="864" alt="image" src="https://github.com/elixir-lang/elixir/assets/3719024/50609477-0a93-435d-b8ab-9f419cf54e79">

Currently canonical links on Elixir documentation pages are:

<link rel="canonical" href="https://hexdocs.pm/elixir/{version}/{page-name}.html" />

The original purpose of the canonical link was to let Google know which page was the authoritative source among many that were very similar. With each documentation version holding itself up as the canonical, Google is making guesses on which version is the most helpful. That's currently being driven by links to old versions of the documentation. 

### Expected behavior

I've gone through some of the more popular libraries and I can't find any that have the same problem. None of them use canonical links that I can see.

I'm curious if the canonical is serving an important purpose. 

If it is something worth changing we could either delete the "--canonical" option from the Makefile 

or change it to be consistent across all versions.

--canonical "https://hexdocs.pm/$(2)/$(CANONICAL)" -> --canonical "https://hexdocs.pm/$(2)/"

I guess that would mean going through each version and editing the Makefile? I'm willing to do it if makes sense to do.

**Comment by josevalim** [comment]
We have stopped setting each branch as canonical as of v1.16.0 (i.e. the CANONICAL var is not set). So this was recently done but it will take a while to propagate.
