### ISSUE TITLE
Incorrect typespec for `++/2`

### ISSUE THREAD

**Issue by jdav-dev** [elixir-lang/elixir#13238]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

Pop!_OS 22.04 LTS

### Current behavior

The [typespec](https://hexdocs.pm/elixir/Kernel.html#++/2) for `++/2` is `@spec list() ++ term() :: maybe_improper_list()`.  The typespec can be incorrect if the left argument is an empty list:

```elixir
iex(1)> [0] ++ 1
[0 | 1]
iex(2)> [] ++ 1
1
```

### Expected behavior

I was surprised by this behavior while working with Ecto associations.  `++/2` returned a `Ecto.Association.NotLoaded` struct from the right side argument when I had expected it to fail.  Here are some possible solutions I came up with:

* The docs and typespec are updated to reflect this behavior.

* Or, an error is raised if the left argument is an empty list and the right argument is not a list (this is what I naively expected, but could be inconsistent):

```elixir
iex(1)> [0] ++ 1
[0 | 1]
iex(2)> [] ++ 1
** (ArgumentError) argument error
    :erlang.++([], 1)
    iex:2: (file)
```

* Or, the right argument is wrapped in a list (this is not what I expected, but might be more consistent):

```elixir
iex(1)> [0] ++ 1
[0 | 1]
iex(2)> [] ++ 1
[1]
```

I realize the second two would likely be Erlang changes.  I couldn't find anywhere in Erlang's docs as to whether this behavior was expected, so I started with an Elixir issue.

Thanks!

**Comment by josevalim** [comment]
`++` simply delegates to the same Erlang operation so we need to update the specs. Perhaps this?

    @spec [] ++ a :: a when a: term()
    @spec nonempty_list() ++ term() :: maybe_improper_list()

Can you please send a PR?
