### ISSUE TITLE
Hammox/Mox issue due to callback vs function in same module not matching

### ISSUE THREAD

**Issue by epinault** [elixir-lang/elixir#13242]
### Elixir and Erlang/OTP versions

Elixir 1.15

### Operating system

all

### Current behavior

If I try to Mock an Application with

```
Hammox.defmock(MyModule.ApplicationMock, for: Application)
```

and then do an expect

```
      expect(MyModule.ApplicationMock, :start, fn name, process_type ->
        assert name == :app_name
        assert process_type == :permanent
      end)
```

I get this error 

```
     ** (Hammox.TypeMatchError)
     1st argument value :app_name does not match 1st parameter's type Application.start_type().
       Value :app_name does not match type :normal | {:takeover, node()} | {:failover, node()}.
     code: capture_io(fn ->
     stacktrace:
       (hammox 0.7.0) lib/hammox.ex:440: Hammox.check_call/3
       (hammox 0.7.0) lib/hammox.ex:408: Hammox.protected_code/3

   ```

when I am looking at https://hexdocs.pm/elixir/1.15.7/Application.html#c:start/2 and https://hexdocs.pm/elixir/1.15.7/Application.html#start/2 they don t seemed aligned in term of typespec but it s really confusing Hammox 

this maybe an issue with Hammox but I found it strange that a callback of function in the same module have different typespec

### Expected behavior

that the typespec is the one from the start/2 function and not the callback? I could be wrong

**Comment by sabiwara** [comment]
> that the typespec is the one from the start/2 function and not the callback? I could be wrong

I think there is a confusion between the `start/2` function from the `Application` module itself and the `c:start/2` callback, which modules implementing the `Application` **behaviour** (e.g. `MyApp`) have to implement.

`Application.start/1` takes a module implementing the behaviour as first argument.

**Comment by josevalim** [comment]
@sabiwara is correct. :)

**Comment by epinault** [comment]
make sense. Thanks. Just seems like I wish I could mock the other one but I ll figure out a way by wrapping it
