### ISSUE TITLE
'error: misplaced operator |/2' compile-time messaging inaccuracy 

### ISSUE THREAD

**Issue by bradhanks** [elixir-lang/elixir#13245]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

MacOS

### Current behavior

I may be mistaken, but I believe that the `error: misplaced operator |/2` error message is incorrect. 

I understand [Elixir linked lists documentation](https://github.com/elixir-lang/elixir/blob/v1.16.0/lib/elixir/pages/getting-started/lists-and-tuples.md#linked-lists) and the [Erlang cons AST documentation](https://www.erlang.org/doc/man/erl_syntax#cons-2) to mean that the head is a single element of any type, i.e., the first element of a cons cell.

Steps to reproduce:

I  added this code to a module in an application that was compiling:
```
  x = [1 | 2 | [3, []]]
  
  map = %{
    :x => x,
    :a => 2

  }
```
gives me this error:
```

      error: misplaced operator |/2

      The | operator is typically used between brackets as the cons operator:

          [head | tail]

      where head is a sequence of elements separated by commas and the tail
      is the remaining of a list.

      It is also used to update maps and structs, via the %{map | key: value} notation,
      and in typespecs, such as @type and @spec, to express the union of two types
      │
 17 │   x = [1 | 2 | [3, []]]
      │                 ^
      │
     └─ lib/demo_web/router.ex:17:14: DemoWeb.Router (module)


== Compilation error in file lib/demo_web/router.ex ==
** (CompileError) lib/demo_web/router.ex: cannot compile module DemoWeb.Router (errors have been logged)

```
 In the context of the message,

> a sequence of elements separated by commas 

defines a "partial prefix" (not sure the technical term).

I also think that the carat is misplaced. I'm not going to be shocked if I'm wrong, 
but since it's right-associative,

`[  1   |  (2 | [3, [ ]]) ]` ,

the | operator fails because the right-hand side argument is an integer not a list.

### Expected behavior

If edits are required, here's a jumping off point. 

```
    error: misplaced operator |/2

      Between brackets the | operator builds a list as the cons operator:

          [head | tail]

      where head is any element and the tail is a list.

      The cons operator builds a proper list when the tail is a proper list.
      Maps and structs update values via the %{map | key: value} notation.
      @type and @spec use the | operator to express the union of two types.
      │
 17 │   x = [1 | 2 | [3, []]]
      │            ^
      │
    └─ lib/demo_web/router.ex:17:14: DemoWeb.Router (module)


  == Compilation error in file lib/demo_web/router.ex ==
  ** (CompileError) lib/demo_web/router.ex: cannot compile module DemoWeb.Router (errors have been logged)
```

When the sentence begins with the conditional "between brackets", the | operator is deterministic.

## Map and struct compile-time errors
Let me know if this needs to be broken off separate, but going through the text of the `error: misplaced operator |/2` error message has me thinking about other error messages involving the | operator.

### Using  the | operator to create a new key-value pair

Current:
```
  == Compilation error in file lib/demo_web/router.ex ==
  ** (CompileError) lib/demo_web/router.ex: cannot compile module DemoWeb.Router (errors have been logged)

  ** (KeyError) key :y not found
      lib/demo_web/router.ex:22: (module)== Compilation error in file lib/demo_web/router.ex ==
  ** (KeyError) key :y not found
      lib/demo_web/router.ex:22: (module)
```

Proposed:
```
      error: missing key :y

      The %{map | key: value} notation updates existing values.
      │
 17 │    x = %{map | y: 3}
      │                         ^
      │
    └─ lib/demo_web/router.ex:22:14: DemoWeb.Router (module)

  == Compilation error in file lib/demo_web/router.ex ==
  ** (CompileError) lib/demo_web/router.ex: cannot compile module DemoWeb.Router (errors have been logged)
```

### Using a comma to update existing values

Current:
```
  == Compilation error in file lib/demo_web/router.ex ==
  ** (SyntaxError) invalid syntax found on lib/demo_web/router.ex:21:18:
      error: syntax error before: ','
      │
 21 │   x = %{ map | :x, 3}
      │                             ^
      │
     └─ lib/demo_web/router.ex:21:18
      (elixir 1.16.0) lib/kernel/parallel_compiler.ex:428: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

Proposed:
```
== Compilation error in file lib/demo_web/router.ex ==
** (SyntaxError) invalid syntax found on lib/demo_web/router.ex:21:18:
    error: syntax error before: ','
    
    The %{map | key: value} notation updates existing values.
    │
 21 │   x = %{ map | :x, 3}
    │                             ^
    │
    └─ lib/demo_web/router.ex:21:18
    (elixir 1.16.0) lib/kernel/parallel_compiler.ex:428: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8
```

###Question###
* Does the location of "== Compilation error ..." vary depending on when in the compilation process the error is caught?

**Comment by josevalim** [comment]
The caret is not misplaced. It sees the first `|` as correct and the second then is incorrect but I agree with could make it clearer. I will give it a shot at that. The `|` syntax for maps is completely separate though, that's a runtime exception, not a compiler one, so it has a different format and different information available.

**Comment by josevalim** [comment]
What do you folks think about:

```
error: misplaced operator |/2

The | operator is typically used between brackets to mark
the tail of a list:

    [head | tail]
    [head, middle, ... | tail]

It is also used to update maps and structs, via the
%{map | key: value} notation, and in typespecs, such
as @type and @spec, to express the union of two types
```

**Comment by bradhanks** [comment]
Looks pretty helpful to me.

**Comment by bradhanks** [comment]
> The caret is not misplaced. It sees the first `|` as correct and the second then is incorrect but I agree with could make it clearer. I will give it a shot at that. The `|` syntax for maps is completely separate though, that's a runtime exception, not a compiler one, so it has a different format and different information available.

That's great to know. I'm looking at a couple files with a lot of improper lists in ecto_sql atm.

**Comment by josevalim** [comment]
The  new message is in main.
