### ISSUE TITLE
Populate `$callers` with `start_supervised`

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#13252]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.15.4 (compiled with Erlang/OTP 26)

### Operating system

Mac OS

### Current behavior

Using ex_units `start_supervised` the started process doesn't `:"$callers"` set correctly.

### Expected behavior

Have `:"$callers"` set correctly.

**Comment by josevalim** [comment]
Can you expand more? $callers and $ancestors are separate things. Supervision typically set ancestors.

**Comment by LostKobrakai** [comment]
I think as a user of `start_supervised` I shouldn‘t need to care that there‘s a separate supervisor process involved. Currently one cannot use `start_supervised` if `$callers` is required for a test to work properly, which I guess isn‘t as relevant to `Task`, but imo is to use cases like Mox or other tools, which link processes to the context of a test.

**Comment by josevalim** [comment]
It is not about start_supervised starting a process, but rather that callers is never set when going through the child_spec start.

**Comment by LostKobrakai** [comment]
Tbh to me that's totally fine. My interest in `$callers` is purely practical in that it is useful for a bunch of test tooling and I'd love to see it used in more places. As it stands right now that tooling can only be used if I manually call an API for starting processes, which harnesses `$callers`, e.g. `Task.async`. 

I'm looking into using `$callers` for processes, which actually are "long running" (contrary to `Task`), which are scoped to a test when started. That started would be `MyModule.start_link([])`. If I replace `MyModule.start_link([])` with `start_supervised(MyModule)` it breaks however. I think that shouldn't be the case, because to someone not intimate with the details the difference likely won't be obvious. I also doubt they'll know to replace `start_supervised(MyModule)` with `MyModule.start_link([])` to get it working. Likely they'll just default to synchronous tests at that point.

The same case can be made with `Task`, which also sets `$callers` on `start_link/1`, but again it it only works wenn calling `start_link` manually, but not when calling it through `start_supervised`. It just happens to be, that calling `Task` via a child_spec is rare.

**Comment by ityonemo** [comment]
I've run into this a lot.

**Comment by ityonemo** [comment]
Apologies for the walled garden, but:  https://twitter.com/DNAutics/status/1750236523579003182

**Comment by josevalim** [comment]
Moving discussion to PR, as we will discuss the final details there. :)
