### ISSUE TITLE
Prepending ./ to the test file path a command like `mix test ./test/some_test.exs:9` breaks the line filter and all tests are excluded

### ISSUE THREAD

**Issue by leikind** [elixir-lang/elixir#13257]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

macOS Sonoma 14.2.1

### Current behavior

`mix test ./test/superproject_test.exs:9` results in all tests excluded.

```
~/superproject → mix test ./test/superproject_test.exs:9
Compiling 1 file (.ex)
Generated superproject app
Excluding tags: [:test]
Including tags: [location: {"./test/superproject_test.exs", 9}]

All tests have been excluded.

Finished in 0.00 seconds (0.00s async, 0.00s sync)
3 tests, 0 failures, 3 excluded

Randomized with seed 605037
```

The same command without `./` works as expected:

```
~/superproject: → mix test test/superproject_test.exs:9
Compiling 1 file (.ex)
Generated superproject app
Excluding tags: [:test]
Including tags: [location: {"test/superproject_test.exs", 9}]

.
Finished in 0.00 seconds (0.00s async, 0.00s sync)
3 tests, 0 failures, 2 excluded

Randomized with seed 915642
```

In Elixir 1.15.7 command `mix test ./test/superproject_test.exs:9` works as expected.

You can reproduce this behaviour in this newly generated mix project: https://github.com/leikind/superproject

### Expected behavior

`./` is a legitimate way to start a file path in Unix, and both commands `mix test ./test/superproject_test.exs:9` and `mix test test/superproject_test.exs:9` should produce the same results, as it was in Elixir 1.15.7

**Comment by sabiwara** [comment]
Thank you for the report 💜
Fixed by https://github.com/elixir-lang/elixir/pull/13258.
