### ISSUE TITLE
Parallel loading NIF causes segmentation fault

### ISSUE THREAD

**Issue by pojiro** [elixir-lang/elixir#13256]
### Elixir and Erlang/OTP versions

```elixir
elixir --version
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 26)
```

### Operating system

```
uname -a
Linux X1-Carbon-9th 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### Current behavior

I created reprodusible repo, https://github.com/pojiro/test_defer_load_nif. 
`mix test test/test_defer_load_nif_test.exs:10` reproduces this issue. (if not please invoke it several times.

---

We found this issue when we try to defer loading nif, the code is following.

```elixir
defmodule TestDeferLoadNif do
  def load_nif() do
    nif_binary = Application.app_dir(:test_defer_load_nif, "priv/test_defer_load_nif")
    :erlang.load_nif(to_charlist(nif_binary), 0)
  end

  def test() do
    case load_nif() do
      :ok -> apply(__MODULE__, :test, [])
      {:error, {:reload, _}} -> apply(__MODULE__, :test, [])
      error -> error
    end
  end
end
```

- before loading NIF: `test/0` calls `load_nif/0`.
- after loading NIF: `test/0` calls NIF it self.

This works fine with sequential calling `test/0`, but this happens segfault with parallel calling `test/0`.
We couldn't understand why this happens in race conditions.

### Expected behavior

Maybe it would be better to work in race conditions?

**Comment by josevalim** [comment]
This would be an issue with Erlang itself, as it is the one doing the NIF loading. However, I am 99% sure that NIFs must be loaded inside the on_load callback. Allowing one to load NIFs anytime after the module is loaded would likely require to introduce complexity into the loader and additional locks into the runtime.
