### ISSUE TITLE
Compilation from scratch freezing with Elixir 1.16

### ISSUE THREAD

**Issue by remotecom** [elixir-lang/elixir#13263]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

Ubuntu 23.10

### Current behavior

We have a code base with more than 9000 files (currently `Compiling 9066 files (.ex)`) and compilation takes a while with Elixir 1.15.7 but finishes.

After I bumped the version to 1.16 (keeping the exact same Erlang version, `26.1.2`), compilation starts as usual (using all cores available), but after a while it just freezes without showing any error.

These are the last lines it showed:
![image](https://github.com/elixir-lang/elixir/assets/76113666/67f5152f-7bde-452f-9cac-eca50cf86f59)

In the beginning of the compilation, core usage looks like this:
![image](https://github.com/elixir-lang/elixir/assets/76113666/7394003d-f9d7-495b-b23e-833aa097cd35)

I'm saying "it freezes" because all cores go to "idle" after a while:
![image](https://github.com/elixir-lang/elixir/assets/76113666/62ee382b-68ac-4dfb-b155-6d74ef24cd57)

When it freezes, all `beam.smp` processes are using `0.0%` CPU:
![image](https://github.com/elixir-lang/elixir/assets/76113666/a332e95f-2fcd-49f0-b42e-d51e69ec8042)

:information_source: Plz also note that:
- My colleagues with Macs (M1) don't have any problem;
- The last file being compiled when it freezes seems to be random, it changes with each try;
- If I cancel the compilation after it freezes (using `Ctrl-C + (a)bort`) and try `mix compile` again, the compilation sometimes works.
- If I'm able to compile the entire application, further recompilations (after tweaking some files or fetching latest `master`) work as expected.

Sorry for not being able to provide more input, given this seems to be related with the code base size (I don't have any problem with smaller projects). Is there any debug flags/config I can use to debug this?

Thank you in advance!

### Expected behavior

I'd expect the compilation to finish.

**Comment by josevalim** [comment]
To rule conflicts with IDE and other tools, please make sure you only have one instance of beam.smp running. :)
