### ISSUE TITLE
Dialyzer error when using `||` with `:no_missing_return` option

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/elixir#13269]
Just registering it for discoverability since it probably requires a fix upstream in dialyzer itself.

The following code:

```elixir
  @spec foo(String.t()) :: integer()
  def foo(text), do: one(text) || two(text)

  defp one("1"), do: 1
  defp one(_), do: nil
  defp two("2"), do: 2
  defp two(_), do: 0
```

incorrectly reports:

```elixir
...:123:missing_range
The type specification is missing types returned by function.

Function:
Foo.foo/1

Type specification return types:
integer()

Missing from spec:
nil
```

`nil` is not a possible return type here.
This seems to be due to success typing not working well with `orelse` guards in Erlang:

```erlang
-spec foo(string()) -> integer().
foo(Text) ->
  case one(Text) of
    X when X == false orelse X == nil -> two(Text);
    X -> X
  end.

one("1") -> 1;
one(_) -> nil.

two("2") -> 2;
two(_) -> 0.
```

**Comment by josevalim** [comment]
Does it work if we use when twice instead of orelse? We will need to change both the macro and some parts of the compiler, but it should work

**Comment by josevalim** [comment]
Yeah, so it sounds like a Dialyzer bug indeed. Can you reproduce it in pure Erlang?

**Comment by sabiwara** [comment]
> Can you reproduce it in pure Erlang?

Yes it's included at the end of the description.
Will open an issue to OTP and close this one, I don't think we can solve it in Elixir.
