### ISSUE TITLE
`mix test --raise` in umbrella does not run all tests

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#13265]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.16.0 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

When `mix test --raise` is run in umbrella app when one of the apps have failing tests, it raises immediately after running tests in that app. Tests in following apps are not attempted.

### Expected behavior

Run tests in all apps and then raise, similarly to `mix test` which runs test in all apps and then exits with appropriate exit code

**Comment by josevalim** [comment]
The whole purpose of `--raise` is to immediately raise, guaranteeing nothing else executes. If you want things to continue, why is `--raise` being used?

**Comment by lukaszsamson** [comment]
My use case was to avoid the default behavior that silently swallows errors and communicates via exit code. Mix task returns :ok regardless of the test suite result

**Comment by josevalim** [comment]
If you are programmatically invoking the API, Then you could do the umbrella recursion yourself combined with the raise flag. I’m also open to different return values, but other than that, the flag is working, as it was designed/requested. Thanks!
