### ISSUE TITLE
Compilation from scratch freezing with Elixir 1.16

### ISSUE THREAD

**Issue by amalbuquerque** [elixir-lang/elixir#13264]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

```
$ cat .tool-versions
erlang 26.1.2
elixir 1.16.0-otp-26
```

### Operating system

Ubuntu 23.10, 13th Gen Intel(R) Core(TM) i7-1355U

### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

Ubuntu 23.10

### Current behavior

We have a code base with more than 9000 files (currently `Compiling 9066 files (.ex)`) and compilation takes a while with Elixir 1.15.7 but finishes.

After I bumped the version to 1.16 (keeping the exact same Erlang version, `26.1.2`), compilation starts as usual (using all cores available), but after a while it just freezes without showing any error.

These are the last lines it showed:
![image](https://github.com/elixir-lang/elixir/assets/76113666/67f5152f-7bde-452f-9cac-eca50cf86f59)

In the beginning of the compilation, core usage looks like this:
![image](https://github.com/elixir-lang/elixir/assets/76113666/7394003d-f9d7-495b-b23e-833aa097cd35)

I'm saying "it freezes" because all cores go to "idle" after a while:
![image](https://github.com/elixir-lang/elixir/assets/76113666/62ee382b-68ac-4dfb-b155-6d74ef24cd57)

When it freezes, all `beam.smp` processes are using `0.0%` CPU:
![image](https://github.com/elixir-lang/elixir/assets/76113666/a332e95f-2fcd-49f0-b42e-d51e69ec8042)

:information_source: Plz also note that:
- My colleagues with Macs (M1) don't have any problem;
- The last file being compiled when it freezes seems to be random, it changes with each try;
- If I cancel the compilation after it freezes (using `Ctrl-C + (a)bort`) and try `mix compile` again, the compilation sometimes works.
- If I'm able to compile the entire application, further recompilations (after tweaking some files or fetching latest `master`) work as expected.

Sorry for not being able to provide more input, given this seems to be related with the code base size (I don't have any problem with smaller projects). Is there any debug flags/config I can use to debug this?

Thank you in advance!

### Expected behavior

I'd expect the compilation to finish.

**Comment by josevalim** [comment]
Please kill all other beam.smp processes (and editors) and try again. If it persists, please shoot me an email (you can find it under my github profile).

**Comment by josevalim** [comment]
I have also checked the history in the ParallelCompiler, and the only change I saw was related to this commit: 22dcba75d2c4a5d4cb4c3d3dfab53a9f08744d6f

You can also try cloning Elixir, checking out version v1.16.0, reverting that commit, and see if the issue persists or not. If it persists, then we'll need a debugging session.

**Comment by amalbuquerque** [comment]
In the meantime I've restarted the machine, ensured nothing was running (including IDEs) and ran `rm -rf _build && mix deps.compile && mix compile` resulting in the same behaviour.

I've asked another colleague using Linux to try to compile the code from scratch and he also observed the same behaviour.

I'll do the same with Erlang/OTP 26.0.2 and then with 25.3.2.8 and will report back.

**Comment by amalbuquerque** [comment]
I had trouble running both Elixir `main` and Erlang `master` branches (installed with `asdf`), `mix` was failing (even after reinstalling `hex` per the suggestions in the error); attached [here](https://github.com/elixir-lang/elixir/files/13980665/error-mix-elixir-main-erlang-master.txt) is the error that I got.

Running Elixir `main` (commit https://github.com/elixir-lang/elixir/commit/f14bcdcac9df251bee72cfd060a2782ef0e471e0), Erlang 26.1.2 it also froze (tried 3 times):

```
$ cat .tool-versions
erlang 26.1.2
elixir path:/home/andre/projs/personal/elixir
```
![image](https://github.com/elixir-lang/elixir/assets/557562/c8c8d2c5-3b94-489f-82ee-02cf37dfafc2)

Reverting the commit https://github.com/elixir-lang/elixir/commit/22dcba75d2c4a5d4cb4c3d3dfab53a9f08744d6f with the same Erlang 26.1.2 version also froze :open_mouth: (I left the last try running for >2h without success, the same symptoms: compilation process hanging, `beam.smp` processes not using any CPU)

![image](https://github.com/elixir-lang/elixir/assets/557562/ee014b67-8155-463f-b19a-8f572391c05c)

Just in case, this is how the revert looks like: https://github.com/elixir-lang/elixir/commit/aa8ec356ad7bfbbbf700c885959bc6172dd1806e

**Comment by josevalim** [comment]
Thank you! Please shoot me an email at my GitHub profile so we figure something out. :)
