### ISSUE TITLE
Mix recompile in iex doesn't work after File.cd

### ISSUE THREAD

**Issue by entertainyou** [elixir-lang/elixir#13260]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

ArchLinux

### Current behavior

1. Create a minimal mix project `mix new mix_test`
2. Start iex mix session, `iex -S mix`
3. Execute File.cd in iex to change cwd to another directory `File.cd("/tmp")`
4. Change `lib/mix_test.ex` file
5. Execute `recompile` in iex, above `lib/mix_test.ex` is not compiled

### Expected behavior

For me I would expect `lib/mix_test.ex` is recompiled in step 5, or at least show a warning that cwd is not Mix project root directory.

**Comment by josevalim** [comment]
We should probably check in `recompile` if we have a `Mix.Project.get` and, if so, `File.cwd` has a mix.exs. PRs welcome.

**Comment by entertainyou** [comment]
@josevalim what should be done if `Mix.Project.get` exists and `File.cwd`doesn't contain a mix.exs?  Also, I tested if `File.cd` into another mix project, `recompile` would recompile the files in that mix project, doesn't seems expected to me.  

Maybe we should save a project root path when configuring the initial Mix project and use that as the base for `config_path`, `elixirc_paths`, etc instead of relying on cwd?

**Comment by josevalim** [comment]
@entertainyou we can emit a warning.

> Also, I tested if File.cd into another mix project, recompile would recompile the files in that mix project, doesn't seems expected to me.

Good find. We can check this:

```
proj = Mix.Project.get()
if proj && proj.__info__(:compile)[:source] == String.to_charlist(Path.absname("mix.exs")) do
  continue
else
  IO.warn("relocated")
end
```

**Comment by josevalim** [comment]
Merged, ty!
