### ISSUE TITLE
dbg/1 no longer stops on breakpoints in a mix project (`iex -S mix`)

### ISSUE THREAD

**Issue by pdgonzalez872** [elixir-lang/elixir#13271]
### Elixir and Erlang/OTP versions

```
paulo@t1 ~/dev/random/dbg_issue (main)$ elixir --version
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.17.0-dev (991baf9) (compiled with Erlang/OTP 26)
```

### Operating system

Linux

### Current behavior

Hi!

I don't think the following behaviour is intented: When leveraging breakpoints with in a mix project, a common workflow is to run something like `iex -S mix test --trace` after setting dbg/1 in a code path we want to look at a bit closer.

This snip shows that `IEx.pry()` still works as expected, but the `dbg/1` call doesn't (note the `line number in lib/dbg_issue.ex:17`)

```
paulo@t1 ~/dev/random/dbg_issue (main)$ iex -S mix test --trace

DbgIssueTest [test/dbg_issue_test.exs]
  * test greets the world [L#5][lib/dbg_issue.ex:16: DbgIssue.hello/0]
binding() #=> []

Request to pry #PID<0.149.0> at DbgIssue.hello/0 (lib/dbg_issue.ex:17)

   14:   """
   15:   def hello do
   16:     dbg()
   17:     require IEx; IEx.pry
   18:     :world
   19:   end
   20: end

Allow? [Yn] Y
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.17.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> whereami
Location: lib/dbg_issue.ex:17

   15:   def hello do
   16:     dbg()
   17:     require IEx; IEx.pry
   18:     :world
   19:   end

    (dbg_issue 0.1.0) lib/dbg_issue.ex:17: DbgIssue.hello/0
    test/dbg_issue_test.exs:6: DbgIssueTest."test greets the world"/1
    (ex_unit 1.17.0-dev) lib/ex_unit/runner.ex:472: ExUnit.Runner.exec_test/2
    (stdlib 5.1.1) timer.erl:270: :timer.tc/2
    (ex_unit 1.17.0-dev) lib/ex_unit/runner.ex:394: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4

iex(2)> 
```

I did see some [docs on breakpoints](https://hexdocs.pm/elixir/main/debugging.html#breakpoints) but using the `--dbg pry` flag didn't seem to work for me. Maybe I'm missing something here:

```
paulo@t1 ~/dev/random/dbg_issue (main)$ iex -S mix test --trace --dbg pry
** (Mix) Could not invoke task "test": 1 error found!
--dbg : Unknown option
paulo@t1 ~/dev/random/dbg_issue (main)$ 
```

Here is a [link to a repo that could help you](https://github.com/pdgonzalez872/dbg_issue), you can run `iex -S mix test` there and see the behaviour.

Thank you for your work as always! :heart: 

### Expected behavior

`iex -S mix test --trace` with a dbg/1 should create a breakpoint, like `IEx.pry()` does and `dbg()` does in earlier versions.

**Comment by josevalim** [comment]
You need to pass the --dbg flag to `iex`, not `mix`:

    iex --dbg pry -S mix test --trace

I will change `mix test` to raise for unknown commands. :)

**Comment by pdgonzalez872** [comment]
Ohh!! Thanks @josevalim ! ❤️
