### ISSUE TITLE
URI.encode/1 should encode [, ] and @ in the path component

### ISSUE THREAD

**Issue by 1player** [elixir-lang/elixir#13279]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

Linux

### Current behavior

```
iex(31)> URI.encode("https://example.com/foo[@bar]")
"https://example.com/foo[@bar]"
iex(32)> URI.encode("https://example.com/foo[@bar]") |> URI.new!()
** (URI.Error) cannot parse due to reason invalid_uri: ":"
    (elixir 1.16.0) lib/uri.ex:645: URI.new!/1
    iex:32: (file)
```

### Expected behavior

The documentation for URI.encode/1 states "By default, this function is meant to escape the whole URI, and therefore **it will escape all characters which are foreign to the URI specification**." (emphasis mine)

`[`, `]`, and `@` are not accepted in the path component as per RFC 3986 (https://www.rfc-editor.org/rfc/rfc3986#section-3.3). Only `sub-delims` characters are accepted, which do not include these.

In general, I expect the invariant `URI.encode(string) |> URI.new!()` to be maintained at all cases.

**Comment by 1player** [comment]
Similar problem because of this, `URI.merge/2` is able to create %URI{} structures which are invalid and unparseable:

```
iex(32)> URI.merge("http://example.com", "/foo[bar]")
%URI{
  scheme: "http",
  authority: "example.com",
  userinfo: nil,
  host: "example.com",
  port: 80,
  path: "/foo[bar]",
  query: nil,
  fragment: nil
}
iex(33)> URI.merge("http://example.com", "/foo[bar]") |> URI.to_string()
"http://example.com/foo[bar]"
iex(34)> URI.merge("http://example.com", "/foo[bar]") |> URI.to_string() |> URI.new()
{:error, ":"}
```

Once again, I expect the invariant `URI.to_string() |> URI.new!()` to always hold

**Comment by josevalim** [comment]
I will update the documentation because it is ambiguous here. It means to say all characters that are foreign to the _whole_ URI specification, so the ones that are not valid _anywhere_.

The following paragraph is clearer:

>   Because different components of a URI require different escaping
>  rules, this function also accepts a `predicate` function as an optional
>  argument.
