### ISSUE TITLE
dedup_by Results The Same Output Whatever The Condition Is

### ISSUE THREAD

**Issue by AmalDarKhalil** [elixir-lang/elixir#13291]
### Elixir and Erlang/OTP versions

Erlang/OTP 24 [erts-12.2.1]
Elixir 1.13.3

### Operating system

MAC OS

### Current behavior

**The output results when the condition is true and the condition is false are the same.**

```elixir
iex> Enum.dedup_by([5, 1, 2, 3, 2, 1], fn x -> true end)
```

Output: 
```elixir
[5] 
```

```elixir
iex> Enum.dedup_by([5, 1, 2, 3, 2, 1], fn x -> false end)
```

Output: 
```elixir
[5] 
```

### Expected behavior

**Expected Results:**
1. `Enum.dedup_by([5, 1, 2, 3, 2, 1], fn x -> true end)`
   - The function `fun` always returns `true`. This means that, according to the logic of your `dedup_by/2` function, every element will be considered different from the previous one, and there will be no consecutive duplicates.
   - The output will be the same as the input, and the order will be preserved.

   Output:
   ```elixir
   [5, 1, 2, 3, 2, 1]
   ```

2. `Enum.dedup_by([5, 1, 2, 3, 2, 1], fn x -> false end)`
   - The function `fun` always returns `false`. This means that, according to the logic of your `dedup_by/2` function, every element will be considered the same as the previous one, and consecutive duplicates will be collapsed.
   - The output will be a list containing only the first element.

   Output:
   ```elixir
   [5]
   ```

**Comment by josevalim** [comment]
There is no bug here. The second argument of the function is not a conditional, but a value used to group when to dedup. If you want, each element of the list should be treated as individual then you should return the element itself.
