### ISSUE TITLE
`@external_resource` relies on mtime of a file

### ISSUE THREAD

**Issue by florius0** [elixir-lang/elixir#13298]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns] [dtrace]

Elixir 1.15.6 (compiled with Erlang/OTP 26)

### Operating system

All

### Current behavior

When using `@external_resource`, module may not be recompiled when manifest is newer than the external resource.

It happens because of https://github.com/elixir-lang/elixir/blob/92db97eab2228fe86344da91cbfe6f103b529a42/lib/mix/lib/mix/compilers/elixir.ex#L431

Steps to reproduce:

1. Add an external resource to the module
2. Compile project
3. Change external resource content
4. Set mtime of `Mix.Compilers.Elixir`'s  manifest to be after mtime of the external resource
5. Compile project

This will result in module not being recompiled, which contradicts [the docs](https://hexdocs.pm/elixir/1.14/Module.html#module-compile-options)

For example, this behaviour does not allow "naive" caching of `_build` directory in CI pipelines

 

### Expected behavior

Expected behaviour is for module to be recompiled.

Based upon my study of [previous issue regarding this topic](https://github.com/elixir-lang/elixir/issues/12057) I understand that it was likely introduced for optimisation purposes.

Proposed solutions:

- make this optimisation toggleable via configuration
- add a mechanism for module to check if it needs to be re-compiled due to external resource changes
- detect stale external resource using digest exclusively.

IMO relying on mtime is unreliable by itself and should be avoided

**Comment by josevalim** [comment]
It has always relied on mtime, it is not a new change. Can you please provide a more detailed description of what you want to achieve?

What is naive caching? Which commands are you expecting to run? Is the caching being busted (recompiled when it should not) or stale (not recompiling when it should)?

**Comment by florius0** [comment]
> Can you please provide a more detailed description of what you want to achieve?

I would like to have some control of how compiler determines if module needs to be recompiled due to external resource change.

The degree of said control is up to discussion, however the option to not rely on mtime's should be present in my opinion, or at least this mechanism should be documented.

It took me quite some time to come up with this fix for my project:

`find _build -type f -path '*/lib/project_name/.mix/compile.elixir' -exec touch -d "@0" {} \;`

> Is the caching being busted (recompiled when it should not) or stale (not recompiling when it should)?

The caching is being stale, module is not being recompiled on change of external resource.

> What is naive caching? Which commands are you expecting to run?

I'm still working on stable reproduction, however feel free to take a look at https://github.com/florius0/external_resource_mtime.

**Comment by josevalim** [comment]
A simple solution to this problem is to also store the inode of external resources. So whenever files are copied the recompilation will happen. I will explore these ideas later.

**Comment by florius0** [comment]
I was going through docs to check if I missed something, and I want to confirm this with you:

Is [`__mix_recompile__?/0`](https://hexdocs.pm/mix/Mix.Tasks.Compile.Elixir.html#module-__mix_recompile__-0) being called for **every* module, even if it was compiled previously and isn't marked for recompilation currently? If so, that is that control I was talking about.

First time reading this I somehow got the idea that it is being called only if module is being recompiled.

> A simple solution to this problem is to also store the inode of external resources. So whenever files are copied the recompilation will happen. I will explore these ideas later.

May be the compiler should rely not only on mtime, but on all fs metadata except certain properties such as last access time?

**Comment by josevalim** [comment]
> A simple solution to this problem is to also store the inode of external resources. So whenever files are copied the recompilation will happen.

I just played with this and this makes it much harder for people to effectively cache in CI :( So I don't think we can go down this path.

> Is [__mix_recompile__?/0](https://hexdocs.pm/mix/Mix.Tasks.Compile.Elixir.html#module-__mix_recompile__-0) being called for *every module, even if it was compiled previously and isn't marked for recompilation currently?

Correct. However, if you are using this to deal with mtime, it feels like the wrong solution, which is why I didn't mention it. :)

**Comment by josevalim** [comment]
@florius0 quick question: are you restoring the cache first and then pulling in changes from Git OR are you pulling changes from Git and then restoring the cache?

**Comment by florius0** [comment]
> are you restoring the cache first and then pulling in changes from Git OR are you pulling changes from Git and then restoring the cache?

The 2nd case, I'm pulling from git and then restoring cache.

However my actual workflow where I encountered the problem is a bit more complicated. Build is dockerized and the cache is being mounted inside build container and then copied around (the tool I'm using does not support cache mounts, only regular mounts).

And that is why I opted to set manifest's mtime to 0 instead of trying to restore actual mtimes.

**Comment by josevalim** [comment]
Yeah, restoring the cache after git will be problematic. I know how to improve this workflow though, so I will play with it, but it will only be available for Elixir v1.17.

**Comment by josevalim** [comment]
In such cases, you should at least attempt to preserve timestamps from the cache, but there is still a chance of race condition if you allow concurrent jobs generating the cache and reading from the cache.

**Comment by florius0** [comment]
I'm not sure if it's related, but I've came across similar problem when updating one of my project's dependencies.

The error was when doing `mix deps.compile` one of the dependencies was outdated, however the version in mix.exs of the dependency was correct.

Setting mtime's to 0 of every `compile.elixir` didn't help, however of every file in `.mix` directories did.
