### ISSUE TITLE
Curious about behaviour with -0.0

### ISSUE THREAD

**Issue by seanhuggins1** [elixir-lang/elixir#13294]
### Elixir and Erlang/OTP versions

Elixir 1.15.4 (compiled with Erlang/OTP 25)

### Operating system

macOS 14.1.1

### Current behavior

I am trying to understand why this behaviour occurs.

Let's say I have a module
```
defmodule Util do
  def normalize_zero(-0.0), do: 1.0
end
```

If I run this, it outputs what you would expect
```
iex> Util.normalize_zero(-0.0)
1.0
```

Now if I change the function head to return `0.0`
```
defmodule Util do
  def normalize_zero(-0.0), do: 0.0
end
```

The output of `Util.normalize_zero(-0.0)` is `-0.0`, not `0.0`!

Is it expected that the sign would be preserved like this?

### Expected behavior

I expected that the output of `Uti.normalize_zero(-0.0)` would be `0.0` in the example I gave.

**Comment by sabiwara** [comment]
As far as I know this is an upstream issue in Erlang which should be fixed in OTP27 https://github.com/erlang/otp/issues/7168.

**Comment by josevalim** [comment]
I have verified this is fixed on Erlang/OTP 27.

**Comment by seanhuggins1** [comment]
@sabiwara @josevalim 
oh very cool, thanks for the reply!

One interesting thing & the reason why this came up for me, I was doing some maths using `:math.atan2(y, x)` and noticed that you get a different result with `x = 0.0` vs. `x = -0.0`.

ex.
```
iex> :math.atan2(0.0, 0.0)
0.0
```

```
iex> :math.atan2(0.0, -0.0)
3.141592653589793
```

the definition of `atan2` being that if `x < 0` we add π.
<img width="437" alt="image" src="https://github.com/elixir-lang/elixir/assets/22649672/a90acd99-b752-4cf5-8408-6424077e0d42">

I was trying to normalize `-0.0` to `0.0` so that I'd get a consistent output here.

the output felt funky, because if we're saying that `0.0` & `-0.0` are the same in Elixir, you'd think we would have the same output for this function for `0.0`, vs. `-0.0`.

But after some digging, it looks like elixir delegates to erlang which delegates to c standard lib, and if I run this c code

```
#include <stdio.h>
#include <math.h>

int main() {
    double x, y, result;

    y = 0.0;
    x = -0.0;
    result = atan2(y, x);
    
    printf("%.2f", result);

    return 0;
}
```

I get the same shift by `π` with `x = -0.0` vs. `x = 0.0`! So my guess is the underlying c implementation is checking for the sign bit?

Not really a bug, just an interesting little low level quirk!

**Comment by seanhuggins1** [comment]
indeed here is the implementation from a `gcc` mirror that checks for the sign bit
https://github.com/gcc-mirror/gcc/blob/4bdcc8b3bf239c48140647c19d3addebc5d4b930/libquadmath/math/atan2q.c#L68

**Comment by sabiwara** [comment]
@seanhuggins In the meantime, you can fix it on existing OTP versions by using a `==` guard:

```elixir
defmodule Util do
  def normalize_zero(x) when x == 0.0, do: 0.0
  def normalize_zero(x), do: x
end

iex> Util.normalize_zero(-0.0)
0.0
```

**Comment by seanhuggins1** [comment]
@sabiwara ah nice, thanks!
