### ISSUE TITLE
Mix breaks character encoding in Powershell on Windows Terminal

### ISSUE THREAD

**Issue by Intelliractive** [elixir-lang/elixir#13301]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

Windows 10

### Current behavior

I'm building an in-game chat filtering app and I experience odd behaviour in my program.
When I use `IO.gets()` in `iex`, everything works properly, but when I launch my code by `mix run` and accept messages there, it looks broken. 

```
PS C:\Users\Ilyushya\Documents\pfilter> mix
Compiling 1 file (.ex)
Generated pfilter app
>>gh
--->gh

>>привет
--->�ਢ��

>>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
Terminate batch job (Y/N)? Y
```

### mix.exs

```elixir
defmodule Pfilter.MixProject do
  use Mix.Project

  def project do
    [
      app: :pfilter,
      version: "0.1.0",
      elixir: "~> 1.16",
      start_permanent: Mix.env() == :prod,
      deps: deps()
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger],
      mod: {Pfilter, []}
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"}
    ]
  end
end
```

### My app code

```elixir
defmodule Pfilter do
  use Application

  def accept_messages do
    msg = IO.gets(">>")
    IO.puts("--->" <> msg)
    accept_messages()
  end

  @impl true
  def start(_start_type, _start_args) do
    accept_messages()
  end

end
```

I noticed this some time ago, but thought it was a project issue. However, it is a common abnormality.

### Expected behavior

I expect receiving normal message content (until I filter it 😈)

```
# starting manually
PS C:\Users\Ilyushya\Documents\pfilter> iex.bat -S mix
Compiling 1 file (.ex)
Generated pfilter app
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.16.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Pfilter.accept_messages
>>ge
--->ge

>>привет
--->привет

>>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
Terminate batch job (Y/N)? Y
```

**Comment by josevalim** [comment]
What does this code return when you execute with and without `iex`?

```
  @impl true
  def start(_start_type, _start_args) do
    IO.inspect :io.getopts()
    accept_messages()
  end
```

**Comment by josevalim** [comment]
Also, can you reproduce the bug by storing this in a file name `pfilter.ex`:

```
defmodule Pfilter do
  def run do
    msg = IO.gets(">>")
    IO.puts("--->" <> msg)
    accept_messages()
  end
end

Pfilter.run
```

And then doing `elixir pfilter.ex`?

**Comment by Intelliractive** [comment]
> What does this code return when you execute with and without `iex`?
> 
> ```
>   @impl true
>   def start(_start_type, _start_args) do
>     IO.inspect :io.getopts()
>     accept_messages()
>   end
> ```

```
mix
Generated pfilter app
[
  expand_fun: &:edlin_expand.expand/2,
  echo: false,
  binary: true,
  encoding: :unicode,
  terminal: true
]
>>hi
--->hi

>>привет
--->�ਢ��

>>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
Terminate batch job (Y/N)? Y
```

**Comment by josevalim** [comment]
@Intelliractive do not place the file I suggested above in `lib`. Instead, put it outside of `lib` and run it _without_ `mix`. Run it with `elixir pfilter.ex`.

**Comment by Intelliractive** [comment]
```
elixir .\pfilter.ex
>>как дела?
--->��� ����?

>>how are things?
--->how are things?

>>
```

**Comment by josevalim** [comment]
@Intelliractive can you save the code below to a file named `foo.erl`:

```erl
-module(foo).
-compile(export_all).

start() ->
  io:setopts([{binary, true}]),
  io:format("~p~n", [io:getopts()]),
  loop().

loop() ->
  Res = io:get_line(">> "),
  io:put_chars(["---> ", Res, $\n]),
  loop().
```

And then:

```
$ erlc foo.erl
$ erl -noshell -s foo
```

Now type the same characters. Does it reproduce the issue?

**Comment by Intelliractive** [comment]
This does reproduce the issue. It turned out it was an Erlang issue again. Thank you

**Comment by josevalim** [comment]
@Intelliractive do you want to report it upstream or should I? :)

**Comment by Intelliractive** [comment]
Good morning mr José! I have discovered that only Powershell behaves in that odd manner.

cmd
```
C:\Users\Ilyushya\Documents\yerkyn>dotnet build
MSBuild version 17.5.1+f6fdcf537 for .NET
  Определение проектов для восстановления...
  Все проекты обновлены для восстановления.
  yerkyn -> C:\Users\Ilyushya\Documents\yerkyn\bin\Debug\net7.0\yerkyn.dll

Сборка успешно завершена.
    Предупреждений: 0
    Ошибок: 0

Прошло времени 00:00:01.66
```

powershell
```
PS C:\Users\Ilyushya\Documents\yerkyn> dotnet build
MSBuild version 17.5.1+f6fdcf537 for .NET
  Определение проектов для восстановления...
  Все проекты обновлены для восстановления.
  yerkyn -> C:\Users\Ilyushya\Documents\yerkyn\bin\Debug\net7.0\yerkyn.dll

���ઠ �ᯥ譮 �����襭�.
    �।�०�����: 0
    �訡��: 0

��諮 �६��� 00:00:05.45
```

**Comment by Intelliractive** [comment]
> @Intelliractive do you want to report it upstream or should I? :)
 
There are already many issues open on topic of odd console behaviour, I guess😅

**Comment by josevalim** [comment]
@Intelliractive can you please try this version?

```
-module(foo).
-compile(export_all).

start() ->
  io:setopts([{binary, true}]),
  io:format("~p~n", [io:getopts()]),
  loop().

loop() ->
  Res = io:get_line(">> "),
  erlang:display(<<0, Res/binary>>),
  io:put_chars(["---> ", Res, $\n]),
  loop().
```

I just realized we are not sure if it is printing wrong or reading it wrong.

**Comment by lukaszsamson** [comment]
Remember that if you read from stdio in binary since OTP 26 you need to pass `-kernel standard_io_encoding latin1`, otherwise the encoding defaults to utf8

**Comment by josevalim** [comment]
@Intelliractive ping :)

**Comment by Intelliractive** [comment]
... pong? xD I've done some more research and figured out that of cmd and powershell stand-alone and in Windows Terminal (four in total), only cmd on WT behaves in an adequate way. I guess this is more an Erlang issue, should we close it here?

**Comment by josevalim** [comment]
@Intelliractive can you try this version of the Erlang program? https://github.com/elixir-lang/elixir/issues/13301#issuecomment-1918885813

Also, can you try this on the version of the installer from this PR? https://github.com/erlang/otp/pull/8103 It is a recent Erlang version, with some debugging, which will tell us if the bug has been fixed already or not. :)

**Comment by Intelliractive** [comment]
Hello @josevalim ! The new program works fine! Even in the VS Code terminal!

```
3> foo:start().
[{expand_fun,fun edlin_expand:expand/2},
 {echo,true},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> hello!<<0,104,101,108,108,111,33,10>>
>> hello!
---> hello!

>> привет!<<0,208,191,209,128,208,184,208,178,208,181,209,130,33,10>>
>> привет!
---> привет!

>> How are things?😀<<0,72,111,119,32,97,114,101,32,116,104,105,110,103,115,63,240,159,152,128,10>>
>> How are things?😀
---> How are things?😀

>> Как дела?😀<<0,208,154,208,176,208,186,32,208,180,208,181,208,187,208,176,63,240,159,152,128,10>>
>> Как дела?😀
---> Как дела?😀

>>
```

**Comment by Intelliractive** [comment]
It works properly on that new Erlang (27 release candidate) as well

```
foo:start().
[{expand_fun,fun edlin_expand:expand/2},
 {echo,true},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> привет
>> привет
---> привет

>> 😎Всё в порядке!
<<0,240,159,152,142,208,146,209,129,209,145,32,208,178,32,208,191,208,190,209,128,209,143,208,180,208,186,208,181,33,10>>> 😎Всё в порядке!
---> 😎Всё в порядке!

>> 😎Everything works fine!
>> 😎Everything works fine!
---> 😎Everything works fine!

>>
```

**Comment by josevalim** [comment]
And does the earlier program work on Erlang 27?

**Comment by Intelliractive** [comment]
> It works properly on that new Erlang (27 release candidate) as well
> 
> ```
> foo:start().
> [{expand_fun,fun edlin_expand:expand/2},
>  {echo,true},
>  {binary,true},
>  {encoding,unicode},
>  {terminal,true}]
> >> привет
> >> привет
> ---> привет
> 
> >> 😎Всё в порядке!
> <<0,240,159,152,142,208,146,209,129,209,145,32,208,178,32,208,191,208,190,209,128,209,143,208,180,208,186,208,181,33,10>>> 😎Всё в порядке!
> ---> 😎Всё в порядке!
> 
> >> 😎Everything works fine!
> >> 😎Everything works fine!
> ---> 😎Everything works fine!
> 
> >>
> ```

Here I demonstrate it running on the release you offered me to test, which is Erlang 27 in-development

**Comment by josevalim** [comment]
Sorry, to be clear, but that's the last program I shared, right? Does [the first program I shared](https://github.com/elixir-lang/elixir/issues/13301#issuecomment-1917656804) also works?

**Comment by Intelliractive** [comment]
Oh, what a frustration! I've just discovered that both versions don't work on Erlang 26.2.2 when run with commands you gave, but do work from Erlang shell, and I tested the second program in interactive mode. I've re-tested both code snippets in cmd in VS Code.

#### First

```
C:\Users\Ilyushya\Documents>erlc foo.erl
foo.erl:2:2: Warning: export_all flag enabled - all functions will be exported
%    2| -compile(export_all).
%     |  ^


[{expand_fun,fun edlin_expand:expand/2},
 {echo,false},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> привет
---> ਢ

>> Runtime terminating during boot ({badarg,[{io,put_chars,[["---> ",eof,10]],[{file,"io.erl"},{line,103},{error_info,#{cause=>{device,{put_chars,unicode,["---> ",eof,10]}},module=>erl_stdlib_errors}}]},{foo,loop,0,[{file,"foo.erl"},{line,11}]},{init,start_em,1,[{file,"init.erl"},{line,1182}]},{init,do_boot,3,[{file,"init.erl"},{line,871}]}]})

BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution


```

##### And here my console crashed (it does not respond)

![изображение](https://github.com/elixir-lang/elixir/assets/98094811/560dba50-c27a-4b08-95c4-f8db8ff5c905)


#### Second

```
C:\Users\Ilyushya\Documents>erlc foo2.erl
foo2.erl:2:2: Warning: export_all flag enabled - all functions will be exported
%    2| -compile(export_all).
%     |  ^


C:\Users\Ilyushya\Documents>erl -noshell -s foo2
[{expand_fun,fun edlin_expand:expand/2},
 {echo,false},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> Привет
<<0,194,143,195,160,194,168,194,162,194,165,195,162,10>>
---> ਢ

>> привет
<<0,194,175,195,160,194,168,194,162,194,165,195,162,10>>
---> ਢ

>> привет!
<<0,194,175,195,160,194,168,194,162,194,165,195,162,33,10>>
---> ਢ!

>>
```

#### First, `erl` shell

```
C:\Users\Ilyushya\Documents>erl
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V14.2.2 (press Ctrl+G to abort, type help(). for help)
1> c(foo).
foo.erl:2:2: Warning: export_all flag enabled - all functions will be exported
%    2| -compile(export_all).
%     |  ^

{ok,foo}
2> foo:start().
[{expand_fun,fun edlin_expand:expand/2},
 {echo,true},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> првиет
---> првиет

>>
```

#### Second, `erl` shell

```
C:\Users\Ilyushya\Documents>erl
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V14.2.2 (press Ctrl+G to abort, type help(). for help)
1> c(foo2).
foo2.erl:2:2: Warning: export_all flag enabled - all functions will be exported
%    2| -compile(export_all).
%     |  ^

{ok,foo2}
2> foo2:start().
[{expand_fun,fun edlin_expand:expand/2},
 {echo,true},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> привет<<0,208,191,209,128,208,184,208,178,208,181,209,130,10>>
>> привет
---> привет

>>
```

That's the exactly same behaviour as with Elixir without and with `IEx`

**Comment by Intelliractive** [comment]
## And now I put the two programs to the test on https://github.com/erlang/otp/pull/8103

### First

```
C:\Users\Ilyushya\Documents>erl -noshell -s foo
[{expand_fun,fun edlin_expand:expand/2},
 {echo,false},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> привет
---> ਢ

>>
---> 

>> hi
---> hi

>>   
```

### Second

```
Microsoft Windows [Version 10.0.19045.3930]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\Ilyushya\Documents>erlc foo2.erl
foo2.erl:2:2: Warning: export_all flag enabled - all functions will be exported
%    2| -compile(export_all).
%     |  ^


C:\Users\Ilyushya\Documents>erl -noshell -s foo2
[{expand_fun,fun edlin_expand:expand/2},
 {echo,false},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> привет
<<0,194,175,195,160,194,168,194,162,194,165,195,162,10>>
---> ਢ

>> hi
<<0,104,105,10>>
---> hi

>>
```

### First (`erl `shell)

```
Microsoft Windows [Version 10.0.19045.3930]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\Ilyushya\Documents>erl
Erlang/OTP 27 [DEVELOPMENT] [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V14.2.2 (press Ctrl+G to abort, type help(). for help)
1> c(foo).
foo.erl:2:2: Warning: export_all flag enabled - all functions will be exported
%    2| -compile(export_all).
%     |  ^

{ok,foo}
2> foo:start().
[{expand_fun,fun edlin_expand:expand/2},
 {echo,true},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> привет
---> привет

>>
--->

>> hi
---> hi

>>
```

### Second, `erl` shell

```
Microsoft Windows [Version 10.0.19045.3930]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

C:\Users\Ilyushya\Documents>erl
Erlang/OTP 27 [DEVELOPMENT] [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Eshell V14.2.2 (press Ctrl+G to abort, type help(). for help)
1> c(foo2).
foo2.erl:2:2: Warning: export_all flag enabled - all functions will be exported
%    2| -compile(export_all).
%     |  ^

{ok,foo2}
2> foo2:start().
[{expand_fun,fun edlin_expand:expand/2},
 {echo,true},
 {binary,true},
 {encoding,unicode},
 {terminal,true}]
>> привет
>> привет
---> привет

>>
>>
--->

>> hi
>> hi
---> hi

>>
```

**Comment by josevalim** [comment]
Yes, it is expected they work on the shell, you need to test them with `erl -noshell`. :)

Your output also makes it clear that the issue is that we are not reading the input correctly. Here is what we get for for "привет" in the wrong case:

```
<<0,194,175,195,160,194,168,194,162,194,165,195,162,10>>
```

However, it should be this:

```
<<0, 208, 191, 209, 128, 208, 184, 208, 178, 208, 181, 209, 130>>
```

I will do a bug report upstream later (unless you want to do it).

**Comment by Intelliractive** [comment]
Thank you so much!

**Comment by josevalim** [comment]
Sorry, I was reading everything again in order to the report and it seems `dotnet build` also shows the wrong behaviour under powershell? If that's the case, this may not be an Erlang issue after all. Did you try configuring the powershell encoding in any way?

**Comment by Intelliractive** [comment]
> Sorry, I was reading everything again in order to the report and it seems `dotnet build` also shows the wrong behaviour under powershell? If that's the case, this may not be an Erlang issue after all. Did you try configuring the powershell encoding in any way?

I have tested consuming Cyrillic input in Erlang and Elixir from CMD stand-alone, on Windows Terminal and VS Code, as well from Powershell stand-alone and on WT and VSC. No option seemed to work well. As for dotnet, the issue with encoding is only present in PS on WT, Cmd stand-alone required me to type `chcp 65001` to turn on UTF8, while Cmd on WT has no such problem

**Comment by josevalim** [comment]
Reported here: https://github.com/erlang/otp/issues/8113 - it is now being tracked upstream.
