### ISSUE TITLE
Support redirecting logger to stderr in .exs script easily

### ISSUE THREAD

**Issue by kidp330** [elixir-lang/elixir#13313]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

and

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 24)

### Operating system

Debian 12 container

### Current behavior

We'd like to be able to write a simple elixir script that could be integrated into a unix pipeline, by strictly controlling its output, e.g. redirecting all Logger output to stderr. From what I've gathered, changing logger device doesn't seem to support reconfiguration during runtime. Though this is marked as an `illegal_config_change` in the case of erlang's logger (see https://github.com/erlang/otp/blob/master/lib/kernel/src/logger_std_h.erl#L122), it is easy, though not obvious, to work around - example below.

The way we achieved the desired result is far from ideal - I believe that upon a short skim of the module's documentation, the most intuitive way to try and redirect the logs would be a single call `LoggerBackends.configure(device: :standard_error)`. But the default logger is not receptive to this request, and `configure/1` does not return any information on whether reconfiguration was successful. It is only possible to set device by removing the default manually via erlang's :logger API, adding a new logger and only then setting its device directly.

```elixir
require Logger

Mix.start()
Mix.shell(Mix.Shell.Quiet)

Mix.install(
  [
    :ratio
  ],
  force: true
)

Logger.configure(device: :standard_error)
Logger.error("this should be in stderr.log")
```
```command
root@5da670a83b2e:/workspace/membrane/logger_mre# elixirc mre.exs 2> stderr.log

10:33:19.472 [error] this should be in stderr.log
```

```elixir
require Logger

Mix.start()
Mix.shell(Mix.Shell.Quiet)

Mix.install(
  [
    :ratio
  ],
  force: true
)

:ok = Logger.configure_backend(:console, device: :standard_error)
Logger.error("this should be in stderr.log")
```
```command
root@5da670a83b2e:/workspace/membrane/logger_mre# elixirc mre.exs 2> stderr.log

10:47:13.698 [error] this should be in stderr.log
```

```elixir
require Logger

Mix.start()
Mix.shell(Mix.Shell.Quiet)

Mix.install(
  [
    :ratio
  ],
  force: true
)

Logger.add_backend(:console, device: :standard_error)
Logger.error("this should be in stderr.log")
```
```command
root@5da670a83b2e:/workspace/membrane/logger_mre# elixirc mre.exs 2> stderr.log

10:49:33.415 [error] this should be in stderr.log
```

```elixir
require Logger

Mix.start()
Mix.shell(Mix.Shell.Quiet)

Mix.install(
  [
    :ratio
  ],
  force: true
)

{:ok, _pid} = Logger.add_backend(Logger.Backends.Console, device: :standard_error)
Logger.error("this should be in stderr.log")
```
```command
root@5da670a83b2e:/workspace/membrane/logger_mre# elixirc mre.exs 2> stderr.log

10:50:22.892 [error] this should be in stderr.log

10:50:22.892 [error] this should be in stderr.log
```

```elixir
require Logger

Mix.start()
Mix.shell(Mix.Shell.Quiet)

Mix.install(
  [
    :ratio,
    :logger_backends
  ],
  force: true
)

:ok = LoggerBackends.configure(device: :standard_error)
Logger.error("this should be in stderr.log")
```
```command
root@5da670a83b2e:/workspace/membrane/logger_mre# elixirc mre.exs 2> stderr.log

10:57:03.706 [error] this should be in stderr.log
```

Here's what we're currently using:

```elixir
require Logger

Mix.start()
Mix.shell(Mix.Shell.Quiet)

Mix.install(
  [
    :ratio,
    :logger_backends
  ],
  force: true
)

:logger.remove_handler(:default)
LoggerBackends.add(LoggerBackends.Console)
LoggerBackends.configure(LoggerBackends.Console, device: :standard_error)

Logger.error("this should be in stderr.log")
```

`Logger.remove_backend` and `LoggerBackends.remove` don't seem to recognize any of the following handles: :console, `:default`, `:logger`, `:logger_std_h`, `Logger.Backends.Console`, `LoggerBackends.Console`.
It would be nice if the current API allowed reconfiguration of the default logger on the fly, or at least support removing it. It seems like passing device to `LoggerBackends.add/2` should be enough, but it also doesn't work.

Additionally, it seems that a new mix warning introduced in 1.16 does not get fully redirected to stderr:
```elixir
Mix.start()
Mix.shell(Mix.Shell.Quiet)

Mix.install(
  [
    :ratio
  ],
  force: true
)
```

```console
root@5da670a83b2e:/workspace/membrane/logger_mre# elixir mre.exs 2> stderr.log
==> ratio
root@5da670a83b2e:/workspace/membrane/logger_mre# cat stderr.log 
    warning: Ratio.DecimalConversion.decimal_to_rational/1 is undefined (module Ratio.DecimalConversion is not available or is yet to be defined)
    │
 17 │     {ratio, Ratio.DecimalConversion.decimal_to_rational(decimal)}
    │                                     ~
    │
    └─ lib/ratio/coerce.ex:17:37: Coerce.Implementations.Ratio.Decimal.coerce/2

both :extra_applications and :applications was found in your mix.exs. You most likely want to remove the :applications key, as all applications are derived from your dependencies
```

### Expected behavior

There exists a more intuitive, or at least better documented, way of setting logger device globally.

**Comment by lukaszsamson** [comment]
@kidp330 This is orthogonal to `Logger` setup but please note that `Mix.Shell.Quiet` is not really quiet. It still print s app banners, prompts, etc. https://github.com/elixir-lang/elixir/blob/e0658bb55a744e33a70c982c992666addc4feb38/lib/mix/lib/mix/shell/quiet.ex#L1

For that very reason ElixirLS uses a custom shell that redirects all those to `stderr` https://github.com/elixir-lsp/elixir-ls/blob/1ab31105e0ef1c0f7392b351cbed5976f3a8d6de/scripts/installer.exs#L1

**Comment by josevalim** [comment]
@kidp330 updating the logger handler is the way to go. The backend configuration is deprecated and supported for backwards compatibility, but Elixir does not use handlers by itself anymore.

If you can't update the handler, you can also remove and attach a new one:

```

:ok = :logger.remove_handler(:default)

:ok = :logger.add_handler(:default, :logger_std_h, %{
   config: %{
     type: {:device, :standard_error}
   },
   formatter: Logger.Formatter.new()
 }})

```

**Comment by kidp330** [comment]
> @kidp330 This is orthogonal to `Logger` setup but please note that `Mix.Shell.Quiet` is not really quiet. It still print s app banners, prompts, etc.
> 
> https://github.com/elixir-lang/elixir/blob/e0658bb55a744e33a70c982c992666addc4feb38/lib/mix/lib/mix/shell/quiet.ex#L1
> 
> For that very reason ElixirLS uses a custom shell that redirects all those to `stderr` https://github.com/elixir-lsp/elixir-ls/blob/1ab31105e0ef1c0f7392b351cbed5976f3a8d6de/scripts/installer.exs#L1

I did notice that, and it seems a chore to need to define a custom shell each time you need to silence mix completely, or redirect to stderr. Maybe it'd make sense to extend the available predefined shells like IO and Process to also include one logging to stderr? 
Unfortunately, we cannot abstract this process to our module, since it may be called only after Mix.install, making it something only the script user has control over.
