### ISSUE TITLE
UndefinedFunctionError when streaming non-utf8 file with encoding: utf8 set

### ISSUE THREAD

**Issue by Munksgaard** [elixir-lang/elixir#13323]
### Elixir and Erlang/OTP versions

 ❯ elixir --version
Erlang/OTP 25 [erts-13.2.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 25)

### Operating system

NixOS

### Current behavior

Trying to execute `File.stream!(file, encoding: :utf8) |> Enum.to_list()` on 
[this file](https://github.com/elixir-lang/elixir/files/14209984/error.xlsx) fails with a `UndefinedFunctionError`.

The error I get is:

```
> File.stream!("/home/munksgaard/tmp/error.xlsx", encoding: :utf8) |> Enum.to_list()
** (UndefinedFunctionError) function :unicode.format_error/1 is undefined or private
    (stdlib 4.3.1.3) :unicode.format_error(:unicode)
    (kernel 8.5.4.2) file.erl:160: :file.format_error/1
    (elixir 1.16.0) lib/io/stream.ex:7: IO.StreamError.exception/1
    (elixir 1.16.0) lib/io.ex:755: IO.each_stream/2
    (elixir 1.16.0) lib/stream.ex:1626: Stream.do_resource/5
    (elixir 1.16.0) lib/enum.ex:4399: Enum.reverse/1
    (elixir 1.16.0) lib/enum.ex:3726: Enum.to_list/1
    iex:20: (file)
```

### Expected behavior

I'm guessing the file is not valid utf8, so it is fine to raise an error, but I would expect a more descriptive error than this one.

**Comment by maennchen** [comment]
It seems like we're putting an error reason into `file:format_error/1` which is not concerning `file` but rather `unicode` when receiving an error from `io:get_line/2`.

Unfortunately, neither `io` nor `unicode` seem to provide a `format_error` function.

Should we match for `{reason, :unicode, :unicode}` in [`IO.StreamError.exception/1`](https://github.com/elixir-lang/elixir/blob/9973a2eded13afc7955de3b7ddbd87807c3006a4/lib/elixir/lib/io/stream.ex#L7) and manually generate a message?

If so, I would happily send a PR.
