### ISSUE TITLE
[Formatter] Allow / insert trailing commas in multiline lists, maps, and tuples

### ISSUE THREAD

**Issue by greg-freewave** [elixir-lang/elixir#13320]
### Elixir and Erlang/OTP versions

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

Mac

### Current behavior

Currently trailing commas on multiline lists, maps and tuples are removed when formatting.

Often when I add or rearrange my multiline lists, maps and tuples I have to read the error `error: syntax error before ...` and then look at my code, and then re-read the error, and then realize its because the formatter removes / doesn't insert trailing commas and I have forgotten one. It is tiring to have to do this over, and over, and over again and the error message is vague at best.

### Expected behavior

Trailing commas in multiline lists, maps, and tuples should not be removed, and preferably should be inserted.

**Comment by josevalim** [comment]
This has been discussed in the last, I recommend exploring the forum and mailing list for past discussions on the topic and why the functionality is not there.
