### ISSUE TITLE
Incorrect incompatible type warning on map dot access

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/elixir#13335]
### Elixir and Erlang/OTP versions

```
Elixir 1.16.1 (compiled with Erlang/OTP 26)
```

(also on main)

### Operating system

MacOS

### Current behavior

The following code:

```elixir
  defmodule Foo do
    def hello() do
      map = Map.new(words: ["world"])
      IO.inspect(map.words)
      map = %{map | words: ["hello" | map.words]}
      map.words
    end
  end
```

incorrectly shows the following warning:

```elixir
    warning: incompatible types:

        %{words: [binary() | var1]} !~ %{words: var1}

    in expression:

        # lib/foo.ex:18
        map.words

    where "map" was given the type %{words: [binary() | var1], words: var1, optional(dynamic()) => dynamic()} in:

        # lib/foo.ex:17
        map = %{map | words: ["hello" | map.words]}

    where "map" was given the type %{words: [binary() | var1], optional(dynamic()) => dynamic()} (due to calling var.field) in:

        # lib/foo.ex:18
        map.words
```

Originally reported [here](https://elixirforum.com/t/trouble-understanding-a-warning-incompatible-types/61597).

### Expected behavior

No warning

Will try to have a look tomorrow.

**Comment by michallepicki** [comment]
I think this code was removed on the main branch, as part of the work on the new set-theoretic typechecker? It may be not worth spending too much time on fixing this one

**Comment by josevalim** [comment]
Correct. Fixed in main.

**Comment by sabiwara** [comment]
Oops, I thought I reproduced it on main but I simply forgot to recompile after backporting, sorry for the noise 🙈
