### ISSUE TITLE
Fix bug in jaro_distance implementation

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#13349]
More info: https://github.com/erlang/otp/pull/7863#issuecomment-1812776125

Also benchmark to see if we should keep our version since Erlang versions also exist.

**Comment by sabiwara** [comment]
A [quick benchmark](https://github.com/sabiwara/elixir_benches/commit/604774fb4836765bd89bddd5ff1f6def82354e17) seems to indicate that the Erlang implementation performs much better on bigger strings, esp. memory wise.

Until we drop support for OTP26, should I just translate Erlang's implementation to Elixir?

**Comment by josevalim** [comment]
Sounds good to me. Our implementation should be a bit simpler than theirs too, since we only accept strings as input

**Comment by josevalim** [comment]
@sabiwara given we want to depend on the Erlang/OTP version, one option is to just copy and paste the Erlang version into the `elixir_utils` module, and then we remove it once we depend on Erlang/OTP 27+?

**Comment by sabiwara** [comment]
> @sabiwara given we want to depend on the Erlang/OTP version, one option is to just copy and paste the Erlang version into the elixir_utils module, and then we remove it once we depend on Erlang/OTP 27+?

Good idea!
