### ISSUE TITLE
`Kernel.SpecialForms` macros are not exported

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#13359]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.16.1 (compiled with Erlang/OTP 25)

### Operating system

any

### Current behavior

In iex
```
iex(1)> macro_exported?(Kernel.SpecialForms, :for, 1)
false
iex(2)> macro_exported?(Kernel.SpecialForms, :fn, 1) 
false
```
but after evaluating exports
```
iex(5)> Kernel.SpecialForms.module_info(:exports)    
[
  __info__: 1,
  "MACRO-%": 3,
  "MACRO-%{}": 2,
  "MACRO-&": 2,
...
iex(6)> macro_exported?(Kernel.SpecialForms, :for, 1)
true
```

### Expected behavior

`macro_exported?` should return true for `Kernel.SpecialForms` macros in a fresh process

**Comment by josevalim** [comment]
As `function_exported?`, you need to make sure the module is loaded before checking if it exports something.

```
iex(1)> Code.ensure_loaded Kernel.SpecialForms
{:module, Kernel.SpecialForms}
iex(2)> macro_exported?(Kernel.SpecialForms, :for, 1)
true
```

**Comment by lukaszsamson** [comment]
Shouldn't it be documented though that `Kernel.SpecialForms` is not loaded automatically? The docs only mention macros being auto imported

**Comment by josevalim** [comment]
I don't think so. You should not assume any module is loaded at any point, and it is not a guarantee we provide for any module, especially because someone can always `code:delete`/`code:purge` it.
