### ISSUE TITLE
ArithmeticError, but error doesn't occur when inspecting the variables

### ISSUE THREAD

**Issue by thmschn** [elixir-lang/elixir#13368]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

Linux (via WSL version: 2.0.9.0)

### Current behavior

Context: I was trying to solve a problem on Exercism when I came across this error. I asked on the Elixir Discord and got referred to here.

Usage: try `PascalsTriangle.rows(3)` with the following code, which generates an ArithmeticError.

Problem: This code gets an error, but when I try to inspect the variables (try uncommenting the `IO.inspect({prev_row_t, prev_row})` on line 17), I no longer seem to get an error (?). I also noticed that the error doesn't occur if I change `create_rows` to be public functions.
<br><br>

This is the error I get without the `IO.inspect`:
```
iex(1)> PascalsTriangle.rows(3)
** (ArithmeticError) bad argument in arithmetic expression: [1] + 1
    :erlang.+([1], 1)
    (pascals_triangle 0.1.0) lib/pascals_triangle.ex:22: anonymous fn/1 in PascalsTriangle.create_rows/2
    (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
    (pascals_triangle 0.1.0) lib/pascals_triangle.ex:21: PascalsTriangle.create_rows/2
    iex:1: (file)
```
<br><br>

With the `IO.inspect`, I don't get an error:
```
iex(2)> PascalsTriangle.rows(3)
{[], [1]}
{[1], [1, 1]}
[[1], [1, 1], [1, 2, 1]]
```
<br><br>

Code:
```elixir
defmodule PascalsTriangle do
  @doc """
  Calculates the rows of a pascal triangle
  with the given height
  """
  @spec rows(integer) :: [[integer]]
  def rows(num) do
    create_rows(num, [[1]])
  end

  defp create_rows(1, all_rows), do: Enum.reverse(all_rows)

  # current row = [1] ++ [left + right for the middle section] ++ [1]
  defp create_rows(num, [prev_row | _t] = all_rows) do
    [_prev_row_h | prev_row_t] = prev_row

    # IO.inspect({prev_row_t, prev_row})

    middle =
      Enum.zip(prev_row_t, prev_row)
      |> Enum.map(fn {l, r} ->
        l + r
      end)

      create_rows(num - 1, [[1] ++ middle ++ [1] | all_rows])
  end
end
```

### Expected behavior

The behavior is correct when I either include the `IO.inspect`, or change to public functions.

**Comment by josevalim** [comment]
Thank you for your report @thmschn. I have verified this is an Erlang bug and I have reported it upstream. I will close it here, as we can now track it upstream, but let me know if you have any questions.
