### ISSUE TITLE
Misleading docs about Task.Supervisor function calls. 

### ISSUE THREAD

**Issue by maikelthedev** [elixir-lang/elixir#13388]
### Elixir and Erlang/OTP versions

So basically in the docs about [Task.Supervisor](https://hexdocs.pm/elixir/Task.Supervisor.html) you have this

![image](https://github.com/elixir-lang/elixir/assets/29461493/5f1f5b3f-270f-4079-bf75-c47d30d66f24)

If they all:

> Starts a task that can be awaited on.

then what's the difference between link and nolink. I think the docs should be clearer here on what is the difference of each function. 

### Current behavior

Docs don't explain what's different. 

### Expected behavior

Clearer docs explaining the difference of each function

**Comment by josevalim** [comment]
That line will always be a short summary. Does clicking the function provide more information on what linking is?

**Comment by wojtekmach** [comment]
My understanding of the issue is explaining the difference between linking and not linking to the caller. Which I think would be out of the scope of these docs. But I wouldn't hurt to link to some documentation that explains the concepts. Perhaps https://hexdocs.pm/elixir/processes.html#links?

**Comment by maikelthedev** [comment]
> That line will always be a short summary. Does clicking the function provide more information on what linking is?

nope. "Linked to the caller" and "not linked to the caller". Sure...but what's LINKED meaning here?


> My understanding of the issue is explaining the difference between linking and not linking to the caller. 

Yes

> Which I think would be out of the scope of these docs. But it wouldn't hurt to link to some documentation that explains the concepts. Perhaps https://hexdocs.pm/elixir/processes.html#links?

Exactly. 

For example, if I go into the link with the full function I get what I just wrote above, but no mention of what linking means. As @wojtekmach said, a reference to it would be awesome. I have some handle_info stuff being triggered in a LiveView out of some task called inside a supervisor and without a full explainer of what linking or not linking is, I couldn't figure it out. 

Docs are normally very clear with this things, but here is a rabbit hole, they send you to .async, async explains again nothing about linking.

**Comment by maikelthedev** [comment]
So it is just as matter really of adding a link to what @wojtekmach supplied. Meaning this: https://hexdocs.pm/elixir/processes.html#links

**Comment by pejrich** [comment]
> > That line will always be a short summary. Does clicking the function provide more information on what linking is?
> 
> nope. "Linked to the caller" and "not linked to the caller". Sure...but what's LINKED meaning here?

[Here's an Erlang link about links](https://github.com/elixir-lang/elixir/issues/13388), and [one from the Elixir docs](https://hexdocs.pm/elixir/processes.html#links) but overall I actually think the docs are doing what they're supposed to be doing here. Documentation is not a tutorial to learn the language, but rather a reference for things which you may know of, but forget the specifics. The more basic information that's put in the docs, the less useful they become once you're comfortable with the language. Learning about linking is typically a one time thing, but referencing what arguments or options a function takes is something even after years with the language I still do on a daily basis. Obviously if you have to wade through a 101 of every topic just to find what options a function takes, it gets pretty cumbersome. I think Elixir does a stellar job at providing really helpful docs, both to those who haven't used a particular function before, _and_ to those who have used it many times but want to check up on some specifics details. But generally if documentation is missing features/functionality of that function, I agree it could be updated. But in this case fixing it as you suggest would require putting information that's really not related to this function at all. Sure, this function has a linking and non-linking version, but those are concepts used broadly in the language, and certainly each specific function that links or doesn't link can't be expected to explain what linking is. After all to explain linking you'd need to mention processes, should this particular function's docs explain how processes work? Obviously not. Think of it like a recipe. An omlet recipe is not a great place to learn about what eggs are. It's a great place to find a new way to use eggs, or to find specific measurements if you forgot them.

**Comment by josevalim** [comment]
The docs say:

> The task will still be linked to the caller, see `Task.async/3` for more information 

The mistake is that `Task.async/1` is the one with more information and it contains a whole section on linking. I will fix that and we should be good. Ty.

**Comment by maikelthedev** [comment]
Wonderful, thank you @josevalim 😁
