### ISSUE TITLE
Issue loading nif.so from release

### ISSUE THREAD

**Issue by tpitale** [elixir-lang/elixir#13401]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.15.7 (compiled with Erlang/OTP 26)

### Operating system

Ubuntu 22.04

### Current behavior

When running `start` or `start_iex` for a release of our app (will share an example app shortly), the process "hangs" or "freezes" (best description I can come up with).

If I run the project with `iex -S mix` the project loads without issue.

I've confirmed that the nif (in this case `erlkaf_nif.so`) has the same sha256sum both in the MIX_ENV=prod compiled version and the `mix release` version.

At the hanging `start_iex`, I was able to hit ctrl+c and dump the `procinfo` and it appears stuck on `erlang:load_nif` with the path of the release nif.so file.

This is as far as I've gotten on isolating the issue.

(Also, this application runs with `mix release` in OTP 24. I haven't checked OTP 25, yet)

### Expected behavior

Application starts from release, loads nif.

**Comment by tpitale** [comment]
I had originally opened an issue on erlkaf, but after discovering that it works from iex, and the `.so` file is identical before and after `mix release`, this feels like something in the way release is working.

We will keep digging.

**Comment by tpitale** [comment]
Related ticket: https://github.com/silviucpp/erlkaf/issues/70

**Comment by tpitale** [comment]
Here's the repo we tried to strip down to: https://github.com/dmccown/erlkaf_example

**Comment by josevalim** [comment]
The issue seems to be IO related, which was partly rewritten in OTP 26. Can you try OTP 26.2 latest to rule it out from already being fixed?

**Comment by tpitale** [comment]
Will do!

**Comment by josevalim** [comment]
I got it. It is not an issue in erlkaf and most likely not in Elixir. I can reproduce with only these two files in the project (and no dependency):

```
# lib/kafka.ex
defmodule ErlkafExample.Kafka do
  @on_load :foo

  def foo do
    :io.format(<<"Loading library: ~p ~n">>, ["mylib"])
    :ok
  end
end
```

```
# lib/application.ex
defmodule ErlkafExample.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application
  alias ErlkafExample.Kafka

  def start(_type, _args) do
    IO.puts("booting app")
    children = []

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: ErlkafExample.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

I deduced this based on this comment: https://github.com/silviucpp/erlkaf/issues/70#issuecomment-1986171538 - so great job spelunking.

I will try to further isolate and reproduce this with only Erlang.

**Comment by tpitale** [comment]
Now trying to debug an issue just running `mix deps.get` on erlang 26.2.3 and elixir 1.16.1. Gimme a few:

```
▶ mix deps.get
Resolving Hex dependencies...
eheap_alloc: Cannot allocate 976733209832459912 bytes of memory (of type "heap_frag").

Crash dump is being written to: erl_crash.dump...beam/erl_term.h:1492:tag_val_def() Assertion failed: tag_val_def error
[1]    36915 abort      mix deps.get
```

**Comment by tpitale** [comment]
Ah, this is known: https://github.com/erlang/otp/issues/8238

**Comment by josevalim** [comment]
@tpitale I am calling it a night. I was able to remove Elixir from the equation locally.

My recommendation is for you to create a new rebar3 project and add a single module to it:

```
-module(foo).
-on_load(foo/0).

foo() ->
  erlang:display(prev),
  io:format(<<"Loading library: ~p ~n">>, ["mylib"]),
  erlang:display(next),
  ok.
```

Now build a release and run it. If you can reproduce the issue, you will see prev written, but not the other two messages. If you can do so, can you please share the rebar3 project on GitHub? I can pick it up later and either report it upstream (or help you report it). :)

**Comment by tpitale** [comment]
I was also able to repeat it on 26.2.2. We'll start working on isolating to erlang. Thank you so much @josevalim!

**Comment by tpitale** [comment]
This might be it: https://github.com/erlang/otp/issues/7466

**Comment by josevalim** [comment]
@tpitale I don't think that's the one. I have a fix for that one and this one is showing other symptoms. In particular, the io module is already loaded in this case.

**Comment by josevalim** [comment]
@tpitale I will try it anyway with my patch from that commit and let you know later.

**Comment by josevalim** [comment]
I can confirm the issue above is not related and my fix to that issue does not fix this issue. Please keep me posted if you were able to reproduce it with rebar or not. :)

**Comment by tpitale** [comment]
Thank you! Will do. Have a good weekend!
