### ISSUE TITLE
Tags before a describe-block aren't passed to tests (unless they are tagged)

### ISSUE THREAD

**Issue by azizk** [elixir-lang/elixir#13414]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

Linux NixOS

### Current behavior

The tags of a describe-block aren't passed on to the tests, unless they are also tagged.

```elixir
@tag :general_flag
describe "with describe" do
  @tag :my_flag
  test "specific and general tag", context do
    assert context[:my_flag] == true
    assert context[:general_flag] == true
  end

  @tag general_flag: false
  test "overriding general_flag", context do
    assert context[:general_flag] == false
  end

  test "untagged", context do
    assert context[:general_flag] == true
  end
end
```

### Expected behavior

I expect the `"untaggged"` test to also receive the `:general_flag` tag from its describe block.

**Comment by josevalim** [comment]
Yes, there is a `@describetag` which applies to describe. `@tag` applies only to the next test.

**Comment by azizk** [comment]
Ah, sorry! Never came across it until now. :sweat_smile:
