### ISSUE TITLE
Formatter breaking line_length in guards

### ISSUE THREAD

**Issue by APB9785** [elixir-lang/elixir#13418]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.16.0 (compiled with Erlang/OTP 26)

### Operating system

macOS Sonoma 14.3

### Current behavior

with `line_length: 120` set in formatter options,

```elixir
def parse_transfer_data(
        %{
          "contract_address" => contract_address,
          "transaction" => transaction,
          "event_type" => event_type,
          "block_number" => block_number,
          "timestamp" => timestamp
        } = data
      )
      when is_binary(contract_address) and is_binary(transaction) and is_binary(event_type) and is_integer(block_number) and
             is_binary(timestamp) do
```
the line starting with `when` has 124 characters

### Expected behavior

Formatting the above code should move one of the checks to the next line to meet the `:line_length` configuration:
```elixir
def parse_transfer_data(
        %{
          "contract_address" => contract_address,
          "transaction" => transaction,
          "event_type" => event_type,
          "block_number" => block_number,
          "timestamp" => timestamp
        } = data
      )
      when is_binary(contract_address) and is_binary(transaction) and is_binary(event_type) and 
             is_integer(block_number) and is_binary(timestamp) do
```

Furthermore, attempting to manually move the clause results in the formatter UNDOing the change, so it goes back up to 124 characters

**Comment by APB9785** [comment]
One quick workaround is to add parenthesis to the second line:
```elixir
def parse_transfer_data(
        %{
          "contract_address" => contract_address,
          "transaction" => transaction,
          "event_type" => event_type,
          "block_number" => block_number,
          "timestamp" => timestamp
        } = data
      )
      when is_binary(contract_address) and is_binary(transaction) and is_binary(event_type) and
             (is_integer(block_number) and is_binary(timestamp)) do
```
which will prevent the formatter from undoing the change

**Comment by josevalim** [comment]
The line length is not a precise limit. It rather indicates when there should be a break and the line break happens at the next possible opportunity. Therefore, if the line break happens at ") and", the next opportunity for a break is only after the end, and you end with 4 characters over the limit. More info in the docs here: https://hexdocs.pm/elixir/Code.html#format_string!/2-line-length
