### ISSUE TITLE
Incorrect Example in Enum.slide Documentation

### ISSUE THREAD

**Issue by mkal1375** [elixir-lang/elixir#13413]
Hi there,
I noticed a discrepancy in the example provided for the Enum.slide/3 function in the Elixir documentation.

Currently, the example shows:

```elixir
fruits = ["apple", "banana", "grape", "orange", "pear"]
Enum.slide(fruits, 1..3, 4)
# => ["banana", "pear", "grape", "orange", "apple"]
```
However, when tested, the actual output differs from the expected result:

```elixir
["apple", "pear", "banana", "grape", "orange"]
```
links: [Github](https://github.com/elixir-lang/elixir/blob/41f6ee3f2e605f7066b23d96362e3b0c620c565b/lib/elixir/pages/cheatsheets/enum-cheat.cheatmd#L714), [Docs](https://arc.net/l/quote/tywjyhqj)

**Comment by josevalim** [comment]
Thank you, it will be fixed in the next release!
