### ISSUE TITLE
Compiler does not respect elixrc_paths in GitHub deps

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#13427]
### Elixir and Erlang/OTP versions

Elixir 1.16.2 (compiled with Erlang/OTP 26)
Erlang/OTP 26 [erts-14.2]

### Operating system

macOS Sonoma 14.2.1 (23C71)

### Current behavior

Compiling a github dependency does not respect the  `elixirc_paths` configuration for the dependency.

To reproduce, [clone this repository](https://github.com/elixir-cldr/elixirc_paths) then:
```elixir
mix deps.get
mix compile
iex -S mix
```
Then in iex:
```elixir
iex> Cldr.PersonName.Mixfile.project()[:elixirc_paths]
["lib", "mix"]
iex> Cldr.PersonName.Names.names()
** (UndefinedFunctionError) function Cldr.PersonName.Names.names/0 is undefined (module Cldr.PersonName.Names is not available)
    Cldr.PersonName.Names.names()
    iex:1: (file)
```
The module `Cldr.PersonName.Names` is defined in `ex_cldr_person_names` `mix` dir which is adjacent to the `lib` dir and is included in the `elixirc_paths` configuration of `ex_cldr_person_names` when `Mix.env() == :dev`.

### Expected behavior

`elixirc_paths` for a GitHub dependency is respected when compiling the dependency.

**Comment by pnezis** [comment]
Dependencies are always assumed to be in the `:prod` environment, unless you specify [the `:env` option](https://hexdocs.pm/mix/1.12.3/Mix.Tasks.Deps.html#module-dependency-definition-options). This should work:

```elixir
{:ex_cldr_person_names, github: "elixir-cldr/cldr_person_names", env: Mix.env()},
```

**Comment by kipcole9** [comment]
Thanks very much @pnezis, I should have known that. Apologies for the noise.
