### ISSUE TITLE
Binary pattern matching error in test

### ISSUE THREAD

**Issue by LVala** [elixir-lang/elixir#13420]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.16.2 (compiled with Erlang/OTP 26)

### Operating system

macOS 14.4

### Current behavior

Reproduction steps:
1. Create new project with `mix new matching_bug`.
2. To `matching_bug/test/matching_bug_test.exs` add the following test:

```elixir
test "bug" do
  a = 4
  b = <<1, 2, 3, 4>>
  assert <<^a, ^b::binary>> = <<4, 1, 2, 3, 4>>
end
```

3. Run `mix test`. The test `bug` should fail (just matching, without `assert`, fails too):

```
~/matching_bug ❱ mix test
Compiling 1 file (.ex)
Generated matching_bug app
.

  1) test bug (MatchingBugTest)
     test/matching_bug_test.exs:9
     match (=) failed
     The following variables were pinned:
       b = <<1, 2, 3, 4>>
       a = 4
     code:  assert <<^a, ^b::binary>> = <<4, 1, 2, 3, 4>>
     left:  <<^a, ^b::binary>>
     right: <<4, 1, 2, 3, 4>>
     stacktrace:
       test/matching_bug_test.exs:12: (test)

.
Finished in 0.01 seconds (0.00s async, 0.01s sync)
1 doctest, 2 tests, 1 failure
```

I'm unable to reproduce this outside of the test case (in `iex` it works as expected, for example), also it works fine with Elixir 1.15.7, but fails with Elixir 1.16.*.

### Expected behavior

The binary is matched properly.

**Comment by sabiwara** [comment]
It is weird, it gets expanded to `<<^a, ^b::binary-size(byte_size(^b))>> = <<4, 1, 2, 3, 4>>` which fails to match - which it shouldn't I believe
.
Interestingly `<<^a, ^b::binary-size(byte_size(^b))>> <> rest = <<4, 1, 2, 3, 4>>` does match, with `rest == ""`.

Also, it only manifests in modules but works in IEx.
I'm starting to suspect a bug upstream.

**Comment by sabiwara** [comment]
Reported upstream https://github.com/erlang/otp/issues/8280.
