### ISSUE TITLE
Assert again for specs in IEx shell docs for erlang

### ISSUE THREAD

**Issue by sabiwara** [elixir-lang/elixir#13438]
Once https://github.com/erlang/otp/pull/8077 is merged, we should unskip tests that have been skipped for OTP 27rc [here](https://github.com/elixir-lang/elixir/pull/13437).

See discussion in https://github.com/elixir-lang/elixir/pull/13352 for more context.

**Comment by josevalim** [comment]
Moving this to #12857 :D
