### ISSUE TITLE
Internal error in pass beam_ssa_opt when compiling phoenix_live_view (Elixir main, OTP 27.0-rc2)

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#13432]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-14.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.17.0-dev (compiled with Erlang/OTP 27)

### Operating system

Apple M1 Pro, macOS Sonoma 14.4

### Current behavior

I know that Erlang/OTP 27 is not fully supported or even out yet, but the Erlang/OTP team asked to try out the RC, so I did my best, and I got an error which might be either an incompatibility on Elixir side, or a bug in Erlang/OTP itself. I'm not yet sure how to narrow this down - I am sorry if this report belongs somewhere else.

Here's a gist with the commands I used to build Erlang, Elixir (from `main`) and the error I'm seeing:
https://gist.github.com/michallepicki/14d9d065754f5ccfebf13dab0ecc220c

### Expected behavior

no error inside the Erlang compiler

**Comment by josevalim** [comment]
Thanks for the report. This is most likely an Erlang bug, given it worked before. I will debug it and report it upstream.

**Comment by josevalim** [comment]
Reported upstream on https://github.com/erlang/otp/issues/8296. Thank you!
