### ISSUE TITLE
Confusing warning for always successful tuple match in with expression

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#13446]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [RELEASE CANDIDATE 2] [erts-14.2.3] [source-f4f3eb4c66] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.17.0-dev (compiled with Erlang/OTP 27)

(elixir at e76dc91)

### Operating system

Apple M1 Pro, macOS Sonoma 14.4.1

### Current behavior

When testing upcoming Erlang/OTP 27 from latest master branch, using Elixir main, I encountered a confusing compilation warning. I reduced it to this snippet:

```
% cat somemod.ex
defmodule SomeMod do
  def read_file(path) do
    with {:ok, contents} <- File.read(path),
         {:ok, result} <- {:ok, String.trim(contents)} do
      {:ok, result}
    end
  end
end

% elixirc somemod.ex
    warning: this clause cannot match because a previous clause at line 4 always matches
    │
  3 │     with {:ok, contents} <- File.read(path),
    │     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    │
    └─ somemod.ex:3
```

I know that the `<-` in the pattern match is incorrect, and `{:ok` tuple wrapping on line 4 is redundant. The fix is to change this line to `result = String.trim(contents) do`.

But I find the warning shown to be very confusing:
1. The snippet shows the previous line that has no problems
2. There is no redundant clause in the snippet, but only the "wrong" operator used

### Expected behavior

A less confusing warning?

**Comment by josevalim** [comment]
I think this is related to the anonymous function approached we move to in main. We generate a lambda, which will have the same line as the `with`, and when called here it is probably finding unused clauses. We should probably mark the whole lambda (or each of its clauses) as generated. Thanks for the report!

**Comment by michallepicki** [comment]
👍🏻 Thank you for the explanation! I think some better warning saying to use `=` might be helpful and could help people avoid bugs and/or simplify their code (but maybe it needs to be implemented differently and not rely on the Erlang compiler warning)

**Comment by sabiwara** [comment]
> I think this is related to the anonymous function approached we move to in main. We generate a lambda, which will have the same line as the `with`, and when called here it is probably finding unused clauses. We should probably mark the whole lambda (or each of its clauses) as generated. Thanks for the report!

I wonder if we could have a smarter warning by adding a different meta to the clause AST instead of just marking it as generated. Because at least now that we moved it to a lambda it should be accurate in its tracking of unused code. Will try to give it a shot.

**Comment by josevalim** [comment]
The warnings are emitted by Erlang, I don't think we get enough metadata up to customize it. Once we have the type system, we will be able to do more.

**Comment by sabiwara** [comment]
> The warnings are emitted by Erlang, I don't think we get enough metadata up to customize it. Once we have the type system, we will be able to do more.

You're right, we have no way to pass anything to the `{nomatch, {shadow, ...}}` to help formatting there.
Added the generated back on https://github.com/elixir-lang/elixir/pull/13454.
