### ISSUE TITLE
mix test --warnings-as-errors and --failed flags with unexpected interaction

### ISSUE THREAD

**Issue by arkanttus** [elixir-lang/elixir#13443]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 25 [erts-13.2.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.4 (compiled with Erlang/OTP 25)
```

### Operating system

Ubuntu 20.04 (but issue also occurs on CI machine with Alpine 3.14.2)

### Current behavior

If i have a file with warnings and other file with wrong assert and i run `mix test --warnings-as-errors || mix test --warnings-as-errors --failed`, the second run (with --failed flag) will ignore the files with warning and re-run only the failed file tests, resulting in a failed success. The exit status will be 2, because of the failed test, overlapping the warning exit status 1

### Expected behavior

If there is any warning, the exit status should be 1 even if there is some failed test. In this case, we can use the correct exit status to execute `--failed` or not.
Other alternative is: not run tests when any warning is detected. Currently, the tests are executed even if exists warnings, overlapping the exit status.

**Comment by josevalim** [comment]
The --warnings-as-errors is unrelated to the failed suite test. It is not effectively part of the test runner. I will update the docs accordingly.

**Comment by josevalim** [comment]
Thank you @arkanttus for the report! :heart:

> If there is any warning, the exit status should be 1 even if there is some failed test.

Currently, the failed status takes precedence over the warning as errors. I can't come up with a strong argument for one over the other but, without a strong reason to change it, we probably shouldn't, as some could consider it backwards incompatible.

> Other alternative is: not run tests when any warning is detected. Currently, the tests are executed even if exists warnings, overlapping the exit status.

I think we should provide as much feedback as we can by default. We could have a flag to fail fast here, but that would be an addition.

One alternative

**Comment by josevalim** [comment]
Oh, you can emulate the behaviour you requested with this:

    mix test --only none --warnings-as-errors

If it passes, it is because there are no warnings. The downside is that you would have to load the test suite twice but it should be good enough for now. Especially because I don't want to necessarily encourage `mix test --warnings-as-errors || mix test --warnings-as-errors --failed` on CIs.
