### ISSUE TITLE
capture_log prints logs to stdout if Logger.Backends.Console is used

### ISSUE THREAD

**Issue by fuelen** [elixir-lang/elixir#13441]
### Elixir and Erlang/OTP versions

Elixir 1.16.2
OTP: 26.2.3

### Operating system

Linux

### Current behavior

* create a new project
* add this line to `config/config.exs`:
```elixir
config :logger, :backends, [Logger.Backends.Console]
```
* add test:
```elixir
defmodule LogIssueTest do
  use ExUnit.Case
  require Logger

  @tag :capture_log
  test "test" do
    Logger.error("Hi")
  end
end
```
* run `mix test`

The last command prints `[error] Hi` to stdout.

### Expected behavior

Don't print anything to stdout if backends are used

**Comment by josevalim** [comment]
Correct. `capture_log` has always replaced the default backend and Logger.Backends.Console is no longer the default one, therefore it is not removed. You can remove it from your environment and all should be good!

**Comment by josevalim** [comment]
Yes, there is no plan. You should set it only if necessary. Prefer the new default handler whenever possible. I will update v1.16 changelog notes to mention this could be a point of concern during migration.
