### ISSUE TITLE
System.cmd hangs on Windows when child process hasn't exited after port gets EOF

### ISSUE THREAD

**Issue by yastanotheruser** [elixir-lang/elixir#13449]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.17.0-dev (e76dc91) (compiled with Erlang/OTP 26)

### Operating system

Windows 11

### Current behavior

Running an Elixir application on Cygwin from the Mix CLI hangs on my machine due to System.cmd never returning when executing some Git commands, it turns out Cygwin programs keep running after the opened port gets EOF, which causes System.cmd to never get the `exit_status` message from the port. This is explained in the `open_port` BIF documentation:

> If the port program closes its stdout without exiting, option exit_status does not work.

---

Reproduce: (Cygwin)

```elixir
iex> System.cmd("git", ["--version"])
```

---

Reproduce: (MinGW example program)

alive_after_eof.c

```c
#include <stdio.h>
#include <synchapi.h>

int main(void)
{
        puts("sleep 1 sec...");
        fclose(stdout);
        Sleep(1000);
        return 0;
}
```

```console
$ gcc alive_after_eof.c -o alive_after_eof.exe
$ iex
```

```elixir
iex> System.cmd("alive_after_eof.exe", [])
```

Related: https://github.com/erlang/otp/issues/8317

### Expected behavior

System.cmd shouldn't hang.

**Comment by josevalim** [comment]
Thank you for the report @yastanotheruser! Given this is an Erlang/OTP behaviour, we will track it upstream. :)
