### ISSUE TITLE
Crash dump then Hex ArgumentError while doing Mix.install

### ISSUE THREAD

**Issue by thbar** [elixir-lang/elixir#13456]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.16.2 (compiled with Erlang/OTP 26)
```

Full version of Erlang is 26.2.3 (installed via `asdf`).

### Operating system

macOS Sonoma 14.4 (⚠️ Mac M1 / Silicon)

### Current behavior

I only attempted this via `asdf` for now.

In `.tool-versions`, put:

```
erlang 26.2.3
elixir 1.16.2-otp-26
```

Then `asdf install`

I created a script with just:

```elixir
Mix.install([
  {:req, "~> 0.4.14"}
])
```

Running it with `elixir myscript.exs` once give:

```
* creating /Users/thbar/.asdf/installs/elixir/1.16.2-otp-26/.mix/archives/hex-2.0.6
Resolving Hex dependencies...
eheap_alloc: Cannot allocate 976733209832459912 bytes of memory (of type "heap_frag").

Crash dump is being written to: erl_crash.dump...beam/erl_term.h:1492:tag_val_def() Assertion failed: tag_val_def error
zsh: abort      elixir all.exs
```

Running it another time gives:

```
Resolving Hex dependencies...
** (ArgumentError) argument error
    (stdlib 5.2.1) io.erl:103: :io.put_chars(:standard_io, [[[], 488366604916229862], 10])
    (hex 2.0.6) lib/hex/remote_converger.ex:127: Hex.RemoteConverger.run_solver/5
    (mix 1.16.2) lib/mix/dep/converger.ex:133: Mix.Dep.Converger.all/4
    (mix 1.16.2) lib/mix/dep/converger.ex:89: Mix.Dep.Converger.converge/4
    (mix 1.16.2) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
    (mix 1.16.2) lib/mix/tasks/deps.get.ex:34: Mix.Tasks.Deps.Get.run/1
    (mix 1.16.2) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.2) lib/mix.ex:925: anonymous fn/5 in Mix.install/2
```

Switching `.tool-versions` back to:

```
erlang 25.3.2.10
elixir 1.16.2-otp-25
```

works as expected.

At this point I have no idea if this is caused by the Mac M1 system, potentially by the `asdf` installation itself, or both, or something else!

### Expected behavior

The script should just work.

**Comment by thbar** [comment]
I have retried both installations multiple times, but the behaviour remains. I will try other tests.

**Comment by josevalim** [comment]
Reported here: https://github.com/erlang/otp/issues/8238#issuecomment-1987173291

There is a fix but not a new release. Either use a previous Erlang/OTP version or reinstall Hex. :)

**Comment by thbar** [comment]
Thank you @josevalim!
