### ISSUE TITLE
Regression: different code paths in mix compilers since 1.15

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#13458]
### Elixir and Erlang/OTP versions

This issue is about difference between versions `<= 1.14` and versions `>= 1.15`

### Current behavior

Mix tasks from dependencies return different results in `1.14` and `1.15`. And it is not just different, but there is extremely important difference that in 1.14 the current app code path is present, but in 1.15 it is not

Reproduction: https://github.com/hissssst/elixir-compiler-regression

### Expected behavior

Consistent decidion whether the app which is compiled has it's own code path in `:code.get_path` or not

**Comment by josevalim** [comment]
Thanks for the report, I will look into it.
