### ISSUE TITLE
Regression: ExUnit macro on the left side since 1.14

### ISSUE THREAD

**Issue by hissssst** [elixir-lang/elixir#13453]
### Elixir and Erlang/OTP versions

It first appeared in 1.15.0 and is still present in 1.16

### Current behavior

With this code:

```elixir
defmodule Xxx do
  defmacro m(x) do
    IO.inspect x
    123
  end
end
```

And in test
```elixir
defmodule XxxTest do
  use ExUnit.Case
  import Xxx

  test "" do
    assert m(Kernel.+(1, 2)) = 123
  end
end
```

Output in 1.14
```elixir
$ mix test
Compiling 1 file (.ex)
Generated xxx app
{{:., [line: 6], [{:__aliases__, [line: 6], [:Kernel]}, :+]}, [line: 6], [1, 2]}
{{:., [line: 6], [Kernel, :+]}, [line: 6], [1, 2]}
.
Finished in 0.01 seconds (0.00s async, 0.01s sync)
1 test, 0 failures
```

Output in 1.15 and 1.16
```elixir
$ mix test
Compiling 1 file (.ex)
Generated xxx app
{{:., [line: 6], [{:__aliases__, [line: 6], [:Kernel]}, :+]}, [line: 6], [1, 2]}
.
Finished in 0.00 seconds (0.00s async, 0.00s sync)
1 test, 0 failures
```

As you can see, in 1.14 macro is called two times and `{{:., [line: 6], [Kernel, :+]}, [line: 6], [1, 2]}` appears on the left side (if we remove return 123 from macro), while in 1.15 and 1.16 `{{:., [line: 6], [{:__aliases__, [line: 6], [:Kernel]}, :+]}, [line: 6], [1, 2]}` display

### Expected behavior

Backport correct behaviour to 1.14 or change it in 1.16. I wrote a lot of code with assumption that behaviour in 1.14 is the correct one, so I'd like some strict resolution here

**Comment by hissssst** [comment]
Real world example: https://github.com/hissssst/tria/actions/runs/8486868978/job/23253928558#step:8:99

**Comment by josevalim** [comment]
The behaviour in v1.16 is correct. We should avoid expanding the macros twice (and, in this case, with different/expanded arguments). There are no plans to backport the behaviour to v1.14, as it is a bug fix, but not one significant enough to justify a new release.
