### ISSUE TITLE
Allow optional depedencies to be included with `runtime: false` and `:load` in releases?

### ISSUE THREAD

**Issue by mayel** [elixir-lang/elixir#13460]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]
Elixir 1.16.2 (compiled with Erlang/OTP 26)

### Operating system

OSX and Ubuntu

### Current behavior

I have an app `my_app` with dependencies such as `a_required_library` which in turn has optional dependencies such as `an_optional_library`. 
Those optional libraries are included as dependencies of the top-level `:my_app` with `runtime: false` which meant they weren't included in the release, so I added them to `:load` in `mix.exs` (this is so they're available but not enabled by default, as part of a plugin system where users can enable optional features):

```
def project do 
 [releases: [
        my_app: [
          applications: [
            my_app: :permanent,
            an_optional_library: :load
          ] 
        ]
      ]
...
```

But this results in the following error, which seems odd given that `:an_optional_library` is an *optional* dependency of ` :my_other_app`:

```
** (Mix) Application :my_other_app has mode :permanent but it depends on :an_optional_library which is set to :load. If you really want to set such mode for :an_optional_library make sure that all applications that depend on it are also set to :load or :none, otherwise your release will fail to boot
```

### Expected behavior

My question then, is this expected/correct behaviour and I should be using a different approach (like maybe not setting `runtime: false` on the optional libs) or should this error only be triggered for non-optional dependencies?

**Comment by josevalim** [comment]
Can you please provide a minimal app that reproduces the error? It may be something that we can address but it will be easier for me to confirm if I can run into the exact same scenario as you. :)

**Comment by mayel** [comment]
Sure thing, I'll set one up :)

**Comment by mayel** [comment]
@josevalim here you go https://github.com/mayel/optional_dep_repro

**Comment by mayel** [comment]
It seems like adding `runtime :false` for `:an_optional_library` also in the `mix.exs` of `:a_required_library` works, though I'm not sure that's a valid workaround as in some cases the top level app may want to include it with `runtime: true` but I guess it could just set `override: true` as well...

**Comment by josevalim** [comment]
Unfortunately I believe Mix is correct here.

When `a_required_library` depends on `an_optional_library`, and `an_optional_library` is available, `a_required_library` will most likely be compiled with the assumption `an_optional_library` is up and running. If `an_optional_library` is not running, then `a_required_library` may not work as expected.

If `an_optional_library` is optional and also not needed at runtime, then it should list both `optional: true, runtime: false`, then Mix will be happy. 

In any case, thanks for the repro, it helped a lot!
