### ISSUE TITLE
Further improvements to Calendar/Duration

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#13467]
It is not yet decided we will accept those, but they are discussion points:

  * [x] A range-like data type that allows us to do recurring constructs on any calendar data type. For example, `Calendar.interval(start, Duration.new(day: 13))`, when iterated, would emit date (if we support a :count option, it can replace `Date.Range`). We should only implement this if we can make it as efficient as Date.Range.
  * [x] Make it so `add` and `shift` can share more code between them
  * [x] `Kernel.to_timeout/1` that accepts integers, duration pairs (hour: ..., etc but not month), durations (but not month) or `:infinity` and return an integer in milliseconds

/cc @tfiedlerdejanze

**Comment by davydog187** [comment]
To add some inspiration to the conversation:

The library [Cocktail](https://github.com/peek-travel/cocktail) has great support for describing recurring calendar recurrences via iCalendar notation, it is quite expressive.

I have a library for using  Postgres range types called [EctoRange](https://github.com/davydog187/ecto_range) that admittedly falls a bit short because of the lack of robust calendar ranges.

**Comment by josevalim** [comment]
@davydog187 that's a very nice reference. I think it helps illustrate problems that we should not solve, as they become quite more complex. But perhaps, we shouldn't introduce Calendar.interval at all, as that's just a Stream.iterate/2 operation away anyway?

**Comment by davydog187** [comment]
Unless Elixir is going to get more declarative means of expressing recurrences and ranges, I think its better to push people towards libraries like Cocktail that already have extremely robust recurrence definitions, or use Stream.iterate/2 as you mentioned.

I should note that it would be interesting if Elixir could support a way to express timestamps as ranges, where a step could be defined in us, ms, secs, etc aligning with the semantics of [tsrange](https://www.postgresql.org/docs/current/rangetypes.html)

**Comment by josevalim** [comment]
@davydog187 we could definitely implements a `tsrange`, as it would map to NaiveDateTime, but I don't think it would be useful, except to specify start and ending for use in conditionals. That's because a full range between two timestamps would enumerate all microseconds between these timestamps (or at best every second).

Date ranges don't have this issue because the smallest unit (dates) are still useful.

And intervals are a whole separate beast, as they may not have a specific beginning and ending. In any case, the message is clear: I will write some docs about shifting and intervals to Duration and close this.

Thank you all for the wonderful input.

**Comment by josevalim** [comment]
Last item closed in favor of #13486.
