### ISSUE TITLE
Significance of order of iex flags 

### ISSUE THREAD

**Issue by gmile** [elixir-lang/elixir#13482]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit] [dtrace]

Elixir 1.16.2 (compiled with Erlang/OTP 26)

### Operating system

macOS 14.1 (23B2073)

### Current behavior

Attempting to start `iex` with `--dbg pry` as a first argument fails with a message:
```sh
iex --dbg pry --sname dev-app --cookie dev-cookie -S mix help
# No file named --sname
```

### Expected behavior

If `--dbg pry` is placed right before `-S`, then it works as expected:

```sh
iex --sname dev-app --cookie dev-cookie --dbg pry -S mix help
# print `mix help` on the screen, then enter iex shell
```

**Comment by josevalim** [comment]
Definitely a bug, we will investigate.
