### ISSUE TITLE
MapSet.to_list/1 fails with certain integers

### ISSUE THREAD

**Issue by distefam** [elixir-lang/elixir#13484]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.3] [source] [64-bit] [smp:32:24] [ds:32:24:10] [async-threads:1] [jit:ns]

Elixir 1.16.2 (compiled with Erlang/OTP 26)

### Operating system

Linux (Fedora 39)

### Current behavior

```elixir
MapSet.new([11]) |> MapSet.to_list()
  ~c"\v"

MapSet.new([11, 12]) |> MapSet.to_list()
  ~c"\v\f"

MapSet.new([11, 12, 13]) |> MapSet.to_list()
  ~c"\v\f\r"

MapSet.new([11, 12, 13, 14]) |> MapSet.to_list()
  [11, 12, 13, 14]
```

### Expected behavior

```elixir
MapSet.new([11]) |> MapSet.to_list()
  [11]

MapSet.new([11, 12]) |> MapSet.to_list()
  [11, 12]

MapSet.new([11, 12, 13]) |> MapSet.to_list()
  [11, 12, 13]

MapSet.new([11, 12, 13, 14]) |> MapSet.to_list()
  [11, 12, 13, 14]
```

**Comment by ericmj** [comment]
This is how integer lists are sometimes printed as it's how we also represent lists of characters "charlists". See https://hexdocs.pm/elixir/List.html#module-charlists.

**Comment by distefam** [comment]
Oh, I didn't realize that was a behavior of Lists with certain items. Thank you for the clarification.
