### ISSUE TITLE
IO.puts failing on `File.open!("", [:ram, :write])`

### ISSUE THREAD

**Issue by dominicletz** [elixir-lang/elixir#13492]
### Elixir and Erlang/OTP versions

Elixir 1.16.2 (compiled with Erlang/OTP 26)

```.tool-versions
elixir 1.16.2
erlang 26.2.3
```

### Operating system

Linux / Any

### Current behavior

```elixir
iex(7)> fp = File.open!("", [:ram, :write])
{:file_descriptor, :ram_file, #Port<0.7>}
iex(8)> :file.write(fp, "lol")
:ok
iex(9)> IO.puts(fp, "lol")
** (FunctionClauseError) no function clause matching in IO.puts/2    
    
    The following arguments were given to IO.puts/2:
    
        # 1
        {:file_descriptor, :ram_file, #Port<0.7>}
    
        # 2
        "lol"
    
    Attempted function clauses (showing 1 out of 1):
    
        def puts(device, item) when is_atom(device) or is_pid(device)
    
    (elixir 1.16.2) lib/io.ex:295: IO.puts/2
    iex:9: (file)
iex(9)> 
```

### Expected behavior

```elixir
iex(7)> fp = File.open!("", [:ram, :write])
{:file_descriptor, :ram_file, #Port<0.7>}
iex(8)> :file.write(fp, "lol")
:ok
iex(9)> IO.puts(fp, "lol")
:ok
iex(10)>

**Comment by wojtekmach** [comment]
FWIW, and sorry if stating the obvious, if you want to use IO functions without writing to disk you can use StringIO:

```elixir
iex> {:ok, f} = StringIO.open("")


iex> :file.write(f, "foo")
# or more commonly:
iex> IO.puts(f, "bar")

iex> StringIO.flush(f)
"foobar\n"
```

**Comment by josevalim** [comment]
When you use `:ram`, the File API no longer returns an IO device but a file descriptor, and therefore you can no longer use the IO module.

**Comment by dominicletz** [comment]
I think the documentation update is a great way to clarify this behavior. I could also see not accepting/deprecating the `:ram` option in `File.open` that would make it even more consistent. - if anyone wants to use `:ram` files they can still use `:file` directly. And StringIO as @wojtekmach says covers the use case in Elixir land.

**Comment by sabiwara** [comment]
>   [requires using the functions in the :file module](https://github.com/elixir-lang/elixir/commit/7f0f970eb23dce32a485dd4eafae2aa98dba82cf#diff-91e651cd87b6c1974b5f642b629a9f1894e300a2fc15056abf3b5df5f57961eeR1473)

I was looking at the [tests](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/test/elixir/file_test.exs#L1611) and `requires` might be a bit too strong since `File.copy` works for instance?
