### ISSUE TITLE
The " map.field notation (without parentheses)" warning doesn't seem to to create an error with --warnings-as-errors

### ISSUE THREAD

**Issue by PragTob** [elixir-lang/elixir#13491]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit:ns]

Elixir 1.17.0-dev (dc6fa24) (compiled with Erlang/OTP 26)

### Operating system

Linux Mint 21.2 (Ubuntu 22.04 base)

### Current behavior

Hell there wonderful elixir team, and as always thanks for your amazing work! :green_heart: :purple_heart: 

The warning "warning: using map.field notation (without parentheses) to invoke function Benchee.Conversion.Count.base_unit() is deprecated, you must add parentheses instead: remote.function()" doesn't lead `mix test --warnings-as-errors` to return an error code. I have a slight suspicion because it feels like a compile error and originates from a non test file, but it doesn't appear during compilation.

From the docs:
```
This option only applies to test files. To treat warnings as errors during
    compilation and during tests, run:
```

To try it out you can take the branch of this MR on benchee: https://github.com/bencheeorg/benchee/pull/429 (or just main without the fix, e.g.: https://github.com/bencheeorg/benchee/commit/a936fdb00d7dbd394ed490662dc73a8942d66f87

The behavior:

```
tobi@qiqi:~/github/benchee(test-against-elixir-main)$ mix test --warnings-as-errors test/benchee/conversion/count_test.exs && echo "wohoooo"
Excluding tags: [needs_fast_function_repetition: true]

.........................warning: using map.field notation (without parentheses) to invoke function Benchee.Conversion.Count.base_unit() is deprecated, you must add parentheses instead: remote.function()
  (benchee 1.3.0) lib/benchee/conversion/scale.ex:178: Benchee.Conversion.Scale.do_best_unit/3
  test/benchee/conversion/count_test.exs:132: Benchee.Conversion.CountTest."test .best when list is mostly thousands, strategy: :none"/1
  (ex_unit 1.17.0-dev) lib/ex_unit/runner.ex:485: ExUnit.Runner.exec_test/2
  (stdlib 5.2) timer.erl:270: :timer.tc/2
  (ex_unit 1.17.0-dev) lib/ex_unit/runner.ex:407: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4

.......................
Finished in 0.05 seconds (0.05s async, 0.00s sync)
21 doctests, 27 tests, 0 failures

Randomized with seed 417204
wohoooo
tobi@qiqi:~/github/benchee(test-against-elixir-main)$ mix compile --force --warnings-as-errors
Compiling 46 files (.ex)
Generated benchee app
```

I tested, and normal warnings (like unused variable) correctly produce error exit codes

For reference, the offending code is: `module.base_unit` which should be `module.base_unit()`

### Expected behavior

I'd expect the warning to be treated as an error and so stopping my CI at either compilation (where right now it isn't reported, probably as it's too dynamic) or test run time, so that I can catch this warning automatically in my CI :grin:

**Comment by josevalim** [comment]
It is the opposite. These warnings happen at runtime, not during compilation, and --warnings-as-errors is a compilation option. No runtime warning will affect it. :) I will clarify the docs for them.

**Comment by PragTob** [comment]
@josevalim alright, thank you! So, there is no way to get your test failing on run time warnings? Is that a feature that may be desired?

**Comment by josevalim** [comment]
@PragTob it is _complicated_. In order to collect those, we need to report and store them somewhere, and that will come at the cost of making runtime warnings more expensive, which we should be careful because it can affect actual systems.

**Comment by PragTob** [comment]
@josevalim makes sense, thank you! For my understanding, at its simplest couldn't it be stored as merely a boolean flag (as we don't want to report on them, just know that any happened) and to further alleviate concerns the "memory" of warnings could be conditional and only optionally enabled during test runs? I'm probably looking at this too simplistically though, without any knowledge of how the entire system works :sweat_smile: That may also be all a bit too much work to make it work, although I gotta say I'd love it if my test suites failed on an `IO.warn` or similar - but I may be very peculiar here.

**Comment by josevalim** [comment]
Yes, those things could be used to alleviate the concerns. :) I don't think it is too much work, I was mostly stating why it doesn't already work. I am unsure how applicable it would be in practice, because you can also have runtime warnings from dependencies at runtime and you may not want to fail because of that (and during compilation we also separate those).

**Comment by PragTob** [comment]
Yeah I was thinking about the dependencies vs. own code separation as well. It'd definitely change the behavior people are used to if they also produced a warning. That said, I figured (for myself) that I'd rather get a failure for those warnings. My reasoning is that compile time warnings in dependencies are usually "the dependency is using elixir wrong" (exaggerated) but runtime warnings originating from dependencies are mostly "you are using this dependency wrong". That said, as with the example here, it might still be the former - as benchee was doing something "wrong" (the dependency using elixir "wrong"). But well if then we'd need to filter these by dependencies/not dependencies again. 

And frankly all concerns and eventualities considered, if this is the first I truly stumble on this I wonder how applicable it is generally. Probably more impactful work to be done :sweat_smile:
