### ISSUE TITLE
 File.Stat struct declares atime, ctime, and mtime as type :calendar.datetime() or integer but they can also be :undefined

### ISSUE THREAD

**Issue by Krapaince** [elixir-lang/elixir#13497]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 23 [erts-11.2.2.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.11.4 (compiled with Erlang/OTP 21)
```

### Operating system

Linux  - Kernel 6.7.9

### Current behavior

When using the `File.Stat.t()` from a record returned by  `:ssh_sftp:read_file_info/3`  with `File.Stat.from_record/1`, fields `atime`, `ctime` and `mtime` may be `:undefined`.

For instance with `channel_pid` returned by calling `:ssh_sftp.start_channel/3`
```
iex [0] > channel_pid
#PID<0.335.0> 
iex [1] > :ssh_sftp.read_file_info(channel_pid, "/home/dummy/test.file")
{:ok,
 {:file_info, 0, :regular, :read_write, {{2024, 4, 16}, {16, 35, 26}},
  {{2024, 4, 16}, {16, 35, 26}}, :undefined, 33188, 1, 0, 0, 0, 3002, 10149}}
iex [2] > File.Stat.from_record(record)
%File.Stat{
  access: :read_write,
  atime: {{2024, 4, 16}, {16, 35, 26}},
  ctime: :undefined,
  gid: 10149,
  inode: 0,
  links: 1,
  major_device: 0,
  minor_device: 0,
  mode: 33188,
  mtime: {{2024, 4, 16}, {16, 35, 26}},
  size: 0,
  type: :regular,
  uid: 3002
}
```
The type declaration on `File.Stat` defines these as `:calendar.datetime()` or `:integer` (since #8838)  which is causing Dialyzer to yield warning when matching against `:undefined`

### Expected behavior

I don't know if this is an intended behaviour to separate the Erlang `:file:file_info` from Elixir `File.Stat.t`. 

However as `File.Stat.from_record/1` exists I supposed the time fields lack the `:undefined` in their union and as with #8838 the `:undefined` value should be added to time fields unions.

**Comment by josevalim** [comment]
We should definitely mirror file_info. If we are not mirroring them, a PR is welcome.

**Comment by sabiwara** [comment]
Indeed it seems we should: https://erlang.org/documentation/doc-15.0-rc2/lib/kernel-9.3/doc/html/file.html#t:file_info/0
`:undefined` seems to have been introduced [here](https://github.com/erlang/otp/commit/3224c9b0b7022ccf2483af95f4efd8a6b6234f47).

**Comment by josevalim** [comment]
I wonder if we should normalize them to nil then?

**Comment by sabiwara** [comment]
> I wonder if we should normalize them to nil then?

I like the idea but wouldn’t it be a breaking change?

**Comment by josevalim** [comment]
You are right. :(
