### ISSUE TITLE
Should `Supervisor.child_spec/2` protect against infinite loops?

### ISSUE THREAD

**Issue by thoughtarray** [elixir-lang/elixir#13500]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.16.2 (compiled with Erlang/OTP 26)

### Operating system

macOS 12.7.4

### Current behavior

While going through the book "Elixir in Action 3rd edition" chapter 9.1 "Supervision trees", I accidentally caused an infinite loop. Took me a while to figure out what was going on. Here's an abridged version that should be reproducible in IEX:
```elixir
defmodule Foo do
  def child_spec(_) do
    Supervisor.child_spec(__MODULE__, id: __MODULE__)
  end
end

Foo.child_spec([])
```

The seasoned reader will spot this as an obvious infinite loop, but the learner may not. Maybe we could have a handy error in cases like this?

I think there are possibly more places in Elixir that infinite loops like this are possible, but this is the first one I've accidentally caused.

### Expected behavior

To be clear, this might not quality as a footgun. If we are interested in protecting people from this class of error, maybe we could have messaging around it. Don't know the best wording, but this is the first thing I thought of:
```
** (UnintendedRecursionError) bad argument in child_spec expression: first argument results in a call to itself
```

I guess we would need to know if `Supervisor.child_spec/2` is being called from a module function called `child_spec/1`. Don't know whether or not we have that kind of reflective capability in Elixir.

**Comment by josevalim** [comment]
There is no cheap way to detect who called a function, so I am afraid there isn’t much we can do here.

**Comment by thoughtarray** [comment]
Ah dang, okay.
