### ISSUE TITLE
Always create `mix.lock` (even if empty)

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#13506]
### Elixir and Erlang/OTP versions

Erlang/OTP 25 [erts-13.2.2.7] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.16.2 (compiled with Erlang/OTP 25)

### Operating system

macOS 14.4.1

### Current behavior

When Mix dependencies are set to empty list, then there will be no `mix.lock` file created.

### Expected behavior

`mix.lock` should be created always, even if it would be just empty file.

---

Reason for that behaviour is that the only sensible way to automatically detect root of the project is to find `mix.lock` file in the list of parents. It is how NeoVim is detecting root of the project when trying to run language servers. We cannot just look for `mix.exs` as it will not work in case of umbrellas, so the only possible way is to look for `mix.lock`. But as `mix.lock` is not created when there are no installable deps, one need to create that file manually to make LS run.

**Comment by josevalim** [comment]
This looks backwards to me. We are forcing a mix.lock to solve a problem unrelated to the lock. We should discuss other options. For example, you could look if the parent directory of the mix.exs is "apps" and then if the parent also has a "mix.exs" file.

**Comment by josevalim** [comment]
Have you discussed alternative solutions with the NeoVim folks?

**Comment by hauleth** [comment]
@josevalim I could, but what would be the alternative? I could fix that myself if I would have an idea how to detect root of the project.

> For example, you could look if the parent directory of the mix.exs is "apps" and then if the parent also has a "mix.exs" file.

That feels very fragile, especially in case of non-standard layouts.

---

A lot of tooling forces creation of empty lock files. For sure:

- Rebar3
- NPM
- Bun
- Cargo
- Yarn
- Bundler

These ones that I have tested so far.

From package managers that do not generate empty lock files (from my testing):

- Nix Flakes

Technically Zig do not generate lock file, but `build.zig.zon` *is* a lock file alongside of being packages definition file, so it fits into neither of the categories.

So I would say that Elixir is outlier there with the fact that it skips generation of lock file for empty deps.

**Comment by josevalim** [comment]
> That feels very fragile, especially in case of non-standard layouts.

I assume they also allow configuration of the project root in non-standard cases?

Because otherwise I could use the same argument to say mix.lock is fragile, since it can be configured in the same way as the umbrella apps folder can (the whole reason your propose mix.lock heuristic works is because it is *configurable* but defined by *convention*).

**Comment by hauleth** [comment]
Yeah, but heuristic for "search `mix.exs` in parent" forces me to *always* traverse whole parent list. There is no way to decide whether it is possible to stop earlier.

> since it can be configured in the same way as the umbrella apps folder can

Yeah, but convention is that `mix.lock` will be placed in root of the project, while there is no such convention for `mix.exs` or `apps`.

In general I find generating lock file, even empty, a useful default, and from the list above it seems that a lot of other projects think the same way. It also can help with differencing between project where `mix deps.get` was not ran at all, and project where it was ran at least once which I believe can be helpful for some automation tools. For example imagine project that uses Make for automation of some stuff. They want to automate dependency fetching in the task, to make it easier for their engineers. One can write:

```makefile
mix.lock: mix.exs
	mix deps.get

intall-deps: mix.lock

build: install-deps
	# build project
```

And that setup will automatically run `mix deps.get` each time `mix.exs` was updated.

Obviously that is not what most Elixir developers do, but in some cases, it may be beneficial for the non-Elixir developers that need to interact with Elixir projects (ex. Ops or FE).

I think that empty lock file is more valuable than lack of such in case of empty dependency list. @tsloughter said that they generate empty file in Rebar3 just of laziness, but I think that it is laziness that is justified and beneficial for the external tooling.

**Comment by josevalim** [comment]
> Yeah, but convention is that mix.lock will be placed in root of the project, while there is no such convention for mix.exs or apps.

apps is more than a convention, it is hardcoded as part of umbrellas and you need to opt-out of it, different than mix.lock that requires opt-in. So I disagree with:

> Yeah, but heuristic for "search mix.exs in parent" forces me to always traverse whole parent list.

You only need to go one level app and see if it is a directory called "apps". If it is, see if it has a mix.exs. If any of those are false, you can stop traversing without ever traversing the whole list.

Given this is enough, I will close this issue for now, thank you.
