### ISSUE TITLE
string_length for Thai sara Am incorrect

### ISSUE THREAD

**Issue by pepa65** [elixir-lang/elixir#13515]
### Elixir and Erlang/OTP versions

Elixir 1.12.2 (compiled with Erlang/OTP 24)

I was very impressed that the output of `string_length("ผู้")` (1 grapheme, 3 unicode points) is `1`! But when I tried `string_length("ผู้นำ")` the value `2` was returned, and as you can see, there are 3 graphemes here... I suspect that somehow the unicode point `ำ` is wrongly assigned as zero-length code-point. The little circle is indeed supposed to be rendered on top of the previous consonant, but the hook is its own grapheme, and obviously needs to be counted as one.

### Operating system

Linux Mint 21.3

### Current behavior

input: `string_length("ผู้นำ")`
output: `2`

### Expected behavior

input: `string_length("ผู้นำ")`
output: `3`

**Comment by kipcole9** [comment]
According to the [Unicode TR29 specification](https://unicode.org/reports/tr29/#GB9a), there is no grapheme break for a grapheme cluster spacing mark, and [Sara Am is a spacing mark](https://codepoints.net/U+0E33). 

I believe therefore that Elixir is exhibiting the right behaviour as defined by Unicode.

There is clearly a Sara Am [glyph](https://www.unicode.org/glossary/#glyph), but its not a separate [grapheme](https://www.unicode.org/glossary/#grapheme).

**Comment by pepa65** [comment]
That would be incredibly bad if Unicode itself got this wrong. If you type in the terminal, it is clear that `นำ` takes up 2 positions, as does `นา`, with the only difference that the first one paints a little circle about the first grapheme. Indeed, `String.length("นา")` gives `2`, as should `String.length("นำ")`, this is obvious to anyone, even if they don't read Thai.

Do you happen to know of any standardized tool that this mistake can be demonstrated with (outside of Elixir)? I don't know any language that can give the grapheme length of unicode strings (correctly), and I don't know of any unix tool that does either.

**Comment by kipcole9** [comment]
I believe Elixir is correct, where correctness is defined by the Unicode standard. In my Mac terminal (tried both standard Mac terminal and iTerm2) the cursor agrees with the standard - it moves by two glyphs with one cursor movement.

The reason that `String.length("นา") == 2` while `String.length("นำ") == 1` is that the "unaccented" code point has the property `grapheme_cluster_break=other`, not `spacing_mark`. For example:
```elixir
iex> Unicode.GraphemeClusterBreak.grapheme_break("า")
[:other]
iex> Unicode.GraphemeClusterBreak.grapheme_break("ำ")
[:spacingmark]
```

Unicode solves a lot of problems in expressing language in a standard manner, but it is still challenging because human language is challenging. I think is a case where glyphs and grapheme clusters commonly cause issues. I'm not a linguist nor a Thai speaker so I cannot speak to the cultural implications of the decisions Unicode makes.  Nevertheless, by the standard Elixir is correct.

> EDIT: the terminal obviously knows how to render both of these correctly, using 2 positions.

Then I suspect the terminal you are using is not Unicode compliant (the two on my Mac appear to be compliant in their cursor handling).

> Do you happen to know of any standardized tool that this mistake can be demonstrated with (outside of Elixir)? I don't know any language that can give the grapheme length of unicode strings (correctly), and I don't know of any unix tool that does either.

This would be something you would need to take up with Unicode I think. I expect they may say that this is an example where glyphs and grapheme clusters show their differences.

**Comment by kipcole9** [comment]
The [Unicode Text Segmentation specification](https://unicode.org/reports/tr29/#Grapheme_Cluster_Boundaries) seems to draw attention to the challenge you outlined:

> This document defines a default specification for grapheme clusters. It may be customized for particular languages, operations, or other situations. For example, arrow key movement could be tailored by language, or could use knowledge specific to particular fonts to move in a more granular manner, in circumstances where it would be useful to edit individual components. This could apply, for example, to the complex editorial requirements for the Northern Thai script Tai Tham (Lanna). Similarly, editing a grapheme cluster element by element may be preferable in some circumstances. For example, on a given system the backspace key might delete by code point, while the delete key may delete an entire cluster.

**Comment by pepa65** [comment]
Elixir really seems to be doing the right thing. I've just never encountered an editor or terminal that treats นำ as one unit.

What I am really after is finding how many positions on a terminal are used by a particular string. I thought this was expressed by the unicode Grapheme concept, but apparently not. Does unicode not have a way of counting how many positions a unicode string takes up?? What is the use of counting graphemes anyway, some sort of linguistic curiosity?

I appreciate your responses, I think we must conclude Elixir does the right thing by the Unicode standard.

I guess asking for an Elixir function that returns the number of positions in a string would be an extra feature request?

**Comment by pepa65** [comment]
> This document defines a default specification for grapheme clusters. It may be customized for particular languages, operations, or other situations. For example, arrow key movement could be tailored by language, or could use knowledge specific to particular fonts to move in a more granular manner, in circumstances where it would be useful to edit individual components. This could apply, for example, to the complex editorial requirements for the Northern Thai script Tai Tham (Lanna). Similarly, editing a grapheme cluster element by element may be preferable in some circumstances. For example, on a given system the backspace key might delete by code point, while the delete key may delete an entire cluster.

Indeed, this is what most interfaces do, which is great. But the Sara Am is NOT zero-length, and I really think Unicode made a mistake. Now to get Thai authorities to care about this...

**Comment by kipcole9** [comment]
> What I am really after is finding how many positions on a terminal are used by a particular string

This is, I think, unobtainable.  Consider the following:
```elixir
iex> String.to_charlist "﷽"
[65021]
```
Thats one code-point, only glyph and one grapheme. How many "positions" does it take?

(We are now off topic for an issue, I recommend closing it and moving to https://elixirforum.com)

**Comment by pepa65** [comment]
That takes 2 positions on a terminal, but the cursor treats it as 1. I guess I am mostly interested in Thai, but at least I know that in Elixir I can just add the number of Sara Ams in the string to the output of String.length..!
