### ISSUE TITLE
Deprecate --

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#13529]
### Elixir and Erlang/OTP versions

All

### Operating system

All

### Current behavior

Currently `--` is supported but its precedence may make operations confusing: `a -- b -- c` is interpreted as `a -- (b -- c)`. I would say that subtracting two lists it is not a common enough operation to warrant a first class operator (for example, there is no equivalent for binaries/strings).

### Expected behavior

Deprecate `--` in favor of `List.subtract/2`. We should first introduce `List.subtract/2` and then deprecate `--/2` in four releases. We should also consider deprecating the related `--` and `---` operators.

**Comment by tfiedlerdejanze** [comment]
Does the same apply for `++` in favor of `List.add/2`? While also being "right associative" the results are not ambiguous when using just `++`. However, i'd find it a bit weird to have `++` but not `--` for Lists in the long term. What do you think?

**Comment by josevalim** [comment]
++ is allowed in pattern matching, where function calls are not allowed. Plus the precedence is correct for ++, it requires fewer copies. It is used quite more often and also has equivalent on binary/strings. There are no plans to deprecate it.

**Comment by josevalim** [comment]
Initial feedback is that `--` is common enough to not warrant a deprecation without further discussion. Thank you.

**Comment by tfiedlerdejanze** [comment]
Reasonable not to deprecate `--` as it also just mirrors what's possible in Erlang. We could still consider adding `List.subtract/2` and `List.add/2` (or append/2) as pipe-friendly alternatives to the kernel operators. Don't have very strong feelings about those, but maybe someone does :)

**Comment by josevalim** [comment]
We generally avoid having duplicate functions. Note you can still pipe to `Kernel.--`, albeit a bit weird.
