### ISSUE TITLE
Latest master fails to compile ecto query that has ... in the bindings.

### ISSUE THREAD

**Issue by dkuku** [elixir-lang/elixir#13520]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.17.0-dev (e557b10) (compiled with Erlang/OTP 26)

### Operating system

linux

### Current behavior

 My code fails to compile dataloader with the folowing error on [this line](https://github.com/absinthe-graphql/dataloader/blob/f1db9ae761ba5264e61d2673d98c0d5577fa8c76/lib/dataloader/ecto.ex#L786)

```elixir
== Compilation error in file lib/dataloader/ecto.ex ==
** (Ecto.Query.CompileError) binding list should contain only variables or `{as, var}` tuples, got: ...
    (ecto 3.10.2) expanding macro: Ecto.Query.where/3
    lib/dataloader/ecto.ex:786: Dataloader.Source.Dataloader.Ecto.build_preload_lateral_query/3
    (elixir 1.17.0-dev) expanding macro: Kernel.|>/2
    lib/dataloader/ecto.ex:786: Dataloader.Source.Dataloader.Ecto.build_preload_lateral_query/3
```

### Expected behavior

It compiles with older versions just fine.

**Comment by v0idpwn** [comment]
This is fixed in Ecto master

**Comment by josevalim** [comment]
It is also fixed in Ecto v3.11.2. :)

**Comment by dkuku** [comment]
Sorry, my bad. I had only ecto_sql in deps that is 3.11.1 and depends on
ecto 3.11.1. In this case mix hex.outdated did not show that there is a
never version of ecto.

**Comment by josevalim** [comment]
No sweat at all, thanks for double checking main!
