### ISSUE TITLE
Windows setup thorw an error

### ISSUE THREAD

**Issue by yeshan333** [elixir-lang/elixir#13569]
### Elixir and Erlang/OTP versions

- Erlang/OTP version is 26.2.5, install by [vfox-erlang](https://github.com/version-fox/vfox-erlang)
- Elixir windows installer: `elixir-otp-26.exe`

### Operating system

windows

### Current behavior

![image](https://github.com/elixir-lang/elixir/assets/39296814/5f45395c-509f-43fa-9845-e1f04311cd61)

when I click elixir-otp-26.exe to install Elixir. then throw an exception: 

```shell
Found existing Erlang/OTP installation at Elixir Setup Found existing Erlang/OTP installation at C:\Userslyeshan333\.version-foxicachelerlanglv-25.3.2.12lerlang-25.3.2.12\release but checking it exited with error:
```

### Expected behavior

No errors are thrown during installation.

**Comment by josevalim** [comment]
@wojtekmach, which check do we execute here? Maybe we can add the check we run?

**Comment by wojtekmach** [comment]
The error is raised here: https://github.com/elixir-lang/elixir/blob/v1.16.2/lib/elixir/scripts/windows_installer/installer.nsi#L119

based on this check:

https://github.com/elixir-lang/elixir/blob/v1.16.2/lib/elixir/scripts/windows_installer/installer.nsi#L94:L96

It looks like you maybe have OTP 25 installed too so consider uninstalling it first. Though the installer should gracefully handle other installation.

**Comment by josevalim** [comment]
@yeshan333 can you try executing the commands above in your Erlang installation? Does it work? What does it return?

**Comment by wojtekmach** [comment]
Thank you for checking, this is really helpful. What is the installer version, i.e. Elixir version, you used?

**Comment by wojtekmach** [comment]
That's not enough information, which release (https://github.com/elixir-lang/elixir/releases) did you download the installer from?

**Comment by yeshan333** [comment]
> That's not enough information, which release (https://github.com/elixir-lang/elixir/releases) did you download the installer from?

this: https://github.com/elixir-lang/elixir/releases/download/v1.16.3/elixir-otp-25.exe

**Comment by simonmcconnell** [comment]
@yeshan333 in the meantime you can handle multiple versions using `scoop`

```
scoop install erlang@25.3.2.12
scoop install elixir@1.16.2-otp-25
scoop install elixir@1.16.3-otp-25 # becomes the current version
scoop reset elixir@1.16.2-otp-25 # change current version
```

**Comment by josevalim** [comment]
Closing this for now. Besides the information above, we are going to include so install scripts on the Elixir website relatively soon. But if you have more updates, please let us know!
