### ISSUE TITLE
initializing basic app throws "  * 1st argument: the table identifier does not refer to an existing ETS table" 

### ISSUE THREAD

**Issue by rrshaban** [elixir-lang/elixir#13574]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

Elixir 1.16.2 (compiled with Erlang/OTP 26)

### Operating system

Mac OS 14.1.2

### Current behavior

Following `Programming Phoenix 1.4` , 
running : 
`mix local.hex` (not sure the purpose of this to be honest, but doesn't fail [though would be nice if it didn't need to http])
`mix archive.install hex phx_new` 
throws 

```

11:21:21.429 [error] GenServer Hex.Registry.Server terminating
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 5.2.3) :ets.insert(nil, {:last_update, {{2024, 5, 20}, {8, 21, 21}}})
    (hex 2.0.6) lib/hex/registry/server.ex:203: Hex.Registry.Server.handle_call/3
    (stdlib 5.2.3) gen_server.erl:1131: :gen_server.try_handle_call/4
    (stdlib 5.2.3) gen_server.erl:1160: :gen_server.handle_msg/6
    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message (from Hex.UpdateChecker): {:last_update, {{2024, 5, 20}, {8, 21, 21}}}
State: %{ets: nil, pending: MapSet.new([]), waiting: %{}, path: nil, fetched: MapSet.new([]), closing_fun: nil}
Client Hex.UpdateChecker is alive

    (stdlib 5.2.3) gen.erl:259: :gen.do_call/4
    (elixir 1.16.2) lib/gen_server.ex:1111: GenServer.call/3
    (hex 2.0.6) lib/hex/update_checker.ex:76: Hex.UpdateChecker.handle_info/2
    (stdlib 5.2.3) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2.3) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Generated phx_new app
```

### Expected behavior

No bugs or errors, just happy Phoenix flying :)

**Comment by josevalim** [comment]
@rrshaban thanks for the report, this seems to have been fixed here: https://github.com/hexpm/hex/commit/15f9e6605295b61ce8ffe8e64501afc09afac622 - in any case, it seems the install operation succeed, you can continue. If you want to be double sure, you can use latest hex: mix archive.install github hexpm/hex

@ericmj perhaps we shall do a new release?

**Comment by josevalim** [comment]
Closing as this has been fixed. Waiting for a new Hex release :)
