### ISSUE TITLE
List.myers_difference/3 results different when comparing nested value

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/elixir#13602]
Given the following:

```elixir
doca = """
        config :phoenix, :template_engines, [
          other: Other.Engine,
        ]
        """

docb = """
        config :phoenix, :template_engines, [
          neex: LiveViewNative.Engine,
          other: Other.Engine
        ]
        """
```

I can split on newlines and find the diff between the two like so:

```elixir
def diff(a, b) do
  a = String.split(a, "\n")
  b = String.split(b, "\n")

  List.myers_difference(a, b, &Kernel.==/2)
end
```

this returns the expected diff:

```elixir
[
  eq: ["config :phoenix, :template_engines, ["],
  del: ["  other: Other.Engine,"],
  ins: ["  neex: LiveViewNative.Engine,", "  other: Other.Engine"],
  eq: ["]", ""]
]
```

however, if I in change to tuples with line numbers:

```elixir
def diff(a, b) do
  a = String.split(a, "\n") |> Enum.with_index(&({&2 + 1, &1}))
  b = String.split(b, "\n") |> Enum.with_index(&({&2 + 1, &1}))

  List.myers_difference(a, b, &(elem(&1, 1) == elem(&2, 1)))
end
```

this results in:

```elixir
[
  eq: [{1, "config :phoenix, :template_engines, ["}],
  del: [{2, "  other: Other.Engine,"}],
  ins: [{2, "  neex: LiveViewNative.Engine,"}, {3, "  other: Other.Engine"}],
  diff: true,
  diff: true
]
```

Now I know the docs reference the nested `diff` key, but if looking at the source, if I add `IO.inspect({diff, elem1, elem2}, label: direction)` to:

https://github.com/elixir-lang/elixir/blob/v1.16.3/lib/elixir/lib/list.ex#L1274
https://github.com/elixir-lang/elixir/blob/v1.16.3/lib/elixir/lib/list.ex#L1291

for the first data set I get:

```elixir
Down: {false, "  other: Other.Engine,", "  neex: LiveViewNative.Engine,"}
Right: {false, "  other: Other.Engine,", "  neex: LiveViewNative.Engine,"}
Down: {false, "]", "  neex: LiveViewNative.Engine,"}
Right: {false, "]", "  neex: LiveViewNative.Engine,"}
Right: {false, "  other: Other.Engine,", "  other: Other.Engine"}
Down: {false, "", "  neex: LiveViewNative.Engine,"}
Right: {false, "", "  neex: LiveViewNative.Engine,"}
Right: {false, "]", "  other: Other.Engine"}
```

and for the 2nd:

```elixir
Down: {false, {2, "  other: Other.Engine,"}, {2, "  neex: LiveViewNative.Engine,"}}
Right: {false, {2, "  other: Other.Engine,"}, {2, "  neex: LiveViewNative.Engine,"}}
Down: {false, {3, "]"}, {2, "  neex: LiveViewNative.Engine,"}}
Right: {false, {3, "]"}, {2, "  neex: LiveViewNative.Engine,"}}
Right: {false, {2, "  other: Other.Engine,"}, {3, "  other: Other.Engine"}}
Down: {false, {4, ""}, {2, "  neex: LiveViewNative.Engine,"}}
Right: {false, {4, ""}, {2, "  neex: LiveViewNative.Engine,"}}
Right: {false, {3, "]"}, {3, "  other: Other.Engine"}}
Right: {false, {2, "  other: Other.Engine,"}, {4, "]"}}
Right: {false, {4, ""}, {3, "  other: Other.Engine"}}
Right: {true, {3, "]"}, {4, "]"}}
Right: {false, {2, "  other: Other.Engine,"}, {5, ""}}
Down: {true, {4, ""}, {5, ""}}
```

The 2nd data set results in a longer path being gone over which is resulting in the `true` values for the comparison and the additional scripts in the final list.

So where am I screwing up?

**Comment by josevalim** [comment]
The algorithm will still compare element by element, the supplied function is only used once you decide they are different, to compute the difference.

**Comment by josevalim** [comment]
It seems you want to compute a per line diff while showing new lines. Note you can still give regular strings to it and compute the line numbers on the result of the diff. Each entry in eq bumps the line number for both, the ins bumps one side, the dels bumps the other.

**Comment by bcardarella** [comment]
@josevalim I was thinking of heading in that direction next, just actually implement a counter while iterating through and properly adding/subtracting. I'll give that a shot.

**Comment by josevalim** [comment]
You don’t add/subtract. Rather two counters, one for the left and the other for the right. We do something like this in mix/tasks/format.ex.
