### ISSUE TITLE
GenServer #PID<~> terminating

### ISSUE THREAD

**Issue by moacirbishopcamata** [elixir-lang/elixir#13615]
### Elixir and Erlang/OTP versions

Erlang/OTP 26.2.5

### Operating system

Windows 10 pro

### Current behavior

[error] GenServer #PID<0.656.0> terminating
** (stop) :econnaborted
Last message: {:tcp_error, #Port<0.29>, :econnaborted}
State: {%ThousandIsland.Socket{socket: #Port<0.29>, transport_module: ThousandIsland.Transports.TCP, read_timeout: 60000, silent_terminate_on_error: false, span: %ThousandIsland.Telemetry{span_name: :connection, telemetry_span_context: #Reference<0.2654146451.1321992198.4719>, start_time: -5764606668487680, start_metadata: %{remote_port: 60877, remote_address: {127, 0, 0, 1}, telemetry_span_context: #Reference<0.2654146451.1321992198.4719>, parent_telemetry_span_context: #Reference<0.2654146451.1321992194.5644>}}}, %{opts: %{http: [], websocket: [], http_1: [], http_2: []}, plug: {Phoenix.Endpoint.SyncCodeReloadPlug, {EVacinaPetWeb.Endpoint, []}}, handler_module: Bandit.HTTP1.Handler, http_1_enabled: true, http_2_enabled: true, requests_processed: 4}}

### Expected behavior

[info] GET /
[debug] Processing with EVacinaPetWeb.PageController.home/2
  Parameters: %{}
  Pipelines: [:browser]

**Comment by whatyouhide** [comment]
Hi @moacirbishopcamata thanks for the issue! This is not an issue with Elixir. Elixir is just reporting that the GenServer handling the request crashed. You'll want to open this issue in https://github.com/mtrudel/thousand_island.
