### ISSUE TITLE
Compiler diagnostics originating from typesystem are incomplete

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#13646]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.17.0-rc.0 (db89cbf) (compiled with Erlang/OTP 27)

### Operating system

any

### Current behavior

Given this code
```
defmodule Foo do
  defstruct asd: nil
end

defmodule Bar do
  a = %Foo{}
  @asd a

  def s do
    @asd.ccc
  end
end
```
The emitted diagnostic has truncated message and no details
```
%Mix.Task.Compiler.Diagnostic{
    file: "/Users/foo/lib/some.ex",
    source: "/Users/foo/lib/some.ex",
    severity: :warning,
    message: "unknown key .ccc in expression:\n\n    %{__struct__: Foo, asd: nil}.ccc\n\nthe given type does not have the given key:\n\n    %Foo{asd: nil}\n\ntyping violation found at:",
    position: {10, 10},
    compiler_name: "Elixir",
    span: nil,
    details: nil,
    stacktrace: [
      {Bar, :s, 0,
       [
         file: ~c"lib/some.ex",
         end_of_expression: [newlines: 1, line: 10, column: 13],
         no_parens: true,
         line: 10,
         column: 10
       ]}
    ]
  }
```
Whereas the same code emits this in terminal
```
    warning: unknown key .ccc in expression:

        %{__struct__: Foo, asd: nil}.ccc

    the given type does not have the given key:

        %Foo{asd: nil}

    typing violation found at:
    │
 10 │     @asd.ccc
    │          ~
    │
    └─ lib/some.ex:10:10: Bar.s/0
```

### Expected behavior

Message not truncated, detail filled, possibly span filled

**Comment by josevalim** [comment]
Thank you!

The message is not truncated, we don't include the snippet because we expect you to show it. I think however it can be confusing. Perhaps we should end the message by saying "typing violation found"?

We could compute the spam though, that would benefit both the console warning and the terminal one.

And what do you expect to be in detail?

**Comment by lukaszsamson** [comment]
> we don't include the snippet because we expect you to show it

I don't think I follow. This is clearly different than `TokenMissingError` etc. where snippets are returned. I don't insist that the snippet is needed. Position/span is sufficient for LSP

> And what do you expect to be in detail?

Other errors have exception in detail. I would expect to find some structured info about the type problem:
- positions where conflicting types are defined
- the conflicting types as data

In [LSP Diagnostic](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic) besides the main position/span (`range` property) and `message`,  there is a collection `relatedInformation` which can contain additional positions and messages. It's possible to build diagnostics that reference type definitions in another files. This is an example from elixir-ls
<img width="642" alt="Screenshot 2024-06-06 at 22 02 39" src="https://github.com/elixir-lang/elixir/assets/1078186/496d3220-7554-4e87-946e-3d1aa9568dbe">

**Comment by josevalim** [comment]
> This is clearly different than TokenMissingError etc. where snippets are returned. I don't insist that the snippet is needed. 

I think that's rather a flaw in TokenMissingError. I don't think we include it anywhere else. If you do `IO.warn("hello", __ENV__)` in the module body, does the diagnostic have the snippet as well or not really?

> Other errors have exception in detail. I would expect to find some structured info about the type problem:

Got it. I will see what we can expose. Perhaps we can expose the traces.

**Comment by lukaszsamson** [comment]
> does the diagnostic have the snippet as well or not really?

No, only some of them do. The changes to include snippets were introduced in 1.16. In fact they do look ugly if the UI displaying it is not using a monospaced font (and there is no markdown support in diagnostic messages but that's VSCode issue https://github.com/microsoft/vscode/issues/54272)

<img width="990" alt="Screenshot 2024-06-09 at 08 09 42" src="https://github.com/elixir-lang/elixir/assets/1078186/9866b1a7-41e5-4997-bb8f-53ea89b86e19">
<img width="993" alt="Screenshot 2024-06-09 at 08 10 20" src="https://github.com/elixir-lang/elixir/assets/1078186/f9fe2b78-79da-478e-bccf-2d7e64a3e6e0">
<img width="984" alt="Screenshot 2024-06-09 at 08 11 03" src="https://github.com/elixir-lang/elixir/assets/1078186/4cf083e6-9a34-4359-b366-ce23b3031eff">

**Comment by josevalim** [comment]
For completeness, the reason why syntax error, token missing error, etc include the snippets is because they are exceptions. You can probably intercept those exceptions and render something without the diagnostics if desired.
