### ISSUE TITLE
Documentation for logger config appears inadequate (or out-of-date?)

### ISSUE THREAD

**Issue by koszalopal** [elixir-lang/elixir#13661]
### Elixir and Erlang/OTP versions

Based on the documentation, that is

```
  https://hexdocs.pm/logger/1.16.2/Logger.html#module-configuration
  elixir/lib/logger/lib/logger.ex
```

I have assumed that the following entry in `config/config.exs` would switch the logger from `stdout` to `stderr`.

```
  config :logger, :default_handler,
    config: [
      type: :standard_error
    ]
```

However, the config entry appears to have no effect.
Steps to reproduce have been automated in the attached script.
It will create a mix project in `/tmp`, configure the logger, and then run a task that uses the logger.

I have tried to alter different settings, including disabling logging altogether with

```
  config :logger, :default_handler, false
```

Yet the logger is never affected.

It also not clear why the Elixir documentation mentions `:default_handler`, 
whereas the config on the Erlang side uses `:default`.

[demo.sh.txt](https://github.com/user-attachments/files/15825269/demo.sh.txt)

### Operating system

Linux

### Current behavior

Output goes to stdout

```
18:15:05.513 [warning] config.type :standard_io
```

### Expected behavior

Output goes to stderr

```
18:15:05.513 [warning] config.type :standard_error
```

**Comment by josevalim** [comment]
Inside Mix tasks, configuration is not applied until you run the Mix task that applies it. You need to add either `@requirements ["app.config"]` or `@requirements ["app.start"]` accordingly.
