### ISSUE TITLE
`key: value` syntax sugar in tuples

### ISSUE THREAD

**Issue by LostKobrakai** [elixir-lang/elixir#13681]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Interactive Elixir (1.17.0) - press Ctrl+C to exit (type h() ENTER for help)

### Operating system

Mac OS

### Current behavior

`{1, a: :b}` is valid syntax and evalutes to `{1, [a: :b]}`.

This came up recently on https://elixirforum.com/t/keyword-inside-tuple-shorthand-syntax-a-1-b-2/63960, but also had someone ask on the slack beginner channel about it today.

### Expected behavior

On https://hexdocs.pm/elixir/syntax-reference.html there are two sections related to `a: :b` key/value pairs.

It's mentioned as part of the definition of maps and keyword list, when within `%{…}` and `[…]` ([here](https://hexdocs.pm/elixir/syntax-reference.html#maps-and-keyword-lists)). Given here it's taken as a keyword list, but without explicit square brackets, the section on optional square brackets is also relevant ([here](https://hexdocs.pm/elixir/syntax-reference.html#keywords-as-last-arguments)).

> Elixir also supports a syntax where if the last argument of a call is a keyword list then the square brackets can be skipped.

Calls are earlier in the document defined to be non-qualified calls (`fun(…)`) or qualified calls (`Mod.fun(…)`). Both include

> …, must start with characters and then follow the same rules as variables, which are optionally followed by parentheses, and then arguments.

Tuple creation doesn't fit that picture painted by those parts of the syntax reference. I would've expected that square brackets would be required for a keyword list being the last element of a tuple.

@michalmuskala showed on slack that the following is also valid syntax, but in that case it doesn't evaluate to a valid value:

```
iex(2)> quote(do: <<1, a: 1, b: 2>>)
{:<<>>, [], [1, [a: 1, b: 2]]}
```

I can't say what's wrong here, documentation or implementation, but coming from the documentation the current behaviours looks like a bug. If that's not a bug then I think the documentation needs adjustment.

**Comment by josevalim** [comment]
The syntax is correct and we use it in places like `mix.exs` for deps:

    {:my_app, path: "..."}

Inside containers, keyword lists are always flattened. Bitstrings are the only ones behaving inconsistently but it was never detected because it is not used anywhere. :) I will fix it accordingly, as well as the docs. Thanks for the report!
