### ISSUE TITLE
Raising compile error when generating lots of functions via `__using__/1` macros.

### ISSUE THREAD

**Issue by c4710n** [elixir-lang/elixir#13691]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.1 (compiled with Erlang/OTP 27)
```

### Operating system

macOS Sonoma 14.5

### Current behavior

Here's a minimal example I'm trying to reproduce the issue:
```
defmodule Demo.A1 do
  defmacro __using__(_opts) do
    Enum.map(1..3000, fn n ->
      quote do
        def get(unquote(n) = n), do: n
      end
    end)
  end
end

defmodule Demo.B1 do
  use Demo.A1
end
```

When running above code, it outputs:
```
Compiling 1 file (.ex)

== Compilation error in file lib/demo.ex ==
** (CompileError) elixir_compiler_3:1: function '__MODULE__'/1+12:
  An implementation limit was reached.
  Try reducing the complexity of this function.

  Instruction: {call_ext,3,{extfunc,elixir_def,store_definition,3}}

    (stdlib 6.0) lists.erl:2310: :lists.foreach_1/2

```

> I saw other people also generate lots of functions via macros in their module, but they are using `@before_compile`, like:
> ```
> defmodule Demo.A2 do
>   defmacro generate_functions(_env) do
>     Enum.map(1..3000, fn n ->
>       quote do
>         def get(unquote(n) = n), do: n
>       end
>     end)
>   end
> end
>
> defmodule Demo.B2 do
>   @before_compile {Demo.A2, :generate_functions}
> end
> ```
> In this way, it works.

### Expected behavior

`use` has the same behaviour like `@before_compile`.

**Comment by josevalim** [comment]
This warning is coming from the Erlang compiler and there is nothing we can do. However, you can easily address this by removing the nesting. Today you are effectively defining a list with one function definition. If you flatten it into a block, it works:

```elixir
defmodule Demo.A1 do
  defmacro __using__(_opts) do
    defs =
    Enum.map(1..3000, fn n ->
      quote do
        def get(unquote(n) = n), do: n
      end
    end)
    
    quote do
      unquote_splicing(defs)
    end
  end
end

defmodule Demo.B1 do
  use Demo.A1
end
```

Or do `{:__block__, [], defs}`.
