### ISSUE TITLE
[1.17] found error while checking types for struct defined without defstruct

### ISSUE THREAD

**Issue by Shakadak** [elixir-lang/elixir#13698]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.17.1 (compiled with Erlang/OTP 27)

### Operating system

Kubuntu 22.04

### Current behavior

Hello, I'm using custom structs to define some sum types/variants and also have access to protocols, and while trying to run my project with Elixir 1.17, I got an error prompting me to report this bug.  
I did a quick Google search for the past month as a range, and didn't find anything, sorry if a missed an existing issue where I could have added to.

Here is the error:
```
** (EXIT from #PID<0.95.0>) an exception was raised:
    ** (RuntimeError) found error while checking types for Data.Option.map/2:

** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
The exception happened while checking this code:

def map(%Data.Option{some: x}, f) do
  %Data.Option{some: f.(x)}
end

Please report this bug at: https://github.com/elixir-lang/elixir/issues

        (elixir 1.17.1) lib/enum.ex:1: Enumerable.impl_for!/1
        (elixir 1.17.1) lib/enum.ex:166: Enumerable.reduce/3
        (elixir 1.17.1) lib/enum.ex:4423: Enum.reduce/3
        (elixir 1.17.1) lib/module/types/of.ex:182: Module.Types.Of.struct/6
        (elixir 1.17.1) lib/module/types/pattern.ex:90: Module.Types.Pattern.of_pattern/4
        (elixir 1.17.1) lib/module/types/helpers.ex:128: Module.Types.Helpers.do_map_reduce_ok/3
        (elixir 1.17.1) lib/module/types/pattern.ex:18: Module.Types.Pattern.of_head/5
        (elixir 1.17.1) lib/module/types.ex:55: Module.Types.warnings_from_clause/6
```

Here is a almost minimal code that produces the error:
```elixir
defmodule Data.Option do
  def __struct__ do
    %{
      __struct__: __MODULE__,
      some: nil,
      none: :none,
    }
  end

  def __struct__(kv) do
    case kv do
      [some: x] -> %{__struct__: __MODULE__, some: x}
      [none: :none] -> %{__struct__: __MODULE__, none: :none}
    end
  end

  defmacro some(x), do: quote(do: %unquote(__MODULE__){some: unquote(x)})
  defmacro none, do: quote(do: %unquote(__MODULE__){none: :none})

  def map(some(x), f), do: some(f.(x))
  def map(none(),  _), do: none()
end
```

### Expected behavior

There is just no error in Elixir 1.16.2

**Comment by josevalim** [comment]
Unfortunately what you are trying to do is not supported. The Elixir compiler cannot deal with structs of different fields (as in your `__struct__/1` function and the compiler may rely on internal metadata used by `defstruct` in order to work properly. If it worked before, it was by accident, as you must define your structs with `defstruct`, otherwise you will always be chasing implementation details of how `defstruct` works behind the scenes.

**Comment by lukaszsamson** [comment]
@josevalim this used to be a documented feature up until 1.12.3. In 1.13.0 the documentation was removed (https://github.com/elixir-lang/elixir/commit/148b62ecb8002b64011bf1d3357f6964aa436c85) but I can't find it mentioned as deprecated in the [changelog for 1.13](https://hexdocs.pm/elixir/1.13/changelog.html) nor [changelog for 1.12](https://hexdocs.pm/elixir/1.12/changelog.html)

**Comment by josevalim** [comment]
Good call. We can likely support defining your `__struct__/0` and `__struct__/1` back but we did not ever support returning different fields per struct.

**Comment by Shakadak** [comment]
It's fine on my end, I'll adapt my code :)
