### ISSUE TITLE
`function_exported?/3` breaks for `__info__/1` after recompile

### ISSUE THREAD

**Issue by reisub** [elixir-lang/elixir#13708]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.1 (compiled with Erlang/OTP 27)

### Operating system

macOS 14.5

### Current behavior

`function_exported?(Foo, :__info__, 1)` returns false for a module that exists and exports the function after a recompile or on the 2nd run.

I've prepared a minimal example that makes it easy to reproduce:
https://github.com/reisub/function-exported-bug

I also tried:
- Elixir 1.16.3-otp-26 (with latest OTP 26)
- Elixir 1.16.3-otp-25 (with latest OTP 25)

And both showed the same behavior.

### Expected behavior

`function_exported?(Foo, :__info__, 1)` should return true when the module exists and exports the `__info__/1` function.

**Comment by josevalim** [comment]
As the docs say, function_exported? does not load the module. You need to ensure it is loaded before: https://hexdocs.pm/elixir/1.17.1/Kernel.html#function_exported?/3 :)

**Comment by reisub** [comment]
Oh, I see now - thanks and sorry for the false alarm!
