### ISSUE TITLE
Elixir 1.17.2 Test Error:    left:  ~c"/usr/local/lib/erlang/lib/kernel-9.3"      right: ~c"/usr/local/lib/erlang/lib/kernel-10.0"

### ISSUE THREAD

**Issue by verbus** [elixir-lang/elixir#13719]
### Elixir and Erlang/OTP versions

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 24.04 LTS
Release: 24.04
Codename: noble

erl -s erlang halt
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

 
 
elixir --version
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]

Elixir 1.17.2 (compiled with Erlang/OTP 27)
 
 
gleam --version
gleam 1.3.1
 

3) test from_config!/3 includes applications (Mix.ReleaseTest)
     test/mix/release_test.exs:74
     Assertion with == failed
     code:  assert release.applications.kernel[:path] == to_charlist(Application.app_dir(:kernel))
     left:  ~c"/usr/local/lib/erlang/lib/kernel-9.3"
     right: ~c"/usr/local/lib/erlang/lib/kernel-10.0"
     stacktrace:
       test/mix/release_test.exs:79: (test)

### Operating system

Description: Ubuntu 24.04 LTS Release: 24.04

### Current behavior

3) test from_config!/3 includes applications (Mix.ReleaseTest)
     test/mix/release_test.exs:74
     Assertion with == failed
     code:  assert release.applications.kernel[:path] == to_charlist(Application.app_dir(:kernel))
     left:  ~c"/usr/local/lib/erlang/lib/kernel-9.3"
     right: ~c"/usr/local/lib/erlang/lib/kernel-10.0"
     stacktrace:
       test/mix/release_test.exs:79: (test)

### Expected behavior

The test should pass.

**Comment by josevalim** [comment]
Can you return the results of `ls /usr/local/lib/erlang/lib/` inside? It seems you have conflicting Erlang installations in the same directory.

**Comment by verbus** [comment]
That seems to have been the problem.
verbus@verbus-X570-AORUS-ELITE-WIFI:~/elixir$ ls /usr/local/lib/erlang/lib/ 
asn1-5.0.16         debugger-5.3         erts-12.0.3  inets-8.2.1        mnesia-4.22.1         sasl-4.1     ssl-11.2
asn1-5.0.17         debugger-5.3.1       erts-12.1    inets-8.2.2        mnesia-4.23           sasl-4.1.1   stdlib-3.15.2
asn1-5.0.18         debugger-5.3.2       erts-12.1.2  inets-8.3          mnesia-4.23.1         sasl-4.1.2   stdlib-3.16
asn1-5.0.19         debugger-5.3.3       erts-12.1.3  inets-8.3.1        mnesia-4.23.2         sasl-4.2     stdlib-3.16.1
asn1-5.0.20         debugger-5.3.4       erts-12.1.4  inets-9.0          mnesia-4.24           sasl-4.2.1   stdlib-3.17
asn1-5.0.21         debugger-5.4         erts-12.1.5  inets-9.0.1        observer-2.10         sasl-4.2.2   stdlib-3.17.1
asn1-5.1            dialyzer-4.4.1       erts-12.2    inets-9.0.2        observer-2.10.1       sasl-4.3     stdlib-4.0
asn1-5.2            dialyzer-4.4.2       erts-12.2.1  inets-9.1          observer-2.11.1       snmp-5.10    stdlib-4.0.1
asn1-5.2.1          dialyzer-4.4.3       erts-12.3.1  inets-9.2          observer-2.12         snmp-5.10.1  stdlib-4.1
asn1-5.2.2          dialyzer-4.4.4       erts-13.0    jinterface-1.12    observer-2.13         snmp-5.11    stdlib-4.1.1
asn1-5.3            dialyzer-5.0         erts-13.0.1  jinterface-1.12.1  observer-2.14         snmp-5.12    stdlib-4.2
common_test-1.20.5  dialyzer-5.0.1       erts-13.0.2  jinterface-1.12.2  observer-2.15         snmp-5.13    stdlib-4.3
common_test-1.21    dialyzer-5.0.2       erts-13.0.3  jinterface-1.13    observer-2.15.1       snmp-5.13.1  stdlib-4.3.1
common_test-1.22    dialyzer-5.0.3       erts-13.0.4  jinterface-1.13.1  observer-2.16         snmp-5.13.2  stdlib-5.0
common_test-1.22.1  dialyzer-5.0.4       erts-13.1    jinterface-1.13.2  observer-2.9.6        snmp-5.13.3  stdlib-5.0.1
common_test-1.23    dialyzer-5.0.5       erts-13.1.1  jinterface-1.14    odbc-2.13.5           snmp-5.13.4  stdlib-5.0.2
common_test-1.23.1  dialyzer-5.1         erts-13.1.2  jinterface-1.14.1  odbc-2.14             snmp-5.13.5  stdlib-5.1
common_test-1.23.2  dialyzer-5.1.1       erts-13.1.3  jinterface-1.15    odbc-2.14.1           snmp-5.14    stdlib-5.1.1
common_test-1.23.3  dialyzer-5.1.2       erts-13.1.4  kernel-10.0        odbc-2.14.2           snmp-5.15    stdlib-5.2
common_test-1.24    dialyzer-5.1.3       erts-13.1.5  kernel-8.0.2       odbc-2.14.3           snmp-5.16    stdlib-5.2.3
common_test-1.25    dialyzer-5.2         erts-13.2    kernel-8.1         odbc-2.15             snmp-5.9.1   stdlib-6.0
common_test-1.25.1  diameter-2.2.4       erts-13.2.1  kernel-8.1.2       os_mon-2.10           ssh-4.12.3   syntax_tools-2.6
common_test-1.26    diameter-2.2.5       erts-13.2.2  kernel-8.1.3       os_mon-2.7            ssh-4.12.4   syntax_tools-3.0
common_test-1.26.2  diameter-2.2.6       erts-14.0    kernel-8.2         os_mon-2.7.1          ssh-4.12.5   syntax_tools-3.0.1
common_test-1.27    diameter-2.2.7       erts-14.0.1  kernel-8.3.1       os_mon-2.8            ssh-4.13     syntax_tools-3.1
compiler-8.0.2      diameter-2.3         erts-14.0.2  kernel-8.4         os_mon-2.8.1          ssh-4.13.2   syntax_tools-3.2
compiler-8.0.3      diameter-2.3.1       erts-14.1    kernel-8.4.1       os_mon-2.8.2          ssh-4.14     tftp-1.0.3
compiler-8.0.4      diameter-2.3.2       erts-14.2.1  kernel-8.4.2       os_mon-2.9            ssh-4.14.1   tftp-1.0.4
compiler-8.1        diameter-2.4         erts-14.2.5  kernel-8.5         os_mon-2.9.1          ssh-4.15     tftp-1.1
compiler-8.2        edoc-1.0             erts-14.3    kernel-8.5.1       parsetools-2.3        ssh-4.15.1   tftp-1.1.1
compiler-8.2.1      edoc-1.0.1           erts-15.0    kernel-8.5.2       parsetools-2.3.1      ssh-4.15.2   tftp-1.2
compiler-8.2.2      edoc-1.1             et-1.6.5     kernel-8.5.3       parsetools-2.3.2      ssh-4.15.3   tools-3.5
compiler-8.2.3      edoc-1.2             et-1.7       kernel-8.5.4       parsetools-2.4        ssh-5.0      tools-3.5.1
compiler-8.2.4      edoc-1.2.1           et-1.7.1     kernel-9.0         parsetools-2.4.1      ssh-5.0.1    tools-3.5.2
compiler-8.2.5      edoc-1.3             et-1.8       kernel-9.0.1       parsetools-2.5        ssh-5.1.1    tools-3.5.3
compiler-8.2.6      eldap-1.2.10         eunit-2.10   kernel-9.0.2       parsetools-2.6        ssh-5.1.4    tools-3.6
compiler-8.3        eldap-1.2.11         eunit-2.6.1  kernel-9.1         public_key-1.11.1     ssh-5.2      tools-4.0
compiler-8.3.1      eldap-1.2.12         eunit-2.7    kernel-9.2         public_key-1.11.2     ssl-10.4.2   wx-2.0.1
compiler-8.3.2      eldap-1.2.13         eunit-2.7.1  kernel-9.2.4       public_key-1.11.3     ssl-10.5     wx-2.1
compiler-8.4        eldap-1.2.9          eunit-2.8    kernel-9.3         public_key-1.12       ssl-10.5.1   wx-2.1.1
compiler-8.4.1      eldap-1.3            eunit-2.8.1  megaco-4.0.1       public_key-1.13       ssl-10.5.2   wx-2.1.3
compiler-8.4.3      erl_docgen-1.1.1     eunit-2.8.2  megaco-4.1         public_key-1.13.1     ssl-10.5.3   wx-2.2
compiler-8.5        erl_docgen-1.1.2     eunit-2.9    megaco-4.2         public_key-1.13.2     ssl-10.6     wx-2.2.1
crypto-5.0.2        erl_docgen-1.2       eunit-2.9.1  megaco-4.3         public_key-1.13.3     ssl-10.6.1   wx-2.2.2
crypto-5.0.3        erl_docgen-1.2.1     ftp-1.1      megaco-4.4         public_key-1.14       ssl-10.7.2   wx-2.3
crypto-5.0.4        erl_docgen-1.3       ftp-1.1.1    megaco-4.4.1       public_key-1.14.1     ssl-10.8     wx-2.3.1
crypto-5.0.5        erl_docgen-1.4       ftp-1.1.2    megaco-4.4.2       public_key-1.15       ssl-10.8.1   wx-2.4
crypto-5.0.6        erl_docgen-1.5       ftp-1.1.3    megaco-4.4.3       public_key-1.15.1     ssl-10.8.2   wx-2.4.1
crypto-5.1          erl_docgen-1.5.1     ftp-1.1.4    megaco-4.4.4       public_key-1.16       ssl-10.8.3   wx-2.4.2
crypto-5.1.1        erl_docgen-1.5.2     ftp-1.1.5    megaco-4.5         reltool-0.9           ssl-10.8.4   wx-2.5
crypto-5.1.2        erl_interface-5.0.1  ftp-1.2      megaco-4.6         reltool-0.9.1         ssl-10.8.5   xmerl-1.3.28
crypto-5.1.3        erl_interface-5.1    ftp-1.2.1    mnesia-4.19.1      reltool-1.0           ssl-10.8.6   xmerl-1.3.29
crypto-5.1.4        erl_interface-5.2.2  ftp-1.2.2    mnesia-4.20        reltool-1.0.1         ssl-10.8.7   xmerl-1.3.30
crypto-5.2          erl_interface-5.3    ftp-1.3      mnesia-4.20.1      reltool-1.1           ssl-10.9     xmerl-1.3.31
crypto-5.3          erl_interface-5.3.1  inets-7.4.1  mnesia-4.20.3      runtime_tools-1.16.2  ssl-10.9.1   xmerl-1.3.31.1
crypto-5.4          erl_interface-5.3.2  inets-7.4.2  mnesia-4.21        runtime_tools-1.17    ssl-11.0     xmerl-1.3.32
crypto-5.4.2        erl_interface-5.4    inets-7.5    mnesia-4.21.1      runtime_tools-1.18    ssl-11.0.1   xmerl-1.3.34
crypto-5.5          erl_interface-5.5    inets-7.5.2  mnesia-4.21.2      runtime_tools-1.19    ssl-11.0.2   xmerl-1.4
debugger-5.1        erl_interface-5.5.1  inets-8.0    mnesia-4.21.3      runtime_tools-2.0     ssl-11.0.3   xmerl-2.0
debugger-5.2        erl_interface-5.5.2  inets-8.1    mnesia-4.21.4      runtime_tools-2.0.1   ssl-11.1
debugger-5.2.1      erl_interface-5.6    inets-8.2    mnesia-4.22        runtime_tools-2.1     ssl-11.1.4

What are the corrective actions to take?

**Comment by josevalim** [comment]
I would uninstall all Erlang versions on your machine and do a fresh install. Perhaps consider using a tool like [asdf](https://asdf-vm.com/) for managing multiple Erlang installations. Meanwhile I will close this as it is not an Elixir issue. :)
