### ISSUE TITLE
No way to specify `dot-formatter` for downstream use in ElixirLS

### ISSUE THREAD

**Issue by kieraneglin** [elixir-lang/elixir#13718]
### Elixir and Erlang/OTP versions

Elixir 1.17.0 (compiled with Erlang/OTP 26)

### Operating system

MacOS

### Current behavior

Additional context: https://github.com/elixir-lsp/vscode-elixir-ls/issues/421

The issue is that when using the ElixirLS via `vscode-elixir-ls` there is no way to specify a custom `dot-formatter` path. According to the maintainers of `vscode-elixir-ls`, this is an upstream issue with Elixir since they lack the ability to read a hypothetical `dot-formatter` path from the Mix project.

### Expected behavior

Elixir formatting tooling should be able to respect custom locations for your `dot-formatter` similar to how you can pass `--dot-formatter` to `mix format`. This behaviour should be opt-in and default to using `.formatter.exs`

**Comment by josevalim** [comment]
`mix format` does not read Mix project on purpose. We want to reduce the amount of operations and files we read before formatting. We could perhaps support an env var but perhaps this is better done as a VSCode config? cc @lukaszsamson

**Comment by lukaszsamson** [comment]
> mix format does not read Mix project

It does in case the project is not compiled. It loads formatter plugins.

> We could perhaps support an env var but perhaps this is better done as a VSCode config

No hard opinions on that. `formatter_for_file` should handle `dot_formatter` opt but there is no standardised way of passing it/reading from project settings. OP uses a mix task alias

```
defp aliases do
  [
    format: "format --dot-formatter=tooling/.formatter.exs",
    # ...
  ]
end
```

The language server is unaware of such aliasing and calls `formatter_for_file` with default opts

**Comment by josevalim** [comment]
I will close this for now for the reasons above. Language servers may provide a config option if desired. The :dot_formatter option is already supported on `formatter_for_file`. :)
