### ISSUE TITLE
should mix test --failed fail when there are test compilation errors

### ISSUE THREAD

**Issue by dvic** [elixir-lang/elixir#13728]
### Elixir and Erlang/OTP versions

1.17 + OTP 26

### Operating system

Mac

### Current behavior

`mix test || mix test --failed` succeeds when a test contains a compilation error

learned through: https://angelika.me/2024/01/08/do-not-run-mix-test-failed/
affects also: https://github.com/karolsluszniak/ex_check/issues/48

### Expected behavior

I was expected that `mix test --failed` fails when there are test compilation errors.

**Comment by josevalim** [comment]
This is tricky. If this happens, we most likely want to tackle the whole suite as invalid. However, if something failed before and tests do not compile, we don’t want to run the whole suite. So perhaps, when compiling tests fail, and there is nothing in the failure manifest, we load all tests.

however, I think we had a discussion about this in the past. We may have a flag or something to deal with this?

**Comment by dvic** [comment]
Not sure about the flag, but I now do see this past discussion: https://github.com/elixir-lang/elixir/issues/10781

What I understand from the discussion is that at one point `mix test --failed` was changed to run all tests if there were no previously failed ones:
https://github.com/elixir-lang/elixir/commit/ae4832599151bdd7ccaec66a9a9f1a7def97cac4

But that got reverted again? https://github.com/elixir-lang/elixir/commit/e717a4bb4f8fa27752292c2e4dd3025080f1f331
