### ISSUE TITLE
ExUnit: ANSI escape sequences are not escaped in doctest and code sections

### ISSUE THREAD

**Issue by fuelen** [elixir-lang/elixir#13723]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.17.2 (compiled with Erlang/OTP 27)

### Operating system

Linux

### Current behavior

```elixir
defmodule MyTest do
  @doc """
  ## Examples

      iex> [[[[[[[] | "\e[31m"] | "\e[46m"], "hello"] | "\e[49m"] | "\e[39m"] | "\e[0m"]
      [[[[[[[] | "\e[46m"] | "\e[31m"], "hello"] | "\e[39m"] | "\e[49m"] | "\e[0m"]

  """
  def test do
    :noop
  end
end
```
```elixir
defmodule MyTestTest do
  use ExUnit.Case
  doctest MyTest
end
```
ANSI escape sequences are not escaped in `doctest` and `code` sections:
![зображення](https://github.com/user-attachments/assets/1aca3274-96ee-44c6-a3a7-be77681b4262)

### Expected behavior

Treat them as a regular text

**Comment by josevalim** [comment]
This is expected because those characters are being introduced as is in the string, instead of being escaped. If you escape them, by using "\\e[31m", or by using the `~S"""` sigil, which disables escaping, you get the desired result.
