### ISSUE TITLE
GTK warnings when starting Observer

### ISSUE THREAD

**Issue by arvaid** [elixir-lang/elixir#13731]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.5.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.16.2 (compiled with Erlang/OTP 26)

### Operating system

Fedora Linux 40

### Current behavior

When running `:observer.start()` from `iex`, the console is filled with messages like this:
```
11:02:37.466 [notice] wx: GTK: State 0 for context 0x7ff1286a7b00 doesn't match state 128 set via gtk_style_context_set_state ()
```

This only happens on Linux systems, and only in `iex`, not in the `erl` shell.

### Expected behavior

Messages like this should be hidden, like when using the `erl` shell.

**Comment by stefannovak** [comment]
It's quite annoying! Getting this on Fedora 38 too.

**Comment by josevalim** [comment]
This is happening because Elixir's default log level is `debug` and I believe Erlang's is `info`. You can change the log level or setup a filter to ignore observer messages.
