### ISSUE TITLE
Make `behaviour_info` more accessible in documentation

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#13733]
Right now, if you want to get information about the `behaviour_info/1` function that gets generated in behaviours, you have to do one of the following:

  * Go to the docs for the `Behaviour` module. This is bad as that module is *deprecated*.
  * Google `behaviour_info elixir`, which returns sucky results (screenshot below)
  * Google `behaviour_info erlang`, where for me the **third result** is the [*Modules* Erlang docs](https://www.erlang.org/docs/17/reference_manual/modules), where then I have to search `behaviour_info` in the page.

This is all not ideal IMO, can we make it better? I’m a bit out of ideas. We could implement a mock `Kernel.behaviour_info/1` function just to document stuff, but I’m not sure that's a good solution. Thoughts? 

![CleanShot 2024-07-23 at 16 02 31@2x](https://github.com/user-attachments/assets/733db8c9-d1cc-45c3-b20e-a8db7235cd79)

**Comment by josevalim** [comment]
We should document it in `Module`. That’s where we document @impl, @behaviour, and others. The Behavior module can point to the new docs we add.

**Comment by whatyouhide** [comment]
@josevalim yeah that's gonna be a start. Currently searching for `@impl` in Hexdocs is not a good experience but something turns up at least 😉 But that's an ex_doc thing and I'll open an issue in there. I'll add docs to `Module` and link from `Behaviour`.
