### ISSUE TITLE
standard error output format for the Elixir compiler

### ISSUE THREAD

**Issue by ericbmerritt** [elixir-lang/elixir#1373]
The de facto standard for error and warning output from compilers is that of GCC. That format is:

```
 <file>:<line-number>(:<column-number>):<detail>
```

It has the dual advantage that a lot of compile tools (compile mode for emacs) already parse this format, and its pretty trivial to parse via regex for future tools. It would be a very nice feature if Elixir had the ability to output in this format. 

Wether that becomes the default option, or some type of compiler flag is up to the author.

**Comment by josevalim** [comment]
Unfortunately that won't fix the issue. Remember that compiling Elixir code is just running Elixir code, which means that you can get compilation errors but also regular exceptions too. The things we can control and normalize, we already do, such as warnings. But there is nothing stopping the user writing directly to stdout/stderr with their own input too.

The less hacky way to do this is to leverage the new compiler diagnostics that shipped in Elixir v1.6 That's what ElixirLS does and it returns the errors and warnings are structured data.
