### ISSUE TITLE
Internal consistency check failed: The following label(s) were referenced but not defined

### ISSUE THREAD

**Issue by zachdaniel** [elixir-lang/elixir#13747]
### Elixir and Erlang/OTP versions

Erlang/OTP OTP-27.0.1 - built on amd64/ubuntu-22.04
Elixir 1.17.2 (built for Erlang/OTP OTP 27)

### Operating system

 ubuntu-22.04

### Current behavior

Quite a few Ash users have been reporting this issue in their CI builds, but we've been holding off on reporting it until we have something reproducible. While this is reproducible in *CI*, no one has yet to run into it locally as far as I know. This issue is flaky and does not occur on every build, but its been reported as much as every other or every third build by some folks.

Here is a link to the reproduction that was shared to me by one of our users: https://github.com/pinetops/ash_compiler_crash/actions/runs/10153994945/job/28078386712

The root of the issue appears to lie in our package `spark`, which defines modules & functions based on a data structure. It is a DSL builder. The error always points to the same function `__set_and_validate_options__`, which is dynamically defined, with multiple clauses matching certain specific inputs. But I do not believe that it always points to the same module (in this case: `Ash.Policy.Authorizer`).

Unfortunately, we do quite a few wacky things in `spark`. I'm very happy to either change those things to avoid this issue (it could very likely be an error on my part), or spend as much time as is necessary explaining what we're doing/why if it can help elucidate the bug.

Here is the full error (omitting the dependencies above compiling)

```
...
==> ash
Compiling 485 files (.ex)

== Compilation error in file lib/ash/policy/authorizer/authorizer.ex ==
Error: ** (CompileError) Elixir.Ash.Policy.Authorizer:1: function '__set_and_validate_options__'/2:
  Internal consistency check failed - please report this bug.
  The following label(s) were referenced but not defined:
  11 13 18 

    (stdlib 6.0.1) lists.erl:2310: :lists.foreach_1/2
could not compile dependency :ash, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile ash --force", update it with "mix deps.update ash" or clean it with "mix deps.clean ash"
```

### Expected behavior

The error does not occur, or perhaps produces a useful error message indicating what I've done wrong.

**Comment by josevalim** [comment]
The error comes from Erlang, so can you please provide a smaller reproduction in Elixir (so I can provide a smaller reproduction to the Erlang/OTP team)?

**Comment by zachdaniel** [comment]
It's been quite difficult to reproduce, as it only happens on CI, and doesn't happen when only the dependencies that seem to be the cause are compiled (i.e ash+ spark). We have a simpler `mix.exs` that was able to reproduce the issuer here: https://github.com/pinetops/ash_compiler_crash/blob/3ca4fc4d8164f2c3c8065980c81e9768a2fd4ea6/mix.exs

But I imagine even that is far from a simple reproduction that we're looking for. We will try to simplify it further, but it takes a long time to try things out because we have to push to CI with some dependency or dependencies removed, and then run CI some random number of times (like 10+) to know if its affected or not.

I might ultimately need to find a way around it that involves just changing the way we define that function in hopes of resolving the issue. Do you know of any class of thing that could be the culprit based on the error message?

My suspicion is that it is in some way related to the way we are generating functions with interpolated lists of atoms being matched at compile time.

```elixir
for path <- paths do
  def generated_matcher(^path) do

  end

  defmodule Module do
     @path path
     @parent unquote(__MODULE__)
     def generated do
        @parent.generated_matcher(unquote(path))
     end
   end
end 
```

I haven't been able to reproduce just following this trail though.

**Comment by josevalim** [comment]
It is really hard to say. You can try using some of the flags in this article to get some additional pointers: https://dashbit.co/blog/how-to-debug-elixir-erlang-compiler-performance

I would try to narrow down why the compilation of that module is not deterministic in the first place. This could led to general improvements to Spark and Ash? For example, Elixir CI has a task to verify the bytecode does not change between `mix compile --force`. It is not always possible but checking this for some modules, such as `Authorizer`, could be a good starting point?

**Comment by zachdaniel** [comment]
The most likely cause of nondeterminism there is using `Kernel.ParallelCompiler.async(fun)` to generate many modules at the same time. I can try cutting a release that removes that (at the expense of longer compile times) to start.

**Comment by zachdaniel** [comment]
I've tried reproducing on a Mac but can't, but I've also tried reproducing using a Dockerfile. I haven't tried doing it on a machine running a non-virtualized ubuntu.

**Comment by zachdaniel** [comment]
So, removing all usage of `ParallelCompiler.async/1` appears to remove the issue. In all honesty, the optimization we were getting with it probably isn't worth the time investment of figuring out a smaller reproduction. Perhaps better to just wait until a clearer reproduction comes up, if ever. I'll close this for now until I can provide something more actionable.

**Comment by larshei** [comment]
Just ran into this as well.

> So, removing all usage of ParallelCompiler.async/1 appears to remove the issue. 

Can confirm the behaviour is inconsistent, I just reran the job and it built successfully.

Versions in the dockerfile

```dockerfile
ARG ELIXIR_VERSION=1.17.1
ARG OTP_VERSION=26.2.5
ARG DEBIAN_VERSION=bullseye-20240612-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
```

Ash Version: `{:hex, :ash, "3.2.4", "81842a319aa18e974c9e87905c2a30b42e5084f10bf2931a6709e26398eeb5a6", ...`

**Comment by larshei** [comment]
Just ran into this as well.

So, removing all usage of ParallelCompiler.async/1 appears to remove the issue.

Can confirm the behaviour is inconsistent, I just reran the job and it built successfully.

Runner info:

```
Current runner version: '2.317.0'
Operating System
  Ubuntu
  22.04.4
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20240730.2.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240730.2/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240730.2
Runner Image Provisioner
  2.0.374.1
```

Build container:

```docker
ARG ELIXIR_VERSION=1.17.1
ARG OTP_VERSION=26.2.5
ARG DEBIAN_VERSION=bullseye-20240612-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
```

Ash Version: `{:hex, :ash, "3.2.4", "81842a319aa18e974c9e87905c2a30b42e5084f10bf2931a6709e26398eeb5a6", ...`

**Comment by pinetops** [comment]
Yeh, to reliably produce the error with a simplified mix.lock (https://github.com/pinetops/ash_compiler_crash/tree/tests/remove_libs_4) I was running 40 CI jobs which would produce ~2 failed jobs.

There were times that in my real app it was failing more like 50 percent of the time though.

**Comment by zachdaniel** [comment]
For any Ash users coming here looking for a fix, update spark :)
