### ISSUE TITLE
`mix deps.get` behaviour contradicts doc

### ISSUE THREAD

**Issue by n-epifanov** [elixir-lang/elixir#13744]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit:ns]

Elixir 1.15.7 (compiled with Erlang/OTP 24)

### Operating system

Debian

### Current behavior

`mix deps.get` fetches locked hex package versions as expected and documented. But when it comes to Git repos it gets BROKEN: say you have `{:package git: <repo>, ref: "master"}`, `mix deps.get` would get your version unlocked and updated! Which makes NO SENSE, since doc says it "Gets all out of date dependencies, i.e. dependencies that are not available or have an invalid lock.", but actually what it does is `mix deps.update`!
"Updates the given dependencies.

The given dependencies and the projects they depend on will be unlocked and
updated to the latest version according to their version requirements."

### Expected behavior

This kind of behaviour makes no sense, is inconsistent, unintuitive, inconvenient and contradicts commands' documentation.
`mix deps.get` should fetch a locked revision as specified in a lock file as documented. `mix deps.update` should unlock and update revision to latest available according to `mix.exs` as it is documented as well.
I suggest it to be fixed as a bug in a minor release. I could make a PR (I think... I hope :D )

**Comment by josevalim** [comment]
Can you please provide an example? Git dependencies do respect the lock, as the docs say.

**Comment by n-epifanov** [comment]
Oops, my bad, some confusion happened, indeed it does. Sorry.
