### ISSUE TITLE
Path escaping for rebar shell command in deps.compile.ex

### ISSUE THREAD

**Issue by gdyr** [elixir-lang/elixir#13750]
https://github.com/elixir-lang/elixir/blob/99be673c3af91ead537a6dfdaeb3bea6e5e6c4d6/lib/mix/lib/mix/tasks/deps.compile.ex#L210

Compilation of Phoenix dependency "telemetry" using Rebar fails when parentheses (or presumably other shell-significant characters) appear in the project path.

This is due to inadequate escaping in `escape_path()`...
https://github.com/elixir-lang/elixir/blob/99be673c3af91ead537a6dfdaeb3bea6e5e6c4d6/lib/mix/lib/mix/tasks/deps.compile.ex#L225

... but could be avoided by using `System.cmd()/3` instead of `Mix.shell().cmd()`, to pass arguments without needing to escape them.

I've attempted a fix in https://github.com/elixir-lang/elixir/commit/806a8890699a3d529ce4e53d4d76681dc3353828, but this breaks the case where there is a space in the path to `rebar` - if I get more time, I'll continue investigating, but perhaps someone else may want to pick this up in the meantime?

**Comment by josevalim** [comment]
@gdyr can you please send a PR with your changes so far? I don't see why a space on the path to rebar would be a problem.

**Comment by josevalim** [comment]
Actually, the root problem is here: https://github.com/elixir-lang/elixir/blob/main/lib/mix/lib/mix/rebar.ex#L218

**Comment by josevalim** [comment]
Closing in favor of the PR: https://github.com/elixir-lang/elixir/pull/13751 Thanks!
