### ISSUE TITLE
Expose the language tokenizer

### ISSUE THREAD

**Issue by liamwhite** [elixir-lang/elixir#13759]
Currently, EEx has special casing for language constructs by directly using the language tokenizer to analyze code fragments. For example,
```eex
<%= cond do %>
  <% @condition_one -> %>
    1
  <% @condition_two -> %>
    2
  <% true -> %> 
    otherwise
<% end %>
```
None of the individual fragments within <%-%> tags can be parsed on their own with facilities such as `Code.string_to_quoted` because individually they do not make sense in the grammar.
```elixir
iex(1)> Code.string_to_quoted("cond do")
{:error,
 {[line: 1, column: 8],
  "missing terminator: end (for \"do\" starting at line 1)", ""}}
iex(2)> Code.string_to_quoted("@condition_one ->")
{:error, {[line: 1, column: 16], "syntax error before: ", "'->'"}}
iex(3)> Code.string_to_quoted("end")
{:error, {[line: 1, column: 1], {"unexpected reserved word: ", ""}, "end"}}
```
I have used cond and stabs as an example here because they are the primary case where this issue comes up.

When using the tokenizer directly to parse tokens, this doesn't pose a problem -- we can defer construction of the quoted expression until later. To use the EEx source code as an example, we can tokenize these individual fragments and get a token list:
```elixir
iex(1)> :elixir_tokenizer.tokenize(~c"cond do", 1, file: "eex", check_terminators: false)
{:ok, 1, 8, [], [{:do_identifier, {1, 1, ~c"cond"}, :cond}, {:do, {1, 6, nil}}]}
iex(2)> :elixir_tokenizer.tokenize(~c"@condition_one ->", 1, file: "eex", check_terminators: false)
{:ok, 1, 18, [],
 [
   {:at_op, {1, 1, nil}, :@},
   {:identifier, {1, 2, ~c"condition_one"}, :condition_one},
   {:stab_op, {1, 16, nil}, :->}
 ]}
iex(3)> :elixir_tokenizer.tokenize(~c"end", 1, file: "eex", check_terminators: false)
{:ok, 1, 4, [], [end: {1, 1, nil}]}
```
As it stands, only EEx is designed to take advantage of this facility, because it is baked into the language and does not have to concern itself with any issues with the API breaking when elixir_tokenizer changes. A stable, documented module Tokenizer or Code.Tokenizer, which allows converting strings to lists of tokens, and lists of tokens to strings, would improve the ability to [work with other Elixir-based template languages like HEEx](https://github.com/phoenixframework/phoenix_live_view/pull/3231).

**Comment by josevalim** [comment]
We have no plans to expose the tokenizer, because it is pretty much an implementation concern. It would be acceptable to expose a function in Code.Fragment or similar that exposes the information the engine cares about, but the whole tokenizer is not work we plan to undertake right now. You can also look at `lib_elixir` if you want a bit more of stability across Elixir version changes: https://elixirforum.com/t/working-on-lib-elixir-elixir-core-modules-as-a-library/65316 (basically an automated way to vendor a private module).
