### ISSUE TITLE
EEx closing tag inside string has higher precedence than string

### ISSUE THREAD

**Issue by liamwhite** [elixir-lang/elixir#13760]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Elixir 1.17.0 (compiled with Erlang/OTP 27)

### Operating system

Linux

### Current behavior

EEx parses `%>`s encountered inside other language grammar. This means that
```elixir
iex(1)> EEx.eval_string(~s|<%= "hello world" %>|)
"hello world"
```
is fine, but
```elixir
iex(2)> EEx.eval_string(~s|<%= "hello %> world" %>|)
```
```
** (TokenMissingError) nofile:1:12: missing terminator: " (for string starting at line 1)
    |
  1 |  "hello 
    |         ^
    lib/eex/compiler.ex:332: EEx.Compiler.generate_buffer/4
    lib/eex.ex:276: EEx.eval_string/3
    iex:2: (file)
```
is not.

### Expected behavior

EEx closing tags should ideally be required to be outside of string boundaries.

**Comment by josevalim** [comment]
EEx is a preprocessor, so this is working as intended. We only parse and evaluate Elixir expressions once they are extracted out.
