### ISSUE TITLE
`mix format` on lines exactly 1 character longer than the limit

### ISSUE THREAD

**Issue by dmarkow** [elixir-lang/elixir#13775]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.2 (compiled with Erlang/OTP 27)

### Operating system

macOS 14.6.1

### Current behavior

Given this code, I expected it to break as the comments describe. The first long line is within the limit so it shouldn't wrap, the second and third lines are 1 longer than the limit so both should wrap, and the last one is 2 longer than the limit so it should wrap.

```elixir
defmodule FormatterIssue do
  def test do
    comment = "The following line is 98 characters and should not wrap or add a space before it"
    do_something(%{foo: "bar bar bar bar bar bar bar bar bar bar bar bar", blah: "bla blah blah"})

    comment = "The following line is 99 characters and should wrap and add a space"
    x = %{foo: "bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar", blah: "blah blah bl"}

    comment = "This one too, but it only adds the space and doesn't wrap?"
    do_something(%{foo: "bar bar bar bar bar bar bar bar bar bar bar bar", blah: "blah blah blah"})

    comment = "Once it's 100 characters, 2 past the limit, it then wraps..."
    do_something(%{foo: "bar bar bar bar bar bar bar bar bar bar bar bar", blah: "blah blah blah."})
  end
end
```

Instead, it formats like this. Specifically, the 3rd pair of statements puts a space between the `comment = ...` line and the `do_something/1` call as if it's going to wrap the `do_something/1` call, but it doesn't actually wrap it. So all the formatter did was add a blank line above it. But if the function call hits 100 characters long, 2 past the 98 limit, then it wraps as expected.

```elixir
defmodule FormatterIssue do
  def test do
    comment = "The following line is 98 characters and should not wrap or add a space before it"
    do_something(%{foo: "bar bar bar bar bar bar bar bar bar bar bar bar", blah: "bla blah blah"})

    comment = "The following line is 99 characters and should wrap and add a space"

    x = %{
      foo: "bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar",
      blah: "blah blah bl"
    }

    comment = "This one too, but it only adds the space and doesn't wrap?"

    do_something(%{foo: "bar bar bar bar bar bar bar bar bar bar bar bar", blah: "blah blah blah"})

    comment = "Once it's 100 characters, 2 past the limit, it then wraps..."

    do_something(%{
      foo: "bar bar bar bar bar bar bar bar bar bar bar bar",
      blah: "blah blah blah."
    })
  end
end
```

### Expected behavior

Both the `do_something/1` calls should wrap the same since they're both past the limit if 98.

```elixir
defmodule FormatterIssue do
  def test do
    comment = "The following line is 98 characters and should not wrap or add a space before it"
    do_something(%{foo: "bar bar bar bar bar bar bar bar bar bar bar bar", blah: "bla blah blah"})

    comment = "The following line is 99 characters and should wrap and add a space"

    x = %{
      foo: "bar bar bar bar bar bar bar bar bar bar bar bar bar bar bar",
      blah: "blah blah bl"
    }

    comment = "This one too, but it only adds the space and doesn't wrap?"

    do_something(%{
      foo: "bar bar bar bar bar bar bar bar bar bar bar bar",
      blah: "blah blah blah"
    })

    comment = "Once it's 100 characters, 2 past the limit, it then wraps..."

    do_something(%{
      foo: "bar bar bar bar bar bar bar bar bar bar bar bar",
      blah: "blah blah blah."
    })
  end
end
```

**Comment by josevalim** [comment]
Thank you for the detailed issue report.

The way the formatter works is that it breaks, if it can find a place to break. In particular, the a map (or keyword or anonymous function) is the last argument of a function, we try to break it like this:

```
foo(%{
  key: ...
```

while most formatters would do this:

```
foo(
  %{
    key: ...
```

And this changes how the formatter consider when things can break.

In any case, there is definitely a bug here. I am only explaining why it can happen and why sometimes it doesn't break, even if above the limit. :)

**Comment by sabiwara** [comment]
I tried to look into it but I've been struggling, will come back to it later. Noting my findings so far in case it helps:

Minimal example (length is 7, but breaks at 5, not 6):

```elixir
Code.format_string!("f(%{x})", line_length: 6) |> IO.puts()
# f(%{x})
```

Corresponding algebra:

```elixir
{:doc_group,
 {:doc_cons, {:doc_string, "f", 1},
  {:doc_fits,
   {:doc_group,
    {:doc_cons,
     {:doc_cons, {:doc_nest, {:doc_cons, "(", {:doc_break, "", :strict}}, 2, :break},
      {:doc_cons,
       {:doc_cons,
        {:doc_nest,
         {:doc_fits,
          {:doc_group,
           {:doc_cons,
            {:doc_nest,
             {:doc_cons, {:doc_cons, {:doc_cons, "%", :doc_nil}, "{"},
              {:doc_cons, {:doc_break, "", :strict}, {:doc_group, {:doc_string, "x", 1}, :self}}},
             2, :break}, {:doc_cons, {:doc_break, "", :strict}, "}"}}, :self}, :enabled}, 2,
         :break}, {:doc_break, "", :strict}}, ")"}}, :doc_nil}, :self}, :disabled}}, :self}
```

[This `fits?` check](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/inspect/algebra.ex#L1107) happens several times:
- a first time with offset `0` on the whole function call, returns `false`
- it later gets called at offset `2` on a nested `:doc_group` which just contains the map but not the last `")"`, and returns `true`, hence the offset of 1

**Comment by josevalim** [comment]
Closing in favor of the PR.
