### ISSUE TITLE
Subsequent WHEN keywords wipeout previous WHEN lists without any warning or error

### ISSUE THREAD

**Issue by krainboltgreene** [elixir-lang/elixir#13773]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.1 (compiled with Erlang/OTP 27)

### Operating system

MacOS 13.6.3 (22G436)

### Current behavior

```
defmodule X do
  def y(a, b, c) when is_nil(a) and is_nil(b) when is_integer(c),
    do: [a, b, c]
end
```

```
iex(2)> X.y(nil, nil, 1)
[nil, nil, 1]
iex(3)> X.y(nil, 1, 1)
[nil, 1, 1]
iex(4)> X.y(1, 1, 1)
[1, 1, 1]
iex(5)> X.y(1, 1, nil)
```

### Expected behavior

I expected elixir to tell me that the when statement I wrote wasn't going to be used or (better yet) a compilation error.

**Comment by krainboltgreene** [comment]
I showed this to two people and neither of them (my self as well) realized what was wrong for about 5m, we're all very well versed in Elixir. The issue is that there are two `when` statements.

**Comment by josevalim** [comment]
Documented here: https://hexdocs.pm/elixir/patterns-and-guards.html#multiple-guards-in-the-same-clause

**Comment by krainboltgreene** [comment]
Yeah, thanks, we just figured that out in the elixir discord. Bleh, man that's weird as hell.
