### ISSUE TITLE
Lack of documentation when Logger.Formatter drops metadata due to unmeet printable conditions

### ISSUE THREAD

**Issue by Krapaince** [elixir-lang/elixir#13772]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 26 [erts-14.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Elixir 1.17.2 (compiled with Erlang/OTP 26)
```

### Operating system

any

### Current behavior

The `Logger.Formatter` silently removes metadata that doesn't meet [printable condition](https://github.com/elixir-lang/elixir/blob/v1.17/lib/logger/lib/logger/formatter.ex#L468-L531).

### Expected behavior

There is nothing wrong with this behavior, but following my experience of why my metadata wasn't printed:

> I did multiple back and forth between my code and the documentation to find out if I had done something  wrong in the configuration, or the `Logger.metadata/1` but didn't found anything.
> I end up in searching on the elixir forum to find this [thread](https://elixirforum.com/t/how-can-i-see-log-metadata-in-dev/63159/24) which lead me to link mentioned in the `Current behavior` section above.

I wonder if we could add to the `Logger.Formatter`'s documentation the conditions that a metadata value must meet in order to be printed. In [1.17.2 the `Metadata` section](https://hexdocs.pm/logger/1.17.2/Logger.html#module-metadata) is kind of empty on that matter

![image](https://github.com/user-attachments/assets/fa9c83f0-b50d-4a39-b052-87d0f5e8595f)

and so is the [`Logger`'s  Metadata section](https://hexdocs.pm/logger/1.17.2/Logger.html#module-metadata) but I don't know if it should be putted there over the `Logger.Formatter` page.

**Comment by josevalim** [comment]
Hi @Krapaince! Do you want to submit a draft PR so we can iterate on it? No worries about the place, we can work on it together later on. :)

**Comment by Krapaince** [comment]
Sure I'll give it a try.

**Comment by whatyouhide** [comment]
Closing in favor of the PR!
