### ISSUE TITLE
`--repeat-until-failure` doesn't re-run `test/test_helper.exs`

### ISSUE THREAD

**Issue by harrisi** [elixir-lang/elixir#13788]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.17.2 (compiled with Erlang/OTP 27)
```

### Operating system

macOS 14.5

### Current behavior

Running `mix test --repeat-until-failure` doesn't re-run `test/test_helper.exs`. This is an issue for a library like [Mimic](https://github.com/edgurgel/mimic), since that is where it copies modules for mocking. This means that after the first run, the modules are reloaded and tests fail.

### Expected behavior

For mimic's case, it seems like re-running would be nice. However, part of `test/test_helper.exs` is calling `ExUnit.start/1`, which is not idempotent. So it doesn't really make sense to run it with the minimal (as per [the documentation](https://hexdocs.pm/ex_unit/ExUnit.html#module-integration-with-mix)). I'm not quite sure what the solution would be.

There is an [`after_suite/1`](https://hexdocs.pm/ex_unit/ExUnit.html#after_suite/1), but there's not a similar function for re-ran tests. `test/test_helper.exs` itself is basically a `before_suite/0`, so adding that function wouldn't necessarily make sense.

Alternatively, `ExUnit.start/1` could be made idempotent for rerunning tests by checking if `ExUnit.Supervisor` has already been started? Or maybe a separate `test/test_helper_reruns.exs` (or something) could be added which would be run when `--repeat-until-failure` is used.

I'm not sure if there's another way around this issue with how things exist now, but as far as I can tell there's not a way to run something before repeating the test suite, and after modules are reloaded.

**Comment by josevalim** [comment]
I am almost sure modules are not reloaded between runs in repeat until failure. The goal is exactly to not reload so we can repeat quickly. Maybe there is something else going on here?

**Comment by harrisi** [comment]
Ah, I think I'm wrong, slightly. The modules aren't reloaded, it's just that the list of loaded modules is "reset", as far as I can tell.

[`ExUnit.maybe_repeated_run/4`](https://github.com/elixir-lang/elixir/blob/main/lib/ex_unit/lib/ex_unit.ex#L510) ultimately [updates the server state](https://github.com/elixir-lang/elixir/blob/main/lib/ex_unit/lib/ex_unit/server.ex#L76) to the modules that were loaded on first run, I believe.

You may be able to grok some context from the [original issue](https://github.com/edgurgel/mimic/issues/63) that the modules on reload don't include the copied modules. This very well may be an instance of mimic not copying modules correctly, but I'm not sure how it should handle this situation.

**Comment by josevalim** [comment]
That’s simply setting some internal GenServer state. There is no copying or changes to the modules state themselves. I understand there is a Mimic issue but we need more information on how exactly that would be a bug in Elixir. Then we will gladly provide guidance. The current report does not give us much information without us also having to go debug mimic.

**Comment by harrisi** [comment]
I'll look into it more later. Sorry, I thought I had a better understanding of the problem. 

Just to be explicit, I don't have anything to do with mimic. It's just how I happened to find out about the `--repeat-until-failure` option.

**Comment by harrisi** [comment]
I found the issue in Mimic. Apologies for the non-issue :(

(For reference, it's explicitly reseting copied modules with `ExUnit.after_suite/1`.)
