### ISSUE TITLE
function 'to_map' in defmodule Tuple

### ISSUE THREAD

**Issue by moacirbishopcamata** [elixir-lang/elixir#13787]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.17.2 (compiled with Erlang/OTP 27)

### Operating system

Windows 10

### Current behavior

Excellent work to all.

I would like to know if it is possible to insert the "to_map" function in the "Tuple" module.

I needed to create such a method in a module to 'login' in Microsoft AD in LDAP with return in json by encode.

def to_map(tuple) when is_tuple(tuple) do
{key, value} = tuple
Enum.into([{key, value}], %{})
end

Sorry for the horrible code, I'm a junior in Elixir but I'm loving it.

I also don't know if it is possible by other methods, if you show me the way I will be very grateful.

Thank you for your attention.

### Expected behavior

Not existe method.

**Comment by whatyouhide** [comment]
Hi @moacirbishopcamata, we use the [elixir-lang-core mailing list](https://groups.google.com/g/elixir-lang-core) for feature discussions, so I would suggest proposing this feature there—the issue tracker is reserved for tracking bugs.

In general, you can achieve what you want even with just `Map.new([tuple])`, so I don't think this might be worth it to have in the stdlib 🙃
