### ISSUE TITLE
Sporadic `error while checking types` failures during `mix test`

### ISSUE THREAD

**Issue by pedromss** [elixir-lang/elixir#13805]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.17.2 (compiled with Erlang/OTP 25)

### Operating system

MacOS Sonoma 14.6

### Current behavior

 I've was updating to 1.17 but started getting some errors which don't happen everytime:

```elixir
** (EXIT from #PID<0.94.0>) an exception was raised:
    ** (RuntimeError) found error while checking types for <module>.__ex_unit_setup_0/1:

** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Flow, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, <internal_module>, Range, Stream
The exception happened while checking this code:

defp __ex_unit_setup_0(_) do
  x = %X{...}
  y = %{...}

  {:ok, x: x, y: y}
end
```

If I attempt to run the tests again it might not fail at all and tests run or it might fail in another test but with the same kind of code.

This doesn't happen when running the application, only with `mix test` although the code the error points to varies, for example sometimes it points to custom `setup` functions like:

```elixir
defp setup_...(context) do
  x = ...
  Map.put(context, :x, x)
end
```

### Expected behavior

Tests should compile and run

**Comment by jeanklingler** [comment]
This looks very similar to https://github.com/elixir-lang/elixir/issues/13770.
Are you using Mimic by any chance?

**Comment by pedromss** [comment]
Running a few more times doesn't yield the same error so it indeed seems the same issue.

Closing, thank you.
