### ISSUE TITLE
Error: beam/jit/beam_jit_common.cpp:89:codegen() Assertion failed: !err && "Could not resolve all links" when using EEx

### ISSUE THREAD

**Issue by jeremyowensboggs** [elixir-lang/elixir#13824]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.17.2 (compiled with Erlang/OTP 27)

### Operating system

Mac OSX

### Current behavior

Using OTP 27
While compiling a module with:
```
  EEx.function_from_file(:defp, :forecast, @forecast_path, [:start_date])
```
where the path pointed to by @forecast_path is a file with over 600 (approx) lines
The compile fails with:
```
beam/jit/beam_jit_common.cpp:89:codegen() Assertion failed: !err && "Could not resolve all links"
```

Full example here: https://github.com/jeremyowensboggs/jit_error_example

### Expected behavior

Compile should either succeed, or fail with an actionable error.

**Comment by josevalim** [comment]
Thank you. This is an Erlang bug and it should not happen. I will isolate it and report it upstream. :)

**Comment by josevalim** [comment]
This seems to work fine on 27.0. I will install 27.0.1 when I back home and try again.

**Comment by josevalim** [comment]
Reported here: https://github.com/erlang/otp/issues/8815
