### ISSUE TITLE
[Documentation] for the System time_unit() not showing the units day, hour, minute

### ISSUE THREAD

**Issue by marine-raimbault** [elixir-lang/elixir#13822]
### Elixir and Erlang/OTP versions

Elixir 1.17.2 (documentation in the https://hexdocs.pm/)

### Operating system

Browser

### Current behavior

In the documentation, it is not written [there](https://hexdocs.pm/elixir/1.17.2/System.html#t:time_unit/0)  that :day, :hour, :minute are also accepted units of time

Here a screenshot of the documentation:

![image](https://github.com/user-attachments/assets/139eff87-24c1-4e9c-a877-25fd167f68e3)

### Expected behavior

I would expect theses units to be added to it like that:

@type time_unit() ::
 :day | :hour | :minute | :second | :millisecond | :microsecond | :nanosecond |pos_integer()

https://hexdocs.pm/elixir/1.17.2/System.html#t:time_unit/0

**Comment by marine-raimbault** [comment]
Hi I new here and this is my first "issue", I read the code of conduct and I'm open to feedback if that documentation thing does not belong here :) I'm also open  to fix it :)

**Comment by whatyouhide** [comment]
@marine-raimbault hey, welcome then 🙃 `System.time_unit` is not meant to represent all possible time units, just the ones supported by functions like `System.convert_time_unit/3`. Days, for example, require calendars and timezone knowledge. Check out the `Calendar`, `Date`, `DateTime` modules for that kind of stuff. Thanks!
