### ISSUE TITLE
Typo in `Supervisor`'s  `typedoc` for `init_option()`

### ISSUE THREAD

**Issue by VasiliyS** [elixir-lang/elixir#13864]
### Elixir and Erlang/OTP versions

1.17.3

### Operating system

all

### Current behavior

Documentation says: (https://github.com/elixir-lang/elixir/blob/78f63d08313677a680868685701ae79a2459dcc1/lib/elixir/lib/supervisor.ex#L598)

### Expected behavior

It should be referring `init/2` -  e.g. `Supervisor.init(children, options)`, not the callback (which takes an arbitrary `init_arg`, passed from `start_link/3`).

**Comment by josevalim** [comment]
You are right! Would you like to send a PR? :)
