### ISSUE TITLE
Lines not reported as covered when they should be

### ISSUE THREAD

**Issue by albertored** [elixir-lang/elixir#13863]
### Elixir and Erlang/OTP versions

```
Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:128:8] [ds:128:8:10] [async-threads:1] [jit:ns]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

```
(erlang 27.1, both elixir and erlang installed with asdf)

### Operating system

Linux

### Current behavior

```elixir
defmodule MyModule do
  def fun(arg1, "bar" <> _) when arg1 in [:arg1, :arg2] do
  end

  def fun(:arg3, arg2) do
    with 12 <- Enum.sum([10, 2]) do
      res = "res-#{arg2}"
      res
    end
  end
end

defmodule MyModuleTest do
  use ExUnit.Case

  test "cover test" do
    assert MyModule.fun(:arg3, "foo") == "res-foo"
  end
end
```

Running the test above I expect to completely cover the second clause of my `MyModule.fun/2` but instead the result of

```
mix test --cover --export-coverage cover
mix test.coverage
```

shows no line covered. The test is correctly passing so we cover for sure that clause.

This is a minimal (not) working example extrapolated form a large code base. Almost every change to this code makes the cover correct again, in particular:
* removing the first clause of  `MyModule.fun/2`
* inverting the 2 clauses of  `MyModule.fun/2`
* removing the `with` in the second clause
* removing the second argument from `MyModule.fun/2`
* changing the first clause to `def fun(arg1, _) when arg1 in [:arg1, :arg2]`

With erlang 26 and elixir 1.16 the behavior was correct. I can try with mixed versions (1.16 with 27 and/or 1.17 with 26) to better understand where the bug was introduced.

### Expected behavior

All the body of the second clause of my function should be reported as covered

**Comment by josevalim** [comment]
Thanks! This is a great report. If you can try mixed versions, that would be great, as that would be my first step debugging it. :)

**Comment by albertored** [comment]
Just tried:
* Erlang 27 Elixir 16 bug
* Erlang 26 Elixir 17 no bug

So the problem seems to be more on Erlang side.

I can try to refresh my Erlang skills and run a similar example in plain Erlang and. if the problem still occurs, open an issue there

**Comment by albertored** [comment]
It happens indeed also in pure Erlang so this may be closed

**Comment by josevalim** [comment]
Thank you for the follow up!
