### ISSUE TITLE
Macro.to_string truncates AST with large maps (> 50 keys)

### ISSUE THREAD

**Issue by mruoss** [elixir-lang/elixir#13875]
### Elixir and Erlang/OTP versions

* OTP 27
* Elixir 1.17.3

### Operating system

OSX

### Current behavior

This is very similar to https://github.com/elixir-lang/elixir/issues/7545 but for maps. When a map contains more than 50 items, 

Here's the code (note the `...` at the end):

```elixir
iex> (quote do: unquote(Map.new(1..51, &{&1, "value"}))) |> Macro.to_string()
"%{39 => \"value\", 45 => \"value\", 50 => \"value\", 22 => \"value\", 51 => \"value\", 26 => \"value\", 47 => \"value\", 27 => \"value\", 5 => \"value\", 21 => \"value\", 30 => \"value\", 16 => \"value\", 3 => \"value\", 33 => \"value\", 14 => \"value\", 40 => \"value\", 37 => \"value\", 24 => \"value\", 17 => \"value\", 48 => \"value\", 11 => \"value\", 43 => \"value\", 6 => \"value\", 20 => \"value\", 28 => \"value\", 25 => \"value\", 1 => \"value\", 32 => \"value\", 36 => \"value\", 35 => \"value\", 15 => \"value\", 49 => \"value\", 9 => \"value\", 23 => \"value\", 10 => \"value\", 44 => \"value\", 8 => \"value\", 31 => \"value\", 38 => \"value\", 7 => \"value\", 2 => \"value\", 42 => \"value\", 13 => \"value\", 29 => \"value\", 41 => \"value\", 19 => \"value\", 12 => \"value\", 46 => \"value\", 34 => \"value\", 4 => \"value\", ...}"
```

Discussion on the forum: https://elixirforum.com/t/how-to-increase-printable-limit-from-macro-to-string/13613/3

### Expected behavior

Expecting the resulting string to represent the entire map.

**Comment by josevalim** [comment]
The difference here is that maps are not valid AST. We fallback to inspect in Macro.to_string for convenience, because the goal of the macro is mostly debugging, but if you returned that from a macro, Elixir would raise accordingly. In any case, it won't be formatted accordingly.  The correct fix is to call `Macro.escape`or build the correct Map ast, as shown in the result of `quote do: %{1 => 2, foo: :bar}`

**Comment by mruoss** [comment]
Oooh right, I remember now. Thanks for clarifying.
