### ISSUE TITLE
Elixir hex doc cannot select the version

### ISSUE THREAD

**Issue by wingyplus** [elixir-lang/elixir#13892]
### Elixir and Erlang/OTP versions

Elixir 1.17.3 OTP 27

### Operating system

Windows

### Current behavior

I'm seeing the document on https://hexdocs.pm/elixir/1.17.3/Kernel.html and realize that the Elixir documentation cannot change a version.

![Screenshot 2024-10-09 230640](https://github.com/user-attachments/assets/5b5df791-3823-495f-ad6e-ef11c860fb0a)

### Expected behavior

The Elixir should change the ability to change the version like before.

**Comment by wingyplus** [comment]
Is the regression from the workflow changes (https://github.com/elixir-lang/elixir/commit/9d5af3fe320fcdfce36af7f0b76ee573896c9adf, introduced by me)?

**Comment by josevalim** [comment]
This URL is returning empty version nodes: https://hexdocs.pm/elixir/1.17.3/docs_config.js

So something is going wrong when we build it.

**Comment by josevalim** [comment]
The script works on my machine:

```
~/OSS/elixir[main]$ elixir lib/elixir/scripts/docs_config.exs elixir
~/OSS/elixir[main]$ cat doc/elixir/docs_config.js
```

Did you change the cloning mechanism from CI/Github Actions to do a shallow clone and not include tags?

**Comment by wingyplus** [comment]
Thank you @josevalim for pointing out.

Judge from the action https://github.com/elixir-lang/elixir/actions/runs/11235937746/job/31234979030. It seems that the checkout action never fetches the tags, cause doc is missing the version selection. 

Will find the time to fix this today. 👍

**Comment by josevalim** [comment]
No, we don't include it on purpose.

**Comment by wingyplus** [comment]
Noted. 🙏
