### ISSUE TITLE
Unit tests with deterministic build enable fail.

### ISSUE THREAD

**Issue by joaohf** [elixir-lang/elixir#13913]
### Elixir and Erlang/OTP versions

Erlang/OTP 27
Elixir main or Elixir 1.17

### Operating system

Ubuntu LTS 24.04.1

### Current behavior

When running elixir unit tests from elixir source code, I got two different behaviors when setting deterministic build flag:

## With deterministic

```
export ERL_COMPILER_OPTIONS="deterministic"
joaohf@porco:~/work/opensource/elixir$ make test
make[1]: Entering directory '/home/joaohf/work/opensource/elixir'
make[1]: Nothing to be done for 'unicode'.
make[1]: Leaving directory '/home/joaohf/work/opensource/elixir'
==> elixir (compile)
make[1]: Entering directory '/home/joaohf/work/opensource/elixir'
make[1]: Nothing to be done for 'app'.
make[1]: Leaving directory '/home/joaohf/work/opensource/elixir'
==> elixir (eunit)
  All 126 tests passed.

==> elixir (ex_unit)

== Compilation error in file test/elixir/atom_test.exs ==
** (RuntimeError) Atom does not have compile-time source information
    (ex_unit 1.18.0-dev) lib/ex_unit/doc_test.ex:280: ExUnit.DocTest.__file__/1
    test/elixir/atom_test.exs:6: (module)
    test/elixir/atom_test.exs:3: (file)
make: *** [Makefile:279: test_stdlib] Error 1
```

Indeed, there is no :source keyword:

```
iex(1)> Logger.Formatter.module_info(:compile)
[version: ~c"8.5.2"]
```

That is expected for  deterministic flag. But I was not expecting test fails.

## Without deterministic build

```
unset ERL_COMPILER_OPTIONS
make clean
make test
....
```

All tests passed.

```
iex(1)> System.module_info(:compile)
[
  version: ~c"8.5.2",
  options: [:no_spawn_compiler_process, :from_core, :no_core_prepare,
   :no_auto_import],
  source: ~c"/build/tmp/work/core2-64-poky-linux/elixir/1.17.1/git/lib/elixir/lib/system.ex"
]
```

As we can check, :source is there. And the tests were Ok.

### Expected behavior

I expected all tests run with and without deterministic build enabled.

There is one issue (https://github.com/elixir-lang/elixir/issues/8986) in Erlang/OTP for deterministic build that could improve things. But I don't have any suggestion about how (and if it would be feasible) to fix elixir unit tests with deterministic builds.

**Comment by josevalim** [comment]
There are other flags you can set that will make it so Elixir build fails. For example, if you discard debug info or line numbers, then our tests that assert on it will fail. I don't think it is realistic to expect that all of our tests will work under all possible compiler flags. Thank you.
