### ISSUE TITLE
Reraising Erlang errors produces `UndefinedFunctionError`

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#13926]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.17.2 (compiled with Erlang/OTP 27)

### Operating system

macOS Big Sur 11.7.10

### Current behavior

```elixir
try do
  1 + "hello"
catch
  :error, error ->
    reraise error, __STACKTRACE__
end
```

Produces

```
** (UndefinedFunctionError) function :badarith.exception/1 is undefined (module :badarith is not available)
    :badarith.exception([])
```

### Expected behavior

Reraises the error

**Comment by josevalim** [comment]
Hi @fertapric! 👋 

That's correct. When you catch, you are catching any term, they are not converted to exceptions. You can `reraise` exceptions that have been _rescued_.
