### ISSUE TITLE
Different pattern match behavior between elixir and erlang

### ISSUE THREAD

**Issue by falood** [elixir-lang/elixir#13931]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.1 (compiled with Erlang/OTP 27)

### Operating system

Macos arm64 arm Darwin

### Current behavior

```bash
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Interactive Elixir (1.17.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> %{x => y} = %{:key => x} = %{:key => :a, :a => :b}
error: cannot use variable x as map key inside a pattern. Map keys in patterns can only be literals (such as atoms, strings, tuples, and the like) or an existing variable matched with the pin operator (such as ^some_var)
└─ iex:1

** (CompileError) cannot compile code (errors have been logged)

iex(1)> %{^x => y} = %{:key => x} = %{:key => :a, :a => :b}
error: undefined variable ^x. No variable "x" has been defined before the current pattern
└─ iex:1
iex(1)> %{^x => y} = %{:key => x} = %{:key => :a, :a => :b}
** (CompileError) cannot compile code (errors have been logged)
```

### Expected behavior

```bash
Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Eshell V15.0 (press Ctrl+G to abort, type help(). for help)
1> #{X := Y} = #{key := X} = #{key => a, a => b}.
#{a => b,key => a}
2> X.
a
3> Y.
b
```

**Comment by josevalim** [comment]
Erlang/OTP 26 added this feature, since we support Erlang/OTP 25, we cannot add it yet. But it is still unclear if we will add said capabilities. You can follow it on #11985.

**Comment by josevalim** [comment]
To add to my response above, the main reason why we may not want to go down this path, is because it can become very confusing with the pin operator:

```elixir
x = 123
%{foo: ^x} = %{bar: x} = %{foo: 123, bar: 456}
```

Should the code above work or fail? It works today, but it won't work if we introduce the proposed feature. I think it is easier to reason if we consider all `=` as one, instead of right to left.

**Comment by falood** [comment]
Thank you for taking the time to discuss this matter ✨

I wanted to clarify my original requirement: 
I was trying to achieve pattern matching where I could get the value `1` from `%{:key => :m, :m => 1, :n => 2}` and the value `2` from `%{:key => :n, :m => 1, :n => 2}`. 
However this pattern isn't supported in either Elixir or Erlang, which led me to split it into two expressions.

Your explanation helped me understand the implementation challenges. While implementing `%{:key => key, key => value} `might also be complex, I think this pattern would have less ambiguity compared to `%{foo: ^x} = %{bar: x} = %{}`.

Thank you for helping me understand these constraints better!"
