### ISSUE TITLE
False positive unused alias warning

### ISSUE THREAD

**Issue by sl1depengwyn** [elixir-lang/elixir#13975]
### Elixir and Erlang/OTP versions

```
elixir -v
Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.17.3 (compiled with Erlang/OTP 27)
```

### Operating system

macOS 15.0.1

### Current behavior

Simple reproduction repo: https://github.com/sl1depengwyn/elixir-unused-alias-example
Compiler warns about unused alias, however alias should not be compiled thus should not trigger warning.
```
$ export FOO=
$ mix compile --force
Compiling 2 files (.ex)
Generated unused_alias_example app

$ unset FOO
$ mix compile --force
Compiling 2 files (.ex)
    warning: unused alias Bar
    │
  4 │     alias Foo.Bar
    │     ~
    │
    └─ lib/unused_alias_example.ex:4:5

Generated unused_alias_example app
```

### Expected behavior

No warning regardless env var value

**Comment by sl1depengwyn** [comment]
Thank you so much for blazing fast answer and nice workaround!

**Comment by josevalim** [comment]
I got an idea on how to fix it. :D I will try it when I am back home!
