### ISSUE TITLE
Potential false positive warning about invalid AST

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#13976]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.18.0-dev (0e052fd) (compiled with Erlang/OTP 27)

### Operating system

Apple M1 Pro, macOS Sequoia 15.1

### Current behavior

Create a new project with `mix new cldring`.
Add deps:
```
      {:ex_cldr, "~> 2.20"},
      {:ex_cldr_numbers, "~> 2.33"}
```
and get them with `mix deps.get`.
Define a new module with:
```elixir
defmodule Cldring.Cldr do
  use Cldr,
    locales: ["pl", "en"],
    default_locale: "pl",
    providers: [Cldr.Number],
    otp_app: :cldring
end
```

Compilation fails with:`
```
% mix compile
Compiling 2 files (.ex)

21:31:19.444 [info] Downloaded locale :pl
Generating Cldring.Cldr for 3 locales named [:en, :pl, :und] with a default locale named :pl

== Compilation error in file lib/cldring/cldr.ex ==
** (ArgumentError) tried to unquote invalid AST: %Cldr.Config{default_locale: :pl, locales: [:en, :pl, :und], add_fallback_locales: false, backend: Cldring.Cldr, gettext: nil, data_dir: "/Users/michal/work/hm/cldring/_build/dev/lib/cldring/priv/cldr", providers: [Cldr.Number], precompile_number_formats: [], precompile_transliterations: [], precompile_date_time_formats: [], precompile_interval_formats: [], default_currency_format: nil, otp_app: :cldring, generate_docs: true, suppress_warnings: false, message_formats: %{}, force_locale_download: false, https_proxy: nil}
Did you forget to escape term using Macro.escape/1?
    (elixir 1.18.0-dev) src/elixir_quote.erl:542: :elixir_quote.argument_error/1
    (ex_cldr_numbers 2.33.3) lib/cldr/number/backend/decimal_formatter.ex:78: Cldr.Number.Backend.Decimal.Formatter.define_number_module/1
    (ex_cldr_numbers 2.33.3) lib/cldr/number/backend/compiler.ex:11: Cldr.Number.Backend.define_number_modules/1
    (ex_cldr 2.40.1) lib/cldr/config/config.ex:2658: anonymous fn/3 in Cldr.Config.define_provider_modules/1
    (elixir 1.18.0-dev) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_cldr 2.40.1) lib/cldr/config/config.ex:2656: Cldr.Config.define_provider_modules/1
    (ex_cldr 2.40.1) expanding macro: Cldr.Backend.Compiler.__before_compile__/1
    lib/cldring/cldr.ex:1: Cldring.Cldr (module)
```

I thought maybe this is a previously undetected issue in the dependency code, and we need to call `Macro.escape` at the given line at `deps/ex_cldr_numbers/lib/cldr/number/backend/decimal_formatter.ex`, but after switching to `{:ex_cldr_numbers, path: "deps/ex_cldr_numbers"}`  and doing that as the error suggested I'm seeing:

```
% mix compile
==> ex_cldr_numbers
Compiling 4 files (.erl)
Compiling 26 files (.ex)
Generated ex_cldr_numbers app
==> cldring
Compiling 2 files (.ex)
Generating Cldring.Cldr for 3 locales named [:en, :pl, :und] with a default locale named :pl

== Compilation error in file lib/cldring/cldr.ex ==
** (KeyError) key :suppress_warnings not found in: {:%{}, [line: 1],
 [
   __struct__: Cldr.Config,
   add_fallback_locales: false,
   backend: Cldring.Cldr,
   data_dir: "/Users/michal/work/hm/cldring/_build/dev/lib/cldring/priv/cldr",
   default_currency_format: nil,
   default_locale: :pl,
   force_locale_download: false,
   generate_docs: true,
   gettext: nil,
   https_proxy: nil,
   locales: [:en, :pl, :und],
   message_formats: {:%{}, [line: 1], []},
   otp_app: :cldring,
   precompile_date_time_formats: [],
   precompile_interval_formats: [],
   precompile_number_formats: [],
   precompile_transliterations: [],
   providers: [Cldr.Number],
   suppress_warnings: false
 ]}

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (ex_cldr_numbers 2.33.3) expanding macro: Cldr.Number.Format.Compiler.maybe_log_compile_warning/3
    /Users/michal/work/hm/cldring/lib/cldring/cldr.ex:1: (file)
    (ex_cldr 2.40.1) /Users/michal/work/hm/cldring/lib/cldring/cldr.ex:1: Cldr.Backend.Compiler.__before_compile__/1
```

because this injected/generated code calls another macro :exploding_head:

### Expected behavior

No compilation error, I think?

**Comment by michallepicki** [comment]
OK, makes sense that the library was doing something illegal already, since `unquote` docs clearly warn that
> This function expects a valid Elixir AST

So my understanding is that this is now more strictly validated in Elixir.

But I couldn't figure out how to fix it without changing the CLDR module interfaces, the CLDR libraries are doing a lot of metaprogramming. I thought there still must be some way to pass this `config` struct as value to the `maybe_log_compile_warning` macro?

**Comment by josevalim** [comment]
The best way would be to have a non-macro API that does the job of `maybe_log_compile_warning` and call that instead, passing the escaped version of the struct.

**Comment by sabiwara** [comment]
I have a hotfix by passing the boolean directly: `unquote(config.suppress_warnings)` which fixed the build for `cldr_numbers`, but as @josevalim points out a proper fix might need deeper refactoring.

**Comment by michallepicki** [comment]
Thank you both! So to sum up, these extra validations are a ~breaking change~ bug fix that can make some meta-programming heavy code no longer compile if they relied onundocumented `unquote` behavior, and there is no drop-in Elixir replacement API to keep this behavior. Closing for now

**Comment by sabiwara** [comment]
> there is no drop-in Elixir replacement API to keep this behavior. 

Mentioning also for the record, in case somebody else finds this thread and needs a workaround.
If you need to keep code generating invalid AST for existing code, you could still hand-craft the pseudo-AST:

e.g.

```elixir
# instead of
quote do: Foo.bar(unquote(invalid_ast))

# do
{{:., [], [(quote do: Foo), :bar]}, [], [invalid_ast]}
```

**Comment by michallepicki** [comment]
Also discussed at https://github.com/elixir-lang/elixir/issues/13965 (sorry, didn't see it before)

**Comment by kipcole9** [comment]
Thanks all for the assist and especially @sabiwara for the PR.  I will sort out the root cause of the error in my lib - there is no intention to be passing invalid AST around.  BTW, the macro version exists because of support for earlier versions of OTP that didn't have `:persistent_term`. Since Elixir 1.11 (oldest supported version for `ex_cldr`) supports `:persistent_term` I can do as @josevalim suggests and use a functional form now.
