### ISSUE TITLE
Wrong positive struct warning on rescue clause

### ISSUE THREAD

**Issue by dominicletz** [elixir-lang/elixir#13980]
### Elixir and Erlang/OTP versions

$ elixir -v
Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Ubuntu

### Current behavior

```bash
$ cat test.ex
defmodule Test do
    def maybe_unzip(term) do
        try do
          :zlib.unzip(term)
        rescue
          [ErlangError, :data_error] ->
            term
        end
    end
end

$ elixir test.ex 
warning: struct :data_error is undefined (module :data_error is not available or is yet to be defined)
└─ test.ex: Test.maybe_unzip/1
```

### Expected behavior

```bash
$ cat test.ex
defmodule Test do
    def maybe_unzip(term) do
        try do
          :zlib.unzip(term)
        rescue
          [ErlangError, :data_error] ->
            term
        end
    end
end

$ elixir test.ex 
(no output)
```

**Comment by josevalim** [comment]
To be clear, either do `rescue _ -> term` or `rescue ErlangError -> _`. The `:data_error` is not doing anything.

**Comment by dominicletz** [comment]
Thanks for clarifying, I've no idea how I got to this construct above - but I did believe it would catch the specific :data_error subtype...
