### ISSUE TITLE
`warning: code block contains unused literal "foo\n"` does not contain line number

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#13986]
I was moving some code around and accidentally made my docs be strings without `@doc`, that is, something like the following:

```elixir
defmodule A do
  """
  foo
  """

  def a do
  end
end
```

this gives a warning:

```
warning: code block contains unused literal "foo\n" (remove the literal or assign it to _ to avoid warnings)
└─ test.exs: A (module)
```

however the warning does not contain line number.

**Comment by josevalim** [comment]
Yes, unfortunately we can't fix this. Literals do not have AST information attached to them. :(
