### ISSUE TITLE
String.valid? returns true for non string

### ISSUE THREAD

**Issue by michaelst** [elixir-lang/elixir#13985]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

macos

### Current behavior

The binary surprised me that it returns true as a valid string since it does not display as a string. Is this expected behavior?

```
iex(47)> String.valid?(<<76, 216, 151, 61, 66, 61, 0, 21, 78, 85, 76, 76>>)
true
```

### Expected behavior

```
iex(47)> String.valid?(<<76, 216, 151, 61, 66, 61, 0, 21, 78, 85, 76, 76>>)
false
```

**Comment by sabiwara** [comment]
The [`i/1`](https://hexdocs.pm/iex/IEx.Helpers.html#i/1) helper in IEx provides the explanation here:

```elixir
iex> i <<76, 216, 151, 61, 66, 61, 0, 21, 78, 85, 76, 76>>
Term
  <<76, 216, 151, 61, 66, 61, 0, 21, 78, 85, 76, 76>>
Data type
  BitString
Byte size
  12
Description
  This is a string: a UTF-8 encoded binary. It's printed with the `<<>>`
  syntax (as opposed to double quotes) because it contains non-printable
  UTF-8 encoded code points (the first non-printable code point being
  `<<0>>`).
```
