### ISSUE TITLE
named args

### ISSUE THREAD

**Issue by akandratovich** [elixir-lang/elixir#14]
many erlang functions accepts list of options (usually it's list of tupples). i think, that this is not cool. now we should use list of tuples too or funcs with default args, but in this case there is constant order of args, so it's not good too.

named args can solve this problem.

**Comment by trungpham** [comment]
Ruby took a long time to implement named arguments. I believe it first showed up in Ruby 2.1.

**Comment by tispratik** [comment]
Python has been a forerunner on this one, leaving Ruby behind. 
https://hexdocs.pm/defnamed/readme.html seems interesting.
