### ISSUE TITLE
Logger.Formatter crash on :ssl alert in mix archive.install

### ISSUE THREAD

**Issue by ruslandoga** [elixir-lang/elixir#14020]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Darwin 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:02:45 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8112 arm64

### Current behavior

Sorry for the screenshot, I'll update this message once I manage to reproduce it (I'm doing it now):

<img width="1102" alt="Screenshot 2024-11-24 at 19 12 07" src="https://github.com/user-attachments/assets/eb7d095a-9edd-462b-bde6-13a2afb566cf">

### Expected behavior

Logger.Formatter can format `:ssl` alerts.

**Comment by josevalim** [comment]
It looks like an Erlang bug to me. We are simply invoking a callback in the metadata:

https://github.com/elixir-lang/elixir/blob/v1.17.3/lib/logger/lib/logger/formatter.ex#L243

**Comment by josevalim** [comment]
Ok, there is something weirder going on. What does `Code.ensure_loaded?(:ssl_alert)` returns for you? I can confirm the function exists in Erlang (and it has been for quite some time), so the only possible reason is that the module failed to load some misterious reason.

**Comment by ruslandoga** [comment]
I tried setting hex repo to a "bad cert" URL and it works as expected:

```console
$ mix hex.repo add expired https://expired.badssl.com
$ mix archive.install hex phx_new --repo expired

17:05:25.287 [notice] TLS :client: In state :certify at ssl_handshake.erl:2158 generated CLIENT ALERT: Fatal - Certificate Expired

Failed to fetch record for expired/phx_new from registry (using cache instead)
{:failed_connect, [{:to_address, {~c"expired.badssl.com", 443}}, {:inet, [:inet], {:tls_alert, {:certificate_expired, ~c"TLS client: In state certify at ssl_handshake.erl:2158 generated CLIENT ALERT: Fatal - Certificate Expired\n"}}}]}
** (Mix) No package with name phx_new (from: mix.exs) in registry
```

I'll try a few more things but for now I'll close the issue since I'm not able to reproduce it.
