### ISSUE TITLE
Stracktraces missing steps

### ISSUE THREAD

**Issue by ponychicken** [elixir-lang/elixir#14022]
### Elixir and Erlang/OTP versions

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

Linux 6.11

### Current behavior

This is a constructed test case, but i had some difficulties debugging some real life bugs,
because the stacktrace is often not showing all functions of the stack.
In the example it is clear from the code who called `illegal_opertation/1` but if there are multiple places where it might have been called from its not so clear.

```
defmodule ModuleA do
  def level1 do
    # Perform some operation and pass the result to level2
    value = 10
    result = value + 5
    IO.puts("Level 1: result = #{result}")
    level2(result)
  end

  def level2(val) do
    # Perform another operation and pass the result to level3
    result = val * 2
    IO.puts("Level 2: result = #{result}")
    level3(result)
  end

  def level3(val) do
    # An illegal operation: division by zero
    IO.puts("Level 3: result = #{val}")
    illegal_operation(val)
  end

  def illegal_operation(val) do
    # Division by zero, which will raise an error
    1 / (val - val)  # This will cause a division by zero error
  end
end

defmodule ModuleB do
  def call_error_via_apply do
    apply(ModuleA, :level1, [])
  end
end

defmodule StacktraceTest do
  use ExUnit.Case

  test "call with apply" do
    # Ensure an error is raised and stacktrace is captured
      ModuleB.call_error_via_apply()
  end

  test "call directly" do
      ModuleA.level1()
  end
end

```

Output:
```
       stacktest2.exs:25: ModuleA.illegal_operation/1
       stacktest2.exs:44: (test)
```

### Expected behavior

Always print full stack

**Comment by josevalim** [comment]
Thank you for the report. 

This is tail call optimization (more precise, last call optimization) and it is an essential part of how the Erlang VM works and how we write recursive code. I always enjoyed Fred's take on the topic, which you can read to learn more: https://learnyousomeerlang.com/recursion

All in all, this is working as expected. :)

**Comment by ponychicken** [comment]
Thanks <3
