### ISSUE TITLE
Why can't I get full output ever in IEx?

### ISSUE THREAD

**Issue by maikelthedev** [elixir-lang/elixir#14025]
### Elixir and Erlang/OTP versions

Elixir 1.16.3

# ~/.iex.exs
IEx.configure(inspect: [limit: :infinity, width: 200])

limit: :infinity is supposed to let me see the full structure, but it never does. 

### Operating system

NixOS latest

### Current behavior

can't see the full output

### Expected behavior

see the full output

**Comment by maikelthedev** [comment]
I can do a dbg(socket) or a IO.inspect(socket) and in both cases, the whole thing is not outputed. 

I normally use it inside Test cases for Liveviews, like I want to render the full thing of {:ok, view, html} but I never get any of those in full.

**Comment by maikelthedev** [comment]
I tried, I still get trimmed view and html on liveview testing.

**Comment by josevalim** [comment]
Please show the code you are trying to invoke and the output you are seeing. We can't be of much help without more information.

**Comment by maikelthedev** [comment]
Two minutes and it'll be here.

**Comment by maikelthedev** [comment]
```elixir
defmodule IndieWeb.SearchResultsTest do
  use IndieWeb.ConnCase, async: true
  import Phoenix.LiveViewTest

  alias IndieWeb.SearchResults

  describe "SearchResults component" do
    setup do
      # Some boring setup
    end

    test "some test rendering a full view", %{conn: conn} do
      {:ok, view, html} = live(conn, "/")
      dbg(view, limit: :infinity)
      dbg(html, limit: :infinity)

      # Other way using IO.inspect
      IO.inspect(view, limit: :infinity)
      IO.inspect(html, limit: :infinity)
    end
  end
end
```

Now, this is what I see despite limit: infinity all over the place. I also had that in ~/.iex.ex as mentioned above. And yet this is what I see. 

The output of the dbgs
![image](https://github.com/user-attachments/assets/9513c38c-fb19-4d97-884b-5e1b4ac5c891)

The output of the inspects. 

![image](https://github.com/user-attachments/assets/6de69be6-8cec-4a75-8276-e90d2521d71c)

**Comment by josevalim** [comment]
The `#Phoenix.LiveViewTest.View` means the struct has more fields but those fields are private. You can never see them, regardless of the limit option. In other words, `...` in that case means "there is private things here which you cannot see".

When it comes to strings, then it is indeed being trimmed, and the docs explain it:

> * `:limit` - limits the number of items that are inspected for tuples, bitstrings, maps, lists and any other collection of items, with the exception of printable strings and printable charlists which use the `:printable_limit` option. If you don't want to limit the number of items to a particular number, use :infinity. It accepts a positive integer or :infinity. Defaults to 50.

And then:

> * `:printable_limit` - limits the number of characters that are inspected on printable strings and printable charlists. You can use [String.printable?/1](https://hexdocs.pm/elixir/String.html#printable?/1) and [List.ascii_printable?/1](https://hexdocs.pm/elixir/List.html#ascii_printable?/1) to check if a given string or charlist is printable. If you don't want to limit the number of characters to a particular number, use :infinity. It accepts a positive integer or :infinity. Defaults to 4096.

**Comment by maikelthedev** [comment]
Oh my Deu, I'm so happy. 

![image](https://github.com/user-attachments/assets/e5e6d7f7-de18-4bfc-9164-2f09d7a54e18)

Thank you Jose. You're the best. 

```elixir
    test "some test rendering a full view", %{conn: conn} do
      {:ok, view, html} = live(conn, "/")
      dbg(view, limit: :infinity, printable_limit: :infinity)
      dbg(html, limit: :infinity, printable_limit: :infinity)

      # Other way using IO.inspect
      IO.inspect(view, limit: :infinity, printable_limit: :infinity)
      IO.inspect(html, limit: :infinity, printable_limit: :infinity)
    end
```

I'm going to change my config also in .iex.exs to have it always in full like this. I can finally see the full HTML. 

Thank you very very much.
