### ISSUE TITLE
chunk function returns charlist at the end from nowhere.

### ISSUE THREAD

**Issue by wootra** [elixir-lang/elixir#14039]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.1.3] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

### Operating system

15.1.1 (Sequoia) / M1 Pro

### Current behavior

when using chunk function, it returns a weird charlist values at the end.
```
iex> list=[1,2,3,4,5,6,7,8,9,10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
iex> Enum.chunk_every(list, 2, 2)
[[1, 2], [3, 4], [5, 6], ~c"\a\b", ~c"\t\n"]
iex> Enum.chunk_by(list, & rem(&1, 4)===0)
[[1, 2, 3], [4], [5, 6, 7], ~c"\b", ~c"\t\n"]
```

### Expected behavior

Expected behavior for `Enum.chunk_every(list, 2, 2)` is
[[1,2], [3,4], [5,6], [7,8], [9,10]]
and for `Enum.chunk_by(list, & rem(&1, 4)===0)` is
[[1,2,3], [4], [5,6,7], [8], [9,10]]

**Comment by sabiwara** [comment]
This is expected. Quoting an answer from a similar issue https://github.com/elixir-lang/elixir/issues/13390:

> This is not "garbage", it is the way lists with printable characters are inspected by default. See https://hexdocs.pm/elixir/1.16.1/List.html#module-charlists . In IEx you can also set `IEx.configure(inspect: [charlists: :as_lists])`
