### ISSUE TITLE
asdf install fails for ref:v1.18.0-rc.0 because of failed mix test (ex_unit)

### ISSUE THREAD

**Issue by Eiji7** [elixir-lang/elixir#14049]
### Elixir and Erlang/OTP versions

Tested release candidate as mentioned in title. I use latest stable `Erlang` version (27.1.3).

### Operating system

Gentoo Linux with `default/linux/amd64/23.0/desktop/plasma` profile and `6.6.62` kernel version.

### Current behavior

The following message is printed:
```
  1) test logs and errors umbrella with file path (Mix.Tasks.TestTest)
     test/mix/tasks/test_test.exs:476
     Refute with =~ failed
     code:  refute output =~ "==> foo"
     left:  "==> foo\nGenerated foo app\n==> bar\nRunning ExUnit with seed: 368447, max_cases: 64\n\n....\nFinished in 0.02 seconds (0.00s async, 0.02s sync)\n4 tests, 0 failures\n"
     right: "==> foo"
     stacktrace:
       test/mix/tasks/test_test.exs:497: anonymous fn/0 in Mix.Tasks.TestTest."test logs and errors umbrella with file path"/1
       (elixir 1.18.0-rc.0) lib/file.ex:1665: File.cd!/2
       test/test_helper.exs:169: MixTest.Case.in_fixture/3
       test/mix/tasks/test_test.exs:477: (test)
```

**Note**: I 've also got such a notice message 7 times:
> [notice] Application parsetools exited: :stopped

I guess it should be captured, but it does not looks like a big priority or part of this issue.

### Expected behavior

All tests passes allowing to install `Elixir` from sources.

**Comment by josevalim** [comment]
Does it fail if you run it again? I believe it is a heisentest and I know the root cause. :)

**Comment by Eiji7** [comment]
Yes, it works after second compilation.
