### ISSUE TITLE
About the release scheme

### ISSUE THREAD

**Issue by chenrui333** [elixir-lang/elixir#14048]
👋 looks like there is some automated release for [v1.18-latest](https://github.com/elixir-lang/elixir/releases/tag/v1.18-latest), raise this issue to check if there would be a new release like 1.18.0 (in that way we need to update the latest version tracker on the homebrew side). Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/200681

**Comment by josevalim** [comment]
We will create a new -latest tag for each minor branch. They exist for hosting nightly builds. There is already a 1.18.0-rc.0 and there will eventually be a 1.18.0. You can safely ignore any `*-latest` tag.

**Comment by chenrui333** [comment]
noted, thanks!!
