### ISSUE TITLE
Runtime comparison of atoms known at compile time results in unclear warning from type-system

### ISSUE THREAD

**Issue by vanderhoop** [elixir-lang/elixir#14057]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Elixir 1.18.0-rc.0 (66c5908) (compiled with Erlang/OTP 27)

### Operating system

Mac OS X 15.1.1

### Current behavior

In the 1.18rc0, we get an error regarding comparing distinct types when comparing atoms when the atom values are known at compile time.

Minimal Repro Module:
```elixir
defmodule AtomComparisonTypingRepro do
  @compile_time_attr_read_from_application :jack

  def same? do
    @compile_time_attr_read_from_application == :jill
  end
end
```

```
warning: comparison between distinct types found:

        :jack == :jill

    While Elixir can compare across all types, you are comparing across types which are always disjoint, and the result is either always true or always false

    typing violation found at:
    │
  6 │     @compile_time_attr_read_from_application == :jill
    │                                              ~
    │
    └─ typing_repro.exs:6:46: AtomComparisonTypingRepro.same?/0
```

### Expected behavior

I would expect that predicate methods relying on atoms known at compile time would be fine with a value always being `true` or `false` at runtime.

It would seem that the guidance is pushing the code toward generating a single boolean value at compile time, i.e the following code, which *doesn't* emit a warning:

```elixir
defmodule AtomComparisonTypingRepro do
  @compile_time_attr_read_from_application :jack
  @same @compile_time_attr_read_from_application == :jill

  def same? do
    @same
  end
end
```

**Comment by vanderhoop** [comment]
I suspect the solution I arrived at in the lower snippet is the desired outcome, as it's less work at runtime, so maybe the warning is great and the actual warning language just needs tweaking in the case of atoms known at compile time?

**Comment by vanderhoop** [comment]
> The issue with adding some tweaking is that we would be guessing and we could totally throw the user in the wrong direction

Yeah, I'd rather the system not guess :)

> The other thing to keep in mind is that we are getting these warnings in retrospect, I assume it would have been clearer if you had just wrote the code, perhaps it would have been more obvious?

Yes, this code that was flagged was written years ago. In the course of moment-to-moment development, I think it would be clearer. 

Closing this issue, and if others encounter the same confusion, hopefully this issue acts as a helpful breadcrumb.

**Comment by josevalim** [comment]
Thank you. If others stumble upon this, we can reopen and leave it open for guidance.
