### ISSUE TITLE
v1.18 changelog on https://hexdocs.pm/elixir/1.18/changelog.html points to invalid links

### ISSUE THREAD

**Issue by w0rd-driven** [elixir-lang/elixir#14084]
### Elixir and Erlang/OTP versions

N/A

### Operating system

N/A

### Current behavior

I'm unsure if this is the repo to fix the issue. The environment doesn't apply because it's how hex resolves **a subset of links** as some work as expected.

These are the links that resolve to `/v1.18/`, searching through the page source:
* `<a href="https://hexdocs.pm/mix/v1.18/Mix.Tasks.Format.html" class="no-underline"><code class="inline">mix format</code></a>`
* `<a href="https://hexdocs.pm/ex_unit/v1.18/ExUnit.Case.html" class="no-underline"><code class="inline">ExUnit.Case</code></a>`
* `<a href="https://hexdocs.pm/iex/v1.18/IEx.html#configure/1" class="no-underline"><code class="inline">IEx.configure/1</code></a>`
* `<a href="https://hexdocs.pm/iex/v1.18/IEx.Helpers.html#recompile/0" class="no-underline"><code class="inline">IEx.Helpers.recompile/0</code></a>`
* `<a href="https://hexdocs.pm/mix/v1.18/Mix.Shell.html" class="no-underline"><code class="inline">Mix.Shell</code></a>`
* `<a href="https://hexdocs.pm/mix/v1.18/Mix.Tasks.Compile.html" class="no-underline"><code class="inline">mix compile</code></a>`
* `<a href="https://hexdocs.pm/mix/v1.18/Mix.Tasks.Test.html" class="no-underline"><code class="inline">mix test</code></a>`
* `<a href="https://hexdocs.pm/mix/v1.18/Mix.Task.Compiler.html#compilers/0" class="no-underline"><code class="inline">Mix.Task.Compiler.compilers/0</code></a>`

I included the full element in case it's unclear where these come from. I haven't checked all of them, but I clicked through quite a few while reading this and the other links were fine.

### Expected behavior

All of the links work as expected and pointed to `/1.18/`, like https://hexdocs.pm/elixir/1.18/JSON.html#encode!/1 or https://hexdocs.pm/elixir/1.18/PartitionSupervisor.html#resize!/2.

**Comment by josevalim** [comment]
Thank you, it has been fixed!
