### ISSUE TITLE
Release SHA256 mismatch - for Elixir v1.18.0 (elixir-otp-27.exe) 

### ISSUE THREAD

**Issue by shishini** [elixir-lang/elixir#14083]
### Elixir and Erlang/OTP versions

Elixir v1.18.0

### Operating system

Windows

### Current behavior

The hash in **elixir-otp-27.exe.sha256sum** is 
759eff7216c2d46f5c26a2d19e3a43bba00d9f134e802de5ffcdee79e9ae2b32

The hash i get running
`get-fileHash -Algorithm SHA256 .\elixir-otp-27.exe ` is B9FD400B053C5B8089DE32B75C81447F4C9E208F350AC503F8C309D1B94AFD91

### Expected behavior

I was expecting same hash

**Comment by wojtekmach** [comment]
This is definitely unexpected, I am seeing the same results:

```
$ curl -fsSL https://github.com/elixir-lang/elixir/releases/download/v1.18.0/elixir-otp-27.exe.sha256sum
759eff7216c2d46f5c26a2d19e3a43bba00d9f134e802de5ffcdee79e9ae2b32  elixir-otp-27.exe
$
$ shasum -a 256 <(curl -fsSL https://github.com/elixir-lang/elixir/releases/download/v1.18.0/elixir-otp-27.exe)
b9fd400b053c5b8089de32b75c81447f4c9e208f350ac503f8c309d1b94afd91  /dev/fd/11```

**Comment by maennchen** [comment]
@wojtekmach Is the azure .exe signer updating the file in-place?

https://github.com/elixir-lang/elixir/blob/6ff6fe45e693d4018e20025b85a85516a38facf1/.github/workflows/release.yml#L138

If yes, we generate the sha too early.

**Comment by wojtekmach** [comment]
Yeah that’s it, good find!

**Comment by maennchen** [comment]
Then the same will apply to the build provenance.

It would probably be better anyways to sign the file in the `build` stage and not in `upload-release`. Security will be tighter inside of one job vs. an artifact between jobs.

That would mean that we either incorporate build provenance & azure signing into the `release_pre_built` action or generate the sha hashes outside of the `release_pre_built` action after the signatures are done.

**Comment by wojtekmach** [comment]
PR always appreciated! I could work on it tomorrow otherwise.

**Comment by maennchen** [comment]
I'm on it.

You'll probably want to manually correct the SHA hashes and delete all the `.exe.cosign` files for 1.18.0 since they will not be fixed by the PR.

**Comment by josevalim** [comment]
Thank you. I have updated the checksums and deleted all cosigns for now. We shall do a v1.18.1 now.
