### ISSUE TITLE
DateTime.from_unix/2 loses precision when converting nanosecond timestamps

### ISSUE THREAD

**Issue by Psli** [elixir-lang/elixir#14081]
### Elixir and Erlang/OTP versions

$ elixir --version
Erlang/OTP 27 [erts-15.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.17.3 (compiled with Erlang/OTP 25)

### Operating system

macOS

### Current behavior

The conversion from nanosecond timestamp to DateTime and back should preserve all digits of precision.

iex(8)> ts = System.system_time(:nanosecond)
1734586364179704909
iex(9)> {:ok, datetime} = DateTime.from_unix(ts, :nanosecond)
{:ok, ~U[2024-12-19 05:32:44.179704Z]}
iex(10)> DateTime.to_unix(datetime, :nanosecond)
1734586364179704000

### Expected behavior

1734586364179704909
1734586364179704000

**Comment by josevalim** [comment]
I will make it clear in the documentation but our calendar types have precision of microseconds, therefore loss of precision is expected here.
