### ISSUE TITLE
Confusing type warning when invoking a function within a function capture

### ISSUE THREAD

**Issue by connorlay** [elixir-lang/elixir#14089]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.1.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Elixir 1.18.0 (compiled with Erlang/OTP 25)

### Operating system

Pop!_OS 22.04 LTS

### Current behavior

Consider the following:
```elixir
defmodule A do
  def fun1() do
    &fun2().fun1/0
  end

  def fun2() do
    __MODULE__
  end
end
```

When I compile this with Elixir 1.18.0 I see this warning:
```
    warning: expected a map or struct when accessing .fun1 in expression:

        fun2().fun1

    but got type:

        dynamic(A)

    hint: "var.field" (without parentheses) means "var" is a map() while "var.fun()" (with parentheses) means "var" is an atom()

    typing violation found at:
    │
  3 │     &fun2().fun1/0
    │             ~
    │
    └─ (capture_type_warning 0.1.0) lib/capture_type_warning.ex:3:13: A.fun1/0
```

A simpler version without the indirection of `fun2()` does not produce this warning:
```elixir
defmodule A do
  def fun1() do
    &__MODULE__.fun1/0
  end
end
```

### Expected behavior

I'm not sure to be honest. I don't think this would emit a type warning at all?

**Comment by sabiwara** [comment]
This seems like an issue about how `&fun2().fun1/0` gets expanded rather than a type only issue.
Currently, it expands to `fn -> fun2().fun1 end` and not `fn -> fun2().fun1() end`, so indeed `.fun1` looks like a map access.
It also warns at runtime:

```elixir
iex> A.fun1()
#Function<0.87535455/0 in A.fun1/0>
iex> A.fun1().()
warning: using map.field notation (without parentheses) to invoke function A.fun1() is deprecated, you must add parentheses instead: remote.function()
```

I think I have a fix.

**Comment by josevalim** [comment]
@connorlay we will push a fix but note that it will be deprecated because the construct is ambiguous. You should rewrite it to: `fn -> fun2().fun1() end` instead :)
