### ISSUE TITLE
Macro.escape missing?

### ISSUE THREAD

**Issue by maikelthedev** [elixir-lang/elixir#14088]
### Elixir and Erlang/OTP versions

latest (1.18)

### Operating system

Nixos

### Current behavior

I get [this error](https://github.com/elixir-cldr/cldr/issues/246) on previously working CLDR. 
The funny thing is the first line points to Elixir, not to Cldr having a missing line

> Did you forget to escape term using Macro.escape/1?

So it's like an error of Elixir 1.18 and not of Cldr itself. 

### Expected behavior

Project compiles

**Comment by maikelthedev** [comment]
Nevermind

**Comment by sabiwara** [comment]
The original issue for reference if somebody else ends up here: https://github.com/elixir-cldr/cldr_numbers/issues/53
