### ISSUE TITLE
Certificates cannot be signed on main/v1.18

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#14099]
@maennchen @wojtekmach is this expected?

Here is one example of failures: https://github.com/elixir-lang/elixir/actions/runs/12444762098

**Comment by maennchen** [comment]
@josevalim I’m on it

**Comment by maennchen** [comment]
Oh, I found the issue. I've overlooked that the `upload-release` job was running in windows and build in ubuntu.

I'll have to take the jobs apart to make it work. I'm working on a PR.
