### ISSUE TITLE
Phoenix project doesn't boot up with Elixir 1.18 (Waiting for lock on the build directory)

### ISSUE THREAD

**Issue by gabrielperales** [elixir-lang/elixir#14104]
### Elixir and Erlang/OTP versions

Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.18.0 (compiled with Erlang/OTP 25)

### Operating system

macOS Sequoia 15.1

### Current behavior

When I run `mix phx.server` it gets stuck showing the following message in the terminal:

```
❯ mix phx.server
==> file_system
Waiting for lock on the build directory (held by process 66604)
```

### Expected behavior

It should launch the Phoenix app 

[Here is the branch](https://github.com/gabrielperales/elixir_jobs/tree/elixir-118) of the project I'm trying to run. If I downgrade Elixir to 1.17 it works without any issue.

**Comment by jonatanklosko** [comment]
Hey @gabrielperales, just to be sure, how long did you wait, does it get stuck forever? Also, when this happens, please try identifying the process from the message (66604 is a OS pid in the example)? Something like `ps aux | grep 66604`. Is there a process running, or is it dead?

Unfortunately I couldn't reproduce it, for me `mix phx.server` finishes as expected.

**Comment by gabrielperales** [comment]
> Hey @gabrielperales, just to be sure, how long did you wait, does it get stuck forever? Also, when this happens, please try identifying the process from the message (66604 is a OS pid in the example)? Something like `ps aux | grep 66604`. Is there a process running, or is it dead?

Yeah, it got stuck forever... I think I tried to kill the process and It didn't work, but I tried again and it solved the issue. Thanks, I'm closing the issue 😓

**Comment by jonatanklosko** [comment]
> I think I tried to kill the process and It didn't work,

So there was a process with that PID actually running? Do you remember what it was, perhaps LSP?

**Comment by gabrielperales** [comment]
> > I think I tried to kill the process and It didn't work,
> 
> So there was a process with that PID actually running? Do you remember what it was, perhaps LSP?

Ops, not sure, I think it said something about erlang...
