### ISSUE TITLE
Duplicated closing meta on AST nodes with nested function calls

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#14119]
### Elixir and Erlang/OTP versions

Erlang/OTP 26 [erts-14.2.5.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.18.1 (compiled with Erlang/OTP 26)

### Operating system

any

### Current behavior

```
buffer = "defmodule MyModule do\n  foo(bar())()\nend\n"

Code.string_to_quoted!(buffer, token_metadata: true, columns: true)
{:defmodule,
 [
   end_of_expression: [newlines: 1, line: 3, column: 4],
   do: [line: 1, column: 20],
   end: [line: 3, column: 1],
   line: 1,
   column: 1
 ],
 [
   {:__aliases__, [last: [line: 1, column: 11], line: 1, column: 11],
    [:MyModule]},
   [
     do: {{:foo, [closing: [line: 2, column: 12], line: 2, column: 3],
       [{:bar, [closing: [line: 2, column: 11], line: 2, column: 7], []}]},
      [
        end_of_expression: [newlines: 1, line: 2, column: 15],
        closing: [line: 2, column: 14],
        closing: [line: 2, column: 12],
        line: 2,
        column: 3
      ], []}
   ]
 ]}
```

Notice `closing` appears twice with different columns

### Expected behavior

Only `closing: [line: 2, column: 14]` should be present on that node

**Comment by josevalim** [comment]
Pinging @jonatanklosko, as I don't believe this one is intentional. :)

**Comment by jonatanklosko** [comment]
This has already been the before v1.18, and we actually need both if we want to have complete information in this case.

**Comment by josevalim** [comment]
@jonatanklosko I thought that could be the case but what left me confused is that the closing information is repeated on both `foo` and the parent node:

```
    {{:foo, [closing: [line: 2, column: 12], line: 2, column: 3],
       [{:bar, [closing: [line: 2, column: 11], line: 2, column: 7], []}]},
      [
        end_of_expression: [newlines: 1, line: 2, column: 15],
        closing: [line: 2, column: 14],
        closing: [line: 2, column: 12],
        line: 2,
        column: 3
      ], []}
```

So isn't it redundant? Why does it need to be duplicated?

**Comment by jonatanklosko** [comment]
Ah yes, you are correct! I will send a PR :)
