### ISSUE TITLE
Elixir 18.1

### ISSUE THREAD

**Issue by gruber123** [elixir-lang/elixir#14113]
Missing windows installation elixir on erlang otp-25 from this link [https://github.com/elixir-lang/elixir/releases/download/v1.18.1/elixir-otp-25.exe](https://github.com/elixir-lang/elixir/releases/download/v1.18.1/elixir-otp-25.exe)

**Comment by josevalim** [comment]
Thank you. It seems that releases are always built from the main branch? So we will need to define the build versions conditionally in the matrix. I will remove the mention to otp-25 on the website.

**Comment by viceice** [comment]
is it expected to drop a erlang major version in a elixir patch version?

**Comment by josevalim** [comment]
It is temporary until the next patch release so we don’t have a broken link. We will add it back on the next patch release.

Although it is worth noting that the shell on OTP 25 is very limited on Windows, so the recommendation is to upgrade anyway. :)
