### ISSUE TITLE
Persistent command history

### ISSUE THREAD

**Issue by christhekeele** [elixir-lang/elixir#1516]
(Intermediate IEx Feature Request)

It would be convenient if your IEx command history could persist across sessions.

I'm suggesting this issue be tagged as Level:Intermediate because aside from modifying the `IEx.History` module to be its own process, you'd have to process navigating the history with the up/down arrow keys through the new `IEx.History` process. That would mean customizing the [erlang C driver](http://www.erlang.org/doc/apps/erts/tty.html) used by [`IEx` here](https://github.com/elixir-lang/elixir/blob/master/lib/iex/lib/iex/cli.ex#L64), or moving to `ncurses` or something. That kind of thing out of my domain expertise.

**Comment by jeznet** [comment]
#rlwrap But the downside of it is that it braks tab (code) completion of IEx...
