### ISSUE TITLE
Passing anonymous functions to remote nodes seems broken

### ISSUE THREAD

**Issue by ChaosSteffen** [elixir-lang/elixir#1520]
Passing an anonymous function to a remote Node causes strange errors when not created in a shell.

If I open an iex-shell and type

```
Node.spawn_link(:"node@remote-machine.local", fn -> IO.puts "Test" end)
# => #PID<11618.1951.0>
# => Test                                     
```

everything works fine.

But, if I create a module, like:

```
defmodule Foo do
    def bar do
        Node.spawn_link(:"node@remote-machine.local", fn -> IO.puts "Test" end)
    end
end
```

And then load it into my shell, it crashes with:

```
Foo.bar
# => #PID<11618.1961.0>
# => ** (EXIT from #PID<11618.1961.0>) {:undef, [{#Function<Elixir.Foo.0.27583298>, [], []}]}
# => iex(node@remote-machine.local)4> 
# => =ERROR REPORT==== 31-Jul-2013::15:29:50 ===
# => Error in process <0.1961.0> on node 'node@remote-machine.local' with exit value: {undef,[{#Fun<Elixir.Foo.0.27583298>,[],[]}]}
```

Local nodes on the same machine work fine with this, but remote nodes do crash.

**Comment by uri** [comment]
What is [`Node.spawn/2`](http://elixir-lang.org/docs/stable/elixir/Node.html#spawn/2) used for then? It has the same problem where the function is compiled into the module.

**Comment by antipax** [comment]
@uri as long as the remote node has the same module loaded, you can pass an anonymous function and it will work just fine.

You can try this out by creating a mix project, starting and connecting two nodes to each other from that project's code using `iex --sname <name> -S mix`, and then using `Node.spawn/2` on an anonymous function defined in a module in the mix project.

**Comment by antipax** [comment]
I would also note that since anonymous functions won't work across node boundaries due to the aforementioned reasons, it is generally recommended to use module/fun/args instead of anonymous functions. This is because they will continue to work as long as the specified Module.fun/arity exists in the called node's code.

**Comment by hauleth** [comment]
@josevalim maybe there should be warning when using `Node.spawn` with anonymous function that would state that this is insecure way to doing so and preferred way is to use `mfa`.

**Comment by michalmuskala** [comment]
The problem is a bit wider, though - sending anonymous functions between nodes in general can be risky, if you can't guarantee they all contain exactly the same code. `Node.spawn` is not particularly special.
