### ISSUE TITLE
Support multimethods (discussion on configurability)

### ISSUE THREAD

**Issue by Raynes** [elixir-lang/elixir#192]
A good example of multimethods is Clojure's multimethods. I think Elixir could benefit from them significantly. I have a scenario in particular in mind that I'd be able to use them for.

I'm working on a URI parser. There are many different schemes that have scheme-specific functionality. For example, the default port for http is 80 while the default port for https is 443. I'd like to make scheme-specific parsing behavior extensible so that users can add their own schemes and parsing behavior on top of my generic parsing. Right now, I allow for an Orddict of schemes -> functions that take a generic-parsed URI and do whatever they want with it and return it. I have a default list for the major schemes. This is a bit ugly and is exactly what multimethods are designed for.

**Comment by alexeypetrushin** [comment]
Any news on this? :)
