### ISSUE TITLE
Line numbers in iex

### ISSUE THREAD

**Issue by batate** [elixir-lang/elixir#1946]
I'm writing seven languages 2, and not surprisingly, Elixir made the cut. I'd like to be able to turn line numbers off in the console because it would make it easier to show examples in the output. Line numbers won't match the user's output, and it's too hard to go through a long sequence of commands without making a mistake.

My guess is that others writing about Elixir will have the same problem. I'd like a switch to turn off line numbers in iex.

**Comment by rachamaduguravi** [comment]
please check solution in below link

How to Change the Prompt in Elixir `IEx` with Examples | TopTechSkills.com
https://www.toptechskills.com/elixir-phoenix-tutorials-courses/how-to-change-prompt-in-iex-elixir-tutorial-examples/
