### ISSUE TITLE
iex syntax error

### ISSUE THREAD

**Issue by binnisb** [elixir-lang/elixir#1966]
I was following the tutorial on:
http://elixir-lang.org/getting_started/2.html

I ran the following code in iex, I am not quite sure what is going on but these are two lines, one I copied and one I entered myself. 

One gives result, the other one gives syntax error.

Any idea what is going on?

iex(37)> { k, l, m } = { :adsf, "fda", 321 }
{:adsf, "fda", 321}
iex(38)> { k, l, m } = { :adsf, "fda", 321 }
*\* (SyntaxError) iex:38: invalid token:  { :adsf, "fda", 321 }
iex(38)> { k, l, m } = { :adsf, "fda", 321 }
{:adsf, "fda", 321}
iex(39)> { k, l, m } = { :adsf, "fda", 321 }
*\* (SyntaxError) iex:39: invalid token:  { :adsf, "fda", 321 }
iex(39)> { k, l, m } = { :adsf, "fda", 321 }
*\* (SyntaxError) iex:39: invalid token:  { :adsf, "fda", 321 }
iex(39)> { k, l, m } = { :adsf, "fda", 321 }
{:adsf, "fda", 321}

**Comment by stevematdavies** [comment]
I have this issue regularly using hyper with **eix**, the code is exact, but writing myself gives a syntax error but pasting it from an example it is fine.

1 My code:   gives syntax error, 2. pasted code: is fine

1 `Agent.update(agent, fn list -> ["eggs" | list] end)` 
2 `Agent.update(agent, fn list -> ["eggs" | list] end)`

No apparent hidden whitespace, or any null chars. Same issue happens in Terminal on Mac

```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```
**Mac Mojave 10.14.06**

**Hyper 3.0.2 (stable)**

**Comment by josevalim** [comment]
Can you please post the error that you receive? Thank you.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by stevematdavies** [comment]
> ** (SyntaxError) iex:5: unexpected token: " " (column 40, code point U+00A0)

**Comment by vendethiel** [comment]
U+00A0, entity usually written `&nbsp;`, is a non breaking space. Maybe you pasted it from some webpage that had it?

**Comment by stevematdavies** [comment]
Quite possibly, actually following course https://elixir-lang.org/getting-started. Just strange I cant see those in an editor or equivalent when I have whitespace and line breaks etc. visible
