### ISSUE TITLE
calling mix compile should copy contents of my_app/priv to _build/MIX_ENV/my_app/priv

### ISSUE THREAD

**Issue by onkel-dirtus** [elixir-lang/elixir#1999]

**Comment by noizu** [comment]
I get build issues with a symlinked priv folder on docker for windows (stable & beta) _if_ I am using gettext locales. Symlinks go a bit pear shaped on shared drives so this can cause issues for vagrant, virtual box, docker for windows, docker toolbox etc.

**Comment by josevalim** [comment]
@noizu Since Elixir v1.2, we ship with a build_embedded option that allows you to take explicit control over the compilation step and disables using symlinks altogether.

**Comment by noizu** [comment]
(bow) yep. Found it after some web based research. Works like a charm, more or less.
