### ISSUE TITLE
Allow ^ in function heads (consider bitinfo and map variables)

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2061]
The following code should work:

```iex
iex> x = 1
iex> fn(x, << y :: size(^x) >>) -> { x, y } end
```

The following code should not:

```iex
iex> x = 1
iex> fn(x, << y :: size(x) >>) -> { x, y } end
```

Both expressions should be valid outside fn match though.

**Comment by sunaku** [comment]
:tada: Since [Erlang/OTP 18.0 is finally here](http://www.erlang.org/news/88), maybe this bug can be revisited? :innocent:

**Comment by josevalim** [comment]
Fixed in master.

**Comment by sunaku** [comment]
:bow: Thank you! :+1:

**Comment by padde** [comment]
I was just trying to use this to match a map key in a function head with another variable from the same match. Are the following examples revealing bugs, or am I just using this wrong?

```
x = fn(%{key => value}, key) -> value end

** (CompileError) iex:6: illegal use of variable key as map key inside match, maps can only match on existing variable by using ^key
    (elixir) src/elixir_map.erl:157: anonymous fn/7 in :elixir_map.translate_map/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_map.erl:156: :elixir_map.translate_map/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_fn.erl:26: :elixir_fn.translate_fn_match/2

defmodule Test do
  def x(%{key => value}, key), do: value
end

** (CompileError) iex:7: illegal use of variable key as map key inside match, maps can only match on existing variable by using ^key
    (elixir) src/elixir_map.erl:157: anonymous fn/7 in :elixir_map.translate_map/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_map.erl:156: :elixir_map.translate_map/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

The pin operator won't help either, as suggested by the compile error. It shouldn't be required for function heads anyway:

```
x = fn(%{^key => value}, key) -> value end
x.(%{a: 1}, :a)

** (FunctionClauseError) no function clause matching in :erl_eval."-inside-an-interpreted-fun-"/2

defmodule Test do
  def x(%{^key => value}, key), do: value
end

** (CompileError) iex:7: unbound variable ^key
    (elixir) src/elixir_map.erl:157: anonymous fn/7 in :elixir_map.translate_map/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (elixir) src/elixir_map.erl:156: :elixir_map.translate_map/4
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

**Comment by josevalim** [comment]
The error messages are correct. Maps only allow you to map on previously
defined variables, they can't come from the same pattern.

On Wednesday, January 27, 2016, Patrick Oscity <notifications@github.com>
wrote:

> I was just trying to use this to match a map key in a function head with
> another variable from the same match. Are the following examples revealing
> bugs, or am I just using this wrong?
>
> x = fn(%{key => value}, key) -> value end
>
> ** (CompileError) iex:6: illegal use of variable key as map key inside match, maps can only match on existing variable by using ^key
>     (elixir) src/elixir_map.erl:157: anonymous fn/7 in :elixir_map.translate_map/4
>     (stdlib) lists.erl:1353: :lists.mapfoldl/3
>     (elixir) src/elixir_map.erl:156: :elixir_map.translate_map/4
>     (stdlib) lists.erl:1353: :lists.mapfoldl/3
>     (elixir) src/elixir_fn.erl:26: :elixir_fn.translate_fn_match/2
>
> defmodule Test do
>   def x(%{key => value}, key), do: value
> end
>
> ** (CompileError) iex:7: illegal use of variable key as map key inside match, maps can only match on existing variable by using ^key
>     (elixir) src/elixir_map.erl:157: anonymous fn/7 in :elixir_map.translate_map/4
>     (stdlib) lists.erl:1353: :lists.mapfoldl/3
>     (elixir) src/elixir_map.erl:156: :elixir_map.translate_map/4
>     (stdlib) lists.erl:1353: :lists.mapfoldl/3
>
> The pin operator won't help either, as suggested by the compile error. It
> shouldn't be required for function heads anyway:
>
> x = fn(%{^key => value}, key) -> value end
> x.(%{a: 1}, :a)
>
> ** (FunctionClauseError) no function clause matching in :erl_eval."-inside-an-interpreted-fun-"/2
>
> defmodule Test do
>   def x(%{^key => value}, key), do: value
> end
>
> ** (CompileError) iex:7: unbound variable ^key
>     (elixir) src/elixir_map.erl:157: anonymous fn/7 in :elixir_map.translate_map/4
>     (stdlib) lists.erl:1353: :lists.mapfoldl/3
>     (elixir) src/elixir_map.erl:156: :elixir_map.translate_map/4
>     (stdlib) lists.erl:1353: :lists.mapfoldl/3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/2061#issuecomment-175480152>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by padde** [comment]
Alright, thanks for the info, too bad :( I guess this limitation comes from the BEAM? Is there anything we can do about it or would it be considered an "anti-feature" anyway?

**Comment by metabrain** [comment]
I ran into this issue as well, hence finding this thread here. My question is, the variable binding is done sequentially, parameter by parameter correct? If so, if the order of the parameters were reverted it should work since key would be bound with the incoming parameter before the ^key was used in the map pattern-match expression yes?
`
defmodule Test do
  def x(key, %{^key => value}), do: value
end
`

I expected it to work but it doesn't. Is it intended? In one hand, I think it is good that it is NOT supported since binding and then using a bound ^ parameter in same function header declaration might lead to more confusing code if abused. On the other hand, it will just force us to not bind the map

`
defmodule Test do
  def x(key, m) do
    case m do
       %{^key => value} -> value
       _ -> true
    end
  end
end
`

which is pretty much the same and works as expected. 

`
iex(4)> Test.x(:a, %{})
true
iex(5)> Test.x(:a, %{:a => false})
false
`

I can see how supporting the pin operation in funcion head declaration for pattern matching might cause some problems, such as the need to delay the **^key** binding until the other parameter that binds the **key** is performed and **key** is matched.
_
(Still very new at Elixir but learning, sorry if I mentioned anything incorrect. And thanks for the great work on the language Jose!)_

**Comment by josevalim** [comment]
No, pattern matching is not sequential. The whole pattern is analyzed at
once and not left to right. :)

It is also noting this is a VM limitation (and not an Elixir one!).

On Sunday, May 8, 2016, Daniel Parreira <notifications@github.com> wrote:

> I ran into this issue as well, hence finding this thread here. My question
> is, the variable binding is done sequentially, parameter by parameter
> correct? If so, if the order of the parameters were reverted it should work
> since key would be bound with the incoming parameter before the ^key was
> used in the map pattern-match expression yes?
>
> defmodule Test do
> def x(key, %{^key => value}), do: value
> end
>
> I expected it to work but it doesn't. Is it intended? In one hand, I think
> it is good that it is NOT supported since binding and then using a bound ^
> parameter in same function header declaration might lead to more confusing
> code if abused. On the other hand, it will just force us to not bind the map
>
>
> defmodule Test do
> def x(key, m) do
> case m do
> %{^key => value} -> value
> _ -> true
> end
> end
> end
>
> which is pretty much the same and works as expected.
>
>
> iex(4)> Test.x(:a, %{})
> true
> iex(5)> Test.x(:a, %{:a => false})
> false
>
> I can see how supporting the pin operation in funcion head declaration for
> pattern matching might cause some problems, such as the need to delay the
> *^key* binding until the other parameter that binds the *key* is
> performed and *key* is matched.
> _
> (Still very new at Elixir but learning, sorry if I mentioned anything
> incorrect. And thanks for the great work on the language Jose!)_
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/2061#issuecomment-217679553>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by heri16** [comment]
:sadface

**Comment by LostKobrakai** [comment]
I'm wondering if it's a known limitation, that the first following example does not work, while the latter does:

```elixir
    Ecto.Multi.new
    |> Ecto.Multi.run({:activity, index}, fn _ ->
      Scheduling.create_activity(campaign, line_to_activity(line))
    end)
    |> Ecto.Multi.run({:timeslot, index}, fn %{{:activity, ^index} => activity} ->
      Scheduling.create_timeslot(activity, line_to_activity(line))
    end)
```

```elixir
    key = {:activity, index}
    Ecto.Multi.new
    |> Ecto.Multi.run(key, fn _ ->
      Scheduling.create_activity(campaign, line_to_activity(line))
    end)
    |> Ecto.Multi.run({:timeslot, index}, fn %{^key => activity} ->
      Scheduling.create_timeslot(activity, line_to_activity(line))
    end)
```

**Comment by azhi** [comment]
Sorry to bump an old thread: I just got hit with same issue as @LostKobrakai.
Is it a known limitation? Maybe it is worth documenting in `Kernel.SpecialForms/^`?
