### ISSUE TITLE
Change String.from_char_list/1 into String.from_characters/2?

### ISSUE THREAD

**Issue by zambal** [elixir-lang/elixir#2067]
:unicode.characters_to_binary, which String.from_char_list uses, allows for much more types of input than String.from_char_list defines in its spec. Some libraries like https://github.com/meh/jazz/ already use this implicit functionality, which is fine unless one want to use the dialyzer, as it will complain about it.

Would it be an idea to change String.from_char_list/1 (and String.from_char_list!/1) into String.from_characters/2 in order to explicitly allow other types of input? The extra argument would be needed for setting the encoding of the input, since it would also allow a list of binaries.

If the answer is yes, I would be happy to provide a PR for this.

**Comment by eksperimental** [comment]
just for the deprecation record, **`String.from_char_list/1`** was replaced by **`String.from_char_data/1`**, which was later replaced by **`List.to_string/1`**

for anybody coming here looking for deprecation replacements
from the following errors:
> warning: String.from_char_list!/1 is deprecated, please use String.from_char_data!/1 instead

and 
> warning: String.from_char_data/1 is deprecated, use List.to_string instead
