### ISSUE TITLE
why [49, 58, 76, 82, 88, 90]  is  '1:LRXZ' ? 

### ISSUE THREAD

**Issue by defp** [elixir-lang/elixir#2172]
Elixir 0.13-dev 

```
Erlang/OTP 17 [erts-6.0] [source-07b8f44] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (0.13.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [49, 58, 76, 82, 88, 90]
'1:LRXZ'
iex(2)> [1, 49, 58, 76, 82, 88, 90]
[1, 49, 58, 76, 82, 88, 90]
iex(3)>
```

**Comment by joekur** [comment]
I'm very new to elixir, but thought I'd throw my input in here that I'd personally prefer `inspect` to not try to be smart and interpret lists as char lists. According to the getting started guide:

> In practice, char lists are used mostly when interfacing with Erlang, in particular old libraries that do not accept binaries as arguments

I feel much more often will I be working with integer lists than char lists. Spun my wheels for a few minutes when my test output totally confused me.
