### ISSUE TITLE
Add Keyword.bool/3 (or similar)

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2497]
Today it is verbose to assert if a value inside a keyword is a boolean. Take this use case for example:

https://github.com/elixir-lang/elixir/blob/a6fab4a11143f91e68f659d12f46d56de13e6c03/lib/elixir/lib/string.ex#L240

I expect a boolean value in there but it is hard to assert I got *only* a boolean value elegantly given `false` and `nil` are treated as "falsy" values and everything else is true. So far we have two options:

  1. use `!!expr` to convert an expression to a boolean. This, however, would accept any value as true or false (we don't have strictness)

  2. use a `case` to match on both true and false outcomes:

        case Keyword.get(options, :trim, false) do
          true -> true
          false -> false
        end

    However this example is verbose and will lead to poor error messages.

The idea is to add a new function that returns a boolean value, defaulting to false in case there is no matching key. The goal is to have a strict function since the non-strict case is easy to achieve using `!!expr` above. 

The proposal is to call the function `Keyword.bool/3` (and possibly a Keyword.bool!/2), their docs are indicated below:

```elixir
@doc """
Retrieves a boolean value for `key` from `dict`.

In case there is no such key, `default` is returned
(`default` defaults to `false`).

In case there is a key and the value is not a boolean,
an error is raised.
"""
def bool(dict, key, default)

@doc """
Retrieves a boolean value for `key` from `dict`.

In case there is no such key, an error is raised.

In case there is a key and the value is not a boolean,
an error is raised.
"""
def bool!(dict, key)
```

Thoughts?

**Comment by philosodad** [comment]
Should this throw a generic runtime error or a custom error?

**Comment by philosodad** [comment]
An alternate approach to this might be to add get/4 or fetch/3, taking a function as the last argument--in that case `is_boolean` is a special case of a generic capability.
