### ISSUE TITLE
Types defined in a module are not visible in other module after import.

### ISSUE THREAD

**Issue by wkhere** [elixir-lang/elixir#2567]
Simplest example:

``` Elixir
defmodule Foo do
  @type t :: String.t
end

defmodule Bar do
  import Foo

  @spec quux(t) :: any
  def quux(x), do: x
end 
```

```
% mix
lib/foo.ex:6: warning: unused import Foo

== Compilation error on file lib/foo.ex ==
** (CompileError) lib/foo.ex:8: type t() undefined
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:170: :elixir.erl_eval/3
    (elixir) src/elixir.erl:158: :elixir.eval_forms/4
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) src/elixir.erl:170: :elixir.erl_eval/3
```

Elixir 0.14.3

(of course in the real world equivalent of Foo is not only used for defining types).

**Comment by mguimas** [comment]
Any chance this might get implemented after all these years? or it a topic to be closed?

**Comment by umuro** [comment]
_Example:_
`
@type html_tree :: Floki.html_tree
`
Simply redeclare types you would like to use without a module name.
The topic is closed but I am writing this as a tip for who would still search the topic.

**Comment by kyleVsteger** [comment]
Posting a (probably hacky) solution because this was driving me nuts too. 

```elixir
```
