### ISSUE TITLE
Mix is horribly slow when a high open-file ulimit is set

### ISSUE THREAD

**Issue by tsutsu** [elixir-lang/elixir#2571]
Here's a regular Docker session containing a Mix task:

```
root@048d82b6188e:/build# ulimit -n
4096
root@048d82b6188e:/build# time (mix deps.get --no-compile)
[...]
real      1m8.753s
user      0m5.516s
sys       0m4.286s
```

Now here's one with a higher open-file-descriptors ulimit set (which happened to be the default on my system):

```
root@63fdb1ab978f:/build# ulimit -n
524288
root@63fdb1ab978f:/build# time (mix deps.get --no-compile)
[...]
real      2m44.383s
user      0m46.817s
sys       0m27.514s
```

As far as I can tell, this is what's going on:
1. Mix spawns git as a port process.
2. Erlang ports create subprocesses using `child_setup`.
3. `child_setup` closes open file-descriptors to ensure the child has no access to them.
4. Either Mix, or the Erlang VM itself, keeps tons of open file descriptors around that `child_setup` has to close each time it's called.
5. Linux does not support `closefrom(2)`, so `child_setup` has to close all these FDs in sequence.

Given a Mix task that spawns N subprocesses while holding M FDs open, this amounts to O(NM) extra context switches from system calls to `close(2)`, which shakes out as a ~3x slowdown on our workload.

**Comment by zeha** [comment]
Just chiming in here that I've encountered the same problem while running `mix test` in Docker, and the default ulimit of 1048576. For me that made the build actually hang completely and timeout after an hour (not a huge codebase).

```
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [hipe]
Elixir 1.10.2 (compiled with Erlang/OTP 22)
Mix 1.10.2 (compiled with Erlang/OTP 22)
```
(This is the elixir, erlang from the `elixir:latest` Docker image.)

**Comment by zeha** [comment]
Related info for people stopping by in the future: https://groups.google.com/forum/#!topic/rabbitmq-users/7FiPdGJ6aco

**Comment by zeha** [comment]
And, otp 23 will (hopefully) fix it: https://github.com/erlang/otp/pull/2438
