### ISSUE TITLE
Provide watcher handlers in the GenEvent module

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2662]
Basically the idea is: should we provide the watcher handlers functionality as part of GenEvent?

If so, we need to APIs, one that starts the GenEvent handler along side its GenServer to be embedded as part of a supervision tree and another that starts it directly in a given supervision tree. I thought about the name `add_watched_handler/3` (I would prefer `add_sup_handler/3` but that would cause confusion with Erlang's) and have the `:sup` option when you want to embed it on a particular supervisor.

/cc @fishcakez

**Comment by lexmag** [comment]
I've found myself a couple of times reimplementing `Logger.Watcher`; are there any plans to have the `GenEvent.Watcher`? I'd like to work on it if it's needed.

**Comment by josevalim** [comment]
This is closed because the plan is to get rid of GenEvent in the long term.

**Comment by edgurgel** [comment]
If anybody is looking for a solution while we don't have a replacement for GenEvent, here's my library that mimics `Logger.Watcher` behaviour: https://github.com/edgurgel/watcher

(Feel free to delete my comment if this shameless ad of the project is not acceptable :P)

**Comment by pedroassumpcao** [comment]
@josevalim your comment is from August 2015, are the plans of removing GenEvent still a thing? I am asking this as I am working with it right now, just wondering if I should consider :gen_event instead.

**Comment by josevalim** [comment]
We may deprecate it but it won't be removed before Elixir 2.0 so there is plenty of time. I wouldn't  worry about it.
