### ISSUE TITLE
Allow mix to pass compiler options to erlang

### ISSUE THREAD

**Issue by ewildgoose** [elixir-lang/elixir#2665]
At present it's possible to compile Elixir to HiPE native code using something like the following command line:

  ERL_COMPILER_OPTIONS="[native,{hipe, [o3]}]" mix compile 

However, it's not clear how to do the same through the mix config file?  Something which seems "close" is the project option: ":erlc_options", however, I can't figure out the syntax on how this passes through to the underlying compiler?

I tried adding the config option below, but it doesn't work as expected:
  erlc_options: [:native, {:hipe, [:verbose, :o3]}],

Can this be done through the existing :erlc_options feature (I think perhaps it can?)  Failing that can we please add a new config option to pass this through?

(Justification: On my sample project invoking tight loops I get nearly a 2x speedup using the native compiler)

**Comment by mgwidmann** [comment]
Would be nice if `ERL_COMPILER_OPTIONS="[native,{hipe,[o3]}]"` were rolled into nice compact `--native` flag to `mix compile --native` or `mix deps.compile --native some_project` ... 

Theres no way I'm going to remember `ERL_COMPILER_OPTIONS="[native,{hipe,[o3]}]"`...

**Comment by c0b** [comment]
but how about other compiler options, if I want to set for erl project wide? in my pure erlang project, I use a Makefile and `erlc -I .../include -DHAVE_UNIT ... parse_transform` like long options, to compile all erl files, if I want to switch to mix managed, how can I save the same set of options to mix.exs ?

**Comment by josevalim** [comment]
@c0b if your project has a makefile, you can tell Mix to use when it when compiling your project:

    {:my_erl_dep, "~> 1.0.0", compile: "make compile"}

**Comment by c0b** [comment]
because its Makefile is using an old build framework (build from configure.ac and autoconf/automake) which we want to get rid of, and I see most elixir projects doesn't need a Makefile; one pain point in rebar2 and resolved in rebar3 is about the need of makefile; most rebar2 project is still relying on a Makefile and rebar3 doesn't need that.

I'm evaluating the way of building a pure erlang project with mix, just wonder is it possible to write erl_compile_options in mix.exs file ? like the `erl_opts` in rebar.config ? or will it be a new feature request to mix ?

1. http://kelly-mclaughlin.com/blog/2014/12/12/building-an-erlang-project-with-mix/
2. https://github.com/rebar/rebar/blob/master/rebar.config.sample#L26-L33

**Comment by josevalim** [comment]
Yes, it is definitely possible. `:erlc_options` in your `mix.exs` file. For more info, run `mix help compile.erlang`. :)

**Comment by c0b** [comment]
@josevalim could you post a gist for how to do that if you have an example? I'm with erlang for some years but still entry with elixir/mix, can't figure out how to write there; I searched a little bit but couldn't find any good ones, and official docs is only a reference, I'm not seeing any good tutorial, if you know any good ones will be appreciated

1. http://featurebranch.com/using-mix-to-compile-your-erlang-projects/
2. http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Deps.Compile.html

**Comment by josevalim** [comment]
I am sorry. I believe you should be able to run it by adding the following inside `def project`in your mix.exs:

```elixir
def project do
  [...,
  erlc_options:  [:no_debug_info, {:i, 'myinclude'}],
  ...]
end

**Comment by c0b** [comment]
is there some debugging command line switches for mix tool? like if a Makefile not working as expected we can call it by `make --debug` it will show a lot of verbose information really useful for debugging
