### ISSUE TITLE
Should --werl be made the default?

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2682]
Or there were some drawbacks? @chyndman do you remember why it was made opt-in?

**Comment by Hades32** [comment]
Win10 brings a much better shell and fwiw most people I know have long resolved to something like ConEmu on Windows. So I don't see much use in werl anyway...

**Comment by bitwalker** [comment]
@Hades32 the one thing werl gives you is access to the `CTRL+G` command menu, which neither ConEmu nor the builtin shell with Windows (including 10) allow. This gives you the ability to do things like remote shell to another node from the current one, list jobs, kill jobs, etc. It may be less commonly used during development, but is a pretty important feature when debugging running applications.

**Comment by josevalim** [comment]
Do the arrows work on Win10 finally?



*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
