### ISSUE TITLE
Should elixir (and other applications) have sticky ebins directories?

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#2728]
Should it be allowed to overwrite elixir (and `:iex`) modules? In OTP `:compiler`, `:stdlib` and `:kernel` have sticky ebin directories. Is it possible things will break if modules are loaded? Certainly the `:iex` shell might break if some of its modules are `reloaded` a few times.

For more information see: http://www.erlang.org/doc/man/code.html#stick_dir-1

**Comment by josevalim** [comment]
I am closing this because we already warn when a module is being accidentally recompiled. Glad to revisit this in the future or if you think we should really do it.
