### ISSUE TITLE
Tasks forces the compilation of project

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#2786]
All tasks that are not builtin or are archives will force the project and its dependencies to be recompiled.

This stems from the removal of `Mix.Task.run "loadpaths"` from `Mix.CLI`. This will make the task unavailable which will trigger the compilation of the project (and the loading of the project and deps).

@josevalim What do you think the best solution is here? I know there was some reason why `Mix.Task.run "loadpaths"` was removed.

**Comment by josevalim** [comment]
I see the issue. Maybe we should first loadpaths and then, if there is still no task, we try to compile?
