### ISSUE TITLE
Compiler warning when using a variable bound in assert_receive

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#2798]
The following code causes the compiler to emit a warning:

```elixir
assert_receive {:ok, num}  # line 10
assert ^num = 13           # line 11
```

```
test/exunit_export_test.exs:11: warning: variable num@1 exported from 'receive' (line 10)
```

Example repo with 2 tags: `warning` and `no-warning` – https://github.com/alco/ex_unit-warning-exported-var

**Comment by lexmag** [comment]
It happens beyond `assert_receive` example with every `macro+export_head` following `^`, e.g:
```elixir
destructure([x], [3])
^x = 3
```
and comes from `erl_lint.erl`.
