### ISSUE TITLE
Mix app.start does not run main app as permanent

### ISSUE THREAD

**Issue by edgurgel** [elixir-lang/elixir#2862]
Right now mix app.start does not run the main app as permanent. If the main application shutdowns because of multiple failures in the app supervisor for example, you get a shutdown message and the runtime stays there running. This is a problem if you are using mix to run your application in production (this is the advised way to run apps on Heroku).

Here's a way of reproducing: https://github.com/edgurgel/crash

After talking with @ericmj, my suggestion is that we add a way to run the main app as permanent, something like:

`mix run --no-halt --permanent` 

Or maybe accept the possible values as an argument

`mix run --no-halt --type permanent`

The possible values are: temporary, transient or permanent

In contrast, the main app is run as permanent in releases generated by exrm/relx (at least that's what I get by default)

**Comment by josevalim** [comment]
This is on v1.0 and master. Will be released as part of v1.0.4.

**Comment by edgurgel** [comment]
Awesome! :+1:
