### ISSUE TITLE
Float.parse("0.3534091") loses last digit

### ISSUE THREAD

**Issue by sunaku** [elixir-lang/elixir#2867]
Using:

``` sh
$ iex
Erlang/OTP 17 [erts-6.1] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]

Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
```

I observe:

``` elixir
iex(1)> Float.parse("0.3534091")
{0.353409, ""}
iex(2)> {:erlang.list_to_float('0.3534091'), ""}
{0.3534091, ""}
iex(3)> {:erlang.list_to_float('0.3534091'), ""} == Float.parse("0.3534091")
false
```

Erlang's float parsing yields the correct result.  Please fix Elixir's accordingly.

**Comment by sunaku** [comment]
@josevalim This was patched before Elixir 1.0.4 right?  There seems to be a regression: :scream:

```
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:24:24] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Float.parse("0.3534091")
{0.353409, ""}
iex(2)> {:erlang.list_to_float('0.3534091'), ""}
{0.3534091, ""}
iex(3)> {:erlang.list_to_float('0.3534091'), ""} == Float.parse("0.3534091")
false
```

**Comment by josevalim** [comment]
We fixed this only in master I believe?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by sunaku** [comment]
Hmm, aren't releases made directly from the master branch? :sweat_smile:  Since the fix was committed on Dec 2, 2014 and Elixir 1.0.4 was released on Apr 7, 2015, I expected that the bug would be fixed in Elixir 1.0.4. :disappointed:

**Comment by ericmj** [comment]
1.0.* releases are made from the v1.0 branch. The master branch will be released as 1.1.0.

**Comment by sunaku** [comment]
Thanks, I didn't know that. :sweat_smile: Any chance this bug fix can be backported to the v1.0 branch? :innocent:

**Comment by josevalim** [comment]
Good call! It has been backported. :)

**Comment by sunaku** [comment]
Hurray! :tada: Thank you. :bow: I'm looking forward to the next v1.0.5 release. :gift:
