### ISSUE TITLE
Uri query parsing of key with `[]` keyword

### ISSUE THREAD

**Issue by SocialfiPanda** [elixir-lang/elixir#2876]
Just a discussion. In Rails and PHP, they parse a uri of something like `http://localhost:3000/?foo=1&bar[]=2&bar[]=3`to `Parameters: {"foo"=>"1", "bar"=>["2", "3"]}`.

Yet right now we just treat `bar[]` as a literal string, so:

```
iex(1)> URI.decode_query("foo=1&bar[]=2&bar[]=3")                       
%{"bar[]" => "3", "foo" => "1"}
```

Is one better than another? I will really appreciate any response. :smile:

**Comment by CrowdHailer** [comment]
Is there any reason why URI only does basic parsing? @jw2013 did you find a roll your own library or did you just end up using plug
