### ISSUE TITLE
Allow inspect opts to be given to error logger handler

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2880]

**Comment by fishcakez** [comment]
Is this a better solution than #3403?

**Comment by josevalim** [comment]
No, we still need #3403 because most people won't remember to customize these until they start getting the errors in production. So #3403 is certainly a better default.

**Comment by fishcakez** [comment]
Do we need options for Exception functions that do inspecting too?

**Comment by josevalim** [comment]
I thought about it and for now I am thinking that catching the state and last message is enough. The only issue is UndefinedFunctionError which may have the whole state in it.... thoughts?

**Comment by fishcakez** [comment]
Any stacktrace can have arbitrarily big terms in the arguments list. Erlang code, unlike Elixir, usually uses `error/2` which adds the arguments of the current function to the stacktrace like `UndefinedFunctionError` (`:undef`). 

If a GenServer terminates abnormally its likely that a caller (or more) will also crash. In this case the callers are going to exit with `{reason, {:gen_server, :call, [process, message, timeout]}}`, where `message` is the last message.

**Comment by fishcakez** [comment]
Erm `message` may not be the last the message, but I mean the term will be like the last message (the same type of term).
