### ISSUE TITLE
Crash when installing from homebrew

### ISSUE THREAD

**Issue by zipme** [elixir-lang/elixir#2911]
I installed the latest version (1.0.2) via homebrew

```
> brew update 
> brew install elixir
> elixir --version

{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

**Comment by art-solopov** [comment]
Have the same issue. Ubuntu 14.04.2, Erlang OTP 17.0. Installed according to the instructions.

```
{"init terminating in do_boot",{{badmatch,{error,{elixir,{bad_return,{{elixir,start,[normal,[]]},{'EXIT',{{badmatch,{error,enotsup}},[{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,272}]}]}}}}}}},[{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,75}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

Here's the crash dump (renamed to *.txt for convenience: http://www.mediafire.com/view/lv20h1ymd9svn37/erl_crash.dump.txt)

**Comment by art-solopov** [comment]
In fact, here's what happens when I try to compile Elixir:

```
art-solopov@desktop ~/built-software/elixir-1.0.3 > make                                                                                                              [ 2015-04-02 23:39:19 ]
==> elixir (compile)
Compiled src/elixir_parser.yrl
Compiled src/elixir_scope.erl
Compiled src/elixir_import.erl
Compiled src/elixir_dispatch.erl
Compiled src/elixir_try.erl
Compiled src/elixir_compiler.erl
Compiled src/elixir_utils.erl
Compiled src/elixir_exp.erl
Compiled src/elixir_clauses.erl
Compiled src/elixir_counter.erl
Compiled src/elixir.erl
Compiled src/elixir_exp_clauses.erl
Compiled src/elixir_aliases.erl
Compiled src/elixir_env.erl
Compiled src/elixir_module.erl
Compiled src/elixir_bootstrap.erl
Compiled src/elixir_errors.erl
Compiled src/elixir_map.erl
Compiled src/elixir_interpolation.erl
Compiled src/elixir_rewrite.erl
Compiled src/elixir_locals.erl
Compiled src/elixir_fn.erl
Compiled src/elixir_lexical.erl
Compiled src/elixir_bitstring.erl
Compiled src/elixir_def_defaults.erl
Compiled src/elixir_sup.erl
Compiled src/elixir_tokenizer.erl
Compiled src/elixir_code_server.erl
Compiled src/elixir_translator.erl
Compiled src/elixir_quote.erl
Compiled src/elixir_for.erl
Compiled src/elixir_def_overridable.erl
Compiled src/elixir_config.erl
Compiled src/elixir_def.erl
Compiled src/elixir_parser.erl
==> bootstrap (compile)
{"init terminating in do_boot",{{badmatch,{error,{elixir,{bad_return,{{elixir,start,[normal,[]]},{'EXIT',{{badmatch,{error,enotsup}},[{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,272}]}]}}}}}}},[{elixir_compiler,core,0,[{file,"src/elixir_compiler.erl"},{line,209}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: *** [lib/elixir/ebin/Elixir.Kernel.beam] Ошибка 1
```

**Comment by josevalim** [comment]
You are using Erlang 17.5, I assume, which won't work with latest Elixir. A new version is coming out soon.

**Comment by art-solopov** [comment]
@josevalim: Thank you!

**Comment by buchpaulo** [comment]
when I run mix I receive 
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

{"init terminating in do_boot",{{badmatch,error},[{'Elixir.System',build,0,[{file,"lib/system.ex"},{line,172}]},{'Elixir.System',build_info,0,[{file,"lib/system.ex"},{line,164}]},{'Elixir.Kernel.CLI',parse_shared,2,[{file,"lib/kernel/cli.ex"},{line,153}]},{'Elixir.Kernel.CLI','shared_option?',3,[{file,"lib/kernel/cli.ex"},{line,113}]},{'Elixir.Kernel.CLI',main,1,[{file,"lib/kernel/cli.ex"},{line,14}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({{badmatch,error},[{Elixir.System,build,0,[{_},{_}]},{Elixir.System,build_info,0,[{_},{_}]},{Elixir.Kernel.CLI,parse_shared,2,[{_},{_}]},{Elixir.Kernel.CLI,shared_option?,

Crash dump is being written to: erl_crash.dump...done

**Comment by josevalim** [comment]
@buchpaulo which Elixir version you have installed locally?

Your error seems to indicate that Elixir itself was compiled with a wrong version, which is very weird.

**Comment by buchpaulo** [comment]
version (1.6.6-2)

**Comment by buchpaulo** [comment]
now I did purge Elixir and Erlang and reinstall. Now the terminal run
Erlang but when I try iex or elixir it doesn't recognize.

$ sudo apt-get install elixir
Reading package lists... Done
Building dependency tree
Reading state information... Done
elixir is already the newest version (1.6.6-2).
The following package was automatically installed and is no longer required:
  libodbc1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 271 not upgraded.
$ elixir
bash: /usr/bin/elixir: No such file or directory
$ iex
bash: /usr/bin/iex: No such file or directory

**Comment by buchpaulo** [comment]
Thank you very much. It works now.

Em qui, 19 de jul de 2018 12:27, José Valim <notifications@github.com>
escreveu:

**Comment by buchpaulo** [comment]
ola ,

Estou trabalhando em um  projeto que necessita medir o request e a
resposta  que passam pelo httpoison. Voce conhece alguma biblioteca que eu
possa usar.

Obrigado pela atencao.
