### ISSUE TITLE
Enforce ranges first and last to have the same type

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2912]
Although we won't enforce it when the range is created, any operation with the range will require such. The goal is to solve that `1.5 in 1..3` returns true but `1.5 in Enum.to_list(1..3)` does not.

**Comment by oneeman** [comment]
Could you elaborate a little bit?  I'm afraid I don't really understand the example, `1.5 in 1..3`.  I take it that the goal is for it to return `false`, whereas it currently returns `true`.  But `1..3` does have `first` and `last` of the same type, so I don't understand how enforcing that requirement would affect it.

**Comment by josevalim** [comment]
Sorry, I was not precise. We need to enforce the first and last are the same so then we start enforcing that the argument given on inclusion (the left side) is of the same type too.

**Comment by oneeman** [comment]
Some relevant discussion from the IRC logs (March 8th, 2015), for future reference:

```
15:39 <oneeman> josevalim: so the idea is for 1.5 in 1..3 to raise an error rather than return false, right? [sorry if this showed up twice, I got disconnected and think the first one didn't make it to the IRC server]
15:39 <josevalim> yes
15:39 <josevalim> i don't know how to do it though
15:39 <josevalim> because one can do
15:39 <josevalim> x in y..z
15:39 <josevalim> inside guards
15:40 <oneeman> ah, so that's problematic because it has to restrict itself to other things that are allowed or because it can throw an error?
15:49 <oneeman> josevalim: ^^ (oops, didn't include your name)
15:50 <josevalim> because it has to restrict itself
15:50 <josevalim> the problem though is with floats and integers
15:50 <josevalim> if we know the values at compile time
15:50 <josevalim> we can generate optimized code
15:50 <josevalim> but if we don't, i have no idea
15:51 <josevalim> another idea is to not allow y..z in guards
15:51 <oneeman> I see
15:51 <ericmj> josevalim: dont we know the range at compile time when used in guards?
15:51 <josevalim> not necessarily
15:51 <josevalim> ericmj: but we could add this limitation
15:52 <josevalim> ericmj: it would make our lives much easier
15:52 <josevalim> that may be the way to go
15:52 <oneeman> only allow 'in' in guards if the endpoints are literals?
15:52 <ericmj> it will be impossible with structs though
15:52 <ericmj> until we have map expressions in guards
```

**Comment by josevalim** [comment]
Just linking #3374.

**Comment by fishcakez** [comment]
I like the idea of integers only because its simple and will always work for everything.

**Comment by josevalim** [comment]
We have two options here:

1. Allow only integers

2. Allow both integers and floats but do not allow checking for the inclusion of floats in the range if both sides are integers

Complexity-wise the solutions are the same. For the dynamic case, the first requires all three to be integers. The second requires one of the two to be floats or the third to be integer.

Thoughts?

/cc @fishcakez @ericmj @alco @lexmag @benwilson512

**Comment by benwilson512** [comment]
I still think there's value to biting the bullet and saying that
```
foo |> Enum.member?(set)

**Comment by benwilson512** [comment]
I still think there's value to saying that the following aren't equivalent.

```elixir
set |> Enum.member?(foo)
set |> Enum.to_list |> Enum.member?(foo)
```
Not all sets can be represented as lists. Enum.member works for unbounded numerical sets, it works for time, really any kind of value that's truly continuous.

Here's a good example. Suppose we have struct that represents a mathematical function, and membership testing is trivially implementable. We may be very interested in implementing Enumerable.reduce for it such that it generates discrete data at some configurable sampling interval. However, given what you're enumerating over, you would never suppose that Enum.member?(equation, value) would be identical to Enum.to_list |> Enum.member?

As far as that pertains to this discussion, you simply allow ints / floats as the predicates for both the range and membership testing, and only allow reduce on int bounded ranges. It's just a documentation problem.

**Comment by benwilson512** [comment]
Maybe a more nuanced version is this. If you want to make `Enum.member?` and `Enum.to_list |> Enum.member?` equivalent, that's fine. Both belong to the Enum module where the premise is that we're treating the data structure in question as a thing that can have one thing pulled after another.

However, the `in` macro needn't play by the same rules as `Enum.member?`. `in` for Range could do pure lt/gt testing. That does leave a question about how `in` behaves in / out of guards for things that aren't ranges however.

I do see you're point, I'm just fishing for a way in which the discreteness assumptions baked into most of Enum can have some kind of limit to them.

**Comment by lexmag** [comment]
I like the integers only approach, it's just a simple and natural compromise.

> .. but do not allow checking for the inclusion of floats in the range if both sides are integers

It could still bring confusion to the people.

**Comment by igas** [comment]
@josevalim @lexmag sounds reasonable, but shouldn't we provide some alternative like `Enum.cover?` or any other to not check `>` / `<` for floats every time?
