### ISSUE TITLE
Enum.sample/1 should raise if the list is empty

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2916]
We should also discuss what happens with `Enum.sample/2` if we get a sample smaller than the asked for. /cc @herenowcoder

**Comment by herenowcoder** [comment]
Hi folks and all the best in the new year.

Now some reminders from a [past](https://github.com/elixir-lang/elixir/pull/2584) discussion to get the context.

We've chosen reservoir sampling for `Enum.sample/2` to be able to process collections which don't fit in memory - implies that collection will be iterated at most once. This in turn implies that we don't know input collection count up front, we know it only after processing it.

This has an obvious advantage over a naive approach of obtaining the size of the input while buffering it and then picking elements from random indexes.

If you think of finishing the sampling earlier than input collection ends, note that this particular algo doesn't work this way AFAIR - it needs to process it to the end to make the probabilities right. Thus, it narrows "collection will be iterated at most once" to "exactly once".

HTH
