### ISSUE TITLE
State of Agents being shared between ExUnit's tests

### ISSUE THREAD

**Issue by Irio** [elixir-lang/elixir#2929]
In a small application built using Agents and Supervisors, the value of an Agent set in a test is visible to another one.

``` elixir
# test/portal_test.exs
defmodule PortalTest do
  use ExUnit.Case

  test "transfer: push data into left struct" do
    Portal.shoot(:orange)
    Portal.shoot(:blue)
    Portal.transfer(:orange, :blue, [1])
    assert [1] == Portal.Door.get(:orange)
    assert [] == Portal.Door.get(:blue)
  end

  test "existent value" do
    assert [1] == Portal.Door.get(:orange)
  end
end
```

The test suite may pass at first, but fails after some retries. Taking some time, I can narrow the bug better, but decided to report in case is something obvious (for you) or an intended behaviour. For me, it seems that the state is not being cleared in suite's teardown.
## How to reproduce
1. Clone https://github.com/Irio/debug_ex_unit_teardown.
2. Run `mix test` multiple times (5 should be enough to see the bug happening).

**EDIT:** Or maybe it's just because tests are run in parallel and both tests are using the API to connect with the same Agent.

**Comment by alejandrodnm** [comment]
Just for the record (I was looking for this xD), this is the updated [Mix & OPT](https://elixir-lang.org/getting-started/mix-otp/docs-tests-and-with.html#running-commands) link, the one posted by José changed.

You have to stop and start the application between tests like this:  

```elixir
setup do
  Application.stop(:your_app)
  :ok = Application.start(:your_app)
end
```
