### ISSUE TITLE
Raise a more meaningful error when using attributes inside match in module

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2963]
```elixir
defmodule Oops do
    @my_const = 42
end
```

**Comment by whatyouhide** [comment]
I'm **very** new to the interiors of Elixir and to Erlang as well, but I'd like to give this a try.

The error you get (on Elixir 1.0.2) when running the snippet above is:

``` elixir
** (CompileError) iex:1: cannot invoke remote function Module.get_attribute/3 inside match
```

The key function *should* be `elixir_translator:assert_allowed_in_context/5`, whose implementation is:

``` erlang
assert_allowed_in_context(Meta, Left, Right, Arity, #elixir_scope{context=Context} = S)
    when (Context == match) orelse (Context == guard) ->
  case (Left == erlang) andalso erl_internal:guard_bif(Right, Arity) of
    true  -> ok;
    false ->
      compile_error(Meta, S#elixir_scope.file, "cannot invoke remote function ~ts.~ts/~B inside ~ts",
        ['Elixir.Macro':to_string(Left), Right, Arity, Context])
  end;
assert_allowed_in_context(_, _, _, _, _) ->
  ok.
```

Should one just check that `Left`, `Right` and `Arity` match `Module.get_attribute/3` or the issue should be solved in a more generic way?

**Comment by josevalim** [comment]
You can solve it more generic way in the `@` implementation:

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L2001

Basically, if you are not inside a function and inside a match context (this information is available in the __CALLER__), we need to raise. :) Let me know if you have further questions.

**Comment by lexmag** [comment]
@whatyouhide any further work on it? I'd like to pick it up :bowtie:.

**Comment by whatyouhide** [comment]
@lexmag I haven't been able to come up with a working solution, my Elixir-fu is still rough :smile: I'll be happy to learn something from your solution, so go ahead! :+1:

**Comment by lexmag** [comment]
@whatyouhide great. Thank you.
Here is a PR: #3005
