### ISSUE TITLE
Support C-l to clear the terminal screen

### ISSUE THREAD

**Issue by jbnicolai** [elixir-lang/elixir#2967]
App: IEx
Type: feature request

IEx already seems to support the most frequently used [`readline`](http://tiswww.case.edu/php/chet/readline/rltop.html#Documentation) [keyboard shortcuts](http://tiswww.case.edu/php/chet/readline/rluserman.html#SEC6), as `C-a` to move to the start of line, `C-e` to move to the end, `C-w` to delete the previous word and `C-u` to delete the previous line, but not `C-l` the clear the screen.

IEx also exposes `clear/2` in `iex/helpers.ex`, so what I would like to request is mapping `C-l` to trigger the same function as defined in `clear/2` to clear the screen.

This would be consistent with how bash, zh, the default python shell, and most other shells operate.

**Comment by CarlosAlexSF** [comment]
`
