### ISSUE TITLE
iex doesn't interact with prompt from :ets.i/1

### ISSUE THREAD

**Issue by adamkittelson** [elixir-lang/elixir#2978]
erl:
````
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V6.3  (abort with ^G)
1> ets:i(ac_tab).
<1   > {{loaded,stdlib},
... irrelevant data omitted ...
EOT  (q)uit (p)Digits (k)ill /Regexp -->q
ok
2>
````

iex:
````
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :ets.i(:ac_tab)
<1   > {{env,logger,console},[]}
... irrelevant data omitted ...
(c)ontinue (q)uit (p)Digits (k)ill /Regexp -->q
(c)ontinue (q)uit (p)Digits (k)ill /Regexp -->q
(c)ontinue (q)uit (p)Digits (k)ill /Regexp -->q
(c)ontinue (q)uit (p)Digits (k)ill /Regexp -->
````

I would expect 'q' to return me to the iex prompt the same way it returned me to the erl prompt in the erl example, but instead it just re-prompts, it seems to do that regardless of input given.

**Comment by josevalim** [comment]
We need to send a patch to OTP to fix this one. Basically this line can return lists or binaries:

https://github.com/erlang/otp/blob/maint/lib/stdlib/src/ets.erl#L1615

We just need to rewrite binary cases back into lists. I have done a similar thing in this commit previously accepted:

https://github.com/erlang/otp/commit/4525bc59822acf0dfffa1edc64125c180d29e59e

**Comment by josevalim** [comment]
OTP pull request sent here: https://github.com/erlang/otp/pull/597

**Comment by adamkittelson** [comment]
Thanks Jose!
