### ISSUE TITLE
Specifying nil in dependency specification does not produce an error

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#2979]
The following example shows that we get an error about an invalid dep specification.
```elixir
# mix.exs
defp deps do
  [{:porcelain}]
end
```
```
λ mix deps
** (Mix) Dependency specified in the wrong format:

    {:porcelain}

Expected:

    {app, opts} | {app, requirement} | {app, requirement, opts}

Where:

    app :: atom
    requirement :: String.t | Regex.t
    opts :: Keyword.t
```

We can see that `{app, opts}` is a valid format where `opts` is a keyword. Yet, when we provide `nil` instead of a keyword, no error is emitted:

```elixir
defp deps do
  [{:porcelain, nil}]
end
```
```
λ mix deps
* porcelain (Hex package)
  the dependency is not available, run `mix deps.get`

λ mix deps.get
Running dependency resolution
Unlocked:   porcelain
Dependency resolution completed successfully
  porcelain: v2.0.0
* Getting porcelain (Hex package)
Checking package (https://s3.amazonaws.com/s3.hex.pm/tarballs/porcelain-2.0.0.tar)
Using locally cached package
Unpacked package tarball (/Users/alco/.hex/packages/porcelain-2.0.0.tar)
```

The spec above is parsed as `{app, nil, []}`. This should produce an error because the version requirement is neither a string nor a regex here.

**Comment by ericmj** [comment]
The dependency specification docs should be updated, setting it to nil is valid.

**Comment by josevalim** [comment]
It should be invalid imo. There is no reason to leak it to the DSL (although it can be nil internally), no?

**Comment by ericmj** [comment]
It can be nil internally and we support `{:ecto, []}` which is the same thing as `{:ecto, nil, []}` so I don't see any reason to limit it. I don't have strong opinions about this though.
