### ISSUE TITLE
Mix has to be stricter when parsing options in dependency specifications

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#2980]
For example, Mix doesn't check that the value of the `:only` key is an atom. This results in the dependency being unavailable regardless of `MIX_ENV` when the value is not an atom.

```elixir
# mix.exs
defp deps do
  [{:ex_doc, "~> 0.6.2", only: 1+2}]
end
```
```
λ mix deps
# no output
λ MIX_ENV=3 mix deps
# no output
```

A related problem is that unrecognized options are silently ignored:

```elixir
defp deps do
  [{:ex_doc, "~> 0.6.2", nly: :docs}]
end
```
```
λ mix deps
* ex_doc (Hex package)
  the dependency is not available, run `mix deps.get`
```

**Comment by josevalim** [comment]
We can solve the first but we cannot solve the second because options are passed to SCMs (and SCMs can use it as a way to keep metadata).
