### ISSUE TITLE
Sanity check information given to @compile

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2983]
Today we just pass the information forward to the erlang compiler but we should explicitly whitelist what is allowed.

**Comment by alco** [comment]
What's the rationale? Do we need to check the options to provide better error messages or to limit the set of allowed options?

**Comment by josevalim** [comment]
It was to limit the set of allowed options. Although we have discussed this personally and we arrived at a conclusion. Do you remember what it was?

**Comment by lpil** [comment]
Do we know what we want to whitelist here?

**Comment by josevalim** [comment]
Today we allow everything to be given. I wanted to start avoiding things like parse transforms and other things that are specific to Erlang and may not hold true in Elixir forever.

**Comment by josevalim** [comment]
Closing this. I found that @compile in Erlang does not do any checking by default for extensibility reasons. So as long as we support things like parse transforms, there is nothing we can do either.
