### ISSUE TITLE
Raise syntax error on :foo.Bar

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2986]

**Comment by bgianfo** [comment]
I was looking into this, but it I'm finding it kind of ill defined.  Would you mind providing a bit more detail?

Are you suggesting that any atom which contains a '.' should be a syntax error? or just in the form you are pointing out here... for instance what happens to the special atom ":..." https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_tokenizer.erl#L267 

It looks like the fix would be made in the tokenizer, specifically unsafe_to_atom, correct? 
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_tokenizer.erl#L637

**Comment by josevalim** [comment]
@bgianfo atoms can have `.` as long as they are quoted. So `:"foo.Bar"` is valid. However, `:foo.Bar` or `:"Foo".Bar` should be invalid. So it is more likely this issue should be fixed in the parser.
