### ISSUE TITLE
Add column info to token metadata and ast metadata

### ISSUE THREAD

**Issue by alehander42** [elixir-lang/elixir#2987]
Lint tools, code quality tools, refactor plugins, editor plugins/modes etc
work best with a good ast representation. In order to analyse and reformat/refactor code automatically, a tool needs precise location info about each token/ast node.
However currently elixir's tokenizer and elixir's parser return only line info about tokens/nodes.

[Previous discussion](https://groups.google.com/d/msg/elixir-lang-core/jqKLX3HuOxQ/9DmhX3GoixQJ)

**Comment by josevalim** [comment]
We can close this in favor of the pull request. :D
