### ISSUE TITLE
Include Docs in precompiled.zip for the windows installer

### ISSUE THREAD

**Issue by V01D-eXe** [elixir-lang/elixir#2989]
It would be very good if the docs for every release could be bundled with precompiled.zip for the windows installer. That way if anyone wants to go through them without internet access he will be able to do that easily. Plus it is much better than cloning the docs repo or getting/extracting the docs from the source.

**Comment by eksperimental** [comment]
I am not too sure about including the docs with the precompiled version, because that can increase the size, but...
one thing it will not hurt doing is provide a compressed version of the docs for easier download

**Comment by V01D-eXe** [comment]
yep that can do. 
Also include an option to get the docs in the installer, so that anyone who wants to download the docs altogether(someone like me), he can do so.

**Comment by V01D-eXe** [comment]
Also, is the Makefile in the precompiled.zip necessary or can that be removed.

**Comment by josevalim** [comment]
I have on my todo to frequently push the docs to readthedocs, where people will be able to download PDF copies too.
