### ISSUE TITLE
Define a struct type and raise if someone attempts to redefine a built-in @type

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#2990]

**Comment by ericmj** [comment]
:+1: for `@type struct :: %{__struct__: module}`. Raising on redefining built-in type is a breaking change so lets go with a warning for now?

**Comment by josevalim** [comment]
@ericmj today we already raise for most types and the code is broken for those do override it, so I believe we can raise from 1.1 onwards.
