### ISSUE TITLE
Auto-completion fail in iex with error message

### ISSUE THREAD

**Issue by xumingthepoet** [elixir-lang/elixir#2992]
Hey, i am not sure if it is a bug or sth.

$ iex
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> LiSt. (tab)
16:17:42.091 [error] Loading of /usr/local/Cellar/elixir/1.0.2/bin/../lib/elixir/ebin/Elixir.LiSt.beam failed: :badfile

16:17:42.093 [error] beam/beam_load.c(1250): Error loading module 'Elixir.LiSt':
  module name in object code is Elixir.List

**Comment by josevalim** [comment]
I would say it isn't and it is not a bug. While it is nice to get a report the module name is invalid, the report is kind of bad. :( On the other hand, there isn't much we can do to fix it.

Thanks for reporting!

**Comment by v6** [comment]
// , Does Elixir still report in this way?
