### ISSUE TITLE
How do you access root project deps_path?

### ISSUE THREAD

**Issue by josephDunne** [elixir-lang/elixir#3012]
How do I get the root project's deps_path? I have a mix task which compile MIBS for my project. I set the mib_include dir in project A mix.ex as:
```
mib_includes: ["#{Mix.Project.deps_path}/project_b/priv/mibs"]
```
as you can see I depend on project_b mibs. This works fine until I include project A as a dependency in a third project. When the mib task runs it will set the mib_includes to:
```
deps/project_a/deps/project_b/priv/mibs
```
I want it to be set to the following regardless of what the root project is:
```
deps/project_b/priv/mibs
```

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by josevalim** [comment]
In any case, you might want to look into: `Mix.Project.build_path`. Check Mix.Project documentation for more info.
