### ISSUE TITLE
Should :==== be an atom?

### ISSUE THREAD

**Issue by microamp** [elixir-lang/elixir#3014]
Just picked up an Elixir book today, playing inside iex mostly.

```
Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> is_atom :=
true
iex(2)> is_atom :==
true
iex(3)> is_atom :===
true
```

But,

```
iex(4)> is_atom :====
...(4)> 
```

It looks as if the last `=` is being treated as the pattern matching operator `=` instead. If I type `:===` in the next line like below,

```
iex(4)> is_atom :====
...(4)> :===
true
```

And if I type something else that would not match against `:===`, it would give me a `MatchError`. 

```
iex(10)> is_atom :====
...(10)> :=
** (MatchError) no match of right hand side value: :=
```

Any idea what is happening here? Thanks!

**Comment by josevalim** [comment]
`:====` isn't an atom! You can use quote and Macro.to_string to see what is really happening:

```iex
iex> Macro.to_string quote do: is_atom :==== :=
"is_atom(:=== = :=)"
```

So you actually have the atom `:===` followed by `=`. :)

**Comment by microamp** [comment]
@josevalim, thanks for the clarification. Good to know about the macro trick too.

:+1:
