### ISSUE TITLE
Debian package needs dependency to erlang-crypto and erlang-syntax-tools

### ISSUE THREAD

**Issue by hisashim** [elixir-lang/elixir#3019]
(Maybe I should contact Erlang Solutions, but I could not find their 
BTS. Excuse me for reporting it here. If you point me to the right place, 
I'd appreciate it.)

I suppose I have found a slight inconvenience in the package for 
Debian/Ubuntu, though it works great once installed properly.

Symptom:

Debian package version of iex raises an error if crypto.app and 
syntax_tools.app are not installed, which are included in packages 
erlang-crypto and erlang-syntax-tools.

Steps to reproduce the problem:

    % wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    % sudo dpkg -i erlang-solutions_1.0_all.deb

    % iex
    Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
    
    *** ERROR: Shell process terminated! (^G to start new job) ***

    % sudo apt-get install erlang-crypto erlang-syntax-tools

    % iex
    Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
    
    Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)>

(Installing a package erlang may have fixed this, but I felt like 
installing minimum set of packages.)

I guess adding dependencies to those packages in elixir_*.deb can fix this.

  debian/control:

    Depends: ..., erlang-crypto, erlang-syntax-tools

Or, updating the document something like as follows, as a temporary 
workaround:

  http://elixir-lang.org/install.html:

    Ubuntu 12.04 and 14.04 / Debian 7

     Add Erlang Solutions repo: wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
     Run: sudo apt-get update
    +Run: sudo apt-get install erlang-crypto erlang-syntax-tools 
     Run: sudo apt-get install elixir

Thank you.

**Comment by josevalim** [comment]
I have reported it to the Erlang Solutions team. Thank you!

**Comment by hisashim** [comment]
Great, thank you!
