### ISSUE TITLE
Expose app.start more clearly

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3020]
Today, `app.start` is not shown on `mix help`. This is good because this task should not be invoked directly but also bad because developers implementing custom tasks often need to call it and they don't know it it exists.

This is a proposal to expose `app.start` on `mix help`. We could also take the opportunity to implement a `mix app` task that shows the current application data (name, location, registered processes, applications, etc).

This is an open discussion, so please give feedback!

**Comment by jcspencer** [comment]
This sounds like a great idea to me. `app.start` is very useful in the case you gave (starting the application from a custom mix task), and is not well documented, as you said. If it's not classified as a breaking change, could it be merged into a 1.0.x release?

In regards to a `mix app` task, I'm curious as to what the output format would be, and which application data would be best/most important to show users.

**Comment by josevalim** [comment]
I think we should show as much information as possible from the app files. I would avoid adding those changes to 1.0 though. They won't break anything but they don't add much in my opinion to justify backporting them.

**Comment by jcspencer** [comment]
I think adding `app.start` to mix help in 1.0.x would be useful, but I don't think back-porting a new `mix app` task would be necessary at all.

**Comment by josevalim** [comment]
> I think adding app.start to mix help in 1.0.x would be useful

I don't want to expose the app.start task without having a parent task. It feels weird. We only do it for escript.build and it was planned. :)

**Comment by jcspencer** [comment]
That's a good point, I didn't think about that.

**Comment by philss** [comment]
I like the idea of expose basic information about the app in a mix task. Specially the registered processes and applications.
So `mix app` is welcome!

Valim pointed some items to display already:
- name;
- location;
- registered processes;
- applications.

In additional we could display:
- mix environment;
- dependencies;
- app version;
- elixir version.

Essentially everything that is required in `mix.exs` could be displayed.

The layout could be a simple table following the style of `mix help` (title in yellow, with fixed width).
An example below (disconsider the table headers): 

#### Application details

attribute | value
----------: | -------- 
app name                    | awsome_app
app version                 | 0.1.0
elixir version                | >= 1.0.0
location                       | "/home/user/awesome_app/ebin"
registered processes  | process1, process2, process3, process4 ..
applications                 | logger, ecto, postgrex
mix environment          | dev
dependencies              | postgrex ~> 0.7.0, ecto ~> 0.7.2

**Comment by josevalim** [comment]
Thanks for the feedback @philss! My concern with your proposal is that it is mixing the project with the application. Mix is about your project: it tells how to compile and so on. The application is about how to run your compiled code and what it contains. So we could include a lot of what you mentioned, it is a very good starting point, but we should skip the mix environment and dependencies. :)

**Comment by fishcakez** [comment]
`:application.get_all_keys/1` might be useful for `mix app`. Could probably display all the information returned there, `:env` and `:description` keys might be of interested that haven't already been mentioned.

**Comment by philss** [comment]
Thanks for the explanation @josevalim! I got your point.

One question about registered processes: is it enough to take the list of registered processes without start the application? And another question: should we show processes related to elixir or erlang vm (not related to my project)?

**Comment by josevalim** [comment]
The registered processes should be explicitly filled in by the user. Nobody does it today but it is a practice we should start doing.

**Comment by josevalim** [comment]
If it helps though, the use of Elixir aliases for naming processes help greatly with avoiding the need of registering processes.
