### ISSUE TITLE
Consider seeding random in elixir_code_server?

### ISSUE THREAD

**Issue by devinus** [elixir-lang/elixir#3022]

**Comment by josevalim** [comment]
More info please? :)

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by devinus** [comment]
It would be nice to use Enum.sample without having to call :random.seed. I never understood why Erlang didn't just seed random itself.

**Comment by josevalim** [comment]
I don't see how the code server would solve this. The code server is just a process in the elixir supervision tree. I have no idea how we could set a seed to all spawned processes.

**Comment by devinus** [comment]
Is `random.seed` per-process? I didn't know that.

**Comment by josevalim** [comment]
Ah yes, it uses the `pdict`.
