### ISSUE TITLE
If mix tool have install package and save to deps like nodejs npm install --save

### ISSUE THREAD

**Issue by developerworks** [elixir-lang/elixir#3030]
npm of nodejs support `--save` command line option that can write deps back to `package.json` file. 

I down kown whether or not mix support this functionality.

May be mix could add deps by the following way:

```
defmodule AddDeps do
  def add_deps(pkg, version) do
    "mix.exs" 
    |> File.read!
    |> Code.string_to_quoted!
    |> Macro.prewalk(fn
      {:defp, line, [{:deps, _, _ } = x, [do: deps]]} -> 
        {:defp, line, [x, [do: [{pkg, version} | deps]]]}
      others -> 
        others
    end)
    |> Macro.to_string
  end
end
```

**Comment by josevalim** [comment]
Please bring those discussions to the elixir core or elixir talk mailing lists. It is not possible today but it can be easily done as:

    $ iex -S mix
    Mix.Project.config[:deps]
