### ISSUE TITLE
Mix.shell.cmd should use System.cmd/3

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3031]
Today, there is an over reliance on `os:cmd/1` commands inside Mix which is bad due to quoting and other factors. We should drop Mix.shell.cmd usage and rely on System.cmd instead.

**Comment by bbense** [comment]
It's not entirely clear to me what you want. Do you want to deprecate Mix.shell.cmd and replace it with 
System.cmd, or create a Mix.shell.cmd that takes a list rather than a single string and uses System.cmd ?

**Comment by ericmj** [comment]
@josevalim We also need to make sure we can still handle the `:compile` option for deps.

**Comment by josevalim** [comment]
We cannot replace them all but I think we can at least replace all other ones (in utils, git, cmd and so on). In fact mix/tasks/cmd is actually broken as it won't preserve the argument quoting.

**Comment by bbense** [comment]
I've made one change to git.ex to verify that I'm on the right track on the kind of changes you want. 

https://github.com/elixir-lang/elixir/pull/3076

**Comment by bbense** [comment]
I think I've got git.ex sorted except for one thing. 

I replaced Mix.shell.cmd and while the tests pass there are lot's of messages about cloning from the git tests. 

Cloning into '/Users/booker/projects/elixir/elixir/lib/mix/tmp/Mix.Tasks.DepsGitTest/test does not load bad mixfiles on update/deps/git_repo'...

My first guess is to just merge stderr into stdin using :stderr_to_stdout , but I'm not entirely sure that something else isn't going on.

**Comment by josevalim** [comment]
I think it is likely stderr_to_stdout, yes.

**Comment by bbense** [comment]
Where exactly is the src to Mix.shell.cmd ? Setting stderr_to_stdout makes the git clone messages go away.

**Comment by josevalim** [comment]
https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/shell.ex#L69-L103

**Comment by bbense** [comment]
Okay, now I'm much more confident that setting stderr_to_stdout is the correct thing to do.

**Comment by bbense** [comment]
So to be absolutely clear, Mix.shell.cmd is bad, but Mix.Shell.cmd is an entirely different thing. 

From what I can see, the two places that use Mix.shell.cmd are git.ex and util.ex.

**Comment by josevalim** [comment]
We still use Mix.shell.cmd in deps.compile too but going on with the ones in util would be a great next step.

**Comment by bbense** [comment]
This one has me stumped 

    command = ~s[$ErrorActionPreference = 'Stop'; ] <>
                  ~s[$client = new-object System.Net.WebClient; ] <>
                  ~s[$client.DownloadFile(\\"#{path}\\", \\"#{out_path}\\")]
        Mix.shell.cmd(~s[powershell -Command "& {#{command}}"])

I've no experience with powershell and do not know what it expects for tokens in ARGV or if it even has ARGV. Poking around in the powershell docs it seems like this should work. 

    System.cmd("powershell",["-Command","& {#{command}}"])

**Comment by josevalim** [comment]
I am not sure if we need the double escape here though: `~s[$client.DownloadFile(\\"#{path}\\", \\"#{out_path}\\")]`. It would be nice to test on Windows to be sure. :(

**Comment by josevalim** [comment]
There is a bug in Erlang ports, and therefore System.cmd, where it does not execute .cmd extensions on Windows. Unfortunately we will have to revert all of those changes. :(

**Comment by josevalim** [comment]
Reverted in master. Closing this, thank you.
