### ISSUE TITLE
Mix should suggest which command to run when deps.update is needed

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3038]
I have been working in ex_doc with a branch that required a higher dependency, 
when  I roll back, mix.lock doesn't match the installed deps.

```
ex_doc/$ mix compile
Unchecked dependencies for environment dev:
* earmark (Hex package)
  lock mismatch: the dependency is out of date
** (Mix) Can't continue due to errors on dependencies
```
So i get this error. But it doens't suggest any option.
I think it should say something like.
```
** Run `mix deps.update earmark` or `mix deps.update --all` to update dependencies.

**Comment by josevalim** [comment]
The problem is that we don't know what to run. It could either be a get or an update, depending on how you want to fix it (keep the lock one or not). If we could automatically fix it or know what to run, we would just run it. :) Maybe we could talk about both.

**Comment by josevalim** [comment]
But it could also be a compilation issue. So maybe the best is to say on the lock mismatch note to run deps.get.

**Comment by eksperimental** [comment]
I have bumped into this issue again.
I intentionally deleted the mix.lock file and the message is still not descriptive. 

```sh
$ MIX_ENV=test mix do clean; mix test test/ex_doc/retriever_test.exs
Unchecked dependencies for environment test:
* earmark (Hex package)
  the dependency is not locked
* hoedown (https://github.com/hoedown/hoedown.git)
  the dependency is not locked
* markdown (https://github.com/devinus/markdown.git)
  the dependency is not locked
** (Mix) Can't continue due to errors on dependencies
```

I think we should check if the mix.lock file is missing, and give a similar message as in https://github.com/elixir-lang/elixir/commit/2aa2bdda2a7cd546da847a2b2bfd8c6ae6ed6630

**Comment by ericmj** [comment]
Looks like we should add the same message to `:lockoutdated` and `:nolock`.

**Comment by eksperimental** [comment]
@ericmj sure, no problems.
