### ISSUE TITLE
Logger formats an exit/1 as an ErlangError in OTP behaviour terminate reasons

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#3052]
In 17.4 and beyond the stacktrace (yay!) is always included in the error logger message (exit signal remains unchanged).
```
GenServer #PID<0.62.0> terminating
Last message: {:update, #Function<6.90072148/1 in :erl_eval.expr/5>}
State: nil
** (exit) an exception was raised:
    ** (ErlangError) erlang error: {:noproc, {GenServer, :call, [:noproc, :oops, 5000]}}
        (elixir) lib/gen_server.ex:357: GenServer.call/3
        (elixir) lib/agent/server.ex:20: Agent.Server.handle_call/3
        (stdlib) gen_server.erl:607: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:639: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3
```

**Comment by fishcakez** [comment]
To clarify It is nolonger possible to differentiate between an `exit/1` and an `:elang.error/1` (ErlangError) in OTP behaviour logged messages because the stacktrace is now included in the reason for `exit/1`:

17.0-17.3: It is not possible to differentiate between an `exit/1` and returning `{stop, ...}`. Currently both of those are assumed to be `exit/1` and it is possible to differentiate those with an error exception using an assumption[1].

17.4: It is not possible to different between an `exit/1` and an `:erlang.error/1`. It is possible to differentiate between returning `{stop,...}` and an `exit/1` or `raise` using the same assumption[1].

This issue epitomises the difference between Erlang and Elixir error handling and how custom errors from Erlang code do not fit well in the context of Elixir. Fortunately these are rare except when emulating a runtime error and usually it is `badarg` and not a custom error that Elixir can not normalise. Note that the Erlang docs suggest using `exit/1` unless emulating runtime errors.

In order to keep logging consistent between 17.0 and 17.4 I propose that for formatting OTP reasons in Logger we use `** (stop)` at the start of all reasons, instead of `** (exit)`.

If the reason does not include a stacktrace[1], then the reason is formatted using `** (stop) " <> Exception.format(:exit, reason, [])`:
```
** (stop) :reason
```
17.0-17.3: This covers `{:stop, :reason, .._}` and `exit(:reason)`.
17.4: This covers `{:stop, :reason, ...}`.

If the reason does include a stacktrace[1] and `normalise(reason, stacktrace)` does not return an `ErlangError`:
```
** (stop) an exception was raised:
     ** (Exception) blah
          (elixir) lib/agent/server.ex:20: Agent.Server.handle_call/3
```
17.0-17.3 AND 17.4: This covers `raise` and `:erlang.error/1` (when the error emulates a real emulator error).

If the reason does include a stacktrace[1] and `normalise(reason, stacktrace)` returns an `ErlangError`, use `** (stop) " <> Exception.format(:exit, reason, stacktrace)`:
```
** (stop) :reason
          (elixir) lib/gen_server.ex:357: GenServer.call/3
```
17.0-17.3: This covers custom reasons in `:erlang.error/1`.
17.4: This covers custom reasons in `:erlang.error/1` and `exit/1`.

This means that for Elixir code the logs are consistent between 17.0 and 17.4, except that `exit/1` calls have stacktraces in 17.4. When using Erlang code there might be some cases where a custom `:erlang.error/1` call looks like an `exit/1`. However from 17.4 this will include the stacktrace which will point to the `:erlang.error/1` call - assuming Erlang does not add emulator errors Elixir can not normalise.

For Elixir it would be nice if reasons were of the form:
```elixir
{:error, reason, stacktrace}
{:exit, reason, stacktrace}
{:throw, value, stacktrace} # throws are caught in OTP behaviours
reason # or {:stop, reason}
```

**Comment by josevalim** [comment]
That sounds like a good plan. If something gets too complex, we should prefer to make 17.4 look better, because that's likely what we will have to live with for the rest of our lives.

Also, why would they change it on a 17.x release? :S

**Comment by fishcakez** [comment]
What if someone raises `ErlangError` explicitly?

**Comment by josevalim** [comment]
It could only be raised via a re-raise. If you do something like:

```elixir
try do
  # something that raises badarg
rescue
  e -> reraise e, System.stacktrace
end
```

Or something of sorts. People should not raise  it directly.

**Comment by fishcakez** [comment]
How to handle that situation when formatting though?

**Comment by josevalim** [comment]
No idea. Maybe we could just format as an error if we have an elixir exception (i.e. no normalization). I know it is not ideal but with a stacktrace now, most of the erlang error messages would be readable. Wdyt?
