### ISSUE TITLE
Rename Precompiled files

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3070]
I think it will be a good idea to rename the precompiled and the compressed files offered at https://github.com/elixir-lang/elixir/releases

A week ago when we were trying to track down a bug that was present in master but not in previous versions, I had to used the precompiled version, but since they are just named "Precompiled.zip" it's impossible to know what version it is, or even what software it is, once it got lost in your in people's download folder,

So instead of having:
https://github.com/elixir-lang/elixir/releases/download/v1.0.2/Precompiled.zip

I propose having:
https://github.com/elixir-lang/elixir/releases/download/v1.0.2/elixir-v1.0.2-precompiled.zip

which keeps the same naming convetion has the tar.gz and .zip files for the source code.

What do you guys think?

**Comment by josevalim** [comment]
We can't change it now because there are many build tools, installers and scripts that rely on on the current naming. :( We could publish two versions but it would add extra work. At least the precompiled package is tiny so people can just download it again. :)

**Comment by eksperimental** [comment]
oh, i had no idea about other tools relying on it :-(
