### ISSUE TITLE
`iex -S mix run --no start` loading :logger

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3071]
In http://elixir-lang.org/getting-started/mix-otp/supervisor-and-application.html#starting-applications
mentions that if i load iex with
`iex -S mix run --no-start`
it shouldn't load anything (includding logger),
the thing is that it is

```
./ab$ iex -S mix run --no-start
Erlang/OTP 17 [erts-6.3] [source] [smp:2:2] [async-threads:10] [kernel-poll:false]
Compiled lib/ab.ex
Generated ab.app
Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Application.start(:ab)
:ok
iex(2)> Application.start(:logger)
{:error, {:already_started, :logger}}
iex(3)> Ab.Mixfile.application  
[applications: []]
```

I have even removed from applications in mix.exs the logger app, but it is still there.
Maybe it's related to the iex environment only.

**Comment by eksperimental** [comment]
here's another log to exemplify better:

```
$ iex -S mix run --no-start
...
iex(1)> Application.start(:logger)
{:error, {:already_started, :logger}}
```

**Comment by josevalim** [comment]
We need to update the guide. Logger is started and not starting actually caused bugs. :)

**Comment by eksperimental** [comment]
thank you!
