### ISSUE TITLE
Parenthesis not required for [x y z, q]

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#3074]
`[x y, q]` errors that parentheses are required to resolve the ambiguity, but it does not error for `[x y z, q]`.

**Comment by josevalim** [comment]
@oneeman I had to revert the pull request because it broke some Elixir code. You can find the explanation in this commit: https://github.com/elixir-lang/elixir/commit/4ecc9ee1dfc375294a4f61aaa58f4fed35e5d476 :)
