### ISSUE TITLE
Mix fails to connect to s3.amazon behind proxy

### ISSUE THREAD

**Issue by davebryson** [elixir-lang/elixir#3075]
I'm unable to get mix to work behind a proxy:
```
$ mix deps.get
Could not find hex, which is needed to build dependency :cowboy
Shall I install hex? [Yn] y
** (Mix) Could not access url
https://s3.amazonaws.com/s3.hex.pm/installs/list.csv, error:
{:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet,
[:inet], :econnrefused}]}
```
I have the http_proxy(s) variables set in my environment.  As a test:
```
curl https://s3.amazonaws.com/s3.hex.pm/installs/list.csv
```
works fine.     Any idea what may be causing the problem with mix?

**Comment by josevalim** [comment]
I am delegating this one to @ericmj. :)

**Comment by ericmj** [comment]
@davebryson Please run: `[System.get_env("HTTP_PROXY"), System.get_env("http_proxy"), System.get_env("HTTPS_PROXY"), System.get_env("https_proxy")]` in iex and paste the output here.

**Comment by davebryson** [comment]
Here's what I get:
["http://gatekeeper.mitre.org:80","http://gatekeeper.mitre.org:80","http://gatekeeper.mitre.org:80","http://gatekeeper.mitre.org:80"]

Again, the settings allow curl to work just fine

**Comment by ericmj** [comment]
The issue seems to be that httpc doesn't pick up the proxy options. I don't know why this happens so I'm going to try debugging the OTP code.

**Comment by davebryson** [comment]
Thanks.  I'm actually testing the connection using httpc as well - similar to: ```Mix.Utils.read_httpc```  Still seeing the same issue.  I've even tried other SSL endpoints just to make sure the issue wasn't with the S3 URL. Odd that httpc would drop the proxy options.    Thanks again!

**Comment by ericmj** [comment]
The issue is there for both HTTP and HTTPS requests.

**Comment by davebryson** [comment]
Can the issue be that ```Mix.Utils.read_httpc``` is changing the httpc profile between ```set_options``` and ```request```?  set_options uses the profile :hex while request and the other calls are using :mix.  When I change these to match, it seems to work.  Changing the profile would make the proxy setting disappear.

**Comment by ericmj** [comment]
@davebryson I've fixed that bug in master but the issue still persists.

**Comment by davebryson** [comment]
Yes you're correct.  I temporarily patched my local version of 1.0.3.  It made it past the error I reported above, but once it started to try and download deps, I received the following error when it tried to install a local copy of rebar:
```
** (Mix) Could not access url http://s3.hex.pm/rebar, got status: 403
```
Of course the same exact code works with no problem when not behind a proxy.  Forbidden (403) status code seems to be an odd error for this.

**Comment by ericmj** [comment]
How did you make it past the error above? In my local tests it doesn't solve the issue.

> Of course the same exact code works with no problem when not behind a proxy. Forbidden (403) status code seems to be an odd error for this.

Maybe the proxy blocks amazon aws? Seems like an issue with the proxy you are using.

**Comment by davebryson** [comment]
I have confirmed the fix you made to the httpc.set_options by changing the profiles to all match ```:mix```, fixes my initial problem installing hex on a fresh install of Elixir.    With the change I can run ```mix local.hex```, and successfully install hex from S3 behind a proxy. 

However, the other issues I encountered trying to install deps from hex have to do with my proxy blocking  the git port.  For others that may run into this, it can be resolved by using ```https``` vs  ```git``` for all your dependencies.  Of course this means you may have to manually manipulate where you grab the deps from.

**Comment by ericmj** [comment]
> I have confirmed the fix you made to the httpc.set_options by changing the profiles to all match :mix, fixes my initial problem installing hex on a fresh install of Elixir. With the change I can run mix local.hex, and successfully install hex from S3 behind a proxy.

That's good to hear.

> However, the other issues I encountered trying to install deps from hex have to do with my proxy blocking the git port. For others that may run into this, it can be resolved by using https vs git for all your dependencies. Of course this means you may have to manually manipulate where you grab the deps from.

Are you sure it's not git dependencies? Hex dependencies are never fetched via git.

You can use this `git config --global url."https://".insteadOf git://` to make sure git always uses https instead of editing projects manually.

**Comment by davebryson** [comment]
Interesting.  I think the fundamental problem is any ```git``` attempt vs ```https```.  I'll try what you recommend. Thanks for the quick responses. It's clear that Elixir has a solid community behind it.

**Comment by davebryson** [comment]
That doesn't resolve the problem.  After making the git config changes you mention above, I created a test project and attempted to load a dep:
```
defp deps do
  [{:cowboy, "~1.0"}]
end
```
that fails, it appears I'm running into an SSL cert issue:

```
Registry update failed (http_error)
[error] SSL: :certify: ssl_handshake.erl:1401:Fatal error: unknown ca
```

Again, if I manually reference the deps with https like this:

```
[{:hackney, git: "https://github.com/...etc"}]
```
it will work

**Comment by ericmj** [comment]
It works because one of them is a hex dependency the other is a git dependency. Of course the hex dependency doesn't care about how you configure git :). I'm guessing by the error that the proxy you are using is using a certificate that isn't signed by a certificate authority.

**Comment by davebryson** [comment]
I'm guessing that our proxy is not recognizing or trusting the certificate from hex, if I understand correctly how the flow works.  Does hex dependencies call to hex_web (via https) to resolve the deps?   Tracking the error through to Erlang, the error happens with:
```
public_key:pkix_path_validation()
```  
I've ran into problems with Erlang public_key before outside of a proxy. But I don't think that's the issue... going through our proxy can be a pain.

The configuration options with hex would be handy

**Comment by ericmj** [comment]
No, the error is likely that Hex doesn't trust your proxy's certificate since the error is from Hex - not from your proxy. Hex uses the same certificate store as Mozilla so your proxy's cert is probably self-signed (which we of course wont trust by default).

Hex never calls hex_web unless you're publishing a package, instead it calls S3.
