### ISSUE TITLE
Emit Warning when @specs are defined for a non-existent function

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3081]
I have not looked much into this one, I just bumped into this issue earlier today,

The specs were not being printed in the documentation
http://elixir-lang.org/docs/v1.0/elixir/Path.html#wildcard/2

but when I checked the source code @specs were there,
https://github.com/elixir-lang/elixir/pull/3079/files#diff-31b1addb44f00f27a17e9d4686ca3be8L587

well, as you can see, they were there but with different arity, so they belonged to a function that doesn't exist.

I think Elixir should emit a warning about defining @specs for a non-existent function, and maybe suggest a candidate if issues a function with the same name but with a different arity doesn't have a spec.
In case this is not the appropriate place I can transfer the issue to ExDoc
I'm just reporting it here, because i think the sooner this gets detected, the better, 

I'm sure once this gets implemented, many more similar issues may show up.

cheers

**Comment by josevalim** [comment]
A function wildcard/1 was actually defined there due to the default argument and Elixir already raises if you define a spec to a function that does not exist. :)
