### ISSUE TITLE
Behaviour docs should be stored in the byte code too

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3088]

**Comment by lexmag** [comment]
I’d like to give it a shot.

**Comment by josevalim** [comment]
@lexmag awesome! Go ahead and let me know if you have any questions.

**Comment by lexmag** [comment]
I think there are 2 possible places to store behaviour docs before adding them to beam chunk:
 * use same ets `docs` entry for it as all other docs do (except module doc), thus we can reuse `Module.add_doc/6` function by just adding `:defcallback` and `:defmacrocallback` to the kinds list; it makes possible to use `h` helper to get docs for the callbacks

* (https://github.com/lexmag/elixir/commit/5622c85ad7bf3f82dc0ba2cf604f26156c096a59) introduce new entry (`behaviour_docs`?) and more strict separation; this requires `elixir_docs_v2` in `elixir_module:add_docs_chunk/4` and new helper for retrieving docs in the IEx

Personally, I like the first approach but not sure how it'll work with overlapped functions, e.g. `Dict` module has same names for behaviour callbacks and for interface functions.

@josevalim what are your thoughts on it?

**Comment by josevalim** [comment]
@lexmag very nice!

I am not sure which one we should go either. @ericmj, @fishcakez and @alco, thoughts?

Btw, if we decide to go with 2, I don't think we need `elixir_docs_v2` because it is a keyword list and we are keeping it as such.

**Comment by lexmag** [comment]
In the meantime, while waiting for feedback, let’s fix the warning in master. :smile: 
```
lib/keyword.ex:1: warning: undefined behaviour function get_lazy/3 (for behaviour Dict)
lib/keyword.ex:1: warning: undefined behaviour function pop_lazy/3 (for behaviour Dict)
lib/keyword.ex:1: warning: undefined behaviour function put_new_lazy/3 (for behaviour Dict)
```
Can't we use `use Dict` instead of `@behaviour Dict` there?

**Comment by josevalim** [comment]
@lexmag let's implement manually because the implementation will certainly be faster than the one in Dict (since we can specialize it here). Please do send a PR!

**Comment by fishcakez** [comment]
I don't like the idea of `h Module.callback/2` showing the callback information because a callback is not "callable" like that. However at the same time I really like the idea of being able to do `h ..` to get the specific information. www.erlang.org/erldoc uses this format when searching.

**Comment by josevalim** [comment]
After @fishcakez comment, I have realized that 1) is not backwards compatible. We are adding entries to the list which are not "callables". This will definitely break IEx autocomplete and likely other APIs. So let's go with 2.

**Comment by lexmag** [comment]
Feels reasonable. Will continue with the 2 option then.
