### ISSUE TITLE
No warning about unused variables when the function returns a value with 2+ maps

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#3092]
Try compiling this module:

```elixir
defmodule Wat do
  def ohai(foo, bar, baz) do
    { %{}, %{} }
  end
end
```

This is the minimal test case I have found. The function body may have other code, the important thing is that the expression is a tuple/list that has at least 2 maps. It may have other elements in addition to the maps.

The moment I remove one of the maps, the `variable is unused` warnings reappear.

Tested with Elixir v1.0.3.

**Comment by josevalim** [comment]
Bug in OTP. @nox is submitting a fix!
