### ISSUE TITLE
Module resolution at compile time

### ISSUE THREAD

**Issue by jordan0day** [elixir-lang/elixir#3096]
Context: https://groups.google.com/forum/#!topic/elixir-lang-talk/Q3-bCnm6nxI

Currently, the elixir compiler does not seem to check if a module name is valid during compilation. So typos, missing aliases, etc. don't show up until runtime. Would it be possible to add an additional compiler phase where it validates whether a module name exists in a dependency? Or, as José mentions in his mailing list comment, a separate mix task?

**Comment by fishcakez** [comment]
There could be a `mix xref` task. `xref` is an application in OTP and
should be able do to what you want (and slightly more).

For more information:
http://www.erlang.org/doc/man/xref.html
https://github.com/rebar/rebar3/blob/master/src/rebar_prv_xref.erl (example
of using `xref` in a build tool)

For success typing analysis you should look at `dialyzer`:
http://www.erlang.org/doc/man/dialyzer.html
https://hex.pm/packages/dialyze (hex package for a `mix dialyze` task)

**Comment by josevalim** [comment]
@fishcakez I think we could do a better job streaming line this experience than using xref. We already compute this information for mix, so we could store it in a table that mix would use in other tasks or even in the beam code itself. There are many ways to go about this but it is a long term concern (we are talking at least 1.2).

**Comment by fishcakez** [comment]
@josevalim mix builds a callgraph?

**Comment by josevalim** [comment]
Mix stores only the remote names but it wouldn't be a stretch to make it store the calls too.

**Comment by josevalim** [comment]
We could start by first warning on bad module names. This is relatively easier to do and a good starting point.

**Comment by grundrauschen** [comment]
We often run into this issues during refactoring and still struggle a bit on using dialyzer for this part (because of a lot of false positives, which will get better in 1.2 as far as i read).
Also misspelled function names are quite a problem, which then cause difficulties during runtime.
So we would greatly appreciate this functionality to have warnings or errors for unfind modules and functions.
If it starts with some warnings it is still a great start.

**Comment by antipax** [comment]
@josevalim I'm interested in giving this a try, is that OK or not?

**Comment by josevalim** [comment]
@antipax go ahead! The current graph that we build can be seen in "lib/mix/lib/mix/compilers/elixir.ex". We could probably build and check the graph after compilation. This may take a while btw... for example, I know you don't have information like the line number where you called a module... but if we get the early warnings working... we can add this information later on. :)

**Comment by antipax** [comment]
@josevalim awesome, already had that file open! 🎉 

Sounds good.

**Comment by josevalim** [comment]
Now in master! :D
