### ISSUE TITLE
String.to_integer should also accept hex string prefixed with "0x" or "0X"

### ISSUE THREAD

**Issue by miwee** [elixir-lang/elixir#3101]
```elixir
iex(1)> String.to_integer("0x12", 16) 
** (ArgumentError) argument error
    :erlang.binary_to_integer("0x12", 16)

iex(2)> String.to_integer("12", 16)   
18
```

**Comment by josevalim** [comment]
I disagree. You are already specifying the base, so we shouldn't need to handle the 0x case.

**Comment by josevalim** [comment]
:)

**Comment by sinetris** [comment]
@josevalim however, it might make sense to have:

```elixir
defmodule String do
  def to_integer("0x"<>string) do
    :erlang.binary_to_integer(string, 16)
  end
end
```

Do you think is something that's worth to have?

**Comment by josevalim** [comment]
No in String.to_integer. Maybe to Integer.parse which could perform more robust checking. Because if it supports 0x, should it support 0xFF_DE_09? Even so, I am still not convinced.

**Comment by sinetris** [comment]
That makes sense :)
