### ISSUE TITLE
String.to_integer should also accept hex string prefixed with "0x" or "0X", in case of base value not being specified

### ISSUE THREAD

**Issue by miwee** [elixir-lang/elixir#3103]
```elixir

iex(11)> 0x12
18
iex(12)> String.to_integer("0x12") 
** (ArgumentError) argument error
    :erlang.binary_to_integer("0x12")

```

**Comment by josevalim** [comment]
Exactly, String.to_integer is not meant to support all the string notations
in the language. That is what Integer.parse or similar would do.

**Comment by josevalim** [comment]
And please don't open another issue given the previous one was already closed. We can continue the discussion there and always reopen if necessary.
