### ISSUE TITLE
Why not change README template to show the bold text?

### ISSUE THREAD

**Issue by tony612** [elixir-lang/elixir#3105]
Why not change `** TODO: Add description **` to `**TODO: Add description**` https://github.com/elixir-lang/elixir/blob/d039bfb2569e17cc4d6b6159867de5ec7cad56f0/lib/mix/lib/mix/tasks/new.ex#L192

So that the HTML content transformed from Markdown will be **TODO: Add description** instead of plain `** TODO: Add description **`

**Comment by josevalim** [comment]
Sure! Please send a pull request?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by tony612** [comment]
@josevalim ok :smile:

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
