### ISSUE TITLE
Iex crashes on Osx Yosemite 10.10.2

### ISSUE THREAD

**Issue by nitrox62** [elixir-lang/elixir#3111]
I can't launch it , it always displays that 
<Code>
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]
*** ERROR: Shell process terminated! (^G to start new job) ***
=ERROR REPORT==== 23-Feb-2015::11:18:29 ===
Error in process <0.26.0> with exit value: {{badmatch,{error,{crypto,{"no such file or directory","crypto.app"}}}},[{'Elixir.IEx',start_iex,0,[{file,"lib/iex.ex"},{line,469}]},{'Elixir.IEx','-start/2-fun-0-',2,[{file,"lib/iex.ex"},{line,455}]}]}
 </code>
Does anyone have any Idea ? Thanks

**Comment by josevalim** [comment]
There is something wrong with your crypto installation. How have you installed Erlang? Which SSL version are you running?

**Comment by josevalim** [comment]
You may want to check this issue: https://github.com/elixir-lang/elixir/issues/2342

**Comment by nitrox62** [comment]
Ok Crypto:start(). give me an error i have tried to reinstall but nothing changes

**Comment by josevalim** [comment]
How have you installed Erlang? Please try to provide as much information as you can!

**Comment by nitrox62** [comment]
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel

Sorry but it's clear... 

I reinstall with this  https://www.erlang-solutions.com/downloads/download-erlang-otp and not brew

**Comment by nitrox62** [comment]
All is ok now , thanks for all.
