### ISSUE TITLE
Add warning on missing spec

### ISSUE THREAD

**Issue by cjimison** [elixir-lang/elixir#3115]
We have a team of about 5 engineers working on elixir and it drives me crazy when they forget to add specs to their functions and dialyzer doesn't work right because of it.  It would be VERY nice if we could add the flag "warn_missing_spec" like erlang has.

Thanks!

**Comment by websymphony** [comment]
Hey @cjimison , are you passing the compilation options using ```ERL_COMPILER_OPTIONS```?
Found this: https://github.com/elixir-lang/elixir/issues/2271#issuecomment-42804217

**Comment by cjimison** [comment]
I am using an umbrella project, so some of the apps do have erlang options that use the following:

erlc_options: [{:parse_transform, :lager_transform}, :warn_missing_spec, :warnings_as_errors],

inside the mix.exs for apps the compile erlang code.

 We also have a couple of pure elixir apps that don’t use the erlc_options.  All of them show the same behavior of not warning on missing spec’s in elixir.

Thanks!

-Chris

**Comment by josevalim** [comment]
Thanks for the report. The erlc_options only apply to the erlang compiler. We are not going to support this beyond the current environment variable. The reasoning is that many of those options are specific to the erlang compiler and we support them unofficially as a simple consequence of relying on the erlang compilation stack.
