### ISSUE TITLE
Document Stream.flat_map/3 accepts :halt and add the same to Enum.flat_map/3

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3117]

**Comment by whatyouhide** [comment]
What's `Enum.flat_map/3` (or did you mean `Enum.flat_map/2`, same for `Stream`?)?

**Comment by josevalim** [comment]
Yes, sorry, flat_map/2.

**Comment by montague** [comment]
you gonna work on this @whatyouhide?

i'm looking for starter stuff to pick off, didn't want to steal your thunder :)

**Comment by whatyouhide** [comment]
Was going to work on this in a couple of hours, but please, steal my
thunder :).

On Tuesday, February 24, 2015, montague <notifications@github.com> wrote:

> you gonna work on this @whatyouhide <https://github.com/whatyouhide>?
>
> i'm looking for starter stuff to pick off, didn't want to steal your
> thunder :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3117#issuecomment-75812575>.
>


-- 

Andrea Leopardi
an.leopardi@gmail.com

**Comment by montague** [comment]
@whatyouhide, cool, thanks!

**Comment by montague** [comment]
@josevalim  i'm not sure what you mean by "accepts :halt" -- i see that flat_map_reduce accepts a tuple with ```:halt``` as the first element, but i'm not sure how ```Enumerable.flat_map/2``` or ```Stream.flat_map/2``` would accept ```:halt```. what am i missing?

**Comment by josevalim** [comment]
`Stream.flat_map/2` todays will halt if you simply return `:halt`.

**Comment by montague** [comment]
ah ok, so it's implemented in ```Stream.flat_map/2``` only at the moment?

**Comment by josevalim** [comment]
Yes, we should add it to Enum.flat_map/2.
