### ISSUE TITLE
"mix" (especially "mix help") fails in the "umbrella" directory when no project was added in the apps directory

### ISSUE THREAD

**Issue by bsmr** [elixir-lang/elixir#3120]
When I tried to run ```mix help``` in the top level directory of an "umbrella" project before I added a project in the ```apps``` directory it fails with the following message:
```bash
$ mix new --umbrella example
$ cd example/
$ mix help
** (Mix.Config.LoadError) could not load config apps/*/config/config.exs
    ** (Code.LoadError) could not load /home/family/bsmr/source/elixir/problems/example/apps/*/config/config.exs
    (mix) lib/mix/config.ex:141: Mix.Config.read!/1
    (mix) lib/mix/config.ex:153: anonymous fn/2 in Mix.Config.read_wildcard!/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:441: :erl_eval.expr/5
    (elixir) lib/code.ex:140: Code.eval_string/3
```
Within the ```apps``` directory ```mix help``` doesn't fail.

After a new project is added (within the ```apps``` directory) ```mix help``` doesn't fail in the top-level "umbrella directory".

**Note:** This bug showed up when I issued ```mix help```, but even without any arguments to ```mix``` it fails.

IMHO this is somewhat irritating, especially for newbies (like me) to Elixir.

**Comment by josevalim** [comment]
Yes, definitely a bug. Thanks for reporting!
