### ISSUE TITLE
Compiler warning information about clause matching doesn't allow find source code origin

### ISSUE THREAD

**Issue by henrythebuilder** [elixir-lang/elixir#3122]
Hi all,
In my code I have a compiler warning about 'clause re-definition'. This is useful when functions are defined in separated lines but when they are defined in some other way is difficult to find the wrong clause.
Let me show a simple example:

```elixir
1  defmodule Foo do
2    [{1,10}, {2, 20}, {3, 30}, {4, 40}, {9, 90}, {2, 22}]
3    |> Enum.map( fn({key, val}) ->
4      def bar(unquote(key)), do: unquote(val)
5    end)
6  end
```

the compiler output is:

`foo.ex:4: warning: this clause cannot match because a previous clause at line 4 always matches`

it is ok but we haven't any information about the wrong clause.
In this case we have a little and simple data so it is simple to find the wrong term but in a more complicate 'dynamic construction' is not very simple detect the term that originate the warning.
I have not found any way to detect this automatically so I think it would be very useful to have some more specific information about the clause for this kind of warning.

Thanks

**Comment by josevalim** [comment]
That's a very good point. It is a complex change because it requires actually changing the Erlang compiler. I am pinging @nox so he can tell us how feasible this is.

**Comment by henrythebuilder** [comment]
Thanks @josevalim,
I hope there will be good news from @nox.
In my small test I found (perhaps) the source origin on erlang code in [otp/lib/compiler/src/v3_kernel.erl](https://github.com/erlang/otp/blob/maint/lib/compiler/src/v3_kernel.erl) in the function [maybe_add_warning(Ke, MatchAnno, St)](https://github.com/erlang/otp/blob/maint/lib/compiler/src/v3_kernel.erl#L1033)
I tried to extract all possible information about the warning and I found these values:
```erlang
Ke = {iclause, [4, {file,"foo.ex"}], [], [], [],
      {c_literal, [], true},
      {c_literal, [0, {file,"foo.ex"}], 22}},
St = {kern, {bar, 1}, {bar, 1}, 1,0,
      {set,2,16,16,8,80,48, {[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},
      {{[cor0], [cor1], [],[],[],[],[],[],[],[],[],[],[],[],[],[]}}},[],[],[],0},
MatchAnno = [4, {file,"foo.ex"}],
```
but my reasearch stop here, I'm not an erlang/elixir guru  :satisfied:

**Comment by nox** [comment]
And what message would you want instead?

**Comment by nox** [comment]
Probably `foo.ex:4: warning: this clause with pattern 2 cannot match because a previous clause at line 4 with pattern 2 always shadows it`?

**Comment by nox** [comment]
That warning is emitted in sys_core_fold, btw. Grep for nomatch_shadow.

**Comment by henrythebuilder** [comment]
Thank @nox 
The message text you proposed is much more useful, it seems to contain the necessary information to understand the wrong term !
Regarding your indication about `sys_core_fold` I tried to change the `Line` term with some other term like `{Line, {C0, E, Ctxt, Sub}}` in [clauses function](https://github.com/erlang/otp/blob/maint/lib/compiler/src/sys_core_fold.erl#L1708) to see all the available information but I don't see anything in the output, instead making similar change in the [maybe_add_warning](https://github.com/erlang/otp/blob/maint/lib/compiler/src/v3_kernel.erl#L1043) the output change, this is not very important but where am I wrong?

**Comment by henrythebuilder** [comment]
Update:
starting from the directions suggested by @nox I made some other test in order to detect a possible way to change warning message but I haven't found any solution, I'm not able to extract function signature information from the data available around the functions used to make the warning message, so at this time my knowledge about Erlang source does not allow me to go further.
I hope @nox finds a way that makes this feasible.

**Comment by josevalim** [comment]
Closing this as it is an erlang bug and for now there isn't much we can do.
