### ISSUE TITLE
We should still return values if _ = is used on last line

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3125]
```
iex(1)> defmodule Foo do
...(1)> def bar do
...(1)> _ = for n <- 1..10, do: n * 2
...(1)> end
...(1)> end
{:module, Foo,
 <<70, 79, 82, 49, 0, 0, 5, 192, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 0, 92, 131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115, 95, 118, 49, 108, 0, 0, 0, 2, 104, 2, ...>>,
 {:bar, 0}}
iex(2)> Foo.bar
20
```

It should still return a list.

**Comment by eksperimental** [comment]
just out of curiosity, if I were to debug/trace what are the files/functions involved in calling a function like this one. what is the procedure to do this?

**Comment by josevalim** [comment]
Right now there isn't. This is done by the compiler, so you need to understand the compiler a bit to do it.

**Comment by eksperimental** [comment]
thanks @josevalim 
Is there any text that documents how the compiler works, I would like to start little by little understanding how the whole process happens.

**Comment by josevalim** [comment]
I don't think there is one yet.
