### ISSUE TITLE
Map update syntax raises semi-cryptic error

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#3126]
I wouldn't be opening this if @josevalim didn't say something like "if you get an error and you don't know what to do next, that's a bug" :smile:.

The map update syntax (`|`) raises an `ArgumentError` with message `argument error` when it's used to try and update a key that isn't in the map.

```elixir
iex> map = %{a: 1}
%{a: 1}
iex> %{map | b: 2}
** (ArgumentError) argument error
    (stdlib) :maps.update(:b, 2, %{a: 1})
    (stdlib) erl_eval.erl:255: anonymous fn/2 in :erl_eval.expr/5
    (stdlib) lists.erl:1261: :lists.foldl/3
```

I briefly tried to solve this myself by digging through `elixir/src/` but I am *deeply* unfamiliar with the Erlang side of Elixir. Is there a way this `ArgumentError` can be given a more meaningful error message?

**Comment by josevalim** [comment]
The error is generated by Erlang and there is nothing we can do. I am lobbying Erlang developers to replace this by something more decent but we don't have news yet. If Erlang doesn't change this, I will do those changes myself.

**Comment by whatyouhide** [comment]
@josevalim so the error leaks directly from `:maps.update/3`. Bummer :( well we'll see how it goes then. Thanks!

**Comment by mremond** [comment]
@josevalim I am convinced that error report in Erlang need indeed to be improved. Please, let me know if I can help you in lobbying :)

**Comment by josevalim** [comment]
I just sent an e-mail to erlang-questions.
