### ISSUE TITLE
Deprecate Keyword.get/3 and Keyword.pop/3

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3132]
The reason is to avoid the semantic difference between `Keyword.get(opts, :foo, :bar)` and `opts[:foo] || :bar`. The latter is preferable because often we don't care about making a distinction between the absence of a value and that value being set to nil.

It is also debatable if we should deprecate similar functions from Enum.

**Comment by ericmj** [comment]
How are you going to make a distinction between `false` and `nil`?

**Comment by josevalim** [comment]
Possibly `Keyword.bool/2` will help with that. That's one of the pending issues to be solved.

**Comment by whatyouhide** [comment]
Why deprecate `Keyword.pop/3` though? You mean turning it into `Keyword.pop/2` and using it like

```elixir
{val, kw} = Keyword.pop(kw, :my_val)
val || :default
```

?

**Comment by josevalim** [comment]
@whatyouhide I am not sure on pop yet. It theoretically suffers from the same issue but it cannot be expressed as concisely as get. Let's wait for more feedback before we start working on any of those changes. :)

**Comment by josevalim** [comment]
We should also look into adding a lazy_put (only puts a value is not there lazily). We need a small overhaul in the Dict API overall.
