### ISSUE TITLE
IO.ANSI.Docs.print formatting error

### ISSUE THREAD

**Issue by larshesel** [elixir-lang/elixir#3134]
Tested on master a few minutes ago:

    iex(2)> IO.ANSI.Docs.print("*hello*",[])
    hello

    :ok
    iex(3)> IO.ANSI.Docs.print("*hello*.",[])
    *hello*.

It is of course not visible here, but the first example is display with a bold font  as expected, but the second is not which is unexpected. It just returns the markup.

I found this while looking at the help for the Stream module in Iex. It has a line ending in `*eager*.`

**Comment by josevalim** [comment]
Thanks for the report!

**Comment by bbense** [comment]
The bug appears whenever the markup word ends with any char that is not in this list. 
From lib/io/ansi/docs.ex 

    # Characters that can mark the beginning or the end of a word.
    # Only support the most common ones at this moment.
    @delimiters [?\s, ?', ?", ?!, ?@, ?#, ?$, ?%, ?^, ?&, ?-, ?+, ?(, ?), ?[, ?], ?{, ?}, ?<, ?>]

We could fix the reported bug by adding ?. to the list.

**Comment by bbense** [comment]
Here's a patch with a test and the fix. I'm not entirely sure it's the correct approach. 

https://github.com/elixir-lang/elixir/pull/3137

**Comment by josevalim** [comment]
Fixed on master, thanks @bbense!
