### ISSUE TITLE
Enum.uniq/2 should be Enum.uniq_by/2

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3142]
We need to deprecate (long term) Enum.uniq/2 and start promoting Enum.uniq_by/2.

**Comment by shankardevy** [comment]
do you mean creating a new method uniq_by and deprecate the existing? I don't see Enum.uniq_by/2 available currently? I can take up this.

**Comment by josevalim** [comment]
The idea is to just rename the current Enum.uniq/2 to Enum.uniq_by/2 but still leave a Enum.uniq/2 definition that calls Enum.uniq_by/2 because we can't remove code. It will likely be officially removed just on Elixir 2.0.
