### ISSUE TITLE
&<=/2 becomes :erlang.make_fun(:erlang, :"=<", 2) in default arguments

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3143]

**Comment by AlexRiedler** [comment]
@josevalim I think that is correct behaviour? your taking the operator as a function that takes two arguments. What was the intended behaviour expected?

**Comment by josevalim** [comment]
It is ok for the compiler. The issue is that it is leaking into the documentation. If you have:

    def foo(a \\ &</2)

It becomes

    def foo(a \\ :erlang.make_fun(:erlang, :<, 2)

in the docs.

**Comment by eksperimental** [comment]
It is also happening in:
ExUnit.Callbacks.on_exit/2

`make_ref`  being translated into `\\ :erlang.make_ref()`

And in IO  functions using `group_leader` becoming `:erlang.group_leader()`

**Comment by oneeman** [comment]
Looks interesting, I'll see if I can figure something out.

**Comment by josevalim** [comment]
Nice. This behaviour was changed in this commit:

https://github.com/elixir-lang/elixir/commit/2137c28e4e2d28d08451ad1a9c32caf5f5ab3c39

The change happened when we moved the [run_on_definition_callbacks](https://github.com/elixir-lang/elixir/commit/2137c28e4e2d28d08451ad1a9c32caf5f5ab3c39#diff-48ea84f09de5b6869f2793c15e811319R164) to run after the expression. I think we should revert it to the previous behaviour where it ran before.

The issue with reverting though is that variables like `@foo` won't be expanded in docs (they would show up as `foo \\ @foo`). So maybe we can traverse those inside [`Module.compile_doc`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/module.ex#L864-L881) and expand just `@` to their actual values. `Macro.prewalk` (or postwalk) can help us do it.
