### ISSUE TITLE
Protocol consolidation seems incomplete/inconsistent

### ISSUE THREAD

**Issue by gamepoet** [elixir-lang/elixir#3152]
After doing protocol consolidation, not all protocols appear to be consolidated as reported by `Protocol.consolidated?/1`. I've tried this with both 1.0.2 and master 7d81909bc74bd3ba812853a24365507614f1be64.

### Steps

```
$ mix new protocol_test
$ cd protocol_test
$ mix compile && mix compile.protocols
$ iex -pa _build/dev/consolidated -S mix
Erlang/OTP 17 [erts-6.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :code.get_path |> Protocol.extract_protocols |> Enum.each fn(x) -> IO.puts "#{x}: #{Protocol.consolidated?(x)}" end
Elixir.Access: false
Elixir.Collectable: true
Elixir.Enumerable: true
Elixir.Inspect: true
Elixir.List.Chars: false
Elixir.Range.Iterator: true
Elixir.String.Chars: true
Elixir.Access: false
Elixir.Collectable: true
Elixir.Enumerable: true
Elixir.Inspect: true
Elixir.List.Chars: false
Elixir.Range.Iterator: true
Elixir.String.Chars: true
:ok
```

Note that both `Access` and `List.Chars` did not get consolidated. I imagine every protocol is in the list twice because they're in the code path twice. Now to make things more interesting, add dependencies for  `ecto ~> 0.8.0` and `postgrex >= 0.0.0`.

```
$ mix deps.get && mix deps.compile && mix compile && mix compile.protocols
$ iex -pa _build/dev/consolidated -S mix
Erlang/OTP 17 [erts-6.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :code.get_path |> Protocol.extract_protocols |> Enum.each fn(x) -> IO.puts "#{x}: #{Protocol.consolidated?(x)}" end
Elixir.Access: false
Elixir.Collectable: false
Elixir.Ecto.Queryable: true
Elixir.Enumerable: true
Elixir.Inspect: true
Elixir.List.Chars: false
Elixir.Range.Iterator: true
Elixir.String.Chars: true
Elixir.Ecto.Queryable: true
Elixir.Access: false
Elixir.Collectable: false
Elixir.Enumerable: true
Elixir.Inspect: true
Elixir.List.Chars: false
Elixir.Range.Iterator: true
Elixir.String.Chars: true
:ok
```

Note that `Collectable` is now no longer consolidated.

What's going on here? Am I missing some crucial step required for proper protocol consolidation?

**Comment by josevalim** [comment]
Yes, it is a bug because the collectable protocol has been loaded before consolidation. If you call `:code.delete(Collectable)`, the new consolidated version will be loaded. This is a known bug to be fixed on 1.1. :)

**Comment by gamepoet** [comment]
Awesome. :D

Is there an existing issue I can watch to track progress on this bug? Also, are you aware that `mix compile.protocols` with an umbrella project appears overwrites the same consolidated beam files as it iterates over each project?

**Comment by josevalim** [comment]
Let's keep this one open. The previous issue was #2804 and there is a related discussion on #2862.

**Comment by gamepoet** [comment]
Thanks!

I can confirm that your suggested workaround does indeed work for the simple scenario I originally described in the bug. However, in my more complex app most of the protocols never get consolidated as reported by `Protocol.consolidated?/1` even after using `:code.delete/1`. I believe this is due to my project actually being an umbrella project with many apps that have similar dependencies (like Ecto). Do you have any suggested workarounds for this use case?

**Comment by josevalim** [comment]
@gamepoet Please try this. Copy this task to one of your projects:

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/compile.protocols.ex#L1

Remove the `@recursive true` bit and name it to something else to avoid conflicts (it can be whatever). Then try running it from the umbrella and see if it fixes the issue. This way you will have consolidation in the umbrella and passing -pa should work.

**Comment by gamepoet** [comment]
Unfortunately no. I'll see what I can do to build a simple app to demonstrate the issue so I'm not asking you to stab in the dark. :-/

**Comment by josevalim** [comment]
An app will really be a great help!

**Comment by gamepoet** [comment]
I was finally able to repro the lack of protocol consolidation while using your workaround in a simple app. It turns out that it has to do with when I was deleting code rather than the fact that I was using an umbrella project. I had originally tested code deletion from an iex session, however then integrating the workaround into my application led to failure. I injected the protocol code deletion in `Application.start/2` since that seemed like the earliest place to hook. Unfortunately the code appears to already be in use at this point and cannot be safely deleted. If launching with iex I can finally purge the code once I get a prompt but that's not going to work with a deployed app.

My simple test-case app can be created with `mix new protocol_test --sup` and replacing `mix.exs` and `lib/protocol_test.ex` with https://gist.github.com/gamepoet/8eaf42328a2e72c9b50d. Launching with iex you should be able to see that the code deletion does not succeed at boot from the output in `lib/protocol_test.ex`.

Did you have a different place in mind for doing the suggested code deletion workaround?

**Comment by josevalim** [comment]
Does it work if you reverse the order? First you purge any old version, so you can finally delete the current one? If not, I can take a look at it later. :) Thanks for the instructions!

**Comment by gamepoet** [comment]
Doesn't appear to. :(

Changing `consolidate` to:
```
  def consolidate(purge \\ false) do
    unconsolidated_protocols |> Enum.each(&purge/1)
    IO.puts "before: #{inspect unconsolidated_protocols}"
    unconsolidated_protocols |> Enum.each(&delete/1)
    IO.puts "after:  #{inspect unconsolidated_protocols}"
    if purge do
      unconsolidated_protocols |> Enum.each(&purge/1)
      IO.puts "purge:  #{inspect unconsolidated_protocols}"
    end
  end
```

gives:

```
$ iex -pa _build/dev/consolidated -S mix
Erlang/OTP 17 [erts-6.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

before: [Access, Collectable, Ecto.Queryable, List.Chars]
after:  [Ecto.Queryable]
purge:  [Ecto.Queryable]
Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
```

**Comment by josevalim** [comment]
Interesting. I have run `:code.clash` and it reported:

```
** /Users/jose/OSS/protocol_test/_build/dev/lib/ecto/ebin/Elixir.Ecto.Queryable.beam hides /Users/jose/OSS/protocol_test/_build/dev/consolidated/Elixir.Ecto.Queryable.beam
** /Users/jose/OSS/protocol_test/_build/dev/consolidated/Elixir.Access.beam hides /Users/jose/OSS/elixir/bin/../lib/elixir/ebin/Elixir.Access.beam
** /Users/jose/OSS/protocol_test/_build/dev/consolidated/Elixir.Collectable.beam hides /Users/jose/OSS/elixir/bin/../lib/elixir/ebin/Elixir.Collectable.beam
** /Users/jose/OSS/protocol_test/_build/dev/consolidated/Elixir.Enumerable.beam hides /Users/jose/OSS/elixir/bin/../lib/elixir/ebin/Elixir.Enumerable.beam
** /Users/jose/OSS/protocol_test/_build/dev/consolidated/Elixir.Inspect.beam hides /Users/jose/OSS/elixir/bin/../lib/elixir/ebin/Elixir.Inspect.beam
** /Users/jose/OSS/protocol_test/_build/dev/consolidated/Elixir.List.Chars.beam hides /Users/jose/OSS/elixir/bin/../lib/elixir/ebin/Elixir.List.Chars.beam
** /Users/jose/OSS/protocol_test/_build/dev/consolidated/Elixir.Range.Iterator.beam hides /Users/jose/OSS/elixir/bin/../lib/elixir/ebin/Elixir.Range.Iterator.beam
** /Users/jose/OSS/protocol_test/_build/dev/consolidated/Elixir.String.Chars.beam hides /Users/jose/OSS/elixir/bin/../lib/elixir/ebin/Elixir.String.Chars.beam
```

You can see that in all paths, the consolidated one hides the regular one, except for Ecto. I have checked `:code.get_path` and I could verify the consolidated path comes first. Since calling `:code.rehash` also does not solve the issue, deleting and re-adding the path does it:

    Code.delete_path("_build/dev/consolidated")
    Code.prepend_path("_build/dev/consolidated")

In any case, I believe we should work on Elixir v1.0.4 that includes protocol consolidated and embedded mode fixes. People are running into this frequently and it is about time we fix those. It cannot wait for Elixir v1.1.0.

**Comment by josevalim** [comment]
This is on v1.0 and master. Will be released as part of v1.0.4.

**Comment by reset** [comment]
Thank you @josevalim!

**Comment by gamepoet** [comment]
Thanks. I'll be taking a look at this as soon as your 1.0.4 homebrew PR gets merged.
