### ISSUE TITLE
<%% should still interpolate inner <%

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3159]
Today, the following code in eex `<%%= <%= "hello" %> %>` does not interpolate the inner `<%= %>`

**Comment by oneeman** [comment]
I'll give this a shot.

**Comment by oneeman** [comment]
Another manifestation of the incorrect current behavior:

```
iex(1)> EEx.Tokenizer.tokenize("<%% <%= foo %> <%= bar %> %>", 1)   
{:ok, [{:text, '<% <%= foo %> '}, {:expr, 1, "=", ' bar '}, {:text, ' %>'}]}
iex(2)> EEx.eval_string("<%% <%= foo %> <%= bar %> %>", [foo: "FOO", bar: "BAR"])
"<% <%= foo %> BAR %>"
```

**Comment by josevalim** [comment]
Awesome, let me know if you have any questions! I really appreciate all your help in those parser related issues.  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by oneeman** [comment]
Happy to!
