### ISSUE TITLE
Module.split is very liberal in accepted arguments, which leads to confusing results

### ISSUE THREAD

**Issue by schnittchen** [elixir-lang/elixir#3161]
Currently, Module.split accepts anything that can be converted to a string.

When passed a string that looks like a Module name, funny things happen:

```elixir
iex(1)> Module.split "Foo.Bar"
["Bar"]
```

This, however, makes sense again:
```elixir
iex(2)> Module.split "Elixir.Foo.Bar"
["Foo", "Bar"]
```

So, Module.split behaviour when passed a string depends on internal "mangling" of atoms in Elixir.
Should anything but a module be accepted?

**Comment by josevalim** [comment]
Good find. Let's assert the module starts with "Elixir.". And it should only accept atoms or strings.

**Comment by schnittchen** [comment]
I'll try to take care of that, might take a few days though.

**Comment by josevalim** [comment]
No problem, Elixir v1.1 will take a few months. :)
