### ISSUE TITLE
mix deps.get --quiet doesn't pass --quiet to git clone

### ISSUE THREAD

**Issue by MSch** [elixir-lang/elixir#3167]
We run a fresh `mix deps.get` on our CI server (Jenkins, which doesn't support the ANSI escape code git uses to replace the previous line and show progress) and it leads to really cluttered output.

`mix deps.get --quiet` should pass `--quiet` to `git clone`.

I looked at the source and didn't see an obvious way to do it, so pointers are appreciated.

**Comment by josevalim** [comment]
I am wondering if we should make it a shell configuration (`Mix.Shell.quiet?` would return true) so it would just work for everything that uses Mix.shell.

**Comment by MSch** [comment]
Sounds like a good idea to me.

**Comment by josevalim** [comment]
If this is still desired, please send a pull request. One option that came to mind is to have a MIX_QUIET=1 that sets the shell to `Mix.Shell.Quiet`. It behaves as the IO shell except that Mix.shell.info is a no-op and Mix.shell.cmd does not print anything either.

**Comment by druzn3k** [comment]
I would like to give this a spin @josevalim. I like the idea of `MIX_QUIET=1`. The only problem is that I don't know if I'm (as today) capable of doing this. Any chance of mentoring if I get stuck? Can I ask directly in this issue?

**Comment by josevalim** [comment]
@druzn3k yes, definitely!

**Comment by druzn3k** [comment]
@josevalim just a simple question (I cannot find anywhere this information): how can I test `Mix` that I'm modifying directly in `iex`? I tried launching `bin/iex`, but it loads the installed `Mix`, and not the development version.

Any hint on how to load the development version of `Mix`?

In the meantime I think that the `Mix.Shell.Quiet` is complete. :tada:

**Comment by josevalim** [comment]
@druzn3k the makefile will always run the cloned version. If you want to try it directly, you run the files in the bin directory, like `MIX_QUIET=1 bin/elixir bin/mix test`. Another idea is just add `bin` to the top of your $PATH. :)

**Comment by druzn3k** [comment]
Thank @josevalim :smile: 
In a minute I will open the PR, let me know if it's good!
