### ISSUE TITLE
make clean test

### ISSUE THREAD

**Issue by williamgueiros** [elixir-lang/elixir#3171]
hello all..

i clone repostory elixir on mac, and try run this command: make clean test

received the error:

  1) test recompiles after path dependency changes (Mix.UmbrellaTest)
     test/mix/umbrella_test.exs:156
     No message matching {:mix_shell, :info, ["Compiled lib/bar.ex"]} after 100ms. Process mailbox:
     {:mix_shell, :info, [":bar env is dev"]}
     {:mix_shell, :info, [":foo env is dev"]}
     {:mix_shell, :info, [":foo env is dev"]}
     {:mix_shell, :info, ["==> foo"]}
     {:mix_shell, :info, ["Generated foo.app"]}
     {:mix_shell, :info, ["==> bar"]}
     {:mix_shell, :info, [":foo env is dev"]}
     {:mix_shell, :info, [":foo env is dev"]}
     {:mix_shell, :info, ["Generated bar.app"]}
     {:mix_shell, :info, [":foo env is dev"]}
     Showing only 10 of 18 messages.
     stacktrace:
       test/mix/umbrella_test.exs:173: anonymous fn/1 in Mix.UmbrellaTest.test recompiles after path dependency changes/1
       (mix) lib/mix/project.ex:194: Mix.Project.in_project/4
       (elixir) lib/file.ex:1111: File.cd!/2
       test/test_helper.exs:96: MixTest.Case.in_fixture/3
       test/mix/umbrella_test.exs:157

but if i can running again using: sudo make clean test

he does't have any problem!

other issue to the same teste: https://github.com/elixir-lang/elixir/issues/2421

**Comment by josevalim** [comment]
Have you installed it in a directory that requires sudo? In which directory have you installed it?

**Comment by williamgueiros** [comment]
No i'm installed with the sudo, only clone on my home space 

pwd
/Users/williamgueiros/workspace/elixir/elixir

**Comment by josevalim** [comment]
Thank you. I have no idea why you get this warnings though. Or it is a small race condition or the timestamps of the cloned repo can be a bit off.

**Comment by williamgueiros** [comment]
ok, i can trying install ubuntu to test, and check receiving the same problema.
tks

**Comment by josevalim** [comment]
Nice thanks!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by williamgueiros** [comment]
no problem on ubuntu .
