### ISSUE TITLE
and/or should compile to erlang:and and erlang:or in guards and be strictly boolean

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3177]
See: https://groups.google.com/forum/#!topic/elixir-lang-talk/wMZ-We1TEdw

**Comment by alco** [comment]
The title implies that this will change the behavior of `and` and `or` in guards only while outside of guards they will keep their current impl. Is that intended?

**Comment by josevalim** [comment]
Inside guards it should not matter because there isn't any expression in guards where the short-circuiting matters. In fact, compiling to erlang:and/or may actually be faster due to compiler optimizations.

**Comment by josevalim** [comment]
And to be precise, we will need to first deprecate the current behaviour by warning on the second argument.

**Comment by josevalim** [comment]
We can use the __CALLER__ environment to know if we are inside a guard or not! https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/macro/env.ex#L30 With this information, we can generate a simple call to :erlang.or inside a guard otherwise a case.

**Comment by oneeman** [comment]
Yes, that works when the time comes to do the change.  But I meant with regard to issuing a deprecation warning before we make this change:

> And to be precise, we will need to first deprecate the current behaviour by warning when the second argument is not a boolean

**Comment by josevalim** [comment]
We don't need to deprecate in guards because semantically the behavior
won't change. You always need to return booleans in guards.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by oneeman** [comment]
Ah, thanks, I understand now.  It's:

(a) Inside guards: switch right away
(b) Outside guards: add deprecation warning if the second value isn't boolean

**Comment by josevalim** [comment]
Perfect!

**Comment by oneeman** [comment]
Punting this to @josevalim since doing it without winding up with `this clause cannot match because a previous clause always matches` warnings requires greater expertise.

**Comment by josevalim** [comment]
Unfortunately we cannot add this change because althought the strictly boolean aspect of guards change is backwards compatible, the short-cirtuiting aspect isn't. Sorry for the false positive folks. :(
