### ISSUE TITLE
Print full path of the generated app

### ISSUE THREAD

**Issue by shankardevy** [elixir-lang/elixir#3178]
When compiling a mix project, following the output shown to the users.

```
Compiled lib/kv.ex
Generated kv.app
```

This is bit misleading as kv.app is not generated in the root level, rather at _build/dev/lib/kv/ebin/kv.app. (or some generically at _build/[env]/...) 

Since the previous message `Compiled liv/kv.ex` shows the relative path to the file, it's normal for people to search for kv.app in the root of the project unless full path is mentioned.

**Comment by josevalim** [comment]
So I would rename it to "Generated kv app" or "Built kv app". I don't think it makes any sense to point users to the the actual .app file. :)

**Comment by oneeman** [comment]
FWIW, I like the current message.  It's somehow satisfying to see each app summed up with a filename.  It's like the compiler saying "I've worked so hard crunching this stuff, this is the result!"  Maybe it's just me, though :-)

**Comment by josevalim** [comment]
Yup, the current message definitely needs to stay. We may just need to
change it so people don't expect an .app file in their current working
directory.
