### ISSUE TITLE
IEx does not receive messages when invoked from two different tabs

### ISSUE THREAD

**Issue by shankardevy** [elixir-lang/elixir#3186]
I am using OS X Terminal. I have two tabs and I am invoking iex in both of them. 

    $ iex
    Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

    Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> 

When both the iex sessions on two different tabs have started, I find their pid being same since `self` return the same pid on both tabs
    
    iex(1)> self
    #PID<0.53.0>
    iex(2)> 

So I assume that this is basically a single process accepting inputs from two interfaces (tabs).

I am trying out a simple exercise from http://elixir-lang.org/getting-started/processes.html

```
iex> parent = self()
#PID<0.41.0>
iex> spawn fn -> send(parent, {:hello, self()}) end
#PID<0.48.0>
iex> receive do
...>   {:hello, pid} -> "Got hello from #{inspect pid}"
...> end
"Got hello from #PID<0.48.0>"
```

Instead of executing above in a single tab (which works correctly), I am executing the receive block in tab1 first and this tab now keeps waiting for the message to arrive as the message box is empty. 
```
iex> receive do
...>   {:hello, pid} -> "Got hello from #{inspect pid}"
...> end
```
Quoting from the guide
> If there is no message in the mailbox matching any of the patterns, the current process will wait until a matching message arrives. 

Now if I send  message to self from tab2, I expect tab1 to output the message and exit the receive block as tab1 and tab2 are essentially the same process. On tab2, I do this
```
iex> parent = self()
#PID<0.41.0>
iex> spawn fn -> send(parent, {:hello, self()}) end
#PID<0.48.0>
```

But still the tab1 keeps waiting for message. Is this a bug?

Questions:
1. Should two different iex sessions on different tabs share the same process?
2. how does function like v(n) work if two sessions share the same pid? The two iex sessions have different history of commands.
3. Why doesn't receive  block find the message sent to the process when the message is sent from a different tab?

**Comment by josevalim** [comment]
They are not the same process. They have the same identifier because a
local process is always shown with leading "0." and the rest happens to be
the same.

In general though, can you please send this discussion to the elixir talk
mailing list? It is not an issue report and discussions and questions
should be moved there.

Thanks!

On Wednesday, March 18, 2015, Shankar Dhanasekaran <notifications@github.com>
wrote:

> I am using OS X Terminal. I have two tabs and I am invoking iex in both of
> them.
>
> $ iex
> Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
>
> Interactive Elixir (1.0.2) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)>
>
> When both the iex sessions on two different tabs have started, I find
> their pid being same since self return the same pid on both tabs
>
> iex(1)> self
> #PID<0.53.0>
> iex(2)>
>
> So I assume that this is basically a single process accepting inputs from
> two interfaces (tabs).
>
> I am trying out a simple exercise from
> http://elixir-lang.org/getting-started/processes.html
>
> iex> parent = self()
> #PID<0.41.0>
> iex> spawn fn -> send(parent, {:hello, self()}) end
> #PID<0.48.0>
> iex> receive do
> ...>   {:hello, pid} -> "Got hello from #{inspect pid}"
> ...> end
> "Got hello from #PID<0.48.0>"
>
> Instead of executing above in a single tab (which works correctly), I am
> executing the receive block in tab1 first and this tab now keeps waiting
> for the message to arrive as the message box is empty.
>
> iex> receive do
> ...>   {:hello, pid} -> "Got hello from #{inspect pid}"
> ...> end
>
> Quoting from the guide
>
> If there is no message in the mailbox matching any of the patterns, the
> current process will wait until a matching message arrives.
>
> Now if I send message to self from tab2, I expect tab1 to out the message
> as tab1 and tab2 are essentially the same process. On tab1, I do this
>
> iex> parent = self()
> #PID<0.41.0>
> iex> spawn fn -> send(parent, {:hello, self()}) end
> #PID<0.48.0>
>
> But still the tab1 keeps waiting for message. Is this a bug?
>
> Questions:
> 1. Should two different iex sessions on different tabs share the same
> process?
> 2. how does function like v(n) work if two sessions share the same pid?
> The two iex sessions have different history of commands.
> 3. Why doesn't receive block find the message sent to the process when the
> message is sent from a different tab?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3186>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by shankardevy** [comment]
@josevalim I was thinking it was a bug and hence opened an issue. I will move it elixir-talk later today. thank you.

**Comment by josevalim** [comment]
Oh, I see. No problem then, thank you!
