### ISSUE TITLE
Uninformative error when calling a function in a keword list literal

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#3187]
This works as expected:

```
iex(2)> [wat: whatever ]
** (RuntimeError) undefined function: whatever/0
```

However, in the following examples the error does indicate what the actual problem is:

```
iex(2)> [wat(): whatever ]
** (SyntaxError) iex:2: invalid token: : whatever ]

iex(2)> [wat(: whatever ]
** (SyntaxError) iex:2: invalid token: : whatever ]

iex(2)> [wat.(): whatever ]
** (SyntaxError) iex:2: invalid token: : whatever ]

iex(2)> [(wat): whatever ]
** (SyntaxError) iex:2: invalid token: : whatever ]
```

Shouldn't it be possible for the parser to detect invalid tokens in the key position, at least when things like parentheses are balanced?

**Comment by josevalim** [comment]
The error is not happening in the parser but in the tokenizer. "foo:" and ":bar" are a valid tokens. A ":" dangling anywhere else is not a valid token. We could always improve the error message but it needs to be done in the tokenizer.

**Comment by ericmj** [comment]
Is it really that uninformative? The invalid token error follows the same format as all syntax errors:

```iex
iex(1)> 1 . 0
** (SyntaxError) iex:1: syntax error before: 0

iex(1)> *0
** (SyntaxError) iex:1: syntax error before: '*'

iex(1)> "abc" "def"
** (SyntaxError) iex:1: syntax error before: "def"
```

It shows you where tokenizer/parser starts to fail so you always know that you should look where the error points you or just before.

**Comment by josevalim** [comment]
Closing this per eric's feedback.
