### ISSUE TITLE
Alias multiple module with same parent more easily

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/elixir#3189]
Sometimes aliases get out of hand and either need to be extracted (not always ideal) or take up lots of space and are somewhat tedious to write and read through.

The example below is a common scenario when writing a Phoenix app. Would some kind of syntax like this be helpful?

```elixir
defmodule
  # Same as writing
  # alias MyApp.Post
  # alias MyApp.User
  # alias MyApp.Comment
  # alias MyApp.Repo
  alias MyApp, [Post, User, Comment, Repo]
end
```

**Comment by josevalim** [comment]
Please bring this discussion to the elixir-lang-core mailing list and once we get enough feedback and a proposal, we can open up an issue for it. :) Thanks!

**Comment by paulcsmith** [comment]
As I posted that, I realized that's probably where it should go. My bad!
