### ISSUE TITLE
Add system-related features to shell

### ISSUE THREAD

**Issue by knewter** [elixir-lang/elixir#3195]
@rvirding asked me at ErlangFactory why we don't have `i` and `regs` in iex.  I didn't know an answer.  If no one knows ahead of time that they're terribly hard to implement, I might try my hand at them.  Can't imagine there's any reason but "haven't done it yet."

**Comment by fishcakez** [comment]
Please can you add an equivalent function to `:c.pid/3` at the same time

**Comment by josevalim** [comment]
They don't exist because nobody contributed them yet. If you would like to sanity check before, just ask in the elixir-lang-core mailing list!
