### ISSUE TITLE
Compiling with: "warning: behaviour Inspect undefined"

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3204]
Compiling elixir is giving a warning:
`lib/hash_dict.ex:257: warning: behaviour Inspect undefined`
you can see it in the last build: https://travis-ci.org/elixir-lang/elixir/jobs/55719797

Could it be related to https://github.com/elixir-lang/elixir/issues/921 ?

**Comment by michalmuskala** [comment]
When I'm compiling I consistently see (both or just one of those):
```
lib/file/stream.ex:68: warning: behaviour Enumerable undefined
lib/gen_event/stream.ex:53: warning: behaviour Enumerable undefined
```
But it was always like that, so I assumed it was normal.

**Comment by pma** [comment]
I'm getting the same compiler warnings when compiling master.

```
==> elixir (compile)
Compiled lib/kernel.ex
Compiled lib/atom.ex
Compiled lib/agent.ex
Compiled lib/bitwise.ex
Compiled lib/behaviour.ex
Compiled lib/application.ex
Compiled lib/access.ex
Compiled lib/code.ex
Compiled lib/collectable.ex
Compiled lib/base.ex
Compiled lib/dict.ex
lib/file/stream.ex:68: warning: behaviour Enumerable undefined
Compiled lib/file/stream.ex
Compiled lib/float.ex
Compiled lib/file.ex
Compiled lib/gen_event/stream.ex
Compiled lib/gen_server.ex
Compiled lib/agent/server.ex
lib/hash_dict.ex:257: warning: behaviour Inspect undefined
Compiled lib/hash_dict.ex
Compiled lib/exception.ex
```

**Comment by josevalim** [comment]
It is fine. We will always have those warnings while bootstrapping the language because of the order things are defined.
