### ISSUE TITLE
Mix.Generator.from_file uses __ENV__.file which is misleading

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3208]
Since the default in Elixir is to use `__DIR__`, to have something that relies on `__ENV__.file` can be confusing. It is also worth noticing that `Mix.Generator.embed_text` also automatically adds a `_text` extension to the argument, which is also confusing.

**Comment by lexmag** [comment]
Should not `Mix.Generator.from_file` be removed?
As I see it was deprecated https://github.com/elixir-lang/elixir/commit/a6b1cca91fefca3e0eaf1009bf3340c4d51985eb and probably removed https://github.com/elixir-lang/elixir/commit/058b157b363b721b359b86aca9c17829629a9c42.

**Comment by josevalim** [comment]
Good catch, I am using it in Phoenix, I need to stop doing it. :)
