### ISSUE TITLE
Support Erlang 18.0 features

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3212]
* [x] Support `Process.get_keys/0`
* [x] Verify https://github.com/erlang/otp/pull/351 and give feedback if required
* [x] Verify badmap for maps
* [x] Support new gen:stop in GenEvent and GenServer
* [x] Use erl_anno in the new compiler
* [x] Replace all `line: -1` by generated annotations
* [x] Migrate from dicts/sets in Elixir sources to maps
* [x] Migrate from dicts/sets in Erlang sources to maps
* [x] Update license files and rename LEGAL to NOTICE (APL2 requirement)
* [x] Soft-deprecate Dict/HashDict/HashSet
* [x] Use `:rand` instead of `:random`

**Comment by lau** [comment]
The variable map keys feature in 18.0 sounds nice. Should it just work automatically?

**Comment by matrixise** [comment]
Here is my contribution for the support of `Process.get_keys/0`

PR: https://github.com/elixir-lang/elixir/pull/3241

**Comment by josevalim** [comment]
Thanks @matrixise but we can't merge it for now. I have updated the description so other developers don't send PRs that won't be merged anytime soon.

**Comment by matrixise** [comment]
But how will you implement the Process.get_keys/0 function ? About the patch, this is for the last version of Elixir and Erlang R18. In fact, I don't understand why you don't merge it for this issue. Can you explain ? thanks

**Comment by josevalim** [comment]
We won't implement it until 1.1 is out. Master today is for Elixir 1.1 and we won't start work on 1.2 until 1.1 is out. To be clear:

* Elixir 1.1 will support 17 and 18 equally. It won't introduce any feature that is 18 only (like `Process.get_keys/0`)
* Elixir 1.2 will support only 18 and it will be released shortly after 1.1 introducing only specific 18 features

**Comment by josevalim** [comment]
More clarification: the issue with your patch is that anyone using it would add an implicit dependency on Erlang 18 which would then require applications to specify both Erlang and Elixir dependencies. For example, Erlang >=18 and Elixir >=1.1.

**Comment by matrixise** [comment]
Yep, in this case, I understand. I will propose it when master will be for Elixir 1.2. Thanks for this clarification.

**Comment by fishcakez** [comment]
There is also the @optional_callbacks attribute.

**Comment by TattdCodeMonkey** [comment]
Here is an attempt at 'Support new gen:stop in GenEvent and GenServer' for your consideration.

PR #3901

**Comment by fishcakez** [comment]
optional callbacks?

**Comment by josevalim** [comment]
Let's open up another issue for it because I don't think it is high priority to make it part of 1.2. I don't find it that important, honestly, because in Elixir we can rely on `use MyMod` to define the optional stuff for you (which is better than sprinkling `function_exported?` checks IMO). :)
