### ISSUE TITLE
Add "compile failed due to warnings" message with --warnings-as-errors

### ISSUE THREAD

**Issue by perc-MikeBinns** [elixir-lang/elixir#3222]
--warnings-as-errors currently returns the correct error code when warnings are present, but no message is noted at the end of the process that warnings caused the compilation to fail. Automated systems will correctly fail, but it is not apparent to a person reading the output that 1) the compile failed or 2) why it failed.

See discussion:

https://github.com/elixir-lang/elixir/issues/3116#issuecomment-87722183

**Comment by josevalim** [comment]
This is the code:

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/parallel_compiler.ex#L61

I believe we just need to write to stdout before.
