### ISSUE TITLE
String.slice/2 different behaviour in Elixir 1.0.0 and 1.0.3 when the string ends with "\r\n"

### ISSUE THREAD

**Issue by jsvisa** [elixir-lang/elixir#3224]
In Elixir 1.0.3, See the example below:

```elixir
ex(37)> String.slice("hello\r\n", 0..-2) # Here it eats to much bytes
"hello"
iex(38)> String.slice("hello", 0..-2) # normal behaviour
"hell"
iex(39)> String.slice("hello\r", 0..-2) # normal behaviour
"hello"
iex(40)> String.slice("hello\n", 0..-2) # normal behaviour
"hello"
```

while in Elixir 1.0.0, the  behaviour is normal, I think it's a bug, if it is, I'll try to fix it later today.

**Comment by josevalim** [comment]
The behaviour in 1.0.3 is correct because String.slice/2 works on graphemes and `\r\n` is considered a single grapheme.

**Comment by josevalim** [comment]
Thank you for opening a bug report and asking though. It is very appreciated!

**Comment by jsvisa** [comment]
@josevalim  So If  I want to slice the  ending `\r\n`, maybe the string contains  more than one `\r\n`, and I don't want to judge it's Elixr 1.0.0 or Elixir 1.0.3, what should I do with a simple method? Should is effective: 

```elixir
iex(1)> :erlang.binary_part("hello\r\n", 0, byte_size("hello\r\n") - 2)
"hello"
```

**Comment by josevalim** [comment]
Yes, binary_part would be it.

**Comment by jsvisa** [comment]
@josevalim Thanks for your reply :+1:
