### ISSUE TITLE
Documention, known keywords as placeholder

### ISSUE THREAD

**Issue by andreas-roehler** [elixir-lang/elixir#3226]
Suggest not to use widely known symbols as place-holder. These might be taken for symbols pointing at implemented stuff.

elixir-lang.readthedocs.org/en/latest/ref/master/elixir/Stream/index.html#module-Stream:

iex> Enum.map range, &(&1 * 2)
[2,4,6,8,10]

Problem: range is a well known function in other languages, but used as an arbitrary identifier here:

iex> range = 1..5
1..5

While understanding the rationale behind this "speaking indentifier", it might create confusion.
"my_var" would be preferable, resp. "baz"

**Comment by lexmag** [comment]
As for me, I think it's a correct naming since `range` variable represents `Range` data type.
BTW there is the [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core) mailing list for that kind discussions. :)

**Comment by josevalim** [comment]
> Suggest not to use widely known symbols as place-holder. These might be taken for symbols pointing at implemented stuff.

This is a great opportunity to learn that `range` isn't anything special in Elixir. If we are going to not use widely known symbols... we are considering which languages? Ruby, Haskell, Erlang and maybe Java and C or Javascript?

There is no right answer here and calling it range tells what the value also is, while `my_var` or `bar` would be too empty.
