### ISSUE TITLE
bug windows file path causes crash

### ISSUE THREAD

**Issue by jschoch** [elixir-lang/elixir#3227]
not sure why this causes the vm to crash on windows.  File.stat also crashes, as does :filelib.file_size/1

``` elixir
defmodule FNTest do
  use ExUnit.Case
  test "filename blows up" do
    z = [id_global: "C66DBEBC-AD67-47E2-8B9F-1865D4529894",
      originalFilename: "RIMG0059.jpg", pathFromRoot: "",
      absolutePath: "E:/lr exports/", extension: "jpg"]
    ap = z[:absolutePath]
    ofn = z[:originalFilename]
    filename = "#{ap}#{ofn}"
    res = File.exists?(filename)
    IO.puts inspect res
  end
end

```

**Comment by josevalim** [comment]
Which Elixir and Erlang versions?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by jschoch** [comment]
this appears to be related to windows deduplication and erlang.  I submitted a bug to erlang-bugs.

i was able to reproduce with 17.3 and 17.5 on windows 2012 with deduplication turned on.  Closing the issue, hope no one else has this problem, it was not easy to figure out.
