### ISSUE TITLE
Elixir on Mint/Ubuntu broken after Erlang update

### ISSUE THREAD

**Issue by Alamoz** [elixir-lang/elixir#3233]
Just updated my Erlang APT package to the latest Erlang 17 using [erts-6.4] and now my Elixir is not working. When I enter iex this is the output:

Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

*** ERROR: Shell process terminated! (^G to start new job) ***

=INFO REPORT==== 3-Apr-2015::07:00:54 ===
    application: elixir
    exited: {bad_return,
                {{elixir,start,[normal,[]]},
                 {'EXIT',
                     {{badmatch,{error,enotsup}},
                      [{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},
                       {application_master,start_it_old,4,
                           [{file,"application_master.erl"},{line,272}]}]}}}}
    type: temporary

=INFO REPORT==== 3-Apr-2015::07:00:54 ===
    application: syntax_tools
    exited: stopped
    type: temporary

=INFO REPORT==== 3-Apr-2015::07:00:54 ===
    application: compiler
    exited: stopped
    type: temporary

=INFO REPORT==== 3-Apr-2015::07:00:54 ===
    application: crypto
    exited: stopped
    type: temporary

=ERROR REPORT==== 3-Apr-2015::07:00:54 ===
Error in process <0.27.0> with exit value: {{badmatch,{error,{elixir,{bad_return,{{elixir,start,[normal,[]]},{'EXIT',{{badmatch,{error,enotsup}},[{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},{application_master,start_it_old,4,[{file,"application_master....

**Comment by websymphony** [comment]
See https://github.com/elixir-lang/elixir/issues/2911#issuecomment-89042120

**Comment by josevalim** [comment]
Yes, it is broken, try v1.0 or master, new release coming soon.

**Comment by Alamoz** [comment]
Thank you. Building from source solved the problem. I'll keep building from source, a better method, especially considering the included test suite.
