### ISSUE TITLE
iex errors out.

### ISSUE THREAD

**Issue by lowks** [elixir-lang/elixir#3235]
I am running with the following setup:

- OS - Ubuntu-14.04
- Erlang - Installed via packages.
~/s/elixir➜ erl --version
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Eshell V6.4  (abort with ^G)
1>

- Elixir - Installed using packages too. 
All packages are from binaries.erlang-solutions.com

When I try starting up iex, I get this:

Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

*** ERROR: Shell process terminated! (^G to start new job) ***

=INFO REPORT==== 4-Apr-2015::09:45:07 ===
    application: elixir
    exited: {bad_return,
                {{elixir,start,[normal,[]]},
                 {'EXIT',
                     {{badmatch,{error,enotsup}},
                      [{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},
                       {application_master,start_it_old,4,
                           [{file,"application_master.erl"},{line,272}]}]}}}}
    type: temporary

=INFO REPORT==== 4-Apr-2015::09:45:07 ===
    application: syntax_tools
    exited: stopped
    type: temporary

=INFO REPORT==== 4-Apr-2015::09:45:07 ===
    application: compiler
    exited: stopped
    type: temporary

=INFO REPORT==== 4-Apr-2015::09:45:07 ===
    application: crypto
    exited: stopped
    type: temporary

=ERROR REPORT==== 4-Apr-2015::09:45:07 ===
Error in process <0.27.0> with exit value: {{badmatch,{error,{elixir,{bad_return,{{elixir,start,[normal,[]]},{'EXIT',{{badmatch,{error,enotsup}},[{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},{application_master,start_it_old,4,[{file,"application_master....

**Comment by josevalim** [comment]
Latest Erlang does not with Elixir. Please downgrade Erlang or use branch
v1.0.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by lowks** [comment]
Wow you are fast :) :+1:

**Comment by lowks** [comment]
Well I guess then the instructions here: http://elixir-lang.org/install.html should be changed as well since I followed this one to the tee.

**Comment by eksperimental** [comment]
@lowks: true.. while updating install.html will help, there is another well known rule of bug reporting that says,, search for your bug in the issue tracker, maybe someone else reported it before

**Comment by lowks** [comment]
@eksperimental thanks :+1:

**Comment by eksperimental** [comment]
@lowks ;-) no worries

@josevalim i think we should create an issue and leave it open reporting this issue, so it's more visible, and It will save people reporting the issue. I know 1.0.4 is on the way.. but still.

**Comment by lowks** [comment]
Just another observation is, checking for erlang versions is not exactly the most straight forward thing to do. Is there a significant number of Elixir developers who are not well versed with Erlang or I am just the minority ?

**Comment by ericmj** [comment]
> Just another observation is, checking for erlang versions is not exactly the most straight forward thing to do.

What do you mean? Checking for erlang versions that elixir supports?

**Comment by lowks** [comment]
Checking for erlang versions in general. It's version numbers are confusing

**Comment by oneeman** [comment]
@ericmj There was someone else with the same error on IRC today and it wasn't obvious to me how to check the OTP version (in the end `apt show erlang` works, but that's just for debian-based distributions). And even /usr/lib/erlang/releases/RELEASES mentioned in http://stackoverflow.com/questions/9560815/how-to-get-erlangs-release-version-number-from-a-shell doesn't say "17.x" as far as I can tell.

**Comment by ericmj** [comment]
Yes they are confusing, especially since they just changed versioning scheme. Not sure how it relates to elixir or elixir developers though.

OTP 17 is the major release which includes many new features and possibly breaking changes. 17.5 is a service release which are smaller and usually contain bug fixes and a few minor new features. Unfortunately this team they included a breaking change that caused an incompatibility with elixir.

**Comment by ericmj** [comment]
@oneeman The OTP team chose to not have an easy way of showing the service release version you are because it does not necessarily map to an exact set of installed erlang applications and their versions (you can install and patch the different applications independently that OTP bundles). Unfortunately this makes it harder for the vast majority of users that do not patch independent applications of their installation.

An easy way of checking if you have OTP 17.5+ installed is if you have erts 6.4. Check by running `iex`:

```iex
λ iex
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

**Comment by oneeman** [comment]
Ah, I see.  Thanks!

**Comment by ctaggart** [comment]
I think I have the same issue on my iMac. I'm just trying to get started. I installed both `erlang` and `elixir` using `brew`.

![image](https://cloud.githubusercontent.com/assets/80104/6998339/4ae97ff6-db93-11e4-8eb8-e7f19180384c.png)

It is not urgent. I was just looking at the new-to-me language. Do I just wait for `1.0.4` or figure out how to downgrade erlang to a compatible version?

**Comment by josevalim** [comment]
You can run `brew install elixir --HEAD` and it will install master which should be enough until v1.0.4 comes out in a couple days.

**Comment by josevalim** [comment]
You can also try this: https://github.com/Homebrew/homebrew/issues/38345 if you have a previous erlang installed.

**Comment by ctaggart** [comment]
Thanks! That worked.

![image](https://cloud.githubusercontent.com/assets/80104/6998404/22915f0c-db97-11e4-9f44-19f6b7767f63.png)

**Comment by Rastopyr** [comment]
:+1: thanks!
