### ISSUE TITLE
Try a MapSet implementation

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3242]
With Erlang 18 coming out, I am starting to believe that the fastest way to implement a Set would actually be by using a map behind the scenes. After all, a Set is a map where having a given key means the entry exists in the set.

So here is what I have in mind. We create a new MapSet struct, that implements the Set behaviour. MapSet will be defined as follows:

    defstruct set: %{}

And all functions would work on top of this set but return a `%MapSet{...}` struct. Once implemented, we could benchmark and see how it fares against the current HashSet. Note Map is faster than a HashDict on all operations on Erlang 18 (here is some [sample benchmarking](https://gist.github.com/josevalim/cd0d3ef6bcda4511da59)) although we may be slower in sets due to the %MapSet{} struct indirection. We need the indirection however if we want it to work as a struct (and have protocols and what not).

**Comment by josevalim** [comment]
@lexmag interested in experimenting with this one?

**Comment by lexmag** [comment]
@josevalim sure, would love to try.

**Comment by ericmj** [comment]
@josevalim We could consider cheating and have `defstruct []` with values directly on the struct if there is a performance benefit.

**Comment by lexmag** [comment]
@ericmj in that case with have to deal with `:__struct__` entry as a special case.

**Comment by ericmj** [comment]
Yeah, may or may not be worth it.

**Comment by josevalim** [comment]
Yeah, i didn't figure out a way to handle `:__struct__` that's why i didn't propose it. :(

**Comment by lexmag** [comment]
I've made initial implementation of `MapSet` https://github.com/lexmag/elixir/commit/a26cd96f72247f1bea6d3be56d3922f2c7e0df24 and run benchmarks for several functions https://gist.github.com/lexmag/32977ce8fd7cb44ddefa so far.

**Comment by josevalim** [comment]
If I read them correctly, the results are really, really good. Please do send a pull request. :)

**Comment by josevalim** [comment]
And before I forget, thank you for doing this!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by lexmag** [comment]
My pleasure. Will send WIP PR soonish; the result are really good, but as you might see I've done the tests not for all the functions (only BIF-based), most interesting ones are left. :smile:
