### ISSUE TITLE
Mix crashing after fresh install on OSX

### ISSUE THREAD

**Issue by TiuTalk** [elixir-lang/elixir#3251]
I've tried reinstalling **Elixir** with:

```shell
$ brew unlink elixir --force
$ brew remove elixir --force

$ brew install elixir
==> Downloading https://homebrew.bintray.com/bottles/elixir-1.0.3.yosemite.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/elixir-1.0.3.yosemite.bottle.tar.gz
==> Pouring elixir-1.0.3.yosemite.bottle.tar.gz
🍺  /usr/local/Cellar/elixir/1.0.3: 328 files, 4.3M

$ mix --help
{"init terminating in do_boot",{{badmatch,{error,{elixir,{bad_return,{{elixir,start,[normal,[]]},{'EXIT',{{badmatch,{error,enotsup}},[{elixir,start,2,[{file,"src/elixir.erl"},{line,34}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,272}]}]}}}}}}},[{elixir,start_cli,0,[{file,"src/elixir.erl"},{line,75}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

The same thing happens when I try to run `iex`. 

Here is the `erl_crash.dump`:
https://gist.github.com/TiuTalk/35cd2f8c25ee9e1ba138

Is there any other information I can provide to help identifying this "bug"?

Should I try to compile it?

**Comment by edgurgel** [comment]
This is probably related to the newest Erlang version: https://github.com/elixir-lang/elixir/issues/3244

**Comment by TiuTalk** [comment]
Probabaly! I will try downgrading to see if it works.

**Comment by TiuTalk** [comment]
Indeed, this is a duplicate of #3244... thanks for your help, @edgurgel

**Comment by soulfly** [comment]
Had the same issue,
had an old version of Erlang installed

just upgraded to latest 18.3 https://www.erlang-solutions.com/resources/download.html
works now!
