### ISSUE TITLE
Do not allow tuple.foo calls anymore

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3254]
It is about time to break away from this weird Erlang behaviour. Something to be discussed for 2.0.

**Comment by jcspencer** [comment]
Are there any currently proposed ideas of a replacement syntax for this behaviour? If not, what do you aim to achieve from breaking away from this behaviour in 2.0?

**Comment by josevalim** [comment]
@jcspencer if you do `{1, :foo}.bar`, the stacktrace is very hard to understand and it has caused confusion, and we are not gaining any features from allowing such tuple calls.

**Comment by renatomoya** [comment]
Here's an example of the stacktrace:

```bash
iex(1)> {1, :foo}.bar
** (ArgumentError) argument error
    :erlang.apply(1, :bar, [])
```

**Comment by gjaldon** [comment]
It's even more confusing with the following examples:

```elixir
iex(2)> {String, :upcase}.test
** (UndefinedFunctionError) undefined function: String.test/1
    (elixir) String.test({String, :upcase})

iex(3)> {String, "test"}.upcase         
** (FunctionClauseError) no function clause matching in String.Unicode.do_upcase/1
    (elixir) unicode/unicode.ex:65: String.Unicode.do_upcase({String, "test"})
    (elixir) unicode/unicode.ex:62: String.Unicode.upcase/1
```

It looks like it uses the first elem as the module for the function and then treats the whole tuple as the argument passed to the function call. So `{String, "test"}.upcase` ends up being `String.upcase({String, "test"})`. I really don't see how we could use this and looks like not allowing this is the way to go.

**Comment by renatomoya** [comment]
@josevalim Is it too soon to discuss a proposal for this? Can we label this or make it part of a 2.0 milestone?

**Comment by josevalim** [comment]
We can only allow this if we first add support for such to Erlang. So it is a very long term effort.

**Comment by lexmag** [comment]
Just for a reference:
- https://erlangcentral.org/wiki/index.php?title=Parameterized_Modules
- http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.58.79&rep=rep1&type=pdf 

and real use case https://github.com/mochi/mochiweb/blob/master/src/mochiweb_request.erl (\cc @gjaldon)

**Comment by ThomasArts** [comment]
In Quviq we use parameterized modules all the time and depend on the fact that a module with its arguments can be represented as a tuple. 

That said, we don't use the syntax of that anywhere on the programming level, but we generate these tuples when calling `MyModule:new(:bla)`. The tuple is then passed and used make calls.

It's relatively ugly, not something to advocate, but very useful. Example is our clustering module. This module takes a list of QuickCheck state machine modules and generates a new module from it, which is basically the cartisian product of the state machines.

If we had had Elixir at the time, we probably would have done it as a source-to-source transformation. But we did have the possibility to add a parse transformation for such source-to-source transformation and decided not to. It's simply too difficult and one cannot add a component to the cluster at runtime.

If you like to think of a better solution: write 3 generic servers A, B, and C with their own state and own messages, some duplicated, some handle calls and handle infos etc. Then think of a way to create a module A+B and A+C and A+B+C automatically that is just the cartesian product of these gen servers. That is, runs in one process!

**Comment by josevalim** [comment]
We are delegating this decision to Erlang, as this is implemented at the VM level.
