### ISSUE TITLE
build failing 

### ISSUE THREAD

**Issue by sononix** [elixir-lang/elixir#3255]
just tried installing elixir 
sudo make clean test

getting this error 
cd lib/elixir && ../../rebar clean
env: escript: No such file or directory
make: *** [clean] Error 127

erl -v
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V6.4  (abort with ^G)
1>

**Comment by ericmj** [comment]
Looks like you don't have escript on your machine so probably something wrong with your erlang installation. What does `which escript` say?

**Comment by josevalim** [comment]
Can you also try without sudo?

**Comment by sononix** [comment]
when i run - which escript i dont see anything but running escript comes back with 

escript
escript: Missing filename

**Comment by josevalim** [comment]
I think the issue is `sudo`. Does `sudo erl -v` work?

**Comment by sononix** [comment]
erl -v
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V6.4  (abort with ^G)
1> 

but when i run 

sudo erl -v
sudo: erl: command not found

**Comment by josevalim** [comment]
That's it. Don't run `make clean test` with sudo because sudo changes your paths and it can no longer find erlang.

**Comment by sononix** [comment]
any particular reason for that - it just seems like a strange behaviour

**Comment by josevalim** [comment]
thats how unix works as sudo changes the user. not related to elixir or erlang

**Comment by sononix** [comment]
thanks guys - I think something is after going wrong on my system - Im having other issues with sudo which i hadnt before

**Comment by MaxBarraclough** [comment]
I had this issue in a VM running Amazon Linux, despite that I wasn't running `make clean test` as superuser.

I found that the superuser $PATH value was much shorter than my ordinary user's $PATH. My hacky solution was to hit `sudo bash` (nasty) and `export PATH=....` to match my ordinary user's $PATH, and then run `make install` from within that superuser bash session. Seems to have installed fine.
