### ISSUE TITLE
Persistent iex history

### ISSUE THREAD

**Issue by TheFirstAvenger** [elixir-lang/elixir#3259]
Currently, when using IEX for testing, if you exit out of IEX to rerun iex with new code, the up-history is cleared out. This results in a large amount of scrolling up in your terminal and copy/pasting commands over again. If the IEX history was somehow made persistent across sessions, it would be a very welcome improvement in developing using Elixir.

**Comment by aandrieiev** [comment]
+1. Since IEx.pry plays so a major role in debugging, history preservation is a must.

**Comment by lexmag** [comment]
There are a couple of the same issues:
https://github.com/elixir-lang/elixir/issues/1516
https://github.com/elixir-lang/elixir/issues/2945

**Comment by ericmj** [comment]
It needs to be supported in OTP. You can use https://github.com/ferd/erlang-history instead.

**Comment by gutschilla** [comment]
Hint: As this question seems to be asked over and over again, one might put a small note in the elixir docs on that ("install erlang-history and you're done").

**Comment by eksperimental** [comment]
@gutschilla  :+1:

**Comment by eksperimental** [comment]
@gutschilla  actually, if there are more recurring questions, it may not be a bad idea to  create a FAQ page on the website

**Comment by josevalim** [comment]
We do have a FAQ in the wiki on Github. This would be a very nice addition.

**Comment by gutschilla** [comment]
@josevalim Good point! Just did it.
