### ISSUE TITLE
documentation: communicating with an iex node behind a firewall

### ISSUE THREAD

**Issue by pkoppstein** [elixir-lang/elixir#3269]
I'm having trouble setting up a two-computer environment for Elixir because one of the computers is behind a firewall.  I've spent some time looking for documentation and hints about doing this, and have made some progress, but the documentation that I've been able to find seems to be inadequate.  In any case, I'd certainly appreciate some help!

Please note that I'm familiar with the general procedure for getting two iex nodes to communicate with each other, ~/.erlang.cookie, as well as the details about port 4369 and the trick involving:
```
   --erl "-kernel inet_dist_listen_min 9001 inet_dist_listen_max 9001"
```

The situation is actually very typical:

* the computer inside the firewall (let's call it inside.edu) can ssh to the computer outside
the firewall (let's call it outside.org), and vice versa;
* the router for outside.org also forwards the two above-mentioned ports (4369 and 9001) to outside.org;
* the guardians of inside.edu have inflexible policies regarding port forwarding.

As I understand it, the challenge here is to configure things so that messages from outside.org
can reach inside.edu.  

Is there a way to do this using ssh tunneling?  Is the iex option "-rsh ssh" relevant?

Thanks.

**Comment by eksperimental** [comment]
post this in the mailing list, this is not the place for such questions.
anyway, you will have more exposure there.

**Comment by pkoppstein** [comment]
@eksperimental - Isn't this a documentation issue?  Elixir is supposed to be useful for distributed computing, isn't it?

**Comment by eksperimental** [comment]
sounds more like a feature request for documentation, than pointing something that is documented wrong.
it will help if you post a link to the documentation you are talking about.

**Comment by pkoppstein** [comment]
@eksperimental suggested:
> it will help if you post a link to the documentation you are talking about.

The following page is titled "Distributed tasks and configuration" but it mainly covers the case of 
"two nodes in the same machine". It does touch on machines in the same network, which is nice, but still rather restricted:

http://elixir-lang.org/getting-started/mix-otp/distributed-tasks-and-configuration.html 

The above-mentioned page does provide a pointer to Erlang documentation at http://learnyousomeerlang.com/distribunomicon
but first, that is Erlang, not Elixir, and second, in the relevant section ("The Walls are Made of Fire and the Goggles do Nothing"), it assumes that ports can be opened up freely.

There is a reference to the possibility of "tunneling over secure channels".  That holds out the promise that tunneling with ssh as I've been trying to do might be possible, which is why I started this thread.

By the way, what is the preferred place for making an "Enhancement Request"?

**Comment by eksperimental** [comment]
feature requests should be sent to the elixir-core mailing list http://groups.google.com/group/elixir-lang-core

**Comment by josevalim** [comment]
This is a bit of a grey area. If you want to do very custom deployments, you need to read Erlang docs and options. I don't think it makes sense to duplicate those docs in Elixir land. ANyway, the discussion will continue in the mailing list!
