### ISSUE TITLE
Incompatibility between @doc and import

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3272]
Today, even if we `@doc false` some function, it will still be imported if someone imports the module. I am listing this as a potential bug, although I am not sure if it qualifies as one or if there are any solutions.

**Comment by whatyouhide** [comment]
This is one tricky case :). In Elixir it looks like `@doc false` is **the** "standard" way to use a function from another module within the same library, without exporting it outside the library. Maybe the solution could be something like a `@hidden` attribute:

```elixir
@hidden
def my_fun do
  # ...
end
```

The `@hidden` (or whatever name) attribute would

* hide the function from the documentation
* prevent the function from being imported with `import`
* [insert whatever other thing is useful when dealing with this pattern]

**Comment by tony612** [comment]
@whatyouhide It seems like `defp`

**Comment by whatyouhide** [comment]
@tony612 with the **major** difference that you can actually *call* that function from outside the module (provided you know the name and arity of the function).

**Comment by liveforeverx** [comment]
"The @hidden (or whatever name) attribute would"

It make sense, only if there will exists something like import_all, that really import all 'def'-defined functions, without  exceptions.

**Comment by whatyouhide** [comment]
@liveforeverx instead of introducing `import_all`, you could easily solve this like in the following example:

```elixir
defmodule MyMod do
  @hidden true
  def my_fun() do
    # ...
  end
end
```

```elixir
import MyMod, hidden: true
```

**Comment by josevalim** [comment]
This discussion pointed out that the current approach is fine. There are multiple ways of avoiding this (moving to another module, using underscore, etc). It seems better than somehow coupling to unrelated things. Thanks everyone!
