### ISSUE TITLE
undefined function: Agent.stop/2

### ISSUE THREAD

**Issue by stevegraham** [elixir-lang/elixir#3274]
When starting a new Phoenix project. Running any mix task that performs compilation aborts with the following error.

```
lib/agent.ex:1: warning: redefining module Agent
** (UndefinedFunctionError) undefined function: Agent.stop/2
    (elixir) Agent.stop(#PID<0.118.0>, :infinity)
    (mix) lib/mix/compilers/elixir.ex:111: Mix.Compilers.Elixir.compile_manifest/5
    (mix) lib/mix/compilers/elixir.ex:50: Mix.Compilers.Elixir.compile/7
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    (mix) lib/mix/tasks/compile.all.ex:15: Mix.Tasks.Compile.All.run/1
    (mix) lib/mix/tasks/compile.ex:64: Mix.Tasks.Compile.run/1
```

I have replicated this with Elixir master branch.

Info:

```
Elixir versions: 1.0.4 and HEAD
Phoenix version: 0.11.0
Erlang version: 17.5
Phoenix application created with phoenix.new mix archive
```

cc @chrismccord

**Comment by josevalim** [comment]
Are you or any project accidentally defining a module named Agent? What does `:code.which Agent` returns to you?

**Comment by josevalim** [comment]
Oops, that's very visible in your output:

> lib/agent.ex:1: warning: redefining module Agent
> ** (UndefinedFunctionError) undefined function: Agent.stop/2

Yes, don't redefine an existing module, otherwise the system will behave in unexpected ways. :)

**Comment by stevegraham** [comment]
This is a fresh project. There is literally no code in it. How is it possible I have opened the Agent module?

**Comment by josevalim** [comment]
If you created a project as `mix new agent` or `mix phoenix.new agent`, then it defined a module named Agent. I have already opened an issue to be sure we check the module does not exists before generating.

**Comment by stevegraham** [comment]
That is it. The project is called `agent`. Now I feel stupid! :laughing: Thanks for helping me out so late at night!
