### ISSUE TITLE
Check on mix new if the given application module exists and raises if so

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3275]

**Comment by lpil** [comment]
Hello! I'd like to take a stab at this (what with the `Level:Starter` label there and all. :smile: 

To clarify, is this the sort of behaviour that is desired?

```bash
$ mix new string
** (Mix) The module name String is already in use
```

Cheers,
Louis

**Comment by josevalim** [comment]
yes, precisely!
