### ISSUE TITLE
False unused import warning when using Code.eval_quoted/3

### ISSUE THREAD

**Issue by zambal** [elixir-lang/elixir#3277]
When using Code.eval_quoted/3 inside a macro, the compiler complains about an unused import although functions from the imported module are used.

See this gist for a minimal example that illustrates the issue:

https://gist.github.com/zambal/52ab241a8c84a80e9e13

**Comment by josevalim** [comment]
Import is lexical and eval is not lexical so, for all purposes, you didn't
use the import.

You can pass warn: false forces like this.


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by zambal** [comment]
Ah, I didn't realize that. Thanks for the quick update. Before closing this issue: is it possible to suppress the warning any other way? I stumbled upon this while using a library that I wrote and I think it would be slightly inconvenient for other users of the library to always write `warn: false` when importing a module.

**Comment by josevalim** [comment]
Not in the current way the library is structured. Maybe it would be fine if
somehow you used module attributed? Also, you need to Macro.escape the eval
result otherwise it expects AST and it will choke on things like maps.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by zambal** [comment]
Whoops, I made the example too simple :) In the actual library code, it works a bit different and evaled code gets properly escaped before inserted.

I don't understand how module attributes could help in this case?

**Comment by josevalim** [comment]
After thinking more about it, I don't think module attributes can help it either. I mean, you could use module attributes, but then you don't need the precompile macro. :(

**Comment by zambal** [comment]
That wouldn't really be an option, since I use the precompile macro for precompiling/rendering markup in my [Eml](https://github.com/zambal/eml) library. Anyway, thanks for thinking with me <3

**Comment by josevalim** [comment]
I have no idea how Eml works but, if the structures are macros, you can achieve much of the precompiled by using Macro.expand and doing the work solely at compile time without evaling. That's what we do in Ecto and I would love to provide more pointers if you are interested. Closing this for now though!
