### ISSUE TITLE
Introduce \u for codepoints in Strings

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3284]
We should remove `\x` in the long term because in most languages it represents a byte and making it a codepoint is source of confusion. The warning should only be applied for codepoints greater than 127 which will eventually become an error.

We also can remove ?\xFF because that is the same as 0xFF.

**Comment by fishcakez** [comment]
At somepoint before or at the same time `\x` is removed it would be nice to warn about invalid escapes.
