### ISSUE TITLE
Live reload iex

### ISSUE THREAD

**Issue by jonhkr** [elixir-lang/elixir#3287]
Hello everyone,
I'm just wondering if is there a way to live reload `iex` on file change?

Sometimes I have to debug a module and for every change I have to quit `iex`, open it again and type or copy/paste the commands.

Thank you.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
