### ISSUE TITLE
Struct default values random behaviour when using env var

### ISSUE THREAD

**Issue by jonhkr** [elixir-lang/elixir#3289]
I have the following scenario where a struct is defined with default values that come from `Application.get_env` function:

```Elixir
defmodule M do
  defstruct a: Application.get_env(:app, :a), b: Application.get_env(:app, :b)
end
```
These env values come from the `config.exs` as follows:

```Elixir
config :app,
  a: "value for a",
  b: "value for b"
```
Sometimes when the application starts, the struct receives the values from the config, sometimes it just receives `nil`, actually, most of the time it receives `nil`.

I think that this happens because the configuration is being evaluated after the struct definition, then when it tries to get the values they weren't defined yet.

**Comment by josevalim** [comment]
This behavior is going to read the application configuration at compile
time. Is this what you really want?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer

**Comment by jonhkr** [comment]
I don't know if I'm right, please correct me if not, I believe the struct default values are evaluated only once, when the struct is evaluated. In this case I think that the application configuration should be available so that the struct can receive its default values.

One use case for this is when I need to authenticate to an third party web service and want to have my authentication info in a struct without having to set it everytime. For instance, I can build the request like:
```Elixir
request = %Request{
  auth: %Auth{},
  foo: "bar"
}
```

Where `Auth` is defined like so:
```Elixir
defstruct key: Application.get_env(:app, :key), secret: Application.get_env(:app, :secret)
```

**Comment by ericmj** [comment]
Struct default values are evaluated only once - at compile time. If you have the key and secret when compiling you should be fine, if not you need to fetch it every time you create a struct.

**Comment by josevalim** [comment]
I could not reproduce this. The values are always there if they have been set at compilation time.

**Comment by jonhkr** [comment]
I'm sorry, I've not shown you the full scenario.

This behaviour happen when I have this struct in a project and I try to configure it from another project.

Say I have the project `A` that contains this struct that gets its default values from the application configuration. Then I create project `B` that depends on project `A` to work. Project `B` sets those environment variables which are not being read because project `A` is compiled before project `B`.

I think there should be a warning in the docs to tell people about this. It is documented here though, in case someone else runs in the same problem.

**Comment by josevalim** [comment]
Your approach is fine but you need to configure it *before* you add A as a dependency. If it is done afterwards, you should do `mix deps.clean a` so it gets compiled again. You should definitely add this information to your project readme because, I agree, it is not super obvious. :)
