### ISSUE TITLE
TokenMissingError: missing terminator: end (for "do" starting at line 1)

### ISSUE THREAD

**Issue by handnot2** [elixir-lang/elixir#3293]
erlang/17.5, elixir/1.0.4

defmodule X do
  def f(), do; nil
end

The compilation error is correct. But it would be very helpful to get a bit more help from the compiler pointing that a semicolon after "do" is the culprit. It is not easy to visually identify this especially when the file is bigger than a few lines!

**Comment by josevalim** [comment]
This could be improved by making the tokenizer not check for termination do tokens that immediately follow a comma.
