### ISSUE TITLE
Mix archive.install fails on my machine

### ISSUE THREAD

**Issue by tallakt** [elixir-lang/elixir#3295]
When installing the phoenix archive with mix, the `mix archive.install http://github.com/phoenixframework/phoenix/releases/download/v0.11.0/phoenix_new-0.11.0.ez` ended with an error message.

Fetching the file with wget and installing locally was ok.

 ```
$ ./bin/mix archive.install http://github.com/phoenixframework/phoenix/releases/download/v0.11.0/phoenix_new-0.11.0.ez
Are you sure you want to install archive http://github.com/phoenixframework/phoenix/releases/download/v0.11.0/phoenix_new-0.11.0.ez? [Yn] 
** (Mix) Could not access url http://github.com/phoenixframework/phoenix/releases/download/v0.11.0/phoenix_new-0.11.0.ez, error: {:failed_connect, [{:to_address, {'github.com', 443}}, {:inet, [:inet], {:eoptions, {{{:badmatch, ""}, [{:ssl_handshake, :dec_hello_extensions, 2, [file: 'ssl_handshake.erl', line: 1737]}, {:ssl_handshake, :decode_handshake, 3, [file: 'ssl_handshake.erl', line: 926]}, {:tls_handshake, :get_tls_handshake_aux, 3, [file: 'tls_handshake.erl', line: 155]}, {:tls_connection, :next_state, 4, [file: 'tls_connection.erl', line: 433]}, {:gen_fsm, :handle_msg, 7, [file: 'gen_fsm.erl', line: 503]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 237]}]}, {:gen_fsm, :sync_send_all_state_event, [#PID<0.85.0>, {:start, :infinity}, :infinity]}}}}]}
```

I am on a compiled master which is `4b728cfd9ab1a7a774dd0c5f1e0a7ce7a3e49b67`

**Comment by josevalim** [comment]
Which erlang version?

**Comment by josevalim** [comment]
Also, please try passing the --system option. :)

**Comment by tallakt** [comment]
Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

The --system option did not yield any different results. I am not sure if it is having an effect though (it is not described in the docs).

**Comment by josevalim** [comment]
It looks like you are using erlang 17.3 (erts-6.2) which has known problems with ssl. Maybe try updating erlang. We also have improvements for future elixir versions which hopefully will make this much easier.
