### ISSUE TITLE
Specs aren't generated for functions with default arguments

### ISSUE THREAD

**Issue by hamiltop** [elixir-lang/elixir#3304]
Best explained with an example:

```elixir
@spec encode!(Encoder.t, Keyword.t) :: iodata | no_return
def encode!(value, options \\ []) do
```

Running dialyzer:
```
:0: Unknown function 'Elixir.Poison':'encode!'/1
```

My understanding is that under the hood

```elixir
def encode!(value, options \\ []) do
```

becomes

```elixir
def encode!(value), do: encode(value, [])
def encode!(value, options \\ []) do
```

Is there a way to do something similar with the spec as well?

**Comment by josevalim** [comment]
So, I think dialyzer is smart enough to figure it out on its own, that's why I never bothered with automatically defining one behind the scenes. If that is not the case, it is not hard to do it automatically.

**Comment by fishcakez** [comment]
Dialyzer will definitely infer the specs correctly. The warning is because `poison` is not in the PLT. If `poison` was in the PLT the warning would be different.

**Comment by fishcakez** [comment]
Just to clarify, if `poison` was in the PLT there would not be a warning because dialyzer would know about the function. If dialyzer knows about a module but the function is not exported from it a callgraph warning is generated.

**Comment by hamiltop** [comment]
Cool. I'll investigate that. Closing.

**Comment by hamiltop** [comment]
Investigation results (for posterity): Simple, just needed to include `:poison` as an application in my mix.exs.
