### ISSUE TITLE
Missing Debian Jessie packages

### ISSUE THREAD

**Issue by cars10w** [elixir-lang/elixir#3305]
The debian repository under https://packages.erlang-solutions.com contains Erlang and Elixir debian-packages. For Debian Jessie (v8, although it is not GA yet) there are already packages available for Erlang and its tools.

For Elixir, only packages up to Debian Wheezy (v7) are available. It would be nice to also provide Elixir debian-packages for Jessie.

**Comment by josevalim** [comment]
We are not responsible for those packages but I am copying those who are: @dexsda Thank you.

**Comment by cars10w** [comment]
Thanks!

**Comment by cars10w** [comment]
Just as a note, the latest Elixir is avalable for Jessie now in the repo mentioned above.. Thanks to everyone!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
