### ISSUE TITLE
Catch-all pattern-match without '^' should show compiler warning or compiler error

### ISSUE THREAD

**Issue by bryanhunter** [elixir-lang/elixir#3307]
A frequent goof that folks coming to Elixir from Erlang make (and will continue to make) is forgetting the `^` on pattern matches. The current behavior in Elixir can turn this simple mistake into a pretty nasty problem. For example...
 
```
defmodule KnockKnock do 
  def who_is_there do
    friend = "Ron Weasley"
    enemy = "Voldemort"
    knocking_at_our_door = "Voldemort"

    our_response = case knocking_at_our_door do
      friend -> "Come on inside, #{friend}."
      enemy -> "Expelliarmus!"
    end

    {friend,enemy,knocking_at_our_door,our_response}
  end
end
```
Compile and run...
```
ex(1)> c "knock_knock.ex"
knock_knock.ex:9: warning: variable enemy is unused
[KnockKnock]
iex(2)> KnockKnock.who_is_there
{"Ron Weasley", "Voldemort", "Voldemort", "Come on inside, Voldemort."}
iex(3)>
```
That's a pretty nasty surprise! Without the `^`, the short-lived `friend` identifier in the `case` will match against *anything* that is passed to it, and there is no warning. A catch-all in the first clause of a case statement is never what you want. I chatted with @josevalim and he confirmed that this is a bug and not 'by design'.

One way to make this safer would be to issue a warning
`Warning: this clause cannot match because a previous clause at line 9 always matches`

Fraud and backdoors are the only scenarios I can think of where doing this intentionally would make sense, so maybe a compiler *error* would be better.

**Comment by bryanhunter** [comment]
This post adds a bit more background info... 
http://codeswamp.com/2015/02/14/elxir-immutability/

In Erlang here's how things would play out:
```
	case KnockingAtOurDoor of
		Friend -> ...  % Good, works just like ^friend would in Elixir;
		Enemy -> "Expelliarmus!"
	end,
```

In Erlang you can't exactly reproduce the reported bug, but this is pretty close. 
```
	Knocking = "Voldemort",
	Friend = "Ron Weasley",
	Enemy = "Voldemort",
	
	case Knocking of
		Buddy -> io:format("Welcome ~s~n", [Buddy]);
		Enemy -> io:format("Experiarmus")
	end.
```
Only warning is that `Friend` is unused. Turns out Erlang doesn't warn/error about the first clause always matching either... unless `Knocking` is passed as a function argument like so...
```
knock_knock_3(Knocking) ->
	Friend = "Ron Weasley",
	Enemy = "Voldemort",
	
	case Knocking of
		_BrandNew -> io:format("Welcome");
		Enemy -> io:format("Experiarmus")
	end.
```
...which when compiled produces: 
` Warning: this clause cannot match because a previous clause at line 34 always matches`

Possibly related...
* http://erlang.org/pipermail/erlang-bugs/2013-June/003629.html  
* https://github.com/elixir-lang/elixir/issues/1215

The trap is there in Erlang too, but the absence of rebinding and `^` make it less likely people will walk into it. How can the trap be removed for Elixir? How can it be removed for both?

**Comment by josevalim** [comment]
@bryanhunter this is indeed a bug in Erlang. The good news is that it only manifests when the variable you are matching on is literal. If we replace the `knocking_at_our_door` variable by an expression, it could even be `"Voldemort" <> enemy`, all important warnings will be triggered. In other words, I think we will actually have a warning on all relevant contexts, I expect the code above to be actually rare in practice.

**Comment by josevalim** [comment]
After spending a couple hours on this, this is very hard to fix in Erlang because, at the point those warnings are emitted, the compiler has already optimized the code out, because it knows it is a literal. Therefore, I am closing this but I don't think it is an issue as it only happens when the case expression comes from a directly literal.
