### ISSUE TITLE
add support for math in bitstring specifiers

### ISSUE THREAD

**Issue by sunaku** [elixir-lang/elixir#3310]
Hello,

Under Elixir 1.0.4, I'm unable to do math in bitstring specifiers:

    def parse(param_count, <<params :: binary-size(11 * param_count)>>) do
      # ...
    end

I get the following error when compiling the function shown above:

    ** (CompileError) myfile.ex:95: size in bitstring expects an
    integer or a variable as argument, got: :erlang.*(11, param_count)

If bitstring specifiers can accept a variable as argument, why can't
they accept simple math performed on variables, or pure math itself?

    << some_field :: binary-size(11 * some_count) >> = some_payload
    << some_field :: binary-size(11 * 5 - 30 + 1) >> = some_payload

In my mind, both of the above examples should work.  See also #2791.

Thanks for your consideration.

**Comment by ericmj** [comment]
We are limited by erlang here so the change would have to be made there.

**Comment by josevalim** [comment]
yes, regardless of the merit of those changes, it requires first moving erlang, so it is definitely a "won't fix".

**Comment by sunaku** [comment]
Thanks. Is there a procedure I could follow to get this fixed upstream, in Erlang itself?

**Comment by josevalim** [comment]
The best option is to send a pull request. You can also create an EEP
(Erlang Enhancement Proposal).



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*
