### ISSUE TITLE
`mix <task> --no-deps-check` checks deps in "compile" task

### ISSUE THREAD

**Issue by hayesgm** [elixir-lang/elixir#3315]
When running `mix phoenix.server`, Elixir is running:

```elixir
if proj, do: Mix.Task.run("compile")
```

to compile the task if it did not find the module for the given task. There appears to be no way to tell phoenix to compile this task without checking dependencies, short of running:

```bash
mix do compile --no-deps-check, phoenix.server --no-deps-check
```

The issue relates to #1430 where `.git` directories are sometimes removed from PaaS, but more generally being able to run a task without a dependency check.  The preferred behavior would be to pass `--no-deps-check` to the `compile` task if present in args for the mix task to run.

**Comment by josevalim** [comment]
I don't think we can fix this besides what you have given. If the task does not exist, it makes sense for us to compile. If you want to make sure it won't happen, then you do need to compile it before hand.

We can't pass options to the underlying compile hook for the regular case, unless we do via environment variables, which is as "special" as using `do` as you did.

**Comment by hayesgm** [comment]
Makes total sense. Good to know this is expected behavior / has a workaround.
