### ISSUE TITLE
Checking of hex happen before reading mix enviroment

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/elixir#3322]
Example would be decimal:

```elixir
MIX_ENV=prod iex -S mix
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

==> decimal
Could not find hex, which is needed to build dependency :ex_doc
Shall I install hex? [Yn]
```

And, the definition is: 

```elixir
{:ex_doc, only: :dev}
```

It tries to install hex, on the case, it doesn't need to install(based on enviroment).

**Comment by ericmj** [comment]
We also you require you to have hex installed if you have overrides over hex dependencies with git. This is tricky to implement, why do you need it?

**Comment by josevalim** [comment]
Right but in this case we could completely skip it though because the environment does not match.

**Comment by liveforeverx** [comment]
We have release server, where our script analyse mix.lock and downloads all dependencies to "deps".

After that, we use it as: https://gist.github.com/liveforeverx/9bdde7ac7bba871130c1 simply a path.

For a production enviroment, to use path dependencies, that `mix` build process doesn't require network access. Hex(as other tars) packages will be cached(once it built, that why it need to be downloaded from build system) on our build enviroment, due to it, there is no need to have access network for rebuilding it.

A question, if we simple require hex as dependency(and preinstall in a deps/ ?), to avoid a problem, does will hex try to access network(or will be something failed or changed in a build process, if network will be unreachable?).

**Comment by ericmj** [comment]
@josevalim There will also be a bunch of overridden hex dependencies as children that we need to know to skip because they are overridden. So we also need to check for overridden before loading the dependency.

@liveforeverx You can't use hex as a dependency, but why not just install it when you install elixir?

**Comment by josevalim** [comment]
Yeah, so we can't fix it per @ericmj comments.

**Comment by liveforeverx** [comment]
" So we also need to check for overridden before loading the dependency." - not really, it happens, only for dependencies, where enviroments are mismatched. It tries to use hex for a hex dependency, which defined as `only: :dev` on `MIX_ENV=prod` . Or do I understand it wrong?

**Comment by ericmj** [comment]
The dependencies you define with `:path` will still have hex children that mix will load. They will be skipped later because they are overridden in your mix.exs file but we already needed hex before that.

**Comment by liveforeverx** [comment]
Do it right, that they are loaded, ignoring environment? Seems, not really. If you define it like

```
deps(Mix.env)

def deps(:dev) do ...
```

Its will work.

Is there a reason, why `only: :dev` behaves different? (If there is no reason, than fixing seems trivial)

**Comment by ericmj** [comment]
We load all the dependencies in your mix.exs file. But those dependencies have children that mix will also try to load, those children are defined as hex dependencies.

**Comment by liveforeverx** [comment]
Ok, I'll see, how it works. It is more complex, as I thought. Thanks for clarification!

One last question. Should it stay, as it is, or should it be changed to work better with overwritten dependencies in the future? (I can tackle it somewhere next time).
