### ISSUE TITLE
(Hard to understand) parse error when using sigils

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#3324]
This is the minimal example which reproduces this:

```elixir
[
  ~s(foo #{1})
  ~s(bar #{2})
]
```

This is of course a syntax error because the first element in the list is missing a trailing comma, but the error comes from the parser code and doesn't seem to be "handled":

```elixir
** (MatchError) no match of right hand side value: {:ok, {:sigil, 3, 115, ["bar ", {3, [{:number, 3, 2}]}], []}}
    (elixir) src/elixir_errors.erl:61: :elixir_errors.parse_error/4
```

**Comment by oneeman** [comment]
Thanks, I'll take care of this one.  It's code from a previous PR of mine.  I have a trivial fix for this case:

```
iex(1)> ~s(foo) ~s(bar #{x})
** (SyntaxError) iex:1: syntax error before: sigil ~s with content 'bar '
 ```

But I'll try to take care of the different error for this case while I'm at it:
```
iex(1)> ~s(foo) ~s(#{x} bar)
** (ArgumentError) argument error
             :erlang.byte_size({{1, 12, 16}, [{:identifier, {1, 14, 15}, :x}]})
    (elixir) src/elixir_errors.erl:61: :elixir_errors.parse_error/4
```

**Comment by whatyouhide** [comment]
@oneeman great, thanks!
