### ISSUE TITLE
Allow named setups

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3332]
And discuss allowing the return of setups to be simply maps.

**Comment by gjaldon** [comment]
What are named setups and what are they for? 

I'm :+1: for setups to allow return of just maps instead of `{:ok, map}`. I found that off the first time I used it. Just the map is more intuitive to me.

**Comment by josevalim** [comment]
I am closing this until we have enough information to bring this back, because I completely forgot. Sorry.
