### ISSUE TITLE
IEx tab-completion doesn't work properly with module aliases

### ISSUE THREAD

**Issue by houshuang** [elixir-lang/elixir#3334]
If I do

```elixir
alias Phoenix.HTML
```

in IEx, I expect to be able to type `HTML.<tab>`, and see a list of functions and modules under Phoenix.HTML. Instead, I see nothing.

If I do

```elixir
alias Phoenix.HTML.Form
```

On typing `Form.<tab>`, I instead see completions for Phoenix.HTML. I can select Endpoint, and click <tab> again, and IEx will happy tab-complete for me, but of course upon selecting a function, such as Form.Endpoint.start_link, that function does not exist.

**Comment by josevalim** [comment]
It is fixed in master and coming in Elixir v1.1!



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer
