### ISSUE TITLE
IO.binread/2 does not properly read binary data

### ISSUE THREAD

**Issue by zykos** [elixir-lang/elixir#3339]
From the docs, IO.binread/2 is supposed to be read the entire content of a file when passed the :all option. However, in the current implementation, it reads a file line by line.

```elixir
  def binread(device, :all) do
    do_binread_all(map_dev(device), "")
  end

  defp do_binread_all(mapped_dev, acc) do
    case :file.read_line(mapped_dev) do
      {:ok, data} -> do_binread_all(mapped_dev, acc <> data)
      :eof -> acc
      other -> other
    end
  end
```

This has the unfortunate consequence of swallowing any CR codes preceding a LF. Is this intentional? If so, it should not be presented as a way to load binary data from a file.

**Comment by josevalim** [comment]
Definitely a bug. Thank you.

**Comment by josevalim** [comment]
So, `:file.read_line/2` includes new lines here:

```iex
iex(2)> {:ok, pid} = :file.open "README.md", []
{:ok, #PID<0.61.0>}
iex(3)> :file.read_line(pid)
{:ok, '# Update\n'}
```

Thoughts?

**Comment by zykos** [comment]
My guess is that :file.read_line/1 is meant for text files and has logic that converts different newline representations to the target system. The problem happens when reading binary files, where the sequence of bytes 0x0d0a may appear and does not have the semantic meaning of "CR+LF". When :file.read_line encounters that sequence, it assumes it does, then converts that to the newline representation of the target system, which is just "LF" on OSX, where I encountered this bug. So this effectively swallows any 0x0d byte on mac or linux every time it is followed by a 0x0a, and on windows, I assume it would create 0x0d bytes before every 0x0a byte.

If IO.binread/2 is supposed to be for reading binary data, not text data, it should not use :file.read_line/1 at all. Instead, a buffered read is better, using :file.read/2 and maybe reading one block at a time. Erlang unfortunately has only the native :file.read_file/1, which operates on a filename. So if I wanted to operate on a file handle, I'd do something like this:

```elixir
  defp do_binread_all(mapped_dev, acc) do
    case :file.read(mapped_dev, block_size) do
      {:ok, data} -> do_binread_all(mapped_dev, acc <> data)
      :eof -> acc
      other -> other
    end
  end
```

Where block_size is something you get from the system configuration, either a filesystem block or a memory page size. Something like 1024 to 4096 should be reasonable.

**Comment by c-rack** [comment]
@zykos I like your solution. Would you mind to send a PR?
A block size of 4K would be a good choice IMHO.

**Comment by zykos** [comment]
@c-rack sure, I'm just not sure where to defined BLOCK_SIZE, or if that's the proper way to name constants in elixir. I can't find any other instance of a C-like constant definition in the source, any suggestion? Or is just shoving the literal 4096 ok in this case?

**Comment by Kabie** [comment]
@zykos How about make it an option and give it a default value.

**Comment by josevalim** [comment]
We don't need to make it option given you can always just read it yourself.

@zykos you can store it in a module attribute `@read_all_size 4194304`.
