### ISSUE TITLE
Compilation errors with handcrafted bitstring spec

### ISSUE THREAD

**Issue by bjhaid** [elixir-lang/elixir#3340]
Crafting a bitstring by hand in a spec, e.g: 

```elixir
 defmodule Test do                                
   @spec foo(<<_ :: 32, _ :: _ * 8>>) :: list   
   def foo(<<x :: 32, y :: binary>>), do: [x, y]  
 end                                              
```

does not compile, instead fails with:

```
 $ elixirc test.exs 

== Compilation error on file test.exs ==
** (CompileError) test.exs:2: type '*'(_,_) undefined
    (stdlib) lists.erl:1336: :lists.foreach/2
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
```

**Comment by milmazz** [comment]
Hi, I think that the problem occurs when you don't specify the **Size** segment:

```bash
iex(1)> << 1 :: 8 * 4 >> == << 1 :: 32 >>
true
iex(2)> << 1 :: 8 * 4 >> == << 1 :: size(8)-unit(4) >>
true
iex(3)> << 1 :: _ * 4 >> == << 1 :: unit(4) >>
** (CompileError) iex:3: a bit unit size must not be specified unless a size is specified too
```

Without knowing the implementation I suspect that the bug can be in the default value for the **Size**, which depends on the _type_.

Can somebody point me in the right direction to solve this issue?, Right now I'm looking at ``elixir/lib/elixir/src/elixir_bitstring.erl``

**Comment by josevalim** [comment]
@milmazz the bug is not related to the bitstring but to the `@spec` syntax. Your third example wouldn't work because you are using `==` instead of `=` in pattern matching. But it is another problem altogether...

**Comment by josevalim** [comment]
The correct syntax is this: `<<_ :: size * unit>> `. I have updated the docs and increased the coverage. Thank you!
