### ISSUE TITLE
Some code examples in the docs fail are joined onto a single line

### ISSUE THREAD

**Issue by lpil** [elixir-lang/elixir#3341]
See here for an example:

http://elixir-lang.org/docs/v1.0/elixir/Macro#unescape_string/2

The markdown in the `@doc` string looks correct to me.

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/macro.ex#L386-L398

**Comment by ericmj** [comment]
It is fixed in the master docs: http://elixir-lang.org/docs/master/elixir/Macro#unescape_string/2

**Comment by lpil** [comment]
Thanks!
