### ISSUE TITLE
Only remove current hex.ez if download is successful of new one

### ISSUE THREAD

**Issue by jeregrine** [elixir-lang/elixir#3345]
https://github.com/hexpm/hex/issues/97

Currently I have the bug where I cannot download a new hex.ez via mix. Sometimes I hit "Y" when it asks to download, in hopes it might be fixed. But it's not and it deletes my current hex. 

So next time I `mix deps.get` it cannot find hex and I have to go download it manually.

**Comment by doomspork** [comment]
@ericmj do you mind if I take a shot at this?

It seems this could be accomplished by moving the `remove_previous_versions/1` to after the `check_file_exists/2` in `Mix.Tasks.Archive.Install`:

```elixir
    if opts[:force] || should_install?(src, previous) do
      archive = Path.join(Mix.Local.archives_path(), basename(src))
      check_file_exists(src, archive)

      remove_previous_versions(previous)
```

Not entirely sure the best way to test this but I'll dig in and see what I can find.

**Comment by ericmj** [comment]
@doomspork Yes, go ahead!

**Comment by josevalim** [comment]
Reopened.

**Comment by renatomoya** [comment]
@josevalim Reopened because #3411 didn't fix it?

**Comment by doomspork** [comment]
@renatomoya there was an issue with my original patch.  When you install an existing version it would remove it at the end of the run.  I'm working on an fix.
