### ISSUE TITLE
Consider increasing assert_receive default timeout

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3346]
Or at least make it configurable. Sometimes 100ms ends up being triggered in slow environments like CI. Maybe we should increase it to 500ms?

**Comment by tony612** [comment]
I think 500 is reasonable. And I don't like the configuration for the default timeout somehow.

**Comment by josevalim** [comment]
Another option is to use the default of 5000ms. The downside is that if you don't receive a mesage you were expecting... you need to wait 5 seconds to figure it out. /cc @fishcakez @ericmj

**Comment by ericmj** [comment]
Do we have experience of it being triggered in CI? The problem is that refute_receive will make the tests much slower.

**Comment by josevalim** [comment]
We don't need to change refute_receive though. I don't think we need to be consistent in this case. Checking for refute_receive is almost always a bad idea anyway. That's why I am considering making the timeout explicit.

**Comment by ericmj** [comment]
I doubt making it explicit will help, it will always be a reactive change after seeing CI failures. It's extremely hard to anticipate if the timeout will be enough, especially when considering CIs.

If slow CIs is the issue I would rather argue for a global timeout multiple you can set in your CI config.

**Comment by josevalim** [comment]
Hold on, we are discussing two changes here and I think we are mixing them up. Let's go by parts: should we change the assert_receive timeout to which value by default? Ignore the refute_receive discussion for now.

**Comment by ericmj** [comment]
I would argue for not changing because the current 100ms timeout is enough in 99% of cases. The multiple I discussed would be used for both assert and refute.

**Comment by josevalim** [comment]
Here is the thing though: increasing the assert_receive timeout (only) is not going to affect or make any passing suite slower. It will however decrease the chance of failing tests in CI though.

**Comment by ericmj** [comment]
It still makes the developer experience, more so if you have many assert_receives in your test (and even more if we add support for multiple assert failures). I think it's wrong to make dev experience worse because there exists slow CI environments, that's why timeout multiple is the right way to go. And what are we really fixing if refute_receive stays the same?

**Comment by josevalim** [comment]
You are right. Let's make both timeouts configurable and call it a day.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by josevalim** [comment]
Fixed in master.
