### ISSUE TITLE
String.reverse does not work with ligatures

### ISSUE THREAD

**Issue by obrok** [elixir-lang/elixir#3351]
Example:

```elixir
iex(1)> "baﬄe" |> String.reverse
"eﬄab" # one would probably expect "elffab"
```

My initial thoughts on how to fix this is to use the decomposition field (currently ignored) from `UnicodeData.txt` when reversing - does that make sense? If yes, then I could take a crack at this.

**Comment by josevalim** [comment]
@obrok I think the decomposition field will actually make it worse because "é" would be broken into "e" and the acute accent, which would have the wrong order when reversed. No?

**Comment by obrok** [comment]
It seems that decompositions for such characters are marked with the <compact> tag(?), for example http://www.fileformat.info/info/unicode/char/fb03/index.htm or http://www.fileformat.info/info/unicode/char/216b/index.htm. I am not versed well enough in Unicode lore to say for sure this is a rule though.

**Comment by josevalim** [comment]
Right. XII is an example of where decomposition will actually yield worse results too. I don't think the character XII should be reversed to IIX. It should still remain as XII. Afaik, decomposition is used for comparing two strings, there is nothing that says we should use it for reversing.

In fact, I don't recall anything about reversing in Unicode, so there is no way for me to confirm if the behaviour here is right or wrong. :(

**Comment by josevalim** [comment]
This perl module says we should work at the grapheme level: http://www.perlmonks.org/?node_id=661510 which is what we do today.

**Comment by obrok** [comment]
In that case feel free to close the issue - I just thought the behaviour in my example was not what you would expect, but one never knows with Unicode.
