### ISSUE TITLE
Node.connect doesn't work with dashes (hyphens) in hostnames

### ISSUE THREAD

**Issue by tnt** [elixir-lang/elixir#3354]
When I do

```bash
$ iex --sname bla2
iex(bla2@aspire-v3)> Node.connect :"bla@aspire-v3"
false
```
it doesn't work (while an iex-session started with `iex --sname bla` is of course running). When do it with the `--remsh` param (`iex --sname bla --remsh bla@aspire-v3`) it works as expected.

It also works with `iex --name bla@127.0.0.1` and `Node.connect :"bla@127.0.0.1"` in the other shell.

I'm running Erlang 17.5 (erts-6.4)/ Elixir 1.0.4  both compiled from source on a Fedora 21 Linux (all tests succeeded for both) and a `$HOME/.erlang.cookie` file exists. I had tried this before with the Fedora Erlang 17.4 packages with the same results.

On a Centos 7 machine with the same versions it also works without problems using `--sname bla`. &mdash; The hostname on that machine doesn't contain hyphens; so maybe it's just that?

**Comment by josevalim** [comment]
There is something definitely up in your setup because it just works here:

```
$ iex --sname bar
Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(bar@mac-book)1> Node.connect :"foo@mac-book"
true
```

**Comment by tnt** [comment]
It turned out that this is an Erlang issue.

```bash
$ erl -sname bla2
(bla2@aspirev3)1> net_kernel:connect_node('bla@aspirev3').
true
```

After changing the hostname back to `aspire-v3`:

```bash
$ erl -sname bla2
(bla2@aspire-v3)1> net_kernel:connect_node('bla@aspire-v3').
false
```

It also works when starting `erl` with `-remsh bla@aspire-v3`.

**Comment by tnt** [comment]
It finally turned out that the difference between `aspirev3` and `aspire-v3` was, that there existed the following lines in my `dnsmasq`-conf:

    address=/aspire-v3/127.0.0.1
    address=/aspire-v3/::1
 
Still strange that connecting via `-remsh` works while `net_kernel:connect_node` doesn't.
