### ISSUE TITLE
Allow ++ in patterns

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3355]
For example:

     [foo: foo] ++ _ = [foo: 1, bar: 2]

**Comment by gjaldon** [comment]
Hi @josevalim! I'd like to take a shot at this task. 

Tried looking for the code responsible for the match behaviour by tracing it through `elixir:eval/2` but couldn't find it. Which module houses it?

**Comment by liveforeverx** [comment]
@gjaldon : that a place( https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_translator.erl#L216 ), where it happen, as I wanted to take this too. And comment: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_translator.erl#L225-L229 seems, like this task wait until fix merged in erlang? (As I understand it right). Seems, that ticket is for elixir 1.2

**Comment by gjaldon** [comment]
Thanks for the help, @liveforeverx! I thought it would be the `translate/2` that matches on `'='` where I would need to work. 

The comment does seem to point out that a fix is needed in Erlang before this can be worked on. Are we still waiting for a fix in Erlang side or is this ok to work on now, @josevalim?
