### ISSUE TITLE
Consider supporting map shorthand syntax

### ISSUE THREAD

**Issue by devinus** [elixir-lang/elixir#3367]
Taking a [pretty cool page out of ES6](https://github.com/lukehoban/es6features#enhanced-object-literals):

```elixir
# If `method`, `url`, `headers`, and `payload` are already bound
%Request{method, url, headers, payload}

# If e.g. `payload` hasn't been bound yet
%Request{method, url, headers, payload: get_payload()}
```

**Comment by josevalim** [comment]
@devinus let's have those discussion on core first. :)

**Comment by mrkaspa** [comment]
This will be pretty useful

**Comment by whatyouhide** [comment]
@mrkaspa we decided to not support this in Elixir after all, but you can find a separate Hex package that implements this [here](https://github.com/whatyouhide/short_maps).

**Comment by mrkaspa** [comment]
@whatyouhide why don't you include the sigil way in the standard library?

**Comment by josevalim** [comment]
@mrkaspa he linked to the discussion that explains why it is not part of the standard library. :)

**Comment by mrkaspa** [comment]
@josevalim I see thanks
