### ISSUE TITLE
Consider expanding ranges in typespecs to be ORs

### ISSUE THREAD

**Issue by devinus** [elixir-lang/elixir#3368]
E.g.

```elixir
@type t :: %__MODULE__{
  status: 100..599
}

# Becomes:
@type t :: %__MODULE__{
  status: 100 | 101 | 102 | 103 | 104 # ...
}
```

**Comment by josevalim** [comment]
Ranges already have a meaning from Erlang itself. I don't think we should change it. Why would we want to do this? What are the pros/cons?

**Comment by ericmj** [comment]
Ranges in typespecs are supposed to work like this. Have you confirmed that it doesn't have this behaviour?

**Comment by devinus** [comment]
@ericmj Ah, I actually didn't know that. I am stoked now.
