### ISSUE TITLE
referencing namespaced module by name

### ISSUE THREAD

**Issue by sunaku** [elixir-lang/elixir#3371]
Hello,

I'm using Elixir 1.0.4 and I find that namespaced modules cannot be referenced by name unless you alias them.  For instance, in the code example below, `Foo` always references the top-level module named `Foo` , whereas I have to first `alias Foo.Bar`  in order to make `Bar` reference itself as a namespaced module.

Is this a bug? :sweat_smile:  Thanks for your consideration.

```sh
$ cat foobar.exs
defmodule Foo.Bar do
  def whoami, do: Bar
  alias __MODULE__
  def whoami2, do: Bar
end

IO.puts Foo.Bar.whoami
IO.puts Foo.Bar.whoami2

defmodule Foo do
  def whoami, do: Foo
  alias __MODULE__
  def whoami2, do: Foo
end

IO.puts Foo.whoami
IO.puts Foo.whoami2

$ elixir foobar.exs
Elixir.Bar
Elixir.Foo.Bar
Elixir.Foo
Elixir.Foo
```

**Comment by ericmj** [comment]
This is working as intended. The module name is actually the full `Foo.Bar` so you cannot reference it with just `Bar` unless you first set up an alias.

**Comment by sunaku** [comment]
:+1: Cool, thanks for clarifying. :sweat_smile:
