### ISSUE TITLE
Stream.timer/1 waits too long

### ISSUE THREAD

**Issue by Joe-noh** [elixir-lang/elixir#3379]
From [ML](https://groups.google.com/forum/#!topic/elixir-lang-core/lDAOAvzlQYI)

@hamiltop 

`Stream.timer(1000)` waits about 2 seconds instead of 1 second.

**Comment by hamiltop** [comment]
Further tests:

```
time elixir -e "Stream.timer(1000) |> Stream.run" 
elixir -e "Stream.timer(1000) |> Stream.run"  0.15s user 0.06s system 9% cpu 2.189 total

time elixir -e "Stream.timer(2000) |> Stream.run"
elixir -e "Stream.timer(2000) |> Stream.run"  0.16s user 0.06s system 5% cpu 4.190 total

time elixir -e "Stream.timer(3000) |> Stream.run"
elixir -e "Stream.timer(3000) |> Stream.run"  0.16s user 0.07s system 3% cpu 6.199 total
```

So we are indeed doubling.

Next test:

Stream.interval is implemented as follows:
```
    unfold 0, fn (count) ->
      :timer.sleep(n)
      {count, count + 1}
    end
```

Stream.timer is just `Stream.interval(n) |> Stream.take(1)`

Let's look at side-effects and `take`:

```
iex(1)> Stream.unfold(1, fn(n) ->
...(1)>   IO.inspect n
...(1)>   {n, n + 1}
...(1)> end) |> Enum.take(1)
1
[1]
iex(2)> Stream.unfold(1, fn(n) ->
...(2)>   IO.inspect n
...(2)>   {n, n + 1}
...(2)> end) |> Stream.take(1) |> Stream.run
1
2
:ok
```
So this actually seems to be a bug in `Stream.take`. `Stream.take` causes a second side effect where `Enum.take` does not.

**Comment by hamiltop** [comment]
@josevalim is this related to the "halt with new acc" issue we've talked about before? I think it was https://github.com/elixir-lang/elixir/issues/2676

**Comment by hamiltop** [comment]
For more context, Stream.take is implemented as follows:

```elixir
  defmacro take(f \\ nil) do
    quote do
      fn(entry, acc(h, n, t) = orig) ->
        if n >= 1 do
          next_with_acc(unquote(f), entry, h, n-1, t)
        else
          {:halt, orig}
        end
      end
    end
  end
```

The key is that we don't halt when n == 1, we halt when n == 0 (which means we've taken 2 elements when we were only supposed to take one). if we change the halting case to take an element it should fix the problem. Going to give it a shot.

**Comment by hamiltop** [comment]
Quick fix in https://github.com/elixir-lang/elixir/pull/3381

Seems to fix timer issue:

```
time ./bin/elixir -e "Stream.timer(1000) |> Stream.run" 
./bin/elixir -e "Stream.timer(1000) |> Stream.run"  0.15s user 0.06s system 17% cpu 1.178 total
time elixir -e "Stream.timer(1000) |> Stream.run"
elixir -e "Stream.timer(1000) |> Stream.run"  0.17s user 0.08s system 10% cpu 2.235 total
```

`./bin/elixir` is built from my branch
`elixir` is 1.0.4

**Comment by josevalim** [comment]
Fixed in master. Thank you! <3
