### ISSUE TITLE
Does not compile ...

### ISSUE THREAD

**Issue by vsraptor** [elixir-lang/elixir#3380]
I'm getting this error when trying to compile from source. Any idea why ? (linux mint)

  1) test fails on missing write access to .beam file (Kernel.CLI.CompileTest)
     test/elixir/kernel/cli_test.exs:113
     expected compilation error message due to not having write access
     stacktrace:
       test/elixir/kernel/cli_test.exs:124
......
Finished in 23.1 seconds (17.2s on load, 5.8s on tests)
1943 tests, 1 failure

Randomized with seed 207009
make: *** [test_stdlib] Error 1

**Comment by josevalim** [comment]
Which operating system are you using? How are you compiling it? The issue seems to be that we are marking a directory as read only but your operating system is not accepting that. There is nothing wrong with Elixir per-se, likely a fault in the est.

**Comment by msaraiva** [comment]
Are you compiling as root user? Because some linux distributions will ignore the readonly flag (set on line 120) if you are root. If that's the case, `&elixirc/1` will overwrite the beam file and the test fails. Try to compile Elixir as a regular user.

**Comment by vsraptor** [comment]
thanks, running as normal user went pass this error, but now I get :
(The OS is LinuxMint)
I'm doing "make clean test"

==> mix (exunit)
..................

  1) test get and compile dependencies for rebar (Mix.RebarTest)
     test/mix/rebar_test.exs:81
     ** (Mix.Error) Could not compile dependency rebar_dep, /my/compile/elixir/lib/mix/tmp/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile rebar_dep
     stacktrace:
       (mix) lib/mix.ex:235: Mix.raise/1
       (mix) lib/mix/project.ex:196: Mix.Project.in_project/4
       (elixir) lib/file.ex:1105: File.cd!/2
       (mix) lib/mix/dep.ex:137: Mix.Dep.in_dependency/3
       (mix) lib/mix/tasks/deps.compile.ex:158: Mix.Tasks.Deps.Compile.do_command/4
       (mix) lib/mix/tasks/deps.compile.ex:62: anonymous fn/3 in Mix.Tasks.Deps.Compile.compile/1
       (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3

**Comment by milmazz** [comment]
@vsraptor I think this could be a permissions issue (in this case Elixir couldn't correctly execute the `File.cd`), can you try to execute `make clean` as `root` and then try `make test` as normal user? or just delete everything, then `git clone` and try to compile as normal user.

**Comment by vsraptor** [comment]
Tried clonning and compiling from scratch again with local user and still get the same error.
(btw earlier before compiling I did chown on all dirs, just so you know)

**Comment by josevalim** [comment]
It is defnitely something related to permissions on your OS. If you reach `/my/compile/elixir/lib/mix/tmp/.mix/rebar` after you run tests, are its permissions properly set?

**Comment by vsraptor** [comment]
$ ls /my/compile/elixir/lib/mix/tmp/.mix/rebar -ltr
-rwxr-xr-x 1 vs vs 164740 Jun  5 18:52 /my/compile/elixir/lib/mix/tmp/.mix/rebar

**Comment by msaraiva** [comment]
Even though this is definitely related to vsraptor's environment,  the test on [cli_test.exs:113](https://github.com/elixir-lang/elixir/blob/b5a00d463d4ea328e0eff00b06115797861843b0/lib/elixir/test/elixir/kernel/cli_test.exs#L113) is the only one that fails when running as root user. I also confirmed this problem on OSX and Alpine Linux. So it will probably fail on many other Linux distributions. I think this test should be ignored when running as root. One way to achieve this is to replace:
```Elixir
if !System.get_env("FAKEROOTKEY") do
```
with
```Elixir
if System.get_env("USER") != "root" do
```
or, in case we don't trust the `USER` variable:
```Elixir
if (System.cmd("id", ["-u"], []) |> (fn({uid, 0})-> uid end).() |> String.strip) != "0" do
```

We could also try to set the immutable bit on the file using `chflags` and `chattr` according to the environment. But I think that would be too much trouble for such a simple thing.

Any other ideas? Should I create a pull request for this?

**Comment by josevalim** [comment]
A pull request that checks for "USER" != "root" sounds like a good idea to me. :)

**Comment by msaraiva** [comment]
Just confirmed that checking the `USER` environment variable will not work across all linux distributions. Fakeroot doesn't define it either. So, using `id -u` really looks ugly, but so far, is the only way I could find that always works. Waiting for suggestions.

**Comment by josevalim** [comment]
The issue is that `id -u` is also specific to windows. Maybe what we should do is to manually try to write to the directory after we mark it as read-only and, if the write succeeds, we do not run the rest of the test?

**Comment by msaraiva** [comment]
Using `File.stat/1` to get the `access` attribute after `chmod` did the trick. Tested on:

- OS X + normal user
- OS X + root
- Alpine Linux + normal user
- Alpine Linux + root
- Alpine Linux + fakeroot

Hope it works for all cases.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
