### ISSUE TITLE
proposal for struct/3

### ISSUE THREAD

**Issue by jschoch** [elixir-lang/elixir#3383]
I'd like propose a option in Kernel.struct that would allow for "kv" to contain elements not defined in defstruct, vs the default which drops them.

struct( struct,kv, [decorate: true])

**Comment by josevalim** [comment]
The point of `struct/2` is to validate the keys, if you want to just merge kv, you can use Map.merge or Dict.merge with the struct as first argument.

Also, please remember to send proposals to the core mailing list. :) Thanks!

**Comment by jschoch** [comment]
struct/2 doesn't validate the keys though.  it should crash if they keys are not in "kv", or it should crash if there are extra keys if structs are intended not to be decorated.

**Comment by ericmj** [comment]
"Decorating" structs is not something we recommend. If you want to add dynamic fields just use a map instead.
