### ISSUE TITLE
Warn when using _var

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#3386]
Warn when using a variable prefixed with `_`. E.g.
```elixir
def fun(_var) do
  _var + 1 #warn here
end
```

**Comment by whatyouhide** [comment]
:+1:

**Comment by ericmj** [comment]
We also need to make sure we catch pattern matching cases, such as: `def fun(_var, _var) do ...`.

**Comment by josevalim** [comment]
We already warn on those.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Lead Developer
