### ISSUE TITLE
`String.Chars` implementation for `Regex` is missing

### ISSUE THREAD

**Issue by padde** [elixir-lang/elixir#3388]
Is there any good reason why there is no `String.Chars` implementation for `Regex`? Possibly it is a bug? Being able to compose complex regexes with interpolation to make them more readable makes so much sense to me. IMHO this should be included:

    defimpl String.Chars, for: Regex do
      def to_string(regex), do: Regex.source(regex)
    end

So we can do:

    hours = ~r/[0-2]?[0-9]/
    minutes = ~r/[0-5][0-9]/
    seconds = ~r/[0-5][0-9]/
    
    assert ~r/#{hours}/ === hours
    assert ~r/#{hours}:#{minutes}(:#{seconds})?/ === ~r/[0-2]?[0-9]:[0-5][0-9](:[0-5][0-9])?/

Maybe you can give it a thought. Thanks!

**Comment by josevalim** [comment]
Regexes do not compose like that. What if the regex is tagged as case insensitive with `i`? Or another modifier? It can get really complex, really fast.

Also, please remember to send feature requests to the elixir core mailing list. :)

**Comment by alco** [comment]
@padde A more controllable approach to composing a complex regex from simpler components is to define each component as a string. This, for example, works beautifully:

```elixir
hours = "[0-2]?[0-9]"
minutes = "[0-5][0-9]"
seconds = "[0-5][0-9]"

time_re = ~r/#{hours}:#{minutes}(:#{seconds})?/
Regex.run(time_re, "23:24:25")
```

**Comment by padde** [comment]
@josevalim, thanks for your reply!

Ok I see so the source of a Regex is not enough to describe it entirely, we need the flags as well.
I just realized that Ruby fixes this with the `(?-mix:)` syntax:

    /#{"a"}/
    => /a/
    
    /#{/a/}/
    => /(?-mix:a)/
    
    /#{/a/m}/
    => /(?m-ix:a)/

Maybe Elixir could benefit from this as well, but it's of course far more work than what I posted above. If you see any chance this could happen, we can continue discussing it on the mailing list.

PS: Sorry, I'll directly use the mailing list next time! :)

**Comment by padde** [comment]
Oh I just saw that the Erlang `re` module also supports the `(?-mix:)` syntax, it seems to be standard, I thought it was Ruby-specific.

See http://erlang.org/doc/man/re.html#id222438

If you'd be interested, I could dive into this.

@alco thanks, but I was specifically looking at composing Regex directly. I have a use case where I need to use the subpatterns as well. For now I build them all as strings and then again compile them as regexes but it's not the prettiest and most straightforward solution IMHO.

**Comment by padde** [comment]
@josevalim I played around a bit trying to mimic the way Ruby does it and (of course) you were right not attempting a solution to this, because there is none. Modifiers like `u` (unicode) and `f` (firstline) act globally for the pattern and if the surrounding pattern has one of them, it cannot be prevented that it changes the semantics of an embedded pattern. This could only work if we could check for the equality of global modifiers of both patterns and raise an error otherwise, but `String.Chars` is not built for that. Other modifiers can be switched around inside the pattern (Ruby does this), but this won't work for global modifiers either.

If someone's interested, I put my experiments into [this Gist](https://gist.github.com/padde/d31b1a1028d7d61f5bf4).

Thanks for hearing me out though ;-)
