### ISSUE TITLE
IEX.pry from another node

### ISSUE THREAD

**Issue by kdisneur** [elixir-lang/elixir#3392]
When you want to debug a Phoenix application for example, the application process must run in the same iex process (i.e: `iex -S mix phoenix.start`).

It could be awesome if we could pry from another iex node.

**Comment by josevalim** [comment]
@kdisneur I am travelling today and I just tried some sample implementation out. My first approach was that IEx.pry would automatically find another node, giving preference to local implementation.

However, we can only find nodes that have been connected upfront, so your code sample would only work if you called `Node.connect :foo` from node `:bar` or vice-versa, which kinda defeats the purpose.

The only other option I can think is to pass the node name directly as argument, something like: `IEx.pry(:name_of_the_other_node)`. Thoughts?

**Comment by kdisneur** [comment]
> However, we can only find nodes that have been connected upfront, so your code sample would only work if you called Node.connect :foo from node :bar or vice-versa, which kinda defeats the purpose.

Yup it makes sense and, anyway, trying to automatically find an IEX node would maybe be too much magic?

> The only other option I can think is to pass the node name directly as argument, something like: IEx.pry(:name_of_the_other_node). Thoughts?

Just to be sure to understand it well, your proposition is:

* in your main app: just put IEx.pry(:name_of_the_other_node)
* on another shell: start iex --sname name_of_the_other_node
* profit \o/

This option looks pretty simple (in a user point of view) because it's easy to start an IEX with a specific name.

Maybe could be worth to ask @jtrim is thought (it's the author of the [blog post](http://www.jessetrimble.net/iex-pry-elixir/) talking about this feature)

**Comment by fishcakez** [comment]
Have you tried using `--remsh` to start an IEx session on the target node from another node?

**Comment by fishcakez** [comment]
Oh I just tested and it doesn't work :(

**Comment by fishcakez** [comment]
Just to clarify my comments, I was a little brief. I think we should support:
```
elixir --name "foo@host" -S mix run
```
and
```
iex --name "bar@host" --remsh "foo@host"
```
Where `IEx.pry/0` is called from an application on `foo@host`. The fact this doesn't work is a bug. I think this is preferable to adding the node name because the node does not need to be known in advance.

**Comment by josevalim** [comment]
Added with 4af9b7e003d376fa65de5f963d8547cbca8cb694.

**Comment by kdisneur** [comment]
Thanks @josevalim

**Comment by jtrim** [comment]
Wow, I should pay more attention to Twitter. Great work @josevalim @kdisneur - such a pleasant surprise to find one of my blog posts spurred development on a core IEx feature! Thanks for implementing! :clap:
