### ISSUE TITLE
Use the same function in Float.to_string as Kernel.to_string

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3401]

**Comment by andrzejsliwa** [comment]
@josevalim what about formatting options?

String.Chars protocol probably should be extended to handle both clauses:

def to_string(thing)
def to_string(thing, options)

**Comment by andrzejsliwa** [comment]
then we can implement for example

defimpl String.Chars, for: Integer do
  def to_string(thing) do
    Integer.to_string(thing)
  end
  def to_string(thing, base) do
    Integer.to_string(thing, base)
  end
end

**Comment by andrzejsliwa** [comment]
next thing... that we have here inconsistency:

some of **defimpl** are defined in **lib/string/chars.ex** (for Integer, Float etc)
and some of them are inside of other module files: (for example **lib/uri.ex**)

what is preferred place to keep protocol implementations

**Comment by andrzejsliwa** [comment]
I would refactor **lib/uri.ex** example

from:

```elixir
defimpl String.Chars, for: URI do
  def to_string(uri) do
    scheme = uri.scheme

    if scheme && (port = URI.default_port(scheme)) do
      if uri.port == port, do: uri = %{uri | port: nil}
    end

    # Based on http://tools.ietf.org/html/rfc3986#section-5.3

    if uri.host do
      authority = uri.host
      if uri.userinfo, do: authority = uri.userinfo <> "@" <> authority
      if uri.port, do: authority = authority <> ":" <> Integer.to_string(uri.port)
    else
      authority = uri.authority
    end

    result = ""

    if uri.scheme,   do: result = result <> uri.scheme <> ":"
    if authority,    do: result = result <> "//" <> authority
    if uri.path,     do: result = result <> uri.path
    if uri.query,    do: result = result <> "?" <> uri.query
    if uri.fragment, do: result = result <> "#" <> uri.fragment

    result
  end
end
```

to: 


```elixir
defimpl String.Chars, for: URI do
  def to_string(uri) do
     URI.to_string(uri)
  end
end
```

```elixir
defmodule URI do
 def to_string(uri) do
    scheme = uri.scheme

    if scheme && (port = URI.default_port(scheme)) do
      if uri.port == port, do: uri = %{uri | port: nil}
    end

    # Based on http://tools.ietf.org/html/rfc3986#section-5.3

    if uri.host do
      authority = uri.host
      if uri.userinfo, do: authority = uri.userinfo <> "@" <> authority
      if uri.port, do: authority = authority <> ":" <> Integer.to_string(uri.port)
    else
      authority = uri.authority
    end

    result = ""

    if uri.scheme,   do: result = result <> uri.scheme <> ":"
    if authority,    do: result = result <> "//" <> authority
    if uri.path,     do: result = result <> uri.path
    if uri.query,    do: result = result <> "?" <> uri.query
    if uri.fragment, do: result = result <> "#" <> uri.fragment

    result
  end
end
```

@josevalim @ericmj what do you think about making this kind of cleanup refactor together with fixing float protocol issue?
maybe we should create new issue for refactor instead?

**Comment by josevalim** [comment]
Yes, it is a different issue. Also, we implement the native types with the
protocol. Custom types implement in the type file, like URI. So please do
not move the protocol implementation around, S there may also be bootstrap
issues.

Also, string.chars should my accept options because the options would be
received by all types.


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by andrzejsliwa** [comment]
> On 20 Jun 2015, at 22:35, José Valim <notifications@github.com> wrote:
> 
> Also, string.chars should my accept options because the options would be
> received by all types.

what you mean?  sorry I don't get it.

the code which I posted as example (with two functions in protocol contract) have
some drawback... we have warnings in every defimpl which have missing second version with options.

so we have two options:
- fix all defimpl for missing second function (with ignoring or using option(s) argument depending from context and place)
- just don't add options (and lose flexibility of protocol)

do you see any other way to do it?

I want to clarify it before I will propose code changes.

**Comment by josevalim** [comment]
Sorry, autocomplete messed me up. What I meant is that we should not add
options to String.Chars as It is meant to be generic and work across all
data types. So it doesn't make sense to add float specific options to its
API. In other words, we are not touching String.Chars.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by andrzejsliwa** [comment]
so then issue is about using protocol inside of Float module?
```elixir
defmodule Float do
  ...
  def to_string(float) do
    :erlang.float_to_binary(float)
  end
  ...
end
```
Vs

```elixir
defmodule Float do
  ...
  def to_string(float) do
    String.Chars.to_string(float)
  end
  ...
end
```

would be great to put detailed problem description otherwise its difficult to get it only from subject:
"Use the same function in Float.to_string as Kernel.to_string"

**Comment by josevalim** [comment]
Yes, I have created the issue as a reminder. I still need to add the proper
tags and description. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Thanks @andrzejsliwa. I have opened an issue with a proper description now at #3413. If there is any issue poorly described, feel free to ping me and I will work on it. Many times I open them as reminders and forget to update them later (sorry!)

**Comment by andrzejsliwa** [comment]
Np i will take a look on it tomorw. My    laptop just died
