### ISSUE TITLE
Considering adding Enum.reduce_while/3

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3402]
Today, we don't have a mechanism for reducing while some condition is true besides calling Enumerable. For such, we could add reduce_while that is a thin wrapper around Enumerable.reduce:

    def reduce_while(collection, acc, fun) do
      Enumerable.reduce(collection, {:cont, acc}, fun) |> elem(1)
    end

The `fun` should return `{:cont, acc}` or `{:halt, acc}`. Thoughts?

**Comment by tony612** [comment]
How about letting `fun` just return `acc` when we want to continue like what in `Enum.flat_map_reduce`?
And, do we need `Enum.reduce_while/2`?

**Comment by doomspork** [comment]
I like returning `{:cont, acc}` or `{:halt, acc}`, I think it makes the intention very clear and is different enough to not cause too much confusion with `reduce/3`.  

I'd be glad to take a stab at implementing this is no one else has called dibs.

**Comment by whatyouhide** [comment]
Yes, this! I found myself wanting a function like this more than once. I happily call second dibs if for any reason @doomspork's gives up his/her dibs :smile:

**Comment by josevalim** [comment]
@doomspork please do send a PR!

**Comment by doomspork** [comment]
Sweet!  @josevalim I will work on it this evening, thank you for the opportunity!

**Comment by josevalim** [comment]
I am the one who should be thanking here! :D
