### ISSUE TITLE
call `quote` then `Macro.to_string` on `def`, got different results

### ISSUE THREAD

**Issue by jiyinyiyong** [elixir-lang/elixir#3414]
Look at the code:

```elixir
(
  ast = quote do: (
    def add(x) do
      x + 1
    end
  )
  IO.inspect ast
  IO.puts Macro.to_string ast
)
```

```elixir
➤➤ elixir demo.ex
{:def, [context: Elixir, import: Kernel],
 [{:add, [context: Elixir], [{:x, [], Elixir}]},
  [do: {:+, [context: Elixir, import: Kernel], [{:x, [], Elixir}, 1]}]]}
def(add(x)) do
  x + 1
end
➤➤ elixir -v
Elixir 1.0.2
➤➤ uname -a
Darwin Air.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 16 23:12:31 PDT 2015; root:xnu-2782.20.48~4/RELEASE_X86_64 x86_64
```

I thought `Macro.to_string` is just the reversed operation of `quote` or something.
This result `def(add(x)) do` is not the expected one. Bug?

**Comment by ericmj** [comment]
The quoted AST doesn't keep the input string so when when converted back to strings it can change. Example:

```iex
iex(1)> x = quote do: (((1)))
1
iex(2)> Macro.to_string x
"1"
```

In this case you are using optional parenthesis when calling the `def` macro and `Macro.to_string` always uses parenthesis for function calls.

**Comment by jiyinyiyong** [comment]
Did you mean `Macro.to_string` will never return a correct function(or macro) back? What a bad news >_<

**Comment by ericmj** [comment]
It is correct, try using the code it returns. It has the same behaviour as the input string but not necessarily the same format.

**Comment by jiyinyiyong** [comment]
I got some problem here, the generated code does not work:
```
iex(1)> def(add(x)) do
...(1)>   x + 1
...(1)> end
** (ArgumentError) cannot invoke def/2 outside module
    (elixir) lib/kernel.ex:3556: Kernel.assert_module_scope/3
    (elixir) lib/kernel.ex:2816: Kernel.define/4
    (elixir) expanding macro: Kernel.def/2
    (elixir) iex:1: :elixir_compiler.__FILE__/2
```

**Comment by ericmj** [comment]
Your original code doesn't work either. As the error message says you cannot use `def` outside modules.

**Comment by jiyinyiyong** [comment]
Oh, my mistake, it's outside module. So it's still valid syntax itself.
Thank you.
