### ISSUE TITLE
Automatic add `application` to Logger meta data

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/elixir#3418]
Related to Mailing List [discussion](https://groups.google.com/forum/#!topic/elixir-lang-talk/le8bN2f_O28)

> We would need some sort of configuration, Application.get_env(:logger, :current_application), and Mix could set it before compiling stuff. 
> - @josevalim 

It will allow to trace the whole application logs in the future.

**Comment by fishcakez** [comment]
Added as `:compile_time_application` in https://github.com/elixir-lang/elixir/commit/4d69404bfe92cb6324f9aa47e05bc7156fc088be.
