### ISSUE TITLE
mix downloads Rebar over plain HTTP

### ISSUE THREAD

**Issue by bgentry** [elixir-lang/elixir#3423]
The mix tool currently downloads and installs rebar over plain HTTP rather than HTTPS: https://github.com/elixir-lang/elixir/blob/4f68c4f10502e0f54a21093bb9a33957e63a9ac4/lib/mix/lib/mix/tasks/local.rebar.ex#L4

Perhaps the tool is verifying the integrity of this file (haven't verified that, but hopefully it's at least doing that). Regardless, using plain HTTP unnecessarily leaks additional metadata and makes it possible for intermediaries (i.e. captive portals like airplane, hotel, or coffee shop wifi) to mess with responses.

I understand there may be a lot of history as to why this is currently done without TLS (some is discussed in https://github.com/elixir-lang/elixir/issues/2152), but I'm sure there are some workable solutions and cost-effective (maybe free) options for this.

cc @ericmj 

I previously reported this in the hex project by mistake, and there is some more detail there: https://github.com/hexpm/hex_web/pull/127

**Comment by josevalim** [comment]
This is fixed on v1.1 to be released soon! Thank you!

**Comment by ericmj** [comment]
@josevalim Thanks for your research and efforts you put into this. :heart:
