### ISSUE TITLE
Use https instead of git for github

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3424]
However, we need to be careful so it doesn't require everyone to run `mix deps.get`.

**Comment by hubertlepicki** [comment]
I think `mix` already uses HTTPS by default. Or this is not what you meant, @josevalim ?

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/scm/git.ex#L30

**Comment by hubertlepicki** [comment]
ah I can see the change was already made and reverted
