### ISSUE TITLE
Allow piping Elixir code into "elixir" binary

### ISSUE THREAD

**Issue by henrik** [elixir-lang/elixir#3425]
You can do it with ruby:

``` bash
echo "p 123" | ruby
```

I use this a lot in Vim to run the contents of a buffer as a script, whether or not it's a saved file:

``` vim
:w ! ruby
```

But the elixir binary doesn't seem to accept code this way.

Sorry for not making a pull request at this time – I might find the time/inclination later, but if someone else wants a stab at this please do go ahead.

**Comment by josevalim** [comment]
I am ok with supporting this if we can detect upfront if there is something in stdin and still show help if elixir is invoked without arguments. Otherwise it is a no-go because showing the help is more useful. Or we could do it with a flag.

**Comment by henrik** [comment]
Yeah, I think I've seen it done with a `-` flag, so `mybin` would show help but `mybin -` would wait for STDIN.

I just looked into STDIN detection a bit. Seems that in bash (but probably not portable across all shells) you can do

``` bash
if [ -t 0 ]; then
  echo "STDIN is a terminal"
else
  echo "STDIN is not a terminal, so probably a pipe"
fi
```

But maybe that's not good enough. My shell scripting and *ux knowledge isn't super strong.

**Comment by henrik** [comment]
Ah, Vim itself is where I've seen the "-" thing:

```
usage: vim [arguments] [file ..]       edit specified file(s)
   or: vim [arguments] -               read text from stdin
```

`vim` without arguments will simply open the editor in the current directory.

**Comment by stevedomin** [comment]
@josevalim can I take a stab at this?

**Comment by josevalim** [comment]
Yes, please!

**Comment by henrik** [comment]
@stevedomin :heart: Awesome, godspeed!

**Comment by eksperimental** [comment]
a very interesting article (a its comment thread) on the subject: http://www.linuxjournal.com/content/determine-if-shell-input-coming-terminal-or-pipe

**Comment by josevalim** [comment]
I am closing this. If someone wants to tackle it, please go ahead, it is not a priority in our books.
