### ISSUE TITLE
Unit tests failing with Erlang/OTP 18.0

### ISSUE THREAD

**Issue by ojakubcik** [elixir-lang/elixir#3426]
After installing OTP 18.0 and recompiling Elixir (both latest development version 91ce4a6b57854359d897090939d5f1e59b69e33e and 1.0.4 tag), the following errors appear when running `make -k test` (rest of unit tests omitted for brevity):

    ==> elixir (exunit)
      1) test update maps (MapTest)
         test/elixir/map_test.exs:85
         Expected exception ArgumentError but got ErlangError (erlang error: {:badkey, :c})
         stacktrace:
           test/elixir/map_test.exs:88
    
    ==> logger (exunit)
    test/logger_test.exs:222: warning: variable pid is unused
    .........................
    
      1) test formats error_logger warning report (Logger.ErrorHandlerTest)
         test/logger/error_handler_test.exs:48
         Assertion with =~ failed
         code: error_log(:warning_report, "hello") =~ msg("[error] \"hello\"")
         lhs:  "\n20:29:02.333 [warn]  \"hello\"\n"
         rhs:  ~r/\d\d\:\d\d\:\d\d\.\d\d\d \[error]\ "hello"/
         stacktrace:
           test/logger/error_handler_test.exs:50
    
      2) test formats error_logger warning message (Logger.ErrorHandlerTest)
         test/logger/error_handler_test.exs:42
         Assertion with =~ failed
         code: error_log(:warning_msg, "hello", []) =~ msg("[error] hello")
         lhs:  "\n20:29:02.335 [warn]  hello\n"
         rhs:  ~r/\d\d\:\d\d\:\d\d\.\d\d\d \[error]\ hello/
         stacktrace:
           test/logger/error_handler_test.exs:44

**Comment by josevalim** [comment]
Yes, we are working on those. Thank you!
