### ISSUE TITLE
elixir 1.0.4 tests not passing with Erlang 18.0

### ISSUE THREAD

**Issue by Alamoz** [elixir-lang/elixir#3429]
Just upgraded to Erlang 18.0 and then rebuilt Elixir 1.0.4. Looks like some breakage. Should I fall back to Erlang 17.x?

**Comment by ericmj** [comment]
It's just tests that need to be updated. Elixir 1.0.4 works with OTP 18.

**Comment by Alamoz** [comment]
Thank you. Looking forward to taking it for a spin.

**Comment by Alamoz** [comment]
What about this message during compile?:

Compiled lib/agent/server.ex
lib/hash_dict.ex:261: warning: behaviour Inspect undefined
Compiled lib/hash_dict.ex

**Comment by ericmj** [comment]
That message will not cause you any issues.
