### ISSUE TITLE
I can't use "iex" and "exilir" on Win7

### ISSUE THREAD

**Issue by brosmaninho** [elixir-lang/elixir#343]
I did the step-by-step from your "getting stated" section, "1.1.2 Precompiled package" and i had this errors below:
# 

Microsoft Windows [versão 6.1.7600]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\XXX>iex
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[{file,"init.erl"},{line,1042}]},{init,start_em,1,[{file,"init.erl"},{line,1022}]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

C:\Users\XXX>elixir
Usage: elixir.bat [options] [.exs file] [data]

 -v              Prints version and exit
 -e command    Evaluates the given command (_)
 -r command    Requires the given file/pattern (_)
 -pr command   Requires the given file/pattern in parallel (_)
 -pa path     Prepend the given path to Erlang code path (_)
 -pz path      Append the given path to Erlang code path (*)
 --no-halt       Do not halt the Erlang VM after execution

*\* Options marked with (*) can be given more than once;

*\* Options given after the .exs file or -- are passed down to the executed code;

*\* Options can be passed to the erlang runtime using ELIXIR_ERL_OPTS.
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[{file,"init.erl"},{line,1042}]},{init,start_em,1,[{file,"init.erl"},{line,1022}]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()

C:\Users\XXX>
#

**Comment by dcotoz** [comment]
Is this solved?

**Comment by josevalim** [comment]
Yes, it should be solved.

**Comment by dcotoz** [comment]
It doesnt work. I have windows 7, and when I try to run iex I get some error messages in German, and then they tell me that the crash dump was written on a file

**Comment by josevalim** [comment]
How are you running it? How did you install Elixir? Please try to provide more info. Are you sure you are running the `iex.bat`? Thanks!

**Comment by dcotoz** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9681009/6445779/f7a3ebba-c0cb-11e4-8ca2-5163c51c92cd.png)

That's  a screenshot of what Im getting

**Comment by josevalim** [comment]
Which command are you running and how have you installed Elixir?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Lead Developer*

**Comment by dartg** [comment]
I am facing the same issue. I uninstalled Elixir 1.5 to install 1.6.6, but now I'm getting this error:

![error](https://user-images.githubusercontent.com/6503980/42839225-6b54726c-89d9-11e8-8cfd-dd7da037edff.png)

I tried installing Elixir 1.6.6, 1.6.5, 1.6.4, 1.5.3, with no luck. I tried switching from OTP 21 to 20.3, then back to 20.0, no luck at all.

Any ideas? I'm on Windows 8 x64.

**Comment by OvermindDL1** [comment]
@dartg This is usually better to ask on the forums, but did you uninstall and reinstall elixir *after* switching OTP versions?  Remember that elixir must be installed after each OTP install so it can compile to the installed version.

**Comment by OvermindDL1** [comment]
Hmm, I'd try wiping both out, uninstallers then deleting their directories, then re-install.
