### ISSUE TITLE
Task.call for doing asynchronous GenServer.calls

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#3448]
`Task.call/3` will be used for doing asynchronous `GenServer.call/3`. Instead of blocking in the call a `%Task{}` will be returned that can be awaited on with `Task.await/2`.

**Comment by fishcakez** [comment]
The returned `%Task{}` can not be guaranteed to work with `Task.shutdown/2` because we may not know the `pid` - i.e. `{name, node}` is used.

**Comment by josevalim** [comment]
@fishcakez in fact, `shutdown/2` is not even beneficial here. Should we store some information in the task and raise when they are powered by a GenServer?

**Comment by fishcakez** [comment]
Well we can set the `pid` to `:call` or `nil`?

**Comment by josevalim** [comment]
@fishcakez I think I am ok with not setting the PID, yeah.

**Comment by fishcakez** [comment]
Introducing a `Task.call` may limit us when bringing in new behaviours in 1.3. https://github.com/elixir-lang/elixir/commit/0a8324597a3ff180c2819ec637d2aeddf80cc6de and https://github.com/elixir-lang/elixir/commit/84e3b895c1109c7188b31f5d97e4001354e174e9 adds the ability to define a task without a pid using a custom process monitor.

The following can be used to create the rough equivalent of a `Task.call` but the GenServer must explicitly call `reply/2` on the "fake" `from` term:
```elixir
ref = Process.monitor(pid)
GenServer.cast({:hello, {self(), ref}})
%Task{ref: ref}
```

If the process is a name and not a `pid` then the process should be looked up - unless its of the type `{name, non_local_node}`, when that tuple should be used.

**Comment by josevalim** [comment]
@fishcakez we need though to raise if there is no pid on Task.shutdown and add GenServer.whereis as an alternative to this. Should we track this in this issue or elsewhere? :)

**Comment by josevalim** [comment]
Opening this until we get those in so we don't lose track. :)

**Comment by fishcakez** [comment]
The first commit I linked raises in `Task.shutdown`, and the second commit add support for custom tasks with `{name, node}` monitors.  I had forgotten about GenServer.whereis though.

**Comment by josevalim** [comment]
I completely missed those commits. Great job there!

**Comment by fishcakez** [comment]
Part of me wants GenServer.async(server, request) and a `handle_async/3` callback that works exactly like `handle_call/3`, the other half of me wants to burn the former half at the stake for blasphemy.

**Comment by josevalim** [comment]
Haha, it is too much to decide for 1.1 anyway. We can't go wrong with the basic toolkit. :)

**Comment by fishcakez** [comment]
`GenServer.whereis/1` is in https://github.com/elixir-lang/elixir/commit/ff3c641add24da67410c24491e802c5d5891a11a
