### ISSUE TITLE
Error on `mix compile`

### ISSUE THREAD

**Issue by jordi-chacon** [elixir-lang/elixir#3450]
My top-level mix.exs file is the following: https://gist.github.com/jordi-chacon/624610f2a42a68aa8e64

Both my top-level application and the `folsom` dependency have `meck` as a dependency. This seems to cause problems when compiling. (Note that folsom is an Erlang application).
```
mix compile
Unchecked dependencies for environment dev:
* meck (git://github.com/eproxus/meck)
  the dependency is not available, run `mix deps.get`
** (Mix) Can't continue due to errors on dependencies
```

Running `mix deps.get` doesn't help:
```
Running dependency resolution
Dependency resolution completed successfully
All dependencies up to date
```

@ericmj thinks this is a bug.

**Comment by Host32** [comment]
Remove meck from `deps` list and add it to the `applications` list

´´´
  def application do
    [mod: {MyService, []},
     applications: [:httpex, :meck],
     included_applications: [:storex]
    ]
  end
 
  ( ... ) 

  defp deps do
    [{:exrm, "~> 0.16.0"},
     {:folsom, git: "git@github.com:boundary/folsom", branch: "master", override: true},
     {:folsomite, git: "git@github.com:campanja/folsomite", branch: "master"},
     {:httpex, git: "git@github.com:.../httpex", branch: "master"},
     {:storex, git: "git@github.com:.../storex", branch: "master"}]
  end
´´´

**Comment by pma** [comment]
@jordi-chacon I addressed this by removing the `only: :test` option. 

My understanding of the issue is that since there is no concept of deps environment in rebar, meck has to be available in all (mix) environments, not just test.

**Comment by ericmj** [comment]
We should either try to handle overriding a prod dependency with a test dependency or we should error explaining that it is not possible.

**Comment by josevalim** [comment]
I tried to fix this buy I ran into this:

```elixir
$ mix compile
==> bear (compile)
Compiled src/bear.erl
WARN:  Expected /Users/jose/OSS/foo/_build/dev/lib/meck to be an app dir (containing ebin/*.app), but no .app found.
==> folsom (compile)
WARN:  Expected /Users/jose/OSS/foo/_build/dev/lib/meck to be an app dir (containing ebin/*.app), but no .app found.
Dependency not available: meck-.* ({git,"git://github.com/eproxus/meck",
                                       {tag,"0.8.2"}})
ERROR: compile failed while processing /Users/jose/OSS/foo/deps/folsom: rebar_abort
** (Mix) Could not compile dependency folsom, /Users/jose/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile folsom
```

I am not sure how to best fix this. It seems that we cannot fix dependencies conflicting in different environments?
