### ISSUE TITLE
Mix is unable to install local.hex from s3

### ISSUE THREAD

**Issue by wsmoak** [elixir-lang/elixir#3451]
Following http://www.phoenixframework.org/v0.14.0/docs/installation I cannot get hex installed
 
$ mix local.hex
[takes about 30 seconds, then]
** (Mix) Could not access url https://s3.amazonaws.com/s3.hex.pm/installs/list.csv, error: {:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet, [:inet], :eperm}]}

I am able to retrieve the file with curl 
$ curl https://s3.amazonaws.com/s3.hex.pm/installs/list.csv
0.0.1,0.13.0-dev
[...output snipped...]

There is a similar issue https://github.com/elixir-lang/elixir/issues/3075 however the error is different and I am not behind a proxy.

(discussed on #elixir-lang with ericmj who asked that an issue be opened)

**Comment by ericmj** [comment]
We need to figure out what the `:eperm` error means, according to the erlang docs it means "not owner" but not sure if that makes sense in this context.

**Comment by wsmoak** [comment]
After downloading and installing hex manually, I get the same error trying to install phoenix from github

$ mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.14.0.ez
Are you sure you want to install archive https://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.14.0.ez? [Yn] Y
** (Mix) Could not access url https://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.14.0.ez, error: {:failed_connect, [{:to_address, {'github.com', 443}}, {:inet, [:inet], :eperm}]}

For the record:
$ elixir -v
Elixir 1.0.4

**Comment by ericmj** [comment]
@wsmoak Could you try a non-https url, just a normal `http://`. That way we know if it's SSL related.

**Comment by wsmoak** [comment]
@ericmj first non ssl url I could think of, let me know if you want me to try something else:

$ mix archive.install http://wsmoak.net/index.html
** (Mix) mix archive.install doesn't know how to install /index.html

**Comment by ericmj** [comment]
You can try any of the github or amazonaws urls above with http://

**Comment by wsmoak** [comment]
Trying the phoenix url with http instead of https

$ mix archive.install http://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.14.0.ez
Are you sure you want to install archive http://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.14.0.ez? [Yn] Y
** (Mix) Could not access url http://github.com/phoenixframework/phoenix/releases/download/v0.14.0/phoenix_new-0.14.0.ez, error: {:failed_connect, [{:to_address, {'github.com', 80}}, {:inet, [:inet], :eperm}]}

**Comment by lancehalvorsen** [comment]
Can you reach the Phoenix archive link in a browser? If so, you can save the file from the browser to the filesystem as per this:
http://www.phoenixframework.org/v0.14.0/docs/installation#section-phoenix

**Comment by wsmoak** [comment]
After a restart, this is no longer happening.  I deleted ~/.mix and my test project and ran through the Installation and Up And Running guides again with no issues.

My suspicion is that it was Norton Firewall misbehaving and blocking the connection without popping up the usual prompt to allow or deny it.

Sorry for the noise, but at least it will be here in the archives if anyone else runs into it.
