### ISSUE TITLE
Unused Alias warnings when using Code.eval_quoted

### ISSUE THREAD

**Issue by thecodeboss** [elixir-lang/elixir#3453]
When compiling this code:
```elixir
defmodule Foo do
  defmacro deffilter(param, do: block) do
    {param, _} = Code.eval_quoted(param, [], __CALLER__)
    quote do
      def filter(unquote(param)) do
        unquote(block)
      end
    end
  end
end

defmodule Bar do
  import Foo
  alias System, as: MyAlias

  deffilter(MyAlias.cwd) do
    :hello
  end
end
```
I get the following warning: `test.ex:14: warning: unused alias MyAlias`

The alias is used, but its use happens during `Code.eval_quoted`. I'm unsure how much work it would be for the compiler to keep track of such alias uses, but it would be great if it did.

The code runs perfectly fine; In `iex` I can call `Bar.filter("/path/to/cwd")` and get the result `:hello`.

Also if this cannot be easily fixed, is there a clean way for me to suppress these warnings in this case?

**Comment by lexmag** [comment]
I think same as https://github.com/elixir-lang/elixir/issues/3277.

**Comment by lexmag** [comment]
Ah, and `warn: false` to suppress a warning.

**Comment by josevalim** [comment]
Yes. The compiler can't see it, so we can't avoid the warning.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by thecodeboss** [comment]
Thanks for pointing that out @lexmag, `warn: false` will work. #3277 was also enlightening toward the reason this does not work. I'll close this.
