### ISSUE TITLE
poor error message for dependency resolution

### ISSUE THREAD

**Issue by talentdeficit** [elixir-lang/elixir#3459]
in a project with a top level dependency of `{:foo, "1.2.3", override: true}` if there exists another dependency that also has `:foo` as a dependency like: `{:foo, "1.2.4", override: true}` or `{:foo, "1.2.2", override: true}` then dependency resolution fails with the following error message:

```elixir
Running dependency resolution
** (ArgumentError) could not put/update key :deps. Expected map/struct, got: nil
    (elixir) lib/access.ex:121: Access.Map.get_and_update!/3
    lib/hex/resolver.ex:190: Hex.Resolver.attach_dep_and_children/3
    lib/hex/resolver.ex:150: Hex.Resolver.get_deps/4
    lib/hex/resolver.ex:109: Hex.Resolver.activate/5
    lib/hex/resolver.ex:31: Hex.Resolver.resolve/3
    lib/hex/remote_converger.ex:33: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:79: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4

```

it doesn't seem to matter whether dependencies are hex deps or github deps, or whether the transitive dependency specifies a higher or lower version of the dependency

**Comment by ericmj** [comment]
Moved to https://github.com/hexpm/hex/issues/107
