### ISSUE TITLE
Get rid of Behaviour

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3465]
We needed it because Erlang required us to define behaviour_info, now we no longer need it, we can simply rely on module attributes.

**Comment by antipax** [comment]
@josevalim think I actually got pretty far on this today, going to finish up a few bits of my code tonight, can we chat tomorrow and do a quick review of what I have so far to make sure I'm going in the right direction?

**Comment by josevalim** [comment]
@antipax That's awesome, definitely!
