### ISSUE TITLE
Error installing Hex

### ISSUE THREAD

**Issue by bcs2002** [elixir-lang/elixir#3467]
Trying to install Hex and got this error msg:

** (Mix) Could not access url https://s3.amazonaws.com/s3.hex.pm/installs/list.csv, error: {:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet, [
:inet], :etimedout}]}

I am behind a proxy and using Windows 7 prof . It says "etimedout". Is it because of proxy?
But am able to access site https://s3.amazonaws.com/

thx

**Comment by ericmj** [comment]
How is your proxy configured? Have you set the `HTTP_PROXY` / `HTTPS_PROXY` environment variables?

**Comment by bcs2002** [comment]
Yes. But still getting timeout.

**Comment by bcs2002** [comment]
What is 443?

**Comment by josevalim** [comment]
443 is the port as we are using HTTPS.

**Comment by ericmj** [comment]
It's the default port used for HTTPS connections. Can you show how you configured your proxy?

**Comment by bcs2002** [comment]
Murphy's law here.  My sysadmin has left. :( .  Shall look into it tomorrow.
Thanks Jose and Eric for your valuable time.

**Comment by josevalim** [comment]
I have changed Elixir so we at least tell you instructions to download manually.

**Comment by bcs2002** [comment]
"I have changed Elixir so we at least tell you instructions to download manually."
Sorry ,Jose.  cant figure out what you mean.  Could you be a bit more specific?

**Comment by josevalim** [comment]
I meant that in future Elixir versions you will be given manual instructions about installing this instead of simply being greeted by an error and having no idea what to do. :)

PS: I removed the label by accident.

**Comment by bcs2002** [comment]
Fine. That would be helpful.

**Comment by bcs2002** [comment]
HTTP_PROXY and HTTPS_PROXY have been set and  I am also able to run wget from command prompt. But the issue with timeout still there.
What modification should i make now?

**Comment by ericmj** [comment]
Can you show how they are set?

**Comment by bcs2002** [comment]
env variables on my PC set up as 

 HTTP_PROXY   http://<ip>:<port> and
 HTTPS_PROXY https://<ip>:<port>

Now if i wget  https://s3.amazonaws.com/s3.hex.pm/installs/list.csv, I get the error:

D:\test>wget https://s3.amazonaws.com/s3.hex.pm/installs/list.csv
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2015-07-15 13:43:09--  https://s3.amazonaws.com/s3.hex.pm/installs/list.csv
Connecting to 34.162.64.152:4329... connected.
ERROR: cannot verify s3.amazonaws.com's certificate, issued by `/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=Terms of use at https://www.verisign.com/rpa
(c)10/CN=VeriSign Class 3 Secure Server CA - G3':
  Unable to locally verify the issuer's authority.
To connect to s3.amazonaws.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.

**Comment by bcs2002** [comment]
HTTP_PROXY as http://<ip>:<port> and
HTTPS_PROXY as https://<ip>:<port>

If i wget the URL , i get the error:

D:\test>wget https://s3.amazonaws.com/s3.hex.pm/installs/list.csv
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2015-07-15 13:43:09--  https://s3.amazonaws.com/s3.hex.pm/installs/list.csv
Connecting to xx.yy.xx.xx:999... connected.
ERROR: cannot verify s3.amazonaws.com's certificate, issued by `/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=Terms of use at https://www.verisign.com/rpa
(c)10/CN=VeriSign Class 3 Secure Server CA - G3':
  Unable to locally verify the issuer's authority.
To connect to s3.amazonaws.com insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.

**Comment by ericmj** [comment]
Your wget installation has an outdated or bar certificate store. Try using curl or downloading with your browser.

**Comment by bcs2002** [comment]
As you know the problem is, i am unable to install hex. Could this certificate issue be the cause of 'timeout' when installing hex?

**Comment by ericmj** [comment]
No, the timeout is another issue. But it's hard to know what's wrong without more information and how your particular proxy is set up. Can you show your environment variables are set in more detail? You can change private information to something else but please show the full string.

**Comment by bcs2002** [comment]
Is this what you want?
![envvar](https://cloud.githubusercontent.com/assets/11626401/8696373/61a107d0-2b09-11e5-9b9a-4af21feb34a4.PNG)

**Comment by ericmj** [comment]
That does look correct and something we should support but I cannot investigate this issue without your full proxy set up. If you want to investigate yourself the relevant code is here: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/utils.ex#L420

**Comment by bcs2002** [comment]
I am now no longer behind the proxy.
![errorinst](https://cloud.githubusercontent.com/assets/11626401/8720588/382bc94e-2bd1-11e5-82de-4f155d5b3e9b.PNG)

Upon giving mix local.hex  , it asks for confirmation to install hex.ez and on giving 'Y'  there is no response - just sort of hangs. Now if you terminate the batch job with "Y'  the User\bcs\.mix\archives folder is empty  else there is a hex.ez file in the folder.  Wonder if it's got something to do with the file extension .ez  - perhaps windows unable to read the file?

wget the URL and you still get the certificate issue.

**Comment by ericmj** [comment]
Does it always hang? Can you try running `powershell -Command "& {$ErrorActionPreference = 'Stop'; $client = new-object System.Net.WebClient; $client.DownloadFile("https://s3.amazonaws.com/s3.hex.pm/installs/hex.ez", "hex.ez")}"`?

`wget` fails because your installation of it has non-existant, bad or out-of-date CA certificate store. We can be pretty confident that amazon serves a correct certificate.
