### ISSUE TITLE
Allow to specify application type in mix.exs

### ISSUE THREAD

**Issue by bharendt** [elixir-lang/elixir#3469]
In embedded mode, it is sometimes required to start __applications__ with other __start types__ than `:permanent` but with type `:transient` or `temporary`. [See: application.ex](https://github.com/elixir-lang/elixir/blob/87003c16c535eec033362e316c98d580afd959af/lib/elixir/lib/application.ex#L238-L247)

In `:permanent` and `:transient` mode, all applications and the __whole node is terminated, if one of the applications termianted__ with a different reason than `normal`.

This is sometimes not wanted behaviour in __production systems__, if just an __uncritical application__, e.g a monitoring or logging application __crashed__.

Would be nice, if the application start type could be specified in the `applications` section of the `mix.exs` file, similar to the [reltool specification `rel_app()`](http://erlang.org/doc/man/reltool.html). E.g like this:

	  def application, do: [
	    applications: [
	      {:mixpanel, :temporary}, 
	      ...
	      :cowboy
	    ],
	    mod: ...,
	  ]

**Comment by josevalim** [comment]
You should be using releases for this. The application callback you have mentioned is for generating the `.app` file which does not include the start type. Please take a look at: https://github.com/bitwalker/exrm

One day we will have releases in Elixir per-se but don't hold your breath. :)
