### ISSUE TITLE
Add convenience method to get given capture group from regex + string

### ISSUE THREAD

**Issue by henrik** [elixir-lang/elixir#3470]
I do this kind of thing a lot in Ruby:

``` ruby
"foo bar"[/b(.)r/]  # => "bar"
"foo bar"[/b(.)r/, 0]  # => "bar"
"foo bar"[/b(.)r/, 1]  # => "a"
```

The best I could come up with in Elixir was:

``` elixir
Regex.run(~r/b(.)r/, "foo bar") |> Enum.at(1)
```

I think a convenience function could be useful here: one that takes the string as a first argument for piping, that takes the capture number as an argument, and that handles non-matches gracefully.

I sketched one below. Happy to make a proper PR with tests if this gets an {:ok}.

Not at all sure about the name – please do suggest others.

``` elixir
defmodule MyString do
  def capture(string, regex, num) do
    case Regex.run(regex, string) do
      nil -> nil
      list -> Enum.at(list, num)
    end
  end

  def capture(string, regex), do: capture(string, regex, 0)
end

IO.inspect "foo bar" |> MyString.capture(~r/b(.)r/)
IO.inspect "foo bar" |> MyString.capture(~r/b(.)r/, 0)
IO.inspect "foo bar" |> MyString.capture(~r/b(.)r/, 1)
```

**Comment by bitwalker** [comment]
Why not use `Regex.named_captures`?

```elixir
Regex.named_captures(~r/b(?:<foobar>.)r/, "foo bar")
#=> %{foobar: "foo bar"}
```

**Comment by henrik** [comment]
@bitwalker I actually looked at that one, and all the other documented `Regex` methods, but none of them have the convenience that I would like. Compare:

``` elixir
Regex.run(~r/b(.)r/, "foo bar") |> Enum.at(1)  # => "a"

%{"x" => x} = Regex.named_captures(~r/b(?<x>.)r/, "foo bar"); x  # => "a"

"foo bar" |> String.capture(~r/b(.)r/, 1)  # => "a"
```

**Comment by bitwalker** [comment]
@henrik The equivalent would be:

```elixir
# Single line version
Regex.named_captures(~r/b(?<x>.)r/, "foo bar") || %{} |> Map.get("x", nil)

# More idiomatic
case Regex.named_captures(~r/b(?<x>.)r/, "foo bar") do
  %{"x": x} -> x
  _  -> nil
end
```

And it has the benefit of explicitly defining what the captures mean for future maintenance/readability. Just seems like there is no particular benefit to a `String.capture/2` helper.

**Comment by lexmag** [comment]
> Just seems like there is no particular benefit to a String.capture/2 helper.

@bitwalker :+1:.

**Comment by henrik** [comment]
This is only intended to be a convenience method. That's the benefit :) Slicing-and-dicing text in this way is pretty common for me – I would guess for many. I feel this would make that rather more convenient.

If some common task feels like much more effort in Elixir than in some other language, and it's due to differences in the standard library rather than philosophical differences, that makes me want to add those things to Elixir.

But maybe there is a philosophical difference here – I'm still very much seeing Elixir through Ruby eyeglasses. Ruby is a lot about reducing boilerplate, to me. Perhaps Elixir puts other values higher.

**Comment by henrik** [comment]
Oh, and I agree named captures and so on can be the readable, maintainable thing in other, more complex situations. I intend this as a convenience e.g. for those oneliners where that would just be overkill.

I needed to parse a number out of a string today, for example. I would have liked to be able to do this:

``` elixir
string |> String.capture(~r/\d+/)
```

**Comment by alxndr** [comment]
I really like having to be explicit about what you want out of a regex match by surrounding it with capturing parentheses; that Ruby and JS return the string which matched the entire regex can lead to (imho) regexes which are more confusing than they need to be.

**Comment by josevalim** [comment]
Let's please have those discussions in the elixir-lang-core mailing list. It exists exactly for this. :)

**Comment by bitwalker** [comment]
@henrix I think the primary philosophical difference when it comes to the Elixir vs Ruby standard library is that Elixir gives you a lot of convenience, while attempting to reduce the overall API surface. In other words, in general you won't find very much, if any, crossover in functionality between functions in the API. In your case, you have the combination of `String.split`, i.e. `[_, num, _] = String.split("abc1233asdlkja@#$", ~r/\D+/, parts: 3)`, or `Regex.named_captures` to extract parts of a string based on a regular expression. If the standard library doesn't offer all of the convenience you want, it does offer the ability to easily build those tools for your own use, i.e.:

```elixir
def capture(str, _, _) when str in [nil, ""], do nil
def capture(str, pattern, idx) when is_binary(str) and idx >= 0 do
    captures = Regex.scan(pattern, str, capture: :all_but_first) 
                      |> List.flatten 
                      |> Enum.drop(idx)
    case captures do
      nil -> nil
      []  -> nil
      [h|_] -> h
    end
end
```

**Comment by bitwalker** [comment]
Sorry @josevalim, clicked send before I saw your reply
