### ISSUE TITLE
Delete key doesn't work in iex

### ISSUE THREAD

**Issue by dwahyudi** [elixir-lang/elixir#3471]
When i 'm inside iex, pressing Delete key will not delete, instead it prints out ~

Operating System: Ubuntu Vivid

```
Erlang/OTP 18 [erts-7.0] [source-4d83b58] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 3 + ~~~~4
** (SyntaxError) iex:1: invalid token: ~4
    
iex(1)> 
```

Here i want to delete 4, but instead it gives ~

**Comment by josevalim** [comment]
Do you have the same issue in the `erl` shell?

**Comment by dwahyudi** [comment]
@josevalim  yes it also happens on erl.

I tried this as well on my remote server, Ubuntu Utopic

```
Erlang/OTP 18 [erts-7.0] [source-4d83b58] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.0  (abort with ^G)
1> 3 + ~4
1> 2 + ~~~~~~6
```

**Comment by ericmj** [comment]
If the issue also exists in erlang's shell the fix needs to happen there. You can raise the issue on erlang-bugs or erlang-questions http://erlang.org/mailman/listinfo.

**Comment by gildo** [comment]
same here

**Comment by hashd** [comment]
One can use Ctrl + D in iex instead

**Comment by epitron** [comment]
Good news! It's been fixed! https://github.com/erlang/otp/commit/2c7e387961251af59f14bca39cbf8fbbe880383e

Now we just have to wait for it to slowly make its way downstream.

**Comment by xyproto** [comment]
If erlang made a new minor release, it could potentially speed things up.

**Comment by dwahyudi** [comment]
The problem remains.

@hashd, Ctrl + D doesn't work.

**Comment by hashd** [comment]
@dwahyudi Strange, it works for me on Ubuntu 15.04, Elixir v1.1.1 in gnome-terminal.

**Comment by dm1try** [comment]
@dwahyudi +1, it will work in any xterm-based(VT100) terminal
```bash
Ctrl-k	clear all characters after the cursor
Ctrl-w	clears word before the cursor. a word is set of characters separated by spaces
Ctrl-u	Clears all characters before the cursor
Ctrl-l	clear screen
Ctrl-d	deletes characters to the right of cursor, if no characters, logs out and closes terminal
Delete	deletes characters to the right of cursor (this may vary depending on settings)
Ctrl-h or Ctrl-8 or Ctrl-Shift-/	deletes characters to the left or the cursor
Backspace	deletes characters to the left or the cursor (this may vary depending on settings)
Ctrl-7 or Ctrl-Shift--	Removes a number? of characters from the end
ALT-Backspace	Removes words, not single chars. (same as CTRL+W)
```

**Comment by hashd** [comment]
@dm1try that's insightful. Thanks!

**Comment by dwahyudi** [comment]
@dm1try yep it works, Thanks :+1: 

but i still find delete key more natural than CTRL + D :cry:

**Comment by dm1try** [comment]
> but i still find delete key more natural 

I totally agree, especially annoying that "DEL" prints "~" :disappointed:
