### ISSUE TITLE
Ensure Logger.log also includes metadata

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3472]
The issue is that today move to `Logger.log` to dynamically log based on the level and they use all the compile time metadata.

We should likely provide Logger.runtime_log that for the ones willing to do it strictly at runtime.

@lexmag and @fishcakez, thoughts?

**Comment by fishcakez** [comment]
:+1:

**Comment by lexmag** [comment]
Sounds good, can't come up with anything better than `runtime_log` for name (`notify`?).

**Comment by josevalim** [comment]
@lexmag can you please send a PR for this? Let's go with runtime_log, it is easy to rename later anyway.

@ericmj / @alco / @MSch  any ideas regarding the name?

**Comment by lexmag** [comment]
Sure, I'm on it.

**Comment by alco** [comment]
I didn't understand the issue very well. Is it about people losing the compile-time metadata when switching from a logging-macro to calling `Logger.log` directly?

**Comment by josevalim** [comment]
@alco yes, exactly. there is no way to log something using a dynamic log level and have the metadata. I have noticed this in Ecto, when I made the log level configurable, and folks complained the metadata was gone.

**Comment by alco** [comment]
If we were allowed to, I would instead rename the current log to `clog` (as in `compile-time log`) or `mlog` (`macro log` or `meta-data-imbued log`). Since we can't do that, I suggest calling the run-time logging function `blog` meaning `basic log` or `bare-bones log`.

**Comment by josevalim** [comment]
Thanks @alco. I like the `basic_log` or `raw_log` or `bare_log`, and bare means "no metadata" by default. `bare_log` then? :+1:?

**Comment by lexmag** [comment]
bare :+1:

**Comment by alco** [comment]
`naked_log`?
