### ISSUE TITLE
Enum.take/2 hang forever if Stream and float are supplied as argument.

### ISSUE THREAD

**Issue by siscia** [elixir-lang/elixir#3473]
Hi All,

I am fairly new to Elixir, however I find this little issues.

``` elixir
simo@simo:~/in_ordine_db$ iex -S mix
Erlang/OTP 17 [erts-6.4.1] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Interactive Elixir (1.0.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
v
Erlang (BEAM) emulator version 6.4.1
Compiled on Thu May 14 16:50:42 2015

nil

iex(2)> Enum.take(Stream.repeatedly(fn -> 42 end), 3.0)

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution

```

The documentation states that Enum.take/2 should take an integer as second argument, however I don't see many reason for this constrain.

I could provide an implementation + test if required.

**Comment by siscia** [comment]
Also, I believe the error is from this commit here: https://github.com/elixir-lang/elixir/commit/38a95131112dc112fb667dde134f2225932eaf7f#diff-6881431a92cd4e3ea0de82bf2338f8eaL1741

Finally, I would suggest, that if we want to keep the same behaviour we should test if the `count` argument is an integer how it was in the original implementation: https://github.com/eksperimental/elixir/commit/8806a73fbdaff543378b5a577fdcb9c1aea769a0

**Comment by josevalim** [comment]
@siscia yes, let's please change both Enum.take and Stream.take to guarantee the given argument is an integer. Can you please send a pull request?

**Comment by eksperimental** [comment]
@josevalim , I just realized today that this is the second change I made to elixir, and didn't made it to v1.0
Is there a proper way too label/tag or metiong that it needs to be backported to 1.0, or we need to submit a new PR? I totally overlooked that fact

**Comment by josevalim** [comment]
It is my fault. I was the one who should backport those. Glad to know this is fixed in master.
