### ISSUE TITLE
Makefile needs to be able to build docs from Precompile.zip Elixir

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3479]
right now it is not possible to create docs with `make docs` from precompiled elixir.
the reason is that it the current make file will try to execute the `compile` task
https://github.com/elixir-lang/elixir/blob/7fe42a73d016f706296a6537981ba58ee34df7a5/Makefile#L142-L172
and it wil fail, since source files are not available.

my proposal is to create a function that checks if `elixir/lib/elixir/lib/kernel.ex` doesn't exist, and that   `lib/elixir/ebin/Elixir.Kernel.beam` does not, and set a variables called IS_PRECOMPILED to true.

and then omit compile from the docs* tasks if IS_PRECOMPILED is true.

Im posting this as a Issue, since i tried to work on this but to no avail, so somebody with some Makefile skills hopefully can do take over.

**Comment by josevalim** [comment]
@eksperimental i disagree with this. we shouldn't even bundle the makefile in the precompiled elixir. it is precompiled, it does not have source files, nor any of the tools that are supposed to ship with sources. if you want more stuff, then please download the source. we have one source tar for each precompiled package.

**Comment by eksperimental** [comment]
@josevalim I understand your point, but it think it's worth to include it.
in that case I think we should provide the docs in a compressed format for every release, what do you think about this?

**Comment by josevalim** [comment]
We could maybe provide them as a separate package, I wouldn't include them necessarily in the precompiled ones.

**Comment by eksperimental** [comment]
@josevalim yes, definitely as a separate pacage.
zip and tar.gz format, same as for the source files?

**Comment by josevalim** [comment]
@eksperimental I will figure it out later because i have in my todo to move to readthedocs which provide docs as pdfs, html and more. :)
