### ISSUE TITLE
Non-symbolic operators are not supported in function capture syntax

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#3486]
While testing https://github.com/KronicDeth/intellij-elixir/issues/143 I found that some operators are not referenceable with `/` for function captures.

For example, `&&/2` and `&&&/2` both quote `:ok` as `{:/, [line: 1], [{:&&, [line: 1], nil}, 2]}` and `{:/, [line: 1], [{:&&&, [line: 1], nil}, 2]}`, respectively, but `and/2` returns `{:error, {1, "syntax error before: ", "'and'"}}` from `Code.string_to_quoted/2`.   A similar issue occurs with `||` and `|||` vs `or`.

For [unary operators](https://github.com/elixir-lang/elixir/blob/87796e1f166d0dd47d8f66a400e759f112fbf58c/lib/elixir/src/elixir_parser.yrl#L70), `+`, `-`, `!`, and `~~~` work with `/`.  `^` does not, but since it's a special form and therefore not meant for overriding that makes sense.  That leaves `not` as the only unary, non-special form operator that can't be referenced for capture.

 `in` also does not work with `/`, but since it's only operator in its group I can't make an argument from group consistency.

Now, it does appear that the operators that cannot be referenced with `/` for function captures are all non-symbolic and look like identifiers, so it could be argued that the behavior is consistent with not allowing functions named after the anonymous function and block keywords (`after`, `catch`, `do`, `else`, `end`, `fn`), but on the other hand, the other, symbolic forms of [`and_op`](https://github.com/elixir-lang/elixir/blob/87796e1f166d0dd47d8f66a400e759f112fbf58c/lib/elixir/src/elixir_parser.yrl#L61) and [`or_op`](https://github.com/elixir-lang/elixir/blob/87796e1f166d0dd47d8f66a400e759f112fbf58c/lib/elixir/src/elixir_parser.yrl#L60) while for `not`, the work-around requires know that `not` is just `:erlang.not/1`.

**Comment by bitwalker** [comment]
You can reference `and/2` with `&Kernel.and/2`, likewise with `^`, `not`, `||`, `|||`, `or`, and `in`. Not that this changes the core of your question, but maybe something you weren't aware of.

**Comment by josevalim** [comment]
Another great find @KronicDeth. This should definitely work. It is a flaw in the parser/tokenizer, we forgot those because they are defined elsewhere. We should fix:

    not, and, or, when, in, ^

Anything else?

**Comment by KronicDeth** [comment]
I missed `when`, should that be fixed?

**Comment by KronicDeth** [comment]
The only other operator I can think of would be `=>`, but that doesn't actually form a 3-tuple in the AST, so I don't think it can really support `=>/2`.  (What's the terminology for the `{atom, metadata, args}` AST element?  I've been calling it a [local call in my java code](https://github.com/KronicDeth/intellij-elixir/blob/35b031d39fa6869d47ece2442b6b3f94d627238b/src/org/elixir_lang/Macro.java#L92-L119).)

**Comment by josevalim** [comment]
@KronicDeth i think we should support `when/2` because the tokenizer/parser should have no semantic knowledge (theoretically). So if it happens that according to elixir semantics `&when/2` makes no sense, that should be addressed later.

However, no need to support `=>` because it is not really an operator (although it is in the operator table for precedence reasons).

**Comment by jisaacstone** [comment]
I'm taking a look at this.
Tokenizer looks good: 
```Erlang
> elixir_tokenizer:tokenize("&and/2", 0, []).
{ok,0,7,
    [{capture_op,{0,1,2},'&'},
     {and_op,{0,2,5},'and'},
     {mult_op,{0,5,6},'/'},
     {number,{0,6,7},2}]}
```
So I guess I'll look at the parser. May have to learn yecc first ;)

**Comment by josevalim** [comment]
Great @jisaacstone! Actually, I think it is a bug in the tokenizer. Check this out:

```iex
iex> :elixir_tokenizer.tokenize('&+/2', 0, [])
{:ok, 0, 5,
 [{:capture_op, {0, 1, 2}, :&}, {:identifier, {0, 2, 3}, :+},
  {:mult_op, {0, 3, 4}, :/}, {:number, {0, 4, 5}, 2}]}
```

Notice how we tag `+` as an identifier in this case. We should probably do the same for `and`.
