### ISSUE TITLE
variable names: `count` vs. `n` vs. `nth` / `position` vs. `index`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3487]
_I don't know if this is the right place, please let me know and I will move it to the mailing list_

I noticed that these three variable names `count`, `n` and `nth` and used and mixed up.
for example

[Enum](http://elixir-lang.org/docs/master/elixir/Enum.html#take/2)
----------
> **take(collection, n)**  Takes the first count items from the collection
> 
> **take_every(collection, nth)**  Returns a collection of every nth item in the collection, starting with the first element

[Stream](http://elixir-lang.org/docs/master/elixir/Stream.html#take/2)
----------
> **take(enum, n)**  Lazily takes the next n items from the enumerable and stops enumeration
>
> **take_every(enum, n)**  Creates a stream that takes every n item from the enumerable

In the Enum.take/2 "n" is the name of the variable, but that's a mistake in the code, it should read **take(collection, count)**, which makes it really a mess because in one group of functions with are dealing with three different names: count, n, and nth,
and they have different names from Module to Module.

I would get rid of `nth`since it's only used as a variable name  in Enum, and it can be easily replaced by `n`
(just for the record, the is a function called `History.nth/2`)

the question when to use `count` and when to use `n`, or if we should stick to one of them.

----
A similar issue raises with the use of `position`  and `index`.

[List](http://elixir-lang.org/docs/master/elixir/List.html)
---
> **insert_at(list, index, value)**  Returns a list with value inserted at the specified index. Note that index is capped at the list length. Negative indices indicate an offset from the end of the list
>
> **keydelete(list, key, position)** Receives a list of tuples and deletes the first tuple where the item at position matches the given key. Returns the new list

all List.key* functions use `position` as a variable name, and  the rest of the function use `index`.
Is there any difference in both concepts?

I would personally use `position` when dealing with indexes starting from 1, and `index` when dealing with zero-based indexes

**Comment by josevalim** [comment]
In the List case, they mean different things. Position is the position in the tuple to find the given key, while index is the same that we mention in enumerables. So I would keep `position` the same.

About `index`, `count`, `n` and `nth`, there are two concepts. Sometimes we are referencing a position (take every 3rd item), sometimes it is a count (take 3 items). `index` can cause confusion as people would think they are indexed for purposes of fast access.

So `nth` should stay, it is just a matter or normalizing `n` and `count`. `count` is more explicit. Thoughts?

**Comment by eksperimental** [comment]
here is another case to exemplify that `n` and `index` also mix.
> **List.at(collection, n, default \\\\ nil)**  Finds the element at the given index (zero-based). Returns default if index is out of bounds. Note this operation takes linear time. In order to access the element at index n, it will need to traverse n previous elements.

**Comment by eksperimental** [comment]
it looks to me that it would be convenient to when `n` means position, use `index` instead.
and when `n` means amount, use `count`,
to avoid ambiguity and normalize the use of variable names.

Is there any use of 1-based indexes? in that case I would favour the use of `position`, since when we think of positions, we think of 1st position as the first one, and there is not such a thing as "0th position"

**Comment by josevalim** [comment]
I don't like indexes. It definitely won't work with Enumerable. If we are traversing a file, does it really make sense to think about indexes? Not a fan. :S Other than that, if `n` means amount, surely, let's use `count`.

**Comment by eksperimental** [comment]
agreed
So when `n` means index, does it make sense to use `index` instead?

**Comment by josevalim** [comment]
No, because, it doesn't make sense to think in terms of indexes when traversing files and other things.

**Comment by eksperimental** [comment]
Sorry, I didn't explain myself clearly. I meant, when it explicitly means an index, as in the examples above "Enum.fetch!(collection, n) Finds the element at the given index (zero-based)"

to sum up, the examples listed above would read like:
> **Enum.take(collection, count)**  Takes the first `count` items from the `collection`
> 
> **Enum.take_every(collection, nth)**  Returns a collection of every `nth` item in the `collection`, starting with the first element
> 
> **Stream.take(enum, count)**  Lazily takes the next `count` items from the enumerable and stops enumeration
>
> **Stream.take_every(enum, nth)**  Creates a stream that takes every `nth` item from the enumerable
> 
> **List.insert_at(list, index, value)**  Returns a list with value inserted at the specified `index`. Note that `index` is capped at the list length. Negative indices indicate an offset from the end of the list
>
> **List.keydelete(list, key, position)** Receives a list of tuples and deletes the first tuple where the item at position matches the given key. Returns the new list
>
> **List.at(collection, index, default \\\\ nil)**  Finds the element at the given zero-based `index`. Returns default if `index` is out of bounds. Note this operation takes linear time.
> 
> **Enum.fetch!(collection, index)** Finds the element at the given index (zero-based)

**Comment by josevalim** [comment]
Sounds great. :+1:
