### ISSUE TITLE
Problem with `mix deps.get` when there are private repositories

### ISSUE THREAD

**Issue by Urielable** [elixir-lang/elixir#3495]
I have the next error message:
```
error: The requested URL returned error: 403 Forbidden while accessing https://github.com/group/private_repo.git/info/refs

fatal: HTTP request failed
** (Mix) Command `git clone --no-checkout --progress "https://github.com/group/private_repo.git" "/home/vagrant/apps/private_repo/deps/private_repo_2"` failed
```
A partial solution is to clone the repository via ssh, but I find the same problem in another dependency.

This problem happens on CentOS release 6.6, with Elixir version 1.0.5 and Git version 1.7.1

In OSx works.

**Comment by ericmj** [comment]
We clone with `git`, you need to either set up git correctly or give URLs that have the proper authentication. Basically, if you can clone it with git you should be able to use it as dependency in mix.

**Comment by josevalim** [comment]
It may also be a SSH issue. Note that, if the repo is private, you should
not use https but ratheR the git@github.com URL.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Urielable** [comment]
I think the same about the ssh issue... I'll change my urls from https to ssh. Thanks!

**Comment by Urielable** [comment]
Well, I changed all the urls in mix.exs to ssh (git@github.com) instead of https, and now the download seems to be working, but this is what I get when running `deps.get`.

```
* Updating foo (git://github.com/user/foo.git)
* Updating private_bar (git@github.com:group/private_bar.git)
Running dependency resolution
```
I don't know what's happening.

**Comment by ericmj** [comment]
You need to tell us what in the output you expect to be different? Does it freeze? What happens?

**Comment by Urielable** [comment]
Yes, it hangs up forever. :confused:

**Comment by ericmj** [comment]
Do you have a way for us to reproduce? Can you confirm that it only happens with ssh git dependencies?

**Comment by Urielable** [comment]
Hey, sorry for the delay. It works now. I had to reboot the server... -_-

I'm closing this issue. Thanks.
