### ISSUE TITLE
Deprecation related issues

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3500]
1. `CHANGELOG` doesn't mention anything about `String.contains?/1` when `string` is empty.

2. Should we add to the functions that we are already emitting a warning (hard deprecated), the comment: `# TODO: Remove by [version number]`

3. None of the three String functions that have been deprecated mention anything about it's use in the documentation. I think we should document about it, so we discourage people from using it, and warn about the warning.

4. `Access` module's been deprecated, should we add also add a `# TODO: Remove by [version number]` stating what version, of it unsure what version, isn't it better to use `# TODO: Remove in a future version`, if there are plans to remove it.

cheers

**Comment by josevalim** [comment]
No need to worry about adding TODOs to deprecated stuff, I manually look for "depreca" after a release. Also, the Access deprecation is still in progress and there is an open issue for it, so no need to worry about it for now.

Improving the docs is very welcome, PR please? I will update the CHANGELOG soon too. Thank you!

**Comment by eksperimental** [comment]
great, I will update the docs for the deprecated uses for the functions the String module

**Comment by josevalim** [comment]
Those should be fixed. Please send a PR if I missing something
