### ISSUE TITLE
Logger metadata behavior

### ISSUE THREAD

**Issue by MSch** [elixir-lang/elixir#3502]
Various things I'm not sure are intentional:

```
iex(1)> Logger.configure(metadata: [:a])
:ok
iex(2)> Logger.configure_backend(:console, metadata: [:a])
:ok
iex(3)> Logger.metadata(a: 1)
:ok
iex(4)> Logger.metadata(a: nil)
:ok
iex(5)> Logger.info "a", a: 2
:ok
iex(6)> 
13:47:02.913 a=2 a= [info]  a
```

1. There's no API to remove a metadata key from the pdict. Setting it to nil doesn't remove it.
2. If a log call sends along some metadata this is appended to the metadata and doesn't replace that metadata key in the pdict
3. There's no way to send a log message without attaching the pdict's metadata (e.g. `Logger.info "a", [custom: :metadata], process_metadata: false`)
4. The backends print the metadata in the order it is in the keyword list, not the order it's defined in the `:metadata` key of the backend's configuration.

**Comment by josevalim** [comment]
> There's no API to remove a metadata key from the pdict. Setting it to nil doesn't remove it.

Should we have an explicit API or set it to nil?

> If a log call sends along some metadata this is appended to the metadata and doesn't replace that metadata key in the pdict

It is fine to merge them.

> There's no way to send a log message without attaching the pdict's metadata (e.g. Logger.info "a", [custom: :metadata], process_metadata: false)

Yes but I am not particularly inclined to support this though.

> The backends print the metadata in the order it is in the keyword list, not the order it's defined in the :metadata key of the backend's configuration.

Let's address this too.

**Comment by MSch** [comment]
> Should we have an explicit API or set it to nil?
I haven't yet needed nil metadata values. IMO if I ever do I can just go straight to the pdict and set it there.

> It is fine to merge them.
+1

> Yes but I am not particularly inclined to support this though.
Ok by me, right now we got only a single place where I want that, I can just directly call Logger there

> Let's address this too.
+1

**Comment by josevalim** [comment]
Ok, so let's remove metadata on nil values too.

**Comment by lexmag** [comment]
Hey @MSch, I'd like to give it a shot if you are not planning to.

**Comment by MSch** [comment]
@lexmag sure, go ahead!
