### ISSUE TITLE
If bad heredocs is followed by working heredocs, no error is outputed but function is not compiled

### ISSUE THREAD

**Issue by dersturm** [elixir-lang/elixir#3503]
```elixir
defmodule Foo do
  @spec bar(char_list) :: term
  @doc """
  Inspect an variable that happens to be a string"""
  def bar(my_string) when is_bitstring(my_string), do: IO.inspect(my_string)
end
```
Outputs
```
== Compilation error on file lib/foo.ex ==
** (TokenMissingError) lib/foo.ex:6: missing terminator: """ (for heredoc starting at line 3)
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

While
```elixir
defmodule Foo do
  @spec bar(char_list) :: term
  @doc """
  Inspect an variable that happens to be a string"""
  def bar(my_string) when is_bitstring(my_string), do: IO.inspect(my_string)

  @doc """
  """
  def baz(), do: :ok
end
```

Outputs
```
== Compilation error on file lib/foo.ex ==
** (CompileError) lib/foo.ex:2: spec for undefined function bar/1
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

Notes: Only happens if the function whose `@doc` is followed later by a function with a heredoc (even if it is not the imediate following function). So, if the function with a problematic heredoc is followed by functions with `@doc false`, the problem doesn't happens
Note2: If the function with problematic heredocs is not preceded by a `@spec`, no error is outputed but you can't use it. ie:
```elixir
defmodule Foo do
  @doc """
  Inspect an variable that happens to be a string"""
  def bar(my_string) when is_bitstring(my_string), do: IO.inspect(my_string)

  @doc """
  """
  def baz(), do: :ok
end
```

Outputs no error but then
```
iex(1)> Foo.bar("The truth")
** (UndefinedFunctionError) undefined function: Foo.bar/1
    (helix) Foo.bar("The truth")
```

**Comment by dersturm** [comment]
Edited the title to make it more obvious that the reason for the `@spec` error is that the function is not compiled, the compiler doesn't fails and no error is outputed on this specific case

**Comment by ericmj** [comment]
This is not a bug. In the following example:

```elixir
defmodule Foo do
  @doc """
  Inspect an variable that happens to be a string"""
  def bar(my_string) when is_bitstring(my_string), do: IO.inspect(my_string)

  @doc """
  """
  def baz(), do: :ok
end
```

The docstring contains:
```
Inspect an variable that happens to be a string"""
def bar(my_string) when is_bitstring(my_string), do: IO.inspect(my_string)

@doc """
```

You can see that if you quote the code:

```elixir
{:defmodule, [context: Elixir, import: Kernel],
 [{:__aliases__, [alias: false], [:Foo]},
  [do: {:__block__, [],
    [{:@, [context: Elixir, import: Kernel],
      [{:doc, [],
        ["Inspect an variable that happens to be a string\"\"\"\ndef bar(my_string) when is_bitstring(my_string), do: IO.inspect(my_string)\n\n@doc \"\"\"\n"]}]},
     {:def, [context: Elixir, import: Kernel],
      [{:baz, [context: Elixir], []}, [do: :ok]]}]}]]}
```

The bug is actually in the syntax highlighters in your editor and on github.

**Comment by josevalim** [comment]
I think we agreed to make `"""` always close exactly because of errors like this?

**Comment by dersturm** [comment]
Hi, @ericmj . That actually makes a lot of sense but seems a bit counterintuitive that if i use the `"""` in the same line as any text character it is escaped automatically. I tought it would simply work as a block (or issue an warning like the `missing terminator """`) while i would have to manually escape it if i wanted to put those quotes inside my docstring.

Any way, thank you

**Comment by jisaacstone** [comment]
To confirm: we are in favor of removing all newline restrictions for heredocs? So for example

    s = """silly"""

would be silly, but also valid?

**Comment by jisaacstone** [comment]
Another question: do we want to append a newline so that

```elixir
'''
foo''' == '''
foo
'''
```
?

**Comment by josevalim** [comment]
Yes exactly. The new line behaviour should still be the same though.

**Comment by josevalim** [comment]
Ah, just now I realize we have a new line inconsistency. The leading `"""` ignores the new line. The trailing one keeps it.

I am thinking then that, instead of allowing `"""` anywhere, we should just raise when we find a `"""` it is not in a new line on its own. Something like:

    Invalid heredoc terminator in the middle of line. Please escape it or move it to its own line. Syntax error at: """

Thoughts?

**Comment by lexmag** [comment]
:+1: for raising on """ in the middle.

**Comment by eksperimental** [comment]
:+1: :heart:

**Comment by jisaacstone** [comment]
Right, I've thought about and I also agree. Heredocs' distinguishing characteristic is the white space trimming. And the terminator serves to show how much white space to trim. So better to keep it on it's own line for both readability and maintainability.
