### ISSUE TITLE
Bitwise: all are operators, but some are more operators than others

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3506]
working on https://github.com/elixir-lang/elixir/pull/3505 and https://github.com/elixir-lang/elixir-lang.github.com/pull/572
made me realize that since Boolean opertors are `and`, `or` and `not`, 
what gives in the Bitwise module the status of operators to some macros, and not to others. I am referring in particular to the options when calling `use`, 
https://github.com/elixir-lang/elixir/blob/d235533b45ce4d8fb8ba1c1c35cd9377e49929f1/lib/elixir/lib/bitwise.ex#L36-L43

**Comment by alexrp** [comment]
Sorry, can you elaborate? I am not sure what the issue is.

**Comment by eksperimental** [comment]
I am (from what I understand) is that all of them are operators,

```
    * `:only_operators` - include only operators
    * `:skip_operators` - skip operators
```

I think what this function is referring to are symbols.
sorry, I cannot think of a better term.

**Comment by ericmj** [comment]
Which symbols that are not operators are you referring to?

**Comment by josevalim** [comment]
When we mention operators, we say so because they are unary (UNARY value) or binary (value BINARY value). If they are not an operator, then we refer to them directly as functions.

**Comment by eksperimental** [comment]
@ericmj the symbols that I was referring to was what the docs for this functions refers to as operators.

yes, what I assumed was that the use of the macros was not like the boolean operators, `true and false` but as functions, band(1, 1)

sorry about that

**Comment by ericmj** [comment]
Those are used as functions. Not sure which docs you are referring to but when the docs for `use Bitwise` talk about operators it's these: `~~~, &&&, |||, ^^^, <<<, >>>`.

**Comment by josevalim** [comment]
No problem! :D
