### ISSUE TITLE
Trapping GenServer exits in ExUnit tests

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#3507]
I'm not sure if this a bug or if I'm doing something wrong. Assume the following GenServer:

```elixir
defmodule Foo do
  use GenServer

  def handle_call(_, _, _) do
    raise "foo"
  end
end
```

Say I want to trap exits from this genserver. In IEX, it works fine:

```iex
iex> Process.flag :trap_exit, true
iex> {:ok, pid} = GenServer.start_link Foo, nil
iex> GenServer.call(pid, :whatever)
** logs a bunch of stuff but doesn't crash IEx
iex> flush()
{:EXIT, ...}
```

If I do this in an ExUnit test though, the test crashes:

```elixir
defmodule FooTest do
  use ExUnit.Case

  test "foo shouldn't crash" do
    Process.flag :trap_exit, true
    {:ok, pid} = GenServer.start_link Foo, nil
    GenServer.call(pid, :whatever)

    assert_receive {:EXIT, _, _} # crashes before arriving here
  end
end
```

What do you think? Also, I made a small Mix project that shows this behaviour ([here](https://github.com/whatyouhide/trapping_exits)), if you want you can clone it and run `mix test` to see it fail, then `iex -S mix` with the commands above to see exits are trapped indeed.

**Comment by ericmj** [comment]
It's not a bug. If the process exits during a `GenServer.call` the call will raise [1]. You can try wrapping the call in `catch_exit/1` and asserting on that.

[1] https://github.com/erlang/otp/blob/maint/lib/stdlib/src/gen.erl#L175-L176

**Comment by whatyouhide** [comment]
Hey @ericmj, thanks for the link to the source, very informative. Sorry to have cluttered the issue tracker with a non-issue :)
