### ISSUE TITLE
Enum.slice ignores floats

### ISSUE THREAD

**Issue by tyre** [elixir-lang/elixir#3509]
Consider the following code:
```elixir
list = [1,2,3,4]
new_list_length = length(list)/2
Enum.slice(list, 0, new_list_length)
```
One would expect this to return a list of half the length — `[1, 2]`— but it does not.

It returns `[1, 2, 3, 4]`, the entire original list.

This is because `length(list)/2` returns a float. `Enum.slice` should either throw an argument error or  behave consistently when passed a float, but certainly should not silently ignore it.

I'm fine with just raising, maybe with a helpful hint about either using `round` or `Float.floor |> round` or `Float.ceil |> round` depending on the behavior you'd like. Regardless, the current implementation is unexpected very surprising.

**Comment by eksperimental** [comment]
yes, the code is not checking for integers, neither for `start` nor for `count` as defined in the typspec
the same is happening for Enum.slice/2 with the ranges, that can be floats
`
