### ISSUE TITLE
Consider warning on variable shadowing on heads

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3520]
So this is not allowed:

    expr = 1
    case some_value do
      {1, expr} -> ...
    end

However, this is still allowed:

    expr = 1
    expr = 2

We need to play with this warning and see how frequently it would complain.

**Comment by lexmag** [comment]
Kinda related to #3307.

**Comment by josevalim** [comment]
Yes, maybe fixing #3307 would be enough.

**Comment by ericmj** [comment]
I am :-1:, elixir allows rebinding because it is useful, #3307 is another story because there is no reason for that code so it's very likely a mistake. We already have the special scoping rules heads that should be enough imo.
