### ISSUE TITLE
Task.Supervisor.async/4 remote process name example docs.

### ISSUE THREAD

**Issue by koudelka** [elixir-lang/elixir#3527]
The example at https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/task.ex#L92 doesn't work, it looks like the name of the remote supervisor in `async/4` needs to be passed as a module rather than an atom. (I'm guessing because module names are atoms prepended with `Elixir.`)

Happy to submit a documentation fix, if that's the right way to go. 

A fix to https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/gen_server.ex#L153 might also be in order, since you can pass a module name (and have it converted to an atom for you).

:smile:

**Comment by josevalim** [comment]
Yes, it is a silly typo, we should just get rid of the leading ":" when
calling it. PR please!

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by koudelka** [comment]
Will do.

What do you think of adding a line to the `GenServer` docs to indicate that you can pass a module name too?

**Comment by josevalim** [comment]
> What do you think of adding a line to the GenServer docs to indicate that you can pass a module name too?

I don't think we should because a module name is always an atom. So the information would be redundant. We should just make it super clear, if it is not yet, that module names are atoms. For example, the getting started guide talks about it in its first half I think.
