### ISSUE TITLE
Errors raised in the init() for GenServer are never reported

### ISSUE THREAD

**Issue by rockerBOO** [elixir-lang/elixir#3529]
I'm not sure if this is intended, but errors don't get reported to the console. They work if I call them in iex though.

Elixir 1.0.5
OTP 18
Linux Ubuntu 15.04

```elixir
defmodule Test do
  def start() do
    GenServer.start(__MODULE__, [])
  end

  def init([]) do
    raise "Throw this error"

    {:ok, []}
  end
end

Test.start()
```

Running returns no errors to console, but starting in iex returns the error.

```elixir
iex(1)> Test.start()
{:error,
 {%RuntimeError{message: "Throw this error"},
  [{Test, :init, 1, [file: '/home/rockerboo/tmp/text.ex', line: 7]},
   {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]},
   {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 239]}]}}
```

**Comment by fishcakez** [comment]
What would you like to happen? Or what did you expect to happen? This seems to be working as intended but that doesn't mean we can't improve error handling.

When a `GenServer` (or other OTP behaviour process) fails to start, the process that started it gets the returned error. That process can log, crash, both or neither. In the first example the return value could be pattern matched on and suitable action taken - much like `iex` handles the result by returning it.

An example of a process handling a start failure is a supervisor that fails to (re)start a `GenServer` will send a log message declaring that it failed to start a child but `Logger` does not report it by default. The `GenServer` process itself will also send a log message with details about the process itself and linked processes if it crashes at any point. This message is separate message to the `GenServer` terminating log message that contains state and last message and also is not reported by `Logger` by default. These extra logs messages (and progress reports) can be turned on with the following line in `config.exs` file:
```
config :logger, handle_sasl_reports: true
```
Setting the logger level to `:debug` will increase the amount of information or a higher level will decrease the amount of information.

**Comment by rockerBOO** [comment]
Thanks for the in-depth response fishcakez. I was just honestly pulling my hair out trying to figure why it was not working correctly (due to the error) and having no response to refer to. And that it was failing to start the process. Spent over 8 hours trying to debug this issue, due to no errors.

I turned on that config option, and the error came out as expected, with a bit more debug than I need. I am not sure what the best option here would be. Having errors spit out everywhere else but in init() seems like a frustrating issue to anyone who is unaware of the issues surrounding it.

**Comment by chrismccord** [comment]
We had a relevant discussion around this here https://github.com/phoenixframework/phoenix/issues/966

**Comment by ericmj** [comment]
@rockerBOO May I ask why you use `GenServer.start` instead of `GenServer.start_link`?

`init` doesn't log because it's expected that the calling process is going to handle it, either by handling the exit or by crashing itself if the exit isn't handled either by catching or trapping it.

By using `start` instead of `start_link` you say that you don't want to crash if the server crashes - you don't care what happens with it. So instead of raising the error in the caller the error is just returned. Sort of like the difference between `Dict.fetch` and `Dict..fetch!`.

**Comment by rockerBOO** [comment]
Honestly, `GenServer.start` was just an example. I use `GenServer.start_link` in my code, but didn't want to complicate the example with linking. Though, I should handle errors with starting the process better on the calling side. This would of helped to identify that it was throwing an error out on starting. 

I'm assuming this is a non-issue as concluded on that phoenixframework issue, and the solution is to handle the errors on the caller side of `start_link`

**Comment by josevalim** [comment]
The best we can do here is to improve the docs so folks use GenServer.start less and less. I will improve the docs.
