### ISSUE TITLE
Makefile: exit with error if current directory contains whitespaces

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3536]
I noticed Make cannot deal with whitespaces in the path, 

rightnow it's a wrong message the one `make` is giving

(currecnt dir is "/home/eksperimental/eli xir" notice the space in "eli xir")
 
```sh
$ make
/bin/sh: 1: /home/eksperimental/eli: not found
Makefile:67: recipe for target 'erlang' failed
make: *** [erlang] Error 127
```

I think the best we can do is check for space in the current directory `Makefile` is located,  and exit with  a message, as it's a real pain to deal with in `make` that from what I read.

**Comment by josevalim** [comment]
Yes, failing sounds ok to me.

**Comment by eksperimental** [comment]
:+1: then I will work on a solution

**Comment by c-rack** [comment]
I could reproduce this issue and found a pretty simple fix for it.
@eksperimental could you please confirm that adding the parentheses fixes the issue?

**Comment by eksperimental** [comment]
@c-rack. sorry, but nope...,  it was not about adding parethesis the issue I addressed.
white-spaces are evil when dealing with a Makefile.
if there is a white-space in the path to current location, we should abort
unless you are want to surround by parethesis everytime you use a variable with a path in it.

**Comment by josevalim** [comment]
@eksperimental is right I think. everytime we use `$(REBAR)` we would still need to wrap it in quotes, no? Anyway, we can just let it fail honestly instead of sanity checking everything. Plus, @c-rack commit wouldn't hurt anyway.

**Comment by eksperimental** [comment]
Here is the code that works,
`CURDIR_NO_SPACE := $(shell printf "$(CURDIR)" '%s' | sed -e 's@ @@g')`

and 
```
#==> Check for Valid Path 
define CHECK_WHITESPACE
	if [ "$(CURDIR)" != "$(CURDIR_NO_SPACE)" ]; then
		echo "You cannot run 'make' from a directory path contains whitespaces" 1>&2;
		exit 1;
	fi;
endef
```

the thing is, I don't know ( i don't know know if there is actually a way to do it),
to check this before any target is called,
or to attach it to every target.
