### ISSUE TITLE
`mix clean` does not clean compiled protocols

### ISSUE THREAD

**Issue by reset** [elixir-lang/elixir#3541]
I ran into an issue where my releases contained unexpected protocol files. This is because the `mix clean` task does not clean out the consolidated protocols directory. Should it? Should there instead be a task for `mix clean.protocols` much like there is for `mix deps.clean`?

**Comment by josevalim** [comment]
It should, thanks. Definitely a bug. We should also likely remove everything in there before consolidating too.

**Comment by c-rack** [comment]
PR https://github.com/elixir-lang/elixir/pull/3573 should solve this issue:

1. Add `protocols` compiler to the list of compilers to clean up by `mix`.
2. Add `clean` method to `compile.protocols` mix-task that just removes `-rf` the default directory.

Tested on Debian Linux.
