### ISSUE TITLE
`make release_zip` - confusing names shared

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3543]
It's a bit confusing the names used by `make release_zip`,.
This command will generate a precompiled version of elixir, which is named **exactly the same** as the one containing the **source files** that can be found in  https://github.com/elixir-lang/elixir/releases/

I propose to rename the command `make release_precompiled`
and to renamed the generated .zip file: `Precompiled-v{VERSION}.zip`

**Comment by josevalim** [comment]
Renaming the generated artifact sounds ok, yes. :) PR pls. :)

**Comment by c-rack** [comment]
I have implemented @eksperimental's proposal. Hope this is ok.

**Comment by eksperimental** [comment]
@c-rack thank you!
