### ISSUE TITLE
Handle messages in long running tasks

### ISSUE THREAD

**Issue by benwilson512** [elixir-lang/elixir#3545]
Given a task that's supposed to run forever like the contrived example:
```
# in supervisor
worker(Task, [LongRunner, :run, []])

defmodule LongRunner do
  def run do
    Stream.interval(1_000)
    |> Stream.each(&do_something_every_second/1)
    |> Stream.run
  end
end
```

Messages passed to the task will never be handled. This is bad, as the message box will grow in an unbounded fashion. @josevalim let me know if this captures the issue properly.

**Comment by ericmj** [comment]
What unhandled messages can be sent that wasn't meant to be sent by the application?

**Comment by benwilson512** [comment]
Per the discussion that spawned https://github.com/fishcakez/stream_runner, :system messages. Additionally, exit messages from the parent can't be used to nicely halt the stream.

**Comment by josevalim** [comment]
I have added TODOs in the source code so this won't fall through when it is time to tackle it. Thanks @benwilson512.
