### ISSUE TITLE
Raise when default value declared in second (or later) function clause

### ISSUE THREAD

**Issue by Tuxified** [elixir-lang/elixir#3546]
Hi,

I found some examples of function heads with defaults, but without a body, which was new to me. After some talk with @fishcakez on IRC, seems like I stumbled upon a bug. The compiler warns me for not having a function clause with defaults as the first clause. I think it should raise an error instead.

A small example of this case (and a [more elaborate version](https://gist.github.com/Tuxified/bf8de715bc5a1e792922) ):

```
defmodule Accountant2 do
  
  def sum([], acc), do: acc
  def sum([head | tail], acc \\ 0) do
    sum(tail, acc + head)
  end
end
# => iex:9: warning: clause with defaults should be the first clause in def sum/2

Accountant2.sum([1,2])      # => 3
Accountant2.sum([1,2], 1)   # => 4
Accountant2.sum([])         # => 0
```

**Comment by josevalim** [comment]
Elixir's goal here is to warn because an error is quite disruptive. Once we error, the compiler will stop, and all other warnings will no longer show, always requiring multiple passes. So listen to your warnings, when they are calling for you, listen to your warnings, there is nothing else you can do.

**Comment by fishcakez** [comment]
This is very inconsistent.. If the default value is declared in the last clause we warn, but if a default value is declared in the one of multiple clauses that is not the last clause we raise. This means if someone sees the warning and does what the warning says the next complie will raise.

**Comment by josevalim** [comment]
Thanks for reopening @fishcakez. If it is inconsistent, then it is definitely a bug.

**Comment by fishcakez** [comment]
For example if we add a third clause:

```elixir
defmodule Accountant2 do

  def sum([], acc), do: acc
  def sum([head | tail], acc \\ 0), do: sum(tail, acc + head)
  def sum(n, acc) when is_integer(n), do: n+acc
end
```
```
iex:4: warning: clause with defaults should be the first clause in def sum/2
** (CompileError) iex:5: def sum/2 has default values and multiple clauses, define a function head with the defaults
    (elixir) src/elixir_def.erl:323: :elixir_def.store_each/7
    (elixir) src/elixir_def.erl:87: :elixir_def.store_definition/9
```

Or if we move the default to first clause:
```elixir
defmodule Accountant2 do

  def sum([], acc \\ 0), do: acc
  def sum([head | tail], acc), do: sum(tail, acc + head)
end
```
```
** (CompileError) iex:4: def sum/2 has default values and multiple clauses, define a function head with the defaults
    (elixir) src/elixir_def.erl:323: :elixir_def.store_each/7
    (elixir) src/elixir_def.erl:87: :elixir_def.store_definition/9
```

**Comment by fishcakez** [comment]
Do we should stick to the stance in https://github.com/elixir-lang/elixir/pull/2467 or change to https://github.com/elixir-lang/elixir/issues/3546#issuecomment-126996233? I believe the #2467 stackoverflow thread is: http://stackoverflow.com/questions/22080713/elixir-default-parameters-for-named-functions-with-multiple-clauses. I am happy to stick with #2467 because @ericmj raised good points in that PR.

**Comment by fishcakez** [comment]
Just to clarify the problem right now, if a single default is declared in the last of multiple clauses we warn that the default should be in the first clause. If the default is declared in the first of multiple clauses we raise, which invalidates the warning. If the default is declared in any other clause of multiple clauses we warn and raise.

**Comment by josevalim** [comment]
Let's make everything consistent with a warning. It should be a single warning, we don't need to have different ones. We may raise later but I would still like to give the warning a try.

**Comment by fishcakez** [comment]
Fixed in https://github.com/elixir-lang/elixir/commit/030a4fec31760fd9bc744ebea7e85b6d2dfe22d6.
