### ISSUE TITLE
Autocomplete suggestions not updated by IEx.Autocomplete

### ISSUE THREAD

**Issue by DavsX** [elixir-lang/elixir#3551]
Hi.
Create a new project ```mix new mymodule``` and have a file in lib/mymodule.ex with the content:

```elixir
defmodule MyModule do
   def fun1, :do nil
end
```

jump to iex via `iex -S mix` and execute the following:
```elixir
> 'MyModule.' |> Enum.reverse |> IEx.Autocomplete.expand
{:yes, 'fun1', []}
```

So far so good. Now without exiting IEx, edit lib/mymodule.ex:
```elixir
defmodule MyModule do
   def fun1, :do nil
   def fun2, :do nil
end
```

Jump back to iex:
```elixir
> 'MyModule.' |> Enum.reverse |> IEx.Autocomplete.expand
{:yes, 'fun1', []} ## did not recompile/reload MyModule, so this is ok
> c "/tmp/mymodule/lib/mymodule.ex"
[MyModule]
> r MyModule
{:reloaded, MyModule, [MyModule]}
> 'MyModule.' |> Enum.reverse |> IEx.Autocomplete.expand
{:yes, 'fun1', []} ## fun2 is not here!
> Code.get_docs(MyModule, :docs)
[{{:fun1, 0}, 2, :def, [], nil}]
> MyModule.__info__(:functions)
[fun1: 0, fun2: 0] #this is accurate
```

As you can see, Code.get_docs did not return the new function, but MyModule.__info__(:functions) does. https://github.com/elixir-lang/elixir/blob/master/lib/iex/lib/iex/autocomplete.ex#L264 Here Code.get_docs is preferred first and if it returns a truthy value (which it does), the output of MyModule.__info__ is not used (which has the updated values).

Is this a bug, or I am using it in a wrong way? Thanks in advance!

**Comment by josevalim** [comment]
The docs are read from the bytecode so unless you update the compiled byte code in disk, they won't be updated!
