### ISSUE TITLE
master(1.1.0-dev), Code.string_to_quoted loses column info from tokenizer

### ISSUE THREAD

**Issue by jfis** [elixir-lang/elixir#3553]
column data ({Line, ColumnBegin, ColumnEnd}) from :elixir_tokenizer.tokenize does not pass through :elixir_parser.parser
if this is not intentional, i have a pr ready

**Comment by josevalim** [comment]
So far it is intentional because Erlang does not support it yet, so there is no purpose in passing it forward. We will need to change the whole compiler tool chain to handle that first.

**Comment by jfis** [comment]
ok. i thought it would be useful for tooling/editors

**Comment by josevalim** [comment]
Yes, it would, but not if it breaks the language. :) Thanks though!

**Comment by jfis** [comment]
Ok. There must be something else that I don't know of then. 
All tests were passing, btw.
