### ISSUE TITLE
Make tests skippable

### ISSUE THREAD

**Issue by NobbZ** [elixir-lang/elixir#3564]
Please provide some option to skip tests.

Currently I comment tests, which I know in advance that they will fail, because the behaviour is already specified, but far from beeing implemented or even scheduled to do so. I then uncomment then when time has come.

From other test-libraries I know “skipped tests”. They won't be run, but appear in the summary as “ignored” or “skipped”.

In rubys `rsepc` you define them like this:

```rb
it "fails" do
  skip
  expect(true).to be (false)
end
```

In Java you can do

```java
@Test
@Ignore
public void failingtest() {
  Assert.assertEqual("1", "0")
}
```

In ExUnit i'd like to see something like that:

```ex
test "fails" do
  skip
  assert true == false
end

# or

skip "fails" do
  assert true == false
end
```

When choosing the first, an optional argument to `skip` could be a reason, why this test has been skipped like in `skip "We need to fix #123 first`. Don't know if we could keep description AND reason in the second variant.

After tests have run, we the could see summary like this:

```plain
1 tests, 0 failures, 1 skipped
skipped
* fails, no reason given (file, line number)
```

**Comment by josevalim** [comment]
Do not use the issues tracker for feature requests or discussions. I believe this functionality is already available somehow, so you can ask in elixir-lang-talk, and there is elixir-lang-core for feature proposals.

**Comment by edgurgel** [comment]
@NobbZ, check this issue: https://github.com/elixir-lang/elixir/issues/1898
