### ISSUE TITLE
There is no documentation about what modifiers are valid in custom sigils

### ISSUE THREAD

**Issue by jisaacstone** [elixir-lang/elixir#3565]
Release 1.0.5 only supports lowercase `a-z`. Current master supports lower and upper case. A dev will have to look at [the tokenizer code](https://github.com/elixir-lang/elixir/blob/d235533b45ce4d8fb8ba1c1c35cd9377e49929f1/lib/elixir/src/elixir_tokenizer.erl#L651) to know that this is the limitation.

I'd like to document this behaviour, but am unsure where to place the words. There is nothing about custom sigils in the current iteration. I could place a blurb at the end the `@moduledoc` for the kernel, is that the best place?

I am aware of the bit about custom sigils in [the official tutorial](http://elixir-lang.org/getting-started/sigils.html#custom-sigils) but there ought to be a mention in the documentation as well.

**Comment by josevalim** [comment]
This is tricky because there is no place we could document them. The best place I could think is a section in the `Macro` module doc.

**Comment by eksperimental** [comment]
@josevalim I think we need the same for what are valid names for Modules and functions.

**Comment by jisaacstone** [comment]
@eksperimental good point I don't think for example the limitation of `!` & `?` only at the end is ever mentioned. Also Erlang allows some accented characters as identifiers but elixir does not.

I think maybe what is missing is a reference manual like [Erlang has] (http://erlang.org/doc/reference_manual/expressions.html). The tutorial on elixir.org should not be cluttered with all the details, but the details should exist somewhere outside the parsing code.

**Comment by josevalim** [comment]
@jisaacstone I think we could put those all in the Macro module for now. Both sigils and identifier rules. A small section about identifiers in the getting started guide would go a long way too. I will open up an issue there.

**Comment by michalmuskala** [comment]
I think a natural place to explain valid module names would be `Kernel.defmodule`, and function names `Kernel.def`

**Comment by josevalim** [comment]
That's a good idea for the identifiers. :+1: @michalmuskala
