### ISSUE TITLE
Typespec error not showing line number

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3572]
```elixir
defmodule Hi do  
  defmodule User, do: defstruct name: "eksperimental"

  @spec hello(list) :: %Struct{Keyword}
  def hello(list), do: struct(%User{}, list)
end
```
would throw:

    == Compilation error on file lib/struct_error.ex ==
    ** (UndefinedFunctionError) undefined function: Struct.__struct__/0 (module Struct is not available)
        Struct.__struct__()
        (elixir) lib/kernel/typespec.ex:865: Kernel.Typespec.typespec/3
        (elixir) lib/kernel/typespec.ex:1075: Kernel.Typespec.fn_args/5
        (elixir) lib/kernel/typespec.ex:591: Kernel.Typespec.translate_spec/4
        (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

Changing the line to

```elixir
@spec bye(list) :: %User{Keyword}
```

would give 

    == Compilation error on file lib/struct_error.ex ==
    ** (FunctionClauseError) no function clause matching in anonymous fn/1 in Kernel.Typespec.typespec/3
        (elixir) lib/kernel/typespec.ex:874: anonymous fn({:__aliases__, [counter: 0, line: 4], [:Keyword]}) in Kernel.Typespec.typespec/3
        (stdlib) lists.erl:1337: :lists.foreach/2
        (elixir) lib/kernel/typespec.ex:874: Kernel.Typespec.typespec/3
        (elixir) lib/kernel/typespec.ex:1075: Kernel.Typespec.fn_args/5
        (elixir) lib/kernel/typespec.ex:591: Kernel.Typespec.translate_spec/4

Maybe related to: https://github.com/elixir-lang/elixir/issues/3311

**Comment by josevalim** [comment]
Fixed in master.
