### ISSUE TITLE
ExUnit's `async: true` does not appear to work as documented

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#3580]
Given:

``` elixir
defmodule AsyncTest do
  use ExUnit.Case, async: true

  test "sleep 1 seconds" do
    IO.puts "\nsleep 1 seconds start"
    :timer.sleep(1000)
    IO.puts "\nsleep 1 seconds end"
  end

  test "sleep 2 seconds" do
    IO.puts "\nsleep 2 seconds start"
    :timer.sleep(2000)
    IO.puts "\nsleep 2 seconds end"
  end
end
```

When I run `mix test test/async_test.exs`:

```
$ mix test test/async_test.exs

sleep 2 seconds start

sleep 2 seconds end

sleep 1 seconds start
.
sleep 1 seconds end
.

Finished in 3.0 seconds (0.06s on load, 3.0s on tests)
2 tests, 0 failures

Randomized with seed 538615
```

The second test is not starting until the first one finishes.  However, the docs claim that using `async: true` should cause the tests to run in parallel:

```
iex(2)> h ExUnit.Case

                                  ExUnit.Case

Sets up an ExUnit test case.

This module must be used in other modules as a way to configure and prepare
them for testing.

When used, it accepts the following options:

  • :async - configure Elixir to run that specific test case in parallel
    with others. Must be used for performance when your test cases do not
    change any global state.
```

**Comment by ericmj** [comment]
Tests are not run in parallel directly, *test cases* are though. Tests inside a test case are always run serially but whole cases can run in parallel with other cases with `async: true`.

**Comment by myronmarston** [comment]
Ah, I misunderstood the docs.  Thanks for the clarification.

Any reason not to run the tests in a single test case module in parallel?

**Comment by ericmj** [comment]
If you think the docs can be made more clear please send a PR improving them.

The reasoning is that it is simpler if all tests in a case run serially because you can worry less about accessing things like global state between tests in that case. Given enough cases and tests you will get enough parallelism to fill the CPU anyway.

We can discuss adding parallel tests but that discussion should happen on the core mailing list.
