### ISSUE TITLE
IEx h/0,1 helper should support accessing Erlang documentation

### ISSUE THREAD

**Issue by bbense** [elixir-lang/elixir#3589]
Currently the iex h helper does not support accessing erlang documentation. 

```
iex> h :crypto
:crypto is an Erlang module and, as such, it does not have Elixir-style docs
```

Since erlang functions are first class citizens in the Elixir language, Elixir
should provide a means of providing this documentation in iex , if possible. 

I have made some progress in this area as documented in these threads on the 
elixir-lang-core email list. 

https://groups.google.com/forum/#!topic/elixir-lang-core/nnyBdZ22hqk

https://groups.google.com/forum/#!topic/elixir-lang-core/hIj-cLMUDxM

There are two git repos that are being used for experimenting with these ideas. 

https://github.com/bbense/iex_h_helper

https://github.com/bbense/erlman

The problem is that there isn't a platform independent way to provide the erlang 
documentation w/o including the erlang documentation in the elixir src tree. As 
documented in the threads above, adding set of module behaviors to implement 
documentation lookup would allow this problem to be solved. 

My plan is that once I have a version of iex_h_helper that implements all the
h functions of `elixir/lib/iex/lib/introspection.ex` is to use that as a base to create a 
patch to the main elixir branch.  This would allow switching the backends behind 
the h command to include platform specific code for documentation lookups.

**Comment by bitwalker** [comment]
Nice work! I'd love to have this, I reference Erlang docs at least as often as Elixir docs, and it's always annoyed me that I can do the latter easily in iex, but not the former. :+1:

**Comment by josevalim** [comment]
@bbense definitely. I would love a pull request that makes h helper more dynamic so you can plug your own backends.

**Comment by bbense** [comment]
A first pass at the implementation is done. There are still some open questions and documentation work to be done.

**Comment by josevalim** [comment]
Perfect, thank you. I am focused on Elixir v1.1 now, I will verify this later. :)

**Comment by ph-One** [comment]
I'm new to Elixir, and this was one of the first things I did, iex> `h(:crypto)`
I rely heavily on documentation at this stage, and would love to see Erlang documentation avail to the Elixir helper. :+1:

**Comment by alco** [comment]
Could we make the warning mention a way to go about looking up Erlang docs in the meantime? It could say something like

> :crypto is an Erlang module and, as such, it does not have Elixir-style docs.
> Consider using a documentation app for quick lookup of both Erlang and Elixir docs, see http://elixir-lang.org/docs/applications.html

**Comment by bbense** [comment]
This pull request provides a framework for extending the h command to interface with any external documentation provider. 

https://github.com/elixir-lang/elixir/pull/3640

There are backends that use this capability to either parse Erlang man pages or provide appropriate documentation URL's ( or interface with Dash or Hex Docs ) at these repo's. 

https://github.com/bbense/erlman

https://github.com/bbense/doc_helpers

For at least the standard erlang libraries it would be straightforward to list the url for the function. 

iex> h :crypto.hash/2

:crypto is an Erlang module and, as such, it does not have Elixir-style docs.
Documentation can be found at http://www.erlang.org/doc/man/crypto.html#hash-2

**Comment by lpil** [comment]
:+1:

**Comment by josevalim** [comment]
@bbense thank you for your lightning talk at Erlang Factory!

If I understand the code correctly, the [erlman](https://github.com/philosophers-stone/ehelper/tree/master/lib/erlman) is all we need if we want to show Erlang documentation and it should be roughly 500 LOC. The downside is that it requires man. 

Is this a fair assessment?

**Comment by bbense** [comment]
That's a reasonable summary. I had a long talk with Joe Armstrong afterwards and he convinced that I should make another attempt at parsing the xml. Which if I understand correctly is distributed with both unix and windows Erlang installations.

**Comment by bbense** [comment]
The most up to date version of the erlman code now resides in the ehelper module. 

https://github.com/philosophers-stone/ehelper/tree/master/lib/erlman

**Comment by josevalim** [comment]
>  Which if I understand correctly is distributed with both unix and windows Erlang installations.

Ah yes, I forgot about this. The man pages are specific to Linux and the XML pages are actually not always available. For example, homebrew does not include them by default. :(

**Comment by michalmuskala** [comment]
What if the `h` helper was made extensible, and we provided additional archives for erlang docs?

With installing archives from hex, it could be as simple as `mix archive.install hex erl_docs`.

**Comment by josevalim** [comment]
@michalmuskala archives do not work for this. They don't have the ability to execute code when the VM starts. Archives are also specific to Mix, so it wouldn't work for `iex`.

**Comment by Eiji7** [comment]
@josevalim: So we should download docs if there does not exists, right?
[erldocs site](http://erldocs.com/) allows to simple download (just send GET request for static url - I mean not session based url or POST request with some data) documentation in HTML pages, so we can check erlang version and then download or scrape directly docs for that version.
What do you think about it?
I have lots of experience scraping data from sites, so let me know if I can help you.

**Comment by josevalim** [comment]
Update: we are currently working on a proposal to share a Docs chunk between all BEAM languages, allowing interoperability when it comes to the documentation. If accepted, it should allows us to access Erlang docs out of the box, with no further work. I will keep this thread posted of any progress on that front.

**Comment by OvermindDL1** [comment]
> Update: we are currently working on a proposal to share a Docs chunk between all BEAM languages, allowing interoperability when it comes to the documentation. If accepted, it should allows us to access Erlang docs out of the box, with no further work. I will keep this thread posted of any progress on that front.

And other BEAM languages too, all transparently.  :-)

**Comment by wrachwal** [comment]
@josevalim - specs in `h/1` helper are really nice. However, the removal of `s/1`, if not moved to somewhere else (I searched for a while, without luck), has one drawback though:
```elixir
Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> s :file.get_cwd
@spec get_cwd() :: {:ok, dir} | {:error, reason} when Dir: filename(), Reason: posix(), dir: var, reason: var
@spec get_cwd(drive) :: {:ok, dir} | {:error, reason} when Drive: string(), Dir: filename(), Reason: posix() | :badarg, drive: var, dir: var, reason: var
iex(2)>
```
It'd be good to have it again until `h/1` for Erlang is worked out.

**Comment by josevalim** [comment]
@wrachwal I would rather make `h :file.get_cwd` show the specs for Erlang and then say documentation for Erlang modules is not available.

**Comment by wrachwal** [comment]
@josevalim - that makes sense and the message will be clear: "spec we have today, and doc will do tomorrow"

**Comment by Awenimpagaritse** [comment]
Cool

**Comment by Awenimpagaritse** [comment]
Cool

**Comment by josevalim** [comment]
Note to self: the new chunk storage should support storing information such as ":since" and ":deprecated".

**Comment by josevalim** [comment]
A proposal for sharing documentation across languages has been sent: http://erlang.org/pipermail/eeps/2018-January/000540.html - the goal is for Elixir to support this new format and we will be able to show documentation for other languages once they adopt it too.

**Comment by untra** [comment]
@josevalim has the proposal been submitted to https://github.com/erlang/eep yet?

**Comment by josevalim** [comment]
The first step of publishing an EEP is to send it to the mailing list for discussion. :)

**Comment by michalmuskala** [comment]
It's very hard to access that EEP from the link you provided. Could you maybe post it in a gist or somewhere similar?

**Comment by josevalim** [comment]
Here we go: https://gist.github.com/josevalim/c6f8fdb4a3dc1afb769418a6b8f586fb

Note this is the initial draft. We will likely have some changes in it before it is finally published.

**Comment by josevalim** [comment]
The EEP has been published: http://erlang.org/eep/eeps/eep-0048.html

There is a PR that slightly changes the documentation format though to support translations: https://github.com/erlang/eep/pull/5/files

**Comment by josevalim** [comment]
The EEP has been updated and we will adopt it by v1.7, see #7198. Once other languages get up to date, we should all live happily ever after. Closing this.
