### ISSUE TITLE
Enable users to specify an option in `mix.exs` that causes the compiler to not allow build warnings.

### ISSUE THREAD

**Issue by lpil** [elixir-lang/elixir#3591]
I want to avoid compiler warnings on my project, and as a result I want build warnings to always be treated as errors, causing the build to fail.

Currently I'm getting something like this by explicitly compiling with this flag on CI, as can be seen here.

https://github.com/lpil/dogma/commit/1d836594eff40379ff4a2eabb87ac56a893a3cfe

In an ideal world I would specify something in `mix.exs`, and when a compiler warning occurs it'll be printed in nice big scary red text, and the build/test run/anything would halt, returning a non-zero status.

Thanks,
Louis

**Comment by ericmj** [comment]
I am :-1: on this because it would mean that when your project is used as a dependency it will also treat warnings as errors which is a very bad thing. Your project will break for users when it doesn't have to.

**Comment by josevalim** [comment]
Just do `mix compile  --warnings-as-errors` in your build tool. Also, please, don't use the issues tracker for feature requests. They should go through elixir-lang-core.

**Comment by lpil** [comment]
Oops, sorry for opening this in the incorrect place.

> I am :-1: on this because it would mean that when your project is used as a dependency it will also treat warnings as errors which is a very bad thing. Your project will break for users when it doesn't have to.

Makes sense. I envisioned this only applying to files in that project, but I imagine that is a lot more complex. I know nothing about compilers.
