### ISSUE TITLE
Accurate line numbers for doctest errors

### ISSUE THREAD

**Issue by jisaacstone** [elixir-lang/elixir#3592]
The problem is that stacktraces in doctests don't report the actual line number of the test. for `@moduledoc`s it is the first line of the module, for `@doc`s it is the first line of the function.

Currently the line numbers of module attributes are not stored.

Maybe the only way to fix this is to special case how @doc/@typedoc/@moduledoc are treated in the @ macro in Kernel. We could make it expand to something besides "put_attribute" that would also store the proper line or simply call Module.put_attribute passing the line AND the doc.

**Comment by jisaacstone** [comment]
OK I have figured out how do do this, but I have a question:

Will changing the stored line number affect any tools, like for example the documentation generation tool? Like will the `Source` links link to the new `@doc` line?

**Comment by josevalim** [comment]
No, it is fine. We can always fetch the function line number too if we want.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Merged, thank you!
