### ISSUE TITLE
Improve error message when no return value is specified in @spec

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3598]
```elixir
  @spec check(integer, integer)
```

gives me the following error:
```sh
** (CompileError) lib/kernel_defensure.exs:100: invalid function type specification: check(integer, integer)
```

I think it can clearly sat that a return value was not specified, same way we do when we provide an undefined type

That will help.

**Comment by eksperimental** [comment]
that was quick @antipax 
thank you guys!!!! :+1:

**Comment by antipax** [comment]
@eksperimental was just working in this code a few days ago so was no big deal!
