### ISSUE TITLE
Add more Application functions

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3603]
I am thinking at least `Application.get_key/2`, `Application.started_applications/0` (calls `:application.which_applications/0`) and `Application.loaded_applications/0`.

@fishcakez wdyt?

**Comment by fishcakez** [comment]
Sounds good to me.

**Comment by josevalim** [comment]
Gah, now I am wondering if it should only be `Application.started` and `Application.loaded`. The rationale is that we have `Process.registered` and not `Process.registered_processes`. Thoughts?

**Comment by josevalim** [comment]
Or `Application.list(:started | :loaded)`.

**Comment by josevalim** [comment]
The second is tricky because of the timeout argument though.

**Comment by fishcakez** [comment]
We also have `Code.loaded_files`

**Comment by josevalim** [comment]
Alright.

**Comment by fishcakez** [comment]
I was just trying to find some consistency :). These new function names are LONG, it would really be nice to shorten them.

**Comment by revdan** [comment]
I'm happy to go back and change them. I'd hate to be responsible for a vague sense of unease that the long function names are giving anyone :)

**Comment by josevalim** [comment]
I think `Application.loaded` and `Application.started` are honestly too short. `Process.registered` makes sense because a "registered process" is a thing of its own. We don't say "started application" as we say "registered process". Anyway, naming is tricky. :)

**Comment by revdan** [comment]
FWIW I don't think the short versions make it obvious that it's going to return a list of applications.
