### ISSUE TITLE
Cannot compile keyword list with `|`

### ISSUE THREAD

**Issue by mgwidmann** [elixir-lang/elixir#3608]
Elixir allows the following for example:

```
[1 | [] ] = [1]
```

Which works fine. However, when the `|` is used with a keyword list, it fails to compile.

```
[a: :b | [] ] = [a: :b]
** (CompileError) iex:1: undefined function |/2
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

```
[a: :b | []]
** (CompileError) iex:2: undefined function |/2
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

Using the full syntax works fine (and is the only workaround):

```
[{:a, :b} | []] = [a: :b]
[a: :b]
```

Unsure if this is intended or not. If this is intentionally not allowed, the error message should at least be improved as its unclear what the user has done wrong and why the code won't compile.

Thanks to @svarlet in slack for pointing this out

**Comment by josevalim** [comment]
There is nothing we can do about this. The workaround is to do this:

    [a: :b] ++ list

is semantically the same as the other constructs you have mentioned.
