### ISSUE TITLE
warning: this clause cannot match because a previous clause...

### ISSUE THREAD

**Issue by fazibear** [elixir-lang/elixir#3612]
I'll get an warning, but code works ok. Without default parameters warning is gone.

```
> elixir test.ex                                                                                                                                                               
test.ex:17: warning: this clause cannot match because a previous clause at line 15 always matches
other hello hello
hello hello
```

This is sample code:

```
defmodule UseModule do
  defmacro __using__(opts) do
    quote bind_quoted: [opts: opts] do

      def hello(what, opts \\ %{}) do
        IO.puts "hello #{what}"
      end

      defoverridable [hello: 2]
    end
  end
end

defmodule OtherModule do
  use UseModule

  def hello(what, opts \\ %{}) do
    IO.puts "other hello #{what}"
    super(what, opts)
  end
end

OtherModule.hello("hello")
```

**Comment by josevalim** [comment]
That's because when you use default parameters, a function with arity `airty-1` is defined. And in this case, because you use default parameters twice, that function will be defined twice. This is a bug though. Or we need to handle default parameters differently or we need to emit a better warning.

**Comment by josevalim** [comment]
We can't fix this one. The proper fix in this case, since you are defining two functions, is to effectively mark both as overridable.

**Comment by lexmag** [comment]
> effectively mark both as overridable

And that's what we are actually doing in the stdlib: [lib/elixir/lib/dict.ex#L305](https://github.com/elixir-lang/elixir/blob/d1b785821ce28c399aa27caafd73cf5ff1cd7b7d/lib/elixir/lib/dict.ex#L305) (note `merge: 2, merge: 3`, `pop: 2, pop:3`).
