### ISSUE TITLE
Workaround to define/use struct in same context?

### ISSUE THREAD

**Issue by Hal9000** [elixir-lang/elixir#3624]
Opening this issue at José's request.
As a relative newbie, I asked this question:
https://gist.github.com/Hal9000/20819c12f1b46e8c9fff

José explained it to me, and said:

[09:15am] josevalim: hal_9000: can you please open up an issue with that gist?
[09:15am] josevalim: i just had an idea on how we can address it

**Comment by josevalim** [comment]
In order to fix this issue we would need to evaluate module definitions. I did some early benchmarks and it it too costly to be worth it in the long term.
