### ISSUE TITLE
Annoying warning about unused `import Thing, only: []`

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#3625]
I'm using Elixir 786089b7225a9f872b14a58837870fba1002885e.

With a module like this

```elixir
defmodule MyPlug do
  use Plug.Router
  import Plug.Conn, only: []

  # there's more stuff here
  # ...
end
```

I get this warning:

```
lib/plug.ex:3: warning: unused import Plug.Conn
```

The reason I do the "unimport" is because `Plug.Router` implicitly imports `Plug.Conn` and I want to cancel out that side-effect.

**Comment by josevalim** [comment]
Good catch. Definitely a bug. We should remove the warn annotation if we no longer import anything.
