### ISSUE TITLE
Exception Error Message issues

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3626]
I have come across to issues that made me spent scratch my head trying to figure out what was going on.

1) First one, the strack trace for raising an exception with invalid arguments is non-descriptive.
```elixir
raise CompileError, foo: :bar
```
will raise
```
** (CompileError) got FunctionClauseError with message `no function clause matching in IO.chardata_to_string/1` while retrieving Exception.message/1 for %CompileError{description: "compile error", file: nil, line: nil}
    test/file.exs:13: (module)
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```
which is actually coming from this line: https://github.com/elixir-lang/elixir/blob/a86607e13b42106926b2eabcb8ecbcf0a5f5ffda/lib/elixir/lib/exception.ex#L49

2) Second issue, is that I think we should have in the documentation (iex and ex_doc), information about the valid arguments for each exception module

3) Make sure all the exceptions when called with no argument, never fail and give an error like in the first issue. They should all pass by default (once agreed what we want I can submit the PR). As of now, `raise CompileError` will fail, since "file: "  argument is required.

4) I think we should by default support message in all exceptions by default

**Comment by josevalim** [comment]
1. Yes, let's check all options have been proper supplied. Can you please send a PR for CompileError and, once we agree on a solution, provide something similar to the other exceptions?

2. Yes, definitely.

3. Same as 1.

4. I don't think so. Sometimes the message should only be calculated later on. I wouldn't like to impose the field.

**Comment by eksperimental** [comment]
I will send a PR soon, just one comment,
regardless whether we fix this issue, so we don't get the error.
Shoudln't the stacktrace be more descriptive (sorry, I have no idea how the stacktrace works)

**Comment by josevalim** [comment]
Ping. Elixir v1.1 is coming this week, which means we should get this in soon before the code freeze. :)

**Comment by eksperimental** [comment]
alright. hands on then :-D

**Comment by josevalim** [comment]
Closing in favor of #3657.

@eksperimental I realized that I gave conflicting instructions regarding 3. Right now, I believe they should not pass by default but rather fail as soon as possible.

**Comment by eksperimental** [comment]
yes, no worries, i think we need to discuss in detail what we want and how we want to do it, and #3657 is a good starting point,.
I will push whatever I have anyway, just in case it can be used
