### ISSUE TITLE
missing an `end` token in a def - line number is not given.

### ISSUE THREAD

**Issue by jisaacstone** [elixir-lang/elixir#3627]
I've come across this a few times - if I forget to add `end` to a `do` block the error message complains about the _module_ missing an end block. This reminds me of the errors I got from the Borland c++ compiler back in '93. I believe we can do better~

Example:

```elixir
Defmodule DOh do
  def foo({_}) do
    :one
  def foo({_,_}) do
    :two
  end
end
```
```bash
** (TokenMissingError) d'oh.exs:10: missing terminator: end (for "do" starting at line 1)
    (elixir) lib/code.ex:363: Code.require_file/2
```

Since `def`, `defp`, `defcallback`, `defmacro` can only be defined inside a `defmodule` block we should be able to detect the exact point of divergence and relay that information to the user. like so:

```bash
** (IllegalTokenError) d'oh.exs:4: cannot define a function within a function definition.
    (elixir) lib/code.ex:363: Code.require_file/2
```

I can probably figure the solution if y'all think it is appropriate.

**Comment by josevalim** [comment]
We can't do it, unfortunately. The tokenizer has no idea about the code semantics. In fact, defmodule is just a macro which one may even remove from their escope. We cannot even assume that `def` is used to define functions.
