### ISSUE TITLE
GenServer and GenEvent are missing proper places to document callbacks

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#3630]
Not sure how the new behaviours work but can we add documentable `@callback`s?

EDIT: With the current mechanism the moduledoc is huge and bloated which makes us miss documenting things like `GenServer.init` which is only documented in `GenServer.start_link`.

**Comment by josevalim** [comment]
Yes, we can and should document them. I was planning to do this after 1.2 anyway.

**Comment by fishcakez** [comment]
Added in https://github.com/elixir-lang/elixir/commit/ad869b88349645774f97f7191d0a6c3e097274d2
