### ISSUE TITLE
Document GenServer, GenEvent callbacks more completely.

### ISSUE THREAD

**Issue by Havvy** [elixir-lang/elixir#3632]
The callbacks defined in GenServer and GenEvent currently show the shape of the functions and a tidbit of information about when they are called. It'd be useful to show more information.

* What information does that argument actually hold?
* What does it mean for each return variant, and what does each part of the return mean?
* What ways the callback gets called.

For instance, take the `init` callback. It could possibly be written something like this (using markdown since I don't know the exdoc syntax):

```
init(args) - invoked when the server is started.
The `args` are passed as args from a call to
`GenServer.start_link(YourServer, args)`. You
can return four different kinds of message:

* `{:ok, state}` - You will probably return this. It sets the starting state for the GenServer, and tells the start_link to return ???.
* `{:ok, state, timeout} - Like previous, but ???.
* :ignore - ???
* {:stop, reason} - ???
```

There is some information that is shared between all callbacks. E.g., `state` as an input is the state of the server before the call and `new_state` in the return is the `state` afterwards. Though `handle_info/2` has `state` in the return position also causing confusion.

**Comment by Havvy** [comment]
This would be easier to do when issue #3630 is fixed.

**Comment by josevalim** [comment]
This is the same as #3630. Closing this. :)
