### ISSUE TITLE
ExUnit: ArgumentError, when running doctest without ExUnit.Case

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3633]
original discussion: https://github.com/elixir-lang/elixir/pull/3628#issuecomment-135986671
and a proposed fix: https://github.com/eksperimental/elixir/commit/9e0690c9f6b48b106eec9962dfe59c8709243399

ExUnit fails when the module fails to compile (CompileError) due to a function clash, but only when ExUnit.DocTest is imported (not via `use ExUnit.Case`)

https://github.com/eksperimental/elixir_fail/blob/master/test/doctest_test.exs#L58-L66
when Import ExUnit.DocTest, the test fails

```elixir
  test "fail: function clash 2" do
    assert_raise CompileError, ~r"function hd/1 imported from both ExUnit.DocTestTest.FunctionClash and Kernel, call is ambiguous", fn ->
      defmodule FunctionClashFail2 do
        import ExUnit.DocTest
        #import Kernel, except: [hd: 1]
        doctest ExUnit.DocTestTest.FunctionClash, import: true
      end
    end
```

```
1) test fail: function clash 2 (ElixirFail.DoctestTest)
     test/doctest_test.exs:58
     Expected exception CompileError but got ArgumentError (argument error)
     stacktrace:
       :erlang.++(:doctest, nil)
       (ex_unit) lib/ex_unit/case.ex:285: ExUnit.Case.__on_definition__/3
       test/doctest_test.exs:63: anonymous fn/3 in :elixir_compiler_6.__MODULE__/1
       (elixir) lib/enum.ex:1385: Enum."-reduce/3-lists^foldl/2-0-"/3
       test/doctest_test.exs:63: (module)
       (elixir) src/elixir_compiler.erl:126: :elixir_compiler.dispatch_loaded/6
       (elixir) src/elixir_module.erl:168: :elixir_module.eval_form/6
       (elixir) src/elixir_module.erl:57: :elixir_module.do_compile/5
```

the one above does not.
https://github.com/eksperimental/elixir_fail/blob/master/test/doctest_test.exs#L43-L56
and they are the same test

**Comment by josevalim** [comment]
Thank you! There is definitely a bug. We just need to find the proper fix. :)
