### ISSUE TITLE
Error on umbrella dependency cycles

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#3634]
Dependency cycles in umbrella apps will cause mix to infinitely recurse instead of erroring.

Example: http://pastebin.com/fiRTStMV

**Comment by antipax** [comment]
Going to work on this now.

**Comment by antipax** [comment]
With two apps in an umbrella referencing each other, the cycle is detected:

`** (Mix) Could not sort dependencies. There are cycles in the dependency graph`

So only the case where the app references itself needs to be fixed.

**Comment by whatyouhide** [comment]
@ericmj closed this for now as as @antipax pointed out, cycles in the graph are already detected. Feel free to reopen if #4667 is not enough.

**Comment by leiding** [comment]
why not print the detailed cycle dependency so people could quick fix this?

**Comment by ericmj** [comment]
@leiding Contributions are welcome, we may be able to use this function to get the cycles: http://erlang.org/doc/man/digraph_utils.html#cyclic_strong_components-1. Otherwise we need to traverse the graph ourselves and detect the cycle.
