### ISSUE TITLE
Equivalent of `npm install` for mix?

### ISSUE THREAD

**Issue by xuxux** [elixir-lang/elixir#3637]
Are there plans for something like `npm install --save` for Mix? That would save me time since I'm always searching hex.pmto figure out the version of the package I need, and then spending a little more time typing it all into mix.exs. It would be great if I could type `mix deps.add  decimal`.

**Comment by josevalim** [comment]
Please don't use the issues tracker for questions or feature discussions.

**Comment by josevalim** [comment]
Check the elixir-lang-core mailing list for that.
