### ISSUE TITLE
Try to warn on pipeline without parenthesis

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3642]
I know we have tried this in the past but we need to give it one more try:

```elixir
[5, 6, 7, 3] 
|> Enum.reverse 
|> Enum.map_join "", &(Integer.to_string(&1)) 
|> String.to_integer
```

This won't work as expected.

Source: http://stackoverflow.com/questions/32303828/strange-behavior-with-string-to-integer-1

**Comment by obrok** [comment]
Is it impossible to give `|>` a very low priority - lower than function application? That seems to be what people expect in cases like this.

**Comment by josevalim** [comment]
Besides being a major backwards incompatible change, it breaks a bunch of places where people rely on `|>` having lower priority and they don't notice it, like in assert:

    assert foo |> bar |> baz == "bat"

**Comment by riverrun** [comment]
Could we deal with this by making additions to the documentation / tutorial, rather than dealing with it at the language level.
Once you know about it, adding parentheses to the function before the pipe operator does not seem so difficult.

**Comment by eksperimental** [comment]
@riverrun it's already in the docs
https://github.com/elixir-lang/elixir/blob/e48ecf47095582a946469d6b572594b4ccfd7721/lib/elixir/lib/kernel.ex#L2544-L2560

**Comment by riverrun** [comment]
Yes, those docs are very clear. My main point is that this problem might be addressed through education rather than at the language level -- especially when developers new to Elixir first see the pipe operator.

**Comment by josevalim** [comment]
@riverrun we already mention that. I have asked Dave to mention on Programming Elixir, it is mentioned on the docs and on the website. People still run into it daily.

**Comment by padde** [comment]
@josevalim maybe this is a more general thing. Other situations can be ambiguous, too. Consider

```elixir
def foo(x, y), do: x + y
def bar(x, y \\ 0), do: x - y
```

Then the following expression

```elixir
foo bar 1, 2
```

Can be interpreted as

```elixir
foo(bar(1), 2)
```

or

```elixir
foo(bar(1, 2))
```

should this throw a warning as well? Would a fix possibly be related to the ambiguous pipeline problem?

**Comment by josevalim** [comment]
No, those are not related issues and are completely different parts of the parser. It is worth mentioning that, although they are ambiguous to the developer, it is not ambiguous to the parser. `foo bar 1, 2` always becomes `foo(bar 1, 2)` and the parser already raises in more confusing cases, like `foo 1, bar 2, 3`.

**Comment by vendethiel** [comment]
Not sure how these would be ambiguous... Unless you're used to perl? It makes sense that a call "gobbles" all its arguments on the right, imho.

**Comment by josevalim** [comment]
Folks, this issue is not about function calls. It is about pipelines. If we want to discuss calls, please start a discussion on elixir-lang-core. :)

**Comment by padde** [comment]
Sorry for starting the off-topic discussion, I just wanted to know whether this has to do with the way parentheses are parsed or not, and apparently it doesn't. Probably I have an entirely wrong picture of the parser inside my head ;-) I will shut up about this now.

**Comment by padde** [comment]
Regarding this issue, I think it is important to note that the *syntax* is ambiguous, regardless of the fact that the parser has a rule to resolve those expressions in an unambiguous way. In my opinion, a viable option would be to refuse parsing ambiguous statements altogether. Would it make things easier if ambiguities were handled at the grammar level? Is this even possible? Or is this the plan anyway?
