### ISSUE TITLE
Difference in dependency handling between platforms

### ISSUE THREAD

**Issue by eproxus** [elixir-lang/elixir#3643]
Running Elixir 1.0.5 and Mix 1.0.5 with targets `mix test` locally on OS X 10.10.5 and on Travis yields different results. On the local OS X environment, everything just works. However, on Travis the following error is produced:

```
$ mix test
Unchecked dependencies for environment test:
* proper (git://github.com/manopapad/proper.git)
  different specs were given for the proper app:
  > In deps/locker/rebar.config:
    {:proper, ~r//, [git: "git://github.com/manopapad/proper.git"]}
  > In deps/jiffy/rebar.config:
    {:proper, ~r/.*/, [git: "git://github.com/manopapad/proper.git", ref: "master"]}
  Ensure they match or specify one of the above in your MyProject.Mixfile deps and set `override: true`
** (Mix) Can't continue due to errors on dependencies
The command "mix test" exited with 1.
```

The full log can be found [here](https://gist.github.com/20e21c82aa27c0602049).

It also seems that the order of compilation between dependencies is wrong. For instance, `proper` should be compiled before `locker` (which has a dependency on `proper` in its the `rebar.config`.

**Comment by josevalim** [comment]
It is jiffy's fault: https://github.com/davisp/jiffy/blob/master/rebar.config.script#L19

**Comment by eproxus** [comment]
Wow, would never have figured that out. I guess switching to Rebar3 / Hex for a majority of Erlang projects can't come soon enough. :-)
