### ISSUE TITLE
mix deps.update problem

### ISSUE THREAD

**Issue by umatomba** [elixir-lang/elixir#3644]
trying to update one dependency i have a problem.

```
mix deps.update hello
* Updating hello (https://github.com/travelping/hello.git)
WARNING: gnome-keyring:: couldn't connect to: /run/user/vtarasen/keyring-DaEysb/pkcs11: No such file or directory
p11-kit: skipping module 'gnome-keyring' whose initialization failed: An error occurred on the device
Running dependency resolution
** (ArgumentError) could not put/update key :deps. Expected map/struct, got: nil
    (elixir) lib/access.ex:138: Access.Map.get_and_update!/3
    lib/hex/resolver.ex:190: Hex.Resolver.attach_dep_and_children/3
    lib/hex/resolver.ex:150: Hex.Resolver.get_deps/5
    lib/hex/resolver.ex:109: Hex.Resolver.activate/5
    lib/hex/resolver.ex:31: Hex.Resolver.resolve/3
    lib/hex/remote_converger.ex:33: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:88: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
```

i have elixir from master commit 22287b142c19b337576e27d59a10cb5b308247fc
mix.ex dependency definition {:hello, github: "travelping/hello"},

**Comment by josevalim** [comment]
@ericmj which Hex version are you using? This is a bug in Hex which has been fixed, although I am not sure if it was released.

**Comment by josevalim** [comment]
@umatomba which Hex version are you using? This is a bug in Hex which has been fixed, although I am not sure if it was released.

/cc @ericmj

**Comment by ericmj** [comment]
It has not been released, it will be fixed in Hex 0.9.0.

**Comment by josevalim** [comment]
Closing this then as it is fixed, just blocking on the Hex version.

**Comment by ericmj** [comment]
You get the error because you are not correctly overriding a dependency. Hard to say where exactly the issue without seeing your full dependency tree.

**Comment by umatomba** [comment]
hi @ericmj,
its 
```
    [{:lager, "~> 2.1.1", override: true},
     {:exlager,  github: "xerions/exlager" },
     {:hello, github: "travelping/hello"},
     {:mariaex, ">= 0.0.0", override: true},
     {:exd, github: "xerions/exd"},
     {:exrun, github: "liveforeverx/exrun"},
     {:linit, github: "liveforeverx/linit"},
     {:exrm, github: "thz/exrm", branch: "configurability", override: true},
     {:earmark, "~> 0.1", only: :dev},
     {:ex_doc, "~> 0.7", only: :dev}]
```
i have Hex v0.8.3

**Comment by josevalim** [comment]
@umatomba can you try to install hex master? Just clone it and follow the instructions in the README. The bug should be fixed and it should tell exactly what went wrong.

**Comment by umatomba** [comment]
ok, thank you!
