### ISSUE TITLE
__info__  for master does not support all keywords provided by module_info

### ISSUE THREAD

**Issue by bbense** [elixir-lang/elixir#3645]
The __info__ function in the current master does not support all the keyword args useable by 
module info. In version 1.0.5, this does work. 

    Erlang/OTP 18 [erts-7.0.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

    Interactive Elixir (1.1.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> Enum.__info__(:md5)
        ** (FunctionClauseError) no function clause matching in Enum.__info__/1
        (elixir) Enum.__info__(:md5)
    iex(1)> Enum.module_info(:md5)
     <<54, 239, 248, 81, 19, 195, 35, 164, 87, 184, 85, 76, 57, 218, 36, 4>>

    Erlang/OTP 18 [erts-7.0.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

    Interactive Elixir (1.0.5) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> Enum.__info__(:md5)
      <<73, 77, 8, 242, 104, 64, 229, 89, 20, 59, 224, 46, 77, 155, 230, 77>>

The missing keywords are  `:md5` and `:native`

**Comment by bbense** [comment]
This is my git log for the master branch 

commit cc233805229eb9b65c5532916757ca0357076c16
Merge: df1ea63 a7605f6
Author: Jos<C3><A9> Valim <jose.valim@gmail.com>
Date:   Sun Aug 30 22:22:12 2015 +0200

    Merge pull request #3638 from hashd/iex-pid-helper

    iex pid helper, using :c.pid

commit a7605f67e4ed4986c5052e896720fc3707fe9a1a
Author: hashd <gitk@danduprolu.com>
Date:   Mon Aug 31 00:49:31 2015 +0530

    implemented iex pid helper, using :c.pid

commit df1ea6300241edf0b93146fc248009320204c14a
Merge: dfa0847 10c398d
Author: Jos<C3><A9> Valim <jose.valim@gmail.com>
Date:   Sun Aug 30 13:33:58 2015 +0200

    Merge pull request #3636 from matteosister/docs_about_keep_in_option_parser

    add docs for :keep option in OptionParser module

**Comment by josevalim** [comment]
Can you point to me where those options are documented? Because they may as well be private.

**Comment by bbense** [comment]
I agree that this could be considered a documentation bug. Here are my sources. 

iex>  h Enum.__info__

                               def __info__(kind)

Provides runtime information about functions and macros defined by the module,
enables docstring extraction, etc.

Each module gets an __info__/1 function when it's compiled. The function takes
one of the following atoms:

  â¢ :functions  - keyword list of public functions along with their arities
  â¢ :macros     - keyword list of public macros along with their arities
  â¢ :module     - module name (Module == Module.__info__(:module))

In addition to the above, you may also pass to __info__/1 any atom supported by
Erlang's module_info function which also gets defined for each compiled module.
See http://erlang.org/doc/reference_manual/modules.html#id69430 for more
information.

From http://erlang.org/doc/reference_manual/modules.html


module_info/1

The call module_info(Key), where Key is an atom, returns a single piece of information about the module.

The following values are allowed for Key:

module
Returns an atom representing the module name.

attributes
Returns a list of {AttributeName,ValueList} tuples, where AttributeName is the name of an attribute, and ValueList is a list of values. Notice that a given attribute can occur more than once in the list with different values if the attribute occurs more than once in the module.

The list of attributes becomes empty if the module is stripped with the beam_lib(3) module (in STDLIB).

compile
Returns a list of tuples with information about how the module was compiled. This list is empty if the module has been stripped with the beam_lib(3) module (in STDLIB).

md5
Returns a binary representing the MD5 checksum of the module. If the module has native code loaded, this will be the MD5 of the native code, not the BEAM bytecode.

exports
Returns a list of {Name,Arity} tuples with all exported functions in the module.

functions
Returns a list of {Name,Arity} tuples with all functions in the module.

native
Return true if the module has native compiled code. Return false otherwise. In a system compiled without HiPE support, the result is always false

**Comment by josevalim** [comment]
Awesome, thank you! A fix is being added to master soon. Also note that :md5 and :native are Erlang 18 only.
