### ISSUE TITLE
Mark Release Candidate as pre-releases in github

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3649]
Github gives us the options to mark the pre-releases, as such,
that would give a red button in the release page,
https://github.com/elixir-lang/elixir/releases

here's an example of what it will look like,
https://github.com/eksperimental/elixir_fail/releases

this also affects if some other app wants to retrieve the latest released final version,
this reflected in the JSON file for the releases,
https://api.github.com/repos/elixir-lang/elixir/releases

right-now all objects are `"prerelease": false,` 

I think we should tick all the releases properly,

**Comment by josevalim** [comment]
I didn't want to mark 1.0.0-rc1 as a prerelease because up to that point, all of them were pre-releases. So marking 1.0.0-rc1 as a pre-release would be inconsistent. The upcoming 1.1.0-beta will be marked as a prerelease though.

**Comment by eksperimental** [comment]
well, my suggestion was to mark all of them before 1.0 as pre-releases.
I know it's a pain in the but, but i was working with a program that would check for the available releases, and having the marks in the json as such can be source confusion.
I know it's a pain the neck, since it's 30 something pre-releases, but i just felt the need to mention it.
my script reads from elixir-lang.org,
but I think it can developers' lives easier (specially when a tool written for github can work for any repository) to rely on such feature, lets say to download all avaliable non-prereleases

**Comment by josevalim** [comment]
> well, my suggestion was to mark all of them before 1.0 as pre-releases.

Ok, then I agree. :)

**Comment by eksperimental** [comment]
:+1:

**Comment by josevalim** [comment]
Btw, which endpoint are you using to access pre-releases so  I can check and be sure I didn't leave anything behind?

**Comment by josevalim** [comment]
It should be all done.

**Comment by lexmag** [comment]
Nice. :+1:

**Comment by eksperimental** [comment]
yes, you did it all, i checked the json file and it's only 6 releases marked as final ones.
now the json file is sorted by the published date, so it's all scrambled-up... hahaha i will report this issue to github,
https://api.github.com/repos/elixir-lang/elixir/releases

**Comment by eksperimental** [comment]
thank you jose!

**Comment by kyrias** [comment]
The last two release candidates were marked as regular releases rather than pre-releases again.  This is bothersome when using tools like nvchecker to keep track of software releases.

**Comment by josevalim** [comment]
@kyrias fixed, thank you!
