### ISSUE TITLE
Requirements and Alternative Methods to Install Documentation

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3650]
The stuff discussed here apply to the Elixir project as well as to it's [website project](https://github.com/elixir-lang/elixir-lang.github.com/),

## GNU MAKE
First, i think we need to mention that if you want to compile Elixir from source code, you need to have GNU MAKE installed, i don't know which would be the base version, but it will be good to find out.

## GIT and EX_DOC
Let's have in mind that at the moment the elixir docs are not downloadable in a package format and they have to be build.

I don't know how to git works on Windows,
but i can assume some people are not gonna have git installed, so git shouldn't be a requirement if they want to build the documentation.

this comes from the tasks to build the docs,
which require ex_doc, which can be downloaded from the as a package as a tar.gz,
and that the make task in elixir to build the docs requires git to find HEAD commit version.

that gives an error,
```sh
Generated iex app
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
/bin/sh: 1: git: not found
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.0.5" "lib/elixir/ebin" -m "Kernel" -u "https://github.com/elixir-lang/elixir" --source-ref "" -o doc/elixir -p http://elixir-lang.org/docs.html
```
the docs get generated, but the link fail to link to the commit HEAD.
https://github.com/elixir-lang/elixir/blob//lib/elixir/lib/atom.ex#L22

I think we can come up with a solution, maybe a git hook that stores the latest commit into a `.commit` file ( I haven't looked into it yet)

## INTERNET CONNECTION
And pushing a bit further the idea, to reduce dependencies as much as a possible,
Is it possible to provide a package to ex_doc that will come with all the dependencies needed so if we download elixir source code and this ex_doc package, we can build elixir and it's documentation, without having to be online.

**Comment by josevalim** [comment]
I have updated the release instrutions and we will now add a Docs.zip to the Github Releases (alongside Precompiled.zip).
