### ISSUE TITLE
Warn when defining variable names in head function more than once.

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3653]
```elixir
defmodule DefDefaultArg do
  @spec sample(integer, atom, String.t) :: :atom | tuple
  def sample(a, b, c)
  def sample(1, _, _), do: :one
  def sample(2, _, _), do: :two

  def sample(aaa, bbb, ccc)
  def sample(alpha, beta, gama), do: {alpha, beta, gama}
end
```
function gets documented as: `def sample(a, b, c)`

I think we should give a warning when setting `def sample(aaa, bbb, ccc)` since all the variable names have already been defined. This will warn the user to move this line to the top if he wants these names to be used.

and we shouldn't warn in a situation like this/

```elixir
defmodule DefDefaultArg do
  @spec sample(integer, atom, String.t) :: :atom | tuple
  def sample(a, _, c)

  def sample(1, _, _), do: :one
  def sample(2, _, _), do: :two

  def sample(aaa, bbb, ccc)
  def sample(alpha, beta, gama), do: {alpha, beta, gama}
end
```
function gets documented as: `def sample(a, bbb, c)`

**Comment by josevalim** [comment]
I don't think we should. The reason is because you can use bodyless function definitions for multiple purposes, documentation being one of them. So we don't want to warn for cases where you first document a bodyless function clause and then you perform something else with it.
