### ISSUE TITLE
Supervisor.start_link/2 Dialyzer Error

### ISSUE THREAD

**Issue by Havvy** [elixir-lang/elixir#3665]
Using dialyze on the "Module-based supervisors" example in the Supervisor docs gives me an error:

`Elixir.Supervisor':start_link('Elixir.MyApp.Supervisor',[]) breaks the contract ([tuple()],options()) -> on_start()`

(Tested in Elixir v.1.0.5)

**Comment by fishcakez** [comment]
Fixed in https://github.com/elixir-lang/elixir/commit/bf36c9d636d34c07f7161b0d68c0cbcdd4a3fe62.
