### ISSUE TITLE
Regex lib docs have stray green characters

### ISSUE THREAD

**Issue by augiedb** [elixir-lang/elixir#3670]
Look at [the code samples for Regex.split](http://elixir-lang.org/docs/v1.0/elixir/Regex.html#split/3).  They turn green halfway through the first example and don't return to black until the fifth.

Looks like it starts on the second forward slash on:

```
iex> Regex.split(~r/-/, "a-b-c")
```

and it carries through to the /a in the fifth example:

```
iex> Regex.split(~r/a(?<second>b)c/, "abc")
```

Then things go back to their normal black with quoted strings in red.  

I can't figure out what's causing it.  Are `/,` and `/a` some sort of special code that border green characters or something?  I can't find it.  Markdown?  CSS?  Haven't seen this pop up anywhere else...

**Comment by ericmj** [comment]
This is highlight.js issue that we use in ex_doc to highlight code. Please open an issue with them.

**Comment by eksperimental** [comment]
It's probably the same issues as no. 3 in the list of existing issues for the elixir plugin in highlight.js
https://github.com/isagalaev/highlight.js/issues/730
@augiedb You may want to add it, or I can update it later.

**Comment by eksperimental** [comment]
I think this issues should be moved to https://github.com/elixir-lang/ex_doc/issues

**Comment by ericmj** [comment]
Nothing we can do in elixir or ex_doc until highlight.js is fixed.

**Comment by ericmj** [comment]
@augiedb Thanks for the report

**Comment by josevalim** [comment]
Invoking @knewter as I think he is the one who contributed to highlight.js. :D
