### ISSUE TITLE
Make "mix new" add Hex fields to mix.exs and add install info in README

### ISSUE THREAD

**Issue by henrik** [elixir-lang/elixir#3671]
I just wrote my first hex package and felt the experience was a bit less smooth than it could have been, because the `mix.exs` in my generated project did not include the required/recommended values for a Hex project: description, package.{licenses,contributors,links}

Would also have been nice for the README to get a boilerplate paragraph about how to install this lib as a dependency.

I wouldn't be surprised if some or all of these omissions are intentional with good reasons behind it, so I thought I'd ask before contributing code.

If it is intentionally omitted, could it make sense to add some flag like `mix new my_project --hex` that adds this stuff?

**Comment by ericmj** [comment]
Please send feature requests and discussions to the code mailing list.

**Comment by henrik** [comment]
Thank you! Done: https://groups.google.com/forum/#!topic/elixir-lang-core/bA9fR19JRTc
