### ISSUE TITLE
Warn on imperative use of case/cond/receive

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3676]
We could allow the dirty metadata to have the previous behaviour, still allowing things like if and unless to be implemented. The warn could likely exist forever too, allowing developers to write a code but have the warning point out the best way to write it.

By imperative use, I mean the assignment of variables inside branches.

**Comment by ericmj** [comment]
Feels backwards to take non allowed behaviour and making it a warning instead, I would understand going the other way.

**Comment by lexmag** [comment]
:+1: for case/cond/receive.

**Comment by josevalim** [comment]
@ericmj the behaviour is allowed today.

**Comment by alco** [comment]
@josevalim How does one disable the warning if they have a legitimate use case for such assignment?

**Comment by josevalim** [comment]
@alco can you give a legitimate use case for such assignment?

**Comment by alco** [comment]
I mean, if it doesn't result in a compilation error, it is supposed to be used in some cases. If there's no such legitimate case, it should be an error.

**Comment by josevalim** [comment]
Because the behaviour is allowed today, we need to use warnings at least until Elixir 2.0. Once we get there, you are right, we should probably just error out or simply not export the variable.

**Comment by henrik** [comment]
Just out of curiosity, is this what you're describing?

``` elixir
x = 1

cond do
  true ->
    x = 2
end

IO.puts x  # => 2
```

**Comment by josevalim** [comment]
Yes. :)

**Comment by myronmarston** [comment]
Out of curiosity, why would `if` and `unless` still be allowed to do this?  When I see:

``` elixir
value = 1

if true do
  value = 2
end

IO.puts value
```

In my head I'm initially unsure what `value` will be printed -- I expect `do...end` blocks to be a scope and therefore not to "leak" the rebinding outside the if block.  Then I remember that this works because of trying it out before. Still, it doesn't seem any different from `case/cond/receive` to me.

**Comment by tuvistavie** [comment]
@myronmarston `if` is translated to `case`, so it will follow its behaviour.

With the new construct `with` where variables do not leak, it feels very inconsistent that
`case` and `with` have different behaviours, as both have very similar use.
Conditional assignment are IMO an anti-pattern in functional languages anyway,
so I think the idea of a warning until the behaviour can be removed in 2.0 is good.

**Comment by myronmarston** [comment]
Good to know, thanks @tuvistavie.
