### ISSUE TITLE
Docs: external links in summary

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3688]
http://elixir-lang.org/docs/master/elixir/Port.html#summary_details

Its the only page* in the docs that link to an external page in the summary of the function,
and it makes the page look really bad as it creates a log of distraction.

I think we should add at one short sentence from the erlang docs, and rephrase it if needed due to legal reasons.

* that's not true, http://elixir-lang.org/docs/master/mix/overview.html Mix.Archive does, but this one is alight.

**Comment by josevalim** [comment]
We should definitely fix it.

**Comment by eksperimental** [comment]
@josevalim just a side comment, .... Don't you think  that when we link to erlang documentation, wouldn't it be better to write the link the the elixir source in the following format: `[:erlang.port_call/3](http://www.erlang.org/doc/man/erlang.html#port_call-3)` or `[:leex.file/2](http://www.erlang.org/doc/man/leex.html#file-2)` ?

**Comment by josevalim** [comment]
Sounds like a great idea.

**Comment by eksperimental** [comment]
Sorry but the original issue has not been solved

**Comment by josevalim** [comment]
Ah, I thought it was. Sorry! :)

**Comment by whatyouhide** [comment]
So what's the road we should take here? Rephrase the short description so that it doesn't contain link and then put links in the long description? Or just remove the backticks around the function names so that they don't turn out in a monospaced font?

**Comment by eksperimental** [comment]
I think having a link to an external site as the description of a function is a bad idea.
I think having something like in http://elixir-lang.org/docs/master/elixir/Port.html#info/1 is good.

I would also change rephrase "See :erlang.port_info/1"
with something like:

"For more information, see :erlang.port_info/1"

**Comment by eksperimental** [comment]
Closed by #3779
