### ISSUE TITLE
Rephrase docs for Mix.raise/2

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3696]
https://github.com/elixir-lang/elixir/blob/b5322b1d10e525aa25e4ff48553b2d1b69e69d9c/lib/mix/lib/mix.ex#L239-L243

Its not clear what it is trying to say.

```
  Raises a mix compatible exception.
  A mix compatible exception has a `mix` field which mix
  uses to store the project or application name which is
  automatically by the formatting tools.
```

**Comment by josevalim** [comment]
Which part is confusing? All of it? Is this better?

```
  Raises a Mix compatible exception.
  A Mix compatible exception contains a special field called
  `:mix` that is used to store the current project or application
  name. This information is used by modules like Mix.CLI to
  properly format and show information to the user.
```

**Comment by eksperimental** [comment]
yes, this one is better. the former one use "which" as a joiner twice in the same sentence. and the is mentions that does "something" automatically, but it didn't say what.
Sorry, it was unclear to me upto the point I wouldn't be sure how to rephrase it.

Thanks, i will send a PR after I submit one that I've got the in oven.
