### ISSUE TITLE
Redifining docs does not emit any warning

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3707]
__`@moduledocs`__,  __`@docs`__, __`@shortdoc`__ and __`@typedoc`__ do not emit warning when redefined

I would expect a warning, at least letting the user know what he is redefining something that was already defined.
This was a source of  at least [one issue](https://github.com/elixir-lang/elixir/pull/2943) in Elixir, where left over code was present.

Code:
```elixir
defmodule DocRedefined do

  @moduledoc """
  ElixirBug module.
  """

  @moduledoc """
  @moduledoc is being redefined without warning.
  """

  @doc """
  Returns `:avocado` no matter what.
  """

  @doc """
  @doc is being redefined without warning.
  """
  def get_fruit do
    :avocado
  end
end

defmodule Mix.Tasks.DocRedefined do
  use Mix.Task

  @shortdoc """
  Returns favourite fruit.
  """

  @shortdoc """
  @shortdoc is being redefined without warning.
  """
  def run(_) do
    IO.inspect DocRedefined.get_fruit
  end
end
```

When compiled, produces:
```elixir
$ iex -S mix
Erlang/OTP 18 [erts-7.0] [source] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Compiled lib/elixir_bugs.ex
Compiled lib/doc_redefined.ex
Generated elixir_bugs app
Interactive Elixir (1.1.0-beta) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> h DocRedefined

                                  DocRedefined

@moduledoc is being redefined without warning.

iex(2)> h DocRedefined.get_fruit

                                def get_fruit()

@doc is being redefined without warning.
```

```sh
$ mix --help | grep doc_redefined
mix doc_redefined     # @shortdoc is being redefined without warning.
```

[elixir_bugs/doc_redefined](https://github.com/eksperimental/elixir_bugs/tree/doc_redefined)
` git clone -b doc_redefined --single-branch https://github.com/eksperimental/elixir_bugs.git doc_redefined`

**Comment by danielberkompas** [comment]
I'd like to try and fix this. Is `Module.put_attribute/3` the correct place to start?

**Comment by josevalim** [comment]
I can't remember out of the box but I think @doc is the one of the attributes that are special cased and do not go through put_attribute.

**Comment by danielberkompas** [comment]
@josevalim Still learning my way around the source. Where does the compiler deal with special cases like this?

**Comment by eksperimental** [comment]
i have added __\@typedoc__ to the list

**Comment by danielberkompas** [comment]
I think I've found the special-casing for `@doc`: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_module.erl#L349-L377

**Comment by josevalim** [comment]
Check the Module.add_doc function. It is probably around there.

**Comment by lexmag** [comment]
It starts in `Module.compile_doc/5` function.

**Comment by danielberkompas** [comment]
How do you emit a warning when you're working in the Elixir source? `IO.puts` isn't available inside the `Module` module. What should I use instead?
