### ISSUE TITLE
Preferring Kernel.match? in asserts and refutes of matches should be documented.

### ISSUE THREAD

**Issue by bbhoss** [elixir-lang/elixir#3709]
Since we're now preferring to use the match? macro when asserting and refuting things, this should be documented for folks so they're aware of it when writing their tests. Functionality was merged in with #3609. It was recommended to modify the Assertion docs by @josevalim. I will try to take a stab at this tonight.

**Comment by ericmj** [comment]
Why are we recommending to use `match?/2` when asserting? I understand for refute since it was changed, but `assert foo = bar` is a lot more readable than `assert match?(foo, bar)`.

**Comment by bbhoss** [comment]
I agree, but it seems very inconsistent to only show it used on refute

**Comment by ericmj** [comment]
Sure, we can show an example. But why is it preferred to use `match?` over `=`?

**Comment by bbhoss** [comment]
Maybe I misunderstood, but this is a quote from IRC: "@josevalim> bbhoss: the preference is to use match?"

**Comment by josevalim** [comment]
I will go ahead and change this trying to address both of your concerns.
