### ISSUE TITLE
Regex doesn't match multibyte characters when it should

### ISSUE THREAD

**Issue by martinsvalin** [elixir-lang/elixir#3711]
Regex seem to have trouble matching multibyte characters correctly, even when using a unicode category. The pattern `~r/\p{L}$/` should match both `a` and `á`, but matches only the `a`.

```elixir
iex> Regex.match? ~r/^\p{L}+$/, "a"
true
iex> Regex.match? ~r/^\p{L}+$/, "á"
false
```

It's not that the unicode category doesn't match, but rather it seems that the multibyte character trips up the match for the next character, or anchor in the example above.

```elixir
iex> Regex.match? ~r/\p{L}{1}/, "áá"
true
iex> Regex.match? ~r/\p{L}{2}/, "áá"
false
```

I've seen this in both Elixir 1.0.5 and 1.1.0-beta.

**Comment by josevalim** [comment]
Regex works on bytes by default so the second one is probably matching by accident due to the bytes involved. If you are using `\p` and friends, you likely want to use the `u` modifier:

```iex
iex(3)> Regex.match? ~r/^\p{L}+$/u, "á"
true
```

**Comment by martinsvalin** [comment]
Doh. Thanks, José.
