### ISSUE TITLE
mix test doesn't work with path in umbrella projects

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#3712]
In 1.0 you could pass a path to a file within any of the applications (even omitting the `apps/application_name` part) and mix would match against all applications to find relevant files. 

In 1.1 it fails with:
```
** (Mix) Test pattern did not match any file, the files given to compile: filename
```
even if I give it the full path to the file.

Allowing a path without the `apps/application_name` part was especially useful, because that's what printed along each test, so you could just copy and past it to isolate a test.

\cc @josevalim @lexmag

**Comment by josevalim** [comment]
If we warn for the projects where no path matches... would this ok?

**Comment by michalmuskala** [comment]
I agree that no matches warning can be useful.

I guess it's fine to warn in umbrellas too.

**Comment by josevalim** [comment]
Ok, I pushed a commit to master. can you plesae give it a try?

**Comment by michalmuskala** [comment]
Works perfectly, thanks!
