### ISSUE TITLE
ExUnit: pending tests?

### ISSUE THREAD

**Issue by AaronSikes** [elixir-lang/elixir#3721]
Would you be interested in having pending tests in ExUnit? I'd be particularly interested in two forms - pending implementation (adding a test/1) like [this](https://www.relishapp.com/rspec/rspec-core/v/2-0/docs/pending/pending-examples#pending-implementation) and temporarily pending by changing test to xtest like [this](https://www.relishapp.com/rspec/rspec-core/v/2-0/docs/pending/pending-examples#temporarily-pending-by-changing-"it"-to-"xit").

The first, pending implementation, is very useful when collecting requirements for a module in the first place. The second, xtest, can be very useful when copying over a test that will be structurally similar, or when writing an incomplete test could inform the writing of another test.

**Comment by josevalim** [comment]
Please use elixir core for feature proposals. I think this topic was even already discussed in the issues tracker.

**Comment by josevalim** [comment]
In fact, it is part of Elixir v1.1: https://github.com/elixir-lang/elixir/pull/3419

**Comment by AaronSikes** [comment]
Thanks for the info, I hadn't seen that. Apologies I didn't read contributing.md thoroughly
