### ISSUE TITLE
Discuss alternatives to File.stat

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3731]
`File.stat` returns local times while we should favor universal times. Since we can't change it, we should deprecate it and introduce a new one. Note that Elixir v1.1 introduces `lstat` also, for links.

My suggestion is `File.fstat` which is also inline with existing syscalls.

**Comment by ericmj** [comment]
We should change both `File.touch` and `File.stat` or we should change neither. It doesn't make sense to change just one of them.

**Comment by lau** [comment]
It would be good if the default for every File function that has to do with files and time is UTC. It would be an API change, so it would need to be done in a future version. 1.2? 2.0?

A way to do it could be: 

- Add warnings (in 1.1?) in the documentation mentioning a coming change to UTC as the default. Encouraging API users to specify either local or UTC time at every function call until the new version. Also encouraging users to change their code to use UTC.
- Start issuing depreciation warnings every time a function is called with the current default (local time).
- In a newer version, finally change all the file related functions to have UTC as default

This way if people just want to continue using their code calling local time and not changing how it works, they just have to look at the warnings and make sure that local time is specified before upgrading to the version where all the defaults are UTC.
