### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by optikfluffel** [elixir-lang/elixir#3732]
I wonder why Elixir doesn't have a Code of Conduct yet.
I'd suggest adding [the one from the Contributor Covenant](http://contributor-covenant.org/version/1/2/0/) as `CODE_OF_CONDUCT.md` and link to it from the [`README.md`](https://github.com/elixir-lang/elixir/blob/master/README.md) and  [`CONTRIBUTING.md`](https://github.com/elixir-lang/elixir/blob/master/CONTRIBUTING.md).

Any thoughts on that?

**Comment by eksperimental** [comment]
it does, since 24hr ago
https://github.com/elixir-lang/elixir/blob/master/CODE_OF_CONDUCT.md

**Comment by optikfluffel** [comment]
Oh, I've overlooked that. Cool! :grin:

**Comment by eksperimental** [comment]
but I think we should link from the pages you mentioned, since now it is an orphan file.
(please fell free to reopen the issue)

**Comment by optikfluffel** [comment]
#3733

**Comment by eksperimental** [comment]
:+1:
