### ISSUE TITLE
Unhelpful error message when rebar compilation fails

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#3737]
```
λ mix deps.compile eper
==> eper (compile)
ERROR: [...]/deps/eper/.rebar/erlcinfo file version is incompatible. expected: 1 got: 2
ERROR: compile failed while processing [...]/deps/eper: rebar_abort
** (Mix) Could not compile dependency :eper, "/Users/alco/.mix/rebar" command failed. If you want to recompile this dependency, please run: "mix deps.compile eper"
```

Cleaning the dependency solves the issue. Should it be mentioned in the error message itself, e.g. "Try `mix deps.clean eper` and then recompile"?

**Comment by josevalim** [comment]
It is hard for us to guess exactly what we should do. For some, cleaning may not help it. That said, we could mention try cleaning it or recompiling it, but it is important to know there is no guarantee.

**Comment by josevalim** [comment]
Fix coming soon.

**Comment by schnittchen** [comment]
Came across this today in a CI environment, cleaning the workspace (jenkins parlance) helped. In other words, this is still an issue.

**Comment by ericmj** [comment]
@schnittchen The error is from rebar, there is nothing we can do about it.
