### ISSUE TITLE
Sending input to IEx too quickly ends up in Eshell

### ISSUE THREAD

**Issue by Nicd** [elixir-lang/elixir#3741]
If you send input to IEx when it has not started yet, the input ends up in Eshell and usually crashes the shell. Example:

```
Kerosene:elixir nicd$ echo "Foo.bar" | iex
Eshell V7.0.3  (abort with ^G)
* 1: syntax error before: '.'
*** Terminating erlang (nonode@nohost)
```

This means at this point you need to use something like `expect` to send input to an IEx shell correctly.

**Comment by eksperimental** [comment]
I think iex cannot interpret info passed trough STDIN,
at least i cannot see that is is doing that in 

probably same feature request as this: https://github.com/elixir-lang/elixir/issues/3425
from what @ericmj mentioned, there is the intention to get rid of the shell scripts real soon.

**Comment by Nicd** [comment]
Well, here is a working script I made with `expect` that sends to STDIN: <https://bitbucket.org/vincit/mebe/src/67c5d55ea627a2b6973980f4d20044cbd8462d23/refresh.exp?at=master&fileviewer=file-view-default>

I think the issue there is just that you need to wait until IEx is ready before sending data.

**Comment by ericmj** [comment]
@eksperimental There are no plans to get rid of the shell scripts afaik.

**Comment by eksperimental** [comment]
@ericmj sorry about the confusion. So. what did you exactly meant by https://github.com/elixir-lang/elixir/issues/3662#issuecomment-137416351

**Comment by ericmj** [comment]
I am talking about the shell scripts we use to download hex and rebar, we used to call `wget` or `curl` because Erlang doesn't do the proper SSL out of the box. In 1.1.0 we will rely on signing instead of SSL for safe file fetching so we dont have to shell out to external programs.

**Comment by josevalim** [comment]
I have been exploring this on and off and it does not seem to be possible to customize how IEx will behave regarding stdout, unfortunately. The erlang shell will always try to interpret it and abort right after. I am marking this as unresolved unless someone has a break through on how to solve this.
