### ISSUE TITLE
timing tests the wrong way?

### ISSUE THREAD

**Issue by odo** [elixir-lang/elixir#3748]
Not sure if issue or wanted:

In ExUnit, the measured time includes the setup, which might take up a lot more time than the actual test.
Shouldn't the measurement only include `exec_test(test, context)`?

https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/runner.ex#L242

**Comment by josevalim** [comment]
I don't think so, the setup is part of the test. You want to measure that too. Btw, please take such discussions to the elixir-core mailing list, we will actually hear more feedback fro folks.
