### ISSUE TITLE
Suspending Stream.flat_map triggers side effects in prior streaming functions

### ISSUE THREAD

**Issue by benwilson512** [elixir-lang/elixir#3751]
Take the following code:
```
stream = Stream.repeatedly(fn ->
  IO.puts "hey"
  [1,2,3]
end)
Enumerable.reduce(stream, {:suspend, nil}, fn(v, _) -> {:suspend, v} end)
```
If you call `Enumerable.reduce(stream, {:suspend, nil}, fn(v, _) -> {:suspend, v} end)` on it you simply get the expected `{:suspended, nil, #Function<3.11075252/1 in Enumerable.Stream.do_each/4>}` and there's no IO output. BUT if you add a `Stream.flat_map` call:

```
stream = Stream.repeatedly(fn ->
  IO.puts "hey"
  [1,2,3]
end) |> Stream.flat_map(&(&1))
Enumerable.reduce(stream, {:suspend, nil}, fn(v, _) -> {:suspend, v} end)
```
You get the same return value as before BUT you also get "hey" printed to the console. This seems unintended, and is problematic. StreamRunner relies on being able to suspend a stream as part of the init process and that's obviously a very bad time to trigger unexpected side effects.

**Comment by benwilson512** [comment]
Since `flat_map` trivially hands off the real work to transform, I started looking there. Possibly this is the issue? https://github.com/elixir-lang/elixir/blob/b1088475a2f1fff4f2bb4a995c8f511befa77dd0/lib/elixir/lib/stream.ex#L691

**Comment by josevalim** [comment]
Yes, if `inner_acc` is `{:suspend, _}` or `{:halt, _}`, we shouldn't invoke the next function, only if it is cont.

**Comment by benwilson512** [comment]
Test Case:
```
  test "transform/3 with suspend" do
    stream = Stream.repeatedly(fn -> throw(:kaboom) end)
    |> Stream.transform(nil, &{[&1, &2], &1})

    assert {:suspended, nil, _} = Enumerable.reduce(stream, {:suspend, nil}, fn(v, _) -> {:suspend, v} end)
  end
```

**Comment by josevalim** [comment]
Awesome! Do you want me to tackle this or will you go ahead?
