### ISSUE TITLE
Guidance/help building Elixir package for OpenWRT

### ISSUE THREAD

**Issue by kevinold** [elixir-lang/elixir#3753]
I would like to build Elixir to run on OpenWRT.  I need a bit of guidance and/or help building the Makefile as defined here: http://wiki.openwrt.org/doc/devel/packages.

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by peterwillcn** [comment]
@kevinold see https://github.com/openwrt/packages/pull/11903

**Comment by peterwillcn** [comment]
@kevinold https://github.com/openwrt/packages/pull/11903
