### ISSUE TITLE
Capturing a function with large arity number consumes much memory.

### ISSUE THREAD

**Issue by bredov** [elixir-lang/elixir#3754]
The case
```elixir
iex> &String.at/100_000_000
```
will try to allocate memory for 100.000.000 possible arguments of capture, what can lead to a crash of interpreter.

**Comment by eksperimental** [comment]
oh.... gosh

**Comment by whatyouhide** [comment]
By heart, this should be easy to fix (and somewhere around [here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_fn.erl#L40)).

**Comment by michalmuskala** [comment]
The capture syntax should probably check if the arity is under 255, because that's the limit according to Erlang documentation: http://www.erlang.org/doc/efficiency_guide/advanced.html

**Comment by ericmj** [comment]
We can fix this in Elixir for `&Module.fun/N` but please report to erlang as well because the underlying issue is with `:erlang.make_fun/3`.

**Comment by DavsX** [comment]
Is it this line of code? https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_fn.erl#L101

**Comment by ericmj** [comment]
@DavsX Yes.

**Comment by lexmag** [comment]
There is not problem with `:erlang.make_fun/3` itself, it is `lists:seq/2`(https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_fn.erl#L41) what causes OOM.

**Comment by josevalim** [comment]
There are three bugs here:

1. erlang:make_fun as shown by @lexmag 
2. Elixir should raise a nice error message if arity > 255
3. Elixir should not use `lists:seq` if the module is unknown, it should simply use make_fun. We should only expand for macros
