### ISSUE TITLE
 Docs: GenEvent.add_handler/3 docs do not mention about using {HandlerModule, id}

### ISSUE THREAD

**Issue by myers** [elixir-lang/elixir#3760]
If you want to use the same module as a event handler you need to pass it in as {Module, id}.  

http://elixir-lang.org/docs/v1.0/elixir/GenEvent.html <- docs

https://github.com/elixir-lang/elixir/blob/v1.0.5/lib/elixir/lib/gen_event.ex#L738 <- where this is possible.

**Comment by CrowdHailer** [comment]
It took until I read learn you some erlang for me to discover this was possible. Admittedly it is discoverable from looking at the type definitions but would be good to make clearer

**Comment by josevalim** [comment]
If someone could send a PR for this, we would really appreciate it!

**Comment by druzn3k** [comment]
well @josevalim, I tried. Obviously, feel free to tell me if it's not up to standards or just plain wrong (wrong place, wrong doc). :smile:
