### ISSUE TITLE
Add more info about :via registry to GenServer

### ISSUE THREAD

**Issue by Havvy** [elixir-lang/elixir#3761]
Currently the documentation of how `:via` works for the server name for OTP things, there's very little information, even counting the Erlang docs. It'd be nice to have more information about this.

**Comment by javimolla** [comment]
Hi @Havvy, I'm new to elixir but I want to help

For what I read from the docs I understand the following: The `:via` method needs a module that exports `register_name/2`, `unregister_name/1`, `whereis_name/1` and `send/2` functions implemented in `:global` module. These functions are responsible for keeping the list of names of processes and their associated pid's that are available globally for a network of Erlang nodes whereas in the module you could choose to register globally or local with a custom implementation

Please, give your feedback

**Comment by josevalim** [comment]
You are correct @javimolla!

**Comment by javimolla** [comment]
@josevalim Ok, so, any hints on where do I have to change the docs? any specific branch?

**Comment by josevalim** [comment]
In the `GenServer` module. Always master branch. :)

**Comment by michalmuskala** [comment]
I wonder, why isn't this a behaviour? It looks like a perfect candidate to be one.
