### ISSUE TITLE
Adnotation for Elixir compiler to warning CamelCase module name with file name camel_case.ex

### ISSUE THREAD

**Issue by Tica2** [elixir-lang/elixir#3762]
My use case come from current developer behavior to copy and paste elixir
file module (like template), put new name for file but forgot to change module name or change with wrong name.

Second case is when we do typo errors.

Is not about me, is about large project with a lot of files and where code is writed by more member team (Junior, Senior, ...) This is like project manager tool to be sure project respect some names rules. 
Java have strong rule here, but is to hard (see many modules in same file).

I prefer to have a *compiler option* that show **warning** only when is used.

Possible solution in file company_rol_type.es 

```elixir
defmodule CompanyRoleType do
   @compiler_camel_case_warning = true
   
   # module definition
   
end
```

Expected output:

> mix compile
web/models/company_rol_type.es warning: CompanyRoleType module expected to be in company_role_type.ex(s) file

Thanks,
@Tica2

**Comment by Tica2** [comment]
or better to say in mix.exs (or .compiler_rc ) ?

[web/models/**/*.ex]
     @compiler_camel_case_warning = true
     @compiler_one_root_module_warning = true

**Comment by ericmj** [comment]
Please send feature requests to the core mailing list.

**Comment by Tica2** [comment]
Upps, sorry 
done here
https://groups.google.com/forum/#!topic/elixir-lang-core/aoMTD5hAKJI
