### ISSUE TITLE
Use new io_lib:scan_format functions in Logger

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3763]
See: https://github.com/erlang/otp/commit/3c3a5b08589a6e54b0d2d81e470fcffaaa74c15c

Unfortunately it requires Erlang 18.1. Which means this is for Elixir 1.3 or even later.

**Comment by lexmag** [comment]
I think `io_lib` is meant here.

**Comment by josevalim** [comment]
Good catch, thanks!

**Comment by josevalim** [comment]
Moved to #4617.
