### ISSUE TITLE
Local system path leaks into docs / .beam files

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3764]
Somehow, and I still don't know how,
only in some of the files when i generate the docs with ExDoc for the exlicir project, i see this as the links or the VIEW SOURCE.

`<a href="https://github.com/elixir-lang/elixir/blob/b1088475a2f1fff4f2bb4a995c8f511befa77dd0//Users/jose/OSS/elixir/lib/elixir/lib/path.ex#L1" title="View Source" class="view-source" rel="help">`

which is the information about your system @josevalim

My question is. why I am seeing this, if i'm building from master.

I searched for that string "Users/jose" and I wasn't able to find anything.

The only  thing I can think of is that i am using exevn and I have installed the precompiled sources.. which in some of them, like in Elixir.Access.beam, i was able to find that string. (for the beta version)

> timehb�a	aaaa
> hdsourcek//Users/jose/OSS/elixir/lib/elixir/lib/access.exjAbst 

Maybe it's also a bug in ExDoc.

exevn is using my git repository from "master"  in the ex_doc folder,
and for the rest it is using the precompiled beta.

It could be considered a security issue because it's revealing information about your personal data, which could be contained in dir path,

**Comment by eksperimental** [comment]
only these modules pass this information to the docs

- Access
- Application
- Code
- Collectable
- Enum
- File
- GenEvent
- GenServer
- IO.ANSI
- IO
- Kernel
- Keyword
- List.Chars
- List
- Macro.Env
- Macro
- OptionParser
- Path
- Process
- Regex
- String.Chars
- String
- Supervisor
- Supervisor.Spec
- System

**Comment by josevalim** [comment]
That's happening because it is loading modules from the precompiled Elixir files. Which command are you using to generate the docs?

**Comment by eksperimental** [comment]
`make docs_elixir`

**Comment by eksperimental** [comment]
from the git repository folder, not from the folder with the precompiled beam files.

**Comment by josevalim** [comment]
can you check if your sources are messed up? Something like this:

    $ bin/iex
    iex> GenServer.__info__(:compile)[:source]

**Comment by eksperimental** [comment]
```elixir
iex(1)>  GenServer.__info__(:compile)[:source]
'/Users/jose/OSS/elixir/lib/elixir/lib/gen_server.ex'
```

**Comment by josevalim** [comment]
so the files themselves were compiled wrong. try compiling everything from scratch again.

**Comment by eksperimental** [comment]
It should not matter than "beta" is my main global elixir version in my system, 
it should not interfere when building from source, right?

**Comment by josevalim** [comment]
It should not. It is likely a bug in Makefile that is using your global elixir to compile instead of the local one or something of sorts.

**Comment by eksperimental** [comment]
i recompiled and i got the same path.
i realized, that if I enter `bin/`
iex will execute they one in  `$PATH`, and not `iex` in the current dir. weird!

anyways, i generated the new files and it is not working.
Should i open a ticket for ExDoc? is there anything we can do to prevent the path appearing in the link?

**Comment by josevalim** [comment]
No, it is not ExDoc's fault.

**Comment by josevalim** [comment]
How are you invoking IEx? you need to invoke it from root with `bin/iex`.

**Comment by eksperimental** [comment]
yes, I did, `cd bin` and then `iex`,
So i cannot tell what the actual value of ` GenServer.__info__(:compile)[:source]` was before i recompiled.

**Comment by josevalim** [comment]
If you do `cd bin` and `iex`, it will use the one from path. You need to either do `bin/iex` or `./iex` from `bin`.

**Comment by josevalim** [comment]
i can't reproduce this so I am closing. If you have more information, please let us know, but it is certainly the precompiled paths interfering.
