### ISSUE TITLE
A copy of the license should be included in the documentation

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3775]
Now that we provide the docs in zip format, I think there should be a copy of the LICENSE and NOTICE in the main folder, or under each individual project.

**Comment by josevalim** [comment]
Yes, good catch! Can you please add it to the zip builder in the Makefile?

**Comment by eksperimental** [comment]
sure
one copy per each project's folder?

**Comment by josevalim** [comment]
No, we can copy it to the doc root. Since everything is in the same zip, kind of mirrong the elixir structure. :)

**Comment by eksperimental** [comment]
I'm thinking if we should include any other files.
Since the file has no version number, and thefolder neither show the version number, should we include VERSION  ?

Other files to consider including:
- README.md
- CHANGELOG.md

I think read me is good because it gives information about the project, where to get help and whatnot,

**Comment by josevalim** [comment]
:+1: for README.md and CHANGELOG.md
