### ISSUE TITLE
Macro expansion bug?

### ISSUE THREAD

**Issue by yrashk** [elixir-lang/elixir#378]
``` elixir
iex> expr = quote do
...> if !a, do: oneway, else: anotherway
...> end
{:if,0,[{:"!",0,[{:a,0,:quoted}]},[{:do,{:oneway,0,:quoted}},{:else,{:anotherway,0,:quoted}}]]}
iex> IO.puts Macro.to_binary(Macro.expand(expr, __ENV__))  
case(!!a) do
  false ->
    oneway
  true ->
    anotherway
end
:ok
iex> Macro.expand(expr, __ENV__)
{:case,0,[{:"!",0,[{:"!",0,[{:a,0,:quoted}]}]},[{:do,{:"->",0,[{[false],{:oneway,0,:quoted}},{[true],{:anotherway,0,:quoted}}]}}]]}
```

**Comment by jechol** [comment]
I expected `Macro.expand` to expand recursively, so that I had to do googling a bit of time to find this issue.
Seems a little bit confusing...

**Comment by jechol** [comment]
In `Macro.expand_once` doc,
```
Notice that expand_once/2 performs the expansion just once and it is not recursive.
Check expand/2 for expansion until the node can no longer be expanded.
```

It says `Macro.expand_once` is not recursive and recommend to check `Macro.expand` for such a case. It sounds like `Macro.expand` would expand recursively...

**Comment by josevalim** [comment]
`Macro.expand` recurses but it does not *traverse*.

**Comment by OvermindDL1** [comment]
For anyone that needs to recursively expand, I use this all over the place in my macro libraries (it is surprising just how often I need it actually...):

```elixir
expanded_ast = Macro.prewalk(ast, &Macro.expand(&1, env))
```

But yeah, as seen it is easy enough to write it that it is not really needed to add it to the `Macro` module.
