### ISSUE TITLE
IEx should automatically link erlang functions to the erlang documentation

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3791]
We automatically create these links to the erlang documentation in ExDoc, when we call 
> \`:erlang.nodes/1\`

in the documentation,
but IEx doesn't do anything about it.

So right now we have to add the link for every function.

Previously discussed:
- https://github.com/elixir-lang/elixir/pull/3691#discussion-diff-38946913
- https://github.com/elixir-lang/elixir/pull/3691#issuecomment-138628383

**Comment by ericmj** [comment]
I don't think we should do this, we don't create links for elixir functions so why do it for erlang functions? We have ongoing work in PRs for supporting erlang functions in the `h` helper which will make it consistent across elixir and erlang.
