### ISSUE TITLE
Mix fails to warn about override: true in umbrella projects

### ISSUE THREAD

**Issue by bbhoss** [elixir-lang/elixir#3795]
In the repo https://github.com/bbhoss/phoenix-umbrella-fail when I try to upgrade the phoenix app to use the master version on Github, instead of warning me that I need to add override: true, it fails to update silently, and remains at Hex 1.0.2.

**Comment by josevalim** [comment]
Thanks for the report. :D

**Comment by josevalim** [comment]
Reopening because the current solution has been reverted due to regressions. We should discuss a better solution which should likely just run `mix deps.check --no-compile` at the end of the fetcher.
