### ISSUE TITLE
Unable to install old version on Ubuntu

### ISSUE THREAD

**Issue by coryfklein** [elixir-lang/elixir#3797]
Following the instructions listed [here](http://elixir-lang.org/install.html) but on the last step specifying a version number:

```
sudo apt-get install elixir=1.0.0
```

And I get the error:

> E: Version '1.0.0' for 'elixir' was not found

My project depends on [poxa](https://github.com/edgurgel/poxa) which only supports version ~>1.0.0 so this prevents me from using poxa.

**Comment by josevalim** [comment]
We are not the one responsible for maintaining distribution packages. You can follow the install instructions to use a precompiled one or compile from source. In any case, there is no need for you to use 1.0.0 explicitly. In fact, `1.0.5` is preferred.

**Comment by eksperimental** [comment]
Run `apt-cache policy erlang` to see what elixir versions you have available.

**Comment by eksperimental** [comment]
sorry, it should read `apt-cache policy elixir` in the command above (i typed accidentally "erlang")
