### ISSUE TITLE
[ExUnit] ArgumentError as test failure on elixir v1.1.0 and v1.1.1

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/elixir#3800]
Hi!

Some tests, ending with ArgumentError without any other information.

The information, that I've gathered for error until now:
* it happens only for 17.4 erlang, it doesn't happen on 18.X.
* it happens, only if match is presented. (Seems like a problem with complex matches with maps)
* it happens, only if right side is a call, not if it is a datastructure
* elixir v1.1.0 and v1.1.1 are affected.

There is minimal reproducible example: 

```elixir
defmodule AssertTestTest do
  use ExUnit.Case
  doctest AssertTest

  test "the truth" do
    assert {:ok, _} = call
    assert {:ok, %{a: _}} = {:ok, %{a: 1, b: 2}}
    assert {:ok, %{a: _}} = call # this test will fail
  end

  def call() do
    data = {:ok, %{a: 1, b: 2}}
  end
end
```

Example output:

```
  1) test the truth (AssertTestTest)
     test/assert_test_test.exs:5
     ** (ArgumentError) argument error
     stacktrace:
       test/assert_test_test.exs:8
```

Do not know, if it can be fixed on elixir side, or there should exists some notes, how to avoid this error or tips to upgrade to erlang 18.
What do you think about?

Can be, that there are many projects in wild are affected, for example mariaex is one of them:

```
  1) test connection_errors (StartTest)
     test/start_test.exs:4
     ** (ArgumentError) argument error
     stacktrace:
       test/start_test.exs:7
```

**Comment by josevalim** [comment]
I can't reproduce this. My system versions:

```
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
```

**Comment by liveforeverx** [comment]
Can you try Erlang/OTP 17 [erts-6.3], 17.4?? May be it is related to 17.4 only.
I'll check 17.5

**Comment by eksperimental** [comment]
is there any application for mantaining different erlang versions? something in the same fashion as `exevn` ?

**Comment by liveforeverx** [comment]
@eksperimental : I use https://github.com/yrashk/kerl for it.

**Comment by eksperimental** [comment]
@liveforeverx thank you! exactly what I needed

**Comment by liveforeverx** [comment]
@josevalim verified, the 17.5 doesn't have this issue too. Seems, like it 17.4 related(may be before).

**Comment by josevalim** [comment]
It seems to be an erlang bug, there is nothing we can do to work around it. we are emitting proper ast.
