### ISSUE TITLE
Elixir v1.1.0:  Keyword.new with duplicate keys:  *first* wins

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#3803]
Hello all,

Moved to v1.1.0 this morning and just seen this issue:

```elixir
Keyword.new([{:a, 1}, {:a, 2}, {:a, 3}])
```

will give

```elixir
[a: 1]
```

In v1.0.5  I get

```elixir
[a: 3]
```

Checked the 1.1.0 docs and they still say last wins.  Nothing I can find in the release notes.

Just me?

**Comment by josevalim** [comment]
It is a regression, thank you.

**Comment by josevalim** [comment]
Fixed in master and in the v1.1 branch. Thank you!

**Comment by ianrumford** [comment]
yep, just built the branch and works fine!

Thank you so much for the prompt fix; saved me from retreating to v1.0.5
