### ISSUE TITLE
No way to apply `warnings_as_errors` to test files

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#3813]
`mix compile --warnings-as-errors` is handy in CI builds to enforce that no warnings are present.  Unfortunately, I haven't been able to find a way to apply this to test `*.exs` files.  I asked @josevalim about it briefly at elixir conf and he said it should be possible to improve the handling of the option so it is handled more generically and could be used for test files as well, and he asked me to open an issue, so here it is :).

**Comment by lexmag** [comment]
I think it is more complicated issue than just improve options handling – currently `Kernel.ParallelRequire` (which used by `test` task, for example) isn't aware about compilation warnings.

@myronmarston I know, it's not quite the same, but `--warnings-as-errors` option can be specified via `Code.compiler_options(warnings_as_errors: true)` call in Mixfile or test_helper.

**Comment by myronmarston** [comment]
> @myronmarston I know, it's not quite the same, but `--warnings-as-errors` option can be specified via `Code.compiler_options(warnings_as_errors: true)` call in Mixfile or test_helper.

I've tried that (and in fact just tried it again) and I can't get it to work.  Do you have an example you can point me to that's working?

At ElixirConf I paired with @josevalim briefly to see if he could help me figure out a solution for this and he said changes will have to be made to elixir and/or mix first to support this.

For now, I'm using this hacky script in `script/fail_if_any_compile_warnings:

``` ruby
#!/usr/bin/env ruby
# Elixir doesn't easily support `--warnings-as-errors` applied to test files,
# since they are exs files in a directory not generally on the elixirc path.
# There's an open issue to fix this in elixir:
# https://github.com/elixir-lang/elixir/issues/3813
# ...but for now we can get the behavior we want from this script.
warning_lines = []

while line = gets
  # http://rubular.com/r/DXpK0xQGPi
  if (relative_file = line[/^\.*(\w[^:]+):\w+: warning: /, 1])
    warning_lines << line if Dir["apps/*/#{relative_file}"].any?
  end

  puts line
end

exit(0) if warning_lines.none?

puts "\n\nProduced warnings:\n\n"
warning_lines.each { |l| puts l }
exit(1)
```

Then in my build script, I run my tests with:

``` bash
set -o pipefail
mix test 2>&1 | script/fail_if_any_compile_warnings.rb
```

Note that `set -o pipefail` must be there -- if not, the build script will happily pass when there are test failures as long as their are warnings.  `set -o pipefail` ensures that if any command in the pipeline fails the script fails as a whole.

It's definitely a hack, but it's working pretty OK for us.

**Comment by lexmag** [comment]
Sorry, I wasn't clear, we still need to support warnings in `*.exs` files.
`Code.compiler_options/1` is a way to specify `:warnings_as_errors` option for `test` task.

**Comment by lexmag** [comment]
@myronmarston current master (since https://github.com/elixir-lang/elixir/commit/18dd2b140ad00a0b46c65a7d513fe2612f4a8d3c) should work with `Code.compiler_options(warnings_as_errors: true)` is set in test_helper.

**Comment by josevalim** [comment]
@lexmag would it work for elixirc_compiler?

**Comment by josevalim** [comment]
Sorry, poorly phrased question. Should we make it work based on elixirc_compiler options?

**Comment by lexmag** [comment]
It works elixirc_compiler options already, if `Code.compiler_options(warnings_as_errors: true)` is set in Mixfile it won't run tests in case of warnings.

**Comment by josevalim** [comment]
The issue with `Code.compiler_options(warnings_as_errors: true)` in `mix.exs` is that it would also affect dependencies, no? Or do we properly handle this case?

**Comment by josevalim** [comment]
Just checked, it does affect deps too.

**Comment by josevalim** [comment]
So I think setting it in the test_helper is the way to go for now.

**Comment by lexmag** [comment]
No we don't, any warning in the deps files will make compilation to fail.

**Comment by lexmag** [comment]
I've just tried many different ways to run `mix test` with `warnings_as_errors` (CLI, `Code`).
It seems that what we have after `ParallelRequire` patch is already good enough.

**Comment by myronmarston** [comment]
Thanks for addressing this, @lexmag!  I'm really looking forward to Elixir 1.2.

**Comment by lexmag** [comment]
@myronmarston happy to help, and thank you for the report. :yellow_heart:
