### ISSUE TITLE
The default value operator is not documented

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#3815]
I looked through the documentation, and couldn’t find a place where the default value operator `\\` is explained. Using it causes sometimes a lot of confusion, especially to the beginners, so I think it should be documented in the core docs.

The place I would expect to look for it is `Kernel.SpecialForms.\\/2`, because it produces the AST like `{:\\, [], [1, 2]}`. This will also allow to easily lookup the docs in iex with `h \\/2`.

**Comment by whatyouhide** [comment]
:+1:, someone on Slack asked how arities work with `\\` yesterday so we definitely need docs for it.

**Comment by josevalim** [comment]
So `\\` is not really an operator. The same way `<-` and `when` are not operators. They are only forms parsed by the containing macro. So we can't really make them special, we should likely document it on `def`.

**Comment by michalmuskala** [comment]
Anything works for me as long as it is documented - `def` is a good place as well.
