### ISSUE TITLE
Consistent handling of lower-case module names

### ISSUE THREAD

**Issue by rwalker01** [elixir-lang/elixir#3818]
This is an interoperability issue. Erlang is no longer the only language on the BEAM VM since now Elixir, LFE, Joxa, etc. also use the same platform. The goal is that ideally any language should be able to be used to write drop-in replacements for modules and applications written in other BEAM languages. Since module names are basically atoms, then any valid atom allowed by BEAM to be used as a module name should be supported by *any* BEAM language. The issue is not how Elixir can use Erlang modules, or how it is possible for Erlang to use Elixir modules, but instead how it is possible for Elixir to be the implementation language while allowing the module name to be lower-case. For example, if a module called "foo" is written in Erlang and I want to rewrite a drop-in replacement in Elixir, I want to be able to call the module :foo in Elixir and it should work. If instead only capitalized module names are allowed and always prefixed with 'Elixir', then an implementation detail is leaking into the API, where that API should be able to be implemented in any BEAM language (without spending a lot of effort writing wrappers manually).

I see that some of this is already possible, since Elixir will allow this to compile...

    defmodule :foo do

        def sum(n1, n2) do
            n1 + n2
        end
    end

...which results in a "foo.beam" compiled file. Since the compiler allows it, then it's valid, correct? Now if I use foo.beam using Erlang's "erl", it of course only works if I ensure the Elixir standard library is included, e.g "erl -pz ~/path/to/elixir/lib/elixir/ebin/". In that case, Erlang can call an Elixir module as if it were written in Erlang, and Erlang is none-the-wiser. The problem is if I try something like this in "mix":

    mix new foo --module :foo --sup

    ** (Mix) Module name must be a valid Elixir alias (for example: Foo.Bar), got: ":foo"

My point is, so are lower-case module names valid or aren't they? This should be handled consistently. A few strategies come to mind:

* "Only allow capitalized module names, refusing to compile lower-case names." While consistent, the
  downside is that now that this necessitates manual wrapping in order to have drop-in replacements
  between BEAM languages. If that is what is warranted, then this should be stated prominently up-front in the documentation. (Did I overlook it?) I also feel this limits the language from doing something that should inherently be considered valid.
* "Allow any valid atom to be a module name, even lower-case, and mix will now handle this."
  This is my preferred choice.
* "Leave things as they stand right now, but further clarify in documentation the inconsistency."
  I think this will cause confusion because people will try to write code that is only
  half-supported.

**Comment by whatyouhide** [comment]
@rwalker01 for future reference, this kind of discussion belongs to the elixir-core mailing list :) https://groups.google.com/forum/#!forum/elixir-lang-core

**Comment by josevalim** [comment]
Yes, we could change Mix to handle it. The tricky part is, if we generate more than one module, then we start running into weird situations that now we need to generate `:foo_sup` and so on. But yes, it is explicitly supported.

**Comment by ericmj** [comment]
I think it's fine if the task for generating new projects does not handle every possible module name. You can also name modules `:"%&/"` which the task also doesn't support.

**Comment by josevalim** [comment]
That's a good point. Let's keep it simple, thanks @ericmj!
