### ISSUE TITLE
Deriving is broken for Enumerable protocol

### ISSUE THREAD

**Issue by lexmag** [elixir-lang/elixir#3821]
As in v1.1 deriving goes via `Any` and there is no ``Enumerable.Any` available.

**Comment by josevalim** [comment]
You can never derive the Enumerable protocol? Is it a poor error message
issue?

On Friday, October 2, 2015, Aleksei Magusev <notifications@github.com>
wrote:

> As in v1.1 deriving goes via Any and there is no `Enumerable.Any
> available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3821>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by lexmag** [comment]
I've just seen there are several libraries that depends on a fact that Enumerable can be derived for structs (yeah not good, but still). Thus v1.1 is making a breaking change for them. Shouldn't we have a warning at first place?

**Comment by josevalim** [comment]
Ouch, it was an accident that deriving worked before, I don't think we should fix it. Maybe we could update the v1.1 changelog to make it clear but I wouldn't do a code change.

**Comment by lexmag** [comment]
I think an addition to the v1.1 changelog would be enough.

**Comment by ianrumford** [comment]
Hi,

I got caught by this also.

I was following the misleading example in the v0.14.0 release post: http://elixir-lang.org/blog/2014/06/17/elixir-v0-14-0-released/

```elixir
defmodule User do
  @derive [Enumerable]
  defstruct name: "", age: 0
end

Enum.each %User{name: "jose"}, fn {k, v} ->
  IO.puts "Got #{k}: #{v}"
end
```
