### ISSUE TITLE
Consider always consolidating protocols

### ISSUE THREAD

**Issue by chrismccord** [elixir-lang/elixir#3826]

**Comment by josevalim** [comment]
Btw, this is almost ready in master. Can you btw remember what slow down did you see in development?

**Comment by chrismccord** [comment]
Rendering a list of 220 Ecto records in dev on 1.1: 7.5s
Rendering a list of 220 Ecto records in dev on master: 34ms

If there are no odd edge cases, this perf bump in dev is an obvious choice

**Comment by josevalim** [comment]
DONE!

**Comment by chrismccord** [comment]
<3 <3 <3 :clap:
