### ISSUE TITLE
Pattern match with <> operator doesn't recognize that bound variable has size

### ISSUE THREAD

**Issue by MSch** [elixir-lang/elixir#3837]
Since `<>` concatenates two binaries, I would have expected this to work, just like `"fixed_pattern" <> rest = whatever` works, but it doesn't.

```elixir
root = "/home/msch/code"
path = "/home/msch/code/project/some/file.ex"
(^root <> rest) = path
```

```
** (CompileError) iex:7: a binary field without size is only allowed at the end of a binary pattern
```

I've got to do this:

```elixir
root = "/home/msch/code"
path = "/home/msch/code/project/some/file.ex"
root_size = byte_size(root)
<<^root::binary-size(root_size), rest::binary>> = path
```

Is this a bug or an inherent limitation?

**Comment by josevalim** [comment]
We can only fix this if we fix it directly in Erlang because we could not precalculate the size in function clauses where the same issue could happen.
