### ISSUE TITLE
excoveralls misses secondary default parameters in multi-line function parameter list

### ISSUE THREAD

**Issue by sunaku** [elixir-lang/elixir#3847]
Hello,

I'm using Elixir 1.1.1 with Erlang 18.1 and ExCoveralls 0.3.11 under 64-bit Linux.

I get the following coverage map when I run the example code snippets below. :scream:

![selection_138](https://cloud.githubusercontent.com/assets/9863/10326575/c3c83b52-6c51-11e5-80e9-04b5ecfcc55c.png)

My expectation is that the secondary default parameters should be covered because all of their corresponding functions were called by the test case.

Thanks for your consideration. :sweat_smile:

## lib/my_coveralls.ex

```elixir
defmodule MyCoveralls do
  def arg0 do
    :ok
  end

  def arg1(a1 \\ 1) do
    :ok
  end

  def arg2(a1 \\ 1,
           a2 \\ 2) do
    :ok
  end

  def arg3(a1 \\ 1,
           a2 \\ 2,
           a3 \\ 3) do
    :ok
  end
end
```

## test/my_coveralls_test.exs

```elixir
defmodule MyCoverallsTest do
  use ExUnit.Case

  test "method with 0 default arguments" do
    assert MyCoveralls.arg0 == :ok
  end

  test "method with 1 default arguments" do
    assert MyCoveralls.arg1 == :ok
  end

  test "method with 2 default arguments" do
    assert MyCoveralls.arg2 == :ok
  end

  test "method with 3 default arguments" do
    assert MyCoveralls.arg3 == :ok
  end
end
```

**Comment by ericmj** [comment]
It will need to be verified but I think we can fix this by giving the function generated from the default argument the metadata from the `\\` operator.

**Comment by ericmj** [comment]
> My expectation is that the secondary default parameters should be covered because all of their corresponding functions were called by the test case.

Actually for the `arg3` case 3 extra functions are generated, but only one of them is called. If you add calls to all 3 functions (`arg3/0..2`) in your tests the lines will be covered.

I was able to remove the warnings by using the function heads' line for the extra functions we generate for default arguments, but unfortunately it created a new uncovered line for `arg2` which I was unable to fix.

Unfortunately since the cover tool was built for erlang code and not for elixir it is very hard to fix these things (if even possible?). As you have probably already seen many lines are not even reported by the coverage tool. A new cover tool written for elixir needs to be created to fix these issues.

**Comment by josevalim** [comment]
@ericmj should we close this or are you still giving this a try?

**Comment by ericmj** [comment]
@josevalim I can't remove the last uncovered line, lets pair on it though, maybe you know what's going on.

**Comment by josevalim** [comment]
@ericmj can you send a PR for what you have already?

**Comment by ericmj** [comment]
@josevalim https://github.com/elixir-lang/elixir/tree/emj-cover-defaults

Using @sunaku's example code the first line of `arg2` is always uncovered and the weird thing is if I swap places of `arg2` and `arg3` in the source file `arg3` will be uncovered so it has something to do with the order of functions.

**Comment by josevalim** [comment]
Btw, this is going to mess up my big annotations PR, so please don't merge it yet. :D Also, we should check if `arg2/0` will call `arg2/2` call directly or pass through `arg2/1`. If the former, that would explain why lines are not being marked.

**Comment by sunaku** [comment]
FYI - I just wanted to point out that this issue still exists under the latest Elixir 1.2.1 release. :memo:

**Comment by mgartner** [comment]
I'm not sure if this is related, but it looks like coverage is also incorrect for function headers with more than one default argument, even when they are on the same line. For example, the function header here is marked as not covered in this code:

```elixir
@spec add(number, number, number) :: number
def add(num, num2 \\ 2, num3 \\ 3)

def add(num, num2, num3) do
  num + num2 + num3
end

add(1)
```

I'm seeing this on 1.2.5.

**Comment by antipax** [comment]
Does your code actually use all of the arities of the function?

**Comment by josevalim** [comment]
This discussion showed up in the past. It is because implementation wise add(1) calls add(1, 2, 3) directly, so the intermediary one is never called.

**Comment by ericmj** [comment]
We can try to work around issues like this but at the end of the day we will never get it working 100% until a coverage tool is written with Elixir in my mind. The coverage tool for Erlang simply makes assumptions that are not valid for Elixir code.

**Comment by mgartner** [comment]
I see. Why does just `add(1, 2)` get full coverage. Doesn't that end up skipping `add/1`?

**Comment by josevalim** [comment]
After a Skype session with Eric it seems we really can't fix this. There are some incompatibilities with how cover annotates code and how default clauses work.
