### ISSUE TITLE
Add examples to Supervisor module functions

### ISSUE THREAD

**Issue by Havvy** [elixir-lang/elixir#3848]
For each function in Supervisor, add (at least) two examples - one for normal strategies and one for the :simple_one_to_one strategy.

**Comment by josevalim** [comment]
A pull request is welcome. :)

**Comment by Havvy** [comment]
Shouldn't this remain open, so that others (possibly people who are looking for something to contribute to Elixir to get their feet warmed up) can find it? With the labels `App:Elixir`, `Kind:Documentation`, `Level:Starter`?
