### ISSUE TITLE
Include underscore/1 and camelize/1 in the Macro module

### ISSUE THREAD

**Issue by nurugger07** [elixir-lang/elixir#3850]
As per the conversation on the elixir-core mailing list, `underscore/1`, `camelize/1`, & `camelize/2` will be included in the String module.

Example for `underscore/1`:
``` elixir
iex(1)> String.underscore("UpperCamelCase")
"upper_camel_case"

iex(2)> String.underscore("pascalCase")
"pascal_case"
```

Example for `camelize/1`/`camelize/2`:
``` elixir
iex(1)> String.camelize("upper_camel_case")
"UpperCamelCase"

iex(2)> String.camelize("pascal-case", :lower)
"pascalCase"
```

In addition to Unicode characters, ASCII characters must also be accounted for.

**Comment by lexmag** [comment]
I think atom examples are definitely not applicable for `String` module.

**Comment by nurugger07** [comment]
@lexmag I modified the issue and removed the atom examples as well as the module examples.

**Comment by josevalim** [comment]
@ericmj suggested to move those functions to the Macro module, this way, we don't need to support Unicode and we can keep both atom and strings as arguments. It also makes sense from the perspective those operations are not really defined by Unicode and they typically apply to code. So a PR that simply moves those functions to the Macro module is welcome. A couple notes:

1. We won't add `camelize/2`. We can add `uncapitalize/1` to String if someone desires to lowercase only the first argument

2. Those functions should still exists in Mix.Utils, although we need to update the docs to say they are deprecated. Please also add a "# TODO: Deprecate by 1.3" to the functions.

**Comment by nurugger07** [comment]
@josevalim got it :)

**Comment by nurugger07** [comment]
I'll submit the new PR for this later this afternoon.

**Comment by josevalim** [comment]
Awesome. I have updated the title to reflect the changes we actually want in.

**Comment by nurugger07** [comment]
@josevalim there are two cases that the Mix.Utils implementation doesn't cover. One being spaces, and the other being atoms. I think handling spaces is definitely a case but wasn't sure about atoms. Also, do we want to remove the feature from Mix.Utils? I would assume so but wanted to confirm.

**Comment by josevalim** [comment]
Because it exists in the Macro module, it is fine to go with the restriction of no spaces (until someone really needs it). Also, because it is in the Macro module module, we can support strings.

We should not remove the Mix.Utils function though. Just do this:

```elixir
# TODO: Deprecate by 1.3
# TODO: Remove by 1.4
def underscore(value) do
  Macro.underscore(value)
end

...
```

**Comment by nurugger07** [comment]
Cool. Will do :)

**Comment by nurugger07** [comment]
Got the PR together for this issue https://github.com/elixir-lang/elixir/pull/3873

**Comment by josevalim** [comment]
Closing in favor of the PR!
