### ISSUE TITLE
Error installing on Mint

### ISSUE THREAD

**Issue by r0fls** [elixir-lang/elixir#3851]
I get the following error when running the install steps on Mint:

    r0fls@platformpi ~/Desktop/code/elixir $ make clean test
    cd lib/elixir && "/home/r0fls/Desktop/code/elixir/rebar" clean
    /usr/bin/env: escript: No such file or directory
    make: *** [clean] Error 127

This is my specific version:

    Distributor ID:LinuxMint
    Release:17.1
    Codename:rebecca

**Comment by ericmj** [comment]
Looks like erlang is not properly installed. Have you followed the instructions here http://elixir-lang.org/install.html#installing-erlang?
