### ISSUE TITLE
Module.register_attribute doesn't check its options

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#3852]
This call kinda works

```elixir
Module.register_attribute(module, :myattr, [:persistent])
```

for some definitions of "works".

It doesn't generate any errors or warnings, but it doesn't do anything useful either because the correct option name is `:persist`.

**Comment by ericmj** [comment]
We generally don't check for keys we don't expect in options, why should we do it here?

**Comment by alco** [comment]
Because it is a terrible user experience.

**Comment by ericmj** [comment]
That may be, but the discussion shouldn't be around updating `Module.register_attribute/3` - it should be about changing every function in stdlib that takes options. I suggest posting to elixir-lang-core.

**Comment by josevalim** [comment]
Yes, exactly. It is not a localized problem, it is a general one.

**Comment by alco** [comment]
But we agreed in the past that it's not possible to check options in all places. Wouldn't it be better to improve it incrementally instead of dismissing it completely?

**Comment by josevalim** [comment]
Not without a plan. Otherwise we will fix only this one and leave everything else inconsistent.

**Comment by eksperimental** [comment]
A similar situation: https://github.com/elixir-lang/elixir/issues/3808
