### ISSUE TITLE
Dict.size/1 should not work on Lists

### ISSUE THREAD

**Issue by rebelwarrior** [elixir-lang/elixir#3853]
First, The following code should not work but does:

```elixir
Dict.size([1,2,3,4,5,6,7,8,9,0])   #=>10
```
According to Jose Valim Lists are not Dicts so this shouldn't work. The correct use would be with `Enum.count/1`

```elixir
Enum.count([1,2,3,4,5,6,7,8,9,0])   #=>10
```

~~Secondly, since an alias for `Enum.count/1` should be made to `Enum.size/1` to allow for easier discoverability on the documentation, as a search for 'size' will point you to the `Dict.size\1` function.~~

**Comment by josevalim** [comment]
We should not alias `count` to `size`. Size is used when the operation is in constant time.

**Comment by rebelwarrior** [comment]
Good point. But there should be a List.size/1 function somewhere. There is a Dict.size() and a Range.size(). How come no List.size()? Am I missing a reason for it not to exist?

**Comment by hashd** [comment]
Size of a List can't be computed in constant time hence the method `size` doesn't apply for a List.

**Comment by danmarcab** [comment]
It seems `Keyword.size` just does `length(keyword)`, so no constant time in that case

**Comment by rebelwarrior** [comment]
I had not found `lenght()` yet and it works fantastically (plus seems tailor made for lists). A `List.length()` alias would be a good idea for discoverability. Otherwise if you don't know `length()` exist, it's a little hard to find. With it being part of `List`, it would show up on iex when you hit tab.

**Comment by ericmj** [comment]
> It seems Keyword.size just does length(keyword), so no constant time in that case

The common case is constant time, hence the name.

> I had not found lenght() yet and it works fantastically (plus seems tailor made for lists). A List.length() alias would be a good idea for discoverability. Otherwise if you don't know length() exist, it's a little hard to find. With it being part of List, it would show up on iex when you hit tab. It would also be distinct semantically from size or count.

Elixir doesn't alias functions for discoverability. Searching for `length` in the documentation would find it. Learning a language is in part learning its conventions, when you learn the conventions around `length`, `count` and `size` you will have an easy time finding the functions later on.

**Comment by danmarcab** [comment]
I just opened a PR to fix this.
It adds a check to make sure we have a Keyword list when you pass a list to the functions of the `Dict` module.
You can still use some Keyword functions (size) with normal lists tough. Not sure if we want to prevent that as well, what do you think?
