### ISSUE TITLE
Test process is not shutting links down in time

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3854]
See: http://stackoverflow.com/questions/33018952/what-is-the-idiomatic-testing-strategy-for-genservers-in-elixir

@fishcakez any ideas?

**Comment by fishcakez** [comment]
One of these:
* Start/stop the application in setup/on_exit of a test
* Start empty/default supervisor in `setup_all`, start `:temporary` child(ren) under it in `setup` or test, terminate the child(ren) in `on_exit`

**Comment by josevalim** [comment]
@fishcakez I was wondering if we could fix the race condition where named processes are not shut down on time. They do receive the EXIT signal but they act on it too late. For this particular problem, even unregistering them would be enough because they would eventually crash.

I was thinking we could also traverse `Process.info(test_process, :links)` and ensure they are all dead. The issue is that there is no guarantee they all have to shut down. :(

**Comment by ericmj** [comment]
We can trap exits and check if all links in `Process.info(test_process, :links)` are down within some timeframe. If we time out we send `exit(pid, :kill)`. Will `exit/2` block until the process is actually killed?

**Comment by josevalim** [comment]
> Will exit/2 block until the process is actually killed?

No, it won't. The tricky part is that the process may not die at all, so adding a timeframe may make the whole suite slow.

**Comment by fishcakez** [comment]
Sorry, I understood the problem and was suggesting what to do. As far as I am aware things are working to my expectations but likely there is a difference of expectations here.

I don't think it is a bug and I don't think it is not possible to `start_link` from a test process and determine a point where that process or any process it `start_link`s has finished exiting.

Unregistering a process is not good. Registering a process is essentially holding a lock and by unregistering a process (that believes its still registered) multiple process can act as if registered, which is breaking guarantees. Either something else might fail, for example the process owns a listen socket or an ets table or the broken guarantee causes weird consequences/bugs such as concurrent write access to a file. If a process traps exits this behaviour is more likely to occur.

Shutting down linked process is not good. Links can be created for other reasons than atomically with a spawn. For example an application might link to a client process if the client process should exit if an application's process crashes.

If synchronisation is required use a supervision tree. Everything is guaranteed to be stopped if the top level supervisor exits (assuming no brutal killing of supervisors).

Inside a test/setup it is also possible to do something like this, which will block `async: false` tests until the agent process exits.
```elixir
test "my test" do
  {:ok, pid} = Agent.start_link(&Map.new/0)
  on_exit(fn() ->
    ref = Process.monitor(pid)
    receive  do
      {:DOWN, ^ref, _, _, _} -> :ok
    end
  end)
end
```
We could provide a function that wraps this `on_exit/1` call or has the equivalent effect (it would be nice to monitor immediately).

**Comment by josevalim** [comment]
Ok, thanks @fishcakez. I think we should just add `.stop` functions everywhere (GenServer, Agent and Supervisor) and use them in the tests.

**Comment by josevalim** [comment]
stop was added to gen event, gen server, agent... the question is: should we add it to supervisors?

**Comment by fishcakez** [comment]
OTP doesn't provide one directly but I can't think of a reason not. I think its better to provide one that have people use the less clear GenServer,stop on a Supervisor.

Lets remove `terminate/2` here: https://github.com/elixir-lang/elixir/blob/790173e146075fec3c896a059f10075912f1e64a/lib/elixir/lib/agent/server.ex#L46. This race condition no longer occurs.

**Comment by josevalim** [comment]
Done in master!
