### ISSUE TITLE
(Mix) Could not compile dependency idna, /root/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile idna

### ISSUE THREAD

**Issue by edossantos** [elixir-lang/elixir#3857]
mix.exs file 

defmodule Wham.Mixfile do
  use Mix.Project

  def project do
    [app: :wham,
     version: "0.0.1",
     elixir: "~> 1.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type `mix help compile.app` for more information
  def application do
    [mod: {Wham, []},
     applications: [:phoenix, :phoenix_html, :cowboy, :logger,
                    :phoenix_ecto, :postgrex, :maru, :maru_swagger, :tzdata]]
  end

  # Specifies which paths to compile per environment
  defp elixirc_paths(:test), do: ["lib", "web", "test/support"]
  defp elixirc_paths(_),     do: ["lib", "web"]

  # Specifies your project dependencies
  #
  # Type `mix help deps` for examples and options
  defp deps do
    [{:phoenix, "~> 1.0.2"},
     {:phoenix_ecto, "~> 1.1"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.1"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:cowboy, "~> 1.0"},
     {:maru, "~>  0.8.1"},
     {:maru_swagger, "~> 0.5", only: :dev },
     {:comeonin, "~> 1.0"},
     {:timex, "~> 1.0.0-pre"}]
  end
end

**Comment by josevalim** [comment]
@edossantos can you paste all the results from running the "mix" command? Also, please include Erlang and Elixir version (shown when you run `iex`).

**Comment by edossantos** [comment]
***Results from mix:**
mix                 
==> poolboy (compile)
Compiled src/poolboy_worker.erl
Compiled src/poolboy_sup.erl
Compiled src/poolboy.erl
==> decimal
Compiled lib/decimal.ex
Generated decimal app
==> combine
Compiled lib/combine/helpers.ex
Compiled lib/combine/parser_state.ex
Compiled lib/combine.ex
Compiled lib/combine/parsers/binary.ex
Compiled lib/combine/parsers/base.ex
Compiled lib/combine/parsers/text.ex
Generated combine app
==> idna (compile)
Killed
==> wham
** (Mix) Could not compile dependency idna, /root/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile idna

***Erlang and Elixir version***
Eshell V7.0  (abort with ^G)
Interactive Elixir (1.0.5)

Thank you

**Comment by josevalim** [comment]
Can you please let me know what is the result of `$ which rebar || echo "none"` in your terminal?

**Comment by edossantos** [comment]
*$ which rebar || echo "none"*
none

**Comment by josevalim** [comment]
Ah, this is though. I don't know what is wrong, it just says "Killed" for idna. I would try the following:

```bash
$ mix local.rebar
$ rm -rf deps
$ rm -rf _build
$ mix deps.get
$ mix
```

**Comment by edossantos** [comment]
I got the same results after trying the following command:

$ mix local.rebar
$ rm -rf deps
$ rm -rf _build
$ mix deps.get

--
$ mix
==> poolboy (compile)
Compiled src/poolboy_worker.erl
Compiled src/poolboy_sup.erl
Compiled src/poolboy.erl
==> decimal
Compiled lib/decimal.ex
Generated decimal app
==> combine
Compiled lib/combine/helpers.ex
Compiled lib/combine/parser_state.ex
Compiled lib/combine.ex
Compiled lib/combine/parsers/binary.ex
Compiled lib/combine/parsers/base.ex
Compiled lib/combine/parsers/text.ex
Generated combine app
==> idna (compile)
Killed
==> wham
** (Mix) Could not compile dependency idna, /root/.mix/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile idna

**Comment by josevalim** [comment]
Which OS are you using? If it has a package manager, please try installing rebar through the package mangaer.

**Comment by edossantos** [comment]
I'm using Ubuntu 14.04.2 LTS. I will try to instal rebar.

**Comment by edossantos** [comment]
I tried to install rebar by:
`apt-get install rebar`

`$ which rebar             
/usr/bin/rebar`

`$ rm -rf deps`
`$ rm -rf _build`
`$ mix deps.get`
`$ mix`

Got the same error!

**Comment by ericmj** [comment]
Rebar 2.0.0 is over 3 years old. You can install a newer one here https://github.com/rebar/rebar/ or by running `mix local.rebar` and putting `~/.mix` in your PATH.

**Comment by josevalim** [comment]
He already tried with mix local.rebar. :(

I have no idea why it fails, sorry I can't help further. My last suggestion
is to go into deps/idna and run "rebar compile".

If you put the project online, I can try to take a look, but I am assuming
the issue is local to your machine. Another idea is to install a more
recent Erlang (we have one version after yours).


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by edossantos** [comment]
I already tried it with Erlang 18, getting the same error.

./rebar compile
==> idna (compile)
Compiled src/idna_ucs.erl
Compiled src/idna_unicode.erl
Compiled src/idna.erl
Compiled src/punycode.erl

Crash dump is being written to: erl_crash.dump...done
eheap_alloc: Cannot allocate 147852528 bytes of memory (of type "old_heap").
Aborted`

--

erl_crash.dump - https://gist.github.com/edossantos/20df700deb1ad752c3b7

**Comment by josevalim** [comment]
It seems to be running out of memory? In which machine are you compiling it?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by edossantos** [comment]
Yes that's my problem. I'm running it on Digital Ocean server -  512MB Ram/20GB SSD Disk/Ubuntu 15.04 x64..I just tried to run it on my mac and it works great.

**Comment by josevalim** [comment]
You should maybe open up a report on idna and see if they can use less
memory. For example, splitting the data in two different modules or ensure
they are compiled at distinct times.

You can also look at exrm, so you don't need to compile it in production
and rather ship the precompiled thing.

On Saturday, October 10, 2015, Edmilson Dos Santos Jr <
notifications@github.com> wrote:

> Yes that's my problem. I'm running it on Digital Ocean server - 512MB
> Ram/20GB SSD Disk/Ubuntu 15.04 x64..I just tried to run it on my mac and it
> works great.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3857#issuecomment-147123156>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by henrik** [comment]
This bit me too, so I opened a report: https://github.com/benoitc/erlang-idna/issues/8

**Comment by henrik** [comment]
Update: Benoit is having a look :)

**Comment by alexeypetrushin** [comment]
FYI had similar bug on Ubuntu 14 LTE. Elixir 1.2.3, Mix 1.2.3.

It build fine for dev, but when I tried prod it failed.

```
MIX_ENV=prod mix ecto.create
==> poolboy (compile)
ERROR: /apps/redeemer/deps/poolboy/.rebar/erlcinfo file version is incompatible. expected: 1 got: 2
ERROR: compile failed while processing /apps/redeemer/deps/poolboy: rebar_abort
** (Mix) Could not compile dependency :poolboy, "/root/.mix/rebar compile skip_deps=true deps_dir="/apps/redeemer/_build/prod/lib"" command failed. You can recompile this dependency with "mix deps.compile poolboy", update it with "mix deps.update poolboy" or clean it with "mix deps.clean poolboy"
```

Resolved it with this command:

```
$ mix local.rebar
$ rm -rf deps
$ rm -rf _build
$ mix deps.get
$ mix
```

**Comment by josevalim** [comment]
It seems to be related to the rebar version. @devinus, is that file
strictly necessary?



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
That file is not part of the poolboy project, rebar creates it.

**Comment by devinus** [comment]
What @ericmj said.

**Comment by christhekeele** [comment]
FWIW I'm having troubles with this too, also on DigitalOcean.

I figure this belongs on idna too but others may find this thread like I did.

I'm running a Dokku droplet (Ubuntu Dokku v0.5.6 on 14.04) on the smallest plan (512MB) with the [HashNuke buildback](https://github.com/HashNuke/heroku-buildpack-elixir). Everything is out-of-the-box, no custom config.

My deps are:

```elixir
defp deps, do: [
    plug: "~> 1.1.4",
    cowboy: "~> 1.0.4",
    websocket_client: "~> 1.1.0",
    httpoison: "~> 0.8.3",
    exjsx: "~> 3.2.0",
]
```

My logs on `git push dokku` look like:

```
       * MIX_ENV=prod
-----> Using cached Erlang 18.2.1
-----> Installing Erlang 18.2.1

-----> Using cached Elixir v1.2.3
-----> Installing Elixir v1.2.3
-----> Installing Hex
       * creating /app/.mix/archives/hex-0.12.0.ez
-----> Installing rebar
       * creating /app/.mix/rebar
       * creating /app/.mix/rebar3
-----> Fetching app dependencies with mix
      Running dependency resolution
       * Getting httpoison (Hex package)
       Checking package (https://repo.hex.pm/tarballs/httpoison-0.8.3.tar)
       Fetched package
       * Getting exjsx (Hex package)
       Checking package (https://repo.hex.pm/tarballs/exjsx-3.2.0.tar)
       Fetched package
       * Getting jsx (Hex package)
       Checking package (https://repo.hex.pm/tarballs/jsx-2.6.2.tar)
       Fetched package
       * Getting hackney (Hex package)
       Checking package (https://repo.hex.pm/tarballs/hackney-1.6.0.tar)
       Fetched package
       * Getting ssl_verify_fun (Hex package)
       Checking package (https://repo.hex.pm/tarballs/ssl_verify_fun-1.1.0.tar)
       Fetched package
       * Getting mimerl (Hex package)
       Checking package (https://repo.hex.pm/tarballs/mimerl-1.0.2.tar)
       Fetched package
       * Getting metrics (Hex package)
       Checking package (https://repo.hex.pm/tarballs/metrics-1.0.1.tar)
       Fetched package
       * Getting idna (Hex package)
       Checking package (https://repo.hex.pm/tarballs/idna-1.2.0.tar)
       Fetched package
       * Getting certifi (Hex package)
       Checking package (https://repo.hex.pm/tarballs/certifi-0.4.0.tar)
       Fetched package
-----> Copying hex from /app/.mix/archives/hex-0.12.0.ez
-----> Compiling
==> idna (compile)
       Compiled src/idna_ucs.erl
       Compiled src/punycode.erl
       Compiled src/idna.erl
       Compiled src/idna_unicode.erl
       Compiled src/idna_unicode_data2.erl
       Killed
```

**Comment by christhekeele** [comment]
Updating my droplet to use 1GB RAM succeeds.

**Comment by brennan3** [comment]
For what its worth for others, if you have a small droplet on digital ocean, you will get memory issues.  When you do, just compile the dependency directly on its own.  IE,
$> cd deps/idna
$> rebar compile

Running your standard mix deps.compile afterwards should proceed along.  If other deps have issues, just compile them directly as well.  You shouldn't have to upgrade the droplet RAM if you go this route.

**Comment by behrendtio** [comment]
For those of you who wan't to save the money for the upgrade, just [create a swapfile on your droplet](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04). Takes just 1m.

**Comment by ericmj** [comment]
@Chawki726 It is not possible for us to investigate the error without more information. Ideally provide a project we can reproduce in and information such as your elixir and OTP version.

**Comment by Chawki726** [comment]
Its a simple project,creating Identicon  here is the link  https://github.com/Chawki726/identicon-

```
Erlang/OTP 21 [erts-10.1] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.8.0 (compiled with Erlang/OTP 20)
```
Thank you

**Comment by ericmj** [comment]
rebar3 fails to fetch the plugins for the egd dependency. Do you have internet access when you compile your project?

**Comment by Chawki726** [comment]
yeah i have

**Comment by azyzz228** [comment]
Build failed on my cheapest (1 gb ram) VPS (digital ocean droplet in my case).

Per discussions on [Elixirforum](https://elixirforum.com/t/mix-failing-mix-could-not-compile-dependency/34815/3):

1. compiling idna is very expensive, so the VPS quickly hits 100% usage and shuts down (some precaution  measures from DO), so solution is to have more powerful VPS.

OR
2. Add swap space to your VPS (https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04)

Solved the issue for me.
