### ISSUE TITLE
test_mix fails when building git c859e49 

### ISSUE THREAD

**Issue by xadhoom** [elixir-lang/elixir#3859]
Just trying to upgrade from 1.0.1 to master git, compilation goes ok but testing stops at test_mix

Using erlang 18 on a raspberry pi

==> mix (exunit)
.....................

  1) test recompiles after path dependency changes (Mix.UmbrellaTest)
     test/mix/umbrella_test.exs:199
     Assertion with > failed
     code: File.stat!("_build/dev/consolidated/Elixir.Enumerable.beam").mtime() > {{2010, 1, 1}, {0, 0, 0}}
     lhs:  {{2010, 1, 1}, {0, 0, 0}}
     rhs:  {{2010, 1, 1}, {0, 0, 0}}
     stacktrace:
       test/mix/umbrella_test.exs:220: anonymous fn/1 in Mix.UmbrellaTest.test recompiles after path dependency changes/1
       (mix) lib/mix/project.ex:196: Mix.Project.in_project/4
       (elixir) lib/file.ex:1137: File.cd!/2
       test/test_helper.exs:102: MixTest.Case.in_fixture/3
       test/mix/umbrella_test.exs:200

............................................................................................................................................................................................................................................................

Finished in 491.0 seconds (96.8s on load, 394.1s on tests)
274 tests, 1 failure

Randomized with seed 173458
Makefile:94: recipe for target 'test_mix' failed
make: *** [test_mix] Error 1
pi@raspberrypi ~/elixir $ date
sab 10 ott 2015, 23.14.38, CES

**Comment by josevalim** [comment]
@xadhoom from time to time we have timing issues which are made clearer when you are running a specially fast or specially slow machine. :) I will investigate this but you don't need to worry about it, it is a test issue (not a code one). Thank you!
