### ISSUE TITLE
Versioning consolidated directory

### ISSUE THREAD

**Issue by hamann** [elixir-lang/elixir#3864]
We deployed a new release where we upgraded from elixir 1.0* to 1.1.1, but the release crashed on start

```
deploy@app-03:/opt/boldpoker_web » /opt/boldpoker_web/bin/boldpoker_web console
Exec: /opt/boldpoker_web/erts-7.1/bin/erlexec -boot /opt/boldpoker_web/releases/0.0.1/boldpoker_web -boot_var ERTS_LIB_DIR /opt/boldpoker_web/erts-7.1/../lib -env ERL_LIBS /opt/boldpoker_web/lib -config /opt/boldpoker_web/releases/0.0.1/sys.config -pa /opt/boldpoker_web/lib/consolidated -args_file /opt/boldpoker_web/releases/0.0.1/vm.args -user Elixir.IEx.CLI -extra --no-halt +iex -- console
Root: /opt/boldpoker_web
/opt/boldpoker_web
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:24:24] [async-threads:10] [hipe] [kernel-poll:false]


=INFO REPORT==== 12-Oct-2015::17:23:12 ===
    application: logger
    exited: {bad_return,
                {{'Elixir.Logger.App',start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{'Elixir.Access.List',get,
                              [[{strategy,rest_for_one},
                                {name,'Elixir.Logger.Supervisor'}],
                               strategy],
                              []},
                          {'Elixir.Supervisor.Spec',supervise,2,
                              [{file,"lib/supervisor/spec.ex"},{line,161}]},
                          {'Elixir.Supervisor',start_link,2,
                              [{file,"lib/supervisor.ex"},{line,270}]},
                          {'Elixir.Logger.App',start,2,
                              [{file,"lib/logger/app.ex"},{line,26}]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,273}]}]}}}}
    type: permanent

BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
```

After a few hours digging around we found out that `lib/consolidated` contained a `Elixir.Access.beam` left over from a previous deployment with 1.0* which referenced `Elixir.Access.List`. We had to delete it to be able to start the release again.

```
$ strings lib/consolidated/Elixir.Access.beam | grep Elixir.
Elixirjd
Elixir.Access
__struct__,Elixir.Timex.Parsers.ZoneInfo.TransitionInfo"Elixir.Timex.Parsers.ZoneInfo.Zone
Elixir.Timex.DateTime+Elixir.Timex.Parsers.DateFormat.ParserState)Elixir.Timex.Parsers.DateFormat.Directive(Elixir.Timex.Parsers.ZoneInfo.LeapSecond$Elixir.Timex.Parsers.ZoneInfo.Header
Elixir.HashDict
Elixir.Access.Map
Elixir.Access.HashDict
Elixir.Access.Atom
Elixir.Access.List
Elixir.Protocol.UndefinedError	exception
```

Maybe it would help to append a version according to elixir version? (.e.g. consolidated-1.0.0, consolidated-1.1.1..)

**Comment by ericmj** [comment]
We consolidate everything in your load path, not just Elixir, so I don't think it makes sense to version by Elixir version. The same issue can happen when you update protocols in your own project without updating Elixir.

If you want to version your consolidated directory it feels like the release build tool should handle that because that is what will load your code later on also.

**Comment by josevalim** [comment]
@ericmj I think he was proposing to version by the current app version. :)

@hamann in master we have fixed this by ensuring we remove outdated consolidation files. Therefore, I will close this because it no longer exists. However, I think versioning by app version may still be a good idea, although I will wait until we are sure we really need it. Thank you!

**Comment by hamann** [comment]
@josevalim My first idea was to verison by elixir version, but @ericmj is right, that doesn't really make sense. Versioning by app version is probably a better solution. But what's exactly fixed in master? Are you talking about `mix clean`? Because that doesn't help here if you're building a clean release tarball, deploy it to your host and extract it, because old files/versions will (and should) still exist.

**Comment by josevalim** [comment]
Shouldn't this be fixed by the release tool then? :) specially considering that things like umbrellas do not really have versions but releases always have. :)

**Comment by hamann** [comment]
@josevalim Ok, got it. I'll move over to exrm. Thanks for pointing me in the right direction ;)
