### ISSUE TITLE
Path.wildcard unexpected results with UNC

### ISSUE THREAD

**Issue by randyridge** [elixir-lang/elixir#3868]
When using a UNC path I don't get expected results.  File.ls seems to work as does Path.wildcard with a mapped drive to the UNC...  Is this expected behavior?

On windows with Elixir 1.1.1:

iex()> File.ls("//someserver/some/path/to/log/files/")
{:ok, ["1.log", "2.log", "3.log", "4.log"]}
 
iex()> Path.wildcard("//someserver/some/path/to/log/files/*.log")
[]

C:\>net use X: \\someserver\some\path\to\log\files
The command completed successfully.

iex()> Path.wildcard("X:/*.log")
["1.log", "2.log", "3.log", "4.log"]

**Comment by josevalim** [comment]
Thank you. Can you please let me know if the following works?

    :filelib.wildcard '//someserver/some/path/to/log/files/*.log'

Notice the single quotes.

**Comment by randyridge** [comment]
Same unexpected result, I assume this means an issue with the underlying erlang lib and not with elixir...?

iex(1)> :filelib.wildcard '//someserver/some/path/to/log/files/*.log'
[]
iex(2)> :filelib.wildcard 'X:/*.log'
['x:/1.log', 'x:/2.log', 'x:/3.log', 'x:/4.log']

**Comment by josevalim** [comment]
>  Same unexpected result, I assume this means an issue with the underlying erlang lib and not with elixir...?

Yes, exactly. We would need to file a report with Erlang. It should be a similar report to the one you wrote here but using the Erlang shell. Also, does this work?

    :filelib.wildcard '//someserver/some/path/to/log/files/1.log'

If it does, it would help point out if the issue is in the traversal or in the listing of the path.

PS: in the erlang shell you would need to use double quotes instead of single quotes when calling filelib.

**Comment by randyridge** [comment]
Same with path to file:

1> filelib:wildcard("//someserver/some/path/to/log/files/1.log").
[]
2> filelib:wildcard("X:/1.log").
["x:/1.log"]

I'll file an issue over at erlang and see if I can figure out what's happening to issue them pull request.

Thanks!

**Comment by josevalim** [comment]
Awesome, thank you! Good luck!
