### ISSUE TITLE
Proposal: "OTP Page" in Extras Docs

### ISSUE THREAD

**Issue by Havvy** [elixir-lang/elixir#3869]
I am proposing adding a page to the "Pages" section of the Elixir API docs a page detailing how OTP works in a reference manner. As part of the API docs it would point to the documentation of individual components (GenServer, Supervisor, etc.) as needed. As this is reference material, the documentation will be given in reference format, not in tutorial format like in the Getting Started Guide.

Its purpose would be to explain common conventions (e.g. `start` and `start_link`), list the common OTP things (`GenServer`, `Supervisor`, etc.) explaining their role in how OTP works, the rationale behind the OTP framework, how to name components, and how`:via` works (directly pulled out of `GenServer` so that `GenServer` can be only about `GenServer`). Also possibly commonalities like termination and code changing.

The use case I want to solve is for users who have questions about OTP to have a common starting point.

Note that I would be writing the initial doc, and would also try to keep it updated.

**Comment by josevalim** [comment]
I think this can work. Today GenServer kind of became the place where we put all this information and all others just link to GenServer docs. If the goal of the OTP page is to list the main principles and reference the main behaviours, it could be quite interesting. @elixir-lang/elixir, what is your take on this?

**Comment by fishcakez** [comment]
I am unsure where we are drawing the line regarding what OTP means. This is just OTP processes?

**Comment by Havvy** [comment]
This is just OTP processes. We're not talking about the entire Erlang distribution here - though I'd have a paragraph specifically saying that "OTP" is also used for that, but that is is not what is discussed.

**Comment by fishcakez** [comment]
:+1:

**Comment by josevalim** [comment]
Thank you @Havvy! I am closing this issue as we tidy up the issues tracker for upcoming releases. We are waiting for your contribution on this!

**Comment by Havvy** [comment]
Kk; Will get a preliminary PR up tonight. (PST)

**Comment by Havvy** [comment]
Or not. Way too tired. :/
