### ISSUE TITLE
Make arguments of command optional in `System.cmd`

### ISSUE THREAD

**Issue by jingweno** [elixir-lang/elixir#3879]
Executing a shell command that doesn't take any argument requires an empty list:

```
> System.cmd "date"
** (UndefinedFunctionError) undefined function: System.cmd/1
    (elixir) System.cmd("date")
> System.cmd "date", []
{"Sat Oct 17 12:54:50 PDT 2015\n", 0}
```

I wonder whether [`args` in System.cmd should be optional](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/system.ex#L428) (defaulting to an empty list) so that the following would work:

```
> System.cmd "date"
{"Sat Oct 17 12:54:50 PDT 2015\n", 0}
```

**Comment by josevalim** [comment]
I am :-1: to be a bit clearer on how the arguments are passed. Folks are often trying to pass whole expression on the first argument which won't work. Thank you though!
