### ISSUE TITLE
Raise clear error message when module tries to require itself

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3881]
It would happen in cases like this:

```elixir
defmodule MyApp do
  defmodule Supervisor do
    require Supervisor
  end
end
```

The inner module redefined `Supervisor` and we want to invoke the `Supervisor` at Elixir's root. The current error message is confusing and we could make it clearer for this particular case.

**Comment by hubertlepicki** [comment]
So I think this error message is being raised from here:
https://github.com/elixir-lang/elixir/blob/77f2558cf59dac25371dd5d3aff7ab7604ca4ac1/lib/elixir/src/elixir_aliases.erl#L143

@josevalim is there a use case where current message is OK? Or it should be changed for all use cases to something like:

    It looks like you are trying to require module Supervisor from module Supervisor. Try requiring module Supervisor from other modules instead.

?
