### ISSUE TITLE
Raise if more than one of branch | ref | tag is given to git deps

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3885]

**Comment by hubertlepicki** [comment]
Looks like another fairly easy one I could catch in my free time...

Anyway, I think we could make it even more stricker and only allow stuff that makes sense for dependency resolution. I think there are main 2 cases:

1. You should only specify *one of*: branch, ref or tag
2. You should only specify it once

Currently I think dependency resolution silently swallows both cases, and you can't even tell what it installed. Makes sense, @josevalim ?

**Comment by josevalim** [comment]
That would be awesome. Your rules are correct. We just need to do something here: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/scm/git.ex#L30 (and two lines below)

Let's go with a warning for now (Mix.shell.error) because we don't want to break people code. Leave it as a todo for us to make it raise. :)
