### ISSUE TITLE
a macro cannot call a private method within the same module while it can call a public one

### ISSUE THREAD

**Issue by leiyangyou** [elixir-lang/elixir#3887]
There is some slight inconsistency in the call semantic within macros

example

``` elixir
defmodule MacroTest do
   defmacro macro_call_private do
       quote do
             private_method
       end
   end
   defmacro macro_call_public do
      quote do
             public_method
      end
   end
end
```

macro_call_private will not pass compilation whilst macro_call_public will

**Comment by josevalim** [comment]
It is not inconsistent. :) The macro is going to expand code in the caller, which means it will never be able to see the private functions defined in `MacroTest`.

**Comment by leiyangyou** [comment]
however, calling public_method directly still works within macro_call_public, so it's somehow able to infer the that defining module is MacroTest.

In my opinion, it should be the case that either

1) both calls fail on compilation
or
2) both works

otherwise the behavior seems inconsistent

**Comment by josevalim** [comment]
It probably only works because you are importing `MacroTest` into the caller, which will bring all public functions but none of the private ones. It is hard to say because your example is not complete.

**Comment by leiyangyou** [comment]
Thanks @josevalim, that explains it :)
