### ISSUE TITLE
Implementation of Enumerable for File.Stream with :bytes option is broken.

### ISSUE THREAD

**Issue by sumerman** [elixir-lang/elixir#3888]
```Elixir
iex(1)> stream = File.stream! "tmp", [], :bytes
%File.Stream{line_or_bytes: :bytes, modes: [:raw, :read_ahead, :binary],
 path: "tmp", raw: true}
iex(2)> [<<1>>, <<2>>] |> Enum.into(stream)
%File.Stream{line_or_bytes: :bytes, modes: [:raw, :read_ahead, :binary],
 path: "tmp", raw: true}
iex(3)> stream |> Enum.into(<<>>)
** (IO.StreamError) error during streaming: bad argument
    (elixir) lib/io.ex:415: IO.each_binstream/2
    (elixir) lib/stream.ex:1092: Stream.do_resource/5
    (elixir) lib/enum.ex:1391: Enum.reduce/3
    (elixir) lib/enum.ex:984: Enum.into/4
```

As far as I can see `Enum.reduce/3` eventually delegates to `IO.each_binstream/2` which in turn calls `binread(file, :bytes)` which is obviously wrong. If stream mode is `:bytes` then `reduce/3` implementation must call `each_binstream/2` with a number of bytes, not the atom `:bytes`. (Same goes for `each_stream/2`).

Described above may be enough for the quick fix, but overall using IO.read/binread for byte streaming feels wrong, because they are supposed to operate on characters.

**Comment by josevalim** [comment]
You don't pass `:bytes`, but rather the amount of bytes you want to read. From the docs:

    # Read in 2048 byte chunks rather than lines
    File.stream!("./test/test.data", [], 2048)

**Comment by sumerman** [comment]
OK, my bad :)  Sorry for disturbance. Maybe some guards on `File.stream!` may guide idiots like me :)

**Comment by josevalim** [comment]
@sumerman that's a great idea. A PR would be welcome!
