### ISSUE TITLE
One test randomly (?) fails (locally and on travis ci)

### ISSUE THREAD

**Issue by hubertlepicki** [elixir-lang/elixir#3892]
This happens for at least a few days now, on master. Not exactly a bug that affects end users but something that has to be fixed at some point anyway, so I'm leaving it here for now.

      1) test recompiles after path dependency changes (Mix.UmbrellaTest)
         test/mix/umbrella_test.exs:199
         Assertion with > failed
         code: File.stat!("_build/dev/consolidated/Elixir.Enumerable.beam").mtime() > {{2010, 1, 1}, {0, 0, 0}}
         lhs:  {{2010, 1, 1}, {0, 0, 0}}
         rhs:  {{2010, 1, 1}, {0, 0, 0}}
         stacktrace:
           test/mix/umbrella_test.exs:227: anonymous fn/1 in Mix.UmbrellaTest.test recompiles after path dependency changes/1
           (mix) lib/mix/project.ex:196: Mix.Project.in_project/4
           (elixir) lib/file.ex:1137: File.cd!/2
           test/test_helper.exs:102: MixTest.Case.in_fixture/3
           test/mix/umbrella_test.exs:200
    ........
    Finished in 41.2 seconds (4.8s on load, 36.3s on tests)
    272 tests, 1 failure

**Comment by josevalim** [comment]
Yes, it is a file system race condition, since we need to rely on mtimes to know when things are compiled. It is quite annoying and I can't reproduce it on my machine anymore, which makes it harder to fix.

**Comment by hubertlepicki** [comment]
Happens to me almost every other time. Possibly Linux or Linux + SSD issue...

**Comment by josevalim** [comment]
Hopefully fixed forever now.
