### ISSUE TITLE
`Macro.to_string/1` format for bitstring is inconsistent with `Kernel.inspect/1`

### ISSUE THREAD

**Issue by lexmag** [elixir-lang/elixir#3898]
```elixir
iex(1)> Macro.to_string(quote(do: <<1::size(2)>>)) 
"<<1 :: size(2)>>"
iex(2)> inspect <<1::size(2)>>  
"<<1::size(2)>>"
```

**Comment by ericmj** [comment]
`Macro.to_string` and `Kernel.inspect` will have different output for non-literals, that's expected. The reason for this difference is because `Macro.to_string` adds spaces around binary operators (`::` is an operator). To illustrate:

```elixir
iex(1)> Macro.to_string(quote(do: <<1+size(2)>>)) 
"<<1 + size(2)>>"
```

I would say this is not a bug.

**Comment by lexmag** [comment]
Actually it adds spaces around any of `@binary_ops`:
```elixir
iex(1)> Macro.to_string(quote(do: <<1::unit(1)-size(2)-integer>>))
"<<1 :: unit(1) - size(2) - integer>>"
```

**Comment by lexmag** [comment]
I think it might be considered as a bug since `Macro.to_string` is frequently used in the error messages.

**Comment by ericmj** [comment]
> Actually it adds spaces around any operator in @binary_ops

Yes, that's what I am saying, the current behaviour is consistent with all other operators. Why should `::` be special handled? Also consider that `::` is used in typespecs where we want the spaces.

> I think it might be considered as a bug since Macro.to_string is frequently used in the error messages.

Why is extra spaces in error messages bad? Can you show an example where it makes the error message wrong or confusing?

**Comment by josevalim** [comment]
I think we should fix binaries in Macro.to_string to mirror inspect and the conventions in the Elixir codebase since <<>> is a special form. We can assume it has a certain shape.

**Comment by ericmj** [comment]
I would prefer if the AST had a consistent shape in `Macro.to_string`, even if it's a special form it can be used with macros.

**Comment by lexmag** [comment]
> Why is extra spaces in error messages bad? Can you show an example where it makes the error message wrong or confusing?

I'm pretty sure extra spaces don't bring any confusing, it's only about consistency and unified style (are important properties IMO).

**Comment by ericmj** [comment]
We are trading consistency in one place for inconsistency in another.

**Comment by lexmag** [comment]
We're already moving to the consistency first I think: https://github.com/elixir-lang/elixir/commit/0ce1c441d548d670eaa1bb79c974d7c1ea0f9e65.

**Comment by ericmj** [comment]
I am :-1 on that too. There are lots of this like this, for example:

```elixir
iex(1)> quote do defmodule Foo do end end |> Macro.to_string |> IO.puts
defmodule(Foo) do
  nil
end
:ok
```

**Comment by josevalim** [comment]
> We are trading consistency in one place for inconsistency in another.

I disagree. We are making everything more consistent altogether. We don't write all binary operators the same way, why would we `Macro.to_string` them all the same way?

**Comment by lexmag** [comment]
I think if there were an `inspect` for `defmodule Foo` it would be consistent with `Macro.to_string`.
As @josevalim said – just singe consistency.

**Comment by ericmj** [comment]
> I disagree. We are making everything more consistent altogether. We don't write all binary operators the same way, why would we Macro.to_string them all the same way?

We can't foresee how operators will be used in macros so we cannot say it will always be consistent.

**Comment by josevalim** [comment]
We can in our special forms though! I know we like recursion but I am pretty sure we are going in loops here.

**Comment by josevalim** [comment]
Ping @lexmag. :)
