### ISSUE TITLE
Introduce with

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#3902]
`with` is `for`'s younger brother. Imagine we have two functions:

```elixir
def ok(x), do: {:ok, x}
def error(x), do: {:error, x}
```

While `for` is used to match on values out of a collection:

```elixir
for {:ok, x} <- [ok(1), error(2), ok(3)], do: x
#=> [1, 3]
```

`with` is used to match on values directly:

```elixir
with {:ok, x} <- ok(1),
     {:ok, y} <- ok(2),
     do: {:ok, x + y}
#=> {:ok, 3}
```

Because all values matched, the `do` block was executed, returning its result. If a value does not match, it will abort the chain:

```elixir
with {:ok, x} <- ok(1),
     {:ok, y} <- error(2),
     do: {:ok, x + y}
#=> {:error, 2}
```

Since `error(2)` did not match `{:ok, y}`, the `with` chain aborted, returning `{:error, 2}`. 

There are many different scenarios on every day Elixir code that we can use `with`. For example, it is useful to avoid nesting "case"s:

```elixir
case File.read(path) do
  {:ok, binary} ->
    case :beam_lib.chunks(binary, :abstract_code) do
      {:ok, data} ->
        {:ok, wrap(data)}
      error ->
        error
    end
  error ->
    error
end
```

Can now be rewritten as:

```elixir
with {:ok, binary} <- File.read(path),
     {:ok, data} <- :beam_lib.chunks(binary, :abstract_code),
     do: {:ok, wrap(data)}
```

Another example is Plug itself. Plug will only call the next plug if the `:halted` field in the connection is false. Therefore a whole plug pipeline can be written as:

```elixir
with %{halted: false} = conn <- plug1(conn, opts1),
     %{halted: false} = conn <- plug2(conn, opts2),
     %{halted: false} = conn <- plug3(conn, opts3),
     do: conn
```

If any of them does not match, because `:halted` is true, the pipeline is aborted.

Similarly to `for`, variables bound inside `with` won't leak. Also similar to `for`, `with` allows "bare expressions". For example, imagine you need to calculate a value before calling the next match, you may write:

```elixir
with {:ok, binary} <- File.read(path),
     header = parse_header(binary),
     {:ok, data} <- :beam_lib.chunks(header, :abstract_code),
     do: {:ok, wrap(data)}
```

**Comment by josevalim** [comment]
Full proposal: https://gist.github.com/josevalim/8130b19eb62706e1ab37

**Comment by liveforeverx** [comment]
Error monad build-in! Great! :+1: :+1: :+1: :heart: :green_heart: :yellow_heart: :blue_heart:
