### ISSUE TITLE
add new label: won't fix - won't fix for the time being

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3904]
hi @josevalim
Could we add a "Won't fix ever/for the time being" label, just as a way to keep track of features that will not be fixed and also of those that will not be added in the near future but could make it in, in the future.

this is one example
~~https://github.com/elixir-lang/elixir/issues/3612#event-443678582~~ https://github.com/elixir-lang/elixir/issues/3624#event-443677345
and i have seen many more issues that have been closed and they are dug somewhere in the list 3k issues in the list.

also it is a good place referer to people before doing a feature request.

**Comment by eksperimental** [comment]
another name for "won't fix for the time being"  could be "won't be implemented for the time being"

**Comment by eksperimental** [comment]
the example that i actually wanted to link to was: https://github.com/elixir-lang/elixir/issues/3624#event-443677345

**Comment by josevalim** [comment]
I am :-1: on this. Our labels are for classifying the issues before they are acted on, before they are closed, and "won't fix" is a closing reason.
