### ISSUE TITLE
List of lines longer than 100 chars

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#3913]
I wrote a command to list all the files containing lines longer than 100 chars 
at this commit in history: 62f0f2a528ce5aa3232fe0e5f517a6a90851ec71

its 134 files out of 438 files in total (the ones with valid extension),
and a total of 547 offending lines.

```sh
# list just the file and the line_no
ag -g '\.(bat|config|eex|erl|ex|exs|hrl|script|src|xrl|yrl)' | xargs -L1 awk 'length > 100 {print length ":" FILENAME ":" FNR}' | sort -t: -k1rn,1 -k2,2 -k3n,3 > ../elixir_long_lines.file_line_no

# include the offending line
ag -g '\.(bat|config|eex|erl|ex|exs|hrl|script|src|xrl|yrl)' | xargs -L1 awk 'length > 100 {print length ":" FILENAME ":" FNR "#" $0}' | sort -t: -k1rn,1 -k2,2 -k3n,3 | sed -e "s/#/\n#/" > ../elixir_long_lines.full
```

the results can be found:
* file:line_no: https://gist.github.com/eksperimental/9116cd5d8601689b2c50
* file:line_no + offending line:  https://gist.github.com/eksperimental/7cb13df2609dfb4aee40

the first column contains the length of the offending line

@josevalim I'm leaving it here as reference in case you want to do something about it.

**Comment by ericmj** [comment]
Thank you for this but we are trying to avoid superficial changes. Additionally we have no guidelines on max line length, lines are terminated where the developers feel is best.

**Comment by eksperimental** [comment]
No worries, my idea was just to expose this issue.

Keep in mind that over 180 lines are longer than 113 chars (which is the limit in my screen and probably of the other many contributors).

While I understand some lines cannot fit in that length, I see that many of them can be split.
for example there are 83 asserts in the list using `==` that could be easily broken into two lines.

I wouldn't underestimate breaking lines into an acceptable size as superficial changes,
they are improving the quality of the code into a more readable one.
I would say that these lines are more susceptible to contain bugs/typos and to remain undetected longer that the in the rest of the lines. since less eyes will be looking at it.

just to give an example, this bug that I found yesterday, I wouldn't have found it had it been out of the reach of my screen. 
https://github.com/elixir-lang/elixir/pull/3112#discussion-diff-42950249

but as I said earlier: I'm leaving it here as reference in case you guys want to do something about it.
