### ISSUE TITLE
assigning enormous data to a variable makes IEx slow and could result in crash

### ISSUE THREAD

**Issue by 287278** [elixir-lang/elixir#3914]
```
Erlang/OTP 18 [erts-7.1] [source-2882b0c] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.1.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> q = 1..1000 |> Enum.map fn _ -> Enum.to_list 1..30000  end ; :ok
:ok
iex(2)> 1
1
iex(3)> 1
1
iex(4)> 1

Crash dump is being written to: erl_crash.dump...done
eheap_alloc: Cannot allocate 790960704 bytes of memory (of type "heap").
Aborted (core dumped)
```
each ```1``` took about a second to evaluate

**Comment by killme2008** [comment]
IEx kept the `q` in memory for your later usage.The long list bound to `q` consume too much memory and may be crash if you don't have enough memory in your machine.(In my machine, it doesn't crash but slow.)

 if you bind `q` to another value such as `q=1`, the IEx is fast again.Garbage collector  would free the long list that was bound to `q`.

I don't think this is an issue.

**Comment by lexmag** [comment]
You can observe this behaviour in the Erlang shell as well:
```erlang
Eshell V7.1  (abort with ^G)
1> Q = lists:seq(1, 100000000). 
[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
 23,24,25,26,27,28,29|...]
2> 1. % <= slow
1
3> 1. % <= slow
1
4> f(Q).
ok
5> 1. % <= fast
1
6> 1. % <= fast
```
As @killme2008 said, it is a session keeping huge `Q` data structure in the state, I assume there is a copying of that `Q` happening what makes next call slow.

**Comment by ericmj** [comment]
It's because all variables in the shell are sent to the evaluator process on each evaluation. This is probably done for a reason but it might be worth investigating if the state can be kept in the evaluator process instead of sending it every time.

**Comment by antipax** [comment]
Hi, I'm going to give this a shot.

(Tried to ask about this on IRC first to get some discussion going, but no one replied so just wanted to put this here as well.) It seems like the main reason the state is passed back to the server from the evaluator is to keep track of the counter and the shell prefix. There's also a peek_env message which uses the state env, but that could be stored in the evaluator. My idea would be to split the state into 2 separate structs, one of which is only in the evaluator and one which is still passed back and forth on each evaluation contains the counter and prefix. If the evaluator dies, the state is currently reset anyway, so the server doesn't really need to hang onto the big parts of the state.

**Comment by antipax** [comment]
Chatted with @lexmag and it sounds like this is a good approach, so moving forward.
