### ISSUE TITLE
Typespecs do not support variable sized tuples of a single homogenous type

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#3924]
I may be reading the [typespec docs](http://elixir-lang.org/docs/v1.1/elixir/Kernel.Typespec.html) incorrectly, but it appears that they only allow you to specify tuples in one of two ways:

* A fixed-size tuple with known types for each position (typespec: `{ atom, String.t }`).
* Just a tuple with no other information about size or the types of the values in the tuple (typespec: `tuple`)

The first typespec form nicely handles the most common usage of tuples: fixed size heterogenous collections (such as a key/value pair in a map.  That's not the only form tuples take, though.  I've got a case where I have a variable-length collection of a particular type of struct.  Usually lists are used for these, and indeed I am using a list to build the collection in the "building" part of my system, but I later convert it to a tuple for use in the "query" part of my system.  Using a tuple has some nice advantages over a list for this part of the system -- namely that provides constant time access to any value in my collection.  I would like to be able to specify in a typespec that a function returns a variable-sized tuple of my struct type.  For lists I can do `[%MyStruct{}]` and that works but for a tuple I believe `{ %MyStruct{} }` id understood to be a tuple of exactly one element.  For now I am using `{}` in my type spec as it seems to be the only thing I can use but I would like to be able to specify more detail.

Could the typespec system be improved to allow us to specify variable sized tuples of a single homogenous type?

**Comment by josevalim** [comment]
I think `{}` is an empty tuple, you should use `tuple`. Other than that, typespecs are provided by dialyzer which ships with Erlang, we cannot add new types directly, they must be added to dialyzer (and we would get them for free, no change in Elixir required). Also, please remember to use the core mailing list for discussing/proposing new features! Thank you! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by myronmarston** [comment]
> Also, please remember to use the core mailing list for discussing/proposing new features! Thank you!

To be honest, it's hard for me to tell what's best suited for the mailing list vs here.  Last time I had an issue I [asked on the mailing list](https://groups.google.com/forum/#!topic/elixir-lang-core/nDM6DfEQv2o) and you asked to move discussion to an issue -- which I took to mean I should have opened that as an issue in the first place.  So this time I opened it here.

**Comment by josevalim** [comment]
Oops, sorry for not being clear. The plan is exactly to always start them in the mailing list and "graduate" them to the issues tracker once we agree they should be part of the language. The rationale is to keep the issues tracker on actionable items and allow the community to help with filtering them. For example, many could have pointed out that we simply rely on dialyzer and it wouldn't take time from the few of us Elixir maintainers to do it. :)

**Comment by myronmarston** [comment]
Thanks for clarifying.  Now I get it :).

**Comment by myronmarston** [comment]
Gonna close this.  I don't have the time or desire to pursue the change in dialyzer.
