### ISSUE TITLE
can't build v1.1.1 under musl (instead of glibc)

### ISSUE THREAD

**Issue by sunaku** [elixir-lang/elixir#3925]
Elixir v1.1.1 failed to build under the following architectures: :scream:

* [ARCH=x86_64-musl BOOTSTRAP=x86_64-musl](https://travis-ci.org/voidlinux/void-packages/jobs/88003195)
* [ARCH=armv7hf-musl BOOTSTRAP=x86_64-musl](https://travis-ci.org/voidlinux/void-packages/jobs/88003196)
* [ARCH=armv6hf-musl BOOTSTRAP=x86_64-musl](https://travis-ci.org/voidlinux/void-packages/jobs/88003197)

[See here](https://travis-ci.org/voidlinux/void-packages/builds/88003189) for all build logs. :cry:   Thanks for your consideration. :sweat_smile:

**Comment by josevalim** [comment]
It seems to be just a version issue: https://travis-ci.org/voidlinux/void-packages/jobs/88003195#L398

The error says "At least Erlang 17.0 is required to build Elixir". Please let me know what is returned by the following command [seen here](https://github.com/elixir-lang/elixir/blob/v1.1/Makefile#L23):

    erl -noshell -eval 'io:fwrite("~s", [erlang:system_info(otp_release)])' -s erlang halt

All in all, it points to be an Erlang poorly configured or installed.

**Comment by sunaku** [comment]
Thanks @josevalim! :smiley_cat: Perhaps @Duncaen can comment further on this matter? :pray:

**Comment by Duncaen** [comment]
I guess its some problem with multiple build jobs or related to travis, locally i can build it for armv7hf-musl without problems.
The installed Erlang version is 18 and all requiered binaries are in the path.
