### ISSUE TITLE
Misleading documentation for Enum.all? and Enum.any?

### ISSUE THREAD

**Issue by oguizol** [elixir-lang/elixir#3927]
Enum.all? documentation is as follow: "Invokes the given fun for each item in the collection and returns false if at least one invocation returns false or nil. Otherwise returns true."

By looking at the code, it does not seem that documentation and implementation are inlined.
The implementation actually stop execution whenever the function (in parameter) call returns false.

Same issue with Enum.any?

**Comment by eksperimental** [comment]
the functions will return false with the expression in the `if` conditional does not evaluate to a truthy value (ie. false or nil)
https://github.com/elixir-lang/elixir/blob/40c70ffcfabfd9547b012bfceaeeac4d1c047e86/lib/elixir/lib/enum.ex#L241
https://github.com/elixir-lang/elixir/blob/40c70ffcfabfd9547b012bfceaeeac4d1c047e86/lib/elixir/lib/enum.ex#L2397

this code shows that it works as expected.

```elixir
iex(10)> list = [true, nil, true]
[true, nil, true]
iex(11)> stream = Stream.map(list, &(&1))
#Stream<[enum: [true, nil, true],
 funs: [#Function<39.75604590/1 in Stream.map/2>]]>
iex(12)> Enum.all? list
false
iex(13)> Enum.all? stream
false
```

do you have a case where it doesn't?

**Comment by Gazler** [comment]
I think @oguizol is suggesting that this part is misleading as the `all?` function halts execution when it encounters a `false` or `nil`

 > Invokes the given fun for each item in the collection

    iex(14)> f1 = fn -> (IO.puts "1") end
    #Function<20.54118792/0 in :erl_eval.expr/5>
    iex(15)> f2 = fn -> (false) end      
    #Function<20.54118792/0 in :erl_eval.expr/5>
    iex(16)> f3 = fn -> (IO.puts "3") end 
    #Function<20.54118792/0 in :erl_eval.expr/5>
    iex(17)> Enum.all?([f1, f2, f3], &(&1.()))   
    1
    false

Expected output based on the docs would be:

    1
    3
    false

I think this could be fixed by documenting that the function stops when it encounters a `false` or `nil.

**Comment by oguizol** [comment]
That is exactly what I meant :)

**Comment by josevalim** [comment]
Yes, we need to improve the docs! PR please?



-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by eksperimental** [comment]
@Gazler I see what you mean.

**Comment by oguizol** [comment]
@josevalim I'll be glad to make my first PR to the project :)
