### ISSUE TITLE
Controller generated by generator needs more comments

### ISSUE THREAD

**Issue by edmz** [elixir-lang/elixir#3929]
I understand that the code generated by the controllers are a learning tool. I think this is great!

That said, I just generated a model and noticed that, at least for the controller, there are no comments in the controller. For a learning tool I think it could be better.

I think that the controller at least, could be more commented and thus explain or teach a bit more what is happening.

(If this is something that you want to do, I can help in this regard).

**Comment by josevalim** [comment]
Did you mean to open this issue on Phoenix?

**Comment by josevalim** [comment]
It also worth pointing out the model has documentation because it is considered an API of your application. the controller is simply callbacks and we typically do not document those. :)

**Comment by edmz** [comment]
Yes, I don't know what glue I was sniffing. Sorry.
