### ISSUE TITLE
Inconsistent pluralization of method names in IO

### ISSUE THREAD

**Issue by mayppong** [elixir-lang/elixir#3933]
Not super important but I thought I should bring it up. The IO methods have strange naming scheme. Some are pluralize: `puts`, `gets`
Some aren't: `inspect`, `write`

What was the reason behind this? Would you consider create aliases for them to make them the same?

**Comment by whatyouhide** [comment]
@mayppong `puts` and `gets` aren't plurals or 3rd forms, they're just abbreviations of "put string" and "get string".

**Comment by josevalim** [comment]
@whatyouhide is correct. :)

**Comment by mayppong** [comment]
Thanks!
