### ISSUE TITLE
Mix fails to read rebar3 git deps

### ISSUE THREAD

**Issue by zyro** [elixir-lang/elixir#3936]
Trying to add [a project](https://github.com/shopgun/turtle) as a dependency to my Mix app results in this error:
```
** (Protocol.UndefinedError) protocol String.Chars not implemented for {:git, 'https://github.com/basho/lager', {:tag, '3.0.1'}}
    (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
    (mix) lib/mix/rebar.ex:122: Mix.Rebar.compile_req/1
    (mix) lib/mix/rebar.ex:88: Mix.Rebar.parse_dep/2
    (elixir) lib/enum.ex:977: anonymous fn/3 in Enum.map/2
    (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:977: Enum.map/2
    (mix) lib/mix/dep/loader.ex:250: anonymous fn/2 in Mix.Dep.Loader.rebar_children/1
```

Is there additional configuration required, either in my application or the library I'm trying to use, or is this an issue with Mix?

**Comment by josevalim** [comment]
@zyro which Elixir version? In any case, Elixir does not officially support Rebar 3 packages yet.

**Comment by zyro** [comment]
I've tried both Elixir 1.0.5 and 1.1.1, I get the same result with both.

**Comment by aerosol** [comment]
@zyro it looks like you need double quotes to get this further, `'https://github.com/basho/lager'` is a list, not a binary string, and this is where you crash comes from

**Comment by zyro** [comment]
@aerosol I believe the issue is [here](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/rebar.ex#L123), trying to `to_string` the whole tuple you see at the top of the stack trace.

Looks like it expects version numbers only for dependency definitions, like [this one](https://github.com/shopgun/turtle/blob/master/rebar.config#L10) in the same config.

**Comment by josevalim** [comment]
Yes, we don't support Rebar 3 at all. there is already a pull request for it. Even if this worked, we would fail on the `ampq_client` dependency. You can try the PR... other than that, you will need to wait or fork the project and pass the dependencies in a format it makes sense for Mix.
