### ISSUE TITLE
(UndefinedFunctionError) undefined function: :crypto.hash/2 (module :crypto is not available)

### ISSUE THREAD

**Issue by czepluch** [elixir-lang/elixir#3939]
Okay, so I am trying to use :crypto within an elixir mix project. It's weird, because :crypto works fine if I just use it directly in iex, but as soon as I use the exact same function in a mix project it fails like this:

```
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Crypto.hash('hello')

18:47:01.491 [error] Unable to load crypto library. Failed with error:
":load_failed, Failed to load NIF library: '/home/czepluch/Dropbox/prgrms/elixir/crypto/_build/dev/lib/crypto/priv/lib/crypto.so: cannot open shared object file: No such file or directory'"
OpenSSL might not be installed on this system.

** (UndefinedFunctionError) undefined function: :crypto.hash/2 (module :crypto is not available)

18:47:01.496 [warn]  The on_load function for module crypto returned {:error,
 {:load_failed,
  'Failed to load NIF library: \'/home/czepluch/Dropbox/prgrms/elixir/crypto/_build/dev/lib/crypto/priv/lib/crypto.so: cannot open shared object file: No such file or directory\''}}

    :crypto.hash(:sha256, 'hello')
```

I am using Arch Linux and should have the newest version of OpenSSL(version 1.0.2d), which I have read is a problem sometimes. But I haven't really been able to trace down this issue. And as mentioned earlier what really confuses me is that this function works fine in iex.

**Comment by josevalim** [comment]
Some Linux distributions break Erlang into multiple package. Make sure you have the Erlang crypto package installed or install Erlang from Erlang Solutions, as linked in our website, because it comes with the full package.

**Comment by czepluch** [comment]
Well I can do crypto:start() in erl. This should indicate that it is installed, right?

**Comment by josevalim** [comment]
Wait, does `:crypto.hash` work? Or did you name your project `Crypto`? Maybe the source of the issue is that it is looking for crypto inside your _build directory? And that would only happen if someone defines a project named :crypto, which would conflict with Erlang's crypto.

**Comment by czepluch** [comment]
Aaah. Stupid me. Everything is fine if I give my project another name. Nicely spotted and thanks a lot! You're the best José!
