### ISSUE TITLE
Passing the :exclude option to ExUnit.start or ExUnit.configure breaks `mix test --only` and `mix test --exclude`

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#3940]
Test repo - https://github.com/alco/ex_unit_exclude_bug. The only thing I changed after running `mix new` was [this line](https://github.com/alco/ex_unit_exclude_bug/blob/8517cc165d6e15e06ed40f98d273fdc19e425e31/test/test_helper.exs#L1) in `test_helper.exs`:

```elixir
ExUnit.start [exclude: :this]
```

Now this is what happens when I run `mix test`:

```
$ mix test --only that
** (FunctionClauseError) no function clause matching in Enum.do_uniq/3
    (elixir) lib/enum.ex:2564: Enum.do_uniq(:this, #HashSet<[:test]>, #Function<11.9404203/1 in Enum.uniq/1>)
    (elixir) lib/enum.ex:2569: Enum.do_uniq/3
    (elixir) lib/keyword.ex:558: Keyword.update/4
    (elixir) lib/keyword.ex:562: Keyword.update/4
    (mix) lib/mix/tasks/test.ex:184: Mix.Tasks.Test.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2

$ mix test --exclude this
** (FunctionClauseError) no function clause matching in Enum.do_uniq/3
    (elixir) lib/enum.ex:2564: Enum.do_uniq(:this, #HashSet<[:this]>, #Function<11.9404203/1 in Enum.uniq/1>)
    (elixir) lib/enum.ex:2569: Enum.do_uniq/3
    (elixir) lib/keyword.ex:558: Keyword.update/4
    (elixir) lib/keyword.ex:562: Keyword.update/4
    (mix) lib/mix/tasks/test.ex:184: Mix.Tasks.Test.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2

$ mix test --exclude that
** (FunctionClauseError) no function clause matching in Enum.do_uniq/3
    (elixir) lib/enum.ex:2564: Enum.do_uniq(:this, #HashSet<[:that]>, #Function<11.9404203/1 in Enum.uniq/1>)
    (elixir) lib/enum.ex:2569: Enum.do_uniq/3
    (elixir) lib/keyword.ex:558: Keyword.update/4
    (elixir) lib/keyword.ex:562: Keyword.update/4
    (mix) lib/mix/tasks/test.ex:184: Mix.Tasks.Test.run/1
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
```

`mix test` without options and `mix test --include <whatever>` still work.

**Comment by josevalim** [comment]
It seems we are missing a `List.wrap` call. This is the last commit that changed this code: https://github.com/elixir-lang/elixir/commit/e867fb0d5feab17ecc3630800c823da6475a7f9a

**Comment by josevalim** [comment]
@alco I have added some comments in the linked commit above in case you want to go ahead and fix it. :D

**Comment by josevalim** [comment]
Ping. :)

**Comment by alco** [comment]
Sorry. I won't get around to landing this for at least a couple more days.

**Comment by josevalim** [comment]
Ok, I pushed fix. Please sanity check when you have a second.

**Comment by alco** [comment]
Looks straightforward enough :) I thought you wanted a test as well to accompany the change.

**Comment by josevalim** [comment]
Unfortunately the mix and exunit integration is super  hard to test because it requires shelling out a new command every time. :( If you have a clean way to do it on top of the existing suite or a new way of doing so, please do push a test. :)
