### ISSUE TITLE
When running the -v switch, please also print the Erlang/OTP version used to compile Elixir, or the version where it is currently running, whichever makes more sense for debug.

### ISSUE THREAD

**Issue by zeroum** [elixir-lang/elixir#3947]

**Comment by eksperimental** [comment]
:+1: 
although I don't think it's a good idea to change the current behaviour of -v
but I was thinking as well of this idea, maybe a new flag "--info" that would print erlang version, operating system, architecture, and all the information needed for debuggin and just asking the user to run one command and print the output

**Comment by eksperimental** [comment]
I forget about this one,,
another useful information that we can have is to include the commit id (short form) after the elixir version, so we can know exactly what version this people are running in case it's the dev. version.

```sh
$ elixir --info
Elixir 1.2.0-dev (511a175)
```
