### ISSUE TITLE
Excessive Background Processes After Elixir 1.1.1 Upgrade

### ISSUE THREAD

**Issue by zmoshansky** [elixir-lang/elixir#3951]
After running my elixir dev setup for a while I eventually get to the point where my system can't `fork` etc, due to `ulimit`. I'm not sure if this is due to a bad install (permissions error) on my part (downloaded precompiled then moved to `/usr/share/elixir/1.1.1`). After some prodding, here is what I've found:

#### Possible Explanations
- Bad install? (permissions, missed symlink) - downloaded precompiled,moved to `/usr/share/elixir/1.1.1`, then symlinked
- `lib/ex_unit` is mentioned, so perhaps not properly shutting down after running tests

#### Debugging
OS
```
Fedora 22
Linux a15 4.2.5-201.fc22.x86_64 #1 SMP Wed Oct 28 20:00:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
The following is repeated many times:
```
ps -ef | sort -rn|head -n20                                                                   
zach      9923  9922  0 Nov09 ?        00:00:00 inet_gethost 4
zach      9922  9881  0 Nov09 ?        00:00:00 inet_gethost 4
zach      9881  4569  0 Nov09 tty2     00:00:00 /usr/lib64/erlang/erts-6.3/bin/beam.smp -- -root /usr/lib64/erlang -progname erl -- -home /home/zach -- -pa /usr/share/elixir/1.1.1/bin/../lib/eex/ebin /usr/share/elixir/1.1.1/bin/../lib/elixir/ebin /usr/share/elixir/1.1.1/bin/../lib/ex_unit/ebin /usr/share/elixir/1.1.1/bin/../lib/iex/ebin /usr/share/elixir/1.1.1/bin/../lib/logger/ebin /usr/share/elixir/1.1.1/bin/../lib/mix/ebin -noshell -s elixir start_cli -extra /usr/bin/mix run --no-halt
.................
```

Which I believe is in excess of 400 processes:
```
ps -ef | gawk '{count[$NF]++}END{for(j in count) print ""count[j]":",j}'|sort -rn|head -n20   
278: 4
139: --no-halt
```

When at boot the computer has around 300:
```
ps -ef | wc -l       
745
```

Which culminates in a lot of old erlang processes:
```
ps aux | grep -i beam
zach      2527  0.0  0.3 1465708 30196 tty2    Sl+  Nov09   0:00 /usr/lib64/erlang/erts-6.3/bin/beam.smp -- -root /usr/lib64/erlang -progname erl -- -home /home/zach -- -pa /usr/share/elixir/1.1.1/bin/../lib/eex/ebin /usr/share/elixir/1.1.1/bin/../lib/elixir/ebin /usr/share/elixir/1.1.1/bin/../lib/ex_unit/ebin /usr/share/elixir/1.1.1/bin/../lib/iex/ebin /usr/share/elixir/1.1.1/bin/../lib/logger/ebin /usr/share/elixir/1.1.1/bin/../lib/mix/ebin -noshell -s elixir start_cli -extra /usr/bin/mix run --no-halt
zach      2707  0.0  0.0 1466220    0 tty2     Sl+  Nov09   0:00 /usr/lib64/erlang/erts-6.3/bin/beam.smp -- -root /usr/lib64/erlang -progname erl -- -home /home/zach -- -pa /usr/share/elixir/1.1.1/bin/../lib/eex/ebin /usr/share/elixir/1.1.1/bin/../lib/elixir/ebin /usr/share/elixir/1.1.1/bin/../lib/ex_unit/ebin /usr/share/elixir/1.1.1/bin/../lib/iex/ebin /usr/share/elixir/1.1.1/bin/../lib/logger/ebin /usr/share/elixir/1.1.1/bin/../lib/mix/ebin -noshell -s elixir start_cli -extra /usr/bin/mix run --no-halt
.....
```

#### Solution
`pkill beam.smp`

Debugging Tips Courtesy of [Redhat](https://access.redhat.com/solutions/543503)

**Comment by josevalim** [comment]
Thank you for the report! What is your Erlang version? Also, are you
running a command repeatedly, like running a test suite, or is it just
elixir?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fishcakez** [comment]
Are you using sublime text and ElixirSublime? If so see https://github.com/vishnevskiy/ElixirSublime/issues/20

**Comment by zmoshansky** [comment]
Typically I end up running `mix clean && mix test` and `mix clean && mix phoenix.server` a lot. Versions to follow, Waiting on OS package to update erlang.
```
>erl -v
Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V6.3
```
```
>dnf info erlang
Installed Packages
Name        : erlang
Arch        : x86_64
Epoch       : 0
Version     : 17.4
Release     : 4.fc22
```

**Comment by zmoshansky** [comment]
@fishcakez Get out of my head! But yes, I just so happen to be. This looks very likely to be the cause. Feel free to close.

**Comment by fishcakez** [comment]
No worries, I don't even use sublime but have seen several people complain about this issue.

**Comment by 2kodes** [comment]
hah..@fishcakez. thanks for pinpointing the fault. having the same problem on archlinux 64bit but never got round to submit an issue here.
