### ISSUE TITLE
UTF-8 handling of bitstrings shows odd behavior.

### ISSUE THREAD

**Issue by tymat** [elixir-lang/elixir#3952]
UTF-8 conversion of Bitstrings results in inconsistent behavior:

```
Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> raw = <<208, 111, 103, 101, 99, 111, 105, 110>>
<<208, 111, 103, 101, 99, 111, 105, 110>>
iex(2)> for <<a::utf8 <- raw>>, do: <<a::utf8>>
[]
iex(3)> raw2 = <<111, 103, 101, 99, 111, 105, 110>>
"ogecoin"
iex(4)> for <<a::utf8 <- raw2>>, do: <<a::utf8>>
["o", "g", "e", "c", "o", "i", "n"]
iex(5)> <<208::utf8>>
"Ð"
```

**Comment by josevalim** [comment]
When you do a 208::UTF8, you are converting a codepoint (208) to UTF8
encoding. If you do <<208::utf8, 0>>, you will see the underlying bytes.
Your raw string is not actually valid. Are you pasting codepoints instead
of the actual bytes?

On Tuesday, November 10, 2015, Anthony Eufemio <notifications@github.com>
wrote:

> UTF-8 conversion of Bitstrings results in inconsistent behavior:
>
> Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)> raw = <<208, 111, 103, 101, 99, 111, 105, 110>>
> <<208, 111, 103, 101, 99, 111, 105, 110>>
> iex(2)> for <<a::utf8 <- raw>>, do: <<a::utf8>>
> []
> iex(3)> raw2 = <<111, 103, 101, 99, 111, 105, 110>>
> "ogecoin"
> iex(4)> for <<a::utf8 <- raw2>>, do: <<a::utf8>>
> ["o", "g", "e", "c", "o", "i", "n"]
> iex(5)> <<208::utf8>>
> "Ð"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3952>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tymat** [comment]
Why would it print Ð on its own when I do <<208::utf8>> but not when it's part of a bytestring?

**Comment by alco** [comment]
@tymat When constructing a binary, `<<208::utf8>>` converts the code point into a UTF-8 encoded byte sequence:

```elixir
iex> inspect <<208::utf8>>, binaries: :as_binaries
"<<195, 144>>"
```

When matching a string, it will decode the byte sequence back into a code point:

```elixir
iex> <<cp::utf8>> = <<195, 144>>
"Ð"
iex> cp
208
```

You can insert your code point into a string if you properly encode it:

```elixir
iex> <<208::utf8, 111, 103, 101, 99, 111, 105, 110>>
"Ðogecoin"
iex> inspect <<208::utf8, 111, 103, 101, 99, 111, 105, 110>>, binaries: :as_binaries
"<<195, 144, 111, 103, 101, 99, 111, 105, 110>>"
```
