### ISSUE TITLE
 (Mix) httpc request failed with

### ISSUE THREAD

**Issue by psychoss** [elixir-lang/elixir#3956]
when i try to use the mix to install the cowboy module, it always failed to like this.

i have searched  for solution everywhere , but still have not found 

hope you help， how to solve the problem

```
>mix deps.get
Could not find Hex, which is needed to build dependency :cowboy
Shall I install Hex? [Yn] y

** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'s3.amazonaws.com', 443}}, {:inet, [:inet], :closed}]}

Could not install Hex because Mix could not download metadata at https://s3.amazonaws.com/s3.hex.pm/installs/hex-1.x.csv.signed.
```

**Comment by josevalim** [comment]
Can you please include Elixir  and Erlang version? Just run `iex`. Also, let us know if the problem still persists and/or if you are running behind a proxy.

**Comment by psychoss** [comment]
@josevalim  no proxy,  please see the below image:
![screenshot from 2015-11-12 18 00 24](https://cloud.githubusercontent.com/assets/5614729/11115754/af378b32-8968-11e5-8d55-1daa12a9b40f.png)

**Comment by josevalim** [comment]
That's weird. For now, please try downloading directly: http://s3.amazonaws.com/s3.hex.pm/installs/1.1.0/hex-0.9.0.ez

And then run: `mix local.install path/to/downloaded/hex-0.9.0.ez`. Please make sure you are safely downloading the file in your browser.

**Comment by ericmj** [comment]
`enetunreach` suggests a network issue on your end. Can you reach https://s3.amazonaws.com/s3.hex.pm/installs/hex-1.x.csv.signed in your browser?

**Comment by psychoss** [comment]
@ ericmj  can reach http://s3.amazonaws.com/s3.hex.pm/installs/hex-1.x.csv.signed

**Comment by psychoss** [comment]
@josevalim  i have installed the hex-0.9.0.ez. but still have trouble to install the modules, is possible download them directly like "http://s3.amazonaws.com/s3.hex.pm/installs/1.1.0/hex-0.9.0.ez"? i'm from china , at here to reach "s3.amonzon.com" is always a problem.

**Comment by josevalim** [comment]
You can try using the southeast-asia mirror. After you install Hex, run this:

    mix hex.config cdn_url https://s3-ap-southeast-1.amazonaws.com/s3-asia.hex.pm

Let me know how it goes!

**Comment by psychoss** [comment]
@josevalim  thanks your very quick response, it was now working fine

**Comment by zsherman** [comment]
@josevalim thanks, also worked for me.

**Comment by Ljzn** [comment]
That should be `mix archive.install path/to/downloaded/hex-0.9.0.ez`.
