### ISSUE TITLE
Markdown link reference in IEx

### ISSUE THREAD

**Issue by almightycouch** [elixir-lang/elixir#3960]
Hello there,

Documenting code with Elixir feel great.

Really like the way it works out of the box with `:ex_doc` and `:earmark` to generate HTML doc for [hexdocs.pm](hexdocs.pm).

The only little problem i have with the IEx formatted doc is with referenced links.

    For more details, have a look at the [API documentation].

    [API documentation]: https://www.myrestservice.com/api

This works great with the HTML generated doc. But in IEx, the formatting for such links doesn't work well:

* The square brackets are shown.
* The reference links are shown inline (without a break) between each other.

**Comment by josevalim** [comment]
Thank you @almightycouch ! Can you provide us a complete sample of the code you have issues, including the inline one? It will help us when we fix the bug. :)

**Comment by almightycouch** [comment]
Hi @josevalim,

Markdown documentation looks like this:

```elixir
@moduledoc """
## Authentication

Under the hood, the `Twittex.API` module uses `HTTPoison.Base` and overrides the
`request/5` method to add support for following OAuth authentication method:

* [xAuth] authentication with user credentials.
* [Application-only authentication] based on the OAuth 2 specification.

To request an access token with one of the method listed above. See `get_token/1`
and `get_token/3`. Here, a brief example:

    > token = API.get_token!
    %OAuth2.AccessToken{}

With [Application-only authentication] you don’t have the context of an
authenticated user and this means that any request to API for endpoints that
require user context, such as posting tweets, will not work.

Twitter requires clients accessing their API to be authenticated. This means
that you must provide an authentication token for each request.

This can be done by passing an OAuth token as a value of the `:auth` option:

    > API.get! "/statuses/home_timeline.json", [], auth: token
    %HTTPoison.Response{}


[xAuth]: https://dev.twitter.com/oauth/xauth
[Application-only authentication]: https://dev.twitter.com/oauth/application-only
"""
```

And here is the output in IEx:

```
Authentication

Under the hood, the Twittex.API module uses HTTPoison.Base and overrides the
request/5 method to add support for following OAuth authentication method:

  • [xAuth] authentication with user credentials.
  • [Application-only authentication] based on the OAuth 2 specification.

To request an access token with one of the method listed above. See get_token/1
and get_token/3. Here, a brief example:

┃ > token = API.get_token!
┃ %OAuth2.AccessToken{}

With [Application-only authentication] you don’t have the context of an
authenticated user and this means that any request to API for endpoints that
require user context, such as posting tweets, will not work.

Twitter requires clients accessing their API to be authenticated. This means
that you must provide an authentication token for each request.

This can be done by passing an OAuth token as a value of the :auth option:

┃ > API.get! "/statuses/home_timeline.json", [], auth: token
┃ %HTTPoison.Response{}

[xAuth]: https://dev.twitter.com/oauth/xauth [Application-only authentication]:
https://dev.twitter.com/oauth/application-only
```

I think the last two lines should look like this:

```
[xAuth]: https://dev.twitter.com/oauth/xauth
[Application-only authentication]: https://dev.twitter.com/oauth/application-only
```

Not sure if square brackets is the best option to indicate that the text  refers to an URL.
Wouldn't it be better to show the text underlined or simply suffix it with ↴?

**Comment by martinsvalin** [comment]
Kind of a corner case, and maybe ↴ is worth the minimal confusion, _but_.
A ↴ could be a little misleading if the reference is linked above instead of below. I know this is uncommon, but consider a reused reference:

```markdown
Some text with a [link].

[link]: http://www.example.com

More text, repeating the [link].
```

**Comment by milmazz** [comment]
More details about this issue, in this case I'll use different types of *inline* and *reference* links.

```elixir
defmodule Markdown do
  @moduledoc """
  Markdown links

  This is [an example](http://example.com/ "Title") inline link.

  This is [an example][id] reference-style link.

  Another reference style links: [Google][], [Elixir Official Site][1]

  [id]: http://example.com/
  [Google]: https://google.com
  [1]: http://elixir-lang.org
  """
  ...
end
```

This current behavior in IEx is the following:

![screen shot 2015-11-16 at 9 36 54 pm](https://cloud.githubusercontent.com/assets/34700/11202111/2f7d1caa-8caa-11e5-91c0-2d9f6a5f8769.png)

I think that we can try to emulate the current behavior of [mdp](https://github.com/visit1985/mdp), a command-line based markdown presentation tool, this is a basic example using *inline* links, apparently mdp does not support *reference* links yet:

![screen shot 2015-11-16 at 9 39 53 pm](https://cloud.githubusercontent.com/assets/34700/11202193/60d4b56e-8cab-11e5-9ceb-699b09bd7cea.png)

HTH

**Comment by milmazz** [comment]
Is somebody working on this? I'd like to take a stab at this if it's free.

**Comment by martinsvalin** [comment]
@milmazz - Go ahead. I started but was interrupted by my two-year-old, and haven't had time since. The markdown processing is done in `IO.ANSI.Docs`, and is due to the links being treated as a paragraph of normal text, and a normal block of text is collected up and inlined.

**Comment by josevalim** [comment]
@milmazz, please go ahead. Also, keep in mind I don't think we need to change the formatting of the bullets at the end at all (`IO.ANSI.Docs` rarely changes the formatting), we just need to make sure it does not show up messed up.

**Comment by milmazz** [comment]
@martinsvalin @josevalim Great!, I'll start working on this, I'll keep you posted.
