### ISSUE TITLE
doctest: ignore lines that don't list an assertion value

### ISSUE THREAD

**Issue by pdilyard** [elixir-lang/elixir#3970]
It would be useful if doctests ignored lines that don't have an explicit value to assert to. For example:
```elixir
@doc """
iex> {:ok, pid} = ListServer.start_link
"""
```
The above will fail to compile because of the following error:
```elixir
** (ExUnit.DocTest.Error) expected non-blank line to follow iex> prompt
```
One possible work around for this is to do the following:
```elixir
iex> {:ok, pid} = ListServer.start_link
iex> :ok
:ok
```
But this sort of clogs up the documentation.

**Comment by josevalim** [comment]
Thank you. I am not sure because, although this feature could be useful, it also looks incomplete from the documentation perspective (we don't show the return value!) or may hide a bug (someone actually forgot to write the next line).

**Comment by lexmag** [comment]
> someone actually forgot to write the next line

I've seen that happened, not once.

**Comment by michalmuskala** [comment]
And also: if there will be no assertion - why do you want to use a doctest?
I presume it's for testing that the code won't crash - but does it have such a big value for documentation? We need to have in mind that doctests are primarily a form of documentation, only later they are a form of tests (at least that's how I view them).

**Comment by pdilyard** [comment]
The intention would be to show the usage of a function like this, that might return a "random" value (such as a PID). One idea I had is something like this:
```elixir
@doc """
iex> SomeServer.start_link
{:ok, _pid}
"""
```
This pattern matching technique could also be applied to stuff like this:
```elixir
@doc """
iex> RandomWords.get_word
_word
"""
```

Maybe this isn't the best solution, but it would be nice to be able to show usage examples even when you can't assert the value you get in response.

Of course, you could ignore certain functions in your doctest statement, like so:
```elixir
doctest RandomWords, except: [get_word: 0]
```
But this creates potential for problems like you guys mentioned above. Someone could very easily change the usage of the function, but forget to reenable the doctest on that particular function.

**Comment by alco** [comment]
> Maybe this isn't the best solution, but it would be nice to be able to show usage examples even when you can't assert the value you get in response.

You can skip the `iex>` prefix to exclude an example from doctests.

**Comment by pdilyard** [comment]
@alco that's a good point. I guess it's just my OCD that wants to be completely consistent :smile:

**Comment by josevalim** [comment]
Ok, I am closing this as we agree it shouldn't be fixed, thanks @pdilyard!

**Comment by pdilyard** [comment]
Thanks for the quick feedback!
