### ISSUE TITLE
Mix deps path: difference where the path points to

### ISSUE THREAD

**Issue by ThomasArts** [elixir-lang/elixir#3979]
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
Interactive Elixir (1.1.1) 

I have a little Erlang project structured as:
myapp/ebin   myapp/include  myapp/doc
The ebin directpry contains all beam files and a myapp.app file.

I added a dependency 
  {:myapp, path: "../myapp-2.0", compile: false}

This is looking for an app file in the directory 
  could not find an app file at _build/dev/lib/myapp/ebin/myapp.app. This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies

But if I copy the complete applications to deps/myapp
and I adapt the mix file: {:myapp, path: "deps/myapp", compile: false}
then it all works fine.

Moreover, if I go back to the original setting and use:
  {:myapp, path: "../myapp-2.0", compile: false, :app false}
then it also works fine.

My conclusion is that the search for a .app file should take the :compile flag into consideration also for paths outside deps.... But I cannot put my finger on it when inspecting the code. My assumption is that line 14 in deps.loadpaths.ex should be changed.

**Comment by josevalim** [comment]
Hello @ThomasArts! In theory, after projects are compiled (even with compile: false), we copy ebin and all of its contents to `_build/ENV/lib`. If the app is not available, I am suspecting something is not being copied as expected. I will investigate.

**Comment by ThomasArts** [comment]
Don't get me wrong, the project has a .app file in the ebin directory.

The files are copied when I use 
  {:myapp, path: "../myapp-2.0", compile: false}
The porblem is that the .app file is searched for in _build/test/lib/myapp/ebin
whereas the copy procedure keeps the original name which has a -2.0 in the path.
Thus:

A directory 
_build/test/lib/myapp-2.0/ebin
is created by the copy procedure, but the .app file is seacrhed for in:
_build/test/lib/myapp/ebin

I double checked and indeed, if I rename my directoty to myapp, then it works again
  {:myapp, path: "../myapp", compile: false}

The question is also, can you deal with an Erlang way of embedding versions in the path name in the Elixir style dependencies?

/Thomas

**Comment by ThomasArts** [comment]
Probably I focus on the wrong problem. If you have a pre-compiled Elrang project, one would normally add that project to ERL_LIBS. In this case one would be able to run mix with the right ENV setting:ERL_LIBS = /home/thomas/projects/myapp-2.0 mix test
and no dependency needs to be provided.... but if no dependency is provided, it is hard to know for users that this project actually has this hidden library dependency.

Thus, is there a hook to tell the mix file to add something to ERL_LIBS?
That would solve part of the unclarity.

**Comment by josevalim** [comment]
@ThomasArts I think you found the bug. If the project is called `{:myapp, path: "../myapp-2.0", compile: false}`, we should copy it to `_build/dev/lib/myapp` (using the first element of the tuple). I will take a further look soon.

**Comment by josevalim** [comment]
Elixir 1.2 will come out in a week or two (at least the release candidate). For now, the best is to ensure the application and the filesystem path are the same (i.e. `myapp` for both).

**Comment by ThomasArts** [comment]
Excellent.
Thanks a lot for your help. I can manage with this, no problem.

/Thomas
