### ISSUE TITLE
Support optional callbacks

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#3980]
See http://www.erlang.org/doc/design_principles/spec_proc.html#id74952 and `-optional_callbacks`

**Comment by stevedomin** [comment]
I'm keen to take this one if no one is on it yet @fishcakez

**Comment by fishcakez** [comment]
@stevedomin please do

**Comment by whatyouhide** [comment]
I'm working on this.

**Comment by josevalim** [comment]
Closing in favor of #4705.
