### ISSUE TITLE
Shell process terminated after define Kernel module

### ISSUE THREAD

**Issue by jfcalvo** [elixir-lang/elixir#3982]
Using Elixir 1.1.1 on MacOS (El Capitan 10.11.1) I get the following error redefining `Kernel`module:

```sh
$ iex
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule Kernel do
...(1)> end
iex:1: warning: redefining module Kernel
*** ERROR: Shell process terminated! (^G to start new job) ***
``` 

This should only show a warning isn't it?

**Comment by josevalim** [comment]
If you redefine Kernel, you are redefining the main Elixir module with most of the Elixir functions, including guards, etc. A lot of things are going to crash if you do that. :)

**Comment by jfcalvo** [comment]
> If you redefine Kernel, you are redefining the main Elixir module with most of the Elixir functions, including guards, etc. A lot of things are going to crash if you do that. :)

Sure, but applying the least surprise principle should not a exception be raised instead of a error? (Only asking) :)

**Comment by lucca65** [comment]
Redefining `Kernel` breaks because IEx is already running when you redefine the module and it relies on that module, since Elixir is a dynamic lang, it makes a lot of sense.

When you write code on iex, it runs on the same process, so it breaks. but if you take that to a file and try again, it don't break. (but the it becomes unusable). That may point that when iex is booting up, it interpret your file in a different process, or that iex runs something after it finishes loading your code.


```elixir
defmodule Kernel do
end
```

Give it a name, and run on iex:
```
> $~: iex redefined.exs 
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

redefined.exs:1: warning: redefining module Kernel
Interactive Elixir (1.1.0) - press Ctrl+C to exit (type h() ENTER for help)
```

**Comment by jfcalvo** [comment]
Ok @lucca65 thanks for the explanation.

**Comment by lucca65** [comment]
and, if you take that and makes it run in a different process, it finishes the cmd without problems, but with the next cmd, it breaks! Perfectly good sense!

```elixir
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.1.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> spawn(fn ->
...(1)> defmodule Kernel do
...(1)> end
...(1)> end)
iex:2: warning: redefining module Kernel
#PID<0.62.0>
iex(2)> *** ERROR: Shell process terminated! (^G to start new job) ***
```

When the next cmd is asked, Kernel module is empty so it panics and breaks

**Comment by lucca65** [comment]
@jfcalvo no problem! you can ask those kind of questions in the IRC or slack channels, so we don't fill the issue tracker with language/vm clarifications
