### ISSUE TITLE
IEx.Info error during introspection of captured function

### ISSUE THREAD

**Issue by antipax** [elixir-lang/elixir#3983]
```elixir
iex(17)> i &Enum.map/2
** (ArgumentError) argument error
          :erlang.apply([module: Enum, name: :map, arity: 2, env: [], type: :external], :name, [])
    (iex) IEx.Info.Function.info_named_fun/1
    (iex) lib/iex/info.ex:205: IEx.Info.Function.info/1
    (iex) lib/iex/helpers.ex:420: IEx.Helpers.i/1
```

Looks like it's due to [this line](https://github.com/elixir-lang/elixir/blob/3a559432d42b0fb60727b6a0653cc4b54e7c34af/lib/iex/lib/iex/info.ex#L219) using `thing.blah` on a Keyword rather than `thing[:blah]`. Glad to make a PR if that sounds right.

**Comment by whatyouhide** [comment]
whoops, my bad :(

**Comment by josevalim** [comment]
No problem. I did a couple of those too, the tests will help. :)
