### ISSUE TITLE
_build location for umbrella applications

### ISSUE THREAD

**Issue by vadim-moz** [elixir-lang/elixir#3992]
Currently, we have the following `_build` structure:

```
  - apps
    - my_app1
      _ _build
        - dev
          - lib
            - my_app2
            - ext_dep1
            - ext_dep2    
      - lib
        ... 
    - my_app2
      _ _build
      - lib
    ...
  - _build
    - dev
      - lib
        - dev
          - my_app1
          - my_app2
        - ext_dep1
        - ext_dep2
        - ext_dep3
  - deps
```

If the number of applications in umbrella becomes considerable,
the schema does not scale too well: 

* application compiles dependencies individually (linear scaling of compile time and disk space);
* group compilation does not reuse results of the compilation of individual application.

It becomes esp. painful with bigger apps, like Ecto, Phoenix, or tzdata. (We do have multiple apps depending on Ecto: they work with different DBs, and it is reasonable to isolate them.)

[

  A typical scenario: 
  * I pull, there are new dependencies in the project
  * go to `app1`, do my work, compile, ...
  * go to `app2` -- test starts compilation of all the irrelevant
    to my direct work things, because of deps changes. But they had beed resolved when I worked on app1!
  * go to project root to run final test: compile again :-( 

]

Altogether, it slows development. So, my question is, why mix does not allow to specify `build_path` in project in the way similar to `dept_path`, `lockfile`, etc.? 

(I tried to soft-link `_build` back to the project root, but it does not work -- I suspect, mostly because of soft-linked `priv` inside `_build`. But it might be more than one problem with the approach.)

@josevalim commented on the [maillist](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/elixir-lang-core/_build/elixir-lang-core/cYcvzNxOLqc/to8S7m-OEwAJ)
You are right Vadim.

We were aware of such issues but we were waiting until it actually became a problem. The reason it behaves the way it does is because the umbrella can use a different configuration than the children which ultimately affects the built artifacts. Maybe we should change all apps to use the umbrella configuration, ultimately allowing us to change the build_path as well.

Can you please open up an issue on Elixir issues tracker?

**Comment by josevalim** [comment]
Thank you @vadim-moz, I have pushed a fix to Elixir master. *Please* give it a try. All you need to do is to bump to Elixir master and add those two lines to the mix.exs files inside apps: b4d5c17d0add69689acb8869f4533e1c0741f5ef

You should have a single, shared _build directory and it should drastically reduce the number of recompilations. Also, you no longer need to import_config from umbrella siblings, since they all depend on a single configuration now (the parent one).
