### ISSUE TITLE
Disallow {:foo, opts} dependency format

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#3995]
If `{:foo}` and `{:foo, nil}` is not allowed then a missing version requirement shouldn't be allowed in `{:foo, opts}` either.

**Comment by josevalim** [comment]
We have discussed this when we deprecated nil. There is a completely valid reason to skip the version for git deps:

    {:foo, github: "foo/bar", tag: "1.0.0"}

I don't see a reason to make it easier to skip the version for hex dependencies.

**Comment by ericmj** [comment]
I'm not arguing that it should be easier to skip the version for hex deps, in fact I want the opposite. It's very easy to skip the version when using an optional dependency: `{:foo, optional: true}`. This is also uncovered a bug in the hex client because I did not expect the missing requirement.

**Comment by josevalim** [comment]
So hex can raise in such cases. I don't think it is worth sacrificing the
git case because of the hex issue.

On Wednesday, November 25, 2015, Eric Meadows-Jönsson <
notifications@github.com> wrote:

> I'm not arguing that it should be easier to skip the version for hex deps,
> in fact I want the opposite. It's very easy to skip the version when using
> an optional dependency: {:foo, optional: true}. This is also uncovered a
> bug in the hex client because I did not expect the missing requirement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/3995#issuecomment-159747064>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
Okay, I will add it to hex directly.
