### ISSUE TITLE
Inconsistent response type from String.replace/3 when 2nd argument is a regex

### ISSUE THREAD

**Issue by Bockit** [elixir-lang/elixir#4001]
```
$ iex --version
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.1.1
```
Mac OS X 10.11.1

I'm getting what I think to be some inconsistent return value types from String.replace/3.

```
iex(1)> String.replace("Freude", ~r/\W/, "")
"Freude"
iex(2)> String.replace("schöner", ~r/\W/, "")
<<115, 99, 104, 195, 110, 101, 114>>
iex(3)> String.replace("schöner", "z", "")
"schöner"
```

My expectation is that all return values would be strings, or at least consistent. Not a combination of bit strings and strings depending on the contents of the string and what you use to search with (regex vs string).

I have tested this in `iex` built from the master branch and it has the same behaviour.

I'm new to elixir so if this is expected behaviour (quite possible) and I just haven't understood something then I apologise.

Thanks for your time.

**Comment by michalmuskala** [comment]
This is definitely and issue of regexes working with unicode strings. You can compile regex to work with unicode by adding a `u` flag:

```
iex(1)> String.replace("schöner", ~r/\W/u, "")
"schöner"
iex(2)> String.replace("schöner", ~r/\W/, "") 
<<115, 99, 104, 195, 110, 101, 114>>
```

**Comment by josevalim** [comment]
Yes, @michalmuskala is right. If you don't pass the unicode flag, it is going to work on bytes and remove bytes you don't expect.

**Comment by Bockit** [comment]
Ahh, that makes sense. Thanks!
