### ISSUE TITLE
Stop using `.lock` extension

### ISSUE THREAD

**Issue by asymmetric** [elixir-lang/elixir#4002]
Hi,

The Bundler project has [changed](https://github.com/bundler/bundler/issues/694) the extension (and the name) of their lockfile: from `Gemfile.lock` to `gems.locked`. This breaking change had to be postponed for several years, but will be introduced with Bundler 2.0.

The main reason is that the `.lock` extension is [traditionally](https://en.wikipedia.org/wiki/File_locking#Lock_files) used in *nix to indicate a resource that is locked for writing, because it's being written to by another process. The implicit assumption is that these files contain no data, and can be deleted on startup/shutdown.

The Bundler team decided to settle for `gems.locked`.

Is this relevant for **mix**?

**Comment by chrismccord** [comment]
has this resulted in actual issues with .lock files disappearing on some *nix configurations? Or just theoretical?

**Comment by josevalim** [comment]
Someone pointed me to the Bundler discussion a couple days (weeks?) ago. We could of course change it, but only by the time Elixir 2.0 is around, which I don't expect to happen in a couple years and I don't think it is worth it even by then. Also worth pointing out you can configure the lockfile location *today*, so if this is an issue for your team, at least it is an easy fix.

Thanks @asymmetric but I don't think this is a concern to most people and there is an easy to circumvent it still. :) Specially when we introduce releases into Elixir proper and then whatever artifact you deploy to production won't have the lock file anyway.

**Comment by alco** [comment]
> Specially when we introduce releases into Elixir proper

@josevalim when can we expect that to happen? :)

**Comment by fishcakez** [comment]
If you implement it Alexei it can probably get merged anytime after 1.2 is
out :P
