### ISSUE TITLE
Attempt to speed up logger by creating a pool of IO processes

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4004]

**Comment by olafura** [comment]
As I understand it going through the source code Erlang has a group server that sends messages to user_drv that has a port process to write to stdio, I can get the process through: :erlang.group_leader()

I'm not sure if a pool would be any faster at processing it. It would be fun doing some tests maybe sending messages directly to the user_drv.

Maybe use a buffer instead?

**Comment by josevalim** [comment]
@olafura the goal was to bypass all that and write directly the stdio via a port. I did a test a couple days ago but it is unfortunately not possible. I am closing this but if you have ideas on how to improve Logger IO performance, please let us know and/or send PRs. :D
