### ISSUE TITLE
Provide different accessors in the Access module

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4009]
The goal is to provide accessors to be used alongside Kernel.put_in and friends. For example:

```elixir
put_in sample[:foo][:bar], :baz
```

Can be thought as a shortcut to:

```elixir
put_in sample, [Access.key(:foo), Access.key(:bar)], :baz
```

Where `Access.key(:foo)` will return a function as described by `Kernel.get_and_update_in`. Similar would exist for structs:

```elixir
put_in sample.foo.bar, :baz
```

is equivalent to:

```elixir
put_in sample, [Access.field(:foo), Access.field(:bar)], :baz
```

For now, we will also provide `all/0` and `at/1` for lists and `elem/1` for tuples. The question is the naming convention for those functions. For example, we could prefix most of them by `by_`: `by_key`, `by_elem` and `by_field`, although it wouldn't work for `all/0` and `at/1`. Alternatively, we can drop the `by_` prefix, although it could be confusing if mixed with the existing `fetch/2`, `get/3` and friends.

Thoughts?

**Comment by tuvistavie** [comment]
Would it be possible to have some more info about this one?

**Comment by josevalim** [comment]
I have updated the description although it is assigned to me. :)

**Comment by lexmag** [comment]
I think not having `by_` prefix is completely fine: there is single "static" argument, feels natural with `fetch/2` and `get/3`.

**Comment by amuino** [comment]
Any reason why `at` was finally not added for lists? I found myself implementing `first` (which is just a particular case of `at`).

**Comment by josevalim** [comment]
No reason. Would you like to send a PR?

On Saturday, May 28, 2016, Abel Muiño <notifications@github.com> wrote:

> Any reason why at was finally not added for lists? I found myself
> implementing first (which is just a particular case of at).
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4009#issuecomment-222328728>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbqktmueRKfRyFu5L27KWPcaCEUZbks5qGKhXgaJpZM4Gq5o4>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by amuino** [comment]
@josevalim Done! #4719

Would it be useful to have `first` and `last`? (Mostly because `last` is a bit cumbersome to implement with an index based API).

Re: naming, I'll throw an idea… `Access.List.at`, `Access.Tuple.elem`… (or maybe the other way around: `List.Access.at`…).
