### ISSUE TITLE
Nested inner for comprehensions accumlate when outer does not accumlate

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#4013]

**Comment by josevalim** [comment]
More info please? I would love to take a look at it tomorrow, specially if
you think it should be part of the next release.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fishcakez** [comment]
```elixir
_ = for y <- x do
  for z <- y do
    side_effect_fun(b)
  end
end
:return_other
```
The inner for is accumulated and reversed. Of course this can be avoided by ensuring it is not returning a useless value after the inner for:
```elixir
_ = for y <- x do
  _ =for z <- y do
    side_effect_fun(b)
  end
  :ok
end
:return_other
```
However maybe we can handle the first case too.
