### ISSUE TITLE
Inline list for comprehensions using generated annotated case in AST

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#4014]
At some point we did this (but without generated annotation), it might be worth bringing this back to pass as much intent to erlang compiler as possible? List to non-binary bitstring would certainly gain as current implementation is very naive (reference bitstring on every element).

**Comment by josevalim** [comment]
https://gist.github.com/fishcakez/bc74ff47cbac14bb9dde

**Comment by fishcakez** [comment]
The list comprehension in that gist does preallocate the bitstring (if you check the core or asm).

**Comment by josevalim** [comment]
Closing because the cost of recur compared to fold is the anonymous function which we can't get rid of.
