### ISSUE TITLE
"mix test" fails if excluded/included tag does not exist

### ISSUE THREAD

**Issue by asymmetric** [elixir-lang/elixir#4016]
If I try running `mix test --exclude non_existent_tag`, mix fails. I would expect it to instead just run all non-excluded tests.

Additionally, running `mix test --include non_existent_tag` also fails. I would find it more intuitive if it just said that no test was run. 

The same happens when using `ExUnit.configure`.

One usecase is configuring `test_helper.exs` with `ExUnit.configure(exclude: :pending)`, and it would be nice if mix wouldn't fail if there are no pending tests.

**Comment by josevalim** [comment]
@asymmetric I cannot reproduce this. Mix does not fail in any of those situations. Can you please provide a proper report with Elixir version and more information on how to reproduce the issue?

**Comment by asymmetric** [comment]
Nevermind, it was an issue with my project. Sorry for the trouble :)
