### ISSUE TITLE
Better err msg for `nil` in pattern matching

### ISSUE THREAD

**Issue by beedub** [elixir-lang/elixir#4019]
Could there be better error messaging for the case below?

```
iex(1)> blah = nil
nil
iex(2)> << blah :: 64 >>
** (ArgumentError) argument error
```

I debugged this today and that it reports `ArgumentError` made the error source misleading

**Comment by fishcakez** [comment]
Unfortunately this error is raised by Erlang and so there is nothing we can do. In a compiled module the stack trace should point to the correct line.

**Comment by beedub** [comment]
> In a compiled module the stack trace should point to the correct line.

Can you elaborate? It is a dependency and I saw this error during test. I was under the impression that all dependencies were compiled and used by `mix test`?

**Comment by beedub** [comment]
Is this something that can or would be addressed by erlang if reported upstream?
