### ISSUE TITLE
Provide a mechanism to change the mirror while installing hex and rebar 

### ISSUE THREAD

**Issue by mingshun** [elixir-lang/elixir#4020]
It's hard to install hex and rebar with `mix local.hex` and `mix local.rebar` for the low speed of network connection from asia resulting in timeouts many times after a success installation.

I found that the s3 url is hard coded in the mix tasks.

Look forward to a mechanism that provides the ability to change the s3 url to other mirrors of different locations.

**Comment by ericmj** [comment]
You can install from our asia mirror with `mix archive.install http://s3-asia.hex.pm.s3.amazonaws.com/installs/hex.ez` but note that this will not verify the file against the public key so it's insecure.

We are likely going to put a region caching CDN in front of S3 in the future, but we should probably add this as an option anyway.

**Comment by josevalim** [comment]
Closed in favor of the PR. thank you!
