### ISSUE TITLE
Install instructions for Linux Mint

### ISSUE THREAD

**Issue by PragTob** [elixir-lang/elixir#4031]
(the docs repo doesn't seem to have issues and it's not a personal support request imo as it's needed for everyone and should find its ways to the docs)

first thanks for a cool programming language and :+1: on a popular repo with less than 30 open issues o_O

Linux Mint is based on Ubuntu, current versions (Linux Mint 17.x) are based on Ubuntu 14.04. So when installing it is usually fine to [look for Ubuntu](http://elixir-lang.org/install.html#unix-and-unix-like). Also Linux Mint is rather popular (number one by far according to [distrowatch](http://distrowatch.com/table.php?distribution=mint)).

However, for Elixir that strategy that usually works failed me, following the instructions:

```
tobi@airship ~ $ wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
--2015-12-01 21:02:18--  https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
Resolving packages.erlang-solutions.com (packages.erlang-solutions.com)... 31.172.186.53
Connecting to packages.erlang-solutions.com (packages.erlang-solutions.com)|31.172.186.53|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4826 (4,7K) [application/x-debian-package]
Saving to: ‘erlang-solutions_1.0_all.deb’

100%[======================================>] 4.826       --.-K/s   in 0s      

2015-12-01 21:02:19 (222 MB/s) - ‘erlang-solutions_1.0_all.deb’ saved [4826/4826]

[sudo] password for tobi: 
Selecting previously unselected package erlang-solutions.
(Reading database ... 296274 files and directories currently installed.)
Preparing to unpack erlang-solutions_1.0_all.deb ...
Unpacking erlang-solutions (1.0) ...
Setting up erlang-solutions (1.0) ...
#deb cdrom:[Linux Mint 17.1 _Rebecca_ - Release amd64 20141126]/ trusty contrib main non-free
tobi@airship ~ $ sudo apt-get update
# snip
tobi@airship ~ $ sudo apt-get install elixir
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package elixir
```

Some system information: 
````
tobi@airship ~ $ uname -a
Linux airship 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```



Other people seem to have hit that problem before but it usually amounts to use precompiled/compile yourself or run this bash script. ([1](http://unix.stackexchange.com/questions/164895/install-elixir-lang-on-linux-mint) [2](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-lang-talk/vj_1TMdBR1E/piWuS_Ai29gJ) [3](https://github.com/DataMelon/install-elixir-1.0.4))

While I'm keen to compile myself, a more accessible way for Linux Mint users would be great.

Thanks for all your hard work!
Tobi

**Comment by josevalim** [comment]
Thank you @PragTob! We don't maintain those packages but I am copying @dexsda who does. :) Maybe he is interested in investigating it further.

**Comment by PragTob** [comment]
@josevalim Thanks!

@dexsda I'm happy to provide further info :) It might just be a case of it not setting the correct repository - I use ubuntu packages everywhere (and it is the same source) so just using the appropriate ubuntu version should be totally fune

**Comment by Gazler** [comment]
@PragTob What is the contents of your `/etc/apt/sources.list.d/erlang-solutions.list`?

I am fairly sure I have installed elixir from https://www.erlang-solutions.com/resources/download.html before.

**Comment by Troush** [comment]
Remove all erlang packages.
Do:
```
wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
sudo dpkg -i erlang-solutions_1.0_all.deb
```
Install all erlang packages.

Install elixir. (Use kiex)

Only this fixed my mint installation

**Comment by PragTob** [comment]
```
tobi@tobi-desktop ~ $ cat /etc/apt/sources.list.d/erlang-solutions.list 
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb http://binaries.erlang-solutions.com/debian squeeze contrib
```

The installer says it can't find the right code name, but suggested squeeze and I hit enter as I'm not too familiar with all the debian release names.

I just adjusted squeeze to the appropriate "wheezy", now it worked. Thanks for your help and I'll see to get in touch with the erlang-solutions people to fix the code name detection.

**Comment by folz** [comment]
I also ran into this issue (Mint 17.1). Following the install instructions

`wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb`

gives me an erlang-solutions.list that looks like 

```
➜  ~  cat /etc/apt/sources.list.d/erlang-solutions.list 
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb http://binaries.erlang-solutions.com/debian rebecca contrib
➜  ~  
```

with the same error as above. Replacing `rebecca` with `trusty` removes the error and installs correctly.

If it helps, `lsb_release -uc` seems to give the "correct" Ubuntu codename:

```
➜  ~  lsb_release -uc                                       
Codename:	trusty
```

Happy new year!

**Comment by kwokhou** [comment]
I had the same issue with Mint 17.3, landed in this page from Google search. 

Changing the word `squeeze` in `/etc/apt/sources.list.d/erlang-solutions.list` to `wheezy` works for me. 

Hope this helps others.

**Comment by josevalim** [comment]
Pinging @dexsda  in case he missed this earlier. :)

**Comment by PragTob** [comment]
Wrote erlang-solutions an email, didn't find an issue tracker or anything like that

**Comment by richarddewit** [comment]
Using `trusty` for Linux Mint 17.3 worked for me. 
@folz - good idea to run `lsb_release -uc` :+1:

**Comment by david-pm** [comment]
I had the exact same problems as @PragTob . Used the GUI installers https://www.erlang-solutions.com/resources/download.html 
changed squeeze to wheezy in /etc/apt/sources.list.d/erlang-solutions.list and it all works fine :)

**Comment by PragTob** [comment]
Still, damn :(

As another solution I just started using [asdf](https://github.com/asdf-vm/asdf) as a version manager and it worked rather nice.

**Comment by sachpatel** [comment]
@PragTob and @david-pm solution worked for me today. I was using Linux Mint Rosa. Had to change squeeze to wheezy, run apt-get update and then elixir installed :+1:

**Comment by DenisGorbachev** [comment]
Solution for Linux Mint 18.1 "Serena":

```
starfall@rhino:~$ cat /etc/apt/sources.list.d/erlang-solutions.list 
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb http://binaries.erlang-solutions.com/debian xenial contrib
```

**Comment by slashmili** [comment]
FYI I faced same problem because with Mint 18.2 distro 
```
$ sb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
$ cat /etc/debian_version
stretch/sid
```

and even though it's base on Debian `stretch` you should still use `wheezy` in erlang-solutions source file. However Elixir 1.3 was installed.

I guess `asdf` is the best option in Mint.

**Comment by josevalim** [comment]
Should we update the website to recommend asdf then? Can someone please send a PR there? the repo is elixir-lang/elixir-lang.github.com

**Comment by DenisGorbachev** [comment]
@josevalim might be better to provide distro-specific installation instructions (in this case, people will be able to install & update elixir via native package manager)

**Comment by PragTob** [comment]
👍 on asdf... went with it after all my experience here and still love it. Won't get to PRing it now but might get around to it the next couple of days :)

**Comment by a-tsvil** [comment]
Currently(20/20/2019) you need to set in /etc/apt/sources.list.d/erlang-solutions.list debian codename to buster.
