### ISSUE TITLE
graphemes handling in unicode printing

### ISSUE THREAD

**Issue by ThomasArts** [elixir-lang/elixir#4038]
Handling graphemes is hard and I am not an expert, but Elixir does a good job:
http://rosettacode.org/wiki/Reverse_a_string#Elixir

Nevertheless, I think there are some uncovered corner cases. I tried to check the property:
property "Reverse strings" do
    forall string <- utf8 do
      ensure String.reverse(String.reverse(string)) == string
    end
  end

I expect the property to hold, but it did not. Not even for strings that are Elixir valid and for which the reverse is a valid Elixir string. This is slightly surprising and I tried to understand it, but after reading more about graphemes, I think they should be respected, even in reversing.
Thus, I guess that either reverse should reject strings or that a warning in the documentation is in place.
(that is, if the issue cannot be simply solved)

Since I know the trust in QuickCheck may be lacking, I also produced unit tests that show the same:
 test "Reverse strings 1" do
    string = <<204,128,32>>
    assert String.valid?(string)
    assert String.valid?(String.reverse(string))
    assert String.reverse(String.reverse(string)) == string
  end

  test "Reverse strings 2" do
    string = "\x{07eb} "
    assert String.valid?(string)
    assert String.valid?(String.reverse(string))
    assert String.reverse(String.reverse(string)) == string
  end

For code to reproduce this: property and tests at
https://github.com/ThomasArts/Mini

**Comment by josevalim** [comment]
Unicode reverse is not re-reversible. I think this example is easier to see why:

```iex
iex(11)> <<204, 128, ?e>>
"̀e"
iex(12)> String.reverse <<204, 128, ?e>>
"è"
iex(13)> String.reverse String.reverse <<204, 128, ?e>>
"è"
```

Because in the initial example the accent is before the vowel, it is considered two graphemes. However, when you reverse once, you have the letter followed by the accent, which becomes one grapheme.

I think this would be a good addition to the docs. What do you think?

> Since I know the trust in QuickCheck may be lacking, I also produced unit tests that show the same:

Never. :)

**Comment by ThomasArts** [comment]
Seems a good solution to explicitly point "surprises" in the doc. 
I do think it is a kind of weakness in the specification of unicode, they should have thought more carefully about it.

Where things may get problematic is when you use graphemes in your password or user name and the software is by some recursion parsing the string and then do a reverse at the end, thinking it's the same.
A common pattern when you use an accumulator and want to append at the end. People better should be warned :-).

Cheers
Thomas
