### ISSUE TITLE
iex doesn't start

### ISSUE THREAD

**Issue by ykg2910** [elixir-lang/elixir#4041]
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

{error_logger,{{2015,12,3},{13,36,2}},"Loading of ~ts failed: ~p\n",["/usr/lib/elixir/bin/../lib/iex/ebin/Elixir.IEx.beam",badfile]}
*** ERROR: Shell process terminated! (^G to start new job) ***
{error_logger,{{2015,12,3},{13,36,2}},"~s~n",["beam/beam_load.c(1682): Error loading module 'Elixir.IEx':\n  This BEAM file was compiled for a later version of the run-time system than R16B03-1.\n  To fix this, please recompile this module with an R16B03-1 compiler.\n  (Use of opcode 158; this emulator supports only up to 153.)\n"]}

=ERROR REPORT==== 3-Dec-2015::19:06:02 ===
Loading of /usr/lib/elixir/bin/../lib/iex/ebin/Elixir.IEx.beam failed: badfile

=ERROR REPORT==== 3-Dec-2015::19:06:02 ===
beam/beam_load.c(1682): Error loading module 'Elixir.IEx':
  This BEAM file was compiled for a later version of the run-time system than R16B03-1.
  To fix this, please recompile this module with an R16B03-1 compiler.
  (Use of opcode 158; this emulator supports only up to 153.)

**Comment by josevalim** [comment]
Please use Erlang 17 or, preferably Erlang 18. Erlang 16 and earlier is not supported.

**Comment by mavdi** [comment]
I had the same issue with Erlang 18, but relinking it with brew worked for me:
```bash
brew link --overwrite erlang
```
