### ISSUE TITLE
Raise when using import with a list of atoms

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/elixir#4043]
When answering https://stackoverflow.com/questions/34066395/how-to-import-a-function-with-different-number-of-params I noticed this.

If a user wants to import multiple functions with the same name but a different arity then the following are all valid ways of importing the `send` function.

    import Request
    import Request: :functions
    import Request, only: [send: 1, send: 2, send: 3, send: 4]
    import Request, except: [notsend: 1, also_notsend: 2]

However a user may also be tempted to try:

    import Request, only: [:send]

This is valid elixir code, however it doesn't actually do anything with the arguments. I think that this should raise, informing the user of the valid ways to import functions/macros.

cc /@ericmj

**Comment by josevalim** [comment]
Definitely.
