### ISSUE TITLE
Get all arguments passed to a function

### ISSUE THREAD

**Issue by Angarsk8** [elixir-lang/elixir#4051]
Hi guys,

Is there a way of getting all the arguments passed to a function as a collection? Like *args in Ruby, the [arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments) object in Javascript or the [...args](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Functions/rest_parameters) rest parameter in ES2015.

Thanks,

***Andrés Alejandro García Hurtado***

**Comment by edgurgel** [comment]
Hi @Angarsk8 , you should probably use the mailing list for questions like this. 

More: https://github.com/elixir-lang/elixir/blob/ecd86761da45bec47c0b2db7b7054fd2e0f603c3/CONTRIBUTING.md#using-the-issue-tracker

**Comment by Angarsk8** [comment]
Great!
