### ISSUE TITLE
The access syntax should probably detect literal atoms and, maybe, whitespace

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#4070]
Here is an example of a case where a bug can be introduced by accident:

```elixir
def handle_call(:foo, _from, state) do
  stuff = do_stuff()
  {:reply [{:this, :good, stuff}], state}
end
```

Note the missing comma after `:reply`.

What I think can be improved:

1. Check if the argument preceding the `[]` is a literal atom and error if it's not `nil`. Should warn or error as well in the case of `nil` as that is a no-op pretty much.
2. We could warn if there is a space between the argument and the `[]`.

**Comment by josevalim** [comment]
We can warn but only for literals. That's because this is valid syntax:

    reply [{:this, :good, stuff}]

That said, I would rather implement just `1`. It would cover all cases.

**Comment by alco** [comment]
:heart_decoration:
