### ISSUE TITLE
Logger.ErrorHandler crash on 1.2.0-rc0.

### ISSUE THREAD

**Issue by hrefhref** [elixir-lang/elixir#4073]
Using Elixir 1.2.0-rc0 on erlang 18.

```
2015-12-13 15:31:30.444 [error] GenEvent handler Logger.ErrorHandler installed at :error_logger
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Logger.Translator.child_info/2
        (logger) lib/logger/translator.ex:174: Logger.Translator.child_info(:debug, [name: :writer, mfargs: {:rabbit_writer, :start_link, [#Port<0.12347>, 0, 4096,
:rabbit_framing_amqp_0_9_1, #PID<0.493.0>, "client 127.0.0.1:46965 -> 127.0.0.1:5672"]}, restart_type: :transient, shutdown: 4294967295, child_type: :worker])
        (logger) lib/logger/translator.ex:159: Logger.Translator.translate_progress/2
        (logger) lib/logger/error_handler.ex:120: Logger.ErrorHandler.translate/6
        (logger) lib/logger/error_handler.ex:62: Logger.ErrorHandler.log_event/5
        (logger) lib/logger/error_handler.ex:27: Logger.ErrorHandler.handle_event/2
        (stdlib) gen_event.erl:538: :gen_event.server_update/4
        (stdlib) gen_event.erl:520: :gen_event.server_notify/4
        (stdlib) gen_event.erl:261: :gen_event.handle_msg/5
        (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

How to reproduce: with https://github.com/hrefhref/elixir-1.2.0rc0-logger-crash, in IEx:

```
AMQP.Connection.open("amqp://none:none@elixir-lang.org")
```

It works fine with Elixir 1.1.

**Comment by fishcakez** [comment]
I don't think this issue is directly related to upgrading from Elixir 1.1 to 1.2, though perhaps some other behaviour changes to cause a crash that generates the error.

The `name` key is not from an OTP supervisor report. If you are using a custom supervisor you should use a different report name than `:supervisor_report` or to use the same terms as `:supervisor`. If `:name` is switched for `:id` then it should work I think. It might be this change is required in a dependency I did not try but rabbit has a habbit of reimplement OTP behaviours.

**Comment by josevalim** [comment]
Shouldn't we be more resilient to this then? Rabbit may be doing some
incorrect but we should not crash on it, should we?

On Sunday, December 13, 2015, James Fish <notifications@github.com> wrote:

> Closed #4073 <https://github.com/elixir-lang/elixir/issues/4073>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4073#event-490405951>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by fishcakez** [comment]
Well I think we should accept `name` in this case because I did some digging through git and it use to be `name`.

I would prefer not to be too resilient but if we can handle an expected error that is ok.

**Comment by lexmag** [comment]
For the reference: https://github.com/elixir-lang/elixir/commit/511cb5d3a58c4ee9900c26f010154200c313a4e5#diff-6bf697cfce89d8072ae720a3aa4b7e2bL31.
