### ISSUE TITLE
Elixir v1.2.0-rc.0: Keyword.new not backwards compatible

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#4074]
Hi all,

My tests has picked up what may be a backwards incompatibility.

In the 1.1 Keyword doc there is an example of new:

```elixir
Keyword.new([{:b, 1}, {:a, 2}])
```

with the result being

```elixir
[a: 2, b: 1]
```

In v1.2.0-rc.0 you get

```elixir
[b: 1, a: 2]
```

BTW The 1.2 docs agree with the 1.2 behaviour.

Can't find anything in the release notes to suggest the behaviour of Keyword.new is changing.

**Comment by josevalim** [comment]
Thank you. I am not sure if this is backwards incompatible because afaik Keyword.new did not guarantee any ordering. We only guarantee key uniqueness.

**Comment by lexmag** [comment]
It could be considered backwards incompatible change since we have never clearly stated that there is no order guarantee until v1.2 (we just have always thought there is no one), but I think what we have today is how it should be.

**Comment by ianrumford** [comment]
I agree the docs have never stated explicitly the ordering but it works differently and v1.2.0-rc.0 is therefore not strictly compatible with previous versions.

But lets move on.  This may just be a documentation issue:  is the intention that v1.2.0 confirms Keyword.new to offer no ordering guarantees at all?

If so I (and others) who need consistent ordering can "wrap" new in some way e.g. put?  Not a big deal but what can we rely on re ordering?

**Comment by josevalim** [comment]
If you need ordering, uniq_by is your best shot.

On Sunday, December 13, 2015, Ian Rumford <notifications@github.com> wrote:

> I agree the docs have never stated explicitly the ordering but it works
> differently and v1.2.0-rc.0 is therefore not strictly compatible with
> previous versions.
>
> But lets move on. This may just be a documentation issue: is the intention
> that v1.2.0 confirms Keyword.new to offer no ordering guarantees at all?
>
> If so I (and others) who need consistent ordering can "wrap" new in some
> way e.g. put? Not a big deal but what can we rely on re ordering?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4074#issuecomment-164272281>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ianrumford** [comment]
Thanks, I will take a look.

BTW I have just (re)read this in the (1.1) docs:

"The functions in Keyword do not guarantee any property when it comes to ordering. "

Fine:  you guys have made it clear absolutely what the intention is re ordering.
