### ISSUE TITLE
mix --version gives wrong result on Windows

### ISSUE THREAD

**Issue by f-lombardo** [elixir-lang/elixir#4075]
On Windows the --version switch is parsed by elixir an not by mix,

![mix --version](https://cloud.githubusercontent.com/assets/280709/11679834/5d11f6b6-9e54-11e5-8194-0fe4f065b490.PNG)

See
https://github.com/KronicDeth/intellij-elixir/pull/220

**Comment by josevalim** [comment]
It always shows the elixir version because the mix version is the elixir
version.

On Sunday, December 13, 2015, Franco Lombardo <notifications@github.com>
wrote:

> On Windows the --version switch is parsed by elixir an not by mix,
>
> [image: mix --version]
> <https://camo.githubusercontent.com/5baedd7580f4cd0ffa30df689581a75375642434/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f3238303730392f31313637393833342f35643131663662362d396535342d313165352d383139342d306665346630363562343930504e47>
>
> See
> https://githubcom/KronicDeth/intellij-elixir/pull/220
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4075>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Ignore me, this is a bug.

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Closing in favor of the PR.
