### ISSUE TITLE
No longer include Erlang compilers by default

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4083]
99% of mix projects don't use those compilers, let's make them opt-in and shave some subseconds from compile times.

**Comment by ericmj** [comment]
This is a breaking change so should be moved to 2.0.0.

**Comment by josevalim** [comment]
Yeah, I was wondering if we could get away with it. Another option is to
emit a warning if you do not explicitly specify it, giving an upgrade path.
Thoughts?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by c0b** [comment]
I would like a soft deprecation warning (with a solution url for mixed language projects) in 1.3; I do have projects were pure erlang code but I switched to use elixir compiler and exrm to manage, then I started to develop new features in elixir, old code were still in erlang and I hope this warning can come with a solution url for how to declare mix project still support both languages and make sure works in upcoming 2.0

**Comment by josevalim** [comment]
We will always support both languages, the question is which one we should attempt to compile by default. At this point, I think we should leave the compilers there by default, instead I will make sure the noop cost is as low as possible. Thank you! :)
