### ISSUE TITLE
Provide mix task that removes only built artifacts

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4088]
See #333.

The issue is that "mix deps.clean plug" removes the dependency and built artifacts. We need to either:

1. Make "mix deps.clean" remove only the build artifacts by default with an --force flag (or similar) that removes everything

2. Keep "mix deps.clean" removing everything (deps and built) but provide an option that removes only the build "mix deps.clean plug --only-builds"

3. Provide a new task that removes the build explicitly

Thoughts?

**Comment by lexmag** [comment]
I like option _1._, but don't think `--force` flag will work here as it changes behaviour, how about `full` or `implode`?

**Comment by tuvistavie** [comment]
I don't know if a breaking change is acceptable here, but the 1st version with `--purge` to remove the dependencies as well seems to me quite natural.

By the way, I would love to give this one a try.

**Comment by josevalim** [comment]
Yes, we should probably drop 1 for it being backwards incompatible. "deps.purge" is not a bad idea either.

**Comment by tuvistavie** [comment]
I feel that two commands would be a little confusing.
Just by looking at it, no way to know if `mix deps.clean` will clean more than `mix deps.purge`.
On the other hand, `mix deps.clean --build-only`, or something similar would be obvious.
As one command is really a subset of the other, I think a flag is more appropriate.

**Comment by josevalim** [comment]
Yeah, so let's go with a `--build` flag that removes the build exclusively. `mix deps.clean --build plug` would be fine.

**Comment by tuvistavie** [comment]
I am going to give it a try.
The behaviour should be the same regardless of whether the `--unused` or `--all` flag is passed, right?

**Comment by josevalim** [comment]
Yes, those flags are orthogonal to `--build`.
