### ISSUE TITLE
Mix reports invalid task name after going through the compilation

### ISSUE THREAD

**Issue by handnot2** [elixir-lang/elixir#4090]
It would be good to report issues such as invalid task names before performing any implicit compilation.

Erlang 18.2/Elixir 1.2.0-rc0

**Comment by michalmuskala** [comment]
I believe there is a good reason compilation is done before: a task with such a name could be defined in one of your dependencies or in your application, but not yet compiled - there would be no way to find such a task without compiling the project.

**Comment by handnot2** [comment]
I understand. Thanks. Here is the usability perspective:

1. Chances of discovering new tasks by doing compilation is far less than chances of typo/incorrect task names.
2. Started "perceiving" this as a issue when dealing with projects of moderate size!
3. A simple prompt could mitigate the problem: "Tasks <task-name> not found. (proceed if this is a newly added task). Do you want to proceed: Y/n

Don't want to complicate this unnecessarily! :-) I would understand if this is not fixed.

**Comment by josevalim** [comment]
Yes, @michalmuskala is correct, asking would be too much. Imagine after you create a phoenix application, you should run `mix ecto.create` and now there is a prompt. Thanks for the report though.
