### ISSUE TITLE
ExUnit ExUnit.CaptureIO.capture_io_with_result

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/elixir#4095]
I found it useful to capture (or even just suppress and ignore) output of a function and also being able to capture the result. After having whipped up a quick and dirty solution for Earmark, (that even breaks Travis) I thought I have a look at ExUnit itself.

Hopefully this is useful.

**Comment by whatyouhide** [comment]
When I have to do this, I usually send myself a message:

```elixir
test "foo" do
  output = capture_io fn ->
    IO.puts("foo")
    send self(), :result
  end
  
  assert_receive :result
end
```

Are there problems with this approach?

**Comment by alco** [comment]
You could also assert right inside the function you're passing to `capture_io`.

**Comment by josevalim** [comment]
Yes, I would like to avoid the extra function. @whatyouhide and @alco gave good suggestions, I will even add them to the docs. Thank you!

**Comment by RobertDober** [comment]
Both ideas look good, probably I prefer the assert inside the capture, but maybe I should learn to valre message sending more.
Funny that I did exactly the same thing when rewriting the tests for the now defunct `capture_io_with_result` function ;).
Ty all for the feedback.

**Comment by RobertDober** [comment]
@josevalim :+1: adding to the docs will help newbies like me, but it was good practice for me anyway.
