### ISSUE TITLE
feature request: need debugability for mix build tool

### ISSUE THREAD

**Issue by c0b** [elixir-lang/elixir#4099]
I'm from C/Erlang background to Elixir world, have an old pure Erlang project which was built based on C/Automake/Autoconf/Makefile as the build tool, for some reason we don't want to maintain the old building way and want to move on, now evaluating rebar/rebar3 or directly move to elixir's mix tool, I created an almost empty `mix.exs` structure for erlang app, then `mix compile` automatically recognized all my `src/*.erl` files and tried to compile all of them; but the problem is this Erlang project is still using some `*.hrl` files for Erlang record, in Makefiles we used to call `erlc` like a gcc compiler, make by default will show the full command line `erlc -I dir/to/hdr_files/ +{parse_transform, ...} ...` for how does it compile, and where it could fail;
this mix tool seems not showing build process at all, I have been reading all the mix documentation for 3 days and asked questions in #2665 still can't figure out how to pass in compiler options, neither I found any debugability for mix tool, I've tried `mix -h` `mix --help` `mix help` all are showing a list of available commands, `mix -v` `mix --verbose` the `-v` shows `mix --version` actually, I don't see anywhere documenting it; is there a full reference for all available mix command line switches?

links here 1 is a reference I can't find a good tutorial how to write the compiler options for erlang into the mix.exs; 2 is the only blog entry isn't very detailed;

1. http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Compile.Erlang.html
2. http://featurebranch.com/using-mix-to-compile-your-erlang-projects/

this issue is created as request for documentation/tutorial, or may need some actually code changes, ideally as a build tool, I am expecting:
1. like `make --debug` or `--verbose` to show all compilation process details, for where it didn't work, and possible suggestions,
2. a command switch to stop at first error, because currently `mix compile` tries to compile all my `src/*.erl` files and until last failure, I don't see an option to make it stop at first compilation error;
3. the ability to build a single file,
4. for `-h` or `--help` to show a full list (or most useful) of all command switches;
5. if like nodejs Gulp can have watch and do continuously build in background would be wonderful.

**Comment by josevalim** [comment]
To get documentation for any task, run `mix help compile.erlang`. I have tried the erlc_options inside `def project` and it worked as discussed in #2665. Do you hvae a project that reproduces the issues you are running into?

1, 2, and 3 are their own issues, I will gladly open up issues for 1 and 2. I am not sure if 3 is needed so let's wait for more feedback. I think there are custom projects that provide 5.

**Comment by crquan** [comment]
I have known `mix help compile` to show per command help; but is there a central `mix -h` ?? that include `mix -v` to show version, and might accept more command switches?

**Comment by crquan** [comment]
if #4106 and #4107 hasn't been merged, why is this issued closed first?

**Comment by josevalim** [comment]
@crquan this issue was closed because it was 5 reports in one. We have broken into relevant smaller issues that we think we should act on and closed it.

**Comment by josevalim** [comment]
To be clear, "closed" does not mean solved, it means we are no longer tracking it.

**Comment by c0b** [comment]
> I  am not sure if 3 is needed so let's wait for more feedback.

then where is the place to discuss 3 ? and where is to a global `mix -h`? to my background, `make help` is usually implemented by a make target named `help` in the Makefile, and `make -h` or `make --help` is for the tool itself to print some globally usable command switches, like `mix -v` to show version;

is there a command switch to print all available command switches? or is `mix -v` the only one

**Comment by josevalim** [comment]
No, there is no global command switches because everyone can add new tasks,
anytime. Therefore each task should document the switches it accepts. The
only "global" switches are -h and -v and they only exist because people
generally expect them to work. :)

On Wednesday, December 23, 2015, Mr C0B <notifications@github.com> wrote:

> I am not sure if 3 is needed so let's wait for more feedback.
>
> then where is the place to discuss 3 ? and where is to a global mix -h?
> to my background, make help is usually implemented by a make target named
> help in the Makefile, and make -h or make --help is for the tool itself
> to print some globally usable command switches, like mix -v to show
> version;
>
> is there a command switch to print all available command switches? or is mix
> -v the only one
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4099#issuecomment-166989065>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by c0b** [comment]
could you help on how to convert this erlc compile command line? it was built with make by this erlc command line, here it need `-pa` to specify where to find parse transformers,

```console
(cd src/; /usr/bin/erlc +debug_info -pa "../fw/template/erlang/" -pa ../src \
    -I ../src +'{ parse_transform, vsn_trans }' \
                +"{ fw_package_version, '1.2.3' }" \
                +'{ parse_transform, oldrecord_trans }' \
      -DHAVE_EUNIT=1   my_source.erl )
```

I have tried this way but it doesn't work; unable to find the parse transformers: `undefined parse transform 'oldrecord_trans'` ; how to debug this and show its `code:get_path()` ?

```elixir
     erlc_options: [{:pa, "fw/template/erlang/"},
                    {:d, :'HAVE_EUNIT', 1},
                    {:parse_transform, :oldrecord_trans},
                    {:fw_package_version, :'1.2.3'},
                    {:parse_transform, :vsn_trans},
                    :debug_info],
```

**Comment by josevalim** [comment]
Your options seems to be ok except for the `:pa` one. `:pa` is not a compiler option. According to the error, all other options are properly given but the parse transform cannot be found. Where is the parse transform supposed to be? Your project must follow the regular OTP structure to work with Mix (or Rebar) otherwise things won't work as expected.

**Comment by c0b** [comment]
the parse transformers and provided by fw/template and located under `"fw/template/erlang/"`; in Makefile it is passed by `erlc -pa ... ` but in mix.exs so how to pass additional patha to erl ?

**Comment by c0b** [comment]
I found `elixir -pa ./fw/template/erlang -S mix` is running fine, but would still prefer to do it via `code:add_patha(...)` in code dynamically

BTW, can I do the same trick like in rebar platform_define ? to differentiate building on different erlang versions,
https://blog.kempkens.io/posts/erlang-17-0-supporting-deprecated-types-without-removing-warnings_as_errors/

```erlang
{erl_opts, [
  {platform_define, "^[0-9]+", namespaced_types},
  debug_info,
  warnings_as_errors
]}.
```

**Comment by josevalim** [comment]
There is no platform define in Mix.

You could in theory solve this by doing:

    Code.prepend_path("fw/template/erlang")

At the top of your mix.exs file.
