### ISSUE TITLE
[EEx] - Strange Escaping with EEx.eval_string

### ISSUE THREAD

**Issue by bmalum** [elixir-lang/elixir#4101]
Hi Elixir Devs

just tired to use an `.eex` Template for LaTeX-files and I saw some strange behaviour. 

```elixir
➜  ~  iex
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.1.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> IO.puts("\{section}{Hello World}")
{section}{Hello World}
:ok
iex(2)> IO.puts("\\{section}{Hello World}")
\{section}{Hello World}
:ok
iex(3)> EEx.eval_string "\{section}{Hello World} <%= bar %>", [bar: "baz"] 
"{section}{Hello World} baz"
iex(4)> EEx.eval_string "\\{section}{Hello World} <%= bar %>", [bar: "baz"]
"\\{section}{Hello World} baz"
```

Okay well it seems that the Backslash needs to be escaped and according to the [Interpolation and escaping in sigils](http://elixir-lang.org/getting-started/sigils.html#interpolation-and-escaping-in-sigils) `\\section` should escape to `\section` but I get `\\section` and without escaping the backslash I get ` ection` - does also happen with letters and numbers except `a` `b` `d` `e` `f`.

 I asked in the `#elixir-lang` channel but nobody responded. So what did i wrong, or is it a bug?

**Comment by alco** [comment]
It's not a bug, it's the same difference as when you inspect a string (which IEx does by default) vs print it:

```
iex(1)> "\\{section}{Hello World} baz"
"\\{section}{Hello World} baz"

iex(2)> IO.puts "\\{section}{Hello World} baz"
\{section}{Hello World} baz
```

If you `IO.puts` the string returned from `EEx.eval_string` you'll get the same result.
