### ISSUE TITLE
Support MIX_DEBUG=1 that prints each task being run

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4106]
We should add debug mode for Mix that will print each task being run.

* [ ] Introduce `Mix.debug?/0` (to read) and `Mix.debug/1` (to write)
* [ ] Mix.CLI should check if MIX_DEBUG is set and set the mode accordingly (default is false)
* [ ] If `Mix.debug?` is true, we should print whenever a task is invoked

Original report: #4099

**Comment by tuvistavie** [comment]
I would love to give this one a try!
