### ISSUE TITLE
Beware of some compilers' return value as it breaks Mix.Compilers.Erlang.compile/6

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#4111]
The `compile.yecc` compiler supports yecc-specific options with `:yecc_options` in `mix.exs`. Some of these options can change the return value of `:yecc.file/2`: by default this function returns `{:ok, _}` or `:error`, but for example, with the `return_errors: true` it returns `{:ok, _}` or `{:error, _, _}`. Other options (such as `return_warnings: true`) can change the return value as well.

This happens [here](https://github.com/elixir-lang/elixir/blob/5968df9649bc293a8361aa951feb0f4301bcb892/lib/mix/lib/mix/compilers/erlang.ex#L150-L154), in `Mix.Compilers.Erlang.interpret_result/2`, where only the `{:ok, _}` and `:error` results are checked in the `case` statement.

```
** (CaseClauseError) no case clause matching: {:error, [{'src/another.yrl', [{:none, :yecc, :no_grammar_rules}, {:none, :yecc, :nonterminals_missing}, {:none, :yecc, :rootsymbol_missing}, {:none, :yecc, :terminals_missing}]}], []}
    (mix) lib/mix/compilers/erlang.ex:135: Mix.Compilers.Erlang.interpret_result/2
    (mix) lib/mix/compilers/erlang.ex:84: anonymous fn/3 in Mix.Compilers.Erlang.compile/3
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/compilers/erlang.ex:83: Mix.Compilers.Erlang.compile/3
    (mix) lib/mix/cli.ex:57: Mix.CLI.run_task/2
```

I'm opening an issue and not directly a PR because I'm not sure how you'd want me to tackle this. My idea is that we explicitly require the callback passed to `Mix.Compilers.Erlang.compile/6` to return `{:ok, _} | :error` and keep only handling those cases in `Mix.Compilers.Erlang.interpret_result/2`; then, in each specific compiler, we make sure that the callback actually returns that. In the yecc compiler, this would mean overriding the `:return_errors` and `:return_warnings` options (as we already do when overriding `report: true`).

Btw, I'd love to tackle this one; I found it while working on #4107.

Wdyt?

**Comment by josevalim** [comment]
It is silly to pass returning `:return_warnings` and `:return_errors` because you can't access them anyway. We should just discard those options as it doesn't make sense for the compiler.

**Comment by whatyouhide** [comment]
@josevalim I agree you can't do anything with it. Yep, discarding makes as much sense as overriding them to be `false
