### ISSUE TITLE
Spec mismatch from Dialyzer's success typing for __info__/1

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#4113]
I created a new mix project `mix new dial`, added [dialyze](github.com/fishcakez/dialyze) to it and ran `mix dialyze --specdiffs`. This is what I got:

```
lib/dial.ex:1: Type specification 'Elixir.Dial':'__info__'(atom()) -> atom() | [{atom(),any()}] is not equal to the success typing: 'Elixir.Dial':'__info__'('attributes' | 'compile' | 'exports' | 'functions' | 'macros' | 'md5' | 'module' | 'native_addresses') -> atom() | [{atom(),_} | {atom(),byte(),integer()}]
```

Notice the last type of the return value Dialyzer has deduced:

```
[{atom(),_} | {atom(),byte(),integer()}]
```

That doesn't match Elixir's spec

```
[{atom(),any()}]
```

**Comment by josevalim** [comment]
This is the where the spec is generated, can you please amend it accordingly? https://github.com/elixir-lang/elixir/blob/5968df9649bc293a8361aa951feb0f4301bcb892/lib/elixir/src/elixir_module.erl#L434-L450

**Comment by alco** [comment]
I found that, but didn't figure it out in a minute :) I can try to amend it, will get back to you tonight.
