### ISSUE TITLE
Mix.env/0 always returns prod for application dependencies

### ISSUE THREAD

**Issue by rbishop** [elixir-lang/elixir#4119]
Elixir version: 1.1.1

I have a dependency ([honeybadger-elixir](https://honeybadger-io/honeybadger-elixir)) and when I'm compiling my application that makes use of that dependency, `Mix.env/0` returns `:prod` when that dependency is being compiled. This happens even if I set `MIX_ENV=dev` before running any `mix` or `iex` commands. When my application is compiling, `Mix.env/0` returns the correct environment.

**Comment by nuss-justin** [comment]
This sounds correct to me. From the [Introduction to Mix](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html):

> Note: If you add dependencies to your project, they will not inherit your project’s environment, but instead run with their :prod environment settings!

**Comment by rbishop** [comment]
Thank you for sharing that note. That seems like surprising behavior to me. Especially with a common pattern of using macros + environment to perform optimizations.

**Comment by josevalim** [comment]
I would argue that the opposite would be much more surprising. Imagine every time you pool Phoenix in, it runs as a dependency without optimizations and bringing its development dependencies (like ex_doc). Dependencies are meant to run in prod. If you want the opposite, pass the `:env` option.
