### ISSUE TITLE
Mix does not recompile files after manually deleting a .beam from _build

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#4124]
Elixir version 5968df9.

```
$ mix new recomp
$ cd recomp
$ mix compile
Compiled lib/recomp.ex
Generated recomp app
Consolidated List.Chars
Consolidated Collectable
Consolidated String.Chars
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
$ rm _build/dev/lib/recomp/ebin/Elixir.Recomp.beam
$ mix compile
Generated recomp app
$ mix run -e "Recomp.module_info"
** (UndefinedFunctionError) undefined function Recomp.module_info/0 (module Recomp is not available)
$ mix clean; mix compile
Compiled lib/recomp.ex
Generated recomp app
Consolidated List.Chars
Consolidated Collectable
Consolidated String.Chars
Consolidated Enumerable
Consolidated IEx.Info
Consolidated Inspect
$ mix run -e "Recomp.module_info"
```

**Comment by josevalim** [comment]
I don't think we should. Why are files being removed from build manually?
If you change the manifest file, for example, things may not go as expected
as well.

On Tuesday, December 29, 2015, Alexei Sholik <notifications@github.com>
wrote:

> Elixir version 5968df9
> <https://github.com/elixir-lang/elixir/commit/5968df9649bc293a8361aa951feb0f4301bcb892>
> .
>
> $ mix new recomp
> $ cd recomp
> $ mix compile
> Compiled lib/recomp.ex
> Generated recomp app
> Consolidated List.Chars
> Consolidated Collectable
> Consolidated String.Chars
> Consolidated Enumerable
> Consolidated IEx.Info
> Consolidated Inspect
> $ rm _build/dev/lib/recomp/ebin/Elixir.Recomp.beam
> $ mix compile
> Generated recomp app
> $ mix run -e "Recomp.module_info"
> ** (UndefinedFunctionError) undefined function Recomp.module_info/0 (module Recomp is not available)
> $ mix clean; mix compile
> Compiled lib/recomp.ex
> Generated recomp app
> Consolidated List.Chars
> Consolidated Collectable
> Consolidated String.Chars
> Consolidated Enumerable
> Consolidated IEx.Info
> Consolidated Inspect
> $ mix run -e "Recomp.module_info"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4124>.
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by alco** [comment]
It makes Mix's guarantees weaker if this is allowed.

Mix claims to take care of generating a correctly filled in .app file for the project. However, when there's a missing .beam in `ebin/`, it simply removes the module from the list of modules in the .app file, which breaks the correspondence between the Mix project tree and the OTP application actually being produced from it.

Regardless of the reasons behind a missing .beam file, I think it complicates matters if it is necessary to take the contents of `ebin/` into account when explaining how a Mix project tree is built.

Although I understand that it might not be worth addressing since there's a known way to reset a Mix project into a known state by executing `mix clean`. It was unexpected behaviour to me, in the context of how I thought Mix worked, that's why I filed the issue.

**Comment by josevalim** [comment]
Mix does not guarantee you can fiddle with `_build`. Therefore, why are you fiddling with `_build`? The only way to solve this is to do an extra file system check for every entry in the manifest, which defeats the point of the manifest as it is meant to reflect what is on disk exactly so we don't need to do such lookups. Otherwise we may as well encode all this information in the bytecode and get rid of the manifest. :)
