### ISSUE TITLE
Confusing behaviour with duplicate test names

### ISSUE THREAD

**Issue by trinode** [elixir-lang/elixir#4125]
If you have two tests with similar names one of them is completely (and silently) ignored, whether that be due to poor naming, or copy paste fail, it would be good to know that if any of your test is being automatically ignored.

I initially started doing a pull request to add a raise if a duplicate name was defined but then this test failed:-

https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/test/ex_unit_test.exs#L190-L208

Which made me think that this behaviour was by design?

I'd be fine with the behaviour to be as is but I think the user should be informed (I wasn't even aware the name was being used as a key until this point, I thought it was used only for display purposes).

What do you guys think?

**Comment by josevalim** [comment]
In the example above I do get a proper warning:

```iex
iex(2)>       defmodule TestWithSameNames do
...(2)>         use ExUnit.Case
...(2)>
...(2)>         test "same name, different outcome" do
...(2)>           assert 1 == 1
...(2)>         end
...(2)>
...(2)>         test "same name, different outcome" do
...(2)>           assert 1 == 2
...(2)>         end
...(2)>       end
iex:9: warning: this clause cannot match because a previous clause at line 5 always matches
```

When we had this discussion in the past was exactly that Elixir already warns, we just don't need to run the test twice.

**Comment by trinode** [comment]
Ah, you do get a warning at _compile_ time, but not at test run time. (the former would be a _lot_ less likely to be seen when using the test suite since things are only compiled when changed, right?)

I don't suggest running the test twice, but to warn (when the tests are run) that a duplicate name (which is actually meant to be unique) has been used, and to suggest that the test should be renamed or deleted if it is a duplicate. 

This could be done in an else clause here, unless I'm mistaken?:
https://github.com/elixir-lang/elixir/blob/5ff37dc1b9c46bccd77370f09387880e6bfa51eb/lib/ex_unit/lib/ex_unit/case.ex#L312-L315

**Comment by josevalim** [comment]
> Ah, you do get a warning at compile time, but not at test run time. (the former would be a lot less likely to be seen when using the test suite since things are only compiled when changed, right?)

Tests are `.exs` files (script files), so you would always see the warning because you compile and run at once.

And the clause is also at compile time. :)

**Comment by lexmag** [comment]
This warning will be printed in every test run.
To make it even more stricter you can have `Code.compiler_options(warnings_as_errors: true)` in your `test_helper.exs` file.
