### ISSUE TITLE
multiple `when` in guard does not raise error during compilation

### ISSUE THREAD

**Issue by adamkittelson** [elixir-lang/elixir#4127]
I just accidentally included `when` twice in a guard and was surprised it didn't raise an error during compilation, should it have? e.g. `def foo(bar, baz) when bar < baz when is_float(bar) and is_float(baz)` (second when should've been `and`)

I think it dropped the second when and everything thereafter and just became `def foo(bar, baz) when bar < baz` in terms of execution.

**Comment by alco** [comment]
Multiple `when`s work like `or`. For example, https://github.com/elixir-lang/elixir/blob/65ec10839941065f77aa21f9639e1ac65dcd0709/lib/elixir/lib/task/supervised.ex#L102

**Comment by josevalim** [comment]
They don't work like `or` in the sense that if you have an error inside an `or` both sides fail. With `when`, they are considered distinct, isolated clauses. So if one errors (let's say because you called length on a tuple), the other still runs.

**Comment by alco** [comment]
subtle

**Comment by adamkittelson** [comment]
Thanks for the clarification. :D
