### ISSUE TITLE
Fail when install elixir `recompile this module with an R16B02 compiler.`

### ISSUE THREAD

**Issue by vanloc0301** [elixir-lang/elixir#4136]
I install elixir in ubuntu but it show error like this:

![selection_001](https://cloud.githubusercontent.com/assets/4168981/12073992/2de2acfa-b16e-11e5-8757-e1f52c06daeb.png)

I was find internet but don't have any resource for this problem.

I install like in homepage of elixir.

`Ubuntu 12.04 and 14.04 / Debian 7
    Add Erlang Solutions repo: wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
    Run: sudo apt-get update
    Install the Erlang/OTP platform and all of its applications: sudo apt-get install esl-erlang
    Install Elixir: sudo apt-get install elixir`

I try uninstall erlang to reinstall but not success. 

I'm try: `sudo apt-get --purge remove erlang*` but it's not success.
Thanks.

**Comment by josevalim** [comment]
You have an old erlang version. Make sure to uninstall all of your previous Erlang versions and install Erlang 18.

**Comment by vanloc0301** [comment]
How to uninstall all Erlang in Ubuntu?
I was try `sudo apt-get --purge remove erlang*` but it's not success.

**Comment by josevalim** [comment]
Sorry, I can't help you there, I don't have a lot of knowledge with ubuntu. :( WHat happens if you run `sudo apt-get --purge remove erlang` without the asterisk?

**Comment by josevalim** [comment]
Or: http://stackoverflow.com/a/25625801/588267
