### ISSUE TITLE
Show stacktrace on i(pid) in IEx

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4139]
It can be retrieved with: `Process.info(pid, :current_stacktrace)`. Thoughts?

**Comment by alco** [comment]
IMO the current output is already quite long. And there's already this section:

> Description
>  Use Process.info/1 to get more info about this process

I would rather mention `Process.info/2` in there or, alternatively, say
> Run `h Process.info` to find out how to get more info about a process.
