### ISSUE TITLE
Mix shell helpers should raise an exception when no interactive tty present

### ISSUE THREAD

**Issue by schnittchen** [elixir-lang/elixir#4140]

**Comment by schnittchen** [comment]
Specifically, I've waited quite a while until I noticed that my non-interactive build had printed

```
Could not find Hex, which is needed to build dependency :exrm
Shall I install Hex? [Yn]
```

and was waiting for a reply.

Things like these are key to successful automation...

**Comment by josevalim** [comment]
I don't think there is a way for us to know nothing is listening on stdin. Just run `mix local.hex` before starting.

**Comment by josevalim** [comment]
Also, even if we did, we would rather abort than just download and install things automatically.

**Comment by schnittchen** [comment]
It should not do anything automatically, but instead fail loudly, because there is no way to continue.

If it's impossible to detect, what about wrapping a generous timeout (like 1min) around it?

**Comment by tuvistavie** [comment]
I totally agree that nothing should be done automatically,
but I think an option similar to `apt-get install -y` or `pacman -S --noconfirm` could be handy,
especially when using automation tools where a prompt is really not very useful.
I would be glad to give it a try if you are interested.

**Comment by schnittchen** [comment]
This would be a global option, not a per-task one. Looks like that would be the first one: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/cli.ex

**Comment by schnittchen** [comment]
Maybe an environment variable would be a better fit for this.

**Comment by tuvistavie** [comment]
I agree. It would be nice to allow something like `NOCONFIRM=1 mix deps.get`.
Any thoughts?
/cc @josevalim

**Comment by josevalim** [comment]
This particular problem already has a defined solution, there is no need
for adding environment variables to Mix unless required.
