### ISSUE TITLE
Lacking error messages when compiling erlang/rebar dependencies - mix

### ISSUE THREAD

**Issue by lau** [elixir-lang/elixir#4144]
I have had problems compiling the `:certifi` package. The error message would just say that the compile failed, but no error messages from the compilation process were visible. Eventually I guessed that it might have something to do with a low amount of RAM. So I tried increasing the RAM size on the VM I was using from 512MB to 1024MB. That solved the problem. But there were no error messages saying anything about *why* compilation of certifi failed.

It would be nice if the error message when running mix compile would display some error messages from the compilation failure.

To reproduce:
- Make a mix project on a machine with little RAM. E.g. an Ubuntu trusty 64 bit machine with 512MB of RAM. I used https://github.com/lau/vagrant_elixir and set the RAM in Vagrantfile to 512
- add `{:hackney, "~> 1.4.7"},` to dependencies.
- `mix compile`

**Comment by josevalim** [comment]
I am not sure if we can do something. Here is what happens:

1. We run the command
2. The command starts to consume memory
3. The OS kills the process
4. The process returns != 1 status code

The only way we can log something is if the process returns a specific exit status that means "out of memory". Otherwise, we simply don't know.

**Comment by lau** [comment]
Ah, OK, so to improve the experience, changes outside of Elixir would be needed.

"The command" in this case is rebar? Maybe rebar could be responsible for displaying an error message, if rebar somehow is able to detect and error instead of just being killed by the OS? I don't know how rebar could do that, but what if it does the compilation in a separate process and can somehow detect if that process has been killed by the OS and then print out an error message?

**Comment by josevalim** [comment]
> Maybe rebar could be responsible for displaying an error message, if rebar somehow is able to detect and error instead of just being killed by the OS? 

I don't think rebar can do that. We may be able to do that as long as the exit signal sent by the OS implies "killed due to memory consumption" (and only that).

**Comment by josevalim** [comment]
More info here: http://stackoverflow.com/questions/726690/who-killed-my-process-and-why

A quick searched review we basically cannot know why it was killed.

**Comment by lau** [comment]
Today there is already an error message displayed. How about simply changing that error message so that it says that the reason is unknown, but it might have been because of lack of memory. It is probably not a bad guess.

A more advanced version could look at the memory of the machine and only suggest lack of memory if the machine has less than e.g. 2GB of memory.

**Comment by josevalim** [comment]
We don't even know if the error is unknown because the subprocess may have written to stderr. I don't think there is much we can do.

**Comment by josevalim** [comment]
Any guessing we attempt to do will yield bad information in many situations. If we want to guess, in one year time the list of suggestions of possible errors will be 20 lines long.

**Comment by josevalim** [comment]
To be fair, such low memory error trigger is something that should be rather done by the project being compiled.

**Comment by lau** [comment]
That makes sense. Yeah, I agree it should be done by the project.

**Comment by lau** [comment]
Thanks for looking in to it. I just wanted to see if I could prevent someone else from experiencing the same problem.
