### ISSUE TITLE
Type check functions do not use "?" suffix (standard?)

### ISSUE THREAD

**Issue by zackehh** [elixir-lang/elixir#4145]
Excuse me if this has been discussed before, but it occurred to me recently that it's a little odd and I don't think I've seen it discussed. 

Currently there are a number of "type check" functions which can be used in guards; `is_number/1` and co. There's a list of them here: http://elixir-lang.org/getting-started/case-cond-and-if.html. However, in the Elixir core modules most boolean functions are of the form `condition?`; such as `Enum.empty?/1` and `Map.has_key?/2`.

Is there a good reason why these `Kernel` functions should not also follow this pattern? As far as I know the `?` is recognised as a standard (and seems to be encouraged), yet the language itself goes against it here. Doing this would translate things like `is_number/1` to `number?/1`. 

Depending on the response (and whether I'm missing something), this would be a 2.0.0 change - but you could introduce them in 1.x by aliasing them to the current implementation, with a soft deprecation attached.

**Comment by josevalim** [comment]
They do not follow this pattern exactly so we know they can be used in guards. Please see this document: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Naming%20Conventions.md
