### ISSUE TITLE
Support different inspect rendering

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4158]
Today Elixir attempts to include as much information as possible on a single line when inspecting it. We can change this by printing one item per line by passing an option.

**Comment by jisaacstone** [comment]
how would this be different from the `pretty: :true` option?

**Comment by josevalim** [comment]
You can think of `pretty: true` as being equivalent to `pretty: :compact`. We want to support something like `pretty: :expanded` or something of sorts.

**Comment by jisaacstone** [comment]
Understood.
I'd like to take a crack at it :)

I've mocked up some demo output - does this match what you had in mind?

https://gist.github.com/jisaacstone/0cd8ca9c1056d22846c9

**Comment by josevalim** [comment]
I think so, yes. Except 10, "key => value" could be in the same line and 13 is indented with one space. Btw, the old pretty implementation of Inspect.Algebra.pretty was used to do something like that and it is explored in the Lindig's paper, it was changed in this commit:

https://github.com/elixir-lang/elixir/commit/2dc1e41aca4b456ee7644f3c4c97a2205f0df36b

So my suggestion is to allow a third, optional argument in pretty that is the mode which defaults to :compact and move the current pretty implementation to a private function called compact. And create a new private function called `:expanded` with the previous implementation and play with the results there. pretty should then just choose between calling compact or extended.

**Comment by jisaacstone** [comment]
Easiest thing to do was render `:expand` the same as `width: 1` might be rendered.
You can see the result of this implementation here
https://gist.github.com/jisaacstone/1328aa353d8c8d52e51f

Only differences being 4, 10, and 13.

Also thought it should behave as the `:width` option does: `IO.inspect` always honors it, but `Kernel.inspect` will only check `:mode` if `:pretty` is `true`

**Comment by josevalim** [comment]
That's a very nice trick. What happens with width: 0?

Also, 4 is a bug in Elixir. I am fixing it in master. :)

**Comment by jisaacstone** [comment]
The reality is that any width < 6 behaves the same. Negative numbers included.

I'm thinking it might make more sense to add `:expand` to the `:width` option, alongside `:infinity`. Would simplify the code and also the interface. Actually I don't see a reason why a numeric `:width` would ever been needed with `:expand`. So adding is as a width option is much better...

I'll change it this afternoon.

**Comment by josevalim** [comment]
@jisaacstone well, we could just document `pretty: true + width: 0` means each item is printed on its own line. Indeed, I am not sure if we want to add a third option, as you said. /cc @alco @lexmag

**Comment by lexmag** [comment]
I really like idea of having `pretty: true + width: 0` instead. It feels natural, in fact makes you think of "each item is printed on its own line".

> Negative numbers included.

I think we should validate `width` then.
