### ISSUE TITLE
Allow customizing the nouns in ExUnit

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4159]
For example, the quickcheck folks are writing properties, however in the reports they still show up as "tests" instead of "properties". We can make this a bit more generic and support both tests and properties cleanly.

**Comment by tuvistavie** [comment]
I would like to try this one!
Does passing the noun as an option to `ExUnit.start` seems fine?

**Comment by josevalim** [comment]
@tuvistavie no. Because that would push the burden to the library user. It should all be in quickcheckex. I am not sure what is the best solution for this though...

**Comment by antipax** [comment]
Could quickcheckex define a module such that you could do something like:

```elixir
defmodule MyQuickCheckProperties do
  use QuickCheck.Case

  property "blah" do
    ...
  end
end
```

and the `property` func/macro actually ends up translating to something like:

```elixir
test "blah", type: "property" do
  ...
end
```

It still requires the user to "use QuickCheck.Case" instead of "use ExUnit.Case" but that's a pretty common pattern already for Phoenix, Ecto, etc. tests.

**Comment by tuvistavie** [comment]
@josevalim 
> no. Because that would push the burden to the library user. It should all be in quickcheckex. I am not sure what is the best solution for this though...

Oh, absolutely, I was forgetting `ExUnit.start` is called in the test helper.

Just to be make sure I understand the issue properly, we are talking about ExUnit report

```
Finished in 17.1 seconds (9.2s on load, 7.9s on tests)
2753 tests, 0 failures
```

where "test" could be customized in, for example, "property" right?

**Comment by bjfish** [comment]
Would `ExUnit.configure` work for this: https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit.ex#L213
https://github.com/parroty/excheck/blob/master/lib/excheck.ex#L26

Or an init option for CLIFormatter:
https://github.com/parroty/excheck/blob/master/lib/excheck/formatter.ex
https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/cli_formatter.ex#L11

**Comment by josevalim** [comment]
I don't think we want to do it in the formatter because the same suite can have both tests and properties. It is more about allowing a different kind of thing to be defined in ExUnit.

**Comment by antipax** [comment]
@josevalim is my idea above an acceptable way to try implementing this? Would like to take a shot at it, if you approve?

**Comment by josevalim** [comment]
@antipax that's ambiguous because we can match on the context as the second argument there. I am still not sure how this should look like, sorry. :( I will need to investigate it with detail later on. I also know @ericmj is working on related things.

**Comment by antipax** [comment]
Cool, no need to apologize! :)

**Comment by josevalim** [comment]
Although I don't know yet how the final API will look like, I have some ideas on how it should behave internally. We could add a `:type` field to the `ExUnit.Test` struct which defaults to `:test`:

https://github.com/elixir-lang/elixir/blob/3a48c4fdfad28a90c5c15118b36a150b89fbe44d/lib/ex_unit/lib/ex_unit.ex#L78

Now, the CLI formatter when counting how many tests have run, it should do per *type*:

https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/cli_formatter.ex#L130

However I ran into issues regarding the pluralization. If the type is property, how would we pluralize it? It would certainly have to be specified somewhere... and that's where I am stuck right now. I have decided to post this information here in case someone would like to continue working on this.

**Comment by tuvistavie** [comment]
> If the type is property, how would we pluralize it? It would certainly have to be specified somewhere

Would there be any drawbacks to allow passing a plural form also stored as property in `ExUnit.Test`, and default to adding an `s` when it is `nil`?

**Comment by josevalim** [comment]
@tuvistavie it would probably be fine. We could store it as: `{:test, :tests}`, `{:property, :properties}` and so on. It just feels a bit awkward to include this information in the test struct and duplicate it everywhere given it is used in just one place. :(

**Comment by antipax** [comment]
@josevalim perhaps an ExUnit configuration for test types would help?

```elixir
ExUnit.start(test_types: [property: "properties"])
```

and then 

```elixir
%ExUnit.Test{type: :property} 
```

Might not be something a test framework can do without asking the user to add it to their test_helper.exs or config.exs, then, though.

**Comment by josevalim** [comment]
That's a good idea, @antipax. The options on start are simply stored in the app environment so we could probably provide an API that stores there. Maybe `ExUnit.plural_rule("property", "properties")` that will store it and ExQuickCheck could call when it gets started.

**Comment by antipax** [comment]
Ok, gonna work on this

**Comment by josevalim** [comment]
Thank you @antipax!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

@ThomasArts, this will finely allow ExUnit to show "34 properties" as you run tests with ExQuickCheck. Ping me once 1.3.0 is out and I will gladly help if you have any questions!

**Comment by ThomasArts** [comment]
Super cool! It works.

I'll update my QuickCheck wrapper accordingly
