### ISSUE TITLE
Improve ExUnit.AssertionError exception messages

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#4161]
ExUnit prints a very nice exception message when it rescues the assertion. However if the assertion is raised in another process the displayed error is sometimes lacking because the raw exception message is used and it does not contain much information.

An example from ecto:
```
** (EXIT from #PID<0.467.0>) an exception was raised:
         ** (ExUnit.AssertionError) match (=) failed
             integration_test/pg/deadlock_test.exs:40: Ecto.Integration.DeadlockTest.acquire_deadlock/2
             (ecto) lib/ecto/adapters/sql.ex:489: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
             (db_connection) lib/db_connection.ex:1162: DBConnection.transaction_run/3
             (db_connection) lib/db_connection.ex:1084: DBConnection.run_begin/3
             (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by sandeshsoni** [comment]
I am taking this issue, currently working on it

**Comment by sandeshsoni** [comment]
@fishcakez 

Mix tasks give us suggestion if there is a small typo.
For example, for mix testy

    mix testy
    ** (Mix) The task "testy" could not be found. Did you mean "test"?

This is calculated considering String jaro distance.
If there is any mix task name with jar score more than 0.80, it is shown.

I was thinking similar message style.

    assert “foobar” = “fooba”,
    # the error message could be
    match (=) failed. did you mean “footer” on rhs ?

    assert “foo” = “bar”, 
    # the error message could be
    match (=) failed. rhs = “bar"

**Comment by sandeshsoni** [comment]
https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/assertions.ex#L128

How do i get lhs value ? need help.

**Comment by fishcakez** [comment]
The right hand side is likely to be code and the left hand side a pattern, so I don't think strings are a common enough case to worry about just yet.

The issues is not about improving this output:
```
  1) test foo (AppTest)
     test/app_test.exs:11
     match (=) failed
     code: :a = :b
     rhs:  :b
     stacktrace:
       test/app_test.exs:12
```
Its about improving the case where assert is used in a process linked to the test process:
```elixir
Task.async(fn() -> assert :a = :b end) |> Task.await()
```
Which outputs:
```
  1) test foo (AppTest)
     test/app_test.exs:11
     ** (EXIT from #PID<0.189.0>) an exception was raised:
         ** (ExUnit.AssertionError) match (=) failed
             test/app_test.exs:12: anonymous fn/0 in AppTest.test foo/1
             (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
Notice it doesn't tell use the right hand side value and not enough information to debug the issue in most cases. If we didn't have `assert`, we get a much better error:
```
  1) test foo (AppTest)
     test/app_test.exs:11
     ** (EXIT from #PID<0.189.0>) an exception was raised:
         ** (MatchError) no match of right hand side value: :b
             test/app_test.exs:12: anonymous fn/0 in AppTest.test foo/1
             (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by sandeshsoni** [comment]
Ok, i will look into this.

**Comment by sandeshsoni** [comment]
I am still working on this issue. Giving most of my time.
But if this is blocking any other issue, you make take this one.
Not surrendered the issue yet.

**Comment by sandeshsoni** [comment]
As discussed,
changing the error messages.

At the same time, checking for a possibility
supervised.ex (around line no 115), function defp exit/4 has more details like message, value of right etc. 
on inspecting get_reason(log_reason), we can see value of message as well as right.
Trying to figure out how is it that only value of message is picked up. what code is doing this. can we attach value of right/left here itself.

:error_logger.format

**Comment by sandeshsoni** [comment]
@fishcakez 
Here is an update.
Your feedback on error message.

No, I haven't had to keep changing message everywhere or add value of right everywhere. The reason is different.

I feel i am close to what is expected.

```
  1) test assert is used inside a process linked to other process (ExUnit.AssertionsTest)
     test/ex_unit/assertions_test.exs:348
     ** (EXIT from #PID<0.261.0>) an exception was raised:
          ** (ExUnit.AssertionError) "match (=) failed. RHS: :b"
>        here the expression was : 
>        Task.async(fn() -> assert :a = :b end) |> Task.await()

             test/ex_unit/assertions_test.exs:350: anonymous fn/0 in ExUnit.AssertionsTest.test assert is used inside a process linked to other process/1
             (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

.................................
23:51:38.482 [error] Task #PID<0.297.0> started from #PID<0.296.0> terminating
** (ExUnit.AssertionError) "**Assertion with in failed. RHS: ['lorem', 'epsum']**"
>     here the expression was:
>     Task.async(fn() -> assert 'foo' in ['lorem', 'epsum'] end) |> Task.await()

    (ex_unit) lib/ex_unit/assertions.ex:281: ExUnit.Assertions.assert/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<4.52216389/0 in ExUnit.AssertionsTest.test assert is used inside a process linked to other process, 2nd example/1>
    Args: []


  2) test assert is used inside a process linked to other process, 2nd example (ExUnit.AssertionsTest)
     test/ex_unit/assertions_test.exs:359
     ** (EXIT from #PID<0.296.0>) an exception was raised:
         ** (ExUnit.AssertionError) "**Assertion with in failed. RHS: ['lorem', 'epsum']**"
             (ex_unit) lib/ex_unit/assertions.ex:281: ExUnit.Assertions.assert/2
             (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

**Comment by sandeshsoni** [comment]
After some modifications, here is one more update
```
  1) test assert is used inside a process linked to other process (ExUnit.AssertionsTest)
     test/ex_unit/assertions_test.exs:348
     ** (EXIT from #PID<0.302.0>) an exception was raised:
         ** (ExUnit.AssertionError) "match (=) failed. RHS: :b"

>  for
>  Task.async(fn() -> assert :a = :b end) |> Task.await()

             test/ex_unit/assertions_test.exs:350: anonymous fn/0 in ExUnit.AssertionsTest.test assert is used inside a process linked to other process/1
             (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

......
12:20:03.038 [error] Task #PID<0.303.0> started from #PID<0.302.0> terminating
** (ExUnit.AssertionError) "match (=) failed. RHS: :b"
    test/ex_unit/assertions_test.exs:350: anonymous fn/0 in ExUnit.AssertionsTest.test assert is used inside a process linked to other process/1
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<2.6828065/0 in ExUnit.AssertionsTest.test assert is used inside a process linked to other process/1>
    Args: []

12:20:03.052 [error] Task #PID<0.312.0> started from #PID<0.311.0> terminating
** (ExUnit.AssertionError) "Expected exception ArgumentError but nothing was raised"

>  for
>  Task.async(fn() -> assert_raise ArgumentError, fn() -> nil end end) |> Task.await()

    (ex_unit) lib/ex_unit/assertions.ex:285: ExUnit.Assertions.assert/2
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<10.6828065/0 in ExUnit.AssertionsTest.test assert is used inside a process linked to other process, 2nd example/1>
    Args: []


  2) test assert is used inside a process linked to other process, 2nd example (ExUnit.AssertionsTest)
     test/ex_unit/assertions_test.exs:359
     ** (EXIT from #PID<0.311.0>) an exception was raised:
         ** (ExUnit.AssertionError) "Expected exception ArgumentError but nothing was raised"
             (ex_unit) lib/ex_unit/assertions.ex:285: ExUnit.Assertions.assert/2
             (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
             (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

```

**Comment by fishcakez** [comment]
@josevalim @lexmag how much information should we move to the message and how much should we leave to in the struct to only be pretty/colour printed if in the test process? I think if we move all the information to the message it will be less clear for 95% of cases. Perhaps we only need to show the right (and if relevant left) when the assert uses `=`, `==`, `>=`, `match? `?

**Comment by josevalim** [comment]
@fishcakez I would say that, whatever we can show in the message, with similar formatting to the one in the formatter, will be a welcome addition.

**Comment by josevalim** [comment]
But without colors, of course.

**Comment by fishcakez** [comment]
@sandeshsoni this looks great except I think we want the current behaviour when the error occurs in the test process, and only display the extended the message when the error occurs elsewhere.

**Comment by lexmag** [comment]
Hard to say without looking at current approach, are we going to have `message/1` function in `ExUnit.AssertionError`?
I looked briefly how we can get it on formatter level, we can match on `{:EXIT, %ExUnit.AssertionError{}}` there and apply more extensive formatting I think.

**Comment by sandeshsoni** [comment]
@fishcakez 
Did does that mean,
continue the old behavior i.e message when error occurs in normal behavior.

```
>  for :a = :b

     match (=) failed
     code: :a = :b
     rhs:  :b

```
When error occurs in test process.
```
>  for   Task.async(fn() -> assert :a = :b end) |> Task.await()

         ** (ExUnit.AssertionError) match (=) failed. RHS: :b
```
The changes i made should not have any effect on regular error message. i.e MatchError etc. The changes have effect only on ExUnit.AssertionError

**Comment by sandeshsoni** [comment]
@lexmag 
Yes, my current approach is having message/1 in ExUnit.AssertionError

**Comment by sandeshsoni** [comment]
This is the approach.

```
--- a/lib/ex_unit/lib/ex_unit/assertions.ex
+++ b/lib/ex_unit/lib/ex_unit/assertions.ex
@@ -16,6 +16,14 @@ defmodule ExUnit.AssertionError do
   def no_value do
     @no_value
   end
+
+  def message(exception) do
+    if exception.right == @no_value do
+      exception.message
+    else
+      exception.message <>". RHS: " <> inspect exception.right
+    end
+  end
 end
```

**Comment by ybur-yug** [comment]
@sandeshsoni hows your progress on this? I'd be happy to chip in if you'd like any help.

**Comment by sandeshsoni** [comment]
@ybur-yug Its in progress. I am giving a try to thought of lexmag.
If i need help in adding tests, i will ask for help.
Thanks.

**Comment by ybur-yug** [comment]
Sounds good! Thanks @sandeshsoni

**Comment by sandeshsoni** [comment]
work in progress update.

After making changes as suggested by lexmag.
So far achieved this. Adding necessary tests.

```

     test/ex_unit/assertions_test.exs:370
     rhs:  {2, 1}
     "match (match?) failed\nThe following variables were pinned:\n  a = 1"
     code: {:match?, [line: 374],
            [{{:^, [line: 374], [{:a, [line: 374], nil}]}, 1}, {{:., [line: 374], [{:__aliases__, [counter: 0, line: 374], [:Value]}, :tuple]}, [line: 374], []}]}

```
```

     test/ex_unit/assertions_test.exs:346
     rhs:  :b
     "match (=) failed"
     code: {:=, [line: 348], [:a, :b]}

```

**Comment by sandeshsoni** [comment]
@fishcakez 
I am almost done with this issue.
Only tests have to be fixed. I am not sure how do i test these **exit** examples.
Could you give some more information on writing tests for this issue?

Have added code as well as tests on formatter. 

The code is here. May i have your feedback.

https://github.com/elixir-lang/elixir/compare/master...sandeshsoni:4161

Here is how the new code would look like.
```

  1) test assert is used inside a process linked to other process (ExUnit.AssertionsTest)
     test/ex_unit/assertions_test.exs:337
     match (=) failed
     rhs:  :b
     code: {:=, [line: 339], [:a, :b]}

.......

  2) test assert is used inside a process linked to other process, 2nd example (ExUnit.AssertionsTest)
     test/ex_unit/assertions_test.exs:346
     Assertion with in failed
     rhs:  ['lorem', 'epsum']
     lhs:  'foo'
     code: {:in, [line: 348], ['foo', ['lorem', 'epsum']]}


```

**Comment by sandeshsoni** [comment]
@lexmag @fishcakez @ybur-yug
Could you have a look at the diff here https://github.com/elixir-lang/elixir/compare/master...sandeshsoni:4161
Suggest changes required. Add your comments.

If no changes required, then I can squash the commits and submit a pull request.

**Comment by lpil** [comment]
@sandeshsoni This seems to have been forgotten. Perhaps make a PR?

**Comment by sandeshsoni** [comment]
@lpil 
I will rebase and give a PR on this weekend.

**Comment by DiogoNeves** [comment]
Is this still being worked on? I'm new to this community but would love to start contributing 😄

**Comment by sandeshsoni** [comment]
@DiogoNeves Do you want to pitch in? here is the code. https://github.com/elixir-lang/elixir/compare/master...sandeshsoni:4161

**Comment by DiogoNeves** [comment]
@sandeshsoni maybe make a pull request to make it easier to comment directly in your code 😄 

Isn't the goal to just print the exact the same assertion message in and out of other processes?
I assumed this was about catching process exits when they're due to an assertion and use the existing formatter.

Your code seems to do a bit more than that, but I'm not entirely sure I understood the problem.

**Comment by sandeshsoni** [comment]
Do you want to add any comment here? https://github.com/elixir-lang/elixir/compare/master...sandeshsoni:4161

**Comment by DiogoNeves** [comment]
@sandeshsoni I can't comment on the link you shared (am I missing something?)

I was looking into the code and I think this issue is about fixing the assertions case when raised inside a process.
I added this little test to ExUnit assertions_test.exs

```Elixir
  test "assert match with pinned variable, in a process" do
    a = 1
    {2, 1} = (assert {2, ^a} = Value.tuple)

    try do
      Task.async(fn() -> assert {^a, 1} = Value.tuple end) |> Task.await()
    rescue
      error in [ExUnit.AssertionError] ->
        "match (=) failed\n" <>
        "The following variables were pinned:\n" <>
        "  a = 1" = error.message
        "{^a, 1} = Value.tuple()" = Macro.to_string(error.expr)
    end
  end
```

This currently fails but if I understood the problem, it shouldn't fail. Maybe after fixing it a little improvement would be to output the process where it happened.

What do you think?

**Comment by DiogoNeves** [comment]
Ok, my suggestion would be to look into simply adding a function that matches the case when we're exiting from a process with an assertion.

```Elixir
defp format_kind_reason({:EXIT, _pid} = kind, {%ExUnit.AssertionError{} = reason, _}, width, formatter) do
  format_kind_reason(:error, reason, width, formatter)
end
```

This ignores all the other process related information. A little improvement could be to change the message to include ```" in process with pid: #{pid}"```

What do you think?

**Comment by josevalim** [comment]
We should not change the formatter. I believe the best way to proceed here is to implement `def message` for `ExUnit.AssertionError` and make it include some of the logic we see in the formatters themselves.

**Comment by josevalim** [comment]
In master, thanks everyone!
