### ISSUE TITLE
request for mix support URLs as Dependencies

### ISSUE THREAD

**Issue by c0b** [elixir-lang/elixir#4164]
I don't see mix currently support any random URLs as Dependencies [1], as nodejs npm [2] does have;
it will be quite useful in corporate environment, can't rely on github, or the company might have private github setup, or gitlab, or private cgit, or just plain source code tarball on an internal http file server,

[1] http://elixir-lang.org/docs/v1.2/mix/Mix.Tasks.Deps.html
[2] https://docs.npmjs.com/files/package.json#urls-as-dependencies
[3] https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
[4] https://about.gitlab.com/
[5] http://git.zx2c4.com/cgit/

BTW, instead of these two kinds of syntax, can we support omit the repo type? like npm support Git URLs as Dependencies [3]

```elixir
{:foobar, git: "https://github.com/elixir-lang/foobar.git", tag: "0.1"}
{:foobar, path: "path/to/foobar"}
```

like `{:foobar, "path/to/foobar"}` let it automatically detect as local path,
or `{:foobar, "git+...github.com/path/to/foobar"}` be recognized as git repo

**Comment by josevalim** [comment]
There is no plan to support URLs as dependencies because you can't lock nor version URLs without changing the URL. Using URLs would not work with locks, which is one of the main features provided by Mix. Also, please remember to send feature requests to the elixir-lang-core mailing list. :) Thank you!

**Comment by c0b** [comment]
then how is `path` supported? it's same no version lock, can we reuse the same support code here?; while I'm looking at `mix help archive.install`, it seems already there? how to write an ez archive in deps in mix.exs? I would like to request some documentation as examples,

```console
mix archive.install http://example.com/foo.ez
```

```console
mix archive.install http://file-server-in-corporate.com/foo-1.2.3.ez
```

**Comment by josevalim** [comment]
`path` is supported for two reasons:

1. you may keep the path dependency inside the main repository itself. For example, you can get something like quickcheck mini and put inside vendor and depend on it with a path dependency

2. when the path is outside of the main repository, it is very likely something local which you are not pushing to remote

Also, if you have already dependencies as archives, it is worth pointing out it would be straight-forward to write a task that downloads those archives in vendor and use them as path dependencies.
