### ISSUE TITLE
ExUnit assert matching can produce invalid unused var warning

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#4166]
e.g.

```elixir
assert {var, var} = {1,1}
```
Will warn `var` is unused but it is being used to match.

**Comment by lexmag** [comment]
Closed in e1904749557f6cf62f6638d3901930d69a2896c4.

**Comment by fishcakez** [comment]
Great :heart:, can you backport to 1.2 please?

**Comment by lexmag** [comment]
Sure.
