### ISSUE TITLE
Suggesting the correct patterns to match

### ISSUE THREAD

**Issue by aesmail** [elixir-lang/elixir#4171]
Hello,
This is something that would have saved me personally a lot of time.
For function headers, wouldn't it be extremely useful if the compiler/parser suggested the intended pattern that the code was trying to match when raising a `FunctionClauseError`?

For example, I wrote the following function:
`def render("template.json", %{group: group})`

I believed (wrongly) that the second argument was going to be %{group: some_group_variable}.
Especially that I did have other related functions that worked fine with this pattern.
I kept getting a FunctionClauseError and I didn't know why (my fault eventually, of course).

Second scenario, I misspelled an argument in a pattern. The function was (phoenix):
`def video_path(conn, :update, ...)`

And I called:
`video_path(conn, :udpate, ...)`

I went crazy here. I saw the typo in its correct form until I caught it after a few hours after I had some "away" time.

I think it would be very valuable to do something like:

```
** (FunctionClauseError) no function clause matching in Rumbl.Router.Helpers.video_path/4
** Provided pattern: video_path(conn, :udpate)
** Valid patterns:
        video_path(&1, :index)
        video_path(&1, :update)
        video_path(&1, :delete)
```

Or something similar to this.

**Comment by lucca65** [comment]
+1 that would help us a lot, those kind of mistakes are very common

**Comment by gusaiani** [comment]
Nice idea.

**Comment by edgurgel** [comment]
And what if the `@spec` was also exposed if available as a hint?

**Comment by paulcsmith** [comment]
This would be wonderful! Especially when you can't easily see the function heads because the error is in another dependency.

**Comment by pablobcb** [comment]
Elm does it in a very nice way

**Comment by sivsushruth** [comment]
I have had a look at this and here are my findings:
**elixir_def.erl**  has 
```
store_each(Check, Kind, File, Location, Module, Defaults, {function, Line, Name, Arity, Clauses})
```
ets lookup can be used to later check for all functions, however, in case of a **FunctionClauseError** the entire functions table is not populated. I was thinking, a parser to store all function declarations might help us here. 
Let me know if I am headed the right direction.

**Comment by omidbachari** [comment]
If this is still available and ready for implementation, I can give it a shot!

**Comment by josevalim** [comment]
Closing in favor of #6127.
