### ISSUE TITLE
Paginated output of `h` in IEx

### ISSUE THREAD

**Issue by asymmetric** [elixir-lang/elixir#4172]
Hi,

Every time I want to read a module's documentation and type `h Module` in `iex`, I have to scroll up several times to read the docs from the start.

Wouldn't it be nice if the output could be paginated, à la `less`? Or is this issue only affecting me for some reason?

**Comment by josevalim** [comment]
Please use the mailing list for questions. Yes, the current terminal does not support paging.

**Comment by expilo** [comment]
I think this issue should be reopened. @asymmetric's post was indeed technically  a question but he obviously meant to say it's a flaw not to have paginated output in `iex`.

**Comment by josevalim** [comment]
A pull request that explores this feature is welcome. It is not currently in our backlog.

**Comment by benjamin-thomas** [comment]
Having a look at Elixir this week and looking at having a pager to be able to search for keywords easily while exploring documentation.

I found this package useful to work around this limitation: https://github.com/silbermm/exdoc_cli

```
exdoc String | less -RS
exdoc String.trim | less -RS
```
Another thing I found slightly irritating is not being able to clear the screen with `Ctrl+L`

I also found a great workaround here: https://elixirforum.com/t/how-to-fix-iex-ctrl-d-exit-and-ctrl-l-clear-with-autokey/26075
