### ISSUE TITLE
Minor 1.2 regression: assignment in the args of an assert_receive inside a macro no longer works

### ISSUE THREAD

**Issue by SimonWoolf** [elixir-lang/elixir#4174]
Wasn't sure if I should report this as it's a bit obscure, easy to work around, and might have been a deliberate change; apologies if this is noise.

Variable assignment in the arguments of an `assert_receive` when inside a macro no longer works:

```elixir
defmacro assert_response(first) do
  quote do
    assert_receive({unquote(first), second}, @timeout)
    # Snip code that asserts things about 'second' that can't be checked with pattern-matching only
  end
end
```

Above (simplified) code worked in elixir 1.1; in 1.2 it produces
`** (CompileError) path_to_test_file:30: undefined function second/0`.

Possibly related to https://github.com/elixir-lang/elixir/commit/c855561e

**Comment by lexmag** [comment]
```elixir
defmodule AssertMacro do
  def call(_any), do: {:ok, 1}
end

ExUnit.start

defmodule AssertMacroTest do
  use ExUnit.Case

  defmacrop assert_call(arg) do
    quote do
      assert {:ok, qwe} = AssertMacro.call(unquote(arg))
      assert qwe == 1
    end
  end

  defp new(), do: %{}

  test "the truth" do
    data = new()
    assert_call data
  end
end
```

**Comment by lexmag** [comment]
@SimonWoolf it looks very mush like a regression.

**Comment by SimonWoolf** [comment]
Awesome, thank you @lexmag :)
