### ISSUE TITLE
Add a warning or error when you implement a protocol inside of a test

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/elixir#4175]
Originally [posted on the mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-lang-core/8sdIXv-50oc/1SWejKcIEAAJ): I wonder if a warning or error should be raised if you implement a protocol inside a test with protocol consolidation on. It took awhile to figure out why my test stopped passing and it was because protocols are consolidated by default in 1.2. Here's an example:

In Elixir 1.1 this works just fine:

```elixir
defmodule MyTest do
  use ExUnit.Case

  defmodule User do
    defstruct first_name: "foo"
  end
  
  defimpl MyProtocol, for: User do
    def do_something(user), do: :bar
  end

  test "something" do
    assert MyProtocol.do_something(%User{first_name: "person"}) == :bar
  end
end
```

But in 1.2 it raises: `** (Protocol.UndefinedError) protocol MyProtocol not implemented for %MyTest.User{email: "person"}`. If it's possible, I wonder if it could issue a warning or even raise? Maybe something like:

```
MyProtocol will not be available because it is being defined in a test and protocol 
consolidation is on. Move the protocol elsewhere or disable protocols in your project config:

    consolidate_protocols: Mix.env != :test 
```

I don't know what this would entail so maybe it's hard to implement. If not, I think it would help when people are upgrading to 1.2. Thoughts?

**Comment by dokie** [comment]
:+1:

**Comment by ericmj** [comment]
This could be generalized to any protocol implementation defined when consolidated protocols are loaded.

**Comment by josevalim** [comment]
@lexmag I wanted to release 1.2.1 but @fishcakez proposed to include this. What do you think?

**Comment by lexmag** [comment]
I agree with @fishcakez on adding this into release.
