### ISSUE TITLE
Outputting elixir version in the CLI is slow

### ISSUE THREAD

**Issue by kofronpi** [elixir-lang/elixir#4176]
On average outputting elixir version in my bash is 10-15 times longer than erlang or other languages.

```
pak@***  λ  ~ (master) $ time erl -version
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 7.2

real	0m0.011s
user	0m0.004s
sys	0m0.006s

pak@***  λ  ~ (master) $ time elixir -v
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Elixir 1.2.0

real	0m0.169s
user	0m0.149s
sys	0m0.044s
```

I built elixir 1.2.0 from source on Ubuntu 14.04.

I realized that because I can see the slowness if I display elixir's version in my bash prompt.

**Comment by josevalim** [comment]
We could make it faster by handling it in the bash script but is there any reason why we should care?

**Comment by gregpardo** [comment]
Mine
```
elixir --version  0.10s user 0.05s system 118% cpu 0.133 total
```

Honestly anything under 0.2 seconds is pretty decent. I've seen programs take over a second.

**Comment by kofronpi** [comment]
I don't know if we should care. I use a lot of different languages and like to have the currently used versions displayed in my bash prompt (especially with things like RVM, NVM etc.). I notice the latency when I'm in elixir folders, so I was wondering why it was slower compared to Erlang. Thank you for your answers !

**Comment by gregpardo** [comment]
Looks like in the bin/elixir there is

```
-v|--compile|--no-halt)
```

I'm guessing the compile is what is taking long. If the binary is always distributed with the source something could be done just like the Makefile does

```
VERSION := $(strip $(shell cat VERSION))
```

Not sure if it's worth it or not. Jose would probably know of any complications that could arise.

**Comment by josevalim** [comment]
@kofronpi that's a good point. We shall make it fast then. :)

**Comment by fishcakez** [comment]
If you are using a elixir version manager then it might be faster for you to get the version from it instead of elixir. For example I use erln8 and `extract --show` is much faster.

**Comment by gregpardo** [comment]
I would also like to note that if it bothers him it probably bothers others even if they don't notice it. Sometimes the little things like the version printing blazingly fast can enhance the overall experience for new elixir developers.

**Comment by lexmag** [comment]
I agree with @fishcakez. I think elixir version manager (package manager) is a better place for fastest retrieval of the version, especially if you are only interested in version and not system information.

**Comment by josevalim** [comment]
Given that we are including the erlang information now, i don't think we can actually make it faster. :S So closing this one for now.

**Comment by kofronpi** [comment]
Okay I'll have a look into elixir version manager. Thanks !

**Comment by dm1try** [comment]
@kofronpi btw I use `kiex` and it stores elixir version in `ELIXIR_VERSION` environment variable as `rvm` stores ruby version in same way. So I created [straightforward  `oh-my-zsh` theme](https://gist.github.com/dm1try/c061f5ff7a6ff4d78cae) that displays elixir/ruby version dependent on current dir. It works pretty fast :)
![shell](https://cloud.githubusercontent.com/assets/486807/12214309/252be81a-b6a0-11e5-91a8-62c5afc6f1c2.png)
