### ISSUE TITLE
Supervisor.stop and friends are not resilient to crashes

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4185]
One of the reason for introducing Supervisor.stop and friends was so they could be used on `on_exit` hooks in tests. However, `Supervisor.stop` (and friends) has a series of flaws that makes this non-practical:

1. If the supervisor is named and you call Supervisor.stop with a name and the name is down, you get no process

2. If the supervisor is already shutting down by the time it gets the stop message, it will exit with the reason as the one being shut down

We will likely keep `stop` as is but this should be kept as a warning that those functions are not useful on on_exit handlers. /cc @fishcakez

**Comment by fishcakez** [comment]
I am not convinced these are flaws because that's how calls work in OTP and its I'm not sure we can do anything to improve that. I think it is just a case of improving documentation if stop is being misused.

**Comment by josevalim** [comment]
Ok, perfect.
