### ISSUE TITLE
Support optional parameters in defdelegate

### ISSUE THREAD

**Issue by stavro** [elixir-lang/elixir#4196]
For consistency with function declarations, it would be nice to consider supporting optional parameters in `defdelegate`.

Example:

```elixir
defmodule Foo do
  def foo(options \\ []) do
    IO.puts "Foo!"
  end
end
```

What is currently required:

```elixir
defmodule Bar do
  defdelegate foo(), to: Foo
  defdelegate foo(options), to: Foo
end
```

What should be allowed:

```elixir
defmodule Bar do
  defdelegate foo(options \\ []), to: Foo
end
```

**Comment by josevalim** [comment]
:+1: we did some changes to make this possible from now on.

**Comment by tuvistavie** [comment]
I would like to give this one a try!

**Comment by josevalim** [comment]
Please go ahead!

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
