### ISSUE TITLE
Pipe here operator?

### ISSUE THREAD

**Issue by dwahyudi** [elixir-lang/elixir#4198]
How about adding an opt in "pipe here" operator ??

For example ~| means pipe here:

```
# pipe foo to 1st argument, but explicitly
foo
  |> bar(~|, baz)

# pipe lorem to 2nd argument
lorem
  |> ipsum(dolor, ~|, sir)
```

this is just a simple example, is it possible?

**Comment by josevalim** [comment]
Please use the elixir-lang-core mailing list for new features discussion. Thank you.
