### ISSUE TITLE
Deprecate defdelegate with lists and append_first

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4199]
I believe those features do not map well to Elixir semantics anymore. You want each defdelegate to be on its own line so you can control module attributes like `@doc` and append_first can be confusing when using defaults (which are more useful than append_first).

/cc @tuvistavie @lexmag

**Comment by lexmag** [comment]
Strongly :+1: for defdelegate with lists deprecation, not sure about though.

**Comment by tuvistavie** [comment]
I totally agree for `defdelegate` with lists.
I think `append_first` is useful, but I agree it adds too much complexity compared to the benefits, especially when used with optional parameters.

**Comment by josevalim** [comment]
@tuvistavie can you please tackle this as well once your PR lands? :)

**Comment by tuvistavie** [comment]
Sure!
