### ISSUE TITLE
request mix to support a package without any particular version requirements

### ISSUE THREAD

**Issue by c0b** [elixir-lang/elixir#4202]
this may be requesting documentation only, or may need code changes

from current doc I don't know how to install just latest version of a package, I am expecting `{:httpotion}` `{:httpotion, "*"}` or `{:httpotion, ~r/.*/}` no one works; for this particular package httpotion we know current version is 2.1.0 we can ">= 2.1.0" but I prefer a general applicable solution

http://elixir-lang.org/docs/v1.2/mix/Mix.Tasks.Deps.html

```elixir
  defp deps do
    [{:httpotion, "*"}]
  end
```

the error msg is:
```console
$ mix deps.get
** (Mix) Dependency specified in the wrong format:

    {:httpotion}

Expected:

    {app, opts} | {app, requirement} | {app, requirement, opts}

Where:

    app :: atom
    requirement :: String.t | Regex.t
    opts :: Keyword.t
```

from python pip requirements.txt, if we don't specific a particular version, means current latest
```python
packageA>=2.1.0,<2.2.0
packageB
```

**Comment by tuvistavie** [comment]
@c0b If you always want the latest version, which I do not recommend, just use

```elixir
  defp deps do
    [{:httpotion, ">= 0.0.0"}]
  end
```

For questions, please ask on IRC or StackOverflow, you will get your answer in no time!

**Comment by josevalim** [comment]
I will improve the error message. :)

**Comment by c0b** [comment]
instead, if I can make code changes in mix to support this way to get the latest, is it acceptable to change?

```elixir
  defp deps do
    [{:httpotion}]
  end
```

I checked other communities like node npm install also assume `npm install packagename` will get the latest version, why not here just follow these conventions ?
https://docs.npmjs.com/cli/install

> If you always want the latest version, which I do not recommend, just use
there are many reasons we just want the latest version, mostly for testing software like below example in my test-requirements.txt in a python project; I won't care which particular version, and I don't think it will break compatibility in its whole life cycle; same is above httpotion hex package, I just use it as http client, and I don't think the its API call can change in its whole life cycle; and if we want to make sure deployment consistency, that's what `mix.lock` used for

```python requirements.txt
coverage
unittest-xml-reporting
```

**Comment by ericmj** [comment]
For the cases where you don't care about which version you use `{:httpotion, ">= 0.0.0"}` is a concise and explicit way of showing it.
