### ISSUE TITLE
Regex.split including captures in the result

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/elixir#4203]
Hopefully I was not unfriendly or trolly on the ML as I got no result.
However I really find that this might be useful so I take another shot here:

```elixir
         Regex.split ~r/([ln])/, "Erlang"                       
         ["Er", "a", "g"]
```

I would prefer the Erlang behavior

```elixir
        iex(7)> :re.split("Erlang","([ln])")             
        ["Er", "l", "a", "n", "g"]
```
I am aware that for backward comp one cannot just change that, what about an option like e.g.
`include_captures: true` or `:include_captures`
I noticed that under the hood `Regexp.split` does not use `:re.split` and I would love to know more about that for my education.

**Comment by josevalim** [comment]
I actually dislike this behaviour because captures in regular expressions are used as captures and grouping. So I think being explicit here would be really worth it. So :+1: for an option.

**Comment by druzn3k** [comment]
I'll try, if nobody is working on this issue!

**Comment by josevalim** [comment]
Please go ahead!

**Comment by druzn3k** [comment]
I'm already writing :+1: I cannot guarantee on the result of course, but I'll do my best. :smile:

**Comment by druzn3k** [comment]
@josevalim would you be so kind of reviewing my PR #4207? I need some advices on how to improve it. Thanks! :shipit:
