### ISSUE TITLE
Leftover references to Kernel.Typespec

### ISSUE THREAD

**Issue by bsedat** [elixir-lang/elixir#4206]
Noticed that #4079 moved the typespec docs but there are still references to it on http://elixir-lang.org/docs/v1.2/elixir/Module.html and http://elixir-lang.org/docs/v1.2/elixir/Kernel.html. Those used to be links in previous Elixir doc versions but I think they're disabled now that the Kernel.Typespec moduledocs are turned off. Should they reference the module or the new doc location?

**Comment by josevalim** [comment]
Let's reference the new doc location. Good catch :)

**Comment by bsedat** [comment]
:heart: :purple_heart: :green_heart: :yellow_heart: :blue_heart: Thanks!
