### ISSUE TITLE
~S"" should insert newlines even if the line ends with \

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#4209]
Normal strings correctly does not insert a newline when a line ends with `\`:

```elixir
iex(1)> "abc\
...(1)> def"
"abcdef"
iex(2)> "abc
...(2)> def"
"abc\ndef"
```

`~S""` where escaping is disabled should always insert newlines, but it doesn't:

```elixir
iex(3)> ~S"abc\
...(3)> def"
"abcdef"
iex(4)> ~S"abc
...(4)> def"
"abc\ndef"
```

Additionally escaping the `\` will insert `\\` with no newline:

```elixir
iex(5)> ~S"abc\\
...(5)> def"
"abc\\\\\ndef"
```

/cc @josevalim

**Comment by whatyouhide** [comment]
@ericmj your last example inserts a newline though, which IMO it's the correct behaviour as the `\` is being escaped and thus the newline is picked up.

I'm not sure that inserting just a single non-escaped `\` in a `~S""` sigil should not insert a newline, as I thought `\` was a special line-continuation character in all Elixir, even outside of strings:

```elixir
iex> 1 + \
...> 2
3
```

I don't think `~S` should have the "power" to override that. Wdyt?

**Comment by ericmj** [comment]
@whatyouhide Maybe not, that's up for discussion. But as it works today there is no way to insert a single `\` with `~S`.

**Comment by oarrabi** [comment]
Hey @ericmj,

Are you saying that
```elixir
iex(3)> ~S"abc\
...(3)> def"
```

Should actually return
`"abc\\\ndef"`?
