### ISSUE TITLE
Introduce assert_down

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4211]
This is proposal to introduce `assert_down` in ExUnit simplifying a bit the common pattern of:

    ref = Process.monitor(pid)
    assert_receive {:DOWN, ^ref, _, _, _}

This will be specially useful when testing named processes as you would simply write:

    setup do
      MyApp.start_link(name: MyApp)
      on_exit -> assert_down MyApp end
    end

The only downside is that people may get used with assert_down and not learn about the underlying semantics of monitoring but I think the pros are worth it.

Thoughts? /cc @fishcakez @lexmag @alco @ericmj

**Comment by fishcakez** [comment]
I think we'd have to force pattern matching on the exit reason, like

```elixir
assert_down MyApp, :normal
```
Though we'd support patterns so someone could do:
```elixir
assert_down MyApp, _
```

Also when asserting that something is down, do we want to monitor at that moment? I think its likely the monitor reference would come earlier in the code to prevent `:noproc` race conditions. Would it then be better to pass a monitor reference? But would that make this less useful?

**Comment by josevalim** [comment]
Well, we need to clarify what is the goal of this function. If the goal is to guarantee the process is not running, :noproc is fine. In those cases we don't even need to monitor. Also, if you need to match on the reason, you can always do it by hand. I was thinking the second argument would be the timeout value.

**Comment by fishcakez** [comment]
Oh. The idea is to ensure the named process has exited. I.E. no longer registered. You only wrote the solution and not the problem :D.

**Comment by josevalim** [comment]
Yes, for both named and non-named processes.

**Comment by edgurgel** [comment]
I would love to use this as well :+1:
