### ISSUE TITLE
Add a way to ignore deprecations in dependencies

### ISSUE THREAD

**Issue by tuvistavie** [elixir-lang/elixir#4212]
Deprecation messages are a very good thing to help smooth transition to newer Elixir versions,
however, there should be a way to enable/disable at least runtime deprecations when
these are in dependencies, as there is not much we can do for it, and often
it cannot be fixed anyway for compatibility issues.

When I run my tests, I currently get something like this, which is clearly horrible.

![screenshot-1453299217](https://cloud.githubusercontent.com/assets/1436271/12451225/7b4b894c-bfcb-11e5-87fd-d4abbb900f35.png)

Being able to explicitly whitelist modules for which we want deprecations notices to be emitted could be a solution.

Any thoughts?

**Comment by alco** [comment]
Hiding warnings is not a solution because sooner or later that code may simply start working after you upgrade to a newer Elixir version. Best solution is to report bugs for the project or upgrade your dependency if it has already been fixed upstream.

**Comment by tuvistavie** [comment]
@alco I think letting this choice to the user is still a solution.
Of course, this is definitely not a good thing to do usually, but it can sometimes help, as long as we do not abuse of it.
For example, here, I am told that plug is using a deprecated function: `uniq`.
I am aware it is deprecated, as well as everyone maintaining plug, but as plug needs to be compatible with Elixir 1.0, this will not fix.
I think it could be nice to at least have a way to ignore some of the warnings, which, in cases like this are counterproductive.
Of course, If you have other ideas to avoid getting a messy logging without ignoring warnings, that would work for me too!

**Comment by josevalim** [comment]
I agree with @alco. We need to have conversation about those cases. Or Plug needs to do a new release where it is compatible only with 1.1 or we need to remove the warning from Elixir side if developers still want to write code that is compatible only with 1.0 and 1.3.

It is also worth pointing out this warning is in master. So while I think it is too early for Plug to depend only on 1.1, by the time 1.3 comes out, I don't think we will have such concerns.

**Comment by matrinox** [comment]
I know this is closed but I also don't want to open an issue with a similar topic. I'll just quickly add my two cents here. I think any warnings from dependencies should not be shown.

I upgrade to elixir 1.4 and `Float.to_string/2 is deprecated` is constantly blasted over and over. I can't use `iex` anymore, it's basically broken. I understand that it's important and warnings are basically errors but at the same time, what if I just want to develop on 1.4 and never upgrade? Then deprecations shouldn't be a concern. Also why are warnings shown in iex?

Also, I can't just stop what I do and focus on upgrading packages. Or chase down dependency owners until they fix it or fix it myself. It just makes me not want to ever upgrade and take advantage of any of the new features.

Sorry for the rant but these warnings are basically errors. I feel like if it really is a warning it should show up hopefully just once during compilation and not in iex (unless I explicitly call that command). That might be more difficult but I know the other option is to just turn that off and I understand why you don't like that.

**Comment by josevalim** [comment]
During development of Elixir v1.4 we moved most new warnings to compile time warnings. The old warnings are running as before though.

**Comment by matrinox** [comment]
Ok, good to know. Glad that's being done :)
