### ISSUE TITLE
Captures (&) bug (191 variables limit instead of 255)

### ISSUE THREAD

**Issue by vkirill** [elixir-lang/elixir#4213]
Hello! 
First time here. Yesterday I was playing in iex and found this bug:
```elixir
iex(1)> &(&191)
** (CompileError) iex:1: capture &191 cannot be defined without &1
    (elixir) src/elixir_fn.erl:112: :elixir_fn.do_capture/4
iex(1)> &(&192)
** (ArgumentError) argument error
             :erlang.list_to_atom([120, 256])
    (elixir) src/elixir_fn.erl:132: :elixir_fn.do_escape/4
    (elixir) src/elixir_fn.erl:108: :elixir_fn.do_capture/4
```
Capture syntax only supports 191 function arguments instead of maximum 255.

**Comment by josevalim** [comment]
Perfect, thank you! We should limit the number down to something like 128 anyway. Anything more than that is abusive. :P

**Comment by michalmuskala** [comment]
Erlang already limits maximum number of arguments to a function to 255, so we could probably stay with that.

**Comment by josevalim** [comment]
We do as well but the limit was being triggered earlier.

**Comment by michalmuskala** [comment]
Yes, I understand the bug. I referred to the proposal to limit arguments at 128.

**Comment by josevalim** [comment]
Right, we already limit to 255 but that doens't work.

**Comment by josevalim** [comment]
I was wrong, we don't limit to 255. The error is happening because we build variables like x0, x1, x2, x3 but for &192, the codepoint is 256 which has no translation. I think we need to build variables like this:

[?x|integer_to_list(X)] so we get proper numbers for any X >= 0.
