### ISSUE TITLE
Captured functions can't run with `&(&1).(arg)` syntax

### ISSUE THREAD

**Issue by vkirill** [elixir-lang/elixir#4214]
This might be not an issue, but why this happens when doing captures?
```elixir
iex(8)> fn x -> x end.(:x)
:x
iex(9)> &(&1).(:x)
#Function<6.54118792/1 in :erl_eval.expr/5>
```

**Comment by tuvistavie** [comment]
For further reference, just check the following output.

```
iex(1)> quote do: &(&1).(:x)
{:&, [], [{{:., [], [{:&, [], [1]}]}, [], [:x]}]}
iex(2)> quote do: (&(&1)).(:x)
{{:., [], [{:&, [], [{:&, [], [1]}]}]}, [], [:x]}
```

Which basically says that `&(&1).(:x) == &((&1).(:x))` , which creates a function that expects a function of arity 1 as argument and passes `:x` to it when called.

```
iex(1)> (&((&1).(:x))).(&(Atom.to_string(&1)))
"x"
```

**Comment by lexmag** [comment]
I'd recommend to combine quoting with `Macro.to_string/1`, e.g.:
```elixir
quote(do: &(&1).(:x)) |> Macro.to_string
#=> "&(&1.(:x))"
```
There is a bug in presenting `(&(&1)).(:x)` though, I'm working on a fix.

**Comment by michalmuskala** [comment]
I think this behaviour of `&(&1).(:x)` is wired and surprising. Is it intended?

**Comment by tuvistavie** [comment]
@lexmag Thanks for the tip, it sure is more readable.
Oh, indeed `(&(&1)).(:x)` seems to loose it brackets after quoting + Macro.to_string.

**Comment by lexmag** [comment]
@michalmuskala sadly yes. :cry:
Capture operator has very low precedence.

**Comment by josevalim** [comment]
It is intended because it is the same as: `& &1.field` which we write a lot.

**Comment by michalmuskala** [comment]
In fact I find `& &1.field` equally confusing :smirk: The first time I encountered it I had no idea what was happening.

But I can see, how it's not possible to change it.
