### ISSUE TITLE
Regex.escape/1 doesn't escape "]" and "}"

### ISSUE THREAD

**Issue by mschae** [elixir-lang/elixir#4220]
`Regex.espace/1` doesn't escape closing closing brackets.

### Expected:

```Elixir
iex> Regex.escape "[]"
"\\[\\]"

iex> Regex.escape "{}"
"\\{\\}"
```

### Actual

```Elixir
iex> Regex.escape "[]"
"\\[]"

iex> Regex.escape "{}"
"\\{}"
```

**Comment by mschae** [comment]
Unless someone else is inclined to, I would be happy to tackle this.

**Comment by josevalim** [comment]
Please go ahead!

**Comment by lexmag** [comment]
I assume that's correct behaviour what we have today, no? Is it breaks matching?

**Comment by lexmag** [comment]
E.g. C# states:

> If a closing bracket or brace is not preceded by its corresponding opening character, the regular expression engine interprets it literally.

**Comment by mschae** [comment]
Sorry maybe I am missing something.

Say I want to replace `[` and `]` in a text:

```Elixir
pattern1 = ~r([\[\]])
pattern2 = Regex.compile! "[#{Regex.escape("[]")}]"

# I would expect pattern1 and pattern2 to be equivalent, hence:

Regex.replace(pattern1, "a[b]c", "") == "abc" # => true
Regex.replace(pattern2, "a[b]c", "") == "abc" # => false
```

What am I missing?

**Comment by lexmag** [comment]
It looks like a special case with `[]` inside `[]`, as I remember `]` inside should be the first element (will look for a source).
These samples but with `{}` inside `[]` works flawlessly.

**Comment by lexmag** [comment]
Nevertheless, having this inconsistency I :+1: for more escaping.
