### ISSUE TITLE
Windows shortcut contains hardcoded werl.exe

### ISSUE THREAD

**Issue by chowetno** [elixir-lang/elixir#4221]
There's a hardcoded `werl.exe` path in the shortcut installed with Elixir using the Windows installer. The path currently is `%USERPROFILE%\Desktop\werl.exe` but it works if you change it to `C:\Program Files\erl7.1\bin\werl.exe`. I think that maybe it's best to not assume `werl.exe` exists on the Desktop?

**Comment by josevalim** [comment]
Could you please make it a pull request to the installer? We rely on contributions for maintaining the installer at: https://github.com/elixir-lang/elixir-windows-setup Thank you!

**Comment by chowetno** [comment]
Ah, thanks, moved to elixir-lang/elixir-windows-setup#3
