### ISSUE TITLE
Consider deprecating NEW LINE + OPERATOR

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4227]
Except for arrow related operators. Because pipe operators have already been special cased in the language, I wouldn't mind making another exception here for sanity reasons.

**Comment by lexmag** [comment]
Really like this idea.

**Comment by ericmj** [comment]
I am :-1: because sometimes code looks better with the operator on the newline. What are the sanity reasons you are referring to?

**Comment by josevalim** [comment]
The fact it won't work with `+` and `-`, the fact it doesn't work on IEx, as well as limitations around `,` (raised on IRC yesterday) and the fact it is often confusing in code like below:

```elixir
{:a, _}
  = 1
```

Do you remember of any cases, besides pipes, where you prefer them in new lines?

**Comment by ericmj** [comment]
Pipes also doesn't work in iex and that should be a bigger issue because that's definitely the binary operator most used on a new line.

I prefer these:

```elixir
backtrack_parents([parent], info, activated)
  || backtrack(name, info, activated)
```

```elixir
"some long string"
  <> "continues here"
```

**Comment by ericmj** [comment]
It also seems odd to start disallowing this if we are considering to allow commas on new lines.

**Comment by josevalim** [comment]
The plan is to not allow commas. Regarding the previous examples, this would be a about us imposing one preferred way of doing so. I see no reason why the examples above would be better than having the operator in the previous line?

**Comment by ericmj** [comment]
No way of doing it is better than the other, there are two ways of doing it and my preference happens to be the one we are considering to disallow.

**Comment by jisaacstone** [comment]
I am in favour of consistent behaviour across all binary operators. I'm against special casing anything. Makes the language easier to communicate, simpler to parse / debug, and reduces the number of decisions I need to make when writing code.

**Comment by josevalim** [comment]
I am closing this because I just realized I use `when` after new lines almost everywhere. However, I wouldn't like to allow the following to work:

```elixir
[foo
,bar
,baz]
```

However, if we want to be consistent, we may need to do.

**Comment by tuvistavie** [comment]
I think those kind of coding conventions are quite personal
and it is hard to say if one is superior to another.
To give a counter example to the above example, indentation such as

```
{ foo
, bar
, baz
}
```

is used all the time in Haskell and I do not think it is less readable than something else.
[Some people](https://docs.npmjs.com/misc/coding-style#comma-first) use this syntax in Node too.
I think those kind of choices are better done at the linter level, allowing some configuration,
rather than trying to enforce too much at the compiler level.
