### ISSUE TITLE
ExUnit: € sign causes Argument error

### ISSUE THREAD

**Issue by hdcos** [elixir-lang/elixir#4235]
When I use a € sign in a test desciprtion with

    test "crediting 850€ with BlueCard" do
      ...
    end

When I run my test with 

    mix test --trace test/...

I get 

    test/lemonwex_test.exs:46: warning: this expression will fail with ArgumentError
    ** (ArgumentError) argument error
        test/lemonwex_test.exs:46: (module)
        (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6

and I can't run my test case.
when I remove the € sign it runs successfully. $ sign is ok

**Comment by josevalim** [comment]
It is because we convert test names to atoms and atoms unfortunately do not support unicode yet. There is nothing we can do but I will investigate what is the status of this, thank you!
