### ISSUE TITLE
ExUnit setup_all returning {:ok, file: :foo} explodes

### ISSUE THREAD

**Issue by benwilson512** [elixir-lang/elixir#4236]
Elixir 1.2

The following test:
```elixir
defmodule ExUnitErrorTest do
  use ExUnit.Case

  setup_all do
    {:ok, file: :foo}
  end

  test "the truth" do
    assert false
  end
end
```

results in
```
14:52:47.363 [error] GenEvent handler ExUnit.CLIFormatter installed in #PID<0.89.0> terminating
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:346: IO.chardata_to_string(:foo)
    (elixir) lib/path.ex:289: Path.relative_to/2
    (ex_unit) lib/ex_unit/formatter.ex:241: ExUnit.Formatter.with_location/1
    (ex_unit) lib/ex_unit/formatter.ex:112: ExUnit.Formatter.format_test_failure/5
    (ex_unit) lib/ex_unit/cli_formatter.ex:71: ExUnit.CLIFormatter.handle_event/2
    (stdlib) gen_event.erl:538: :gen_event.server_update/4
    (stdlib) gen_event.erl:520: :gen_event.server_notify/4
    (stdlib) gen_event.erl:261: :gen_event.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:test_finished, %ExUnit.Test{case: ExUnitErrorTest, logs: "", name: :"test the truth", state: {:failed, [{:error, %ExUnit.AssertionError{expr: false, left: :ex_unit_no_meaningful_value, message: "Expected truthy, got false", right: :ex_unit_no_meaningful_value}, [{ExUnitErrorTest, :"test the truth", 1, [file: 'test/ex_unit_error_test.exs', line: 9]}]}]}, tags: %{async: false, case: ExUnitErrorTest, file: :foo, line: 8, test: :"test the truth"}, time: 3240}}
State: %{colors: [enabled: true], failures_counter: 0, invalids_counter: 0, seed: 348148, skipped_counter: 0, tests_counter: 0, trace: false, width: 282}
```

Changing the `file:` key to anything else makes the error go away. Making the test pass makes the error go away.

see https://github.com/benwilson512/ex_unit_error for a full isolated example (not that there's really any  more to it than what I pasted).

**Comment by josevalim** [comment]
`@file` is a reserved key. We should raise a decent error if you try to override one of those.

**Comment by benwilson512** [comment]
A bummer. I assume there's no hope of renaming it to `:__file__` ? `file` is a pretty common word to have reserved.

**Comment by josevalim** [comment]
Here is the issue, those tags can be used as filters. So you can say: run all tests with the file tag. That's why I don't think we should move it to __file__, because then the filter becomes awkward. Does it make sense?

More info: https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/case.ex#L117-L120

**Comment by benwilson512** [comment]
I see. That makes sense. What I don't yet see is where / why the output of the setup blocks gets merged with those tags. Do all inputs to a test end up as tags?

**Comment by josevalim** [comment]
The tags and the user data as stored in the same map. It is a decision I mostly regret today but I guess we could move tags to `context.tags` so if you override them we won't choke.

**Comment by benwilson512** [comment]
Ah that is indeed unfortunate. I'd go as far as putting it in `ex_unit_context.tags` or something just so that we can avoid collision as much as possible.

**Comment by buob** [comment]
I hate to drudge up such an old issue, but I figured this would be the appropriate place to ask in case anyone finds this like I did -- Is there a workaround for this if one has a module named `File`?

for teh googs...
```
** (RuntimeError) ExUnit callback in MyApp.FileControllerTest is trying to set reserved 
field :file to %MyApp.Files.File
    stacktrace:
       (ex_unit) lib/ex_unit/callbacks.ex:460: ExUnit.Callbacks.raise_merge_reserved!/3
       (elixir) lib/map.ex:571: Map.update/4
       (stdlib) lists.erl:1263: :lists.foldl/3
       test/my_app/controllers/file_controller_test.exs:1: MyApp.FileControllerTest.__ex_unit__/2
```

**Comment by benwilson512** [comment]
I just call it `{:ok, test_file:  file}` or similar.

**Comment by buob** [comment]
🤦‍♂️ 

I didn't realize this was generated from the phoenix generators, so yeah, renaming that in the setup private function and in the test captures fixed it.  Sorry for the spam, hopefully this helps anyone else that might have used the html or json phoenix generators to make a `File` model and make it worth the time. 😅
