### ISSUE TITLE
Hidden error in build process when upgrading packages

### ISSUE THREAD

**Issue by seantanly** [elixir-lang/elixir#4239]
In upgrading my packages on a Phoenix 1.1.4 app, specifically `phoenix_html` from 2.4.0 to 2.5.0, I encountered the following

`** (FunctionClauseError) no function clause matching in Phoenix.HTML.Form.normalize_form/1`

The steps I took is simply `mix deps.update --all` and running `mix test` thereafter.

Looking into the issue, I thought the error lies with the new phoenix_html specifically https://github.com/phoenixframework/phoenix_html/blob/master/lib/phoenix_html/form.ex#L239 which matches for the presence of both `data` and `model` attributes. However, it is not.

I chanced upon clearing all my dependencies `mix deps.clean --all` and reinstalling them `mix deps.get` and the error is gone. 

I'm able to replicate the upgrade error by reinstating the previous phoenix_html 2.4.0 and repeat the upgrade process. This time, `rm -rf _build` and running `mix test` works as well, instead of downloading all the deps files again. Upgrading via changing the `mix.lock` file for phoenix_html from `2.4.0` to `2.5.0` with `mix deps.get`, produces the same error.

There's probably some problem with the build process when upgrading packages, outdated build artefacts not being rebuilt... While this issue is not being resolved, perhaps we should force a rebuild of everything there is a change in package versions, rather than leaving this rather **insidious** error lurking around, which could very well translate to runtime errors on production machines, depending on the deployment strategies, whether the `_build` artefacts are being always_rebuilt every time.

**Comment by josevalim** [comment]
Which Elixir version are you using?

-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by seantanly** [comment]
Installation Info 
Elixir 1.2.1 & Erlang 18.2.1 installed via homebrew.

$ mix hex.info
Hex:    0.10.4
Elixir: 1.2.1
OTP:    18.2.1

Built with: Elixir 1.2.1 and OTP 18.2.2

Registry file available (last updated: 2016-01-29 08:25:23)
Size: 1359kB (compressed 441kb)
Packages #: 1446
Versions #: 6420

**Comment by josevalim** [comment]
This is great, thank you. Those errors indeed should not happen, I will investigate what is happening. Is this app public by any chance? It would be easier if I could just have a failing test ready but if not I will build one. :)

**Comment by seantanly** [comment]
Sure, here's the example app which I built from Programming Phoenix. ;)

https://github.com/seantanly/phoenix-rumbl

**Comment by josevalim** [comment]
Unfortunately I cannot reproduce the issue. Once I cloned the repository, I changed the lock file because it was using 2.5.0 already. I did the steps and nothing. :S

**Comment by josevalim** [comment]
Nevermind, I can reproduce it now. :) We should recompile phoenix_ecto but we haven't for some reason. :)

**Comment by seantanly** [comment]
Ah yes, the updated mix.lock got committed. Just fixed it on the repo reverting the phoenix_html version back to 2.4.0.

Glad that you got the error reproduced anyway. :)

**Comment by josevalim** [comment]
Excellent catch and top notch bug report, thank you! 1.2.2 should be out soon with a fix. :)
