### ISSUE TITLE
Dialyzer has output with _@ instead of variable/function names

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/elixir#4240]
When running dialyzer on Elixir 1.2.1 the output contains many instances of `_@x` where `x` is an integer. Here is an example build of the plt and some excerpts from the output:

The plt:

````
dialyzer --output_plt .dialyzer.plt --build_plt -pa _build/dev/lib/bamboo/ebin -pa _build/dev/lib/cowboy/ebin -pa _build/dev/lib/dialyxir/ebin -pa _build/dev/lib/envy/ebin -pa _build/dev/lib/earmark/ebin -pa _build/dev/lib/ecto/ebin -pa _build/dev/lib/exgravatar/ebin -pa _build/dev/lib/ex_machina/ebin -pa _build/dev/lib/oauth2/ebin -pa _build/dev/lib/pact/ebin -pa _build/dev/lib/phoenix_ecto/ebin -pa _build/dev/lib/phoenix_html/ebin -pa _build/dev/lib/phoenix/ebin -pa _build/dev/lib/postgrex/ebin -pa _build/dev/lib/timex/ebin -pa _build/dev/lib/secure_random/ebin -pa _build/dev/lib/httpoison/ebin -pa _build/dev/lib/cors_plug/ebin --apps erts kernel stdlib crypto public_key bamboo cowboy dialyxir envy earmark ecto exgravatar ex_machina oauth2 pact phoenix_ecto phoenix_html phoenix postgrex timex secure_random httpoison cors_plug -r /usr/local/Cellar/elixir/1.2.1/bin/../lib/elixir/../eex/ebin /usr/local/Cellar/elixir/1.2.1/bin/../lib/elixir/../elixir/ebin /usr/local/Cellar/elixir/1.2.1/bin/../lib/elixir/../ex_unit/ebin /usr/local/Cellar/elixir/1.2.1/bin/../lib/elixir/../iex/ebin /usr/local/Cellar/elixir/1.2.1/bin/../lib/elixir/../logger/ebin /usr/local/Cellar/elixir/1.2.1/bin/../lib/elixir/../mix/ebin
```

I included everything in case that makes it easier to debug. As you can see it's using the latest 1.2.1 build of elixir and includes many of the dependencies we use in this particular project.

Excerpt of the dialyzer output:

```
daily_digest.html.eex:1: The pattern {'safe', _@39} can never match the type 'nil' | binary()
daily_digest.html.eex:1: The pattern {'safe', _@16} can never match the type 'nil' | binary()
page_controller.ex:1: The call 'Elixir.Phoenix.Controller':put_new_layout(_@3::#{},{'Elixir.Constable.LayoutView','app'}) breaks the contract ('Elixir.Plug.Conn':t(),{atom(),binary()} | 'false') -> 'Elixir.Plug.Conn':t()
```

As you can see it uses `_@x` which makes it difficult to figure out where the problem lies. I also believe there may be some incorrect typespecs in Phoenix that are causing the PutLayout error, but I'm not sure. I can open up an issue on the Phoenix repo with more examples if that is helpful!

**Comment by josevalim** [comment]
Please open up issues in the appropriate projects, they should tag the output. If you can include a simple way to reproduce it, even better (like a small project on Github with a command to run). Feel free to ask me on IRC (or on this thread) if you are not sure if you should open an issue here, Phoenix or Phoenix.HTML. :)

The safe one seems to be on Phoenix.HTML. I will fix put_new_layout in Phoenix. :)

**Comment by paulcsmith** [comment]
@josevalim I don't believe this is just a Phoenix issue; that's why I opened it here. The warnings I pasted happen to be from Phoenix, but the `_@` stuff also comes up on other parts that aren't Phoenix specific. It may be elixir or possibly eex, but I'm not sure. That's why I opened it here because I believe you said that should have been fixed in Elixir 1.2. Maybe I misinterpreted though?

**Comment by paulcsmith** [comment]
Also I'll open a Phoenix specific issue with the Phoenix warnings that are generated. I'll also include an example app if I can to make it a bit easier to debug :)

**Comment by paulcsmith** [comment]
And maybe it would be good if you could give me a hint on where to put the issue(s). I think maybe I'm not sure where this problem is coming for since I thought it was an elixir thing :P

**Comment by josevalim** [comment]
What is happening is that, when any Elixir project generates code, usually for optimization, we may generate clauses like this:

```elixir
    case expr do
      {:safe, _} ->
      nil ->
      other ->
    end
 ```

The issue is that dialyzer can look at such code and say: well, some of those clauses will never match. So the answer for who is to blame in those _@INT warnings is usually: "who generated the code?". For the code snippets above, anything in .html.eex is Phoenix.HTML. The put_layout was a Phoenix bug but it has been fixed in master.

Does this help? :)

**Comment by paulcsmith** [comment]
@josevalim Yes that helps a lot, thank you! I think I see what you mean now and that it's not an elixir issue. One question, how do you "mark a clause as generated"? I've tried searching, but can't find where that is, or what it means :S

I'll get a repo up and open an issue with the phoenix html stuff :)
