### ISSUE TITLE
Add Process.sleep

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4242]
Based on `:timer.sleep`. We should also document common cases of how using it can be avoided.

**Comment by josevalim** [comment]
In master. :D

**Comment by JugrajSingh91** [comment]
Hey
I want to add process delay but Process.delay and even timer.delay can do it in milliseconds. I am not being able to find a way to add delays in microseconds. Can you please help?!

**Comment by NobbZ** [comment]
The beams internal clock and message delay mechanics do not allow for granularity finer than milliseconds.

**Comment by JugrajSingh91** [comment]
Thanks! I can stop looking then.
