### ISSUE TITLE
location: :keep bug seems like?

### ISSUE THREAD

**Issue by eminarcissus** [elixir-lang/elixir#4243]
lib/test.ex
```
defmodule Test do
  import Test2,only: [wrapfunc: 3,wrapfunc: 2]
  wrapfunc test do
    raise "error"
  end

  def create do
    quote location: :keep do
      def test do
        raise "error"
      end
    end
  end

  def create_with_wrap do
    quote location: :keep do
      wrapfunc test do
        raise "error"
      end
    end
  end

end

```
lib/test2.ex
```
defmodule Test2 do
  defmacro wrapfunc(head,opts \\ [],do: block) do
    {name,args} = case head do
      name when is_atom(name) ->
      {name,[]}
      h ->
      Macro.decompose_call h
    end
    quote location: :keep do
      def unquote(name)(unquote_splicing(args)) do
        unquote(block)
      end
    end
  end
end
```

Testing it with console
```
iex(1)> Module.create TestModule,Test.create,__ENV__
{:module, TestModule,
 <<70, 79, 82, 49, 0, 0, 5, 76, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 0, 127, 131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115, 95, 118, 49, 108, 0, 0, 0, 4, 104, 2, ...>>,
 {:test, 0}}
iex(2)> TestModule.test
** (RuntimeError) error
    lib/test.ex:6: TestModule.test/0
iex(2)> TestModule2.test
** (UndefinedFunctionError) undefined function TestModule2.test/0 (module TestModule2 is not available)
    TestModule2.test()
iex(2)> Module.create TestModule2,Test.create_with_wrap,__ENV__
{:module, TestModule2,
 <<70, 79, 82, 49, 0, 0, 5, 84, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 0, 127, 131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115, 95, 118, 49, 108, 0, 0, 0, 4, 104, 2, ...>>,
 {:test, 0}}
iex(3)> TestModule2.test
** (RuntimeError) error
    lib/test2.ex:14: TestModule2.test/0
```
in TestModule2.test we should expect it raised error from lib/test.ex: 14 but not lib/test2.ex

Some more interesting founds:
1: if I removed test2.ex location: :keep, directly call Test.test will return the correct line number test.ex : 8
but TestModule.test and TestModule2.test both have no line number at all(don't know if has anything to do with Module.create's env)
2: if I put it back location: :keep it will always have the correct line number but always pointing to the incorrect file name(do block is defined in test.ex but it always pointing to test2.ex)

**Comment by eminarcissus** [comment]
With location: :keep in test2.ex
```
iex(1)> Test.test
** (RuntimeError) error
    (igourmet) lib/test2.ex:8: Test.test/0
```

Without
```
iex(1)> Test.test
** (RuntimeError) error
    (igourmet) lib/test.ex:8: Test.test/0
```

**Comment by josevalim** [comment]
which Elixir version?

**Comment by eminarcissus** [comment]
```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.2.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>

```
latest version I think

**Comment by josevalim** [comment]
Thank you! I will investigate this later.

**Comment by eminarcissus** [comment]
Appreciate , thx :)
2016年1月30日(土) 18:22 José Valim <notifications@github.com>:

**Comment by lexmag** [comment]
There is a limited case which shows this problem:
```elixir
# lib/test.ex
defmodule Test do
  require Test2

  Test2.wrapfunc :my_fun do
    # line 5
    # line 6
    # line 7
    # line 8
    # line 9
    raise "error"
  end
end

# lib/test2.ex
defmodule Test2 do
  defmacro wrapfunc(name, do: block) do
    quote location: :keep do
      def unquote(name)() do
        unquote(block)
      end
    end
  end
end
```

```elixir
iex(1)> Test.my_fun
** (RuntimeError) error
    (misversion) lib/test2.ex:10: Test.my_fun/0
```
In the stacktrace we're taking __line__ from original place but __file__ from the quote.
That's not happening when we providing quoted expression instead of bare atom `:my_fun` (e.g. `Test2.wrapfunc my_fun() do`), and same with `Macro.decompose_call/1` we effectively losing file information from the definition.

**Comment by lexmag** [comment]
For a case when we use bare atom `:my_fun` as function name, the function gets metadata from quote location and not from the place where this atom was defined.
The following commit should fix that situation: https://github.com/lexmag/elixir/commit/b9e084dd6bf76dbc7918891b4634d27eefab4316.
Although this special case doesn't feel quite right. @josevalim what are your thoughts about it?

Generated AST link: https://gist.github.com/lexmag/199e70637399122b2d8c, what we have before doing expand.
