### ISSUE TITLE
iex : consider adding a shortcut to cancel current line ? 

### ISSUE THREAD

**Issue by geoffroymontel** [elixir-lang/elixir#4248]
Newbie here.

If you mistype something in iex interpreter, you have to type `#iex:break` to cancel the line interpretation.
It's not very convenient. Could you add an option to ctrl+c options ?

```elixir
iex(1)> fn
...(1)> 
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
```

**Comment by josevalim** [comment]
Unfortunately we cannot add this feature easily as we rely on the erlang toolchain for now. So I will close this as won't fix until we have our own. Thank you!

**Comment by geoffroymontel** [comment]
OK ! Thanks for your answer
