### ISSUE TITLE
warning options for deprecated elixir modules?

### ISSUE THREAD

**Issue by linearregression** [elixir-lang/elixir#4249]
it does not look like there is an options to turn on warnings of deprecated Elixir modules.
There is for the underlying erlang code but not for elxir code.

E.g. will help for migration of Dict/HashDict to Map etc.

http://elixir-lang.org/docs/stable/elixir/Dict.html

**Comment by josevalim** [comment]
Right now those are "soft" deprecated on purpose. We won't want them to emit warnings just yet. :)
