### ISSUE TITLE
Question: missing debug_info in string metadata modules

### ISSUE THREAD

**Issue by skirino** [elixir-lang/elixir#4250]
Using newly-released v1.2.2, dialyzer starts to complain:
```
$ mix dialyze
Finding applications for analysis
Finding suitable PLTs
Looking up modules in dialyze_erlang-18.2.1_elixir-1.2.2_deps-dev.plt
Looking up modules in dialyze_erlang-18.2.1_elixir-1.2.2.plt
Finding applications for dialyze_erlang-18.2.1_elixir-1.2.2.plt
Finding modules for dialyze_erlang-18.2.1_elixir-1.2.2.plt
Checking 156 modules in dialyze_erlang-18.2.1_elixir-1.2.2.plt
Adding 201 modules to dialyze_erlang-18.2.1_elixir-1.2.2.plt
** (Mix) Dialyzer error: Could not get abstract code for file: /home/skirino/code/Erlang/elixir-repo-1.2.2/lib/elixir/ebin/Elixir.String.Normalizer.beam (please recompile it with +debug_info)
```

The reason of the error is obvious: `String.Graphemes`, `String.Unicode` and `String.Normalizer` do not have `debug_info` ( https://github.com/elixir-lang/elixir/commit/e65b01b870b8b75882a ).
Removing `@compile {:debug_info, false}` from these modules and recompiling elixir resolve my issue (for the moment).

I'm wondering what the purpose of disabling debug_info in these modules is.
Removing debug_info can reduce size of beam files but in my environment the saving is insignificant compared with the total size of elixir application's beam files, 3.7MB:

```
compiled without debug_info:
 83K Elixir.String.Graphemes.beam
135K Elixir.String.Normalizer.beam
141K Elixir.String.Unicode.beam

compiled with debug_info:
152K Elixir.String.Graphemes.beam
170K Elixir.String.Normalizer.beam
173K Elixir.String.Unicode.beam
```

Probably I'm missing something but any thoughts would be appreciated.
Thanks!

**Comment by josevalim** [comment]
Fixed in master and v1.2 (which will have a new release soon-ish).
