### ISSUE TITLE
Macro.create created module have incorrect context in macro injected method

### ISSUE THREAD

**Issue by eminarcissus** [elixir-lang/elixir#4254]
I've posted a question yesterday on StackOverflow to make sure if this is a bug or something I missed when testing the macro and dynamically created module, and find this might be potentially a bug here.
The code are as following

```
defmodule A do
  defmacro wrap(head,opts \\[],do: block) do
    {name,args} = case head do
      name when is_atom(name) ->
      {name,[]}
      h ->
      Macro.decompose_call h
    end
    quote do
      def unquote(name)(unquote_splicing(args)) do
        IO.inspect __ENV__
        unquote(block)
      end
    end
  end
end

defmodule B do
  import A,only: [wrap: 2]
  alias B.C
  wrap test do
    C.test2
  end
end

defmodule C do
  def test do
    quote do
      import A,only: [wrap: 2]
      alias B.C
      wrap test do
        IO.inspect __ENV__
        C.test2
      end
    end
  end
end

defmodule B.C do
  def test2 do
    "good"
  end
end
Module.create D,C.test,__ENV__

```

Calling B.test 
result : "good"

Calling D.test
(UndefinedFunctionError) undefined function C.test2/0

Where dynamically generated module D and predefined B should be practically identical. But calling D.test will eventually raise out C cannot be found, which means in this module it didn't resolve out the alias created in the context which C -> B.C.

But after printing out the __ENV__, both D.test and B.test have a the same alias setting(which means both should recognize C as B.C).

also couple a few days ago I found a similar problem which I'm trying to inject a var! into context,but likewise, only predefined module works but dynamically created are not, when checking out var binding, I found in dynamic module,all variables are in ModuleName context(or a random number context), [google_talk](https://groups.google.com/forum/#!topic/elixir-lang-talk/xNlyqWMlT-c).

So don't know if this is a bug or something I missed in creating the module dynamically. Hope can take a look at this. thx :)

**Comment by josevalim** [comment]
Thank you for the report, it has been fixed in master!
