### ISSUE TITLE
Ensure get_in foo[bar][baz] and get_in(foo, [bar, baz]) behave the same

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4258]
They may behave differently in the presence of anonymous functions. This means we need to make it consistent with `foo[bar][baz]` itself.

**Comment by tuvistavie** [comment]
I would be glad to give this one a try, could you give a little more details please?
I understand `get_in` can be passed a function while the access syntax expects
the key to be an atom, is this what you are referring to here?

**Comment by josevalim** [comment]
@tuvistavie Since `foo[bar]` compiles to `Access.get(foo, bar)`, I believe it is a matter of removing these clauses:

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L1695-L1698

And moving them inside `Access.fetch`. Then do the same for `get_and_update_in`: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L1695-L1698

And then, of course, improving Access docs and writing some unit tests. :D

**Comment by tuvistavie** [comment]
@josevalim Thank you for the precisions.

So if I understand you correctly, this mean that we would be able to write
something like

```elixir
users = [%{name: "john", age: 27}, %{name: "meg", age: 23}]
all = fn :get, data, next -> Enum.map(data, next) end
users[all][:age]

# -> [27, 23]
```

right?

**Comment by josevalim** [comment]
Precisely!

**Comment by tuvistavie** [comment]
Thank you, I will give it a shot!

**Comment by tuvistavie** [comment]
Hi @josevalim,

I started to work on this, but either I am missing something,
either it is not as obvious as moving a function around.

For a case such as

```elixir
map = %{"fruits" => ["banana", "apple", "orange"]}
assert get_in map, ["fruits", by_index(0)]  == "banana"
```

it is obvious than moving the call to `Access.fetch` is enough,
but for something such as

```elixir
users = [%{name: "john", age: 27}, %{name: "meg", age: 23}]
all = fn :get, data, next -> Enum.map(data, next) end
get_in users, [all, :age]
```

when using `get_in` we know if we will need to recurse or not,
and can therefore create the `next` function accordingly.
However, when trying to do this with the access syntax:

```elixir
users = [%{name: "john", age: 27}, %{name: "meg", age: 23}]
all = fn :get, data, next -> Enum.map(data, next) end
users[all][:age]
```

AFAIK we have no idea when calling `Access.fetch(users, all)` if we will have another call
to `Access.fetch` later or not, so I am not sure how to create the `next` function.

Am I missing something here?

Thank you.

**Comment by josevalim** [comment]
@tuvistavie you are right, thanks for checking this. I will review it later on. :)

**Comment by tuvistavie** [comment]
@josevalim Thank you for your confirmation. Please let me know if there is something I can help with!

**Comment by josevalim** [comment]
The only way for us to fix this is to make `foo[bar][baz]` compile to `get_in foo, [bar, baz]`. I am not sure though if this is what we want so I am closing this. /cc @lexmag

@tuvistavie thanks for investigating and sorry for the "false alarm"!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
