### ISSUE TITLE
 2500 / 3 |> Float.round(2) |> Float.to_string equals "8.33330000000000040927e+02"

### ISSUE THREAD

**Issue by hdcos** [elixir-lang/elixir#4262]
The bug I had came from this line.
    2500 / 3 |> Float.round(2) |> Float.to_string
I was expecting the result to be "833.33"
but iex tells me:
    "8.33330000000000040927e+02"

Is this normal? Have I done something wrong?

2500 / 3 |> Float.to_string(decimals: 2) works as expected.

**Comment by josevalim** [comment]
Please use the mailing list for questions, specially if you are not sure if something is a bug. This particular topic has been discussed there a couple times. :)
