### ISSUE TITLE
UTF-8 string in iex hangs console (Windows 10 x64 - Erlang 18 - Elixir 1.2.1)

### ISSUE THREAD

**Issue by resilva87** [elixir-lang/elixir#4266]
I'm trying to run the example from the page http://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html. After typing `iex> string = "hełło"` (previously setting my console to handle UTF-8 strings) it hangs.

    C:\Users\Renato\Workspace
    λ chcp 65001
    Página de código ativa: 65001

    C:\Users\Renato\Workspace
    λ iex
    Eshell V7.2.1  (abort with ^G)
    Interactive Elixir (1.2.1) - press Ctrl+C to exit (type h() ENTER for help)
    iex(1)> string = "hełło"
    // Nothing shows here

I'm using cmder (https://github.com/cmderdev/cmder) but this issue happens with Windows default console too.

Thanks!

**Comment by josevalim** [comment]
Thank you @resilva87! If you can investigate it further and gives us feedback, we would really appreciate it. The `chcp 65001` was enough in my Windows machine so I wonder why it doesn't work for you.

**Comment by josevalim** [comment]
I just tried again on Windows and I cannot reproduce. If you can provide a more precise way to reproduce the issue, please let me know. I'm also paging @OnorioCatenacci to check if he can reproduce or has a clue about what is happening.

**Comment by OnorioCatenacci** [comment]
I can take a look Jose but I doubt I can reproduce it if you can't.

**Comment by OnorioCatenacci** [comment]
Hi Jose and @resilva87,

I just tried this on Windows 10 (10.0.10586) and I do get a hang.  This is exactly what I did:

1.) Win+R then type "cmd" (without the double quotes, of course)

2.) chcp 65001

3.) iex.bat 

4.) string = "hełło" (I have to paste the string in since I'm not sure of how to get those two non-Latin chars from the keyboard). 

5.) No response from iex.bat but I can Ctrl+C to stop it.

**Comment by OnorioCatenacci** [comment]
For whatever it's worth, UTF-8 support on Windows Console seems to be spotty at best.  I can dig into this to see if I can figure out what's going on but there are lots of reports of issues using UTF-8 on Windows Console and they're reported from several different programming languages.

By the way, I also tested this with a powershell prompt (since powershell is newer I thought the UTF-8 support might be better)--same issue.

**Comment by josevalim** [comment]
Changing the font fixes it? http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500

**Comment by OnorioCatenacci** [comment]
Sorry José -- I should have mentioned that I tried changing the font too
(actually I found that S O answer too) and it didn't help.

On Tue, Feb 9, 2016 at 10:08 AM, José Valim <notifications@github.com>
wrote:

> Changing the font fixes it?
> http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-181907497>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
Oh and while I'm jotting down the circumstances of my test, I also tried
this from a Powershell prompt (as opposed to a cmd prompt) and I got the
same hang result.

On Tue, Feb 9, 2016 at 10:14 AM, Onorio Catenacci <Catenacci@ieee.org>
wrote:

> Sorry José -- I should have mentioned that I tried changing the font too
> (actually I found that S O answer too) and it didn't help.
>
> On Tue, Feb 9, 2016 at 10:08 AM, José Valim <notifications@github.com>
> wrote:
>
>> Changing the font fixes it?
>> http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how/388500#388500
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-181907497>
>> .
>>
>
>
>
> --
> Onorio Catenacci
>
> http://onor.io
> http://www.google.com/+OnorioCatenacci
>
>


-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by josevalim** [comment]
I have read somewhere that setting the codepage is exactly what blocks the input. Unicode characters can work as long as they belong to your default code page.

**Comment by OnorioCatenacci** [comment]
I think it's actually a problem with Erlang.  I just fired up the Erlang terminal (erl) and did this:

x = 'hełło' 

and also

x = "hełło"

(I'm not sure which form is right and I'm not as long on Erlang skills as you are José :) ) 
and it hung there too.  I'd say the best course of action is to ask the Erlang/Windows folks if they know anything about this.

**Comment by OnorioCatenacci** [comment]
I'll post a question to the Erlang folks and see if anyone over there has an idea of what's going on.  Or you can if you'd rather José.  Just let me know how you'd like to proceed.

**Comment by josevalim** [comment]
I don't think this is Erlang related because I have seen folks reporting the same issues with Python (and Ruby). :) One option is to check if iex --werl solves it.

**Comment by OnorioCatenacci** [comment]
Sorry. I guess it would have been more correct for me to say that I think
the issue is at a lower level than Elixir. :)  I mean I know you're right
about others seeing this same behavior in Python and Ruby and a few other
places too.  Interestingly, directly echo'ing the string at the command
prompt works just fine.

The problem doesn't occur in iex.bat --werl but the two unicode characters
(i. e. the two łł characters) are not displayed correctly either.  That's
with a chcp 65001 run first, of course.

On Tue, Feb 9, 2016 at 10:43 AM, José Valim <notifications@github.com>
wrote:

> I don't think this is Erlang related because I have seen folks reporting
> the same issues with Python (and Ruby). :) One option is to check if iex
> --werl solves it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-181919887>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by OnorioCatenacci** [comment]
For whatever it's worth, this works:

 l = <<0xc582::utf16>>
"ł"

I don't think that's a real fix but I mention it in case someone can use it as a workaround if they run into this issue.

**Comment by resilva87** [comment]
Hi, I've done a couple of tests and seems that if I enable code page 65001 through `chcp 65001`, then the problem happens.
If I just open the console, type `iex` and `string = "hełło"`, then everything works.
Kind of weird though.
It seems that if you change the code page, things start **not working**

**Comment by OnorioCatenacci** [comment]
Look closely at the string you get Renato.  The "L" characters do not have
the slash--at least they don't on my machine.

--
Onorio


On Tue, Feb 9, 2016 at 3:25 PM, Renato Silva <notifications@github.com>
wrote:

> Hi, I've done a couple of tests and seems that if I enable code page 65001
> through chcp 65001, then the problem happens.
> If I just open the console, type iex and string = "hełło", then
> everything works.
> Kind of weird though.
> It seems that if you change the code page, things start *not working*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-182046391>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by resilva87** [comment]
@OnorioCatenacci you're correct, I didn't notice.

**Comment by OnorioCatenacci** [comment]
Not trying to split hairs or anything Renato :)  just trying to be sure I
wasn't seeing things wrong.

On Tue, Feb 9, 2016 at 3:30 PM, Renato Silva <notifications@github.com>
wrote:

> @OnorioCatenacci <https://github.com/OnorioCatenacci> you're correct, I
> didn't notice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-182047935>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by resilva87** [comment]
Sure @OnorioCatenacci. Well, as I've installed both Elixir and Erlang through chocolatey (https://github.com/chocolatey/choco) and my Elixir version is not latest, I think I'll wait for a new release update and check things out. I don't have any other ideas except installing Linux in my machine :bowtie: 
I think this can be closed unless you guys want to try something else.

Thank you very much for time and support

**Comment by OnorioCatenacci** [comment]
I really do need to pay better attention to this. I'm the one who takes
care of Chocolatey and I didn't notice that Jose released 1.2.2.  I'll
remedy that one directly.

You may want to retest with 1.2.2 (I didn't test with 1.2.2 myself) but I
suspect the issue is at a lower level than Elixir since we've found reports
of unicode issues with Python and Ruby on Windows as well.

On Tue, Feb 9, 2016 at 4:07 PM, Renato Silva <notifications@github.com>
wrote:

> Sure @OnorioCatenacci <https://github.com/OnorioCatenacci>. Well, as I've
> installed both Elixir and Erlang through chocolatey (
> https://github.com/chocolatey/choco) and my Elixir version is not latest,
> I think I'll wait for a new release update and check things out. I don't
> have any other ideas except installing Linux in my machine [image:
> :bowtie:]
> I think this can be closed unless you guys want to try something else.
>
> Thank you very much for time and support
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-182068240>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by josevalim** [comment]
This is definitely not fixed on 1.2.2. :)

**Comment by OnorioCatenacci** [comment]
Sorry for my tardiness in getting 1.2.2 on Chocolatey Jose!  I really do need to pay better attention when you release new packages. :)

**Comment by resilva87** [comment]
Not trying to clutter the thread's topic but this sure seems to be related to Windows as pointed by @OnorioCatenacci: https://bugs.python.org/issue1602
I'll reinstall Elixir with Web Installer to the new 1.2.2 version and check things out :)

**Comment by OnorioCatenacci** [comment]
Either way Renato.  The 1.2.2 Chocolatey NuGet package should be available
in a couple of hours (it's 16:28 EST where I'm at right now).

On Tue, Feb 9, 2016 at 4:26 PM, Renato Silva <notifications@github.com>
wrote:

> Not trying to clutter the thread's topic but this sure seems to be related
> to Windows as pointed by @OnorioCatenacci
> <https://github.com/OnorioCatenacci>: https://bugs.python.org/issue1602
> I'll reinstall Elixir with Web Installer to the new 1.2.2 version and
> check things out :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-182076933>
> .
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by Steve-O-Cassels** [comment]
Hi there, I've upgraded to Elixir 1.2.4 on Win 10, (not using choco) and with the following steps in cmder

$ chcp 65001
$ iex
iex(1)> ?ł

The CLI hangs.

If I instead:

$ chcp 65001
$ iex --werl
iex(1)> ?ł

I get the correct codepage of 322 whilst in the erland cli

**Comment by OnorioCatenacci** [comment]
Yep.  Known issue.  It's an issue with Erlang not Elixir.  The only
solution is to use werl (which you've found for yourself).   And, I just
tried pasting ł into the Erlang CLI and it hangs for me.  It's an Erlang
issue.

On Mon, Apr 4, 2016 at 10:36 AM, Steve-O-Cassels <notifications@github.com>
wrote:

> Hi there, I've upgraded to Elixir 1.2.4 on Win 10, (not using choco) and
> with the following steps in cmder
>
> $ chcp 65001
> $ iex
> iex(1)> ?ł
>
> The CLI hangs.
>
> If I instead:
>
> $ chcp 65001
> $ iex --werl
> iex(1)> ?ł
>
> I get the correct codepage of 322 whilst in the erland cli
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-205324812>
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by josevalim** [comment]
There is also an environment variable you could set to always start in WERL.

**Comment by OnorioCatenacci** [comment]
That's a good point José.  Thanks for the reminder!

On Mon, Apr 4, 2016 at 11:15 AM, José Valim <notifications@github.com>
wrote:

> There is also an environment variable you could set to always start in
> WERL.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4266#issuecomment-205343488>
>



-- 
Onorio Catenacci

http://onor.io
http://www.google.com/+OnorioCatenacci

**Comment by vincent-lg** [comment]
Just dropping that here: `werl` isn't accessible to screen readers.  For users who generally handle themselves pretty well in CLI mode, that's a no-go.  This is strange too, I'm not sure how this is built.  Bottom line: it seems entering accents in CLI on Windows 10+ (for some reason) isn't an option.  That's too bad, though if an accessible version of Werl is in process (or in flux), I'm more than happy to help.

**Comment by josevalim** [comment]
A pull request has just been sent upstream to add new shell to Windows to Erlang/OTP: https://github.com/erlang/otp/pull/6144

I really recommend trying it out. Check this document on how to build on Windows: https://github.com/erlang/otp/blob/master/HOWTO/DEVELOPMENT.md

**Comment by josevalim** [comment]
Actually, there are pre-built artifacts in the pull request and you can download a Windows installer: https://github.com/erlang/otp/pull/6144#issuecomment-1179159068

**Comment by vincent-lg** [comment]
Good news!  I have tried OTP 26 on Windows and accents seem to be properly displayed (no need to change codepage).  Here's my test on OTP 22:

```erl
1> io:fwrite("~p~n", ["oké"]).
[111,107,130]
ok
2>
```

That doesn't sound like an error to me, though it doesn't sound too good either.  Anyway, if I run the same instruction in OTP 26:

```erl
1> io:fwrite("~p~n", ["oké"]).
"oké"
ok
2>
```

I'm not sure if I used the right flag (I'm not expert on Erlang, or even confident using it) but the result seems optimistic.  So a careful "wow, maybe!".

I'd like to force Iex to run OTP 26 to make sure but I imagine it's not possible without building Elixir itself, which might be hard on Windows.  I'm also running Elixir 1.13.4 on Linux with OTP 25, but as you can see, my OTP version on Windows is 22, so maybe I'll have to wait a bit for an update.

Still, it sounds promising!  Waiting on other feedback,

**Comment by mardukbp** [comment]
Compiling Elixir on Windows is straightforward. Just follow the [instructions](https://github.com/elixir-lang/elixir/wiki/Windows). Before compilation you have to modify `elixir/lib/iex/lib/iex/cli.ex`. Comment out the function `start` and define a new function:

```elixir
def start do
    :user_drv.start([:"tty_sl -c -e", tty_args()])
end
```
 
Compile, run iex and try `IO.puts("oké")`. In order to get autocompletion the `shell` function in broker.ex has to be fixed, since user_drv no longer defines the function `interfaces`.

**Comment by mardukbp** [comment]
Compiling Elixir on Windows is straightforward. Just follow the [instructions](https://github.com/elixir-lang/elixir/wiki/Windows). Before compilation you have to modify `elixir/lib/iex/lib/iex/cli.ex`. Comment out the function `start` and define a new function:

```elixir
def start do
    :user_drv.start([:"tty_sl -c -e", tty_args()])
end
```
 
Compile, run `bin\iex` and try `IO.puts("oké")`. 

In order to get autocompletion the `shell` function in `broker.ex` has to be fixed, since `user_drv` no longer defines the function `interfaces`.
