### ISSUE TITLE
Function list as IEx Macro

### ISSUE THREAD

**Issue by jbodah** [elixir-lang/elixir#4267]
Just learning Elixir and really enjoying it. I realize that you can see a module's functions by doing something like: `String.__info__ :functions`, but it would be suuuper if there was a shortcut for this, maybe something like `f String`. Then my workflow can just be `f String` followed by `h String.codepoints/1`. No need to jump over to the docs or anything :smile_cat:

**Comment by ericmj** [comment]
Write `String.` and then press [TAB] for auto-complete to list the functions.

**Comment by jbodah** [comment]
Awesome thanks!
