### ISSUE TITLE
make ignores user defined prefix. Does make script support install at custom directory?

### ISSUE THREAD

**Issue by linearregression** [elixir-lang/elixir#4269]
make PREFIX=/opt/elixir122  && make install
still install at /usr/local
please add make uninstall 
install.log:
==> elixir (compile)
==> Install prefix /usr/local  <-----
==> elixir (install)
make install_man
make[1]: Entering directory '/opt/elixir-1.2.2'
make clean_man
make[2]: Entering directory '/opt/elixir-1.2.2'
rm -f man/elixir.1
rm -f man/iex.1
make[2]: Leaving directory '/opt/elixir-1.2.2'
make[1]: Leaving directory '/opt/elixir-1.2.2'

**Comment by josevalim** [comment]
Can you please provide those tasks? We would really appreciate a contribution but they are not high priority for us, thank you!

**Comment by linearregression** [comment]
quite a few of companies especially enterprise wants to be able install under custom directory to keep it clean. and are hard requirements for use in production. 
It looks like a change to the makefile. 
e.g I can install Erlang under custom directory.

**Comment by josevalim** [comment]
@linearregression indeed, I think it is a change to the makefile. As I mentioned, a pull request will be really welcome! Thank you!
