### ISSUE TITLE
In elixir 1.2 protocol implementations aren't used when defined in exunit .exs

### ISSUE THREAD

**Issue by meadsteve** [elixir-lang/elixir#4270]
I'm not sure if this is a duplicate (or related) to #4151 but any protocol implementation defined in an .exs file for a test seems to be ignored.
 
Demonstrated by this build:
https://travis-ci.org/meadsteve/CompError/builds/107636091
of this test repo:
https://github.com/meadsteve/CompError

**Comment by fishcakez** [comment]
Compiling will consolidate the protocol - unless disabled - and any implementations set in your `test/**/*.exs` won't be used because they are loaded after the main compilation.

**Comment by josevalim** [comment]
You can disable this behaviour by doing something like:

    consolidate_protocols: Mix.env != :test

in your mix.exs file!

**Comment by meadsteve** [comment]
thanks @josevalim & @fishcakez I think I'd missed this change in 1.2.
