### ISSUE TITLE
HashSet from[[1], []] does not equal HashSet from [[], [1]]

### ISSUE THREAD

**Issue by ijt** [elixir-lang/elixir#4271]
Erlang sets handle this case as expected:

    iex(1)> :sets.from_list([[], [1]]) == :sets.from_list([[1], []])
    true

Elixir HashSets handle it if the arguments are in the same order:

    iex(3)> Enum.into([[], [1]], HashSet.new) == Enum.into([[], [1]], HashSet.new)
    true

but not if they are not:

    iex(4)> Enum.into([[], [1]], HashSet.new) == Enum.into([[1], []], HashSet.new)
    false

**Comment by michalmuskala** [comment]
HashSet does not guarantee structural equality. You need to use `HashSet.equal?/2` function.

It's newer replacement `MapSet` is based on maps and thus guarantees structural equality.
