### ISSUE TITLE
IEx evaluator_test randomly failing?

### ISSUE THREAD

**Issue by tuvistavie** [elixir-lang/elixir#4274]
I just noticed that the build failed in the PR I just sent.

https://travis-ci.org/elixir-lang/elixir/builds/107709147

I have not checked it out yet, but I suspect the error happens randomly,
as the [merge commit](https://travis-ci.org/elixir-lang/elixir/builds/107724048) passed normally.

Any ideas?

**Comment by ericmj** [comment]
Likely because this code has a race condition where application env vars can be unset https://github.com/elixir-lang/elixir/blob/master/lib/iex/test/test_helper.exs#L38-L42

**Comment by tuvistavie** [comment]
@ericmj Thanks for the quick fix!
