### ISSUE TITLE
Support Task.async/2/4 and Task.start_link/2/4

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4289]
They will receive the node name as argument. Built on top of `:rpc.call/4`. @fishcakez, thoughts?

**Comment by fishcakez** [comment]
What is the advantage of using `:rpc.call/2` compared to registering a
`Task.Supervisor` in the `elixir` supervision tree?

**Comment by josevalim** [comment]
Good point. I can think of any besides we would be re-using the already registered process from Kernel.
