### ISSUE TITLE
Compile time warning which didn't saw before

### ISSUE THREAD

**Issue by eminarcissus** [elixir-lang/elixir#4293]
```
defmodule C do

  def test do
    a = %{"bad" => 123}
    if not Enum.empty?(a) do
      a = Map.put a,"good",213
    end
    IO.inspect a
  end
end
```

The following line now warning me with
lib/test.ex:9: warning: the variable "a" is unsafe as it has been set in a conditional clause, as part of a case/cond/receive/if/&&/||. Please rewrite the clauses so the value is explicitly returned. For example:

    case int do
      1 -> atom = :one
      2 -> atom = :two
    end

Can be rewritten as:

    atom =
      case int do
        1 -> :one
        2 -> :two
      end
when doing compiling, which I believe I didn't saw before.(I'm now using the latest elixir master branch with 0407ddc .don't know if that's a new bug or a feature yet.) rewrite the code does fix the warning, which I don't think always writing
 a = if Enum.empty?(a),do: Map.put(a,"good",123),else: a
is a good way to fix the warning here.

**Comment by josevalim** [comment]
It is a new warning. You can check the rationale in the elixir-lang-core mailing list: https://groups.google.com/forum/#!topic/elixir-lang-core/3o-omqgCV3E
