### ISSUE TITLE
`mix deps.get` doesn't update dependency if you update the requested git tag.

### ISSUE THREAD

**Issue by obmarg** [elixir-lang/elixir#4309]
When I want to update a hex.pm package, my approach is usually to change the version I'm requesting in `mix.exs` and then run `mix deps.get`.  This usually pulls in the new version, and changes the mix.lock file for me.

However when I'm pulling dependencies from github, using something like this:

```elixir
{:exometer_datadog, github: "obmarg/exometer_datadog", tag: "v0.4.1"}
```

If I update the tag I'm requesting and run `mix deps.get`, it will not pull in the new tag that I've requested.  However, it will write out the tag I've requested to the `mix.lock` file giving me something like this:

```elixir
"exometer_datadog": {:git, "https://github.com/obmarg/exometer_datadog.git", "7984fe3b01dd762145eac6c4f6f11f72a29254e4", [tag: "v0.4.1"]},
```

Where `7984fe3b` is actually `v0.3.0`, not `v0.4.1`.

Ideally I think `mix deps.get` should behave the same when you change the tag you're requesting as when you change the version.  But if that's not possible, it'd be good to make this problem more obvious somehow - printing the tag in `mix.lock` makes it harder to spot that nothing has actually changed.

**Comment by obmarg** [comment]
Forgot to say - this is on elixir 1.2.2 and 1.2.0

**Comment by josevalim** [comment]
I was able to reproduce this. Thank you for the report.

**Comment by whatyouhide** [comment]
@josevalim are you working on this? If not, I'd be happy to give it a try.

**Comment by josevalim** [comment]
@whatyouhide no, please go ahead. :)

**Comment by josevalim** [comment]
Btw, I am thinking you should have run `mix deps.update`. That's because the old reference "7984fe3b01dd762145eac6c4f6f11f72a29254e4" is valid in both tags, so Mix won't force for an update in there.

**Comment by ericmj** [comment]
> Btw, I am thinking you should have run mix deps.update. That's because the old reference "7984fe3b01dd762145eac6c4f6f11f72a29254e4" is valid in both tags, so Mix won't force for an update in there.

But if "v0.4.1" doesn't point to "7984fe3b01dd762145eac6c4f6f11f72a29254e4" this seems wrong. mix.exs specifies a tag that isn't locked and mix neither updates or complains about this.

**Comment by josevalim** [comment]
Yes, exactly That's why I believe the bug is in the checkout code and not in lock outdated.

**Comment by seanabrahams** [comment]
I ran into this issue with the `branch:` option and have confirmed @whatyouhide's code fixes this as well. Thank you!
