### ISSUE TITLE
Padding in Base.url_encode64 is not URL safe

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4316]
Today we generate padding `=` in Base.url_encode64 which is not safe to use in URLs and would have to be URL encoded.

The spec also allows padding to be skipped on the url_encode64 cases, as mentioned here: https://tools.ietf.org/html/rfc4648#section-5

So we should url_decode64 strings without padding as well as allow them to be generated without padding.

**Comment by riverrun** [comment]
With [pbkdf2 base64 encoding / decoding in Comeonin](https://github.com/elixircnx/comeonin/blob/master/lib/comeonin/pbkdf2/base64.ex), which uses a different alphabet, but is based on the base.ex `do_encode64` and `do_decode64` functions, we already strip the padding.

**Comment by pma** [comment]
Should the default behaviour remain strict and an extra option necessary for the lenient behaviour?
Do we need to work with padding chars different than the default (`=`)?

A possible set of configuration options:

Add to the `encode` functions:

* `padding`: `true` (appends the default padding char =) - default behaviour
* `padding`: `false` (omits padding)
* `padding`: `char` (appends char as padding) - needed?

Add to the `decode` functions that currently enforce padding:

* `padding`: `true` (enforce padding when decoding) - default behaviour
* `padding`: `char` (enforce padding of char when decoding) - needed? 
* `padding`: `:ignore` (accepts input with or without padding)

Considering we now have `ignore: :whitespace` as an option, do we need to use `ignore: [:whitespace, :padding]` to keep the naming consistent?

**Comment by josevalim** [comment]
What is the use case here? Why do we need to support custom padding?

My plan is to support only padding: false on encoding and just support with
and without padding on decode. That's based on the spec. What is the
rationale for all the other combinations proposed?

On Saturday, February 20, 2016, Paulo Almeida <notifications@github.com>
wrote:

> Should the default behaviour remain strict and an extra option necessary
> for the lenient behaviour?
> Do we need to work with padding chars different than the default (=)?
>
> A possible set of configuration options:
>
> Add to the encode functions:
>
>    - padding: true (appends the default padding char =) - default
>    behaviour
>    - padding: false (omits padding)
>    - padding: char (appends char as padding) - needed?
>
> Add to the decode functions that currently enforce padding:
>
>    - padding: true (enforce padding when decoding) - default behaviour
>    - padding: char (enforce padding of char when decoding) - needed?
>    - padding: :ignore (accepts input with or without padding)
>
> Considering we now have ignore: :whitespace as an option, do we need to
> use ignore: [:whitespace, :padding] to keep the naming consistent?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4316#issuecomment-186653112>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by pma** [comment]
@josevalim The custom padding char came up because the RFC mentions using `~` or `.` as an alternative for padding. But adding `padding`: `boolean` (defaults to `true`) to the encode function seems to cover all use cases. If a different alphabet is needed, it can be implemented in a custom module.

Regarding the decode function, I think the default behaviour should remain strict. What do you think should be the option name?

a) We can reuse the `ignore` option and allow `ignore: :padding` and `ignore: [:whitespace, :padding]`
b) We can add a new option to the decode function, specifically to control the padding behaviour 

_"just support with and without padding on decode"_

"without padding" means "padding must **not** be in the input" or "accept even if padding is missing"?

**Comment by josevalim** [comment]
I would go with padding: false on both encoding and decoding. In the former, it means the padding won't be included. In the latter, it means it will accept even if the padding is missing. Do you intend to send a PR? :) I would like to make this part of the 1.2.3 release.

**Comment by pma** [comment]
@josevalim Yes, I'd like to take this one.

**Comment by josevalim** [comment]
Awesome! Please go ahead. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
