### ISSUE TITLE
Incorrect warning when importing module multiple times

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#4317]
Per conversation on IRC, I'm opening up this issue.

Here's how to reproduce it:

```elixir
# $ cat example.exs
import String, only: [upcase: 1]
import String, only: [downcase: 1]

IO.puts String.upcase("hello")
IO.puts String.downcase("hello")

# $ elixir example.exs
# HELLO
# hello
# example.exs:2: warning: unused import String
```

I think in this particular case, there should be no warning.

As a potential improvement, compiler could suggest to keep all imports of a module in the same line (`import String, only: [upcase: 1, downcase: 1]` in this case)

**Comment by ericmj** [comment]
Actually when I check again, both imports are unused so the warning is correct. I'm guessing the first line doesn't warn because `import :only` overwrites the previous `import`.

**Comment by wojtekmach** [comment]
@ericmj yeah, my bad, I forgot to actually take `String.` out from the code
