### ISSUE TITLE
Mix alias chain does not stop in case of non-zero exit code

### ISSUE THREAD

**Issue by vraravam** [elixir-lang/elixir#4318]
In my mix.exs, i have the following:
```
  defp aliases do
    [
      commit: ["deps.get --only #{Mix.env}", "espec --cover", "credo -i todo,duplicatedcode --strict"]
    ]
  end
```
If one of my specs fail, I would expect that the mix invocation bubbles up the exit code and stops the current process. But, this does not happen. Mix only reports the exit code of the last step.

**Comment by ericmj** [comment]
What exit code are you referring to? The aliased tasks runs in the same process.

**Comment by vraravam** [comment]
@ericmj In the above example, i'm trying to run `mix espec --cover` as the second in the "chain". As I mentioned, if I have a failing spec, I would expect the whole `mix commit` task to halt with a non-zero exit code. But that doesnt seem to happen.

**Comment by ericmj** [comment]
Is the problem that the chain doesn't halt on failures or that the exit code is zero when it should be non-zero? Or is it both?

**Comment by vraravam** [comment]
I think its both - since:
1) The chain does not halt on the task that should expose the failure; and
2) When I invoke the same through my CI pipeline, I get a green build.

**Comment by ericmj** [comment]
1) The chain does not halt by design because both the `test` and `espec` tasks does not raise or call `System.halt` on failures. credo does seem to halt on failures which is bad because you should be able to run multiple tasks, a single task should not exit the VM.

We could add a return value to the `test` task to indicate if tests failed or not, the same would have to be done for the two other tasks you call. If you write a custom alias you can check the return values and halt in your code.

2) Looking at the code I can't see why this happens. Can you verify it locally or show a project that reproduces it?

**Comment by josevalim** [comment]
@ericmj we could add a --raise switch to `mix test` that would raise if it fails. Thoughts?

**Comment by ericmj** [comment]
@josevalim A --raise switch and a boolean return value would be great I think.

**Comment by vraravam** [comment]
The project we are using to learn is OSS - here's the GH url: https://github.com/twchennai/Recruitx-Backend

If I uncomment one of the specs marked with `xit`, it will fail. In this state, if I run `MIX_ENV=test mix espec` - the exit code is non-zero. This is reproducible if I call the `espec` task directly. If I use the alias, its not erroring out - which is what I am trying to get fixed :)

**Comment by vraravam** [comment]
ok - just introduced a `expect(true) |> to(eq(false))`. And am seeing the exit code as 1 - though the 3rd task in the alias is also run. But, i think, i can live with the current behavior (as long as it raises non-zero code), I can still hook it upto my CI and get notified on breaking builds.

thanks a lot guys!

**Comment by ericmj** [comment]
@vraravam We can add a `--raise` flag to the `test` task which will halt the chain. But you need to open issues on two other projects you call tasks from.

**Comment by vraravam** [comment]
Sure - will do that. Tx for the VERY quick response! btw - I'm loving elixir and phoenix - keep up the great work!!!

**Comment by ericmj** [comment]
Let's leave this open because we need to implement the switch :)
