### ISSUE TITLE
Sign Elixir release SHAs with known keys?

### ISSUE THREAD

**Issue by garyposter** [elixir-lang/elixir#4323]
Hi! Would you maintainers be open to signing the release SHAs with known GPG keys, a la node?  See their release process for examples, specifically ["Who can make a release? : 3. A Publicly Listed GPG Key"](https://github.com/nodejs/node/blob/master/doc/releases.md#3-a-publicly-listed-gpg-key) and ["How  to create a release : 12. Promote and Sign the Release Builds"](https://github.com/nodejs/node/blob/master/doc/releases.md#12-promote-and-sign-the-release-builds).

These are useful for packaging automation, such as [Node's official Dockerfile](https://github.com/nodejs/docker-node/blob/master/5.6/Dockerfile). People who want to do this kind of check in Elixir are doing things like [specifying the SHA in the Dockerfile](https://github.com/voidlock/docker-elixir/blob/master/1.1/Dockerfile), which requires more frequent updates to build automation scripts.

Thanks for considering!

**Comment by josevalim** [comment]
Can you please post such discussions in the elixir-lang-core mailing list as asked in the opening issue template? Many others will be able to contribute to the discussion there. Thank you.
