### ISSUE TITLE
iex pipeline

### ISSUE THREAD

**Issue by yltsrc** [elixir-lang/elixir#4324]
It would be nice to have feature line we have in irb, when you can use last returned value
I just wondering if we can have behaviour like described below, because it may be very useful
and it is valid elixir code as well, so it can be run when it is written in file, but not in iex

### Environment

* Elixir version (elixir -v): 1.2.1
* Operating system: mac os 10.11.2

### Current behavior

```
iex(1)> Integer.digits(12)
[1, 2]
iex(2)> |> Enum.sum
** (SyntaxError) iex:2: syntax error before: '|>'
```

### Expected behavior

```
iex(1)> Integer.digits(12)
[1, 2]
iex(2)> |> Enum.sum
3
```

**Comment by yltsrc** [comment]
feel free to close the ticket if you think it is not a right time to implement it :wink:

**Comment by wojtekmach** [comment]
You can already use the 'v' IEx helper to grab the value from the last expression. In general you probably want to ask questions/propose new features on the mailing list :)

**Comment by josevalim** [comment]
Interesting enough. We could make this work. I can foresee two complications if we do such:

1. We would need to support such on iex
2. We would need to support such for iex inside doctests

It may be worth doing it because it is a common source of confusion and I don't think such addition would harm people's understanding of Elixir syntax and rules.

**Comment by lexmag** [comment]
I'm more toward :-1:, It feels inconsistent to other operators. I rather see proposed behaviour confusing, I think for most (every?) REPLs it's natural to treat one-line expression as is and not to wait for extra content, for example the following Ruby code doesn't work in irb:
```ruby
User
.where(<long condition>)
.select(<select statement>)
.joins(:posts)
```

> It would be nice to have feature line we have in irb, when you can use last returned value

As @wojtekmach said, we already have `v` helper for that, it's even more powerful (as it accepts index argument) than Ruby's `_`.

If the "chaining" is still needed there is `\` available:
```elixir
iex(1)> Integer.digits(12) \
...(1)> |> Enum.sum
3
```
Also there is a trick I use to copy multiline-pipe-expression from the source code into IEx:
```elixir
iex(2)> (Integer.digits(12)
...(2)> |> Enum.sum)
3
```
start with `(` and close `)` after. :bowtie:

**Comment by ericmj** [comment]
Agree with @lexmag.

**Comment by heavyk** [comment]
I'm still learning elixir so I don't know everything, but this is super useful to me. in iex you can do this:

```
ex(1)> Integer.digits(12)
[1, 2]
iex(2)> v(-1)
[1, 2]
iex(3)> v(-1) |> Enum.sum
3
```

when calling v(n), n will be the nth iex statement - and you see next to ex(n) (for positive integers) - or negative n refers to previous values. (-1 for previous, -2 for second to last, etc.)
