### ISSUE TITLE
Match Multiple Structs

### ISSUE THREAD

**Issue by hamiltop** [elixir-lang/elixir#4327]
Per https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-lang-core/U6bQqVKL3UE/QE9bBBibAgAJ

It was proposed to allow pattern matching on the Struct type itself.

The following code:

```elixir
%x{} = some_struct
```

Would be functionally equivalent to:

```elixir
%{__struct__: x} = some_struct
```

Valid use cases:

```elixir
case some_struct do
  %x{} when x in [A, B, C] -> {:ok, some_struct}
  %x{} when x in [D, E] -> {:error, some_struct}
end
```

```elixir
def ensure_map(s = %_x{}), do: Map.from_struct(s)
def ensure_map(m = %{}), do: m
```

```elixir
struct_module = get_struct_module
s = %^struct_module{} = get_result
```

A few cases that were not clear:

```elixir
x = User
%x{name: "john", age: 27}
```
Should that be valid? or should it raise at compile time?

```elixir
%unquote(1){}
```
That should definitely raise, in or out of a match.

Any other cases we are missing?

**Comment by josevalim** [comment]
It is already in master. :)

**Comment by hamiltop** [comment]
Wonderful! Thanks!
