### ISSUE TITLE
mix deps.clean --unused doesn't write change to mix.lock 

### ISSUE THREAD

**Issue by zhangsoledad** [elixir-lang/elixir#4328]
### Environment

* Elixir version (elixir -v): Elixir 1.2.3
* Operating system:  osx

### Current behavior

when i change mix.exs 
run `mix deps.clean --unused` ,  it cleaned the unused deps,
but doesn't write change to mix.lock

**Comment by josevalim** [comment]
You need to pass the `--unlock` flag. :)

**Comment by zhangsoledad** [comment]
@josevalim  thx
