### ISSUE TITLE
Pending escript tasks

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4330]
* [x] Check the file is an actual escript before writing to disk
* [x] Verify they work on Windows (it will likely need .bat files to be generated)

/cc @alco can you please tackle the first one?

**Comment by josevalim** [comment]
Issue updated to add `MIX_ESCRIPTS`.

**Comment by alco** [comment]
> Check the file is an actual escript before writing to disk

I may be able to look into it tomorrow. If you don't hear from me then, I apologize in advance :sweat_smile:

**Comment by josevalim** [comment]
@alco it now works on Windows because we also write .bat files. :)

**Comment by sivsushruth** [comment]
I have added 
```
!function_exported?(main, :main, 1) ->
  Mix.raise "Module does not contain main/1"
```
(escript.build.ex)

**Comment by josevalim** [comment]
Thank you but the check not be done before building but after installation. We will have to open the file and snoop around if it is an actual escript.

**Comment by jcspencer** [comment]
Is there any specific standard escript header that can be checked? That seems like the only check we could perform that would be effective across the board.

**Comment by josevalim** [comment]
You can look at `escript:parse_file/1` for ideas on how we can validate them. I believe we don't need to consider all formats for now but only the one generated by `escript.build`. Source: https://github.com/erlang/otp/blob/maint/lib/stdlib/src/escript.erl#L403

**Comment by jcspencer** [comment]
It looks like the only per-line check performed in OTP is:

```erlang

classify_line(Line) ->
    case Line of
        "#!" ++ _ -> shebang;
        "PK" ++ _ -> archive;
        "FOR1" ++ _ -> beam;
        "%%!" ++ _ -> emu_args;
        "%" ++ _ -> comment;
        _ -> undefined
   end.
```
This should be enough to confirm that the file is an escript from the first few bytes.

**Comment by josevalim** [comment]
Yes, that would be awesome. :)

**Comment by Troush** [comment]
Added ```is_escript``` implementation and check before writing to disk https://github.com/Troush/elixir/commit/9b1d833888263ed2f7b57d8023530620368e709b

Do this is what we want? Or not?

**Comment by josevalim** [comment]
@Troush that's a step in the proper direction. We probably want to define that here though:

https://github.com/Troush/elixir/blob/9b1d833888263ed2f7b57d8023530620368e709b/lib/mix/lib/mix/tasks/escript.install.ex

The place you changed is shared by both archives and escripts and I think we could make it escript only.
