### ISSUE TITLE
Confusing error message when incorrectly casing an Elixir module.

### ISSUE THREAD

**Issue by tokafish** [elixir-lang/elixir#4342]
### Environment

* Elixir version: 1.2.3
* Operating system: OS X 10.11

### Current behavior

When incorrectly casing the name of an Elixir module, Elixir logs an error message that I think could be improved.

Example, if I have code like the following:

```
defmodule MyServer do
  use GenServer

  def do_it(server) do
    Genserver.call(server, :do_it)
  end
end
```

I see the following messages when I start iex:

> 08:53:19.865 [error] Loading of /usr/local/Cellar/elixir/1.2.3/bin/../lib/elixir/ebin/Elixir.Genserver.beam failed: :badfile
> 08:53:19.865 [error] beam/beam_load.c(1278): Error loading module 'Elixir.Genserver':
>   module name in object code is Elixir.GenServer

### Expected behavior

I'm not sure what would be the best thing to do here. My only thought is that if the error message were simply suppressed, it might be less confusing, because you'd still get `undefined function Genserver.call/2 (module Genserver is not available)` later when you attempted to use the code, and it would be more consistent with the error you get when you attempt to call a function on any other undefined module.

**Comment by josevalim** [comment]
I agree those are not nice error messages but there is nothing we can do. They come directly from the emulator and I am not sure supressing it is enough because you could trigger it by calling Code.ensure_loaded?(Genserver) and then you would have a silent failure. :(

**Comment by tokafish** [comment]
Understood. Thanks for the info!
