### ISSUE TITLE
Mix can't shell out to rebar on Windows

### ISSUE THREAD

**Issue by Gobiner** [elixir-lang/elixir#4345]
### Current behavior

Running `mix deps.compile esqlite` on Windows, in my phoenix project folder, yields the following error:
```
'c:/Program' is not recognized as an internal or external command, operable program or batch file.
 ** (Mix) Could not compile dependency :esqlite, "c:/Program Files/erl7.2.1/bin/rebar.cmd compile skip_deps=true deps_dir="c:/Users/Aaron/Desktop/hurdoo/_build/dev/lib"" command failed.
```

A little digging showed me that mix is attempting to shell out to `C:\\WINDOWS\\system32\\cmd.exe /c c:/Program Files/erl7.2.1/bin/rebar.cmd compile skip_deps=true deps_dir="c:/Users/Aaron/Desktop/hurdoo/_build/dev/lib"`

This has a couple of issues. The first is that the path to rebar has spaces but isn't surrounded by quotes. I changed Mix.Rebar.wrap_cmd to resolve that, like so:

```
@@ -276,10 +276,13 @@ defmodule Mix.Rebar do

   defp wrap_cmd(nil), do: nil
   defp wrap_cmd(rebar) do
-    if match?({:win32, _}, :os.type) and not String.ends_with?(rebar, ".cmd") do
-      "escript.exe \"#{rebar}\""
-    else
-      rebar
+    cond do
+      match?({:win32, _}, :os.type) and not String.ends_with?(rebar, ".cmd") ->
+        "escript.exe \"#{rebar}\""
+      match?({:win32, _}, :os.type) and String.ends_with?(rebar, ".cmd") ->
+        "\"#{rebar}\""
+      true ->
+        rebar
     end
   end
```
This changes the command to `C:\\WINDOWS\\system32\\cmd.exe /c "c:/Program Files/erl7.2.1/bin/rebar.cmd" compile skip_deps=true deps_dir="c:/Users/Aaron/Desktop/hurdoo/_build/dev/lib"` which looks better. However, even with the path quoted, the result is the exact same error message. From `cmd /?`:
```
If /C or /K is specified, then the remainder of the command line after
the switch is processed as a command line, where the following logic is
used to process quote (") characters:

    1.  If all of the following conditions are met, then quote characters
        on the command line are preserved:

        - no /S switch
        - exactly two quote characters
        - no special characters between the two quote characters,
          where special is one of: &<>()@^|
        - there are one or more whitespace characters between the
          two quote characters
        - the string between the two quote characters is the name
          of an executable file.

    2.  Otherwise, old behavior is to see if the first character is
        a quote character and if so, strip the leading character and
        remove the last quote character on the command line, preserving
        any text after the last quote character.
```
Apparently, the solution is to pass /S and wrap your entire command in another set of quotes. This lead me to change Mix.Shell like so
```
@@ -117,9 +117,9 @@ defmodule Mix.Shell do
       {:win32, osname} ->
         command = String.to_char_list(command)
         case {System.get_env("COMSPEC"), osname} do
-          {nil, :windows} -> 'command.com /c ' ++ command
-          {nil, _}        -> 'cmd /c ' ++ command
-          {cmd, _}        -> '#{cmd} /c ' ++ command
+          {nil, :windows} -> 'command.com /S /C ' ++ command
+          {nil, _}        -> 'cmd /S /C ' ++ command
+          {cmd, _}        -> '#{cmd} /S /C "#{command}"'
         end
     end
   end
```
However, this still doesn't fix the issue. The paths have backslashes in them, which I surmised might be an issue. When I replaced the backslashes in `command` to Windows's forward slashes, it worked!

```
@@ -115,11 +115,13 @@ defmodule Mix.Shell do
         'sh -c "' ++ command ++ '"'

       {:win32, osname} ->
-        command = String.to_char_list(command)
+        command = command
+          |> String.replace("/", "\\")
+          |> String.to_char_list
         case {System.get_env("COMSPEC"), osname} do
-          {nil, :windows} -> 'command.com /c ' ++ command
-          {nil, _}        -> 'cmd /c ' ++ command
-          {cmd, _}        -> '#{cmd} /c ' ++ command
+          {nil, :windows} -> 'command.com /S /C "#{command}"'
+          {nil, _}        -> 'cmd /S /C "#{command}"'
+          {cmd, _}        -> '#{cmd} /S /C "#{command}"'
         end
     end
   end
```
Well, it fixed `mix` not being to shell out to `rebar`. I still can't compile `esqlite` but at least `rebar` is trying now. The code to change path separators is awfully broad, and it will break any commands that use forward slashes for something that isn't path separation, so I chose not to create a pull request.

**Comment by Gobiner** [comment]
I forgot to mention that I'm running on Erlang/OTP 18 and Elixir 1.2.3

**Comment by josevalim** [comment]
Thank you @Gobiner for such a detailed report! Which Windows version are you running on? According to the Windows docs, I see this:

>      Command : The command, program or batch script to be run.
>                This can even be several commands separated with '&' 
>                (the whole should also be surrounded by "quotes")

So I am thinking we may be able to not use \S as long as we quote correctly. Can you try the following changes:

```diff
       {:win32, osname} ->
-        command = String.to_char_list(command)
+        command = '"' ++ String.to_char_list(command) ++ '"'
         case {System.get_env("COMSPEC"), osname} do
           {nil, :windows} -> 'command.com /c ' ++ command
           {nil, _}        -> 'cmd /c ' ++ command
           {cmd, _}        -> '#{cmd} /c ' ++ command
         end
     end
   end
```

Then we move the path replacing to wrap_cmd "/" by "\\". Can you please try this:

```elixir
    defp wrap_cmd(rebar) do
      cond do
        not match?({:win32, _}, :os.type) ->
          rebar
        String.ends_with?(rebar, ".cmd") ->
          "\"#{String.replace(rebar, "/", "\\")}\""
        true ->
          "escript.exe \"#{rebar}\""
      end
    end
```

Can you please let me know how it goes? Thank you! :heart:

**Comment by Gobiner** [comment]
I tried your proposed changes and mix shelled out to rebar without issue. I give it the Works On My Machine seal of approval.
![Works On My Machine](https://i.imgur.com/WnmTVx0.png)

The `deps_dir="c:/Users/Aaron/Desktop/hurdoo/_build/dev/lib"` bit still has forward slashes of course, but that didn't seem to change the behavior (my test case doesn't compile successfully regardless, so this might not be strong evidence).

**Comment by josevalim** [comment]
@Gobiner thank you! I went with `/s` anyway because it is supported since Windows XP, so we should be safe and run into less corner cases. The deps_dir path does not matter because it is handled by rebar so that should just work™.
