### ISSUE TITLE
Unit test touch_with_timestamp fails on February 29th

### ISSUE THREAD

**Issue by aleksandarzivkovic** [elixir-lang/elixir#4347]
### Environment

* Elixir version: https://github.com/elixir-lang/elixir/archive/v1.0.0.tar.gz
* Operating system: building on Ubuntu 2.6.32-38-generic-pae #83-Ubuntu SMP Wed Jan 4 12:11:13 UTC 2012 i686 GNU/Linux 

### Current behavior
Our build server runs nightly build of elixir package. After build is performed unit tests are executed.
During the unit test execution (at least) one test fails when system clock date is February 29th. Here is output from the test that fails:
`test touch_with_timestamp (FileTest)
     test/elixir/file_test.exs:1159
     ** (File.Error) could not touch /var/lib/hudson/jobs/Buildroot_2013-02_x86_Head/workspace/buildroot-2013.02/output/build/elixir-1.0.0/lib/elixir/tmp/tmp_test.txt: bad argument
     stacktrace:
       (elixir) lib/file.ex:339: File.touch!/2
       test/elixir/file_test.exs:1166`
When I change system clock date to March 1st all tests pass.

### Expected behavior
All unit tests pass.

**Comment by wojtekmach** [comment]
This is already fixed in master with https://github.com/elixir-lang/elixir/pull/4344
