### ISSUE TITLE
Compilation hangs indefinitely

### ISSUE THREAD

**Issue by stevedomin** [elixir-lang/elixir#4351]
### Environment

* Elixir version (elixir -v): 1.2.3
* Operating system: OS X 10.11.2

### Current behavior

I've ported the UUID module from Ecto to my project because I need a tiny incompatible change to it. I meant to wrap the code around `if Code.ensure_loaded?()` statement to make sure this was only compiled when Ecto was in the project. Fast forward a couple of days, I haven't added the `ecto` dependency to my project and I try to compile and it just hangs. I don't get any error message.

Here's a repo that reproduces the error: https://github.com/stevedomin/elixir_compilation_bug

### Expected behavior

I would expect to see an error message or at least it shouldn't hang forever.

**Comment by josevalim** [comment]
It should be fixed in Ecto master. :)

**Comment by stevedomin** [comment]
Awesome thanks @josevalim 

Can you point me to the relevant commit?

Also I felt like this was more of a bug in Elixir rather than in Ecto. Is that not the case?

**Comment by josevalim** [comment]
Oops, I mean to say it is fixed in Elixir master, I am sorry. Here is the commit: https://github.com/elixir-lang/elixir/commit/b6dc389f5e3eb2286885c172009333ef414d7860

**Comment by stevedomin** [comment]
Aaah, that makes sense :) Thanks
