### ISSUE TITLE
I need to issue deps.compile twice to get my .so copied in _build/dev/lib/fast_xml/priv/lib

### ISSUE THREAD

**Issue by mremond** [elixir-lang/elixir#4352]
### Environment

* Elixir version (elixir -v): Elixir 1.2.0
* Operating system: OSX 10.11.3

### Current behavior

My mix.exs:

```
...
  defp deps do
    [{:ejabberd, "~> 16.2"}]
  end
...
```

```
$ mix deps.get
...
$ mix deps.compile
...
$ ls -la _build/dev/lib/fast_xml/priv
ls: _build/dev/lib/fast_xml/priv: No such file or directory
$ mix deps.compile
...
$ ls -la _build/dev/lib/fast_xml/priv/lib/*
-rwxr-xr-x+ 1 mremond  staff  14104 Mar  2 20:18 _build/dev/lib/fast_xml/priv/lib/fxml.so
-rwxr-xr-x+ 1 mremond  staff  27764 Mar  2 20:18 _build/dev/lib/fast_xml/priv/lib/fxml_stream.so
```

### Expected behavior

I expect that the .so file are copied to _build/dev/lib/fast_xml/priv/lib/ on first mix deps.compile run.

Did I miss something ?

**Comment by josevalim** [comment]
Is fast_xml an Elixir project?

**Comment by mremond** [comment]
This is an Erlang project, built with Mix: https://github.com/processone/fast_xml

**Comment by whatyouhide** [comment]
@mremond I tried to reproduce your output but was not able to. I tried on 1.2.0 and OSX 10.11.3 as well. I just created a fresh project, added just `{:ejabberd, "~> 16.2"}` to my deps (didn't change anything else in `mix.exs`) and ran:

```bash
$ mix deps.get
$ mix deps.compile
```

I have the `.so` files in `_build/dev/lib/fast_xml/priv/`. Could you try this on a new project and tell us if you still have this problem?

**Comment by mremond** [comment]
Thanks for checking out :+1: 

Sure, I will retry from scratch.
It was already a new project, but I will restart from scratch to see if some local tinkering could be interfering.

**Comment by mremond** [comment]
@whatyouhide I check from scratch with Elixir 1.2.3 and it seems to work fine.

I think the original issue what that the priv dir need to be packaged in the hex.pm archive, even empty.

**Comment by whatyouhide** [comment]
Alright, thanks for the report anyways @mremond :)
