### ISSUE TITLE
Integer.parse/1, inconsistent error reporting

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [elixir-lang/elixir#4356]
### Environment

* Elixir version (elixir -v): Elixir 1.3.0-dev
* Operating system: Windows 10

### Current behavior

```iex
iex(1)> Integer.parse("1433")
{1433, ""}
iex(2)> Integer.parse(nil)
** (FunctionClauseError) no function clause matching in Integer.parse_in_base/2
    (elixir) lib/integer.ex:145: Integer.parse_in_base(nil, 10)
iex(2)> Integer.parse("")
:error
iex(3)> Integer.parse("0")
{0, ""}
iex(4)> Integer.parse("-")
:error
```

### Expected behavior

`Integer.parse(nil)` should give `:error` 

should give same error as` Integer.parse("some invalid integer")`

**Comment by NobbZ** [comment]
The spec of `Integer.parse/2` is clearly stating that it wants a binary as input, while `nil` is an atom. From my point of view missing clause is what I'd expect in this case.

**Comment by ericmj** [comment]
`Integer.parse` will return `:error` when the given string is an invalid string, if not given a string it will raise. This is a convention of all Elixir functions and in line with the "let it crash" philosophy.
