### ISSUE TITLE
(Mix) Failed to open Hex registry

### ISSUE THREAD

**Issue by alxgnon** [elixir-lang/elixir#4365]
I get the same error every time I run `mix`.
```
$ mix
** (Mix) Failed to open Hex registry ({:read_error, {:file_error, '/home/alxgnon/.hex/registry.ets', :enoent}})
```

I just installed Elixir on this machine. Here is the first time output of `mix`:
```
$ mix               
Could not find Hex, which is needed to build dependency :phoenix
Shall I install Hex? [Yn] 
* creating /home/alxgnon/.mix/archives/hex-0.11.1.ez
** (Mix) Failed to open Hex registry ({:read_error, {:file_error, '/home/alxgnon/.hex/registry.ets', :enoent}})
```

The registry file does not exist. Maybe it was supposed to be created automatically and wasn't? I tried this too and it also fails:
```
$ touch ~/.hex/registry.ets
$ mix
** (Mix) Failed to open Hex registry ({:read_error, {:not_a_log_file, '/home/alxgnon/.hex/registry.ets'}})
```

### Environment (Elixir 1.2.3, Debian jessie)
```
$ elixir -v
Erlang/OTP 18 [erts-7.2] [source-e6dd627] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.2.3
$ uname -a
Linux progress 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux
```

**Comment by alxgnon** [comment]
### Update:

I found two different workarounds to fix this for myself.

The first workaround is to run `mix hex.registry fetch` to fetch the registry manually.

The second workaround is to run `mix deps.get` before running any other mix commands. It will fetch the registry.

I will leave the issue open because it might be an indicator of a bug. There might be a way to prevent this error from happening.

**Comment by josevalim** [comment]
Can you please run `mix hex.info` and let us know?

**Comment by josevalim** [comment]
Btw, the registry file is never supposed to be created by hand.

**Comment by alxgnon** [comment]
```
$ mix hex.info
Hex:    0.11.1
Elixir: 1.2.3
OTP:    18.2

Built with: Elixir 1.2.3 and OTP 18.2.4

Registry file available (last updated: 2016-03-06 16:12:05)
Size: 1599kB (compressed 519kb)
Packages #: 1663
Versions #: 7426
```

**Comment by alxgnon** [comment]
It seems running hex.info generated the registry file?

**Comment by ericmj** [comment]
@josevalim I think we should print the stacktrace on Mix errors also. I have an idea where this happens but I am not 100% sure because we have no trace.

**Comment by josevalim** [comment]
MIX_DEBUG will start printing the stacktrace but honestly, you should likely not be raising Mix.Error for a case like this.

**Comment by ericmj** [comment]
I've changed the error message in hex to "** (Mix) Failed to open Hex registry (file does not exist, run `mix hex.info` to fetch it)".

**Comment by aaronjensen** [comment]
@josevalim  @ericmj Is this really fixed? It's common for us on our docker container to get this new error message now when just running a `mix test` if the deps are already in place. We use a shared volume for our deps so our test container doesn't need to do a `mix deps.get`, which means we get build failures w/ this unless we do a `mix hex.info` first. This seems weird.

**Comment by ericmj** [comment]
@aaronjensen The only "fix" was improving the error message.

You get the error because the registry is not available on your docker instance. Which hex version do you have, hex should no longer require the registry when loading the dependencies. Please reopen this issue on https://github.com/hexpm/hex with this information, the commands your run and their output.

**Comment by aaronjensen** [comment]
@ericmj the latest. It's not while loading, it's while building exsyslog. I can open an issue.

**Comment by aaronjensen** [comment]
I can't create a repro with that I thought the problem was. It's probably something specific to the order I was doing things in. I'll open an issue if I manage to create a repro some day.

**Comment by JoshSmith** [comment]
We're seeing this issue right now. Digging in to see what's happening because it's a little unclear as of right now.
