### ISSUE TITLE
Hard to understand error message when using <> with non binaries

### ISSUE THREAD

**Issue by paulcsmith** [elixir-lang/elixir#4366]
### Environment

* Elixir version (elixir -v): 1.2.2
* Operating system: OS X 10.11.3

### Current behavior

```elixir
"something" <> 1
```

Raises: `ArgumentError: argument error`

In this particular example it is fairly easy to see what's wrong, but I've had instances similar to this that are harder to figure out:

```elixir
def add_to_url(id_of_a_record) do
  "example.com" <> id_of_a_record
end

add_to_url(user.id) # user.id returns an integer
```

### Expected behavior

If possible, I think that the function should say something like:

```
Expected both arguments to <>/2 to be binaries. Instead got #{first_arg} and #{second_arg}
```

Something similar would be nice for calling `var.foo` on non maps/structs (as mentioned in https://github.com/elixir-lang/elixir/issues/3494), but I guess that's still not possible?

**Comment by josevalim** [comment]
There is not much we can do here unfortunately. We could add checks but it would affect performance and the behaviour inside matches.

**Comment by paulcsmith** [comment]
That's too bad. Thanks for the clarification!
