### ISSUE TITLE
ExUnit.DocTest misses tests when iex prefix contains a number

### ISSUE THREAD

**Issue by digitalronin** [elixir-lang/elixir#4368]
#According to the docs, doctest should cope with iex prefixes that contain numbers (the default) like this;

    iex(1)> MyModule.foo

But, the presence of a number seems to cause the doctests to be skipped, as per this gist;

https://gist.github.com/digitalronin/dc81b24f2fa4264b524f

* Elixir version 1.2.2
* Operating system: OSX 10.11.3

### Current behavior

This runs a failing doctest;

```
defmodule MyApp do
  @doc """
  iex> MyApp.foo
  123
  """
  def foo do
    456
  end
end
```

With this version, the doctest is not run;

```
defmodule MyApp do
  @doc """
  iex(1)> MyApp.foo
  123
  """
  def foo do
    456
  end
end
```

### Expected behavior

According to the docs here http://elixir-lang.org/docs/stable/ex_unit/ExUnit.DocTest.html  the presence of numbers in the iex prefix shouldn't matter, so the doctest should run, and fail, in both cases.

**Comment by lexmag** [comment]
Closed in cd6a102a5dc1cbaa9a940313786d9bf00489d813.

@digitalronin thank you for report. :yellow_heart:
