### ISSUE TITLE
Manpages are not installed correctly via homebrew

### ISSUE THREAD

**Issue by accatyyc** [elixir-lang/elixir#4378]
### Environment

* Elixir version (elixir -v): `Elixir 1.2.3`
* Operating system: `OSX 10.11.3`

### Current behavior

`man elixir` yields `No manual entry for elixir`

### Expected behavior

`man elixir` should display the info in https://github.com/elixir-lang/elixir/blob/master/man/elixir.1.in

I noticed that manpages actually exist for Elixir by browsing the repo here. Previously I have always assumed that there were none available. I suppose installing them doesn't work correctly when installing Elixir via [homebrew](http://brew.sh).

**Comment by josevalim** [comment]
Thank you @accatyyc! We are not responsible for how Elixir is packaged in the many different managers and OSes, so I would recommend opening an issue directly in homebrew or sending a pull request. Feel free to link the PR here if you would like help getting reviewed.
