### ISSUE TITLE
How to run a shell command ?

### ISSUE THREAD

**Issue by robin850** [elixir-lang/elixir#438]
Hello,

I have google about that but I haven't found anything. Could you help me telling me how we can run a shell command such as `ls` with Elixir please ? I have found that for Erlang but it doesn't work in Elixir:

``` erlang
Eshell V5.9.1  (abort with ^G)
1> os:cmd("ls").
"main.ex\n"
```

Thanks, have a nice day.

**Comment by JLarky** [comment]
```
iex(1)> System.cmd "ls", []
```
