### ISSUE TITLE
GenServer crashes without logging

### ISSUE THREAD

**Issue by adamkittelson** [elixir-lang/elixir#4381]
### Environment

* Elixir version (elixir -v): 1.2.0
* Erlang version: 18.2.1
* Operating system: OS X 10.9.5

I converted a call to a cast in a genserver yesterday but I made a mistake when altering the return value tuple, rather than going from `{:reply, resp, state}` to `{:noreply, state}` I absentmindedly landed on `{:noreply, resp, state}`

This caused my process to crash (rightly) because my 3rd argument was not an integer (the 3rd argument is a timeout value).

### Current behavior
My issue is that the crash resulted in no logging or errors.

To eliminate anything in my application as a cause I created a minimal repo at https://github.com/adamkittelson/noreply-test which contains a small genserver written in Elixir and one written in Erlang, both of which behave the same way, so this may be an OTP issue (assuming it's an issue at all and that there's not a reason for the behavior that I'm not seeing.)

```
Interactive Elixir (1.2.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> # Elixir
iex(2)> elixir = Process.whereis(:elixirbadserver)
#PID<0.209.0>
iex(3)> Process.monitor(elixir)
#Reference<0.0.3.147>
iex(4)> NoreplyTest.BadServer.boom!(elixir)
:ok
iex(5)> Process.whereis(:elixirbadserver) # different pid because it crashed and was restarted
#PID<0.217.0>
iex(6)> flush
{:DOWN, #Reference<0.0.3.147>, :process, #PID<0.209.0>, :timeout_value}
:ok
iex(7)> 
iex(8)> # Erlang
iex(9)> erlang = Process.whereis(:erlangbadserver)
#PID<0.210.0>
iex(10)> Process.monitor(erlang)
#Reference<0.0.1.155>
iex(11)> :bad_server.boom(erlang)
:ok
iex(12)> Process.whereis(:erlangbadserver) # different pid because it crashed and was restarted
#PID<0.225.0>
iex(13)> flush
{:DOWN, #Reference<0.0.1.155>, :process, #PID<0.210.0>, :timeout_value}
:ok
```

### Expected behavior

I would expect to see some kind of logging or error report of a crash, such as below where I intentionally give a bad value to `after` in a receive block in a Task.

```
iex(16)> Task.start fn ->
...(16)>   receive do
...(16)>   after :some_bad_value -> :noop
...(16)>   end
...(16)> end
{:ok, #PID<0.234.0>}
iex(17)> [error] Task #PID<0.234.0> started from #PID<0.211.0> terminating
** (stop) :timeout_value
    :prim_eval.receive/2
    (stdlib) erl_eval.erl:959: :erl_eval.receive_clauses/7
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<20.54118792/0 in :erl_eval.expr/5>
    Args: []
```

As always thanks for all the work you do on Elixir! Sorry if this doesn't belong here due to being an OTP issue instead, I'm just not 100% sure where the line is there or if my Erlang example running in the context of a mix app is a potential factor or not.

**Comment by fishcakez** [comment]
The error is occurring inside the `:gen_server` code so there is anything to be done in Elixir itself. A `:crash_report` will be logged in this situation. Logger will log this report with the following config:
```elixir
config :logger, handle_sasl_reports: true
```
