### ISSUE TITLE
OpenSSL 0.9.8 Ubuntu 15.10

### ISSUE THREAD

**Issue by bartoszbinda** [elixir-lang/elixir#4388]
There is a problem installing Erlang/Elixir on Ubuntu 15.10 due to the fact of unmet dependencies.

**Comment by josevalim** [comment]
Can you please read the template and open an issue and provide proper information in the bug report? How are you installing it? From which package? Which error are you seeing? It is unlikely this is an Elixir error but rather an Erlang one. Thank you.
