### ISSUE TITLE
Unexpected stack trace during debugging

### ISSUE THREAD

**Issue by KaySackey** [elixir-lang/elixir#4391]
### Environment

* Elixir version (elixir -v): Elixir 1.2.2
* Operating system: Mac OSX

### Current behavior

If you create a Supervisor and override start_link, and have an error within that method to  Supervisor.start_link/3 then the stacktrace will skip the function that you defined.

     ** (CaseClauseError) no case clause matching: "rooms-lobby"
         (elixir) lib/supervisor.ex:297: Supervisor.start_link/3
         (server_el) web/models/room/registry.ex:21: Room.Registry._start_child/1
         (server_el) web/models/room/registry.ex:96: Room.Registry.handle_call/3
         (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
         (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
         (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

Include code samples, errors and stacktraces if appropriate.

### Expected behavior

     ** (CaseClauseError) no case clause matching: "rooms-lobby"
         (elixir) lib/supervisor.ex:297: Supervisor.start_link/3
         (server_el) web/models/room/supervisor.ex:9: Room.Supervisor.start_link/1
         (server_el) web/models/room/registry.ex:21: Room.Registry._start_child/1
         (server_el) web/models/room/registry.ex:96: Room.Registry.handle_call/3
         (stdlib) gen_server.erl:629: :gen_server.try_handle_call/4
         (stdlib) gen_server.erl:661: :gen_server.handle_msg/5
         (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

**Comment by josevalim** [comment]
That's how Elixir works, it performs tail call optimization. if the last thing you do in a function is to call another function, the caller won't be included in the stacktrace.
