### ISSUE TITLE
Confusing error: "undefined function" when actually private

### ISSUE THREAD

**Issue by nathanl** [elixir-lang/elixir#4405]
### Environment

* Elixir version (elixir -v): 1.3.0-dev
* Operating system: OS X 10.11

### Current behavior

`apply(__MODULE__, :name_of_private_function, [some,args]` gives error "undefined function"

### Expected behavior

I was confused by this. I figured out that `apply` is inlined to `__MODULE__.name_of_function...`, but it took a minute to understand that the function definition I was looking at wasn't being found because it was private.

I think that something like "undefined (**or private**) function Foo.bar/2" would be a clearer error.

**Comment by josevalim** [comment]
We could use something like `String.module_info(:functions)` to find out if it is private or not and show a proper error but I am really not sure if we should.

**Comment by lexmag** [comment]
I'm :-1: on doing so.

**Comment by sunny-mittal** [comment]
For what it's worth, I would agree that actually catering the error to private vs undefined functions would be a little unsafe, but amending the existing message to convey that the function is either undefined or private might be useful.

**Comment by nathanl** [comment]
I'd be happy with just amending the message as a friendly reminder.

**Comment by Qqwy** [comment]
I agree with @sunny-mittal on this. I find behaviour like Ruby, where it is explixitly stated when a private function is called. Although that is understandable there, with the way everything ought to be monkey patchable, I really think that that approach does not fit well in Elixir. 

Changing the error message to hint at the possibility of a private method seems a lot cleaner.
