### ISSUE TITLE
mix test command does not run only one test when line number provided

### ISSUE THREAD

**Issue by gaynetdinov** [elixir-lang/elixir#4406]
### Environment

* Elixir version (elixir -v): 1.2.3
* Operating system: OSX 10.11.3

### Current behavior

I have a fresh mix project where I created a simple module with 2 functions and a test for this module with scopes like this:
`lib/big_module.ex`
```elixir
defmodule TestApp.BigModule do
  def func_1 do
    "func_1"
  end

  def func_2 do
    "func_2"
  end
end
```

`test/big_module_test.exs`
```elixir
defmodule TestApp.BigModuleTest.Func1 do
  use ExUnit.Case

  test "func_1" do
    assert "func_1" == TestApp.BigModule.func_1
  end
end

defmodule TestApp.BigModuleTest.Func2 do
  use ExUnit.Case

  test "func_2" do
    assert "func_2" == TestApp.BigModule.func_2
  end
end
```

If I run this test file with specifying a line number like this:
```
$ mix test test/big_module_test.exs:12  
Including tags: [line: "12"]
Excluding tags: [:test]

..

Finished in 0.05 seconds (0.05s on load, 0.00s on tests)
2 tests, 0 failures

Randomized with seed 398921
```
I see that both test were executed. Line number 12 points to the line `test "func_2" do`. Interestingly that if I run the test command with line number 4 which points to the `test "func_1" do` everything works ok, one test got skipped:
```
$ mix test test/big_module_test.exs:4               
Including tags: [line: "4"]
Excluding tags: [:test]

.

Finished in 0.05 seconds (0.05s on load, 0.00s on tests)
2 tests, 0 failures, 1 skipped

Randomized with seed 437843
```
Also, if test file is not scoped with different modules, everything works as expected.

### Expected behavior

Only one test should be executed when I provide the line number of the test in the `mix test` command.

**Comment by lexmag** [comment]
Unfortunately we can't fix this today, it requires too invasive changes which isn't desired yet, this will be one of the things we would like to fix in the long term. It will be a won't fix for now. Sorry.

I've added a note about line filter for a file with multiple test cases: https://github.com/elixir-lang/elixir/commit/3f9ea587f30e77197ecefdd316d076e773b76c3a.
