### ISSUE TITLE
removed dependencies not removed from mix.lock

### ISSUE THREAD

**Issue by benoitc** [elixir-lang/elixir#4410]
### Environment

```sh
[hackney] elixir -v                                                                                               11:18:34  ☁  master ☂ ⚡
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

Elixir 1.2.3
hackney] uname -a                                                                                                11:20:14  ☁  master ☂ ⚡
Darwin Benoits-iMac.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64 i386 iMac15,1 Darwin
```

### Current behavior

removed a dependency from the list of des to fetch and that change is not reflected in `mix.lock`

### Expected behavior

having the removed dependency also removed from `mix.lock`

**Comment by josevalim** [comment]
That's on purpose because some projects have dependencies that are fetched only in certain environments. To clean up the lock, run `mix deps.unlock --unused` or some of the options. Thank you!
