### ISSUE TITLE
Improve error message when attempting to define a non-allowed infix operator

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#4411]
### Environment

* Elixir version (elixir -v): 1.2.3
* Operating system: Linux Mint 17.2

### Current behavior

I just attempted to define my own infix `...` operator. 
This did not work, as `...` is not in the allowed infix operator list.

However, the given compiler error was very confusing:

~~~
== Compilation error on file lib/sequences/ranges.ex ==
** (CompileError) lib/sequences/ranges.ex:6: cannot invoke local .../1 inside match
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
~~~

This is why I only understood what was happening after [asking about it on StackOverflow](http://stackoverflow.com/questions/36105943/elixir-operator-overloading-defining-an-exclusive-range-using-macros/36106510#36106510).

### Expected behavior

I think it would be a good idea to improve this error message.

**Comment by josevalim** [comment]
`...` is a valid identifier in Elixir. So when you write `def left ... right do`, it is the same as writing `def foo bar baz do` which is the same as `def foo(bar(baz)) do`. In other words, you would be calling `bar(baz)` inside a match (function arguments). So the message is correct, you just need to know `...` is an identifier and not an operator to make sense of it.

So suggestions for improving the error message are welcome but the background above is important. I don't believe we should special case `...` in the error message nor mention function definitions exclusively. Maybe we could show the full call, like `...(right)`, in addition to `.../1`. That must provide more visual clues.

**Comment by Qqwy** [comment]
Thank you for your reply. 

I indeed had the expectation that above error would happen for any non-permiitted two- or three-symbol infix operator, which is not the case (all others that I tested return a syntax error instead).


Because it is only this single case, it makes the problem a lot less important. 

It does seem like a good idea to me to show the full call, if possible.
