### ISSUE TITLE
Consider injecting binding discards for Logger when expanding

### ISSUE THREAD

**Issue by chrismccord** [elixir-lang/elixir#4417]
Unused variable warnings can be caused by a Logger macro call for a Logger level that is compiled out of the environment. For example, for the test/prod env, the following code block warns for unused `status`:

```elixir
def parse_response(%{status: status, body: body}) do
  Logger.debug "Got response with status #{status}"
  JSON.decode(body)
end
```

The only way to solve this yourself is to add a discard or if check:

```elixir
_ = status
Logger.debug "Got response with status #{status}"
# or
if status, do:  Logger.debug "Got response with status #{status}"
```

One solution would be to add in discards automatically when expanding logger macros that get compiled out of the program. Whether this is worth the complexity is up for discussion, but I've been bitten by this a few times so it's worth thinking about.

**Comment by whatyouhide** [comment]
Not sure about which solution is better here, but it's definitely a user experience problem IMO, so I'm :+1: on finding a solution.

**Comment by ericmj** [comment]
This can also produce warnings for unused private functions.

**Comment by whatyouhide** [comment]
I tried on of the solutions @chrismccord proposed for unused variables and it works pretty well: when a `Logger` call has to be pruned out of the AST, we just return `_ = var1; _ = var2; ...` for all the variables passed to the call.

@ericmj I think private functions are much more difficult (this would also affect unused imports btw). Do you have a solution in mind?

Also, do you think it's worth to only take care of variables (even if we can't cleanly take care of private functions/unused imports) or at that point we can just leave all the warnings?

**Comment by ericmj** [comment]
I think it's still worth it to handle the variable warnings. I just
mentioned other possible related issues, they should not stop us from
fixing the lower hanging fruit.

On Saturday, 26 March 2016, Andrea Leopardi <notifications@github.com>
wrote:

> I tried on of the solutions @chrismccord <https://github.com/chrismccord>
> proposed for unused variables and it works pretty well: when a Logger
> call has to be pruned out of the AST, we just return _ = var1; _ = var2;
> ... for all the variables passed to the call.
>
> @ericmj <https://github.com/ericmj> I think private functions are much
> more difficult (this would also affect unused imports btw). Do you have a
> solution in mind?
>
> Also, do you think it's worth to only take care of variables (even if we
> can't cleanly take care of private functions/unused imports) or at that
> point we can just leave all the warnings?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4417#issuecomment-201770974>
>


-- 
Eric Meadows-Jönsson

**Comment by whatyouhide** [comment]
@ericmj will open a PR for variables then :).

**Comment by whatyouhide** [comment]
We can keep this open for private functions and unused imports, but I don't think there's an easy solution for those; if others agree to that, we can close this :).
