### ISSUE TITLE
Evaluation of .exs script with large binary module attribute defined and referenced is very slow

### ISSUE THREAD

**Issue by tinglei8** [elixir-lang/elixir#4425]
### Environment

* Elixir version (elixir -v): Elixir 1.1.1
* Operating system: Mac OSX El Capitan 10.11.3

### Current behavior

Referencing large binary module attribute in elixir script is very slow. Creating and referencing the same binary in a function is normal.

test2.exs
```elixir
defmodule Test do

  @str_3B "123"
  @str_8B "12345678"
  @str_64B String.duplicate(@str_8B, 8)
  @str_64KB String.duplicate(@str_64B, 1024)
  @str_128KB String.duplicate(@str_64KB, 2)
  @str_149KB String.duplicate(@str_3B, 7 * 1024) <> @str_128KB
  @str_256KB String.duplicate(@str_64KB, 4)
  @str_1280KB String.duplicate(@str_256KB, 5)
  @str_5120KB String.duplicate(@str_1280KB, 4)

  def datum do
    @str_5120KB
  end

end

Test.datum
```

test3.exs
```elixir

defmodule Test do

  def datum do
    # write these in module body causes slow evaluation
    str_3B = "123"
    str_8B = "12345678"
    str_64B = String.duplicate(str_8B, 8)
    str_64KB = String.duplicate(str_64B, 1024)
    str_128KB = String.duplicate(str_64KB, 2)
    str_149KB = String.duplicate(str_3B, 7 * 1024) <> str_128KB
    str_256KB = String.duplicate(str_64KB, 4)
    str_1280KB = String.duplicate(str_256KB, 5)
    str_5120KB = String.duplicate(str_1280KB, 4)

    str_5120KB
  end

end

Test.datum
```

Run "time elixir test2.exs": 
real	0m20.113s
user	0m15.733s
sys	0m4.471s

Run "time elixir test3.exs": 
real	0m0.325s
user	0m0.275s
sys	0m0.121s

### Expected behavior

When reading the two codes, it's hard to imagine such a big difference in their executing times. Although I'm aware that .exs scripts have an extra overhead to be compiled before executed, I'm wondering if this particular use case can be optimized for .exs evaluations.

**Comment by josevalim** [comment]
I will see if we can optimize this use case but I am afraid the answer is rather not. The crux of the issue is that we need to transform this 5MB binary into AST and the AST will be really large, which will slow the whole compilation down. I will investigate and come back shortly.

**Comment by josevalim** [comment]
Confirmed, the compiler is already optimized to handle this case. Thanks for another well described issue :)
