### ISSUE TITLE
How about a String.to_list/1 function?

### ISSUE THREAD

**Issue by setzer777** [elixir-lang/elixir#4427]
I don't know if this is even relevant... but in my humble opinion this function will save us to transform the string into a char_list, and then transform it into an array of strings. I don't know if this makes some sense at all with Elixir philosophy, but it'd be really cool as module List already has `List.to_string/1`

Something like this: 
```elixir
iex(1)> string = "Hello"
"Hello World"
iex(2)> String.to_list(string)
["H", "e", "l", "l", "o"]
```

Greetings :)

**Comment by tuvistavie** [comment]
@setzer777 You are talking about something which would do

```
> String.to_list("foo")
["f", "o", "o"]
```

right?
If this is the case, we already have a way to do this with the `String` module:

```
String.split("foo", "", trim: true)
```

**Comment by setzer777** [comment]
Oh great! Then sorry for the suggestion :p I guess it's more than enough with that c: 
Thanks a lot!

**Comment by josevalim** [comment]
There is also String.codepoints and String.graphemes. Also, please don't use the issues to request or propose features, there is a mailing list for such discussions. Thank you.
