### ISSUE TITLE
Interpolated string map key causes compile error

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#4428]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.1
```

* Operating system:

OS X El Capitan

### Current behavior

``` iex
iex(1)> foo = "foo"
"foo"
iex(2)> %{ "#{foo}:1" => 3 }
** (CompileError) iex:2: illegal use of variable rewrite as map key inside match, maps can only match on existing variable by using ^rewrite
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

### Expected behavior

```
iex(1)> foo = "foo"
"foo"
iex(2)> %{ "#{foo}:1" => 3 }
%{ "foo:1" => 3 }
```

(Originally reported on the mailing list: https://groups.google.com/forum/#!topic/elixir-lang-core/_fYiUeVJwVE)

**Comment by felipesere** [comment]
How would one go about solving this? Is this part of the parser `elixir_parser.yrl`?

**Comment by tuvistavie** [comment]
@felipesere I think the issue is in the translator. An error in the parser would probably result in a `SyntaxError`.
