### ISSUE TITLE
Inconsistent behavior of map pattern matching with pin operator

### ISSUE THREAD

**Issue by tuvistavie** [elixir-lang/elixir#4429]
Hi,

When trying to pattern match on maps, I found the behavior of the pin operator inconsistent.
I would except the same result when using a literal map or a pinned value.

### Environment

* Elixir version (elixir -v): 1.2.3 and master
* Operating system: Linux 4.4.1-2-ARCH x86_64 GNU/Linux

### Current behavior

```elixir
iex(1)> foo = %{a: 1}      
%{a: 1}
iex(2)> bar = %{a: 1, b: 2}
%{a: 1, b: 2}
iex(3)> %{a: 1} = bar      
%{a: 1, b: 2}
iex(4)> ^foo = bar         
** (MatchError) no match of right hand side value: %{a: 1, b: 2}
```

### Expected behavior

```elixir
iex(4)> ^foo = bar         
%{a: 1, b: 2}
```

I am not sure if this is the intended behavior, a limitation or a bug, but I could
not find anything in the docs about this particular case.

Thanks!

**Comment by lexmag** [comment]
This is an expected behaviour, pin operator means that `foo` must be equal `bar`.
There were at leat 2 similar issues opened previously, I'll try to link them.

**Comment by tuvistavie** [comment]
Thanks for the quick reply and sorry for the inconvenience!
I will be very glad to take a look at the other issues if you can find them.

**Comment by lexmag** [comment]
Didn't manage to find relevant issues, but there is a whole discussion in mailing list exists:
https://groups.google.com/forum/?fromgroups#!searchin/elixir-lang-talk/pin/elixir-lang-talk/e6Ly4tWEEWM/k2reV-BPDQAJ.

**Comment by tuvistavie** [comment]
Great, thank you very much!
