### ISSUE TITLE
Replace String.lstrip/rstrip/ljust/rjust that works on code points on versions that works on graphemes

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4433]

**Comment by lpil** [comment]
Hi! From reading the title I presumed this this assertion would fail:

```elixir
assert String.lstrip("ééé abc ééé", ?é) == " abc ééé"
```
But it does not. What is an input in which the current implementation shows unwanted behaviour?

Thanks,
Louis

**Comment by josevalim** [comment]
@lpil the problem is the second argument. I want to propose versions where `String.lstrip("ééé abc ééé", "é")` is possible. Implementing this one in particular is quite straightforward today: 

```elixir
def lstrip(string, to_strip) do
  String.replace_leading(string, to_strip, "")
end
```

 Implementing the just versions are a bit more complicated.

**Comment by lpil** [comment]
I see, thanks!
