### ISSUE TITLE
Compiler error when trying to use an unquoted range as a guard clause in a generated function

### ISSUE THREAD

**Issue by campezzi** [elixir-lang/elixir#4466]
### Environment

* Elixir version (elixir -v): 1.2.3
* Operating system: Mac OS X El Capitan (10.11.3)

### Current behavior

Metaprogramming: compiler errors when trying to use an unquoted range as a guard clause in a generated function, even when using `Macro.escape` to get an AST representation of said range.

---
Code:
```elixir
defmodule SomeModule do
  range = 1..10
  def in_range(number) when number in unquote(range), do: true
  def in_range(_), do: false
end
```
Result:
`** (ArgumentError) invalid args for operator "in", it expects a compile time list or range on the right side when used in guard expressions, got: 1..10`

Same code as above, but using `unquote(Macro.escape(range))`:
`** (ArgumentError) invalid args for operator "in", it expects a compile time list or range on the right side when used in guard expressions, got: %{__struct__: Range, first: 1, last: 10}`

Same code as above, but using `unquote(Macro.escape(Macro.escape(range)))`:
`** (ArgumentError) invalid args for operator "in", it expects a compile time list or range on the right side when used in guard expressions, got: {:%{}, [], [__struct__: Range, first: 1, last: 10]}`

[This line](https://github.com/elixir-lang/elixir/blob/v1.2.4/lib/elixir/lib/kernel.ex#L2682) in `Elixir.Kernel.SpecialForms.left in right` suggests this last form form should have worked.

PS: the documentation for `Macro.escape` mentions escaping happens recursively until reaching the AST representation of the passed value - however, as seen above that didn't happen (the result of two nested `Macro.escape` calls was different from the one with a single call). Please let me know if you'd like me to open another issue for that.

### Expected behavior

Generated `in_range/1` function when compiling `SomeModule`.

**Comment by whatyouhide** [comment]
I'm looking into this.
