### ISSUE TITLE
Allow String.replace to replace multiple parts of a string with multiple values.

### ISSUE THREAD

**Issue by Maikon** [elixir-lang/elixir#4473]
This is a feature that I know [Ruby](http://ruby-doc.org/core-2.1.4/String.html#method-i-gsub) and [Clojure](https://clojuredocs.org/clojure.string/replace#example-542692d7c026201cdc327100) provide that is quite handy. I'm not aware of a way that this can be done in Elixir currently and I am keen to see what the community thinks about implementing something like this.

How would this look?

```
String.replace("abba", ~r/a|b/, %{"a" => "1", "b" => "2"})
=> "1221"
```
If there's interest in this, I have implemented a version which can be reviewed.

I would love to hear your thoughts :blush:

**Comment by josevalim** [comment]
Would your implementation also work when the second argument is a string?
If not, it should likely be added only to the regex module. Also, don't
forget to generally send proposals to elixir-Lang-core.

On Monday, April 4, 2016, Makis Otman <notifications@github.com> wrote:

> This is a feature that I know Ruby
> <http://ruby-doc.org/core-2.1.4/String.html#method-i-gsub> and Clojure
> <https://clojuredocs.org/clojure.string/replace#example-542692d7c026201cdc327100>
> provide that is quite handy. I'm not aware of a way that this can be done
> in Elixir currently and I am keen to see what the community thinks about
> implementing something like this.
>
> How would this look?
>
> String.replace("abba", ~r/a|b/, %{"a" => "1", "b" => "2"})
> => "1221"
>
> If there's interest in this, I have implemented a version which can be
> reviewed.
>
> I would love to hear your thoughts [image: :blush:]
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4473>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Maikon** [comment]
Ah apologies Jose, wasn't sure where to bring it up. I can move the discussion there if desired?

To answer your question, yes the implementation I have works when the second argument is a string so it behaves as it currently does.

**Comment by josevalim** [comment]
Please send a PR then. :) Let's discuss the implementation and move forward based on that. Thank you!

**Comment by rahul-bali** [comment]
Can I know how do you perform this in Elixir? Or where is this PR?

**Comment by FNickRU** [comment]
@rahul-bali #4474
