### ISSUE TITLE
Obscure error message when using with

### ISSUE THREAD

**Issue by mschae** [elixir-lang/elixir#4476]
### Environment

* Elixir version (elixir -v): 1.2.4
* Operating system: Mac OS X, 10.11.4

### Current behavior

Currently omitting arrows or equal signs in with clauses yields the following error:

Example:
```Elixir
with true,
do:  "Yep, it's true"
```

Error:
```
== Compilation error on file lib/error_msg.ex ==
** (FunctionClauseError) no function clause matching in :elixir_with.build_cases/2
    (elixir) src/elixir_with.erl:50: :elixir_with.build_cases([true], "Yep, it's true")
    (elixir) src/elixir_with.erl:46: :elixir_with.translate/3
```

### Expected behavior

Being spoiled by the high quality of other error messages in Elixir, I would've expected the error message to tell me what I am doing wrong and how I can fix it.

**Comment by whatyouhide** [comment]
I think this is fixed on master?

**Comment by mschae** [comment]
Might be, sorry if it is, didn't find a related issue.

**Comment by josevalim** [comment]
Fixed in master, just checked :)

**Comment by mschae** [comment]
Sorry about that...

**Comment by whatyouhide** [comment]
No worries @mschae, btw for reference I *think* it was fixed in https://github.com/elixir-lang/elixir/commit/92bbb10a. :)
