### ISSUE TITLE
GenServer.call/3 should raise a nice error message if you try to call yourself

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4479]
@fishcakez I think this would be really helpful but I am afraid of changing today's semantics. Thoughts?

**Comment by fishcakez** [comment]
Added in https://github.com/elixir-lang/elixir/commit/cc59462e968415f09be062bf64270c3a4a1518f3 and https://github.com/elixir-lang/elixir/commit/7f948540c63da74ad5e13bb87884eb4627371f0c
