### ISSUE TITLE
Elixir recompiles unchanged files under Vagrant with VirtualBox 'vboxsf' /vagrant mountpoint 

### ISSUE THREAD

**Issue by martin-langhoff** [elixir-lang/elixir#4490]
### Environment

* Elixir version (elixir -v): Elixir 1.2.3 (also v1.2.1 and 1.2.2)
* Operating system - guest: CentOS7 (guest) and CentOS6 (guest)
* Operating system - host: Fedora 21, 22, 23 (host), VirtualBox 4.0.x and tested up to 5.0.14

Similar behaviour observed on MacOS X hosts.

### Current behavior

Every `mix compile` acts as if all files needed recompilation. This seems to be related to source files being read from the `/vagrant` directory, which is a magic mountpoint, using `vboxsf` kernel drivers, which allows the VM to trivially read/edit files on the host.

We have validated clocks on VM and host, to ensure it is not related to file timestamp mismatches.

Tests of `/vagrant` vs placing on the VM root partition (using a bindmount if needed):

* `_build`, `deps` and source on `/vagrant` -- full recompile
* `_build`  and `deps` on root part, bindmounted , source on `/vagrant`  -- full recompile
* `_build`, `deps` and source on root partition -- only changed files recompile

### Expected behavior

* Only changed files (and their deps) recompile.

...

Hints for debugging this further welcome :-) which part of Elixir handles deciding whether to recompile?

**Comment by ericmj** [comment]
If you run `ls -l lib` and `ls -l _build/dev/lib/[APP]/ebin` are the source file and compile artifact mtimes what you would expect? Source files should be older than compile artifacts unless they were changed since the last compile.

**Comment by martin-langhoff** [comment]
After a build things look normal to me (see below), yet calling compile again will recompile everything.
```
# Find newest file under apps/web/lib
$ find apps/web/lib -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" " | xargs ls -l
-rw-rw-r--. 1 vagrant vagrant 4439 Apr  7 16:41 apps/web/lib/web/resource.ex
ls -l apps/web/lib _build/dev/lib/web/ebin/
apps/web/lib:
total 4
drwxrwxr-x. 1 vagrant vagrant  44 Apr  7 16:41 web
-rw-rw-r--. 1 vagrant vagrant 763 Apr  5 20:06 web.ex

_build/dev/lib/web/ebin/:
total 680
-rw-rw-r--. 1 vagrant vagrant  9600 Apr  8 13:12 Elixir.FOO.API.Resource.beam
... many beam files, all same timestamp ...
-rw-rw-r--. 1 vagrant vagrant  3860 Apr  8 13:12 Elixir.FOOWeb.UserSocket.Publishers.Users.beam
-rw-rw-r--. 1 vagrant vagrant  2848 Apr  8 13:12 Elixir.FOOWeb.Web.beam
-rw-rw-r--. 1 vagrant vagrant  1636 Apr  8 13:12 Elixir.FOOWeb.Web.Helpers.beam
-rw-rw-r--. 1 vagrant vagrant  3791 Apr  8 13:12 web.app

```

**Comment by martin-langhoff** [comment]
Any hint as to what code in Mix/Elixir I could/should instrument to gain some insight on this? Files are on different (and perhaps odd) mountpoints, so  checks might be returning unexpected values...

**Comment by ericmj** [comment]
`lib/mix/tasks/compile.elixir.ex` and `lib/mix/compilers/elixir.ex`. Notice the calls to `Mix.Utils.stale?/2` and `Mix.Utils.last_modified/1`.

**Comment by josevalim** [comment]
@martin-langhoff I would also inspect the .compile.* files that can be found inside _build/dev/lib/YOUR_APP as well as the mix.exs and mix.lock files. Here is the bulk of the code that does the checking: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/compile.elixir.ex#L63

**Comment by martin-langhoff** [comment]
Thanks! I'll look into instrumenting `Mix.Utils.stale?/2` and report back.

**Comment by martin-langhoff** [comment]
Apologies for the delay! Seems like I am getting closer. The `.compile.elixir` and `.compile.lock` files are the ones that end up with odd timestamps, leading to a full rebuild every time we call `mix compile`.

I don't fully understand how those work, guidance welcome.

How I instrumented Elixir compile:
```
[martin@tp-martin elixir]$ git diff
diff --git a/lib/mix/lib/mix/utils.ex b/lib/mix/lib/mix/utils.ex
index 8f3d483..915e992 100644
--- a/lib/mix/lib/mix/utils.ex
+++ b/lib/mix/lib/mix/utils.ex
@@ -82,7 +82,14 @@ defmodule Mix.Utils do
     modified_target = targets |> Enum.map(&last_modified(&1)) |> Enum.min

     Stream.filter(sources, fn(source) ->
-      last_modified(source) > modified_target
+      early_source = source
+      r = last_modified(source) > modified_target
+      if r do
+        IO.inspect(early_source)
+        IO.inspect(last_modified(source)) ## last_modified seems to change source
+        IO.inspect(modified_target)
+      end
+      r
     end)
   end
```

Lightly edited output

```
miyapp compile web
elixir --name web@iso.dev --erl -smp enable -S mix compile
==> config
Compiled lib/config/indicator.ex
"/vagrant/_build/dev/lib/config/.compile.elixir"
{{2016, 4, 12}, {22, 14, 49}}
{{2016, 4, 12}, {22, 14, 1}}
"/vagrant/_build/dev/lib/operational_data/.compile.lock"
{{2016, 4, 12}, {22, 14, 50}}
{{2016, 4, 12}, {22, 14, 5}}
==> operational_data
Compiled lib/operational_data.ex
(...)
"/vagrant/_build/dev/lib/operational_data/.compile.lock"
{{2016, 4, 12}, {22, 14, 50}}
{{2016, 4, 12}, {22, 14, 5}}
Generated operational_data app
"/vagrant/_build/dev/lib/web/.compile.lock"
{{2016, 4, 12}, {22, 14, 54}}
{{2016, 4, 12}, {22, 14, 35}}
==> web
Compiled lib/web.ex
(...)
Compiled web/views/error_helpers.ex
Compiled web/gettext.ex
Compiled web/web.ex
...

"/vagrant/_build/dev/lib/web/.compile.lock"
{{2016, 4, 12}, {22, 14, 54}}
{{2016, 4, 12}, {22, 14, 35}}
Generated web app
"/vagrant/_build/dev/lib/web/.compile.lock"
{{2016, 4, 12}, {22, 14, 54}}
{{2016, 4, 12}, {22, 14, 40}}
Consolidated Timex.Date.Convert
Consolidated Joken.Claims
Consolidated List.Chars
Consolidated Poison.Decoder
Consolidated Plug.Exception
Consolidated Phoenix.HTML.FormData
Consolidated Amnesia.Selection
Consolidated Phoenix.Param
Consolidated Phoenix.HTML.Safe
Consolidated String.Chars
Consolidated Collectable
Consolidated Enumerable
Consolidated JOSE.Poison.OrdEncoder
...

```

**Comment by martin-langhoff** [comment]
The prior patch didn't tell us what the targets where. Updated to

```
$ git diff
diff --git a/lib/mix/lib/mix/utils.ex b/lib/mix/lib/mix/utils.ex
index 8f3d483..d25e12b 100644
--- a/lib/mix/lib/mix/utils.ex
+++ b/lib/mix/lib/mix/utils.ex
@@ -82,7 +82,15 @@ defmodule Mix.Utils do
     modified_target = targets |> Enum.map(&last_modified(&1)) |> Enum.min

     Stream.filter(sources, fn(source) ->
-      last_modified(source) > modified_target
+      early_source = source
+      r = last_modified(source) > modified_target
+      if r do
+        IO.inspect(early_source)
+        IO.inspect(last_modified(source))
+        IO.inspect(targets)
+        IO.inspect(modified_target)
+      end
+      r
     end)
   end
```

We now get this output below, which makes me think that lib/config/indicator is a problem, it's full name is `apps/config/lib/config/indicator.ex` ; apps/config is an internal app that other apps depend on; if something in apps/config is rebuilt then everything follows.

Why is `apps/config/lib/config/indicator.ex` apparently bypassing stale checks?

```
elixir --name web@iso.dev --erl -smp enable -S mix compile
==> config
Compiled lib/config/indicator.ex
"/vagrant/_build/dev/lib/config/.compile.elixir"
{{2016, 4, 12}, {22, 41, 5}}
["/vagrant/_build/dev/lib/operational_data/.compile.lock"]
{{2016, 4, 12}, {22, 39, 55}}
"/vagrant/_build/dev/lib/operational_data/.compile.lock"
{{2016, 4, 12}, {22, 41, 6}}
["/vagrant/_build/dev/lib/operational_data/.compile.elixir"]
{{2016, 4, 12}, {22, 39, 59}}
==> operational_data
Compiled lib/operational_data.ex
...
"/vagrant/_build/dev/lib/operational_data/.compile.lock"
{{2016, 4, 12}, {22, 41, 6}}
["/vagrant/_build/dev/lib/operational_data/ebin/operational_data.app"]
{{2016, 4, 12}, {22, 39, 59}}
Generated operational_data app
"/vagrant/_build/dev/lib/web/.compile.lock"
{{2016, 4, 12}, {22, 41, 10}}
["/vagrant/_build/dev/lib/web/.compile.elixir"]
{{2016, 4, 12}, {22, 40, 30}}
==> web
Compiled lib/web.ex
...
Compiled web/views/layout_view.ex
"/vagrant/_build/dev/lib/web/.compile.lock"
{{2016, 4, 12}, {22, 41, 10}}
["/vagrant/_build/dev/lib/web/ebin/web.app"]
{{2016, 4, 12}, {22, 40, 30}}
Generated web app
"/vagrant/_build/dev/lib/web/.compile.lock"
{{2016, 4, 12}, {22, 41, 10}}
["/vagrant/_build/dev/consolidated/.compile.protocols"]
{{2016, 4, 12}, {22, 40, 36}}
Consolidated ...

```

**Comment by martin-langhoff** [comment]
`apps/config/lib/config/indicator.ex` is empty.

I suspect a similar problem could be triggered by a file made up of comments; or enough macros/conditionals that it generates no compiled output (can Elixir code do that? I new around here :-) ).

Perhaps we could / should?

* Issue a warning if a file compilation has created no output.
* Prune the empty-output file from the list of files/modules/deps built, so empty output of a file in a shared app (ie: apps-as-modules in an umbrella project) do not cascade into a full rebuild.

Looked a bit around `lib/elixir/lib/kernel/parallel_compiler.ex`, all the way down to `spawn_compilers/8` but lost track of the white rabbit around that point.

**Comment by josevalim** [comment]
>
> I suspect a similar problem could be triggered by a file made up of
> comments; or enough macros/conditionals that it generates no compiled
> output (can Elixir code do that? I new around here :-) ).
>
Yes, that could happen! Great find!

Please open up an issue, we can easily solve this issue now that we store
compiled files to an ETS table. :)

**Comment by josevalim** [comment]
Actually, no need to open up an issue. It has been fixed in master:

https://github.com/elixir-lang/elixir/commit/e3a04eca10e2c690512552e90a23ce88d0064742

And it has been backported to the v1.2 branch:

https://github.com/elixir-lang/elixir/commit/3798dff0fca55b2a486581257831e3830e770f72

I would love if you could give it a try. Thanks for investing and reporting
the bug, Elixir is better because of it. <3




*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by martin-langhoff** [comment]
Tested 3798dff -- works for me, skips pointless recompilation on empty file, yet triggers compilation on a valid updated file, tested in a large umbrella proj with app and module deps.

_Thank you_ for amazing maintainership, help debugging various random matters on irc, mailing list, github and for the 1.2 backport. Looking at the patch, it was a fairly involved job!

**Comment by josevalim** [comment]
Glad to help @martin-langhoff! If you are using umbrella projects, I would love your feedback here:

https://groups.google.com/forum/#!topic/elixir-lang-core/uhar5L5FNBU

It is a commit after the one you just tried which hopefully will make life for those using umbrellas easier. :)
