### ISSUE TITLE
IEx: Autocompletion doesn't work when `@moduledoc false` but functions are documented

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#4492]
_I'm still not sure whether it's the intented behaviour, or not..._

Take for example `Mix.Compilers.Elixir`, which is set to `@moduledoc false`.

When on iex, type the `h` command, and start typing, autocompletion will not work, only until i reach the module where this function is in (this case `h Mix.Compilers.Elixir.`<kbd>Tab</kbd>)

```iex
iex> h Mix.Compilers.Elixir.
clean/1                  compile/7                protocols_and_impls/1  
```

I think that if the docs are going to be available via IEx, they should be available via autocompletion as well.

**Comment by josevalim** [comment]
That's because mix is not a loaded application. IEx can only load modules from loaded applications. If you try to autocomplete it under `iex -S mix`, then it works. :)
