### ISSUE TITLE
Raise when redefining ExUnit test cases

### ISSUE THREAD

**Issue by stavro** [elixir-lang/elixir#4493]
### Raise when redefining ExUnit test cases
Elixir: 1.2.0

I've been bitten by this multiple times through copy/pasting test cases, where two test cases end up with the same name.  Especially since I'm not aware of any context blocks, or ways of grouping tests cases under a nested structure (a la RSpec's `context` block).

```elixir
defmodule TestTest do
  use ExUnit.Case
  doctest Test

  test "the truth" do
    assert 1 + 1 == 2
  end

  test "the truth" do
    assert 1 + 1 == 3 # SHOULD FAIL
  end
end
```

When running the suite, there is a **warning** reported, but the second test never runs, and the exit code doesn't reflect the true result of the test.

The result of a test run is:
```
$ mix test
test/test_test.exs:9: warning: this clause cannot match because a previous clause at line 5 always matches
.

Finished in 0.08 seconds (0.08s on load, 0.00s on tests)
1 test, 0 failures

Randomized with seed 633981

$ echo $?
0
```

This is confusing because *I am not intentionally defining any functions*, so it isn't obvious that tests must be uniquely named. Since the test suite often runs in CI, the output of the test itself is often not easily visible.

Since we are using a macro to define test cases, it would be prudent to raise an error upon definition of a second test case with the same name, rather than softly reporting warnings. 

I know there is an option to treat warnings as errors, but I really think it should be the default for an implicitly defined function like this.

**Comment by josevalim** [comment]
We had this discussion when we added the warning. The thing is that tests are functions (maybe we should make it clearer) and we can see that in examples like:

    test "foo", %{foo: foo} do

If there is no foo key, it will fail.

Furthermore, most of the warnings you may get in your test suite may indicate you are not testing what you were supposed to. This is definitely just one of them (same for your code!).

So for now, we will keep this as is and wait for more feedback. If others continue to feel this as not helpful, let's revisit it. Thank you for the report!  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
