### ISSUE TITLE
Umbrella project enforce path name as application name

### ISSUE THREAD

**Issue by papylhomme** [elixir-lang/elixir#4499]
Hello,

I'm using an umbrella project where application names are different from their directory names. No technical reason, nor any technical problem either, it's more of a nomenclature thing: Umbrella project is called _habitat_ with 2 subdirectories _core_ and _web_, where application are named respectively _habitat_core_ and _habitat_web_ to avoid an eventual clashing of application names.

Running the apps directly from their directory is not a problem, even when one depend on the other (using both ```in_umbrella: true``` and ```path: "../core"``` in the dependency), but from the umbrella directory it doesn't work.

It seems the code responsible for this behavior is located solely in ```Mix.Dep.Umbrella```:

```elixir

  def loaded do
    #...
    Path.wildcard(Path.join(apps_path, "*/mix.exs")) |> Enum.map(&Path.dirname/1)
    |> extract_umbrella
    #...
  end

  defp extract_umbrella(paths) do
    for path <- paths do
      app = path |> Path.basename |> String.downcase |> String.to_atom
      {app, path}
    end
  end
```

Would it be acceptable to extract the application name from the mix file instead of the directory name ? I'm willing to give it a try if it seems reasonable enough

**Comment by michalmuskala** [comment]
I believe I was complaining about the exactly same thing. It seems the main issue is that the `mix.exs` is loaded further down the road and is not available at that point.

I proposed I would be perfectly fine with specifying the name/path in the umbrella's `mix.exs` config:

```elixir
def project do
  [apps_path: "apps",
   apps: [my_app_foo: "apps/foo",
          my_app_bar: "apps/bar"]]
end
```
I'm not sure though how ward would it be to implement something like that.

**Comment by josevalim** [comment]
Can we please move this discussion to the mailing list? I think we need to put some more visibility into it and the elixir-lang-core mailing list is a perfect place to do that. Other than that, @michalmuskala  solution would be fine and is relatively straight-forward to implement.

Thank you!

**Comment by mrinalwadhwa** [comment]
I would like to setup similar to what @papylhomme originally requested. @michalmuskala's solution would be great.

Was this discussed further on the mailing list? Can't find a thread.
