### ISSUE TITLE
[question] mix hex.info error

### ISSUE THREAD

**Issue by HaFoLuoKe** [elixir-lang/elixir#4500]
My OS is MacOS . I got a elixir project from github
under the project folder, run make 
```
myMacBook-Air:cog-master my$ make
iex -S mix phoenix.server
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

** (Mix) Failed to open Hex registry (file does not exist, run `mix hex.info` to fetch it)
```

then I run mix hex.info, I got the response:

```
Hex:    0.11.5
Elixir: 1.2.4
OTP:    18.3

Built with: Elixir 1.2.3 and OTP 18.3.1

Registry update failed (http_error)
{:failed_connect, [{:to_address, {'hexpmrepo.global.ssl.fastly.net', 443}}, {:inet, [:inet], :closed}]}
** (Mix) Failed to fetch registry
```

please teach me how to fix it. I've trying for few days. 
thanks very much

**Comment by josevalim** [comment]
@HaFoLuoKe where are you based? Maybe there are proxies or timeouts blocking your access?

/cc @ericmj

**Comment by ericmj** [comment]
It's usually a proxy issue if you consistently get connection errors. If you use a proxy make sure it's set up correctly and that you have set the environment variables for it.

**Comment by josevalim** [comment]
@ericmj do you have a link or a command we can run to get information on the proxy configuration?

**Comment by ericmj** [comment]
@josevalim I don't, maybe we should print this when set `MIX_DEBUG=1` is set?

**Comment by josevalim** [comment]
Why wouldn't we print it always that fetch the registry fail? We could say:

Registry update failed (http_error). This may happen if you don't have internet connection or if you are behind a proxy that may intercept external connections. Please run `mix help hex.config` for more information on using mirrors or setting up proxies.

Thoughts?

**Comment by ericmj** [comment]
@josevalim I misunderstod you, I thought you meant a command printing the configuration. But you meant guiding the user to documentation for the configuration?

**Comment by josevalim** [comment]
Yes, the latter. We get those reports frequently. :)

On Saturday, April 9, 2016, Eric Meadows-Jönsson <notifications@github.com>
wrote:

> @josevalim <https://github.com/josevalim> I misunderstod you, I thought
> you meant a command printing the configuration. But you meant guiding the
> user to documentation for the configuration?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4500#issuecomment-207758375>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by HaFoLuoKe** [comment]
Thanks for your responses。I am in china。atcually, I access internet through proxy because we have 'great fire wall'。Now I closed my proxy, But I also cannot run the command。I think a way to check the connectivity, or a package to let we can install the components locally will be helpful。
Thanks for the responses again。

**Comment by josevalim** [comment]
@ericmj should we move this to hex?

**Comment by ericmj** [comment]
Yeah.

**Comment by Lispre** [comment]
I meet this problem either.
