### ISSUE TITLE
Reenable documentation for Kernel.Typespec?

### ISSUE THREAD

**Issue by aaronjensen** [elixir-lang/elixir#4506]
The documentation for `Kernel.Typespec` was disabled here https://github.com/elixir-lang/elixir/commit/f1d4d5b034bd47d6488b808766f25a3f6fd82683, but it still has some useful functions such as `beam_types/1` https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/typespec.ex#L226

Is there a reason these are "undocumented"?

**Comment by Troush** [comment]
There is still documentation for ```Kernel.Typespec```. https://github.com/elixir-lang/elixir/commit/f1d4d5b034bd47d6488b808766f25a3f6fd82683 moved only "How to" to docs pages. But function documentation still there. See https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/typespec.ex#L226

**Comment by josevalim** [comment]
We are considering making those private in the long term. Feel free to use them at your own risk, we likely won't change anything before Elixir 2.0 anyway because they were public at some point during 1.x.

**Comment by aaronjensen** [comment]
@Troush when [`@moduledoc false` is set](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/typespec.ex#L2), the docs don't actually get generated. 

@josevalim fwiw [this](https://groups.google.com/forum/#!topic/elixir-lang-talk/gI8sGkfmObc) was my reason for using `beam_types/1`. We're using it for now in this way (to fill the atom table with atoms used in structs' typespecs prior to a recursive `String.to_existing_atom/1` application on the keys of a struct.

Understood re: "at your own risk", we may come up w/ a better solution later, but this plugs the hole for now. If you have any other suggestions, please do chime in on the thread. Thanks much!
