### ISSUE TITLE
Restart applications when running recursive tasks

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#4509]
### Environment

Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.2.3

### Current behavior

When a recursive task, such as `mix test` is running, all the applications in the umbrella are started only once at the beginning and are kept running while the task recurses.

This makes it impossible to call tasks that expect the app not to be running, for example aliasing test to recreate the database before actually running tests.

### Expected behavior

I'd expect running a recursive task to be equivalent to going into the subdirectory of each application and running the task there. This means all applications should be stopped after running a task in one application and before running it again for the next application.

### Workaround

It's possible to get it to work currently by aliasing the problematic task and calling `Application.stop/1` and `Application.ensure_all_started/1` explicitly. For example:
```elixir
test: [fn _ -> Application.stop(my_app) end,
       "ecto.drop", "ecto.create", "ecto.migrate",
       fn -> Application.ensure_all_started(my_app) end,
       "test"]
```

**Comment by josevalim** [comment]
@michalmuskala I am not sure this is something we should do. Maybe you should run it with `--no-start` and eventually start when you want to?

**Comment by michalmuskala** [comment]
The biggest problem for me is that it's completely inconsistent - it works for the first app, but fails for the next one.

I also don't think we should keep things between runs - this may create situations where `mix test` works for each app independently, but fails when running from umbrella. 

I always considered recursive task to be somewhat equivalent to running:
```bash
for app in apps/*; do
  (cd $app && mix task)
done
```

**Comment by josevalim** [comment]
Well, it isn't equivalent to that because the state will be carried around. Can we talk about your particular issue? Which state is being carried over?

**Comment by michalmuskala** [comment]
Let me explain the full issue:

With ecto 1.1 I could reset the database for tests in `test_helper.ex`. That method unfortunately does not with with 2.0, because by the time we get to the `test_helper.ex` the connections are already established. Alternative solution, that is advised, is to setup a mix alias for test that will reset the database. This works perfectly with normal application or in umbrella with just one app. Unfortunately it breaks down again when we have 2 applications with repositories we're trying to reset - the first one will work perfectly fine, but the second one will fail, because by the time we run the task alias, the connections are established (from the runs of previous applications).

**Comment by josevalim** [comment]
Let's solve this in Ecto. :)

**Comment by ericmj** [comment]
@josevalim Why shouldn't we test individual umbrella children in isolation? State from one test run can affect the tests of another app.

**Comment by dokie** [comment]
I too am hitting this issue in upgrading from 1.1.1 to 1.2.5 as my individual umbrella apps all pass their tests with `mix espec` when in the umbrella app dir but the second app fails when `mix espec` is run from the upper umbrella app. I'm going to continue to see what I can determine that I can do to fix it but any help would be welcomed too.
