### ISSUE TITLE
GenServer should give a warning, if init/0 callback is defined instead of init/1

### ISSUE THREAD

**Issue by miwee** [elixir-lang/elixir#4511]
In this case callback init routine not required any args, I mistakeny defined a init/0 function. Since use GenServer, injects a default init/1 function, in case init/1 is not defined by callback module. So I thought I've defined init callback but it was not used at all. Genserver was using default init/1 function. 

It took a while to figure out that I needed to define init, with args as input, even if args was not to be used. (http://elixir-lang.org/docs/stable/elixir/GenServer.html#c:init/1)

I think a compiler warning for GenServer callbacks, in case of a init/0 function (and no init/1 function) is most likely case of mistaken assumption. A gentle reminder should be valuable to the developer.

**Comment by fishcakez** [comment]
It is very easy to make an error in the arity of a callback when using `use GenServer`. An alternative is to `@behaviour GenServer` and define all callbacks by hand. I guess `handle_call/2` (missing `from`) and `handle_cast/3` (including `from`) might be other common ones. I am concerned about false positives though.

**Comment by josevalim** [comment]
Yes, there is nothing we can do. Someone may as well have defined `init/0` on purpose.

**Comment by TBK145** [comment]
Isn't it possible to define `init/1` as `def init(args \\ []) do`?
