### ISSUE TITLE
Function clause when setting param `@impl` with env defined with config/2

### ISSUE THREAD

**Issue by kzemek** [elixir-lang/elixir#4519]
### Environment

* Elixir version (elixir -v): Elixir 1.2.4
* Operating system: OS X 10.11.5 Beta

### Current behavior

Having compile-time configs defined as follows:

```elixir
# config.exs
use Mix.Config
config :repro, config2key: :value
config :repro, :config3key, key: :value
```

and a module that sets param `@impl` that fetches the configuration:

```elixir
defmodule Repro, do: @impl Application.get_env(:repro, :config2key)
```

the compilation fails with:

```
** (FunctionClauseError) no function clause matching in Access.fetch/2
    (elixir) lib/access.ex:117: Access.fetch(:value, :protocol)
    (elixir) lib/access.ex:149: Access.get/3
    (mix) lib/mix/compilers/elixir.ex:150: Mix.Compilers.Elixir.detect_kind/1
    (mix) lib/mix/compilers/elixir.ex:140: Mix.Compilers.Elixir.each_module/6
    (elixir) lib/kernel/parallel_compiler.ex:146: Kernel.ParallelCompiler.wait_for_messages/8
    (elixir) lib/kernel/parallel_compiler.ex:55: Kernel.ParallelCompiler.spawn_compilers/3
    (mix) lib/mix/compilers/elixir.ex:107: Mix.Compilers.Elixir.compile_manifest/5
    (mix) lib/mix/compilers/elixir.ex:54: Mix.Compilers.Elixir.compile/7
```

When initializing `@impl` using `:config3key`:

```elixir
defmodule Repro, do: @impl Application.get_env(:repro, :config3key)
```

the compilation completes successfuly and `@impl` contains the config.

### Expected behavior

Neither definition of `Repro` fails to compile or a meaningful (to the user) error is displayed.

**Comment by tuvistavie** [comment]
The `@impl` attribute is used internally for protocols implementation, and the compilers tries to retrieve the `protocol` from it,
which is why it fails here, as obviously `:value[:protocol]` will not work.

It is simple enough to add a a meaningful error message, but I wonder if we should not
use `:__impl__` internally to avoid cases like this.
