### ISSUE TITLE
Support for Erlangs  #rec{_ = '_' } and for record_info/2

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#4522]
There is no way to set a record to be created with default fields.  

ETS and  Mnesia select/match functions rely on records with all fields set to '_' to work.

In Erlang shell this can be done by:
```
erl> rd(test, {field1, field2}).
test
erl> #test{_= '_'}.
#test{field1 = '_',field2 = '_'}
```
My proposal is to allow MyRecords.test(\_: :\_) to set for example :\_ to every value, or something like, MyRecords.test() |> Record.default(:\_).  The former in a one-liner is better as the expression is used often for example in Erlang:
```
mnesia:dirty_match_object(#test{field1=<<"Username">>, _='_'}).
```
Writing MyRecords.test() |> Record.default(:\_), each time you want a default record will be cumbersome and useless.

The second issue is for Mnesia to create a table from a record you need to pass it the record attributes. You can get this using record_info/2.
```
erl> record_info(fields, test).
[field1,field2]
```
Currently the only way to do this in Elixir thanks to ericmj is:
```
iex> MyRecords.test() |> MyRecords.test() |> Keyword.keys
```
This is cumbersome and not intuitive.  Not documented anywhere.

I propose to have Record.record_info/2.

It should be noted that record_info is a macro.  

This is needed to have much cleaner compatibly with ETS and Mnesia.

**Comment by whatyouhide** [comment]
Hey there @vans163! Elixir's issue tracker is reserved for bugs in Elixir. Proposals of new features should be directed at the [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core) mailing list, where the community can discuss such features. Thanks! :heart_decoration:

**Comment by vans163** [comment]
josevalim told me on irc I could just open an pull request or an issue, I assumed he meant github.  Also that mailing list is behind a google user wall.

**Comment by whatyouhide** [comment]
Well if @josevalim vouched for this then by all means, an issue is fine :) The mailing list is behind the Google wall, but sadly that's how it is for now :disappointed:

**Comment by josevalim** [comment]
You can subscribe to the mailing list without a Google account but they hide it the best they can. If you want to, please try this address: https://groups.google.com/forum/#!forum/elixir-lang-core/join

**Comment by vans163** [comment]
Yea it seem I can join it eventually but to make new topic it wants a google account. Anyways just close this if its wrong place.

**Comment by josevalim** [comment]
> Yea it seem I can join it eventually but to make new topic it wants a google account.

Ouch, sorry to hear about that.

>  Anyways just close this if its wrong place.

No, this is correct place as we already validated this on IRC. :)

**Comment by vans163** [comment]
Started a pull.  
https://github.com/elixir-lang/elixir/pull/4523
