### ISSUE TITLE
If special form do not eval 'true' clause when first argument is false.

### ISSUE THREAD

**Issue by daewon** [elixir-lang/elixir#4524]
### Environment

* Elixir version (elixir -v): 1.2.4
* Operating system: MacOS 10.11.4

### Current behavior
If special form do not eval 'true' clause when first argument is false.
but, below expression raise error

expression
```
if false, do: raise "do not eval ':true clause'", else: true
```

stack trace
```
iex(15)> if false, do: raise "do not eval ':true clause'", else: true
** (CompileError) iex:15: invalid call "do not eval ':true clause'".exception() else
  true
end
    (elixir) expanding macro: Kernel.raise/2
             iex:15: (file)
    (elixir) expanding macro: Kernel.if/2
             iex:15: (file)

```

### Expected behavior
No compile error.

It should works like below code.(it works, with no error)
```if true, do: true, else: raise "do not eval :false clause"```

**Comment by tuvistavie** [comment]
The problem is easy to understand if you check the AST produced by your code.

```elixir
IO.puts Macro.to_string(quote do: if false, do: raise "do not eval ':true clause'", else: true)
# gives
if(false) do
  raise("do not eval ':true clause'") else
    true
  end
end
```

which indeed does not mean anything.

So you must add parenthesis to your `raise` call to fix this.

```elixir
if false, do: raise("do not eval ':true clause'"), else: true
```

**Comment by josevalim** [comment]
Thanks you @tuvistavie! Since there is a bug in Macro.to_string above, I will keep this open until it is fixed. :)

**Comment by tuvistavie** [comment]
@josevalim I would be glad to give it a try.
Should the correct output look something like this:

```elixir
if(false) do
  raise("do not eval ':true clause'", [else: true])
end
```

**Comment by josevalim** [comment]
Yes. We should not use the block format if there is no "do" keyword.

**Comment by tuvistavie** [comment]
Ok, I am going to take a look.
It seems we have the same problem with `catch`, `after` and `rescue`.
