### ISSUE TITLE
Observer with Mnesia tables does not allow editing/deleting records.

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#4528]
### Environment
Elixir 1.2.3

### Current behavior
With mnesia started and with at least one table present, using observer to inspect the table and edit or deleting a record fails with:
```
Could not edit object: node or table is not available
```

### Expected behavior
The record is edited/deleted.

**Comment by edgurgel** [comment]
Observer is not part of Elixir but erlang: https://github.com/erlang/otp#bug-reports

**Comment by vans163** [comment]
Yea but its a bug when used with elixir. Works fine with the same mnesia database running from Erlang.

**Comment by edgurgel** [comment]
Sweet then :+1:

**Comment by ericmj** [comment]
> Yea but its a bug when running Elixir. Works fine with the same mnesia database running from Erlang.

What do you mean running from Elixir? What part of mnesia or observer is affected by Elixir?

**Comment by vans163** [comment]
To workaround not yet having #Rec{_=> '_'} in Elixir I set the records default values to _, but apparently this is a reserved value and Mnesia cannot store values with '_' in them.
