### ISSUE TITLE
whether it is possible to add a function String.decapitalize?

### ISSUE THREAD

**Issue by anronin** [elixir-lang/elixir#4537]
Hi! It's not an issue but the question. 
Do you need such a function in the standard library? 

`String.decapitalize` when you need to convert to lowercase a first letter in the word. Maybe it's not the most desired feature but sometimes it can be useful and i can try to implement it, but I'm not very good at programming)

**Comment by nubunto** [comment]
A "decapitalized" string is just a full downcased string, if you think about it. So, if you want to "decapitalize" you can always:

     capitalized = String.capitalize("striNG!")
     decapitalized = String.downcase(capitalized)
     IO.puts decapitalized # puts "string!"

**Comment by anronin** [comment]
not quite, I mean this `String.decapitalize("UpperCaseString") => "upperCaseString"`

**Comment by whatyouhide** [comment]
Hey @anronin Elixir's issue tracker is reserved for bugs and issues with Elixir. The [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core) mailing list is where feature proposals should be posted so that the community can discuss them :) Thanks!

**Comment by anronin** [comment]
my bad, thanks @whatyouhide, will post to elixir-lang-core mailing list
