### ISSUE TITLE
Missing esl-erlang and elixir packages under Ubuntu 16.04

### ISSUE THREAD

**Issue by samuelebistoletti** [elixir-lang/elixir#4544]
Erlang and elixir packages aren't available on repository for Ubuntu 16.04 Xenial.
404 Not found is returned after installing erlang-solutions package on system and trying apt-get update.

**Comment by Troush** [comment]
Hey, @samuelebistoletti 
Elixir issues are for elixir related bugs.

Ask for package in ubuntu community or get in touch with maintainers of previous ubuntu packages or make one by your self :)

**Comment by ericmj** [comment]
Please contact Erlang Solutions (if it's their packages you are using). The Elixir team does not maintain those packages.
