### ISSUE TITLE
Document OTP behaviours

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#4546]
Elixir declares callbacks of `GenServer` and `GenEvent` even though the underlying code is using `@behaviour :gen_server` or `:gen_event`. I see this mainly as documentation effort. 

We should document `Application` and `Supervisor`'s callbacks in a similar fashion. Today one has to do to the erlang docs to find it properly described.

A thing to consider is if we should keep `@behaviour :gen_server` or switch to `GenServer`.

\cc @josevalim @fishcakez

**Comment by josevalim** [comment]
Yes, we should definitely do this except for GenEvent (which will eventually be removed anyway).
