### ISSUE TITLE
Compile error with capture and cons

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#4553]
### Environment

The error exists in both 1.2.4 and master.

### Current behavior

```elixir
iex(1)> [&IO.puts/1 | []]
** (CompileError) iex:1: invalid args for &, expected an expression in the format of &Mod.fun/arity, &local/arity or a capture containing at least one argument as &1, got: IO.puts() / 1 | []
```

### Expected behavior

```elixir
iex(1)> [&IO.puts/1 | []]
[&IO.puts/1]
```

**Comment by whatyouhide** [comment]
The problem should be that `[&IO.puts/1 | []]` is quoted incorrectly:

```elixir
iex> quote do: [&IO.puts/1 | []]
[{:&, [],
  [{:|, [],
    [{:/, [context: Elixir, import: Kernel],
      [{{:., [], [{:__aliases__, [alias: false], [:IO]}, :puts]}, [], []}, 1]},
     []]}]}]
```

So `&` takes precedence over `|`. Likely, the correct quoted AST would be the one returned if we put the capture in parens:

```elixir
iex(2)> quote do: [(&IO.puts/1) | []]
[{:|, [],
  [{:&, [],
    [{:/, [context: Elixir, import: Kernel],
      [{{:., [], [{:__aliases__, [alias: false], [:IO]}, :puts]}, [], []},
       1]}]}, []]}]
```

**Comment by michalmuskala** [comment]
Yeah, I suspected this might be a precedence issue.

I'd say though that this still is a bug. The capture is a whole value, no matter the context, so I should be able to write it as such without wrapping in parens.

**Comment by whatyouhide** [comment]
@michalmuskala definitely a bug, yes. `&` should likely have higher precedence over most other things. I'll have a look into this in the morning if no one's already working on it.

**Comment by josevalim** [comment]
I am almost 100% sure we can't fix this. & has lower precedence than
operators, so & &1+&2 works. Maybe we can make operators with lower
precedence to not be included in this list but it would be a special case
and hard to make it work in the parser.

On Monday, April 25, 2016, Andrea Leopardi <notifications@github.com> wrote:

> @michalmuskala <https://github.com/michalmuskala> definitely a bug, yes. &
> should likely have higher precedence over most other things. I'll have a
> look into this in the morning if no one's already working on it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4553#issuecomment-214047053>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by whatyouhide** [comment]
@josevalim ah, this is nasty. Maybe a quick solution would be to extend the error message a bit so that

> invalid args for &, expected an expression in the format of &Mod.fun/arity, &local/arity or a capture containing at least one argument as &1

mentions something like "this error may be caused because `&` has lower precedence than other operators (such as `|`)" or similar.

**Comment by josevalim** [comment]
@whatyouhide I am not sure what we can do here in regards to the error message. This is just an example of where the precedence is wrong and I am sure there are many more. :(

**Comment by whatyouhide** [comment]
Yeah, that's why I showed an error message that's kind of generic ("[...] than other operators [...]"). Still not too useful probably :(
