### ISSUE TITLE
MapSet-like entities are not handled gracefully

### ISSUE THREAD

**Issue by jisaacstone** [elixir-lang/elixir#4555]
I was messing around with MapSets and did something no sane person would do.

```elixir
iex> m2 = %{:ok => :go, "ok" => "go", 'ok' => 'go'}
iex> m2ms = Map.put(m2, :__struct__, MapSet)
%Inspect.Error{message: "got FunctionClauseError with message \"no function clause matching in MapSet.to_list/1\" while inspecting %{:__struct__ => MapSet, :ok => :go, 'ok' => 'go', \"ok\" => \"go\"}"}
```
iex does not know what to do with this thing.

```elixir
iex> %MapSet{} = m2ms
%Inspect.Error{message: "got FunctionClauseError with message \"no function clause matching in MapSet.to_list/1\" while inspecting %{:__struct__ => MapSet, :ok => :go, 'ok' => 'go', \"ok\" => \"go\"}"}
```
Yes this should fail, but it ought to fail with a `MatchError`, not a `FunctionClauseError`

---------------------

So, I can fix these issues. But before I do, is it even worth fixing? I mean I really hope no one ever uses anything like `Map.put(m2, :__struct__, MapSet)` in production code...

**Comment by ericmj** [comment]
To me it looks like everything is working as expected.

When you do `%MapSet{} = m2ms` only the `__struct__` key is matched, the match is successful and then we crash when printing `m2ms` because it's an invalid `MapSet` struct.

**Comment by josevalim** [comment]
You should never do this:

```elixir
m2ms = Map.put(m2, :__struct__, MapSet)
```

There is no guarantee you are actually respecting the structured defined by MapSet. Use one of the functions in `MapSet` or generally `struct/2`  or `struct!/2`. If you mess up the internal representation of `MapSet`, it is expected many functions won't work.
