### ISSUE TITLE
Keyword lists with module keywords bug?

### ISSUE THREAD

**Issue by jordan0day** [elixir-lang/elixir#4561]
I believe this may be related to issue #3113 and PR #3127

In 1.2, I'm seeing some behavior that seems a little off when using module names as the keys for a keyword list:

```Elixir
iex(32)> kwl1 = [SomeModule: 1]
[SomeModule: 1]
iex(33)> kwl2 = [{SomeModule, 1}]
[{SomeModule, 1}]
iex(34)> Keyword.keyword?(kwl1)
true
iex(35)> Keyword.keyword?(kwl2)
true
iex(36)> kw11 == kwl2
false
```
Compare that to the behavior when a non-module atom is used:
```Elixir
iex(37)> kwl3 = [some_atom: 1]
[some_atom: 1]
iex(38)> kwl4 = [{:some_atom, 1}]
[some_atom: 1]
iex(39)> kwl3 == kwl4
true
```

It appears that when the `[SomeModule: 1]` style is used, the quoted atom `:'SomeModule'` is used as the key, and not the module name atom:

```Elixir
iex(40)> List.first(kwl1)
{:SomeModule, 1}

iex(41)> List.first(kwl2)
{SomeModule, 1}
```

I tried digging around in the Elixir source for a bit to see if there was an obvious fix for this, but unfortunately my Erlang abilities are rather lacking. Adding an entry to `kw_test()` in `test/erlang/tokenizer_test.erl` like
```Erlang
[{kw_identifier, {1, 1, 3}, 'A'}] = tokenize("A: "),
```
passes, but it seems like `tokenize` would have to return a bit more info to let to parser know that it 'A' should be a regular module atom and not a quoted atom.

On the flip side, however,
```Elixir
iex(14)> [is_atom: 1] == ['is_atom': 1]
true
```
So maybe this is just an unfortunate quirk of the module-names-are-atoms-without-colons thing?

**Comment by whatyouhide** [comment]
What you're seeing happens because `SomeModule != :SomeModule`:

```elixir
iex> SomeModule == :SomeModule
false
iex> SomeModule == :"Elixir.SomeModule"
true
```

Just to add information to this, not sure how we should behave in this case.

**Comment by ericmj** [comment]
What @whatyouhide said.

`[foo: 1]` and `[Foo: 1]` are sugar for `[{:foo, 1}]` and `[{:Foo, 1}]` respectively. `Foo != :Foo` hence the the equality check fails.

**Comment by jordan0day** [comment]
Should `Foo != :Foo` actually be considered part of the language specification (informal or otherwise), or just a side effect of the implementation?.

Since the `atom: value` sugar is used all over the place for keywords and maps, it seems surprising that there's a class of atoms for which it doesn't work.

A use case where it'd be nice to be able to use module names with the keyword/map sugar is configuration:
```Elixir
config :my_app, :num_workers,
  ImportantServer: 10,
  NotImportantServer: 1
```

**Comment by ericmj** [comment]
> Should Foo != :Foo actually be considered part of the language specification (informal or otherwise), or just a side effect of the implementation?

Yes, it's definitely a defined part of the language, it's not a side-effect of something else. Atoms and module aliases are different.

> Since the atom: value sugar is used all over the place for keywords and maps, it seems surprising that there's a class of atoms for which it doesn't work.

What do you mean it doesn't work? It definitely does work for capitalized atoms, but they are not aliases.

**Comment by jordan0day** [comment]
Ah, yes, I am conflating atom aliases with atoms.

**Comment by vadim-moz** [comment]
I would put question differently: should `x = [Foo: 12]` be interpreted as `[{:Foo, 12}]` or `[{Foo, 12}]`? Given that in the next `x[Foo]` it would be interpreted differently, it causes confusion. 

\<sight\>Eternal problem with implicit rules\</sight\>

**Comment by ericmj** [comment]
I don't think so since `["foo": 123] != [{"foo", 123}]`.

The rules are pretty straightforward, for keyword lists just move the colon from the right hand side to the left hand side.

**Comment by josevalim** [comment]
Think about it this way: if `[Foo: 12]` would be the same as `[{Foo, 12}]` then I would expect `[foo: 12]` to be the same as `[{foo, 12}]`, which does not make much sense. It always returns atoms.

**Comment by vadim-moz** [comment]
It is not exactly like this: for example `IO.puts "#{Foo}"` and `IO.puts "#{:foo}"` are different. So upper-case _identifiers_ (for lack of better term) behave differently in the language than low-case one. 

(Ok, `IO.puts "#{:Foo}"` behaves exactly like `IO.puts "#{:foo}"`. My point is unqualified `foo` is not an item, and `Foo` is. So, 'colonizing' is not exactly necessary -- keying could behave quite like `List.wrap`. I could expect them to behave differently in key context. I can expect anything, although -- it does not make it any true.)
