### ISSUE TITLE
Mix deps.clean removes sources of path based dependency in deps/

### ISSUE THREAD

**Issue by wrachwal** [elixir-lang/elixir#4566]
### Environment

* Elixir version (elixir -v): Elixir 1.3.0-dev (23dd272)
* Operating system: Ubuntu 14.04

### Current behavior

If a `:path` based dependency is stored in *deps/*, `mix deps.clean` (--all) removes this dependency completely (with sources!). When the location is changed outside *deps/*, sources are left intact (only its _build is cleaned).

### Expected behavior

Sources of `:path` dependencies should never removed, regardless where these dependencies were declared to reside.

**Comment by josevalim** [comment]
Yes, good catch. There is a `scm.fetchable?` option we can use to check if we should remove a path or not.

**Comment by emilsoman** [comment]
I'd like to work on the fix if this is not being worked upon.
[Here's a failing test](https://github.com/emilsoman/elixir/commit/0b0f078cb9a0712fe80129d705a04cfc1a7a4dac) that I've added, does it look alright ?

**Comment by josevalim** [comment]
Yup, the test looks great. I hvae added just one tiny comment. :)

**Comment by emilsoman** [comment]
Thanks, fixed that :) Also, here's the PR that makes the failing test pass : #4575 . Please review and let me know if something needs to change.
