### ISSUE TITLE
Getting weird stacktrace (`:`) via `assert a.nil == :b` when `a()` returns `nil`

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#4570]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.1
```

* Operating system:

OS X El Capitan

### Current behavior

``` elixir
defmodule NilTest do
  use ExUnit.Case, async: true

  test "`function_returning_nil.foo`" do
    assert function_returning_nil.foo == :bar
  end

  test "`nil.foo`" do
    assert nil.foo == :bar
  end

  defp function_returning_nil do
    nil
  end
end
```

Running these tests produces:

```
NilTest
  * `function_returning_nil.foo` (21.4ms)

  1) test `function_returning_nil.foo` (NilTest)
     test/unit/nil_test.exs:4
     ** (UndefinedFunctionError) undefined function nil.foo/0
     stacktrace:
       nil.foo()
       :

  * `nil.foo` (13.8ms)

  2) test `nil.foo` (NilTest)
     test/unit/nil_test.exs:8
     ** (UndefinedFunctionError) undefined function nil.foo/0
     stacktrace:
       nil.foo()
       test/unit/nil_test.exs:9
```

### Expected behavior

For the stacktrace for the `function_returning_nil.foo` failure I'd expect it to print `test/unit/nil_test.exs:5` instead of `:`.

On a completely unrelated note: I'm surprised these tests are taking 21.4ms and 13.8ms.  They are not really doing anything.  I'm used to seeing test runtimes like `0.03ms` for such simple tests...but these are taking a couple orders-of-magnitude longer for some reason.  I'm not opening this issue to report that, but if someone knows why it's taking so much longer and can explain it to me, I'd be very curious to hear :).

**Comment by lexmag** [comment]
> I'm surprised these tests are taking 21.4ms and 13.8ms

@myronmarston I'm wondering how you measure these times, in my tryout I'm getting 32us to run:
```
test "ok" do
    assert function_returning_nil == nil
end
```
and 1113us for the following test:
```
test "error" do
    assert function_returning_nil == 123
end
```

**Comment by myronmarston** [comment]
> @myronmarston I'm wondering how you measure these times

I'm just running `mix test --trace`.  The measured times are what ExUnit is printing.

I'm actually curious how you measured microseconds -- for me, ExUnit's measured times are in milliseconds and only show two decimal places.

Anyhow, just for comparison against the two tests you provided I decided to try them a bunch of times and see what results I got:

```
$ for i in {0..10}; do; mix test test/nil_test.exs --trace --seed 1 | grep ms; done
  * ok (0.00ms)
  * error (11.6ms)
  * ok (0.00ms)
  * error (10.5ms)
  * ok (0.00ms)
  * error (10.7ms)
  * ok (0.00ms)
  * error (11.0ms)
  * ok (0.00ms)
  * error (12.7ms)
  * ok (0.00ms)
  * error (14.5ms)
  * ok (0.00ms)
  * error (10.7ms)
  * ok (0.00ms)
  * error (10.4ms)
  * ok (0.00ms)
  * error (11.8ms)
  * ok (0.00ms)
  * error (11.2ms)
  * ok (0.00ms)
  * error (11.2ms)
```

Looks like the `ok` test is less than 10 microseconds (probably less than 5 microseconds if ExUnit does typical rounding) and the `error `test` is about 11 milliseconds (11,000 microseconds).

So apparently test failures are extremely slow (in my case, 1000x slower)?  I understand exceptions are not cheap but that's pretty surprising.

Anyhow, thanks for fixing the issue I reported!

**Comment by josevalim** [comment]
It would be nice to measure with care because definitely it is not only the
exception cost. :)

**Comment by myronmarston** [comment]
> It would be nice to measure with care because definitely it is not only the
> exception cost. :)

Can you recommend how to do that?

**Comment by lexmag** [comment]
> I'm actually curious how you measured microseconds

I've manually wrapped https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/runner.ex#L200 with `:timer.tc/1`. :bowtie:

Anyway I'll try to get time slices on every level up to failure printing to see where we spend the most of it.
I assume it is formatting.
Good thing is that happy case is wicked-fast and that's the goal. :)

**Comment by lexmag** [comment]
@myronmarston that milliseconds time is needed to load `ExUnit.AssertionError` and `Exception` modules and happens only once during whole test run:
```elixir
MyAppTest1
  * error3 (3.1ms)

  1) test error3 (MyAppTest1)

  * error (0.01ms)

  2) test error (MyAppTest1)
     
  * error2 (0.00ms)

  3) test error2 (MyAppTest1)
     
     
MyAppTest2
  * error3 (0.00ms)

  5) test error3 (MyAppTest2)

  * error (0.00ms)

  6) test error (MyAppTest2)
     
  * error2 (0.00ms)

  7) test error2 (MyAppTest2)
     
```

However on my machine it takes only `3.1ms`.
You can try to measure with the following `setup_all` to be 100% sure that it's the loading time:
```elixir
  setup_all do
    Code.ensure_loaded(ExUnit.AssertionError) |> IO.inspect
    Code.ensure_loaded(Exception) |> IO.inspect
    :ok
  end
```

**Comment by myronmarston** [comment]
Thanks for that info, @lexmag.  That definitely explains the times I was seeing from your example.  However, in my original example there is an additional 10-20ms that is unaccounted for.  Changing the assertion so that it is on `function_returning_nil.foo` instead of just `function_returning_nil` adds 10-20ms. In fact, I can remove the assertion entirely and just use `nil.foo` in my tests and I see the same sort of times.  I added the `setup_all` thing you provided above and it does not appear to have an effect:

``` elixir
defmodule NilTest do
  use ExUnit.Case, async: true

  setup_all do
    Code.ensure_loaded(ExUnit.AssertionError)
    Code.ensure_loaded(Exception)
    :ok
  end

  test "1" do
    nil.foo
  end

  test "2" do
    nil.foo
  end

  test "3" do
    nil.foo
  end
end
```

I'm also running the same test 3 times to see if there is any similar one-time load cost at play, but the times are consistently slow across all 3 tests:

```
NilTest
  * 3 (12.9ms)

  1) test 3 (NilTest)
     test/foo_test.exs:18
     ** (UndefinedFunctionError) undefined function nil.foo/0
     stacktrace:
       nil.foo()
       test/foo_test.exs:19

  * 2 (21.0ms)

  2) test 2 (NilTest)
     test/foo_test.exs:14
     ** (UndefinedFunctionError) undefined function nil.foo/0
     stacktrace:
       nil.foo()
       test/foo_test.exs:15

  * 1 (24.5ms)

  3) test 1 (NilTest)
     test/foo_test.exs:10
     ** (UndefinedFunctionError) undefined function nil.foo/0
     stacktrace:
       nil.foo()
       test/foo_test.exs:11
```

In this case, it took 12.9ms, 21.0ms and 24.5ms, all because of the `.foo` syntax.  I suspect it's because with `var.foo` syntax, it can't be statically known what that'll do -- if `var` is a map, it'll access the `:foo` key but if `var` is an alias or atom, it'll call the `foo` function on the `var` module.  In this case, `nil` is an atom, so I guess it is trying to load a module named `nil`, and that fails.  The attempted load time for the `nil` module could explain the 10-20ms I am seeing.  It's interesting to see that it gets the same slow time on each test; does the VM not cache the fact of the failed load of a `nil` module in order to not attempt it again?

Regardless, thanks for digging into this!

**Comment by lexmag** [comment]
@myronmarston yes, I think you're right, that should be the cost of module loading.

> does the VM not cache the fact of the failed load of a nil module in order to not attempt it again?

VM has two code loading modes: interactive (by default) and embedded.

* In interactive mode, only some code is loaded during system startup-up, basically the modules needed by the runtime system itself. Other code is dynamically loaded when first referenced. When a call to a function in a certain module is made, and the module is not loaded, the code server searches for and tries to load the module.

* In embedded mode, all code is loaded during system start-up according to the boot script. (Code can also be loaded later by explicitly ordering the code server to do so).

The simplest way to confirm that your times are code loading times is the following:
```
$ erl
```
```erl
1> timer:tc(fun() -> catch qwe:qwe() end).
% => {1802, ...}
```
and with `embedded` mode:
```
$ erl -mode embedded
```
```erl
1> timer:tc(fun() -> catch qwe:qwe() end).
% => {32, ...}
```

**Comment by myronmarston** [comment]
Thanks for the detailed explanation!
