### ISSUE TITLE
`map |> Stream.filter |> Map.get` confusingly returns `nil`

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#4571]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.1
```

* Operating system:

OS X El Capitan

### Current behavior

Normally, when you pass a stream to `Map.get`, it fail with a `BadMapError`:

```
iex(4)> Stream.cycle([1, 2, 3]) |> Map.get(:foo)
** (BadMapError) expected a map, got: #Function<38.10952117/2 in Stream.unfold/2>
    (stdlib) :maps.find(:foo, #Function<38.10952117/2 in Stream.unfold/2>)
    (elixir) lib/map.ex:131: Map.get/3
```

However, if you pipe a map through `Stream.filter` and then into `Map.get`, it silently returns `nil`:

```
iex(5)> %{foo: 1, bar: 2} |> Stream.filter(fn _ -> true end) |> Map.get(:foo)
nil
```

### Expected behavior

I'd expect a `BadMapError` when `Map.get` is passed any kind of stream.  I was very confused by some behavior of my code since I had a spot where I had used `Stream.filter` (and forgotten about it) and was thinking I was calling `Map.get(%{foo: 1}, :foo)` and getting `nil`.

**Comment by ericmj** [comment]
Some streams are functions, others are structs:

```iex
iex(1)> %{foo: 1, bar: 2} |> Stream.filter(fn _ -> true end)
#Stream<[enum: %{bar: 2, foo: 1},
 funs: [#Function<63.92292775/1 in Stream.filter/2>]]>
iex(2)> Stream.cycle([1, 2, 3])
#Function<35.92292775/2 in Stream.unfold/2>
```

Since structs are built from maps `Map.get/2` will work on them. We shouldn't raise `BadMapError` if you actually pass a map to `Map` functions.
