### ISSUE TITLE
** (Mix) Could not start application brcpfcnpj: 'bad encoding'

### ISSUE THREAD

**Issue by alfakini** [elixir-lang/elixir#4578]
### Environment

* Elixir version (elixir -v):

```sh
$ elixir -v
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.2.4
```

* Operating system:

```
System Version: OS X 10.11.4 (15E65)
Kernel Version: Darwin 15.4.0
```

### Current behavior

I am getting the error `** (Mix) Could not start application brcpfcnpj: 'bad encoding'` when I run `mix test`. I just added accented characters in the description of my `mix.exs` file:

```elixir
defp description do
  """
  Coleção de funções para validação e formatação de CPF e CNPJ.

  Validation and format for brazilian id documents (CPF/CNPJ).
  """
end
```

To reproduce, just add any non-ASCII character (e.g. "é") to a `mix.exs` and run `mix test`.

### Expected behavior

I was expecting Elixir to support UTF-8 by default.

**Comment by josevalim** [comment]
Apparently we cannot have non-ASCII characters in the description. I will investigate and make sure to raise better errors, thank you.
