### ISSUE TITLE
Diffing takes a long time for large strings

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4579]
If we have large strings, the diffing algorithm can take a really long time. I am not sure if it can be optimized but should set up a limit for now. Here is an example to be added to difference.exs:

```elixir
test "long strings" do
  assert String.duplicate("bar", 1000) =~ String.duplicate("foo", 1000)
end
```

We should add a limit such that, the size of both strings exceed the limit, we should not perform a diff.

**Comment by josevalim** [comment]
@lexmag one option is that, if the string is large, we could compare line by line, maybe getting some of the ideas we have seen here:

https://github.com/elixir-lang/elixir/pull/4430#issuecomment-206504858

@lexmag I am thinking that maybe the meyers difference algorithm actually belongs in Enum? The String version just calls it passing a list of graphemes?

**Comment by lexmag** [comment]
@josevalim, agree, it could be better to do line by line difference: better output and performance.
I believe it doesn't belong to `Enum`.
