### ISSUE TITLE
Add boolean methods for different unicode character groups (String.alphanumeric?, etc)

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#4580]
I have seen multiple people ([In the Elixir Slack group](https://elixir-lang.slack.com/archives/general/p1462294660007855), [on Reddit](https://www.reddit.com/r/elixir/comments/4h4y4e/whats_missing_from_the_elixir_ecosystem/d2nvbwd)) during the last couple of days requiring something that checks if a (possibly long) string contains e.g. only alphanumeric characters.

It is possible to do this using regular expressions right now (`~r/[^[:alnum:]]/u`) but this is very slow.

My proposal is to add the following boolean functions to the String module:

 - alphabetic?
 - numeric?
 - alphanumeric?
 - whitespace?
 - uppercase? 
 - lowercase?
 - control_character?

Function heads for these functions can probably be best generated by using compile-time macros similar to what other unicode-based functions already use.

**Comment by josevalim** [comment]
Please send proposals to the elixir-lang-core mailing list. IIRC, we already had such discussions in the past.

**Comment by Qqwy** [comment]
For posterity, the proposal on elixir-lang-core [can be found here](https://groups.google.com/forum/#!topic/elixir-lang-core/DU-_euhvVk0).
