### ISSUE TITLE
IEx recompile does not restart app after compilation failure

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#4581]
The helper `recompile/0` will stop running mix apps, compile the code and then start the apps again. If compilation fails the apps will not be started again.

But since recompile only restarts apps if they were started before calling recompile they will not be started the second time you call recompile, after you've fixed the compilation error.

**Comment by ericmj** [comment]
Not sure what the best way to solve this issue. We can store in `Mix.State` if apps have been started at some point and then always try to start them again if compilation was successful. WDYT?

**Comment by josevalim** [comment]
@ericmj Elixir's compilation is not going to write any file to disk in case of crashes. So maybe we can just start the app again?

**Comment by ericmj** [comment]
@josevalim They are still loaded in memory though right? Writing to disk shouldn't matter unless you restart iex.

**Comment by josevalim** [comment]
Ah, good point. :S

**Comment by josevalim** [comment]
@ericmj lately we found out in Phoenix that we do not need to actually stop applications when recompiling. What if we change `recompile` then to no longer stop applications? We could maybe add `restart` if you actually to stop and start it again. Alternatively, we can always start it afterwards. Thoughts?

**Comment by ericmj** [comment]
@josevalim Sounds good. Let's make that change on master and see how it goes.
