### ISSUE TITLE
Do not show "Compiled ...." in Mix

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4585]
The focus is to put more attention on warnings and reduce compiler output. Setting `MIX_DEBUG=1` will bring the compiler information back. We can also provide a `--verbose` option.

**Comment by josevalim** [comment]
@tsloughter is there an option we can pass to rebar3 so it doesn't print the same as well?

**Comment by ericmj** [comment]
Are there plans for a progress meter? It can be a bad user experience to not see any progress for the duration of the compilation.

**Comment by josevalim** [comment]
We could try that as well.

**Comment by whatyouhide** [comment]
If we go with the progress bar, we should think about printing warnings: where would we print them with the progress bar? All at the end? Below the progress bar, re-drawing over the previous lines?

**Comment by ericmj** [comment]
Clear the progress bar line, print the warning, draw the progress bar again below the warning.

**Comment by josevalim** [comment]
@ericmj we are not ready for that. :( it would require a very tight integration between mix and the warning system :(

**Comment by josevalim** [comment]
One alternative is to use dots, the same way we do for test suites.

**Comment by ericmj** [comment]
Dots are not a great interface unfortunately. I think we should hold off on this until we can control the output from the compiler.

Don't know if rebar3 is interested in dots or progress bar. erlang.mk just calls erlc so I don't think the output is customizable, so maybe focus on mix projects for now? For other build tools we can collect stdout and stderr and only show it for non zero exit status.

**Comment by antipax** [comment]
I would like to add that the Compiled... messages were very important in diagnosing an issue I had the other day where a rogue editor plugin was recompiling my modules in the background. This resulted in the modules not being detected as needing recompilation, and thus their .beams were not reloaded.

Without the messages indicating which files were compiled, it would have been much more difficult to realize what was going wrong. I think the MIX_DEBUG/--verbose option is sufficient, but just wanted to raise this for consideration.

**Comment by antipax** [comment]
I forgot to add that this is only relevant to use of `recompile/0` in iex. For mix CLI I'm definitely 100% on this change.

**Comment by josevalim** [comment]
@antipax one of the ideas that came to mind is to show that a file is being compiled only if it has passed 5 seconds and it has not finished compiled yet. For example:

    Compiling lib/foo.ex... (5s has passed)

Thoughts?

**Comment by whatyouhide** [comment]
I think that printing "Compiling [...]" only for *some* modules (if it takes more than 5s) may be even more confusing.

**Comment by josevalim** [comment]
@whatyouhide even if we say *why* we are printing it?

**Comment by whatyouhide** [comment]
@josevalim maybe `Compiling lib/foo.ex... (taking longer than 5s)` or something along this lines, wdyt?

**Comment by josevalim** [comment]
Yup, whatever wording makes more sense. :)

**Comment by antipax** [comment]
:+1:, I like it.

**Comment by whatyouhide** [comment]
@josevalim I started working on an implementation for this, just a couple of questions:

1. right now `Kernel.ParallelCompiler.files/2` takes an `:each_file` option. Should we add a `:each_slow_to_compile_file` option (with a better name possibly 😄)?
1. do we want this just for `mix compile`? I'm thinking of when Elixir is compiled (`make compile`), do we want this there as well?

The change per-se shouldn't be hard to implement, I think we can handle this by adding an `after` clause [in `Kernel.ParallelCompiler.wait_for_messages/8`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/parallel_compiler.ex#L196) (btw, this is the first time I write down an arity of `/8` 😆).

**Comment by josevalim** [comment]
I thought about :each_waiting.

We could also make the waiting time a configuration option.

Implementation wise, I don't think you can use after because we are waiting
for multiple files concurrently. So you will have to use Process.send_after
every time you start compiling a new file. If the timeout is triggered, you
invoke the callback. Once the file is compiled, you will have to cancel the
timer and cancel any potential inbox message.

Using after could work but you would start counting from scratch after
every new message, which means that it would likely be invoked after the
file is waiting for likely way more than 5 seconds. Maybe that's OK too.

On Saturday, May 14, 2016, Andrea Leopardi <notifications@github.com> wrote:

> @josevalim <https://github.com/josevalim> I started working on an
> implementation for this, just a couple of questions:
>
>    1. right now Kernel.ParallelCompiler.files/2 takes an :each_file
>    option. Should we add a :each_slow_to_compile_file option (with a
>    better name possibly 😄)?
>    2. do we want this just for mix compile? I'm thinking of when Elixir
>    is compiled (make compile), do we want this there as well?
>
> The change per-se shouldn't be hard to implement, I think we can handle
> this by adding an after clause in
> Kernel.ParallelCompiler.wait_for_messages/8
> <https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/parallel_compiler.ex#L196>
> (btw, this is the first time I write down an arity of /8 😆).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4585#issuecomment-219225699>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by eksperimental** [comment]
/8!???!!!! @whatyouhide luckily [it's a private function](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel/parallel_compiler.ex#L142)

**Comment by whatyouhide** [comment]
@josevalim makes sense, I will play with both implementations and see what looks/behaves nicer.
