### ISSUE TITLE
Elixir crashes on Linux Mint Rebeca

### ISSUE THREAD

**Issue by mageddo** [elixir-lang/elixir#4590]
### Environment

* Elixir version (elixir -v):

		elixir -v
		{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}
		init terminating in do_boot ()
	
* Operating system:

		cat /proc/version
		Linux version 3.13.0-74-generic (buildd@lcy01-07) (gcc version 4.8.2 (Ubuntu 4.8.2-	19ubuntu1) ) 			#118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015

* Erlang version

		$ erl
		Erlang R16B02 (erts-5.10.3) [source-b44b726] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-	poll:false]
		Eshell V5.10.3  (abort with ^G)
		1> erlang:system_info(otp_release).
		"R16B02"

### Current behavior
The elixir is crashing

**Comment by mageddo** [comment]
I tried search in stackoverflow and there, but no answer

**Comment by eksperimental** [comment]
how did you install Elixir? and what version...?
I can see you are running erlang 16, and v18 is required for 1.2.x

**Comment by eksperimental** [comment]
you can run
```sh
apt-cache policy erlang elixir
```
to find out

**Comment by mageddo** [comment]
I have downloaded the Precompiled from https://github.com/elixir-lang/elixir/releases/tag/v1.2.5 and 1.2.4

It works now, the problem was the erlang version, now I can see where is specified the elixir requirements http://elixir-lang.org/blog/2016/01/03/elixir-v1-2-0-released/.

**Comment by mageddo** [comment]
Thanks a lot

**Comment by eksperimental** [comment]
you are welcome. please do not forget to close the issue
