### ISSUE TITLE
Make alias, import and require return the module given instead of nil

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4596]
Instead of:

```iex
iex> alias Foo
nil
```

we want:

```iex
iex> alias Foo
Foo
```

**Comment by tuvistavie** [comment]
I will take this one if nobody is on it yet!

**Comment by josevalim** [comment]
Please go ahead! :D

**Comment by michalmuskala** [comment]
What should be returned in case of the multi-syntax?

```elixir
alias Foo.{Bar, Baz}
```

**Comment by josevalim** [comment]
A list of the aliased/imported/required atoms.

On Sunday, May 8, 2016, Michał Muskała <notifications@github.com> wrote:

> What should be returned in case of the multi-syntax?
>
> alias Foo.{Bar, Baz}
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4596#issuecomment-217717042>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
Maybe we should always return a list, then? It will be the most consistent option.

**Comment by josevalim** [comment]
@michalmuskala it is fine as is. I don't expect anybody to rely on such values, it is just that showing nil in the terminal is a bit weird.

**Comment by antipax** [comment]
Seems fine to go with the plan as is, but maybe returning `:ok` would be simpler to implement and achieve the goal of being clearer in the terminal?

**Comment by tuvistavie** [comment]
I agree if the main purpose is to make it sound less weird in iex, `:ok` seems better.

**Comment by josevalim** [comment]
The reason why I proposed to return the module name is because you may want to alias/import/require an already aliased, and returning the final module name will give more information about what exactly did you alias/import/require.

**Comment by tuvistavie** [comment]
I see, this makes sense indeed.
I am going to give it a try!

**Comment by antipax** [comment]
Ah, makes sense. Thanks for the explanation!

**Comment by josevalim** [comment]
@tuvistavie in case you didn't see it yet, someone already sent a PR for this. :)

**Comment by tuvistavie** [comment]
I just saw it, thank you :smile:
