### ISSUE TITLE
Consistent function definition in String.Char

### ISSUE THREAD

**Issue by paulgoetze** [elixir-lang/elixir#4609]
Just a small thing, but should the inline function [String.Chars.to_string/1](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/string/chars.ex#L44) for consistency reasons be written as 

```elixir
def to_string(charlist) do
  List.to_string(charlist)
end
```

instead of 

```elixir
 def to_string(charlist), do: List.to_string(charlist)
```
—or the other way round, the multiline definitions be one-liners where it makes sense and still reads good?

**Comment by whatyouhide** [comment]
There is no convention on this in Elixir, and I think the Elixir team tries to not focus on contributions around style too much. 😃 Also, Elixir's issue tracker is reserved for bug reports; this looks more like a questions, and it would probably be better handled in the [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core) mailing list or on Elixir's Slack/IRC channels.

**Comment by paulgoetze** [comment]
Thanks for your fast reply @whatyouhide. Yeah, maybe it sounded too much like a question—actually I suggest to care about consistency in the implementation. I know that there are community driven style guides for Elixir (like https://github.com/niftyn8/elixir_style_guide) that recommend at least consistency in whatever style you use.

I just came across this example when reading the Elixir doc and was wondering, why some functions were one-liners and other functions of the same appearance were not. Since most of Elixir is implemented in Elixir it would, in my opinion, be great if its codebase also were the first reference on how to use it. That’s why I think style and consistency matters. 

But I think you’re right—style concerns might not be the number one priorities at this stage :)
Thanks anyway for the hints on IRC and core group, will check them out.
