### ISSUE TITLE
mix deps.get , mix local.hex etc not working

### ISSUE THREAD

**Issue by waqas321** [elixir-lang/elixir#4612]
### Precheck

I'm facing the problem while using mix. When i want run any command using mix it gives me following same error on every commad
[2016/05/12-17:54:02, critical] Error: Cannot parse configuration file!
[2016/05/12-17:54:02, critical] Terminating Programm!

### Environment
* Erlang (Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false])
* Mix-Version: 00.08.37
* Elixir version (Elixir 1.1.1):
* Linux Mint 17.1

**Comment by josevalim** [comment]
@waqas321, can you please paste the full output of running your command?

**Comment by waqas321** [comment]
engintech@engintech-HP-EliteBook-8460p ~ $ mix deps.get
[2016/05/12-18:29:19, critical] Error: Cannot parse configuration file!
[2016/05/12-18:29:19, critical] Terminating Programm!

**Comment by waqas321** [comment]
@josevalim, engintech@engintech-HP-EliteBook-8460p ~ $ mix deps.get
[2016/05/12-18:29:19, critical] Error: Cannot parse configuration file!
[2016/05/12-18:29:19, critical] Terminating Programm!

**Comment by waqas321** [comment]
@josevalim, Thanks to show interest in my problem 
I'm using this blog to setup the phoenix and their dependencies 
please guide me in this

**Comment by josevalim** [comment]
@waqas321 I believe there may be something else happening in your system. The format of those error messages are not, afaik, emitted by Elixir nor Erlang. Can you please paste your `mix.exs` file?

**Comment by waqas321** [comment]
@josevalim, can't locate mix.exe file 
I'm doing my phoenix setup from this blog "http://blog.fxndev.com/erlang-elixir/"
After install Erlang and Elixir when I'm running this command "mix local.hex: it gives the error
[2016/05/12-18:29:19, critical] Error: Cannot parse configuration file!
[2016/05/12-18:29:19, critical] Terminating Programm!

**Comment by waqas321** [comment]
@josevalim  Can use tell how I install "mix tool"  for Elixir Project

When I run "sudo apt-get install mix" command it says to me to install "sudo apt-get install anon-proxy" for this. I do this when i check anon-proxy version then it show me this think

Mix-Version: 00.08.37
Using: OpenSSL 1.0.1f 6 Jan 2014
Using Xerces-C: 3.1.1
Max open sockets: 1021

I'm talking about this "MIX version" in question description

**Comment by eksperimental** [comment]
start a new project with

```sh
mix new test_project
cd test_project
mix deps.get
```

if you get some error, it is probably some corrupt file in your Elixir/Erlagn install (somehting wrong with your file system).
Those errors are linux related, not Elixir/Erlang as José stated.

if test_project works, follow the steps in the blog post (I haven't read it), and do it again starting fresh,
tell us how it goes

**Comment by eksperimental** [comment]
actually, now that you metion it, 
that is an error related to anon-proxy, 
if you google "Terminating Programm!" (sic) you will find it is related to that.

**Comment by eksperimental** [comment]
I was tempted to ask when i read your initial post, where did you get that "mix" version from.. now I see is from other mix program, not Elixir's mix.

can do put the output of this command please

`which mix`

that answer is most likely to solve this issue

**Comment by waqas321** [comment]
@eksperimental, 
$ which mix
/usr/sbin/mix

**Comment by waqas321** [comment]
@eksperimental,

mix new test_project

command give the same error

[2016/05/12-19:24:05, critical] Error: Cannot parse configuration file!
[2016/05/12-19:24:05, critical] Terminating Programm!

**Comment by eksperimental** [comment]
please do:
```
which elixir
mix --version
```

**Comment by waqas321** [comment]
@eksperimental 

which elixir
/home/engintech/elixir/elixir/bin/elixir

mix --version

Mix-Version: 00.08.37
Using: OpenSSL 1.0.1f 6 Jan 2014
Using Xerces-C: 3.1.1
Max open sockets: 1021

**Comment by eksperimental** [comment]
alright,, your anon-proxy app, has a command named mix, which is not our mix.
you need to make an alias in bash, to use 
`/home/engintech/elixir/elixir/bin/mix`and name it `elixir-mix`,

I remember some time ago somebody mentioned in the mailing list that there was a command named the same as one of the bin commands in elixir (probably mix, and probably this one).

**Comment by eksperimental** [comment]
somebody else had the same issue, https://github.com/Microsoft/BashOnWindows/issues/106#issuecomment-214930703

**Comment by waqas321** [comment]
@eksperimental thanks it work

**Comment by waqas321** [comment]
@eksperimental 
elixir-mix throw  another error
(Mix) Could not find a Mix.Project, please ensure a mix.exs file is available

**Comment by eksperimental** [comment]
you need to run mix from the root folder in your project, you are proabbly running ti from somewhere else. and there must be a mix.exs file in it, if you created a project with the `mix` command ,it should be there

**Comment by pedroassumpcao** [comment]
@waqas321 are you in the directory of a mix project?

**Comment by waqas321** [comment]
@josevalim, @eksperimental, @pedroassumpcao once again thanks for helping me. 
@eksperimental specially you 
My has been problem resolved cause of you

**Comment by eksperimental** [comment]
@waqas321 no worries
fortunately other people will see this and figure out what's going on in their system
