### ISSUE TITLE
Mix compile error by renamed packages

### ISSUE THREAD

**Issue by liveforeverx** [elixir-lang/elixir#4619]
Hi! 

I have a [repository](https://github.com/liveforeverx/riak_app) for reproducing it. Checkout repository and do `mix do deps.get, compile`

### Environment

* Elixir version (elixir -v): Elixir 1.3.0-dev (9d03be2)
* Operating system: Mac OS X 10.11.4 (15E65)
* Hex: v0.11.5

### Current behavior

Seems, like Hex + mix tries to compile a package with hex name instead of proposed application name, I didn't dived in a code at the moment:

```elixir
Unchecked dependencies for environment dev:
* basho_poolboy (Hex package)
  could not find an app file at _build/dev/lib/basho_poolboy/ebin/basho_poolboy.app. This may happen if the dependency was not yet compiled, or you specified the wrong application name in your deps, or the dependency indeed has no app file (then you can pass app: false as option)
** (Mix) Can't continue due to errors on dependencies
```

It is defined in `riak_core` as: `{poolboy, "0.8.1-p3", {pkg, basho_poolboy}}`

### Expected behavior

Compiles.

**Comment by josevalim** [comment]
Thank you. I think @kanatohodets has stumbled on this issue too.

**Comment by ericmj** [comment]
Can you include `mix deps.tree`? We need to know how the `riak_core` dependency is declared.

**Comment by liveforeverx** [comment]
@josevalim after his presentation I wanted to switch our codebase from big `override`-s with patches over dependencies, and stumbled to it.

**Comment by liveforeverx** [comment]
@ericmj 
```
riak_app
└── riak_core ~> 2.2 (Hex package)
    ├── riak_sysmon 2.1.2 (Hex package)
    │   └── lager 3.0.2 (Hex package)
    │       └── goldrush 0.1.7 (Hex package)
    ├── riak_ensemble 2.1.3 (Hex package)
    │   ├── lager 3.0.2 (Hex package)
    │   │   └── goldrush 0.1.7 (Hex package)
    │   └── eleveldb 2.1.3 (Hex package)
    ├── pbkdf2 2.0.0 (Hex package)
    ├── lager 3.0.2 (Hex package)
    │   └── goldrush 0.1.7 (Hex package)
    ├── goldrush 0.1.7 (Hex package)
    ├── exometer_core 1.0.0 (Hex package)
    │   ├── setup 1.7.0 (Hex package)
    │   ├── parse_trans 2.9.0 (Hex package)
    │   │   └── edown > 0.0.0 (Hex package)
    │   ├── lager 3.0.2 (Hex package)
    │   │   └── goldrush 0.1.7 (Hex package)
    │   └── folsom 0.8.3 (Hex package)
    │       └── bear 0.8.3 (Hex package)
    ├── erocksdb 0.4.1 (Hex package)
    ├── eleveldb 2.1.3 (Hex package)
    ├── edown 0.7.0 (Hex package)
    ├── cuttlefish 2.0.7 (Hex package)
    │   ├── lager 3.0.2 (Hex package)
    │   │   └── goldrush 0.1.7 (Hex package)
    │   └── getopt 0.8.2 (Hex package)
    ├── clique 3.0.1 (Hex package)
    │   └── cuttlefish 2.0.7 (Hex package)
    │       ├── lager 3.0.2 (Hex package)
    │       │   └── goldrush 0.1.7 (Hex package)
    │       └── getopt 0.8.2 (Hex package)
    ├── chash 0.1.1 (Hex package)
    ├── basho_stats 1.0.3 (Hex package)
    └── basho_poolboy 0.8.1-p3 (Hex package)
```

**Comment by ericmj** [comment]
@liveforeverx Thank you, it only seems to be an issue for transitive dependencies which indicates a hex issue. Lets keep the issue open here while I investigate.

**Comment by ericmj** [comment]
The issue seems to be with rebar3_hex. The package is published with `basho_poolboy` as the application name of the `basho_poolboy` dependency.

**Comment by josevalim** [comment]
@ericmj did you ping them? :)

**Comment by ericmj** [comment]
I have pinged them, waiting for confirmation before I close this issue.

**Comment by kanatohodets** [comment]
Regarding José's note -- yep, this is exactly what I bumped into (and hacked around by editing the .app file in `deps/`). Thanks @liveforeverx for writing up the issue.

**Comment by ericmj** [comment]
Reported to rebar3 team.

**Comment by liveforeverx** [comment]
Does there exists related issue?

@ericmj Thank you!

**Comment by ericmj** [comment]
It should be fixed in this commit https://github.com/hexpm/rebar3_hex/commit/a512dffbc14b17e69c1b8533534252cc0b80aca3.

A new release of rebar3_hex should be coming out soon, keep an eye on hex.pm.

**Comment by liveforeverx** [comment]
@ericmj One more question: Should the maintainers of broken packages publish new version, or it will be fixed automatically on hex??

**Comment by ericmj** [comment]
@liveforeverx They need to push a new version but the maintainers unfortunately want to wait until there are changes in the upstream riak_core.

**Comment by Licenser** [comment]
To clarify the reasoning for not publishing a new package, riak_core_ng is in sync with the riak core versions (+1 minor version for the additional functionality as dictated by semver). It is not allowed to re-publish the package on the same version (mix policy), build metadata is not a part of the package identity in mix either (so it is not possible to publish `2.2.5+mixfix` so that isn't a way to fix it either.

With that there are only two options left:
1) Publish a new patch without any code changes
2) Wait until a new version of riak_core is released and then upload a new version

I decided on 2, since option 1 has major issues. It is violates semver there is no patch or code change involved here, the only change is what hex stores as package metadata. the package will get out of sync with riak core until the next minor or major release is published (by that resetting the patch level to zero and solving the out of sync). Having the sync broken is involving some serious confusion on what version is what and how they relate.

**Comment by josevalim** [comment]
Thank you for the feedback @Licenser!

**Comment by liveforeverx** [comment]
@Licenser Thank you for feedback!

**Comment by Licenser** [comment]
Sorry to comment on a closed issue, I know this took a really really long while to get sorted, but a new version of riak_core was release and after a week or two with banging my head against the dependencies there is now a new riak_core_ng package that should solve this problem.
