### ISSUE TITLE
dependency calculation issues

### ISSUE THREAD

**Issue by vadim-moz** [elixir-lang/elixir#4622]
### Environment

* Elixir version (elixir -v): v1.2.5
* Operating system: Linux

### Current behavior

Full code sample: https://github.com/josevalim/umbrella_sample/pull/4

relevant part:

umbrella project with three subprojects (dependencies only):

master:
```ex
  defp deps do
    [
      test_only: [in_umbrella: true, only: :test],
      helper: [in_umbrella: true, only: [:dev, :test]],
    ]
  end
```

helper:
```ex
  defp deps do
    [
      test_only: [in_umbrella: true, only: :test],
    ]
  end
```

test_only:
```ex
  defp deps do
    [
    ]
  end
```

When executed:

```bash 
cd apps/master
MIX_ENV=test mix compile
```

output:
```
Unchecked dependencies for environment test:
* test_only (../test_only)
  the dependency test_only

  > In mix.exs:
    {:test_only, nil, [path: "../test_only", in_umbrella: true, only: :test, manager: :mix]}

  does not match the environments calculated for

  > In /.../v-umbrella_sample/apps/helper/mix.exs:
    {:test_only, nil, [only: [:dev, :test], path: "../test_only", in_umbrella: true]}

  Ensure the parent dependency specifies a superset of the child one in your dep
** (Mix) Can't continue due to errors on dependencies
```

in constrast

```bash
pushd apps/master
mix compile
popd 

mix compile

MIX_ENV=test mix compile
```

all result in successful compilation. It can also be observed running `mix deps` and other commands. The behavior does not depend on shared or separate build/config directories.

### Expected behavior

* no error should be reported.
* dependency error detection (at very least, for `mix deps`) should not depend on the `mix` environment. (I recognize that for other `mix` subcommands it might be a matter of optimization. For example, if `A` depends on `B` for `only: :test`, and current environment is `:dev`, it is reasonable not to load `B` in compilation and other commands. `mix deps` has a special status however, it is used to track dependencies.)

**Comment by josevalim** [comment]
TIL about `pushd` and `popd`. :)

**Comment by josevalim** [comment]
I have fixed this but I would like to add a note about this:

> dependency error detection (at very least, for mix deps) should not depend on the mix environment. 

`mix deps` must be per environemnt because it is not even guaranteed we can get all deps from all environments into the same tree without running into more conflicts. In particular, every dependency is loaded in a particular environment (prod for regular dependencies and Mix.env for umbrella siblings), which adds to this notion that `mix deps` represents the current environment.
