### ISSUE TITLE
improve error messages based on context

### ISSUE THREAD

**Issue by henry-hz** [elixir-lang/elixir#4630]
### Environment

* Elixir version (elixir -v): 1.3-dev
* Operating system: debian

### Current behavior

Sometimes, if the developer forget to fill variables as the example below: entity, execution and updated, the compiler claims that these variables are a function call without parentheses, but in fact they are variables. 

```elixir
RedixPool.command(~w(HSET #{entity} #{execution} #{updated}))
== Compilation error on file lib/common/db.ex ==
** (CompileError) lib/common/db.ex:66: undefined function entity/0
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
```

### Expected behavior

Expect the compiler to know if it lacks a function or a variable could be too complex, based on the context, but would be more precise. Another option is to output a broader message:
** (CompileError) lib/common/db.ex:66: undefined variable entity or function entity/0

**Comment by josevalim** [comment]
@henry-hz Elixir v1.4 will warn when a variable becomes used as a function call, so when used together it will provide enough context. Other than that, those errors are raised in different parts of the stack, so when we raise that the function was not defined we no longer have the information it was a variable, unfortunately.  For the other issue, please track #3517.
