### ISSUE TITLE
mix compile freezes

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#4646]
I have a commit where `mix compile` freezes without output.  I assume this is due to some circular dependency, but I would expect the compiler to either tell me that (since it's computing a dependency graph and topological sort to order the compiles) or error out with a timeout if the circular dependency can't be detected.

The commit that triggers the freezing is https://github.com/C-S-D/alembic/commit/d668ebdbd78e6129fe7e1a82ee0988057208b451.

When I build locally (using Elixir 1.2.3 or 1.2.5), it freezes after compiling `lib/alembic/document.ex`:

```
$ rm -rf _build
$ mix compile
==> alembic
Compiled lib/alembic.ex
Compiled lib/alembic/fetch.ex
Compiled lib/alembic/relationship_path.ex
Compiled lib/alembic/pagination.ex
Compiled lib/alembic/pagination/page.ex
Compiled lib/alembic/to_ecto_schema.ex
Compiled lib/alembic/from_json.ex
Compiled lib/alembic/to_params.ex
Compiled lib/alembic/relationships.ex
Compiled lib/alembic/relationship.ex
Compiled lib/alembic/fetch/includes.ex
Compiled lib/alembic/resource_linkage.ex
Compiled lib/alembic/meta.ex
Compiled lib/alembic/link.ex
Compiled lib/alembic/source.ex
Compiled lib/alembic/resource_identifier.ex
Compiled lib/alembic/error.ex
Compiled lib/alembic/resource.ex
Compiled lib/alembic/document.ex
```

On CircleCI (https://circleci.com/gh/C-S-D/alembic/79), using a cache of _build and Elixir 1.2.3, it freezes after compiling `lib/alembic/resource_linkage.ex`:

```
$ mix compile
Compiled lib/alembic.ex
Compiled lib/alembic/fetch.ex
Compiled lib/alembic/from_json.ex
Compiled lib/alembic/pagination.ex
Compiled lib/alembic/pagination/page.ex
Compiled lib/alembic/relationship_path.ex
Compiled lib/alembic/to_ecto_schema.ex
Compiled lib/alembic/error.ex
Compiled lib/alembic/to_params.ex
Compiled test/support/api/test_author.ex
Compiled lib/alembic/link.ex
Compiled lib/alembic/meta.ex
Compiled lib/alembic/source.ex
Compiled lib/alembic/fetch/includes.ex
Compiled lib/alembic/relationship.ex
Compiled lib/alembic/relationships.ex
Compiled lib/alembic/resource.ex
Compiled lib/alembic/document.ex
Compiled lib/alembic/resource_identifier.ex
Compiled lib/alembic/resource_linkage.ex
```

Once sorted the only extra file is ` test/support/api/test_author.ex` on CircleCI, so it's probably just a random ordering thing between the two environments.

**Comment by josevalim** [comment]
@KronicDeth can you please try Elixir master? The compiler has many improvements and one of them is exactly better deadlock detection.

**Comment by josevalim** [comment]
This is what I got in master:

```
==> alembic
Compiling 26 files (.ex)

== Compilation error on file lib/alembic/links.ex ==
** (CompileError) lib/alembic/links.ex:345: Pagination.__struct__/0 is undefined, cannot expand struct Pagination
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```

That seems to be the real issue but your compiler is getting stuck for some reason. So it is fixed in master indeed. :)

**Comment by KronicDeth** [comment]
I got the build to work by redoing the cherry-pick (Alembic is opening sourcing part of one our private repos).  The issue was a missing `alias Alembic.Pagination` in `lib/alembic.links.ex`, so the `@behaviour Pagination`, `Pagination.t` and `%Pagination{}` would all have been waiting on `Pagination` module to be defined instead of the correct `Alembic.Pagination`.  The odd part is, I've had circular dependencies with structs before and it will give a nice error like `Pagination.__struct__` is not defined, so maybe the problem was the `@behavior Pagination`.

Also, hooray for compiler improvements in master!
