### ISSUE TITLE
Handle generated listings in lexical tracker

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4657]
@antipax, when collecting calls, some of those calls may come from within a macro. For example:

    some_macro()

Which can expand to:

    SomeUnknownModule.unknown_function(1, 2, 3)

We typically do not emit warnings for generated code. Because if the user looks at the source, he won't ever see such calls. I have opened this to discuss how we want to support this regarding the lexical tracker.

**Comment by antipax** [comment]
Yeah, definitely needs some discussion. Maybe we could move these dispatches to `compile_dispatches` and annotate them with the macro that generated them, and then also check `compile_dispatches` like we do `runtime_dispatches`, and in the warning display the source macro call in addition to the missing function.

**Comment by josevalim** [comment]
@antipax they would fit the "compile time" bucket by some broad definition. :) Maybe it is fine to not implement this for now. We do not skip warnings for all generated code, mostly variables, and maybe those warnings will be useful. Let's wait and see. :)
