### ISSUE TITLE
Executable code doesn't have proper line numbering in the abstract code

### ISSUE THREAD

**Issue by studzien** [elixir-lang/elixir#4659]
### Environment

* Elixir version (elixir -v): Elixir 1.3.0-dev (ee715dd)
* Operating system: OS X 10.11

### Current behavior

The following function:
```
def to_integer('0'), do: 0
def to_integer('1'), do: 1
```

has the following abstract code generated:
```
      {function,2,to_integer,1,
       [{clause,2,
         [{cons,0,{integer,0,48},{nil,0}}],
         [],
         [{integer,0,0}]},
        {clause,3,
         [{cons,0,{integer,0,49},{nil,0}}],
         [],
         [{integer,0,1}]}]}
```

What means, that not all [executable lines](http://erlang.org/doc/apps/tools/cover_chapter.html#lines) are tagged correctly (with line number 0 instead of their actual line number), causing the ``cover`` tool to generate inappropriate analysis results.
As far as I can see, this is also the case for the ``case`` branches.

### Expected behavior

Mark all the "executable lines" with the proper line in the abstract code, allowing coverage tools to generate correct results.

**Comment by josevalim** [comment]
That's a side-effect of how Elixir AST works. Values that are literals, like integers and lists, do not have line information attached to them, so they will be always marked as 0 in the intermediate Erlang Abstract Format.

**Comment by josevalim** [comment]
Case branches should be properly annotated. If they are not annotated, please post examples.

**Comment by studzien** [comment]
I actually still meant literals, but inside the ``case`` structure, so for example the above code rewritten as:
```
  def to_integer(i) do
    case i do
      '0' -> 0
      '1' -> 1
    end
  end
```

If you have time, can you please quickly describe what makes the Elixir literals different than Erlang ones, where they are annotated properly?

Correct me if I'm wrong, but if Elixir literals are not annotated with the line number we will never be able to tell which branches of ``case`` or which clauses of a function (in a case/function like above) were covered.

If I didn't make myself clear I can provide an Elixir vs. Elixir example of the issue I'm experiencing :)

Cheers.

**Comment by josevalim** [comment]
> If you have time, can you please quickly describe what makes the Elixir literals different than Erlang ones, where they are annotated properly?

The integer 42 in Erlang AST is represented as `{integer, Line, 42}`. In Elixir AST it is simply `42`. This is very useful in Elixir when it comes to macros but it means we will have no line information when we convert it to the Erlang AST.

> Correct me if I'm wrong, but if Elixir literals are not annotated with the line number we will never be able to tell which branches of case or which clauses of a function (in a case/function like above) were covered.

You can still look at the line information in the clause in the Erlang abstract format (see 2 below):

    [{clause,2,
         [{cons,0,{integer,0,48},{nil,0}}],
         [],
         [{integer,0,0}]},

**Comment by studzien** [comment]
Yes, that's obvious, but still clauses are not executable pieces in the ``cover``'s terms.
Wouldn't it make sense then to approximate the line number of literals during the Elixir AST -> Erlang AST transformation, so we don't make ``cover`` a little bit useless?

**Comment by josevalim** [comment]
I would rather have a cover that understands Elixir semantics than complicate the generation of Elixir -> Erlang AST with the only purpose of making cover happier.

**Comment by josevalim** [comment]
Oops, premature send. If you search the issues tracker, you will see there are other cover and coverage related issues, and that's because in some situations we cannot pass all the meaning to Erlang Abstract Format, specially with constructs like default arguments.

**Comment by studzien** [comment]
I've already seen the issue with the default arguments :)
Thanks for the explanation and I hope I can help somehow when there's work on "cover that understands elixir" ;)
