### ISSUE TITLE
Compilation error when using bitstrings spec

### ISSUE THREAD

**Issue by JustMikey** [elixir-lang/elixir#4669]
There is a closed [issue](https://github.com/elixir-lang/elixir/issues/3340) on the same problem but the resolution seems unclear and the problem still exists. My elixir version is 1.2.5.

**Comment by josevalim** [comment]
Can you please provide your source code? The issue in the original report is that the syntax is simply invalid:

       @spec foo(<<_ :: 32, _ :: _ * 8>>) :: list   

A bitstring typespec can only have a single element.

**Comment by ericmj** [comment]
The elixir docs and code are invalid. For some reason Erlang supports that syntax but not `<<_::size*unit>>`.

http://erlang.org/doc/reference_manual/typespec.html

**Comment by josevalim** [comment]
@ericmj yes, I just realized that now. We need to fix Elixir. Thanks @JustMikey.
