### ISSUE TITLE
Add to_iso8601 and from_iso8601 to Time, Date and NaiveDateTime

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4672]
We are going to support the Calendar dates in the extended format: https://en.wikipedia.org/wiki/ISO_8601

## Notes

  * `to_iso8601`: Returns a string
  * `to_iso8601`: All entries (hour, minute, second, ...) must be padded per the standard
  * `to_iso8601`: Must match the calendar field on its inputs to be `Calendar.ISO`

  * `from_iso8601`: Returns `{:ok, struct} | {:error, atom}`
  * `from_iso8601`: The values must also be checked for validity. The `new` function can be used for such after parsing
  * `from_iso8601`: Microseconds must be parsed for times and naive datetimes. If higher precision is given, the value must be *truncated*.

## Questions

* If a datetime with timezone is given to `NaiveDateTime.from_iso8601`, should we accept it and ignore the timezone information or should we not accept it?

/cc @lau @bitwalker

**Comment by lau** [comment]
I think it is fine to ignore UTC offset information if present.

**Comment by bitwalker** [comment]
I'm not strongly opposed to ignoring it, but I really kind of feel like if we have the UTC offset, we should shift it to UTC if we're going to discard the information.

**Comment by josevalim** [comment]
Closed in favor of #4676
