### ISSUE TITLE
Normalize precision and Calendar fields

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4680]
The System.convert_time_unit function accepts precision as `:seconds`, `:minutes` and so on. The Calendar fields are singular: `:second`, `:minute`, etc. Should we normalize those to be same? I believe the answer should be no because precision is in "seconds", "kilograms", etc (plural) and the fields should be singular, although I thought I would bring the topic up anyway.

/cc @lau @bitwalker @lexmag @fishcakez

**Comment by lexmag** [comment]
I agree with not changing these names.
My reasoning is the following:
Calendar fields say what `:second` (`:minute`, ets.) of point in time it represents (e.g. X second of Y hour).
Precision says what unit of it you expect as function return, e.g X [amount of] `:seconds` in Y `:minutes`.
