### ISSUE TITLE
Dependency conversion error in umbrella

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#4684]
### Environment

* Elixir version (elixir -v): latest master (and 1.2.4)
* Operating system: ubuntu 16.04

### Current behavior

One app in umbrella lists ecto as a normal hex dependency.
Another one that has the first one as a dependency lists ecto as path dependency using `override: true`.
The override is not taken into account and a dependency diversion error is printed (recommending to use `override: true`).

```
Dependencies have diverged:
* ecto (Hex package)
  different specs were given for the ecto app:

  > In apps/famitool_domain/mix.exs:
    {:ecto, "~> 2.0.0-rc", [env: :prod, hex: :ecto]}

  > In apps/famitool_api/mix.exs:
    {:ecto, [env: :prod, path: "~/projects/ecto", override: true]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

### Expected behavior

The path dependency overrides the other one and is used.

**Comment by josevalim** [comment]
From the umbrella project perspective, they are not being overridden because they are siblings. You need to make them consistent or override at the umbrella parent as well. The former is advised.

**Comment by michalmuskala** [comment]
Yeah makes sense, overriding at the umbrella level works.
Overriding in each application is not really practical for quick changes to test some ecto bugs :smirk: 

The error message could be better though. I believe mix knows you're in umbrella, doesn't it?

**Comment by ericmj** [comment]
I tried to change 'Ensure they match or specify one of the above in your deps and set "override: true"' to say that you should override at a higher level but couldn't find a way to word it that wouldn't just make it more confusing.

@michalmuskala Do you have any suggestions for how to improve the error message?

**Comment by josevalim** [comment]
I think the message is good because he is getting it already at the
umbrella root. So it is implicit the issue is tied to the root mix.exs.
Although if we can improve it more, then surely!

On Wednesday, May 25, 2016, Eric Meadows-Jönsson <notifications@github.com>
wrote:

> I tried to change 'Ensure they match or specify one of the above in your
> deps and set "override: true"' to say that you should override at a higher
> level but couldn't find a way to word it that wouldn't just make it more
> confusing.
>
> @michalmuskala <https://github.com/michalmuskala> Do you have any
> suggestions for how to improve the error message?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4684#issuecomment-221553094>
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
Maybe when we have an umbrella and an override in one of the conflicting dependencies we could give something like:

```
All applications of an umbrella are treated equally and one cannot override 
dependencies of the others. In order to override a dependency version you
can set it directly on the umbrella or in each of the applications.
```

**Comment by ericmj** [comment]
> All applications of an umbrella are treated equally and one cannot override 
dependencies of the others.

This is not strictly true, siblings can't override each other, but umbrella apps can have a hierarchy.

**Comment by michalmuskala** [comment]
I thought a little bit more about this. Maybe something like that:

```
Sibling applications in umbrellas cannot override each other's dependencies.
In order to override a shared umbrella dependency, you need to set the override in the
umbrella's mix.exs or in each of the applications using it.
```

**Comment by josevalim** [comment]
I believe detecting this exact scenario may be non trivial. Umbrella apps
are treated as regular dependencies and the issue does not happen in the
dep but in their parent. If you want to give this a try, please go ahead,
but it may be tricky.

On Saturday, May 28, 2016, Michał Muskała <notifications@github.com> wrote:

> I thought a little bit more about this. Maybe something like that:
>
> Sibling applications in umbrellas cannot override each other's dependencies.
> In order to override a shared umbrella dependency, you need to set the override in the
> umbrella's mix.exs or in each of the applications using it.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4684#issuecomment-222325497>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbrNlj4vnoeyaGwIoxY6CcFNROOY5ks5qGJbDgaJpZM4ImOwE>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
I think it may be enough to detect it if we are in an umbrella and one of the conflicting dependencies has `override: true`.
