### ISSUE TITLE
URI.to_string produces inconsistent result if IPv6 address and port were specified

### ISSUE THREAD

**Issue by kroburg** [elixir-lang/elixir#4685]
### Environment

* Elixir 1.2.3
* Ubuntu Linux

According to RFC (https://tools.ietf.org/html/rfc3986#section-3.2.2 and https://www.ietf.org/rfc/rfc2732.txt) IPv6 address should be enclosed in "[" and "]'. It is crucial to put braces if port was specified.

URI.to_string should enclose IPv6 address in "[" and "]" but it is not.

### Current behavior

Result of `URI.to_string(URI.parse("http://[2001:db8::]:8080"))` is `"http://2001:db8:::8080"`

I.e. result of `URI.to_string(URI.parse(URI.to_string(URI.parse("http://[2001:db8::]:8080"))))` is 
`"http://2001"`

### Expected behavior

Result of `URI.to_string(URI.parse("http://[2001:db8::]:8080"))` is `"http://[2001:db8::]:8080"`

I.e. result of `URI.to_string(URI.parse(URI.to_string(URI.parse("http://[2001:db8::]:8080"))))` is `"http://[2001:db8::]:8080"`

**Comment by whatyouhide** [comment]
This indeed seems like a bug, but I'll look into it a bit more and see what can be done :) Thanks for the report @kroburg!

**Comment by tuvistavie** [comment]
I think that it is a bug in `URI.to_string`.
Stripping the brackets when parsing is fine, but they should be added
back in `to_string` when the IP is v6 and a port is present I think.

**Comment by whatyouhide** [comment]
@tuvistavie yeah, the idea is that the bug is in `URI.to_string/1`. Still not sure about the solution though :0

**Comment by josevalim** [comment]
Isn't : in the host invalid unless it is IPv6? If so, that's your check. :)

On Wednesday, May 25, 2016, Andrea Leopardi <notifications@github.com>
wrote:

> @tuvistavie <https://github.com/tuvistavie> yeah, the idea is that the
> bug is in URI.to_string/1. Still not sure about the solution though 😃
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4685#issuecomment-221582354>
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by tuvistavie** [comment]
For reference, according to RFC 3986

> A host identified by an Internet Protocol literal address, version 6
   [RFC3513] or later, is distinguished by enclosing the IP literal
   within square brackets ("[" and "]").

**Comment by whatyouhide** [comment]
Yep, @josevalim's solution sounds right as `:` is not allowed in the "host" part of a URI (specifically, it's not allowed in `IPv4address` or in `reg-name`):

```
host = IP-literal / IPv4address / reg-name
```

PR on its way :)

**Comment by whatyouhide** [comment]
I did some research and I have some updates. First of all, we do something bad, which is stripping the `[]` from the *authority* when parsing URIs:

```elixir
iex> URI.parse("http://foo@[::]:1234")
%URI{authority: "foo@:::1234", fragment: nil, host: "::", path: nil, port: 1234,
 query: nil, scheme: "http", userinfo: nil}
```

As you can see, we strip brackets from the `:host` field as well.

I researched what other languages are doing.

### Ruby, Java
They keep `[]` in both authority (`[::]:1234`) as well as host (`[::]`).

### Python, NodeJS
They keep `[]` in the authority (`[::]:1234`), as well as host (`[::]`).

## What do to

Right now, we:

* strip the host of `[]`s
* rebuild the authority from `userinfo + host + port` when parsing in `URI.parse/1` (which means we lose the `[]` in the host given that we stripped them)
* build the URI as `[...] + userinfo + host + port + [...]` in `URI.to_string/1`, falling back to `[...] + authority + [...]` if the host is not present

What I'm gonna do to try and make things better:

* [ ] we'll not rebuild the authority ourselves when parsing in `URI.parse/1`, but use the raw authority we got (meaning that `URI.parse("http://[::]:1234").authority == `[::]1234`)
* [ ] we'll keep stripping `[]` from the host when parsing, but this won't affect the authority anymore (this will make us more backwards compatible and we don't strictly need `[]` there)
* [ ] we'll prefer using the authority in `URI.to_string/1` if there's one, as the authority will contain all the info we need about that part (and it will be faster ¯\\\_(ツ)\_/¯)
* [ ] if we don't have the authority in `URI.to_string/1`, we build it ourselves from `userinfo + host + port`, *but* we surround `host` with `[]` if it contains one or more `:` (as per the RFC)
* ...
* profit!

**Comment by kroburg** [comment]
As I remember, current URI module implementation perform some URI normalization during URI.to_string/1. It will remove specified port if it is equal to the current scheme default port, for example. I think that the right way is to split URI.to_string/1 into URI.to_string/1 and new URI.normalize/1 function.

And new URI.normalize/1 should favor rules from [RFC normalization rules] (https://tools.ietf.org/html/rfc3986#section-6).

**Comment by kroburg** [comment]
BTW, URI.normalize/1 is a separate topic for discussion because there are pitfalls and some questions:
* Should we add or remove `/` from the last path segment? (I think they should be removed, yet RFC mentions some concerns)
* Do we need to sort query arguments?
* What about query arguments separators (`&`, `?` etc.)?
* Should we apply IDNA encoding for authority?

**Comment by whatyouhide** [comment]
@kroburg indeed, you're right, we do perform some normalization and this is why we prefer to use `userinfo + host + port` if we have those. I agree that `URI.normalize/1` and such things should be discussed separately.

So, let's do something different to fix this issue:

* always print the host surrounded by `[]` if it contains one or more `:` in `URI.to_string/1`
* don't strip the `[]` from the host when building the authority in `URI.parse/1` (otherwise `URI.parse("foo://[::]:1234").authority` will result in `":::1234"` - the current behaviour - instead of `"[::]:1234"`, which sucks)

**Comment by josevalim** [comment]
> don't strip the [] from the host when building the authority in URI.parse/1

That's backwards incompatible though. We need to continue stripping it. It should be ok though to not rebuild the authority.

**Comment by whatyouhide** [comment]
@josevalim I know it's backwards incompatible, but I think it's a bug 😕

Just to be 100% clear, I mean that `URI.parse("foo://[::]:1234")` will have `authority: "[::]:1234"` and `host: "::"`.

**Comment by josevalim** [comment]
> Just to be 100% clear, I mean that URI.parse("foo://[::]:1234") will have authority: "[::]:1234" and host: "::".

If so, this is fine, yes. :)
