### ISSUE TITLE
DateTime.utc_now() fails under Windows

### ISSUE THREAD

**Issue by robi-wan** [elixir-lang/elixir#4704]
### Environment

* Elixir version (elixir -v):
Erlang/OTP 18 [erts-7.3] [64-bit] [smp:8:8] [async-threads:10]
Elixir 1.3.0-dev (commit c839521d741764fb8b516f24cbdeea1b262a4cd5)

* Operating system: Windows 7 Professional 64bit

### Current behavior

Doc Test `DateTime.utc_now()` fails:

    test doc at DateTime.utc_now/0 (15) (DateTimeTest)
     test/elixir/calendar_test.exs:61
     Doctest failed: got CaseClauseError with message no case clause matching: 1024000
     code:  datetime = DateTime.utc_now()
            datetime.time_zone
     stacktrace:
       (elixir) lib/calendar.ex:1006: DateTime.precision_for_unit/1
       (elixir) lib/calendar.ex:996: DateTime.from_unix/2
       (elixir) lib/calendar.ex:1032: DateTime.from_unix!/2
       (for doctest at) lib/calendar.ex:959: (test)

Using the :native time unit under Windows converts one second to 1_024_000 native time units. `precision_for_unit/1` lacks a case clause for this value:

    iex(5)> :os.system_time |> DateTime.from_unix!(:native)
    ** (CaseClauseError) no case clause matching: 1024000
        (elixir) lib/calendar.ex:1006: DateTime.precision_for_unit/1
        (elixir) lib/calendar.ex:996: DateTime.from_unix/2
        (elixir) lib/calendar.ex:1032: DateTime.from_unix!/2

    iex(5)> System.convert_time_unit(1, :seconds, :native)
    1024000

### Expected behavior

DateTime.utc_now() does not fail under Windows.

Suggestion:

    diff --git a/lib/elixir/lib/calendar.ex b/lib/elixir/lib/calendar.ex
    index 42af9cf..128f919 100644
    --- a/lib/elixir/lib/calendar.ex
    +++ b/lib/elixir/lib/calendar.ex
    @@ -1006,8 +1006,7 @@ defmodule DateTime do
         case System.convert_time_unit(1, :seconds, unit) do
           1 -> 0
           1_000 -> 3
    -      1_000_000 -> 6
    -      1_000_000_000 -> 6 # Our maximum precision is 6
    +      x when x >= 1_000_000 -> 6 # Our maximum precision is 6
         end
       end

**Comment by josevalim** [comment]
@robi-wan I have pushed a fix to master, can you please give it a try? Thank you!

**Comment by robi-wan** [comment]
@josevalim Works. Thank you!
