### ISSUE TITLE
mix escript.install/archive.install from SCM

### ISSUE THREAD

**Issue by antipax** [elixir-lang/elixir#4734]
@ericmj's proposal on the elixir-lang-core list:

> Today we have `mix escript.install` for installing escripts on the local system.
> It supports installing pre-built escripts from the local filesystem or via HTTP.
> 
> One issue with this is that the project maintainers need to build and host the
> escripts themselves which goes against the conveniences we have built around Mix
> with Hex and the surrounding tooling such as HexDocs.
> 
> We propose to extend the `escript.install` task with support for building and
> installing projects via Git URLs or Hex package names. Examples of this would be:
> 
>     $ mix escript.install github my_project git_ref
>     $ mix escript.install git https://path/to/git/repo git_ref
>     $ mix escript.install hex phoenix_new
>     $ mix escript.install hex phoenix_new 1.2.3
> 
> This would fetch the project and its dependencies to a temporary directory with
> Mix' dependency tooling, build the project as an escript and install it on the
> local system.

Going to be working on this now, so let me know if you have any ideas or feedback about this for me to incorporate.

/cc @josevalim @ericmj

**Comment by antipax** [comment]
Just going to reuse this issue for the archive.install version, unless anyone has any objections.

**Comment by josevalim** [comment]
Sounds good!
