### ISSUE TITLE
Using prim_file instead of using file

### ISSUE THREAD

**Issue by olafura** [elixir-lang/elixir#4740]
:code already states that:
%% prim_file is faster than file and the file server may
%% not be started yet.

And the :file_server is basically just a wrapper.

I think it might be worth considering at least for read and write.

I'm just wondering if the other interface are just for backwards
compatibility and not being tied to an implementations.

I'll try creating some tests to see what the difference is.

We are already requiring certain versions of Erlang.

**Comment by fishcakez** [comment]
@olafura `:prim_file` is not documented so we wont be used it directly. You can open with `raw` mode to use `:prim_file` almost directly. The code server can not use `:file`/`:file_server` to load `:file`/`:file_server` but `:prim_file` is preloaded so will always be there to load other files with.

**Comment by fishcakez** [comment]
@olafura but yes you can gain quite some performance by using `:raw` mode, I suggest you try it out and perhaps other tips listed in the `File` docs :smile:.

**Comment by olafura** [comment]
@fishcakez Thanks for the explanation ;)
