### ISSUE TITLE
How to run elixir mix app in detached mode

### ISSUE THREAD

**Issue by VJOfficial** [elixir-lang/elixir#4755]
Hello , i build api app using mix , elixir , how to run mix app in detached mode ? i tried --detached but api is not working. let me know if we have any command in mix or something else i need to add to configuration file or something. thanks in advance.

**Comment by eksperimental** [comment]
hi VJ, this is not the place for posting questions.
you may try luck with www.elixirforum.com 
or the mailing list elixir-lang-talk@googlegroups.com
