### ISSUE TITLE
Check for recursive imports in config files

### ISSUE THREAD

**Issue by chvanikoff** [elixir-lang/elixir#4757]
Currently, there are no checks in `import_config` and in case of recursive include like this `config.exs`:
```elixir
# this is contents of config.exs
use Mix.Config
import_config "config.exs"
```
iex will hang untill it gets to spawn_process limit:
```
11:04:27.347 [error] Too many processes


** (Mix.Config.LoadError) could not load config config/prod.secret.exs
    ** (SystemLimitError) a system limit has been reached
    :erlang.spawn_opt(:proc_lib, :init_p, [#PID<0.48.0>, [], :gen, :init_it, [:gen_server, #PID<0.48.0>, #PID<0.48.0>, Agent.Server, #Function<0.49473282/0 in Mix.Config.Agent.start_link/0>, []]], [:link])
    (stdlib) proc_lib.erl:330: :proc_lib.start_link/5
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:438: :erl_eval.expr/5
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:168: Code.eval_string/3
```

Expected behaviour is to throw an error immediately before reaching processes limit if such a recursion detected

**Comment by StevenXL** [comment]
Hello. I'd like to take on this issue please.

**Comment by josevalim** [comment]
Please go ahead! :D

**Comment by StevenXL** [comment]
Still working on this. Learning as I go. Getting a lot of help on IRC. No timeline for completion but if I think I won't be able to complete, I will update this issue so that others can feel free to take a look.

**Comment by whatyouhide** [comment]
Great @StevenXL, thanks for the update! 💟

**Comment by antipax** [comment]
@StevenXL I'm around on IRC if you have more questions, or we could pair on it some time over skype or something if you need some more help.
