### ISSUE TITLE
`mix compile` does not report invalid switches (as the 1.3 changelog suggests it should)

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#4768]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.0-rc.0 (7881123)
```
* Operating system:

OS X el capitan

### Current behavior

Running `mix compile --force --errors-as-warnings` ran without failing.

### Expected behavior

I meant `--warnings-as-errors` and mistyped it.  However, given the [Option Parser Integration](https://github.com/elixir-lang/elixir/blob/master/CHANGELOG.md#option-parser-integration) section of the changelog:

> Elixir v1.3 includes improvements to the option parser, including `OptionParser.parse!/2` and `OptionParser.parse_head!/2` functions that will raise in case of invalid or unknown switches. Mix builds on top of this functionality to provide automatic error reporting solving a common complaint where invalid options were not reported by Mix tasks.

...I expected it to tell me that `--errors-as-warnings` is not a valid switch.

**Comment by josevalim** [comment]
Mix compile won't be able to support this because it is a facade to multiple compilers, each bringing its own options. I will make it more explicit in the CHANGELOG but it won't be available to all tasks.

**Comment by josevalim** [comment]
Thank you for the report and for trying v1.3.0 :D

**Comment by josevalim** [comment]
The changelog is updated in master!
