### ISSUE TITLE
"nil" ({0, 0}) microsecond default

### ISSUE THREAD

**Issue by lau** [elixir-lang/elixir#4769]
In 1.3.0-rc.0 we get:
```
> ﻿%Time{hour: 0, minute: 0, second: 0}
** (ArgumentError) the following keys must also be given when building struct Time: [:microsecond]
    (elixir) expanding struct: Time.__struct__/1
             iex:2: (file)
```

Should microsecond default to `{0, 0}` ? For all the three types that have microseconds. We already have it as default for the sigil.

cc @josevalim

**Comment by josevalim** [comment]
Sounds good. We decided to not include it originally probably because of
precision but now it is explicit.

On Friday, June 3, 2016, Lau Taarnskov <notifications@github.com> wrote:

> In 1.3.0-rc.0 we get:
>
> > ﻿%Time{hour: 0, minute: 0, second: 0}
> ** (ArgumentError) the following keys must also be given when building struct Time: [:microsecond]
>     (elixir) expanding struct: Time.__struct__/1
>              iex:2: (file)
>
> Should microsecond default to {0, 0} ? For all the three types that have
> microseconds. We already have it as default for the sigil.
>
> cc @josevalim <https://github.com/josevalim>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4769>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbiHTN19sXl33Whi-b5_QmcWP8l8Nks5qII6dgaJpZM4It4ZE>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
