### ISSUE TITLE
`mix deps.compile app` is not force compiling the dependency

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#4770]
From docs:

```
By default, compile all dependencies. A list of dependencies can be given to
force the compilation of specific dependencies.
```

The force compilation does not work.

**Comment by ericmj** [comment]
It also doesn't seem to load dependencies:

```
~/code/hex_web λ mix deps.compile phoenix
==> phoenix
Compiling 60 files (.ex)

== Compilation error on file lib/phoenix/transports/websocket.ex ==
** (CompileError) lib/phoenix/transports/websocket.ex:51: module Plug.Conn is not loaded and could not be found
could not compile dependency :phoenix, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix", update it with "mix deps.update phoenix" or clean it with "mix deps.clean phoenix"
```

**Comment by josevalim** [comment]
Removed force. 

> It also doesn't seem to load dependencies:

This is explained in the docs. :)

**Comment by ericmj** [comment]
> Removed force.

I think we should have force compilation. If I change configuration for a dependency (for example `config :mime, :types`) I have to either `mix deps.clean` or delete directories from `_build/`. It's bad enough that I have to know I have to explicitly force recompilation after changing configuration so we should really try to make this straight-forward.

> This is explained in the docs. :)

Can you point me to those docs? I see docs about children not being compiled, but nothing about them not being loaded. Is this because we can't load deps without trying to compile them, if so it should be clarified? It really seems like a misfeature because it makes it impossible to compile dependencies that have compile time dependencies on their children.

**Comment by josevalim** [comment]
The dependencies should be loaded, they won't be loaded through if they haven't been previously compiled.
