### ISSUE TITLE
Regression in f957d2fb76a6206493feb451f1035b1ee9338dc1 breaks the `test_all` mix task in my umbrella project

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#4783]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.0-rc.0 (3b5bb5c)
```

(This is HEAD as of this morning).

* Operating system:

OS X El Capitan

### Current behavior

When I run `mix test_all` in my umbrella app, I get this error:

```
** (RuntimeError) trying to access Mix.Project.app_path for an umbrella project but umbrellas have no app
    (mix) lib/mix/project.ex:332: Mix.Project.app_path/1
    (mix) lib/mix/project.ex:353: Mix.Project.compile_path/1
    (mix) lib/mix/tasks/test.ex:187: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

This task is a custom one in our project ([which I proposed on the mailing list](https://groups.google.com/forum/#!searchin/elixir-lang-core/test_all/elixir-lang-core/8wX8i5sEtFg/zxJaYGFeDwAJ) at one point) which looks like this:

``` elixir
defmodule MyProject.Mixfile do
  use Mix.Project

  def project do
    [
      # ...
      test_paths: test_paths,
      preferred_cli_env: %{ test_all: :test },
      # ...
    ]
  end

  defp test_paths do
    "apps/*/test" |> Path.wildcard |> Enum.sort
  end
end

# `mix test` cd's into each app directory in sequence and runs the tests.
# `mix test_all` runs tests for all apps at the same time.
defmodule Mix.Tasks.TestAll do
  use Mix.Task
  @shortdoc "Runs all sub-app tests at once"
  defdelegate run(args), to: Mix.Tasks.Test
end
```

Using `git bisect` on the elixir repo, I tracked the problem down to f957d2fb76a6206493feb451f1035b1ee9338dc1.  On the parent commit (03039938e84771e72cdf3c42ee04ddf76a30a26e) it does not occur.

### Expected behavior

It should not fail in this manner.  Our `test_all` task worked on Elixir 1.2.x and on Elixir 1.3.0-rc.0.

**Comment by josevalim** [comment]
@myronmarston I am ok with fixing it BUT it is worth mentioning that the new --stale feature won't work with your test_all task. Do you still think it is worth keeping it?

**Comment by myronmarston** [comment]
> @myronmarston I am ok with fixing it BUT it is worth mentioning that the new --stale feature won't work with your test_all task. Do you still think it is worth keeping it?

That's good to know.   I've not used 1.3 yet (still haven't managed to upgrade our project to it...) so I don't have any experience with `--stale` in our workflow to see if it removes the need for `test_all`.  I expect `test_all` to still be useful at times, though.  For example, when upgrading Elixir (as I'm trying to do now) I want to be able to run all tests from all sub apps all at once, and `--stale` won't help in that situation.

**Comment by josevalim** [comment]
@myronmarston you can still use `mix test` to run all apps at once. ;)

Anyway, I will push a fix shortly, but I want to remind you that you have a workaround and we may not be able to support it on our side forever and ever. :) Specially now that the reason this is failing is because of the new `--stale` feature.

**Comment by antipax** [comment]
@myronmarston I think using `mix test --stale` would give you greater performance gains than running all of your test suites at once for the use case you describe.

**Comment by myronmarston** [comment]
> Anyway, I will push a fix shortly, but I want to remind you that you have a workaround and we may not be able to support it on our side forever and ever. 

What specifically are we doing that may not be supported?  We are:

* Defining a mix task the delegates to another one
* Setting `preferred_cli_env` to `test` for our custom task
* Overwriting `test_paths`

Which of these things is a work around/non-standard thing that may not be supported? They all seem like normal mix operations to me...

> @myronmarston I think using `mix test --stale` would give you greater performance gains than running all of your test suites at once for the use case you describe.

If everything is stale (because a universal dependency like elixir changed), then how would `mix test --stale` be faster?

Anyhow, TBH, the value I get out of `mix test_all` is less about the perf than about the output.  We have 40 apps in our umbrella app, and being able to run the tests for all of them and get the combined summary output for them all is very nice -- in contrast to having to scroll through pages of output from `mix test` running on each individual one.

**Comment by josevalim** [comment]
> Defining a mix task the delegates to another one

You are not supposed to call the `run/1` function of a Mix.Task directly. They should be invoked through the Mix API which will guarantee they are running in the proper environment, that aliases are run, that they are running recursively and so on. So if you wanted to delegate, you should use `Mix.Task.run "test", arg` but that would be recursive and you don't want that. :)

> Anyhow, TBH, the value I get out of mix test_all is less about the perf than about the output. We have 40 apps in our umbrella app, and being able to run the tests for all of them and get the combined summary output for them all is very nice -- in contrast to having to scroll through pages of output from mix test running on each individual one.

Oh, this is good to know!

**Comment by myronmarston** [comment]
> @myronmarston you can still use `mix test` to run all apps at once. ;)

Is there a mode that `mix test` supports to run all apps at the same time and provide a single summary report at the end of the results?  I've only ever seen `mix test` do the normal recursive approach of running `mix test` in the context of each app in turn, resulting in multiple pages of output for our umbrella app (which has 40 children, as I mentioned above).

If there is such a mode, I'd be keen to learn about it :).

**Comment by antipax** [comment]
@myronmarston Actually, now that I think about it `mix test --stale` wouldn't improve your use case, my bad. :) 

Forgot that we changed it so it would only start determining which tests are stale until until you have a totally successful test suite.

**Comment by myronmarston** [comment]
Thank you for the quick fix, @josevalim!

> You are not supposed to call the `run/1` function of a Mix.Task directly.

I had no idea!  It would be good to document this somewhere...but I'm not sure where it would go.

Anyhow, would you be open to Elixir providing out-of-the-box support for what we're achieving via `mix test_all` in Elixir 1.4?  Then you could stop supporting our work around :).

If you're open to Elixir supporting this out-of-the-box I'd be happy to work up a PR to add it.  I know this shouldn't be the default behavior of `mix test` (based on the earlier mailing list conversation) but perhaps an alternate task (e.g. `mix test_all`) or a flag (e.g. `mix test --combine-subapps`) would work well.

**Comment by josevalim** [comment]
> Anyhow, would you be open to Elixir providing out-of-the-box support for what we're achieving via mix test_all in Elixir 1.4? Then you could stop supporting our work around :).

I am more open to do this, certainly, but let's wait a bit further. If it gets to the point we can no longer support what you are doing, I would gladly introduce such a task.
