### ISSUE TITLE
Issue with Date.to_iso_8601! - no roundtrip compatibility 

### ISSUE THREAD

**Issue by tallakt** [elixir-lang/elixir#4784]
### Environment

* Elixir version (elixir -v): 
    Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]

    Elixir 1.3.0-rc.0 (5830699)

* Operating system:

Linux tallak-VirtualBox 3.16.0-71-generic #92~14.04.1-Ubuntu SMP Thu May 12 23:31:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Current behavior

    iex(2)> NaiveDateTime.to_iso8601(~N[2000-02-28 23:00:13.001])                      
    "2000-02-28T23:00:13.001"
    iex(3)> NaiveDateTime.to_iso8601(~N[2000-02-28 23:00:13.001]) |> Date.from_iso8601!
    ** (ArgumentError) cannot parse "2000-02-28T23:00:13.001" as date, reason: :invalid_format
        (elixir) lib/calendar.ex:220: Date.from_iso8601!/1

### Expected behavior

I expected the iso convertsion to work round-trip

**Comment by josevalim** [comment]
You are converting from NaiveDateTime to Date, I wouldn't expect a roundtrip there.
