### ISSUE TITLE
System.cmd's parallelism: true flag doesn't seem to work with whiptail or dialog

### ISSUE THREAD

**Issue by phipix01** [elixir-lang/elixir#4787]
I'm not 100% if this is a bug or me having it implemented wrong but given the existing documentation I couldn't think of another way to achieve this.

I'd like to display the stdout from programms like whiptail or dialog in the shell i executed the elixir script in.

### Environment
* Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
* Elixir 1.2.4
* Operating system: Ubuntu 16.04 4.4.0-22-generic

### Current behavior
```.ex
System.cmd "whiptail",
  ["--msgbox","title","20","20"],
  [into: IO.stream(:stdio, :line),
  parallelism: true]

System.cmd "dialog",
  ["--msgbox","title","20","20"],
  [parallelism: true,
  into: IO.stream(:stdio, :line)]
```
both display either whiptail or dialog but both either crash or end up with this weird behaviour:
![dialog ran from elixir](http://i.imgur.com/7KMLSFb.gif)
### Expected behavior
[_This function returns a tuple containing the collected result and the command exit status._](http://elixir-lang.org/docs/stable/elixir/System.html#cmd/3)

**Comment by josevalim** [comment]
@phipix01 does it work without parallelism: true?

**Comment by alco** [comment]
What is the expected behaviour? To me it looks like it's working as intended.

**Comment by phipix01** [comment]
@josevalim .. no doesn't work without parallelism either.
@alco I shouldn't have to abort the erlang vm. `whiptail` and `dialog` both crash after a few keystrokes or after a certain time waiting.
The behaviour is very inconsistent though sometimes they crash very early and sometimes I'm able to use it for some seconds. Also I noticed that if I redirect the `stderr` it's more likely to crash. 

I noticed that @jfreeze is experiencing the same in his [ex_curses](https://github.com/jfreeze/ex_ncurses) library.
> Testing ncurses inside an 'iex -S mix' console will fail to work after a few keystrokes.

I'll try if it works if I compile the file.

**Comment by josevalim** [comment]
I don't think System.cmd is going to work for your use case. What is happening is that you are writing the dialog output into stdout but all of the stdin still goes to Erlang and not dialog. Erlang echos what you type in back, resulting in the behaviour you described, nothing is really reaching dialog.

You can look into Ports (and the System.cmd) implementation to see if there is a way you can bypass the Erlang IO system and have the user IO connected directly to the Port but I don't think that's possible. I believe you will at least need to open your own port that captures stdin events and write it back to the Dialog application. Here is a one-liner that cycles over stdin printing everything:

```bash
$ elixir --erl "-noinput" -e "Port.open {:fd, 0, 1}, []; Stream.interval(100) |> Enum.each(fn _ -> receive do: (x -> IO.inspect x) end)"
```

Now write to the terminal and press enter and you will see the port messages echoed.
