### ISSUE TITLE
Logger console backend does not print metadata values when using default keys

### ISSUE THREAD

**Issue by zackehh** [elixir-lang/elixir#4799]
### Precheck

Disclaimer: I'm not 100% sure whether this is a core bug, a doc bug, or a misunderstanding (which I suppose may result in a doc bug).

### Environment

* Elixir version (elixir -v): 1.2.6
* Operating system: OS X 10.11

### Issue

The Logger [documentation](http://elixir-lang.org/docs/stable/logger/Logger.html) states the following about the `:console` backend:

> `:metadata` - the metadata to be printed by $metadata. Defaults to an empty list (no metadata)

Which is then followed by:

> In addition to the keys provided by the user via Logger.metadata/1, the following default keys are available in the `:metadata` list: (followed by a list of 5 keys)

This appears to be a contradiction. My guess would be that the first message is referring to *extra* metadata keys? If so, that might need to be clarified.

Regardless, I then tested this behaviour by trying to use `:module` metadata. At first, you can see that the metadata was ignored on the `:console` backend (`iex(2)`), which seems surprising considering the documentation says that `:module` is already recognised. 

```elixir
Interactive Elixir (1.2.6) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> require Logger
nil
iex(2)> Logger.warn("test", [ module: MyModule ])
11:52:22.895 [warn]  test
:ok
```

I then proceeded to adding that metadata key manually, via `Logger.configure_backend/2`. As shown below, it's then recognised... but something fails in the logging and it just uses a blank String for my value. I tried with both a Module, and a basic String, and neither work.

```elixir
iex(3)> Logger.configure_backend(:console, metadata: [ :module ])
:ok
iex(4)> Logger.warn("test", [ module: MyModule ]) 
11:52:47.181 module= [warn]  test
:ok
iex(5)> Logger.warn("test", [ module: "MyModule" ])
11:59:30.692 module= [warn]  test
:ok
```

I'm not entirely sure if this is a bug, or if it's due to misunderstandings from the documentation.

Further investigation showed that it appears to be something specific to the `:module` key (and maybe other pre-built ones). I tried the `:from` value and it prints just fine - so it seems like this is indeed a bug.

Thoughts appreciated!

**Comment by zackehh** [comment]
Ah, following up on this seems like it only occurs in `iex` - if I compile and run without an `iex` session, it logs correctly. 

So this seems like a bug, but less significant (maybe?).

**Comment by josevalim** [comment]
I will improve the docs to be clearer. It is also worth pointing out that you cannot really pass the module, as Logger automatically gets one for you, and in this case, because you are in IEx, there is no module. :)

**Comment by josevalim** [comment]
Thank you!
