### ISSUE TITLE
Repeated compilation does not produce identical beams

### ISSUE THREAD

**Issue by ulfurinn** [elixir-lang/elixir#4814]
Elixir 1.2.5, Erlang 18.3

Deleting `_build` and recompiling without any code changes does not produce identical beam files.

Looking closer, `:beam_lib.cmp file1, file2`, run on two beam files produced from the same source, returns `{:error, :beam_lib, {:chunks_different, 'Atom'}}`.

Looking at `:beam_lib.chunks file1, [:atoms]`, the atom order slightly varies between compilations. Some parts of the abstract code chunk also looked reordered (like function bodies in different places each time) but I didn't spend a lot of time analysing the differences there.

Consequently, the automatically generated module vsn is different each time, and appup generating tools like exrm will falsely pick it up as a changed module.

Is there something non-deterministic going on?

**Comment by josevalim** [comment]
@ulfurinn great catch. Since we are storing functions in an ETS table, which is non-ordered, I bet that's the source of non-determinism. I have just verified the report in Ecto and I will work on a fix soon.
