### ISSUE TITLE
Possible mistake in the Getting Started example for "Enumerables & Streams/Eager vs Lazy"

### ISSUE THREAD

**Issue by akitaonrails** [elixir-lang/elixir#4826]
I was trying this example from [this section](http://elixir-lang.org/getting-started/enumerables-and-streams.html#eager-vs-lazy) in the Getting Started guide:

```elixir
1..100_000 |> Stream.map(&(&1 * 3)) |> Stream.filter(odd?)
```

It blows the following error:

```
** (CompileError) iex:18: undefined function odd?/0
    (elixir) expanding macro: Kernel.|>/2
             iex:18: (file)
```

I think the correct example would be using the `Integer.is_odd` macro, wouldn't it?

```elixir
require Integer
1..100_000
  |> Stream.map(&(&1 * 3))
  |> Stream.filter(&(Integer.is_odd(&1)))
  |> Enum.sum
```

**Comment by josevalim** [comment]
Hi @akitaonrails! :D We did define the `odd?` function in the previous section: http://elixir-lang.org/getting-started/enumerables-and-streams.html#eager-vs-lazy

Maybe we should make it clearer?

**Comment by josevalim** [comment]
@akitaonrails I am closing this but please let me know if you think we can make it clearer. Thank you! :D

**Comment by akitaonrails** [comment]
Ah, sorry, you're right :-) I was copying this snippet to use in a presentation (I say it's from the getting started in the site), so without context it fails, but following step by step it does work. Not a bug, just out of context from my part indeed.
