### ISSUE TITLE
Investigate if "mix deps.get --only test" can only fetch test deps

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#4833]

**Comment by ericmj** [comment]
The underlying issue is that Mix will call Hex even if no Hex dependencies are defined for the given environment.

**Comment by ericmj** [comment]
@fishcakez Can you verify if this does what you wanted? I did not recall our conversation exactly.

**Comment by josevalim** [comment]
Looks good to me regardless!

**Comment by fishcakez** [comment]
This does seem to be what I wanted but of course I can't replicate the initial bug I hit because it was on old OTP/Elixir.
