### ISSUE TITLE
Assertion messages in 1.3 broke tests that previously worked in 1.2

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/elixir#4837]
It seems that assertion messages now get prepended with `\n\n` and appended with `\n`.

I'm not advocating for this to be reverted, however using `assert_raise` now means I have to wrap everything in those new lines. And that isn't expected as the actual assertion message I raise doesn't have them.

**Comment by josevalim** [comment]
Can you please provide a more detailed example? It is not obviously clear
from your report. Are you talking about the message from
ExUnit.AssertionError? If so it is worth pointing out there is no
compatibility guarantee in error messages as the goal is always to make
them as readable as possible. If you check Elixir v1.0 announcement it is
one of the examples. You can also pass regular expressions to assert_raise
for partial matches.

On Tuesday, June 21, 2016, Brian Cardarella <notifications@github.com>
wrote:

> It seems that assertion messages now get prepended with \n\n and appended
> with \n.
>
> I'm not advocating for this to be reverted, however using assert_raise
> now means I have to wrap everything in those new lines. And that isn't
> expected as the actual assertion message I raise doesn't have them.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4837>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbsnWeeJTMElTnrUZ7UrrX84n459Dks5qN--RgaJpZM4I6xaR>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by bcardarella** [comment]
@josevalim ah, didn't know about the regex. I'll just do that.
