### ISSUE TITLE
mix xref unreachable should return an error code

### ISSUE THREAD

**Issue by kevinastone** [elixir-lang/elixir#4839]
### Environment

* Elixir version (elixir -v):
```
kstone@kstone-mbp ~/D/requestbox> elixir -v
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.0
```

* Operating system:

OSX 10.11.5

### Current behavior
```
kstone@kstone-mbp ~/D/requestbox> mix xref unreachable
web/helpers/date.ex:5: Timex.DateFormat.format!/3
kstone@kstone-mbp ~/D/requestbox> echo $status
0
```
### Expected behavior

```
kstone@kstone-mbp ~/D/requestbox> mix xref unreachable
web/helpers/date.ex:5: Timex.DateFormat.format!/3
kstone@kstone-mbp ~/D/requestbox> echo $status
~0
```

**Comment by josevalim** [comment]
I disagree it should return an error code. It is performing static analysis and even though a warning is not an error. If you would like to get errors, I would suggest to use something like `mix compile.xref --warnings-as-errors`.

**Comment by josevalim** [comment]
Thank you for trying the new release out. :D

**Comment by kevinastone** [comment]
Is this a suggested implementation?  I'm fine with the flag (I just want this in my CI system).
```
kstone@kstone-mbp ~/D/requestbox> mix compile.xref --warnings-as-errors
kstone@kstone-mbp ~/D/requestbox> echo $status
0
```

**Comment by josevalim** [comment]
@kevinastone if you want that in your system, I would suggest enabling warnings as errors throughout the compiler. In your `mix.exs`, please add:

    elixirc_options: [warnings_as_errors: true]

**Comment by josevalim** [comment]
@kevinastone it is not a suggested implementation, it is implemented today and we have tests to check it indeed works :D Here is the source: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/compile.xref.ex#L27-L36 and here is the test: https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/mix/tasks/compile.xref_test.exs#L68-L77

**Comment by kevinastone** [comment]
👍 

(it wasn't re-compiling so I needed to `mix clean` first)
