### ISSUE TITLE
Inconsistency with unsafe assignment 

### ISSUE THREAD

**Issue by tuvistavie** [elixir-lang/elixir#4846]
Hi,
I am not sure what is the desirable behavior here, but the imperative assignment
introduced what I think is an inconsistency. Here is an example:

```elixir
case a = 1 do
  _ -> IO.puts(a)
end
# no problem
``` 

```elixir
case true && a = 1 do
  _ -> IO.puts(a)
end
# warning: the variable "a" is unsafe
```

I understand that this is a result of how the `case` is expanded internally, 
but from a user point of view, I think that the behaviors of these two expression should
be the same.

What do you think?

For the record, the code I was actually trying to upgrade to 1.3 looked something like this:

```elixir
some_id = Map.get(params, "some_id")
if some_id && (result = Repo.get_by(Model, some_id: some_id)) do
  # do something with result
end
```

and I had to look at how all this was expanded to understand what was happening.

**Comment by josevalim** [comment]
There is no inconsistency. When you do:

```elixir
case a = 1 do
  ...
end
```

There is no conditional assignment. `a` is effectively defined before the case, equivalent to:

```elixir
a = 1
case a do
```

However, when you do:

```elixir
true && a = 1
```

`a = 1` is the conditional assignment because of `&&`.

I have typically fixed those cases by rewriting it to:

    result = some_id && Repo.get_by(Model, some_id: some_id)

Although I understand that the mixture of `case` and `&&` may have made finding out the source of the actual warning tricky.

**Comment by tuvistavie** [comment]
I see, thank you for the explanation!
I found out the `with/else` form reads quite well for this case :smile:

**Comment by maxim** [comment]
@josevalim  I ran into a few of these, and had a question. Isn't it always safe to use this variable in the `if`, and always unsafe to use it in `else`? And therefore, shouldn't the warning only be produced if the variable is used in `else`?

```elixir
if a && (b = get(a)) do
  # b is always bound here
else
  # b should produce warning here
end
```

**Comment by tuvistavie** [comment]
I think it is safe, but it is indeed a conditional assignment,
so the warning is correct in that it is a conditional assignment, but
maybe a little misleading in this particular case as it is not really unsafe.
I am not sure if there is anything we could do to make this clearer.
