### ISSUE TITLE
xref warning not showing on recompilation

### ISSUE THREAD

**Issue by tuvistavie** [elixir-lang/elixir#4849]
### Environment

* Elixir version (elixir -v): Elixir 1.3.0
* Operating system: ArchLinux 4.6.2-1-ARCH

### Current behavior

`xref` compiler does not seem to emit any warning after the first compilation

### Expected behavior

I would expect warnings (if any) to be emitted each time a module is changed.

Sidenote: the `Compiling 1 file (.ex)` message does not show up either on recompilation,
 which I suppose is intended, but I am not sure.

### Steps to reproduce

1. Create a project: `mix new project`

2. Add some function

  ```elixir
  defmodule Project do
    def foo do
      String.lengthh("foo")
    end
  end
  ``` 

3. Compile with `mix compile`, it gives a warning
4. Modify the module, for example change `String.lengthh` to `String.lengths`
5.  Compile with `mix compile`, it does not give a warning

**Comment by josevalim** [comment]
I could not reproduce it. Given that you didn't see "Compiling 1 file", and you were supposed to, I am assuming you either forgot to save it OR Mix is failing to track changes somehow:

```
~/OSS/project$ mix compile
Compiling 1 file (.ex)
warning: function String.lengthh/1 is undefined or private
  lib/project.ex:3

Generated project app
~/OSS/project$ mix compile
Compiling 1 file (.ex)
warning: function String.lengths/1 is undefined or private
  lib/project.ex:3

~/OSS/project$
```

**Comment by josevalim** [comment]
Can you please double check?

**Comment by tuvistavie** [comment]
Sorry false alert, after trying with another editor,
it seems that my editor (Atom) is using atomic write,
or some kind of feature like this which is probably why mix did not pick up the changes.
I'll check how I can disable this Atom feature.

**Comment by tuvistavie** [comment]
Ok, I just understood what is going on.

For posterity, here is what happens with
a more or less standard Atom installation.

It has nothing to do with atomic write or whatsoever,
atom is just running `fs.writeFileSync` under the hood.

The issue was with the linter. The default settings of elixir-linter
uses `mix compile` and the project is therefore already
compiled when running `mix compile` from the terminal,
which explains the absence of output. 
Using the `always use elixirc` from the linter settings
solves the issue.

Sorry for the false alarm.
