### ISSUE TITLE
Elixir lexer for SynWrite+CudaText

### ISSUE THREAD

**Issue by Alexey-T** [elixir-lang/elixir#4850]
The lexer is made today, support for syntax hiliting, and basic support for Tree-panel (list of def's)
To install in Synwrite/Cudatext, -- AddonsManager.

Example of CudaText, with tree-panel

![eli](https://cloud.githubusercontent.com/assets/4154978/16268890/332c5138-38a1-11e6-9447-681d86799d66.png)

**Comment by josevalim** [comment]
Is this an issue or just a heads up that it is working? If so, congrats!

On Wednesday, June 22, 2016, Alexey T. <notifications@github.com> wrote:

> The lexer is made today, support for syntax hiliting, and basic support
> for Tree-panel (list of def's)
> To install in Synwrite/Cudatext, -- AddonsManager.
>
> Example of CudaText with Elixir file and tree-panel
>
> [image: eli]
> <https://cloud.githubusercontent.com/assets/4154978/16268890/332c5138-38a1-11e6-9447-681d86799d66.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4850>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbnbFllcK0M6yssqNChnjtGQeSIMfks5qOTyjgaJpZM4I7zE2>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by Alexey-T** [comment]
It is heads-up that it is new lexer.

**Comment by josevalim** [comment]
Perfect, thank you!
