### ISSUE TITLE
Allow protocols to work with opaque types

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#4853]
@benwilson512 reported an interesting dialyzer error from ecto:
```
The call 'Elixir.Ecto.Queryable':to_query('Elixir.Ecto.Query':t()) 
contains an opaque term as 1st argument when a structured term of type 
atom() | bitstring() | fun() | pid() | port() | reference() | maybe_improper_list() | number() | tuple() | map() 
is expected
```

And it makes sense, because protocol is defined externally to the module with opaque type and relies on the internal structure for dispatch.
On the other hand often the protocol implementations are conceptually part of the module that defines the type.

@fishcakez proposed to define `@dialyer :no_opaque` in `defprotocol`

**Comment by fishcakez** [comment]
> On the other hand often the protocol implementations are conceptually part of the module that defines the type.

I disagree with this, `defimpl` is defined outside a module defining the struct.

**Comment by ericmj** [comment]
> I disagree with this, defimpl is defined outside a module defining the struct.

The unfortunate effect of this is that there is no way to define a protocol implementation for an opaque types. And you can also get cases where the distinction is less clear since you define an implementation inside the module with the opaque. I realize that to erlang and dialyzer there is no such thing as nested modules.

**Comment by fishcakez** [comment]
@ericmj hence the suggestion to add `@dialyzer :no_opaque` to protocol modules, then if `defimpl` uses an opaque the protocol will not create a warning for the protocol. The implementation would then need to manually use `@dialyzer :no_opaque`

**Comment by michalmuskala** [comment]
Is adding the attribute to the protocol module and documenting how to make it work for implementations enough? Or is something more needed here?

**Comment by fishcakez** [comment]
@michalmuskala that's enough yes, please go ahead if you like.

**Comment by michalmuskala** [comment]
As discussed yesterday on IRC, I tried implementing a fix for the dialyzer warning, but it seems we can't remedy this. The warning is issues at the place the protocol function is called, and not inside the protocol. 
I think this can be closed.

**Comment by fishcakez** [comment]
@michalmuskala can we check there aren't any other warnings before closing. For example dispatching to an an opaque implementation does not cause warnings after consolidation.

**Comment by fishcakez** [comment]
Doesn't appear to be anything we can do here, except to suggest using `@dialyzer {:no_opaque, [fun: arity]}` where appropriate.
