### ISSUE TITLE
binary-size(struct.property) causes compile error

### ISSUE THREAD

**Issue by KallDrexx** [elixir-lang/elixir#4858]
### Environment

* Elixir version (elixir -v): 1.3.0 (Erlang/OTP 18)
* Operating system: Windows

### Current behavior

````
Eshell V7.2.1  (abort with ^G)
Interactive Elixir (1.3.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule Test, do: defstruct value: 5
{:module, Test,
 <<70, 79, 82, 49, 0, 0, 8, 252, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 0, 186,
   131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115,
   95, 118, 49, 108, 0, 0, 0, 4, 104, 2, ...>>, %Test{value: 5}}
iex(2)> instance = %Test{}
%Test{value: 5}
iex(3)> <<x::binary-size(instance.value)>> = <<1,2,3,4,5>>
** (CompileError) iex:3: size in bitstring expects an integer or a variable as argument, got: instance.value()
    (elixir) src/elixir_bitstring.erl:52: :elixir_bitstring.expand_bit_info/5
    (elixir) src/elixir_bitstring.erl:29: :elixir_bitstring.expand_bitstr/4
    (elixir) src/elixir_bitstring.erl:10: :elixir_bitstring.expand/3
iex(3)> int = instance.value
5
iex(4)> <<x::binary-size(int)>> = <<1,2,3,4,5>>
<<1, 2, 3, 4, 5>>
````

### Expected behavior

I would expect a struct's property value to work just the same as a variable (line 3 should react the same as line 4)

**Comment by josevalim** [comment]
It is working as expected. Although you could say you could simply
precompiled the variable in this example, it wouldn't be that
straight-forward to do so in case and it would make matching more
expensive. So you need to be explicit and pre calculate it. We should
improve the error message though to say "a literal integer" for clarity.

On Thursday, June 23, 2016, Matthew Shapiro <notifications@github.com>
wrote:

> Environment
>
>    - Elixir version (elixir -v):
>    - Operating system: Windows
>
> Current behavior
>
> Eshell V7.2.1  (abort with ^G)
> Interactive Elixir (1.3.0) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)> defmodule Test, do: defstruct value: 5
> {:module, Test,
>  <<70, 79, 82, 49, 0, 0, 8, 252, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 0, 186,
>    131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115,
>    95, 118, 49, 108, 0, 0, 0, 4, 104, 2, ...>>, %Test{value: 5}}
> iex(2)> instance = %Test{}
> %Test{value: 5}
> iex(3)> <<x::binary-size(instance.value)>> = <<1,2,3,4,5>>
> ** (CompileError) iex:3: size in bitstring expects an integer or a variable as argument, got: instance.value()
>     (elixir) src/elixir_bitstring.erl:52: :elixir_bitstring.expand_bit_info/5
>     (elixir) src/elixir_bitstring.erl:29: :elixir_bitstring.expand_bitstr/4
>     (elixir) src/elixir_bitstring.erl:10: :elixir_bitstring.expand/3
> iex(3)> int = instance.value
> 5
> iex(4)> <<x::binary-size(int)>> = <<1,2,3,4,5>>
> <<1, 2, 3, 4, 5>>
>
> Expected behavior
>
> I would expect a struct's property value to work just the same as a
> variable (line 3 should react the same as line 4)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4858>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbt-JsoqRmFLydrjScnpiT4nRqrY1ks5qOf6tgaJpZM4I8bJP>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
