### ISSUE TITLE
Update Elixir's Unicode support to Unicode 9.0

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#4864]
On 21 June(as of writing, two days ago), [version 9.0](http://www.unicode.org/versions/Unicode9.0.0/) of the Unicode standard [was released](http://blog.unicode.org/2016/06/announcing-unicode-standard-version-90.html). 

This added some new scripts, both in current use and historic, some new emojis and also the [IEEE1621 Power Symbol](http://unicodepowersymbol.com/we-did-it-how-a-comment-on-hackernews-lead-to-4-%C2%BD-new-unicode-characters/)
### Current behavior

Elixir adheres to version 8.0 of the Unicode standard.
### Expected behavior

Elixir adheres to version 9.0 of the Unicode standard.

**Comment by felipesere** [comment]
I'd give this a go if I can get some minimal instructions :)

**Comment by josevalim** [comment]
@felipesere sorry but I would prefer to handle this one personally. :)

**Comment by felipesere** [comment]
Sure

**Comment by Qqwy** [comment]
:heart_eyes: Thank you, José!
