### ISSUE TITLE
URI.encode doesn't escape #

### ISSUE THREAD

**Issue by martinos** [elixir-lang/elixir#4875]
### Environment

* Elixir version (elixir -v): Elixir 1.3.0

* Operating system: OS X El Capitan

### Current behavior

    iex(3)> URI.encode("http://example.com/file#1.pdf")
    "http://example.com/file#1.pdf    

### Expected behavior

I think it would be better if `#` was escaped like the Ruby URI.encode function.

    ex(3)> URI.encode("http://example.com/file#1.pdf")
    "http://example.com/file%231.pdf"

**Comment by josevalim** [comment]
The behaviour of URI.encode is well specified. It will by default escape all non-reserved and non-unreserved characters according to RFC 3986. You can change the behaviour by passing a function to `URI.encode`.
