### ISSUE TITLE
mix.copy() does not work on folders if there is a dot in the directory name

### ISSUE THREAD

**Issue by anik786** [elixir-lang/elixir#4892]
### Environment

* Elixir version (gulp elixir -v):
```
[15:33:06] CLI version 1.2.1
[15:33:06] Local version 3.9.1
```

* Operating system: Windows 10 Home

### Current behaviour

I have found that if I use elixir on a directory that contains a dot, it will only copy the folder, but not the contents inside.

For example consider copying a folder called `public/a.something` at the root of the project:

```
exlixir(function(mix) {
    mix.copy('a.something', 'public/a.something');
});
```

The above will only make an empty directory called `a.something` and not copy its contents.

On the other hand the following works fine if the folder is called `a`:

```
exlixir(function(mix) {
    mix.copy('a', 'public/a');
});
```

### Expected behaviour

It should have copied the entire folder as well as the contents within it.

**Comment by whatyouhide** [comment]
You're probably talking about [this](https://github.com/laravel/elixir), not Elixir the programming language :) You can open an issue on https://github.com/laravel/elixir probably.

**Comment by anik786** [comment]
Apologies. Feel a bit stupid now!

**Comment by whatyouhide** [comment]
@anik786 no problem, it happens to everyone :D

**Comment by eksperimental** [comment]
They also have something called "mix"?!
Actually thats the first line u see in their getting started guide
https://laravel.com/docs/5.1/elixir#introduction

```
elixir(function(mix) {
    mix.sass('app.scss')
       .coffee('app.coffee');
});
```

What a coincidence

**Comment by anik786** [comment]
I know lol. That's why I was confused!
