### ISSUE TITLE
Add some useful functions to string module

### ISSUE THREAD

**Issue by Chicker** [elixir-lang/elixir#4898]
Some times ago, in google elixir group discussed a possibility of adding some additional functions for working with strings and symbols. Here is the link to this discussion:

[link to discussion in elixir google group](https://groups.google.com/forum/#!searchin/elixir-lang-core/unicode/elixir-lang-core/DU-_euhvVk0/1wqDwgWgBAAJ)

I also consider that these functions very useful when manipulating with strings and chars. Many languages has these functions in stdlib.

* is_lower?
* is_upper?
* is_digit?
* is_control?
* is_whitespace?

I re-wrote some functions in "unicode.ex" that is allowed not only to add these features, but also reduce the file size of beam files to 26,5 Kb.

I made ref to PR.

**Comment by josevalim** [comment]
Closing in favor of the PR.
