### ISSUE TITLE
:elixir_tokenizer.tokenize column info and numbers with embedded underscores

### ISSUE THREAD

**Issue by mikestok** [elixir-lang/elixir#4907]
### Environment

* Elixir version (elixir -v): Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace] Elixir 1.3.0
* Operating system: Darwin ratdog-2.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

### Current behavior

I'm working on an improvement to `credo` and its checking of long numbers, and to do this I want to be able to get back to the original source which created the number token so that I can tell if it was written as decimal, hex, binary, or octal in the source.

I have code like this:

```elixir
defmodule X do
  def parts(string) do
    string
    |> String.to_charlist
    |> :elixir_tokenizer.tokenize(1, [])
    |> (fn({:ok, _, _, token_list}) -> token_list end).()
    |> Enum.map(&(extract_source(&1, string)))
  end

  defp extract_source({type, tuple, _}, source), do: extract_source({type, tuple}, source)
  defp extract_source({_, {_, start_pos, next_pos}}, source) do
    String.slice(source, start_pos - 1, next_pos - start_pos)
  end
end
```

I would expect it to get the original bits of the source for each token, and mostly it does, until we put some `_` into the number then it seems like the columns returned with the tokens get out of sync by the number of `_` characters we have added:

```elixir
iex(1)> "def f(x), do:  10000 + x * 2" |> X.parts
["def", "f", "(", "x", ")", ",", "do:", "10000", "+", "x", "*", "2"]
iex(2)> "def f(x), do:  10_000 + x * 2" |> X.parts
["def", "f", "(", "x", ")", ",", "do:", "10_00", " ", " ", " ", " "]
iex(3)> "def f(x), do:  10_0_00 + x * 2" |> X.parts
["def", "f", "(", "x", ")", ",", "do:", "10_0_", "0", "+", "x", "*"]
```
### Expected behaviour

I would expect it to get the original bits of the source for each token, so the last two `iex` results would be:

```elixir
iex(2)> "def f(x), do:  10_000 + x * 2" |> X.parts
["def", "f", "(", "x", ")", ",", "do:", "10_000", "+", "x", "*", "2"]
iex(3)> "def f(x), do:  10_0_00 + x * 2" |> X.parts
["def", "f", "(", "x", ")", ",", "do:", "10_0_00", "+", "x", "*", "2"]
```

I *think* that this is because in `lib/elixir/src/elixir_tokenizer.erl` this code discards the `_`:

```erlang
%% Check if we have an underscore followed by a number;
tokenize_number([$_, H | T], Acc, Bool) when ?is_digit(H) ->
  tokenize_number(T, [H | Acc], Bool);
```

and later we use `length(Acc)` as the character count (so it doesn't include the `_`s):

```erlang
%% Cast to float...
tokenize_number(Rest, Acc, true) ->
  {Rest, list_to_float(lists:reverse(Acc)), length(Acc)};

%% Or integer.
tokenize_number(Rest, Acc, false) ->
  {Rest, list_to_integer(lists:reverse(Acc)), length(Acc)}.
```

It also affects the column information returned for binary, octal, hex, and floating point numbers in the source.

**Comment by josevalim** [comment]
@mikestok the tokenizer is private API. We won't provide any guarantees about its return values. :)
