### ISSUE TITLE
Force disable warnings_as_errors for dependencies

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#4913]
Warnings as errors causes more harm than good when it's enabled for dependencies. We should disable it for both the elixir and erlang compilers.

For makefiles we already added the `IS_DEP=1` env var to disable it for erlang.mk. I will investigate how to do it for rebar3, I've got some ideas from the rebar3 team already. With mix we, of course, have full control over the options.

**Comment by josevalim** [comment]
I have fixed this for mix too. So just rebar/rebar3 left. :)

**Comment by josevalim** [comment]
@ericmj and i am almost sure you can do it for rebar3 by using overrides?

**Comment by josevalim** [comment]
This is pending a new Rebar 3 release.

**Comment by ericmj** [comment]
Reopening to remind me of updating `mix local.rebar`.

**Comment by skalmus** [comment]
@ericmj Sorry for bothering in a 1 year old closed issue. 😄 
How I can run `mix compile` filtering at all the deps warnings?

**Comment by ericmj** [comment]
You can't filter deps warnings and this by design so that you will not be surprised when your deps break when you update elixir.
