### ISSUE TITLE
Doc for String.replace/4 is messed because of escape character \

### ISSUE THREAD

**Issue by sunboshan** [elixir-lang/elixir#4914]
Not sure if this is a bug of `ExDoc` or `Elixir`, but in the doc for [String.replace/4](http://elixir-lang.org/docs/master/elixir/String.html#replace/4), the last part of the example is messed because of the escape character `\` in the doc in the following sentence.

    Notice we had to escape the escape character `\`.

When run `mix docs`, it emits warning

    Closing unclosed backquotes ` at end of input

A simple workaround would be changing the above sentence to:

    Notice we had to escape the escape character `\ `.

This will fix the warning and the doc.

**Comment by whatyouhide** [comment]
Thanks for the report @sunboshan. I am not sure but I suspect the bug is in [Earmark](https://github.com/pragdave/earmark) (the Markdown parser used by ExDoc) because I would expect

```
`\\`
```

To be turned into a backslash in monospaced font if

```
`\`
```

is considered as an escaped backtick. But the weird thing is that the backslash is displayed correctly in the docs (in monospaced font and all), but then everything goes south (and we have the warnings about unclosed backticks).

Let's ping @RobertDober here for advice? In the meantime, we can always replace "the escape character `\`" with "the escape character backslash".

**Comment by RobertDober** [comment]
pong @whatyouhide ;)
There is definitely a bug in the markdown 
```
    `\`    
```
opens a backtick and does not *close* it.

However when I tested with the fixed version
```
   `\\`
```
it still does not work, so there is a bug in Earmark too!
I'll open an issue soon. Thank you both for the report.

**Comment by whatyouhide** [comment]
Yep, as I suspected. Thanks for the swift reply @RobertDober. @josevalim if you approve, I can push the "backslash" instead of `\` fix so that docs work fine again for now.

**Comment by josevalim** [comment]
Please go ahead Andrea.

On Thursday, June 30, 2016, Andrea Leopardi <notifications@github.com>
wrote:

> Yep, as I suspected. Thanks for the swift reply @RobertDober
> <https://github.com/RobertDober>. @josevalim
> <https://github.com/josevalim> if you approve, I can push the "backslash"
> instead of \ fix so that docs work fine again for now.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-lang/elixir/issues/4914#issuecomment-229729638>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbuYESTdLx1FXBGj18eUnPbX_1zPaks5qQ_xOgaJpZM4JCS30>
> .
>


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
Solved for now in https://github.com/elixir-lang/elixir/commit/4ba0c6c16a122c269c592096165240979d979cea, please @RobertDober ping us when this will be solved in Earmark and we can use a new version in ExDoc so we'll bring the actual `\` back (which I definitely prefer over the word "backslash").

**Comment by RobertDober** [comment]
@whatyouhide I am a little bit confused here. Yes we get a warning, however the generated HTML does look correct. 
```iex
iex(11)> Earmark.to_html "a `\\` v"
<no file>:1: warning: Closing unclosed backquotes ` at end of input
"<p>a <code class=\"inline\">\\</code> v</p>\n"
```

**Comment by whatyouhide** [comment]
@RobertDober yes but the following generated text gets all screwed up and code blocks don't show up as code blocks anymore.

**Comment by RobertDober** [comment]
@whatyouhide Oh boy, almost missed the whole point of the issue. Thanx a lot.

**Comment by RobertDober** [comment]
@whatyouhide  have resolved the issue and am waiting for the release by @pragdave
