### ISSUE TITLE
Document :sys in the GenServer module and possibly provide a custom install handler

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4918]
/cc @fishcakez

**Comment by michalmuskala** [comment]
Should this describe the whole concept of special processes, system messages, etc?

**Comment by josevalim** [comment]
No, I don't think it should talk about special process but system messages, we can focus on log and trace as a starter.

**Comment by michalmuskala** [comment]
Wouldn't this be better as a separate page? This could get quite a lot of text. As a separate page you could also easily reference it from other places.

**Comment by josevalim** [comment]
I am not sure. I don't oppose the idea but I am also not sure it deserves its own page. It is meant to be a quick reference. The actual page is in the erlang docs.

**Comment by michalmuskala** [comment]
I'll write something and we'll see how it will work out. Moving some text around is not a big problem, writing it is.

**Comment by josevalim** [comment]
Closing in favor of the PR.
