### ISSUE TITLE
Support mix test --listen-to-stdin

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4919]
The idea of this flag is that it will automatically listen to stdin after running the tests. For now, if enter is pressed, tests will automatically re-run. This can be powerful when combined with `--stale` or when receiving input from another unix command.

**Comment by josevalim** [comment]
Useful gist: https://gist.github.com/josevalim/a5e747c90a72e40a4b52062ea6919877

**Comment by antipax** [comment]
Ok for me to grab this?

**Comment by josevalim** [comment]
Please do! :D I hope it is straight-forward to implement. I believe it is mostly a matter of documentation on how to use it with `--stale` and make it clear any text from stdin will be accepted to trigger a restart.
