### ISSUE TITLE
Return value of OptionParser.parse!/2 and OptionParser.parse_head!/2 differ from their counterparts without exclamation point

### ISSUE THREAD

**Issue by robi-wan** [elixir-lang/elixir#4935]
### Environment

```
$ elixir -v
Erlang/OTP 18 [erts-7.3] [64-bit] [smp:8:8] [async-threads:10]

Elixir 1.3.1
```
* Operating system:
Windows 7 Professional 64bit 

### Current behavior

The number of element in the returned tuples differ:

```
$ iex
Eshell V7.3  (abort with ^G)
Interactive Elixir (1.3.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(2)> OptionParser.parse([])
{[], [], []}
iex(3)> OptionParser.parse!([])
{[], []}
iex(4)> OptionParser.parse_head([])
{[], [], []}
iex(5)> OptionParser.parse_head!([])
{[], []}
iex(6)>
```
### Expected behavior

The number of the elements in the returned tuples are the same. This behavior is also described in the documentation.

I think [this commit](https://github.com/elixir-lang/elixir/commit/91aa29d1b47a110572b45bb846453a87fac519b7) introduced this behavior.

**Comment by antipax** [comment]
First of all, thanks for opening this issue!

As I see it, the spec for `parse_head!` is indeed incorrect (it should be the same as the spec for `parse!`), but the specs for `parse_head`, and both versions of `parse` seem to be correct.

The third element in the non-! versions contains the errors that occurred during parsing, and so for the ! versions (which raise in case of errors) this element would always be empty if the function returns. Thus the ! versions should indeed only return 2 element tuples.

**Comment by josevalim** [comment]
Yes, we should fix the specs. The current behaviour is correct. :)

**Comment by robi-wan** [comment]
I see that the docs were recently updated in commit https://github.com/elixir-lang/elixir/commit/1498c423e3d9e8d39d2a4af77e49ee2d8bf1b48c.

I docs for elixir 1.3.1 still mention the three-element tuple for the !-versions: 
* [parse!/2](http://elixir-lang.org/docs/stable/elixir/OptionParser.html#parse!/2)
* [parse_head!/2](http://elixir-lang.org/docs/stable/elixir/OptionParser.html#parse_head!/2)

I used pattern matching on the result of parse/2 and was surprised that I got a MatchError after calling parse!/2. Obviously there is no need for the error list in parse!/2 and parse_head!/2.

**Comment by antipax** [comment]
@robi-wan This is what I see for `parse!` at the link you provided:

```elixir
parse!(argv, options) ::
  {parsed, argv} |
  no_return
```

which looks correct to me? Are you seeing something different?

**Comment by robi-wan** [comment]
This is correct. I also see this spec.
But the text below reads:

> If there weren’t any errors, returns a three-element tuple as follows:
> 
> 1. parsed options,
> 2. remaining arguments,
> 3. empty list.

**Comment by antipax** [comment]
Ah, ok. Definitely an issue then! :)

**Comment by josevalim** [comment]
@robi-wan the docs and specs are out of date, the code is correct. Sorry about that, can you send a PR fixing both?

**Comment by whatyouhide** [comment]
So I noticed the wrong typespec in `parse_head!/2` and decided to fix that, ended up in the rabbit hole of fixing all the docs in https://github.com/elixir-lang/elixir/pull/4924 and forgot the spec 😄 I took care of the specs in https://github.com/elixir-lang/elixir/commit/d75cad62db54cde517d60897836f78a58884172d and had already took care of the docs in #4924, so everything should be a-ok @robi-wan :)

**Comment by robi-wan** [comment]
@whatyouhide Wow - that was fast! Thanks!
Could you also 'backport' these changes to branch v1.3?

**Comment by whatyouhide** [comment]
@robi-wan doing that exactly right now :) Thanks for bringing this up! 💟
