### ISSUE TITLE
Access behaviour callbacks are missing documentation

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#4937]
### Environment

* Elixir version (elixir -v): v 1.4 (and earlier)

### Current behavior

The documentation of Elixir's Access behaviour [does not include information](http://elixir-lang.org/docs/stable/elixir/Access.html#callbacks) on how the callbacks should be implemented. 

### Expected behavior

It would be better if this were properly documented. Right now, the only way to find out how to implement `fetch`, `get`, `pop` and `get_and_update` is by looking closely at the specs, the source code of the Access module where the callbacks are called and the implementations for Map and Keyword.

__________

I faced this problem yesterday evening while trying to implement a vector/matrix library. After deep-diving the source, I now understand how the Access callbacks are supposed to work, so if you want I can pick this issue up myself.

**Comment by whatyouhide** [comment]
@Qqwy if you want to send a PR, that would be great! 😃 Otherwise, I can take care of it if you prefer. 💟

**Comment by Qqwy** [comment]
All right! expect a PR for this this evening.

**Comment by lexmag** [comment]
Closed in #4939.
