### ISSUE TITLE
Missing typespecs for String.replace_{prefix,suffix,leading,trailing}/3

### ISSUE THREAD

**Issue by sunboshan** [elixir-lang/elixir#4943]
The latest [doc](http://elixir-lang.org/docs/master/elixir/String.html#replace_leading/3) doesn't have typespecs for 

```
String.replace_prefix/3
String.replace_suffix/3
String.replace_leading/3
String.replace_trailing/3
```
which should be `String.replace_xxx(t, t, t) :: t` or `String.replace_xxx(t, pattern, t) :: t`. I think it's the first one but I'm not 100% sure..

**Comment by josevalim** [comment]
Thank you @sunboshan! Since we do not guarantee we will provide them, I am going to close this issue but, if anyone is interested in providing one, pull requests are welcome. I believe they should be indeed `String.replace_xxx(t, t, t)` as they do not allow binary patterns.

**Comment by sunboshan** [comment]
Thanks @josevalim for explaining! And thanks @whatyouhide for adding it!
