### ISSUE TITLE
mix test fails on umbrella applications with "database does not exist"

### ISSUE THREAD

**Issue by chrisfishwood** [elixir-lang/elixir#4955]
### Environment

* Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
* Elixir 1.4.0-dev (cbe0398)

* OSX 10.11.5

### Current behavior
`mix test` will fail (database does not exist) when run from the parent project of an umbrella application with 2 or more applications if it has not been run for each application first.  `mix test` from the parent project with only one sub application will succeed.

Simple example project here: [https://github.com/chrisfishwood/mix_test_umbrella](https://github.com/chrisfishwood/mix_test_umbrella).

![screen shot 2016-07-06 at 10 44 43 pm](https://cloud.githubusercontent.com/assets/5195704/16643637/5b33bf38-43cb-11e6-99f5-3c7f81de9009.png)

### Expected behavior

I would expect `mix test` to run successfully from the parent directory after creating new sub-applications without first having to run `mix test` for each sub-application.

**Comment by josevalim** [comment]
This is a bug in Ecto. When you run Mix.Task.run "ecto.create" in the first application, it marks the task as run, so when the second application comes in it won't re-run the task. One fix is to replace the calls to `Mix.Task.run` in your test helper by `Mix.Task.rerun`. Although updating to Ecto 2.0 is recommended as it takes a different approach on this. If you build a new app with phoenix v1.2 you can see such example.

**Comment by chrisfishwood** [comment]
Awesome. Thanks for the quick reply! 🍻
