### ISSUE TITLE
Notation for capture \N is not consistency in String.replace/4 and Regex.replace/4

### ISSUE THREAD

**Issue by sunboshan** [elixir-lang/elixir#4975]
In latest [doc](http://elixir-lang.org/docs/master/elixir/String.html#replace/4) for `String.replace/4`, it uses `\N` to refer to a specific capture.

    ... one can give \N or \g{N} in the replacement string ...
     
    Notice we had to escape the escape the backslash escape character...

While in latest [doc](http://elixir-lang.org/docs/master/elixir/Regex.html#replace/4) for `Regex.replace/4`, it uses `\\N` to refer to a specific capture. 

    ... to be accessed via \\N or \g{N}, where N is the capture. In case \\0 is used...

It used to use `\N` for both places, until [this commit](https://github.com/elixir-lang/elixir/commit/a0753a68731a9a9d297c2e78f8c0f1f1e80c8889) change the latter to `\\N`.

So is it fine to use two notations in two places? Or is it better to make them consistency?

**Comment by josevalim** [comment]
Great catch. It is a little bit tricky. The correct is `\N` but because `\` is escaped, `\\N` is what you will see in most strings. Maybe we should use `\N` but mention we need to use `\\N` because of the escape character.

**Comment by sunboshan** [comment]
Thanks!

Ping @whatyouhide since he changed wording for `String.replace/4` in a recent [commit](https://github.com/elixir-lang/elixir/commit/4ba0c6c16a122c269c592096165240979d979cea). Note there might be a typo in the current [doc](http://elixir-lang.org/docs/master/elixir/String.html#replace/4) for `String.replace/4`

    Notice we had to escape the escape the backslash escape character.

Might be

    Notice we had to escape the backslash escape character.

**Comment by whatyouhide** [comment]
Great catch @sunboshan, thanks for the ping and sorry it took me a while to get back to you :) I opened #4998 to hopefully fix this 👍
