### ISSUE TITLE
Syntax highlight for Regex.split/3's Example is messed

### ISSUE THREAD

**Issue by sunboshan** [elixir-lang/elixir#4976]
In the latest [doc](http://elixir-lang.org/docs/master/elixir/Regex.html#split/3) for `Regex.split/3`, the syntax highlight for Example section is messed due to using slash `/` as delimiter for sigil_r

    ~r/-/

A simple work around would be using other delimiters, such as

    ~r{-}

However there might be some other bug causing this issue.

**Comment by josevalim** [comment]
Yes, let's change it so it looks nice on the syntax highlight.

**Comment by michalmuskala** [comment]
I often like to use `~r"-"` when the regex does not involve quotes itself.

**Comment by eksperimental** [comment]
sweet, we've been dealing for ages with this bug
