### ISSUE TITLE
Deprecate Enum.partition in favor of Enum.split_with

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4996]
Enum.partition should be soft-deprecated. Which means we will add a `@doc false` and leave a TODO so we can emit warnings on version 1.5 or later.

The reason for the renaming is that `GenStage` will introduce a particular meaning to partitions which we want to avoid mixing up with `Enum.partition`.

**Comment by whatyouhide** [comment]
I can tackle this.

**Comment by josevalim** [comment]
All yours!

**Comment by tsubery** [comment]
Instead of ```@doc false``` we can mention this function has been renamed. It would have saved me few minutes of confusion.

**Comment by josevalim** [comment]
That's a good point. Because right now we don't warn as well, so it is clearly hard to know its purpose. @whatyouhide, @lexmag: in the future, let's keep the docs around until we add a warning (no need to revisit stuff we have already deprecated though).

**Comment by imlcl** [comment]
Just find this...
