### ISSUE TITLE
Release v1.3.2

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#4999]
* [x] Confirm with @myronmarston and @wojtekmach they haven't see further issues in umbrella apps
* [x] Confirm with @mobileoverlord he hasn't seen any further issues with Nerves
* [x] Confirm with @ericbmerritt support for Nix works
* [x] Investigate exdoc issue on Erlang 19: https://github.com/elixir-lang/ex_doc/issues/580

**Comment by mobileoverlord** [comment]
confirmed. v1.3 head is working as expected.

**Comment by myronmarston** [comment]
Confirm that I haven't seen any new issues with our umbrella app.  I also just compiled HEAD of the `v1.3` branch and will use it today and report back if I see any issues.

Note, however, that I have still periodically seen the issue I reported in #4842, but when it happens I'm not quite sure if the elixir I had just run is `v1.3.1` or my locally compiled elixir out of the v1.3 branch.  One issue is that `elixir -v` reports `1.3.1` even when I am running against an elixir compiled against a later commit in that branch -- which means that I am unable to tell from `elixir -v` if it's actually 1.3.1 or if it's 1.3.1-plus-extra-fixes.  @josevalim would it be possible to include the SHA in the `elixir -v` output when compiled against a commit that is not exactly at that tag?  That would help me differentiate.

**Comment by wojtekmach** [comment]
Looks good on my end, I tested it on both v1.3 head and recent v1.4-dev.

Btw, I just posted this on ML: https://groups.google.com/forum/#!topic/elixir-lang-talk/6O8DwVkzICE, it's probably not a bug (hence ML) but it was related to my experiments with umbrella that lead me to reproduce the bug in #4842.

**Comment by ericmj** [comment]
@myronmarston The bug is that https://github.com/elixir-lang/elixir/blob/v1.3/VERSION was not bumped to `1.3.2-dev` after `v1.3.1` was tagged.

**Comment by josevalim** [comment]
@myronmarston I have bumped the version file and that can help. Alternatively, you can also run this `elixir -e "IO.inspect System.build_info"` and that will give a bit more information.

**Comment by myronmarston** [comment]
Good to know, thank @josevalim.  No problems yet with the version I compiled this morning.
