### ISSUE TITLE
Regression on GenServer handle_call :timeout

### ISSUE THREAD

**Issue by heri16** [elixir-lang/elixir#5003]
### Environment

* Elixir version (elixir -v): 1.2.5
* Operating system: Windows 8.1

### Current behavior

In a GenServer, I had made sure that all the handle_call function clauses return {:noreply, state, :infinity}.
Even so, a ":timeout" message is sent to the GenServer process after 30 seconds, resulting in handle_info(:timeout, state) being called.

### Expected behavior
Since the timeout is :infinity, there should not be any :timeout message.

According to the Elixir docs:

Returning {:reply, reply, new_state, timeout} is similar to {:reply, reply, new_state} except handle_info(:timeout, new_state) will be called after timeout milliseconds if no messages are received.

Returning {:noreply, new_state, timeout} is similar to {:noreply, new_state} except handle_info(:timeout, new_state) will be called after timeout milliseconds if no messages are received.

**Comment by josevalim** [comment]
@heri16 can you please provide the source code of your GenServer? I have just tried locally and I could not reproduce it:

```iex
iex(1)> defmodule Sample do
...(1)> use GenServer
...(1)> def handle_call(:ok, _from, state) do
...(1)> {:reply, :ok, state, :infinity}
...(1)> end
...(1)> def handle_info(msg, state) do
...(1)> IO.inspect msg
...(1)> {:noreply, state, :infinity}
...(1)> end
...(1)> end
{:module, Sample,
 <<70, 79, 82, 49, 0, 0, 10, 64, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 2, 57,
   131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115,
   95, 118, 49, 108, 0, 0, 0, 4, 104, 2, ...>>, {:handle_info, 2}}
iex(2)> {:ok, pid} = GenServer.start_link Sample, :ok
{:ok, #PID<0.72.0>}
iex(3)> GenServer.call(pid, :ok)
:ok

# Nothing was printed after 30 seconds

# Now let's check noreply
iex(4)> send pid, :try_handle_info
:try_handle_info
:try_handle_info
```

After 30 seconds nothing was printed in both cases.

**Comment by heri16** [comment]
Apparently one of my handle_info was returning {:noreply, new_state, 30_000}.

Missed that because the documentation of handle_info/2 is missing the part about timeouts.

**Comment by josevalim** [comment]
The docs for `handle_info/2` currently refer to `handle_cast/2` so we don't repeat all information. The typespec though still mentions the timeout return.

**Comment by heri16** [comment]
Apologies, must have been the lack of coffee over an overnight sprint.
