### ISSUE TITLE
Support a :label option in IO.inspect/2

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#5009]
As discussed in [this thread](https://groups.google.com/forum/#!topic/elixir-lang-core/iCaUDS6IEiY) in the elixir-lang-core mailing list.

`IO.inspect/2` will now accept a `:label` option (a binary) to inspect values with a small label before:

```elixir
iex> IO.inspect([1, 2, 3])
[1, 2, 3]
[1, 2, 3]
iex> IO.inspect([1, 2, 3], label: "a list")
a list: [1, 2, 3]
[1, 2, 3]
```

The return value of `IO.inspect/2` will remain unchanged.

@michalmuskala is working on this.

<strike>I wonder, maybe `:label` is a better name for this option? `:tag` looks a bit too generic maybe 😕 </strike> We went with `:label` :)

**Comment by michalmuskala** [comment]
I like `tag` because it's short, which is important in case of a debugging utility.

**Comment by whatyouhide** [comment]
I think two characters are still very ok though, with more clarity that this is just a visual thing (tag always makes me think of more complicated/general stuff). Let's wait for other opinions? 😃

**Comment by josevalim** [comment]
:+1: for tag.

**Comment by lexmag** [comment]
I really like `:label` (we also refer to such thing as label in `ExUnit.Formatter` code). :bowtie:

**Comment by Troush** [comment]
I prefer ':label', elixir uses 'tag' a lot in different context than "Marking stuff". (in 'ExUnit' like example).

**Comment by whatyouhide** [comment]
I think we've got more votes for `:label` then? 😄 @josevalim what shall we do? :)

**Comment by josevalim** [comment]
`:label` is fine so we don't further overload `:tag`.
