### ISSUE TITLE
Docs and typespec for Kernel.get_and_update_in/3 don't mention :pop

### ISSUE THREAD

**Issue by Sgeo** [elixir-lang/elixir#5013]
### Environment

* Elixir version (elixir -v): Elixir 1.3.1

### Current behavior

No mention of `:pop` in  `Kernel.get_and_update_in/3`'s typespec or documentation.

### Expected behavior

It seems like `Kernel.get_and_update_in/3` is intended to allow a "get and update" function to pop, by emitting `:pop` instead of a `{get, update}` tuple. This is documented in `Access.get_and_update/3`

This should be documented and typespeced.

**Comment by whatyouhide** [comment]
Thanks for the report @Sgeo! :) Do you want to submit a PR for this, or should I take care of it? :)
