### ISSUE TITLE
String.replace_leading leads to infinite recursion

### ISSUE THREAD

**Issue by nrio0** [elixir-lang/elixir#5019]
`String.replace_leading("foo", "", "")`

should return "foo", but instead it runs forever.
Tested with elixir version 1.3. and Erlang version 19.0.

**Comment by whatyouhide** [comment]
Same happens for `String.replace_trailing/3` btw.

**Comment by wobh** [comment]
Hah! Nice catch!

Looks like there's no null-case testing in either `String.replace_leading/3` or the private function `String.replace_leading/6`. The latter could detect when `prefix_size` and `suffix_size` are both 0 and return the string. Likewise with `String.replace_trailing/3`.
