### ISSUE TITLE
Enum.slice/2-3 correct documentation regarding negative indexes

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#5023]
####  Enum.slice/2
- [ ] We need to correct docs examplaining how using non-valid indexes will return in `[]` .
originally discussed here https://github.com/elixir-lang/elixir/pull/5017#issuecomment-233183078

Currently we have:
>   If the start of the range is not a valid index for the given enumerable or if the range is in descending order, it returns `[]`.

there are two cases where this is not true.
where range is `1..-1` (still valid)
and `-1..1`, ascending order, and it will return `[]`

####  Enum.slice/3
We need to
- [ ] Correct the typespec to be `@spec slice(t, index, non_neg_integer) :: list`
- [ ] Explain that is `start` is out of bounds, it will return `[]`

**Comment by eksperimental** [comment]
for  Enum.slice/2 @josevalim [suggested](https://github.com/elixir-lang/elixir/pull/5017#issuecomment-233183167)
> I think we should explain how indexes are normalized and then say that the normalized indexes must be such in a way that end >= start.

**Comment by whatyouhide** [comment]
@eksperimental will you submit a PR for this or should we take care of it?

**Comment by eksperimental** [comment]
Give me two days. If i am not able to submit anything, please take care of it
