### ISSUE TITLE
"with" suppresses unused variable warnings

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#5024]
The code below doesn't produce any warnings when compiled with Elixir v1.3.2.

```elixir
defmodule Warn do
  def foo() do
    with :ok <- :ok do
      foo = 1
      bar = 2
      baz = 3
    end
  end
end
```

Not all warnings are suppressed. For example, the following code

```elixir
# lib/warn.ex
defmodule Warn do
  def foo() do
    with :ok <- :ok do
      foo = 1
      bar = 2
      baz = 3
      1 / 0
    end
  end
end
```

produces this output

```
$ mix compile
Compiling 1 file (.ex)
warning: this expression will fail with ArithmeticError
  lib/warn.ex:7
```

**Comment by josevalim** [comment]
This is a consequence of how safe/unsafe variables work in Elixir. This won't emit warnings either:

```elixir
defmodule Warn do
  def foo() do
    case :ok do
      :ok ->
        foo = 1
        bar = 2
        baz = 3
    end
  end
end
```

There are two ways for us to fix this. 1. Emit the unused variable warnings ourselves or 2. Wait until we unify the scoping rules (something we have already started but we will able to finish effectively on 2.0 only). I believe it makes more sense to wait until Elixir v2.0.

**Comment by alco** [comment]
I've just upgraded to Elixir v1.3.4 and it found a bug in our code, in a gen server's init:

```elixir
def init(...) do
  case foo(state) do
    {:ok, state} ->
      s = bar(state)
      ...
      {:ok, state}
    ...
  end
end
```

Elixir v1.3.3 didn't warn about the unused variable `s`, v1.3.4 does.

Both examples from the earlier discussion here now also emit warnings on v1.3.4. Does this mean the issue is resolved?

**Comment by josevalim** [comment]
@alco beautiful. I optimized the compiler to emit less intermediate variables and apparently we fixed this bug in the process.

@lexmag also spotted the fix and is writing a test. So I will move the milestone to v1.4.0 and assign it to @lexmag. He can close the issue once he pushes the test. :)
