### ISSUE TITLE
Calling :erlang.apply on macros fails

### ISSUE THREAD

**Issue by walkr** [elixir-lang/elixir#5034]
Dynamically calling a function on the Logger module as in the code below

```elixir
:erlang.apply(Logger, :error, ["There was an error"])
```

fails with the following error message: 

```shell

** (UndefinedFunctionError) function Logger.error/1 is undefined or private. Did you mean one of:

      * error/1
      * error/2

    (logger) Logger.error("There was an error")

```

Is this expected, and if it is could someone please explain why it's the expected behavior?

Thanks!

**Comment by josevalim** [comment]
Macros are not functions, you cannot apply them at runtime nor invoke them dynamically. There is a function called `Logger.bare_log` that can be used for this purpose.
