### ISSUE TITLE
mix hex.outdated in umbrella projects

### ISSUE THREAD

**Issue by TBK145** [elixir-lang/elixir#5035]
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: Ubuntu 14.04

### Current behavior

When using `mix hex.outdated` in an umbrella project it shows the dependencies of all sub-projects, but we have some dependencies (ex_doc, credo) defined in the root mix.exs. This mix file is not listed in the output of `mix hex.outdated`.

**Comment by josevalim** [comment]
Please file the issue on github.com/hexpm/hex. The task should probably not be marked as recursive. :)
