### ISSUE TITLE
Quote suppresses unused variable warnings

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#5040]
Elixir v1.3.2:

```elixir
defmodule QuotedWarn.Template do
  defmacro __using__(_opts) do
    quote do
      def foo(unused) do
        :ok
      end
    end
  end
end

defmodule QuotedWarn do
  use QuotedWarn.Template
end
```

```
$ mix compile
# no warnings
```

**Comment by josevalim** [comment]
Yes, this one is by definition. A lot of times the generated code itself may end-up emitting warnings and it doesn't make sense to go through hops and tailing the code generation. That's also one of the many reasons to avoid generating a lot of code inside quote. :)

**Comment by alco** [comment]
This should be mentioned in the docs. The only place in `quote`'s documentation where the word "warning" is mentioned is in the Options section:

> `:generated` - marks the given chunk as generated so it does not emit warnings. Currently it only works on special forms (for example, you can annotate a `case` but not an `if`)

and I'm not really sure what exactly this option does. Does it suppress all kinds of warnings? How does it related to the default behaviour of suppressing unused variable warnings?
