### ISSUE TITLE
Integer.digits/2 doc is confusing with Ruby 2.4 changes

### ISSUE THREAD

**Issue by dalexj** [elixir-lang/elixir#5046]
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/integer.ex#L70

```elixir
      iex> Integer.digits(101)
      [1, 0, 1]
```

Ruby 2.4 is adding `int#digits`, which has a different behavior than elixir's version

Ruby's version reverses the digits `123.digits # => [3, 2, 1]`, while elixir's doesn't. The docs use the number `101` which makes it confusing as to what elixir's does - reversing it or not. Please change to not use a palindrome number

**Comment by antipax** [comment]
Thanks for the report! I agree the example would be improved by using a non-palindromic number, but I would also like to note that the docs do currently state that it returns the "ordered digits."

**Comment by eksperimental** [comment]
thank you for the report @dalexj. Do you feel like submitting a PR, or should I take care of it?

**Comment by dalexj** [comment]
you can go ahead and take it
