### ISSUE TITLE
@moduledoc and @typedoc accept charlists as input

### ISSUE THREAD

**Issue by keathley** [elixir-lang/elixir#5049]
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: OS X 10.11.6

### Current behavior

Currently `@moduledoc` and `@typedoc` accept a charlist as input while `@doc` throws a `FunctionClauseError`:

```elixir
defmodule ExampleModule do
  @moduledoc '''
  This is an example module
  '''

  @typedoc '''
  Example type
  '''
  @type t :: String.t

  @doc '''
  Function doc
  '''
  def foo do
  end
end
```

```
$ elixir example.ex
** (FunctionClauseError) no function clause matching in Module.add_doc/6
    (elixir) lib/module.ex:552: Module.add_doc(ExampleModule, 11, :def, {:foo, 0}, [], 'Function doc\n')
    (elixir) lib/module.ex:986: Module.compile_doc/6
```

### Expected behavior

Based on conversations on IRC it seems that `@moduledoc` and presumably `@typedoc` should reject charlists as input the same way that `@doc` does.

**Comment by whatyouhide** [comment]
I can look at this one.
