### ISSUE TITLE
Undefined struct value memory leak

### ISSUE THREAD

**Issue by Troush** [elixir-lang/elixir#5056]
### Environment

* Elixir version (elixir -v): `1.3 / master`
* Operating system: `ubuntu 16.04`

### Current behavior

When you define module with struct and functions that return this struct, you can set undefined value for a struct, that causes process to freeze and consume all the memory it can.
Code:
```
defmodule SrtuctMemoryLeak do
  defstruct id: 0, test: "value"
  def test do
    %StructMemoryLeak{id: 0, test: test}
  end
end
```
### Expected behavio
```
** (CompileError) iex:1: undefined function test/0
```

I will try tackle this.
P.S. Maybe related to #5053, but I am not sure.

**Comment by antipax** [comment]
You are calling the function `test/1` for the value of `test` within the function `test/1`, so you are producing an infinite recursion.

**Comment by Troush** [comment]
@antipax Still, this is not valid behavior.

**Comment by antipax** [comment]
@Troush can you explain why you think this is not valid behavior? Unless you have figured out a solution to the halting problem, I'm not sure there is anything the compiler can do here. :)

**Comment by Troush** [comment]
Okay, I am closing this :+1: 
Late night stupidity, sorry lads.

**Comment by antipax** [comment]
@Troush happens to all of us! :) ❤️

**Comment by josevalim** [comment]
@Troush it is valid behaviour. That's how a GenServer works: it calls the same function over and over again recursively. Basically you are writing this:

```elixir
def test do
  test()
end
```

I think the real bug is that you intended to write a variable and it ended-up being a function call. :) Luckily we have a warning for it on master. :bowtie:

**Comment by Troush** [comment]
I will tell the whole story behind this, to maybe explain the thinking, that ended up here :)

I have production code that looks like.
```
defmodule Example do
  defstruct id: 0, test: :atom
  def same do
    %Example{id: 0, type: :same}
  end
end
```
And miss typed, and `:same` become `same`. Get machine freeze couple of times, then fixed this. But totally lost context that `:same` is a function name. And it ends up here.
Busy day, sorry again :)
