### ISSUE TITLE
Contrinituitive behaviour of `import` - it uses least set of imported functions

### ISSUE THREAD

**Issue by asiniy** [elixir-lang/elixir#5072]
### Environment

* Elixir version (elixir -v): 1.3.1
* Operating system: Ubuntu 14.04

### Current behavior

Let's suppose I have a code like that (this is the real code):

``` elixir
defmodule MyApp.MyModel do
  use MyApp.Web, :model # => which contains `import Ecto.Changeset` in its `__using__`
  use EctoStateMachine # => which contains `import Ecto.Changeset, only: [cast: 4, add_error: 3]` in its `__using__`.

  def changeset(model, params) do
    model
    |> cast(params, @fields) # line number n
  end
end
```

Surprisingly (for me), I have a compilation error here: `undefined method cast/3 on line number n`. I fixed that by [this commits](https://github.com/asiniy/ecto_state_machine/commit/79fefc736c4532ca81f53e83cd5277a0491951ab), which removed `only: [cast: 4, add_error: 3]` from EctoStateMachine. But it looks a little bit contrintuitively - why elixir relies to the `import` with the least set of imported functions?

I think it should import the maximum set. It will looks better by design. Isn't it?

**Comment by josevalim** [comment]
In my opinion the opposite would be counter-intuitive. If I am asking to import only `cast: 4`, why is `cast: 3` still around? Furthermore, if we always imported the maximum, then you would never be able to remove imports.

Also, I don't understand why EctoStateMachine is even importing changeset functions into the user codebase. You should the import to ouside of the quote. It will keep the same behaviour but not affect the user code semantics.

**Comment by asiniy** [comment]
@josevalim but you are asking to import everything in another part of code, isn't it?

Yeah, `EctoStateMachine` implementation still isn't clean, but I'm improving it

**Comment by josevalim** [comment]
> @josevalim <https://github.com/josevalim> but you are asking to import
everything in another part of code, isn't it?

Which is now being overwritten. Is like setting up an alias, the last one
is going to prevail.
>
>

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
