### ISSUE TITLE
Better documentation for binary pattern matching

### ISSUE THREAD

**Issue by TreyE** [elixir-lang/elixir#5076]
Currently the syntax and specifiers for binary pattern matching in elixir are hard to find extensive documentation for - you have to dig into the comments provided in the actual Erlang source for Elixir.

### Current behavior

Right now I have to read the Erlang source in order to find a full specification and examples.

### Expected behavior

This documentation should be available in either the Elixir docs or the language manual.

**Comment by josevalim** [comment]
Full specification can be found here: http://elixir-lang.org/docs/stable/elixir/Kernel.SpecialForms.html#%3C%3C%3E%3E/1

Or by typing `h <<>>` in your terminal. If you believe this is not enough, please let us know the specific aspects of the docs we can improve.

**Comment by TreyE** [comment]
Nope - this is precisely what I was looking for - don't  know why I missed it.

Thanks!
