### ISSUE TITLE
Realize swapcase function

### ISSUE THREAD

**Issue by yaBliznyk** [elixir-lang/elixir#5079]
I read how works functions upcase and downcase and try to think how to realize function swapcase.

```
  # Swapcase

  def swapcase(string), do: swapcase(string, "")

  for {codepoint, upper, lower, _title} <- codes, lower && upper do
    if lower != codepoint do
      defp swapcase(unquote(codepoint) <> rest, acc) do
        swapcase(rest, acc <> unquote(lower))
      end
    else
      defp swapcase(unquote(codepoint) <> rest, acc) do
        swapcase(rest, acc <> unquote(upper))
      end
    end
  end

  defp swapcase(<<char, rest::binary>>, acc) do
    swapcase(rest, <<acc::binary, char>>)
  end

  defp swapcase("", acc), do: acc
```

I down known how to test it. Is this code working?  If it is, may you insert it in codebase?

**Comment by lexmag** [comment]
Hi @yaBliznyk, Elixir's issue tracker is reserved for bug reports, https://elixirforum.com would be preferred place for such questions.
Regarding feature proposal, please use elixir-core mailing list.
Thank you.

**Comment by yaBliznyk** [comment]
Thank you very much, i go to mailing list!
