### ISSUE TITLE
ArgumentError stacktrace in ExUnit.Case.test does not include source line

### ISSUE THREAD

**Issue by dplummer** [elixir-lang/elixir#5083]
An `:erlang.apply` ArgumentError in an `ExUnit.Case.test` doesn't include the stacktrace line of the actual error, just the line where the test was defined.

### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: Mac OS X 10.11.5 (15F34)

### Current behavior

```elixir
defmodule AsserttestTest do
  use ExUnit.Case

  test "apply" do
    things = [%{}]

    things.foo
    assert true == true
  end
end
```

```
$ mix test

  1) test apply (AsserttestTest)
     test/asserttest_test.exs:4
     ** (ArgumentError) argument error
     stacktrace:
       :erlang.apply([%{}], :foo, [])
```

### Expected behavior

Stacktrace would include the line with the error, being line 7 of the test file.

**Comment by fishcakez** [comment]
Fix brewing in #5116.

**Comment by fishcakez** [comment]
My bad #5116 does not handle this.

**Comment by michalmuskala** [comment]
#5116 would fix this if there was a previous stack entry. It looks like that the test executes in a new process so the stack is empty when the mocked entry for bad call is added. 

What would be a fix? Ensure that we're not calling the test in the tail position, so we have proper stack info?

**Comment by josevalim** [comment]
Fixed in master.
