### ISSUE TITLE
Sytax errors from 'make test' command originating from src file

### ISSUE THREAD

**Issue by aidanSoles** [elixir-lang/elixir#5090]
### Environment

* Erlang version: Erlang R16B03 (erts-5.10.4) [source] [64-bit] [async-threads:10] [kernel-poll:false]
* Elixir version (elixir -v): 1.4.0-dev (grabbed from GitHub: 'elixir: command not found')
* Operating system: Linux Mint 17.3 Rosa (VirtalBox VM)

### Current behavior

$ git clone https://github.com/elixir-lang/elixir.git # No error messages.

$ make clean test
cd lib/elixir && "/home/aidan/prog_files/elixir/rebar" clean
==> elixir (clean)
rm -rf ebin
rm -rf lib/*/ebin
rm -rf lib/elixir/test/ebin
rm -rf lib/*/tmp
rm -rf lib/mix/test/fixtures/git_repo
rm -rf lib/mix/test/fixtures/deps_on_git_repo
rm -rf lib/mix/test/fixtures/git_rebar
rm -rf lib/elixir/src/elixir.app.src
make clean_man
make[1]: Entering directory `/home/aidan/prog_files/elixir'
rm -f man/elixir.1
rm -f man/iex.1
make[1]: Leaving directory `/home/aidan/prog_files/elixir'
==> elixir (compile)
Compiled src/elixir_parser.yrl
src/elixir.hrl:13: syntax error before: '{'
src/elixir_def_defaults.erl:7: syntax error before: '{'
src/elixir_def_defaults.erl:3: function expand/2 undefined
ERROR: compile failed while processing /home/aidan/prog_files/elixir/lib/elixir: rebar_abort
make: *** [erlang] Error 1

$ make clean
cd lib/elixir && "/home/aidan/prog_files/elixir/rebar" clean
==> elixir (clean)
rm -rf ebin
rm -rf lib/*/ebin
rm -rf lib/elixir/test/ebin
rm -rf lib/*/tmp
rm -rf lib/mix/test/fixtures/git_repo
rm -rf lib/mix/test/fixtures/deps_on_git_repo
rm -rf lib/mix/test/fixtures/git_rebar
rm -rf lib/elixir/src/elixir.app.src
make clean_man
make[1]: Entering directory `/home/aidan/prog_files/elixir'
rm -f man/elixir.1
rm -f man/iex.1
make[1]: Leaving directory `/home/aidan/prog_files/elixir'

$ make test
==> elixir (compile)
Compiled src/elixir_parser.yrl
src/elixir.hrl:13: syntax error before: '{'
src/elixir_def_defaults.erl:7: syntax error before: '{'
src/elixir_def_defaults.erl:3: function expand/2 undefined
ERROR: compile failed while processing /home/aidan/prog_files/elixir/lib/elixir: rebar_abort
make: *** [erlang] Error 1

### Expected behavior

Forgive me if this is a dumb installation issue--I am a newbie. Basically, when I try to 'make clean test' in UNIX I get the following issue. I already followed the steps for the #3035 bug fix (https://github.com/elixir-lang/elixir/issues/3035) but the build still fails. I am not sure why this is happening, and I really want to get learning so any help is much appreciated! Also, please let me know if I can be more descriptive in my error report.

**Comment by ericmj** [comment]
You need to update your Erlang version. You are using R16 and 18.0 or later is needed.

It seems this commit https://github.com/elixir-lang/elixir/commit/f524f25c58169da28ce0d17fb7235932bb043c9a broke the version checker for versions <17.0.
