### ISSUE TITLE
Doctest 'opaque type' regular expression is too restrictive

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#5103]
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: Linux Mint

### Current behavior

This is sort of a follow-up on #5100.

I followed the documentation on DocTests outlined [here](http://elixir-lang.org/docs/stable/ex_unit/ExUnit.DocTest.html#module-opaque-types), which states that opaque types are matched specially, because they start with a `#` (and these are also used inside doctests to create explanatory comments).

However, even with the inspect-format of the vectors and matrices changed slightly so they follow the  `#Name<...>`-format and editing the example code changed so opaque types and non-opaque types are no longer used interchangeably, it still does not work:

```
      iex> mat = Matrix.new([[1,2],[3,4]], 2,2)   
      iex> {vector, mat2} = Tensor.pop(mat, 0)   
      iex> vector
      #Vector<(2)[1, 2]>
      iex> mat2
      #Matrix<(2×2)
      ┌                 ┐
      │       0,       0│
      │       3,       4│
      └                 ┘
      >
``` 

This has as output:
```
  1) test doc at Tensor.pop/3 (1) (TensorTest)
     test/tensor_test.exs:3
     Doctest failed
     code: mat = Matrix.new([[1,2],[3,4]], 2,2)   
            {vector, mat2} = Tensor.pop(mat, 0)   
            vector === #Vector-(2)[1, 2]
     lhs:  #Vector-(2)[1, 2]
     stacktrace:
       lib/tensor.ex:156: Tensor (module)
```

Therefore, I started digging in the source code of ExUnit.

It turns out that [on line 592 in the DocTest module](https://github.com/elixir-lang/elixir/blob/v1.3.2/lib/ex_unit/lib/ex_unit/doc_test.ex#L592) there exists a Regular Expression that checks for the special case of coming across an opaque type:

```
~r/^#[A-Z][\w\.]*<.*>$/
```

This regular expression:

- does not match unicode characters.
- does not match multi-line inspect results.

### Expected behavior

An altered regular expression is used ,which _does_ allow for the two cases mentioned above. An example would be:

```
~r/\A#[A-Z][\w\.]*<(.|\n)*>\n?\z/um
```
_(This also allows for the case where a multi-line inspect is constructed using heredocs (`"""`), which add a final `\n` at the end)_

**Comment by Qqwy** [comment]
The only way to make these kind of values work with doctests right now, is to use `inspect(matrix)` and wrap the result in `"..."`. This degrades the quality of the examples, because it of course is not what a user should do in their terminal.

**Comment by josevalim** [comment]
If you would like to send a PR we would appreciate it. The regex can definitely be improved but I also think it could be simpler. I would say all we care is what it starts with `~r/\A#[A-Z][\w\.]*</u`. I don't think we need to care about the rest.

**Comment by Qqwy** [comment]
Yes, I agree. I will create a PR tomorrow. (It's nearly midnight over here right now).

Do we actually care about the `<` in there? I can totally understand cases where an opaque inspect would not use `<...>`. 
Or is there then the problem of matching things that are actually comments?

**Comment by josevalim** [comment]
> Or is there then the problem of matching things that are actually comments?

Precisely. I would require the `<`.
