### ISSUE TITLE
IEx: `r Kernel` searches for source path of computer that originally compiled Elixir

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#5104]
### Environment

* Elixir version (elixir -v): 1.3.1, 1.3.2, possibly 1.4
* Operating system: Linux Mint; OSX.

### Current behavior

When doing `r Kernel` from inside IEx, you get the following result:

```
** (ArgumentError) could not find source (/Users/jose/OSS/elixir/lib/elixir/lib/kernel.ex) for module: Kernel
    (iex) lib/iex/helpers.ex:370: IEx.Helpers.do_r/1
    (iex) lib/iex/helpers.ex:356: IEx.Helpers.r/1
```
This is when using the Elixir version (1.3.2) that was built with the `asdf` version manager.

```
(ArgumentError) could not find source (/home/vagrant/build-dir_16-06-29_09-47-40/elixir_1.3.1-1/lib/elixir/lib/kernel.ex) for module: Kernel
```
This is when using Elixir (1.3.1 in this case) loaded from the [erlang-solutions.com](https://www.erlang-solutions.com/resources/download.html) APT package repository. (As mentioned by DeadTrickster on IRC)

```
** (ArgumentError) could not find source (/private/tmp/elixir-20160715-41149-dywkfu/elixir-1.3.2/lib/elixir/lib/kernel.ex) for module: Kernel
```
This is when using Elixir 1.3.2 from brew on OSX. (As mentioned by David Antaramian)

When building Elixir from source, it indeed refers to the file inside my own home directory, and works without problems. (Confirmed for 1.3.2 and master,  the upcoming 1.4)

I have not tested other kinds of Elixir distributions; David Antaramian confirmed that the same happens on the asdf-version on OSX.

### Expected behavior

This is a good question. What do we expect here? Above behaviour is understandable, but a little bit weird, and in any case undesirable in a pre-built version of Elixir. We might want to show a nicer error on failing to reload the Kernel in these cases.

**Comment by josevalim** [comment]
I don't think there is something we can do here. You effectively do not have the source for that module. What would you add to the error message? We cannot guess that the reason is that it is precompiled because maybe you just changed directories of your Elixir source.

**Comment by Qqwy** [comment]
That is a good question. There probably isn't any difference between a locally-built version of Elixir and a built-and-packaged version of Elixir that can be seen from within. Hmm...

What we might maybe ask instead is: How useful is `r Kernel`?

**Comment by josevalim** [comment]
@Qqwy it is useful if you are working against Elixir. Why would you reload `Kernel` though if you haven't changed it locally? You need to have the Elixir source in your machine and have compiled from it.

I believe we are doing what is correct here. Shall we close this? :)

**Comment by Qqwy** [comment]
It is... a bit weird, and I don't like that you're able to see a path of someone else's computer this way, but I guess there is no way around it.

Thank you for your support :-)

**Comment by eksperimental** [comment]
I agree with you @Qqwy, and I have faced this earlier.
from a privacy point of view I think this is a bug,
If i compile elixir and distribute it, it should not save in the binaries the path it was compiled from in my local system.
