### ISSUE TITLE
ExUnit.Server hard-coded timeout limit of 60_000msec

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#5110]
### Current situation

ExUnit.Server has a hard-coded timeout value of 60_000 which appears to be the cause of one of my complex test cases timing out with:

```elixir
15:09:18.053 [error] Task #PID<0.147.0> started from #PID<0.70.0> terminating
** (stop) exited in: GenServer.call(ExUnit.Server, {:take_async_cases, 1}, 60000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:604: GenServer.call/3
    (ex_unit) lib/ex_unit/runner.ex:71: ExUnit.Runner.loop/2
    (stdlib) timer.erl:166: :timer.tc/1
    (ex_unit) lib/ex_unit/runner.ex:13: ExUnit.Runner.run/2
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &ExUnit.run/0
```

In my example I am using sample data to generate test cases similar to the following - since the sample data is several thousands items, generating the test cases takes more than 60_000 on all my machines.  Indeed the tests never start executing - the ExUnit.Server timeout hits before generating all the cases.  I have validated that the tests generate and execute correctly if I narrow the scope of sample data.

### Preferred situation

Either increase the hardcoded timeout, or provide a means to configure it.

**Comment by josevalim** [comment]
Yes, we can definitely provide a way to configure it. I never thought someone would hit it. :)

**Comment by Maikon** [comment]
Is this not solved using the `:timeout` tag? https://github.com/elixir-lang/elixir/blob/96da837136e13a5d599e8d1bbcb87f2b4675e861/lib/ex_unit/lib/ex_unit/case.ex#L134

**Comment by josevalim** [comment]
The :timeout tag is per test. Those refer to the inner working of ExUnit (before the test even starts running, for example).

**Comment by Maikon** [comment]
Gotcha. Thanks for the clarification :-)

**Comment by JGulbronson** [comment]
I wouldn't mind taking a look at this, as long as no one's started on it yet. Have been using Elixir at work lately, and would love to give back. Let me know and I'll get started!

**Comment by josevalim** [comment]
@JGulbronson please go ahead. The idea is to have a configuration in the application environment called server_timeout and use it in both places where we use `@timeout` in ExUnit code base. :)
