### ISSUE TITLE
Reverse line in token matching error message

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5122]
The following code:

```elixir
defmodule Foo do {
end
```

Raises:

    ** (SyntaxError) iex:2: unexpected token: "end". "{" starting at line 1 is missing terminator "}"

However, since most of the causes are likely to be closer at line 1, I believe we should reverse it to:

    ** (SyntaxError) iex:1: "{" is missing terminator "}". unexpected token: "end" at line 2. 

Thoughts?

**Comment by ottolin** [comment]
I think the suggested message looks more natural since users will usually scan the error message from left to right.
I would like to look into this if the final conclusion is agreed with the change.

**Comment by lexmag** [comment]
Agree, suggested message describes problem better.

**Comment by whatyouhide** [comment]
👍 on my side as well.
