### ISSUE TITLE
Add docs page on operators and guards

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#5129]
For reference: http://elixir-lang.org/getting-started/basic-operators.html#operator-table

**Comment by fishcakez** [comment]
@whatyouhide sorry that was part of 2operators", hence the link to the table, Then in the guide we can link to the new page.

**Comment by whatyouhide** [comment]
Ok, awesome :) Can I ask what you mean exactly with "guards"? Should we describe what you can do in guards, what functions/operators you can use, and why?
