### ISSUE TITLE
IEx auto-complete doesn't work for structs

### ISSUE THREAD

**Issue by pareeohnos** [elixir-lang/elixir#5132]
I've come across what I think is a bug (although could be a design choice) whereby autocompletion in IEx does nothing if it is a struct. Take for example the following

```elixir
defmodule MyStruct do
    defstruct my_val: "val"
end
```

In IEx, I am able to do `MyStr` and hit tab and autocompletion works fine, but if I prefix that with a `%` autocompletion stops working.

Whilst this is obviously not a major issue, it gets quite annoying. I've got a fix running on a local copy of Elixir which simply replicates the functionality of the `strip_ampersand/1` function but to strip the percentage character instead.

Running against Elixir 1.4.0-dev (9a31d79)

Cheers

**Comment by josevalim** [comment]
@pareeohnos thank you! Would you like to submit a pull request with tests or should we tackle it?

**Comment by pareeohnos** [comment]
I'll get one prepped now :) @josevalim
