### ISSUE TITLE
guard-safe `Integer.mod` revisited

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#5135]
A couple of days ago, I started a topic on the elixir-core mailing group about implementing a guard-safe version of the modulo (floored division remainder) operation in Elixir.
I thought this would be easy, but in the end it turned out to be hard. The final macro we ended up with was, when expanded:
```
mod(a, n) 
# expands to:
 a - (n * div(a, n) + div(div(rem(a,n) * n, div(abs(rem(a, n) * n) + 1 + abs(abs(rem(a, n) * n) - 1), 2)) - 1, 2))
```
[I wrote a blog post about how we came up with this.](https://medium.com/@W_Mcode/down-the-rabbit-hole-defining-a-guard-safe-modulo-operation-in-elixir-6335ade7c078#.ng08al1v1)

While it worked, this resulting macro was:
- very (ridiculously?) long.
- hard to read, understand and therefore maintain.
- Very slow: 4x `div`, 3x `rem`, 3x `abs` as well as some other arithmetic.

In the end, the original PR, #5112, was closed because of this reason. 
Instead, the new PR #5117 was made which only included normal versions of `mod` and `floor_div` and not the macro ones. #5117 has been merged.

___________

But today I came across an odd behaviour of how the right-bit-shift operator works in Elixir: When shifting a negative number with a number large enough to completely 'empty' it, the sign is kept, and the answer stays `-1`. This is exactly what we required to implement `floor_div` (and, in extension, `mod`) and around which 3/4 of the ridiculousness was based.

A new implementation thus is possible:
```
foor_div(a, n)
# expands to
div(a, n) + ((rem(a, n) * n) >>> abs(a * n))
```
(the result of `div`, with `-1` added if the `rem(a,n)` is not zero and `a` and `n` are of different signs)

```
mod(a, n) === (a - (n * floor_div(a, n))
# therefore expands to:
a - (n * (div(a, n) + ((rem(a, n) * n) >>> abs(a * n))))
```

This new approach simplifies the implementation greatly, so I would like to revisit this.

The original PR was closed because of bad inefficiency due to the amount of calculations required. This new version is a lot simpler and faster.

Shall we add these new versions to the language, so `Integer.mod` and `Integer.floor_div` will be guard-safe?

**Comment by josevalim** [comment]
Closing in favor of the PR.
