### ISSUE TITLE
little- works for floats in binary matching, but is not documented

### ISSUE THREAD

**Issue by Marqin** [elixir-lang/elixir#5144]
* elixir 1.3.2
* OS X 10.11.6

prefix `little-` works for floats in binary matching, but is not documented:
http://elixir-lang.org/docs/stable/elixir/Kernel.SpecialForms.html#%3C%3C%3E%3E/1

Docs say that little can be used only for "integer, utf16, utf32", but I used it for `float` and it works.

Is it bug in elixir or it docs?

**Comment by josevalim** [comment]
@Marqin great catch. Docs bug. Can you please send a PR?

**Comment by Marqin** [comment]
:ok
