### ISSUE TITLE
String.ends_with?

### ISSUE THREAD

**Issue by sa-mm** [elixir-lang/elixir#5148]
The [documentation](http://elixir-lang.org/docs/stable/elixir/String.html#ends_with?/2) for `String.ends_with?` might be slightly ambiguous. At the beginning of the method explanation, "string" refers to the first argument. Later, it refers to the second argument.

Here's the method syntax:

`ends_with?(string, suffixes)`

### Current behavior

> An empty string will always match:
>
```
iex> String.ends_with? "language", ""  
true  
iex> String.ends_with? "language", ["", "other"]  
true
```

### Expected behavior

> An empty suffix will always match:
>
```
iex> String.ends_with? "language", ""  
true  
iex> String.ends_with? "language", ["", "other"]  
true
```

**Comment by c0b** [comment]
what's the problem? your **Current behavior** is exactly same as **Expected behavior**

![image](https://cloud.githubusercontent.com/assets/14798161/17839523/04a0cf42-679f-11e6-8c8d-172e01b84165.png)

**Comment by fishcakez** [comment]
Fixed in https://github.com/elixir-lang/elixir/commit/9e4d4724cd78b13f158a9769efe79a273307c509
