### ISSUE TITLE
(newly defined) lowercase sigils do not apply escape characters

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#5153]
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: Linux Mint

### Current behavior

Define a sigil such as the following one:

```
defmodule Example do
  def sigil_k(str, _opts) do
    IO.puts(str)
    str
  end
end
```

Note that this is a lowercase sigil, so we would expect escape characters `\n, \t, etc` to be inserted in the string. This is however not what happens for custom-defined sigils:

```
iex> import Example
iex> ~j{foo\nbar}
foo\nbar
"foo\\nbar"
```
### Expected behavior

Sigils with lowercase identifier letters, including custom-defined ones, insert escape characters. Therefore, the output of above ought to be:

```
iex> import Example
iex> ~j{foo\nbar}
foo
bar
"foo\nbar"
```

**Comment by josevalim** [comment]
@Qqwy you have to implement it yourself since different sigils may have different escape rules (like strings and regexes). See how the sigils r and s are implemented in Elixir as an example.

**Comment by Qqwy** [comment]
Thank you for your reply! I managed to make this work by using `Macro.escape_string`, which is also used in Elixir's built-in sigils.

I was confused by the getting-started guide on sigils, which was what prompted this issue. I've made a fix to the respective page. See [PR #838 on the elixir-lang.github.com repo](https://github.com/elixir-lang/elixir-lang.github.com/pull/838).
