### ISSUE TITLE
rescue e in ErlangError will recue all exceptions

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#5157]
### Environment
- Elixir version (elixir -v): 1.2, 1.3
### Current behavior

``` elixir
try do
  :undef.undef
rescue
  e in ErlangError ->
    e
end

%UndefinedFunctionError{}
```

Include code samples, errors and stacktraces if appropriate.
### Expected behavior

``` elixir
try do
  :undef.undef
rescue
  e in ErlangError ->
    e
end

** (UndefinedFunctionError) undefined function ...
```

**Comment by josevalim** [comment]
That's not a bug in my opinion. If it is not an Elixir exception, it is an Erlang exception. Maybe it is a documentation issue?

**Comment by fishcakez** [comment]
The expectation is that `e` will only match if the raised struct is `%ErlangError`. I am unsure how to justify any other behaviour.

**Comment by fishcakez** [comment]
Sorry I meant produced struct, not raised struct.

**Comment by josevalim** [comment]
@fishcakez oh, I see. I think we should continue rescuing it but wrap it in `ErlangError`. What do you think?

**Comment by fishcakez** [comment]
We used to have `%ErlangError{original: :undef}` which is awkward because we get a less helpful error. I don't really understand why `ErlangError` should have this special behaviour.

**Comment by josevalim** [comment]
@fishcakez the reason why I think we should have this special behaviour is because, if ErlangError handles only exceptions that are not handled by the kinds of UndefinedFunctionError, adding future exception handling would make `ErlangError` no longer rescue certain cases. Therefore `ErlangError` must always rescue all tuples, we need to choose between always wrapping them in `ErlangError` or returning multiple structs.

**Comment by fishcakez** [comment]
@josevalim good point. I think you are right, we must keep rescuing non-Elixir style exceptions (to maintain bakcwards compatibility and ease of use) and the current behaviour gives the best error. Therefore just better documentation needed.

**Comment by josevalim** [comment]
Documented under Kernel.SpecialForms.try.
