### ISSUE TITLE
Elixir makes bash exit on non-interactive mode

### ISSUE THREAD

**Issue by pufe** [elixir-lang/elixir#5159]
### Environment

* Elixir version (elixir -v):

Erlang/OTP 19 [erts-8.0.2] [source-9503fff] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.2

* Operating system:

OS X 10.10.5
and also on
Ubuntu 14.04

### Current behavior
```bash
bash <<EOF
echo "before elixir"
( elixir -e 'IO.puts "hello from elixir"' )
echo "after elixir"
command-that-does-not-exist "and is not executed"
EOF
```
current output
```
before elixir
hello from elixir
```
### Expected behavior

expected output
```
before elixir
hello from elixir
after elixir
bash: line 4: command-that-does-not-exist: command not found
```

This issue makes it harder to automate deploying my production code, as running `mix` to compile the project inside a script makes the script stop.

**Comment by josevalim** [comment]
@pufe do you know what in particular would cause it to exit?

**Comment by pufe** [comment]
@josevalim I have no idea. I tried replicating without calling elixir on the command line and was unable to do it.

**Comment by josevalim** [comment]
I figured it out. `bash` is passing the whole input to stdin. Because Elixir eagerly reads from stdin, it eats all input and then there is nothing else to be executed. A workaround is to pass the erlang flag `-noinput`:

    elixir --erl "-noinput" -e "IO.puts 'hello'"

We could expose it from Elixir if desired to make things more convenient.

Another approach is to use `xargs` to read the script out of stdin and pass it as an argument alongside the `-c` flag:

```bash
xargs -0 <<EOF bash -c
echo "before elixir"
(  elixir -e "IO.puts 'hello'" )
echo "after elixir"
command-that-does-not-exist "and is not executed"
EOF
```

**Comment by pufe** [comment]
This solves my issue. Thank you very much.

**Comment by ghbutton** [comment]
Just a small note since I just encountered this. I think you can do something like this:

```bash <<EOF
echo "before elixir"
( elixir -e 'IO.puts "hello from elixir"' ) < /dev/null
echo "after elixir"
command-that-does-not-exist "and is not executed"
EOF
```

**Comment by ghbutton** [comment]
So that elixir takes input from /dev/null instead of from the heredoc
