### ISSUE TITLE
Add unix_now to DateTime

### ISSUE THREAD

**Issue by ZuraGuerra** [elixir-lang/elixir#5161]
To get the current time in Unix right now we need to write

```elixir
DateTime.utc_now
|> DateTime.to_unix
```
Do you think something like `DateTime.unix_now/0` which outputs the same as the code above would be worth to add?

**Comment by michalmuskala** [comment]
This is already possible with `System.system_time(:seconds)` and `System.os_time(:seconds)` depending on what time guarantees you need.

**Comment by ZuraGuerra** [comment]
Good to know :) Thanks!
