### ISSUE TITLE
Obscure warning in with's else clause

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#5164]
From what I can tell, this warning is emitted when there is no `<-` match, only `=`. For example:

```elixir
defmodule M do
  def foo(arg) do
    with %{"foo" => foo} = arg do
      {:ok, foo}
    else
      _ -> :not_ok
    end
  end
end
```

```
$ elixirc with.ex
warning: this clause cannot match because of different types/sizes
  with.ex:6
```

If the matched value `foo` is not used in the body of `with`, no such warning is emitted.

Erlang 19.0.2, Elixir v1.3.2.

**Comment by michalmuskala** [comment]
The warning that the clause can never match is correct - `else` will never be called. That said the reason "different types/sizes" is quite obscure...
