### ISSUE TITLE
`List.delete/2` sometimes does not work

### ISSUE THREAD

**Issue by Ljzn** [elixir-lang/elixir#5171]
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: OSX

### Current behavior
```
iex(14)🍀 List.delete([1,2,3], 1)
[2, 3]
iex(22)🍀 list = [[1,2],[3,4],[5,6]]
[[1, 2], [3, 4], [5, 6]]
iex(23)🍀 List.delete(list, 1)      
[[1, 2], [3, 4], [5, 6]]
```
### Expected behavior

`[[3,4], [5,6]]`

**Comment by michalmuskala** [comment]
According to documentation `List.delete/2` works on values and removes the element that is equal to the second argument. `List.delete_at/2` works with indexes.

**Comment by Ljzn** [comment]
@michalmuskala  oh, sorry. It's my fault.
