### ISSUE TITLE
`make test_mix` fails with older Git (sparse checkout issue?)

### ISSUE THREAD

**Issue by wrachwal** [elixir-lang/elixir#5176]
### Environment

* Elixir version (elixir -v): 1.4.0-dev (5c4e52c)
* Operating system: openSUSE 11.1
* Git --version: 1.7.3.4 (from "evergreen" repo)

### Current behaviour

All failing tests have one in common: `sparse checkout`. I don't use this feature of Git. Default Git version for this OS coming from official repo was even older - 1.5.*.. The Git used (1.7.3.4) was refreshed from "evergreen" repo, and it's the best what I can do on this OS.

### Expected behaviour

Tests should be skipped and a warning printed. Skipped based on Git version? Presumably yes, but I don't know which version is a real "boundary" as I found somewhere the feature was introduced in 1.7.0, but I guess, could have its phases and fixes.

### Stack traces (3 tests)

```
  1) test gets and updates Git repos with sparse checkout (Mix.Tasks.DepsGitTest)
     test/mix/tasks/deps.git_test.exs:72
     ** (Mix.Error) Command "git --git-dir=.git checkout --quiet origin/master" failed
     stacktrace:
       (mix) lib/mix.ex:276: Mix.raise/1
       (mix) lib/mix/scm/git.ex:231: Mix.SCM.Git.git!/1
       (mix) lib/mix/scm/git.ex:118: Mix.SCM.Git.checkout/2
       (elixir) lib/file.ex:1145: File.cd!/2
       (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:175: Mix.Dep.Converger.all/9
       (mix) lib/mix/dep/converger.ex:115: Mix.Dep.Converger.all/7
       (mix) lib/mix/dep/converger.ex:70: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:50: Mix.Dep.Converger.converge/4
       (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
       (mix) lib/mix/tasks/deps.get.ex:27: Mix.Tasks.Deps.Get.run/1
       test/mix/tasks/deps.git_test.exs:77: anonymous fn/0 in Mix.Tasks.DepsGitTest.test gets and updates Git repos with sparse checko
       (elixir) lib/file.ex:1145: File.cd!/2
       test/test_helper.exs:102: MixTest.Case.in_fixture/3
       test/mix/tasks/deps.git_test.exs:76: (test)
```
```
  2) test updates the repo when sparse is turned off (Mix.Tasks.DepsGitTest)
     test/mix/tasks/deps.git_test.exs:282
     ** (Mix.Error) Command "git --git-dir=.git checkout --quiet origin/master" failed
     stacktrace:
       (mix) lib/mix.ex:276: Mix.raise/1
       (mix) lib/mix/scm/git.ex:231: Mix.SCM.Git.git!/1
       (mix) lib/mix/scm/git.ex:118: Mix.SCM.Git.checkout/2
       (elixir) lib/file.ex:1145: File.cd!/2
       (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:175: Mix.Dep.Converger.all/9
       (mix) lib/mix/dep/converger.ex:115: Mix.Dep.Converger.all/7
       (mix) lib/mix/dep/converger.ex:70: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:50: Mix.Dep.Converger.converge/4
       (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
       (mix) lib/mix/tasks/deps.get.ex:27: Mix.Tasks.Deps.Get.run/1
       test/mix/tasks/deps.git_test.exs:287: anonymous fn/0 in Mix.Tasks.DepsGitTest.test updates the repo when sparse is turned off/1
       (elixir) lib/file.ex:1145: File.cd!/2
       test/test_helper.exs:102: MixTest.Case.in_fixture/3
       test/mix/tasks/deps.git_test.exs:286: (test)
```
```
  3) test updates the repo when sparse is turned on (Mix.Tasks.DepsGitTest)
     test/mix/tasks/deps.git_test.exs:310
     ** (Mix.Error) Command "git --git-dir=.git checkout --quiet origin/master" failed
     stacktrace:
       (mix) lib/mix.ex:276: Mix.raise/1
       (mix) lib/mix/scm/git.ex:231: Mix.SCM.Git.git!/1
       (mix) lib/mix/scm/git.ex:118: Mix.SCM.Git.checkout/2
       (elixir) lib/file.ex:1145: File.cd!/2
       (mix) lib/mix/dep/fetcher.ex:61: Mix.Dep.Fetcher.do_fetch/3
       (mix) lib/mix/dep/converger.ex:175: Mix.Dep.Converger.all/9
       (mix) lib/mix/dep/converger.ex:115: Mix.Dep.Converger.all/7
       (mix) lib/mix/dep/converger.ex:70: Mix.Dep.Converger.all/4
       (mix) lib/mix/dep/converger.ex:50: Mix.Dep.Converger.converge/4
       (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
       (mix) lib/mix/tasks/deps.get.ex:27: Mix.Tasks.Deps.Get.run/1
       test/mix/tasks/deps.git_test.exs:325: anonymous fn/0 in Mix.Tasks.DepsGitTest.test updates the repo when sparse is turned on/1
       (elixir) lib/file.ex:1145: File.cd!/2
       test/test_helper.exs:102: MixTest.Case.in_fixture/3
       test/mix/tasks/deps.git_test.exs:313: (test)
```

**Comment by ericmj** [comment]
Is it `--git-dir` that is the issue? Does mix deps.get with git dependencies work on v1.7.3.4 or is just tests failing? Also keep in mind that git v1.7.3.4 is 6 years old and v1.5.0 is almost 10 years old.

/cc @mobileoverlord

**Comment by wrachwal** [comment]
mix deps.get works just fine on v1.7.3.4; just these 3 tests fail.
I know v1.7.3.4 is quite old, but it's not uncommon that LAB (not desktop) users have to stick with old linuxes, and simply compiling git from sources is not an option when there is an easy way to upgrade from a "better" repo.
Okay, if this is a problem or not worth effort, I can tell them to:
* ```make test_erlang test_stdlib test_ex_unit test_logger test_eex test_iex```
* ```make test``` but ignore expected failing tests
* or do not test at all

**Comment by josevalim** [comment]
@wrachwal if you can't get a precompiled elixir and users are compiling from source, `make compile` should be enough. You may also want to checkout one specific tag, instead of using master (although I appreciate the report on master!).

**Comment by josevalim** [comment]
Given the information listed here, I believe at this point sparse checkouts do not work on Git 1.7. Or there is a bug fix or a combination of features that require a more recent version of Git. I would love to find the minimum version of git that works with Mix's sparse checkout. Once such is found, we can discuss if we should skip tests or not via a flag.

**Comment by mobileoverlord** [comment]
According to docs sparse was added in 1.7.0+. I'll see if I can replicate with older versions and determine what the min should be. I agree, once found we can check git version on test run and conditionally add an exclusion. I'll start working on this

**Comment by josevalim** [comment]
@mobileoverlord sweet. I think after Elixir is compiled, you just need to change the git versions in your path. You probably know this but you can run a single test file in Elixir source with `elixir lib/mix/test/mix/tasks/deps.git_test.exs`.
