### ISSUE TITLE
date comparisons across month boundaries are incorrect

### ISSUE THREAD

**Issue by paulswartz** [elixir-lang/elixir#5181]
(I did a quick search for this, but didn't see anything open or closed)

### Environment

* Elixir version (elixir -v): 
```
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.2
```

* Operating system: 
`Darwin petra 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64`

### Current behavior

August 31st, 8pm is compared as greater than September 1st, 1am:

```
iex(1)> ~N[2016-08-31T20:00:00] > ~N[2016-09-01T01:00:00]
true
iex(2)> ~N[2016-09-01T20:00:00] > ~N[2016-09-02T01:00:00]
false
```

The same problem also exists with DateTime.

### Expected behavior

I would expect the both of those queries comparisons to be false, and they were false with TImex 2.*'s DateTime.  Converting them before the comparison also gives the correct result:

```
iex(1)> NaiveDateTime.to_erl(~N[2016-08-31T20:00:00]) > NaiveDateTime.to_erl(~N[2016-09-01T01:00:00])
false
```

**Comment by fishcakez** [comment]
`NaiveDateTime` and `DateTime` are structs, which have undefined ordering of keys and that determines order. Therefore greater/less than comparisons will have undefined ordering. After a quick looking at Timex 2.0 I am unsure how it achieved ordering you suggest.
