### ISSUE TITLE
Whitespace differences are not highlighted by ExUnit

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#5191]
### Environment
- Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.2
```
- Operating system:

OS X El Capitan
### Current behavior

Given an assertion like:

``` elixir
assert [%{a: "abc "}, %{a: "def"}, %{c: "gh"}] == [%{a: "abc"}, %{a: " def"}, %{c: "ghi"}]
```

ExUnit currently produces a diff like:

![screen shot 2016-09-07 at 2 17 38 pm](https://cloud.githubusercontent.com/assets/49391/18328876/dd9794a2-7505-11e6-9605-929579fa8f6d.png)
### Expected behavior

This diff is confusing.  It looks like the only difference is the addition of the letter `i` but there are actually some whitespace differences, too. Since those are not highlighted, my brain is drawn to the highlighted `i` and I initially wrongly interpreted it as meaning that the `i` was the only difference.  The diff would be less-confusing and more useful if whitespace differences were highlighted, too.  As an example, here's how `git diff` shows whitespace differences:

![screen shot 2016-09-07 at 1 49 12 pm](https://cloud.githubusercontent.com/assets/49391/18328927/23ade0c2-7506-11e6-9527-db65e5f86f01.png)

(See also #4689 for some prior art that was later reverted.)

**Comment by josevalim** [comment]
For future info, we can get the dark background color by doing: `IO.ANSI.color_background(1, 0, 0)`.

**Comment by josevalim** [comment]
@lexmag do you believe this can make v1.4?

**Comment by lexmag** [comment]
@josevalim yeah, I think we'll get this in. :bowtie:
