### ISSUE TITLE
Mix should report the error directly when the task doesn't exist

### ISSUE THREAD

**Issue by gonglexin** [elixir-lang/elixir#5192]
### Environment

* Elixir version (elixir -v):

> Erlang/OTP 19 [erts-8.0.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

> Elixir 1.3.2

* Operating system:

> OSX 10.10.5

### Current behavior

`mix new mix_test && cd mix_test`

Add a dependency in mix.ex ( I add httpoison here):
```
  defp deps do
    [
      {:httpoison, "~> 0.9.0"}
    ]
  end
```

`mix deps.get`

then try `mix depx.compile`, notice: we have a typo here: `deps -> depx`

![image](https://cloud.githubusercontent.com/assets/48140/18335720/3b4c0822-75b4-11e6-9f82-2cbc12d8e02c.png)

it compiles some dependencies and then report the error.

### Expected behavior

it should report the error directly instead of compiling dependencies.

**Comment by josevalim** [comment]
The reason we compile dependencies is because maybe a dependency defines the task you are trying to invoke, so we compile them hoping we may find it.
