### ISSUE TITLE
@external_resource does not work in Windows for files under /priv

### ISSUE THREAD

**Issue by milmazz** [elixir-lang/elixir#5193]
### Environment

* Elixir version: 1.3.0, 1.4.0-dev
* Operating system: Windows

### Current behavior

Sample project:

https://github.com/milmazz/external_resource

Using something like this:

```elixir
defmodule ExternalResource do
  @external_resource path = Application.app_dir(:external_resource, "priv/media-types.txt")

  #...
end
```

At least on Windows, every time that you run `mix compile` the `ExternalResource` module it's recompile, even when you don't make any changes.

```bash
$ mix compile
Compiling 1 file (.ex)
$ mix compile
Compiling 1 file (.ex)
```

### Analysis

`Mix.Compilers.Elixir.compile/5` (called by `Mix.Tasks.Compile.Elixir.run/1`) it's compiling the `ExternalResource` module because the timestamp for the `priv/media-types.txt` file change everytime that it's copied to `_build/dev/lib/external_resource/priv`, which is fine. So, which function is copying that file everytime?

It looks like the responsible for this behavior is `Mix.Utils.symlink_or_copy/2`, the `:file.read_link/1` in that function returns an `{:error, reason}` in Windows and then everything under `/priv` is copied recursively with `do_symlink_or_copy/3`, that's why the timestamp is changing constantly.

Maybe we should try to do a *sync* (ala `rsync`) in Windows, wdyt?

### Current workaround

Move the file referenced by `@external_resource` to another location such as `/lib`

### Expected behavior

The same behavior as in _Darwin_ or _GNU/Linux_.

**Comment by josevalim** [comment]
@milmazz thank you! Maybe we should set the mtime after copying files then?

**Comment by milmazz** [comment]
@josevalim If the file exists in `target`, why not to try to compare the timestamps first and then execute the copy only if the timestamp in `source` is newer than `target`, wdyt?

**Comment by josevalim** [comment]
@milmazz that would work as well!

**Comment by milmazz** [comment]
Ok, I'll work on this :)
