### ISSUE TITLE
assert_receive output can be confusing on failure due to race to read process mailbox

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#5199]
### Environment

* Elixir version (elixir -v): 1.3.2
* Operating system: 

### Current behavior

If a message is received after the `assert_receive` timeout, but before [`ExUnit.Assertions.__mailbox__(self())`](https://github.com/elixir-lang/elixir/blob/0f206e533569cf9b2ac50986e676322c5fa1ed08/lib/ex_unit/lib/ex_unit/assertions.ex#L408) is called, the failure message is confusing, because the message will appear in `Process mailbox` section, but the error will say `No message matching`.

```
No message matching {:DOWN, ^client_reference, :process, ^client_pid, {:timeout, _}} after 100ms.
The following variables were pinned:
  client_reference = #Reference<0.0.6.1817>
  client_pid = #PID<0.935.0>
Process mailbox:
  {:DOWN, #Reference<0.0.6.1817>, :process, #PID<0.935.0>, {:timeout, {GenServer, :call, [#PID<0.935.0>, {:index, %{}}, 1]}}}
```

### Expected behavior

Check the message again inside `ExUnit.Assertions.__mailbox__(self())` before flunking, then do one of the following:
A) Say "Message appeared in mailbox after `<timeout>`.  Increase timeout.", then have the user retest after increasing the timeout option to `assert_receive`
B) Don't `flunk` and allow the test to pass even though it was a little past the timeout (since the timeouts aren't precise anyway).

I like (A) because it makes the test more reliable and allows users that are checking soft-realtime issues to know that they are on the edge of their timeout window.

I'd be happy to open a PR for either option.

**Comment by josevalim** [comment]
@KronicDeth good catch. I would go with A as well. :)

**Comment by whatyouhide** [comment]
👍 for A, really clear solution with clear path for the user to take and a really nice and informative error message :). Please @KronicDeth, feel free to open the PR, would be awesome! 💟
