### ISSUE TITLE
doc/Mix.Tasks.Deps.html has some wrong label

### ISSUE THREAD

**Issue by hykw** [elixir-lang/elixir#5205]
doc/Mix.Tasks.Deps in http://elixir-lang.org/docs/stable/mix/Mix.Tasks.Deps.html has some wrong label: `Git options` and `Path options`(Maybe it has some duplication with the following line). I only found those two labels, but I'm not sure if there is no other label which has the same issue.

![doc](https://cloud.githubusercontent.com/assets/1897735/18416125/c969fa86-7845-11e6-8ac7-01fcee9f46a4.png)

**Comment by josevalim** [comment]
Thank you, it has been fixed in master (and it will likely be fixed in stable too once we do a new 1.3.x release).
