### ISSUE TITLE
Press Kit / Vector Logo?

### ISSUE THREAD

**Issue by jessejanderson** [elixir-lang/elixir#5212]
There are questions almost daily in the #elixir-lang Slack group asking for usage guidelines for the Elixir logo and/or a vector (or at least high resolution) version of the logo.

Are there any plan for a proper press kit that could answer these questions and provide a higher quality logo?

**Comment by josevalim** [comment]
It will be published once we are done with the trademark/copyright process, which, from what I understand, can take quite some time.

**Comment by jessejanderson** [comment]
Obviously not a lawyer, but isn't that the point of using "Pending Trademark"?

It's frustrating to get a mixture of answers between "Yes you can use it for slides" and "No, Plataformatec could sue you for putting it in your slides" and everything in between.

Even if the answer is "No, it cannot be used at all until the trademark/copyright process is complete", that's preferable to not knowing what is allowed.

It's Elixir - I just want the **explicit** answer. 😄
