### ISSUE TITLE
Documenting additional options for String.split/3

### ISSUE THREAD

**Issue by jbranchaud** [elixir-lang/elixir#5213]
According to the documentation of [`String.split/3`](https://github.com/elixir-lang/elixir/blob/v1.3.2/lib/elixir/lib/string.ex#L241-L348), there are two supported options: `:trim` and `:parts`. However, because whenever `String.split` is invoked with a `Regex` pattern, it delegates to [`Regex.split/3`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/regex.ex#L333-L404), there end up being other available options, namely those available to `Regex.split` (`:on` and `:include_captures`).

### Environment

* Elixir 1.3.0
* Operating system: OS X 10.11.6

### Current behavior

Here is an example of how that affects behavior of `String.split/3`:

```elixir
> String.split("23d", ~r/\d+/)
["", "d"]
> String.split("23d", ~r/\d+/, trim: true)
["d"]
> String.split("23d", ~r/\d+/, trim: true, include_captures: true)
["23", "d"]
```

### Expected behavior

This behavior seems reasonable, but as long as this is how it works, I propose that we add a note at the end of the `String.split/3` documentation directing people to `Regex.split/3` for details on `:include_captures` and `:on` options.

I'd be glad to submit a PR with the proposed changes, but wanted to get some feedback first.

_Update_: I forgot to mention there was a semi-related conversation in #2445.

**Comment by ericmj** [comment]
We need to either remove the regex-only options before delegating to `Regex.split` or document on `String.split` that it also accepts the regex options when passing a regex.

Listing the options of `Regex.split` on `String.split` means that we will likely forget to update `String.split` when `Regex.split` changes.

**Comment by josevalim** [comment]
> This behavior seems reasonable, but as long as this is how it works, I propose that we add a note at the end of the String.split/3 documentation directing people to Regex.split/3 for details on :include_captures and :on options.

Yes, let's mention that when a regex is given, it accepts the same optins as `Regex.split/3`.

**Comment by whatyouhide** [comment]
@jbranchaud you're more than welcome to open up a PR btw, that would be awesome 💟

**Comment by jbranchaud** [comment]
Great, working on the PR now. Two questions:

1. Should I name `:on` and `:include_captures`? Or be more general by just saying Regex.split has additional options?
2. Would it be useful or confusing to include an example of `String.split` using a regex and the `:include_captures` options?

**Comment by whatyouhide** [comment]
1. I say just point people to `Regex.split/3`, it will be much more future-proof :)
2. I think it's ok to add an example, these should be doctested so if we break something we will notice :)
