### ISSUE TITLE
Add protocol integration to the IEx.Helpers.i/1 function

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5239]
For any given data type, we should show all protocols it implements.

And if an atom is given and it represents a module that is as protocol, we should show all data types that implement that protocol.

**Comment by whatyouhide** [comment]
I can work on this. :)

**Comment by eksperimental** [comment]
@josevalim I think you forgot a verb after "should" in your opening sentence.

**Comment by whatyouhide** [comment]
(the verb would be "show") :)

**Comment by whatyouhide** [comment]
Closed by #5241.
