### ISSUE TITLE
Does not compile `with \` when followed by a comment

### ISSUE THREAD

**Issue by bill-mybiz** [elixir-lang/elixir#5246]
## Environment
- Elixir version (elixir -v):

Erlang/OTP 19 [erts-8.0.2] [source-753b9b9] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.2
- Operating system: Ubuntu 16.04
### Current behavior

The `with` statements don't compile if in the following form (taken from a [gist](https://gist.github.com/bill-mybiz/f0c771a97ba303214eafc83100706cc2) I made that expounds the different syntax permutations using `with`):

```
# Doesn't compile
test "with, comma-do, newline, backslash, comments" do
:ok =
  with \
    # Comment here <<<< Won't compile because of this line
    :ok <- :ok,
    :ok <- :ok,
    do: :ok
end

# Doesn't compile
# test "with, do block, newline, backslash, comments" do
:ok =
  with \
    # Comment here
    :ok <- :ok,
    :ok <- :ok do
    :ok
  end
end
```

I thought this was syntactic side-effect, but when I [mentioned](https://elixirforum.com/t/with-tweak-feature-request-first-clause-on-new-line/1671/4?u=ibgib) this behavior on the elixir forum, @josevalim asked me to open an issue for it. 

Include code samples, errors and stacktraces if appropriate.
### Expected behavior

It should compile, regardless of if the `with \` line is followed directly by a comment or not.

Thanks for all of y'alls hard work! :+1:

**Comment by cmaggard** [comment]
The tokenizer output (below) seems to have an extra eol that isn't being discarded when a line continuation is used leading into the comment. I don't have enough domain experience with the tokenizer or yecc source to make a solo contribution here, but I'd be happy to help anyone who wants to dive into it with me.
```
[{atom,{1,1,4},ok},
 {match_op,{1,5,6},'='},
 {identifier,{1,7,11},with},
 {eol,{2,3,4}},              %%  <-- this guy
 {atom,{3,3,6},ok},
 {in_match_op,{3,7,9},'<-'},
 {atom,{3,10,13},ok},
 {',',{3,13,14}},
 {atom,{4,3,6},ok},
 {in_match_op,{4,7,9},'<-'},
 {atom,{4,10,13},ok},
 {do,{4,14,16}},
 {eol,{4,16,17}},
 {atom,{5,3,6},ok},
 {eol,{5,6,7}},
 {'end',{6,1,4}},
 {eol,{6,4,5}}
]
```

**Comment by vic** [comment]
I made another quick test and the following also does not work:

```elixir
puts \
  # some comment
  :bug
```

This fails trying to call `puts/0`, just like if code were

```elixir
puts # some comment
  :bug
```

This got me thinking on what the proper behavior should be for an escaped newline followed by a comment. Made a couple of examples on other langs just to get an example example on how  they handle this case:

Ruby calls `puts()` and then just evaluates the symbol

```ruby
puts \
  # comment
  :foo
```

Bash is pretty much the same, echoes nothing and then tries to evaluate `foo` which fails when undefined.

```bash
echo \
  # comment
  foo
```

So now I'm wondering, if we should handle this case specially in Elixir or if the current parser is actually doing the *right thing*.

**Comment by whatyouhide** [comment]
I do think that `\` means "don't consider the following newline as a expression separator such as newline or `;`". In such cases, this:

```elixir
IO.puts \
  # some comment
  :atom
```

would be interpreted (by just ignoring - that is, removing, the newline) as:

```elixir
IO.puts # some comment
:atom
```

**Comment by bill-mybiz** [comment]
Ah that's interesting. I was just looking at it from the usage POV. This framing of the issue does seem to change things to me, and also I have become quite comfortable with (and fond of) using paren syntax:
```
with(
  # some comment
  x <- foo()
...
) do
  {:ok, x}
else
  error -> handle(error)
end
```

**Comment by josevalim** [comment]
Yes, `\` is literally about escaping the upcoming newline (that's why it is at the end of the line and right before the new line). So I believe we can close this.
