### ISSUE TITLE
Deprecate single quote strings

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5248]
The goal is to soft-deprecate for now and introduce an actual warning only on version 1.6. When inspected, we should show `~c[foo]`. We should also add a note to deprecate single quotes inside sigils too. Finally, let's guarantee `h ~c[foo]` works and prints readable documentation.

**Comment by sotojuan** [comment]
Is `'a'` deprecated or just stuff like `'hello'` (character list)?

**Comment by ericmj** [comment]
@sotojuan Both are deprecated, they both create char list strings.

**Comment by eksperimental** [comment]
To see the discussion of this feature in the Elixir Lang Core mailing list:
https://groups.google.com/forum/#!topic/elixir-lang-core/_pAjPEayLLI

**Comment by josevalim** [comment]
We are not doing the deprecation. Once the discussion started, folks have been sending more and more code samples where the change above would have undesired results and make the code harder to read.

**Comment by sotojuan** [comment]
Thanks for listening to the community!
