### ISSUE TITLE
Revisit ExUnit terms on Elixir 2.0

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5254]
We often refer to the module that defines the test cases as a "case", because it is the one that includes `ExUnit.Case`, but that nomenclature is confusing. We should refer to the module either as a suite (which can also be confusing) or simply as a module and each test is a function (getting rid of the `case` name almost everywhere except in `ExUnit.Case`).

**Comment by theduke** [comment]
Have I missed something or is elixir 2 on the (at least faint) horizon?

**Comment by josevalim** [comment]
No, it isn't on the horizon at all.

**Comment by jpettit** [comment]
As it seems to me currently, I would caution some discretion when making this change.  Fundamentally, the inner workings of ExUnit are tightly coupled design-wise with the idea that the `module` is to be the "case".  As a result, simply changing the functionality on the surface to revise the nomenclature as proposed above may lead to some interesting and unintended side effects.

**Comment by josevalim** [comment]
In order to make this less of a breaking change, we should probably introduce the new fields before Elixir 2.0 and remove the old fields only on 2.0.

**Comment by josevalim** [comment]
This has been done here: 23c7542d95683a497a7b93071b9ccbbeb9e45d2f

We have added TODOs with the places that require breaking changes on 2.0.
