### ISSUE TITLE
Migrate Logger away from GenEvent

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5255]
The goal is to migrate Logger handlers away from GenEvent. We can either use Erlang's `gen_event` or have a custom implementation on top of GenServer. We are not going to use GenStage because this is one of the few cases where gen_event's architecture actually makes sense: we want to avoid copying between multiple handlers. Therefore, differently from #5254, this issue can be tackled now-ish.

**Comment by antipax** [comment]
@josevalim I'd like to take a crack at this unless you have someone else in mind?

**Comment by josevalim** [comment]
@antipax that would be fantastic, please go ahead. I would start with `gen_event` at first. Keep in mind ExUnit kinda depends on Logger internals.

**Comment by antipax** [comment]
So here's a couple things that have come up that we should discuss:

* `GenEvent` provides an error when you try to add a duplicate handler to a manager. `:gen_event` provides none, and I can't think of a way to do that outside the manager process without introducing a race condition.

* `GenEvent` provides `add_mon_handler`, which is also impossible to implement with the `:gen_event` manager

A possible solution to the first is to allow duplicate backends to be installed, or, we could track them separately somewhere, like an ETS table or another process.

As for the second, I think we could use `add_sup_handler`, because currently the process which uses `add_mon_handler` exits in all the cases it would with `add_sup_handler`, AFAIK.

**Comment by josevalim** [comment]
Yes, we don't need the mon handler feature because we can use the sup
handler.

For the uniqueness thing though, maybe we can use the logger watcher
supervisor to give us uniqueness, as it requires the watchers id to be
unique. This means we can't use a simple one for one though (which is fine,
we wouldn't have dozens of children anyway).


-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by antipax** [comment]
So, I don't think we can use a `:one_for_one` supervisor for this. The child spec for a `:transient` child persists in the supervisor even after the process dies, so you cannot remove and then re-add a child with a given ID. Any thoughts? Could just use a separate gatekeeper process or ETS table.

**Comment by josevalim** [comment]
I can think of two options:

  * allow duplicates and leave it up to the user to handle those with care?
  * have an ets table and have the watcher check the table on init, maybe returning ignore in case of already taken

/cc @fishcakez

**Comment by fishcakez** [comment]
Can we pass this to the calling process? The watcher can be removed with `delete_child` if it is present and the code is very simple and keeps the uniqueness guarantee in a single place.
```elixir
def start_backend(module, arg) do
  case Supervisor.start_child(WatcherSup, worker(Watcher, [module, arg], [id: module])) do
    {:error, :already_present} ->
      _ = Supervisor.delete_child(WatcherSup, module)
      start_backend(module, arg)
   other ->
    other
end
```

**Comment by antipax** [comment]
Yes, that's a good point. I had not thought to use `:already_present` vs. `:already_started` for this purpose.

Could there be a (perhaps unimportant) race where two processes attempt to add a backend, and instead of it getting added once, it gets added, removed, and added again?

**Comment by fishcakez** [comment]
Its not possible because delete_child does not work unless the child has
undefined pid. So the second client in the race will get an already started
error.

**Comment by antipax** [comment]
Perfect! Thanks @fishcakez! ❤️ 

I'll move ahead with this approach.
