### ISSUE TITLE
Remove NaiveDateTime.from_unix (not yet released) in favor of add and diff functionality

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5260]
See discussion: e50735ff2a7c16cc7705d8fa59af906e986c19f7

**Comment by JEG2** [comment]
The `from_unix()` functions [do seem to be in the latest Elixir](http://elixir-lang.org/docs/stable/elixir/DateTime.html#from_unix/2).  Am I wrong about that?  If I'm not, is it still OK to remove them?

**Comment by JEG2** [comment]
I seem to have it a version behind as well:

```elixir
Interactive Elixir (1.3.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> DateTime.from_unix(0)
{:ok,
 %DateTime{calendar: Calendar.ISO, day: 1, hour: 0, microsecond: {0, 0},
  minute: 0, month: 1, second: 0, std_offset: 0, time_zone: "Etc/UTC",
  utc_offset: 0, year: 1970, zone_abbr: "UTC"}}
```

**Comment by josevalim** [comment]
Oops, it was meant to be `NaiveDateTime.from_unix`. I will fix the description. Thank you!

**Comment by JEG2** [comment]
Do we also want to remove `NaiveDateTime.utc_now/0`?  It uses `from_unix/2`, but could be rewritten.

**Comment by josevalim** [comment]
@JEG2 `utc_now` now is going to stay. `from_unix` and `to_unix` will be removed.

If you look at the from_unix implementation, you may notice it is effectively an `add(naive_datetime, integer, precision)` operation. Similarly, `to_unix` is `diff(naive_datetime, naive_datetime, precision)`. So the goal is to expose both `add` and `diff`` instead of the specific `from_unix` and `to_unix`.

Also from_unix and to_unix are timezone specific, it implies UTC, so it should probably belong exclusively to DateTime.

**Comment by JEG2** [comment]
Sorry for all of the questions.  I'm trying to help with this issue, but, as you can tell, I'm clueless.  Please do ignore this if you don't have the time.

Does my `NaiveDateTime.add` function need to support `System.time_unit` or just seconds?  I'm having a hard time figuring out how to add a number of microseconds.

**Comment by josevalim** [comment]
@JEG2 it is totally fine to ask. I am the one sorry for the short answers. :)

> Does my NaiveDateTime.add function need to support System.time_unit or just seconds? I'm having a hard time figuring out how to add a number of microseconds.

We should support any precision but you can start with seconds. This is the rough sketch of an add/3 function:

```elixir
  def add(%NaiveDateTime{} = naive_datetime, integer, unit \\ :precision) when is_integer(integer) do
    # Convert naive_datetime to microseconds
    epoch = naive_datetime_to_gregorian_seconds(naive_datetime)
    epoch = epoch * 1_000_000 + microseconds_from_naive_datetime(naive_datetime)

    # Convert the integer to microseconds
    integer = System.convert_time_unit(integer, unit, :microsecond)
 
    # Finally add them together and compute the parts back
    total = integer + epoch
    microsecond = rem(total, 1_000_000)
    precision = precision_for_unit(unit)
    {{year, month, day}, {hour, minute, second}} = :calendar.gregorian_seconds_to_datetime(div(total, 1_000_000))
    %NaiveDatetime{year: ..., ..., microsecond: {microsecond, precision}}
  end
```

There is no guarantee this works but it should give you an idea on how the computations are done.
