### ISSUE TITLE
Can not connect node with short name

### ISSUE THREAD

**Issue by gonglexin** [elixir-lang/elixir#5264]
### Environment

* Elixir version (elixir -v):
> Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
>
> Elixir 1.3.3

* Operating system:
> OSX 10.10.5

### Current behavior

Correct: with `--name`
![image](https://cloud.githubusercontent.com/assets/48140/18905576/69db16b4-8596-11e6-9c9d-704f8894fde0.png)

Wrong: with `--sname`
![image](https://cloud.githubusercontent.com/assets/48140/18905663/c6f60fde-8596-11e6-95c1-a95871ea6086.png)

Wrong: one with `--name`, the other with `--sname`
![image](https://cloud.githubusercontent.com/assets/48140/18905984/38179f7e-8598-11e6-8de1-ce92dbef62c7.png)

### Expected behavior
Am I wrong? I would like to connect nodes with the short name.

**Comment by josevalim** [comment]
I have had issues like this in the past if recently changed the machine name. I would recommend checking your host files or restarting your machine (network services) and see if the problem persists.

**Comment by gonglexin** [comment]
@josevalim It works after I cutting off WI-FI connection and won't work when I connect WI-FI again.

**Comment by josevalim** [comment]
@gonglexin so it does feel to be something related to your network/machine settings. If you go to System Preferences > Sharing and change your computer name to something else, does it work permanently?

**Comment by gonglexin** [comment]
@josevalim No, it doesn't work after I changing my computer name, changing to another WI-FI connection (Totally different network). No lucky even I re-installed Elixir (1.3.3) and Erlang (19.1).

**Comment by gonglexin** [comment]
@josevalim I finally figured out it has nothing to do with network, computer name or other things. It's ok  in Elixir 1.3.3 and Erlang 19.0, but doesn't work with Elixir 1.3.3 and Erlang **19.1**

it seems that something changed in  `:net_kernel.connect_node/1`  of Erlang 19.1

**Comment by josevalim** [comment]
@gonglexin can you reproduce it using Erlang only? Something like:

```
$ erl -sname foo
...
1> net_kernel:connect_node(bar@monster).
```

If so, they would probably appreciate a bug report!

**Comment by gonglexin** [comment]
Erlang's `net_kernel:connect_node` works both in 19.0 and 19.1 and then I switch back to Elixir's `iex`, it works both with  Erlang 19.0 and 19.1.  it's very strange. let's close this issue for now, I'll reopen it in case I find any further bugs of this connecting problem.

**Comment by steve-fan** [comment]
@gonglexin I got the same problem, help me out please! 😄

**Comment by josevalim** [comment]
@steve-fan when did you install Erlang? How and which version?

**Comment by gonglexin** [comment]
@steve-fan Actually, I can't reproduce it right now. I just uninstalled Elixir from homebrew and had a whole new installation via [asdf](https://github.com/asdf-vm/asdf) when I encounter this problem last time. Maybe you can reinstall Erlang and Elixir and have another try.

@josevalim But I do remember that it hangs for several seconds before returns `false` when I try to connect a node
