### ISSUE TITLE
html documentation presentation suggestions

### ISSUE THREAD

**Issue by vladdu** [elixir-lang/elixir#5265]
Following discussion on erlang-questions, I looked a little at the docs CSS and I have some comments.

- the main site has text size set to 0.8em, why? It is quite small.

- some font sizes and height lines are hardcoded (px, not em), for example 'code' elements 
- IMHO line height can be made 1.4em (maybe even 1.3) without impairing legitibility
- .content-inner pre has "overflow-x: scroll;", changing it to "auto" will remove the scrollbar when not needed. 
- it would look even nicer to have the function docs content indented a bit, like the erlang docs do. It helps scanning the page faster.

**Comment by josevalim** [comment]
Thank you, I have moved it to the documentation project: https://github.com/elixir-lang/elixir/issues/5265
