### ISSUE TITLE
`mix new` should bail if the directory already exists

### ISSUE THREAD

**Issue by et** [elixir-lang/elixir#5272]
### Environment

* Elixir version (elixir -v): Elixir 1.3.2
* Operating system: ProductName:	Mac OS X, ProductVersion: 10.10.5, BuildVersion: 14F27

### Current behavior

* `mkdir foo`
* `touch foo/bar.js foo/buzz.js`
* `mix new foo`
```
creating README.md
creating .gitignore
creating mix.exs
creating config
creating config/config.exs
creating lib
creating lib/foo2.ex
creating test
creating test/test_helper.exs
creating test/foo2_test.exs
```

Mix creates a bunch of files in my `foo` project.

### Expected behavior

`mix new` should bail with an error message saying "foo directory already exists". I can't think of a valid reason why someone would want to create a new package inside a preexisting directory.

**Comment by et** [comment]
FWIW, doing this with Phoenix

```
mix phoenix.new foo
> The directory foo already exists. Are you sure you want to continue? [Yn]
```

This seems a little better because it's giving you a chance to bail.

**Comment by josevalim** [comment]
:+1:

**Comment by shhavel** [comment]
I can take this one if no objections.

**Comment by et** [comment]
@shhavel - that would be awesome! Ultimately it should be @josevalim's decision, but I think it should maintain the same behavior as Phoenix (providing the prompt). That way we get consistency (with Phoenix), a safety net (for n00bs like me), and flexibility (for people who really want to create a new mix project inside an existing one).

**Comment by josevalim** [comment]
@shhavel please go ahead :D

**Comment by eksperimental** [comment]
Wouldn't we need options to avoid prompting when not wanting to act interactively, such in writing a script to automatize things.

something like `--assume-yes` and `--assume-no` such as in `apt-get`

```
$man apt-get
   ...
       -y, --yes, --assume-yes
           Automatic yes to prompts; assume "yes" as answer to all prompts and run non-interactively. If an undesirable situation, such as
           changing a held package, trying to install a unauthenticated package or removing an essential package occurs then apt-get will
           abort. Configuration Item: APT::Get::Assume-Yes.

       --assume-no
           Automatic "no" to all prompts. Configuration Item: APT::Get::Assume-No.
```

**Comment by josevalim** [comment]
@eksperimental we could add those if desired. It should be called `--force` in this case, to keep inline with other conventions in Mix.

**Comment by josevalim** [comment]
This issue has been solved though. Further PRs can be sent if necessary. :)
