### ISSUE TITLE
app version fun is called many times in a single compile

### ISSUE THREAD

**Issue by martin-langhoff** [elixir-lang/elixir#5274]
### Environment

* Elixir version (elixir -v): 1.3.3
* Operating system: CentOS6, CentOS7

### Current behavior

If an app version is set to a function instead of a string, the function is called multiple times during a single compile (in our case, 18-25 times depending on app). 

How to repro? In `mix.exs`:

```
defmodule Foo.Mixfile do
  use Mix.Project
  def get_version do
    IO.puts "get_version"
    "1.0.0"
  end
  def project do
    [app: :foo,
     version: get_version,
...
```

### Expected behavior

Output shows `get_version` once, result of `get_version` is cached or memoized by called.

In our case, get_version uses `git describe` which can be expensive. As a workaround, we use a simple memoize strategy: https://gist.github.com/martin-langhoff/299d98d452b8b17e130ba80e62001df5

**Comment by NobbZ** [comment]
It will get called everytime project/0 is called. I think a much better workaround were to use a macro instead of a function. 

Remember, you don't set the version to a function but to the return value of a function, as such of course the function will be called everytime the list is built.

**Comment by josevalim** [comment]
@martin-langhoff please don't do the git describe approach. Please, please, please. If you really need to, do it at the module body so it happens once. The Ruby community had major problems not long ago because of practices exactly like that.

**Comment by josevalim** [comment]
@martin-langhoff Can you please tell me which command are you running to see it printed 25 times? That value is already cached today and I see it only once per compile (and twice per test because of other reasons).

**Comment by martin-langhoff** [comment]
@josevalim - we find it pretty good (as long as we use strategically-placed tags) to automagically version builds. The git project itself uses it (I was an early contributor to git myself).  Link, or anything I can google on what's bad about it?

Maybe I'm missing a trick here, what do you mean by "do it at the module body"? 

@NobbZ  - I'm not sure how a macro would help.

**Comment by martin-langhoff** [comment]
@josevalim I am just running `mix compile` in a complex project. I can try patching up Phoenix to demo if that helps.

**Comment by josevalim** [comment]
> Link, or anything I can google on what's bad about it?

Imagine if all of your projects and dependencies did that. So if you started a Phoenix project, which let's say has 15 dependencies, you will have 15 dependencies issuing a git command, sometimes even two, which ends up adding considerably to the boot time. The issue you are reporting is exactly the problem.

> Maybe I'm missing a trick here, what do you mean by "do it at the module body"?

```elixir
@version System.cmd("git", [...])

def project do
  [version: @version]
end
```

**Comment by josevalim** [comment]
> @josevalim I am just running mix compile in a complex project. I can try patching up Phoenix to demo if that helps.

I have just tried it in a new Phoenix project and I saw it just once as well, so we will be waiting for more info on how to reproduce it. :)

**Comment by martin-langhoff** [comment]
Clarification - I am running `mix compile` in a particular `apps/foo` dir of a large umbrella project. There are 4 apps under the umbrella, and this one depends on 2 others. So I'd expect perhaps 3 calls total.

Thanks for the "In Module" example. Will see if I can work it in.

To clarify, this is for our in-house development code. I would not do this for a release version of a re-usable library (something to publish in Hex), except perhaps for developer builds. That's agreed.

**Comment by martin-langhoff** [comment]
OK will experiment some more. Thanks for the help so far!

**Comment by NobbZ** [comment]
> @NobbZ - I'm not sure how a macro would help.

Well, because of the very same reason @josevalim's attribute does work, it is resolved at compiletime of the projects Mix-module, not at its runtime.

I simply suggested a macro, because it can have more complex logic than an attribute.

But aside of that, I have to be honest. I thought that the git-describe approach for versioning stuff is cool as well and tried it in various languages on a couple of projects. I really liked it. Well, until I had to compile/run the project the first time outside of the git-repository. Since then I often only have some consistency check in the testsuite which fails if necessary but is happy if there is no git info available.

**Comment by martin-langhoff** [comment]
@josevalim this sample approximates what I ahve in my private tree, and repros the issue https://github.com/martin-langhoff/exrm-umbrella-test/tree/get-version-test

**Comment by josevalim** [comment]
@martin-langhoff thank you. That makes more sense as we are indeed navigating between multiple projects. However, once inside a project, the configuration should not be loaded again unless moved elsewhere. We could add caching between traversals but that will bring its own complexities. For now, we will recommend developers to avoid doing any work inside `def project`, as it is meant to return configuration.

**Comment by martin-langhoff** [comment]
@josevalim -- the actual commit is https://github.com/martin-langhoff/exrm-umbrella-test/commit/3a5b58de1f02bc123d07c21eb0eb3794bb78001d - I don't think you managed to hit it (I mis-pushed earlier, so wouldn't have been there).

Just in case it's interesting. I understand the rationale to close.

**Comment by josevalim** [comment]
@martin-langhoff I have added something similar myself. :) For now, module attributes are the way to go in your case.
