### ISSUE TITLE
`ExUnit.CaptureLog.capture_log/1` can capture logs from other tests even when `async: false` is set

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#5277]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.2
```

* Operating system:

OS X El Capitan

### Current behavior

I've got this module:

``` elixir
defmodule Validate do
  require Logger

  @moduledoc """
  Simple way to ensures that result is good, and raise simple to
  understand error otherwise.
  """

  @doc """
  Return ok'ed value, or raise error on non-ok result.
  The assumption is that {:error, ...} is properly logged.
  OTOH, anything but {:ok, ...}, {:error, ...} is treated as
  contract violation, and logged.
  """
  @spec validate!(any) :: any
  def validate!({:ok, value}), do: value
  def validate!({:error, description}) do
    raise __MODULE__.ValidationError, message: description
  end
  def validate!(anything) do
    message = "unexpected input (#{inspect anything})"
    Logger.error(message)
    raise __MODULE__.ValidationError, message: message
  end

  defmodule ValidationError do
    defexception [:message]
  end
end
```

And this test:

``` elixir
defmodule ValidateTest do
  use ExUnit.Case, async: false
  import ExUnit.CaptureLog

  test "`validate!` returns value on :ok" do
    assert 123 = validate!({:ok, 123})
  end

  test "`validate!` raises ValidationError on error, but does not log" do
    log = capture_log fn ->
      assert_raise Validate.ValidationError, fn -> validate!({:error, "message"}) end
    end
    assert "" == log
  end

  test "`validate!` raises ValidationError and logs on unexpected input" do
    log = capture_log fn ->
      assert_raise Validate.ValidationError, fn -> validate!(:foobar) end
    end
    assert log =~ ~r"unexpected input"
  end
end
```

Usually the tests pass, but every now and then I get a failure when I run it together with my entire suite.  Here's an example:

```
  2) test `validate!` raises ValidationError on error, but does not log (ValidateTest)
     apps/util/test/unit/validate_test.exs:9
     Assertion with == failed
     code: "" == log
     lhs:  ""
     rhs:  "\e[31m11:57:54.241 [error] Process #PID<0.12216.0> raised an exception\n** (RuntimeError) boom\n    apps/worker_pool/test/unit/worker_test.exs:68: anonymous fn/0 in Delorean.WorkerPool.WorkerTest.test notifies the observer when a job fails/1\n    (worker_pool) lib/worker.ex:86: Delorean.WorkerPool.Worker.Server.process_job/1\n\e[0m\e[31m11:57:54.241 [error] Process #PID<0.12220.0> raised an exception\n** (RuntimeError) boom\n    apps/worker_pool/test/unit/worker_test.exs:77: anonymous fn/0 in Delorean.WorkerPool.WorkerTest.test is able to run subsequent jobs after a failure/1\n    (worker_pool) lib/worker.ex:86: Delorean.WorkerPool.Worker.Server.process_job/1\n\e[0m"
     stacktrace:
       apps/util/test/unit/validate_test.exs:13: (test)
```

### Expected behavior

The docs for `capture_log/1` say this:

> Note that when the `async` is set to `true`, the messages from another test might be captured.

While it does not explicitly say so, it implies that when `async` is set to `false`, it will guarantee that the logs from another test will not be captured.  However, even with `async: false`, I occasionally get a failure due to logs captured from another test.

I have a couple theories as to why this could be happening:

1. Unprocessed log messages in the Logger server.  I noticed the implementation of `capture_log/1` calls `Logger.flush/0` at the _end_, to ensure all log messages have been processed before returning, but it does not do that at the start, before beginning to capture logs. I think that means that there could be unprocessed log messages that were already in the server's mailbox that get included in the capture.
2. As discussed in #3854, processes linked to a test process may not have completed exited when the next test begins running.  I suspect that some processes started in `worker_test.exs` (mentioned in the logs above) may not have finished exiting when these `validate_test.exs` tests run, in spite of `async: false`.  (On a side note, I've started using this [synchronize_death_on_exit](https://gist.github.com/myronmarston/adacf3884730133a19d033cfe1cc9500) helper function in my tests to ensure named processes have completely exited in my tests, and it would be nice not to have to do that...I wonder if ExUnit could provide stronger guarantees around that?)

**Comment by josevalim** [comment]
@myronmarston excellent bug report. :heart: I can see both 1 and 2 mentioned above happening.

/cc @fishcakez @antipax

**Comment by antipax** [comment]
Interesting, I wonder if the new `:gen_event` branch causes any changes here. Will try out @myronmarston's test case a little later. Thanks Myron!

**Comment by myronmarston** [comment]
BTW, I've also occasionally run into what's essentially the opposite of this problem.  A test like this:

``` elixir
test "logs a message" do
  log = capture_log fn ->
    do_something_that_should_log()
  end

  assert log =~ ~r/something/
end
```

...will sometimes fail because `log` is `""` instead of a string containing `"something"`.  However, I've never been able to consistently repro, and `do_something_that_should_log()` is complex enough that I couldn't totally rule out the possibility of a bug in my code causing this.  At one point, I suspected that it was a synchronization problem due to logging being asynchronous, but I checked the `capture_log` implementation and noticed that it calls `Logger.flush()` to address that.  So I have no theories as to why I've seen that.  If I ever get a simple enough example to report (as this one is) I'll open an issue.

**Comment by wojtekmach** [comment]
> BTW, I've also occasionally run into what's essentially the opposite of this problem (...) will sometimes fail because log is "" instead of a string containing "something"

this just reminded me of recent failures on phoenix master. I just took a stab at reproducing it, and one of the example from the test below fails every single time for me (on a fresh project). This is about capture_io (not capture_log) but they seem related:

```elixir
defmodule FooTest do
  use ExUnit.Case
  import ExUnit.CaptureIO

  test "1" do
    assert capture_io(fn ->
      Mix.Task.run("help", ["help"])
    end) != ""
  end

  test "2" do
    assert capture_io(fn ->
      Mix.Task.run("help", ["help"])
    end) != ""
  end
end
```

```
% elixir --version
Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.3
```

This uses MIx.Task.run, so perhaps it's a different issue altogether, in which case sorry for the noise.

**Comment by fishcakez** [comment]
@myronmarston your code example is not consistent with the failure example and it is not possible to produce a failure for your code example:

If there are unprocessed messages in the Logger message queue then they will always be ahead of the message for the `add_handler` call and so we don't need to flush the Logger process. However there could be messages in the `:error_logger` message queue so we should "flush" that process before adding the Logger handler. That isn't happening in your code but it is possible it is happening in your failure example.

Given the log message in the failure we can imagine what the code might look like. A raw process created with a spawn BIF is crashing and the VM is logging it to `:error_logger`. If we do the `:error_logger` flush it does not solve this race condition (but might make it less likely) because the VM sends the event after links and monitors are handled and  all of these are handled asynchronously with the possibility of getting pre empted at any point (it all costs reductions as normal). Therefore we have no way to guarantee a point in time at which a raw process crash event has been sent to error logger so that we can flush after it.

However with OTP processes the log messages are always sent before the process exits so a link or monitor is guaranteed to be sent after any of their events to `:error_logger`. Therefore using a Task instead of a spawn BIF would handle this race condition if we flushed `:error_logger`.

I think the only thing `ExUnit` could do is provide an empty Supervisor per test that will be shutdown before it marks the test as done. I am not sure that is better than explicitly using one.

**Comment by fishcakez** [comment]
@wojtekmach could you open a separate issue as these are handled differently?

**Comment by myronmarston** [comment]
> @myronmarston your code example is not consistent with the failure example and it is not possible to produce a failure for your code example:

I don't understand what you mean.  I copied the code, test and failure output verbatim with two small tweaks (renamed the module so it's not namespaced like it is in our app, and replaced `use OurApp.TestCase` (which just does `use ExUnit.Case` plus some minor things like set up common aliases, doc test, etc) with `use ExUnit.Case`.

You're right that it's not possible to reproduce the exact failure I pasted w/ only what I gave you, because it only happens when I run the test with the entire suite and I can't provide that.

> Given the log message in the failure we can imagine what the code might look like. A raw process created with a spawn BIF is crashing and the VM is logging it to :error_logger.

The logged error message indicates it is coming from a test at `worker_test.exs:68` and I'm not using `spawn` there.  In that test, I only use `start_link` and `GenStage.from_enumerable` to start processes.  Here's some excerpted code from that test, in case it helps:

``` elixir
  test "notifies the observer when a job fails" do
    job_1 = %{id: id} = build_job(fn -> raise "boom" end)

    start_consuming_jobs([job_1])

    assert_receive {:job_failed, ^id, {%RuntimeError{message: "boom"}, stacktrace}}
    assert is_list(stacktrace)
  end

  defp start_consuming_jobs(jobs) when is_list(jobs) do
    {:ok, producer} = GenStage.from_enumerable(jobs)
    {:ok, worker} = Worker.start_link([producer])
    worker
  end

  defp build_job(job_fun, overrides \\ []) do
    %Job{
      job_fun: job_fun,
      logger_metadata: Keyword.get(overrides, :logger_metadata, []),
      id: make_ref(),
      observer_pid: Keyword.get(overrides, :observer_pid, self()),
      timeout: Keyword.get(overrides, :timeout, :infinity),
    }
  end
```

**Comment by fishcakez** [comment]
@myronmarston ah sorry I misunderstood, I thought it was supposed to be possible just with that code.

The log message printed should only be occurring when a process spawned with `spawn` or another spawn BIF like `spawn_link` was used. We can never provide a guarantee for that message.

What happens on line 86 of `lib/worker.ex`? Is that the function being used to initiate a spawned process? Given the stack depth in the error message I would imagine it or a function that calls `Delorean.WorkerPool.Worker.Server.process_job/1` in the tail would be passed to a `spawn` BIF.

**Comment by myronmarston** [comment]
> The log message printed should only be occurring when a process spawned with `spawn` or another spawn BIF like `spawn_link` was used.

As it turns out, in `worker.ex`, I'm using `spawn_monitor`.  I didn't realize that processes spawned with `spawn_monitor`, `spawn_link` or `spawn` could defeat Elixir's logger synchronization.  (And I also didn't connect your mention of `spawn` causing this with my use of `spawn_monitor` -- sorry about that).

FWIW, here's the code in question in my worker (which is a `GenStage` consumer):

``` elixir
    def handle_events(jobs, _from, state) do
      Enum.each(jobs, &process_job_in_isolated_process/1)
      {:noreply, [], state}
    end

    defp process_job_in_isolated_process(job) do
      fn -> process_job(job) end
      |> spawn_monitor()
      |> wait_for_process_completion(job.timeout)
      |> case do
           :normal -> :ok
           :timeout -> notify_observer(job, :job_timed_out, job.timeout)
           failure -> notify_observer(job, :job_failed, failure)
         end
    end

    defp wait_for_process_completion({pid, ref}, timeout) do
      receive do
        {:DOWN, ^ref, :process, ^pid, info} -> info
      after timeout ->
        Process.exit(pid, :kill)
        :timeout
      end
    end

    defp process_job(job) do
      Logger.metadata(job.logger_metadata)

      if Process.alive?(job.observer_pid) do
        result = job.job_fun.()
        notify_observer(job, :job_finished, result)
      else
        Logger.warn "#{__MODULE__} aborted job #{inspect job.id}, " <>
                    "since observer #{inspect job.observer_pid} is down"
      end
    end

    defp notify_observer(job, notification, data) do
      send(job.observer_pid, {notification, job.id, data})
    end
```

Given that I want to start a process and monitor it, is there a way to do so with OTP processes without having to write a full-fledged GenServer?

> We can never provide a guarantee for that message.

That's good to know.  Now that we understand what's going on, I think the only changes to consider making to Elixir are documentation improvements.  Specifically, I'm thinking of:

* A note in `ExUnit.CaptureLogger` that mentions that the the log-capturing mechanism isn't synchronized with log messages sent to `:error_logger` and that non-OTP processes will log there.
* A note on `spawn`, `spawn_link` and `spawn_monitor` mentioning that the spawned processes will suffer from this issue (and perhaps other issues related to them not being full-fledged OTP processes, but I don't yet know enough about OTP to know what those might be) and suggesting OTP-compliant alternatives.

Such documentation improvements definitely would have helped me understand this issue without resorting to opening what turned out to be a false bug report.

**Comment by fishcakez** [comment]
@myronmarston it is not a false bug report because we can improve the situation by flushing `:error_logger` even though it's unfortunate that we can't handle it for your case. Also they're isn't really a lot we can do about log messages arriving due to asynchronous failures because really that requires handling to know what those processes are and `ExUnit` can't know.

**Comment by fishcakez** [comment]
@myronmarston Elixir provides `Task.Supervisor`, `Task.Supervisor.async_nolink`, `Task.yield` and `Task.shutdown` for this purpose.

When using `Process.exit(pid, :kill)` you monitor (you already are) and await the `:DOWN` to wait for `pid` to have exited. Exit signals are asynchronous so `pid` can still be doing work until you get that `:DOWN`. In your code the `:DOWN` will arrive late and might not be `:killed` because `pid` could exit before it gets killed.

**Comment by myronmarston** [comment]
@fishcakez Thanks for the help!  I took a stab at re-writing my worker using `Task.Supervisor`.  If you have the time, can you confirm I've done this correctly?

https://gist.github.com/myronmarston/42e3d2261e42751fea0959e88538a6ba

It passes my tests, at least :).

Besides the changes to flush `:error_logger`, I hope we can improve the docs for `ExUnit.CaptureLogger` to include some caveats about when it cannot provide guarantees even if you are using `async: false`.

**Comment by myronmarston** [comment]
So this is weird -- I re-ran my entire test suite (all 2K+ test cases) and the `ValidateTest` failure I originally reported above failed again, even with the change from `spawn_monitor` to using a supervised task:

``` 
  1) test `validate!` raises ValidationError on error, but does not log (Delorean.Util.ValidateTest)
     apps/util/test/unit/validate_test.exs:9
     Assertion with == failed
     code: "" == log
     lhs:  ""
     rhs:  "\e[31m16:03:17.125 [error] Task #PID<0.12106.0> started from #PID<0.12104.0> terminating\n** (RuntimeError) boom\n    apps/worker_pool/test/unit/worker_test.exs:68: anon
ymous fn/0 in Delorean.WorkerPool.WorkerTest.test notifies the observer when a job fails/1\n    (worker_pool) lib/worker.ex:83: Delorean.WorkerPool.Worker.Server.process_job/1\n
(elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2\n    (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5\n    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_a
pply/3\nFunction: #Function<1.83351332/0 in Delorean.WorkerPool.Worker.Server.process_job_in_isolated_process/2>\n    Args: []\n\e[0m"
     stacktrace:
       apps/util/test/unit/validate_test.exs:13: (test)
```

Seems like something else must be at play?

**Comment by fishcakez** [comment]
@myronmarston it looks good I would suggest `case Task.yield(..) || Task.shutdown(..) do` as this will handle the situation where the result arrives after the yield and before the process is killed. Note that a `nil` return would then be a timeout.

A `Task` (and other OTP processes) send terminating log message to `:error_logger` so we need to flush `:error_logger` to provide the guarantee it doesn't "leak". Sorry if that wasn't clear before. I have sent a PR for this issue: #5280.

**Comment by myronmarston** [comment]
> @myronmarston it looks good I would suggest `case Task.yield(..) || Task.shutdown(..) do` as this will handle the situation where the result arrives after the yield and before the process is killed. Note that a `nil` return would then be a timeout.

Good to know, thanks!

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
