### ISSUE TITLE
ExUnit.CaptureLog and Mix.Task.run

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#5279]
### Environment

* Elixir version (elixir -v): 

```
Erlang/OTP 18 [erts-7.3.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.3.3
```

* Operating system: OSX 10.11.6

### Current behavior

For this test:

```elixir
defmodule FooTest do
  use ExUnit.Case
  import ExUnit.CaptureIO

  test "1" do
    assert capture_io(fn ->
      Mix.Task.run("help", ["help"])
    end) != ""
  end

  test "2" do
    assert capture_io(fn ->
      Mix.Task.run("help", ["help"])
    end) != ""
  end
end
```

one of the examples (randomly) will fail with something like this:

```
  1) test 2 (FooTest)
     test/foo_test.exs:11
     Assertion with != failed
     code: capture_io(fn -> Mix.Task.run("help", ["help"]) end) != ""
     lhs:  ""
     rhs:  ""
     stacktrace:
       test/foo_test.exs:12: (test)
```

This error can be fixed by replacing `Mix.Task.run("help", ["help"])` with `Mix.Tasks.Help.run(["help"])` (as I did in https://github.com/phoenixframework/phoenix/pull/1941/files) but perhaps it's still worth fixing in ExUnit/Mix.

### Expected behavior

Both examples are passing.

cc @fishcakez

**Comment by ericmj** [comment]
`Mix.Task.run/1` will only run a given task name once unless you call `Mix.Task.reenable` for it.

**Comment by josevalim** [comment]
Yes, @ericmj is correct. :) Another option is to use `Mix.Task.rerun`, although I can't quite remember when it was added.
