### ISSUE TITLE
Adding unicode example to Regex docs

### ISSUE THREAD

**Issue by jbranchaud** [elixir-lang/elixir#5293]
The docs for Regex mention, toward the beginning, that the `u` modifier can be used for Unicode specific patterns. There are no examples of using it throughout the rest of the page though. I suggest adding an example to one of the function examples, e.g. for [`scan/3`](http://elixir-lang.org/docs/stable/elixir/Regex.html#scan/3):

```elixir
iex> Regex.scan(~r/\p{Sc}/u, "$, £, and €")
[["$"], ["£"], ["€"]]
```

This example has the added benefit of also showing off its use with unicode character categories.

If this seems like an agreeable approach, I'll go ahead and create a PR for it.

**Comment by josevalim** [comment]
Yes, please!
