### ISSUE TITLE
Errors in nested apps within an umbrella project have relative paths

### ISSUE THREAD

**Issue by uri** [elixir-lang/elixir#5309]
### Environment

```
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```

Operating system: macOS Sierra 10.12

### Current behavior

Compiling an umbrella project will show relative paths when there is an error:

```
# Running in ./umbrella_example
$ mix compile
==> nested_app
Compiling 1 file (.ex)

== Compilation error on file lib/nested_app.ex ==
** (CompileError) lib/nested_app.ex:3: undefined function beep_boop/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

Here is the structure of the example app I used:

```
├── README.md
├── _build
│   └── dev
│       └── lib
│           └── nested_app
│               └── ebin
├── apps
│   └── nested_app
│       ├── README.md
│       ├── config
│       │   └── config.exs
│       ├── lib
│       │   └── nested_app.ex
│       ├── mix.exs
│       └── test
│           ├── nested_app_test.exs
│           └── test_helper.exs
├── config
│   └── config.exs
└── mix.exs
```

### Expected behavior

Error message should reference `apps/nested_app/lib/nested_app.ex` instead of  `lib/nested_app.ex`.

**Comment by josevalim** [comment]
@uri yes, when compiling an application, we need to change into that application directory, hence we report this line:

```
==> nested_app
```

Unfortunately there isn't much we can do. Changing the directory into the application is essential in case developers are using relative paths and that will affect warnings and error reporting.
