### ISSUE TITLE
`String.replace_leading/3` goes into infinite loop

### ISSUE THREAD

**Issue by SekiT** [elixir-lang/elixir#5310]
### Environment

* Elixir version (elixir -v): 1.3.4
* Operating system: macOS Sierra

### Current behavior
It seems `String.replace_leading/3` goes into an infinite loop when the second argument is an empty string.

```elixir
iex> String.replace_leading("foo", "", "")
# never ends
```

### Expected behavior

`String.replace_leading("foo", "", "")` should be `"foo"` I think.

**Comment by josevalim** [comment]
It is fixed in master, thank you!
