### ISSUE TITLE
Doc test warning introduced in Kernel.++/2

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#5325]
My [latest commit on the `Kernel.++/2` function when dealing with improper lists](https://github.com/elixir-lang/elixir/commit/16b3e889bc8b66ea5fef616a19ee67a70862d990#diff-e06d5ebc2907d951188e88476f85af51R956) introduced a doctest warning when compiling Elixir.

```console
 ==> elixir (exunit)
warning: this expression will fail with ArgumentError
  (for doctest at) lib/kernel.ex:956
```

I would like if there is a way to suppress this warning.

**Comment by josevalim** [comment]
Compilation warnings cannot be silenced from tests. The only option is to remove the `iex>` and have a separate paragraph explaining it. I will change it in master. Thank you!

**Comment by eksperimental** [comment]
ok. thank you @josevalim
