### ISSUE TITLE
Bug in `mix test --timeout :infinity`

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#5337]
lib/mix/lib/mix/tasks/test.ex:168

OptionParser switches is set to integer, excluding `:infinity` as a valid option.

```console
$ mix test --timeout :infinity
** (Mix) Could not invoke task "test": 1 error found!
--timeout : Expected type integer, got ":infinity"
```

We are also allowing negative integers. the test will run, but we will get a:
`** (ErlangError) erlang error: :timeout_value`

**Comment by eksperimental** [comment]
I can volunteer to fix this if you guide me in the direction you want this issue to be solved.

**Comment by josevalim** [comment]
I think we should make `--timeout 0` become infinity. We already use something similar in `--seed 0`.

**Comment by eksperimental** [comment]
i think it can be confusing because in receive `0` and `:infinity` are totally different. one the opposite of the other.

**Comment by josevalim** [comment]
Alright, so to keep things simple, it is probably best to just use `--trace` or set a really high value, like 300000, that should be enough.

**Comment by eksperimental** [comment]
`--trace` is a good trick, but that doesn't solve the bug.
OptParser should accept every valid option.
if a boolean OR "`integer` OR `:inifity`" cannot be set, i think it will be better off to remove this switch, and let ExUnit deal with it.
the bad thing is that every test will have to be run with an invalid timeout.

**Comment by eksperimental** [comment]
how about just parsing "manually" this particular entry, mimicking OptParser switches?

**Comment by josevalim** [comment]
I think a high value or --trace will do for now. I would prefer to keep
things simple than add complexity for a quite rare use case.



-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
