### ISSUE TITLE
literal float is not a valid typespec

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#5351]
Code:

```elixir
  @spec div(number, 0.0) :: no_return
```

will throw:

```console
== Compilation error on file lib/specs.ex ==
** (CompileError) lib/specs.ex:8: unexpected expression in typespec: 0.0
```

In the typespecs page it is mentioned that 

    Literals
    
    The following literals are also supported in typespecs:
    
    type :: :atom                         ## Atoms
          | 1.0                           ## Floats
          | 1                             ## Integers
          | 1..10                         ## Integers from 1 to 10

and checking http://erlang.org/doc/reference_manual/typespec.html
I see that there is nothing that tells us we can use it.

I tried hacking kernel/typespec.ex adding `:float`  as a type, I guess the restriction comes from Erlang.
I can submit a PR fixing the docs, 
but just wanted to create an issue in case there is a way to support this.

**Comment by josevalim** [comment]
Yes, we should fix the docs. A PR is appreciated. :)

**Comment by eksperimental** [comment]
@josevalim same happens with
`improper_list(type1, type2)`

**Comment by eksperimental** [comment]
I will submit a PR with a fix to the docs, and a test that verifies everything expressed in the docs

**Comment by josevalim** [comment]
@eksperimental yup, we have only `maybe_improper_list`.

**Comment by eksperimental** [comment]
@josevalim actually, it should be replaced with: `nonempty_improper_list/2`

**Comment by eksperimental** [comment]
@josevalim Erlang's been bitten by the same documentation bug.
http://erlang.org/pipermail/erlang-bugs/2011-September/002576.html
it makes sense why there is not such a type.

**Comment by josevalim** [comment]
Thank you! I did not know that. :)

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
