### ISSUE TITLE
Raise a detailed error for default implementations for behaviours that currently exit/1

### ISSUE THREAD

**Issue by fishcakez** [elixir-lang/elixir#5356]
For example the `handle_call/3` implementation defined by `use GenServer` does `exit({:bad_call, req})`, we could raise an exception with a message explaining the situation.

**Comment by eidge** [comment]
I'm happy to tackle this.

From what I've found, exit/1 is only being used by:

`GenEvent - handle_call/2`
`GenEvent.Stream - handle_call/2 and handle_event/2`
`GenServer - handle_call/3 and handle_cast/2`

Thinking about throwing a ```__MODULE__.CallbackNotImplementedError``` with a message along the lines of:

"handle_call/3 is not implemented for #{msg}"

Does that make sense?

**Comment by josevalim** [comment]
@fishcakez please let us know which error you had in mind. :) I think a raise "message" may be enough too?

**Comment by fishcakez** [comment]
@josevalim yes exactly, a RuntimeError explaining why the function was called, what the request was, perhaps which process sent it and what can be done about it.
