### ISSUE TITLE
Weird diff colouring on simple case

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#5364]
the diff between these two strings give a really weird result

     left:  "@type(literal_map_with_arrow() :: %{optional(any()) => any()})"
     right: "@type(literal_map_with_arrow() :: %{any() => any()})"

![elixir_diff_wrong](https://cloud.githubusercontent.com/assets/9133420/19768580/43905610-9c82-11e6-8068-f09c61f64a28.png)

/cc @lexmag

**Comment by josevalim** [comment]
The diff does not have semantic understand of the string contents, so sometimes the behaviour above will happen.

**Comment by eksperimental** [comment]
thank you
