### ISSUE TITLE
is_map? returns unexpected result for regex

### ISSUE THREAD

**Issue by andyl** [elixir-lang/elixir#5368]
### Environment

Elixir 1.3.4 / Erlang 19 / Ubuntu 16.04

### Current behavior

`is_map?(~r/asdf/)` returns `TRUE`

### Expected behavior

`is_map?(~r/asdf/)` should return `FALSE`

Discussion: I'm a new elixir user.  This behavior surprised me and I spent 90 minutes figuring out what was going on.  After study, I came to understand the underlying implementation, the regex macro and internal representation.  But I believe this behavior violates the 'Principle of Least Surprise', it adds 'magic' to the language and makes Elixir more difficult to learn for new users.

**Comment by eksperimental** [comment]
there is no way for Elixir to know the difference between a regular map and a regex,
because as stated in the Regex module documentation:

> A Regex is represented internally as the Regex struct. Therefore, %Regex{} can be used whenever there is a need to match on them.

```elixir
iex(38)> (quote do: ~r/asdf/) |> Macro.expand(__ENV__)                   
{:%{}, [],
 [__struct__: Regex, opts: "",
  re_pattern: {:{}, [],
   [:re_pattern, 0, 0, 0,
    <<69, 82, 67, 80, 71, 0, 0, 0, 0, 0, 0, 0, 81, 0, 0, 0, 255, 255, 255, 255,
      255, 255, 255, 255, 97, 0, 102, 0, 0, 0, 0, 0, 0, 0, 56, 0, 0, 0, 0,
      ...>>]}, source: "asdf"]}

```

and structs are maps.

**Comment by eksperimental** [comment]
same happens with a range

```elixir
iex> is_map(1..2)
true
```

**Comment by josevalim** [comment]
Closing as @eksperimental explained.
