### ISSUE TITLE
Grammatical error in kernel docs

### ISSUE THREAD

**Issue by Jargonius** [elixir-lang/elixir#5374]
In [this file](https://github.com/elixir-lang/elixir/blob/v1.3.4/lib/elixir/lib/kernel.ex#L1100) it says, "Returns `true` if the two items are match."  I know what it means but it doesn't make grammatical sense.

**Comment by eksperimental** [comment]
this has been fixed in master
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L1081

**Comment by josevalim** [comment]
Thanks for reporting @Jargonius!

**Comment by Jargonius** [comment]
You're welcome!
