### ISSUE TITLE
Changelog for released versions (including 1.3.x series!) missing

### ISSUE THREAD

**Issue by pikeas** [elixir-lang/elixir#5383]

**Comment by ericmj** [comment]
You can find them here: https://github.com/elixir-lang/elixir/releases.

The changelog.md file only has the releases for the current minor version.

**Comment by pikeas** [comment]
The Releases page is non-obvious, changes should be in `CHANGELOG.md` and/or directly linked from http://elixir-lang.org/

**Comment by ericmj** [comment]
To me the releases page is the obvious place to find information about releases. The changelogs are also linked to at the end of every release blog post http://elixir-lang.org/blog/2016/06/21/elixir-v1-3-0-released/.

**Comment by pikeas** [comment]
But there's no blog post for point releases.

Me, this afternoon:

I'm working on an Elixir project for the first time in a while, so `brew upgrade`.
Hm, Elixir 1.3.4 was installed and I was on 1.3.1, let's see what's new.
Check Github CHANGELOG, nothing.
Check Elixir blog, nothing.
Google "elixir 1.3.4 changelog" - Releases page is 2nd result but summary doesn't have the string 1.3.4, so looks like nothing.
Post this issue.

**Comment by josevalim** [comment]
I have added a link to the end of every changelog that links to the changelog of the previous version.
