### ISSUE TITLE
Inaccurate error for function clause

### ISSUE THREAD

**Issue by pikeas** [elixir-lang/elixir#5384]
Elixir 1.3.4/OTP 19 on OS X 10.11.6.

    iex(3)> :http_uri.parse("http://foo")
    ** (FunctionClauseError) no function clause matching in :string.substr2/2

These functions exist in `:string`:

- sub_string/2
- sub_string/3
- substr/2
- substr/3

There is no function called `substr2/2`.

**Comment by pikeas** [comment]
Er, I'm mistaken. Looks like `substr2` exists if I search Erlang docs, but `h :string.substr2/2` fails to find it because Elixir isn't compiled with Erlang docs.

**Comment by josevalim** [comment]
There is no public function but there is a private one. If you check the stacktrace, you can see the path that led to substr2.

To fix the error you should use a charlist and not a string `:http_uri.parse('http://foo')` or prefer to use Elixir's own URI.parse that accepts strings. More information for integrating with Erlang here: http://elixir-lang.org/crash-course.html

**Comment by pikeas** [comment]
Yep, see my previous comment. :-)

However, I do think there's something interesting here. Is there any way for IEX's help function to know that `:string:substr2` exists but `:string:substr12345` doesn't, even when Erlang docs aren't compiled?
