### ISSUE TITLE
The doc of `Supervisor.start_link/2` maybe not very clear

### ISSUE THREAD

**Issue by Ljzn** [elixir-lang/elixir#5410]
```
  @doc """
  Starts a supervisor module with the given `arg`.
```
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/supervisor.ex#L298

We know a supervisor is a `process`, not a `module`. 

Maybe "Starts a supervisor process with the given `module` and `arg`." is better.

[This is erlang's document](http://erlang.org/doc/man/supervisor.html#start_link-2)

**Comment by whatyouhide** [comment]
Good catch @Ljzn! Do you feel like fixing this yourself and opening a PR or do you prefer me to take care of it? 👍

**Comment by Ljzn** [comment]
@whatyouhide  Sure! : )

**Comment by josevalim** [comment]
Thank you. Closing this in favor of the PR.
