### ISSUE TITLE
Warning in dependency is not under project's section in output log

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#5431]
```sh
./dialyxir$ mix do deps.get, compile, archive.build, archive.install
Running dependency resolution
* Getting ex_doc (Hex package)
  Checking package (https://repo.hex.pm/tarballs/ex_doc-0.14.3.tar)
  Using locally cached package
* Getting earmark (Hex package)
  Checking package (https://repo.hex.pm/tarballs/earmark-1.0.2.tar)
  Using locally cached package
warning: variable doc is unused
  tasks/readme.exs:83

==> earmark
Compiling 3 files (.erl)
Compiling 19 files (.ex)
Generated earmark app
==> ex_doc
Compiling 14 files (.ex)
Generated ex_doc app
==> dialyxir
Compiling 3 files (.ex)
warning: redefining module Dialyxir.Project (current version loaded from /home/eksperimental/.mix/archives/dialyxir-0.4.0/dialyxir-0.4.0/ebin/Elixir.Dialyxir.Project.beam)
  lib/dialyxir/project.ex:1

warning: redefining module Mix.Tasks.Dialyzer (current version loaded from /home/eksperimental/.mix/archives/dialyxir-0.4.0/dialyxir-0.4.0/ebin/Elixir.Mix.Tasks.Dialyzer.beam)
  lib/mix/tasks/dialyzer.ex:1

warning: redefining module Dialyxir.Plt (current version loaded from /home/eksperimental/.mix/archives/dialyxir-0.4.0/dialyxir-0.4.0/ebin/Elixir.Dialyxir.Plt.beam)
  lib/dialyxir/plt.ex:5

Generated dialyxir app
Generated archive "dialyxir-0.4.0.ez" with MIX_ENV=dev
Found existing archive: /home/eksperimental/.mix/archives/dialyxir-0.4.0.
Are you sure you want to replace it with "dialyxir-0.4.0.ez"? [Yn] y
* creating /home/eksperimental/.mix/archives/dialyxir-0.4.0
```

See al the warnings, are under their project section, but look at this one.

> warning: variable doc is unused
>   tasks/readme.exs:83

it should be under Earmark.

**Comment by ericmj** [comment]
Not related to this issue but the task inside `tasks/readme.exs` should be an alias or a proper mix task in `lib/`.

I don't know really how we can improve this except maybe changing the warning path from `tasks/readme.exs` to `deps/earmark/tasks/readme.exs` but that would be a hack. The warning comes from loading the dependency's `mix.exs` file and we have to load it at that stage to see if there are other dependencies to fetch.

@josevalim do you have any ideas?

**Comment by josevalim** [comment]
> Not related to this issue but the task inside tasks/readme.exs should be an alias or a proper mix task in lib/.

Probably an alias. You can even make it something like: [readme: "run tasks/readme.exs"]

> we have to load it at that stage to see if there are other dependencies to fetch.

I think we load it because we have to compile it. Hex deps do not load mix.exs until compilation. :)

> @josevalim do you have any ideas?

Unfortunately not yet.

**Comment by ericmj** [comment]
> I think we load it because we have to compile it. Hex deps do not load mix.exs until compilation. :)

Yes, but that means we can only fix this for Hex dependencies, git and path would still have the bug.

**Comment by josevalim** [comment]
@ericmj you are right. Unfortunately I don't think we can fix this without major changes, such as providing directory context to the warning system. :( I will mark this as unresolved.
