### ISSUE TITLE
GenServer.cast/2 different behaviour

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#5440]
Currently the implementation of `GenServer.cast/2` and `:gen_server.cast/2` differ slightly in how remote, not connected nodes, are handled. The Elixir version will try connecting synchronously to the node, while the erlang version will do this asynchronously spawning a process to do so.

Elixir: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/gen_server.ex#L796-L803
```elixir
  defp do_send(dest, msg) do
    try do
      send(dest, msg)
      :ok
    catch
      _, _ -> :ok
    end
  end
```

Erlang: https://github.com/erlang/otp/blob/maint/lib/stdlib/src/gen_server.erl#L401-L407
```erlang
do_send(Dest, Msg) ->
    case catch erlang:send(Dest, Msg, [noconnect]) of
	noconnect ->
	    spawn(erlang, send, [Dest,Msg]);
	Other ->
	    Other
    end.
```

Should the elixir version be changed to mirror the erlang one?

**Comment by fishcakez** [comment]
We purposefully used a different behaviour so that semantics were consistent for all naming schemes and so that we had ordering of messages. Unfortunately we do not have that ordering guarantee. I have changed the tag to `bug` because I think it is more important to highlight that we can't provide the guarantee we were trying to than the behaviour is different to `:gen_server`.

**Comment by fishcakez** [comment]
Sorry I misunderstood an email. We do provide this guarantee and it is documented as such. This would be a backwards incompatible change.

**Comment by michalmuskala** [comment]
If we're aiming for different semantics it makes a perfect sense to have different implementation. I wasn't aware of the semantic difference between `GenServer.cast/2` and `:gen_server.cast/2`. Is this something that should be explicitly indicated in the docs?

**Comment by jvf** [comment]
With the new auto-connect implementation in Erlang/OTP 21 (see [otp\_src\_21.0-rc1.readme](http://erlang.org/download/otp_src_21.0-rc1.readme)) the the behaviour of `GenServer.cast/2` and `:gen_server.cast/2` is now identical, neither of them is blocking the caller anymore. See #8407. 

It is my understanding that this also solves the ordering issue for `:gen_server.cast/2`.

**Comment by josevalim** [comment]
@jvf yes, it does. :)
