### ISSUE TITLE
Enum to_list odd behavior for range

### ISSUE THREAD

**Issue by jrissler** [elixir-lang/elixir#5443]
Not sure if I'm missing something here but this seems odd.

### Environment

Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.3

### Current behavior

iex(14)> b = Enum.to_list 41..55
')*+,-./01234567'

iex(15)> b = Enum.to_list 21..40
[21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

### Expected behavior

iex(14)> b = Enum.to_list 41..55
[41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]

**Comment by eksperimental** [comment]
yes, you are missing this ;-P
https://github.com/elixir-lang/elixir/wiki/FAQ#4-why-is-my-list-of-integers-printed-as-a-string

**Comment by jrissler** [comment]
@eksperimental I see - all valid ASCII - thanks!
