### ISSUE TITLE
GenServer terminating with "no process" very difficult to debug

### ISSUE THREAD

**Issue by scouten** [elixir-lang/elixir#5458]
### Environment

```
$ elixir -v
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```

Operating system: MacOS 10.11.6

### Current behavior

The following message occurs occasionally in a certain unit test:

```
23:29:48.175 [error] GenServer #PID<0.718.0> terminating
** (stop) no process
```

There is not enough context information here to determine what code was running at the time and how I might address this issue. I suspect that there's a race condition in my code in handling the shut down of a process group (maybe the processes aren't shutting down in a good sequence?), but after that, I'm totally guessing.

### Expected behavior

The message above would be accompanied by a stack trace or other context that helps me determine what code was running at the time of the fault.

This seems like a significant usability issue in the language.

**Comment by josevalim** [comment]
We have plans to overhaul GenServer errors and exits for Elixir v1.5. We will make those plans publicly available soon. However, for now, there is not much we can do as those reports are coming directly from Erlang.

@fishcakez do you have any suggestion on how to get more information in this case?

**Comment by fishcakez** [comment]
Can turn on Logger level :debug for more information in that log message. I
think we show more of that information on master when above debug. I would
guess it's due to {:stop, :noproc, state}, perhaps stopping with monitor
:DOWN reason. It could also be trapping exits and getting :noproc exit
signal from parent.

Neither have a stacktrace. Don't think crash report will help here.

**Comment by josevalim** [comment]
Ok, closing this as Ecto master will now show more information.

**Comment by michalmuskala** [comment]
Did you mean "Elixir master"?

**Comment by josevalim** [comment]
Yes sorry.
