### ISSUE TITLE
Warn if an attribute is defined but never read/used

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5463]

**Comment by ericmj** [comment]
Should all attributes when not used? What about attributes such as `@protocol` and `@for`?

**Comment by josevalim** [comment]
@ericmj you will need to write `_ = @protocol` and `_ = @for` similar to how you write for variables injected in the user code.

**Comment by ericmj** [comment]
Will it catch Module.get_attribute also or do I need to use the `@attribute` form?

**Comment by josevalim** [comment]
get_attribute one will also work.

**Comment by josevalim** [comment]
Closing in favor of the PR.
