### ISSUE TITLE
Make xref warnings "persistent"

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#5464]
Extracting discussion from https://github.com/elixir-lang/elixir/issues/5461#issuecomment-261413372

>Another issue I would like to discuss is warnings reported from the xref analysis. They are extremely helpful, but they only appear when a particular module is compiled. It might be tricky since you compile once, fix some other error and by compiling again you make sure the errors have gone away. But you forgot about one module that's not compiled again, and the warning is completely lost. If it's in the code that's rarely (or even never) touched, this can go unnoticed for very long. I'm speaking here from experience.
Would it be possible for the xref pass to record all the errors related to a particular application and emit them all each time this application is compiled (no matter if the particular module is or is not compiled in that pass)? I believe this would make the xref warnings much more useful.

**Comment by josevalim** [comment]
I have removed the comment from the other issue to keep that side organized.

I do believe we could do this. The warnings could be stored alongside the module until the module is recompiled.

Copying @antipax just in case he still wants to take care of his baby. :)

**Comment by antipax** [comment]
Yeah, happy to do this. Are you thinking of adding the warnings to the xref
manifest, or somewhere else?

**Comment by josevalim** [comment]
@michalmuskala apparently we always run xref through the whole project as soon as any file changed, so this is not a bug (and I have just verified this locally). If you have a way to reproduce this, please let us know.
