### ISSUE TITLE
Mix deps.get should fail if cyclic deps found

### ISSUE THREAD

**Issue by ardhitama** [elixir-lang/elixir#5487]
Transferred from: [https://github.com/hexpm/hex/issues/321](https://github.com/hexpm/hex/issues/321)

**Running `mix` throws**
`** (Mix) Could not sort dependencies. There are cycles in the dependency graph`

While running `mix deps.get` stalled the console.

The behavior should be similar.

**Env**
```
elixir -v
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```

**Code sample**

`App1`'s `mix.exs`

```
defp deps do
    [
...
     {:app2, in_umbrella: true},
...
   ]
  end
```

`App2`'s `mix.exs`

```
defp deps do
    [
...
     {:app1, in_umbrella: true},
     {:ex_admin, github: "smpallen99/ex_admin"},
...
   ]
  end
```

**Comment by tsubery** [comment]
I failed to reproduce the bug using [this code](https://github.com/tsubery/ex_issue5487) and either Elixir 1.3.4 or 1.4.0 and OTP 19.
There might be something else in the code that contributes to the stalling or it could be something in the code environment.
@ardhitama Can you check if you get stalling using my minimal reproduction?
We many need more info about the environment or the code depending on the outcome.

**Comment by ardhitama** [comment]
@tsubery still happened in 1.4.0, will create a sample project.

**Comment by AndrewDryga** [comment]
@ardhitama can you suggest whats wrong with @tsubery code. I also wasn't able to reproduce this issue.

**Comment by ardhitama** [comment]
Added single line
`{:ex_admin, github: "smpallen99/ex_admin"},`

To repro, `run mix deps.get`
