### ISSUE TITLE
Unused module attribute showing incorrect line number

### ISSUE THREAD

**Issue by TBK145** [elixir-lang/elixir#5490]
### Environment

* Elixir version (elixir -v):
```
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

IEx 1.4.0-dev (050780c)
```
* Operating system: Ubuntu 16.04

### Current behavior

If I compile a module with unused module attributes I get a warning with a wrong line number:
```
warning: module attribute @agent_key was set but never used
  lib/queue.ex:1
```
```bash
~$ grep @agent_key * -RIn
lib/queue.ex:67:  @agent_key  :uri
```
I know you're supposed to define module attributes at the top of your file, but even then, when defining multiple module attributes, you would have the same problem.

### Expected behavior

I would expect a warning to be given with `lib/queue.ex:67`.

**Comment by whatyouhide** [comment]
Hey @TBK145, thanks for the report. Can you show more code? I have a feeling this is related to `use`ing something 😄

**Comment by josevalim** [comment]
@whatyouhide it is a bug. I am pushing a fix soon.

**Comment by whatyouhide** [comment]
Oh, didn't expect that! Good job @josevalim :)
