### ISSUE TITLE
Quirk of the parser

### ISSUE THREAD

**Issue by ijunaid8088** [elixir-lang/elixir#5526]
### Environment

* Elixir & Erlang versions (elixir -v): 1.3
* Operating system: Ubuntu 14.04

### Current behavior
I accidentally attached `9` with `end` But it still running and giving me results, Is that fine or something wrong here? it should give me some error no?
```
  iex(15)> Enum.filter([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], fn(x) -> x >= 3 && x <= 9end) 
    [3, 4, 5, 6, 7, 8, 9]
```
### Expected behavior
some error?

**Comment by eksperimental** [comment]
actually, no spaces will throw no error
iex> Enum.filter([1,2,3,4,5,6,7,8,9,10],fn(x)->x>=3&&x<=9end)
[3, 4, 5, 6, 7, 8, 9]

**Comment by josevalim** [comment]
As @eksperimental said, the current behaviour is correct. :)
