### ISSUE TITLE
escript fails to start with "could not find application file: logger.app"

### ISSUE THREAD

**Issue by ivan** [elixir-lang/elixir#5529]
After 75e2ee0e37d79b9b596233bfc3b7e4987310427f, if you `mix escript.build` and have a

 ```elixir
  def application do
    # Specify extra applications you'll use from Erlang/Elixir
    [extra_applications: [:logger]]
  end
```

in your `mix.exs`, the compiled escript errors out with:

```
# ./escript_demo
Could not start application logger: could not find application file: logger.app
```

This is reproducible with an empty project created by `mix new` (just add an `escript: escript()` listing a `main_module`.)

Removing the `def application` makes the escript work, at least for escripts that don't need the logger.

**Comment by whatyouhide** [comment]
Fixed in #5534.
