### ISSUE TITLE
Float.parse/1 does not parse binaries with the format "-.x" and ".x"

### ISSUE THREAD

**Issue by sashaafm** [elixir-lang/elixir#5533]
### Description
I'm working with some floats right now, which are read from a data file and some of the read floats are in the format "-.x" and ".x". However, `Float.parse/1` returns `:error` and seems unable to parse floats in this format.

### Expected Behaviour
```
Float.parse("-.09") # => {-0.09, ""}
Float.parse(".09") # => {0.09, ""}
```

### Reasoning
I believe this is a valid behaviour for `Float.parse/1` since this notation is common in certain academic fields and/or certain countries.

If .`00523 / .423` is inputted into Google Search, Google's calculator accurately recognises the expression as `0.00523 / 0.423`.

### Environment
* Elixir & Erlang versions (elixir -v): Elixir 1.3.4; Erlang 19
* Operating system: MacOS Sierra

### Workarounds
Right now the only way I can seem to find to work around this issue is to use `String.starts_with?/2` and `String.replace/3` to change the binary to a recognisable format.

**Comment by whatyouhide** [comment]
Just wanted to mention that this behaviour may be expected given `.0123` is not valid Elixir syntax and will raise a syntax error.

**Comment by sashaafm** [comment]
Hello @whatyouhide, yeah we we're just talking about it in Elixir's Slack channel. I completely understand it goes against Elixir's syntax. However, since it's a common notation used outside of Elixir and since it's being parsed from a syntax outside of the language (i.e., from a binary which does not have to obey to the syntax), then in my point of view this behaviour should be reasonable for the function. But that's just my opinion, I'll go with whatever people think it's best for Elixir :)

**Comment by eksperimental** [comment]
I would say if you are reading for an external source you should create your own function to parse this format and convert it to Elixir's .
Same should be done if your format uses comma as a decimal separator. Float parse won't interpret it.

**Comment by josevalim** [comment]
Yes, parse is meant to stick with Elixir's own rules.
