### ISSUE TITLE
not false in []

### ISSUE THREAD

**Issue by lmshk** [elixir-lang/elixir#5544]
I am confused: why is `not false in []`, even though [`not` has higher precedence than `in`](http://elixir-lang.org/docs/master/elixir/operators.html)? I expected this to yield `false`.

### Environment

* Elixir & Erlang versions (elixir -v):

```
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.2`
```

* Operating system: Arch Linux (`4.8.11-1-ARCH`)

**Comment by eksperimental** [comment]
interesting.

`!/1` behaves the same way, but other operators with the same precedence behave differently.

```iex
iex> quote do not false in [] end |> Macro.to_string
"not(false in [])"

iex> quote do ! false in [] end |> Macro.to_string 
"!(false in [])"

iex> quote do + false in [] end |> Macro.to_string
"+false in []"

iex> quote do - false in [] end |> Macro.to_string
"-false in []"

iex> quote do ^ false in [] end |> Macro.to_string 
"^false in []"
```

**Comment by josevalim** [comment]
@eksperimental good catch. We should unify all unary operators to behave the same as `not` and `!` because `in` has higher precedence than unary operators.

**Comment by josevalim** [comment]
We should also fix the precedence table to mention the `UNARY left IN right` format. Thank you @lmshk!

**Comment by josevalim** [comment]
Actually, please ignore me. Making `+` and `-` behave the same as `not` and `!` will have unintended side-effects. We should probably deprecate the current special case with `not` and `!` and introduce a proper syntax, such as `not in`.

**Comment by antipax** [comment]
@josevalim is this ready for implementation? `not in` is something I've been desiring for a while, actually.

**Comment by josevalim** [comment]
@antipax yes, it is. We have agreed that the implementation should be at the lexical/parser level exclusively. I.e: `(x not in right)` will appear as `not(x in right)` in the AST. This means that we should also change `Macro.to_string/2` to show the proper conversion. We should also add a TODO to the parser where we rearrange `not x in right` so we emit a deprecation warning in the future.

**Comment by eksperimental** [comment]
@josevalim since this is a breaking change.
shouldn't we warn on the use `not foo in bar` and suggest people to use `foo not in bar`?

**Comment by josevalim** [comment]
@eksperimental it is not a breaking change. We are not going to change any behaviour but add a new one. "not foo in bar" will continue to behave as today even if wrong. The goal is to add a new functionality, emit warnings in the future and remove the wrong behaviour on Elixir 2.0.

**Comment by antipax** [comment]
Ok, starting on this!

**Comment by whatyouhide** [comment]
Can we close this @josevalim?
