### ISSUE TITLE
Apparent regression in `Access.key/2` in 1.4

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#5548]
### Environment

* Elixir & Erlang versions (elixir -v):

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.0-rc.1 (16a14c1)
```

* Operating system:

OS X El Capitan

### Current behavior

```  iex
iex(2)> get_in(%{}, [Access.key(:unknown), Access.key(:name)])
** (BadMapError) expected a map, got: nil
    (stdlib) :maps.find(:name, nil)
    (elixir) lib/map.ex:234: Map.get/3
    (elixir) lib/access.ex:403: anonymous fn/5 in Access.key/2
```

### Expected behavior

This exact example comes from the Elixir 1.3.4 `Access.key/2` docs:

https://hexdocs.pm/elixir/1.3.4/Access.html#key/2

...and as such, I expected it to continue working in 1.4, particularly since the changelog makes no mention of a change in `Access.key/2`.

It looks like eb30e709e54db4163dab6839234051b9137ad3bd is the source of the change, which makes it seem intentional. Can you explain the reasoning behind the change, @josevalim?

Given that this breaks an example in the Elixir 1.3.4 docs, it seems like an overly aggressive change that will appear to be a regression to users (it broke some things in my app, for example).  Also, since the introduction of `Access.key/2` and friends I've thought of `get_in(map, [:foo, :bar])` as being a short hand for `get_in(map, [Access.key(:foo), Access.key(:bar)])`.  Maybe that's not the right mental model, but it seems weird to me that `[:foo, :bar]` -- which is clearly trying to access the `:foo` and `:bar` keys -- behaves differently from the more explicit `[Access.key(:foo), Access.key(:bar)]`.

If this change is kept in Elixir 1.4, I'd ask that it is documented in the Changelog, please :).

**Comment by josevalim** [comment]
1. We should definitely fix this. No breaking change is acceptable on v1.4.

2. `Access.key/2` is different in two ways to `get_in(map, [:foo, :bar])`. `Access.key` is map specific while `get_in` works on maps, keywords and nil. This change makes it accept exclusively maps. It made no sense to support nil here. However, this is a breaking change when you are not using defaults so we need to fix that. I will introduce `Access.key/1` that warns and use the previous implementation.

Thank you for the reports! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by josevalim** [comment]
@myronmarston please give the v1.4 branch a try and let us know how it goes!

**Comment by myronmarston** [comment]
Thanks for the prompt fix!

I do want to push against this change a bit, though.  Sometimes you want to get a safely get value out of a data structure w/o worrying about what the exact structure is, as long as it supports key access.  `get_in(struct, [:a, :b])` does not work on structs, but `get_in(struct, [Access.key(:a), Access.key(:b)])` does, so using `Access.key` was a way to make the access work on just about anything you could throw at it.

With this change, there's apparently going to be no way going forward to do that.  I can use `get_in(term, [:a, :b])` to handle nils (particularly if `term` might be `nil`) but I can't use `Access.key` if there might be nils.  OTOH, if `term` might be a struct, I have to use `Access.key`, but if `term` could be nil it is going to fail.

More generally, it seems like a function named `Access.key` should work on any structure that has keys (such as a keyword list).  If the function is meant to work only on map keys, then maybe it should be named `Access.map_key` so that that is explicit.

**Comment by josevalim** [comment]
`get_in(term, [:a, :b])` would have to be rewritten as `term = term || %{}; get_in(term, [Access.key(:a, %{}), Access.key(:b)])`. Which is more verbose but quite more explicit. In ay case, I will reopen this because I want to make sure to discuss this with @lexmag and @whatyouhide.

**Comment by whatyouhide** [comment]
I personally prefer the over-explicit way. I think it's often better to have stricter functions and more code in the long term, it makes understanding and maintaining code easier.

If something *might* be `nil`, I definitely prefer to handle that possibility explicitly by doing something like `get_in(term || %{}, [Access.key(:a, %{}), Access.key(:b)])`. I think the `|| %{}` part is pretty concise and not too verbose, but it adds clarity and *intent* to the code.

What's the case against `term || %{}` if `term` might be `nil`? Is it just verbosity?

**Comment by myronmarston** [comment]
> What's the case against term || %{} if term might be nil? Is it just verbosity?

It feels inconsistent, given you can do `get_in(nil, [:a, :b])` -- why allow nil for one and not the other?

**Comment by josevalim** [comment]
@myronmarston because they are not equivalent? :)

The whole purpose of introducing Access.key and friends is to have a more specific way of traversing and accessing values. See for example `Access.all`, which is not about maps, structs or nils.

We could introduce another accessor, such as `Access.access`, that behaves exactly as `get_in(nil, [:a, :b])` but I don't think it would have any purpose beyond documentation?

**Comment by lexmag** [comment]
I feel that not allowing `nil` in `Access.key/2` is a great thing and move into right direction.
It indeed makes code more verbose but in exchange it makes code easier to comprehend and maintain.
Personally I have already experienced couple of times code like `get_in(%{}, [Access.key(:unknown), Access.key(:name)])` which was not easy to refactor because I wasn't sure if we actually should to consider `nil` values associated with intermediate keys or not.
In contrast with list of bare atoms `Access.key/2` gives us full control on how to express key access, thus it feels counterintuitive to make it more "magical" and let it handle `nil` values by default.

**Comment by myronmarston** [comment]
Thanks for the responses.  I think I agree now :).

**Comment by michalmuskala** [comment]
The main issue is that there's no way to work with structs in an easy way for the `_in` functions.

For static keys, everything is nice an shiny when working with both maps and structs:

```elixir
update_in(foo.bar.buz, &(...))
```

Unfortunately as soon as we need to introduce a dynamic value, it suddenly becomes extremely clunky in case of structs:

```elixir
update_in(foo.bar[key], &(...))
# vs
update_in(foo, [Access.key!(:foo), Access.key!(:bar), Access.key!(key)], &(...))
```

This is generally pushing me to work more with unstructured data in forms of maps, the usability difference is huge. The Access is a very powerful tool that helps to solve many problems in a concise way, it's unfortunate structs have such a poor support.

**Comment by josevalim** [comment]
@michalmuskala that's a very good point and we should probably move its discussion elsewhere. :)

**Comment by michalmuskala** [comment]
That's a good point. I'll send the issue to the core mailing list - that seems like a good place to continue the discussion.

**Comment by josevalim** [comment]
Closing this after feedback.
