### ISSUE TITLE
Please consider only soft-deprecating `Stream.uniq/2` until 1.5

### ISSUE THREAD

**Issue by myronmarston** [elixir-lang/elixir#5549]
### Environment

* Elixir & Erlang versions (elixir -v):

```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.0-rc.1 (16a14c1)
```

* Operating system:

OS X El Capitan

### Current behavior

I'm getting lots of these warnings when trying to upgrade my code base to 1.4:

```
warning: Stream.uniq/2 is deprecated, use Stream.uniq_by/2 instead
```

I tried changing the `Stream.uniq/2` calls to `Stream.uniq_by/2`, which fixes the warning, but breaks on Elixir 1.3 because `Stream.uniq_by/2` is a new API on 1.4.

Until 1.4 final is released, we are planning to run our project's travis CI builds on 1.3 and 1.4, to make sure we don't have "regressions" in all the warnings we've spent time fixing (such as changing `foo` to `foo()`).  Unfortunately, due to the deprecation of `Stream.uniq/2` in favor of an API that's not available on any prior versions, there's no way to have a working, warning-free code base on both 1.3 and 1.4 unless we abandon our usage of `Stream.uniq(_by)/2` entirely.

### Expected behavior

Given that Elixir commonly soft deprecates APIs in new releases, and later hard-deprecates them with a warning in a later release, I was under the impression that there was a policy of soft-deprecating APIs for at least one release before hard-deprecating them.  It seems like a reasonable policy: without it, it's hard for libraries to work on and be warning-free on multiple versions at the same time.  While there's not usually a need for libraries to work on lots of different versions, most libraries, particularly major ones like phoenix, need to support at least two versions (e.g. 1.3 and 1.4 once 1.4 is released) and as such I think it would be helpful for the community if the `Stream.uniq/2` deprecation could be postponed until 1.5.

On a side note, I expected my use of `--warnings-as-errors` to lead to a failure due to this deprecation warning, but it is not...which is good in my case, I guess (as it lets my travis build on 1.4 pass) but is `--warnings-as-errors` not meant to include deprecation warnings?

**Comment by whatyouhide** [comment]
Yep, that was my bad cause it was marked as "Deprecate by 1.5", but it clearly meant "soft-deprecate" and not "hard-deprecate". I will revert the warning for `Stream.uniq/2` and only soft-deprecated it if @josevalim is ok with it.

**Comment by josevalim** [comment]
Yes, we always need to wait at lesat two versions before emit warnings for deprecated feature. Please revert the warning @whatyouhide.

**Comment by whatyouhide** [comment]
Turned the hard deprecation into a soft deprecation in https://github.com/elixir-lang/elixir/commit/c599956de1e38e1ec6944b1fd0b22bc17a6c38ea on the 1.4 branch. Sorry for the trouble everyone!
