### ISSUE TITLE
Task.async_stream/5 is leaking messages

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#5554]
### Environment

* Elixir & Erlang versions (elixir -v): 
```
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.0-rc.0 (5e1b7d9)
```

### Current behavior
```elixir
iex(1)> Process.flag(:trap_exit, true)
false
iex(2)> [1] |> Task.async_stream(&(&1 * 2)) |> Stream.run
:ok
iex(3)> flush
{:EXIT, #PID<0.84.0>, :normal}
:ok
```

### Expected behavior

No message should be left in the inbox after `Task.async_stream/5` finishes regardless if process is trapping exists or not.

**Comment by josevalim** [comment]
@fishcakez should we also remove messages in case users are trapping exits? AFAIK we don't do it for `Task.async`.

**Comment by michalmuskala** [comment]
Without this it makes little sense to have the `{:exit, _}` return value in case caller is trapping exits, https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/task.ex#L293-L295, and encourage them in the documentation.

The process is flooded with the exit messages.

**Comment by josevalim** [comment]
@michalmuskala you can always use Task.Supervisor.async_nolink then. I am not sure we should clean up for side-effects you decided to cause in your own processes.

**Comment by michalmuskala** [comment]
It makes it very easy to use the `async_stream` function in a wrong way. And as far as I understand the point of introducing that function was that people were doing pmap in a wrong way.

Also the function will hijack the mailbox, and with long streams (you don't need that function for short streams) the messages build up really quickly. I only noticed this, because suddenly one of my processes had 10 000 messages appearing seemingly out of nowhere while it was doing IO in parallel using that function.

**Comment by josevalim** [comment]
@michalmuskala I understand that. I don't have anything to add beyond my previous reply. If you are trapping exits, *for now you need to use async_nolink*. Please give us time to figure out if we should rather document this behaviour or fix it.
