### ISSUE TITLE
`mix test` fails if an application in an umbrella has no `tests/test_helper.ex` file

### ISSUE THREAD

**Issue by talentdeficit** [elixir-lang/elixir#5556]
### Environment

* Elixir & Erlang versions (elixir -v):
```bash
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```
* Operating system:
ubuntu 16.04

### Current behavior

i have an umbrella application with one application that is headers only and has no tests

if i don't include `test/test_helper.ex` i get the following failure:
```bash
squirtle:some_project talentdeficit$ mix test --no-start
==> an_app_with_no_tests
** (Mix) Cannot run tests because test helper file "test/test_helper.exs" does not exist
```

if i include either an empty or minimal `test_helper.exs` i get:
```bash
squirtle:some_project talentdeficit$ mix test --no-start
==> an_app_with_no_tests
Test patterns did not match any file: 
```
(this at least returns a zero error code)
 

### Expected behavior

i'm aware of the `exclude` option for `mix test` but i think `mix test` can and should ignore any apps without tests rather than warning

**Comment by josevalim** [comment]
What if we make those be warnings instead of errors? Too much nuisance?

**Comment by talentdeficit** [comment]
warnings would be better than the current behaviour, but i don't think they would be very good warnings. presumably i know i don't have a `test` folder and have zero tests

**Comment by kelvinst** [comment]
@talentdeficit an idea of how to go with it is to configure your `Mix.Project` with: 
```elixir
use Mix.Project

def project do
  [ #...
   test_paths: [],
   deps: deps]
end
```

@josevalim I guess that a warning would be better than a raise too... Opening PR here.

**Comment by josevalim** [comment]
I like the test_path suggestion. Does it actually work?

**Comment by kelvinst** [comment]
Well, it depends on your concept of works. 😆 

It says `Test patterns did not match any file: ` on the output. Yes, with the ending colon, strange, but it actually says that because the resulting matcher for the list `[]` is empty.

But the shell returns a `0` response, so it does not fail the test like in the @talentdeficit case.

**Comment by talentdeficit** [comment]
what about only defaulting to '"test"' for test paths if it actually exists?

**Comment by kelvinst** [comment]
@talentdeficit the PR I've linked above does exactly this. ;)

**Comment by kelvinst** [comment]
@whatyouhide I guess the PR #5561 closed this. 😬
