### ISSUE TITLE
Donation to elixir-project

### ISSUE THREAD

**Issue by kandros** [elixir-lang/elixir#5563]
Hello, I would love to make a donation to the project, how can I do it?

**Comment by josevalim** [comment]
Thank you for prompting but the Elixir project does not take donations. Instead consider supporting another project in the ecosystem that you use, sponsoring ideas on Kickstart [such as Firestorm](https://www.kickstarter.com/projects/1003377429/firestorm-an-open-source-forum-in-phoenix-from-eli), getting learning resources available to support the authors or donating to a charity of your choice in name of Elixir.  :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by tobarja** [comment]
Given recent changes to the entities around Elixir, is this still the current stance? (3.5 years since original post seems like long enough to warrant asking again)

**Comment by kathgironpe** [comment]
Yeah... it seems like a good idea to donate since a lot of you guys work full-time on this.

**Comment by josevalim** [comment]
Thanks for asking! We still do not accept donations, my suggestion is to join to the [Erlang Ecosystem Foundation](https://erlef.org/) if you are an individual or sponsor it if you are company. Alternatively, donate to projects in the community, such as [Nerves](https://opencollective.com/nerves-project/), or the ones that you use in your apps. :)
