### ISSUE TITLE
Documentation improvement for File.dir?

### ISSUE THREAD

**Issue by sergiotapia** [elixir-lang/elixir#5565]
* Elixir & Erlang versions (elixir -v): 

Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.3.4

* Operating system:

MacOS Sierra

### Current behavior

Bug in the documentation.

https://hexdocs.pm/elixir/File.html#dir?/1

It says, "Returns true if the path is a directory." - what it doesn't say is that the path must be absolute for it to work properly.

### Expected behavior

Just update the documentation to let people know the path has to be absolute.

```
# This doesn't work:
iex(1)> File.dir?("~/Downloads/")
false

# This does:
iex(1)> File.dir?("/Application/")
true
```

**Comment by bbense** [comment]
"~/Downloads" is a shell convention. The file path does not have to be absolute, but it has to be a path that has any shell conventions expanded. 

iex> File.dir?("./docs") 

works just fine.

**Comment by ShallmentMo** [comment]
I try this:
```elixir
iex(1)> File.dir?("~/Downloads/")
false
iex(3)> File.dir?(Path.expand("~/Downloads/"))
true
```
Is it a bug?

**Comment by bbense** [comment]
No. The path "~/Downloads" does not exist in the file system.

**Comment by eksperimental** [comment]
as @ShallmentMo, the path is not expanded. `~` is a shell expansion.

> Path.expand(path)
> Converts the path to an absolute one and expands any . and .. characters and a leading ~.

in your shell, if you do: `ls "~"`, you will get
> ls: cannot access '~': No such file or directory

same thing happens here.
`~` is a shell expansion that happens

**Comment by eksperimental** [comment]
Maybe we should add an example explaining this, and how to solve it using `Path.expand/1-2`

**Comment by josevalim** [comment]
@eksperimental we should make it clear that paths given to `File` are not automatically expanded and relative paths will be taken into account from `File.cwd!`. Such belongs to the `File` moduledoc though and not to a specific function.

**Comment by eksperimental** [comment]
I can take care of this PR.

**Comment by josevalim** [comment]
Yes please!

**Comment by eksperimental** [comment]
@josevalim please assign me so I don't forget

**Comment by whatyouhide** [comment]
@eksperimental we cannot assign people that don't have commit access to Elixir :( If you can remember yourself that would be great, otherwise I can take care of the issue if you prefer :).

**Comment by eksperimental** [comment]
oh this was mentioned to me earlier in another project. no worries, I will try to remember this

**Comment by PotHix** [comment]
Since the last interaction was 6 days ago, I decided to try it and created the pull request mentioned above. Hope it helps.
