### ISSUE TITLE
Enum.take_random occasionally printing random character strings instead of lists

### ISSUE THREAD

**Issue by leishman** [elixir-lang/elixir#5573]
### Description

In iex when I call `Enum.take_random`, it occasionally prints a string of random characters instead of a properly formatted list. Here is an example of a call that causes this to occur:

```elixir
Enum.take_random(1..90, 9)
```

This usually returns something to the console like `[18, 21, 79, 31, 13, 86, 36, 16, 11]`. However, occasionally it returns something like `',R\'JM09%A'`.

I have not been able to reproduce this when passing in a `List` instead of a `Range` and not all ranges and selection size arguments cause this problem from what I can tell.

### Environment

```
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.4
```
### Current behavior

```elixir
iex(19)> Enum.take_random(1..90, 9)
[82, 64, 58, 27, 10, 39, 30, 9, 5]
iex(20)> Enum.take_random(1..90, 9)
[68, 87, 50, 23, 83, 36, 69, 30, 65]
iex(21)> Enum.take_random(1..90, 9)
[6, 52, 11, 54, 4, 82, 77, 44, 45]
iex(22)> Enum.take_random(1..90, 9)
[67, 66, 77, 43, 79, 39, 11, 28, 47]
iex(23)> Enum.take_random(1..90, 9)
[87, 77, 5, 7, 53, 79, 36, 4, 59]
iex(24)> Enum.take_random(1..90, 9)
[59, 54, 33, 84, 29, 3, 4, 62, 30]
iex(25)> Enum.take_random(1..90, 9)
'%U,B\r\'Z\v('
iex(26)> Enum.take_random(1..90, 9)
[85, 24, 70, 62, 54, 19, 40, 15, 36]
```

### Expected behavior
I would expect this function to always print a list of integers in the proper format

**Comment by ericmj** [comment]
Charlists are lists of integers, they are printed as charlists when the list of integers have valid ASCII chars. `'%U,B\r\'Z\v('` is actually a list of integers printed as charlist.

Check out this for more information http://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#char-lists

**Comment by leishman** [comment]
Right I assumed it was printing the ASCII representing the integers I just did not know if that was the expected behavior or if it was supposed to somehow know how to differentiate between an integer list and a charlist. Good to know. Thanks for the quick response.
