### ISSUE TITLE
Inconsistent behavior when overwriting alias in IEx

### ISSUE THREAD

**Issue by bobbypriambodo** [elixir-lang/elixir#5587]
### Environment

* Elixir & Erlang versions (elixir -v):
```
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.3.4
```

* Operating system: **OSX El Capitan**

### Current behavior

The problem originated from [this post](https://elixirforum.com/t/iex-shell-how-to-delete-overwrite-an-alias-in-the-shell/2967) in the Elixir Forum. The original problem was, in IEx, given two module names `ModuleA.Foo` and `Foo`, if we do `alias ModuleA.Foo`, we have no way to "re-alias" `Foo` to refer to original module name `Foo`. Illustrated as follows:

```elixir
# Given we have the following alias
iex> alias ModuleA.Foo
ModuleA.Foo
iex> Foo
ModuleA.Foo

# We can overwrite the Foo alias with other module
iex> alias ModuleB.Foo
ModuleB.Foo
iex> Foo
ModuleB.Foo

# We can also overwrite it by aliasing another module
iex> alias Bar, as: Foo
Bar
iex> Foo
Bar

# Now, if we go back to ModuleA.Foo
iex> alias ModuleA.Foo
ModuleA.Foo

# We can't re-alias Foo to point to the module "Foo" using Elixir.Foo
iex> alias Elixir.Foo
Foo # seemed to work
iex> Foo
ModuleA.Foo # but it doesn't

# Same goes if we used :as
iex> alias Elixir.Foo, as: Foo
Foo
iex> Foo
ModuleA.Foo
```

From the forum post, José pointed out that this is a bug.

### Expected behavior

We can overwrite the alias, like so:

```elixir
iex> alias ModuleA.Foo
ModuleA.Foo
iex> alias Elixir.Foo
Foo
iex> Foo
Foo
```

**Comment by lexmag** [comment]
Closing in favour of the PR.
