### ISSUE TITLE
Add `System` function that raises if ENV var is not present

### ISSUE THREAD

**Issue by mwean** [elixir-lang/elixir#5608]
Continuing from this forum discussion: https://groups.google.com/forum/#!msg/elixir-lang-core/yw54VGwGkt4/GGoh7ZEmFAAJ

The current method of getting ENV variables is `System.get_env`, but this returns `nil` if the variable is missing. This can lead to confusing errors if not explicitly handled, so it would be nice to have `fetch_env` and `fetch_env!` functions that would return an error tuple or raise on missing variables. This will fail fast and make it easier to debug.

**Comment by josevalim** [comment]
Please see rationale for closing this on #5608.

**Comment by joeellis** [comment]
Was also looking for this but noticed the posted rationale link just goes to this page.  I assume @josevalim meant to post the PR where it was discussed, you can find that here: https://github.com/elixir-lang/elixir/pull/5610#issuecomment-270127996
