### ISSUE TITLE
Dependencies have diverged for App using umbrella using umbrella

### ISSUE THREAD

**Issue by jdmiranda** [elixir-lang/elixir#5622]
### Precheck

Different but related to https://github.com/elixir-lang/elixir/issues/4684

### Environment

* Elixir & Erlang versions (elixir -v): Erlang 19, Elixir 1.4.0
* Operating system: OSX

### Current behavior

mix deps.get fails when an umbrella dep has an umbrella dep for a dependency. Previously working on 1.3.4 . I upgraded to 1.4.0 and fails. As the issue above suggests I override: true at the root application. This allows you to get past mix deps.get but will fail when you try to mix deps.compile --all. There will be an error for file not found because the path to the leaf dep will have the wrong path. I can toggle between versions to reproduce. 

### Expected behavior
 The expected behavior is for the nesting of umbrella applications to resolve dependency locations as was done on version 1.3.4. 

I reviewed the release log and don't see anything that would cause such behavior. https://github.com/elixir-lang/elixir/releases/tag/v1.4.0

**Comment by josevalim** [comment]
Yes, this is definitely a regression. Can you provide a sample application that reproduces the error? We will look into it and work on a fix.

**Comment by jdmiranda** [comment]
I will create a sample app this weekend

**Comment by jdmiranda** [comment]
The sample application can be found [here](https://github.com/jdmiranda/umbrella_error_example). To reproduce 

1. `brew switch elixir 1.3.4` 
2. cd node_two
3. `mix deps.get`
4. `iex -S mix`. Works fine. 
5. Now to make it fail. `mix deps.clean --all`
6. `brew switch elixir 1.4.0`
7. `mix deps.get` 

Error message should be  

> Dependencies have diverged ..

**Comment by KallDrexx** [comment]
I seem to be getting this as well and I'm not clear how to fix it.  Repro can be done by checking out https://github.com/KallDrexx/elixir-media-libs/tree/9550729a75006d9c447789462609c638397a16ab and typing `mix compilie` for the umbrella app.  It causes the very confusing `Dependencies have diverged` error with no obvious way to fix it.

Building each application one at a time works just fine, and there's pretty much no code at the umbrella level.

**Comment by josevalim** [comment]
I will investigate those two apps today. Thank you @jdmiranda and @KallDrexx.

**Comment by josevalim** [comment]
@KallDrexx in your case, your umbrella children have conflicting definitions. "apps/gen_rtmp_server" depends on rtmp but rtmp is also an umbrella child. In such scenarios, you must depend on rtmp using `in_umbrella: true`. Another way to put this: if you are publishing your packages, then the umbrella setup is not going to work for you, because umbrellas expect dependencies between children to happen locally (and not via hex).

**Comment by jdmiranda** [comment]
@josevalim i don't think my issue was the same as @kalldrex since for me versions are all the same. My issue is with having an umbrella as a dep for a dep that is an umbrella. which creates different relative paths . both have 'in_umbrella: true'

**Comment by josevalim** [comment]
@jdmiranda yup, your issue is different and it has been fixed on master and v1.4. When we release v1.4.2, it should be good to go! Thank you for the app, it helped a lot! :heart:

**Comment by jdmiranda** [comment]
least i could do for all the work you've done. Thanks for the update.
