### ISSUE TITLE
Regex.escape/1 does not escape "-"

### ISSUE THREAD

**Issue by jonnystorm** [elixir-lang/elixir#5624]
While it is, arguably, correct behavior to not escape "-", it is easy to encounter problems while "composing" regular expressions via string interpolation, prior to using Regex.compile/1 or Regex.compile!/1.

In the examples I give below, imagine the escaped string is named `comment_delim` and that the intent is to match any one of the possible comment delimiters, including "-", rather than match a range of characters.

One obvious concern is that users expecting ranges to be preserved by Regex.escape/1 would necessarily have their code broken by changing this behavior. For this reason, I certainly understand that even a favorable review of this issue may not result in correction before Elixir 1.5, if ever.

### Environment

"-" remains unescaped as recently as master.

### Current behavior

```elixir
iex> Regex.match? Regex.compile!("[" <> Regex.escape("!-#") <> "]"), "!"
true
iex> Regex.match? Regex.compile!("[" <> Regex.escape("!-#") <> "]"), "-"
false
iex> Regex.match? Regex.compile!("[" <> Regex.escape("!-#") <> "]"), "#"
true
```

### Expected behavior

```elixir
iex> Regex.match? Regex.compile!("[" <> Regex.escape("!-#") <> "]"), "!"
true
iex> Regex.match? Regex.compile!("[" <> Regex.escape("!-#") <> "]"), "-"
true
iex> Regex.match? Regex.compile!("[" <> Regex.escape("!-#") <> "]"), "#"
true
```

**Comment by josevalim** [comment]
I believe it is a bug, so regardless if developers were relying on it, we should fix it. A PR is appreciated.

**Comment by Eiji7** [comment]
@josevalim: Currently Elixir escape these characters: `.^$*+?()[]{}\|#` + white space matcher: `\s`:
```elixir
{:ok, pattern} = :re.compile(~S"[.^$*+?()\[\]{}\\\|\s#]", [:unicode])
```

1. Elixir allows for named capture with `<` and `>` characters. Should these characters be also escaped?

2. If we are escaping white space matcher then why we do not escape other special matchers?
**\S** - `Any non-whitespace character`
**\d** - `Any digit`
**\D** - `Any non-digit`
**\w** - `Any word character`
**\W** - `Any non-word character`
**\b** - `A word boundary`
**\B** - `Non-word boundary`

**Comment by jonnystorm** [comment]
@Eiji7 Not to put words in his mouth, but here is a post from José explaining this behavior on [elixir-lang-core](https://groups.google.com/d/msg/elixir-lang-core/7KxqS9FW5vw/0Sd__0FHDQAJ).

That aside, it looks like someone else made that PR before I had time to finish my coffee for the morning. :)

**Comment by Eiji7** [comment]
@jonnystorm: This post is about `&Regex.compile/1`, so I do not know why you linked it. José wrote there about escaping `'\d` and `\w` that I understand (see my test in linked gist - matchers are escaped as: `\\d`).
I saw also PR, but there is only fix for `-` character. I also wrote tests for all cases: **meta characters**, **special matchers** and **whitespaces**. Hope my gist will help.

**Comment by josevalim** [comment]
@Eiji7 thanks for the extra cases.

The reason why whitespace is escaped is because some regex modes, such as `x`, ignore whitespaces.

And afaik we don't need to escape the named capture characters because we already escape `?` and escaping `?` is enough to disable the named capture.

**Comment by Eiji7** [comment]
@josevalim: Thanks for response. If you are interested in I updated my gist based on what you described: [Eiji/regex_test.exs](https://gist.github.com/Eiji7/2673730dbc25256087ced38e6f6b34ae). All tests passed!

**Comment by josevalim** [comment]
Thanks for checking master! :heart:
