### ISSUE TITLE
Unexpected Macro.underscore/1 behavior with screaming snake case

### ISSUE THREAD

**Issue by dantswain** [elixir-lang/elixir#5627]
This may not be a bug so much as an incorrect expectation on my part, but I couldn't find it reported otherwise.

### Environment

Tested with Erlang/OTP 19, Elixir 1.3.4 and 1.4.0

### Current behavior

```
iex(1)> Macro.underscore("FOO_BAR")
"fo_o__bar"
```

### Expected behavior

I would expect `"foo_bar"` or some variation on that.  I know this isn't precisely what `Macro.underscore/1` advertises to do, but I'm trying to use it to turn a not-quite-arbitrary string (may represent, e.g., a function name in another language) into a valid Elixir function name.  Regardless, the output `"fo_o__bar"` seems odd.

**Comment by dantswain** [comment]
FWIW This produces the expected result:

```
iex(3)> "FOO_BAR" |> String.split("_") |> Enum.map(&Macro.underscore/1) |> Enum.join("_")
"foo_bar"
```

**Comment by Eiji7** [comment]
Similar:
```elixir
Macro.underscore("Foo_Bar")
"foo__bar"
```

**Comment by eksperimental** [comment]
I think it is a bug,
also see the behaviour of the "reverse" function

``iex
iex>  Macro.camelize("FOO_BAR")  
"FOO_BAR"
```

**Comment by Eiji7** [comment]
I created my version of `&Macro.underscore/1` with test for bots implementations: [MyMacroUnderscore](https://gitlab.com/ex-open-source/my_macro_underscore).
What do you think about it?
