### ISSUE TITLE
Calendar does not have a `time_to_string/1` callback.

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#5628]
### Environment

* Elixir & Erlang versions (elixir -v): Elixir Master, 1.5.0-dev
* Operating system: Linux Mint 17.02

### Current behavior

As [can be seen in the source code of Calendar](https://github.com/elixir-lang/elixir/blob/f161cdb33da38f0168821b4d421b5108bb23d041/lib/elixir/lib/calendar.ex#L87), it contains callbacks for `date_to_string/1`, `datetime_to_string/1` and `naive_datetime_to_string/1`. `time_to_string/1` is mysteriously lacking.

Looking down in the [String.Chars implementation for Time](https://github.com/elixir-lang/elixir/blob/f161cdb33da38f0168821b4d421b5108bb23d041/lib/elixir/lib/calendar.ex#L767) as well as [`Time.to_string/1`](https://github.com/elixir-lang/elixir/blob/f161cdb33da38f0168821b4d421b5108bb23d041/lib/elixir/lib/calendar.ex#L566), we see that at both places, Calendar.ISO has been hard-coded.

### Expected behavior

I think a `time_to_string/1` callback should be added to the Calendar behaviour. 
To deprecate the current behaviour, a warning could be shown when `Time.to_string/1` or `String.Chars.Time.to_string/1` is being called with a calendar that does not yet have it implemented.

**Comment by josevalim** [comment]
We assumed so far that all calendar implementations shared the same notion of time. That's why there is no `:calendar` field in the time struct. We can add the calendar field to the time struct although I would like to wait for the results of your research if supporting other times is actually possible.

**Comment by josevalim** [comment]
I will close this while we work on #5603. We can revisit it later although we will probably end-up with the conclusion that we only support HH:MM:SS times by default.
