### ISSUE TITLE
Add e/1 to IEx.Helpers that lists all exports in a module

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5633]
Today you can press `ModuleName.<TAB>` to find all functions+macros in a given module but such  is not compatible across operating systems. For example, IEx on some Windows terminals do not support it.

So the goal is to provide a `e/1` function that list functions and macros in the same way the autocomplete would. Notice we already have a function for listing many entries using tabs in the `ls` implementation.

We should make the `module_info_funs/1` in IEx.Autocomplete public (and probably rename it to `exports/1`).

**Comment by michalmuskala** [comment]
Why `e` and `exports`? As far as I can tell, nowhere in elixir we're referring to exported functions - it's only public and private functions.

I would propose something slightly different instead - a function that would print all functions in a module with the first line of documentation - exactly what is done today in ex_doc at the beginning of module. This would be truly useful when looking for an appropriate function.

**Comment by josevalim** [comment]
> Why e and exports? As far as I can tell, nowhere in elixir we're referring to exported functions - it's only public and private functions.

See `function_exported?/3` and `macro_exported?/3` in Kernel.

> I would propose something slightly different instead - a function that would print all functions in a module with the first line of documentation

I thought about so but if I want to quickly see all the functions available in a given module, this format becomes too verbose. Ideally we would have both options but hopefully most function names are descriptive enough to give you a good idea about what it does.
