### ISSUE TITLE
Dialyzer errors when matching Date and Time structs

### ISSUE THREAD

**Issue by sasa1977** [elixir-lang/elixir#5634]
### Environment

* Erlang 19.1, Elixir 1.4.0

### Current behavior

Migrating from Elixir 1.3.4 to Elixir 1.4 produced some dialyzer warnings related to date/time types, when pattern matching on those types. A simple example would be:

```elixir
defp map_parameter(%Date{} = date), do:
  Date.to_erl(date)
```

Which produces

```
The call 'Elixir.Date':to_erl(date@1::#{'__struct__':='Elixir.Date', _=>_}) breaks the contract ('Elixir.Calendar':date()) -> calendar:date()
```

I tried playing with explicitly matching on required fields in `Calendar.date`. For example, this works:

```elixir
defp map_parameter(%{calendar: _, year: _, month: _, day: _} = date), do:
  Date.to_erl(date)
```

However, any extra field in the map is not allowed, so following will trigger a dialyzer error:

```elixir
defp map_parameter(%Date{calendar: _, year: _, month: _, day: _} = date), do:
    Date.to_erl(date)

defp map_parameter(%{calendar: _, year: _, month: _, day: _, __struct__: Date} = date), do:
    Date.to_erl(date)
```

Looking at [date type definition](https://github.com/elixir-lang/elixir/blob/f045705ac559290866abda5f9daeac4b701b6e7f/lib/elixir/lib/calendar.ex#L54), I wonder if it should also contain `optional(any) => any`. 

I tried changing the spec in my local Elixir build to:

```elixir
@type date :: %{:calendar => calendar, :year => year, :month => month, :day => day, optional(any) => any}
```

And that fixed the problem. 

So my impression is that a spec `%{foo: bar}` doesn't allow other fields in the map. I didn't pursue this further to verify on a simpler example though.

### Expected behavior

When matching `%Date{}` or `%Time{}` I don't expect dialyzer complaining when passing the matched arg to functions such as `Date.to_erl`. I'm unsure whether typespecs in `calendar.ex` should be changed (as I explained above), or maybe the problem is that `%{foo: bar}` should generate the `optional` part implicitly.

**Comment by fishcakez** [comment]
I believe we should have `optional(any) => any` because the alternative does not allow expressing limited key maps.

**Comment by sasa1977** [comment]
In that case, maybe a support for `...` might be useful, so we can write something like `%{foo: bar, ...}` instead of `%{:foo => bar, optional(any) => any}`. Regardless of that, I'd like to see the calendar typespecs fixed in the next patch release, so even if you agree with the ellipsis syntax, that should probably be done separately, for the next minor version.

If/when the decision on this is final, i.e. it is agreed that `optional(any) => any` is the immediate fix, I can prepare the PR.

**Comment by josevalim** [comment]
> So my impression is that a spec %{foo: bar} doesn't allow other fields in the map.

This is weird because I would expect that spec to match any map that has the field :foo with value of type bar. Exactly how maps work in matches.

I wonder if the problem is Elixir using `#{'__struct__':='Elixir.Date', _=>_}` for structs.

**Comment by josevalim** [comment]
Please ignore me. `optional(any) => any` is apparently the way to go. @sasa1977 please submit a patch, I will backport it to 1.4 as well.

**Comment by fishcakez** [comment]
Note that `%{optional(any) => any, foo: :bar}` will work (as it does with keyword syntax).
