### ISSUE TITLE
mix: possible bug in eval of rebar.config.script

### ISSUE THREAD

**Issue by tuncer** [elixir-lang/elixir#5645]
As originally reported by @guitarmind in https://github.com/tuncer/re2/issues/18, for some reason when re2 is built indirectly via mix (and then rebar), it fails at evaluating `rebar.config.script`. It specifically seems to fail with `{badmatch,undefined}` when trying to `application:get_key(rebar, vsn)`, which should never fail.

How does mix process rebar projects? Even if one calls the Erlang API of the rebar escript archive, it will make sure to load the app first. I don't know why it fails and cannot reproduce it with rebar or rebar3.

**Comment by josevalim** [comment]
Thank you for reporting it upstream.

**Comment by ericmj** [comment]
We can't set application keys for other applications and we can't load rebar into the VM because we need to support both rebar2 and rebar3 and they use the same application name. I think if your project wants to support mix it should match against `undefined` and/or and a check for `application:get_key(elixir, vsn)`.

**Comment by tuncer** [comment]
Hi, @ericmj. I'm not sure I understand. How does mix invoke rebar? It can officially be invoked either via the escript archive Erlang API (which loads the app) or more fitting for mix, as you want to invoke either rebar2 or rebar3 from the same VM, by spawning an OS process. It sounds like neither the official API nor the rebar executable is run. So, unless I'm misinterpreting your comment, and this is actually the case, it's unfortunately incorrect and a fragile approach. Also, given that build processes naturally spawn more than a few OS processes anyway, executing rebar outside the VM makes sense and cannot be argued against in the name of efficiency. I would suggest to treat rebar like any other external tool and spawn it.

Some background, as it seems there might be confusion what the rebar version is used for: depending on the rebar version, and in order to not break builds on any supported platform and Erlang/rebar/CXX combo, the config script emits the appropriate terms. Right now I cannot remove the compatibility code, but even if in the future it might be feasible to do so, running the rebar like any other OS process will still be the most reliable approach.

**Comment by ericmj** [comment]
> It sounds like neither the official API nor the rebar executable is run. So, unless I'm misinterpreting your comment, and this is actually the case, it's unfortunately incorrect and a fragile approach.

The escript executable is run to compile the application but we need to evaluate the rebar script to correctly determine what dependencies to fetch since it's mix fetching and resolving dependencies.

> Some background, as it seems there might be confusion what the rebar version is used for: depending on the rebar version, and in order to not break builds on any supported platform and Erlang/rebar/CXX combo, the config script emits the appropriate terms. Right now I cannot remove the compatibility code, but even if in the future it might be feasible to do so, running rebar like any other OS process will still be the most reliable approach.

I understand that you need the version but if you want your project with other build tools than rebar it needs account for those other build tools. Mix will correctly compile the vast majority of rebar projects, but some projects will break due to the rebar.config.script such as yours and then the project needs custom code if it wants to support mix.

**Comment by tuncer** [comment]
> Mix will correctly compile the vast majority of rebar projects, but some projects will break due to the rebar.config.script such as yours and then the project will need custom code if it wants to support mix.

rebar projects regularly use this kind of scripting or even more complex custom plugins, and if they cannot rely on the fact that the rebar app has been loaded, then the behavior is undefined. That means, there's nothing unofficial or experimental done here.

**Comment by tuncer** [comment]
> The escript executable is run to compile the application but we need to evaluate the rebar script to correctly determine what dependencies to fetch since it is mix fetching and resolving dependencies.

That explains the error, and I'm afraid evaluating rebar.config.script, assuming the environment you gave it yourself is enough, is a bug and not something one can expect script writers to account for. After all, the script was written for rebar.

**Comment by ericmj** [comment]
> rebar projects regularly use this kind of scripting or even more complex custom plugins, and if they cannot rely on the fact that the rebar app has been loaded, then the behavior is undefined. That means, there's nothing unofficial or experimental done here.

Yes, it is fairly common but only projects accessing keys from the rebar application will break and in this case it's a fairly easy workaround although it's unfortunate it is needed.

> That explains the error, and I'm afraid evaluating rebar.config.script, assuming the environment you gave it yourself is enough, is a bug and not something one can expect script writers to account for. After all, the script was written for rebar.

It can be seen as a bug but in this case we cannot fix the bug so there's not much we can do. If you have a fix for the bug then we are very interested to hear it of course.

**Comment by tuncer** [comment]
I suppose it's too late now, but I wish the rebar project had been contacted when partially reimplementing rebar.config.script evaluation for the sole purpose of extracting the deps list.

That said, given the situation, I think the following can work:

1. the vast majority of projects will have most if not all deps already in rebar.config and only override/extend in rebar.config.script. So, if it's okay to have a partial list of deps, then fetching deps only from rebar.config is sufficient.
2. when running file:script(rebar.config.script), mix can make available the rebar versions it will use, but this will force scripts to be aware of it and is not something you can expect script writers to do

**Comment by tuncer** [comment]
> Yes, it is fairly common but only projects accessing keys from the rebar application will break and in this case it's a fairly easy workaround although it's unfortunate it is needed.

I cannot work around it, because I cannot decide what to do in that case but let it fail early. Trying by selecting either list of terms doesn't make sense.

**Comment by tuncer** [comment]
> It can be seen as a bug but in this case we cannot fix the bug so there's not much we can do. If you have a fix for the bug then we are very interested to hear it of course.

I'm afraid it's a bug in a partial rebar config loader emulator and it would be hard to argue for scripts to support the emulator.

**Comment by tuncer** [comment]
Another reliable approach is to load and unload the rebar application when evaluating rebar scripts, using the escript archive just like you would use it via its official Erlang API after adding the escript archive to the code path. If you do that, you could of course also use the API and choose to not spawn the rebar executable.

**Comment by tuncer** [comment]
Another solution is to execute `rebar list-deps` and capture the output.

**Comment by josevalim** [comment]
>  If you do that, you could of course also use the API and choose to not spawn the rebar executable.

@tuncer unless this changed with rebar3, rebar2 unfortunately had no official Erlang API we could invoke. This was our very first choice early on.

**Comment by tuncer** [comment]
rebar2 had an API to run it from the VM just like you would from the shell. This was added way back in rebar.beam as extra entry points (unused by rebar's main escript entry point) for callers inside a running VM. It's rebar:run.

**Comment by josevalim** [comment]
I don't know if you would like to do this, but this code would support Mix, Rebar3 and Rebar2:

```erlang
LDFLAGS = case application:get_key(rebar, vsn) of
              {ok, Rebar2Vsn} when Rebar2Vsn < "2.6.4" ->
                   [{"(linux|freebsd|solaris)",
                    "LDFLAGS", "$LDFLAGS -l" ++ WhichCPPLib()}]
             _ ->
               []
end.
```

**Comment by ericmj** [comment]
> the vast majority of projects will have most if not all deps already in rebar.config and only override/extend in rebar.config.script. So, if it's okay to have a partial list of deps, then fetching deps only from rebar.config is sufficient.

That's not our experience. This is the first time I hear of a bug like this and I know of other projects that will not work if deps are missing from rebar.config.script. hackney is one such popular project.

> when running file:script(rebar.config.script), mix can make available the rebar versions it will use, but this will force scripts to be aware of it and is not something you can expect script writers to do.

Sure, we can do that but in that case the "bug" will still exist.

> I cannot work around it, because I cannot decide what to do in that case but let it fail early. Trying by selecting either list of terms doesn't make sense.

As I said above you can default to rebar3 if the key is not defined and/or check if the mix application is available. Mix will use a rebar2 version where this bug is fixed.

> I'm afraid it's a bug in a partial rebar config loader emulator and it would be hard to argue for scripts to support the emulator.

Okay, if you don't want to support that is of course perfectly fine. It is your choice.

> Another reliable approach is to load and unload the rebar application when evaluating rebar scripts, using the escript archive just like you would use it via its official Erlang API after adding the escript archive to the code path. If you do that, you could of course also use the API and choose to not spawn the rebar executable.

I get `{error, bad_directory}` when adding escript to the load path. We also like to avoid loading external applications into the VM since user applications, with potential conflicts, run in the same VM.

> Another solution is to execute rebar list-deps and capture the output.

That may work for rebar2 but not for rebar3 since overrides from parent dependencies will not apply.

**Comment by josevalim** [comment]
> rebar2 had an API to run it from the VM just like you would from the shell. 

You are right. I misspoke. :)

**Comment by tuncer** [comment]
@josevalim, `rebar:run/2` since 2012.

**Comment by tuncer** [comment]
> That's not our experience. This is the first time I hear of a bug like this and I know of other projects that will not work if deps are missing from rebar.config.script. hackney is one such popular project.

Usually, rebar.config.script in the context of deps is used to add or maybe replace deps if certain environment coditions are met. This means rebar.config has the full set for a project to build and work in production. This doesn't mean a project could not list zero deps in rebar.config and construct the term exclusively in rebar.config.script.

**Comment by tuncer** [comment]
> > when running file:script(rebar.config.script), mix can make available the rebar versions it will use, but this will force scripts to be aware of it and is not something you can expect script writers to do.
> >
> Sure, we can do that but in that case the "bug" will still exist.

Exactly, and you'd put the burden of being mix-compatible on projects that don't use mix. It would be HTML compatibility chaos all over, just very limited in scope.

**Comment by tuncer** [comment]
> Mix will use a rebar2 version where this bug is fixed.

I could fix this particular script by assuming that mix has the newest rebar because it downloads its own version, but that would still leave room for other errors in scripts that do not expect to be evaluated in a partial emulation.

**Comment by ericmj** [comment]
> Usually, rebar.config.script in the context of deps is used to add or maybe replace deps if certain environment coditions are met. This means rebar.config has the full set for a project to build and work in production. This doesn't mean a project could not list zero deps in rebar.config and construct the term exclusively in rebar.config.script.

Again, this is not our experience in practice.

Unfortunately using the API will not work since rebar3 with all its dependencies can not run in the same VM as user code since the dependencies can conflict with the user's dependencies. Since using the API would only work for rebar2 we are not interested in this approach because the rebar2 support is mostly on legacy maintenance mode, we recommend everyone to use rebar3 instead.

> Exactly, and you'd put the burden of being mix-compatible on projects that don't use mix. It would be HTML compatibility chaos all over, just very limited in scope.

This is a tradeoff we are willing to make. And again, you are free to not support mix if you don't want to.

**Comment by tuncer** [comment]
> Okay, if you don't want to support that is of course perfectly fine. It is your choice.

I can try to detect mix and as you suggested assume rebar is of version >=x.y. That won't fix the error in general. It would only resolve it in a script by accounting for an unexpected rebar config loader emulator. You can use `rebar:run/2` and `rebar list-deps`. And you could also load rebar, evaluate the script via rebar_config, which isn't going to change in rebar2 and hasn't for years, and request an API guarantee for the equivalent from rebar3.

The point is that config scripts are out there and we don't know them all. It's run in a similar environment as plugins that implement commands or hooks for existing commands that expect a certain environment.

**Comment by ericmj** [comment]
> That won't fix the error in general. It would only resolve it in a script by accounting for an unexpected rebar config loader emulator. You can use rebar:run/2 and rebar list-deps. And you could also load rebar, evaluate the script via rebar_config, which isn't going to change in rebar2 and hasn't for years, and request an API guarantee for the equivalent from rebar3.

Again, as I have stated multiple times before, we can't and wont load rebar into the VM because it will lead to conflicts with user code.

> The point is that config scripts are out there and we don't know them all. It's run in a similar environment as plugins that implement commands or hooks for existing commands that expect a certain environment.

Again, this is unfortunate but it is a tradeoff we are willing to make.

I am closing this issue now because the same points are just being reiterated.

**Comment by tuncer** [comment]
To be clear, does mix use rebar3 or rebar2 when building rebar projects? Or can a mix project declare it wants rebar3 to be used?

**Comment by ericmj** [comment]
Mix defaults to using rebar3 unless the hex package specifies it should be compiled with rebar2 or if the mix project declares it with `manager: :rebar`.
