### ISSUE TITLE
Calendar string date parsing

### ISSUE THREAD

**Issue by alisinabh** [elixir-lang/elixir#5669]
Elixir Calendars already provide callbacks for converting date in specific calendar to string (e.g. ``Calendar.date_to_string``), but they do not have callbacks to get date from a string in a specific calendar. 

Would it be a good idea to add parsing from a string?

### Environment

* Elixir & Erlang versions (elixir -v): 1.4

**Comment by josevalim** [comment]
Right now our thought is that those should be exposed by the other calendars themselves. We are currently having many calendar related discussions on elixir-lang-core and elixirforum, so I would recommend following those.

**Comment by alisinabh** [comment]
@josevalim i'm sorry but in calendar conversion discussion in ElixirForum you told me to [discuss it in a separate discussion](https://elixirforum.com/t/calendars-calendar-conversions/3119/60?u=alisinabh). I thought maybe issue tracker is a good place for this.

Thank you.

**Comment by josevalim** [comment]
@alisinabh the issues tracker is not a good place because not everyone follows up here and the issues tracker should focus on actionable issues, otherwise the issues tracker tends to devolve into a bunch of issues which we cannot act on and make the project harder to maintain. :)

**Comment by alisinabh** [comment]
@josevalim BTW i really like elixir and it's community and will be happy to help.

Have a good time :)
