### ISSUE TITLE
IO.inspect :limit option dynamically reduces fields printed of maps within lists

### ISSUE THREAD

**Issue by mgartner** [elixir-lang/elixir#5671]
I'm not sure if this is intended or not, but based on the documentation of the [`:limit` option](https://hexdocs.pm/elixir/Inspect.Opts.html) of `IO.inspect`, the current behavior does not seem intended:

> `:limit` - limits the number of items that are printed for tuples, bitstrings, and lists, does not apply to strings nor charlists, defaults to 50.

### Environment

* Elixir & Erlang versions (elixir -v): Erlang/OTP 19, Elixir 1.4.0
* Operating system: Mac OS X 10.11.4

### Current behavior

`IO.inspect` shows less fields of maps away from the beginning of a list.

```elixir
map = %{
  a: 1,
  b: 2,
  c: 3,
  d: 4,
  e: 5
}

list = List.duplicate(map, 50)

IO.inspect(list, limit: 4)
```

**Output**:

```
[%{a: 1, b: 2, c: 3, ...}, %{a: 1, b: 2, ...}, %{a: 1, ...}, %{...}, ...]
```

### Expected behavior

**Output**:

```
[%{a: 1, b: 2, c: 3, d: 4, ...}, %{a: 1, b: 2, c: 3, d: 4, ...}, %{a: 1, b: 2, c: 3, d: 4, ...}, %{a: 1, b: 2, c: 3, d: 4, ...}, ...]
```

**Comment by ericmj** [comment]
I believe this is intended. The docs should be updated to include "maps".

**Comment by mgartner** [comment]
Should the docs also mention how each successive nested element prints less and less details? Also, how is it determining which ones to show, and why is does the first element show 3 key/values when the limit is set to 4.
