### ISSUE TITLE
NIFs getting recompiled in separate build_paths

### ISSUE THREAD

**Issue by gjaldon** [elixir-lang/elixir#5672]
### Environment

* Elixir & Erlang versions (elixir -v): Elixir 1.4.0 and Erlang 19.0
* Operating system: OSX El Capitan

### Current behavior

I'm running my Elixir application inside Docker and I set the Mix build_path to `_docker_build` when inside Docker to keep compiled code for Docker separate from the ones compiled outside Docker. The Docker OS is Alpine 3.5. 

If I do the following steps:
1. `mix compile` outside Docker
2. `docker-compose up` (which compiles the project again but this time inside Docker)
3. `mix test` outside Docker

Some of my tests fail with the error below related to the NIF library that Comeonin depends on: 
```
[warn] The on_load function for module Elixir.Comeonin.Bcrypt returned {:error,
  {:load_failed,  'Failed to load NIF library: \'Error loading shared library ~/my_app/server/_build/dev/lib/comeonin/priv/bcrypt_nif.so: Exec format error\''}}
...
** (UndefinedFunctionError) function Comeonin.Bcrypt.checkpw/2 is undefined (module Comeonin.Bcrypt is not available)
...
```

If I do the reverse where I compile inside Docker first and then compile outside Docker next, my tests all pass fine but then the app inside Docker will return the same error above every time `Comeonin.Bcrypt.checkpw/2` is run. 

Even though I set different `build_path`s for inside Docker(_docker_build) and outside Docker(_build), the NIF library `bcrypt_nif.so` inside _docker_build and _build seems to always get recompiled. When I `mix compile` in OSX, `_docker_build/.../bcrypt_nif.so` and `_build/.../bcrypt_nif.so` gets recompiled for OSX and the app will no longer work in Alpine Docker. When I `mix compile` inside Docker which uses Alpine, the same thing happens and the app will no longer work in OSX.

### Expected behavior

Since I set a different build_path for the Docker environment, shouldn't the NIFs be compiled separately for each system and just work? 

I made a bunch of assumptions here and don't know the details about how mix deals with NIFs. Let me know if there's anything wrong with my understanding or if this is an actual bug that can be addressed in elixir/mix.

**Comment by ericmj** [comment]
Can you show how you set the build_path?

If you are recompiling the project anyway why do you need separate directories? Wouldn't it be better to avoid copying _build or deleting it instead?

**Comment by ericmj** [comment]
I believe the issue is related to that NIFs are compiled into the priv/ directory that is symlinked into _build/.../priv. Since the same priv/ directory is used for both macos and docker you can get conflicts. You can try setting `build_embedded: false` in your mix project config to disable symlinks, but not sure if that will help since the directory is still shared.

**Comment by josevalim** [comment]
@ericmj yes, I think you are right.

**Comment by gjaldon** [comment]
My `project/0` fun looks like this in mix.exs:
```elixir
  def project do
    [app: :sightline_maps,
     version: "0.0.1",
     elixir: "~> 1.4.0",
     elixirc_paths: elixirc_paths(Mix.env),
     compilers: [:phoenix, :gettext] ++ Mix.compilers,
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     build_path: System.get_env("BUILD_PATH") || "_build",
     test_paths: ["test/lib", "test/mix", "test/web", "test/feature"],
     aliases: aliases,
     deps: deps]
  end
```

> If you are recompiling the project anyway why do you need separate directories? Wouldn't it be better to avoid copying _build or deleting it instead?
I don't recompile the project every time Docker runs. I just tried recompiling when I got the error related to NIFs. I tried setting a different build_path for the Docker app to try and resolve the issue with NIFs. 

`build_embedded` is already false for both Docker and MacOS. Would it be possible to compile the NIFs into the build_path instead of into the priv/ directory or possible expose a config option for it?

**Comment by ericmj** [comment]
> build_embedded is already false for both Docker and MacOS.

Sorry, I meant `build_embedded: true`.

**Comment by ericmj** [comment]
There needs to be something that triggers recompilation of the NIF when the environment changes. If the makefile cannot detect this you need to do something else. Can you delete the generated files in priv/ when changing between docker and macos?

**Comment by gjaldon** [comment]
Ok will try deleting the generated files in priv/ when switching between docker and macos. Will update you in a bit.

**Comment by gjaldon** [comment]
Finally figured out the issue. I did `mix do deps.get, compile` when I built the Docker image. I had to add that deps directory inside as a volume so that it would be mounted in the container when I ran `docker-compose up`. I added the ff to my docker-compose file.

```yaml
volumes:
  - /server/deps     # this mounts the deps directory that were downloaded when the image was built
  - /server/_docker_build   #this mounts the _docker_build directory that was compiled in the mage
```

Thanks for the info on how the NIFs are symlinked to the deps/package/priv directory @ericmj! That helped me to solve this issue. The problem was my lack of understanding on how to use volumes in Docker.

**Comment by nicklayb** [comment]
Hey @gjaldon I'm having the exact same issue as you but I don't really understand how you made it work.

Here is my Dockerfile
```
FROM bitwalker/alpine-elixir-phoenix:latest

# Set exposed ports
EXPOSE 5000
ENV PORT=5000 MIX_ENV=prod

# Cache elixir deps
ADD mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

ADD . .

USER default

CMD ["mix", "phx.server"]
```

I'm also having a the following in a `.dockerignore` file 
```
_build
deps
```
