### ISSUE TITLE
Redirect old docs website to hexdocs

### ISSUE THREAD

**Issue by alex88** [elixir-lang/elixir#5682]
After posting in the slack channel @jeregrine told me to open an issue here.
Basically all my browser history elixir docs points to the old stable url http://elixir-lang.org/docs/stable/elixir, wouldn't be possible (and useful) to redirect that to the new hexdocs website?
Because the url still shows `stable` but shows the old 1.3.4 version, someone that ends up there wouldn't know that there is a new stable version out there
It should be pretty straightforward as the path after `stable` is the same you can find in hexdocs.

**Comment by josevalim** [comment]
There is already an open issue here: https://github.com/elixir-lang/elixir-lang.github.com/issues/921 We plan to set up redirects soon.

**Comment by josevalim** [comment]
Thank you for reporting anyway!

**Comment by alex88** [comment]
Oh that's why I haven't found it, i was searching on this repo! Ops!

**Comment by eksperimental** [comment]
@alex88 could you please test it now?
and let me know if you find anything not working as expected in https://github.com/elixir-lang/docs/pull/17
thank you

**Comment by alex88** [comment]
Hi @eksperimental, it seems to work correctly!
Too bad it won't trigger a 301 but from a fast research seems it's not possible with github pages, so browser urls won't change probably.

**Comment by eksperimental** [comment]
yes, it is not possible with github pages, otherwise it would have save me the trouble of creating 1,600+ unique pages.

**Comment by OvermindDL1** [comment]
At the very least a `<meta ...` redirect header and fallback javascript to redirect would work for most purposes?  And easy to generate 1500+ pages with some `sed`'ing for the urls...

**Comment by josevalim** [comment]
@OvermindDL1 such solution has already been pushed.

**Comment by eksperimental** [comment]
@OvermindDL1 please see this PR: https://github.com/elixir-lang/docs/pull/17
