### ISSUE TITLE
MIX ----   100 percent  recompiled what ever you do 

### ISSUE THREAD

**Issue by zhaohansprt** [elixir-lang/elixir#5684]
### Environment

* Elixir & Erlang versions (elixir -v):  1.4.0  R19.2   
* Operating system:  centos 7  

### Current behavior

there is a  medium size  project  that got  100 percent opertunity  recompiled it self  ;even you just restart it ; and i tried to clean it  but even after that when i alter some code or config files it start behaves just like before;
i don't have a clue how to find it out  the reason; and i didn't find there is a  --force  keyword throughout the whole project files
or teach me how to debug the mix 
my other new  mix  project  behaves fine .....
### Expected behavior

behavior normal

**Comment by josevalim** [comment]
Has this been solved? :)

**Comment by zhaohansprt** [comment]
yes  debuged the  file  "Elixir.Mix.Compilers.Elixir " 
  and i think there is  no need for counting  the  runtime_reference as we do in erlang  so i  deleted that block below: (and see if  the project runs well)

   # If I have a runtime references to something stale,
      # I am stale too.
      # Enum.any?(runtime_references, &Map.has_key?(stale, &1)) ->
      #   :io.format('runtime_references~p~n  stale~p~n',[ runtime_references   ,stale])
      #   {[entry | rest], Map.put(stale, module, true), removed}

**Comment by zhaohansprt** [comment]
now  it  only recomple 32 files  (before:  350+    )

**Comment by rranelli** [comment]
@zhaohansprt I suggest you take a look at this post: 
http://milhouseonsoftware.com/2016/08/11/understanding-elixir-recompilation/

`mix xref graph` can help you a lot finding why these issues are happening. If your whole project is being recompiled, chances are you have circular dependencies between your modules.

**Comment by zhaohansprt** [comment]
thanks that is useful ,
 I had known it that  the whole project was written by  a group of  code farmer and  bricker; such subtle things they wouldn't consider ,and they  really can tolerate the waiting  ，if  there is such circular dependencies  i wouldnt superise, but as i debugged the mix itself  i found compile time references is  fine 
;the resault the the whole project files get involved  is because the runtime_references matters
the probes i placed in the code tells the whole story:
   :io.format('compile_references:~p~n source:~p~n module:~p~n stale:~p~n',[ compile_references, source, module, stale])
     :io.format('runtime_references~p~n  stale~p~n',[ runtime_references   ,stale])
