### ISSUE TITLE
EEx/Phoenix Error Display Breakout

### ISSUE THREAD

**Issue by dabaer** [elixir-lang/elixir#5691]
### Environment
Erlang/OTP 19.2 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.4.0
Ubuntu 16.10 (yakkety)

Both erlang and elixir were built from source, elixir with no options and erlang with only the --enable-m64-build option.

### Current behavior
I am unable to narrow down the specific code that is causing this (since it is very specific and seems to include at the very least my entire template, but upon accidentally omitting a `do` keyword after an if statement, the error output managed to break out of the code display from Phoenix:

https://8.lithi.io/Qchbzk.png and https://8.lithi.io/Gd2eZdT.png is the entire page view, and https://gist.github.com/dabaer/10aa9e42559015e3461a5251adf73eac if you wish to peruse the exact output as text.

The applicable template code is (profile.html.eex):
https://gist.github.com/dabaer/f71e5e463586be74b1d35269ba5ffb79#file-template-html-eex-L19

I am able to produce this with the statements only on L19, L20, and L24, removing any other produces the proper error that the `end` keyword is unexpected for that block.

Additionally, the code calling that template is:
```
def profile(conn, %{"username" => username}) do
    member = Repo.get_by(Member, username: username)
    query = from p in ProfileField, where: p.member_id == ^member.id
    conn |> render("profile.html", member: member, fields: Repo.all(query))
end
```

This module also contains an external plug call, however it is not in effect on that specific action.

### Expected behavior
A contained error, such as https://8.lithi.io/iNtRS.png

I apologize if this should have been posted to the Phoenix bug tracker, but i wasn't sure whether this is purely a Phoenix.HTML issue, or if the root cause was EEx.

CC @chrismccord

Regards,
Jadenn

**Comment by josevalim** [comment]
Thank you for the report. Look for <%= else %> in your template. That's the
bug, just remove the =. However please leave this open as we should
certainly improve the error message.

**Comment by dabaer** [comment]
Wow I was certain i looked for that already, but found one :P Thanks for the tip. I recall running into this at the beginning of last year but forgot about it since so I thought maybe it flew under the radar
