### ISSUE TITLE
File.stream is delivering the byte order marker when reading lines

### ISSUE THREAD

**Issue by mlankenau** [elixir-lang/elixir#5695]
### Environment

* Elixir & Erlang versions (elixir --version): elixir 1.4.0, Erlang 19
* Operating system: OSX 10.12.1

### Current behavior

I am opening an utf-8 file with File.stream! with the default setting (read lines) like

```
File.stream!("my_file.txt")
> Enum.map(...)
```

When trying to match the first line to something expected it fails. It took me quite long to find out that the first line contains 3 extra bytes in the beginning (the BOM, https://de.wikipedia.org/wiki/Byte_Order_Mark).

I solved it in my project with adding the BOM to the expectation

```
<<239, 187, 191>> <> "HEADER" = line
```

This might be brittle (when the BOM changes) and confusing. 

### Expected behavior

When using :line mode or (as Jose suggested at elixirforum) another option :strip_bom is given, the bom should be skipped.

**Comment by AndrewDryga** [comment]
@mlankenau Hi.

I can't reproduce this issue in tests. I've added some utf8 file with BOM and user `File.stream!/1` over it, but everything looks fine and first line doesn't contain BOM.

See [here](https://github.com/elixir-lang/elixir/pull/5702/files).

**Comment by AndrewDryga** [comment]
@josevalim this one can be closed.
