### ISSUE TITLE
Regression in ExDoc's ability to handle fenced code blocks in 1.3.4?

### ISSUE THREAD

**Issue by christhekeele** [elixir-lang/elixir#5697]
I [implemented support](https://github.com/elixir-lang/elixir/pull/5389) for `ExUnit.Doctests` to handle github-flavored fenced code blocks a few months ago.

In particular, while it could handle a lot of cases allowed by `ExDoc`, it [failed if there wasn't an empty newline in between the last example and the end of the code block](https://groups.google.com/d/msg/elixir-lang-core/EsRK3n7sifo/0icBfhz5AQAJ).

I first noticed that these failures returned [4 days ago](https://travis-ci.org/christhekeele/mnemonix/builds/193852424); and that [the newline](https://travis-ci.org/christhekeele/mnemonix/builds/194787494) is apparently [the problem](https://travis-ci.org/christhekeele/mnemonix/builds/194793717). However, adding 1.4.0 to my build matrix suite showed the latest and greatest [handles them just fine](https://travis-ci.org/christhekeele/mnemonix/builds/194798540).

The travis builds should have sufficient information about the build environment to help understand the cause; I haven't dug into them but wanted to report this before I forgot for 4 days again, it's been a busy few weeks. :)

**Comment by josevalim** [comment]
Your PR was never included in the v1.3 branch, so I wouldn't expect it to work there. It is part of v1.4, which explains why it works once you upgraded. :)

**Comment by christhekeele** [comment]
😆  Well, that is about as closed as an issue gets. I must have lost track of what versions of things I was running when I switched shells. 💜
