### ISSUE TITLE
put_in line has no local return warning in dialyzer

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#5707]
### Environment

* Elixir & Erlang versions (elixir --version):
Elixir: `1.4.0`
Erlang: `19.2`
* Operating system:
OSX

### Current behavior

```
  defp full_params(params) do
    includes = Includes.from_params(params)
    includes = ["job-assignments" | includes]
    include_param = Includes.to_string(includes)
    put_in params["include"], include_param
  end
```

gives a dialyzer warning on `put_in params["include"], include_params`

```
my_module.ex:186: The created fun has no local return
```

### Expected behavior

`put_in` does not cause a dialyzer warning

**Comment by sngeth** [comment]
Trying to look into this but un sure  of how to reproduce your issue. I'm not sure what your Includes implementation is doing so I did an arbitrary example below and it seemed fine.

```
➜  Code  cat test_put_in.exs
defmodule Simple do
  def call_it do
    test()
  end

  defp test do
    params = %{"include" => 1}
    include_param = 2
    put_in params["include"], include_param
  end
end

Simple.call_it
➜  Code  elixirc test_put_in.exs
warning: redefining module Simple (current version loaded from Elixir.Simple.beam)
  test_put_in.exs:1

➜  Code  dialyzer Elixir.Simple.beam
  Checking whether the PLT /Users/sngeth/.dialyzer_plt is up-to-date... yes
  Proceeding with analysis...
Unknown types:
  file:date_time/0
  file:file_info/0
 done in 0m0.33s
done (passed successfully)

```

**Comment by josevalim** [comment]
I have also failed to reproduce this issue. So I am closing this until we can successfully do it. @KronicDeth, please let us know if you have more info.
