### ISSUE TITLE
OptionParser.parse regression

### ISSUE THREAD

**Issue by savonarola** [elixir-lang/elixir#5708]
### Environment

* Elixir & Erlang versions (elixir --version):
Elixir: 1.4.0
Erlang: 19.2
* Operating system:
OSX

### Current behavior

```elixir
iex(1)> OptionParser.parse(["--a", "b", "--c", "d", "--ee", "f"], switches: [a: :string])      
{[a: "b", c: "d"], [], [{"--ee", "f"}]}
```

### Expected behavior

```elixir
iex(1)> OptionParser.parse(["--a", "b", "--c", "d", "--ee", "f"], switches: [a: :string]) 
{[a: "b", c: "d", ee: "f"], [], []}
```

As in Elixir 1.3.4 and earlier.

**Comment by josevalim** [comment]
Yup, looks like a regression indeed. You may be able to solve it for now by explicitly listing the other switches you are interested in, but we shall fix this regardless.

**Comment by tsubery** [comment]
Looks like this change was [intentional](https://github.com/elixir-lang/elixir/pull/5134) . Coincidentally, the atoms ```:a``` and ```:c``` exist so [this line](https://github.com/elixir-lang/elixir/blob/9b5810c8ec104da113fc62da0e1cc81b80f32437/lib/elixir/lib/option_parser.ex#L673) fails only for ```:e```.
Maybe this behaviour should only happen when the parsing is 'strict'.

**Comment by savonarola** [comment]
@tsubery thanks for pointing out the roots of the cause.

I'd also like to note, that my case is accepting an open set of command-line arguments. So I can't just list them in `switches` proplist.

**Comment by AndrewDryga** [comment]
I agree with @savonarola. If there are part of your options parsed and other don't, you will spend a while to understand that all atoms must be registered in Erlang VM.

**Comment by lexmag** [comment]
I think it is rather documentation issue, as it feels not right to provide unsafe functionality in standard library. I'm wondering, what is that use case when you parse options and never access them by key? :bowtie:

**Comment by AndrewDryga** [comment]
@lexmag Sometimes you don't have atom, but create them in runtime with `String.to_atom/1`. But this case sounds too close to the edge :).

**Comment by josevalim** [comment]
@lexmag we should have a mechanism to opt-in though into unsafe issues. OptionParser is most commonly used on CLIs where atom exhaustion is not a problem. Plus, we need to give users an option to remain backwards compatible. So I would suggest `unsafe_atoms: true`.

**Comment by lexmag** [comment]
Yeah, mechanism to control atom behaviour sounds like the way to fix this. 👍
I propose to use `existing_atoms` (alternatively `use_ existing_atoms`) as the name to be closer to what it actually affects, `unsafe` could be questionable.

**Comment by josevalim** [comment]
@lexmag given this is about unsafe behaviour, I would prefer an option that is set to true, to make sure there is no confusion. `existing_atoms: false` is quite unclear on what it means. So `allow_unexisting_atoms: true` or `unsafe_atoms: true` or other options are welcome.

**Comment by tsubery** [comment]
FWIW, my two cents is to to print a warning about it. Can't imagine a situation where this should fail silently.

**Comment by lexmag** [comment]
`allow_inexistent_atoms` sounds good to me.

**Comment by savonarola** [comment]
@lexmag the case is he following: my app allows arguments of the form  `--tlv-0x1234 VALUE`, so it never accesses such keys directly but rather parses them.

**Comment by savonarola** [comment]
As far as I can understand, my problem is expected to be a common one: if one didn't want "unknown" keys, they would use `strict` instead, not `switches`. The only point of using `switches` over `strict` is to expect keys that are not known beforehand (and hence not represented by existing atoms).

So using `switches` is generally useless without implying "`allow_inexistent_atoms`" option.

**Comment by tsubery** [comment]
Switches are used to define the expected type. In the case of the default - string, it would be redundant to specify them.

**Comment by lexmag** [comment]
@savonarola `allow_inexistent_atoms` option and `strict` do have some overlapping, but the difference is that `strict` is about a way of expressing user's expectations on result (and it is not always used from the beginning even in places where it should be), while `allow_inexistent_atoms` is a safety guarantee which should be ideally enabled by default.
Also `strict` still could be specified dynamically at runtime.

**Comment by savonarola** [comment]
@lexmag Yes, I understand this point. Just tried to figure out "general expectations" about the API for a fuller view of the problem.
