### ISSUE TITLE
Style question: what do we call idiomatic Elixir?

### ISSUE THREAD

**Issue by natecox** [elixir-lang/elixir#5710]
I'm coming from the Python world, where we typically call idiomatic Python _pythonic_. If you're describing doing something in a way that is conceptually _correct_ and falls within the guidelines for the  [Zen of Python](https://www.python.org/dev/peps/pep-0020/) you would say that it is _pythonic_. Is there an established term for idiomatic elixir? If not, should there be?

(bad) examples:
* Hermetic
* Alchemic
* Fluidic
* Etc

Is this something that the community would even want, or is it not really important?

**Comment by josevalim** [comment]
Idiomatic Elixir. :)

Also please don't use the issues tracker for such discussions, there are preferred means for that, such as mailing lists and the Elixir forum.
