### ISSUE TITLE
Should bytes render like this in iex?

### ISSUE THREAD

**Issue by bhargavrpatel** [elixir-lang/elixir#5711]
### Environment

* Elixir: `1.4.0`
* Erlang: `Erlang/OPT 19`
* Operating system: `Mac OSX Capitan`

### Current behavior

```elixir
iex(40)> :crypto.rand_bytes 1
<<208>>
iex(41)> :crypto.rand_bytes 1
<<154>>
iex(42)> :crypto.rand_bytes 1
"\""
iex(43)> :crypto.rand_bytes 1
<<136>>
iex(44)> :crypto.rand_bytes 1
"e"
iex(45)> :crypto.rand_bytes 1
"V"
iex(46)> :crypto.rand_bytes 1
<<191>>
iex(47)> :crypto.rand_bytes 1
"\d"
```

### Expected behavior
* It should always render the bytes within the `<< ___ >>`

**Comment by ericmj** [comment]
Strings are UTF-8 encoded binaries. Because of that, sometimes, binaries will render as strings. You can learn more by using the `i/1` helper in IEx, for example: `i "this is a string"`.
