### ISSUE TITLE
Inconsistent regex comparison with named capture groups

### ISSUE THREAD

**Issue by davidsulc** [elixir-lang/elixir#5716]
### Environment

* Elixir & Erlang versions (elixir --version):
   * Erlang/OTP 19 [erts-8.1] [source-4cc2ce3] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
   * Elixir 1.3.3
* Operating system:
```
uname -a

Linux <machine_name> 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
lsb_release -a

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

### Current behavior

Comparing regex values yields inconsistent results depending (it seems) on capture names.

```
iex(1)> ~r/(?<place>.)(?<number>.)/ == ~r/(?<place>.)(?<number>.)/
false
iex(2)> ~r/(?<place>.)(?<number>.)/ == ~r/(?<place>.)(?<number>.)/
true
```

Additional executions seem to then yield only `true`.

However, with different capture names, results are as expected:

```
iex(1)> ~r/(?<foo>.)(?<bar>.)/ == ~r/(?<foo>.)(?<bar>.)/          
true
iex(2)> ~r/(?<foo>.)(?<bar>.)/ == ~r/(?<foo>.)(?<bar>.)/
true
```

### Expected behavior

Regex value comparison should return the correct boolean value consistently, regardless of capture names.

### Context

I stumbled on this surprising behavior because I am using `Regex.compile/1` to generate regexes from input data. I want to test the compiled regex and ensure it matches the expected result.

Tests comparing regexes as in the above case will fail inconsistently as both ExUnit and doctests.

**Comment by ericmj** [comment]
It is not safe to compare regex with `==`. If you want to compare regex you should do it on the source `~r/(?<place>.)(?<number>.)/.source == ~r/(?<place>.)(?<number>.)/.source`

**Comment by davidsulc** [comment]
Thanks for taking the time to look into this. Comparing regular expressions with `==` felt strange, but I was unsure how else to achieve my testing objective. Comparing the value of `.source` works as expected though, thanks for bringing it to my attention.
