### ISSUE TITLE
Syntax Check Feature Needed

### ISSUE THREAD

**Issue by SchrodingerZhu** [elixir-lang/elixir#5717]
Is There A way to do syntax check without running the code？
Just like the nodeJS `-c/--check command.

**Comment by josevalim** [comment]
There is no such thing because simply parsing the syntax does not guarantee the code will be ultimately valid due to macros. For example, a code such as `defmodule Foo` would pass `-c` but not be valid when compiled. If you need something close to this though, you can do:

    elixir -e 'Code.string_to_quoted("path/to/file")'

**Comment by josevalim** [comment]
Also please remember to use the mailing list or the forum for questions next time around. :)

**Comment by SchrodingerZhu** [comment]
Thanks, I will use mailing list next time for sure.
