### ISSUE TITLE
Allowing fn closures with several definitions (and arity)

### ISSUE THREAD

**Issue by FabienHenon** [elixir-lang/elixir#5728]
It is currently possible to declare a closure this way: 

```elixir
fn
  (10, b) -> {10, b}
  (a, b} -> {a, b}
end
```

but not this way:

```elixir
fn
  (b) -> {10, b}
  (a, b} -> {a, b}
end
```

because arity is different.

But is there any reason to forbid this kind of declaration with different arity?

I have a use case where I would like to return a function and pass it to a function like `Enum.map` and I would like it to work with functions of different arity;

My code should look like this:

```elixir
def f(a) do
  fn
    (b, c) -> :ok end
    (b) -> fn (c) -> :ok end
  end
end
```

But it is not possible for now. Would it be a problem to make an evolve to allow this kind of notation?

**Comment by OvermindDL1** [comment]
Limitation of the BEAM.  A function is defined as a combination of a name (or memory location) and arity.  Anonymous function are the such memory location and arity.  If you want to be able to call a function of any arity then you need to test its arity then `apply` the arguments to it, which is quite a bit slower, thus you need to do it yourself if you want it done, but it can be done.

**Comment by FabienHenon** [comment]
Ok, I understand.

But, trying to take the problem by an other edge, let's see this code:

```elixir
defmodule MyModule do
  def func(a), do: {a, 10}
  def func(a, b), do: {a, b}
end
```
This is a correct code, and it is permitted because arity is different.

But given this, why isn't possible to write this code:

```elixir
defmodule MyModule do
  def func(a), do: {a, 10}
  def func(a, b), do: {a, b}

  def call, do: func
end
```
What I would like to do with the code above is to return the `func` function but with no arity specified so that it can be called with either 1 or 2 parameters.

**Comment by josevalim** [comment]
Functions in Elixir are identified by name and arity, we could make it work but it would drastically affect performance and/or integration with Erlang. So you need to pick either &func/1 or &func/2 in the example above.

Also, please use the mailing list or Elixir forum for discussions and proposing features. This way other developers can join the discussion before they make it to the tracker.
