### ISSUE TITLE
iex freezes when a module is pasted on "dumb" terminal

### ISSUE THREAD

**Issue by AleffSouza** [elixir-lang/elixir#5730]
I noticed that every time I've pasted some module code into iex it freezes. Even a simple code like:
```
defmodule Hello do
  def say_hello do
    IO.puts "Hello..."
  end
end
```
It's enough to freeze it.

Elixir 1.4.1
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 8.2
Windows 10 x64

**Comment by josevalim** [comment]
Does it happen if you use `iex --werl`?

**Comment by josevalim** [comment]
Also, which terminal are you using on Windows?

**Comment by AleffSouza** [comment]
No, is doesn't. `iex --werl` works fine =)
I'm using the default windows terminal.

**Comment by OvermindDL1** [comment]
This is not an Elixir issue, it is just very very bad Windows terminal handling, I've seen it plenty when pasting in multi-line things.  `werl` does not use a terminal so it gets around the issue.  This happens in other things other than elixir as well on the windows terminal (at least in Windows 10).

Elixir may be able to fix it for itself only, I'm unsure, I do not even know the cause, but it does happen in non-elixir things as well.  Maybe the buffer size the program accepts needs to be larger than the input or something, who knows...  Needs research.  :-)

**Comment by AleffSouza** [comment]
@OvermindDL1 Actually Node.js can evaluate any pasted code on the same terminal.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 Actually Node.js can evaluate any pasted code on the same terminal.

'Any' amount?  I've had python's input get frozen as well.  I am wondering if it is some kind of buffer setting, hmm...

**Comment by OvermindDL1** [comment]
Just did some testing, sent a lot of input into `iex` and I managed to get it into a state where the prompt still shows `iex> `, however it is taking in Erlang code, giving it Elixir code reports with errors, as in I even have to end expressions with `.` even.
```erlang
iex> 2 + 2                              
.                                       
iex> 4                                  
iex> defmodule Testering do end         
.                                       
iex> * 1: syntax error before: Testering
iex> 2+2.                               
iex> 4                                  
iex> 2+2                                
:blah                                   
vwoop                                   
.                                       
iex> * 3: syntax error before: vwoop    
iex>                                    
```
So... that is weird.  Is there some command that I might have sent it that made it switch to an Erlang handler?

**Comment by AleffSouza** [comment]
@OvermindDL1 Sorry, I don't know if any amount will work but a 20 lines have been evaluated fine there. 

The funny fact is if you paste 

```
defmodule MyModule do
end
```

on iex, it will be evaluated just fine, but if you put any function inside that module it will freeze.

**Comment by OvermindDL1** [comment]
@AleffSouza Can you try that?  Paste something like:
```elixir
defmodule MyModule do
  def blah, do: :blah
end
```
And as you see if you hit 'enter' a few times it does nothing, but then hit period `.` and enter.  `.` is the Erlang end-of-statement character (`,` comma is the end-of-expression character if you are curious), see if you get a message then and if so please paste it?

I get this:
```elixir
$ iex
Eshell V8.2  (abort with ^G)
Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex> defmodule MyModule do
  def blah, do: :blah
end
.
...> * 1: syntax error before: blah
...> .
...> * 1: syntax error before: '.'
...> end
.
...> * 1: syntax error before: 'end'
...>
```

I think the Elixir and Python problems that I have are two different things now, I think Elixir's handler process is crashing perhaps and reverting to Erlang.  Fascinating...

**Comment by OvermindDL1** [comment]
For note, putting in the above defmodule is random, sometimes it works, sometimes it does not...

**Comment by OvermindDL1** [comment]
And now I managed to freeze it entirely, no input is being accepted, not even newlines...  Ctrl+C still managed to kill it though, hmm...

**Comment by AleffSouza** [comment]
yes, it happened here

```
Eshell V8.2  (abort with ^G)
Interactive Elixir (1.4.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule MyModule do
  def blah, do: :blah
end
.
...(1)> * 1: syntax error before: blah
...(1)> ...(1)> .
...(1)> * 1: syntax error before: '.'
...(1)> ...(1)> .
...(1)> * 1: syntax error before: '.'
```

**Comment by OvermindDL1** [comment]
I cannot manage to replicate the issue in linux over ssh, but ssh could be buffering things and affecting the tests so unsure...

**Comment by josevalim** [comment]
`TERM=dumb iex` is enough to reproduce it on Linux.

**Comment by OvermindDL1** [comment]
This has been such a *long* standing bug forcing me to kill and recreate my sessions so much, I just thought it was 'yet-another' of the Windows annoyances.  You have no idea how happy its made me that @josevalim managed to replicate it.  ^.^

**Comment by OvermindDL1** [comment]
Maybe remove the "Note:Windows" since it is replicateable elsewhere now?
