### ISSUE TITLE
Use @optional_callbacks in GenServer

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5735]
One of the features added to Elixir early on to help integration with Erlang code was the idea of overridable function definitions. This is what allowed our GenServer definition to be as simple as:

```elixir
defmodule MyServer do
  use GenServer
end
```

Implementation-wise, `use GenServer` defines functions such as:

```elixir
def terminate(reason, state) do
  :ok
end
```

and then mark them as overridable:

```elixir
defoverridable terminate: 2
```

In some cases, the use of defoverridable seems to be unnecessary. For instance, we provide a default implementation for `handle_call/3` and mark it as overridable, but the default implementation simply raises when invoked. That's counter-intuitive as it would be best to simply not define a default implementation in the first place, truly making the `handle_call/3` callback optional.

Luckily, Erlang 18 added support for marking callbacks as optional, which we support on Elixir v1.4. We propose Elixir and libraries to leverage this feature and no longer define default implementations for the `handle_*` functions and instead mark them as optional.

Instead of the version we have today:

```elixir
defmodule GenServer do
  @callback handle_call(message, from, state)

  defmacro __using__(_) do
    quote do
      @behaviour GenServer

      def handle_call(_message, _from, _state) do
        raise "handle_call/3 not implemented"
      end

      # ...

      defoverridable handle_call: 3
    end
  end
end
```

We propose:

```elixir
defmodule GenServer do
  @callback handle_call(message, from, state)
  @optional_callbacks handle_call: 3

  defmacro __using__(_) do
    quote do
      @behaviour GenServer

      # ...
    end
  end
end
```

The proposed code is much simpler conceptually since we are using the `@optional_callbacks` feature instead of `defoverridable` to correctly mark optional callbacks as optional. `defoverridable` will still be used for functions such as `terminate/2`, which are truly required.

We should take account of backwards compatibility, as users may be calling `super` in their current GenServer implementations.

This depends on #5676.

**Comment by josevalim** [comment]
We are holding off #5676 for now in an attempt to get those changes in OTP instead. As a result, those changes won't make it to Elixir v1.5.

**Comment by josevalim** [comment]
Given optional callbacks were added as part of OTP 20, we can likely move forward with this without rolling our own implementation. The only concern is regarding `init` which should probably no longer be optional, which requires us to put the proper deprecation warnings in place.

**Comment by josevalim** [comment]
The decision on `init` should also align with how we want `init` to work on supervisors. Today we may `use Supervisor` for the `child_spec` function but that warns if `init` is missing. We need to decide how we want to act on this case.

**Comment by josevalim** [comment]
This is being broken in two parts. One is the discussion of `init` in the standard library and the other is the use of optional callbacks, which require OTP 20 to be done completely.

**Comment by vans163** [comment]
Is there the inverse of this?  @force_callbacks?  

The problem is recompile/0 unloads modules, if a gen_server receives a msg at the exact time a recompile is happening (100ms margin) the msg gets dropped with WARNING: handle_info/2 not defined.

This leads to inconsistent state as messages get lost.

The old behaviour would result in the gen_server crashing. Which is correct to maintain state.
