### ISSUE TITLE
Show warning when a package is defined twice in mix.exs

### ISSUE THREAD

**Issue by jeroenvisser101** [elixir-lang/elixir#5741]
Currently, if you have the following in your `mix.exs`:

``` elixir
  defp deps do
    [{:ecto, "~> 2.1"},
     {:postgrex, "~> 0.13.0"},
     {:ecto, "~> 2.0"}]
  end
```

The last definition for ecto is ignored and `~> 2.1` is resolved. It could be useful if multiple definitions of the same dependency (in the same file) exist, to show a warning.

**Comment by kelvinst** [comment]
I can give it a try if no one else is interested. Will start today, maybe I'll open the PR until wednesday.

**Comment by whatyouhide** [comment]
@kelvinst please do go ahead :) 💟
