### ISSUE TITLE
Modules are loaded with various path and environment depending if they were rebuilt

### ISSUE THREAD

**Issue by mspanc** [elixir-lang/elixir#5746]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 19 [erts-8.0] [64-bit] [smp:12:12] [async-threads:10] Elixir 1.4.1
* Operating system: Windows 10

### Current behavior

I have an app that has several Mix dependencies with NIFs.

I have written a Mix task that is added as compiler to each Mix dependency. So far it just does simple `gcc something`.

In each of these dependencies, I use`@on_load` and in the actual method I call `:ok = :erlang.load_nif('mynif', 0)`.

Then I call `iex -S mix` in the app's directory. It properly invokes compilation of all dependenices, compiler is being called and `.so` libs are created in the `deps/something` directory, or in the dependencies' folders if they are referenced as `:path` in `mix.exs`. So far it works well.

The issue is that seems that `File.cwd` in the `@on_load` callback returns different value depending if elixir source code needs to be rebuilt or not.

If it does not need to be rebuilt, it returns path of the master application.

If it does, it returns path of the dependency.

I have also found out that `Mix.Project.deps_paths[:mydep]` in the first case returns valid path of the dependency (which may be used to find the actual NIF location), and in the second case it returns nil.

### Expected behavior

Modules are being loaded with consistent environment, regardless if they were recompiled or not.

**Comment by josevalim** [comment]
Don't use File.cwd. :)

File.cwd inside `@on_load` will change based on when the module is loaded. If the module is loaded during compilation, then it will likely be the current project. However, if you are on a project that depends on said module as a dependency, whenever you invoke said module, causing it to be loaded, File.cwd will be whatever the current project is. In other words, File.cwd is highly dependent on the user session and when the code is loaded.

The best option is to keep the .so files in priv and use `Application.app_dir(:your_app, "priv/my_app.so")`. That failing, then you can use __DIR__ to retrieve the directory of the current file and access the .so file from there during compilation.
