### ISSUE TITLE
Strange exception raises at `eex` with `cond` at the first line

### ISSUE THREAD

**Issue by asiniy** [elixir-lang/elixir#5752]
### Environment

* Elixir & Erlang versions (elixir --version): 1.3.4 & 19.2
* Operating system: ubuntu

### Current behavior

I have an `.eex` partial for my phoenix application. It has an `<%= cond do %>` at the first line and raises unpredictable `web/templates/layout/_header_user_menu.html.eex:1: expected -> clauses for do in cond`:

```
** (CompileError) web/templates/layout/_header_user_menu.html.eex:1: expected -> clauses for do in cond
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

My code is:

``` elixir
<%= cond do %>
<% is_nil(assigns[:current_user]) -> %>
  <!-- doens't matter -->
<% @current_user.state != "lack_of_credentials" -> %>
  <!-- doesn't matter -->
<% true -> %>
  <!-- nothing -->
<% end %>
```

Is it a bug or feature?

**Comment by josevalim** [comment]
I cannot reproduce this. The code snippet you posted above compiles just fine on Elixir master.

**Comment by Eiji7** [comment]
@josevalim: I can reproduce this error on **Erlang** 19.2.3, **Elixir** 1.4.1 and **Phoenix** 1.2.1.
Steps to reproduce:
1. run `mix phoenix.new test_project_name`
2. replace contents of file: `web/templates/layout/app.html.eex` with posted code
**Note**: This code works inside `body`, but not instead of all contents (at top of file).

**Comment by josevalim** [comment]
Ok, I can reproduce it now. :)

**Comment by asiniy** [comment]
@josevalim thanks!
