### ISSUE TITLE
Proposal: Logger Backends and Formatters

### ISSUE THREAD

**Issue by Ebtoulson** [elixir-lang/elixir#5754]
### [ElixirForum Discussion](https://elixirforum.com/t/proposal-logger-backends-and-formatters/3605)
The current `:console` logger backend doesn't support injecting custom formatters.

### Issue
Creating a backend seems to be the intended pattern but I think this could be improved. I see a definite separation between outputting (stdio, file, tcp/udp, etc) and formatting, but this seems to be coupled in a lot of existing logger packages (e.g. logger_json_file_backend).

### Proposal
Let's create a behavior for formatters, break out the default formatter from `:console`, and determine formatters from configuration.

We might also want to break out common functionality into the utils module to help with the creation of custom formatters. This would include things like handling metadata.

```
config :logger,
  backends: [:console]

config :logger, :console,
  level: :debug,
  metadata: [:request_id],
  formatter: Logger.Formatters.Json
```

Doing something like this while remaining backwards compatible with the existing `:console` backend and `:format` configuration might be a little tricky.

> It is not possible in the current implementation, we would have to reimplement the whole backend. - Jose

I'm also hoping this creates a pattern for other elixir logger projects to follow.

**Comment by fishcakez** [comment]
We already support this. Use `Logger.Formatter.compile` with `{module, function}` for completely custom format. Then call `Logger.Formatter.format`. Perhaps the docs are not quite so good in the `Logger` module itself. I believe this feature has existed since Logger was first introduced.

**Comment by josevalim** [comment]
Good call @fishcakez. I had totally forgotten about this!

**Comment by Ebtoulson** [comment]
👍 This is what I was looking for. Thanks
