### ISSUE TITLE
Mix alias behaviour: can't proceed after "run"

### ISSUE THREAD

**Issue by rawkode** [elixir-lang/elixir#5760]
With the following alias:
```
      "develop": [
        "init",
        "ecto.reset",
        "run priv/seeds.exs",
        "phoenix.server"
      ]
```

`phoenix.server` is never called, as the alias stops after **any** `run` command

**Comment by josevalim** [comment]
Please fill in the template information when filling up a new issue. Thank you.

**Comment by josevalim** [comment]
Btw, the reason this does not work is because Phoenix itself uses `Mix.Task.run "run"`. We need to either reenable run in Mix or Phoenix needs to do it.

**Comment by josevalim** [comment]
@lexmag @whatyouhide are you ok with us reenabling run automatically, allowing it to be called multiple times?

**Comment by josevalim** [comment]
@rawkode this has been fixed on Phoenix here: https://github.com/phoenixframework/phoenix/blob/master/lib/mix/tasks/phoenix.server.ex

I think meanwhile you can write your alias as:

      "develop": [
        "init",
        "ecto.reset",
        "phoenix.server -r priv/seeds.exs"
      ]

**Comment by rawkode** [comment]
Thanks, @josevalim

**Comment by whatyouhide** [comment]
@josevalim do we special case other Mix tasks?

**Comment by josevalim** [comment]
@whatyouhide I thought we did it for `mix cmd` but we don't (but I think we should).

**Comment by lexmag** [comment]
I think we shouldn't reenable it automatically, it breaks expectations from tasks.
You may assume, wrongly, that it behaves as all other tasks (as it makes sense), but find out the opposite the hard way, if script for run isn't idempotent and breaks things in bad way.
Reenabling in Phoenix seems natural to me.

**Comment by balduncle** [comment]
I know this ticket is closed, but in case more user feedback is valuable, this baffled me for a while.  My specific use case is defining an `ecto.reset` alias that runs two separate seeds files in a Phoenix project, and I couldn't figure out why my second seed file wasn't running.
