### ISSUE TITLE
Compiler error by space between function name and (

### ISSUE THREAD

**Issue by t-ce** [elixir-lang/elixir#5761]
### Environment
Fedora 25
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Interactive Elixir (1.3.1)
### Current behavior
In iex, **note** the space between function name (`f`) and `(`:
```
iex(8)> defmodule A do def f (x), do: x end
** (CompileError) iex:8: can use only variables and \\ as arguments in function heads
```
Or as a a program (test.ex) with the same line of code:
```
$ elixir test.ex 
** (CompileError) test.ex:1: can use only variables and \\ as arguments in function heads
```

Also on more lines there is an error:
```elixir
defmodule A do
  def f (x), do: x
end
```
### Expected behavior
Either no error or a correct error message

**Comment by josevalim** [comment]
We will attempt to clarify the error message. Your example is being parsed as `def f((x), do: x)`.

**Comment by kelvinst** [comment]
@josevalim any idea of how the error message could be clarified for this situation? Having hard times to find a good message for it. :rofl: 

All I can think of is something like:

```
only variables and \\\\ are allowed as arguments in definition header.
Tip: the syntax sugar for space instead of parens can be a tricky mud pit.
As you can see in:

    def foo (x), do: x

that is actually parsed like:

    def foo((x), do: x)

```

**Comment by kelvinst** [comment]
Maybe change the `can be a tricky mud pit` by `can generate some confusion`, IDK. :rofl:

**Comment by josevalim** [comment]
```
only variables and \\ are allowed as arguments in definition header.

If you did not intend to define a header, make sure your function definition has
the proper syntax by wrapping the arguments in parentheses and ensuring there
is no space between the function name and arguments, got:

    #{Macro.to_string({:def, [], [{name, _, args}]})}
```

**Comment by t-ce** [comment]
Just an observation: The space is accepted in the multi-line version
```elixir
defmodule A do
  def f (x) do
    x
  end
end
```

**Comment by josevalim** [comment]
@t-ce not if you have multiple arguments, which then is a parser error. It is generally good advice to not add spaces between the function name and arguments. :)

**Comment by kelvinst** [comment]
@t-ce yes, but this does not:

```
defmodule A do
  def f (x, y) do
    {x, y}
  end
end

**Comment by kelvinst** [comment]
Opening a PR really soon. Wait for it!

**Comment by t-ce** [comment]
Thank you.
I tested your code @kelvinst.
```elixir
defmodule A do
  def f (x, y) do
    {x, y}
  end
end
```
And I got
```
** (SyntaxError) iex:2: unexpected parentheses. If you are making a function call, do not insert spaces between the function name and the opening parentheses. Syntax error before: '('
```
That is, there is already a message with the space. Beside _function call_ one could add _or a function definition_

**Comment by kelvinst** [comment]
@t-ce the problem is that in `def f (x), do: x` the compiler understands it like a function header without the body, which cannot have any match expression too. That's why this message you got exist as it is in the first place.

**Comment by kelvinst** [comment]
@josevalim got one problem with `Macro.to_string\1`. I changed the message and in the tests I got `def(f(x) do\n  x\nend\n)` instead of `def(f((x), do: x))`. I have tested here, and got the following result:

```elixir
iex(1)> IO.puts Macro.to_string(quote do: def f (x), do: x)
def(f(x) do
  x
end)
```

Is this a problem with `Macro.to_string`? Or did I lose something?

**Comment by kelvinst** [comment]
Forget about it! I was just confused by the way it prints. Actually `def(f(x) do x end)` is an invalid function header too, the correct would be `def(f(x)) do x end`

**Comment by josevalim** [comment]
I am wondering though if showing that Macro.to_string result will end up
being more confusing?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by kelvinst** [comment]
Well, it's a good point. I got confused pretty easily, maybe only the long description would be less confusing and clear enough. WDYT?

**Comment by josevalim** [comment]
Sounds good!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
