### ISSUE TITLE
Deprecate usage of parse_transforms

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5762]
Elixir supports Erlang parse transforms but if we want to eventually perform less compiler steps and even compile directly to core one day, we will no longer be able to support those.

**Comment by michalmuskala** [comment]
If this is going to happen, we need good alternatives. The only two places, I've used parse transforms were to make `:dbg.fun2ms/1` or `:ets.fun2ms/1` work. If there are convenient alternatives, I see no downsides in going forward with this change.

**Comment by fishcakez** [comment]
Note we don't currently support those two, only a small subset of features
work for those functions. To use them you already need to use another
library or an Erlang module.

**Comment by josevalim** [comment]
@michalmuskala this may be a good starting point: https://github.com/ericmj/ex2ms

**Comment by holsee** [comment]
What do you folks think this will mean for elixir projects which use things like Erlang's lager library which leverages parse transforms to remove logging levels that are not desired for a given build type?

I am working on https://github.com/erlang-lager/lager/issues/348 "Add docs about using lager in elixir" and that is how I stubbled upon this issue.

**Comment by josevalim** [comment]
This is one of the few cases where I would recommend wrapping an Erlang
library in an elixir library and provide the same API with macros.

Parse_transforms work on Erlang AST and being dependent on the Erlang AST
is going to limit the improvements we can do to the Elixir compiler.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
