### ISSUE TITLE
Unexpected interaction between `Stream.concat`, `Stream.take`, and `Stream.transform`

### ISSUE THREAD

**Issue by 4xrsJCr9** [elixir-lang/elixir#5763]
```elixir
% iex
Erlang/OTP 19 [erts-8.2] [source-fbd2db2] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> [1] |> Stream.concat([2]) |> Stream.take(1) |> Stream.transform(0, fn e, a -> {[e], a} end) |> Enum.to_list
[1]
iex(2)> [1] |> Stream.take(1) |> Stream.concat([2]) |> Stream.transform(0, fn e, a -> {[e], a} end) |> Enum.to_list
** (TryClauseError) no try clause matching: {:suspended, [2, 1], #Function<20.36862645/1 in Stream.do_list_transform/9>}
    (elixir) lib/stream.ex:784: Stream.do_transform/8
    (elixir) lib/enum.ex:1776: Enum.reverse/2
    (elixir) lib/enum.ex:2528: Enum.to_list/1
iex(2)>
```

### Environment
`Elixir 1.4.0`
`Linux 3.13.0-85-generic #129-Ubuntu SMP x86_64 GNU/Linux`

### Current behavior

The second expression (`iex(2)`) raises an error.

### Expected behavior

The result of the second expression (`iex(2)`) should be ~~the same as that of the first expression (`iex(1)`)~~ `[1, 2]`.

**Comment by kelvinst** [comment]
First of all, I guess the result will not be the same, that's a wrong assumption since if you concat first and take one after you would have `[1]` and if you take one first and concat after you would get a `[1, 2]`.

Anyways, I'm investigating why this is happening, I guess it's really a bug. Thank you for the report!

**Comment by 4xrsJCr9** [comment]
> First of all, I guess the result will not be the same, that's a wrong assumption since if you concat first and take one after you would have [1] and if you take one first and concat after you would get a [1, 2].

Sorry about that, just slipped my mind.

**Comment by 4xrsJCr9** [comment]
Would I be correct in stating that this is caused when the `case` where `curr` is `1` returns a `{:halt, _}` rather than `{:suspend, _}` as the caller of the function (generated by the `take` macro from the reducers module) expects?

```elixir
fn(entry, acc(head, curr, tail) = original) ->
        case curr do
          0 ->
            {:halt, original}
          1 ->
            {_, acc} = next_with_acc(unquote(fun), entry, head, 0, tail)
            {:halt, acc}
          _ ->
            next_with_acc(unquote(fun), entry, head, curr - 1, tail)
        end
end
```
