### ISSUE TITLE
Erlang core files are not being compiled by the Erlang compiler

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-lang/elixir#5798]
### Precheck

I have the erlang files in the `src` folder, and the `erl` and `yrl` are compiled fine, however the `core` files are not being compiled.  Yet if I run the erlang compiler directly via `erlc blah.core` it creates the `blah.beam` without issue, at which point I can them copy that into the `_build/dev/lib/my_server/ebin` and it works without issue.

### Environment

* Elixir & Erlang versions (elixir --version):
```sh
$ elixir --version
Erlang/OTP 19 [erts-8.2] [64-bit] [smp:8:8] [async-threads:10]

Elixir 1.4.0
```
* Operating system:
   Tested with both Windows 10 and Linux 4.4.0-53

### Current behavior

Some erlang code in `src` is not compiling.

### Expected behavior

For all the erlang code in `src` to compile.

**Comment by OvermindDL1** [comment]
For note, the file formats that `erlc` supports is documented at:  http://erlang.org/doc/man/erlc.html#id200533

I know `erl` and `yrl` and `asn1` work as I use them.  I do not know about `S` or `mib` or `idl` or `bin` or `rel` or so files as I've not tried them, but at the very least `core` is not working.

**Comment by OvermindDL1** [comment]
Well, actually I'm not sure about the asn1, I may have compiled that manually and just copied the files for it too now that I am thinking about it...  >.>

**Comment by josevalim** [comment]
We support only .erl, .xrl and .yrl extensions. Everything else requires a custom compiler.

**Comment by OvermindDL1** [comment]
> We support only .erl, .xrl and .yrl extensions. Everything else requires a custom compiler.

Ah, just based on those few extensions?  Why such a limited set compared to `erlc`?  Where is such a compiler?

**Comment by josevalim** [comment]
https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/compile.erlang.ex

**Comment by OvermindDL1** [comment]
> https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/compile.erlang.ex

Yeah I already fixed it in a replacement version:  https://github.com/OvermindDL1/mix_compile_erlang_core/blob/master/lib/mix/tasks/compile.erlang.ex  ^.^

I'd of PR'd it but the `We support only` implies "only", hence the word only, but if it is not actually 'only' I can PR it back.  :-)

**Comment by josevalim** [comment]
I don't see a reason to directly support core from Elixir. It is definitely an advanced feature and I expect only very few developers to actually want to use on it. We have decided to keep compilers that are much more used, such as the make compiler, out so I don't see a reason to include a core one.

**Comment by OvermindDL1** [comment]
It's not a build system like make or anything of the sort, it is just a post-processed format of erl files that are output by a few things (better scoping control and such), it is supported by erlc itself as shown in the original post and compiles to the same beam files as erl.  Are you stating that a `Makefile should be used instead?  I'm unsure how well that would work on Windows... (which, sadly, I have to support...)  >.>

Actually, can mix even use a Makefile for/in the current project?  Or rebar for that matter?  I'm only finding things about it using those in dependencies?  So I'm unsure how making a Makefile to call erlc would solve the issue?

**Comment by josevalim** [comment]
Sorry, I am not saying you should use a Makefile. Your current compiler is the way to go.

What I am saying is that we are not adding more compilers to Mix and we have already rejected other compilers in the past (in this case, a Makefile-based compiler).

**Comment by OvermindDL1** [comment]
> Sorry, I am not saying you should use a Makefile. Your current compiler is the way to go.

Heh, my current one is such a hack though, perhaps if it were cleaned up (it handles both erl and core files since the code between them is identical).  ^.^

> What I am saying is that we are not adding more compilers to Mix and we have already rejected other compilers in the past (in this case, a Makefile-based compiler).

Yeah I'd find makefile based ones awfully platform specific to support, but it is odd not to support a format that is already supported by native erlang is what my thinking was, though being an advanced use in general does make sense to try to hide it (though I'd probably have done that via just not documenting it instead of having the code not work at all, or at least toss a warning?).  ^.^
