### ISSUE TITLE
`Task.Supervisor.start_child` failed silently when `args` is not a list

### ISSUE THREAD

**Issue by timnew** [elixir-lang/elixir#5801]
### Environment

* Elixir & Erlang versions (elixir --version):

Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2

* Operating system:

macOS Sierra 10.12.4 Beta (16E154a)

### Current behavior

Not sure whether it is counted as a bug. 

I have code as following:

```elixir
{:ok, pid} = Task.Supervisor.start_child(Task.Supervisor, MyModule, :my_method, {:action, "text})
```

The last parameter of `Task.Supervisor.start_child` should be a `list`, but given a tuple.
The code should fail but it runs. It returns `:ok` with a pid, but the method is never called.

### Expected behavior

Throw an error at runtime complaining about the argument should be `list`

**Comment by timnew** [comment]
I think it is possible to fix the issue by changing `Task.Supervisor. start_child` signature from 
```elixir
def start_child(supervisor, module, fun, args) do
```
to 
```elixir
def start_child(supervisor, module, fun, args) when is_atom(module) and is_atom(fun) and is_list(args) do
```

But not sure whether it is a good solution.

If it is acceptable, I can provide a PR to fix the issue and add related tests.

**Comment by josevalim** [comment]
Yes, please do provide a PR. :)

**Comment by timnew** [comment]
@josevalim PR is ready, tests added and passed on CI. 
Please have a look. Cheers.
