### ISSUE TITLE
Feature | Auto recompile on source file change

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#5803]
I was suggested in #elixir-lang that this is the correct place for feature requests. Close this issue if its not.

The request is to add support to mix via a task or other to allow automatic calls to recompile when a source file changed.

I currently wiped up a project to do this https://github.com/vans163/mix_auto.  But built in support seems very useful, for example calling mix like 'iex -S mix watch' would make it so when any project in the deps or the projects own lib/ folder has source code change, IEx.Helpers.recompile/0 gets called.

Currently remix is not up to the task due to bugs such as it not properly loading modules after it reloads the code or the fact that it crashes and takes 10 seconds to restart itself if there is an error in the new code.  Also remix is not evented meaning it polls the file system.

**Comment by whatyouhide** [comment]
Hey @vans163!

> I was suggested in #elixir-lang that this is the correct place for feature requests.

Mmh 🤔, they were wrong! 😄 The correct place for feature requests is the [elixir-lang-core](https://groups.google.com/forum/#!forum/elixir-lang-core) mailing list where the whole community can discuss ideas and proposals before they move to the "accepted" stage where we then open an issue and the community can start working on an implementation. So I would advise to post the proposal there :)

Thanks for the input though!

**Comment by vans163** [comment]
@whatyouhide My mistake!
