### ISSUE TITLE
using recompile/0 cannot find modules if messages are inflight

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#5809]
### Environment

Erlang/OTP 19 [erts-8.2.1] [source-83292f7] [64-bit] [smp:24:24] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0-dev (58a75f6)

Linux, kernel 3.10.0-327.el7.x86_64

### Current behavior

When using recompile/0 if messages are inflight like a state_timeout for a gen_statem often we crash with an error that modules cannot be loaded.

Reason for termination = :error:{:"module could not be loaded", MyApp.MainGSM}

### Expected behavior

The expected behavior is for execution to continue as normal.

**Comment by josevalim** [comment]
@vans163 I will update the docs to mention that's the case since we need to ensure a clean slate of recompiled modules and for a while the module is indeed not defined.

**Comment by vans163** [comment]
@josevalim Is there anyway this could be fixed with a pull? Or is it quite complex for me to tackle?

**Comment by josevalim** [comment]
It cannot be fixed, it is a consequence of how Elixir's parallel compiler works.
