### ISSUE TITLE
using recompile/0 on a IN_CLOSE_WRITE inotify event corrupts _build folder

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#5815]
### Environment

Erlang/OTP 19 [erts-8.2.1] [source-83292f7] [64-bit] [smp:24:24] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0-dev (58a75f6)

Linux, kernel 3.10.0-327.el7.x86_64

### Current behavior

Modules fail to load with a timing or truncated source file issue, not sure.  The way to replicate the problem is to create a boilerplate elixir project on a remote target (linux) and run it via iex -S mix.  Then you need to call recompile/0 at the exact time the filesystem triggers an event notification that a IN_CLOSE_WRITE inotify event occurred  (http://man7.org/linux/man-pages/man7/inotify.7.html).  The result is that _build folder gets corrupt and you need to rm -rf _build + recompile the project to fix it. Restarting the shell via iex -S mix keeps the app in the corrupt built state and you cannot call any module. They fail with error module not loaded.

The compiler generates no errors and continues as if everything was fine.

To be clear you need to save the file locally when you sshfs the targets dir.

If you do not immediately call recompile but wait 1s for example, no corruption occurs.

I could not reproduce this without sshfs.

The sshfs command is 
```
sshfs -o auto_cache,reconnect,ServerAliveInterval=15,ServerAliveCountMax=3 user@server:/elixir_boilerplate
```

To help replicate you can include the project {:mix_auto, git: "https://github.com/vans163/mix_auto.git", ref: "6c25ed3e5d10"} and start the application :mix_auto.  This listens for inotify notifications and immediately issues a recompile.

This is probably related to https://github.com/elixir-lang/elixir/issues/5809.

I think something related to this is the parallel compiler fails to find the module due to the timing that sshfs introduces but finishes compiling the project without that module.  Then for some reason when you restart iex -S mix without rm -rf _build, it thinks that module is still missing.  I noticed similar behavior happens when you produce an error in a module and call recompile, the project compiles but the file with the error just gets excluded (instead of loading the previous working version).

EDIT: I just added this commit (300ms delay after a IN_CLOSE_WRITE before call to recompile/0) and it fixes the problem so far,
https://github.com/vans163/mix_auto/commit/0e731810fdceab17b845c2a64bd4cc9a8fcbcb80.

But still mix should not be corrupting the _build folder like this, not under any circumstances and without erroring.

**Comment by josevalim** [comment]
@vans163 I am not familiar with sshfs so it is not clear on the impacts it may have on Mix. However, I am confident if you have two different entities writing to _build, Mix and something syncing in, your _build directory **will get corrupted**.

> I think something related to this is the parallel compiler fails to find the module due to the timing that sshfs introduces but finishes compiling the project without that module

Can you please explain the timing issue here? Where is the race happening? Which file is being added, what is being removed and what is leading to recompilation?

**Comment by vans163** [comment]
@josevalim nothing is writing to _build as recompile is going on.  

The only thing going on is testt.ex file gets saved locally, this triggers sshfs locally and sshfs pushes the file to the remote (i dont think sshfs is at fault here as this could happen using regular cp/scp probably), on the remote the filesystem is being listened to by inotify, once sshfs finishes the write inotify triggers a IN_CLOSE_WRITE event meaning the file has been written to and got closed, we call recompile/0 immediately, but recompile does not pick up the file that was just saved, regardless it compiles the rest of the project with the file missing, thats fine.  

When we try to call into that now missing testt.ex the modules in it are missing. We kill the iex and restart the app via iex -S mix, and the same thing we cannot call the modules in testt.ex.

**Comment by josevalim** [comment]
@vans163 if I understand correctly, the testt.ex file is pushed but Elixir cannot find it in the remote server when recompile() is invoked. Have you checked what happens if you print `IO.inspect File.stat("path/to/file/just/pushed")`? Can File.stat find the file?

**Comment by vans163** [comment]
So first we call Testt.Test.test and nil. Fine.

Now when we save the file we get the stat first, we see the filesize is 0, this probably means sshfs does a delete+add. We start recompile when the filesize is 0 and immediately we get another IN_CLOSE_WRITE event that the file has size 55 now. We call recompile/0 again.

Then when we try and call the module its undefined.  Kill the shell and restart iex -S mix, its still undefined.

I see the problem we start compile when the filesize is 0 and potentially call a second recompile before the first finished, but it should not break things.

```
iex(5)> Testt.Test.test
nil
iex(6)> 
18:58:08.205 [info]  Elixir.MixAuto.Worker: File changed /elixir_compile/lib/testt.ex
{:ok,
 %File.Stat{access: :read_write, atime: {{2017, 2, 23}, {23, 58, 3}},
  ctime: {{2017, 2, 23}, {23, 58, 8}}, gid: 0, inode: 665463, links: 1,
  major_device: 65025, minor_device: 0, mode: 33188,
  mtime: {{2017, 2, 23}, {23, 58, 8}}, size: 0, type: :regular, uid: 0}}
Compiling 1 file (.ex)
Generated Testt app

18:58:08.252 [info]  Elixir.MixAuto.Worker: File changed /elixir_compile/lib/testt.ex
{:ok,
 %File.Stat{access: :read_write, atime: {{2017, 2, 23}, {23, 58, 3}},
  ctime: {{2017, 2, 23}, {23, 58, 8}}, gid: 0, inode: 665463, links: 1,
  major_device: 65025, minor_device: 0, mode: 33188,
  mtime: {{2017, 2, 23}, {23, 58, 8}}, size: 55, type: :regular, uid: 0}}

18:58:09.551 [info]  Elixir.MixAuto.Worker: File changed /elixir_compile/lib/testt.ex
{:ok,
 %File.Stat{access: :read_write, atime: {{2017, 2, 23}, {23, 58, 3}},
  ctime: {{2017, 2, 23}, {23, 58, 9}}, gid: 0, inode: 665463, links: 1,
  major_device: 65025, minor_device: 0, mode: 33188,
  mtime: {{2017, 2, 23}, {23, 58, 9}}, size: 0, type: :regular, uid: 0}}
Compiling 1 file (.ex)

18:58:09.608 [info]  Elixir.MixAuto.Worker: File changed /elixir_compile/lib/testt.ex
{:ok,
 %File.Stat{access: :read_write, atime: {{2017, 2, 23}, {23, 58, 3}},
  ctime: {{2017, 2, 23}, {23, 58, 9}}, gid: 0, inode: 665463, links: 1,
  major_device: 65025, minor_device: 0, mode: 33188,
  mtime: {{2017, 2, 23}, {23, 58, 9}}, size: 55, type: :regular, uid: 0}}

nil
iex(7)> Testt.Test.test
** (UndefinedFunctionError) function Testt.Test.test/0 is undefined (module Testt.Test is not available)
    (Testt) Testt.Test.test()
iex(7)> Testt.Test.test
** (UndefinedFunctionError) function Testt.Test.test/0 is undefined (module Testt.Test is not available)
    (Testt) Testt.Test.test()
iex(7)> 
18:58:41.535 [info]  Elixir.MixAuto.Worker: File changed /elixir_compile/lib/testt.ex
{:ok,
 %File.Stat{access: :read_write, atime: {{2017, 2, 23}, {23, 58, 3}},
  ctime: {{2017, 2, 23}, {23, 58, 41}}, gid: 0, inode: 665463, links: 1,
  major_device: 65025, minor_device: 0, mode: 33188,
  mtime: {{2017, 2, 23}, {23, 58, 41}}, size: 0, type: :regular, uid: 0}}
Compiling 1 file (.ex)

18:58:41.602 [info]  Elixir.MixAuto.Worker: File changed /elixir_compile/lib/testt.ex
{:ok,
 %File.Stat{access: :read_write, atime: {{2017, 2, 23}, {23, 58, 3}},
  ctime: {{2017, 2, 23}, {23, 58, 41}}, gid: 0, inode: 665463, links: 1,
  major_device: 65025, minor_device: 0, mode: 33188,
  mtime: {{2017, 2, 23}, {23, 58, 41}}, size: 55, type: :regular, uid: 0}}

nil
iex(8)> Testt.Test.test
** (UndefinedFunctionError) function Testt.Test.test/0 is undefined (module Testt.Test is not available)
    (Testt) Testt.Test.test()
iex(8)> 
```

**Comment by josevalim** [comment]
Thanks for the detailed updates.

> I see the problem we start compile when the filesize is 0 and potentially call a second recompile before the first finished, but it should not break things.

The filesize is 0, probably meaning the contents have not been written yet, and yet the mtime has already been updated. Because Mix works based on the mtime, the only way Mix could detect this is by also storing the size in its manifest and comparing the sizes. However, it really feels like you should not invoke compile when the file contents have not been written yet.

Isn't there a better event on inotify you could rely on?

**Comment by vans163** [comment]
@josevalim 

Im not sure I looked and this was the best I found.  

Regardless this problem will crop up randomly 1/100,000 times especially for users that use different file systems or nfs/smb/etc.  Basically I think this implies that if a recompile is going on and something touching something at the wrong time, itl corrupt the entire _build folder.  I hear reports of random rare bugs where the only fix is to rm -rf _build, maybe this is one of the reasons.

**Comment by josevalim** [comment]
You are right. We are going to add a mechanism that ignores and warns for files that have no size under certain circumstances. This will at least guarantee the test file will be picked up the next time around.

Btw, you likely do not need to remove `rm -rf _build`, if you save the file the compiler missed, it should be able to pick it up the next time around, no?

**Comment by vans163** [comment]
@josevalim Thats the thing, once the file is there again (size 55 vs 0) using iex -S mix does not pick it up, neither does recompile, or mix compile.  (this is a different system I tested this particular test case on)

```
user@server:~/elixir_compile# ls -l lib/
total 8
-rw-r--r-- 1 user user 302 Feb 23 12:58 ex.ex
-rw-r--r-- 1 user user  55 Feb 23 18:58 testt.ex
user@server:~/elixir_compile# iex -S mix
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]


10:50:05.083 [info]  Elixir.MixAuto.Worker: Started watcher on lib/
starting app
Interactive Elixir (1.5.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Testt.Test.test
** (UndefinedFunctionError) function Testt.Test.test/0 is undefined (module Testt.Test is not available)
    Testt.Test.test()
iex(1)> recompile()
:noop

user@server:~/elixir_compile# mix compile
user@server:~/elixir_compile# iex -S mix
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]


10:52:22.652 [info]  Elixir.MixAuto.Worker: Started watcher on lib/
starting app
Interactive Elixir (1.5.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Testt.Test.test
** (UndefinedFunctionError) function Testt.Test.test/0 is undefined (module Testt.Test is not available)
    Testt.Test.test()
```

**Comment by josevalim** [comment]
>  Thats the thing, once the file is there again (size 55 vs 0) using iex -S mix does not pick it up, neither does recompile, or mix compile

Even if you explicitly touch or save the file, bumping its mtime?

**Comment by vans163** [comment]
@josevalim Ah, if I change the mtime, iex -S mix recompiles the project.

**Comment by josevalim** [comment]
A fix has been pushed to master. Can you please give it a try and let us know if the problem persists by any chance? Thank you!
