### ISSUE TITLE
Add :printable_limit to inspect

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5817]
This will control the limit for printable lists and binaries. It is important the `printable?` check also respects printable_limit, ensuring both the check and the subsequent formatting is as fast as possible.

**Comment by benwilson512** [comment]
Presumably `printable?` will retain a 1-arity form that is limitless for backwards compatibility, but have a 2-arity form that is `String.printable?(str, limit: n_bytes)` ?

**Comment by benwilson512** [comment]
So the hardest bit here is figuring out what we mean by a limit on `String.printable?`. Codepoints? bytes? If bytes, we need to really go to the nearest code point direction or another.

**Comment by benwilson512** [comment]
Actually this may be simple. How about:
```
def printable?(str, limit: limit) do
  str
  |> split_at(0..limit)
  |> printable?
end
```

**Comment by josevalim** [comment]
@benwilson512 the problem is that we cannot assume str is a utf-8 encoded binary. That's why we need to call `String.printable?(string, n_codepoints)` and count codepoints at the same time we check if it is printable.

**Comment by benwilson512** [comment]
Sorry I meant to use `String.slice` which seems to handle both utf8 and non utf8 content fine. Is that not correct?

**Comment by josevalim** [comment]
@benwilson512 it handles it fine at the cost of traversing it multiple times. We would make it faster for larger binaries but add one extra pass for small ones.

**Comment by benwilson512** [comment]
Ahh ok. Well I'll stop being lazy and write the optimal custom version :)

**Comment by josevalim** [comment]
@benwilson512 it may be even ideal to escape, limit and check if printable in a single pass BUT that may be more expensive for cases where it is not printable. So I think two passes, one for check and another doing the operation is the ideal one.

**Comment by benwilson512** [comment]
I agree. I'm planning to add the counter to `printable?` always and simplely handle `:infinity` as the default. I think the cost of handling the extra argument is negligible, and duplicating the logic for `printable?` doesn't seem worth it.
