### ISSUE TITLE
Date.compare/2, DateTime.compare/2, NaiveDateTime.compare/2 happily compare across calendars.

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#5842]
### Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 19 [erts-8.0] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false]

Elixir 1.5.0-dev (8ecc48180)
* Operating system: Linux Mint Rafaela

### Current behavior

`DateTime.compare(left, right)`, `NaiveDateTime.compare(left, right)` and `Date.compare(left, right)` do not care if the `:calendar`s of `left` and right are the same. This means that they will return unexpected results when attempting to compare two Dates/DateTimes/NaiveDateTimes that are not of the same calendar.

### Expected behavior

These functions should throw an error when passing two elements from different calendars to them (at least until #5841 is done and for some cross-calendar comparisons more useful results can be returned).

**Comment by josevalim** [comment]
This is not true. :) The `to_tuple` implementation checks if the calendar type is precisely `Calendar.ISO`. It will fail for all other calendars: https://github.com/elixir-lang/elixir/blob/8ecc481808ed5b6c90426b43d565f936be241192/lib/elixir/lib/calendar.ex#L1400

**Comment by Qqwy** [comment]
Yes, you are completely right! :+1:
