### ISSUE TITLE
`mix test --cover` ArgumentError in :cover module

### ISSUE THREAD

**Issue by schnittchen** [elixir-lang/elixir#5843]
I'm using CoberturaCover, and the problem could be anywhere in the stack...

I've created a repo at https://github.com/schnittchen/faulty-cover for reproducing the problem.

### Environment

Elixir 1.4.1, Erlang/OTP 19 [erts-8.2.2] on Ubuntu yakkety

### Current behavior

```
✓ mix test --cover
Compiling 2 files (.ex)
Generated foo app
Cover compiling modules ... 

13:27:12.063 [error] Process #PID<0.167.0> raised an exception
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:318: :erl_anno.set(:location, -1, [location: -1, generated: true])
    (stdlib) erl_parse.yrl:1515: anonymous fn/3 in :erl_parse.map_anno/2
    (stdlib) erl_parse.yrl:1644: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1657: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1636: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1657: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1647: :erl_parse.modify_anno1/3
    (stdlib) erl_parse.yrl:1657: :erl_parse.modify_anno1/3
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) erl_anno.erl:318: :erl_anno.set(:location, -1, [location: -1, generated: true])
        (stdlib) erl_parse.yrl:1515: anonymous fn/3 in :erl_parse.map_anno/2
        (stdlib) erl_parse.yrl:1644: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1657: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1636: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1657: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1647: :erl_parse.modify_anno1/3
        (stdlib) erl_parse.yrl:1657: :erl_parse.modify_anno1/3
    cover.erl:583: :cover.call/1
    lib/cobertura_cover.ex:6: CoberturaCover.start/2
    (mix) lib/mix/tasks/test.ex:206: Mix.Tasks.Test.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2


13:27:12.064 [error] Process #PID<0.168.0> raised an exception
** (ArgumentError) argument error
    (stdlib) :ets.insert(:cover_internal_clause_table, {Foo, [{Foo, :__info__, 1, 1, 1}, {Foo, :__info__, 1, 2, 1}, {Foo, :__info__, 1, 3, 1}, {Foo, :hello, 0, 1, 1}]})
    cover.erl:1584: :cover.do_compile_beam2/5
    cover.erl:1478: :cover.do_compile_beam/3
    (stdlib) lists.erl:1239: :lists.map/2
    cover.erl:2732: anonymous fn/2 in :cover.pmap_spawn/4
```

**Comment by josevalim** [comment]
I believe you are using an Elixir compiled for Erlang 18. Does it happen if you compile Elixir using Erlang 19?

**Comment by schnittchen** [comment]
I removed the erlang-solutions package, esl-erlang and elixir and went through http://elixir-lang.org/install.html#unix-and-unix-like again. I removed _build and ran `mix test --cover` again. The problem persists.

**Comment by schnittchen** [comment]
Is there a way to tell, maybe from the contents of `/usr/local/lib/elixir/lib/elixir/ebin`?

**Comment by schnittchen** [comment]
I have removed the Elixir package but kept Erlang 19.2, then cloned the elixir repo, checked out the v1.4.1 tag and installed via `make && make install`. Same result.

**Comment by josevalim** [comment]
Hrm, I cannot reproduce it in master. Can you?

**Comment by schnittchen** [comment]
Master fails upon compiling postgrex :(

(I tried inside a project I extracted the problem out of into the linked repo)

I'll build a clean container and try reproducing there, later this day.

**Comment by josevalim** [comment]
`mix deps.update postgrex` and it should work. :)

**Comment by schnittchen** [comment]
I used vagrant to reproduce, see https://github.com/schnittchen/faulty-cover/commit/f5b4f694789446560b4eaf5c3c0a34016bb3eddb and the two parent commits.

It's broken in 1.4.1, including the version debian/ubuntu users would install from the package repo, but fixed on master.
