### ISSUE TITLE
Wrong variable name in docs for Access.get_and_update/3

### ISSUE THREAD

**Issue by christhekeele** [elixir-lang/elixir#5846]
At a glance I can't figure out why this is so, since I'm not familiar with how these get generated, but the short signature for [`c:Access.get_and_update/3`](https://hexdocs.pm/elixir/Access.html#c:get_and_update/3) is called `list` [when it should be](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/access.ex#L202) `fun`.

**Comment by christhekeele** [comment]
This might be an [exdoc thing](https://github.com/elixir-lang/ex_doc/blob/018cc55a436755cf2e6c727b806e4641f97a3352/lib/ex_doc/retriever.ex#L347-L389).

**Comment by josevalim** [comment]
Yes, it is. can you please file an ExDoc bug? Thank you!
