### ISSUE TITLE
Add some documentation to Process as to what it means to be 'suspended'

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#5847]
### Environment

* Elixir & Erlang versions (elixir --version):
* Operating system:

### Current behavior

Recently a [question on the Elixir Forum](https://elixirforum.com/t/purpose-of-infinity/4014) was asked, as to what it means for a process to be suspended, such as e.g. using [`Process.sleep(:infinity)`](https://hexdocs.pm/elixir/Process.html#sleep/1).

While I was able to find information on this in the Erlang documentation, such as [`:sys.suspend/1`](http://erlang.org/doc/man/sys.html#suspend-1), I believe that explaining in one or two sentences what it means to be suspended would be a good addition to the documentation of the Process module.

**Comment by josevalim** [comment]
`:sys.suspend` and `Process.sleep(:infinity)` are very different from each other. `Process.sleep(:infinity)` simply means the process will sleep forever. While `:sys.suspend/1` is specific to OTP processes so they temporarily stop replying to messages, in case you want to perform hot code upgrades and other changes. We already have a section about the `:sys` module in the GenServer docs, so there seems like a good point for further clarification.

**Comment by robinsjdotcom** [comment]
I added a sentence on the suspended state of a process, as that it will not consume or reply to messages. I didn't add fact that a suspended process, will still reply to some system processes.

Can find the proposed changes  in #5848 😄

**Comment by whatyouhide** [comment]
Closed in #5848 and https://github.com/elixir-lang/elixir/commit/97810dd836a9fe52448bfd592b735b0160f4c47e.
