### ISSUE TITLE
Unicode.ex compile fails on armv71

### ISSUE THREAD

**Issue by alisinabh** [elixir-lang/elixir#5856]
Compile of ``unicode.ex `` fails on armv71 architecture.
I've build and installed Erlang 19.2 with kerl on it. erlang seems to work fine. elixir 1.1-dev installs fine from apt but 1.4.2 wont install because of following error in ``make`` command.

### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 19 [erts-8.2] [source] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]
* Operating system: Linux FriendlyARM 3.4.39-h3 #24 SMP PREEMPT Sat Feb 4 15:23:58 CST 2017 armv7l armv7l armv7l GNU/Linux
* Hardware: NanoPi Neo 512mb

### Current behavior

make[1]: Entering directory '/root/elixir-1.4/elixir-1.4.2'
==> unicode (compile)
Compiling unicode/unicode.ex (it's taking more than 5s)
Killed
Makefile:91: recipe for target 'lib/elixir/ebin/Elixir.String.Unicode.beam' failed
make[1]: *** [lib/elixir/ebin/Elixir.String.Unicode.beam] Error 137
make[1]: Leaving directory '/root/elixir-1.4/elixir-1.4.2'
Makefile:78: recipe for target 'lib/elixir/ebin/Elixir.Kernel.beam' failed
make: *** [lib/elixir/ebin/Elixir.Kernel.beam] Error 2

**Comment by josevalim** [comment]
@alisinabh your OS is killing it because of lack of memory. The Unicode module requires loading large UTF tables into memory and optimizing those tables, there is not much we can do here, unfortunately. My suggestion is to use precompiled Elixir.

**Comment by alisinabh** [comment]
Thank you @josevalim

**Comment by randysecrist** [comment]
I'm seeing this while building elixir with docker on alpine.  Considering options... anyone know if it is possible to increase the RAM used during a docker build?
