### ISSUE TITLE
Options for erl are not removed from $@

### ISSUE THREAD

**Issue by fxn** [elixir-lang/elixir#5881]
I noticed that that the options in a call to `elixir` that are intended for `erl` get passed also in `-extra`, because it gets the whole thing as `"$@"`.

For example, launching `iex` results in

```
erl ... -user Elixir.IEx.CLI -extra --no-halt --erl "-user Elixir.IEx.CLI" +iex
```

In this case, we see `--erl "-user Elixir.IEx.CLI"` duplicated in the call.

Maybe that is intentional, in which case this issue would be closed. Otherwise I could volunteer a patch.

**Comment by josevalim** [comment]
It is intentional since we want to keep all options for Elixir's CLI later processing. The fact they had to be handled earlier is an implementation detail. :)

**Comment by fxn** [comment]
Cool!
