### ISSUE TITLE
mix archive.install error 

### ISSUE THREAD

**Issue by sergey-ivlev** [elixir-lang/elixir#5882]
if the name of archive is differ from contained folder
f. e. phoenix_new_1503.ez 
or when it downloaded twice
phoenix_new (1).ez

then  mix archive.install failed with :bad_directory reason 

➜ mix archive.install phoenix_new\ \(1\).ez 
Are you sure you want to install archive "phoenix_new (1).ez"? [Yn] Y
* creating .mix/archives/phoenix_new (1)
** (MatchError) no match of right hand side value: {:error, :bad_directory}
    (mix) lib/mix/tasks/archive.install.ex:97: Mix.Tasks.Archive.Install.install/3
    (mix) lib/mix/local/installer.ex:107: Mix.Local.Installer.do_install/3
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2

may be we can added some checkes for this case?
and print more user-frendly text for error?

**Comment by josevalim** [comment]
Definitely, thank you for the report.

**Comment by sergey-ivlev** [comment]
thanks a lot

**Comment by kamilchm** [comment]
I encounter this error with
```
$ mix -v
Erlang/OTP 18 [erts-7.3.1.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.4.4
```

trying to install:
```
$ mix archive.install https://github.com/Virviil/agala/releases/download/v1.0.3/agala_new.ez
Found existing archive: /home/kamil/.mix/archives/agala_new.
Are you sure you want to replace it with "https://github.com/Virviil/agala/releases/download/v1.0.3/agala_new.ez"? [Yn] y
* creating /home/kamil/.mix/archives/agala_new
** (MatchError) no match of right hand side value: {:error, :bad_directory}
    (mix) lib/mix/tasks/archive.install.ex:97: Mix.Tasks.Archive.Install.install/3
    (mix) lib/mix/local/installer.ex:107: Mix.Local.Installer.do_install/3
```
