### ISSUE TITLE
Compiler doesn't check invalid module/variable "SString"

### ISSUE THREAD

**Issue by mbenatti** [elixir-lang/elixir#5897]
### Environment

* Elixir & Erlang versions (elixir --version): 1.4.2
* Operating system: mint 18

### Current behavior

With code: 
```Elixir
defmodule SString.Invalid do
  try do
    cSString.to_integer("10")
  rescue
    e -> "Message: #{e.message}"
  end
end
```
Output:
```
$ iex example.ex              
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

** (KeyError) key :message not found in: %UndefinedFunctionError{arity: 1, exports: nil, function: :to_integer, module: SString, reason: nil}
    example.ex:5: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

With code:

```Elixir
defmodule SString.Invalid do
  try do
    cSString.to_integer("10")
  rescue
    e -> "Message: #{e.message}"
  end
end
```
Output:
```
$ iex example.ex
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

warning: variable "cSString" does not exist and is being expanded to "cSString()", please use parentheses to remove the ambiguity or change the variable name
  example.ex:3

** (CompileError) example.ex:3: undefined function cSString/0
    (stdlib) lists.erl:1239: :lists.map/2
```

The error can be reproduced with more "S" too
like: "SString", "SSSSString"

### Expected behavior

Compiler check invalid module/variable SString

---
In this example code like these will not print the `e -> "Message: #{e.message}"` and will raise an error

**Comment by josevalim** [comment]
Modules can be loaded dynamically at any time in Elixir so we cannot check if a module is available at compile time. You need to attempt to invoke it or check if it is available yourself.

**Comment by mbenatti** [comment]
@josevalim 

Look my two examples, the first output doesn't need to be the same as the second?
They are the same thing.

**Comment by josevalim** [comment]
You have an error in one of your examples because they are both the same here and they both yield the same error.

**Comment by josevalim** [comment]
Also note you cannot do `e.message`. Exceptions are not guaranteed to have a message field. Use `Exception.message(e)` instead.

**Comment by fishcakez** [comment]
I think the first one is supposed to be:
```elixir
defmodule SString.Invalid do
  try do
    SString.to_integer("10")
  rescue
    e -> "Message: #{e.message}"
  end
end
```
This does a call to undefined function in another module, the second does a call to undefined call in same function. The compiler catches the later because it knows whats in the scope of the current module and can't evaluate the code. However same is not true for call to another module, and it can.

**Comment by josevalim** [comment]
Also worth noting that in a Mix project we do check external calls since we
have all modules in there.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by mbenatti** [comment]
@fishcakez You are right, by mistake I put two same examples...

The first code example its with "SString"

`Elixir
defmodule SString.Invalid do
  try do
    SString.to_integer("10")
  rescue
    e -> "Message: #{e.message}"
  end
end
`

The case its using SString.to_integer/1 or cSString.to_integer/1 (both modules and function not exists..) by the logic will be produced the same output, 

More clear code snipts

1) Using invalid module SString:

`Elixir
defmodule SString.Invalid do
  def test do
    try do
      SString.to_integer("10")
    rescue
      e -> "Message: #{Exception.message(e)}"
    end
  end
end
`
Output:
`
$ iex example.ex
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.4.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> SString.Invalid.test
"Message: function SString.to_integer/1 is undefined (module SString is not available)"
`
2) Using another module (using cSString.to_integer/1) its runtime error(UndefinedFunctionError):

`Elixir
defmodule SString.Invalid do
  def test do
    try do
      cSString.to_integer("10")
    rescue
      e -> "Message: #{Exception.message(e)}"
    end
  end
end
`

Output:
`
$ iex example.ex
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

warning: variable "cSString" does not exist and is being expanded to "cSString()", please use parentheses to remove the ambiguity or change the variable name
  example.ex:4

** (CompileError) example.ex:4: undefined function cSString/0
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
`

**Comment by josevalim** [comment]
@mbenatti I see. As @fishcakez explained, `cSString` is no longer a module but a variable and function call. So the examples are not really comparable. If you put `1` before the module name, such as `1SString`, then it is neither and will directly raise a compilation error.
