### ISSUE TITLE
Doctests aren't always updated

### ISSUE THREAD

**Issue by bopjesvla** [elixir-lang/elixir#5905]
Elixir version:

```
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.1
```

Steps to reproduce:

- `mix new doctest`
- `cd doctest`
- `mix test`, succeeds as it should
- Change `:world` to `:worl` in the lib/test.ex doc
- `mix test`, succeeds
- Make an unrelated change to lib/test.ex to force recompilation
- `mix test`, fails

**Comment by josevalim** [comment]
Thank you for the report. Unfortunately I cannot reproduce this on master.

**Comment by josevalim** [comment]
To add a little bit of more information, `mix test` fails as soon as I change `:world` to `:worl`.

**Comment by bopjesvla** [comment]
To be clearer, the change should be in the @doc module attribute, not in the actual code. Other than that, I'm on Ubuntu 14.04.

**Comment by josevalim** [comment]
Yes, I changed the doc module attribute and everything works as expected. Can you consistently reproduce it?

**Comment by bopjesvla** [comment]
I tried this two more times, and the second time I failed to reproduce the erroneous behavior. But after I added the d back, ran mix test, removed the d, ran mix test again, tests succeeded as before.

**Comment by josevalim** [comment]
Do you have any special setup? Shared FS driver? Use vagrant? Etc?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by bopjesvla** [comment]
Right, I'm using asdf as a version manager, and I am on a shared filesystem. In hindsight I should've given these details right away.

Also, I tried the exact same procedure with the test in doctest_test.exs, which fails and succeeds as expected.

**Comment by josevalim** [comment]
Can you remove the shared file system? Pen make sure it is reporting the
proper mtimes. I am afraid it doesn't .
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by bopjesvla** [comment]
If this is just a quirk in my personal setup no one else has ever encountered I might as well work around it. Just ping me if anyone else reports the same problem and you need additional information to discover the pattern.
