### ISSUE TITLE
Mismatched Typespecs Between Supervisor and Application

### ISSUE THREAD

**Issue by adsteel** [elixir-lang/elixir#5912]
### Environment

Elixir version:

```bash
$ elixir --version
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.1
```

OS: MacOS 10.12.13

### Current behavior

Defining an Application a la [the docs](https://hexdocs.pm/elixir/Application.html#module-application-module-callback) means a module using the Application behavior should have a [`&Application.start/2`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/application.ex#L133) function that returns:

```elixir
 @callback start(start_type, start_args :: term) ::
    {:ok, pid} |
    {:ok, pid, state} |
    {:error, reason :: term}
```

However, the return value of `&Application.start/2` is commonly the return value of `&Supervisor.start_link/2`, which has a return value of [`Supervisor.on_start`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/supervisor.ex#L247), meaning:

```elixir
@type on_start :: {:ok, pid} | :ignore |
                             {:error, {:already_started, pid} | {:shutdown, term} | term}
```

This was caught using [Dialyxir](https://github.com/jeremyjh/dialyxir), because `:ignore` is not a valid `&Application.start/2` return value.

```bash
The return type 'ignore' in the specification of start/2 is not a subtype of {'error',_} | {'ok',pid()} | {'ok',pid(),_}, which is the expected return type for the callback of 'Elixir.Application' behaviour
```

### Expected behavior

`&Supervisor.start_link/2` cannot return a value that `&Application.start/2` is not expecting.

**Comment by adsteel** [comment]
I've discovered a related issue where `&Supervisor.init` expects a different set
of possible return values than `&Supervisor.Spec.supervise` says it will
return. Should that be opened in a new issue, or should I augment this issue's description to include both?

**Comment by josevalim** [comment]
You can fix so in your application by matching on the result of `{:ok, pid} = Supervisor.start_link(...)` and then returning `{:ok, pid}`. The application callback does not allow `:ignore` to be returned and fail otherwise.

To me this is an issue Dialyzer being unable to see what the `init` callback returns, since in most cases it is unlikely that it will return `:ignore`.
