### ISSUE TITLE
Mix: hex.publish task crashes when using a sparse git dependency

### ISSUE THREAD

**Issue by rschmukler** [elixir-lang/elixir#5913]
### Current behavior

When using a `mix.exs` file with a git-based dependency that specifies a `sparse` option and attempting to publish a package onto hex (via `mix hex.publish`), the task will crash with the following stack trace:

```
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir) lib/io.ex:445: IO.chardata_to_string(nil)
    (elixir) lib/path.ex:468: Path.join/2
    (mix) lib/mix/scm/git.ex:130: Mix.SCM.Git.sparse_opts/1
    (mix) lib/mix/scm/git.ex:31: Mix.SCM.Git.accepts_options/2
    (elixir) lib/enum.ex:2803: Enum.do_find/3
    (hex) lib/mix/hex/build.ex:117: Mix.Hex.Build.package_dep?/1
    (elixir) lib/enum.ex:1623: anonymous fn/3 in Enum.split_with/2
    (elixir) lib/enum.ex:1755: Enum."-split_with/2-lists^foldl/2-0-"/3
```

Here is a [sample mix.exs](https://github.com/urbint/rox/blob/4d56cb9ad71dd8ebd61a63daac133ba69f2fb445/mix.exs) that will trigger this error. Specifically the `rustler` dependency configuration.

### Expected behavior

According to @ericmj an error message should be provided warning the user that projects with non hex-based dependencies are not allowed to be published onto hex.

### Environment
```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
```

```
MacOS 10.12.3
```

**Comment by ericmj** [comment]
Can you open on https://github.com/hexpm/hex instead? Sorry for not being clear earlier.

**Comment by josevalim** [comment]
Closing this as it is a hex issue.
