### ISSUE TITLE
Remove to_microsecond conversion in Time and NaiveDatetime

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5920]
The implementation of `Time.diff`, `NaiveDateTime.add` and `NaiveDateTime.diff` are more complex and expensive than they need to be because they perform multiple conversions. For example, `to_microsecond` in NaiveDateTime converts between calendars, which in itself converts into days and seconds, then build another NaiveDateTime in ISO and then convert the ISO datetime back into days and seconds.

Those functions should rather convert to rata_die and day fraction and work on day fraction instead, similar to how DateTime.diff is implemented but without the offsets.

Since it is likely DateTime and NaiveDateTime will share functionality, we can move it to a private function in `Calendar.ISO` (as we are effectively computing the ISO difference).

/cc @Qqwy

**Comment by Qqwy** [comment]
Yes, `NaiveDateTime.diff`, `NaiveDateTime.add` and `Time.diff` should follow the implementation structure that `DateTime.diff` has. And indeed, the conversion of `days-> seconds` is shared between NaiveDateTime and DateTime, with the conversion of `hours/minutes/seconds -> microseconds` being shared by all three. 

With 'a private function in `Calendar.ISO`', do you mean 'a public fuction with `@doc false`'?

**Comment by josevalim** [comment]
> With 'a private function in Calendar.ISO', do you mean 'a public fuction with @doc false'?

Yes. :D
