### ISSUE TITLE
Error from mistyping "receive" is inconsistent and misleading between running in iex and compiling

### ISSUE THREAD

**Issue by brianpscoggins** [elixir-lang/elixir#5924]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.4.1, Erlang/OTP 19
* Operating system: Ubuntu 16.04.2 LTS - xenial

### Current behavior
given a function that uses `receive`, if the 'i' and 'e' are transposed, the compiler error and iex errors don't match:
for a code snippet in a module or run in iex
`recieve do
  {:hello, msg} -> msg
end`

iex returns
`** (CompileError) iex:1: undefined function recieve/1`

but the compiler returns
`** (CompileError) lib/myModule.ex:77: unhandled operator ->
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3`
where line 77 is `{:hello, msg} -> msg`

### Expected behavior
The compiler should report `undefined function recieve/1` in both cases.

**Comment by whatyouhide** [comment]
I cannot reproduce this on mater.

```elixir
iex(1)> recieve do {:hello, msg} -> msg end
** (CompileError) iex:1: undefined function recieve/1
```

and `elixirc ~/tmp/recieve.ex` with `recieve.ex` containing:

```elixir
recieve do {:hello, msg} -> msg end
```

How are you reproducing this?

**Comment by brianpscoggins** [comment]
[typo.tar.gz](https://github.com/elixir-lang/elixir/files/868249/typo.tar.gz)
In the attached, find typo.ex in lib/.
Attempt to compile using iex -S mix
Attempt to run the one line in iex
Compare error messages.
That's *all* I'm doing.

The error I get from iex -S mix is
`== Compilation error on file lib/typo.ex ==
** (CompileError) lib/typo.ex:3: unhandled operator ->
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3`

Whereas when I start iex and copy/paste, line-by-line, I get
`** (CompileError) iex:1: undefined function recieve/1`

The fact that one suggests there's something wrong with `->` and the other points out that I spelled "receive" wrong is the bug.

**Comment by josevalim** [comment]
When the code is defined inside a module, we assume that `recieve(...)` is going to call a local function and then we proceed to expand its arguments, failing when we see a `->`. It doesn't happen in IEx because we not inside a module. But if you copy the contents of the whole file and paste in IEx, you will see the same result.

It is not a bug, that how calling local function inside modules work.
