### ISSUE TITLE
NaiveDateTime.add loses calendar information

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#5938]
`NaiveDateTime.add` is still directly using `:calendar.datetime_to_gregorian_seconds` and losing the calendar field in the process.

We need to decide if the number of seconds given to `NaiveDateTime.add` is in the ISO unit or in the calendar seconds unit and implement the operation according to the calendar API.

Continuation of #5920.

/cc @Qqwy

**Comment by josevalim** [comment]
I would also like to point out that `add` and `diff` are not primitives because we would be able to implement them if we exposed the `to_rata_die`/`from_rata_die` functions or more trivially if we provided `to_gregorian_seconds` and `from_gregorian_seconds`. The `Calendar.ISO.rata_die_to_unit` is literally the `to_gregorian_seconds` implementation. See this commit on how we can simplify and optimize implementations by working on that: ddd92110a5eb2475e6c3ba423cf767fdf9e7bc1c

**Comment by josevalim** [comment]
Here is my suggestion. Let's add `Date.to_gregorian(unit \\ :days)` as well as `Time|NaiveDateTime|DateTime.to_gregorian(unit \\ :seconds)`, where `unit` can be also be any of the system units in the second case.

Then we document the `add` and `diff` implementations work on gregorian seconds according to the functions we have defined.

What do you think?

**Comment by josevalim** [comment]
We should consider adding `from_gregorian` and possibly

**Comment by michalmuskala** [comment]
Wouldn't using Unix epoch as the standard instead of gregorian days/seconds be more practical? I'm not sure I understand sticking to gregorian values in the general interface - those aren't particularly useful.

**Comment by josevalim** [comment]
@michalmuskala theoretically the reference point doesn't matter, going from one point to the other is just an addition / subtraction away. However, the issue with UNIX epoch is that UNIX time does not include leap seconds and they are always in UTC. This can be the source of confusion, as we would need to clarify it is the UNIX epoch over the ISO Calendar and that's why the UNIX epoch is generally avoided.

For example, @lau is strongly against adding `to_unix` and `from_unix` to NaiveDateTime for those reasons.

**Comment by michalmuskala** [comment]
What timezone is the gregorian epoch in? Isn't that exactly the same problem just shifted by 1970 years?

**Comment by lau** [comment]
> What timezone is the gregorian epoch in?

None.

> Isn't that exactly the same problem just shifted by 1970 years?

No, that's at least one important difference: UNIX epoch is in UTC, the gregorian isn't.
