### ISSUE TITLE
[SEO] Finding function signatures on the Typespec page

### ISSUE THREAD

**Issue by JeremyBellows** [elixir-lang/elixir#5940]
## Issue
Searching on google for `typespec function signatures` did not return https://hexdocs.pm/elixir/typespecs.html#types-and-their-syntax in the first page of results for me.  http://elixir-lang.org/getting-started/typespecs-and-behaviours.html was the top ranking but it did not answer how to express function signatures as types. Googling for `elixir function signatures as types` also returns the getting started page.

## Proposed Fix
Adding a paragraph explaining how to express function signatures as types should rank hexdocs for these keywords.

File to edit https://github.com/elixir-lang/elixir/blob/d3f1fff8a9d00ab98e8f48ff02493831ff475d61/lib/elixir/pages/Typespecs.md

**Comment by josevalim** [comment]
Thank you @JeremyBellows. The problem in this case is that this is not a function signature. It is just a function type and I am not sure if we should introduce an individual section for that. Does it mean an individual section for every literal people may Google? I am not quite comfortable with that.

**Comment by ericmj** [comment]
If I add "elixir" or "hexdocs" to your example query it does show up on the first page.

**Comment by JeremyBellows** [comment]
@ericmj Are you logged into an account? Search results are tailored based on previous searches and browsing history.

@josevalim We'll have to write useful banter in order to rank pages for phrases and keywords. The function type defines the input and output of a function. Could you elaborate on why this isn't a function signature? What would be a better way of describing this?

**Comment by josevalim** [comment]
It is a function type. A signature is a spec definition.

And I am very against adding banter to the docs for SEO purposes. I know it
is not only banter, but we should judge the change based on the developers
reading it rather than SEO.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by JeremyBellows** [comment]
What is a good measurable approach  we could use to judge the change based on developers reading it? SEO is a utility for communicating with targeted groups.

Specs are excellent for specifying the function signature of an implementation but doesn't solve the need for expressing a function signature as a type. This is useful when needing to express a signature as a input parameter or output type. The other synonym for this is type signature. Could you elaborate on your reasons for not wanting to include this? What are some other solutions to the proposed problem?

**Comment by josevalim** [comment]
> Specs are excellent for specifying the function signature of an implementation but doesn't solve the need for expressing a function signature as a type. This is useful when needing to express a signature as an input parameter or output type.

I am nitpicking but, because this is an addition to the documentation, I want to clarify that we do not call what you defined in the PR as a function signature.

```elixir
# A type signature "foo" with a function type
@type foo :: (integer -> integer) 

# A specification for a function that returns a function type
@spec bar(integer) :: (integer -> integer)

# This is the signature + implementation
def bar(integer) do
  ...
end
```

>  What are some other solutions to the proposed problem?

We don't need to solve all problems. If this is not improving the documentation, then I wouldn't add it only for SEO reasons. So we need to know: is this the current documentation for function types not clear? If they are not, then we fix it, if they are, then we leave it as is.

**Comment by JeremyBellows** [comment]
> I am nitpicking but, because this is an addition to the documentation, I want to clarify that we do not call what you defined in the PR as a function signature.

Who is 'we' in the scenario provided? What are the reasons that the group associated with 'we' does not call this a function signature?

This improves the documentation by increasing accessibility through language and content elaboration. Current documentation provides helpful information but it does not describe the content it is providing. Elaborating on type (or function) signatures helps with the overall user experience by communicating with users who may have the same issue.

This helps programmers who are learning elixir and have a typed functional programming background.

**Comment by josevalim** [comment]
> Who is 'we' in the scenario provided? What are the reasons that the group associated with 'we' does not define this as a function signature?

We: the Elixir Core Team and the Elixir documentation. It is also consistent with the definition of signature in wikipedia and other languages: https://en.wikipedia.org/wiki/Type_signature

**Comment by JeremyBellows** [comment]
>We: the Elixir Core Team and the Elixir documentation.
What are the reasons for excluding function signature as a definition?

Located in the [Signature](https://en.wikipedia.org/wiki/Type_signature#Signature) section of the Type Signatures wikipedia page is the following text
> A function signature consists of the function prototype.

**Comment by josevalim** [comment]
Yes, and in Elixir the prototype is done like this:

```
def add(left, right) # prototype!

def add(left, right) do
  left + right
end
```

this also aligns with the function signature examples from other languages.

Can you please describe what you expect to be the function signature?

**Comment by JeremyBellows** [comment]
```
some_input -> some_output
```

https://fsharpforfunandprofit.com/posts/function-signatures/

**Comment by josevalim** [comment]
OK, then our definitions diverge. The divergence likely comes that typespecs in Elixir are annotations. In Elixir you can have function signatures without using types at all as shown above.

**Comment by JeremyBellows** [comment]
>OK, then our definitions diverge. The divergence likely comes that typespecs in Elixir are annotations. In Elixir you can have function signatures without using types at all as shown above.

Can you elaborate on this? I want to understand why function signature is not an appropriate definition for expressing a function literal as a type.

**Comment by josevalim** [comment]
@JeremyBellows for two reasons:

Elixir does not provide currying, so you can't rewrite this:

```
@spec bar(integer()) :: integer()
```

as this:

```
@type int_to_int :: (integer() -> integer())
@spec bar :: int_to_int()
```

So a function literal as a type can never be used as a function signature, so I would avoid treating them as synonyms.

And the second reason is because function signature in Elixir means *something else* as per the discussion above.

**Comment by josevalim** [comment]
```
# A type that describes a function type
@type some_function_signature :: (integer -> integer)
# A spec for get_some_function that *returns* the given type
@spec get_some_function(integer) :: some_function_signature
```

The reason why I wouldn't call the type "some_function_signature" is because it is not really the function signature as it can only describe the return type. In F# I can write something like this:

```
type Negate :: int -> int
negate : Negate = (-)
```

but it is not possible to use this pattern in Elixir. If I try to write it like this:

```
@type negate :: (integer() -> integer())
@spec negate :: negate()
def negate(number), do: -number
```

It won't compile because you are spec'ing `negate/0` and not `negate/1`. If you write it like this:

```
@type negate :: (integer() -> integer())
@spec negate(integer) :: negate()
def negate(number), do: -number
```

then you are saying it returns a function and not a number (which is wrong).

**Comment by josevalim** [comment]
I will go ahead and close this issue since the term you were looking for in the typespec page does not apply to Elixir. It is like someone from Rust looking for borrowing in Elixir, they won't find anything, because the concept does not apply.
