### ISSUE TITLE
Suggestion: improve the error message for "no process"

### ISSUE THREAD

**Issue by Trevoke** [elixir-lang/elixir#5953]
The error message in question is [this one](https://github.com/elixir-lang/elixir/blob/dca3df0c031918d822e6f59a8b43bc84fd642239/lib/elixir/lib/exception.ex#L243)

```elixir
  defp format_exit_reason(:noproc) do
    "no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started"
  end
```

This error message took me on [quite a ride](https://elixirforum.com/t/exit-no-process-the-process-is-not-alive-or-theres-no-process-currently-associated-with-the-given-name-possibly-because-its-application-isnt-started/4368/7).

The fault ultimately of course lied with me, but I spent a very long time looking for applications that hadn't started, when in fact the problem was that the test ended and the test framework reaped the processes too fast, so my async call tried to call a process  that didn't exist anymore.

I'm not sure what restrictions / guidelines there are around these error messages, which is why I'm not just starting with a PR, but I would suggest modifying the latter part of the string, maybe adding that the process may have also died before execution reached this point.

**Comment by josevalim** [comment]
I am not sure what we should change. The part you described is already covered in the error message: "the process is not alive". It means either the process didn't start or it started and it is already dead.

**Comment by Trevoke** [comment]
The suggestion afterwards led me down a rabbit hole  and blinded me to the
latter possibility. Maybe, then, we remove the second bit and leave it at
just "the process doesn't exist"?

**Comment by josevalim** [comment]
We have already accounted to that because we say "possibly because its application isn't started". We never declare it as the root cause and I think removing it would do more harm than good.

**Comment by Trevoke** [comment]
I understand that from a strictly logical perspective the sentence is
perfectly accountable to all of its meanings, but it has a psychological
effect.

None of the people whom I asked for help even considered that maybe the
process was already dead.

**Comment by josevalim** [comment]
@Trevoke the second suggestion there mentions this:

> Check the result of GenServer.whereis/1 just before calling the process

This is exactly how you will find if the process is dead or not.

In any case, we will keep watching if folks are confused by this error message. Previously we had many reports about  no process errors and the suggestion definitely helped. So we need to balance this out and this is the first time we hear about the message being misleading.

Thank you!
