### ISSUE TITLE
Apply EEx bindings partially (feature)

### ISSUE THREAD

**Issue by toraritte** [elixir-lang/elixir#5959]
Probably not a feature that would be of high demand but it can come in handy (unless there is already something like this that I don't know about).
https://github.com/toraritte/elixir/commit/21c4c9f4a326cd6e6b141dd795848d7039b6c294

An example:
``` elixir
s = "<%=   a %>, <%= b %> and another <%= c %>"
EEx.partial_eval_string(s)
#> "<%=   a %>, <%= b %> and another <%= c %>"
EEx.partial_eval_string s,[b: "pie", c: "one"]
#> "<%=   a %>, pie and another one"
```

It would be pretty easy to incorporate it to the `eval_*`s and `function_from_*`s. On the other hand, it is just as easy to write a wrapper around them in the current project but who knows.

Thanks  a bunch!

**Comment by josevalim** [comment]
Please send feature requests to the core mailing list and argue for its
needs.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
