### ISSUE TITLE
`mix new --umbrella` generates hard-coded apps_path in config.exs

### ISSUE THREAD

**Issue by jsnathan** [elixir-lang/elixir#5961]
**Version**: master

**Current behavior**: Configuration of nested applications in umbrella projects is _silently ignored_ if a custom apps_path is used in mix.exs.

**Expected behavior**: Configuration should be loaded by default.

**Steps to reproduce**:

```bash
mix new --umbrella umbrella

cd umbrella/apps

mix new nested
echo 'IO.puts "hello from nested"' >> nested/config/config.exs

cd ..

sed -i 's/"apps"/"custom_apps_path"/' mix.exs
mv apps custom_apps_path

mix run
```

Should output "hello from nested" but does not.

```bash
sed -i 's$/apps/$/custom_apps_path/$' config/config.exs

mix run
```

Now outputs "hello from nested".

**Explanation**:

The template used by `mix new --umbrella` generates the following code in the top-level config/config.exs

```elixir
import_config "../apps/*/config/config.exs"
```

The code which does this is found in elixir/lib/mix/lib/mix/tasks/new.ex ([line 387](https://github.com/elixir-lang/elixir/blob/3c8bdfcc2cb842913c53e937959f05b969527cc3/lib/mix/lib/mix/tasks/new.ex#L387))

Because the apps_path is configurable in mix.exs and so not always `apps`, this should instead use `Mix.Project.config[:apps_path]`.

**Comment by josevalim** [comment]
As you change mix.exs, you should change the config/config.exs file accordingly. I would prefer to keep the config/config.exs straight-forward then try to make it work with all possible scenarios. In your case, I would even prefer listing each app explicitly.

Thank you for the report anyway!
