### ISSUE TITLE
Failure in linked process during ExUnit `setup_all` doesn't change process exit code.

### ISSUE THREAD

**Issue by benkirzhner** [elixir-lang/elixir#5967]
### Current Behavior

For some reason, ex_unit exits with an zero exit code if the only failure during a test run is a linked process dying within a `setup_all` block. When running the following test script, the output includes a failure, but elixir exits with an exit code of zero.

```elixir
ExUnit.start

defmodule ExampleTestCase do
  use ExUnit.Case

  setup_all do
    {:ok, task} = Task.start_link(fn -> raise "boom" end)
    Task.await(task)

    :ok 
  end 

  test "the truth" do
    assert 1 == 1
  end 
end
```
That script produces the following output:
```
→ elixir exunit_bug_example.exs; echo $?  


  1) ExampleTestCase: failure on setup_all callback, test invalidated
     ** (EXIT from #PID<0.65.0>) an exception was raised:
         ** (RuntimeError) boom
             exunit_bug_example.exs:7: anonymous fn/0 in ExampleTestCase.__ex_unit_setup_all_0/1
             (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
             (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3



Finished in 0.04 seconds (0.04s on load, 0.00s on tests)
1 failure

15:47:33.209 [error] Task #PID<0.66.0> started from #PID<0.65.0> terminating
** (RuntimeError) boom
    exunit_bug_example.exs:7: anonymous fn/0 in ExampleTestCase.__ex_unit_setup_all_0/1
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Function: #Function<0.87956765/0 in ExampleTestCase.__ex_unit_setup_all_0/1>
    Args: []

Randomized with seed 191520
0
```

Interestingly, if I replace the `setup_all` with a `setup` block with the same body, the script fails with a non-zero exit code.

### Expected Behavior

For any test run in which there are one or more failures, I'd expect a non-zero exit code.

### Environment
* Operating system: macOS Sierra 10.12.3
* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.0
```

Let me know if there's any other information you need!

**Comment by Zanadar** [comment]
I have a sense of why this is happening and was going to take a crack at address, if nobody else is working on this bug.

**Comment by whatyouhide** [comment]
@Zanadar please feel free to go ahead! 💟

**Comment by eksperimental** [comment]
Should this issue be closed as it has already been addressed by https://github.com/elixir-lang/elixir/issues/6061
