### ISSUE TITLE
"View Source" links in Elixir documentation (1.4.*) on hexdocs.pm are pointing to wrong github destination

### ISSUE THREAD

**Issue by robi-wan** [elixir-lang/elixir#5985]
### Current behavior

When visiting the Elixir documentation on hexdocs.pm I clicked the "View Source" link to view the implementation of that function. But the destination was not quite right - it was off some lines.
Examples:
https://hexdocs.pm/elixir/1.4.2/Kernel.html#!=/2
"View Source" points to https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L1177

https://hexdocs.pm/elixir/1.4.1/Kernel.html#!=/2
"View Source" points to https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L1177

https://hexdocs.pm/elixir/1.4.0/Kernel.html#!=/2
"View Source" points to https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/kernel.ex#L1177

(I checked it for Elixir 1.4.* releases - Elixir 1.3.* seems to have correct links.)

### Expected behavior
"View Source" points to the correct source code destination (the correct git tag).

(I guess the documentation was not generated from the appropriate git tags.)

I apologize in advance if this is the wrong place to report this kind of issue.

**Comment by josevalim** [comment]
Thank you. This has been fixed one exDoc iirc.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ericmj** [comment]
@josevalim Is the fix released? I just built the docs and we still have the issue.

**Comment by ericmj** [comment]
@josevalim We also need to make sure that we push the new tags when making new ex_doc releases or Bob will not be able to pick them up.

**Comment by robi-wan** [comment]
The mentioned fix in ex_doc is probably https://github.com/elixir-lang/ex_doc/commit/2228073feabda52136aed345208c8af8ea74b596 from March 3, 2017.
[Latest ex_doc release on hex.pm](https://hex.pm/packages/ex_doc) is 0.15.0 from February 20, 2017.

I locally build the Elixir documentation with the current master of ex_doc - this worked (--source-ref is kept).

**Comment by josevalim** [comment]
@ericmj I thought bob used master?

**Comment by ericmj** [comment]
It only uses ex_doc master for elixir master because older elixir versions have trouble with ex_doc master.

**Comment by josevalim** [comment]
v0.15.1 is out, thanks everyone.
