### ISSUE TITLE
Module names seemingly "mashed" together

### ISSUE THREAD

**Issue by lukerollans** [elixir-lang/elixir#5989]
### Environment

* Elixir & Erlang versions (elixir --version):
```
admin feature/admin-catering-category-crud % elixir --version
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
```

* Operating system: macOS Sierra 10.12.3

### Current behavior

I'm experiencing an intermittent issue where in some tests. the compiler seems to be mashing together two different module names, such as `Plug.Exception.Ecto.NoResultsError`, which obviously doesn't exist.

The application I'm working on is an umbrella, which makes me think it may be _slightly_ related to #5987.

Here's an example

#### Error
```
 10) test Lunchbox.Admin.IngredientController.show/2 raisesan Ecto.NoResultsError (404) when ingredient does not exist(Lunchbox.Admin.IngredientControllerTest)
     test/controllers/ingredient_controller_test.exs:76
     Expected exception Ecto.NoResultsError but got UndefinedFunctionError (function Plug.Exception.Ecto.NoResultsError.status/1 is undefined (module Plug.Exception.Ecto.NoResultsError is not available))
     stacktrace:
       Plug.Exception.Ecto.NoResultsError.status(%Ecto.NoResultsError{message: "expected at least one result but got none in query:\n\nfrom i in Lunchbox.Ingredient,\n  where: i.id == ^\"-1\"\n"})
       (phoenix) lib/phoenix/endpoint/render_errors.ex:71: Phoenix.Endpoint.RenderErrors.render/5
       (phoenix) lib/phoenix/endpoint/render_errors.ex:58: Phoenix.Endpoint.RenderErrors.__catch__/5
       (phoenix) lib/phoenix/test/conn_test.ex:224: Phoenix.ConnTest.dispatch/5
       test/controllers/ingredient_controller_test.exs:77: (test)
```

#### The test
```
test "raises an Ecto.NoResultsError (404) when ingredient does not exist", %{conn: conn} do
  assert_raise Ecto.NoResultsError, fn ->
    get(conn, ingredient_path(conn, :show, -1))
  end
end
```

This example is obviously a Phoenix controller, so let me know if I should head on over to the Phoenix repo. I have indeed seen this happen within other, non-Phoenix apps in this umbrella, this is just the latest occurrence.

#### Solution
To fix this issue, wiping out the `_build` directory and recompiling temporarily fixes the issue. But it will occur again eventually, normally about once a day.

### Expected behavior
Module names should not be mixed together in this fashion.

**Comment by michalmuskala** [comment]
This is the same issue as #5987 - protocol implementations are modules where the name of the module is the name of the protocol & data structure concatenated.

**Comment by lukerollans** [comment]
OK, fantastic, will close to prevent duplicates. Thanks for the response!
