### ISSUE TITLE
Enum.take returning text instead of list with results expected

### ISSUE THREAD

**Issue by raphaelcuba** [elixir-lang/elixir#5994]
### Environment

* Elixir & Erlang versions:  Erlang/OTP 19 [erts-8.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] & Elixir 1.4.2

* Operating system: Docker using debian in macOS 10.12.4. [Link image](https://hub.docker.com/_/elixir/).

### Current behavior

I've started studying Elixir right now and `Enum.take` returning text instead of list with results expected.

```elixir
# I don't know if this first case should be expected.
Enum.take(10..100, 1)
'\n'
Enum.take(10..100, 2)
'\n\v'
Enum.take(10..100, 3)
'\n\v\f'
Enum.take(10..100, 4)
'\n\v\f\r'
Enum.take(10..100, 5)
[10, 11, 12, 13, 14]
```

### Expected behavior
```elixir
# I don't know if this first case should be expected.
Enum.take(10..100, 1)
[10]
Enum.take(10..100, 2)
[10, 11]
Enum.take(10..100, 3)
[10, 11, 12]
Enum.take(10..100, 4)
[10, 11, 12, 13]
```

**Comment by eksperimental** [comment]
It's a feature, not a bug
https://github.com/elixir-lang/elixir/wiki/FAQ#4-why-is-my-list-of-integers-printed-as-a-string

**Comment by raphaelcuba** [comment]
Wow, sorry and thanks by explanation @eksperimental!
