### ISSUE TITLE
Plug.Session, store :cookie // put_session error: bad argument

### ISSUE THREAD

**Issue by ignaci0** [elixir-lang/elixir#5999]
### Environment

```
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.0
```

### Current behavior

I've been trying to use Plug.Session.COOKIE (https://hexdocs.pm/plug/Plug.Session.COOKIE.html#content) and whenever I tried to use Plug.conn's put_session got "bad argument" error.

This error was caused by a `:ets.lookup(cache ...)`.

Apparently, the put_session (actually it seems to be the Plug.Crypto.KeyGenerator) is somehow using a cache table called `Elixir.Plug.Keys`. I don't seem to find any documentation on sessions using such functionality. Moreover, the cache doesn't seem to be configurable for the session only.

To workaround the issue and to be able to use the session store, I had to call:

```:ets.new(Elixir.Plug.Keys, [:named_table, :public, read_concurrency: true])```

Before my supervisor is started.

### Expected behavior

I expect the Plug.Session to have an option to pass the cache name to the `Plug.Crypto.KeyGenerator` or to disable it.

Maybe something like:
```
Plug.Session, store: :cookie,
                       ...
                       cache: term() | false,
                       ....
```

**Comment by josevalim** [comment]
If you have an `:applications` list in your mix.exs, you need to add `:plug` to the list of applications, so all services provided by Plug are started.
