### ISSUE TITLE
r/1 destroying anonymous functions

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#6003]
### Environment
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2

Linux

### Current behavior

r/1 destroys anonymous functions. Giving  
** (BadFunctionError) expected a function, got: #Function<2.5551862/1 in Test>  
When the anonymous function that was declared in that specific module that we call r/1 on is called again.
  
Using recompile/0 does not exhibit this same behavior.
  
### Expected behavior

The expected behavior is to not get a BadFunctionError in this case.  

```elixir
defmodule Test do
    def tt(), do: :ttt
    def t() do
        anon = fn() ->
            IO.puts "hi"
        end
        :erlang.spawn(fn()->
            Enum.each(:lists.seq(1,10000), fn(_)->
                anon.()
                Process.sleep(2000)
            end)
			
        end)
    end
end
```

Now change :ttt to :tttt and call r(Test). Watch it crash the next time anon.() gets called.

Try again but use recompile/0 this time, no crash.

**Comment by josevalim** [comment]
Both fail. The VM can keep only two versions of a single module, so if you either `recompile/0` twice or call `r/1` twice, the old version of the module will be purged.

**Comment by vans163** [comment]
It seems same behavior in Erlang (now that iv tried changing code twice + recompiling twice), except in Erlang its even worse, the process just dies with no errors.

I wonder if this is intentional or if there's a way to solve this.

**Comment by josevalim** [comment]
This is by design. The VM only keeps two versions of a given module name. Once you recompile twice, the original version is purged and any code that relies on any local function stops working.

**Comment by vans163** [comment]
I am not liking that behavior, its not very fault tolerant or reliable, and makes using anon functions in the code base dangerous.  I am going to see if I can get some better answers as to why it behaves like that  and if there is a way to 'fix' it.

**Comment by josevalim** [comment]
@vans163 It behaves like that because it is exactly how code reloading in the VM works. I am trying to understand why do you think this is a problem. When you are code reloading software in production, you are not calling functions like `r` or `recompile`. There is an actual process where code reload goes through.

Any code that you write, regardless if it uses anonymous functions or not, needs to have an upgrade path for code reloading. Otherwise the code fails even if no anonymous function is involved at all, for example, if you rename a private function from name `a` to name `b`.

**Comment by vans163** [comment]
Its a problem because say you pass an anonymous function to a gen_server that is being held for a long time in that gen_servers state.  Or you have a very long running loop using R17 syntax (fun Loop()-> Loop() end)().

In both cases if the code is running a long time and you are hotloading, eventually youl have problems.

The upgrade path is fine, we can deal with most things.  But if we passed a anon function already somewhere, it becomes really complex to reinitialize that anon function after a hotload,  or in the case if our entire process loop is an anon function.

Iv never had a problem (that could not have been fixed) with Erlang's hotloading before.  I am stumped here though.

**Comment by josevalim** [comment]
Yes, then you cannot use anonymous functions in this case. You need to pass
them as &Foo.bar/3 or keep them as tuples {Mod, fun, [arg1, arg2, ...]}.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by vans163** [comment]
The problem with the approach of &Foo.bar/3 is you lost the outer scope, and need to pass contexts around as well.  

The tuple approach is actually interesting, I was not aware of that, it seems you cannot call the tuple anymore, but with a small pattern match you can turn {Mod, :mod_fun, [arg1, arg2, ...]} into something apply/2|3 can understand, unless I missed the way to correctly use the tuple function approach.

And so unfortunate that anonymous functions cannot be used in that case.  Keeping any anonymous function around that still has a process holding a ref to it seems pretty reasonable to me.  I am not sure on the full implications of doing that, but keeping the version of the module with that anonymous function around seems required.  Then if that old module (with the anon function) calls a function in itself (from the anon function), can it go to the new module? Etc.
