### ISSUE TITLE
Error when Node.spawn_link function

### ISSUE THREAD

**Issue by GianFF** [elixir-lang/elixir#6013]
I'm trying to do [this](http://elixir-lang.org/getting-started/mix-otp/distributed-tasks-and-configuration.html#distributed-tasks) guide of elixir distributed tasks but I am running in troubles with this exception:

```
** (EXIT from #PID<0.62.0>) an exception was raised:
    ** (BadFunctionError) expected a function, got: #Function<20.50752066/0 in :erl_eval.expr/5>
        :erlang.apply/2

[error] Error in process #PID<8796.100.0> on node :"silver@192.168.0.25" with exit value:
{{:badfun, #Function<20.50752066/0 in :erl_eval.expr/5>},
 [{:erlang, :apply, 2, []}]}
```

I start `machine one` with: `iex --name gold@192.168.0.20 --cookie foo` and run:

```
iex(silver@192.168.0.25)1> defmodule Hello do
iex(silver@192.168.0.25)1>   def world, do: IO.puts "hello world"
iex(silver@192.168.0.25)1> end
```

Then start `machine two` with: `iex --name silver@192.168.0.25 --cookie foo`. And try to spawn Hello.world function:

`Node.spawn_link :"silver@192.168.0.25", fn -> Hello.world end`

After this, the error is displayed.

MORE INFO:

On `machine one` `Node.list` returns [:"silver@192.168.0.25"]

On` machine two` `Node.list` returns [:"gold@192.168.0.20"]

`epmd -names` on `machine one` returns:

```
epmd: up and running on port 4369 with data:
name gold at port 37295
```

`epmd -names` on `machine two` returns:

```
epmd: up and running on port 4369 with data:
name gold at port 39738


```

**Comment by josevalim** [comment]
@GianFF you need to guarantee they are running exactly the same Erlang version. For production, we typically compile our code in a single machine and distribute it across, to guarantee the same version everywhere.

If you cannot guarantee the same version, then you must avoid anonymous function and always used named versions, such as:

    Node.spawn_link :"silver@192.168.0.25", &Hello.world/0
    Node.spawn_link :"silver@192.168.0.25", Hello, :world, []

**Comment by GianFF** [comment]
@josevalim thanks you very much! I will try with this changes... but what about to add this on the docs that I mentioned? (http://elixir-lang.org/getting-started/mix-otp/distributed-tasks-and-configuration.html#distributed-tasks)

**Comment by fishcakez** [comment]
Should we improve the error message when value is a fun?
