### ISSUE TITLE
Elixir crash when pasting ascii curly quotes from os x

### ISSUE THREAD

**Issue by twinfire** [elixir-lang/elixir#6020]
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:8:8] [async-threads:10] [kernel-poll:false] [dtrace]
Elixir 1.3.4
OS X 10.12.4

I am experiencing an Elixir crash ([End]) when pasting curly double quoted text from the 'Notes' app on my MacBook into an ssh window that is attached to a remote iex process.  I have looked into this a bit and it appears that the Notes app sends ascii 147 and 148 for the left and right curly double quotes.  I have found that I can go into the System preferences and turn off "smart quotes and dashes" and the straight double quote ascii 34 is used instead and the paste works fine.  For some reason, when I paste the 147/148 chars into my remote iex window, the iex process crashes.

**Comment by josevalim** [comment]
Can you please paste an example of such string here? Thank you.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by twinfire** [comment]
Here is a string that causes the crash - “Foo”
and here is one that doesn't = "Foo"

**Comment by ericmj** [comment]
I can you reproduce it in a normal iex session or is it only when using a remote console? Also, does it only happen when you ssh? Try to provide as many details as possible to make it easier for us to reproduce your scenario.

**Comment by twinfire** [comment]
The only way I can seem to make it happen is when I have ssh'd into a remote machine and attached to iex using the exrm generated bin/<projectname> attach.  When I start up iex on the remote machine that I am ssh'd into, the paste doesn't crash it.

**Comment by twinfire** [comment]
Also, I am unable to reproduce it on a locally running iex session.

**Comment by OvermindDL1** [comment]
Just as another data point, `“Foo”` does not crash in iex on Windows 10, so unable to reproduce it here either.

If your system is replacing `"` with binary of 147/148 that sounds horribly buggy as that is *not* valid unicode...

**Comment by OvermindDL1** [comment]
Do note, putting `“Foo”` into a string via `"“Foo”"` just returns an empty string, which is odd, but expected if it is not valid unicode maybe (though I'd expect an error).

```elixir
iex> s = """
...> “Foo”
"""
""
iex> s
""
```

**Comment by josevalim** [comment]
@OvermindDL1 it works fine here. It seems the issue is either the terminal is sending corrupted data or not sending the data at all and in both cases there isn't much we can do.

**Comment by josevalim** [comment]
I was able to reproduce the issue by programmatically starting iex and sending corrupted bytes. It seems only IEx crashes but the connected node is still running, so I would say it is behaving as expected. Maybe there is some ssh configuration that could be set in those cases, since other users have reported no issues even through ssl.

Thank you.
