### ISSUE TITLE
Warnings as errors not picking up warnings in mix files

### ISSUE THREAD

**Issue by TBK145** [elixir-lang/elixir#6021]
### Environment

* Elixir & Erlang versions (elixir --version): 1.4.2, 19.3
* Operating system: Ubuntu 16.04

### Current behavior

When compiling a project with the --warnings-as-errors parameter, the compilation doesn't fail on errors in the mix file.
To recreate, try compiling a project with a mix file that calls `deps` without `()`.

### Expected behavior

Compilation should fail on any error in the project when given --warnings-as-errors.

**Comment by josevalim** [comment]
Thank you for the report in any case!
