### ISSUE TITLE
Document the default argument operator (\\)

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#6024]
As far as I can tell, `\\` is only "documented" [in the Getting Started guide](http://elixir-lang.org/getting-started/modules-and-functions.html#default-arguments
), and mentioned as a possible operator in the "Operators" page, but is not properly documented anywhere. If I'm correct, we should document it in `Kernel.def/2` and mention it (referencing `def`) in all the things that support it (`def`, `defp`, `defmacro`, `defmacrop`, `defdelegate`).

**Comment by josevalim** [comment]
Agreed.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by kevinlitchfield** [comment]
May I try my hand at this, @whatyouhide? (I noticed the labels you added, but just wanted to confirm.)

**Comment by whatyouhide** [comment]
@kevinlitchfield sure! I added the label but then thought "oh maybe if I take the label out someone will do the work for me" 😄 Feel free to go ahead and ping me if you need any help :)

**Comment by kevinlitchfield** [comment]
@whatyouhide Hahaha, cool. 😄 Thanks, appreciate the offer of help and will let you know!

**Comment by kevinlitchfield** [comment]
@whatyouhide So, I do have a question for you if you have a minute. 

I'm not sure I understand the exact mechanics of what's going on with the generation of multiple functions when `\\` is used. In my current draft, commenting on [this example](http://elixir-lang.org/crash-course.html#default-values), I've written in part:

> The compiler translates this into multiple function clauses with different arities, here `Foo.mul_by/1` and `Foo.mul_by/2`.

Is that correct?

**Comment by whatyouhide** [comment]
Yes, multiple functions are generated. If you have `def foo(a, b \\ :b, c \\ :c), do: # impl`, then the compiler will generate something like

```elixir
def foo(a), do: foo(a, :b, :c)
def foo(a, b), do: foo(a, b, :c)
def foo(a, b, c), do: impl
```

so you'll effectively have `foo/1`, `foo/2`, and `foo/3`.

**Comment by kevinlitchfield** [comment]
@whatyouhide Thanks! Just wanted to make sure my phrasing wasn't misleading. Appreciate your response. Opening PR.
