### ISSUE TITLE
Document application inference

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#6025]
As far as I can tell the application inference is only documented in the 1.4 changelog - there's no mention of it in the Mix documentation or anywhere.

**Comment by whatyouhide** [comment]
Something is mentioned [here](https://github.com/elixir-lang/elixir/blob/24fb49305c1577842f74c1658431d90b71b23134/lib/mix/lib/mix/tasks/compile.app.ex#L47-L51), did you have something more in mind?

**Comment by michalmuskala** [comment]
That's the first time I see the documentation for this task. I'm not really sure it's discoverable. Maybe something in `Mix.Project`?

I only know that whenever somebody asks about how it all works now, the only place I could refer them too is the changelog. It seems wired to refer new users who never used Elixir before 1.4 to the changelog - nothing changed for them.

**Comment by josevalim** [comment]
The best place would be `mix compile.app` or maybe `Mix`. So if the documentation is not enough, please do send a PR. I don't think `Mix.Project` would be a good candidate, it is very specific to Mix internals.

**Comment by josevalim** [comment]
I will close this as the behaviour is documented. If someone has ideas for improvements, they are always welcome, but currently it is not clear what should be acted on. Thank you!
