### ISSUE TITLE
Document coding guidelines for variables and module names

### ISSUE THREAD

**Issue by vramiro** [elixir-lang/elixir#6026]
It should be clear at the documentation that variables names must be lowercase and module names must be uppercase. Now it seems to me like it is a simple good practice, but in fact you get a different behaviour at the name binding.

### Current behavior

iex(1)> x
warning: variable "x" does not exist and is being expanded to "x()", please use parentheses to remove the ambiguity or change the variable name
  iex:1

** (CompileError) iex:1: undefined function x/0

iex(1)> X
X
iex(2)>

### Environment

elixir --version
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2

**Comment by ericmj** [comment]
If you want to document this it should be done here under variables and aliases: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Syntax%20Reference.md
