### ISSUE TITLE
Performance problem reading from StringIO

### ISSUE THREAD

**Issue by balexand** [elixir-lang/elixir#6037]
### Environment

Mac OS 10.12.4 on an older Macbook Pro

```
> elixir --version
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
```

### Current behavior

Reading from a `StringIO` using `IO.read(pid, :line)` is extremely slow. In the benchmark below with 30,000 lines it takes 2,500 times longer to read from a `StringIO` than to read from a file.

### Expected behavior

I would expect reading from a `StringIO` to have similar performance to reading from a file. Furthermore, I would expect to read N lines in O(N) time.

### Benchmark

```elixir
defmodule Read do
  def with_timing(label, pid) do
    {micro_sec, :ok} = :timer.tc(fn -> until_eof(pid) end)
    IO.puts "#{label}: #{round(micro_sec / 1_000)}ms"
  end

  def until_eof(pid) do
    case IO.read(pid, :line) do
      :eof -> :ok
      line when is_binary(line) -> until_eof(pid)
    end
  end
end

num_lines = 30_000
IO.puts "Number of lines: #{num_lines}"

lots_of_lines =
  0..num_lines
  |> Enum.map(fn _ -> "abcdefghijklmnopqrstuvwxyz" end)
  |> Enum.join("\n")

{:ok, pid} = StringIO.open(lots_of_lines)

Read.with_timing("StringIO", pid)

# For comparison, read the same lines from file
path = "/tmp/lots_of_lines.txt"
File.write!(path, lots_of_lines, [:utf8])

file_pid = File.open!(path, [:read, :utf8])
Read.with_timing("File", file_pid)
```

### Results

```
➜ elixir perf.exs
Number of lines: 10000
StringIO: 56336ms
File: 94ms
➜ elixir perf.exs
Number of lines: 20000
StringIO: 291517ms
File: 172ms
➜ elixir perf.exs
Number of lines: 30000
StringIO: 616679ms
File: 247ms
```

**Comment by eksperimental** [comment]
You shouldnt be using is_binary/1. That may slow things down

**Comment by michalmuskala** [comment]
That's definitely not the problem - exactly the same code is executed for a file. 

Taking a quick look at `StringIO` it looks like there's couple `binary -> charlist -> binary` conversions happening during a single request. Without a deeper analysis, I would start investigating this as the primary source of the problematic overhead

**Comment by eksperimental** [comment]
@michalmuskala I never said it was, but we are just adding 30,000 is_binary/1 runs that are not being run on `File.read/1`

**Comment by balexand** [comment]
My sloppy benchmark seems to be distracting from the problem. Let me try to demonstrate using iex:

```elixir
iex(1)> {:ok, pid} = String.duplicate(String.duplicate("a", 30)<>"\n", 50_000) |> StringIO.open
{:ok, #PID<0.82.0>}
iex(2)> :timer.tc(IO, :read, [pid, :line])
{230405, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"}
iex(3)> :timer.tc(IO, :read, [pid, :line])
{119776, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"}
```

Rounding to the nearest order of magnitude, each read call took 100ms.

```elixir
iex(1)> {:ok, pid} = String.duplicate(String.duplicate("a", 30)<>"\n", 500_000) |> StringIO.open
{:ok, #PID<0.82.0>}
iex(2)> :timer.tc(IO, :read, [pid, :line])
{4224717, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"}
iex(3)> :timer.tc(IO, :read, [pid, :line])
{1190399, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"}
```

When 10X more lines are used, each read call now takes ~1,000ms.

```elixir
iex(1)> File.write!("/tmp/lots_of_lines.txt", String.duplicate(String.duplicate("a", 30)<>"\n", 5_000_000), [:utf8])  
:ok
iex(2)> pid = File.open!("/tmp/lots_of_lines.txt", [:read, :utf8])
#PID<0.84.0>
iex(3)> :timer.tc(IO, :read, [pid, :line])
{237, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"}
iex(4)> :timer.tc(IO, :read, [pid, :line])
{45, "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n"}
```

When reading from a file, a single read takes on the order of 100µs. This number is constant regardless of the number of lines.

**Comment by eksperimental** [comment]
@michalmuskala I didn't read from my cellphone that is_binary is being called for both cases. my bad. :-P

**Comment by balexand** [comment]
The offending O(N) operation is [`:unicode.characters_to_list(input, encoding) `](https://github.com/elixir-lang/elixir/blob/ddd962ca94d9099e41a7fea28cbe381d1667d478/lib/elixir/lib/string_io.ex#L268), which results in the entire input string being copied for each read. The same problem exists in [`get_until`](https://github.com/elixir-lang/elixir/blob/ddd962ca94d9099e41a7fea28cbe381d1667d478/lib/elixir/lib/string_io.ex#L301).

The approach that I'm working on is to have `collect_line` efficiently split out the line before decoding the characters. The challenge is that `collect_line` must now be aware of the encoding.

I'd like to start by adding test coverage. Is there a function that reads a line from an IO pid while passing the encoding (like `IO.read(pid, :line, encoding: :utf16`)? It appears that calls to `IO.read` always pass an encoding of `:unicode` (an alias for `:utf8`) and calls to `IO.binread` always pass `:latin1`. If we only need to support these 2 encodings then this should be straightforward.

**Comment by josevalim** [comment]
I believe the IO interface does not support passing the encoding like that.
Each device has a specific encoding and I think StringIO is exclusive to
UTF8. Any Latin request is due to the old IO interface and it should return
raw bytes directly.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
