### ISSUE TITLE
Empty body in case expression.

### ISSUE THREAD

**Issue by ankhers** [elixir-lang/elixir#6040]
### Environment

* Elixir & Erlang versions (elixir --version): 1.4.2
* Operating system: OSX 10.11.6

### Current behaviour

``` elixir
case foo() do
  {:ok, val} ->
    ...
  {:error, reason} ->
end
```

The previous code compiles with a warning (`warning: an expression is always required on the right side of ->. Please provide a value after ->`) despite missing the body of the last case. If you hit that code path, it simply returns `nil`. If you exclude the body of any case that is not the last, it is a compiler error.

### Expected behaviour

I would expect the code to not compile.

**Comment by josevalim** [comment]
@ankhers Since this code was used to compile without warnings on version 1.0, we cannot make it an error until Elixir 2.0. We have annotations in the code to remove it when we start working towards 2.0. Thank you!
