### ISSUE TITLE
Should defmodule et al be stricter with the module name?

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#6042]
~~~
iex(6)> defmodule :"Elixir.José", do: nil
{:module, :"Elixir.José",
 <<70, 79, 82, 49, 0, 0, 3, 196, 66, 69, 65, 77, 69, 120, 68, 99, 0, 0, 0, 94,
   131, 104, 2, 100, 0, 14, 101, 108, 105, 120, 105, 114, 95, 100, 111, 99, 115,
   95, 118, 49, 108, 0, 0, 0, 4, 104, 2, ...>>, nil}
iex(7)> h Elixir.José
** (SyntaxError) iex:7: unexpected token: "é" (column 13, codepoint U+00E9)
~~~

I was expecting the `defmodule` to fail.

Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:
false] [dtrace]                                                                            

Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)

**Comment by josevalim** [comment]
Any valid atom can be a valid module name. Including `:hello` if you want build Erlang atoms or `:"hello++world"` if you want to use quote. So I don't think we should limit it, it is semantically working as intended.

**Comment by eksperimental** [comment]
@pragdave you need to do:

    iex> h :"Elixir.José"

**Comment by pragdave** [comment]
I used tab completion, and that's what it gave me.

**Comment by josevalim** [comment]
@pragdave oh, so that's the bug. :) I opened #6043.  Thanks @pragdave
