### ISSUE TITLE
Consider quoted atoms when doing autocompletion

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6043]
See #6042.

**Comment by arjan** [comment]
Should this work like this (where | is the cursor position):
```
iex> defmodule :"Elixir.José", do: nil
iex> Elixir.Jos|
```
..when you now press TAB:
```
iex> :"Elixir.José"|
```
So it quotes the entire atom.

**Comment by josevalim** [comment]
@arjan Unfortunately we cannot wrap around quotes ourselves so we probably should just not show the alias during autocomplete.

**Comment by arjan** [comment]
Okay. I'll see what I can do :)

**Comment by josevalim** [comment]
@arjan one possible option is, after we find the available candidates, we should call `inspect(:"Elixir.José")` and see if it starts with `:`. If so, it is not a valid alias name.

**Comment by josevalim** [comment]
The above is just a suggestion, I haven't checked the code to see if it is the best way to go. :)

**Comment by arjan** [comment]
Makes sense. I was considering filtering all found candidates to include only the characters that make up a valid non-quoted atom (e.g. only upper/lowercase, 0-9 and _),  but your way is more future-proof.
