### ISSUE TITLE
Dialyzer warning "fun requires that _@1 is of type atom() | tuple() not #{}" only on Elixir 1.4 + Erlang 18 (NOT with 1.3 + (18 | 19) or 1.4 + 19)

### ISSUE THREAD

**Issue by PragTob** [elixir-lang/elixir#6046]
### Environment

* Elixir & Erlang versions (elixir --version): 

```
tobi@speedy ~/github/benchee $ elixir -v
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2
```

(Erlang is Erlang 18.3)

* Operating system: 

```
tobi@speedy ~/github/benchee $ uname -a
Linux speedy 4.8.0-45-generic #48~16.04.1-Ubuntu SMP Fri Mar 24 12:46:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

* important dependencies: [dialyxir](https://github.com/jeremyjh/dialyxir) 0.5.0

### Current behavior

When running dialyzer (through dialyxir) using elixir 1.4 and erlang 18.3 I get the following warning:

```
tobi@speedy ~/github/benchee $ elixir -v
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2
tobi@speedy ~/github/benchee $ mix dialyzer
Compiling 3 files (.ex)
Checking PLT...
[:compiler, :deep_merge, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/home/tobi/github/benchee/_build/dev/dialyxir_erlang-18.3_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/home/tobi/github/benchee/_build/dev/lib/benchee/ebin'],
 warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
  :unknown]]
done in 0m0.95s
lib/benchee/formatters/console.ex:190: The call _@1:'ips'() requires that _@1 is of type atom() | tuple() not #{}
done (warnings were emitted)
```

The code in question is:

```elixir
  @spec comparisons({any, Statistics.t}, %{atom => Unit.t}, integer, [{any, Statistics.t}]) :: [String.t]
  defp comparisons({_, reference_stats}, units, label_width, jobs_to_compare) do
    Enum.map jobs_to_compare, fn(job = {_, job_stats}) ->
      format_comparison(job, units, label_width, (reference_stats.ips / job_stats.ips))
    end
  end
```

This behaviour can be observed in PragTob/benchee#69 - for example [in this travis build matrix](https://travis-ci.org/PragTob/benchee/builds/226951533?utm_source=github_status&utm_medium=notification).

According to the [erlang documentation](http://erlang.org/doc/reference_manual/typespec.html) `#{}` seems to stand for an empty map. No idea how it gets that idea... at benchee (as you can see) I even tried `@spec`ing the function in question giving the calls in questions the type of `Statistics.t` which means it should now that it's a struct that has an `ips` key. The error was also occuring before when it was still implemented as a generic map.

Funnily, the same error occurs over at wallaby keathley/wallaby#205 (only under the same conditions aka elixir 1.4 and erlang 18) [build matrix](https://travis-ci.org/keathley/wallaby/builds/226702906)

There are a lot more errors over there, the ones I checked also seem to be key accesses through `.`-notation on maps and structs.

Even really simple stuff like:

```elixir
  def visit(%Session{driver: driver} = session, path) do
    uri = URI.parse(path)

    cond do
      uri.host == nil && String.length(base_url()) == 0 -> # error is on this line on `host`
       # .. don't care
    end
  end
```

emits warnings like `lib/wallaby/browser.ex:980: The call _@1:'host'() requires that _@1 is of type atom() | tuple() not #{}`

As a workaround to skip dialyzer for the problematic combination I do the following in my .travis.yml:

```
if ! ([[ "$TRAVIS_ELIXIR_VERSION" == "1.4"* ]] && [[ "$TRAVIS_OTP_RELEASE" == "18"* ]]); then mix dialyzer --halt-exit-status; fi
```
    
edit: [Same behavior on current master](https://github.com/elixir-lang/elixir/issues/6046#issuecomment-298104946)

### Expected behavior

Sam as it does on Elixir 1.3 and Erlang 18 + 19 or Elixir 1.4 does on Erlang 19

```
tobi@speedy ~/github/benchee $ elixir -v
Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.3.4
tobi@speedy ~/github/benchee $ mix dialyzer
Checking PLT...
[:compiler, :deep_merge, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
[check_plt: false,
 init_plt: '/home/tobi/github/benchee/_build/dev/dialyxir_erlang-18.3_elixir-1.3.4_deps-dev.plt',
 files_rec: ['/home/tobi/github/benchee/_build/dev/lib/benchee/ebin'],
 warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
  :unknown]]
done in 0m0.94s
done (passed successfully)
tobi@speedy ~/github/benchee $ asdf local elixir 1.4.2
tobi@speedy ~/github/benchee $ asdf local erlang 19.2
tobi@speedy ~/github/benchee $ mix dialyzer
Checking PLT...
[:compiler, :deep_merge, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/home/tobi/github/benchee/_build/dev/dialyxir_erlang-19.2_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/home/tobi/github/benchee/_build/dev/lib/benchee/ebin'],
 warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
  :unknown]]
done in 0m1.55s
done (passed successfully)
tobi@speedy ~/github/benchee $ 
```

As always, thanks for a great programming language that brings us all so much joy and all the work that goes into it :green_heart:

**Comment by josevalim** [comment]
Thank you for the detailed report. Can you please check master as well?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by PragTob** [comment]
Sorry, should have done so straight away!

Seems to be a problem on master (dfd0ab5) as well (just checked with benchee):

```
tobi@speedy ~/github/benchee $ ../elixir/bin/elixir -v
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0-dev (dfd0ab5)
tobi@speedy ~/github/benchee $ asdf local erlang 18.3
tobi@speedy ~/github/benchee $ ../elixir/bin/mix dialyzer --plt
Checking PLT...
[:compiler, :deep_merge, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
tobi@speedy ~/github/benchee $ ../elixir/bin/mix dialyzer 
Checking PLT...
[:compiler, :deep_merge, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/home/tobi/github/benchee/_build/dev/dialyxir_erlang-18.3_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/home/tobi/github/benchee/_build/dev/lib/benchee/ebin'],
 warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
  :unknown]]
done in 0m0.96s
lib/benchee/formatters/console.ex:190: The call _@1:'ips'() requires that _@1 is of type atom() | tuple() not #{}
done (warnings were emitted)
tobi@speedy ~/github/benchee $ asdf local erlang 19.2
tobi@speedy ~/github/benchee $ ../elixir/bin/mix dialyzer 
Checking PLT...
[:compiler, :deep_merge, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/home/tobi/github/benchee/_build/dev/dialyxir_erlang-19.2_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/home/tobi/github/benchee/_build/dev/lib/benchee/ebin'],
 warnings: [:unmatched_returns, :error_handling, :race_conditions, :underspecs,
  :unknown]]
done in 0m1.46s
done (passed successfully)
```

**Comment by fishcakez** [comment]
This is intentional because of how generated code is handled in Erlang OTP 18 and 19. In 1.3 we don't get ideal stacktraces, see: https://github.com/elixir-lang/elixir/pull/5116. Note that OTP 18 and OTP 19 behave quite differently regarding maps and there was a dialyzer bug in 19.0, so its likely you can only become warning free in OTP 19.1+ 1.4.0+: https://github.com/elixir-lang/elixir/blob/357bb4f914a6e46d3d14e7fd8e79cfdafea30125/lib/elixir/test/elixir/fixtures/dialyzer/remote_call.ex

**Comment by josevalim** [comment]
Thanks @fishcakez. I just started digging this rabbit hole again but you were faster than me. :)

**Comment by fishcakez** [comment]
@josevalim fortunately I remembered the issue but I was worried you were going to try to fix it on master so had to reply quick before you wasted your evening.

**Comment by PragTob** [comment]
Thank you very much for the amazing fast responses as always :tada:

Too bad Google didn't bring up anything about this. Maybe this at least helps others :)
