### ISSUE TITLE
Enum.chuck with weird result

### ISSUE THREAD

**Issue by ducduong** [elixir-lang/elixir#6058]
`iex(22)> Enum.chunk([1, 2, 3, 4, 5, 6, 7], 3, 3, [])`
`[[1, 2, 3], [4, 5, 6], '\a']`

It doesn't seem right to me.

**Comment by ducduong** [comment]
Another try produced the expect result

`iex(26)> Enum.chunk([1, 2, 3, 4, 5, 6], 4, 4, [])`
`[[1, 2, 3, 4], [5, 6]]`

**Comment by skovsgaard** [comment]
Erlang strings are represented as integers, which means that a list consisting of just 7 will be printed as the character, "a".

This means that you're actually getting the expected return value, but it's being printed differently in the shell.

**Comment by josevalim** [comment]
Exactly. When in doubt about a value, put an `i` in the front:

```iex
iex(3)> i '\a'
Term
  '\a'
Data type
  List
Description
  This is a list of integers that is printed as a sequence of characters
  delimited by single quotes because all the integers in it represent valid
  ASCII characters. Conventionally, such lists of integers are referred to as
  "charlists" (more precisely, a charlist is a list of Unicode codepoints,
  and ASCII is a subset of Unicode).
Raw representation
  [7]
Reference modules
  List
Implemented protocols
  IEx.Info, Collectable, Enumerable, Inspect, List.Chars, String.Chars
```
