### ISSUE TITLE
Compilator error when map used as a default value in record

### ISSUE THREAD

**Issue by Zert** [elixir-lang/elixir#6060]
Hello. It seems I found a compiler bug in macros-related code. When I use `%{}` as a default value in record, compiler does not compile this code:

```
** (CompileError) elx_bug.ex: invalid quoted expression: %{}
    expanding macro: TT.Metric.metric/1
    elx_bug.ex:34: TT.Metric.rd2st/1
    (elixir) expanding macro: Kernel.|>/2
    elx_bug.ex:34: TT.Metric.rd2st/1
```

### Environment

Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2

### Current behavior

Code with compilation error: https://gist.github.com/Zert/5c3249352ab456fb94e30386461d204e

Code without compilation error (`%{}` in defrecord has been replaced by `nil`): https://gist.github.com/Zert/eb34fac6260c24989bd0f75bfb290290

### Expected behavior

Both code samples should be compiled successfully

**Comment by josevalim** [comment]
Thank you. It is mostly like a bug in defrecord which is not properly escaping expressions.
