### ISSUE TITLE
Unclear behavior between Logger and SASL

### ISSUE THREAD

**Issue by Trevoke** [elixir-lang/elixir#6064]
### Environment

* Elixir & Erlang versions (elixir --version): 
  * Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
  * Elixir 1.4.2
* Operating system: 
  * OSX

I have observed what might be a defect. I have provided a simple Elixir app as evidence. https://github.com/Trevoke/sample-logger-vs-sasl-app

Here are the steps:

1. Create a new normal Elixir app, 
2. add https://github.com/onkel-dirtus/logger_file_backend as a dependency and the basic configuration to redirect the log out to a file
3. and make sure you tell Logger to handle SASL reports.
4 Then in the `extra_applications`, start `:os_mon`. Since that requires `:sasl` that will start it too... 

And the SASL reports will be sent to the terminal when you start things with `iex -S mix`. To turn that off I need to pass in the option `config :sasl, :sasl_error_logger, false` and then the logs disappear again, but that might now be because they're not being logged at all ?

My expectation would be that with this configuration, Logger would handle all of the SASL reports.

My current guess is that maybe the Logger is getting configured before SASL starts and when SASL does start, it gets its own default logger anyway?

**Comment by josevalim** [comment]
I believe you need to enable this option: https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L157-L160

**Comment by Trevoke** [comment]
It is enabled: https://github.com/Trevoke/sample-logger-vs-sasl-app/blob/master/config/config.exs#L34

**Comment by Trevoke** [comment]
(Though please do note that if you try the app I linked to, it won't output anything to the terminal because I told `sasl` to disable its error logger [here](https://github.com/Trevoke/sample-logger-vs-sasl-app/blob/master/config/config.exs#L44) so you'd have to comment out that line).

**Comment by josevalim** [comment]
@Trevoke thank you for the reply. This issue happens because sasl is being started before logger is configured, so we don't redirect the logs. Then, after mix runs, logs is properly configured, so all future sasl reports will be redirected.

Unfortunately I do not believe there is anything we can do before Mix itself boots your app. :(

**Comment by Trevoke** [comment]
So this is not exactly a defect, just a difficult timing problem. It would
probably go away if I started `sasl` myself somewhere *other* than
`extra_applications`.

This was a little unexpected for me, though it makes sense. Is there cause
to update the documentation of the `handle_sasl_reports` option to indicate
that it will not work when `sasl` is started via `extra_applications` ?

**Comment by josevalim** [comment]
Actually you want to start logger after sasl, so sasl reporter is properly removed when logger is started, but then it means the early messages definitely won't be handled by logger. Let's summon @fishcakez in case he has an idea.
