### ISSUE TITLE
Badly loaded module

### ISSUE THREAD

**Issue by InoMurko** [elixir-lang/elixir#6065]
Erlang/OTP 19 [erts-8.0.2] [source-9503fff] [64-bit] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.3.2
Debian GNU/Linux 8.7 (jessie)

We had some SASL crash reports saying a call to an undefined function has been made.
I went and I checked which function module exports. Indeed:
```
module = Transaction.ReadRepo
function = transaction_for_entity
arguments = [1,2]
Kernel.apply(module, function, arguments)
** (UndefinedFunctionError) function Transaction.ReadRepo.transaction_for_entity/2 is undefined or private

Transaction.ReadRepo.module_info()
[module: Transaction.ReadRepo,
exports: [__info__: 1, module_info: 0, module_info: 1],
```
I proceed with reloading the module
`l(Transaction.ReadRepo)`

I re-run module info:

```
module = Transaction.ReadRepo
function = transaction_for_entity
arguments = [1,2]
Kernel.apply(module, function, arguments)
{:ok, nil}

Transaction.ReadRepo.module_info()
[module: Transaction.ReadRepo,
exports: [__info__: 1, all_transactions: 0, all_transactions: 1, transaction_for_entity: 2, ...
```

Wondering, how could this happen?

**Comment by josevalim** [comment]
You can use `:code.which(module)` as an attempt to find the `.beam` and see if they are the same before and after reloading. It may happen because you have a stray .beam file somewhere, that ends up being loaded first, and then `l` forces it to be reloaded with a more recent version in the path.

Make sure you have no warnings during compilation, especially about duplicate modules. If the problem persists, please provide us a mechanism to reproduce the issue.

**Comment by InoMurko** [comment]
Indeed, the paths are not the same:
`Transaction.ReadRepo.module_info
[module: Transaction.ReadRepo,
 exports: [__info__: 1, module_info: 0, module_info: 1],
 attributes: [vsn: [287389242218781174952288126763274151498]],
 compile: [options: [:debug_info], version: '7.0.1', source: '/app/iex'],
 native: false,
 md5: <<216, 53, 39, 156, 71, 161, 218, 198, 246, 79, 31, 187, 200, 221, 38,
   74>>]`

after reload:

`Transaction.ReadRepo.module_info()
[module: Transaction.ReadRepo,
 exports: [__info__: 1, all_transactions: 0, all_transactions: 1,
  transaction_for_entity: 2, module_info: 0, module_info: 1],
 attributes: [vsn: [156517611047686208865032691176436449519]],
 compile: [options: [:debug_info], version: '7.0.1',
  source: '/app/apps/transaction/lib/transaction/read_repo.ex'], native: false,
 md5: <<117, 192, 50, 5, 88, 129, 156, 37, 125, 176, 249, 61, 231, 172, 192,
   239>>]`

We deploy a distillery generated release into docker. I'll try to find a way to reproduce. Thanks

**Comment by josevalim** [comment]
Cool. I would try to figure out why there is a version at /app/iex and how it is becoming part of the release.
