### ISSUE TITLE
Unclear error message do "fn .. do ... end"

### ISSUE THREAD

**Issue by benzen** [elixir-lang/elixir#6068]
I hear that elixir is trying to improve its error messages.

Hear is a case case that can be annoying for a new commer.
Here is an exemple of code:

    Enum.find network.positions, fn [_station_id, _line_id, metro_id] do
        metro_id === metro.id
     end

You'll notice that if've user fn ... do ... end instead of fn ... -> ... end

In this case the error message is 

    missing terminator: end (for "do" starting at line 1)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

since the  "do end" is frequently used  i think it could be valuable to add a custom error message for this pattern

**Comment by josevalim** [comment]
Thank you @benzen. Unfortunately I don't think there is anything we can do in this case. We would need to add a lot of complexity to make the tokenizer and parser understand an invalid syntax just to say it is invalid.
