### ISSUE TITLE
Time Sigil Doesn't Accept Interpolation

### ISSUE THREAD

**Issue by kyledecot** [elixir-lang/elixir#6069]
### Environment

* Elixir & Erlang versions (elixir --version): 1.4.2, Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
* Operating system: MacOS 10.12.4 (16E195)

### Current behavior

```
iex(1)> hour = "01"
"01"
iex(2)> ~T[#{hour}:00:00]
** (ArgumentError) cannot parse "\#{hour}:00:00" as time, reason: :invalid_format
    (elixir) lib/calendar.ex:645: Time.from_iso8601!/1
    (elixir) expanding macro: Kernel.sigil_T/2
             iex:2: (file)
```
### Expected behavior

```
iex(1)> hour = "01"
"01"
iex(2)> ~T[#{hour}:00:00]
~T[00:00:00]
```

**Comment by josevalim** [comment]
That's by design. None of the sigils starting in uppercase will handle interpolation.

**Comment by kyledecot** [comment]
@josevalim is there a plan to add the lowercase counterpart in a future version?
