### ISSUE TITLE
Test execution with stale HTTP responses

### ISSUE THREAD

**Issue by InoMurko** [elixir-lang/elixir#6099]
Erlang/OTP 19 [erts-8.3] 
Interactive Elixir (1.4.2) 

Hi,
some background what the test should perform. I want to execute two transactions towards Braintree API. First one has an amount of 500, the second one amount of 100. Between each transaction is a 40s timeout (:timer.sleep).
What happens is that the execution and HTTP responses are correct when executing the test script directly:
mix test test/wallet/payments/braintree/braintree3_test.exs

And when executing all tests with:
mix test
The second HTTP request for a transaction (via HttPoison) returns a stale response of the first transaction. I can see that because the created_at parameter and amount and id returned of the transaction is the same in both cases, which is not, when the test is executed directly.
The braintree3_test.exs has only **one** test function.
Is there a level of caching implemented somewhere in tests execution?

**Comment by ericmj** [comment]
This is likely an issue with your application rather than mix. There is no caching of test execution.

**Comment by InoMurko** [comment]
Is there a difference between execution of tests when providing a direct script or the whole suite?

**Comment by ericmj** [comment]
There is no difference in the execution of the tests but your application state can have changed due to the execution of other tests.

**Comment by josevalim** [comment]
Agreed with @ericmj. If you believe this is a bug in Mix, please provide a mechanism to reproduce it and more information on why do you believe it is a bug in Elixir/Mix.
