### ISSUE TITLE
Mix.Dep.Umbrella.loaded() does not work properly after using File.cd

### ISSUE THREAD

**Issue by Gazler** [elixir-lang/elixir#6104]
### Environment

* Elixir & Erlang versions (elixir --version): 1.4.2 and master
* Operating system: Linux

Using `Mix.Dep.Umbrella.loaded()` after running `File.cd` causes the paths to be wrong in the `Mix.Dep` struct.

I have created a repo to demonstrate this issue which you can check at https://github.com/Gazler/deps_test and run `mix run deps.exs`

This function is used in Phoenix at: https://github.com/phoenixframework/phoenix/blob/663d5f770ee490e05e444906d4eb23f5167e0cf1/lib/phoenix/code_reloader/server.ex#L111

It is also trivial to cause this issue on Phoenix master with the following:

    mix phx.new reloader_test --umbrella --no-ecto --no-brunch --no-html && cd reloader_test && iex -S mix phoenix.server && FIle.cd("/tmp")

Then when you visit http://localhost:4000 this will break with:

 > could not set current working directory to "/tmp/apps/foo" no such file or directory

This requires  restart of Phoenix to fix.

The output of `Mix.Dep.Umbrella.loaded()` in a new iex session is:

```elixir
[%Mix.Dep{app: :foo, deps: [], extra: [],
  from: "/home/gazler/development/elixir/deps_test/mix.exs", manager: :mix,
  opts: [path: "apps/foo",
   dest: "/home/gazler/development/elixir/deps_test/apps/foo",
   from_umbrella: true, env: :dev,
   build: "/home/gazler/development/elixir/deps_test/_build/dev/lib/foo"],
  requirement: nil, scm: Mix.SCM.Path, status: {:ok, "0.1.0"},
  top_level: false},
 %Mix.Dep{app: :bar,
  deps: [%Mix.Dep{app: :foo, deps: [], extra: [],
    from: "/home/gazler/development/elixir/deps_test/apps/bar/mix.exs",
    manager: nil,
    opts: [env: :dev, path: "../foo",
     dest: "/home/gazler/development/elixir/deps_test/apps/foo",
     build: "/home/gazler/development/elixir/deps_test/_build/dev/lib/foo",
     in_umbrella: true], requirement: nil, scm: Mix.SCM.Path,
    status: {:ok, nil}, top_level: false}], extra: [],
  from: "/home/gazler/development/elixir/deps_test/mix.exs", manager: :mix,
  opts: [path: "apps/bar",
   dest: "/home/gazler/development/elixir/deps_test/apps/bar",
   from_umbrella: true, env: :dev,
   build: "/home/gazler/development/elixir/deps_test/_build/dev/lib/bar"],
  requirement: nil, scm: Mix.SCM.Path, status: {:ok, "0.1.0"},
  top_level: false}]
```
After running `File.cd("/tmp")` the output is now:

```elixir
[%Mix.Dep{app: :bar, deps: [], extra: [], from: "/tmp/mix.exs", manager: :mix,
  opts: [path: "apps/bar", dest: "/tmp/apps/bar", from_umbrella: true,
   env: :dev, build: "/tmp/_build/dev/lib/bar"], requirement: nil,
  scm: Mix.SCM.Path, status: {:unavailable, "/tmp/apps/bar"}, top_level: false},
 %Mix.Dep{app: :foo, deps: [], extra: [], from: "/tmp/mix.exs", manager: :mix,
  opts: [path: "apps/foo", dest: "/tmp/apps/foo", from_umbrella: true,
   env: :dev, build: "/tmp/_build/dev/lib/foo"], requirement: nil,
  scm: Mix.SCM.Path, status: {:unavailable, "/tmp/apps/foo"}, top_level: false}]
```

**Comment by josevalim** [comment]
As per the IRC discussion, this is a Phoenix bug as Mix expects to run in the current directory and Phoenix is fetching deps after the directory changes.
