### ISSUE TITLE
Elixir 1.4 regression: requires git even with `--no-deps-check`

### ISSUE THREAD

**Issue by SimonWoolf** [elixir-lang/elixir#6114]
* Elixir 1.4.2, erlang 19.3, Linux (ubuntu 14.04)

Just upgrading a production app from Elixir 1.2.6 to 1.4.2.

When we compile a slug to be run on a docker container, after compilation we strip out the `.git` dir (and the docker container doesn't contain a git executable). It's then run as `elixir --sname <myappname> -S mix run --no-halt --no-deps-check`.

On Elixir 1.2, with the `--no-deps-check` flag, this worked fine. On Elixir 1.4, this gives a `Error fetching/updating Git repository: the "git" executable is not available in your PATH. Please install Git on this machine or pass --no-deps-check if you want to run a previously built application on a system without Git.`

In Elixir 1.4, Mix.Tasks.Deps.Loadpaths [appears to be calling `check_lock/1` on all the cached deps](https://github.com/elixir-lang/elixir/blob/690c2c40c948564f7db5fccfd66246ed78c6fe8d/lib/mix/lib/mix/tasks/deps.loadpaths.ex#L24) before the `--no-deps-check` flag is even checked. `check_lock/1` calls `SCM.Git.lock_status/1`, which calls `assert_git!/0`, which prints that error.

Would you be open to a PR that put the `check_lock/1` map behind the `--no-deps-check` check? It's just decorating everything with `status` information that's never going to be needed given `deps_check` won't be called, right?

**Comment by josevalim** [comment]
Yes, please send a PR and a test so we make sure we don't have any further regression. :)

**Comment by josevalim** [comment]
@SimonWoolf in fact the solution is most likely moving the check_lock inside the `deps_check/2` function. So the most important bit is indeed the test. :)

**Comment by xiamx** [comment]
Has any work been done on this? I'd like to take a try.

**Comment by whatyouhide** [comment]
@xiamx go ahead! :D

**Comment by SimonWoolf** [comment]
Apologies for dropping the ball on this (I came down with the flu). Thanks @xiamx for picking it up :)
