### ISSUE TITLE
strange behaviour in the IEx console.

### ISSUE THREAD

**Issue by chenfei-io** [elixir-lang/elixir#6139]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
```
* Operating system: macOS

### Current behavior
start the iex console, and 
```
iex(1)> h Mix.Cli
Could not load module Mix.Cli, got: badfile

18:44:27.697 [error] Loading of /usr/local/Cellar/elixir/1.4.2/bin/../lib/mix/ebin/Elixir.Mix.Cli.beam failed: :badfile

iex(2)> 
18:44:27.698 [error] beam/beam_load.c(1376): Error loading module 'Elixir.Mix.Cli':
  module name in object code is Elixir.Mix.CLI
```

### Expected behavior
I am not sure about the expected behaviour, but it shouldn't display the output like this?

**Comment by josevalim** [comment]
Although the error message is confusing, that's expected behaviour. The important part is this:  "Error loading module 'Elixir.Mix.Cli': module name in object code is Elixir.Mix.CLI"

Module names are case sensitive and you used Mix.Cli while it should be Mix.CLI.

**Comment by chenfei-io** [comment]
```
iex(1)> h Mix.Cli
output from iex
iex(2)> 
output from iex again for the same input
```
I think there maybe some unexpected new line character? because the out put should be out in one go?

**Comment by josevalim** [comment]
Yes, the new lines are getting garbled but if you type `1 + 2` it will return 3. Or just press enter to start a new one.
