### ISSUE TITLE
Cryptic error when invalid :limit given in IO.inspect

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#6142]
Look at the misspelling in the `:limit` value
```
iex(8)> IO.inspect([a: 1, b: 2], limit: :infitiny)
** (ArithmeticError) bad argument in arithmetic expression
    (elixir) lib/inspect/algebra.ex:596: Inspect.Algebra.decrement/1
    (elixir) lib/inspect/algebra.ex:578: Inspect.Algebra.do_surround_many/5
    (elixir) lib/inspect/algebra.ex:562: Inspect.Algebra.do_surround_many/7
    (elixir) lib/io.ex:293: IO.inspect/3
```

It's impossible to know what's wrong with that Error message.

I was looking at a solution, but it seems that we should be validating Inspect.Opts, just wanted to look for some guidance before investing energy on this.

**Comment by josevalim** [comment]
Let's attempt to improve this on the Erlang side: https://github.com/erlang/otp/pull/1478

**Comment by eksperimental** [comment]
@josevalim it's great to see that issues discovered in Elixir make their way into Erlang.
