### ISSUE TITLE
Strict SemVer rejection of leading zeros in v1.4.4

### ISSUE THREAD

**Issue by ntrepid8** [elixir-lang/elixir#6155]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.4.4 Erlang/OTP 18

* Operating system: Ubuntu 16.04.2 LTS

### Current behavior

The `Version.parse/1` function now rejects leading zeros:
```
iex(1)> Version.parse("2017.05.26-0")
:error
```

In Elixir 1.4.2 it does not:
```
iex(1)> Version.parse("2017.05.26-0")
{:ok, #Version<2017.5.26-0>}
```

### Expected behavior

The new behavior is correct according to the SemVer spec: http://semver.org/#spec-item-2
> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

There is no mention of this in the changelog for `v1.4.3` or `v1.4.4` that I can find. Would it be possible to add this to the [CHANGLOG.md](https://github.com/elixir-lang/elixir/blob/v1.4/CHANGELOG.md)?

We were using leading zeros in our version numbers so the artifacts (debian packages) would sort in order when viewed (lame I know). But after updating Elixir today the builds are broken and it took a while to figure out exactly why. A note in the changelog would be helpful.

Would a PR to update `CHANGELOG.md` to note this be accepted?

**Comment by josevalim** [comment]
@ntrepid8 yes, please send a PR to the v1.4 branch.

This was lack of attention from our part. We improved the Version parser so it works on Erlang 20 but forgot to note we are now properly following the spec.
