### ISSUE TITLE
mix compile.xref always runs, even without file changes

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#6165]
### Environment

* Elixir & Erlang versions (elixir --version): v1.4.4
* Operating system: macOS Sierra

### Current behavior

As mentioned in issue title, `mix compile.xref` runs every single time, even when there are no file changes. The `.compile.xref` manifest file is empty.

I see two potential issues:

1. manifest is called `.compile.xref`, whereas the docs say:

   > When this task runs, it will check the modification time of the `:elixir` compiler manifest.

2. we just touch the manifest, but it does not have any content to start with: https://github.com/elixir-lang/elixir/blob/v1.4.4/lib/mix/lib/mix/tasks/compile.xref.ex#L64

### Expected behavior

`mix compile.xref` runs only if there are file changes.

**Comment by josevalim** [comment]
@wojtekmach I cannot reproduce this. We compare the mtime of the xref manifest with the elixir manifest, that's why the manifest file can be empty.

I have changed the task locally and it runs only on the first time. Maybe mtimes are borked on the project you checked this?

**Comment by wojtekmach** [comment]
@josevalim yeah, my mtimes must have got borked as I can't reproduce this error anymore after `rm -rf _build`. Thank you and sorry for noise.
