### ISSUE TITLE
File.stream! is not splitting lines for osx text files (CR instead of LF)

### ISSUE THREAD

**Issue by mlankenau** [elixir-lang/elixir#6169]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.2 
* Operating system: 
OSX 10.12.3

Test text file (CSV) was produced with MS Excel 2011 on OSX. Not exotic enough to ignore.

### Current behavior

```
iex(1)> File.write("test.txt", "first\rsecond")
:ok
iex(2)> File.stream!("test.txt") |> Enum.into([])
["first\rsecond"]
iex(3)>
```

### Expected behavior

```
iex(1)> File.write("test.txt", "first\rsecond")
:ok
iex(2)> File.stream!("test.txt") |> Enum.into([])
["first", "second"]
iex(3)>
```

**Comment by josevalim** [comment]
"\r" is not a valid line break. Line breaks are "\n" or  "\r\n". "\r" on its own is not.  Please see representations here: https://en.wikipedia.org/wiki/Newline

**Comment by NobbZ** [comment]
Please do not say that it isn't valid, even your linked source does mention it in the "represantation" section:

> * CR:    Commodore 8-bit machines, Acorn BBC, ZX Spectrum, TRS-80, Apple II family, Oberon, the classic Mac OS up to version 9, MIT Lisp Machine and OS-9

So it is valid and at least historically relevant. And even worse, it seems to be actually used by a relevant software.

**Comment by josevalim** [comment]
@NobbZ does the Erlang VM run in any of those systems? Are you running in any of those systems?

The context matters here. File.stream is meant to read from the filesystem, optimized for the line terminations in the system it runs on. The reporter mentioned OSX 10. If I use File.stream and it breaks on "\r" under OSX 10, I would consider it a **bug**.

**Comment by josevalim** [comment]
In any case, my first comment should have specified that "\r" is not a valid line break under the systems the VM runs on.

**Comment by NobbZ** [comment]
I'm not sure if there is a recent version of the BEAM available for any of those systems. So yes, I think we can agree that it shouldn't be relevant anymore after Mac OS X has been released and that is more a bug in Office than in Elixir.

**Comment by mlankenau** [comment]
@josevalim Not sure why the file has to be created on the system where BEAM is running. In our case it is a customer upload. I think it will be easy to fix (if you know were to look) and would make the platform more mature.

**Comment by mlankenau** [comment]
@NobbZ The Error happened on OS X. The file have been created on a brand new Mac Book Pro with the latest OSX and Excel 2011. It is NOT legacy stuff.

**Comment by josevalim** [comment]
We need to draw a line. Theoretically, anyone can come up with any format that uses a character of choice for new lines. It seems Excel did so, it doesn't mean we need to support it. Our line is drawn at "we support the formats the VM runs on".

It is worth repeating that, if we change Elixir to treat "\r" as a new line on Mac OS X, then File.stream will be broken for everyone that does not expect "\r" to be considered a new line under Mac OS X, which is the majority of users.

**Comment by michalmuskala** [comment]
The only way to argue it's not legacy (given it's not used by any OS since 2001) would be to list languages that support `\r` line endings in their stdlib.

**Comment by mlankenau** [comment]
I think - after looking at the code - it is an erlang issue anyways (:io.get_line), maybe I am wrong.

**Comment by mlankenau** [comment]
@josevalim just in case, it would be necessary to treat \r\n as \n not as \n\n.

**Comment by josevalim** [comment]
@mlankenau that's already how it is treated.

**Comment by josevalim** [comment]
Oh yes, definitely. But we don't have to worry about that since we don't plan to support \r as a new line anyway. :)
