### ISSUE TITLE
Consider showing a snippet of the source code in case of exceptions in ExUnit

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6173]
Currently we show only the exception message and stacktrace. Showing a source snippet can help speed up the cause of the error.

@talentdeficit, do you know of any tool that does it? Should we show the source snippet of the call in the test that failed or the place in the source that caused the exception?

**Comment by talentdeficit** [comment]
current:
```bash
  1) test example (Example.Tests)
     test/example_test.exs:171
     ** (ArgumentError) argument error
     stacktrace:
       :erlang.binary_to_atom(:key, :utf8)
       (example) lib/example.ex:325: Example.function/2
       ...
       test/example_test.exs:172: (test)
```

would be nice:
```bash
  1) test example (Example.Tests)
     test/example_test.exs:171
     ** (ArgumentError) argument error
     code: Example.function(nil)
     stacktrace:
       :erlang.binary_to_atom(:key, :utf8)
       (example) lib/example.ex:325: Example.function/2
       ...
       test/example_test.exs:172: (test)
```

i think just showing the line that has the exception would be fine, but if the actual call could be highlighted that would be even better

**Comment by robi-wan** [comment]
I think the Elm compiler does this for [compiler errors](http://elm-lang.org/blog/compiler-errors-for-humans): ![Image of compiler error message](http://elm-lang.org/assets/blog/error-messages/0.15.1/naming.png)
