### ISSUE TITLE
Add __protocol__(:impls) to protocols

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6178]
It will return `{:ok, list_of_impls} | :error`. We can use this when raising Protocol.UndefinedError and then list all known implementations.

The list is only available if protocols have been consolidated (hence the possible `:error` tuple result).

**Comment by antipax** [comment]
Would be happy to pick this one up if no one else is working on it yet.

**Comment by josevalim** [comment]
Yes, please.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ericmj** [comment]
Will this only work if we have run consolidation?

**Comment by josevalim** [comment]
Yes!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by antipax** [comment]
Do we want a function like `Protocol.consolidated?/1` for this, and/or documentation on `Kernel.defprotocol/2`, like for `module.__protocol__(:name | :functions)`?

**Comment by josevalim** [comment]
We should document it like we document `:functions` but no need for `Protocol.impls`.
