### ISSUE TITLE
Concatenates a proper list

### ISSUE THREAD

**Issue by dzc944262316** [elixir-lang/elixir#6179]
iex: [1] ++ [2] ++ [3]
result: [1, 2, 3]

iex: [1, 2, 3] -- [2] -- [3]
result: [1, 3]

this is a bug?

**Comment by eksperimental** [comment]
It's correct. This is due to the associativity of the `--` operator, which is right to left.
So if you add parenthesis, your example translates as:

```
iex(17)> [1, 2, 3] -- ([2] -- [3])                  
[1, 3]
```

**Comment by dzc944262316** [comment]
Thank you   
`iex(1)> ([1,2,3] -- [2]) -- [3]
[1]
`
This is the result I want

**Comment by eksperimental** [comment]
no worries
