### ISSUE TITLE
"Internal consistency check failed" during compilation using && operator with floats

### ISSUE THREAD

**Issue by CandyGumdrop** [elixir-lang/elixir#6201]
### Environment

* Elixir & Erlang versions (elixir --version):

Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe]

Elixir 1.4.4

* Operating system: Gentoo Linux x86_64

### Current behavior

Attempting to compile the following `test.ex`:

```elixir
defmodule Test do
  def test(x) do
    y = x + 1.0
    x > 0 && y > 0
  end
end
```

fails as follows:

```
$ elixirc test.ex

== Compilation error on file test.ex ==
** (CompileError) Elixir.Test: function test/1+18:
  Internal consistency check failed - please report this bug.
  Instruction: {bif,'>',{f,0},[{x,1},{integer,0}],{x,0}}
  Error:       {uninitialized_reg,{x,1}}:

    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

```

I've tried to strip down this example as much as I can to see under what conditions this bug occurs and it seems to fail if `y` is assumed to be a float (which is the case adding 1.0) and is derived from a parameter and not just a constant float. Different combinations of comparison operators on the last line also produce this bug, but it seems to only occur when using the `&&` operator.  This doesn't seem to happen for `and` or `||`.

Testing on another machine with Erlang 20.0-rc1 and Elixir 1.4.4, this error doesn't seem to occur.  The machine this bug occurs on is Erlang 19.3 and Elixir 1.4.4 from Gentoo packages.

**Comment by josevalim** [comment]
This is an Erlang/OTP bug, however, you have mentioned and I have verified it is fixed on Erlang 20.0, so we should be good to go. Thank you! :heart:

**Comment by michalmuskala** [comment]
Would it make sense to report it to OTP team anyway? Maybe it was fixed only accidentally and in that case, it would be nice to add a test for this.

**Comment by josevalim** [comment]
@michalmuskala good point. can you please do so? Thank you!

**Comment by michalmuskala** [comment]
Done https://bugs.erlang.org/browse/ERL-433

**Comment by JayachandraGunturu** [comment]
Environment : CenOS7
Erlang version : Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Attempted to build kazoo from source code and got the following
