### ISSUE TITLE
Compiling Erlang with mix, doesn't generate beam files if using {:d, VAR, VALUE} in erlc_options

### ISSUE THREAD

**Issue by rlipscombe** [elixir-lang/elixir#6209]
I'm using mix to compile some Erlang modules, and I've got the following in `src/foo.erl`:

```
-module(foo).
-export([bar/0]).

bar() -> ok.
```

This compiles fine with `mix compile`.

I then add `erlc_options: [{:d, 'BAZ', 'quux'}]` to `mix.exs` and run `mix clean`.

Now when I run `mix compile`, mix reports the following:

```
Compiling 1 file (.erl)
Generated bug app
```

There are no `.beam` files in the `_build/dev/lib/ebin` directory and the `bug.app` file has an empty `{modules,[]}` term.

Running `mix compile` again results in:

```
Compiling 1 file (.erl)
```

...and it never generates a beam file. You can repeat this step as many times as you like.

Setting `erlc_options: []` causes it to start working correctly again.

----

My mix.exs file looks like this:

```
defmodule Bug.Mixfile do
  use Mix.Project

  def project do
    [app: :bug,
     version: "0.1.0",
     #erlc_options: [],
     erlc_options: [{:d, 'BAZ', 'quux'}],
     deps: []]
  end

  def application do
    []
  end
end
```

**Comment by josevalim** [comment]
@rlipscombe can you please push a small project to github that we can run `mix compile` on and verify? That will make our life much easier if we already have a mechanism to directly reproduce the issue. Thank you!

**Comment by rlipscombe** [comment]
```
$ mix -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.4.4
```

...incidentally.

**Comment by josevalim** [comment]
So the error is because you should write: `erlc_options: [{:d, :BAZ, :quux}]`, i.e. as Elixir atoms. I will make sure to not silently discard on those cases but the error message will just say "ArgumentError", because unfortunately that's all Erlang gives us.
