### ISSUE TITLE
Publish a hex package for Elixir

### ISSUE THREAD

**Issue by filmor** [elixir-lang/elixir#6210]
Currently, when running a predominantly Erlang environment, it's a bit more pain than necessary to integrate Elixir since one has to guess or configure the correct installation path for Elixir manually.

If hex packages were published for the individual parts of Elixir (elixir, mix, eex, ex_unit, iex, logger) that would immensely help adoption in pure-Erlang projects.

**Comment by josevalim** [comment]
Currently we have no plans for publishing Hex packages for Elixir libraries. There is code between the libraries that assume you are running on an equal version, for example `mix x.y.z` runs only against `elixir x.y.z` and publishing those packages would be bring those problems to the surface (which are currently low priority to tackle).

**Comment by 2kodes** [comment]
hi,
 on a slightly related note is there any way to get the docs for elixir-lang through hexdocs?? something like mix hex.docs  fetch elixir

**Comment by josevalim** [comment]
@2kodes that command does not work? If it does not work, please open up an issue on github.com/hexpm/hex

**Comment by 2kodes** [comment]
nope it doesnt..will file a report..thanks

**Comment by filmor** [comment]
This is a bit unfortunate. How about being restrictive with the versioning (`== 1.4.4`)?
