### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by jackalcooper** [elixir-lang/elixir#6211]
### Environment

* Elixir & Erlang versions (elixir --version): 

Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2

* Operating system: macOS 10.12.5 (16F73)

### Current behavior

```elixir
defmodule Strain do
  def keep(list, fun) do
    do_keep(list, fun, []) |> Enum.reverse
  end

  def do_keep([], _fun, result) do
    result
  end

  def do_keep([head | tail], fun, result) do
    if apply(fun, head), do: do_keep(tail, fun, [head | result]), else: do_keep(tail, fun, result)
  end
end
```
If I call `Strain.keep([1, 2, 3], fn e -> e < 10 end) == [1, 2, 3]`, I got incorrect error message:
```
** (UndefinedFunctionError) function Strain.do_keep/3 is undefined or private. Did you mean one of:
     
           * do_keep/3
```
But actually the incorrect part is `head` which should be `[head]`
### Expected behavior
Correct error message addressing the real problem
Thanks you!

**Comment by josevalim** [comment]
This is amazing! It is an Erlang VM bug. I will put it on my queue of PRs to send there. :)

**Comment by josevalim** [comment]
Here is a slightly smaller example:

```elixir
defmodule Strain do
  def keep([head | _], fun) do
    apply(fun, head)
  end
end

try do
  Strain.keep [1, 2, 3], fn x -> x end
catch
  kind, reason -> IO.inspect {kind, reason, System.stacktrace}
end
```

**Comment by michalmuskala** [comment]
I reported a similar issue in the erlang's bug tracker couple days ago: https://bugs.erlang.org/browse/ERL-432

**Comment by josevalim** [comment]
Closing this as it has been reported to OTP.
