### ISSUE TITLE
ExUnit --listen-on-stdin considerably slower than just reruning test

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#6217]
### Environment

* Elixir & Erlang versions: Elixir 1.5.0-dev, OTP 19.3
* Operating system: macOS Sierra 10.12.5

### Current behavior

See a gif below trying to measure the relative difference, on left pane we manually re-run tests, on right pane we use `--listen-on-stdin`

![untitled](https://user-images.githubusercontent.com/76071/27014301-949a13ee-4ef6-11e7-8687-e373d4378611.gif)

See: https://github.com/wojtekmach/slow_ex_unit

### Expected behavior

`--listen-on-stdin` makes re-running tests as fast or faster than starting from scratch.

**Comment by josevalim** [comment]
There is not much we can do here. --listen-on-stdin shuts down your system politely instead of halting and when you just shut down you don't need to care about this. Unless you need it to be running on the same process, starting from scratch is likely better.

**Comment by wojtekmach** [comment]
I'm looking at the lines where this behavior seems to occur [1] and I wonder if it's possible to politely shutdown/restart the system when the test finished but _before_ the next test run occurs (triggered by STDIN) so that the cost of shutting down/booting is amortized and so make it more responsive. Or is it that "warming up" before the next test run can mess with test results (e.g. supervision tree started way before test actually run).

To give some context, I'm trying to use `--stale --listen-on-stdin` to mimic Ruby's guard tool, and the lag before next test run is quite noticeable. I'm probably missing details and tbh it's not a huge deal, jsut wondering if there's some low hanging fruit to speed it up.

https://github.com/elixir-lang/elixir/blob/v1.4.4/lib/mix/lib/mix/tasks/test.ex#L181:L182

**Comment by josevalim** [comment]
Oh, I like a lot the idea of restarting before! Let's give it a try, yes!

**Comment by josevalim** [comment]
@wojtekmach oh, the problem with this approach is that if there is input while we are restarting to wait for input, it will be missed, certainly not working like guard.

**Comment by josevalim** [comment]
@wojtekmach I will close this because of the limitation above. If you have more ideas, please let us know, and I will gladly reopen this. :)
