### ISSUE TITLE
Add Date.range

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6223]
It should use a `Date.Range` struct that implements the Enumerable protocol. It should keep the first and last dates for `member?` tests and the `first_rata_die` and `last_rata_die` for a fast `reduce` implementation and a `kind` field that describes it as increasing or decreasing. The range dates must have matching calendars.

**Comment by uesteibar** [comment]
Hi!

What would the interface for this be? I guess `Date.Range.new(first_date, last_date)` should do it.
Also, with `the range dates must have matching calendars` you mean that they should be one of: `Date`, `Time`, `NaiveDateTime` and `DateTime`, or am I missing something?

Nice one, i like it! :)

**Comment by josevalim** [comment]
The interface is `Date.range/2`. Matching calendars mean the calendar field in the data struct received as argument must match.

**Comment by uesteibar** [comment]
If you're okay with it, I'd like to see if I can take care of this. It's a little bit more complex than what I've done so far but I think I can tackle it :)

Thanks!

**Comment by jameslong** [comment]
@uesteibar If you don't have time please let me know because I can have a crack at it this weekend.

**Comment by uesteibar** [comment]
@jameslong I already have a working prototype :) some polishing left to do but shouldn't take long. Thanks for offering!
