### ISSUE TITLE
Confusion with multiple describe blocks with the same message

### ISSUE THREAD

**Issue by gmile** [elixir-lang/elixir#6236]
After getting to the bottom of what seemed like a weird test failure, I realized I made a mistake by giving two `describe` blocks the same description.

Along with setup blocks, this causes a confusion: the second `setup` is executed for the first test, not the first `setup` block as I'd expect to.

### Current behavior

```elixir
defmodule DescribeTest do
  use ExUnit.Case

  describe "my_description" do
    setup do
      {:ok, %{value: 5}}
    end

    test "test 1", %{value: value} do
      assert 5 = value
    end
  end

  describe "my_description" do
    setup do
      {:ok, %{value: 10}}
    end

    test "test 2", %{value: value} do
      assert 10 = value
    end
  end
end
```

Code above will fail with the following error:

```
mix test test/unit/describe_test.exs


  1) test my_description test 1 (DescribeTest)
     test/unit/describe_test.exs:9
     match (=) failed
     code:  5 = value
     right: 10
     stacktrace:
       test/unit/describe_test.exs:10: (test)

.

Finished in 0.08 seconds
2 tests, 1 failure

Randomized with seed 873389
```

### Expected behavior

Show a warning or even raise an error when defining a `describe` block with description that was already taken. I'm not sure for a use case to justify having multiple `describe` blocks with the same description.

**Comment by whatyouhide** [comment]
I think it would make sense to not allow describe blocks with the same name (like we do not allow tests with the same description anymore). I can work on this if this is how we want to go.

**Comment by josevalim** [comment]
Yes, let's forbid duplicate describe blocks.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
