### ISSUE TITLE
Recursion in `with` with `else` isn't tail call optimized

### ISSUE THREAD

**Issue by Azolo** [elixir-lang/elixir#6251]
With Elixir 1.4.5 and Erlang 20

### Given a `with` with an `else` clause: 

```elixir
defmodule WithLoopDemo do
  def with_loop do
    receive do
      msg ->
        with :next <- msg do
          with_loop()
        else
          _ -> IO.puts "Not :next"
        end
    end
  end
end
```

The stack size increases with every recursive call.

```elixir
iex> pid = spawn(WithLoopDemo, :with_loop, [])
#PID<0.93.0>
iex> Process.info(pid, :stack_size)
{:stack_size, 1}
iex> send(pid, :next)                         
:next
iex> Process.info(pid, :stack_size)
{:stack_size, 2}
iex> send(pid, :next)              
:next
iex> send(pid, :next)
:next
iex> send(pid, :next)
:next
iex> send(pid, :next)
:next
iex> Process.info(pid, :stack_size)
{:stack_size, 6}
```

### A regular `with` clause:

```elixir
defmodule WithLoopDemo do
  def simple_with_loop do
    receive do
      msg ->
        with :next <- msg,
        do: simple_with_loop()
    end
  end
end
```

The `stack_size` is always `0`:

```elixir
iex> pid = spawn(WithLoopDemo, :simple_with_loop, [])
#PID<0.113.0>
iex> Process.info(pid, :stack_size)           
{:stack_size, 0}
iex> send(pid, :next)                         
:next
iex> Process.info(pid, :stack_size)
{:stack_size, 0}
iex> send(pid, :next)              
:next
iex> send(pid, :next)
:next
iex> send(pid, :next)
:next
iex> send(pid, :next)
:next
iex> send(pid, :next)
:next
iex> Process.info(pid, :stack_size)
{:stack_size, 0}
```

**Comment by josevalim** [comment]
Good catch. To fix this we will need to either repeat all else clauses on every case or return all bindings from the success case which is matched on a last case.

So take this `with`:

```elixir
with {:ok, a} <- foo(),
     {:ok, b} <- bar() do
  a + b
else
  {:a, a} -> return(a)
  {:b, b} -> return(b)
end
```

We can compile it to:

```elixir
case foo() do
  {:ok, a} ->
    case bar() do
      {:ok, b} -> a + b
      {:a, a} -> return(a)
      {:b, b} -> return(b)
    end
  {:a, a} -> return(a)
  {:b, b} -> return(b)
end
```

or:

```elixir
result =
  case foo() do
    {:ok, a} ->
      case bar() do
        {:ok, b} -> {:ok, a, b}
        other -> {:error, other}
      end
    other -> {:error, other}
  end

case result do
  {:ok, a, b} -> a + b
  {:error, {:a, a}} -> return(a)
  {:error, {:b, b}} -> return(b)
end
```

Any other ideas?

**Comment by michalmuskala** [comment]
I'm sure in the second case, later passes of the compiler will be able to eliminate the intermediary tuples (they eliminate them today). In the first proposal, the compiler should also be able to unify the clauses, but we'd be emitting much more code (with deeply nested `with`), so it could be slower to compile.

As a clarification, this is what the example José posted compiles to today (more-or-less):

```elixir
result =
  case foo() do
    {:ok, a} ->
      case bar() do
        {:ok, b} -> {:ok, a + b}
        other -> {:error, other}
      end
    other -> {:error, other}
  end

case result do
  {:ok, return} -> return
  {:error, {:a, a}} -> return(a)
  {:error, {:b, b}} -> return(b)
end
```

**Comment by Azolo** [comment]
I find the second example closer to what I used to work around. 

But I didn't need any variables from in side the `with` context. Just `:ok` or `{:error, reason}`.

Otherwise my workaround would have looked something like:

```elixir
def handle_event(x) do
  res = with {:ok, a} <- do_stuff(x),
             {:ok, b} <- do_other_stuff(a),
        do: {:ok, a, b}

  case res do
    {:ok, a, b} -> loop(x, a, b)
    {error, reason} -> terminate(x, a, b)
  end
end
```

I tried looking at [`elixir_with.erl`][1], but didn't quite wrap my head around how it built the AST. But from what @michalmuskala wrote I think that with an `else` clause the `with` AST just gets wrapped with `result = with_ast` and then adds the `case result` clause at the end.

My only idea is to reduce the difference between the `with` and `with..else` compilation. So, for example, with this code:

```elixir
with {:ok, a} <- foo(),
     {:ok, b} <- bar() do
  a + b
end
```

It compiles to something this:

```elixir
result =
  case foo() do
    {:ok, a} ->
      case bar() do
        {:ok, b} -> {:ok, a,  b}
        other -> {:error, other}
      end
    other -> {:error, other}
  end

case result do
  {:ok, a, b} -> a + b
  {:error, other} -> other
end
```

Compared to how the second example that @josevalim wrote, adding an `else` clause only changes how the `result` `case` is built.

There would be more overhead as the `with` is executing, but it would probably make the underlying AST easier to write.

[1]: https://github.com/elixir-lang/elixir/blob/ec9248e51d82c385e9450f35b85c63ec28c20405/lib/elixir/src/elixir_with.erl

**Comment by scottdavis** [comment]
S

**Comment by michalmuskala** [comment]
I evaluated a lot of different solutions:
* creating the intermediate tuple
* inserting error cases to each case
* using a private inline function for error cases
* using a private regular function for error cases

Out of all those, the nicest code is emited by the "private regular function" solution. For code like this:
```elixir
with {:ok, a} <- Map.fetch(map, :a),
     {:ok, b} <- Map.fetch(map, :b),
     {:ok, c} <- Map.fetch(map, :c),
     {:ok, d} <- Map.fetch(map, :d) do
  {:ok, a + b + c + d}
else
  :error -> {:ok, 0}   
  :err -> {:ok, 1} 
end
```
(yes, I know the `:err` case won't ever match, but I wanted to see how it would work with multiple patterns)

It would mean generating something like:
```elixir
def test3(map) do
  case Map.fetch(map, :a) do
    {:ok, a} ->
      case Map.fetch(map, :b) do
        {:ok, b} ->
          case Map.fetch(map, :c) do
            {:ok, c} ->
              case Map.fetch(map, :d) do
                {:ok, d} ->
                  {:ok, a + b + c + d}
                err ->
                  handle_err(err)
              end
            err ->
              handle_err(err)
          end
        err ->
          handle_err(err)
      end
    err ->
      handle_err(err)
  end
end

defp handle_err(err) do
  case err do
    :error -> {:ok, 0}
    :err -> {:ok, 1}
    _ -> raise WithClauseError
  end
end
```

The downside of this approach is much more complex code generation and an additional stacktrace entry for the "helper" function.

**Comment by michalmuskala** [comment]
I tried to do some benchmarking and here are the results: https://gist.github.com/michalmuskala/d039007fdb4fcb141fd3c8e9aeb6807e

The tuple-creating code is significantly slower (15%) and has higher deviation, probably because of the additional GC pressure. Even though the results are a bit messy (as is understandable in such tiny benches), the trend is clearly visible.

**Comment by michalmuskala** [comment]
I realised there's one more option - creating an anonymous function to match the errors. Unfortunately, that one is even slower than the "tuple" version.

**Comment by OvermindDL1** [comment]
How much of a slowdown is it in the error case's are fully duplicated and inlined into each case?

**Comment by michalmuskala** [comment]
That's going to depend entirely on the number of those cases and the size of them.

**Comment by OvermindDL1** [comment]
I'd lean toward the helper function with perhaps some descriptable name, like if the function the case is in is named `blah` and the case error is on line `12` then it's name could be like `$blah-errorcase-line12` or so.
