### ISSUE TITLE
Incorrect escaping of sigils in Inspect protocol

### ISSUE THREAD

**Issue by lpil** [elixir-lang/elixir#6255]
### Environment

Erlang/OTP 19
Elixir 1.4.5

### Current behaviour

I've been working a bunch with sigil escaping and I discovered that the Inspect protocol incorrectly prints some sigils with tricky escaping in them.

```elixir
iex(1)> ~r" \\/ "
~r/ \\/ /
iex(2)> ~r/ \\/ /
...(2)> # Sigil isn't complete!
```

### Expected behaviour

I expected this: `~r/ \\\/ /`

However when testing this happened, so I'm unsure:
```elixir
iex(1)> ~r/ \\\/ / == ~r" \\/ "
false
```
```elixir
iex(1)> quote do: ~r/ \\\/ /
{:sigil_r, [context: Elixir, import: Kernel], [{:<<>>, [], [" \\\\/ "]}, []]}
iex(2)> quote do: ~r" \/ "
{:sigil_r, [context: Elixir, import: Kernel], [{:<<>>, [], [" \\/ "]}, []]}
```

Is this parsing correctly?

**Comment by josevalim** [comment]
I believe it is parsing correctly. Call `.source` and that should make it clearer:

```iex
iex(2)> ~r/ \\\/ /.source
" \\\\/ "
iex(3)>  ~r" \\/ ".source
" \\\\/ "
```

**Comment by lpil** [comment]
I don't think this should be closed. It's parsing correctly but there is a bug in the Inspect protocol as it is printing sigils that are not valid Elixir syntax.

**Comment by NobbZ** [comment]
You have actually read the closing commit? It introduces some changes in the generation of escapes, also it has a test case with exactly your example. So in fact your reported issue is fixed in current master and can therefore be closed.

**Comment by lpil** [comment]
Ah, I didn't see there had been a commit, it wasn't obvious in the mobile GitHub UI. Thanks all :)
