### ISSUE TITLE
Calendar.ISO.naive_datetime_to_rata_die doesn't actually allow naive_date_time tuple as a parameter

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#6262]
I'm back on my favourite topic, calendars.  In refactoring my k-day lib to Elixir 1.5.0-rc.0 (with ERTS 9.0) I was surprised to find:
```
iex> {:ok, dt} = NaiveDateTime.new(2000, 1, 1, 23, 59, 59, 999_999)
{:ok, ~N[2000-01-01 23:59:59.999999]}
iex> Calendar.ISO.naive_datetime_to_rata_die dt                    
** (UndefinedFunctionError) function Calendar.ISO.naive_datetime_to_rata_die/1 is undefined or private. Did you mean one of:

      * naive_datetime_to_rata_die/7

    (elixir) Calendar.ISO.naive_datetime_to_rata_die(~N[2000-01-01 23:59:59.999999])
```
It may have been a design decision I missed during the review period but it would seem to be a bug that a method with that name doesn't actually allow a parameter of that type?

**Comment by josevalim** [comment]
@kipcole9 it is to avoid cyclic dependencies. Otherwise DateTime would call Calendar.ISO which would need to call or know how to build DateTime. If we are going to have such function, it should be rather part of the data type API. Glad to hear you are back!
