### ISSUE TITLE
Cannot compile PID/Reference in Elixir 1.5.0-rc.0

### ISSUE THREAD

**Issue by tv4-infrastruktur** [elixir-lang/elixir#6286]
When testing Elixir-1.5.0-rc.0 we ran into the "cannot compile PID/Reference inside quoted expression" error. We figured out a ugly workaround (see "working macro" test below) but this seems less than ideal.

Both tests work in Elixir 1.4 but only the "working macro" test in Elixir 1.5.0-rc.0.

Is this an expected behaviour and is there a better way to do this in 1.5.0?

When running the "broken macro" test we get the following output:
```
warning: cannot compile PID/Reference #PID<0.173.0> inside quoted expression for function send_to_caller/1
  test/warning_test.exs



  1) test broken macro (MacroWarningTest)
     test/warning_test.exs:49
     ** (MatchError) no match of right hand side value: :ok
     code: macro = broken_macro(:broken) do
     stacktrace:
       (elixir) src/elixir_expand.erl:543: :elixir_expand.expand_arg/2
       (stdlib) lists.erl:1354: :lists.mapfoldl/3
       (elixir) src/elixir_expand.erl:552: :elixir_expand.expand_args/2
       (elixir) src/elixir_expand.erl:633: :elixir_expand.expand_remote/7
       (elixir) src/elixir_clauses.erl:19: :elixir_clauses.def/2
       (elixir) src/elixir_def.erl:138: :elixir_def."-store_definition/10-lc$^0/1-0-"/2
       (elixir) src/elixir_def.erl:138: :elixir_def.store_definition/10
       test/warning_test.exs:50: (module)
       (elixir) src/elixir_compiler.erl:85: :elixir_compiler.dispatch/6
       (elixir) src/elixir_module.erl:230: :elixir_module.eval_form/6
       (elixir) src/elixir_module.erl:73: :elixir_module.compile/5
       (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/3
       test/warning_test.exs:50: (test)
```

Sample test case:
```elixir
defmodule MacroWarningTest do
  use ExUnit.Case

  defmacro working_macro(module_name, do: code) do
    quote do
      defmodule unquote(module_name) do
        @test_pid_string inspect(self())

        def send_to_caller(message) do
          send(test_pid(), message)
        end

        defp test_pid do
          [[_, pid_string]] = Regex.scan(~r/#PID<([0-9]+\.[0-9]+\.[0-9]+)>/, @test_pid_string)
          pid = IEx.Helpers.pid(pid_string)
        end

        unquote(code)
      end
      unquote(module_name)
    end
  end

  test "working macro" do
    macro = working_macro(:working) do
      def do_stuff, do: send_to_caller(:done_stuff)
    end

    macro.do_stuff()
    assert_received(:done_stuff)
  end

  defmacro broken_macro(module_name, do: code) do
    quote do
      defmodule unquote(module_name) do
        @test_pid self()

        def send_to_caller(message) do
          send(@test_pid, message)
        end

        unquote(code)
      end
      unquote(module_name)
    end
  end

  test "broken macro" do
    macro = broken_macro(:broken) do
      def do_stuff, do: send_to_caller(:done_stuff)
    end

    macro.do_stuff()
    assert_received(:done_stuff)
  end
end
```

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.5.0-rc.0 (fa0de7786)
MacOS 10.12.5

We saw that the change was introduced in 767f7ee2bb3f91890a629f51a3569468779120c9.

**Comment by ericmj** [comment]
Maybe this is just example code but why are compiling PIDs used during compilation into the code? It would be better to grab this pid at runtime which you can also hide with a macro, why do you need the pid at compile time?

**Comment by josevalim** [comment]
As @ericmj said, using a pid at compile time is a bug, as there is no guarantee the PID is the same during runtime. You also shouldn't rely on `inspect`, as it is meant to represent data structures for users, and it can also change at any time.

If you really really really want to serialize a PID, then use `erlang:term_to_binary/1` and `erlang:binary_to_term/1`, but should really reconsider your approach, as PIDs are intrinsically ephemeral and may no longer exist once deserialized.

**Comment by josevalim** [comment]
In any case, thank you for the report and for trying the RC out!
