### ISSUE TITLE
v1.5.0-rc.0 Map.equal? exception behaviour has changed

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#6288]
### Environment

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0-rc.0 (0391b12)

Ubuntu Xenial 16.04

### Current behaviour

One of my tests picked this up:

`Map.equal?(%{a: 1}, [])`

raises a BadMapError exception:

> ** (BadMapError) expected a map, got: []
    (elixir) lib/map.ex:861: Map.equal?(%{a: 1}, [])

### Expected behaviour

v1.4.5 raises a FunctionClauseException

> ** (FunctionClauseError) no function clause matching in Map.equal?/2
    (elixir) lib/map.ex:793: Map.equal?(%{a: 1}, [])

I think the change is "better" (more consistent with other Map functions) so maybe just an entry in the release notes?

**Comment by josevalim** [comment]
Yes, let's make those changes explicit even though developers shouldn't be relying on function_clause, case_clause and badarg errors. Thanks!

**Comment by ianrumford** [comment]
I understand your point about looking at exceptions but disagree.

In this case my code had "wrapped" Map.equal? and my test was to ensure I had not changed the semantics of Map.equal?

But if we should not be looking at Exception why does Elixir have BadMapError, CaseClauseError, FunctionClauseError, etc exceptions at all? Why not just one AnExceptionError? :-)  (Rhetorical by the way).

**Comment by josevalim** [comment]
> But if we should not be looking at Exception why does Elixir have BadMapError, CaseClauseError, FunctionClauseError, etc exceptions at all? Why not just one AnExceptionError? :-) (Rhetorical by the way).

Even though it is rhetorical, many follow the issues tracker, so being explicit is worth it: the different kind of exceptions is to provide more information for debugging and not to be a mechanism for the caller of the code to perform control flow.

**Comment by ianrumford** [comment]
I know its not the Elixir way to use exceptions for flow control but I've found that sometimes that is the only way I can find to make an unambiguous decisions.  

For example there appears to be no unambiguous way to determine if a value is enumerable? (This is another issue I've just seen where the exception behaviour - in Enum.to_list - is different in 1.5.)

Do I open another issue where the exception behaviour has changed but really I'm trying to find out whether a value is enumerable?

**Comment by ericmj** [comment]
> For example there appears to be no unambiguous way to determine if a value is enumerable? 

You can check with `Enumerable.impl_for(MyType) != nil`.

**Comment by ianrumford** [comment]
Thanks Eric, aware of impl_for.  In my code though (albeit written some time ago) I have a comment which suggested that impl_for wasn't 100% comprehensive.  I need to go back and review that code, comment and use case, and craft an example against 1.5.

**Comment by josevalim** [comment]
> I know its not the Elixir way to use exceptions for flow control but I've found that sometimes that is the only way I can find to make an unambiguous decisions.

So please open up an issue in those cases because it means our API is incomplete. :)

**Comment by josevalim** [comment]
> This is another issue I've just seen where the exception behaviour - in Enum.to_list - is different in 1.5.

Please file a bug here too. In the best scenario we will make it explicit in the CHANGELOG. In the worst scenario we will close it (but still appreciate the reporting). :)

**Comment by ianrumford** [comment]
Opened two new issues.

**Comment by whatyouhide** [comment]
Closed in 75f6af7.
