### ISSUE TITLE
v1.5.0-rc.0 Enum.to_list exception behaviour has changed when passed a fun

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#6289]
### Environment

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0-rc.0 (0391b12)
Ubuntu Xenial 16.04

### Current behaviour

An obscure case but Jose asked me to file a report.

Passing a simple function to Enum.to_list:

`fn x -> x end |> Enum.to_list`

raises

> ** (BadArityError) #Function<6.99386804/1 in :erl_eval.expr/5> with arity 1 called with 2 arguments ({:cont, []}, #Function<147.79927189/2 in Enum.reverse/1>)
    (elixir) lib/enum.ex:3196: Enumerable.Function.reduce/3
    (elixir) lib/enum.ex:1833: Enum.reverse/1
    (elixir) lib/enum.ex:2582: Enum.to_list/1

### Expected behaviour

In v1.4.5 the exception is:

> ** (FunctionClauseError) no function clause matching in Enumerable.Function.reduce/3
    (elixir) lib/enum.ex:3113: Enumerable.Function.reduce(#Function<6.99386804/1 in :erl_eval.expr/5>, {:cont, []}, #Function<143.113552552/2 in Enum.reverse/2>)
    (elixir) lib/enum.ex:1776: Enum.reverse/2
    (elixir) lib/enum.ex:2528: Enum.to_list/1

I think the v1.4.5 exception is more helpful.

**Comment by ericmj** [comment]
This should be documented in the changelog but the behaviour should stay the same, see #6288 for the reason.

**Comment by whatyouhide** [comment]
Closed (documented in CHANGELOG) by @josevalim in https://github.com/elixir-lang/elixir/commit/f94477b2ef30e34f6b75af5e9afb618e3bffee60.
