### ISSUE TITLE
Enumerable.impl_for returns non nil for a simple fun

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#6291]
### Environment

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0-rc.0 (0391b12)

Ubuntu Xenial 16.04

### Current behaviour

A simple function passed to Enumerable.impl_for returns a non nil
result (Enumerable.Function) i.e the function is enumerable.

`f1 = fn -> :hello_world end; f1 |> Enumerable.impl_for`

returns Enumerable.Function

But f1 is not really enumerable as shown by

`f1 |> Enum.to_list`

which raises

> ** (BadArityError) #Function<20.99386804/0 in :erl_eval.expr/5> with arity 0 called with 2 arguments ({:cont, []}, #Function<147.79927189/2 in Enum.reverse/1>)
    (elixir) lib/enum.ex:3196: Enumerable.Function.reduce/3
    (elixir) lib/enum.ex:1833: Enum.reverse/1
    (elixir) lib/enum.ex:2582: Enum.to_list/1

### Expected behaviour

The same behaviour in v1.4.5  but the exception is different (FunctionClauseError) (In fact I first saw this in March 2016)

### Background

A function can be enumerable  e.g.

`defmodule Misc99 do

  f2 = Stream.flat_map([1,2,3], fn x -> [x,x] end)

  true = is_function(f2)

  Enumerable.Function = f2 |> Enumerable.impl_for

  f2 |> Enum.to_list
  |> Enum.map(&IO.puts/1)
  
end`

**Comment by ericmj** [comment]
`MyProtocol.impl_for` will return the protocol implementation for the given value's type. It does not mean that there will be an implementation for every possible value of that type.

Will close because #6289 already covers the documentation issue.

**Comment by michalmuskala** [comment]
I guess it would be nice if the `Function` implementation of `Enumerable` raised `Protocol.UndefinedError` in the case of bad arity the same way that the `BitString` implementation of `String.Chars` does when faced with a bistring that is not a binary.

**Comment by ianrumford** [comment]
Eric that doesn't help.

I opened this issue to demonstrate that I could not find a way to 100% correctly determine whether a value was enumerable.  Jose made the point that I should do so because:

> So please open up an issue in those cases because it means our API is incomplete. :)

If you remember from my original issue (6289), I said  I used an Enum.to_list in a try rescue clause to dertmine if a value was enumerable. Hence I used the exception to control flow. Hence I needed the same exception in 1.5 to make the decision. Hence why the change in 1.5 mattered.

You seem to be confirming that Elixir does *not* have a 100% accurate way to test if a value is enumerable?  Have I got you wrong? Have I got Jose wrong? Please explain.

**Comment by ianrumford** [comment]
I would like this issue reopened please. (I do not have the authority to do so?)

**Comment by ericmj** [comment]
> I opened this issue to demonstrate that I could not find a way to 100% correctly determine whether a value was enumerable.

It is not possible to determine with 100% certainty if a given value is enumerable since it depends on the internals of protocol implementations that neither the standard library or the user has control of since any library can make their implementations. For example I can implement Enumerable for a streaming database cursor, if the database connection goes down should Enumerable.impl_for return nil?

> If you remember from my original issue (6289), I said I used an Enum.to_list in a try rescue clause to dertmine if a value was enumerable. Hence I used the exception to control flow. Hence I needed the same exception in 1.5 to make the decision. Hence why the change in 1.5 mattered.

This is not a valid argument since you shouldn't use exceptions for control flow and we make no guarantees about what exception will be raised so this is not a breaking change.

**Comment by ianrumford** [comment]
Simple question: If I have a value how do I test whether it is enumerable without using try/catch/exceptions? Literally, what code do I write?

**Comment by ericmj** [comment]
As I have said, you can check if the type of value can be enumerable but you can't check if an arbitrary value is enumerable since enumerating that  arbitrary value can crash for whatever reason that is beyond our control.

**Comment by OvermindDL1** [comment]
Some bikeshedding so feel free to ignore this, but what if protocols had a, oh, `protocol_valid?` optional method on a `defimpl` that could be passed the value to test if it is valid, and if it does not exist it just default returns 'true'.

**Comment by ericmj** [comment]
How do you define if a protocol is valid? As I showed previously you may not know for enumerables until you actually try to enumerate it.

**Comment by OvermindDL1** [comment]
> How do you define if a protocol is valid? As I showed previously you may not know for enumerables until you actually try to enumerate it.

Exactly, that is why it is optional (defaulting to the current style of 'yes it is valid regardless).  If it is untestable then just assume it is valid, but otherwise if it is testable then allow it to be tested.

**Comment by ianrumford** [comment]
Eric, thanks for the response.

So it is impossible in Elixir to test whether a value is enumerable without using try/catch/exceptions.

**Comment by ericmj** [comment]
> So it is impossible in Elixir to test whether a value is enumerable without using try/catch/exceptions.

Yes.

I reopened the issue because I think @michalmuskala's idea about raising `Protocol.UndefinedError` if the function arity is wrong was a great idea.

**Comment by ianrumford** [comment]
Fantastic! If that's the way forward to help deliver on Jose's aspiration that you don't need exceptions for flow control in Elixir, what's not to like.

**Comment by josevalim** [comment]
@ianrumford just to clarify, it is ok to rely on it when it is part of the public contract such as Protocol.UndefinedError or when you just rescue everything. It is not ideal, but ok. The issue is that some exceptions like ArgumentError, FunctionClauseError, CaseClauseError are almost always an implementation detail and can change any time.

**Comment by ianrumford** [comment]
Thanks for the feedback Jose but I think its regrettable that Elixir considers the exceptions raises to be ephemeral implementation details.

To me software failure modes (including exceptions raised) are just as much part of the contract as the success modes.

But, as Zach Tellman insightfully remarked,

> we should understand that when someone shares their source code, they didn’t necessarily make it for us.

Best Regards.
