### ISSUE TITLE
v 1.5.0-rc.0 Macro Wrapped Function With Rescue Block Emits Compiler Error

### ISSUE THREAD

**Issue by asummers** [elixir-lang/elixir#6295]
### Environment

* Elixir & Erlang versions (elixir --version): 

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.0-rc.0 (fa0de7786)

* Operating system: 
OSX 10.12.3

### Current behavior

Starting with Elixir 1.5 rc0, a macro from one of our dependencies is no longer working when using `rescue`. It's possible the dependency is doing something strange, though digging through its code I could not see anything immediately off hand that would cause this behavior. This was previously confirmed working from 1.4.2->1.4.5.

https://github.com/arjan/decorator/issues/11 is the relevant issue with the dependency, including stack trace and example code. It appears from https://github.com/elixir-lang/elixir/issues/6287 that `rescue` has some other issues, so my suspicion is that they're both related in some capacity, though that's not based in evidence. It also appears that `rescue` blocks combined with macros have had issues with upstream Erlang changes in the past, though the relevant issues around that seem to all be closed from what I can see.

Please let me know if I can provide any other supporting details. If this is an issue with Elixir itself, I can transpose those details here and close the associated issue with the dependency.

### Expected behavior

The code compiles without error.

**Comment by josevalim** [comment]
This is the same issue as #6298. We have properly documented the change.

**Comment by josevalim** [comment]
Thank you for reporting! :heart:
