### ISSUE TITLE
v1.5.0.rc-0 quoted body passed to Module's on_definition callback is now [do: body]

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#6298]
### Environment

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.5.0-rc.0 (0391b12)
Ubuntu Xenial 16.04

### Current behavior

Below is the output from running the (v1.4.5) example from Module of using the on_definition callback:

> Defining def named hello with args:
[{:arg, [line: 28], nil}]
and guards
[{:or, [line: 28],
  [{:is_binary, [line: 28], [{:arg, [line: 28], nil}]},
   {:is_list, [line: 28], [{:arg, [line: 28], nil}]}]}]
and body
[do: "Hello" <> to_string(arg)]
Defining def named hello with args:
[{:_, [line: 32], nil}]
and guards
[]
and body
[do: :ok]

Note e.g. the two lines:

> and body
[do: "Hello" <> to_string(arg)]

### Expected behavior

In v1.4.5 the output is:

> Defining def named hello with args:
[{:arg, [line: 28], nil}]
and guards
[{:or, [line: 28],
  [{:is_binary, [line: 28], [{:arg, [line: 28], nil}]},
   {:is_list, [line: 28], [{:arg, [line: 28], nil}]}]}]
and body
"Hello" <> to_string(arg)
Defining def named hello with args:
[{:_, [line: 32], nil}]
and guards
[]
and body
:ok

Note e.g. the two lines:

> and body
"Hello" <> to_string(arg)

I guess the change is to support full do/rescue/catch/after bodies (which is good).  In that case, it does need to be documented as a breaking change.

**Comment by josevalim** [comment]
Yes, it is a bug fix as we were losing information in the previous one. We will probably document it. Thank you.

**Comment by josevalim** [comment]
To be clear, the information we were losing is that it was impossible to distinguish between a bodyless clause and a function that returns nil.

**Comment by josevalim** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:
