### ISSUE TITLE
1.5.0-rc.0: error when defining an overridable function with defaults

### ISSUE THREAD

**Issue by paulswartz** [elixir-lang/elixir#6300]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.0-rc.0 (fa0de77)
```
* Operating system: locally, OS X 10.12.5: remote, whatever Travis has
* Repo: https://github.com/paulswartz/undefined_overridable
* Travis build: https://travis-ci.org/paulswartz/undefined_overridable

### Elixir 1.4.5

```
$ mix compile
Compiling 2 files (.ex)
Generated undef app
```

### Elixir 1.5.0-rc.0

```
$ mix compile
Compiling 2 files (.ex)

== Compilation error in file lib/undef.ex ==
** (CompileError) lib/undef.ex:6: undefined function func (overridable 1)/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

**Comment by paulswartz** [comment]
:+1: thanks!

**Comment by josevalim** [comment]
And thank you for the report and the mechanism to reproduce the issue, it makes our lives much much easier!
