### ISSUE TITLE
Cleanup Enum and Stream chunk APIs

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6301]
Today `Enum.chunk/4` has a very big flaw in that it discards data by default, which is not consistent with `chunk_by` and a bad default altogether. To make matters worse, when passing four arguments, we use `nil` to enable the discarding behaviour: `chunk(enum, 2, 2, nil)`.

Here we propose two new functions to add to `Enum`:

  * [x] `Enum.chunk_every/4` - chunks every element. Equivalent to today's `chunk/4` except that it does not discard chunks by default and the discarding behaviour will be done by passing `chunk_every(enum, 2, 2, :discard)`. The name reflects the `take_every` and `drop_every` which are also by position 

  * [ ] `Enum.chunk_on/2` - creates a new chunk every time the given function returns true. Should be easily created on top of the existing `Enum.chunk_while/4`. The difference between `chunk_on` and `chunk_by` is that the latter creates a new chunk every time the value changes and `chunk_on` happens every time true is returned

  * [x] Besides, we should rename `chunk_by/4` (unreleased) to `chunk_while/4` as it is closer to `reduce_while/4`.

**Comment by josevalim** [comment]
So I have ran into a wall. Should `chunk_on` start a new chunk BEFORE or AFTER the functions returns true?

```elixir
[1, 1, 1, 2, 7, 7, 2, 8, 9] |> Enum.chunk_on(& &1 == 2)
# => [[1, 1, 1, 2], [7, 7, 2], [8, 9]]
[1, 1, 1, 2, 7, 7, 2, 8, 9] |> Enum.chunk_on(& &1 == 2)
# => [[1, 1, 1] [2, 7, 7], [2, 8, 9]]
```

We should probably introduce `chunk_before` and `chunk_after` but given both can be expressed with the low-level `chunk_while/4`, maybe that's enough?

**Comment by Qqwy** [comment]
I think that `chunk_before` and `chunk_after` are more descriptive names.

Personally, I'd think that `chunk_on` would return the following:
```elixir
[1, 1, 1, 2, 7, 7, 2, 8, 9] |> Enum.chunk_on(& &1 == 2)
# => [[1, 1, 1], [7, 7], [8, 9]]
```
Which is, remove the boundary values all together. (Basically similar to what `String.split/2` does for binaries)

**Comment by josevalim** [comment]
Closing this for now. Let's wait for more feedback before implementing chunk_after and chunk_before since both can be implemented today with chunk_while.
