### ISSUE TITLE
mix run --no-start cant find .app files

### ISSUE THREAD

**Issue by TBK145** [elixir-lang/elixir#6303]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

IEx 1.5.0-rc.0 (fa0de77)
```
* Operating system: Ubuntu 16.04

### Current behavior

When running `iex -S mix run --no-start` and then trying to start an application, Elixir can't find the .app file:
```
$ iex -S mix run --no-start
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

Interactive Elixir (1.5.0-rc.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Application.start :timex
{:error, {'no such file or directory', 'timex.app'}}
```
However, the file does exist.

The problem only occurs when using `run --no-start`, using `iex -S mix phoenix.server --no-start` and `iex -S mix run` do not produce the error.

### Expected behavior

For Elixir to find the .app files.

**Comment by ericmj** [comment]
I believe the bug is here https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/run.ex#L84-L88 because it is app.start that adds the codepaths. We should be able to always call app.start from run since app.start will also check the --no-start flag.
