### ISSUE TITLE
`mix do` doesn't parse command parameters

### ISSUE THREAD

**Issue by whysoserious** [elixir-lang/elixir#6306]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.5
```
* Operating system: 
```
Ubuntu 16.04.2 LTS
```

### Current behavior

The command below does not drop `Other.Repo`.
```
$ mix do ecto.drop, ecto.drop --repo Other.Repo
The database for My.Repo has been dropped
```
Both `Other.Repo` and `My.Repo` did exist before invoking this command.

It looks like `--repo Other.Repo` is not parsed properly by `mix`.

### Expected behavior

```
$ mix do ecto.drop, ecto.drop --repo Other.Repo
The database for My.Repo has been dropped
The database for Other.Repo has been dropped
```

**Comment by josevalim** [comment]
Mix tasks are designed to run only once, so the second time you call ecto.drop it is skipped. Do this instead:  `mix ecto.drop --repo My.Repo --repo Other.Repo`. A PR to Ecto that makes it clear --repo can be passed multiple times is welcome!
