### ISSUE TITLE
Expand "with" into cases when translating to Erlang instead of during expansion

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6317]
That's because backends may be able to emit better code if they have the whole `with` AST.

@bryanjos - this means you will need to change ElixirScript to consider `with`. However, no need to worry for now, this is targeted to v1.6 only.

**Comment by josevalim** [comment]
Actually, we need to do it now if we want to fix #6251 efficiently. So retargetting it to v1.5.0 and including it as part of the former. Please take notes @bryanjos :)

**Comment by bryanjos** [comment]
@josevalim thanks, I'll be sure to implement it in ElixirScript
