### ISSUE TITLE
URI.path_to_segments result ordering

### ISSUE THREAD

**Issue by asd1o2487c** [elixir-lang/elixir#6327]
### Environment

Erlang/OTP 20
Elixir 1.4.5
macOS

### Current behavior

```elixir
iex(1)> URI.path_to_segments "/aa//a/asdf///fe/r//sd////"
["", "sd", "r", "fe", "asdf", "a", "aa", ""]
```

### Expected behavior
```elixir
iex(1)> URI.path_to_segments "/aa//a/asdf///fe/r//sd////"
["", "aa", "a", "asdf", "fe", "r", "sd", ""] # or ["aa", "a", "asdf", "fe", "r", "sd"]
```

That is, the segments are in the reverse order. Or is it intentional?

**Comment by asd1o2487c** [comment]
Also, `URI.path_to_segments` performs [worse](https://github.com/asd1o2487c/bench) then
```elixir
for segment <- :binary.split("/aa//a/asdf///fe/r//sd////", "/", [:global]), segment !== "" do
  segment
end
``` 
Maybe it should be replaced with a for comprehension?

**Comment by ericmj** [comment]
This was an undocumented function that was accidentally changed from `defp` to `def` earlier. It has now been changed back to private in 1.5.0 since it was never documented.
