### ISSUE TITLE
Unexpected mix deps :optional behavior

### ISSUE THREAD

**Issue by wpcarro** [elixir-lang/elixir#6333]
### Current behavior

I have an application, A, that depends on an application that is configured in A's `config.exs`.

```elixir
  defp deps do
    [
      {:some_dependency, "~> 1.0.0", optional: true},
    ]
  end
```

I created a new application, B, that depends on application A. B does not need the dependency that's configured in A's `config.exs`. Therefore in A's `config.exs` it's marked as `optional: true`. This works great for application B.

The problem is that when I run application A, I get warnings logged that look like:

```
You have configured application :some_dependency in your configuration
file, but the application is not available.

This usually means one of:

1. You have not added the application as a dependency in a mix.exs file.

2. You are configuring an application that does not really exist.

Please ensure :some_dependency exists or remove the configuration.
```

I'm surprised by this behavior given my understanding of the `:optional` setting:

> In such cases, the current project will always include the optional dependency but any other project that depends on the current project won’t be forced to use the optional dependency

I would expect that since "...the current project will always include the optional dependency..." not to see the lines:

> You have not added the application as a dependency in a mix.exs file.

or

> You are configuring an application that does not really exist.

I'm trying to figure out what I don't understand about `:optional`'s behavior.

### Environment

* Elixir: 1.4.5
* Erlang/OTP: 20

**Comment by josevalim** [comment]
@wpcarro can you please provide a sample application that reproduces the error? Because I just did the steps in the issues above and I could not get any warning. Thank you.

**Comment by wpcarro** [comment]
Repro. steps:

## Project A
1. Create Umbrella app
2. Create TestA as a sub-app in Umbrella
3. Require `:sentry` as a dependency and use the default config provided on their GH page:

```elixir
# inside of apps/test_a/mix.exs
  defp deps do
    [
      {:sentry, "~> 5.0.0", optional: true},
    ]
  end
```

```elixir
# inside of apps/test_a/config/config.exs

config :sentry,
  dsn: "https://public:secret@app.getsentry.com/1",
  environment_name: :prod,
  included_environments: [:prod],
  enable_source_code_context: true,
  root_source_code_path: File.cwd!,
  tags: %{
    env: "production"
  },
  hackney_opts: [pool: :my_pool],
  in_app_module_whitelist: [MyApp]
```

## Project B
1. Create TestB as a separate app entirely
2. Require TestA as a dependency in TestB

```elixir
# inside test_b/mix.exs
  defp deps do
    [
      {:test_a, path: "../umbrella/apps/test_a"}
    ]
  end
```

This should cause `Project B` to work just fine. When you run `Project A` you should expect to see a warning logged.

**Comment by josevalim** [comment]
I could partially reproduce this. The error happens when I run from the umbrella root, not from inside "test a". Is this correct?

**Comment by josevalim** [comment]
Btw, the issue is exactly because the umbrella does not load the optional dependencies and then end-up pruning the optional dependency entries from `_build`. We can either force optional dependencies to be brought or not allow umbrella apps to prune dependencies. I am more inclined towards the latter.

**Comment by josevalim** [comment]
A temporary fix is to set `build_path: "_build"` inside `def project` in your umbrella `mix.exs` file.

**Comment by wpcarro** [comment]
> The error happens when I run from the umbrella root, not from inside "test a". Is this correct?

This is correct. 

> A temporary fix is to set build_path: "_build" inside def project in your umbrella mix.exs file.

The workaround works just fine. I appreciate the explanation about optional dependency pruning. I also agree with preventing umbrella apps from pruning dependencies.

I'm slightly confused about why setting `build_path: "_build"` from the umbrella's `mix.exs` works. Was `build_path`'s value `nil` prior with no defaults? I would imagine it defaulted to `"_build"` already. Is there any documentation you can point me to so that I can understand more about this issue?

**Comment by josevalim** [comment]
@wpcarro the fact that setting the build_path to "_build" works is an implementation detail and work around you should not rely on. It will likely be fixed when we fix this issue too. :)

**Comment by kelvinst** [comment]
> We can either force optional dependencies to be brought or not allow umbrella apps to prune dependencies.

Doing the second one here. :wink:
