### ISSUE TITLE
Add mix test --slowest N which prints slowest N tests

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6334]
This will be really helpful to debug slow tests in a suite. The value will be printed at the end of the test suite. The test suite execution itself won't be altered.

**Comment by sorentwo** [comment]
Is this up for grabs? If so, I'd like to tackle it.

**Comment by josevalim** [comment]
Yes, it is. :)

**Comment by josevalim** [comment]
Btw, --slowest should imply --trace, because you won't get proper times if you are running tests concurrently.
