### ISSUE TITLE
1.5.0-rc1 `child_spec/1` for `Consumer` passes the entire keyword list to `Consumer.start_link/1`

### ISSUE THREAD

**Issue by seivan** [elixir-lang/elixir#6342]
Although I'm getting this issue with `GenStage`, I'd thought the ticket would be appropriately put here since it's related to how `child_spec/1` is supposed to work. 
 
### Environment

* Elixir & Erlang versions (elixir --version):  `1.5.0-rc1`
* Operating system:  `Mac OS Sierra 10.12.5`

### Current behavior

When using `worker(Consumer, [:my_argument_to_init], id: 2)`    the `[id: 2]`  won’t be passed as an  argument  `Consumer.start_link/1`  however with `1.5.0-rc1` new `{module, arg}` tuple for child specs like e.g  `{Consumer, [ :my_argument, [id: 1] ] }`   the entire list is passed as an argument to `Consumer.start_link/1` which breaks existing behaviour. 

### Expected behavior

With 
```elixir
{Consumer, [ :my_argument, [id: 2] ] }
```
I expect the same argument to `Consumer.start_link/1` as I would have gotten from 

```elixir
worker(Consumer, [:my_argument_to_init], id: 2)
```

I don't expect `[id: 1]` to be passed to `Consumer.start_link/1` with the new `{module, arg}` `child_spec/1` syntax. 

This breaks existing code that expects that  `worker(Consumer, [:my_argument_to_init], id: 2)` will pass *only* `: my_argument_to_init` as `arg` to `Consumer.start_link/1`

Looking at https://github.com/elixir-lang/gen_stage/blob/master/lib/gen_stage.ex#L1030 you can see that arg isn't filtering out Supervisor keywords like `:id` for instance.

**Comment by josevalim** [comment]
Hi @seivan!

I am glad to see people using Elixir's v1.5 child specs. Keep in mind, however, that they are not equivalent. One of the things we tried to fix with child_spec/1 is exactly this "arguments" dance that we had with `worker`, which was very confusing. Therefore, you always want to call `{Consumer, :my_argument_to_init}` and `start_link/1` is always called.

If you need to customize child spec data such as ID, then you can do so by calling `Supervisor.child_spec/2`:

    Supervisor.child_spec {Consumer, :my_argument_to_init}, id: 2

**Comment by seivan** [comment]
@josevalim Sorry, but this is still pretty confusing. I see now that the exception message contains the tidbit about `Supervisor.child_spec/2`, but what's proper way of implementing `child_specs/1`  for packages that could for instance, expect multiple versions of itself (so it would require `:id`) 

In other words, would you say this is the wrong approach? 

```elixir
  def child_spec(arg) do
    #assume arg has been cleaned up so this fits expectations for now. 
    {arguments, options, supervisor_options} = {arg |> Enum.at(0), 
                                                arg |> Enum.at(1),
                                                arg |> Enum.at(2)
                                              }

    %{
      id: supervisor_options[:id] || __MODULE__,
      start: {__MODULE__, :start_link, [arguments, options]},
      type: :worker
    }
  end
```

In other words, this would let the user of said package void calling `Supervisor.child_spec/2` and instead just rely on `{Module, Tuple}` syntax which btw is a great addition 👍

**Comment by josevalim** [comment]
You can implement your custom child_spec as above and that would work. But our choice was exactly to *not couple those*. Keep the arguments in the tuple and allow customization via an explicit child_spec/2 call. But, at the end of the day, it is your choice.
