### ISSUE TITLE
Mix Compile custom compiler Github depdency Issue

### ISSUE THREAD

**Issue by IRog** [elixir-lang/elixir#6350]
### Environment

* Elixir & Erlang versions (elixir --version): 
* Operating system: 
Elixir 1.4.5
Mac OS Sierra
### Current behavior
`mix deps.compile ejabberd` doesn't seem to use compile ejabberd correctly when listed as a github dependency, but works fine when using the dependency in path i.e. `{:ejabberd, path: "../ejabberd"}`. The exact same code are in the file system and on github.

To test:

```Elixir
defmodule ModMix.Mixfile do
  use Mix.Project

  def project do
    [app: :mod_mix,
     version: "0.1.0",
     elixir: "~> 1.4",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

  def application do
    [extra_applications: [:logger, :ejabberd]]
  end

  defp deps do
    [
      {:ejabberd, git: "https://github.com/IRog/ejabberd.git", branch: "fixIex"}
    ]
  end
end
```

While with the same Mixfile pointing to that branch on the local file system, there are no compilation issues. Unfortunately, due to the vague error messages, I'm not quite sure why it's failing as a github dependency. My only guess is that 1 of the following is causing issues:

(mix file from the ejabberd project)
```elixir
compilers: [:asn1] ++ Mix.compilers,
     erlc_options: [:debug_info, {:i, "deps/fast_xml/include"}, {:i, "deps/p1_utils/include"}, {:i, "deps/xmpp/include"}],
```
I think either the erlc_options aren't being used and/or the asn1 compiler is also not being used. I'm guessing that there aren't many mixed Erlang/Elixir projects used as dependencies with these options, so this could maybe be a bug. Sorry about any lack of detail, but that's all the information I have. Feel free to ask me anything else, though!

### Expected behavior
There is no difference in using a dependency on the filesystem vs on github.

**Comment by josevalim** [comment]
@IRog can you please post your full stacktrace? We need to reproduce the issue and it is hard to reproduce it if we don't know which error you are getting.

**Comment by josevalim** [comment]
In any case, I think your hunch is correct. The issue is in ejabberd. If I change the `erlc_options` to point to the proper deps then it works on my machine as expected:

```elixir
   erlc_options: [:debug_info, {:d, :ELIXIR_ENABLED} | erl_includes()]

    defp erl_includes do
      for {app, path} <- Mix.Project.deps_paths,
          app in [:fast_xml, :p1_utils, :xmpp],
          do: {:i, Path.join(path, "include")}
    end
```

**Comment by IRog** [comment]
I have created https://gist.github.com/IRog/db52526eba186881959131aba47478be which shows the stacktrace for when the dependency is retrieved via git. There are lines like `src/mod_version.erl:40: can't find include file "xmpp.hrl"` which leads me to believe it's ignoring the 
```elixir
erlc_options: [:debug_info, {:i, "deps/fast_xml/include"}, {:i, "deps/p1_utils/include"}, {:i, "deps/xmpp/include"}],
```
in the forked ejabberd mix file. I am aware of the issues with ejabberd core. This is to address the fact that I can compile the dependency just fine when using the `:path` option and it's on my filesystem, but it fails when retrieved with git with the exact same codebase and erlc_options. @josevalim

**Comment by josevalim** [comment]
@IRog it only works on a path dependency because the path dependency has a deps directory. If you erase its deps directory (a clean checkout), it will no longer work.

It is not a Mix bug. The project is assuming a certain directory layout and if that layout happens to be there, then it works by accident.

**Comment by IRog** [comment]
Thanks. Do you happen to know how to work-around this behavior other than using the file system version? I tried using a custom `compile: 'mix do deps.get, compile` but that didn't seem to work. Any place to look in the code would also be welcome! (I still haven't really looked at Elixir source)

Thanks, again!

**Comment by josevalim** [comment]
The proper solution is the one in my second comment. ejabberd needs to properly detect the paths instead of hardcoding them.
