### ISSUE TITLE
`not in` description in 1.5 changelog

### ISSUE THREAD

**Issue by pikeas** [elixir-lang/elixir#6351]
From https://github.com/elixir-lang/elixir/blob/v1.5/CHANGELOG.md:

    [Kernel] not left in right is soft-deprecated in favor of left not in right

Under Elixir 1.4.5, `not in` does not compile: `** (SyntaxError) my_file.ex:12: syntax error before: in`.

In other words, there's a second, currently undocumented change - `not in` is also a new guard condition (operator?).

**Comment by josevalim** [comment]
Yes, you are correct. I will add it to the CHANGELOG, thank you!
