### ISSUE TITLE
"Unchecked dependencies for environment" within umbrella apps and only: deps

### ISSUE THREAD

**Issue by xadhoom** [elixir-lang/elixir#6359]
### Environment

* elixir-1.4.5 / 1.5.0-rc.1 with OTP-20
* Operating system: Linux fedora 26

### Current behavior

In an umbrella project, when subapp1 depends on subapp2, and subapp1 has a :test only dep on an external package which is also a "normal" dep in subapp2, running mix deps.get or mix test inside subapp1 results in `Unchecked dependencies for environment test:` which suggests to remove the :only restriction in subapp1.
If same is run inside the toplevel umbrella, everything works as expected

Sample repo here: https://github.com/xadhoom/test_deps

### Expected behavior
The deps resolution should work inside the umbrella subapp as it works inside the main umbrella project.

**Comment by josevalim** [comment]
If subapp2 has a "normal" dep and subapp1 says this "normal" app is ":test" only, Mix is actually saying that this is just not true. subapp2 will always bring the normal app and therefore you must remove the `:only` restriction, because it will never be applied. This happens because subapp2 is in the same dependency tree as subapp1.

The reason it works in umbrella is because those then become distinct trees so we chose to automatically merge it for you. So we could make it work inside the umbrella child but I truly don't think we should, exactly because `only: :test` truly has no effect and having it on all environments could be seen as surprising.

**Comment by xadhoom** [comment]
I don't agree entirely, I think that is more intuitive to do the same that's done on toplevel.

some rationale:

Think the case when I want to split up the subapp: It will bring a not needed dep in prod/dev, unless I remember to add the :only flag when splitting up (this means add comments like: remember to move to a test only dep if/when splitting away from the umbrella).

or when subapp2 changes its dep to something different, that leaves subapp1 with a dep lingering around in production even if is not needed. (since subapp1 is not meant to know subapp2 deps)

Imho is more correct to have a formally clean mix.exs and accept that the umbrella does some mixing for me (which is reasonable after all), because is easier to split up.

Doing as it is now, means that each subapp must be aware of other apps deps, thus coupling them, which should be not. Deps should be "hidden" in someway (except versions, of course).

maybe a warning can be ok.

jm2c

**Comment by josevalim** [comment]
I think it is worth having this discussion outside of the context of the umbrella.

Imagine that subapp1 and subapp2 are completely separate. How would you expect them to behave?

**Comment by josevalim** [comment]
> or when subapp2 changes its dep to something different, that leaves subapp1 with a dep lingering around in production even if is not needed. (since subapp1 is not meant to know subapp2 deps)

Btw, I can totally see this point, but in practice it is not so clean. For example, imagine those projects specify different versions or different sources for a given depednency. subapp1 uses git, subapp2 uses hex. You will have to pick one and the choice may be motivated by the child application needs.

**Comment by xadhoom** [comment]
> Imagine that subapp1 and subapp2 are completely separate. How would you expect them to behave?

exactly as mix.exs says: subapp1 should not bring the dep into production, while subapp2 does.

**Comment by xadhoom** [comment]
> Btw, I can totally see this point, but in practice it is not so clean. For example, imagine those projects specify different versions or different sources for a given depednency. subapp1 uses git, subapp2 uses hex. You will have to pick one and the choice may be motivated by the child application needs.

Correct, but with versions we must live with it, since erlang mandates that inside with the same vm.
But since having or not having a package built into the production can be done, so, why not?

**Comment by xadhoom** [comment]
maybe is worth asking others what feels more intuitive ?

**Comment by josevalim** [comment]
> Correct, but with versions we must live with it, since erlang mandates that inside with the same vm.

Hrm, it is not about the VM supports. The question is if the conflict should be resolved behind the scenes or explicitly. In both cases, a decision is made.
