### ISSUE TITLE
Compilation fails in Phoenix live reloader

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#6361]
### Environment

* Elixir & Erlang versions (elixir --version): elixir 1.5.0-rc.1, erlang 20.0
* Operating system: macOS 10.12.5
* phoenix 1.3.0-rc.2
* phoenix_live_reload 1.0.8
### Current behavior
In a simple freshly generated Phoenix app (no umbrella) whenever the live reloader recompiles the app it crashes with

`Compiling 2 files (.ex)

== Compilation error in file lib/my_app/web/endpoint.ex ==
** (ArgumentError) argument error
    (stdlib) :ets.new(MyApp.Web.Endpoint, [:set, :public, :named_table])
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1`

After killing & restarting the process the compilation succeedes.

**Comment by josevalim** [comment]
Great catch, I am on it!

**Comment by lukaszsamson** [comment]
That was quick. Thanks!
