### ISSUE TITLE
Changes from 1.3 -> 1.4

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/elixir#6362]
The following:

```elixir
put_in(["foo", bar: 1], [:bar], 2)
```

worked in 1.3:

```
["foo", {:bar, 2}]
```

but does not work in 1.4:

```
** (FunctionClauseError) no function clause matching in Keyword.get_and_update/4
    (elixir) lib/keyword.ex:227: Keyword.get_and_update(["foo", {:bar, 1}], [], :bar, #Function<12.40206377/1 in Kernel.put_in/3>)
    (elixir) lib/kernel.ex:1831: Kernel.put_in/3
```

I cannot find anything in the Changelog that would indicate that a change should have been expected.

**Comment by josevalim** [comment]
That's because the previous one worked by accident. We support only keyword lists and the given list is definitely not one. :) I will add a note though, thank you!
