### ISSUE TITLE
Build failed with "src/elixir.erl:21: syntax error before: ':='"

### ISSUE THREAD

**Issue by yoshiokatsuneo** [elixir-lang/elixir#6363]
### Environment

* Elixir & Erlang versions (elixir --version): 

Elixir: https://github.com/elixir-lang/elixir.git (1cc84f20c7b497af63464156a45a9181e2f3064f)

Erlang: Erlang/OTP 18 [erts-7.3] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

* Operating system: 
Ubuntu16.04 (on Docker)

### Current behavior

Build failed.

```
root@3dd09fd6492c:/tmp# git clone https://github.com/elixir-lang/elixir.git 
Cloning into 'elixir'...
remote: Counting objects: 114482, done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 114482 (delta 84), reused 102 (delta 41), pack-reused 114307
Receiving objects: 100% (114482/114482), 31.77 MiB | 3.86 MiB/s, done.
Resolving deltas: 100% (71714/71714), done.
Checking connectivity... done.
root@3dd09fd6492c:/tmp# cd elixir/
root@3dd09fd6492c:/tmp/elixir# make install
==> elixir (compile)
Compiled src/elixir_parser.yrl
...
Compiled src/elixir_def.erl
Compiled src/elixir_interpolation.erl
src/elixir.erl:21: syntax error before: ':='
src/elixir.erl:14: type struct() undefined
ERROR: compile failed while processing /tmp/elixir/lib/elixir: rebar_abort
Makefile:69: recipe for target 'erlang' failed
make: *** [erlang] Error 1
```
Include code samples, errors and stacktraces if appropriate.

### Expected behavior

Build succeed.

**Comment by josevalim** [comment]
@yoshiokatsuneo Elixir master requires Erlang 19. I have changed the Makefile to fail early instead of an unreadable error message. Thank you.
