### ISSUE TITLE
Code.eval_quoted/3 error

### ISSUE THREAD

**Issue by lachezar** [elixir-lang/elixir#6365]
I get the following error when using Conform 2.4.0 with Erlang 20.0 and Elixir 1.5.0 (tested with 1.5.0-rc2 with Alpine Linux 3.6 and also 1.5.0-rc1 on macOS from brew).

```
$ MIX_ENV=prod mix release --env=prod
... compilation will succeed and then we can run it ...
$ _build/prod/rel/test_conform_umbrella/bin/test_conform_umbrella console
** (ErlangError) erlang error: {:badrecord, :elixir_erl}
    (elixir) src/elixir_erl_var.erl:134: :elixir_erl_var.load_binding/2
    (elixir) lib/code.ex:207: Code.eval_quoted/3
    (conform) lib/conform/schema.ex:98: Conform.Schema.parse/1
    (conform) lib/conform/schema.ex:118: Conform.Schema.parse!/1
    (conform) lib/conform/schema.ex:132: Conform.Schema.load!/1
    (conform) lib/conform.ex:95: Conform.process/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

I have a sample project which I have compiled for another bug some time ago, but could be used as a demo for this issue as well - https://github.com/lachezar/test_conform_umbrella

I suspect that the error is not caused by Conform, since this issue is not present on elixir 1.4.5 and reading through the commits and release notes I can not find any information about breaking changes in elixir 1.5.0 that are related to elixir_erl or Code.eval_quoted/3, but there are some changes from February that are not present in 1.4.5 and may be have something to do with the issue - https://github.com/elixir-lang/elixir/commit/e7e0d512ff796aebe6885bdc4c7eb85077920855.

I am sorry if this turns out to be problem in Conform 😬

**Comment by josevalim** [comment]
It seems to be an issue with conform+release. After debugging your sample application, it turned out that we are receiving `#elixir_scope` where we expect `#elixir_erl`. The issue is that #elixir_scope is nowhere to be found in the Elixir release.

However, conform does embed Elixir into its executable. Could that be the source of the bug? Is there any chance the modules between Elixir v1.5.0 and the one used for Conform are getting mixed? @bitwalker, are you loading the conform script into the running VM somehow?

**Comment by josevalim** [comment]
Btw, no worries if this ends up being a conform issue, it is not an obvious one. :) And good bug reports are always easier to debug. :)

**Comment by lachezar** [comment]
Oh, right, I remembered there is an escript in Conform that would need recompilation. After `mix escript.build` it works correct! Thanks for the hint :)

**Comment by josevalim** [comment]
@lachezar you probably still want to report a bug to conform because I would not expect this error to happen anyway since it embeds Elixir.
