### ISSUE TITLE
Should `String.contains?` be grapheme aware?

### ISSUE THREAD

**Issue by alvinlindstam** [elixir-lang/elixir#6373]
`String.contains?` currently just checks if the given binary is in the other binary. This could cause some wierd behaviour with unicode graphemes, such as:

```elixir
iex> es_ee = "🇪🇸🇪🇪"
"🇪🇸🇪🇪"
iex> se = "🇸🇪"     
"🇸🇪"
iex> String.contains?(es_ee, se)
true
```

I guess that a grapheme aware `contains?` would be quite a lot slower than the binary match. But given that the String module is grapheme aware for most other functions, this seems a little off. 

### Environment

* Elixir & Erlang versions (elixir --version): 1.4.0, Erlang/OTP 19. But should be the same in current master.

**Comment by josevalim** [comment]
Great point. I will document that the splitting/matching functions can happen across grapheme boundaries and provide counter examples - since changing the implementation would have a huge impact on performance. For example, this also works: `String.contains?("josévalim", <<204, 12, 118>>)`, there the binary is the eaccent and the letter v.

**Comment by alvinlindstam** [comment]
Yes. It can match across grapheme boundaries, but it could also be a match agains just part of a cluster (without matching across boundaries) that might be wrong/unexpected, such as `String.contains("g̈", "g") == true`.

Clarified documentation could be great.

**Comment by OvermindDL1** [comment]
That would make sense for something more like a Unicode.contains or so.  I use String.contains to do binary matching quite often and changing that would break it pretty royally.  Can't you use a regex to do it anyway?  If passing a string I'd think nothing magical should be done to it.

**Comment by alvinlindstam** [comment]
@OvermindDL1: Other than than the performance issue, is there any situation where you think that the current behaviour is better than if it would match against grapheme sequences?

**Comment by OvermindDL1** [comment]
> @OvermindDL1: Other than than the performance issue, is there any situation where you think that the current behaviour is better than if it would match against grapheme sequences?

It's inconsistent even with utf8 libraries that I've used elsewhere.  I've always been taught in every other lib that you if want to match utf8 then normalize it first and match specifically.  This would just be a large hidden (*massive*) performance cost when many cases just categorically do not need it.

> String.contains("g̈", "g")

And I would expect this to return true.  The diacritic adds on to the character but does not change it, and you can in fact chain them pretty arbitrarily (look at zalgo text generators on google).

If you want unicode aware containing then I would always reach for regex instead as it would be more efficient regardless.

**Comment by OvermindDL1** [comment]
For note, I'd expect this to be true too:
```elixir
.


String.contains("Y̧̢̤̱̠̞̰̙̘͚̗̠̙̼͍̠̲̺͖̎̽̆ͮ͂̉̄ͧͤ̇̏́̚ͅͅo̸̡̳̭͇͖ͭͪͥ̃̀͊ͯͩ͒u̸̫̪̪̮̮͎̗̤̰̤̻̥̯̜͙͓͖͋̃̍̅͒̌̋̇́̕͞rͫ̈́̅ͨ̋ͮ̒͏͝҉̛͚̪͎̫̙͉̘̩̱̫̹͈̯̙ ̛̛̀͌ͩ̓̄ͬͬ̋͊́̚҉̗͚͍̘̣̭̜̠̣̱͙̮͙̥p̴͕͖̥͙̯̊̑͋͂̅̈́̓͂͡a͉̮͕̞̮̺̘̮̼͙̲̹̠̘̤̙̗̐͊͋̓̔̄͋̂̒ͭ̽̓̐͠͞ͅs̛̛͉̻̦̜̩̠̻̥͓̐̔̂͛̈̾̆ͫ̄ͣ̂ͬs̸̨̬̲̫̘̲̬̮͕̯̖̭͈̲̉͗͂͐̄͋̓̀̚͢w̴͙͎̬̮̻̜̺͉̳ͭ̇ͫ̽ͯ̅̈́͊̅̇̓͜͠o̴̵̸̴̡͖̹͓̞̳̩͎͚̮͑̂ͣ̇ͫ̈ͮ̾̾ͮ̚r̹̼̻̯̠̦̅̓̆͜͡ď̵̾̏̿̈́̾ͩͯ́̌ͫͧͥ͂̉̎̓͏̣̠̭͖͍ ̔̽́̇ͧ̇̈ͤ͜҉̷̩͙͉̖̪͇̤̼̭͇̘̦͝ͅi̧̇ͨ͒̄̇́̕҉̱͈͙̩̠̟ş̙̳͚̣͔̭͉̠̞̖̟͕̝͉͎̫ͪ̍͌ͣ͢ͅͅ ̷̧̘̞͖̜̲̣̫̤̯͕̪̠͖̮̥͙̜͎͒͂̆͆̒͐͆͛̿ͯ͝n̷̛͍̦̫̆̎ͣ̄́̽̚͢͞ǫ̵̗͇͕͔̙̞̯͔̤͍̩̤̼̳ͩ͛͗̎̄ͩ̿́͋̌̔̌̿́̕ţ̸̻̣͖̱̮̰̠͕̤̞͍̞͙͉̘̙͊́ͪͯ̓ͮ̌͊̊̈́͗̅̿ͭ̂̀͢͟ ̷͊ͩ͊̂̃̄̊͂̌ͭ́̇͌̓̉̈́̚҉͘͏̵̝͎̰̫͎̘̱̠̠̗̻͚͕s̆͒̐̈́ͬ̾͜҉̰̘͙̭̘͈͈͓̤̬̩̩̫t̢̅̇ͮ̐̇͘͏͉͇͈̗̺̹r̶ͭ̅̀͒̽̌̒̐̃̂̏͗͏̴̪̹̯͈̠͈͙̜̲̥͚̗̯̹̠̹̮̤ͅŏ̆̓ͯ̕͏͙̠̙̩̤n̷̽̀̋ͤ͒̔͒ͣͪ͏͜͏͚̣̪͉̮̲̯̖g̛͔̙̰͓̺͚̤̭̯̻͌̐͆́ͣ͊ͨ̈͊̂̒ͣͦ̎̚͝ ̸̡̬̟͙̝͚͈̭̤̟̯͓͉͓͉̣͈̦̋̊͐̓̍̀͜e̵̙͓̳̪̜̗̳̻̬͎͖̱̩͓͉͎̩͙̿̃̈̂̓͟n̯̘̲̯̹̘̫̥̪ͦ̊̃̒ͧ̀ͩͭͣ̂̋ͬ̿ͧ̀ͨ̈͠ͅö͐̋́̂̅͒ͦ̅̃̓̈́̐̾ͧ̋҉̵̧̖͖͓̱͔̙͕̯͚͠u̞̼͖͍͚̙͈̻̜̲̞ͯͯ̃̈́ͩ̓́̏ͧ́̆͐͛̉͑͐ͬ́͡g̑̉̈́ͥ̿ͦͤ͢͏̥̤͇̪͇͓̗͇̹h̵̸̴̫̹̰̬̦̣͍͖̤̖̖ͣ̅ͥ͒͂ͩͣ͑̽ͯ̽͊̋̉̓͐͊͞͞", "Y") === true


.
```

**Comment by alvinlindstam** [comment]
Is the regular expressions are grapheme-aware? A quick test seems to indicate that they are not:

```elixir
iex> es_ee = "🇪🇸🇪🇪"
"🇪🇸🇪🇪"
iex> se_regex = ~r/🇸🇪/  
~r/🇸🇪/
iex> String.match?(es_ee, se_regex)
true
```

My expectation would be the opposite, for a module that in many parts is built around using graphemes over single codepoints. Also, being native in a language that uses diacritic marks (swedish, with å, ä and ö), diacritic marks signals that it is in fact another character and not just some addon (though å, ä and ö have single codepoint forms, so they are not affected when using unicode normalized binaries).

I understand the issue about performance, which I'm guessing is a dealbreaker for changing the default behaviour, but not really why one would expect graphemes to be ignored in `String.contains?`.

In your last example, @OvermindDL1, would you not expect it to also match `Your` if you expect it to ignore the grapheme combinations?

**Comment by OvermindDL1** [comment]
> Is the regular expressions are grapheme-aware? A quick test seems to indicate that they are not:

No but they should be fully following the unicode spec (at least up to Unicode 9 for the BEAM regex engine as I recall, maybe newer) aware and can do conversions as necessary, which it looks like it did there, but you can somewhat control how that works with various things inside the regex.

> diacritic marks signals that it is in fact another character and not just some addon

Which a unicode aware regex should get right, if not it is a bug.  :-)

> I understand the issue about performance, which I'm guessing is a dealbreaker for changing the default behaviour, but not really why one would expect graphemes to be ignored in String.contains?.

Thing is that `contains` could follow any number of styles.  Maybe an option to designate the style would be useful, but by default I'd think it should be the fastest one possible.

> In your last example, @OvermindDL1, would you not expect it to also match Your if you expect it to ignore the grapheme combinations?

Not at all.  ^.^
