### ISSUE TITLE
Warn if length(list) == 0 is used inside guards

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6374]
We can either optimize or warn the user, but warning is probably the best way to go, since educating the user is better than optimizing away, as the user can still write the same code above in areas that cannot be optimized.

**Comment by davydog187** [comment]
Can you explain why we should warn?

**Comment by whatyouhide** [comment]
@davydog187 lenght/1 will always calculate the length of the whole list (which is a linear operation, O(n) for n being the length of the list). When you want to check for the list being empty, matching on [] will be constant time as it is a simple term comparison. Does it make sense?

**Comment by davydog187** [comment]
That does, I thought that context was important to include here for
whomever implements the warning

**Comment by kelvinst** [comment]
> We can either optimize or warn the user

Why not both? This way we educate without losing the benefits of the optimization.

**Comment by josevalim** [comment]
@kelvinst yup. On the other hand, it is very likely this is already something done by the Erlang compiler. So just warning will be fine!

**Comment by kelvinst** [comment]
I'm giving a try on this warning, just to let you know. ;)
