### ISSUE TITLE
mix test pointed to describe block line of code runs wrong tests. 

### ISSUE THREAD

**Issue by amencarini** [elixir-lang/elixir#6375]
### Environment

* Elixir & Erlang versions (elixir --version): 1.5.0, r19
* Operating system: macOS Sierra 10.12.5

As a setup, I have the following file:

```
defmodule FileLocationTest do
  use ExUnit.Case

  describe "describe 1" do # line 4
    test "test 1" do
      IO.puts "in test 1"
    end
  end

  describe "describe 2" do # line 10
    test "test 2" do
      IO.puts "in test 2"
    end
  end
end
```

### Current behavior

When running`mix test test/file_location_test:4`, all tests are skipped.

When running`mix test test/file_location_test:10`, the terminal output is `in test 1`.

### Expected behavior

When running`mix test test/file_location_test:4`, the terminal output should be `in test 1`.

When running`mix test test/file_location_test:10`, the terminal output should be `in test 2`.

**Comment by josevalim** [comment]
For now Mix only allows pointing to the tests themselves, not to describe groups.

**Comment by amencarini** [comment]
Cool, thanks for coming back to me!

**Comment by OvermindDL1** [comment]
> For now Mix only allows pointing to the tests themselves, not to describe groups.

Hmm, that could be a useful feature though thinking about it.  Would you be interested in a PR if anyone did one?  (Not me, in another crunch period at work, otherwise if someone reminds me later I can.)

**Comment by josevalim** [comment]
If someone does it we will be glad to accept it depending on the code complexity.

**Comment by dustinfarris** [comment]
I am confused by the documentation

https://hexdocs.pm/ex_unit/ExUnit.Case.html#describe/2-examples

```
mix test --only describe:"String.capitalize/1"
```

This sort of works for me unless i have spaces in the describe string.

```
mix test --only describe:"My interesting describe"
```

results in including tag `"My"` rather than the whole string.

**Comment by josevalim** [comment]
@dustinfarris what operating system are you using?

**Comment by josevalim** [comment]
@dustinfarris and can you fix it by including the describe in the quotes?

    mix test --only "describe:My interesting describe"

**Comment by dustinfarris** [comment]
@josevalim no, including the describe in quotes does not change anything.  Continues with above behavior.

**Comment by dustinfarris** [comment]
macOS Sierra, using ZSH shell, elixir 1.4.4

**Comment by josevalim** [comment]
Then it will be up to escaping in your shell. You need to find a way to quote the arguments such as the command below returns a single list, as shown:

```
$ elixir -e "IO.inspect System.argv" -- "describe:My test"
["describe:My test"]
```

**Comment by dustinfarris** [comment]
That works, but the test command does not :-/
