### ISSUE TITLE
Unexpected behaviour using `Kernel.apply(mod, fnc, args)` in Elixir 1.5

### ISSUE THREAD

**Issue by cbarratt** [elixir-lang/elixir#6377]
### Environment

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.0

Mac OSX Sierra

### Current behavior

The codebase in question has existed for a good year and has upgraded nicely with Elixir versions, 1.4 all included.

The problem I'm seeing is that in my code where I'm setting a return value to be a tuple like so:

`
{:ok, %{response: Jiffy.decode(data)}}
`

I'm actually getting a really weird result from `apply`

```
[do: {:ok, %{response: %{...}}]
```

Below is a gist of the code in question. The code path starts in `movies.ex` - my phoenix controller calls that function. Which will then check the ETS cache which for all sakes and purposes is always empty on boot - so it falls through to calling `apply(...)` and fetches the data fresh inside `resolver.ex`.

https://gist.github.com/cbarratt/0fa77b597b9f5d4c2d7bf3e60418b2a6

### Expected behavior

To return the return value set in the code and not have the odd `List` wrapped around.

Here's an example of my logging in the actual application:

```
Return result from programme_details
{:ok,
 %{response: %{"cast" => [%{"name" => "Jonathan Pryce",
        "roles" => ["Mayor Nathan Keane"]....


Return result from apply
[do: {:ok,
  %{response: %{"cast" => [%{"name" => "Jonathan Pryce",
         "roles" => ["Mayor Nathan Keane"]....]
```

**Comment by josevalim** [comment]
Are you using some sort of decoration or API that annotates function definitions? There was a bug in that the function body would be ambiguous on the `@on_definition` callback and I am afraid this may be biting you.

**Comment by cbarratt** [comment]
Aha! that could be it... I'm using AppSignal to monitor my application and I am decorating these functions:

https://docs.appsignal.com/elixir/instrumentation/instrumentation.html#decorator-transaction-events

**Comment by OvermindDL1** [comment]
Can you also inspect `resolver(), endpoint, [uuid]` as well to see what the values of those are that are being passed into the `apply` call?

**Comment by josevalim** [comment]
@cbarratt I have reported it to the decorator library already. Maybe try updating it and, if that's not enough, please ping them!

**Comment by cbarratt** [comment]
@josevalim No worries - thanks for the assistance in understanding the problem :) I'll give it a go using the latest decorator and keep my eye on those packages

**Comment by arjan** [comment]
If you do `mix deps.update decorator` in your project, it should update to vsn 1.2.2 which fixes this bug.
