### ISSUE TITLE
mix deps.compile in umbrellas

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#6381]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 20 Elixir 1.6.0-dev (e4455a411)
* Operating system: macOS

### Current behavior

When `mix deps.compile` is called in a root of an umbrella project, not only dependencies, but also all the umbrella applications are compiled. This means in umbrellas `mix deps.compile` and `mix compile` are exactly the same.

### Expected behavior

Ideally only the dependencies without any of the umbrella applications would be compiled. That said, I understand where the current behaviour comes from. It might also be complex to decide what is a dependency and what is not given umbrella children can depend on each other.
If the behaviour can't be changed, it should at least be documented.

**Comment by josevalim** [comment]
Please send a PR documenting it. We have no plans to change the behaviour as all umbrella children are just path dependencies.
