### ISSUE TITLE
Add current_stacktrace helper for pry

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#6390]
As suggested by @jayjun. It's a common feature of debuggers to have a command to print current stacktrace. Within a pry session, it's possible to use `Process.info(self(), :current_stacktrace)`, but it has disadvantages:

* returns data instead of printing nicely
* includes elements of pry internals

It would be nice to have the stracktrace captured before `pry` is started and have access to that during the session.

**Comment by josevalim** [comment]
Maybe we can print this information alongside whereami? So we don't need to
add a new function that works exclusively with debugging?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by michalmuskala** [comment]
I was thinking about that, should we really have all the helpers in the main `IEx.Helpers` module? Wouldn't it make sense to split those that are pry specific to `IEx.Pry.Helpers`?

**Comment by josevalim** [comment]
I thought about the same thing after my reply - the downside of this is obviously discovery. And right now we have only two functions that are specific to being inside pry, whereami and continue, so as long as we keep it like that, we are fine.

**Comment by jayjun** [comment]
I like augmenting `whereami` with stacktrace, that’s the first function I tried so at least it’s intuitive.
