### ISSUE TITLE
Code.compile_quoted works slow on Elixir 1.5.

### ISSUE THREAD

**Issue by surik** [elixir-lang/elixir#6393]
### Environment
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.0
```
MacBook Air late 2013 OS X 10.12.5

### Current behavior

I have big module quoted expression, see: https://gist.github.com/surik/0f83ae9899f6d0e8c8088ff73cec6633

On Elixir 1.4.5 I dint have any problem in terms of time to compile this. But on 1.5.0 it takes more than 200 seconds on my machine.

### Expected behavior
At least the same with Elixir 1.4.5

**Comment by josevalim** [comment]
On Erlang 19, v1.5.0 takes 7 seconds, v1.4.5 takes 10 seconds.

On Erlang 20, v1.5.0 indeed takes forever while v1.4.5 takes 10 seconds.

**Comment by josevalim** [comment]
I have built a minimum case and I will report the bug to the OTP team soon. Meanwhile, you can fix it in your app by removing the list starting it here: https://gist.github.com/surik/0f83ae9899f6d0e8c8088ff73cec6633#file-a-ex-L31. It finishes in the last line.

If you change the list it should have no effect on the result and it solves the compilation time. The reason why is still unclear but I can say it is related to BEAM optimizations when we have binaries inside lists.
