### ISSUE TITLE
async_stream emits wrong value when on_timeout is set to :kill_task

### ISSUE THREAD

**Issue by methyl** [elixir-lang/elixir#6395]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.0
```
* Operating system: OSX 10.11

### Current behavior

When I process some tasks using `Task.async_stream`, setting `on_timeout: :kill_task`, when process times out I receive`{:exit, :timeout}` tuple as value:
```
defmodule TestAsync do
  def test(element) do
    element
    :timer.sleep(1000)
  end
end

elements = [1]

tasks = Task.async_stream(elements, TestAsync, :test, [], timeout: 100, on_timeout: :kill_task)
results = Enum.to_list(tasks)
IO.inspect(results) # => [exit: :timeout]
```

### Expected behavior

`IO.inspect(results) # => [exit: :timeout, 1]`

When I process some tasks using `Task.async_stream`, setting `on_timeout: :kill_task`, I expect to receive the `{:exit, :timeout, element}` tuple as it's mentioned in documentation: https://hexdocs.pm/elixir/Task.html#async_stream/5-options

**Comment by josevalim** [comment]
@methyl thank you. It is a bug in the documentation.

**Comment by methyl** [comment]
@josevalim why don't we support the way it is in doc? I think this would be pretty useful to know _which_ items failed to be processed, instead of getting them somehow manually after processing.

**Comment by josevalim** [comment]
@methyl I agree but it would be a backwards incompatible change. We could maybe do it under a flag.

**Comment by methyl** [comment]
Right, that makes sense. Probably not worth breaking API, not sure about the flag. Maybe add something like `:kill_task_with_element` to avoid introducing another option?

**Comment by josevalim** [comment]
I would think of a separate flag altogether: `:include_elements`. And then we always include the elements with the input, regardless of what the output is.
