### ISSUE TITLE
Error when performing deps.get with invalid version syntax

### ISSUE THREAD

**Issue by ciaran** [elixir-lang/elixir#6398]
```
** (FunctionClauseError) no function clause matching in Version.InvalidRequirementError.exception/1

    The following arguments were given to Version.InvalidRequirementError.exception/1:

        # 1
        [message: "<> 0.12.0"]

    (elixir) lib/version.ex:116: Version.InvalidRequirementError.exception/1
    (hex) lib/hex/version.ex:97: Hex.Version.parse_requirement!/2
    (hex) lib/hex/version.ex:23: anonymous fn/3 in Hex.Version.match?/3
    (hex) lib/hex/version.ex:106: Hex.Version.cache/2
    (hex) lib/hex/remote_converger.ex:330: anonymous fn/2 in Hex.RemoteConverger.unlock_deps/2
    (elixir) lib/enum.ex:2857: Enum.filter_list/2
    (hex) lib/hex/remote_converger.ex:325: Hex.RemoteConverger.unlock_deps/2
    (hex) lib/hex/remote_converger.ex:313: Hex.RemoteConverger.prepare_locked/3
```

This seems to happen only in the event the dependancy is locked,
if the `mix.lock` is emptied, the exception is handled and the message is printed:

```
** (Mix) Required version "<> 0.12.0" for package httpoison is incorrectly specified (from: mix.exs)
```

Minimal reproduction case attached:
[deps-test.tar.gz](https://github.com/elixir-lang/elixir/files/1182954/deps-test.tar.gz)

Tested with 1.5.0

**Comment by ericmj** [comment]
This is a Hex bug that was caused by a backwards incompatible change in Elixir in https://github.com/elixir-lang/elixir/commit/824b26842052fc9f92a1916995ee91d5ef1c86e8.

@josevalim Is raising exceptions supposed to be public API or should we use our own exceptions in Hex?

**Comment by ericmj** [comment]
Thanks for the report @ciaran. This will be fixed in the next Hex release.
