### ISSUE TITLE
match? generates unused warning incorrectly (or misleadingly)

### ISSUE THREAD

**Issue by citizenparker** [elixir-lang/elixir#6403]
### Environment
* Elixir 1.4.2 & Erlang 19
* Operating system: OSX 10.12.5

### Current behavior

If I capture a variable for the purposes of using it in the first argument of a `match?` statement, Elixir complains that it is unused. This is useful behavior in the context of tests. Here's a simple way to reproduce:

```
x = 5
assert match?(x, 5)
```

If it's useful to understand why I'd want to do this, you can see an example in an actual production at https://github.com/swsheets/swsheets/commit/4fe7f409b70b8514a51cb1da23232cbdd794dfe3#diff-95692765a520d015e95a01d3cd510701R80

Thanks!

**Comment by josevalim** [comment]
The warning is correct. You are assigning to x but never using it. If you
want to match on an existing value, you need to use ^x.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
