### ISSUE TITLE
Confusing Date Documentation

### ISSUE THREAD

**Issue by JEG2** [elixir-lang/elixir#6404]
Is [this documentation](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/calendar/date.ex#L227-L229) intended?  It feels like it could be a copy and paste error to me.

Doesn't `Date` ignore all time related details?  Why the mention of "naive date times?"

**Comment by josevalim** [comment]
> It feels like it could be a copy and paste error to me.

It feels the same to me. :) PR please?
