### ISSUE TITLE
confusing error message when `tuple` is used as typevariable

### ISSUE THREAD

**Issue by NobbZ** [elixir-lang/elixir#6411]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe]

Elixir 1.5.0
```
* Operating system: Gentoo Linux (`Linux funtoo-tuxedo 4.8.15-1 #8 SMP Thu Jun 8 18:56:41 CEST 2017 x86_64 Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz GenuineIntel GNU/Linux`)

### Current behavior

```sh
$ cat foo.ex
defmodule M do
  @spec f(list) :: nil when list: [integer]
  def f(_), do: nil

  # @spec g(tuple) :: nil when tuple: {integer, integer}
  def g(_), do: nil

  @spec h(integer) :: nil when integer: 1
  def h(1), do: nil
end

$ elixrc foo.ex

$ edit foo.ex # remove that `#` and make `g`s spec available

$ elixrc foo.ex

== Compilation error in file foo.ex ==
** (CompileError) foo.ex:5: type variable tuple is only used once (is unbound)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

### Expected behavior

Print out a meaningful errormessage for all internal types or be able to use them as a typevariable.

Personally I'd prefer to disallow their usage as type variables.

**Comment by wuhkuh** [comment]
Due to the GitHub downtime I didn't see your bug report. The solution I proposed was:

> tuple cannot be used as argument (reserved keyword)

Also, consistency with keywords as 'list' would be great. This means no more usage of list, tuple, integer or similar as arguments.

**Comment by NobbZ** [comment]
Tuple is **not** a keyword. Elixir has only a very small number if them. Also the term might be confused with [`Keyword`-module](https://hexdocs.pm/elixir/Keyword.html). Also you aren't using `tuple` as an argument, you are using it as a typevariable. So a better error were probably:

> ```plain
> == Compilation error in file $file ==
> ** (CompileError) $file:$line: type variable $token_text the name of a basic type, please choose another name
> ```

Perhaps only deprecate/warn for now?

**Comment by josevalim** [comment]
Thanks for the report!

The reason why you get an error with tuple but not with lists is because tuple is an actual type while list is a built-in alias for `list(any())`. [Source](https://hexdocs.pm/elixir/typespecs.html).

I think the actual bug here is that the error message is confusing but I don't think we will aim to make tuple and list consistent since they are not the same thing.

**Comment by josevalim** [comment]
Actually I spoke too soon. From all built-in types, this error seems to happen only with tuples. There is something else going on here.
