### ISSUE TITLE
Nested Sigils

### ISSUE THREAD

**Issue by meyercm** [elixir-lang/elixir#6414]
### Environment

Checked in Elixir 1.4 & 1.5 / OTP 19 & 20

### Current behavior

Sigils terminate as soon as a matching delimiter is found. Using different delimiters for nested sigils is a workaround, but unsatisfying and mildly problematic.

The problem can be demonstrated with stdlib sigils, but this example uses [ShorterMaps] (https://github.com/meyercm/shorter_maps) to provide a more realistic use case. 

```elixir
iex> import ShorterMaps
...> ~M{subscriber_id, params: ~M{channel, node}} = %{subscriber_id: 1, params: %{channel: :test_chan, node: node()}}
** (SyntaxError) iex:2: unexpected token: }
# Now switch the inner sigil delimiter to ( ): 
...> ~M{subscriber_id, params: ~M(channel, node)} = %{subscriber_id: 1, params: %{channel: :test_chan, node: node()}}
%{params: %{channel: :test_chan, node: :nonode@nohost}, subscriber_id: 1}
```

### Expected behavior

For the matched sigil open delimiters `( [ < {`, I expect that the parser should count additional open delimiters, and not terminate the sigil until finding that many closing delimiters.

As ShorterMaps is intended to be a syntax replacement for maps, my preference is to always use `{ }`; because ShorterMaps can embed arbitrary Elixir in the sigil, to include function calls, lists, tuples, and binaries, fixing this issue reduces the cognitive load of choosing the right terminator for a particular use case.

It appears that this issue was looked at in 2012 with #743, but I'm hopeful that there is a more feasible approach available now.

**Comment by josevalim** [comment]
If we do the proposed changes, it would break a lot of code and be quite problematic. For example, this would no longer be a valid string `~s[(]`. I don't see why strings need to have matching parentheses inside of them, after all, sigils are about text-based representations.

This seems to be a problem with trying to represent Elixir code inside a sigil. You will need to escape the control characters as in any other string (or change the delimiters).

**Comment by meyercm** [comment]
I think I wasn't completely clear;  I'm not suggesting that every sigil needs to have balanced internal paren.

What I'm trying to describe only applies to the chosen sigil delimiter, the symbol that opens the string.  This would not recurse to any delimiters found within the sigil, just the open/close delimiter pair. In your example, that would be the `[`, and the sigil would not close until finding a balanced count of `]`.  

I can update your counterexample; it would be impossible to use `~s[[]`, and so in this case, where you need to represent a string with unbalanced open delimiters, you would have to choose another sigil delimiter.  In the worst case, the payload `( [ < { ' " / |` (or any payload containing that string) is unrepresentable by a single sigil without escaping a character.


I can appreciate a strong commitment to backwards compatibility, but perhaps you'd consider this for a 2.0 feature, though I'd rather you choose natively-implemented ES6-style maps.

**Comment by josevalim** [comment]
Thanks for the clarification.

I am afraid it doesn't change the answer much. To achieve what you want, you must escape the separator, as in any way textual representation of code. For example, imagine I have a string that represents Elixir code, you would need to write this:

    "this_is_a_string = \"foo\""

So you either need to change the terminator or escape them.

And we generally don't treat Elixir 2.0 as an opportunity to make breaking changes. The goal for Elixir v2.0 is to remove the deprecated code that we added throughout the 1.x series.
