### ISSUE TITLE
An issue of `HEX_MIRROR` environment

### ISSUE THREAD

**Issue by qhwa** [elixir-lang/elixir#6422]
### Environment

* Elixir & Erlang versions (elixir --version): 

      Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

      Elixir 1.5.0

* Operating system: any

### Current behavior

1. `HEX_MIRROR` is **used** for `mix hex.local` task, [source code](https://github.com/elixir-lang/elixir/blob/43a4720b1ab3678a8bc8bb99f5dfe142b9d224fb/lib/mix/lib/mix/hex.ex#L67)
2. `HEX_MIRROR` is **deprecated** for `mix deps.get` and raises an error

      > The environment variable HEX_MIRROR and configuration key mirror_url have been deprecated in favor of setting the repository configuration through the `mix hex.repo` task", mix: true

This causes problems. For example It's now hard to config edeliver when [its source code](https://github.com/edeliver/edeliver/blob/e12b6dce40952b96a2feff1812b875361686c8a0/libexec/erlang#L127-L128) looks like:

```elixir
APP=\"$APP\" MIX_ENV=\"$TARGET_MIX_ENV\" $MIX_CMD local.hex --force
APP=\"$APP\" MIX_ENV=\"$TARGET_MIX_ENV\" $MIX_CMD deps.get
```

### Expected behavior

 The same way to set mirror for both tasks? Or http(s)_proxy is supported in `local.hex` task.

Thanks.

**Comment by ericmj** [comment]
This is a bug in Hex and is tracked here: https://github.com/hexpm/hex/issues/391.
