### ISSUE TITLE
Deps recompile each time after I changed my code, Confirmed!

### ISSUE THREAD

**Issue by neroishero** [elixir-lang/elixir#6423]
### Environment

* Elixir & Erlang versions (elixir 1.5.1): 
* Operating system: WIN 7

I deleted the folder _build and deps, and redownload deps. Each time i change my source code(NOT the deps codes), then I run "iex -S mix run", elixir recompile the deps code each time. So it should be a bug?!

plus my deps:
    [{:cowboy, "~> 1.0.0"},
     {:plug, "~> 1.0"},
     {:logger_file_backend, "~> 0.0.10"},
     {:json, "~> 1.0"},
     {:ecto, "~> 2.1"},
     {:mariaex, "~> 0.8.2"},
     {:chronos, "~> 1.7.0" }]
with so many warnings~ GOD!

**Comment by josevalim** [comment]
It is a bug but you need to give us a mechanism to reproduce the issue, such as an application on Github. Simply filling a report is not enough.

@OvermindDL1 are you aware of anything that could be causing this from the top of your mind?

**Comment by OvermindDL1** [comment]
> @OvermindDL1 are you aware of anything that could be causing this from the top of your mind?

Considering Windows there are *lots* of things that can cause a timestamp update on a file if that is what elixir checks for, including even some antiviruses and file synch programs, that is the first thing I'd be checking for, is if the timestamp updated even a second after when it was actually saved.

**Comment by wuhkuh** [comment]
@neroishero 

I've cloned your elixir_test repository and tried to reproduce the issue using your notes in the README.md, but to no avail. It compiles properly (just once), even when editing the source code.

### Environment
- Elixir & Erlang versions:
  Elixir 1.5.1
  Erlang/OTP 19 [erts-8.0] [64-bit] [smp:16:16] [async-threads:10]
- Operating system: Windows 10 Pro
