### ISSUE TITLE
Every time I run escript.build, the result gets bigger

### ISSUE THREAD

**Issue by tony612** [elixir-lang/elixir#6436]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.5.0
```
* Operating system: macOS 10.12.5

### Current behavior

In the project https://github.com/tony612/protobuf-elixir:

```
$ mix escript.build
$ ls -lh priv/protoc-gen-elixir
-rwxr-xr-x  1 tony  staff   2.3M Aug  5 20:17 priv/protoc-gen-elixir

# Add a blank line to lib/protobuf/protoc/generator.ex
$ mix escript.build
$ ls -lh priv/protoc-gen-elixir
-rwxr-xr-x  1 tony  staff   4.6M Aug  5 20:24 priv/protoc-gen-elixir

# Remove that blank line of lib/protobuf/protoc/generator.ex
$ mix escript.build
$ ls -lh priv/protoc-gen-elixir
ls -lh priv/protoc-gen-elixir
-rwxr-xr-x  1 tony  staff   6.8M Aug  5 20:24 priv/protoc-gen-elixir
...
```

### Expected behavior

The result should have the same size every time.

Is this a bug?

**Comment by ericmj** [comment]
You have configured the escript compiler to output into the priv directory [1] and that directory is included in the escript.

[1] https://github.com/tony612/protobuf-elixir/blob/master/mix.exs#L46

**Comment by tony612** [comment]
I see. Thank you!
