### ISSUE TITLE
Optional Dependency compile-graph misordered

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-lang/elixir#6438]
Tried with master just to make sure as well.

### Environment

* Elixir & Erlang versions (elixir --version):
```bash
╰─➤  elixir --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0-dev (0beeef8) (compiled with OTP 20)
```
* Operating system:  Linux 64-bit

### Current behavior

I have a library that has an optional dependency on `postgrex`:

```elixir
      {:postgrex, "~> 0.13.0", optional: true},
```

And in this library there is a module that is conditionally compiled if `postgrex` exists, via:

```elixir
if Code.ensure_loaded?(Postgrex) do

  defmodule SomeModuleThatNeedsPostgrex do
    ...
  end
end
```

However, using this library in another project that uses postgrex:

```elixir
      {:postgrex, "~> 0.13.3"},
      {:my_library, "~> 0.1.1"},
```

Is having postgrex compile 'after' my_library:
```bash
╰─➤  mix deps.compile
==> my_library
Compiling 1 file (.ex)
Generated my_library app

==> postgrex
Compiling 62 files (.ex)
warning: Enum.partition/2 is deprecated, use Enum.split_with/2
  lib/postgrex/error_code.ex:14

Generated postgrex app
```

Which is causing the module to not exist, thus crashing at compile-time when the main application compiles:
```bash
** (ArgumentError) invalid or unknown type SomeModuleThatNeedsPostgrex for field :renewal_period
    lib/ecto/schema.ex:1727: Ecto.Schema.check_type!/3
    lib/ecto/schema.ex:1431: Ecto.Schema.__field__/4
    lib/my_server/db/module/requirement.ex:8: (module)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

### Expected behavior

For optional dependencies to force that dependency to be compiled 'before' the library that specifies that optional dependency 'if' that optional dependency exists.

If you wish to test it yourself, my `EctoInterval` project hits this bug, just depend on it and postgrex and play, it reproduces 100% of the time here (I'm guessing it compiles EctoInterval first because `E` < `P`?).

**Comment by OvermindDL1** [comment]
And I've entirely wiped and re-built the project and now the order is right (after taking 3 minutes to recompile everything...), now I cannot reproduce it...

Is the compile-graph kept out of the `_build` directory somewhere, because I kept wiping that directory repeatedly...

**Comment by josevalim** [comment]
The graph is built every time we traverse dependencies - it is not cache. I can't see a reason why it would be out of order but maybe some particular order of events would trigger it. Maybe it requires changing a dependency and not compiling from scratch?

**Comment by OvermindDL1** [comment]
> Maybe it requires changing a dependency and not compiling from scratch?

Perhaps, but it was still happening when I `rm -r _build`, it only stopped happening when I `rm -r deps` too (even though individually the deps were updated prior, just without blasting the whole directory).

**Comment by josevalim** [comment]
Could it be you were on an old version of one of the repos that did not list the dependencies correctly?

**Comment by OvermindDL1** [comment]
> Could it be you were on an old version of one of the repos that did not list the dependencies correctly?

At least not for ecto_interval, I thought that and `cat deps/ecto_interval/mix.exs` and it had the proper optional dependency listed.  Nor the main project either of course.

**Comment by josevalim** [comment]
I will close this as it seems there is no mechanism for us to reproduce the issue. If there is one, please let us know and we will gladly investigate it!
