### ISSUE TITLE
Third parameter of assert_in_delta...

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#6439]
If the third parameter of `assert_in_delta` is less than zero, the assertion never passes.

But a negative value makes no sense, so I believe that the code should take the absolute value of the delta before testing.

This issue arises if you want to test against a variable delta:

~~~ elixir
a = -1
b = -1.00001

# are A and B the same to 1%
assert_in_delta a, b, a/100
~~~

**Comment by josevalim** [comment]
Thanks @pragdave! Although... wouldn't it be better to raise then?

**Comment by pragdave** [comment]
Why raise? You're doing users a favor by letting them pass a negative delta, just as a convenience.


On Tue, Aug 08, 2017 at 5:06pm, José Valim < notifications@github.com [notifications@github.com] > wrote:
Thanks @pragdave [https://github.com/pragdave] ! Although... wouldn't it be better to raise then?

**Comment by josevalim** [comment]
You said it:

> But a negative value makes no sense

:)

If the user is passing a negative value it may be an error in the user code and raising will allow them to catch it faster compared to us accidentally making it work.

**Comment by pragdave** [comment]
I see this as a beneign form of coercion.


It's a common problem with assert_in_delta that you can't give an absolute value for the delta. Instead you only know the precision. To drive the delta, you have to scale one of the original numbers by some factor. So negative deltas will be common, and we may as well make it easier for folks.


Or... What does delta mean? abs(a-b) < delta. So your already discarding the sign on the left. Why not the right?



On Tue, Aug 08, 2017 at 5:11pm, José Valim < notifications@github.com [notifications@github.com] > wrote:
You said it:

But a negative value makes no sense

:)

If the user is passing a negative value it may be an error in the user code and raising will allow them to catch it faster compared to us accidentally making it work.
