### ISSUE TITLE
Fix Time.new spec?

### ISSUE THREAD

**Issue by linges** [elixir-lang/elixir#6444]
The function `Time.new` has as the spec `  @spec new(Calendar.hour, Calendar.minute, Calendar.second, Calendar.microsecond, Calendar.calendar) ::
{:ok, t} | {:error, atom}`  [Time.ex:97](https://github.com/elixir-lang/elixir/blob/v1.5.1/lib/elixir/lib/calendar/time.ex#L97) where `Calendar.microsecond` resolves to `microsecond :: {0..999_999, 0..6}` [Calendar.ex:56](https://github.com/elixir-lang/elixir/blob/v1.5.1/lib/elixir/lib/calendar.ex#L56).

But `Time.new` also accepts integer as microseconds [Time.ex:101](https://github.com/elixir-lang/elixir/blob/v1.5.1/lib/elixir/lib/calendar/time.ex#L101).

Found with v1.5.1 but is still present on the current master https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/calendar/time.ex#L97.

**Comment by josevalim** [comment]
Yes, please do send a PR.
