### ISSUE TITLE
Hoisting defstruct calls

### ISSUE THREAD

**Issue by wpcarro** [elixir-lang/elixir#6445]
### Environment

* Elixir `v1.5.1`. Erlang `OTP 20`
* Operating system: Mac OS Sierra

### Current behavior

I've noticed that the `defstruct` calls are not hoisted to the top of the module during compilation time. I realize that this may not be a bug, but is it the desired behavior?

I have a library that builds struct definitions and injects the accumulated `defstruct` during the `@before_compile` hook. This works fine until functions within that module reference the struct in pattern matches and it returns...

## Example

```elixir
defmodule Person do
  use Decoder

  field :first_name,
    type: binary, column_index: 0

  field :last_name,
    type: binary, column_index: 1

  field :age,
    type: binary, column_index: 2

  def name(%Person{first_name: fname, last_name: lname}),
    do: "#{fname} #{lname}"
end
```

This results in a compilation error...
```
** (CompileError) /lib/file.ex:13: Person.__struct__/0 is undefined, cannot expand struct Person
```

Put differently, the following works...

```elixir
defmodule WorkingPerson do

  defstruct [:first_name, :last_name, :age]
  
  def name(%Person{first_name: fname, last_name: lname}),
    do: "#{fname} #{lname}"
end

end
```

...while this does not.

```elixir
defmodule FailingPerson do
  
  def name(%Person{first_name: fname, last_name: lname}),
    do: "#{fname} #{lname}"

  defstruct [:first_name, :last_name, :age]
end
```

**Comment by josevalim** [comment]
Elixir won't perform any hoisting. That's because Elixir has lexical constructs. For example:

```
defmodule FailingPerson do
  
  def name(%Person{first_name: fname, last_name: lname}),
    do: "#{fname} #{lname}"

  import Foo, only: [defstruct: 1]
  defstruct [:first_name, :last_name, :age]
end
```

If we hoist, we could potentially change the result of defstruct. Also, because defstruct is simply a macro and not a syntax construct, we can only know what it is after we expand all imports up to that point and then expand the defstruct macro.

**Comment by wpcarro** [comment]
Thanks for the reply, @josevalim. I suppose this may be a separate concern, but is there anyway to control the injection point for the `@before_compile` hook?
