### ISSUE TITLE
Supervisor.which_children/1

### ISSUE THREAD

**Issue by xfumihiro** [elixir-lang/elixir#6451]
Shouldn't it be named **list_children** since it

> Returns a list with information about all children of the given supervisor.

**Comment by josevalim** [comment]
It was named as such to mirror the Erlang API. Please use the elixir-lang-core mailing list for such discussions next time, ad we reserve the issues tracker for mostly bugs (although I can see you may consider this as a bug, so no worries). :heart:

**Comment by ivanovaleksey** [comment]
I just wanted to suppose it is due to Erlang API too.
You can see Erlang's version [here](http://erlang.org/doc/man/supervisor.html#which_children-1).

**Comment by xfumihiro** [comment]
@ivanovaleksey Thanks! I should really checkout Erlang's stuff someday...
