### ISSUE TITLE
mix local.hex --if-missing: Unknown option

### ISSUE THREAD

**Issue by xtian** [elixir-lang/elixir#6453]
Not sure if I am doing something wrong here, but I'm having trouble getting the new `--if-missing` option to work with `mix local.hex`.

### Environment

* Elixir & Erlang versions (elixir --version): 
```
~$ mix --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Mix 1.5.1
```

* Operating system: macOS 10.12.6

### Current behavior

```
~$ mix local.hex --if-missing
** (Mix) Could not invoke task "local.hex": 1 error found!
--if-missing : Unknown option
```

### Expected behavior

`--if-missing` flag should be recognized and trigger the behavior described in #5674

**Comment by josevalim** [comment]
Can you by chance be running a Mix from a precious Elixir installation?
What happens if you do "iex -S mix" and then call
Application.started_applications?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
No worries, I was able to verify it. :)
