### ISSUE TITLE
Can't download binaries from Asia

### ISSUE THREAD

**Issue by florianmonfort** [elixir-lang/elixir#6467]
Been looking around for a solution but haven't come across any.

Been trying to download Elixir for WSL, through the command line. Added the repos to the Ubuntu instance using Bash, everything goes well. Then I try to install and this happens:

![image](https://user-images.githubusercontent.com/1446429/29352747-7a1bcc4c-829a-11e7-9192-c96993106938.png)

I am located in Mainland China and I have tried both without a VPN / Proxy and with a Proxy in Hong Kong. In Hong Kong is a bit faster but as slow as what you are seeing above, however without it it's even not downloading anything at all.

I know we're supposed to look through forums and stuff, but I am assuming here that only people from er solutions can actually solve this.

For more configuration info:

- I use Windows 10 Creators Update, latest build;
- I try to install through Windows Subsystem for Linux, my Ubuntu Xenial is up-to-date;
- Other repositories I do an apt-get install or apt-get update from work just fine;

**Comment by josevalim** [comment]
Hi @florianmonfort. We are not the ones responsible for maintaining the packages and distributions. If you are having troubles with some repos or you don't have any repos available, you can compile from source, it is relatively straight-forward and documented on the website: https://elixir-lang.org/install.html. Tools such as `asdf` can also help.
