### ISSUE TITLE
Operators with unary and binary forms improperly parse

### ISSUE THREAD

**Issue by isaacsanders** [elixir-lang/elixir#6469]
### Environment

Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.5
```

Operating system: 

```
Darwin Kernel Version 15.6.0; x86_64; OS X 10.11.6
```

### Current behavior

Currently, expressions wrapped in parentheses are not parsing in a way that I would expect.

Addition and subtraction appear to parse as an unused literal and a numeric identity or numeric negation.

In an expression wrapped as such, I would expect the entire expression to be parsed as a whole before the parser decides whether my literals/variables are unused.

In IEx:
```
iex(1)> (
...(1)> 1
...(1)> +
...(1)> 1
...(1)> )
warning: code block contains unused literal 1 (remove the literal or assign it to _ to avoid warnings)
  iex

1
iex(2)> (
...(2)> 2
...(2)> *
...(2)> 2
...(2)> )
4
iex(3)> (
...(3)> 1
...(3)> -
...(3)> 1
...(3)> )
warning: code block contains unused literal 1 (remove the literal or assign it to _ to avoid warnings)
  iex

-1
iex(4)> (
...(4)> 1
...(4)> /
...(4)> 2
...(4)> )
0.5
```

Likewise, with a variable:

```
iex(1)> a = 1
1
iex(2)> (
...(2)> a
...(2)> +
...(2)> 1
...(2)> )
warning: variable a in code block has no effect as it is never returned (remove the variable or assign it to _ to avoid warnings)
  iex:3

1
```

In `erl`:

```
 $ erl
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V9.0  (abort with ^G)
1> (
1> 1
1> +
1> 1
1> ).
2
```

### Expected behavior

```
iex(1)> (
...(1)> 1
...(1)> +
...(1)> 1
...(1)> )
2
iex(2)> (
...(2)> 2
...(2)> *
...(2)> 2
...(2)> )
4
iex(3)> (
...(3)> 1
...(3)> -
...(3)> 1
...(3)> )
0
iex(4)> (
...(4)> 1
...(4)> /
...(4)> 2
...(4)> )
0.5
```

**Comment by josevalim** [comment]
Parens can expand over multiple lines. If you replace the numbers by expressions, it may become clearer what happens:

```elixir
(
foo_bar_baz()
+default_number()
)
```

Those are really two lines in isolation. The reason why it works in Erlang is because it requires explicit terminators. The reason why it works with `*` and others is because they are not unary. The ambiguity happens only with `+` and `-` which are the only operators that are unary and binary.

**Comment by isaacsanders** [comment]
@josevalim I know what it is doing. I disagree with it. Note that there is a difference in your example from mine. The operator is on its own line, as is the second literal. It is inconsistent.

This could be the source of pretty serious bugs for folks who aren't aware of this distinction.

**Comment by isaacsanders** [comment]
I would posit that parens shouldn't be able to evaluate a number of expressions, but contain only one.

There are other syntactical structures that are meant for the evaluation of multiple expressions.

**Comment by josevalim** [comment]
@isaacsanders being in another line doesn't change the outcome. The `+` is treated as an unary operator in both cases.

As you pointed out, the issue is really that parens can hold a number of expressions - but we cannot change this behaviour - it is a major breaking change. And Elixir does not have other syntactical structures for the evaluation of multiple expressions. We do have do-block  but they are not general purpose - they can be used only on function calls. You can't write something such as:

```elixir
foo = do
  ...
end
```

**Comment by OvermindDL1** [comment]
```elixir
iex1> quote do
...1> (
...1> 1
...1> +
...1> 1
...1> )
...1> end
{:__block__, [], [1, {:+, [context: Elixir, import: Kernel], [1]}]}
```
Is indeed a bit unexpected but it is obvious why it does it.  (though I have opinions on whitespace sensitivity in languages in general, and this is definitely one of those issues, grrr...)

**Comment by isaacsanders** [comment]
@josevalim I think the fact that the mathematical results produced by the language can be significantly incorrect in a subtle way warrants a "major breaking change".

**Comment by isaacsanders** [comment]
@OvermindDL1 It was not obvious to me that my math hadn't changed, but my results had. Not until I looked at individual results in the repl did the truth of the matter reveal itself.

**Comment by josevalim** [comment]
@isaacsanders the mathematical results are correct. The way you were expecting the expressions to be parsed are incorrect. We have no plans to change how the parser works.

**Comment by fishcakez** [comment]
If someone has different expectations to the presedence of the language
then warnings are printed. Are we able to explain that unary operators have
higher presedence in these cases or does the parser not allow it?

**Comment by josevalim** [comment]
We could make a unary operator followed by a new line to warn. I am ok with this solution since it is an uncommon idiom anyway. Is that reasonable?

**Comment by OvermindDL1** [comment]
> We could make a unary operator followed by a new line to warn. I am ok with this solution since it is an uncommon idiom anyway. Is that reasonable?

Or perhaps if an unary operator is the first thing on a newline?  It is hard to think of actual used cases where that would actually be used except for custom functions and/or macro unary calls.

I actually do use `+` on the end of a newline in binary calls fairly often, so as long as it only affects unary calls I'm good.  :-)

**Comment by ericmj** [comment]
> I actually do use + on the end of a newline in binary calls fairly often, so as long as it only affects unary calls then I'm good with as proposed. :-)

It would be for unary operators only, ending lines with binary operators is common.

**Comment by josevalim** [comment]
> Or perhaps if an unary operator is the first thing on a newline? It is hard to think of actual used cases where that would actually be used except for custom functions and/or macro unary calls.

`@foo` is an unary operator on a newline and it is an extremely common pattern.
