### ISSUE TITLE
Strange behavior applying Integer.parse with Enum.map

### ISSUE THREAD

**Issue by tevyt** [elixir-lang/elixir#6472]
### Environment

* Elixir & Erlang versions (elixir --version): 
   Elixir Version: Elixir 1.4.5
   Erlang Version: Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
* Operating system: Ubuntu 17.04

### Current behavior

I came across some very strange behavior when mapping `Integer.parse` over a map of strings in Elixir. I executed the following:
`Enum.map(["7", "8", "9"], &elem(Integer.parse(&1), 0))`
Which resulted in the following output: `'\a\b\t'`.

Oddly enough if I change the "7" it behaves as I would expect:
  
    `Enum.map(["4", "8", "9"], &elem(Integer.parse(&1), 0))`

Results in `[4, 8, 9]`

Further experimentation shows that there is similar behavior for every leading number greater than 6 but less than 14

For example `Enum.map(["11", "8", "10"], &elem(Integer.parse(&1), 0))` results in `'\v\b\n'` but `Enum.map(["16", "8", "10"], &elem(Integer.parse(&1), 0))` results in `[16, 8, 10] `

### Expected behavior
I would expect the result of `Enum.map(["7", "8", "9"], &elem(Integer.parse(&1), 0))` to be `[7, 8, 9]` as with the other cases.

**Comment by sorentwo** [comment]
That isn't because of `Enum.map` or `Integer.parse`, it is just the behavior of character lists in Erlang. There isn't any difference between a list of integers and a list of characters. The reason it looks like a list of plain integers for some numbers is because there isn't an ASCII equivalent.

**Comment by tevyt** [comment]
I see, thanks for the explanation

**Comment by fishcakez** [comment]
Hi @tevyt, its as @sorentwo says. Though its to do with whether the whole list can be printable as a string, and supports characters outside ascii range. The examples you gave are valid ascii but not all printable characters. You can get more information on a term using i/1 in the shell

```
iex(1)> i '\a\b\t'
Term
  '\a\b\t'
Data type
  List
Description
  This is a list of integers that is printed as a sequence of characters
  delimited by single quotes because all the integers in it represent valid
  ASCII characters. Conventionally, such lists of integers are referred to as
  "charlists" (more precisely, a charlist is a list of Unicode codepoints,
  and ASCII is a subset of Unicode).
Raw representation
  [7, 8, 9]
Reference modules
  List
Implemented protocols
  IEx.Info, Inspect, Collectable, Enumerable, List.Chars, String.Chars
```
Or perhaps combine with v/1: `i v(-1)`

**Comment by fishcakez** [comment]
Oh seems it is indeed only printable ascii..
