### ISSUE TITLE
On windows x64: make test results in 3697 tests, 1 failure

### ISSUE THREAD

**Issue by oboudry** [elixir-lang/elixir#6473]
I compiled Elixir 1.5.1 on Windows 7 SP2 Pro x64, with OTP20 x64, using mingw-w64\x86_64-7.1.0-posix-seh-rt_v5-rev2. It built without any error, but make test fails on one of the tests.

`==> elixir (exunit)
"C:/Program Files (x86)/Git/bin/sh.exe": line 0: exec: epmd: not found
...
08:52:00.133 [info]  Protocol 'inet_tcp': register/listen error: econnrefused

  1) test start/3 and stop/0 (NodeTest)
     test/elixir/node_test.exs:8
     match (=) failed
     code:  assert {:ok, _} = Node.start(:hello, :shortnames, 15000)
     right: {:error,
             {{:shutdown,
               {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}},

              {:child, :undefined, :net_sup_dynamic,
               {:erl_distribution, :start_link,
                [[:hello, :shortnames, 15000], false]}, :permanent, 1000,
               :supervisor, [:erl_distribution]}}}
     stacktrace:
       test/elixir/node_test.exs:10: (test)
`

**Comment by josevalim** [comment]
We have the appveyor build passing in Windows, so it is most likely something with your installation. Please make sure `epmd` is available in your path (it is part of the Erlang distribution) or start it manually before running the test suite.

**Comment by robi-wan** [comment]
An Erlang/OTP installation comes with two bin folders: just one of them contains the epmd executable. You have to add this bin folder to your PATH environment variable. 

See the line with the cmd command under the "before_test" section in https://github.com/elixir-lang/elixir/blob/master/.appveyor.yml: 

      - cmd: set PATH=%PATH%;C:\Program Files\erl8.3\erts-8.3\bin

You may have to adopt the used path to your local Erlang installation.

**Comment by oboudry** [comment]
Thanks, that was the cause.
