### ISSUE TITLE
Strange error message, wrong line number

### ISSUE THREAD

**Issue by meyercm** [elixir-lang/elixir#6478]
### Environment
Occurs in both Elixir 1.5.0 (Erlang 20) and 1.4.2 (Erlang 19.2)

### Current behavior

`example.ex`:
```elixir
  1 defmodule Test do
  2   def broken do
  3     if false do
  4       :a
  5     end
  6     else if false do
  7       :b
  8     else
  9       :c
 10     end
 11   end
 12 end
```

```
> elixirc example.ex

== Compilation error in file example.ex ==
** (CompileError) example.ex:2: expected -> clauses for :else in "try"
    (stdlib) lists.erl:1239: :lists.map/2
    (stdlib) lists.erl:1239: :lists.map/2
```
### Expected behavior
```
** (SyntaxError) example.ex:6: syntax error before: else
```

### Parsimonious example
```
defmodule Test do
  def method do
    else if false do
      :a
    end
  end
end
```

### Discussion

Setting aside my embarrassing lapse in syntax to other languages that use `else if`, this occurred halfway down a ~300 line code file with a `try do` block as a red herring above it - I had to resort to a binary search commenting out method bodies to find the problem block of code.

Of note, the CompileError cites the method def line (line 2), rather than the line beginning with `else` (line 6). Everything up to that point is valid syntax, so I would expect the same error a misplaced `else` provides in other situations: `syntax error before: else`.

I recognize this probably isn't the highest priority issue ever, but I recall reading that Elixir treats confusing error messages as bugs, so here you go.

**Comment by josevalim** [comment]
The issue is that the syntax above *is* valid:

```iex
iex(1)> quote do
...(1)> defmodule Test do
...(1)>   def method do
...(1)>     else if false do
...(1)>       :a
...(1)>     end
...(1)>   end
...(1)> end
...(1)> end
iex(2)> IO.puts Macro.to_string v(1)
defmodule(Test) do
  def(method) do
    nil
  else
    if(false) do
      :a
    end
  end
end
:ok
```

So the one to complain is indeed the function definition since the `else` has been "misplaced". I.e. the code is valid syntatically but invalid semantically.

In any case, thanks for the report! :heart:

**Comment by michalmuskala** [comment]
If it were `def` complaining, it indeed wouldn't be that confusing, but it's the implicit `try` that is complaining, which is more confusing.

**Comment by josevalim** [comment]
@michalmuskala that's true.

**Comment by kelvinst** [comment]
I'm planning to tackle this tonight. OK? 😁
