### ISSUE TITLE
mix compile not picking up changes on macOS sierra

### ISSUE THREAD

**Issue by keiththomps** [elixir-lang/elixir#6483]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 20, Elixir 1.5.1 & master
* Operating system: macOS Sierra (10.12.6)

### Current behavior

Changes in source file not causing the file to register as stale. I first discovered this by not having a controller in a brand new phoenix 1.3 application be code reloaded. I was able to reproduce this on another mac by installing erlang, elixir, & phoenix.

Working off of 90217137c I add some [debug statements](https://github.com/keiththomps/elixir/commit/c94d5920513a75ab380c5120a00c96f96efb82b4) to the compiler and this is was I get from a newly generated project via `mix new example`:

<img width="1119" alt="screen shot 2017-08-19 at 12 11 39 pm" src="https://user-images.githubusercontent.com/666270/29488386-a781ce9a-84d7-11e7-9307-918c6b34d73f.png">

I've spent a few hours trying to figure this out. I don't know what is modifying the manifest, but I know it always happens **after** the file change because occasionally the manifest's modified time will be the second after the file's.

### Expected behavior

The changed file should be considered stale by the elixir compiler.

**Comment by josevalim** [comment]
@keiththomps can it possible be your editor running things behind the scenes and not writing the .beam files to disk? For example, can you reproduce this issue if you don't use an editor and instead you use `touch` and `mix compile` from the command line?

**Comment by keiththomps** [comment]
That was 100% it. I have vim running something in the background apparently. :) Thanks for sorting out my silly issue (super fast no less).
