### ISSUE TITLE
defdelegate with default values: confusing documentation link to private module

### ISSUE THREAD

**Issue by davidsulc** [elixir-lang/elixir#6487]
(Reposted from https://github.com/elixir-lang/ex_doc/issues/770 at @josevalim's request)

### Current behavior

ExDoc generates confusing documentation when functions are `defdelegate`d with default values. Example:

```elixir
defmodule Foo do
  defmodule Bar do
    @moduledoc false

    def hello(name, _options) do
      IO.puts "Hello, #{name}"
    end
  end

  @doc """
  Prints a welcoming message
  """
  defdelegate hello(name, options \\ []), to: __MODULE__.Bar

  @doc """
  Prints hi
  """
  def hi(name, options \\ []), do: IO.puts "Hi!"
end
```

In the above, I would like to have `Foo.Bar` as a private module (hence `@moduledoc false`), and expose the functionality via the public `Foo` API.

In this situation, ExDoc will generate the following docs:

> 
> ### hello(name)
> 
> Prints a welcoming message
> 
> ### hello(name, options)
> 
> See `Foo.Bar.hello/2`.
> 
> ### hi(name, options \\\\ [])
> 
> Prints hi

Note how the generated `defdelegate` docs differ from the docs for `hi/2` in cases that are similar. This is particularly confusing, as the reader is told to refer to `Foo.Bar.hello/2` which isn't publicly documented.

### Expected behavior

I would instead expect the documentation to yield a single documented function for `hello/2`:

> 
> ### hello(name, options \\\\ [])
> 
> Prints a welcoming message

**Comment by davidsulc** [comment]
Elixir 1.4.5, ExDoc 0.14 (didn't realise it wasn't the most recent: copied dep tuple from ExDoc readme)

**Comment by josevalim** [comment]
I could also verify it is fixed in master, thanks @jeffkreeftmeijer. Closing this then!

**Comment by jeffkreeftmeijer** [comment]
Haha, that's quick! For the record; [reproduced](https://github.com/jeffkreeftmeijer/elixir-6487/commit/0baa8263c88a34bb9072d89c8601cf80af9c8833) on 1.4.5 (still on ExDoc 0.16.3).
