### ISSUE TITLE
Possible bug on interaction between dialyzer and `throw`

### ISSUE THREAD

**Issue by renatomassaro** [elixir-lang/elixir#6491]
### Environment

* Elixir & Erlang versions (elixir --version): 

Erlang/OTP 20(.0.1) [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.1

* Operating system: 

FreeBSD 11.0 amd64
Also replicated on 64-bit Arch Linux with Elixir 1.5.1; OTP 20.0.1

### Current behavior

Running `dialyzer` on the `fails_dialyzer/2` function below raises an error that seems to be unexpected. The interesting bit is that when you remove the `throw` call, the `dialyzer` check is successful. This is portrayed on the `works_as_expected/2` function. Finally, the `workaround/2` function is the workaround solution we've come up to silence these errors. 
```elixir
defmodule Sample do

  # Fails with:
  #   The pattern 'error_a' can never match the type 'error_b' | 'false'
  #   The pattern 'error_b' can never match the type 'false'
  def fails_dialyzer(v1, v2) do
    with \
      true <- is_nil(v1) || :error_a,
      true <- not is_nil(v2) || :error_b
    do
      :foo
    else
      :error_a ->
        throw({:error, :a})
      :error_b ->
        throw({:error, :b})
    end
  end

  # Works as expected. The only difference is the removal of `throw`
  def works_as_expected(v1, v2) do
    with \
      true <- is_nil(v1) || :error_a,
      true <- not is_nil(v2) || :error_b
    do
      :foo
    else
      :error_a ->
        {:error, :a}
      :error_b ->
        {:error, :b}
    end
  end

  # Catch-all below works
  def workaround(v1, v2) do
    with \
      true <- is_nil(v1) || {:error, :a},
      true <- not is_nil(v2) || {:error, :b}
    do
      :foo
    else
      error = {_, _} ->
        throw(error)
    end
  end
end
```

### Expected behavior

Maybe this is an error on my part, but so far I can't figure out why, specially since the `works_as_expected/2` and `fails_dialyzer/2` seem equivalent to me. As such, I expected that both would report as returning `:foo | {:error, :a} | {:error, :b}`, with the `else` having to handle either `:error_a` or `:error_b`. Any ideas? 

For a more contextualized (real) example, here's the code that raised this pattern for the first time:
[raises error](https://github.com/renatomassaro/Helix/blob/c3609ae1182ccad9721bea3b8a70dcfdbe90cacf/lib/universe/bank/internal/bank_account.ex#L126)  | [workaround fix](https://github.com/renatomassaro/Helix/blob/7b507f5f504b71cb75b8222b2245777b3d87fd31/lib/universe/bank/internal/bank_account.ex#L126)

### Notes

It may be related to #6426, but the error messages are different, and this specific behavior only happens with ~~`Repo.rollback/1`~~ `throw`

**Comment by josevalim** [comment]
What if you use `throw` instead of `Repo.rollback`?

**Comment by renatomassaro** [comment]
Same error is raised.

**Comment by fishcakez** [comment]
@renatomassaro please can you paste the dialyzer warning(s)?

**Comment by renatomassaro** [comment]
Hi @fishcakez,

dialyzer output is:

```
lib/account/websocket/sample.ex:13: The pattern 'error_a' can never match the type 'error_b' | 'false'
lib/account/websocket/sample.ex:15: The pattern 'error_b' can never match the type 'false'
```

I've updated the post to use `throw` instead of `Repo.rollback`, since as noticed by @josevalim it is the actual problem, not `Repo` itself.

**Comment by fishcakez** [comment]
These warnings are unrelated to `throw` and it is just the warning from the `with` issue in #6426. I wanted to see the warnings to know if the warning was the function would never locally return (i.e dialyzer thought rollback or throw was always called).

**Comment by renatomassaro** [comment]
Oh, good to know it's the same, I thought it was a different bug due to the different message and lack of guard clauses (on my code anyway, perhaps Elixir generates a new code with guards under the hood). Keep up the good work :+1:
