### ISSUE TITLE
def (%__MODULE{}) do compiles (note __MODULE, not __MODULE__)

### ISSUE THREAD

**Issue by jeremyowensboggs** [elixir-lang/elixir#6497]
```
def purchase_time_valid?(%__MODULE{pickup_time: :asap} = cart, menu_data) do
...
end
```

I don't think this should compile.  What appears to be happening is that the name of the struct is being bound to `__MODULE`, but this seems weird.  I would expect this to be flagged by the compiler.

**Comment by josevalim** [comment]
@jeremyowensboggs the code above is valid, it would be the same as:

    def purchase_time_valid?(%_module{pickup_time: :asap} = cart, menu_data) do

or:

    def purchase_time_valid?(%_whatever{pickup_time: :asap} = cart, menu_data) do

or:

    def purchase_time_valid?(%_WHATEVER{pickup_time: :asap} = cart, menu_data) do

It can happen in many other circumstances, even on simple alias matches, atoms, etc. I don't think the compiler should try to guess typos because it is valid code after all.

In any case, thanks for the report.
