### ISSUE TITLE
Node.start function doesn't work properly

### ISSUE THREAD

**Issue by lanycrost** [elixir-lang/elixir#6500]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
* Operating system: Ubuntu 16.04 LTS

### Current behavior

When i try use Node.start function from iex mode nothing happens and error appears.

Node.start "user@comp" # Node.start "user"

```
{:error,
 {{:shutdown, {:failed_to_start_child, :net_kernel, {:EXIT, :nodistribution}}},
  {:child, :undefined, :net_sup_dynamic,
   {:erl_distribution, :start_link,
    [["user@lanycrost", :longnames, 15000], false]}, :permanent, 1000,
   :supervisor, [:erl_distribution]}}}
```

Thanks!

**Comment by josevalim** [comment]
Can you make sure EPMD is running?

    $ epmd -names

**Comment by lanycrost** [comment]
@josevalim I received this message: **epmd: Cannot connect to local epmd**
And one more thing` iex --sname user` command work for me.

**Comment by josevalim** [comment]
That's because epmd is not running. `--sname user` will automatically epmd for you though. So if you don't want t use `--sname` or `--name`, you need to make sure epmd is up and running. It is a matter of simply calling `epmd`.

**Comment by lanycrost** [comment]
@josevalim I get a message `epmd: up and running on port 4369 with data:` but Node.start still doesn't work.

**Comment by josevalim** [comment]
What happens when you try to start it with `iex --name user@lanycrost`. Can you make sure your current machine knows how to resolve lanycrost?

**Comment by lanycrost** [comment]
```
$ iex --name user@lanycrost 
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(user@lanycrost)1>
```

Please

**Comment by josevalim** [comment]
Thank you. Then I must say I do not understand why the error happens.

**Comment by lanycrost** [comment]
Thanks for the help. 

I started epmd manually and use atoms as names.

```
$ iex
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe]

Interactive Elixir (1.5.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Node.start :foo, :shortnames
{:ok, #PID<0.87.0>}
iex(foo@funtoo-tuxedo)2>
```
