### ISSUE TITLE
Weird cursor line jumps when moving cursor back after an error message

### ISSUE THREAD

**Issue by pejrich** [elixir-lang/elixir#6504]
Recently updated to Erlang/OTP 20 and Elixir 1.5.1

I have noticed some weird activity since then in IEx. After an error, for a line of code that goes to the end of the terminal line or past it, if I hit up to see my last command, then cursor back to the error, it jumps lines. I don't think this is Terminal/OSX related, as someone else noticed it on iTerm2.

\#\# I added the line break after `:public` just to show my exact Terminal width so you can repeat it.
```
iex(1)> :ets.new(:table, [:named_table, :bag, {write_concurrency, true}, :public
])
** (CompileError) iex:1: undefined function write_concurrency/0
```

Here I need to fix that and add : in front of write_concurrency. So I press up, and start going back, when my cursor gets to between the `b` and `l` in public (`pub|lic`), one more char back and it jumps up and floats in the line above it. It ONLY happens after the error. For example, if the error happens, then I hit enter, then up, and cursor back it works fine. It's just when the error message gets output, and I cursor back immediately after.

If this is not repeatable for others, or something specific to OSX, then sorry for posting in the wrong place, but I have a feeling it's Elixir/IEx related.

**Comment by josevalim** [comment]
I can reproduce it on Terminal but not on iTerm2. Now I have no idea if it is a Terminal bug or an Erlang shell one. :S

**Comment by pejrich** [comment]
@josevalim Are you using the same Elixir version in both? I only noticed in recently, so maybe it's Erlang20 or Elixir1.5 related. Never had it before, but I updated both at the same time, so it's hard to say which is the culprit. I'll try some other versions and check back.

**Comment by josevalim** [comment]
Same Elixir and Erlang versions, yes.

**Comment by ggcampinho** [comment]
I think the bug is related to the error in the function `move_cursor` in Erlang driver that I comment in this PR (https://github.com/erlang/otp/pull/1536).

If you put a `printf` right before the [move up](https://github.com/ggcampinho/otp/blob/master/erts/emulator/drivers/unix/ttsl_drv.c#L1260) you will see that when you are already on the first line the function thinks that it needs to move one line above. I'll see if I can submit a PR to fix this function.

**Comment by josevalim** [comment]
@ggcampinho awesome work getting these bugs explained and fixed! :heart:

**Comment by ggcampinho** [comment]
Glad to help :)
It was a bit more complex than I expected, but I opened a PR to fix the issue on Erlang. I'll follow up the status there.

**Comment by ggcampinho** [comment]
Fixed on Erlang https://github.com/erlang/otp/pull/1549, we can close this issue

**Comment by josevalim** [comment]
@ggcampinho :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by pejrich** [comment]
Thanks @ggcampinho and thanks @josevalim! Keep up the great work.
