### ISSUE TITLE
Warn if catch comes before rescue in try

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6511]

**Comment by devonestes** [comment]
I don't think I have the Erlang skills (yet) to work through this, but here's a commit with a failing test for this chore that's just waiting to be fixed if someone wants to work off this: https://github.com/devonestes/elixir/commit/072f79ff7d37cc54eddac8b9ae4ea79cb9c8e3be

**Comment by josevalim** [comment]
Thanks Devon! Regarding the test, you don't need the module nor the
function, just the try should do it!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by kelvinst** [comment]
I guess this can be closed since #6537 is merged. Right?

**Comment by whatyouhide** [comment]
Yes, thanks @kelvinst! 💟
