### ISSUE TITLE
List comprehension with binary pattern matching and String.to_atom on invalid Unicode data causes segfault

### ISSUE THREAD

**Issue by gnucifer** [elixir-lang/elixir#6516]
### Environment
Elixir: 1.5.1
Erlang: 20.0
OS: Debian GNU/Linux 8 (jessie)

### Current behavior
Elixir segfaults for me when running:
`for <<a :: binary-size(2), b :: binary>> <- ["c£1"], do: {String.to_atom(a), b}`
as the first line in an iex prompt. The weird thing is that it only segfaults with the list comprehension.

`<<a :: binary-size(2), b :: binary>> = "c£1"`
`String.to_atom(a)` 
Works and produces the correct error:
`** (ArgumentError) argument error
    :erlang.binary_to_atom(<<99, 194>>, :utf8)`

<<99, 194>> is incorrect Unicode data I presume since `£` is split in half by binary-size(2).

`for a <- [<<99, 194>>], do: {String.to_atom(a)}` works and produces the correct error.

`for <<a :: binary-size(2), b :: binary>> <- ["c€1"], do: {String.to_atom(a),  b}` also
works, which is also a bit odd.

Have tried this on two different computers, and hope it's reproducible. Have gotten some strange results when for example running `for <<a :: binary-size(2), b :: binary>> <- ["c€1"], do: {String.to_atom(a),  b}` first in the console, and then `for <<a :: binary-size(2), b :: binary>> <- ["c£1"], do: {String.to_atom(a), b}` works. But segfaults when running `for <<a :: binary-size(2), b :: binary>> <- ["c£1"], do: {String.to_atom(a), b}` as the first input.

### Expected behavior
Should produce:
`** (ArgumentError) argument error
    :erlang.binary_to_atom(<<99, 194>>, :utf8)
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:236: :erl_eval.expr/5
    (stdlib) erl_eval.erl:228: :erl_eval.expr/5
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3`

All examples above works with Elixir 1.4.1 and Erlang 19.3, so perhaps this is some kind of regression if reproducible? I'm not sure if this is an Elixir or Erlang bug, so sorry if this does not belong here.

**Comment by josevalim** [comment]
Thank you! It is indeed an Erlang bug but we need to translate it to Erlang and isolate it, so you did well in reporting it here. Here is the Erlang report: https://bugs.erlang.org/browse/ERL-474

Closing as it is now being tracked there, I will reopen here if necessary. :heart:
