### ISSUE TITLE
Raise if __block__ and __aliases__ identifiers are written literally

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6532]

**Comment by Eiji7** [comment]
Hey, @josevalim 
I know `:__aliases__` and `:__block__` from writing macros, but I'm not sure what you exactly want to achieve here. Do you mean that `__block__` (without a colon) should raise, but `:__block__` not? Can you give more description / examples for this issue? Maybe I could help you with it.

**Comment by whatyouhide** [comment]
This needs further explanation from José but I suspect he might mean to warn on things like 

```elixir
__aliases__(Foo.Bar)
```

**Comment by Eiji7** [comment]
@whatyouhide: Wow don't know about it, now I better see a problem - thanks.

**Comment by josevalim** [comment]
@Eiji7 exactly what @whatyouhide said. Thanks for asking!
