### ISSUE TITLE
In umbrella .app are not correct when using included application and start_phases

### ISSUE THREAD

**Issue by xadhoom** [elixir-lang/elixir#6533]
### Environment

* Elixir & Erlang versions (elixir --version): 1.5.1
* Operating system: Linux

### Current behavior

I'm scratching my head on how to accomplish sync startup between umbrella apps, but no luck right now.

The base erlang reference (what I'm trying to obtain) is: http://erlang.org/doc/design_principles/included_applications.html#id82330

I can use start_phases inside a single app to do things after the start callback and before the start returns , but I'm not able to sync several apps like the erlang reference does.

I've played with included_applications, extra and so on, but no luck.

Here's a sample repo for what I'm testing: https://github.com/xadhoom/sync_start_test

What I'm obtaining is:

> Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
> 
> SECONDARY: :go
> PRIMARY: :init
> PRIMARY: :go
> Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)>

### Expected behavior
While I'm expecting to have: init & go from the primary app and then go from the secondary, like:

> iex -S mix run --no-start
> Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)> Application.start(:primary)
> PRIMARY: :init
> PRIMARY: :go
> SECONDARY: :go
> :ok
> iex(2)> 

(this correct sequence has been obtained by modifyng by hand the .app file, see below)

### Additional notes
By looking into .app files, seems that primary app mod callback is wrong, it is: 

>{mod,{'Elixir.Primary.Application',[]}}

while it should be (according to erlang docs)

>{mod, {application_starter,['Elixir.Primary.Application',[]]}}

At the same time, the umbrella starter should not start automatically the included app.
If `--no-start` is omitted (with the modified app file), a weird callback sequence happens:

> iex -S mix 
> Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

> SECONDARY: :go
> PRIMARY: :init
> PRIMARY: :go
> SECONDARY: :go
> Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
> iex(1)> 

This also means that the user may be responsible to property handle the app tree dependency since bad thing may happen (like application not started at all).

**Comment by josevalim** [comment]
The umbrella app does not define an actual `.app` file. Maybe we should raise if someone defines `def application` in an umbrella project.

**Comment by xadhoom** [comment]
No, I'm speaking about generated primary.app and secondary.app

**Comment by xadhoom** [comment]
I just realized that in mix.exs I can set

>mod: {:application_starter, [Primary.Application, []]},

And this partially solves the issue, because the secondary app is started anyway, while it should not.
So maybe there's a way to avoid an umbrella app to be started automatically?

**Comment by josevalim** [comment]
@xadhoom I also pressed send prematurely, sorry. It was supposed to be a list of notes:

* Umbrellas will always start all children. You can tweak that by passing the `:apps` option in `def project` inside for the umbrella.

* You can change the `:mod` option to be what you desired.

**Comment by xadhoom** [comment]
mmmh I cannot get how the :apps option is meant to be used.
If I set it to apps: [:primary] it blames about not finding :secondary, maybe there is some other option?

**Comment by josevalim** [comment]
You still need to depend on `:secondary` from your `:primary` application using in_umbrella: true for all apps primary depends on. Always. Regardless of this discussion.

In any case, the issue here is that the umbrella always starts its children because it is necessary if you want to use things like `mix test` that runs across all apps. But because you can't start all of its children for the reasons above, you won't have `mix test` running for secondary anyway, so you may as well have an included_apps directory where :secondary exists and depend on it using a path dependency (in_umbrella is just a shortcut for a path dependency).

**Comment by xadhoom** [comment]
Ok about deps, I was just toying around to understand how is meant to be.

I'll play with your suggestion to check how to make it work.

**Comment by xadhoom** [comment]
Well, following your suggestion to add a local path dep outside the apps path does the trick.

I've updated my test repo https://github.com/xadhoom/sync_start_test, is this the correct way ?
If yes maybe I can add a small howto somewhere (where ?) to help others on same task :)

**Comment by josevalim** [comment]
Yup, that looks good. We will keep an eye if this is a common necessity and if so we will improve the docs. Thanks!
