### ISSUE TITLE
in OTP/20, dialyzer flags __info__/1 with -Woverspec due to missing :native, :native_address

### ISSUE THREAD

**Issue by evadne** [elixir-lang/elixir#6536]
Elixir 1.5.1, Erlang/OTP 20, macOS 10.12.6 (16G29).

In Erlang/OTP 20 new module info keys were introduced and the full type is currently as follows (see Erlang/OTP repository, `erts/preloaded/src/erlang.erl`):

```
-type module_info_key() :: attributes | compile | exports | functions | md5
                         | module | native | native_addresses.
-spec erlang:get_module_info(Module, Item) -> ModuleInfo when
      Module :: atom(),
      Item :: module_info_key(),
      ModuleInfo :: term().
get_module_info(_Module, _Item) ->
    erlang:nif_error(undefined).
```

However Elixir does not emit a corresponding spec; `:elixir_erl.add_info_function` currently emits:

```
add_info_function(Line, Module, Def, Defmacro) ->
AllowedArgs =
  lists:map(fun(Atom) -> {atom, Line, Atom} end,
            [attributes, compile, exports, functions, macros, md5, module]),
…
{Spec, Info}.
```

Elixir’s spec is missing `:native` and `:native_addresses` both accepted by `:erlang.get_module_info/2`. This causes a problem when the Elixir 1.5.1 application is run against dialyzer with `-Woverspec`:

```….ex:1: Type specification '…':'__info__'('attributes' | 'compile' | 'exports' | 'functions' | 'macros' | 'md5' | 'module') -> atom() | [{atom(),any()} | {atom(),byte(),integer()}] is a subtype of the success typing: '…':'__info__'('attributes' | 'compile' | 'exports' | 'functions' | 'macros' | 'md5' | 'module' | 'native' | 'native_addresses') -> any()```

It may be a good idea to amend the spec emitted by Elixir if building for OTP 20. I see that `erlang:system_info(otp_release)` has already been used in `:elixir_erl` so perhaps additional testing of the OTP version, for the purposes of emitting the correct spec, is acceptable.

**Comment by josevalim** [comment]
Thank you for the report @evadne! I am not sure we want to simply delegate everything to Erlang. I partially think that exporting `:exports` was a mistake as it leaks implementation details. So I would rather change the implementation to stop delegating everything to Erlang and only list the ones we want.

With this in mind, I would consider deprecating `:exports`. And possibly `:md5`. @elixir-lang/elixir what are your thoughts on this?

**Comment by fishcakez** [comment]
It is not good to change the spec until we are OTP 20+ because the older versions wouldn't support it and should only spec what is supported in all versions. Using `overspec` can produce false positives, such as this, so as a rule of thumb we should not make changes purely based on those type of warnings. It is perfectly valid to support a subset of another functions behavior when its wrapped.

I think the `:exports` and other keys are a separate issue but would be ok for that to go because we don't have that concept in Elixir. I am unsure if people would use `:md5` as part of a check for differences.

**Comment by josevalim** [comment]
@fishcakez `:md5` is still available via module_info. I am thinking `__info__` should focus on non VM specific attributes, so it is also available on places such as elixirscript. @bryanjos does ElixirScript make `__info__` available? And if it did/does, which of those attributes could you support: attributes, compile, exports, functions, macros, md5, module?

@fishcakez we also rely a lot on the `__info__(:compile)[:source]`. It may be worth making it first class as `:source` and then deprecating `:compile` too.

**Comment by fishcakez** [comment]
@josevalim I think that moving away from VM specific attributes is a good choice when they will still be available from Erlang module calls. In our situation the `:md5` is of the `:md5` of the wrong thing really.

**Comment by bryanjos** [comment]
@josevalim ElixirScript does make `__info__` available. Right now it supports: functions, macros, and module. `attributes` could be supported. I've only ever seen attributes that are set to persist show up in the attributes field in debug info. Can support `exports` too. Not sure all the keys in `compile` can be supported, but the debug info contains the source file path. So it would be possible to at least make `__info__(:compile)[:source]` work. I am not sure about `md5`.

**Comment by josevalim** [comment]
@bryanjos i would say attributes are necessary, it is part of the language semantics. :)

**Comment by josevalim** [comment]
@bryanjos all the compiler info is in the beam file:

    :beam_lib.chunks :code.which(String), [:compile_info]

So you could also read it when reading the debug_info chunk.

**Comment by josevalim** [comment]
One of the things we could do is to store the compile info chunk to store metadata such as the elixir version. But unfortunately that is listed inside the options part:

```iex
iex> :beam_lib.chunks :code.which(String), [:compile_info]
{:ok, {String,
  [
    compile_info: [
      options: [elixir: '1.4.0'],
      version: '7.1',
      source: '/Users/jose/OSS/elixir/lib/elixir/lib/string.ex'
    ]
  ]}}
```

**Comment by bryanjos** [comment]
@josevalim thanks. Is it possible to call `__info__` on the module I'm compiling to JS and compile the result into the `__info__` function that's being created in JS?

```
# get functions from module
functions = module.__info__(:functions)

# compile result to JS AST
functions_js_ast = Form.compile!(functions, state)

# insert into __info__ function when given the `:functions` as a parameter
```

So far from trying it that seems to be working, but also wanted to know if they is ok or if it's not good to do it that way

**Comment by josevalim** [comment]
I have sent a proposal to allow us to add our own information to the compile chunk, so let's move forward with it being "public" as well.

**Comment by josevalim** [comment]
@bryanjos that looks great, yes!

**Comment by josevalim** [comment]
Closing this for the reasons given by @fishcakez. Thanks for the report @evadne! :+1:
