### ISSUE TITLE
Nested try blocks and erlang:get_stacktrace warning

### ISSUE THREAD

**Issue by deadtrickster** [elixir-lang/elixir#6539]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.4.4 & OTP 20
* Operating system: Linux

### Current behavior

```elixir
    def(sometimes_raise(arg)) do
      try() do
        5 / arg
      rescue
        exception in ArithmeticError ->
          stacktrace = System.stacktrace
          try do
            :io.format("qwe")
          rescue
            _ -> IO.puts("internal rescue")
          end
          reraise(exception, stacktrace)
      end
    end
```

produces 

`warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)` (points to `stacktrace = System.stacktrace` line).

### Expected behavior

No warning

**Comment by josevalim** [comment]
This has been isolated and reported as an Erlang bug: https://bugs.erlang.org/browse/ERL-478 Thank you!
