### ISSUE TITLE
Rebar3 compile error

### ISSUE THREAD

**Issue by Pouriya-Jahanbakhsh** [elixir-lang/elixir#6544]
Hi elixir developers, Im a simple Erlang developer and i have to include some elixir apps to my Erlang project, i specified elixir in deps of my rebar.config and in compile time,  Rebar3 said that [This file](https://github.com/elixir-lang/elixir/blob/12254e2cfda543c9af913ed2e5d48f3081978add/lib/mix/test/fixtures/archive/ebin/local_sample.app#L2) has not vsn field and i could not compiling elixir correctly.

I know i can use some rebar3 plugins for compiling elixir apps inside erlang project which might compile elixir inside erlang correctly, but i have some issue abour generating release using them (actualy relx has), but i wrote simple make file which does all things and my problem is just this little vsn field :-S

Can you put it to these files?

**Comment by josevalim** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. If you believe this is an issue, please file the issues template accordingly. Thank you!
