### ISSUE TITLE
Multiple @callback with the same name/arity are discarded

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#6546]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6.0-dev, OTP 20
* Operating system: macOS

### Current behavior

Given the following module:

```elixir
defmodule Test do
  @callback test(:foo) :: String.t
  @callback test(:bar) :: [String.t]
end
```

When later getting callback info from iex, we only get the last clause:

```elixir
iex(1)> b Test
@callback test(:bar) :: [String.t()]
```

### Expected behavior

I'm not 100% sure what the expected behaviour is, two possible solutions I see are:

* return all the clauses in `b`.
* warn/raise when defining multiple callbacks like that in the module.

**Comment by sorentwo** [comment]
I've wondered about this recently as well, and didn't find anything conclusive in the Erlang docs. Hopefully somebody more knowledgeable will provide the correct answer.

**Comment by josevalim** [comment]
The first step is to see if Erlang supports multiple callbacks with the same name and, if so, does it return the same result?

**Comment by alco** [comment]
Erlang/OTP 20.0 refuses to compile such code:

```erlang
-module(test).

-callback test(foo) -> string.
-callback test(bar) -> [string].
```

```
$ erlc test.erl
test.erl:4: callback test/1 already defined
```

**Comment by kelvinst** [comment]
So let's add a compile error for it right?

Just one more thing: Erlang/OTP 20 also refuses to compile duplicated spec definitions.

```erlang
-module(test).

-spec test(foo) -> string.
-spec test(bar) -> [string].
```

```erlang
$ erlc test.erl
test.erl:4: spec for test/1 already defined
```

Let's add the compile check for both?

**Comment by josevalim** [comment]
The way multiple clauses work in Erlang is that they are separated by comma:

```erlang
-module(foo).
-callback test(foo) -> string;
              (bar) -> [string].
```

In Elixir we don't have the same syntax so we allow the same one to specified multiple times and then we merge them together in a later pass.

We do this later pass for specs but apparently we don't do it for callbacks, so that's what needs to be done. :)

**Comment by kelvinst** [comment]
> The way multiple clauses work in Erlang is that they are separated by comma:

Well, living and learning. 🤣

> We do this later pass for specs but apparently we don't do it for callbacks, so that's what needs to be done. :)

If no one else is interested, I can do it! :)

**Comment by josevalim** [comment]
Please go ahead :)
