### ISSUE TITLE
Too slow to compile a function with many clauses.

### ISSUE THREAD

**Issue by Kabie** [elixir-lang/elixir#6553]
### Environment

```
Linux karch 4.12.8-2-ARCH #1 SMP PREEMPT Fri Aug 18 14:08:02 UTC 2017 x86_64 GNU/Linux

Erlang/OTP 20 [erts-9.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.5.1
```

### Current behavior

An example:

```elixir
defmodule SlowCompilation do

  for i <- 1..10_000 do
    def test(unquote(i)) do
      unquote(i)
    end
  end

end
```

The compile time doesn't scale with the number linearly:

```
$ time elixir slow_compilation.ex  # 10_000
elixir slow_compilation.ex  1.02s user 1.81s system 124% cpu 2.279 total
$ time elixir slow_compilation.ex  # 20_000
elixir slow_compilation.ex  2.94s user 4.95s system 108% cpu 7.258 total
$ time elixir slow_compilation.ex  # 30_000
elixir slow_compilation.ex  7.00s user 8.25s system 107% cpu 14.142 total
$ time elixir slow_compilation.ex  # 40_000
elixir slow_compilation.ex  15.74s user 13.01s system 106% cpu 26.922 total
$ time elixir slow_compilation.ex  # 50_000
elixir slow_compilation.ex  29.50s user 16.03s system 104% cpu 43.410 total
```

### Expected behavior

The corresponding erlang code(function with thousands of clauses) compiles way faster.

A profiling leads me to this:

https://github.com/elixir-lang/elixir/blob/2e1e51c4d0e72836cf1ef57c666675adde03b05e/lib/elixir/src/elixir_def.erl#L291-L293

This `ets:match` call will do a full scan to the defs table. And it would have a huge impact for functions with many clauses, since all the `{clauses, Tuple}`s are in the same table with the `{def, Tuple}`s. With more clauses added, the scan became slower, hence the result.

I would suggest using a different ets structure. Either by separate defs and clauses, or make the key can be specified in this match.

**Comment by josevalim** [comment]
Can you please file the issue template and also include Elixir version and so on? Thank you.

**Comment by josevalim** [comment]
So the given code takes 3 seconds on master and Elixir v1.5 since we have fixed this a couple months ago. If you can still reproduce on more recent versions, please let us know. Thank you.

**Comment by Kabie** [comment]
I didn't make myself clear. The problem is not about this particular example, but the compile time does not scale with the number of clauses linearly.

If I have a function with 50_000 clauses, I would expect the compile time be ~5x to the same function with 10_000 clauses. But that's not the behavior in both 1.5.1 and master.

By changing the number of clauses in the example:

| clauses | compile time | scale
|---------|--------------|-------
| 10_000  | 2.134s       | 1.0x
| 50_000  | 43.119s      | 20.2x
| 100_000 | 199.56s      | 93.5x

And I found, it's this `ets:match` call make this defaults check a O(n^2) algorithm. I hope you take another look at this. Thanks.

@josevalim

**Comment by josevalim** [comment]
Thank you, that clarifies it!
