### ISSUE TITLE
:code.get_object_code/1 returns a "/../" in the beam path

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#6555]
Elixir 1.5.1
Ubuntu 17.04 and Debian 9

Small nitpick. This only happens for Elixir modules.
```elixir
:code.get_object_code List
{List,
 <<70, 79, 82, 49, 0, 0, 71, 36, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 3, 237,
   0, 0, 0, 95, 11, 69, 108, 105, 120, 105, 114, 46, 76, 105, 115, 116, 8, 95,
   95, 105, 110, 102, 111, 95, 95, 9, 102, 117, ...>>,
 '/usr/local/lib/elixir/bin/../lib/elixir/ebin/Elixir.List.beam'}
```
That path should be '/usr/local/lib/elixir/lib/elixir/ebin/Elixir.List.beam'.

**Comment by josevalim** [comment]
Thanks. That's because the executable passes the path to be `../lib/elixir/*`. I don't see a reason to normalize the path, so I am inclined to keep things as is.

**Comment by whatyouhide** [comment]
I think we can keep the path as is as well. If so, can we close this issue?
