### ISSUE TITLE
Error when starting multiple Registries in supervision tree

### ISSUE THREAD

**Issue by jlevycpa** [elixir-lang/elixir#6556]
I have a need to start two different Registry processes in my supervision tree. My list of children includes the following:

```
...
{Registry, [keys: :unique, name: Wif.ConnectionRegistry]},
{Registry, [keys: :unique, name: Wif.TriggerRegistry]},
...
```
I received this error when I compiled:
`** (Mix) Could not start application wif: Wif.Application.start(:normal, []) returned an error: bad child specification, more than one child specification has the id: Registry.`

It looks like [`Registry.child_spec/1`](https://github.com/elixir-lang/elixir/blob/dbcc36ddb25782155cf6c7712019554b599b41d3/lib/elixir/lib/registry.ex#L305) includes the fixed value of `Registry` as the child id, which would prevent multiple Registry processes from being started under the same supervisor without pre-1.5 style child specs or some other workaround. 

I propose that instead, when the `name` option is used, the `name` is used as the child id. Alternatively, a separate `id` parameter could be passed. 

Please let me know if you would be open to a PR or if I'm missing something.

**Comment by josevalim** [comment]
That's a great suggestion. :+1: A PR will definitely be welcome.

**Comment by yordis** [comment]
@josevalim how would you do the testing for this https://github.com/yordis/elixir/commit/9b410159aecca43ef6d2a718ac17f8409705c833 ?

I could just open that function and test the lookup or I could setup the whole environment with the supervision tree so I can see it pass

**Comment by josevalim** [comment]
@yordis for the test, calling `child_spec(opts)` on the Regitry defined in the tests themselves should be enough.

**Comment by jlevycpa** [comment]
Just went to put the PR together, but I see you beat me to it!

**Comment by yordis** [comment]
@jlevycpa sorry I saw this was 5 hours ago when I did it!

**Comment by jlevycpa** [comment]
@yordis no worries. I wrote this on my way out and just got back.

**Comment by whatyouhide** [comment]
Closed by https://github.com/elixir-lang/elixir/pull/6560.
