### ISSUE TITLE
NaiveDateTime.add/2 failures on year 9999

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#6561]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.5.1/OTP 20
* Operating system: macOS Sierra

### Current behavior

```elixir
iex> NaiveDateTime.add(~N[9999-12-31 23:59:59], 1)
%Inspect.Error{message: "got ArgumentError with message \"argument error\" while inspecting %{__struct__: NaiveDateTime, calendar: Calendar.ISO, day: 1, hour: 0, microsecond: {0, 0}, minute: 0, month: 1, second: 0, year: 10000}"}
```

Another somewhat similar failure is:

```elixir
iex> NaiveDateTime.add(~N[0000-01-01 00:00:00], -1)
** (FunctionClauseError) no function clause matching in :calendar.day_to_year/1
```

although this should be addressed by https://github.com/elixir-lang/elixir/issues/6294

### Expected behavior

I'm not sure what's the correct behavior. I'll admit it's fairly obscure edge case.

Currently we have this spec:

```elixir
iex> s NaiveDateTime.add/3
@spec add(t(), integer(), System.time_unit()) :: t()
```

Perhaps it should actually be: ` :: {:ok, t} | {:error, term}` to account for cases where arithmetic breaks? Is it conceivable that other calendars might have similar restrictions in terms of dates they can represent? Or maybe we should lift `9999` max year restriction in ISO? Or at least improve error message for `add/3` throwing e.g. `ArgumentError` instead?

**Comment by michalmuskala** [comment]
:+1: for raising consistent errors and documenting that. I don't think there's a meaningful action you could take if the calendar does not support the date you're trying to use - and a possible "meaningful action" is for me a requirement to returning the tuples instead of raising.

**Comment by josevalim** [comment]
We can't change the signature of NaiveDateTime.add, so that's out of the way. :+1: for raising a proper exception.

**Comment by wojtekmach** [comment]
I've checked it on `master` and it provides excellent error messages:

```elixir
iex(1)> NaiveDateTime.add(~N[9999-12-31 23:59:59], 1)
** (FunctionClauseError) no function clause matching in Calendar.ISO.date_from_iso_days/1

    The following arguments were given to Calendar.ISO.date_from_iso_days/1:

        # 1
        3652425

    Attempted function clauses (showing 1 out of 1):

        def date_from_iso_days(days) when is_integer(days) and (days >= 0 and days <= 3652424)

    (elixir) lib/calendar/iso.ex:140: Calendar.ISO.date_from_iso_days/1
    (elixir) lib/calendar/iso.ex:76: Calendar.ISO.naive_datetime_from_iso_days/1
    (elixir) lib/calendar/naive_datetime.ex:672: NaiveDateTime.from_iso_days/3
```

```elixir
iex(1)> NaiveDateTime.add(~N[0000-01-01 00:00:00], -1)
** (FunctionClauseError) no function clause matching in Calendar.ISO.date_from_iso_days/1

    The following arguments were given to Calendar.ISO.date_from_iso_days/1:

        # 1
        -1

    Attempted function clauses (showing 1 out of 1):

        def date_from_iso_days(days) when is_integer(days) and (days >= 0 and days <= 3652424)

    (elixir) lib/calendar/iso.ex:140: Calendar.ISO.date_from_iso_days/1
    (elixir) lib/calendar/iso.ex:76: Calendar.ISO.naive_datetime_from_iso_days/1
    (elixir) lib/calendar/naive_datetime.ex:672: NaiveDateTime.from_iso_days/3
iex(1)>
```

sorry for the noise!
