### ISSUE TITLE
Make sure IEx.Helpers.open/1 works with Elixir modules

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6562]
Elixir is usually precompiled which means today it points to the precompiled place. We can try to detect if the module comes from any of Elixir built-ins and translate that accordingly.

**Comment by wojtekmach** [comment]
Some more context around this in: https://github.com/elixir-lang/elixir/issues/6348

**Comment by wojtekmach** [comment]
@josevalim what do you think about shipping `lib/**/*.ex` files in `Precompiled.zip` (and same for https://repo.hex.pm/builds/elixir/v1.5.2-otp-20.zip using bob)? I think we're almost there:

```
~% iex
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> open Enum
Could not open: "/Users/wojtek/.asdf/installs/elixir/1.5.2/bin/../lib/elixir/lib/enum.ex". File is not available.
```

cc @ericmj

**Comment by ericmj** [comment]
Given the exception helpers we have now I think we should ship the source from files with the precompiled zip.

**Comment by ericmj** [comment]
We need to be careful so we can find the source files regardless where the zip file is unzipped though. I’m not sure if this is possible so testing will need to be done.
