### ISSUE TITLE
Misleading child_spec error for missing module

### ISSUE THREAD

**Issue by pikeas** [elixir-lang/elixir#6565]
Elixir 1.5.1

```
def start(_type, _args) do
  Supervisor.start_link([DoesNotExist], strategy: :one_for_one, name: MyApp.Supervisor)
end
```

This will fail with a misleading error: 
```
** (Mix) Could not start application foo: MyApp.Application.start(:normal, []) returned an error: an exception was raised:
    ** (ArgumentError) The module DoesNotExist was given as a child to a supervisor
but it does not implement child_spec/1.
```

While it's technically correct that the module does not implement `child_spec/1`, it would be preferable to throw an error about the module not being defined instead.

**Comment by OvermindDL1** [comment]
I'm bored and have a few minutes free, let me go ahead and fix this since it is pretty trivial to do if no objections (and I've been hit by it before when I forgot to alias something >.>).  PR incoming when done.
