### ISSUE TITLE
manager in mix.lock is not being populated

### ISSUE THREAD

**Issue by chulkilee** [elixir-lang/elixir#6570]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.5.1 / Erlang/OTP 20 [erts-9.0.4]
* Operating system: Mac

### Current behavior

```sh
mix new hello_world
cd hello_world

# no mix.lock file
sed '# {:dep_from_hexpm, "~> 0.3.0"},'
sed -i.bak 's/# {:dep_from_hexpm, "~> 0.3.0"},/{:httpoison, "~> 0.13"},/' mix.exs
rm mix.exs.bak

mix deps.get
cat mix.lock | grep '"hackney":' | awk '{print $6}'
# [],

mix deps.compile
cat mix.lock | grep '"hackney":' | awk '{print $6}'
# [],

# re-running deps.get does not populate them
mix deps.get
cat mix.lock | grep '"hackney":' | awk '{print $6}'
# [],

rm mix.lock

mix deps.get
cat mix.lock | grep '"hackney":' | awk '{print $6}'
# [:rebar3],
```

### Expected behavior

I don't know much about mix internal - maybe compile is required to detect managers. Then I think `deps.compile` should backfill manager fields.

If manager field is not required (e.g. can be deferred to compile task), then why is it in `mix.lock` file?

**Comment by josevalim** [comment]
This seems to be a hex issue, as hex is responsible for filling that field. To clarify, I believe the issue you are reporting is that this makes the lock file a bit non-deterministic, right?

Can you please let us know your Hex version? Just run `mix hex.info`. Thanks!

**Comment by chulkilee** [comment]
```
Hex:    0.17.1
Elixir: 1.5.1
OTP:    20.0.4

Built with: Elixir 1.5.1 and OTP 18.3
```

**Comment by josevalim** [comment]
Closing this since it is a hex bug. Thanks!
