### ISSUE TITLE
v1.5.1 Kernel & Kernel.SpecialForms documentation issue

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#6571]
### Environment

Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1

Ubuntu 16.04

### Current behavior

The v1.5.1 documentation does not disambiguate functions and macros; everything is listed as a function.

So you might be surpised, as I was :-), if you do this

`Kernel.SpecialForms.__info__(:functions)`

and get an empty list.

### Expected behavior

Unless my memory is playing up, I feel sure Kernel docs once did separate into functions and macros?

Pragmatically it makes no difference but the docs should be correct IMHO.

**Comment by josevalim** [comment]
The division between functions and macros in the docs caused difficulty when learning new APIs. You can see that on the right side, close to the source link, we still say they are a "macro". Please open up an issue in ExDoc if you would like to discuss how those should be exhibited. Thank you!
