### ISSUE TITLE
Elixir 1.5.1: elixir -v crashes

### ISSUE THREAD

**Issue by raif-s-naffah** [elixir-lang/elixir#6580]
running the above on Fedora 26 crashes w/...

```
$ elixir -v
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done
```

the dump file is too large to attach (412KB) unless requested.  the first few lines follow:

```
=erl_crash_dump:0.3
Sun Sep 17 16:16:18 2017
Slogan: init terminating in do_boot ()
System version: Erlang/OTP 19 [erts-8.3.5.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]
Compiled: Mon Jul 31 19:38:44 2017
```

**Comment by josevalim** [comment]
How did you install Elixir? This usually means that Elixir was not compiled at all or that it cannot find its .beam files.

**Comment by raif-s-naffah** [comment]
you're of course right!  i first installed from the ZIP (download) from github.

installing the 'pre-compiled' version linked from the install page [1] works w/o problem:
```
$ elixir -v
Erlang/OTP 19 [erts-8.3.5.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```

apologies for the noise.
