### ISSUE TITLE
String.valid? is true, but doesn't correspond to any character assignment.

### ISSUE THREAD

**Issue by sergiotapia** [elixir-lang/elixir#6581]
### Environment

* Elixir & Erlang versions (elixir --version): 
→ elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.4.5

* Operating system: Mac OS Sierra

### Current behavior

```
String.chunk(my_string, :printable)
["normal html", <<227, 175, 226, 189, 226, 191>>, "normal html"]
```

`String.valid?` returns true for `my_string`.

>According to the unicode table these appear in the valid utf-8 range, but there is no character assignment (that I could find). Hence valid as encoding, but not printable since there is no character assignment.

>May be worth filing an issue on Elixir?
---

More details can be found on the Elixir forum thread where I originally asked this question.

https://elixirforum.com/t/cant-save-html-from-a-website-to-postgres-utf-8-field-any-tips/8741/9

**Comment by josevalim** [comment]
They are valid according to the Unicode standard. See "Are noncharacters invalid in Unicode strings and UTFs?" here: http://www.unicode.org/faq/private_use.html.

Thanks for the report!
