### ISSUE TITLE
ExUnit not recognising differently named apps in umbrella project

### ISSUE THREAD

**Issue by andrewtimberlake** [elixir-lang/elixir#6582]
If I setup an umbrella project but name one of the apps with a different directory than the app name, ExUnit doesn’t run that apps tests.

```bash
$ mix new ex_unit_umbrella --umbrella
$ cd ex_unit_umbrella/apps
$ mix new my_app
$ mix new api --app my_app_api --module MyAppAPI
$ cd ../
$ mix test
==> my_app_api
Compiling 1 file (.ex)
Generated my_app_api app
==> my_app
Compiling 1 file (.ex)
Generated my_app app
==> my_app_api
** (Mix) Could not start application api: could not find application file: api.app
```

The error is expected. To fix the error, I add `apps: [:my_app, :my_app_api],` to my project list.

Now when I run mix test for the umbrella, only the tests for `:my_app` are run, `:my_app_api` is ignored.

```bash
$ mix test
==> my_app
Compiling 1 file (.ex)
Generated my_app app
==> my_app
..

Finished in 0.04 seconds
2 tests, 0 failures

Randomized with seed 785789
```

I would expect it to run test for both apps.

Renaming the app makes it work again.

```bash
$ mv apps/api/ apps/my_app_api
$ mix test
==> my_app_api
Compiling 1 file (.ex)
Generated my_app_api app
==> my_app
..

Finished in 0.03 seconds
2 tests, 0 failures

Randomized with seed 851521
==> my_app_api
..

Finished in 0.03 seconds
2 tests, 0 failures

Randomized with seed 851521
```

### Environment

* Elixir 1.5.1, Erlang 20.0
* Operating system: macOS Sierra 10.12.6

**Comment by josevalim** [comment]
The name of your application should be the name of the directory in apps.

**Comment by andrewtimberlake** [comment]
Then what is the purpose of this setting in `project`?
`apps: [:my_app, :my_app_api]`

**Comment by yordis** [comment]
@andrewtimberlake the name of the folders

**Comment by josevalim** [comment]
@andrewtimberlake it gives you control over the ordering and some folks also have multiple apps in apps but they want just some of them to be managed by the umbrella.

**Comment by andrewtimberlake** [comment]
Okay, thanks
