### ISSUE TITLE
Filter ExUnit tests by name

### ISSUE THREAD

**Issue by glittershark** [elixir-lang/elixir#6584]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 20 [erts-9.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
* Operating system: 
Linux 4.12.10-1-ARCH #1 SMP PREEMPT Wed Aug 30 12:18:42 CEST 2017 x86_64 GNU/Linux

----------

Maybe I'm missing something, but it doesn't look like it's possible to filter running tests (ie via mix tests) by their full name. I took a look in the source and it looks like something like the following patch would work:
```patch
diff --git a/lib/ex_unit/lib/ex_unit/case.ex b/lib/ex_unit/lib/ex_unit/case.ex
index a54402077..bbdb1f5f1 100644
--- a/lib/ex_unit/lib/ex_unit/case.ex
+++ b/lib/ex_unit/lib/ex_unit/case.ex
@@ -452,7 +452,7 @@ defmodule ExUnit.Case do
       |> normalize_tags
       |> validate_tags
       |> Map.merge(%{line: line, file: file, registered: registered, async: async,
-                     describe: describe, describe_line: describe_line, type: type})
+                     describe: describe, describe_line: describe_line, type: type, name: name})

     test = %ExUnit.Test{name: name, case: mod, tags: tags, module: mod}
     Module.put_attribute(mod, :ex_unit_tests, test)
```
But I'm not sure how to go about testing it

**Comment by josevalim** [comment]
The test name and module are already added to the tags automatically later on: https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/runner.ex#L138

**Comment by glittershark** [comment]
holy crap you're fast.
That's awesome, thanks!
