### ISSUE TITLE
Use a different random seed for each ExUnit test

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#6587]
We want to move from a global ExUnit random seed to a random seed for each test (maybe based on "module + test name") that is generated starting from the original seed. This will be useful to run single tests that use randomness (through something like [stream_data](https://github.com/whatyouhide/stream_data)) in a reproducible way. \cc @josevalim

**Comment by josevalim** [comment]
@whatyouhide should we change ExUnit.seed to use the pdict and then do the global lookup then?

**Comment by whatyouhide** [comment]
@josevalim yeah I think that makes sense.
