### ISSUE TITLE
Date parsing with JSON formatted date strings

### ISSUE THREAD

**Issue by mfeckie** [elixir-lang/elixir#6592]
This issue has appeared when addressing deprecations with Ecto.Date.  Now that Ecto recommends using the standard library for dates, parsing of JSON formatted dates no longer behaves as expected.

There does not seem to be similar functionality as this https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/date_time.ex#L145-L147 in the standard library's implementation of date parsing.

### Environment

* Elixir 1.5 + Erlang 20
* Operating system: 
Mac + Ubuntu

### Current behavior

```elixir
iex(1)> Date.from_iso8601("2017-09-21T23:44:52.115Z")
{:error,
 :invalid_format}
```

### Expected behavior

```elixir
iex(1)> Date.from_iso8601("2017-09-21T23:44:52.115Z")
{:ok,
 ~D[2017-09-21]}
```

**Comment by ggcampinho** [comment]
@mfeckie I think you want to use `DateTime` module, not `Date`

https://hexdocs.pm/elixir/DateTime.html#from_iso8601/2

**Comment by mfeckie** [comment]
Thanks for the suggestion, but I specifically want a `Date`.

Because JSON always sends a datetime, not being able to accept this string type is a deviation from previous behaviour with `Ecto.Date`

**Comment by ggcampinho** [comment]
You can just convert after to `Date`, I would imagine that this behaviour is intended.

```
iex(1)> {:ok, datetime, _} = DateTime.from_iso8601("2017-09-21T23:44:52.115Z") 
{:ok, #DateTime<2017-09-21 23:44:52.115Z>, 0}
iex(2)> DateTime.to_date(datetime)
~D[2017-09-21]
```

**Comment by mfeckie** [comment]
It's currently handled by default with `Ecto.Date`, I'm suggesting that in addressing the deprecation, the change does not support existing behaviour.

Whilst your suggestion remains correct, if I'm handling dates manually, the Ecto deprecation will cause breakages for numerous applications where there is a frontend communicating dates from javascript

**Comment by josevalim** [comment]
Thanks @mfeckie. That should be handled in Ecto. Can you please open up an issue there? Thank you!
