### ISSUE TITLE
Can't use UTF-8 on Windows 7 64 bit

### ISSUE THREAD

**Issue by lkppo** [elixir-lang/elixir#6600]
Hello,

I have put in a file test.exs, encoded in UTF-8, the very first sample of the tutorial (IO.puts "Hello world from Elixir") and launched with PowerShell and cmd the command bellow :

`> elixir.bat .\test.exs`

I have also tested those commands :

```
> iex.bat
Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> IO.puts "BÉPO"
** (UnicodeConversionError) invalid encoding starting at <<144, 80, 79, 34, 10>>
    (elixir) lib/string.ex:1840: String.to_charlist/1
iex(1)> Terminer le programme de commandes (O/N) ? o
> chcp 65001
Page de codes active : 65001
> iex.bat
Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> IO.puts "BÉPO"
```

After I changes the page code, the output in iex with a É character never return! I can only use Ctrl+C to end.

### Environment

* Erlang/OTP 20 [erts-9.0] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] Elixir 1.5.1
* Operating system: Windows 7 Pro 64 bit

### Current behavior

```
> ** (SyntaxError) test.exs:1: unexpected token: "´╗┐" (column 1, codepoint U+FEFF)
>     (elixir) lib/code.ex:376: Code.require_file/2
```

### Expected behavior

`> Hello world from Elixir`

**Comment by josevalim** [comment]
Can you try running `iex.bat --werl` and let us know if it works there? I believe this is a duplicate, I will try to find a previous one.

**Comment by josevalim** [comment]
Found it! #5596

**Comment by lkppo** [comment]
iex.bat --werl launch a erlang interpreter

![werl](https://user-images.githubusercontent.com/10128284/30834202-5fa9f6cc-a252-11e7-939e-c1ad8b84c7a3.png)
UTF-8 is ok with that.

**Comment by josevalim** [comment]
Thanks for checking. If you follow the linked issue, we have reported this as an Erlang bug and it has unfortunately been tagged as won't fix. So you need to use --werl. You can set the `USE_WERL` environment variable to `1` in your system configuration if you always want to use --werl.

**Comment by lkppo** [comment]
Ok, I read the first report. Too bad. How can I execute my script with werl interpreter without opening it?

**Comment by josevalim** [comment]
I am not quite sure if it is possible. AFAIK werl always open up as a separate window since it needs to use a completely separate input mode. You can try using other shells such as powershell and mingw.

**Comment by lkppo** [comment]
Ok, I tried with Git Bash MINGW32 and it's half broken :

```
S@F MINGW32 ~
$ elixir text.exs
Hello world from Elixir

S@F MINGW32 ~
$ elixir text.exs
Hello world from Elixir B├ëPO
```

With cygwin32 it works.

It can go for home scripts but I can not do DIY on a prod server. Pity.

Thanks for you help josevalim.
