### ISSUE TITLE
Registry.match/4 does not support :_ for the key

### ISSUE THREAD

**Issue by Trevoke** [elixir-lang/elixir#6602]
### Environment

* Elixir & Erlang versions (elixir --version): 1.5.1 and 20.0
* Operating system: OSX

### Current behavior

```elixir
iex(41)> 1..6 |> Enum.map(&Integer.to_string/1) |> Enum.map(&Registry.lookup(World.LocationRegistry, &1))
[[{#PID<0.314.0>, "1"}], [{#PID<0.317.0>, "2"}], [{#PID<0.319.0>, "3"}],
 [{#PID<0.322.0>, "4"}], [{#PID<0.325.0>, "5"}], [{#PID<0.2477.0>, "6"}]]
iex(42)> Registry.match World.LocationRegistry, "1", "1"
[{#PID<0.314.0>, "1"}]
iex(43)> Registry.match World.LocationRegistry, :_, :_
[]
```

### Expected behavior

```elixir
Registry.match World.LocationRegistry, :_, :_
[{#PID<0.1883.0>, "5"}, {#PID<0.1877.0>, "3"}, {#PID<0.1872.0>, "1"},
 {#PID<0.1880.0>, "4"}, {#PID<0.1875.0>, "2"}]
```

This is despite the CHANGELOG which says that this is now possible.

**Comment by fishcakez** [comment]
@Trevoke the match patterns are supported in the 3rd argument but not for the key (2nd argument), which is can not be a pattern.

**Comment by Trevoke** [comment]
@fishcakez Okay, so what does this mean?

> [Registry] Ensure `Registry.match/4` works with `:_` as key

https://github.com/elixir-lang/elixir/blob/v1.5/CHANGELOG.md

**Comment by yordis** [comment]
@fishcakez yeah, in the CHANGELOG said matching vs the `key`

**Comment by fishcakez** [comment]
That entry is amount fixing the Registry so that `:_` as the actual key works, not `:_` as a pattern for the key.

**Comment by yordis** [comment]
@fishcakez definitely I didn't see that coming 😆

**Comment by Trevoke** [comment]
Yeeeeaaaaaaaaaaaaaaaaaah me neither.

Turns out communication is difficult.

I guess we're OK with that behavior being dropped from 1.4? (This _used_ to work).

**Comment by fishcakez** [comment]
> I guess we're OK with that behavior being dropped from 1.4? (This used to work).

This is a bug fix, and it did not always "work" in 1.4, for example unique registry with > 1 partition. Much more complex patterns might have been possible and supporting this would have been very complex. Also it would make some keys not work with match in ambiguous fashion (any key that could be a pattern would be a pattern and not the key). Therefore we definitely don't want to support patterns in keys so we are very okay with it ;).

**Comment by Trevoke** [comment]
Always fun to learn that you were relying on behavior that got dropped.. Thanks for the explanation, I guess I'm implementing a duplicate Registry for this, for now anyway.

**Comment by fishcakez** [comment]
> behavior that got dropped

To be clear the behavior did not get dropped, it was never intended to work and it was not documented to work. Rather the documentation (or at least spec) states that the argument was an exact key, and not a pattern. It just happened you were using the edge case bug.

**Comment by josevalim** [comment]
To further clarify, the bug that we fixed is that you could never lookup a
key named :_ in match as it would always match on all keys.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Trevoke** [comment]
Got it; thanks to both of you for the explanations. Amazing the trouble one can get into when one has no idea what they're doing.
