### ISSUE TITLE
Typespec for ignored parameters

### ISSUE THREAD

**Issue by yordis** [elixir-lang/elixir#6604]
When I have some functions that do not care about specific parameter I tried to us `_` in the `typespec` but it failed.

### Current Behavior
```
# the arguments are relative to Absinthe resolver
@spec current_user(user, _, _) :: :ok` <-- it will fail
def current_user(user, _args, _context), do: :ok
```

### Expected Behavior
The typespec should pass, marking that parameter as ignored parameter.

I tried to get help on this one but no success. I am expecting to actually allow to do `_` so I don't have to find out whatever type should be over there.

**Comment by NobbZ** [comment]
Its `any/0` or `term/0` you want to use here.

**Comment by yordis** [comment]
@NobbZ wouldn't be a good idea to actually add `_` as typespec? Tools could benefits from that no?!

**Comment by NobbZ** [comment]
I do not think so.

In general I do read `_` as "is not used at all", so why have it as an argument then? Why not remove it and just write a `somethinkg/1` instead?

**Comment by yordis** [comment]
> just write a somethinkg/1 instead?

Wrong example, the point is actually having ignored params 😄 

> In general I do read _ as "is not used at all"

In ErLang we normally use `_` or any name starting with `_` as something that will "ignored" or actually meant to be ignored.

**Comment by NobbZ** [comment]
Yeah, I know about that convention, and I still ask, why require to pass it in when its actually not needed?

I do see that ignoring a value in a match is usefull, perhaps it will be used in another clause. But already specifying in the type, that an argument will never be used, that feels to be not right...

**Comment by yordis** [comment]
@NobbZ I will update the example

**Comment by devonestes** [comment]
The only example I can think of is if you're implementing a Behaviour but not using all of the available arguments passed to the callback that you need. However, in that case, I would still think that documenting the expected inputs would be helpful for documentation purposes. If you wanted to take the shortcut route to make Dialyzer happy you could use `any/0` or `term/0`, but that seems like you would be putting the task of documentation of how that function is used off to a later point.

**Comment by yordis** [comment]
> The only example I can think of is if you're implementing a Behaviour but not using all of the available arguments passed to the callback that you need.

Yes, it's the case.

The argument is that if somebody later one start using any of those ignored parameters they should maintain the proper typespec of course.

> Dialyzer happy you could use any/0 or term/0

What about introducing `_/0` ?  Dialyzer question because I don't know that much of the core, what would be code different for Dialyzer anyway?! Is `any` and/or `term` important in the Dialyzer task?

**Comment by NobbZ** [comment]
> @NobbZ I will update the example

Your updated example fails for two reasons:

* `_` in a typespec is not allowed, use `any` or `term` here (as said already)
* returning `"whatever"` does not obey the contract of returning `:ok`

And still, your example only shows, that the function were much cleaner when those superflous arguments got removed.

**Comment by NobbZ** [comment]
I've read your comment about implementing a callback only after writing my last answer.

And yes, even if you are right, that there we can't remove an argument from a function, I generally tend to either not spec them at all or use the spec from the behaviour as close as possible. This way I do not have to look it up when I feel to use that formerly unused arguement. Also I can avoid early that it gets called with wrong "stuff" in the ignored places.

**Comment by yordis** [comment]
> Also I can avoid early that it gets called with wrong "stuff" in the ignored places.

You don't care anyway, so why would that matter at all?

> use the spec from the behaviour as close as possible.

Right now because those parameters come from some library I don't know them and wasting time looking for something that you don't even care is not something that many developers will love to do, no?!

@jeremyjh, you are the mage on this. Will `_/0` helps at all Dialyzer or should be completely fine to use `any` because it does not care about it, which is the same behavior?

**Comment by josevalim** [comment]
I agree with @NobbZ. Not used is different from accepting anything. You can still say you expect an integer but not use it.

Also note this is a feature request. Feel free to start this discussion in the mailing list but it is unlikely we would add such convenience.

**Comment by yordis** [comment]
Sorry what is `mailing list` thing I keep reading 😄 ?
