### ISSUE TITLE
Mix cannot find git installation

### ISSUE THREAD

**Issue by heyitsjames** [elixir-lang/elixir#6606]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.2
```
* Operating system: 

MacOS 10.11

### Current behavior

`> mix deps.get`

```** (Mix) Error fetching/updating Git repository: the "git" executable is not available in your PATH. Please install Git on this machine or pass --no-deps-check if you want to run a previously built application on a system without Git.```

`> git --version`
`git version 2.14.2`

### Expected behavior

```mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
  absinthe 1.3.2
  absinthe_plug 1.3.1
  appsignal 1.2.2
  bamboo 1.0.0-rc.1
  base64url 0.0.1
  basic_auth 2.1.4
  bugsnag 1.3.2
  bunt 0.2.0
  certifi 1.2.1
  combine 0.9.6
  connection 1.0.4
  ...
```

If I remove all instances in my `mix.exs` file of getting a dependency from a git repo a la `{:lager, git: "git://github.com/basho/lager.git", tag: "2.0.3"},`, then it works

**Comment by heyitsjames** [comment]
Upgrading to `1.5.1` doesn't solve this issue either, for what it's worth

**Comment by heyitsjames** [comment]
Uninstalling `zsh` did the trick. Now to figure out why `zsh` couldn't find `git`.... :-/

**Comment by OvermindDL1** [comment]
> Uninstalling zsh did the trick. Now to figure out why zsh couldn't find git.... :-/

For note, I run zsh exclusively and have never seen such an issue...

**Comment by NobbZ** [comment]
`zsh` seemed to be able to find it… At least you showed the output of `git --version`… After reinstalling it, does the problem persist?

**Comment by heyitsjames** [comment]
Reinstalling zsh now works. I wonder if it was something I updated from brew that borked it. Like you said, I've run zsh for over a year with Elixir and Mix with no problems. Oh well, computers man, they'll get ya!
