### ISSUE TITLE
Add compiler check that __before_compile__ is defined as macros

### ISSUE THREAD

**Issue by gasparch** [elixir-lang/elixir#6617]
### Environment
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.5.1

### Current behavior

While using `@before_compile SampleModule` compiler will complain if `__before_compile__/1` is undefined. 

Compiler stops complaining when this code added to SampleModule
```
def __before_compile__(_) do
   :return_not_AST
end
```

But it does not invoke this function at all. This leads to situation when code is not executed and compiler gives no helpful hints what is wrong, leading to developer frustration :)

### Expected behavior

Compiler should emit error message that `__before_compile__` must be defined as macros, not as function.

**Comment by josevalim** [comment]
It definitely invokes the function. :)

```elixir
defmodule Foo do
  def __before_compile__(args) do
    IO.inspect args
  end
end

defmodule Bar do
  @before_compile Foo
end
```

Sometimes you want the before compile callback to do some checks and not actually generate code. In such cases, defining it as a function make this intent explicit.

**Comment by gasparch** [comment]
Ahh, then function result does not get injected into module. May be in that case just check if someone returned valid AST and warn that may be they want to use macro and not the function?

**Comment by josevalim** [comment]
I understand the case you ran into but restricting it would reject valid use cases today. Using `:ok` is not a bad idea but it would require us to special case based on the function we are invoking, which is unprecedent. For now it is probably better to wait if others are also running into the same issue.

**Comment by gasparch** [comment]
May be it is enough to add in documentation somewhere in https://elixir-lang.org/getting-started/meta/domain-specific-languages.html and https://elixir-lang.org/getting-started/module-attributes.html

In both cases it says something along the lines 'inject code before compilation' and does not mention possibility of not injecting code. Simple test saying that if __before_compile__ can be function and can be useful for checking without injecting code will immediately raise suspicions :) 

Just in here https://hexdocs.pm/elixir/Module.html is says that `If it’s a macro, its returned value will be injected at the end of the module definition before the compilation starts`.

So definitely this functionality is documented, but final behaviour is totally not obvious :)
