### ISSUE TITLE
`mix xref callers` and Phoenix templates

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#6629]
Original bug report: https://github.com/phoenixframework/phoenix/issues/2543

### Environment

* Elixir & Erlang versions (elixir --version): 1.5.2/OTP 20
* Operating system: macOS Sierra

### Current behavior

Let's say I have following files:

```elixir
# post_view.ex
defmodule ExampleWeb.PostView do
  use ExampleWeb, :view
end
```

```eex
# lib/example_web/templates/post/index.html.eex
line 1
line 2
<%= String.upcase("foo") %>
```

```
$ mix xref callers String.upcase
lib/example_web/views/post_view.ex:3: String.upcase/1
```

Note xref correctly got the line number but used views' filename instead of template's.

### Expected behavior

```
$ mix xref callers String.upcase
lib/example_web/templates/post/index.html.eex:3: String.upcase/1
```

**Comment by wojtekmach** [comment]
FWIW I was able to get a failing test on master:

```elixir
# lib/mix/test/mix/tasks/xref_test.exs

  test "callers: handles external files" do
    contents_a = """
    defmodule A do
      require EEx
      EEx.function_from_file :def, :render, "lib/a.eex", []
    end
    """
    contents_a_eex = """
    <%= String.upcase "foo" %>
    """

    callee = "String.upcase"
    in_fixture "no_mixfile", fn ->
      File.write!("lib/a.ex", contents_a)
      File.write!("lib/a.eex", contents_a_eex)

      assert capture_io(fn ->
        Mix.Task.run("xref", ["callers", callee])
      end) == "lib/a.eex:1: String.upcase/1\n"
    end
  end
```

it's not quite the same as in phoenix templates (which don't use `EEx.function_from_file`) but seems related. Hope it helps!

**Comment by josevalim** [comment]
Thanks @wojtekmach!

The fix is probably that, if we find a warning, we should traverse the abstract code and retrieve the proper file, similar to how we were used to do here: https://github.com/elixir-lang/elixir/blob/v1.5.2/lib/iex/lib/iex/introspection.ex#L138

We can likely solve this by traversing the module definition too: https://github.com/elixir-lang/elixir/blob/v1.5.2/lib/iex/lib/iex/pry.ex#L309. It will be inside of the meta: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_erl.erl#L235

The second approach is much faster but it works only on OTP 20. That's probably an OK behaviour for this, especially because by Elixir v1.6 most will be using OTP 20 anyway.

**Comment by ggcampinho** [comment]
I was trying out this issue transversing the tree as you suggested, but I had the impression that if we change the source struct to store the external file it would be easier and faster.

Current structure:
```
{
    :source,
    "lib/a.ex",
    89,
    [Module, Keyword, Kernel.LexicalTracker, Kernel, Enum, EEx],
    [String.Chars, String],
    [
      {EEx, %{{:compile_file, 2} => [3], {:function_from_file, 4} => [3]}},
      {Enum, %{{:map, 2} => [3]}},
      {
        Kernel,
        %{
          {:<>, 2} => [3],
          {:@, 1} => [3],
          {:def, 2} => [3],
          {:defmodule, 2} => [1],
          {:defp, 2} => [3]
        }
      },
      {Kernel.LexicalTracker, %{{:read_cache, 2} => [1]}},
      {Keyword, %{{:merge, 2} => [3]}},
      {Module, %{{:put_attribute, 5} => [3]}}
    ],
    [
      {String, %{{:upcase, 1} => [1]}},
      {String.Chars, %{{:to_string, 1} => [3]}}
    ],
    ["lib/a.eex"],
    []
  }
```

Proposed structure:
```
{
    :source,
    "lib/a.ex",
    89,
    [Module, Keyword, Kernel.LexicalTracker, Kernel, Enum, EEx],
    [String.Chars, String],
    [
      {EEx, %{{:compile_file, 2} => [3], {:function_from_file, 4} => [3]}},
      {Enum, %{{:map, 2} => [3]}},
      {
        Kernel,
        %{
          {:<>, 2} => [3],
          {:@, 1} => [3],
          {:def, 2} => [3],
          {:defmodule, 2} => [1],
          {:defp, 2} => [3]
        }
      },
      {Kernel.LexicalTracker, %{{:read_cache, 2} => [1]}},
      {Keyword, %{{:merge, 2} => [3]}},
      {Module, %{{:put_attribute, 5} => [3]}}
    ],
    [
      {String, %{{:upcase, 1} => [{1, external_source: "lib/a.eex"}]}},
      {String.Chars, %{{:to_string, 1} => [{3, external_source: "lib/a.eex"}]}}
    ],
    ["lib/a.eex"],
    []
  }
```

**Comment by josevalim** [comment]
@ggcampinho the problem then is that generating this structure comes at the expense of compilation time. I would rather keep compile time faster and compute those only when we need to show the warning.

**Comment by josevalim** [comment]
@ggcampinho that's a good point but I would prefer to still handle it exclusively in xref if possible.

**Comment by josevalim** [comment]
Hi @ggcampinho, after looking at the xref implementation and your comments, I cannot find a way solution that avoids traverse the definitions all the time and that will likely be more expensive on the long term. So I believe you were right, storing it during compilation time is probably the best way to go. We can store it as `{"lib/a.eex", 1}`.

Let's keep the current PR open for further discussion but could you also please send a PR that changes the manifest directly? Thank you! :heart:

**Comment by josevalim** [comment]
@ggcampinho also noticed I pushed 5b9a5ff6372d5333fdefd1838cb54bf7b9e202a0 which cleans up the assert_callers a bit to allow us to pass multiple files. :)

**Comment by ggcampinho** [comment]
Thanks, @josevalim! I'll start working on the change for the manifests!

One thing that I realized after the PR is that if we want to output only once for the external files we will need to keep a structure with all the callers in all the files to remove duplicates instead. In a big project, this approach will probably cause problems.

I don't know if it's better to just ignore this, change a bit the output to have duplicates or add also the external file (`lib/a.eex`) to the sources in the manifest.

**Comment by josevalim** [comment]
> One thing that I realized after the PR is that if we want to output only once for the external files we will need to keep a structure with all the callers in all the files to remove duplicates instead. In a big project, this approach will probably cause problems.

This particular grouping can happen in mix xref at least, no? Although it is probably unlikely the same template is being used in many many places, so the duplication shouldn't hurt much as well.
