### ISSUE TITLE
`with` sentences does not pattern match against structs

### ISSUE THREAD

**Issue by ndac-todoroki** [elixir-lang/elixir#6631]
### Environment

* Elixir & Erlang versions (elixir --version): 
  - Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
  - Elixir 1.5.1

* Operating system: 
  - Ubuntu 17.04

### Current behavior
```elixir
iex(1)> defmodule Test do                 
...(1)>   def a(args) do                  
...(1)>     with %MapSet{} = m <- args, do: m
...(1)>   end                                
...(1)> end
{:module, Test,
 <<70, 79, 82, 49, 0, 0, 3, 216, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 104,
   0, 0, 0, 10, 11, 69, 108, 105, 120, 105, 114, 46, 84, 101, 115, 116, 8, 95,
   95, 105, 110, 102, 111, 95, 95, 9, 102, ...>>, {:a, 1}}
iex(2)> Test.a(MapSet.new)
#MapSet<[]>
iex(3)> Test.a(%{})       
%{}
iex(4)> Test.a(100)
100
```

### Expected behavior

```elixir
iex(2)> Test.a(MapSet.new)
#MapSet<[]>
iex(3)> Test.a(%{})       
**WithClauseError
iex(4)> Test.a(100)
**WithClauseError
```

---

Since it was very hard for me to find documents about `with` comprehensions (`with` is all over there in Google), I believe that struct pattern matching should work here too.
I thought that using both `=` and `->` makes it wrong, but this didn't work either:

```elixir
iex(1)> defmodule Test do                      
...(1)>   def a(args) do                       
...(1)>     with %MapSet{} <- args, do: args   
...(1)>   end
...(1)> end
{:module, Test,
 <<70, 79, 82, 49, 0, 0, 3, 208, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 104,
   0, 0, 0, 10, 11, 69, 108, 105, 120, 105, 114, 46, 84, 101, 115, 116, 8, 95,
   95, 105, 110, 102, 111, 95, 95, 9, 102, ...>>, {:a, 1}}
iex(2)> Test.a(MapSet.new)
#MapSet<[]>
iex(3)> Test.a(12)        
12
```

**Comment by josevalim** [comment]
You can find more documentation for with by typing `h with` in IEx or on our docs: https://hexdocs.pm/elixir/search.html?q=with

It is important to note that `with` **will return the value that does not match**. That's why you think it is matching but it actually isn't. Try this:

    with %MapSet{} <- args, do: {:ok, args}

or this:

    with %MapSet{} <- args do
      {:ok, args}
    else
      x -> {:error, x}
    end

and it will probably become clearer how it is behaving.

**Comment by ndac-todoroki** [comment]
OK, the problem was indeed in my code; the `with` sentence (btw, what should I call `with`... a macro?) was returning {:ok, nil}, which didn't stop start_link/3 of GenServer in my test code. Thank you @josevalim !
I also was misreading the docs (and thanks noting about the `h`... I was reading the `@doc` directly :( ),

> If there is no matching `else` condition

as something like _no matching `with`condition_ ... my bad. sorry!
