### ISSUE TITLE
Formatter doesn't keep newline in non-"<-" clauses in "for" and friends

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#6651]
Formatting this code:

```elixir
for a <- a(),
    b = b() do
  :ok
end
```

spits out

```elixir
for a <- a(), b = b() do
  :ok
end
```

The same happens for 

```elixir
for a <- a(),
    b do
  :ok
end
```

which is formatted as

```elixir
for a <- a(), b do
  :ok
end
```

I think in this case we want to have the newline between each clause.

**Comment by josevalim** [comment]
Yup, working as intended. We only force breaks if you have two or more generators.
