### ISSUE TITLE
Code formatter re arranges comments in structs which causes loss of context

### ISSUE THREAD

**Issue by minhajuddin** [elixir-lang/elixir#6725]
Code formatter re arranges comments in structs which causes loss of context

### Environment

* Elixir & Erlang versions (elixir --version): Erlang 20, Elixir 1.6.0-dev bb26227f7
* Operating system: Ubuntu 16.04

### Current behavior

Before formatting my code looks like below:

```
  defmodule Request do
    defstruct uri: %URI{},
      method: :get,
      http_version: :http1_1,
      headers: [], # e.g. [{"User-Agent", "Danny"}, {"Accept", "text/html"}]
      body: [] # iodata/iolist
  end
```
After formatting my code looks like below:

```
  defmodule Request do
    # e.g. [{"User-Agent", "Danny"}, {"Accept", "text/html"}]
    # iodata/iolist
    defstruct uri: %URI{}, method: :get, http_version: :http1_1, headers: [], body: []
  end
```

### Expected behavior
As you can see the comments are moved from their place to the top of the struct definition. This causes in the loss of context

**Comment by ericmj** [comment]
I think this is one of those cases where you have to fix the comments manually after running the formatter.

**Comment by stavro** [comment]
This is documented as intentional: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/code.ex#L284-L325

**Comment by josevalim** [comment]
We are now keeping the struct over multilple lines but the comments will be moved out, yes. :)

**Comment by josevalim** [comment]
Btw, this was added to master at some point. The code above will be formatted to:

```elixir
defmodule Request do
  defstruct uri: %URI{},
            method: :get,
            http_version: :http1_1,
            # e.g. [{"User-Agent", "Danny"}, {"Accept", "text/html"}]
            headers: [],
            # iodata/iolist
            body: []
end
```
