### ISSUE TITLE
Support uniq: true in for comprehensions

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6792]
This avoids doing a later pass on the data.

**Comment by OvermindDL1** [comment]
What about having `uniq:` take a 1-arity function to act as a `uniq_by` (as in `Enum`), or perhaps a `uniq_by:` that takes such a 1-arity function?  What would be preferred?

**Comment by bschaeffer** [comment]
Would it be better to have `:uniq` accept either `true` or `fun/1`?

**Comment by OvermindDL1** [comment]
> Would it be better to have :uniq accept either true or fun/1?

That is what I was thinking, it'd be a lot more useful then.  Although an even more powerful method would be to somehow make a unique'ing clause so any arbitrary step could be uniq'd (like a `uniq(blah)` filter), but of what form would such a clause take?  Maybe something like:

```elixir
for\
  x <- [1, 1, 2, 2, 3, 3],
  uniq(x),
  do: x
```

This makes it look like a function call like any other normal filter, however it is not a function call so it breaks this expectation as a user may be wondering where it comes from, however it would be the most generically powerful and it is shorter too, I'm just uncertain about having it look like a normal function even though it does make the most sense there I think...  Hmm...

**Comment by josevalim** [comment]
@OvermindDL1 the problem is the ambiguity with a potential local named `uniq/1` and forcing the bindings to be all defined upfront. Having `uniq_by` with an anonymous function has the opposite issues in the sense we can only call `uniq_by` if the value you are computing the unique part is in the result, which may not be the case.

That's why `uniq: true` is appealing because none of those issues exist and we can postpone this decision for latter. And even if we add uniq_by, it can be slightly more performant than doing `uniq_by: & &1`.

There is a nice paper about similar extensions to haskell here: https://www.microsoft.com/en-us/research/wp-content/uploads/2007/09/list-comp.pdf

**Comment by OvermindDL1** [comment]
> @OvermindDL1 the problem is the ambiguity with a potential local named uniq/1 and forcing the bindings to be all defined upfront.

That is precisely what I was referencing when I'm talking about it breaking expectations, the user would not be able to use a `uniq/1` in their scope even if they wanted to.  ^.^;

> And even if we add uniq_by, it can be slightly more performant than doing uniq_by: & &1.

Indeed, not too hard to do at all to just optimize it out entirely when it is not specified.

However, by having it be an option instead of a clause means that you can cannot do arbitrary uniqueness at some step like you could with clause, like how would you be able to do this with the given proposal (ignoring `uniq_by` for now as it is similar):

```elixir
for\
  x <- [1, 2, 3],
  y <- [4, 5, 6],
  uniq(x+y),
  z <- [7, 8, 9],
  do: x + y + z
```

**Comment by OvermindDL1** [comment]
Hmm, could make it something that does not make sense otherwise at the location, perhaps 'internal' filters could just be prefixed with a `_` to make the above example's `uniq` line become `_uniq(x+y),` as in:

```elixir
for\
  x <- [1, 2, 3],
  y <- [4, 5, 6],
  _uniq(x+y),
  z <- [7, 8, 9],
  do: x + y + z
```

It does make it obvious then that it is not a natural function call (though still possible, just not a usual form).  Could always introduce a new syntax as well that is not possible to do otherwise in elixir currently, no backwards compat issues even possible then, or use one of the other unused operators for built-in filters like:

```elixir
for\
  x <- [1, 2, 3],
  y <- [4, 5, 6],
  uniq <-> x+y, # Named built-in filter
  z <- [7, 8, 9],
  do: x + y + z
```

Not really happy with any honestly though, but I far *far* more often would `uniq` on some intermediate step then the output value personally (and usually on something within the output value rather than the value itself as well)..

**Comment by josevalim** [comment]
> However, by having it be an option instead of a clause means that you can cannot do arbitrary uniqueness at some step like you could with claus

Yup, that's the downside I meant about a function.

@OvermindDL1 for now we are going with uniq: true as a boolean as it doesn't have any of the issues above. The jury is still out there regarding uniq_by and order_by. You can start a discussion in the mailing list if you want to.

**Comment by ggcampinho** [comment]
I was giving a try to this issue, and if I can understand correctly the for comprehension is a sequence of reducers, and there are two solutions that can be done:

1. Reduce like today, and then apply `Enum.uniq`;
2. When the reduce is applying the final expression, check if the element is already in the list before inserting it.

I think that the first one is simpler and faster, is this the way to go?

**Comment by josevalim** [comment]
@ggcampinho the faster implementation is to change how the reducing function in the comprehension works. For example, if you have:

    for x <- collection, do: expr(x)

It becomes something close to:

    Enum.reduce(collection, [], fn x, acc ->
      [expr(x) | acc]
    end) |> :lists.reverse()

Instead, we want it to become this:
 
    Enum.reduce(collection, {[], %{}}, fn x, {acc, uniq} ->
      val = expr(x)
      case uniq do
        %{^val => true} -> {acc, uniq}
        %{} -> {[val | acc], Map.put(uniq, val, true)}
      end
    end) |> elem(0) |> :lists.reverse()

Notice that the initial value of the accumulator `[]`, the concatenation operation `[expr(x) | acc]` and the final operation `:lists.reverse` will all change based on the generator type and on `into`. But this should not affect the implementation of `uniq` because we can all wrap around that.

In pseudo code, we compile to this:

    Enum.reduce(collection, INITIAL_ACC, fn x, ACC ->
      CONCAT(expr(x), ACC)
    end) |> LAST()

and we want to compile to this:

    Enum.reduce(collection, {INITIAL_ACC, %{}}, fn x, {ACC, uniq} ->
      val = expr(x)
      case uniq do
        %{^val => true} -> {ACC, uniq}
        %{} -> {CONCAT(val, ACC), Map.put(uniq, val, true)}
      end
    end) |> elem(0) |> LAST()

**Comment by ggcampinho** [comment]
Ah okay, I understand. It makes sense, I was afraid that passing around a map would be bad and then I thought about checking the list. I'll try to do this, thanks!

**Comment by ggcampinho** [comment]
@josevalim I was checking the issue again and I noticed that I didn't see that you were assigned for this, sorry.

Anyways, I opened the PR with my progress so far, it's not complete and there is one open question for maps: should it be unique by pair or by key? The simple solution is just to follow what was implemented for the other and do it by pair, but if we do by key it's possible to introduce some optimizations.

Feel free to close my PR if the solution is too far from this or if you want to implement it, sorry again for the confusion!

**Comment by josevalim** [comment]
> I noticed that I didn't see that you were assigned for this, sorry.

No worries, that has been fixed! ;)

>  The simple solution is just to follow what was implemented for the other and do it by pair, but if we do by key it's possible to introduce some optimizations.

By pair, we should treat it as any other enumerable. :)
