### ISSUE TITLE
Formatter should put parens around some operators

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#6797]
This code

```elixir
& -&1
```

is formatted as

```elixir
&-&1
```

**Comment by josevalim** [comment]
In master.

**Comment by OvermindDL1** [comment]
I'm curious (mostly trying to understand the formatting rules), what is wrong with that?  Isn't it an unary negation thus `&-&1` is what I'd do?  Separating the `&` from the function call of `-/1` seems to separate the fact it is function passing away from the function it is passing?
