### ISSUE TITLE
Formatter: don't wrap string substitutions

### ISSUE THREAD

**Issue by mhinz** [elixir-lang/elixir#6809]
I'm not really sure this even counts as an issue, but when I format `Kernel`, I notice this:

```elixir
raise ArgumentError, "long long long long long long long long long long long long long long, got: #{inspect other}"
```

..gets formatted like this..

```elixir
raise ArgumentError,
      "long long long long long long long long long long long long long long, got: #{
        inspect(other)
      }"
```

Take one `long` away, and you'll get..

```elixir
raise ArgumentError,
      "long long long long long long long long long long long long long, got: #{inspect(other)}"
```

Obviously the second line is still too long, but automatically wrapping the string substitution in the former case looks wrong.

Is this intended, a bug, or just an unfortunate corner case? :)

**Comment by josevalim** [comment]
It is by design. We need to split where it can and the only place we can split such large strings it is there. You need to refactor your code. :)
