### ISSUE TITLE
Code formatter: syntax error after formating heredoc with line break before terminator

### ISSUE THREAD

**Issue by amatalai** [elixir-lang/elixir#6861]
### Environment

* Elixir & Erlang versions: Elixir 1.6.0-dev (7b8d5ec28) (compiled with OTP 20)
* Operating system: macOS 10.13 (17A365) - High Sierra

### Current behavior

Formatter output for this file
```elixir
defmodule Example do
  @moduledoc false
  def text do
    """
    heredoc \
    """
  end
end
```
looks like this
```elixir
defmodule Example do
  @moduledoc false
  def text do
    """
    heredoc """
  end
end
```
which ends as
`** (SyntaxError) lib/example.ex:5: invalid location for heredoc terminator, please escape token or move it to its own line: """`

### Expected behavior
**VERSION A**

Don't remove line break from last line of heredoc

**VERSION B**

Don't allow to use line break in last line of heredoc like some other languages.
In this case I would like to make PR, something like this:
https://github.com/amatalai/elixir/blob/7817b634a9877368ac314b55aa4a8ab53e881cc4/lib/elixir/src/elixir_tokenizer.erl#L725-L727, but maybe with better message :)

**Comment by josevalim** [comment]
I will fix the formatter accordingly. Thank you!

**Comment by amatalai** [comment]
💚
