### ISSUE TITLE
Documentation Inspect.Algebra and actual code out of sync

### ISSUE THREAD

**Issue by ThomasArts** [elixir-lang/elixir#6881]
Running on OTP 20 with Elixir 1.6.0-dev

Reading the documentation in Inspect.Algebra and compared it with actual behaviour. Missing newline in result.

```elixir
Erlang/OTP 20 [erts-9.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.6.0-dev) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> doc = Inspect.Algebra.nest(Inspect.Algebra.glue("hello", "world"), 5)
{
  :doc_nest,
  {:doc_cons, "hello", {:doc_cons, {:doc_break, " ", :strict}, "world"}},
  5,
  :always
}
iex(2)> Inspect.Algebra.format(doc, 5)
["hello", " ", "world"]
```

Expected behaviour according to documentation:
```elixir
["hello", "\n     ", "world"]
```

I believe the documentation is right in this case.

**Comment by josevalim** [comment]
Hi @ThomasArts!

Were you trying this example?

```elixir
      iex> doc = Inspect.Algebra.nest(Inspect.Algebra.glue("hello", "world"), 5)
      iex> doc = Inspect.Algebra.group(doc)
      iex> Inspect.Algebra.format(doc, 5)
      ["hello", "\n     ", "world"]
```

In this case, is it possible that you forgot the `group` call?

**Comment by ThomasArts** [comment]
I used the documentation from 1.5.2:
https://hexdocs.pm/elixir/Inspect.Algebra.html#nest/2

There group is missing.

**Comment by josevalim** [comment]
I see. `format` was used to auto group but we no longer do it. I will investigate what are the consequences of this change. But if you explicitly group, it should work on past and future versions. Thanks for the report @ThomasArts!
