### ISSUE TITLE
Use inspect in assertion diff for structs

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#6930]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.6.0-dev
* Operating system: macOS Sierra

### Current behavior

On our project we've been recently dealing a lot with time and on large lists the diff is hard to read. We ended up explicitly using inspect for assertions (as shown in expected behavior section). Looks like in https://github.com/elixir-lang/elixir/pull/4430#issuecomment-202370016 `Inspect` was considered to diff in structs. Perhaps it could be reconsidered?

```
t1 = ~N[2017-10-15 09:00:00]
t2 = ~N[2017-10-15 12:00:00]
t3 = ~N[2017-10-16 22:00:00]

assert [t1, t2, t3, t1] == [t1, t1, t1, t1, t1]
```

<img width="971" alt="zrzut ekranu 2017-10-15 o 10 40 40" src="https://user-images.githubusercontent.com/76071/31583162-86002c72-b195-11e7-8cf3-9521a41ab2e0.png">

### Expected behavior

<img width="972" alt="zrzut ekranu 2017-10-15 o 10 46 50" src="https://user-images.githubusercontent.com/76071/31583199-a2f3c9aa-b196-11e7-8ae0-faa54e2006c2.png">

**Comment by whatyouhide** [comment]
Could it be a problem that sometimes things are omitted in the inspect representation? For example, a `StreamData.LazyTree` struct from [stream_data](https://github.com/whatyouhide/stream_data) omits the children of the tree because they are lazy, and then two different structs would not have anything to show in the diff when inspected. I just realized that streams are already an instance where this would cause problems, right?

**Comment by josevalim** [comment]
If they are not the same, maybe we should do an inspect diff and if that is the same, then we do a struct diff?

**Comment by yordis** [comment]
@josevalim shouldn't `]` and `~N[` highlighted in the Expected behavior image? or is that a mistake?

**Comment by whatyouhide** [comment]
@josevalim I still see it as problematic. These two diffs would be different and we'd show basically a meaningless diff:

```elixir
iex> Stream.filter([1, 2, 3], &(&1))
#Stream<[enum: [1, 2, 3], funs: [#Function<39.47899354/1 in Stream.filter/2>]]>
iex> Stream.take([1, 2, 3], 2)
#Stream<[enum: [1, 2, 3], funs: [#Function<55.47899354/1 in Stream.take/2>]]>
```

**Comment by kelvinst** [comment]
@whatyouhide IMO the highlight colors do this job when the difference is so small.

**Comment by kelvinst** [comment]
I can do it if no one else is interested. ;)

**Comment by josevalim** [comment]
@kelvinst I am still not personally sure what is the best way to go so I will go ahead and mark this as a discussion.

**Comment by kelvinst** [comment]
@josevalim cool!!

**Comment by whatyouhide** [comment]
I still think this needs to be thought through but in the meantime I found something else that suggests what we have today is suboptimal:

```elixir
     left:  %MapSet{version: 2, map: %{}}
     right: %MapSet{version: 2, map: %{"elixir-format" => []}}
```

**Comment by michalmuskala** [comment]
What if we first tried to compare inspect results, and if they don't differ do the structural comparison like today?

There's also the possibility of diffing the algebra documents (if the particular implementation leverages them), but that might be much more complex.
