### ISSUE TITLE
In some cases formatter replaces parens with space after capture

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-lang/elixir#6936]
By running code formater on one of our projects, I've noticed this change:
```diff
- assert [^request5_id] = Enum.map(page, &(&1.id))
+ assert [^request5_id] = Enum.map(page, & &1.id)
```

By looking at the most examples over the internet:
1. ["Official"](https://github.com/lexmag/elixir-style-guide) code style tells nothing about this case;
2. rrrene code style [prefers to keep the parens](https://github.com/rrrene/elixir-style-guide#function-calling-parens);
3. Google TOP examples are all [with parens](https://dockyard.com/blog/2016/08/05/understand-capture-operator-in-elixir).

For me, simple rule "newer leave a space after the capture" would be easier to remember. This is how I would like to change it:
```diff
-      assert_format "&(&1)", "& &1"
-      assert_format "&(&1.foo)", "& &1.foo"
+      assert_format "&(&1)", "&(&1)"
+      assert_format "&(&1.foo)", "&(&1.foo)"

-      assert_same "& &&/2"
+      assert_format "& &&/2", "&(&&/2)"
```

Feel free to close it, I don't want to start a long discussion about the code style, because avoiding them is the main reason for introducing the formater :).

**Comment by NobbZ** [comment]
I prefer to have parens after capture as well. Due to the parens highlighting in my editor it would be much easier to visually scan them.

Also, since I'm polyglotal, I do have often a hard time to recognize the capture operator as such if it has spaces on both sides... My brain tries to parse it as "BITWISE AND" then, which is fundamentally wrong. While having something without a space right of it, helps me mentally parsing as "the reference of something".

**Comment by AndrewDryga** [comment]
Few other small things I want to deliver as feedback about formatting:
- it's better to keep comma on the end of multi-line list, because by adding/reordering elements git diff would be smaller
- this one feel weird for a function definition:
```diff
-  def call(%Plug.Conn{method: method, status: status} = conn, [subscriber: subscriber])
+  def call(%Plug.Conn{method: method, status: status} = conn, subscriber: subscriber)
```
- one-line  `if (...), do: `blocks requires you to read code horizontally, when we have opposite goal by having low (98 chars) max length.
- this not where the comment should be, it can be related to the string below it:
```
+    # TODO: Try QLC to filter by methods
    apis =
      table_name
-      # TODO: Try QLC to filter by methods
      |> :ets.match_object({:_, match_spec, :_, :_})
```

**Comment by josevalim** [comment]
> "Official" code style tells nothing about this case;

The official code style *is the formatter*.

Everyone is going to have preferences on how code is written and the
formatter is what it is.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
It is also worth noting that the formatter cannot make your code always
look beautiful without user intervention. The docs has some examples of
this and I would likely rewrite your “if” to a do/end block.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
