### ISSUE TITLE
Extending the Enumerable protocol

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6950]
The Enumerable protocol today contains 3 functions: `reduce/3`, `member?/2` and `count/1`. As the community grew, they asked for more extension points, such as `fetch/2`, but we didn’t add those functions as we did not see cases for them in the standard library itself.

With the addition of `Date.Range` and the upcoming `Stream.Data`, we have enough cases that require the specialization of the Enumerable protocol in the standard library itself to finally justify adding new functions to the protocol.

They are three: `aggregate/2`, `fetch/2` and `take_random/2`. Those are detailed below.

## aggregate/2

`aggregate/2` is used to take general information from the collection, such as `:count`, `:sum`, `:max` and `:min`:

```elixir
@spec aggregate(Enumerable.t, :sum | :min | :max | :count | atom()) :: {:ok, term()} | {:error, __MODULE__}
```

It should be implemented by data structures that can provide such data without traversing the whole collection. For example, ranges:

```elixir
def aggregate(min..max, :sum) do
  (max - min + 1) * (min + max) / 2
end

def aggregate(min.._, :min) do
  min
end

def aggregate(_..max, :max) do
  max
end

def aggregate(min..max, :count) do
  max - min + 1
end

def aggregate(_range, _) do
  {:error, __MODULE__}
end
```

`count/1` will no longer be used by `Enum`.

The idea of hiding all aggregations behind a single function is that most data types can continue to return `{:error, __MODULE__}` without implementing 4 or 5 different functions.

This new function will benefit `Range` and `Date.Range` in the standard library.

## fetch/2

`fetch/2` will access an element at a given position:

```elixir
@spec fetch(Enumerable.t, integer()) ::
        {:ok, {:ok, term()} | :error}
        | {:error, __MODULE__}
        | {:boundary, non_neg_integer(), __MODULE__}
```

It should be implemented by data structures that can provide such data without traversing the whole collection. The `{:boundary, ...}` can be returned by data structures that cannot efficiently implement `fetch/2` but have a size known upfront. This is used for efficient boundary checks.

This new function will benefit `Range` and `Date.Range` in the standard library.

## take_random/2

`take_random/2` will take N random elements from the collection.

```elixir
@spec take_random(Enumerable.t, pos_integer()) ::
        {:ok, [term()]}
        | {:error, __MODULE__}
        | {:boundary, non_neg_integer(), __MODULE__}
```

It should be implemented by data structures that can provide such data without traversing the whole collection. The `{:boundary, ...}` can be returned by data structures that cannot efficiently implement `take_random/2` but have a size known upfront. This is used for more efficient random algorithms.

This new function will benefit `Range`, `Date.Range` and `Stream.Data` in the standard library.

**Comment by Kabie** [comment]
Shouldn't `aggregate/2` also return `{:ok, term()} | {:error, __MODULE__}`?

**Comment by teamon** [comment]
And shouldn't `fetch` also return `{:ok, term() | :error} | {:error, __MODULE__} | ...` ?

I guess the reason for "count/1 will no longer be used by Enum." is it's not an O(1) operation?

**Comment by josevalim** [comment]
@Kabie thanks, i forgot the return type there, fixed.

@teamon it needs to be `{:ok, {:ok, term()} | :error}` otherwise we can't distinguish between an `:error` and actually fetching `:error`.

**Comment by teamon** [comment]
Hmm I misread that, but it's still confusing:

```
fetch(.., :nope) => :error # fetch not ok
fetch(.., :key) => {:ok, value} # fetch ok, we get value
fetch(.., :key) => {:ok, :error} # the value is :error 
```

Am I missing something?

**Comment by josevalim** [comment]
@teamon there are two `:ok` because one `:ok` is "I can provide this functionality" and the second `:ok` is "I have something at this position". In any case, this probably won't matter in a couple hours as I have adjustments to make to this part of the proposal. :)

**Comment by teamon** [comment]
Ah, ok. Wouldn't it make sense to make fetch part of a separate protocol then?

**Comment by josevalim** [comment]
@teamon no because it always provide that functionality, this is about providing a faster version or not.

**Comment by AndrewDryga** [comment]
@josevalim thats 👍 💯. I'd like to work on this one.

**Comment by josevalim** [comment]
Thanks @AndrewDryga! I would like to work on this one myself because this is not 100% defined and we will probably have to do changes as we move forward.

**Comment by josevalim** [comment]
I have written a new and simpler but more powerful version of this proposal here: #6955.
