### ISSUE TITLE
Formatter: preserve whitespace in comments after the # sign

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/elixir#6969]
Currently the formatter turns this:

```elixir
#foo
```

into this:

```elixir
# foo
```

As evidenced by this iex session:

```
iex(5)> Code.format_string!("#! foo")  
["# ! foo"]
iex(6)> Code.format_string!("#!foo") 
["# !foo"]
```

This improves readability if what's to the right of the `#` is indeed text, but if it is a hint for a program that operates on Elixir source it's pretty bad. Such hints could be hints for the formatter to ignore a certain part of the code, for example:

```elixir
#! formatter-ignore:begin
...
# some code with wacky formatting
...
#! formatter-ignore:end
```

**Comment by yordis** [comment]
I am confused when this is a use case, could you put a real example I don't see why we would do such of thing 🤔

**Comment by tmbb** [comment]
Yes. One use case is the one I've already described. Say you want to mark some code blocks as blocks that should be delimited by the formatter. Using comments is a logical choice, and if the formatter messes with the comments' whitespace it makes it harder than it should be.

Another example, from real working code. I've written a markdown implementation which you can use with ExDoc, named ExDocMakeup: https://github.com/tmbb/ex_doc_makeup

It ships with a number of extensions. One of them allows the user to extract literal blocks of code into the documentation, by marking such blocks of code with specia comments. Currently, the comments are `# !begin: block-name` and `# !end: block-name`, which I'll change into `#! begin: block-name` `#! end: block-name`, so that other source-processing tools can distinguish these comments from normal comments. You can read the docs here: https://github.com/tmbb/ex_doc_makeup#include-a-block-of-code

This is a real-life use for these kinds of annotations (yes, almost no one uses this yet, but this library is 1 week old or something like that). If the formatter messes with comments like this, it makes it hard to use these annotations.

Another example might be hints for code coverage tools (I'm not familiar with any such library for Elixir, but most python tools accept hints given by these kinds of comments).

I hope it's clearer now.

**Comment by whatyouhide** [comment]
I think that we should only turn `#some comment` into `# some comment`, that is, ensure that there's one space but nothing more. @tmbb can you use something else to mark your comments, instead of `#!`?

**Comment by tmbb** [comment]
> can oyu use something else to mark your comments, instead of  `#!`

Yes, of course, that's what I'm doing right now, and it's working fine.
But maybe having some kind of convention for annotations like mine (credo, for example). That would make it easier to interoperate. The goal of such convention would be to distinguish normal comments from "meaningful comments" and the absence of space following `#` could be one such convention.

Maybe this issue is not the right place to discuss this. I'll open a topic in the forum instead.
