### ISSUE TITLE
URI.to_string/1 doesn't encode correct URL according to WHATWG

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#6970]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```
* Operating system: 
```
Darwin niuniobook 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64
```

### Current behavior

```
iex> URI.to_string(%URI{host: "google.com", scheme: "http", query: "q=foo"})
"http://google.com?q=foo"
```

### Expected behaviour

```
iex> URI.to_string(%URI{host: "google.com", scheme: "http", query: "q=foo"})
"http://google.com/?q=foo"
```

Accordingly to [WHATWG spec](https://url.spec.whatwg.org/#special-scheme) all special schemes, i.e. `uri.schema in ~w(ftp file gopher http https ws was)` then `path` part cannot be empty.

**Comment by ericmj** [comment]
The `URI` module follows RFC3986 and according to it the path can be empty: https://tools.ietf.org/html/rfc3986#section-3.3.

**Comment by hauleth** [comment]
As far as I am concerned this document is about parsing URIs, not displaying them. So I would agree that `URI.parse/1` should accept form `http://a?b=foo`, but I think that output form should follow WHATWG (at least when using schemes listed earlier). 

--
Łukasz Jan Niemier

**Comment by ericmj** [comment]
RFC3986 does not really establish how to display URIs so the best thing to do is to just print the values we stored without any transformations. The URI module does not follow the WHATWG spec so if you want those behaviors you need to use another module.

**Comment by josevalim** [comment]
What @ericmj said. In particular, URI.to_string does not attempt to normalize but rather create back the original URI parsed. You can always normalize it yourself though.
