### ISSUE TITLE
Cannot execute mix do run multyple times with different scripts

### ISSUE THREAD

**Issue by vasspilka** [elixir-lang/elixir#6973]
### Environment
```
> elixir --version
Erlang/OTP 20 [erts-9.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.2
```
```
> uname -a
Linux vs 4.13.8-1-ARCH #1 SMP PREEMPT Wed Oct 18 11:49:44 CEST 2017 x86_64 GNU/Linux
```

### Current behavior

I have multyple script files that I want to execute one after the other 
when doing 
```
mix do run ./scriptA.exs, run ./sciptB.exs
```
 it will run only the first script.

When asked about this in slack I found out one can put `Mix.Task.reenable("run")` at the end of the script files to reenable the run command and allow for it to be used again with `mix do`.

### Expected behavior

I would expect doing `mix do run ./scriptA.exs, run ./sciptB.exs` to work out of the box.

**Comment by josevalim** [comment]
That's by design. Mix tasks run only once, then they need to be explicitly reenabled. You can use the -r flag on this case to pass multiple files or use separate mix commands.

**Comment by vasspilka** [comment]
That makes sense, thanks for quick reply
