### ISSUE TITLE
Master Macro in Binaries Compiler Bug

### ISSUE THREAD

**Issue by OvermindDL1** [elixir-lang/elixir#6980]
Creating issue as per @ericmj at:  https://elixirforum.com/t/ecto-failing-to-compile-on-elixir-1-6-0-dev/9662/5
And I quote:

> I can reproduce when using Ecto 2.2.6 on Elixir master, it seems to be an issue when using macros inside binary literals. Please open an issue on Elixir.

Using OTP 20 / erts-9.1, with Elixir 1.6.0-dev (git HEAD), compiling with Ecto 2.2.6 causes:

```elixir
╰─➤  mix compile
==> ecto
Compiling 70 files (.ex)
warning: function slice/1 required by protocol Enumerable is not implemented (in module Enumerable.Ecto.Adapters.SQL.Stream)
  lib/ecto/adapters/sql/stream.ex:12


== Compilation error in file lib/ecto/adapters/postgres/connection.ex ==
** (ArgumentError) argument error
    (stdlib) erl_anno.erl:322: :erl_anno.set(:generated, false, {"lib/ecto/adapters/postgres/datetime.ex", 48})
could not compile dependency :ecto, "mix compile" failed. You can recompile this dependency with "mix deps.compile ecto", update it with "mix deps.update ecto" or clean it with "mix deps.clean ecto"
```

The issue does not happen in Elixir commit f36a0f4 so it happened between then and HEAD (f36a0f4 was a little less than a week ago).

On RedHat7, manually compiled Elixir, Erlang from erlangsolutions package repo.

**Comment by josevalim** [comment]
Can you please tell us what is your HEAD? Because this does not happen on Elixir master (after `make clean compile`) and then `mix compile --force` on the Ecto repo.

**Comment by josevalim** [comment]
Apologies, I was using Ecto master. I can reproduce it on 2.2.6.

**Comment by OvermindDL1** [comment]
Ah sorry, forgot to copy more stuff from that thread.  ^.^;

Yes I clean compiled, yes I fresh git clone'd elixir as well as my project, etc...  Sorry for missing that (end of my work day I blame it on ^.^).
