### ISSUE TITLE
Compiling function with unbound variable in match spec fails with confusing error

### ISSUE THREAD

**Issue by tmbb** [elixir-lang/elixir#6982]
### Environment

* Elixir & Erlang versions (elixir --version):

```
Erlang/OTP 20 [erts-9.0] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10]
Elixir 1.5.1
```

* Operating system: Windows 10

### Current behavior

When Elixir tries to compile the following function:

```elixir
 defp strip_indent(line, indent) do
    case line do
      << _::binary-size(ident), rest::binary >> ->
        rest
      _ ->
        line
    end
  end
```

It fails with the given error message:

```
== Compilation error in file lib/guaxinim/internal/source_processor.ex ==
** (CaseClauseError) no case clause matching: []
    (elixir) src/elixir_bitstring.erl:113: :elixir_bitstring.expand_each_spec/4
    (elixir) src/elixir_bitstring.erl:86: :elixir_bitstring.expand_specs/5
    (elixir) src/elixir_bitstring.erl:29: :elixir_bitstring.expand/6
    (elixir) src/elixir_bitstring.erl:9: :elixir_bitstring.expand/4
```

This makes it very hard to diagnose the problem, which is simply the use of an unbound variable inside the binary match spec (it should be `indent` instead of `ident`).

### Expected behavior

Ideally, unbound variables should raise an appropriate error instead of the one above.

**Comment by josevalim** [comment]
A fix was already out on v1.5.2. Please update. :) See #6459.
