### ISSUE TITLE
Enum.at returning invalid value from list

### ISSUE THREAD

**Issue by rohanaceres** [elixir-lang/elixir#6983]
### Environment

Hi,

I'm using Elixir 1.5.1 on Debian 9. This is the output from `elixir --version`:

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```

When I create a list with a single element, if I try to use `Enum.at(0)` and `Enum.at(-1)`, both return the same element in the list. It also happens with `Enum.fetch` function.

### Current behavior

This is how to reproduce the issue (on iex):

```
iex(1)> track = [ 1 ]
[1]
iex(2)> Enum.at(track, 0)
1
iex(3)> Enum.at(track, -1)
1
iex(4)> Enum.fetch(track, 0)
{:ok, 1}
iex(5)> Enum.fetch(track, -1)
{:ok, 1}
```

### Expected behavior

```
iex(1)> track = [ 1 ]
[1]
iex(2)> Enum.at(track, 0)
1
iex(3)> Enum.at(track, -1)
nil
iex(4)> Enum.fetch(track, 0)
{:ok, 1}
iex(5)> Enum.fetch(track, -1)
:error
```

**Comment by wojtekmach** [comment]
This is per design:

> A negative index can be passed, which means the enumerable is enumerated once and the index is counted from the end (e.g. -1 finds the last element).

(https://hexdocs.pm/elixir/Enum.html#at/3)

**Comment by josevalim** [comment]
Closed as explained by @wojtekmach.

**Comment by rohanaceres** [comment]
@wojtekmach thanks for the explanation! But then why the `Enum.at(track, -2)` returns `nil`?

**Comment by wojtekmach** [comment]
@rohanaceres from the same docs:

> Returns default if index is out of bounds.

`default` is `nil`. Note you'll also get `nil` for `Enum.at(track, 2)` for the same reason.
