### ISSUE TITLE
Wrong NaiveDateTime comparison with/without microseconds

### ISSUE THREAD

**Issue by DenisGorbachev** [elixir-lang/elixir#6985]
First off, thanks for a great language!

Second, it looks like there's a bug in NaiveDateTime comparison:

### Environment

```
starfall@nx:~$ cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"

starfall@nx:~$ elixir --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.1
```

### Current behavior

```
iex(14)> ~N[2017-10-28 09:12:59.000000] >= ~N[2017-10-28 09:13:00]       
true
iex(15)> ~N[2017-10-28 09:12:59.000000] >= ~N[2017-10-28 09:13:00.000000]
false
```

### Expected behavior

```
iex(14)> ~N[2017-10-28 09:12:59.000000] >= ~N[2017-10-28 09:13:00]       
false
iex(15)> ~N[2017-10-28 09:12:59.000000] >= ~N[2017-10-28 09:13:00.000000]
false
```

**Comment by wojtekmach** [comment]
For comparisons please use `NaiveDateTime.compare/2` instead of `>=` and friends. From docs:

> **Comparing naive date times**
> Comparisons in Elixir using ==, >, < and similar are structural and based on the NaiveDateTime struct fields. For proper comparison between naive datetimes, use the compare/2 function.

https://hexdocs.pm/elixir/NaiveDateTime.html#module-comparing-naive-date-times

**Comment by ggcampinho** [comment]
Does it make sense to warn when we have Date/DateTime sigils comparison? We
are had a few issues about that already.

**Comment by josevalim** [comment]
@ggcampinho tricky. Theoretically there is nothing wrong with those comparisons, it is just not the meaning folks would expect. Plus we could only warn at compile time, which makes it less useful, and we wouldn't make it apply to all structs, so the mistake would still happen outside of Elixir.
