### ISSUE TITLE
formatter output is confusing when function calls are used between string interpolation

### ISSUE THREAD

**Issue by miwee** [elixir-lang/elixir#6989]
given this code:
```elixir
	  Logger.info "starting my_app{#{MyApp.build_time}} for device_id #{MyApp.device_id} and data_dir #{MyApp.data_dir}"
```
the formatter gives this:
```elixir
      Logger.info(
        "starting my_app{#{MyApp.build_time()}} for device_id #{
          MyApp.device_id()
        } and data_dir #{MyApp.data_dir()}"
      )
```

Inserting a new line in MyApp.device_id() function call deosn't make sense, as all three function calls are equivalent. A better formatting would be something like:
```elixir
      Logger.info(
        "starting my_app{#{MyApp.build_time()}} for device_id #{MyApp.device_id()}
         and data_dir #{MyApp.data_dir()}"
      )
```

**Comment by josevalim** [comment]
This is explained in the docs for the formatter, please check them out (Code.format_string!/2). The version you proposed is not equivalent, because of the newline, and likely not possible because it is reaching the default line length.

**Comment by josevalim** [comment]
Link: https://hexdocs.pm/elixir/master/Code.html#format_string!/2-adjusting-formatted-output
