### ISSUE TITLE
Regression in compiling behaviours 1.5 -> 1.6-dev ?

### ISSUE THREAD

**Issue by gasparch** [elixir-lang/elixir#6993]
### Environment

1.6 compiler: 
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] 
Elixir 1.6.0-dev (4b714eb) (compiled with OTP 20)

1.5 compiler:
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] 
Elixir 1.5.2

### Current behaviour

Here is minimal project that causes problems: https://gist.github.com/gasparch/23db7f298baa383180305465ad054d63

When running `mix test` compilation stage crashes with 

```
== Compilation error in file test/demo_test.exs ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for :undefined. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
    (elixir) /root/snap/parts/elixir/build/lib/elixir/lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) /root/snap/parts/elixir/build/lib/elixir/lib/enum.ex:166: Enumerable.member?/2
    (elixir) lib/enum.ex:1510: Enum.member?/2
    (elixir) lib/module.ex:1345: Module.add_callback/5
    (elixir) lib/enum.ex:1897: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/module.ex:1277: Module.check_behaviours_and_impls/4
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:657: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:171: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/1
```

Offending [line](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/module.ex#L1345), because `optional_callbacks == :undefined`

### Expected behavior

Same code compiles and runs without problems wit Elixir 1.5 (giving warnings that behaviour is not implemented).

Either it should compile/run or give nice compiler message that it cannot be compiled. Current message is totally cryptic and incomprehensible ;) Would be nice to compile :)

**Comment by josevalim** [comment]
:heart:

**Comment by gasparch** [comment]
thanks :)
