### ISSUE TITLE
Add truncate to Time, DateTime and NaiveDateTime

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#6997]
The idea is that it will correctly truncate the precision of the microseconds field. Instead of:

    %{time | microseconds: {0, 0}}

Developers can do:

    Time.truncate(time)
    Time.truncate(time, :milliseconds)

This is useful when you are writing to a storage that has lower precision than microseconds.

Note the first element in microseconds tuple needs to be properly truncated too. This means:

    %{time | microseconds: {123456, 6} |> Time.truncate(:milliseconds)

will return a field with microseconds set to `{123000, 3}`.

/cc @wojtekmach @lau

**Comment by rlustin** [comment]
Hello!

I’d like to work on this issue. Can you assign it to me?

**Comment by josevalim** [comment]
Thanks @rlustin! We can't assign it to you as we can only assign to maintainers. However, note the issue has a Discussion label, this means we are not quite sure it will be added. You can go ahead and implement it but there is a chance we will change function names or even give up on it completely.

**Comment by rlustin** [comment]
I understand, no problem. I’m just looking for easy issues to fix to start contributing to Elixir :)
I may start an implementation, even just for the sake of the exercise.

**Comment by josevalim** [comment]
Then by all means please go ahead! :D You can check the README.md for general contribution instructions.

**Comment by wojtekmach** [comment]
:+1:, I often incorrectly did: `%{t | microsecond: 0}` only to later learn I corrupted my struct

**Comment by josevalim** [comment]
@rlustin please let us know if you got started or if you need help moving forward!

**Comment by rlustin** [comment]
I’m almost done, and still have to write some documentation. I’ll suggest a PR during the day.
