### ISSUE TITLE
Autocompleting types

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#6999]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.6.0-dev (compiled with OTP 20)
* Operating system: macOS Sierra

### Current behavior

Currently, we always autocomplete functions (or variables etc). However, specifically for `t` helper the autocompleted value will almost always be wrong:

```
iex> t System.time_<tab> # => System.time_offset
```

I'd like to propose to add special treatment for `t` so that only types are autocompleted.

### Expected behavior

```
iex> t System.time_<tab> # => System.time_unit
```

**Comment by brodeuralexis** [comment]
@josevalim, may I take this issue ?

**Comment by josevalim** [comment]
It is in master thanks to @brodeuralexis! I also added callback completion in the next commit: 7869f1ca1bd7bdf105dda4d57a7f94f5a29ba4d2
