### ISSUE TITLE
Inconsistent formatting of do:

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#7007]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0-dev (88f4a5796) (compiled with OTP 20)
``` 

### Current behavior

```elixir
defmodule Foo do
  defp token_list_downcase(<<char, rest::binary>>, acc) when is_whitespace(char) or is_comma(char),
       do: token_list_downcase(rest, acc)

  defp token_downcase(<<char, rest::binary>>, token, acc) when is_tchar(char),
    do: token_downcase(rest, <<token::binary, lower_char(char)>>, acc)
end
```

### Expected behavior

The first function clause should have the same indentation as the second clause or move the guard to a new line:

```elixir
defmodule Foo do
  # Alternative 1
  defp token_list_downcase(<<char, rest::binary>>, acc) when is_whitespace(char) or is_comma(char),
    do: token_list_downcase(rest, acc)

  # Alternative 2
  defp token_list_downcase(<<char, rest::binary>>, acc)
       when is_whitespace(char) or is_comma(char),
       do: token_list_downcase(rest, acc)
end
```

**Comment by whatyouhide** [comment]
FWIW we use "Alternative 1" for other times when we use keyword lists as the last argument:

```elixir
config :foo, :bar,
  baz: :bong
```

**Comment by isaacsanders** [comment]
I also use this alternative frequently

```elixir
defmodule Foo do
  defp token_list_downcase(<<char, rest::binary>>, acc)
    when is_whitespace(char) or is_comma(char),
    do: token_list_downcase(rest, acc)
end
```

**Comment by josevalim** [comment]
Yup, this is behaving as expected. You can force them to be consistent by putting the `when` in its own line. Then it will behave like @isaacsanders mentioned, except it is aligned with the beginning of token_list_downcase.

**Comment by ericmj** [comment]
What is the rule that causes this to happen and why do we need to keep that rule over a rule that gives us alternative 1 or 2?

**Comment by josevalim** [comment]
The general rule is 2 but 1 exists because of `config` as pointed out by @whatyouhide. 1 is only applied if all previous arguments fits on the previous line and the trailing keywords do not fit on said line.

**Comment by ericmj** [comment]
@josevalim Maybe you are misunderstanding me. Alternative 1 and 2 is what i expect to happen but it isn't happening. I can force alternative 2 by inserting newlines but I cannot make it format as 1.

What I am seeing is the first clause under "Current behavior".

**Comment by josevalim** [comment]
You can't force the first clause. Clause 2 is the rule. Clause 1 is the exception.
