### ISSUE TITLE
Do not emit conflicting behaviours if the same behaviour is used more than once

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7008]

**Comment by josevalim** [comment]
Not a regression. Erlang emitted this warning already and we should continue emitting it too.

**Comment by novaugust** [comment]
Came here to open an issue but I think you're describing what I came to ask about.
The following is not considered a bug then, right?
```elixir
iex(1)> defmodule Behave do
...(1)>   @callback foo(any) :: any
...(1)> end
{:module, Behave,
 <<70, 79, 82, 49, 0, 0, 4, 36, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 164,
   0, 0, 0, 15, 13, 69, 108, 105, 120, 105, 114, 46, 66, 101, 104, 97, 118, 101,
   8, 95, 95, 105, 110, 102, 111, 95, 95, ...>>, true}
iex(2)> defmodule Implement do
...(2)> @behaviour Behave
...(2)> @behaviour Behave
...(2)>   def foo(any), do: any
...(2)> end
warning: conflicting behaviours found. function foo/1 is required by Behave and Behave (in module Implement)
```

**Comment by josevalim** [comment]
Yup, it is not a bug. I believe the ja_resource is the same project that actually made me first open this. :)

**Comment by novaugust** [comment]
Thanks for the confirmation! FYI, there's nothing about this change in the 1.6 changelog, but hopefully people'll just find this issue

**Comment by josevalim** [comment]
There is nothing in the CHANGELOG because it is supposedly the same
behavior as in v1.5. If it is not the same behavior then we do have to fix
it.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by novaugust** [comment]
> There is nothing in the CHANGELOG because it is supposedly the same behavior as in v1.5. If it is not the same behavior then we do have to fix it.

Might need to fix it then! I only saw this compiler error when trying out 1.6 to see if we could immediately upgrade. 

Here's the same code as above, run on 1.5.1 (version in top line)
```ex
Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule Behave do
...(1)> @callback foo(any) :: any
...(1)> end
{:module, Behave, .....}
iex(2)> defmodule Implement do
...(2)> @behaviour Behave
...(2)> @behaviour Behave
...(2)>   def foo(any), do: any
...(2)> end
{:module, Implement,
 <<70, 79, 82, 49, 0, 0, 3, 216, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 86,
   0, 0, 0, 8, 16, 69, 108, 105, 120, 105, 114, 46, 73, 109, 112, 108, 101, 109,
   101, 110, 116, 8, 95, 95, 105, 110, 102, ...>>, {:foo, 1}}
```

**Comment by atomkirk** [comment]
also seeing this with changing nothing else in my project except upgrade to 1.6.

compile, no warning
`asdf install elixir 1.6 && asdf global elixir 1.6`
compile, warnings

**Comment by josevalim** [comment]
Thanks folks! I just double checked Erlang once again and it does emit those warnings. I would say we should align with Erlang here, because otherwise tools like dialyzer can misbehave too, so I will go ahead and update the CHANGELOG.
