### ISSUE TITLE
IEx with remsh flag crashes when running Mix task which uses ensure_all_started

### ISSUE THREAD

**Issue by tpitale** [elixir-lang/elixir#7009]
### Environment

* Elixir & Erlang versions (elixir --version):  Erlang/OTP 20 [erts-9.0.4] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.5.1

* Operating system: inside docker, using `FROM elixir:1.5.1-slim`

### Current behavior

`iex --name my_console --cookie $COOKIE --remsh $NAME -S mix my_app.some_task` appears to fail because my app fails to start (it collides with a running port of the remote process I'm connected to).

`iex --name my_console --cookie $COOKIE --remsh $NAME` does work perfectly. Once at a console I can then run `Mix.Tasks.MyApp.SomeTask.run(args)` and it also works as expected.

`Mix.Tasks.MyApp.SomeTask` includes a line `Application.ensure_all_started(:my_app)` which simply returns `{:ok, []}` if I run it on `iex` with `--remsh` (as you could probably guess)

### Expected behavior

Running `iex` with `--remsh` and then using `-S mix …` would run the task just as it does if I start `iex` and then run the task using its module.

**Comment by josevalim** [comment]
The task is going to run on the server. So if the server is already running on that port, then running the task which will start another app on the same port will definitely cause it to fail to start.

**Comment by josevalim** [comment]
You can try the User Switch way as outlined here: https://hexdocs.pm/iex/IEx.html#module-remote-shells

**Comment by tpitale** [comment]
@josevalim Please re-read the issue. I'm doing what's described there:

```
In fact, connecting to remote shells is so common that we provide a shortcut via the command line as well:

$ iex --sname baz --remsh foo@HOST
```

**Comment by tpitale** [comment]
If I run `iex` with `--remsh` and then use the task's module to run; it works.

If I run `iex` with `--remsh` AND `-S mix`; it does not work.

**Comment by tpitale** [comment]
Maybe whatever is passed to `-S mix …` runs _before_ `iex` is started … I just assumed `iex` would start and the `-S` would be the first thing it would run.

**Comment by josevalim** [comment]
I still don't understand why are you expecting both to behave the same when they are doing different thiings. Namely one is running the mix task and the other does not. You also need to consider the context the mix task will run when you pass the --remsh flag.

**Comment by josevalim** [comment]
> `iex --name my_console --cookie $COOKIE --remsh $NAME` does work perfectly. Once at a console I can then run Mix.Tasks.MyApp.SomeTask.run(args) and it also works as expected.

How can you invoke the task if `-S mix` was not given and therefore the project code won't be available?

**Comment by tpitale** [comment]
@josevalim Sorry, I guess wasn't clear … I'm using `--remsh` to connect to an already running instance of the application. That's why calling `Mix.Tasks.MyApp.SomeTask.run` works when I start `iex`.

**Comment by josevalim** [comment]
> @josevalim Sorry, I guess wasn't clear … I'm using --remsh to connect to an already running instance of the application. 

Doh, that makes sense. It was my bad. So, as you said earlier, the mix command runs BEFORE you connect to the node. To make sure there is no confusion:

```
$ iex --sname another_console --remsh my_console -e "IO.inspect(node())" -S mix run -e "IO.inspect(node())"
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

:another_console@josemac
:another_console@josemac
```
