### ISSUE TITLE
The way the child spec argument is applied to start keyword prevents workers from having start_link/0 functions

### ISSUE THREAD

**Issue by pickme467** [elixir-lang/elixir#7018]
https://github.com/elixir-lang/elixir/blob/7f8db39ce27854c34b7d722783f5e89a9058fbe1/lib/elixir/lib/supervisor.ex#L445

Now it is hard to use child_spec predefined function to start workers under supervisor tree if given worker has start_link/0 function defined. 
Current implementation puts an argument taken from child_spec into a list of arguments in start keyword. It makes implicit assumption that start_link would have at least one argument.

If start keyword would concatenate child_spec's argument if it is a list or do what it does now otherwise, that would make possible to create workers which have start_link/0 functions.

Line like this one would work:
{:ok, worker} = Supervisor.start_child(supervisor, SomeWorker.child_spec([]))

With the current implementation either dummy parameter needs to be added to start_link on worker to make it start_link/1 or full spec needs to be provided to Supervisor.start_link which is a kind of redundancy.

**Comment by josevalim** [comment]
That's by design. Having a dummy parameter is not bad because, if you ever need to expect a new argument, then nobody needs to change the signature.

If you don't agree with it or you having existing workers, then you can always specify the child_spec by hand, which is what we always did in the past - so I don't see why that would be an issue now.

**Comment by michaelkschmidt** [comment]
@josevalim Sorry to push back, but I think @pickme467  is correct.  This line is breaks the convention of both Elixir and Erlang:

```elixir
worker(SomeModule,[])
```
would result in a call to
```elixir
SomeModule.start_link()
```

The new syntax of
```elixir
{SomeModule,[]}
```
calls
```elixir
SomeModule.start_link([])
```

This means that to convert to the new Supervisor syntax, we have to change every module we use, wrapping its args in `[]`
