### ISSUE TITLE
Documentation for Protocol.derive is missing information how it works

### ISSUE THREAD

**Issue by narrowtux** [elixir-lang/elixir#7019]
Reading the [code in Poison](https://github.com/devinus/poison/blob/master/lib/poison/encoder.ex#L344), it seems like you have to add a macro named `__deriving__` to an impl to get the options that were passed. The documentation and the guides on the homepage don't tell you that. 

Also, I'd like a hint that you can use `@derive` attributes on a struct in the documentation for Protocol.derive

**Comment by josevalim** [comment]
Yup, those will be good improvements. Thank you.

**Comment by acconrad** [comment]
I'll take this! How do I claim this issue to work on it?

**Comment by ericmj** [comment]
@acconrad Mentioning in the issue that you are working on it is enough. Thanks!
