### ISSUE TITLE
Comprehensive overview of elixir and OTP versions

### ISSUE THREAD

**Issue by NobbZ** [elixir-lang/elixir#7025]
After a quick chat in IRC with @ericmj, he asked me to open an issue:

Currently its hard to find out what elixir versions require which version of BEAM or otherwise support it.

Often one has to skim the changelog to find out which is the upper bound of official support while having to search the web pages source history to get the minimum required version of OTP.

Therefore I'd suggest to provide a cheat sheet, matrix or otherwise comprehensive overview of elixir versions and their minimum required OTP versions as well as the officially supported ones/known to work ones.

**Comment by ericmj** [comment]
I'm thinking we can add this to Deprecations or a new a page in the ExUnit pages docs.

**Comment by whatyouhide** [comment]
Why ExUnit @ericmj? 🤔

**Comment by ericmj** [comment]
I meant ExDocs. These pages: https://hexdocs.pm/elixir/deprecations.html#content

**Comment by josevalim** [comment]
Available on master: https://hexdocs.pm/elixir/master/compatibility-and-deprecations.html
