### ISSUE TITLE
Make error message when using optional arguments in lambdas more explicit

### ISSUE THREAD

**Issue by Wonko7** [elixir-lang/elixir#7029]
### Environment

Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [async-threads:10]
Elixir 1.5.2
Linux.

### Current behavior

```
iex(4)> f = fn x \\ 3 -> x end
** (CompileError) iex:4: undefined function \\/2
    (elixir) src/elixir_fn.erl:10: anonymous fn/3 in :elixir_fn.expand/3
    (stdlib) lists.erl:1239: :lists.map/2
    (elixir) src/elixir_fn.erl:14: :elixir_fn.expand/3
```

### Expected behavior

Something that helps to understand why that's not legal. As I was told on IRC:
```
nox> 	wonko7: Optional arguments actually compile to different functions with different arities.
nox> 	A single function still has a single arity. So lambdas cannot have optional arguments.
```

**Comment by jgmchan** [comment]
Would I be able to try doing this one? From what I understand I will need to modify the logic in `lib/elixir/src/elixir_fn.erl` and add a new `format_error` function?
