### ISSUE TITLE
Logger.Backend.Console: Does not reset configuration after redefining

### ISSUE THREAD

**Issue by Virviil** [elixir-lang/elixir#7035]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] Elixir 1.5.2
* Operating system: Manjaro Linux

### Current behavior

```
iex(1)> require Logger
Logger
iex(2)> Logger.configure_backend(:console, format: "$metadata[$level] $message\n")
:ok
iex(3)> Logger.warn("Foo", foo: :bar)
[warn] Foo #foo=bar does not appear, as configured
:ok
iex(4)> Logger.configure_backend(:console, format: "$metadata[$level] $message\n", metadata: [:foo])
:ok
iex(5)> Logger.warn("Foo", foo: :bar)
foo=bar [warn] Foo #foo=bar appears, because of changing configuration
:ok
iex(6)> Logger.configure_backend(:console, format: "$metadata[$level] $message\n")
:ok
iex(7)> Logger.warn("Foo", foo: :bar)
foo=bar [warn] Foo #foo=bar appears again, even after redefining configuration.
# This still looks logical, because we do not explicitly point about metadata
:ok
iex(8)> Logger.remove_backend(:console)
:ok
iex(9)> Logger.add_backend(:console)
{:ok, #PID<0.95.0>}
iex(10)> Logger.configure_backend(:console, format: "$metadata[$level] $message\n")
:ok
iex(11)> Logger.warn("Foo", foo: :bar)
foo=bar [warn] Foo #foo=bar appears after removing/adding console backend, which feels like wrong behavior
:ok
```

### Expected behavior

Different aproaches:

1. Even in `iex(7)` foo=bar should not appear - because it should be reconfigured explicitly (My opinion - this approach is wrong)
2. In `iex(11)` foo=bar should not appear - because we recreating the backend.
    ```
    iex(11)> Logger.warn("Foo", foo: :bar)
    [warn] Foo
    ```

**Comment by josevalim** [comment]
This is working as intended. You can explicitly set metadata to an empty list if you want to remove it. The reason this is working as intended is because sometimes you want to temporarily remove or disable a backend, and we don't want to lose all previous configuration. We also want the configuration to "stick" if for some reason the backend is restarted too.

**Comment by Virviil** [comment]
Well, it sounds logical...

May be, additional method to reset this config should be provided then?

Let's for example assume, that we want to change logger logic dynamically. And we want to switch from 2 configurations - as provided in example.
Then after back switch, logger behavior is not the same as on the first cycle, and it looks like **not pure**

I'm facing this problem when switching logger config in production environment. Current approach forces me to explicitely *nullify* each and every parameter to keep system with the same attitude.

I'm not sure, that this approach is right or wrong, but may be it can be discussed.
