### ISSUE TITLE
short-circuited expressions causing "nil" assignment

### ISSUE THREAD

**Issue by ishantar** [elixir-lang/elixir#7044]
elixir 1.5.2, erlang 20, windows 7 x64

If a pattern-matching operation is nested within the right-side expression of a short circuit operator, and the left-side expression causes the operator to short-circuit, unbound identifiers in the right-side pattern-match will be silently assigned to "nil".  Nesting the pattern-match in some sort of wrapper seems to be neccessary.

examples: (assume x is unbound)
```
a.    false and (x=1)  => "false"           
b.    true || (x="a") => "true"               ## for a. and b., parens are needed
c.    if false do x={:a} end => "nil"         ## here the do/end block is enough

```

These or similar expressions assign 'x' to 'nil' as a side effect.  Other conditionals do the same.
Variables assigned this way type-check (is_nil, is_atom) and seem to otherwise behave normally.  

note: if called without the parentheses, the 'a' and 'b' examples return:
 (CompileError) iex:21: cannot invoke remote function :erlang.andalso/2 inside match
    (elixir) expanding macro: Kernel.and/2
    iex:21: (file)

Expected behavior is either an error, or assignment-free non-evaluation.

(I ran into this just fooling around, it might be totally unimportant.  But it doesn't seem to be documented so I figured I'd pass it along).

**Comment by NobbZ** [comment]
Shouldn't there be a warning, telling you about imperative assignements?

If not, then the bug is that there is no warning, not that the variables are bound to `nil`.

At least this is my opinion.

**Comment by josevalim** [comment]
Today we emit a warning but you don't see this warning on IEx because we evaluate the expression at distinct moments. However there is a bug in this warning/error, which we need to fix:

```elixir
false and (x=1)
x
```

```
** (CompileError) foo.exs:2: variable 'Vx@1' unsafe in 'case' (line 1)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (elixir) lib/code.ex:678: Code.require_file/2
```

**Comment by ggcampinho** [comment]
@josevalim I get this on master
```
iex(1)> false and (x=1); x
** (ErlangError) Erlang error: {:unbound, :Vx@1}
```

but when I'm running the version installed on my machine (Elixir 1.5.1), I have:
```
iex(1)> false and (x=1); x
warning: the variable "x" is unsafe as it has been set inside one of: case, cond, receive, if, and, or, &&, ||. Please explicitly return the variable value instead. For example:

    case integer do
      1 -> atom = :one
      2 -> atom = :two
    end

should be written as

    atom =
      case integer do
        1 -> :one
        2 -> :two
      end

Unsafe variable found at:
  iex:3

nil
```

Is the second behavior the desired one?

**Comment by josevalim** [comment]
Yes, it needs to be a warning. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
