### ISSUE TITLE
Enum.reduce_while on a stream is not behaving as expected

### ISSUE THREAD

**Issue by jfayad** [elixir-lang/elixir#7050]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.1
* Operating system: Mac OS Sierra

### Current behavior

If reduce_while receives `{[], 0}` it will not iterate to the next element and it will stop instead.

### Expected behavior

I would expect the enumeration to keep reading the stream...

More details can be found here: https://github.com/rubencaro/sshex/issues/19

**Comment by josevalim** [comment]
Can you please provide a quick snippet that reproduces the error?

**Comment by jfayad** [comment]
Hi @josevalim ,

The snippet I have relies on SSHEX

```
  defp ssh_connect() do
    ip = Application.fetch_env!(:ew_aegir_bridge, EwAegirBridge.Aegir) |> Keyword.get(:aegir_server_ip)
    username = Application.fetch_env!(:ew_aegir_bridge, EwAegirBridge.Aegir) |> Keyword.get(:aegir_server_user)
    case Mix.env do
      :dev ->
        SSHEx.connect ip: to_charlist(ip), 
      user: to_charlist(username), 
      user_dir: Application.fetch_env!(:ew_aegir_bridge, EwAegirBridge.Aegir) |> Keyword.get(:user_dir)
      _ ->
        SSHEx.connect ip: to_charlist(ip), 
      user: to_charlist(username)
    end
  end
  defp aegir_commad(commands) do
    
    # open ssh connection to terminal
    case ssh_connect() do
      {:ok, connection} -> 
        ping = "ping -c 2 www.google.com; ping -c 3 www.google.fr;"
        IO.puts ping
        str = SSHEx.stream connection,'#{ping}'
        IO.puts "Stream returned from SSHex"
        str
        |> Enum.reduce_while({}, fn(x, acc)->
          IO.inspect x
              case x do
                {:stdout,row}    -> 
                  {:cont, {}}
                {:stderr,row}    -> 
                  {:cont, {}}
                {:status,status} -> 
                  {:halt,{:ok, status}}
                {:error,reason}  -> 
                  {:halt,{:error, reason}}
              end
            end)
      {:error, reason} ->
        {:error, reason}
    end 
  end
```

I initially though this was an issue with the sshex project and created the issue I referenced above there. After further inspections with the creator of sshex it appeared the problem comes from `reduce_while`.

**Comment by josevalim** [comment]
@jfayad sorry for not being clear. Can you provide a minimal snippet that reproduces the error that I can run on IEx?

**Comment by jfayad** [comment]
Ohh sure, 

Does this make it ? (You'll need the SSHex module for it work).

```
defmodule A do

  def go(cmd) do
    {:ok, conn} = SSHEx.connect ip: "127.0.0.1"
    str = SSHEx.stream conn, cmd
    Enum.reduce_while(str, [], fn(x, acc)->
      case x do
        {:stdout, row}    -> {:cont, acc ++ [row]}
        {:stderr, row}    -> {:cont, acc ++ [row]}
        {:status, status} -> {:halt, acc ++ ["stopped"]}
        {:error, reason}  -> {:halt, acc ++ [reason]}
      end
    end)
  end

end
```

**Comment by ericmj** [comment]
@jfayad Since you figured out the error is not in SSHEx can you provide a reproducing example that does not require us to dig into the SSHEx library. Some code that reproduces without using external dependencies would help a lot. Thanks!

**Comment by jgmchan** [comment]
I think the issue is not with `Enum.reduce_while` but with the logic in the reducer function.
```
defmodule A do

  def go(cmd) do
    {:ok, conn} = SSHEx.connect ip: "127.0.0.1"
    str = SSHEx.stream conn, cmd
    Enum.reduce_while(str, [], fn(x, acc)->
      case x do
        {:stdout, row}    -> {:cont, acc ++ [row]}
        {:stderr, row}    -> {:cont, acc ++ [row]}
        {:status, status} -> {:halt, acc ++ ["stopped"]} 
        #####                 ^^^ This should be {:cont, acc ++ ["stopped"]} #####
        {:error, reason}  -> {:halt, acc ++ [reason]}
      end
    end)
  end
end
```

I did some testing with the SSHEx library by dumping out the process mailbox after the command has been executed in the `Stream.resource`'s `start_fun` and the messages received were (though not necessarily always in the exact order):
```
iex(1)> A.go("hostname")
PROCESS_MAILBOX: [
  {:ssh_cm, #PID<0.212.0>, {:data, 0, 0, "ubuntu-xenial\n"}},
  {:ssh_cm, #PID<0.212.0>, {:exit_status, 0, 0}},
  {:ssh_cm, #PID<0.212.0>, {:eof, 0}},
  {:ssh_cm, #PID<0.212.0>, {:closed, 0}}
]
["ubuntu-xenial\n", "stopped"]
```
The logic in the reducer function will stop the enumeration after processing the `:exit_status` message and leave the `:eof` and `:closed` message in the mailbox. This then stuffs up the next call to `A.go`.

Changing `{:status, status} -> {:halt, acc ++ ["stopped"]}` to `{:status, status} -> {:cont, acc ++ ["stopped"]}` in the reducer function solves the problem.

**Comment by josevalim** [comment]
Thanks @jgmchan. So it seems to not be an issue with Elixir after all?

**Comment by jgmchan** [comment]
No, it's not an issue with Elixir.

**Comment by ericmj** [comment]
@jgmchan Thank you for looking into it.

**Comment by jfayad** [comment]
Thanks Everyone for the help. I'll inform the maintainer of the SSHex module about how things developed here so a fix can be pushed there.
