### ISSUE TITLE
Invalid AST in debug_info for default calls

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#7054]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0-dev (d8a533d19) (compiled with OTP 20)
```

### Current behavior

When reading the data from `debug_info` chunk, the definitions with default arguments are expanded very strangely. Given the following module:

```elixir
defmodule Test do
  def test(x \\ 1), do: x
end
```

We get following in the `:definitions` field:
```elixir
[
  {{:test, 1}, :def, [defaults: 1, line: 2], [
     {[line: 2], [{:x, [line: 2], nil}], [], {:x, [line: 2], nil}}
   ]},
  {{:test, 0}, :def, [line: 2], [
     {[line: 2], [], [], {:super, [line: 2], [{:def, :test}, 1]}}
   ]}
]
```

As you can see, it contains a strange `super({:def, :test}, 1)` call.

### Expected behavior

The AST should probably contain a simple `test(1)` call instead of the `super` call.

**Comment by josevalim** [comment]
It behaves as such by intent. We need to document the internal AST, currently it is still private.

**Comment by josevalim** [comment]
In a nutshell, super in the expanded AST means calling the function given as first argument with the remaining arguments. I thought about putting the `{Kind, Name}` in the metadata but it may be weird to require some AST node to be present? The other idea is to introduce a new internal node, such as `__local__` but the way things work means the users wouldn't be able to use such node as well, which is a smell.
