### ISSUE TITLE
Add blame/2 as a callback of the Exception behaviour

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7074]
`Exception.blame/3` should normalize errors and delegate to the callback:

```elixir
  def blame(:error, error, stacktrace) do
    %module{} = struct = normalize(:error, error, stacktrace)
    module.blame(struct, stacktrace)
  end
```

The callback should return a tuple with the blamed exception and the stacktrace. A default callback will be generated by default by defexception.

/cc @michalmuskala @chrismccord

**Comment by michalmuskala** [comment]
I like that. I would change it slightly and instead made the callback optional instead of macro-generating the default.

**Comment by josevalim** [comment]
> I would change it slightly and instead made the callback optional instead of macro-generating the default.

Great idea. We can check for `Code.ensure_loaded?` and `function_exported?` and then call blame/2 only if it exists.

**Comment by michalmuskala** [comment]
I'll send a PR
