### ISSUE TITLE
IEx appending to IEx.History state regardless of shell_history value

### ISSUE THREAD

**Issue by bglusman** [elixir-lang/elixir#7080]
Reddit user [ClemDev](https://www.reddit.com/user/ClemDev) reported this on Elixir Reddit [here](https://www.reddit.com/r/elixir/comments/7gws99/iex_locks_up_when_calling_processinfoself_a_lot/), and at first I didn't think it was a bug since I had IEx history enabled, but even when disabling the shell_history param the history grows with every call.

I think there's an easy fix to check the Erlang VM env var before appending history [here](https://github.com/elixir-lang/elixir/blob/e120a212ad1d86034de6df0450eae542ec127dfa/lib/iex/lib/iex/history.ex#L16) and have a possible PR of that [here](https://github.com/elixir-lang/elixir/compare/master...bglusman:master), but never opened an issue or PR on Elixir before so thought I'd check first :-)  @josevalim thought it should be opened as an issue and chimed in there, somewhat of an edgecase but in a long enough IEx session it could have implications, particularly if running on a production machine (where history is less likely to be enabled).  Assuming there's no other value/usage to this history state without erlang shell_history enabled, this seems like an easy fix.

**Comment by bglusman** [comment]
After this was opened [dmor](https://www.reddit.com/user/dmor) on reddit pointed out some reasons this may not be a bug at all, but might still be an opportunity for improvement or making it more similar to how erlang's repl behaves, but the behavior can be repro'd there, it's just storing it in a seperate process not the main process.

**Comment by josevalim** [comment]
I agree with diagnosis from the reddit folks, it is not a bug, but it was worth investigating nonetheless. Thanks for following up!
