### ISSUE TITLE
Consider adding a new "trace" log level in the Logger

### ISSUE THREAD

**Issue by whitfin** [elixir-lang/elixir#7083]
This stems from discussion on the mailing list, Slack, and around friends/colleagues. I'm opening this issue for broader feedback; most people I've spoken to agree that this is a hole in the existing API.

There currently exists no good solution for a library developer to log messages. If I am writing a package that's designed to be a Mix dependency, I want to be able to log messages which are not shown unless the end-user of the library turns them on. This is not possible because the default log level in `Logger` also happens to be the lowest log level. I believe that we should add a new logging level, which is off by default. This can be seen as "verbose" logging, but I think "trace" would be a better name due to the length of the name. 

I have polled across various developers from various backgrounds; it appears Ruby developers think it's fine as is (which makes sense as Ruby is the same). However, people I spoke to coming from Java, Node.js and C/C++ all agree there should be a level that is opt-in, rather than opt-out. Typically the `:info` level (or synonymous) would be the default when coming from those languages, but due to Ruby familiarity and the existing API, Elixir should likely keep `:debug` as default. However this does mean that there should likely be something familiar for these other types of developer backgrounds too.

Currently there is no good solution other than "write something in your code to handle it". You can tell a user to turn off the debug logs, but they can't control them for a single application as far as I know. It's also a step a user has to do; it would be better if the developer could handle it for them. It's far better to be suppressed by default and only have it turned on if a user feels it necessary (they see a bug, strange behaviour, etc).

A couple of examples for the types of logs I'm referring to as a library developer:

1. Maybe you want to log every message a server receives, clearly far too noisy to be on by default, but useful when debugging.
2. Periodic updates of assets, some sort of scheduled process which emits what's happening; again too noisy due to the repetition.

When reading this, please keep in mind that I'm not talking about writing logs in your own production application - focus on the concept of writing code that is included by other developers (OSS projects, etc).

**Comment by josevalim** [comment]
Please hold on with moving issues from the mailing list to the issues tracker until there is a consensus or an explicit approval. We have no plans in introducing a new log level because then we will only shift the issue: for example, lib A uses lib B and lib A wants to debug its own "traces" but lib B is too verbose.

I am personally more inclined in allowing the log level to be purged per library at compile time. I believe this effectively solves this problem and it could also be useful for production (it has been asked in the past). In any case, this discussion still belongs to the mailing list and not here.

**Comment by whitfin** [comment]
Hey @josevalim! Gotcha and noted; there's a thread [here](https://groups.google.com/d/msg/elixir-lang-core/C5-ixZVau3U/Wq0uuDy-BgAJ) but most feedback came via Slack (hence why I moved here). I'll wait for further mailing list feedback; I'd appreciate if you could drop your thoughts in if you get a chance!
