### ISSUE TITLE
Range arithmetic

### ISSUE THREAD

**Issue by bcardarella** [elixir-lang/elixir#7088]
This may be something that is working by mistake at the moment:

```elixir
1..1 + 1

=> 1..2
```

I'm guessing there is some Protocol that is allowing for this? It would end up being useful in certain circumstances, but when the range is assigned to a variable `:erlang.+` is used and an error is raised:

```elixir
foo = 1..1
foo + 1

** (ArithmeticError) bad argument in arithmetic expression
    :erlang.+(1..1, 1)
```

If the range arithmetic is not intended can it be disallowed in the first case? If it is intended then I guess there is a bug as demonstrated in the second case.

I'm on Elixir 1.5.2 w/ OTP 20

**Comment by wojtekmach** [comment]
`1..1 + 1` expands to the same AST as `1..(1 + 1)` and that's the only reason it works

**Comment by josevalim** [comment]
Yup, @wojtekmach got it. It is related to the operator precedence in this case!

**Comment by bcardarella** [comment]
Thanks for the quick explanation!
