### ISSUE TITLE
`mix format` changes file modification time if content was not changed

### ISSUE THREAD

**Issue by remiprev** [elixir-lang/elixir#7090]
If `mix format` is ran on a file and its content is not changed by the formatter, its modification time is still updated.

### Environment

* Elixir & Erlang versions (elixir --version): 
  ```bash
  $ elixir -v
  Erlang/OTP 20 [erts-9.1.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

  Elixir 1.6.0-dev (102d22a8f) (compiled with OTP 20)
  ```

* Operating system: 
  ```bash
  $ uname -a
  Darwin sun 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64 i386 MacBookPro11,4 Darwin
  ```
  * MacOS 10.12.6

### Current behavior

```
$ stat config/config.exs
mtime   1512563789

$ md5sum config/config.exs
6ba14e314d35959e0702095fcba2ef18  config/config.exs

$ mix format

$ stat config/config.exs
mtime   1512563851

$ md5sum config/config.exs
6ba14e314d35959e0702095fcba2ef18  config/config.exs
```

We can see the file’s `mtime` attribute has been updated but its content stayed the same (hence the same md5 hash).

The problem with this is that it doesn’t play well with Phoenix code reloading feature (and probably other tools that look at file modification times to detect file updates) which requires the developer to restart its server when a config file has been modified (based on `mtime`):

```
You must restart your server after changing the following config or lib files:

  * config/config.exs
```

It this by design in `mix format` or is it a bug? Should the file be _touched_ even if its content was not changed by the formatter?

### Expected behavior

If `mix format` doesn’t change the content of a file, it should not change its modification time.

Thank you! 😄

**Comment by josevalim** [comment]
Yup, we should not write the files. A quick benchmark I ran locally even showed that the formatter is faster if it is not writing on every change.

**Comment by doomspork** [comment]
@josevalim I'd be happy to take a whack at this if it's not something you're already tackling 👍

**Comment by josevalim** [comment]
@doomspork glad you asked because I am almost done with it! :D
