### ISSUE TITLE
Compilation error with too many modules

### ISSUE THREAD

**Issue by geofflane** [elixir-lang/elixir#7091]
### Environment

Elixir 1.5.2 & Erlang 19.3
Ubuntu Linux 17.10 

### Current behavior
(This is a Phoenix app that does some statistics tracking and so has a large number of small ecto schemas each with a corresponding "calculator" to condense data into various stats.)

I have a project with about 600 modules currently. Somewhere between about 550 and 600 modules the elixir compiler can no longer compile the full application from a clean state. We get an error in the locals_tracker related to too many ets tables apparently.

> ** (exit) an exception was raised:
>     ** (SystemLimitError) a system limit has been reached
>         (stdlib) :ets.new(:edges, [:set, :protected])
>         (stdlib) digraph.erl:78: :digraph.new/1
>         (elixir) lib/module/locals_tracker.ex:232: Module.LocalsTracker.init/1
>         (stdlib) gen_server.erl:328: :gen_server.init_it/6
>         (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

At other times I get:

> [error] ** Too many db tables **

### Expected behavior

To compile with a larger number of modules.

Workaround for now is to refactor into an umbrella app with multiple sub apps.

**Comment by josevalim** [comment]
@geofflane I believe this system limit has been removed on Erlang/OTP 20. Did you give it a try?

**Comment by wojtekmach** [comment]
you can also manually bump the limit by setting env var

```
export ERL_MAX_ETS_TABLES=5000
```

**Comment by geofflane** [comment]
@josevalim I believe you are correct that Erlang 20 does away with that limit. We have multiple apps that are deployed using Docker on Alpine images and Alpine doesn't get Erlang 20 in a release until the end of this year... so for reasons, hadn't tried that yet. :)

I just assumed others would still be on 19 as well and didn't know the implications of bumping the max ets tables.

**Comment by josevalim** [comment]
@geofflane oh, you definitely did well in reporting! I was just providing a quick work around for now. :)

**Comment by AndrewDryga** [comment]
Sidenote: @geofflane you can build Alpine image on your own, this one works for a large project - https://hub.docker.com/r/nebo15/alpine-erlang/~/dockerfile/.
