### ISSUE TITLE
Newline (\n) before comma in parentheses arguments is syntax error while no space and space is not

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#7093]
While making optimizations to the IntelliJ Elixir parser and grammar, I came up with some new test cases for treating optional newlines the same as whitespace.  When testing comma handling, I hit a case that is reported as an error in the native parser/tokenizer.

### Environment

* Elixir & Erlang versions (elixir --version): 
  ```
  Erlang/OTP 20 [erts-9.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] 
  [kernel-poll:false] [dtrace]

  Elixir 1.6.0-dev (abdd29d) (compiled with OTP 20)
  ```

* Operating system:
   `macOS High Sierra 10.13.1`

### Current behavior

No space before `,` is valid

```
iex> Code.string_to_quoted("""
...> one(
...>  1,
...>
...>  two: 3
...> )
...> """)
{:ok, {:one, [line: 1], [1, [two: 3]]}}
```

Space before `,`

```
iex> Code.string_to_quoted("""
...> one(
...>  1 ,
...>
...>  two: 3
...> )
...> """)
{:ok, {:one, [line: 1], [1, [two: 3]]}}
```

Newlines before `,`

```
iex> Code.string_to_quoted("""
...> one(
...>  1
...>
...>  ,
...>
...>  two: 3
...> )
...> """)
{:error, {4, "syntax error before: ", "','"}}
```

### Expected behavior

The newline is treated the same as no space or space before `,` and is `:ok`.

```
iex> Code.string_to_quoted("""
...> one(
...>  1
...>
...>  ,
...>
...>  two: 3
...> )
...> """)
{:ok, {:one, [line: 1], [1, [two: 3]]}}
```

**Comment by josevalim** [comment]
Is there any reason to support this style?

My biggest concern is the implications this may have in function calls without parens and, given that nobody would actually encourage this style, I see no reason to support it.

**Comment by josevalim** [comment]
It is worth noting there are other situations where an optional newline is not the same as a whitespace, such as `foo\nbar` and `foo\n+bar`. There are probably others.

**Comment by KronicDeth** [comment]
I just make the pathological test cases.  I didn't mean to imply it was a good idea to write code like that.  I only used the "Expected behavior" because it's in the template.  If you want to close as not supported, I have no problem with that.

**Comment by josevalim** [comment]
Thanks for clarifying Luke! Very appreciated.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by KronicDeth** [comment]
Seems consistent with the rules for `do` also

```
iex(1)> Code.string_to_quoted("""
...(1)> two
...(1)>   do
...(1)> 
...(1)> end
...(1)> """)
{:error, {2, "syntax error before: ", "do"}}
```

while it's fine for parenthesized.  So we could group both under making no parentheses calls less confusing

```
iex(1)> Code.string_to_quoted("""
...(1)> one()
...(1)> 
...(1)>   do
...(1)> end
...(1)> """)
{:ok, {:one, [line: 1], [[do: {:__block__, [], []}]]}}
```

**Comment by josevalim** [comment]
@KronicDeth yeah, we do support it in many places but almost all of them appeared with use cases. We support in operators because of things like pipelines. We support in do end blocks because some people prefer to write this:

```elixir
with \
  foo <- bar
do
  ...
end
```

But unless we have a use case for commas, I would like to avoid it.

Thanks for the report!

**Comment by j-hotlink** [comment]
Although this has been closed and is ultimately a matter of taste, Jose asked for an example where this syntax has any merit so here goes:

style 1 (ok)
<pre>
    changeset = %{ changeset |
                   :firstname => conn.params[ "firstname" ],
                   :lastname  => conn.params[ "lastname" ],
                   :telephone => conn.params[ "telephone" ],
                   :email     => conn.params[ "email" ]
                 }
</pre>

style 2 (syntax error)
<pre>
    changeset = %{ changeset
                   | :firstname => conn.params[ "firstname" ]
                   , :lastname  => conn.params[ "lastname" ]
                   , :telephone => conn.params[ "telephone" ]
                   , :email     => conn.params[ "email" ]
                 }
</pre>

Apart from the aesthetic symmetry of style 2, it allows line items in a map/list to be introduced or removed without thinking about commas. Eg. you can quickly rearrange lines (or delete the line containing ":email") with style 2, but with style 1 you must additionally check and/or fiddle with commas after your edits.

The issue of having to fiddle with commas and dots whilst rearranging code is an existing complaint of Erlang's syntax, and I associate those types of idiosyncrasies with older languages (like Ocaml with it's quirky semi-colon).

I've grown accustomed to the terse elegance of Elm's syntax (style 2) and admit I've become a fan, but I assume there are other considerations making this unideal for Elixir.
