### ISSUE TITLE
Stream.chunk_every/4 gives odd results

### ISSUE THREAD

**Issue by Paddy3118** [elixir-lang/elixir#7096]
I am *very* new to Elixir, and so looking at `chunk_every` when argument `step` is more than `count`.

    Erlang/OTP 20 [erts-9.0] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10]
    
    Interactive Elixir (1.5.2) - press Ctrl+C to exit (type h() ENTER for help)
    iex(17)> Enum.chunk_every('ABCDEFGHIJK', 3, 4, [])
    ['ABC', 'EFG', 'IJK', 'IJK']
    iex(18)> Enum.chunk_every('ABCDEFGHIJKL', 3, 4, [])
    ['ABC', 'EFG', 'IJK']
    iex(19)> 

The output with 'IJK' repeated does not seem of much use?

Thanks.

(Copied from Reddit [here](https://www.reddit.com/r/elixir/comments/7i9ssa/messing_with_chunk_every_gives_odd_results/))

**Comment by albertoalmagro** [comment]
@josevalim may I take care of this one?

**Comment by josevalim** [comment]
@albertoalmagro yes please! If it is not assigned and nobody "claimed" it, you should be good to go!

**Comment by Paddy3118** [comment]
This came about because I was so impressd, I decided to do a version in Python, and noticed the above in my testing.

My blog post is: [Elixirs' chunk_every in Python](http://paddy3118.blogspot.co.uk/2017/12/elixirs-chunkevery-in-python.html).
