### ISSUE TITLE
Regex lookbehind & lookahead issue

### ISSUE THREAD

**Issue by Daniel-Xu** [elixir-lang/elixir#7098]
### Environment
Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.1

### Current behavior

lookahead and lookbehind return wrong results:
```elixir
iex(41)> Regex.scan(~r/(?<=<).*?(?=>)/, "<ei,{{{a<<>},{{<>}},{{{{<{<ei>}")
[["ei,{{{a<<"], [""], [">},{{<"], [""], [">}},{{{{<{<ei"]]
```
### Expected behavior
The expected results should be 

![image](https://user-images.githubusercontent.com/548144/33794171-776efa2e-dc94-11e7-8db1-1ced2f524c50.png)

also, this is the ruby return value: 
```irb
irb(main):001:0>  "<ei,{{{a<<>},{{<>}},{{{{<{<ei>}".scan(/(?<=<).*?(?=>)/)
=> ["ei,{{{a<<", "", "", "{<ei"]

```

**Comment by josevalim** [comment]
Elixir and Ruby use different Regex engines. Although I cannot understand why Elixir returns A and Ruby returns B, I can say the result you are getting is consistent with the PCRE engine used by Elixir: https://regexr.com/3hp9m
