### ISSUE TITLE
Introduce @since module attribute

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7099]
It can be stored alongside the documentation. My suggestion is to support `@since` for now, so we at least have the information in the source code but to store them with the docs would require to redesign the docs chunk, something we are trying to do with the consensus of all other BEAM languages.

**Comment by albertoalmagro** [comment]
Could I try this one @josevalim ? Could you please give me an example of a similar already existing feature?
Thanks!

**Comment by whatyouhide** [comment]
@albertoalmagro you can look at how we store `@doc` for starters.

**Comment by josevalim** [comment]
I assigned this one to me because I am already working on it. :)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by albertoalmagro** [comment]
Thanks @josevalim @whatyouhide this one looked interesting 😉

**Comment by eksperimental** [comment]
I guess this one can be closed
