### ISSUE TITLE
Formatter: Indentation is broken when |> case do

### ISSUE THREAD

**Issue by amrnt** [elixir-lang/elixir#7102]
I'm testing around the formatter and looking at my code. I just found that some indentation is broken in some cases.

An issue is when you have a pipeline to a `case`, the line after `do`, i'm not sure it it needs an extra space or there is an extra space already.

<img width="579" alt="screen shot 2017-12-11 at 13 58 14" src="https://user-images.githubusercontent.com/21756/33832341-1acb482e-de7c-11e7-9d88-23eead2ac304.PNG">

If you have a case inside a case, the inner case clauses indentation is just fine:

<img width="474" alt="screen shot 2017-12-11 at 14 02 28" src="https://user-images.githubusercontent.com/21756/33832321-0172c000-de7c-11e7-81ff-411c8160ac20.PNG">

### Environment

* Elixir & Erlang versions (elixir --version):  

```
Erlang/OTP 20 [erts-9.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.0-dev (840c995) (compiled with OTP 20)
```

* Operating system: MacOS

**Comment by NobbZ** [comment]
The clauses are indented 2 spaces relative to the indentation of the `case`, as aswell the `end` is at the very same indentation as the `case`.

This is one of the things I can live with, even though I had prefered the `|>` as anchor and indenting clauses 4 spaces and having `end` at the same indent as `|>`. To be honest, the `case`s `end` feels much more off than the clauses...

**Comment by josevalim** [comment]
@amrnt it is working by design but we can discuss the options that we have.

1. Indent by the operator

```elixir
Account.create_user(user_params)
|> case do
     {:ok, %User{} = user} ->
       user

     {:error, other} ->
       other
   end
```

2. Indent nothing

```elixir
Account.create_user(user_params)
|> case do
  {:ok, %User{} = user} ->
    user

  {:error, other} ->
    other
end
```

3. Indent only clauses

```elixir
Account.create_user(user_params)
|> case do
    {:ok, %User{} = user} ->
      user

    {:error, other} ->
      other
end
```

I am personally fine with 1 or 2, 3 is by far the worst for me.

**Comment by whatyouhide** [comment]
Agreed, 1 or 2 are fine, 3 is not :smile:

**Comment by michalmuskala** [comment]
The same is happening with anonymous functions. I think before the formatter the most common way was to write:


```elixir
foo
|> Enum.map(&foo/1)
|> Enum.reduce(fn elem, acc ->
  bar(elem, acc)
end)
```

Which corresponds to proposal 2. I find the current indentation pretty weird in this situation.

**Comment by amrnt** [comment]
No for the 3rd option please! 1 and 2 are fine!

IMO,  I would go with the second one since it's cleaner and prettier in a way.

**Comment by NobbZ** [comment]
I'd go for option 2 as well. I also skimmed my code now and realized, that while I explained something similar to 3, I actually use 2 in my code ;) Dunno why I said 4 spaces...

**Comment by josevalim** [comment]
Here is the PR: https://github.com/elixir-lang/elixir/pull/7103

You can see how the changes affect the Elixir codebase in it. Please give your opinion accordingly.
