### ISSUE TITLE
The changelog seems to have an incorrect description of atom and variable names

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#7106]
(I've tried this on 1.6: I assume nothing has changed here since 1.5)

The Changelog says

> Identifiers must still be a sequence of letters, followed by digits and combining marks.

However, I don't think it means this. How about:

> Identifiers must start with a letter or underscore, optionally followed by letters, digits, and underscores. Here _letter_ means any UTF-8 _letter-character_ (optionally with a _combining mark_) and _digit_ means a UTF-8 _decimal-digit-character_. If you're using ASCII, this does what you'd expect.

> Examples of valid variables are:

     name    josé   _age   まつもと  _42  адрес

> Examples of invalid variables include:

     name•   a±2  42

**Comment by josevalim** [comment]
Thanks @pragdave!

We did the mistake of being too terse (and plain wrong) in the CHANGELOG. I have ported your fixes to the v1.5 branch.

A slightly more formal specification can be found here: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Unicode%20Syntax.md
