### ISSUE TITLE
Usage of `defprotocol` sometimes causes dialyzer warning

### ISSUE THREAD

**Issue by christhekeele** [elixir-lang/elixir#7107]
### Environment

* Elixir & Erlang versions (`elixir --version`): 

  ```
  Erlang/OTP 20 [erts-9.1.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] 
  [kernel-poll:false] [dtrace]
  
  Elixir 1.5.2
  ```

* Operating system: OSX (`sw_vers`):

  ```
  ProductName:	Mac OS X
  ProductVersion:	10.13.1
  BuildVersion:	17B1003
  ```
### Current behavior

Any usage of the `defprotocol` macro in a project dependency causes dialyzer to complain:

`Guard test 'or'('false','false') can never succeed`

### Expected behavior

It would be nice if this did not occur, as every project containing dependencies with protocols must then mark these warnings as allowed to get clean dialyzer runs. It's one thing for the language to not get a clean dialyzer run itself but it is a bit of a hassle if it causes projects' dialyzer runs to fail indirectly because of how the `defprotocol` macro is implemented.

Dialyzer can't provide very useful backtracing into the cause of this since it is a macro. Since this is a low-priority, nice-to-have, hard-to-implement issue I'm fine if this is just closed out but I thought it'd be nice to have it reported somewhere and I couldn't see any such a report anywhere already.

If closed off I will approach maintainers of Elixir dialyzer tasks and see if this can instead be included in a set of default ignores.

**Comment by christhekeele** [comment]
Confirmed that the exact same warning is emitted in prod mode, so this is not a consolidation thing.

**Comment by fishcakez** [comment]
@christhekeele please provide an example because our own protocol dialyzer test does not warn. If I add protocol consolidation to the test I get different warnings:
```
protocol_opaque.ex:8: Function any_impl_for/0 will never be called
protocol_opaque.ex:8: Function 'impl_for?'/1 will never be called
```
Note we consolidate by default since 1.4 when using mix.

**Comment by christhekeele** [comment]
I've created a clean mix project reproducing this issue in my orphaned branch [here](https://github.com/christhekeele/elixir/tree/defprotocol_dialyzer_warn). Running `mix dialyzer` produces the dialyzer errors documented in the [`dialyzer.output`](https://github.com/christhekeele/elixir/blob/defprotocol_dialyzer_warn/dialyzer.output) file.

**Comment by christhekeele** [comment]
@fishcakez I've included richer erlang and OS version info in my description.

**Comment by christhekeele** [comment]
I'm using the newer [`dialyzex`](https://github.com/Comcast/dialyzex) package in my example, but this does not affect the outcome versus [`dialyxir`](https://github.com/jeremyjh/dialyxir).

**Comment by christhekeele** [comment]
I've created a [build matrix](https://travis-ci.org/christhekeele/elixir/builds/315749168) to diagnose the versions of Elixir and OTP where this occurs. (Takes quite some time to run, no conclusions to draw yet.)

**Comment by fishcakez** [comment]
@christhekeele don't worry the issue is trivial, fallback to any with consolidation creates guard clause that can never match. In future please try to give more minimal examples or at least full warnings. You reported that it was all protocols and consolidation didn't matter, which made this confusing to understand.

**Comment by christhekeele** [comment]
Yeah, I didn't have time to dig into it until tonight; but I knew when I noticed and silenced the warning yesterday that I'd never get around to reporting it if I didn't then.

In the future I'll avoid speculating on the probable cause if I haven't had time to do more investigation, though! 😄 👍

**Comment by christhekeele** [comment]
Unless you are on the heels of a fix yourself, I'm confident that armed with your synopsis I can submit a patch for this. Feel free to assign to me if you are not working on this, and thanks for your help!

**Comment by josevalim** [comment]
@christhekeele please do send a PR!

**Comment by josevalim** [comment]
I will go ahead with this since we are working towards a release candidate for v1.6.
