### ISSUE TITLE
Syntax error on comma placement

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#7109]
### Environment

* Elixir 1.5.2
* Erlang/OTP 20 [erts-9.1.5] [64-bit] 
* macOS Sierra 10.12.6

### Current behavior

Elixir 1.5.2 is giving syntactic error on the first comma:

```
{ :reply
 , new_server # this is line 15
 , Map.put(todo_servers, todo_list_name, new_server) }
```
** (SyntaxError) lib/todo/cache.ex:15: syntax error before: ','
    (elixir) lib/code.ex:334: Code.load_file/2
    (iex) lib/iex/helpers.ex:421: IEx.Helpers.do_r/1
    (iex) lib/iex/helpers.ex:401: IEx.Helpers.r/1
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (iex) lib/iex/evaluator.ex:231: IEx.Evaluator.handle_eval/5

but no error if the code is in one line 

```
{ :reply, new_server, Map.put(todo_servers, todo_list_name, new_server) }
```
or the commas are placed at the end of the lines

```
{ :reply, 
 new_server, 
 Map.put(todo_servers, todo_list_name, new_server) }
```

### Expected behavior

The place of the commas should be free as in most (if not all) mainstream languages.
According to this, the last two code snippets should be accepted by the compiler.

**Comment by josevalim** [comment]
Thanks for the report.

This is working as intended. Please see #7093 for a similar discussion.
