### ISSUE TITLE
error when creating a tuple with elixir 1.5.2

### ISSUE THREAD

**Issue by romenigld** [elixir-lang/elixir#7120]
### Environment

Elixir 1.5.2, erlang 20.2
```
elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.2
erl -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
```
* Operating system: 
MacOS x High Sierra 10.13.2
### Current behavior
I'm reading a book and for create this tuple I get this error:
```
> a_tuple = {a,b,c}
** (CompileError) iex:29: undefined function a/0
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
```

**Comment by OvermindDL1** [comment]
Do you mean:

```elixir
a_tuple = {:a,:b,:c}
```

?

**Comment by antonioj-mattos** [comment]
It might be because the code sample in the book is incomplete, and the variables a, b and c are not defined.

And, as OvermindDL1 pointed out, you can use it with atoms or strings as in

```elixir
a_tuple = {'a', 'b', 'c'}
```

**Comment by romenigld** [comment]
yes it's true, it was an error of the book. 
Thank you guys!
