### ISSUE TITLE
Code formatter: compilation error after commented out one line of typespec

### ISSUE THREAD

**Issue by amatalai** [elixir-lang/elixir#7130]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.6.0-dev (05dba8e9e) (compiled with OTP 20)
* Operating system: macOS 10.13.2 - High Sierra

### Current behavior

When we have multiline typespec like this:

```elixir
defmodule Foo do
  @spec bar ::
          :ok
          | :invalid
          | :unknown
          | :other
  def bar do
    Enum.random([:ok, :invalid, :unknown, :other])
  end
end
```
comment out one line and run formatter, we get this:
```elixir
  @spec # | :unknown
        bar ::
          :ok
          | :invalid
          | :other
```
after one additional formatter run:
```elixir
  # | :unknown
  @spec
  bar ::
    :ok
    | :invalid
    | :other
```
both versions cause `** (CompileError) lib/foo.ex:4: undefined function ::/2`

### Expected behavior

Return 
```elixir
  # | :unknown
  @spec bar ::
          :ok
          | :invalid
          | :other
```
in single formatter run

**Comment by josevalim** [comment]
This code is already invalid:

```elixir
  @spec # | :unknown
        bar ::
          :ok
          | :invalid
          | :other
```

The formatter cannot get invalid code and make it valid, that's why it errors.

**Comment by amatalai** [comment]
@josevalim I missed example for one step because my editor is running formatter on save.
This is how it looks after commenting out but before running formatter
```elixir
  @spec bar ::
          :ok
          | :invalid
          #| :unknown
          | :other
```
It compiles properly before formatting

**Comment by josevalim** [comment]
@amatalai ah, that's definitely a bug. Good catch.
