### ISSUE TITLE
Build error in node_test.exs for master branch on Ubuntu 16.04

### ISSUE THREAD

**Issue by malcolmwhat** [elixir-lang/elixir#7131]
### Precheck

* [x] For bugs, do a quick search and make sure the bug has not yet been reported

### Environment

* Elixir & Erlang versions (elixir --version): Trying to install elixir 16.0-dev, currently have erlang/OTP release 19.2, since this was highlighted in #5670 to be a correct version of erlang to be using. I installed erlang through the [erlang solutions downloads page](https://www.erlang-solutions.com/resources/download.html).
* Operating system: Ubuntu 16.04LTS

### Current behavior
Cloned the git repo, and followed the instructions by issuing
```bash
make clean test
```

The result is (where `[...]` denotes a bunch of what I deem irrelevant console output):
```
[...]
==> elixir (exunit)
[...]
21:26:15.839 [error] Too short cookie string


  1) test start/3 and stop/0 (NodeTest)
     test/elixir/node_test.exs:8
     match (=) failed
     code:  assert {:ok, _} = Node.start(:hello, :shortnames, 15000)
     right: {:error,
             {{:shutdown,
               {:failed_to_start_child, :auth,
                {'Too short cookie string',
                 [
                   {:auth, :init_cookie, 0, [file: 'auth.erl', line: 286]},
                   {:auth, :init, 1, [file: 'auth.erl', line: 140]},
                   {:gen_server, :init_it, 6,
                    [file: 'gen_server.erl', line: 328]},
                   {:proc_lib, :init_p_do_apply, 3,
                    [file: 'proc_lib.erl', line: 247]}
                 ]}}},
              {:child, :undefined, :net_sup_dynamic,
               {:erl_distribution, :start_link,
                [[:hello, :shortnames, 15000], false]}, :permanent, 1000,
               :supervisor, [:erl_distribution]}}}
     stacktrace:
       test/elixir/node_test.exs:10: (test)

[...]

Finished in 30.3 seconds (15.6s on load, 14.7s on tests)
1367 doctests, 2847 tests, 1 failure

Randomized with seed 924447
Makefile:214: recipe for target 'test_stdlib' failed
make: *** [test_stdlib] Error 1
```

**Comment by josevalim** [comment]
Thank you. Apparently there is an existing ~/.erlang.cookie file that is either too old or created by hand. We could try to erase it but on the other hand I don't think we should touch the user's home directory. Please erase the mentioned file and you should be good to go. Thanks for reporting!

**Comment by malcolmwhat** [comment]
Thanks for the response, deleting the `~/.erlang.cookie` file (which was empty, not sure where it came from) did the trick and the tests all passed.
