### ISSUE TITLE
Add compatibility info for v1.7

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#7142]
To avoid https://github.com/elixir-lang/elixir/issues/7137

**Comment by josevalim** [comment]
We will do so when we release, especially since the RELEASES.md page says so now.

**Comment by eksperimental** [comment]
My question is, how can users trying master know what is the highest OTP version that Elixir is guaranteed to work on. Actually, now that I'm thinking this information should be in the README file, as it will be really annoying to install the latest OTP version to find out it is not supported
