### ISSUE TITLE
v1.6 CHANGELOG improve entry for @deprecated and @since attributes

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#7145]
The current entry reads
>> This release also introduces two new attributes associated to function definitions: @deprecated and @since. The former says if a function or macro is deprecated, the latter says the version said API was added:

1. "says" sounds untechinical. "Annotates reads better IMO.
2. "the latter says the version said API was added" is grammatically wrong, maybe something like "the latter annotates the version the API was introduced"
3. In the release info of v1.6-rc0 https://github.com/elixir-lang/elixir/releases/tag/v1.6.0-rc.0 there's a weird casing in subheading "@deprecated and @SInCE attributes"

**Comment by eksperimental** [comment]
Oh..regarding no.3 `@since` is a GitHub user thats why it is stylised like that. You may want to use backticks to avoid that

**Comment by josevalim** [comment]
Thanks @eksperimental! I have applied all fixes from the issues you opened! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
Great! One more thing you could update the release info with the latest CHANGELOG
