### ISSUE TITLE
Greek final sigma

### ISSUE THREAD

**Issue by vjorjo** [elixir-lang/elixir#7149]
### Environment

* Elixir & Erlang versions (elixir --version): 
Erlang/OTP 20 [erts-9.2] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10]
Elixir 1.6.0-rc.0 (182c730bd) (compiled with OTP 19)

* Operating system: 
windows 7 x64

### Current behavior

String.downcase for Greek letter 'Σ' now always returns the final sigma 'ς', which is completely wrong.
Until version 1.5.2, it always returned 'σ' which is preferable.

However String.Casing.downcase works quite better. Here are some results of this one (acc="", mode=:greek):
"Σ" -> "ς": wrong, correct is "σ"
"ΣΣ" -> "σς": CORRECT
"Σ ΣΑΣ" -> "ς σας": wrong, correct is "σ σας"

I checked a little the code in  elixir/lib/elixir/unicode/properties.ex and I realized that the function doesn't take into account the letters before the sigma.
I copied the downcase function in a module and tried to fix it. I concluded to this code that I think works correctly (In mine I didn't have "unquote"s but I tried to put them back):
``` elixir
  def downcase(<<unquote(sigma), rest::bits>>, acc, mode) do
    downcased = case mode == :greek and starts_with_letter?(acc) do
      true ->
        case starts_with_letter?(rest) do
          true -> 0x03C3  # sigma_lower
          false -> 0x03C2  # sigma_final
        end
      false -> 0x03C3  # sigma_lower
    end

    downcase(rest, <<downcased::utf8, acc::binary>>, mode)  # reversed
  end


  for {codepoint, _upper, lower, _title} <- codes,
      lower && lower != codepoint,
      codepoint not in @conditional_downcase do
    def downcase(<<unquote(codepoint), rest::bits>>, acc, mode) do
      downcase(rest, unquote(lower) <> acc, mode)  # reversed
    end
  end

  def downcase(<<char, rest::bits>>, acc, mode) do
    downcase(rest, <<char, acc::binary>>, mode)  # reversed
  end

  def downcase("", acc, _mode), do: String.reverse(acc)
```
I save the codepoints in acc in reverse order because when "Σ" is encountered we need to check if there was a letter just before it and since there is "starts_with_letter?/1" function, I used this to actually check the previous codepoint if any.
In order to avoid reversion a function "ends_with_letter?/1" or something similar has to be written.
Or in addition to acc, the previous codepoint could be passed as an argument.

**Comment by michalmuskala** [comment]
The Unicode 10 standard defines the behaviour for final sigma in section 3.13 in table 3-14:

> C is preceded by a sequence consisting of a cased letter and then zero or more case-ignorable characters, and C is not followed by a sequence consisting of zero or more case-ignorable characters and then a cased letter.

There's also a helpful (or not) regex provided:
* Before C: `\p{cased} (\p{case-ignorable})*`
* After C: `! ( (\p{case-ignorable})* \p{cased} )`

I have no idea, how to implement those conditions efficiently.

**Comment by vjorjo** [comment]
@josevalim 
@michalmuskala 

could you please add in String.Casing module these changes and additions (or something like these) so that handling of Greek final sigma become fully on par with the unicode specifications (the one that michalmuskala mentioned: "The Unicode 10 standard defines the behaviour for final sigma in section 3.13 in table 3-14")?
It will add 2000+ case_ignorable? casing functions. I'm not sure if this is a big problem.

```
  # BEGIN ADDED By George
  # ====================================
  derived_path = Path.join(__DIR__, "DerivedCoreProperties.txt")
  regex = ~r/(?:^([0-9A-F]+)(?:\.\.([0-9A-F]+))?)\s+;\s(Case_Ignorable)/m

  derived =
    Enum.reduce(File.stream!(derived_path), %{}, fn line, acc ->
      case Regex.run(regex, line, capture: :all_but_first) do
      [first, "", class = "Case_Ignorable"] ->
        codepoint = String.to_integer(first, 16)
        Map.update(acc, class, [codepoint], &[String.to_integer(first, 16) | &1])

      [first, last, class = "Case_Ignorable"] ->
        range = String.to_integer(first, 16)..String.to_integer(last, 16)
        codepoints = Enum.map(range, &(&1))
        Map.update(acc, class, codepoints, &(codepoints ++ &1))

      nil ->
        acc
      end
    end)

  for cp <- derived["Case_Ignorable"] do
    defp case_ignorable?(unquote(cp)), do: true
  end
  defp case_ignorable?(_), do: false

  # ====================================
  # END ADDED by George


  # BEGIN change by George
  # ----------------------------------------------
  defp cased_letter_binary?(<<codepoint::utf8, rest::bits>>) do
    if case_ignorable?(codepoint) do
      cased_letter_binary?(rest)
    else
      cased_letter?(codepoint)
    end
  end
  defp cased_letter_binary?(_), do: false

  defp cased_letter_list?([<<codepoint::utf8>>| rest]) do
    if case_ignorable?(codepoint) do
      cased_letter_list?(rest)
    else
      cased_letter?(codepoint)
    end
  end
  defp cased_letter_list?(_), do: false

  # ====================================
  # END change by George
```
DerivedCoreProperties.txt is another unicode text file that lists case_ignorable codepoints.

Thanks

**Comment by josevalim** [comment]
We definitely should. Can you please provide practical examples though so
we can complement the suite?

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by vjorjo** [comment]
One example it comes to my mind is when some words are abbreviated with an apostrophe.
e.g.
"ΜΕΣΑ ΑΠΟ" is typically abbreviated to "ΜΕΣ'ΑΠΟ". (it means "through")
In this case the correct lower casing is "μεσ'απο"
or "ΑΣΕ ΤΟΥΣ" is abbreviated to "ΑΣ'ΤΟΥΣ". It means "let them" and is lowcased to "ασ'τους"

assert String.downcase("ΜΕΣ'ΑΠΟ", :greek) == "μεσ'απο"
assert String.downcase("ΑΣΕ ΤΟΥΣ", :greek) == "ασ'τους"

One last question. Why do we have to specify :greek atom in order to have proper handling of greek final sigma and not make this a default rule since from what I have read I understand that this is dependent in context only.
Quote from SpecialCasing.txt for Greek  final sigma:
> Language-Insensitive Mappings"
> These are characters whose full case mappings do not depend on language, but do
> depend on context (which characters come before or after). For more information
> see the header of this file and the Unicode Standard.

**Comment by michalmuskala** [comment]
@josevalim I don't think the implementation in https://github.com/elixir-lang/elixir/commit/44a8f665b1f224de5d6134e8e39658a57028c7a5 is correct - it uses the accumulator that is already converted for checking the previous codepoints, but I think the algorithm requires using the original string.

I'm not sure, though, if it actually matters - common sense tells that a cased character should convert to a cased character after downcasing, but common sense often doesn't apply to unicode.

**Comment by josevalim** [comment]
> I'm not sure, though, if it actually matters - common sense tells that a cased character should convert to a cased character after downcasing, but common sense often doesn't apply to unicode.

Good catch. I will validate this hypothesis.

> One last question. Why do we have to specify :greek atom in order to have proper handling of greek final sigma and not make this a default rule since from what I have read I understand that this is dependent in context only.

It is the sanest approach for now. Once we figure out all details and we are sure we have a fast implementation, we may be able to streamline it into the main one.

**Comment by josevalim** [comment]
Hypothesis validated and case ignorable characters added. Thank you for you help @vjorjo, it was essential in helping us move this forward and in guaranteeing the final implementation is correct.

**Comment by vjorjo** [comment]
You are welcome and in my turn I'd like to help you both @josevalim and @michalmuskala for your responsiveness and materializing correct Greek final sigma handling.
