### ISSUE TITLE
Unexpected dialyzer warnings for child_spec/1

### ISSUE THREAD

**Issue by nifoc** [elixir-lang/elixir#7151]
### Environment

* Elixir & Erlang versions (elixir --version):

```
$ elixir --version
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.0-rc.0 (182c730bd) (compiled with OTP 20)
```
* Operating system:

```
$ uname -a
Darwin FooBar.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

(macOS High Sierra 10.13.2)

### Current behavior

Modules with `child_spec/1` functions that look like this generate unexpected `dialyzer`-warnings:

```elixir
@spec child_spec(term) :: Supervisor.child_spec()
def child_spec(_arg) do
  %{
    id: __MODULE__,
    start: {__MODULE__, :start_link, []},
    restart: :permanent,
    shutdown: :infinity,
    type: :supervisor
  }
end
```

The `dialyzer` output looks like this:

```
lib/foo/pool_supervisor.ex:10: Invalid type specification for function 'Elixir.Foo.PoolSupervisor':child_spec/1. The success typing is (_) -> #{'id':='Elixir.Foo.PoolSupervisor', 'restart':='permanent', 'shutdown':='infinity', 'start':={'Elixir.Foo.PoolSupervisor','start_link',[]}, 'type':='supervisor'}
```

Since the value for the `Supervisor.child_spec()` type changed in 1.6, I tried the "old" (1.5) value:

```elixir
@spec child_spec(term) :: :supervisor.child_spec()
```

That type worked as expected and no warning was emitted.

I've used `dialyxir` 0.5.1 with the following configuration in my tests:

```elixir
      dialyzer: [
        flags: [:unmatched_returns, :error_handling, :race_conditions, :underspecs],
        ignore_warnings: "dialyzer.ignore-warnings"
      ]
```

### Expected behavior

`dialyzer` should not emit any warnings.

**Comment by nifoc** [comment]
I have created a [small example repository](https://github.com/nifoc/child_spec_example) to easily reproduce the issue.

**Comment by CrowdHailer** [comment]
Hi I have just run into the same issue. It looks like it also occurs when the default child_spec is used. I have a module not implementing child_spec and dialyzer references a line in `gen_server` for the error.

```
lib/gen_server.ex:581: The call 'Elixir.Supervisor':child_spec(_@2::#{'id':='Elixir.Ace.HTTP.Service', 'start':={'Elixir.Ace.HTTP.Service','start_link',[any(),...]}},[]) breaks the contract (child_spec() | {module(),arg::term()} | module(),elixir:keyword()) -> child_spec()
```

I'm looking through the Elixir source and cannot see why that call would break the child specification.
For the moment is there any way to silence this warning?

**Comment by fishcakez** [comment]
The issue is the child_spec type declaration has function() but it should
be atom() for the type of the second element in start. The function name is
an atom and not a fun.
