### ISSUE TITLE
Unused Variables Misreporting v1.6.0

### ISSUE THREAD

**Issue by HangingClowns** [elixir-lang/elixir#7158]
Elixir/Erlang versions:

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.0-rc.0 (182c730bd) (compiled with OTP 20)

when I use assert_reply or assert_broadcasted in phoenx 1.3 I get unused variable warnings.

**Comment by josevalim** [comment]
Could you please do a complete bug report? Please include code samples or, even better, an application that reproduces the error. FWIW, Phoenix test suite passes without warnings here, and it uses both assert_reply and assert_broadcasted.

**Comment by HangingClowns** [comment]
Apologizes. If you just create a blank project in phoenix then use the generator to generate a new channel ( I used room, like the examples):

``` elixir
  test "shout broadcasts to room:lobby", %{socket: socket} do
    payload = %{"hello" => "all"}
    push socket, "shout", payload
    assert_broadcast "shout", payload
  end
```

```
warning: variable "payload" is unused
  test/test_app_web/channels/room_channel_test.exs:22
```

**Comment by josevalim** [comment]
I am almost sure that `assert_broadcast` is expecting a pattern, so you are receiving a message, assigning it to the variable `payload` and never using it. This should fix it:

    assert_broadcast "shout", ^payload

The warning actually caught a bug. :)

**Comment by HangingClowns** [comment]
Oops:

```
NOTE: Because event and payload are patterns, they will be matched. This means that if you wish to assert that the received payload is equivalent to an existing variable, you need to pin the variable in the assertion expression.
```
I should have read farther down on another method. Thanks!
