### ISSUE TITLE
Passthrough timestamps in logging

### ISSUE THREAD

**Issue by isaacsanders** [elixir-lang/elixir#7175]
### Environment

* Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.5.2
```

* Operating system: OS X 10.11

### Current behavior

The `Logger` module currently does not allow me to provide my own timestamp for my log entries, which is almost certainly an acceptable behavior in most cases.

### Expected behavior

I am working on a library that integrates with a lower level C library that has the capability of installing a "logging callback". A proper implementation of this would take the log messages and the timestamps provided by the library and would have Elixir log them without changing them. This isn't possible without the ability to pass the timestamp through to the Logger.

I would expect the Logger module to allow me to provide my own timestamp for my log entries.

**Comment by fishcakez** [comment]
Using a module and function name Logger formatter you can do this already:
https://github.com/elixir-lang/elixir/blob/0baa5b1ca446876a1e2801e229669706ef182dcf/lib/logger/lib/logger/formatter.ex#L127-L129

**Comment by josevalim** [comment]
Yup, a custom formatter sounds like the way to go here. You can pass the timestamp in the metadata and choose accordingly which one to use. :+1:

**Comment by isaacsanders** [comment]
how would I implement this on the library level that won't be clobbered on the application level?

**Comment by fishcakez** [comment]
@isaacsanders the formatter should be configurable in the Logger backend. At the library level you can add metadata to the log such as `override_timestamp: x` and then in your custom formatter check for the presence of this key in the metadata, and if it is present override the timestamp.

I am unsure how well this work with your existing formatting or backend. If it is a custom backend then you would need to add the feature there too.

**Comment by isaacsanders** [comment]
This isn't a library for the a backend or a format. These are new log lines. I need a way to get the log lines into the logger, with the appropriate information.

**Comment by isaacsanders** [comment]
If I configure library one way, won't the log lines it generates be subject to the configuration of the logger configuration from the host application?

**Comment by fishcakez** [comment]
> If I configure library one way, won't the log lines it generates be subject to the configuration of the logger configuration from the host application?

The host project/release
