### ISSUE TITLE
Dialyzer - False warning with abs - Guard test 0 | 1 | 2 | 3 >= 8 can never succeed

### ISSUE THREAD

**Issue by dylan-chong** [elixir-lang/elixir#7179]
### Environment

* Elixir & Erlang versions (elixir --version): 

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.3

Using dialyxir 0.5.1

* Operating system: Mac 10.13.2

### Current behavior

```
defmodule TestMod do
  def call do
    accept(9)
    accept(-3)
  end
  defp accept(number) when abs(number) >= 8 do # Guard test 0 | 1 | 2 | 3 >= 8 can never succeed
    :first
  end
  defp accept(number), do: :second
end
```

### Expected behavior

No warning should be shown

**Comment by josevalim** [comment]
Can you please provide a sample application that reproduces this? I have tried it locally and I could not reproduce it. Thanks.

**Comment by dylan-chong** [comment]
here you go:

```
git clone https://github.com/dylan-chong/elixir_environment_error_test.git
cd elixir_environment_error_test
git checkout dialyzer-abs-test
```

**Comment by josevalim** [comment]
I cannot reproduce this on Elixir v1.5.3 and v1.6.0-rc although with Erlang 20.0 (erts 9.0). Can you please try earlier Erlang versions and let us know if the problem exists? If you can't reproduce it on earlier Erlang versions, then it is definitely an Erlang issue.

**Comment by josevalim** [comment]
I just realized that the project you shared doesn't have the code you reported.

**Comment by josevalim** [comment]
I was able to reproduce it in this simple Erlang file, so it is an Erlang bug:

```erlang
-module(test_mod).
-export([call/0]).

call() ->
  accept(9),
  accept(-3).

accept(Number) when abs(Number) >= 8 -> first;
accept(Number) -> second.
```

Could you please report it to bugs.erlang.org? Thank you.
