### ISSUE TITLE
Bug: import_dependency not working

### ISSUE THREAD

**Issue by mumughal** [elixir-lang/elixir#7180]
### Environment

* Elixir & Erlang versions (Elixir 1.6.0): 
* Operating system: MacOS 10.12.6 

### Current behavior

When I try to import formatter from dependency, it doesn't seem to work. I have tried with `espec` formatter and a clean project.
I have created this new repository to test with clean project, still it doesn't seem to work.
 
### Expected behavior
Formatter should be able to import rules from the dependency and apply the rules on the files. 

Please look into this code:
[test-repository](https://github.com/mumughal/test-elixir-formatter)

**Comment by josevalim** [comment]
Thanks for the report with a mechanism to reproduce the issue. :heart: I am looking into this now.

**Comment by josevalim** [comment]
@mumughal I was able to format it just fine. Here is the file I got after formatting:

```elixir
defmodule TestFormatSpec do
  @moduledoc "Tests for controller"
  use ESpec.Phoenix, async: false

  let conn: build_conn()
  let response: subject()

  let body: response().resp_body
  let json: Poison.decode!(body())
  let status: response().status

  describe "/index" do
    subject do: get(conn(), "/index")

    it "should return status code 200" do
      expect(status() |> to(eq 200))
    end
  end
end
```

Note parens were not added to `it`, `subject`, `let` and friends.

What were you expecting to happen?

**Comment by mumughal** [comment]
I was working with Elixir 1.6.0-dev. I just upgraded to version 1.7.0-dev and now it works! :)

Thank you so much for looking into it.

**Comment by josevalim** [comment]
Glad to hear!
