### ISSUE TITLE
v1.6.0-rc.0 new documentation groups for Modules do not add any clarity

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#7184]
I don't believe the new documentation groups for Modules add clarity
and can be rather confusing.

For example when I saw IO&System I immediately thought it would have
the date & time functions: Finding the time is *the* system feature I
use most in every language I've ever used. But of course DateTime gets
the time and formats it as well. So maybe DateTime should live in
IO&System and Data&Behaviours?

Also OptionParser lives in IO&System. Well yes the data comes from the
system but its surely a Data transformation package?

Also, one of the most important feature of any languages are its
collections. So why not group called Collections with Enum, Stream,
Enumerable and Collectable in it?

The point I'm highlighting, as I'm sure your see, is that any grouping
is essentially a personal view and may be confusing to other.

I note Erlang still, and just, uses an alphabetic list.  I would
commend alphabetic as the best, future-proof solution for Elixir.

**Comment by josevalim** [comment]
We completely understand this change may be an improvement to some and a regression for others. We will only know the net outcome once enough users try it out and give their opinion, so we really appreciate you are doing so.

I also agree that groups are a personal view and there are multiple interpretations. Our hope, however, is that the grouping will help newcomers, who need to make sense of what the Elixir standard library provides and an alphabetical ordering is of absolutely no help here. From this perspective, an eagle view is more important than being accurate according to everyone's interpretation (which is most likely be impossible).

Therefore a discussion on how to improve the groups is definitely welcome. For example, I like the suggestion of having a separate group for collections. You would include Keyword, Map, and MapSet and in there as well?

On the other hand, if the ordering makes it harder to navigate, we need to consider improvements. For example, we could provide search by modules (similar to pressing t on GitHub to find files) or have an option that removes the group and keeps the alphabetical ordering.

If you would like to gather more feedback on the usefulness of groups as a whole,  then it is probably best to start a wider discussion on the topic, maybe by starting a thread in the mailing list and/or Elixir Forum.

**Comment by josevalim** [comment]
To move the discussion forward I have opened #7185.

**Comment by josevalim** [comment]
Closing in favor of the PR. Feel free to open more discussions about specific changes on the grouping functionality. The plan for now is to keep it around! Thanks!
