### ISSUE TITLE
Formatter bug on 1.6.0-rc0

### ISSUE THREAD

**Issue by MSch** [elixir-lang/elixir#7188]
Was trying to test if formatting our code base with the formatter from 1.6.0-rc0 works.

Before:

```elixir
Enum.each(& :ok = A.b(nil, {:c, &1}))
```

After:

```elixir
Enum.each((&:ok) = A.b(nil, {:c, &1}))
```

Needless to say, this doesn't compile any more.

**Comment by josevalim** [comment]
@MSch both before and after do not compile here locally:

```iex
iex(2)> Enum.each(& :ok = A.b(nil, {:c, &1}))
** (CompileError) iex:2: unhandled &1 outside of a capture
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

and

```iex
iex(2)> Enum.each((&:ok) = A.b(nil, {:c, &1}))
** (CompileError) iex:2: unhandled &1 outside of a capture
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

what am I missing? :)

**Comment by MSch** [comment]
Ah, just checked: It compiles (for me) on 1.5.2-otp-20 but not on 1.6.

**Comment by josevalim** [comment]
@MSch hrm. I think there was a bug fix on this area because of the precedence of `|`. I will investigate.

**Comment by MSch** [comment]
@josevalim ❤️
