### ISSUE TITLE
Possible mix dependency bug

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#7194]
Application A has a dependency `{:b, github: "pragdave/b}`.

Application B has a dependency `{:c, github: "pragdave/c}`.

Run `mix deps.get` in A, and you correctly receive B and C.

Now change B to have a different dependency: `{:x, github: "pragdave/x}`.

Run `mix deps.update B` in A, and you receive a new B, but you do not receive X. 

If you then do `mix deps.get`, it fetches X.

I would have expected that `mix deps.update` would fetch an updated app, and then fetch it's dependencies. In particular, if the dependency change was to a different version of the same app, then an update would fetch that, and it would appear to compile OK, but it would be using the old not the new version.

**Comment by josevalim** [comment]
Dave, was this using the RC?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by pragdave** [comment]
Yes
