### ISSUE TITLE
Alias definition interferes with module definition

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#7196]
### Environment

* Elixir 1.5.3
* Erlang/OTP 20 [erts-9.2]  
* macOS 10.12.6

### Current behavior

When defining a module using an alias, like

```
defmodule A do
end
```
the file `Elixir.A.beam` is generated as typically expected (and documented everywhere).

However, if the definition of module `A` is preceded by an `alias` defining alias `A`, i.e., the same alias as the module alias, like in

```
alias Something.A

defmodule A do
end
```

then what is generated is the file `Elixir.Something.A.beam` without a warning to the developer.

### Expected behavior

The `alias` definition should not interfere with the module definition, so that both cases above should generate the same file `Elixir.A.beam`.

If this "feature" interference is not considered a bug, it would be nice to know a strong use case for it.

Also, if it is not a bug, then at the minimum a compiler warning should be produced.

Thank you.

**Comment by josevalim** [comment]
The use case is this one:

```elixir
defmodule Foo do
  defmodule Bar do

  end

  defmodule Bar.Baz do

  end
end
```

The reason why Bar inside Foo works is because it defines an alias behind the scenes. You can always get rid of the alias by using the `Elixir.` prefix.

**Comment by mguimas** [comment]
If I understand the case you present, Elixir is generating the alias Foo.Bar behind the scene. But it should be possible to distinguish your case and the one that I presented, and give a warning at least in the latter case. Can you consider this suggestion? Thank you.

**Comment by josevalim** [comment]
The behaviour you described may be used intentionally too: https://github.com/elixir-lang/gen_stage/blob/cd59e0c17a04eb2a1951a1e979656b1d31375603/lib/gen_stage.ex#L1-L5

**Comment by mguimas** [comment]
That is an interesting use case: a module is developed and tagged as experimental, but used as if it was "official". Then, after the experimental phase, the `Experimental` tag is removed without affecting the client code. Still, while in this case it was intentional, I believe a warning would be useful to avoid unintentional use, like when someone uses another person's macro which generates an alias that will interfere with the first person's code, which is my case ...

**Comment by josevalim** [comment]
You should have stated with your case then :) since we do track aliases generated by macros and it probably makes more sense to warn on such cases.

The issue here with a warning is that people on valid use cases have no way to opt out of it.

Can you please provide a code snippet that reproduces the case you were seeing?

**Comment by josevalim** [comment]
Actually, I will take a step back. Unless the macro you are using wants to introduce an alias in your code, which then the behaviour you are seeing is intentional, they should move the alias outside of the quoted expressions.

For example, instead of:

```elixir
quote do
  alias Foo.Bar
  Bar.baz()
end
```

they should do:

```elixir
alias Foo.Bar

quote do
  Bar.baz()
end
```

Otherwise they are indeed aliasing your code and you should see the results of such alias. :)

**Comment by mguimas** [comment]
> You should have stated your case then :) since we do track aliases generated by macros and it probably makes more sense to warn on such cases.

Perhaps I should have made my case explicit in the beginning, my fault. But it is nice to know you are tracking macro generated aliases, so the change perhaps does not require much effort.

> Unless the macro you are using wants to introduce an alias in your code

Yes, the macro introduces an alias in the user's code. The case is:

1. The user calls the macro
1. The macro introduces an alias, e.g., `alias Something.X` in the user's code without the user being aware of
1. Then after calling the macro the user's code does `defmodule X do ... end`
1. The user is expecting to have a file `Elixir.X.beam`, but instead gets a file `Elixir.Something.X.beam`
1. The user should get a message `warning: alias X already defined at line <n>` where `<n>` is the line where the macro was called.

This is one case of possible interference between a macro's injected `alias` and user code. Another example if for the macro to inject `alias Something.X` and then the user code to do `alias AnotherThing.X`, which should give an equivalent warning.

> The issue here with a warning is that people on valid use cases have no way to opt out of it.

The solution is to distinguish valid use cases, like the nested module use case you gave before. An hypothesis is to detect that `defmodule Bar ...` is happening inside `defmodule Foo ...` and give no warning in this case. Perhaps when `defmodule Bar ...` is expanded inside `defmodule Foo ...` there is some "information context" where the module nesting can be detected, which would indicate a valid use case. 

Thank you.
