### ISSUE TITLE
Macro.to_string does not rewrite guards, so output is inconsistent with exception blaming

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#7209]
I'm not sure if this is actually a bug, since `Macro.to_string` output is valid, just inconsistent with another module's output, the exception blaming.

I can make the argument that it should be left as-is because it shows literally what is in the AST.  

Arguing the other side, it can be confusing for new user as they have to know that internally, Elixir guards are translated to these `:erlang` guard functions and they have to translate back or do a `Macro.prewalk` in their own code and duplicate the `rewrite_guard` functionality from `Exception` blaming.  There also is other code in `Macro.to_string` that hides implementation details, such as rewriting `sigil_<NAME>` calls to `~<NAME>` and converting interpolation back from it's function call form.

### Environment

* Elixir & Erlang versions (elixir --version): 
```
elixir --version
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.7.0-dev (f34d749) (compiled with OTP 20)
```
* Operating system: macOS

### Current behavior

While building the BEAM chunk viewer for IntelliJ Elixir, I noticed that my port of `Macro.to_string` into Kotlin was showing the raw `:erlang` calls for the guards.  

![screen shot 2018-01-14 at 6 06 51 pm](https://user-images.githubusercontent.com/298259/34922457-be230874-f955-11e7-827e-723a33b37cb7.png)

I assumed I missed porting something, but then checked the output from `Macro.to_string` in `iex`:

![screen shot 2018-01-14 at 6 07 45 pm](https://user-images.githubusercontent.com/298259/34922467-e16240fc-f955-11e7-87a8-b81d40514554.png)

```
iex(2)> :beam_lib.chunks('/Users/luke.imhoff/github/C-S-D/alembic/_build/dev/lib/alembic/ebin/Elixir.Alembic.Document.beam', [:debug_info]) |> elem(1) |> elem(1) |> Keyword.get(:debug_info) |> elem(2) |> elem(1) |> Map.get(:definitions) |> Enum.at(0) |> elem(3) |> Enum.at(0) |> elem(3) |> Macro.to_string() |> IO.puts()
case(minimum_children?(json)) do
  x when :erlang.or(:erlang."=:="(x, nil), :erlang."=:="(x, false)) ->
    Alembic.FromJson.merge(collectable_result, minimum_children_error(error_template))
  _ ->
    collectable_result
end
```

1. `git clone git@github.com:C-S-D/alembic.git`
2. `mix deps.get`
3. `mix compile`
4. `iex`
5. `:beam_lib.chunks('_build/dev/lib/alembic/ebin/Elixir.Alembic.Document.beam', [:debug_info]) |> elem(1) |> elem(1) |> Keyword.get(:debug_info) |> elem(2) |> elem(1) |> Map.get(:definitions) |> Enum.at(0) |> elem(3) |> Enum.at(0) |> elem(3) |> Macro.to_string()`

### Expected behavior

The guards after `x when` in the case would be rewritten to the "Elixir form" the same way the exception blamer rewrites the guards for function heads

```elixir
case(minimum_children?(json)) do
  x when x !== nil or x !== false ->
    Alembic.FromJson.merge(collectable_result, minimum_children_error(error_template))
  _ ->
    collectable_result
end
```

#### Potential Extra behavior

The actual code for `validate_minimum_children?/3` uses an `if` `else`.  

```elixir
  defp validate_minimum_children(collectable_result, json, error_template) do
    if minimum_children?(json) do
      collectable_result
    else
      FromJson.merge(collectable_result, minimum_children_error(error_template))
    end
  end
```

I'm not sure if y'all'd want `Macro.to_string` to rewrite `case`s that look like an `if` back to an `if` since it involves a larger pattern check, but it's a possibility to make the output look like the input to `Code.string_to_quoted` more.

**Comment by josevalim** [comment]
Macro.to_string should be kept as is.

While we do handle things such as sigils, we only do so because there is no ambiguity behind their calls. If we see `sigil_r` as a local call with a `<<>>` node as first argument then we can translate from one to the other without ambiguity.

When you see `:erlang.==` in the AST, it is impossible for us to know if the user wrote `==`, `Kernel.==` or `:erlang.==`. It is not the job of `Macro.to_string` to introduce this ambiguity. In fact, the user may even have unimported `==` in that given context.

Another way to look at it is to notice that Macro.to_string is doing transformations that are done when we tokenize+parse (such as sigils, access syntax, etc) but it should not touch transformations that are done during AST expansion.

You should either have a pass that undo those yourselves or work on the AST prior to expansion.

**Comment by KronicDeth** [comment]
> Another way to look at it is to notice that Macro.to_string is doing transformations that are done when we tokenize+parse (such as sigils, access syntax, etc) but it should not touch transformations that are done during AST expansion.

This is a helpful distinction. Thank you.
