### ISSUE TITLE
error compile elixir

### ISSUE THREAD

**Issue by molavy** [elixir-lang/elixir#7215]
on compile elixir from source git
make test clean
  1) test stream keeps BOM (FileTest)
     test/elixir/file_test.exs:1449
     Assertion with == failed
     code:  assert [<<239, 187, 191>> <> "Русский\n"] == bom_line
     left:  ["\uFEFFРусский\n"]
     right: ["Русский\n"]
     stacktrace:
       test/elixir/file_test.exs:1457: (test)

........................................................................................................................................................................

  2) test binread all (IOTest)
     test/elixir/io_test.exs:28
     Assertion with == failed
     code:  assert "LF\nCR\rCRLF\r\nLFCR\n\r" == IO.binread(file, :all)
     left:  "LF\nCR\rCRLF\r\nLFCR\n\r"
     right: "LF\nCR\rCRLF\nLFCR\n\r"
     stacktrace:
       test/elixir/io_test.exs:30: (test)

..............................................................

Finished in 31.1 seconds (12.3s on load, 18.8s on tests)
1368 doctests, 2860 tests, 2 failures

Randomized with seed 867233
Makefile:214: recipe for target 'test_stdlib' failed
make: *** [test_stdlib] Error 1

### Environment
erlang v 20
elixir source from git last commit Date:   Tue Jan 16 12:40:29 2018 +0100
linux mint 17

### Expected behavior
make test with no problem

**Comment by josevalim** [comment]
There are tools, sometimes git depending on your configuration, that
removes BOM and CRLF. I would recommend checking what is your git autocrlf
config and check of anything may have stripped those files along the way.
Note the tests pass on CI (although they use another Linux distro)
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Please let us know if you have more info and we will gladly reopen this. Thank you!
