### ISSUE TITLE
Elixir 1.6 causes dialyzer to show error `Function init/1 has no local return` if `name` is given as argument

### ISSUE THREAD

**Issue by samphilipd** [elixir-lang/elixir#7220]
### Environment

* Elixir & Erlang versions (elixir --version): 

```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.0 (compiled with OTP 20)
```

* Operating system: 

Mac OS High Sierra 10.13.2 (17C205)

### Current behavior

Dialyzer emits warnings that were not present in elixir 1.5

```
apps/rested/lib/workable/supervisor.ex:12: Function init/1 has no local return
```

Module looks like:

```elixir
defmodule Workable.Supervisor do
  @moduledoc """
  The main supervisor managing Workable state and workers.
  """

  use Supervisor

  def start_link(opts) do
    Supervisor.start_link(__MODULE__, :ok, opts)
  end

  def init(:ok) do
    Supervisor.init([], strategy: :rest_for_one, name: Workable.Supervisor)
  end
end
```

It does not emit an error here:

```elixir
defmodule Workable.Supervisor do
  @moduledoc """
  The main supervisor managing Workable state and workers.
  """

  use Supervisor

  def start_link(opts) do
    Supervisor.start_link(__MODULE__, :ok, opts)
  end

  def init(:ok) do
    Supervisor.init([], strategy: :rest_for_one)
  end
end
```

### Expected behavior

I would expect dialyzer to not emit any error in either case.

**Comment by josevalim** [comment]
Dialyzer is correct here. `:name` is not a valid option to give to `init`.

**Comment by josevalim** [comment]
Closing this for now! Please let us know if you have any questions.

**Comment by samphilipd** [comment]
Did the interface change in Elixir 1.6? How do we give a name to the supervising process now?

**Comment by samphilipd** [comment]
Ah I see, it gets passed to start_link. Not sure how this ever worked then... Thanks!

**Comment by apoorv-2204** [comment]
> `:name` is not a valid option to give to `init`

please elaborate, I am facing same issue.
```
defmodule Archethic.Bootstrap.Supervisor do
  @moduledoc false

  use Supervisor
  alias Archethic.Bootstrap.NetworkConstraints
  alias Archethic.Utils

  def start_link(args \\ []) do
    Supervisor.start_link(__MODULE__, args, name: __MODULE__)
  end

  def init(_args) do
    children = [
      {NetworkConstraints, []}
    ]

    children = Utils.configurable_children(children)

    Supervisor.init(children, strategy: :one_for_one, restart: :transient)
  end
end
```

**Comment by sigurdsa** [comment]
> > `:name` is not a valid option to give to `init`
> 
> please elaborate, I am facing same issue.
> 
> ```
> defmodule Archethic.Bootstrap.Supervisor do
>   @moduledoc false
> 
>   use Supervisor
>   alias Archethic.Bootstrap.NetworkConstraints
>   alias Archethic.Utils
> 
>   def start_link(args \\ []) do
>     Supervisor.start_link(__MODULE__, args, name: __MODULE__)
>   end
> 
>   def init(_args) do
>     children = [
>       {NetworkConstraints, []}
>     ]
> 
>     children = Utils.configurable_children(children)
> 
>     Supervisor.init(children, strategy: :one_for_one, restart: :transient)
>   end
> end
> ```

`restart:` is not a valid option either, see https://hexdocs.pm/elixir/1.13/Supervisor.html#init/2
