### ISSUE TITLE
Code recompilation issue

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#7221]
### Environment

* Elixir: 1.6

### Current behavior

In a phoenix app I have a plug that reads some config value in `init/1` callback.
I run `mix test test/my_plug_test.exs`, the test passes
Next I change the config to some invalid value
I run `mix test test/my_plug_test.exs` again and it still passes (should now fail)
The app is not recompiled, and the old config value is still used.

Side note: when I move the config retrieval to `call/2` callback, the issue no longer appears.

### Expected behavior
Recompile should happen after config change

**Comment by rranelli** [comment]
could you provide us with a code sample reproducing the issue?

**Comment by lukaszsamson** [comment]
I'll try to prepare a minimal repro

**Comment by josevalim** [comment]
Is it an umbrella application or a regular one? Where do you change the
config value?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by lukaszsamson** [comment]
It's an umbrella. I'm changing `config :my_app_web, :prop_name, 1` in  `lib/my_app_web/config/test.exs`

**Comment by josevalim** [comment]
It is a known issue. There is an issue to track it, I will post it here
when I am back home.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
See #6996 (also opened by you :D).
