### ISSUE TITLE
GenServer injects an @opts in using code

### ISSUE THREAD

**Issue by princemaple** [elixir-lang/elixir#7230]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.6
* Operating system: N/A

### Current behavior

In Elixir 1.6 `use GenServer` injects an `@opts` into the destination module
This can cause problems if you have the same module attribute above the line `use GenServer`
And having code referring to `@opts`

See someone reporting this on slack https://elixir-lang.slack.com/archives/C03EPRA3B/p1516350397000058

in case the link dies,

@ssb on slack posted this

```elixir
defmodule A do
 defmacro __using__(opts) do
   quote do
     @a Keyword.get(unquote(opts), :a, "wata")
   end
 end
end

defmodule B do
 defmacro __using__(opts) do
   quote do
     @opts unquote(opts)
     use GenServer
     use A, unquote(opts)

     @b Keyword.fetch!(@opts, :b)
   end
 end
end

defmodule C do
 use B, b: [:watb]

 IO.inspect("A: #{inspect @a}")
 IO.inspect("B: #{inspect @b}")
end
```

### Expected behavior

Std libs not injecting more code than necessary.

### Question

Why change it from `bind_quoted` (in <= 1.5) to `@opts` ?

**Comment by josevalim** [comment]
@princemaple good call. We should namespace it.

**Comment by princemaple** [comment]
⚡️ ⚡️ ⚡️
