### ISSUE TITLE
Forcing Logger Sync

### ISSUE THREAD

**Issue by benwilson512** [elixir-lang/elixir#7246]
Hey folks, in talking with @fishcakez it was unclear which precise set of logger configurations might force it to operate in sync mode. A forced sync mode can be useful for example in development when using it to correlate database access with other specific function calls.

This may be a simple matter of documentation, or if there isn't any such logger configuration, a change to enable this.

**Comment by josevalim** [comment]
Probably setting sync_threshold to 0 is enough. But we would need to document it and write a test.

**Comment by tontytwo** [comment]
Hi, I want to contribute to elixir, is this a good task for a beginner like me?

**Comment by josevalim** [comment]
@tontytwo you will have to try it to be sure. :)

Here is the place where we would write a test to verify this behaviour: https://github.com/elixir-lang/elixir/blob/master/lib/logger/test/logger/utils_test.exs#L14

The documentation should be added to the `Logger` module.

Have fun!
