### ISSUE TITLE
Potentially useless allocate/deallocate bytecode operations that could slow code execution/loading

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#7258]
### Environment

* Elixir & Erlang versions (elixir --version): 
  ```
   Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] 
   [kernel-poll:false] [dtrace]
    
   Elixir 1.7.0-dev (c38fa49) (compiled with OTP 20)
   ```
* Operating system: macOS High Sierra 10.13.2

### Current behavior

`genop.tab`'s description of [`allocate`](https://github.com/erlang/otp/blob/OTP-20.2.2/lib/compiler/src/genop.tab#L90-L94) arguments are described

```
## @spec allocate StackNeed Live
## @doc Allocate space for StackNeed words on the stack. If a GC is needed
##      during allocation there are Live number of live X registers.
##      Also save the continuation pointer (CP) on the stack.
```

So, from that description, I would think that the `allocate` is a no-op if `StackNeed` is not `> 0` since it's like `malloc`ing `0` bytes.  

* `git clone https://github.com/C-S-D/alembic.get`
* `git checkout 027c0dd8c875e5ab1a23fce8da6950f5e5637153`
* `mix compile`
* `iex`
* `File.write("disasm.ex", :beam_disasm.file('/Users/luke.imhoff/github/C-S-D/alembic/_build/dev/lib/alembic/ebin/Elixir.Alembic.Document.beam')  |> inspect(printable_limit: 100_000, limit: 100_000, width: 120, pretty: true))`
* Open `disasm.ex`
* View lines 189 to 198

I looked at the disassembly of `Alembic.Document.beam`, 

```elixir
      {:allocate, 0, 0},
      {:make_fun2, {Alembic.Document, :"-errors_options/0-fun-2-", 1}, 2, 83098346, 0},
      {:move, {:atom, :member}, {:x, 1}},
      {:move, {:x, 0}, {:x, 2}},
      {:move, {:literal, %{field: :errors, member: %{name: "errors"}}}, {:x, 0}},
      {:line, 7},
      {:call_ext, 3, {:extfunc, Access, :get_and_update, 3}},
      {:line, 7},
      {:bif, :element, {:f, 0}, [integer: 2, x: 0], {:x, 0}},
      {:deallocate, 0},
```
-- `disasm.ex` lines 189 to 198

It has `allocate(0, 0)` followed after a bit by `deallocate(0)`, which appears to be useless bytecode instructions.  I can also reproduce the disassembly in my own implementation in Kotlin/Java, so I don't think it's a bug in the disassembly only.

![screen shot 2018-01-25 at 5 08 35 pm](https://user-images.githubusercontent.com/298259/35415243-e908913a-01f2-11e8-8e6d-ff5dcc291ad6.png)

### Expected behavior

I would expect that some part of the compilation process would not generate no-op allocations and deallocation, but **I don't know if this is a bug or just a missed optimization pass**.  It could also be that a `NOP` is needed here for some reason to set up the microarchitectural state of the VM and `allocate(0, 0)` was just chosen to do that since BEAM doesn't have a specific `NOP` instruction and so its not really useless.

I have not traced if this is a problem with the Elixir compiler or the OTP compilation passes.  It was just some weird bytecode I spotted when making my BEAM Chunk viewer.  If you want me to follow up with OTP's issue tracker let me know.  I also have not checked if the beam loader that converts the generic operators in the bytecode to the version executed in memory optimizes this out.

**Comment by michalmuskala** [comment]
`allocate 0` is not a NOP, besides allocating place on the stack for the `Y` registers, it also saves the continuation pointer on the stack. This is needed when you call some other function from that function, otherwise the original return point would be lost. Symmetrically, `deallocate 0` besides deallocating place for the stack registers, pops the continuation pointer from the stack and sets it as the current one, so that the following `return` instruction reaches correct code.

**Comment by KronicDeth** [comment]
Thanks @michalmuskala.  It's good to know that `allocate(0, 0)` is used just for it's save `CP` effect.
