### ISSUE TITLE
Supervisor: got "@impl true" for function init/1 but no behaviour was declared

### ISSUE THREAD

**Issue by nifoc** [elixir-lang/elixir#7285]
### Environment

* Elixir & Erlang versions (elixir --version):

```
$ elixir --version
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 20)
```
* Operating system: 

```
$ uname -a
Darwin FooBar.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

### Current behavior

Compiling the following module emits a warning:

```elixir
defmodule Demo.Supervisor do
  use Supervisor

  @impl true
  def init([]) do
    supervise([], strategy: :one_for_one)
  end
end
```

```
warning: got "@impl true" for function init/1 but no behaviour was declared
```
### Expected behavior

The warning should not be emitted.

This is happening because the `@behaviour Supervisor` line was removed from `supervisor.ex` in this commit: https://github.com/elixir-lang/elixir/commit/ecad8493190e6ff1bb2bd78a95eb321782556dec#diff-9d432a14620b20769d459b1041935cf8

If this was done by accident, I'd be happy to submit a PR 😄

**Comment by josevalim** [comment]
Ouch, it was an accident. Great catch. Please submit a PR!
