### ISSUE TITLE
`mix test –-only inexistent_tag` gives no warning/error

### ISSUE THREAD

**Issue by pablobcb** [elixir-lang/elixir#7294]
Not sure if this is right place to talk about it, tried on the forum and slack but got no answer
### Environment

* Elixir & Erlang versions (elixir --version): 
Elixir 1.6.0 (compiled with OTP 19)

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

* Operating system: Mac OS X 10.12.6

### Current behavior

`mix test –only inexistent_test` runs fine even if there is not test named `inexistent_test`

### Expected behavior

I think it would be better if some hint/warning/error to notify the user that the desired test is not going to run

**Comment by josevalim** [comment]
We could indeed emit a error. We should likely error anytime no test runs at all.

**Comment by josevalim** [comment]
Question: should we do this in `mix test` or inside ExUnit itself? Probably the former.

**Comment by hlhr** [comment]
I checked the code of the `mix test`, it would be possible to emit a error if the only option is used and the excluded and total number of tests is equal.

If this is a possible solution I would give it a try.

**Comment by josevalim** [comment]
That sounds good to me!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Closing in favor of the PR.
