### ISSUE TITLE
Don't include private dependencies Github OAuth token in mix.lock

### ISSUE THREAD

**Issue by mvpgomes** [elixir-lang/elixir#7301]
### Environment
```elixir
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.0 (compiled with OTP 20)
```

### Current behavior
When having a dependency that is a private repo in Github in `mix.exs`:

```elixir
{:my_lib, git: "https://#{System.get_env("GITHUB_OAUTH_TOKEN")}@github.com/my_org/my_lib.git"}
``` 
and running `mix deps.get`, `GITHUB_OAUTH_TOKEN` is being hardcoded in the entry generated in `mix.lock`

```elixir
"my_lib": {:git, "https://GITHUB_OAUTH_TOKEN@github.com/my_org/my_lib.git", "618a38786cbzx546fb2ae0dad3c179bslfj734e9fe8"}
```
As result, when commiting `mix.lock` to the version control, the `GITHUB_OAUTH_TOKEN` will be exposed and stored in the version control.

**Comment by mvpgomes** [comment]
Just for reference https://github.com/bundler/bundler/issues/3609 about the same issue that existed in Bundler.

**Comment by ericmj** [comment]
You can use git config to rewrite urls, see: https://git-scm.com/docs/git-config#git-config-urlltbasegtinsteadOf
