### ISSUE TITLE
Map key matching in function headers with pin'd variables

### ISSUE THREAD

**Issue by aseigo** [elixir-lang/elixir#7302]
### Environment

* Environment: Elixir 1.6.0 and Erlang 20.1 
* Operating system: Linux

Somewhat related to #2061, but perhaps a bit more specific issue. If you feel this is a duplicate, please feel free to close it as such.

### Current behavior

    fn (key, %{^key => value} = state) -> %{state | key: 1} end

Results in:

    ** (CompileError) iex:1: unknown variable ^key. No variable "key" has been defined before the current pattern
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3

buuuut, this also doesn't work:

    f = fn (key, %{key => value} = state) -> %{state | key: 1} end 

as it errors out with:

     ** (CompileError) iex:4: illegal use of variable key inside map key match, maps can only match on existing variables by using ^key
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3

### Expected behavior

It should compile and work. :) This seems to be a mismatch between how pattern matching with Maps works, and how function headers work. Not sure if those two worlds can be bridged, but it would be nice.

Cheers, and thanks for the awesome 1.6 release!

**Comment by michalmuskala** [comment]
Unfortunately, it's not possible to do this right now (and I don't think it will be ever possible).

Imagine a situation like this:

```
def foo({:a, value} = key, %{key => value}), do: ...
```

It's not very clear what should happen in a case like that, especially if you have many similar clauses - the pattern match would become very expensive.

The way to do this now, is to have a separate `case` inside the function body matching on the map.

**Comment by josevalim** [comment]
Yup, there isn't much we can do in this case.

**Comment by ijverig** [comment]
@michalmuskala @josevalim 
```elixir
def foo({:a, value} = key, %{key => value}), do: ...
```
> It's not very clear what should happen in a case like that

Why/what is it not clear?
Could you give me some example? I'm failing to see the unclarity of the situation, given that we can match on keys of Keywords:

```elixir
iex(3)> f = fn(a, [{a, a}]) -> a end 
#Function<12.99386804/2 in :erl_eval.expr/5>
iex(4)> f.(:me, me: :me)             
:me
iex(5)> f.(:me, mee: :me)
** (FunctionClauseError)
```

**Comment by michalmuskala** [comment]
Keywords and maps are inherently different. Pattern matches on lists (and keywords are lists) are "exact" in a sense that you need to specify the whole structure. On the other hand patterns for maps match on a subset of the structure. 

In any case - this is not something we can implement in Elixir alone. Such a feature would need to be first introduced into the Erlang compiler (that we use underneath for compiling Elixir). You should lobby the OTP Team first 🙂.
