### ISSUE TITLE
Compiler error when not using anonymous functions could be changed to be more helpful

### ISSUE THREAD

**Issue by SkipMike** [elixir-lang/elixir#7307]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6
* Operating system: macOS

### Current behavior

When you define an anonymous function and then call it improperly, the error message is confusing.

```
defmodule Foo do
  def hello do
    bar = fn x ->
      x + 1
    end

    bar(1)
    Enum.map([1], &bar(&1))
  end
end
```
Returns "undefined function anon_fun/1". It took me a while to understand what I had done wrong, I need to call anonymous functions with a ".". I honestly couldn't figure it out until reviewing anonymous functions at Elixir School.

### Expected behavior
I'm hoping that the error can be improved to say something like "bar is an anonymous function and must be called like bar.(1)". I don't use anonymous function like this very often, I mostly use them as arguments to functions and I suspect many beginners might hit this error and be confused as well.

**Comment by josevalim** [comment]
The compiler cannot guess what you have tried to do *wrong*. What if you really wanted to pass `bar/1` but forget to define it locally? What if it was a typo on the function name? I am aware there is an anonymous function in the same place but it is one of the things that can go wrong, not the only one.
