### ISSUE TITLE
Adding support for 'ctrl-l' and 'ctrl-d' to iex

### ISSUE THREAD

**Issue by i-s-o-g-r-a-m** [elixir-lang/elixir#7310]
### Precheck

This is not really a new language feature, or anything close to that, so it seems like it could be OK to propose here and not on the mailing list. Let me know if that's a bad assumption.

I see that `iex` supports stuff like `ctrl-a` and `ctrl-e`. Would there be interest in also supporting `ctrl-l` (to clear the screen, like you can do with `clear()` currently) and `ctrl-d` to exit -- both standard in many REPLs and similar terminal-based programs?

### Environment

* Elixir & Erlang versions (elixir --version): 1.7.0-dev
* Operating system: macOS

**Comment by michalmuskala** [comment]
Elixir relies on the Erlang shell infrastructure to provide editing and all the other support mechanisms. The request would probably need to go upstream.

**Comment by josevalim** [comment]
As @michalmuskala said, we simply rely on the Erlang shell, so we would need to add those there.

I have actually proposed ctrl+d in the past, but that is used to disconnect from a live shell without bringing the node down, so using it to shut a node down could be very risk and they did not accept it.

Supporting ctrl+l would be a nice addition, but someone would have to make it work across OSes.

**Comment by i-s-o-g-r-a-m** [comment]
@josevalim @michalmuskala thanks 👍

**Comment by kelvinst** [comment]
Also, important to notice this seems like something that is open to discussion by the erlang core team, since this https://bugs.erlang.org/browse/ERL-331 still open. Maybe we should do some noise there, IDK.

**Comment by OvermindDL1** [comment]
@kelvinst The BEAM does not expose unix signals internally, so again that would have to be proposed/PR'd into Erlang itself, not Elixir.  You should ask them?  :-)

**Comment by kelvinst** [comment]
@OvermindDL1 yeah, I guess I'll just ask them on the issue I mentioned above! 👍

**Comment by josevalim** [comment]
The BEAM does expose exit signals from 20.x. Check the `:os` module.

**Comment by OvermindDL1** [comment]
> The BEAM does expose exit signals from 20.x. Check the :os module.

Oooo, really?  That's awesome!  There are things that I can use those for (like reloading certain configs), wonder how I missed that addition.  :-)

Thanks!

**Comment by kelvinst** [comment]
Well, seems like BEAM does expose the OS signals, but not `sigeof`, which is what normally `ctrl-d` is mapped to. 😕

**Comment by sodapopcan** [comment]
Hi!  I'm pretty new to Elixir and was quite missing `ctrl-l` (and ya, `ctrl-d` would be nice too).

It seems like there is nothing to be done on Elixir side of things, but I just wanted to ping this this 2+ year old, closed issue.

From explanations here, my understanding is that iex piggybacks off of Erlang's REPL.  When visiting the Erlang issue linked by @kelvinst https://bugs.erlang.org/browse/ERL-331, it looks like in the Erlang REPL you can type `q()` to quit.  Why does this not work in iex?  I don't mind having to press `ctrl-c` twice, but it's a little jarring to always see that message.

Being told "Nope, this can't ever happen" is not a deal-breaker for using Elixir for me by any stretch!  I'm merely wondering if anyone has been sitting on new insight around this in the last couple of years.

✌️
