### ISSUE TITLE
Mix installation of rebar3 due to "ecto.create" (to build :ranch) does not respect MIX_ARCHIVES environment variable

### ISSUE THREAD

**Issue by CMCDragonkai** [elixir-lang/elixir#7323]
### Environment

* Elixir & Erlang versions (elixir --version):  

```
Erlang/OTP 20 [erts-9.2] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10]

Elixir 1.6.0 (compiled with OTP 19)
```
* Operating system: Windows

### Current behavior

When running `mix ecto.create`, it asks to install rebar3 if it is not available. This installation of rebar3 gets installed into `~/.mix/rebar3` even when `MIX_ARCHIVES` environment variable has been exported and set to the absolute path of a local directory `$(pwd)/.mix`.

### Expected behavior

I would expect that rebar3 and rebar gets installed in the `$(pwd)/.mix` since all the other mix installations gets put into there including `mix archive.install ...` and hex itself are all there.

**Comment by josevalim** [comment]
MIX_ARCHIVES controls only archives and rebar3 is not one of them. :) Use MIX_HOME or MIX_REBAR or MIX_REBAR3 to control the rebar installation.

**Comment by CMCDragonkai** [comment]
If I set only `MIX_HOME` does this also specify where `MIX_ARCHIVES` would be if it wasn't set?

**Comment by josevalim** [comment]
Yes!
