### ISSUE TITLE
v1.6.1 defguard seeing runtime error

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#7332]
### Environment

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.1 (compiled with OTP 20)
Ubuntu 16.04

### Current behavior

Trying out defguard and following the is_even example in the docs. Two versions:

  `defguard is_even1(number) when is_integer(number) and rem(number, 2) == 0`
  `defguard is_even2(number) when rem(number, 2) == 0`

`41 |> is_even1`
`41 |> is_even2`

both return `false` as expected.

Also

`:not_an_integer |> is_even1`

gets `false`

But

`:not_an_integer |> is_even2`

gets

`** (ArithmeticError) bad argument in arithmetic expression
    :erlang.rem(:not_an_integer, 2)`

### Expected behavior

The "Failing guards" section in the docs says runtime errors will be pre empted and `false` returned.

Just me? Am I reading this right?

**Comment by michalmuskala** [comment]
The "failing guards" section refers to expressions used in guard position, not macros defined using `defguard`. It should be made clearer.

**Comment by josevalim** [comment]
Good catch. Can you please send a PR to make the docs clearer? Thank you!

**Comment by michalmuskala** [comment]
@josevalim did you mean me or @ianrumford?

**Comment by josevalim** [comment]
Whoever wants to do it. 🎉

**Comment by ianrumford** [comment]
Thank you Michal, you beat me to it. If I can help any, please holler.

**Comment by ianrumford** [comment]
This closed out before I could find time to focus on it again yesterday.

Thank you again Michal.
