### ISSUE TITLE
Weird error message when I pass true instead of a do_block 

### ISSUE THREAD

**Issue by narrowtux** [elixir-lang/elixir#7333]
When I write one-liner definitions, and forget to write `do:`, like so:
```elixir
iex(1)> defmodule Test do
...(1)> def foo(), true
...(1)> end
```
the compiler will result in:
```
** (CompileError) iex:2: invalid arguments for "try"
    iex:2: (module)
```
Which is a bit confusing. Maybe there could be a better error message.

**Comment by josevalim** [comment]
Thanks, I have verified this on master. Please don't forget to include the Elixir version in upcoming reports. :)

**Comment by josevalim** [comment]
I will push a fix soon. We raise for missing :do in some cases but not in others, I will make sure we raise it consistently.
