### ISSUE TITLE
Module.add_doc is missing in 1.6

### ISSUE THREAD

**Issue by mspanc** [elixir-lang/elixir#7335]
I noticed that 1.6 has no Module.add_doc. When it disappeared? That changelog does not mention such change. Is it intentional? What is the replacement?

reference: https://github.com/elixir-lang/elixir/blob/v1.6/CHANGELOG.md

It was present in 1.5.

### Environment

* Elixir & Erlang versions (elixir --version): 1.6.1
* Operating system:  Mac OS X

### Current behavior

Module.add_doc is not present in 1.6

### Expected behavior

Module.add_doc is present or it's disappeareance is mentioned in the changelog. Clear replacement is described.

**Comment by josevalim** [comment]
It was accidental, we will add it back and properly deprecate it.

As a replacement, you can probably just use `@doc` directly.
