### ISSUE TITLE
v1.6.1 doco error in Typespecs

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#7339]
In the [Typespecs documentation](https://hexdocs.pm/elixir/typespecs.html#types-and-their-syntax) it says:

> See the “Defining a type” and “Defining a specification” sub-sections 

There is no "Defining a type" section.  Should this be  "User-defined types"?

**Comment by josevalim** [comment]
Yes! Could you please send a PR?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ianrumford** [comment]
Never done a PR for Elixir before but now's the time to learn I guess!

**Comment by josevalim** [comment]
@ianrumford this one can be a bit easier because you can do it directly via the github UI. :)

**Comment by ianrumford** [comment]
Thanks for the steer.  Had a practice first and have now submitted the PR.
