### ISSUE TITLE
defoverridable ignored in __before_compile__ macro

### ISSUE THREAD

**Issue by blatyo** [elixir-lang/elixir#7340]
### Environment

* Elixir & Erlang versions (elixir --version): 

Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 20)

* Operating system: 
OS X 10.11.5

### Current behavior

When I run the following code:

``` elixir
defmodule X do
  defmacro __using__(_) do
    quote do
      def handle_in(_event, _message, socket) do
        {:noreply, socket}
      end

      defoverridable handle_in: 3
    end
  end
end

defmodule Y do
  defmacro __using__(_) do
    quote do
      @before_compile unquote(__MODULE__)
    end
  end

  defmacro __before_compile__(_) do
    quote unquote: false do
      @handle_events [
        {"a", A, :a},
        {"b", B, :b},
        {"c", C, :c}
      ]

      for {event, module, function} <- @handle_events do
        def handle_in(unquote(event), payload, socket) do
          apply(unquote(module), unquote(function), [payload, socket])
        end
      end
    end
  end
end

defmodule Z do
  use X
  use Y
end
```

It generates `warning: this clause cannot match because a previous clause at line 6 always matches`

### Expected behavior

It should not generate the warning, because the 3 new functions being generated are overriding the default.

**Comment by josevalim** [comment]
It is working as intended. Callbacks registered first run last. Think about
Plug.Router. If you have a module that uses Plug.Router, it will use
Plug.Router first. If that module has a before compile that generates
routes, Plug.Router needs to compile the routes last.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
To clarify, defoverridable should be working fine. What may be causing
confusion is the order which callbacks run.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by blatyo** [comment]
I don't think I understand. From the code above, I expect the following to happen:

1. `use X` in `Z` will cause the `X.__using__/1` macro to run, which defines `handle_in/3` and makes it overridable.
2. `use Y` in `Z` will cause the `Y.__using__/1` macro to run, which sets up a before compile callback.
3. The `Y.__before_compile__/1` macro runs, which defines overrides for `handle_in/3`, which was defined in step 1.

**Comment by blatyo** [comment]
I made a slightly modified version to convince myself that things were happening in the order I expect.

``` elixir
defmodule X do
  defmacro __using__(_) do
    IO.puts "1 using X"
    quote do
      IO.puts "3 default handle_in"
      def handle_in(_event, _message, socket) do
        {:noreply, socket}
      end

      defoverridable handle_in: 3
    end
  end
end

defmodule Y do
  defmacro __using__(_) do
    IO.puts "2 using Y"
    quote do
      IO.puts "4 before compile callback setup"
      @before_compile unquote(__MODULE__)
    end
  end

  defmacro __before_compile__(_) do
    IO.puts "5 before compile Y"
    quote unquote: false do
      @handle_events [
        {"a", A, :a},
        {"b", B, :b},
        {"c", C, :c}
      ]

      for {event, module, function} <- @handle_events do
        IO.puts "6 defining override with event #{inspect event}"
        def handle_in(unquote(event), payload, socket) do
          apply(unquote(module), unquote(function), [payload, socket])
        end
      end
    end
  end
end

defmodule Z do
  use X
  use Y
end
```

When that is run I get:

1 using X
2 using Y
3 default handle_in
4 before compile callback setup
5 before compile Y
6 defining override with event "a"
6 defining override with event "b"
6 defining override with event "c"
warning: this clause cannot match because a previous clause at line 11 always matches

**Comment by josevalim** [comment]
Oh, apologies. I've read it the first example as if it was defining the code in a `__before_compile__` callback.

The behaviour you are seeing is still desired as all overridable definitions are made concrete before the first before compile hook runs. This allows us to do checks such as verifying if a function/macro was defined. You can, however, make it overridable again. I have updated the docs to clarify this, since it wasn't documented before (although I do expect folks to be relying on the existing behaviour).
