### ISSUE TITLE
Do not allow a dot to follow ...

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7342]
Looks at @ericmj.

**Comment by josevalim** [comment]
The same for + after ++ and - after --. I will do a complete scan soon.

**Comment by whatyouhide** [comment]
Should we handle this at the tokenizer level directly? I can jump on it if so

**Comment by josevalim** [comment]
Yes.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by whatyouhide** [comment]
I think `^` should be added to the list as well.

**Comment by josevalim** [comment]
Why? We generally allow unary operators to be repeated. For example: `!!` or `@@`.

**Comment by whatyouhide** [comment]
`^^^` is an operator and `^` is as well, so `a ^^^^ b` parses as `a ^^^ (^b)`.

**Comment by josevalim** [comment]
good call.
