### ISSUE TITLE
Dialyzer warnings using anonymous functions in with statement else block that refers to any variable

### ISSUE THREAD

**Issue by xadhoom** [elixir-lang/elixir#7351]
This is basically #6378 ported to 1.6.
Did not understand if is a dialyzer issue or not.

### Environment

* Elixir & Erlang versions: Elixir 1.6 & 1.5  with otp 20.2.2
* Operating system: Fedora Linux 27

### Current behavior

When using anonymous function in `else` block of a `with` statement, and such function refers to any variable (outside the with statement or in the `else` block itself), dialyzer always complains about `The created fun has no local return`

Basically, everytime a Logger call is passed a fn() which logs a variable, dialyzer blames it.

Does not happen with Elixir 1.4.5

I've setup a sample minimal repo to demonstrate the issue: https://github.com/xadhoom/test_dialyzer
Just run `mix dialyzer` on it.

`logger_dialyzer.ex, logger_dialyzer2.ex` will fail while trying to log a variable via an anon function
`test_dialyzer.ex` same, but using a generic function instead of Logger (to demonstrate that is not a Logger issue)
`works_dialyzer.ex` still uses an anon fun, but without referring to outer scope and passes the dialyzer check

### Expected behavior
Dialyzer should not warn such statements as was in 1.4.5, or at least be sure that is a dialyzer issue.

**Comment by michalmuskala** [comment]
This looks quite strange. I tried running dialyzer on the translated `test_dialyzer.ex` module, but it does not fail with the same error. I suspect there might be some issues with lines, but I'm not really sure...

```erl
-module(test).

-compile(no_auto_import).

-export([test/0]).

foo(Fun) ->
    Fun().

ok_or_error() ->
    lists:nth(rand:uniform(2), [ok, error]).

ok_or_other_error() ->
    lists:nth(rand:uniform(2), [ok, error]).

test() ->
    Var = outer_scope,
    case ok_or_error() of
        ok ->
            case ok_or_other_error() of
                ok ->
                    ok;
                Other ->
                    case Other of
                        error ->
                            foo(fun() -> Var end),
                            error;
                        other_error ->
                            other_error;
                        Other2 ->
                            erlang:error({with_clause,Other2})
                    end
            end;
        Other ->
            case Other of
                error ->
                    foo(fun() -> Var end),
                    error;
                other_error ->
                    other_error;
                Other2 ->
                    erlang:error({with_clause,Other2})
            end
    end.
```

**Comment by fishcakez** [comment]
Could we include the full dialyzer warnings in the issue please so that people do not need to run the code.

**Comment by michalmuskala** [comment]
Here they are:

```
lib/logger_dialyzer.ex:14: The created fun has no local return
lib/logger_dialyzer2.ex:14: The created fun has no local return
lib/test_dialyzer.ex:12: The created fun has no local return
```

**Comment by xadhoom** [comment]
uhm,
looking into erlang generated code,  ok_or_other_error is not supposed to return ok or other_error atoms?

**Comment by flaviogrossi** [comment]
I can confirm this happens quite a lot in our codebase. Is there any news?

**Comment by michalmuskala** [comment]
Reported upstream as https://bugs.erlang.org/browse/ERL-593

A quick fix to bypass the issue in applications would be to suppress the no local return warning for affected functions using:
```elixir
@dialyzer {:no_return, foo: 1}
```
The only elixir-level solution we could do is to mark entire body of `with` as generated effectively disabling all dialyzer warnings. I don't think that's a good choice.

**Comment by josevalim** [comment]
Thanks for the report!
