### ISSUE TITLE
Mix format changing code unexpectedly on multi parenthesis operation

### ISSUE THREAD

**Issue by grufino** [elixir-lang/elixir#7367]
### Environment

* Elixir & Erlang versions (elixir --version): Version Elixir 1.6.1 (compiled with OTP 20)
* Operating system: Mac OS

### Current behavior

FUNCTION BEFORE RUNNING MIX FORMAT:

```
defp delayed?(%{
         "estimated_arrival_time" => estimated_arrival_time,
         "current_eta" => current_eta,
         "total_rest_time" => total_rest_time,
         "total_estimated_time" => total_estimated_time
       }) do
    ((total_rest_time + (estimated_arrival_time - current_eta)) / total_estimated_time < 0)
  end

```
With the following input parameters:

```
delayed?(%{
         "estimated_arrival_time" => 1517292000,
         "current_eta" => 1517335151,
         "total_rest_time" => 6.84e4,
         "total_estimated_time" => 1.476e5
       })

```
output: false, as expected

FUNCTION AFTER RUNNING MIX FORMAT ON THE FILE:

```
def delayed?(%{
        "estimated_arrival_time" => estimated_arrival_time,
        "current_eta" => current_eta,
        "total_rest_time" => total_rest_time,
        "total_estimated_time" => total_estimated_time
      }) do
    total_rest_time + (estimated_arrival_time - current_eta) / total_estimated_time < 0
  end
```

this time, the output is still false if I call the result from outside the function, but very often I need to debug such function to find out if the calculation is correct, which at first leads me to something like this:
```

total_rest_time + (estimated_arrival_time - current_eta) / total_estimated_time < 0
|> debugger

```
with the debugger only inspecting the value and passing it on:

```
def debugger(item) do
  IO.inspect(item)
  item
end
```

The problem is that this value changes after formatting, it starts printing number values (probably because it tries to evaluate the pipe operator before resolving the value to true/false, or something like that).

so the output of the debugger becomes:
0, which is not an expected output.

### Expected behavior

That's why I think there should be a way of formatting with keeping encapsulation for future purposes, that can be understood by pipe operators (keeping the parenthesis that were there for a reason), we could never expect that a formatter could change behaviour of our code, in any case, not even if my assumption of using pipe operator after this call was wrong because of the parenthesis that mix removed before.

**Comment by josevalim** [comment]
It is a bug in the formatter as we are changing the code semantics. The formatter does not guarantee expressions are "pipeable" though unless you have the pipe operator at the moment of formatting.

Note you can always put IO.inspect in the front too.

**Comment by josevalim** [comment]
I have run the formatter and it is working as expected, as it emits:

```elixir
 (total_rest_time + (estimated_arrival_time - current_eta)) / total_estimated_time < 0
```

Can you please make sure your snippet is correct? Thank you.

**Comment by grufino** [comment]
Jose, the snippet above is what I think is "wrong", because it removed my parenthesis (since it isn't really necessary at the moment), which caused a different behaviour when I piped my debugger function. Although I understand what you said:

>  "The formatter does not guarantee expressions are "pipeable" though unless you have the pipe operator at the moment of formatting"

I think it is not very safe that a formatter erase parenthesis that could make a difference in the future, because you won't remember why you would need it. 

If you think my last argument has no foundation or no solution with the formatter's current implementation/line of thought, please close this issue.

**Comment by OvermindDL1** [comment]
I think this goes along with the formatter removing parenthesis around mathematical operators when they are not strictly required (but I and others like to add to make reading them more clear and unambiguous).

**Comment by josevalim** [comment]
Thanks for the reply @grufino!

> I think it is not very safe that a formatter erase parenthesis that could make a difference in the future, because you won't remember why you would need it.

By this criteria, every pipeline needs a parens because you can use an operator after a pipeline that will have a difference precedence depending on the parens. For example, we will have to format to this:

```elixir
def some_fun do
  (foo
   |> bar)
end
```

Because someone may want to add `+ baz` at the end.

The formatter can't protect you from code you are going to write. We can't guess that an expression may be used with a pipeline or a comparison operator in the future.
