### ISSUE TITLE
h/1 should suggest to use the `t` helper if there is a type with the same name

### ISSUE THREAD

**Issue by yordis** [elixir-lang/elixir#7374]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.7.0-dev
* Operating system: MacOS 10.13.3

### Current behavior

Using `h/1` function an a typespec type do not show the documentation.

```
iex(1)> h StrawHat.Mailer.Schema.Template.t
No documentation for StrawHat.Mailer.Schema.Template.t was found
iex(2)>
```
Source code https://github.com/straw-hat-team/straw_hat_mailer/blob/af8291f80dec5d263aadc6068cb92fc71881aa36/lib/straw_hat_mailer/schema/template.ex#L24

### Expected behavior

~~~It should display the documentation written on `@typedoc`.~~~

It should display a suggestion to use the `t` helper.

**Comment by josevalim** [comment]
Use the `t` helper for it (and the `b` helper for callbacks).

**Comment by wojtekmach** [comment]
I'll send a PR!

**Comment by josevalim** [comment]
I have renamed the title and updated the issue. :)

**Comment by josevalim** [comment]
Closing in favor of the PR.
