### ISSUE TITLE
Why does the compiler enforce that `@callback` definitions include type specs?

### ISSUE THREAD

**Issue by raymond-ji** [elixir-lang/elixir#7388]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 19)
```
* Operating system: macOS High Sierra 10.13.2

### Current behavior

I haven't been able to find documentation/discussion around this so I wanted to ask here.
It seems like when you define a behaviour the compiler requires you to include type specs within the `@callback` definition. Then when you adopt the behaviour, the compiler warns if `function_name/arity` is not defined, but is perfectly happy if you don't follow the type specs.

My question is, why does the compiler enforce that `@callback` definitions include type specs? The compiler otherwise seems consistent about not requiring type specs anywhere else, and it feels confusing that it would require type specs but not enforce them. Also, this means that anyone who wants to use behaviours to get compile-time `function_name/arity` checks has to buy-in to writing type specs, even if they otherwise want to use Elixir as a purely dynamic language.

For example:

If we omit the type specs, we get a compile error
```
defmodule Greeting do
  @callback hello(person)
end
# (CompileError) iex:82: type specification missing return type: hello(person)
```

To make the compiler happy, we have to include type specs:
```
defmodule Greeting do
  @callback hello(%Person{}) :: {:ok, String.t} | {:error, String.t}
end
```

Now when we adopt the behaviour, the compiler checks that `function_name/arity` is defined:
```
defmodule WesternGreeting do
  @behaviour Greeting
  def hello(), do: "Howdy"
end
# warning: undefined behaviour function hello/1 (for behaviour Greeting)
```

However all the type specs in the @callback are disregarded by the compiler:
```
defmodule WesternGreeting2 do
  @behaviour Greeting
  def hello([a, b, c]), do: a <> b <> c
end
# No warnings or errors
```

### Expected behavior

Since Elixir advocates optional typing, as a new user I would expect type specs not to be a requirement to use the behaviour feature.

**Comment by josevalim** [comment]
The callbacks are checked by a separate pass called DIalyzer which we are checking how to better integrate in future Elixir versions. Although they will always require a separate command. Btw, please use the mailing list or elixir forum for discussions/questions. :)
