### ISSUE TITLE
Compiler missing unused variables (&notation/1 related?)

### ISSUE THREAD

**Issue by novaugust** [elixir-lang/elixir#7392]
I made a change to a file in my project and got a "variable unused" compiler warning out of nowhere. Digging in, the unused variable had been unused before even my totally unrelated change. I shrank my file down to a minimal reproducible example below

### Environment

* Elixir & Erlang versions (elixir --version): elixir 1.5.1, erl/otp 20
* Operating system: mac osx

### Current behavior

Compiling this code generates no warnings

```elixir
defmodule M do
  def p(a, b, c, d, e, f, g, h, i, j, ...) do
    a
    |> Enum.map(&B.x/1)
    |> Enum.map(&C.z/1)
  end
end
```

The number of parameters is irrelevant, and any number of variables can be created in the body as well.

the warnings come back as soon as the `&Module.fun/arity` style is removed

#### iex demo

```
iex(1)> defmodule M do
...(1)>   def p(a, b, c, d, e, f, g, h, i, j, ...) do
...(1)>     a
...(1)>     |> Enum.map(&B.x/1)
...(1)>     |> Enum.map(&C.z/1)
...(1)>   end
...(1)> end
{:module, M, <snip>} 
iex(2)> defmodule M do
...(2)>   def p(a, b, c, d, e, f, g, h, i, j, ...) do
...(2)>     a
...(2)>     |> B.x #changed
...(2)>     |> Enum.map(&C.z/1)
...(2)>   end
...(2)> end
warning: redefining module M (current version defined in memory)
  iex:2

warning: variable "..." is unused
  iex:3

warning: variable "b" is unused
  iex:3
(warnings continue)
```

### Expected behavior

There should be warnings on the unused variables even in the first case.

**Comment by josevalim** [comment]
It has been fixed in master now that we have moved the unused variable warnings to the Elixir pass. :)
