### ISSUE TITLE
Base.decode16 does not work with lowercase characters

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#7393]
Elixir 1.6.1, Erlang 20.2

Often when we decode hex strings into binaries we do something like this:

`
Base.decode16!("0a0b0c0d" |> String.upcase)
`

The upcase here can get really expensive in terms of garbage produced. Because Base.decode16 only works with uppercase hex string. Base.decode16 should work with lowercase and uppercase characters.

**Comment by fertapric** [comment]
@vans163 you can pass `case: :mixed` to `decode16!/2`. [Check the documentation for more information](https://hexdocs.pm/elixir/Base.html#decode16/2) :)

**Comment by vans163** [comment]
@fertapric ah, silly me
