### ISSUE TITLE
`inspect` seems to reset `seq_trace` token

### ISSUE THREAD

**Issue by binaryseed** [elixir-lang/elixir#7400]
Hi, I was playing around with the `seq_trace` module, and I found a strange behavior...

If I ever call the `inspect` function, it seems like the current trace token gets reset:

```elixir
test "inspect clears the token" do
  label = 567
  :seq_trace.set_token(:label, label)

  assert {_, ^label, _, _, _} = :seq_trace.get_token()

  inspect({:foo, :bar})

  assert {_, ^label, _, _, _} = :seq_trace.get_token()
end
```

Running this test will fail the second assert...

```
match (=) failed
The following variables were pinned:
 label = 567
code:  assert {_, ^label, _, _, _} = :seq_trace.get_token()
right: []
```

Here's my current versions of things:

```
elixir --version
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.6.1 (compiled with OTP 19)
```

**Comment by josevalim** [comment]
I have created a new Mix project, I have added this there, and all tests pass. Same Elixir and Erlang versions as you. Can you consistently reproduce this in a new project and push it to github?

**Comment by josevalim** [comment]
Apologies, I was able to reproduce it now. :)

**Comment by josevalim** [comment]
Ok, I understand why I cannot reproduce it consistently now. It seems to be related to module loading.

For example, if you call `inspect(1)`, it still makes your test fail. But if I load both `Inspect.Integer` and `Inspect.Algebra` before the test. It no longer fails. I can reproduce it with a simpler example too:

```elixir
  test "inspect clears the token" do
    label = 567
    :seq_trace.set_token(:label, label)

    assert {_, ^label, _, _, _} = :seq_trace.get_token()

    URI.parse "ok"

    assert {_, ^label, _, _, _} = :seq_trace.get_token()
  end
```

And loading the URI module before by calling `Code.ensure_loaded(URI)` makes it pass. My suggestion is for you to build a minimal example in Erlang (use `code:is_loaded/1` to find a module that has not been loaded yet) and send it to the Erlang mailing list to get more information.

**Comment by binaryseed** [comment]
Thanks for digging in! I'll do some more investigation and figure out a minimal Erlang example.

**Comment by binaryseed** [comment]
FYI, tracked down a minimal Erlang example. Turns out it's also triggered by simply trying to read a file wether or not the file exists.

I've submitted a question to the mailing list but i'm new to the list so my message didn't get posted yet

```erlang
-module(seq_fail).
-include_lib("eunit/include/eunit.hrl").

seq_fail_test() ->
  seq_trace:set_token(label, 123),
  ?assertMatch({_, 123, _, _, _}, seq_trace:get_token()),

  {error, enoent} = file:read_file('not_there'),
  ?assertMatch({_, 123, _, _, _}, seq_trace:get_token()).
```

```
  1) seq_fail:seq_fail_test/0: module 'seq_fail'
     Failure/Error: ?assertMatch({ _ , 123 , _ , _ , _ }, seq_trace : get_token ( ))
       expected: = { _ , 123 , _ , _ , _ }
            got: []
     %% .../_build/test/lib/seq_fail/src/seq_fail.erl:9:in `seq_fail:-seq_fail_test/0-fun-1-/0
```

**Comment by binaryseed** [comment]
Tracked this down lower to `open_port` calls. Submitted a bug, and there's some further conversation there: https://bugs.erlang.org/browse/ERL-602
