### ISSUE TITLE
Formatter do not add parenthesis for the typespec

### ISSUE THREAD

**Issue by yordis** [elixir-lang/elixir#7401]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.7.0-dev (77c9d48) (compiled with OTP 20)
* Operating system: MacOS

### Current behavior

I ran `mix format` I am expecting this line https://github.com/straw-hat-team/straw_hat_mailer/blob/224410cf37ee685237bc058c4822361e6b705f4d/lib/straw_hat_mailer/schema/template.ex#L76 do not change

### Expected behavior

I am expecting the typespec to be added the parenthesis as Elixir does with the primitive types (so far).

So it would change to

```elixir
@spec changeset(t(), partial_attrs()) :: Ecto.Changeset.t()
```

**Comment by josevalim** [comment]
Elixir formatter cannot change the AST/semantics of the code, otherwise we risk breaking the code. For this reason, we only add parens to remote calls, we cannot add to local ones.

**Comment by yordis** [comment]
@josevalim if that is true why does the formatter add the parenthesis when I remove it from `Ecto.Changeset.t` what does `we only add parens to remote calls` means? For my personal knowledge, if you dont mind to answer.
