### ISSUE TITLE
Invalid unused variable warning

### ISSUE THREAD

**Issue by febeling** [elixir-lang/elixir#7402]
### Environment

* Elixir & Erlang versions (elixir --version): 
1.6.1
* Operating system: 
macos 10.13.3 (17D102)

### Current behavior
This test generates warnings about unused variable `found`.

```elixir
defmodule UnusedTest do
  use ExUnit.Case

  def fun, do: %{}

  test "unused warning repro" do
    found = fun()
    assert match?(found, %{})
  end
end
```

```
warning: variable "found" is unused
  test/projections/unused_test.exs:9

warning: variable "found" is unused
  test/projections/unused_test.exs:10
```

### Expected behavior

No warning, as the variable is actually used in assert's match.

**Comment by michalmuskala** [comment]
The warning is correct. The first argument of `match?` is a pattern. A variable used in pattern matches any value. Your test is exactly the same as:
```elixir
  test "unused warning repro" do
    found = fun()
    assert match?(x, %{})
  end
```

Most probably you wanted:
```elixir
  test "unused warning repro" do
    found = fun()
    assert match?(^found, %{})
  end
```

**Comment by febeling** [comment]
Gotcha. Makes sense. Thanks!
