### ISSUE TITLE
Introduce proper API for returning the types and specs of a module

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7404]
Today they are hidden in a private module called `Kernel.Typespec`. My suggestion is to add `fetch_specs` and `fetch_types` that will mirror the return types of #7198.

**Comment by OvermindDL1** [comment]
o.O

You mean I don't need to be parsing the `*.beam` file source?!

**Comment by josevalim** [comment]
@OvermindDL1 you can still do that if you want the erlang typespecs. The goal here is to return them in the "Elixir" syntax. But now that I think about it... using the Erlang typespec may actually be better in some occasions and provides interoperability with ERlang.

Haha, hold on a sec, I am going back to the drawing board on this one.

**Comment by OvermindDL1** [comment]
Ah cool.  Yeah I'm grabbing the erlang typespecs in some cases for both some code generation and in my typed elixir experiments for trying to acquire information about remote calls and modules so you don't need to decorate absolutely everything you use.  :-)

**Comment by lukaszsamson** [comment]
For the record the code has been moved to internal module `Code.Typespec`. There are functions that return erlang type AST `Code.Typespec.fetch_(types|specs|callbacks)`. There are also `Code.Typespec.(types|specs)_to_quoted` that translate it to elixir AST. @josevalim are there plans to make those functions public?

**Comment by josevalim** [comment]
At the moment there are no plans in making them public. We are making the Elixir compiler smarter when it comes to types, so we may choose to surface that information instead of typespecs, which is why we haven't decided to make these public.
