### ISSUE TITLE
Unused functions given to @compile {:inline, ...} trigger compilation error

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7409]
We already need to validate inline as part of #5800. So we need to make sure we also remove unreachable entries.

**Comment by josevalim** [comment]
Alternatively we should give all functions to the Erlang pass. Since other calls such as `@dialyzer` may also list functions.

**Comment by josevalim** [comment]
@michalmuskala so this is quite tricky because of private macros. Private macros may use private functions and if we leave those in, then dialyzer will fail because of unused functions. However, if we keep those out, `@dialyzer` and `@compile` inline will fail because they are not available.

I am not sure about the best way to proceed but I am more inclined to remove them from `@compile {:inline, _}`, since we need to validate those anyway as part of #5800.

**Comment by michalmuskala** [comment]
Maybe if the problem is just dialyzer we should generate a `@dialyzer` annotation to skip the unused functions from analysis?
