### ISSUE TITLE
Improve coverall tool

### ISSUE THREAD

**Issue by yordis** [elixir-lang/elixir#7418]
- [ ] Improve the default HTML
- [ ] Add a navigation sidebar to the HTML
- [ ] Add an overview page

cc: @josevalim

**Comment by josevalim** [comment]
Thanks but this would be a todo list for Erlang/OTP, it is not actionable in this repository itself. They don't have an issues tracker, so it is best if you track it yourself. :)

**Comment by yordis** [comment]
@josevalim ohhhhh my bad, now I get it, let me go to Erlang repo then. Sorry about that!

**Comment by milmazz** [comment]
@yordis Please let me know if you want to do this in Erlang/OTP, I'm also interested in adding this feature to `cover`. I've already checked the `cover` code and it seems feasible to do this at least for one module or file.

**Comment by josevalim** [comment]
@milmazz @yordis :heart:

**Comment by yordis** [comment]
@milmazz I could definitely helps on the front end side, maybe I would love to know the data I will have available because I never did this before but I will start dig in for sure.

**Comment by milmazz** [comment]
@yordis That's great!, if you agree we can work together, I've already push some initial code [here](https://github.com/milmazz/otp/tree/improve-cover-html-pages), and it's working so far:

![screen shot 2018-03-04 at 11 15 00 am](https://user-images.githubusercontent.com/34700/36948266-c2453738-1f9d-11e8-80a4-d542a7dc25a2.png)

If you want to run some tests please check this [wiki page](https://github.com/erlang/otp/wiki/Running-tests). Also, feel free to improve the inline HTML/CSS code or adapt the current color palette.

BTW, I don't like a few things of the current implementation, such as embedding the CSS in the code (I just did it that way to have something quickly to show), but I could move that content into the `priv` directory and then read it from there. Also, I need to add some unit tests and check with @josevalim if he has any suggestion about the styling, the Erlang code in general, or another Erlang/OTP guideline that I'm missing.

**Comment by yordis** [comment]
@milmazz could we have something like EEx on ErLang?

I would write the files for you and as long as we agree on some kind of simple template engine it would be easier so from your side it would be just sending me the data to the template and I can work on the UI aspects of it.

**Comment by josevalim** [comment]
AFAIK we don't have something like EEx for Erlang/OTP and adding something like this to Erlang would probably be a major effort.

**Comment by yordis** [comment]
@milmazz well, just create a function that give me the file and the information I need and I keep writing into it, just dont put it inline so it is easier to centralize where the front end code will be.

**Comment by milmazz** [comment]
@yordis Now the [stylesheet contents](https://github.com/milmazz/otp/commit/aa3e83d0806911f724bc6a4eaad4ed300b740e5e) is in the `priv` directory, that change should ease a few things for you. Let me know what do you think.

**Comment by milmazz** [comment]
@yordis Sure, I'll do that tonight, now I have to go out for a few hours. In the meantime, feel free to change whatever you need.

**Comment by milmazz** [comment]
@yordis Just to let you know that I already move all the HTML layout/syntax into functions.

**Comment by milmazz** [comment]
@yordis ping? Please let me know if you need some help.

**Comment by yordis** [comment]
@milmazz sorry has been two really busy days,

btw, how do I need help with something. How did you ran specific module for the coverage? (I am not involve on ErLang ecosystem itself so learning the tool is a learning curve, sorry)

**Comment by OvermindDL1** [comment]
> AFAIK we don't have something like EEx for Erlang/OTP and adding something like this to Erlang would probably be a major effort.

There are a number of compiled template engines for Erlang, ones that I know of off hand (could be many more now):

Logicless:
https://github.com/mojombo/mustache.erl
https://github.com/filippo/sgte

Logicful:
https://github.com/erlydtl/erlydtl

\</offtopic>

**Comment by yordis** [comment]
@OvermindDL1 from that list, definitely Mustache because people are more exposed to it so it is easier.

I am not sure if OTP would like to include that on the repo.

**Comment by OvermindDL1** [comment]
I'd think that erlydtl would be more usual as it follows the django-style templates, which I've seen about *everywhere*.  ^.^

Still though, I'm not sure a template system is worth it overall for something as simple as this.

**Comment by josevalim** [comment]
I would keep it simple. Just improve the existing layouts, keeping about the same style for generating them.

**Comment by yordis** [comment]
@milmazz I got it working, I am working on it.

**Comment by milmazz** [comment]
@yodis Any updates about this?

**Comment by yordis** [comment]
@milmazz sorry mate, I am having a busy weeks, working on it right now.

I need to create this partial right after the `body`

```html
<ul id="menu">
  <li>
    <span class="cov <%= COVERAGE_LEVEL %>">
      <%= COVERAGE_PERCENTAGE  %>
    </span>
    <a href="<%=  FILE_NAME  %>" class="">
      <span class="dirname">
        <%= DIR_NAME/ %>
      </span>
      <span class="basename">
        <%= FILE_NAME.ex %>
      </span>
    </a>
  </li>
</ul>
```

COVERAGE_LEVEL: terrible,  low, medium, high
