### ISSUE TITLE
Keyword.merge/{2,3} behave inconsistently on kw1 having duplicate keys

### ISSUE THREAD

**Issue by am-kantox** [elixir-lang/elixir#7420]
### Environment

* Elixir & Erlang versions (elixir --version): **all up to `1.7-dev`**
* Operating system: **Linux**

### Current behavior

On merge, the first keyword discards the `N+1`th (and all others) values having the same key if and only the amount of values with the same key in the second keyword is `N > 0`:

```elixir
iex|1 ▶ {kw1, kw2} = {[a: 42, a: 3.14, b: :foo], [b: :zoo]}
iex|2 ▶ Keyword.merge(kw1, kw2, fn _k, _v1,v2->v2 end)     
# both `a`s are alive
#⇒ [a: 42, a: 3.14, b: :zoo]
iex|3 ▶ {kw1, kw2} = {[a: 42, a: 3.14, b: :foo], [a: 42, b: :zoo]}
iex|4 ▶ Keyword.merge(kw1, kw2, fn _k, _v1,v2->v2 end)            
# `a:42` is merged, `a:3.14` is _killed_
#⇒ [a: 42, b: :zoo]
iex|5 ▶ {kw1, kw2} = {[a: 42, a: 3.14, b: :foo], [a: 42, a: 3.14, b: :zoo]}
iex|6 ▶ Keyword.merge(kw1, kw2, fn _k, _v1,v2->v2 end)                     
# both `a`s are alive
#⇒ [a: 42, a: 3.14, b: :zoo]
```

### Expected behavior

```elixir
iex|3 ▶ {kw1, kw2} = {[a: 42, a: 3.14, b: 0], [a: 42]}
iex|4 ▶ Keyword.merge(kw1, kw2, fn _k, v1,v2->v1+v2 end)
#   ⇓ sum  ⇓ intact
#⇒ [a: 84, a: 3.14, b: 0]
```
Since `b` remains intact in the merged keyword, the second `a` should remain intact as well.

### Comments

Fix for the `Keyword.merge/3` would be easy: just `s/delete/delete_first/` [here](https://github.com/elixir-lang/elixir/blob/v1.6.2/lib/elixir/lib/keyword.ex#L741):

```diff
- do_merge(tail, acc, delete(rest, key), original, fun, keywords2)
+ do_merge(tail, acc, delete_first(rest, key), original, fun, keywords2)
```
but it breaks the `Keyword.merge(_, _, fn _, _, v2 -> v2 end) ≡ Keyword.merge(_, _)` rule, which is obviously wrong.

The proper fix seems to be to `reduce` remaining keys [here](https://github.com/elixir-lang/elixir/blob/v1.6.2/lib/elixir/lib/keyword.ex#L677) rather than just check for their existence.

**Comment by josevalim** [comment]
@am-kantox the algorithm is keeping the same amount of entries on the second list, which is the one being merged and has higher priority.

Here is a property:

```elixir
 check all list <- list_of({atom(:alphanumeric), integer()}) do
      double = list ++ list
      assert Keyword.merge(double, list) == list
      assert Keyword.merge(list, double) == double
      assert Keyword.merge(double, list, fn _, _, v2 -> v2 end) == list
      assert Keyword.merge(list, double, fn _, _, v2 -> v2 end) == double
    end
```

In a nutshell, in case of conflicts, we keep one matching entry for each element on the right hand side. The remaining on the left hand side are discarded.

**Comment by am-kantox** [comment]
I understand how it behaves currently.

I might be wrong, but I find it counter-intuitive that adding a single element into right-hand list _accidentally kills a bundle of elements from the left-hand list_. `Keyword` allows duplicate keys, which makes me think that the conflict is “the first against the first” and the remaining keys from the left-hand keyword _have no conflicts at all_, while they still get discarded [for no reason].

**Comment by josevalim** [comment]
Keyword allows duplicate entries but most of its API was meant to mirror the dict API unless explicitly stated so. To quote the docs:

> A keyword may have duplicated keys so it is not strictly a key-value store.
> However most of the functions in this module behave exactly as a dictionary so
> they work similarly to the functions you would find in the Map module.

In this case, it means that what goes on the right side does remove everything on the left side. The same way that `Keyword.put` removes all other entries, instead of simply prepending to the keyword list. :)
