### ISSUE TITLE
ExUnit @moduletag not working as described in the docs

### ISSUE THREAD

**Issue by bundacia** [elixir-lang/elixir#7423]
### Environment

```
% elixir --version
Erlang/OTP 20 [erts-9.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 19)
% uname -v
Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64
```

### Current behavior

When I use a `@moduletag` as described in the docs [here](https://hexdocs.pm/ex_unit/ExUnit.Case.html#module-reporting-tags) I get the following error:

```
== Compilation error in file test/moduledoc_test.exs ==
** (FunctionClauseError) no function clause matching in anonymous fn/2 in ExUnit.Case.normalize_tags/1
```

See the test file and full error here:
https://gist.github.com/bundacia/a58db9fe5aa4f3ce46285071f16ac1da

If I change the `@moduletag` to this, things work as expected:

```
@moduletag [[report: [:foo]]]
```

### Expected behavior
I expected the tests to compile and run when I used the syntax specified in the docs.

I'm not sure if this is a bug in the docs or if the docs are "right" and the code should be changed to match.

**Comment by bundacia** [comment]
Ahh, I see maybe this feature is going away? https://github.com/elixir-lang/elixir/commit/e0c112370ea1ca1c021ec69280faeda444690a2c#diff-da9b91caf1cd02e59ee50c01929a2058

**Comment by josevalim** [comment]
@bundacia they are not going away. the module doc needs to be defined after use ExUnit.Case, i will make sure it emits a good error message.

**Comment by bundacia** [comment]
Thanks!

**Comment by m13m** [comment]
@josevalim I want to take this where do I have to make changes to add the error message?

**Comment by whatyouhide** [comment]
@m13m I think you can start looking at where the exception is being raised now, that would be https://github.com/elixir-lang/elixir/blob/master/lib/ex_unit/lib/ex_unit/case.ex#L525.
