### ISSUE TITLE
Logger error in 1.6.2

### ISSUE THREAD

**Issue by binaryseed** [elixir-lang/elixir#7425]
Just upgraded to 1.6.2 but now I'm seeing some strange errors in my tests:

```
16:16:49.423 [error] :gen_event handler Logger.ErrorHandler installed at :error_logger
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Logger.Translator.sup_name/1
        (logger) lib/logger/translator.ex:199: Logger.Translator.sup_name(Endpoint.TaskSupervisor)
        (logger) lib/logger/translator.ex:111: Logger.Translator.translate_supervisor/2
        (logger) lib/logger/error_handler.ex:160: Logger.ErrorHandler.translate/6
        (logger) lib/logger/error_handler.ex:92: Logger.ErrorHandler.log_event/6
        (logger) lib/logger/error_handler.ex:31: Logger.ErrorHandler.handle_event/2
        (stdlib) gen_event.erl:573: :gen_event.server_update/4
        (stdlib) gen_event.erl:555: :gen_event.server_notify/4
        (stdlib) gen_event.erl:557: :gen_event.server_notify/4
        (stdlib) gen_event.erl:296: :gen_event.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

`Endpoint.TaskSupervisor` is a `Task.Supervisor` name

The definitions of `Logger.Translator.sup_name/1` don't include one that is _just_ a module name:
https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/translator.ex#L199

Versions:
```
Erlang/OTP 20 [erts-9.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.2 (compiled with OTP 20)
```

Any ideas what this could be? Or steps I could take to help track down the problem? Going back to `1.6.1` clears up the error...

Thanks!

**Comment by michalmuskala** [comment]
It looks to me like the problem is with the child progress reports that `DynamicSupervisor` is sending.

https://github.com/elixir-lang/elixir/blob/9ce15e568c20c471086b667f3561dd0de077620e/lib/elixir/lib/dynamic_supervisor.ex#L966-L974

It should probably translate `name` back into the erlang-style tuples.

**Comment by binaryseed** [comment]
Awesome, thanks for the quick fix!!
