### ISSUE TITLE
Logger calls containing interpolation raise an `ArgumentError` when the module is interpreted

### ISSUE THREAD

**Issue by KronicDeth** [elixir-lang/elixir#7426]
### Environment

* Elixir & Erlang versions (elixir --version): 
  ```
  Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

  Elixir 1.6.1 (compiled with OTP 20)
  ```
* Operating system:  macOS 10.13.3

### Current behavior

Logger calls containing interpolation raise an `ArgumentError` when the module calling `Logger` is interpreted.

Logger calls (such as `Logger.info`) that take an anonymous function that contains a string that performs interpolation cannot be debugged using [`:debugger`](http://erlang.org/doc/apps/debugger/debugger_chapter.html), [IntelliJ Elixir](https://github.com/KronicDeth/intellij-elixir/tree/1ecceea4b5bec156b644dd695145b787207b934b) or the [Elixir Language Server](https://github.com/JakeBecker/elixir-ls/tree/cb94e00bcfd9128dbae485812c46dc0740aac21d) that all use the `:int` OTP module
to interpret modules to perform line-based debugging.  (This bug was first spotted using the IntelliJ Elixir debugger and then reproduced using just `:int.ni` used by all the named debuggers.) 

1. `git clone git@github.com:KronicDeth/interpret_logger_call.git`
2. `cd interpret_logger_call`
3. Run `mix test` without `:int` to see the code works fine when not debugging.
    ```
     ..
     22:22:40.708 [info]  1
     .
     22:22:40.708 [info]  1
    .

     Finished in 0.02 seconds
    4 tests, 0 failures
    ```
4. Run `INT=1 mix test` with `:int` to see the code raises an exception when debugging.
    ```
    ..
    22:22:47.931 [info]  1


   1) test log_interpolation/0 (InterpretLoggerCallTest)
      test/interpret_logger_call_test.exs:18
      ** (ArgumentError) argument error
      stacktrace:
        (interpret_logger_call) Elixir.InterpretLoggerCall.erl:17: anonymous fn/4 in InterpretLoggerCall.log_interpolation/0
        (interpret_logger_call) Elixir.InterpretLoggerCall.erl:17: InterpretLoggerCall.log_interpolation/0

     .

    Finished in 0.05 seconds
    4 tests, 1 failure
    ```

The weird `Elixir.InterpretLoggerCall.erl` name is a side-effect of how `:int` works.  It assumes that `<MODULE_NAME>.erl` is the location of source because `:int` only understands Erlang Abstract Code and assumes everything is Erlang.  In Elixir 1.6, `:int` is using the Erlang Abstract Code that Elixir's `Dbgi` chunk backend derives from the Elixir AST for backwards compatibility with tools, like `:int` that only understand the old `Abst` chunk.

Note that the current tests in the [reproduction repository](https://github.com/KronicDeth/interpret_logger_call) test 4 cases.

```elixir
defmodule InterpretLoggerCall do
  require Logger

  def fn_interpolation do
    (fn -> a = 1; "#{a}" end).()

    :ok
  end

  def fn_to_string do
    (fn -> a = 1; to_string(a) end).()

    :ok
  end

  def log_interpolation do
    Logger.info(fn -> a = 1; "#{a}" end)

    :ok
  end

  def log_to_string do
    Logger.info(fn -> a = 1; to_string(a) end)

    :ok
  end
end
```

1. Interpolation in an `fn` that is called immediately
2. `to_string` in an `fn` that is called immediately
3. Interpolation in an `fn` that is called by `Logger.info`
4. `to_string` in an `fn` that is called by `Logger.info`

Only (3) raises an exception.

### Expected behavior

The `Logger.<LEVEL>` calls should succeed whether the calling module is interpreted or not.

**Comment by josevalim** [comment]
You do the best bug reports, thank you @KronicDeth! I will take a look at it today. The four steps you did are great. My next step is to check if 1 and 2, when generated by a macro, changes anything. :)

**Comment by josevalim** [comment]
Ok, the plot thickens. If I add this code:

```elixir
defmodule O do
  def bare_log(_info, fun) do
    fun.()
  end
end
```

And change `Logger` to `O` in 3 and 4, 3 continues to fail. However, both will pass if I also interpret `O`. This rules out `Logger`. Now I am looking into the binary bit. It may be a debugger bug after all.

**Comment by josevalim** [comment]
New minimal Elixir case:

```elixir
defmodule O do
  def bare_log(_info, fun) do
    fun.()
  end
end

defmodule InterpretLoggerCall do
  def fn_interpolation do
    O.bare_log(:info, fn -> <<String.Chars.to_string(1)::binary>> end)
    :ok
  end
end
```

**Comment by michalmuskala** [comment]
Interesting. Can you reproduce it with erlang?

**Comment by josevalim** [comment]
Ok, I was able to reduce it further and convert it to Erlang:

```erlang
-module(fn_int).
-export([call/0]).
call() -> <<(fn_bin:to_binary(1))/binary>>.
```

```erlang
-module(fn_bin).
-export([to_binary/1]).
to_binary(Integer) -> integer_to_binary(Integer).
```

If I had to guess, the argument error is coming from the fact interpreter is trying to put the result of the call into the binary but forgetting the binary modifier.

**Comment by josevalim** [comment]
I have a fix. :)

**Comment by josevalim** [comment]
Done! https://github.com/erlang/otp/pull/1741
