### ISSUE TITLE
Unexpected :timed_out message on failed compilation using Mix.Task.compile/2 with "--return-errors" option

### ISSUE THREAD

**Issue by allansson** [elixir-lang/elixir#7428]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.0] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10]

Elixir 1.6.2 (compiled with OTP 19)
```
* Operating system: Windows 10 x64

### Current behavior

When compiling an mix project with compilation errors using `Mix.Task.run("compile", ["--return-errors"])` a `:timed_out` message is sent to the process invoking the task.

To reproduce, create a new mix project and make sure the code does not compile, e.g. by trying to reference a variable/function which does not exist, then modify and paste the following in an `iex`-session:

```elixir
defmodule SSCCE do
  def run() do
    File.cd!("<DIRECTORY TO FAILING MIX PROJECT>")
    Mix.Task.clear()
    Mix.Task.run("compile", ["--return-errors"])

    receive do
      {:timed_out, pid} ->
        IO.puts("Unexpected timeout received from #{inspect(pid)}")
    after
      60_000 ->
        IO.puts("Works on my computer!")
    end
  end
end

SSCCE.run()

```

Eventually, the following message should be printed:

```
Unexpected timeout received from #PID<0.233.0>
```

### Expected behavior

All scheduled timeouts should be cancelled  after compilation has finished and no `:timed_out` messages should be sent.

### Investigation

The `:timed_out` message is sent from a `Process.send_after` scheduled by [`Kernel.ParallellCompiler`](https://github.com/elixir-lang/elixir/blob/a044559e8203e1a2b321fdcad4e66258c0d2ff5b/lib/elixir/lib/kernel/parallel_compiler.ex#L218). The timeout is cancelled in [`wait_for_messages`](https://github.com/elixir-lang/elixir/blob/a044559e8203e1a2b321fdcad4e66258c0d2ff5b/lib/elixir/lib/kernel/parallel_compiler.ex#L283), but one clause seem to be missing the call to cancel the timeout: [the final `{:file_done, _}` clause](https://github.com/elixir-lang/elixir/blob/a044559e8203e1a2b321fdcad4e66258c0d2ff5b/lib/elixir/lib/kernel/parallel_compiler.ex#L360). This clause appears to be in charge of handling compilation errors, which explains why the problem only appears to occur when compilation fails.

This has probably not a huge issue since the task is usually not executed with the "--return-errors" option. It could have adverse effects on tools relying on "--return-errors", such as [elixir-ls](https://github.com/JakeBecker/elixir-ls).

**Comment by whatyouhide** [comment]
@josevalim I think we can close this after #7429.

**Comment by allansson** [comment]
I'll close it since it has already been merged. Thanks for such speedy processing!
