### ISSUE TITLE
Guard clauses allow simple bindings as expressions

### ISSUE THREAD

**Issue by zachdaniel** [elixir-lang/elixir#7430]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.6.1 (compiled with OTP 20)
* Operating system: Mac OSX

### Current behavior

A way in which this could be very confusing is if someone thought it worked w/ truthiness.
```elixir
value = 1

case value do
  a when a -> "here"
  _ -> "there"
end

"there"
```
vs
```elixir
value2 = true

case value2 do
  a when a -> "here"
  _ -> "there"
end

"here"
```

### Expected behavior

I think this should either evaluate truthiness, or fail if the expression is just a single value that isn't guaranteed to evaluate to a boolean expression.

**Comment by zachdaniel** [comment]
@michalmuskala I totally agree, but when you use an expression that might not yield a boolean value (like `when x && y`) you are warned about an invalid expression, and I think an expression in the form of `{:a, [], Elixir}` or `{:^, [], [{:a, [], Elixir}]}` should be included in that validation.

**Comment by josevalim** [comment]
@zachdaniel the issue is that you could have `{:ok, bool} when bool` and that is completely valid. `when ^x` already fails accordingly though. Thanks for the report but I don't think there is anything to fix here. :)

**Comment by zachdaniel** [comment]
I still think that it should require you to say `{:ok, bool} when bool == true`. No big deal though. Thanks for your time :)

**Comment by OvermindDL1** [comment]
I'd think this is something that dialyzer 'should' catch (and if not then it should be fixed)?

**Comment by bschaeffer** [comment]
@zachdaniel we have `{:ok, bool = true}` for that
