### ISSUE TITLE
Improve unhandled operator error message

### ISSUE THREAD

**Issue by nsuchy** [elixir-lang/elixir#7440]
**Code:**
```
defmodule Parallel do
def pmap(collection, fun) do
collection
|> Enum.map(&spam_process(&1, self, fun))
|> Enum.map(&await/1)
end

defp spawn_process(item, parent, fun) do
spawn_link fn ->
send parent, {self, fun.(item)}
end
end

defp await(pid) do
recieve do
{^pid, result} -> result
end
end

end
```

The issue is that I spelled the word `receive` wrong.

**Error Message:**
```
iex processes.ex
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

warning: variable "self" does not exist and is being expanded to "self()", please use parentheses to remove the ambiguity or change the variable name
processes.ex:4

warning: variable "self" does not exist and is being expanded to "self()", please use parentheses to remove the ambiguity or change the variable name
processes.ex:10

** (CompileError) processes.ex:16: unhandled operator ->
(stdlib) lists.erl:1354: :lists.mapfoldl/3
(stdlib) lists.erl:1355: :lists.mapfoldl/3
```

The above error message talks about line 16 having an unhandled operator however the error isn't clear about the problem. Could this be improved upon?

**Comment by josevalim** [comment]
Good call. I think it can be improved upon if we track the caller we are expanding and include that in the error message. Although not sure how to do so without adding new fields to Macro.Env.

**Comment by nsuchy** [comment]
@josevalim Thanks for taking a look at this - I'm new to Elixir and am not sure of alternative error text however I hope you guys can work towards a solution :)

**Comment by yordis** [comment]
@josevalim do you have any ideas on how would like to fix this?

**Comment by josevalim** [comment]
No, not yet.

**Comment by ggcampinho** [comment]
In both cases, the operators are expanded as local functions, maybe we can check if the arguments of the local function contain the `->` before expanding them and throw an error like `Invalid clauses with -> operator passed to local function <name>. Clauses are valid only for case, cond, receive, catch, rescue and fn.`, and on the cases where the <name> matches throw an error showing how is the proper syntax. If this makes sense, I'm happy to do it.

**Comment by josevalim** [comment]
@ggcampinho yes, that's probably the simplest fix. :+1:

My suggestion though is to traverse only the last argument, looking up for two element tuples where the first element is an atom and the second element is the `->` AST. We don't need to recurse or go deeper than that, which would keep it still cheap. :)
