### ISSUE TITLE
__DIR__ does not match documentation when used in mix config file

### ISSUE THREAD

**Issue by Nicd** [elixir-lang/elixir#7448]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6.2
* Operating system: macOS (probably irrelevant)

### Current behavior

If you use `__DIR__` in a normal project's mix config file (in the `config/`) directory, it will be replaced with `"config"`, a relative path. But the Elixir documentation states:

> Returns the absolute path of the directory of the current file as a binary.

For example:

```elixir
# In config/config.exs
config :dir_test, dir: __DIR__

iex(1)> Application.get_env(:dir_test, :dir)
"config"
```

### Expected behavior

```elixir
# In config/config.exs
config :dir_test, dir: __DIR__

iex(1)> Application.get_env(:dir_test, :dir)
"/Users/nicd/dir_test/config"
```

or document that in config files it returns a different value.

**Comment by josevalim** [comment]
It is a Mix bug but should likely be fixed in elixir because we are not expanding the file passed as option during evaluation.

**Comment by michalmuskala** [comment]
I tried looking into this and always expanding the path in here: https://github.com/elixir-lang/elixir/blob/d0378be1e7f2ad934897a76aa8029affd9902686/lib/elixir/src/elixir.erl#L184-L187

but I'm not sure that's the right thing to do. This would mean that passing `Code.eval_string(..., file: "foo.ex")` would always expand the name relative to cwd, but that might not be correct.

I think this should be done in mix specifically when evaluating config files.

**Comment by josevalim** [comment]
Good point. Agreed.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by josevalim** [comment]
Fixed in master.
