### ISSUE TITLE
Umbrella application: conflicting `only` on dependency

### ISSUE THREAD

**Issue by stevedomin** [elixir-lang/elixir#7458]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6.3
* Operating system: Alpine Linux

### Current behavior

* In an umbrella application with two sub apps, specify a dependency (in my case Swoosh) like this:
  * app_1: `{:swoosh, "~> 0.13"}`
  * app_2: `{:swoosh, "~> 0.13", only: [:dev, :test]}`
* When I run `mix do deps.get, deps.compile, compile` on my Mac (macOS 10.12.6), no issues at all.
* However, when ran into a Docker container (`elixir:alpine`), I get the following error

```
Could not compile :swoosh, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
```

* If I remove the `only` specification inside `app_2`'s dependencies, everything runs normally again.

### Expected behavior

* Option 1: Mix runs normally, "ignoring" the `only` in `app_2`. (That's what seems to happen on Mac).
* Option 2: Mix warns me that this `only` can't be taken into account.

**Comment by josevalim** [comment]
Can you please confirm that both machines are on the same Elixir and Erlang
versions and let us know the versions?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by stevedomin** [comment]
### Local environment

Elixir: **1.6.3**
Erlang: **20.2.4**
OS: **macOS 12.10.6**

### Docker container

Elixir: **1.6.3**
Erlang: **20.3.1**
OS: **Alpine 3.7**

I will upgrade both Erlang and Elixir and report back.

**Comment by josevalim** [comment]
@stevedomin we have released Elixir v1.6.4 with compatibility fixes for Erlang 20.3 but I don't think it is supposed to make a difference in this case but please try it out.

We are not meant to have differences between those OSes at all, I can't recall anywhere where we treat darwin differently from linux. So if the issue still persists, we would like to ask a way that reproduces the issue. Thank you!

**Comment by josevalim** [comment]
Ping. :)

**Comment by stevedomin** [comment]
Sorry @josevalim, been busy. Here is  a repo with a repro case: https://github.com/stevedomin/umbrella_conflict

**Comment by aquarhead** [comment]
> When I run mix do deps.get, deps.compile, compile on my Mac (macOS 10.12.6), no issues at all.

I can repro the same error in shell (on macOS 10.13) as in your docker run, just need to set `MIX_ENV`

```
◊ MIX_ENV=prod mix deps.compile
Could not compile :swoosh, no "mix.exs", "rebar.config" or "Makefile" (pass :compile as an option to customize compilation, set it to "false" to do nothing)
```

My Elixir & Erlang version:

```
◊ elixir --version
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.6.6 (compiled with OTP 20)
```

**Comment by stevedomin** [comment]
Thanks for fixing this @josevalim!
