### ISSUE TITLE
How about replace argument of 'nth' with 'step' or 'interval'?

### ISSUE THREAD

**Issue by jung-hunsoo** [elixir-lang/elixir#7463]
The `Enum.map_every/3` function seems useful in some cases, but the API document was not accustomed to. Reason for me was that `nth` is too ambiguous. So I suggest considering to replace with more descriptive word like `step` or `interval`.

I have a strong belief that Elixir will be more popular when developers feel easy to settle down.

https://github.com/elixir-lang/elixir/blob/c107a2fe2623d11d132cdfeefbb7370abd44f85c/lib/elixir/lib/enum.ex#L1335

**Comment by josevalim** [comment]
Thanks @jung-hunsoo. As asked on the opening issues tmplate, please move discussions to the mailing list.
