### ISSUE TITLE
Elixir install test failure Ubuntu 14.04

### ISSUE THREAD

**Issue by han-so1omon** [elixir-lang/elixir#7465]
### Environment
Elixir: Main branch as of yesterday
Erlang OTP: version 21

According to install guide (https://elixir-lang.org/install.html#compiling-from-source-unix-and-mingw), Erlang OTP 18+ and path to binaries are the only necessary components.

### Current behavior
Useful temporary files not created during testing. No behavioral change with or without `sudo` in `make test` command. Current user is owner of current directory.

<code>
==> elixir (compile)
bin/elixir bin/mix format --check-formatted
==> elixir (eunit)
  All 197 tests passed.

==> elixir (exunit)
Excluding tags: [windows: true]

...........................................................................................................................................................................................................................................................................................................................................................

  1) test chgrp! with failure (FileTest)
     test/elixir/file_test.exs:1910
     Wrong message for File.Error
     expected:
       ~r/could not change group for "\/home\/eric\/Programs\/elixir\/lib\/elixir\/tmp\/tmp_test.txt": no such file or directory/
     actual:
       "could not change group for \"/home/eric/Programs/elixir/lib/elixir/tmp/tmp_test.txt\": bad argument"
     code: assert_raise File.Error, message, fn ->
     stacktrace:
       test/elixir/file_test.exs:1916: (test)

............

  2) test chgrp with failure (FileTest)
     test/elixir/file_test.exs:1903
     Assertion with == failed
     code:  assert File.chgrp(fixture, 1) == {:error, :enoent}
     left:  {:error, :badarg}
     right: {:error, :enoent}
     stacktrace:
       test/elixir/file_test.exs:1907: (test)

.....

  3) test chown! with failure (FileTest)
     test/elixir/file_test.exs:1928
     Wrong message for File.Error
     expected:
       ~r/could not change owner for "\/home\/eric\/Programs\/elixir\/lib\/elixir\/tmp\/tmp_test.txt": no such file or directory/
     actual:
       "could not change owner for \"/home/eric/Programs/elixir/lib/elixir/tmp/tmp_test.txt\": bad argument"
     code: assert_raise File.Error, message, fn ->
     stacktrace:
       test/elixir/file_test.exs:1934: (test)

  4) test chown with failure (FileTest)
     test/elixir/file_test.exs:1921
     Assertion with == failed
     code:  assert File.chown(fixture, 1) == {:error, :enoent}
     left:  {:error, :badarg}
     right: {:error, :enoent}
     stacktrace:
       test/elixir/file_test.exs:1925: (test)

...................................................................................................................................................

Finished in 148.5 seconds (83.8s on load, 64.6s on tests)
1387 doctests, 2921 tests, 4 failures, 7 excluded

Randomized with seed 648123
</code>

### Expected behavior
Presumably the temporary files mentioned are supposed to be created. Interesting that this fails with `chown` and `chgrp` calls. However, failure is not due to permissions, but rather due to that the file referenced doesn't exist.
`erl` works fine and shows correct OTP version.

Edit:
Formatting + note.
Note: I have no experience with Erlang/Elixir thusfar.

**Comment by michalmuskala** [comment]
It seems you're running under the unstable OTP 21 - we don't commit to stability of Elixir on unreleased OTP versions. We'll look into fixing the issues once the RCs for OTP 21 are released which should be in early May.

I recommend using the latest stable release of OTP, which would be 20.3.

**Comment by han-so1omon** [comment]
Brilliant! Thank you

**Comment by josevalim** [comment]
@han-so1omon In any case, I went ahead and reported the issue here, as I could reproduce it locally: https://bugs.erlang.org/browse/ERL-589 :)
