### ISSUE TITLE
Calling exit/1 inside the shell process does not kill it

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#7468]
### Environment

* Elixir 1.6.4 (compiled with OTP 20)
* macOS 10.12.6

### Current behavior

Calling `exit/1` in the shell does not restart a new shell.

Example 1:

```
Interactive Elixir (1.6.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> p=self()
#PID<0.84.0>
iex(2)> Process.alive?(p)
true
iex(3)> exit(:bad)
** (exit) :bad

iex(3)> Process.alive?(p)
true
iex(4)>
```

Example 2:

```
Interactive Elixir (1.6.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> p=self()
#PID<0.84.0>
iex(2)> :erlang.is_process_alive(p)
true
iex(3)> exit(:bad)
** (exit) :bad

iex(3)> :erlang.is_process_alive(p)
true
iex(4)>
```

### Expected behavior

The expected behavior is that of Erlang's shell:

```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V9.3  (abort with ^G)
1> P=self().
<0.60.0>
2> erlang:is_process_alive(P).
true
3> exit(bad).
** exception exit: bad
4> erlang:is_process_alive(P).
false
5> 
```

**Comment by josevalim** [comment]
We explicitly chose to handle such exits because discarding the whole shell context when you do a GenServer call to the wrong name is not the most pleasant experience. :)

However, exits from links do terminate the shell.

**Comment by mguimas** [comment]
Why did you not choose instead to restore the shell context in a new shell process, and so, keep Elixir's shell consistent with that of Erlang? What problems would this other option entail that made you decide to break consistency with Erlang?

**Comment by josevalim** [comment]
Because it is not about variables, it is about other processes, messages, link, monitors that may have been established by the process and they are all now all lost and those cannot simply be restored.

**Comment by mguimas** [comment]
What "shell context" are you talking here? For example, in Erlang, when exiting in the shell process, the state of variables prior to the exit is restored in the new process:

```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V9.3  (abort with ^G)
1> A=90.
90
2> self().
<0.60.0>
3> exit(bad).
** exception exit: bad
4> self().
<0.64.0>
5> A.
90
6> gen_server:call(no_server, "hello").
** exception exit: {noproc,{gen_server,call,[no_server,"hello"]}}
     in function  gen_server:call/2 (gen_server.erl, line 206)
7> self().
<0.68.0>
8> A.
90
9>
```

**Comment by mguimas** [comment]
OK, I understood know ... that is a lot of context indeed.

I don't know if this Elixir's shell behavior is clearly documented in the shell's docs, but it should.

Thanks.
