### ISSUE TITLE
Formatter converting sum/subtraction to a function

### ISSUE THREAD

**Issue by 4knahs** [elixir-lang/elixir#7469]
When formatting a sum/subtraction where there is no space between the operator (+) and the second parameter the outcome varies depending if both parameters are integers or if one is a variable.

### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.6.1 (compiled with OTP 20)
* Operating system: Ubuntu 17.04

### Current behavior

Before mix format

```
a = 1
b = a +1
c = 1 +1
```

After mix format

```
a = 1
b = a(+1)
c = 1 + 1
```

### Expected behavior

```
a = 1
b = a + 1
c = 1 + 1
```

After all, while probably not a nice coding practice it is supported by the language:

```
iex(1)> 1 +1
2
```

**Comment by 4knahs** [comment]
This is because of the ambiguity with functions without parenthesis, iex will also throw a "please use explicit parentheses or even spaces"

**Comment by josevalim** [comment]
Yes, it is also not valid code (it won't compile).

**Comment by michalmuskala** [comment]
Should formatter fail in such case instead of emitting something different?

**Comment by josevalim** [comment]
@michalmuskala the problem is that it requires semantic understanding (which variables are defined) to know that it will fail. If there are no variables defined, then it is always a function call, which is what the formatter chooses.
