### ISSUE TITLE
Formatter configuration: omit parens for functions with no arguments

### ISSUE THREAD

**Issue by IcyEagle** [elixir-lang/elixir#7479]
Is it possible to do so?

For some situations it makes sense to omit parens (when function body is simple and, say, returns constant value). By the way there are some "best practices" where this approach is used as well.

Thanks!

**Comment by josevalim** [comment]
It is not possible and even the Elixir compiler will warn in those cases.

**Comment by OvermindDL1** [comment]
For note, this would change the AST, which could (would) easily break a variety of Macro's, that is why the formatter will absolutely not change the AST.  :-)
