### ISSUE TITLE
Erlang error for ++ operator inside match

### ISSUE THREAD

**Issue by ggcampinho** [elixir-lang/elixir#7485]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.7.0-dev (8c05bb0) (compiled with OTP 20)
```
* Operating system: MacOS High Sierra 10.13.3

### Current behavior

```
iex(1)> "a" ++ "b" = "ab"
** (ErlangError) Erlang error: {:illegal_pattern, {:op, 1, :++, {:bin, 0, [{:bin_element, 0, {:string, 0, 'a'}, :default, :default}]}, {:bin, 0, [{:bin_element, 0, {:string, 0, 'b'}, :default, :default}]}}}
iex(1)> "a" ++ "b"
** (ArgumentError) argument error
    :erlang.++("a", "b")
```

### Expected behavior

I believe it should give an error similar to the <> operator:
```
iex(1)> "a" ++ "b" = "ab"
** (ArgumentError) expected list argument in <> operator but got: "a"
iex(1)> "a" ++ "b"
** (ArgumentError) expected list argument in <> operator but got: "a"
```

If the issue makes sense, I would be glad to fix it.

**Comment by michalmuskala** [comment]
Yes, we should check the left side of the `++` operator in matches to be a literal list.

**Comment by josevalim** [comment]
Yes, we should check only the left side though because this is allowed:

```elixir
iex(3)> [2] ++ 1 == [2 | 1]
true
```

In this particular case, I think the implementation should be all in the compiler, because we already consider `++` to be something especial allowed in matches (similar to the unary operators `+` and `-`), even though those are not special forms.
