### ISSUE TITLE
create map with multiple ways

### ISSUE THREAD

**Issue by husafwan** [elixir-lang/elixir#7497]
Elixir 1.6.1
Erlang/OTP 20

problem:
if you create map with this way: %{p: "x" , :a =>  "b"} will give you syntax error

if you create map with this way: %{ :a =>  "b" , p: "x" } working fine!

Note: i don't know if this issue or not

**Comment by whatyouhide** [comment]
Hey @husafwan, the **keyword** syntax can only be used at the end of lists, maps, tuples. This is not an issue, but documented and expected behaviour. You can read more about it in the [Syntax reference](https://hexdocs.pm/elixir/syntax-reference.html) page in the documentation.

Thanks! 💟

**Comment by husafwan** [comment]
if i understand you 
this style should not work: %{a: "x" , b: "y"}
but its working fine

**Comment by whatyouhide** [comment]
@husafwan maps support the keyword syntactic sugar (`foo: "something"`) only at the end of the map, but if there are no key-value pairs in the map where the key is not an atom, then everywhere in the map is the "end of the map", so you can have maps where all key-value pairs use the syntactic sugar. As I pointed, this is documented in the "Syntax reference" page in the documentation. For example, [here](https://hexdocs.pm/elixir/syntax-reference.html#maps-and-keyword-lists).

**Comment by husafwan** [comment]
Thank you @whatyouhide
