### ISSUE TITLE
@impl documentation does not mention setting @doc false

### ISSUE THREAD

**Issue by bblaszkow06** [elixir-lang/elixir#7505]
As stated in [here](https://github.com/elixir-lang/elixir/issues/5734), using  `@impl true` on callback implementation adds `@doc false` unless the documentation has been given (and it seems to be done here: https://github.com/elixir-lang/elixir/blob/ae6fb479b5f9600a7dea1daba4995d27407e793f/lib/elixir/lib/module.ex#L1287)

Yet, the documentation for neither `@impl` nor `@doc` mentions that fact. So unless, of course, that's intended for some reason, the docs should point that out, letting know that this:
```elixir
@doc false
@impl true
def foo()
```
can simply become:
```elixir
@impl true
def foo()
```

**Comment by fertapric** [comment]
Maybe some of the documentation of the official [release of Elixir v1.5](https://elixir-lang.org/blog/2017/07/25/elixir-v1-5-0-released/) can be included in the [`Module`](https://hexdocs.pm/elixir/Module.html#content) documentation.

> Readability of the code is increased, as it is now clear which functions are part of your API and which ones are callback implementations. To reinforce this idea, `@impl true` automatically marks the function as `@doc false`, disabling documentation unless `@doc` is explicitly set
