### ISSUE TITLE
Dialyzer issue introduced in for expansion of Elixir 1.6.4

### ISSUE THREAD

**Issue by MaartenFaddegon** [elixir-lang/elixir#7508]
With 

```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.4 (compiled with OTP 19)
```

the following example code

```
  def f() do
    for a <- [1,2,3], into: <<>>, do: <<a::big-integer-size(8)>>
  end
```
seems to expand to code for which Dialyzer issues the following warnings:
```
lib/ex16.ex:20: The variable _@1 can never match since previous clauses completely covered the type <<_:8>>
lib/ex16.ex:20: Cons will produce an improper list since its 2nd argument is <<_:8>>
```

With earlier versions of Elixir no warnings were issued for the code.

**Comment by josevalim** [comment]
Thanks! We will fix it and ship a new elixir version at some point.

**Comment by MaartenFaddegon** [comment]
Minimal project to reproduce the issue:

[ex16.tar.gz](https://github.com/elixir-lang/elixir/files/1855849/ex16.tar.gz)
