### ISSUE TITLE
Time.iso_from8601 argument format "hh:mm"

### ISSUE THREAD

**Issue by kobatako** [elixir-lang/elixir#7511]
Hi.

In the Time.from_iso8601 function, the argument "hh: mm: ss" is valid, but the argument "hh: mm" is invalid.

```
iex(1)>Time.from_iso8601("10:30:00")
{:ok, ~T[10:30:00]}
iex(2)>Time.from_iso8601("10:30")
{:error, :invalid_format}
```

Will you add the function to support Time.from_iso8601 function with argument "hh: mm" format?

```
iex(1)>Time.from_iso8601("10:30:00")
{:ok, ~T[10:30:00]}
iex(2)>Time.from_iso8601("10:30")
{:ok, ~T[10:30:00]}
```

**Comment by josevalim** [comment]
Hi @kobatako! 👋 

Although ISO 8601 does support reduced accuracy, as you proposed, it also says this must be agreed between parties. We don't want to encode this agreement by default on all users of the library so, at the moment, we have no plans to support the representations with reduced accuracy.

Thank you!

**Comment by kobatako** [comment]
Thank you for your reply!!

OK, I understood reduced accuracy ISO 8601.
