### ISSUE TITLE
Improve warning for grouped clauses

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7512]
We should say that Foo and Bar have different names. When they have the same name, we should say they expect a different number of arguments (i.e. arity).

https://elixirforum.com/t/compiler-warning-clauses-for-the-same-def-should-be-grouped-together/13366/2

**Comment by zacck** [comment]
@josevalim  any hints for a first-time contributor to go hunting for this?

**Comment by josevalim** [comment]
@zacck this is where it is raised: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_def.erl#L399

I would say the current warning is good for functions of different names but probably not enough for only when the arity changes.

**Comment by aaruel** [comment]
Would this be a change in the wording of the existing warning or a separate warning?

**Comment by josevalim** [comment]
A separate warning.

**Comment by zacck** [comment]
@josevalim so I am trying to find out where the `format_error` function is called?

**Comment by zacck** [comment]
Hey @josevalim  I have given it a few bashes and some trials with a bit of effort and help, here is what I came up with 
-  match for the condition
```erlang
check_valid_clause(Meta, File, Name, Arity, Kind, Set, StoredMeta, StoredFile) ->
  case ets:lookup_element(Set, ?last_def, 2) of
    none -> ok;
    {Name, Arity} -> ok; # name and arity here match with arguments 3 lines up
    {Name, OtherArity} -> 
       Relative = elixir_utils:relative_to_cwd(StoredFile),
       elixir_errors:form_warn(Meta, File, ?MODULE,
       {grouped_clause, {Kind, Name, Arity, OtherArity, ?line(StoredMeta), Relative}})
    _ ->
      Relative = elixir_utils:relative_to_cwd(StoredFile),
      elixir_errors:form_warn(Meta, File, ?MODULE,
        {ungrouped_clause, {Kind, Name, Arity, ?line(StoredMeta), Relative}})
  end.
```

- throw this as the issue 
```erlang
format_error({grouped_clause, {Kind, Name, Arity, OtherArity, OrigLine, OrigFile}}) ->
  io_lib:format("clauses with the same name should be grouped together, ~ts ~ts/~B was previously defined (~ts:~B)",
```
Would this suffice? 

Also I am finding it a little difficult to locate the tests for the check valid clause function any pointers to where these would be?
