### ISSUE TITLE
mix deps.compile unexpectedly compiles apps in umbrella

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#7519]
## Observed behaviour

Create a dummy umbrella:
```
$ mix new --umbrella foo_umbrella
$ cd foo_umbrella/apps
$ mix new foo_app
```

Now in the umbrella root (`foo_umbrella/`) run the following:
```
$ mix deps.compile
==> foo_app
Compiling 1 file (.ex)
Generated foo_app app

$ mix deps.compile
<no output>

$ touch apps/foo_app/mix.exs
$ mix deps.compile
==> foo_app
Compiling 1 file (.ex)
Generated foo_app app
```

## Expected behaviour

`mix deps.compile` must not compile apps within the umbrella.

**Comment by alco** [comment]
I've noticed that `Mix.Dep.loaded([])` includes `%Mix.Dep{app: :foo_app, ...}` when it is invoked in the project root. I don't know if it's expected but looks like it could be the culprit here.

**Comment by josevalim** [comment]
Yes, this is by design. Each umbrella child is considered to be a dependency of the umbrella.

**Comment by josevalim** [comment]
@AndrewDryga you want to compile the dependencies but not the umbrella children? or only the umbrella children?

**Comment by AndrewDryga** [comment]
@josevalim dependencies without the umbrella children. So that I can cache compiled dependencies and don't spend time compiling it on each CI job execution. Alex had an exactly same use case.

**Comment by josevalim** [comment]
@AndrewDryga in this case a pull request that adds a `--skip-umbrella-children` to `mix deps.compile` would be welcome.

**Comment by wojtekmach** [comment]
@AndrewDryga what you can also do in the meantime is cache the entire `_build/test` (including your apps'  beam) and `mix compile --force` when building the project. It won't recompile deps, unless they've changed but make sure your code is always recompiled from scratch.
