### ISSUE TITLE
mix does not support ipv6

### ISSUE THREAD

**Issue by kbespalov** [elixir-lang/elixir#7522]
### Environment

* Elixir & Erlang versions (elixir --version):  1.6.3-1
* Operating system: Ubuntu 16.04

### Current behavior

If mix is trying to perform http request to a domain that has **only** AAAA record (ipv6) using `read_httpc(path)`, then it fails with:

```
mix local.xxx
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'<domain here>', 443}},
 {:inet, [:inet], :nxdomain}]}
```

As you can see, the root cause of the issue is usage of default  **:inet** (ipv4) socket family instead of **inet6fb4** despite the fact that a domain has only AAAA record.

I have no experience with erlang and elixir, but looks like the following  option should be set:

`httpc.set_option(:ipfamily, :inet6fb4, :mix)`

in case of ipv6. Otherwise it will not work, because of default is always  **:inet** .

You can easy reproduce ipv6 only environment and the issue by adjusting `/etc/hosts` :

```
/etc/hosts

::1/128  iloveelixir.com
```

```
read_httpc(iloveelixir.com)
```

### Expected behavior

`read_httpc(path)` should support ipv6.

**Comment by eksperimental** [comment]
I guess this one can be closed

**Comment by genofire** [comment]
and open again with: https://github.com/elixir-lang/elixir/commit/f63e7200a690877551a2cb83b96c8aac242661aa
