### ISSUE TITLE
`mix compile` error with invalid or empty `apps_path`

### ISSUE THREAD

**Issue by talentdeficit** [elixir-lang/elixir#7531]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.4 (compiled with OTP 20)
```
* Operating system: 
```
17.0.4 Darwin
```

### Current behavior

```
$ cat mix.exs
defmodule Ask.Mixfile do
  use Mix.Project

  def project do
    [
      app: :apps_path_bug,
      version: "1.0.0",
      apps_path: "this_path_does_not_exist_or_is_empty"
    ]
  end
end
```

```
$ mix compile
** (Enum.EmptyError) empty error
    (elixir) lib/enum.ex:1843: Enum.reduce/2
    (mix) lib/mix/tasks/compile.ex:93: Mix.Tasks.Compile.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2
    (elixir) lib/code.ex:677: Code.require_file/2
```

### Expected behavior

this should probably have a friendlier failure mode

**Comment by JulioDeLeon** [comment]
I would like to work on this issue.

**Comment by josevalim** [comment]
@JulioDeLeon go ahead. :)

**Comment by soteras** [comment]
Is there a way to debug code with IEx.pry or IO.inspect?

I changed the code and after i run (make compile | make clean_elixir compile) but my code didn't change. I want to check the return of Mix.Task.run("compile.all", args).

**Comment by josevalim** [comment]
How are you testing it? You need to make sure you are using the elixir and mix scripts from the bin directory. Something like: `bin/elixir bin/mix compile`. You can also leverage the test suite and let the tests do the verification for you. :) 

Other than that, there is a debugging chapter on the getting started chapter in the website.
