### ISSUE TITLE
Logger cannot set `discard_threshold`

### ISSUE THREAD

**Issue by pallix** [elixir-lang/elixir#7532]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [kernel-poll:false]

Elixir 1.6.0 (compiled with OTP 19)
```
* Operating system: 

Linux

### Current behavior

I can set the `discard_threshold` value for the `Logger` configuration

```
iex(1)> Logger.configure(discard_threshold: 10_000)
:ok
iex(2)> Logger.Config.__data__()   
%{
  async_threshold: 15,
  discard_threshold: 500,
  keep_threshold: 375,
  level: :debug,
  mode: :async,
  sync_threshold: 20,
  translators: [{Logger.Translator, :translate}],
  truncate: 8096,
  utc_log: false
}
```

### Expected behavior

I can set the `discard_threshold` value for the `Logger` configuration, like the documentation indicates.

### Analysis

I think the `discard_threshold` key is missing in the [`valid_options` attribute list](https://github.com/elixir-lang/elixir/blob/v1.6.4/lib/logger/lib/logger.ex#L503).

**Comment by hlhr** [comment]
Had some time to kill so I wrote a unit test for that issue, can confirm it for option `discard_threshold` and `translator_inspect_opts`. I can fix this with the described solution if this is ok?

**Comment by pallix** [comment]
There may be the same problem for `:translator_inspect_opts`, also I don't see this option when printing `Logger.Config.__data__() ` so I am not sure how it is used.
