### ISSUE TITLE
Mix test exits without finishing tests in umbrella 

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#7534]
### Environment

* Elixir & Erlang versions (elixir --version):

Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.4 (compiled with OTP 20)
* Operating system: OSX 10.13.4

### Current behavior

When running `mix test` from umbrella root mix exits during testing one of the apps and fails to repot test results or any errors.

```
$ mix test
==> core
.......

Finished in 0.3 seconds
7 tests, 0 failures

Randomized with seed 175375
==> api
.....................

Finished in 0.3 seconds
21 tests, 0 failures

Randomized with seed 175375
==> utils
There are no tests to run
==> panel
There are no tests to run
==> backend
Excluding tags: [:skip]

..$
```
It looks like mix is being killed but the exit code is actually 0.
I tried running `mix test --trace` to pinpoint the faulty test but it is not deterministic at all.
When I run tests in every app there are not problems.

### Expected behavior

Tests should complete and report result (or crash with stacktrace and nonzero exit code)

**Comment by josevalim** [comment]
Can you please provide an application that reproduces the error?

**Comment by lukaszsamson** [comment]
It turned out one of the apps was calling `System.halt(0)` after some timeot
