### ISSUE TITLE
Map pattern matching with pinned key parts doesn't compile

### ISSUE THREAD

**Issue by japplegame** [elixir-lang/elixir#7543]
### Environment
```console
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.4 (compiled with OTP 19)
CentOS 7 x86_64
```

### Current behavior
This code doesn't compile
```elixir
m = %{{1, 2} => 3}
a = 1
b = 2
%{{^a, ^b} => c} = m
```
```console
** (CompileError) main.ex:4: illegal map key in pattern
```

### Expected behavior
It should compile.

**Comment by fertapric** [comment]
FYI it works inside IEx:

```elixir
$ iex
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.6.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> m = %{{1, 2} => 3}
%{{1, 2} => 3}
iex(2)> a = 1
1
iex(3)> b = 2
2
iex(4)> %{{^a, ^b} => c} = m
%{{1, 2} => 3}
iex(5)> c
3
iex(6)>
```

but not when compiling.

**Comment by josevalim** [comment]
Thank you for the report @japplegame!

The raising is correct but the error message is not good. We will fix that.

@fertapric good catch. It works on IEx by accident. The Elixir expansion pass was supposed to catch it and raise. This is part of #5800.

**Comment by liveforeverx** [comment]
@josevalim Why it shouldn't work?

This works:

```elixir
d = {a, b}
%{^d => c} = m # the same as %{{^a, ^b} => c} = m
```

**Comment by josevalim** [comment]
@liveforeverx as far as we are concerned, it is an Erlang compiler limitation. We need to ask them why. :)
