### ISSUE TITLE
Some of dependencies' compiler warnings show up with full file path while others with relative path

### ISSUE THREAD

**Issue by michallepicki** [elixir-lang/elixir#7568]
I'm not sure if it's intended or not (maybe the path got trimmed because it was too long?) but looks off. Honestly I prefer the full path.

### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.6.4 (compiled with OTP 19)
```
* Operating system: 

```
Linux (Ubuntu 17.10, kernel: 4.13.0-38-generic)
```

### Current behavior

```
warning: String.strip/1 is deprecated, use String.trim/1
  /home/michal/projects/my-project-dir/app/deps/poison/mix.exs:4

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated, use Integer.to_charlist/2
  lib/poison/encoder.ex:173

Generated poison app
```

### Expected behavior

```
warning: String.strip/1 is deprecated, use String.trim/1
  /home/michal/projects/my-project-dir/app/deps/poison/mix.exs:4

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated, use Integer.to_charlist/2
  /home/michal/projects/my-project-dir/app/deps/poison/lib/poison/encoder.ex:173

Generated poison app
```

or

```
warning: String.strip/1 is deprecated, use String.trim/1
  poison/mix.exs:4

==> poison
Compiling 4 files (.ex)
warning: Integer.to_char_list/2 is deprecated, use Integer.to_charlist/2
  lib/poison/encoder.ex:173

Generated poison app
```

**Comment by josevalim** [comment]
There is a reason. I will expand on it soon, but I just wanted to give a
heads up.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michalmuskala** [comment]
Ah, I guess only with a relative path, for every dependency we would just write `mix.exs` file, since it's always relative to the dependency's directory.

**Comment by josevalim** [comment]
Jackpot! And we wouldn’t be able to print the application name because we
haven’t confirmed/verified it yet.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by michallepicki** [comment]
That makes sense. It is not an issue :)
