### ISSUE TITLE
match? doesn't work with map pinned variable

### ISSUE THREAD

**Issue by virtual-light** [elixir-lang/elixir#7584]
root@phoenix:/var/app# elixir -v
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [kernel-poll:false]

Elixir 1.5.2

root@phoenix:/var/app# iex

iex(1)> match?(%{a: 1}, %{a: 1,  b: 2})
true

iex(2)> a = %{a: 1}
%{a: 1}

iex(3)> match?(^a, %{a: 1,  b: 2})                
false

Is this a bug? How to match against whole map pattern in Elixir?

**Comment by josevalim** [comment]
@virtual-light a pattern is not the same as a value. For example, I can have a pattern such as `[_ | _]` but there is no such list as a value. With that in mind, note that ^a compares values, and not patterns. So your last example would only match if both maps were fully equal.
