### ISSUE TITLE
Document "already started" for `DynamicSupervisor.start_child/2`?

### ISSUE THREAD

**Issue by nathanl** [elixir-lang/elixir#7586]
In [https://hexdocs.pm/elixir/master/DynamicSupervisor.html#start_child/2](https://hexdocs.pm/elixir/master/DynamicSupervisor.html#start_child/2), it says:

> If the child process start function returns an error tuple or an erroneous value, or if it fails, the child specification is discarded and this function returns `{:error, error}` where error is a term containing information about the error and child specification.

I think it would be useful to document that `{:error, {:already_started, pid}}` is returned if a child exists with the given spec. In my case, I wanted to ensure that only worker one at a time would be doing a particular task, defined by the arguments I passed. It turned out that this "error" was returned in the case of dups, which for me was not an error but a sign that "it's being taken care of."

Would you like a PR describing this return value in the docs for `start_child/2`?

**Comment by josevalim** [comment]
Yes! I think we even do document it in most cases. We should probably do `{:error, {:already_started, pid} | error}` in the typespecs.

**Comment by josevalim** [comment]
Actually, already_started is not returned in case of duplicate specs, it is returned when the name is already taken, and that is not a property of dynamic supervisor, it is simply what start_link on GenServer, Supervisor, Agent, etc and so on return in this case.

In any case, we have recently clarified the typespecs for start_child, so hopefully this return is already a bit clearer.

**Comment by nathanl** [comment]
Oh, I see that now. Thanks!

**Comment by adamu** [comment]
👋🏼 7 years later.

> Actually, already_started is not returned in case of duplicate specs, it is returned when the name is already taken, and that is not a property of dynamic supervisor, it is simply what start_link on GenServer, Supervisor, Agent, etc and so on return in this case.

Now [`DynamicSupervisor.on_start_child`](https://hexdocs.pm/elixir/DynamicSupervisor.html#t:on_start_child/0) is its own typespec, and DynamicSupervisor never returns `{:error, {:already_started, pid}}` (unless the started child itself returns that for some reason), maybe it should be removed from the spec? I guess that's impossible now, so for v2.

**Comment by adamu** [comment]
Ah, never mind, `already_started` is returned when name registration is used. I'll delete my comment.
