### ISSUE TITLE
Formatter does not respect line length on function definitions

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#7604]
### Environment

* Elixir & Erlang versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.4 (compiled with OTP 20)
```
* Operating system: Mac OS X

### Current behavior

The following code exceeds the default line length (line length 100, maximum line length 98), but the formatter does not split the function definition into multiple lines:

```elixir
defmodule LineLength do
  def a_really_really_really_long_function_name(first_argument, second_argument, third__argument) do
    :ok
  end
end
```

However, if the name of the last argument is changed to `third____argument`, then the formatter works as expected:

```elixir
defmodule LineLength do
  def a_really_really_really_long_function_name(
        first_argument,
        second_argument,
        third____argument
      ) do
    :ok
  end
end
```

### Expected behavior

I would expect the formatter to split the function definition into multiple lines if it exceeds the configured line length.

**Comment by josevalim** [comment]
Can you please add that as a comment to #7406? Thank you.
