### ISSUE TITLE
included_applications in env of kernel/stdlib

### ISSUE THREAD

**Issue by okeuday** [elixir-lang/elixir#7607]
### Environment

* Elixir 1.6.4 & Erlang/OTP 20.3
* Operating system: Ubuntu 16.04.3 LTS

### Current behavior

    > Application.get_all_env(:kernel)
    [included_applications: [],  ...
    > Application.get_all_env(:stdlib)
    [included_applications: [],  ...

### Expected behavior

`included_applications` should not be present in the env settings for `kernel` and `stdlib`

**Comment by fishcakez** [comment]
`incuded_applications` is present as application env for all applications. This is directly inherited from Erlang's behavior.

**Comment by okeuday** [comment]
@fishcakez That isn't correct.  The .app `included_applications` is separate from the `env` as shown at https://github.com/erlang/otp/blob/master/lib/kernel/src/kernel.app.src#L130

**Comment by michalmuskala** [comment]
Yes, but the `included_applications` env key is added unconditionally to every app's env by Erlang when the application is loaded.

https://github.com/erlang/otp/blob/30689e4e47351e235944350c88822b1e09b290e6/lib/kernel/src/application_controller.erl#L1274-L1276

**Comment by okeuday** [comment]
@michalmuskala Ok, true.  I did not notice that in the past.  Thanks!
