### ISSUE TITLE
Elixir install wants to remove esl-erlang on Ubuntu 18.04

### ISSUE THREAD

**Issue by realbrianstern** [elixir-lang/elixir#7624]
* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 20, No Elixir installed
* Operating system: Ubuntu 18.04

When I try to install Elixir, I get the following response:
```
❯ sudo apt-get install elixir
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  erlang-mode
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  erlang-base erlang-crypto erlang-syntax-tools
Suggested packages:
  erlang-tools erlang erlang-manpages erlang-doc
The following packages will be REMOVED:
  esl-erlang
The following NEW packages will be installed:
  elixir erlang-base erlang-crypto erlang-syntax-tools
0 upgraded, 4 newly installed, 1 to remove and 0 not upgraded.
Need to get 10.5 MB of archives.
After this operation, 19.4 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```
This would remove esl-erlang, which is definitely a problem. If I allow that to happen, and then run `mix local.hex`, that command is not available.

Has anyone seen this before? Is a working Elixir repository not yet available for Ubuntu 18.04?

**Comment by josevalim** [comment]
Hi @realbrianstern! We don't maintain any of the distributions so the best is to figure out who is providing the elixir package and ask them why they are doing so. Notice that you can also install elixir from the esl-erlang repository.

If you can figure it out, please drop another comment here, as it may help others in the future. Thank you!

**Comment by realbrianstern** [comment]
Ah thanks! It looks like the Erlang Solutions repository doesn't have an Elixir package for Ubuntu Bionic yet. I'll wait for that.

**Comment by NobbZ** [comment]
Also ESL is changing packaging structure into split packages as original Debian and Ubuntu packages are. Esl-erlang is deprecated.
