### ISSUE TITLE
Provide "rescue var not in [Exprs]"

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#7627]
This should nicely complement the current behavoiour when we want to rescue all exceptions except for some particular kind. Example use-case: 

https://github.com/elixir-plug/plug/blob/c547f2bd7a64aec7c4759dcc1ed88b6eab0c7499/lib/plug/parsers/multipart.ex#L32-L44

With `not in` this could look as:

```elixir
    try do
      parse_multipart(conn, opts)
    rescue
      # Wrap all errors except Plug.UploadError
      e not in Plug.UploadError ->
        reraise Plug.Parsers.ParseError.exception(exception: e), System.stacktrace()
    end
```

Doing this should be more efficient than reraising, since the VM could skip building the symbolic representation of the stacktrace in case it does not match.

**Comment by whatyouhide** [comment]
I'll take a stab at this.
