### ISSUE TITLE
Logger :application key is undefined

### ISSUE THREAD

**Issue by BlueHotDog** [elixir-lang/elixir#7641]
### Environment

Elixir 1.6.4 Erlang/OTP 20
Operating system: Ubuntu

### Current behavior

I'm trying to build an exception catching lib. but it seems that if two applications under an umbrella are running and one of them crashes, i want to report the exception to the correct backend.
I thought about doing so using the :application metadata..
Unfortunately it seems that it's undefined for some cases(the one i know about is if the application is crashing very early)

Any other idea on how to overcome this would be also appreciated.

**Comment by josevalim** [comment]
Yes, :application is a metadata and unfortunately it is not guaranteed that it will be included. #7494 aims to include more metadata when relevant but it is not a guarantee, only a best effort.
