### ISSUE TITLE
Catching exceptions calls deprecated Exception.normalize/2

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#7644]
I realised this after looking at #7643, but decided to open another issue since it's not directly related.

We should probably call `normalize/3` with an explicit `nil` stacktrace. 

Alternatively, given we now have the `__STACKTRACE__` var, we could also pass the stacktrace to the normalization pass when we know we'll be building it anyway. 
I'm not 100% convinced about that one, though. The reason is that Erlang can skip building the stacktrace even if it's bound to a variable in case the stacktrace variable is used only in calls to `:erlang.raise/3` (basically when reraising) and this would prevent it.

Additionally, I noticed that as soon as we start rescuing erlang errors, we also get an unnecessary call to `Exception.normalize/2` for the elixir exceptions case - this will never do anything, so we should skip it.

**Comment by josevalim** [comment]
@michalmuskala yup, we should tackle this as part of working on 21. I think the best idea here is to move the clauses that expect a stacktrace into the generated code so we get the stacktrace only when we need it.
