### ISSUE TITLE
Provide more topics for IEx.Helpers.runtime_info

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#7645]
This function has a lot of potential to be very useful for debugging - as a first tool for discovery where the problem might be in production situations.

I propose providing more topics based on features of the `:c` module and things that might be found in [recon](https://ferd.github.io/recon/) and other places of OTP.

Proposed additional topics:
* `:ets` - list of ets tables with basic info, like `:ets.i()`
* `:modules` - list of loaded modules, like `:c.m()`
* provide information about dirty schedulers in `:system`
* `:memory_details` - based on the new `:instrument` module in OTP 21. Maybe print some ASCII histograms?
* `:sctp`, `:tcp`, `:udp`, `:files` - list of ports of the provided type with some basic information about each of them (I'm not sure how this interacts with OTP 21 where files are no longer ports).

**Comment by josevalim** [comment]
Many of those are welcome but ASCII histograms are probably out of scope (unless somebody has a very short and trivial implementation).

**Comment by aerosol** [comment]
I'd like to tackle this if that's ok

**Comment by michalmuskala** [comment]
Go ahead, @aerosol. This could be also split across multiple commits & PRs if some of the implementations are bigger/more complex.

**Comment by josevalim** [comment]
Btw, let's not add anything based on processes and ports. My concern is that we may want to order, sort, filter this data in multiple ways and the runtime info panel won't provide this flexibility. I will amend the issue description for now.

**Comment by michalmuskala** [comment]
TBH i considered those to be the most useful ones.

I agree a simple list might not be that useful. I'm not sure how to proceed here. You could make the same argument for ets or modules.

**Comment by josevalim** [comment]
What would we show for modules? Alphabetical is properly fine there. I am
not worried about ets because the number of ets tables compared to
processes is way lower.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by aerosol** [comment]
To me it sounds like single `runtime_info` function isn't the perfect interface for a comprehensive runtime inspection. Would it make sense to introduce `Runtime` module that's more specialized and provides the flexibility needed?

**Comment by josevalim** [comment]
@aerosol good call. We could introduce process_info and ports_info in the future but that would be a separate issue. :) For now let's focus on how to improve the ones that fits runtime_info.

**Comment by aerosol** [comment]
`:ets` and `:modules` are straight-forward to implement, so I'll start with those, although I'm not sure if it's safe to assume that there aren't too many ETS tables in the system (I'm aware of some erlang libs that make you end up with thousands). For now I'll just go ahead with those two topics first.

`:memory_details` - This is new to me. I'll catch up with the OTP blog and get back here to discuss what can be done \cc @michalmuskala 

> :sctp, :tcp, :udp, :files - list of ports of the provided type with some basic information about each of them

Given what has been said in this thread, those also seem to be out of scope, correct?

**Comment by josevalim** [comment]
> :sctp, :tcp, :udp, :files - list of ports of the provided type with some basic information about each of them

@aerosol if they are ports, then it is better left for the port functionality.

About ETS and modules, let's wait a bit then. Given that we may add `port_info` and `process_info`, it doesn't hurt to wait and see how those will look like.

In hindsight, we should probably have started this discussion in the mailing list. thanks for all of the input!

So the best we can do here is to improve the memory measurements. A good beginning could even be by showing allocators specific data (see `:observer`). The new `:instrument` module may also be handy, so a PR around that is definitely welcome. I will add that to the "Support OTP 21 issue" but please go ahead with it.

**Comment by josevalim** [comment]
@aerosol after a further look, the `:instrument` module seems to only provide temporal data and I think formatting data into the terminal is a bit out of scope. The static allocator reference can be found with `:erlang.system_info :allocated_areas`.
