### ISSUE TITLE
If you use `@type` when you meant to use `@spec`, error messages are not very helpful and your project won't build

### ISSUE THREAD

**Issue by knewter** [elixir-lang/elixir#7647]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
jadams ~/e/specbug master λ elixir --version                                                                             4s 190ms
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 19)

* Operating system: 
OS X

### Current behavior

I've created a reproduction [here](https://github.com/dailydrip/specbug) that you can use to see what happens.

```elixir
defmodule Specbug do
  # This should say spec, but your brain betrays you
  @type hello(String.t()) :: String.t()
  def hello(world) do
    world
  end
end
```

Wrong code like the above ^^ yields the following error:

```
Compiling 1 file (.ex)

== Compilation error in file lib/specbug.ex ==
** (CompileError) lib/specbug.ex: internal error in lint_module;
crash reason: badarg

  in function  atom_to_list/1
     called as atom_to_list({'.',[{line,2}],
      [{'__aliases__',[{line,2},{counter,-576460752303422973}],['String']},
       t]})
  in call from erl_lint:'-check_type/2-fun-0-'/3 (erl_lint.erl, line 2808)
  in call from dict:fold_bucket/3 (dict.erl, line 460)
  in call from dict:fold_seg/4 (dict.erl, line 456)
  in call from dict:fold_segs/4 (dict.erl, line 452)
  in call from lists:foldl/3 (lists.erl, line 1263)
  in call from erl_lint:forms/2 (erl_lint.erl, line 689)
  in call from erl_lint:module/3 (erl_lint.erl, line 534)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
```

And it's really hard to go from that error to the code that caused it.

### Expected behavior

Something other than badarg? It's possible this is a special case, but I'm not exactly new to Elixir and my stupidity got me stuck for a bit here because my brain refused to read the line's problem.

**Comment by josevalim** [comment]
@knewter oh yeah, that's really not good. We can definitely improve it.
