### ISSUE TITLE
Move URI deprecations to @deprecated attribute

### ISSUE THREAD

**Issue by ricardoperez** [elixir-lang/elixir#7659]
Hi There, I don't bother with a such small issue . I was looking on the `URI` module other day I spotted the function `decode_query/2` still uses `IO.warn` instead of `@deprecated`.

*I've already changed in my local fork.

**Comment by josevalim** [comment]
That's because only a certain branch of the function is deprecated and not the whole function. In those cases, `@deprecated` does not work, as it always deprecate the whole function and not only part of it.

**Comment by ricardoperez** [comment]
Ok, sorry for that then.
