### ISSUE TITLE
Make Code.Formatter.block_to_algebra public

### ISSUE THREAD

**Issue by dannote** [elixir-lang/elixir#7661]
Hello!

It would be great to have ability to dump AST to a formatted block of code. We are one step from this feature – just a little wrapper around `Code.Formatter.block_to_algebra` has to be written. I can prepare a pull request if this proposal will be approved.

**Comment by josevalim** [comment]
The AST is actually highly annotated so we can't expose any of the Code.Formatter APIs publicly because it won't have the highly annotated AST.
