### ISSUE TITLE
Issue reading from file stream Elixir 1.6.5 & Erlang/OTP 21.0-rc1

### ISSUE THREAD

**Issue by rohanpujaris** [elixir-lang/elixir#7671]
Below code works fine on elixir 1.6.5 with Erlang/OTP 20, but doesn't work with Erlang/OTP 21.0-rc1
```
File.stream!("mix.exs", [:raw])
|> Enum.each(fn (line) -> IO.inspect(line) end)
```

In Erlang/OTP 21.0-rc1 I am getting  following error

```
** (FunctionClause
Error) no function clause matching in :raw_file_io_raw.open_layer/3    
    
    The following arguments were given to :raw_file_io_raw.open_layer/3:
    
        # 1
        "mix.exs"
    
        # 2
        [:read, :read_ahead, :binary, :binary]
    
        # 3
        [:raw, :raw]
    
    (kernel) raw_file_io_raw.erl:24: :raw_file_io_raw.open_layer/3
    (elixir) lib/file/stream.ex:78: anonymous fn/2 in Enumerable.File.Stream.reduce/3
    (elixir) lib/stream.ex:1346: anonymous fn/5 in Stream.resource/3
    (elixir) lib/enum.ex:1911: Enum.each/2

```
Is elixir 1.6.5 expected to support Erlang/OTP 21.0-rc1 completely? if not this ticket can be closed.

**Comment by josevalim** [comment]
@rohanpujaris it is expected to work but our initial tests did not catch this. We will give this a try and let you know.

**Comment by rohanpujaris** [comment]
@josevalim Thanks!

**Comment by josevalim** [comment]
@rohanpujaris does it work if you remove the `:raw` option? File streams add the `:raw` automatically, so when you do so, they end-up being added twice, which causes OTP 21 to fail. I am going to document the explicitly allowed options in stream better. Thank you!

**Comment by rohanpujaris** [comment]
@josevalim It works when we remove `:raw` option. Thanks!
