### ISSUE TITLE
Mix does not detect diverged dependencies

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#7685]
### Environment

Hex:    0.17.8-dev
Elixir: 1.7.0-dev
OTP:    20.2

Built with: Elixir 1.7.0-dev and OTP 20.2

### Current behavior

With the following dependencies:

```elixir
[
  {:phoenix, git: "https://github.com/phoenixframework/phoenix.git"},
  {:phoenix_ecto, "~> 3.2"}
]
```

And this dependency tree:

```
mix deps.tree
myapp
├── phoenix (https://github.com/phoenixframework/phoenix.git)
│   ├── plug ~> 1.5 (https://github.com/elixir-plug/plug.git) *override*
│   │   └── mime ~> 1.0 (Hex package)
│   └── phoenix_pubsub ~> 1.0 (Hex package)
└── phoenix_ecto ~> 3.2 (Hex package)
    ├── ecto ~> 2.1 (Hex package)
    │   ├── decimal ~> 1.2 (Hex package)
    │   └── poolboy ~> 1.5 (Hex package)
    └── plug ~> 1.0 (Hex package)
```

I get the following error when running `mix run`:

```
Unchecked dependencies for environment dev:
* plug (https://github.com/elixir-plug/plug.git)
  lock outdated: the lock is outdated compared to the options in your mix.exs. To fetch locked version run "mix deps.get"
** (Mix) Can't continue due to errors on dependencies
```

### Expected behavior

The error is wrong because we have diverged dependencies so `mix deps.get` won't fix it. Mix should instead raise a diverged dependencies error telling us to add `override: true`.

/cc @alex88

**Comment by ktec** [comment]
Anyone looking at this? Happy to try, might need some support tho.

**Comment by josevalim** [comment]
@ktec please go ahead! Note though that the mix.lock given by @ericmj will likely no longer fail since Phoenix master now depends on Plug properly. I think you will also need to ask Phoenix to use this reference: 6d4cdfe7c57bad398e764b1b77970e885a6b69e1

**Comment by ktec** [comment]
@josevalim thanks I'll try that!

**Comment by ericmj** [comment]
@ktec I was able to create a reproducing test that you can use: https://github.com/elixir-lang/elixir/commit/3fb9d8d42fb9bd3b0c55213c0f15c3e2c4a241c4
