### ISSUE TITLE
List.wrap\1 returns ASCII equivalents for integer 7 to 13

### ISSUE THREAD

**Issue by thegboat** [elixir-lang/elixir#7694]
When using List.wrap\1 strange behavior for integers 7 thru 13.  The function returns the ascii char equivalents.

### Environment

* Erlang/OTP 20 (elixir 1.6.5)
* Operating system:  macOS 10.13.4

### Current behavior

`iex(22)> List.wrap(13)
'\r'`

### Expected behavior

`iex(22)> List.wrap(13)
[13]`

**Comment by josevalim** [comment]
Hi @thegboat!

When you see a weird value in `IEx`, put `i` before the expression:

```iex
iex(1)> i List.wrap(13)
Term
  '\r'
Data type
  List
Description
  This is a list of integers that is printed as a sequence of characters
  delimited by single quotes because all the integers in it represent valid
  ASCII characters. Conventionally, such lists of integers are referred to
  as "charlists" (more precisely, a charlist is a list of Unicode codepoints,
  and ASCII is a subset of Unicode).
Raw representation
  [13]
Reference modules
  List
Implemented protocols
  IEx.Info, Collectable, Enumerable, Inspect, List.Chars, String.Chars
```

This explains why you see `'\r'`and that it is actually `[13]` underneath. :)

**Comment by thegboat** [comment]
Ah, I see.  Thanks for the quick response.
