### ISSUE TITLE
Dialyzer Spec Type + Struct Bug 

### ISSUE THREAD

**Issue by asummers** [elixir-lang/elixir#7700]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.5 (compiled with OTP 20)
```

* Operating system: OSX

### Current behavior

So I'm not positive where this bug lies, so I figured I would start with Elixir. When running dialyzer, and using `@type`s for structs, there is strange behavior exhibited. This example is mostly minimal, but there's probably a few things that are not contributing to the problem directly. 

Running the following through Dialyzer

```elixir
defmodule A do
  defstruct [:a]
  @type t :: %A{}
end

defmodule B do
  defstruct [:a, :b]
  @type t :: %B{}
end

defmodule Example do
  @type c :: A.t() | B.t()

  @spec ok(c()) :: :error
  def ok(%A{a: 10}) do
    %B{a: "foo", b: 10}
  end

  def ok(%B{a: 10}) do
    :ok
  end
end
```

Produces:

```
lib/testing.ex:14: Invalid type specification for function 'Elixir.Example':ok/1. The success typing is (#{'__struct__':='Elixir.A' | 'Elixir.B', 'a':=10, _=>_}) -> 'ok' | #{'__struct__':='Elixir.B', 'a':=<<_:24>>, 'b':=10}
```

As you can see, there's a weird term 
```erlang
#{'__struct__':='Elixir.A' | 'Elixir.B', 'a':=10, _=>_}
```
which is seemingly the two structs' innards concatenated together. 

### Expected behavior

The type has two structs `|`d together. Something like:
```erlang
#{'__struct__':='Elixir.A', 'a':=10} | #{'__struct__':='Elixir.B', 'a':=10, _=>_}
```
producing
```
lib/testing.ex:17: Invalid type specification for function 'Elixir.Example':ok/1. The success typing is (#{'__struct__':='Elixir.A', 'a':=10} | #{'__struct__':='Elixir.B', 'a':=10, _=>_}) -> 'ok' | #{'__struct__':='Elixir.B', 'a':=<<_:144>>, 'b':=10}
```

I know full well that this may be an error deeper down in dialyzer, but depending on the implementation of structs, Elixir might be the culprit here.

**Comment by josevalim** [comment]
Thanks @asummers! Elixir expands those exactly to:

    #{'__struct__':='Elixir.A', 'a':=10} | #{'__struct__':='Elixir.B', 'a':=10, 'b' := term()}

But dialyzer does merge terms together freely and we don't any control over it. So this is pretty much a dialyzer behaviour.

**Comment by asummers** [comment]
That's what I expected to be the case, but was hoping otherwise! Thanks @josevalim
