### ISSUE TITLE
Enum.random/1 blocks indefinitely

### ISSUE THREAD

**Issue by unthought** [elixir-lang/elixir#7726]
### Environment

```
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.6.4) - press Ctrl+C to exit (type h() ENTER for help)
```

```
uname -a
Linux bc-acquibase1 4.4.0-124-generic #148~14.04.1-Ubuntu SMP Thu May 3 07:26:53 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Current behavior

Our deployment of a Phoenix 1.3 app executes the following statement when processing requests:

```ex
Enum.random(1_000_000_000..2_000_000_000)
```

This has worked without issues under Elixir 1.4 on the same machines, and it still does under Elixir 1.6 on our dev machines, but it blocks indefinitely on our production machines. The Phoenix request never actually returns from that call or aborts in a visible fashion (`after_send` isn't executed), the requests just hang in an eternal loop (or rather in a very slow computation that grows with the size of the range, see timings below). We haven't found evidence of them blowing the stack or otherwise aborting.

The system boots directly into this behavior, so it's not something that accumulates. Here are some timings:

production machine (after warmup)
```
:timer.tc fn -> Enum.random(1_000_000..2_000_000) end
{461093, 1068242}

:timer.tc fn -> Enum.random(10_000_000..20_000_000) end
{12174193, 11965470}

:timer.tc fn -> :rand.uniform(1_000_000_000) + 1_000_000_000 end
{11, 1485118987}
```

on localhost (after warmup):
```
:timer.tc fn -> Enum.random(1_000_000..2_000_000) end
{31, 1440877}

:timer.tc fn -> Enum.random(10_000_000..20_000_000) end
{42, 18816482}

:timer.tc fn -> :rand.uniform(1_000_000_000) + 1_000_000_000 end
{13, 1872014607}
```

about localhost:
```
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.6.4) - press Ctrl+C to exit (type h() ENTER for help)
```

I have a production-like system available on which this can be reproduced (or on which I can run tests), but I don't have an isolated test case that exhibits the behavior.

### Expected behavior

Immediate return of:

```ex
Enum.random(1_000_000_000..2_000_000_000)
```

**Comment by josevalim** [comment]
@unthought this looks a protocol consolidation error or module lookup error. How are you running it in production? Here is a test you can run in prod:

```iex
iex(1)> Protocol.consolidated? Enumerable
true
iex(2)> Enumerable.__protocol__(:impls)
{:consolidated,
 [Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet,
  IO.Stream, List, Map, MapSet, Range, Stream]}
iex(3)> Code.ensure_loaded?(Enumerable.Range) and function_exported?(Enumerable.Range, :slice, 1)
true
```

If the first example returns false or you don't see `Range` in the second one or the third line returns false, it means we are not locating the efficient range implementation. Can you configure a full rebuild for prduction?

**Comment by unthought** [comment]
@josevalim thanks for the swift answer

Here's how it looks like:

```
Protocol.consolidated? Enumerable
true

Enumerable.__protocol__(:impls)
** (FunctionClauseError) no function clause matching in Enumerable.__protocol__/1

    The following arguments were given to Enumerable.__protocol__/1:

        # 1
        :impls

    (elixir) lib/enum.ex:1: Enumerable.__protocol__/1
```

**Comment by unthought** [comment]
Note: this is not an iex, but the remote_console.

**Comment by josevalim** [comment]
@unthought what about the third line?

**Comment by unthought** [comment]
just added above

```
Code.ensure_loaded?(Enumerable.Range) and function_exported?(Enumerable.Range, :slice, 1)
true
```

**Comment by josevalim** [comment]
@unthought it is very weird that `Enumerable.__protocol__(:impls)` is erroring out for you. Very very. Can you or anyone else be accidentally overriding it? What does `Enumerable.module_info()` return?

**Comment by unthought** [comment]
I nuked `_build/` and `deps/` and I'm rebuilding now.

On the current (non-rebuilt) deploy, I get this:

```
Enumerable.module_info()
[
  module: Enumerable,
  exports: [
    __info__: 1,
    __protocol__: 1,
    impl_for: 1,
    impl_for!: 1,
    behaviour_info: 1,
    module_info: 0,
    module_info: 1,
    member?: 2,
    count: 1,
    reduce: 3
  ],
  attributes: [
    vsn: [277702036914435370877700735300077052686],
    protocol: [fallback_to_any: false]
  ],
  compile: [options: [:debug_info], version: '7.0.4.1'],
  native: false,
  md5: <<208, 235, 119, 131, 141, 122, 39, 75, 180, 84, 216, 101, 10, 127, 99,
    14>>
]
```

**Comment by unthought** [comment]
@josevalim re-built and deployed, same behavior.

**Comment by josevalim** [comment]
@unthought I will need a way to reproduce this issue then. It seems that your Enumerable protocol is coming from an old Elixir version, since it doesn't have `:impls` clause nor the `slice` function, which would explain the performance issue you are seeing.

I would look at the Elixir version you are compiling your software. Is it the same as you run it in production? Could you be caching artefacts in any way?

**Comment by unthought** [comment]
@josevalim I would have to check and see if we cache something somewhere. We're compiling with distillery to the tgz and then unpack that on the production machines. Maybe we pick up something old from somewhere.

**Comment by unthought** [comment]
@josevalim The problem was introduced by unpacking the release tar without wiping the target directory first. Because of that there were stale files from previous releases there. We're not consolidating protocols explicitly, and even though [mix compile.protocols](https://hexdocs.pm/mix/Mix.Tasks.Compile.Protocols.html) states that it's always called unless explicitly disabled, that doesn't seem to be the case. So we most likely picked up an ancient consolidation file which didn't have the correct code.

I'm now simply wiping the destination before unpacking and the problem disappeared (and a couple of others probably prevented). Thanks for showing me the right direction. Closing.
