### ISSUE TITLE
Show warning in tests when find a `describe` with code, but no `test` call

### ISSUE THREAD

**Issue by maksimf** [elixir-lang/elixir#7727]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.6.4 (compiled with OTP 20)
* Operating system: MacOS 10.13.4

### Current behavior

If you have forgotten to wrap your test with actual `test` function call, like this:

```elixir
describe "function_to_test/2" do
  Repo.aggregate(...)

  assert something == 1
end
```

When I try to run this test a get a `DBConnection.OwnershipError`:

```
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.704.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.
```

### Expected behavior

I get some kind of warning from Elixir, that I try to invoke a `describe` function with code, but no `test` calls inside. Something that would help me debug the simple fact that I forgot `test` call

**Comment by maksimf** [comment]
Thanks for swift response, José! I guess I'm closing the issue then

**Comment by AndrewDryga** [comment]
@josevalim can't we do that by analyzing module AST (probably after macros are expanded)? I'm not sure if there is a pass where we can do that, adding a compilation pass just for this purpose would be overkill.

**Comment by josevalim** [comment]
We can't because you can have your own macro that calls `test`. Or you can have `test` inside a `for`, etc. It would be really hard to do something without false positives or false negatives.
