### ISSUE TITLE
v1.6.3 fails build from source

### ISSUE THREAD

**Issue by marinakr** [elixir-lang/elixir#7728]
### Environment
Erlang/OTP 20 [erts-9.3.2], elixir 1.6.5 was installed, 1.6.3 - tag to build 
* Operating system: 
MacOS

I am tried to downgrade elixir from 1.6.5 to 1.6.3 by building from source, 
running: 
make clean 
make test
 and test fails with errors

### Current behavior

Generated iex app
==> elixir (eunit)
  All 198 tests passed.

==> elixir (exunit)
Excluding tags: [windows: true]

...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

  1) test for comprehensions into dynamic binary (Kernel.ComprehensionTest)
     test/elixir/kernel/comprehension_test.exs:157
     ** (ArgumentError) argument error
     code: assert (for x <- enum, into: into do
     stacktrace:
       :erlang.iolist_to_binary(<<13::size(6)>>)
       (elixir) lib/collectable.ex:105: anonymous fn/2 in Collectable.BitString.into/1
       test/elixir/kernel/comprehension_test.exs:165: (test)

.......

  2) test list for comprehensions into dynamic binary (Kernel.ComprehensionTest)
     test/elixir/kernel/comprehension_test.exs:283
     ** (ArgumentError) argument error
     code: assert (for x <- enum, into: into do
     stacktrace:
       :erlang.iolist_to_binary(<<13::size(6)>>)
       (elixir) lib/collectable.ex:105: anonymous fn/2 in Collectable.BitString.into/1
       test/elixir/kernel/comprehension_test.exs:291: (test)

.....................

  3) test binary for comprehensions into dynamic binary (Kernel.ComprehensionTest)
     test/elixir/kernel/comprehension_test.exs:353
     ** (ArgumentError) argument error
     code: assert (for <<x <- bin>>, into: into do
     stacktrace:
       :erlang.iolist_to_binary(<<13::size(6)>>)
       (elixir) lib/collectable.ex:105: anonymous fn/2 in Collectable.BitString.into/1
       test/elixir/kernel/comprehension_test.exs:361: (test)

.............................................................................................

  4) test for comprehensions into binary (Kernel.ComprehensionTest)
     test/elixir/kernel/comprehension_test.exs:145
     ** (ArgumentError) argument error
     code: assert (for x <- enum, into: "" do
     stacktrace:
       :erlang.iolist_to_binary(<<13::size(6)>>)
       test/elixir/kernel/comprehension_test.exs:152: (test)

  5) test list for comprehensions into binary (Kernel.ComprehensionTest)
     test/elixir/kernel/comprehension_test.exs:271
     ** (ArgumentError) argument error
     code: assert (for x <- enum, into: "" do
     stacktrace:
       :erlang.iolist_to_binary(<<13::size(6)>>)
       test/elixir/kernel/comprehension_test.exs:278: (test)

.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................warning: Module.add_doc/6 is deprecated, use @doc instead
  test/elixir/kernel/docs_test.exs:182

............................................................................................................................

Finished in 21.3 seconds (7.5s on load, 13.8s on tests)
1367 doctests, 2884 tests, 5 failures, 7 skipped

Randomized with seed 528780

### Expected behavior
make test shouldn't fail

**Comment by josevalim** [comment]
Hi @marinakr!

You are correct, the tests do not pass because there was an incompatibility between Elixir v1.6.3 and OTP 20.3 (erts-9.3). The incompatibility has been fixed on v1.6.4 and [you can see it in the CHANGELOG](https://github.com/elixir-lang/elixir/blob/v1.6/CHANGELOG.md#v164-2018-03-16).

Is there a reason why you can't use v1.6.5 (or at least v1.6.4)?

**Comment by marinakr** [comment]
Ok, I see, in description v1.6.3 erlang should be 19 or higher
1.6.3 and 1.6.5 have different 'mix format', because of it

**Comment by josevalim** [comment]
@marinakr it is v1.6.3 or higher because at the time it was released Erlang/OTP 20.3 was not out yet. I will add a note. :) Thank you!
