### ISSUE TITLE
Mix.Project.in_project/4 always produces recompilation warnings

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-lang/elixir#7741]
### Environment

```
elixir -v
Erlang/OTP 20 [erts-9.3.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.7.0-dev (73201ca) (compiled with Erlang/OTP 20)
```

### Current behavior

This code would always produce warnings (It's run from within the umbrella app):
```
Mix.Project.in_project application_name, "apps/#{application_name}", fn _module ->
  Mix.Project.config()[:version] |> Version.parse!() |> IO.puts()
end
```

```
warning: redefining module Work.MyApp.Mixfile (current version defined in memory)
  /Users/andrew/Projects/work/talk/apps/myapp/mix.exs:1

0.1.0
```

### Expected behavior

No warnings produced:
```
0.1.0
```

**Comment by josevalim** [comment]
Does it happen if you give a full path? Also, can you please provide a
simple application that reproduces it?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by AndrewDryga** [comment]
@josevalim it does reproduce with full path. For now, I found a workaround by setting `Code.compiler_options(ignore_module_conflict: true)` in the beginning of Mix task.

I can prepare sample all later this week.

**Comment by josevalim** [comment]
Ping.

**Comment by AndrewDryga** [comment]
@josevalim here is the repo to reproduce: https://github.com/AndrewDryga/elixir-issue-7741.
In umbrella app root run `mix reproduce app2`.

**Comment by josevalim** [comment]
@AndrewDryga the first argument here needs to be an atom: https://github.com/AndrewDryga/elixir-issue-7741/blob/master/apps/app1/lib/mix_task.ex#L6

but because we don't have a guard, you were not catching it. Pushing a guard soon!
