### ISSUE TITLE
Formatter breaks single line clauses because of comments

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#7742]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.6.5 and master

### Current behavior

```elixir
case x do
  # comment
  :foo -> :bar
end
```

is formatted into

```elixir
case x do
  # comment
  :foo ->
    :bar
end
```

### Expected behavior

Keep clauses as single line because they are not beyond the line length limit and comments should not affect it.

**Comment by Hanspagh** [comment]
This also seems to be the case when adding a line break in any of the case statements

    case x do
      :foo -> :bar
      :foo -> 
        :bar
    end
is formatted to 

    case x do
      :foo ->
        :bar

      :foo ->
        :bar
    end

**Comment by fertapric** [comment]
@Hanspagh I think that's an expected behavior.

**Comment by ericmj** [comment]
Yes, that's expected behavior, the formatter works similarly on other circumstances.

**Comment by Hanspagh** [comment]
@fertapric I expected that as well, but was not able to find any docs to support this, so I though I might as well report it

**Comment by josevalim** [comment]
Closing in favor of #7843.
