### ISSUE TITLE
(Mix) Failed to find installation for Hex package and Elixir 1.6.5

### ISSUE THREAD

**Issue by Sylhare** [elixir-lang/elixir#7747]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.6.5 (compiled with OTP 20)
* Operating system: MacOS 10.13.5

### Current behavior

Hi, I have been trying to install hex package using:

```bash
mix hex.install <package>
```
And whenever I do that, whichever the package (I even tried with the most popular one on https://hex.pm/ to see if it was a package problem) I always get the same error:

```
** (Mix) Failed to find installation for Hex <package> and Elixir 1.6.5
```

### Expected behavior

Well I was expecting the package to install nicely, I am new to elixir, but I guessed it would do like npm. I wanted to try without putting the package as a runtime dependency of my mix project.
Thanks

**Comment by josevalim** [comment]
Welcome! 

The `hex.install` task is private. You are not supposed to invoke it. In particular, Mix doesn't support packages to be used globally like in npm. You need to list them as dependencies of your mix project or install it as an archive or an escript. See `archive.install` and `escript.install`. If a package is meant be used as an archive or escript, they will let you know explicitly in their README. :)
