### ISSUE TITLE
Mix format do nothing

### ISSUE THREAD

**Issue by marinakr** [elixir-lang/elixir#7759]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 20 [erts-9.3.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.3 (compiled with OTP 20)

* Operating system: 
Macos

### Current behavior
mix format

no error returned, everything is ok

mix format do nothing, whitespaces, new lines, etc is not fixed 

### Expected behavior
'mix format' will format files

**Comment by josevalim** [comment]
Do you have a `.formatter.exs` file in your project? Could you please paste its contents here? Or can you provide a sample project that reproduces this error? Thank you!

**Comment by marinakr** [comment]
`cat .formatter.exs 
# Used by "mix format"
[
  inputs: ["mix.exs", "mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 120
]`

**Comment by josevalim** [comment]
Yes, this was supposed to work. Can you reproduce this issue in a new project and upload it to github so we can take a look?

**Comment by marinakr** [comment]
Yes, it's already here
https://github.com/edenlabllc/mpi.api/tree/json-and-tables%232308

**Comment by josevalim** [comment]
Ok, I checked it out and the project is already formatted, so running `mix format` is going to have no effect. If you introduce some poorly formatted code than it should work.

**Comment by josevalim** [comment]
> It fails when build because of 'mix format' : https://travis-ci.org/edenlabllc/mpi.api/builds/392766358?utm_source=github_status&utm_medium=notification

The build seems to be failing on `mix credo` and not `mix format`. Or am I missing something? :)

@marinakr could your editor be stripping whitespaces or formatting the file on save? You can try this in your terminal (assuming you have linux):

```
$ echo "foo bar, baz" > lib/foo.ex
$ mix format
$ cat lib/foo.ex
```

Are the parens now included?

**Comment by josevalim** [comment]
@marinakr were you able to get it to work then? :)

**Comment by marinakr** [comment]
mix format works
my misunderstanding - The problem was that files with migrations did not formatted(but it is normal according to my .formatter file)
