### ISSUE TITLE
Warn if x < y < z is used

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#7769]
Or any combination of `<`, `>`, `<=` or `>=` are nested. This should be added to the compiler since the warning only makes sense for comparison operators but a DSL may override the meaning of those operators.

**Comment by lukevmorris** [comment]
I'd love to tackle this. I wrote a failing test for this in elixir/kernel/warning_test.exs. (Hope I did it right). I've been able to trace the origin of the warning messages to some files like `elixir_locals.erl`, `elixir_compiler.erl` and `elixir_env.erl`. Do you have a preference for where I try to implement?

**Comment by josevalim** [comment]
I believe in elixir_expand.erl as we already have a function checking
explicitly for those operators there.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by lukevmorris** [comment]
Great thank you very much!

**Comment by josevalim** [comment]
Closing in favor of #7773.
