### ISSUE TITLE
File.stream! error

### ISSUE THREAD

**Issue by benwilson512** [elixir-lang/elixir#7771]
### Environment
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.6.6 (compiled with OTP 19)
```

### Current behavior
This invocation works on Elixir 1.6.6 and OTP 20.3.2, but not on OTP 1.6.6 and OTP 21.0

```
iex(8)> "Readme.md" |> File.stream!([:raw, :read_ahead, :binary]) |> Enum.to_list
** (FunctionClauseError) no function clause matching in :raw_file_io_raw.open_layer/3    
    
    The following arguments were given to :raw_file_io_raw.open_layer/3:
    
        # 1
        "Readme.md"
    
        # 2
        [:read, :read_ahead, {:read_ahead, 65536}, :binary, :binary]
    
        # 3
        [:raw, :raw]
    
    (kernel) raw_file_io_raw.erl:24: :raw_file_io_raw.open_layer/3
    (elixir) lib/file/stream.ex:78: anonymous fn/2 in Enumerable.File.Stream.reduce/3
    (elixir) lib/stream.ex:1346: anonymous fn/5 in Stream.resource/3
    (elixir) lib/enum.ex:1911: Enum.reverse/1
    (elixir) lib/enum.ex:2588: Enum.to_list/1
```

**Comment by josevalim** [comment]
@benwilson512 I am not quite sure this is a bug. The stream already uses raw, binary, and read_ahead options, so specifying those on stream is irrelevant, and now Erlang is complaining about it. I can see an argument for us fixing it though but that won't change the fact that those options are irrelevant.

The read_ahead option can even be problematic when writing to a stream, which is an argument for raising.

**Comment by benwilson512** [comment]
Yeah it's definitely a gray area. The prime argument for calling it a bug is that code that worked on 1.6.6 and OTP 20 no longer works on 1.6.6 and OTP 21. I'm not entirely sure what guarantees Elixir provides about backwards compatibility though.

**Comment by benwilson512** [comment]
> this case is about forward compatibility though.

Good point!

**Comment by hauleth** [comment]
Is there any workaround for that?
