### ISSUE TITLE
Having Trouble Reading From STDIO with Erlang 21.0

### ISSUE THREAD

**Issue by JEG2** [elixir-lang/elixir#7772]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.6.6 and Erlang 21.0
* Operating system: macOS 10.13.5

### Current behavior

Observe the differences between older Erlang and newer (I'm unsure which language is at fault here):

```
$ iex -e ':stdio |> IO.read(:all) |> IO.inspect' <<< 'DATA'
"DATA\n"
Interactive Elixir (1.6.6) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> ^C
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
$ asdf local erlang 21.0
$ iex -e ':stdio |> IO.read(:all) |> IO.inspect' <<< 'DATA'
```

The terminal hangs at this point (instead of spitting out data as it did on line 2).

### Expected behavior

I expect `IO.read/2` not to block in this scenario.

**Comment by josevalim** [comment]
I can reproduce it with Erlang. On Erlang 19.0 it terminates:

    /Users/jose/.kerl/19.0/bin/erl -noshell -eval '"DATA\n" = io:get_line(""), eof = io:get_line(""), halt()' <<< 'DATA'

On Erlang 21.0 it blocks forever:

    /Users/jose/.kerl/21.0/bin/erl -noshell -eval '"DATA\n" = io:get_line(""), eof = io:get_line(""), halt()' <<< 'DATA'

Could you please file a report at bugs.erlang.org? Please let us know if you have any issues or questions while doing so. Thank you!

**Comment by JEG2** [comment]
[Done](https://bugs.erlang.org/browse/ERL-647).
