### ISSUE TITLE
Build issue with OTP 20+

### ISSUE THREAD

**Issue by dmilith** [elixir-lang/elixir#7775]
### Environment

* Elixir 1.6.6 & Erlang/OTP 20+, 21+
* Operating system: HardenedBSD 11.1+/ FreeBSD 11.1+

### Current behavior

On make:

```
Uncaught error in rebar_core: {'EXIT',
                                  {badarg,
                                      [{re,split,3,[]},
                                       {escript,run,2,[]},
                                       {escript,start,1,[]}]}}
```

### Expected behavior

Just build start I guess?

**Comment by dmilith** [comment]
I will add that build of OTP 21 is exectly the same as I do build for 19.3.x (where it works just fine).

**Comment by josevalim** [comment]
@dmilith our CI builds on those versions and they work fine: https://travis-ci.org/elixir-lang/elixir/builds/394326170

From your error, it seems that the rebar version is incompatible with the Erlang version, but I can't quite grasp why.

Also, can you please try master? We no longer depend on `rebar` to build on master, so this issue may have disappeared altogether.

**Comment by josevalim** [comment]
Ping?

**Comment by dmilith** [comment]
I will check with these explicit build options you specify for build on Ubuntu and let you know :)

**Comment by josevalim** [comment]
Please let us know if you have more information as we can't reproduce the issue. Thank you!
