### ISSUE TITLE
typo: `Continue` should be `continue`

### ISSUE THREAD

**Issue by sunboshan** [elixir-lang/elixir#7781]
https://github.com/elixir-lang/elixir/blob/f730125b443515adfbe894b26e6bb6d97de6f73c/lib/elixir/lib/gen_server.ex#L359

**Comment by whatyouhide** [comment]
Closed by 072eee8ea6b370d47440e81c5224ca8d67367dc6.

**Comment by fishcakez** [comment]
Perhaps we should clarify these docs further by using variable names that don't match the instruction, e.g. `{:reply, response, state}`, `{:stop, reason, state}`, `{:noreply, state, {:continue, data}}`
