### ISSUE TITLE
Automate building Precompiled.zip with checksum

### ISSUE THREAD

**Issue by chulkilee** [elixir-lang/elixir#7791]
`Precompiled.zip` is the only official build and used by many other integration (e.g. Docker image), so it is important to make sure it is not compromised or tampered.

### Current behavior

- [GitHub release page](https://github.com/elixir-lang/elixir/releases) has docs, source code, and precompiled elixir
- The release page does not have any checksum for those artifacts
- GitHub release is made manually with artifacts created by someone's dev laptop (per https://github.com/elixir-lang/elixir/blob/master/RELEASE.md)

### ~~Expected~~ Desired behavior

- Use automated build to create `Precompiled.zip` to be uploaded to GHE release
  - e.g. use travis build to print out checksum and push the artifacts to somewhere
- Provide checksum to prevent tampering; should be provided differently than artifacts
  - e.g. put the link to the travis build page on the release page

Example: k8s
- [releases page](https://github.com/kubernetes/kubernetes/releases): source code and its SHA256
- [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.8.md#v1814): link to compiled artifacts and their SHA256

See also comments by @ericmj  at https://github.com/hexpm/bob/issues/16.

**Comment by ericmj** [comment]
> Provide checksum to prevent tampering; should be provided differently than artifacts

👍 

> Use automated build to create Precompiled.zip to be uploaded to GHE release

The release process is already a manual process and building the release locally is faster than waiting for an external build system. Can you elaborate on why this is needed?

**Comment by josevalim** [comment]
We already keep a file with sha1 an sha512: https://github.com/elixir-lang/elixir-lang.github.com/blob/master/elixir.csv

 I will make sure to:

  1. link to the CSV file from the website
  2. include the shas on the github release page in the future releases too

Thanks @chulkilee!
