### ISSUE TITLE
Introduce assert_no_guard_scope in Kernel

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#7795]
Several macros in `Kernel` cannot be used inside guards - `!`, `&&` and `||` being the most notable examples. We should fail gracefully when that happens. Right now the error is "cannot use case in guards", which is not very helpful.

The simplest way to do this would probably to introduce a private `assert_no_guard_scope` function verifying `__CALLER__.context`, similar to `assert_module_scope` and `assert_no_function_scope`.

**Comment by Sihui** [comment]
Hi @michalmuskala, I reuse the error message from [elixir_expand](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_expand.erl#L1102). Not sure if we want something different than that. I also only use the new `assert_no_guard_scope` in  `!`, `&&` and `||`. Let me know if you think I should use it somewhere else as well.

Maybe I miss your point. Why is this better than what we already have?

**Comment by josevalim** [comment]
@Sihui the difference is that we raise the error closer to the user code, so the error message will be more precise and relevant. :)

**Comment by Sihui** [comment]
That makes sense. Thanks, @josevalim! :)

**Comment by devonestes** [comment]
I think this can be closed now. It wasn't closed automatically for some reason when the PR was merged.
