### ISSUE TITLE
Mix does not honor override flag

### ISSUE THREAD

**Issue by walkr** [elixir-lang/elixir#7798]
Mix fails to fetch dependencies

### Environment

* Elixir 1.6.6 (compiled with OTP 20) & Erlang/OTP 21 [erts-10.0] 
* macOS

### Current behavior

`mix deps.get` fails, even though I set the override flag to true

```
* rustler (https://github.com/hansihe/rustler)
  different specs were given for the rustler app:

  > In apps/store/mix.exs:
    {:rustler, [env: :prod, git: "https://github.com/hansihe/rustler", ref: "b6578ea3", sparse: "rustler_mix", override: true, manager: :mix]}

  > In deps/rox/mix.exs:
    {:rustler, [env: :prod, git: "https://github.com/hansihe/rustler", sparse: "rustler_mix"]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

### Expected behavior

Dependency fetching should work

Cheers!

**Comment by NobbZ** [comment]
As I understand it, you can only use `override: true` from the top-level app, and since umbrellas are just wrappers around `:path`-deps, its propably true here as well. Try overriding from you umbrella.

**Comment by josevalim** [comment]
@NobbZ we are supposed to override if they belong in the same tree though.

@walkr can you please provide a sample application that reproduces the error?

**Comment by NobbZ** [comment]
Maybe a double of #4684?

**Comment by NobbZ** [comment]
@josevalim Thank you, understood!

**Comment by ericmj** [comment]
It seems to be a similar issue, mix sees the dependency and umbrella child as siblings so they can't override each other. You need to move the override to a higher level.

**Comment by walkr** [comment]
My apologies for the delayed response!

@josevalim Sure! Here it is: [otrue_umbrella](https://github.com/walkr/otrue_umbrella)

Thanks!

**Comment by josevalim** [comment]
Thanks @walkr for the app, that helps a ton! As @ericmj said, from the umbrella perspective, there is indeed a conflict, as it wants to run each app in isolation and it needs to pick which one of the two it is going to use.

**Comment by dylan-chong** [comment]
For us it does seem to work by specifying the override in the top level umbrella app, however, when running ecto migrations, each app compiles individually and complains about the deps conflict because the umbrella app's mix file isn't seen by the inner app
