### ISSUE TITLE
Windows Web Install is broken

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#7804]
https://elixir-lang.org/install.html#windows

When you run it, theres an error about fetching a .csv.

**Comment by josevalim** [comment]
Can you please provide more information? What is your OS version? What does
the error say? Did you try it on another machine or another network?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
I have just ran the installer on a VM and everything worked fine. So please try to provide more information and see if by any chance you are running into one of the issues listed here: https://github.com/elixir-lang/elixir-windows-setup/issues

Thank you!

**Comment by vans163** [comment]
This is the error I get when I run the webinstaller.

![Image of Yaktocat](https://i.imgur.com/pxKqAj8.png)

**Comment by vans163** [comment]
Yea any possible news on this, or will this issue that is an actual problem continue to be closed for some odd reason? Why close issues that report bugs, its just bad management and discouraging.

**Comment by josevalim** [comment]
@vans163 as you have noted, this issue is already open in the relevant repository.
