### ISSUE TITLE
Buffer IEx prompt and user input to automatically shift down/re-print after an incoming message.

### ISSUE THREAD

**Issue by s6o** [elixir-lang/elixir#7808]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 21; Elixir 1.6.6 (compiled with OTP 20)
* Operating system: macOS 10.12.6 

### Current behavior

When interacting with a running application via IEx, where the application emits log messages, the messages interleave with IEx's user input:

```
iex(3)> with {:ok, result} <- (fn -> {:error, "[debug] 17:59:08.351 module=IncidentNotifier function=handle_info/2 : No new incidents to notify about.
Failure"} end).() do
...(3)> true
...(3)> end
{:error, "Failure"}
iex(4)> [debug] 18:01:08.352 module=IncidentNotifier function=handle_info/2 : No new incidents to notify about.
```

This is not about turning off logging or adjusting log levels. I'd still like to receive application's output, but without mangling the current IEx prompt and (partial) input.

### Expected behavior

  * buffer the IEx prompt and user input
  * always print incoming output message from 0 (left most) position
  * re-print buffered prompt and input after last output message, so that an automatic "shift down" would occur resulting in the output below, instead of the output above:

```
[debug] 17:59:08.351 module=IncidentNotifier function=handle_info/2 : No new incidents to notify about.
iex(3)> with {:ok, result} <- (fn -> {:error, "Failure"} end).() do
...(3)> true
...(3)> end
{:error, "Failure"}
[debug] 18:01:08.352 module=IncidentNotifier function=handle_info/2 : No new incidents to notify about.
iex(4)>
```

**Comment by josevalim** [comment]
Hi @s6o! The shell is actually implemented in Erlang, so anyone interested on this feature should rather send a pull request to the OTP team. :)
