### ISSUE TITLE
no syntax error in config.exs

### ISSUE THREAD

**Issue by atomkirk** [elixir-lang/elixir#7813]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.6.6
* Operating system: High Sierra

### Current behavior

When I do this in config:

```elixir
config :my_app, Something,
  key: %{
    key_a: %{
      value: "a",
    } # <--- notice no comma
    key_b: %{
      value: "b"
    }
  }
```

I don't get any syntax error. So we deployed that and it broke our app.

### Expected behavior

Seems like normal syntax errors like that should be caught in config.exs

**Comment by wojtekmach** [comment]
this crashes for me:

```
Erlang/OTP 21 [erts-10.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

** (Mix.Config.LoadError) could not load config config/config.exs
    ** (SyntaxError) config/config.exs:8: syntax error before: key_b
    (elixir) lib/code.ex:192: Code.eval_string/3
    (mix) lib/mix/config.ex:188: Mix.Config.read!/2
    (mix) lib/mix/tasks/loadconfig.ex:37: Mix.Tasks.Loadconfig.load/1
    (mix) lib/mix/tasks/loadconfig.ex:27: Mix.Tasks.Loadconfig.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

can you double-check on a fresh project? Maybe there's more in your config.exs that makes it pass somehow?

**Comment by atomkirk** [comment]
Yeah you're right, this must be our issue. thanks

**Comment by atomkirk** [comment]
Is it possible this is distillery error? I see the same error when making changes to dev.exs, but when we built the release with distillery and the error was in prod.ex, the error was ignored and as far as we can tell, the config value was just ignored or nil or something
