### ISSUE TITLE
Invalid spec in Supervisor.init

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#7824]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.6.6 (compiled with OTP 21)

### Current behavior

```
children = [
      supervisor(MyApp.MySupervisor, [])
]

Supervisor.init(children, strategy: :simple_one_for_one)
```

The call 'Elixir.Supervisor':init(Vchildren@1::any(),[{'strategy','simple_one_for_one'},...]) breaks the contract ([supervisor:child_spec() | {module(),term()} | module()],[init_option()]) -> {'ok',tuple()}

### Expected behavior
No error

**Comment by josevalim** [comment]
This is happening because we have removed simple_one_for_one from the list of strategies as it is soft deprecated. I would like to hear thoughts on this.

**Comment by NobbZ** [comment]
Because `strategy: :simple_one_for_one` is discouraged/deprecated in favor of [`DynamicSupervisor`](https://hexdocs.pm/elixir/DynamicSupervisor.html).

>  There is also a deprecated strategy called `:simple_one_for_one` which
>  has been replaced by the `DynamicSupervisor`. The `:simple_one_for_one`
>  supervisor was similar to `:one_for_one` but suits better when dynamically
>  attaching children. Many functions in this module behaved slightly
>  differently when this strategy is used. See the `DynamicSupervisor` module
>  for more information and migration strategies.

**Comment by lukaszsamson** [comment]
IMO even if this strategy is deprecated it is still a supported one and the type spec should allow it.
Similar code using also deprecated ```Supervisor.Spec.supervise``` returns no dialyzer errors

**Comment by josevalim** [comment]
@lukaszsamson `Supervisor.Spec` won't fail the specs because we would just remove them and missing specs do not cause dialyzer crashes.

**Comment by michalmuskala** [comment]
I would consider this as a deprecation warning for what arguments a function accepts. Similar how we don't provide a way to silence warnings for function deprecations (when a function will be removed), we shouldn't support silencing warnings for deprecating part of the function (through restricting the type spec).

**Comment by josevalim** [comment]
For now we will keep the warning, we can always revisit it later. Thanks everyone!
