### ISSUE TITLE
Supervisor Report  reason noproc on Erlang 21.0 and Elixir 1.5.1

### ISSUE THREAD

**Issue by Darkpingouin** [elixir-lang/elixir#7842]
### Environment

```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]

Elixir 1.5.1
```

### Current behavior

Trying to run `mix phoenix.server` on a project I recieved but I get this error when trying to do so : 

```
=SUPERVISOR REPORT==== 9-Jul-2018::08:51:44.756661 ===
    supervisor: {local,'Elixir.Logger.Supervisor'}
    errorContext: start_error
    reason: noproc
    offender: [{pid,undefined},
               {id,'Elixir.Logger.ErrorHandler'},
               {mfargs,
                   {'Elixir.Logger.Watcher',start_link,
                       [{error_logger,'Elixir.Logger.ErrorHandler',
                            {true,false,500}}]}},
               {restart_type,permanent},
               {shutdown,5000},
               {child_type,worker}]
=CRASH REPORT==== 9-Jul-2018::08:51:44.792341 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.80.0>
    registered_name: []
    exception exit: {{shutdown,
                         {failed_to_start_child,'Elixir.Logger.ErrorHandler',
                             noproc}},
                     {'Elixir.Logger.App',start,[normal,[]]}}
      in function  application_master:init/4 (application_master.erl, line 138)
    ancestors: [<0.79.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.81.0>,normal}]
    links: [<0.79.0>,<0.42.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 193
  neighbours:

=INFO REPORT==== 9-Jul-2018::08:51:44.794509 ===
    application: logger
    exited: {{shutdown,
                 {failed_to_start_child,'Elixir.Logger.ErrorHandler',noproc}},
             {'Elixir.Logger.App',start,[normal,[]]}}
    type: temporary
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1]
```

I already tried to change Erlang version to 20.0 or 20.3 using `evm` since I read that it could be a problem to use `Erlang 21.0` with `Elixir 1.5.1.` But when running `mix phoenix.server` with this configuration I get this error : 

```
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
``` 

### Expected behavior

The project should compile and run on localhost:4000

**Comment by josevalim** [comment]
Yes, Elixir v1.5 does not support Erlang/OTP 21. You need Elixir v1.6.6 or downgrade Erlang to Erlang/OTP 20. Here is the compatibility table: https://hexdocs.pm/elixir/master/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp

**Comment by Darkpingouin** [comment]
@josevalim Thanks for the quick response, but as mentionned in my issue, when downgrading the Erlang version (I tried 20.3, 20.0, 18.0) I always get this issue when runnong `mix phoenix.server`

```
{"init terminating in do_boot",{undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{elixir,start_cli,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
```

**Comment by josevalim** [comment]
@Darkpingouin this usually means two things:

1. You cloned/downloaded Elixir but you did not compile it
2. You compiled Elixir with a more recent Erlang/OTP version than the one you have right now

How did you install both Erlang/OTP and Elixir?

**Comment by Darkpingouin** [comment]
I installed my Elixir versions using `kiex` and my Erlang version `evm`  if you know how to do it another way tell me how.

**Comment by josevalim** [comment]
@Darkpingouin I believe `kiex` is going to compile it from scratch. So my suggestion is to make sure you are on Erlang/OTP 20 and then compile 1.5 again.

Here is the install page with other install steps: http://elixir-lang.org/install.html

**Comment by Darkpingouin** [comment]
Thank you very much ! Apparently using `evm` to change erlang versions wasn't a good idea at all. I reinstalled it properly and it worked. :smile:
