### ISSUE TITLE
make: *** [lib/elixir/ebin/Elixir-Kernel.beam] Error 1

### ISSUE THREAD

**Issue by bussiere** [elixir-lang/elixir#785]
Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
make: **\* [lib/elixir/ebin/Elixir-Kernel.beam] Error 1

here is the crachdump ::

https://github.com/bussiere/Scripts/blob/master/erl_crash.dump

Regards
Bussiere

**Comment by SanAngeloMike** [comment]
FYI: I just got the exact same error and the exact same crash dump as the OP using a clone I made a few moments ago. No erlang directory. When I ran 
sudo make clean test
I still got the error. However,
sudo make clean
sudo make
gave me joy.

**Comment by coldneverdie** [comment]
make: *** [lib/elixir/ebin/Elixir.Kernel.beam] 错误 2

i come with the same error, but  the way not works
