### ISSUE TITLE
mix format produces too long lines as specified in config

### ISSUE THREAD

**Issue by pnowosie** [elixir-lang/elixir#7851]
Hello,
This quite strange example but if you use it together with `credo` in strict mode is a little pain.
Issue is that `mix format` re-formats code which then causes credo check failure (reporting too long line).
I've found workaround already and the example code is a weird, but maybe it won't be hard to fix.

### Environment

* Elixir & Erlang/OTP versions 
```
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.5 (compiled with OTP 19)
Mix 1.6.5 (compiled with OTP 19)
```
* Operating system:  Ubuntu linux 16.04 LTS

### Setup
``` .formatter.exs
[ #file: .formatter.exs
  inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  line_length: 80
]

#file: config\.credo.exs
 checks: [
    {Credo.Check.Readability.MaxLineLength, priority: :low, max_length: 80},
```

In code file
``` elixir
"string"
    |> (&say_hello(
      "01234567890123456789012345678901234567890123456789012", &1)).()
```
### Current behavior
`mix format` will fix code formatting to the following, where 2nd line is over 80 chars long

``` elixir
"string"
|> (&say_hello("01234567890123456789012345678901234567890123456789012", &1)).()
```

### Expected behavior
However when existing code is formated a little bit differently, e.g.:
``` elixir
"string"
|> (&say_hello("01234567890123456789012345678901234567890123456789012",
    &1)).()
```

after re-formatting it will looks like this
``` elixir
"string"
|> (&say_hello(
         "01234567890123456789012345678901234567890123456789012",
         &1
      )).()
```

**Comment by josevalim** [comment]
@pnowosie the formatter does not guarantee all lines will be below the length because it can only break the code under certain specific circumstances. If it can't find a good place to break the code, then there isn't much it could do.

Alternatively it could implement backtracking but that could be very harmful to performance. We have recently added such notes to the docs.
