### ISSUE TITLE
Add Supervisor.Spec to Deprecations page. More info needed

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#7867]
It has been deprecated, I need information regarded with what it has been replaced in order to submit a PR

replaced by Supervisor.child_spec/2  , and anything else?

cheers

**Comment by eksperimental** [comment]
CHANGELOG for v1.5 talks about it
https://github.com/elixir-lang/elixir/blob/v1.5/CHANGELOG.md#streamlined-child-specs

Should a warning be added in v1.7? and what about adding this to the deprecations page, since a warning notice in the module is showing since v1.5

**Comment by josevalim** [comment]
It is not in the deprecations page because it doesn't warn yet. The replacement is mentioned in `Supervisvor.Spec` module docs:

> The functions in this module are deprecated and they do not work with the module-based child specs introduced in Elixir v1.5. Please see the Supervisor documentation instead.

**Comment by eksperimental** [comment]
All clear then. Thank you
