### ISSUE TITLE
`mix new` lacks an option to replace all files, instead it asks one by one

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#7868]
### Environment
* Elixir & Erlang/OTP versions (elixir --version): master

### Current behavior

`mix new` lacks an option to replace all files, instead it asks the same question whether you want to replace it, everytime!

```console
$ mix new iex_print_table --module IExPrintTable
The directory "iex_print_table" already exists. Are you sure you want to continue? [Yn] y
* creating README.md
README.md already exists, overwrite? [Yn] y
* creating .formatter.exs
.formatter.exs already exists, overwrite? [Yn] y
* creating .gitignore
.gitignore already exists, overwrite? [Yn] y
* creating mix.exs
mix.exs already exists, overwrite? [Yn] y
* creating config
* creating config/config.exs
config/config.exs already exists, overwrite? [Yn] y
* creating lib
* creating lib/iex_print_table.ex
lib/iex_print_table.ex already exists, overwrite? [Yn] y
* creating test
* creating test/test_helper.exs
test/test_helper.exs already exists, overwrite? [Yn] y
* creating test/iex_print_table_test.exs
test/iex_print_table_test.exs already exists, overwrite? [Yn] y

Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:

    cd iex_print_table
    mix test

Run "mix help" for more commands.
```

### Expected behavior

Figure out a way to give option to replace all to avoid boring developer to death with the same question over and over and over

**Comment by YongHaoWu** [comment]
Maybe we can add a option named `--override` for `mix new `?
After scanning the code, I think I can work on this.

**Comment by josevalim** [comment]
I think it is fine as is. I can see only two scenarios:

1. You want to replace files in an existing project: then it is better to do it carefully one by one

2. You want to fully replace a project: then it is easier to remove the directory and run the command again

Thanks!
