### ISSUE TITLE
Logger.Translator.child_info/2 fails on supervisor reports including `:name`

### ISSUE THREAD

**Issue by arkgil** [elixir-lang/elixir#7889]
Hi there! I have a problem with Logger.Translator failing on supervisor reports with Elixir 1.6.6.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.6.6 & 20.3 (or 19.3)
* Operating system: macOS High Sierra 10.13.1

### Current behavior

`Logger.Translator.child_info/2` fails on supervisor progress reports which include a name of the process, e.g. the one reported by `supervisor3` - https://github.com/klarna/supervisor3/blob/master/src/supervisor3.erl#L1656.

The error looks as follows:

```
15:35:56.711 [error] :gen_event handler Logger.ErrorHandler installed at :error_logger
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Logger.Translator.child_info/2
        (logger) lib/logger/translator.ex:320: Logger.Translator.child_info(:debug, [name: LoggerTranslatorRepro.Server, mfargs: {Agent, :start_link, [#Function<0.78284505/0 in LoggerTranslatorRepro.init/1>, [name: LoggerTranslatorRepro.Server]]}, restart_type: :permanent, shutdown: 5000, child_type: :worker])
        (logger) lib/logger/translator.ex:240: Logger.Translator.report_supervisor_progress/2
        (logger) lib/logger/erlang_handler.ex:104: Logger.ErlangHandler.translate/6
        (logger) lib/logger/erlang_handler.ex:97: Logger.ErlangHandler.translate/5
        (logger) lib/logger/error_handler.ex:93: Logger.ErrorHandler.log_event/6
        (logger) lib/logger/error_handler.ex:33: Logger.ErrorHandler.handle_event/2
        (stdlib) gen_event.erl:574: :gen_event.server_update/4
        (stdlib) gen_event.erl:556: :gen_event.server_notify/4
```

This happens on Elixir 1.6.6, I couldn't observe this error on 1.5.3. Most probably the issue was introduced in the PR bringing integration with Erlang 21 `logger`, [this deletion](https://github.com/elixir-lang/elixir/commit/2c770ba9d65f1c75437b392a1782585d8db05cc6#diff-6bf697cfce89d8072ae720a3aa4b7e2bL107) removed the clause which handled the name of the child process.

If anyone's interested, [here is the repo](https://github.com/arkgil/logger_translator_repro) to reproduce the error.

### Expected behavior

Logger.Translator properly handles and prints out progress reports with process names.

I'll be happy to prepare a PR for this, if it's not intentional. If the change was intentional, maybe a good idea would be to log a warning when translator receives the report it can't handle?

**Comment by josevalim** [comment]
@arkgil a PR will be very welcome. :)

**Comment by arkgil** [comment]
@josevalim on it :)

**Comment by arkgil** [comment]
@josevalim now that I think about it - Erlang's and Elixir's supervisors always report child info with `id` key. This means that we can't test if the `name` is really picked up, and that we'll be trying to conform to 3rd party lib. Maybe a better idea would be to log, or at least ignore the report? Unfortunately current behaviour makes Logger crash 😢

**Comment by josevalim** [comment]
@arkgil yes it is important that we don't crash. :) We can probably just ignored malformed data. Although I believe those crashes will be unlikely when using OTP 21.
