### ISSUE TITLE
Cover summary sometimes not displayed

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#7898]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.8.0-dev (5f3ad5d09) (compiled with Erlang/OTP 21)

### Current behavior

When running `mix test --cover`, I've noticed the summary **is** present for e.g. decimal & hexpm, but **is not** for e.g. ecto & phoenix, not sure what's the culprit.

### Expected behavior

Summary is always displayed.

**Comment by josevalim** [comment]
It is because those projects have test_coverage configuration set. Probably something related to defaults.

**Comment by wojtekmach** [comment]
Neither decimal nor phoenix has test_coverage set and yet one has summary and the other does not, that's why it's weird.

**Comment by josevalim** [comment]
Just for sanity checking purposes: which OTP version?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
OTP 21 on all projects.

**Comment by wojtekmach** [comment]
OK I've found the issue, both Ecto & Phoenix have line like such:

```elixir
# test_helper.exs
Mix.shell(Mix.Shell.Process)
```

(https://github.com/elixir-ecto/ecto/blob/master/test/mix/test_helper.exs#L3)

which leaks -after the tests finished and control is given back to Mix.Tasks.Test, we're stuck with that and that explains why stuff hasn't been printed on screen.

**Comment by wojtekmach** [comment]
Probably needs to be fixed in Ecto etc.

**Comment by josevalim** [comment]
Great catch! I guess the proper fix would be to move those setup_all
callbacks in the relevant cases and use on_exit to revert it.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
