### ISSUE TITLE
Support an operator for binary concatenation

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#79]

**Comment by c0b** [comment]
why can't overlord the more intuitive `+` is that some limit of current implementation?

```elixir
iex(7)> "abc" <> "def"
"abcdef"
iex(8)> "abc" + "def" 
** (ArithmeticError) bad argument in arithmetic expression
    :erlang.+("abc", "def")
```

**Comment by tuvistavie** [comment]
@c0b You should use the mailing list if you want to propose new features.

**Comment by c0b** [comment]
no, github # issues is the better platform than ML, because I can subscribe this particular issue only, to subscribe a whole ML seems like too much information

**Comment by c0b** [comment]
@tuvistavie or do you know how to subscribe a particular thread only from a ML ?

**Comment by tuvistavie** [comment]
@c0b It is not a problem of which one is better, they have different purposes.
Please read the [CONTRIBUTING.md](https://github.com/elixir-lang/elixir/blob/master/CONTRIBUTING.md#using-the-issue-tracker) for more info about how to use both.

Of course you can subscribe to a particular thread, see the attached screenshot.
I think you should be subscribed automatically if you create a new topic.

![ggroup](https://cloud.githubusercontent.com/assets/1436271/12346336/ed3a2dee-bb96-11e5-9563-770df503098c.png)
