### ISSUE TITLE
mix escript.install <remote package> fails depending on your local directory

### ISSUE THREAD

**Issue by AnilRedshift** [elixir-lang/elixir#7901]
### Environment
elixir --version
Erlang/OTP 20 [erts-9.3.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.5 (compiled with OTP 20)

### Current behavior
There are several scenarios where calling `mix escript.install` can fail:

1. `git clone git@github.com:AnilRedshift/wand.git`
2. `cd wand`
3. `mix escript.install hex wand --force`

**Expected**: wand is installed from the remote hex repository.
 

**Actual**: 

> 
> Error while loading project :wand at /private/var/folders/_l/mlm71j9949x58bp66zqzl5p80000gn/T/mix-local-installer-fetcher-GnfCqg/deps/wand
> ** (Mix) Trying to load Wand.MixProject from "/private/var/folders/_l/mlm71j9949x58bp66zqzl5p80000gn/T/mix-local-installer-fetcher-GnfCqg/deps/wand/mix.exs" but another project with the same name was already defined at "/Users/anil/projects/wand/mix.exs"
> 

This happens when your current directory is in a project with the same name as the remote repository.

## Other repros
1. `mix new test`
2. `cd test`
3. modify the mix.exs file to contain a syntax error
4. `mix escript.install hex wand --force`

Actual:

> ** (SyntaxError) mix.exs:28: unexpected token: end
>     (elixir) lib/code.ex:629: Code.load_file/2
>     (mix) lib/mix/cli.ex:29: Mix.CLI.proceed/1
>     (elixir) lib/code.ex:677: Code.require_file/2

This latter one is pretty bad IMO. I would prefer global tasks to succeed regardless of whether the current project builds properly.

I can split these out into two bugs as needed, but they are related in terms of making global mix tasks more robust regardless of your local directory.

**Comment by AnilRedshift** [comment]
The user story is trying to tell others how to add an escript (or archive) package, but then having to caveat that with a bunch of error handling depending on the state of their current directory. As adding an escript or an archive is independent of your local directory, this should work regardless.

**Comment by josevalim** [comment]
@AnilRedshift if you have an error in your local `mix.exs`, then any mix command will fail, including `help`, as we need to load the local `mix.exs` for any customization the user may have done on how mix works.

The first error is fixed on Elixir v1.7, which had a release candidate out yesterday.

Thanks for the reports!
