### ISSUE TITLE
MIX_QUIET=1 should silence warnings from mix archive.build

### ISSUE THREAD

**Issue by fapdash** [elixir-lang/elixir#7912]
### Environment

* Elixir & Erlang/OTP: Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.6.6 (compiled with OTP 19)
* Mix: Mix 1.6.6 (compiled with OTP 19)
* Operating system: Ubuntu 16.04

### Current behavior

```
~/repos/credo$ MIX_QUIET=1 mix archive.build
warning: redefining module Bunt (current version loaded from /home/fap/.mix/archives/bunt-0.2.0/bunt-0.2.0/ebin/Elixir.Bunt.beam)
  lib/bunt.ex:1

warning: redefining module Bunt.ANSI.Sequence (current version loaded from /home/fap/.mix/archives/bunt-0.2.0/bunt-0.2.0/ebin/Elixir.Bunt.ANSI.Sequence.beam)
  lib/bunt_ansi.ex:1

warning: redefining module Bunt.ANSI (current version loaded from /home/fap/.mix/archives/bunt-0.2.0/bunt-0.2.0/ebin/Elixir.Bunt.ANSI.beam)
  lib/bunt_ansi.ex:29

warning: String.strip/1 is deprecated, use String.trim/1
  /home/fap/repos/credo/deps/poison/mix.exs:4

...

```
### Expected behavior
No output at all.

**Comment by josevalim** [comment]
Those warnings are not coming from Mix but rather the compiler, so there isn't much Mix can do about those. Why do you want to disable warnings from building your own project?

**Comment by fapdash** [comment]
The mix task is executed during a docker build and the output should stay as clean as possible.
Problem is that even with `mix archive.build >/dev/null` the warnings still get printed.
Am I missing something?

**Comment by josevalim** [comment]
Yeah, piping to stderr sounds like the way to go then.

**Comment by NobbZ** [comment]
@fapdash you really should take care of the warnings instead of silencing them, also after I have gone through a lot with docker, I want to give you a little advise: Prefer verbose over quite modes when running scripts, it will help you later when you need to dig into failing builds.
