### ISSUE TITLE
representation of Elixir structs in Erlang AST

### ISSUE THREAD

**Issue by tim2CF** [elixir-lang/elixir#7913]
### Environment

* Elixir & Erlang/OTP versions: Elixir 1.6.6 / Erlang 21
* Operating system: macOS

### Current behavior

Elixir module

```elixir
defmodule Car do

  defstruct [:year, :price, :model]

  def can_buy?(%Car{price: price}, money) when (price <= money), do: true
  def can_buy?(%Car{}, _), do: false

end
```

is translated by Elixir compiler to Erlang AST equivalent to the Erlang source code

```erlang
-file("secret.ex", 1).

-module('Elixir.Car').

-compile(no_auto_import).

-export(['__info__'/1, '__struct__'/0, '__struct__'/1,
	 'can_buy?'/2]).

-spec '__info__'(attributes | compile | functions |
		 macros | md5 | module | deprecated) -> any().

'__info__'(module) -> 'Elixir.Car';
'__info__'(functions) ->
    [{'__struct__', 0}, {'__struct__', 1}, {'can_buy?', 2}];
'__info__'(macros) -> [];
'__info__'(attributes) ->
    erlang:get_module_info('Elixir.Car', attributes);
'__info__'(compile) ->
    erlang:get_module_info('Elixir.Car', compile);
'__info__'(md5) ->
    erlang:get_module_info('Elixir.Car', md5);
'__info__'(deprecated) -> [].

'__struct__'() ->
    #{'__struct__' => 'Elixir.Car', model => nil,
      price => nil, year => nil}.

'__struct__'(_@1) ->
    'Elixir.Enum':reduce(_@1,
			 #{'__struct__' => 'Elixir.Car', model => nil,
			   price => nil, year => nil},
			 fun ({_@2, _@3}, _@4) -> maps:update(_@2, _@3, _@4)
			 end).

'can_buy?'(#{price := Vprice@1,
	     '__struct__' := 'Elixir.Car'},
	   Vmoney@1)
    when Vprice@1 =< Vmoney@1 ->
    true;
'can_buy?'(#{'__struct__' := 'Elixir.Car'}, _) -> false.
```

Which formally is not correct. Elixir struct always has fixed amount of fixed fields, but in Erlang patterns we can see maps with different amount of different fields:

```erlang
'can_buy?'(#{price := Vprice@1,
	     '__struct__' := 'Elixir.Car'},
	   Vmoney@1)
    when Vprice@1 =< Vmoney@1 ->
    true;

'can_buy?'(#{'__struct__' := 'Elixir.Car'}, _) -> false.
```

### Expected behavior

```erlang
'can_buy?'(#{price := Vprice@1,
	     year := _,
	     model := _,
	     '__struct__' := 'Elixir.Car'},
	     Vmoney@1)
    when Vprice@1 =< Vmoney@1 ->
    true;

'can_buy?'(#{price := _,
	     year := _,
	     model := _,
	     '__struct__' := 'Elixir.Car'}, 
	     _) -> false.
```

### Comment

I founded this issue when I was working on https://github.com/josefs/Gradualizer tool. Strict representation of Elixir structs in Erlang AST is requirement for gradual static type system.

**Comment by michalmuskala** [comment]
This is intentional and extremely unlikely to change. We always match on the subset of keys. The guarantees structs provide are compile-time and not runtime. This minimises the runtime overhead of using structs.

**Comment by tim2CF** [comment]
I just think that this means that currently formal struct definitions are conflicting with actual final AST
https://github.com/elixir-lang/elixir/blob/4b4e9e99879859746cc2c94c5a280a3c92cd61a9/lib/elixir/lib/uri.ex#L19-L28
Or maybe I miss something?

**Comment by michalmuskala** [comment]
Map pattern matches are always matching on a subset of keys. In such case typespecs are overly restrictive with regards to actual implementation, but that's often the case that a function could actually work with much more types compared to what typespecs describe. Consider:

```elixir
@spec is_positive(integer()) :: boolean()
def is_positive(n) do
  n > 0
end
```

There's nothing in the function that enforces the argument is an integer, yet the type specifies it only makes sense to call it with an integer - that's generally perfectly fine.

**Comment by josevalim** [comment]
To build on what @michalmuskala said, this is not specific to structs or Elixir either.

For example, imagine you define the following GenServer state:

    @type state :: %{counter: integer(), receiver: pid()}

Throughout the GenServer implementation, sometimes you will match on both fields, sometimes on some and sometimes on none. :)
