### ISSUE TITLE
\n or No \n at the end of file? 

### ISSUE THREAD

**Issue by decentname** [elixir-lang/elixir#7918]
Credo throws a warning that there should be \n at the end of file while using mix format removes that \n. I think we need to decide whether we want this or not and accordingly update the formatting rules or credo rules.

**Comment by josevalim** [comment]
@decentname [`mix format` definitely adds a new line at the end](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/format.ex#L397) and [we have tests that show so](https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/mix/tasks/format_test.exs).

If you believe Elixir is still misbehaving, please fill in the issue template accordingly. Let us know the Elixir version and provide more steps to reproduce the issue. Thanks.
