### ISSUE TITLE
Logger metadata not removed 

### ISSUE THREAD

**Issue by albertored** [elixir-lang/elixir#7926]
### Environment

* Elixir & Erlang/OTP versions: Erlang/OTP 20.1, Elixir 1.6.6
* Operating system: Ubuntu 16.04

### Current behavior

When setting a logger metadata to `:nil` using the `Logger.metadata/1` function the given metadata is removed from the keyword list and not printed. If instead this is done via a single log call (for instance `Logger.debug("bar", foo: nil)` the metadata is not removed and for example the console backend prints it as `foo=`

```
iex> require Logger
Logger
iex> Logger.configure_backend(:console, metadata: [:foo])
:ok
iex> Logger.metadata(foo: 123)
:ok
iex> Logger.debug("bar")
foo=123 [debug] bar
iex> Logger.debug("bar", foo: 456)
foo=456 [debug] bar
iex> Logger.debug("bar", foo: nil)
foo= [debug] bar
iex> Logger.metadata(foo: nil)
:ok
iex> Logger.debug("bar")
[debug] bar
iex> Logger.debug("bar", foo: nil)
foo= [debug] bar
```

### Expected behavior

I would expect that the behavior is the same, specifically that setting a metadata to `nil` removes it always (in the case of single call only for that call).

I think it is sufficient to implement the logic of the function `Logger.metadata/1` in the function `Logger.bare_log/3` but without saving the changed metadata in the process dictionary.

I can try to push a PR if you think is worth.

On the other hand if this is intended I think we should specify in the documentation that setting a metadata to nil in single log calls does not remove it.

**Comment by josevalim** [comment]
@albertored A PR would be great, although I think we should handle it here: https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/formatter.ex#L165-L167

I.e. if the value is nil, we should return an empty list. :)

What do you think?

**Comment by albertored** [comment]
thanks @josevalim for the suggestion!

It will work also in this way but IMHO the inconsistency remains. If we decide to not print metadatas with `nil` values in the `Logger.Formatter` module than we should also use a simply `Keyword.merge(metadata, keyword)` [here](https://github.com/elixir-lang/elixir/blob/1ec9d1d7bdd01665deb3607ba6beb8bcd524b85d/lib/logger/lib/logger.ex#L409), right?

But in this case I'm still in favour of the first solution in order to avoid polluting the process dict with useless `nil` values

**Comment by josevalim** [comment]
@albertored yeah. Maybe there is a faster option. I will explore it a bit and come back.

**Comment by albertored** [comment]
Perfect as always ;-) thanks!
