### ISSUE TITLE
You can define function whose name starts with uppercase character

### ISSUE THREAD

**Issue by SekiT** [elixir-lang/elixir#7946]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 20 [erts-9.3.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.8.0-dev (f3ef799d3) (compiled with Erlang/OTP 20)
```
* Operating system: macOS High Sierra 10.13.6

### Current behavior

Using macro below, you can define function whose name starts with uppercase character, but cannot call it.

```ex
iex(1)> defmodule A do  
...(1)>   defmacro define(name) do
...(1)>     quote do
...(1)>       def unquote(name)(), do: :foo   
...(1)>     end
...(1)>   end
...(1)> end
{:module, A,
 <<70, 79, 82, 49, 0, 0, 4, 108, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 132,
   0, 0, 0, 14, 8, 69, 108, 105, 120, 105, 114, 46, 65, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, {:define, 1}}
iex(2)> require A
A
iex(3)> defmodule B do
...(3)>   A.define(:Func)
...(3)> end
{:module, B,
 <<70, 79, 82, 49, 0, 0, 3, 192, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 124,
   0, 0, 0, 14, 8, 69, 108, 105, 120, 105, 114, 46, 66, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, {:Func, 0}}
iex(4)> B.Func
Func/0
iex(4)> B.Func()
** (SyntaxError) iex:4: syntax error before: '('
```

### Expected behavior

In the above, defining `B` (more precisely, `A.define(:Func)`) should be compile error.

**Comment by josevalim** [comment]
You can define functions with such names, but you have to quote them before using:

    B."Func"()

**Comment by OvermindDL1** [comment]
And for a use-case, this is requirement for compatibility with quite a number of Erlang things (like the ASN.1 parser that I'm actively using).

**Comment by SekiT** [comment]
I did not know the quoting or any use case. Sorry for my lack of research before making issue.

**Comment by josevalim** [comment]
@SekiT it is no problem at all. If you think there is a place we can improve our docs, we will be glad to hear about it too.
