### ISSUE TITLE
Function.capture does not guard for arity

### ISSUE THREAD

**Issue by GriffinMBNCC** [elixir-lang/elixir#7983]
### Environment

* Elixir 1.7.0/1.8.0-dev

### Current behavior

[`Function.capture`](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/function.ex#L37) does not guard against invalid arity. For example:

```
iex(1)> Function.capture(String, :length, 900)
&String.length/900
```

### Expected behavior

Throw an error as it would for standard function captures:

```
iex(2)> &String.length/900
** (CompileError) iex:2: invalid arity for &, expected a number between 0 and 255, got: 900
    (elixir) src/elixir_fn.erl:38: :elixir_fn.capture/3
```

Happy to make a PR later, but am not at my computer at the moment.

**Comment by josevalim** [comment]
Can you please report this to Erlang? We simply delegate to Erlang here. The function we call is: `erlang:make_fun/3`. Thanks!
