### ISSUE TITLE
Isolated case of function call with missing parens not detected by the formatter

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#7987]
### Current behavior

This issue was spotted while reading the Elixir codebase. 

`DateTime.convert/2` contains a function call to `to_iso_days` that should include parens, but it does not:

https://github.com/elixir-lang/elixir/blob/691460a6e661f174476c69153776cba2f8a47341/lib/elixir/lib/calendar/datetime.ex#L797-L804

However, a few lines above, there is a similar pipe with the parens:

https://github.com/elixir-lang/elixir/blob/691460a6e661f174476c69153776cba2f8a47341/lib/elixir/lib/calendar/datetime.ex#L639-L651

When running the formatter `bin/elixir bin/mix format` it does not include the parens, and `bin/elixir bin/mix format --check-formatted` says everything is ok. That's why the current `master` branch is green.

### Expected behavior

I would expect the formatter to include the parens.

**Comment by fertapric** [comment]
🤔 I guess adding the parens would modify the final AST.

**Comment by josevalim** [comment]
Right. It is a function call semantically, but the formatter does not know about semantics. In fact, somebody could import their own pipe operator that behaves like addition, and adding parens would then definitely break their code.
