### ISSUE TITLE
New Windows 10 install, can't recognize elixerc command

### ISSUE THREAD

**Issue by 98-f355-f1** [elixir-lang/elixir#7998]
Hello,

I just installed Elixer/Erlang via the Windows Installer route... I have confirmed with elixer --version, iex, erl works too, but..

`C:\Users\MaraTom\Desktop\Elixer>elixir --version
Erlang/OTP 21 [erts-10.0.1] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.7.1 (compiled with Erlang/OTP 19)`

How do you compile a program?  I ran 'elixerc' <filename.ex> and it says not recognized command.

Any help please, total new here.

**Comment by josevalim** [comment]
Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!
