### ISSUE TITLE
Dialyzer error when collecting bitstrings

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#8001]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.1 (compiled with Erlang/OTP 21)

### Current behavior
Collecting bitstrings into `<<>>`
```
# data contains list of 5 bit unsigned integers
for d <- data, into: <<>>, do: <<d::size(5)>>
```
results in dialyzer complaining
```
Guard test is_binary(__@1::<<_:5>>) can never succeed
```

Note: specifying type silences the warning
```
for d <- data, into: <<0::size(0)>>, do: <<d::size(5)>>
```

### Expected behavior
No dialyzer error as the code works correctly

**Comment by josevalim** [comment]
Closing in favor of #8036.
