### ISSUE TITLE
warn_on_unnecessary_quote should only warn for app code, not deps / library code within given app

### ISSUE THREAD

**Issue by mkralla11** [elixir-lang/elixir#8009]
### Environment

* Elixir (elixir --version):  elixir >= 1.7
* Operating system: Apline

### Current behavior

After upgrading to elixir >= 1.7, I receive warnings regarding unnecessary quoting of atoms _within library code.

### Expected behavior

There should be a way to configure the new option to only warn code for which you _should be changing_ in your app, not code that is a dependency / library.

**Comment by josevalim** [comment]
@mkralla11 This is a warning like any other. Elixir does not disable warning for dependencies intentionally. This makes them more visible and allow everyone to contribute fixes.

However, we do disable --warnings-as-errors, so warnings in those deps do not break your app.

**Comment by mkralla11** [comment]
Understood! Thank you for the quick response.
