### ISSUE TITLE
Unable to load crypto library

### ISSUE THREAD

**Issue by Mayurgupta3** [elixir-lang/elixir#8010]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.6.6 (compiled with OTP 19)

* Operating system: 
kali Linux 

### Current behavior

23:33:36.597 [warn]  The on_load function for module crypto returned:
{:error, {:load_failed, 'Failed to load NIF library /usr/lib/erlang/lib/crypto-4.3/priv/lib/crypto: \'libcrypto.so.1.0.0: cannot open shared object file: No such file or directory\''}}

** (UndefinedFunctionError) function :crypto.strong_rand_bytes/1 is undefined (module :crypto is not available)
    :crypto.strong_rand_bytes(64)
    lib/mix/tasks/phoenix.new.ex:484: Mix.Tasks.Phoenix.New.random_string/1
    lib/mix/tasks/phoenix.new.ex:223: Mix.Tasks.Phoenix.New.run/4
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:80: Mix.CLI.run_task/2

**Comment by lackac** [comment]
Please use the [ElixirForum](https://elixirforum.com/) or StackOverflow for questions/help, where a wider community will be able to help you. The issues tracker is reserved for issues only. Thank you!

**Comment by Mayurgupta3** [comment]
Okk, Thank you!

**Comment by michalmuskala** [comment]
The issue, most probably, is because many distributions split erlang into multiple packages. Just installing erlang usually does not install all components. There might be some additional `erlang-crypto` package you need to install.

The advice of using ElixirForum or StackOverflow is a good one, though - you can usually expect much faster response there.

**Comment by josevalim** [comment]
In this case though i think the issue is on the `openssl` bindings, since the crypto module was found, it just can't be loaded.
