### ISSUE TITLE
Consider change ExUnit.Diff to public API

### ISSUE THREAD

**Issue by Eiji7** [elixir-lang/elixir#8019]
Here is @josevalim comment on forum:

> Thanks @Eiji! This is a good example. I recommend you to start a discussion on Elixir issues tracker. We do not track comments or discussions on the forum as feature requests.
> 
> Note that it is unlikely that exporting ExUnit.Diff as is would be useful to you, as the current algorithm is recursive on itself, and you want to support more data types than the ones we do. There are different ways we could solve this, for example, by making the recursive function an argument on ExUnit.Diff, introducing a protocol, or by breaking ExUnit.Diff into smaller, reusable bits. So when opening the issue, please make sure that you provide a more complete proposal with examples on how you believe the ExUnit.Diff should be exported.

Based on it I would like to start a proposal to make `ExUnit.Diff` module public, so everyone could use it without worry that it would be modified or even removed in future releases. Personally I think that introducing protocol would be the best way to achieve it. I'm also not sure if it should be kept in `ExUnit` application since lots of developers would be able to use it or libraries based on it in `prod` environment and `ExUnit` at least for newbie is associated only with tests.

In short I would like to propose creating a new protocol called `Diff` (`Elixir.Diff`). It should define at least `compare/2` and `compare/3` (optional `opts` argument). Here are smaller topics to discuss:

- [ ] Should we move `Diff` module from `ExUnit` application to `Elixir`
- [ ] How we want to implement it (for example using protocol)
- [ ] What type of return we should provide in public API (type documentation)

*Note*: For now I do not have lots of time to describe it well (hope it's enough information), because I'm in the process of relocation. If you would like to ask any questions to me then you need to expect some delay (sorry for that).

Here you can find more information from what point this issue comes:
1. [My question on forum about adding different diff algorithms](https://elixirforum.com/t/any-plans-for-other-diff-algorithms-like-string-myers-difference-method-but-for-other-data-types/2035?u=eiji)
2. [José Valim forum topic about problem with private APIs in Elixir libraries](https://elixirforum.com/t/psa-do-not-use-private-apis-request-a-feature-instead/15449?u=eiji)

**Comment by josevalim** [comment]
Hi @Eiji7. I don't believe this warrants a protocol in Elixir itself. If the goal is to make this usable outside of testing, then we can discuss adding small functions throughout Elixir's standard library that makes it easier to assemble your own.

**Comment by Eiji7** [comment]
@josevalim As said I do not have enough time, so I can't think about it as much as I would like. Unfortunately I did not had even chance to give a try for a new Elixir release. I think that return like in `String.myers_difference/2` (of course for all data types) should be enough for library maintainers at least at start (don't remember this topic well, so maybe some optional `opts` could be also useful in some cases).

**Comment by josevalim** [comment]
@Eiji7 would you mind reopening this issue then when you have time to get involved? This is a feature request and if the requestor does not have time to discuss it, there isn't much we can do. Thanks!

**Comment by josevalim** [comment]
Also please see #8022 and #8021 where we have extracted functions used by `ExUnit.Diff` to make custom implementations more accessible. We will be glad to reopen this once  a solid proposal is in place. Thanks.

**Comment by Eiji7** [comment]
@josevalim ok, no problem
It will still take some time to finish all things with relocation. Almost all furniture will be custom and deliver would not be soon. Before it will be delivered I have also other things to do and of course job. When everything will be finished I could even consider contribute also in code.

**Comment by Eiji7** [comment]
@josevalim Still can't help with code **now**, but I'm ok to chat from today.

I take a look at my old code. What I would need from `Elixir` is to have a unique format of difference for all supported data types which could be used to `patch` original data and `revert` changes.

Maybe we should consider adding new struct in case we are comparing large data. For example:

```elixir
type opts :: [keep_unmodified_data: boolean()]

type t :: %__MODULE__ {
  data: term(),
  index: non_neg_integer(),
  type: :del | :eq | :ins
}
```

In such way example we could have for example:

```elixir
iex(1)> Diff.compare("aaabbbccc", "aaaxxxccc")
[%Diff{data: "aaa", index: 0, type: :eq}, %Diff{data: "bbb", index: 3, type: :del}, %Diff{data: "xxx", index: 3, type: :ins}, %Diff{data: "ccc", index: 6, type: :eq}]

iex(2)> Diff.compare("aaabbbccc", "aaaxxxccc", [keep_unmodified_data: false])
[%Diff{data: "bbb", index: 3, type: :del}, %Diff{data: "xxx", index: 3, type: :ins}]
```

This format would help a lot for example when comparing changes in big articles.

What do you think about it?

**Comment by josevalim** [comment]
@Eiji7 I believe such format is fine but I still do not understand why this format needs to be part of core, especially if it intends to be more than what we need to do in `ExUnit.Diff` today. Also note that we extracted some of ExUnit.Diff functionality into public functions already, which should make rolling your own easier.

**Comment by Eiji7** [comment]
@josevalim I see your point, but think that you want create library using such functions. For example what you will have for maps? If you do not know algorithm names then how you will look for any diff method? If I remember correctly I have found Myers difference accidentally. Also documentation is confusing when searching by `diff` word. Here are some examples:

```elixir
Date.diff/2
"Calculates the difference between two dates, in a full number of days.(…)"
iex> Date.diff(~D[2000-01-03], ~D[2000-01-01])
2

MapSet.difference/2
"Returns a set that is map_set1 without the members of map_set2.(…)"
iex> MapSet.difference(MapSet.new([1, 2]), MapSet.new([2, 3, 4]))
#MapSet<[1]>

String.myers_difference/2
"Returns a keyword list that represents an edit script.(…)"
iex> string1 = "fox hops over the dog"
iex> string2 = "fox jumps over the lazy cat"
iex> String.myers_difference(string1, string2)
[eq: "fox ", del: "ho", ins: "jum", eq: "ps over the ", del: "dog", ins: "lazy cat"]
```

Everything is in different format, in different naming and for different solutions. Unlike `ExUnit` there is no way to diff every term in any way. Also adding opts like in example requires to perform extra iteration on results, so maybe (not sure) easier way is to copy sources of those functions and implement something similar in my library, but then I would need to track every change in lots of modules and check if there are any changes to diff functions.

Please let me know if I'm wrong somewhere.

**Comment by josevalim** [comment]
Yes, each data structure is going to have meaningful difference operation relevant to its domain.

For example, it makes no sense for `MapSet.difference/2` to return the same diff as ExUnit.Diff. The ExUnit.Diff may actually try to be recursive and find exactly how two values are different, which would just be incorrect and too expensive for everybody using it as a set (which is its primary use case).

Elixir makes no attempt to unify those and that's not a problem we are interested in solving. They are different operations with different purposes which just happens to share the same name across domains.

If you are working on a problem that requires diffing, then you likely need to investigate each data type individually based on the problem you are solving. It may be that the medium you want to show those diffs also largely impact on the algorithms and solutions. Even for a simple string, you may want to choose between a byte diff, grapheme diff, word diff or line diff.

**Comment by Eiji7** [comment]
@josevalim ok, so I see that I would need to write my own implementations anyway no matter what happens in core. Also good point for string example. I need to remember that. `MapSet` is only example. Originally I do not even tried to write any diff function for it. I will need to think about it later. Thanks for all of your explanations.
