### ISSUE TITLE
Add Mix.Config.config/1 - support for including sys.config format config files in the generated sys.config

### ISSUE THREAD

**Issue by jjl** [elixir-lang/elixir#8029]
sys.config may contain in addition to an `{appname, config}` tuple, a (list) string filename. This has the effect of including that config and merging it to the configuration thus far accrued.

At present, I see no means of generating this form.

I propose `config/1` to take a filename (binary) and add it to the config.

Pros:
- Makes it easier to build a release and selectively override configuration at boot time

Cons:
- Order sensitive. I haven't looked to see if order is preserved at present.
- Could be confusing (as if the config system isn't confusing enough already!)

**Comment by josevalim** [comment]
You can do `import_config` to import any other configuration. If you believe this is not enough, please send a proposal to the mailing list, which would be the best place to discuss new features. Thank you.
