### ISSUE TITLE
mix docs ** (RuntimeError) module ... was not compiled with flag --docs

### ISSUE THREAD

**Issue by walkr** [elixir-lang/elixir#8034]
I'm trying to run `mix docs` inside this project [lib_cleanex](https://github.com/walkr/lib_cleanex)

### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.1 Erlang/OTP 21 [10.0.4]
* Operating system: macOS

### Current behavior

```
$ mix docs

** (RuntimeError) module Cleanex.Cleanable.Any was not compiled with flag --docs
    (ex_doc) lib/ex_doc/retriever.ex:154: ExDoc.Retriever.export_docs?/1
    (ex_doc) lib/ex_doc/retriever.ex:138: ExDoc.Retriever.get_module/2
    (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
    (ex_doc) lib/ex_doc/retriever.ex:116: ExDoc.Retriever.docs_from_modules/2
    (ex_doc) lib/ex_doc.ex:107: ExDoc.generate_docs/3
    (ex_doc) lib/mix/tasks/docs.ex:202: anonymous fn/6 in Mix.Tasks.Docs.run/3
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_doc) lib/mix/tasks/docs.ex:201: Mix.Tasks.Docs.run/3
```

### Expected behavior

Should compile and create docs.

Any thoughts? 

Thank you!

**Comment by josevalim** [comment]
Please update your ExDoc version. :) `~> 0.19` should be good enough!

**Comment by walkr** [comment]
Yep! It was the mix.lock that forced an older version of ex_doc even though I've specified ">= 0.0.0".
Regards!
