### ISSUE TITLE
Change in `mix test` exit code behavior in Elixir 1.7

### ISSUE THREAD

**Issue by grantovich** [elixir-lang/elixir#8040]
### Environment

* Erlang/OTP 21
* Elixir 1.7.1
* Alpine Linux 3.8

### Current behavior

In Elixir versions prior to 1.7, `mix test` returned exit code 0 if there were no tests to run. Since Elixir 1.7, `mix test` returns exit code 1 in this scenario. This also applies to umbrella projects: if any applications in the umbrella have no tests, `mix test` now returns exit code 1, even if all tests passed in applications that had tests.

(note: I did test this with Elixir 1.6.6 and Erlang/OTP 21 to confirm it wasn't an Erlang/OTP change)

### Expected behavior

I couldn't find any direct mention of exit codes in the Elixir 1.7 changelog, so I'm not sure whether this new behavior is technically "expected". However, it is not backwards-compatible with the common CI behavior of treating a test command as "failed" if it returns a non-zero exit code. I encountered this on an umbrella project where one of the applications has no tests; it's unclear how we should work around this issue beyond adding an empty `assert true` test case to that application.

If this isn't deemed a bug, advice on how to work around it for CI workflows would be appreciated 🙂

**Comment by josevalim** [comment]
For now, the best is to add a dummy test. Although we will likely revert the commit or put it behind a flag.

**Comment by josevalim** [comment]
Hi @grantovich, actually I cannot reproduce this issue:

```
$ mix new umbrella --umbrella
$ cd umbrella/apps
$ mix new a
$ mix new b
$ rm -rf test/a_test.exs
$ mix test
==> a


Finished in 0.00 seconds
0 failures

Randomized with seed 615582
==> b
..

Finished in 0.07 seconds
1 doctest, 1 test, 0 failures

Randomized with seed 615582
$ echo $?
0
```

Are you by any chance using the `--only` flag or something similar?

**Comment by grantovich** [comment]
> Are you by any chance using the `--only` flag or something similar?

This is using `mix test` with no flags (and without any aliases for `test`). I notice my output is different from yours on the project where I encountered this issue. It looks like:

```
$ mix test
==> app_one
............

Finished in 0.2 seconds
12 tests, 0 failures

Randomized with seed 570130
==> app_two
There are no tests to run
==> app_three
.

Finished in 0.1 seconds
1 test, 0 failures

Randomized with seed 570130
$ echo $?
1
```

Note that where yours outputs the runtime, failure count, and random seed for the app with no tests, mine only prints `There are no tests to run`. Interestingly, with Elixir 1.7.1 this line is in bold red text, but with Elixir 1.6.6 it is in the default text color.

I will try to reduce this to a minimal example that shows the issue. I will say it doesn't seem specific to the umbrella context — when I `cd` into an individual app directory and run `mix test` there, it has the same exit code behavior and prints the same `There are no tests to run` line.

**Comment by josevalim** [comment]
Oh, I see what I missed. Ok, I got this. I will revert it for now and discuss it accordingly.

**Comment by grantovich** [comment]
Many thanks @josevalim for the quick investigation 🙇

**Comment by davich** [comment]
Thanks for this! We hit the same issue.
