### ISSUE TITLE
Warn for nested comparison with ==, ===, != and !== operators

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#8045]
PR https://github.com/elixir-lang/elixir/pull/7773 introduced a warning for the `<`, `>`, `<=` and `>=` nested operators. We should have a similar one for nested equality checks - they also won't do what might be expected.

**Comment by josevalim** [comment]
I think we will have false positives. Like this: `(foo == var) == true`. It doesn't make much sense, but it can happen, especially given this code can be generated by macros.

This could also happen:

    (foo == bar) == expect_true_or_false

**Comment by michalmuskala** [comment]
Yeah, I guess you're right. I don't think we could remove those false positives.
