### ISSUE TITLE
Incorrect leaking variable warning

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#8052]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.8.0-dev (b49d7c6d0)
* Operating system: macOS

### Current behavior

Given the following code a warning about "leaking variable from case" is produced:
```elixir
defmodule Test do
  def run_script(driver) do
    case start(driver) do
      {:ok, driver} -> :ok
      {:error, driver} -> {:error, driver}
    end
  end

  def start(x), do: x
end
```

### Expected behavior

This warning is incorrect in this case - yes, the variable is not used (the `driver` variable in the `:ok` case), but there's no "leaking" of it anywhere. The warning shouldn't be issued here.

Original report, courtesy of @jjl

**Comment by josevalim** [comment]
Well, it doesn't leak but it could leak. In the same way that:

```elixir
if foo do
  bar = 1
end
```

could leak `bar` but it doesn't. In fact, the variables in function head did leak until 1.3 (iirc). It was considered a bug though and it was the first leaking bug that we fixed.

Does it make sense?

**Comment by josevalim** [comment]
@michalmuskala did you try it in a module?

```iex
iex(1)> defmodule Foo do
...(1)> def bar do
...(1)> if true do
...(1)> baz = 1
...(1)> end
...(1)> end
...(1)> end
warning: variable "baz" is unused
  iex:4
```

**Comment by jjl** [comment]
The main problem I have with it is that it's *huge*. I'd quite like the option to be able to turn it off if it's going to remain dumb.

**Comment by michalmuskala** [comment]
I think the "leaking" warning should only be produced if there is any real possibility of it causing issues. Otherwise it's just noise. It's often to have two branches of `case` use the same variables. Using the same variable in two branches of `case` is hardly a "leaking" and the warning as it is right now is extremely verbose. The information about unused variable is lost amongst the warning message.

**Comment by josevalim** [comment]
@michalmuskala so you are basically arguing about not emitting the warning at all because **there is no chance variables will leak**.

**Comment by josevalim** [comment]
What we can do is to make it clear that part of the warning is a HINT and repeat the variable name at the end for convenience, to make it easy to scan. Otherwise I see no other option than getting rid of the hint altogether.

**Comment by michalmuskala** [comment]
Yes, I argue that in case variables are only used in the head of case, the warning shouldn't be emitted. The warning should be emitted in case like this:
```elixir
  def run_script(driver) do
    case start(driver) do
      {:ok, _driver} -> 
        run = 1
        :ok
      {:error, driver} ->
        run = 2
        {:error, driver}
    end
  end
```

where it's clear the intention was to export the variable. Case head is not such an intention.

**Comment by josevalim** [comment]
Well, even if we accept that there is no intention of overriding on case heads, having to track from where the variable is from (head or match) is non trivial and would require at least a new field on `Macro.Env`, which I don't think is worth it.

So we either accept all rebindings are equal or we remove the warning. I think the warning is still more help than harm, so my vote is to keep and improve its ergonomics.

**Comment by jjl** [comment]
Improved ergonomics suggestion: make the tip a link to more information, like rust and purescript do for errors.

**Comment by michalmuskala** [comment]
@josevalim Wouldn't be able to avoid this warning if we expanded patterns and bodies in case separately? By keeping the env struct after expanding the pattern, we would know which variables where defined there.

**Comment by josevalim** [comment]
@michalmuskala we will either have to introduce a new field to track variables from those specific places or we will need to traverse the new ENV struct and compare it to the old ENV struct to find those, which won't be cheap, especially on huge module bodies.

I am more inclined to go with a command to get extra information, as suggested by @jjl. Because we can even add useful information to simple warnings like "unused variables foo", telling people to use underscores if they don't intend to use such vars. There are other warnings, such as mixing function clauses with defaults, which are very long and they could be made shorter.

Although I don't want it to be a link, you shouldn't need internet access to get more information about an error. @jjl is there a command line possibility in those languages too? If so, how does it look like?

**Comment by jjl** [comment]
@josevalim Not that I'm aware of, however some languages make you give a `--debug` or similar to get extra information. I'd actually be quite willing to have a flag that opted into potentially expensive checks (such as the one @michalmuskala describes) instead.

**Comment by josevalim** [comment]
@jjl I think a `--debug` wouldn't help here because it means adding complexity to the compiler that will mostly likely end-up leaking to user land, due to the macro system. But if we can put the lengthy explanations in a separate flag, I don't see a need for `--debug`. I am thinking something like this:

```
warning: unused variable "foo" (learn more by running: elixir -h elixir:unused_var)
    iex:4 
```

There is probably a better way to add the "learn more" information but that should be a starting point.

**Comment by michalmuskala** [comment]
Right now we don't have any flags enabling/disabling errors or warnings and I don't think we should change this.

Maybe something like `elixir --explain ...`? We could have something like:
```
warning: variable "x" is unused (learn more with elixir --explain unused_var)
  test.ex: 3
```

**Comment by josevalim** [comment]
@michalmuskala I thought about `--explain`, the exact same name, but it led me to those questions:

1. Should we make it extensible? What if Mix wants to add its own explanations?

2. Should we add `explain` to `iex` too? If so, what is the difference between `explain`, `help` and `info`?

To answer 1, I propose the name to be prefixed, hence "elixir:unused_var". I am not sure what the lookup mechanism would be though. Maybe we camelize and always invoke a specific module, such as `Elixir.ErrorInfo`. Or we find an `elixir.app` file and get the module name from there. For example, the `elixir.app` could tell Elixir to use invoke the module `Kernel.ErrorInfo`, so we end-up dispatching to `Kernel.ErrorInfo.unused_var`. The nice thing about this is that we can do dynamic code. For example, "elixir:guards" could get the docs of Kernel module and print the list of guards based on the docs metadata. This means that we can make errors about functions not available in guards much more meaningful. 

To answer 2, I think it would be nice to just re-use the "help" infrastructure by allowing strings. For example, printing this information with the markdown formatting can do wonders. In IEx you would be able to do `h "elixir:unused_var"`. Then I propose to have `-h` as a fully functional flag on `elixir` CLI too (and the siblings `-o`, `-t` and `-b`). I believe this would provide a more unified approach to help/docs.

Coincidentally, it has always annoyed me that `help` is called so, `doc` would be much more fitting. But if we go in this direction, I would say `help` is finally aptly named.

**Comment by cybrox** [comment]
@michalmuskala Wouldn't an error message with a pointer to the helper command add more clutter to the actual information than necessary? I think it makes more sense to _promote_ the existence of a help command outside of the warnings (in guides, docs, mans) and use a unified naming scheme for errors and warnings, so it's easier to look them up. (e.g. as José suggested, `elixir:unused_var`)

```
warning: variable "x" is unused (learn more with elixir --explain unused_var)
warning: variable "x" is unused (elixir:unused_var)
  test.ex: 3
``` 

I've always found Elixir error messages to be a lot more helpful than errors in a lot of other languages already, but I think the ideas tossed around here could have huge impact, especially for beginners encountering common issues that library authors and people contributing to Elixir know about.

> Maybe we camelize and always invoke a specific module, such as Elixir.ErrorInfo.
> [...]
> In IEx you would be able to do h "elixir:unused_var"

👍 👍

**Comment by josevalim** [comment]
A proposal has been sent for this: https://elixirforum.com/t/proposal-introduce-help-catalogs/15718

As mentioned, I don't consider the current warning to be a bug, but if we can improve the experience altogether, it is worth discussing it.
