### ISSUE TITLE
Errors, when clear deps folder for compiled app

### ISSUE THREAD

**Issue by SofaKing18** [elixir-lang/elixir#8058]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 20 [erts-9.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.4 (compiled with OTP 19)
* Operating system: 
Mac OS High SIerra 10.13.4

### Current behavior

➜  phoenix_app git:(master) ✗ mix ecto.migrate
2018-08-06 15:37:57.830 [info][module: Ecto.Migrator] Already up
➜  phoenix_app git:(master) ✗ rm -rf deps
➜  phoenix_app git:(master) ✗ mix ecto.migrate --no-compile --no-deps-check
Unchecked dependencies for environment dev:
* bcrypt_elixir (Hex package)
  the dependency is not available, run "mix deps.get"
* eredis (https://github.com/savonarola/eredis.git)
  the dependency is not available, run "mix deps.get"
* phoenix_bootstrap_form (Hex package)
  the dependency is not available, run "mix deps.get"
* httpotion (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix_pubsub (Hex package)
  the dependency is not available, run "mix deps.get"
* uuid (Hex package)
  the dependency is not available, run "mix deps.get"
* ibrowse (Hex package)
  the dependency is not available, run "mix deps.get"
* phoenix (Hex package)
  the dependency is not available, run "mix deps.get"
* postgrex (Hex package)
  the dependency is not available, run "mix deps.get"
* instream (Hex package)
  the dependency is not available, run "mix deps.get"
....
### Expected behavior

Expected, that there are no errors or checking of deps, because sources already compiled in _build

**Comment by josevalim** [comment]
By default we will always check deps as we want to make sure the build is up to date to the local deps and the listed versions. You can pass `--no-compile` to many commands or even `--no-deps-check` to compile itself if you want to avoid dependency checking.

**Comment by SofaKing18** [comment]
I did pass those flags, as you can see in example, they doesn't work
