### ISSUE TITLE
Make sure our records implementation triggers dsetel optimization

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#8059]
This means that we need to allocate arguments to vars during expansion and start by the higher position first. We should also apply the same logic as found in `erl_expand_records` and convert some updates to matches if most of the data is being updated.

**Comment by michalmuskala** [comment]
Are you sure we need to extract arguments to vars - I'm pretty sure `v3_core` pass does this when converting to core erlang. In core you can't have complex arguments to an operation.

**Comment by josevalim** [comment]
We need to. Imagine this code:

```elixir
record(foo, bar: bar(), baz: baz())
```

If it expands to this:

```elixir
setelem(setelem(foo, 0, bar()), 1, baz())
```

The arguments won't be safe and the optimization won't apply. We need to move those operations out.

**Comment by josevalim** [comment]
Closing in favor of #8062.
