### ISSUE TITLE
Please revert old Erlang syntax

### ISSUE THREAD

**Issue by erlang-developer** [elixir-lang/elixir#8066]
Hello, 

I am new to Elixir because I was Erlang developer before.
When I started writing new programs in Elixir I noticed that its very hard to switch to new atom syntax with colon in the beginning. Now when I think I write atom, I write a variable and it's quite annoying.
Can we revert the Erlang syntax in Elixir in newer Elixir version?
Thank you

**Comment by josevalim** [comment]
Hi @erlang-developer, welcome!

Elixir is its own language, it is not Erlang. Nor it was written to ease the migration of Erlang developers. If you believe this change is worth considering, then please write a proposal to the mailing list, as asked in the issues template, with the pros and cons of your suggestion. Don't forget to consider other languages beyond Erlang. And remember to propose ways the how the community and the millions of lines of code already written should be converted to the new syntax without causing major disruption.

Thanks!
