### ISSUE TITLE
Data Comparison

### ISSUE THREAD

**Issue by realsugar** [elixir-lang/elixir#8068]
Hello! I faced very strange Date comparison behaviour recently:

### Current behaviour
```
iex> ~D[2018-06-09] > ~D[2018-08-10]
false
iex> ~D[2018-06-09] > ~D[2018-08-08]
true 
```
### Expected behaviour

```
iex> ~D[2018-06-09] > ~D[2018-08-10]
false
iex> ~D[2018-06-09] > ~D[2018-08-08]
false
```

[Screenshot](http://take.ms/Hh1BI)

This does not make sense in real life, 'cause June 9th is earlier than Aug 8th ;)
Am I doing something wrong?

### Environment

* Elixir 1.6.1
* Erlang/OTP: 20 [erts-9.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10]
* Operating system: OS X 10.13.6

**Comment by josevalim** [comment]
Yes, `<` and `>` are structural comparisons. You need to use `Date.compare/2` instead for semantic comparisons.
