### ISSUE TITLE
Add ExUnit.after_suite

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#8082]
See https://github.com/elixir-ecto/ecto/pull/2620 for discussion.

**Comment by devonestes** [comment]
Just wanted to ask a few questions to clarify some intended behavior before I take a swing at this.

1) Would it make sense for the signature for this to be `ExUnit.after_suite/1`, accepting a single function to be executed after all tests have finished execution for a given run of `mix test`?

2) This would most likely be used in a `test_helper.exs` file before a call to `ExUnit.start/1`, right? Or would this be defined in a test module?

3) Would it be possible to define multiple `after_suite/1` callbacks? If so, would there be any guarantees in the order in which they are run? If not, should we raise an error if someone tries to define `after_suite/1` multiple times, or emit a warning?

**Comment by josevalim** [comment]
> Would it make sense for the signature for this to be ExUnit.after_suite/1, accepting a single function to be executed after all tests have finished execution for a given run of mix test?

Yes.

> This would most likely be used in a test_helper.exs file before a call to ExUnit.start/1, right?

Yes.

> Would it be possible to define multiple after_suite/1 callbacks?

Yes, they should run in the reverse order they are added.

**Comment by ggcampinho** [comment]
I don't know if I understand the advantage of this over a `try/after` block

**Comment by josevalim** [comment]
@ggcampinho you can't use try/after. The suite does not run inside test_helper.exs but after test_helper.exs finishes loading. Usually inside `mix test`, which the user has no control.

**Comment by fertapric** [comment]
I would like to include a few questions:

* Does the `after_suite` callback need to return any special value to notify everything went right (for example, `:ok`)? or should we rely on the function to raise an exception? I would vote for `:ok`.

* If the `after_suite` raises an exception or returns an error, should the output still contain the tests statistics? Should the exit status of the `mix test` process not be 0? I think the exit status should not be 0. Regarding the statistics, I'm not sure.

**Comment by josevalim** [comment]
I think `after_suite` should run like any code in test_helper. So if it fails, it will cause the whole thing to fail too.

**Comment by josevalim** [comment]
That said, we don't need to care about the return result for now.
