### ISSUE TITLE
@spec module attribute no longer accessible in 1.7

### ISSUE THREAD

**Issue by whitepaperclip** [elixir-lang/elixir#8085]
### Current behavior

```elixir
defmodule Foo do
  @spec x() :: integer()
  def x(), do: 5
  def spec(), do: @spec
end

iex> Foo.spec() #=> nil
```

### Expected behavior

```elixir
iex> Foo.spec() #=>
[
  {:spec, {:::, [line: 2], [{:x, [line: 2], nil}, {:integer, [line: 2], []}]},
   {Foo, {2, 1}}}
]
```

**Comment by paulperegud** [comment]
I was accessing @spec via `Module.get_attribute(__MODULE__, :spec)` in `defmacro __before_compile__(_)`. Same observations.

**Comment by koudelka** [comment]
also would love a fix for this, my precious [behaves_like](https://github.com/koudelka/behaves_like/blob/5fd6731c5b1da23d04d485335ff35e587d8743d1/lib/behaves_like.ex) is broken 😭

**Comment by wende** [comment]
Same here - foreign function interface to Elixir type-checking in [Elchemy](https://github.com/wende/elchemy) relies on it
