### ISSUE TITLE
Update mix formatter help output

### ISSUE THREAD

**Issue by DanielDent** [elixir-lang/elixir#8088]
Apologies if this has already been discussed elsewhere, I did a bit of searching and nothing came up.

The current default of `mix format` seems unsafe. After using the code formatter, the file may have quite a number of changes. It is a perhaps unrealistic expectation that the user will always be able to spot unintended changes to the meaning of code.

I don't know the history of how `--check-equivalent` came to be, my suspicion is that it is for performance related reasons. I would propose that users should explicitly opt-in to potentially dangerous optimizations rather than the other way around.

**Comment by josevalim** [comment]
> The current default of mix format seems unsafe. After using the code formatter, the file may have quite a number of changes. It is a perhaps unrealistic expectation that the user will always be able to spot unintended changes to the meaning of code.

The formatter should never, ever, change the meaning of the code. This is guaranteed by the formatter. The `--check-equivalent` flag was originally used to find bugs in the formatter but now that the formatter is stable and solid, those cases no longer happen.

**Comment by DanielDent** [comment]
That's great to hear & thank you for the prompt response.  Are you interested in a pull request to update documentation and/or deprecate that flag? 

If so, I have two questions:

1. Is it still true that the formatted output will continue to evolve?
2. Under what circumstances would a person still want to use the `--check-equivalent` flag? If the AST is always guaranteed to be equivalent, then maybe it's not actually a documentation update that's needed, but instead that flag should be deprecated because it doesn't do anything anymore?

The output of what `mix help format` says in 1.7.1 is below:
>   • --check-formatted - checks that the file is already formatted. This is
>     useful in pre-commit hooks and CI scripts if you want to reject
>     contributions with unformatted code. However keep in mind that the
>     formatted output may differ between Elixir versions as improvements and
>     fixes are applied to the formatter.
>   • --check-equivalent - checks if the files after formatting have the same
>     AST as before formatting. If the ASTs are not equivalent, it is a bug in
>     the code formatter. This option is recommended if you are automatically
>     formatting files.
>

**Comment by josevalim** [comment]
In general I think the number of changes in the formatter will reduce with time. For example, there is nothing schedule for now.

I think the flag could still be useful under some situations, such as testing the formatter itself, which we do in Elixir. So my recommendation would be to change it something like "This option is useful if you suspect you have ran into a formatter bug and you would like confirmation".

What do you think?

**Comment by josevalim** [comment]
Closing in favor of #8222.
