### ISSUE TITLE
Allow Inspect protocol to be derivable with the only/except options

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#8098]
Sometimes you may want to hide certain fields from structs, so they don't show up in logs, inspects and similar. Especially fields containing private user information.

This is doable today by implementing inspect by hand, but it may be much simpler if we simply make the Inspect protocol derivable with the `:only` and `:except` option. For example:

```elixir
defmodule User do
  @derive {Inspect, only: [:id, :name]}
  defstruct [:name, :email, :id, :address]
end

inspect(%User{id: 1, name: "jane", age: 30, address: "earth"})
#=> #User<id: 1, name: "jane", ...>
```

**Comment by OvermindDL1** [comment]
As long as there is some option we can pass to `inspect/2` to display *everything*, not just via the protocol, that would be great.

**Comment by josevalim** [comment]
You can always pass `structs: false`. That's valid today. Note this proposal is nothing new, it is only a shortcut for a mechanism that already exists today.

**Comment by fertapric** [comment]
Should it be `@derive [{Inspect, only: [:id, :name]}]`?

**Comment by josevalim** [comment]
@fertapric both formats are supported.

**Comment by fertapric** [comment]
Oh! I didn't know that. The documentation always talks about a "list" https://hexdocs.pm/elixir/Kernel.html#defstruct/1-deriving

**Comment by OvermindDL1** [comment]
I'd imagine `@derive Inspect: [only: [:id, :name]]` would work too.  ^.^

**Comment by josevalim** [comment]
@OvermindDL1 it does not. `:Inspect` is not the same as `Inspect`.

**Comment by wojtekmach** [comment]
Just wanted to say this is a very welcome change, imagine an Ecto schema with a lot of of preloaded associations - the inspect output can be huge. With this change it will be really easy to make it more compact.

**Comment by fertapric** [comment]
I'm working on this. Almost done, I'm polishing the tests and looking where to document this new functionality :)

**Comment by josevalim** [comment]
@fertapric let's document it in the `Inspect` protocol docs and make sure `Kernel.inspect/2` tells people how to provide their own inspect.

**Comment by ericmj** [comment]
I would suggest avoiding `#` in the output in `#User<id: 1, name: "jane", ...>` and instead use the normal struct syntax `%User{id: 1, name: "jane", ...}`.

I understand that it may be desirable to show that the output has been redacted but `#` causes a lot pain when copying from the inspect output to somewhere it will be evaluated because all `#` instances such as `#DateTime<2018-08-17 10:34:34.413548Z>` will have to be manually replaced.

**Comment by fertapric** [comment]
@ericmj that would go against the documentation of [`Kernel.inspect/2`](https://hexdocs.pm/elixir/Kernel.html#inspect/2):

> Note that the `Inspect` protocol does not necessarily return a valid representation of an Elixir term. In such cases, the inspected result must start with `#`.

In addition, the syntax `%User{id: 1, name: "jane", ...}` would also require manual editing, since you must remove the `...` at the end :)

**Comment by ericmj** [comment]
> that would go against the documentation of Kernel.inspect/2:

I don't believe it is against the documentation because a struct with some fields removed is still a valid struct, for example this is valid: `%User{}`.

> In addition, the syntax %User{id: 1, name: "jane", ...} would also require manual editing, since you must remove the ... at the end :)

Sorry, I didn't mean `...` as part of the actual output, it was only to show there may be more fields.

**Comment by fertapric** [comment]
> Sorry, I didn't mean `...` as part of the actual output, it was only to show there may be more fields.

👌All my comments were based on having `...` as part of the actual output.

In fact, that was [my initial implementation](https://github.com/elixir-lang/elixir/pull/8104#discussion_r210835094). However:

* I think denoting that the struct was redacted is important
* there is an edge case with `@enforce_keys` in which the copy won't work

**Comment by josevalim** [comment]
@ericmj we will always add the `...` by default to denote we don't have all data, which makes the representation invalid, IMO. And I do believe adding `...` is important, because `%User{}` and `%User{email: "foo"}` are not the same. I believe we should use the regular syntax only when we have a guarantee that the printed representation is the same as the one we have in memory.

**Comment by ericmj** [comment]
What about printing it as `struct(User, email: "foo")`? I think it is a good compromise because you can still eval it and it is not a literal so it is clear it is not an exact memory representation.

**Comment by josevalim** [comment]
@ericmj Do we have precedent for doing this? The example above is more verbose and it won't play well with doctests too.

Imagine that the e-mail is hidden:

```iex
# imagine email is hiddren
iex> %User{id: 1, email: "foo@bar"}
struct(User, id: 1)
```

The example above will compare `%User{id: 1, email: "foo@bar"} == struct(User, id: 1)`. Which won't be true. By using `#User<...>`, it is clear to doctests that we are using the inspected result and it will work.

I want to emphasize that you are trying to stick to a guarantee that `inspect` **does not provide**.

**Comment by ericmj** [comment]
> The example above is more verbose and it won't play well with doctests too.

But a doctest with `#` is not testing anything so I am not sure what point is being made? You should be able to write a doctest like this also:

```elixir
iex> %User{id: 1, email: "foo@bar"}
#struct(User, id: 1)
```

> I want to emphasize that you are trying to stick to a guarantee that inspect does not provide.

I don't want to make an existing problem with inspect even worse.

**Comment by ericmj** [comment]
> >But a doctest with # is not testing anything so I am not sure what point is being made?

> A doctest with #...< compares inspected representations directly. It does work.

That is indeed a good point :). Maybe the check for `#...<` can be generalized to also support inspect comparisons of expressions.

> It is only a problem if you are trying to use it in ways it is not meant to. It is like refusing to improve your hammer because it would make it worse at cooking soup. :)

It may not be what Inspect is intended for but I don't believe it is uncommon for it to be used in this way which makes # an inconvenience. But we won't fix it in this issue so I will drop this for now.

**Comment by josevalim** [comment]
> That is indeed a good point :). Maybe the check for #...< can be generalized to also support inspect comparisons of expressions.

The problem is that we evaluate expressions today and changing that could possibly be breaking. It is generally not expected from inspect to return an expression (as in function calls in the AST).
