### ISSUE TITLE
Define criteria for choice between `__MODULE__` and module name

### ISSUE THREAD

**Issue by basdirks** [elixir-lang/elixir#8105]
When defining a `@type t :: %_{}`, we vary between `__MODULE__` and the actual module name.

In general we use the form:

```elixir
@type t :: %__MODULE__{}
```

But in the following modules we use the actual module name:

- lib/elixir/lib/range.ex
- lib/elixir/lib/calendar/time.ex
- lib/elixir/lib/calendar/date.ex
- lib/elixir/lib/calendar/naive_datetime.ex
- lib/elixir/lib/kernel.ex

Do we want to be consistent, or do we think that the current mix of approaches is a non-issue?

For discussion, see #8103.

**Comment by whatyouhide** [comment]
Personally, I would go with `__MODULE__`. While sometimes the module name is shorter, `__MODULE__` has the guarantee of being easy to recognize and it always means the same thing, "the current module", regardless of the name.

**Comment by basdirks** [comment]
I agree. Being consistent here does not sacrifice clarity.

**Comment by fertapric** [comment]
I would also go with `__MODULE__`.

Besides, using the module name also opens the debate of using the fully qualified name: 

```elixir
@type t :: %MyApp.Context.MyModule{ ... }
``` 

or the module name + alias:

```elixir
alias MyApp.Context.MyModule
# or alias __MODULE__ ?
@type t :: %MyModule{ ... }
```

**Comment by lexmag** [comment]
I second what @whatyouhide said, using `__MODULE__ ` also makes renaming easier.

**Comment by josevalim** [comment]
Alright! @basdirks can you please send a PR that changes them all once? Sorry for the back and forth.

**Comment by basdirks** [comment]
Will do. No problem 👍

**Comment by basdirks** [comment]
#8113 contains the proposed changes.

**Comment by fertapric** [comment]
Looking at #8113, should `__MODULE__` be also used when creating structs? 

For example, in the `Date` module there is:

```elixir
{:ok, %Date{year: year, month: month, day: day, calendar: calendar}}
``` 

and that could be written as: 

```elixir
{:ok, %__MODULE__{year: year, month: month, day: day, calendar: calendar}}
```

for the same reasons mentioned above:

*  guarantee of being easy to recognize and it always means the same thing, "the current module", regardless of the name
* makes renaming easier.

However, in this case I prefer the `%Date{}` syntax 🤷‍♂️ 

Other option is to accept that we do not be "consistent" in this case, and both `__MODULE__` and the module name can be used interchangeably.

**Comment by bitwalker** [comment]
I'd prefer to see us always use `__MODULE__`, it benefits from clarity of purpose, and leaves no debate about when it should or shouldn't be used, and most importantly, always using it makes things consistent, which is easier for people submitting PRs, as well as for the core team when reviewing them.
