### ISSUE TITLE
Include test times when sending `:module_finished` event to ExUnit formatters

### ISSUE THREAD

**Issue by devonestes** [elixir-lang/elixir#8112]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.7.1 (compiled with Erlang/OTP 19)
* Operating system: MacOS 10.13.6

### Current behavior

When writing a custom formatter, the `%ExUnit.TestModule{}` struct that is sent as part of the `:module_finished` cast includes all of the tests in that module, but it does not include the correct run times of those tests. For example, in that message I get:

```elixir
%ExUnit.TestModule{
  name: TestmetricsElixirClientTest.BasicTest,
  state: nil,
  tests: [
    %ExUnit.Test{
      case: TestmetricsElixirClientTest.BasicTest,
      logs: "",
      module: TestmetricsElixirClientTest.BasicTest,
      name: :"test false",
      state: nil,
      tags: %{
        async: true,
        describe: nil,
        describe_line: nil,
        file: "/Users/devoncestes/sandbox/testmetrics/testmetrics_elixir_client/test/testmetrics_elixir_client_test.exs",
        line: 13,
        registered: %{},
        test_type: :test
      },
      time: 0
    },
    %ExUnit.Test{
      case: TestmetricsElixirClientTest.BasicTest,
      logs: "",
      module: TestmetricsElixirClientTest.BasicTest,
      name: :"test true",
      state: nil,
      tags: %{
        async: true,
        describe: nil,
        describe_line: nil,
        file: "/Users/devoncestes/sandbox/testmetrics/testmetrics_elixir_client/test/testmetrics_elixir_client_test.exs",
        line: 9,
        registered: %{},
        test_type: :test
      },
      time: 0
    }
  ]
}
```

### Expected behavior

I would expect that the `:time` for each test in the test module would be updated to reflect how long the test actually took to run. Essentially, I would expect that the `:tests` key would be updated to include the new structs that are sent as part of the `:test_finished` message, so they include the run times of each test and an updated `:state` of each test, including failure information for failed tests.

**Comment by josevalim** [comment]
@devonestes good catch. Can you please investigate how hard would be to fix this? I think we should be able to return the test results before calling module finished. Thanks!
