### ISSUE TITLE
Date.add/2 seems broken for when the year rolls into a negative leap year

### ISSUE THREAD

**Issue by paulanthonywilson** [elixir-lang/elixir#8128]
### Precheck

* For bugs, do a quick search and make sure the bug has not yet been reported

Can't find anything.

### Environment

```
Hex:    0.18.1
Elixir: 1.7.3
OTP:    21.0.5
```
Mac OS High Sierra 10.13.6

### Current behaviour

```
iex(1)> Date.add(~D[-0005-12-31], 1)
~D[-0005-12-32]
```

Note that this is only an issue with dates with negative years.

### Expected behaviour

```
iex(1)> Date.add(~D[-0005-12-31], 1)
~D[-0005-12-32]
```

**Updated 2018-08-26** : Originally found when preparing a Property Testing demonstration; just now narrowed the issue down to being about negative leap years.

**Comment by paulanthonywilson** [comment]
Ok, so I've narrowed it down to a problem with the undocumented `Calendar.ISO.date_from_iso_days/1`:

(excuse the pipe)
```
iex(1)> Calendar.ISO.date_to_iso_days(-4, 1, 1) |> Calendar.ISO.date_from_iso_days()  
{-5, 12, 32}
```
Specifically the issue seems to be in the private `days_to_year/x` functions, but I am really struggling to understand the maths.

**Comment by josevalim** [comment]
Closing in favor of the PR, thanks!
