### ISSUE TITLE
How about add a simple mode for browse doc in IEx?

### ISSUE THREAD

**Issue by chenge** [elixir-lang/elixir#8130]
I Hope to see the top brief message without scrolling, thanks.

**Comment by eksperimental** [comment]
This is a really annoying limitation. It probably comes from the erl repl as it heavily relies on it

**Comment by josevalim** [comment]
I agree this would be awesome to have but it is a feature that would have to be implemented in Erlang first. Therefore I suggest for somebody to investigate and send a PR there and then I will be glad to follow up on the Elixir side of things. Thanks!
