### ISSUE TITLE
Macro.underscore behavior consistency

### ISSUE THREAD

**Issue by kevmojay** [elixir-lang/elixir#8141]
### Current behavior

```
Macro.underscore("vIN")
"v_in"
```

### Expected behavior

```
Macro.underscore("vIN")
"v_i_n"
```
-----------------------------------------------------------------------------------------------
I think this is more of a point of discussion. I am curious why the above is considered the valid behavior when the following snippet behaves in a more predictable way.

```
Macro.underscore("vINs")
"v_i_ns"
```

To me this is inconsistent behavior but I can understand the use cases the behavior is meant to solve such as 
```
Macro.underscore("OrderDBManager")
"order_db_manager"
```

But I also feel that Macro.underscore and Macro.camelize should be as close to reverse operations as possible
```
"v_i_n" |> Macro.camelize |> Macro.underscore
"vin"
```

**Comment by josevalim** [comment]
As you noted, this is by design and documented that they are not fully reversible. Changing this now could be considered a breaking change and break cases like you mentioned. For example, I would expect HTTPMethod to be underscored as `http_method` and not `h_t_t_p_method`. Thanks!
