### ISSUE TITLE
Invalid type annotations allowed in Elixir

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#8143]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.0-dev (9ab98af68) (compiled with Erlang/OTP 21)
```
* Operating system: Mac OS X 10.13.6

### Current behavior

While working on `{undefined_type, {TypeName, Arity}}` and `{unused_type, {TypeName, Arity}}` of https://github.com/elixir-lang/elixir/issues/5800, I've found that some type annotations are parsed as `:user_type`. This is an example:

https://github.com/elixir-lang/elixir/blob/de42c4cf20a3ac907b5bff81468b509b07d7a907/lib/elixir/lib/process.ex#L28

The resulting AST is:

```elixir
{:type,
 {:type,
  {:::, [line: 7],
   [
     {:dest, [line: 7], nil},
     {:::, [line: 7],
      [
        {:|, [line: 7],
         [
           {:pid, [line: 7], nil},
           {:|, [line: 7],
            [{:port, [line: 7], nil}, {:registered_name, [line: 7], nil}]}
         ]},
        {:|, [line: 7],
         [
           {:atom, [line: 7], nil},
           {{:::, [line: 7],
             [{:registered_name, [line: 7], nil}, {:atom, [line: 7], nil}]},
            {:node, [line: 7], nil}}
         ]}
      ]}
   ]}, {Foo, {7, 1}}}}
```

and the translation passed to build the forms:

```elixir
 {type,
     {dest,0},
     7,
     {dest,
         {ann_type,7,
             [{type,7,union,
                  [{type,7,pid,[]},
                   {type,7,port,[]},
                   {user_type,7,registered_name,[]}]},
              {type,7,union,
                  [{type,7,atom,[]},
                   {type,0,tuple,
                       [{ann_type,7,
                            [{var,7,registered_name},{type,7,atom,[]}]},
                        {type,7,node,[]}]}]}]},
         []},
     true}
```

As seen above, the type annotation `registered_name` is translated as `{user_type,7,registered_name,[]}`.

It seems to be related to operator precedence, because this typespec is parsed properly:

```elixir
@type dest :: pid | port | (registered_name :: atom) | {registered_name :: atom, node}
```

```elixir
{type,{dest,0},
       7,
       {dest,{type,7,union,
                   [{type,7,pid,[]},
                    {type,7,port,[]},
                    {ann_type,7,[{var,7,registered_name},{type,7,atom,[]}]},
                    {type,0,tuple,
                          [{ann_type,7,
                                     [{var,7,registered_name},
                                      {type,7,atom,[]}]},
                           {type,7,node,[]}]}]},
             []},
       true}
```

I tried doing the same with Erlang, but it raises `test.erl:3: syntax error before: '::'`:

```erlang
-type dest() :: pid() | port() | RegisteredName::atom() | {RegisteredName::atom(), node()}.
```

but works if parens are added:

```erlang
-type dest() :: pid() | port() | (RegisteredName::atom()) | {RegisteredName::atom(), node()}.
```

### Expected behavior

I would mirror Erlang and raise a `SyntaxError` in such cases.

If I may, I would like to work on this issue if the expected behavior is desired 🙂

**Comment by fertapric** [comment]
Btw, this issue made me wonder:

* Why an `undefined "registered_name" type` is not emitted if that's marked as an `user_type` and that type is not defined?
* Why this is not raising any kind of error like it did for the Erlang example?

**Comment by josevalim** [comment]
It looks like a bug. The precedence is making Elixir believe somehow that two types are being defined. I agree we should raise like Erlang does.

**Comment by fertapric** [comment]
I've been investigating this issue and it's a lot harder than I thought 😅 

I first studied in which part of the Erlang codebase the syntax error was raised. I found out that they are produced by the Erlang's parser, baked into the Erlang's yecc grammar ([along these lines](https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_parse.yrl#L102-L139)). 

I thought that I could do the same using the Elixir's parser. One thing I kept in mind was that any modification regarding types should also consider binaries and bitstrings syntax `<<256 :: size(16)>>`, because the type operator `::` can also be used there. 

However, Elixir's parser is a bit more generic than Erlang's parser. For example, Erlang's parser extracts `ann_type` directly. Besides, to raise a `SyntaxError` for these cases required to fight against the operator precedence of the grammar. Not easy.

After many failed attempts modifying the grammar, I decided to look for alternative solutions. I saw that this syntax `<<256 :: size(16) :: foo>>` does not produce a `SyntaxError`, it produces a `CompileError` when [validating the spec](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_bitstring.erl#L209). So, I started thinking that it might be an option to detect ambiguous types also during the expansion phase. What do you think?

**Comment by josevalim** [comment]
Oh, we should definitely **not** change the grammar. Elixir's grammar is meant to not care about the semantics at all. So the correct is indeed to raise it later on, when validating the spec, which is when we have the semantic meaning of it.

**Comment by fertapric** [comment]
That makes much more sense! Thanks @josevalim
