### ISSUE TITLE
Better support for custom operators

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8170]
### Precheck

Elixir 1.7

### Current behavior

Elixir only supports the definition of a static set of operators (see [Operators](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Operators.md)).

### Enhancement

Provide better support for custom DSLs by supporting the definition of custom operators.

### Details

Let me explain the idea:

1. Elixir would distinguish two sets of operators
   - **Universal operators**: these are those operators we know from school, like +, -, /, *, >, <, =, and the like;

   - **Custom operators**: these are all other operators, comprising any combination of single character symbols on the keyboard, except for accents, comments, quotes, parentesis, brackets, commas, semicolons, and others that are related to program structure. For example, the programmer could (re)define these custom operators: \~>, <\~, <*>, *>, <*, =$=, and so on.

2. Elixir would forbid the redefinition of universal operators
   - The separation of universal and custom operators promotes readable code.

      For example, a programmer who wanted to define a custom operator for string repetition, would then (re)define the <\*> operator instead of \* which everyone knows is for numbers multiplication. So instead of typing "A" \* 3, one would type "A" <\*> 3 to mean "AAA" (not a big deal to type, and very clear);

     But, if the programmer opted to define the custom operator **&$+$&** for string repetition, which is perhaps as much understandable as a call to function **pqrst(..)**, then someone seeing that operator should perhaps throw out the affected code, or kick the programmer (preferably very hard).

3. Elixir would let define the precedences of custom operators **relative** to other universal or custom operators.

   The word "relative" is important here: instead of associating numbers to precedences, like in Haskell, Elixir would allow to (re)define the position of custom operators in the operator precedence ladder.

   A programmer could then define the precedence of a custom operator in the following terms:

      - **same of OPER**: the same precedence of OPER;

      - **above OPER**: precedence higher than OPER, and the same as any operator with precedence higher than OPER;

      - **below OPER**: precedence lower than OPER, and the same as any operator with precedence lower than OPER;

      - **between OPER1 [exclusive] and OPER2 [exclusive]**: precedence higher than OPER1 [exclusive] and lower than OPER2 [exclusive] (given that OPER1 as precedence lower than OPER2).

   Inconsistencies in precedence specifications would be easily detected as cycles in a precedence graph.

   This way of defining precedences would provide for ASTs whose structure better fits the meaning of custom operators, and their precedences, in a DSL.

4. A possible syntax could be something close to this:

```
def a <*> b, precedence: {:of, <>} do
end

def a <*> b, precedence: {:below, <>} do
end

def a <*> b, precedence: {:above, <>} do
end

def a <*> b, precedence: {:between_exclusive_inclusive, <+>, <->} do
end
```

5. Elixir would offer a function, say `Operator.precedences/0` that would print the precedence of all operators relative to that of others in a project.

   This would be useful to clarify the current operator precedences in case of doubt when looking into an expression with custom operators. Also, such doubts could be easily resolved by seeing the result of `quote do: expression`.

### Conclusion

To my best knowledge, relative operator precedences has not been implemented in any language, so this could be a distinct feature of Elixir.

All this is would provide greater support for implementing clean and powerful DSLs, while avoiding the risk of messing up with the meaning of the universal operators that come with Elixir.  

Hope you liked this idea, and consider it for inclusion in Elixir somewhere in the near future.

**Comment by fertapric** [comment]
> Elixir would forbid the redefinition of universal operators

I think this will be a breaking change, and it will reduce the flexibility Elixir provides. 

For example, some libraries could be relying on giving those operators a different meaning:

```elixir
defmodule PoorMansMoney do
  defstruct [:amount, :currency_code]

  def new(amount, currency_code \\ "EUR") do
    %PoorMansMoney{amount: amount, currency_code: currency_code}
  end

  def x + y do
    case {x, y} do
      {%__MODULE__{currency_code: currency_code}, %__MODULE__{currency_code: currency_code}} ->
        amount = Kernel.+(x.amount, y.amount)
        new(amount, currency_code)

      _ ->
        Kernel.+(x, y)
    end
  end
end
```

and then:

```elixir
iex(2)> import PoorMansMoney
PoorMansMoney
iex(3)> import Kernel, except: [+: 2]
Kernel
iex(4)> PoorMansMoney.new(3) + PoorMansMoney.new(5)
%PoorMansMoney{amount: 8, currency_code: "EUR"}
iex(5)> 3 + 2
5
```

That's not something I would personally do, but I hope it illustrates my point 🙂

**Comment by mguimas** [comment]
Yep, this would break those libraries, which would have to define, for example, operator `<+>` instead. 

I don't know if there are many libraries redefining operators called above as universal, notwithstanding it doesn't seem to much effort to replace those redefinitions with the operator enclosed with `<` and `>` (for example, to replace `+` for `<+>`).

The benefit is greater readability because a `+` is always a `+` for numbers.

**Comment by mguimas** [comment]
Point 2 above could be turned `off` or `on` at project level (and it would be `on` by default).

**Comment by fertapric** [comment]
I'm not sure if enforcing such rules would be desirable, or even feasible. For example, I could write the following code:

```elixir
defmodule IAmEvil do

  defmacro __using__(_) do
    quote do
      import unquote(__MODULE__)
    end
  end

  defmacro my_macro({:+, meta, [x, y]}) do
    {:-, meta, [x, y]}
  end

  defmacro my_macro(ast), do: ast
end
```

```elixir
iex(1)> use IAmEvil
Hello
iex(2)> my_macro 3 + 2
1
```

**Comment by mguimas** [comment]
Did not undsertand your point in the above example: redefining `+` is already possible, the feature proposal would only forbid (or not) doing it.

(Where there comes that "Hello" ?! I get `IAmEvil`)

**Comment by fertapric** [comment]
> Did not understand your point in the above example: redefining + is already possible, the feature proposal would only forbid (or not) doing it.

My point was that forbidding the redefinition of universal operators would require to inspect the AST and validate that those operators are used with the valid arguments.

> (Where there comes that "Hello" ?! I get IAmEvil)

Sorry for that. My original test was with a `Hello` module name, but then I thought it would be fun to use `IAmEvil` (since it changes the `+` operators to `-`) 😬

**Comment by fertapric** [comment]
On the other hand, do you have real-life examples of its usage? 

Overriding operator precedences seems like a lot of effort, and I'm quite not see the benefits of doing it, nor if developers will use it.  At the end, it will be an additional thing to implement and maintain: "Adding is easy, removing is very hard". 

Having real-life examples might help understand the capabilities of this proposal 🙂

**Comment by mguimas** [comment]
> My point was that forbidding the redefinition of universal operators would require to inspect the AST and validate that those operators are used with the valid arguments.

Can you clarify this? I cannot see why ...

**Comment by mguimas** [comment]
> Having real-life examples might help understand the capabilities of this proposal 🙂

1. The current set of customizable operators is fixed, and in some DSLs some other operators can make more sense (e.g., operators `<$>` and `<*>` are very used in Haskell-based DSLs, and unavailable in Elixir).

**Comment by fertapric** [comment]
> >My point was that forbidding the redefinition of universal operators would require to inspect the AST and validate that those operators are used with the valid arguments.
>
> Can you clarify this? I cannot see why ...

In fact, forget what I said. Inspecting the AST will only check that the `+` operator is properly used in that expression, but it could not control the usage of the `+` operator in macros.  

For example, you can build a macro that changes completely the semantics of the `+` operator, leaving no trace in the AST (like the example I gave). 

To further clarify it, given the example above, how would you forbid the redefinition of the `+` operator if the resulting AST is `{:-, meta, [x, y]}`, and there is not redefinition of the `+/2` function?

**Comment by mguimas** [comment]
That is not redefining the `+` operator.

That is defining a macro that takes the AST `{:+, meta, [x, y]}` and returns that AST `{:-, meta, [x, y]}`, and this can never be forbidden.

**Comment by mguimas** [comment]
> Having real-life examples might help understand the capabilities of this proposal 🙂

1. The current set of customizable operators is fixed, and in some DSLs some other operators can make more sense (e.g., operators `<$>` and `<*>` are very used in Haskell-based DSLs, and unavailable in Elixir).

2. Precedence redefinition is useful to get ASTs whose structure better match that of the meaning of the operators in a DSL. For example, in my DSL, I would like the result of

```
quote do
a ~> p when g <- e
end
```

instead of

```
{:<-, [],
 [
   {:when, [],
     [
       {:~>, [], [{:a, [], Elixir}, {:p, [], Elixir}]},
       {:g, [], Elixir}
     ]},
   {:e, [], Elixir}
 ]}
```

it could be

```
{:~>, [], 
  [
    {:a, [], Elixir}, 
    {:<-, [], 
       [
         {:when, [], [{:p, [], Elixir}, {:g, [], Elixir}]},
         {:e, [], Elixir}
       ]}
  ]}
```

which exactly matches the meaning of `~>` in the DSL, and eases understanding of the DSL's abstract syntax tree. For this I need to set the precedence of `~>` relative to the precedence of `<-`.

**Comment by josevalim** [comment]
Hi @mguimas, as the issue template suggests, can you please move feature discussions proposal either to the elixir-core mailing list or the Elixir Forum? Only a small subset of the community is active in the issues tracker, so moving the feature proposals elsewhere will bring more visibility and more discussion.

You should probably include an analyses of the cons of custom operators too. You can find criticisms of them in languages like Scala and Haskell.

Also keep in mind though that this has been proposed in the past and refused. Our goal was always to have a small subset of operators available and add more operators on a case by case basis. So please also provide use cases on why your proposal is important.

Last time we touched this topic we have agreed to add new math-like operators to the language. But once again, we were rather considering certain cases instead of having a generic operator mechanism in the language.

Thanks!

**Comment by mguimas** [comment]
Hi @josevalim ,

can you please give the links for the pages where this topic has been discussed before in the community?

It would help understand what as been discussed in the past regarding custom operators, what was refused, why, and so on, to avoid me repating it again. Has this is an important topic, probably you have those links or pages referenced somewhere in your notes, so that I can proceed from there.

Thanks.

**Comment by josevalim** [comment]
Here are the searches I would explore on the mailing list:

* Custom operators: https://groups.google.com/forum/#!searchin/elixir-lang-core/custom$20operators%7Csort:date
* Additional operators: https://groups.google.com/forum/#!searchin/elixir-lang-core/additional$20operators%7Csort:date
