### ISSUE TITLE
Error loading module 'Elixir' when executing expression "Elixir.m" in IEx

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8173]
### Environment

macOS 10.13.6 (High Sierra)
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]
Elixir (1.7.3)

### Current behavior

```
$ iex
Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Elixir.m

15:34:25.279 [error] beam/beam_load.c(1428): Error loading module 'Elixir':
  module name in object code is elixir



15:34:25.289 [error] Loading of /usr/local/Cellar/elixir/1.7.3/bin/../lib/elixir/ebin/Elixir.beam failed: :badfile


15:34:25.289 [error] beam/beam_load.c(1428): Error loading module 'Elixir':
  module name in object code is elixir



15:34:25.289 [error] Loading of /usr/local/Cellar/elixir/1.7.3/bin/../lib/elixir/ebin/Elixir.beam failed: :badfile

** (UndefinedFunctionError) function Elixir.m/0 is undefined (module Elixir is not available)
    Elixir.m()
iex(1)> X.m
** (UndefinedFunctionError) function X.m/0 is undefined (module X is not available)
    X.m()
iex(1)>
```

### Expected behavior

All "[error]" messages above should be resolved.

**Comment by mguimas** [comment]
The above problem does not happen in this environment:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch

$ uname -a
Linux dev 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 GNU/Linux

$ iex
Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Elixir.m
** (UndefinedFunctionError) function Elixir.m/0 is undefined (module Elixir is not available)
    Elixir.m()
iex(1)>
```

**Comment by josevalim** [comment]
The reason why this happens is because file systems are case insensitive. So while we do not have a module named `Elixir`, we do have a module named `elixir`, and attempting to load it will cause bad module name errors. This is the same as doing `:IO.m`. The big question here is why does the error messages appear twice - but I don't believe we should/would get fully rid of them.

**Comment by josevalim** [comment]
That's interesting. So even in case sensitive file system it seems the Erlang VM attempts to load the `elixir.beam` file. In any case, as I said, we can't fix the output altogether, but we can probably make it happen only once.

**Comment by josevalim** [comment]
@mguimas Btw, just now I saw that your original report is on Mac OS X and I would like to add that the Mac OS X file system is case **insensitive**. That explains why you see it on Mac OS X and not on Debian.

**Comment by mguimas** [comment]
@josevalim I am on APFS, which can be configured in both sensitive ways. According to the command `diskutil info /` and the accepted answer for [How to check if my HD is case sensitive or not?](https://apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not) I get:

```
   File System Personality:  APFS
   Type (Bundle):            apfs
   Name (User Visible):      APFS
```
so I believe I have it configured as **insensitive**.

Perhaps I was trapped by `ls` which in my system is having this strange output:

```
$ echo test >File.txt
$ ls File.txt
File.txt
$ ls file.txt
file.txt
$ ls Fi*.txt
File.txt
$ ls fi*.txt
ls: fi*.txt: No such file or directory
```
which does not seem sensitive according to the last command ...

**Comment by josevalim** [comment]
Yes, the bash autocompletion does not seem to be case insensitive, probably because they first get all files in a directory and then filter it at the software level and not at the syscall level? The system call seems to be case insensitive though. :)

**Comment by josevalim** [comment]
I have investigated this issue and we can't avoid the double warning because the code is being evaluated. So the first warning comes when compiling and we are checking for deprecations. The second comes from when the code is executed. In an actual code, the warning would appear only when executed. I think we should improve the warning in Erlang though, so we should start a discussion there too. Thanks!
