### ISSUE TITLE
Relax nimble_parsec version in makeup and makeup_elixir

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#8178]
According to `mix hex.outdated nimble_parsec` on Elixir 1.7.3 and OTP 20 I see:
```
Source         Requirement       
mix.exs        ~> 0.2 or ~> 0.4  
makeup         ~> 0.2.2          
makeup_elixir  ~> 0.2.2 
```
Which means I can't use a version later than that in my project and `mix hex.update nimble_parsec` won 't allow the update.

**Comment by wojtekmach** [comment]
Wrong GitHub repo? :)

**Comment by kipcole9** [comment]
That curious because I was sure that `makeup` and `makeup_elixir` are added when i `kiex install 1.7.3` and therefore I assumed a part of the current Elixir build process?  Apologies if thats not the case and I'll keep digging.

**Comment by wojtekmach** [comment]
I know ex_doc depends on makeup but I dont think anything in Elixir itself does.

**Comment by kipcole9** [comment]
You are right, apologies.  Shouldn't be doing this at midnight (in my zone).  Closing.
