### ISSUE TITLE
 [error] Can't load module ':lists' that resides in sticky dir

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8183]
I'm getting this error message on screen, but no test fails.

    [error] Can't load module ':lists' that resides in sticky dir

It doesn't happen all the time, but you can reproduce it with seed `513799`
the offending line is in file: iex/helpers_test.exs
```elixir
assert nl([node()], :lists) == {:ok, [{:nonode@nohost, :error, :sticky_directory}]}
```
I have tried running inside `capture_io` to no avail.
any idea how to stop the error message from spilling into the output?

```
==> iex (exunit)
...............................................
21:38:56.786 [error] Can't load module ':lists' that resides in sticky dir

...................................................................................................................................................................

Finished in 12.1 seconds (1.4s on load, 10.7s on tests)
210 tests, 0 failures

Randomized with seed 513799
```

**Comment by eksperimental** [comment]
Running
Erlang/OTP 21 [erts-10.0.5]

**Comment by fertapric** [comment]
Related https://github.com/elixir-lang/elixir/pull/8055

**Comment by fertapric** [comment]
The test case `assert nl([node()], :lists) == {:ok, [{:nonode@nohost, :error, :sticky_directory}]}` always produces an error message. That error message should be captured by `ExUnit.CaptureLog.capture_log/2`, but my hypothesis if that the error message arrives too late and the error is printed.

In #8055, I tried moving the error message from the bottom to give some time to the message to arrive. We might move the assertion to the top, but that does not guarantee that the error message won't appear.

**Comment by eksperimental** [comment]
It has happened again @fertapric 

Elixir 1.8.0-dev (de9207895) (compiled with Erlang/OTP 21)

```
==> iex (ex_unit)
................................................
12:08:41.253 [error] Can't load module ':lists' that resides in sticky dir

....................................................................................................................................................................

Finished in 6.4 seconds (1.3s on load, 5.1s on tests)
212 tests, 0 failures

Randomized with seed 967841
```

**Comment by fertapric** [comment]
@eksperimental this message is printed due to a race condition. The PRs reduced the odds, but they did not remove it. 

I have plans of [adding a `logger:flush/0`](https://github.com/elixir-lang/elixir/pull/8186#issuecomment-420315058) function that we can use in our tests, but I've not worked on it yet (but I will!) 🙂

**Comment by fertapric** [comment]
@eksperimental this message is printed due to a race condition. The PRs reduced the odds, but they did not remove it. 

I have plans of [adding a `logger:flush/0`](https://github.com/elixir-lang/elixir/pull/8186#issuecomment-420315058) function that we can use in our tests, but I've not worked on it yet (but I will!) 🙂

**Comment by eksperimental** [comment]
Yes, I knew it wasn't guarantee to work most of the time.
One question, Is it replicable when you pass the seed?

**Comment by fertapric** [comment]
@eksperimental I think not (sorry for the late reply, this was lost in my inbox)

**Comment by eksperimental** [comment]
@fertapric thank you for the answer and no worries
