### ISSUE TITLE
Confusing error on duplicate import

### ISSUE THREAD

**Issue by nathanl** [elixir-lang/elixir#8187]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.1 (compiled with Erlang/OTP 21)
* Operating system: MacOS High Sierra (10.13.6)

### Current behavior

A duplicate function in the `import only:` list fails with a confusing error.

```elixir
defmodule Foo do
  def hi, do: "hi there"
end

defmodule Bar do
  import Foo, only: [hi: 0, hi: 0]
  def greet, do: hi()
end

IO.puts Bar.greet()
```

The problem is that `hi: 0` is repeated in the `import`. But the `CompileError` says `cannot import Foo.hi/0 because it is undefined or private`. This is confusing because `hi: 0` clearly is defined and public.

### Expected behavior

The compiler should give a warning or error that identifies the problem as a duplicate import. Something like `cannot import Foo.hi/0 because it has already been imported`, or `hi/0 is specified multiple times in the same import statement`.

**Comment by josevalim** [comment]
I think we can raise CompileError as it doesn't work today anyway. :+1:
