### ISSUE TITLE
quoted atom warning is poorly worded (and probably unneeded)

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#8197]
* erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
* Elixir 1.7.2 (compiled with Erlang/OTP 21)

Given

~~~ elixir
  def info_function_name do
    :"oɟuı_ʇuǝuodɯoɔ"
  end
~~~
 
The compiler warns with:

~~~
warning: found quoted atom "oɟuı_ʇuǝuodɯoɔ" but the quotes are not required. Quotes should only be used to introduce atoms with foreign characters in them
  lib/component.ex:9
~~~

Two things: 

1. The idea of "foreign characters" probably doesn't mean much, as we now support any UTF letter chars in atoms.

2. Why does the compiler care? If I choose to add quotes where they're not needed, then I guess the formatter could remove them, but as it makes no different to the semantics, I don't think it helps to warn. It's as if the compiler warns for 

~~~
a =  1 + (2*a)    # should warn about unneeded parens

a = 2 * 6   # should warn that 2*6 should be replaced with 12
~~~
and so on.

**Comment by fertapric** [comment]
Related https://github.com/elixir-lang/elixir/issues/7634

**Comment by josevalim** [comment]
Thanks @pragdave, I agree that considering UTF-8 the warning is not good enough.

There are two reasons for the warning:

1. The first one, as linked by @fertapric, is that the use of quotes is often confusing, leading developers to think we will have string keys, while they are still atoms

2. The second one is that there may be a difference in meaning between `:josé` and `:"josé"`, as outlined in our [Unicode Syntax document](https://hexdocs.pm/elixir/unicode-syntax.html#content). The former can only be written in a single way (NFC format) while the latter can be written in multiple ways according to the Unicode spec, which can be the source of confusion. This means that, based on the visual representation, `:josé` is always equal to  `:josé` but `:"josé"` is not always equal to something written as `:"josé"`. So not having the quotes removes ambiguity and potencial confusion.

My preference would be to adjust the warning, and suggestions are welcome. But I am fine to restrict the warning only to ascii characters so we still address #7634.

**Comment by josevalim** [comment]
@pragdave right, we are mirroring strings precisely. Once the atoms are quoted, they can be as bad as strings.

**Comment by josevalim** [comment]
Also, not having quotes mimics identifiers, where you can have an identifier called `oɟuı_ʇuǝuodɯoɔ`, as long as it is in NFC format. You can't quote identifiers though. So they are always in NFC.

**Comment by pragdave** [comment]
Do macros normalize all strings before emiting their result? If not, then
the issue is still there.

I'm, just wondering how often this actually is a problem.

As for the error, why not just issue it if the string isn't normalized (so
str != String.normalize(string, :nfc)). Then the error could be "atoms must
follow the same rules as identifiers, and be normalized Unicode"

**Comment by josevalim** [comment]
> Do macros normalize all strings before emiting their result? 

No, we don't change the string/atom normalization ever. It is going to be same as the source. But I don't see how macros are part of this discussion?

> As for the error, why not just issue it if the string isn't normalized

We shouldn't normalize strings, for some reasons users may be dependent on that. Do you mean to normalize atoms? I am actually OK with requiring atoms to always be normalized NFC. Less source for confusion.

But keep in mind that we still remove the quote for ascii only atoms when possible because of issue 1) above.

**Comment by pragdave** [comment]
> > As for the error, why not just issue it if the string isn't normalized

I mean the string in `:"string"`

> 
> But keep in mind that we still remove the quote for ascii only atoms when possible because of issue 1) above.

If you normalize a quoted atom, and unquoted atoms must already be normalized, then haven't we removed the ambiguity? So the ASCII issue goes away, because ASCII is always normalized.

**Comment by josevalim** [comment]
I am on my phone Dave but if you re-read my first reply, there are actually
two reasons for removing the quotes. I am referring to the first one, which
we haven’t discussed yet, and @fertapric linked to.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by pragdave** [comment]
Ah, so the problem here is that the "string" in `:"string"` doesn't actually mean "string literal that I'm converting to an atom at compile time". It's really just a delimiter. So perhaps the solution to the original problem is to move away from the `:"string"` syntax to make that clear. Perhaps `~:/my atom name/` ?

FWIW I personally don't find `"my key": "my value"` confusing, and no one in my classes has either. But that's just a small sample.

I'm happy to close this, as I think all the bases have been covered.

**Comment by josevalim** [comment]
> FWIW I personally don't find "my key": "my value" confusing, and no one in my classes has either. But that's just a small sample.

It does come up all the time, unfortunately.

We still have a decision to make here: which is to not warn on quotes for non-ascii atoms. I think we can do this without affecting 1. Do you think we should go ahead with this?

**Comment by josevalim** [comment]
Or even better. Assuming we will stay as is, how would you rewrite the warning so it is less confusing?

**Comment by josevalim** [comment]
Dave, I pushed a better message, let me know if it is clearer now! Thanks for the feedback!
