### ISSUE TITLE
Module and function name allow for white-spaces. Unnecessary?

### ISSUE THREAD

**Issue by mdsmithson** [elixir-lang/elixir#8199]
System.halt
can also be ran as 
System.                                                     halt

Is this necessary? does it serve any purpose?

**Comment by josevalim** [comment]
As the issue template asks, please do not use the issues tracker for questions and discussions. ElixirForum or mailing list are more appropriate. But in a nutshell, we treat the `.` as an operator, so the space is allowed. Tools like the Elixir Formatter normalize this though and remove any space.
