### ISSUE TITLE
Better error message when defining the same record twice

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#8210]
### Environment

* Elixir & Erlang/OTP versions: Elixir 1.8.0-dev (13ced80fc) (compiled with Erlang/OTP 21)

### Current behavior

I've accidentally defined the same record twice (bad git merge) and got pretty cryptic error. It was   easy enough to see what's wrong as it says "defines defaults multiple times" but perhaps there's a way for something more explicit. Here's a repro:

```elixir
defmodule M do
  import Record
  defrecord :r, [:a]
  defrecord :r, [:a]
end
```

```
** (CompileError) a.ex:4: defmacro r/1 defines defaults multiple times. Elixir allows defaults to be declared once per definition. Instead of:

    def foo(:first_clause, b \\ :default) do ... end
    def foo(:second_clause, b \\ :default) do ... end

one should write:

    def foo(a, b \\ :default)
    def foo(:first_clause, b) do ... end
    def foo(:second_clause, b) do ... end

    a.ex:4: (module)
```

### Expected behavior

Better error message, e.g.: `"record :a is already defined"`

**Comment by josevalim** [comment]
We can use Module.defines? to check that something with the same name does not already exist.

**Comment by cryic** [comment]
Thanks for the starter issue! I'd like to take a first pass at this. I'll respond here if I have any questions.
