### ISSUE TITLE
File.rm_rf not deleting recursively

### ISSUE THREAD

**Issue by alanj853** [elixir-lang/elixir#8230]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): IEx 1.6.3 (compiled with OTP 19)
* Operating system: Ubuntu 16.04.4 LTS

### Current behavior
When attempting to delete a folder recursively, this function can get called. http://erlang.org/doc/man/file.html#del_dir-1, which has an error ":eexist", which means directory is not empty. Recursive remove should not do that, I think.

### Expected behavior
 I would have thought this issue would never arise for the File.rm_rf command as I would have thought it would behave the same as the Linux command that it very closely resembles.

**Comment by josevalim** [comment]
@alanj853 can you please provide an example of where this happens? Under what circumstances? Could it be that a file in the directory is still being? We need more info so we can reproduce and fix the issue.

**Comment by josevalim** [comment]
@alanj853 ping?

**Comment by josevalim** [comment]
Closing for now. Please let us know if you have a way to reproduce the problem and we will gladly look into it. Thanks!

**Comment by narup** [comment]
I think this happens when the file is being used. I noticed this while trying to delete the .mnesia directory from a code using the shell but mnesia is using that folder. @josevalim not sure how easy it is to implement but it doesn't return any error
