### ISSUE TITLE
Unquote leaves a trace of its own in the resulting AST

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8233]
### Environment

Elixir 1.7.3
macOS High Sierra 10.13.6

### Current behavior

The result of the following expression

    quote do
      defmodule X do
        unquote do
          args = [{:a, [], Elixir}, {:b, [], Elixir}]
          quote do
            def myfun(unquote_splicing(args)) do
            end
          end
        end
      end
    end

is this

    {:defmodule, [context: Elixir, import: Kernel],
     [
       {:__aliases__, [alias: false], [:X]},
       [
         do: [ # <---- SHOULD NOT BE HERE
           do: {:def, [context: Elixir, import: Kernel],
            [
              {:myfun, [context: Elixir], [{:a, [], Elixir}, {:b, [], Elixir}]},
              [do: {:__block__, [], []}]
            ]}
         ] # <---- SHOULD NOT BE HERE
       ]
     ]}

### Expected behavior

The result of the previous expression should match that of this expression

    quote do
      defmodule X do
        def myfun(a,b) do
        end
      end
    end

which is

    {:defmodule, [context: Elixir, import: Kernel],
     [
       {:__aliases__, [alias: false], [:X]},
       [
         do: {:def, [context: Elixir, import: Kernel],
          [
            {:myfun, [context: Elixir], [{:a, [], Elixir}, {:b, [], Elixir}]},
            [do: {:__block__, [], []}]
          ]}
       ]
     ]}

The execution of either `quote` or `unquote` should not leave a trace of their own in the resulting AST.

**Comment by whatyouhide** [comment]
You're unquoting the `do`/`end` block you're passing to `unquote`. `unquote` doesn't take a block so it's taking that literally and unquoting that block. Does that make sense?

**Comment by mguimas** [comment]
That makes sense. I though quote was supposed to run any block of code inside, and return a quoted expression at the end, but it is not that powerful. Thanks.

**Comment by whatyouhide** [comment]
To achieve what I *think* you're trying to achieve in your code snippet, you could do something like this:

```elixir
quote unquote: false do
  defmodule X do
    args = [{:a, [], Elixir}, {:b, [], Elixir}]

    def myfun(unquote_splicing(args)) do
      a + b
    end
  end
end
```

**Comment by mguimas** [comment]
I was trying to achieve this:

```
  defmodule X do
    def myfun(a,b) do
    end
  end

{:defmodule, [context: Elixir, import: Kernel],
 [
   {:__aliases__, [alias: false], [:X]},
   [
     do: {:def, [context: Elixir, import: Kernel],
      [
        {:myfun, [context: Elixir], [{:a, [], Elixir}, {:b, [], Elixir}]},
        [do: {:__block__, [], []}]
      ]}
   ]
 ]}
```
but what you did returns this:

```
defmodule(X) do
  args = [{:a, [], Elixir}, {:b, [], Elixir}]
  def(myfun(unquote_splicing(args))) do
    a + b
  end
end

{:defmodule, [context: Elixir, import: Kernel],
 [
   {:__aliases__, [alias: false], [:X]},
   [
     do: {:__block__, [],
      [
        {:=, [],
         [
           {:args, [], Elixir},
           [
             {:{}, [], [:a, [], {:__aliases__, [], [Elixir]}]},
             {:{}, [], [:b, [], {:__aliases__, [], [Elixir]}]}
           ]
         ]},
        {:def, [context: Elixir, import: Kernel],
         [
           {:myfun, [context: Elixir],
            [{:unquote_splicing, [], [{:args, [], Elixir}]}]},
           [
             do: {:+, [context: Elixir, import: Kernel],
              [{:a, [], Elixir}, {:b, [], Elixir}]}
           ]
         ]}
      ]}
   ]
 ]}
```

In fact, I was trying to do too much computation perhaps inside `unquote`, hence I used `unquote do ... end`. When too much computation is needed it is then preferred to do `unquote(func(...))` and to do the computation inside `func`.

Thanks.

**Comment by fertapric** [comment]
Exactly. As @whatyouhide explained, you are passing a `do ... end` block to `unquote`. 

You can also define the quoted expression before:

```elixir
args = [{:a, [], Elixir}, {:b, [], Elixir}]

fun_ast = quote do
  def myfun(unquote_splicing(args)) do
  end
end

quote do
  defmodule X do
    unquote(fun_ast)
  end
end
```

or, as you mentioned, move the calculation of `fun_ast` to a different function.

**Comment by whatyouhide** [comment]
When you eval the quoted code:

```elixir
defmodule(X) do
  args = [{:a, [], Elixir}, {:b, [], Elixir}]
  def(myfun(unquote_splicing(args))) do
    a + b
  end
end
```

it works as expected though :). But yeah manipulating the AST through other functions is usually better.

**Comment by mguimas** [comment]
Thanks for you clarifications. 👍
