### ISSUE TITLE
Perform {type_syntax, _} checks in Kernel.Typespec

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#8242]
Today `erl_lint` performs checks for syntax in typespecs (search for `{type_syntax` [in this file](https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_lint.erl)). Since we will no longer run `erl_lint`, we need to perform those checks ourselves.

They are:

  * [x] Check that the (... -> ...) syntax is a product or any on the left side
  * [ ] Check that both sides of `x..y` are integers after expansion
  * [ ] Check that all `x` and `y` in `<<x * y>>` are non negative integers
  * [ ] Check that the record name in `record(name, ...)` is an atom

This is a leftover from #5800.

**Comment by whatyouhide** [comment]
@fertapric I'll take this if you're not already working on it.

**Comment by fertapric** [comment]
@whatyouhide 👍

**Comment by whatyouhide** [comment]
Letting this one free for now, I'll pick it up in a bit if no one has picked it up by then. But feel free to claim it! :)

**Comment by josevalim** [comment]
Closing in favor of the PR.
