### ISSUE TITLE
Compiler warning when using a guard clause that looks at a module attribute

### ISSUE THREAD

**Issue by MainShayne233** [elixir-lang/elixir#8245]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
- Elixir 1.7.3
- Erlang 20.3.8.8
* Operating system: 
- Linux
- Mac

### Current behavior

If a guard close solely looks at a module attribute, like so:

```elixir
defmodule Demo do
  @moduledoc false

  @test_module_attribute Application.get_env(:demo, :test_value)

  def test when @test_module_attribute == true do
    :something
  end

  def test when @test_module_attribute == false do
    :something_else
  end
end
```

then the following compiler warning is emitted:

```
warning: this clause cannot match because a previous clause at line 6 always matches
  lib/demo.ex:10
```

### Expected behavior

A compiler warning should not be emitted. This is a useful behavior configuring which function clause gets called at compile time via configs.

**Comment by Gazler** [comment]
This code will be rewritten as:

```
defmodule Demo do
  @moduledoc false

  def test when true == true do
    :something
  end

  def test when true == false do
    :something_else
  end
end
```

To achieve the same thing you can write:

```
defmodule Demo do
  @moduledoc false

  if Application.get_env(:demo, :test_value) do
    def test(), do: :something
  else
    def test(), do: :something_else
  end
end
```

**Comment by whatyouhide** [comment]
Yeah since the value of the module attribute is evaluated at compile time, the compiler will see `true == true` and complain that this will always be true. Rewriting it as @Gazler suggested is the way to go here if you mean to read the value from the app environment at compile time.

**Comment by MainShayne233** [comment]
Sweet! Thanks you both!
