### ISSUE TITLE
Do not raise if Kernel.get_in recurses onto a structure that does not implement Access

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-lang/elixir#8246]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.7.3
* Operating system: Mac OS X high Sierra

### Current behavior

`get_in(%{"a" => 1}, ["a", "b"])`

Produces the exception
```
** (FunctionClauseError) no function clause matching in Access.get/3

    The following arguments were given to Access.get/3:

        # 1
        1

        # 2
        "b"

        # 3
        nil

    Attempted function clauses (showing 5 out of 5):

        def get(%module{} = container, key, default)
        def get(map, key, default) when is_map(map)
        def get(list, key, default) when is_list(list) and is_atom(key)
        def get(list, key, _default) when is_list(list)
        def get(nil, _key, default)

    (elixir) lib/access.ex:316: Access.get/3
```

### Expected behavior

`get_in(%{"a" => 1}, ["a", "b"])` should return `nil`

**Comment by josevalim** [comment]
Can you please explain why this is expected behavior? Because I would find
it counter intuitive and possibly a cause of bugs in my software. If you
want to provide unsafe access, then you should probably have your own
acessors.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by mobileoverlord** [comment]
Lets say I have a tree of data, 
```
data = %{"a" => %{"b" => 2}, "c" => "123"}
```
If I want to check to see if a value exists in this tree I can use 

```
2 = get_in(data, ["a", "b"])
```

or I could look for a value that does not exist
```
nil = get_in(data, ["d"])
```

In this case, a value at the specified key path does not exist, but will raise because it recurses through part of a path that exists.
```
get_in(data, ["a", "b", "d"])
```

The last example is what makes me feel like it should respond with `nil` because a value at that key path does not exist.

**Comment by mobileoverlord** [comment]
If raising is the right thing to do, then I can just protect my code from this case.

**Comment by josevalim** [comment]
Right, but nil implements the behavior. You need to handle this yourself
for everything else. I wouldn’t expect get_in to silently return on non-nil
non-kv input.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by OvermindDL1** [comment]
Wrong place I know, but I'd honestly prefer something like `get_in(%{a: 1}, [:a, Access.try_(:b, fn _ -> %{c: 42} end), :c])` or so.  I wonder if that's doable via a custom function actually...  Hmm...
