### ISSUE TITLE
Fast list nth

### ISSUE THREAD

**Issue by jjl** [elixir-lang/elixir#8248]
I have discovered that a simple inline function works quicker than `Enum.at` for accessing the nth item of a list.

It would be nice if we could include this in elixir as `List.nth` and have the `Enum.at` delegate to it.

## Benchmark result

```
Name              ips        average  deviation         median         99th %
inl_nth       14.05 K       71.17 μs    ±16.06%          67 μs         119 μs
enum_at        7.01 K      142.56 μs    ±11.32%         136 μs         202 μs

Comparison: 
inl_nth       14.05 K
enum_at        7.01 K - 2.00x slower
```
## Faster Code

```elixir
@compile {:inline, nth: 3}
def nth(list, n, default \\ nil)
def nth([], _, default), do: default
def nth([val|_], 0, default), do: {:ok, val}
def nth([_|rest], n, default), do: nth(rest, n - 1, default)
```

### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.3 (compiled with Erlang/OTP 21)
* Operating system: OSX High Sierra

**Comment by jjl** [comment]
## Benchmark

```
list = Enum.to_list(1..10_000)

%{
  "inl_nth"  => fn -> nth(list, 10_000) end,
  "enum_at" => fn -> Enum.at(list, 10_000) end,
}
|> Benchee.run()
```

**Comment by fertapric** [comment]
@jjl I would run the benchmarks again without the inlining and supporting negative indexes 🙂 

> A negative index can be passed, which means the enumerable is enumerated once and the index is counted from the end (e.g. -1 finds the last element).

**Comment by jjl** [comment]
My version that handles negative indices (`inl_nthplus`) runs about the same:

```
Name                  ips        average  deviation         median         99th %
inl_nth           14.39 K       69.48 μs    ±14.23%          66 μs         112 μs
inl_nthplus       14.37 K       69.57 μs    ±14.45%          66 μs         110 μs
enum_at            7.18 K      139.19 μs    ±11.33%         132 μs         197 μs

Comparison: 
inl_nth           14.39 K
inl_nthplus       14.37 K - 1.00x slower
enum_at            7.18 K - 2.00x slower
```

I don't understand why you're keen to remove the inline-ness.

**Comment by josevalim** [comment]
@jjl removing the inline cases just helps us understand if the benefit comes from the inlining or the rewriting of the algorithm. Anyway, it seems those changes are welcome, can you please send a PR that optimizes Enum.at? I don't think we should add `List.nth`, as `nth` implies 1-based indices, and the List module is meant to complement Enum, there is almost no overlap.

**Comment by jjl** [comment]
@josevalim I would prefer this functionality was available without having to go through Enum, as a public function somewhere so that we can reuse it directly. Whether it belongs in `List` or under the name `nth` are things I'd be happy to take suggestions on.

**Comment by josevalim** [comment]
@jjl the place where this functionality belongs is Enum.at. :)

**Comment by josevalim** [comment]
Ok, closing this then. A PR is welcome any time!
