### ISSUE TITLE
The ":unquote" option behavior of "quote" does not match what is documented

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8249]
### Environment

* Elixir 1.7.3
* macOS 10.13.6

### Current behavior

According to this

>:unquote - when false, disables unquoting. Useful when you have a quote inside another quote and want to control what quote is able to unquote.

isn’t this
```
x = "Hello"
quote unquote: false do
  quote do
    unquote(x)
  end
end
```
supposed to return this
```
{:quote, [], [[do: "Hello"]]}
```
?

It is returning `{:quote, [], [[do: {:unquote, [], [{:x, [], Elixir}]}]]}` which seems contrary to what is documented for the `:unquote` option.

### Expected behavior

I believe it is the documentation that needs to be fixed to something like this:

```
:unquote - when false, disables unquoting. This injects the AST of an `unquote(...)` itself
           in the result of its enclosing `quote`. For example.

iex(1)> quote unquote: false do
...(1)>   quote do
...(1)>     unquote(x)
...(1)>   end
...(1)> end
{:quote, [], [[do: {:unquote, [], [{:x, [], Elixir}]}]]}
```

**Comment by josevalim** [comment]
Note that the unquote inside the inner quote is never escaped anyway, so the docs are definitely unclear.

**Comment by mguimas** [comment]
So the documentation is wrong, and I reworked my suggestion to be more clear (see above the update).

**Comment by josevalim** [comment]
I have pushed some improvements, if you feel we could do better, please send a PR as well. Thanks! :)

**Comment by mguimas** [comment]
Thanks

**Comment by mguimas** [comment]
No, its perfect. Thanks
