### ISSUE TITLE
can not find the doc about 'label' of Inspect.Opts

### ISSUE THREAD

**Issue by absente** [elixir-lang/elixir#8250]
https://hexdocs.pm/elixir/master/IO.html#inspect/2
the doc use a 'label' opts for IO.inspect/2：

```elixir
IO.inspect(1..100, label: "a wonderful range")
```

However, the 'label' opts can not found in its doc:
https://hexdocs.pm/elixir/master/Inspect.Opts.html

### Environment

* Elixir & Erlang/OTP versions (elixir --version):  
```
Erlang/OTP 21 [erts-10.1] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
Elixir 1.7.3 (compiled with Erlang/OTP 19)
```
* Operating system:  Windows 10 pro x64, version  10.0.17134.285

**Comment by josevalim** [comment]
The docs you linked say:

> The output can be decorated with a label, by providing the :label option to easily distinguish it from other IO.inspect/2 calls. The label will be printed before the inspected item.
> See Inspect.Opts for a full list of remaining formatting options.

So it is documented in the IO.inspect/2 function itself. What are we missing? :)

**Comment by fertapric** [comment]
@absente `:label` cannot be included in `Inspect.Opts` because it's an specific option of [`IO.inspect/2`](https://hexdocs.pm/elixir/master/IO.html#inspect/2). The options listed in `Inspect.Opts` are also used in [`Kernel.inspect/2`](https://hexdocs.pm/elixir/master/Kernel.html#inspect/2).

**Comment by absente** [comment]
@josevalim @fertapric  thanks. I got the mind
