### ISSUE TITLE
Makefile `test`s tasks should when warning is emitted

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8271]
The tests should stop same as the compilation,
I haven't managed to successfully make this work, that's why I'm creating an issue.
What's the proper way to pass the `warnings_as_errors` flag to `elixir` bin under the `--erl` flag?
I would be happy to create a PR once I figure this out

**Comment by josevalim** [comment]
I don't think we need to have warnings_as_errors in the tests because this will hurt the ability of running all tests at once and get a complete report.

**Comment by eksperimental** [comment]
Where can I read about these limitations when running with warnings_as_errors?
Thank you
