### ISSUE TITLE
mix deps.get not working for hex dependencies in Mac OS 10.13.6

### ISSUE THREAD

**Issue by Sumitforyou** [elixir-lang/elixir#8281]
### Environment

Elixir Version - 1.7.3
Erlang Version - Otp/21
Operating system- Mac OS 10.13.6

### Current behavior

mix deps.get

Could not find Hex, which is needed to build dependency :jsex
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn]  Y

(no response, seems it hangs).

I tried - brew update && brew upgrade && brew cleanup and removing and reinstalling erlang and elixir
still facing the issue.

**Comment by josevalim** [comment]
I wonder if if it can be the IPv6 issue mentioned in #8252?

What happens if you start `iex` and run:

    iex> :httpc.set_option(:ipfamily, :inet6fb4, :mix)

In any case, you can download Hex here at this address:

    https://repo.hex.pm/installs/1.6.0/hex-0.18.1.ez

Then you do this:

    mix archive.install path/to/where/you/downloaded/hex

And you should be good to go!

Help elixiring!

**Comment by Sumitforyou** [comment]
`iex(1)> :httpc.set_option(:ipfamily, :inet6fb4, :mix)` gave `:ok`

It worked for me .

**Comment by pavanagrawal123** [comment]
@josephwilk I am observing this behavior on Mojave (10.14) when connected over a VPN, btw!
Ran the command in this thread, but it did not fix. Disconnecting from the VPN did!
