### ISSUE TITLE
Variable definition inside case block warning is printed from with block

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-lang/elixir#8285]
### Environment

```
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.2 (compiled with Erlang/OTP 21)
```
### Current behavior

This code prints a warning that I think should not be there
```
  with :ok <- Foo.ensure_permissions(subject, Authorizer.read_permission()),
         {:ok, messages} <- Message.Mutator.mark_messages_as_read_by_user(query, subject.user),
         {:ok, conversation} <- Conversation.Mutator.decrement_unread_count(conversation, length(messages)) do
      :ok
    end
```

The printed warning can be confusing because it tells us about the variable definition in case block which is generated with macros:
```
warning: variable "conversation" is unused

Note variables defined inside case, cond, fn, if and similar do not leak. If you want to conditionally override an existing
 variable "conversation", you will have to explicitly return the variable. For example:

    if some_condition? do
      atom = :one
    else
      atom = :two
    end

should be written as


    atom =
      if some_condition? do
        :one
      else
        :two
      end

Unused variable found at:
  lib/my_app_domain/messaging.ex:194
```

Replacing `conversation` with `_conversation` would silence the whole output.

### Expected behavior

Only `warning: variable "conversation" is unused` warning should be printed without information about variables in case, cond and other blocks.

**Comment by josevalim** [comment]
I believe this warning is causing more pain than helping, so I believe we should just go ahead and remove it for Elixir v1.8.

**Comment by josevalim** [comment]
The reason why we have to remove it is because all of the forms were unified in v1.7, which means case/with/if all behave the same.
