### ISSUE TITLE
`Code.format_string!/2` should format numbers that are not completely formatted, or poorly formatted

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8301]
```elixir
# half formatted
1000_000

# poorly formatted
100_0000
```

In the first case it is likely the user forgot to add the first underscore
and in the second example it is misleading and the programmer may think when reading the number
that this is is `100_000` when it actually is `1_000_000`

IMO the formatter should standardize these numbers as well

**Comment by josevalim** [comment]
This is by design as you may have entries expressed as a numbers, that should not be read as 1_000_000 but rather as 1000_0000.
