### ISSUE TITLE
Extra space in metadata part of log messages

### ISSUE THREAD

**Issue by albertored** [elixir-lang/elixir#8339]
### Environment
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.7.3 (compiled with Erlang/OTP 21)
```

### Current behavior
At the moment the `Logger.Formatter` add a space at the end of metadata chardata:
```elixir
iex> pattern = Logger.Formatter.compile("[$level] $metadata$message\n")
iex> formatted = Logger.Formatter.format(pattern, :info, "hello", nil, [foo: 1, bar: "baz"])
iex> IO.chardata_to_string(formatted)
"[info] foo=1 bar=baz hello\n"
```
this makes log formats like the follwowing a little bit ugly
```elixir
iex> pattern = Logger.Formatter.compile("[$level] ($metadata) $message\n")
iex> formatted = Logger.Formatter.format(pattern, :info, "hello", nil, [foo: 1, bar: "baz"])
iex> IO.chardata_to_string(formatted)
"[info] (foo=1 bar=baz ) hello\n"
```

### Expected behavior

The last space at the end of metadata part should be removed.

I took a look at the code and implementing this fix should be straightforward so I'm wondering if there is a reason that I'm not aware of for having that space.

One con I can think of is that this change can be viewed as a breaking one since all format strings like `"$metadata$message"` will then result in log messages with a missing space and maybe you are not interested in changing it for this reason. If not I can submit a PR.

**Comment by josevalim** [comment]
Hi @albertored! Yes, this would be a breaking change. The best option in your case is maybe to use a custom formatter. See Logger.Formatter for examples.
