### ISSUE TITLE
@doc tag for describe block is not recognized

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8341]
I get this warning when I use `@doc` for describe, and inside a describe, there is a `setup` callback.

```
warning: defp __ex_unit_setup_0/1 is private, @doc attribute is always discarded for private functions/macros/types
  test/ex_unit/filters_test.exs:8
```

```
defmodule ExUnit.FiltersTest do
  use ExUnit.Case

  @doc """
  some documentation
  """
  describe "filter precedence" do
    setup do
      [foo: :bar]
    end

    test "no filters", tags do
      assert(true)
    end
```

the issue is solved by moving up `setup`

```
defmodule ExUnit.FiltersTest do
  use ExUnit.Case

  setup do
    [foo: :bar]
  end

  @doc """
  some documentation
  """
  describe "filter precedence" do
    test "no filters", tags do
      assert(true)
    end
```

which leaves me thinking that describe does not take the `@doc` correctly, and the compiler thinks it belongs to `setup`.

While is it nice to place setup inside a describe, there is no warning against it, So I consider it a bug.

**Comment by wojtekmach** [comment]
Given _test.exs files won’t get IEx etc docs, if you want to document some stuff how about using comments instead?

**Comment by eksperimental** [comment]
oh.... `@doc` warning happened because of `setup` , probably the docs for test are not assigned either

**Comment by josevalim** [comment]
`describe` does not define any function, so you can't really `@doc` it. And I think that's the issue with thinking that test and describe are doc-able, it can be tricky to figure out which construct has a definition underneath and which ones do not.

**Comment by eksperimental** [comment]
Would it be possible to add a warning then? so avoid adding the doc to whatever doc-able element comes first inside the describe

**Comment by josevalim** [comment]
@eksperimental we can't do that effectively, right? We would need to add code that checks for a warning to every non-docable element, which doesn't "scale".

**Comment by eksperimental** [comment]
fair enough
