### ISSUE TITLE
CaseClauseError with map module attribute with duplicate keys

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#8345]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.8.0-dev (6c4d359b1) (compiled with Erlang/OTP 21)
* Operating system: macOS

### Current behavior

This works:

```elixir
defmodule M do
  @flags %{
    a: 0x0001,
    a: 0x0002
  }

  IO.inspect @flags
end
```

```
~% elixir a.exs
warning: key :a will be overridden in map
  a.exs:2

%{a: 2}
```

However this raises a CaseClauseError

```elixir
defmodule M do
  @flags %{
    a: 0x0001,
    a: 0x0002,
    a: 0x0004
  }

  IO.inspect @flags
end
```

```
warning: key :a will be overridden in map
  a.exs:2

** (CaseClauseError) no case clause matching: :ok
    (stdlib) lists.erl:1263: :lists.foldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

Not sure if worth fixing as we get a warning already but thought I'll mention this anyway.

### Expected behavior

No error.

**Comment by fertapric** [comment]
Should it warn twice?

**Comment by josevalim** [comment]
@fertapric i would say so, yes. But if it is too complex, warning once is also fine.
