### ISSUE TITLE
IEx.Helpers.import_file/1 does not work as documented

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8353]
### Environment

* Elixir 1.7.3 

### Current behavior

The documentation for `IEx.Helpers.import_file/1` state that this macro

> Evaluates the contents of the file at path as if it was directly typed into the
shell.

For example, given file `x.exs` (the extension does not matter) with the following code

```
defmodule X do
  defmacro hello do
    quote do
      alias Foo.Bar
      IO.puts("Hello World")
    end
  end
end

require X
X.hello
```
it results in an error when running this in IEx

```
$ iex
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> IEx.Helpers.import_file("x.exs")
** (CompileError) iex:10: module X is not loaded but was defined. This happens when you depend on a module in the same context in which it is defined. For example:

    defmodule MyApp do
      defmodule Mod do
      end

      use Mod
    end

Try defining the module outside the context that uses it:

    defmodule MyApp.Mod do
    end

    defmodule MyApp do
      use MyApp.Mod
    end

If the module is defined at the top-level and you are trying to use it at the top-level, this is not supported by Elixir
    (iex) expanding macro: IEx.Helpers.import_file/1
    iex:1: (file)
iex(1)>
```

But typing the lines in the file inside IEx everything runs ok:

```
$ iex
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule X do
...(1)>   defmacro hello do
...(1)>     quote do
...(1)>       alias Foo.Bar
...(1)>       IO.puts("Hello World")
...(1)>     end
...(1)>   end
...(1)> end
{:module, X,
 <<70, 79, 82, 49, 0, 0, 4, 192, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 127,
   0, 0, 0, 13, 8, 69, 108, 105, 120, 105, 114, 46, 88, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, {:hello, 0}}
iex(2)>
nil
iex(3)> require X
X
iex(4)> X.hello
Hello World
:ok
iex(5)>
```

### Expected behavior

Make `IEx.Helpers.import_file/1` work as if the lines of the file were typed inside IEx. Otherwise, if this is a documentation issue, make this clear.

In fact, I do not see any usefulness for this macro if not for reading lines as if these were typed inside IEx, so I prefer this macro to be fixed, not the documentation.

**Comment by ggcampinho** [comment]
Your examples are not the same, the equivalent in `iex` would be:

```
Erlang/OTP 21 [erts-10.0.8] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule X do
...(1)>   defmacro hello do
...(1)>     quote do
...(1)>       alias Foo.Bar
...(1)>       IO.puts("Hello World")
...(1)>     end
...(1)>   end
...(1)> end; require X; X.hello
** (CompileError) iex:8: module X is not loaded but was defined. This happens when you depend on a module in the same context in which it is defined. For example:

    defmodule MyApp do
      defmodule Mod do
      end

      use Mod
    end

Try defining the module outside the context that uses it:

    defmodule MyApp.Mod do
    end

    defmodule MyApp do
      use MyApp.Mod
    end

If the module is defined at the top-level and you are trying to use it at the top-level, this is not supported by Elixir
```

Note that when you type enter, the module will be evaluated and then the second part works.
If you remove the part below from your file, it will work:

```
require X
X.hello
```

It should be done outside of the file, in `iex` or another file. I believe that the error is quite clear.

**Comment by wojtekmach** [comment]
To give some historical context this is not a new issue, see: #3328. I somewhat agree that the docs aren't quite accurate but not sure how change them, whether we should mention this particular case.

Perhaps worth mentioning that:

```
iex(1)> (defmodule M, do: nil) ; require M
** (CompileError) iex:1: module M is not loaded but was defined. This happens when you depend on a module in the same context in which it is defined. For example:
```

**Comment by josevalim** [comment]
I think we could make it work by unpacking expressions and evaling them through a loop. It is more expensive but I also think it would make this feature more useful too.

**Comment by mguimas** [comment]
That's the right decision @josevalim. Also, consider adding a `source("path/to/file")` command to IEx, to make the feature more easy to use and recall than `IEx.Helpers.import_file("path/to/file")`.

**Comment by fertapric** [comment]
@mguimas you can use `import_file("path/to/file")` directly in IEx :)

**Comment by mguimas** [comment]
@fertapric Even though `source("path/to/file")` would be much easier to remember, or even `s("path/to/file")`.

**Comment by ggcampinho** [comment]
I know that the module is IEx.Helpers, but wouldn't be confusing to have a file that works with this function on iex but it doesn't when used as a script? Maybe it would be nice to have an option like `interactive: true`

**Comment by mguimas** [comment]
@ggcampinho I don't think so, because `import_file(..)`, `source(..)` or `s(..)` would have an interactive semantics, as if each line of the input file was typed at the prompt.

**Comment by josevalim** [comment]
> @fertapric Even though source("path/to/file") would be much easier to remember, or even s("path/to/file").

We have decided to add single-letter functions to IEx because we already have too many and they are hard to keep up. We also avoid aliases (two functions with the same name).

**Comment by josevalim** [comment]
I have actually investigated this and unfortunately cannot implement the behaviour here because it is a regular macro and a macro cannot change `Macro.Env` bit by bit. It would be possible for the .dot_iex file but this can add inconsistencies. So unfortunately we will have to go with updating the docs, which I will push to master soon.

**Comment by mguimas** [comment]
@josevalim Don't understand

> We have decided to add single-letter functions to IEx because we already have too many and they are hard to keep up. We also avoid aliases (two functions with the same name).

If `IEx.Helpers.import_file/1` cannot be fixed because it is a macro, then can you introduce a new `source("path/to/file")` or s("path/to/file") that will automate typing on the prompt by executing line-by-line the contents of the file?

This will not be an alias to any existing function, and there are not too many commands at IEx, and particularly, no command starting with an `s`.

This would be a useful addition of a missing feature, especially as `IEx.Helpers.import_file/1` is useless.

**Comment by josevalim** [comment]
I also would like to point out that `import_file` can be used to import or require any module that has been already defined, such as imports/requires from dependencies. The limitation being discussed here applies only for modules defined in the same file, which is a limitation that exists on *all Elixir files*.
