### ISSUE TITLE
Misleading docstring for naive_datetime_to_iso_days

### ISSUE THREAD

**Issue by aawalton** [elixir-lang/elixir#8354]
The function signature for Calendar.naive_datetime_to_iso_days does not include the time zone, and the documentation for Calendar.naive_datetime_to_string explicitly says the input is a datetime without time zone, both of those cannot be correct, I believe the first is wrong.

Current
"Converts the given datetime (with time zone) into the iso_days/0 format."

Should be
"Converts the given datetime (without time zone) into the iso_days/0 format."

**Comment by josevalim** [comment]
Good catch. Can you please send a PR?
