### ISSUE TITLE
Float.ratio(0.0) gives absurd result

### ISSUE THREAD

**Issue by skilchen** [elixir-lang/elixir#8359]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 21 [erts-10.1] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Elixir 1.7.4 (compiled with Erlang/OTP 19)
```
* Operating system: 
Windows 10 (but I don't think it matters)

### Current behavior
```elixir
Float.ratio(0.0)
```
gives:
```elixir
{1,
 89884656743115795386465259539451236680898848947115328636715040578866337902750481566354238661203768010560056939935696678829394884407208311246423715319737062188883946712432742638151109800623047059726541476042502884419075341171231440736956555270413618581675255342293149119973622969239858152417678164812112068608}
```

### Expected behavior
```elixir
Float.ratio(0.0)
```
should give:
```elixir
{0, 1}
```

**Comment by skilchen** [comment]
I would fix it at the function clause level. 

Another issue with Float.ratio might be that it doesn't give correct results for subnormal floats (having an exponent of 0 in the binary representation). But I don't know if elixir makes any claims to support subnormal floats. So my observations might be irrelevant.

something like 
```elixir
# the smallest representable subnormal float as a ratio
Float.ratio(5.0e-324)
```
gives a result different from other languages. Python, Julia and Scheme agree that the result has a 1 in the numerator and number with 324 digits in the denominator starting with 20240225330 and ending with 1093494784.
But elixir gives a result with 4503599627370497 in the numerator and a number which corresponds to the denominator from the other languages times 2.

It is not possible to perform the division of the numerator and denominator in elixir, but using Python, Scheme or Julia the result of the division as 64bit float is the same as in the case of `Float.ratio(0.0)` i.e. the float which has the highest bit in the significand (mantissa) set and all other bits zero in the binary representation.

**Comment by josevalim** [comment]
Great catch @skilchen! Closing in favor of PR #8360!
