### ISSUE TITLE
Failing test example in ExUnit register_attribute documentation

### ISSUE THREAD

**Issue by edwinthinks** [elixir-lang/elixir#8362]
While trying out ExUnit [register_attribute](https://hexdocs.pm/ex_unit/ExUnit.Case.html#register_attribute/3) I noticed that the example code in the documentation results in a test failure.
```
defmodule MyTest do
  use ExUnit.Case
  ExUnit.Case.register_attribute __ENV__, :foobar

  @foobar hello: "world"
  test "using custom test attribute", context do
    assert context.registered.hello == "world"
  end
end
```

It does work however, if I replace `context.registered.hello` with `context.registered.foobar[:hello]`. I am not sure if the documented example is outdated?

### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating system: Mac OSX 10.13.6

### Current behavior

```
defmodule MyTest do
  use ExUnit.Case
  ExUnit.Case.register_attribute __ENV__, :foobar

  @foobar hello: "world"
  test "using custom test attribute", context do
    assert context.registered.hello == "world"
  end
end
```
Has this assertion failure:
```
  1) test using custom test attribute (MyTest)
     test/my_test.exs:6
     ** (KeyError) key :hello not found in: %{foobar: [hello: "world"]}
     code: assert context.registered.hello == "world"
     stacktrace:
       test/my_test.exs:7: (test)
```

### Expected behavior

I would have expected at first that the assertion would not have failed in the documented example.

Let me know if I can help with anything :) Thanks!

**Comment by josevalim** [comment]
THe documented example is wrong. Great catch!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by edwinthinks** [comment]
Opened https://github.com/elixir-lang/elixir/pull/8363 to address this issue. Hope it works!

**Comment by josevalim** [comment]
Closing in favor of #8363.
