### ISSUE TITLE
`Path.wildcard/1` doesn't match ".../**/*.toml" properly

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#8366]
`Path.wildcard/1` finds `.../_schema.toml` when given the pattern `.../**/_schema.toml`.
However, it fails to find it when given the pattern `.../**/*.toml`.  FWIW, Ruby's `Dir.glob` method succeeds in both cases.

**Comment by josevalim** [comment]
@RichMorin can you please fill in the issue template accordingly? Thank you.

**Comment by RichMorin** [comment]
Sorry; user error.  Nothing to see here; move along...

**Comment by josevalim** [comment]
Thanks for the follow up. That's why it is very important to fill the issues template. Sometimes reporting the bug in itself can help fix it. :)
