### ISSUE TITLE
Logger.configure/1 does not validate the values of the keys

### ISSUE THREAD

**Issue by pallix** [elixir-lang/elixir#8367]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
λ elixir --version
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Elixir 1.7.3 (compiled with Erlang/OTP 20)
```

* Operating system: Linux

### Current behavior

`Logger.configure/1` does not validate the values of the keys:

```
iex(1)> require Logger
Logger
iex(2)> Logger.configure(level: :warm)
:ok
iex(3)> Logger.error("Something wrong")
** (FunctionClauseError) no function clause matching in Logger.level_to_number/1    
    
    The following arguments were given to Logger.level_to_number/1:
    
        # 1
        :warm
    
    Attempted function clauses (showing 4 out of 4):
    
        defp level_to_number(:debug)
        defp level_to_number(:info)
        defp level_to_number(:warn)
        defp level_to_number(:error)
    
    (logger) lib/logger.ex:536: Logger.level_to_number/1
    (logger) lib/logger.ex:533: Logger.compare_levels/2
    (logger) lib/logger.ex:668: Logger.__should_log__/1
```

We can see that typing `:warm` (it's winter here...) instead of `:warn` is accepted as a valid logging level even if it's invalid, causing the next call to a log function to crash.

This looks like a harmless error but when changing the logging level error in production with iex this causes the beam process to crash, since every process logging some information will crash. The supervisor will try to restart the processes but the log level is still wrong, causing the processes to further crash, the supervisor to give up and the Beam to crash.

### Expected behavior

I would expect an error earlier, when calling the `Logger.configure/1` function. An `ArgumentError` exception or something equivalent would be appropriate.

**Comment by OvermindDL1** [comment]
Just curious, but wouldn't this be more the realm of Dialyzer?

**Comment by pallix** [comment]
@OvermindDL1 I cannot see how dialyzer would prevent an error when typing dynamically in the REPL on a production system.

It's not the best practice to do so, I agree, but sometimes it is very useful.

**Comment by OvermindDL1** [comment]
Pallix, it couldn't but then again to perform value type checks at runtime like this sounds exceedingly inefficient.

How would you propose this to be done?  Perhaps by changing it to a macro and testing the value, but then that would fail for when a binding is passed in instead of a value, etc... etc...  What if a user makes custom logger levels?  The only thing that opeion does is set the values in the logger application, which can easily be set elsewhere as well (say a config file), and how would you handle if it changed dynamically?  Plus the user might 'want' to set an invalid value to help enforce that a valid value gets set later explicitly, which doesn't need to go through `configure` as it can be set on the application directly.

Though just calling `level_to_number` once on it in configure and a few other times would help ensure the common cases, but it would still lack quite a few.  Maybe a PR?  ^.^

**Comment by josevalim** [comment]
My concern is that this introduces a precedent that is hard to apply generally. For example, should we validate only `:level` or other options? Note similar function exists in ExUnit and IEx, should we apply those there too? Plus, this wouldn't fix `config :logger, level: :warm` in your config files.

So I completely understand the point that, we should fix this despite of other things exhibiting the same behaviour, at the same time I think that fixing this won't actually make much difference after all.

What allows `Logger.configure/2` (and config in general) to be a dynamic API that receives keyword lists is exactly what makes this type checking very hard. I think we would benefit more of some sort of "typed" storage (or "typed" environment variable), than manually tackling each entry.

For this reason, I will make it as unresolved. It would be nice to have a general solution for this, but it will take a while.

Thanks everyone for the discussion.

**Comment by OvermindDL1** [comment]
> For this reason, I will make it as unresolved. It would be nice to have a general solution for this, but it will take a while.

Gradualizer hopefully, when it finishes.  :-)

**Comment by weisslj** [comment]
Note that with Elixir 1.10 this does not seem to crash anymore, invalid keys are just ignored:

```
Erlang/OTP 21 [erts-10.3.5.9] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.10.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> require Logger
Logger
iex(2)> Logger.configure(level: :warm)
:ok
iex(3)> Logger.error("Something wrong")

20:39:50.221 [error] Something wrong
:ok
```
