### ISSUE TITLE
Date.to_iso8601() does not support year > 9999

### ISSUE THREAD

**Issue by capablemonkey** [elixir-lang/elixir#8368]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.3 Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
* Operating system: official `elixir-1.7.3` Docker container, Mac OS 10.12.6 (Docker host)

### Current behavior

Date.to_iso8601 does not support years greater than 4 digits.  Here's a happy example, with a 4 digit year of 2012:

```elixir
iex(2)>  d = %Date{year: 2012, month: 12, day: 25}
~D[2012-12-25]
iex(3)> Date.to_iso8601(d)
"2012-12-25"
```

And this is a sad example, with a 5 digit year of `21200`.

```elixir
iex(4)> d = %Date{year: 21200, month: 12, day: 25}
%Inspect.Error{
  message: "got ArgumentError with message \"argument error\" while inspecting %{__struct__: Date, calendar: Calendar.ISO, day: 25, month: 12, year: 21200}"
}
iex(5)> Date.to_iso8601(d)
** (ArgumentError) argument error
    (stdlib) :binary.copy("0", -1)
    (elixir) lib/calendar/iso.ex:566: Calendar.ISO.zero_pad/2
    (elixir) lib/calendar/iso.ex:402: Calendar.ISO.date_to_string/4
```

This exception happens because `Calendar.ISO.zero_pad` subtracts the length of the year from 4 in order to determine the number of additional `"0"`s to add in front of the year.  In this case, that number is `4 - 5 = -1`, and calling `:binary.copy("0", -1)` raises an exception.

```elixir
  defp zero_pad(val, count) when val >= 0 do
    num = Integer.to_string(val)
    :binary.copy("0", count - byte_size(num)) <> num
  end
```

https://github.com/elixir-lang/elixir/blob/v1.7/lib/elixir/lib/calendar/iso.ex#L556-L559

The [Elixir Date docs](https://hexdocs.pm/elixir/Date.html) do not mention any max value for years, so I assume a 5 digit year should be supported.  Ruby, for instance, supports a 5 digit year:

```rb
2.4.2 :006 > Date.new(20001, 12, 12).iso8601
 => "20001-12-12"
```

While it appears that `Date.new` considers 20001 to be an invalid date, we encountered this problem because there was a date value in our database of `20102-01-06` and Ecto (with the Postgres adapter) happily created a Date with this value.

```
iex(5)> Date.new(20001, 12, 12)
{:error, :invalid_date}
```

### Expected behavior

I would expect Date.to_iso8601() to be able to format a Date with year > 9999, e.g. `"20001-12-12"`.

**Comment by josevalim** [comment]
ISO 8601 does not support other years, unless agreed upfront, so I would
consider sticking to this limitation for now. Custom calendars can increase
this. Therefore we should update the docs here. We also need to check
Postgrex and make sure it handles those dates accordingly.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
To clarify my last message, the limitation will apply only to parsing. When printing, I think it should just work, as we assume the date was correctly created. Good call!
