### ISSUE TITLE
bits to byte/int convert issue

### ISSUE THREAD

**Issue by MiKDevIS** [elixir-lang/elixir#8369]
Hello,
I wanted to convert some bits to integer but elixir didn't work normally. please check this issue.
thanks,

iex(1)> <<00000000>>
<<0>>
iex(2)> <<00000010>>
"\n"
iex(3)> <<00000100>>
"d"
iex(4)> <<00001000>>
<<232>>
iex(5)> <<00010000>>
<<16>>
iex(6)> <<00100000>>
<<160>>
iex(7)> <<01000000>>
"@"
iex(8)> <<10000000>> 
<<128>>

**Comment by michalmuskala** [comment]
Please use the elixir forum or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
When filing an issue, please remember to fill in the provided issue template. Thank you.

---

The syntax for integers is explained in the getting started guides: https://elixir-lang.org/getting-started/basic-types.html#basic-arithmetic
