### ISSUE TITLE
Invalid spec for Logger.add_backend

### ISSUE THREAD

**Issue by pallix** [elixir-lang/elixir#8374]
The spec of `Logger.add_backend/1` seems invalid. The spec specify `atom` as argument but it is also possible to pass a `tuple`, as we can see in this [unit test](https://github.com/elixir-lang/elixir/blob/v1.7.3/lib/logger/test/logger_test.exs#L58).

**Comment by josevalim** [comment]
It seems to be correct in master: https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L587

And the handler is either atom or tuple: http://erlang.org/doc/man/gen_event.html

**Comment by pallix** [comment]
Oh ok, sorry!
