### ISSUE TITLE
Required validations are not returned by `Ecto.Changeset.validations/1`

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8380]
### Environment

* Elixir 1.7.3
* Ecto 3.0.1

### Current behavior

Given a changeset function with `validate_required` and `validate_format` calls, only the latter contibutes to the return value of `Ecto.Changeset.validations/1`.

For example:
```
defmodule Person do

  use Ecto.Schema

  import Ecto.Changeset

  schema "person" do
    field :name
    field :email
  end

  def changeset(person, params) do
    person
    |> cast(params, [:name, :email])
    |> validate_required([:name])
    |> validate_format(:email, ~r/@/)
  end
end

iex(2)> person = Person.changeset(%Person{}, %{})
#Ecto.Changeset<
  action: nil,
  changes: %{},
  errors: [name: {"can't be blank", [validation: :required]}],
  data: #Person<>,
  valid?: false
>
iex(3)> Ecto.Changeset.validations(person)
[email: {:format, ~r/@/}]
```

### Expected behavior

For completeness the `Ecto.Changeset.validations/1` should return all validations, which in the example above should be something like this
```
iex(3)> Ecto.Changeset.validations(person)
[name: :required, email: {:format, ~r/@/}]
```
or this
```
iex(3)> Ecto.Changeset.validations(person)
[name: {:required, true}, email: {:format, ~r/@/}]
```

**Comment by michalmuskala** [comment]
I believe this was opened in the wrong repo. Correct would be https://github.com/elixir-ecto/ecto.

Anyhow, the information about required fields is stored in the `.required` key of the changeset. It is public and can be accessed directly, unlike `.validations`, which require a function.

**Comment by mguimas** [comment]
Yeah, right, this was the wrong repo, sorry. But shouldn't it appear in the validations like all other validations, for consistency sake? I am asking this to check with you if it is worthwhile to open this issue in Ecto's repo. Thanks

**Comment by josevalim** [comment]
I have already added a note to Ecto docs, but I referred to the wrong issue number, because I did not notice it was the wrong repo: https://github.com/elixir-ecto/ecto/commit/8cf724bddd493152fc5caa0c0425fbe68dc21ff3

Ecto tracks this in a special field because we were used to handle required fields differently. Changing this is not worth the breaking change and/or duplication.

**Comment by mguimas** [comment]
I only opened this issue because instead of having to access two fields to process what validations are being done, one would only access just the function `Ecto.Changeset.validations/1`, making the code simpler and clear. But I understand your position of avoiding breaking changes. It's a matter of balancing pros & cons. Thanks.
