### ISSUE TITLE
Trailing commas, when on one line or in tuple, indicate mistake but are ignored

### ISSUE THREAD

**Issue by schnittchen** [elixir-lang/elixir#8390]
### Environment

```
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 20)
```

```
> lsb_release -d -r
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
```

### Current behavior

The following line compiled fine, but my code was broken and raised an exception. I was missing a pattern inside `, }` by mistake:

```
Enum.map(list, fn {{_, x}, } -> x end)
```

This behaviour probably happens because we want to support trailing commas in lists etc. (see https://github.com/elixir-lang/elixir/issues/479) for simple re-ordering. I am questioning the benefit here for two reasons:

* the list-ish thing (in this case the full tuple pattern) was all on one line
* tuples are ordered

### Expected behavior

I was expecting an error from the compiler, to what should look like a mistake.

### A few thoughts

I have no idea how hard this would be to restrict to lists and maps. There is already an exception for parameter lists, see https://github.com/elixir-lang/elixir/issues/7122) that suggests it could be feasible.

I also have no idea if it would be feasible for the parser to behave differently depending on whether the line continues after the comma or not. (it could be hard because the problem could cross processing steps during compilation).

Technically, both changes would be breaking, although the all-on-one-line case looks pretty obscure.

**Comment by josevalim** [comment]
We currently support trailing commas for all data structures and we don't plan to change it, as it would be a breaking change.

We don't support it for parameters though (it has been deprecated) because it would be inconsistent, as argless calls can't have trailing commas.
