### ISSUE TITLE
SemVer checking is overly strict

### ISSUE THREAD

**Issue by inferiorhumanorgans** [elixir-lang/elixir#8398]
### Environment

```
$ elixir --version
Erlang/OTP 19 [erts-8.3.5.6] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.7.4 (compiled with Erlang/OTP 19)
```

### Current behavior

Mix complains that `2018.1117.030911+2ae0126` is an invalid SemVer

### Expected behavior

Somewhat related to #4423 Version should validate as leading zeros are kosher per:

https://github.com/semver/semver/issues/112

**Comment by eksperimental** [comment]
Weird, because my Elixir version takes that string as valid.

```iex
Erlang/OTP 21 / Interactive Elixir (1.7.3)
iex(1)> Version.parse "2018.1117.1030911+2ae0126"
{:ok, #Version<2018.1117.1030911+2ae0126>}
```

Please copy the command and the error that you get

**Comment by inferiorhumanorgans** [comment]
Sorry, that's the one without the leading zero.  Correct problematic version is `2018.1117.030911+2ae0126`

**Comment by eksperimental** [comment]
Apparently it is not allowed in PATCH

https://semver.org/#spec-item-2
> A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and MUST NOT contain leading zeroes. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0.

**Comment by josevalim** [comment]
According to the spec, as @eksperimental said, those are not supported. IF you are the one generating those releases you can use the "day of year" as the third entry instead of the complete date.
