### ISSUE TITLE
ExUnit documentation is missing CSS on main site

### ISSUE THREAD

**Issue by jakub-gonet** [elixir-lang/elixir#8399]
As in title, check: https://hexdocs.pm/ex_unit/ExUnit.html

`GET https://hexdocs.pm/ex_unit/dist/app-4b38423804.css net::ERR_ABORTED 404`

**Comment by josevalim** [comment]
This is weird. This is an old deploy and suddenly the CSS images are missing. I will ping the Hex team: @ericmj and @wojtekmach.

**Comment by ericmj** [comment]
Thanks for the report. It seems to work after purging the CDN cache.
