### ISSUE TITLE
Broken links on https://elixir-lang.org/docs.html

### ISSUE THREAD

**Issue by cohawk** [elixir-lang/elixir#8400]
Heads up that on https://elixir-lang.org/docs.html there are many broken links to hexdocs for previous releases (Stable and Master work fine)

all of v1.7 give custom 404s:
https://hexdocs.pm/elixir/1.7.4/
https://hexdocs.pm/eex/1.7.4/
etc

spot checked a few other previous versions as well
https://hexdocs.pm/ex_unit/1.6.6/
https://hexdocs.pm/logger/1.5.3/Logger.html
https://hexdocs.pm/eex/1.4.5/

**Comment by ericmj** [comment]
We are currently rebuilding the docs. It will be fixed in a few minutes for the latest versions and in a few hours for older versions.
