### ISSUE TITLE
Enhance xref to detect undefined types

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#8405]
The xref compiler should be issuing warnings for undefined remote types to prevent obviously incorrect typespecs. This might require enhancing some other parts of the compiler to track types a module exports and depends on.

**Comment by josevalim** [comment]
Sorry, I didn't meant to say we should add this to xref. Adding this means we would need to store the types somehow into the module or add type specific callbacks to the compiler, which I really don't think we should. The alternative would be to parse beam files but that would make `xref` slower and compilation times are too important. Plus this work would be redundant to anyone who actually runs dialyzer.

My suggestion was that we could enable dialyzer to check types specificaly in the Elixir code base, but I am very against adding this to xref. :)
