### ISSUE TITLE
Confusing error message for BadFunctionError

### ISSUE THREAD

**Issue by devonestes** [elixir-lang/elixir#8406]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.3, Erlang 21.0
* Operating system: Ubuntu 18.04

### Current behavior

I'm seeing errors reported to our error catching service in production that look like this:
`(BadFunctionError) expected a function, got: #Function<5.105936317/1 in MyAppWeb.Users.Worker>`

This was pretty confusing because it's saying it expected a function and didn't get it, but it's showing that it got a function.

I'm not 100% sure that this is the case because I haven't actually fixed the bug yet, but I _think_ I'm seeing this because the reference to this anonymous function was passed from one node to another node, and that other node is running a different release than the node on which that function was originally created, so it can't find the correct function (we're running with Kubernetes, clustering with libcluster).

If this is the case, I think we might want a better error message telling folks what's going on here in case they can't figure out this distribution case for themselves and pointing them towards passing a `{M, F, A}` tuple instead of an anonymous function to prevent this issue (which I think is what's going to fix this).

### Expected behavior

A short description on how you expect the code to behave.

I think a better error might look something like:
`(BadFunctionError) `(BadFunctionError) expected an existing function, got: #Function<5.105936317/1 in MyAppWeb.Users.Worker> which could not be found` or something like that.

**Comment by josevalim** [comment]
Great find! I *think* we can fix this by adding a `is_function` check when building the message.

**Comment by josevalim** [comment]
Closing in favor of PR.
