### ISSUE TITLE
Mix tries to use use IPV6 when its not available.

### ISSUE THREAD

**Issue by JonRowe** [elixir-lang/elixir#8415]
### Environment

* Elixir 1.7.4 & Erlang/OTP 21
* Operating system: Amazon Linux 2018-1010

### Current behavior

Cannot access the internet with mix, e.g.

```
15:44:12.832 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'hello', 32, 'received SERVER ALERT: Fatal - Handshake Failure', 10]
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet6, [:inet6], :eaddrnotavail}, {:inet, [:inet], {:tls_alert, 'handshake failure'}}]}
 
Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.
```

### Expected behavior

Mix should use IPV4

**Comment by josevalim** [comment]
We have changed this in master and it should be out in the next release. :) Thanks for the report!

**Comment by JonRowe** [comment]
Changed what in master?

**Comment by JonRowe** [comment]
More details please this is a blocker for my current work.

**Comment by josevalim** [comment]
@JonRowe in master we no longer attempt to set ipv6. It is related to #8252.

You can fetch a Hex package by hand by doing this:

    https://repo.hex.pm/installs/[ELIXIR_VERSION]/hex-[HEX_VERSION].ez

In your case:

    https://repo.hex.pm/installs/1.7.0/hex-0.18.2.ez

Then you save it to your machine and you do:

    mix archive.install path/to/hex.ez

**Comment by JonRowe** [comment]
@josevalim Thanks for the reply, I also cannot do a `mix deps.get` due to this issue though, and this is a system I'm hoping to deploy this week. How can I backport these patches to 1.7 so I have a functional elixir setup?

**Comment by josevalim** [comment]
@JonRowe the fix I mentioned is not going to fix `mix deps.get`. Afaik, Hex does not set ipv6, only Mix does. So I am afraid this won't fix the issue you are seeing and your root cause is likely something else.

**Comment by josevalim** [comment]
What you can do to further debug issue is to open up `:httpc` in the production node and try to perform some requests and see what fails and what does not.

**Comment by JonRowe** [comment]
Yes I get that the hex workaround was only for hex, so I'm asking how I can get the ipv6 fix into 1.7.x

**Comment by josevalim** [comment]
@JonRowe that's what i am saying. `mix local.hex` was the only part where we forced ipv6. If there is something else failing due to ipv6, then it is either a general Erlang issue or OS issue, it is not about Elixir at all.

**Comment by JonRowe** [comment]
So erlang is forcing elixir to use the unavailable ipv6 configuration?

**Comment by josevalim** [comment]
I have not said that. :) I have said the issue needs to be investigated. :) It can be the OS, it can be Erlang, or something else.

**Comment by josevalim** [comment]
I would recommend you to use the ElixirForum or something similar to see if someone has run into this issue and see if they have ideas or feedback to share.
