### ISSUE TITLE
Excluding parts of code from formatter

### ISSUE THREAD

**Issue by lawik** [elixir-lang/elixir#8416]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.3 (compiled with Erlang/OTP 21)
* Operating system: OS X

### Current behavior

Brought this up on Slack to see if I was missing a way to exclude parts of code from the formatter. A friendly figure referred me here and let me know there was interest in samples of where the formatter can make code harder to maintain. I think this is a legitimate case.

I encountered this attempting to port some electronics library from python. So the formatting wasn't mine originally but I think the formatting is useful and clarifies the code with technical details.

Original:

```elixir
defmodule Sample do
<<
# Phase 0     Phase 1     Phase 2     Phase 3     Phase 4     Phase 5     Phase 6
# A B C D     A B C D     A B C D     A B C D     A B C D     A B C D     A B C D
0b01001000, 0b10100000, 0b00010000, 0b00010000, 0b00010011, 0b00000000, 0b00000000,  # LUT0 - Black
0b01001000, 0b10100000, 0b10000000, 0b00000000, 0b00000011, 0b00000000, 0b00000000,  # LUTT1 - White
>>
end
```

Formatted it gives me:

```elixir
defmodule Sample do
  <<
    # Phase 0     Phase 1     Phase 2     Phase 3     Phase 4     Phase 5     Phase 6
    # A B C D     A B C D     A B C D     A B C D     A B C D     A B C D     A B C D
    # LUT0 - Black
    0b01001000,
    0b10100000,
    0b00010000,
    0b00010000,
    0b00010011,
    0b00000000,
    0b00000000,
    # LUTT1 - White
    0b01001000,
    0b10100000,
    0b10000000,
    0b00000000,
    0b00000011,
    0b00000000,
    0b00000000
  >>
end

```
### Expected behavior

It would be incredibly convenient to be able to tell the formatter to skip this part. I could probably find another way to format it. But with this reformat it gets significantly less dense. I've cut several lines off of this data for a smaller sample.

**Comment by josevalim** [comment]
We know this is a desired feature but having discussions about this is extremely hard because the discussion is often derailed, many focus only on personal preferences without listening to others, people ask the formatter to be removed, etc. So I recommend reading previous discussions on the topic and do a complete proposal because I personally don't have the energy to shepherd the process again.

My preference would be to have a special comment that annotates exactly how the data should be formatted and the formatter will do the formatting for you. I recommend reading the previous discussions and formatting a proposal to be sent to the mailing list.

Thank you.

**Comment by josevalim** [comment]
Oh, meanwhile, you can move those tables to a separate file and have it excluded from the formatter. Again, I know it is not ideal, but it is the best we can do for now.

**Comment by lawik** [comment]
Thanks for the consideration. I know formatter discussions have been all over the place. I'll probably just exclude the single file then. Sorry to poke a sore spot.

**Comment by bmarkons** [comment]
Hi, I ended up on this issue while trying to figure out how to exclude subdirectory from formatter. 

Can anyone here help me figure this out?

I came up only with this solution so far: http://blog.enazarov.ru/2020/07/elixir-mix-do-not-format-my-file.html

Is there any other way?

Thanks 🙇
