### ISSUE TITLE
Allow formatter to keep newlines in chains of `++` calls

### ISSUE THREAD

**Issue by devonestes** [elixir-lang/elixir#8417]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)

* Operating system: Linux Mint 19

### Current behavior

We have the following function in the Benchee CSV formatter:

```elixir
  @doc false
  def to_csv(%Scenario{
        name: name,
        input_name: input_name,
        memory_usage_statistics: memory_usage_statistics,
        run_time_statistics: run_time_statistics
      }) do
    [name, input_name] ++
      to_csv(:run_time, run_time_statistics) ++ to_csv(:memory, memory_usage_statistics)
  end
```

I would like to be able to format that as:

```elixir
  @doc false
  def to_csv(%Scenario{
        name: name,
        input_name: input_name,
        memory_usage_statistics: memory_usage_statistics,
        run_time_statistics: run_time_statistics
      }) do
    [name, input_name] ++
      to_csv(:run_time, run_time_statistics) ++
      to_csv(:memory, memory_usage_statistics)
  end
```

but the formatter doesn't allow `to_csv(:run_time, run_time_statistics) ++ to_csv(:memory, memory_usage_statistics)` to be split on two lines.

### Expected behavior

It seems to me that since the formatter is so good with respecting user preferences for newlines that this would also be the case here. I looked for previous discussion about `++` specifically, but the closest I could find was #6977 which seems to suggest that the formatter should keep the newline since it's a function call, but this is a "special" function call, so there may be additional rules and reasons for not allowing the newline here.

**Comment by josevalim** [comment]
Yes, I have been annoyed by this too. I also think it looks weird because of the associativity. If you use `+`, then it formats to:

```elixir
@doc false
def to_csv(%Scenario{
      name: name,
      input_name: input_name,
      memory_usage_statistics: memory_usage_statistics,
      run_time_statistics: run_time_statistics
    }) do
  [name, input_name] + to_csv(:run_time, run_time_statistics) +
    to_csv(:memory, memory_usage_statistics)
end
```

which is slightly less awkward. But yes, I think always respecting newlines after operators is good.
