### ISSUE TITLE
IEx doc header broken for `fn/1`

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#8428]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): master
* Operating system: macOS Mojave

### Current behavior

<img width="740" alt="screenshot 2018-11-26 at 12 04 21" src="https://user-images.githubusercontent.com/76071/49010426-8635b580-f173-11e8-9fd3-7ab6d41b106e.png">

**Comment by Hanspagh** [comment]
Investigated this a bit and I think its caused by `Code.fetch_docs` returning

` {{:macro, :fn, 1}, 1442, ["fn\n  [clauses]\nend"],
    %{
      "en" => "Defines an anonymous function.\n\n## Examples\n\n    iex> add = fn a, b -> a + b end\n    iex> add.(1, 2)\n    3\n\nAnonymous functions can also have multiple clauses. All clauses\nshould expect the same number of arguments:\n\n    iex> negate = fn\n    ...>   true -> false\n    ...>   false -> true\n    ...> end\n    iex> negate.(false)\n    true\n\n"
    }, %{}},`

**Comment by josevalim** [comment]
Yeah, the issue is that we store in the Docs chunk the result of `Macro.to_string` but we should probably skip the `Macro.to_string` call for `Kernel.SpecialForms.fn` as we can't actually format it properly. It is not a valid AST, so we have to special case (or define a fake-ish AST, such as `fn ... -> ... end`.

**Comment by Hanspagh** [comment]
I would love to fix this, but I am not quite sure where the `Macro.to_string` happens. So far I got to the understanding that `code.fetch` uses `:code.get_object_code(module)` to get the docs

**Comment by josevalim** [comment]
@Hanspagh we probably just need a new clause around here: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/src/elixir_erl.erl#L531-L540

You can see other special forms are already special cased. :)

**Comment by Hanspagh** [comment]
Thanks. Giving it a try
