### ISSUE TITLE
Provide port/1,2 helpers in IEx

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#8437]
Those should be similar to the `pid` and `ref` helpers but work for ports instead. It should be possible to use the `:erlang.list_to_port/1` function to do this.

**Comment by axelson** [comment]
Just wanted to note the current workaround for this from the Elixir Forum thread for anyone that comes across this issue and wants to know how to do this without a helper function

```
iex> :erlang.list_to_port('#Port<0.7>')
#Port<0.7>
```
