### ISSUE TITLE
Opaque MapSet type causes Dialyzer error

### ISSUE THREAD

**Issue by 1player** [elixir-lang/elixir#8463]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating system: macOS 10.13.6

### Current behavior

```
def public_field?(field, %MapSet{} = public_fields), do: MapSet.member?(public_fields, field)
```

gives Dialyzer error `The call 'Elixir.MapSet':'member?'(_public_fields@1::#{'__struct__':='Elixir.MapSet', _=>_},_field@1::any()) does not have an opaque term of type 'Elixir.MapSet':t(_) as 1st argument`

### Expected behavior

Dialyzer not to give any error.

Similar to https://github.com/elixir-ecto/ecto/issues/2693, fixed by making the type not opaque.

**Comment by josevalim** [comment]
Closing in favor of #8480.
