### ISSUE TITLE
Restricted shell in `iex`

### ISSUE THREAD

**Issue by paulperegud** [elixir-lang/elixir#8481]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.7.3 (compiled with Erlang/OTP 21)
```
* Operating system: Ubuntu 18.04 LTS

### Current behavior
```
$ iex --erl "-stdlib restricted_shell shell"
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :application.get_env(:stdlib, :restricted_shell) 
{:ok, :shell}
iex(2)> 
```

While erl accepts shell.erl as a proper restricted_shell:
```
$ erl -stdlib restricted_shell shell
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Restricted Eshell V10.1  (abort with ^G)
1> application:get_env(stdlib, restricted_shell).
** exception exit: restricted shell does not allow application:get_env(stdlib,restricted_shell)
2>
``` 

### Expected behavior

According to this post https://elixirforum.com/t/restricted-shell-in-elixir/17753 restricted shell was at least working some time ago. What is the status? Is it a bug or lack of a feature?

**Comment by josevalim** [comment]
I don't think the restricted shell ever worked in Elixir. You can pass the options, but did they ever had an effect?

So it is rather a feature that does not exist as we would have to implement it specifically for Elixir. If developers are interested on this feature, than I recommend drafting and submitting a complete proposal to the mailing list.
