### ISSUE TITLE
Provide more hints for UndefinedFunctionError in case there is a behaviour

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#8513]
If there's a behaviour declared on a module that expects a particular function and we get an `UndefinedFunctionError` on that function - the `blame` callback should add information about this.

The information about behaviours is available in the return of the `module_info/1` function and the information about callbacks of a particular behaviour is available in the return of the `behaviour_info/1` function.

**Comment by dnsbty** [comment]
I would love to help with this one if no one has picked it up by this afternoon.

**Comment by michalmuskala** [comment]
Please, go ahead 🙂

**Comment by dnsbty** [comment]
Any ideas on what those hints should actually say? I think I've got some basic ideas on this so I'll try to get a first pass on a PR up in a couple minutes

**Comment by josevalim** [comment]
I am really not sure what is the benefit here. We already warn it at
compile time, so why do we need an extra information on runtime? It can
even be confusing. What if we missing function is not in a module that I
own? So what is the use case here? :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Closing in favor of #8517

**Comment by josevalim** [comment]
Thanks for expanding @michalmuskala !
