### ISSUE TITLE
Reuse Erlang's `logger` metadata to Elixir's `Logger`

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#8515]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
  ```
  Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

  Elixir 1.7.3 (compiled with Erlang/OTP 21)
  ```
* Operating system: any

### Current behavior

```
:logger.set_process_metadata(%{foo: "bar"})

refute Keyword.has_key?(Logger.metadata(), :foo)
```

### Expected behavior

```
:logger.set_process_metadata(%{foo: "bar"})

assert Keyword.has_key?(Logger.metadata(), :foo)
```

**Comment by josevalim** [comment]
There is unfortunately no way we can make this work, so I don't think that will happen. Those are different logger systems, so it is expected they have their own metadata, although the metadata you set in Elixir should be available to everything logged by any.

**Comment by michalmuskala** [comment]
The two systems are separate - each metadata is used when using the appropriate logging mechanism. In particular, it's not clear how that should work. What if the keys overlap? Should one override the other? What should be the result of the following sequence:

```elixir
:logger.set_process_metadata(%{foo: "bar"})
Logger.metadata(foo: "baz")
Logger.metadata()
```

And this one?

```elixir
Logger.metadata(foo: "baz")
:logger.set_process_metadata(%{foo: "bar"})
Logger.metadata()
```

If they should be different - how would this be even implemented?

**Comment by hauleth** [comment]
@michalmuskala IMHO the latter should win. So in first case there would be `[foo: "baz"]` and in second `[foo: "bar"]`. In general having 2 completely separate "official" logging systems is a little bit confusing.

**Comment by michalmuskala** [comment]
I would agree it would be the best to make "later wins" scenario here. Unfortunately, I can't imagine a way to implement it efficiently.

We always had 2 logging systems - before it was `Logger` and `:error_logger`. Now there's a third one `:logger`.

**Comment by hauleth** [comment]
@michalmuskala one possible solution is to ditch `Logger.metadata` process store and instead use only `:logger` one.

`:error_logger` was less problematic when integrating because it was very limited in it's scope. Also `:error_logger` is deprecated and probably will be removed in future.

I see 2 solutions for the current dichotomy (without breaking changes):

- rewrite `:console` output to use Erlang's `:logger` instead
- rewrite `Logger` module to use Erlang's `:logger` internally and create wrapper that will allow using Elixir-style `Logger` outputs

I didn't dig deep into `Logger` but both options seems possible.

**Comment by josevalim** [comment]
> I see 2 solutions for the current dichotomy (without breaking changes)

I am afraid none of those options are as doable as it sounds without breaking changes. I definitely recommend to dig deeper as there are many nuances to consider, even on simple things like: Erlang uses :mfa as metadata and Elixir uses two separate keys (:module and :function).

A simple solution of unifying those means either a breaking change or having both (which means you get duplicate entries in your logs when using `metadata: :all`).

We also need to consider they have different levels and we still need to continue supporting custom backends.

**Comment by hauleth** [comment]
@josevalim I have idea how to achieve that. I will prepare PR and I will see if that is so crazy.

**Comment by josevalim** [comment]
Ok, just keep in mind though we can't do any of this stuff now while we support OTP 20 too. So even if we have something working today, we would probably need to wait a year (at least until Elixir 1.10) alongside the other entries in here #6611.

**Comment by hauleth** [comment]
@josevalim yes, I am fully aware of that.
