### ISSUE TITLE
[EEx] issue with case generating incorrect code.

### ISSUE THREAD

**Issue by nunocf** [elixir-lang/elixir#8521]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  elixir 1.6.6/OTP 21

* Operating system: 
MacOS Mojave 10.14.2
We also see this issue in our linux servers

### Current behavior

this piece of code 
```
<div class="claimContentDescription">
            <p class="claimContentDescriptionText">
                <%= case @unsubscribed do %>
                    <% :yes -> %>
                        <div><%= @copy["success"] %></div>
                    <% :no -> %>
                        <div><%= @copy["description"] %></div>
                        <form id="unsubscribe" action="../unsubscribe" method="POST">
                            <input type="hidden" name="_csrf_token" value="<%= get_csrf_token() %>">
                            <input type="hidden" name="order_id" value="<%= @order_id %>">
                            <div class="claimPlatformViewCTA">
                                <input type="submit" class="claimBtnDefault claimBtn" value="<%= @copy["cta"] %>">
                            </div>
                        </form>
                    <% :error -> %>
                        <div><%= @copy["error"] %></div>
                <% end %>
            </p>
          </div>
```
Generated this section of HTML

![image](https://user-images.githubusercontent.com/22882922/50011203-5f6ce100-ffb3-11e8-8dab-79d7e53e5a12.png)

Pay attention to the empty `<p>`s.

**The issue:**
The initial problem is that the text is not formatted. The cause for it is that the `<p>` that contains the class `claimContentDescriptionText` is not being populated. Instead, it's supposed inner div is being created at the same level (not as a child element). The fix on our side is quite simple, just move the CSS class into the div on the `:yes` and `:no` matches, but it feels like a fever pill more than a solution.

### Expected behavior

I'd expect the code to be generated to look similar to this:
```
<div class="claimContentDescription">
    <p class="claimContentDescriptionText">
        <div>You have been successfully unsubscribed.</div>
    </p>
 </div>
```

**Comment by josevalim** [comment]
That’s your browser inserting it. You can’t have a div inside a paragraph,
so the browser assumes it is an error, closes the paragraph, inserts the
div, and then open up another paragraph to match your closing one.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by nunocf** [comment]
Thank you so much for the answer, @josevalim, Obrigado pela ajuda!

I'm absolutely astonished by Elixir's power. I can say I haven't had this much fun developing software since I learned about programming when I was a teenager.

Abraço de Portugal
