### ISSUE TITLE
Improve Protocol.UndefinedError message when passing the module name of a struct

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#8532]
### Current behavior

```elixir
%{a: 1, b: 2} |> Map.keys |> Enum.into(MapSet)
** (Protocol.UndefinedError) protocol Collectable not implemented for MapSet. This protocol is implemented for: BitString, Ecto.Adapters.SQL.Stream, File.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Plug.Conn, Postgrex.Stream
    (elixir) lib/collectable.ex:1: Collectable.impl_for!/1
    (elixir) lib/collectable.ex:77: Collectable.into/1
    (elixir) lib/enum.ex:1193: Enum.into_protocol/2
```

### Expected behavior

 The `MapSet` used here is a module name, which is why the call fails. 
However, in the list of implementations, it is listed, just as module name.
Can we improve this error message?

**Comment by josevalim** [comment]
We could probably say: "protocol Collectable not implemented for MapSet, which is an Atom."

Thoughts?

**Comment by michalmuskala** [comment]
What about "for value MapSet of type Atom,.... Implemented for types A, B, C"

**Comment by adkron** [comment]
“For the Atom, MapSet, ... implemented for ...”

Amos King
Binary Noggin

**Comment by josevalim** [comment]
:+1: to @michalmuskala suggestion.

**Comment by Qqwy** [comment]
I like @michalmuskala 's suggestion the most as well; I think it is the most clear to beginners.

**Comment by josevalim** [comment]
Closing in favor of the PR!
