### ISSUE TITLE
scoping compiler bug on cond

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#8542]
### Environment
OTP 21.2
Elixir 1.7.3

```elixir
defmodule Test do
    def handle_ms(ms) do
        Map.put(ms, 5, 5)
    end

    def test() do
        ms = %{}
        ms_new = cond do
            true ->
                ms = Map.put(ms, :wtf, 5)
                handle_ms(ms)
        end
        {ms, ms_new}
    end
end

1> Test.test
{%{wtf: 5}, %{5 => 5, :wtf => 5}}
```

Its clear the evaluation of this is incorrect and should be {%{}, %{5 => 5, :wtf => 5}}

**Comment by michalmuskala** [comment]
It looks like this is a bug in the compiler related to "flattening" of a `cond` with just one branch. A `cond` with two branches is compiled correctly.

**Comment by vans163** [comment]
Not exactly

```
defmodule Test do
    def handle_ms(ms) do
        Map.put(ms, 5, 5)
    end

    def test(s\\%{ms: %{test: true}}) do
        ms = s.ms
        ms_new = cond do
            ms[:test] == true ->
                junk = 4
                ms = Map.put(ms, :wtfa, 5)
                handle_ms(ms)
            true -> 
                ms = Map.put(ms, :wtfa, 5)
                handle_ms(ms)
        end
        {ms, ms_new}
    end
end
1> Test.test
{%{test: true}, %{5 => 5, :test => true, :wtfa => 5}}
```

**Comment by michalmuskala** [comment]
In versions before 1.7 the behaviour you saw would be expected. It was a long-standing scoping compatibility with pre-1.0 code. This code would compile, but would issue a warning. The compatibility was dropped in 1.7, because otherwise we wouldn't be able to fix some other bugs in the compiler.

**Comment by josevalim** [comment]
Closing in favor of #8544.
