### ISSUE TITLE
[PROPOSAL] Hint to add :ex_doc dependency when running `mix docs` and docs task not present

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8554]
When running `mix docs` in a project with no docs task, we should special case and 
give a suggestion saying:

*************
If you want to build the docs for this project, you need to add ex_doc as your dependency,
please add `{:ex_doc, only: :dev, runtime: false},` to your deps/0 functions in your mix.exs file,
so it looks like this:

>   defp deps do
>     [
>       {:ex_doc, only: :dev, runtime: false},
>     ]
>   end
> 

and run `mix deps.get` and `mix docs`

*************

before working on a PR, I would like to know if there's interest in such a feature

**Comment by josevalim** [comment]
Could you please move it to the mailing list? Thank you.
