### ISSUE TITLE
System.version/0 returns "1.8.0" in Elixir 1.8.0-rc.0

### ISSUE THREAD

**Issue by ejpcmac** [elixir-lang/elixir#8566]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

    ```
    Erlang/OTP 20 [erts-9.3.3.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

    Elixir 1.8.0 (compiled with Erlang/OTP 20)
    ```

* Operating system: macOS 10.13.6

### Current behavior

```elixir
iex(1)> System.version
"1.8.0"
```

### Expected behavior

```elixir
iex(1)> System.version
"1.8.0-rc.0"
```

IIRC, past Elixir RCs did show their correct version number. It is not the case with Elixir 1.8.0-rc.0 and it can be confusing. Note the error is also there for `elixir --version`.

**Comment by josevalim** [comment]
Good catch, thanks, fixed here: https://github.com/elixir-lang/elixir/commit/e284007968586c5422bb7f1ff21808bfcaa6ecfc
