### ISSUE TITLE
1.8.0-rc.0 record specification errors are unclear and/or broken

### ISSUE THREAD

**Issue by whitfin** [elixir-lang/elixir#8571]
### Environment

* Elixir & Erlang/OTP versions: Elixir 1.8.0 (compiled with Erlang/OTP 20)
* Operating system: macOS High Sierra

### Explanation

This is a cross-post from https://github.com/whitfin/cachex/issues/203, which reports a compilation failure in `1.8.0-rc.0` due to the following:

```
invalid record specification, expected the record name to be an atom
```

In essence, there's a `@type record` declaration in the file [here](https://github.com/whitfin/cachex/blob/master/lib/cachex/spec/validator.ex#L14), and somehow Elixir is picking that up (I guess due to the name) and trying to enforce some rules on it. My expectation is that this should be perfectly fine, as there's nothing about this in the official documentation being this being reserved, etc. 

Before changing this on my end, I'd like some official clarification on the stance here as this appears to be a (at the very least) an annoyance in terms of backwards compatibility. To go from compiling to failing to compile is a pretty bad change on a non-major version bump, so I'm not sure whether this is a compiler bug or just something not well documented.

**Comment by sneako** [comment]
Hi @whitfin! I also ran in to this issue compiling one of my projects that uses Cachex, and opened this issue https://github.com/elixir-lang/elixir/issues/8564. It should be fixed in master now (https://github.com/elixir-lang/elixir/pull/8569)

**Comment by whitfin** [comment]
@sneako well, I guess I should have looked harder then :p thanks for the info! I'll link that issue back on the Cachex ticket.
