### ISSUE TITLE
Compilation failure on 1.8.0-rc.0

### ISSUE THREAD

**Issue by jfornoff** [elixir-lang/elixir#8585]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.8.0-rc.0 / 21.1.1 and 21.2.2
* Operating system: MacOS

### Current behavior

Compilation failure with attached stacktrace, seems to occur multiple times.

> 15:34:15.868 [error] GenServer #PID<0.12458.0> terminating
** (stop) {:compile_forms, {:error, [{[], [{:none, :compile, {:crash, :sys_core_fold, {{:case_clause, {:EXIT, {:function_clause, [{:sys_core_fold, :module, [[{:attribute, 1, :file, {'lib/tracing/adapter/noop.ex', 1}}, {:attribute, 1, :module, Tracing.Adapter.Noop_meck_original}, {:attribute, 1, :compile, [:no_auto_import]}, {:attribute, 1, :behaviour, Tracing.Adapter}, {:attribute, 1, :export, [__info__: 1, finish_span: 1, get_ids: 1, get_name: 1, log: 2, start_span: 1, start_span: 2, tag: 3]}, {:attribute, 1, :spec, {{:__info__, 1}, [{:type, 1, :fun, [{:type, 1, :product, [{:type, ...}]}, {:type, 1, :any, []}]}]}}, {:function, 0, :__info__, 1, [{:clause, 0, [{:atom, 0, :module}], [], [{:atom, 0, Tracing.Adapter.Noop}]}, {:clause, 0, [{:atom, 0, :functions}], [], [{:cons, 0, {:tuple, ...}, {...}}]}, {:clause, 0, [{:atom, 0, :macros}], [], [nil: 0]}, {:clause, 0, [{:match, 0, {:var, ...}, {...}}], [], [{:call, 0, ...}]}, {:clause, 0, [{:match, 0, {...}, ...}], [], [{:call, ...}]}, {:clause, 0, [{:match, 0, ...}], [], [{...}]}, {:clause, 0, [{:atom, ...}], [], [...]}]}, {:function, 61, :add_option, 3, [{:clause, 61, [{:match, 61, {:tuple, 61, [...]}, {:var, 61, ...}}, {:var, 61, :_key@1}, {:var, 61, :_value@1}], [], [{:match, 62, {:var, ...}, {...}}, {:call, 64, {...}, ...}]}]}, {:function, 47, :finish_span, 1, [{:clause, 47, [{:var, 47, :__span@1}], [], [{:atom, 0, :ok}]}]}, {:function, 40, :generate_id, 0, [{:clause, 40, [], [], [{:match, 41, ...}, {:var, ...}]}]}, {:function, 50, :get_ids, 1, [{:clause, 50, [{:tuple, 50, [...]}], [], [{:call, ...}]}]}, {:function, 53, :get_name, 1, [{:clause, 53, [{:tuple, 53, ...}], [], [{...}]}]}, {:function, 56, :log, 2, [{:clause, 56, [{:var, ...}, {...}], [], [...]}]}, {:function, 30, :resolve_parent, 1, [{:clause, 30, [{...}], [...], ...}, {:clause, 32, [...], ...}, {:clause, 38, ...}]}, {:function, 7, :start_span, 1, [{:clause, 7, [...], ...}]}, {:function, 7, :start_span, 2, [{:clause, 7, ...}]}, {:function, 59, :tag, 3, [{:clause, ...}]}, {:function, 11, :transform_options, 1, [{...}]}], [:binary, :return_errors, :debug_info, :dialyzer, :no_spawn_compiler_process, :from_core, :no_auto_import]], [file: 'sys_core_fold.erl', line: 109]}, {:compile, :"-select_passes/2-anonymous-2-", 3, [file: 'compile.erl', line: 585]}, {:compile, :"-internal_comp/5-anonymous-1-", 3, [file: 'compile.erl', line: 349]}, {:compile, :fold_comp, 4, [file: 'compile.erl', line: 376]}, {:compile, :internal_comp, 5, [file: 'compile.erl', line: 360]}, {:compile, :"-do_compile/2-anonymous-0-", 2, [file: 'compile.erl', line: 177]}, {:meck_code, :compile_and_load_forms, 2, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_code.erl', line: 71]}, {:meck_proc, :backup_original, 4, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_proc.erl', line: 373]}, {:meck_proc, :init, 1, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_proc.erl', line: 212]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}, [{:compile, :"-select_passes/2-anonymous-2-", 3, [file: 'compile.erl', line: 585]}, {:compile, :"-internal_comp/5-anonymous-1-", 3, [file: 'compile.erl', line: 349]}, {:compile, :fold_comp, 4, [file: 'compile.erl', line: 376]}, {:compile, :internal_comp, 5, [file: 'compile.erl', line: 360]}, {:compile, :"-do_compile/2-anonymous-0-", 2, [file: 'compile.erl', line: 177]}, {:meck_code, :compile_and_load_forms, 2, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_code.erl', line: 71]}, {:meck_proc, :backup_original, 4, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_proc.erl', line: 373]}, {:meck_proc, :init, 1, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_proc.erl', line: 212]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}]}], []}}
Last message: {:EXIT, #PID<0.90.0>, {:compile_forms, {:error, [{[], [{:none, :compile, {:crash, :sys_core_fold, {{:case_clause, {:EXIT, {:function_clause, [{:sys_core_fold, :module, [[{:attribute, 1, :file, {'lib/tracing/adapter/noop.ex', 1}}, {:attribute, 1, :module, Tracing.Adapter.Noop_meck_original}, {:attribute, 1, :compile, [:no_auto_import]}, {:attribute, 1, :behaviour, Tracing.Adapter}, {:attribute, 1, :export, [__info__: 1, finish_span: 1, get_ids: 1, get_name: 1, log: 2, start_span: 1, start_span: 2, tag: 3]}, {:attribute, 1, :spec, {{:__info__, 1}, [{:type, 1, :fun, [{:type, 1, :product, ...}, {:type, 1, ...}]}]}}, {:function, 0, :__info__, 1, [{:clause, 0, [{:atom, 0, :module}], [], [{:atom, 0, ...}]}, {:clause, 0, [{:atom, 0, :functions}], [], [{:cons, ...}]}, {:clause, 0, [{:atom, 0, ...}], [], [nil: 0]}, {:clause, 0, [{:match, ...}], [], [...]}, {:clause, 0, [{...}], [], ...}, {:clause, 0, [...], ...}, {:clause, 0, ...}]}, {:function, 61, :add_option, 3, [{:clause, 61, [{:match, 61, {...}, ...}, {:var, 61, ...}, {:var, ...}], [], [{:match, ...}, {...}]}]}, {:function, 47, :finish_span, 1, [{:clause, 47, [{:var, 47, ...}], [], [{...}]}]}, {:function, 40, :generate_id, 0, [{:clause, 40, [], [], [...]}]}, {:function, 50, :get_ids, 1, [{:clause, 50, [{...}], [], ...}]}, {:function, 53, :get_name, 1, [{:clause, 53, [...], ...}]}, {:function, 56, :log, 2, [{:clause, 56, ...}]}, {:function, 30, :resolve_parent, 1, [{:clause, ...}, {...}, ...]}, {:function, 7, :start_span, 1, [{...}]}, {:function, 7, :start_span, 2, [...]}, {:function, 59, :tag, 3, ...}, {:function, 11, :transform_options, ...}], [:binary, :return_errors, :debug_info, :dialyzer, :no_spawn_compiler_process, :from_core, :no_auto_import]], [file: 'sys_core_fold.erl', line: 109]}, {:compile, :"-select_passes/2-anonymous-2-", 3, [file: 'compile.erl', line: 585]}, {:compile, :"-internal_comp/5-anonymous-1-", 3, [file: 'compile.erl', line: 349]}, {:compile, :fold_comp, 4, [file: 'compile.erl', line: 376]}, {:compile, :internal_comp, 5, [file: 'compile.erl', line: 360]}, {:compile, :"-do_compile/2-anonymous-0-", 2, [file: 'compile.erl', line: 177]}, {:meck_code, :compile_and_load_forms, 2, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_code.erl', line: 71]}, {:meck_proc, :backup_original, 4, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_proc.erl', line: 373]}, {:meck_proc, :init, 1, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_proc.erl', line: 212]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}, [{:compile, :"-select_passes/2-anonymous-2-", 3, [file: 'compile.erl', line: 585]}, {:compile, :"-internal_comp/5-anonymous-1-", 3, [file: 'compile.erl', line: 349]}, {:compile, :fold_comp, 4, [file: 'compile.erl', line: 376]}, {:compile, :internal_comp, 5, [file: 'compile.erl', line: 360]}, {:compile, :"-do_compile/2-anonymous-0-", 2, [file: 'compile.erl', line: 177]}, {:meck_code, :compile_and_load_forms, 2, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_code.erl', line: 71]}, {:meck_proc, :backup_original, 4, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_proc.erl', line: 373]}, {:meck_proc, :init, 1, [file: '/Users/jfornoff/workspace/project/backend/deps/meck/src/meck_proc.erl', line: 212]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}}]}], []}}}

Hope this information is sufficient to get an idea of what is going wrong, please let me know if there is any additional info that I can provide to help!

**Comment by josevalim** [comment]
Thanks for the report! This is an issue in meck which a pull request has been provided here: https://github.com/eproxus/meck/pull/202
