### ISSUE TITLE
PIDPartition grows on :already_registered errors from Registry.register

### ISSUE THREAD

**Issue by fhunleth** [elixir-lang/elixir#8611]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.4, Erlang 21
* Operating system: Linux

### Current behavior

If I run the following and watch the size of the ETS UniqueTest.PIDPartition0 table, it'll grow a row on every call to `register` even though all but the first one return an error.
```
iex(3)> Registry.start_link(keys: :unique, name: UniqueTest)
{:ok, #PID<0.128.0>}
iex(4)> Registry.register(UniqueTest, "hello", [])
{:ok, #PID<0.129.0>}
iex(5)> Registry.register(UniqueTest, "hello", [])
{:error, {:already_registered, #PID<0.107.0>}}
iex(6)> Registry.register(UniqueTest, "hello", [])
{:error, {:already_registered, #PID<0.107.0>}}
iex(7)> Registry.register(UniqueTest, "hello", [])
{:error, {:already_registered, #PID<0.107.0>}}
iex(8)> :ets.i()
 id              name              type  size   mem      owner
 ----------------------------------------------------------------------------
 #Ref<0.3405087786.1607073797.255116> 'Elixir.UniqueTest.KeyPartition0' set   1      1340     'Elixir.UniqueTest.PIDPartition0'
 #Ref<0.3405087786.1607073797.255117> 'Elixir.UniqueTest.PIDPartition0' duplicate_bag 4      1392     'Elixir.UniqueTest.PIDPartition0'
```

It looks like this behavior is intentional since the `:already_registered` error case is called out here: https://github.com/elixir-lang/elixir/blob/v1.7.4/lib/elixir/lib/registry.ex#L895. 

I'd like to keep PIDPartition from growing since it got quite large on a long running system. The code that blindly calls `Registry.register` is unfortunately not too smart and it's hard to make it know beforehand whether it has already registered a key or not. Calling `Registry.unregister` on `:already_registered` errors cleans up too much so I can't do that.

### Expected behavior

The ETS PIDPartition doesn't grow unbounded on `:already_registered` errors.

Sadly, simply adding `:ets.delete_object` on this error case didn't work since it deletes all matching rows (the table is a duplicate_bag).

**Comment by josevalim** [comment]
@fhunleth good catch! My suggestion is to use do generate a unique integer and add it as fourth element to the tuple added to the PIDs table. This way you can uniquely delete it. If you would like to send a PR, it would be very welcome, otherwise we will include a fix later. :)

**Comment by michalmuskala** [comment]
We should be able to insert to the pid table with `insert_new` and use the return value to decide if we should delete back from it on already registered error.

**Comment by josevalim** [comment]
@michalmuskala you are right. Since we can only register from self and if self is already registered with that key, then it is absolutely clear we have already registered ourselves. :+1:

**Comment by adkron** [comment]
Why not invert the logic in `register_key(:duplicate...)`? Instead of inserting and then looking up if that fails would it be better to lookup and insert only when needed?

~~~elixir
  defp register_key(:unique, pid_server, key_ets, key, entry) do
    case :ets.lookup(key_ets, key) do
      [{^key, {pid, _}} = current] ->
        if Process.alive?(pid) do
          {:error, {:already_registered, pid}}
        else
          # Notice we have to call register_key recursively
          # because we are always at odds of a race condition.
          :ets.delete_object(key_ets, current)
          register_key(:unique, pid_server, key_ets, key, entry)
        end

      [] ->
        :ets.insert_new(key_ets, entry)
        {:ok, pid_server}
    end
  end

~~~

**Comment by josevalim** [comment]
@adkron we have two tables in the registry, the issue is in the pid table (`pid_ets`), not the key one (`key_ets`). I also did this same mistake in my initial look :D

The other issue is that your code has a race, because two processes can lookup the table, see the table is empty, then proceed to call `insert_new`, and only one of them would win, but both would get `:ok`. So the reason why we do `insert_new` first is because it is atomic.

**Comment by fhunleth** [comment]
Thanks for all of the quick responses. I did not expect that.

I did make an attempt at a PR at https://github.com/elixir-lang/elixir/pull/8616. I'll be honest that I don't see the race condition on insertion since `self()` is part of the tuple being inserted. I.e. if two processes lookup the table and call register, their `self()`'s would be different, so `insert_new` would work for both of them. Or does some other code I'm not seeing insert from another process with an arbitrary pid? 

I do feel uneasy about my solution on the delete, since I didn't see a way in ets to just delete one entry with a `duplicate_bag`. Therefore, I deleted everything and added the one entry back. Of course, that leaves the table momentarily without an entry that it should have. I'm hopeful someone knows a better way or knows what the ramifications are of this.

**Comment by josevalim** [comment]
> Therefore I think the best fix is to use a unique integer. So you would insert it like this:

Doh, ignore me. @michalmuskala fix is correct because we always clean up all entries when we return already registered because another process registered it.

To be super clear, here is what I think should be the fix:

```diff
diff --git a/lib/elixir/lib/registry.ex b/lib/elixir/lib/registry.ex
index 3d23f72f0..2e739d933 100644
--- a/lib/elixir/lib/registry.ex
+++ b/lib/elixir/lib/registry.ex
@@ -911,26 +911,37 @@ defmodule Registry do
     # always be able to do the cleanup. If we register first to the
     # key one and the process crashes, the key will stay there forever.
     Process.link(pid_server)
-    true = :ets.insert(pid_ets, {self, key, key_ets})

-    case register_key(kind, pid_server, key_ets, key, {key, {self, value}}) do
-      {:ok, _} = ok ->
-        for listener <- listeners do
-          Kernel.send(listener, {:register, registry, key, self, value})
-        end
+    if register_pid(kind, pid_ets, key_ets, self, key) do
+      case register_key(kind, pid_server, key_ets, key, {key, {self, value}}) do
+        {:ok, _} = ok ->
+          for listener <- listeners do
+            Kernel.send(listener, {:register, registry, key, self, value})
+          end

-        ok
+          ok

-      {:error, {:already_registered, ^self}} = error ->
-        error
+        {:error, {:already_registered, ^self}} = error ->
+          error

-      {:error, _} = error ->
-        true = :ets.delete_object(pid_ets, {self, key, key_ets})
-        unlink_if_unregistered(pid_server, pid_ets, self)
-        error
+        {:error, _} = error ->
+          true = :ets.delete_object(pid_ets, {self, key, key_ets})
+          unlink_if_unregistered(pid_server, pid_ets, self)
+          error
+      end
+    else
+      {:error, {:already_registered, self}}
     end
   end

+  defp register_pid(:unique, pid_ets, key_ets, self, key) do
+    :ets.insert_new(pid_ets, {self, key, key_ets})
+  end
+
+  defp register_pid(:duplicate, pid_ets, key_ets, self, key) do
+    :ets.insert(pid_ets, {self, key, key_ets})
+  end
+
   defp register_key(:duplicate, pid_server, key_ets, _key, entry) do
     true = :ets.insert(key_ets, entry)
     {:ok, pid_server}
```

**Comment by josevalim** [comment]
> To be super clear, here is what I think should be the fix:

Nope. This is not going to work. `insert_new` checks only for the key and not the whole entry, even on duplicate_bag. :( So i guess we are back to the unique integer, haha.

So here is what I think the fix should actually be:

```diff
diff --git a/lib/elixir/lib/registry.ex b/lib/elixir/lib/registry.ex
index 3d23f72f0..d47d54b1c 100644
--- a/lib/elixir/lib/registry.ex
+++ b/lib/elixir/lib/registry.ex
@@ -911,7 +911,8 @@ defmodule Registry do
     # always be able to do the cleanup. If we register first to the
     # key one and the process crashes, the key will stay there forever.
     Process.link(pid_server)
-    true = :ets.insert(pid_ets, {self, key, key_ets})
+    counter = System.unique_integer()
+    true = :ets.insert(pid_ets, {self, key, key_ets, counter})

     case register_key(kind, pid_server, key_ets, key, {key, {self, value}}) do
       {:ok, _} = ok ->
@@ -922,10 +923,11 @@ defmodule Registry do
         ok

       {:error, {:already_registered, ^self}} = error ->
+        true = :ets.delete_object(pid_ets, {self, key, key_ets, counter})
         error

       {:error, _} = error ->
-        true = :ets.delete_object(pid_ets, {self, key, key_ets})
+        true = :ets.delete_object(pid_ets, {self, key, key_ets, counter})
         unlink_if_unregistered(pid_server, pid_ets, self)
         error
     end
```

But we will probably have to change other places in the code.
