### ISSUE TITLE
Code.format_string! fails with dialyzer

### ISSUE THREAD

**Issue by rodrigues** [elixir-lang/elixir#8631]
### Environment

* Elixir 1.8.0 (compiled with Erlang/OTP 21.2.2)

* Operating system: macOS Mojave

### Current behavior

The presence of `Code.format_string!` in a pipeline makes dialyzer to emit a warning. Example:

```elixir
defmodule DialyzerCodeFormat do
  @path "~/code/dialyzer_code_format/test.exs" |> Path.expand()

  @spec call() :: :ok | {:error, File.posix()}
  def call do
    content =
      %{foo: :bar}
      |> inspect()
      |> Code.format_string!()
      |> IO.iodata_to_binary()

    @path |> File.write(content)
  end
end

:ok = DialyzerCodeFormat.call()
```

`lib/dialyzer_code_format.ex:5: Function call/0 has no local return`

### Expected behavior

The same as when there's no format, this works:

```elixir
@spec call() :: :ok | {:error, File.posix()}
def call do
  content = %{foo: :bar} |> inspect()
  @path |> File.write(content)
end
```

For reference, dialyzer configuration in `mix.exs`

```elixir
 def project do
    [
      # ...
      dialyzer: dialyzer()
    ]
  end
  defp deps do
    [
      {:dialyxir, "~> 1.0.0-rc.4", only: :dev, runtime: false}
    ]
  end

  defp dialyzer do
    [
      plt_add_apps: [:mix],
      flags: [:error_handling, :race_conditions, :unmatched_returns]
    ]
  end
```

**Comment by josevalim** [comment]
Hi @rodrigues, can you please pack all of this into a minimal project? It is going to make it easier for us to reproduce the issue and eventually fix it. Thanks!

**Comment by rodrigues** [comment]
@josevalim there you go, thanks! https://github.com/rodrigues/dialyzer_code_format

**Comment by romul** [comment]
That's because `Code.Formatter.to_algebra!/2` could raise an exception and this function is called inside of `Code.format_string!/1`

https://github.com/elixir-lang/elixir/blob/v1.8.0/lib/elixir/lib/code/formatter.ex#L240

I can handle this one, if you point me out what kind of solution would be appropriate.
Maybe adding `no_return` result option to all functions specs down to `Code.Formatter.to_algebra!/2`?

**Comment by romul** [comment]
In fact, to satisfy dialyzer it's enough to add `no_return` to the `call` function spec, like that:

```elixir
  @spec call() :: no_return
  def call do
    content =
      %{foo: :bar}
      |> inspect()
      |> Code.format_string!()
      |> IO.iodata_to_binary()

    @path |> File.write(content)
  end
```

**Comment by josevalim** [comment]
`no_return` is not correct though because that function can return in some situations. We only use `no_return` when the function is always fail. So this error is happening because dialyzer thinks something somewhere inside those functions will always fail.

**Comment by josevalim** [comment]
I have found a fix while exploring the problem, pushing shortly.

**Comment by adamwight** [comment]
I seem to be getting the same error even after the patch:
dialyxir_erlang-23.0.1_elixir-1.10.3_deps-dev.plt,
```
lib/codegen.ex:24:call                          
The function call will not succeed.                              
                                                 
Code.format_string!(atom() | [any()] | number() | {_, _, _, _})
                             
will never return since it differs in arguments with             
positions 1st from the success typing arguments:            
                                                                              
(binary())                                                    
```

**Comment by josevalim** [comment]
Note: we have other Dialyzer fixes in master.

**Comment by adamwight** [comment]
My error came from code like this,
```
EEx.eval_file(template, bindings)
|> Code.format_string!()
```

The success type mismatch was caused by a variable output type from the `EEx.eval_file` function, which can return `any()`.  It was possible to workaround by casting a returned `atom` to string--and the whole issue is probably due to some misunderstanding of mine.

Workaround:
```
raw_code = EEx.eval_file(template, bindings)
raw_code = cond do
  is_atom(raw_code) -> Atom.to_string(raw_code)
  true -> raw_code
end
```
