### ISSUE TITLE
Allows `@callback`  to not to have a return type to act as a head definition

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8636]
The reason why I think we need this is to be able to set the argument name, same like we do with bodiless functions.

```elixir
def foo(item)
def foo(:bar), do: baz
```

with callbacks it is not possible to dot that at the moment.

this will generate a signature of: `__info__(atom)`
```elixir
  @callback __info__(:attributes) :: keyword()
  @callback __info__(:compile) :: [term()]
```

Not giving a return type, will will throw a compile error.
```elixir
  @callback __info__(item)  
  @callback __info__(:attributes) :: keyword()
  @callback __info__(:compile) :: [term()]
```

```
== Compilation error in file lib/module.ex ==
** (CompileError) lib/module.ex:516: type specification missing return type: __info__(item)
    (elixir) lib/kernel/typespec.ex:881: Kernel.Typespec.compile_error/2
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (elixir) lib/kernel/typespec.ex:226: Kernel.Typespec.translate_typespecs_for_module/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
```

the only way is to do

```elixir
  @callback __info__(item :: :attributes) :: keyword()
  @callback __info__(:compile) :: [term()]
```

which is rendered in ExDoc and IEx as:
```
__info__(item) View Source
__info__(item :: :attributes) :: keyword()
__info__(:compile) :: [term()]
```

So you see `item :: :attributes`

**Comment by josevalim** [comment]
The reason why we have it for functions is because the documentation tooling uses that signature  but the documentation tooling would not used said signature for specs/callbacks, because there is nowhere we can store this information for a callback.
