### ISSUE TITLE
IEx: recompiling module with `r` helper doesn't reload changes in documentation

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8659]
run `iex -S mix`

```iex
h Foo.bar
```
> shows docs

update docs, save file.

```iex
r Foo
h Foo.bar
```

and the docs have not changed.

**Comment by josevalim** [comment]
Yup, it is mentioned and explained in the docs:

```iex
iex(1)> h r

                                 def r(module)

Recompiles and reloads the given module.

Please note that all the modules defined in the same file as module are
recompiled and reloaded.

This function is meant to be used for development and debugging purposes. Do
not depend on it in production code.

## In-memory reloading

When we reload the module in IEx, we recompile the module source code, updating
its contents in memory. The original .beam file in disk, probably the one where
the first definition of the module came from, does not change at all.

Since typespecs and docs are loaded from the .beam file (they are not loaded in
memory with the module because there is no need for them to be in memory), they
are not reloaded when you reload the module.
```

:)

**Comment by eksperimental** [comment]
I should read the docs more carefully :-P
Sorry for the false positive

**Comment by eksperimental** [comment]
@josevalim is this part of this issue, or should I create a new one?

Converting a private function to public and reloading the module with "r",
doesn't make the previously private function visible in autocompletion.

**Comment by josevalim** [comment]
It is the same root cause. “r” doesn’t change what is in disk. So both
issues can’t be fixed. recompile should work though.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by eksperimental** [comment]
Thank you
