### ISSUE TITLE
mix test: passing a line number out of range makes the last test to execute

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8675]
While doing a QA for https://github.com/elixir-lang/elixir/pull/8673, I came across this bug,

You can test it with any file (no doctest for simplicity)

`mix test test/some_test.exs:100000`

will output
```
 Excluding tags: [:test]
Including tags: [line: "1000"]

18
.

Finished in 0.03 seconds
3 tests, 0 failures, 2 excluded
```

where the number of excluded files is always be one less than the total number of tests.

I have verified and the last test gets executed

**Comment by josevalim** [comment]
Yes. the way the feature is described takes that into account:

> If the given line starts a describe block, the line filter runs all tests in
> it. Otherwise, **it runs the closest test on or before the given line number**.

**Comment by eksperimental** [comment]
It is consistent with what the documentation explains, but IMO if the line is out of the last describe or last test block, it shouldn't run anything.
