### ISSUE TITLE
Future commit messages should be improved

### ISSUE THREAD

**Issue by bmwiedemann** [elixir-lang/elixir#8700]
Future commit messages should be improved.
This is sort of a meta-issue, not affecting the elixir software itself, but getting this right can greatly improve the long-term maintainability of the project.

One example is 3fd6cf5e917e2f1383d4ecf1f3de5726337f66dc - just to illustrate and not meant to blame its author..

In our (SUSE) projects, we considered it good style to include in commit texts some detail about "Why" a change is good that is not only a issue-tracker number, because that makes the git history more readable and much more useful in case the issue-tracker is changed or goes down later (think decades).
That is related to item 7 in https://chris.beams.io/posts/git-commit/
It is also good to consistently follow other recommendations in the list.
I can remember having done 1-line changes with 20 lines of commit message.

**Comment by josevalim** [comment]
Thanks for the references, we will discuss this internally. The perspective of decades in comparison to the issues tracker is a good one. :+1:

We will close this for now though, as it is a "meta" issue, as you said.
