### ISSUE TITLE
A big thank you for all the team

### ISSUE THREAD

**Issue by angelo-moreira** [elixir-lang/elixir#8704]
I just want to give a big thank you to everybody that contributed and make this fantastic technology possible, I have used a lot of technology but this is the best and well thought language I have ever work with, brought me back the joy I had when I was 16 doing my first `hello world`

A big big big THANK YOU

**Comment by josevalim** [comment]
Thanks for the nice words @angelo-moreira! :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

I would love to keep this open but I have to stay true to our rules and close non actionable issues. 😅 But still, very appreciated!
