### ISSUE TITLE
`mix clean` should not be required after moving a module file

### ISSUE THREAD

**Issue by kurtome** [elixir-lang/elixir#8728]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

Erlang/OTP 21 [erts-10.0.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.7.3 (compiled with Erlang/OTP 21)

* Operating system: OSX 10.14.2

### Current behavior

Include code samples, errors and stacktraces if appropriate.
 - Create file at lib/frontend/bar.ex, with a module name Foo.Frontend.Bar
 - Save code and compile app
 - Move file to lib/frontend/bar/bar.ex
 - Save and compile with --warnings-as-errors
 - Local build output still has a stale version of the old file, and the new file, which leads to a
   compiler warning (or error if you have the flag on)

```
Compiling 4 files (.ex)
warning: redefining module Foo.Frontend.Bar (current version loaded from /Users/.../_build/dev/lib/frontend/ebin/Elixir.Foo.Frontend.Bar.beam)
  lib/frontend/bar/bar.ex:1

Compilation failed due to warnings while using the --warnings-as-errors option
```

### Expected behavior

Compiler should detect deleted file and purge it from the build output, resulting in a clean build.

**Comment by josevalim** [comment]
Hi @kurtome. I cannot reproduce this:

```
~/OSS$ mix new foo
* creating README.md
* creating .formatter.exs
* creating .gitignore
* creating mix.exs
* creating config
* creating config/config.exs
* creating lib
* creating lib/foo.ex
* creating test
* creating test/test_helper.exs
* creating test/foo_test.exs

Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:

    cd foo
    mix test

Run "mix help" for more commands.
~/OSS$ cd foo/
~/OSS/foo$ mix compile
Compiling 1 file (.ex)
Generated foo app
~/OSS/foo$ mkdir -p lib/foo/
~/OSS/foo$ mv lib/foo.ex lib/foo/bar.ex
~/OSS/foo$ mix compile
Compiling 1 file (.ex)
```

It is also consistent with the code, since we [remove files before we compile](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/compilers/elixir.ex#L104-L107).

Can you please provide a more detailed step by step that reproduces the issue? Thank you!

**Comment by kurtome** [comment]
Apologies for the bad repro steps, I thought I had the cause isolated. This definitely did just happen to me though in my decent sized Phoenix app. I created a new controller by copying an existing one, then renamed and moved the controller file and was unable to compile with the above error. I have  `   elixirc_options: [warnings_as_errors: true],` on in my project config. I might be a Phoenix code reloading problem, but I'm having trouble reproducing it now 😑

**Comment by josevalim** [comment]
No problem. If you can reproduce it, please let us know and we will gladly reopen this and take a look at it.

Also, Phoenix code reloading just calls `mix compile`, so it's most likely safe too. :) So there may be something else at play. Thanks!
