### ISSUE TITLE
The `recompile` command in IEx sometimes does not work, but compiling outside IEx works

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8744]
### Environment

```
$ elixir --version
Erlang/OTP 21 [erts-10.2.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.0 (compiled with Erlang/OTP 21)
```
I build inside a Docker container, and the Docker version is

```
$ docker --version
Docker version 18.09.0, build 4d60db4
```

### Current behavior

Sometimes when calling `recompile` in IEx I get this incomprehensible error, or a similar one:

```
** (MatchError) no match of right hand side value: nil
    (elixir) lib/kernel/parallel_compiler.ex:303: Kernel.ParallelCompiler.waiting_on_without_definition/2
    (elixir) lib/kernel/parallel_compiler.ex:257: anonymous fn/3 in Kernel.ParallelCompiler.spawn_workers/6
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/kernel/parallel_compiler.ex:256: Kernel.ParallelCompiler.spawn_workers/6
    (elixir) lib/kernel/parallel_compiler.ex:137: Kernel.ParallelCompiler.spawn_workers/3
    (mix) lib/mix/compilers/elixir.ex:195: Mix.Compilers.Elixir.compile_manifest/9
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:68: Mix.Tasks.Compile.All.run_compiler/2
```

### Expected behavior

The expected behavior is for `recompile` to work everytime inside IEx, and to not give this error.

The **workaround** I do, which seems to always work, is to abandon IEx, run `mix do clean, compile`, and get back to IEx. 

I do not know how to reproduce this strange behavior yet I hope this report is worth to users facing this problem, and to Elixir core delopers to whom this report might shed some light on what is  happening here.

**Comment by josevalim** [comment]
Thanks for the report. We will leave it open for a short period of time, to see if others have stumbled on this same issue, but without a way to reproduce the issue, then there isn't much we can do.

**Comment by vans163** [comment]
What host filesystem, raid?, fstab (how is it mounted), docker uses FUSE and/or overlay2 depending on system support.  Are you passing the project in as a volume? To me it looks like some core file is missing during the recompile run due to fs issues, mix caches timestamps of files to determine when to recompile, iv seen mix act up all the time due to this, but its gotten better.

**Comment by josevalim** [comment]
@mguimas if you were receiving those annoying messages, it usually means your computer was hibernating or suspend. So one thing you could do to help us pinpoint the issue is to see if the errors reported in this thread happen always or only after hibernating.

**Comment by josevalim** [comment]
Ok, I could reproduce this. It is related to async processes in the compiler. Any chance you are using gettext with a configuration to compile backends in parallel?

**Comment by mguimas** [comment]
They happen much time after the computer returned from hibernated mode.

My typical workflow is this: the computer returns from hibernation at the start of the day; then I code outside the container, and go into the container and type `recompile`; everything compiles, or I get some compilation error, go fix it outside in the sources, tye `recompile` inside the container, and get compilation ok; then I run this cycle many times without seeing the error reported in this issue, but then occasionally this error happens. I don't know why, hence my difficulty to reproduce it, but quiting IEx and `mix do clean, compile` inside the container then compiles fine, and I go back into IEx.

I am sure that I see the error reported in this issue several recompilations after comming back from hibernation, otherwise it would be easy to reproduce it.

(Also, I have an SSD only)

**Comment by mguimas** [comment]
I have an umbrella project with two subprojects.

One of the projects has these lines in its configuration:

```
compilers: [:phoenix, :gettext] ++ Mix.compilers
...
{:gettext, "~> 0.16"}
```

The other project does not have any of these as it essentially only depends on Ecto.

I am working in the root directory of this second project, where I usually run via:

`$ iex -S mix`

It is in this project I am calling `recompile`.

I never work on the other project which depends on `gettext`; that is, I think I am not messing somehow with the first project when I only work in the second project.

**Comment by mguimas** [comment]
Wow, that was a big fix 👍
Thanks.
