### ISSUE TITLE
stdout piping causes softlock if piped to process that closes stdin

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#8747]
1.8.0
OTP22

If you pipe stdio to another process and close stdin in that process (even graceful term), (maybe requires a next write to stdio) locks up the emulator with this. The correct behaviour should be to throw the exception normally allows the process that causes this to crash.

```
:gen_event handler Logger.Backends.Console installed in Logger terminating
** (exit) an exception was raised:
    ** (RuntimeError) no device registered with the name :user
        (logger) lib/logger/backends/console.ex:160: Logger.Backends.Console.async_io/2
        (logger) lib/logger/backends/console.ex:145: Logger.Backends.Console.log_event/5
        (logger) lib/logger/backends/console.ex:49: Logger.Backends.Console.handle_event/2
        (stdlib) gen_event.erl:577: :gen_event.server_update/4
        (stdlib) gen_event.erl:559: :gen_event.server_notify/4
        (stdlib) gen_event.erl:300: :gen_event.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

This is piping an .exs script output into another program.

```
iex myscript.exs | prog_that_closes_stdin
```

Removing the logger backend solves this Logger.remove_backend(:console), but I do not think the emulator should ever get into a state like this.

Another thing to add to this, is you get perma stuck inside IO.puts :stderr, "hi" or IO.puts :stdio, "hi" and CTRL-C doesnt respond so we need to use kill -9 or CTRL Z.

This silly (and not 100% reliable) fix is getting me by for now
```elixir
pid = :erlang.spawn(fn()->
    receive do
        :io_ok -> :die
    after
        1500 -> System.halt()
    end
end)
:ok = IO.write(:stdio, body)
send(pid, :io_ok)
```

**Comment by josevalim** [comment]
For completeness, i could reproduce it with this:

```
~/OSS/elixir[master %]$ cat foo
#!/bin/sh
0<&-
~/OSS/elixir[master %]$ iex | ./foo
:gen_event handler Logger.Backends.Console installed in Logger terminating
** (exit) an exception was raised:
    ** (RuntimeError) no device registered with the name :user
        (logger) lib/logger/backends/console.ex:160: Logger.Backends.Console.async_io/2
        (logger) lib/logger/backends/console.ex:145: Logger.Backends.Console.log_event/5
        (logger) lib/logger/backends/console.ex:49: Logger.Backends.Console.handle_event/2
        (stdlib) gen_event.erl:573: :gen_event.server_update/4
        (stdlib) gen_event.erl:555: :gen_event.server_notify/4
        (stdlib) gen_event.erl:296: :gen_event.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

If I start the iex node with a name, I can connect remotely to it and see that the whole system is fine, except for the console backend which has been properly removed. So the emulator is not stuck in any way, it just can't communicate with stdio (for example, writing to stderr is fine):

```
iex --sname foo -e 'spawn fn -> require Logger; Stream.interval(1000) |> Enum.each &IO.puts :stderr, "#{&1}" end' | ./foo
```

I will continue looking into this. Meanwhile, may I ask why are you using `iex` to run scripts? Why not use `elixir`? If I use `elixir`, the system eventually errors when writing to stdout:

```
$ elixir --sname foo -e 'Process.sleep(1000); IO.puts :stderr, "oops"; IO.inspect :stderr, IO.puts("abc"), []; IO.inspect :stderr, IO.puts("abc"), []; Process.sleep(:infinity)' | ./foo
oops
:ok
** (ErlangError) Erlang error: :terminated
    (stdlib) :io.put_chars(:standard_io, :unicode, ["abc", 10])
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
    (stdlib) erl_eval.erl:404: :erl_eval.expr/5
    (stdlib) erl_eval.erl:122: :erl_eval.exprs/5
    (elixir) lib/code.ex:232: Code.eval_string/3
:gen_event handler Logger.Backends.Console installed in Logger terminating
** (exit) an exception was raised:
    ** (RuntimeError) no device registered with the name :user
        (logger) lib/logger/backends/console.ex:160: Logger.Backends.Console.async_io/2
        (logger) lib/logger/backends/console.ex:145: Logger.Backends.Console.log_event/5
        (logger) lib/logger/backends/console.ex:49: Logger.Backends.Console.handle_event/2
        (stdlib) gen_event.erl:573: :gen_event.server_update/4
        (stdlib) gen_event.erl:555: :gen_event.server_notify/4
        (stdlib) gen_event.erl:296: :gen_event.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

But with IEx we don't, which is why you opened this report. :)

**Comment by josevalim** [comment]
So this behaviour also exists in Erlang:

    $ erl | ./foo

Given the fact the system is actually operating normally, the only limitation is that it can't talk to stdio, I think this is reasonable behaviour. After all, your system may be communicating with many streams, ports, files, sockets and one of them crashing may not be enough reason to bring the whole system down. However, if you do want to bring the system down for missing stdout, then this would have to be a  behaviour added to Erlang. So I suggest moving the discussion there. Thanks!

**Comment by vans163** [comment]
> reason to bring the whole system down. However, if you do want to bring the system down for miss

The behavior should be returning :error or :stdio_closed from IO.write instead of blocking indefinitely, perhaps adding a timeout, and indeed the fix probably belongs on Erlang side.

**Comment by josevalim** [comment]
@vans163 to clarify, it does return :error or :stdio_closed, which causes the IEx process to terminate, but the rest of the system continues runniing. If you try  to invoke IO.puts or similar, I also get an error.

**Comment by vans163** [comment]
> @vans163 to clarify, it does return :error or :stdio_closed, which causes the IEx process to terminate, but the rest of the system continues runniing. If you try to invoke IO.puts or similar, I also get an error.

Let me recheck, I was getting a deadlock on IO.write, let me try some variants now.

**Comment by ericdude4** [comment]
Has there been any progress on this? I am currently running into this issue in one of my applications which seems to crash without any explanation...

```
18:06:03.014 [error] GenServer #PID<0.1159.0> terminating
** (stop) :eio
Last message: {:EXIT, #PID<0.1160.0>, :eio}
State: {:state, :user_sup, :undefined, #PID<0.1160.0>, {#PID<0.1159.0>, :user_sup}}
18:06:03.019 [error] :gen_event handler Logger.Backends.Console installed in Logger terminating
** (RuntimeError) no device registered with the name :user
    (logger 1.10.2) lib/logger/backends/console.ex:156: Logger.Backends.Console.async_io/2
    (logger 1.10.2) lib/logger/backends/console.ex:141: Logger.Backends.Console.log_event/5
    (logger 1.10.2) lib/logger/backends/console.ex:45: Logger.Backends.Console.handle_event/2
    (stdlib 3.12.1) gen_event.erl:577: :gen_event.server_update/4
    (stdlib 3.12.1) gen_event.erl:559: :gen_event.server_notify/4
    (stdlib 3.12.1) gen_event.erl:561: :gen_event.server_notify/4
    (stdlib 3.12.1) gen_event.erl:300: :gen_event.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:error, #PID<0.1136.0>, {Logger, [["GenServer ", "#PID<0.1159.0>", " terminating", ["\n** (stop) " | ":eio"], "\nLast message", [], ": ", "{:EXIT, #PID<0.1160.0>, :eio}"], "\nState: ", "{:state, :user_sup, :undefined, #PID<0.1160.0>, {#PID<0.1159.0>, :user_sup}}"], {{2020, 7, 28}, {18, 6, 3, 14}}, [crash_reason: {:eio, []}, domain: [:otp], error_logger: %{tag: :error}, file: "gen_server.erl", function: "error_info/7", gl: #PID<0.1136.0>, line: 889, mfa: {:gen_server, :error_info, 7}, module: :gen_server, pid: #PID<0.1159.0>, report_cb: &:gen_server.format_log/1, time: 1595959563014503]}}
State: %Logger.Backends.Console{buffer: [], buffer_size: 0, colors: %{debug: :cyan, enabled: true, error: :red, info: :normal, warn: :yellow}, device: :user, format: ["\n", :time, " ", :metadata, "[", :level, "] ", :levelpad, :message, "\n"], level: nil, max_buffer: 32, metadata: [], output: nil, ref: nil}
```

I can confirm that the process is still running in the background with `ps -aux`, but functionally, it has stopped working.
