### ISSUE TITLE
Dialyzer Error Using Derive Inspect in 1.8.0, 1.8.1

### ISSUE THREAD

**Issue by asummers** [elixir-lang/elixir#8749]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
❯ elixir --version
Erlang/OTP 22 [DEVELOPMENT] [erts-10.0.1] [source-70b46d747d] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.0 (compiled with Erlang/OTP 22)
```
* Operating system: OSX, also failing on Linux

### Current behavior

Given the following code,

```elixir
defmodule Test do
  @derive {Inspect, except: [:id]}
  defstruct [:id, :first_name]
end
```

Dialyzer complains about the generated `inspect` call. Reverting to a pre-`1.8.0` custom `defimpl Inpsect` here makes the error disappear.

```
lib/demolyzer.ex:3: Function inspect/2 has no local return.
lib/demolyzer.ex:3: The call 'Elixir.Inspect.Any':inspect(__@3::map(),__@5::{'doc_color','doc_line' | 'doc_nil' | binary() | {'doc_collapse',pos_integer()} | {'doc_force',_} | {'doc_break' | 'doc_color' | 'doc_cons' | 'doc_fits' | 'doc_group' | 'doc_string',_,_} | {'doc_nest',_,'cursor' | 'reset' | non_neg_integer(),'always' | 'break'},atom() | binary() | maybe_improper_list(atom() | binary() | maybe_improper_list(any(),atom() | binary() | []) | char(),atom() | binary() | [])},__@2::#{'syntax_colors':=_, _=>_}) will never return since it differs in the 2nd argument from the success typing arguments: (map(),binary(),#{'limit':=_, _=>_})
```

### Expected behavior

Dialyzer does not complain. 

I have not checked this on 1.8.1 yet, but I did not see this in the past few weeks of commits, so apologies if this is already fixed. 

Edit: Same issue in 1.8.1

**Comment by josevalim** [comment]
I don’t think this is fixed, yeah. Can you please provide a minimal app
that reproduces the issue?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by asummers** [comment]
https://github.com/asummers/failing_dialyzer

`mix new` + that aforementioned module + `dialyxir` import in `mix.exs` + deleting test

Running `mix dialyzer` results in the error.
