### ISSUE TITLE
FEATURE: Keyed maps syntax shortcuts

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#8767]
New feature.

keyed maps support in syntax / guards

OLD:
```
def verify(%{user_id: user_id, user_balance: user_balance}), do: user_id
```
NEW:
```
def verify(%{user_id, user_balance}) when user_balance > 0, do: user_id
```
Basically writing a map like %{user_id} implies to the compiler to expand it to %{user_id: user_id}

user_id = 5
new_map = %{user_id}

insert support too

**Comment by Gazler** [comment]
Has been discussed many times before.

https://groups.google.com/forum/#!topic/elixir-lang-core/NoUo2gqQR3I

**Comment by josevalim** [comment]
Also please don't use the issues tracker for feature requests, as mentioned in the issues template. Thank you!
