### ISSUE TITLE
Running `i :Kernel` in IEx seems to crash

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#8780]
### Environment

```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
```

### Current behavior

```
ex(15)> i :Kernel
Term

10:46:53.462 [error] beam/beam_load.c(1428): Error loading module 'Kernel':
  module name in object code is kernel


  :Kernel

10:46:53.462 [error] Loading of /usr/local/Cellar/erlang/21.2/lib/erlang/lib/kernel-6.2/ebin/Kernel.beam failed: :badfile

Data type
  Atom
Reference modules
  Atom
Implemented protocols
  IEx.Info, Inspect, String.Chars, List.Chars
```

### Expected behavior

The current behavior lets the user think a crash happened somewhere.

I suppose this is not desired, and the normal behavior is expected as for other non-special modules.

Perhaps it is needed to treat some modules as special for the `i` command to behave normally.

**Comment by whatyouhide** [comment]
This happens when you do `Code.ensure_loaded?(:Kernel)`.

**Comment by mguimas** [comment]
@whatyouhide That situation you refer does not happen to me:

```
$ iex
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Code.ensure_loaded?(:Kernel)
false
iex(2)> Code.ensure_loaded?(Kernel)
true
iex(3)>
```

**Comment by fertapric** [comment]
`:Kernel` and `Kernel` are not equivalent. 

If you want to directly use atoms instead of module aliases, you have to include the Elixir prefix: `:'Elixir.Kernel'`.

More info at https://hexdocs.pm/elixir/Kernel.html#defmodule/2-module-names

**Comment by fertapric** [comment]
@mguimas regarding the error, is you filesystem case insensitive? I think that could mess up with how modules are being loaded. Same thing happens if you misspell `DateTime`:

```elixir
iex(1)> i Datetime

12:48:15.670 [error] beam/beam_load.c(1428): Error loading module 'Elixir.Datetime':
  module name in object code is Elixir.DateTime



12:48:15.673 [error] Loading of /usr/local/Cellar/elixir/1.8.0/bin/../lib/elixir/ebin/Elixir.Datetime.beam failed: :badfile

Term
  Datetime
Data type
  Atom
Raw representation
  :"Elixir.Datetime"
Reference modules
  Atom
Implemented protocols
  IEx.Info, Inspect, List.Chars, String.Chars
```

**Comment by hauleth** [comment]
@whatyouhide @fertapric this issue is related to the case-sensitiveness of the filesystem. It tries to load `Kernel.beam` and on macOS/Windows it loads `kernel.beam` instead, that mean that the file name and defined module mismatch. Instead I would catch that error (only in `IEx.Helpers.i/0-1`) and provide "more user friendly" message, if possible of course.

**Comment by mguimas** [comment]
@fertapric According to [this](https://apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not) my FS is case-insensitive:

```
$ diskutil info /
...
   File System Personality:  APFS
   Type (Bundle):            apfs
   Name (User Visible):      APFS
...
```

**Comment by hauleth** [comment]
To provide such behaviour the check for module would need to be done in 2 steps:

```elixir
def is_module(atom) when is_atom(atom) do
  case :code.get_object_code(atom) do
    :error -> Code.ensure_loaded?(atom)
    {^atom, beam, _file} ->
      module_name =
        beam
        |> :beam_lib.info()
        |> Keyword.get(:module, 0) # to prevent match on any atom, even `nil`

      module_name == atom
  end
end
```

**Comment by fertapric** [comment]
@mguimas Btw, I think @whatyouhide meant `Code.ensure_loaded(:Kernel)` (without the question mark) 🙂

**Comment by hauleth** [comment]
@fertapric it returns `{:error, :badfile}` and also logs error messages in the console.

**Comment by fertapric** [comment]
Ups! My bad. Both print error messages in the console.

**Comment by pedrosnk** [comment]
this seems to be happening only with OTP related file names, using the same case sensitive logic. trying `:String`, `:Pg2`, `:Gen_tcp` it's gonna behave the same.

**Comment by josevalim** [comment]
Closing in favor of #8782.
