### ISSUE TITLE
Mix deps.update problems with complex self-dependency

### ISSUE THREAD

**Issue by Virviil** [elixir-lang/elixir#8788]
## Environment:
```
Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Interactive Elixir (1.7.4) - press Ctrl+C to exit (type h() ENTER for help)

iex(1)> :os.type
{:unix, :darwin}
iex(2)> :os.version
{18, 2, 0}
```

## Bug description:

This line should appear for self-dependency.
https://github.com/elixir-lang/elixir/blob/2e576f67a00164d88e2e242e523dc3b5c1a8a5db/lib/mix/lib/mix/dep/converger.ex#L21

This is working, for example, when library with name `foo` requires library with name `foo` in it's dependency.

**BUT**: While this process has one additional step, i.e. `foo` requires `bar`, and `bar` requires `foo` (i.e. **foo->bar->foo**), resolution is not working.

It leads to 2 different situations:

### Simple project.

Library `foo` will be downloaded as a dependency inside project `foo`, but as expected the project will fail to start with message:
```
another project with the same name was already defined
```

### Umbrella project

`mix deps.get` hangs on `Resolving Hex dependencies...` with consuming 100% CPU and all available memory.

## Example 

I've tested on project with name `plug`, that requires `plug_cowboy`(that is relies on `plug`).
Example repository: https://github.com/Virviil/hang

**Comment by josevalim** [comment]
@wojtekmach @ericmj I believe this is a Hex bug. Thoughts?

**Comment by ericmj** [comment]
Yeah, I think so too.

**Comment by josevalim** [comment]
Hi @Virviil, could you please report this bug on https://github.com/hexpm/hex? Thank you.

**Comment by Virviil** [comment]
Done. https://github.com/hexpm/hex/issues/693
