### ISSUE TITLE
EEx inconsistent trim behaviour with carriage returns

### ISSUE THREAD

**Issue by evax** [elixir-lang/elixir#8792]
### Environment

* Elixir from master / OTP 21
* Operating system: Linux

### Current behavior

This test would fail on the current and previous Elixir versions:

``` elixir
  test "trim mode with multiple lines" do
      string = """
      <%= "First line" %>
      <%= "Second line" %>
      <%= "Third line" %>
      <%= "Fourth line" %>
      """

      expected = """
      First line
      Second line
      Third line
      Fourth line
      """

      assert_eval(expected, string, [], trim: true)
    end
```
```shell
  1) test evaluates trim mode with multiple lines (EExTest)
     test/eex_test.exs:87
     Assertion with == failed
     code:  assert result == expected
     left:  "First lineSecond line\nThird lineFourth line\n"
     right: "First line\nSecond line\nThird line\nFourth line\n"
     stacktrace:
       test/eex_test.exs:102: (test)
```

### Expected behavior

I would expect the trailing `\n` not to be trimmed (or at least to be trimmed always).

The EEx docs reads `:trim - trims whitespace left/right of quotation tags`, and the line break handling is only mentioned in a [comment in the code](https://github.com/elixir-lang/elixir/blob/master/lib/eex/lib/eex/tokenizer.ex#L203).

My understanding is that the logic was specifically introduced in #3194 to deal with `if`/`else` statements in templates (see [this comment](https://github.com/elixir-lang/elixir/pull/3194#issuecomment-86178406)).

As trim is enabled by default in [phoenix templates](https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/template/eex_engine.ex#L9), it makes it hard to create plain text templates in phoenix, one needing to introduce additional line breaks to compensate for the trim behaviour. This also means there's potentially a lot of code depending on the current behaviour.

Maybe a path forward would be to introduce a non line-break trimming tag?

**Comment by josevalim** [comment]
You should open up an issue in Phoenix. It should only enable trim for HTML templates.

Other than that, there is a bug here indeed because we should be more consistent on the trimming and remove the whitespace on all cases in your example above.
