### ISSUE TITLE
With macro using parens and args on different lines misses code coverage

### ISSUE THREAD

**Issue by TheFirstAvenger** [elixir-lang/elixir#8796]
When using the `with` macro in this format:
```
with(
  :ok <- function(),
  :ok <- function
) do
```
the first line doesn't get tagged as covered. This appears to be unique to with, as other macros do get tagged as covered:
![screen shot 2019-02-14 at 10 34 12 am](https://user-images.githubusercontent.com/8557871/52798581-3534af80-3046-11e9-9c2d-cd2c964d6656.png)

Minimal reproduction repo:
https://github.com/TheFirstAvenger/with_test

The purpose of using parens on the with macro is that this improves readability of the with statement:

```
with
  :ok <- function(),
  :ok <- function
do
```
but if you don't include parens, the formatter will revert that format to:

```
with :ok <- function(),
     :ok <- function do
```

**Comment by josevalim** [comment]
Can it be that the lack of coverage is because none of the failure paths
are checked?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Confirmed. If I change the second clause to `:ok <- :error`, then all lines are tested. I agree this is not super obvious but I don't think there is another way we can portray the "catch all" in those cases and it is nice that cover is actually catching that. :+1:

**Comment by TheFirstAvenger** [comment]
@josevalim So if I understand it correctly, the issue is that the implicit failure path (`else:` block) of `with` is not being tested, but when using `with` without parens, the fact is masked because the first arg of the with statement marks that line "covered" by tests? This means that an explicit `else:` must be defined and hit for code coverage to be complete on a with statement that uses parens as above, and that the implicit `else` is missed in coverage but not indicated when you use `with` without parens.

Side note: Is it possible to have the formatter additionally accept this (IMHO more readable) format:
```
with
  :ok <- function(),
  :ok <- function()
do
```
and not squash it down to two lines?

**Comment by josevalim** [comment]
Correct!

> Side note: Is it possible to have the formatter additionally accept this (IMHO more readable) format

No because that is not even valid Elixir (or it won't compile to what you think it does). :D
