### ISSUE TITLE
Error while fetching deps in umbrella app

### ISSUE THREAD

**Issue by AndrewDryga** [elixir-lang/elixir#8803]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.8.1 / OTP 21.2.5
* Operating system: MacOSS

### Current behavior

Following code raises MatchError exception in our project: `Mix.Project.deps_paths()`.

Stack trace:
```
** (MatchError) no match of right hand side value: nil
    (mix) lib/mix/dep.ex:126: Mix.Dep.load_and_cache/5
    (mix) lib/mix/dep.ex:114: Mix.Dep.load_and_cache/0
    (mix) lib/mix/project.ex:396: Mix.Project.deps_paths/1
    lib/app_releases.ex:65: App.Releases.umbrella_deps_paths/0
    lib/app_releases/changes.ex:41: App.Releases.Changes.get_changes_since/1
    lib/app_releases/version.ex:45: App.Releases.Version.next_release_version/1
    lib/mix/tasks/rel.version.bump.ex:35: anonymous fn/1 in Mix.Tasks.Rel.Version.Bump.run/1
    (mix) lib/mix/project.ex:348: Mix.Project.in_project/4
```

**Comment by AndrewDryga** [comment]
I've reset the cache with `mix clean && rm -rf _build` and issue persists.

**Comment by josevalim** [comment]
Can you please provide us a sample app that reproduces the error? Thank you!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Thanks, I have improved the error message. You need to invoke one of "deps.loadpaths", "loadpaths" or "compile" before you can fetch dependency information. Previously it worked by accident and it could potentially return incorrect version about the dependencies (exactly because they were not loaded).

**Comment by AndrewDryga** [comment]
@josevalim is there a function we can run instead of mix task there? We are using `Mix.Project.deps_paths()` within our own mix task which uses `in_project`, so running another mix task on umbrella level won't work.

**Comment by AndrewDryga** [comment]
Even executing `Mix.Tasks.Deps.Loadpaths.run([])` before running `Mix.Project.deps_paths/0` did not help.

**Comment by josevalim** [comment]
@AndrewDryga you have to execute the mix task at the beginning of the task. I.e. at the root, before jumping inside in_project. :)
