### ISSUE TITLE
Typo in GenServer Doc

### ISSUE THREAD

**Issue by raulintosh** [elixir-lang/elixir#8812]
Hi Elixir Team,
In line 138 the text must be "In both cases, Stack.start_link/1 is always invoked.", the word always has a typo.

https://github.com/elixir-lang/elixir/blob/511a51ba8925daa025d3c2fd410e170c1b651013/lib/elixir/lib/gen_server.ex#L138

Thanks for your hard work.
Raul.

**Comment by adkron** [comment]
This appears to be fixed on master. 

https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/gen_server.ex

**Comment by josevalim** [comment]
Thanks @raulintosh and @adkron!
