### ISSUE TITLE
Syntax error when using k => v before k: v in struct in func head inside quote

### ISSUE THREAD

**Issue by chulkilee** [elixir-lang/elixir#8813]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating system: macOS

### Current behavior

SyntaxError when `unquote(k) => v` comes *after* `k: v` in a struct in a function argument.

```elixir
defmodule MyStruct do
  defstruct [:foo, :bar]
end

key = :bar

quote do
  def hello(%MyStruct{foo: nil, unquote(key) => 1}), do: false
end
# => (SyntaxError) syntax error before: unquote
```

### Expected behavior

`quote/2` should not fail. 

Note that it works when `unquote(k) => v` comes *before* `k: v`.

```elixir
defmodule MyStruct do
  defstruct [:foo, :bar]
end

key = :bar

raw =
  quote do
    def hello(%MyStruct{bar: 1, foo: nil}), do: false
  end

with_unquote =
  quote do
    def hello(%MyStruct{unquote(key) => 1, foo: nil}), do: false
  end

raw == with_unquote

raw ==
  {:def, [context: Elixir, import: Kernel],
   [
     {:hello, [context: Elixir],
      [
        {:%, [],
         [
           {:__aliases__, [alias: false], [:MyStruct]},
           {:%{}, [], [bar: 1, foo: nil]}
         ]}
      ]},
     [do: false]
   ]}
```

### Expected behavior

It should not fail in such cases.

**Comment by fertapric** [comment]
The `key: value` shorthand syntax can only be used at the end:

```elixir
iex(1)> %{a: 1, :b => 2}
** (SyntaxError) iex:1: syntax error before: b

iex(1)> %{:a => 1, b: 2}
%{a: 1, b: 2}
```

This is documented in the [`Map` module](https://hexdocs.pm/elixir/Map.html) (but the documentation might be improved):

> When the key in a key-value pair is an atom, the `key: value` shorthand syntax can be used (as in many other special forms), provided key-value pairs are put at the end:
>
>     iex> %{"hello" => "world", a: 1, b: 2}
>     %{:a => 1, :b => 2, "hello" => "world"}

**Comment by josevalim** [comment]
Closing this as @fertapric mentioned. I would love to improve the error message here but unfortunately the parser does not give us a lot of control over it. :(

**Comment by chulkilee** [comment]
Thanks a lot!

I tried to find it from [Structs](https://elixir-lang.org/getting-started/structs.html) page, which says "Structs are extensions built on top of maps that provide compile-time checks and default values." but didn't think about it was limitation of syntax on Map..

Quick thoughts on doc improvement

- introduce "bad example" to Map module doc showing syntax error
- add example of using `=>` in struct guide page

**Comment by josevalim** [comment]
A PR to the Map module would be welcome!

I wouldn’t change the Struct guide though because it is meant to be a
getting started guide and this error would only appear in special
circumstances, as it is unlikely for you to use => in structs.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
