### ISSUE TITLE
mix: follow XDG base dir specification

### ISSUE THREAD

**Issue by NobbZ** [elixir-lang/elixir#8818]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): currently 1.7 and 1.8 (depends on the host) but affects earlier versions as well.
* Operating system: Linux, but maybe affects Mac OS as well

### Current behavior

Mix saves it configuration, downloaded data, archives, etc to `~/.mix`

### Expected behavior

It should follow the [XDG Base Dir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and use appropriate folders from the users configuration to save aforementioned stuff.

This makes it easier for a user to wipe caches, backup config or archives, etc.

This is issue is explicitely about global cache/data/config, not their per-project equivalents.

**Comment by josevalim** [comment]
Can you please send a proposal to the mailing list? In particular, I would
love to hear why we should accept this particular spec, given that it is
not 1.0 yet, how it compares to other specs, and who is already adopting
it. Thank you.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by NobbZ** [comment]
https://groups.google.com/forum/#!topic/elixir-lang-core/7nyDfkgRsI0

**Comment by maennchen** [comment]
Is the idea here to only change the `Mix.Utils.mix_home/1`to consider the `XDG_DATA_HOME` or would a clean implementation also change the location of the following files / folders (those are the ones I found, there may be more):

- `archives` - `${XDG_DATA_HOME:-/usr/local/share/}mix/archives`
- `config.exs` - `${XDG_CONFIG_HOME:-$HOME/.config/}mix/config.exs`
- `rebar` - `${XDG_DATA_DIRS:-/usr/local/share/}mix/bin/rebar`
- `rebar3` - `${XDG_DATA_DIRS:-/usr/local/share/}mix/bin/rebar3`
- `escripts` - `${XDG_DATA_HOME:-/usr/local/share/}mix/bin/escripts`

**Comment by michalmuskala** [comment]
When it comes to implementation, the Erlang's [filename:basedir/3](http://erlang.org/doc/man/filename.html#basedir-3) function might be of interest, that generally does "the right thing" on each OS.

**Comment by maennchen** [comment]
If we'd use the directories as specified, this would also change existing file locations for people that do neither specify `XDG_*` nor `MIX_*` variables.

Would that be considered a breaking change and has to wait for v2?

**Comment by josevalim** [comment]
Thanks @maennchen. I took a deeper look at XDG and I have questions:

1. The `XDG_CONFIG_HOME` does not tell which kind of configuration it is about. For example, is it about manual user configuration or  configuration persisted by the software? All examples I have seen online are a bit vague.

2. The  `_DIRS` variables are about data lookups and we don't plan to introduce the complexity behind said lookups.

Unfortunately we can't fallback to `filename:basedir/3` because that would be backwards incompatible. :(

**Comment by josevalim** [comment]
Here is my suggestion:

1. Change `Mix.Utils.mix_home/1` to consider `XDG_DATA_HOME` after `MIX_HOME`

2. Change whatever loads `~/.mix/config.exs` to consider `XDG_CONFIG_HOME` after `MIX_HOME`

**Comment by maennchen** [comment]
@josevalim 

> The XDG_CONFIG_HOME does not tell which kind of configuration it is about. For example, is it about manual user configuration or configuration persisted by the software? All examples I have seen online are a bit vague.

I experienced the same when I tried to find the correct variable for each directory / file currently  inside of `MIX_HOME`.

> Unfortunately we can't fallback to filename:basedir/3 because that would be backwards incompatible. :(

So then this is basically the idea?

```patch
diff --git a/lib/mix/lib/mix/utils.ex b/lib/mix/lib/mix/utils.ex
index fd12d1c04..fc63503d9 100644
--- a/lib/mix/lib/mix/utils.ex
+++ b/lib/mix/lib/mix/utils.ex
@@ -15,7 +15,11 @@ defmodule Mix.Utils do
   stored there.
   """
   def mix_home do
-    System.get_env("MIX_HOME") || Path.expand("~/.mix")
+    case {System.get_env("MIX_HOME"), System.get_env("XDG_DATA_HOME")} do
+      {directory, _} -> directory
+      {nil, directory} -> Path.join(directory, "mix")
+      {nil, nil} -> Path.expand("~/.mix")
+    end
   end
 
   @doc """

```

**Comment by maennchen** [comment]
@josevalim I'll do a PR.
