### ISSUE TITLE
mix test --cover: total is less than the mathematical average

### ISSUE THREAD

**Issue by Helpys** [elixir-lang/elixir#8825]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 21 [erts-10.2.1]
* Operating system: macOS 10.14.3

### Current behavior

run mix test --cover

Percentage | Module
-----------|--------------------------
   100.00% | Cover.BitString
   100.00% | CoverFixture
-----------|--------------------------
    33.33% | Total

The total is less than expected. I think the problem is with the protocol. The file "Cover" itself is not listet.

https://github.com/Helpys/coverfixture

### Expected behavior

Percentage | Module
-----------|--------------------------
   100.00% | Cover.BitString
   100.00% | CoverFixture
-----------|--------------------------
    100.00% | Total

**Comment by PragTob** [comment]
:wave: I stumbled upon this in the forum and thought it'd be a fun thing to fix. I have the basic test setup ready here (incorporating the provided sample): https://github.com/PragTob/elixir/tree/protocol-cover-issue-8825

I'm in a train though so Internet is spotty and if I don't finish it before I arrive in Berlin/get too tired it's unlikely that I'll get to it before next weekend.

**Comment by josevalim** [comment]
Closed in favor of #8828 and #8826.
