### ISSUE TITLE
offline installer

### ISSUE THREAD

**Issue by cup** [elixir-lang/elixir#8831]
when i go here:

https://elixir-lang.org/install#windows

i only get an option for the web-based installer:

https://repo.hex.pm/elixir-websetup.exe

however other languages offer "offline installer", for example python:

https://python.org/downloads/release/python-372/

**Comment by josevalim** [comment]
Hi @cup! You can do a feature request in the installer here: https://github.com/elixir-lang/elixir-windows-setup/.

Also note that if you want to automate this installation, you can also use the [precompiled package](https://elixir-lang.org/install.html#precompiled-package). It should be a matter of unzipping and adding it to your $PATH.

Thanks!

**Comment by cup** [comment]
hm it seems elixir relies on the erlang binary?

**Comment by josevalim** [comment]
Yes, but if Erlang is already installed, it skips the Erlang step.
