### ISSUE TITLE
`@impl`-tagged function invisible in IEx autocomplete

### ISSUE THREAD

**Issue by davidsulc** [elixir-lang/elixir#8835]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.7.2 (compiled with Erlang/OTP 20)

* Operating system: 
Linux 4.15.0-45-generic #48-Ubuntu SMP x86_64

### Context

```
defmodule Foo do
  @callback func(a :: any, b :: any) :: any
end

defmodule Implementation do
  @behaviour Foo

  @impl Foo
  def func(_, _), do: :func
end
```

### Current behavior

In IEx, typing `Implementation.` followed by "tab" offers no autocompletion. However, if the `@impl Foo` line is removed, autocompletion for `Implementation.func` happens as expected. Note that autocompletion also fails if the line is changed instead to `@impl true`.

### Expected behavior

IEx should be able to autocomplete behaviour callback implementations even when tagged with `@impl`.

### Potentially related issue

I have not been able to reproduce a minimal case for this problem, but it appears it could be related.

Context:
* app `A` in an umbrella
* module `A` defines a behaviour with a single callback `bar`
* module `A.Foo` implements the `A` behaviour (and therefore an implementation of `bar`)
* app `B` in same umbrella, depends on `A`
* function in module `B` calls `A.Foo.bar` (the behaviour function implemented in `A.Foo`)

When running dialyzer for app `B`, an error is returned saying that `A.Foo.bar` doesn't exist, even though it's successfully called during execution of the `B` app.

**Comment by wojtekmach** [comment]
That's by design, `@impl true` adds `@doc false` which makes it not show up in IEx (and ExDoc etc)

**Comment by josevalim** [comment]
As explained by @wojtekmach, `@impl` marks it as doc false and nothing that is doc false shows in the autocomplete.
