### ISSUE TITLE
File.Stat struct declares atime, ctime, and mtime as type :calendar.datetime() but they can be integer()

### ISSUE THREAD

**Issue by akappen** [elixir-lang/elixir#8838]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)
```

* Operating system: 
```
Linux - Kernel 4.18.0
```

### Current behavior

When `File.stat()` is called with the `time: :posix` option it returns a `File.Stat` struct with integer values for `atime`, `ctime`, and `mtime`.

```
{:ok, info} = File.stat("/file.txt", time: :posix)
{:ok,
 %File.Stat{
   access: :read_write,
   atime: 1548343720,
   ctime: 1538148152,
   gid: 1000,
   inode: 789497,
   links: 1,
   major_device: 2053,
   minor_device: 0,
   mode: 33188,
   mtime: 1538148152,
   size: 6,
   type: :regular,
   uid: 1000
 }}
```

Without the `time: :posix` option it returns an Erlang `{date, time}` tuple:

```
{:ok, info} = File.stat("/file.txt")              
{:ok,
 %File.Stat{
   access: :read_write,
   atime: {{2019, 1, 24}, {15, 28, 40}},
   ctime: {{2018, 9, 28}, {15, 22, 32}},
   gid: 1000,
   inode: 789497,
   links: 1,
   major_device: 2053,
   minor_device: 0,
   mode: 33188,
   mtime: {{2018, 9, 28}, {15, 22, 32}},
   size: 6,
   type: :regular,
   uid: 1000
 }}
```

The type declaration on `File.Stat` defines these as strictly `:calendar.datetime()` which is causing type checking to misbehave.

### Expected behavior

The type definition for `File.Stat` should be loosened to also allow integer values for `atime`, `ctime`, and `mtime`.

Thanks!

**Comment by akappen** [comment]
I'm not sure how or where to add tests against type related issues. Let me know what I should add.

Thanks!

**Comment by josevalim** [comment]
We don't test the types themselves. Fixing the definition is enough. :)
