### ISSUE TITLE
Supervisor.start_link/2 documentation incomplete?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [elixir-lang/elixir#8845]
Env
----

Elixir 1.8.1
https://hexdocs.pm/elixir/Supervisor.html#start_link/2

Background
----

I am trying to build an OTP compliant app using supervisors. However I was having trouble interpreting a part of the documentation.

Docs
---

The documentation states that [Supervisor.start_link/2](https://hexdocs.pm/elixir/Supervisor.html#start_link/2) returns the following:

```
{:ok, pid}
| :ignore 
| {:error, {:already_started, pid} | {:shutdown,term} | [term]}
```

Problem
---

The problem is that even though the documentation specifies when start_link returns `{:ok, pid}` and `{:error, any}` it doesn’t specify when it returns `:ignore`, leaving me to think that it can never return :ignore.

Research
----

After a lengthy discussion in the forums, it was finally made clear when this can happen:

https://elixirforum.com/t/supervisor-start-link-2-documentation-incomplete/20510

However this use case is not documented in the official HexDocs.

I suggest a PR with the intention of updating the dos to make it clear when `Supervisor.start_link/2` can return `:ignore`

**Comment by josevalim** [comment]
.start_link/2 itself cannot return `:ignore` (but start_link/3 can). So I would update its typespec. :) PR please?

**Comment by Fl4m3Ph03n1x** [comment]
> .start_link/2 itself cannot return `:ignore` (but start_link/3 can).

This is so confusing. Specially because in the forums someone came up with an example where start_link/2 does return ignore:

https://elixirforum.com/t/supervisor-start-link-2-documentation-incomplete/20510/10?u=fl4m3ph03n1x

So which one is it?

**Comment by josevalim** [comment]
I made the same confusion  as @sasa1977 in that thread, it can return `:ignore`. I will push a fix.

**Comment by Fl4m3Ph03n1x** [comment]
If the fix is only regarding documentation, perhaps I can help out with a PR that includes the code snippet demonstrated in the forums. This way you can focus on other things. What do you think?

**Comment by josevalim** [comment]
Although it is worth noting the spec matches on the list input. For that input, then it cannot return :ignore.

**Comment by Fl4m3Ph03n1x** [comment]
Do you need a PR for the documentation or will you handle it in another way? (do you need my help on this or are you fine on your own?)
