### ISSUE TITLE
How to set defaults for releases

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#8861]
Now that #8677 has been merged, we need to talk about providing default values for releases.

Today, we can configure multiple releases like this in the mix.exs:

```elixir
releases: [
  demo_foo: [
    ...
  ],
  demo_bar: [
    ...
  ]
]
```

The issue is that, if you want to use the same configuration value in `demo_foo` and `demo_bar`, it has to be duplicated in both.

We should discuss a mechanism for providing default values for configuration. I can see two approaches:

1. Have a special `defaults` key inside `releases` that is merged but not a release per se:

```elixir
releases: [
  demo_foo: [
    ...
  ],
  demo_bar: [
    ...
  ],
  defaults: [
    ...
  ]
]
```

This approach is nice because everything is under the release key. The downside though is that `defaults` can be confused by an actual release name.
 
2. Have a key, outside of releases, called `releases_defaults`, that holds all of the defaults. This means releases configuration is now spread across multiple keys, but the ambiguity from one is removed.

Any other options or further considerations?

**Comment by maennchen** [comment]
Why should elixir provide a way for that if the user can just do this?

```elixir
defaults = [
  # define defaults
]

[
  releases: [
    demo_foo: Keyword.merge(defaults, [
      # define properties for foo
    ]),
    demo_bar: Keyword.merge(defaults, [
      # define properties for bar
    ]),
  ]
]
```

**Comment by josevalim** [comment]
Good call @maennchen! I think a more concise way can be worth it if it has to be done frequently but since we have a reasonably good alternative for now, let's go with that.
