### ISSUE TITLE
build_embedded: true deleting generated files 

### ISSUE THREAD

**Issue by ConnorRigby** [elixir-lang/elixir#8878]
### Environment

```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

### Current behavior

setting `build_embedded: true` while _also_ having files in the `priv` dir of a project will cause files generated in `priv` to be deleted.

I made a sample repo as an [example](https://github.com/ConnorRigby/elixir-build-embedded-bug)

I tracked it down to `lib/mix/lib/mix/project.ex` [here](https://github.com/elixir-lang/elixir/blob/da3c426478b8e30d54942f62058058a47283a718/lib/mix/lib/mix/project.ex#L639-L653)

### Expected behavior

I would expect that files generated into `priv` aren't deleted when `build_embedded` is set to `true`

**Comment by josevalim** [comment]
I am not sure if we can fix this. Build_embedded is meant to mirror what is
in the project “priv” with the build “priv”, so anything extra will be
deleted, because we would think it was deleted from the project “priv”.

I understand there is an issue we want to address here though, which is to
have self managed priv directories?

Can you remind me what would happen if you wrote to the project priv
instead of the build priv? The problem is what would happen when you change
targets right? What if you write to the project priv with the target as
directory?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by ConnorRigby** [comment]
> The problem is what would happen when you change targets right?

This is correct. 

> What if you write to the project priv with the target as directory?

I've thought of this as well, but the problem is 
1) there is a step in the Nerves firmware bundler that checks for all shared object files and ensures that they are the correct architecture (even if they aren't used). This one can probably be solved without too much work
2) Keeping many target's versions of the assets would be quite a waste of precious space.

**Comment by josevalim** [comment]
@ConnorRigby let's take one extra step back then: why is build_embedded necessary? can you remove priv, remove build_embedded and make sure that everything that needs to be in `priv` is copied at some point? This would be the way to "self-manage" priv. Thoughts?

**Comment by ConnorRigby** [comment]
I don't think `build_embedded` is _required_. It has some nice features and the docs and new project generator say to set it to `true` because in the past this fixed a different bug that i think has since been fixed with elixir 1.8 and elixir_make 0.5. 

My solution for now is to **not** have a root `priv` directory, and have `elixir_make` copy and build files there for it to be copied. The only problem with this is that i have some large-ish files in my `priv` so it takes a bit of time to copy them to the priv directory, then copy them again into the build directory, then maybe once more to the release directory if i'm not mistaken.

**Comment by josevalim** [comment]
Right. My suggestion is to copy them directly to the build priv directory
and skip the project one altogether. Would that work?
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by ConnorRigby** [comment]
yep i think that would work as well as skip one copy step.

**Comment by josevalim** [comment]
Ok, pls let me know how it goes then!

**Comment by josevalim** [comment]
Ping! I believe this can be closed?

**Comment by ConnorRigby** [comment]
i believe it can be closed, however issues still persist in other forms. I will open another issue when i have more information.

**Comment by lnikkila** [comment]
@ConnorRigby In case you're still interested in this, I think elixir_make might be causing similar behaviour. Link above
