### ISSUE TITLE
Elixir 1.8.1 crashes after install on OpenSuse Leap 15

### ISSUE THREAD

**Issue by CyborTronik** [elixir-lang/elixir#8886]
Just did a fresh installation of opensuse leap 15 and elixir.

Did as in documentation and got installed elixir 1.8.1 (there are available `1.8.1-12.8 and `1.8.1-12.7` only) and erlang `20.3.8.15-lp150.2.3.4` (max available).

Getting next error when run `iex`:``` "beam/beam_load.c(1863): Error loading module 'Elixir.IEx.CLI':\n  This BEAM file was compiled for a later version of the run-time system than 20.\n  To fix this, please recompile this module with an 20 compiler.\n  (Use of opcode 162; this emulator supports only up to 159.)\n"```

So there are 2 points: 

* Documentation says elixir 1.8 supports erlang/OTP 20/21
* There are no way to install a working elixir/erlang version in OpenSUSE Leap 15 by `zypper` so it breaks `usability` for newbies or someone who wants to give a try.

**Comment by josevalim** [comment]
Hi @CyborTronik, thanks for the report!

We are not the ones who maintain the distributions, there are too many OSes and distributions for that to be our responsibility. I recommend you to ping whoever is responsible for maintaining those packages, there is probably enough information in the package manager.

Note that on OpenSuse you can also try the Erlang Solutions repo: https://elixir-lang.org/install.html#unix-and-unix-like

There are also many [version managers you could use to do the installation for you](https://elixir-lang.org/install.html#compiling-with-version-managers), I believe `asdf` is the most common one. You can also always compile from source and it is relatively straight-forward.
