### ISSUE TITLE
Doctest error messages could display the actual doctest code

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#8889]
When a doctest fails, ExUnit generates the following sort of error message:

    1) doctest Foo.Bar.baz/1 (13) (Foo.BarTest)
       test/foo/views/_bar_test.exs:5
       Doctest failed
       code:  1 === 2
       left:  1
       right: 2
       stacktrace:
         lib/foo/views/_bar_helpers.ex:171: Foo.BarHelpers (module)

Unfortunately, the "code" has been modified to the point that it no longer resembles the test lines. I can use a text editor to view the relevant lines (171, et al), but this seems tedious. So, I'd like ExUnit to show the actual doctest code instead, eg:

    1) doctest Foo.Bar.baz/1 (13) (Foo.BarTest)
       test/foo/views/_bar_test.exs:5
       Doctest failed
       code:
         iex> 1
         2
       left:  1
       right: 2
       stacktrace:
         lib/foo/views/_bar_helpers.ex:171: Foo.BarHelpers (module)

Alternatively, it could show both versions, as a way to help the programmer figure out where the test went awry:

    1) doctest Foo.Bar.baz/1 (13) (Foo.BarTest)
       test/foo/views/_bar_test.exs:5
       Doctest failed
       doctest:
         iex> 1
         2
       code:  1 === 2
       left:  1
       right: 2
       stacktrace:
         lib/foo/views/_bar_helpers.ex:171: Foo.BarHelpers (module)

**Comment by ryanwinchester** [comment]
Would this show some preceding lines on a multi-line doctest or just the last line for comparison?

**Comment by RichMorin** [comment]
> On Mar 13, 2019, at 10:12 AM, Ryan Winchester <notifications@github.com> wrote:
> 
> Would this show some preceding lines on a multi-line doctest or just the last line for comparison?

Each doctest is supposed to be separated from its neighbors in the @doc text,
so I think it would make sense to display the entire doctest.

-r

**Comment by josevalim** [comment]
Let’s start simple for now and show the IEx line that led to the assertion.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by RichMorin** [comment]
I was wondering whether only displaying "the IEx line that led to the assertion" would leave out useful context, so I tried an experiment:

    iex> a = "This is an egregiously long text string."
    iex> b = ~r{an egregiously long}
    iex> c = "a slightly shorter"
    iex> String.replace(a, b, c) 
    "This is a much shorter text string."

Here is the relevant output:

     Doctest failed
     code:  a = "This is an egregiously long text string."
             b = ~r{an egregiously long}
             c = "a slightly shorter"
             String.replace(a, b, c) === "This is a much shorter text string."
     left:  "This is a slightly shorter text string."
     right: "This is a much shorter text string."

It displays the "code", but not in doctest format. Also, it mangles the indentation slightly.

**Comment by josevalim** [comment]
Yes, apologies, I meant to say the direct IEx lineS that led to the
assertion. That’s because you may have iex>+assertion+iex>+iex>+assertion.
So for the first assertion is one iex> line, for the second is two.

Basically what we do today, but we will keep the original code.

-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Hanspagh** [comment]
I started on this [here](https://github.com/Hanspagh/elixir/tree/doctest-show-code), but I am not quite sure what you mean by keep the original code?

**Comment by ryanwinchester** [comment]
@Hanspagh, I think he means, keeping the doctest code the same as it was written in the doctest.

Example using the above example:

```
Doctest failed
 code:  iex> a = "This is an egregiously long text string."
        iex> b = ~r{an egregiously long}
        iex> c = "a slightly shorter"
        iex> String.replace(a, b, c)
        "This is a much shorter text string."
 left:  "This is a slightly shorter text string."
 right: "This is a much shorter text string."
```

**Comment by josevalim** [comment]
Let's continue the discussion on #8903. Most of the work is done, just two open questions remaining!
