### ISSUE TITLE
ExUnit sync tests do not wait for linked process to terminate before starting next sync test

### ISSUE THREAD

**Issue by kelostrada** [elixir-lang/elixir#8892]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 21 [erts-10.2.3] Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating system: macOS Mojave 10.14.3

### Current behavior

Whenever you run synchronous tests the process which is linked to the test is killed after the test is over. However sometimes (very rare) the process which was linked might not get killed before the next test begins.

I've prepared a simple test which will demonstrate the behaviour (sometimes):

```elixir
defmodule ExUnitLinksTest do
  use ExUnit.Case, async: false

  defmodule TestGenServer do
    use GenServer

    def start_link(_opts), do: GenServer.start_link(__MODULE__, :ok, name: __MODULE__)

    def init(:ok) do
      {:ok, []}
    end
  end

  for i <- 1..3_000 do
    test "Test links #{i}" do
      {:ok, _pid} = TestGenServer.start_link([])
    end
  end
end
```

I run the tests in a bash loop so there is a higher chance of seeing the issue:

```bash
while :; do mix test; done
........

  1) test Test links 787 (ExUnitLinksTest)
     test/ex_unit_links_test.exs:15
     ** (MatchError) no match of right hand side value: {:error, {:already_started, #PID<0.1937.0>}}
     code: {:ok, _pid} = TestGenServer.start_link([])
     stacktrace:
       test/ex_unit_links_test.exs:16: (test)

...............

Finished in 1.5 seconds
3000 tests, 1 failure
```

### Expected behavior

It would be preferred if the tests are synchronous that they will wait for all spawned linked processes to be killed before begining the rest of the tests. Please correct me if I'm wrong about this assumption.

**Comment by josevalim** [comment]
This is quite hard to guarantee in practice because processes can be linked and crashed at any time and there is no way ExUnit can intervene. If you want to guarantee a process terminates when the test terminates, then use `start_supervised`, to start the process in a tree managed by ExUnit or the `on_exit` callback.
