### ISSUE TITLE
Windows web installer - index out of bounds error

### ISSUE THREAD

**Issue by stevewest** [elixir-lang/elixir#8901]
![elixir-windows-web-installer-failted](https://user-images.githubusercontent.com/41179502/54499321-1f275100-495c-11e9-8042-acc72ed7b9a6.PNG)

### Environment

* Elixir & Erlang/OTP versions (elixir --version):  Windows web-installer
* Operating system: Windows 10 Enterprise 10.0.15063 Build 15063 x64-based PC i5-6500

### Current behavior

Clicking download link on https://elixir-lang.org/install.html#windows. The file downloads no problems. When running this installer and giving permission to make changes to the computer, then the error message appears - list index out of bounds.

### Expected behavior

Elixir installed and available via command line prompt.

Many thanks for looking into this.

**Comment by josevalim** [comment]
Are you running behind a proxy? Have you tried running on another Windows
machine just in case? Just checking if it is a specific issue or a general
one.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by stevewest** [comment]
Hello Jose
Yes, it all worked fine on my home machine but at work I am behind a proxy.

**Comment by josevalim** [comment]
Thanks! Unfortunately this is a known bug in https://github.com/elixir-lang/elixir-windows-setup. We will continue tracking it there!

**Comment by sergiomonteiro** [comment]
I solved this problem installing via Chocolatey.
