### ISSUE TITLE
doctest parsing can't handle newlines in text strings

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#8906]
When I try to use a string containing a newline in a doctest, eg:

    iex> test     = ~s(foo\nbar)

I get the following nastygram:

    == Compilation error in file test/phx_http_web/views/search_test.exs ==
    ** (ExUnit.DocTest.Error) lib/phx_http_web/views/search_view.ex:42:
      indentation level mismatch on doctest line: "bar)"
    ...

If I use the following syntax:

    iex> test     = "foo\nbar"

I get a similar message:

    == Compilation error in file test/phx_http_web/views/search_test.exs ==
    ** (ExUnit.DocTest.Error) lib/phx_http_web/views/search_view.ex:42:
    indentation level mismatch on doctest line: "bar\""
    ...

**Comment by josevalim** [comment]
That's because you are introducing a literal new line since the doctest is in another string:

```elixir
@doc """
  iex> test     = ~s(foo\nbar)
"""
```

You need to either escape the new line with `\\n`:


```elixir
@doc """
  iex> test     = ~s(foo\nbar)
"""
```

Or use the `~S` sigil to disable escape characters:


```elixir
@doc ~S"""
  iex> test     = ~s(foo\nbar)
"""
```

**Comment by RichMorin** [comment]
Thanks for the explanation. I can certainly add another backslash to get around this problem, but it seems awkward and potentially confusing to modify my actual IEx code to make it work in the doctest. Using the `~S"""..."""` syntax seems cleaner to me, but I worry that it could keep me from using a newline elsewhere in the doctest. Sigh.

BTW, I think your second example may need another backslash, eg:

    @doc """
      iex> test     = ~s(foo\\nbar)
    """
