### ISSUE TITLE
Capital word in module attributes

### ISSUE THREAD

**Issue by Ljzn** [elixir-lang/elixir#8907]
### Precheck

[origin proposal](https://groups.google.com/forum/#!topic/elixir-lang-core/2RHCgsoOnAw)

### Environment

Erlang/OTP 21 [erts-10.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 20)

### Current behavior

```ex
defmodule M do
  
  Module.put_attribute(__MODULE__, :A, 1)

  IO.inspect @A
end
```

iex -S mix
```shell
Compiling 1 files (.ex)
:ok
warning: module attribute @__aliases__ was set but never used
  lib/m.ex:5
```

### Expected behavior

Raising an error when trying to use capital word in module attribute (maybe better error type and message):
```
** (ArgumentError) module attributes cannot start with an uppercase letter
```

or support capital word in module attributes, could just ignore alias.

**Comment by edisonywh** [comment]
Hey can I work on this? Would appreciate some pointers too!

**Comment by josevalim** [comment]
Yes, please go ahead. The fix is most likely adding a clause to `defmacro @` in Kernel like this:

```
defmacro @{:__aliases__, _, _} do
  raise ArgumentError, "..."
end
```

And adding a proper test.

**Comment by edisonywh** [comment]
I don't think the error is with the `@` syntax, but rather `Module.put_attribute`.

If you try to assign an uppercase attribute currently with the `@` syntax, it throws a syntax error:

```elixir
  @A 5
```
> ** (SyntaxError) module.exs:3: syntax error before: "5"`

**Comment by josevalim** [comment]
Passing an argument to `@A` is a separate error because it has another AST. There is nothing wrong with `Module.put_attribute(..., :A, ...)` but you have to keep in mind that you then need to access it as ``Module.get_attribute(..., :A)`.

**Comment by edisonywh** [comment]
Cool, so we're not actually disallowing setting it as capital, got it!

In that case, feel free to check out my PR :) #8908
