### ISSUE TITLE
Compilation error in OTP-22: (BadFunctionError) expected a function, got: :guard

### ISSUE THREAD

**Issue by essen** [elixir-lang/elixir#8909]
Hello,

Environment:

OTP-22 (master as of today)
either Elixir 1.7.4 (compiled with Erlang/OTP 21)
or Elixir 1.8.1 (compiled with Erlang/OTP 21)

The following module fails to compile at the moment: https://github.com/rabbitmq/rabbitmq-cli/blob/master/lib/rabbitmq/atom_coerce.ex

The error I get is:

```
== Compilation error in file lib/rabbitmq/atom_coerce.ex ==
** (BadFunctionError) expected a function, got: :guard
   (elixir) expanding macro: Kernel.in/2
   lib/rabbitmq/atom_coerce.ex:17: Rabbitmq.Atom.Coerce (module)
   (elixir) expanding macro: Kernel.||/2
   lib/rabbitmq/atom_coerce.ex:17: Rabbitmq.Atom.Coerce (module)
   (elixir) expanding macro: Protocol.def/1
   lib/rabbitmq/atom_coerce.ex:17: Rabbitmq.Atom.Coerce (module)
```

Also seen this same error with a module in `parallel_stream`:

```
== Compilation error in file lib/parallel_stream/filter.ex ==
** (BadFunctionError) expected a function, got: :guard
    (elixir) expanding macro: Kernel.in/2
    lib/parallel_stream/filter.ex:20: ParallelStream.Filter.Consumer.build!/2
    (elixir) expanding macro: Kernel.!/1
    lib/parallel_stream/filter.ex:20: ParallelStream.Filter.Consumer.build!/2
    (elixir) expanding macro: Kernel.|>/2
    lib/parallel_stream/filter.ex:16: ParallelStream.Filter.Consumer.build!/2
    (elixir) expanding macro: Kernel.|>/2
    lib/parallel_stream/filter.ex:15: ParallelStream.Filter.Consumer.build!/2
```

Compiles fine under OTP-21.

**Comment by josevalim** [comment]
Thanks for the report!

There may be bugs hidden in Erlang/OTP master so we will give it a try, but generally speaking we don't guarantee compatibility with unreleased Erlang/OTP versions!

**Comment by essen** [comment]
Yeah no worries we just started fixing RabbitMQ for OTP-22 earlier than usual.

**Comment by josevalim** [comment]
@essen so I can confirm that Elixir compiled on OTP 21 does not work on OTP 22 but Elixir compiled with OTP 22 does work on 22. This is possibly a backwards incompatible change on BEAM bytecodes. :(

**Comment by josevalim** [comment]
Bug reported on OTP with a minimal case here: https://bugs.erlang.org/browse/ERL-899

**Comment by michaelklishin** [comment]
@josevalim thank you for reporting a minimal case to the OTP team.

Not to sound patronizing but how should products that use Elixir test against OTP preview releases then? I'm afraid some RabbitMQ users will begin installing OTP 22 the day it ships regardless of what the docs say. So the only option for us is to conduct testing as soon as rc-0 drops.

I understand that it takes time and effort but it would greatly benefit both Erlang and Elixir users if this policy of not testing previews of major releases was reconsidered.

**Comment by josevalim** [comment]
@michaelklishin I said we do not **guarantee compatibility** against **master**. But our CI runs against master and we do test the RCs as soon as they are out.

**Comment by josevalim** [comment]
To further clarify: we do our best-effort to spot bugs early on but if you want to run against master, we don't guarantee Elixir will work as we won't test against every commit in master. If it is released (including pre-releases), then we support it barring bugs upstream (for example, we did not support one of the RCs for Erlang/OTP 21 due to an upstream bug that was reported and later fixed). Sometimes supporting a new Erlang/OTP version also requires a new Elixir version.

**Comment by josevalim** [comment]
Sorry, one last note 😛: regardless if Elixir guarantees those compatibilities, please do "conduct testing as soon as rc-0 drops". As you are correct that it can help both Erlang and Elixir too.

**Comment by michaelklishin** [comment]
Alright, I must have misunderstood your comment. We usually start testing around rc-0 but have plans to revive testing against daily builds of [OTP] master. Maybe we should add Elixir master, too.

**Comment by josevalim** [comment]
Against Elixir master would be great too, thank you!
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*
