### ISSUE TITLE
Formatter should add an empty line before doctest-like code if it finishes the string

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#8914]
```
  @doc """
  ## Examples
      iex> List.last([])
      nil
      iex> List.last([1])
      1
  """

should be formatted to

  @doc """
  ## Examples
      iex> List.last([])
      nil
      iex> List.last([1])
      1

  """
```
We have corrected this in the entire Elixir-core base, but I cannot find the commit.

See @whatyouhide  for reference: 
https://github.com/elixir-lang/elixir/pull/8912/files#r269757967

**Comment by josevalim** [comment]
The formatter cannot change the semantics of the code. Changing the contents of a string would violate this important formatter rule.

**Comment by eksperimental** [comment]
So true and I missed it.
