### ISSUE TITLE
Tree-Sitter grammar parser for Elixir

### ISSUE THREAD

**Issue by reaysawa** [elixir-lang/elixir#8917]
https://tree-sitter.github.io/tree-sitter/#available-parsers

It seems like Elixir is not in the roadmap for language support.

Atom has the most complete implementation currently. I expect other editors (e.g. Vim, VSCode, Emacs, etc...) to follow in adoption when the API stabilizes and more bugs are fixed.

Project: https://github.com/tree-sitter/tree-sitter
Neovim: https://github.com/neovim/neovim/pull/9219
Emacs: https://github.com/karlotness/tree-sitter.el
VSCode: https://github.com/Microsoft/vscode/issues/50140

[Example grammar for Javascript](https://github.com/tree-sitter/tree-sitter-javascript)

**Comment by whatyouhide** [comment]
Hey @reaysawa, we reserve the issue tracker for issues or bugs in the language. For proposals we usually go to the [elixir-core mailing list](https://groups.google.com/forum/#!forum/elixir-lang-core) and for discussions we go to the [Elixir Forum](https://elixirforum.com). Thanks! 💟
