### ISSUE TITLE
Cannot override an umbrella dependency

### ISSUE THREAD

**Issue by AnilRedshift** [elixir-lang/elixir#8922]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): elixir --version
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating system: OSX

### Current behavior

In an umbrella, try to change the env of a sibling project, and override the dependency. This fails:
```
 defp deps do
    [
      {:a, in_umbrella: true, env: :test, override: true}
    ]
end
```

### Repro steps

You can see a small working demo here:
The only interesting non-boilerplate file is [apps/b/mix.exs](https://github.com/AnilRedshift/demo_umbrella_bug/blob/master/apps/b/mix.exs)

1. checkout https://github.com/AnilRedshift/demo_umbrella_bug

1. run `mix deps.get`

> Dependencies have diverged:
> * a (apps/a)
>   the dependency a in mix.exs is overriding a child dependency:
> 
>   > In mix.exs:
>     {:a, [path: "apps/a", from_umbrella: true, env: :dev]}
> 
>   > In apps/b/mix.exs:
>     {:a, [path: "../a", in_umbrella: true, env: :test, override: true]}
> 
>   Ensure they match or specify one of the above in your deps and set "override: true"
> ** (Mix) Can't continue due to errors on dependencies

### Expected behavior

I would expect that the override should work and the `:a` app would be run with the :test environment
As to the motivation behind this: When running dependency b in test mode, I want to run dependency a in dev mode, for testing to work properly. (The demo project doesn't do this exactly, since I wanted to make the simplest repro possible)

I do see https://github.com/elixir-lang/elixir/issues/8642 but that was talking about overriding an external dependency. Also @josevalim indicates that it should work in that bug, hence this new issue.

At the very least, the output could be improved to say that this isn't expected to work, if this indeed is a wont-fix.

**Comment by josevalim** [comment]
The reason why it can't work is because from the umbrella, you don't know that `b` depends on `a` and there is no guarantee the order the dependencies are loaded.

Luckily in this case we can detect when raising an error and provide a better error message.
