### ISSUE TITLE
Protocol consolidation no match of right hand side value: {:debug_info_v1, :elixir_erl, :none}

### ISSUE THREAD

**Issue by smpallen99** [elixir-lang/elixir#8923]
Elixir 1.8.1
Erlang 21.3.2
Centos 6

Project (> 600 .ex files) compiles fine on Elixir 1.7.4. After installing 1.8.1, I'm getting the following exception for many protocols:

```
04:09:53.541 [error] Task #PID<0.18513.0> started from #PID<0.107.0> terminating
** (MatchError) no match of right hand side value: {:debug_info_v1, :elixir_erl, :none}
    (elixir) lib/protocol.ex:316: Protocol.beam_protocol/1
    (elixir) lib/protocol.ex:305: Protocol.consolidate/2
    (mix) lib/mix/tasks/compile.protocols.ex:141: Mix.Tasks.Compile.Protocols.consolidate/4
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<9.45181099/0 in Mix.Tasks.Compile.Protocols.consolidate/6>
    Args: []
```

The following protocols are failing with the exception:
* Pigeon.Encodable,
* Ecto.Queryable,
* Ecto.DataType,
* Plug.Exception,
* Coherence.DbStore,
* Pigeon.Configurable,
* Phoenix.Param,
* Phoenix.HTML.FormData,
* Phoenix.HTML.Safe,

Error  does not happen with a sample project on the same server. This is a commercial project, so I'm unable to provide the source, but I'll provide more information as requested.

**Comment by josevalim** [comment]
The only chance this can happen is if the protocols are not being compiled with debug_info or debug_info is being stripped. Since this is a commercial project, could that be the case? If so, please make sure those are not stripped for protocols.

**Comment by josevalim** [comment]
Nevermind, I found the bug. :)

**Comment by smpallen99** [comment]
That fixed it! Thanks @josevalim. Awesome response time!
