### ISSUE TITLE
Floats don't round as expected

### ISSUE THREAD

**Issue by relistan** [elixir-lang/elixir#8930]
### Environment

* Elixir 1.7.4 (compiled with Erlang/OTP 21), Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating system: macOS 10.13.6

### Current behavior

```
iex(1)> Float.round(5.55, 0)
6.0
iex(2)> Float.round(5.55, 1)
5.5
Float.round(5.55000000001, 1)
5.6
```
### Expected behavior

I would expect `5.55` to round up to `5.6`, especially when `5.55` rounds up to `6` when no decimals are retained. I believe this is a different issue than #3400 .

cc @rolandtritsch who reported it to me

**Comment by josevalim** [comment]
@relistan is some information missing from the report? Or I am missing something. :) Can you please fill in the values below, as you would expect them:

```iex
iex(1)> Float.round(5.55, 0)
???
iex(2)> Float.round(5.55, 1)
???
iex(3)> Float.round(5.55000000001, 1)
???
```

**Comment by josevalim** [comment]
Oh, I see, you were expecting this:

```iex
iex(2)> Float.round(5.55, 1)
5.6
```

**Comment by relistan** [comment]
@josevalim, yes, sorry I tried to explain it better in the "Expected Behavior" section rather than just changing the value in the output.

**Comment by josevalim** [comment]
So this is actually working as intended. The Important thing to remember is that floats are never what you see. 5.55 is not an actual float. In memory, it is encoded to the closest float to 5.55 and that float is actually `5.5499999...`!

If we actually perform the division by hand, we will see the third digit is 4. First let's represent the float as a ratio:

```elixir
iex(8)> Float.ratio 5.55
{6248744482976563, 1125899906842624}
```

Now let's compute the digits:

```elixir
# first digit
iex> 6248744482976563 |> div(1125899906842624)
5
# second digit
iex> 6248744482976563 |> rem(1125899906842624) |> Kernel.*(10) |> div(1125899906842624)         5
# third digit
iex> 6248744482976563 |> rem(1125899906842624) |> Kernel.*(10) |> rem(1125899906842624) |> Kernel.*(10) |> div(1125899906842624)
4
``` 

To make things more confusing, the floats are never printed as they actually are in memory in most languages, including Elixir, as that would be too verbose. So even if  you write `5.5499999999999998`,  it will be rounded to 5.55 as that is the smallest way you can represent that float anyway.

**Comment by relistan** [comment]
@josevalim Ok, thanks for the explanation. For reference, Go, Ruby, and Haskell all round 5.55 up to 5.6. If the representation in memory is, as you explained `5.5499999...` then why do we get:
```
Float.round(5.55, 0)
6.0
```

Shouldn't that then round down as well?

**Comment by relistan** [comment]
@josevalim Thanks for the detailed explanation
