### ISSUE TITLE
Error in Enum.min/2 documentation

### ISSUE THREAD

**Issue by Maultasche** [elixir-lang/elixir#8935]
As of Elixir 1.8.1, the documentation for Enum.min/2 is incorrect. It states that "If multiple elements are considered minimal, the first one that was found is returned." This is incorrect. The *last* minimal element is returned.

Here's an example from iex.

iex> min(1, 1.0)
1
iex> min(1.0, 1)  
1.0
iex> Enum.min([1, 1.0])
1.0
iex> Enum.min([1.0, 1])  
1

**Comment by josevalim** [comment]
Yes, you are correct. Good catch. Can you  please submit a PR that fixes the docs? Thank you.

**Comment by Maultasche** [comment]
Yes, I'm working on that now. :)

**Comment by Maultasche** [comment]
This has been fixed in pull request #8937

**Comment by whatyouhide** [comment]
Closing in favour of the PR.
