### ISSUE TITLE
Error in Enum.max/2 documentation

### ISSUE THREAD

**Issue by Maultasche** [elixir-lang/elixir#8936]
As of Elixir 1.8.1, the documentation for Enum.max/2 is incorrect. It states that "IIf multiple elements are considered maximal, the first one that was found is returned." This is incorrect. The *last* maximal element is returned.

Here's an example from iex.

iex> max(1, 1.0)
1
iex> max(1.0, 1)
1.0
iex> Enum.max([1, 1.0])
1.0
iex> Enum.max([1.0, 1])
1

**Comment by Maultasche** [comment]
Working on a PR to fix this issue.

**Comment by Maultasche** [comment]
This has been fixed in pull request #8937

**Comment by whatyouhide** [comment]
Closing in favour of the PR.
