### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by houmanka** [elixir-lang/elixir#8948]
Hi guys,

https://github.com/elixir-lang/elixir/blob/v1.8.1/lib/elixir/lib/calendar/date.ex#L746

Line: 748 to 751 needs one extra indentation.

Here is the current view:

https://hexdocs.pm/elixir/Date.html#day_of_era/1-examples

Thanks

**Comment by whatyouhide** [comment]
Thanks for the report @houmanka, this has been fixed in https://github.com/elixir-lang/elixir/commit/5a217ee9415899ce67b4055506263b459eb6470d and the fix will be pushed in the next patch update :)
