### ISSUE TITLE
Allow ? in variable names

### ISSUE THREAD

**Issue by orenbenkiki** [elixir-lang/elixir#896]
Functions are allowed to end with `?` but variables are not. It would be cleaner to use the same set of rules in both cases. It is very useful to be able to name boolean variables as a question, just like boolean functions:

```
overflow? = used > size
...
if overflow? do ... end
```

It seems like this shouldn't cause any issues as today one can already use `foo?` as a value in an expression (to invoke an argument-less function). And we don't have the `?` ternary operator to worry about.

**Comment by BenMorganIO** [comment]
I would consider predicates types of information that will always return a boolean. We don't use this `*?` to signal a function, we use it to signal to the _developer_ that they're working with a Boolean.

With Elixir 1.4 now logging warnings when we don't use a `()` at the end of some functions without piping, I would consider the vice argument from @alco now irrelevant.

It would help shorten some code as well by two characters... (A small, but perhaps gracious win for a few developers.)

**Comment by josevalim** [comment]
@BenMorganIO you are jumping into this discussion waaaaaay to late. :) Elixir support predicates in variables for quite some time now.

**Comment by josevalim** [comment]
And yes, you are right. @alco's argument would no longer apply as of v1.4 but it is irrelevant for a while already. :)

**Comment by BenMorganIO** [comment]
@josevalim lols for the longest time I thought they weren't supported.... :p
