### ISSUE TITLE
Formatter doesn't insert new line after constant definition

### ISSUE THREAD

**Issue by rhnonose** [elixir-lang/elixir#8960]
### Environment

* Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
* Elixir 1.8.1 (compiled with Erlang/OTP 20)`
* macOS High Sierra 10.13.6

### Current behavior

Formatting of a file doesn't include blank lines between a constant and a function definition.
A reproducible snippet:
```
defmodule MyModule do
  @const [
    :test1,
    :test1
  ]
  def my_function do
    :do_nothing
  end
end
```
The formatter doesn't insert a blank line between `]` and `def my_function do`.
If there's a blank line, the formatter keeps it.

### Expected behavior

The formatter should insert a blank line between `]` and `def my_function do`.

**Comment by josevalim** [comment]
It is on purpose becomes sometimes you want the attribute stay close to the function, such as `@spec`, `@doc`, etc. We also don't want to hardcode special module attributes (as you can always define your own), so we have to respect the user choice. For example, this would be completely valid:

```elixir
  @decorate [Foo, Bar]
  def foo(...)
```

And if we put them apart users would be angry at us. :)
