### ISSUE TITLE
Reference `Function.capture` from documentation of `Kernel.SpecialForms.&`

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#8961]
Since Elixir v1.7.0 we can build function captures programmatically using `Function.capture/3`.
However, this function is not yet referenced from `Kernel.SpecialForms.&/1`'s (the capture operator's) documentation.

This is obviously a low-priority, low-hanging-fruit issue, but it was something that I stumbled across in the documentation yesterday (luckily, someone else told me about the existence of `Function.capture` at some point; I was already resorting to `Code.eval_quoted`.) so I wanted to report it :slightly_smiling_face: .

I'll happily make a PR for it, unless someone else wants to.

**Comment by josevalim** [comment]
Please do send a PR!
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
