### ISSUE TITLE
Behaviours can 'conflict with themselves' (a confusing compilation warning)

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#8965]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

Erlang/OTP 21 [erts-10.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Operating system: Linux Manjaro

### Minimal code example

```elixir
defmodule Bar do
  @behaviour Access
  @behaviour Access
end
```

### Expected behavior

I'd expect warnings about missing behaviour implementation functions, but not a warning about a conflicting behaviour.

### Current behavior

```
warning: conflicting behaviours found. function pop/2 is required by Access and Access (in module Bar)
  iex:1

warning: conflicting behaviours found. function get_and_update/3 is required by Access and Access (in module Bar)
  iex:1

warning: conflicting behaviours found. function fetch/2 is required by Access and Access (in module Bar)
  iex:1

 ...
```

So it seems like the behaviour is conflicting with itself. 

---
Now this example is of course contrived. However, I have seen this in the wild where the same `@behaviour`-line ended up in module twice, having been added by two different `use`-statements.

I don't think we should show any warning in this (adding the same behavour twice) case, but even if we do want to, then the current warning message could be improved. :slightly_smiling_face:

**Comment by josevalim** [comment]
I think we should show some warning, because a duplicate behavior may be
caused by some other bug. But we should definitely improve the error
message.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
