### ISSUE TITLE
optional dependencies: `Code.ensure_loaded?/1` wrapping `use` does not work

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#8970]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.8.1
* Operating system:  Linux Manjaro

### Current behavior

Example snippet:

```elixir
defmodule UseInEnsureLoaded do
  if Code.ensure_loaded?(Bar) do
    use Bar
  end
end
```

Note that `Bar` is _not_ defined in the project. Imagine that it is defined in an optional dependency.

Now when compiling this module, you'll get the following error:

```bash
$ mix compile
Compiling 1 file (.ex)

== Compilation error in file lib/use_in_ensure_loaded.ex ==
** (CompileError) lib/use_in_ensure_loaded.ex:3: module Bar is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/use_in_ensure_loaded.ex:3: UseInEnsureLoaded (module)
    (elixir) expanding macro: Kernel.if/2
    lib/use_in_ensure_loaded.ex:2: UseInEnsureLoaded (module)
```

### Expected behavior

I would expect this code to compile properly, with the `use` only triggering after the condition in the `if` is true. 
Is there another, better way to `use` a module from an optional dependency instead? And/or is this a bug?

---

I have also tried to wrap the `use`-call in `Code.eval_quoted` to see if this would postpone the triggering of the macro. It does, but as soon as the `__using__`-code tries to use `@` (to e.g. specify documentation or specs for functions that are generated) we get the message

`** (ArgumentError) cannot invoke @/1 outside module`

(To see this in action, use the following snippet:

```elixir
defmodule Bar do
  IO.inspect("Hi1")
  defmacro __using__(_opts) do
    IO.inspect("#{__MODULE__} is using Bar!")
    quote do
      @doc "Default implementation of bar"
      def bar do
        42
      end
    end
  end
end
defmodule UseInEnsureLoaded do
  if Code.ensure_loaded?(Bar) do
    Code.eval_quoted(quote do
                      use Bar
    end)
  else
    IO.inspect "No bar!"
  end
end

```
)

**Comment by josevalim** [comment]
That will never work because macros (and therefore require) are expanded
before we execute “if”.

For you to achieve the desired behavior, you need to have a macro that
checks if it is loaded and then emits the proper quotes expressions
accordingly.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by josevalim** [comment]
Closing per the above, thanks for the report!

**Comment by Qqwy** [comment]
For posterity, I ended up writing this macro:

```elixir
  @doc false
  defmacro use_if_exists?(module, opts) do
    module = Macro.expand(module, __ENV__)
    if Code.ensure_loaded?(module) do
      quote do
        use unquote(module), unquote(opts)
      end
    end
  end

```
