### ISSUE TITLE
How to conditionally update map elegantly?

### ISSUE THREAD

**Issue by YongHaoWu** [elixir-lang/elixir#8971]
I am now doing it like this in a route:

```
    query = %{ type: params["type"] }
    query = if !!params["language"], do: Map.put(query, :language, params["language"]), else: query
    query = if !!params["id"], do: Map.put(query, :language, params["id"]), else: query
```

I wonder, could we afford a function to decide whether to put the key?

RIP, Joe.

**Comment by josevalim** [comment]
Hi @YongHaoWu!  Please use the [ElixirForum](http://www.elixirforum.com) or StackOverflow for questions/help/feedback, where a wider community will be able to help you. We reserve the issues tracker for issues only. Thank you!

**Comment by josevalim** [comment]
Actually, I realize now that you did mention this as a proposal. :) You can start a discussion about it on ElixirForum or on the core mailing list, as we do focus on issues here. Thanks!

**Comment by YongHaoWu** [comment]
> Actually, I realize now that you did mention this as a proposal. :) You can start a discussion about it on ElixirForum or on the core mailing list, as we do focus on issues here. Thanks!

Yep, I do mention this as a proposal if there is no best practice.
OK, I will mail it to the core mailing list.
