### ISSUE TITLE
Add `RELEASE_VMARGS` to specify vm.args file 

### ISSUE THREAD

**Issue by jesseshieh** [elixir-lang/elixir#8973]
#8967 enables a custom vm.args file to be generated at build time, but once it is built, it can not be modified at runtime. Distillery supports a [`VMARGS_PATH`](https://github.com/bitwalker/distillery/blob/b945641ebbc17848378f4cd0f1c116ec78326ad4/priv/libexec/config.sh#L15) variable to specify which vm.args file to use at runtime. We hope to add the same functionality to Elixir's new core releases with a `RELEASE_VMARGS` variable.

**Comment by josevalim** [comment]
PR sent here: https://github.com/elixir-lang/elixir/pull/8974. Let's continue the discussion there!
