### ISSUE TITLE
Code format indenting ends up in bigger indents than necessary

### ISSUE THREAD

**Issue by imanhodjaev** [elixir-lang/elixir#8975]
Hi,

Found similar related issue #7005 but I believe my case extends the scope which is affected.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.8.1
* Operating system: MacOS

### Current behavior

If forced indent long function heads by moving each argument on it's own new line and then apply formatting more indents added than expected

```elixir
def update(
      _parent,
      %{user_id: uid, fields: to_update},
      %{context: %{user: session_user}}
    ) do
  uid
  |> Users.get_user()
  ...
```

Which may be should look like this?

```elixir
def update(
    _parent,
    %{user_id: uid, fields: to_update},
    %{context: %{user: session_user}}
) do
  uid
  |> Users.get_user()
  ...
```

Also found similar inconsistency when formatting finds maps

This

```elixir
assert result == %{
  "data" => %{
    "changePassword" => %{
      "email" => "user1@email.com"
    }
  }
}
```

formatted like

```elixir
assert result == %{
              "data" => %{
                "changePassword" => %{
                  "email" => "user1@email.com"
                }
              }
            }
```

### Expected behavior

Format should indent no more than expected and for forced indents should at leas align indent to block body.

Is it expected to work this way? In my opinion this an unexpected side-effect.

Thanks.

**Comment by josevalim** [comment]
Those are formatted correctly. `def` and `assert` are regular function calls in their own right and `update(...)` and `left == right` are arguments to it. So everything is formatted after `def` and `assert`.

**Comment by imanhodjaev** [comment]
But as you can also see the indent is little bit deeper.
