### ISSUE TITLE
"deterministic" compile config option similar to erlang compiler

### ISSUE THREAD

**Issue by pavels** [elixir-lang/elixir#8986]
Erlang has `deterministic` option for compilation wit following meaning:

> Omit the `options` and `source` tuples in the list returned by `Module:module_info(compile)`, and reduce the paths in stack traces to the module name alone. This option will make it easier to achieve reproducible builds.

It would be nice to  have this in Elixir - especially the `source` omission. Sometimes it is necessary to be able to produce builds which are binary exactly the same and as it is now, you would need to do this on exactly same source paths.

I would even volunteer to make a PR, problem is, the build process of Elixir is quiet impenetrable to me. Tried multiple times to get a grasp on what's  going on, but failed, so i would at least need some hints on where to start.

**Comment by josevalim** [comment]
This option should just work for Elixir too, as Elixir delegates to the
Erlang compiler. Have you tried this route? If so, what is being different
between the BEAM files?
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by pavels** [comment]
I tried to put it in `erlc_options`  - it affects only compilation of `.erl` files from `src` folder (and there it works as documented). It has no effect on `.ex` files from `lib` .

**Comment by josevalim** [comment]
You can set it via environment variables:

    ERL_COMPILER_OPTIONS=deterministic mix compile --force

**Comment by pavels** [comment]
THAT WORKS :) - i should better read the manual next time
thank you very much
