### ISSUE TITLE
missing information in eex diagnostics

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#9005]
If an Extended Elixir file begins with an `<%= if ... %>` entry, but has no `<% end %>` entry, the resulting diagnostic message does not specify the file name (let alone the line number):

    == Compilation error in file lib/phx_http_web/views/item_view.ex ==
      ** (CompileError) lib/phx_http_web/views/item_view.ex:9:
        undefined function if/1
    (elixir) src/elixir_locals.erl:107:
      :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
    (elixir) src/elixir_locals.erl:108:
      anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:208:
      anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

Note: I initially posted this as https://github.com/phoenixframework/phoenix/issues/3336, but Chris McCord closed it, saying:

> This looks like an issue for the Elixir side as we only implement an EEx engine,
so this error is out of our control. Thanks!

**Comment by josevalim** [comment]
Thanks @RichMorin. Can you please provide a template that reproduces the error? Just to make sure we are working on the same root cause. Thank you.

**Comment by RichMorin** [comment]
I don't have the original code and output (blush), so I had to recapitulate it. I also realize that I mischaracterized the problem. That said, here's an example template file:

    <% foo = 42 %>
    <%= if foo %>

Here's the output; note that the template file (`.../templates/foo.eex`) is never mentioned:

    == Compilation error in file .../views/foo.ex ==
    ** (CompileError) .../views/foo.ex:3: undefined function if/1
        (elixir) src/elixir_locals.erl:107:
          :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
        (elixir) src/elixir_locals.erl:108:
          anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
        (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
        (elixir) lib/kernel/parallel_compiler.ex:208:
          anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6

**Comment by cybrox** [comment]
The error is correct (but also not ideal, I'd say). You are using `<% if foo %>`, instead of `<% if foo do %>`, which will attempt to call `if/1` instead of the existing `if/2`.  The missing end tag does not matter. Still, the error could probably be improved.

**Comment by cybrox** [comment]
As far as I can see, there is no reasonable way to improve feedback here. Both cases (with `do` but no `en` and with `end` but no `do` are handled correctly by EEx. The syntax you used is valid fo outputting a function result (e.g. `<%= MyApp.customfunc foo %>`), so it is correct that this will just call the function.

We could add extra checks for conditional here but that would be a rather large effort, I guess.

**Comment by michalmuskala** [comment]
I don't think the complaint was about not specifying that the `end` is missing - the complaint was that the produced stacktrace does not include the file where the issue actually is - it only includes the view module.

**Comment by cybrox** [comment]
You're right. My point with the `end`s is, that without the `do` and without an `end`, the template engine will (correctly) treat the tag as a function call, not a start/mid/end tag.

While it is confusing to the user, I would argue that it is technically correct that the stacktrace does not include the template file, because the templating worked perfectly fine. The correctly compiled instruction in the view creates the error.

**Comment by michalmuskala** [comment]
The compiler already does check if the function/macro exists. It's just that the reported location is wrong. The compiler will also report issues from eex correctly in some other cases, but not this one. It's probably some issue in the compiler dropping metadata in some place where it shouldn't or using incorrect metadata.

For example given the following files:
```elixir
# test.ex
defmodule Test do
  require EEx

  EEx.function_from_file(:def, :test, "test.eex", [])
end
# test.eex
<%= self %>

<%= self %>
```
The compiler properly emits two warnings with proper file/line information:
```
warning: variable "self" does not exist and is being expanded to "self()", please use parentheses to remove the ambiguity or change the variable name
  test.eex:1

warning: variable "self" does not exist and is being expanded to "self()", please use parentheses to remove the ambiguity or change the variable name
  test.eex:3
```

But if we change the template to:
```
<%= a %>
```
The compiler correctly emits the warning that it replaces `a` with `a()`, but then incorrectly reports that there's no such function as `a/0` - so the information is lost somewhere.
```
warning: variable "a" does not exist and is being expanded to "a()", please use parentheses to remove the ambiguity or change the variable name
  test.eex:1

== Compilation error in file test.ex ==
** (CompileError) test.ex:1: undefined function a/0
    (elixir) src/elixir_locals.erl:107: :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
    (elixir) src/elixir_locals.erl:108: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
```

**Comment by RichMorin** [comment]
Thanks, guys, for examining and fleshing out this issue. As @michalmuskala notes, the real issue is the fact that the location of the error is not given. As a side note, leaving out a "do" on an "if" is a mistake I make all too frequently, probably because Ruby doesn't use it.

**Comment by cybrox** [comment]
@michalmuskala Ah, true. I meant the EEx template compiler, but on second thought, that would be obsolete, since the elixir compiler does the check after the template has been compiled to code anyways. - Sorry for the confusion.

Yes, I think you're right then. I glanced over it really quick but I don't think my knowledge of the metadata handling in the elixir compiler is sufficient to tackle this.
