### ISSUE TITLE
Modules permit free floating atoms, tuples, lists and anon functions but not strings or integers.

### ISSUE THREAD

**Issue by chriseyre2000** [elixir-lang/elixir#9016]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)

* Operating system: 
macOS Mojave 10.14.3

### Current behavior

Given the source file experiment.ex:

defmodule Experiment do
  %{}
  {:ok}
  :ok
  []
  fn -> :ok end
end

This compiles without an error.

### Expected behavior

I would expect it to work in the same manner as if 1 or "fred" were included.

warning: code block contains unused literal 1 (remove the literal or assign it to _ to avoid warnings)
  experiment.ex

(which is what happens if you include 1 in the file).

This was found by one of my Exercism students who accidentally left a `:w` in a file between functions while saving in vim.

This is not actually harmful, just odd.

**Comment by josevalim** [comment]
So the warning is on purpose. The idea is that it helps developers find stray lines of code or text that is never used. Right now it detects only basic constructs but it may become smarter in the future. :) But when it is emitted, it is always correct. Thank you for the report!
