### ISSUE TITLE
Port.open documentation example leads to a dialyzer error

### ISSUE THREAD

**Issue by pallix** [elixir-lang/elixir#9021]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 

```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Elixir 1.7.3 (compiled with Erlang/OTP 20)
```

Using dialyxir with `{:dialyxir, "~> 1.0.0-rc3", only: [:dev], runtime: false}`

* Operating system: 

Debian 9

### Current behavior

Opening a Port like [the current documentation suggests](https://hexdocs.pm/elixir/Port.html#open/2) with `:spawn_executable`, like this:

```
path = System.find_executable("echo")

port = Port.open({:spawn_executable, path}, [:binary, args: ["hello world"]])
```

results in an error when using dialyzer:

```
:erlang.open_port({:spawn_executable, <<_::344>>}, [:binary | {:args, [<<_::56>>, ...]}, ...])

breaks the contract
(:PortName, :PortSettings) :: port()
when PortName:
       {:spawn, Command :: string() | binary()}
       | {:spawn_driver, Command :: string() | binary()}
       | {:spawn_executable, FileName :: :file.name()}
       | {:fd, In :: non_neg_integer(), Out :: non_neg_integer()},
     PortSettings: [:Opt],
     Opt:
       {:packet, N :: 1 | 2 | 4}
       | :stream
       | {:line, L :: non_neg_integer()}
       | {:cd, Dir :: string() | binary()}
       | {:env, Env :: [{Name :: :os.env_var_name(), Val :: :os.env_var_value() | false}]}
       | {:args, [string() | binary()]}
       | {:arg0, string() | binary()}
       | :exit_status
       | :use_stdio
       | :nouse_stdio
       | :stderr_to_stdout
       | :in
       | :out
       | :binary
       | :eof
       | {:parallelism, Boolean :: boolean()}
       | :hide
```

### Expected behavior

The code example should not trigger a dialyzer error.

### Remarks

`Port.open` in Elixir directly calls [`:erlang.open_port`](http://erlang.org/doc/man/erlang.html#open_port-2). The type of the `:spawn_executable` option is `{spawn_executable, FileName :: file:name()}`. And the `file:name` type is documented like this:

> name() = string() | atom() | deep_list()

> If VM is in Unicode filename mode, string() and char() are allowed to be > 255. See also the documentation of the name_all() type.

> name_all() =
>    string() | atom() | deep_list() | (RawFilename :: binary())

> If VM is in Unicode filename mode, characters are allowed to be > 255. RawFilename is a filename not subject to Unicode translation, meaning that it can contain characters not  conforming to the Unicode encoding expected from the file system (that is, non-UTF-8 characters although the VM is started in Unicode filename mode). Null characters (integer value zero) are not allowed in filenames (not even at the end). 

I am not familiar with Erlang so it's not clear to me why the `name()` type refers to `name_all()` in this case and if `binary()` could be a valid value for the option or not (in this case Dialyzer would be incorrect).

**Comment by josevalim** [comment]
PR sent here, thanks: https://github.com/erlang/otp/pull/2223!

**Comment by pallix** [comment]
Thank you.
