### ISSUE TITLE
Application.put_env typespec inconsistencies

### ISSUE THREAD

**Issue by hazardfn** [elixir-lang/elixir#9022]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating system: Mac OSX

### Current behaviour

The dialyzer spec for `Application.put_env/4` defines that a key must be an `atom()` however in my codebase it works with a tuple (and other terms) just fine.

`The call 'Elixir.Application':put_env(_table@1::any(),_k@1::{_,'server'},_server@1::any()) will never return since it differs in the 2nd argument from the success typing arguments: (atom(),atom(),any())`

### Expected behaviour

I suspect there is a valid reason for this typespec definition however it is confusing that the code works regardless of following the typespec and causes dialyzer to complain. Either `put_env/4` should enforce atoms using a guard or the typespec should be updated.

**Comment by josevalim** [comment]
The typespec is correct. The reason we don't add a guard is because some code may be using tuples and we don't want to suddenly break it. The same happens in Erlang: http://erlang.org/doc/apps/kernel/application.html#set_env-3

If we do an eventual Elixir v2.0, then we would feel comfortable with adding a guard or deprecating non-atoms before, for now, our best option is to allow the previous API but inform users with the help of typespecs. Thanks!

**Comment by josevalim** [comment]
@hazardfn I was hoping my answer above explained exactly that? The typespec is always meant to be the correct one. If you are violating the typespec, there is no guarantee it will continue to work on future releases. However, if we suddenly forbid non-atoms, we will break users application, which, even though they are wrong in this case, we want to avoid doing so.

**Comment by hazardfn** [comment]
I understand that the typespec states `atom()` is the only allowable key type my question was more WHY that is so in the typespec if tuples (and other terms) work fine?

What is it that is either A) bad practice or B) stopping tuples from working completely as env keys in either Erlang or Elixir? I personally find tuple keys very useful in the env and the services I have done this in have been quite happily ticking along.

I am trying to get at the crux of WHY `atom()` is the only allowable key type outside of what the typespec is saying.

**Comment by josevalim** [comment]
> I am trying to get at the crux of WHY atom() is the only allowable key type outside of what the typespec is saying.

Oh, I see. The restriction comes from Erlang but the rationale for having a more restricted format is that it suits better different medium for setting configuration. For example, you can do via command line `-kernel distribution_port 9090` or via config files. There may be other reasons but those (or an eventual relaxation of the existing API) would need to be discussed with the Erlang/OTP team.

**Comment by josevalim** [comment]
Another possibility, based on my personal experience, is that I sometimes tend to start with more restrictive APIs and make it more flexible as users demand. Maybe that's the case and it is just that nobody asked or proposed for it to allow any type of key.

**Comment by hazardfn** [comment]
I can maybe take this issue there and see what they say... Thanks for getting back to me so quickly and taking the time to discuss it further!

**Comment by hazardfn** [comment]
For anyone interested in following here is the ERL question ticket - https://bugs.erlang.org/browse/ERL-939

@josevalim not sure how you want to handle this but if they decide the restriction to atoms is a legacy restriction shall I notify on this issue or create a new more specific one?

**Comment by josevalim** [comment]
Please notify here and we can reopen it!
