### ISSUE TITLE
Add String.replace(string, value, replacement_fn) 

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9023]

**Comment by gkpacker** [comment]
Hey, @josevalim, i'm new with elixir and want to start contributing to open source, but no luck on getting easy issues. I've looked this one and tried to implement this method, it may be useful for you: 

```elixir
def replace(subject, value, replacement) when is_function(replacement) do
  {_status, pattern} =
    subject
    |> String.graphemes
    |> Enum.filter(replacement)
    |> Enum.join("|")
    |> Regex.compile

  replace(subject, pattern, value)
end
```
It usage would be something like this:
```elixir
iex> String.replace("ELIXIR", " ", fn letter -> letter == "I" end)
"EL X R"
```
When the `pattern` is a function, it will return a new string, changing all matching ocurrencies to the `value`

Does it make sense?

Thanks in advance!

**Comment by josevalim** [comment]
I am on this!

**Comment by leandrocp** [comment]
It seems that it's a way to define a more flexible `pattern`, right ?

Why not change the already existing function `String.replace/4` and add support for passing a function `(element -> as_boolean(term))` to the `pattern` arg ? 🤔

**Comment by romul** [comment]
Hmm, but what's a point for add such the function to stdlib, if it works exactly the same as a simple regexp? Imho, replacement_fn should be able to make different substitutions for different matches.
More like this:

```elixir
String.replace("ELIXIR", fn letter -> 
  case letter do
    "I" -> ""
    "X" -> "ks"
    ...
  end 
end)
```

**Comment by josevalim** [comment]
@romul the implementation I am working on is exactly what you proposed. I just need some time to finish it.

**Comment by josevalim** [comment]
Here is the PR #9073. Thanks everyone!
