### ISSUE TITLE
Almost true: "heredoc start must be followed by a new line"

### ISSUE THREAD

**Issue by playfulcats** [elixir-lang/elixir#9047]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

  Erlang/OTP 21 [erts-10.3.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]  
  Elixir 1.8.2 (compiled with Erlang/OTP 20)

* Operating system: 

  Ubuntu 18.10

### Current behavior

Sample code:
```elixir
'''x
'''
```
Compiler error message:
```
** (SyntaxError) test.exs:1: heredoc start must be followed by a new line after '''
    (elixir) lib/code.ex:767: Code.require_file/2
```

Replace `x` by any number of spaces before new line.
There are no any error messages, spaces just removed.

### Expected behavior

Well, perhaps, it would be more correct to not allow spaces between the heredoc start and new line just like other characters.

**Comment by josevalim** [comment]
> Well, perhaps, it would be more correct to not allow spaces between the heredoc start and new line just like other characters.

Doing that right now would be a breaking change, so our best option is to say that "followed by optional whitespace and a newline". A PR would be very welcome!

**Comment by josevalim** [comment]
Closing in favor of #9048.
