### ISSUE TITLE
One-off release commands (using start_clean) should not preload all apps

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9051]
/cc @tsloughter

**Comment by tsloughter** [comment]
Seems to work in relx, https://github.com/erlware/relx/pull/722 -- waiting to have the person who originally opened the issue verify it finds the OTP apps it needs to even when erts is not included in the release (the original issue that brought this nastiness to my attention).

**Comment by josevalim** [comment]
Closing in favor of #9056.
