### ISSUE TITLE
Small typo in Task.Supervisor docs

### ISSUE THREAD

**Issue by cybernetlab** [elixir-lang/elixir#9066]
Hi, while looking a [Task.Supervisor docs](https://hexdocs.pm/elixir/Task.Supervisor.html#async_nolink/3-examples) I found small typo in examples: I think that `handle_cast` [here](https://github.com/elixir-lang/elixir/blob/v1.8.2/lib/elixir/lib/task/supervisor.ex#L190) should be a `handle_call` really. Also `_from` argument missing [here](https://github.com/elixir-lang/elixir/blob/v1.8.2/lib/elixir/lib/task/supervisor.ex#L185),

**Comment by josevalim** [comment]
Good catch! Please do send a PR and we will gladly merge it. :)

**Comment by cybernetlab** [comment]
Ha, the master is already fixed by [this commit](https://github.com/elixir-lang/elixir/commit/58c86e1fcf41dd009eb99a2fc00d6d577510123d#diff-27ebed9d036ee5f6de38a53f8a5dd611) :)

**Comment by josevalim** [comment]
Sweet, thanks!
