### ISSUE TITLE
COMMERCIAL_AT and atom <Start>

### ISSUE THREAD

**Issue by playfulcats** [elixir-lang/elixir#9067]
I'm not sure in which way it is better to fix something here, but...

Please, read: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Unicode%20Syntax.md#atoms

It is stated that there are only one modification of atom `<Start>` in Elixir: `_`
In fact we can write this:
```
iex(1)> :@
:@
iex(2)> is_atom(:@)
true
iex(3)> a = :@
:@
iex(4)> is_atom(a)
true
```
Looks like it is correct to think about COMMERCIAL_AT in `<Start>`, but:
```
iex(1)> a = :@@
** (SyntaxError) iex:1: syntax error before: '@'

iex(1)> a = :@fail
** (SyntaxError) iex:1: syntax error before: fail
```
Nope, it is incorrect to think so. If you start your atom name with `@`, it will be the first and the last valid code point of this atom. :)

I repeat, I'm not sure what is more correct here, it is clear only that there is some confusion. :)

**Comment by fertapric** [comment]
All operators in Elixir are also valid atoms. In this case, [`Kernel.@/1`](https://hexdocs.pm/elixir/Kernel.html#@/1).

The same thing happens with `Kernel.++/2`:

```elixir
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.8.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :++
:++
iex(2)> :++a
** (SyntaxError) iex:2: syntax error before: a
```

This is documented in [the "Atoms" section of the "Syntax reference" docs](https://hexdocs.pm/elixir/syntax-reference.html#atoms) 🙂

**Comment by playfulcats** [comment]
Yep. But it is also stated that atoms can't start with `@`. It is documented in "Unicode syntax" from my report.
