### ISSUE TITLE
Old text in 'DynamicSupervisor' documentation

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#9075]
In the docs of the DynamicSupervisor, in the [module-based supervisors section](https://hexdocs.pm/elixir/DynamicSupervisor.html#module-module-based-supervisors) it is stated:

> .... 
> The `@doc` annotation immediately preceding `use DymamicSupervisor` will be attached to the generated `child_spec/1` function. 
> ...

However, in the code snippet above this paragraph, there is no `@doc`-annotation any more. On the line preceding the `use DyanmicSupervisor` there is however a comment.

So either the snippet needs to be updated, or the paragraph below it. 

Which one is correct? :slightly_smiling_face:

**Comment by josevalim** [comment]
Both approaches are fine. We can either add an example or replace "The @doc" by "A @doc" or similar. Your call. PR please? :)

**Comment by Qqwy** [comment]
All right! I'll do so tomorrow
