### ISSUE TITLE
Fails to generate 'this clause cannot match' warning with pattern match

### ISSUE THREAD

**Issue by akash-akya** [elixir-lang/elixir#9079]
`mix compile --warnings-as-errors` fails to generate `this clause cannot match because a previous clause at line x always matches` warning when function signature has a pattern matching.

### Current behavior
Sample code

```elixir
defmodule Dummy do
  def print([]) do
    IO.puts("Empty list")
  end

  def print([], extra \\ "") do
    IO.puts("Empty list: #{extra}")
  end
end
```

When compiled with `mix compile --force --warnings-as-errors`, does **not** generate any warning. and compiles successfully. This is true for all pattern matching (tested map, struct, number).

### Expected behavior

As ` def print([], extra \\ "") do` generates two signatues ` def print([]) do` and ` def print([], extra)`. Out of these former can never match.

We tried *without a pattern match*. ie.
```elixir
defmodule Dummy do
  def print(_list) do
    IO.puts("List")
  end

  def print(_list, extra \\ "") do
    IO.puts("List: #{extra}")
  end
end
```
This *does* generate `this clause cannot match because a previous clause at line 2 always matches` warning.

It seems it fails to generate a warning when params have a pattern matching.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Elixir 1.8.2 (compiled with Erlang/OTP 20)

* Operating system: 
`macOS High Sierra`

**Comment by josevalim** [comment]
It works as intended on master with OTP/22:

```
defmodule Dummy do
  def print(_list) do
    IO.puts("List")
  end

  def print(_list, extra \\ "") do
    IO.puts("List: #{extra}")
  end
end
warning: this clause cannot match because a previous clause at line 2 always matches
  iex:6
```

The warning comes from OTP, so it is likely OTP 22 that has better detection. Also note that those warnings are not a guarantee. If the compiler can tell you something will fail, great, but due to the complexity of patterns, we cannot always say so.

Thank you for the report.

**Comment by akash-akya** [comment]
Thanks for the quick response.

For the future reference, I tested with OTP 22 too. It didn't generate a warning.
From your comment, it seems like you are testing second code snippet, which is not a failure case I mentioned.

anyway, if the warning comes from OTP It does not matter.

**Comment by josevalim** [comment]
@akash-akya you are correct, I tested the wrong code, thanks for noticing it. Indeed, we don't show the warning for the first case, I will submit a bug report to the OTP team.

But as I mentioned, there is nothing theoretically wrong with the code, the warning is mostly a convenience for developers and not a guarantee, so it may be that we won't get a warning in the future anyway. 

Thanks!

**Comment by akash-akya** [comment]
Yes. you are right. I know its not a guarantee. It's just that I was curious about why it didn't work for one particular case when I had seen it catching these things before.

Thanks for clarifying
