### ISSUE TITLE
Spec of GenServer.server() type is lacking information of `:via`-tuples

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#9081]
In the documentation of GenServer, the [server()](https://hexdocs.pm/elixir/GenServer.html#t:server/0) type is specified as:

```elixir
server() :: pid() | name() | {atom(), node()}
```
which is used as parameter type for many of GenServer's functions.

It might be important to mention that `{:via, registry_name, key}`-tuples are also supported, to (a) improve the documentation, and (b) make Dyalizer happy when `:via`-tuples are passed to them.

The spec probably should be:
```elixir
server() :: pid() | name() | {atom(), node()} | {:via, registry :: atom(), identifier :: term()}
```
and we might want to improve the type documentation from 'the server reference' to something slightly more informing like:

```
The server reference. This is either a plain PID or a value representing a registered name. See the 'Name registration' section of this document for more information.
```

And related: currently, the documentation of `call` mentions something like this already, (`server can be any of the values described in the "Name registration" section of the documentation for this module.`) but then it is missing from the documentation of `cast` right below.
Maybe we want to include this information here as well?

**Comment by josevalim** [comment]
Yes, please include `via` and please add the docs to `cast`. PR is welcome!
