### ISSUE TITLE
IEx: Autocompleting types from OTP doesn't work

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#9087]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Erlang/OTP 22 [erts-10.4] [source] [64-bit] Elixir 1.9.0-dev (a8062a8) (compiled with Erlang/OTP 22)`
* Operating system: macOS

### Current behavior

Autocompleting functions works:

```
iex> :file.<tab>
advise/4                    allocate/3
(...)
```

But not types:

```
iex> t :file.<tab>
*nothing*
```

Note, listing types already works:

```
iex> t :file
@type filename() :: string()

@type filename_all() :: string() | binary()

(...)
```

### Expected behavior

Autocompleting types works.

**Comment by josevalim** [comment]
@wojtekmach I believe it is because we use the Docs chunk? But I guess we can traverse the abstract code chunk instead.

**Comment by josevalim** [comment]
Closing in favor of the PR!
