### ISSUE TITLE
Any chance we can add gitlab: to dependencies

### ISSUE THREAD

**Issue by pragdave** [elixir-lang/elixir#9117]
To parallel the way `github:` works...

Cheers

Dave

**Comment by josevalim** [comment]
I mostly regret adding `:github` so I wouldn't want to double on the mistake. Plus gitlab has many self-hosted versions (I use more self-hosted gitlabs than non-self hosted ones), so the option could be confusing from this perspective.

Also @pragdave, please use the mailing list for those discussions, we focus the issues tracker on actionable bugs and features which have been agreed to be added as part of the language. THe mailing list also generally has more participants in the discussion. Thanks!
