### ISSUE TITLE
Compilation Errors seemingly unrelated to the real reason (in untouched files)

### ISSUE THREAD

**Issue by RobertDober** [elixir-lang/elixir#9124]
I am really sorry to write a bug report that I just would hate to receive myself, but I just failed again and again to reproduce this behavior in any simple setup.

I am quite sure that I miss something obvious but even so I believe that the error messages are incorrect and I fail to debug/refactor Earmark's code.

I'll try to describe this as thoroughly as possible and will be more than happy to help with this in any way, but right now I am a little bit desperate.

So without much further ado here we go:

In this commit https://github.com/pragdave/earmark/commit/a82496b0369bf4506594d2af326041e2ec84c472 Earmark just compiles and the test in question fails as expected 
 ```
mix test /home/robert/gh/elixir/earmark/test/earmark_helpers_tests/list_helpers/space_lists_test.exs
...
 Assertion with == failed
     code:  assert space_lists(@one_input) == @one_output
     left:  [:blank, %Earmark.Block.List{attrs: nil, bullet: "-, +, *, 1) or 2.", bullet_type: "-", lnb: 1, start: "", type: :ul, blocks: [%Earmark.Block.ListItem{attrs: nil, blocks: [:blank, %Earmark.Block.Para{attrs: nil, lines: ["one"], lnb: 1}], bullet: "-", bullet_type: "-", lnb: 1, type: :ul, spaced: true}]}, :blank]
     right: [:blank, %Earmark.Block.List{attrs: nil, bullet: "-, +, *, 1) or 2.", bullet_type: "-", lnb: 1, start: "", type: :ul, blocks: [%Earmark.Block.ListItem{attrs: nil, blocks: [:blank, %Earmark.Block.Para{attrs: nil, lines: ["one"], lnb: 1}], bullet: "-", bullet_type: "-", lnb: 1, type: :ul, spaced: false}]}, :blank]
     stacktrace:
       test/earmark_helpers_tests/list_helpers/space_lis
```
Now I just started to develop the functionality as can be seen in this diff

[here](https://github.com/pragdave/earmark/compare/a82496b0369bf4506594d2af326041e2ec84c472...398557ac0bb2f800139affb6a6269d137767e382
)

which is the same as this one:

```
diff --git a/lib/earmark/helpers/list_helpers.ex b/lib/earmark/helpers/list_helpers.ex
index cd6f141..44f8b6a 100644
--- a/lib/earmark/helpers/list_helpers.ex
+++ b/lib/earmark/helpers/list_helpers.ex
@@ -2,6 +2,7 @@ defmodule Earmark.Helpers.ListHelpers do

   alias Earmark.Error
   alias Earmark.Line
+  alias Earmark.Block

   @ul_item_header_rgx ~r<\A\s*([*+\-])\s+>
   @ol_item_header_rgx ~r<\A\s*(\d{1,9})([).])\s+>
@@ -37,6 +38,9 @@ defmodule Earmark.Helpers.ListHelpers do
   end

   defp space_list(block)
+  defp space_list(%Block.List{blocks: blocks} = list) do
+    %{list | blocks: space_lists(blocks)}
+  end
   defp space_list(%{spaced: _}=block) do
     %{block | spaced: false}
   end
```
And now I get

```
mix test /home/robert/gh/elixir/earmark/test/earmark_helpers_tests/list_helpers/space_lists_test.exs                                                              [9:44:43]
Compiling 12 files (.ex)

== Compilation error in file lib/earmark/parser.ex ==
** (CompileError) lib/earmark/parser.ex:35: Earmark.Block.FnDef.__struct__/0 is undefined, cannot expand struct Earmark.Block.FnDef
    lib/earmark/parser.ex:35: (module)
```
So I am just puzzled how the parser cannot see a struct from `Block` correctly anymore after changes in an unrelated file please note that the `alias Earmark.Block` does not trigger the error but the usage of `Block.List` as well as an unaliased `Earmark.Block.List`

Again sorry for the mess but I am more than ready to spend the time necessary for any tests you need.

#### The examples above are from:

Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 20)

Linux roma 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Also experienced with

* OTP 22
* Elixir 1.9.0-rel.0
* Darwin aude 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by josevalim** [comment]
So the reason why the error happens is a cyclic dependencies.  Earmark.Block depends on code that uses list_helpers and list helpers now depend on the block:

In `block.ex` we have:

```
import Earmark.Helpers.ListHelpers, only: [space_lists: 1]
...
defmodule List, do: ...
```

and once you add `%Block.List` to `list_helpers.ex` you add a dependency in the other direction and the compiler can't resolve it. The error message is bad because the compiler doesn't know yet `Block.List` will be defined in `block.ex` since it is stuck on `import`. The compiler just knows compilation can't continue because any of the structs in `block.ex` can't be found since `block.ex` is stuck on `import Earmark.Helpers.ListHelpers`.

My suggestion is to move those definitions out:

```elixir
defmodule Earmark.Block.Heading,     do: defstruct lnb: 0, attrs: nil, content: nil, level: nil
defmodule Earmark.Block.Ruler,       do: defstruct lnb: 0, attrs: nil, type: nil
defmodule Earmark.Block.BlockQuote,  do: defstruct lnb: 0, attrs: nil, blocks: []
defmodule Earmark.Block.Para,        do: defstruct lnb: 0, attrs: nil, lines:  []
defmodule Earmark.Block.Code,        do: defstruct lnb: 0, attrs: nil, lines:  [], language: nil
defmodule Earmark.Block.Html,        do: defstruct lnb: 0, attrs: nil, html:   [], tag: nil
defmodule Earmark.Block.HtmlOther,   do: defstruct lnb: 0, attrs: nil, html:   []
defmodule Earmark.Block.IdDef,       do: defstruct lnb: 0, attrs: nil, id: nil, url: nil, title: nil
defmodule Earmark.Block.FnDef,       do: defstruct lnb: 0, attrs: nil, id: nil, number: nil, blocks: []
defmodule Earmark.Block.FnList,      do: defstruct lnb: 0, attrs: ".footnotes", blocks: []
defmodule Earmark.Block.Ial,         do: defstruct lnb: 0, attrs: nil, content: nil, verbatim: ""
# List does not need line number
defmodule Earmark.Block.List,        do: defstruct lnb: 1, attrs: nil, type: :ul, blocks:  [], start: "", bullet: "-, +, *, 1) or 2.", bullet_type: "-, +, *, . or )"
defmodule Earmark.Block.ListItem,    do: defstruct lnb: 0, attrs: nil, type: :ul, spaced: true, blocks: [], bullet: "-, +, *, 1) or 2.", bullet_type: "-, +, *, . or )" 

defmodule Earmark.Block.Plugin,      do: defstruct lnb: 0, attrs: nil, lines: [], handler: nil, prefix: "" # prefix is appended to $$

defmodule Earmark.Block.Table do
  defstruct lnb: 0, attrs: nil, rows: [], header: nil, alignments: []

  def new_for_columns(n) do
    %__MODULE__{alignments: Elixir.List.duplicate(:left, n)}
  end
end

defmodule Earmark.Block do
  alias Earmark.Block.{
    Heading,
    Ruler,
    BlockQuote,
    Para,
    Code,
    Html,
    HtmlOther,
    IdDef,
    FnDef,
    FnList,
    Ial,
    List,
    ListItem,
    Plugin,
    Table
  }
```

But generally speaking, if there are cyclic definitions is because there are too many parts of the code with shared knowledge of the same pieces.

Unfortunately this is nothing something we can do something about in the compiler. We can improve the error message for missing structs but that would be it, sorry.

**Comment by RobertDober** [comment]
I know the code is bad right now, unfortunately I missed the cyclic import thingy, so many, many thanks for that. I knew I was missing something :cry:

Can the compiler not indicate the cyclic import?

**Comment by josevalim** [comment]
Unfortunately the compiler does not know it is a cyclic dependency because it hasn't reached that far int he code, it is stuck in importing the ListHelper which never completes.
