### ISSUE TITLE
IEx.Helpers.t displays types in reverse order of definition

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#9129]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): master

### Current behavior

For this module:

```elixir
defmodule M do
  @type a() :: integer()

  @type b() :: integer()

  @type c() :: integer()
end
```

we get:

```elixir
iex(1)> t M
@type c() :: integer()

@type b() :: integer()

@type a() :: integer()
```

Note:

```elixir
iex(1)> Code.Typespec.fetch_types(M)
{:ok,
 [
   type: {:c, {:type, 6, :integer, []}, []},
   type: {:b, {:type, 4, :integer, []}, []},
   type: {:a, {:type, 2, :integer, []}, []}
 ]}
iex(2)> Code.fetch_docs(M)
{:docs_v1, 1, :elixir, "text/markdown", :none, %{},
 [
   {{:type, :a, 0}, 2, [], :none, %{}},
   {{:type, :b, 0}, 4, [], :none, %{}},
   {{:type, :c, 0}, 6, [], :none, %{}}
 ]}
```

Maybe we're putting them into chunks in the wrong order in the first place?

### Expected behavior

Types are sorted by name. Note, we could display them in order of definition but since we're sorting callbacks in `IEx.Helpers.b`, makes sense to sort it here too.

**Comment by josevalim** [comment]
Yes, we should sort them alphabetically.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
