### ISSUE TITLE
IEx crash on Process.exit( Process.group_leader(), :kill )

### ISSUE THREAD

**Issue by jsimmonds2** [elixir-lang/elixir#9138]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.8.1 and Erlang/OTP 21
* Operating system: `Linux  version 4.19.25` on ARMv7 (Raspberry Pi 3 B+)

### Current behavior

SSH connection to IEx session closes but crash log sent to Logger.

### Expected behavior

SSH connection and IEx process closed **without** crash log.

This issue on [Toolshed](https://github.com/fhunleth/toolshed/issues/25) seems more like a plain **IEx  bug** (`** (IEx.Error) error when printing EXIT message: :terminated`) than anything else.

**Comment by josevalim** [comment]
Why are you expecting no crash reason? You are terminating the process
responsible for doing I/O, therefore I would even expect multiple things to
fail. Getting errors is definitely expected.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by jsimmonds2** [comment]
Oh, Ok.  Does the `:kill` message **not allow** the target process to do cleanup in any way ?
(newbie question, sorry)

Am only trying to help the author of Toolshed find a quiet, sure way of terminating an IEx shell over SSH.
Your thoughts on this would be highly regarded.
Thanks

**Comment by josevalim** [comment]
> Oh, Ok. Does the :kill message not allow the target process to do cleanup in any way ?

No cleanup is allowed if you send a `:kill`. It is the "strongest" signal there is in Erlang/Elixir.

@fhunleth if you start `ssh` with the Erlang shell, does it log anything when you terminate it in the same fashion as Elixir? If so, then it is an IEx bug, otherwise another way to terminate has to be found.

**Comment by fhunleth** [comment]
Amazingly, I don't get a log message when I terminate from the Erlang shell when connecting over ssh. I just tried it again - exact same code that I was running from IEx. No log message. 

To be clear, all that I did was change the ssh daemon configuration to not start up IEx. Then I logged in over ssh and ran `'Elixir.Toolshed.Misc':exit().`. That's the function that @jsimmonds2 is trying to fix.

**Comment by fhunleth** [comment]
Here's the full log message that I get when "exiting" from IEx:
```
13:32:57.324 [error] Process #PID<0.1778.0> raised an exception
** (ErlangError) Erlang error: :terminated
    (stdlib) :io.put_chars(:standard_io, :unicode, ["\e[31m** (IEx.Error) error when printing EXIT message: :terminated\e[0m", 10])
    (iex) lib/iex/server.ex:247: IEx.Server.handle_take_over/6
:ok
```

**Comment by josevalim** [comment]
@fhunleth thanks, I could reproduce it.

When I reproduce it though, it simply crashes both Erlang/Elixir shell. Does it have a different behaviour under ssh? What happens after the exit? It simply disconnects?

**Comment by fhunleth** [comment]
Right, it disconnects the `ssh` session and that's it. As far as I can tell, it doesn't have any side effects. We used to type `<enter>~.` to disconnect ssh sessions and it seems to work similarly.

**Comment by josevalim** [comment]
@fhunleth ok, sounds good. Btw, I wonder if ssh has a better API for shutdown, but that's a separate discussion. :)

**Comment by fhunleth** [comment]
Yes - would be nice to have a better way. Thanks for making the fix, though! It will be nice to not see that log message.
