### ISSUE TITLE
mix test silently skips test that fails to compile

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#9151]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 22 [erts-10.4.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.9.0-rc.0 (c30b6d6) (compiled with Erlang/OTP 22)
* Operating system: osx 10.14.5

### Current behavior

In phoenix app i added a test file with syntax errors.
```
defmodule Demo.ModelTest do
  use ExUnit.Case
  alias Demo.Model
  alias Demo.Model.MyStruct

  test "empty equal" do
    desired = %MyStruct{
      field1: %{}
      field2: %{}
    }

    current = %MyStruct{
      field1: %{}
      field2: %{}
    }

    assert [] == Model.build_requests()
  end
end
```
When i run
```
$ mix test
Compiling 40 files (.ex)
Generated demo app
....
Finished in 0.04 seconds
11 tests, 0 failures
```
When i run the faulty file directly
```
$ mix test test/model_tests.exs 
== Compilation error in file test/model_tests.exs ==
** (SyntaxError) test/model_tests.exs:9: syntax error before: field2
    (elixir) lib/kernel/parallel_compiler.ex:237: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```
### Expected behavior

`mix test` should raport error and exit with non 0 code

**Comment by josevalim** [comment]
Your test file should be named `_test.exs` and not `_tests.exs`.

**Comment by lukaszsamson** [comment]
🤦‍♂ silly me. Maybe a warning message would help if mix detects any .exs files in test dir not ending in _test.exs

**Comment by josevalim** [comment]
We do have a configuration that warns for certain patterns the issue is always false positives. Someone could have a legitimate file as a test helper named `_tests.exs`.
