### ISSUE TITLE
Documentation improvements: new Config module (Elixir 1.9) and Mix.env() calls

### ISSUE THREAD

**Issue by tompave** [elixir-lang/elixir#9153]
Hello,

I'm trying Elixir `1.9-rc.0` on a Phoenix 1.4.8 project and I've noticed some unclear information in the docs for the new `Config` module. I'm not sure if this is the right place to report it, but hopefully it will result in a change in the documentation for 1.9, so the repository issues seemed more appropriate than the forum and the mailing list. If it's not, I'm happy to move the conversation somewhere else.

The [`Config` 1.9-rc.0 docs](https://hexdocs.pm/elixir/1.9.0-rc.0/Config.html) use `Mix.env` in some examples, like the main introductiory paragraph and `import_config/1`. That seems at odds with what is implied in the [release notes](https://github.com/elixir-lang/elixir/releases/tag/v1.9.0-rc.0) for `1.9`:

> A new `Config` module has been added to Elixir. The previous configuration API, `Mix.Config`, was part of the Mix build tool. But since releases provide runtime configuration and Mix is not included in releases, we ported the `Mix.Config` API to Elixir.

I feel that it's not clear yet when Mix is available (compile- vs run-time), and whether it should have a role in the new `config/{config,prod}.exs` files. I know that Mix is only available at compile-time (and therefore in dev[1]), but at the moment the documentation makes it more confusing.

Am I misinterpreting things, or is there room for improvement and clarifications?

### Environment

```
$ elixir --version

Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.0-rc.0 (aad7aa4) (compiled with Erlang/OTP 22)
```

----

[1]: Unless you run your production app as a Mix task with `MIX_ENV=prod`, which is possible but discouraged.

**Comment by josevalim** [comment]
More docs have been pushed, thanks!

> [1]: Unless you run your production app as a Mix task with MIX_ENV=prod, which is possible but discouraged.

Btw, I wouldn't say it is discouraged. :)
