### ISSUE TITLE
Nested module failing dialyzer on Erlang 22

### ISSUE THREAD

**Issue by indocomsoft** [elixir-lang/elixir#9154]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.2 (compiled with Erlang/OTP 22)
```

* Operating system: `macOS Mojave Version 10.14.5`

### Current behavior

When defining nested module like this:
```elixir
defmodule SpecBug do
  defmodule Asd do
    def bug do
      Code.eval_quoted(
        quote do
        end,
        [],
        __ENV__
      )
    end
  end
end
```

Running dialyzer yielded warnings:
```
[
  {:warn_return_no_exit, {'lib/spec_bug.ex', 3},
   {:no_return, [:only_normal, :bug, 0]}},
  {:warn_failing_call, {'lib/spec_bug.ex', 4},
   {:call,
    [
      Code,
      :eval_quoted,
      '({\'__block__\', [], []},[],\#{\'__struct__\':=\'Elixir.Macro.Env\', \'aliases\':=[{\'Elixir.Asd\',\'Elixir.SpecBug.Asd\'},...], \'context\':=\'nil\', \'context_modules\':=[\'Elixir.SpecBug\' | \'Elixir.SpecBug.Asd\',...], \'contextual_vars\':=[], \'current_vars\':=\#{}, \'file\':=<<_:360>>, \'function\':={\'bug\',0}, \'functions\':=[{\'Elixir.Kernel\',[{atom(),0 | 1 | 2 | 3},...]},...], \'lexical_tracker\':=\'nil\', \'line\':=8, \'macro_aliases\':=[{\'Elixir.Asd\',{{\'Elixir.SpecBug\',1},\'Elixir.SpecBug.Asd\'}},...], \'macros\':=[{\'Elixir.Kernel\',[{atom(),0 | 1 | 2 | 3},...]},...], \'module\':=\'Elixir.SpecBug.Asd\', \'prematch_vars\':=\'warn\', \'requires\':=[\'Elixir.Kernel\' | \'Elixir.Kernel.Typespec\',...], \'unused_vars\':=\#{}, \'vars\':=[]})',
      [3],
      :only_contract,
      '(any(),[{atom() | {_,_},_}],[{atom(),_}] | \#{\'__struct__\':=\'Elixir.Macro.Env\', _=>_})',
      '{_,_}',
      {true,
       '(\'Elixir.Macro\':t(),[any()],\'Elixir.Macro.Env\':t() | elixir:keyword()) -> {term(),binding::[any()]}'}
    ]}}
]
```

Calling `:dialyzer.format_warning/1` on the `:warn_failing_call` resulted in error:

```
** (MatchError) no match of right hand side value: {:error, {1, :erl_parse, ['syntax error before: ', '\'::\'']}}
    dialyzer.erl:626: anonymous fn/1 in :dialyzer.sig/2
    dialyzer.erl:541: :dialyzer.call_or_apply_to_string/6
    dialyzer.erl:322: :dialyzer.message_to_string/2
    dialyzer.erl:297: :dialyzer.format_warning/2
```

Which seems like it's because dialyzer reconstructed the spec as `binding::[any()]` and in Erlang, `binding` is an atom.

However, if I instead defined the modules without nesting:
```elixir
defmodule SpecBug do
end

defmodule SpecBug.Asd do
  def bug do
    Code.eval_quoted(
      quote do
      end,
      [],
      __ENV__
    )
  end
end
```

Dialyzer returned no error.

### Expected behavior

Expect that there is no dialyzer error.

Note that running on Erlang 21 and 20 also results in no dialyzer warning.

**Comment by indocomsoft** [comment]
My suspicion now is this line:
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/macro/env.ex#L88

should be `macro_aliases: macro_aliases` instead of `macro_aliases: aliases`

**Comment by indocomsoft** [comment]
Yup, that's the main reason for Dialyzer emitting the warning. I submitted a PR for this: https://github.com/elixir-lang/elixir/pull/9155

I am still intrigued by the second part though: the failure of dialyzer to actually generate warnings. Is this a bug in the code generated by the Elixir compiler, or is it a bug in Dialyzer itself?

**Comment by josevalim** [comment]
> Is this a bug in the code generated by the Elixir compiler, or is it a bug in Dialyzer itself?

The second: https://github.com/erlang/otp/pull/2240
