### ISSUE TITLE
1.9.0 config/releases.exs causing issues on start_iex command

### ISSUE THREAD

**Issue by sunboshan** [elixir-lang/elixir#9164]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): otp 22.0.4/elixir 1.9.0
* Operating system:  darwin

### Current behavior

```
➜ mix new b
```

config/releases.exs
```
import Config

config :b, :key, "value"
```

```
➜ MIX_ENV=prod mix release
Compiling 1 file (.ex)
Generated b app
* assembling b-0.1.0 on MIX_ENV=prod
* using config/releases.exs to configure the release at runtime

Release created at _build/prod/rel/b!

    # To start your system
    _build/prod/rel/b/bin/b start

Once the release is running:

    # To connect to it remotely
    _build/prod/rel/b/bin/b remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/prod/rel/b/bin/b stop

To list all commands:

    _build/prod/rel/b/bin/b


tmp/ex/b via 💧 v1.9.0
➜ _build/prod/rel/b/bin/b start_iex
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

*** ERROR: Shell process terminated! (^G to start new job) ***
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(b@sbs)1> %                                                                                                     
tmp/ex/b via 💧 v1.9.0 took 42s

➜ _build/prod/rel/b/bin/b start_iex
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

The shell log file has mysteriousy closed. Ignoring currently unread history.
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(b@sbs)1> % 

```

When have `config/releases.exs` in building a release, using `start_iex` command will have one of two errors shown above. Even though the iex shell is up, but don't know why those error's shows up.

-------------------

In the [docs](https://hexdocs.pm/mix/Mix.Tasks.Release.html),

> If a config/releases.exs exists, it will be copied to your release and executed as soon the system starts. Once the configuration is loaded, the Erlang system will be restarted (within the same Operating System process) and the new configuration will take place.

Seems the erts will be restarted after loading the configuration. So i guess this is an expected behaviour?

**Comment by josevalim** [comment]
Thanks @sunboshan! This issue happens only if you have shell history is enabled. It is a race condition on shutdown. I wrote a report here: https://github.com/erlang/otp/pull/2302

We can follow up the discussion on OTP side of things.
