### ISSUE TITLE
Zombie process wrapper script does not exit on wrapped program exit

### ISSUE THREAD

**Issue by Javyre** [elixir-lang/elixir#9171]
Hey, I am running a program through `System.cmd` that does not mind its `stdin` being closed. The `System.cmd` documentation points me to the recommended wrapper script on the `Port` docs for preventing zombie processes, but this script accomplishes its task at the cost of ignoring when the wrapped program exits

```bash
#!/bin/bash
"$@" & # There is nothing making the script exit with this process exits
pid=$!
while read line ; do
  :
done
kill -KILL $pid
```

### Environment
```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.0 (compiled with Erlang/OTP 22)

Mac OS 10.14.5
```

### Current behavior
```elixir
System.cmd("/path/to/wrapper", ~w(echo test))
```

Hangs indefinitely even after `echo test` is run

### Expected behavior

The script should prevent zombie processes by exiting on `stdin` close, but also exit when the wrapped program finishes (preferably with the same exit code)

**Comment by josevalim** [comment]
Thank you. I will add a note that the above should only be used if you expect the child program to run forever, for something that you expect to terminate, then it won't work (which is less of a problem because it will terminate eventtually). If anyone can come up with a different script for those cases or one that works for both, please let us know!

**Comment by eksperimental** [comment]
Also If anyone can come up with a script that is POSIX compliant, it will be greatly appreciated as this is the only piece of shell script code that is not

**Comment by OvermindDL1** [comment]
If you don't mind a port program made in C wrapping it the https://github.com/saleyn/erlexec (and erlang) library is what I've replaced my old scripts with.  Otherwise I have a posix script on the ElixirForums somewhere in my old posts that I used to use that worked.  I really recommend `erlexec` when you can though.

**Comment by Javyre** [comment]
@josevalim The process I am running is `ffmpeg`... so yes, it *will* terminate *eventually*
@eksperimental I don't see anything non-POSIX other than the shebang, in which case I agree
@OvermindDL1  Thanks, this seems to be more than appropriate for my use case

**Comment by josevalim** [comment]
Fantastic, thanks everyone for the input.

**Comment by josevalim** [comment]
Ok, so I was able to write a version of the wrapper that terminates if the program terminates, at the cost of an extra process:

```sh
#!/bin/sh

# Start the program in the background
exec "$@" &
pid1=$!

# Silence warnings from here on
exec >/dev/null 2>&1 

# Read from stdin in the background and
# kill running program when stdin closes
exec 0<&0 $(
  while read; do :; done
  kill -KILL $pid1
) &
pid2=$!

# Clean up
wait $pid1
kill -KILL $pid1
kill -KILL $pid2
```

`shellcheck` validates it OK too.

**Comment by Javyre** [comment]
@josevalim I found that terminating the script does not kill the `exec "$@" &`

```bash
$ ./wrapper sh -c 'sleep 6; echo test'
^C
$ # but the 'sleep 6; echo test' is still running (ironically zombified now)
```

**Comment by josevalim** [comment]
We are not trapping signals. You have to send a Ctrl+D to simulate closing
stdin. Someone could add trapping but it isn’t required for the port usage.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by Javyre** [comment]
Yeah that sounds fair.
Thank you

**Comment by Javyre** [comment]
@josevalim Is there a reason why you're killing `$pid1` after waiting for it?

**Comment by josevalim** [comment]
Ah, good catch. I will remove it.

**Comment by Javyre** [comment]
I'll stop annoying you after this but the return code of the `wait` is also not forwarded. I'm not sure if this was intended..

**Comment by josevalim** [comment]
@Javyre do you know how to forward it?

**Comment by Javyre** [comment]
@josevalim This works for me

```bash
# Clean up
wait $pid1
ret=$?
kill -KILL $pid2
exit $ret
```

**Comment by josevalim** [comment]
Do you want to submit a PR with the last two proposed changes? Otherwise I will do it. :)

**Comment by Javyre** [comment]
No problem, I'll do it
