### ISSUE TITLE
erlc_options is missing :debug_info if not explictly stated

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#9183]
## Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 22)
```
* Operating system: macOS Mojave

### Current behavior

There is irritating difference in behaviour of `:elixirc_options` and `:elrc_options`. This is the inclusion of `:debug_info`. In `:elixirc_options` it is added always (or at least seems so when running Dialyzer) while in `:erlc_options` it need to be explicitly stated, otherwise Dialyzer will fail with information that it cannot find Erlang Core informations.

### Expected behavior

Mix should always add `:debug_info` option or should provide different way to ensure, that this is handled properly. Otherwise it can result with irritating problems when using Mix in Erlang projects.

**Comment by josevalim** [comment]
Can you please open up a new report?

1. I am not sure what the issue actually is. Do you mean that debug_info is not added by default in erlang?

2. Please remove the parts about it being irritating. We know. Almost all bugs are irritating. But we are not here to address irritations nor we are required to sort through it.

Thanks.
