### ISSUE TITLE
Mix release documentation improvements

### ISSUE THREAD

**Issue by whitepaperclip** [elixir-lang/elixir#9187]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.9.0
* Operating system: Ubuntu 16.04

### Current behavior

Quoting from the current documentation for Mix releases:

> Furthermore, while vm.args is static, you can use env.sh and env.bat to dynamically set VM options. For example, if you want to make sure the Erlang Distribution listens only on a given port known at runtime, you can set the following:
> 
> `export ELIXIR_ERL_OPTIONS="-kernel inet_dist_listen_min $BEAM_PORT inet_dist_listen_max $BEAM_PORT"`

However, for the common case where only a single BEAM port is used, setting this option in `env.sh` causes most RPC calls to fail:

```sh
$ bin/my_app rpc "IO.puts(1)"
Protocol 'inet_tcp': register/listen error: eaddrinuse
$ bin/my_app pid
Protocol 'inet_tcp': register/listen error: eaddrinuse
```

Setting these kernel flags in `vm.args` is obviously preferable here, since it doesn't require the port to be available.

### Expected behavior

The documentation should probably expand further on the differences between the two files, and/or remove the current example.

---

### Current behavior

The documentation also states:

> For example, if you need to do some prep work before running the actual system, like migrating your database, `eval` can be a good fit. Just keep in mind any application you may use during `eval` has to be explicitly started.

Database/Ecto connections are typically configured with Mix on a per-environment basis; these options aren't available unless the application is started, which is impossible if the app is started in another VM instance and listens on a hardcoded port:

```sh
$ bin/my_app eval "MyApp.ReleaseTasks.migrate"
Starting dependencies..
Starting repos..
Running migrations for my_app
[error] GenServer #PID<0.148.0> terminating
** (RuntimeError) connect raised KeyError exception: key :database not found.
```

Worth noting: [this used to work](https://hexdocs.pm/distillery/guides/running_migrations.html) with Distillery.

In fact, if you take the suggested `ReleaseTasks` module, there is some odd behavior with `Application.get_env(:my_app, ...)`:

```elixir
defmodule MyApp.ReleaseTasks do
  @repos Application.get_env(:my_app, :ecto_repos)

  def migrate() do
    IO.inspect(@repos)
    IO.inspect(Application.get_env(:my_app, :ecto_repos))
  end
end
```

```sh
$ bin/my_app eval "MyApp.ReleaseTasks.migrate"
[MyApp.Repo]
nil
```

### Expected behavior

The documentation could clarify `rpc` vs. `eval` by including an example of a common task that doesn't require application configuration parameters, and/or by suggesting database migrations be done via `rpc`.

**Comment by josevalim** [comment]
> In fact, if you take the suggested ReleaseTasks module, there is some odd behavior with Application.get_env(:my_app, ...):

You need to load the application before reading its environment. In any case, your point is clearer, we can improve the docs. I will push a PR soon.

**Comment by whitepaperclip** [comment]
@josevalim Much clearer, thanks! :smile:
