### ISSUE TITLE
Using mix clean with MIX_BUILD_PATH can erase your source code files

### ISSUE THREAD

**Issue by derekkraan** [elixir-lang/elixir#9188]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 22)
```
* Operating system: 
Arch linux / docker

### Current behavior

In Docker I usually set MIX_BUILD_PATH to avoid permission conflicts with the host. So in my docker container I have `MIX_BUILD_PATH=/_build` and my app in `/api`.

However, `mix clean` is expecting the build path to be two directories deep, ie `/_build/dev`. So it runs `Path.dirname()`, resulting in `"/"`. Then it adds to that path, eventually resulting in the following pattern: `/*/lib/your_app_name`, and it erases everything matching that. My application is in `/api/`, so this matches.

The result: my source code gets deleted.

### Expected behavior

I would expect `mix clean` to only delete build files.

### Possible solutions

1. add the env to `MIX_ENV_PATH` in `Mix.Project.build_path/1`
2. have `mix clean` match only build files (`.beam` etc)
3. document MIX_BUILD_PATH better so that users understand that it should be eg, `/_build/dev` (https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix.ex#L237)
4. modify `mix clean` to recognize when it is dealing with `MIX_BUILD_PATH` so that it doesn't remove the last directory from the path.
5. filter files to be deleted to make sure they aren't actually in your application directory
6. something else?

**Comment by josevalim** [comment]
My suggestion is to change MIX_BUILD_PATH to actually be only the `:build_path`, as it is in the `project` config. In other words, [this line](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/project.ex#L479) should be:

    dir = System.get_env("MIX_BUILD_PATH") || config[:build_path] || "_build"

Can you please send a PR?
