### ISSUE TITLE
Mix tasks that come from dependencies are not recompiled if dependency changes

### ISSUE THREAD

**Issue by whatyouhide** [elixir-lang/elixir#9190]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.0-dev (2e0ca9d) (compiled with Erlang/OTP 22)
* Operating system: macOS 10.14.5

### Current behavior

If I generate a new project:

```bash
mix new my_app
```

and I add a dependency that exposes a Mix task (such as Credo):

```elixir
def deps
  [{:credo, "1.0.0"}]
end
```

and I run `mix deps.get` and `mix credo --version`, everything is compiled the first time and the output of `mix credo --version` is `1.0.0`. If I change the version of the Credo dependency:

```elixir
def deps do
  [{:credo, "1.1.0"}]
end
```

and run `mix deps.get` and `mix credo --version`, the output is still `1.0.0` and Credo doesn't get recompiled.

### Expected behavior

The reason this happens is that `mix credo` doesn't invoke anything that loads the current Mix project. If it did, the usual recompilation mechanisms would kick in, Credo would get recompiled (since it changed from 1.0.0 to 1.1.0), and `mix credo --version` would correctly return `1.1.0`. However, none of that happens and Credo isn't recompiled. This is in part a deliberate choice because a Mix task can not be related to the code in the project in any way (think of `mix local.hex`), so it makes sense that we don't load the project and hence not recompile anything.

However, we should at least load and possibly recompile the library that a Mix task was defined in. In the example above, doing so would mean that when I run `mix credo` and we know that `mix credo` is in the Credo library, we check if the Credo library changed and possibly recompile it.

#### Notes

Note that the same isn't true for local Mix tasks (defined in the current project). Even if a local Mix task doesn't load the project, it still gets recompiled if it changed.

**Comment by relistan** [comment]
Definitely saw this in one of our apps today :) . Workaround was `mix deps.clean <dep_name>` but incredibly subtle to identify.
