### ISSUE TITLE
mix format does not fix a multi-line statement that could fit on 1 line

### ISSUE THREAD

**Issue by nickjj** [elixir-lang/elixir#9196]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang 21 / Elixir 1.8.1
* Operating system: Debian Stretch
* `.formatter.exs` has `line_length: 80` in it

### Current behavior

I originally had a test function defined like this:

```elixir
    test "creates user, sends email and redirects to the list courses page",
         %{
           conn: conn
         } do
```

What you see above is after running `mix format` and that formatting is expected.

But then I changed my test function to be this:

```elixir
    test "creates user, sends email and redirects",
         %{
           conn: conn
         } do
```

And `mix format` did not pull everything up onto 1 line.

If I manually format it to this:

```elixir
    test "creates user, sends email and redirects", %{conn: conn} do
```

It is 68 characters and fits on 1 line very nicely.

### Expected behavior

I would have expected `mix format` to pull that up to 1 line since it fits within 80 characters. I have noticed `mix format` pulling up other lines outside of ExUnit test cases.

**Comment by josevalim** [comment]
That’s on purpose. Many like to have their code with a single entry per
line, even if just one entry (in case you want to add more in the future),
even if it fits a single line. If we automatically squeezed it, we would
definitely get a lot of complaints (and we did).

The docs for the formatter in the Code module outlines those cases
explicitly. You can read them for more info. For now, you can always put
them back in the same line and the formatter will respect your choice too.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D
