### ISSUE TITLE
ExDoc should deal with fully namespaced module names

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#9199]
I think a reference to `Module` and `Elixir.Module` should link to `Module.html`,
same for `Elixir.Module.function/1`

**Comment by josevalim** [comment]
This should be reported on ExDoc. Also, plaese always fill in the issues template, regardless of how small the issue is. Thanks.

**Comment by eksperimental** [comment]
It was meant to be reported in ExDoc but I picked the wrong browser tab. Sorry for the noise
