### ISSUE TITLE
Unquote is not evaluated when called without parens before a block

### ISSUE THREAD

**Issue by mhanberg** [elixir-lang/elixir#9202]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.9.0 & 21.0.8
* Operating system: macOS 10.14.4

### Description

Calls to `unquote` are not evaluated when directly preceding a block. This should be identical to calling with parens.

I originally wrote this code but it didn't work, so I added the parens to make it work and moved on, not thinking much of it.

After calling mix format and seeing that the code was reverted and once again didn't work, I did some investigation and discovered the bug.

### Current behavior

```elixir
quote do
  unquote(:foo) do
    "bar"
  end
end

# {:unquote, [], [:foo, [do: "bar"]]}

quote do
  unquote(:foo)() do
    "bar"
  end
end

# {:foo, [], [[do: "bar"]]}
```

### Expected behavior

The following two expressions should produce the same AST.

```elixir
quote do
  unquote(:foo) do
    "bar"
  end
end

# {:foo, [], [[do: "bar"]]}

quote do
  unquote(:foo)() do
    "bar"
  end
end

# {:foo, [], [[do: "bar"]]}
```

---

I have been able to reproduce this with a test in the elixir-lang repo, but I haven't had any luck figuring out the fix.

**Comment by josevalim** [comment]
@mhanberg yes, if you look at the ast returned, you can see you are calling unquote/2:

```
quote do
  unquote(:foo) do
    "bar"
  end
end
# {:foo, [], [[do: "bar"]]}
```

This is following Elixir's regular language rules. Replace `unquote` by anything else and you will see what I mean:

```
if(:foo) do
  "bar"
end
```

And we shouldn't treat unquote especially, because if we do, then we will break existing code.

**Comment by mhanberg** [comment]
Oh, good catch. Thanks!

How should I format this code then?

The following does what I want,  but the formatter will remove the parens and change the code to call `unquote/2` like you mentioned above. 

```elixir
quote do
  unquote(:foo)() do
    "bar"
  end
end

# {:foo, [], [[do: "bar"]]}
```

**Comment by josevalim** [comment]
Oh, a formatter bug! You should play in the lottery, we don't have many of those anymore. :D I have opened a new report here #9204. You can work-around it for now by not using blocks:

```elixir
quote do
  unquote(:foo)(do: "bar")
end
```

**Comment by mhanberg** [comment]
I originally thought it was a formatter bug! Maybe i should trust my instincts... thanks!
