### ISSUE TITLE
String.split/3 with regex and including captures does not preserve :parts option

### ISSUE THREAD

**Issue by sebsel** [elixir-lang/elixir#9219]
* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.8.1 (compiled with Erlang/OTP 21)
* Operating system: macOS 10.14.5

I'm not sure if this a bug or intended behaviour, but I could not find a real answer in existing issues. Also, the tests do not cover this part, so it seems like there is either no decision made, or it is really a bug :)
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/string_test.exs#L78

When using `String.split/3` with a regex, a special option `:include_captures` comes available. When used in conjunction with the `:parts` option, the captures do not count towards the parts. It kind of makes sense they are not counted, because the caller asks for both, but it also makes sense to count them, for the caller clearly wants two parts.

The related method `Regex.split/3` has the same behaviour, and it's tests also do not test this case.
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/regex_test.exs#L255

### Current behaviour

```elixir
iex(1)> String.split("1,2,3", ~r/,/, include_captures: true, parts: 2)
["1", ",", "2,3"]
iex(2)> Regex.split(~r/,/, "1,2,3", include_captures: true, parts: 2)
["1", ",", "2,3"]
iex(3)> Regex.split(~r/,/, ",2,3", include_captures: true, parts: 2)
["", ",", "2,3"]
iex(4)> Regex.split(~r/,/, ",2,3", include_captures: true, parts: 2, trim: true)
[",", "2,3"]
iex(5)> Regex.split(~r/,/, "1,2,3", include_captures: true, parts: 2, trim: true)
["1", ",", "2,3"]
iex(6)> Regex.split(~r/,/, "1,2,3,4,5,6,7,8,9,0", include_captures: true, parts: 5)
["1", ",", "2", ",", "3", ",", "4", ",", "5,6,7,8,9,0"]
```

### Expected behaviour

```elixir
iex(1)> String.split("1,2,3", ~r/,/, include_captures: true, parts: 2)
["1", ",2,3"]
iex(2)> Regex.split(~r/,/, "1,2,3", include_captures: true, parts: 2)
["1", ",2,3"]
iex(3)> Regex.split(~r/,/, ",2,3", include_captures: true, parts: 2)
["", ",2,3"]
iex(4)> Regex.split(~r/,/, ",2,3", include_captures: true, parts: 2, trim: true)
[",", "2,3"]
iex(5)> Regex.split(~r/,/, "1,2,3", include_captures: true, parts: 2, trim: true)
["1", ",2,3"]
iex(6)> Regex.split(~r/,/, "1,2,3,4,5,6,7,8,9,0", include_captures: true, parts: 5)
["1", ",", "2", ",", "3,4,5,6,7,8,9,0"]
```

Again, there is something to say for the current situation too. Happy to PR with tests to document and ensure the current behaviour, or to look into fixing it if it turns out to be a bug.

**Comment by josevalim** [comment]
Good find!

I think we should keep the current behavior, to avoid changes, as you said
it can also be justified.  Indeed, I think parts is about how many times we
split and not on how many entries we return. So we can say that the capture
is not counted towards the parts, with the relevant docs and tests.

Also note that include_captures is soft deprecated for String, so we can
focus on this behavior exclusively on the Regex module.
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by sebsel** [comment]
Made a PR!

> Indeed, I think parts is about how many times we split and not on how many entries we return.

This is not really valid, I would say... the option should've been called `:splits`, if that were the case.

I still think the current behaviour is less expected, but, I understand the argument for not breaking things, even in such an edge case. Still happy to PR the other way though :)
