### ISSUE TITLE
Broken link in Mix Test documentation, Missing ExUnit.cli_formatter docs

### ISSUE THREAD

**Issue by nevadajames** [elixir-lang/elixir#9221]
### Current Behaviour
The link to `ExUnit.CLIFormatter`  in the description of the `--formatter` option in the documentation for Mix.Tasks.Test is broken.
- Mix.Tasks.test docs https://hexdocs.pm/mix/master/Mix.Tasks.Test.html
- Broken link https://hexdocs.pm/ex_unit/ExUnit.CLIFormatter.html

![Screen Shot 2019-07-13 at 16 29 09](https://user-images.githubusercontent.com/24971740/61172918-fb7fba80-a58b-11e9-8a51-e3a1603dfe75.png)

### Expected Behaviour
The link should work correctly and lead me to the corresponding documentation.

### More info
This seems due to the fact that there is no corresponding documentation for ExUnit.CLIFormatter.
Seems like there are two possible solutions: 
- Add moduledoc for `elixir/lib/ex_unit/lib/ex_unit/cli_formatter.ex` 
- Update the module_doc for ` lib/mix/lib/mix/tasks/test.ex` to refer just to the ExUnit docs for more information,
here is a link to the problematic code:

https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/test.ex#L168

**Comment by josevalim** [comment]
Thanks @nevadajames! I think we should just say "Defaults to ExDoc's built-in CLI formatter". What do you think? Can you please send a PR?

**Comment by nevadajames** [comment]
@josevalim, sounds like a good solution to me. I'll start a PR
