### ISSUE TITLE
Internal consistency check failed

### ISSUE THREAD

**Issue by JayachandraGunturu** [elixir-lang/elixir#9233]
Environment

*Erlang/OTP versions (elixir --version): Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

* Operating system: CentOS7

Current behavior
kz_att_ftp: function send_request/5+164:
  Internal consistency check failed - please report this bug.
  Instruction: {put_list,{y,7},nil,{x,0}}
  Error:       {unassigned,{y,7}}:

/opt/kazoo/make/kz.mk:86: recipe for target 'ebin/kazoo_attachments.app' failed

### Expected behavior

Building of kazoo/core

**Comment by josevalim** [comment]
@JayachandraGunturu kazoo/core is written in Erlang, so you want to report it in Kazoo so they can provide a minimum case for the Erlang/OTP team. But this is most likely something related to your OTP version. Maybe using Erlang/OTP 21 works? Thanks!

**Comment by sergey-safarov** [comment]
[Ticket opened.](https://bugs.erlang.org/browse/ERL-1128)
