### ISSUE TITLE
Some examples not showing up in IEx

### ISSUE THREAD

**Issue by hassanshaikley** [elixir-lang/elixir#9235]
### Environment
```
Erlang/OTP 22 [erts-10.4.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 20
```

macOS Mojave

### Current behavior

Some examples don't show up.

<img width="651" alt="Screen Shot 2019-07-23 at 1 52 15 AM" src="https://user-images.githubusercontent.com/6746840/61698139-7617ab00-aced-11e9-8c3e-d244cb71e8e8.png">

However when I built from source they did.

<img width="653" alt="Screen Shot 2019-07-23 at 1 52 11 AM" src="https://user-images.githubusercontent.com/6746840/61698145-79129b80-aced-11e9-855a-76e73dba6842.png">

Does this mean that this issue has already been fixed and not released yet or could it be something else?

### Expected behavior

I expected it to display the example.

**Comment by wojtekmach** [comment]
The docs change landed on master, it will be available on Elixir v1.10. You can see it here: https://hexdocs.pm/elixir/master/Agent.html#cast/4. Usually only bug fixes are backported to latest stable branches.
