### ISSUE TITLE
IEx.pry broken in Emacs shell

### ISSUE THREAD

**Issue by danbikle** [elixir-lang/elixir#9239]
Github issues might suggest to some, this is a windows bug.

I see it as a Emacs-shell-IEx.pry bug.

On Ubuntu, this is an easy bug to reproduce.

- I found an Ubuntu 16.04 account.
- I installed Elixir with the shell commands listed below:

```
cd ~/Downloads
wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
sudo dpkg -i erlang-solutions_1.0_all.deb
sudo apt update
sudo apt install esl-erlang
sudo apt install elixir
```

I saw this after my installation:

```
dan@p95:~/Downloads $ elixir -v
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] 
[async-threads:1] [hipe]

Elixir 1.9.0 (compiled with Erlang/OTP 21)
dan@p95:~/Downloads $ 
dan@p95:~/Downloads $
```

Next I installed Emacs with one shell command:

```
sudo apt install emacs
```

I saw this after emacs installation:

```
dan@p95:~/Downloads $ emacs --version
GNU Emacs 24.5.1
```

Next, I started emacs with shell command: 

```
emacs
```

Inside of Emacs I started a shell with emacs-command: 

```
esc x shell
```

In that shell I started IEx:

```
iex
```

Inside of IEx I typed two commands:

```
break! String.length/1
String.length "hi"
```

I encountered the IEx.pry() bug next:

```
dan@p95:~ $ 
dan@p95:~ $ iex
Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> break! String.length/1
1
iex(2)> String.length "hi"

Break reached: 
String.length/1 (/root/deb/elixir_1.9.0-1/lib/elixir/lib/string.ex:1779)

Cannot pry #PID<0.103.0> at String.length/1 
(/root/deb/elixir_1.9.0-1/lib/elixir/lib/string.ex:1779). 
Is an IEx shell running?
2
iex(3)>
```

Look closely, you will see the bug above.

Next I tried the same commands in a Linux-Terminal-window:

```
dan@p95:~ $ iex
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:4:4] [ds:4:4:10]
[async-threads:1] [hipe]

Interactive Elixir (1.9.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> break! String.length/1
1
iex(2)> String.length "hi"
Break reached: String.length/1 
(/root/deb/elixir_1.9.0-1/lib/elixir/lib/string.ex:1779)

pry(1)> binding
[string: "hi"]
pry(2)> 
```

The bug does not appear in my Terminal-window session.

So, IEx.pry works well in the Terminal which is a sufficient work-around for me.

I doubt the bug needs to be fixed but I want fellow Emacs-people to be
aware of the bug because the simple work-around is not obvious.

**Comment by josevalim** [comment]
Thanks @danbikle for the detailed report. The bug has been fixed but the reason it happened is because your emacs shell is not being considered a TTY (maybe it isn't) and therefore a limited version of the shell is running. Although break points should work on the limited version the shell (hence the fix above), you will be missing other features.
