### ISSUE TITLE
mix release command

### ISSUE THREAD

**Issue by Paradox-3arthling** [elixir-lang/elixir#9242]
![Capture8](https://user-images.githubusercontent.com/11226110/61934023-0412c080-af90-11e9-9f0a-2f71af3b31bc.PNG)

### Environment

- In ScreenShot
### Current behavior

- It starts but then exits saying "No file named projects\pass\_build\prod\rel\pass\releases\0.1.0\\..\..\erts-10.0.1\bin\erl.exe"
- check screenshot.
### Expected behavior

for the error not to appear or a better error message for me to act on.

**Comment by josevalim** [comment]
What is your operating system? I am assuming Windows?

I am alsso assuming that "starting escalations..." is being logged by your app... which means that the app is starting successfully and then your code is the one failing, not Elixir releases. Do you have a way for us to reproduce the issue so we can find out the root cause?

**Comment by Paradox-3arthling** [comment]
Thanks for replying quickly... 
when a release is made under a directory/sub-directory with a space is where the error appears.

**Comment by josevalim** [comment]
@Paradox-3arthling I see. But, as I mentioned above, the release seems to boot fine and our tests check releases in paths with spaces in them. So we would need a way to reproduce the issue.

Have you tried creating a brand new application and releasing it? Do you see the same error?

**Comment by Paradox-3arthling** [comment]
@josevalim  Yap just confirmed it.... create one project in a file with spaces i.e "test app" and another without i.e "test_app" and try releasing them from those directories

**Comment by josevalim** [comment]
Do you get the same error when there are spaces? Can you post the logs?

Also, which terminal are you using to run the releases? Windows CMD? Powershell? Ubuntu subsystem? I have just double checked that our test suite does run tests with spaces in the directory, so something else has to be at play here.

Thanks!

**Comment by Paradox-3arthling** [comment]
this is how I recreated it from scratch with Windows CMD
E:\test>mkdir "test app"

E:\test>cd "test app"

E:\test\test app>mix new test_app
* creating README.md
* creating .formatter.exs
* creating .gitignore
* creating mix.exs
* creating lib
* creating lib/test_app.ex
* creating test
* creating test/test_helper.exs
* creating test/test_app_test.exs

Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:

    cd test_app
    mix test

Run "mix help" for more commands.

E:\test\test app>cd test_app

E:\test\test app\test_app>mix release.init
* creating rel/vm.args.eex
* creating rel/env.sh.eex
* creating rel/env.bat.eex

E:\test\test app\test_app>mix release
Compiling 1 file (.ex)
Generated test_app app
* assembling test_app-0.1.0 on MIX_ENV=dev
* skipping runtime configuration (config/releases.exs not found)
* creating _build/dev/rel/test_app/releases/0.1.0/vm.args
* creating _build/dev/rel/test_app/releases/0.1.0/env.sh
* creating _build/dev/rel/test_app/releases/0.1.0/env.bat

Release created at _build/dev/rel/test_app!

    # To start your system
    _build/dev/rel/test_app/bin/test_app start

Once the release is running:

    # To connect to it remotely
    _build/dev/rel/test_app/bin/test_app remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/dev/rel/test_app/bin/test_app stop

To list all commands:

    _build/dev/rel/test_app/bin/test_app


E:\test\test app\test_app>"_build/dev/rel/test_app/bin/test_app" start
No file named app\test_app\_build\dev\rel\test_app\releases\0.1.0\\..\..\erts-10.0.1\bin\erl.exe

E:\test\test app\test_app>

**Comment by Paradox-3arthling** [comment]
But this runs, difference being the parent directory name:
E:\test>mkdir "test_app"

E:\test>cd "test_app"

E:\test\test_app>mix new test_app
* creating README.md
* creating .formatter.exs
* creating .gitignore
* creating mix.exs
* creating lib
* creating lib/test_app.ex
* creating test
* creating test/test_helper.exs
* creating test/test_app_test.exs

Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:

    cd test_app
    mix test

Run "mix help" for more commands.

E:\test\test_app>cd test_app

E:\test\test_app\test_app>mix release.init
* creating rel/vm.args.eex
* creating rel/env.sh.eex
* creating rel/env.bat.eex

E:\test\test_app\test_app>mix release
Compiling 1 file (.ex)
Generated test_app app
* assembling test_app-0.1.0 on MIX_ENV=dev
* skipping runtime configuration (config/releases.exs not found)
* creating _build/dev/rel/test_app/releases/0.1.0/vm.args
* creating _build/dev/rel/test_app/releases/0.1.0/env.sh
* creating _build/dev/rel/test_app/releases/0.1.0/env.bat

Release created at _build/dev/rel/test_app!

    # To start your system
    _build/dev/rel/test_app/bin/test_app start

Once the release is running:

    # To connect to it remotely
    _build/dev/rel/test_app/bin/test_app remote

    # To stop it gracefully (you may also send SIGINT/SIGTERM)
    _build/dev/rel/test_app/bin/test_app stop

To list all commands:

    _build/dev/rel/test_app/bin/test_app


E:\test\test_app\test_app>"_build/dev/rel/test_app/bin/test_app" start


![Capture8](https://user-images.githubusercontent.com/11226110/61942960-19451a80-afa3-11e9-9e04-2abc4535e7a4.PNG)

**Comment by josevalim** [comment]
Excellent, thank you! I was able to reproduce it and I am working on a fix!

**Comment by josevalim** [comment]
In any case, it is very surprising that our tests do not catch this even though it has directories with spaces. I tried to reproduce the failure in our suite but it always works, although it does fail as a user input.

**Comment by Paradox-3arthling** [comment]
@josevalim no problem, am just happy I could solve an issue in a language I :heart:  :)
Just an honor to be able to talk to u and do something, even though a little, for this language :grinning:
