### ISSUE TITLE
simultaneously accessing files give random :enoent

### ISSUE THREAD

**Issue by WannesFransen1994** [elixir-lang/elixir#9258]
### Precheck

- [x] not help or support => This irregular behavior is indeed causing me problems, but not asking to give a solution to my problem, just whether this behavior is expected or not
- [X] not a feature
- [X] not an existing bug, nor a security vulnerability as far as i could find
_Small note: this behavior was detected during development with Phoenix. But considering it was just reading multiple files, regardless of the send_file function, this sounded to me like it might be an elixir problem instead of Phoenix?_
### Environment
output iex -v : Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

* Operating system: Ubuntu 18.04.2 Bionic Beaver LTS

### Current behavior
Reproduced the problem at https://github.com/WannesFransen1994/phoenix-dynamic-images
Reading multiple images at once with either  File.read or File.exists returns a random result. This is tested within a phoenix application where I display an image through a route: 
```elixir
def display(conn, %{"id" => id}) do
    i = Repo.get(Image, id)

    case File.exists?(Image.local_path(i)) do
      true ->
        Logger.info("File with ID #{i.id} exists")

      false ->
        Logger.warn(
          "File with ID #{i.id}, path #{Image.local_path(i)} doesn't exist. Listing image folder content #{
            inspect(Path.wildcard("uploads/images/*"))
          }"
        )
    end

    conn |> put_resp_content_type(i.content_type) |> send_file(200, Image.local_path(i))
  end
```
when going to localhost:4000/image/1 it renders always
when rendering multiple images in an overview page, some images randomly crash due to not being able to read the file:
```
(exit) an exception was raised:
    ** (File.Error) could not read file stats "uploads/images/3-02-full.jpg": no such file or directory
        (elixir) lib/file.ex:403: File.stat!/2
```
Output from the Logger.warn when File.exists returns false
```
[warn] File with ID 1, path uploads/images/1-01-full.jpg doesn't exist. Listing image folder content []
```
=> note that this is completely random (though most likely random for me has a completely logical explanation for the people I'm asking this to ^^'). 

### Expected behavior
I expect that files can be read simultaneously.

**Comment by josevalim** [comment]
@WannesFransen1994 can try the code below?

```elixir
def display(conn, %{"id" => id}) do
    cwd = File.cwd!
    i = Repo.get(Image, id)

    case File.exists?(Image.local_path(cwd, i)) do
      true ->
        Logger.info("File with ID #{i.id} exists")

      false ->
        Logger.warn(
          "File with ID #{i.id}, path #{Image.local_path(cwd, i)}, cwd #{cwd}, doesn't exist. Listing image folder content #{
            inspect(Path.wildcard(Path.join(cwd, "uploads/images/*")))
          }"
        )
    end

    conn |> put_resp_content_type(i.content_type) |> send_file(200, Image.local_path(i))
  end
```

And when the error happens, look at the current working directory. My guess it that something is changing the current working directory (Phoenix code reloader does it for example) and that is causing your path lookups to fail. The correct solution is to use absolute paths. Either have a path in your OS with the uploads (common in production) or put it in `priv` and use `Application.app_dir(:my_app, "uploads/images")` to read it.

**Comment by WannesFransen1994** [comment]
Thank you josevalim, that's exactly it!
Also thanks for the tip regarding the Phoenix code reloader (or something else). I'll work with absolute paths from now on.

Hereby closing the issue.
