### ISSUE TITLE
Pattern diffing should always compare tuples positionally

### ISSUE THREAD

**Issue by michalmuskala** [elixir-lang/elixir#9259]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): master
* Operating system: macOS

### Current behavior

When the new ex_unit pattern diffing deals with tuples, it treats them similarly to lists, just with different delimiters. This is not correct and leads to poor errors, for example:

<img width="680" alt="Screenshot 2019-08-02 at 15 03 38" src="https://user-images.githubusercontent.com/477062/62372055-c0432c80-b536-11e9-8cdc-0516feb42c0a.png">

### Expected behavior

The error should show a mismatch on the `ok`/`error` atoms in the first position.

**Comment by ggcampinho** [comment]
For tuples with different sizes, should it just show the tuple as wrong?

**Comment by josevalim** [comment]
@ggcampinho I think we should match by position for the available positions and any of the extra positions should be tagged as removals or additions depending on the side.

**Comment by ggcampinho** [comment]
Apparently, it's also missing a comma, maybe some algebra error.
