### ISSUE TITLE
Support American (USA) spelling of @behavior

### ISSUE THREAD

**Issue by sikanrong** [elixir-lang/elixir#9269]
### Environment

* Elixir & Erlang/OTP versions: **all versions**
* Operating system: **all OS**

### Current behavior
```
defmodule MyMod do 
    @behavior GenServer
end
```
warning: @behavior attribute is not supported, please use @behaviour instead

### Expected behavior

(should accept the "@behavior" attribute just as it would "@behaviour") 

In general, the language should always support both British and US spelling styles, so as to be maximally inclusive to the global development community.

**Comment by sikanrong** [comment]
Fun observation: even the Github issue template for this project uses the US spelling "behavior". US spelling style is doubtlessly the one in more common use throughout the world.

**Comment by josevalim** [comment]
Please start a discussion on the elixir core mailing list but generally speaking, having two ways of doing the same thing is arguably worst than having a single way, even if surprising.

**Comment by sikanrong** [comment]
> having two ways of doing the same thing is arguably worst than having a single way, even if surprising.

While normally I would agree; I just don't see this as being two ways of doing the same thing. I could see how it could be interpreted that way, but really all we're asking for is an alias.

**Comment by josevalim** [comment]
Well, it is literally two ways of achieving the same behaviour. :) If we add this, we increase the odds that in the same codebase some can use `@behaviour` and others use `@behavior`. Especially on teams composed by different people around the world, which will more naturally pick one or another.

**Comment by fertapric** [comment]
For the record, [this was supported at some point and deprecated](https://github.com/elixir-lang/elixir/commit/5f682023a6bbc59d277071395d552b61ed36258a) probably for the reasons @josevalim mentioned above

**Comment by wojtekmach** [comment]
If we support `@behavior` then arguably we should also automatically define a `module.behavior_info/1`, `IO.ANSI.colour*` aliases and likely much much more, and I'm not sure if that's beneficial enough to justify all these changes.

**Comment by sikanrong** [comment]
@wojtekmach actually this is really the change that I'd wanted to see - that _everything_ with a british spelling to be aliased with the US spelling as well. 

Anyway guys, after reading your comments I can at least better understand the logic behind not supporting it, and the fact that perhaps it would not be desirable that in a given project people might be using both spellings, etc.
