### ISSUE TITLE
Unable to run Elixir programs in Visual Studio Code

### ISSUE THREAD

**Issue by andy289** [elixir-lang/elixir#9279]
#9042 # Environment

* Elixir & Erlang/OTP versions - 1.9.1
* Operating system: Windows 10 1903

### Current behavior

No file associations set by Windows Installer for '.exs' or '.ex'. This causes Visual Code Studio to fail to run an Elixir program or debug it. I would have set these myself, but the appropiate tool in Windows Settings has diappeared as well and I do not really like playing with Windows registery settings.

### Expected behavior

Windows Studio Code to run Elixir scripts and programs seemlessly "out of the box" after Elixir plugin installed for WSC.

**Comment by josevalim** [comment]
Hi @andy2891 👋  You should reach out to the authors of the plugin and talk to them about what can possibly be wrong. The VS Code plugin is not maintained the Elixir team. You can also reach out to the ElixirForum for general discussion and see if someone has already ran into it.
