### ISSUE TITLE
Add :clean release step

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#9288]
This step will clean the release directory rel/. It can be useful to run before assembling to release to ensure you have a fresh release without old versions. For example: `steps: [:clean, :assemble]`.

**Comment by josevalim** [comment]
@ericmj clarification: it will clean rel/ for the current release name.

**Comment by Ianleeclark** [comment]
Hey, I'd like to take a stab at this one! I should have the availability to get something out this tomorrow or during this weekend.

**Comment by josevalim** [comment]
Hi @Ianleeclark. We probably won't have a need for this because the implementation of the `:tar` step won't require it anymore. We will close this for now until we are sure. Thanks!
