### ISSUE TITLE
Add :tar release step

### ISSUE THREAD

**Issue by ericmj** [elixir-lang/elixir#9289]
This step will put the release inside a tarball. For example: `steps: [:assemble, :tar]`.

**Comment by josevalim** [comment]
@Gazler I believe you have already written this code? Could you share the snippet here if you are allowed to?

**Comment by Gazler** [comment]
Yup, posted it on this issue: https://github.com/elixir-lang/elixir/issues/8612#issuecomment-494456304

**Comment by Gazler** [comment]
I am happy to open a PR if we want this in the mix task btw.

**Comment by ericmj** [comment]
Is there any benefit of using the functionality from systools?

**Comment by tsloughter** [comment]
@ericmj yes, systools `make_tar` ensures only the files for the particular release version are included in the tarball. I commented on the PR about this.

**Comment by josevalim** [comment]
Closing in favor of the PR.
