### ISSUE TITLE
Standardize function expressions with multiple arities `fun/1,2` in the documentation

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#9295]
As discussed in [the Elixir mailing list](https://groups.google.com/forum/#!topic/elixir-lang-core/75Rz_Ds-aEk/discussion).

cc @hassanshaikley

**Comment by hoominkani** [comment]
@fertapric 
May I try it?
This is the first time for me to contribute to open source.
I will convert function expressions with multiple arities like `fun/1/2` to `fun/1,2` in the documentation.

**Comment by josevalim** [comment]
> I will convert function expressions with multiple arities like fun/1/2 to fun/1,2 in the documentation.

Perfect. Please go ahead and let us know if you have any questions.
