### ISSUE TITLE
missing env var error for config provider path during release assembly

### ISSUE THREAD

**Issue by adamkittelson** [elixir-lang/elixir#9298]
### Environment

* erlang 22.0.7
* elixir 1.9.0
* bitwalker/toml-elixir, ref: "476136b47265e06cea0ced80d37602ec99fa5a7b"

### Current behavior

I'm working on migrating a project from using Distillery to using Elixir 1.9 releases using the toml config provider from https://hex.pm/packages/toml and I noticed some behavior that surprised me.

When configuring the provider to use a system tuple for the path like so:

```
config_providers: [
          {Toml.Provider,
           [
             path: {:system, "RELEASE_CONFIG_DIR", "my_app.toml"},
             transforms: []
           ]}
        ]
```
I get an error stating that the env var RELEASE_CONFIG_DIR is not set when assembling the release.

```
* assembling my_app-x.x.x on MIX_ENV=prod
** (ArgumentError) could not fetch environment variable "RELEASE_CONFIG_DIR" because it is not set
    (elixir) lib/system.ex:518: System.fetch_env!/1
    (elixir) lib/config/provider.ex:134: Config.Provider.resolve_config_path!/1
    lib/provider.ex:177: Toml.Provider.expand_path/1
    lib/provider.ex:69: Toml.Provider.init/1
    (elixir) lib/config/provider.ex:139: anonymous fn/2 in Config.Provider.init/3
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/config/provider.ex:139: Config.Provider.init/3
    (mix) lib/mix/release.ex:344: Mix.Release.merge_provider_config/3
```

However if I just set a full path to the file (which is also missing on the build server during release assembly) like so:

```
config_providers: [
          {Toml.Provider,
           [
             path: "/path/to/my_app.toml",
             transforms: []
           ]}
        ]
```
it gets through the assembly step without error and correctly finds the file on the app server when I boot the application.

### Expected behavior

The part that surprises me is that it seems the that if one wants to use the system tuple form it would appear the env var must be set while building the release, even though I believe there's no reason to expect the path to actually point to a file during release assembly.

This is due to the usage of System.fetch_env! when resolving the path at https://github.com/elixir-lang/elixir/blob/40756137278cd5ee2e182e86265c21f0a248808d/lib/elixir/lib/config/provider.ex#L135 instead of something like System.get_env/2, but ultimately the source of my surprise is that the path resolution is happening during release assembly at all. I'm not sure if that's specific to the Toml provider or if that's how providers work in general though, so apologies if I'm barking up the wrong tree.

Thanks!
Adam

**Comment by josevalim** [comment]
That would be definitetly be up to the TOML provider, as it is the one effecttively calling `resolve_config_path`. Please open up an issue there and if there is anything we can do here please let us know! Thank you!

**Comment by adamkittelson** [comment]
Thanks Jose! Would I be correct in assuming that this issue could arise if resolve_config_path is called in the init function of the provider rather than the load function?

**Comment by josevalim** [comment]
@adamkittelson yes!
