### ISSUE TITLE
Crash in Mix.Compilers.Elixir.parse_manifest/2

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#9308]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Operating system: macOS 10.14.6

### Current behavior

This happened when I returned to a project (phoenix app, not an umbrella) after some time.
```
git pull
mix deps.get
mix test
...
Generated phoenix_ecto app
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1    
    
    The following arguments were given to IO.chardata_to_string/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 2 out of 2):
    
        def chardata_to_string(string) when is_binary(string)
        def chardata_to_string(list) when is_list(list)
    
    (elixir) lib/io.ex:557: IO.chardata_to_string/1
    (elixir) lib/path.ex:524: Path.do_join/3
    (elixir) lib/path.ex:517: Path.join/2
    (mix) lib/mix/compilers/elixir.ex:524: anonymous fn/3 in Mix.Compilers.Elixir.parse_manifest/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/compilers/elixir.ex:523: Mix.Compilers.Elixir.parse_manifest/2
    (mix) lib/mix/compilers/elixir.ex:40: Mix.Compilers.Elixir.compile/6
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
```
after
```
mix clean
```
the crash is no longer reproducible.

**Comment by josevalim** [comment]
We need to know which elixir version you last compiled the project with. We did have some bugs on how we read the manifest file and we fixed those. So without more info to reproduce the issue we can’t do much.

**Comment by lukaszsamson** [comment]
@josevalim I might have tried compiling this project on 1.10 master about 2 weeks ago. I don't remember if I recompiled it on 1.9 afterwards.

**Comment by josevalim** [comment]
@lukaszsamson ah, in rare cases we may break forwards compatibility. In this case, the module struct has changed in v1.10 which is incompatible with v1.9 and our attempt to clean fails. I will make sure that we raise at least a reasonable error message.
