### ISSUE TITLE
Enum.dedup_by logic

### ISSUE THREAD

**Issue by ayrat555** [elixir-lang/elixir#9312]
### Environment

* Elixir & Erlang/OTP versions:
```
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```
* Operating system:  `Linux`

### Current behavior

Currently, it looks like `Enum.dedup_by` does not consider passed function if items are equal.

```
iex(1)> Enum.dedup_by([%{val: 5}, %{val: 5}], fn item -> item.val == 0 end)
[%{val: 5}]
```

```
iex(5)> Enum.dedup_by([%{val: 5}, %{val: 5}], fn item -> item.val < 0 end)                
[%{val: 5}]
```

### Expected behavior

It should use a passed function to determine if items are equal

```
iex(1)> Enum.dedup_by([%{val: 5}, %{val: 5}], fn item -> item.val == 0 end)
[%{val: 5}, %{val: 5}]
```

**Comment by josevalim** [comment]
@ayrat555 the second argument to `dedup_by` is not boolean logic. It is rather the value you want to "dedup by". Since both return `false`, then they are considered the same, because the function is returning the same value. You want something more akin to this:

```elixir
iex(3)> Enum.dedup_by([%{val: 5}, %{val: 5}], fn item -> if item.val == 0, do: :dup, else: System.unique_integer  end)
[%{val: 5}, %{val: 5}]
```
