### ISSUE TITLE
Using Keyword.replace! messes the order of the keys in a keyword list

### ISSUE THREAD

**Issue by spapas** [elixir-lang/elixir#9315]
### Environment
Using Windows 10 with: 
```
C:\Users\serafeim>elixir --version
Erlang/OTP 21 [erts-10.1] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.9.0 (compiled with Erlang/OTP 20)
```

### Current behavior

```
iex(1)> [a: 3, b: 4, c: 5] |> Keyword.replace!(:b, 11)
[b: 11, a: 3, c: 5]
```

### Expected behavior

I expected the order of the keys in the keyword list to not be messed up.

Notice that I have the same behavior with `Keyword.put`. On the other hand, `Keyword.update!` doesn't change the order of the keys:

```
iex(6)> [a: 3, b: 4, c: 5] |> Keyword.update!(:b, &(&1+1))
[a: 3, b: 5, c: 5]

```

**Comment by jjl** [comment]
At first I thought there might have been performance implications to this, but I've now satisfied myself that there aren't (save for possible microoptimisations in a rather specific use case):

```
[a: 1, b: 2, c: 3, d: 4, e: 5]

replace value at `:c` with 6

before: 2 entries
after: 2 entries

current: [{:c, 6} | before] ++ after
proposed: before ++ [{:c, 6} | after ]
```
