### ISSUE TITLE
Mix.Tasks.Xref.calls returns the wrong caller

### ISSUE THREAD

**Issue by sasa1977** [elixir-lang/elixir#9322]
### Environment

Elixir 1.9.1, Erlang/OTP 22

### Current behavior

It seems that `Mix.Tasks.Xref.calls/0` gets confused when multiple modules are defined in the same file.

For example, consider the following contents of a single file in a mix project:

```elixir
defmodule A do
  def some_fun, do: B.some_fun()
end

defmodule B do
  def some_fun, do: :ok
end
```

Trying xref in iex:

```elixir
iex> Mix.Tasks.Xref.calls() |> Enum.find(&(&1.callee == {B, :some_fun, 0}))
%{callee: {B, :some_fun, 0}, caller_module: B, file: "lib/test.ex", line: 2}
```

Notice how caller_module is `B` when it should be `A`.

A seemingly related problem happens when the modules are nested:

```elixir
defmodule Top do
  defmodule C do
    def some_fun, do: Top.D.some_fun()
  end

  defmodule D do
    def some_fun, do: :ok
  end
end
```

In this case, we get:

```elixir
iex> Mix.Tasks.Xref.calls() |> Enum.find(&(&1.callee == {Top.D, :some_fun, 0}))
%{
  callee: {Top.D, :some_fun, 0},
  caller_module: Top,
  file: "lib/test2.ex",
  line: 3
}
```

I.e. `caller_module` is `Top` instead of `Top.C`.

**Comment by josevalim** [comment]
Yes, this is a bug that is fixed in master but in master the implementation of xref calls is much slower because we traverse beams. The fastest way to implement this in master is by using compilation tracers: https://hexdocs.pm/elixir/master/Code.html#module-compilation-tracers - you can store the information in a table and then access them in your pass. You can configure them in Mix like this:

    elixirc_options: [tracers: [Boundary]]

**Comment by sasa1977** [comment]
> The fastest way to implement this in master is by using compilation tracers

OK, this looks quite interesting, thanks! I guess that the road forward would be to build boundary on top of tracers in 1.10?

**Comment by josevalim** [comment]
Yes, that's what will be most performant and give the most amount of information.
