### ISSUE TITLE
`mix release` option `:runtime_config_path` is resolved at build time, not runtime

### ISSUE THREAD

**Issue by talentdeficit** [elixir-lang/elixir#9323]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  1.9.x
* Operating system: n/a

### Current behavior

[here](https://github.com/elixir-lang/elixir/blob/d44da48ee108de4166d961d5bf94dd4c8584f0f2/lib/mix/lib/mix/tasks/release.ex#L1099) the `mix release` task copies the file given as an argument to `:runtime_config_path` into the release and configures `Config.Reader` to read from the resulting path inside the release

### Expected behavior

the path given as `:runtime_config_path` will be read at runtime, not build time, and will not be copied into the release directory

**Comment by talentdeficit** [comment]
this is relatively easy to work around with a custom config provider that wraps `Config.Reader` but the combination of the option name (`:runtime_config_path`) and the sparse documentation do not indicate this is necessary

**Comment by josevalim** [comment]
Thanks @talentdeficit!

> the sparse documentation do not indicate this is necessary

Is the documentation sparse only around this option or generally? Any other gaps we need to fill?

> this is relatively easy to work around with a custom config provider that wraps Config.Reader

You don't need to wrap `Config.Reader`, you can use it directly, I have also pushed some examples to the `Config.Reader` module.
