### ISSUE TITLE
Feature Request: Built in breakpoint

### ISSUE THREAD

**Issue by Olshansk** [elixir-lang/elixir#9325]
There are two things I wanted to mention:

1. I'm not 100% sure if this is best forum for new feature requests, so please let me know if I should repost elsewhere.
2. I'm willing to do this myself, but was hoping for some feedback before I put the time into it.

I recently read [this](https://hackernoon.com/python-3-7s-new-builtin-breakpoint-a-quick-tour-4f1aebc444c) article about breakpoints in python 3, which implemented [PEP553](https://www.python.org/dev/peps/pep-0553/), and a few things stood out

1. A breakpoint function is built-in, not requiring imports (i.e. requires). I realize adding a require is not hard, but having `breakpoint` become a function that's accessible everywhere will really reduce the friction for its usage.
2. Breakpoints can be enabled/disabled via an environment variable. This can be the default in production to avoid unnecessary requires.
3. The type of debugger can be modified via the environment variable as well. This is probably not necessary for the first iteration of this.

**Comment by josevalim** [comment]
Hi @Olshansk, the best place to discuss new issues is at: https://groups.google.com/group/elixir-lang-core - this information is also linked in the README and in the issue template.

Regarding the breakpoint, one of the concerns is that it only works inside IEx, so skipping the IEx require can be a bit contradictory. Also, regarding point 2, I really hope folks are not shipping code to production with breakpoints in them. :) Having to rely on an environment variable for that sounds a bit scary. Anyway, those are best discussed in the linked mailing list, thanks for the issue!

**Comment by Olshansk** [comment]
Thanks for the quick reply Jose!

It seems like the suggestion is unlikely to go through based on your feedback, but I'll reach out to the community anyhow :)
