### ISSUE TITLE
In a `if` condition, assignments on the right hand of `&&` don't work as expected

### ISSUE THREAD

**Issue by dsdshcym** [elixir-lang/elixir#9326]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.10.0-dev (1059b86) (compiled with Erlang/OTP 22)`
* Operating system: macOS 10.14.6 (18G87)

### Current behavior

```elixir
iex(1)> if (a = 1) && (b = 2), do: b
warning: variable "b" is unused (if the variable is not meant to be used, prefix it with an underscore)
  iex:1

** (CompileError) iex:1: undefined function b/0
    (stdlib 3.9.2) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.9.2) lists.erl:1355: :lists.mapfoldl/3
    (stdlib 3.9.2) lists.erl:1354: :lists.mapfoldl/3
    (elixir 1.10.0-dev) expanding macro: Kernel.if/2
```

But the left hand assignment works:
```elixir
iex(1)> if (a = 1) && (b = 2), do: a
warning: variable "b" is unused (if the variable is not meant to be used, prefix it with an underscore)
  iex:1

1
```

### Expected behavior

I would expect the assignment on the right hand to work without emitting a warning.

```elixir
iex(1)> if (a = 1) && (b = 2), do: b
2
```

**Comment by dsdshcym** [comment]
After some investigation, I found it's related to how `&&` macro work:

`(a = 1) && (b = 2)` would be expanded to

```elixir
case a = 1 do
  x when :"Elixir.Kernel".in(x, [false, nil]) ->
    x

  _ ->
    b = 2
end
```

But Elixir doesn't support Imperative Assignments, therefore we have the current behavior (`b = 2` doesn't affect the variable space). Related issue:
- #8076
- #7403
- #8285

I'm not sure if we should fix this issue or how we can fix it. Any ideas?

**Comment by josevalim** [comment]
You are correct in your analysis. I don't think it is a solvable issue, which is why we have closed previous occurrences in the past. You can rewrite it as:

```
a = 1
if b = a && 2, do: b
```
