### ISSUE TITLE
releases random_cookie can generate an invalid cookie

### ISSUE THREAD

**Issue by karlseguin** [elixir-lang/elixir#9328]
On Elixir 1.9 (and 1.9.1) I think `Mix.Release.random_cookie/0` can generate an invalid cookie. Because it uses `Base.url_encode64/1`, it's possible for the first character to start with a dash (`-`). 

This results in an empty command line argument to `setcookie` (e.g., `-setcookie -84BlQcX_...`)

**Comment by kwando** [comment]
A proper base64 encoded string does not contain dashes, the only "wierd" characters are ```+``` and ```/```.

The table of characters can be found here: https://en.wikipedia.org/wiki/Base64


You can "prove" it to yourself by running the following code in iex:
```
iex(1)> :crypto.strong_rand_bytes(1_000_000) |> Base.encode64 |> String.codepoints |> Enum.uniq |> Enum.sort |> IO.puts
+/0123456789=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
```

**Comment by karlseguin** [comment]
It isn't using `Base.encode64/1`, it's using `Base.url_encode64/1`:

```
iex(1)> Base.url_encode64(<<250, 0, 0>>)
"-gAA"
```

**Comment by kwando** [comment]
Wow, my bad!
