### ISSUE TITLE
Docs: broken url: ExUnit.CLIFormatter  (404, page not found)

### ISSUE THREAD

**Issue by jivko-chobanov** [elixir-lang/elixir#9349]
Here: https://hexdocs.pm/mix/Mix.Tasks.Test.html

when I click on: ExUnit.CLIFormatter

in text: --formatter - sets the formatter module that will print the results. Defaults to ExUnit.CLIFormatter

I get 404: page not found

**Comment by josevalim** [comment]
This has been fixed in master, thank you for the report.
