### ISSUE TITLE
on_definition and Module.defines?/2

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#9351]
### Environment

* Elixir & Erlang/OTP versions: Elixir 1.10.0-dev (9213f61) (compiled with Erlang/OTP 22)

### Current behavior

Per [`@on_definition`](https://hexdocs.pm/elixir/Module.html?#module-on_definition-1) docs:

> Note the hook receives the quoted arguments and it is invoked before the function is stored in the module. So Module.defines?/2 will return false for the first clause of every function.

However that is not the behaviour I'm observing here:

```elixir
defmodule Hooks do
  def __on_definition__(env, _kind, name, args, _guards, _body) do
    IO.write "is #{inspect(env.module)}.#{name}/#{length(args)} defined? "
    IO.inspect Module.defines?(env.module, {name, length(args)})
  end
end

defmodule Bar do
  @on_definition Hooks

  def foo(x) when is_integer(x), do: :int
  def foo(x) when is_binary(x), do: :binary
end
```

```
Compiling 1 file (.ex)
is Bar.foo/1 defined? true
is Bar.foo/1 defined? true
```

**Comment by josevalim** [comment]
@wojtekmach nice find. Let's update the [assertions here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/module_test.exs#L153) and update the docs.

**Comment by wojtekmach** [comment]
@josevalim I did some more research and looks like the behaviour changed between versions:

```
~/bar% for v in 1.5 1.6 1.7 1.8; do echo Elixir $v; asdf local elixir $v; mix compile --force; echo; done
Elixir 1.5
Compiling 1 file (.ex)
is Bar.foo/1 defined? false
is Bar.foo/1 defined? true
Generated bar app

Elixir 1.6
Compiling 1 file (.ex)
is Bar.foo/1 defined? false
is Bar.foo/1 defined? true
Generated bar app

Elixir 1.7
Compiling 1 file (.ex)
is Bar.foo/1 defined? true
is Bar.foo/1 defined? true
Generated bar app

Elixir 1.8
Compiling 1 file (.ex)
is Bar.foo/1 defined? true
is Bar.foo/1 defined? true
Generated bar app
```

double-checking, should we stick with the current behaviour on master but just update the docs & tests, or look more into it?

**Comment by josevalim** [comment]
Yes, I don’t think we should change the behavior again at this point. The most important is the test so we don’t accidentally change the behavior in the future.
