### ISSUE TITLE
import_file/1 and import_file_if_available/1 can result in an infinite loop

### ISSUE THREAD

**Issue by halostatue** [elixir-lang/elixir#9363]
* Elixir & Erlang/OTP versions (elixir --version): OTP 21, Elixir 1.8.2
* Operating system: linux, Heroku (stack-16)

### Current behavior

I have a project-local `.iex.exs` file that contains:

```elixir
import_file_if_available "~/.iex.exs"
```

When running `iex -S mix` (and probably just `iex`) from the project locally, IEx just works. On Heroku, the interactive prompt never appears because `Path.expand("~/.iex.exs") == Path.join(File.cwd!, ".iex.exs")`. Because `import_file` and `import_file_if_available` are macros, it is not possible to _conditionally_ import such a file as this results in a recursively infinite macro expansion.

### Expected behavior

The IEx prompt _should_ appear. I’m not sure if, before expansion, `import_file` should see if it’s already read the named file and refuse to do so if it has, but that would fix the issue if it is possible. I am currently on vacation, so I’m a few weeks away from being able to look at this as a possible fix.

**Comment by josevalim** [comment]
Closing in favor of #9364.
