### ISSUE TITLE
module loader not getting updated cwd?

### ISSUE THREAD

**Issue by foucist** [elixir-lang/elixir#9376]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):  Elixir 1.9.1 (compiled with Erlang/OTP 22)
* Operating system:  OSX 10.13

### Current behavior

Moving the project directory while an elixir app is running causes it to begin failing to find modules.

I suspect this behavior would be elixir-specific, however I am reproducing this when running `mix phx.server` and then moving the project directory.  Hitting a new URL endpoint will typically cause a `(module Phoenix.Router is not available)` error, but other module finding errors can occur as well.

### Expected behavior

Typical behavior for *nix programs is that they are not interrupted or interfered with when the project directory is moved, particularly since they often use getcwd(3).

When I investigated the elixir code, at first glance it actually looks like elixir is setup to handle this properly.  The modules have their relative file paths saved with `elixir_utils:relative_to_cwd(File)` and the path expanding `Path.expand/1` appears to get the updated cwd anyways.  I'm very new to elixir so I'm having trouble finding the cause of this issue, perhaps there's a list that caches all the module paths?

**Comment by ericmj** [comment]
Thanks for the report. Please include the full errors with stacktraces that you are getting.

**Comment by josevalim** [comment]
Yes, please include stacktraces and steps to reproduce because as you said,
this is supposed to work just fine. :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by foucist** [comment]
I've also discovered that the full path seems to be getting stored in the compiled .beam files.  Even when I restart the elixir app in the new location, the stack trace still uses the original path?

## steps to reproduce

    git clone https://github.com/DockYard/live_view_demo testrepo
    cd testrepo
    mix deps.get
    cd assets
    npm install
    cd ..
    mix phx.server
    open http://localhost:4000
    open http://localhost:4000/clock

extra step:

    stop mix phx.server
    mv testrepo testrepo2
    run mix phx.server again 

in new terminal, while elixir app is running:

    mv testrepo2 testrepo3
    open http://localhost:4000/clock

note how the paths here are still testrepo and not even testrepo2 :
```
[error] #PID<0.491.0> running LiveViewDemoWeb.Endpoint (connection #PID<0.479.0>, stream id 3) terminated
Server: localhost:4000 (http)
Request: GET /clock
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Phoenix.Router.__call__/2 is undefined (module Phoenix.Router is not available)
        (phoenix) Phoenix.Router.__call__(%Inspect.Error{message: "got UndefinedFunctionError with message \"function Inspect.Plug.Conn.inspect/2 is undefined (module Inspect.Plug.Conn is not available)\" while inspecting %{__struct__: Plug.Conn, adapter: {Plug.Cowboy.Conn, %{bindings: %{}, body_length: 0, cert: :undefined, has_body: false, headers: %{\"accept\" => \"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\", \"accept-encoding\" => \"gzip, deflate\", \"accept-language\" => \"en-ca\", \"connection\" => \"keep-alive\", \"host\" => \"localhost:4000\", \"upgrade-insecure-requests\" => \"1\", \"user-agent\" => \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\"}, host: \"localhost\", host_info: :undefined, method: \"GET\", path: \"/clock\", path_info: :undefined, peer: {{127, 0, 0, 1}, 61244}, pid: #PID<0.479.0>, port: 4000, qs: \"\", ref: LiveViewDemoWeb.Endpoint.HTTP, scheme: \"http\", sock: {{127, 0, 0, 1}, 4000}, streamid: 3, version: :\"HTTP/1.1\"}}, assigns: %{}, before_send: [#Function<0.66442134/1 in Plug.Telemetry.call/2>, #Function<0.50969320/1 in Phoenix.LiveReloader.before_send_inject_reloader/2>], body_params: %{}, cookies: %{__struct__: Plug.Conn.Unfetched, aspect: :cookies}, halted: false, host: \"localhost\", method: \"GET\", owner: #PID<0.491.0>, params: %{}, path_info: [\"clock\"], path_params: %{}, port: 4000, private: %{LiveViewDemoWeb.Router => {[], %{}}, :phoenix_endpoint => LiveViewDemoWeb.Endpoint, :phoenix_router => LiveViewDemoWeb.Router, :plug_session_fetch => #Function<1.35161479/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: \"\", remote_ip: {127, 0, 0, 1}, req_cookies: %{__struct__: Plug.Conn.Unfetched, aspect: :cookies}, req_headers: [{\"accept\", \"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\"}, {\"accept-encoding\", \"gzip, deflate\"}, {\"accept-language\", \"en-ca\"}, {\"connection\", \"keep-alive\"}, {\"host\", \"localhost:4000\"}, {\"upgrade-insecure-requests\", \"1\"}, {\"user-agent\", \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15\"}], request_path: \"/clock\", resp_body: nil, resp_cookies: %{}, resp_headers: [{\"cache-control\", \"max-age=0, private, must-revalidate\"}, {\"x-request-id\", \"Fcn5UDl9vJDluDMAAACC\"}], scheme: :http, script_name: [], secret_key_base: \"dummy_val_for_dev_env\", state: :unset, status: nil}"}, {%{conn: nil, log: :debug, path_params: %{}, pipe_through: [:browser], plug: Phoenix.LiveView.Plug, plug_opts: LiveViewDemoWeb.ClockLive, route: "/clock"}, #Function<0.26052923/2 in LiveViewDemoWeb.Router.__match_route__/3>, #Function<1.26052923/1 in LiveViewDemoWeb.Router.__match_route__/3>, {Phoenix.LiveView.Plug, LiveViewDemoWeb.ClockLive}})
        (live_view_demo) lib/live_view_demo_web/endpoint.ex:1: LiveViewDemoWeb.Endpoint.plug_builder_call/2
        (live_view_demo) lib/plug/debugger.ex:122: LiveViewDemoWeb.Endpoint."call (overridable 3)"/2
        (live_view_demo) lib/live_view_demo_web/endpoint.ex:1: LiveViewDemoWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:40: Phoenix.Endpoint.Cowboy2Handler.init/2
        (cowboy) /Users/foucist/test/testrepo/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/foucist/test/testrepo/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
        (cowboy) /Users/foucist/test/testrepo/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by OvermindDL1** [comment]
The paths stored for stacktraces and so forth are debugging information, they should absolutely not change when the 'compiled' binaries are moved around, they should reference the location of the source code at the time the binary was compiled so you can refer back to it.  If you strip debugging information from the compiled beam files that information vanishes, including the ability to make useful stacktraces.

**Comment by foucist** [comment]
@OvermindDL1 Thanks for the clarification.  Hopefully the module loading isn't relying on the old location to load the modules though?

**Comment by josevalim** [comment]
@foucist if the module is already loaded in memory, then we won't try to read from the filesystem again. And @OvermindDL1 is correct, if you don't recompile modules, their source location for debugging will remain the same, so everything is working as expected. :)

**Comment by foucist** [comment]
@josevalim Sorry that is 2 out of 3 things mentioned in this thread.  The main issue is still there: moving the folder on an active elixir program still has a chance of causing it to break when it hasn't loaded all modules to memory - because it's not actually looking them up relative to the NEW current working directory.

**Comment by josevalim** [comment]
There is nothing we can do about this as well. How could we know the new
directory it was moved to? You have to restart your server if you move the
directory compiled files are at. I would be surprised if this actually
worked (regardless of the technology).
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by foucist** [comment]
@josevalim `Path.expand/1` knows the new directory.

```
2423 ~/foo» elixirc test.ex
/Users/foucist/foo
move this directory in another window while we wait 10 seconds
/Users/foucist/blah
```
```
2425 ~» mv foo blah
2426 ~» cd blah
2427 ~/blah» cat test.ex
IO.puts(Path.expand('./'))
IO.puts('move this directory in another window while we wait 10 seconds')
:timer.sleep(10000)
IO.puts(Path.expand('./'))
```

**Comment by OvermindDL1** [comment]
`[GAME]   29.852 Quitting: window closed.` Still makes me curious.  It's not being manually closed?  Or is that just what windows does when it receives a kill signal (where at least for me it says it received a kill signal and is dying)?
