### ISSUE TITLE
Protocols functions cannot have arbitrary names

### ISSUE THREAD

**Issue by pallix** [elixir-lang/elixir#9413]
### Environment

```
λ elixir --version
Erlang/OTP 21 [erts-10.3.5.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Elixir 1.8.2 (compiled with Erlang/OTP 21)
```

### Current behavior

I can create a function with an arbitrary name in a module but not in a protocol:

```

defmodule A do
  def unquote(:"topic1/topic2/get_message")() do # ok
    1
  end
end

defprotocol B do
  def unquote(:"topic1/topic2/get_message")(m) # fails
end
```

fails with:

```
** (ArgumentError) invalid arguments for def inside defprotocol
    (elixir) expanding macro: Protocol.def/1
```

### Expected behavior

I would expect the `unquote` to work also for protocols and have the ability of providing arbitrary name for protocols.

**Comment by josevalim** [comment]
Thanks @pallix for the report.

To be honest, I am OK with the limitation. Protocols are limited in nature, we don't need to provide the same flexibility as regular function definitions. And you can achieve what you need with macros.

Do you have a very good argument to do the above?

**Comment by pallix** [comment]
I don't know if I have a very good argument but let me explain why I considered these solution.

I am writing an interface for a MQTT API. It has different topics which are hierarchically ordered. I don't want to represent all these topics in different Elixir modules but provide them all, in one unified interface.

Allowing a slash in the name of the functions would allow the hierarchy to be clear, for example a function named `:topic1_topic2_error_message` is ambiguous and could refers either to `topic1/topic2/error/message` or `topic1/topic2/error_message` whereas the name `:"topic1/topic2/error_message"` is not.

I can achieve arbitrary names on protocols with macros?

**Comment by josevalim** [comment]
Assuming you have to use protocols, then this patch would be necessary. But I am not convinced you need protocols?

Why do you need to dispatch each topic per data type? Wouldn't a regular behaviour surface? Or couldn't you have a static function (named `handle` or whatever) that receives the topics as a list and as first argument?

**Comment by pallix** [comment]
I am assigning each topic to a function. My intend is to provide an API so that different simulated MQTT writers can be implemented. Having a clear interface of which topic need to be implemented makes the implementation easier.

I have also considered behaviours. I think it could work also. Each of the simulation will have an internal state so binding the internal state to an API and allowing the user to swap one simulation for another (dynamic dispatch) lead me to think protocols could be a better fit.

Thanks for taking time to discuss this.

**Comment by josevalim** [comment]
Yes, given the discussion above, I believe behaviours are a better fit. For example, GenServers are still bound to a state, and it could be implemented by a protocol, but in this case using the protocol would actually be limiting because you would impose a shape on the state (basically, it would have to be a struct).

NP!

**Comment by pallix** [comment]
Unquote works for behaviours, that's great. You are right, behaviours may be a better fit for my case.
I am also ok with the small limitation of protocols then. You can close this issue and if somebody feels like bringing new - stronger - arguments, he can reopen it.
