### ISSUE TITLE
Bad ExUnit diff for dates

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#9429]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.10.0-dev (db7d715) (compiled with Erlang/OTP 22)`

### Current behavior

Not sure if it can be considered a bug but I got this:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/76071/67126837-56165b80-f1f8-11e9-9afa-b623a498877c.png">

whereas I'd expect a shorter diff that uses sigil representation in all cases.

**Comment by devonestes** [comment]
I would consider that a bug. Representing the same struct in two different ways in a single diff could be quite confusing to folks.

I wonder if this is also the case for DateTime, Time and NaiveDateTime?
