### ISSUE TITLE
Remote shell causes 100% CPU usage if crashed waiting on STDIN

### ISSUE THREAD

**Issue by karlseguin** [elixir-lang/elixir#9445]
Using OTP 22 and Elixir 1.9.1

SSH'ing into a dev machine, I:

1 - I start a remote shell: `bin/myapp remote`
2 - Ask for user input: `IO.gets("spice?: ")`
3 - Abruptly terminate the connection (close tab)

The iex process remains alive and will, after a few seconds, use 100% CPU until terminated.

I figured this out because the strace of scheduler_1, which was the thread taking 100% of the CPU, was continuously doing:

```
futex(0x561b5a706a80, FUTEX_WAKE_PRIVATE, 1) = 1
read(0, "", 1024)                       = 0
write(10, "!", 1)                       = 1
epoll_ctl(8, EPOLL_CTL_MOD, 0, {EPOLLIN, {u32=0, u64=140625819205632}}) = 0
```

 I think I was using `observer_cli` which is where the read from stdin probably came from. I _thought_ I exited normally, but I guess not?

**Comment by josevalim** [comment]
I cannot reproduce this locally, so I will need more information. Here is what I did:

    $ mix new foo
    $ cd foo
    $ mix release
    $ _build/dev/rel/foo/bin/foo start

Then I ssh-ed from another machine and ran: `_build/dev/rel/foo/bin/foo remote`. I typed `IO.gets("spice?: ")`, pressed enter. Wait 5 seconds, closed the SSH tab.

Back in the host, I could see the machine was correctly terminated. Do the steps above reproduce the issue for you?

Also, can you please include both `elixir --version` and your OS, as asked in the issue template? Thank you.

**Comment by karlseguin** [comment]
Figured out the missing step. Not an Elixir problem, but worth fully documenting.  First though, to answer your questions:

```
$ elixir --version
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]

Elixir 1.9.1 (compiled with Erlang/OTP 22

$ cat /proc/version
Linux version 4.15.0-50-generic (buildd@lcy01-amd64-013) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019
```
Ubuntu 18.04

The missing step was that `remote` is being execute via `sudo su -c "/path/to/bin/app remote"` which I now realize is an improper usage of the -c flag (we have generic wrappers)

If you still want to look at it and can't reproduce, you can ssh into `root@172.105.73.253`. I added your github key (I'll kill the  machine in a few days). In one session,  you can: `/opt/testapp/_build/prod/rel/testapp/bin/testapp start`  and in the other start the remote shell via `su -c "/opt/testapp/_build/prod/rel/testapp/bin/testapp remote"`  Now doing IO.gets("...") and closing will cause the issue.

**Comment by josevalim** [comment]
Thank you for the extra info.

> The missing step was that remote is being execute via sudo su -c "/path/to/bin/app remote" which I now realize is an improper usage of the -c flag (we have generic wrappers)

So is the error being caused because the shell itself (beam's parent) is not terminating?

**Comment by josevalim** [comment]
macOS does not support the `-c` flag for `su`. :(

Can you please try one more thing? Try running this:

    $ su -c 'erl'

And then in erl:

    1> io:get_line("freeze? ").

And then kill the window as you did before. Does that reproduce the issue? If so, maybe we should report this on Erlang/OTP? Or do you still think there is not an issue here?
freeze?

**Comment by karlseguin** [comment]
Yes. The above steps also cause it to happen.

I don't think there's an issue. I think it's an improper usage on my part. Maybe it would be nice if there was some protection against it, but not for me to say. Hopefully just having the issue here, indexed, will help anyone else who runs into it.
