### ISSUE TITLE
(UndefinedFunctionError) when using function :crypto.hash/2 in MIX release

### ISSUE THREAD

**Issue by otboss** [elixir-lang/elixir#9450]
### Environment

Elixir 1.9.1 (compiled with Erlang/OTP 21)
Ubuntu 18.04 LTS
AMD A10-9600P RADEON R5, 10 COMPUTE CORES 4C+6G × 4

### Current behavior

Executing the command `":crypto.hash(:md5, 'test')"` within a mix release using eval results in the following error:
```
** (UndefinedFunctionError) function :crypto.hash/2 is undefined (module :crypto is not available)
    :crypto.hash(:md5, 'ottor-HP-Notebook')
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:240: Code.eval_string/3
```

### Expected behavior

The md5 representation of the supplied bitstring

**Comment by wojtekmach** [comment]
Are you setting that your application depends on :crypto? You need to add it to :extra_applications in your project or :applications in your release config in mix.exs.

**Comment by otboss** [comment]
This problem has been resolved. This error was encountered within the Mongo Package. After adding :crypto to the :extra_applications, the current error is:
```
** (EXIT from #PID<0.92.0>) an exception was raised:
    ** (ArgumentError) argument error
        :erlang.!(Mongo.Events, {:notify, %Mongo.Events.TopologyOpeningEvent{topology_pid: #PID<0.93.0>}})
        (stdlib) gen_event.erl:269: :gen_event.send/2
        lib/mongo/topology.ex:70: Mongo.Topology.init/1
        (stdlib) gen_server.erl:374: :gen_server.init_it/2
        (stdlib) gen_server.erl:342: :gen_server.init_it/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I will migrate this issue to the forum instead: https://github.com/ankhers/mongodb/issues/
Thank you for the assistance!
