### ISSUE TITLE
Provide better warning message in the presence of conflicting function clauses

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9453]
### Environment

```
$ elixir --version
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

### Current behavior

The follwoing code

```
# Example 1
defmodule M do
  def foo, do: :foo_a    # LINE 3
  def foo, do: :foo_b    # LINE 4
end
```
generates this message
```
warning: this clause cannot match because a previous clause at line 3 always matches
  lib/w.ex:4
```
which is enough to identify the affected function.

Now, in the next example, 

```
# Example 2
defmodule A do
  defmacro macro_from_a do
    quote do
      def foo, do: :foo_a
    end
  end
end

defmodule B do
  defmacro __using__(_) do
    quote do
      def foo, do: :foo_b
    end
  end
end

defmodule C do
  import A
  use B             # LINE 20
  macro_from_a()    # LINE 21
end
```
the generated warning is
```
warning: this clause cannot match because a previous clause at line 20 always matches
  lib/w.ex:21
```
does not help to immediately identify the affected function because there are no function clauses at the reported lines. A more experienced developer will understand that these two lines are injecting the conflicting code, but identifying the affected function will definitely take as much effort as length and complexity of the code to inspect.

Another more intricate example is the following
```
# Example 3
defmodule X do
  defmacro __using__(_) do
    quote do
      @before_compile unquote(__MODULE__)
    end
  end
  defmacro __before_compile__(_env) do
    quote do
      def bar, do: "bar"
    end
  end
end

defmodule Y do
  defmacro __using__(_) do
    quote do
      use X
      def bar, do: "BAR"
    end
  end
end

defmodule Z do  # LINE 24
  use Y         # LINE 25
end
```
which generates the same warning
```
warning: this clause cannot match because a previous clause at line 25 always matches
  lib/w.ex:24
```
but this time on two totally unexpected lines, which may confound both novice and experienced developers.

### Expected behavior

If correct source code locations cannot be reported in the warning, at least report the name and arity of the affected function, by reporting like this

```
warning: this clause `fun(arg1, ..., argN)` cannot match because a previous clause at line 25 always matches
  lib/w.ex:24
```

or like this

```
warning: this clause for function `fun/N` cannot match because a previous clause at line 25 always matches
  lib/w.ex:24
```

This will provide much useful information to resolve the warning even in complex cases, like those involving macros that inject code in complex ways.

**Comment by josevalim** [comment]
This would need to be changed on Erlang but I think it is a good change. Thanks for suggesting it.

**Comment by mguimas** [comment]
Should I do something now, and what, or will the Elixir team take care of this and integrate with the Erlang team?

**Comment by josevalim** [comment]
I will send a PR to the Erlang project.

**Comment by mguimas** [comment]
Right, that is the best approach, since this issue affects more code involving macros, which Erlang does not have, it will be better if reported by you. Thanks José.

**Comment by josevalim** [comment]
https://github.com/erlang/otp/pull/2435
