### ISSUE TITLE
can not print number inside `spawn` in .exs file without a module

### ISSUE THREAD

**Issue by terriblecodebutwork** [elixir-lang/elixir#9459]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 20)

* Operating system: macOS mojave

### Current behavior

write code in file `a.exs`, run with `elixir a.exs`.

code:
```ex
spawn(fn -> IO.puts(1) end)
```

result: nothing

### Expected behavior

Print the number.

**Comment by nubunto** [comment]
The main issue with your code is that `spawn` spawns a new process that starts asynchronously. The program ends after that, giving no time for the scheduler to actually run your new process.

If you give it enough time, it will print:

```
spawn(fn -> IO.puts(1) end)
:timer.sleep(10)
```

This prints "1" to the console.

**Comment by terriblecodebutwork** [comment]
@nubunto Thank you!
