### ISSUE TITLE
Cryptic error message when using reserved keyword in pattern match

### ISSUE THREAD

**Issue by JackShannon** [elixir-lang/elixir#9467]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.1 (compiled with Erlang/OTP 21)
* Operating system: Ubuntu 18.04

### Current behavior

```
iex(1)> %{after: a} = %{after: 5}
%{after: 5}
iex(2)> %{after: after} = %{after: 5}
** (SyntaxError) iex:2: syntax error before: 'after'
```

### Expected behavior

An error message saying that 'after' is a reserved keyword.

**Comment by josevalim** [comment]
Good call. We can explicitly check for keywords in syntax error before and add a special note. Thanks for the report!
