### ISSUE TITLE
Guards and matches do not have the concept of thruthy/falsey

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#9495]
This took me by surprise today, as I would have expected anything other than `false` or `nil` evaluated in guards to make the guard pass, but it does not work like that.

```elixir
defmodule A do
  def check(term) when tuple_size(term), do: true
  def check(_), do: false
end
```
the  function `check/2` will never return `true`, regardless `term` is a tuple or not.

I have read the section dedicated to Guards and defguard, defguardp, and nothing is mentioned.

**Comment by eksperimental** [comment]
Erlangbyexample mentions this in a very concise way:

> The whole guard is true if all guard expressions will evaluate to true.

**Comment by eksperimental** [comment]
For the record, this information should be briefly explained in http://elixir-lang.org

**Comment by ericmj** [comment]
The guides on the website links to the more in-detail documentation on hexdocs.pm so I think it is fine.

**Comment by eksperimental** [comment]
> The guides on the website links to the more in-detail documentation on hexdocs.pm so I think it is fine.

@ericmj true. There's not a section dedicated to guads in the guide.
