### ISSUE TITLE
Process ID is returning as undefined

### ISSUE THREAD

**Issue by DmitryKK** [elixir-lang/elixir#9504]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.8.1/21.2.3
* Operating system: macOS Mojave 10.14.6

### Current behavior

My code is

```elixir
defmodule MyApp.StatisticSupervisor do
  use DynamicSupervisor

  def start_link(_) do
    DynamicSupervisor.start_link(__MODULE__, [], name: {:global, __MODULE__})
  end

  def start_statistic(team_id) do
    DynamicSupervisor.start_child(global_name(), {MyApp.Statistic.Server, [team_id]})
  end

  def init(_) do
    DynamicSupervisor.init(strategy: :one_for_one)
  end
end

defmodule MyApp.Statistic.Server do
  def child_spec(team_id) do
    %{
      id: team_id,
      start: {__MODULE__, :start_link, [team_id]},
      restart: :transient
    }
  end

 def start_link(team_id) do
    GenServer.start_link(__MODULE__, %{team: team_id}, name: via_tuple(team_id))
  end

  def init(state) do
    {:ok, state}
  end

 defp via_tuple(team_id) do
    {:via, :syn, {:team, team_id}}
  end
end
```
I was executing:

```elixir
MyApp.StatisticSupervisor.start_statistic(1)
```

Got `{:ok, #PID<0.973.0>}`

And then:

```elixir
DynamicSupervisor.which_children({:global, MyApp.StatisticSupervisor})
```

And got:

```elixir
[
  {:undefined, #PID<0.973.0>, :worker, [MyApp.Statistic.Server]}
]
```

### Expected behavior

I expected to got:

```elixir
[
  {1, #PID<0.973.0>, :worker, [MyApp.Statistic.Server]}
]
```

It doesn't matter number, atom or module. Identifier always returns undefined.

Is it Elixir's bug?

**Comment by josevalim** [comment]
No, this is by design and also how Erlang's simple_one_for_one supervisor (which is the equivalent to DynamicSupervisor) works: the `id` is ignored and it is not used.

**Comment by josevalim** [comment]
In any case, thanks for the report! :heart:

**Comment by DmitryKK** [comment]
@josevalim The documentation says nothing about the ID being ignored in the case of a DynamicSupervisor http://erlang.org/doc/design_principles/sup_princ.html#child-specification

Why do you think this is correct behavior? Could you get me link to the doc?

**Comment by josevalim** [comment]
DynamicSupervisor.which_children says:

>    * `id` - it is always `:undefined` for dynamic supervisors

Similar can be found here:

http://erlang.org/doc/man/supervisor.html#which_children-1

That's because a dynamically supervised children all come from the same child spec, so they would all end-up with the same id, which would be a conflict.

**Comment by DmitryKK** [comment]
Thank you very much
