### ISSUE TITLE
StringIO ignores raw mode and forces UTF8 

### ISSUE THREAD

**Issue by sunaku** [elixir-lang/elixir#9505]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.9.2 (compiled with Erlang/OTP 22)
```
* Operating system: 
```
Linux hostname 4.1.15.pnotify #18 SMP Thu May 18 15:50:05 PDT 2017 x86_64 GNU/Linux
```

### Current behavior

StringIO is ignoring `:raw` mode and forcing UTF8 encoding:

```elixir
iex(315)> {:ok, f} = StringIO.open("", [:raw])
{:ok, #PID<0.19126.0>}
iex(2)> IO.binwrite(f, <<131>>)
:ok
iex(3)> StringIO.contents(f)
{"", <<194, 131>>}
```

Here, the written byte 131 is padded with another byte 194. 

### Expected behavior

StringIO should honor `:raw` mode just like normal files do:

```elixir
iex(1)> f = File.open!("", [:ram, :write, :read])
{:file_descriptor, :ram_file, #Port<0.16>}
iex(2)> IO.binwrite(f, <<131>>)
:ok
iex(3)> :file.position(f, :bof)
{:ok, 0}
iex(4)> IO.binread(f, :all)
<<131>>
```

Here, 131 is written verbatim without any UTF8 conversion.

**Comment by josevalim** [comment]
The `:raw` option is not generally accepted across all IO devices. For example, it is not supported by stderr/stdin, and those are the canonical IO devices. However, notice that you can pass `encoding: :latin1` for StringIO in master, which is often considered as an equivalent to keeping the bytes as is:

```elixir
iex(1)> {:ok, f} = StringIO.open("", [encoding: :latin1])
{:ok, #PID<0.110.0>}
iex(2)> IO.binwrite(f, <<131>>)
:ok
iex(3)>  StringIO.contents(f)
{"", <<131>>}
```
