### ISSUE TITLE
Enum.chunk/3 is broken

### ISSUE THREAD

**Issue by alco** [elixir-lang/elixir#9506]
I know this function is deprecated, but it still may be used in the wild. I've found one such case and wanted to find the documentation of its behaviour before deciding on the best replacement. That alone was not easy: I had to randomly pick past Elixir versions on hexdocs.pm before switching to v1.0.4 where I found the docs.

But the real issue is that the function no longer works as documented. When invoked with 3 arguments, it raises `Protocol.UndefinedError`:

```
iex(3)> Enum.chunk([1,2,3,4,5,6,7,8,9], 2, 1)
warning: Enum.chunk/3 is deprecated. Use Enum.chunk_every/3 instead
  iex:3

** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:141: Enumerable.reduce/3
    (elixir) lib/enum.ex:2507: Enum.take/2
    (elixir) lib/stream/reducers.ex:31: anonymous fn/3 in Stream.Reducers.chunk_every/5
    (elixir) lib/enum.ex:518: Enum.chunk_while/4
```

I figured that it must be implemented in terms of `chunk_every` now, so I tried the following

```
iex(3)> Enum.chunk([1,2,3,4,5,6,7,8,9], 2, 1, [])
warning: Enum.chunk/4 is deprecated. Use Enum.chunk_every/4 instead
  iex:3

[[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], '\a\b', '\b\t', '\t']

iex(4)> Enum.chunk([1,2,3,4,5,6,7,8,9], 2, 1, :discard)
warning: Enum.chunk/4 is deprecated. Use Enum.chunk_every/4 instead
  iex:4

[[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], '\a\b', '\b\t']
```

Those calls work but the behaviour does not match the docs anymore.

This is bad on two levels:

  1. Someone somewhere might find a call to `Enum.chunk/3` in a code base they inherited and that person may not be familiar with the deprecation history of the function. It's not easy to find the docs to understand what the existing code is doing.

  2. Because the deprecated function's behaviour is different in the latest Elixir version from what it used to be, it makes the problem of understanding the existing code even harder, plus it may also break existing code when upgrading from one Elixir version to a newer one.

**Comment by Eiji7** [comment]
It's really easy to find and fix:
https://github.com/elixir-lang/elixir/blob/1b6321e9238bc1b7ffd8c2e43d7d5dffb529eb24/lib/elixir/lib/enum.ex#L408-L418

The problem is that `leftover` in `Enum.chunk/3` is always `nil`. However if `leftover` in `Enum.chunk/4` is `nil` then it's set to `:discard`.

`:discard` value is handled separately and any other value is passed as `enumerable` to `Enum.take/2`
https://github.com/elixir-lang/elixir/blob/1b6321e9238bc1b7ffd8c2e43d7d5dffb529eb24/lib/elixir/lib/stream/reducers.ex#L28-L32

so our problem is `nil` value at: `elixir/lib/elixir/lib/enum.ex:411`.

**Comment by whatyouhide** [comment]
Do we know which version of Elixir this was broken in? Because we'd have to backport this on all subsequent versions if we wanted to be tidy :)

**Comment by Eiji7** [comment]
@whatyouhide It's broken at least from `v1.7.0-rc.0` as `v1.6.6` code looks good for me, but not tested manually.

**Comment by riosgabriel** [comment]
Is there any reason why this fix is not backported?

**Comment by Eiji7** [comment]
Information about latest releases of previous minor versions from [Bob](https://bobs-list.kobrakai.de):

> 1.7.4 eb5679bf
v1.7.4
2019-05-15 00:59:18 UTC

> 1.8.2 98485daa
v1.8.2
2019-05-15 02:31:56 UTC

> 1.9.4 05552605
v1.9.4
2019-11-05 16:22:08 UTC

Also following 52f01c2 commit information it looks like that it work only in v1.10.0-rc.0 + of course for any manual build contains this commit. I have just tested and verified that.

The funniest thing is that it would work only in release which as first displays warnings that such call is deprecated. :smiley:

ping @whatyouhide and @josevalim

**Comment by ericmj** [comment]
If we do another patch release of the v1.9 branch we will include this fix in the release.
