### ISSUE TITLE
Revamp capture_io with named process

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9508]
Currently, `capture_io` does not allow concurrent captures on `:stderr` and other named devices. The goal is to allow `capture_io` on named devices to run concurrently, similar to `capture_log`, AS LONG AS no input for the capture was given (as we can't read from the capture concurrently).

Note that, if multiple captures are on the same named device, then the returned capture will include output for all captures happening at the same time. However, it is guaranteed that a single message won't be garbled. For example:

    IO.puts :stderr, "hello\nworld\n"

will always appear together in the capture output. While:

    IO.puts :stderr, "hello\n"
    IO.puts :stderr, "world\n"

May be garbled with messages from other processes. However, to reduce leaking content from between devices, every time a capture starts and the device is already being captured, we should capture the current output `byte_size` and return only the StringIO.contents from the given offset.

The mock device should be closed only when all captures are disabled. This means we will need to move the StringIO device management to the CaptureServer.

Once this work is done, there are three further improvements we can do:

  * [x] We can enable async: true on all tests that rely on capture_io(:stderr) today
  * [x] Strip kernel/warnings_test a bit (it should only hold warnings from Kernel or the compiler)
  * [ ] Add `@tag :capture_io`, `@tag capture_io: true`, `@tag capture_io: :stderr` (true means `:stdio`)

**Comment by josevalim** [comment]
I have reopened because we still have to other checkboxes to tackle (and I am working on the second one).

**Comment by fertapric** [comment]
@devonestes are you going to tackle the third one?

**Comment by josevalim** [comment]
So I started working on the third part and I gave up for some reasons:

* opposite to log, we can capture different devices
* capture_log has a whole infrastructure for showing captured results which I don’t think we necessarily want to replicate here
* my initial use case for this feature won’t work (to capture deprecation warnings since they are compile time)
* I don’t think capturing io devices is that common anyway, especially in this case where we want to discard the results

So I will close this. Good news is that I at least refactored the tests, so I will push that soon!
