### ISSUE TITLE
Customize tar test failing when building v1.9.4 from source

### ISSUE THREAD

**Issue by 0rzech** [elixir-lang/elixir#9514]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.2 (compiled with Erlang/OTP 20)
* Operating system: Ubuntu 18.04.3

### Current behavior

```elixir
  1) test customize tar (Mix.Tasks.ReleaseTest)
     test/mix/tasks/release_test.exs:39
     ** (MatchError) no match of right hand side value: {:error, {'/home/user/some/dir/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test customize tar/_build/dev/rel/demo/erts-9.2/doc', :enoent}}
     stacktrace:
       (mix) lib/mix/tasks/release.ex:1039: Mix.Tasks.Release.make_tar/1
       (mix) lib/mix/tasks/release.ex:959: Mix.Tasks.Release.run_steps/1
       (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
       test/mix/tasks/release_test.exs:54: anonymous fn/1 in Mix.Tasks.ReleaseTest."test customize tar"/1
       (mix) lib/mix/project.ex:352: Mix.Project.in_project/4
       (elixir) lib/file.ex:1542: File.cd!/2
       test/test_helper.exs:120: MixTest.Case.in_fixture/3
       test/mix/tasks/release_test.exs:40: (test)
```

It looks like `/home/user/some/dir/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test customize tar/_build/dev/rel/demo/erts-9.2/doc` is a symlink pointing to non-existing `../../../share/doc/erlang-doc/erts-9.2/doc` and hence the error. Same for `info` symlink in the same directory.

My system has `/usr/share/doc/erlang-doc/erts-9.2/doc` and `/usr/share/doc/erlang-doc/erts-9.2/info` both coming from Ubuntu's `erlang-doc` package.

Removing `:dereference` option from `:erl_tar.create/3` call like so:
```diff
diff --git a/lib/mix/lib/mix/tasks/release.ex b/lib/mix/lib/mix/tasks/release.ex
index 9aa1b240d..96e40cab8 100644
--- a/lib/mix/lib/mix/tasks/release.ex
+++ b/lib/mix/lib/mix/tasks/release.ex
@@ -1036,7 +1036,7 @@ defmodule Mix.Tasks.Release do
       Enum.map(dirs, &{String.to_charlist(&1), String.to_charlist(Path.join(release.path, &1))})
 
     File.rm(out_path)
-    :ok = :erl_tar.create(String.to_charlist(out_path), files, [:dereference, :compressed])
+    :ok = :erl_tar.create(String.to_charlist(out_path), files, [:compressed])
     release
   end
 
```
allows to ignore problematic files, but I guess it's desirable to have it enabled.

### Expected behavior

Test does not fail.

**Comment by josevalim** [comment]
Thanks @0rzech!

I think we should rather copy only parts of `erts` and not everything. @tsloughter, when you copy ERTS, are there some directories that you keep/exclude?

**Comment by tsloughter** [comment]
@josevalim nope, whole thing. Been meaning to for years to look at what can be removed and no one notice. But because the size (at least now with the smp vm being the only one) of everything compared to the VM is negligible so it hasn't been a priority to figure out.

**Comment by josevalim** [comment]
Thanks! We will give it a try then at keeping the `doc` out and we can exchange experiences later!

**Comment by tsloughter** [comment]
Oh, removing `doc` is good idea. I've never had it have anything in it for an erts being used to build a release, at least a production release, so never noticed. May as well get rid of `man` too.

I'll make a note to drop these in relx. Wonder why the above problem has never hit relx...

**Comment by 0rzech** [comment]
@josevalim You're welcome and thank you for Elixir!

**Comment by tsloughter** [comment]
Hah, just discovered it was a bug that we had the whole thing in the tarball. Was using the wrong path to `erts` (using the path to the install of `erts` instead of to the contents of the tarball created by `systools`) when updating the tarball `systools` makes with the `relx` overlays.

See `systools_make` for all you have to include (and all we will include now that I've fixed this bug) https://github.com/erlang/otp/blob/master/lib/sasl/src/systools_make.erl#L1959-L1962

So you should be able to safely go further than just removing those dirs and instead only include `bin`.
