### ISSUE TITLE
Support application-wide Logger metadata

### ISSUE THREAD

**Issue by fertapric** [elixir-lang/elixir#9521]
That would allow to log things like the commit ID with every message.

**Comment by josevalim** [comment]
@hauleth does logger support anything like this? I was thinking this could be stored in the handler config, so we don’t have to read it on every log command, but this would make it specific to Elixir backends. Thoughts?

**Comment by hauleth** [comment]
`logger` do not support anything like that. Such data could be added in global filters, formatter, or handler itself. There is no configuration option that would provide such functionality OotB.

**Comment by hauleth** [comment]
Just to update, I think it would be better to push such proposal upstream instead of handling it on our own as currently neither of the implementations support such functionality. I think it could be nice addition to overall `logging` facility.

**Comment by josevalim** [comment]
So let’s propose it upstream then. In case they do not accept it, we could merge it with our current process filter, so we have all extensions on a single place.

**Comment by hauleth** [comment]
Created [ERL-1094](https://bugs.erlang.org/browse/ERL-1094).

**Comment by fertapric** [comment]
Thanks @hauleth!

Closing this in favor of [ERL-1094](https://bugs.erlang.org/browse/ERL-1094). 

We can follow up there and reopen here if the proposal is not accepted.
