### ISSUE TITLE
struct() type is listed as both a basic and built-in type

### ISSUE THREAD

**Issue by MainShayne233** [elixir-lang/elixir#9522]
Looking at: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Typespecs.md

I'm not sure if it's exactly an issue, but it seems strange that `struct()` is listed in both the list of [**Basic Types**](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Typespecs.md#basic-types) and [**Built-in Types**](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/Typespecs.md#built-in-types).

**Comment by ericmj** [comment]
Good find. It should only be listed in built-in types.

**Comment by eksperimental** [comment]
5 year-old documentation "bug".
Great catch! Thank you @MainShayne233
