### ISSUE TITLE
Erlang logger configuration isn't loaded on startup

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#9545]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
  ```
  Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

  Elixir 1.10.0-dev (3578be2) (compiled with Erlang/OTP 22)
  ```
  But for sure this happens on all current `master`
* Operating system: Doesn't matter

### Current behavior

Configuring Erlang's `logger` via:

```elixir
config :kernel, :logger, [
  {:handler, :example, :logger_std_h, %{config: %{file: 'foo.bar'}}}
]
```

Doesn't add handler with ID `:example` as `kernel` configuration is set in stone when the application is ran via Mix. This can be confusing for users that want to use Erlang logger backends with Elixir as this will be non obvious how to manage them.

### Expected behavior

With configuration given as above this assertion should pass

```elixir
assert :example in :logger.get_handler_ids()
```

**Comment by josevalim** [comment]
There is nothing we can do. Kernel is already started when we load the
configurations. If all of logger configuration is boot time, then we can
warn, but otherwise this won’t be fixed.

-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D

**Comment by josevalim** [comment]
Another idea is to add an API to Erlang’s logger so it reloads its
configuration by restarting.
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D

**Comment by hauleth** [comment]
@josevalim yet another idea is to traverse `kernel.logger` options in Mix and add all required entries before starting application

**Comment by hauleth** [comment]
I have found even better way to handle that. [`logger:add_handlers/1`](http://www.erlang.org/doc/man/logger.html#add_handlers-1) and in case when we generate application then we should also include `:logger.add_handlers(:my_app)` so user can then do:

```elixir
config :my_app, :logger, […]
```

I think it would be the cleanest solution.

**Comment by josevalim** [comment]
> I have found even better way to handle that. logger:add_handlers/1 and in case when we generate application then we should also include :logger.add_handlers(:my_app) so user can then do:

Yes, let's go this route. Maybe we can have a session on `Logger` moduledocs that discusses integation with Erlang and how to do things like adding handlers, using the APIs above.

**Comment by hauleth** [comment]
@josevalim I think that there are few things to be done:

- Add function in core that would load configuration with all features (filters and module levels)
- Encourage people to use current application to configure logger handlers via `:logger.add_handlers` or the newly created function

However I think that Mix still should use `:logger.add_handlers(:kernel)` even if that do not apply all configuration options as this will reconfigure Logger Proxy. We need to think how to handle other configuration options though.

**Comment by josevalim** [comment]
I see two problems with doing things in Mix:

* it would be incompatible with other kernel configurations which are not loaded

* we would have to reimplement how logger behaves, in ways that may be potentially incompatible and those differences would only be spotted in a release (as one used the kernel configuration and the other uses our Mix shim)

Both of them are deal breakers to me, so we are probably not going down this path.

I would even be ok with adding options to our :logger that work as a proxy and that would apply them to Erlang’s logger. A bit of indirection but at least it means we will bootstrap the logger application consistently.
