### ISSUE TITLE
Release with :tar without :include_erts fails

### ISSUE THREAD

**Issue by lasseebert** [elixir-lang/elixir#9567]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.4 (compiled with Erlang/OTP 21)
* Operating system: Ubuntu 19.04

### Current behavior

* I have a release with `include_erts: false`, since I'm building it for an embedded device where erlang should be cross-compiled to ARM,
* My steps in the release are `[:assemble, :tar]`

When I run `mix release`, it tries to add erts to the tar, but fails: 

```
* assembling my_app-0.4.4 on MIX_ENV=dev
* skipping runtime configuration (config/releases.exs not found)
* creating _build/dev/rel/my_app/releases/0.4.4/vm.args
* creating _build/dev/rel/my_app/releases/0.4.4/env.sh
* building /path/to/my_app/_build/dev/my_app-0.4.4.tar.gz
** (MatchError) no match of right hand side value: {:error, {'/path/to/my_app/_build/dev/rel/my_app/erts-10.1', :enoent}}
    (mix) lib/mix/tasks/release.ex:1039: Mix.Tasks.Release.make_tar/1
    (mix) lib/mix/tasks/release.ex:959: Mix.Tasks.Release.run_steps/1
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```

### Expected behavior

I was hoping it would not include erts in the tar.

These lines of code seems to be the critical place: https://github.com/elixir-lang/elixir/blob/cf4272d22c2b4594c40a4c5dc971de888efd37b6/lib/mix/lib/mix/tasks/release.ex#L1044-L1046

Am I right in my assumption about the expected behaviour?

**Comment by Gazler** [comment]
I think we should exclude `"erts-#{release.erts_version}"` if `include_erts` is set to false.

**Comment by lasseebert** [comment]
:+1: I will make a PR as suggestion to expected behaviour.

**Comment by lasseebert** [comment]
PR submitted --^
The `make_tar` function also tries to add erlang libs that does not exist when releasing with `include_erts: false`, so I have excluded those in `make_tar`, but perhaps they should be excluded earlier in the release process?

**Comment by josevalim** [comment]
Those applications are part of the release, they just are not copied over. I left a comment on the PR talking about how to handle them.

**Comment by josevalim** [comment]
Closing in favor of the PR!
