### ISSUE TITLE
Compiler warning - unused variable

### ISSUE THREAD

**Issue by pdgonzalez872** [elixir-lang/elixir#9572]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
```
* Operating system: macOS - Mojave

### Current behavior
In tests, it is nice to combine pattern matching with assertions. [Here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/test/elixir/agent_test.exs#L13) is an example of the technique.

I was writing some tests and saw an interesting warning when doing something like the below. I thought I'd at least share it as an issue to document it:
```
# in a test
params = %{id: "an_id"}
assert params = %{id: "an_id"}

# warning
warning: variable "params" is unused (if the variable is not meant to be used, prefix it with an underscore)
  test/warning_test.exs:20: WarningTest."test greets the world"/1
```

The pin operator works to stop the warning, so that's a great solution and what we went with. But my question is: Should the compiler warn in this case? Should it use the message that it used?

Sample repo: [here](https://github.com/pdgonzalez872/warning_example/blob/master/test/warning_test.exs#L5). Run `mix test` and you should see the warning.

### Expected behavior
I'm not sure there is an expected behavior other than what already exists. It may just have been a personal "aha" moment. I feel that sometimes we forget about these moments and they go undocumented. Surfacing these may help with mitigating knowledge bias. So, I did! :)

Maybe a different warning message to nudge me towards a solution: "The pin operator may help you here".

PS: Thanks for working on Elixir ❤️. I love your work 🙂

**Comment by josevalim** [comment]
It is tricky to do suggestions on warnings because there are more possible scenarios. For example, in the test above, I would rather have written `assert params == %{id: 1}`. We had similar cases in other warnings, when adding more suggestions made the warnings more misleading.

So I believe we should keep this is as is for now. In any case, thanks for opening the issue and the feedback, it is appreciated!

**Comment by pdgonzalez872** [comment]
Very interesting, I can see how it would eventually be misleading. Agree with the solution, thanks  @josevalim !
