### ISSUE TITLE
Randomly "make check_reproducible" fails

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#9579]
```
Diffing...
Binary files lib/elixir/ebin/Elixir.System.beam and lib/elixir/tmp/ebin_reproducible/Elixir.System.beam differ
Makefile:130: recipe for target 'check_reproducible' failed
```

And I have seen the same error in Cirrus CI, for `Elixir.UndefinedFunctionError.beam`.
It doesn't happen very often, but it is not that uncommon either.

I investigated for a bit, to no avail.

**Comment by fertapric** [comment]
@eksperimental That happened before and I had a poor man's script to perform a diff between `.beam` files (chunk diff). I'm improving that script, I'll submit a PR, and it'll run in every build.

**Comment by eksperimental** [comment]
Awesome. I did an hex diff it meant nothing to me, as the differences were big enough.

**Comment by eksperimental** [comment]
@fertapric it may help https://github.com/elixir-lang/elixir/issues/8689#issuecomment-457239695
https://github.com/bmwiedemann/reproducibleopensuse/blob/master/filterdiff

**Comment by fertapric** [comment]
@eksperimental thanks for the comment!

I started with that one but the hex-diff was hard to read, that's why I implemented the chunk-diff.

**Comment by eksperimental** [comment]
Awesome. Looking forward to it!

**Comment by eksperimental** [comment]
Update: Under FreeBSD it found a diff in `Elixir.Task.beam`
https://cirrus-ci.com/task/5773269864546304

> Binary files lib/elixir/ebin/Elixir.Task.beam and lib/elixir/tmp/ebin_reproducible/Elixir.Task.beam differ

**Comment by josevalim** [comment]
We are now equipped to debug this. So if it happens again, we will have more precise feedback.
