### ISSUE TITLE
Update URL in project website field

### ISSUE THREAD

**Issue by eksperimental** [elixir-lang/elixir#9584]
This is in Github, so I cannot send a PR.
we need to update the URL of the Elixir project website, to use https

> Elixir is a dynamic, functional language designed for building scalable and maintainable applications http://elixir-lang.org/

to

> Elixir is a dynamic, functional language designed for building scalable and maintainable applications https://elixir-lang.org/

**Comment by josevalim** [comment]
Good call, thanks! 
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by eksperimental** [comment]
You are welcome
