### ISSUE TITLE
Tackling the runtime vs compile time configuration issue 

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9586]
This is issue tackles a limitation that has been made more critical
with the addition of releases, as releases increases the separation
between runtime and compile-time configuration.

In a nutshell, the issue is that people write this code:

    @some_var Application.get_env(:my_app, :key)

And then they set it in their config/releases.exs:

    config :my_app, :key, System.get_env!("FOO_BAR")

Which won't have an effect!

To tackle this, we plan to do two changes:

  * [x] Add an `Application.compile_env(:my_app, :key)` function.
    This function will annotate all values read at compile time
    and, once the system boots, it will validate those values
    have not changed!

  * [x] Deprecate using `Application.get_env(:my_app, :key)` in the
     module of a body (outside of a function).

The only limitation of this proposal is that it won't work for
things like Phoenix, where only some of the keys are compile-time.
To support complex configurations like Phoenix, we will also allow
a path to be given:

    Application.compile_env(:my_app, [MyApp.Repo, :debug_errors])

That will traverse the paths and annotate that only that specific
nesting is compile-time.

**Comment by josevalim** [comment]
Closing in favor of #9602. The deprecation task was added as a TODO to the code.

**Comment by jamesstonehill** [comment]
> Closing in favor of #9602. The deprecation task was added as a TODO to the code.

This feature ended up being implemented here: #9628
