### ISSUE TITLE
Clarify module documentation for Config.Reader

### ISSUE THREAD

**Issue by liamwhite** [elixir-lang/elixir#9629]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 22; Elixir 1.9.4
* Operating system: Linux 5.3.12-300.fc31.x86_64

### Current behavior

`Config.Reader` currently includes the following in its moduledoc:
https://github.com/elixir-lang/elixir/blob/c9c1068fe5eda1d7d407f13cbb316520d413c041/lib/elixir/lib/config/reader.ex#L5-L15

However, I'm unclear as to how
1. this works outside of the `mix release` task - can I use it in development?
2. this is even possible, given that https://github.com/elixir-lang/elixir/blob/c9c1068fe5eda1d7d407f13cbb316520d413c041/lib/elixir/lib/config/reader.ex#L54-L58 seems to just directly [eval the json](https://github.com/elixir-lang/elixir/blob/c9c1068fe5eda1d7d407f13cbb316520d413c041/lib/elixir/lib/config.ex#L190-L232) ...

**Comment by josevalim** [comment]
Yes, that's a bad example, it should be a link to an elixir file. We will fix it, thank you!
