### ISSUE TITLE
IEx expand_fun error through remsh

### ISSUE THREAD

**Issue by stavro** [elixir-lang/elixir#9636]
### Environment

* Elixir `v1.9.1`, Erlang `v22.0.4`
* Ubuntu (remsh origination) & Alpine Linux (remsh target)

### Current behavior

Connecting to a remote node via:

```bash
iex --hidden --cookie "$COOKIE" --name root@10.12.2.187 --remsh server@"$PRIVATE_IP"
```

When issuing a `tab` for autocompletion, an error occurs and the shell completely terminates.

```
19:41:51.226 [error] Process #PID<0.75.0> on node :"root@10.12.2.187" raised an exception
** (BadFunctionError) function #Function<24.134130798/1 in IEx.Autocomplete> is invalid, likely because it points to an old version of the code
    (kernel) error_handler.erl:65: :error_handler.undefined_lambda/3
    (kernel) group.erl:596: :group.get_line1/5
    (kernel) group.erl:471: :group.get_chars_loop/9
    (kernel) group.erl:181: :group.io_request/6
    (kernel) group.erl:117: :group.server_loop/3
```

Both systems have the same version of Elixir & Erlang. The target host is running a release built through `mix release`

Issuing the following command stops the error from happening, at the expense of completely disabling autocomplete: `:io.setopts(expand_fun: fn _ -> {:no, [], []} end)`

### Expected behavior

IEx autocomplete should work in a remsh environment, ideally, and not throw an error at a minimum.

**Comment by ericmj** [comment]
This is likely because your local elixir and remote elixir are different versions. Please double check that they are actually the same version.

**Comment by stavro** [comment]
Let me know if you'd like me to run some more debugging information. But here's what I see:

From root node:

```bash
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 20)
```

From target node:

```
Erlang/OTP 22 [erts-10.4.3] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

Interestingly, they're running the same versions of both platforms, but it does appear that on the root node it was compiled from a different OTP version... Could that be it? Will attempt to recompile it and check again.

**Comment by stavro** [comment]
Yes - this was the issue.

Elixir was compiled on OTP 20. Changing the compilation target fixed it.
