### ISSUE TITLE
DateTime.from_iso8601!/2 support?

### ISSUE THREAD

**Issue by kpanic** [elixir-lang/elixir#9642]
Hello everyone, I noticed that we don't have `DateTime.from_iso8601!/2`, however we have `Date.from_iso8601!/2`

I found this thread in the elixir lang core ml:
https://groups.google.com/forum/#!msg/elixir-lang-core/fJNYux9OrwQ/Dqyf3MctAgAJ

Would you be interested in a PR for this?
I could prepare it

If not, I'll close the issue.

Thanks!

**Comment by josevalim** [comment]
Hi! When we discussed it in the mailing list, I believe we could not agree if it should return a tuple or only the DateTime. Which is why this API does not exist. But maybe it is worth revisiting the discussion there if someone has new arguments. Thanks!
