### ISSUE TITLE
The readme.me document is incorrect

### ISSUE THREAD

**Issue by MarkHoo** [elixir-lang/elixir#9644]
After downloading the master branch to compile and install, the version of elixir is 1.10.0-dev.
The readme.me document is incorrect

```
git clone https://github.com/elixir-lang/elixir.git
cd elixir
make clean test
```

```
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

Interactive Elixir (1.10.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
```

**Comment by josevalim** [comment]
I have updated the README to say "information similar to", as a couple things may be different besides the Erlang/OTP and IEx versions. Thank you!
