### ISSUE TITLE
A possible syntax for creating tuples in lists has not been documented afaik

### ISSUE THREAD

**Issue by thojanssens** [elixir-lang/elixir#9645]
```
iex> [1, foo: 2, bar: 3]
[1, {:foo, 2}, {:bar, 3}]
```

It is not a keyword list, yet the syntax to build keyword lists can be used in a list containing non-tuples, as long as they are the last elements in the list. I can often see the use of this syntax, e.g. in Ecto options.

Honestly I had a wtf-moment. Do you think that it should be mentioned in the documentation?

**Comment by devonestes** [comment]
That seems more like a compiler bug to me... I would think that we should raise an exception in that case since it's most likely a typo in what was intended to be a keyword list, right?

**Comment by thojanssens** [comment]
My guess is that a lot of existing code would fail then.

One example of this use of syntax in Ecto docs:
https://github.com/elixir-ecto/ecto/blob/v3.3.0/lib/ecto/query.ex#L1893
