### ISSUE TITLE
Support adding additional files to a Mix release, i.e. Distillery overlays

### ISSUE THREAD

**Issue by dcrck** [elixir-lang/elixir#9651]
Hi,

I'm trying to replicate the [Distillery AWS deployment example](https://github.com/bitwalker/distillery-aws-example) using Mix releases. I reached a hangup when I was trying to add a custom file, which AWS will use for deployment, to the tarball. In Distillery it looks like this is possible using [Overlays](https://hexdocs.pm/distillery/extensibility/overlays.html). 

Is there a way to do this using Mix releases? @josevalim indicated on the forum that it isn't possible right now. How can I work around this in the meanwhile, aside from just copying the files manually using SCP?

Thanks!

**Comment by josevalim** [comment]
Hi @dcrck!

We have avoided overlays because they could simply be copied manually before but I think you ran into an actual limitation.

  1. Support an `:overlays` option that is a map (or a function that returns a map) of source files to their destination

  2. Support rel/overlays, where files in said directory are automatically copied to the release. rel/overlays has a limitation that it wouldn't support dynamic files (or it can support dynamic files by writing them to rel/overlays before calling assemble)

/cc @ericmj @wojtekmach @Gazler @fertapric

**Comment by josevalim** [comment]
Actually, I think we can mix both approaches.

```
  :overlays - extra files to be copied into the release.
  Must be a string pointing to a directory that is copied
  recursively to the release root or a function that may
  perform any action and returns a list of extra files.
  Defaults to "rel/overlays".
```

**Comment by Gazler** [comment]
The limitation here is that we only include specific directories in the tar ball?

For example, you could add a file by doing something like:

```
  steps: [:assemble, &add_file_tasks/1, :tar],


  defp add_file(rel) do
    [{_, bin}] = Code.load_file(Path.join(["..", "some_file.ex"]))
    path = Path.join([rel.path, "lib", "#{rel.name}-#{rel.version}", "ebin"])
    File.mkdir_p(path)
    File.write(Path.join([path, "some_file.beam"]), bin)
    rel
  end
```

However if the file wasn't inside the `lib` directory then it wouldn't be included?

**Comment by josevalim** [comment]
@Gazler correct.

**Comment by Gazler** [comment]
I think `overlays` makes sense. The only alternative I can think of is to add extra configuration to the step, for example:

```
  steps: [:assemble, {:tar, [overlays: ...]}],
```

However this would require duplicating it if we want to use overlays elsewhere.

**Comment by blackode** [comment]
IMO, forcing to put files in one dir named  `assets` will be much easier and neat.

**Comment by mobileoverlord** [comment]
Do the files have to be in the lib dir? We include ExUnit tests in the release by copying them to another top level directory.

**Comment by mobileoverlord** [comment]
Ah, I am reminded that we tar the release ourselves.

**Comment by dcrck** [comment]
Also, for umbrella applications the above strategy doesn't quite work, I have to put the files I want into one of the child apps' directories.

I've worked around this for now, but I'm looking forward to seeing this in 1.10.
