### ISSUE TITLE
Remote connection to elixir IEx through ssh port forwarding fails only for IEx (not for erl)

### ISSUE THREAD

**Issue by grufino** [elixir-lang/elixir#9656]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
On target host: Elixir 1.8 OTP 21
localhost: Elixir 1.9 OTP 22
* Operating system: 
target host: Gentoo Base System release 2.6
localhost: MacOS High Sierra
### Current behavior

Hello! I am trying to build a script to connect to a remote machine through ssh port forwarding, then run IEx using remsh and that port from localhost.
What is very strange is that I can successfully connect (and confirm that by loading all my modules) through erl and even run observer seeing everything that’s going on the other server, but not through iex, using the same parameters.

ssh command:
```
ssh -N -L $port:localhost:$port -L 4369:localhost:4369 my_app@$machine &
```
in this case port is the internal epmd port, example:

epmd: up and running on port 4369 with data:
name my_app at port 31747
port = 31747

and machine is just the hostname, something like: qa.company_name.com

commands that work:
```
erl -name debug@127.0.0.1 -setcookie $secret_cookie -hidden -run observer
erl -name "debug@127.0.0.1" -setcookie "$secret_cookie" -remsh "my_app@127.0.0.1"
```
execution:
```
Erlang/OTP 22 [erts-10.5.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Eshell V10.1.1  (abort with ^G)
(my_app@127.0.0.1)1>
```
command that doesn’t work:
```
iex --name "debug@127.0.0.1" --cookie "$secret_cookie" --remsh "my_app@127.0.0.1"
```
Error message:
```
Could not contact remote node my_app@127.0.0.1, reason: :nodedown. Aborting...
```

**Comment by josevalim** [comment]
Can you try this:

```
$ iex --name "debug@127.0.0.1" --cookie "$secret_cookie"
iex> Node.get_cookie
...
iex> :rpc.call :"my_app@127.0.0.1", :code, :ensure_loaded, [IEx]
...
```

And please let me know what both commands return?

**Comment by grufino** [comment]
Thanks for the quick reply, here you go:
```
iex --name "debug@127.0.0.1" --cookie "my_magic_cookie"
Erlang/OTP 22 [erts-10.5.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.9.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(debug@127.0.0.1)1> Node.get_cookie
:my_magic_cookie
iex(debug@127.0.0.1)2> :rpc.call :"my_app@127.0.0.1", :code, :ensure_loaded, [IEx]
{:badrpc, :nodedown}
```

**Comment by josevalim** [comment]
> update: I forgot to update the user in my env to the correct user, after I did, the last output changed.

So now IEx should work too. No?

**Comment by grufino** [comment]
@josevalim nope, I forgot to update only before replying you, in the script it was already correct, the problem persists. When I remove the `remsh` command it doesnt get the data from the server.

**Comment by josevalim** [comment]
Thanks. I am afraid I will need some way to reproduce this then. :/ What IEx does is basically to call `:rpc.call` behind the scenes but that is failing with `{:badrpc, :nodedown}` when you use `--remsh`. But when you are doing it manually it seems to be working fine.

**Comment by grufino** [comment]
So I've been trying to reproduce the error, but without success, if I try to connect to another node locally with remsh it works, I even tried ssh forwarding from inside docker container and then remsh and it worked, so I'm starting to assume the issue can be related to our custom linux version or something in our enviroment.

I still wonder why the erl remsh works normally, and even if I run iex without remsh and then try Node.connect it also works, but iEX with remsh doesn't, few examples:
```
iex --name "debug@127.0.0.1" --cookie "$secret_cookie" 
iex(debug@127.0.0.1)7> :rpc.call :"segmentation_api_qa@127.0.0.1", :code, :ensure_loaded, [IEx]
{:module, IEx}
iex(debug@127.0.0.1)8> Node.list
[:"segmentation_api_qa@127.0.0.1"]
iex(debug@127.0.0.1)9> Node.connect(:"segmentation_api_qa@127.0.0.1")
true
iex(debug@127.0.0.1)10> Node.start(:"segmentation_api_qa@127.0.0.1")
{:error,
 {{:already_started, #PID<0.56.0>},
  {:child, :undefined, :net_sup_dynamic,
   {:erl_distribution, :start_link,
    [[:"segmentation_api_qa@127.0.0.1", :longnames, 15000], false]}, :permanent,
   1000, :supervisor, [:erl_distribution]}}}
iex(debug@127.0.0.1)11> :net_adm.names
{:ok, [{'debug', 49623}]}
```

Is there a way to start remsh after running iEX? or start iex from erl? Maybe helps me debug.

Anyway thanks for the help and I think this issue can be closed since I cannot reproduce outside my environment.

**Comment by josevalim** [comment]
You can always start remsh after you open IEx by pressing Ctrl+G and then:

    r 'node@127.0.0.1' 'Elixir.IEx'

That should probably work!
