### ISSUE TITLE
ambiguity in struct/2

### ISSUE THREAD

**Issue by ityonemo** [elixir-lang/elixir#9657]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.4 (compiled with Erlang/OTP 21)

### Current behavior

`Kernel.struct/2` does not follow expected keyword map semantics.

```elixir
iex(1)> defmodule A do
...(1)>   defstruct [:a]
...(1)> end
{:module, A,
 <<70, 79, 82, 49, 0, 0, 5, 188, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 178,
   0, 0, 0, 18, 8, 69, 108, 105, 120, 105, 114, 46, 65, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, %A{a: nil}}
iex(2)> kwm = [a: 1, a: 0]
[a: 1, a: 0]
iex(3)> struct(A, kwm)
%A{a: 0}
iex(4)> kwm[:a]
1
```

### Expected behavior
```
iex(3)> struct(A, kwm)
%A{a: 1}
```
or, documentation warning about the behavior of `struct/2`

**Comment by josevalim** [comment]
Thanks @ityonemo! FWIW, Map.new also returns the last element. So the best way to go here is to document the behaviour.
