### ISSUE TITLE
"matched pattern" misused in String module

### ISSUE THREAD

**Issue by RichMorin** [elixir-lang/elixir#9659]
The documentation for the String module misuses the phrase "matched pattern" (twice):

    ... a function that receives the matched patterns:

The function receives the result of the pattern matches, not the matched patterns.

    ... one can inject the whole matched pattern in the replacement string.

Again, one can replace the result of the pattern match, not the matched pattern.

**Comment by evantravers** [comment]
This is interesting. Could you tell me more about what "matched pattern" actually means to you?

**Comment by wojtekmach** [comment]
Perhaps the phrase "matched pattern" (as in strings/regexs etc) was used deliberately to distinguish from "pattern matches" (as in FP); to me such distinction makes sense.

**Comment by RichMorin** [comment]
> On Dec 19, 2019, at 11:39, Evan Travers <notifications@github.com> wrote:
> 
> This is interesting. Could you tell me more about what "matched pattern" actually means to you?

I would interpret "matched pattern" as meaning "the pattern which was matched"
(as opposed to "the substring which matched the pattern").

-r

**Comment by evantravers** [comment]
In searching the docs, "matched pattern" only shows up on this one docs page… so it doesn't look like anyone else is using this to mean this thing.

In looking through the `Regex` module, it looks like they use the language of "pattern" to describe the regex/pattern (also used by `String.replace`), and "match" for the result. Let me see how this ends up reading…
