### ISSUE TITLE
Project deps that specify :targets require :override when also a dep of a dep

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-lang/elixir#9664]
Example project: 

https://github.com/mobileoverlord/target-override

Dep tree:

```bash
app
├── dep2 (../dep2)
└── dep1 (../dep1)
    └── dep2 (../dep2)
```

In the example, `app` and `dep1` both have a dependency on `dep2`. However, `app` specifies its dependency on `dep2` with `{:dep2, targets: :foo}` and `dep1` does not. This causes dependency resolution to raise the error:

```elixir
Dependencies have diverged:
* dep2 (../dep2)
  the :targets option for dependency dep2

  > In mix.exs:
    {:dep2, [env: :prod, path: "../dep2", targets: :foo]}

  does not match the :targets option calculated for

  > In /Users/jschneck/Desktop/target-override/dep1/mix.exs:
    {:dep2, [env: :prod, path: "../dep2"]}

  Remove the :targets restriction from your dep
** (Mix) Can't continue due to errors on dependencies
```

Adding `override: true` to the options for `dep2` in `app` allows dependency resolution to succeed, but this feels like an undesirable solution to this problem.

**Comment by josevalim** [comment]
After thinking about it a bit, I would say the error makes sense. That's because dep1 depends on dep2. Once you say dep2 is only in a certain target X, it means dep1 would be without dep2 on target Y. You can either override or limit both dep1 and dep2 to the same targets.

**Comment by josevalim** [comment]
Can you please let us know the names of dep1 and dep2 as it actually happened in practice? Maybe the error doesn't make sense when we understand the actual dependencies.

**Comment by josevalim** [comment]
Closing ler the above after confirming it with @mobileoverlord.
