### ISSUE TITLE
ExUnit failures message adds parens to map fields

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#9668]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.0-dev (d2ac69e) (compiled with Erlang/OTP 22)
* Operating system: macOS 10.15.2

### Current behavior

```
assert 1 = ~D[2019-01-01].year
** (ExUnit.AssertionError)

match (=) failed
code:  assert 1 = ~D"2019-01-01".year()
left:  1
right: 2019
```

Note `()` in `~D"2019-01-01".year()`

### Expected behavior

```
assert 1 = ~D[2019-01-01].year
** (ExUnit.AssertionError)

match (=) failed
code:  assert 1 = ~D"2019-01-01".year
left:  1
right: 2019
```

**Comment by josevalim** [comment]
I will push a fix soon.
