### ISSUE TITLE
Release steps defined in dependencies render warnings

### ISSUE THREAD

**Issue by mobileoverlord** [elixir-lang/elixir#9676]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10-dev (7f86ea3)
* Operating system: *

### Current behavior
`
Mix will render a warning about functions in the release steps that come from dependencies.

### Expected behavior

Do not render the warning. This was the behavior < 1.10

Here is an example project that demonstrates this: https://github.com/mobileoverlord/release_warn

**Comment by josevalim** [comment]
@ericmj do you think we should disable these warnings for mix.exs?

**Comment by ericmj** [comment]
After talking with Jose we decided:

We should add an option to disable the undefined function warnings on `Code` and `Kernel.ParallelCompiler` functions. `Mix.CLI` should use this option when loading `mix.exs` https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/cli.ex#L42.
