### ISSUE TITLE
“make” is failing

### ISSUE THREAD

**Issue by lindividual** [elixir-lang/elixir#9680]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 22 [erts-10.6.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]
* Operating system: CentOS Linux release 7.7.1908 (Core)

### Current behavior

[root@VM_0_11_centos ~]# git clone https://github.com/elixir-lang/elixir.git
Cloning into 'elixir'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (78/78), done.
remote: Total 147871 (delta 54), reused 50 (delta 30), pack-reused 147763
Receiving objects: 100% (147871/147871), 41.53 MiB | 232.00 KiB/s, done.
Resolving deltas: 100% (95504/95504), done.
[root@VM_0_11_centos ~]# cd elixir/
[root@VM_0_11_centos elixir]# make clean test
rm -rf ebin
rm -rf lib/*/ebin
rm -rf lib/elixir/src/elixir_parser.erl
make[1]: Entering directory `/root/elixir'
rm -rf lib/*/_build/
rm -rf lib/*/tmp/
rm -rf lib/elixir/test/ebin/
rm -rf lib/mix/test/fixtures/deps_on_git_repo/
rm -rf lib/mix/test/fixtures/git_rebar/
rm -rf lib/mix/test/fixtures/git_repo/
rm -rf lib/mix/test/fixtures/git_sparse_repo/
rm -f erl_crash.dump
make[2]: Entering directory `/root/elixir'
rm -f man/elixir.1
rm -f man/elixir.1.bak
rm -f man/iex.1
rm -f man/iex.1.bak
make[2]: Leaving directory `/root/elixir'
make[1]: Leaving directory `/root/elixir'
Crash: error:undef
[{yecc,compile,
       ["/root/elixir/lib/elixir/src/elixir_parser",
        "/root/elixir/lib/elixir/src/elixir_parser",
        {options,[],"/root/elixir",undefined,[],1,false,999,
                 [{report,true},{verbose,true}],
                 "/root/elixir/lib/elixir/src/elixir_parser.erl",
                 "/root/elixir"}],
       []},
 {erl_compile,compile_file,4,[{file,"erl_compile.erl"},{line,290}]},
 {erl_compile,compile3,3,[{file,"erl_compile.erl"},{line,277}]},
 {erl_compile,compile,2,[{file,"erl_compile.erl"},{line,60}]},
 {erl_compile,'-compile_cmdline1/1-fun-0-',2,
              [{file,"erl_compile.erl"},{line,73}]}]
make: *** [lib/elixir/src/elixir_parser.erl] Error 2
[root@VM_0_11_centos elixir]# erl
Erlang/OTP 22 [erts-10.6.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:1] [hipe]

### Expected behavior

should work

**Comment by josevalim** [comment]
Some OS distributions break Erlang/OTP apart into multiple packages. This is not actually how Erlang should be distributed but it is something out of our control. In your case, you are a missing a erlang-parser package or erlang-parsertools or similar. If you install it, everything should work as expected. Thanks for the report!

**Comment by lindividual** [comment]
> Some OS distributions break Erlang/OTP apart into multiple packages. This is not actually how Erlang should be distributed but it is something out of our control. In your case, you are a missing a erlang-parser package or erlang-parsertools or similar. If you install it, everything should work as expected. Thanks for the report!

it works, thanks！
