### ISSUE TITLE
Enum.chunk/2 not documented

### ISSUE THREAD

**Issue by hobson42** [elixir-lang/elixir#9692]
The function Enum.chunk/2 is available in release 1.9.4 and previous versions, but is not included in the documentation. 

This is unfortunate because it is used in the udemy course "The Complete Elixir and Phoenix Bootcamp".

**Comment by wojtekmach** [comment]
The function is no longer documented because it's been deprecated since Elixir v1.7 [1] in favour of Enum.chunk_every.

[1] https://hexdocs.pm/elixir/master/compatibility-and-deprecations.html#table-of-deprecations

**Comment by josevalim** [comment]
Correct. Our general policy is that Functions that emit deprecation warnings when invoked are no longer documented. Thanks for the report!
