### ISSUE TITLE
An Regex.named_captures alternative that return a list instead of one group?

### ISSUE THREAD

**Issue by sezaru** [elixir-lang/elixir#9698]
Hello, currently `Regex.named_captures` returns the first regex group sequence found, for example:
```
regex = ~r/value.+?(?<score>\d)/iu
Regex.named_captures(regex, "value 1 and value 2")
```
Will return `%{"score" => "1"}`

But in the case that I need to find multiple times the regex in the string, there is no alternative to that function.

Can we have a version of `Regex.named_captures` that return a list instead? Looking at that function implementation I derived this solution:
```
  def named_captures(regex, string, options \\ []) when is_binary(string) do
    names = Regex.names(regex)
    options = Keyword.put(options, :capture, names)

    regex
    |> Regex.scan(string, options)
    |> Enum.map(fn result -> Enum.zip(names, result) |> Enum.into(%{}) end)
  end
```

Now running the exame core will return `[%{"score" => "1"}, %{"score" => "2"}]`

**Comment by josevalim** [comment]
Hi @sezaru! Rolling your own sounds like a great idea for now, thanks for the code samples. If it becomes a commonly requested feature, then we can also add it to the Elixir in the future. :heart:

**Comment by Ljzn** [comment]
Hi, it is a useful feature imo. In javascript the `matchAll` can do it llikes:
```js
const regexp = /test(?<number>\d)/g;
const str = 'test1test2';

const array = [...str.matchAll(regexp)];

console.log(array.map(e => e.groups));
// Expected output: Array [Object { number: "1" }, Object { number: "2" }]
```

I think we can add an option item to `Regex.scan`, likes `return: :named_group`, as we already has `return` option.
