### ISSUE TITLE
New Enum.max, max_by, min, min_by api introduces a breaking change

### ISSUE THREAD

**Issue by lukaszsamson** [elixir-lang/elixir#9701]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.0-rc.0 (105770c) (compiled with Erlang/OTP 22)

### Current behavior

New default parameter `sorter \\ &<=/2` breaks existing code using empty fallback
```
Enum.max_by(enum, fn e -> get_value_from(e) end, fn -> :empty end)
Enum.max(enum, fn -> :empty end)
Enum.min_by(enum, fn e -> get_value_from(e) end, fn -> :empty end)
Enum.min(enum, fn -> :empty end)
```
now empty fallback is passed as sorter.
This requires manual inspection of all usages

### Expected behavior

New default parameters should be added only at end.

**Comment by wojtekmach** [comment]
Could you show an example where it breaks? I tried all examples from 1.9 docs and they still work on 1.10 for me:

```elixir
iex> Enum.max([], fn -> 0 end)
0
iex> Enum.max_by(["a"], &String.length/1, fn -> nil end)
"a"
iex> Enum.min([], fn -> 0 end)
0
iex> Enum.min_by([], &String.length/1, fn -> nil end)
nil
```

**Comment by lukaszsamson** [comment]
@wojtekmach I see. I was basing my concerns on lots of dialyzer warnings like those:

```
The function call will not succeed.

Enum.min([any()], (() -> nil))

will never return since it differs in arguments with
positions 2nd from the success typing arguments:

(any(), atom() | (_, _ -> boolean()))
```

```
The function call will not succeed.

Enum.max_by(
  any(),
  (_ -> any()),
  (() -> {0,
          %MyStruct{}})
)

will never return since it differs in arguments with
positions 3rd from the success typing arguments:

(any(), (_ -> any()), atom() | (_, _ -> boolean()))
```

as well as seeing specs like
```
min_by(enumerable, fun, sorter \\ &<=/2, empty_fallback \\ fn -> raise(Enum.EmptyError) end)
```
in the docs.

I was not aware about the hackery in https://github.com/elixir-lang/elixir/blob/2cab7ec926171d8c8ca747c4e76a0b5b78e27ae4/lib/elixir/lib/enum.ex#L1739

The expected behaviour is that for a func
```
def my(a \\ nil, b \\ nil) , do: :ok
```
the call
```
my(3)
```
is equivalent to
```
my(3, nil)
```
and not to
```
my(nil, 3)
```

**Comment by josevalim** [comment]
Yes, it seems to behave correctly, but if you have a failing snippet or failing test, please let us know!

**Comment by lukaszsamson** [comment]
@josevalim it seems so yet dialyzer is not happy. Maybe we need to change the spec from
```
@spec min(t, (element, element -> boolean) | module(), (() -> empty_result)) ::
          element | empty_result
when empty_result: any
def min(enumerable, sorter \\ &<=/2, empty_fallback \\ fn -> raise Enum.EmptyError end)
```
to
```
@spec min(t, (element, element -> boolean) | module() | (() -> empty_result), (() -> empty_result)) ::
          element | empty_result
when empty_result: any
def min(enumerable, sorter \\ &<=/2, empty_fallback \\ fn -> raise Enum.EmptyError end)
```
etc.

**Comment by josevalim** [comment]
Yes, when we soft deprecate an API, we also change the `@spec` notation to the latest, so Dialyzer warns and users update their code to the non-deprecated version.
