### ISSUE TITLE
Warning this expression will fail with ArithmeticError provides no file location

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9714]
### Environment

```
$ elixir --version
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

### Current behavior

This is rare, but I had twice I can remember this compiler warning message with no file location information

```
warning: this expression will fail with ArithmeticError
  lib/.../file.ex
```

### Expected behavior

There should be a line number reported in the message to help discover what is happening.

I hope this information is enough to debug and fix this issue (in case I get more information, I will post here).

**Comment by josevalim** [comment]
Can you Please provide a file that reproduces the error? Thank you!
-- 


*José Valim*
www.plataformatec.com.br
Founder and Director of R&D

**Comment by mguimas** [comment]
This happened during a `recompile` inside `IEx`. After exiting `IEx`, and starting it again with `iex -S mix`, everything compiled without any error or warning.

There must something unstable with `recompile`, since in other ocasions when I get unexpected errors, I tend to exit `IEx`, and come back again, and everything compiles fine.

**Comment by mguimas** [comment]
I cannot reproduce this error since I exited `IEx`, and everything is compiling fine now. Sorry.

**Comment by mguimas** [comment]
OK, I can reproduce it now. For example, the module:

```
defmodule X do
  def foo do
    elem({1,2}, @missing)
  end
end
```

results in

```
iex(20)> recompile
Compiling 1 file (.ex)
warning: redefining module X (current version defined in memory)
  lib/x.ex:1

warning: undefined module attribute @missing, please remove access to @missing or explicitly set it before access
  lib/x.ex:3: X (module)

warning: this expression will fail with ArithmeticError
  lib/x.ex
```
