### ISSUE TITLE
Unexpected behavior of mix test with specific invalid line numbers

### ISSUE THREAD

**Issue by adrianomitre** [elixir-lang/elixir#9727]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.4 (compiled with Erlang/OTP 20)
* Operating system: Ubuntu 18.04.3 LTS (kernel 4.15.0-72-generic)

### Current behavior

Create a new Elixir project with `mix new foo`, enter the project path with `cd foo`, then edit  `test/foo_test.exs` to the following:
```elixir
defmodule FooTest do
  use ExUnit.Case
  test "A", do: assert(true)

  test "B", do: assert(true)
  test "C", do: assert(true)
end
```

Examples of current behavior:
```
$ mix test --trace test/foo_test.exs:-43:0:1:2
Excluding tags: [:test]
Including tags: [line: "-43", line: "0", line: "1", line: "2"]


FooTest
  * test A (excluded)
  * test C (excluded)
  * test B (excluded)


Finished in 0.01 seconds
3 tests, 0 failures, 3 excluded

Randomized with seed 642462
```
```
$ mix test --trace test/foo_test.exs:4
Excluding tags: [:test]
Including tags: [line: "4"]


FooTest
  * test B (excluded)
  * test C (excluded)
  * test A (0.00ms)


Finished in 0.01 seconds
3 tests, 0 failures, 2 excluded

Randomized with seed 258138
```
```
$ foo mix test --trace test/foo_test.exs:42
Excluding tags: [:test]
Including tags: [line: "42"]


FooTest
  * test B (excluded)
  * test A (excluded)
  * test C (0.00ms)


Finished in 0.01 seconds
3 tests, 0 failures, 2 excluded

Randomized with seed 489324
```

### Expected behavior

It seems to me that the expected behavior would be (i) to warn about the specific lines that do not exist, such as -43, 0 and 42 (first and last examples); (ii) to warn about specific lines that do not contain any test definition, such as line 1 and 4 (first and second examples); and (iii) to not run any test.

**Comment by josevalim** [comment]
We always run the closest test defined on and before the given line. So line:42 works because it runs the last test.

We don't want to be very strict about this. For example, imagine I have this file:

```elixir
defmodule FooTest do
  test "..." do
    ...
    assert foo.bar
  end
end
```

Now imagine that `assert foo.bar` is failing and I run the test based on that line. If I add a newline to my test before the assertion, if we were struct, ExUnit would now suddenly complain that it can't find a test, which would be annoying. In this case, being strict serves no purpose, especially because it is a CLI convenience - your code in production won't rely on it.

We can warn for -42 and 0, but again, it would be validation for validation's sake. It is a CLI convenience and I don't expect users to be passing those values in any day to day situation. :)

**Comment by josevalim** [comment]
So to be clear, we would accept a PR that warns and discards `lines <= 0`. But the other lines are correct and being strict would be more of an inconvenience than a help.

**Comment by josevalim** [comment]
Closing in favor of PR, thanks!

**Comment by adrianomitre** [comment]
> We always run the closest test defined on and before the given line. So line:42 works because it runs the last test.

I believe that the first example above shows that not to be the case: test A is the "closest" to lines 1 and 2, however test A is not ran.

Actually, the _considered test region_ starts at the beginning of the actual test definition and ending in the line prior to the definition of the next test (or, in the case of the last test definition of the file, the region extends to infinity).

> If I add a newline to my test before the assertion and if we were strict, ExUnit would now suddenly complain that it can't find a test, which would be annoying.

What I mean by "It seems to me that the expected behavior would be [...] to warn about specific lines that do not contain any test definition" were lines that are not in the test definition region, i.e., from the `test` to the `end`, including both. Please refer to the example below:
```elixir
defmodule Test do  # warn
  use ExUnit.Case  # warn
                   # warn
  test "A" do      # run test A
                   # run test A
    assert true    # run test A
  end              # run test A
                   # warn
  test "B" do      # run test B
    assert false   # run test B
  end              # run test B
                   # warn
end                # warn
```

Being strict with the aforementioned interpretation would **not** lead to the undesired behavior you described.

**Comment by josevalim** [comment]
> I believe that the first example above shows that not to be the case:
test A is the "closest" to lines 1 and 2, however test A is not ran.

That’s exactly why I said the closest test “on or before” the given line. :)

So the region of a test is when it starts until the next test. As I said in
the previous message, changing it may be a bit inconvenient, so we
currently plan to keep the region as is. Thanks.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by adrianomitre** [comment]
> As I said in the previous message, changing it may be a bit inconvenient

In my previous message, I have shown that being strict with the aforementioned interpretation would **not** lead to the inconvenience described ("If I add a newline to my test before the assertion and if we were strict, ExUnit would now suddenly complain that it can't find a test, which would be annoying.")

Am I missing something?

**Comment by josevalim** [comment]
I think you are missing one important bit of information is that the line of the `end` is not in the AST, so at best we can go until the line before the `end`, which makes it a bit more brittle as we add and remove lines in the test.

**Comment by adrianomitre** [comment]
I did not know that indeed. Thanks for pointing that out.

In any case, if only the `end` line is missing, it should be possible to infer that the test definition range is `i..j+1` instead of `i..j`, assuming that the end goes in a line of its own, which would be true virtually always except for one-liners.

**Comment by josevalim** [comment]
> In any case, if only the end line is missing, it should be possible to infer that the test definition range is i..j+1 instead of i..j, assuming that the end goes in a line of its own, which would be true virtually always except for one-liners.

This is not true in cases like this:

```elixir
test "foo" do
  assert bar

end
```

Or when you comment something (which is also common when working on a test:

```elixir
test "foo" do
  assert bar
  # assert baz
  # assert bat
end
```
