### ISSUE TITLE
1.10.0-rc.0 compilation error with ExAws

### ISSUE THREAD

**Issue by sneako** [elixir-lang/elixir#9737]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.10.0-rc.0 (105770c) (compiled with Erlang/OTP 22)
```

* Operating system: `macOS Catalina 10.15.2 (19C57)`

### Current behavior
[ExAws](https://github.com/ex-aws/ex_aws) fails to compile using the new release candidate.
```
== Compilation error in file lib/ex_aws/config/defaults.ex ==
** (CompileError) nofile:1066: key "eu-west-1" will be overridden in map
    (stdlib 3.11.1) lists.erl:1263: :lists.foldl/3
    (stdlib 3.11.1) lists.erl:1354: :lists.mapfoldl/3
    (stdlib 3.11.1) lists.erl:1355: :lists.mapfoldl/3
```
[lib/ex_aws/config/defaults.ex](https://github.com/ex-aws/ex_aws/blob/master/lib/ex_aws/config/defaults.ex)

### Expected behavior

The library compiles as it did on the previous Elixir version.

**Comment by josevalim** [comment]
Thanks for giving the RC a try and reporting the regression!

**Comment by sneako** [comment]
My pleasure! Wish I could be more helpful, but I'm not sure where to begin with this one 😕
