### ISSUE TITLE
[ex_unit] Missleading error message when using `{assert,refute}_receive` not in `test/2,3`

### ISSUE THREAD

**Issue by NobbZ** [elixir-lang/elixir#9744]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): tested with 1.9.3-otp-22 and 1.9.4-otp-22, probably affects earlier versions as well
* Operating system: Arch Linux

### Current behavior

Example code available at GitHub: https://github.com/kbredemeier/test_template_issue

Running `mix test` yields the following compile error:

```plain
Compiling 2 files (.ex)

== Compilation error in file test/support/template.ex ==
** (ArgumentError) could not fetch application environment :assert_receive_timeout for application :ex_unit because the application was not loaded/started. If your application depends on :ex_unit at runtime, make sure to load/start it or list it under :extra_applications in your mix.exs file
    (elixir) lib/application.ex:498: Application.fetch_env!/2
    expanding macro: ExUnit.Assertions.assert_receive/1
    test/support/template.ex:13: Template.test_something/0
```

The proposed fix of adding `:ex_unit` to `:extra_applications` does of course not work.

Instead providing a timeout manually to `assert_receive` does indeed fix the error message or calling `Application.ensure_started(:ex_unit)` during compiletime.

### Expected behavior

I see 2 alternative expactations:

#### Improved error message and docs

The error message and the documentation should suggest to provide a default argument instead when not inside of `test/2,3`.

#### Change the default argument

Change the current default value, such that it is quaranteed to be resolved at runtime instead of compiletime-ish.

**Comment by josevalim** [comment]
We should definitely resolve it at runtime.

**Comment by josevalim** [comment]
Closing in favor of PR!
