### ISSUE TITLE
Make `recompile` rebuild whenever something needs to be rebuilt in the dependency tree

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9746]
### Environment

```
$ elixir --version
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.1 (compiled with Erlang/OTP 22)
```

### Current behavior

When calling `recompile` inside IEx, after changing the source files of a project included as a dependency in the project loaded via `iex -S mix`, does not rebuild the dependency project, but instead returns `:noop`. For example, after changing one source file in a dependency project
 
```
iex(18)> recompile
:noop
```

In this case the developer needs to quit IEx, and restart it to have the dependency recompile, like this:

```
iex(19)>
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
$ iex -S mix
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

==> dependency
Compiling 1 file (.ex)
Generated dependency app
==> main
Compiling 3 files (.ex)
Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
```

This behavior is boring, and causes the loss of all bindings and their state in the IEx session.

### Expected behavior

The `recompile` command should detect when source files (and others with influence in the build result) in the dependency tree of the project loaded via `iex -S mix` have changed and need to be rebuilt, and build them.

The dependency projects I used to test are all local and included in the `main` project as `      {:dependency, in_umbrella: true}`, but `recompile` should rebuild even when dependency projects are updated from the network, for example, after issuing a `mix deps` command or similar.

Probably `recompile` needs to do the same checks that `iex -S mix` does at start to rebuild what needs to be rebuilt.

Note that today's workaround to all this is to run `recompile force: true` but this rebuilds what does not need to be rebuilt, thus being a time waste and disruptive of development flow.

**Comment by josevalim** [comment]
Unfortunately this is far from trivial to implement. The issue is that the current application obviously depends on its dependencies, which may form a tree, so we would need to shut down all of the dependencies, in the proper order, and then restart them again - while busting any cache along the way. The whole process is complex and error prone, which is why for compiling dependencies, it is simpler to just start from scratch.

The author is welcome to give the problem a try if you believe this can be trivially addressed or it is a very important feature to have.

**Comment by esse** [comment]
@mguimas you can try workaround I've created:
https://github.com/esse/recompile_dep
https://hex.pm/packages/recompile_dep

It's working for me, but you know - it's very experimental ;)
Let me know if you decide to give it a shot.

**Comment by vans163** [comment]
Yea I dont agree @josevalim, this is not a release, the whole point of recompile is to be a "works most of the time in development" type of tool.  Often I have the case where I am developing a new project and some of the deps its using need updates too, I do not want to restart my project every single time I change one of those deps.  Often the project has state and external API connections, etc.  So every restart + the time to get the project synced up with external calls can often take 1min+.

Every interruption where hotload is not possible costs 1min+, and interruptions happen often in early stages of projects.
