### ISSUE TITLE
Date.compare accepts NaiveDateTimes and ignores the Date part

### ISSUE THREAD

**Issue by marick** [elixir-lang/elixir#9753]
I noticed that the following test passes:

```elixir
  test "Time.compare and NaiveDateTimes" do
    datetime =  ~N[2001-01-01 01:02:03]
    datetime2 = ~N[2222-02-22 01:02:03]

    assert Time.compare(datetime, datetime2) == :eq
  end
```

Note that it's comparing only the `Time` part of the `NaiveDateTime`. 

Is this intentional? 

One datapoint: I discovered this when trying to produce two `Ecto.Types` for Postgres range types. I made a mistake about what the endpoint type of one of them should be:

```elixir
defmodule Ecto.Timespan do
  use Ecto.Span, db_type: :tsrange, type: Time
  alias Pile.TimeHelper
```

### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.2 (compiled with Erlang/OTP 22)
* Operating system: MacOS 10.14.4

**Comment by josevalim** [comment]
Yes, it is intentional. Most of the functions in the Calendar types work with structural typing, so they will accept any value that have the necessary map fields. This was done to avoid unnecessary conversions. For example, I can reach out for time properties of a NaiveDateTime without a need to explicitly convert it before.

This is documented on all modules too. For example, Date module says:

> The functions on this module work with the Date struct as well as any struct
> that contains the same fields as the Date struct, such as NaiveDateTime and
> DateTime.

**Comment by marick** [comment]
Would it be reasonable to add some text to `Time.compare` (etc.) that points out this behavior? I don't know what I was thinking last time I looked at its documentation, but I'm sure I didn't click through the `Calendar.time()` items in the spec to see that they meant "any record that contains the appropriate fields". I think structural typing is excellent, but documentation wouldn't hurt, I think. 

If so, I'll make pull requests.

I'd almost think that a better type than `Calendar.time()` would be `Calendar.contains_time()`, but that's probably too big a change.

**Comment by josevalim** [comment]
Yes, if you feel repeating the remarks is helpful, then a PR is definitely
welcome.
-- 


*José Valimhttps://dashbit.co/ <https://dashbit.co/>*
