### ISSUE TITLE
compilation error for typespec of struct in defining module -> type t/0 undefined

### ISSUE THREAD

**Issue by Harper04** [elixir-lang/elixir#9758]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.5.6] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [hipe]

Elixir 1.10.0 (compiled with Erlang/OTP 22)
```
* Operating system: Catalina

### Current behavior
test.ex
```
defmodule TestModule do
  defstruct test: 0
  @spec new() :: TestModule.t()

  def new do
    %__MODULE__{}
  end
end
```

```
> elixirc test.ex

== Compilation error in file test.ex ==
** (CompileError) test.ex:3: type t/0 undefined (no such type in TestModule)
    (elixir 1.10.0) lib/kernel/typespec.ex:898: Kernel.Typespec.compile_error/2
    (elixir 1.10.0) lib/kernel/typespec.ex:937: Kernel.Typespec.fn_args/6
    (elixir 1.10.0) lib/kernel/typespec.ex:377: Kernel.Typespec.translate_spec/8
    (stdlib 3.10) lists.erl:1354: :lists.mapfoldl/3
    (elixir 1.10.0) lib/kernel/typespec.ex:229: Kernel.Typespec.translate_typespecs_for_module/2
    (elixir 1.10.0) src/elixir_erl_compiler.erl:12: anonymous fn/3 in :elixir_erl_compiler.spawn/2
```

### Expected behavior

As of Elixir 1.10.0 it is no longer possible to use the typespec of a struct in the same module where the struct is defined. I understand that this is a recursive definition and could lead to trouble for analysis during compilation etc. So i am not sure if this presents a regression or an expected behavior.

nevertheless here is my report :)

best regards!

**Comment by wojtekmach** [comment]
You need to explicitly define the type `t()`; this compiles:

```elixir
defmodule TestModule do
  defstruct test: 0

  @type t() :: %__MODULE__{}

  @spec new() :: TestModule.t()
  def new do
    %__MODULE__{}
  end
end
```

**Comment by Harper04** [comment]
Thanks that could be a workaround.
But unfortunately this emits a warning:
```
warning: redefining module TestModule (current version loaded from Elixir.TestModule.beam)
  test.ex:1
```

**Comment by josevalim** [comment]
Hi @Harper04, the above is not a workaround but rather the proper fix. Note that `defstruct` does not define a type `t` for you. So you have to do it yourself.

Previously Elixir did not error if you pointed to a type that did not exist but that would often lead to a failure elsewhere. So we are enforcing their existence now. The warning you are seeing is probably because you also have a `Elixir.TestModule.beam` at the current directory.

Other than that, recursive definitions are fine. :) Thanks for the report!

**Comment by Harper04** [comment]
That change makes sense! Thank your for the explanation!
