### ISSUE TITLE
Possible bug in the Calendar.ISO module

### ISSUE THREAD

**Issue by mathieuprog** [elixir-lang/elixir#9759]
See function `add_day_fraction_to_iso_days/3` in the link below.

There seem to be two function signatures with same name, same arity, and no guard clauses or something to match on that differs between the two...

How can the second function be ever called? Or is there some "magic" involved?

https://github.com/elixir-lang/elixir/blob/v1.10.0/lib/elixir/lib/calendar/iso.ex#L1171

(I also take advantage of this issue to ask to rename "ppd" variables by "parts_per_day" in all the files related to dates; I'd like to PR that but Elixir doesn't compile locally; another Windows nightmare.)

**Comment by josevalim** [comment]
The first clause will only match when both `ppd` variables have the same value:

```
  def add_day_fraction_to_iso_days({days, {parts, ppd}}, add, ppd) do
                                                  ---         ---
```

It is a tiny optimization.

**Comment by mathieuprog** [comment]
Of course completely missed that! Thank you for looking!
