### ISSUE TITLE
Give a compiler warning when aliases are captured

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9763]
### Environment

```
$ elixir --version
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
```

### Current behavior

Given this file

```
defmodule X do
 defmacro __using__(_) do
  quote do
   alias Mod.A
  end
 end
end
```

and this file

```
alias Pod.A 
defmodule Y do
 use X
 def foo, do: A.bar()
end
````

it may seem that function `foo` refers to module `Pod.A`, but in fact it refers to module `Mod.A`.

This happens because the use of module `X` implicitly captures the alias `A`.

### Expected behavior

Give a warning in the presence of two aliases referring to different modules in the same context.

A workaround is to always put aliases after uses, but this requires discipline on the programmer, and so, it is error-prone.

**Comment by josevalim** [comment]
Well, you are injecting code into the user context, so we expect that user context to be affected by the code you call. The solution is to not inject the alias in the user code. This would work:

```elixir
defmodule X do
 alias Mod.A

 defmacro __using__(_) do
  quote do
    A #=> will point to Mod.A but without affecting the user of this module
  end
 end
end
```

**Comment by mguimas** [comment]
@josevalim That is nice, but the inadvertent programmer may fall into this alias capture issue, hence a compiler warning would be helpful to avoid this pitfall, I think.

**Comment by michalmuskala** [comment]
This is used intentionally in many places, though. For example, in the default generators from Phoenix.

https://github.com/phoenixframework/phoenix/blob/ad28716cb2fc04613fb89ae26fe6c2cc3784ea48/installer/templates/phx_single/lib/app_name_web.ex#L26
