### ISSUE TITLE
Warn if none of <- or = are used in an with expression

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9764]
Otherwise one can accidentally write code like this:

```elixir
  def react_with_emoji(user, object, emoji, options \\ []) do
    with local <- Keyword.get(options, :local, true),
         activity_id <- Keyword.get(options, :activity_id, nil),
         is_unicode_emoji?(emoji),
         ...
```

while they meant:

```elixir
  def react_with_emoji(user, object, emoji, options \\ []) do
    with local <- Keyword.get(options, :local, true),
         activity_id <- Keyword.get(options, :activity_id, nil),
         true <- is_unicode_emoji?(emoji),
         ...
```

However, note today one can write:

```elixir
  def react_with_emoji(user, object, emoji, options \\ []) do
    with local <- Keyword.get(options, :local, true),
         activity_id <- Keyword.get(options, :activity_id, nil),
         some_side_effect(emoji),
         ...
```

So we will task them to write it as:

```elixir
  def react_with_emoji(user, object, emoji, options \\ []) do
    with local <- Keyword.get(options, :local, true),
         activity_id <- Keyword.get(options, :activity_id, nil),
         _ <- some_side_effect(emoji),
         ...
```

(or `_ = ...`).

**Comment by joladev** [comment]
I'm wondering if it could warn also in the case of `x = something()` (you don't mention it explicitly, but maybe it is already included in the issue and I misunderstood!)

```elixir
  def react_with_emoji(user, object, emoji, options \\ []) do
    with local = Keyword.get(options, :local, true),
         activity_id <- Keyword.get(options, :activity_id, nil),
         ...
```

It seems like if you're in a `with` you probably don't mean to use `=`. This typo bit me in the [diff.hex.pm project](https://github.com/hexpm/diff/pull/44). The only difference to `<-` is that you potentially throw a MatchError.

**Comment by wojtekmach** [comment]
to me with/1 is all about pattern matching and a clause like `var <- ...` *always* matches. For this reason I'd have people change:

```elixir
  def react_with_emoji(user, object, emoji, options \\ []) do
    with local <- Keyword.get(options, :local, true),
         activity_id <- Keyword.get(options, :activity_id, nil),
         true <- is_unicode_emoji?(emoji),
```

to:

```elixir
  def react_with_emoji(user, object, emoji, options \\ []) do
    local = Keyword.get(options, :local, true)
    activity_id = Keyword.get(options, :activity_id, nil)

    with true <- is_unicode_emoji?(emoji),
```

perhaps it's a bit too strict and if anything should be more of a Credo check, but I thought I'd mention this anyway.

**Comment by josevalim** [comment]
The issue is that using `=` today in `with` is supported as sometimes I want to mix "hard matches" with "soft matches" in the same `with`. If we disallow them, then we will be forcing users to write nested `with`s, which will introduce the problem `with` was meant to solve in the first place.

**Comment by joladev** [comment]
Would you not be able to replace any instance of  `=` with `<-`? For soft and hard matches.

**Comment by josevalim** [comment]
@joladev Sorry, I am not sure I follow the question. :)

**Comment by OvermindDL1** [comment]
@joladev The difference is that `<-` will just escape to the else clause if the matcher doesn't match, where `=` will throw an exception (I.E. this shouldn't happen or you don't want to handle it cleanly).  I use both for precisely these reasons in `with`.

**Comment by joladev** [comment]
@OvermindDL1 right, that's what I mentioned in an earlier comment. So you're saying that you'd want to throw the exception. To clarify:

```elixir
with scenario1 <- :error,
        scenario2 = :error,
        {:ok, scenario3} <- :error,
        {:ok, scenario4} = :error do
```

So here, scenario 1 and 2 are equivalent, while scenario 3 would pass to `else` and scenario 4 throw exception. If we force `<-` then it would be difficult to do trigger a `MatchError` in a `with`, you'd have to do something awkward like `{:ok, data} <- {:ok, _} = call()`. So my question earlier was whether it was better to support throwing `MatchError` or to warn, and I guess throw support is more important 🙂

**Comment by whatyouhide** [comment]
I’m 👍 on warning for `pattern_that_matches_anything <- ...` since really `=` is the thing to use there.

**Comment by josevalim** [comment]
> I’m 👍 on warning for pattern_that_matches_anything <- ... since really = is the thing to use there.

To be clear, this is not what this issue proposes! :D I think we can discuss it as well, but it is definitely a separate discussion.

**Comment by josevalim** [comment]
Closing in favor of PR, thanks!

**Comment by ericmj** [comment]
I believe this is a valid use case for a non-matching expression in `with` that now warns:

https://github.com/hexpm/diff/blob/master/lib/diff/storage/local.ex#L22

**Comment by wojtekmach** [comment]
Agreed, I'd say its a _matching_ expression so it should not warn!

**Comment by ericmj** [comment]
@wojtekmach Sorry, `master` branch changed so the link pointed to the wrong line. I updated it to point to correct commit.

**Comment by whatyouhide** [comment]
I was not entirely convinced with this either. Good find @ericmj.

**Comment by josevalim** [comment]
Here are other changes we had to do because of this change: https://github.com/elixir-ecto/postgrex/commit/92b996cce7d188d455e50296716615e82bc69d1e

I am ok with this change, but not very happy about it. It does remove false negatives but it definitely introduces false positives.
