### ISSUE TITLE
Logger truncate fails for multi-byte UTF-8 characters 

### ISSUE THREAD

**Issue by akash-akya** [elixir-lang/elixir#9766]
Logger incorrectly handles multi-byte UTF-8 characters

### Environment
Elixir 1.11.0-dev (b62a23d) (compiled with Erlang/OTP 22)

### Current behavior
```elixir
require Logger
Logger.configure(truncate: 15)
Logger.info("𠜎𠜱𠝹𠱓")
```
produces 
```
22:20:35.456 [info]  𠎜𠜱𠝹 (truncated)
```

### Expected behavior
```
22:20:35.456 [info]  𠜎𠜱𠝹 (truncated)
```

**Comment by josevalim** [comment]
Closing in favor of PR! Thanks!
