### ISSUE TITLE
Mix format on map keys nil/true/false mixed with non-atom keys

### ISSUE THREAD

**Issue by hypno2000** [elixir-lang/elixir#9771]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.10.0 (compiled with Erlang/OTP 22)

* Operating system:
MacOS Catalina, 10.15.2

### Current behavior
`mix format` will transform
```elixir
%{
  :nil => "foo",
  :false => "foo",
  :true => "foo",
  "bar" => "foo"
}
```
to:
```elixir
%{
  nil => "foo",
  false => "foo",
  true => "foo",
  "bar" => "foo"
}
```
and when running `mix format` again it will be formatted to:
```elixir
%{
  nil: "foo",
  false: "foo",
  true: "foo",
  "bar" => "foo"
}
```
The code above will not compile anymore: `syntax error before: "bar"`

### Expected behavior

1. Mix format should output final format on first run
2. The output of mix format should compile

**Comment by dhedlund** [comment]
A git bisect with a failing test suggests the issue was introduced by the "Add literal encoder option to Code.string_to_quoted" (f38895cebba0fa06f686e1dd9b74e5729aebcb45) commit.

**Comment by josevalim** [comment]
Thanks @dhedlund for the bisect. It was very helpful! I will push a fix soon!
