### ISSUE TITLE
Allow @requirements to be listed on Mix tasks

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9786]
Today, if you want to define and use a Mix task in your project itself, you need to make sure to call "compile" or "app.start" before. The issue with this approach is that, if you update the task itself, calling "compile" will re-compile the task but not update the version currently running.

In other words, this is not enough:

```elixir
defmodule Mix.Tasks.MyTask do
  use Mix.Task

  def run(argv) do
    Mix.Task.run("compile")
    # task code
  end
end
```

To fix it, you need to do:

```elixir
defmodule Mix.Tasks.MyTask do
  use Mix.Task

  def run(argv) do
    Mix.Task.run("compile")
    __MODULE__.compiled_run(args)
  end

  def compiled_run(args) do
    # task code
  end
end
```

To make this easier, my suggestion is to add a @requirements annotation of tasks that should be run before the current one. So the outcome is this:

```elixir
defmodule Mix.Tasks.MyTask do
  use Mix.Task

  @requirements "compile"
  # or: @requirements ["compile", "app.start"]

  def run(argv) do
    # task code
  end
end
```

It is a small amount of indirection but it will yield actual improvements to those writing their own tasks.

**Comment by smaximov** [comment]
> The issue with this approach is that, if you update the task itself, calling "compile" will re-compile the task but not update the version currently running

Oh, I shot myself in the foot because of this several times before, thank you for the workaround 👍 

> So the outcome is this

What if I want to run a mix task with arguments as a requirement, how would I be supposed to specify it? I see several options:

* `"compile --warnings-as-errors"` &mdash; need to split this string to separate task name from arguments, probably need to deal with shell quoting/escaping.
* `["compile", "--warnings-as-errors"]` &mdash; this would conflict with the suggested way of specifying multiple requirements.
* `{"compile", ["--warnings-as-errors"]}` &mdash; my favourite so far.

**Comment by wojtekmach** [comment]
> `"compile --warnings-as-errors"` — need to split this string to separate the task name from the arguments, probably need to deal with shell quoting/escaping while splitting too.

this syntax is the same as in aliases:

```elixir
defp aliases() do
  [
    test: ["compile --warnings-as-errors", "test"]
  ]
end
```

so that would be my first choice but option 4. sounds good to me too.

**Comment by smaximov** [comment]
> this syntax is the same as in aliases

Good point, I've looked up how Mix handles aliases and it uses `OptionParser.split/1` under the hood, so splitting is already covered. Given that, I now think it makes sense to use the first option too.

**Comment by whatyouhide** [comment]
I vote for option 1 too, I think it's the most intuitive since it's already present in the Elixir landscape. Thanks for bringing up those points @smaximov! 💟
