### ISSUE TITLE
Warn on unused variable in assert match

### ISSUE THREAD

**Issue by wojtekmach** [elixir-lang/elixir#9787]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Elixir 1.11.0-dev (a1c9115) (compiled with Erlang/OTP 22)`

### Current behavior

Currently, if the variable in match is not used we don't warn. For example here:

```elixir
test "foo" do
  value = "42"
  assert {:ok, value} = Ecto.Type.cast(value, :integer)
end
```

The intention was to write `assert {:ok, ^value} = ...` but due to mistake this test silently passes. 

If the intention was _not_ to match on that value, but use the value is used later in the test, we shouldn't warn.

### Expected behavior

Warn on unused variables in assert matches.

**Comment by ericmj** [comment]
IIRC this warning is suppressed on purpose because we don't want to add underscores to variables in assertion matches all the time.

**Comment by josevalim** [comment]
I actually think that we warned on it. Maybe the recent pattern matching diff removed the warning accidentally.

**Comment by whatyouhide** [comment]
I have been bitten by this multiple times. I also often find examples of this in codebases I work with, where I'm confused as to why a variable is underscored but then not used, only to figure out that it's just not used and this doesn't warn. I'm all for re-enabling the warning.

**Comment by wojtekmach** [comment]
I think I have a fix for it, stay tuned.
