### ISSUE TITLE
Bracket-based access documentation inconsistency with actual behaviour for keyword lists

### ISSUE THREAD

**Issue by Qqwy** [elixir-lang/elixir#9800]
### Current behavior

[The module documentation](https://hexdocs.pm/elixir/master/Access.html) of `Access`, currently states:

> Access supports keyword lists (Keyword) and maps (Map) out of the box. **The key can be of any type** and it returns nil if the key does not exist

Note that the emphasized part is not actually true: Elixir currently disallows you to use the Access functions on keyword lists that use non-atom keys:

```
iex> y = [a: 1, b: 2, c: 3]
iex> y[33]
** (ArgumentError) the Access calls for keywords expect the key to be an atom, got: 33
    (elixir) lib/access.ex:343: Access.get/3
```

### Expected behavior

The behavior of the documentation and the implementation should align.

Personally, I think that restricting keyword lists to only allow atoms as keys is a bad idea for two reasons:

- It forces a restriction on the datatype that Erlang does not.
- There are use-cases for keyword-lists with other types of keys (probably most notably integers and strings). When do you use a list over a map? When newer additions to the data structure should shadow earlier additions rather than replacing them.

So I'd be for changing the implementation to align with the current documentation.

The other way to solve this problem would of course be to change the documentation to align with the current implementation.

**Comment by josevalim** [comment]
I don't think we should break the keyword semantics - keys have to be atoms only. The docs have been updated, thanks!
