### ISSUE TITLE
MatchError in Task.Supervised.stream_monitor_loop/2

### ISSUE THREAD

**Issue by davidsulc** [elixir-lang/elixir#9803]
# Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 22 [erts-10.5.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.2 (compiled with Erlang/OTP 21)

* Operating system: 
Linux 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Current behavior

I'm performing tasks under a Task.Supervisor, and periodically get the following error:

```
18:53:18.996 [error] Process #PID<0.11235.55> raised an exception
** (MatchError) no match of right hand side value: nil
    (elixir) lib/task/supervised.ex:517: Task.Supervised.stream_monitor_loop/2
```

Per https://github.com/elixir-lang/elixir/blob/v1.9.2/lib/elixir/lib/task/supervised.ex#L516 it would appear that somehow the failing task doesn't exist among the list of running tasks. The same logic is  present on master: https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/task/supervised.ex#L543

I apologize for the poor bug report, but this is all the info I have (the error messages simply get dumped in IEx during execution). It's also possible I'm doing something improperly, although I wouldn't expect to be able to trigger an error within Elixir code.

Within the task, I'm doing some database updates with locking so it's very possible that tasks fail due to waiting too long on the DB. (Although no postgrex messages are displayed in IEx at the `info` logging level.)

### Expected behavior

Not triggering a match error within Elixir code and having access to the `DOWN` reason so the underlying issue within my code can be diagnosed.

**Comment by josevalim** [comment]
H @davidsulc! Thanks for the report. Can you please post all error messages printed? Without looking at the code and only at your description, I would guess that for some reason the task is being attempted for removal twice. If there are other error messages in the log, potentially associated to task exits, it will help us a lot.

**Comment by davidsulc** [comment]
Unfortunately, I don't have anything to give you... The logs basically look like:

```
15:24:20.469 [info] Starting partition ImgRetriever
15:28:07.822 [error] Process #PID<0.28865.0> raised an exception
** (MatchError) no match of right hand side value: nil
    (elixir) lib/task/supervised.ex:517: Task.Supervised.stream_monitor_loop/2
15:28:13.239 [error] Process #PID<0.29384.0> raised an exception
** (MatchError) no match of right hand side value: nil
    (elixir) lib/task/supervised.ex:517: Task.Supervised.stream_monitor_loop/2
15:28:57.793 [error] Process #PID<0.1972.1> raised an exception
** (MatchError) no match of right hand side value: nil
    (elixir) lib/task/supervised.ex:517: Task.Supervised.stream_monitor_loop/2
15:42:48.452 [error] Process #PID<0.29047.4> raised an exception
** (MatchError) no match of right hand side value: nil
    (elixir) lib/task/supervised.ex:517: Task.Supervised.stream_monitor_loop/2
15:45:36.063 [error] Process #PID<0.20955.5> raised an exception
** (MatchError) no match of right hand side value: nil
    (elixir) lib/task/supervised.ex:517: Task.Supervised.stream_monitor_loop/2
```

Where the first [info] line is an OTP app started on startup (i.e. the above is the beginning of the IEx session).
