### ISSUE TITLE
v1.10.1: variable named struct in either with or case causes unexpected compiler warning

### ISSUE THREAD

**Issue by ianrumford** [elixir-lang/elixir#9804]
### Environment

Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1]

Elixir 1.10.1 (compiled with Erlang/OTP 22)

Ubunti 18.04

### Current behaviour

A variable named struct in either with or case clauses causes an unexpected compiler warning saying the struct name var is unused:

```
defmodule A do
  defstruct foo: :bar
end
defmodule B do
  mod_a = A
  with %mod_a{} <- struct(mod_a) do
    true
  end
end
defmodule C do
  mod_a = A
  struct(mod_a)
  |> case do
       %mod_a{} -> true
     end
end
```

I get this:

> warning: variable "mod_a" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/test_with_struct_named1.ex:6: B

> warning: variable "mod_a" is unused (if the variable is not meant to be used, prefix it with an underscore)
  lib/test_with_struct_named1.ex:14: C

### Expected behaviour

Code should compile clean and not cause a warning.

Seems to be in same territory as  [#9801](https://github.com/elixir-lang/elixir/issues/9801)

**Comment by josevalim** [comment]
I believe these warnings are correct. Maybe you want to this instead:

```elixir
defmodule C do
  mod_a = A
  struct(mod_a)
  |> case do
       %^mod_a{} -> true
     end
end
```

**Comment by wojtekmach** [comment]
I'm not sure how this would read, but perhaps in cases like this the warning should mention that if you're trying to match against the value, do `^mod_a`.

**Comment by ianrumford** [comment]
Fair enough. 

I was taking my steer on syntax from the 1.3 release note comment but can see how the caret is needed.
