### ISSUE TITLE
iex doesn't reset terminal blocking flag when it exits

### ISSUE THREAD

**Issue by rlipscombe** [elixir-lang/elixir#9805]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Elixir 1.10.0 (compiled with Erlang/OTP 21)
```

* Operating system: Ubuntu 18.04.4

### Current behavior

```
$ iex -S mix
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

Compiling [...snip...]
Interactive Elixir (1.10.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
BREAK: (a)bort (c)ontinue (p)roc info (i)nfo (l)oaded
       (v)ersion (k)ill (D)b-tables (d)istribution
^C$ perl -MFcntl -e 'print(fcntl(STDIN, F_GETFL, 0) & O_NONBLOCK)'
2048$ 
```
(terminal's broken; "git add -p" and "apt-get install" both quit; see the explanation at https://askubuntu.com/questions/509852/why-does-apt-get-abort-by-itself-as-though-id-pressed-n/1206244#1206244)

### Expected behavior

```
$ perl -MFcntl -e 'print(fcntl(STDIN, F_GETFL, 0) & O_NONBLOCK)'
0
```

**Comment by josevalim** [comment]
Thanks for the report. Can you reproduce this issue using `erl` instead and also using Ctrl+C to exit?

**Comment by rlipscombe** [comment]
> Thanks for the report. Can you reproduce this issue using erl instead and also using Ctrl+C to exit?

Yes.

**Comment by josevalim** [comment]
So it is rather an Erlang bug, as we simply re-use their shell structure. Could you please report this in bugs.erlang.org? If you prefer I can also do it. Thanks!

**Comment by rlipscombe** [comment]
I'll do it; I'll post a link here when done.

**Comment by josevalim** [comment]
Thanks. Closing this as there is nothing we can act on.
