### ISSUE TITLE
Code.string_to_quoted regression elixir 1.10

### ISSUE THREAD

**Issue by k-cross** [elixir-lang/elixir#9812]
Version
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.10.1 (compiled with Erlang/OTP 22)
```

MacOS 10.15.3

I didn't quite have the proper context around this function and the changes to know if this was an intended breaking change or not but it does seem like a regression. The following snippet below once worked and now produces the following error.

```
iex(1)> Code.string_to_quoted(~s<value "#{format(:date, \"now\", \"{M}/{D}/{YYYY}\")}">)
** (SyntaxError) iex:1: unexpected token: "\" (column 49, code point U+005C)
```

Removing the backslashes fixes the issue. Sorry if this is garbage.

**Comment by josevalim** [comment]
Hi @k-cross ! So the issue is not related to string_to_quoted, but rather the string. Just this fails:

    ~s<value "#{format(:date, \"now\", \"{M}/{D}/{YYYY}\")}">

That's coming from inside the interpolation. Let's break it apart:

    formatted = format(:date, \"now\", \"{M}/{D}/{YYYY}\")
    ~s<value "#{formatted}">

As you can see, `\` is indeed invalid, because there is nothing to unescape. And this syntax has been invalid, most likely, since Elixir v1.0. Can you please double checked if you had this code as is working on previous versions? Thanks.

**Comment by k-cross** [comment]
@josevalim ahh, this is a bad case. Sorry I will try to find the case that worked in 1.7 and not on 1.10.

**Comment by k-cross** [comment]
Okay so I tracked this down to the `Macro.to_string` call that we make and it seems to have changed from elixir 1.9 to 1.10 as I did check that.

```
macro: {:value, [line: 1],
 [
   [
     {:@, [line: 1], [{:citizenshipStatus, [line: 1], nil}]},
     {:@, [line: 1], [{:expirationDate, [line: 1], nil}]}
   ],
   [
     do: [
       {:->, [line: 2], [[["citizen", {:_, [line: 2], nil}]], ""]},
       {:->, [line: 3], [[["noncitizen", {:_, [line: 3], nil}]], ""]},
       {:->, [line: 4], [[["permResident", {:_, [line: 4], nil}]], ""]},
       {:->, [line: 5], [[["authAlien", nil]], "N/A"]},
       {:->, [line: 6], [[["authAlien", ""]], "N/A"]},
       {:->, [line: 7],
        [
          [["authAlien", {:_, [line: 7], nil}]],
          {:<<>>, [line: 7],
           [
             {:"::", [line: 7],
              [
                {{:., [line: 7], [Kernel, :to_string]}, [line: 7],
                 [
                   {:format, [line: 7],
                    [
                      :date,
                      {:@, [line: 7], [{:expirationDate, [line: 7], nil}]},
                      "{M}/{D}/{YYYY}"
                    ]}
                 ]},
                {:binary, [line: 7], nil}
              ]}
           ]}
        ]}
     ]
   ]
 ]}

after macro: "value([@citizenshipStatus, @expirationDate]) do\n  [\"citizen\", _] ->\n    \"\"\n  [\"noncitizen\", _] ->\n    \"\"\n  [\"permResident\", _] ->\n    \"\"\n  [\"authAlien\", nil] ->\n    \"N/A\"\n  [\"authAlien\", \"\"] ->\n    \"N/A\"\n  [\"authAlien\", _] ->\n    \"\#{format(:date, @expirationDate, \\\"{M}/{D}/{YYYY}\\\")}\"\nend"

```

Here is the `inspect` of the quoted expression before the call and the string portion after the call.

Sorry if this is now expected behavior, but I didn't see it documented as a change.

**Comment by k-cross** [comment]
Ahh, this is still not the case...

**Comment by josevalim** [comment]
It is definitely a bug. I will push a fix shortly. Thanks for the report!

**Comment by k-cross** [comment]
Are there plans for a 1.10.2 version?
