### ISSUE TITLE
`elixir` command cannot read `/dev/*` files as an input file

### ISSUE THREAD

**Issue by hauleth** [elixir-lang/elixir#9813]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
  ```
  Erlang/OTP 22 [erts-10.5.5] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

  Elixir 1.10.0 (compiled with Erlang/OTP 22)
  ```
* Operating system: 
  ```
  Darwin NiunioBook-2.local 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,1 Darwin
  ```

### Current behavior

```sh
$ echo 'IO.puts "hello"' | elixir /dev/stdin
No file named /dev/stdin
```

The same happens for `/dev/fd/0`. These files are pipes that are equivalent to read from the standard input. This can be useful for running shell scripts quickly from the command line.

### Expected behavior

```sh
$ echo 'IO.puts "hello"' | elixir /dev/stdin
hello
```

**Comment by josevalim** [comment]
If someone wants to submit a pull request, then we will gladly review it and see if it makes sense to merge according to the code complexity, but it is not a feature it is currently in our roadmaps for now. Thanks!

**Comment by hauleth** [comment]
TBH I do not even know where to look for it, as it should be available "automatically" on POSIX systems. So if you would have some points where I can look then I would be happy.

**Comment by josevalim** [comment]
IIRC Erlang requires explicit commands or flags to read from pipes and it is only available inove recent versions.
