### ISSUE TITLE
dialyxir error on `EEx.eval_string()` in Elixir 1.10.1

### ISSUE THREAD

**Issue by garret-smith** [elixir-lang/elixir#9815]
* Operating system: Ubuntu linux, 19.10
* Works as expected: Erlang/OTP 22 [erts-10.6.4] / Elixir 1.9.4 (compiled with Erlang/OTP 20)
* Dialyxir fails: Erlang/OTP 22 [erts-10.6.4] / Elixir 1.10.1 (compiled with Erlang/OTP 22)

This code passes dialyxir in Elixir 1.9.4, but fails in 1.10.1

```
@spec hello() :: String.t()
def hello do
  EEx.eval_string("world")
end
```

The dialyxir error is:

```
lib/eex_dia.ex:17:invalid_contract
The @spec for the function does not match the success typing of the function.

Function:
EexDia.hello/0

Success typing:
@spec hello() :: atom() | [any()] | number() | {_, _, _, _}
```

**Comment by josevalim** [comment]
I believe your typespec is incorrect. :) Evaluating the string "world" won't return a string but, as a variable, it can return anything.  You should either say it returns `any()` or one of the suggested types by dialyzer.

**Comment by garret-smith** [comment]
My typespec is certainly more restrictive than necessary, but EEx.eval_string("world") does indeed return a String.  So at a minimum the success typing is overly restrictive.

```
 iex                                                                 ~/hw/helloworks [otp_elixir_1_10_upgrade|✚4…]
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Interactive Elixir (1.10.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> i EEx.eval_string("world")
Term
  "world"
Data type
  BitString
Byte size
  5
Description
  This is a string: a UTF-8 encoded binary. It's printed surrounded by
  "double quotes" because all UTF-8 encoded code points in it are printable.
Raw representation
  <<119, 111, 114, 108, 100>>
Reference modules
  String, :binary
Implemented protocols
  Collectable, IEx.Info, Inspect, List.Chars, String.Chars
iex(2)>
```

**Comment by josevalim** [comment]
Oh, good point: `EEx.eval_string` would only evaluate what is inside `<%= ... %>`, so passing a string returns itself. So I would expect dialyzer to be able to at least include binary in its return type but it doesn't. So it needs further investigation. We don't actually run Dialyzer ourselves, we use `@spec` mostly for docs, but if you find Elixir could be a better citizen here, a PR would be appreciated!

**Comment by garret-smith** [comment]
A PR is a bit beyond me at this point, but the value returned ultimately comes from this call to `erl_eval:expr()`: https://github.com/elixir-lang/elixir/blob/d490c1297db9526988fec0f3ff6be8eaf0e8bd47/lib/elixir/src/elixir.erl#L278

The relevant typespecs in the Elixir docs appear ok (`EEx.eval_string` `@spec` is `any()`, though I can't seem to get it to return anything but a `binary()`) but dialyzer is further restricting the return type for a reason I can't fathom.
