### ISSUE TITLE
Improve ExUnit expression diffing for tuples

### ISSUE THREAD

**Issue by arnodirlam** [elixir-lang/elixir#9824]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 1.10.0 and current master ([711f346](https://github.com/elixir-lang/elixir/commit/711f346a44900b99a0f9eead8caabbd778ca2046)), OTP 22.2.2
* Operating system: macOS High Sierra (10.13.6)

### Current behavior

A test asserting

```
assert {[], [], [], nil} = {[], nil}
```

yields the diff (-- means red, ++ means green)

```
     match (=) failed
     code:  assert {[], [], [], nil} = {[], nil}
     left:  {'', -[]-, -[]-, -nil-}
     right: {'', +nil+}
```

### Expected behavior

The diff should be (-- means red)

```
     match (=) failed
     code:  assert {[], [], [], nil} = {[], nil}
     left:  {[], -[]-, -[]-, nil}
     right: {[], nil}
```

1. I expected the empty lists to be displayed as empty list (not empty char lists)
2. I expected the diff to recognize the common last tuple element (`nil`), just like it does when diffing lists

I'll have a look and see whether I'll be able to create a fix this week😁

**Comment by josevalim** [comment]
Hi @arnodirlam! Thanks for the report!  :heart: I went ahead and pushed a fix because I am doing a new releasse tomorrow morning and I believe a fix for this should be included.

**Comment by josevalim** [comment]
Hi @arnodirlam! Thanks for the report!  :heart: I went ahead and pushed a fix because I am doing a new releasse tomorrow morning and I believe a fix for this should be included.

**Comment by arnodirlam** [comment]
Alright great! 👍 

Do you generally think it would be preferable to use the myers difference used when diffing matched lists also for diffing matched tuples?
