### ISSUE TITLE
MapSet is not a map, but it is

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9829]
### Environment

````
$ elixir --version
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
````

### Current behavior

The following results are "strange"

```
iex(28)> map_size(MapSet.new())
3
iex(29)> :erlang.map_size(MapSet.new())
3
```

### Expected behavior

At first sight I expected the previous expressions to raise something like `ArgumentError`.

The problem here is that `MapSet` is internally represented vai a map, and the dynamics of the language exposes it to all map-like functions, though semantically `MapSet` is not a map.

Perhaps it would be preferable to have `MapSet` implemented as a tuple (possibly a record), as it would perhaps be less confounded with `Map` (just a guess).

I think there is no perfect solution for this, so perhaps this issue is just a reminder of this behavior, and nothing can be done better.

**Comment by ericmj** [comment]
This is the case for all structs in Elixir. Changing it to a record would not help since `tuple_size(MapSet.new())` would work then instead.
