### ISSUE TITLE
mix release for Windows 10 has dependency towards "Visual C++ Redistributable Packages for Visual Studio 2013"

### ISSUE THREAD

**Issue by pickatag** [elixir-lang/elixir#9832]
### Environment
* Elixir & Erlang/OTP versions (elixir --version): Erlang/OTP 22 / Elixir 1.9.4
* Operating system: Windows 10 Pro / Version 1909 (clean install, no other applications)

### Current behavior
When producing a release with mix release and copying into a clean install of Windows 10, I get an error message from erl.exe (see attached picture).
![image](https://user-images.githubusercontent.com/31210931/75024319-7baebc80-5499-11ea-9dd3-3712733947a8.png)

### Expected behavior
This is due to a dependency from Erlang to "Visual C++ Redistributable Packages for Visual Studio 2013" (or Windows SDK), more info [here](http://erlang.org/documentation/doc-10.3/doc/installation_guide/INSTALL-WIN32.html).
As far as I can tell, Windows 10 out of the box does not have any VC++ files installed, and it must be added by the user.
mix release does not address this issue and maybe there should be some information in the documentation about this?
I will solve this by manually add the missing MS dll files in the erts-10.5\bin directory, but this is maybe not the correct approach from a mix release perspective.

**Comment by josevalim** [comment]
> mix release does not address this issue and maybe there should be some information in the documentation about this?

Agreed. Good catch, thank you!

I am not a Windows expert but at first it feels it would be better to have the SDK installed system wide, no? However, if you can get away with including the .DLLs inside the release, then please let us know and we will list that as an option. Or even better, if you could send a PR with your findings, we would appreciate it!

**Comment by pickatag** [comment]
Thanks for quick response.
I will create a PR for this in the release documentation...

**Comment by josevalim** [comment]
Ping! :)

**Comment by pickatag** [comment]
Pong! :)
