### ISSUE TITLE
Wrong line is reported on error message when get_in is used

### ISSUE THREAD

**Issue by eniolopes** [elixir-lang/elixir#9833]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.1 (compiled with Erlang/OTP 21)

* Operating system: Ubuntu 18.04

### Current behavior

```elixir
a = get_in(%{}, [:v])
10 / a
```
```
** (ArithmeticError) bad argument in arithmetic expression
    test.exs:1: (file)
    (elixir 1.10.1) lib/code.ex:917: Code.require_file/2
```
### Expected behavior

The error message should've said that the exception happened on line 2.

**Comment by michalmuskala** [comment]
This issue exists in Erlang. In the following module, when calling `test:test()`, the error is reported on line 6 instead of 7:
```erlang
-module(test).

-export([test/0]).

test() ->
    A = maps:find(v, #{}),
    10 / A.
```

**Comment by josevalim** [comment]
Can someone please report this bug upstream then on bugs.erlang.org?

**Comment by michalmuskala** [comment]
Reported as https://bugs.erlang.org/browse/ERL-1178

**Comment by josevalim** [comment]
Thanks!
