### ISSUE TITLE
Documentation incorrect for adding a new :logger handler

### ISSUE THREAD

**Issue by Shayon** [elixir-lang/elixir#9841]
https://github.com/elixir-lang/elixir/blob/51c95b60004d3d9d297fff23f576bdd97c931afd/lib/logger/lib/logger.ex#L471

The line should instead be: `[{:handler, :name_of_the_handler, ACustomHandler, configuration = %{}}]` Note the added tuple.

**Comment by josevalim** [comment]
Fantastic! Can you please send a PR?

**Comment by Shayon** [comment]
My mistake looks like in master it's been fixed for 16 days.  I was looking off the commit for the latest release.
