### ISSUE TITLE
File module rename tests don't cope with behaviour difference on PASE

### ISSUE THREAD

**Issue by NattyNarwhal** [elixir-lang/elixir#9858]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]` `Elixir 1.11.0-dev (18bf816) (compiled with Erlang/OTP 22)` (but reproducible on v1.10.x)

* Operating system: IBM i 7.2

### Current behavior

```
  1) test rename parent dir to existing sub dir (FileTest.Rename)
     test/elixir/file_test.exs:242
     Assertion with == failed
     code:  assert File.rename(src, dest) == {:error, :einval}
     left:  {:error, :eexist}
     right: {:error, :einval}
     stacktrace:
       test/elixir/file_test.exs:248: (test)



  2) test rename file to existing non-empty dir (FileTest.Rename)
     test/elixir/file_test.exs:82
     Assertion with == failed
     code:  assert File.rename(src, dest) == {:error, :eisdir}
     left:  {:error, :eexist}
     right: {:error, :eisdir}
     stacktrace:
       test/elixir/file_test.exs:88: (test)

.......................................................................................................

Finished in 145.9 seconds (82.9s on load, 63.0s on tests)
1584 doctests, 3460 tests, 2 failures, 8 excluded
```

### Expected behavior

These tests should pass. (I don't know if this should be handled by the tests/consuming applications, the Elixir stdlib, or OTP...) My guess is to what's happening is that the AIX compatibility layer (PASE) on i (which BEAM is running on) is thinly wrapping the native environment's version of the rename call, which has [slightly different behaviour](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apis/renameun.htm).

Side note: Overall, I'm actually impressed with how well Elixir works on this platform. I'm actually using it to develop a simple application against the native database on the platform (via ODBC) and its going surprisingly well. The platform tests passing has been quite pleasant for me, since I'm using used to seeing red or not even being able to think of exotic languages on minority platforms...

**Comment by josevalim** [comment]
We could rewrite it but I think hiding the system call return value can be seen as an issue in some places. So I would rather change the tests to do this instead:

    assert File.rename(src, dest) in [{:error, :eisdir}, {:error, :eexist}]

What do you think? Could you please send a PR?

**Comment by NattyNarwhal** [comment]
That fixes it and lets the test suite run further, until it stops again at building releases for mix projects. 

```
warning: redefining module ReleaseTest.MixProject (current version defined in memory)
  /home/calvin/src/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test runs in daemon mode/mix.exs:1

warning: redefining module ReleaseTest (current version loaded from /home/calvin/src/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test assembles a bootable release without distribution/_build/dev/lib/release_test/ebin/Elixir.ReleaseTest.beam)
  lib/release_test.ex:1

/home/calvin/src/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTest/test runs in daemon mode/_build/dev/rel/permanent2/bin/permanent2[9]: 0403-057 Syntax error at line 38 : `>' is not expected.


  9) test runs in daemon mode (Mix.Tasks.ReleaseTest)
     /home/calvin/src/elixir/lib/mix/test/mix/tasks/release_test.exs:596
     ** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:

       1. per test by setting "@tag timeout: x" (accepts :infinity)
       2. per test module by setting "@moduletag timeout: x" (accepts :infinity)
       3. globally via "ExUnit.start(timeout: x)" configuration
       4. by running "mix test --timeout x" which sets timeout
       5. or by running "mix test --trace" which sets timeout to infinity
          (useful when using IEx.pry/0)

     where "x" is the timeout given as integer in milliseconds (defaults to 60_000).

     stacktrace:
       (stdlib 3.11) gen.erl:167: :gen.do_call/4
       (stdlib 3.11) gen_server.erl:219: :gen_server.call/3
       (kernel 6.5.1) file.erl:1495: :file.call/2
       test/mix/tasks/release_test.exs:665: anonymous fn/1 in Mix.Tasks.ReleaseTest.wait_until_decoded/1
       test/mix/tasks/release_test.exs:673: Mix.Tasks.ReleaseTest.wait_until/1
       test/mix/tasks/release_test.exs:622: anonymous fn/1 in Mix.Tasks.ReleaseTest."test runs in daemon mode"/1
       (mix 1.11.0-dev) lib/mix/project.ex:352: Mix.Project.in_project/4
       (elixir 1.11.0-dev) lib/file.ex:1544: File.cd!/2
       test/test_helper.exs:122: MixTest.Case.in_fixture/3
       test/mix/tasks/release_test.exs:597: (test)
       (ex_unit 1.11.0-dev) lib/ex_unit/runner.ex:355: ExUnit.Runner.exec_test/1
       (stdlib 3.11) timer.erl:166: :timer.tc/1
       (ex_unit 1.11.0-dev) lib/ex_unit/runner.ex:306: anonymous fn/4 in ExUnit.Runner.spawn_test_monitor/4
```

Line: `      echo "ERROR: Expected sname, name, or none in RELEASE_DISTRIBUTION, got: $RELEASE_DISTRIBUTION" >&2`

I think this is due to `/bin/sh` not supporting bashisms. I'll try to verify this.

**Comment by josevalim** [comment]
> That fixes it and lets the test suite run further

FWIW, I would say that would be enough for an initial PR. :)

> I think this is due to /bin/sh not supporting bashisms. I'll try to verify this.

FYI, we verify our scripts with shellcheck, which detects bashisms, and we also run it on Ubuntu and FreeBDS and MacOS, which all provide different shells. So it may be something else... but it may still be a bashism. :)

**Comment by NattyNarwhal** [comment]
yup, all tests pass if I make the mix release init task use bash instead. I'll file a PR for the test fix, at least.

```diff
diff --git a/lib/mix/lib/mix/tasks/release.init.ex b/lib/mix/lib/mix/tasks/release.init.ex
index bb4d30b..667288b 100644
--- a/lib/mix/lib/mix/tasks/release.init.ex
+++ b/lib/mix/lib/mix/tasks/release.init.ex
@@ -57,7 +57,7 @@ defmodule Mix.Tasks.Release.Init do
   @doc false
   def env_text,
     do: ~S"""
-    #!/bin/sh
+    #!/usr/bin/env sh
 
     # Sets and enables heart (recommended only in daemon mode)
     # case $RELEASE_COMMAND in
@@ -80,7 +80,7 @@ defmodule Mix.Tasks.Release.Init do
   @doc false
   def cli_text,
     do: ~S"""
-    #!/bin/sh
+    #!/usr/bin/env bash
     set -e
 
     SELF=$(readlink "$0" || true)
```

**Comment by josevalim** [comment]
If you use `#!/usr/bin/env sh` instead of `#!/usr/bin/env bash` on the second one, is it not enough?

**Comment by NattyNarwhal** [comment]
Nope, breaks if I use sh. I suspect the AIX bourne shell is extremely conservative. ksh didn't like it either, so I suspect a bashism... (I also suspect the releases generated might not be portable because of how aggressive rpath can be on AIX, but that's another issue...)

**Comment by josevalim** [comment]
ksh is available on Mac. I can give it a try later! You can also try it yourself by doing this:

    bin/mix new demo
    cd demo
    mix release

Then follow the instructions to start it and see if you run into any issues. Running it directly may be easier to debug than through tests.

**Comment by NattyNarwhal** [comment]
Yeah, running it directly confirms that with `/bin/sh` I get the error, and making it use bash is fine. Even the release works, though I suspect that's because the rpath is making it pick up the system BEAM, but I haven't measured that yet.

**Comment by josevalim** [comment]
@NattyNarwhal for what is worth, I installed `ksh` locally and made all scripts use it instead of sh, and all tests passed. So this seems to be something specific to PASE (or ksh on PASE) rather than only ksh itself. :)

**Comment by NattyNarwhal** [comment]
Yeah, it's the crumbly AIX `/bin/sh`. I guess they don't handle POSIX as well as I thought :grimacing:

**Comment by OvermindDL1** [comment]
Specifically there are different versions of ksh, ksh89 I think is on AIX, where MAC's have a significantly more updated one.  ksh98 is actually quite posix compliant as I recall.
