### ISSUE TITLE
Warning as errors do not work for warnings emitted from application tracer

### ISSUE THREAD

**Issue by josevalim** [elixir-lang/elixir#9861]
See https://github.com/elixir-lang/elixir/issues/9407#issuecomment-592650008.

We could move the handling of warnings as errors to Mix and outside of the Elixir compiler but by then the compiler would already persist the files to disk. We will most likely need to introduce or change a new callback in the compiler.

**Comment by michallepicki** [comment]
confirming fixed :100:
