### ISSUE TITLE
Erlang download

### ISSUE THREAD

**Issue by cup** [elixir-lang/elixir#9863]
I am interested in trying Elixir, so I saw this:

> The only prerequisite for Elixir is Erlang, version 21.0 or later, which can
> be easily installed with Precompiled packages. 

<https://elixir-lang.org/install#installing-erlang>

Which links to the Erlang page, but it seems no downloads are available:

> Download Erlang Packages
>
> Hey, we are currently working on this page to make all packages easily
> downloadable to you on desktop; in the meantime you can contact us directly
> at general@erlang-solutions.com with any questions, or subscribe to our
> Erlang & Elixir Newsletter.

<https://erlang-solutions.com/resources/download.html>

Can I download Erlang somewhere else?

**Comment by cup** [comment]
Workaround, looks like some downloads here:

https://erlang.org/downloads

**Comment by josevalim** [comment]
Hi @cup! most of the installation methods for Elixir just go ahead and install Erlang, so you can generally skip that section. However, your proposed link also works, so I will go ahead with it.

**Comment by josevalim** [comment]
Links clarified, thank you!
