### ISSUE TITLE
some platforms have a deficient /bin/sh that prevents mix releases from working

### ISSUE THREAD

**Issue by NattyNarwhal** [elixir-lang/elixir#9870]
Split from #9858.

### Environment

* Elixir & Erlang/OTP versions (elixir --version): `Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1]` `Elixir 1.10.0 (compiled with Erlang/OTP 22)`
* Operating system: IBM i 7.2 (reproducible on AIX, since PASE is a subset environment of)

### Current behavior

`_build/dev/rel/testapp/bin/testapp[9]: 0403-057 Syntax error at line 38 : `>' is not expected.`

### Expected behavior

The release script to function.

Problematic line: `      echo "ERROR: Expected sname, name, or none in RELEASE_DISTRIBUTION, got: $RELEASE_DISTRIBUTION" >&2`

Using each built-in shell on PASE (subset of AIX; ignoring external packages like bash):

```
$ bsh _build/dev/rel/testapp/bin/testapp # Bourne shell
_build/dev/rel/testapp/bin/testapp: Syntax error at line 4: `SELF=$' not expected.
$ ksh _build/dev/rel/testapp/bin/testapp # Korn shell
_build/dev/rel/testapp/bin/testapp[9]: 0403-057 Syntax error at line 38 : `>' is not expected.
$ ksh93 _build/dev/rel/testapp/bin/testapp # Korn shell '93
Usage: testapp COMMAND [ARGS]
```

Not sure if it'd be wise to have different shells per supported platform?

**Comment by OvermindDL1** [comment]
Best thing would be to drop down to pure posix.  Right now `/bin/sh` on most systems has more features than posix requires, where the old ksh89/93 shells are fully posix compliant as I recall (but with their own extra features as well of course).  I think there is a posix `sh` validator online somewhere if someone could find it?

**Comment by josevalim** [comment]
I would like to support it but to be honest, I am not sure how feasible it is. We already test on FreeBSD, Ubuntu, Windows, and MacOS. We also run shellcheck which verifies for POSIX compliance (or at least against bashisms). So unless someone can setup a CI that allows us to test and run things on proprietary systems like AIX, there is very little that the Elixir team itself can do.

**Comment by josevalim** [comment]
Also, to add, everything works fine on more recent versions of `ksh` after some local testing.

**Comment by OvermindDL1** [comment]
I think it was ksh98 that started adding a lot of bashisms for compatibility.

**Comment by josevalim** [comment]
Hi everyone, I will go ahead and close this. We will be glad to reopen if someone sends a pull request or if someone provides an automated mechanism for us to reach out to those proprietary platforms. Thanks!

**Comment by eksperimental** [comment]
> I would like to support it but to be honest, I am not sure how feasible it is. We already test on FreeBSD, Ubuntu, Windows, and MacOS. We also run shellcheck which verifies for POSIX compliance (or at least against bashisms). So unless someone can setup a CI that allows us to test and run things on proprietary systems like AIX, there is very little that the Elixir team itself can do.

@josevalim I think something that we are missing is testing the shell bin commands in the different platforms. If you have any idea on what and how should be done, I may be able to start working on it.
