### ISSUE TITLE
Typespec Compiler error  type t/0 undefined 

### ISSUE THREAD

**Issue by anildigital** [elixir-lang/elixir#9875]
### Environment

* Elixir & Erlang/OTP versions : Elixir 1.10.0 / Elixir 1.10.2 (compiled with Erlang/OTP 22
* Operating system: macOS Catalina

### Current behavior

** (CompileError) lib/db/governance.ex:34: type t/0 undefined (no such type in AB.Core.Db.Governance)

Here is governance.ex https://gist.github.com/anildigital/d25852aa46a2b9c1c59c016057984a09

### Expected behavior

Elixir 1.10 should not raise any compiler error for this.

Ref
https://github.com/elixir-lang/elixir/blob/v1.10.2/lib/elixir/lib/kernel/typespec.ex#L678
https://github.com/elixir-lang/elixir/commit/a7150c1f1c2d9b56ba57495076f126f59e0374da

**Comment by wojtekmach** [comment]
This is not a bug, the `t()` was never automatically defined for you, just the compiler got recently better at catching this. See e.g.: https://github.com/elixir-ecto/ecto/issues/3237#issuecomment-589992045 for similar report.
