### ISSUE TITLE
Warning not to have multiple doc(test)s for the same function/arity

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [elixir-lang/elixir#9883]
### Environment
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.2 (compiled with Erlang/OTP 21)
Ubuntu 18.04.4 LTS
```

### Current behavior
```elixir
@doc ~S"""
iex> MyModule.foo(:bar)
:qux
"""
def foo(:bar), do: :bar

@doc ~S"""
iex> MyModule.foo(:qux)
:qux
"""
def foo(:qux), do: :qux
```
```
$ mix test test/my_module_test.exs
1 doctest, 0 failures
```

### Expected behavior
```
     Doctest failed
     doctest:
       iex> MyModule.foo(:bar)
       :qux
     code:  MyModule.foo(:bar) === :qux
     left:  :bar
     right: :qux

2 doctests, 1 failure
```

It turns out you can't have multiple `@doc` annotations for the same function/arity.
`:code.get_object_code/1` will only return the last one (overwriting the previous docs).
I didn't know that and it confused me a lot because many of my tests weren't being executed.
Maybe the docs could have a warning about this.

**Comment by elridion** [comment]
I'm not sure if my proposal is in line what you had in mind, I'm open for advice.
Also the introduced warning breaks the builds since it is emitted during compilation.

**Comment by i-n-g-m-a-r** [comment]
I can't give an informed opinion on how to approach this issue.
It seems to me that such a warning at compile time would help a lot.
Also to mention the limitation in howto's regarding `@doc` would be great.
Maybe it's even possible to solve the issue by not overwriting documentation.

**Comment by elridion** [comment]
Thanks, so as of now the builds succeed.
Overwriting the documentation will yield an warning.
```elixir
defmodule Foo do
  @doc ~S"""
  iex> MyModule.foo(:bar)
  :qux
  """
  def foo(:bar), do: :bar

  @doc ~S"""
  iex> MyModule.foo(:qux)
  :qux
  """
  def foo(:qux), do: :qux
end
```

```
warning: @doc attribute will override the documentation and test previously defined in line 2
  .iex.exs:8: Foo.foo/1
```
