### ISSUE TITLE
`M.f` and `M.f/a` disappeared from `mix xref callers` in 1.10.x

### ISSUE THREAD

**Issue by wrachwal** [elixir-lang/elixir#9887]
On `v1.10` branch `mix xref callers` has only one option with module (`M`). Present yet in `1.9.4` there were `M.f` and `M.f/a`. The functionality could have been removed under the commit:
```
* 1956e9580 2019-07-18  Remove dispatch tracking in LexicalTracker (#9228)
```
I could not find any remark of the removal (or deprecation) in the CHANGELOG.md

Removed options were very useful, e.g. to answer questions like "whether and how often is my API used in that (alien) project which uses my app as dependency". The same answer on module level is too broad, simply useless.

**Comment by josevalim** [comment]
We will update the CHANGELOG. Mix no longer keeps a database of all calls but we provide the tools, via Compilations Tracers, for someone to build one (and do even more powerful things with it). I believe `boundary` is building a database, maybe they want to provide similar tasks. /cc @sasa1977

**Comment by sasa1977** [comment]
Boundary stores remote calls of the current project except for calls to some "system apps" (e.g. stdlib, kernel, elixir), calls to preloaded modules, and calls to erlang modules (this last part will probably change at some point).

So it seems that we have enough data stored to support such mix task. The downside is that you'd have to define boundaries in your project, although we could make an opt-out switch for that, so you can use boundary only for the purpose of recording the calls and analyzing module dependencies without the need to define any boundaries. @wrachwal, if you're interested in this, you can open up the issue on the [project repo](https://github.com/sasa1977/boundary) and we can take it from there.
