### ISSUE TITLE
Warning checker runs on every line when pasted into REPL

### ISSUE THREAD

**Issue by vans163** [elixir-lang/elixir#9892]
OTP22 Elixir 1.9.1

When you paste code into REPL it runs the warning checker on every line.

```
defmodule Test do
    def trigger() do
        atom = :"its_quoted"
        atom = :"its_quoted2"
    end

    def keep_triggering() do
        "The warning above will trigger on every evaluated line"
    end
end
```

**Comment by josevalim** [comment]
@vans163 thanks. The tokenizer attempts to parse the expression line by line, until it is complete, which causes the multiple warnings. We have two options to fix this:

1. Collect the warnings and emit the warnings only at the end if tokenizing suceeds

2. Make the tokenizer reentrant, so we stop parsing things multiple times

**Comment by vans163** [comment]
As long as it does not lock anything up I think either is fine? Like output to stdout.

**Comment by pablocostass** [comment]
> 1. Collect the warnings and emit the warnings only at the end if tokenizing suceeds

Hey @josevalim, is it okay if I do a PR with the first option as a fix? Also, would it be okay to simply store said warnings in the process dictionary and in case of tokenizing success emit their warnings?

**Comment by josevalim** [comment]
@pablocostass there is no need to use the process dictionary I think. The tokenizer has a state to pass around and we could create a "warnings" field in there. Then return the value of this field at the end of tokenization. Perhaps a first step would be to collect and return those warnings, while still emitting them, and then at the end we move the emitting of them elsewhere. and yes, a PR would be welcome! :)
