### ISSUE TITLE
Dynamic Supervisor shutdown before mix tests finished

### ISSUE THREAD

**Issue by farao** [elixir-lang/elixir#9904]
I refactored my Application to use a DynamicSupervisor as proposed by the documentation:

```
def start(_,_) do
  children = [{DynamicSupervisor, name: MySupervisor, strategy: :one_for_one},...]
  Supervisor.start_link(children, strategy: :one_for_one)
end
```

In my tests, I since then have a race condition, in which sometimes all tests succeed and sometimes the last test doesn't because the DynamicSupervisor was already shut down:
```
     ** (exit) exited in: GenServer.call(MySupervisor, {:start_child, {{MyProcess, :start_link, [["..."]]}, :permanent, 5000, :worker, [MyProcess]}}, :infinity)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```
When verifying with a Process.monitor on MySupervisor + receive in a separate process, I get a:
```
{:DOWN, #Reference<0.2010477200.3125018627.140701>, :process,
 {MySupervisor, :nonode@nohost}, :shutdown}
```
before the red dot of the last test in the cases when it fails and after all green dots in case everything succeeds.

This tells me, that the dynamic supervisor is already shut down before the last test - how can this happen? I guess this is a bug?

**Comment by josevalim** [comment]
Hi @farao, it is best to use mediums such as the ElixirForum for general help and discussions. Once you can boil this down to a smaller application that can consistently reproduce the error, then you can open up a bug report. The reason for this is that the community is large and if it depends on us to investigate all potential issues, then we wouldn't have time to actually fix them.

In your case, I would recommend looking at the max_restarts an max_seconds of your supervisor. My hunch is that the supervisor children is failing, leading it to restart. Or something is explicitly shutting own the app.

Thanks.
