### ISSUE TITLE
Only allowing a single config/relase.exs file causes issues for umbrella project with multiple releases defined

### ISSUE THREAD

**Issue by midas** [elixir-lang/elixir#9911]
### Environment

* Elixir 1.10.2
* Erlang 22.3
* Operating system: Fedora 31

### Current behavior

Due to only the `config/releases.exs` file being copied into the current release, an umbrella project with many releases defined cannot have a unique `releases.exs` file per defined release.

### Expected behavior

I would expect a mechanism that allows a releases file per release to be specified.  I see there is a `:runtime_config_path` option but it will not work as it applies to all defined releases per the documentation:

>The following options can be set inside your releases key in your mix.exs to control how runtime configuration and config providers work:

Thank you in advance for your consideration of this issue!

**Comment by josevalim** [comment]
`runtime_release_path` can be set per release:

```elixir
    releases: [
      foo: [runtime_release_path: ...],
      bar: [runtime_release_path: ...],
   ]
```

I will improve the docs.
