### ISSUE TITLE
tuple_size/1 still emits an errorneous warning

### ISSUE THREAD

**Issue by ityonemo** [elixir-lang/elixir#9917]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.10.1 (compiled with Erlang/OTP 21)
```
* Operating system: 
- Linux Mint (Ubuntu-Bionic ish)

### Current behavior

Compiler incorrectly warns on tuple_size/1 guard, emitting the following warning:
```
warning: this expression will fail with ArgumentError
```
sample repo:

https://github.com/ityonemo/guard_warning

Can be triggered by running `mix test`.

Relevant code:
```
defmodule GuardWarning do
  defguard foo(tup) when is_tuple(tup) and tuple_size(tup) == 4
end
```

```
defmodule GuardWarningTest do
  use ExUnit.Case

  require GuardWarning

  test "guard guards" do
    refute GuardWarning.foo(:bar)   # warning points to this line
    IO.inspect GuardWarning.foo(:bar) 
  end
end
```

This is a low severity issue, but does prevent me from using warnings as errors in CI.

### Expected behavior

No warning should be emitted.  (Tests pass as expected).

### Related Issues
appears to be the same problem as https://github.com/elixir-lang/elixir/issues/6632

**Comment by josevalim** [comment]
This is an Erlang bug which has been reported and I can verify it has been fixed in Erlang/OTP 23-rc.2. :) Maybe it has been fixed in earlier versions too.

**Comment by josevalim** [comment]
Btw, thanks for the app that reproduces it, it is always helpful!

**Comment by ityonemo** [comment]
thanks!  I think there's also a similar problem with `:erlang.map_get/2`, would you like for me to update the example repo for verification that it's been resolved in OTP23?
