### ISSUE TITLE
Confusing ExUnit diff for pinned decimal

### ISSUE THREAD

**Issue by i-n-g-m-a-r** [elixir-lang/elixir#9923]
### Environment
Erlang/OTP 22 [erts-10.7] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.2 (compiled with Erlang/OTP 21)
Ubuntu 18.04.4 LTS

### Current behavior
```elixir
a = Decimal.new("3.95")
b = Decimal.new("2.50")

assert %{a: ^a, b: ^b} = %{a: a, b: a}
```
![pinned_decimals](https://user-images.githubusercontent.com/5416491/78639471-4fff5e80-78ae-11ea-9ed0-703f251b2814.png)

### Expected behavior
Field `:a` should not be highlighted.

**Comment by josevalim** [comment]
This has been fixed in master, thanks! Dup of #9872.
