### ISSUE TITLE
Syntax error reported for quoted atom function name

### ISSUE THREAD

**Issue by kipcole9** [elixir-lang/elixir#9940]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.10.2; Erlang 22.3.1
* Operating system: macOS Catalina

### Current behavior

A valid atom function name causes a syntax error but passes if unquoted into the function definition.

```elixir
defmodule FunTest do

  fun = quote do
    :"$handle_undefined_function"
  end

  # No error reported here
  def unquote(fun)(func, args) do
    apply(Calendar.Gregorian, func, args)
  end

  # Error reported on the following line:
  def :"$handle_undefined_function"(func, args) do
    apply(Calendar.Gregorian, func, args)
  end

end

== Compilation error in file lib/fun_test.ex ==
** (SyntaxError) lib/fun_test.ex:11: syntax error before: '('
```

### Expected behavior

Valid atom name is acceptable as a function name,

**Comment by josevalim** [comment]
Yes, this is by design. We don't want to allow weird function names to be easily defined, so you need to go the unquote route. Consider this a warning to not use `"$handle_undefined_function"`. :) Thanks!

**Comment by kipcole9** [comment]
:-) I have no plans to ever use it; just happened to be experimenting. Thanks for the explanation.
