### ISSUE TITLE
Nested lists inside documentation are not working as expected

### ISSUE THREAD

**Issue by mguimas** [elixir-lang/elixir#9941]
### Environment

```
$ elixir --version
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.9.4 (compiled with Erlang/OTP 22)
```
### Current behavior

Writting this inside a `@moduledoc`

```
defmodule X do
  @moduledoc """
  * level 1
    * level 2
      * level 3
        * level 4
          * level 5
            * level 6
  """
end
```

which is valid Markdown (as referenced in the links given [here](https://hexdocs.pm/elixir/writing-documentation.html)), does not generate the expected nesting levels:

```
iex(2)> h X
                                       X
  • level 1
    • level 2
    • level 3
      • level 4
      • level 5
      • level 6
```

### Expected behavior

Generate the six nesting levels. I did not test if this is happening inside `@doc` too.

**Comment by sushant12** [comment]
@josevalim  I am looking into this issue and working on a PR.

I made a change in my fork and it worked for the case mentioned above but it broke other tests for such list

https://github.com/sushant12/elixir/commit/fda2915c84c85d2326045a729093340fa9d2fc44

I am still looking into it when I am free

**Comment by josevalim** [comment]
@sushant12 yes, your fix is incorrect because it is always nesting now. You can add a test with this list as a more complete example:

```
  @moduledoc """
  * level 1
    * level 2a
    * level 2b
      * level 3
        * level 4a
        * level 4b
          * level 5
            * level 6
  """
