### ISSUE TITLE
Mix release tar path incorrect

### ISSUE THREAD

**Issue by nasdf** [elixir-lang/elixir#9949]
### Environment

```
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.2 (compiled with Erlang/OTP 22)
```

### Current behavior

The tar is put into `../../` relative to the path option.

```
$ cd /Projects/app
$ mix release --path tmp
...
* building /Projects/app-0.1.0.tar.gz
```

### Expected behavior

The tar should be put into the path option directory.

```
$ cd /Projects/app
$ mix release --path tmp
...
* building /Projects/app/tmp/app-0.1.0.tar.gz
```

**Comment by wojtekmach** [comment]
Good find.

We're doing:

```elixir
tar_filename = "#{release.name}-#{release.version}.tar.gz"
out_path = Path.join([release.path, "..", "..", tar_filename]) |> Path.expand()
```

which makes sense for the default `:path` being `"_build/MIX_ENV/rel/RELEASE_NAME"`, we then end up with the default tar path: `_build/MIX_ENV/RELEASE_NAME-RELEASE_VSN.tar.gz`.

But I agree the current behaviour is confusing. Perhaps a solution would be to allow passing `:tar_path` with the following behaviour?

```
    * `:tar_path` - the path the release tarball should be created at.
      If `:path` is set, defaults to `PATH/RELEASE_NAME-RELEASE_VSN.tar.gz`,
      otherwise to: `_build/MIX_ENV/rel/RELEASE_NAME-RELEASE_VSN.tar.gz`.
```
