### ISSUE TITLE
mix install local.hex - error: ** (Mix) The task "install" could not be found

### ISSUE THREAD

**Issue by ORESoftware** [elixir-lang/elixir#9951]
So I am new to mix/elixir, I am following the directions here:
https://medium.com/@ctbuchan1/phoenix-reasonreact-full-stack-functional-programming-15ab9ae8fe67

I just ran this:

```shell
mix install local.hex
```

and I got this :(

```shell
** (Mix) The task "install" could not be found
```

wtf, FML :(

```bash
 mix --version
```

yields:

```
Erlang/OTP 20 [erts-9.3.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]

Mix 1.6.6 (compiled with OTP 19)
```

not sure what's up but I don't like it lol fml

**Comment by kipcole9** [comment]
Often a good idea to first consult the [Elixir slack](https://elixir-lang.slack.com), or the [forum](https://elixiforum.com). It seems the instructions on that blog post are incorrect - maybe check the [official guide](https://elixir-lang.org/install.html)?

In short, use `mix local.hex`. If you run `mix help` it will show you what tasks are available. There is no task `install`.

**Comment by ORESoftware** [comment]
ok ty
