### ISSUE TITLE
String.equivalent?/2 with specific unprintable characters runs for a long time

### ISSUE THREAD

**Issue by vertexarray** [elixir-lang/elixir#9957]
### Environment

* Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
* Elixir 1.10.2 (compiled with Erlang/OTP 21)
* Operating system: OSX Catalina 10.15.3 (19D76)

### Current behavior

String.equivalent?(<<15, 206>>, <<15, 206>>) ran for at least a minute when running in iex. Never saw it complete.

### Expected behavior

String.equivalent?/2 should error if those parameters are somehow invalid, or ideally return true.

**Comment by fertapric** [comment]
`:unicode.characters_to_nfd_binary(<<206>>)` is returning `{:error, "", <<206>>}` causing an infinite loop here https://github.com/elixir-lang/elixir/blob/v1.10.2/lib/elixir/lib/string.ex#L684

**Comment by josevalim** [comment]
Fixed on master and v1.10 with 9b5cafe72a407f3bb3175fbe150ca8c2264dbfe9. Thanks!
