### ISSUE TITLE
Option :static_atoms_encoder in Code.string_to_quoted/2 causes syntax errors

### ISSUE THREAD

**Issue by gVirtu** [elixir-lang/elixir#9996]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.9.2 (compiled with Erlang/OTP 21)
```
* Operating system: 
```
Ubuntu 16.04
```

### Current behavior

The [docs](https://hexdocs.pm/elixir/1.9.0/Code.html#string_to_quoted/2-the-static_atom_encoder-function) mention the encoder will **not** be invoked for syntax keyword atoms such as `fn`. However, using the encoder below shows that `fn` and `end` actually do get picked up, causing a syntax error.

```elixir
iex(1)> code = "fn a -> a end"
iex(2)> encoder = fn atom, _opts -> {:ok, IO.inspect(atom)} end
iex(3)> Code.string_to_quoted(code, static_atoms_encoder: encoder)
"fn"
"a"
"a"
"end"
{:error, {1, "syntax error before: ", "'->'"}}
```

### Expected behavior

In the scenario above, I'd expect the following return:

```elixir
iex(3)> Code.string_to_quoted(code, static_atoms_encoder: encoder) 
{:ok,
 {:fn, [line: 1],
  [{:->, [line: 1], [[{"a", [line: 1], nil}], {"a", [line: 1], nil}]}]}}
```

**Comment by josevalim** [comment]
Thanks @gVirtu! I have pushed a fix but the fix was a bit more complex than I expected, so we won't be backporting it to v1.10, it will be on v1.11. A temporary fix for you is to explicitly pattern match on those values and return the regular atom:

    encoder = fn :fn, _opts -> {:ok, :fn}; atom, _opts -> {:ok, IO.inspect(atom)} end
